### ISSUE TITLE
WDA Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash 

### ISSUE THREAD

**Issue by ekarCumAliORUC** [appium/appium#17007]
Hi, try multiple times, appium and xcode install but I face up with NO WDA device message again and again. 
**My Envirement**
MacBook Air (M1, 2020) version 12.0.1
Appium Desktop 1.19.1 
Xcode 13.0
npm version 8.9.0
node version 16.15.0

And Log as Below

[Appium] Welcome to Appium v1.19.1
[Appium] Non-default server args:
[Appium]   relaxedSecurityEnabled: true
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 7 ms - 40
[HTTP] 
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"app":"/Users/cumalioruc/Library/Developer/Xcode/DerivedData/UIKitCatalog-deduftobbaogjebrmqqwldbbnmoz/Build/Products/Debug-iphonesimulator/UIKitCatalog.app","automationName":"XCUITest","deviceName":"iPhone 12","platformName":"iOS","platformVersion":"15.0","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/cumalioruc/Library/Developer/Xcode/DerivedData/UIKitCatalog-deduftobbaogjebrmqqwldbbnmoz/Build/Products/Debug-iphonesimulator/UIKitCatalog.app","automationName":"XCUITest","deviceName":"iPhone 12","platformName":"iOS","platformVersion":"15.0","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1653891133442 (09:12:13 GMT+0300 (GMT+03:00))
[Appium] Appium v1.19.1 creating new XCUITestDriver (v3.31.1) session
[Appium] Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] Creating session with MJSONWP desired capabilities: {
[BaseDriver]   "app": "/Users/cumalioruc/Library/Developer/Xcode/DerivedData/UIKitCatalog-deduftobbaogjebrmqqwldbbnmoz/Build/Products/Debug-iphonesimulator/UIKitCatalog.app",
[BaseDriver]   "automationName": "XCUITest",
[BaseDriver]   "deviceName": "iPhone 12",
[BaseDriver]   "platformName": "iOS",
[BaseDriver]   "platformVersion": "15.0",
[BaseDriver]   "newCommandTimeout": 0,
[BaseDriver]   "connectHardwareKeyboard": true
[BaseDriver] }
[BaseDriver] Session created with session id: c0a77e8a-3e59-449f-8346-abac45269139
[XCUITest] Current user: 'cumalioruc'
[XCUITest] iOS SDK Version set to '15.0'
[iOSSim] Constructing iOS simulator for Xcode version 13.0 with udid '08E5C5D3-E23F-42EF-B54A-890288357D65'
[XCUITest] Determining device to run tests on: udid: '08E5C5D3-E23F-42EF-B54A-890288357D65', real device: false
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1653891134694 (09:12:14 GMT+0300 (GMT+03:00))
[BaseDriver] Using local app '/Users/cumalioruc/Library/Developer/Xcode/DerivedData/UIKitCatalog-deduftobbaogjebrmqqwldbbnmoz/Build/Products/Debug-iphonesimulator/UIKitCatalog.app'
[BaseDriver] Event 'appConfigured' logged at 1653891134695 (09:12:14 GMT+0300 (GMT+03:00))
[XCUITest] Checking whether app '/Users/cumalioruc/Library/Developer/Xcode/DerivedData/UIKitCatalog-deduftobbaogjebrmqqwldbbnmoz/Build/Products/Debug-iphonesimulator/UIKitCatalog.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/Users/cumalioruc/Library/Developer/Xcode/DerivedData/UIKitCatalog-deduftobbaogjebrmqqwldbbnmoz/Build/Products/Debug-iphonesimulator/UIKitCatalog.app': 'com.example.apple-samplecode.UIKitCatalogJPPZ668T7Y'
[BaseDriver] Event 'resetStarted' logged at 1653891134698 (09:12:14 GMT+0300 (GMT+03:00))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[BaseDriver] Event 'resetComplete' logged at 1653891134953 (09:12:14 GMT+0300 (GMT+03:00))
[WebDriverAgent] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent'
[WebDriverAgent] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[XCUITest] Continuing without capturing device logs: iOS Simulator with udid '08E5C5D3-E23F-42EF-B54A-890288357D65' is not running
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[iOS] Setting did not need to be updated
[iOSSim] Setting preferences of 08E5C5D3-E23F-42EF-B54A-890288357D65 Simulator to {"ConnectHardwareKeyboard":true}
[iOSSim] Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":true}
[iOSSim] Updated 08E5C5D3-E23F-42EF-B54A-890288357D65 Simulator preferences at '/Users/cumalioruc/Library/Preferences/com.apple.iphonesimulator.plist' with {"DevicePreferences":{"08E5C5D3-E23F-42EF-B54A-890288357D65":{"ConnectHardwareKeyboard":true}},"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":true}
[iOSSim] Starting Simulator UI with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 08E5C5D3-E23F-42EF-B54A-890288357D65 -RotateWindowWhenSignaledByGuest 1 -ConnectHardwareKeyboard 1 -PasteboardAutomaticSync 0
[iOSSim] Simulator '08E5C5D3-E23F-42EF-B54A-890288357D65' is already running
[iOSSim] Simulator with UDID 08E5C5D3-E23F-42EF-B54A-890288357D65 booted in 4.377s
[BaseDriver] Event 'simStarted' logged at 1653891139608 (09:12:19 GMT+0300 (GMT+03:00))
[WebDriverAgent] Parsed BUILD_DIR configuration value: '/Users/cumalioruc/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp/Build/Products'
[WebDriverAgent] Got derived data root: '/Users/cumalioruc/Library/Developer/Xcode/DerivedData/WebDriverAgent-alwvnomvwrdtzoaxbbkniqrpcdpp'
[IOSSimulatorLog] Starting log capture for iOS Simulator with udid '08E5C5D3-E23F-42EF-B54A-890288357D65' using simctl
[BaseDriver] Event 'logCaptureStarted' logged at 1653891140214 (09:12:20 GMT+0300 (GMT+03:00))
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneSimulator"]
[XCUITest] Reset requested. Removing app with id 'com.example.apple-samplecode.UIKitCatalogJPPZ668T7Y' from the device
[XCUITest] Installing '/Users/cumalioruc/Library/Developer/Xcode/DerivedData/UIKitCatalog-deduftobbaogjebrmqqwldbbnmoz/Build/Products/Debug-iphonesimulator/UIKitCatalog.app' on Simulator with UUID '08E5C5D3-E23F-42EF-B54A-890288357D65'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1653891142662 (09:12:22 GMT+0300 (GMT+03:00))
[WebDriverAgent] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device 08E5C5D3-E23F-42EF-B54A-890288357D65 on local port 8100
[DevCon Factory] Cached connections count: 0
[DevCon Factory] Successfully requested the connection for 08E5C5D3-E23F-42EF-B54A-890288357D65:8100
[XCUITest] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[WD Proxy] connect ECONNREFUSED 127.0.0.1:8100
[WebDriverAgent] WDA is not listening at 'http://127.0.0.1:8100/'
[WebDriverAgent] WDA is currently not running. There is nothing to cache
[XCUITest] Trying to start WebDriverAgent 2 times with 10000ms interval
[XCUITest] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[BaseDriver] Event 'wdaStartAttempted' logged at 1653891142750 (09:12:22 GMT+0300 (GMT+03:00))
[WebDriverAgent] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Installing/updating dependencies for platforms 'iOS', 'tvOS'
[WebDriverAgent] *** Checking out CocoaAsyncSocket at "72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc"
[WebDriverAgent] *** Checking out YYCache at "1.1.2"
[WebDriverAgent] *** xcodebuild output can be found in /var/folders/24/l6csvsxs7z1gx4j5240j0yz00000gn/T/carthage-xcodebuild.Y8CF0I.log
[WebDriverAgent] *** Building scheme "tvOS Framework" in CocoaAsyncSocket.xcodeproj
[WebDriverAgent] A shell task (/usr/bin/xcrun lipo -create /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/tvOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/appletvos/CocoaAsyncSocket.framework/CocoaAsyncSocket /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-appletvsimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/tvOS/CocoaAsyncSocket.framework/CocoaAsyncSocket) failed with exit code 1:
[WebDriverAgent] fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/tvOS Framework/IntermediateBuildFilesPath/UninstalledProducts/appletvos/CocoaAsyncSocket.framework/CocoaAsyncSocket and /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-appletvsimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket have the same architectures (arm64) and can't be in the same fat output file
[WebDriverAgent] Building universal frameworks with common architectures is not possible. The device and simulator slices for "CocoaAsyncSocket" both build for: arm64
[WebDriverAgent] Rebuild with --use-xcframeworks to create an xcframework bundle instead.
[WebDriverAgent] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Installing/updating dependencies for platforms 'iOS', 'tvOS'
[WebDriverAgent] *** Checking out YYCache at "1.1.2"
[WebDriverAgent] *** Checking out CocoaAsyncSocket at "72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc"
[WebDriverAgent] *** xcodebuild output can be found in /var/folders/24/l6csvsxs7z1gx4j5240j0yz00000gn/T/carthage-xcodebuild.vTTjO2.log
[WebDriverAgent] *** Building scheme "tvOS Framework" in CocoaAsyncSocket.xcodeproj
[WebDriverAgent] A shell task (/usr/bin/xcrun lipo -create /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/tvOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/appletvos/CocoaAsyncSocket.framework/CocoaAsyncSocket /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-appletvsimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/tvOS/CocoaAsyncSocket.framework/CocoaAsyncSocket) failed with exit code 1:
[WebDriverAgent] fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/tvOS Framework/IntermediateBuildFilesPath/UninstalledProducts/appletvos/CocoaAsyncSocket.framework/CocoaAsyncSocket and /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-appletvsimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket have the same architectures (arm64) and can't be in the same fat output file
[WebDriverAgent] Building universal frameworks with common architectures is not possible. The device and simulator slices for "CocoaAsyncSocket" both build for: arm64
[WebDriverAgent] Rebuild with --use-xcframeworks to create an xcframework bundle instead.
[BaseDriver] Event 'wdaStartFailed' logged at 1653891199060 (09:13:19 GMT+0300 (GMT+03:00))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/Scripts/carthage-wrapper.sh bootstrap --platform iOS\,tvOS' exited with code 1
[XCUITest] Quitting and uninstalling WebDriverAgent
[WebDriverAgent] Shutting down sub-processes
[iOSSim] Building bundle path map
[iOSSim] The simulator has '0' bundles which have 'WebDriverAgentRunner-Runner' as their 'CFBundleName':
[WebDriverAgent] No WDAs on the device.
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[GENERIC] Calling AppiumDriver.getSessions() with args: []
[GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 7 ms - 40
[HTTP] 
[BaseDriver] Event 'wdaStartAttempted' logged at 1653891209417 (09:13:29 GMT+0300 (GMT+03:00))
[XCUITest] Retrying WDA startup (2 of 2)
[WebDriverAgent] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Installing/updating dependencies for platforms 'iOS', 'tvOS'
[WebDriverAgent] *** Checking out YYCache at "1.1.2"
[WebDriverAgent] *** Checking out CocoaAsyncSocket at "72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc"
[WebDriverAgent] *** xcodebuild output can be found in /var/folders/24/l6csvsxs7z1gx4j5240j0yz00000gn/T/carthage-xcodebuild.JY3Wbk.log
[WebDriverAgent] *** Building scheme "tvOS Framework" in CocoaAsyncSocket.xcodeproj
[WebDriverAgent] A shell task (/usr/bin/xcrun lipo -create /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/tvOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/appletvos/CocoaAsyncSocket.framework/CocoaAsyncSocket /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-appletvsimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/tvOS/CocoaAsyncSocket.framework/CocoaAsyncSocket) failed with exit code 1:
[WebDriverAgent] fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/tvOS Framework/IntermediateBuildFilesPath/UninstalledProducts/appletvos/CocoaAsyncSocket.framework/CocoaAsyncSocket and /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-appletvsimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket have the same architectures (arm64) and can't be in the same fat output file
[WebDriverAgent] Building universal frameworks with common architectures is not possible. The device and simulator slices for "CocoaAsyncSocket" both build for: arm64
[WebDriverAgent] Rebuild with --use-xcframeworks to create an xcframework bundle instead.
[WebDriverAgent] Launching WebDriverAgent on the device
[WebDriverAgent] Fetching dependencies
[WebDriverAgent] Installing/updating dependencies for platforms 'iOS', 'tvOS'
[WebDriverAgent] *** Checking out CocoaAsyncSocket at "72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc"
[WebDriverAgent] *** Checking out YYCache at "1.1.2"
[WebDriverAgent] *** xcodebuild output can be found in /var/folders/24/l6csvsxs7z1gx4j5240j0yz00000gn/T/carthage-xcodebuild.NoZfDR.log
[WebDriverAgent] *** Building scheme "iOS Framework" in CocoaAsyncSocket.xcodeproj
[WebDriverAgent] A shell task (/usr/bin/xcrun lipo -create /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/iOS\ Framework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaAsyncSocket.framework/CocoaAsyncSocket /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-iphonesimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket -output /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/Carthage/Build/iOS/CocoaAsyncSocket.framework/CocoaAsyncSocket) failed with exit code 1:
[WebDriverAgent] fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Intermediates.noindex/ArchiveIntermediates/iOS Framework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CocoaAsyncSocket.framework/CocoaAsyncSocket and /Users/cumalioruc/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/CocoaAsyncSocket/72e0fa9e62d56e5bbb3f67e9cfd5aa85841735bc/Build/Products/Release-iphonesimulator/CocoaAsyncSocket.framework/CocoaAsyncSocket have the same architectures (arm64) and can't be in the same fat output file
[WebDriverAgent] Building universal frameworks with common architectures is not possible. The device and simulator slices for "CocoaAsyncSocket" both build for: arm64
[WebDriverAgent] Rebuild with --use-xcframeworks to create an xcframework bundle instead.
[BaseDriver] Event 'wdaStartFailed' logged at 1653891269592 (09:14:29 GMT+0300 (GMT+03:00))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/Scripts/carthage-wrapper.sh bootstrap --platform iOS\,tvOS' exited with code 1
[XCUITest] Quitting and uninstalling WebDriverAgent
[WebDriverAgent] Shutting down sub-processes
[iOSSim] Building bundle path map
[iOSSim] The simulator has '0' bundles which have 'WebDriverAgentRunner-Runner' as their 'CFBundleName':
[WebDriverAgent] No WDAs on the device.
[XCUITest] {}
[DevCon Factory] Releasing connections for 08E5C5D3-E23F-42EF-B54A-890288357D65 device on any port number
[DevCon Factory] Found cached connections to release: ["08E5C5D3-E23F-42EF-B54A-890288357D65:8100"]
[DevCon Factory] Cached connections count: 0
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[IOSSimulatorLog] Stopping iOS log capture
[BaseDriver] Event 'newSessionStarted' logged at 1653891269608 (09:14:29 GMT+0300 (GMT+03:00))
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: Command '/bin/bash /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/Scripts/carthage-wrapper.sh bootstrap --platform iOS\,tvOS' exited with code 1
[MJSONWP]     at quitAndUninstall (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:541:15)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:571:11
[MJSONWP]     at wrapped (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:35:13)
[MJSONWP]     at retry (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:18:13)
[MJSONWP]     at retryInterval (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:45:10)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:551:7
[MJSONWP] Destroying socket connection
[HTTP] <-- POST /wd/hub/session 500 136167 ms - 401
[HTTP] 
[HTTP] --> DELETE /wd/hub/session
[HTTP] {}
[HTTP] No route found for /wd/hub/session
[HTTP] <-- DELETE /wd/hub/session 404 21 ms - 211
[HTTP]

**Comment by mykola-mokhnach** [comment]
Please use the most recent server version (e.g. Appuim2 with [Inspector](https://github.com/appium/appium-inspector)).

**Comment by ekarCumAliORUC** [comment]
That works. I spent my all weekend. Finally it works. Thanks for your help....
