### ISSUE TITLE
Safari atoms that trigger alerts never get resolved

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#17013]
## The problem

Any web view atom calls that trigger an alert never get resolved and always fail with a timeout:

```
dbug XCUITestDriver@fe30 (067565ba) Calling XCUITestDriver.click() with args: [":wdc:1653940363891","067565ba-adb5-4542-bf88-6a1e04bdcce7"]
dbug XCUITestDriver@fe30 (067565ba) Executing command 'click'
dbug RemoteDebugger Executing atom 'click' with 'args=[{"ELEMENT":":wdc:1653940363891"}]; frames='
dbug RemoteDebugger Executing 'click' atom in default context
dbug RemoteDebugger Sending javascript command: '(function(){return function(){var h,aa=this;fun...'
dbug RemoteDebugger Sending '_rpc_forwardSocketData:' message to app 'PID:26571', page '1', target 'page-17' (id: 40): 'Runtime.evaluate'

>>> After 1 second timeout

dbug XCUITestDriver@fe30 (067565ba) Matched '/alert/text' to command name 'getAlertText'
dbug XCUITestDriver@fe30 (067565ba) Proxying [GET /alert/text] to [GET http://127.0.0.1:8100/session/EEC9F038-8E4F-4AE8-94C1-C72BE29BF370/alert/text] with no body
dbug XCUITestDriver@fe30 (067565ba) Got response with status 200: {"value":"I am an alert","sessionId":"EEC9F038-8E4F-4AE8-94C1-C72BE29BF370"}
dbug XCUITestDriver@fe30 (067565ba) Encountered internal error running command: UnexpectedAlertOpenError: A modal dialog was open, blocking this operation
dbug XCUITestDriver@fe30 (067565ba)     at EventEmitter.onAlertCallback (/Users/elf/code/appium-xcuitest-driver/lib/commands/web.js:671:38)
dbug XCUITestDriver@fe30 (067565ba)     at Object.onceWrapper (events.js:519:28)
dbug XCUITestDriver@fe30 (067565ba)     at EventEmitter.emit (events.js:400:28)
dbug XCUITestDriver@fe30 (067565ba)     at EventEmitter.emit (domain.js:475:12)
dbug XCUITestDriver@fe30 (067565ba)     at /Users/elf/code/appium-xcuitest-driver/lib/commands/web.js:662:48
dbug XCUITestDriver@fe30 (067565ba)     at processTicksAndRejections (internal/process/task_queues.js:95:5)
info HTTP <-- POST /session/067565ba-adb5-4542-bf88-6a1e04bdcce7/element/%3Awdc%3A1653940363891/click 500 30650 ms - 582
info HTTP 
2022-05-30T19:53:45.380Z ERROR webdriver: Request failed with status 500 due to unexpected alert open: A modal dialog was open, blocking this operation
```

e2e test to reproduce:

https://github.com/appium/appium-xcuitest-driver/pull/1412/files#diff-363736c9bd441093a4fdbf4f11d79afd6c619d7354b120210f42e84a68341130R37

Basically this `click` call always gets stuck until `UnexpectedAlertOpenError` is thrown according to the current logic as the `click` atom promise never gets resolved in https://github.com/appium/appium-xcuitest-driver/blob/29a376521e5d4f107989f863f98c3963214ecbd2/lib/commands/web.js#L638 and then in https://github.com/appium/appium-remote-debugger/blob/906c0ddcb04e03c924a9fb25177cc3478538538e/lib/rpc/rpc-client.js#L282

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta30
* Last Appium version that did not exhibit the issue (if applicable):
* Driver version that exhibits the issue (only for Appium2): 4.4.4
* Last driver version that did not exhibit the issue (if applicable, only for Appium2):
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): 16
* Package manager name and version (we only officially support NPM): npm8
* Mobile platform/version under test: iOS 15.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe:

**Comment by KazuCocoa** [comment]
Let me see if we can do something (just a note comment)

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-remote-debugger/pull/268 is a new PR to update atom.
Afaik, the main motivation to give our own patch in atom before was to handle shadow dom. https://github.com/appium/appium-remote-debugger/blob/master/atoms-notes.md

At least latest selenium clients have shwdow root stuff, https://github.com/SeleniumHQ/selenium/search?q=ShadowRoot, so we need to check, but potentially we can simply keep update selenium atom as-is

**Comment by KazuCocoa** [comment]
https://www.w3.org/TR/webdriver2/#shadow-root
We also need to check client code if they have ShadowRoot stuff. We may removed in our code, btw.

https://github.com/appium/appium/blob/master/packages/base-driver/lib/protocol/routes.js#L281-L295

**Comment by KazuCocoa** [comment]
Note about general atom's status in selenium channel:

https://seleniumhq.slack.com/archives/CBH302726/p1669582115105309

**Comment by jlipps** [comment]
I found a solution for this, I think. PR coming with the atoms update.
