### ISSUE TITLE
Unable to click element with offsets in Windows UWP App

### ISSUE THREAD

**Issue by YenikeRaghuRam** [appium/appium#17016]
## The problem

Automation testing a Windows UWP App
Using below command unable to click on element 5,5 coordinates , it always clicks on middle of element

new TouchAction(Base.uwpDriver).press(ElementOption.element(driver.findElement(object), 5, 5)).perform();

## Environment

* Appium version (or git revision) that exhibits the issue:1.22.3
* Desktop OS/version used to run Appium: Windows 10

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

new TouchAction(Base.uwpDriver).press(ElementOption.element(driver.findElement(object), 5, 5)).perform();

**Comment by mykola-mokhnach** [comment]
Please report this issue to Microsoft. Appium team does not maintain WinAppDriver.
