### ISSUE TITLE
w3c actions appium python

### ISSUE THREAD

**Issue by YenikeRaghuRam** [appium/appium#17019]
## The problem
Require how to w3c actions appium using python

Deprecated Touch action is displayed , didn't find any w3c actions for appium python client [Refer http://appium.io/docs/en/commands/interactions/actions/]

 tas = TouchAction(driver)
    tas.press(e2).perform()

[Deprecated] 'TouchAction' action is deprecated. Please use W3C actions instead.

desired_caps = dict(
    noReset=True,
    clearSystemFiles=True,
    platformName='Windows',
    deviceName='WindowsPC',
    platformVersion='10',
    automationName='Windows',
    createSessionTimeout='60000',
    app="CarrierTransicold.ContainerLINK_b3cjpzkqb6qq2!App",
    forceMjsonwp=True
)

driver = webdriver.Remote('http://localhost:4723', desired_caps)

## Environment

* Appium python client: 2.2.0
* Selenium: 4.1.5
* Device: Windows 10

**Comment by mykola-mokhnach** [comment]
Some examples of W3C actions could be found at 
- https://www.programcreek.com/python/example/100022/selenium.webdriver.ActionChains
- https://github.com/appium/python-client/blob/09a0cd0c72cc9e63c26c516f8bd8a4ac7b211808/appium/webdriver/extensions/action_helpers.py


Kindly use Appium forum to ask questions.
