### ISSUE TITLE
Appium is not providing crash logs for ios real device.

### ISSUE THREAD

**Issue by asolanki-in** [appium/appium#17015]
driver.manage().logs().get('crashlog').getAll();

This code is responding nothing.

At appium side logs i can see AppiumDriver.getLog call and crash id

But no error is printing and even not data is given as app crashed.

I found that without syncing iphone everytime after crash I cannot see crash at folder location in mac.

I am using appium cli 1.22 version
I can run automation but at the time of crash I cannot retrieve crash report.

In simulator working fine

**Comment by mykola-mokhnach** [comment]
Please use the most recent driver version, which is only available in [Appium2](https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli). It supports direct crashes retrieval from real devices, but also requires https://github.com/YueChen-C/py-ios-device tool to be available on the host system.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
