### ISSUE TITLE
Could not load plugin 'relaxed-caps'

### ISSUE THREAD

**Issue by aaroncarry** [appium/appium#17025]
## The problem

Hi, I am facing issue to start the Appium2.0 server using **relaxed-caps** plugin.
but it not be available.

![image](https://user-images.githubusercontent.com/24429337/171381684-5f0d412e-9f4e-4b27-a2bb-3ebcd9f9006e.png)

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v2.0.0-beta.35 (REV 30e3d8883cde265cbc16ff94b49a3ac14137590e)
* Driver version that exhibits the issue (only for Appium2): all
* Desktop OS/version used to run Appium: MacOS 12.1
* Node.js version (unless using Appium.app|exe):v14.19.3
* Package manager name and version (we only officially support NPM):6.14.17
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Detail Log:
https://gist.github.com/aaroncarry/d130d45b5c53c356f0bb225bc832852c

**Comment by aaroncarry** [comment]
> Is it same as #16981 ?

The situation is similar, it seems that the relax-caps plugin cannot be started and the espresso driver prompts a memory leak detect.

I not sure, but it seems #16981 appears in Appium server which on the windows platform and the error stack is somewhat different

**Comment by jlipps** [comment]
Can you please uninstall appium and completely blow away your appium home dir (usually ~/.appium unless you changed it), then reinstall everything and report back?

**Comment by aaroncarry** [comment]
> Can you please uninstall appium and completely blow away your appium home dir (usually ~/.appium unless you changed it), then reinstall everything and report back?

I will try it later, thx for you suggestion

**Comment by aaroncarry** [comment]
> > Can you please uninstall appium and completely blow away your appium home dir (usually ~/.appium unless you changed it), then reinstall everything and report back?
> 
> I will try it later, thx for you suggestion

Unfortunately, reinstall Appium didn't solve the problem, it introduced new problems

https://gist.github.com/aaroncarry/b960fe560df741c33369d06b0d33bd6a

**Comment by jlipps** [comment]
@aaroncarry you did completely remove your APPIUM_HOME dir before this?

**Comment by aaroncarry** [comment]
> @aaroncarry you did completely remove your APPIUM_HOME dir before this?

Yes,,i didn't. I remove /Users/xxx/.appium folder before this

**Comment by jlipps** [comment]
just released appium 2 beta 40 with some additional fixes. please try again!

**Comment by jlipps** [comment]
@aaroncarry which version of the relaxed caps plugin are you using?

**Comment by aaroncarry** [comment]
> @aaroncarry which version of the relaxed caps plugin are you using?

@jlipps relaxed-caps@1.0.0-beta.9

**Comment by jlipps** [comment]
@boneskull what do you think could be going on here? this version of the relaxed caps plugin has the peer dep listed and appium 2 beta 40 should have all the exports for `appium/plugin`, right?

**Comment by boneskull** [comment]
@jlipps Can you reproduce this?

**Comment by boneskull** [comment]
anyway, will take a look

**Comment by linyayu** [comment]
> 
NPM version is 6.14.17,
Some versions of NPM do not automatically install peer dep

**Comment by jlipps** [comment]
No, I could not repro this myself.

**Comment by boneskull** [comment]
Neither can I.

@linyayu It shouldn't matter.

@aaroncarry To help diagnose, can you please paste the following information (assuming you are using a bash-compatible shell):

1. The result of `appium --version`
2. The result of `appium plugin list`
3.  The result of `which appium`
4. The result of `echo ${APPIUM_HOME:-~/.appium}`
5. The result of `cat ${APPIUM_HOME:-~/.appium}/package.json` 
6. The result of `cat ${APPIUM_HOME:-~/appium}/node_modules/.cache/appium/extensions.yaml`

**Comment by boneskull** [comment]
I suspect that you may have multiple copies of `appium` installed, and one of those is old.

**Comment by KazuCocoa** [comment]
The same error occurred in ruby_lib_core test suite.

https://gist.github.com/KazuCocoa/bd4e4e369807c49cf60dcfe0b0e50ac1

https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=21877&view=logs&j=bc41d514-1fb7-52e0-ac21-52379c69d731&t=e031ff12-7537-59cb-505f-2b29adeae0e5 is `appium plugin list` etc.
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=21877&view=artifacts&pathAsName=false&type=publishedArtifacts has appium server log. ("func_test_ios_opencv")

https://github.com/appium/ruby_lib_core/pull/387 is the PR to show information. `ci-jobs/functional/run_appium.yml` is the preparation code. Feel free to modify the branch if you want.

**Comment by KazuCocoa** [comment]
Maybe is this because of `npm` version?
When I installed plugins with npm v8 and nodejs v14 on my local, it worked. But npm v6 (default npm version in nodejs 14) got the error. Actually the Azure environment also npm v6 since the environment used vanilla NodeJS v14. (did not update npm)

**Comment by aaroncarry** [comment]
> Neither can I.
> 
> @linyayu It shouldn't matter.
> 
> @aaroncarry To help diagnose, can you please paste the following information (assuming you are using a bash-compatible shell):
> 
> 1. The result of `appium --version`
> 2. The result of `appium plugin list`
> 3. The result of `which appium`
> 4. The result of `echo ${APPIUM_HOME:-~/.appium}`
> 5. The result of `cat ${APPIUM_HOME:-~/.appium}/package.json`
> 6. The result of `cat ${APPIUM_HOME:-~/appium}/node_modules/.cache/appium/extensions.yaml`
> 7. The result of `ls ${APPIUM_HOME:-~/appium}/node_modules`

sure.  
https://gist.github.com/aaroncarry/74cb91d66e1183f5c6b2383bdbd500da

In case of error, "appium": "^2.0.0-beta.40" is not included in package.json file.
After I add it to package.json and execute npm install, the relax-caps plugin can be loaded normally

**Comment by aaroncarry** [comment]
> Maybe is this because of `npm` version? When I installed plugins with npm v8 and nodejs v14.19.0 on my local, it worked. But npm v6 (default npm version in nodejs 14) with nodejs v14.19.3 got the error. Actually the Azure environment also npm v6 since the environment used vanilla NodeJS v14. (did not update npm)
> 
> If the environment already had npm v8 installed drivers/plugins, the npm v6 env also had no issue.

I also suspect it may because of npm version, my local npm version is `6.14.17`

**Comment by jlipps** [comment]
@aaroncarry can you upgrade npm, clear everything out, and try again?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
