### ISSUE TITLE
beta.37 - driver / plugin installation

### ISSUE THREAD

**Issue by StephanB75** [appium/appium#17026]
## The problem

my driver /plugin installation seems not to work anymore.
I tried to follow the discussion around the big changes but i have no clue what i do have to change.

Until now i have installed everything via "npm install" into the default [UserDir]/.appium folder
and a postinstallscript which deletes old drivers and plugins infront of installing them freshly.

"postinstall": "npx appium plugin uninstall images || true && npx appium driver uninstall uiautomator2 || true && npx appium driver install uiautomator2 || true && npx appium plugin install images || true"

Also installing drivers and images over cli command "appium driver install uiautomator" does result in the same.

## Environment

* Appium version (or git revision) that exhibits the issue: beta.37
* Last Appium version that did not exhibit the issue (if applicable): beta 35
* Driver version that exhibits the issue (only for Appium2): 
* Last driver version that did not exhibit the issue (if applicable, only for Appium2):
* Desktop OS/version used to run Appium: Monterey
* Node.js version (unless using Appium.app|exe):  14.18.1
* Package manager name and version (we only officially support NPM): npm 6.14.15
* Mobile platform/version under test: iOS/Android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

Every driver and plugin throws this kind of error

WARN Appium Appium encountered 2 warnings while validating plugins found in manifest /Users/stephan.b/.appium/node_modules/.cache/appium/extensions.yaml
WARN Appium Plugin "images" has 1 potential problem: 
WARN Appium   - Plugin "images" (package `@appium/images-plugin`) may be incompatible with the current version of Appium (v2.0.0-beta.37) due to an invalid or missing peer dependency on Appium. A newer version of `@appium/images-plugin` is available; please attempt to upgrade "images" to v1.3.1 or newer.

WARN Appium Driver "uiautomator2" has 1 potential problem: 
WARN Appium   - Driver "uiautomator2" (package `appium-uiautomator2-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.37) due to an invalid or missing peer dependency on Appium. A newer version of `appium-uiautomator2-driver` is available; please attempt to upgrade "uiautomator2" to v2.2.0 or newer.

**Comment by StephanB75** [comment]
additional log/stacktrace from appium startup:

2022-06-01 13:20:51:528 - Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'UiAutomator2' and platformName android'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Cannot find module 'log-symbols'
Require stack:
- /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/build/lib/console.js
- /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/build/lib/index.js
- /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/index.js
- /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/logger.js
- /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/desired-caps.js
- /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/capabilities.js
- /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js
- /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/index.js
- /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/index.js
- /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/build/lib/driver.js
- /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/build/index.js
- /Users/stephan.b/git/rossmann-android-uitesting-java/node_modules/appium/build/lib/extension/extension-config.js
- /Users/stephan.b/git/rossmann-android-uitesting-java/node_modules/appium/build/lib/cli/extension-command.js
- /Users/stephan.b/git/rossmann-android-uitesting-java/node_modules/appium/build/lib/cli/driver-command.js
- /Users/stephan.b/git/rossmann-android-uitesting-java/node_modules/appium/build/lib/cli/extension.js
- /Users/stephan.b/git/rossmann-android-uitesting-java/node_modules/appium/build/lib/main.js
- /Users/stephan.b/git/rossmann-android-uitesting-java/node_modules/appium/index.js)

**Comment by StephanB75** [comment]
npm install appium with "npm install appium@2.0.0-beta.37 --drivers=uiautomator2 --plugins=images"
does looks good while driver installation, but when starting the tests i get also errors

2022-06-01 13:36:22:233 - [Appium] Attempting to load driver uiautomator2...
2022-06-01 13:36:22:272 - [debug] [Appium] Requiring driver at /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver
2022-06-01 13:36:23:391 - [Appium] Could not load driver 'uiautomator2', so it will not be available. Error in loading the driver was: Cannot find module 'log-symbols'
2022-06-01 13:36:23:392 - [Appium] Require stack:
2022-06-01 13:36:23:392 - [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/build/lib/console.js
2022-06-01 13:36:23:392 - [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/build/lib/index.js
2022-06-01 13:36:23:392 - [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/index.js
2022-06-01 13:36:23:393 - [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/logger.js
2022-06-01 13:36:23:393 - [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/desired-caps.js
2022-06-01 13:36:23:393 - [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/capabilities.js
2022-06-01 13:36:23:393 - [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js
2022-06-01 13:36:23:393 - [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/index.js
2022-06-01 13:36:23:394 - [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/index.js
2022-06-01 13:36:23:394 - [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/build/lib/driver.js
2022-06-01 13:36:23:394 - [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/build/index.js
2022-06-01 13:36:23:394 - [Appium] - /Users/stephan.b/git/rm-android-uitesting-java/node_modules/appium/build/lib/extension/extension-config.js
2022-06-01 13:36:23:394 - [Appium] - /Users/stephan.b/git/rm-android-uitesting-java/node_modules/appium/build/lib/cli/extension-command.js
2022-06-01 13:36:23:394 - [Appium] - /Users/stephan.b/git/rm-android-uitesting-java/node_modules/appium/build/lib/cli/driver-command.js
2022-06-01 13:36:23:395 - [Appium] - /Users/stephan.b/git/rm-android-uitesting-java/node_modules/appium/build/lib/cli/extension.js
2022-06-01 13:36:23:395 - [Appium] - /Users/stephan.b/git/rm-android-uitesting-java/node_modules/appium/build/lib/main.js
2022-06-01 13:36:23:395 - [Appium] - /Users/stephan.b/git/rm-android-uitesting-java/node_modules/appium/index.js

**Comment by jlipps** [comment]
@StephanB75 can you completely remove your APPIUM_HOME (usually `~/.appium`) and uninstall appium, then try again:

```
rm -rf ~/.appium
npm uninstall -g appium
npm install -g appium@next
appium driver install uiautomator2
appium plugin install images
```

**Comment by jlipps** [comment]
btw, if you are using npm , you should not be messing with `~/.appium`. that is a directory reserved for using the appium CLI tools. if you want to use NPM then manage everything in your own project directory including local appium installation.

**Comment by StephanB75** [comment]
@jlipps 
still same result

Installation log :
`
npm uninstall appium
npm WARN appium_installation@1.0.0 No description

removed 436 packages and audited 345 packages in 8.354s

138 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm install -g appium@next

/usr/local/bin/appium -> /usr/local/lib/node_modules/appium/index.js

> appium@2.0.0-beta.38 postinstall /usr/local/lib/node_modules/appium
> node ./scripts/autoinstall-extensions.js

[Appium] ✔ Appium installation OK
[Appium] Found local Appium installation; skipping automatic installation of extensions.
+ appium@2.0.0-beta.38
added 454 packages from 413 contributors in 226.98s

appium driver install uiautomator2
✔ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
⚠ Driver "uiautomator2" has 1 potential problem: 
  - Driver "uiautomator2" (package `appium-uiautomator2-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.38) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-uiautomator2-driver` to add a peer dependency on `^appium@2.0.0-beta.38`.
ℹ Driver uiautomator2@2.2.0 successfully installed
- automationName: UiAutomator2
- platformNames: ["Android"]
stephan.b@MB-033 rm-android-uitesting-java % appium plugin install images
WARN Appium Appium encountered 2 warnings while validating drivers found in manifest /Users/stephan.b/.appium/node_modules/.cache/appium/extensions.yaml
WARN Appium Driver "uiautomator2" has 1 potential problem: 
WARN Appium   - Driver "uiautomator2" (package `appium-uiautomator2-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.38) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-uiautomator2-driver` to add a peer dependency on `^appium@2.0.0-beta.38`.
✔ Installing 'images' using NPM install spec '@appium/images-plugin'
ℹ Plugin images@1.3.2 successfully installed
`

**Comment by StephanB75** [comment]
on starting the tests i get also the same error with identical stacktrace

2022-06-02 07:17:46:957 - [Appium] Attempting to load driver uiautomator2...
2022-06-02 07:17:46:972 - [debug] [Appium] Requiring driver at /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver
2022-06-02 07:17:47:901 - [Appium] Could not load driver 'uiautomator2', so it will not be available. Error in loading the driver was: Cannot find module 'log-symbols'

**Comment by StephanB75** [comment]
also simply starting appiun from terminal with command "appium" throws errors

appium
WARN Appium Appium encountered 2 warnings while validating drivers found in manifest /Users/stephan.b/.appium/node_modules/.cache/appium/extensions.yaml
WARN Appium Driver "uiautomator2" has 1 potential problem: 
WARN Appium   - Driver "uiautomator2" (package `appium-uiautomator2-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.38) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-uiautomator2-driver` to add a peer dependency on `^appium@2.0.0-beta.38`.
[Appium] Welcome to Appium v2.0.0-beta.38
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver
[Appium] Could not load driver 'uiautomator2', so it will not be available. Error in loading the driver was: Cannot find module 'log-symbols'
[Appium] Require stack:
[Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/build/lib/console.js
[Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/build/lib/index.js
[Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/index.js
[Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/logger.js
[Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/desired-caps.js
[Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/capabilities.js
[Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js
[Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/index.js
[Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/index.js
[Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/build/lib/driver.js
[Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/build/index.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/extension/extension-config.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension-command.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/driver-command.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/main.js
[Appium] - /usr/local/lib/node_modules/appium/index.js
[debug] [Appium] Error: Cannot find module 'log-symbols'
[debug] [Appium] Require stack:
[debug] [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/build/lib/console.js
[debug] [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/build/lib/index.js
[debug] [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/index.js
[debug] [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/logger.js
[debug] [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/desired-caps.js
[debug] [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/capabilities.js
[debug] [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/basedriver/driver.js
[debug] [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/build/lib/index.js
[debug] [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/index.js
[debug] [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/build/lib/driver.js
[debug] [Appium] - /Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/build/index.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/extension/extension-config.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension-command.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/driver-command.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/main.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/index.js
[debug] [Appium]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:974:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:93:18)
[debug] [Appium]     at Object.<anonymous> (/Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/lib/console.js:5:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:950:32)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:974:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:93:18)
[debug] [Appium]     at Object.<anonymous> (/Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/lib/index.js:16:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:950:32)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:974:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:93:18)
[debug] [Appium]     at Object.<anonymous> (/Users/stephan.b/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/index.js:1:18)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:950:32)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - uiautomator2@2.2.0 (automationName 'UiAutomator2')
[Appium] Available plugins:
[Appium]   - images@1.3.2
[Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate

**Comment by StephanB75** [comment]
ok i got it running.
1) set the appium home also to my project root directory
2) installed appium into my project folder (as before)
3) installed drivers also into the project folder

But i still have no clue why at least the global installation of appium did not work.

**Comment by jlipps** [comment]
@StephanB75 let's try the global installation again. please follow these steps:

1. move out of your project directory entirely to somewhere else on your system `cd ~`
2. uninstall appium `npm uninstall -g appium`
3. unset APPIUM_HOME `export APPIUM_HOME=""`
4. `rm -rf ~/.appium`
5. install appium `npm install -g appium@next`
6. confirm no drivers/plugins installed `appium driver list` (should show none installed)
7. install driver `appium driver install uiautomator2`
8. run appium `appium`

what happens when you do these steps?

**Comment by StephanB75** [comment]
ok that seems to work, looks like i had still an APPIUM_HOME envvar in my .zshrc with path to "userdir/.appium" on my last global installation
