### ISSUE TITLE
Appium stop working with iOS on MacOS 12.3

### ISSUE THREAD

**Issue by Biloleg** [appium/appium#17031]
## The problem

Since Mac OS 12.3 python 2 by path usr/bin/python was replaced by Python 3 with path usr/bin/python3
Directory usr/bin/python doesn't exist anymore and can't be created as a protected system directory.

When trying to run any test on a real iOS device or iOS Simulator I get an error:
"org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command '/usr/bin/python' not found. Is it installed?"

Any installation of Python2 and adding it to any System path didn't fix a problem.

Looks like WebDriver is looking for usr/bin/python directory only ignoring any System variables and installed python2

Issue reproduced on any call of embedded selenium-remote-driver (3.141.59)
For example: getDriver().setLocation(53.3453, -1.4532, 0);

## Environment

* Appium version (or git revision) that exhibits the issue: GUI appium version 1.22.3-4 + server 1.22.2 and appium console server 1.22.0
* Last Appium version that did not exhibit the issue (if applicable): no one
* Driver version that exhibits the issue (only for Appium2): all (Mac OS version depends)
* Last driver version that did not exhibit the issue (if applicable, only for Appium2): no one
* Desktop OS/version used to run Appium: Mac OS 12.3 (Doesn't reproduce on Mac OS 12.2 and older)
* Node.js version (unless using Appium.app|exe):
* Package manager name and version (we only officially support NPM):
* Mobile platform/version under test: iOS any version
* Real device or emulator/simulator: real device and simulator
* Appium CLI or Appium.app|exe: io.appium java-client 8.1.0
* Java 8

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
Intelij IDEA log
https://gist.github.com/nebesionok/cd9b51bd623e51f4a74673d8c22151be

Appium console server log
https://gist.github.com/nebesionok/16b66adde3fe80281d4402a520d2b049

**Comment by amar1989** [comment]
Do I need to update Appium library for that ? as i am facing exact issue in mac while setting location 
getDriver().setLocation()

**Comment by KazuCocoa** [comment]
I wonder creating a symlink helps for it as a workaround

**Comment by amar1989** [comment]
I updated appium using `npm install appium -g` but still getting same error , I think appium did not get updated.

**Comment by KazuCocoa** [comment]
Newer versions are available via appium 2. You can get it via npm as `appium@next`.

**Comment by amar1989** [comment]
Thanks a lot for quick response !! Updated but seems lot of change is required for appium 2.0, had to revert that for now. Any other workaround plz for version 1.22.3?

**Comment by Biloleg** [comment]
> Do I need to update Appium library for that ? as i am facing exact issue in mac while setting location getDriver().setLocation()
> 
> **@Biloleg** have you been able to resolve the issue?

No, it is impossible to resolve.  Also setLocation() it is just an example but not only one method which crashing run by python path error

**Comment by mykola-mokhnach** [comment]
Unfortunately we don't provide patches for older Appium versions. Closed as fixed

**Comment by Biloleg** [comment]
> Unfortunately we don't provide patches for older Appium versions. Closed as fixed

But we are using latest version of Appium

**Comment by mykola-mokhnach** [comment]
> > Unfortunately we don't provide patches for older Appium versions. Closed as fixed
> 
> But we are using latest version of Appium

Currently the most recent xcuitest driver version is 4.4.5. It is only available as part of Appium2. Appium1 is is legacy and not maintained anymore

**Comment by peterlight90** [comment]
@KazuCocoa When I try set location on Appium2 this issue appear, do you have any advice?
 
![Screen Shot 2022-08-18 at 16 47 13](https://user-images.githubusercontent.com/32845863/185365579-e199eca7-3ed6-4191-80a3-0ed275e8f108.png)

**Comment by Biloleg** [comment]
> @KazuCocoa When I try set location on Appium2 this issue appear, do you have any advice?
> 
> ![Screen Shot 2022-08-18 at 16 47 13](https://user-images.githubusercontent.com/32845863/185365579-e199eca7-3ed6-4191-80a3-0ed275e8f108.png)

@peterlight90 only one way it is use appium 2.0

**Comment by mykola-mokhnach** [comment]
It looks like Apple has excluded pyobjc from the standard python deployment
We need to avoid python usage in general for such scenarios

**Comment by peterlight90** [comment]
Thank you @mykola-mokhnach setLocation function is working well on MacOS latest version (12.5.1)

**Comment by mykola-mokhnach** [comment]
Closed as fixed
