### ISSUE TITLE
click does not work on tvOS 

### ISSUE THREAD

**Issue by raamojirao** [appium/appium#17030]
## The problem

click command navigates to the required element but fails while clicking on it

## Environment

* appium_lib (12.0.1)
* appium_lib_core (5.1.1)
* selenium-webdriver (4.1.0)
* appium version - 1.22.3

## Code
```
desired_caps = {
      caps:       {
          platformName: 'tvOS',
          deviceName: 'AppleTV',
          bundleId: 'XXXX',
          udid: 'XXXXX',
          platformVersion: '15.2',
          agentPath: '/usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'

      },
      appium_lib: {
          server_url: 'http://localhost:4723/wd/hub'
      }
  }
  @driver = Appium::Driver.new(desired_caps)
  @driver.start_driver.manage.timeouts.implicit_wait = 10

  wait = Selenium::WebDriver::Wait.new(:timeout => 30)
  wait.until { @driver.find_element(:name, "Home").displayed? }
  @driver.execute_script 'mobile: pressButton', { name: 'left' }
  sleep(5)
  element = @driver.find_element(:accessibility_id, 'My Library')
  element.focused
  element.click
```

`element.click` navigates to `My Library` element but throws below mentioned error while clicking on it

![Screen Shot 2022-06-01 at 10 39 03 PM](https://user-images.githubusercontent.com/21014170/171543961-41612852-7164-4a95-b9d0-a0637802057a.png)

Please help!

**Comment by mykola-mokhnach** [comment]
Please provide the full server log along with xcodebuild logs

**Comment by mykola-mokhnach** [comment]
According to the current logic click only works if the destination is enabled and if it contains the current input focus. If any of these conditions is not satisfied then the above exception is thrown.

**Comment by mykola-mokhnach** [comment]
it must be both enabled and focused

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
