### ISSUE TITLE
How to access the windows outside the current app 

### ISSUE THREAD

**Issue by BISTArk** [appium/appium#17042]
## I want to access the elements outside the child tree of my main window, is it possible to do with appium?

For example, 
In the picture of inspect.exe shown below  assume,I have started the appium server with app capability as the path to the command prompt (App1) I have clicked a button in the command prompt window(App1) which opens a child process "untitled- Notepad " window(window2) even though the notepad(window2) is launched from command prompt(App1) , the window2 is not a child of window1(as seen in the picture). Is there any way to access the window2 using appium when the driver capability has the app as App1?

Basically, can i access the sibling windows that appear in the inspect tool from a driver with app capability as one of those apps?
![inspect](https://user-images.githubusercontent.com/65766420/172229698-71a6a017-3b91-4aba-9d06-c35b88426c2b.png)

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.
Regarding this particular issue I would also try to ask at https://github.com/microsoft/WinAppDriver as the Appium team neither maintains this component nor has access to its sources.
