### ISSUE TITLE
Mobile Tests Behind a Proxy

### ISSUE THREAD

**Issue by benwalpole** [appium/appium#17044]
## The problem

We are trying to run some automated tests for our Xamarin based iOS app using the IOSDriver within Visual Studio for Mac.

The error we are getting when we run them is (I've sanitised to remove the URL we are actually trying to send the request to).

A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL https://<Test Host URL>. The status of the exception was NameResolutionFailure, and the message was: nodename nor servname provided, or not known nodename nor servname provided, or not known

Because our machines are behind a proxy we often see DNS errors like this when the code sending the request is unaware of the proxy.

We've tried various approached to setting the proxy, such as HttpClient.DefaultProxy and OpenQA.Selenium.Proxy but the error still persists.

Are there any other ways to tell the tests that they are operating behind a proxy?

## Environment

* Appium version (or git revision) that exhibits the issue: 4.2.1
* Last Appium version that did not exhibit the issue (if applicable):
* Driver version that exhibits the issue (only for Appium2):
* Last driver version that did not exhibit the issue (if applicable, only for Appium2):
* Desktop OS/version used to run Appium: OS X 11.6
* Node.js version (unless using Appium.app|exe):
* Package manager name and version (we only officially support NPM): NuGet
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator 
* Appium CLI or Appium.app|exe: Visual Studio

**Comment by mykola-mokhnach** [comment]
Unfortunately Appium does not provide support to proxies.

**Comment by mykola-mokhnach** [comment]
There are multiple places where this is done. Basically the proxy support is missing as the part of the general server architecture, where there must be a centralised proxy settings store initialized based on the session capabilities  and each driver would respect these. Local patches here and there won't help to resolve the issue.

**Comment by StephanB75** [comment]
Would it be possible to go around this issue with an own proxy (like charles proxy) on the local machine, so that all traffic is going over the local proxy which routes it over your company proxy ?

**Comment by StephanB75** [comment]
ok, i only came on this idea, because i use the charles proxy for routing my mac traffic over it and this can than also routet over the company proxy. But i don't use it with appium, because i mock the complete traffic. Maybe this could also be a solution to use a mock server if you don't want to test the backend

**Comment by benwalpole** [comment]
That's the problem it's not HTTP requests coming from the app itself that are the problem, we would mock those. Its the requests Appian is sending in order to run the tests and unfortunately it's not an option to run the server on the client.

**Comment by mykola-mokhnach** [comment]
We are not going to consider such feature in the foreseeable future
