### ISSUE TITLE
Android OS 11 - Unable to perform keyboard action using executeScript

### ISSUE THREAD

**Issue by KritikaSahare1611** [appium/appium#17059]
## The problem

Unable to perform the keyboard actions by using the executeScript option. Below is the sample code

driver.executeScript(“mobile: performEditorAction”, ImmutableMap.of(“action”, “search”));

The same code is working fine on Android 10 or below OS versions.

## Environment

Android

##Logs - 

org.openqa.selenium.WebDriverException: Appium error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'android-sdk/platform-tools/adb -P 5037 -s R5CT238S5CP shell ime set io.appium.settings/.AppiumIME' exited with code 255'; Stderr: 'Unknown input method io.appium.settings/.AppiumIME cannot be selected for user #0'; Code: '255' (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'TECH-KRITIKAS', ip: '172.30.144.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '16.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {64bit: false, acceptSslCert: false, acceptSslCerts: false, adbExecTimeout: 120000, appActivity: com.healthkart.healthkart.r..., appPackage: com.healthkart.healthkart, autoGrantPermissions: true, automationName: uiautomator2, browserstack-tunnel: true, browserstack.appium_version: 1.17.0, browserstack.is_hub_canary: false, browserstack.minOSVersion: 5.0, buildName: Java Android, bundleID: com.healthkart.healthkart, bundleId: com.healthkart.healthkart, cap_browserstack.idleTimeout: 300, capabilities: {64bit: false, acceptSslCert: false, acceptSslCerts: false, adbExecTimeout: 120000, appActivity: com.healthkart.healthkart.r..., appPackage: com.healthkart.healthkart, autoGrantPermissions: true, automationName: uiautomator2, browserstack-tunnel: true, browserstack.appium_version: 1.17.0, browserstack.is_hub_canary: false, browserstack.minOSVersion: 5.0, buildName: Java Android, bundleID: com.healthkart.healthkart, bundleId: com.healthkart.healthkart, cap_browserstack.idleTimeout: 300, chromeOptions: {w3c: false}, chromedriverPort: 18082, chromedriverPorts: [[18122, 18132]], customFullReset: true, databaseEnabled: false, desired: {64bit: false, acceptSslCert: false, acceptSslCerts: false, adbExecTimeout: 120000, appActivity: com.healthkart.healthkart.r..., appPackage: com.healthkart.healthkart, autoGrantPermissions: true, automationName: uiautomator2, browserstack-tunnel: true, browserstack.appium_version: 1.17.0, browserstack.is_hub_canary: false, browserstack.minOSVersion: 5.0, buildName: Java Android, bundleID: com.healthkart.healthkart, bundleId: com.healthkart.healthkart, cap_browserstack.idleTimeout: 300, chromeOptions: {w3c: false}, chromedriverPort: 18082, chromedriverPorts: [[18122, 18132]], customFullReset: true, detected_language: selenium/3.141.59 (java win..., device: samsung galaxy s22 ultra, deviceName: Android, disableSuppressAccessibilityService: true, enablePerformanceLogging: false, mobile: {browser: mobile, version: Samsung Galaxy S22 Ultra-12.0}, nativeWebScreenshot: true, newCommandTimeout: 0, new_bucketing: true, normalizeTagNames: true, orig_os: android, osVersion: 12.0, os_version: 12.0, platform: ANDROID, platformName: Android, projectName: Android Suite Master, realMobile: true, resetKeyboard: true, sessionName: testPromptOrderPlaceCOD, skipServerInstallation: true, systemPort: 8202, udid: R5CT238S5CP, uiautomator2ServerLaunchTimeout: 60000, unicodeKeyboard: false, version: }, detected_language: selenium/3.141.59 (java win..., device: samsung galaxy s22 ultra, deviceApiLevel: 31, deviceManufacturer: samsung, deviceModel: SM-S908E, deviceName: R5CT238S5CP, deviceScreenDensity: 450, deviceScreenSize: 1080x2316, deviceUDID: R5CT238S5CP, disableSuppressAccessibilityService: true, enablePerformanceLogging: false, javascriptEnabled: true, locationContextEnabled: false, mobile: {browser: mobile, version: Samsung Galaxy S22 Ultra-12.0}, nativeWebScreenshot: true, networkConnectionEnabled: true, newCommandTimeout: 0, new_bucketing: true, normalizeTagNames: true, orig_os: android, osVersion: 12.0, os_version: 12.0, pixelRatio: 2.8125, platform: ANDROID, platformName: Android, platformVersion: 12, projectName: Android Suite Master, realMobile: true, resetKeyboard: true, sessionId: 48fe489d025c30c9dfa39e9ebbe..., sessionName: testPromptOrderPlaceCOD, skipServerInstallation: true, statBarHeight: 75, systemPort: 8202, takesScreenshot: true, udid: R5CT238S5CP, uiautomator2ServerLaunchTimeout: 60000, unicodeKeyboard: false, version: , viewportRect: {height: 2031, left: 0, top: 75, width: 1080}, warnings: {}, webStorageEnabled: false}, chromeOptions: {w3c: false}, chromedriverPort: 18082, chromedriverPorts: [[18122, 18132]], customFullReset: true, databaseEnabled: false, detected_language: selenium/3.141.59 (java win..., device: samsung galaxy s22 ultra, deviceApiLevel: 31, deviceManufacturer: samsung, deviceModel: SM-S908E, deviceName: R5CT238S5CP, deviceScreenDensity: 450, deviceScreenSize: 1080x2316, deviceUDID: R5CT238S5CP, disableSuppressAccessibilityService: true, enablePerformanceLogging: false, javascriptEnabled: true, locationContextEnabled: false, mobile: {browser: mobile, version: Samsung Galaxy S22 Ultra-12.0}, nativeWebScreenshot: true, networkConnectionEnabled: true, newCommandTimeout: 0, new_bucketing: true, normalizeTagNames: true, orig_os: android, osVersion: 12.0, os_version: 12.0, pixelRatio: 2.8125, platform: ANDROID, platformName: Android, platformVersion: 12, projectName: Android Suite Master, realMobile: true, resetKeyboard: true, sessionId: 48fe489d025c30c9dfa39e9ebbe..., sessionName: testPromptOrderPlaceCOD, skipServerInstallation: true, statBarHeight: 75, systemPort: 8202, takesScreenshot: true, udid: R5CT238S5CP, uiautomator2ServerLaunchTimeout: 60000, unicodeKeyboard: false, version: , viewportRect: {height: 2031, left: 0, top: 75, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 48fe489d025c30c9dfa39e9ebbec69358214410f

**Comment by mykola-mokhnach** [comment]
@KazuCocoa I saw you were mentioning this adb issue while checking compat with Android11. Are there are known workarounds?

**Comment by mykola-mokhnach** [comment]
Please provide the full server log. Also it makes sense to try the most recent driver version (only available in Appium2)

**Comment by KazuCocoa** [comment]
Yes, I saw the IME change error in Android 13 beta check (on an emulator) recently. At that time, the error had gone after a few retrials.

I wonder if it has a case the system needs to enable it manually once. Then, you could try to enable the keyboard once from settings -> system -> keyboard (this flow could differ from devices).

**Comment by KazuCocoa** [comment]
I don't remember well, but i also maybe tried to call `adb -P 5037 -s R5CT238S5CP shell ime set io.appium.settings/.AppiumIME` by manual to check the error. But it worked at that time.

**Comment by mykola-mokhnach** [comment]
Closed because oof no response
