### ISSUE TITLE
Making Android MJPEG server accessible remotely?

### ISSUE THREAD

**Issue by seanmajorpayne** [appium/appium#17062]
## The problem

I am supplying a custom MJPEG server port (9100) via the capabilities for some tests. With iOS, this port is accessible remotely, but with Android it appears to only be accessible locally. If I run a curl request from within the instance, I can get image streaming data from port 9100, but remotely this results in a `connection refused` error.

My understanding is that this is due to the actual server being port forwarded locally (from 7810). Is there a recommended way to make the MJPEG stream available remotely for android?

**Comment by mykola-mokhnach** [comment]
We use `adb` to perform port forwarding. It only forwards to localhost as it is the right (and secure) way to do it. 

Perhaps, you could directly connect to the device using its IP address or expose the locally forwarded port as a possible workaround.
Please use Appium forum to ask questions
