### ISSUE TITLE
Appium server is hanging after switching to webview in hybrid app

### ISSUE THREAD

**Issue by SubbuLomada** [appium/appium#17066]
## The problem

If we are running scripts for hybrid app we need to switch from native to webview and webview to native. If we switch from Native to webview then appium server is hanging and no logs are rolling.

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta. 40
* Last Appium version that did not exhibit the issue (if applicable): 1.22.0+
* Driver version that exhibits the issue (only for Appium2): 2.0.7(uiautomator2)
* Last driver version that did not exhibit the issue (if applicable, only for Appium2):
* Desktop OS/version used to run Appium: MAC OS Monterey
* Node.js version (unless using Appium.app|exe): 16.14.2
* Package manager name and version (we only officially support NPM):
* Mobile platform/version under test: Android and OS 12
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI
* Java Client : 7.6.0

## Link to Appium logs
There is no logs getting rolled for this issue

## Code To Reproduce Issue [ Good To Have ]
try to use switchcontext in hybrid to webview and try to click on any element

**Comment by mykola-mokhnach** [comment]
Closed because of no response
