### ISSUE TITLE
element not found , Expected condition failed: waiting for visibility of element, when trying to find elements in webview on android app

### ISSUE THREAD

**Issue by dinesh1784393** [appium/appium#17065]
problem :
element not found , Expected condition failed: waiting for visibility of element ,when trying to find elements in webview on android app

code:
package moalaunch;

import org.testng.annotations.Test;
import java.util.Iterator;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.core.env.SystemEnvironmentPropertySource;
import org.testng.annotations.Test;

public class Topup extends Base {

	@Test
	public void launch() throws InterruptedException{
		

     	driver.findElement(By.xpath("//android.widget.LinearLayout[@content-desc=\"Top Up\"]/android.widget.ImageView")).click();
		Thread.sleep(5000);
        Set<String> contextsNames = driver.getContextHandles();
        for (String contextName : contextsNames)
        {
       
        	System.out.println(contextName);
        }
        driver.context((String) contextsNames.toArray()[1]);
		WebDriverWait wait = new WebDriverWait(driver, 3);
		WebElement e=	wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("historybtn")));
	e.click();
		driver.findElement(By.id("txt1")).sendKeys("1234");

		System.out.println("Application started1");
	}
}

LOGS 👍 
[35m[WD Proxy][39m Got response with status 404: {"sessionId":"e380cc1d-6459-4e0e-92c1-37fe905555a5","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:70)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:266)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:260)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann...
[debug] [35m[W3C][39m Matched W3C error code 'no such element' to NoSuchElementError
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element/00000000-0000-01b8-7fff-ffff00000068/click[39m
[35m[HTTP][39m [90m{"id":"00000000-0000-01b8-7fff-ffff00000068"}[39m
[debug] [35m[W3C (d8b1c506)][39m Calling AppiumDriver.click() with args: ["00000000-0000-01b8-7fff-ffff00000068","d8b1c506-69e2-41ab-b835-290dca2664ee"]
[debug] [35m[WD Proxy][39m Matched '/element/00000000-0000-01b8-7fff-ffff00000068/click' to command name 'click'
[debug] [35m[WD Proxy][39m Proxying [POST /element/00000000-0000-01b8-7fff-ffff00000068/click] to [POST http://127.0.0.1:8200/wd/hub/session/e380cc1d-6459-4e0e-92c1-37fe905555a5/element/00000000-0000-01b8-7fff-ffff00000068/click] with body: {"element":"00000000-0000-01b8-7fff-ffff00000068"}
[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"e380cc1d-6459-4e0e-92c1-37fe905555a5","value":null}
[debug] [35m[W3C (d8b1c506)][39m Responding to client with driver.click() result: null
[35m[HTTP][39m [37m<-- POST /wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element/00000000-0000-01b8-7fff-ffff00000068/click [39m[32m200[39m [90m2657 ms - 14[39m
[35m[HTTP][39m [90m[39m
Application started
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element[39m
[35m[HTTP][39m [90m{"using":"xpath","value":"//android.widget.LinearLayout[@content-desc=\"Top Up\"]/android.widget.ImageView"}[39m
[debug] [35m[W3C (d8b1c506)][39m Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.LinearLayout[@content-desc=\"Top Up\"]/android.widget.ImageView","d8b1c506-69e2-41ab-b835-290dca2664ee"]
[debug] [35m[BaseDriver][39m Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
[debug] [35m[BaseDriver][39m Waiting up to 60000 ms for condition
[debug] [35m[WD Proxy][39m Matched '/element' to command name 'findElement'
[debug] [35m[WD Proxy][39m Proxying [POST /element] to [POST http://127.0.0.1:8200/wd/hub/session/e380cc1d-6459-4e0e-92c1-37fe905555a5/element] with body: {"strategy":"xpath","selector":"//android.widget.LinearLayout[@content-desc=\"Top Up\"]/android.widget.ImageView","context":"","multiple":false}
[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"e380cc1d-6459-4e0e-92c1-37fe905555a5","value":{"ELEMENT":"00000000-0000-01b8-7fff-ffff00000211","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-01b8-7fff-ffff00000211"}}
[debug] [35m[W3C (d8b1c506)][39m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"00000000-0000-01b8-7fff-ffff00000211","ELEMENT":"00000000-0000-01b8-7fff-ffff00000211"}
[35m[HTTP][39m [37m<-- POST /wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element [39m[32m200[39m [90m558 ms - 137[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element/00000000-0000-01b8-7fff-ffff00000211/click[39m
[35m[HTTP][39m [90m{"id":"00000000-0000-01b8-7fff-ffff00000211"}[39m
[debug] [35m[W3C (d8b1c506)][39m Calling AppiumDriver.click() with args: ["00000000-0000-01b8-7fff-ffff00000211","d8b1c506-69e2-41ab-b835-290dca2664ee"]
[debug] [35m[WD Proxy][39m Matched '/element/00000000-0000-01b8-7fff-ffff00000211/click' to command name 'click'
[debug] [35m[WD Proxy][39m Proxying [POST /element/00000000-0000-01b8-7fff-ffff00000211/click] to [POST http://127.0.0.1:8200/wd/hub/session/e380cc1d-6459-4e0e-92c1-37fe905555a5/element/00000000-0000-01b8-7fff-ffff00000211/click] with body: {"element":"00000000-0000-01b8-7fff-ffff00000211"}
[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"e380cc1d-6459-4e0e-92c1-37fe905555a5","value":null}
[debug] [35m[W3C (d8b1c506)][39m Responding to client with driver.click() result: null
[35m[HTTP][39m [37m<-- POST /wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element/00000000-0000-01b8-7fff-ffff00000211/click [39m[32m200[39m [90m267 ms - 14[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/contexts[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (d8b1c506)][39m Calling AppiumDriver.getContexts() with args: ["d8b1c506-69e2-41ab-b835-290dca2664ee"]
[debug] [35m[AndroidDriver][39m Getting a list of available webviews
[debug] [35m[ADB][39m Running 'C:\Users\dineshreddy.m.DIGITRAL\Android\platform-tools\adb.exe -P 5037 -s 3202dee19804 shell cat /proc/net/unix'
[debug] [35m[AndroidDriver][39m Parsed 1 active devtools socket: ["@webview_devtools_remote_29470"]
[debug] [35m[AndroidDriver][39m Collecting CDP data of 1 webview
[debug] [35m[AndroidDriver][39m Forwarding remote port webview_devtools_remote_29470 to a local port in range 10900..11000
[debug] [35m[AndroidDriver][39m You could use the 'webviewDevtoolsPort' capability to customize the starting port number
[debug] [35m[ADB][39m Running 'C:\Users\dineshreddy.m.DIGITRAL\Android\platform-tools\adb.exe -P 5037 -s 3202dee19804 forward tcp:10900 localabstract:webview_devtools_remote_29470'
[debug] [35m[ADB][39m Removing forwarded port socket connection: 10900 
[debug] [35m[ADB][39m Running 'C:\Users\dineshreddy.m.DIGITRAL\Android\platform-tools\adb.exe -P 5037 -s 3202dee19804 forward --remove tcp:10900'
[debug] [35m[AndroidDriver][39m CDP data collection completed
[debug] [35m[AndroidDriver][39m WEBVIEW_29470 mapped to pid 29470
[debug] [35m[AndroidDriver][39m Getting process name for webview 'WEBVIEW_29470'
[debug] [35m[ADB][39m Running 'C:\Users\dineshreddy.m.DIGITRAL\Android\platform-tools\adb.exe -P 5037 -s 3202dee19804 shell ps --help'
[debug] [35m[ADB][39m Error: Command 'C:\\Users\\dineshreddy.m.DIGITRAL\\Android\\platform-tools\\adb.exe -P 5037 -s 3202dee19804 shell ps --help' exited with code 1
[debug] [35m[ADB][39m     at ChildProcess.<anonymous> (C:\Users\dineshreddy.m.DIGITRAL\AppData\Roaming\npm\node_modules\appium\node_modules\teen_process\lib\exec.js:113:19)
[debug] [35m[ADB][39m     at ChildProcess.emit (node:events:526:28)
[debug] [35m[ADB][39m     at maybeClose (node:internal/child_process:1092:16)
[debug] [35m[ADB][39m     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
[debug] [35m[ADB][39m Running 'C:\Users\dineshreddy.m.DIGITRAL\Android\platform-tools\adb.exe -P 5037 -s 3202dee19804 shell ps'
[debug] [35m[AndroidDriver][39m Got process name: 'com.ooredoo.selfcare'
[debug] [35m[AndroidDriver][39m Found 1 webview: ["WEBVIEW_com.ooredoo.selfcare"]
[debug] [35m[AndroidDriver][39m Available contexts: ["NATIVE_APP","WEBVIEW_com.ooredoo.selfcare"]
[debug] [35m[W3C (d8b1c506)][39m Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_com.ooredoo.selfcare"]
[35m[HTTP][39m [37m<-- GET /wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/contexts [39m[32m200[39m [90m706 ms - 55[39m
[35m[HTTP][39m [90m[39m
NATIVE_APP
WEBVIEW_com.ooredoo.selfcare
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/context[39m
[35m[HTTP][39m [90m{"name":"WEBVIEW_com.ooredoo.selfcare"}[39m
[debug] [35m[W3C (d8b1c506)][39m Calling AppiumDriver.setContext() with args: ["WEBVIEW_com.ooredoo.selfcare","d8b1c506-69e2-41ab-b835-290dca2664ee"]
[debug] [35m[AndroidDriver][39m Getting a list of available webviews
[debug] [35m[ADB][39m Running 'C:\Users\dineshreddy.m.DIGITRAL\Android\platform-tools\adb.exe -P 5037 -s 3202dee19804 shell cat /proc/net/unix'
[debug] [35m[AndroidDriver][39m Parsed 1 active devtools socket: ["@webview_devtools_remote_29470"]
[debug] [35m[AndroidDriver][39m Collecting CDP data of 1 webview
[debug] [35m[AndroidDriver][39m Forwarding remote port webview_devtools_remote_29470 to a local port in range 10900..11000
[debug] [35m[AndroidDriver][39m You could use the 'webviewDevtoolsPort' capability to customize the starting port number
[debug] [35m[ADB][39m Running 'C:\Users\dineshreddy.m.DIGITRAL\Android\platform-tools\adb.exe -P 5037 -s 3202dee19804 forward tcp:10900 localabstract:webview_devtools_remote_29470'
[debug] [35m[ADB][39m Removing forwarded port socket connection: 10900 
[debug] [35m[ADB][39m Running 'C:\Users\dineshreddy.m.DIGITRAL\Android\platform-tools\adb.exe -P 5037 -s 3202dee19804 forward --remove tcp:10900'
[debug] [35m[AndroidDriver][39m CDP data collection completed
[debug] [35m[AndroidDriver][39m WEBVIEW_29470 mapped to pid 29470
[debug] [35m[AndroidDriver][39m Getting process name for webview 'WEBVIEW_29470'
[debug] [35m[ADB][39m Running 'C:\Users\dineshreddy.m.DIGITRAL\Android\platform-tools\adb.exe -P 5037 -s 3202dee19804 shell ps'
[debug] [35m[AndroidDriver][39m Got process name: 'com.ooredoo.selfcare'
[debug] [35m[AndroidDriver][39m Found 1 webview: ["WEBVIEW_com.ooredoo.selfcare"]
[debug] [35m[AndroidDriver][39m Available contexts: ["NATIVE_APP","WEBVIEW_com.ooredoo.selfcare"]
[debug] [35m[AndroidDriver][39m Connecting to chrome-backed webview context 'WEBVIEW_com.ooredoo.selfcare'
[debug] [35m[AndroidDriver][39m A port was not given, using random free port: 8000
[debug] [35m[AndroidDriver][39m Passing web view details to the Chromedriver constructor: {
[debug] [35m[AndroidDriver][39m   "info": {
[debug] [35m[AndroidDriver][39m     "Android-Package": "com.ooredoo.selfcare",
[debug] [35m[AndroidDriver][39m     "Browser": "Chrome/102.0.5005.78",
[debug] [35m[AndroidDriver][39m     "Protocol-Version": "1.3",
[debug] [35m[AndroidDriver][39m     "User-Agent": "Mozilla/5.0 (Linux; Android 7.0; Redmi Note 4 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.78 Mobile Safari/537.36",
[debug] [35m[AndroidDriver][39m     "V8-Version": "10.2.154.5",
[debug] [35m[AndroidDriver][39m     "WebKit-Version": "537.36 (@df6dbb5a9fd82af3f567198af2eb5fb4876ef99c)",
[debug] [35m[AndroidDriver][39m     "webSocketDebuggerUrl": "ws://127.0.0.1:10900/devtools/browser"
[debug] [35m[AndroidDriver][39m   },
[debug] [35m[AndroidDriver][39m   "process": {
[debug] [35m[AndroidDriver][39m     "name": "com.ooredoo.selfcare",
[debug] [35m[AndroidDriver][39m     "id": "29470"
[debug] [35m[AndroidDriver][39m   }
[debug] [35m[AndroidDriver][39m }
[debug] [35m[AndroidDriver][39m Automated Chromedriver download is disabled. Use 'chromedriver_autodownload' server feature to enable it
[debug] [35m[AndroidDriver][39m Precalculated Chromedriver capabilities: {
[debug] [35m[AndroidDriver][39m   "androidPackage": "com.ooredoo.selfcare",
[debug] [35m[AndroidDriver][39m   "androidUseRunningApp": true,
[debug] [35m[AndroidDriver][39m   "androidProcess": "com.ooredoo.selfcare",
[debug] [35m[AndroidDriver][39m   "androidDeviceSerial": "3202dee19804"
[debug] [35m[AndroidDriver][39m }
[debug] [35m[AndroidDriver][39m Before starting chromedriver, androidPackage is 'com.ooredoo.selfcare'
[debug] [35m[Chromedriver][39m Changed state to 'starting'
[35m[Chromedriver][39m Set chromedriver binary as: D:\Automation\chromedriver.exe
[debug] [35m[Chromedriver][39m Killing any old chromedrivers, running: wmic process where "commandline like '%chromedriver.exe%--port=8000%'" delete
[debug] [35m[Chromedriver][39m Successfully cleaned up old chromedrivers
[debug] [35m[Chromedriver][39m Cleaning this device's adb forwarded port socket connections: 3202dee19804
[debug] [35m[ADB][39m List forwarding ports
[debug] [35m[ADB][39m Running 'C:\Users\dineshreddy.m.DIGITRAL\Android\platform-tools\adb.exe -P 5037 -s 3202dee19804 forward --list'
[35m[Chromedriver][39m Spawning chromedriver with: D:\Automation\chromedriver.exe --url-base=wd/hub --port=8000 --adb-port=5037 --verbose
[debug] [35m[Chromedriver][39m Chromedriver version: '102.0.5005.61'
[35m[Chromedriver][39m Chromedriver v. 102.0.5005.61 supports W3C protocol, but MJSONWP one has been explicitly requested
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[35m[WD Proxy][39m connect ECONNREFUSED 127.0.0.1:8000
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"build":{"version":"102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819})"},"message":"ChromeDriver ready for new sessions.","os":{"arch":"x86_64","name":"Windows NT","version":"10.0.18362"},"ready":true}}
[35m[Chromedriver][39m Starting MJSONWP Chromedriver session with capabilities: {
[35m[Chromedriver][39m   "desiredCapabilities": {
[35m[Chromedriver][39m     "chromeOptions": {
[35m[Chromedriver][39m       "androidPackage": "com.ooredoo.selfcare",
[35m[Chromedriver][39m       "androidUseRunningApp": true,
[35m[Chromedriver][39m       "androidProcess": "com.ooredoo.selfcare",
[35m[Chromedriver][39m       "androidDeviceSerial": "3202dee19804",
[35m[Chromedriver][39m       "w3c": false
[35m[Chromedriver][39m     },
[35m[Chromedriver][39m     "loggingPrefs": {
[35m[Chromedriver][39m       "browser": "ALL"
[35m[Chromedriver][39m     }
[35m[Chromedriver][39m   }
[35m[Chromedriver][39m }
[debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.ooredoo.selfcare","androidUseRunningApp":true,"androidProcess":"com.ooredoo.selfcare","androidDeviceSerial":"3202dee19804","w3c":false},"loggingPrefs":{"browser":"ALL"}}}
[debug] [35m[Chromedriver][39m Webview version: 'Chrome/102.0.5005.78'
[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"e5126c4c016c1f5f5532b68ea8512be8","status":0,"value":{"acceptInsecureCerts":false,"acceptSslCerts":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedriverVersion":"102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819})"},"cssSelectorsEnabled":true,"databaseEnabled":false,"goog:chromeOptions":{"debuggerAddress":"localhost:59192"},"handlesAlerts":true,"hasTouchScreen":true,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"pageLoadStrategy":"normal","platform":"ANDROID","proxy":{},"rotatable":false,"setWindowRect":false,"strictFileInteractability":false,"takesHeapSnapshot":true,"takesScreenshot":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unexpectedAlertBehaviour":"ignore","version":"102.0.5005.78","webStorageEnabled":true,"webauthn:extension:credBlob":false,"webauthn:extension:largeBlob":false,"webauthn:virtualAuthenticators":false}}
[35m[WD Proxy][39m Determined the downstream protocol as 'MJSONWP'
[debug] [35m[Chromedriver][39m Changed state to 'online'
[debug] [35m[W3C (d8b1c506)][39m Responding to client with driver.setContext() result: null
[35m[HTTP][39m [37m<-- POST /wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/context [39m[32m200[39m [90m3373 ms - 14[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element[39m
[35m[HTTP][39m [90m{"using":"id","value":"historybtn"}[39m
[35m[W3C (d8b1c506)][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[WD Proxy][39m Matched '/wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element' to command name 'findElement'
[debug] [35m[WD Proxy][39m Proxying [POST /wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element] to [POST http://127.0.0.1:8000/wd/hub/session/e5126c4c016c1f5f5532b68ea8512be8/element] with body: {"using":"id","value":"historybtn"}
[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"e5126c4c016c1f5f5532b68ea8512be8","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"id\",\"selector\":\"historybtn\"}\n  (Session info: chrome=102.0.5005.78)\n  (Driver info: chromedriver=102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}),platform=Windows NT 10.0.18362 x86_64)"}}
[debug] [35m[MJSONWP][39m Matched JSONWP error code 7 to NoSuchElementError
[35m[HTTP][39m [37m<-- POST /wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element [39m[33m404[39m [90m248 ms - 1201[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element[39m
[35m[HTTP][39m [90m{"using":"id","value":"historybtn"}[39m
[35m[W3C (d8b1c506)][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[WD Proxy][39m Matched '/wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element' to command name 'findElement'
[debug] [35m[WD Proxy][39m Proxying [POST /wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element] to [POST http://127.0.0.1:8000/wd/hub/session/e5126c4c016c1f5f5532b68ea8512be8/element] with body: {"using":"id","value":"historybtn"}
[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"e5126c4c016c1f5f5532b68ea8512be8","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"id\",\"selector\":\"historybtn\"}\n  (Session info: chrome=102.0.5005.78)\n  (Driver info: chromedriver=102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}),platform=Windows NT 10.0.18362 x86_64)"}}
[debug] [35m[MJSONWP][39m Matched JSONWP error code 7 to NoSuchElementError
[35m[HTTP][39m [37m<-- POST /wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element [39m[33m404[39m [90m344 ms - 1201[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element[39m
[35m[HTTP][39m [90m{"using":"id","value":"historybtn"}[39m
[35m[W3C (d8b1c506)][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[WD Proxy][39m Matched '/wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element' to command name 'findElement'
[debug] [35m[WD Proxy][39m Proxying [POST /wd/hub/session/d8b1c506-69e2-41ab-b835-290dca2664ee/element] to [POST http://127.0.0.1:8000/wd/hub/session/e5126c4c016c1f5f5532b68ea8512be8/element] with body: {"using":"id","value":"historybtn"}
[debug] [35m[WD Proxy][39m Got response with status 200: {"sessionId":"e5126c4c016c1f5f5532b68ea8512be8","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"id\",\"selector\":\"historybtn\"}\n  (Session info: chrome=102.0.5005.78)\n  (Driver info: chromedriver=102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}),platform=Windows NT 10.0.18362 x86_64)"}}
[debug] [35m[MJSONWP][39m Matched JSONWP error code 7 to NoSuchElementError

org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.id: historybtn (tried for 3 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at moalaunch.login.launch(login.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"id","selector":"historybtn"}
  (Session info: chrome=102.0.5005.78)
  (Driver info: chromedriver=102.0.5005.61 (0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}),platform=Windows NT 10.0.18362 x86_64)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'WLPT866', ip: '172.16.45.75', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: io.appium.java_client.AppiumDriver
Capabilities {app: D:\Automation\MOA8.6.3Stagi..., appPackage: com.ooredoo.selfcare, chromeOptions: {w3c: false}, chromedriverExecutable: D:\Automation\chromedriver.exe, databaseEnabled: false, desired: {app: D:\Automation\MOA8.6.3Stagi..., chromeOptions: {w3c: false}, chromedriverExecutable: D:\Automation\chromedriver.exe, deviceName: Redmi Note 4, platformName: android, platformVersion: 7, udid: 3202dee19804}, deviceApiLevel: 24, deviceManufacturer: Xiaomi, deviceModel: Redmi Note 4, deviceName: 3202dee19804, deviceScreenDensity: 480, deviceScreenSize: 1080x1920, deviceUDID: 3202dee19804, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 3, platform: LINUX, platformName: Android, platformVersion: 7.0, statBarHeight: 72, takesScreenshot: true, udid: 3202dee19804, viewportRect: {height: 1848, left: 0, top: 72, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: d8b1c506-69e2-41ab-b835-290dca2664ee
*** Element info: {Using=id, value=historybtn}
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:61)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:372)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementById(DefaultGenericMobileDriver.java:69)
	at io.appium.java_client.AppiumDriver.findElementById(AppiumDriver.java:1)
	at org.openqa.selenium.By$ById.findElement(By.java:188)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:57)
	

Can any one please help me with this issue

**Comment by mykola-mokhnach** [comment]
Elements interactions inside of the web view are completely controlled by chromedriver. Consider reporting an issue to Google as UIA2 simply acts as a proxy in this situation.

**Comment by mykola-mokhnach** [comment]
You could also use Appium forum to ask questions
