### ISSUE TITLE
Appium 2 beta40 - xcuitest@4.6.0 driver not installable

### ISSUE THREAD

**Issue by StephanB75** [appium/appium#17079]
## The problem

Since yesterday i can't install the xcuitest driver anymore
Tried appium driver install xcuitest which throws this kind of errors (many of this kind)

npm WARN tar ENOENT: no such file or directory, open '/Users/st/git/-ios-uitest_java/node_modules/.staging/es-abstract-12fae35c/5/ToUint16.js'

Tried that on 4 different machines and all have the same problem.
uiautomator2 driver works.

## Environment

* Appium version (or git revision) that exhibits the issue: 2.beta40
* Last Appium version that did not exhibit the issue (if applicable): 2.beta40 (last sunday)
* Driver version that exhibits the issue (only for Appium2): 4.6.0
* Last driver version that did not exhibit the issue (if applicable, only for Appium2): 4.5.0
* Desktop OS/version used to run Appium: macOS Momterey
* Node.js version (unless using Appium.app|exe): 14.18.1
* Package manager name and version (we only officially support NPM): 6.14.5
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

**Comment by StephanB75** [comment]
@mykola-mokhnach i have seen you release a feature in xcuitest driver 4.6.0
(Add a mobile wrapper for forcePress gesture)
Is it related to this change ?

**Comment by mykola-mokhnach** [comment]
Does it behave differently when Node16/NPM8 is used?

**Comment by StephanB75** [comment]
i dont know, all machines are configured identically.
Normally i don't like to update node because it breaks the opencv installation on the machines.
Does appium 2.0 still needs the opencv4nodejs installation/building ?

**Comment by mykola-mokhnach** [comment]
No it does not. We've switched the image plugin to use another opencv client

**Comment by StephanB75** [comment]
ok than i will try to upgrade node

**Comment by mykola-mokhnach** [comment]
you could probably only upgrade npm first, without bumping Node.js

**Comment by StephanB75** [comment]
installed node 16 and now other error occurs

✖ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev appium-xcuitest-driver --json' failed with code 1.

STDOUT:


STDERR:
npm ERR! Cannot read properties of null (reading 'parent')
{
  "error": {
    "code": null,
    "summary": "Cannot read properties of null (reading 'parent')",
    "detail": ""
  }
}

Installing xcuidriver 4.5.0 still works

**Comment by mykola-mokhnach** [comment]
The only change between these two versions is the webdriveragent dependency bump. I've reported the issue to NPM. let see what npm authors say

**Comment by mykola-mokhnach** [comment]
@StephanB75 Please attach this stack trace to the NPM issue above

**Comment by StephanB75** [comment]
i noticed somthing in the npm logs :
installing xcuitest driver 4.5.0 shows
  _timing reifyNode:node_modules/appium-xcuitest-driver Completed in 467ms_

installing 4.6.0 shows 
_timing reifyNode:node_modules/appium-xcuitest-driver/node_modules/appium-xcuitest-driver Completed in 2ms_

used same installation folder and APPIUM_HOME which lies directly beside the appium installation

**Comment by mykola-mokhnach** [comment]
I've added some more logging there and it looks like npm goes to an endless loop because of `file:.` inclusion:

```
ArboristLink {#####⸩ ⠦ reify:appium-xcuitest-driver: timing reify:createSparse Completed in 125ms
  name: 'appium-xcuitest-driver',
  version: '4.6.0',
  location: 'node_modules/appium-xcuitest-driver/node_modules/appium-xcuitest-driver/node_modules/appium-xcuitest-driver',
  path: '/Users/user/temp/node_modules/appium-xcuitest-driver/node_modules/appium-xcuitest-driver/node_modules/appium-xcuitest-driver',
  realpath: '/Users/user/temp/node_modules/appium-xcuitest-driver/node_modules/appium-xcuitest-driver',
  resolved: 'file:..',
  extraneous: true,
  dev: true,
  optional: true,
  peer: true,
  hasShrinkwrap: true,
  target: null
}

```

**Comment by StephanB75** [comment]
@mykola-mokhnach @jlipps Thank you for investigating and providing a fix so fast

✔ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver'
ℹ Driver xcuitest@4.6.1 successfully installed
- automationName: XCUITest
- platformNames: ["iOS","tvOS"]
