### ISSUE TITLE
Appium2 - Installing drivers "may be incompatible with the current version of Appium v2.0.0-beta.40 due to an invalid or missing peer dependency on Appium

### ISSUE THREAD

**Issue by KimEklund13** [appium/appium#17073]
## The problem

I installed the latest Appium [per the documentation](https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli)
`npm install -g appium@next`

When I try and install any of the drivers (espresso, uiautomator2...) I get warnings of incompatibility:
Ex: When I run `appium driver install uiautomator2` 
```
✔ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
⚠ Driver "uiautomator2" has 1 potential problem:
  - Driver "uiautomator2" (package `appium-uiautomator2-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.40) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-uiautomator2-driver` to add a peer dependency on `^appium@2.0.0-beta.40`.
Driver uiautomator2@2.2.0 successfully installed
```

When I run `appium install driver xcuitest`, it can't even be found.
`appium: error: unrecognized arguments: install driver xcuitest`

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.40

* Driver version that exhibits the issue (only for Appium2):
uiautomator2@2.2.0
espresso@2.5.0
xcuitest: N/A, could not download

* Last driver version that did not exhibit the issue (if applicable, only for Appium2): N/A, first time installing and setting up Appium 2 with drivers.

* Desktop OS/version used to run Appium: MacOS 12.4 Monterey

* Node.js version (unless using Appium.app|exe): v18.2.0

* Package manager name and version (we only officially support NPM): NPM version 8.12.1

* Mobile platform/version under test: N/A
* Real device or emulator/simulator: N/A
* Appium CLI or Appium.app|exe: N/A (though I am about to use Appium server GUI (latest) with the separate inspector tool 
Inspector tool specs: 2022.5.4 / Electron 13.6.9 / Node.js 14.16.0.
The Appium desktop GUI gives me `showAppInfo` so I can't check the GUI version. Although, it says there's no updates available.

**Comment by mykola-mokhnach** [comment]
The warning above is expected for now. We've made the server module to a peer dependency and it takes a while too update all drivers to support this approach. It does not affect drivers functionality though.

Regarding the second error - probably the CLI command has been mistyped. Please read the tutorial carefully: https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli

**Comment by jlipps** [comment]
`appium driver install xcuitest` is correct (not `appium install driver xcuitest`)

**Comment by richdownie** [comment]
I am seeing the below error today after updating xcuitest from `-v 4.4.6 `to `-v 4.6.0` and trying to start appium with 
` $ appium --allow-cors`

```[Appium] Welcome to Appium v2.0.0-beta.13
[Appium] Non-default server args:
[Appium]   allowCors: true
[Appium]   tmpDir: /var/folders/2x/qxvbwlx97bs21c8kls_n_vpr0000gn/T
[Appium] Attempting to load driver xcuitest...
[Appium] Could not load driver 'xcuitest', so it will not be available. Error in loading the driver was: Cannot find module 'appium/driver'
[Appium] Require stack:
[Appium] - /Users/richdownie/.appium/appium-xcuitest-driver/node_modules/appium-xcuitest-driver/build/lib/driver.js
[Appium] - /Users/richdownie/.appium/appium-xcuitest-driver/node_modules/appium-xcuitest-driver/build/index.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/extension-config.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/parser-helpers.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/args.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/parser.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/main.js
[debug] [Appium] Error: Cannot find module 'appium/driver'
[debug] [Appium] Require stack:
[debug] [Appium] - /Users/richdownie/.appium/appium-xcuitest-driver/node_modules/appium-xcuitest-driver/build/lib/driver.js
[debug] [Appium] - /Users/richdownie/.appium/appium-xcuitest-driver/node_modules/appium-xcuitest-driver/build/index.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/extension-config.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/parser-helpers.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/args.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/parser.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/main.js
[debug] [Appium]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:974:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:92:18)
[debug] [Appium]     at Object.<anonymous> (/Users/richdownie/.appium/appium-xcuitest-driver/node_modules/appium-xcuitest-driver/lib/driver.js:1:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:950:32)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:974:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:92:18)
[debug] [Appium]     at Object.<anonymous> (/Users/richdownie/.appium/appium-xcuitest-driver/node_modules/appium-xcuitest-driver/index.js:2:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:950:32)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
[Appium] You have enabled CORS requests from any host. Be careful not to visit sites which could maliciously try to start Appium sessions on your machine
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - xcuitest@4.6.0 (automationName 'XCUITest')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.```

**Comment by jlipps** [comment]
@richdownie how are you managing drivers? if via the Appium CLI, can you blow away your `~/.appium`, make sure you're on the latest Appium 2 beta, then reinstall the xcuitest driver?

**Comment by richdownie** [comment]
Here is a gif of me running all the things 

`$ xcodebuild -version && sw_vers && rm -rf ~/.appium && npm install -g appium@next && appium driver install xcuitest && appium --allow-cors`
![appium_xcuitest_issue](https://user-images.githubusercontent.com/3307/174685562-5ac85875-4e41-45a5-b096-0f4197db4153.gif)

I also get the error now when trying to revert back to the prior working version `xcuitest@4.4.6`

**Comment by mykola-mokhnach** [comment]
@richdownie Is the issue fixed with the recent xcuitest driver patch (4.6.1+)?

**Comment by mykola-mokhnach** [comment]
What is the local npm version? Make sure it's 7 or newer

**Comment by joweywen** [comment]
WARN Appium Appium encountered 2 warnings while validating drivers found in manifest C:\Users\LENOVO\.appium\node_modules\.cache\appium\extensions.yaml
WARN Appium Driver "uiautomator2" has 1 potential problem:
WARN Appium   - Driver "uiautomator2" (package `appium-uiautomator2-driver`) may be incompatible with the current version of Appium (v2.0.1) due to its peer dependency on older Appium v^2.4.1. Please ask the developer of `appium-uiautomator2-driver` to update the peer dependency on Appium to v2.0.1.
WARN Appium Driver "xcuitest" has 1 potential problem:
WARN Appium   - Driver "xcuitest" (package `appium-xcuitest-driver`) may be incompatible with the current version of Appium (v2.0.1) due to its peer dependency on older Appium v^2.5.4. Please ask the developer of `appium-xcuitest-driver` to update the peer dependency on Appium to v2.0.1.
[Appium] spawn EINVAL
how to fix that.help

**Comment by AmirSamson** [comment]
Hi I am trying to install Appium xcuitest-driver with "appium driver install xcuitest" CLI command, but I get the following error:

✖ Checking if 'appium-xcuitest-driver' is compatible
Error: ✖ 'xcuitest' cannot be installed because the server version it requires (^3.0.0-rc.2) does not meet the currently installed one (2.4.1). Please install a compatible server version first.

How can I update the Appium server?
