### ISSUE TITLE
Add emulator to appium studio

### ISSUE THREAD

**Issue by miladsalimiiii** [appium/appium#17077]
## The problem

I am going to add **emulator** to **appium** **studio** :

<img width="390" alt="Screen Shot 1401-03-29 at 18 00 19" src="https://user-images.githubusercontent.com/31917346/174484574-53466478-2cb9-41e4-90b5-12ae4733037c.png">

**But i encountered with a problem :**

<img width="448" alt="Screen Shot 1401-03-29 at 18 00 48" src="https://user-images.githubusercontent.com/31917346/174484608-94bb1fef-84e0-4fe2-bb71-0c440d02a13d.png">

_I dont have any problem with real device , does any one have a similar experience and solve it ?_

**What is the meaning of debug tab , debug tab of what?!**

## Environment

* appium 1.22.3 
* appium studio 22.4.8737
* MY DEVICE IS MAC M1

**Comment by mykola-mokhnach** [comment]
Sorry, but Appium Studio is a commercial product and has nothing to do with OSS Appium project. Please report the issue to its vendor
