### ISSUE TITLE
AppiumDriver.getScreenshot()  can not work on ios 16

### ISSUE THREAD

**Issue by lgc2016** [appium/appium#17074]
My phone is ios16,when I open Appium Inspector, it not work ,the error log is socket hang up when Executing command 'getScreenshot'

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/17540002/174266596-bca7a5c3-45fd-4083-80e2-b16d8142aaed.png">

**Comment by lgc2016** [comment]
my phone is ios16,when I open Appium Inspector, it not work ,the error log is  socket hang up when Executing command 'getScreenshot'

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly and provide the requested information along with the full server and device logs

**Comment by lgc2016** [comment]
> Please fill out the issue report properly and provide the requested information along with the full server and device logs

 the full server and device logs is:
[appium-server-logs.txt](https://github.com/appium/appium/files/8926871/appium-server-logs.txt)

and my capability set is


when I start session ,it cannot show the screen

**Comment by KazuCocoa** [comment]
Did you enable developer mode?
iOS 16 beta requires developer mode for app development purpose as the release note addressed. I wonder you followed it.
We've added the developer mode in https://github.com/appium/appium-xcuitest-driver#requirements as well.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by lgc2016** [comment]
> Did you enable developer mode? iOS 16 beta requires developer mode for app development purpose as the release note addressed. I wonder you followed it. We've added the developer mode in https://github.com/appium/appium-xcuitest-driver#requirements as well.

thank you ,i have no problem now
