### ISSUE TITLE
Driver update does not install latest version if driver is not installed

### ISSUE THREAD

**Issue by nextlevelbeard** [appium/appium#17086]
To more easily setup drivers `npx appium driver update xcuitest` shouldn't fail if the driver is not installed.
We should just go ahead and install the latest version.
Currently, an error is thrown:
```shell
Error: ✖ The driver "xcuitest" was not installed, so can't be updated
```

**Comment by StephanB75** [comment]
> To more easily setup drivers `npx appium driver update xcuitest` shouldn't fail if the driver is not installed. We should just go ahead and install the latest version. Currently, an error is thrown:
> 
> ```shell
> Error: ✖ The driver "xcuitest" was not installed, so can't be updated
> ```

i work around that error with "npx appium driver update xcuitest || true "

**Comment by boneskull** [comment]
I'd be in support of an `--update` flag to `install`.  I think "update-or-install" as default behavior is probably a little too surprising.
