### ISSUE TITLE
Control + key presses using action chains does not work

### ISSUE THREAD

**Issue by jainilparikh** [appium/appium#17089]
## The problem
Sending CTRL + A and CTRL + C (basically copying typed text to the clipboard).

## The code which does not work:

```
from appium.webdriver.common.appiumby import AppiumBy
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common import keys

action = ActionChains(self.driver)
print("CTRL + A")
action.move_to_location(0, 0).key_down(keys.Keys.CONTROL).send_keys('a').key_up(keys.Keys.CONTROL).perform()
print("CTRL + C")
action.move_to_location(0, 0).key_down(keys.Keys.CONTROL).send_keys('c').key_up(keys.Keys.CONTROL).perform()

text = self.driver.get_clipboard_text()

```

but this does not produce any output (no error messages). 

## Environment

* Appium version (or git revision) that exhibits the issue:  1.22.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Desktop version of Appium server on MacOS 
* Mobile platform/version under test: iOS 15
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: .app

## Details

I have text typed in a notepad application and I would like to copy it and take it in the clipboard. (I cannot use .text as I do not have a way to search for the text field either using Xpath to accessibility Id) We can assume that the text area is in focus while the above operation is being performed.

I am open to any other suggestions which do not use actionChains as well.

**Comment by mykola-mokhnach** [comment]
I don't expect key combinations to work on iOS - this was never implemented, neither supported by XCTest itself.

**Comment by jainilparikh** [comment]
@mykola-mokhnach , but XCUITest does provide a way in its docs using the modifier key: https://developer.apple.com/documentation/xctest/xcuielement/2920413-typekey

**Comment by jainilparikh** [comment]
Oh ok, in the meantime any way you could suggest to copy the text from a textarea (MSword, editor etc) which is in focus but I cannot get its Xpath/accessibility id and get its .text value?

In Android I am able to do it via `metastate` param which the `keycode` function has.

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't have any suggestions for such particular case.

**Comment by mykola-mokhnach** [comment]
I've checked the recent XCTest SDK and it looks like the typeKey API is only limited to macOS/Catalyst targets and does not work for iOS:

```

/*!
 * Types a string into the element. The element or a descendant must have keyboard focus; otherwise an
 * error is raised.
 *
 * This API discards any modifiers set in the current context by +performWithKeyModifiers:block: so that
 * it strictly interprets the provided text. To input keys with modifier flags, use  -typeKey:modifierFlags:.
 */
- (void)typeText:(NSString *)text;

#if TARGET_OS_OSX || TARGET_OS_MACCATALYST || TARGET_OS_IOS

/*!
 * Hold modifier keys while the given block runs. This method pushes and pops the modifiers as global state
 * without need for reference to a particular element. Inside the block, elements can be clicked on, dragged
 * from, typed into, etc.
 */
+ (void)performWithKeyModifiers:(XCUIKeyModifierFlags)flags block:(XCT_NOESCAPE void (^)(void))block API_AVAILABLE(ios(15.0), macCatalyst(13.0));

#if TARGET_OS_OSX || TARGET_OS_MACCATALYST

/*!
 * Types a single key with the specified modifier flags. Although `key` is a string, it must represent
 * a single key on a physical keyboard; strings that resolve to multiple keys will raise an error at runtime.
 * In addition to literal string key representations like "a", "6", and "[", keys such as the arrow keys,
 * command, control, option, and function keys can be typed using constants defined for them in XCUIKeyboardKeys.h
 */
- (void)typeKey:(NSString *)key modifierFlags:(XCUIKeyModifierFlags)flags;

#endif // TARGET_OS_OSX || TARGET_OS_MACCATALYST
```

And while `performWithKeyModifiers` seems to be supported after iOS 15 `typeText` API explicitly mentions that it ignores any modifiers set by `performWithKeyModifiers`

**Comment by jainilparikh** [comment]
As mentioned in the above para although it ignores `performWithKeyModifiers` the API actively takes input from `modifierFlags` param. I think apple has come up with a new API for `performWithKeyModifiers` [here](https://developer.apple.com/documentation/xctest/xcuielement/1500563-perform). Hence the typeText API prevents it.

**Comment by mykola-mokhnach** [comment]
Have you tried to type keys with modifiers using vanilla XCTest? Did it work for your case?

**Comment by jainilparikh** [comment]
I tried on iPhone and it didn't work (I will try it on an iPad soon). But for my usecase I see that apple has provided dynamic flags I am trying to figure out how I can use them for do ctrl + combinations or shift + combinations.

/```
* KeyboardOrKeypad Page (0x07) */
/* This section is the Usage Page for key codes to be used in implementing a USB keyboard. A Boot Keyboard (84-, 101- or 104-key) should at a minimum support all associated usage codes as indicated in the ÒBootÓ */
/* column below. */
/* The usage type of all key codes is Selectors (Sel), except for the modifier keys Keyboard Left Control (0x224) to Keyboard Right GUI (0x231) which are **Dynamic Flags (DV)**. */
```

**Comment by mykola-mokhnach** [comment]
btw, Ctrl would probably not work there. You'd need to use Command button (aka Cmd)

**Comment by jainilparikh** [comment]
correct :)

**Comment by jlipps** [comment]
> Oh ok, in the meantime any way you could suggest to copy the text from a textarea (MSword, editor etc) which is in focus but I cannot get its Xpath/accessibility id and get its .text value?

You can do what a user would do: long press the text, select all, and copy, using the popup buttons in the UI.

**Comment by jainilparikh** [comment]
Ya, this would work I think using the `mobile: touchAndHold` event at x = mid of screen and y = mid of screen. I will try this out.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by krishtoautomate** [comment]
@KazuCocoa any idea how to send Upper case using performIoHidEvent

**Comment by mykola-mokhnach** [comment]
I assume this API does not allow it. It only supports single key press with given duration. Nothing else is supported by XCTest

**Comment by krishtoautomate** [comment]
may be this can enhanced to support more hid events using apple private apis

https://github.com/kennytm/iphone-private-frameworks/tree/master/IOKit/hid

**Comment by nanoscopic** [comment]
@krishtoautomate No. See https://iphonedev.wiki/IOHIDFamily ; there are checks to prevent calling the function to get a handle to IOHID from anywhere except from Springboard.
