### ISSUE TITLE
Safari appium CSS SELECTOR not work

### ISSUE THREAD

**Issue by suzhenyu006** [appium/appium#17080]
i get a error when i do test at ios safari use appium >Message: Unsupported CSS selector '.cbd-plate.plate-headline .cbd-plate-head'. Reason: ''[object Object].cbd-plate.plate-headline'
is not a valid ios class. Must be a single string (e.g.: XCUIElementTypeWindow) without
dots separating them'
Stacktrace:
InvalidSelectorError: Unsupported CSS selector '.cbd-plate.plate-headline .cbd-plate-head'. Reason: ''[object Object].cbd-plate.plate-headline'
is not a valid ios class. Must be a single string (e.g.: XCUIElementTypeWindow) without
dots separating them'

**Comment by jlipps** [comment]
Based on the error it looks like you're not actually in webview mode.

**Comment by suzhenyu006** [comment]
solved! is my code fault
