### ISSUE TITLE
mp4 file maked by stop_recording_screen() can not play on quike-time player

### ISSUE THREAD

**Issue by lgc2016** [appium/appium#17087]
appium：1.22.3
when i use stop_recording_screen() to make a mp4 file, it can not open with quick time player,i don't know where is wrong.is my code wrong?

my code:
        mp4_64 = self.driver.stop_recording_screen()
        mp4_byte = base64.b64decode(mp4_64)
        self.project_path = os.getcwd().split('qa-app-ui')[0] + 'qa-app-ui/'
        self.path = self.project_path + 'result/record.mp4'
        with open(self.path, "wb") as code:
            code.write(mp4_byte)
<img width="399" alt="image" src="https://user-images.githubusercontent.com/17540002/175232721-df81da50-83bf-4e31-a9b1-f742943efa31.png">

**Comment by KazuCocoa** [comment]
What about VLC player. Quick time does not play some correct mp4 cases.
Btw, may video type `h264` work?

**Comment by lgc2016** [comment]
> 

thanks         
use mp4_64 = self.driver.stop_recording_screen(videoType='libx264',timeLimit=600)，it works
