### ISSUE TITLE
With appium-webdriveragent `3.17.0` when I try to get screenshot got `Cannot take a screenshot within 20000 ms timeout` error.

### ISSUE THREAD

**Issue by suzukieita** [appium/appium#17099]
## The problem

When I tried to get a screenshot I got an error.
```
[Xcode] 2022-06-27 16:19:23.458687+0900 WebDriverAgentRunner-Runner[10836:8198933] Error Domain=com.facebook.WebDriverAgent Code=1 "Cannot take a screenshot within 20000 ms timeout" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}
```

## Environment
- XCode: 13.2.1
- appium: 1.22.3
- WebDriverAgent: 3.17.0
- iOS: 14.4

## Details

I checked the PRs, and I found this PR https://github.com/appium/WebDriverAgent/pull/577.
I ported the code locally and it solved the problem.
Could you backport the change to 3.17.x as well?

**Comment by jlipps** [comment]
Is there a reason you can't use the latest version?

**Comment by mykola-mokhnach** [comment]
Unfortunately the Appium team does not have enough resources to maintain/patch old releases. If someone is interested in doing that then please let us know.
