### ISSUE TITLE
mFocusedApp and mCurrentFocus return two entries on Android 12 Galaxy Flip 5G 

### ISSUE THREAD

**Issue by samuel-verdonck** [appium/appium#17106]
## The problem

When trying to install and run app wrong package and activity are selected. Running on real device, launched from Appium Inspector

`Found package: 'com.android.systemui' and fully qualified activity name : 'com.android.systemui.subscreen.SubHomeActivity'`

`adb -P 5037 -s R5CR805PBNX shell dumpsys window displays | grep 'mFocusedApp' 
  mFocusedApp=ActivityRecord{14d88c3 u0 com.android.systemui/.subscreen.SubHomeActivity t9}
  mFocusedApp=ActivityRecord{d72327 u0 eu.niko.smart.universal/crc648a3abc16689e594e.MainActivity t409}
`

`adb -P 5037 -s R5CR805PBNX shell dumpsys window displays | grep 'mCurrentFocus'
  mCurrentFocus=null
  mCurrentFocus=Window{2785a60 u0 eu.niko.smart.universal/crc648a3abc16689e594e.MainActivity}`

Tried suggestions on [https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Desktop OS/version used to run Appium: macOS 12.4
* Node.js version (unless using Appium.app|exe): Node.js v18.4.0.
* Package manager name and version (we only officially support NPM): npm@8.12.1
* Mobile platform/version under test: Android 12
* Real device or emulator/simulator: Galaxy Z Flip3 5G
* Appium CLI or Appium.app|exe: Both

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com/samuel-verdonck/84d0ec74f53dfd5d05124174c9ce36ed#file-appiumdebug-log) 

## Code To Reproduce Issue [ Good To Have ]

No real code here - just installing the app from the inspector

**Comment by mykola-mokhnach** [comment]
I assume this happens because the device actually has two screens, so there are different apps being active at the same time on each of them?

**Comment by mykola-mokhnach** [comment]
Yes, it could be. Actually, before it was probably never the case for Appium to deal with such devices.
As a possible workaround you could ask the server to not wait for activity at all.
In the meantime a've prepared a simple(?) [patch](https://github.com/appium/appium-adb/pull/604), which you could apply and test locally. Note, that we don't maintain Appium1 anymore and all changes are only available in drivers that are available as part of Appium2.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
