### ISSUE TITLE
key words 'Open Application'  always gets failed result:No application is open

### ISSUE THREAD

**Issue by DirecTion1024** [appium/appium#17111]
## The problem

i use appium+robotframework to test my app.when i use key words:Open Application,it always gets failed result:No application is open.**but actually the app was already open**.i started appium server with code:appium -p 4723 --session-override --no-reset

## Environment

info AppiumDoctor Appium Doctor v.1.16.0
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: C:\Program Files\nodejs\node.EXE
info AppiumDoctor  ✔ Node version is 16.15.1
info AppiumDoctor  ✔ ANDROID_HOME is set to: D:\Android_Sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: C:\Program Files\Java\jdk1.8.0_60
info AppiumDoctor    Checking adb, android, emulator
info AppiumDoctor      'adb' is in D:\Android_Sdk\platform-tools\adb.exe
info AppiumDoctor      'android' is in D:\Android_Sdk\tools\android.bat
info AppiumDoctor      'emulator' is in D:\Android_Sdk\emulator\emulator.exe
info AppiumDoctor  ✔ adb, android, emulator exist: D:\Android_Sdk
info AppiumDoctor  ✔ 'bin' subfolder exists under 'C:\Program Files\Java\jdk1.8.0_60'
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###

## Link to Appium logs

[Appium] Welcome to Appium v1.22.3
[Appium] Non-default server args:
[Appium]   sessionOverride: true
[Appium]   noReset: true
[Appium] Deprecated server args:
[Appium]   --no-reset => --default-capabilities
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:[Appium]   noReset: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[debug] [HTTP] Request idempotency key: 7f23cbc2-7404-4dc1-af31-8e9f377ac667
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{"platformName":"Android","appium:platformVersion":"4.4","appium:deviceName":"NotUsedInAndroid","appium:automationName":"UIAutomator1","appium:appPackage":"com.iflytek.xiri","appium:appActivity":"com.iflytek.setting.SettingActivity","appium:noSign":"true","appium:udid":"","appium:newCommandTimeout":"1200"}]},"desiredCapabilities":{"platformName":"Android","platformVersion":"4.4","deviceName":"NotUsedInAndroid","automationName":"UIAutomator1","appPackage":"com.iflytek.xiri","appActivity":"com.iflytek.setting.SettingActivity","noSign":"true","udid":"","newCommandTimeout":"1200"}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","platformVersion":"4.4","deviceName":"NotUsedInAndroid","automationName":"UIAutomator1","appPackage":"com.iflytek.xiri","appActivity":"com.iflytek.setting.SettingActivity","noSign":"true","udid":"","newCommandTimeout":"1200"},null,{"firstMatch":[{"platformName":"Android","appium:platformVersion":"4.4","appium:deviceName":"NotUsedInAndroid","appium:automationName":"UIAutomator1","appium:appPackage":"com.iflytek.xiri","appium:appActivity":"com.iflytek.setting.SettingActivity","appium:noSign":"true","appium:udid":"","appium:newCommandTimeout":"1200"}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1656492115876 (16:41:55 GMT+0800 (中国标准时间))
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   noReset
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[Appium] Appium v1.22.3 creating new AndroidDriver (v4.51.0) session
[debug] [Appium] There are no active sessions for cleanup
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "Android",
[debug] [BaseDriver]     "appium:noReset": true,
[debug] [BaseDriver]     "appium:platformVersion": "4.4",
[debug] [BaseDriver]     "appium:deviceName": "NotUsedInAndroid",
[debug] [BaseDriver]     "appium:automationName": "UIAutomator1",
[debug] [BaseDriver]     "appium:appPackage": "com.iflytek.xiri",
[debug] [BaseDriver]     "appium:appActivity": "com.iflytek.setting.SettingActivity",
[debug] [BaseDriver]     "appium:noSign": "true",
[debug] [BaseDriver]     "appium:udid": "",
[debug] [BaseDriver]     "appium:newCommandTimeout": "1200"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Number capability passed in as string. Functionality may be compromised.
[BaseDriver] Capability 'noSign' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'newCommandTimeout' changed from string ('1200') to integer (1200). This may cause unexpected behavior
[BaseDriver] Session created with session id: ed30d3e5-c6b5-4295-91c5-a7461eddd788
[ADB] Found 8 'build-tools' folders under 'D:\Android_Sdk' (newest first):
[ADB]     D:/Android_Sdk/build-tools/30.0.2
[ADB]     D:/Android_Sdk/build-tools/29.0.3
[ADB]     D:/Android_Sdk/build-tools/29.0.2
[ADB]     D:/Android_Sdk/build-tools/28.0.3
[ADB]     D:/Android_Sdk/build-tools/28.0.2
[ADB]     D:/Android_Sdk/build-tools/27.0.3
[ADB]     D:/Android_Sdk/build-tools/26.0.2
[ADB]     D:/Android_Sdk/build-tools/25.0.0
[ADB] Using 'adb.exe' from 'D:\Android_Sdk\platform-tools\adb.exe'
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 start-server'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices
[debug] [ADB] Connected devices: [{"udid":"10.5.34.163:5555","state":"device"}]
[AndroidDriver] Looking for a device with Android '4.4.0'
[debug] [ADB] Setting device id to 10.5.34.163:5555
[ADB] Getting device platform version
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 4.4.2
[debug] [ADB] Setting device id to 10.5.34.163:5555
[AndroidDriver] Using device: 10.5.34.163:5555
[ADB] Using 'adb.exe' from 'D:\Android_Sdk\platform-tools\adb.exe'
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 start-server'
[debug] [ADB] Setting device id to 10.5.34.163:5555
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 19
[debug] [ADB] Device API level: 19
[AndroidDriver] App file was not listed, instead we're going to run com.iflytek.xiri directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell pm list packages com.iflytek.xiri'
[AndroidDriver] Starting Android session
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 wait-for-device'
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell echo ping'
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell dumpsys package io.appium.settings'
[debug] [ADB] 'io.appium.settings' is installed
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell dumpsys package io.appium.settings'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('3.4.0' >= '3.4.0')
[debug] [ADB] There is no need to install/upgrade 'C:\Users\xiangfang\AppData\Roaming\npm\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Using ps-based PID detection
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell ps --help'
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell ps'
[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell settings put secure mock_location 1'
[debug] [Logcat] Starting logs capture with command: D:\\Android_Sdk\\platform-tools\\adb.exe -P 5037 -s 10.5.34.163\:5555 logcat -v threadtime
[ADB] Getting device platform version
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell getprop ro.build.version.release'
[debug] [ADB] Current device property 'ro.build.version.release': 4.4.2
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell wm size'
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell getprop ro.product.model'
[debug] [ADB] Current device property 'ro.product.model': B860AV1.1-T
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell getprop ro.product.manufacturer'
[debug] [ADB] Current device property 'ro.product.manufacturer': ZTE Corporation
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [AndroidDriver] No app capability. Assuming it is already on the device
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 forward tcp:4724 tcp:4724'
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell mkdir -p /data/local'
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 push C:\Users\xiangfang\AppData\Roaming\npm\node_modules\appium\node_modules\appium-android-driver\bootstrap\bin\AppiumBootstrap.jar /data/local/tmp/'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting IDs of all 'uiautomator' processes
[debug] [ADB] Using ps-based PID detection
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell ps'
[ADB] No 'uiautomator' process has been found
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","10.5.34.163:5555","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.iflytek.xiri","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell dumpsys window'
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [ADB] Running 'D:\Android_Sdk\platform-tools\adb.exe -P 5037 -s 10.5.34.163:5555 shell am start -W -n com.iflytek.xiri/com.iflytek.setting.SettingActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000'
[Appium] New AndroidDriver session created successfully, session ed30d3e5-c6b5-4295-91c5-a7461eddd788 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1656492130741 (16:42:10 GMT+0800 (中国标准时间))
[debug] [W3C (ed30d3e5)] Cached the protocol value 'W3C' for the new session ed30d3e5-c6b5-4295-91c5-a7461eddd788
[debug] [W3C (ed30d3e5)] Responding to client with driver.createSession() result: {"capabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","noReset":true,"platformVersion":"4.4","deviceName":"NotUsedInAndroid","automationName":"UIAutomator1","appPackage":"com.iflytek.xiri","appActivity":"com.iflytek.setting.SettingActivity","noSign":true,"udid":"","newCommandTimeout":1200},"platformName":"Android","noReset":true,"platformVersion":"4.4.2","deviceName":"10.5.34.163:5555","automationName":"UIAutomator1","appPackage":"com.iflytek.xiri","appActivity":"com.iflytek.setting.SettingActivity","noSign":true,"udid":"","newCommandTimeout":1200,"deviceUDID":"10.5.34.163:5555","deviceScreenSize":"1280x720","deviceModel":"B860AV1.1-T","deviceManufacturer":"ZTE Corporation"}}
[HTTP] <-- POST /wd/hub/session 200 14873 ms - 938

**Comment by DirecTion1024** [comment]
> I don't think anyone would be able to help much there. We do not maintain the obsolete UIAutomator1 driver anymore and Android 4 is quite out of date as well.

okay...but i have tryed android 10, the same thing happened...and in robotframework's report shows:AttributeError: can't set attribute,i dont know how to solve this problem
![error](https://user-images.githubusercontent.com/19743170/176434314-7d8561ef-2691-4ab4-8e72-6a2876d9f57b.png)

**Comment by mykola-mokhnach** [comment]
Sorry, we cannot help much without having the server logs. Screenshots are mostly useless. 
Also, make sure you use one of supported drivers for Android (either UiAutomator2 or Espresso)

**Comment by mykola-mokhnach** [comment]
> [BaseDriver] Shutting down because we waited 60 seconds for a command
> [Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'

I don't observe any issues in the recent log. The driver has been shut down because it did not receive any commands within 60 seconds.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
