### ISSUE TITLE
faceId automation - faceId biometrice false match can also login to the app

### ISSUE THREAD

**Issue by blueskymd** [appium/appium#17119]
## The problem

I am writing an automation for iOS simulator. The test case is that if I input non-matching face, app should not allow to login to the app. However, the test is failing because even with non-matching face I am able to login to the app.

I am using WebDriverIO to write the automation. Following is the code snippet that is supposed to check non-matching face.

_await driver.execute(
      'mobile:sendBiometricMatch',
      { type: 'faceId' },
      { match: false }_

## Environment

* Appium version (or git revision) that exhibits the issue:  2.0
* Appium service: In package.json following is the entry under **devDependencies**
  "devDependencies": {
    **"@wdio/appium-service": "^7.19.5",**

* Last Appium version that did not exhibit the issue (if applicable): N/A
* Driver version that exhibits the issue (only for Appium2):
* Last driver version that did not exhibit the issue (if applicable, only for Appium2): N/A
* Desktop OS/version used to run Appium: N/A
* Node.js version (unless using Appium.app|exe): 16.14.0
* Package manager name and version (we only officially support NPM): NPM
* Mobile platform/version under test: iOS v15.2, iPhone12 
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: 2.0.0-beta.18

**Comment by mykola-mokhnach** [comment]
Please provide the server log

**Comment by mykola-mokhnach** [comment]
Closed because of no response
