### ISSUE TITLE
Element with locator not found.

### ISSUE THREAD

**Issue by BISTArk** [appium/appium#17110]
We are trying to automate some flows on a macos app using Robot framework and appium library. We are able to automate the flows for apps like calculator. So, the installation and sever are running well on the machine. But when we run it on our app it gives the following logs (saying the element with the specified locator isnt found).
Any inputs?

[logs.txt](https://github.com/appium/appium/files/9008056/logs.txt)

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description according to the given template. Kindly use appium forum if this is a question and not a server issue

**Comment by BISTArk** [comment]
Thamk you
