### ISSUE TITLE
Drivers not found after upgrade

### ISSUE THREAD

**Issue by Auto81** [appium/appium#17123]
## The problem

Cannot load drivers after upgrades. Very similar looking to #17026

Previously on v2 Beta35 (everything was fine with uiautomator2 and xcuitest installed), 
Upgraded XCUITest from 4.3.0 to 4.7.0 and now getting the following when trying to create session

`Could not find a driver for automationName 'XCUITest' and platformName ios'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Cannot find module 'appium/driver'`

Tried upgrading appium to v2Beta40 but same error.
Tried going back to XCUITest 4.3.0 and v2Beta35 but still get the same.

Also tried https://github.com/appium/appium/issues/17026#issuecomment-1145096921 . When running 'appium' command I get the following output

> [Appium] Welcome to Appium v2.0.0-beta.40
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at /Users/USER/.appium/node_modules/appium-xcuitest-driver
[Appium] Could not load driver 'xcuitest', so it will not be available. Error in loading the driver was: Cannot find module 'appium/driver'
[Appium] Require stack:
[Appium] - /Users/USER/.appium/node_modules/appium-xcuitest-driver/build/lib/driver.js
[Appium] - /Users/USER/.appium/node_modules/appium-xcuitest-driver/build/index.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/extension/extension-config.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension-command.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/driver-command.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension.js
[Appium] - /usr/local/lib/node_modules/appium/build/lib/main.js
[Appium] - /usr/local/lib/node_modules/appium/index.js
[debug] [Appium] Error: Cannot find module 'appium/driver'
[debug] [Appium] Require stack:
[debug] [Appium] - /Users/USER/.appium/node_modules/appium-xcuitest-driver/build/lib/driver.js
[debug] [Appium] - /Users/USER/.appium/node_modules/appium-xcuitest-driver/build/index.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/extension/extension-config.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension-command.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/driver-command.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/cli/extension.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/build/lib/main.js
[debug] [Appium] - /usr/local/lib/node_modules/appium/index.js
[debug] [Appium]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:952:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:88:18)
[debug] [Appium]     at Object.<anonymous> (/Users/USER/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:1:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:928:32)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:952:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:88:18)
[debug] [Appium]     at Object.<anonymous> (/Users/USER/.appium/node_modules/appium-xcuitest-driver/index.js:2:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:928:32)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - xcuitest@4.7.0 (automationName 'XCUITest')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.

## Environment

* Appium version (or git revision) that exhibits the issue: v2 Beta40 (latest)
* Last Appium version that did not exhibit the issue (if applicable): v2 Beta35
* Driver version that exhibits the issue (only for Appium2):
* Last driver version that did not exhibit the issue (if applicable, only for Appium2):
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): 14.15.4
* Package manager name and version (we only officially support NPM): 6.14.10
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
Update NPM to v7+ and reinstall drivers

**Comment by Auto81** [comment]
Brilliant, that seems to work!

Thanks
