### ISSUE TITLE
Forward mjpegport to local similar to wdapory

### ISSUE THREAD

**Issue by krishtoautomate** [appium/appium#17136]
When session is started, by default wdaport can be accessed using localhost:wdaPort and not mjpeg port though we sent mpegPort.

Is it possible implement same for mjpegserver as well so it can be used better in mpeg feature of appium-inspector.

**Comment by mykola-mokhnach** [comment]
There is already [appium:mjpegServerPort](https://github.com/appium/appium-xcuitest-driver#webdriveragent) capability.

Please use Appium forum to ask questions

**Comment by krishtoautomate** [comment]
this feature is not working as wdaProxy.

start session with additional capability 
appium:mjpegServerPort:9100
appium:wdaPort:8100

Open in browser :
localhost:8100 --works
localhost:9100 --Not working

**Comment by mykola-mokhnach** [comment]
xcuitest driver does not use iproxy at all since quite a while. appium-ios-device library is used instead.

**Comment by krishtoautomate** [comment]
@mykola-mokhnach  can you please point me where  appium-ios-device is used to tcp connect locallost and wdaPort in appium?

**Comment by mykola-mokhnach** [comment]
This happens in the [iProxy](https://github.com/appium/appium-xcuitest-driver/blob/master/lib/device-connections-factory.js) class

**Comment by krishtoautomate** [comment]
I mean where this class is used or executed.

**Comment by krishtoautomate** [comment]
Found it

@mykola-mokhnach 

Why iproxy is used only for wdaPort? Why not same applied for mjpegPort?

https://github.com/appium/appium-xcuitest-driver/blob/c3617ed8241833c58935244dc6b117e1fe7fc569/lib/wda/webdriveragent.js#L224

**Comment by mykola-mokhnach** [comment]
This is some very old commit. Consider checking the current master:

https://github.com/appium/appium-xcuitest-driver/blob/7f2e17e1924cf372053cafd71738d0d5f61ee88c/lib/commands/recordscreen.js#L59

**Comment by krishtoautomate** [comment]
So mjpeg port forward starts only on screen-record start.

in this case new mjpeg function in  appium inspector dont work.

**Comment by jlipps** [comment]
maybe the port forwarding should happen automatically if the mjpeg screenshot capability is sent in and we're on a real device?

**Comment by krishtoautomate** [comment]
Yes, I guess that should be done instead of screen-record ON only.
