### ISSUE TITLE
Appium driver (XCUITest) is returning http://appium.io page source instead https://www.youtube.com page source

### ISSUE THREAD

**Issue by DisruptedDev** [appium/appium#17135]
## The problem

After going to www.youtube.com,  XCUITest driver is returning as page source code of  https://appium.io page source instead youtube source code.

The steps :
- driver.get("https://www.youtube.com") 
- driver.getPageSource() 
- driver.context("NATIVE_APP")
- driver.getScreenshotAs(OutpuType.FILE)
- driver.resetApp();
- driver.closeApp();
- driver.quit();

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Driver version that exhibits the issue (only for Appium2): 
* Last driver version that did not exhibit the issue (if applicable, only for Appium2): N/A
* Desktop OS/version used to run Appium:  10.15.7
* Node.js version (unless using Appium.app|exe):  v13.10.1
* Package manager name and version (we only officially support NPM): NPM 6.13.7
* Mobile platform/version under test: 14.6
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Applium Cli

## Link to Appium logs
[Appium Logs](https://gist.github.com/DisruptedDev/3d99be99b1591bb071f8ccf766322ec2)

**Comment by mykola-mokhnach** [comment]
- resetApp/closeApp APIs are deprecated and is going to be removed soon
- Appium 1 is not maintained anymore. Please try Appium 2 with the most recent xcuitest driver version

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by DisruptedDev** [comment]
@mykola-mokhnach  Sorry to not give you quick feedback as fast as you would like, but I cannot switch from Appium 1 to 2 and test it in few days. I hope next week have results and be able to confirm  if this issue persists (I hope not);)

**Comment by mykola-mokhnach** [comment]
Sure, I can keep the issue open till the end of the week
