### ISSUE TITLE
Not able to interact with app UI screen using Appium flutter driver

### ISSUE THREAD

**Issue by ommoneynmore** [appium/appium#17140]
## The problem

I'm using Appium flutter driver to automate flutter app, we've already automated 2 screen, but once we logged in to the app getting timeout for all the locators on home page not even interacting with any of UI elements using flutter finder

## Environment

* Appium version: 1.22.3
* Emulator
* emulator and real device both
* OS: Linux

Any help/input will be appreciated

**Comment by mykola-mokhnach** [comment]
This driver is not maintained by Appium team, but rather by a third party. Consider creating your issue in the corresponding driver's repository.
