### ISSUE TITLE
Appium fails to detect android alerts on Huawei device

### ISSUE THREAD

**Issue by rychtak** [appium/appium#17152]
**Huawei P50 PRO**
**Android 12.0.1**
**Appium 1.22.1 (node version 16.13.2) / tried also on newest desktop version (1.22.3)**
**Java project, run on MAC (macOS Monterey 12.3.1)**

I'm trying to handle Android alerts after installing a fresh app on Huawei p50 pro device and here is my issue (other phone models like Samsung, Honor with different android versions are fine):

Here are my test steps:
1. Install an app.
2. Wait for the first android alert using **wait.until(ExpectedConditions.alertIsPresent())** method.

After calling alertIsPresent() method the test is stuck until appium server throws a timeout error: (240000ms timeout)
<img width="162" alt="image" src="https://user-images.githubusercontent.com/49534784/177950675-14f2e828-9fd2-44ba-840c-255da93dc923.png">
If I close alerts manually then appium "unstuck itself" and throws an error that no alerts are present on the device in given time.

Here are appium logs and logcats from the device.
[logcat_debugg_huawei_p50_pro.odt](https://github.com/appium/appium/files/9070273/logcat_debugg_huawei_p50_pro.odt)
[logcat_errors_huawei_p50_pro.odt](https://github.com/appium/appium/files/9070274/logcat_errors_huawei_p50_pro.odt)
[appium_logs.odt](https://github.com/appium/appium/files/9070313/appium_logs.odt)

If there is anything more you need just let me know, thanks!

**Comment by rychtak** [comment]
Ok then, I will create a workaround with autoGrantPermissions on this specific device.
Thank you for help :)

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
