### ISSUE TITLE
Element returned from async script is not cached

### ISSUE THREAD

**Issue by systemboogie** [appium/appium#17154]
## The problem

When the result of `executeAsyncScript()` is a `WebElement`, that element does not get cached. Therefore, trying to use the element fails with a `StaleElementReferenceError`.

We are using the official [selenium-webdriver NPM package](https://www.npmjs.com/package/selenium-webdriver) from the Selenium project. This is an oversimplified code snippet that causes the problem to show (I have also set up a self-contained executable project, see further down below):

```
await driver.get('https://the-internet.herokuapp.com');
const result = await driver.executeAsyncScript(
  function executeSomethingVerySimple() {
    const callback = arguments[arguments.length - 1];
    callback(document.querySelector('h1'));
  }
);

assert.strictEqual((await result.getTagName()).toLowerCase(), 'h1');
// StaleElementReferenceError: An element command failed because the referenced element is no longer attached to the DOM.
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3 with appium-xcuitest-driver >= 3.51.0
* Last Appium version that did not exhibit the issue (if applicable): 1.22.3 with appium-xcuitest-driver 3.50.2
* Desktop OS/version used to run Appium: macOS 12.3.1
* Node.js version (unless using Appium.app|exe): 14.19.2
* Package manager name and version (we only officially support NPM): NPM
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

This is an excerpt from the Appium logs (full logs below), where you can see that `executeAsyncScript()` properly returns a `WebElement`, but it is immediately stale:

<details><summary>Log excerpt</summary>

```
[debug] [RemoteDebugger] Received result for atom 'execute_script' execution: null
[debug] [W3C (9c2dd027)] Responding to client with driver.executeAsync() result: {"element-6066-11e4-a52e-4f735466cecf":":wdc:1657275218184","ELEMENT":":wdc:1657275218184"}
[HTTP] <-- POST /wd/hub/session/9c2dd027-4b95-4aa5-9806-4b875b135b39/execute/async 200 39 ms - 101
[HTTP] 
[HTTP] --> GET /wd/hub/session/9c2dd027-4b95-4aa5-9806-4b875b135b39/element/:wdc:1657275218184/name
[HTTP] {}
[debug] [W3C (9c2dd027)] Calling AppiumDriver.getName() with args: [":wdc:1657275218184","9c2dd027-4b95-4aa5-9806-4b875b135b39"]
[debug] [XCUITest] Executing command 'getName'
[debug] [W3C (9c2dd027)] Encountered internal error running command: StaleElementReferenceError: An element command failed because the referenced element is no longer attached to the DOM.
[debug] [W3C (9c2dd027)]     at XCUITestDriver.getAtomsElement (/Users/marcus.noll/Documents/git/bug-appium-xcuitest-driver/node_modules/appium-xcuitest-driver/lib/commands/web.js:296:11)
[debug] [W3C (9c2dd027)]     at XCUITestDriver.getName (/Users/marcus.noll/Documents/git/bug-appium-xcuitest-driver/node_modules/appium-xcuitest-driver/lib/commands/element.js:42:31)
[debug] [W3C (9c2dd027)]     at commandExecutor (/Users/marcus.noll/Documents/git/bug-appium-xcuitest-driver/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
[debug] [W3C (9c2dd027)]     at /Users/marcus.noll/Documents/git/bug-appium-xcuitest-driver/node_modules/async-lock/lib/index.js:154:12
[debug] [W3C (9c2dd027)]     at AsyncLock._promiseTry (/Users/marcus.noll/Documents/git/bug-appium-xcuitest-driver/node_modules/async-lock/lib/index.js:287:31)
[debug] [W3C (9c2dd027)]     at exec (/Users/marcus.noll/Documents/git/bug-appium-xcuitest-driver/node_modules/async-lock/lib/index.js:153:9)
[debug] [W3C (9c2dd027)]     at AsyncLock.acquire (/Users/marcus.noll/Documents/git/bug-appium-xcuitest-driver/node_modules/async-lock/lib/index.js:170:3)
[debug] [W3C (9c2dd027)]     at XCUITestDriver.executeCommand (/Users/marcus.noll/Documents/git/bug-appium-xcuitest-driver/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
[debug] [W3C (9c2dd027)]     at XCUITestDriver.executeCommand (/Users/marcus.noll/Documents/git/bug-appium-xcuitest-driver/node_modules/appium-xcuitest-driver/lib/driver.js:784:24)
[debug] [W3C (9c2dd027)]     at AppiumDriver.executeCommand (/Users/marcus.noll/Documents/git/bug-appium-xcuitest-driver/node_modules/appium/lib/appium.js:563:36)
[debug] [W3C (9c2dd027)]     at runMicrotasks (<anonymous>)
[debug] [W3C (9c2dd027)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[debug] [W3C (9c2dd027)]     at asyncHandler (/Users/marcus.noll/Documents/git/bug-appium-xcuitest-driver/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[HTTP] <-- GET /wd/hub/session/9c2dd027-4b95-4aa5-9806-4b875b135b39/element/:wdc:1657275218184/name 404 56 ms - 1967
```

</details>

I was able to trace the problem down to this change in appium-xcuitest-driver, which got shipped with version 3.51.0:
https://github.com/appium/appium-xcuitest-driver/commit/31c83daf7fc06c7b9eae3ee840194cbb93cc42d1. When forcing appium to use the previous version of appium-xcuitest-driver (3.50.2), everything works fine. However, that's not a viable solution, since we are using Sauce Labs to run our tests (I also contacted them).

There was a similar issue with `executeScript()`, which was fixed here: https://github.com/appium/appium-xcuitest-driver/commit/934779cbf7b9e89652bff5422d8b94906b88cbf7

## Link to Appium logs

https://gist.github.com/systemboogie/efbf2692bca615b4fba6f530b3d0fe8e

## Code To Reproduce Issue [ Good To Have ]

https://github.com/systemboogie/bug-appium-xcuitest-driver

**Comment by mykola-mokhnach** [comment]
Please try the most recent driver version (only available as part of Appium2)

**Comment by systemboogie** [comment]
@mykola-mokhnach 
Checked locally with version 2.0.0-beta.40. It works! Sorry for the noise and thanks a bunch for your quick response! ❤️ I guess you don't fix issues in version 1.x anymore, right? 🥺

**Comment by mykola-mokhnach** [comment]
Unfortunately we don't have much resources to maintain both 1.x and continue working on 2.x branch.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
