### ISSUE TITLE
Getting error while staring appium "Error: Cannot find module 'appium/driver'"

### ISSUE THREAD

**Issue by maheshchaudharCoupa** [appium/appium#17155]
I have installed the appium 2.0 beta version using command " npm install -g appium@2.0.0-beta.40"
Also i have installed uiautomator2 driver using  "appium driver install uiautomator2". But when am starting appium am getting error 

[Appium] Welcome to Appium v2.0.0-beta.40
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /root/.appium/node_modules/appium-uiautomator2-driver
[Appium] Could not load driver 'uiautomator2', so it will not be available. Error in loading the driver was: Cannot find module 'appium/driver'
[Appium] Require stack:
[Appium] - /root/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/build/lib/driver.js
[Appium] - /root/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/build/index.js
[Appium] - /root/.appium/node_modules/appium-uiautomator2-driver/build/lib/driver.js
[Appium] - /root/.appium/node_modules/appium-uiautomator2-driver/build/index.js
[Appium] - /usr/lib/node_modules/appium/build/lib/extension/extension-config.js
[Appium] - /usr/lib/node_modules/appium/build/lib/cli/extension-command.js
[Appium] - /usr/lib/node_modules/appium/build/lib/cli/driver-command.js
[Appium] - /usr/lib/node_modules/appium/build/lib/cli/extension.js
[Appium] - /usr/lib/node_modules/appium/build/lib/main.js
[Appium] - /usr/lib/node_modules/appium/index.js
[debug] [Appium] Error: Cannot find module 'appium/driver'
[debug] [Appium] Require stack:
[debug] [Appium] - /root/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/build/lib/driver.js
[debug] [Appium] - /root/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/build/index.js
[debug] [Appium] - /root/.appium/node_modules/appium-uiautomator2-driver/build/lib/driver.js
[debug] [Appium] - /root/.appium/node_modules/appium-uiautomator2-driver/build/index.js
[debug] [Appium] - /usr/lib/node_modules/appium/build/lib/extension/extension-config.js
[debug] [Appium] - /usr/lib/node_modules/appium/build/lib/cli/extension-command.js
[debug] [Appium] - /usr/lib/node_modules/appium/build/lib/cli/driver-command.js
[debug] [Appium] - /usr/lib/node_modules/appium/build/lib/cli/extension.js
[debug] [Appium] - /usr/lib/node_modules/appium/build/lib/main.js
[debug] [Appium] - /usr/lib/node_modules/appium/index.js
[debug] [Appium]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:974:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:101:18)
[debug] [Appium]     at Object.<anonymous> (/root/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/driver.js:1:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:950:32)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:974:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:101:18)
[debug] [Appium]     at Object.<anonymous> (/root/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/index.js:3:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:950:32)
[debug] [Appium]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[debug] [Appium]     at Module.require (internal/modules/cjs/loader.js:974:19)
[debug] [Appium]     at require (internal/modules/cjs/helpers.js:101:18)
[debug] [Appium]     at Object.<anonymous> (/root/.appium/node_modules/appium-uiautomator2-driver/lib/driver.js:12:1)
[debug] [Appium]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[debug] [Appium]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[debug] [Appium]     at Module.load (internal/modules/cjs/loader.js:950:32)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - uiautomator2@2.1.0 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.

**Comment by mykola-mokhnach** [comment]
Please update npm to version 7+.
Closed as duplicate

**Comment by maheshchaudharCoupa** [comment]
Wroked .. Thanks a lot !
