### ISSUE TITLE
autoGrantPermissions Not Working With Android OS 12

### ISSUE THREAD

**Issue by askariya** [appium/appium#17169]
## The problem

If I specify autoGrantPermissions should be set to true in my Automated Test and the Device under test uses Android OS 12, the permission popups appear anyway although they should have been automatically granted. If I try the same thing with a Device running Android OS 11, this does not happen.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Desktop OS/version used to run Appium: Windows 10
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android OS 12
* Real device or emulator/simulator: Real Device - Samsung S6 Lite
* Appium CLI or Appium.app|exe: Appium CLI

## Details

See The Problem.

## Link to Appium logs

https://gist.github.com/askariya/b0d38818296a861fc351d20d2f80bd06

## Code To Reproduce Issue [ Good To Have ]

I am setting the capabilities like so. 
`appiumOptions.AddAdditionalCapability(MobileCapabilityType.DeviceName, "Android 28");
appiumOptions.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Android");
appiumOptions.AddAdditionalCapability(MobileCapabilityType.PlatformVersion, "12.0");
appiumOptions.AddAdditionalCapability("autoGrantPermissions", "true");`

**Comment by mykola-mokhnach** [comment]
The server log looks completely fine to me. App install is being performed with `-g` argument, which makes adb to automatically grant requested app permissions:

> [debug] [ADB] Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -P 5037 -s R52R70F1FZA install -g C:\Users\arunalu.x.kariyawasa\Documents\DriverMate\Archives\APKs\com.trapezegroup.drivermatexam.apk'

Which permission does the device ask? Could it be an adb bug?

**Comment by askariya** [comment]
The Device asks for the following permissions:
- Access Files on device
- Device's location
- Make/manage Phone Calls
- Record Audio
- Take Pictures and Record Video
Maybe it's a bug in ADB like you said; I updated to the newest version (33.0.2) and it seems to still be there.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by sharutkarsh** [comment]
Now autograntpermissions is not working on Android 13 devices such as pixel with appium, can someone tell if this appium side compatibility issue with Android 13?

**Comment by KazuCocoa** [comment]
Could you share the full appium log as GitHub GIST?
It worked Pixel 4 for example with Android 13 and our test apps like https://github.com/appium/ruby_lib_core/blob/master/test/functional/app/api.apk?raw=true . With `appium:autoGrantPermissions` true, the app via App Info (settings app) shown all permissions were allowed while false did not.

**Comment by sharutkarsh** [comment]
> appium:autoGrantPermissions

can you try for pixel7 also for location permission pop ups 
like this 
https://i.stack.imgur.com/14lw9.png

**Comment by KazuCocoa** [comment]
I don't have the model. I just checked with test apk's permissions as below.
I checked compile SDK version 31 also changed to allow only xxxx when the auto grant was enabled while don't allow when it was disabled.
https://github.com/appium/android-apidemos
![image](https://user-images.githubusercontent.com/5511591/209296165-28eedf2d-1615-42fe-a39c-d0c83c265dbb.png)

Could you check the app's permission as well? I wonder the auto grant stuff can change the default value, but OS requires user interaction once regardless the permission grant status.

**Comment by sharutkarsh** [comment]
> I don't have the model. I just checked with test apk's permissions as below. (if you have downloadable test apk (not via play store), it may help) I checked compile SDK version 31 also changed to allow only xxxx when the auto grant was enabled while don't allow when it was disabled. https://github.com/appium/android-apidemos ![image](https://user-images.githubusercontent.com/5511591/209296165-28eedf2d-1615-42fe-a39c-d0c83c265dbb.png)
> 
> Could you check the app's permission as well? I wonder the auto grant stuff can change the default value, but OS requires user interaction once regardless the permission grant status.

Are you talking about driver.updatesettings command to enable these permissions?
I'm not sure how it will help.
I cant share apk 
https://appium.io/docs/en/commands/session/settings/update-settings/

**Comment by KazuCocoa** [comment]
No, I'm only saying `'appium:autoGrantPermissions'` capability right now. When I set the capability as `true`, the app had "Allow only xxxx". When it was false, the location permission had "Don't allow". I wonder your app's location permission's status when you set `'appium:autoGrantPermissions'` as true

**Comment by sharutkarsh** [comment]
> 

When I use this capability appium:autoGrantPermissions nothing happens, that popup remains there on the screen and automation gets stuck there as the popup was not handled. I have used xpaths and click on allow to handle the popup to proceed ahead. But this capability appium:autoGrantPermissions doesn't works wheather we set it to false or true, the behaviour is same.

**Comment by KazuCocoa** [comment]
What about the app information's permission preference like what I've attached as a screenshot? The popup behavior could differ from the app information's status (it depends on the app implementation). So, it would be helpful to check the system's permission status

**Comment by KazuCocoa** [comment]
and it would be also nice to check manually install the app with `adb install -g /path/to/the/app` and see how the popup behavior will be.

**Comment by sharutkarsh** [comment]
I see you asking to check on a local device with adb install.

And, about the app information's permission preference like what you've attached as a screenshot. In my case it dosent select any option  also i don't have UI like the radio buttons you shared, it's like the image i shared previously.

I think you can't help me, thanks 👍

**Comment by KazuCocoa** [comment]
>  In my case it dosent select any option also i don't have UI...

oh... it's interesting. Potentially... something SDK version stuff (e.g. compile sdk version, mini sdk version etc), or something implementation thing I guess.
Anyway, Appium does what `adb install -g /path/to/the/app` does in `autoGrantPermissions`, so theoretically the capability's behavior should be the same as with `-g` installation behavior

**Comment by sharutkarsh** [comment]
Thank you for sharing this information

**Comment by prasanta-biswas** [comment]
@KazuCocoa @mykola-mokhnach This is happening in appium 2.4.1. Tried the same in 2.0.1 and it is working.

**Comment by Olgash7318** [comment]
Appium 2.5.1- the auto grant permissions is not working anymore, I'm not sure about previous versions of appium 2, but it worked perfectly in Appium 1x (Really miss the old version with close/launch/reset app)

**Comment by prasanta-biswas** [comment]
@Olgash7318 I found a workaround for this. Just after creating driver instance, you can call this extension method to update the settings to accept all permission dialogs.

```
Map<String, Object> params = new HashMap<String, Object>() {
            {
                this.put("permissions", "all");
                this.put("appPackage", my.app.package); // defaults to app under test if not provided
                this.put("action", "grant"); // defaults to grant if not provided
            }
        };
driver.executeScript("mobile: changePermissions", params);
```
After executing this, you won't get any permission popups. Every permission that the app requests is already granted.
For further details on this extension method, please visit the documentation [page](https://github.com/appium/appium-uiautomator2-driver#mobile-changepermissions).

**Comment by prasanta-biswas** [comment]
@mykola-mokhnach this is a real issue. Please check this in the newer Appium version.
