### ISSUE TITLE
Appium Automatically Passes in browserName while appPackage is Already Passed in

### ISSUE THREAD

**Issue by CadeHowarth** [appium/appium#17197]
## The problem

I am trying to run a natively installed app, and have setup my appActivity and appPackage capabilities to include the correct strings, but whenever I run my test I receive an error stipulating that I cannot have browserName and appPackage in the same capability set.

## Environment

* Appium version: 1.22.3
* Desktop OS/version: Windows 11 Pro
* Node.js version): 12.8.1
* Mobile platform/version: Android 11 API 32
* Real device or emulator/simulator: Emulator

## Details

I have dug through all of the Appium server logs and tried to understand it, and from what I can gather, it seems that Appium is automatically passing in the browserName capability when my configuration file does not contain it anywhere. I have even attempted to pass in the browserName capability with "null" or an empty string, but then it only returns another error stipulating that it cannot read undefined. I cannot find where in my node_modules Appium is passing in the browserName capability. 

For more information, I am running Appium alongside Nightwatch JS in order to test a native app running on an Android Studio emulator I have configured. Below I have pasted my configuration and environment variables, and the error I receive upon trying to run the test.

By passing in the "app" desired capability, and pasting in the correct directory path into the string, the test works flawlessly without attempting to open a browser instance. However, I am trying to bypass having to reinstall the app every time by using that capability, and have created a snapshot of my emulator where the app is already installed and preliminary actions having been taken. However, since having added in the appPackage and appActivity capabilities, I have been getting this error as Appium passes in the browserName without me asking for it.

## Link to Appium logs

https://gist.github.com/CadeHowarth/65491bac81db32a340ebd3800f4edc09

## Code To Reproduce Issue

  test_settings: {

    androidNative: {
      selenium_start_process: false,
      selenium_port: 4723,
      selenium_host: "127.0.0.1",
      selenium_path: "/wd/hub",

    desiredCapabilities: {
        appiumVersion: "1.22.3",
        automationName: "Appium",
        platformName: "Android",
        platformVersion: "11.0",
        avd: "Samsung_Galaxy_Tab_S7_API_32",
        deviceName: "Samsung Galaxy Tab S7",
        appActivity: "<acitivtyString>",
        appPackage: "<packageString>",
        browserName: "",
        autoGrantPermissions: true
    },
      appium: {
        start_process: true,
        noReset: true,
        fullReset: false
      }
    }
  }

**Comment by KazuCocoa** [comment]
```
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"browserName":"firefox","appiumVersion":"1.22.3","automationName":"Appium","platformName":"Android","platformVersion":"11.0","avd":"Samsung_Galaxy_Tab_S7_API_32","appActivity":"com.enexsolutions.PestPad.MainActivity","appPackage":"com.enexsolutions.PestPad","autoGrantPermissions":true,"name":"001 Sales Create Customer"},"capabilities":{"alwaysMatch":{"browserName":"firefox","platformName":"Android"}}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"browserName":"firefox","appiumVersion":"1.22.3","automationName":"Appium","platformName":"Android","platformVersion":"11.0","avd":"Samsung_Galaxy_Tab_S7_API_32","appActivity":"com.enexsolutions.PestPad.MainActivity","appPackage":"com.enexsolutions.PestPad","autoGrantPermissions":true,"name":"001 Sales Create Customer"},null,{"alwaysMatch":{"browserName":"firefox","platformName":"Android"}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1657744603594 (14:36:43 GMT-0600 (Mountain Daylight Time))
```

Your client sent `"browserName":"firefox"` as the attached log.
Did you say this was unexpected for you? Then, maybe something in your client sent it.

**Comment by CadeHowarth** [comment]
Yeah that was one of the first things I noticed, and it is unexpected.. It's obviously being passed in, but I don't know from where. It's not present in the desired capabilities that I setup, so it must be coming from the driver that Appium is running.

**Comment by jlipps** [comment]
Drivers don't pass in capabilities; they receive them. If you share your client code we can maybe see what's happening. Are you using the appropriate remote web driver class in your client?

**Comment by CadeHowarth** [comment]
I'd be happy to share the code. There's a lot of files receiving content from Appium, so I'm not sure what constitutes as a client in this situation however. Do you mean my test files, my full configuration file, or my emulator? To answer your question I am not using any webdriver class in my config, I think the closest I get to that is my selenium port and host that I have set to match Appium; which I provided in my original post.

**Comment by CadeHowarth** [comment]
Upon further digging, the problem may not lie with Appium, but my Nightwatch installation alongside it. Looking over the Appium logs, it appears the calling of the W3C web driver protocol is what is populating the browserName string. The W3C protocol is the default that Nightwatch utilizes. I am in the process of looking over the npm installation to see if it could be referencing some default configuration that I have not found yet.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
