### ISSUE TITLE
appium-doctor warns: android could NOT be found in SDK path

### ISSUE THREAD

**Issue by omprakashchavan01** [appium/appium#17195]
appium-doctor warns "_android could NOT be found in C:\Users\<user_name>\AppData\Local\Android\Sdk!_" even when ANDROID_HOME is set. It can find 'adb' and 'emulator' though at the same path (see the appium-doctor logs below. Please ignore the Java related errors since Java is not yet installed). So no issues with the SDK path as such.

As per the suggestion in the logs (i.e. Manually install android and add it to PATH), I also tried installing command line tools from here: https://developer.android.com/studio#cmdline-tools and setting it to PATH. But same error is observed.
Also note that android.bat is not seen under cmdline-tools/latest/bin folder. So sounds like the suggestion is also not working.

P.S.: The issue resolves only after installing "Android SDK Tools" which is now Obsolete. Also, the android.bat is found under the "tools" folder which is quite strange (if we go by appium-doctor's suggestion in the logs). Sounds like Appium is still needing this folder which is now obsolete from Android Studio perspective. Please confirm if we still need this obsolete package to continue using Appium or there is any other way?

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 2.0 Beta 40
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 11
* Node.js version (unless using Appium.app|exe): Latest LTS
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: Appium CLI

## Appium Doctor logs:

C:\Users\ompra>appium-doctor --android
info AppiumDoctor Appium Doctor v.1.16.0
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: C:\Program Files\nodejs\node.EXE
info AppiumDoctor  ✔ Node version is 16.16.0
info AppiumDoctor  ✔ ANDROID_HOME is set to: C:\Users\<user_name>\AppData\Local\Android\Sdk
WARN AppiumDoctor  ✖ JAVA_HOME is set to 'C:\Program Files\Java\jdk-17.0.1' but this is NOT a valid path!
info AppiumDoctor    Checking adb, android, emulator
info AppiumDoctor      'adb' is in C:\Users\<user_name>\AppData\Local\Android\Sdk\platform-tools\adb.exe
info AppiumDoctor      'emulator' is in C:\Users\<user_name>\AppData\Local\Android\Sdk\emulator\emulator.exe
**WARN AppiumDoctor  ✖ android could NOT be found in C:\Users\<user_name>\AppData\Local\Android\Sdk!**
WARN AppiumDoctor  ✖ 'bin' subfolder does not exist under 'C:\Program Files\Java\jdk-17.0.1'. Is %JAVA_HOME% set to a proper value?
info AppiumDoctor ### Diagnostic for necessary dependencies completed, 3 fixes needed. ###
info AppiumDoctor
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
WARN AppiumDoctor  ✖ gst-launch-1.0.exe and/or gst-inspect-1.0.exe cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 5 fixes possible. ###
info AppiumDoctor
info AppiumDoctor ### Manual Fixes Needed ###
info AppiumDoctor The configuration cannot be automatically fixed, please do the following first:
WARN AppiumDoctor  ➜ Make sure the environment variable JAVA_HOME is properly configured for the Appium process. Refer https://github.com/appium/java-client/blob/master/docs/environment.md for more details.
WARN AppiumDoctor  ➜ Manually install android and add it to PATH. https://developer.android.com/studio#cmdline-tools and https://developer.android.com/studio/intro/update#sdk-manager may help to setup.
WARN AppiumDoctor  ➜ Set %JAVA_HOME% environment variable to the root folder path of your local JDK installation

**Comment by mykola-mokhnach** [comment]
@KazuCocoa may you know what it is about?

**Comment by omprakashchavan01** [comment]
Ok so is it safe to just ignore the warning?

**Comment by mykola-mokhnach** [comment]
I assume it is, but let us check first. Maybe it just needs to be removed as obsolete

**Comment by KazuCocoa** [comment]
I don't remember right now, but perhaps the command was emulator related thing
My local has `android`, but potentially it has been replaced with avdmanager etc

**Comment by KazuCocoa** [comment]
oh, actually it is deprecated for now.
```
kazu$ android
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command ""

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
```

**Comment by mykola-mokhnach** [comment]
lets then either remove this check or include sdkmanager/avdmanager validation instead

**Comment by jlipps** [comment]
this is a very inconvenient string to grep across a project for :-/

**Comment by omprakashchavan01** [comment]
Apparently it looks like I can automate tests even without cmdline-tools folder. If that's the case, do we really need a check for sdkmanager/avdmanager validation? I'm bit confused here. The only environment variable I have set is ANDROID_HOME and updated PATH to include %ANDROID_HOME%\platform-tools (needed for "adb"). Everything just work fine. I don't need "cmdline-tools" as well as "tools" folder.

**Comment by KazuCocoa** [comment]
Maybe no, nowadays since Android emulators are managed by `emulator` command.
I have searched the words in Appium repositories, but we no longer used them.

Note:
we should clean up `android` command stuff like https://github.com/appium/appium-adb/blob/0898bfc6959253339254dab4123c419fa223b6e0/lib/tools/system-calls.js#L70

**Comment by mykola-mokhnach** [comment]
Removed the obsolete check in the PR above. It won't be present anymore in the following Appium releases

**Comment by anabeatrizzz** [comment]
@omprakashchavan01 what about `JAVA_HOME is set to ... but this is NOT a valid path!` and `'bin' subfolder does not exist under 'C:\Program Files (x86)\Java\jre1.8.0_333'. Is %JAVA_HOME% set to a proper value?` warnings, any solution?

**Comment by Tigrulla** [comment]
@omprakashchavan01 

The Android SDK download is now half the size that it was before. One thing that has disappeared is the android.bat file.

This Link will give you a Android SDK that will install.
[http://dl-ssl.google.com/android/repository/sdk-tools-windows-4333796.zip 99](http://dl-ssl.google.com/android/repository/sdk-tools-windows-4333796.zip)

It is not the latest but it will work.


[http://dl-ssl.google.com/android/repository/sdk-tools-windows-4333796.zip](url)

**Comment by akhlaqdelhi** [comment]
Surprisingly the "apkanalyzer" file was there but without ".bat" extension, I renamed it with ".bat" and the issue got resolved.

**Comment by mariamafifi** [comment]
> Surprisingly the "apkanalyzer" file was there but without ".bat" extension, I renamed it with ".bat" and the issue got resolved.

thank you , the issue resolved :D

**Comment by danielandrioli** [comment]
> Surprisingly the "apkanalyzer" file was there but without ".bat" extension, I renamed it with ".bat" and the issue got resolved.

Yea, this worked fine!

**Comment by SumayaHossain** [comment]
That worked 

> Surprisingly the "apkanalyzer" file was there but without ".bat" extension, I renamed it with ".bat" and the issue got resolved.

This worked for me too

**Comment by KazuCocoa** [comment]
Did the `apkanalyzer` itself was executable on Windows? So, in case even without `.bat`, the file works on Windows.
For now, https://github.com/appium/appium-adb/blob/d407196aeb41e621eed3f65af98d4bab89880edc/lib/tools/system-calls.js#L75 expects Windows env has `.bat`, but in case newer Android SDK does not have them, and they work on Windows, we may need to tweak the logic somehow to handle it on Win better

**Comment by pierresouza** [comment]
first of all, sorry if i write something wrong, english is not my native language.

hi guys, i just need some help, then i use the appium-doctor se just say that he can't find the android, i try everything that i could, i set the JAVA_HOME and ANDROID_HOME without problems, but the android was never found by the command appium-doctor, and that is the log i receive:

### Appium Log

info AppiumDoctor Appium Doctor v.1.16.2
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
(node:21675) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info AppiumDoctor  ✔ The Node.js binary was found at: /home/linuxbrew/.linuxbrew/bin/node
info AppiumDoctor  ✔ Node version is 21.2.0
info AppiumDoctor  ✔ ANDROID_HOME is set to: /home/pierresouza/Android/Sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /usr/lib/jvm/default-java
info AppiumDoctor    Checking adb, android, emulator, apkanalyzer
info AppiumDoctor      'adb' is in /home/pierresouza/Android/Sdk/platform-tools/adb
info AppiumDoctor      'emulator' is in /home/pierresouza/Android/Sdk/emulator/emulator
info AppiumDoctor      'apkanalyzer' is in /home/pierresouza/Android/Sdk/cmdline-tools/latest/bin/apkanalyzer
WARN AppiumDoctor  ✖ android could NOT be found in /home/pierresouza/Android/Sdk!
info AppiumDoctor  ✔ 'bin' subfolder exists under '/usr/lib/jvm/default-java'
info AppiumDoctor ### Diagnostic for necessary dependencies completed, one fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
WARN AppiumDoctor  ✖ mjpeg-consumer cannot be found.
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
info AppiumDoctor  ✔ gst-launch-1.0 and gst-inspect-1.0 are installed at: /usr/bin/gst-launch-1.0 and /usr/bin/gst-inspect-1.0
info AppiumDoctor ### Diagnostic for optional dependencies completed, 4 fixes possible. ###
info AppiumDoctor 
info AppiumDoctor ### Manual Fixes Needed ###
info AppiumDoctor The configuration cannot be automatically fixed, please do the following first:
WARN AppiumDoctor  ➜ Manually install android and add it to PATH. https://developer.android.com/studio#cmdline-tools and https://developer.android.com/studio/intro/update#sdk-manager may help to setup.
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: http://appium.io/docs/en/writing-running-appium/image-comparison/
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'.
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it
info AppiumDoctor 
info AppiumDoctor ###
info AppiumDoctor 
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor

**Comment by KazuCocoa** [comment]
Please use the latest one, https://github.com/appium/appium/tree/master/packages/doctor
which is available with `npm install @appium/doctor -g`

**Comment by Riiuzaky** [comment]
> Utilice la última versión, https://github.com/appium/appium/tree/master/packages/doctor , que está disponible con`npm install @appium/doctor -g`

como actualizo me dice que ya esta y me sigue apareciendo el mismo error

**Comment by lonely-caat** [comment]
> first of all, sorry if i write something wrong, english is not my native language.
> 
> hi guys, i just need some help, then i use the appium-doctor se just say that he can't find the android, i try everything that i could, i set the JAVA_HOME and ANDROID_HOME without problems, but the android was never found by the command appium-doctor, and that is the log i receive:
> 
> ### Appium Log
> info AppiumDoctor Appium Doctor v.1.16.2 info AppiumDoctor ### Diagnostic for necessary dependencies starting ### (node:21675) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead. (Use `node --trace-deprecation ...` to show where the warning was created) info AppiumDoctor ✔ The Node.js binary was found at: /home/linuxbrew/.linuxbrew/bin/node info AppiumDoctor ✔ Node version is 21.2.0 info AppiumDoctor ✔ ANDROID_HOME is set to: /home/<user_name>/Android/Sdk info AppiumDoctor ✔ JAVA_HOME is set to: /usr/lib/jvm/default-java info AppiumDoctor Checking adb, android, emulator, apkanalyzer info AppiumDoctor 'adb' is in /home/<user_name>/Android/Sdk/platform-tools/adb info AppiumDoctor 'emulator' is in /home/<user_name>/Android/Sdk/emulator/emulator info AppiumDoctor 'apkanalyzer' is in /home/<user_name>/Android/Sdk/cmdline-tools/latest/bin/apkanalyzer WARN AppiumDoctor ✖ android could NOT be found in /home/<user_name>/Android/Sdk! info AppiumDoctor ✔ 'bin' subfolder exists under '/usr/lib/jvm/default-java' info AppiumDoctor ### Diagnostic for necessary dependencies completed, one fix needed. ### info AppiumDoctor info AppiumDoctor ### Diagnostic for optional dependencies starting ### WARN AppiumDoctor ✖ opencv4nodejs cannot be found. WARN AppiumDoctor ✖ ffmpeg cannot be found WARN AppiumDoctor ✖ mjpeg-consumer cannot be found. WARN AppiumDoctor ✖ bundletool.jar cannot be found info AppiumDoctor ✔ gst-launch-1.0 and gst-inspect-1.0 are installed at: /usr/bin/gst-launch-1.0 and /usr/bin/gst-inspect-1.0 info AppiumDoctor ### Diagnostic for optional dependencies completed, 4 fixes possible. ### info AppiumDoctor info AppiumDoctor ### Manual Fixes Needed ### info AppiumDoctor The configuration cannot be automatically fixed, please do the following first: WARN AppiumDoctor ➜ Manually install android and add it to PATH. https://developer.android.com/studio#cmdline-tools and https://developer.android.com/studio/intro/update#sdk-manager may help to setup. info AppiumDoctor info AppiumDoctor ### Optional Manual Fixes ### info AppiumDoctor The configuration can install optionally. Please do the following manually: WARN AppiumDoctor ➜ Why opencv4nodejs is needed and how to install it: http://appium.io/docs/en/writing-running-appium/image-comparison/ WARN AppiumDoctor ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it WARN AppiumDoctor ➜ mjpeg-consumer module is required to use MJPEG-over-HTTP features. Please install it with 'npm i -g mjpeg-consumer'. WARN AppiumDoctor ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it info AppiumDoctor info AppiumDoctor ### info AppiumDoctor info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied! info AppiumDoctor

@pierresouza were you able to resolve this issue?

**Comment by Pedro1105-sp** [comment]
> Surpreendentemente, o arquivo "apkanalyzer" estava lá, mas sem a extensão ".bat", renomeei-o para ".bat" e o problema foi resolvido.

Funcionou aqui, tbm! Obrigado!

**Comment by Yetta-Yi** [comment]
android could NOT be found in SDK path
--------------------------------------------------
SDK download by Android Studio without C:\Users\XXX\AppData\Local\Android\Sdk\tools, after download, it will be solved.

**Comment by ashokchhetri7** [comment]
Go to Andriod Studio, **SDK Manager >> SDK Tools** and choose Hide Obsolete Packages and 
Install the “_Android SDK Tools_” which was marked as Obsolete

**Comment by leticiasilverio** [comment]
Guys, it works perfectly for me:
https://stackoverflow.com/questions/47081004/apkanalyzer-is-not-recognized-as-an-internal-or-external-command

**Comment by moshe-pendo** [comment]
Patch: create symbolic link to folder `cmdline-tools` in the `sdk` folder.

`ln -s cmdline-tools android`

**Comment by 17337162621254271304** [comment]
cd ~/Library/Android/sdk
mkdir android
