### ISSUE TITLE
appium-chromedriver: postinstall should not attempt to install chromedriver infinity times

### ISSUE THREAD

**Issue by boneskull** [appium/appium#17196]
When running the postinstall lifecycle script `npm-install.js`, there's a call to `waitForDeps()`.  If the callback fails _prior_ to the `doInstall()` call, it will continue in an infinite loop, because:

```js
  waitForDeps(function wait (err) {
    if (err) {
      // this should only happen on local install (i.e., npm install in this directory)
      log.warn(`Unable to import install script: ${err.message}`);
      log.warn(`Re-run 'npm run chromedriver' manually.`);
      return;
    }
    require(BUILD_PATH).doInstall().catch(function installError (err) {
      // ...
    });
  }
```

If `err` is truthy, then the callback will exit continually be called again.  Either that `return` should be a `process.exit(1)`, or there should be a timeout.

I'm unsure who "owns" `appium-chromedriver`--I can address this myself if needed--but just wanted to create a tracking issue anyway.

This was causing infinite execution time in Appium's E2E tests due to a misconfiguration.

**Comment by boneskull** [comment]
This exacerbates #17167

**Comment by mykola-mokhnach** [comment]
@boneskull apqium-chromedriver is used by both android drivers to implement hybrid mode. Feel free to fix the script if you know how to solve the original issue
