### ISSUE TITLE
Appium missed showing some elements from the second time connects to the IOS react native app

### ISSUE THREAD

**Issue by hoangnguyen14** [appium/appium#17212]
## The problem

Appium missed some Elements when opening the IOS react-native app from the second session on IOS

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac Mini M1 2020
* Node.js version (unless using Appium.app|exe): 14.17.6
* Npm or Yarn package manager:6.14.15
* Mobile platform/version under test: IOS 14.4
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Details

When I try to inspect the App Source at the first time after the app is installed on my real device, then App Source is showed as my expectation, but when I try to inspect the App Source from the second time (without reinstall), the App Source missed some Elements

I used getSourcePage function to get the App Source from IOS and see that XCUTEST returned different value of source from second time when compared with source of the first time opening the app
you can see that there is no element XCUIElementTypeStaticText with name = submitBtn
here is the log: 
https://gist.github.com/hoangnguyen14/eb4df6b19d61f53766b225142d1c9dc0

**Comment by mykola-mokhnach** [comment]
- Appium 1.21 is out of date. Please try the most recent driver version (only available as part of Appium 2)
- The actual page source is based on xctest output. You could check what xctest itself generates by using https://github.com/appium/appium-xcuitest-driver#mobile-source and setting the `format` arg to `description`.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
