### ISSUE TITLE
Encountered internal error running command: Error: Error getting device API level. Original error: Error executing adbExec.

### ISSUE THREAD

**Issue by SushmaE1** [appium/appium#17222]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac 11.6.7
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test: Android
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe:

## Details

When i am running the eclipse code for real android device, i am getting below error

## Code To Reproduce Issue [ Good To Have ]
[issue.txt](https://github.com/appium/appium/files/9131105/issue.txt)

Log and code are attached

**Comment by mykola-mokhnach** [comment]
It looks that there is either a problem with the device or adb (it times out)
Make sure Android sdk is up to date and/or replace the device under test

**Comment by StephanB75** [comment]
maybe you have to re-enable developer debugging mode

**Comment by bipin-k** [comment]
@SushmaE1 What is the OS version installed in your device? Also, please check what is the output you are getting with manually executing `adb` commands with `adb shell getprop ro.build.version.sdk`. 
If you are getting expected response from above `adb` command, then please increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability.

**Comment by SushmaE1** [comment]
My Device OS version is 12.
When i execute 'adb shell getprop ro.build.version.sdk' in terminal it returns 32
I have added 
cap.setCapability(AndroidMobileCapabilityType.ADB_EXEC_TIMEOUT, 10000);

But it is same even after that

**Comment by SushmaE1** [comment]
I have increased the limit to 40000 then it started working.
