### ISSUE TITLE
Error in UIAutomator2 due appium-uiautomator2-server apk not found

### ISSUE THREAD

**Issue by alvarolgn** [appium/appium#17221]
## The problem

UIAutomator2 is not working successfully after upgrading to 2.4.5 because appium-uiautomator2-server-v5.4.0.apk is not found.

## Environment

* Appium version (or git revision) that exhibits the issue: 
  * v2.0.0-beta.27
  * uiautomator2@2.4.5
* Last Appium version that did not exhibit the issue (if applicable): 
  * v2.0.0-beta.27
  * uiautomator2@2.2.0 
* Desktop OS/version used to run Appium: macOS 11.4 (20F71)
* Node.js version (unless using Appium.app|exe): v17.8.0
* Npm or Yarn package manager: npm@8.5.5
* Mobile platform/version under test: Android10
* Real device or emulator/simulator: Real Redmi 9
* Appium CLI or Appium.app|exe: appium cli

## Details

After the following upgrade, uiautomator2 is not working due the attached error in appium logs

```
 $ appium driver update uiautomator2
✔ Checking if driver 'uiautomator2' is updatable
✔ Checking if driver 'uiautomator2' needs an update
✔ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver@2.4.5'
✔ Updating driver 'uiautomator2' from 2.0.5 to 2.4.5
Update report:
- driver uiautomator2 updated: 2.0.5 => 2.4.5
```

```
An unknown server-side error occurred while processing the command. Original error: The file at '/Users/CX02592/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v5.4.0.apk' does not exist or is not accessible
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:384:35)
```

## Link to Appium logs

 [GIST](https://gist.github.com/alvarolgn/4159e5378174140601e769c2290fa462)

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `examples` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in examples, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Try to also update the server to the most recent version and reinstall the driver.
Do you also have any antivirus software installed that might be deleting the APK?

**Comment by alvarolgn** [comment]
Still having the same problem after upgrade. I think that antivirus shouldn't be the problem here as I have another versions of that apk in the expected path:

```
$ ls -l /Users/CX02592/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/
total 30504
-rw-r--r--  1 CX02592  staff    733759 18 jul 10:50 appium-uiautomator2-server-debug-androidTest.apk
-rw-r--r--  1 CX02592  staff     14149 18 jul 10:50 appium-uiautomator2-server-debug-androidTest.apk.idsig
-rw-r--r--  1 CX02592  staff  14055209 18 jul 10:50 appium-uiautomator2-server-v5.6.2.apk
-rw-r--r--  1 CX02592  staff    116549 18 jul 10:50 appium-uiautomator2-server-v5.6.2.apk.idsig
```

**Comment by mykola-mokhnach** [comment]
Did you do full reinstall? (e.g. remove and install?)

**Comment by StephanB75** [comment]
the jenkins workspace is always completly wiped including the locally installed appium server and drivers.
With every test job everything is setup from the scratch (thats why i get always updated drivers and the bugs) ;)

**Comment by alvarolgn** [comment]
Yes, I did a full reinstall and still not working

**Comment by StephanB75** [comment]
could it be that there are leftovers on the emulator that cause that issue ?
