### ISSUE TITLE
Link to the appium examples is broken

### ISSUE THREAD

**Issue by mbenach** [appium/appium#17232]
Examples link on Appium.io give a 404.
https://github.com/appium/appium/tree/master/sample-code
The 'appium/appium' repository doesn't contain the 'sample-code' path in 'master'.

**Comment by KazuCocoa** [comment]
note: https://github.com/appium/appium/tree/1.x/sample-code

**Comment by CuongHoang69** [comment]
Oh man. I have to change the branch to find the document I need. Change to the banch with the right version you are using to find the doc

**Comment by KazuCocoa** [comment]
We're working on preparing appium 2, and the section is probably going to each repository mainly.
https://github.com/appium/appium/tree/master/packages/appium/sample-code will be thin examples.


I'll check later, but probably we can change the branch name in https://github.com/appium/appium.io directly for v1.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/17254#issuecomment-1192283855

**Comment by mbenach** [comment]
Thank you!


________________________________
