### ISSUE TITLE
Address `appium:` prefix in webdriverio new session creation documentation in appium.io

### ISSUE THREAD

**Issue by alliv8** [appium/appium#17238]
## The problem

Appium docs lists appium capabilities without the `appium:` keyword which fails (invalid caps) in Webdriverio when using W3C capabilities. How does the Appium team plan to tackle this?

## Environment

* WebdriverIO client

## Details

This issue is concerning as customers using appium specific capabilities like popup handling using W3C caps get confused when using WebdriverIO.

Visibility on this would also help us at BrowserStack to handle this nuance in our documentation accordingly as the python client for example, doesn't need `appium:` for W3C caps, whereas WebdriverIO does. This should also be handled within Appium documentation as well, when there are snippets being provided for JS.

Apologies if this is not the correct place to raise this, and if this is already being addressed with the Appium 2.0 project.

**Comment by alliv8** [comment]
Right but will Appium handle this for NodeJS code snippets in official documentation?

It gets confusing for users to copy a JS snippet from appium docs and then it doesn't work on the NodeJS client prescribed by Appium, i.e. WebdriverIO (in W3C mode).

**Comment by KazuCocoa** [comment]
Perhaps https://appium.io/docs/en/commands/session/create/ and https://appium.io/docs/en/about-appium/getting-started/v ...?
Current documentation in appium.io is for Appium 1 which supports MJSONWP and W3C, so I guess only the documentation cacn address w3c only case needs to to add `appium:` prefix for webdriverio. (I don't know if webdriverio sends both mjsonwp and w3c, or only either) For now, https://github.com/appium/appium.io will need a direct update.


Appium 2 documentation (we're preparing) will have links for each client repo/document, so perhaps clients' specific code in appium's documentation will only be in sample code like https://github.com/appium/appium/blob/master/packages/appium/sample-code/quickstarts/js/test.js

**Comment by jlipps** [comment]
Yes, the best answer is: in our Appium 2 docs, the sample code will work, as it does in the link @KazuCocoa shared :-)

**Comment by KazuCocoa** [comment]
Updated as https://github.com/appium/appium/pull/17264
It will be in appium.io
