### ISSUE TITLE
In macos12.4 when use appim http response error

### ISSUE THREAD

**Issue by leeyc0704** [appium/appium#17258]
## The problem

when i use appium to app auto test ,i need at the same time get data by http api, when my mac os verson is lower all is normal,but recently, because i want to test ios15+ , i update my imac, then api always retrun bellow（ occasional）:
Max retries exceeded with url: /_xx/xxx/xxx/query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd1159fa290>:
when i don't start appium test ,only  just runs api in cycles ，my api's response is always right, perhaps, it's because 
The number of local requests is too frequent, has any suggestion to me? thanks!

## Environment
* mac os 12.4 
* Appium version (or git revision) that exhibits the issue:1.22.3
* Desktop OS/version used to run Appium:server
* Mobile platform/version under test:ios15+
* Real device or emulator/simulator:real

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by mykola-mokhnach** [comment]
Closed because of no response
