### ISSUE TITLE
Swipe Element to the left and click on a Button is not working as expected in iOS

### ISSUE THREAD

**Issue by pallavichandrashekarjetty** [appium/appium#17253]
Description: Swipe Element to the left and click on a Button

We are facing a stale element issue while swiping an element to the left and clicking on the Delete button. 
In order to resolve this issue, I tried the below scenarios:
•	Recapturing the element before performing the action. 
•	Also added a logic to wait for the element to load
•	Added a logic if (element. Displayed) then perform the action> But even though the element is present and enabled on the screen, it is not passing the if condition.
•	Instead it is failing to recognize the element.
•	If I add just Click on the element after swipe> it is swiping the different elements and not clicking on it..

Do we have any existing issues for the same?

Expected result: We would like to click on the Delete button as shown below:
![image](https://user-images.githubusercontent.com/79142459/180208917-68a0add4-00a9-4048-8dd8-8d0d46353eda.png)

Actually below element is getting recognized after performing the click Operation and test case is failing because it is not recognizing the actual element .
![image](https://user-images.githubusercontent.com/79142459/180208976-21c5fb47-e957-41ff-a3f9-2f007ea26082.png)

code snippet Tried:
![image](https://user-images.githubusercontent.com/79142459/180209040-5d7f8acd-58b6-4c03-aed5-b943c6c29da6.png)

**Comment by mykola-mokhnach** [comment]
Try to click by coordinates instead

**Comment by mykola-mokhnach** [comment]
You could also try to play with appium:useNativeCachingStrategy capability (only available in recent driver releases)

**Comment by mykola-mokhnach** [comment]
Also please fill out the required issue info and provide the server log

**Comment by pallavichandrashekarjetty** [comment]
I tried using Locator but the same behavior. The Delete Button is enabled only after swipe left but I wonder why some other delete Button is highlighted upon clicking the delete id/name.


Please find below for the detailed exception:
OpenQA.Selenium.StaleElementReferenceException
  HResult=0x80131500
  Message=The previously found element ""Delete" Button" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Identity Binding from input {(
    Button, {{293.0, 586.5}, {82.0, 31.5}}, label: 'Delete',
    StaticText, {{308.0, 591.5}, {52.0, 22.0}}, label: 'Delete'
)}
  Source=WebDriver

**Comment by mykola-mokhnach** [comment]
Have you actually tried what is recommended in the error message as above?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
