### ISSUE TITLE
Request permissions for installing WinAppDriver instead of erroring

### ISSUE THREAD

**Issue by Richienb** [appium/appium#17271]
## The problem

Currently, administrator permissions are checked for but not requested:

https://github.com/appium/appium-windows-driver/blob/0dc89aa7ab467a8c6f6af40cad1c223defd48644/lib/installer.js#L150-L152

I have been successfully using https://github.com/jorangreef/sudo-prompt to attempt to request for administrator permissions for running the installer.

## Environment

- `appium-windows-driver`@`2.0.6`

**Comment by mykola-mokhnach** [comment]
Marking it as a feature request. @Richienb feel free to pop up a PR in order to improve this functionality

**Comment by mykola-mokhnach** [comment]
@Richienb Please check if https://github.com/appium/appium-windows-driver/pull/191 works for you
