### ISSUE TITLE
teen_process: subprocess doesn't actually stop until "close" timer fires

### ISSUE THREAD

**Issue by boneskull** [appium/appium#17282]
I noticed this when running the test suite, which was failing to exit in a timely manner.

When `Subprocess#stop()` gets called, there's a timer that gets set which will throw an error if the subprocess did not emit `close` within _n_ ms.

This timer actually causes the parent process to stay open (at least in Node.js v18) until the timer has expired. This is, by default, ten (10) seconds. 

This can be addressed by using `unref()`, which will tell Node.js to _not_ let the parent process run if the timer is the only thing left in the event loop.

**Comment by jlipps** [comment]
I think this explains a lot of weird stuff I've noticed. Sorry for being too clever!
