### ISSUE TITLE
Appium commands causing app to crash on iOS real devices

### ISSUE THREAD

**Issue by SpencerMelo** [appium/appium#17281]
## The problem

Appium command execution is causing the iOS application to crash.

Overview of what we are doing with our test:
- Open the app (Everything fine)
- Assert elements for login are visible (Everything fine)
- Perform Login (Everything fine)
- Assert some elements on the landing page are visible (Crash)
  - It crashes the application under test while checking the visibility of the element.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.22.3**
* Last Appium version that did not exhibit the issue (if applicable): **N/A**
* Desktop OS/version used to run Appium: **MacOS Monterey 12.4**
* Node.js version (unless using Appium.app|exe): **17.8.0**
* Npm or Yarn package manager: **NPM**
* Mobile platform/version under test: **iPhone 13 Pro Max, iOS 15.31**
* Real device or emulator/simulator: **Real device**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

- I can constantly reproduce when the following request is sent to the appium server (displayed command):
`[HTTP] --> GET /wd/hub/session/686a1db0-a3f3-4301-928a-c714122f07f0/element/C0000000-0000-0000-4105-000000000000/displayed`
- The request is returning success, but it's crashing the app, result of the command above:
`[HTTP] <-- GET /wd/hub/session/686a1db0-a3f3-4301-928a-c714122f07f0/element/C0000000-0000-0000-4105-000000000000/displayed 200 50 ms - 65`
- It does not crash on every scenario we run the `displayed` command on the server, but it ALWAYS crash on same group of scenarios.
- I happens when we are running automation (java-client) against the application, or we are sending commands via inspector.
- The app doesn't crash with any user/manual action.
- If the element is displayed or not and the command returns (true or false), the app will close, no matter what.

## Link to Appium logs

> [HTTP] --> GET /wd/hub/session/686a1db0-a3f3-4301-928a-c714122f07f0/element/C0000000-0000-0000-4105-000000000000/displayed
[HTTP] {}
[W3C (686a1db0)] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [WD Proxy] Matched '/wd/hub/session/686a1db0-a3f3-4301-928a-c714122f07f0/element/C0000000-0000-0000-4105-000000000000/displayed' to command name 'elementDisplayed'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/686a1db0-a3f3-4301-928a-c714122f07f0/element/C0000000-0000-0000-4105-000000000000/displayed] to [GET http://127.0.0.1:8100/session/1BC19F96-B234-4B87-82E7-091D23F8397C/element/C0000000-0000-0000-4105-000000000000/displayed] with no body
[debug] [WD Proxy] Got response with status 200: {"value":true,"sessionId":"1BC19F96-B234-4B87-82E7-091D23F8397C"}
[WD Proxy] Replacing sessionId 1BC19F96-B234-4B87-82E7-091D23F8397C with 686a1db0-a3f3-4301-928a-c714122f07f0
[HTTP] <-- GET /wd/hub/session/686a1db0-a3f3-4301-928a-c714122f07f0/element/C0000000-0000-0000-4105-000000000000/displayed 200 50 ms - 65

## Code To Reproduce Issue [ Good To Have ]
This might not be useful because on our automation we are using java, but this gives a glance on where we fail.
`new WebDriverWait(driver, Duration.ofSeconds(timeout)).until(ExpectedConditions.visibilityOfElementLocated(by));`

**Comment by SpencerMelo** [comment]
Some more notes:
- Commands like: findElement and click are working fine.

**Comment by mykola-mokhnach** [comment]
The visibility check in WDA is really hacky and uses some private API calls. You could try to check the device logs to get more details there, but I don't think much could be changed from the driver side.

**Comment by SpencerMelo** [comment]
@17275 I see on my logs that the appium server is using a really old XCUITestDriver:
`[Appium] Appium v1.22.3 creating new XCUITestDriver (v3.59.0) session`

Isn't it supposed to use the latest version of the XCUITestDriver?
https://github.com/appium/appium-xcuitest-driver/releases/tag/v4.7.4

**Comment by mykola-mokhnach** [comment]
The latest driver is only available for Appium2 
We do not maintain Appium1 since the beginning of this year

**Comment by SpencerMelo** [comment]
Sorry for not responding to this issue anymore @mykola-mokhnach 

The issue is with UITableView of iOS, when there is tons of elements available and you try to interact with it on Appium it causes the app to crash.

We did not find a fix and we are basically skipping this case, as it always crash.
I will close this issue anyway.

**Comment by mykola-mokhnach** [comment]
> Sorry for not responding to this issue anymore @mykola-mokhnach
> 
> The issue is with UITableView of iOS, when there is tons of elements available and you try to interact with it on Appium it causes the app to crash.
> 
> We did not find a fix and we are basically skipping this case, as it always crash. I will close this issue anyway.

I don't think there is anything we could do about it. WebDriverAgent is based on xctest, so if the latter fails to handle lerge hierrachies we'd fail as well. You could try the same scenario on your app with a vanilla xctest script and report the issue to Apple.

**Comment by SarmadSaleeem** [comment]
@SpencerMelo Did you find the solution. I am facing the same issue.

My IOS simulator is crashing on this line. Only crashing during automation. However, working fine doing manual testing.

Wait(driver).Until(SeleniumExtras.WaitHelpers.ExpectedConditions.ElementIsVisible(XPath));

@Dor-bl @mykola-mokhnach any idea about this.
