### ISSUE TITLE
Getting  An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: 'POST /wd/hub/session/*session Id*/*METHOD CALLED*' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

### ISSUE THREAD

**Issue by Void-SimonToMars** [appium/appium#17303]
## The problem

hello, i am having this pop up showing on Appium Inspector. 
1)I start the server in localhost trought GUI
2)i connected to server from inspector Appium (setup is minimal : localhost , 4723 as port,"platformName": "Android" as caps)
3) inspector is now connected with my phisical device and all works fine
problem is when i run my python Test it connects but when i try to browse with inspector it is like its disconnected from the server and it gave me back the error above.
in the excact momemt driver connects to remote localhost, i have this issue.

## Environment

* Appium version (or git revision) that exhibits the issue:  2022.7.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

-I use driver.quit() to terminate the connection
-if i try to print the driver also after the "driver.quit()" i still have the session printed
(ex of output : <appium.webdriver.webdriver.WebDriver (session="0d92f812-a6a1-4b09-944c-0cef82eaeaea")> )

## Link to Appium logs

[Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!](https://gist.github.com/Void-SimonToMars/26bc6525dce2f5e0184ec7d2b2dc7f40)

## Code To Reproduce Issue [ Good To Have ]

from appium import webdriver
from selenium.webdriver.common.by import By
import time

desired_capabilities={
        "platformName": "Android", 
        "platformVersion":"12",
        "deviceName:": "LE2115",
         #"app": "/path/to/my.app"
         "automationName":"UiAutomator2"
         }

driver=webdriver.Remote("http://localhost:4723/wd/hub", desired_capabilities)
driver.quit()

**Comment by mykola-mokhnach** [comment]
I can observe some mess in the log - multiple requests to create and delete a session. Please make sure your tests properly handle the sessions creation flow (e.g. create it in test setup and destroy in test teardown). Also that no tests are being executed in parallel on the same device.

**Comment by Void-SimonToMars** [comment]
> I can observe some mess in the log - multiple requests to create and delete a session. Please make sure your tests properly handle the sessions creation flow (e.g. create it in test setup and destroy in test teardown). Also that no tests are being executed in parallel on the same device.

i updated the logs, i started the server, started appium inspector and conntected to server , ran the pyhton test  and tried to navigate trought appium inspector to get the error

**Comment by mykola-mokhnach** [comment]
You must either start the session from inspector or from the automated test. It is not possible to connect to a running session

**Comment by Void-SimonToMars** [comment]
> 

so the problem is because i basically start two session to same server? is there a way to have real time display and code on python with that session?

**Comment by mykola-mokhnach** [comment]
not that I know of. Maybe there are some workarounds. Consider asking about it at Appium forum

**Comment by jlipps** [comment]
the python client might have a way to construct a WebDriver object without starting a session, perhaps you can pass an existing session id as a kwarg.

not sure why you would want to do this though. if you want to run python code, just start the session in python.

**Comment by Void-SimonToMars** [comment]
> the python client might have a way to construct a WebDriver object without starting a session, perhaps you can pass an existing session id as a kwarg.
> 
> not sure why you would want to do this though. if you want to run python code, just start the session in python.

I thought about that but how ? I mean on webdrivrr there is only " .Remote" to connect to a server, I already tried to connect trought localhost/path/to/Appiumsession but it can't reach connection .

I want to do it because I would like to have real time results, I mean , inspect element-> write code on python -> run to see if all it's correct ( element, finding it correctly ecc)

**Comment by jlipps** [comment]
theni would do it the other way around. start the session using an interactive python session with no command timeout. print out the session id. then attach using the inspector (this is a feature of the inspector). now you can write python code as well as use the inspector.

**Comment by Void-SimonToMars** [comment]
> 

Yea I thought about that too but on inspector when I attach session printed from webdriver it says something like not found

**Comment by jlipps** [comment]
if you think the inspector attach to session feature isn't working, you could submit a detailed issue report at the inspector repo
