### ISSUE TITLE
plugins don't have access to cliArgs in updateServer

### ISSUE THREAD

**Issue by jlipps** [appium/appium#17304]
Plugins should reasonably have access to cli args passed in via the plugin cli arg interface.

Currently they have access via the `this.cliArgs` property on a plugin instance.

But plugins can also implement `static async updateServer`, a method which should also reasonably have access to the plugin's CLI args. Obviously, `this.cliArgs` is not a thing here.

Options:
1. make `updateServer` an instance method
2. figure out how to pass the cli args into `updateServer` so they're accessible

**Comment by boneskull** [comment]
I vaguely recall mentioning that the interface for `Plugin` could be different, and `updateServer` was part of that.  I think my proposed solution was 1.

**Comment by jlipps** [comment]
I am now OK with that solution, if I wasn't before

**Comment by jlipps** [comment]
We might also consider whether there's a way to make `cliArgs` available in the plugin constructor, since that is also a place where we might reasonably expect to do things with them.

**Comment by saikrishna321** [comment]
`since that is also a place where we might reasonably expect to do things with them` Yes agree! This is much needed

**Comment by boneskull** [comment]
@jlipps `cliArgs` _is_ passed in the `Plugin` constructor.

But `Plugin` has diverged a bit from `Driver`, and it will diverge more after this.

Given the potential confusion around `static updateServer` in a `Driver` and a hypothetical instance method `updateServer` in a `Plugin`, I'm going to name it something else.

**Comment by boneskull** [comment]
From Slack, I wrote:

so the `updateServer` thing for `Plugin`s.  currently it appears `Plugin`s are instantiated lazily--not until they are needed to handle a command.  I don't think this can be the case any longer.  does that sound right?

this seems like kind of a not-necessarily-wanted consequence of moving `updateServer` to an instance method.  so maybe that's not what we want to do. maybe we just want to supply `cliArgs` to `static updateServer`

the `updateServer` static method would then have a signature like `type UpdateServerCallback = (expressApp: Express, httpServer: AppiumServer, cliArgs: object) => Promise<void>`;

where `object` is something like `Args`
