### ISSUE TITLE
Appium2 cli can't handle long start server commands

### ISSUE THREAD

**Issue by Jiurong-Yang** [appium/appium#17308]
Appium2 doesn't seem to be able to handle long server start commands. For both beta 40 and 41

command in question:

appium -p 11000 -pa /wd/hub --session-override  --local-timezone --relaxed-security --log-timestamp  -bp 11100 --default-capabilities '{"appium:systemPort": 11300, "appium:webviewDevtoolsPort": 11600, "appium:udid": "19271JEG502669", "appium:platformName": "ANDROID", "appium:platformVersion": "11", "appium:chomedriverPorts": [[11400, 11499]], "appium:deviceName": "19271JEG502669_Pixel_5a"}' --debug

Log: 
WARN Appium Appium encountered 1 warning while validating drivers found in manifest /local_home/exec/.appium/node_modules/.cache/appium/extensions.yaml
WARN Appium Driver "uiautomator2" has 1 potential problem: 
WARN Appium   - Driver "uiautomator2" (package `appium-uiautomator2-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.41) due to an invalid or missing peer dependency on Appium. A newer version of `appium-uiautomator2-driver` is available; please attempt to upgrade "uiautomator2" to v2.4.6 or newer.

ENAMETOOLONG: name too long, open '{"appium:systemPort": 11300, "appium:webviewDevtoolsPort": 11600, "appium:udid": "19271JEG502669", "appium:platformName": "ANDROID", "appium:platformVersion": "11", "appium:chomedriverPorts": [[11400, 11499]], "appium:deviceName": "19271JEG502669_Pixel_5a"}'

Tested the exact command against 1.20.2 and it doesn't have any issues. 

Edit: For now I can probably use the relaxed-cap plugin to reduce the command length, but this seems like an arbitrary limitation and probably not intended.

**Comment by jlipps** [comment]
The way to do this with Appium 2 is to use a config file. It's a much cleaner solution. Here's an example config file: https://github.com/appium/appium/blob/master/packages/appium/sample-code/appium.config.sample.json

**Comment by Jiurong-Yang** [comment]
Ok I see, and I see now the nodeconfig file is also part of that config instead of a separate config file. But I'm assuming this limitation is not intentional?

**Comment by jlipps** [comment]
actually i think this might be a bug @boneskull . maybe we first check to see if the value is a file that exists, which triggers this ENAMETOOLONG error, and then never get to the part where we parse it as JSON instead?

**Comment by Jiurong-Yang** [comment]
> `nodeconfig` must be an object in the config file; this was intentional, but it may be undesirable. as far as I recall, you can still pass a filepath on the command-line.

This bug isn't related to the nodeconfig. The part of the command that's causing problem is the default capabilities

**Comment by boneskull** [comment]
See #17352 for `ENAMETOOLONG` fix
