### ISSUE TITLE
applesimutils binary has not been found in your PATH

### ISSUE THREAD

**Issue by olezvinskyi** [appium/appium#17310]
## The problem

When I ran Appium tests with capabilities
options.setPermissions(new Permissions("{\""+config().bundleIdIos()+"\": {\"userTracking\": \"NO\", \"location\": \"always\", \"notifications\": \"NO\"}}"));

I got next exception 
applesimutils binary has not been found in your PATH. Please install it ('brew tap wix/brew && brew install wix/brew/applesimutils') to be able to change application permissions

## Environment

* Appium version (or git revision) that exhibits the issue: 1.23.0-beta.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Monterey 12.4 **(M1)**
* Node.js version (unless using Appium.app|exe): 16.15.1
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS 15.5
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

My PATH 
PATH=/Users/tsaakyan/bin:/usr/local/bin:/Users/tsaakyan/Library/Android/sdk/emulator:/Users/tsaakyan/Library/Android/sdk/build-tools/33.0.0/bin:/Users/tsaakyan/Library/Android/sdk/build-tools/33.0.0:/Users/tsaakyan/Library/Android/sdk/tools/bin:/Users/tsaakyan/Library/Android/sdk/tools:/Users/tsaakyan/Library/Android/sdk/platform-tools/bin:/Users/tsaakyan/Library/Android/sdk/platform-tools:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tsaakyan/Library/Android/sdk/tools:/Users/tsaakyan/Library/Android/sdk/platform-tools:/Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home:/usr/local/Cellar/maven/3.6.3_1/libexec
LC_TERMINAL=iTerm2

## Link to Appium logs

[GIST](https://gist.github.com/olezvinskyi/a8323f56df30f1bcf86e9b8a8a025570)

**Comment by olezvinskyi** [comment]
echo $SHELL return /bin/zsh
and this is my  zsh profile
```
export ANDROID_HOME=/Users/tsaakyan/Library/Android/sdk
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home
export PATH=$PATH:$JAVA_HOME
export M2_HOME=/usr/local/Cellar/maven/3.6.3_1/libexec
export PATH=${HOME}/homebrew/bin:${PATH}

export PATH=$PATH:$M2_HOME

export ANDROID_SDK_ROOT=/Users/$USER/Library/Android/sdk
export ANDROID_HOME=/Users/$USER/Library/Android/sdk

export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/platform-tools/bin:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/tools/bin:$PATH
export PATH=$ANDROID_HOME/build-tools/33.0.0:$PATH
export PATH=$ANDROID_HOME/build-tools/33.0.0/bin:$PATH
export PATH=$ANDROID_HOME/emulator:$PATH

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="agnoster"

plugins=(git)

source $ZSH/oh-my-zsh.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

**Comment by mykola-mokhnach** [comment]
Did you check the actual environment for the Appium server process. What is the PATH value there?

**Comment by olezvinskyi** [comment]
PID   TT  STAT      TIME COMMAND
52192   ??  S      0:03.57 /usr/local/bin/node /usr/local/lib/node_modules/appium/build/lib/main.js --port 4723 --address 0.0.0.0 --log /Users/tsaakyan/Documents/appium_new/appium.log --allow-insecure true --log-level debug --relaxed-security __CFBundleIdentifier=com.jetbrains.intellij.ce PATH=/Users/tsaakyan/Library/Android/sdk/emulator:/Users/tsaakyan/Library/Android/sdk/build-tools/33.0.0/bin:/Users/tsaakyan/Library/Android/sdk/build-tools/33.0.0:/Users/tsaakyan/Library/Android/sdk/tools/bin:/Users/tsaakyan/Library/Android/sdk/tools:/Users/tsaakyan/Library/Android/sdk/platform-tools/bin:/Users/tsaakyan/Library/Android/sdk/platform-tools:/Users/tsaakyan/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin SHELL=/bin/bash JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.0.3.1.jdk/Contents/Home USER=tsaakyan COMMAND_MODE=unix2003 TMPDIR=/var/folders/zl/r3dv8ngj6ns1sdz1b2_5tnz00000gn/T/ ANDROID_HOME=/Users/tsaakyan/Library/Android/sdk SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.HYbfcICV1a/Listeners XPC_FLAGS=0x0 __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0 LOGNAME=tsaakyan JAVA_MAIN_CLASS_52186=com.intellij.rt.testng.RemoteTestNGStarter LC_CTYPE=en_US.UTF-8 PWD=/Users/tsaakyan/Documents/appium_new XPC_SERVICE_NAME=0 HOME=/Users/tsaakyan

**Comment by mykola-mokhnach** [comment]
is applesimutils executable actually present in any of the paths above?

**Comment by olezvinskyi** [comment]
Thanks. I fixed my issue, `export PATH=/opt/homebrew/bin:$PATH` was missing in PATH
