### ISSUE TITLE
uiautomator2 driver installation in appium 2(ap2.0.0-beta.42) fails

### ISSUE THREAD

**Issue by mshariqa-github** [appium/appium#17326]
## The problem

Facing issue to install uiautomator2 in "ap2.0.0-beta.42" version of appium

## Environment

* Appium version: ap2.0.0-beta.42
* Desktop OS/version used to run Appium: Arch Linux
* Node.js version (unless using Appium.app|exe): v17.9.0
* Npm or Yarn package manager: 8.5.5

## Details

Issue while installing "uiautomator2" in the new appium2 version(ap2.0.0-beta.42). 
Please check the logs for details. 

This issue could be related to https://github.com/appium/appium/issues/17287

## Terminal logs

```
~> appium --version
ap2.0.0-beta.42
~> appium driver install uiautomator2
✖ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.

STDOUT:


STDERR:
npm ERR! code 1
npm ERR! path /home/auto/.node_modules/lib/node_modules/appium
npm ERR! command failed
npm ERR! command sh -c npm run build
npm ERR! > appium@2.0.0-beta.42 build
npm ERR! > babel lib --root-mode=upward --out-dir=build/lib
npm ERR! Error: Babel was run with rootMode:"upward" but a root could not be found when searching upward from "/home/auto/.node_modules/lib/node_modules/appium".
npm ERR! One of the following config files must be in the directory tree: "babel.config.js, babel.config.cjs, babel.config.mjs, babel.config.json".
npm ERR!     at resolveRootMode (/home/auto/.node_modules/lib/node_modules/@babel/core/lib/config/partial.js:64:29)
npm ERR!     at loadPrivatePartialConfig (/home/auto/.node_modules/lib/node_modules/@babel/core/lib/config/partial.js:92:27)
npm ERR!     at loadPrivatePartialConfig.next (<anonymous>)
npm ERR!     at loadFullConfig (/home/auto/.node_modules/lib/node_modules/@babel/core/lib/config/full.js:57:46)
npm ERR!     at loadFullConfig.next (<anonymous>)
npm ERR!     at Object.<anonymous> (/home/auto/.node_modules/lib/node_modules/@babel/core/lib/transform-file.js:30:45)
npm ERR!     at Generator.next (<anonymous>)
npm ERR!     at step (/home/auto/.node_modules/lib/node_modules/@babel/core/node_modules/gensync/index.js:261:32)
npm ERR!     at evaluateAsync (/home/auto/.node_modules/lib/node_modules/@babel/core/node_modules/gensync/index.js:291:5)
npm ERR!     at Object.errback (/home/auto/.node_modules/lib/node_modules/@babel/core/node_modules/gensync/index.js:113:7) {
npm ERR!   code: 'BABEL_ROOT_NOT_FOUND',
npm ERR!   dirname: '/home/auto/.node_modules/lib/node_modules/appium'
npm ERR! }
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "sh -c npm run build\n> appium@2.0.0-beta.42 build\n> babel lib --root-mode=upward --out-dir=build/lib\nError: Babel was run with rootMode:\"upward\" but a root could not be found when searching upward from \"/home/auto/.node_modules/lib/node_modules/appium\".\nOne of the following config files must be in the directory tree: \"babel.config.js, babel.config.cjs, babel.config.mjs, babel.config.json\".\n    at resolveRootMode (/home/auto/.node_modules/lib/node_modules/@babel/core/lib/config/partial.js:64:29)\n    at loadPrivatePartialConfig (/home/auto/.node_modules/lib/node_modules/@babel/core/lib/config/partial.js:92:27)\n    at loadPrivatePartialConfig.next (<anonymous>)\n    at loadFullConfig (/home/auto/.node_modules/lib/node_modules/@babel/core/lib/config/full.js:57:46)\n    at loadFullConfig.next (<anonymous>)\n    at Object.<anonymous> (/home/auto/.node_modules/lib/node_modules/@babel/core/lib/transform-file.js:30:45)\n    at Generator.next (<anonymous>)\n    at step (/home/auto/.node_modules/lib/node_modules/@babel/core/node_modules/gensync/index.js:261:32)\n    at evaluateAsync (/home/auto/.node_modules/lib/node_modules/@babel/core/node_modules/gensync/index.js:291:5)\n    at Object.errback (/home/auto/.node_modules/lib/node_modules/@babel/core/node_modules/gensync/index.js:113:7) {\n  code: 'BABEL_ROOT_NOT_FOUND',\n  dirname: '/home/auto/.node_modules/lib/node_modules/appium'\n}"
  }
}

```

### Install appium 2
npm install -g appium@next

### Install driver uiautomator2
appium driver install uiautomator2

**Comment by KazuCocoa** [comment]
Did you remove `APPIUM_HOME` (`~/.appium` by default) once? I haven't observed the issue in beta 42 in my local and our CI env like https://github.com/appium/appium/issues/17287 so far.

**Comment by saikrishna321** [comment]
@KazuCocoa @boneskull 

I bumped into this issue today, Installing from npm source 

```
 appium driver install --source=npm uiautomator2
WARN Appium Appium encountered 2 warnings while validating plugins found in manifest /Users/saikrisv/.appium/node_modules/.cache/appium/extensions.yaml
WARN Appium Plugin "element-wait" has 1 potential problem:
WARN Appium   - Plugin "element-wait" (package `appium-wait-plugin`) may be incompatible with the current version of Appium (v2.0.0-beta.42) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-wait-plugin` to add a peer dependency on `^appium@2.0.0-beta.42`.
WARN Appium Plugin "appium-reporter-plugin" has 1 potential problem:
WARN Appium   - Plugin "appium-reporter-plugin" (package `appium-reporter-plugin`) may be incompatible with the current version of Appium (v2.0.0-beta.42) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-reporter-plugin` to add a peer dependency on `^appium@2.0.0-beta.42`.
✖ Installing 'uiautomator2'
Error: ✖ Encountered an error when installing package: driver "uiautomator2" invalid; missing a `appium` field of its `package.json`
```

**Comment by jlipps** [comment]
This will not work, if you do `--source=npm` it's going to look for the `uiautomator2` npm package, which is not our driver. You'd need to do `appium-uiautomator2-driver`, since that is the module name on npm. you can only use the shortcut name if you don't include a `--source` flag.

**Comment by saikrishna321** [comment]
Oh yeah! My bad. Thanks

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by teovuk** [comment]
I have the same issue:

appium driver install uiautomator2
✖ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.

STDOUT:


STDERR:
npm ERR! code 1
npm ERR! path /Users/a.vukovic/.appium/node_modules/appium
npm ERR! command failed
npm ERR! command sh -c node ./scripts/autoinstall-extensions.js
npm ERR! /Users/a.vukovic/.appium/node_modules/appium/scripts/autoinstall-extensions.js:35
npm ERR!   process.stderr.columns ?? process.stdout.columns ?? 25
npm ERR!                           ^
npm ERR! 
npm ERR! SyntaxError: Unexpected token ?
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:723:23)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR!     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
npm ERR!     at startup (internal/bootstrap/node.js:283:19)
npm ERR!     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "sh -c node ./scripts/autoinstall-extensions.js\n/Users/a.vukovic/.appium/node_modules/appium/scripts/autoinstall-extensions.js:35\n  process.stderr.columns ?? process.stdout.columns ?? 25\n                          ^\n\nSyntaxError: Unexpected token ?\n    at Module._compile (internal/modules/cjs/loader.js:723:23)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)"
  }
}
****ENV

appium 2.0.0-beta.42
node v17.4.0

**Comment by teovuk** [comment]
> /usr/bin/env node -v

/usr/bin/env node -v
v18.10.0

**Comment by KazuCocoa** [comment]
Which npm version did you have?

**Comment by teovuk** [comment]
8.19.2

**Comment by KazuCocoa** [comment]
I tried the same installation with npm and node version via `2.0.0-beta.44`. What about removing `~/.appium` once?

```
$ appium driver install uiautomator2
info Appium Setting NODE_PATH to '/Users/kazu/.nodebrew/node/v18.10.0/lib/node_modules'
✔ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
ℹ Driver uiautomator2@2.7.1 successfully installed
- automationName: UiAutomator2
- platformNames: ["Android"]
```

**Comment by bwomsm1** [comment]
@KazuCocoa @jlipps I am also facing a similar issue with `appium update` command, when trying to run both:
`appium plugin update uiautomator2`
or
`appium plugin update appium-uiautomator2-driver`

I get an error that neither `appium-uiautomator2-driver` or `uiautomator2` found:

`Error: ✖ The plugin "appium-uiautomator2-driver" was not installed, so can't be updated`
`Error: ✖ The plugin "uiautomator2" was not installed, so can't be updated`

**Comment by jlipps** [comment]
@bwomsm1 `uiautomator2` is a driver, not a plugin. Use `appium driver update` instead.

**Comment by bwomsm1** [comment]
> @bwomsm1 `uiautomator2` is a driver, not a plugin. Use `appium driver update` instead.

ohhh.. right. thanks
