### ISSUE TITLE
ios page with scroll view make find element time much more

### ISSUE THREAD

**Issue by kangqf** [appium/appium#17322]
Hi, master, I have 3 problems for use appium, please help me.

1. Page with animation will slow down the find element action. Even use `waitForIdleTimeout=0`, this is obviously in Android. Is any other action to reduce this.
2. I wan't to confirm one thing first. I find android only has two types of find element response:  exist or not, but ios has 3 types: exist, not exist, and exist but not display. So I guess the android only snapshot the element on current screen, but ios snapshot the element out of current screen. So I want to known if we can use the location field in the response of find element in ios platform, because it can speed up the find action for one element.
3. Base on problem 2, I find when one page has a scroll view for paging, the ios will auto scroll the page when snapshot the page source. This will lead to 3 problems, 1. cost much more time (in our case 0.5s->7s and ) to find the element. 2. this will leave a white screen on the page. 3. some action like click will loss as the snapshot time is much more. This problems make much trouble for us. If we have options to resolve it? such as we only want get the element on current screen but not the current page.

![image](https://user-images.githubusercontent.com/5372027/183012412-ed6f3fc2-09e2-4062-9041-85a37595e71e.png)

**Comment by mykola-mokhnach** [comment]
1. Unfortunately there is not much we could do about it. Element interactions are controlled by XCTest framework. It is known that all accessibility-based test frameworks don't perform well if the application under test is not idling.
2. According to what I could observe earlier XCTest may return unexpected coordinates for an element (e.g. for a table cell) even if this element is outside of the current viewport. Not sure if this is a bug or expected behaviour there though.
3. Same as previous - XCTest does implement autoscroll for standard element actions like `click` and it is not possible to change that behaviour. The best way to workaround that would be to disable animations in the app under test while running automated tests.

**Comment by kangqf** [comment]
Thanks for your reply.
For question 3, we not perform scroll function, but we just try to find an element. Normally, the framework just capture the current viewport and get the page source xml, then find the element in the page source. What is unbelievable, we find even just do a find action,  the framework will scroll the current page on the sly, which will request the paging api to get many pages that more than current demand. If we move the current viewport to the paging section we find white screen occurs. So we guess the framework will auto scroll the page(not visible for user just on the background) to load much more data, is it correct?
If any options that forbidden background autoscroll action which leads to load more pages and make the page source much large? We just want the behavior like android - get current screen page element. And we don't care about the element which exists but not displayed .

**Comment by mykola-mokhnach** [comment]
How do you perform the element lookup? Please provide the appropriate server log and the client code snippet

**Comment by kangqf** [comment]
``` python
from appium import webdriver
import time


if __name__ == '__main__':
    address = f"http://127.0.0.1:4723/wd/hub"
    caps = {
        "platformName": "iOS",
        "appium:automationName": "xcuitest",
        "appium:autoAcceptAlerts": True,
        "appium:bundleId": "com.beeasy.shopee.id.enterprise",
        "appium:locationServicesAuthorized": True,
        "appium:locationServicesEnabled": True,
        "appium:noReset": True,
        # "appium:forceAppLaunch": True,
        "appium:autoUpdateImageElementPosition": True,
        "appium:getMatchedImageResult": True,
        "appium:waitForIdleTimeout": 5,
        "appium:skipLogCapture": True,
        "appium:boundElementsByIndex": True,
        "appium:enablePerformanceLogging": True,

        "appium:platformVersion": "14.4",
        "appium:deviceName": "iPhone 12 Pro Max",
    }
    driver = webdriver.Remote(address, caps)
    driver.implicitly_wait(5)
    i = 0
    while i < 1000:
        start = time.time()
        brand_card = driver.find_element('accessibility id', 'button/Brand')
        # brand_card = driver.find_element_by_xpath('//XCUIElementTypeButton[@name="Return"]')
        end = time.time()
        print("cost: ", end - start)


        if brand_card and brand_card.is_displayed():
            print("display", brand_card.location['x'], brand_card.location['y'])
        elif brand_card:
            print("exist", brand_card.location['x'], brand_card.location['y'])
        else:
            print("not exist")
```
this is the client code
[appium.log](https://github.com/appium/appium/files/9280397/appium.log)

and this is the server log

**Comment by mykola-mokhnach** [comment]
on which line does the unexpected scroll happen?

**Comment by kangqf** [comment]
after `driver = webdriver.Remote(address, caps)` this step called, the paging request sent.

**Comment by mykola-mokhnach** [comment]
Hm, too much is happening in the driver creation call. It could only probably be investigated in combination with the app under test.

You could also try to run a vanilla XCTest script and check if it cases the same behaviour to confirm it is a WebDriverAgent specific behaviour.

**Comment by KazuCocoa** [comment]
I remember when an iOS app's implementation was table view, iOS's accessibility function (to get the snapshot) loaded elements outside the view as well. So http requests, should have occurred after scrolling down a couple of times, happened at that time. This behavior did not occur in manual scrolling.

I don't know recent behavior details in iOS well, but like this behavior could happen in iOS. If this was the same thing, this behavior is potentially kind of iOS internal stuff rather than Appium.

**Comment by kangqf** [comment]
Yeah, I think it's a behavior in ios or wda(because android work very well for the same code). So if any options to forbidden this behavior? If not, how can I resolve this problem, because this will make the cost time much more to find an element and leads to lost click event.

**Comment by kangqf** [comment]
> Hm, too much is happening in the driver creation call. It could only probably be investigated in combination with the app under test.
> 
> You could also try to run a vanilla XCTest script and check if it cases the same behaviour to confirm it is a WebDriverAgent specific behaviour.

If any XCTest script example to check this case? I will try to check it.

**Comment by kangqf** [comment]
> I remember when an iOS app's implementation was table view, iOS's accessibility function (to get the snapshot) loaded elements outside the view as well. So http requests, should have occurred after scrolling down a couple of times, happened at that time. This behavior did not occur in manual scrolling.
> 
> I don't know recent behavior details in iOS well, but like this behavior could happen in iOS. If this issue was the same thing, this behavior is potentially kind of iOS internal stuff rather than Appium.

If the behavior can be refer in here: [https://developer.apple.com/forums/thread/683775](https://developer.apple.com/forums/thread/683775)

**Comment by mykola-mokhnach** [comment]
@Dan-Maor Do you have anything to comment on this issue?

**Comment by Dan-Maor** [comment]
@KazuCocoa is correct regarding table views - I built a quick `UITableView` sample and called `findElement` on the page - this triggered a call for `tableView:cellForRowAtIndexPath:` to load the entire table. Moreover - a call of `debugDescription` on the tested application from a vanilla XCUITest sample (which requests a snapshot of the page) triggers the same behavior.

This really sounds like a behavior out of WDA's control.

@kangqf Out of curiosity - what kind of scroll view are you using? `UITableView` / `UICollectionView` / `UIScrollView` with custom elements / other? And do you trigger an action that may initiate a movement or load a page resource as part of the cell/object instantiation?

**Comment by kangqf** [comment]
we use TableView with custom elements. And this view has a paging function, when we swipe to the pagesize(15) bottom, the next page will auto load. we found when we enter the homepage the first page load(tableview not displayed). Then we not force reload the app, and start the same test code again. After `driver = webdriver.Remote(address, caps)` called, the next page (page 2) load, even if the tableview still not displayed. If we call `swipe` to slide down, even we swipe a small distance the more pages will load(page 3,4,5).

**Comment by kangqf** [comment]
@Dan-Maor have you refer to this doc: [https://developer.apple.com/forums/thread/683775](https://developer.apple.com/forums/thread/683775) ? The apple dev said they optimize this problem in ios 15 beta, but I still get the same result

**Comment by Dan-Maor** [comment]
@kangqf I'm not sure that the link is related, I believe that the issue in that thread is related to arbitrary cells being loaded unnecessarily, whether in our case _all_ of the cells are loaded during an accessibility snapshot request by the XCTest framework.

In any case given the behavior of Apple's testing framework relating to tables I'm not sure there's anything that can be done from the Appium side of things regarding this matter.

**Comment by mykola-mokhnach** [comment]
@Dan-Maor Thanks for the detailed investigation

Closed as third party issue.
