### ISSUE TITLE
third-party extension working copies should be discoverable

### ISSUE THREAD

**Issue by boneskull** [appium/appium#17340]
## The problem

If `appium` (the package) is a dependency of the project in the current working directory, `appium` (the executable) will automatically look into `node_modules` for installed extensions.  _However_, it should _also_ look at `$CWD/package.json`.

This should prevent the workaround to symlink `my-extension/node_modules/my-extension` to `my-extension`

**Comment by jlipps** [comment]
huh, i assumed this was already the case
