### ISSUE TITLE
Android Automation Id Not found

### ISSUE THREAD

**Issue by joshwl2003** [appium/appium#17358]
## The problem

We are setting automation ids for our android xamarin application on collection views. Appium indicates that they are not being found when our QA opens the application. We have verified that the ids are being set from code behind of our application. Only Ids we can get to show up are the ones that we set in XAML.

## Environment
Running on Windows 10
Testing android 9 application
Device honeywell CT60

## Details

If necessary, describe the problem you have been experiencing in more detail.

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help on this. Try asking about it Xamarin-specific forums. Basically, what is visible to UIA2 driver must also be visible to Android's accessibility and vice versa.
