### ISSUE TITLE
persistence API

### ISSUE THREAD

**Issue by boneskull** [appium/appium#17364]
Today, if extensions wish to persist data across server invocations, they need to do this themselves.

Maybe it'd be a good idea to have a persistence API that can be used by the extensions.

My current use case is persisting a device-assigned token across server invocations.

**Comment by mykola-mokhnach** [comment]
I support this idea. xcuitest driver for example needs to persist some data about WDA compilation and currently it uses `$HOME/.appium/webdriveragent` folder for such purpose. Although it would make sense to have a dedicated BaseDriver API to allocate such folder without hardcoding its name

**Comment by jlipps** [comment]
interesting idea. what should we use? json/yaml flatfile? sqlite db?

**Comment by jlipps** [comment]
we could call it the 'extension cache'

**Comment by SrinivasanTarget** [comment]
Good idea. In our [device farm plugin ](https://github.com/AppiumTestDistribution/appium-device-farm) we use an in-memory database to persist device information, etc using [loki.js](https://github.com/techfort/LokiJS)

**Comment by boneskull** [comment]
sqlite is good, but would require a native module and is probably overkill.

a simple JSON key/value store may work fine.  any such file-based store would not support multiple concurrent writes, so we'd need to work around that (e.g. with a lockfile).  to reduce potential concurrency we could have a per-extension k/v store.

imo, value encryption is a non-goal here.  

however, if someone needs something more powerful, the system should be written in such a way that an extension could bring a custom data store.  this shouldn't require too much "extra" up-front investment, and mainly just affects how the API is exposed.

for example, `BaseDriver` could expose CRUD methods and perhaps an `initStore()` method which returns a handle to the underlying data store.  these would call into protected APIs which could be overridden by the user.  e.g., `BaseDriver` exposes `readData()`, which calls its `_readData()` method that interacts directly with the store interface (a JSON store, by default); any driver which needs a different store (and thusly interface) would override `initStore` and `_readData` (and the other CRUD implementations).

**Comment by jlipps** [comment]
Yeah, I agree with that. A flatfile k/v store (1 file per extension to make lock management more sane) in some reasonable format (JSON/YAML) makes sense.

**Comment by mykola-mokhnach** [comment]
The strongbox API is there
