### ISSUE TITLE
An element command could not be completed because the element is in an invalid state (e.g. attempting to click a disabled element)

### ISSUE THREAD

**Issue by NazarBorak** [appium/appium#17362]
## The problem
There are two problems:
1) I wanted to create a new issue on your https://discuss.appium.io/ forum, but after creating an account, i stuck on the moment where i needed to _"follow the instructions in that email to activate your account"_. The problem is that after five hours of waiting for the activation email i still didn't receive it. In advance apologize for asking questions here.

2) The main problem. I have a test suite, which falls on the moment of clicking the button in my app.

## Environment

* Appium version: **1.22.3**.
* Desktop OS/version: **macOS Monterey**/**12.4**.
* Node.js version: **18.7.0**.
* Npm: **8.15.0**.
* TV platform/version under test: **tvOS**/**15.3**.
* Real device: **YES**.

## Details

My simple test has such steps:
1) From the main menu open my test application.

_After the application is opened, it looks like this:_
<img width="506" alt="image" src="https://user-images.githubusercontent.com/65663866/184367462-ba0d785b-9fe0-41af-b791-0585ab26b2ce.png">

2) Find email field, click it and enter my email.

_It successfully clicks and enters my email_
<img width="506" alt="image" src="https://user-images.githubusercontent.com/65663866/184367878-c53ffa29-644f-4ec5-8ad1-64433ef28144.png">

3) After entering email it should find and click "next" button. But during execution of the `next_button.click()` method, it makes two moves towards the button and stops for one minute. Afterwards, it throws the following error: _**An element command could not be completed because the element is in an invalid state (e.g. attempting to click a disabled element)**_.

_Here is what happens when the `next_button.click()` method begins_.
![31](https://user-images.githubusercontent.com/65663866/184373417-997d93bf-3e50-4e1d-bb8a-02cb9ce68ded.png)
![32](https://user-images.githubusercontent.com/65663866/184373440-6c8d26c1-e047-49b5-9738-6956c8dcad1b.png)
![33](https://user-images.githubusercontent.com/65663866/184373453-b57cc998-54eb-47f5-b99d-096224a14ce4.png)

 After it gets to the "2" button it stops for 1 minute and after it throws an Exception. **Worth to mention that those moves from "a" to "1" and to the "2" button all happening during the execution of `next_button.click()` method.** 

## Link to Appium logs

https://gist.github.com/NazarBorak/f1b2166f3b3c97ffb5cef88482ebe77c

## Code To Reproduce Issue

```
dc = {
    "platformName": "tvOS",
    "deviceName": "Apple TV (4th generation)",
    "platformVersion": "15.3",
    "udid": "<device_udid>",
    "noReset": True,
    "wdaLocalPort": 8143,
    "useNewWDA": False,
    "automationName": "XCUITest"
}

driver = webdriver.Remote(command_executor='http://localhost:4723/wd/hub',
                          desired_capabilities=dc)

driver.activate_app("com.testTVOSapp")  # STEP 1.
time.sleep(1)

email_field_xpath = '//XCUIElementTypeApplication[@name="<app_name>"]/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTextField'  # noqa
email_field = driver.find_element(AppiumBy.XPATH, email_field_xpath)  # STEP 2.
email_field.click()  # STEP 2.
email_field.send_keys("test@test.com")  # STEP 2.

next_button_xpath = '//XCUIElementTypeButton[@name="next"]'
next_button = driver.find_element(AppiumBy.XPATH, next_button_xpath)  # STEP 3.
next_button.click()   # STEP 3.  <---  HERE IT FAILS
```

**Comment by KazuCocoa** [comment]
Maybe wda tried click maximum iteration number in: https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement%2BFBTVFocuse.m#L39 but did not succeed.

In fact tvOS does not provide a feature to interact with the target directly like iOS so Appium's tvOS feature tries to move the focus to the target element by moving the focus. I guess the case did not go to the "next" position with current logic in https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBTVNavigationTracker.m , so the click retry also reached the maximum.

When you move the focus to "Next" with explicit key move https://github.com/appium/appium-xcuitest-driver#mobile-pressbutton before `next_button_xpath = '//XCUIElementTypeButton[@name="next"]'` , can it click the "next"?

**Comment by KazuCocoa** [comment]
Perhaps the FBTVNavigationTracker.m can tune the logic.

**Comment by NazarBorak** [comment]
> 

Can you widely describe what should i do with that?

**Comment by NazarBorak** [comment]
> Perhaps the FBTVNavigationTracker.m can tune the logic.

Can you widely describe what is that and what should i do with that?

**Comment by NazarBorak** [comment]
> When you move the focus to "Next" with explicit key move https://github.com/appium/appium-xcuitest-driver#mobile-pressbutton before `next_button_xpath = '//XCUIElementTypeButton[@name="next"]'` , can it click the "next"?

Thank You for the fast response!

Answering the above question, I had used three presses down before an execution of this part of code - `next_button_xpath = '//XCUIElementTypeButton[@name="next"]'` and it successfully pressed the "next" button.

---

What's interesting, if i'm in the main menu and want to open my application using `.click()` method, i get almost in the same situation as i described above. By the way, i use `.activate_app()` instead of finding and clicking.


So what happens:

1) I find my app like this: 
```
app_xpath = '(//XCUIElementTypeIcon[@name="AppCell"])[1]/XCUIElementTypeOther/XCUIElementTypeOther'
app = driver.find_element(AppiumBy.XPATH, app_xpath)
```

2) Click:
`app.click()`.

And here what happens on TV's screen after `app.click()` method:
![git_gif_1_itself](https://user-images.githubusercontent.com/65663866/184621639-c0d31237-07c9-4b7d-8762-acfc48ed7a82.gif)

It goes to the app icon and stops on it, waits for some time and later raises the following exception -  `selenium.common.exceptions.StaleElementReferenceException`. 

Even using explicit key moves, which you mentioned before, didn't help to open that app. I mean, it went from settings to the left side of the screen, then two times up and used `.click()` method, but nothing happed. It just froze and afterwards raised `selenium.common.exceptions.InvalidElementStateException: Message: An element command could not be completed because the element is in an invalid state (e.g. attempting to click a disabled element)` exception.

**Comment by KazuCocoa** [comment]
> didn't help to open that app

Then... I guess it needs to find another way, or something? At least the app had an issue to start by https://developer.apple.com/documentation/xctest/xcuiremote/1627475-pressbutton (what Appium does)

What about the systemlog?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
