### ISSUE TITLE
Appium Chrome not reachable issue 

### ISSUE THREAD

**Issue by SSabat-SDET** [appium/appium#17379]
## The problem

When we try to run our android mobile suite( in Chrome browser) by using chrome auto download option as well as dedicated chromedriver, we get chrome not reachable issue for some of the test cases.
This issue we are continuously facing from many days.

## Environment

- Appium version: 1.22.3
- Android version: 12.0
- Chrome version: 104.0.5112.69
- Node.js version (unless using Appium.app|exe):v16.14.0
- Npm package manager:8.5.5
- Mobile platform/version under test: 12
- Real device or emulator/simulator: Real Device
- Appium CLI or Appium.app|exe: CLI

## Details

When we try to run our android mobile suite( in Chrome browser) by using chrome auto download option as well as dedicated chromedriver, we get chrome not reachable issue for some of the test cases.
we are getting below error after chrome becomes un responsive.

**org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: chrome not reachable**

## Link to Appium logs
Kindly find the full logs and errors of Appium server for your reference
https://gist.github.com/SSabat-SDET/8b562815f92aca09dd25cebabbc335b7

## Code To Reproduce Issue [ Good To Have ]
Code used to launch browser is as below

//code to launch android web browser

capabilities.setCapability(MobileCapabilityType.UDID, DexRunner.udid);
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,DexRunner. device);
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "uiautomator2");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, DexRunner.platformname);	
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, DexRunner.os_version);
capabilities.setCapability(AndroidMobileCapabilityType.CHROMEDRIVER_EXECUTABLE, "./Drivers/chromedriver");
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, DexRunner.browser);
capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, Constants.NEW_COMMAND_TIMEOUT);
if(DexRunner.browser.equalsIgnoreCase("chrome")) {
	
ChromeOptions option = new ChromeOptions();
 option.addArguments(new ArrayList<String>() {
		 {
        add("--no-sandbox");
	add("--disable-gpu-sandbox");
	add("--disable-dev-shm-usage"); // overcome limited resource problems
		 }
		});
	capabilities.setCapability(ChromeOptions.CAPABILITY, option);

**Comment by mykola-mokhnach** [comment]
This error is thrown by chromedriver itself. We cannot do anything about it as UIA2 driver acts as a simple proxy in such case. consider reporting your issue to Google.

**Comment by mykola-mokhnach** [comment]
Also make sure the session management is setup properly for the suite, e.g. new driver session is created on test startup is is deleted on teardown. I could observe some mess with session creation requests in the log above

**Comment by SSabat-SDET** [comment]
@mykola-mokhnach Thanks for the reply. I will double check whether session management is setup properly from my end.
I have seen many issues related to chrome not reachable but didn't found any solution for that yet.
