### ISSUE TITLE
Code Sign Issue for IntegrationApp.app

### ISSUE THREAD

**Issue by ps1logi** [appium/appium#17372]
## The problem

I m getting  the below error in Xcode whenever it tried to build IntegrationApp.app
```
/Users/psrw2/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou/Build/Products/Debug-iphoneos/IntegrationApp.app: errSecInternalComponent
Command CodeSign failed with a nonzero exit code
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable): 1.20.1
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 16.17.0
* Npm or Yarn package manager: 8.15.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

Whenever I tried to build from Xcode I m getting a code sign error for the integration app. I have updated changes as per https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Still seeing this issue previous I have not encountered this issue

**Comment by mykola-mokhnach** [comment]
not sure why you need IntegrationApp at all. Only WebDriverAgentRunner and WebDriverAgentLib need to be signed to perform testing.

**Comment by ps1logi** [comment]
@mykola-mokhnach thank for the information. please close this
