### ISSUE TITLE
Default capabilities, are automaticaly overridden by desired capabilities

### ISSUE THREAD

**Issue by singhsantosh237** [appium/appium#17380]
## The problem

For Running Parallel test in Appium, I have setup two servers:

appium -p 4700 --default-capabilities '{"wdaLocalPort": 8100, "systemPort": 8200}'
appium -p 4701 --default-capabilities '{"wdaLocalPort": 8101, "systemPort": 8201}'

During the run I was getting error: Failed to create session. All non-standard capabilities should have a vendor prefix. 

What I understand was that if I need to run my code, I have to mention these two capabilities into code:

IOS_CAPS = [
{
    'platformName': 'iOS',
    'platformVersion': '15.5',
    'deviceName': 'iPhone 13',
    'automationName': 'XCUITest',
    'app': IOS_APP,
    'wdaLocalPort': '8100',
    'systemPort': '8200'
}, 
{
    'platformName': 'iOS',
    'platformVersion': '15.5',
    'deviceName': 'iPhone 8',
    'automationName': 'XCUITest',
    'app': IOS_APP,
    'wdaLocalPort': '8101',
    'systemPort': '8201'
}]

Otherwise its not working, any solution to avoid mentioning this 2 capabilities

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.40
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): v18.7.0
* Npm or Yarn package manager: 8.15.0
* Mobile platform/version under test: 15.5
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
Sorry, it is not very clear what the issue is from the description above. Please attach the server log and proper actual and expected result descriptions

**Comment by singhsantosh237** [comment]
When I have setup two servers:

appium -p 4700 --default-capabilities '{"wdaLocalPort": 8100, "systemPort": 8200}'
appium -p 4701 --default-capabilities '{"wdaLocalPort": 8101, "systemPort": 8201}'

and run the code with following capabilities:

IOS_CAPS = [
{
'platformName': 'iOS',
'platformVersion': '15.5',
'deviceName': 'iPhone 13',
'automationName': 'XCUITest',
'app': IOS_APP,
},
{
'platformName': 'iOS',
'platformVersion': '15.5',
'deviceName': 'iPhone 8',
'automationName': 'XCUITest',
'app': IOS_APP,
}]


My Expectation was that it will run the code in two mentioned devices successfully, but I got following error:

**Python Error:** 

santoshsingh@Santoshs-MacBook-Pro parallel % pytest -n 2
=============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
rootdir: /Users/santoshsingh/Automation_Python/asf/parallel
plugins: xdist-2.5.0, forked-1.4.0
gw0 [2] / gw1 [2]
EE                                                                                                                                                                          [100%]
===================================================================================== ERRORS ======================================================================================
_________________________________________________________________________ ERROR at setup of test_echo_box _________________________________________________________________________
[gw0] darwin -- Python 3.10.5 /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10

server = 'http://localhost:4700'
caps = {'app': '/Users/santoshsingh/Automation_Python/asf/parallel/../apps/TheApp.app.zip', 'automationName': 'XCUITest', 'deviceName': 'iPhone 13', 'platformName': 'iOS', ...}
platform = 'ios'

    @pytest.fixture
    def driver(server, caps,  platform):
>       driver = webdriver.Remote(
            command_executor=server,
            desired_capabilities=caps
        )

conftest.py:93: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/appium/webdriver/webdriver.py:230: in __init__
    super().__init__(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:277: in __init__
    self.start_session(capabilities, browser_profile)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/appium/webdriver/webdriver.py:320: in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:435: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x1048716c0>
response = {'status': 400, 'value': '{"value":{"error":"invalid argument","message":"All non-standard capabilities should have a ...ncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:339:19)"}}'}

    def check_response(self, response: Dict[str, Any]) -> None:
        """
        Checks that a JSON response from the WebDriver does not have an error.
    
        :Args:
         - response - The JSON response from the WebDriver server as a dictionary
           object.
    
        :Raises: If the response contains an error message.
        """
        status = response.get('status', None)
        if not status or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen: str = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, str):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if not status:
                        status = value.get("status", ErrorCode.UNKNOWN_ERROR)
                        message = value.get("value") or value.get("message")
                        if not isinstance(message, str):
                            value = message
                            message = message.get('message')
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class: Type[WebDriverException]
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_SHADOW_ROOT:
            exception_class = NoSuchShadowRootException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:
            exception_class = ElementNotInteractableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = InvalidCookieDomainException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = UnableToSetCookieException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        elif status in ErrorCode.JAVASCRIPT_ERROR:
            exception_class = JavascriptException
        elif status in ErrorCode.SESSION_NOT_CREATED:
            exception_class = SessionNotCreatedException
        elif status in ErrorCode.INVALID_ARGUMENT:
            exception_class = InvalidArgumentException
        elif status in ErrorCode.NO_SUCH_COOKIE:
            exception_class = NoSuchCookieException
        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:
            exception_class = ScreenshotException
        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:
            exception_class = ElementClickInterceptedException
        elif status in ErrorCode.INSECURE_CERTIFICATE:
            exception_class = InsecureCertificateException
        elif status in ErrorCode.INVALID_COORDINATES:
            exception_class = InvalidCoordinatesException
        elif status in ErrorCode.INVALID_SESSION_ID:
            exception_class = InvalidSessionIdException
        elif status in ErrorCode.UNKNOWN_METHOD:
            exception_class = UnknownMethodException
        else:
            exception_class = WebDriverException
        if not value:
            value = response['value']
        if isinstance(value, str):
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None  # type: ignore[assignment]
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        st_value = value.get('stackTrace') or value.get('stacktrace')
        if st_value:
            if isinstance(st_value, str):
                stacktrace = st_value.split('\n')
            else:
                stacktrace = []
                try:
                    for frame in st_value:
                        line = self._value_or_default(frame, 'lineNumber', '')
                        file = self._value_or_default(frame, 'fileName', '<anonymous>')
                        if line:
                            file = f"{file}:{line}"
                        meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                        if 'className' in frame:
                            meth = "{}.{}".format(frame['className'], meth)
                        msg = "    at %s (%s)"
                        msg = msg % (meth, file)
                        stacktrace.append(msg)
                except TypeError:
                    pass
        if exception_class == UnexpectedAlertPresentException:
            alert_text = None
            if 'data' in value:
                alert_text = value['data'].get('text')
            elif 'alert' in value:
                alert_text = value['alert'].get('text')
            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.InvalidArgumentException: Message: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: wdaLocalPort,systemPort
E       Stacktrace:
E       InvalidArgumentError: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: wdaLocalPort,systemPort
E           at parseCaps (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:200:11)
E           at processCapabilities (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:277:43)
E           at parseCapsForInnerDriver (/opt/homebrew/lib/node_modules/appium/lib/utils.js:127:21)
E           at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:241:26)
E           at commandExecutor (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:73:9)
E           at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:90:15)
E           at processTicksAndRejections (node:internal/process/task_queues:95:5)
E           at defaultBehavior (/opt/homebrew/lib/node_modules/appium/lib/appium.js:666:16)
E           at AppiumDriver.executeWrappedCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:760:16)
E           at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:682:17)
E           at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:339:19)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:247: InvalidArgumentException
_____________________________________________________________ ERROR at setup of test_saved_message_is_initially_empty _____________________________________________________________
[gw1] darwin -- Python 3.10.5 /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10

server = 'http://localhost:4701'
caps = {'app': '/Users/santoshsingh/Automation_Python/asf/parallel/../apps/TheApp.app.zip', 'automationName': 'XCUITest', 'deviceName': 'iPhone 8', 'platformName': 'iOS', ...}
platform = 'ios'

    @pytest.fixture
    def driver(server, caps,  platform):
>       driver = webdriver.Remote(
            command_executor=server,
            desired_capabilities=caps
        )

conftest.py:93: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/appium/webdriver/webdriver.py:230: in __init__
    super().__init__(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:277: in __init__
    self.start_session(capabilities, browser_profile)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/appium/webdriver/webdriver.py:320: in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:435: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x102662020>
response = {'status': 400, 'value': '{"value":{"error":"invalid argument","message":"All non-standard capabilities should have a ...ncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:339:19)"}}'}

    def check_response(self, response: Dict[str, Any]) -> None:
        """
        Checks that a JSON response from the WebDriver does not have an error.
    
        :Args:
         - response - The JSON response from the WebDriver server as a dictionary
           object.
    
        :Raises: If the response contains an error message.
        """
        status = response.get('status', None)
        if not status or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen: str = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, str):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if not status:
                        status = value.get("status", ErrorCode.UNKNOWN_ERROR)
                        message = value.get("value") or value.get("message")
                        if not isinstance(message, str):
                            value = message
                            message = message.get('message')
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class: Type[WebDriverException]
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_SHADOW_ROOT:
            exception_class = NoSuchShadowRootException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:
            exception_class = ElementNotInteractableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = InvalidCookieDomainException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = UnableToSetCookieException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        elif status in ErrorCode.JAVASCRIPT_ERROR:
            exception_class = JavascriptException
        elif status in ErrorCode.SESSION_NOT_CREATED:
            exception_class = SessionNotCreatedException
        elif status in ErrorCode.INVALID_ARGUMENT:
            exception_class = InvalidArgumentException
        elif status in ErrorCode.NO_SUCH_COOKIE:
            exception_class = NoSuchCookieException
        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:
            exception_class = ScreenshotException
        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:
            exception_class = ElementClickInterceptedException
        elif status in ErrorCode.INSECURE_CERTIFICATE:
            exception_class = InsecureCertificateException
        elif status in ErrorCode.INVALID_COORDINATES:
            exception_class = InvalidCoordinatesException
        elif status in ErrorCode.INVALID_SESSION_ID:
            exception_class = InvalidSessionIdException
        elif status in ErrorCode.UNKNOWN_METHOD:
            exception_class = UnknownMethodException
        else:
            exception_class = WebDriverException
        if not value:
            value = response['value']
        if isinstance(value, str):
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None  # type: ignore[assignment]
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        st_value = value.get('stackTrace') or value.get('stacktrace')
        if st_value:
            if isinstance(st_value, str):
                stacktrace = st_value.split('\n')
            else:
                stacktrace = []
                try:
                    for frame in st_value:
                        line = self._value_or_default(frame, 'lineNumber', '')
                        file = self._value_or_default(frame, 'fileName', '<anonymous>')
                        if line:
                            file = f"{file}:{line}"
                        meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                        if 'className' in frame:
                            meth = "{}.{}".format(frame['className'], meth)
                        msg = "    at %s (%s)"
                        msg = msg % (meth, file)
                        stacktrace.append(msg)
                except TypeError:
                    pass
        if exception_class == UnexpectedAlertPresentException:
            alert_text = None
            if 'data' in value:
                alert_text = value['data'].get('text')
            elif 'alert' in value:
                alert_text = value['alert'].get('text')
            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.InvalidArgumentException: Message: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: wdaLocalPort,systemPort
E       Stacktrace:
E       InvalidArgumentError: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: wdaLocalPort,systemPort
E           at parseCaps (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:200:11)
E           at processCapabilities (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:277:43)
E           at parseCapsForInnerDriver (/opt/homebrew/lib/node_modules/appium/lib/utils.js:127:21)
E           at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:241:26)
E           at commandExecutor (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:73:9)
E           at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:90:15)
E           at processTicksAndRejections (node:internal/process/task_queues:95:5)
E           at defaultBehavior (/opt/homebrew/lib/node_modules/appium/lib/appium.js:666:16)
E           at AppiumDriver.executeWrappedCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:760:16)
E           at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:682:17)
E           at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:339:19)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:247: InvalidArgumentException
================================================================================ warnings summary =================================================================================
test_echo_box.py::test_echo_box
test_echo_box.py::test_saved_message_is_initially_empty
  /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/appium/webdriver/webdriver.py:230: DeprecationWarning: desired_capabilities has been deprecated, please pass in an Options object with options kwarg
    super().__init__(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================= short test summary info =============================================================================
ERROR test_echo_box.py::test_echo_box - selenium.common.exceptions.InvalidArgumentException: Message: All non-standard capabilities should have a vendor prefix. The following c...
ERROR test_echo_box.py::test_saved_message_is_initially_empty - selenium.common.exceptions.InvalidArgumentException: Message: All non-standard capabilities should have a vendor...
========================================================================== 2 warnings, 2 errors in 0.37s ==========================================================================



**Server Log**

**Server 4700**

Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"15.5","appium:deviceName":"iPhone 13","appium:automationName":"XCUITest","appium:app":"/Users/santoshsingh/Automation_Python/asf/parallel/../apps/TheApp.app.zip"}}]
[debug] [AppiumDriver@ab03] Event 'newSessionRequested' logged at 1660824901083 (17:45:01 GMT+0530 (India Standard Time))
[Appium] Could not parse W3C capabilities: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: wdaLocalPort,systemPort
[debug] [AppiumDriver@ab03] Event 'newSessionStarted' logged at 1660824901087 (17:45:01 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@ab03] Encountered internal error running command: InvalidArgumentError: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: wdaLocalPort,systemPort
[debug] [AppiumDriver@ab03]     at parseCaps (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:200:11)
[debug] [AppiumDriver@ab03]     at processCapabilities (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:277:43)
[debug] [AppiumDriver@ab03]     at parseCapsForInnerDriver (/opt/homebrew/lib/node_modules/appium/lib/utils.js:127:21)
[debug] [AppiumDriver@ab03]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:241:26)
[debug] [AppiumDriver@ab03]     at commandExecutor (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:73:9)
[debug] [AppiumDriver@ab03]     at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:90:15)
[debug] [AppiumDriver@ab03]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [AppiumDriver@ab03]     at defaultBehavior (/opt/homebrew/lib/node_modules/appium/lib/appium.js:666:16)
[debug] [AppiumDriver@ab03]     at AppiumDriver.executeWrappedCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:760:16)
[debug] [AppiumDriver@ab03]     at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:682:17)
[debug] [AppiumDriver@ab03]     at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:339:19)
[HTTP] <-- POST /session 400 28 ms - 1553

**Server 4701**

Request idempotency key: 8355bbb7-53da-49ed-b34f-7e24e2fb53ad
[HTTP] --> POST /session
[HTTP] {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"15.5","appium:deviceName":"iPhone 8","appium:automationName":"XCUITest","appium:app":"/Users/santoshsingh/Automation_Python/asf/parallel/../apps/TheApp.app.zip"}}}
[debug] [AppiumDriver@9715] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"15.5","appium:deviceName":"iPhone 8","appium:automationName":"XCUITest","appium:app":"/Users/santoshsingh/Automation_Python/asf/parallel/../apps/TheApp.app.zip"}}]
[debug] [AppiumDriver@9715] Event 'newSessionRequested' logged at 1660824901081 (17:45:01 GMT+0530 (India Standard Time))
[Appium] Could not parse W3C capabilities: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: wdaLocalPort,systemPort
[debug] [AppiumDriver@9715] Event 'newSessionStarted' logged at 1660824901085 (17:45:01 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@9715] Encountered internal error running command: InvalidArgumentError: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: wdaLocalPort,systemPort
[debug] [AppiumDriver@9715]     at parseCaps (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:200:11)
[debug] [AppiumDriver@9715]     at processCapabilities (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/capabilities.js:277:43)
[debug] [AppiumDriver@9715]     at parseCapsForInnerDriver (/opt/homebrew/lib/node_modules/appium/lib/utils.js:127:21)
[debug] [AppiumDriver@9715]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:241:26)
[debug] [AppiumDriver@9715]     at commandExecutor (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:73:9)
[debug] [AppiumDriver@9715]     at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:90:15)
[debug] [AppiumDriver@9715]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [AppiumDriver@9715]     at defaultBehavior (/opt/homebrew/lib/node_modules/appium/lib/appium.js:666:16)
[debug] [AppiumDriver@9715]     at AppiumDriver.executeWrappedCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:760:16)
[debug] [AppiumDriver@9715]     at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:682:17)
[debug] [AppiumDriver@9715]     at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:339:19)
[HTTP] <-- POST /session 400 29 ms - 1553


Now when I add the two capabilities:

 # 'wdaLocalPort': '8101',
 # 'systemPort': '8201'
 
 I got successful results, my question is that is there any way I can get the successful result, without mentioning these 2 capablities.

**Comment by mykola-mokhnach** [comment]
> Encountered internal error running command: InvalidArgumentError: All non-standard capabilities should have a vendor prefix. The following capabilities did not have one: wdaLocalPort,systemPort

These errors are expected. W3C spec requires all non-standard capability names to have a vendor prefix. Add `appium:` prefix to both capability names to make that work

**Comment by singhsantosh237** [comment]
Thanks for help
