### ISSUE TITLE
iPad iOS 15 - presentationControllerShouldDismiss is repeatedly called for non-full screen modals

### ISSUE THREAD

**Issue by xliang-smartsheet** [appium/appium#17382]
## The problem

On iOS 15.x with iPad, if a view controller is presented as a modal with the `modalPresentationStyle` set as anything beside `fullScreen`, the `presentationControllerShouldDismiss` function is called anytime Appium attempts to reference a screen element. This can be easily reproed using the Appium Inspector when the modal is launched.

The bug definitely poses an issue in automation testing, as we have business logic that require `presentationControllerShouldDismiss` to work correctly when the modal is actually being dismissed (like when the user taps in the gray area surrounding the modal).

## Environment

* Appium version (or git revision) that exhibits the issue: 
  * Appium 1.22.3-4 for macOS desktop (though we see Appium CLI also have this issue)
* Last Appium version that did not exhibit the issue (if applicable):
  * N/A
* Desktop OS/version used to run Appium:
  * macOS Monterey 12.5
* Node.js version (unless using Appium.app|exe):
  * N/A
* Npm or Yarn package manager:
  * npm 8.16.0
* Mobile platform/version under test:
  * iPad, iOS 15.4+
* Real device or emulator/simulator:
  * iPad Simulator
* Appium CLI or Appium.app|exe:
  * Appium.app

## Details

The setup is extremely easy.

1. Ensure a view controller can present another view controller as a modal, using `modalPresentationStyle` as `.formSheet` or `.pageSheet`
2. Launch the app using iPad on iOS 15.x (we tested with 15.4+)
3. Start Appium Server 1.22.3-4 desktop, and then Appium Inspector with iPad on iOS 15.x
5. When the app is launched, navigate to the screen with the modal presented
6. Tapping anything outside or inside the modal (basically any interaction) will result in `presentationControllerShouldDismiss` getting called on the modal VC.

## Link to Appium logs

[Gist Link](https://gist.github.com/xliang-smartsheet/7a1044790d40db0a5ca081ee6057b293) to appium logs

## Code To Reproduce Issue [ Good To Have ]

XCode project with barebones code to repro: [AppiumModalTest.zip](https://github.com/appium/appium/files/9377208/AppiumModalTest.zip)

**Comment by mykola-mokhnach** [comment]
Please try the most recent driver version, which is only available with Appium2

I don't think this is something specific to XCUITest driver/WDA. You could try to run a vanilla XCTest script and see if it produces a similar behaviour. 

@Dan-Maor Do you have any ideas on that?

**Comment by xliang-smartsheet** [comment]
Hi @mykola-mokhnach ! Thanks for the quick response.

I followed the instructions here to install appium@next, which is `2.0.0-beta.43` after running ```appium --version```. Even with the 2.0 Beta, and I'm seeing the same modal issue. I'm using Appium Inspector (for macOS desktop).

I can try the XCTest as well in the sample project.

**Comment by xliang-smartsheet** [comment]
Ok after writing a simple XCUITest to interact with the modal on iPad on iOS 15.x, it is indeed showing the same unexpected behavior with `presentationControllerShouldDismiss`. I verified this is not an issue on iOS 14.x. I will be filing an Apple bug.

Thanks again for the quick response!

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
