### ISSUE TITLE
@appium/test-support should not have a peer dep of appium

### ISSUE THREAD

**Issue by boneskull** [appium/appium#17398]
Recently I had moved some test harnesses from `@appium/base-driver` and `@appium/base-plugin` into `@appium/test-support`.  In retrospect, this was probably a bad idea.

Because of this change, `@appium/test-support` requires a peer dep of `appium`--otherwise we wind up with a dependency cycle where `@appium/test-support` depends on `@appium/base-driver` which depends on `@appium/test-support`.

I think the mistake here was the assumption that `@appium/test-support` was intended for extensions (drivers/plugins).  If this was the case, the peer dep of `appium` would be reasonable, because that's expected of extensions.  However, non-extensions get use from `@appium/test-support` (e.g. `appium-adb`), and if a package is not an extension, it should not necessarily need to install `appium`.

To that end I'd like to rip out the driver-and-plugin specific harnesses in `@appium/test-support` and put them back in their original locations.  However, they will be accessible via the public API instead of buried deep within the `test` directory.

Example:

```js
// old
import {driverE2ETestSuite} from 'appium/test'; // or '@appium/test-support'

// new
import {driverE2ETestSuite} from 'appium/driver/test';
```

This will necessitate `driver` and `plugin` dirs at the root of the `appium` package and associated modules in `@appium/base-driver` and `@appium/base-plugin` roots.

Alternatively, we could export from `appium/driver` itself, but that feels kind of strange to me.

**Comment by jlipps** [comment]
yeah, this makes sense IMO

**Comment by boneskull** [comment]
I think it makes even _more_ sense to move them to their own packages.  otherwise we got stuff like `chai` and `sinon` being dependencies of base-driver

**Comment by jlipps** [comment]
to move what to their own packages?

**Comment by boneskull** [comment]
reusable test harnesses/suites/fixtures for drivers and plugins, respectively.  e.g. `@appium/driver-test-support`

**Comment by boneskull** [comment]
I think that also means that `appium/test` can probably go away, as imo the main value it provides is that stuff I'm ripping out
