### ISSUE TITLE
Could not find a driver for automationName 'XCUITest'

### ISSUE THREAD

**Issue by viveksoundar** [appium/appium#17395]
## The problem

Receiving Could not find a driver for automationName 'XCUITest' when launching the session from Appium inspector. 

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.43
* Last Appium version that did not exhibit the issue (if applicable): 1.2
* Desktop OS/version used to run Appium: Mac OS Bigsur 11.6.5
* Node.js version (unless using Appium.app|exe): v18.7.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iPhone 11 version 15.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.
<img width="1440" alt="Screen Shot 2022-08-22 at 5 44 15 PM" src="https://user-images.githubusercontent.com/37587895/185920836-77699f44-d139-409a-a104-37b36b31d8b8.png">

Please git clone https://github.com/appium/appium and from the `examples` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in examples, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Appium2 does not contain any drivers by default. Consider installing the necessary drivers before using them as described in https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli

closed as not an issue
