### ISSUE TITLE
Android API 33 - .getSystemBars throws error

### ISSUE THREAD

**Issue by StephanB75** [appium/appium#17405]
## The problem

I tried to launch my test on android emulator with API 33 and got the following error when retrieving systembars
with driver.getSystemBars();

 An unknown server-side error occurred while processing the command. Original error: Cannot parse the frame size from 'NavigationBar0' window properties

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0beta41
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac Monterey
* Node.js version (unless using Appium.app|exe):  16.6
* Npm or Yarn package manager: 8.11
* Mobile platform/version under test: Android API 33
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by StephanB75** [comment]
https://gist.github.com/StephanB75/b95f6702122c7191f41150952e4f2c7a

**Comment by mykola-mokhnach** [comment]
It looks like like Google has again changed the coordinates output format. We need to update the parser to support the new format

**Comment by mykola-mokhnach** [comment]
The patch has been published to UIA2 driver
