### ISSUE TITLE
Getting NoSuchElement error while hitting execute_driver endpoint through webdriver.io

### ISSUE THREAD

**Issue by vasudha0309** [appium/appium#17403]
## The problem
I'm writing an automation test using webdriver.io and their appium protocol and trying to implement the driverSciript() function which allows you to define a webdriverio script in a string and send it to the Appium server to be executed locally to the server itself, thus reducing latency that might otherwise
In running the script I'm getting **NoSuchElement** error for a simple script which hits the endpoint - POST /session/:session_id/appium/execute_driver.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe): 12.16.1
* Npm or Yarn package manager: Npm 6.13.4
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Details
Getting NoSuchElement error for a simple script being sent using webdriverio and appium function driver.driverScript(script) which hits the endpoint - POST /session/:session_id/appium/execute_driver

[90m2022-08-23T10:01:38.289Z[39m [96mINFO[39m [97mwebdriver[39m: [36mRESULT[39m {error: 'no such element', message: 'An element could not be located on the page using the given search parameters.', stacktrace: 'NoSuchElementError: An element could not be…ons (internal/process/task_queues.js:97:5)'}

![image](https://user-images.githubusercontent.com/48402640/186138850-4637d179-8412-4c86-814d-e1b63ce0aacb.png)

## Code To Reproduce Issue [ Good To Have ]

const script = `console.log("Hello");`;
await driver.driverScript(this,script);

**Comment by jlipps** [comment]
We'll need a full appium log to help diagnose. And please make sure you're using appium 2 with the execute script plugin. It looks like you're on an unsupported appium 1.x version currently.

**Comment by vasudha0309** [comment]
Hi thanks for the quick response! I was indeed using Appium v1.22.3. Once I updated to v2.0.0.-beta.43, I'm getting another issue where alternately for every test run I'm getting ECONNRESET error, Socket Hang up error or Could not proxy command to the remote server error. 
PFA appium logs - 
[appium.log](https://github.com/appium/appium/files/9423551/appium.log)

**Comment by mykola-mokhnach** [comment]
The error is expected. I can observe multiple session creation requests without finishing previous ones. Make sure the session management is configured properly.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
