### ISSUE TITLE
Tests failing at first hurdle - kAXErrorServerNotFound

### ISSUE THREAD

**Issue by tking16** [appium/appium#17404]
## The problem

None of my tests work. Can't find any element or assert anything. Running `self.driver.page_source` returns 
```
*** selenium.common.exceptions.StaleElementReferenceException: Message: The previously found element "Application 'com.mycomp.myapp.development'" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Error getting main window kAXErrorServerNotFound
Stacktrace:
StaleElementReferenceError: The previously found element "Application 'com.mycomp.myapp.development'" is not present in the current view anymore. Make sure the application UI has the expected state. Original error: Error getting main window kAXErrorServerNotFound
```

## Environment

* Appium v2.0.0-beta.43
* Mac OS Montery
* v18.7.0
* 8.15.0
* Mobile platform/version under test:
* xcuitest@4.10.0

## Details

If necessary, describe the problem you have been experiencing in more detail.

**Comment by tking16** [comment]
Just to add. Tests run fine on an iPhone 11 Pro Simulator, but don't on an iPhone12 Pro Max

**Comment by mykola-mokhnach** [comment]
This error is coming directly from XCTest. I don't think there is much we could do from WebDriverAgent side

**Comment by AndreiTsialenchanka** [comment]
Hey @mykola-mokhnach and @tking16,

Is there any link to the reported issue on Apple's websites?
