### ISSUE TITLE
element.location return x / y is not real

### ISSUE THREAD

**Issue by suzhenyu006** [appium/appium#17419]
## The problem

I did some mobile web tests，when i use 

`driver.execute_script("arguments[0].scrollIntoView({behavior: 'smooth', block: 'center', inline: 'nearest'});", elem[0])`

When the element is positioned, there is an asynchronously loaded Iframe above it that occupies some height, and the returned x and y are still old，How can I get the real location in this case？？

**Comment by KazuCocoa** [comment]
Please follow the issue template to understand the situation well

**Comment by jlipps** [comment]
probably best to wait until the async iframe is fully loaded

**Comment by mykola-mokhnach** [comment]
Closed because of no response
