### ISSUE TITLE
Appium Select-> Click activates the next (incorrect) element.  BUG!

### ISSUE THREAD

**Issue by StephanLuis** [appium/appium#17415]
## The problem

There's a problem with find(xpath) click. The wrong element is activated!  Selenium for other devices is fine.

## Environment

* Appium version 2.0.0
* Desktop OS/version used to run Appium: Gitpod
* Node.js version (unless using Appium.app|exe): v16.13.0
* Npm or Yarn package manager: none
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real iPad
* Appium CLI or Appium.app|exe:  SauceLabs 

## Details

The problem has been reduced to the above, click() activates the wrong element!

## Link to Appium logs

 [The Log GIST](https://gist.github.com/StephanLuis/a84d6d48ff76e68c6b2149360c80d4b9) my full  Appium log.

## Code To Reproduce Issue [ Good To Have ]

```
 await driver.get("http://practisemaster.com/demos/chronoHMStest.html");

        let elements = await driver.findElements(By.xpath('//div[@id="bob"]/input[@name="startHours"]'));
        for(let e of elements) {
            console.log('child name: ' + await e.getAttribute("name"));

          var parent =   e.findElement(By.xpath('./..'));

          console.log('parent ID: ' + await parent.getAttribute('id'));
        }
      
        await driver.findElement(By.xpath('//div[@id="bob"]/input[@name="startHours"]')).click();


        console.log('Actual active element: ' + await driver.executeScript('return document.activeElement.parentElement.id'));

```

The result is 'jane'  which is incorrect, it should be 'bob'.  On Selenium for other devices the result is fine.  Jane is the next div after bob .

The js rendered html for the two controls:

```

<p>Bob:</p>
    <div id="bob" data-univhms="" class="timeCase">
      <input type="number" class="sH D2 ts_digit" name="startHours" data-tp="1" min="-1" max="100" value="00">
      <span class="bds">:</span>
      <input type="number" class="sM D2 ts_digit" name="startMinutes" data-tp="2" min="-1" max="60" value="00">
      <span class="bds">:</span>
      <input type="number" class="sS D2 ts_digit" name="startSeconds" data-tp="3" min="-1" max="60" value="00">
      <span class="bds">.</span>
      <input type="number" class="sMS D3 ts_digit" name="startMilliSecs" data-tp="4" min="-10" max="1010" step="10" value="000">
      <div id="svgContainer">
        <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" data-prefix="fal" data-icon="stopwatch" class="svg-inline--fa fa-stopwatch fa-w-14" role="img" viewBox="0 0 448 512">
          <path xmlns="http://www.w3.org/2000/svg" fill="currentColor" d="M393.9 184l22.6-22.6c4.7-4.7 4.7-12.3 0-17l-17-17c-4.7-4.7-12.3-4.7-17 0l-20.7 20.7c-31.1-27.5-70.4-45.9-113.8-50.8V48h28c6.6 0 12-5.4 12-12V12c0-6.6-5.4-12-12-12H172c-6.6 0-12 5.4-12 12v24c0 6.6 5.4 12 12 12h28v49.4C96.4 109.3 16 197.2 16 304c0 114.9 93.1 208 208 208s208-93.1 208-208c0-44.7-14.1-86.1-38.1-120zM224 464c-88.4 0-160-71.6-160-160s71.6-160 160-160 160 71.6 160 160-71.6 160-160 160zm12-112h-24c-6.6 0-12-5.4-12-12V204c0-6.6 5.4-12 12-12h24c6.6 0 12 5.4 12 12v136c0 6.6-5.4 12-12 12z"></path>
        </svg>
      </div>
  </div>
    <p>Jane</p>
    <div id="jane" data-univhms="" class="timeCase">
      <input type="number" class="sH D2 ts_digit" name="startHours" data-tp="1" min="-1" max="100" value="00">
      <span class="bds">:</span>
      <input type="number" class="sM D2 ts_digit" name="startMinutes" data-tp="2" min="-1" max="60" value="00">
      <span class="bds">:</span>
      <input type="number" class="sS D2 ts_digit" name="startSeconds" data-tp="3" min="-1" max="60" value="00">
      <span class="bds">.</span>
      <input type="number" class="sMS D3 ts_digit" name="startMilliSecs" data-tp="4" min="-10" max="1010" step="10" value="000">
      <div id="svgContainer">
        <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" data-prefix="fal" data-icon="stopwatch" class="svg-inline--fa fa-stopwatch fa-w-14" role="img" viewBox="0 0 448 512">
          <path xmlns="http://www.w3.org/2000/svg" fill="currentColor" d="M393.9 184l22.6-22.6c4.7-4.7 4.7-12.3 0-17l-17-17c-4.7-4.7-12.3-4.7-17 0l-20.7 20.7c-31.1-27.5-70.4-45.9-113.8-50.8V48h28c6.6 0 12-5.4 12-12V12c0-6.6-5.4-12-12-12H172c-6.6 0-12 5.4-12 12v24c0 6.6 5.4 12 12 12h28v49.4C96.4 109.3 16 197.2 16 304c0 114.9 93.1 208 208 208s208-93.1 208-208c0-44.7-14.1-86.1-38.1-120zM224 464c-88.4 0-160-71.6-160-160s71.6-160 160-160 160 71.6 160 160-71.6 160-160 160zm12-112h-24c-6.6 0-12-5.4-12-12V204c0-6.6 5.4-12 12-12h24c6.6 0 12 5.4 12 12v136c0 6.6-5.4 12-12 12z"></path>
        </svg>
      </div>
  </div>
```

**Comment by mykola-mokhnach** [comment]
Try to calculate coordinates and perform click in a native context as a possible workaround. Check https://appiumpro.com/editions/36-using-the-nativewebtap-capability for more details

**Comment by StephanLuis** [comment]
Thanks, I can look into that while pursuing the bug fix.  Problem, I imagine, would be preventing the test control from moving coordinates.

**Comment by StephanLuis** [comment]
The js updated html for the two controls:
`<p>Bob:</p>
    <div id="bob" data-univhms="" class="timeCase">
      <input type="number" class="sH D2 ts_digit" name="startHours" data-tp="1" min="-1" max="100" value="00">
      <span class="bds">:</span>
      <input type="number" class="sM D2 ts_digit" name="startMinutes" data-tp="2" min="-1" max="60" value="00">
      <span class="bds">:</span>
      <input type="number" class="sS D2 ts_digit" name="startSeconds" data-tp="3" min="-1" max="60" value="00">
      <span class="bds">.</span>
      <input type="number" class="sMS D3 ts_digit" name="startMilliSecs" data-tp="4" min="-10" max="1010" step="10" value="000">
      <div id="svgContainer">
        <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" data-prefix="fal" data-icon="stopwatch" class="svg-inline--fa fa-stopwatch fa-w-14" role="img" viewBox="0 0 448 512">
          <path xmlns="http://www.w3.org/2000/svg" fill="currentColor" d="M393.9 184l22.6-22.6c4.7-4.7 4.7-12.3 0-17l-17-17c-4.7-4.7-12.3-4.7-17 0l-20.7 20.7c-31.1-27.5-70.4-45.9-113.8-50.8V48h28c6.6 0 12-5.4 12-12V12c0-6.6-5.4-12-12-12H172c-6.6 0-12 5.4-12 12v24c0 6.6 5.4 12 12 12h28v49.4C96.4 109.3 16 197.2 16 304c0 114.9 93.1 208 208 208s208-93.1 208-208c0-44.7-14.1-86.1-38.1-120zM224 464c-88.4 0-160-71.6-160-160s71.6-160 160-160 160 71.6 160 160-71.6 160-160 160zm12-112h-24c-6.6 0-12-5.4-12-12V204c0-6.6 5.4-12 12-12h24c6.6 0 12 5.4 12 12v136c0 6.6-5.4 12-12 12z"></path>
        </svg>
      </div>
  </div>
    <p>Jane</p>
    <div id="jane" data-univhms="" class="timeCase">
      <input type="number" class="sH D2 ts_digit" name="startHours" data-tp="1" min="-1" max="100" value="00">
      <span class="bds">:</span>
      <input type="number" class="sM D2 ts_digit" name="startMinutes" data-tp="2" min="-1" max="60" value="00">
      <span class="bds">:</span>
      <input type="number" class="sS D2 ts_digit" name="startSeconds" data-tp="3" min="-1" max="60" value="00">
      <span class="bds">.</span>
      <input type="number" class="sMS D3 ts_digit" name="startMilliSecs" data-tp="4" min="-10" max="1010" step="10" value="000">
      <div id="svgContainer">
        <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" data-prefix="fal" data-icon="stopwatch" class="svg-inline--fa fa-stopwatch fa-w-14" role="img" viewBox="0 0 448 512">
          <path xmlns="http://www.w3.org/2000/svg" fill="currentColor" d="M393.9 184l22.6-22.6c4.7-4.7 4.7-12.3 0-17l-17-17c-4.7-4.7-12.3-4.7-17 0l-20.7 20.7c-31.1-27.5-70.4-45.9-113.8-50.8V48h28c6.6 0 12-5.4 12-12V12c0-6.6-5.4-12-12-12H172c-6.6 0-12 5.4-12 12v24c0 6.6 5.4 12 12 12h28v49.4C96.4 109.3 16 197.2 16 304c0 114.9 93.1 208 208 208s208-93.1 208-208c0-44.7-14.1-86.1-38.1-120zM224 464c-88.4 0-160-71.6-160-160s71.6-160 160-160 160 71.6 160 160-71.6 160-160 160zm12-112h-24c-6.6 0-12-5.4-12-12V204c0-6.6 5.4-12 12-12h24c6.6 0 12 5.4 12 12v136c0 6.6-5.4 12-12 12z"></path>
        </svg>
      </div>
  </div>`

**Comment by jlipps** [comment]
what if you do something like this instead, just to check the parent element of the found element before performing any action.

```
const bobHours = await driver.findElement(By.xpath('//div[@id="bob"]/input[@name="startHours"]'));
console.log('Parent id: ' + await driver.executeScript('return arguments[0].parentElement.id', [bobHours]));
```

**Comment by StephanLuis** [comment]
bob

**Comment by StephanLuis** [comment]
@jlipps I misunderstood and thought you meant to use your code suggestion to debug appium.

I realise now you probably meant as a substitute to my test.  No, I can't use a 'parent of the found element' technique, my plugin uses 'active element' to  determine user input and set values. 

So I need appium to click on specific elements and be able to accurately determine which elements are active.

**Comment by jlipps** [comment]
No, I meant to put that in your test to help us debug and see what happens, not as a replacement for what you ultimately want us to do

**Comment by StephanLuis** [comment]
@jlipps Your test is fine.

**Comment by StephanLuis** [comment]
@jlipps  I looks like it's a bug in .click() ... will post some 'results' in a few hours to help in debugging.

**Comment by StephanLuis** [comment]
@jlipps I'm still looking at the nuance of this bug, but one basic problem is that .click() does not fire correctly when there are two input buttons on a HTML page.

You can see the fail yourself:
` await driver.get("http://practisemaster.com/demos/appium2InputBug.html");
   
  await driver.findElement(By.xpath('//*[@id="testButton3"]')).click();

  var q1 = await driver.executeScript('return (document.querySelector("#testButton3").value == "Johnny Bravo 3")');

 console.log('Value after input time click is correct: ' + q1);
`
just fails and then works for http://practisemaster.com/demos/appiumInputBug.html which has one button.  Order of the buttons has be checked and found not relevant, just number.

I'm noticing in my tests that the active element after .click()  is the body, not the input.  Which is a factor affecting other appium methods like .key() where in my code after keystrokes the active element is selected and changed.  [my bug about values]https://github.com/appium/appium/issues/16697#issuecomment-1183610729)

For now it would be great to debug click() and potentially keep the element active.

**Comment by jlipps** [comment]
@KazuCocoa do we know which version of selenium the current atoms came from? we could look at the click implementation in that code to see if we notice any bugs, or to see if anything has changed in the implementation such that bringing in the current atoms might help

**Comment by KazuCocoa** [comment]
Maybe 3.141.59? https://github.com/appium/appium-remote-debugger/pull/132 is the last one to update entire atoms

**Comment by StephanLuis** [comment]
@jlipps @KazuCocoa I've done the same sort of trial for 'input number' was surprised that a click on the first element on a page activated the second.  So it may be that when body is active after the button click, appium has 'selected' the body ... after the button.  Thought it might be something to keep in mind?

**Comment by jlipps** [comment]
ok if the error is in click, then it would be somewhere in this code or code that it calls: https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/javascript/atoms/action.js#L282-L288

**Comment by StephanLuis** [comment]
@jlipps had a quick look, and where is element defined and/or instantiated?

**Comment by jlipps** [comment]
What Appium sends to the click atom is an object of the form `{ELEMENT: "<id>"}`. the click atom is compiled in such a way that these objects are dereferenced to find an actual web element reference in some kind of local cache. it's hard to navigate this code because it looks like this: https://github.com/appium/appium-remote-debugger/blob/master/atoms/click.js

**Comment by StephanLuis** [comment]
Nice!  Block-spaghetti.   Oh, I want to confirm that you also see the bug (using the code I provided)?  

Hmm.  What do you suggest?  You mentioned that SauceLabs had a way of sending a Appium bundle for it to use.  I'm wondering if you think that [Browserstack -- Appium Desktop](https://www.browserstack.com/docs/app-automate/appium/integrations/appium-desktop) integration would work for debugging?

**Comment by mkucko** [comment]
Can confirm this issue still exists `Welcome to Appium v1.22.3`

**Comment by StephanLuis** [comment]
> Can confirm this issue still exists `Welcome to Appium v1.22.3`

Thanks.  It's surprising that a lot of people aren't reporting about this bug.

**Comment by jlipps** [comment]
Unfortunately the bug, whatever it is, appears to be in the selenium atoms, but the atoms have changed so much that it is a big project to update them in Appium, and we've all been focused on other issues.

**Comment by jlipps** [comment]
@StephanLuis I've finally incorporated a new version of the Selenium atoms into the XCUITest driver. It's several years newer, so maybe it has a fix for these issues? Please try XCUITest driver 4.34 and let me know how it goes.
