### ISSUE TITLE
Add elevated/root to Android Emulator to allow broadcasting set airplane mode true

### ISSUE THREAD

**Issue by sceiler** [appium/appium#17422]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

I am trying to run the io.appium.java_client.android.AndroidConnectionTest tests and it requires on newer emulator versions (at least with API 28) elevated access to broadcast the intent to set airplane mode to true. See here https://gist.github.com/kiwiandroiddev/38df80fed9ae84f1fb012b68a28a143a

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.43
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacBook 12.1
* Node.js version (unless using Appium.app|exe): v16.15.0
* Npm or Yarn package manager: 8.5.5
* Mobile platform/version under test: Android Emulator API 28
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe:

## Details

https://github.com/appium/appium-adb/blob/ae612ce3ae01b882584df577c5d3bdc19ea549bb/lib/tools/adb-commands.js#L759 and https://github.com/appium/appium-adb/blob/ae612ce3ae01b882584df577c5d3bdc19ea549bb/lib/tools/adb-commands.js#L770 are called in io.appium.java_client.android.AndroidConnectionTest. However elevated permission is required for this to work. Trying https://gist.github.com/kiwiandroiddev/38df80fed9ae84f1fb012b68a28a143a locally on an Android Emnulator API 28 works.

Probably something like here would work https://github.com/appium/appium-adb/blob/ae612ce3ae01b882584df577c5d3bdc19ea549bb/lib/tools/adb-commands.js#L1269 but needs to be verified for older and newer emulator versions as not all Android Emulator versions might require elevated permissions.

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

Run io.appium.java_client.android.AndroidConnectionTest by adding `includeTestsMatching 'io.appium.java_client.android.AndroidConnectionTest' into build.gradle for task uiAutomationTest.
`

:uiAutomationTest --tests "io.appium.java_client.android.AndroidConnectionTest.test2"

**Comment by mykola-mokhnach** [comment]
The patch has been published

**Comment by mykola-mokhnach** [comment]
btw, root mode is not available for emulators using google_apis image
