### ISSUE TITLE
Android app flagging device for mock location app, despite clearing mockLocationApp desired cap

### ISSUE THREAD

**Issue by chrisgraham24** [appium/appium#17423]
## The problem

My native Android application under test is flagging my devices for using a mock location app. To get around this, I am setting mockLocationApp as an empty string via Desired caps. However, the application is still flagging the devices occasionally (it does not happen all of the time). Of note, I am using Browser Stack public cloud devices for my testing, so I am not able to run any adb/shell commands to remove applications from the mockLocation role.

## Environment

* Appium 1.22.0
* Android
* Real device
* BrowserStack integration

    desired_caps = {
        "browserstack.user":       browserstack_user,
        "browserstack.key":        browserstack_key,
        "deviceName":                 device1_name,
        "platformVersion":           device1_os,
        "platformName":             'android',
        "app":                               some_app,
        "automationName":        'UiAutomator2',
        "autoGrantPermissions":     'true',
        "locale":                   'en_US',
        "mockLocationApp":          '',
        "appium:mockLocationApp":   '',
	    "bstack:options":           {
		                            "projectName":          'Android Smoke Tests',
		                            "buildName":            'Build 1',
		                            "sessionName":          current_test,
		                            "disableAnimations":    'true',
                                    "debug":                'true',
                                    "appiumVersion":        '1.22.0'
	                                }

**Comment by mykola-mokhnach** [comment]
Please use the most recent UIA2 driver version, which contains recent fixes (only available as part of Appium2)

**Comment by mykola-mokhnach** [comment]
Unfortunately we do not provide patches for older releases. Perhaps, you could ask the cloud provider to patch it locally as a possible workaround

**Comment by chrisgraham24** [comment]
I am OK with upgrading with Appium 2.0.0 so long as it is stable, however I just want to know if you know that upgrading will solve this problem specifically?

**Comment by mykola-mokhnach** [comment]
I cannot guarantee that, although if it still does not work then the resulting logs might help us to find the actual reason for a possible issue.

**Comment by chrisgraham24** [comment]
@mykola-mokhnach I tried using Appium 2.0.0 and still ran into the issue with mockLocation app being set, despite setting an empty string for that desired cap. I did notice however, that BrowserStack is currently using UIA2 version 2.2.0, and not the latest version of 2.4.7...I tried overwriting this value, but it led to an error. Do you think the logs could be helpful to debug this? thank you!

**Comment by mykola-mokhnach** [comment]
yes, logs are always helpful

**Comment by chrisgraham24** [comment]
@mykola-mokhnach Here you go -- https://gist.github.com/chrisgraham24/28684d5399ee6a7168710b5d42b9bf5b. Thank you! and let me know if there is any other information you need.

**Comment by mykola-mokhnach** [comment]
It looks like mock permissions are never revoked from an app once given. You could try to apply https://github.com/appium/appium-android-driver/pull/756 locally to see if it resolves your issue

**Comment by chrisgraham24** [comment]
Yes, I have noticed that. It seems like that cap is just ignored. However, at the request of BrowserStack, I tried setting the mockLocation cap to 'null' (instead of an empty string), and I am still able to repro the issue (happened 20% of the time), and this was in the logs:

`2022-08-29 13:41:08:629 - [debug] [ADB] Running '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s R5CT11WJXSN shell appops set null android:mock_location allow'
2022-08-29 13:41:08:692 - [AndroidDriver] Unable to set mock location for app 'null': Error executing adbExec. Original error: 'Command '/usr/local/.browserstack/android-sdk/platform-tools/adb -P 5037 -s R5CT11WJXSN shell appops set null android\:mock_location allow' exited with code 255'; Command output: Error: No UID for null in user 0`

**Comment by chrisgraham24** [comment]
As for testing locally, I have no local instance of Appium set up (I use BrowserStack), I will need to do that. I might need additional support on how to load this version containing the changes you've made, as well.

**Comment by mykola-mokhnach** [comment]
You need to install Appium server locally and have all the UIA2 driver [Requirements](https://github.com/appium/appium-uiautomator2-driver#requirements) deployed on the host. The simply checkout from the branch above and link it to your server installation using --source=local option as described in https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli

**Comment by chrisgraham24** [comment]
OK, thanks. I will give that a shot ASAP. Suppose this fixed this issue, would this make it's way into the next 2.0.0 Beta release? If so, what is the typical timeframe for this? I want to coordinate this with BrowserStack. ty

**Comment by mykola-mokhnach** [comment]
As for Appium2 driver release schedule is disconnected from the server ones. I'll let you know once the change is published to UIA2 driver

**Comment by chrisgraham24** [comment]
@mykola-mokhnach I am getting an error when installing the branch I pulled down locally.
I run:
`appium driver install --source=local /Users/chris.graham/Desktop/appium-android-driver`
and here is the gist: https://gist.github.com/chrisgraham24/3dd86a3d8f78979a702ccb307f712b28

**Comment by chrisgraham24** [comment]
I also just saw this got merged anyways -- 🎉 This PR is included in version 5.2.11 🎉
So if I get BrowserStack to use this version, how should I specify desired capabilities to take advantage of this fix?

**Comment by mykola-mokhnach** [comment]
this module is not included to the drivers list, but is rather used by other drivers. It will be available for you as soon UIA2 driver version is bumped next time.

**Comment by chrisgraham24** [comment]
Do you have any idea when that will be? And please see my follow up question about desired caps. Thank you!

**Comment by chrisgraham24** [comment]
I am just wondering so I can plan work around this @mykola-mokhnach and ultimately request that BrowserStack support this version. thanks!

**Comment by mykola-mokhnach** [comment]
I am currently in the middle of doing other fixes. Perhaps this will take some days

**Comment by chrisgraham24** [comment]
Understood, thanks for the info. Will follow up in a few days. thanks

**Comment by mykola-mokhnach** [comment]
the patch is available in uia2 driver since v2.4.9

**Comment by mykola-mokhnach** [comment]
> Excellent I will do the testing. @mykola-mokhnach, do I just need to use the standard desired cap?
> "appium:mockLocationApp": ''

yes, just set it to an empty string

**Comment by chrisgraham24** [comment]
@mykola-mokhnach I did my testing and using "appium:mockLocationApp": '' it works perfectly in uiautomator2@2.4.9!! Thank you again!
