### ISSUE TITLE
Add Appium to CDF landscape 

### ISSUE THREAD

**Issue by MarckK** [appium/appium#17432]
The CDF would like to include Appium on the [CD landscape](https://landscape.cd.foundation/). 

This was raised as an issue/request: https://github.com/cdfoundation/cdf-landscape/issues/83

In short, we would be happy to add Appium to the Test Automation category.

To do so we need 4 pieces of information:
* homepage url : https://appium.io/
* GitHub repo url for OS project: https://github.com/appium/appium

Missing info:
* Crunchbase url:
* SVG logo (vertically stacked logo looks better)

If you are interested, please respond with the crunchbase url and an SVG of the Appium logo. Or PR the logo SVG to the hosted_logos directory on [CDF landscape repo](https://github.com/cdfoundation/cdf-landscape).

Thank you!

**Comment by boneskull** [comment]
@MarckK Appium is a OpenJS Foundation project; do you want their Crunchbase URL?

**Comment by boneskull** [comment]
@jlipps I don't see any SVGs around...

**Comment by MarckK** [comment]
Hi @boneskull, Yes for Crunchbase URL. 
Thank you!

**Comment by jlipps** [comment]
![Appium logo vert color](https://user-images.githubusercontent.com/605053/198377328-61c300a4-572b-450e-9626-68ade10040a1.svg)
here's an SVG of a stacked logo

**Comment by boneskull** [comment]
https://www.crunchbase.com/organization/open-js-foundation
