### ISSUE TITLE
Failure to start running tests using Appium + Device Farm

### ISSUE THREAD

**Issue by filipegoncalvesBP** [appium/appium#17438]
## Problem

While running tests on device using appium server we faced an issue using an Android Device (Google Pixel 6a) with the latest Android 13.

## Environment

* Appium v1.22.2
* Device Farm Machine (Linux)
* Real Device - Google Pixel 6a
* Node version - 14.19.1
* Running Tests with Android 13

## Details

Based on the appium log output file, it fails to open the test app due to several failed attempts to retrieve the activity and package of "com.google.android.permissioncontroller". If I add this line of code to the Android Driver capabilities:

capabilities.setCapability("autoGrantPermissions", true);

We are able to run the tests without this issue popping up.

## Appium Log

[appiumlog.txt](https://github.com/appium/appium/files/9469018/appiumlog.txt)

**Comment by filipegoncalvesBP** [comment]
But without providing the capability the tests fail to even start running. 
We have handlers in our code to click on the Allow button but they are never reached because the App we are testing does not open.

**Comment by mykola-mokhnach** [comment]
> We have handlers in our code to click on the Allow button but they are never reached because the App we are testing does not open.

The permissions dialog belongs to the operating system, not the app under test. I assume the app does start, but its main activity never gets focused because of that alert. This means you must either start your test without starting the app or wait for that particular system activity to appear and handle it first.

**Comment by filipegoncalvesBP** [comment]
Allright will try it. 
Thank you for your feedback :) 
Best regards, Filipe
