### ISSUE TITLE
Speed up WebDriverAgent [WD Proxy] connect ECONNREFUSED 127.0.0.1:8100

### ISSUE THREAD

**Issue by appiumtest00003** [appium/appium#17434]
## The problem

I’m creating a CI flow in github action that uses appium and iOs simulator. Is there any workaround to make wda server response faster? It takes about 5 ~ 8 mins for wda server to respond and it makes my test case consumes a lot of time.

## Environment

* Appium version (or git revision) that exhibits the issue: appium@v1.22.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS-11
* Node.js version (unless using Appium.app|exe): 16
* Npm or Yarn package manager: Npm 
* Mobile platform/version under test: Mobile
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I use this caps

caps.setCapability(MobileCapabilityType.DEVICE_NAME, “Iphone_12_v15_2”);
caps.setCapability(MobileCapabilityType.PLATFORM_NAME, “iOs”);
caps.setCapability(MobileCapabilityType.PLATFORM_VERSION, “15.2”);
caps.setCapability(“showXcodeLog”, true);
caps.setCapability(MobileCapabilityType.APP, AP);
caps.setCapability(“useNewWDA”, true);
[//caps.setCapability](https://caps.setcapability/)(“usePrebuiltWDA”, true);
caps.setCapability(“automationName”, “XCUITest”);
caps.setCapability(“noReset”, false);
caps.setCapability(“clearSystemFiles”, true);
caps.setCapability(“wdaStartupRetries”, 3);
caps.setCapability(“wdaStartupRetryInterval”, “12000”);

Appium retried multiple times to connect the WDA server at http://127.0.0.1:8100/status

## Link to Appium logs

https://gist.github.com/appiumtest00003/52146a0a54edd4f834a88530ce9ee165

**Comment by StephanB75** [comment]
From my understanding the WDA is build by xcode there and the time depends on CPUs of your mac.
I think you can speed this up by using a pre-build WDA but i have never used that feature.
Also there is a capability "UseNewWDA" which you can set to false. Than the webdriver again is only build ones while your tests running.

**Comment by appiumtest00003** [comment]
Hi @StephanB75, @mykola-mokhnach 
I used MacOS image runner which has the following hardware specification
Hardware specification for macOS virtual machines:

    3-core CPU (x86_64)
    14 GB of RAM
    14 GB of SSD space

With macOS latest (aka mac-11)
So I think CPUs are not a problem here. I also search for capabilities pre-build WDA but it leads to (an)other error(s).

**Comment by mykola-mokhnach** [comment]
3 CPUs is definitely not enough. It takes about 20s to compile WDA on M1 CPU with 8 cores. On Intel arch it's much slower though.

Consider caching the precompiled bundle as mentioned above. I don't think there is a real reason to compile it again for each new test

**Comment by appiumtest00003** [comment]
```
WDA Setup

WebDriverAgent source is automatically downloaded with Appium. The usual folder location in case Appium is installed via npm tool (npm install -g appium) is /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent

cd /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent
./Scripts/bootstrap.sh -d

Also, it might be necessary to create an empty folder for WDA resources:

mkdir -p /usr/local/lib/node_modules/appium/node_modules/appium-webdriveragent/Resources/WebDriverAgent.bundle

No further configuration steps are needed if you're going to execute your automated tests on iOS Simulator.
```
Do I need anything else besides these steps?

**Comment by StephanB75** [comment]
@appiumtest00003 
I don't know what you want to archive.
I do normally only install appium and drivers via npm and set the useNewWDA :false
Before i start the testsuite i create a new clean simulator.
When testsuite starts it builds automatically the WDA (which takes time) but after that the test is running for 8 hours without rebuilding the WDA.

**Comment by appiumtest00003** [comment]
Hi @StephanB75 
I want to speed up even at the 1st build. I don't know if it can but I will try rebuild WDA

**Comment by StephanB75** [comment]
> Hi @StephanB75 I want to speed up even at the 1st build. I don't know if it can but I will try rebuild WDA

Ok, there i have no experience.

**Comment by appiumtest00003** [comment]
Btw, Thanks a lot @StephanB75 @mykola-mokhnach
I will close this issue

**Comment by mykola-mokhnach** [comment]
If you want to prebuild WDA then make sure you provide the -derivedDataPath to the xcodebuild command line. The command line you could simply copy the one that xcuitest driver generates from logs and replace tasks with `build` one. Then pass the same value to `derivedDataPath` capability of your tests along with `usePrebuiltWDA` set to true.

Another option would be to build .xctestrun file and pass it to `useXctestrunFile` capability. Check capability descriptions at https://github.com/appium/appium-xcuitest-driver for more details.

**Comment by appiumtest00003** [comment]
Hi @mykola-mokhnach 
Sorry for adding a comment to this ticket 
I found a change log for prebuilt WDA
`
Add prebuilt WebDriverAgentRunner snapshots to speed up tests execution on iOS Simulator in appium-webdriveragend npm package [WebDriverAgent#331](https://github.com/appium/WebDriverAgent/pull/331)
The path is appium/node_modules/appium-webdriveragend/WebDriverAgentRunner-Runner.app.zip
The usage is:
idb install /WebDriverAgentRunner-Runner.app --udid <device-udid>
idb launch com.facebook.WebDriverAgentRunner.xctrunner
`
Should I use it to accelerate or build WDA like https://appium.io/docs/en/advanced-concepts/wda-custom-server/

**Comment by mykola-mokhnach** [comment]
yes, you could try that. I was observing idb being quite poorly maintained recently, so there might be compatibility issues with recent iOS versions.

**Comment by appiumtest00003** [comment]
I tried to build WDA with 
```
/Applications/Xcode_13.2.1.app/Contents/Developer/usr/bin/xcodebuild -project /Users/runner/hostedtoolcache/node/16.17.0/x64/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=5A215A1E-612A-494A-A834-4825F426F306 test
```
and got this 
```
2022-09-05 05:58:19.302098+0000 WebDriverAgentRunner-Runner[16318:646417] Built at Sep  5 2022 05:54:55
2022-09-05 05:58:19.398574+0000 WebDriverAgentRunner-Runner[16318:646417] ServerURLHere->http://10.79.12.137:8100/<-ServerURLHere
2022-09-05 05:58:19.485894+0000 WebDriverAgentRunner-Runner[16318:646468] Using singleton test manager
```
Is there any way to config the URL to 127.0.0.1 like in appium or a fixed endpoint maybe? Because this is in Github Actions, I don't know the IP each time WDA is compiled.

**Comment by mykola-mokhnach** [comment]
you should provide derived data path as a command line argument

the IP address there is the address of the device itself. It cannot be changed. You don't need to use the `test` task to prebuild sources, but rather `build`

**Comment by appiumtest00003** [comment]
Thanks
I will try and respond later
