### ISSUE TITLE
Incorrect links in read me document related to examples

### ISSUE THREAD

**Issue by ravibabu101143** [appium/appium#17436]
In read me document, links are provided for get started and sample code examples.. But those links are not directing to correct pages

Get Started
Check out our [Getting Started](https://github.com/appium/appium/blob/master/docs/en/about-appium/getting-started.md) guide to get going with Appium.

There is also a sample code that contains [many examples of tests in a variety of different languages](https://github.com/appium/appium/tree/master/sample-code)!

**Comment by eglitise** [comment]
Closing as fixed
