### ISSUE TITLE
8 high severity vulnerabilities seen on installing appium 2.0 on Windows

### ISSUE THREAD

**Issue by AT1990** [appium/appium#17433]
## 8 high severity vulnerabilities seesn on installing appium 2.0 on Windows machine

trying to install appium globally via command "npm install -g appium@next" but getting below outcome

C:\Users\ASUS>npm install -g appium@next

added 523 packages, and audited 524 packages in 51s

76 packages are looking for funding
  run `npm fund` for details

8 high severity vulnerabilities

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

npm audit is giving 0 vulnerabiliyites as output
C:\Users\ASUS>npm audit
found 0 vulnerabilities

**Comment by mykola-mokhnach** [comment]
Duplicate of https://github.com/appium/appium/issues/17170
