### ISSUE TITLE
Typo in documentation: Ruby Example

### ISSUE THREAD

**Issue by drvesk** [appium/appium#17440]
## The problem

There is an @ in the code that doesn't seem intentional

## Environment

In the ruby example:
http://appium.io/docs/en/commands/interactions/actions/

## Details

The @ in line "f2.create_pointer_move(duration: 1, x: 200, y: 800, origin: ::Selenium::Web@Driver::Interactions::PointerMove::VIEWPORT)"

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium.io/pull/374
