### ISSUE TITLE
Android app can not be brought to foreground on appium2

### ISSUE THREAD

**Issue by bswhb** [appium/appium#17455]
## The problem

Android app can not be brought to foreground on appium2 from background, which works on appium1.

## Environment

* Appium version (or git revision) that exhibits the issue: v2.0.0-beta.43
* Last Appium version that did not exhibit the issue (if applicable): v1.23
* Desktop OS/version used to run Appium: MacOS Monterey 12.5.1 M1
* Node.js version (unless using Appium.app|exe): v18.8.0
* Npm or Yarn package manager:
* Mobile platform/version under test:
* Real device or emulator/simulator: Redmi Note8 (Android 9) and Pixel 2 (Android 11)
* Appium CLI or Appium.app|exe:

## Details

We tried to launch and bring the Android Settings app to foreground, but it failed if the app was already in the background. Another wrong app will be started and brought to foreground.

Instead, if we manually killed the Settings app before execution. It will be brought to foreground, even if there's another app already on the foreground.

By the way, right now it seems the `shouldTerminateApp` does not work on Anroid, just leaving the app as is after the test run. Is there another capability to handle this?

Kindly please advise, thanks a lot in advance!

## Link to Appium logs

https://gist.github.com/bswhb/6c4b5c05d1acaf3f718b577725d58588

**Comment by StephanB75** [comment]
Do you use 
driver.activateApp("com.android.settings");
and 
driver.terminateApp("com.android.settings");

This work for me with appium 2.0

**Comment by mykola-mokhnach** [comment]
> 2022-09-07 17:25:50:165 [AndroidUiautomator2Driver@b1a1]   shouldTerminateApp

Where it is mentioned this capability should work for UIA2 driver? In general noReset being set to true already assumes that the state of the application under test must not be changed.

**Comment by bswhb** [comment]
Hi @mykola-mokhnach , thanks for your investigation. 

I think the issue is the behavior of Appium v2 is quite different from v1. In v1, the Android app will be killed automatically after the session is closed, and `shouldTerminateApp` is not necessary to set. Could you please confirm this difference is by design of Appium v2?

Regarding `noReset`, in my opinion this cap means not to reset the app data / cache, instead of keeping the background / foreground state.

**Comment by mykola-mokhnach** [comment]
> I think the issue is the behavior of Appium v2 is quite different from v1. In v1, the Android app will be killed automatically after the session is closed, and shouldTerminateApp is not necessary to set. Could you please confirm this difference is by design of Appium v2?

Confirmed. Also, small correction to the terminology: `Appium 2` is unrelated here. It is the uiautomator2 driver we are talking about.

> Regarding noReset, in my opinion this cap means not to reset the app data / cache, instead of keeping the background / foreground state.

Not really. noReset means "do not touch it, I want to continue where I left". Terminating the app also changes its state, so this has been patched in later versions.

**Comment by mykola-mokhnach** [comment]
Correct. It is expected the client script overtakes the lifecycle of the application under test, not the driver.
We've also recently duplicated application management primitives to mobile extensions, so they could be conveniently invoked from any client that does not implement special wrappers fro them and got proper documentation: https://github.com/appium/appium-uiautomator2-driver/pull/540

**Comment by bswhb** [comment]
thanks for the info and issue closed
