### ISSUE TITLE
FindElement is executed on wrong device when two Android 12 devices are connected

### ISSUE THREAD

**Issue by jhaerig** [appium/appium#17458]
## The problem

My project automates UI interactions on two real Android devices with the same Android Version (12) via Appium in c#.
The devices have unique Udids and deviceNames.
Whenever the program interacts with one of the devices (`device1`) via `AndroidDriver` and `FindElementByAndroidUIAutomator`, the other device (`device2`) tries to execute the `UiSelector/findElement` activity. This does not always happen, but in 90% of all cases.

When using Android devices with **NONE equal** Android Versions (11 and 12), the problem does not occur at all.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.22.0 / Appium.WebDriver 4.2.1 / Selenium.WebDriver 3.141.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 16.14.0.0
* Npm or Yarn package manager:
* Mobile platform/version under test: Android 11/12
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: 

## Details

In this example, one AppiumService is launched. The AndroidDriver of each device connects to this single AppiumService.
Launching AppiumServices for each AndroidDriver was leading to the same problem.

In most cases `_driver2.FindElementByAndroidUIAutomator` triggers element search on `Device1` instead of `Device2`, or the other way.

``` c#
// AppiumService initialization:
string _appiumServiceUrl = string.Empty;
_appiumLocalService = new AppiumServiceBuilder()
      .UsingAnyFreePort()
      .WithLogFile(new FileInfo(path))
      .Build();
  _appiumLocalService.Start();
_appiumServiceUrl = _appiumLocalService.ServiceUrl.AbsoluteUri;

Dictionary<string, object> AppiumConfiguration_Device1 = new Dictionary<string, object>
{
    { "PlatformName", "Android" },
    { "platformVersion", "12"},
    { "deviceName", "172.16.250.248:5555"},
    { "noReset", false},
    { "dontStopAppOnReset", true},
    { "newCommandTimeout", 300},
    { "launchTimeout", 60000},
    { "Udid", "172.16.250.248:5555"},
};
Dictionary<string, object> AppiumConfiguration_Device2 = new Dictionary<string, object>
{
    { "PlatformName", "Android" },
    { "platformVersion", "12"},
    { "deviceName", "UBV0218725005021"},
    { "noReset", false},
    { "dontStopAppOnReset", true},
    { "newCommandTimeout", 300},
    { "launchTimeout", 60000},
    { "Udid", "UBV0218725005021"}
};

_driver1 = new AndroidDriver<AndroidElement>(new Uri(_appiumServiceUrl), AppiumConfiguration_Device1, TimeSpan.FromSeconds(60))
_driver2 = new AndroidDriver<AndroidElement>(new Uri(_appiumServiceUrl), AppiumConfiguration_Device2, TimeSpan.FromSeconds(60))

var objSelector2 = new AndroidUiScrollable(
                    new AndroidUiSelector()
                    .IsScrollable(true))
                    .SetScrollDirection(ListDirection.Vertical)
                    .ScrollIntoView(
                    new AndroidUiSelector()
                    .ClassNameMatches("android.widget.TextView")
                    .TextContains("Wi-Fi")
                    .ResourceIdMatches("android:id/title"));

var object2 = _driver2.FindElementByAndroidUIAutomator((objSelector2 as AndroidUiSelector)).Click();
```

## Link to Appium logs

The issue occurs around line 1855. There a `UiSelector` should find an element on Device2, but instead starts the `findElement` on Device1.
[https://gist.github.com/jhaerig/427676fe6bf6e51c253247503b4054e5](https://gist.github.com/jhaerig/427676fe6bf6e51c253247503b4054e5)

Very suspicious is line 1801. There, Udid and deviceUDID do not match:
`2022-09-07 12:33:40:177 [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8207/wd/hub/session] with body: `
```json
{
	"value": [
		{
			"id": "252c423a-6fe3-4f68-b7c9-ca76a08384c7",
			"capabilities": {
				"platform": "LINUX",
				"webStorageEnabled": false,
				"takesScreenshot": true,
				"javascriptEnabled": true,
				"databaseEnabled": false,
				"networkConnectionEnabled": true,
				"locationContextEnabled": false,
				"warnings": {},
				"desired": {
					"platformName": "Android",
					"PlatformName": "Android",
					"platformVersion": "12",
					"deviceName": "172.16.250.248:5555",
					"noReset": false,
					"dontStopAppOnReset": true,
					"newCommandTimeout": 300,
					"launchTimeout": 60000,
					"Udid": "172.16.250.248:5555"
				},
				"platformName": "Android",
				"PlatformName": "Android",
				"platformVersion": "12",
				"deviceName": "172.16.250.248:5555",
				"noReset": false,
				"dontStopAppOnReset": true,
				"newCommandTimeout": 300,
				"launchTimeout": 60000,
				"Udid": "172.16.250.248:5555",
				"deviceUDID": "172.16.250.248:5555",
				"deviceApiLevel": 31,
				"deviceScreenSize": "1920x956",
				"deviceScreenDensity": 160,
				"deviceModel": "MMI",
				"deviceManufacturer": "International",
				"pixelRatio": 1,
				"statBarHeight": 119,
				"viewportRect": {
					"left": 0,
					"top": 119,
					"width": 1920,
					"height": 697
				}
			}
		},
		{
			"id": "a42b2904-9cfe-4ea1-bf7b-03df2bfe323c",
			"capabilities": {
				"platform": "LINUX",
				"webStorageEnabled": false,
				"takesScreenshot": true,
				"javascriptEnabled": true,
				"databaseEnabled": false,
				"networkConnectionEnabled": true,
				"locationContextEnabled": false,
				"warnings": {},
				"desired": {
					"platformName": "Android",
					"PlatformName": "Android",
					"platformVersion": "12",
					"deviceName": "UBV0218725005021",
					"noReset": false,
					"dontStopAppOnReset": true,
					"newCommandTimeout": 300,
					"launchTimeout": 60000,
					"Udid": "UBV0218725005021"
				},
				"platformName": "Android",
				"PlatformName": "Android",
				"platformVersion": "12",
				"deviceName": "172.16.250.248:5555",
				"noReset": false,
				"dontStopAppOnReset": true,
				"newCommandTimeout": 300,
				"launchTimeout": 60000,
				**"Udid": "UBV0218725005021"**,
				**"deviceUDID": "172.16.250.248:5555"**,
				"deviceApiLevel": 31,
				"deviceScreenSize": "1920x956",
				"deviceScreenDensity": 160,
				"deviceModel": "MMI",
				"deviceManufacturer": "International",
				"pixelRatio": 1,
				"statBarHeight": 119,
				"viewportRect": {
					"left": 0,
					"top": 119,
					"width": 1920,
					"height": 697
				}
			}
		}
	],
	"sessionId": null,
	"status": 0
}
```

## Code To Reproduce Issue [ Good To Have ]

-

**Comment by mykola-mokhnach** [comment]
there is the obvious typo in capabilities: "Udid -> udid"

**Comment by mykola-mokhnach** [comment]
Do you in general follow the [parallel execution](https://github.com/appium/appium-uiautomator2-driver#parallel-tests) guide?

**Comment by jhaerig** [comment]
Thanks! I'll give it a try with lower case `udid`. 
Wasn't aware that casing is an issue at this capability, too. Only stumbled about casing with `platformVersion`.
Yes, in general I followed the parallel execution guide. I'll run a test for the next hours.

**Comment by jlipps** [comment]
In general, if there is any instance of one session talking to another session's devices, the error usually lies in the client threading logic (client side), or the failure to adequately partition out capabilities per session so there are no clashing ports. But once you've confirmed nothing like this is going on, we can dig in more to see if it's an issue with Appium's logic somehow.

**Comment by jhaerig** [comment]
I now could verify, problem is solved by using lower case capability parameter `udid`. Thanks for your support.
