### ISSUE TITLE
How to get the name of Context Handles

### ISSUE THREAD

**Issue by AnandChaurasia** [appium/appium#17451]
## The problem

My iOS App is Hybrid and at a time I can see more than one WEB_VIEW context handles. To identify web element with class or ID  , I have to switch to correct context handle like:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/21359464/188679833-71867695-8082-4fb3-bd43-5db79346acc6.png">

I have noted that context handle keep on changing but Name is same. is it possible to get name of contextHandles ?
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/21359464/188682699-b640b10e-ea86-4fc6-9d3e-c0964682dbd3.png">

## Environment

 DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
    desiredCapabilities.setCapability("platformName", "ios");
    desiredCapabilities.setCapability("appium:deviceName", "iPhone 12 Pro Max");
    desiredCapabilities.setCapability("appium:automationName", "XCUITest");
    desiredCapabilities.setCapability("appium:app", "/Users/chaurasia/IdeaProjects/ahead-ci-overarching-testautomation-mobile/src/test/resources/app/27689135.319926980_QA.app");
    desiredCapabilities.setCapability("appium:includeSafariInWebviews", true);
    desiredCapabilities.setCapability("appium:autoAcceptAlerts", "true");
    desiredCapabilities.setCapability("appium:platformVersion", "14.5");
    desiredCapabilities.setCapability("appium:autoWebview", false);
    desiredCapabilities.setCapability("appium:newCommandTimeout", 3600);
    desiredCapabilities.setCapability("appium:connectHardwareKeyboard", true);

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `examples` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in examples, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Try https://github.com/appium/appium-xcuitest-driver#mobile-getcontexts

Please use Appium forum to ask questions.
