### ISSUE TITLE
Appium not able to identify elements when Android version upgraded from 10 to 12 for Hybrid App

### ISSUE THREAD

**Issue by PreetamQA** [appium/appium#17453]
## Scenario
We have been using Appium (1.20-1.22) successfully for automating Hybrid Android /iOS mobile app which is built on ionic 6 and Angular 14. 
Automation tools: Appium/Selenium/Java

## The problem
We recently upgraded our emulators from Android 10 to Android 12.

With this changes in Android version, we have seen a change in how Appium parses the HTML and we are not able to find most of the previously used elements through Appium inspector.
Every element is identified as a view class only in Appium.

NOTE: This issue is replicable only on Android 11 and 12. Android 10 perfectly works fine.

Can anyone please help in fixing this issue?

**Comment by mykola-mokhnach** [comment]
- The most recent driver version is only available in Appium 2. We do not maintain older releases
- The provided information is not enough to make any conclusions. Please provide server logs, actual page sources for different Android versions, etc
- If you use UiAutomator2 driver then the actual page source you can observe in the inspector reflects the structure that the app itself provides to the Accessibility. You could verify it using any available accessibility inspector for Android and then compare its output with the page source generated by the UIA2 driver.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
