### ISSUE TITLE
socket hangup

### ISSUE THREAD

**Issue by Mr-Ples** [appium/appium#17467]
## The problem

When I don't leave a 3 second sleep between each command to the appium webdriver then I get socket hang up errors when trying to perform any action with the webdriver

## Environment

* Appium version (or git revision) that exhibits the issue: 1.23.0-beta.0
* Desktop OS/version used to run Appium: 12.2 Beta Monterey
* Node.js version (unless using Appium.app|exe): v17.3.0
* Npm or Yarn package manager: 8.3.0
* Mobile platform/version under test: 13-15
* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe: CLI

## Details

When I add a 3 second sleep between each web driver command (a command being something like find_element or query app state) everything runs fine, when I remove the 3 second sleep then I get spammed with socket hang up errors.

## Link to Appium logs

https://gist.github.com/Mr-Ples/e619ffa93b11878eb461a06f50dfe74b

**Comment by mykola-mokhnach** [comment]
Please use the most recent xcuitest driver version, which is only available in Appium2

**Comment by Mr-Ples** [comment]
- installed appium 2 using npm install appium@next
- updated Appium-Python-Client
- migrated code to appium 2 (minimally, not using the new XCUITEST options still using desired capabilities)

still getting socket hangups: https://gist.github.com/Mr-Ples/c9b1f31e4e8f95aaaccbda65577bab10

```
<PY_USER>21:21:48 UTC [0:04:38] [18|stop_app] Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
    at JWProxy.command (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:342:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at XCUITestDriver.proxyCommand (/Users/gitlabrunner/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:95:12)
    at XCUITestDriver.mobileTerminateApp (/Users/gitlabrunner/.appium/node_modules/appium-xcuitest-driver/lib/commands/app-management.js:66:10)
    at XCUITestDriver.terminateApp (/Users/gitlabrunner/.appium/node_modules/appium-xcuitest-driver/lib/commands/app-management.js:117:10)
```

Its actually worse now, I am getting socket hangups even with a 3 second wait between driver calls

**Comment by mykola-mokhnach** [comment]
What if you try another device or another app? Do you still observe the same issue?

**Comment by Mr-Ples** [comment]
The issue happens on all of the 10 different devices I regularly use. They all have different os versions (ranging from 13.x.x to 15.x.x (they are all iphone 8 though, I don't have other iphones available). I will write a test case that closes the app entirely and taps around on the device, it might take a few days

**Comment by adrianwoda-viacom** [comment]
I have encountered similar issue, after upgrading to xcode 14.0. Trying to rollback

**Comment by adrianwoda-viacom** [comment]
rollback to xcode 13.4.1 solved the problem.

**Comment by Mr-Ples** [comment]
I'm using python 3.6 so I can't install the latest Appium-Python-Client. I guess its just a matter of finding the right combination of versions for xcode / python packages / appium. I'm just going to revert back to appium 1 and accept the 3 second wait between calls. Thanks for help

**Comment by Mr-Ples** [comment]
Turns out appium 1.23.0-beta.0 doesn't exist anymore, I will try appium 2 again and update python etc

**Comment by Mr-Ples** [comment]
updated to appium2, updated python to 3.7, updated Appium-Python-Client to 2.6.2, rebuilt the web driver (didn't perform this step above) and removed sleeps between driver calls (will also look into using more performant lookups: https://github.com/facebookarchive/WebDriverAgent/wiki/How-To-Achieve-The-Best-Lookup-Performance), at first glance it seems like there is no issue anymore. I don't see any socket hangups. Will report here again in a few days to confirm if issue was resolved.

**Comment by Mr-Ples** [comment]
i've been running quite some tests and have not had the socket hang up error since updating to appium2, i think the issue is fixed

**Comment by Mr-Ples** [comment]
i've been running quite some tests and have not had the socket hang up error since updating to appium2, i think the issue is fixed
