### ISSUE TITLE
Original error: 'opencv4nodejs' module is required to use OpenCV features

### ISSUE THREAD

**Issue by hello297** [appium/appium#17483]
## The problem

Unable to use opencv features even though it is installed.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Desktop OS/version used to run Appium: MacOS 12.5.1
* Node.js version (unless using Appium.app|exe): 18.9.0
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: Android 12
* Real device or emulator/simulator: Pixel 4a 5G
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I get the error `Original error: 'opencv4nodejs' module is required to use OpenCV features` even though it is installed.
Running `npm list -g` shows the following:
/usr/local/lib
├── @appium/doctor@1.16.26
├── appium@1.22.3
├── npm@8.19.1
├── opencv-build@0.1.9
└── opencv4nodejs@5.6.0

I have tried uninstalling and re-installing appium, opencv, and npm multiple times but to no avail. 

## Link to Appium logs
(https://gist.github.com/hello297/64a0c7cfb98c46ac102c0559db8750d9)

**Comment by StephanB75** [comment]
better try to use appium 2.0 there it is not necessary tp install and compile opencv

**Comment by hello297** [comment]
@StephanB75 thanks for the response.

I tried installing appium 2.0 briefly but it seemed like it was going to take some considerable refactoring so I stopped.
Also I couldn't find very many guides to get started so that was also a factor.

I'll try your steps, I'm hoping it resolves my issue.

**Comment by StephanB75** [comment]
installing opencv was really a pain for me in appium 1.x
But better you should start migarting to 2.0 because all latest drivers and clients depending on it,
most probably it will not work anymore sooner or later because appium 1.x will get no updates anymore.

**Comment by StephanB75** [comment]
@hello297 
here are 2 guides what look good
https://appiumpro.com/editions/123-migrating-to-appium-20-part-1-capability-prefixes
https://journeyofquality.com/2021/10/08/migrate-appium-server-1-x-to-2-x/

**Comment by hello297** [comment]
@StephanB75 
Unfortunately it didn't work.
There's issues when linking.

npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/opencv4nodejs
npm ERR! command failed
npm ERR! command sh -c -- node ./install/install.js
npm ERR! info install using lib dir: /usr/local/lib/node_modules/opencv4nodejs/node_modules/opencv-build/opencv/build/lib
npm ERR! /usr/local/lib/node_modules/opencv4nodejs/install/install.js:37
npm ERR!   throw new Error('library dir does not exist: ' + libDir)
npm ERR!   ^
npm ERR! 
npm ERR! Error: library dir does not exist: /usr/local/lib/node_modules/opencv4nodejs/node_modules/opencv-build/opencv/build/lib
npm ERR!     at Object.<anonymous> (/usr/local/lib/node_modules/opencv4nodejs/install/install.js:37:9)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1119:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:997:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:838:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:18:47
npm ERR! 
npm ERR! Node.js v18.9.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/takeshi.yanagita/.npm/_logs/2022-09-14T05_41_53_608Z-debug-0.log

**Comment by KazuCocoa** [comment]
Previously I succeeded to install opencv4nodejs with NodeJS 14 (npm v6), but haven't with nodejs 16 (npm v8). I haven't tried with nodejs 18 anymore, but nodejs18 also cannot install correctly.
https://github.com/appium/appium/issues/11865

**Comment by StephanB75** [comment]
library dir does not exist: /usr/local/lib/node_modules/opencv4nodejs/node_modules/opencv-build/opencv/build/lib

sounds like building the openCV node library failed anymore or the linking with
sudo npm link opencv4nodejs was missing

**Comment by mykola-mokhnach** [comment]
opencv4nodejs has not been maintained for years. I don't think it would be possible to make it working in the current nodejs env without applying special patches.

**Comment by jlipps** [comment]
there is an official appium 2 migration guide: https://appium.github.io/appium/docs/en/2.0/guides/migrating-1-to-2/

it's really not too big of a change. test code itself doesn't need to change at all in most cases.

**Comment by hello297** [comment]
I was able to get appium 2 working and my gosh.  It is just so much more simple to run opencv now...
Thank you everyone for commenting, I will close this ticket.

I do have one follow up question regarding appium 2, is there a way to specify udid in appium 2?  That's my only hang up.

Thank you!

**Comment by StephanB75** [comment]
> I was able to get appium 2 working and my gosh. It is just so much more simple to run opencv now... Thank you everyone for commenting, I will close this ticket.
> 
> I do have one follow up question regarding appium 2, is there a way to specify udid in appium 2? That's my only hang up.
> 
> Thank you!

i think still over the capability "appium:udid"
or if you use java and the XCUITestOptions "options.setUdid()"
