### ISSUE TITLE
How to get a screenshot with only web page

### ISSUE THREAD

**Issue by suzhenyu006** [appium/appium#17488]
## The problem

When using appium for automation, I found that if I use Android Chrome, I can get screenshots that only contain web pages, but not ios mobile safari

## Environment

* Appium version (or git revision) that exhibits the issue: appium version 1.22.3
* Last Appium version that did not exhibit the issue (if applicable): unkown
* Desktop OS/version used to run Appium: appium-python
* Node.js version (unless using Appium.app|exe): none
* Npm or Yarn package manager: none
* Mobile platform/version under test: ios 14.1 / all version i guess
* Real device or emulator/simulator: read device
* Appium CLI or Appium.app|exe: appium-python

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

<img width="540" alt="image" src="https://user-images.githubusercontent.com/38517127/190306630-56f0fc02-3be9-48cb-9a10-732b8819a589.png">

<img width="549" alt="image" src="https://user-images.githubusercontent.com/38517127/190306674-4f36c716-dd11-4f07-8f14-5d632bbcc832.png">

Sorry, the page content has been processed

## Code To Reproduce Issue [ Good To Have ]

`driver.save_screenshot(os.path.join('/Users/szy/Documents','test.png'))`

**Comment by KazuCocoa** [comment]
It is not available in xcuitest driver.
What about safaridriver? https://github.com/appium/appium-safari-driver

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by KazuCocoa** [comment]
I checked the safaridriver directly in another place. Safari driver actually captured the screen without tab bar etc, but the screen size was bigger than the actual Safari browser's window size like area hidden by tab bars by the OS.
Just FYI.
