### ISSUE TITLE
The test is getting passed in android but its not running in the emulator

### ISSUE THREAD

**Issue by sathya5401** [appium/appium#17484]
## The problem
When i run the test in vscode , the test is getting passed but its not running in the emulator. The emulator will open the apk I want to test and it will immediately close the apk (so the test doesnt happen in the emulator)  

## Environment
* Appium version : 1.22.3
* Desktop OS/version used to run Appium: Windows 11
* Node.js version (unless using Appium.app|exe): v16.14.2
* Npm or Yarn package manager: npm 8.5.0
* Mobile platform/version under test: Android 13
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: appium app
* using webdriverio

## Details
- terminal logs
- 
https://gist.github.com/sathya5401/2f35df590694428288be9dbd6cbd7e0e

## Link to Appium logs

https://gist.github.com/sathya5401/736a0d42c90b4163462e634a835e96f3

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/sathya5401/6f8eb48a9a875119d02e7ec887ad342d - (test scripts)

https://gist.github.com/sathya5401/9838797c2e7bdbf6ba7c8e309cb75bdd - ( my package.json & wdio.conf.js file)

**Comment by mykola-mokhnach** [comment]
I don't observe any obvious issues in the server log. The client sends the delete command and then tries to send some commands to a session that does not exist anymore.

**Comment by sathya5401** [comment]
Yeah, maybe that could be a reason why the test is getting passed.. But , the test is not running in the emulator ?  And the delete session command should be appearing after the test finished run in the emulator right?

**Comment by mykola-mokhnach** [comment]
> And the delete session command should be appearing after the test finished run in the emulator right?

I assume in theory it should, but we have what we have. Some script is still sending it.

**Comment by sathya5401** [comment]
Is there any way to solve it ? Any solutions ? I badly need it

**Comment by mykola-mokhnach** [comment]
Nothing from the server side. Perhaps, hire a consultant to review client automation scripts?
