### ISSUE TITLE
Unable to launch WebDriverAgent in Appium CLI and Simulator

### ISSUE THREAD

**Issue by URashmi23** [appium/appium#17498]
## The problem

I am trying to launch WebDriverAgent but getting xcodebuild failed with code 65 xcodebuild error message.
Please assist to resolve the same.

## Environment

* Appium version (or git revision) that exhibits the issue: **Appium v1.22.3**

* Last Appium version that did not exhibit the issue (if applicable): N/A

* Desktop OS/version used to run Appium: **MacBook Air OS - v12.6**

* Node.js version (unless using Appium.app|exe): **node - v18.9.0**

* Npm or Yarn package manager: **npm - 8.19.1**

* Mobile platform/version under test: **iOS**

* Real device or emulator/simulator: **Simulator** 

* Appium CLI or Appium.app|exe: **Appium CLI and Appium.app both** 

- Xcode: 14.0
- Appium inspector: 2022.8.1
- Appium Server GUI : 1.22.3-4

## Details
Trying to start session from Appium server and launch WebDriverAgent with the capabilities mentioned under Code section 

## Link to Appium logs
[https://gist.github.com/URashmi23/ebb9485c566bbda78ce2dd4fb9864715](url)

## Code To Reproduce Issue [ Good To Have ]
JSON
{
  "platformName": "iOS",
  "appium:deviceName": "iPhone 14 Pro Max",
  "appium:automationName": "XCUITest",
  "appium:udid": "D0FDB641-FE12-4BC1-A2EB-3CC1C95E5E5A",
  "appium:app": "/Users/rashmimohan/Downloads/ios-uicatalog-master/UIKitCatalog/build/Release-iphonesimulator/UIKitCatalog-iphonesimulator.app",
  "appium:showXcodeLog": true
}

**Screenshot:**
![Screenshot 2022-09-16 at 11 56 55 AM](https://user-images.githubusercontent.com/113539834/190572172-d6be0a24-00bc-4fa7-8f36-564465ebb017.png)

**Comment by mykola-mokhnach** [comment]
Please use the most recent xcuitest driver version available for Appium2.
The driver supplied with Appium 1 is not maintained anymore and  won't work with iOS 16
Closed as duplicate.
