### ISSUE TITLE
Plans on supporting wireless devices (i.e. Apple TV 4K)

### ISSUE THREAD

**Issue by gustavoriveray** [appium/appium#17506]
## The problem

More than an issue a question:

What are the plans for future support of wireless devices?. Looking at the documentation here: https://appium.io/docs/en/writing-running-appium/ios/ios-tvos/#tvos-support it seems that these kind of devices aren't supported currently, because [ios-deploy](https://github.com/ios-control/ios-deploy) doesn't support wireless devices. 

That project doesn't seem to be very active. Is there any plans to switch to another tool?

**Comment by KazuCocoa** [comment]
Afaik, we do not have.

Latest ios-deploy has finding network devices option, so i wonder recent ios-deploy can. (or our appium-ios-device can find it?) Did you tried that, and did not work? I don't have the 4k environment so I cannot verify it

**Comment by KazuCocoa** [comment]
How did you build the WDA module?
I wondered if you ran `xcodebuild` for WDA, and ios-deploy with your test target to install it.

It seems like... the case is installation was working (but the build target was maybe for a simulator, not a real device), so ios-deploy was working.

**Comment by raamojirao** [comment]
build target was a real 4K Apple TV device and also as seen in the screenshot, 4K Apple TV device is mentioned as **unsupported family**. Do we know if that could be the reason why we are not able to build
<img width="570" alt="Screen Shot 2022-09-27 at 3 48 14 PM" src="https://user-images.githubusercontent.com/21014170/192622735-1483dfa5-32e2-4a40-9c03-3028d9cb5bd5.png">

**Comment by KazuCocoa** [comment]
What about running tests with WebDriverAgentRunner_tvOS  scheme via the Xcode?

**Comment by raamojirao** [comment]
Appium - 1.22.3
Xcode - 14.0.1
tvOS - 16.0
Device - Apple TV 4K
I get error as shown in the screenshot when I run **xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner_tvOS -destination 'id=dc570a73021da577b0e8eb3da32b3e575ce6aa93' test**
<img width="1591" alt="Screen Shot 2022-09-27 at 9 51 52 PM" src="https://user-images.githubusercontent.com/21014170/192669376-9a21b140-94f5-4273-9698-dea86c4e3d7e.png">

**Comment by mykola-mokhnach** [comment]
The xcuitest driver version supplied with Appium 1 won't work with Xcode 14. Consider upgrading the server to Appium 2, so you could fetch the most recent driver.

**Comment by raamojirao** [comment]
ok thanks! I was able to install WebDriverAgent on the Apple 4K device. I wrote a simple script with Appium, Ruby to launch the app but it's not successful. Please find below the code and the error I get.
```
desired_caps = {
      "platformName": "tvOS",
      "platformVersion": "16.0",
      "deviceName": "4K_AppleTV",
      "udid":"dc570a73021da577b0e8eb3da32b3e575ce6aa93",
      "bundleId":"com.xxxx.x2",
      "automationName": "XCUITest"
  }

  appium_driver = Appium::Driver.new({
                                         'caps' => desired_caps,
                                         'appium_lib' => {
                                             :server_url => "http://localhost:4723/wd/hub"
                                         }}, true)
  @driver = appium_driver.start_driver
```
I get this error message 
**The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource (Selenium::WebDriver::Error::UnknownComman
![Screen Shot 2022-09-28 at 1 14 54 PM](https://user-images.githubusercontent.com/21014170/192846789-332f8296-bbff-46c1-8724-ec0efb4e13e9.png)
dError)**

**Comment by KazuCocoa** [comment]
Appium 2 does not need `/wd/hub` by default, or you need to start an appium 2 server with `--base-path=/wd/hub`

**Comment by sudheer54900** [comment]
is this issue Fixed ? Appium supports Apple TV 4k devices ?

**Comment by raamojirao** [comment]
@sudheer54900 yes Appium supports 4k devices. What error are you facing?

**Comment by Sendel93** [comment]
Hi! I am facing some trouble trying to connect to my Apple TV 4k. Investiganting on the web, i suppose that maybe my xcode config is not correct, but i am not sure if 4k devices from apple are supported in appium, as the xcuidriver documentation says it does not.

I am a bit lost as is my first appium project with a tv device and i don't have any other devices to test on. I'm getting the same error as @raamojirao  did when trying to install the WebDriverAgent, even though it shows in the devices list:

```
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner_tvOS -destination id=04b7d9dfa0ac4cf4d6624cb52893b46393fad097 test

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

2023-03-14 16:09:47.556 xcodebuild[33603:401367] Writing error result bundle to /var/folders/rk/k3rl4vc55z56wwjs4h55hh5h0000gn/T/ResultBundle_2023-14-03_16-09-0047.xcresult
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
		{ id:04b7d9dfa0ac4cf4d6624cb52893b46393fad097 }

	The requested device could not be found because no available devices matched the request.

	Available destinations for the "WebDriverAgentRunner_tvOS" scheme:
		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Any tvOS Device }
		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Any tvOS Simulator Device }
		{ platform:tvOS, id:04b7d9dfa0ac4cf4d6624cb52893b46393fad097, name:Apple TV 4K }
		{ platform:tvOS Simulator, id:EA20A20C-5078-4A87-BC5A-D2310602FF48, OS:16.1, name:Apple TV }
		{ platform:tvOS Simulator, id:5B1ADFE2-E130-432B-B7CB-380F31D4196D, OS:16.1, name:Apple TV 4K (3rd generation) }
		{ platform:tvOS Simulator, id:FF972603-DC90-4F02-A2FB-A068D14AE239, OS:16.1, name:Apple TV 4K (3rd generation) (at 1080p) }
```

I am using Appium 2 from the command line. When trying to connect through Appium Inspector i get the same error with 70 code

**Comment by KazuCocoa** [comment]
Probably https://github.com/appium/appium/issues/17896 may help

**Comment by Sendel93** [comment]
It did help indeed!thanks @KazuCocoa

**Comment by Annjames1** [comment]
Hi team any updates on  this,  I was able to install WebDriverAgent on the Apple device  but the app is not launching on Apple TV
any suggestions please !

Xcode - 14.3.1
Apple TV -15.6
- xcuitest - 4.33.2
Appium -2.0.1
CC  : @KazuCocoa @raamojirao @Sendel93 @mykola-mokhnach
