### ISSUE TITLE
Doing an ‘adb uiatomator dump’ didn’t work as appium has a running uiautomator process .

### ISSUE THREAD

**Issue by studyJavaForLive** [appium/appium#17502]
## Can not get uix file from android devices when appium is running uiautomator process

Doing an ‘adb uiatomator dump’ didn’t work as appium has a running uiautomator process .
How can i get uix file when appium's uiautomator program is running?
Help me,please! thanks a lot.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.21.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v14.16.1
* Npm or Yarn package manager: Npm
* Mobile platform/version under test: Android 10/Android 6
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Code To Reproduce Issue [ Good To Have ]
[cmd]: >adb shell uiautomator /dump /data/local/tmp/ui.uix

**Comment by KazuCocoa** [comment]
I wonder if `"appium:disableSuppressAccessibilityService": true` helps

**Comment by studyJavaForLive** [comment]
> I wonder if `"appium:disableSuppressAccessibilityService": true` helps

Thank you very much!
I will try it right now.

**Comment by studyJavaForLive** [comment]
> > I wonder if `"appium:disableSuppressAccessibilityService": true` helps
> 
> Thank you very much! I will try it right now.

**Comment by studyJavaForLive** [comment]
> > > I wonder if `"appium:disableSuppressAccessibilityService": true` helps
> > 
> > 
> > Thank you very much! I will try it right now.
> > Unluckly,It seems do not work. I have find a link of stackoverflow about this problem.
> > [stackoverflow]:https://discuss.appium.io/t/getting-uix-file-suitable-for-uiautomatorviewer/8422
> > The method also does no work.

**Comment by mykola-mokhnach** [comment]
It looks like we don't know the answer to this question. Perhaps, you may get some more info at Google Android forums.
