### ISSUE TITLE
desiredCapConstraints makes me sad

### ISSUE THREAD

**Issue by boneskull** [appium/appium#17518]
## El Problemo

`desiredCapConstraints` is a property of a `Driver` object describing the allowed shape of incoming capabilities from WD clients.  The type of `desiredCapConstraints` is nominally `Readonly<Record<string,Constraint>>` where:

```typescript
// this is not quite what it looks like, but rather what it ought to be
interface Constraint {
  readonly presence?: boolean | Readonly<{allowEmpty: boolean}>;
  readonly isString?: boolean;
  readonly isNumber?: boolean;
  readonly isBoolean?: boolean;
  readonly isObject?: boolean;
  readonly isArray?: boolean;
  readonly deprecated?: boolean;
  readonly inclusion?: ReadonlyArray<string>;
  readonly inclusionCaseInsensitive?: ReadonlyArray<string>;
}
```

Given that they are not theoretically unique to instances, `desiredCapConstraints` should be immutable.  There's an argument here that they should actually be `static` properties, but that's a separate issue.

> Note that they aren't _entirely_ immutable otherwise; there's at least one place in the logic where we're deleting a property from a `Constraints` object--which isn't 100% necessary.

The problem is that while the `Driver` interface wants a `desiredCapConstraints` prop, the `BaseDriverCore` class (the thing that `BaseDriver` is before mixins) defines it with _accessors_.  The "real" `desiredCapConstraints`--which is the "built-in" set of `Constraint`s--is stored in a `_desiredCapConstraints` property.

The intent of the accessors is to allow subclasses to define their own constraints via variable assignment (e.g., `this.desiredCapConstraints = {stuff}`).  Magically, the setter merges the "built-in"'s from `BaseDriver` with whatever the subclass defines.  The getter returns the merged set.  Beyond this, the intent is unclear to me, and may simply be for convenience in `BaseDriver`, since (I'm assuming) the `Driver` author probably won't need to interact directly with constraints once they are defined.

So, due to the presence of a setter, we no longer have an immutable object. Because we don't have an immutable object, we cannot use the constraints to derive the shape of any incoming `Capabilities` (which we can do otherwise; see the `DriverCaps` type).  The end result is that calling e.g., `super.createSession()` from the subclass returns a (tuple containing a) `Capabilities` object that is constrainted _only_ by the shape of the "built-in" `desiredCapConstraints`.  Everything else is just of type `any`.

Furthermore, the accessor means that implementors cannot use things such as public fields to define their constraints; they _must_ use assignment to `this.desiredCapConstraints` (is this documented anywhere?) or Appium will claim that the constraints are unrecognized, and driver implementors will be clueless as to why.  For example, this will cause Appium to emit warnings:

```js
class MyDriver extends BaseDriver {
  desiredCapConstraints = {
    foo: {isString: true, presence: true},
    bar: {isBoolean: true, presence: true},
  };
}
```

Instead, this is what you have to do:

```js
class MyDriver extends BaseDriver {
  constructor(...args) {
    super(...args);
    this.desiredCapConstraints = {
      foo: {isString: true, presence: true},
      bar: {isBoolean: true, presence: true},
    };
  }
}
```

The thing that prompted this was that it _also_ creates problems for us when attempting to automatically generate documentation for drivers.  Unless a driver author explicitly adds types via TS or JSDoc, we cannot know what the shape of the `desiredCapConstraints` is, and thus cannot automatically generate the relevant documentation.

And finally, the shape of the built-in capabilities exist in two places: 1. in `@appium/types` via `@wdio/types`, and 2. as a `Constraints` object in `@appium/base-driver`.  Obviously, we don't need two separate places; we can just derive caps from the constraints.

## Loco Solution

1. Remove the `desiredCapConstraints`/`_desiredCapConstraints` from `BaseDriverCore` _entirely_. 
2. Move it into `@appium/types` as a constant object.  This is because `Capabilities` will now consume the object via `DriverCaps`.  It cannot live in `@appium/base-driver` because that would create a circular dependency.  Note that this may require a tweak to the TS configuration to generate the appropriate `.js` file (or we need to use Babel like the other packages).
3. Update `Capabilities` (and `W3CCapabilities`) to use this object instead of the stuff from wdio.
4. Import these constraints into `BaseDriver` and use it to validate caps, as before.
5. Wherever we are referencing `this.desiredCapConstraints` in `BaseDriver` (so, including the mixins), ensure that we've merged whatever `this.desiredCapConstraints` is (which will be defined by the downstream drivers) with the built-in constraints.
6. Probably re-export these built-in constraints if driver authors need them (unclear).

_Assuming downstream drivers aren't futzing with `this.desiredCapConstraints` directly_, this should (in theory):

1. Not break people
2. Make the built-in `Constraints` object the single-source-of-truth for what capabilities can contain
3. Allow subclasses of `BaseDriver` to define their own constraints via whatever means they prefer (assignment, public field, prototype assignment, etc)
4. Improve typing of capabilities within downstream drivers

## Yes, But

`desiredCapConstraints` should really just be a JSON schema. 😀

**Comment by mykola-mokhnach** [comment]
If the changes are not going to break the legacy stuff then just do it. I don't think capability validation strategy was ever properly documented or exposed anywhere for driver authors, so that would be a cool addition.

**Comment by boneskull** [comment]
would like @jlipps' thoughts; it is not quite "blocking" the documentation effort but is making things much more difficult

**Comment by jlipps** [comment]
Yeah I think this is a good change. We can easily grep through our drivers for `this.desiredCapConstraints` to see if we do any of the aforementioned futzing. I would expect not.

**Comment by boneskull** [comment]
I almost have an implementation ready for this, but need to test it against something other than `FakeDriver`
