### ISSUE TITLE
Sporadic WDA 500. Cannot pass nil activity to runActivityNamed:block:

### ISSUE THREAD

**Issue by alex-i-rybkin** [appium/appium#17527]
## The problem

Sometimes iOS tests are failing with an error from WDA. Could not find any regularity to the failures. Various commands result in this error: wda/touch/perform, performTouch, activateApp
`2022-09-26 03:03:47:216 - [35m[WD Proxy][39m Got response with status 500: {"value":{"error":"unknown error","message":"Cannot pass nil activity to runActivityNamed:block:","traceback":"(\n\t0   CoreFoundation                      0x0000000181bd6d50 3BDAC092-5C30-38CB-B212-167AE4A7C9C4 + 597328\n\t1   libobjc.A.dylib                     0x0000000198f506a8 objc_exception_throw + 56\n\t2   Foundation                          0x00000001833a899c E00646F4-FB8E-336D-8025-6DA2421D78CB + 1190300\n\t3   XCTestCore                          0x00000001029e6b4c __38-[XCTContext _runActivityNamed:block:]_block_invoke + 144\n\t4   XCTestCore                          0x00000001029e7648 -[XCTContext _runActivityNamed:type:block:] + 308\n\t5   XCTestCore                          0x00000001029e6a98 -[XCTContext _runActivityNamed:block:] + 148\n\t6   XCTestCore                          0x00000001029e6598 +[XCTContext runActivityNamed:block:] + 164\n\t7   XCUIAutomation                      0x0000000102fa3e5c __67-[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]_block_invoke + 448\n...`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.2
* WDA: 4.5.1
* Last Appium version that did not exhibit the issue (if applicable): ??
* Desktop OS/version used to run Appium: Linux
* Node.js version (unless using Appium.app|exe): 16.17.0
* Npm or Yarn package manager: npm
* Mobile platform/version under test: iOS: 14.6, 15.1, 15.2, 15.3, 15.3.1 
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

Example of the command that sometimes results in the 500 error.
`2022-09-22 00:00:13:085 - [debug] [35m[WD Proxy][39m Proxying [POST /wda/touch/perform] to [POST http://127.0.0.1:8100/session/A49681AB-1146-445D-B8F2-D1E5A49195D7/wda/touch/perform] with body: {"actions":[{"action":"press","options":{"x":207,"y":627}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":207,"y":268}},{"action":"release","options":{}}]}`

**Comment by KazuCocoa** [comment]
Do you have the system log?

**Comment by alex-i-rybkin** [comment]
you mean more of appium server logs?

**Comment by KazuCocoa** [comment]
I mean the system log of the device which is available via `appium:showIOSLog` (via appium capabilities case) to see the stack trace and around system info more to guess where the error comes from, if appium can improve or XCTest internal.
