### ISSUE TITLE
For the same page in my app, element different between Sauce Labs session and local

### ISSUE THREAD

**Issue by ColinChen1121** [appium/appium#17526]
## The problem

we find that python "self.driver page_source()" shows different content between local simulator with saucelabs simulator for the same page.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.1
* Real device or emulator/simulator: simulator 
* Appium CLI or Appium.app|exe: Appium.app

## Details
The following is the latest response from Saucelabs support team:

I wanted to reach out about this issue as I have investigated this with our engineering team and we can't seem to find a reason why the element in your app is appearing differently in a local Appium Inspector emulator session.
 
The most recent theory was that the uiautomator2 driver version might have been older for the local emulator session depending on what version of appium server is being run. 
 
Sauce Labs sessions use AndroidUiautomator2Driver (v1.70.1), which is newer version, so I thought that by updating the local Appium Server this would allow the local session to use a newer version of uiautomator2 driver and this might then make the element name match the Sauce Labs session.
 
Unfortunately, updating the local Appium Server version and uiautomator2 driver still created a session where the element was different from the Sauce Labs session.
 
I might suggest opening an issue with Appium for this as there doesn't seem to be a solution that can be found on our end.

You can refer to this saucelabs tickets
(https://support.saucelabs.com/hc/en-us/requests/122023)

**Comment by KazuCocoa** [comment]
I cannot see the ticket, but generally, the result depends on what AccessibilityNodeInfo (by Android OS) returns, so the same emulator environment may return the same result.

**Comment by mykola-mokhnach** [comment]
Also, the driver version used is very old. We only maintain the most recent driver version, which is only available with Appium 2.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by ColinChen1121** [comment]
@mykola-mokhnach 
we used Appium 1.22.0
<img width="268" alt="Screen Shot 2022-09-29 at 5 36 13 PM" src="https://user-images.githubusercontent.com/114382277/192997113-4222652c-fa80-4607-9dab-ee2a23ce5df6.png">

Both test use the the following setting:
    "platformName": "android",
    "appium:deviceName": "Google Pixel 3 GoogleAPI Emulator",
    "appium:platformVersion": "10.0",

[local.txt](https://github.com/appium/appium/files/9673410/local.txt)
<img width="896" alt="local" src="https://user-images.githubusercontent.com/114382277/193000251-53d7b1d9-c00f-44fe-a715-89fbe756e910.png">
[saucelabs.txt](https://github.com/appium/appium/files/9673413/saucelabs.txt)
<img width="1792" alt="saucelabs" src="https://user-images.githubusercontent.com/114382277/193000279-e8fb081c-1799-43ad-bc83-4977afb8b239.png">

Could you please help to invest this issue again?

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help much on that. It is Google's UiAutomator framework which is responsible for generating the page source.

You could also read the [troubleshooting article](https://github.com/appium/appium-uiautomator2-driver#elements-cannot-be-found) and play with some setting values to hide/show various elements from the source XML.
