### ISSUE TITLE
"mobile: swipe" when used to scroll to an element, intermittently taps on that element

### ISSUE THREAD

**Issue by MishkaTheCub** [appium/appium#17534]
## The problem

Instead of scrolling to a particular element, the element is tapped.

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.44
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: macOS 12.6
* Node.js version (unless using Appium.app|exe): node 18.3.0
* Npm or Yarn package manager: npm 8.11.0
* Mobile platform/version under test: iOS 16.0.2 / iOS 16.1 beta. **Not reproducible on iOS 15.7**
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Details

In my test I work with a screen with the list of device settings. The test verifies that all the settings are visible. If the setting is not visible the test will scroll to the last XCUIElementTypeCell in the current view, which will show the settings below it. Intermittently the Cell element gets tapped instead of scrolled to.

## Link to Appium logs
https://gist.github.com/MishkaTheCub/8426cd6ee9675f870be351d237280c4f
the timestamps for instances when the swipe didn't work and the element was tapped instead are:
2022-09-28 06:23:07:852
2022-09-28 06:23:20:767 

## Code To Reproduce Issue [ Good To Have ]

```
 public void scrollToElement(String locator) {

        locator = "**/XCUIElementTypeOther[$name='DOORBELL SETTINGS'$]/*/XCUIElementTypeCell[-1]";
        RemoteWebElement el = (RemoteWebElement) driver.findElement(MobileBy.iOSClassChain(locator));

        HashMap<String, String> scrollObject = new HashMap<>();
        scrollObject.put("direction", "up");
        scrollObject.put("elementId", el.getId());
        driver.executeScript("mobile: swipe", scrollObject);
    }

```

**Comment by mykola-mokhnach** [comment]
This method is a simple wrapper over https://github.com/appium/appium-xcuitest-driver#references 
Consider reporting the issue to Apple

**Comment by MishkaTheCub** [comment]
Got it, tickets filed via Feedback Assistant 🤞

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
