### ISSUE TITLE
How to click on textSpan of richText

### ISSUE THREAD

**Issue by jagadeeshpurplle** [appium/appium#17546]
Hey all, 

Can anybody help on how to click on `TextSpan` of `RichText`?

**Here is my application looks like:**
<img width="817" alt="Screenshot 2022-10-03 at 6 25 23 PM" src="https://user-images.githubusercontent.com/25878053/193582089-1f6e814a-eaf7-4e5a-b53b-be0e8daf6d4c.png">

Here is the outcome of above application code and i wanted to click on `Sign up` link.
<img width="199" alt="Screenshot 2022-10-03 at 6 22 33 PM" src="https://user-images.githubusercontent.com/25878053/193581228-ce9c0cd3-7a0f-4baa-a493-18d53a45e2ec.png">

I see there are couple of solutions(https://github.com/flutter/flutter/issues/56023) with respective to flutter_driver test and not related to appium flutter test using webdriverIO.!

@KazuCocoa

**Comment by mykola-mokhnach** [comment]
Kindly use Appium forum to ask questions
