### ISSUE TITLE
appium:avd capability does not launch Android Emulator

### ISSUE THREAD

**Issue by RahulNethi** [appium/appium#17549]
## The problem

I am trying to launch emulator (that is returned in emulator -avd list) with appium:avd capability but it does not recognize/honor any of the avd capabilities set. This used to work just fine in previous versions (1.22.3)

## Environment

* Appium version: v2.0.0-beta.44
* Last Appium version that did not exhibit the issue (if applicable): v1.22.3
* Desktop OS/version used to run Appium: macOS Monterey 12.5.1
* Node.js: 6.17.1
* Npm: 8.15.0
* Mobile platform/version under test: Android 10
* Real device or emulator/simulator: Emulator

## Details

It works when we manually launch the emulator but it does not launch the emulator automatically and wait for it.
I do not see the following log anymore.

[debug] [35m[ADB][39m Launching Emulator with AVD Pixel4, launchTimeout 120000ms and readyTimeout 120000ms

## Link to Appium logs

https://gist.github.com/RahulNethi/80d8a07d1215684a257f23f64d1925cc

## Code To Reproduce Issue
DesiredCapabilities cap = new DesiredCapabilities();
			cap.setCapability("appium:avd", Pixel4);
			cap.setCapability("appium:avdArgs", "-no-snapshot-load -port 5554");
			cap.setCapability("appium:avdLaunchTimeout", 120000);
			cap.setCapability("appium:avdReadyTimeout", 120000);
			cap.setCapability("appium:skipUnlock", true);
			cap.setCapability("appium:udid", "emulator-5554");
			cap.setCapability("appium:deviceName", Pixel4);
			cap.setCapability("platformName", "Android");
			cap.setCapability("appium:automationName", "uiautomator2");
			cap.setCapability("appium:adbExecTimeout", 120000);
			cap.setCapability("appium:newCommandTimeout", 120);
			cap.setCapability("appium:unicodeKeyboard", true);
			cap.setCapability("appium:resetKeyboard", true);
			cap.setCapability("appium:enforceAppInstall", true);
			cap.setCapability("appium:app", apkFile.getAbsolutePath());
			cap.setCapability("appium:appActivity", appActivity);
			cap.setCapability("appium:locale", country);
			cap.setCapability("appium:language", language);
			cap.setCapability("appium:systemPort", Integer.parseInt(systemPort));
			URL url = new URL("http://127.0.0.1:" + portNumber + "/wd/hub");
			driver = new AndroidDriver<MobileElement>(url, `cap);

**Comment by mykola-mokhnach** [comment]
Yes, this seems to be a regression. I'll try to fix it

**Comment by mykola-mokhnach** [comment]
The patch has been published in UIA2 driver 2.7.1

**Comment by RahulNethi** [comment]
@mykola-mokhnach Thanks for the quick fix. Works as expected now.
