### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code ‘70’ for Apple TVOS 15.3.

### ISSUE THREAD

**Issue by pmsviacom** [appium/appium#17545]
I am facing an issue with my AppleTV - TVOS 15.3 test automation set up and configuration. I am able to launch my apps manually, but not working when i’m executing via Appium inspector as well as Appium script. Getting error as xcode build failure 70.

The proper set up has been followed for the configuration, but seems like some issues with the WebDriver agent or Appium - Appium project is able to build successfully.

Version Details as follows:-
TVOS -15.3 , Xcode 13.3, Mac OS- 12.5, Appium 1.22.3 . Installed all the necessary packages required for the set up as well. Able to build the Xcode project successfully.

From the showXcode logs i can see the device is not getting identified.

## Details

If necessary, describe the problem you have been experiencing in more detail.

Appium logs:-
```

Failed to create session. An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70 xcodebuild error message: objc[68902]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x200087620) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103ce4598). One of the two will be used. Which one is undefined. objc[68902]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x200087670) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103ce45e8). One of the two will be used. Which one is undefined. objc[68902]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x2000876c0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103ce4638). One of the two will be used. Which one is undefined. objc[68902]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x200087710) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103ce4688). One of the two will be used. Which one is undefined. objc[68902]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x200087760) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103ce46d8). One of the two will be used. Which one is undefined. objc[68902]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x2000877b0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103ce4728). One of the two will be used.

    
[debug] [W3C] /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild build-for-testing test-without-building -project /opt/homebrew/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner_tvOS -derivedDataPath /Users/Library/Developer/Xcode/DerivedData/WebDriverAgent-fxmsedpwfaalxlbcwefbceeuodem -destination id=e833be5a2126fa8cd6d853f3592ec4aff78ca07a IPHONEOS_DEPLOYMENT_TARGET=15.3 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
[debug] [W3C] User defaults from command line:
[debug] [W3C]     IDEDerivedDataPathOverride = /Users/Library/Developer/Xcode/DerivedData/WebDriverAgent-fxmsedpwfaalxlbcwefbceeuodem
[debug] [W3C]     IDEPackageSupportUseBuiltinSCM = YES
[debug] [W3C] Build settings from command line:
[debug] [W3C]     COMPILER_INDEX_STORE_ENABLE = NO
[debug] [W3C]     GCC_TREAT_WARNINGS_AS_ERRORS = 0
[debug] [W3C]     IPHONEOS_DEPLOYMENT_TARGET = 15.3
[debug] [W3C] xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[debug] [W3C] 		{ id:e833be5a2126fa8cd6d853f3592ec4aff78ca07a }
[debug] [W3C] 	The requested device could not be found because no available devices matched the request.
[debug] [W3C] 	Available destinations for the "WebDriverAgentRunner_tvOS" scheme:
[debug] [W3C] 		{ platform:tvOS, id:e833be5a2126fa8cd6d853f3592ec4aff78ca07a, name:Bedroom }
[debug] [W3C] 		{ platform:tvOS Simulator, id:A94F219F-18D6-4B16-A3BD-0B0237628FED, OS:15.4, name:Apple TV }
[debug] [W3C] 		{ platform:tvOS Simulator, id:553FA7FF-8446-4016-B02D-81F9E650EEFC, OS:15.4, name:Apple TV }
[debug] [W3C] 		{ platform:tvOS Simulator, id:EC6861CE-8EDC-4BB0-87CE-96F37C8243FC, OS:15.4, name:Apple TV 4K (2nd generation) }
[debug] [W3C] 		{ platform:tvOS Simulator, id:AC569E17-71D0-42B8-A33E-EF04592E8A4D, OS:15.4, name:Apple TV 4K (at 1080p) (2nd generation) }
[debug] [W3C] 	Ineligible destinations for the "WebDriverAgentRunner_tvOS" scheme:
[debug] [W3C] 		{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Any tvOS Device }
[debug] [W3C] 		{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Any tvOS Simulator Device }. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [W3C]     at quitAndUninstall (/opt/homebrew/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:585:15)
```

Issue has been already reported here as well and no resolution found.
https://discuss.appium.io/t/unable-to-launch-webdriveragent-because-of-xcodebuild-failure-xcodebuild-failed-with-code-70/37366

https://developer.apple.com/forums/thread/715187

**Comment by mykola-mokhnach** [comment]
Please upgrade XCUITest driver to the most recent version and the Appium server to v2. Appium 1 is not maintained anymore

**Comment by pmsviacom** [comment]
Hello @mykola-mokhnach ,
I was able to upgrade the Appium to version 2  and followed the steps as well as per the 17359 issue. 
But i am not able to launch my app with the capabilities, i am seeing - 
_Failed to create session. The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource_

[debug] [HTTP] No route found for /wd/hub/sessions
[HTTP] <

The same was working with the previous versions of Appium.

**Comment by mykola-mokhnach** [comment]
This is expected. Appium 2 does not use `/wd/hub` prefix anymore, but rather `/` by default. This could be changed by providing `--base-path` argument to the server

**Comment by pmsviacom** [comment]
@mykola-mokhnach , Thanks for the update. i tried to run via the command "appium server -a 127.0.0.1 -pa /wd/hub --allow-cors -p 4723 --use-plugins=relaxed-caps --log-timestamp --local-timezone" and able to launch app on my TVOS. 
Currently trying to launch the app via test scripts, i just tried and failed with appiumCommand executor as

Appium initiation failed with error: info Appium Setting NODE_PATH to '/opt/homebrew/lib/node_modules'
[ERROR] Unrecognized arguments: -U <Udid>,
checking that from my end and will revert back with my updates
Thanks

**Comment by KazuCocoa** [comment]
The appium server log may help

**Comment by pmsviacom** [comment]
I just tried with the help of the AppiumDriverLocalService. 
AppiumDriverLocalService service = AppiumDriverLocalService.buildService(new AppiumServiceBuilder().usingDriverExecutable(new File("/opt/homebrew/Cellar/node/18.7.0/bin/node")).
					withAppiumJS(new File("/opt/homebrew/bin/appium")).withIPAddress("127.0.0.1").
					usingPort(4723).withArgument(() -> "-pa", "/wd/hub").withArgument(() -> "--use-plugins=relaxed-caps"));
			
after the service started, im seeing **[Appium] spawn npm ENOENT**

**Comment by mykola-mokhnach** [comment]
> Appium initiation failed with error: info Appium Setting NODE_PATH to '/opt/homebrew/lib/node_modules'
> [ERROR] Unrecognized arguments: -U "Udid"
> checking that from my end and will revert back with my updates

Looks like there is some issue with these test scripts. Try to ask at Appium forum

**Comment by pmsviacom** [comment]
Hello @mykola-mokhnach , @KazuCocoa .

i tried to give like -
AppiumDriverLocalService.buildService(new AppiumServiceBuilder().usingDriverExecutable(new File("/opt/homebrew/Cellar/node/18.7.0/bin/node")).
					withAppiumJS(new File("/opt/homebrew/lib/node_modules/appium/build/lib/main.js")).withIPAddress("127.0.0.1").
					usingPort(4723).withCapabilities(capabilities).withArgument(() -> "-pa", "/wd/hub").withArgument(() -> "--use-plugins=relaxed-caps"));

but i dont know why, its showing as o.appium.java_client.service.local.InvalidServerInstanceException: Node Package Manager (npm) is either not installed or its executable is not present .

i can see the node executable. Any thoughts?

**Comment by KazuCocoa** [comment]
I guess NODE_PATH was not properly set in the running environment

**Comment by Param3159** [comment]
/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent

**Comment by tc-mnunez** [comment]
my solution was, download the lates iOS OS in simulators and works fine

**Comment by Karthik-m-k** [comment]
Hi Everyone, you can refer my comment in the following ticket to resolve this issue. [https://github.com/appium/appium/issues/17545](url)
