### ISSUE TITLE
iOS fails to hide_keyboard on appium-xcuitest-driver 4.11.1 with legit conditions

### ISSUE THREAD

**Issue by ehabibov** [appium/appium#17550]
## The problem

Trying to hide keyboard on iOS with corresponding python client method but receiving error:
```
[debug] [XCUITestDriver@4844 (b91203d3)] Proxying [POST /wda/keyboard/dismiss] to [POST http://127.0.0.1:8100/session/8840DD90-45AF-45C9-9BF7-7B5794C62824/wda/keyboard/dismiss] with body: {"keyNames":["Done","done"]}
[XCUITestDriver@4844 (b91203d3)] Got response with status 400: {"value":{"error":"invalid element state","message":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test.\" UserInfo={NSLocalizedDescription=Did not know how to dismiss the keyboard. Try to dismiss it in the way supported by your application under test.}","traceback":""},"sessionId":"8840DD90-45AF-45C9-9BF7-7B5794C62824"}
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Monterey 12.5.1
* Node.js version (unless using Appium.app|exe): 18.9.1
* Npm or Yarn package manager: npm 8.19.1
* Mobile platform/version under test: 15.2
* Real device or emulator/simulator: real iPhone XS
* Appium CLI or Appium.app|exe: CLI

## Additional versions (some were updated manually after appium npm installation):
```
 ~/.nvm/versions/node/v18.9.1/lib/node_modules/appium/node_modules  #v0.38.0  cat appium-xcuitest-driver/package.json| jq .version                                                                                              0|3 ✘  20:08:04
"4.11.1"
 ~/.nvm/versions/node/v18.9.1/lib/node_modules/appium/node_modules  #v0.38.0  cat appium-ios-driver/package.json| jq .version                                                                                                       ✔  20:08:07
"4.8.3"
 ~/.nvm/versions/node/v18.9.1/lib/node_modules/appium/node_modules  #v0.38.0  cat appium-ios-device/package.json| jq .version                                                                                                       ✔  20:08:35
"2.4.5"
 ~/.nvm/versions/node/v18.9.1/lib/node_modules/appium/node_modules  #v0.38.0  cat appium-webdriveragent/package.json| jq .version                                                                                                   ✔  20:08:43
"3.17.0"
 ~/.nvm/versions/node/v18.9.1/lib/node_modules/appium/node_modules  #v0.38.0  cat appium-webdriveragent/package.json| jq .version
```
Appium-Python-Client==2.7.0

## Details
Almost the same case as https://github.com/appium/appium/issues/15073 but mine one has legit conditions (as Mykola pointed out https://github.com/appium/appium/issues/15073#issuecomment-770661510) - I have "Done" button and it is clearly visible with Inspector.

Appium log provided executing python console line `driver.hide_keyboard(key_name="Done")`:
![python_debugger](https://user-images.githubusercontent.com/20490584/193639088-987f78a0-a025-4126-a1bb-2a575c936478.jpg)
![inspector](https://user-images.githubusercontent.com/20490584/193639166-209c1dc4-53dc-4949-b3c9-a02bf1884f45.jpg)

Used capabilities (some values removed) to let know that nothing potentially related was used :
```
Creating session with W3C capabilities: {
[debug] [XCUITestDriver@4844]   "alwaysMatch": {
[debug] [XCUITestDriver@4844]     "platformName": "iOS",
[debug] [XCUITestDriver@4844]     "appium:automationName": "XCUITest",
[debug] [XCUITestDriver@4844]     "appium:udid": "<removed>",
[debug] [XCUITestDriver@4844]     "appium:derivedDataPath": "~/Library/Developer/Xcode/DerivedData",
[debug] [XCUITestDriver@4844]     "appium:xcodeOrgId": "<removed>",
[debug] [XCUITestDriver@4844]     "appium:xcodeSigningId": "<removed>",
[debug] [XCUITestDriver@4844]     "appium:usePrebuiltWDA": true,
[debug] [XCUITestDriver@4844]     "appium:showXcodeLog": true,
[debug] [XCUITestDriver@4844]     "appium:app": "<removed>"
[debug] [XCUITestDriver@4844]   },
[debug] [XCUITestDriver@4844]   "firstMatch": [
[debug] [XCUITestDriver@4844]     {}
[debug] [XCUITestDriver@4844]   ]
[debug] [XCUITestDriver@4844] }
```

Also I want to point out that XCUITestDriver (and Inspector) sends "done" button label/name by default (when, for ex., no args passed to method) while all cases that I faced on iOS had capitalised "Done" label/name. I mean - default value has no use cases at all.
```
[debug] [W3C (e1285559)] Calling AppiumDriver.hideKeyboard() with args: [null,null,null,null,"e1285559-86b2-4b3c-bf27-00871ad90c52"]
[debug] [XCUITestDriver@ab03 (e1285559)] Executing command 'hideKeyboard'
[debug] [XCUITestDriver@ab03 (e1285559)] Proxying [POST /wda/keyboard/dismiss] to [POST http://127.0.0.1:8100/session/4E04A0F2-C8AC-43E9-BDBA-0219C437EF7B/wda/keyboard/dismiss] with body: {"keyNames":["done"]}
```

## Link to Appium logs
https://gist.github.com/ehabibov/6a6359c490fbf0d2b61cfb03f3224ef0

## Code To Reproduce Issue [ Good To Have ]
`driver.hide_keyboard("Done")`

**Comment by KazuCocoa** [comment]
I guess [keyboard](https://developer.apple.com/documentation/xctest/xcuielementtype/xcuielementtypekeyboard?language=objc) in XCTest did not include the area as keybaord, where appium depends on it.

Can you interact with the Done button with find element and click it?

**Comment by mykola-mokhnach** [comment]
This behaviour is expected. We only try to click the corresponding button if it is present on the keyboard itself. Toobar buttons don't belong to the keyboard and thus are not included

**Comment by ehabibov** [comment]
@KazuCocoa, @mykola-mokhnach You are right, as I just have realised, "mine" "Done" button is not legit at all, it is part of some toolbar and closing another keyboard (having "done" button in a corner) via method is successful.

Closing. Thank you. :ukraine:
