### ISSUE TITLE
Dart Observatory failing to connect on ios devices running on browserstack with wdio framework

### ISSUE THREAD

**Issue by IOnilearan** [appium/appium#17556]
dart observatory cannot connect meaning the session closes and the automation tests cannot start

## Environment
Appium 2

config.capabilities = [
        platformName: 'iOS',
        automationName: 'flutter',
        observatoryWsUri: 'ws://127.0.0.1:8283/8283=ws'
        device: "device",
       app: "browserstackurl"
]

https://gist.github.com/IOnilearan/288b72b8058f53cde81517bb74a7e484

**Comment by mykola-mokhnach** [comment]
Please report your issue to BS customer support. Also, flutter driver is not support by Appium team. Please reach the driver community.

**Comment by IOnilearan** [comment]
@mykola-mokhnach its appium flutter driver I'm using this ticket was for @KazuCocoa

**Comment by mykola-mokhnach** [comment]
Please create it in the flutter driver's issues tracker then.

**Comment by KazuCocoa** [comment]
Yes, please create a ticket in https://github.com/appium-flutter-driver/appium-flutter-driver

**Comment by giangthao** [comment]
Yes, I still meet the same issue here just only IOS.

**Comment by IOnilearan** [comment]
@giangthao here is the issue for it, it works fine on android just not ios https://github.com/appium-userland/appium-flutter-driver/issues/342
