### ISSUE TITLE
Windows: Discrepancy in API When Launching Application vs. Attaching to Existing Application

### ISSUE THREAD

**Issue by samuelfreiberg** [appium/appium#17551]
## The problem

**Preface**: I am using Appium/WebDriverIO to test a native application, specifically on Windows.

I have two testing scenarios:

1. Having Appium **launch** a Windows application
2. Having Appium **attach** to an existing application

Both are possible with the [Windows Appium Driver ](https://github.com/appium/appium-windows-driver)(the former being most common). Specifically, using the `appTopLevelWindow` capability.

I run the exact same test code in both instances. However, when I attach to an existing application, one of the API's I use doesn't work (500 internal error).

Specifically, the **[touchScroll](https://webdriver.io/docs/api/jsonwp/#touchscroll)**, which is apart of the JSON Wire Protocol. And which the [Windows Application Driver](https://github.com/microsoft/WinAppDriver/blob/master/Docs/SupportedAPIs.md) has full capacity to handle.

**Summarize**: I am running the exact same test code in two different instances. One when I have Appium launch an application, and one when I have Appium attach to an application. The latter causes a `500: internal error` error when using the `touchScroll` API. An API that I had never had problem with before trying to attach to an application.

## Environment

* Appium version (or git revision) that exhibits the issue: "appium": "2.0.0-beta.41"
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): Node v14.20
* Npm or Yarn package manager: Npm v8
* Mobile platform/version under test: Windows
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: Via WebDriverIO

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Please see [LOG](https://gist.github.com/samuelfreiberg/24d55b078c58286f8e537585b6dde50e)

**Comment by KazuCocoa** [comment]
It seems like WinAppDriver itself returned 500 error...? Then, https://github.com/microsoft/WinAppDriver is proper place to report it than here.

```
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/session/9bb0ee9a-9424-4025-9ad9-443f378483ee/touch/scroll[39m
[35m[HTTP][39m [90m{"xoffset":0,"yoffset":-100}[39m
[35m[WindowsDriver@467b (9bb0ee9a)][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m Proxying [POST /session/9bb0ee9a-9424-4025-9ad9-443f378483ee/touch/scroll] to [POST http://127.0.0.1:4724/wd/hub/session/ADD25580-7AD3-486C-A049-F7DEFD5E28CC/touch/scroll] with body: {"xoffset":0,"yoffset":-100}
[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m ==========================================

[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m POST /wd/hub/session/ADD25580-7AD3-486C-A049-F7DEFD5E28CC/touch/scroll HTTP/1.1


[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m Accept: application/json, */*


[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m Connection: keep-alive


[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m Content-Length: 28


[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m Content-Type: application/json; charset=utf-8


[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m Host: 127.0.0.1:4724


[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m User-Agent: appium


[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m 


[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m {"xoffset":0,"yoffset":-100}
[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m HTTP/1.1 500 Internal Error


[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m Content-Length: 133


[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m Content-Type: application/json


[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m 


[debug] [35m[WindowsDriver@467b (9bb0ee9a)][39m {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[35m[WindowsDriver@467b (9bb0ee9a)][39m Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [35m[W3C][39m Matched W3C error code 'unknown error' to UnknownError
[35m[HTTP][39m [37m<-- POST /session/9bb0ee9a-9424-4025-9ad9-443f378483ee/touch/scroll [39m[31m500[39m [90m23 ms - 879[39m
[35m[HTTP][39m [90m[39m
[35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/session/9bb0ee9a-9424-4025-9ad9-443f378483ee/touch/scroll[39m
[35m[HTTP][39m [90m{"xoffset":0,"yoffset":-100}[39m
```

**Comment by mykola-mokhnach** [comment]
The Appium team does not maintain the server part of WinAppDriver nor has access to its sources. Please report your issue to Microsoft.

Closed as third party issue.

**Comment by bwomsm1** [comment]
@samuelfreiberg did you manage to solve the issue?

**Comment by samuelfreiberg** [comment]
@bwomsm1 I have not. I've looked in the logs. The API [POST] calls are the exact same. I'm not sure what is going wrong. My only thought is something with the driver gets spawned differently with Appium when launching the application itself vs. attaching.

I don't think this is a WinAppDriver issue. My assumption is something with the Appium Windows Driver, but I can't put my finger on it and it's driving me crazy.

**Comment by samuelfreiberg** [comment]
@bwomsm1 Are you running into this same issue?

**Comment by bwomsm1** [comment]
@samuelfreiberg yes, I am facing the same issue. it's quite blocking my current work.

**Comment by bwomsm1** [comment]
@samuelfreiberg my scenario is when the appium driver reaches `driver_.find_element` method
