### ISSUE TITLE
[Feature Request] make locator value with new line code consistent

### ISSUE THREAD

**Issue by mwakizaka** [appium/appium#17557]
## The problem
Suppose we have the following page and find an element in the red rectangle (i.e. an element which contains `\n`).
<img width="420" alt="Screen Shot 2022-10-04 at 20 06 08" src="https://user-images.githubusercontent.com/21286384/193804476-48035ae2-81d9-4595-85b6-c47114b35c71.png">

Here's the current behaviour with Appium 2.0.0-beta.44. When finding the element in XPath, the locator value is like `//XCUIElementTypeStaticText[@name='line break line break']`. However, when it comes to ios class chain, the locator value is like ```**/XCUIElementTypeStaticText[`name == "line break\\nline break"`]```

Here's my request. Although it sounds like a breaking change, I appreciate it if it's possible to query the element in XPath with `\n` (i.e. `//XCUIElementTypeStaticText[@name='line break\\nline break']`) to make it less confusing. Maybe https://github.com/appium/appium/issues/17554#issuecomment-1266567681 says the same kind of thing? 

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.44
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe): nodejs 16
* Npm or Yarn package manager: npm
* Mobile platform/version under test: : iOS 15.5 (Xcode 13.4.1)
* Real device or emulator/simulator: simulator (haven't tried with real devices)
* Appium CLI or Appium.app|exe: 

## Code To Reproduce Issue [ Good To Have ]

You can try it out with https://github.com/mwakizaka/webdriveragenttest

**Comment by mykola-mokhnach** [comment]
Yes, @KazuCocoa has created https://github.com/appium/appium/issues/17554 to track the same issue. Please continue the discussion there

**Comment by mykola-mokhnach** [comment]
> Here's my request. Although it sounds like a breaking change, I appreciate it if it's possible to query the element in XPath with \n (i.e. //XCUIElementTypeStaticText[@name='line break\\nline break']) to make it less confusing. Maybe https://github.com/appium/appium/issues/17554#issuecomment-1266567681 says the same kind of thing

I assume it won't be possible to implement it exactly like that because XML attributes don't allow line breaks. Currently the request would look like `//XCUIElementTypeStaticText[@name='line break&#10;line break']`
