### ISSUE TITLE
XCUITest: Cannot update driver Settings

### ISSUE THREAD

**Issue by Mr-Ples** [appium/appium#17566]
## The problem

Updating the driver settings using the `update_settings` method does nothing.

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.44 (driver: xcuitest@4.12.0)
* Last Appium version that did not exhibit the issue (if applicable): never worked
* Node.js: v18.10.0
* Npm: 8.19.2
* Mobile platform/version under test: iOS devices system version 13.x.x to 16.0.2
* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe: CLI but using Python Appium-Python-Client 2.7.0

## Details

Usage of the `update_settings` method is documented here: https://appium.io/docs/en/commands/session/settings/update-settings/

However, in practice these settings don't do anything. e.g. the `screenshotOrientation` setting (found here: https://github.com/appium/appium-xcuitest-driver#settings-api), does not change the orientation of the video:

```
driver_settings = dict(
            screenshotOrientation="portraitUpsideDown"
)

appium_driver.update_settings(driver_settings)
```

Result without using the `screenshotOrientation` setting ([see screenshot](https://s3.eu-central-1.amazonaws.com/cos-dev-attachments/ShareX/notsimon/PrUJcMhzCxkvuJdE.png)).
Result with `screenshotOrientation` setting ([see screenshot](https://s3.eu-central-1.amazonaws.com/cos-dev-attachments/ShareX/notsimon/vrGmPbTvIKVkkIBH.png)).

## Link to Appium logs

Without `screenshotOrientation`: https://gist.github.com/Mr-Ples/afc9e83f5e0560c058f30ba2c8b8f05e
With `screenshotOrientation`: https://gist.github.com/Mr-Ples/63cf6f2dfabb013bdf8c3896c4ef0617

**Comment by mykola-mokhnach** [comment]
> However, in practice these settings don't do anything. e.g. the screenshotOrientation setting (found here: https://github.com/appium/appium-xcuitest-driver#settings-api), does not change the orientation of the video:

Where it is documented this setting should change the video orientation? It only affects screenshots (e.g. /screenshot API)

**Comment by Mr-Ples** [comment]
I see, didn't know about screenshot api
