### ISSUE TITLE
mobile:selectPickerWheelValue return StaleElementReferenceException

### ISSUE THREAD

**Issue by viveksoundar** [appium/appium#17569]
## The problem

 Trying to select a value from picker wheel in iOS by executing the scrip of 

> driver.executeScript("mobile: selectPickerWheelValue", params);
the params are
> {elementId=98210000-0000-0000-0865-000000000000, offset=0.15, order=next}
 
It works on UI but returning stale element reference exception

## Environment

* Appium version (or git revision) that exhibits the issue: v2.0.0-beta.43
* Last Appium version that did not exhibit the issue (if applicable): 1.2
* Desktop OS/version used to run Appium: Mac OS Big Sur 11.6.8
* Node.js version (unless using Appium.app|exe): v18.7.0
* Npm or Yarn package manager: rpm
* Mobile platform/version under test: 15.2
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

https://gist.github.com/viveksoundar/2f82e04ff3433459d8288850454dcc3b

## Code To Reproduce Issue [ Good To Have ]
params.put("order", "next");
params.put("offset", "0.15");
params.put("elementId", ((RemoteWebElement) element).getId());
driver.executeScript("mobile: selectPickerWheelValue", params);
<img width="1440" alt="Screen Shot 2022-10-06 at 1 57 42 PM" src="https://user-images.githubusercontent.com/37587895/194264053-6aa88624-c8c9-47c6-8d97-798e98a4956b.png">

**Comment by viveksoundar** [comment]
@mykola-mokhnach Sorry for the delayed response.

Log for useNativeCacheStrategy false conditon.
https://gist.github.com/viveksoundar/850d26a0f2f1b61cb51cd5506af92308

Log for Bound Elements by index
https://gist.github.com/viveksoundar/7d1850d1851111de22fc1ef354179b68

**Comment by mykola-mokhnach** [comment]
> [HTTP] --> POST /wd/hub/session/1e12d482-b110-4f31-a200-87afc72bd32c/appium/settings
> [HTTP] {"settings":{"boundElementsByIndex":false}}

`false` is the default value. Please set it to true

**Comment by viveksoundar** [comment]
@mykola-mokhnach 
Tried that changing true, still I fece the error. 

https://gist.github.com/viveksoundar/02086645fe3c41039782ce4662270950

**Comment by mykola-mokhnach** [comment]
Please change it `before` locating the corresponding element

**Comment by viveksoundar** [comment]
@mykola-mokhnach Sorry, I tried that too, and facing error. 
https://gist.github.com/viveksoundar/628cf81b7606482aafee63ff79228cac

**Comment by mykola-mokhnach** [comment]
Does it help if both (the capability and the setting) are set to non-default values?

**Comment by mykola-mokhnach** [comment]
Some more context on this issue to make it cleaner:

When we try to reference a previously found element instance in the cache with the actual UI instance XCTest uses so called 'binding'. XCTest provides two binding strategies: 

- https://developer.apple.com/documentation/xctest/xcuielementquery/1500816-allelementsboundbyaccessibilitye?language=objc 
- https://developer.apple.com/documentation/xctest/xcuielementquery/1500945-allelementsboundbyindex?language=objc

We use the first one by default, which tells XCTest to store element accessibility identifier after it is found and verify this identifier has not changed next time we reference this element.

The other strategy tells XCTest to store element index instead and verify the element position (index) in the accessibility tree has not been changed.

xpath is not a native location strategy for XCTest, it has been added by WebDriverAgent. When an element is located by xpath we must store it to the cache, but we cannot keep the actual xpath there as it is not supported by XCTest natively. So instead we just bind found elements using the current binding strategy. 

You have used xpath to locate the picker wheel. Also, after its value has been changed the element's accessibility id did change as well. Let say the previous accessibility id was '25' and now it's '26'. That is why WDA was confused and the exception was thrown. 

I am not going to describe what the above setting and capability do as they are already documented. I hope you have now more visibility over what is happening there.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by viveksoundar** [comment]
@mykola-mokhnach sorry for the long delay, I am still facing the issue, even I upgraded the WebDriverAgent version.
