### ISSUE TITLE
[Appium Windows Driver] An unknown error occurred in the remote end while processing the command, thrown not consistently 

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#17572]
## The problem

From time to time, not consistently I am facing an issue that the error in the title is showing, when my test is calling to `find_element` 

## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0.44 BETA, windows appium driver `2.0.7`
* Last Appium version that did not exhibit the issue (if applicable): Never
* Desktop OS/version used to run Appium: Windows OS
* Node.js version (unless using Appium.app|exe): `v16.17.0`
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Windows appium driver
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Details

desire capabilities
```
app = C:\\AeroScoutEngineManager\\bin\Rte\\EngineManager.exe
win_app_driver_host = http://127.0.0.1:4723
app_arguments = ShellLayout.xml ShellCnf.xml
app_working_dir = c:\\AeroScoutEngineManager\\bin\\Config
```

## Link to Appium logs
[Appium server logs](https://github.com/bwomsm1/AppiumLogs/blob/master/win_app_appium.log)

**Comment by bwomsm1** [comment]
@mykola-mokhnach can you please help with that issue? I might suspect that it has to do with `WinAppDriver` but I am not sure, I am really stuck with that for a long time. 

Thanks!

**Comment by mykola-mokhnach** [comment]
I know that Microsoft does not properly maintain WinAppDriver project. They also never made it open source, so it is impossible to fix/update the server part.

My suggestion for now would be the same as https://github.com/microsoft/WinAppDriver/issues/1610#issuecomment-1044873255

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
