### ISSUE TITLE
Localized Control Type locators not supported in Appium with selenium and python (find by tag name)

### ISSUE THREAD

**Issue by gagemm1** [appium/appium#17577]
## The problem

When attempting to find elements by tag name using appium server, a message appears saying that locator strategy is not supported for this session. This locator strategy works fine using winappdriver.exe directly, leading us to believe this an appium bug. 

## Environment

* Appium version (or git revision) that exhibits the issue: first experienced on 2.7.0, present in 2.2.0 and later
* Appium server GUI version: 1.22.0 (issue persists in appium server alone as well, i.e. no GUI)
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows 10 enterprise 19042.1766
* Node.js version (unless using Appium.app|exe): 12.8.1
* Npm or Yarn package manager: 6.14.13
* Mobile platform/version under test: NA
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: unknown

## Details

varying python clients attempted, multiple server GUI's attempted as well, works fine with other applications and the one we're testing using winappdriver directly (appium is a necessity for our code base)

## Link to Appium logs

python client / appium stacktrace error logs: https://gist.github.com/gagemm1/c324aa50cab672256153c052585f3c06
appium server logs: https://gist.github.com/gagemm1/72857080aae2d1aa516aba4476217af9

## Code To Reproduce Issue [ Good To Have ]

from appium import webdriver
from appium.webdriver.common.appiumby import AppiumBy
import time

desired_caps = {}
desired_caps["app"] = "C:/Windows/System32/notepad.exe"
desired_caps["platformName"] = "Windows"
desired_caps["deviceName"] = "WindowsPC"
driver = webdriver.Remote("http://127.0.0.1:4723/wd/hub",desired_caps)

time.sleep(3)

element = driver.find_element(AppiumBy.TAG_NAME,"Edit")
print(element)

driver.close()

**Comment by KazuCocoa** [comment]
appium-windows-driver 2.1.1 accepts the locator

**Comment by gagemm1** [comment]
I see that PR you already closed adding that 1 liner. Much appreciated! Internet kudos
