### ISSUE TITLE
Error: Intent matches multiple activities

### ISSUE THREAD

**Issue by Madvic90** [appium/appium#17589]
## The problem

Hi all, I am currently researching test automation for the Android TV APPS. I recently started working with Appium. At the moment I'm working on getting it to work to test an Android App in an Nvidia Shield Pro. Unfortunately I keep getting the same error message.

 **An unknown server-side error occurred while processing the command. Original error: Cannot start the 'nl.nep.delta.tv.test' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\imad.essadeq\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 1324121050017 shell am start -W -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 1'; Command output: Error: Intent matches multiple activities; can't stop: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 }**

I managed to get it to work on an Android mobile device, of course with a different APK file.

**The device is seen:**
adb devices
List of devices attached
1324121050017   device

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Desktop OS/version used to run Appium: Windows 10 Enterprise
* Node.js version (unless using Appium.app|exe): v16.17.0
* Npm or Yarn package manager: 8.15.0
* Mobile platform/version under test: 11
* Real device or emulator/simulator: nvidia shield tv pro
* Appium CLI or Appium.app|exe: Appium app

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

<script src="https://gist.github.com/Madvic90/2f1e50143cf18e4a8910ee24f5c8f26d.js"></script>

## Code To Reproduce Issue [ Good To Have ]

 public void Initialize()
        {
            //Android-TV-v0.5.3-56-Delta-Dtest-release.apk
            var appPath = @"C:\Users\imad.essadeq\Downloads\Android-TV-v0.5.3-56-Delta-Dtest-release.apk";
            //Platform, device, Application
            var driverOption = new AppiumOptions();

        
            driverOption.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Android");
            driverOption.AddAdditionalCapability(MobileCapabilityType.DeviceName, "1324121050017");
            driverOption.AddAdditionalCapability(MobileCapabilityType.PlatformVersion, "11");
            driverOption.AddAdditionalCapability(MobileCapabilityType.App, appPath);
            driverOption.AddAdditionalCapability("ignoreHiddenApiPolicyError", "true");
            
            driverOption.AddAdditionalCapability("appPackage", "nl.nep.delta.tv.test");
            driverOption.AddAdditionalCapability("appWaitActivity", "com.stoneroos.deltatv.main.MainActivity");
            driverOption.AddAdditionalCapability("appWaitDuration", "30000");
            driverOption.AddAdditionalCapability("skipServerInstallation", "true");
            driverOption.AddAdditionalCapability("newCommandTimeout", "60000");
            driverOption.AddAdditionalCapability("autoacceptalerts", "true");
            driverOption.AddAdditionalCapability("autoGrantPermissions", "true");
            driverOption.AddAdditionalCapability("clearSystemFiles", "true");

            //driverOption.AddAdditionalCapability("appActivity", "nl.nep.delta.tv.test.MainActivity");
            //appAcitivity: "com.login.mobile.MainActivity",

            driver = new AndroidDriver<AndroidElement>(new Uri("http://localhost:4723/wd/hub"), driverOption);
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromMilliseconds(2000);

 **OpenQA.Selenium.WebDriverException : An unknown server-side error occurred while processing the command. Original error: Cannot start the 'nl.nep.delta.tv.test' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'C:\\Users\\imad.essadeq\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 1324121050017 shell am start -W -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 1'; Command output: Error: Intent matches multiple activities; can't stop: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 }**

**Please guys, could someone  give advice related to this issue? I don't know where to look anymore

Thanks in advance!**

Kind regards!

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

Have you read the tutorial (it has been recently moved: https://github.com/appium/appium-uiautomator2-driver#activity-startup) ?

**Comment by Madvic90** [comment]
> **Please guys, could someone give advice related to this issue? I don't know where to look anymore
> 
> Thanks in advance!**
> 
> Kind regards!



> Please provide the full server log
> 
> Have you read the tutorial (it has been recently moved: https://github.com/appium/appium-uiautomator2-driver#activity-startup) ?

[Raw logs Appium server.txt](https://github.com/appium/appium/files/9745803/Raw.logs.Appium.server.txt)

**Comment by mykola-mokhnach** [comment]
From the logs it looks like uia2 driver is unable to retrieve the main activity name from the application under test. Consider providing appActivity manually to capabilities. Also make sure you could start your app manually with the corresponding `adb shell am` command from a terminal.

**Comment by Madvic90** [comment]
> From the logs it looks like uia2 driver is unable to retrieve the main activity name from the application under test. Consider providing appActivity manually to capabilities. Also make sure you could start your app manually with the corresponding `adb shell am` command from a terminal.

Thank you very much! It seems that adding appActivity did the job!
