### ISSUE TITLE
Calling `(AppiumDriverMgr.driver as TakesScreenshot).getScreenshotAs(OutputType.FILE)` in iOS may result in an exception which closes socket.

### ISSUE THREAD

**Issue by dlanaghen** [appium/appium#17596]
## The problem
Calling `(AppiumDriverMgr.driver as TakesScreenshot).getScreenshotAs(OutputType.FILE)` in iOS may result in an exception.  When that occurs, the socket to the server is closed and further appium testing is not possible.  This is different behavior than Android.  When an exception occurs in Android, if the exception is handled appropriately, the connection remains alive allowing further testing.

## Environment

* Appium version (or git revision) that exhibits the issue: v2.0.0-beta.25
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: macOS 12.6
* Node.js version (unless using Appium.app|exe): v17.3.0
* Npm or Yarn package manager: 8.3.0
* Mobile platform/version under test: iOS 15.6.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: java client 7.6.0

## Details

Obviously, the fact that I am seeing this exception means that there is some kind of issue causing the exception that I can't get to the bottom of.  But this is another problem.

## Link to Appium logs

[gist for appium log](https://gist.github.com/dlanaghen/4e8ddc45b9c34ebeb5c0eb6bff17bf1c)

## Code To Reproduce Issue [ Good To Have ]

(AppiumDriverMgr.driver as TakesScreenshot).getScreenshotAs(OutputType.FILE)

**Comment by mykola-mokhnach** [comment]
- Please make sure the xcuitest driver is at the most recent version
- Please provide device logs and xcodebuild output

**Comment by dlanaghen** [comment]
[here](https://gist.github.com/dlanaghen/dbca033a10514cf8833cde687f1374dd) is the gist of the ios crash log for the device before upgrading the xcuitest driver.

I upgraded the driver.  I was originally nervous about it because it said that breaking changes were possible.

```
bou-c02zh3k3lvdr-mac:/ lanaghendavid$ appium driver update xcuitest --unsafe
✔ Checking if driver 'xcuitest' is updatable
✔ Checking if driver 'xcuitest' needs an update
✔ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver@4.12.1'
✔ Updating driver 'xcuitest' from 3.62.0 to 4.12.1
Update report:
- driver xcuitest updated: 3.62.0 => 4.12.1
```

After upgrading the driver, I no longer get the exception when creating a snapshot.  That is nice.  On the other hand, I think there is some kind of underlying issue that does need to be addressed regarding my original issue.  I believe that the socket is closed when then snapshot throws an exception.  Hopefully that crash log helps in some way.

I always appreciate how quickly you respond!  Thanks.

**Comment by KazuCocoa** [comment]
It seems like the crash happens in `com.apple.testmanagerd`, appium gets a screenshot via `XCTestSession._XCT_requestScreensho` via it.

Could `appium:screenshotQuality` capability as `2` help?

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
