### ISSUE TITLE
Appium Settings app is not running after 5000ms on Real Device with android version 7.0

### ISSUE THREAD

**Issue by gbcbooks** [appium/appium#17595]
## The problem

Appium Settings app is not running after 5000ms on Real Device with android version 7.0

i run my test demo on virtual samsung s6 with android version 7.1.1, it works 
i swith to appium 1.13, run the same script,  Appium Settings app can run properly on the all devices

i try appium 2.0.0-beta.44, have the same issue

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3-4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  Archlinux 
* Node.js version (unless using Appium.app|exe): 18.10.0-1
* Npm or Yarn package manager: NPM
* Mobile platform/version under test: samsung galaxy s6 and versions  7.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: both

**Comment by mykola-mokhnach** [comment]
Please provide the full server log and the device logcat output

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by gbcbooks** [comment]
https://gist.github.com/gbcbooks/fed996ac153556aafc955d9daa9267e0
check logs
