### ISSUE TITLE
65 XcodeBuild error with appium2 version 

### ISSUE THREAD

**Issue by ashwithpoojary98** [appium/appium#17600]
## The problem
XCode build failed with appium2. Working fine in simulator but in real device it's not working. Manually we are able to install WD agent.

## Environment

* Appium version : 2.0.0-beta.44
* Desktop OS/version used to run Appium: MAC OS Monterey(12.6 version)
* Node.js version (unless using Appium.app|exe): 
* Npm or Yarn package manager:
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Real device IPad Air(5th generation)
* Xcode Version: Xcode 14.0.1

[test2.log](https://github.com/appium/appium/files/9764039/test2.log)

**Comment by mykola-mokhnach** [comment]
Please provide xcodebuild log (showXcodeLog capability must be enabled)

**Comment by ashwithpoojary98** [comment]
[appiumlog1.log](https://github.com/appium/appium/files/9765248/appiumlog1.log)
updated

**Comment by mykola-mokhnach** [comment]
> Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the Signing & Capabilities editor.

The error message looks pretty clear to me. Perhaps, codesigning settings were lost after sources upgrade

**Comment by hudson-pierce** [comment]
I encountered something similar and was able to resolve it by adding something like this to my Podfile. Might be worth a shot for you.
```
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["DEVELOPMENT_TEAM"] = "<YOUR_DEVELOPMENT_TEAM>"
         end
    end
  end
end
```

**Comment by KazuCocoa** [comment]
Yea... it is maybe the same as what appium does when it gets capabilities such as `xcodeOrgId`.
https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/lib/xcodebuild.js#L245-L247
https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/lib/utils.js#L147

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
