### ISSUE TITLE
Appium: The application's Info.plist does not contain a valid CFBundleVersion

### ISSUE THREAD

**Issue by kdolecki** [appium/appium#17605]
## The problem

Hi, I have this problem in Appium Inspector:
`Failed to create session. An unknown server-side error occurred while processing the command. Original error: Error running 'install': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22): Failed to install the requested application The application's Info.plist does not contain a valid CFBundleVersion. Ensure your bundle contains a valid CFBundleVersion.`

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.22.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Monterey
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: npm 8.14
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Emulator/Simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

I was trying to follow https://stackoverflow.com/questions/43111501/the-bundles-info-plist-does-not-contain-a-cfbundleversion-key-or-its-value-is-n but neither assigning build version in XCode nor erasing all content and settings from simulator didn't work. 

## Link to Appium logs

(https://gist.github.com/kdolecki/6153536a2ddb22ffb5c7ead8f032cb10#file-gistfile1-txt)

## Code To Reproduce Issue [ Good To Have ]

My capabilites:
```
{
  "platformName": "iOS",
  "appium:platformVersion": "16.0",
  "appium:deviceName": "iPhone 14 Pro",
  "appium:automationName": "XCUITest",
  "appium:autoGrantPermissions": true,
  "appium:dontStopAppOnReset": true,
  "appium:udid": "03DB9F35-43A8-4576-A354-23B3FE6EBD1A",
  "appium:bundleId": "com.m.ios.debug",
  "appium:app": "/Users/kamild/Library/Developer/Xcode/DerivedData/MRing-ebxqddnfsrocmrfxtzcnugswjyru/Build/Products/Debug-iphoneos/test123.app"
}

```

Thanks for any input!

**Comment by mykola-mokhnach** [comment]
Unfortunately there nothing that could be done there on XCUITest driver side. The error is thrown by simctl, which is the tool provided by Apple. consider either fixing your application or reporting an issue to Apple.
