### ISSUE TITLE
Installing 'appium-uiautomator2-driver' after 2.0.0-beta.46 update failed

### ISSUE THREAD

**Issue by Dor-bl** [appium/appium#17614]
## The problem

I was on appium version:2.0.0-beta.45 with appium-uiautomator2-driver .
After I updated appium to .46 and re-installed appium-uiautomator2-driver. I receive the below Error:
`Error: × Encountered an error when installing package: npm command 'install --save-dev appium-uiautomator2-driver --json' failed with code 1.`
## Environment

* Appium version (or git revision) that exhibits the issue: 2.0.0-beta.46
* Last Appium version that did not exhibit the issue (if applicable): 2.0.0-beta.45
* Desktop OS/version used to run Appium: WIN HOME 10
* Node.js version (unless using Appium.app|exe): 16.18.0
* Npm or Yarn package manager:
* Mobile platform/version under test: Android
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe:

## Details

```
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev appium-uiautomator2-driver --json' failed with code 1.

STDOUT:


STDERR:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: appium@1.22.3
npm ERR! node_modules/appium
npm ERR!   appium@"^1.22.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer appium@"^2.0.0-beta.40" from appium-uiautomator2-driver@2.8.0
npm ERR! node_modules/appium-uiautomator2-driver
npm ERR!   dev appium-uiautomator2-driver@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Dor-B\AppData\Local\npm-cache\eresolve-report.txt for a full report.
{
  "error": {
    "code": "ERESOLVE",
    "summary": "unable to resolve dependency tree",
    "detail": "\nWhile resolving: undefined@undefined\nFound: appium@1.22.3\nnode_modules/appium\n  appium@\"^1.22.3\" from the root project\n\nCould not resolve dependency:\npeer appium@\"^2.0.0-beta.40\" from appium-uiautomator2-driver@2.8.0\nnode_modules/appium-uiautomator2-driver\n  dev appium-uiautomator2-driver@\"*\" from the root project\n\nFix the upstream dependency conflict, or retry\nthis command with --force, or --legacy-peer-deps\nto accept an incorrect (and potentially broken) dependency resolution.\n\nSee C:\\Users\\Dor-B\\AppData\\Local\\npm-cache\\eresolve-report.txt for a full report."
  }
}
```

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read!
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/appium and from the `examples` directory, use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in examples, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
> npm ERR! Found: appium@1.22.3

You probably have some leftovers from the old Appium version. Make sure these are removed first

**Comment by Dor-bl** [comment]
Any command I should run in order to do so?

**Comment by Dor-bl** [comment]
After I Uninstalled appium and installed it again , everything is OK

**Comment by MBugraDincaslan** [comment]
![image](https://user-images.githubusercontent.com/113547552/205892920-52c03b5a-e2b1-4493-8797-cd97fffb2e4b.png)
Firstly install this release
https://nodejs.org/dist/latest-v14.x/ 
node-v14.21.1.pkg for mac
secondly open terminal and write code
"appium driver install uıautomater2"
"appium driver install xcuitest"

at least
![image](https://user-images.githubusercontent.com/113547552/205894318-1881e6f8-f1ca-4d42-a96a-d9cb92eaf3ac.png)
I installed this release and I will have been used this released. So I fixed ...

**Comment by Ybrault** [comment]
Find the solution, I perform the following steps :

`npm -g install npm@6`
`appium driver install xcuitest`

And then, it works !

**Comment by jlipps** [comment]
@boneskull any thoughts on this? seems like npm 8 wasn't working for this user?

**Comment by boneskull** [comment]
Well, they have Appium 1 installed, so it conflicts with Appium 2, which is the default behavior of npm v7+

**Comment by boneskull** [comment]
The proper fix would be to remove Appium 1, probably.

**Comment by Ybrault** [comment]
> 

What I tried to do and seemed to uninstall completely, I was with npm 9.x and after downgrading to npm 6.x it worked

**Comment by Ybrault** [comment]
> The proper fix would be to remove Appium 1, probably.

What I tried to do and seemed to uninstall completely, I was with npm 9.x and after downgrading to npm 6.x it worked

**Comment by AmbikaMurugesan** [comment]
Hi @boneskull 

I'm also facing the same issue when i tried to install **uiautomator2** driver.

**Configurations:**
Node : v18.12.1
NPM : 8.19.2
appium version: 2.0.0-beta.48
Java version : jdk-19

Below is the error which Im getting.

× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev appium-uiautomator2-driver --json' failed with code null.

STDOUT:


STDERR:



I also tried by downgrading npm to 6.x version , still it didn't work. Kindly help here

**Comment by boneskull** [comment]
uninstall appium 1

**Comment by AmbikaMurugesan** [comment]
Yes I did uninstalled appium1 by running **npm uninstall -g appium@1.22.3** command, still facing the same issue.

 Is there any other place that I need to delete manually ?

**Comment by wuzhenni0316** [comment]
Thanks @Ybrault , it works from my side as well after I downgrading npm to 6.x.
<img width="938" alt="image" src="https://user-images.githubusercontent.com/44227267/212867388-78a319db-3e20-4833-a1be-df1db2047655.png">

**Comment by rushian** [comment]
> > npm ERR! Found: appium@1.22.3
> 
> You probably have some leftovers from the old Appium version. Make sure these are removed first

Here I delete the content in folder C:\Users\MY_USER\.appium

**Comment by nethira** [comment]
> Yes I did uninstalled appium1 by running **npm uninstall -g appium@1.22.3** command, still facing the same issue.
> 
> Is there any other place that I need to delete manually ?



> Hi @boneskull
> 
> I'm also facing the same issue when i tried to install **uiautomator2** driver.
> 
> **Configurations:** Node : v18.12.1 NPM : 8.19.2 appium version: 2.0.0-beta.48 Java version : jdk-19
> 
> Below is the error which Im getting.
> 
> × Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver' Error: × Encountered an error when installing package: npm command 'install --save-dev appium-uiautomator2-driver --json' failed with code null.
> 
> STDOUT:
> 
> STDERR:
> 
> I also tried by downgrading npm to 6.x version , still it didn't work. Kindly help here

Did your issue got resolved??

**Comment by Ajayush96** [comment]
Hi Guy's,
Im facing issue during installing uiautomator2 driver , earlier it was working fine , but once i have reinstalled appium then not able to install driver

C:\Users\Ashish Jha>appium driver install uiautomator2
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev appium-uiautomator2-driver --json' failed with code 1.

STDOUT:
{
  "error": {
    "code": "ERESOLVE",
    "summary": "unable to resolve dependency tree",
    "detail": "\nWhile resolving: undefined@undefined\nFound: appium@1.22.3\nnode_modules/appium\n  appium@\"^1.22.3\" from the root project\n\nCould not resolve dependency:\npeer appium@\"^2.0.0-beta.40\" from appium-uiautomator2-driver@2.15.0\nnode_modules/appium-uiautomator2-driver\n  dev appium-uiautomator2-driver@\"*\" from the root project\n\nFix the upstream dependency conflict, or retry\nthis command with --force or --legacy-peer-deps\nto accept an incorrect (and potentially broken) dependency resolution."
  }
}

STDERR:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: appium@1.22.3
npm ERR! node_modules/appium
npm ERR!   appium@"^1.22.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer appium@"^2.0.0-beta.40" from appium-uiautomator2-driver@2.15.0
npm ERR! node_modules/appium-uiautomator2-driver
npm ERR!   dev appium-uiautomator2-driver@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\Ashish Jha\AppData\Local\npm-cache\_logs\2023-04-16T17_00_54_879Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ashish Jha\AppData\Local\npm-cache\_logs\2023-04-16T17_00_54_879Z-debug-0.log

**Comment by Ajayush96** [comment]
> After I Uninstalled appium and installed it again , everything is OK

how can you uninstall the appium completely?

**Comment by rushian** [comment]
> > After I Uninstalled appium and installed it again , everything is OK
> 
> how can you uninstall the appium completely?

First I uninstalled the previous version, with the command
npm uninstall -g appium
then I deleted the content from the directory C:\Users\YOUR_USERNAME\.appium

**Comment by pallavichandrashekarjetty** [comment]
![Appium2](https://github.com/appium/appium/assets/79142459/cdeb1aa5-1a59-495b-bd76-a834d61f6681)
