### ISSUE TITLE
Appium Settings app is not running after 5000ms on Real Device with android version 7.0

### ISSUE THREAD

**Issue by gbcbooks** [appium/appium#17620]
## The problem

Appium Settings app is not running after 5000ms on Real Device with android version 7.0

i run my test demo on virtual samsung s6 with android version 7.1.1, it works
i swith to appium 1.13, run the same script, Appium Settings app can run properly on the all devices

i try appium 2.0.0-beta.44, have the same issue

## Environment

* Appium version (or git revision) that exhibits the issue:1.22.3-4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Archlinux
* Node.js version (unless using Appium.app|exe):18.10.0-1
* Npm or Yarn package manager:NPM
* Mobile platform/version under test:samsung galaxy s6 and versions 7.0
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:both

## Link to Appium logs

https://gist.github.com/gbcbooks/fed996ac153556aafc955d9daa9267e0

Sorry to re open a new issue, i did not notice the old ticket has a reply.

**Comment by mykola-mokhnach** [comment]
The logcat output is still missing

Which output do you get if settings helper is started manually via adb?

>  adb -P 5037 -s 02157df2a809c10c shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
>  adb -P 5037 -s 02157df2a809c10c shell 'pgrep ^appium\\.settings$ || pgrep ^io\\.appium\\.setti$'

**Comment by gbcbooks** [comment]
[user1@archlinux ~]$ adb -P 5037 -s 02157df2a809c10c shell am start -n io.appium.settings/.Settings -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=io.appium.settings/.Settings launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }
[user1@archlinux ~]$ adb -P 5037 -s 02157df2a809c10c shell 'pgrep ^appium\.settings$ || pgrep ^io\.appium\.setti$'

**Comment by gbcbooks** [comment]
looks like  this is the only output i got, am i giving the correct information?

**Comment by mykola-mokhnach** [comment]
Sorry, I cannot help much without the logcat. It is necessary to know if the helper starts properly

**Comment by gbcbooks** [comment]
sorry , i am knida new , the cmdline you give out can retrivewe logcat ?

**Comment by mykola-mokhnach** [comment]
Not really. The command line is to verify the utility startup for possible errors.

Feel free to use Google about how to fetch logcat from the device.

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot find any useful traces in the attached logs. Try to use another device for testing as a possible workaround.

**Comment by gbcbooks** [comment]
thks,  then , i met another issue , i use appium 1.13 to run script on Samsung S6,  the APP stuck at photo selecting , it can not collect element from device. 
i run the same script on Appium 1.13 withe virtual device , it works fine 

logcat : https://gist.github.com/gbcbooks/740890fa2a7efa64d0d5f4cd043e80f4
appium server log : https://gist.github.com/gbcbooks/79817e2aed888379dc3ca915e53edda3

**Comment by gbcbooks** [comment]
i flash a original ROM of samsung ,  this issue done
