### ISSUE TITLE
Error: Cannot find module '@appium/types' after installed Appium2

### ISSUE THREAD

**Issue by DeliaLing** [appium/appium#17624]
Not able to use appium command, getting Error: Cannot find module '@appium/types' 
## Environment

* Appium version 2.0.0-beta.44
* Desktop OS/version : Mac 12.6
* Node.js version : 16.5
* Npm or Yarn package manager: 8.19.2

## Details
1, npm install -g appium@2.0.0-beta.44
2, run appium -v (OR appium plugin install execute-driver)

Getting below issue:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/115450980/196306768-af4d4545-ac61-4fce-bed4-76f3a004edb8.png">

**Comment by mykola-mokhnach** [comment]
Try to delete all the leftovers and installed the moist recent server version by running `npm i -g appium@next`

**Comment by DeliaLing** [comment]
Thanks @mykola-mokhnach . It is working now. I would like to build the WDA file, is it the correct path to open the file? 
<img width="448" alt="image" src="https://user-images.githubusercontent.com/115450980/196458432-161ca812-a092-4a4b-aecc-f882a31f2c62.png">

**Comment by mykola-mokhnach** [comment]
Not sure which paths you need. The way to find WDA sources root is documented at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md#finding-webdriveragent-project-root-on-the-local-file-system

Closed as fixed
