### ISSUE TITLE
android(uiAutomator2): adds ability to set webview name in which driver switch using autoWebview option

### ISSUE THREAD

**Issue by DudaGod** [appium/appium#17639]
## The problem

In app which I tested webview context has the name different from default - `WEBVIEW_${appPackage}`, which is defined here - https://github.com/appium/appium-android-driver/blob/master/lib/commands/context.js#L153. Can we add new option `webviewName` (for example) which will override default value?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.22.3
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): 12.18.1
* Npm or Yarn package manager: 6.14.5
* Mobile platform/version under test: Android 11
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: cli

**Comment by mykola-mokhnach** [comment]
I'm not quite sure why the default web view name is hardcoded. I would expect it to be retrieved as the first non-native item from web views list. 

Although having a capability like `autoWebViewName` would make sense anyway. Feel free to create a PR.

**Comment by mykola-mokhnach** [comment]
Fixed as resolved. Thanks for your help @DudaGod
