### ISSUE TITLE
[Appium and windows plugin] appium raises a timeout error when trying to start win OS test 

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#17635]
## The problem
I am trying to start WinOS test, but getting a timeout error when appium client is trying to connect to appium server:
```
{'app': 'C:\\Arial\\Arial.exe', 'win_app_driver_host': 'http://127.0.0.1:4723', 'app_working_dir': 'C:\\Arial'}
WinAppDriverWrapper: test failed connecting to appium server after 0 tries
Message: An unknown server-side error occurred while processing the command. Original error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually
    at getResponseForW3CError (C:\Users\qahw\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:956:9)
    at asyncHandler (C:\Users\qahw\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:435:35)
```

According to that error:
**Message: An unknown server-side error occurred while processing the command. Original error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually**
When I am starting `WinAppDriver.exe` manually it does starting successfully.
The `WinAppDriver` version which I am using is [1.2.99](https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.99)

I am running the appium server from CLI as an administrator. 

**Versions** 
Appium version: `beta-2.0.0.45` (latest)
Python, Appium-Python-Client: `2.7.1` (latest)
WinAppDriver: `1.2.99` (latest)
Windows OS: `Windows 10`
appium-windows-driver: `2.1.1` (latest)

## Environment

* Appium version (or git revision) that exhibits the issue: Beta 2.0.0.45
* Last Appium version that did not exhibit the issue (if applicable): was working on other OS 
* Desktop OS/version used to run Appium: Windows OS 
* Node.js version (unless using Appium.app|exe): 16
* Npm or Yarn package manager: npm
* Mobile platform/version under test: Windows platform
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
https://github.com/bwomsm1/AppiumLogs/blob/master/appium_win.log

Details:
My appium windows driver is installed with version `2.1.1`

**Comment by bwomsm1** [comment]
@mykola-mokhnach can you please advise with that issue? 

Thanks!

**Comment by mykola-mokhnach** [comment]
I would try to manually replace winappsriver with an older/stable version. I don't think there is anything on the appium driver side that could be done to address the issue.

**Comment by bwomsm1** [comment]
Amazing @mykola-mokhnach, that solve my problem, it seems that there is an issue with the PreRelease version `1.2.99`, I just installed `1.2.1` and the problem solved. 

Closing the ticket. 

Thanks!
