### ISSUE TITLE
Not able to find all invisible elements using the ID locator Strategy.

### ISSUE THREAD

**Issue by vishnuverma2908** [appium/appium#17646]
## The problem
I have set the desired capability of loading the invisible elements while using UiAutomator2 Automation framework for Native App Automation with Appium Tool. I am not getting all the invisible elements using ID locator Strategy.

cap.setCapability("allowInvisibleElements", true); 

## Environment
* OS : Windows 10
* Appium version: 1.22.3
* Node.js version : v16.17.0
* Android Version: 11
* Real device OPPO

## Code To Reproduce Issue [ Good To Have ]

List<MobileElement> remarkElement=driver.findElements(MobileBy.id("ID"));
remarkElements.size();
Here suppose 4 elements are available in the Dom with the above specified ID (including Displayed attribute true and false value) but I am not getting 4 Elements.

**Comment by mykola-mokhnach** [comment]
Element location is controlled by Google's UiAutomator framework, so there is not much we could do there. You could also check https://github.com/appium/appium-uiautomator2-driver#elements-cannot-be-found

**Comment by hemche** [comment]
You need to change it through the `Settings` api. I had the same issue and updating like below worked.
`driver.setSetting('allowInvisibleElements', true);
`

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by vishnuverma2908** [comment]
> driver.setSetting('allowInvisibleElements', true);

Giving compilation Error

**Comment by vishnuverma2908** [comment]
> Closed as third party issue
![image](https://user-images.githubusercontent.com/116249567/198935037-54112ee7-8e14-4fe6-8608-945fd6dd9014.png)
Getting the Message while raising the same issue on appium-UiAutomtor2-driver project. Please Guide me What to do to get this issue resolved ?
My Appium Version: 1.22.3
Appium Java Library: 7.6.0
Node version: 16.17.0

**Comment by jlipps** [comment]
if you think this issue should be reopened then please provide more information here.
