### ISSUE TITLE
How to find in the doc how the iOS zip app as been prepared

### ISSUE THREAD

**Issue by kopax-polyconseil** [appium/appium#17649]
## The problem

I want to run a basic test such as the one in javascript-webdriverio.

I was able to do it on android using an apk downloaded from appcenter, but I am unable to do the same for iOS as it seems you proivde a zip file which was created by you and not documented

## Environment

* Appium version (or git revision) that exhibits the issue: 1.x
* Last Appium version that did not exhibit the issue (if applicable): 1.x
* Desktop OS/version used to run Appium: macOS
* Node.js version (unless using Appium.app|exe): 16
* Npm or Yarn package manager: yarn
* Mobile platform/version under test: 
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

I would like to know how to produce an app for Appium

**Comment by jlipps** [comment]
Here are the docs for the ios driver: https://github.com/appium/appium-xcuitest-driver

Basically you must have the source code for the iOS app that you want to test. You need to build it using Xcode. for the appropriate target. You should make sure it installs and runs on your device before you try to automate it with Appium. If you can't run it, Appium can't automate it. It needs to be a debug build.

That's it!

**Comment by kopax-polyconseil** [comment]
> Basically you must have the source code for the iOS app that you want to test.

The source code of the iOS app https://github.com/pass-culture/pass-culture-app-native/

>  You need to build it using Xcode.

We have an IPA distributed on appcenter for our testing and staging environment, would this work ?
Why do you have a zip ? What do you mean by debug build ? We expect to test a production build, why would we use a non final version for e2e testing ?

> Here are the docs for the ios driver: https://github.com/appium/appium-xcuitest-driver

Thanks I will have a check a deep look today on the provided like !

**Comment by jlipps** [comment]
> We have an IPA distributed on appcenter for our testing and staging environment, would this work ?

Probably not

> We expect to test a production build, why would we use a non final version for e2e testing ?

Ask Apple. Their test tools don't allow running on a release build.

> Make sure the correct deployment target has been selected for its compilation in Xcode

Make sure you build your  app for the simulator. The result should be a debug .app.zip, not an .ipa.
