### ISSUE TITLE
Selenium 4.3+ Actions not supported by Appium

### ISSUE THREAD

**Issue by ryanferns1995** [appium/appium#17656]
## The problem

I am currently unable to use Selenium Actions class when I upgrade to any selenium versions from 4.3.0 and above. I receive the error `org.openqa.selenium.UnsupportedCommandException: actions` using the Legacy Protocol. 
I receive the error `FAIL: Exception during test: The element identified by "5004" is either not resent or it has expired from the internal cache. Try to find it again` when using the W3C protocol.

## Environment

* Appium version (or git revision) that exhibits the issue: All appium versions but I'm currently using 1.21.0 over Browserstack
* Last Appium version that did not exhibit the issue (if applicable): Does not occur if Selenium is downgraded below 4.3.0
* Desktop OS/version used to run Appium: Browserstack
* Node.js version (unless using Appium.app|exe): N/A
* Npm or Yarn package manager: N/A
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPhone XS
* Appium CLI or Appium.app|exe: Browserstack

## Details

Using Selenium's Remote Webdriver, we're executing test cases over iOS. Upgrading our selenium repository to 4.3.0+ causes errors with executing selenium's actions class. as mentioned above. Is this since appium does not yet support selenium 4.3.0 ActionsClass?

## Code To Reproduce Issue [ Good To Have ]

Just using a simple actions class method, should reproduce the issue:
`actions.moveToElement(.WebElement, xOffset, yOffset).perform();`

**Comment by mykola-mokhnach** [comment]
No actions (neither old jwp implementation nor the new w3c one) were never supported in iOS web context.

**Comment by Cadigal-displayr** [comment]
> No actions (neither old jwp implementation nor the new w3c one) were ever supported in iOS web context.

Can you suggest a workaround that we can use in place of `actions.moveToElement(webElement, xOffset, yOffset).perform();`?

I have found https://github.com/appium/appium/issues/16185#issuecomment-983123972 which suggests that something similar to the following code will give us the desired behaviour, can you please confirm this?
```java
// Old
new Actions(driver).moveToElement(webElement, xOffset, yOffset).perform();
// New
JavascriptExecutor js = (JavascriptExecutor) driver;
Map<String, Object> params = new HashMap<>();
params.put("element", ((RemoteWebElement) webElement).getId());
params.put("x", xOffset);
params.put("y", yOffset);
js.executeScript("mobile: tap", params);
```

**Comment by mykola-mokhnach** [comment]
A workaround would be to syntesize a custom javascript snippet. Actions are only supported in native context.

**Comment by jlipps** [comment]
Yeah this is unfortunate. I wonder if the updated atoms have actions support? If so that could be another reason to try to sort out the atoms mess.

**Comment by jlipps** [comment]
The updated atoms don't have actions support. I think all we can recommend right now is using actions in the native mode. You would get the position of the element in the webview, translate that to the position of the element on screen, and apply the offset.
