### ISSUE TITLE
Getting [Fatal Error: Could not parse version to test against: '0’ ] ERROR on trying to run appium after installing the webOS driver through Appium 2 " appium driver install --source=npm appium-webos-driver "

### ISSUE THREAD

**Issue by rajasubudhi1988** [appium/appium#17667]
## The problem

Getting [Fatal Error: Could not parse version to test against: '0’ ] ERROR on trying to run appium after installing the webOS driver through Appium 2 " appium driver install --source=npm appium-webos-driver "

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 2 Installed vis (npm install -g appium@next)
* Last Appium version that did not exhibit the issue (if applicable): same Appium 2
* Desktop OS/version used to run Appium: Mac pro 12.6
* Node.js version (unless using Appium.app|exe): v18.11.0
* Npm or Yarn package manager: 8.19.2 
* Mobile platform/version under test: All android and IOS mobiles
* Real device or emulator/simulator: Real device LG TV 
* Appium CLI or Appium.app|exe: CI

## Details

I installed Appium 2.0 and tried to install the drivers as below to automate the connected devices.

xcuitest@4.12.1 [installed (NPM)] [Up to date]
tizentv@0.7.1 [installed (NPM)] [Up to date]
roku@0.8.3 [installed (NPM)] [Up to date]
uiautomator2@2.9.0 [installed (NPM)] [Up to date]
espresso@2.13.0 [installed (NPM)] [Up to date]
mac2@1.4.3 [installed (NPM)] [Up to date]
windows@2.1.1 [installed (NPM)] [Up to date]
gecko@1.1.3 [installed (NPM)] [Up to date]
safari@3.2.3 [installed (NPM)] [Up to date]
**But after trying to install the driver for LG webOS . the install was successful D. But afterwards Appium is not working and shows the below error.

Fatal Error: Could not parse version to test against: '0’**
at NPM.getLatestSafeUpgradeFromVersions (/opt/homebrew/lib/node_modules/appium/node_modules/[@appium](https://discuss.appium.io/u/appium)/support/lib/npm.js:166:15)
at NPM.getLatestSafeUpgradeVersion (/opt/homebrew/lib/node_modules/appium/node_modules/[@appium](https://discuss.appium.io/u/appium)/support/lib/npm.js:129:19)
at DriverCommand.checkForExtensionUpdate (/opt/homebrew/lib/node_modules/appium/lib/cli/extension-command.js:581:22)
at /opt/homebrew/lib/node_modules/appium/lib/cli/extension-command.js:131:25
at spinWith (/opt/homebrew/lib/node_modules/appium/lib/cli/utils.js:41:12)
at DriverCommand.list (/opt/homebrew/lib/node_modules/appium/lib/cli/extension-command.js:121:5)
at DriverConfig.getListData (/opt/homebrew/lib/node_modules/appium/lib/extension/extension-config.js:244:22)
at DriverConfig.getGenericConfigWarnings (/opt/homebrew/lib/node_modules/appium/lib/extension/extension-config.js:315:24)

**Please let me know how to resolve this fatal error.Being blocked due to this.

I tried all possible ways to resolve the same like uninstall the node from homebrew. Uninstal/Install homebrew and installing node/npm again.But no luck.**

Note : From terminal i am trying to launch Appium and all the drivers are installed from cli only.

## Link to Appium logs
None as appium is ony not launching on entering appium comman in cli

## Code To Reproduce Issue 
https://github.com/sharkyStudy/appium-webos-driver
git@github.com:sharkyStudy/appium-webos-driver.git
https://github.com/sharkyStudy/appium-webos-driver.git
gh repo clone sharkyStudy/appium-webos-driver

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/pull/17666 should relax version checks, so no error will be thrown

**Comment by mykola-mokhnach** [comment]
The patch has been released
