### ISSUE TITLE
[Bug]: io.appium.uiautomator2.server crashing with message Permission related app op changed

### ISSUE THREAD

**Issue by keyur2maru** [appium/appium#17679]
## The problem
The problem I am experiencing is when I am running one Appium server and launching multiple sessions on it with real/emulated devices for running tests using the Robot framework, most of the time a couple of devices fail the test while 
others pass it. 

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v2.0.0-beta.46
* Desktop OS/version used to run Appium: Ubuntu 22.04 
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe: CLI

## Details

I am using an Appium single server instance to connect multiple devices with their sessions to run tests on all connected devices. Sometimes, I randomly see it passes on all devices without errors, but the rest of the time, it fails with the following error message:
Test fail message from Robot:
```
WebDriverException: Message: 'GET /wd/hub/session/bfdcd28c-ff2e-4607-a60b-102166128fe5/source' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Stacktrace:
InvalidContextError: 'GET /wd/hub/session/bfdcd28c-ff2e-4607-a60b-102166128fe5/source' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
```
Appium server message:
```
[debug] [35m[AndroidUiautomator2Driver@5249 (c46870c6)][39m Responding to client with driver.findElements() result: []
[35m[HTTP][39m [37m<-- POST /wd/hub/session/c46870c6-9b21-4c77-9793-84041e7f399d/elements [39m[32m200[39m [90m12 ms - 12[39m
[35m[HTTP][39m [90m[39m
[debug] [35m[Instrumentation][39m INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[debug] [35m[Instrumentation][39m INSTRUMENTATION_CODE: 0
[35m[AndroidUiautomator2Driver@8e0d (bfdcd28c)][39m socket hang up
[debug] [35m[AndroidUiautomator2Driver@8e0d (bfdcd28c)][39m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
[debug] [35m[AndroidUiautomator2Driver@8e0d (bfdcd28c)][39m     at UIA2Proxy.command (/home/kd/.nvm/versions/node/v18.10.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:342:13)
[debug] [35m[AndroidUiautomator2Driver@8e0d (bfdcd28c)][39m     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [35m[AndroidUiautomator2Driver@8e0d (bfdcd28c)][39m     at AndroidUiautomator2Driver.helpers.doFindElementOrEls (/home/kd/.appium/node_modules/appium-uiautomator2-driver/lib/commands/find.js:30:10)
[debug] [35m[AndroidUiautomator2Driver@8e0d (bfdcd28c)][39m     at doFind (/home/kd/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:36:17)
[debug] [35m[AndroidUiautomator2Driver@8e0d (bfdcd28c)][39m     at wrappedCondFn (/home/kd/.nvm/versions/node/v18.10.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/timeout.js:138:16)
[debug] [35m[AndroidUiautomator2Driver@8e0d (bfdcd28c)][39m     at spin (/home/kd/.nvm/versions/node/v18.10.0/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:138:20)
[debug] [35m[AndroidUiautomator2Driver@8e0d (bfdcd28c)][39m     at waitForCondition (/home/kd/.nvm/versions/node/v18.10.0/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:155:10)
[debug] [35m[AndroidUiautomator2Driver@8e0d (bfdcd28c)][39m     at AndroidUiautomator2Driver.implicitWaitForCondition (/home/kd/.nvm/versions/node/v18.10.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/timeout.js:140:14)
[debug] [35m[AndroidUiautomator2Driver@8e0d (bfdcd28c)][39m     at AndroidUiautomator2Driver.findElOrEls (/home/kd/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:60:5)
[debug] [35m[AndroidUiautomator2Driver@8e0d (bfdcd28c)][39m     at AndroidUiautomator2Driver.findElOrElsWithProcessing (/home/kd/.nvm/versions/node/v18.10.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.js:80:16)
[debug] [35m[AndroidUiautomator2Driver@8e0d (bfdcd28c)][39m     at AndroidUiautomator2Driver.findElements (/home/kd/.nvm/versions/node/v18.10.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.js:29:14)
[35m[HTTP][39m [37m<-- POST /wd/hub/session/bfdcd28c-ff2e-4607-a60b-102166128fe5/elements [39m[31m500[39m [90m803 ms - 2063[39m
```
Logcat
```
10-29 15:48:49.133  1508  2131 I MediaProvider: Invalidating LocalCallingIdentity cache for package io.appium.uiautomator2.server. Reason: op android:read_external_storage
10-29 15:48:49.134  1508  1542 I MediaProvider: Invalidating LocalCallingIdentity cache for package io.appium.uiautomator2.server. Reason: op android:read_external_storage
10-29 15:48:49.134   548  3343 I ActivityManager: Killing 2714:io.appium.uiautomator2.server/u0a131 (adj 0): Permission related app op changed
10-29 15:48:49.136   548  3343 W ActivityManager: Crash of app io.appium.uiautomator2.server running instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner}
10-29 15:48:49.136   548  3343 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10131 user=0: finished inst

```
I have also tried providing unique systemPort while launching new sessions but that also didn't help. All the logs that I have shared are captured while using the relaxed-caps plugin. I have also tried without it, but that didn't seem to help.

## Link to Appium logs
Server logs
https://gist.github.com/keyur2maru/aa67115687fb16b06e20a104994d00d2

Logcat from all the 5 devices that ran the same out of which 2 failures and 3 passed the tests without crashing appium

Device 1 -> PASS
https://gist.github.com/keyur2maru/2fdb5664ce56e734d7e1398bee7d3e90

DEVICE 2 -> FAIL
https://gist.github.com/keyur2maru/19808715b0f3f0e75e931e705532d30f

DEVICE 3 -> PASS
https://gist.github.com/keyur2maru/912bc1d9fef4a90633b3df7ce5b61fa3

DEVICE 4 -> PASS
https://gist.github.com/keyur2maru/230aa68489dbe3a861c4fe13115e0e9d

Device 5 -> FAIL
https://gist.github.com/keyur2maru/9c0c8fa14801976c03ad92703f9ee784

**Comment by mykola-mokhnach** [comment]
Please use the most recent driver version, which is available as part of Appium 2. We do not maintain Appium 1 anymore

**Comment by keyur2maru** [comment]
@mykola-mokhnach I have tried using Appium v2.0.0-beta.46 as well, but I seemed to get the same issue. 
I have updated the issue with newer logs from the device's logcat and server logs with Appium v2.0.0-beta.46.

**Comment by mykola-mokhnach** [comment]
I've only found https://stackoverflow.com/questions/32307786/application-is-getting-killed-after-enable-disable-permissions-from-settings-on so far. Not sure though why this permission gets changed or what could be done to modify that behaviour

**Comment by KazuCocoa** [comment]
Also https://stackoverflow.com/questions/33488589/android-marshmallow-dynamic-permission-change-kills-all-application-processes ..? I haven't seen such reported behavior, so I also have no good idea about the cause...

**Comment by keyur2maru** [comment]
@KazuCocoa @mykola-mokhnach After removing android.permission.WRITE_EXTERNAL_STORAGE from appium-uiautomator2-server and android.permission.READ_EXTERNAL_STORAGE from io.appium.settings, my tests are no longer failing. I am unsure if these permissions are required for Appium to function correctly, but I haven't faced any other issues.

**Comment by KazuCocoa** [comment]
Latest io.appium.settings has a feature which needs storage scan, so maybe the permission is necessary.
https://github.com/appium/appium-adb/pull/624 makes sure the process is running before getting broadcast, so I guess the settings app can work with the latest UIA2.

**Comment by KazuCocoa** [comment]
UIA2 2.10.1 (available in Appium v2) has the update. Please try it out
