### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by technigirl** [appium/appium#17671]
## The problem

Hello, I am trying to run Appium Desktop to launch Safari on an iPhone simulator.  The simulator boots, but Safari fails to launch.  I see the following error in the Appium log:

Error running 'spawn': An error was encountered processing the command (domain=com.apple.CoreSimulator.LaunchdSimError, code=111):
Process spawn via launchd failed.
Underlying error (domain=SimXPCErrorDomain, code=111):
	Invalid or missing Program/ProgramArguments

## Environment

* Appium version (or git revision) that exhibits the issue:  1.22.3
* Last Appium version that did not exhibit the issue (if applicable):  N/A
* Desktop OS/version used to run Appium:  MacOS 12.5 (Monterrey)
* Node.js version (unless using Appium.app|exe):  N/A
* Npm or Yarn package manager: npm
* Mobile platform/version under test:    iOS 15.4/iPhone 13 
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium. app v1.22.3 
* xcode: 13.3.1

## Link to Appium logs

https://gist.github.com/technigirl/2eac533c31284da417a4eb1399c9aba6

## Code To Reproduce Issue [ Good To Have ]

No special code since this is failing on launch.

**Comment by mykola-mokhnach** [comment]
- Appium 1 is not supported anymore. Please use xcuitest driver supplied with Appium 2
- I see multiple tries to start a session in the log without properly terminating it. Make sure a session is only started once.

**Comment by technigirl** [comment]
@mykola-mokhnach thank you for the guidance.   It seems [Appium Desktop ](https://github.com/appium/appium-desktop/releases) is still on Appium 1, so that's why I have that. Perhaps it is no longer maintained.  I will try with Appium 2 and see if it will work with that.

**Comment by mykola-mokhnach** [comment]
Appium Desktop has been replaced with https://github.com/appium/appium-inspector

**Comment by technigirl** [comment]
@mykola-mokhnach Thank you, I upgraded to v2.0 and used appium-inspector, and it works for me now.  :).   Thank you for your help!

**Comment by tungntuit** [comment]
thanks @technigirl , you save my day :D
