### ISSUE TITLE
Unable to click buttons using xpath locators in salesforce community sites for iOS devices (Selenium C#)

### ISSUE THREAD

**Issue by Bhanureddy2204** [appium/appium#17689]
Unable to click buttons using xpath locators in salesforce community sites for iOS devices (Automation using Selenium C#). The same xpath locators are working for Android devices.

- Appium driver(s) and their version(s): 4.3.2
- Platform and version under test:  all iOS versions mostly from 14 to above
- Real device or emulator/simulator: Both Real device and Simulator

**Comment by KazuCocoa** [comment]
Could you fill in the template and share the full appium log as GIST?

**Comment by mykola-mokhnach** [comment]
Closed as incomplete
