### ISSUE TITLE
bug: find by class name is returning all elements when class is not found

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#17690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Calling AppiumDriver.findElements() with args: ["class name","XCUIElementTypeApplicationasdasdasdasd","7a4c674c-33cb-4541-b41f-dc3d2a4066dc"] is returning all current elements instead of an empty set / not found message.

I will note in case its relevant, this behavior was discovered when changing our tests from using @FindAll / @FindBy annotation to @iOSXCUITFindBy (and android) versions while migration from v7 to v8 java client. That change was necessitated due to the breaking of By.className from Selenium 4 as noted in the migration document (great document by the way very helpful).

### Expected Behavior

Responding to client with driver.findElements() result: []

### Minimal Reproducible Example

driver.findElements(AppiumBy.className("asldnajsdnasda""));

### Environment

- Operating system: Mac OSX 12.6
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.46
  - Node.js version (output of `node --version`): v16.17.0
  - `npm` version (output of `npm --version`): 8.15.0
  - Last `appium` version which did _not_ exhibit the problem: Appium 1.22.3 I guess?
- Appium driver(s) and their version(s): xcuitest@4.12.1, uiautomator2@2.8.0, espresso@2.11.0
- Appium plugin(s) and their version(s): N/A
- Platform and version under test: iOS 16.0
- Real device or emulator/simulator: iOS simulator.... will also check if this is happening on real device

### Futher Information

[AppiumServerLogs.txt](https://github.com/appium/appium/files/9913953/AppiumServerLogs.txt)

**Comment by james-vanhorn** [comment]
Side note to me rerun with Xcode logs enabled to see what’s happening and if there is any clue there. Also try physical device and Android (I guess with both uiautomator2 and espresso?) as well to see if that matters for some reason. Doubt it though, feels like an issue specific to iOS / XCUITest driver.

**Comment by Dan-Maor** [comment]
I believe that this may be the defined behavior according to this section:
https://github.com/appium/WebDriverAgent/blob/674fbe9b45d841d2bcf0749d797a88ea9ce00a04/WebDriverAgentLib/Utilities/FBElementTypeTransformer.m#L120

**Comment by jamesvanhorn** [comment]
Hmm yeah you're right it seems like any unknown element type is just mapped to XCUIElementTypeOther. Thanks for linking that. Going to borrow that list of element tags and make my own enum to reference.

**Comment by mykola-mokhnach** [comment]
confirming what @Dan-Maor stated above. The behaviour is expected because Apple adds new types from time to time and WDA might at some point stop working if a new type is added and it is not yet listed there unless we map it to a known one. 
This only happens though if your type name starts with `XCUIElementType` prefix. Any other strings will be parsed as unacceptable type names.
