### ISSUE TITLE
How to launch a proxy which supports w3c client but using jsonwp when forwarding message to WinAppDriver?

### ISSUE THREAD

**Issue by licanhua** [appium/appium#17726]
Hi, There is a [known issue](https://github.com/microsoft/WinAppDriver/issues/1610) that WinAppDriver doesn't support w3c and still using old jsonwp.

I saw appium supports both w3c and jsonwp in appium code. For example, [jsonwp-proxy](https://github.com/appium/appium/tree/master/packages/base-driver/lib/jsonwp-proxy)

Is it easy to create a proxy which sits between appium and winappdriver which converts the w3c to jsonwp?

The solution looks like this:

w3c client <-> appium <-> w3c to jsonwp proxy <-> WinAppDriver

**Comment by mykola-mokhnach** [comment]
It is already working like that, just not all APIs are covered: https://github.com/appium/appium/blob/master/packages/base-driver/lib/jsonwp-proxy/protocol-converter.js

**Comment by hritha** [comment]
@mykola-mokhnach - 

https://github.com/appium/appium/blob/master/packages/base-driver/lib/jsonwp-proxy/protocol-converter.js
Please share an example for java program that I can refer winAppdriver scenarios with jsonwp-proxy
