### ISSUE TITLE
Unable to Click an element in IOS Version 16.0.2

### ISSUE THREAD

**Issue by Subin367** [appium/appium#17724]
<img width="919" alt="Screenshot 2022-11-04 at 5 01 05 PM" src="https://user-images.githubusercontent.com/106580100/199962784-9779df94-9ef1-4482-9a79-737e66228561.png">

I am able to work with an element when the visible is true but the issue is with those elements which have visible false.
I tried tapping by getting the location of the element. 

The application was developed using Flutter.

XCode version- 14.1
Appium Version-1.22.3

**Comment by mykola-mokhnach** [comment]
The visibility valid is returned by XCTest and we cannot influence that. Consider reporting the issue to Apple.
