### ISSUE TITLE
Socket Hangup error.

### ISSUE THREAD

**Issue by devibalakrishnan** [appium/appium#17721]
Please review the enclosed document. It includes eclipse console logs, appium server logs, and adb logs. I have a suite of ten or more packages, ten+ classes, and twenty+ priority tests in each class. I see a socket hangup problem in the first package of a suite [after executing more than five classes (Approximately, 5 classes x 20 tests)]. Kindly lend me a hand to resolve this issue.

https://1drv.ms/w/s!AmMs39GJ0cP5cH1sUvtROeb7f0M

Expecting a guidance from you. Thank you!

**Comment by KazuCocoa** [comment]
Please follow bug report format via https://github.com/appium/appium/issues/new/choose, or please use https://discuss.appium.io/ to ask questions
