### ISSUE TITLE
bug: <Socket Hangup>

### ISSUE THREAD

**Issue by devibalakrishnan** [appium/appium#17738]
[###]([SocketHangup.docx](https://github.com/appium/appium/files/9949060/SocketHangup.docx)) Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Please review the enclosed document. It includes eclipse console logs, appium server logs, and adb logs. I have a suite of ten or more packages, ten+ classes, and twenty+ priority tests in each class. I see a socket hangup problem in the first package of a suite [after executing more than five classes (Approximately, 5 classes x 20 tests)]. Kindly lend me a hand to resolve this issue.

https://1drv.ms/w/s!AmMs39GJ0cP5cH1sUvtROeb7f0M

### Expected Behavior

Instead of socket hangup error, expecting to run all the test classes

### Minimal Reproducible Example

https://1drv.ms/w/s!AmMs39GJ0cP5cH1sUvtROeb7f0M

### Environment

- Operating system:Mac Os Monterey. version: 12.5.1
- Appium Desktop, its version:1.22.3
- Appium plugin(s) and their version(s):
- Platform: Eclipse 2022-23 
- Real device : vivo y21

**Comment by mykola-mokhnach** [comment]
Socket hangup means that UIA2 driver unexpectedly loses connection to the server part running on the device. There might be multiple reasons to that.

Please provide logs as gists and add the logcat output. Unfortunately I cannot open links above on my mac.

**Comment by mykola-mokhnach** [comment]
It also makes sense to use the most recent version of UIA2 driver, which is available in Appium 2. We do not maintain Appium 1 anymore

**Comment by devibalakrishnan** [comment]
[SocketHangup.docx](https://github.com/appium/appium/files/9949171/SocketHangup.docx)

**Comment by mykola-mokhnach** [comment]
I won't be able to help without access to requested logs provided in _plain text_ format

**Comment by devibalakrishnan** [comment]
[ERROR.pdf](https://github.com/appium/appium/files/9960041/ERROR.pdf)

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot find any traces of possible issues in the provided document. Probably, because all logs are cut.
Try the troubleshooting article at https://github.com/appium/appium-uiautomator2-driver#socket-hangup-error

**Comment by devibalakrishnan** [comment]
[SocketHangup.docx](https://github.com/appium/appium/files/9968066/SocketHangup.docx)

**Comment by devibalakrishnan** [comment]
[SocketHangup.pdf](https://github.com/appium/appium/files/9968106/SocketHangup.pdf)
Kindly check this pdf for all logs.

**Comment by mykola-mokhnach** [comment]
> 11-02 15:03:03.396 4736 4799 W Binder :
> stub implementation.
> 11-02 15:03:03.396 4736 4799 W Binder :
> not trusted UID!
> 11-02 15:03:03.396 4736 4799 W Binder : android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConn ection.java:525)
> 11-02 15:03:03.396 4736 4799 W Binder : at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:429)
> 11-02 15:03:03.396 4736 4799 W Binder : at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:390) 11-02 15:03:03.396 4736 4799 W Binder : at android.os.Binder.execTransactInternal(Binder.java:1159)
> 11-02 15:03:03.396 4736 4799 W Binder : at android.os.Binder.execTransact(Binder.java:1123)


This is what causes the issue. Unfortunately the exception is coming from UiAutomator framework itself, so I don't know if we could do anything on our side about it. 
Simply make sure the driver and server versions are up to date.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
