### ISSUE TITLE
[Feat]: Is it possible to pass the arguments via the Appium?

### ISSUE THREAD

**Issue by andrew-clear** [appium/appium#17737]
Is it possible to pass the arguments via the Appium?
I can pass arguments via the Xcode, but I want to be able to pass the arguments via the Appium.
I tried to use the `processArguments`, but it isn't working.

![Screen Shot 2022-11-06 at 16 38 50](https://user-images.githubusercontent.com/81910554/200181246-6d507c13-9229-4185-8695-545dc3e321b0.jpg)

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description according to the given template

**Comment by andrew-clear** [comment]
@mykola-mokhnach 
I need to pass runtime arguments to the app.
We want to send arguments, as I can do that via the Xcode when I build the .ipa, and I can print this argument.
Here is how we print the argument in our app:
```
DispatchQueue.main.asyncAfter(deadline: .now() + 5) {
            let value = CommandLine.arguments.joined(separator: "\n")
            self.router.showPopupViewController(title: "TestArgs", message: value, buttons: [.init(title: "OK", handler: nil)], theme: self.uiTheme)
        }
```

**Comment by mykola-mokhnach** [comment]
processArguments is the only possible way to send arguments to an app under test. 
I cannot help further without logs and other necessary details.  `is not working` is not very helpful thing to investigate.

**Comment by KazuCocoa** [comment]
I guess you set the processArguments like`"appium"processArguments": { args: ["something"] }` as the example in https://github.com/appium/appium-xcuitest-driver#webdriveragent. Then, our implementation passes it to https://developer.apple.com/documentation/xctest/xcuiapplication/1500477-launcharguments?language=objc . 

Bug report in https://github.com/appium/appium/issues/new/choose may help to prepare the details what we need

**Comment by andrew-clear** [comment]
This solution helped me
https://discuss.appium.io/t/how-to-pass-ios-launchoptions-in-appdelegate-from-appium/32610/4

> "appium:processArguments" via ProcessInfo.processInfo.arguments or ProcessInfo.processInfo.environment not the launchOptions in the didFinishLaunchingWithOptions: function.
> [https://developer.apple.com/documentation/foundation/processinfo 22](https://developer.apple.com/documentation/foundation/processinfo)

Dev team fixed 
thanks @KazuCocoa @mykola-mokhnach
