### ISSUE TITLE
bug: w3c actions should be able to type a unicode key(?) like \uE003 on iOS

### ISSUE THREAD

**Issue by mwakizaka** [appium/appium#17734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

suppose running a following snippet of code
```
  let el = await driver.$('XXX');
  // make sure the keyboard is up
  await el.click();

  const actions = [{
    type: 'key',
    id: 'keyboard',
    actions: [
      {type: 'keyDown', value: '0'},
      {type: 'keyUp', value: '0'},
      {type: 'keyDown', value: '1'},
      {type: 'keyUp', value: '1'},
      {type: 'keyDown', value: '\uE003'},
      {type: 'keyUp', value: '\uE003'}
    ]
  }];
  await driver.performActions(actions);
```

it types nothing

### Expected Behavior

the output value in the element should be eventually `0`

### Minimal Reproducible Example

```
it('should key a backspace', async function () {
  let el = await driver.$('XCUIElementTypeTextField');
  // make sure the keyboard is up
  await el.click();

  const actions = [{
    type: 'key',
    id: 'keyboard',
    actions: [
      {type: 'keyDown', value: '0'},
      {type: 'keyUp', value: '0'},
      {type: 'keyDown', value: '1'},
      {type: 'keyUp', value: '1'},
      {type: 'keyDown', value: '\uE003'},
      {type: 'keyUp', value: '\uE003'}
    ]
  }];
  await driver.performActions(actions);

  let text = await el.getText();
  text.should.eql('0');
})
```

### Environment

- Operating system: macOS 12.6
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.46
  - Node.js version (output of `node --version`): v16.13.2
  - `npm` version (output of `npm --version`): 8.1.2
  - Last `appium` version which did _not_ exhibit the problem: N/A
- If running Appium Desktop, its version: N/A
- Appium driver(s) and their version(s): xcuitest@4.12.1 [installed (NPM)]
- Appium plugin(s) and their version(s): N/A
- Platform and version under test: iOS 16.1
- Real device or emulator/simulator: simulator
- Xcode: `Xcode 14.1 Build version 14B47b`

### Link to Appium Logs

https://gist.github.com/mwakizaka/006417e583bf234b7f440a44d6703043

### Futher Information

- this issue has been derived from https://github.com/appium/appium-xcuitest-driver/pull/1450#discussion_r1013476391

**Comment by mykola-mokhnach** [comment]
The support of key typing is quite limited in iOS because poor internal XCTest APIs. Not sure if this scenario is possible in general, but you could try to play with the actual implementation: https://github.com/appium/WebDriverAgent/blob/915f5486e8d8477342d2aeb39aeadd5379a3aa7c/WebDriverAgentLib/Utilities/FBW3CActionsSynthesizer.m#L389

**Comment by jlipps** [comment]
@mwakizaka yes unfortunately w3c support is best effort because we don't control the underlying implementation so there's only so much we can do. but maybe it's possible by looking at how we call the xctest apis.

**Comment by mwakizaka** [comment]
thank you for the responses. I'll try to address this issue. although I'm not very familiar with the implementation, I guess it's possible because `/session/:sessionId/keys` end point works as I expected. e.g. 
```
        it('should key a backspace', async function () {
          let el = await driver.$('XCUIElementTypeTextField');
          // make sure the keyboard is up
          await el.click();

          await driver.sendKeys(['01\uE003']);
          let text = await el.getText();
          text.should.eql('0');
        });
```

**Comment by jlipps** [comment]
ok yeah it suggests there is some way it might work then

**Comment by mykola-mokhnach** [comment]
closed as fixed
