### ISSUE TITLE
bug: Accepting alert on iOS presses the "precise" button instead

### ISSUE THREAD

**Issue by jamesvanhorn** [appium/appium#17754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Simulator Screen Shot - iPhone 14 - 2022-11-09 at 10 38 21](https://user-images.githubusercontent.com/19415323/200873937-6f6cd35a-cc86-4982-8374-fc711308a93f.png)

While this screen is active, calling `driver.switchTo().alert().accept()` taps the "Precise: On" button changing it to"Precise: Off"

### Expected Behavior

I would expect it to tap on either "Allow Once" or "Allow While Using the App"

### Minimal Reproducible Example

driver.switchTo().alert().accept(); //you'll need an alert showing that is location based and allows for toggling precise location on/off

### Environment

Operating system: Mac OSX 12.6
If running via appium CLI...
Appium CLI version (output of appium --version): 2.0.0-beta.46
Node.js version (output of node --version): v16.17.0
npm version (output of npm --version): 8.15.0
Last appium version which did not exhibit the problem: Unsure
Appium driver(s) and their version(s): xcuitest@4.12.1
Appium plugin(s) and their version(s): N/A
Platform and version under test: iOS 16.0
Real device or emulator/simulator: Both

### Futher Information

[appiumLogs.txt](https://github.com/appium/appium/files/9972673/appiumLogs.txt)

Side note, is there a suggested better way to have control on Alerts with more than 2 buttons? accept/dismiss work fine for binary alerts, but not for this location alert (bug notwithstanding) as accept() is ambiguous and could be "allow once" or "allow while using app" while dismiss() should map to "don't allow" obviously. 

I wrote a class to handle this that uses xpath index to tapAlertAtIndex(int), but that feels hacky/wrong. Thanks!

**Comment by mykola-mokhnach** [comment]
This is expected as xctest does not provide a reliable way of alert buttons detection. You could either click the necessary button in your client script or define a custom value to acceptAlertButtonSelector/dismissAlertButtonSelector [settings](https://github.com/appium/appium-xcuitest-driver#settings-api)

**Comment by jamesvanhorn** [comment]
thanks as always for the quick response and guidance @mykola-mokhnach

**Comment by ansonliao** [comment]
Hi @mykola-mokhnach , 
Could you kindly help to advise how to use the `acceptAlertButtonSelector`/`dismissAlertButtonSelector` of [settings](https://github.com/appium/appium-xcuitest-driver#settings-api)? 
I am running Appium with JS/TS in WebDriverIO.
Thanks.

**Comment by bwomsm1** [comment]
> Hi @mykola-mokhnach , Could you kindly help to advise how to use the `acceptAlertButtonSelector`/`dismissAlertButtonSelector` of [settings](https://github.com/appium/appium-xcuitest-driver#settings-api)? I am running Appium with JS/TS in WebDriverIO. Thanks.

Hi @ansonliao , did you find any answer to that question?
