### ISSUE TITLE
bug: StaleElementReferenceException: The previously found element "PickerWheel" is not present in the current view anymore

### ISSUE THREAD

**Issue by viveksoundar** [appium/appium#17752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Tried the solution provided last time [#17569](https://github.com/appium/appium/issues/17569) , but still I face the stale reference exception while automating the wheelpicker

### Expected Behavior

It should be allowed to select values from the wheelPicker, the solution was given not helpful

### Minimal Reproducible Example

Entire appium log is provided here.
https://gist.github.com/viveksoundar/077b74f3b67a598c50b12585da725e92

### Environment

- Operating system: Mac OS Montrey 12.6
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.46
  - Node.js version (output of `node --version`):v18.11.0
  - `npm` version (output of `npm --version`): 8.19.2
  - Last `appium` version which did _not_ exhibit the problem: It worked in 1.2
- If running Appium Desktop, its version: 
- Appium driver(s) and their version(s): xcuitest@4.12.2
- Appium plugin(s) and their version(s):
- Platform and version under test: iOS 16.0
- Real device or emulator/simulator: Real Device

### Link to Appium Logs

https://gist.github.com/viveksoundar/077b74f3b67a598c50b12585da725e92

**Comment by viveksoundar** [comment]
@mykola-mokhnach can you please help me to unblock from this?

**Comment by mykola-mokhnach** [comment]
I don't know how I can help.

**Comment by Dan-Maor** [comment]
@viveksoundar according to the Appium log it looks like you're trying to retrieve the text value of the pickerwheel element after - like @mykola-mokhnach previously explained - its accessibility id has changed.

You can perhaps try to search for the element again using the same Xpath after the pickerwheel value has changed and check its value. Might not be ideal, but that's the best I can think of.

**Comment by anurag-lambdatest** [comment]
I can see that WebDriverAgent crashes once this exception is encountered, is there a way to ensure WDA does not crash?

**Comment by anurag-sudo** [comment]
I can see that WebDriverAgent crashes once this exception is encountered, is there a way to ensure WDA does not crash?
