### ISSUE TITLE
bug: Find Element by Image fails randomly 

### ISSUE THREAD

**Issue by jorgoncalves** [appium/appium#17753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**We have a suite of tests for Android that use the find element by image, on static images, which can all be found, but sometimes it fails randomly with the bellow error.**

NoSuchElementException: Message: An element could not be located on the page using the given search parameters.
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at ImageElementFinder.findByImage (/Users/username/.appium/node_modules/@appium/images-plugin/lib/finder.js:230:13)
    at ImageElementPlugin._find (/Users/username/.appium/node_modules/@appium/images-plugin/lib/plugin.js:61:12)
    at ImageElementPlugin.findElement (/Users/username/.appium/node_modules/@appium/images-plugin/lib/plugin.js:45:12)
    at /usr/local/lib/node_modules/appium/lib/appium.js:722:18
    at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:762:16)
    at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:684:17)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:346:19)

-----------------------

**After getting the above error, subsequent runs of the same suite will get the bellow error.**

WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'match')
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot read properties of undefined (reading 'match')
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:956:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:435:35)

**This second error will always appear until the server is restarted and the images will be found again until the first error happens again.**

### Expected Behavior

The images are found or not consistently and the server is able to handle the exception without the needing a restart.

### Minimal Reproducible Example

We are providing an png image into the bellow function, which will then be converted to base64.

    def _find_by_image(self, img_path: str):
           driver = self._get_driver_instance()
    
            with open(img_path, 'rb') as i_file:
                b64_data = base64.b64encode(i_file.read()).decode('UTF-8')
    
            return driver.find_element(by=AppiumBy.IMAGE, value=b64_data)

Regarding steps is only needed to execute the find_by_image a few times.

### Environment

- Operating system: MacOS/Windows
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.46
  - Node.js version (output of `node --version`): v16.14.2
  - `npm` version (output of `npm --version`): 8.17.0
- Appium driver(s) and their version(s): 
  - uiautomator2@2.10.2
- Appium plugin(s) and their version(s):
  - device-farm@2.0.0-beta.4 [installed (NPM)]
  - appium-dashboard@v1.0.0-beta.13 [installed (NPM)]
  - images@1.3.7 [installed (NPM)]
- Platform and version under test:
  - Android 12
- Real device or emulator/simulator:
  - Redmi  Note 9T

### Link to Appium Logs

https://gist.github.com/jorgoncalves/8a163bbcd77498cab0a02a9e4f3b520e

**Comment by mykola-mokhnach** [comment]
I believe the plugin provides settings that allow to customise the matching threshold. Otherwise the matching itself is done by opencv and we cannot influence that

**Comment by jorgoncalves** [comment]
The images plugin has an option to configure the matching threshold, which is at the default of 0.4, but that isn't being changed during tests, so it failing for not finding the image and them not being able to use the find element by image again, shouldn't be a bug from appium? 

Like I mentioned on Current Behavior, the suite passes as expected but after a few couple of runs it will not be able to find a given image that is on the screen and previously was able to find, with the first error which will make the suite fail (like it should), and all the other calls to find element by image will result on the second error, making so you can't call that method anymore without a server restart.

**Comment by jorgoncalves** [comment]
Do you require more info from me?

**Comment by mykola-mokhnach** [comment]
You could try to check out the patch https://github.com/appium/appium/pull/17756 and verify if it works

**Comment by jorgoncalves** [comment]
This where the steps that I took:
- Applied the changes on the mentioned patch locally
- Restarted the server
- Generated a apk build and used for all the subsequent suite runs
- Run the suite 2 times with success (Finding all the images)
- Run the suite a 3 time and it failed with the first error (NoSuchElementException)
- Running the suite after that, always returns the second error (WebDriverException) when using the find element by image.

So the issue is still there.

After the above, I restarted the appium server and changed an image to something wrong, expecting it to not be found and I was able to reuse the find image method without getting the WebDriverException, which from what I understand is the expected behaviour.

**Comment by mykola-mokhnach** [comment]
> Running the suite after that, always returns the second error (WebDriverException) when using the find element by image.

Could you please the server log and the actual exception stack trace?

**Comment by jorgoncalves** [comment]
After deleting the existing server and installing it again we still got the same behaviour. Also confirmed that this happens in 3 machines, one being a Mac and two Windows 10.

Could you please explain how I get the actual exception stack trace? Would like to provide all the info needed.

**Comment by mykola-mokhnach** [comment]
Reinstalling the server won't help as the patch has not been merged neither published yet. You must checkout the branch from GitHub and run appium from sources in order to verify the fix locally

**Comment by mykola-mokhnach** [comment]
Closed because of no response. The patch is currently merged to master, but not published. The only way to try it is to run the server from source or wait until the next version is published
