### ISSUE TITLE
bug: Appium keeps killing emulator whenever a test fails

### ISSUE THREAD

**Issue by algernon28** [appium/appium#17768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run a Test (TestNG+Cucumber), after the test ends it kills the emulator whether it was started by Appium or manually, without even giving the time for a screenshot.

This only happens with Appium 2.0

### Expected Behavior

The emulator should not be killed, at least when I started it outside Appium.
Expecially it should not be brutally killed like that.

I'm not even sure if it is the emulator crashing or it is terminated by Appium, but as I mentioned above, it does not happen with Appium 1.x

I start appium with CLI (using two plugins, but it also happens without them)
_appium server --base-path /wd/hub --allow-insecure chromedriver_autodownload ^
--use-plugins execute-driver ^
--log C:\dev\logs\appium.log_

The emulator is running Android SDK 31.0 with these capabilities:
_{
"platformName": "Android",
"appium:platformVersion": "12.0",
"appium:automationName": "UiAutomator2",
"appium:deviceName": "emulator-5554",
"appium:deviceOrientation": "portrait",
"appium:appWaitActivity": "it.hype.app.ui.dev.DevToolsActivity",
"appium:avd": "A12",
"appium:browserName": "Chrome",
"newCommandTimeout": 500
}_

### Minimal Reproducible Example

I don't have a "minimal" example now because the tests run in a framework.
Basically it seems to happen just after the end of execution, when my cucumber hook is trying to uninstall the app.
I also attach here android logcat and my application log, if they are any useful.

[logcat.log](https://github.com/appium/appium/files/9989611/logcat.log)
[slf4j-logback.log](https://github.com/appium/appium/files/9989612/slf4j-logback.log)

### Environment

- Operating system: Windows 10 pro
- If running via `appium` CLI... 
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.46
  - Node.js version (output of `node --version`): 18.12.1
  - `npm` version (output of `npm --version`): 8.19.3
  - Last `appium` version which did _not_ exhibit the problem: 1.x

The tests run with:

- java-client 8.2.0
- selenium-support 4.5.0
- org.tesng 7.6.1
- cucumber-java 7.9.0
- maven surefire 3.0.0-M7

### Link to Appium Logs

https://gist.github.com/algernon28/24b981254506371349ded398a5fe2df1

**Comment by mykola-mokhnach** [comment]
I don't see any traces of UIA2 trying to kill the emulator (and it actually should not to unless the emulator is created by this particular session). Most likely it just crashes unexpectedly. Verify the OS event logs for more details.

**Comment by algernon28** [comment]
But it doesn't happen with Appium 1.x...

**Comment by mykola-mokhnach** [comment]
I don't see much options there. You could either keep using the unmaintained Appium1 or find out which actions makes emulator crashing and report it to Google hoping it's going to be fixed soon

**Comment by algernon28** [comment]
I see this event:
The strange thing is that if I perform 2 test executions in the same session the emu doesn't get killed but still get errors after each execution.
Any idea on what could be the cause?

Nome registro: Application
Origine:       Application Error
Data:          11/11/2022 14:26:34
ID evento:     1000
Categoria attività:(100)
Livello:       Errore
Parole chiave: Classico
Utente:        N/D
Computer:      DRUMNADROCHIT
Descrizione:
Nome dell'applicazione che ha generato l'errore: qemu-system-x86_64.exe, versione: 0.0.0.0, timestamp: 0x633747c5
Nome del modulo che ha generato l'errore: MSVCP140.dll, versione: 14.32.31326.0, timestamp: 0x7255e0ca
Codice eccezione: 0xc0000005
Offset errore 0x0000000000013278
ID processo che ha generato l'errore: 0x7a8
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d8f5d1381985e2
Percorso dell'applicazione che ha generato l'errore: D:\development\Android\Android_SDK\emulator\qemu\windows-x86_64\qemu-system-x86_64.exe
Percorso del modulo che ha generato l'errore: C:\WINDOWS\SYSTEM32\MSVCP140.dll
ID segnalazione: 22cbe251-7bd0-441c-aad9-97df2cbefa2f
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore: 
XML evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-11-11T13:26:34.9023790Z" />
    <EventRecordID>2421793</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DRUMNADROCHIT</Computer>
    <Security />
  </System>
  <EventData>
    <Data>qemu-system-x86_64.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>633747c5</Data>
    <Data>MSVCP140.dll</Data>
    <Data>14.32.31326.0</Data>
    <Data>7255e0ca</Data>
    <Data>c0000005</Data>
    <Data>0000000000013278</Data>
    <Data>7a8</Data>
    <Data>01d8f5d1381985e2</Data>
    <Data>D:\development\Android\Android_SDK\emulator\qemu\windows-x86_64\qemu-system-x86_64.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\MSVCP140.dll</Data>
    <Data>22cbe251-7bd0-441c-aad9-97df2cbefa2f</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by algernon28** [comment]
I tried to debug it, and it happens that right after the end of a scenari
that the crash (if it is a crash) happens right after I do driver.terminateApp()...

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by jlipps** [comment]
FWIW if you don't want appium to manage the AVD lifecycle then I would probably not use the `appium:avd` capability at all.

**Comment by algernon28** [comment]
@jlipps What should I use to point the avd then? deviceName?

**Comment by jlipps** [comment]
`udid` set to the value returned by `adb devices`
