### ISSUE TITLE
[Feat]:Add opencv4nodejs support in image-plugin

### ISSUE THREAD

**Issue by scxhwhb** [appium/appium#17765]
**Is your feature request related to a problem? Please describe.**
I run appium on an arm device like Raspberry PI. Finding elements by image will take more than 10 seconds. I modify it using opencv4nodejs, the same finding just take about 3 seconds. On a normal x86 computer, it also takes about half as long.

**Describe the solution you'd like**
Use opencv.js by default, but the user can decide whether to use opencv4nodejs by configuration.

**Comment by mykola-mokhnach** [comment]
It was a deliberate decision to drop opencv4nodejs lib because it has no maintainers.

**Comment by scxhwhb** [comment]
So I will I will modify it locally. Thanks for help.

**Comment by mykola-mokhnach** [comment]
you could also create an alternative plugin and make it public
