### ISSUE TITLE
Testing Multiple Apps in One Device - First session is terminated when second starts

### ISSUE THREAD

**Issue by rasihonurolgun** [appium/appium#17775]
Hello,
I’m trying to use one device and I would like to test two different apps on one device. (Android)
I checked through documentation and according to that configured the necessary settings for appium servers and also for sessions.
https://github.com/appium/appium-uiautomator2-driver#parallel-tests as it states here, for parallel tests systemPort capability should be given differently.

Another post: https://stackoverflow.com/questions/54740167/how-to-open-same-mobile-application-with-different-types-of-users-and-switching

As it is stated here, I also changed the Bootstrap port for 2 server instances.
Here is my configuration for Appium Servers: (Started via Appium Desktop App)
![appium_servers_cfg](https://user-images.githubusercontent.com/36571369/201720157-bdad7b55-3ad8-4476-adae-e304ecfdf38c.PNG)

**Appium Inspector Configurations:**
First session is configured to work on 127.0.0.0.1/4724 with **systemPort** 8202 and second is 127.0.0.0.1/4734 **systemPort** 8212 

**1st session: First App** 

    Caps:
        {
          "platformName": "Android",
          "appium:deviceName": "Nokia G20 new",
          "appium:udid": "PT99653AA11B2600974",
          "appium:appPackage": "app_package_here",
          "appium:automationName": "UiAutomator2",
          "appium:appActivity": "app_activity_here",
          "appium:unlockType": "password",
          "appium:unlockKey": "1111",
          "appium:newCommandTimeout": 7200,
          "appium:app": apk_path_here",
          "appium:nativeWebScreenshot": true,
          "appium:clearSystemFiles": true,
          "appium:systemPort": 8202,
          "appium:fullReset": false,
          "appium:noReset": true
        }
![1st_session_cfg_app_inspector](https://user-images.githubusercontent.com/36571369/201720400-2ebb757e-eb45-4c3c-a28c-de95ab7268b1.png)

**2nd session: Second App**

    Caps:
        {
          "platformName": "Android",
          "appium:deviceName": "Nokia G20 new",
          "appium:udid": "PT99653AA11B2600974",
          "appium:appPackage": "different_app_package_here",
          "appium:automationName": "UiAutomator2",
          "appium:appActivity": "different_app_activity_here",
          "appium:unlockType": "password",
          "appium:unlockKey": "1111",
          "appium:newCommandTimeout": 7200,
          "appium:app": apk_path_here",
          "appium:nativeWebScreenshot": true,
          "appium:clearSystemFiles": true,
          "appium:systemPort": 8212,
          "appium:fullReset": false,
          "appium:noReset": true
        }

![2nd_session_cfg_app_inspector](https://user-images.githubusercontent.com/36571369/201720412-d851c43f-9db5-4c70-ad76-e27b68ae9e00.png)

**Issue description:**
When I start the **1st session**, everything is fine. Session starts.(2nd server instance already terminates! Why??) Then I'm trying to start **2nd session** with a different app. At this point, **1st session** got terminated by itself and of course, I can't take any actions.

**Appium Server and App Inspector logs when the problem happens:**
![problem1](https://user-images.githubusercontent.com/36571369/201720555-52b5f98d-8e02-41ee-977f-501e1d7ae056.PNG)
![problem2](https://user-images.githubusercontent.com/36571369/201720560-5b758eec-7f48-40a3-aefa-097da1c8e952.PNG)

What is the problem here? Is it not possible to open up two apps on one device in different sessions?

I also tried different remote ports, localhost address, bootstrap ports and so on. Nothing worked. 

**Note:** 
- Appium Desktop (Server) App version: 1.20.0 
- Appium Inspector version: 2022.9.1

Kind regards,

**Comment by mykola-mokhnach** [comment]
This is expected. Parallel sessions could only be executed on *different* devices.

**Comment by mykola-mokhnach** [comment]
No this is not possible. You can only switch between apps in scope of the same session

**Comment by rasihonurolgun** [comment]
@MagdelineNg in one device its not possible. If you have 2 different devices you can open two different sessions. And if you are going to use 2 sessions from one script, it should be possible IMHO.
