### ISSUE TITLE
bug: Appium crashes with android app

### ISSUE THREAD

**Issue by algernon28** [appium/appium#17780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Refer to https://github.com/appium/appium/issues/17768
Apparently now switching the emulator to Android 11 the emulator itself won't crash anymore.
However, the app crashes (probably due to its own bug not sure), but the worrying part is that Appium seems to crash too with it.
The SIGINT in the appium log is because I had to manually close the window, but Appium itself was not responding anymore.

### Expected Behavior

Appium should not terminate if the android app crashes.

### Minimal Reproducible Example

N.A

### Environment

- Operating system:
- If running via `appium` CLI... 
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.46
  - Node.js version (output of `node --version`): 18.12.1
  - `npm` version (output of `npm --version`): 8.19.3
  - Last `appium` version which did _not_ exhibit the problem: 

- The tests run with:
  - java-client 8.2.0
  - selenium-support 4.5.0
  - org.tesng 7.6.1
  - cucumber-java 7.9.0
  - maven surefire 3.0.0-M7

### Link to Appium Logs

https://gist.github.com/algernon28/366d2128dd5031e3bb34e14d78037b51

**Comment by mykola-mokhnach** [comment]
> Appium seems to crash too with it.

Where is the corresponding log line which shows that crash? I cannot find any traces of it in the log

**Comment by algernon28** [comment]
2022-11-16 11:03:11:931 [Instrumentation] Time: 40.112

2022-11-16 11:03:11:933 [Instrumentation] 

2022-11-16 11:03:11:934 [Instrumentation] OK (1 test)
2022-11-16 11:03:12:444 [Instrumentation] The process has exited with code 0

**Comment by algernon28** [comment]
At that point I had to manually kill the window because Appium was not responding anymore

**Comment by mykola-mokhnach** [comment]
> At that point I had to manually kill the window because Appium was not responding anymore (therefore the very last line "2022-11-16 11:10:34:216 [Appium] Received SIGINT - shutting down")

Which window it is? Appium is a CLI server, it does not create any windows. Also, have you tried to send any command to it using curl? Is it listening on the given port?

**Comment by algernon28** [comment]
(sorry for the labels, must have clicked on them by mistake)

**Comment by mykola-mokhnach** [comment]
I don't observe any server errors/issues neither in the attached log nor in the video. It looks like the emulator itself stops being visible to adb after calling `dumpsys` command. 
Maybe try to run tests on a Linux or macOS where emulator/adb combination is more stable

**Comment by algernon28** [comment]
Excuse me
the log says 
```
2022-11-16 11:03:11:931 [Instrumentation] Time: 40.112
2022-11-16 11:03:11:933 [Instrumentation]
2022-11-16 11:03:11:934 [Instrumentation] OK (1 test)
2022-11-16 11:03:12:444 [Instrumentation] The process has exited with code 0
```

which is exactly after the emulator died. With that Appium stopped responding

**Comment by algernon28** [comment]
It seems you are right.
The behaviour is so erratic that it looked like Appium's fault.
