### ISSUE TITLE
[Feat]: iOS 16 and Xcode 14 Support

### ISSUE THREAD

**Issue by JYOTIPRAKASH225** [appium/appium#17782]
Any Tentative date on iOS 16 and Xcode 14 Support?

**Comment by KazuCocoa** [comment]
Have you tried https://github.com/appium/appium-xcuitest-driver#xcode-version-support ?

A note about the XCUITest version:

https://github.com/appium/appium-xcuitest-driver#appium-xcuitest-driver

> Since version 4.0.0 XCUITest driver has dropped the support of Appium 1, and is only compatible to Appium 2. Use the appium driver install xcuitest command to add it to your Appium 2 dist.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. Kindly use Appium forum to ask questions
