### ISSUE TITLE
bug: Element click hides mouse pointer

### ISSUE THREAD

**Issue by MiniGadget** [appium/appium#17797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using windows driver and 'click' is called on an element, an animation plays to indicate the click location but this hides the mouse pointer. If further clicks are done at the *same* location the mouse pointer stays hidden, the click animation plays, but the click does not work. If the mouse is moved, then the pointer re-appears and clicks will work again. Moving the pointer currently cannot be done programmatically due to another issue...

https://github.com/appium/appium/issues/17779

### Expected Behavior

Click does not hide mouse pointer, or works as expected for subsequent clicks

### Minimal Reproducible Example

element.click();

### Environment

Operating system: Windows 10
If running via appium CLI...
Appium CLI version (output of appium --version): 2.0.0-beta.46
Node.js version (output of node --version): v18.8.0
npm version (output of npm --version): 8.18.0
Last appium version which did not exhibit the problem: unknown
If running Appium Desktop, its version: n/a
Appium driver(s) and their version(s): windows@2.1.2
Appium plugin(s) and their version(s): images@1.3.7
Platform and version under test: windows 10
Real device or emulator/simulator: real device

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot change this behavior as the server part is owned by Microsoft and it is not open source. Consider reporting an issue to https://github.com/microsoft/WinAppDriver
