### ISSUE TITLE
bug: [Android Native]Appium 2.0.0 fails finding input element from type password 

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#17798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I am printing my elements on the screen I can clearly see that I have the following element:
```
<android.widget.EditText index="0" package="com.stanley.deployment" class="android.widget.EditText" text="Key" resource-id="com.stanley.deployment:id/key_validation_TextInputEditText" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="true" password="true" scrollable="false" selected="false" bounds="[48,814][1032,981]" displayed="true" hint="Key" />
```

But when I am searching for that element with uiautomator and id = `com.stanley.deployment:id/key_validation_TextInputEditText` I am getting the following error on Appium log:
```
[debug] [AndroidUiautomator2Driver@e82f (0b3d2a27)] Proxying [POST /element] to [POST http://127.0.0.1:8200/session/69742647-4d42-4133-bcfa-c84ce4f8a4bc/element] with body: {"strategy":"id","selector":"com.stanley.deployment:id/Key_validation_TextInputEditText","context":"","multiple":false}
[AndroidUiautomator2Driver@e82f (0b3d2a27)] Got response with status 404: {"sessionId":"69742647-4d42-4133-bcfa-c84ce4f8a4bc","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:70)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:267)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:261)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann...
```

### Expected Behavior

WebElement should be found with the resource id 
```
com.stanley.deployment:id/key_validation_TextInputEditText
```

### Minimal Reproducible Example

find_element(By.ID, 'com.stanley.deployment:id/key_validation_TextInputEditText') 

### Environment

- Operating system: Mac OS
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.46
  - Node.js version (output of `node --version`): v16.13.0
  - `npm` version (output of `npm --version`): 8.1.0
  - Last `appium` version which did _not_ exhibit the problem: 1.22.3
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test: Android native.
- Real device or emulator/simulator: real device.

### Link to Appium Logs

https://github.com/bwomsm1/AppiumLogs/blob/master/input_password.log

**Comment by mykola-mokhnach** [comment]
> [debug] [AndroidUiautomator2Driver@e82f (0b3d2a27)] Proxying [POST /element] to [POST http://127.0.0.1:8200/session/69742647-4d42-4133-bcfa-c84ce4f8a4bc/element] with body: {"strategy":"id","selector":"com.stanley.deployment:id/Key_validation_TextInputEditText","context":"","multiple":false}
> [AndroidUiautomator2Driver@e82f (0b3d2a27)] Got response with status 404: {"sessionId":"69742647-4d42-4133-bcfa-c84ce4f8a4bc","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:70)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:267)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:261)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann...

Are you sure the locator value is the same as in the xml page source? The one above is different

**Comment by bwomsm1** [comment]
@mykola-mokhnach yes I am 100% sure, this is very weird for me too.

**Comment by mykola-mokhnach** [comment]
> com.stanley.deployment:id/Key_validation_TextInputEditText (page source)
> com.stanley.deployment:id/key_validation_TextInputEditText (locator)

These two strings are different, aren't they?

**Comment by bwomsm1** [comment]
Different? I don't see it.... maybe **char difference** thing, do you want me to try by coping from the page source? I will try

**Comment by bwomsm1** [comment]
Wow @mykola-mokhnach my bad big time!
The difference is with the capital `k`
`com.stanley.deployment:id/**K**ey_validation_TextInputEditText`
vs 
`com.stanley.deployment:id/**k**ey_validation_TextInputEditText`

**Comment by bwomsm1** [comment]
Not a bug. thanks @mykola-mokhnach
