### ISSUE TITLE
[Feat]: Handle driver install/update flow for peer dependencies set to "future" server versions

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#17806]
Given a situation: 
- User has Appium server version X installed on the machine, which is not the latest one. 
- User executes install/upgrade command for driver FOO, which itself or one of its dependent modules requires minimum Appium server version X+n as peer dependency

Actual result:
The driver gets successfully installed and then fails in runtime with some random unclear error because of missing function/member, etc

Expected result:
We should either verify peer dependencies (also dependencies of dependencies) for the given driver module and throw an error or show a warning if the required server version is incompatible with the current one (e.g. the current server version is too low and must be updated)

The expected behaviour above needs to be discussed though.

**Comment by mykola-mokhnach** [comment]
cc @jlipps @boneskull @KazuCocoa

**Comment by boneskull** [comment]
there is a warning displayed if the peer dep isn't satisfied, but it won't prevent installation if done via `appium install`. 

if the upgrade command detects a new version with an unsatisfiable peer dep, the nicest thing to do would be to prompt the user to upgrade appium or upgrade anyway or abort. maybe that also means adding a "self-update" command to appium

**Comment by mykola-mokhnach** [comment]
This warning would probably not help if updates are done via CI. We probably need something (maybe a command line parameter) that would prevent install/update completely in such case. 
Also, not quite sure such scenario would work for a dependency of dependency, for example, if we try to install appium-xcuitest-driver, which depends on appium-webdriver-agent, which requires higher version of appium peer dep.

**Comment by jlipps** [comment]
> Also, not quite sure such scenario would work for a dependency of dependency, for example, if we try to install appium-xcuitest-driver, which depends on appium-webdriveragent, which requires higher version of appium peer dep (while xcuitest-driver itself is still fine).

I don't think we should allow this situation as developers. The only thing Appium knows about are drivers, not driver deps. Therefore if a driver developer upgrades a dep that somehow requires a newer version of Appium, the developer is obligated to reflect that in the driver's required Appium peer version. With locked/shrinkwrapped deps, the same version of a driver should never be pulling in new versions of deps so it is theoretically possible to ensure this.

> if the upgrade command detects a new version with an unsatisfiable peer dep, the nicest thing to do would be to prompt the user to upgrade appium or upgrade anyway or abort. maybe that also means adding a "self-update" command to appium

Yeah good point that this should be surfaced as part of the install process (and upgrade and maybe even list process), and not just during server start.

I'm not sure how complex something like `appium --self-update` would actually be. I'm afraid it would be brittle given the variety of ways users might have installed it. But maybe it's simple and worthwhile.

**Comment by mykola-mokhnach** [comment]
> I don't think we should allow this situation as developers. The only thing Appium knows about are drivers, not driver deps. Therefore if a driver developer upgrades a dep that somehow requires a newer version of Appium, the developer is obligated to reflect that in the driver's required Appium peer version. With locked/shrinkwrapped deps, the same version of a driver should never be pulling in new versions of deps so it is theoretically possible to ensure this.

I am still not quite sure if this is going to work for peer dependencies. I don't think lockfiles have records for these. Correct me if I'm wrong @jlipps

**Comment by mykola-mokhnach** [comment]
As for the 

> Therefore if a driver developer upgrades a dep that somehow requires a newer version of Appium, the developer is obligated to reflect that in the driver's required Appium peer version.

also not sure how to follow that rule in the real world. Let say I change appium-webdriveragent and set `appium` peer dep to a higher version. Then next time xcuitest driver is published it automatically picks up that new module version because we do not have dependency version numbers set to struct values, but rather allow all minor and patch updates (which makes sense to me). And I don't think it worth to change the major module version if a peer server version is bumped.

**Comment by jlipps** [comment]
What I'm saying is we should not have `appium` as a peer dep for `appium-webdriveragent` at all. Rather the xcuitest driver should receive a PR at the same time updating its `appium` peer dep rev as well as `appium-webdriveragent`.

**Comment by jlipps** [comment]
Also, I would be sort of inclined to think that if `appium-webdriveragent` is relying on something from a certain version of appium we are doing something wrong. Would be better to have whatever it needs injected from the xcuitest driver, which can then manage ownership of appium related things.

**Comment by mykola-mokhnach** [comment]
Ok, this sounds logical to not have direct peer dependencies in non-driver modules. I'll prepare PRs later to achieve that
