### ISSUE TITLE
bug: appium failed to connect to windows@2.1.2

### ISSUE THREAD

**Issue by Dor-bl** [appium/appium#17801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, I'm unable to establish a connection to Windows appium driver V2.1.2.

### Expected Behavior

In the previous version of the appium server, I was able to establish a new session for the Windows driver 

### Minimal Reproducible Example

[StickeyNoteTest.txt](https://github.com/appium/appium/files/10047056/StickeyNoteTest.txt)

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): Appium v2.0.0-beta.46
  - Node.js version (output of `node --version`): v16.18.0
  - `npm` version (output of `npm --version`):  8.19.2
  - Last `appium` version which did _not_ exhibit the problem: Appium V2.0.0-Beta.45
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test: .NET client 5.0.0 Beta 2
- Real device or emulator/simulator: Windows

### Link to Appium Logs

https://gist.github.com/Dor-bl/cd29e97046660b89978b9b68c2bf1160

### Futher Information

[debug] [AppiumDriver@76ce] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{"platformName":"Windows","appium:app":"Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe!App","appium:automationName":"Windows","appium:deviceName":"WindowsPC"}]}]
[debug] [AppiumDriver@76ce] Event 'newSessionRequested' logged at 1668862817186 (15:00:17 GMT+0200 (שעון ישראל (חורף)))
[Appium] Attempting to find matching driver for automationName 'Windows' and platformName 'Windows'
[Appium] The 'windows' driver was installed and matched caps.
[Appium] Will require it at C:\Users\Dor-B\.appium\node_modules\appium-windows-driver
[debug] [Appium] Requiring driver at C:\Users\Dor-B\.appium\node_modules\appium-windows-driver
[AppiumDriver@76ce] Appium v2.0.0-beta.46 creating new WindowsDriver (v2.1.2) session
[AppiumDriver@76ce] Checking BaseDriver versions for Appium and WindowsDriver
[AppiumDriver@76ce] Appium's BaseDriver version is 8.7.3
[AppiumDriver@76ce] WindowsDriver's BaseDriver version is 8.7.3
[debug] [WindowsDriver@292b] Creating session with W3C capabilities: {
[debug] [WindowsDriver@292b]   "alwaysMatch": {
[debug] [WindowsDriver@292b]     "platformName": "Windows",
[debug] [WindowsDriver@292b]     "appium:app": "Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe!App",
[debug] [WindowsDriver@292b]     "appium:automationName": "Windows",
[debug] [WindowsDriver@292b]     "appium:deviceName": "WindowsPC"
[debug] [WindowsDriver@292b]   },
[debug] [WindowsDriver@292b]   "firstMatch": [
[debug] [WindowsDriver@292b]     {}
[debug] [WindowsDriver@292b]   ]
[debug] [WindowsDriver@292b] }
[WindowsDriver@292b (5197c2c9)] Session created with session id: 5197c2c9-4cd1-47f2-a47f-e1b17dee9e17
[WindowsDriver@292b (5197c2c9)] Spawning 'C:\Program Files\Windows Application Driver\WinAppDriver.exe' with args: ["4724/wd/hub"]
[debug] [WindowsDriver@292b (5197c2c9)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@292b (5197c2c9)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body[WindowsDriver@292b (5197c2c9)] connect ECONNREFUSED 127.0.0.1:4724
[debug] [WindowsDriver@292b (5197c2c9)] Windows Application Driver listening for requests at: http://127.0.0.1:4724/wd/hub
[debug] [WindowsDriver@292b (5197c2c9)] Press ENTER to exit.
[debug] [WindowsDriver@292b (5197c2c9)] Matched '/status' to command name 'getStatus'
[debug] [WindowsDriver@292b (5197c2c9)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body[debug] [WindowsDriver@292b (5197c2c9)] ==========================================
[debug] [WindowsDriver@292b (5197c2c9)] GET /wd/hub/status HTTP/1.1
[debug] [WindowsDriver@292b (5197c2c9)] Accept: application/json, */*
[debug] [WindowsDriver@292b (5197c2c9)] Connection: keep-alive
[debug] [WindowsDriver@292b (5197c2c9)] Content-Type: application/json; charset=utf-8
[debug] [WindowsDriver@292b (5197c2c9)] Host: 127.0.0.1:4724
[debug] [WindowsDriver@292b (5197c2c9)] User-Agent: appium
[WindowsDriver@292b (5197c2c9)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError

**Comment by Dor-bl** [comment]
@mykola-mokhnach could be related to Issue: https://github.com/appium/appium/issues/17779?

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach could be related to Issue: #17779?

I don't think so. 
Try to downgrade the WAD server itself to the latest stable release: https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.1

**Comment by Dor-bl** [comment]
But I'm using the windows driver from here :https://github.com/appium/appium-windows-driver. 
The Microsoft one is not working on appium 2.0 due to W3C spec issues.

**Comment by mykola-mokhnach** [comment]
I am talking about the server part. The driver bundled with Appium is basically proxy to it

**Comment by Dor-bl** [comment]
So I should start the Microsoft server in addition to the appium one?
I don't recall it's being that way

**Comment by mykola-mokhnach** [comment]
Probably you don't understand how it works. windows driver downloads and installs a particular version of WAD server bundled with it. It is also possible to manually replace this server whenever necessary

**Comment by Dor-bl** [comment]
Thank you for the explanation. 
I'll try to downgrade and update.

**Comment by Dor-bl** [comment]
After the downgrade, session is connected.
