### ISSUE TITLE
bug: (Android) Appium does not detect all Webviews shown by chrome debugger

### ISSUE THREAD

**Issue by heychirag** [appium/appium#17800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running appium server with the following flags:

```
appium --allow-insecure=chromedriver_autodownload
```

I have noticed that Appium getContexts API doesn't lists all the Webviews I am otherwise able to see in the Chrome debugger window (`chrome://inspect`). It lists at most one Webview instead of all of them.

### Expected Behavior

getContexts API should return all Webviews visible on the Chrome debugger page.

### Minimal Reproducible Example

1) Use an app with multiple debuggable Webviews.
2) Open Chrome debugger (`chrome://inspect`) and you'll see multiple Webviews.
3) Use `driver.getContexts()` API and it will only return at most one Webview from the above list apart from the NATIVE context.

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 1.22.3
  - Node.js version (output of `node --version`): v12.22.12
  - `npm` version (output of `npm --version`): 6.14.16
  - Last `appium` version which did _not_ exhibit the problem: Not sure
- If running Appium Desktop, its version: N/A
- Appium driver(s) and their version(s): I am using `chromedriver_autodownload` flag
- Appium plugin(s) and their version(s): N/A
- Platform and version under test: macOS
- Real device or emulator/simulator: tried on Android 11, 12 and 13 emulators.

**Comment by mykola-mokhnach** [comment]
Maybe these are not webviews, but pages? Have you tried to list pages in the available view?

**Comment by mykola-mokhnach** [comment]
Also check with the latest available driver version in Appium2. Appium1 is not being maintained.

**Comment by heychirag** [comment]
Appium2 is still in beta. Why is it a good idea to use it?

**Comment by heychirag** [comment]
I also tried with Appium2 (did `npm install -g appium@next`). But still the same issue.

> Maybe these are not webviews, but pages? Have you tried to list pages in the available view?

How do I get all the pages within the Webview? These are separate URLs so I assume they are also separate Webviews right? Also what API to use for this? I didn't find any.

**Comment by mykola-mokhnach** [comment]
Try https://www.w3.org/TR/webdriver1/#get-window-handles

**Comment by heychirag** [comment]
Thanks! That worked like a charm.
