### ISSUE TITLE
we don't really need babel

### ISSUE THREAD

**Issue by boneskull** [appium/appium#17807]
Did I make this ticket already?

Given we're targeting v14, we don't actually need most of what Babel gives us. All we really need is to convert from ESM to CJS. I'm sure I've mentioned this before somewhere. 

Technically we don't even _need_ a build step, but I wouldn't recommend going all-in on pure ESM (at least not yet); such a move would require a nontrivial amount of refactoring and exploratory work around tests and mocks. 

So if we're just converting module formats, we don't have to use Babel. ideally I'd like to trim down the toolchain weight and increase build performance. Possible candidates to replace it include (but are not limited to):

- TypeScript; handy because it's already in the toolchain
- esbuild - very fast. pretty easy. uses native modules though. does not do polyfills etc. 
- ncc - basically just compresses an entire package into a single file. don't recall if we can get it to _not_ bundle dependencies
- rollup - only advantage over esbuild is that it's probably more mature

I've got varying levels of experience with all of these, and would probably recommend trying TS or esbuild. 

If we do go with esbuild, then how exactly we use it with Mocha is unclear to me, but I'm sure it's possible. whatever we use should allow us to run source files directly and provide reasonable stack traces like what we have now. 

there seem to be plenty of tools like this nowadays. any others we should consider?

low priority.

**Comment by boneskull** [comment]
also maybe something we could use to solve #17746. some sort of all-in-one thing? problem is that most of these tools are very web-centric, e.g. vite

**Comment by mykola-mokhnach** [comment]
could you please mention what are pros and cons of using babel for the current setup?
what would be the transition strategy if we decide to get rid of it. There are plenty of different packages under Appium github org.
We probably need to get rid of these that are not maintained anymore first (move them to boneyard maybe)?

**Comment by jlipps** [comment]
I'd be in favour of jettisoning babel for tsc if we can make it happen without a huge amount of work. having it as the default toolchain makes it easier to incrementally add typescript to various places, which in my mind would be preferable than the ts-in-comments situation we have now (though i wouldn't advocate for a full rewrite to TS since it seems necessary).

**Comment by boneskull** [comment]
> could you please mention what are pros and cons of using babel for the current setup?

I'm not sure how easily I can split this into "pros" and "cons", since it's all tradeoffs, but:

- We can use any stage-4 syntax regardless of our supported Node.js versions.
- Babel lets us (for better or worse) mix and match ESM and CJS in a Node.js context.
- Currently, we don't appear to be using any syntax unsupported by our supported Node.js versions.
- Babel provides no polyfills.  Note there's a difference between _new syntax_ and _new APIs_.  For example, `Object.entries()` isn't present in Node.js v10.  Babel would not help us with that.
- We do not transpile "down" to ES5, so in practice, Babel isn't doing much other than converting ESM to CJS.
- Babel is popular and mature.

Regarding TS in particular, we don't even have to start writing TS (I'd rather not, but I guess I could live with it) to use the compiler.  We should, in theory, be able to swap it out, and it can handle converting ESM to CJS.  I am under the impression that the code `tsc` generates isn't as smart/good as Babel, but maybe that doesn't apply to us, given we're not transpiling down.

The transition strategy needn't be done at all once.  I would recommend `@appium/gulp-plugins`, which uses Babel, not change.  Any driver using `@appium/gulp-plugins` can continue to do so insofar as we want to keep maintaining it (which we don't).

The steps to migrate from Babel to _x_ are TBD, of course.  But there's no reason to think it needs to happen all at once.  It needn't even happen all at once in the monorepo.

Unmaintained packages are another issue entirely.

**Comment by boneskull** [comment]
@jlipps @mykola-mokhnach Here's an example of building `appium` (just `appium`--not the entire monorepo) with `tsc` instead of `babel`

**Comment by boneskull** [comment]
While there are other packages like `esbuild` that absolutely have speed advantages, I'd be fine with `tsc` just to simplify the workflow.

**Comment by jlipps** [comment]
build speed hasn't been a huge issue so far. simplicity is probably worth it.
