### ISSUE TITLE
[xcuitest-driver] Allow usage of private development key without keychains

### ISSUE THREAD

**Issue by PowerOfCreation** [appium/appium#17818]
The [xcuitest-driver](https://github.com/appium/appium-xcuitest-driver) needs access to the private development key, which is a .p12 file. There are many issues with keychains in a CI environment, which is why it is recommended to create a new keychain https://github.com/appium/appium-xcuitest-driver/blob/master/README.md#real-device-security-settings. I have two issues with this.

**The naming** 
The description is not clear. It says a capability called `keychainPath` needs to be provided. For me that suggests, this is the path to a **keychain**. [Further down](https://github.com/appium/appium-xcuitest-driver/blob/master/README.md#webdriveragent) it says it is a path to a .p12 **file**.  I'm honestly not sure which one of the two is true and if it's only the path to the keychain, how does it determine which .p12 file to use in case there are multiple? If it is the full path to a .p12 file then I suggest renaming the parameter to `developmentKeyPath`.

**Forcing the usage of keychain**
In multiple scenarios and different software's I always face the same issue again and again. Keychains are super annoying to deal with especially when working with CI. Why not just allow the parameter to point to a file outside of a keychain and only when `keychainPassword` is set as well, then try to unlock the keychain. I think it would save so many headaches to make the whole keychain usage optional. It would be the users choice to use it and because the keychain password needs to be given around as a parameter and is even displayed in plain text in the appium log, I don't think just having it lying around as file would raise any additional security concerns and if so then the user can simply use a keychain.

**Comment by mykola-mokhnach** [comment]
Thanks for the feedback. 
We do not use the above feature neither test it. I assume you could define the best way to apply the corresponding capabilities and/or their names because you use it in everyday work and can test/verify the changes. Feel free to create a PR to the driver.

> is even displayed in plain text in the appium log

you could always define custom --log-filters to scrub plain-text passwords from the output

**Comment by PowerOfCreation** [comment]
> Thanks for the feedback. We do not use the above feature neither test it. I assume you could define the best way to apply the corresponding capabilities and/or their names because you use it in everyday work and can test/verify the changes. Feel free to create a PR to the driver.
> 
> > is even displayed in plain text in the appium log
> 
> you could always define custom --log-filters to scrub plain-text passwords from the output

Thank you for your quick response. I have since then tried many options and got the real device setup in a CI environment to work without those capabilities, so I won't be in a spot to test them any further.

One thing that caught me completely off-guard though and I didn't see any note about this in the documentation is the fact, that the Apple Account with the given xOrgId needs to be connected to the used pc. Having all the certificates and provisioning profiles installed/in the keychain is not enough.

For anyone stumbling across this:
I can only suggest to avoid creating additional keychains. This usually comes with a huge rattail. Starting with keychain access being not very reliable and the CLI commands are partially not working as intended. Another issue is that codesign does ask for the password for all existing keychains despite the fact that the certificates are in a different already unlocked keychain. So you might be using a custom keychain, but codesign will still ask for the password to unlock the login keychain. In a CI environment any graphical prompt popping up and asking for a password is deadly. The allow always or disabling keychain timeout is also not very reliable. It is much easier to just use the login keychain in combination with fastlane and match. Unlock the keychain at each CI run with unlock_keychain. The keychain password can be saved as an environment variable in the .bash_profile for example.

**Comment by mykola-mokhnach** [comment]
Perhaps this would be a good idea to decorate the above info about CI setup as a document and add it under https://github.com/appium/appium-xcuitest-driver/tree/master/docs

Would you mind creating such document @PowerOfCreation ?

**Comment by PowerOfCreation** [comment]
I did create a documentation, which covers the points I have raised.
https://github.com/appium/appium-xcuitest-driver/pull/1454
