### ISSUE TITLE
Is there any way to improve the performance of WDA? 

### ISSUE THREAD

**Issue by mwakizaka** [appium/appium#17810]
Using the script below, I compared the performance of find element API between WDA v4.8.0 and v4.7.0 with Xcode 13.4.1.
The result indicated that both median and average of the response time of the API increased around 30%.

| WDA version | v4.7.0 | v4.8.0 | v4.10.2 |
| ---                  | ---      | ---      | ---        |
| average (ms) | 160.9  | 209.27 | 211.13  |
| median (ms)  | 160    | 208    | 209     |

I believe https://github.com/appium/WebDriverAgent/commit/1c1a8060ffcaeef59b537da62c7a37dd0c6b9eb7 since WDA v4.8.0 is essential to support Xcode 14.X, it is a great work. 
The comparison is conducted with Xcode 13.4.1 because WDA 4.7.0 doesn't work with Xcode 14.X. 
Therefore, I'm not sure it can be also slow when it comes to using WDA 4.8.0 with Xcode 14.X (I have no idea to compare the performance with Xcode 14.X). 
But, I would love to ask if there's a chance to improve the performance at WDA side. 

### Minimal Reproducible Example

```
const wdio = require("webdriverio");

const options = {
  logLevel: 'silent',
  port: 4723,
  capabilities: {
    'appium:automationName': "XCUITest",
    'appium:platformName': "iOS",
    'appium:platformVersion': "15.5",
    'appium:deviceName': "iPhone 12",
    'appium:app': "/Users/mwakizaka/Documents/10_projects/magic-pod-repo/apps/UIKitCatalog.zip",
    'appium:newCommandTimeout': "60",
    'appium:useNewWDA': true,
  }
}

const main = async () => {
  let driver;
  try {
    driver = await wdio.remote(options);
    for (let i = 0; i < 100; i++) {
      await driver.$("~Activity Indicators");
      await driver.$("~Alert Views");
      await driver.$("~Buttons");
      await driver.$("~Date Picker");
      await driver.$("~Image View");
      await driver.$("~Page Control");
      await driver.$("~Picker View");
      await driver.$("~Progress Views");
      await driver.$("~Search");
      await driver.$("~Segmented Controls");
    }
    
    console.log("The end");
  } catch( err ) {
    console.log(err);
  } finally {
    if (driver) await driver.deleteSession();
  }
}
main();
```

### Environment

- Operating system: macOS 12.6
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.46
  - Node.js version (output of `node --version`): v16.13.2
  - `npm` version (output of `npm --version`): 8.1.2
  - Last `appium` version which did _not_ exhibit the problem: N/A
- If running Appium Desktop, its version: N/A
- Appium driver(s) and their version(s): xcuitest@4.12.2 with WDA4.10.2, xcuitest@4.7.3 with WDA4.8.0, xcuitest@4.7.2 with WDA4.7.0 [installed (NPM)]
- Appium plugin(s) and their version(s): N/A
- Platform and version under test: iOS 15.5
- Real device or emulator/simulator: simulator
- Xcode: `Xcode 13.4.1 Build version 13F100`

### Link to Appium Logs

- [WDA4.7.0_uicatalog_appium_elements_perf.log](https://gist.github.com/mwakizaka/b837068b58ea00c2e92ced9c9f96b426)
- [WDA4.8.0_uicatalog_appium_elements_perf.log](https://gist.github.com/mwakizaka/3cbfba91a5dd392d77a36d5194f8ef73)
- [WDA4.10.2_uicatalog_appium_elements_perf.log](https://gist.github.com/mwakizaka/3161d9eacbc90df446a4174990d9359e)

### the performance comparison
[perf_WDA4.8.0_vs_WDA4.7.0.xlsx](https://github.com/appium/appium/files/10057193/perf_WDA4.8.0_vs_WDA4.7.0.xlsx)

**Comment by mykola-mokhnach** [comment]
Thanks for detailed results @mwakizaka 

Did you test the performance all locator types or only the accessibility id one?

I think I could try to apply some internal optimisations, but they would require some testing from your side. Would you help me there?

**Comment by mykola-mokhnach** [comment]
You could start comparing the current results with https://github.com/appium/WebDriverAgent/pull/630
Please let me know if these changes bring noticeable improvements

**Comment by mwakizaka** [comment]
> Did you test the performance of all locator types or only the accessibility id one?

I tried only accessibility id. I'll try the others as well.

> I think I could try to apply some internal optimisations, but they would require some testing from your side. Would you help me there?

Sure!

**Comment by mwakizaka** [comment]
Thank you for checking my issue and sorry to be late. I checked WDA 4.10.3. However, I couldn't confirm the noticeable improvements. Anyway, here's the result.

| WDA version | v4.7.0 | v4.8.0 | v4.10.3 |
| ---                  | ---      | ---      | ---        |
| average (ms) | 174.878 | 217.3 | 214.952 |
| median (ms)  | 175 | 218 | 217 |

fyi, I used the following script. (I used `derivedDataPath` capability instead to use WDA4.10.3) (BTW, is there any way to get WDA version while running appium test?)
```
const wdio = require("webdriverio");

const options = {
  logLevel: 'silent',
  port: 4723,
  capabilities: {
    'appium:automationName': "XCUITest",
    'appium:platformName': "iOS",
    'appium:platformVersion': "15.5",
    'appium:deviceName': "iPhone 12",
    'appium:app': "/Users/mwakizaka/Documents/10_projects/magic-pod-repo/apps/UIKitCatalog.zip",
    'appium:newCommandTimeout': "60",
    'appium:derivedDataPath': "<path/to/WebDriverAgent/DerivedData>",
  }
}

const main = async () => {
  let driver;
  try {
    driver = await wdio.remote(options);
    for (let i = 0; i < 100; i++) {
      await driver.$("~Activity Indicators");
      await driver.$("~Alert Views");
      await driver.$("~Buttons");
      await driver.$("~Date Picker");
      await driver.$("~Image View");
      await driver.$("~Page Control");
      await driver.$("~Picker View");
      await driver.$("~Progress Views");
      await driver.$("~Search");
      await driver.$("~Segmented Controls");
    }
    
    console.log("The end");
  } catch( err ) {
    console.log(err);
  } finally {
    if (driver) await driver.deleteSession();
  }
}
main();
```

- [WDA4.10.3_uicatalog_appium_elements_perf.log](https://github.com/appium/appium/files/10067314/WDA4.10.3_uicatalog_appium_elements_perf.log)
- [WDA4.8.0_uicatalog_appium_elements_perf.log](https://github.com/appium/appium/files/10067316/WDA4.8.0_uicatalog_appium_elements_perf.log)
- [WDA4.7.0_uicatalog_appium_elements_perf.log](https://github.com/appium/appium/files/10067315/WDA4.7.0_uicatalog_appium_elements_perf.log)
- [perf_WDA4.8.0_vs_WDA4.10.3.xlsx](https://github.com/appium/appium/files/10067313/perf_WDA4.8.0_vs_WDA4.10.3.xlsx)

I'll try the other locators tomorrow.

**Comment by mykola-mokhnach** [comment]
If the patch is not published then the only way to test it is to replace local WDA sources manually with the ones checked out from the corresponding branch. Also make sure the new WDA binary has been built and deployed to the device under test before running the test (perhaps, cleaning of xcodebuild caches would be  a good idea)

**Comment by mwakizaka** [comment]
Thank you for your advice and the second optimization. I added `appium:useNewWDA: true` capability in order to make sure switching WDA version in an iOS simulator under test. Here's the performance check result for https://github.com/appium/WebDriverAgent/pull/632. One interesting thing to me here is that xpath didn't get affected by https://github.com/appium/WebDriverAgent/commit/1c1a8060ffcaeef59b537da62c7a37dd0c6b9eb7

- accessibility id

| WDA version  | v4.7.0  | v4.8.0  | v4.10.4 |
| ---          | ---     | ---     | ---     |
| average (ms) | 172.392 | 218.749 | 218.921 |
| median (ms)  | 173     | 218     | 218     |

- ios class chain

| WDA version  | v4.7.0  | v4.8.0  | v4.10.4 |
| ---          | ---     | ---     | ---     |
| average (ms) | 168.532 | 216.394 | 216.401 |
| median (ms)  | 171     | 216     | 216     |

- ios predicate string

| WDA version  | v4.7.0  | v4.8.0  | v4.10.4 |
| ---          | ---     | ---     | ---     |
| average (ms) | 172.349 | 220.523 | 221.029 |
| median (ms)  | 174     | 221     | 220     |

- xpath

| WDA version  | v4.7.0  | v4.8.0  | v4.10.4 |
| ---          | ---     | ---     | ---     |
| average (ms) | 918.033 | 914.174 | 923.587 |
| median (ms)  | 914     | 912     | 918     |

- the evidence (appium log files and the excel file): [20221123.zip](https://github.com/appium/appium/files/10072958/20221123.zip)

**Comment by mykola-mokhnach** [comment]
I've recently merged https://github.com/appium/WebDriverAgent/pull/634

For now I don't have any more ideas on how to improve the performance of predicates lookup (since basically every strategy eventually maps to a predicate, except of class name and xpath ones). Perhaps, it would require much thorough investigation with detailed timings measurements of each particular method call in the corresponding WDA implementation.

**Comment by mwakizaka** [comment]
Thank you for your optimizations. Here's the performance check result for https://github.com/appium/WebDriverAgent/pull/634, unfortunately I couldn't find noticeable improvement though.

- accessibility id

| WDA version  | v4.7.0  | v4.8.0  | v4.10.6 |
| ---          | ---     | ---     | ---     |
| average (ms) | 172.154 | 217.544 | 222.224 |
| median (ms)  | 173     | 217     | 221     |

- ios class chain

| WDA version  | v4.7.0  | v4.8.0  | v4.10.6 |
| ---          | ---     | ---     | ---     |
| average (ms) | 170.639 | 216.236 | 217.81  |
| median (ms)  | 170     | 216     | 217     |

- ios predicate string

| WDA version  | v4.7.0  | v4.8.0  | v4.10.6 |
| ---          | ---     | ---     | ---     |
| average (ms) | 174.558 | 220.706 | 219.723 |
| median (ms)  | 174     | 220     | 221     |

- the evidence: [20221124.zip](https://github.com/appium/appium/files/10082012/20221124.zip)

> it would require much thorough investigation with detailed timings measurements of each particular method call in the corresponding WDA implementation.

I'd try to dive into WDA implementation and find which part of WDA makes find element API slow.

**Comment by mwakizaka** [comment]
I dived into WDA v4.7.0 and WDA v4.10.8. I guess the performance issue happened around https://github.com/appium/WebDriverAgent/pull/596/commits/32940078bb1349c744dfb363ef9c8a909e796a2c#diff-92c6ecbf454aa866d6a05c2d5b2d380b77f2a44906ec3a4bf7f185ceb7f10c44R108. is there room for improving the query to be more performant?

fyi: I locally built WDA with the following logging at `WebDriverAgentLib/Utilities/FBXCodeCompatibility.m`
```
- (XCUIElement *)fb_firstMatch
{
  [FBLogger logFmt: @"FBConfiguration.useFirstMatch: %d", FBConfiguration.useFirstMatch];
  XCUIElement* match = FBConfiguration.useFirstMatch
    ? self.firstMatch
    : self.fb_allMatches.firstObject;
  [FBLogger log:@"match start"];
  XCUIElement* result = [match exists] ? match : nil;
  [FBLogger log:@"match end"];
  return result;
}

- (NSArray<XCUIElement *> *)fb_allMatches
{
  [FBLogger logFmt: @"FBConfiguration.boundElementsByIndex: %d", FBConfiguration.boundElementsByIndex];
  return FBConfiguration.boundElementsByIndex
    ? self.allElementsBoundByIndex
    : self.allElementsBoundByAccessibilityElement;
}
```
and tried a predicate string locator as
```
curl -X POST $JSON_HEADER \
-d "{\"using\":\"predicate string\",\"value\":\"type == 'XCUIElementTypeStaticText' && name == 'Activity Indicators'\"}" \
$DEVICE_URL/session/$SESSION_ID/element
```

the performance result seems different as

- WDA v4.7.0 took 0.16 second
```
2022-11-25 12:17:10.688717+0900 WebDriverAgentRunner-Runner[45608:532537] FBConfiguration.useFirstMatch: 0
2022-11-25 12:17:10.688857+0900 WebDriverAgentRunner-Runner[45608:532537] FBConfiguration.boundElementsByIndex: 0
    t =    17.31s Get all elements bound by accessibility element for: Elements matching predicate '(wdType == "XCUIElementTypeStaticText" AND wdName == "Activity Indicators") AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)'
    t =    17.31s     Requesting snapshot of accessibility hierarchy for app with pid 31874
    t =    17.39s     Find: Descendants matching type Any
    t =    17.39s     Find: Elements matching predicate '(wdType == "XCUIElementTypeStaticText" AND wdName == "Activity Indicators") AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)'
2022-11-25 12:17:10.771569+0900 WebDriverAgentRunner-Runner[45608:532537] match start
    t =    17.39s Checking existence of `"Activity Indicators" StaticText`
    t =    17.40s     Requesting snapshot of accessibility hierarchy for app with pid 31874
    t =    17.46s     Find: Descendants matching type Any
    t =    17.46s     Find: Elements matching predicate '(wdType == "XCUIElementTypeStaticText" AND wdName == "Activity Indicators") AND (1 == 1 OR identifier == 0 OR frame == 0 OR value == 0 OR title == 0 OR label == 0 OR elementType == 0 OR enabled == 0 OR placeholderValue == 0 OR selected == 0)'
    t =    17.47s     Find: Identity Binding
2022-11-25 12:17:10.846299+0900 WebDriverAgentRunner-Runner[45608:532537] match end
```

- WDA v4.10.8 took 0.20 second
```
2022-11-25 12:13:32.946915+0900 WebDriverAgentRunner-Runner[44766:527806] FBConfiguration.useFirstMatch: 0
2022-11-25 12:13:32.947052+0900 WebDriverAgentRunner-Runner[44766:527806] FBConfiguration.boundElementsByIndex: 0
    t =    62.90s Get all elements bound by accessibility element for: Elements matching predicate 'BLOCKPREDICATE(0x6000028dea30)'
    t =    62.91s     Requesting snapshot of accessibility hierarchy for app with pid 31874
    t =    63.00s     Find: Descendants matching type Any
    t =    63.00s     Find: Elements matching predicate 'BLOCKPREDICATE(0x6000028dea30)'
2022-11-25 12:13:33.053334+0900 WebDriverAgentRunner-Runner[44766:527806] match start
    t =    63.01s Checking existence of `"Activity Indicators" StaticText`
    t =    63.01s     Requesting snapshot of accessibility hierarchy for app with pid 31874
    t =    63.10s     Find: Descendants matching type Any
    t =    63.10s     Find: Elements matching predicate 'BLOCKPREDICATE(0x6000028dea30)'
    t =    63.10s     Find: Identity Binding
2022-11-25 12:13:33.149424+0900 WebDriverAgentRunner-Runner[44766:527806] match end
```

**Comment by mykola-mokhnach** [comment]
Perhaps block predicates are just slower in general. For now I'm out of ideas on how we could make that process faster

**Comment by mykola-mokhnach** [comment]
Maybe try https://github.com/appium/WebDriverAgent/pull/638
It could be a breaking change if my initial assumption is wrong, but it should improve the actual performance for sure

**Comment by mwakizaka** [comment]
Thank you so much for your change! it looks so performant on both Xcode 13.4.1 and Xcode 14.1

## Xcode 13.4.1 (intel mac)
- accessibility id

| WDA version  | v4.7.0  | v4.8.0  | v4.10.10 |
| ---          | ---     | ---     | ---      |
| average (ms) | 179.442 | 224.113 | 175.863  |
| median (ms)  | 176     | 223     | 179      |

- ios class chain

| WDA version  | v4.7.0  | v4.8.0  | v4.10.10 |
| ---          | ---     | ---     | ---      |
| average (ms) | 173.257 | 228.385 | 175.56   |
| median (ms)  | 174     | 220     | 175      |

- ios predicate string

| WDA version  | v4.7.0  | v4.8.0  | v4.10.10 |
| ---          | ---     | ---     | ---      |
| average (ms) | 178.808 | 222.912 | 175.001  |
| median (ms)  | 178     | 222     | 177      |

## Xcode 14.1 (m1 mac)

- accessibility id

| WDA version  | v4.8.0  | v4.10.10 |
| ---          | ---     | ---      |
| average (ms) | 132.332 | 114.943  |
| median (ms)  | 129     | 112      |

- ios class chain

| WDA version  | v4.8.0  | v4.10.10 |
| ---          | ---     | ---      |
| average (ms) | 132.156 | 115.006  |
| median (ms)  | 130     | 112      |

- ios predicate string

| WDA version  | v4.8.0  | v4.10.10 |
| ---          | ---     | ---      |
| average (ms) | 135.916 | 115.527  |
| median (ms)  | 132     | 113      |

**Comment by mykola-mokhnach** [comment]
Good, I'm happy these patches did the job. 
Closing the issue as fixed.
