### ISSUE TITLE
bug:when using chromedriver_autodownload feature, I cannot change chromedriver_cdnurl

### ISSUE THREAD

**Issue by linpy00** [appium/appium#17821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### When using chromedriver_autodownload feature, **the appium cannot connect chromedriver server.** The error is as follows:
![image](https://user-images.githubusercontent.com/37139086/203713522-c1271061-1e23-4837-9b0e-30c25f9f077c.png)

### **The browser also cannot visit the page(https://chromedriver.storage.googleapis.com). The error is as follows:**
![image](https://user-images.githubusercontent.com/37139086/203713631-72f61518-d0b7-4bba-bf58-ea19d759f5e8.png)

**So I add 【chromedriver_cdnurl=https://registry.npmmirror.com/binary.html?path=chromedriver/ 】in the .npmrc file, but it doesn't work. When auto downloading chromedriver, the appium still visits https://chromedriver.storage.googleapis.com.**

Does anyone encounter this problem?How to solve it?
Thank you~

### Expected Behavior

Hope to change chromedriver_cdnurl 

### Minimal Reproducible Example

content of .npmrc file
chromedriver_cdnurl=https://registry.npmmirror.com/binary.html?path=chromedriver/

### Environment

- Operating system: mac os 10.15.7
  - Node.js version (output of `node --version`):v18.12.1
  - `npm` version (output of `npm --version`):  8.19.2
- Appium verison: 2.0.0-beta.46
- Appium driver(s) and their version(s): uiautomator2@2.10.2
- Real device or emulator/simulator: android10  webview

**Comment by KazuCocoa** [comment]
Did you tried to configure it via environment variable? `CHROMEDRIVER_CDNURL`

Appium 2.0 will work only with environment variable as https://github.com/appium/appium/blob/master/packages/appium/docs/en/guides/migrating-1-to-2.md#bangbang-chromedriver-installation-flags

**Comment by linpy00** [comment]
Thanks a lot. It works for me!
