### ISSUE TITLE
com.apple.mobilesafari does not exist in the list of Simulator processes

### ISSUE THREAD

**Issue by Sanoop-PM** [appium/appium#17825]
After updating XCode to 14.1, with the iOS 16 or 16.1 simulator, Safari is getting launched but not navigating to the URL. I am getting below error:
"Error: Mobile Safari cannot open 'http://0.0.0.0:4723/welcome' after 25.933s. Its process com.apple.mobilesafari does not exist in the list of Simulator processes"

Whereas if I try with older version iOS 15.5, then Safari is getting launched and getting navigated to the URL successfully 

Appium: 1.22.3

Code:
DesiredCapabilities caps = new DesiredCapabilities();
			caps.setCapability("deviceName", "iPad (10th generation)");
			caps.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
			caps.setCapability(MobileCapabilityType.PLATFORM_VERSION, "16.1");
			caps.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
			caps.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
			caps.setCapability("autoAcceptAlerts", true);
			AppiumDriver<WebElement> driver = new AppiumDriver<WebElement>(new URL("http://127.0.0.1:4723/wd/hub"), caps);
			driver.get("https://www.google.com/");

[appium-server-logs.txt](https://github.com/appium/appium/files/10082459/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
Appium 1 is not maintained anymore. Please try the most recent XCUIText driver supplied with Appium2

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by balakiran432** [comment]
Facing similar kind of issue when browserName capability is set to Safari.
URL is only getting launched when browserName Capability is removed or commented but throws "An element could not be located on the page using the given search parameters." error for the very first web element that i want to interact with.
FYI, applied enough Wait for the website to launch and detect the Web Element.
@mykola-mokhnach , Can you please help me with this issue. Thanks!!

**Comment by Sanoop-PM** [comment]
@balakiran432 : After upgrading to Appium2 it worked for me. Please try the same

**Comment by balakiran432** [comment]
Issue still persists even after upgrading Appium to Appium 2.0.0-beta.55 and XCUITest drivers.
@Sanoop-PM , Can you please share the link to which WebDriverAgent you have used for building the Xcode and installing it in the simulator? That might help me.....

**Comment by balakiran432** [comment]
@Sanoop-PM , Xcode build s getting failed if i tried to use default WebDriverAgent with the error present in the attached screenshot. Any idea on why this is happening? Thanks a lot for your responses!!
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/51917675/220119700-564fb2af-99a2-42ac-9cbf-85d8116e5d21.png">

**Comment by Sanoop-PM** [comment]
@balakiran432 : Not sure what's the exact reason for this error.  It's better to raise a new request so that all will have a track of it.

**Comment by AvallaSD** [comment]
Just faced same problem

"ios": {
      "deviceKey": "iOS_Simulator",
      "capabilities": {
        "browserName": "safari",
        "platformName": "iOS",
        "automationName": "XCUITest",
        "wdaLaunchTimeout": 90000,
        "wdaStartupRetries": 4,
        "wdaStartupRetryInterval": 60000,
        "noReset": true,
        "isHeadless": false,
        "simulatorStartupTimeout": 300000,
        "safariAllowPopups": true
      }
    }
    


> @balakiran432 : Not sure what's the exact reason for this error. It's better to raise a new request so that all will have a track of it.

Did ypu find the solution?

**Comment by AvallaSD** [comment]
> Closed because of no response
My appium version is 2.0.0-beta.66 and i still face the problem

**Comment by jlipps** [comment]
For old and closed issues if you think something is not fully resolved, it's usually best to create a new issue and provide all the requested logs etc so an investigation can be done. Link this issue when you do.
