### ISSUE TITLE
bug:  Android produce blank screenshot / black video within GitHub actions

### ISSUE THREAD

**Issue by kopax-polyconseil** [appium/appium#17837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run tests within a CI, I upload an artifacts that contains screenshots and videos of failed test. 

This is how it look like for the screenshots
![image](https://user-images.githubusercontent.com/77674046/204536866-98d297de-90b4-4716-b725-0879831baa0f.png)

This is the video shot in CI:
https://user-images.githubusercontent.com/77674046/204561099-597271b2-9bcd-4b68-ba41-e7273432b2b6.mp4

This is the video log: [wdio-0-0-Video-reporter.log](https://github.com/appium/appium/files/10114136/wdio-0-0-Video-reporter.log)

Both work locally.

### Expected Behavior

We expect to have proper screenshot of our app

### Minimal Reproducible Example

- github action workflow: https://github.com/pass-culture/pass-culture-app-native/blob/8ee2e682c8b0d299e8aa64586efc627a9b6b65ab/.github/workflows/e2e-android-app.yml
- code to do screenshot: https://github.com/pass-culture/pass-culture-app-native/blob/8ee2e682c8b0d299e8aa64586efc627a9b6b65ab/e2e/config/wdio.shared.conf.ts#L159-L174

### Environment

- Operating system: macos-12 github action
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.46
  - Node.js version (output of `node --version`): v18.7.0
  - `yarn` version (output of `yarn --version`):  1.22.15
  - Last `appium` version which did _not_ exhibit the problem:  NA
- Appium driver(s) and their version(s): - uiautomator2@2.9.0 [installed (NPM)]
- Appium plugin(s) and their version(s): NA
- Platform and version under test: Android 10.0 Nexus6P
- Real device or emulator/simulator: emulator

### Link to Appium Logs

https://github.com/pass-culture/pass-culture-app-native/actions/runs/3573959420/jobs/6008640936

**Comment by mykola-mokhnach** [comment]
Please provide the full server log. I assume there should be some issue with your CI script...

**Comment by mykola-mokhnach** [comment]
Also, have you tried to run the automation script locally? Was it able to take a screenshot?

**Comment by kopax-polyconseil** [comment]
yes locally it worked fine, I dropped the logs, you can't access them ?

**Comment by kopax-polyconseil** [comment]
archive with server logs [logs_19232.zip](https://github.com/appium/appium/files/10113903/logs_19232.zip)

**Comment by mykola-mokhnach** [comment]
It also makes sense to check with app developers. Some apps deliberately set FLAG_SECURE on views, which prevents screenshots to be taken

**Comment by kopax-polyconseil** [comment]
I am the app developer and we do not set it.

**Comment by kopax-polyconseil** [comment]
I believe this is an issue because we do not have video as we do not have any display... Because it's in a CI. Some hardware acceleration problem I believe. I doubt the adb screenshots will work...

**Comment by kopax-polyconseil** [comment]
Hmm, weird, on iOS, I am able to take screenshots in CI without problem

**Comment by jlipps** [comment]
on iOS, presumably you are running on mac? i wonder if you ran your android tests on mac as well if the displays would be set correctly for screenshot to work. headless linux CI envs often pose problems with android emulators.

**Comment by kopax-polyconseil** [comment]
The project is public and I linked the workflow, but here is the exact line https://github.com/pass-culture/pass-culture-app-native/blob/8ee2e682c8b0d299e8aa64586efc627a9b6b65ab/.github/workflows/e2e-android-app.yml#L65

So yes it run on macos

**Comment by jlipps** [comment]
ah ok, i guess that's not the issue.

**Comment by mykola-mokhnach** [comment]
I assume it's an issue with Github runner itself. Found a duplicate: https://github.com/wix/Detox/issues/3578

Consider reporting it to Github

**Comment by kopax-polyconseil** [comment]
Thanks for the duplicate, I reported the issue to GitHub https://github.com/actions/runner/issues/2287 

Perhaps we can keep this open for those also interested, for tracking in order to gather the effort ?

**Comment by mykola-mokhnach** [comment]
I usually pin issues in such case, although this only makes sense if we get the same issues reported by multiple people. For now it was only a single report so far.

**Comment by raven123** [comment]
@kopax-polyconseil can you please help me how to record video for android emulator on macos in github actions?
