### ISSUE TITLE
bug: Appium cannot find elements on Android 13 in Chrome

### ISSUE THREAD

**Issue by bapszy** [appium/appium#17836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

I am a tester of a hybrid app, that has some links that opens the chrome and opens a website there. 
We use Appium 2.0 currently and I try to write tests on Android 13 (API 33)

I found that Appium (and also inspector) cannot find element with locator style:
`//android.widget.TextView[@text='Privacy Policy'] `
as before, but I need to switch to WEBVIEW_chrome context and use a web style locator like
 `//*[contains(text(), 'Privacy Policy')]` 
to find that element.

I don't know if this is intentional or this is a bug, as the documentation for Appium 2.0 is not ready, but this is really annoying as we want to support several Android versions and now we need a big if for all places to be able to use Android 13. 

### Expected Behavior

It would be great if we could use the native locators in Chrome as before on Android 13

### Minimal Reproducible Example

    @AndroidFindBy(xpath = "//android.widget.TextView[@text='Privacy Policy']"
    private WebElement `textPrivacyPolicy;
`wait.until(ExpectedConditions.visibilityOf(textPrivacyPolicy));`

### Environment

- Operating system: Win, MacOS
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.46
  - Node.js version (output of `node --version`): v19.0.0
  - `npm` version (output of `npm --version`): 8.19.2
  - Last `appium` version which did _not_ exhibit the problem: 1.22
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): uiautomator2@2.10.0
- Appium plugin(s) and their version(s):
- Platform and version under test: Android 13 (API 33)
- Real device or emulator/simulator: Emulator

**Comment by bapszy** [comment]
The thing is, that I see the element in appium inspector, I see the attributes, the text, class, package, everything, but if I try to search for the element with the above mentioned locator it doesn't find it

**Comment by mykola-mokhnach** [comment]
Try https://github.com/appium/appium-uiautomator2-driver#elements-cannot-be-found

**Comment by jlipps** [comment]
@bapszy this suggests there's a race condition in your finding logic. make sure the elements are fully loaded and present before finding them. explicit waits are the recommended way to do this.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
