### ISSUE TITLE
We are seeing Un lock screen on trying to unlock Android device using ((AndroidDriver) driver).unlockDevice();

### ISSUE THREAD

**Issue by SharathVarganti** [appium/appium#17849]
We are seeing Blank unlock screen on trying to unlock device which is having swipe pattern as lock screen pattern

Samsung A50 (Device Model)

Appium v1.22.3 

Refer attached screenshot

Due to this seeing  element is not found as in the background still seeing screen is unlocked.

Exception in thread "main" org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'VIN0020ALTVTVCQ', ip: '192.168.1.4', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_202'
Driver info: io.appium.java_client.android.AndroidDriver

* Element info: {Using=id, value= cannot be disclosed}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:61)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:372)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementById(DefaultGenericMobileDriver.java:69)
	at io.appium.java_client.AppiumDriver.findElementById(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementById(AndroidDriver.java:1)
	at AppiumProject.Sharath.LaunchApplication.main(LaunchApplication.java:199)

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description

**Comment by SharathVarganti** [comment]
Due to th

> * HttpCommandExecutor

I added screenshot as well what we are facing  for swipe lock pattern

**Comment by mykola-mokhnach** [comment]
The provided information is not enough. Please clearly describe steps to reproduce the issue, the actual and the expected result. Also, the server log is required

**Comment by SharathVarganti** [comment]
> The provided information is not enough. Please clearly describe steps to reproduce the issue, the actual and the expected result. Also, the server log is required

What info. needed as  I mentioned what I am trying to do  and error I got 

We are seeing unlock screen for swipe lock pattern on trying to unlock it with  unlockdevice method 

Got response with status 404: {"sessionId":"2ae48eec-ab59-4d49-9a92-9c44bb9b0c5f","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:70)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:266)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:260)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann

seeing blank unlock screen on trying to unlock and in background it opened the app and could not find element to enter MDN

If u see the screenshot attached u can get it for unlocking on having swipe pattern
![Uploading Unlock_Screen_SwipeLockPattern.PNG…]()

**Comment by SharathVarganti** [comment]
> The provided information is not enough. Please clearly describe steps to reproduce the issue, the actual and the expected result. Also, the server log is required

What info. needed as  I mentioned what I am trying to do  and error I got 

We are seeing unlock screen for swipe lock pattern on trying to unlock it with  unlockdevice method 

Got response with status 404: {"sessionId":"2ae48eec-ab59-4d49-9a92-9c44bb9b0c5f","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:70)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:266)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:260)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann

seeing blank unlock screen on trying to unlock and in background it opened the app and could not find element to enter MDN

If u see the screenshot attached u can get it for unlocking on having swipe pattern

**Comment by SharathVarganti** [comment]
> The provided information is not enough. Please clearly describe steps to reproduce the issue, the actual and the expected result. Also, the server log is required

What info. needed as  I mentioned what I am trying to do  and error I got 

We are seeing unlock screen for swipe lock pattern on trying to unlock it with  unlockdevice method 

Got response with status 404: {"sessionId":"2ae48eec-ab59-4d49-9a92-9c44bb9b0c5f","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:70)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:266)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:260)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann

seeing blank unlock screen on trying to unlock and in background it opened the app and could not find element to enter MDN

If u see the screenshot attached u can get it for unlocking on having swipe pattern

**Comment by mykola-mokhnach** [comment]
If an element could not be found then it is most likely not there. Check https://github.com/appium/appium-uiautomator2-driver#elements-cannot-be-found for troubleshooting

**Comment by mykola-mokhnach** [comment]
Also consider using the most recent UIA2 driver version available int Appium2. Appium 1 is not maintained anymore

**Comment by SharathVarganti** [comment]
> If an element could not be found then it is most likely not there. Check https://github.com/appium/appium-uiautomator2-driver#elements-cannot-be-found for troubleshooting

Element is there as I am trying to unlock device with swipe lock pattern showing the screen which is attached if we click on device back from that screen seeing still swipe not happened so app. opened in the background but element is not visible in Android if element is not visible then we see that error so issue with swipe lock pattern not element getting find .

**Comment by mykola-mokhnach** [comment]
device unlocking might not work if a custom locking screen is used, this is pretty common in customised firmwares. The recent driver version also includes screen unlock using adb, which might help, but you won't be able to use it if you don't update.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
