### ISSUE TITLE
use commitlint

### ISSUE THREAD

**Issue by boneskull** [appium/appium#17844]
Might be worthwhile to adopt [commitlint](https://www.npmjs.com/package/@commitlint/cli).  I have it running on a couple of my projects and works well.

While we're in there, we should swap out `pre-commit` for `husky` given the former hasn't been published in six (6) years.

**Comment by jlipps** [comment]
👍

**Comment by boneskull** [comment]
We would likely want to disable some of the default rules w/r/t line length, since those aren't part of the spec.

**Comment by jlipps** [comment]
yeah i love this. could it also run in CI in case someone somehow bypasses the local checks?
