### ISSUE TITLE
create scheduled build against "current" Node.js

### ISSUE THREAD

**Issue by boneskull** [appium/appium#17859]
### Discussed in https://github.com/appium/appium/discussions/17858

<div type='discussions-op-text'>

<sup>Originally posted by **boneskull** December  1, 2022</sup>
The next publish of Appium, **v2.0.0-beta.47** (and its dependencies) will **drop support for various versions of Node.js**.  

The versions dropped include:

- v14.0.0 to v14.17.0
- v16.0.0 to v16.13.0

These version ranges are exclusive (e.g., v14.17.0 is the minimum supported version).

Please note:

- Versions older than v14.0.0 and _odd-numbered Node.js releases_ continue to be unsupported.
- "Unsupported" doesn't necessarily mean "it won't work"--it just means Appium does not claim compatibility nor does it test on these Node.js versions.  Appium cannot address any future issues specific to these versions.

See [the Node.js Release WG repo](https://github.com/nodejs/release) for more information about the Node.js release cadence.
</div>

* * *

While we don't need to test every single build against the current Node.js version, I think it's worth doing on a daily or weekly schedule.  What's in "current" will eventually become LTS, so it's probably a good idea to know if there are any breaking changes coming.

**Comment by jlipps** [comment]
Is there a way to get this feedback without marking a build as failed if this fails?

**Comment by boneskull** [comment]
@jlipps Why?

**Comment by jlipps** [comment]
i mean the overall set of builds, not this particular build. would be nice to merge a green PR even if it breaks a future not yet supported version of node. then we can go and look at it without feeling like the build randomly broke on some random PR.

**Comment by boneskull** [comment]
> i mean the overall set of builds, not this particular build. would be nice to merge a green PR even if it breaks a future not yet supported version of node. then we can go and look at it without feeling like the build randomly broke on some random PR.

What I'm proposing is that this runs on a schedule--not per PR.  So it won't run during a PR.  I mean, we _could_ do that I guess, but I'm wary of expanding the build matrix further.

**Comment by mykola-mokhnach** [comment]
I do not see much point in scheduled jobs unless somebody is monitoring their results and takes actions on possible failures. If there is no such person then it also makes no sense to spend time building that feature. 
Btw GH Actions's `actions/setup-node@v3` plugin allows to simply set node version as `lts` and the latest one will be selected. In drivers though I use more advanced scripting: https://github.com/appium/appium-uiautomator2-driver/blob/f066e68e60bdac5d80beec9bca3da6044824bfc1/.github/workflows/unit-test.yml#L7

**Comment by boneskull** [comment]
I mean, yes, someone (usually @jlipps) will get a notification if the build fails.  We run FOSSA checks on a schedule as well.

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
