### ISSUE TITLE
Unable to start the Chrome app in Android Emulator on mac

### ISSUE THREAD

**Issue by kushalchitransh** [appium/appium#17856]
Issue: While trying to automate the mweb scenario ie trying to open a url in chrome browser of Android emulator on Android Studio in MAC we are getting following error

ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","am","instrument","-w","-e","disableAnalytics",true,"io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8200/wd/hub/status] with no body
[WD Proxy] socket hang up
[Instrumentation] io.appium.uiautomator2.server.test.AppiumUiAutomator2Server:
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8200/wd/hub/status] with no body
[WD Proxy] socket hang up
[Instrumentation] Error in startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server):
[Instrumentation] java.lang.ExceptionInInitializerError
[Instrumentation] 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotServer.(MjpegScreenshotServer.java:41)
[Instrumentation] 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotServer.(MjpegScreenshotServer.java:35)
[Instrumentation] 	at io.appium.uiautomator2.server.ServerInstrumentation.startMjpegServer(ServerInstrumentation.java:241)
[Instrumentation] 	at io.appium.uiautomator2.server.test.AppiumUiAutomator2Server.startServer(AppiumUiAutomator2Server.java:31)
[Instrumentation] 	... 27 trimmed
[Instrumentation] Caused by: java.lang.IllegalStateException: UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@88fa1aealready registered!
[Instrumentation] 	at android.os.Parcel.createException(Parcel.java:2079)
[Instrumentation] 	at android.os.Parcel.readException(Parcel.java:2039)
[Instrumentation] 	at android.os.Parcel.readException(Parcel.java:1987)
[Instrumentation] 	at android.app.IUiAutomationConnection$Stub$Proxy.connect(IUiAutomationConnection.java:427)
[Instrumentation] 	at android.app.UiAutomation.connect(UiAutomation.java:241)
[Instrumentation] 	at android.app.Instrumentation.getUiAutomation(Instrumentation.java:2160)
[Instrumentation] 	at androidx.test.uiautomator.UiDevice.getUiAutomation(UiDevice.java:1129)
[Instrumentation] 	at androidx.test.uiautomator.QueryController.(QueryController.java:95)
[Instrumentation] 	at androidx.test.uiautomator.UiDevice.(UiDevice.java:109)
[Instrumentation] 	at androidx.test.uiautomator.UiDevice.getInstance(UiDevice.java:261)
[Instrumentation] 	at io.appium.uiautomator2.utils.Device.getUiDevice(Device.java:33)
[Instrumentation] 	at io.appium.uiautomator2.model.internal.CustomUiDevice.(CustomUiDevice.java:70)
[Instrumentation] 	at io.appium.uiautomator2.model.internal.CustomUiDevice.getInstance(CustomUiDevice.java:80)
[Instrumentation] 	at io.appium.uiautomator2.server.mjpeg.MjpegScreenshotStream.(MjpegScreenshotStream.java:43)
[Instrumentation] 	... 32 more
[Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.
[Instrumentation] INSTRUMENTATION_CODE: 0
[Instrumentation] The process has exited with code 0
[UiAutomator2] The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
[UiAutomator2] Deleting UiAutomator2 session
[UiAutomator2] Deleting UiAutomator2 server session
[UiAutomator2] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'DELETE /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8200 
[ADB] Running '/Users/automation/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:8200'
[UiAutomator2] Restoring hidden api policy to the device default configuration
[ADB] Running '/Users/automation/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[BaseDriver] Event 'newSessionStarted' logged at 1669876378690 (00:32:58 GMT-0600 (Central Standard Time))
[W3C] Encountered internal error running command: Error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
[W3C]     at Object.errorAndThrow (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
[W3C]     at UiAutomator2Server.startSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/uiautomator2.js:247:13)
[W3C]     at AndroidUiautomator2Driver.startUiAutomator2Session (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:416:5)
[W3C]     at AndroidUiautomator2Driver.createSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-uiautomator2-driver/lib/driver.js:229:7)
[W3C]     at AppiumDriver.createSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/lib/appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 8242 ms - 859

Just checking if there is any security settings in IOS thats hampering this 

MAC Configuration: Mac mini (2018) Monterey 3.2 GHz 6-Core Intel Core i7
Appium Version : Appium v1.22.3
Java : 14
Android Studio Version
Code Snippet:

import com.google.common.collect.ImmutableMap;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import java.net.MalformedURLException;
import java.net.URL;
public class Dummy {

    AndroidDriver androidDriver;
    public void openChromeBrowser() throws MalformedURLException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "Android Test");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
        capabilities.setCapability("appium:chromeOptions", ImmutableMap.of("w3c", false));
        capabilities.setCapability("automationName", "UiAutomator2");
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Chrome");
        capabilities.setCapability("noReset", true);
        //capabilities.setCapability("adbExecTimeout", "50000");
        androidDriver = new AndroidDriver(new URL("http://localhost:4723/wd/hub"), capabilities);
        androidDriver.get("https://southwest.com/");
    }

    public static void main(String[] args) throws MalformedURLException {
        Dummy aps = new Dummy();
        aps.openChromeBrowser();
    }
}

.ZSHRC Configuration:

#setting path for nodejs
export NODEJS_HOME=/usr/local/bin

#setting JAVA Home
export JAVA_HOME=$(/usr/libexec/java_home)
export PATH=$JAVA_HOME/bin:$PATH

export JAVA_HOME_8=/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk

#Android Home
export ANDROID_HOME=/Users/automation/Library/Android/sdk
export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/platform-tools/bin:$PATH
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/tools/bin:$PATH
export PATH=$PATH:$JAVA_HOME_8/bin

export PATH=$ANDROID_HOME/build-tools/30.0.2:$PATH
export PATH=$ANDROID_HOME/build-tools/30.0.2/bin:$PATH

Appium Doctor logs

 ~ % appium-doctor --android
WARN AppiumDoctor [Deprecated] Please use appium-doctor installed with "npm install @appium/doctor --location=global"
info AppiumDoctor Appium Doctor v.1.16.2
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 18.12.1
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/automation/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home
info AppiumDoctor    Checking adb, android, emulator, apkanalyzer
info AppiumDoctor      'adb' is in /Users/automation/Library/Android/sdk/platform-tools/adb
info AppiumDoctor      'android' is in /Users/automation/Library/Android/sdk/tools/android
info AppiumDoctor      'emulator' is in /Users/automation/Library/Android/sdk/emulator/emulator
info AppiumDoctor      'apkanalyzer' is in /Users/automation/Library/Android/sdk/cmdline-tools/latest/bin/apkanalyzer
info AppiumDoctor  ✔ adb, android, emulator, apkanalyzer exist: /Users/automation/Library/Android/sdk
info AppiumDoctor  ✔ 'bin' subfolder exists under '/Library/Java/JavaVirtualMachines/jdk-14.0.2.jdk/Contents/Home'
info AppiumDoctor ### Diagnostic for necessary dependencies completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor ### Diagnostic for optional dependencies starting ###
WARN AppiumDoctor  ✖ opencv4nodejs cannot be found.
WARN AppiumDoctor  ✖ ffmpeg cannot be found
info AppiumDoctor  ✔ mjpeg-consumer is installed at: /usr/local/lib. Installed version is: 2.0.0
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
WARN AppiumDoctor  ✖ gst-launch-1.0 and/or gst-inspect-1.0 cannot be found
info AppiumDoctor ### Diagnostic for optional dependencies completed, 4 fixes possible. ###
info AppiumDoctor 
info AppiumDoctor ### Optional Manual Fixes ###
info AppiumDoctor The configuration can install optionally. Please do the following manually:
WARN AppiumDoctor  ➜ Why opencv4nodejs is needed and how to install it: http://appium.io/docs/en/writing-running-appium/image-comparison/
WARN AppiumDoctor  ➜ ffmpeg is needed to record screen features. Please read https://www.ffmpeg.org/ to install it
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it
WARN AppiumDoctor  ➜ gst-launch-1.0 and gst-inspect-1.0 are used to stream the screen of the device under test. Please read https://appium.io/docs/en/writing-running-appium/android/android-screen-streaming/ to install them and for more details
info AppiumDoctor 
info AppiumDoctor ###
info AppiumDoctor 
info AppiumDoctor Bye! Run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor 

[appium-server-logs.txt](https://github.com/appium/appium/files/10130030/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
Please use the most recent driver version available with Appium 2. Appium 1 is not maintained anymore. Also make sure the old server app is deleted from the device under test before trying the fresh driver (you could also run `appium driver run uiautomator2 reset`)

**Comment by mykola-mokhnach** [comment]
Closed because of no response
