### ISSUE TITLE
appium-xcuitest-driver: want to get elements only of current view.

### ISSUE THREAD

**Issue by AbhishekDhiman01** [appium/appium#17875]
Current I'm getting all elements of screen that makes appium refresh rate very slow and make test execution very very slow. Like In contact screen it will get ids of all contact instead of contact present on current view. Is there any setting that will limit the elements in DOM or will just get elements of current view.

**Comment by mykola-mokhnach** [comment]
Unfortunately xcuitest driver does not provide such feature.
https://appiumpro.com/editions/20-making-your-appium-tests-fast-and-reliable-part-2-finding-elements may be useful to check.
Please use Appium forum to ask questions.
