### ISSUE TITLE
[Feat]:I'm doing an Android automation test, and there is a test case that is to long press the power key for 8 seconds. The phone should restart. I have tried a lot of methods and none of them work, including adb commands. Among them, driver.long_press_keycode() in appium is the closest, but unfortunately the long press time of this method cannot be set. Can anyone help me?

### ISSUE THREAD

**Issue by a6865517** [appium/appium#17888]
Please help me！

**Comment by mykola-mokhnach** [comment]
You could use [W3C actions](https://appiumpro.com/editions/46-sending-arbitrary-keystrokes-with-the-actions-api) to inject key codes with given durations. Android key codes could be found at https://developer.android.com/reference/android/view/KeyEvent

Please use Appium forum to ask questions
