### ISSUE TITLE
after switching chromedriver_cndurl，appium can connect to the url, but it still cannot download chromedriver

### ISSUE THREAD

**Issue by linpy00** [appium/appium#17880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

chromedriver_url = "http://npm.taobao.org/mirrors/chromedriver/"
when downloading chromedriver, it gets errors in terminal:
![image](https://user-images.githubusercontent.com/37139086/205807003-673ff317-c261-4f55-a0f2-331339a2d157.png)
appium server log:

![image](https://user-images.githubusercontent.com/37139086/205808697-f3226b16-e034-4090-8695-351aae8558ac.png)

I wonder if the autodownload mechanic needs more info with chromedrivercdn_url. From the logs, it failed because it lacks some xml file.

### Expected Behavior

appium auto download chromedriver successfully

### Minimal Reproducible Example

no

### Environment

Operating system: mac os 10.15.7
Node.js version (output of node --version):v18.12.1
npm version (output of npm --version): 8.19.2
Appium verison: 2.0.0-beta.46
Appium driver(s) and their version(s): uiautomator2@2.10.2
Real device or emulator/simulator: android10 webview

**Comment by KazuCocoa** [comment]
Did you try out environment variable?
https://appium.github.io/appium/docs/en/2.0/guides/migrating-1-to-2/

**Comment by linpy00** [comment]
Yes,I have set the env and Appium visits the cdn_url successfully.
![image](https://user-images.githubusercontent.com/37139086/205822363-f2cf032f-8b63-415c-87a3-ad6f5e7226eb.png)

**Comment by KazuCocoa** [comment]
What the result of the cdn url?
Usually the response of http://chromedriver.storage.googleapis.com/ is XML. http://npm.taobao.org/mirrors/chromedriver/ was redirected to https://registry.npmmirror.com/binary.html?path=chromedriver/ on my local, so I'm not sure if the URL is a valid CDN.

**Comment by linpy00** [comment]
It is the same on my local. I try the cdn_url on appium official website [https://npmmirror.com/mirrors/chromedriver](https://npmmirror.com/mirrors/chromedriver) the result is also incorrect. So Appium should provide  a valid CDN?

![image](https://user-images.githubusercontent.com/37139086/205826296-7920381c-6cc7-46d2-8a09-0f4a49103ead.png)
[https://npmmirror.com/mirrors/chromedriver](https://npmmirror.com/mirrors/chromedriver) is redirected to [https://cdn.npmmirror.com/binaries/chromedriver](https://cdn.npmmirror.com/binaries/chromedriver)
![image](https://user-images.githubusercontent.com/37139086/205826392-375ceba0-6480-45f9-badd-bc763e687ced.png)

**Comment by KazuCocoa** [comment]
it is an example url to use another URL. No driver found is expected then.
As http://chromedriver.storage.googleapis.com/, Appium expects the URL by default, but we provide a way to customize the URL for some cases.

**Comment by linpy00** [comment]
So we have to use the default url, since  the cdn_urls we got here don't work out.

**Comment by mykola-mokhnach** [comment]
In order to properly fetch available chromedrivers info the given CDN must reply to `Accept: application/xml, */*` requests and return the actual mapping XML similar to the one returned by the original URL.

**Comment by linpy00** [comment]
Ok, thanks a lot!
