### ISSUE TITLE
bug: [iOS] Element with locator was not found from webdriver even it is exists (only on real device iOS 16.1/16.2beta)

### ISSUE THREAD

**Issue by StsiapanPal** [appium/appium#17889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is a different behaviour on same screen on simulator ios 16.1 iphone 12 and real device (SauceLabs)  ios 16.1/16.2beta iPhone 12. 
1. On simulator I am able to get element by AppiumBy.iOSClassChain - _**/XCUIElementTypeCell[`name == 'address'`]/XCUIElementTypeTextView[`name = 'detail_1'`]_, and test passes. Here is screenshot from appium inspector:

![Screenshot 2022-12-07 at 16 49 15](https://user-images.githubusercontent.com/94680206/206205145-5e168a5c-ee16-4831-96ea-18c816d1bc11.png)

2. On real device ios 16.1/16.2beta only (iOS 15.6 issue is not reproducible) test is failing on same screen with error message _Element with locator: AppiumBy.iOSClassChain: **/XCUIElementTypeCell[`name == 'address'`]/XCUIElementTypeTextView[`name = 'detail_1'`] was not found from webdriver / root element after 20 seconds_. Here is screenshot from appium inspector:

<img width="807" alt="Screenshot 2022-12-07 at 17 23 03" src="https://user-images.githubusercontent.com/94680206/206205679-6f91e975-c345-4e3b-80e5-0c18c371e5bf.png">

### Expected Behavior

On real device element should be found by AppiumBy.iOSClassChain: **/XCUIElementTypeCell[`name == 'address'`]/XCUIElementTypeTextView[`name = 'detail_1'`] and test should pass

### Minimal Reproducible Example

driver.findElement(AppiumBy.iOSClassChain("**/XCUIElementTypeCell[`name == 'address'`]/XCUIElementTypeTextView[`name = 'detail_1'`]"));

### Environment

- Operating system: mac
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.44
  - Node.js version (output of `node --version`): v17.4.0
  - `npm` version (output of `npm --version`):  8.3.1
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator: real device iOS 16.1

### Link to Appium Logs

https://gist.github.com/StsiapanPal/ab82d6de6510cb29614f9d48d0f0f583

**Comment by mykola-mokhnach** [comment]
Elements tree is returned to us by XCTest. Consider reporting the issue to Apple.

**Comment by StsiapanPal** [comment]
@mykola-mokhnach Please tell me if this is the right place to report a issue with XCTest to Applehttps://github.com/apple/swift-corelibs-xctest/issues?

**Comment by mykola-mokhnach** [comment]
I would usually try https://developer.apple.com/bug-reporting/
Not sure how much Apple is responsive to bug reports though 🤷
