### ISSUE TITLE
bug: app dont launch when the test session is started 

### ISSUE THREAD

**Issue by HamzaMiz** [appium/appium#17883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i launch test with testng.Xml file 
the sesssion is created 
the app is not launched stays in background 
i check the console , appium is start the fetch the elements 

Before i used the capability : 
forceAppLaunch to launch the app 
this cap is deprecated on appium 2 

### Expected Behavior

the appium launch when session is started 

### Minimal Reproducible Example

 case "ios":
                // For this platform, the name is set to ios
                capabilities.setCapability("appium:platformName", platform);
                capabilities.setCapability("appium:platformVersion", platformVersion); //Replace this with your ios version
                capabilities.setCapability("appium:deviceName", deviceName); //Replace this with your simulator/device
                capabilities.setCapability("appium:xcodeOrgId", "5YUC5L4ER7");
                capabilities.setCapability("appium:xcodeSigningId", "iPhone Developer");
                capabilities.setCapability("appium:automationName", "XCUITest");

                capabilities.setCapability("appium:udid", udid);
                capabilities.setCapability("appium:fullReset", false);
                capabilities.setCapability("appium:noReset", true);
                capabilities.setCapability("appium:forceAppLaunch", true);
                capabilities.setCapability("appium:–session-override",true);
                capabilities.setCapability(IOSMobileCapabilityType.WDA_LOCAL_PORT,"8200");

                capabilities.setCapability("appium:instrumentApp", false);
                capabilities.setCapability("appium:autoAcceptAlerts", true); // May produce errors on Apple ID alerts
                capabilities.setCapability("appium:bundleID", DataClass.appIOS);
 

### Environment

- Operating system: mac 12.6.1
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): appium@2.0.0-beta.46
  - Node.js version (output of `node --version`):v19.1.0
  - `npm` version (output of `npm --version`):  9.1.2
  - Last `appium` version which did _not_ exhibit the problem: appium 1  lastest version
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test: Ios 15.7
- Real device or emulator/simulator: real device

### Link to Appium Logs

https://gist.github.com/HamzaMiz/be75ea4a3798b687f7eeb226fac11015

### Futher Information

i dont use app path , i use bundleID

**Comment by mykola-mokhnach** [comment]
> this cap is deprecated on appium 2

Where it is stated this capability is deprecated?

**Comment by mykola-mokhnach** [comment]
you could also try to run https://github.com/appium/appium-xcuitest-driver#mobile-activateapp in order to activate the app

**Comment by HamzaMiz** [comment]
i will try that   and tell u the result ,  and on the logs last time 2 days ago , it written on the logs , forceapplaunch its not recognized by appium

**Comment by HamzaMiz** [comment]
https://discuss.appium.io/t/appium-suddenly-stop-setting-up-and-tearing-down-app/34682/6 i have the same problem as this guy , i always used forceapplaunch , itwas working fine

**Comment by mykola-mokhnach** [comment]
> i will try that and tell u the result , and on the logs last time 2 days ago , it written on the logs , forceapplaunch its not recognized by appium

I assume this is because of the typo in `bundleId` capability. Capability names are case sensitive

**Comment by HamzaMiz** [comment]
i have tried it , it opens the app , but the problem is if the app is on foreground , and the test restarts , the app its not killed 
and relaunched  , the app stays on foreground 
i have                 
capabilities.setCapability("appium:shouldTerminateApp",true);
capabilities.setCapability("appium:noReset", false);
capabilities.setCapability("appium:fullReset", false);
capabilities.setCapability("appium:forceAppLaunch", true);

**Comment by mykola-mokhnach** [comment]
Please provide the updated server log

**Comment by HamzaMiz** [comment]
https://gist.github.com/HamzaMiz/701def4e2c2baddb4785869a6fa0c33f

**Comment by mykola-mokhnach** [comment]
> [XCUITestDriver@30cd] The following capabilities were provided, but are not recognized by Appium:
> [XCUITestDriver@30cd]   bundleID

I don't see the cap name being fixed

**Comment by HamzaMiz** [comment]
aha i see let me retest sorry

**Comment by HamzaMiz** [comment]
thanks its fixed nice catch
