### ISSUE TITLE
bug: "Command 'Windows Application Driver' not found. Is it installed?" Yes, it is installed

### ISSUE THREAD

**Issue by CRYPTO-7CA** [appium/appium#17890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using Appium Inspector to access a Windows Application (which was written on Qt using C++ QWidgets without QML). Appium server is not finding my Windows Application Driver (which I have is on version 1.2.1). I do have it. See Screenshot below.

![image](https://user-images.githubusercontent.com/61016421/206249979-0f557cfd-e514-4fb7-83d7-8fe228bc898f.png)

### Expected Behavior

Appium inspector opens an Appium Session successfully and I can go ahead and inspect elements in the GUI App and do stuff like Send Keys.

Alternatively I would also consider using alternatives to Windows Application Driver since I have learned from [my other Github issue](https://github.com/appium/appium-desktop/issues/2134), that Microsoft has suspended maintaining Windows Application Driver.

### Minimal Reproducible Example

Capabilities used:
```
{
  "platformName": "Windows",
  "platformVersion": "10",
  "deviceName": "WindowsPC",
  "app": "C:\\Resources\\QtGuiApps\\GUI_Test_App\\V0.1.1\\GUI_Test_App.exe",
  "appium:automationName": "windows"
}
```

### Environment

- Operating system: Windows 10 Enterprise
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.46
  - Node.js version (output of `node --version`): v18.12.1
  - `npm` version (output of `npm --version`): 8.19.2
  - Last `appium` version which did _not_ exhibit the problem: 1.22.3
- If running Appium Desktop, its version: N/A
- Appium driver(s) and their version(s): 8.7.3
- Appium plugin(s) and their version(s): N/A
- Platform and version under test: Windows 10 Enterprise
- Real device or emulator/simulator: N/A

Using appium windows driver 2.2.2 installed through NPM.

### Link to Appium Logs

https://gist.github.com/CRYPTO-7CA/54c6cdda910c081e54e8a57d5bfd3e96

**Comment by jlipps** [comment]
```
[debug] [WinAppDriver] Loaded WinAppDriver path from the APPIUM_WAD_PATH environment variable: C:\Program Files (x86)\Windows Application Driver
```

You've set an invalid value in your environment. The program is not `C:\Program Files (x86)\Windows Application Driver`, it is `C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe`

**Comment by CRYPTO-7CA** [comment]
Ah, sorry, my bad. It looks for the System Environment Variable also, not User Environment Variable. Got it working now. Thanks for the swift response.
