### ISSUE TITLE
[Feat]: launch.json for debugging appium and its unit test from source

### ISSUE THREAD

**Issue by pacozaa** [appium/appium#17895]
I am trying to understand what's going on in the Appium source code. And it's really tough without debugging tool.

Maybe we can add one more configuration to `launch.json` for both debugging appium and its test

- So far I got one for debug appium.

```
{
      "type": "node",
      "request": "launch",
      "name": "launch appium",
      "skipFiles": ["<node_internals>/**"],
      "cwd": "${workspaceFolder}",
      "program": "${workspaceFolder}/packages/appium/index.js",
      "internalConsoleOptions": "openOnSessionStart",
    },
```
this one is working

- For the unit test, I tried this config

```
{
      "type": "node",
      "request": "launch",
      "name": "Mocha Tests",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "args": [
        "--no-timeouts",
        "--require",
        "ts-node/register",
        "${workspaceFolder}/packages/appium/test/unit/extension/*.spec.js"
      ],
    }
```

It doesn't work yet.

**Comment by mykola-mokhnach** [comment]
Monorepo tests are being executed by lerna: https://github.com/appium/appium/blob/d160e3959e583038150aab4a03643ca30766fba8/package.json#L62

While in each package the following mocha command is used:
https://github.com/appium/appium/blob/d160e3959e583038150aab4a03643ca30766fba8/packages/appium/package.json#L56

We h already  ave debug profiles defined for vscode: https://github.com/appium/appium/tree/master/.vscode

AFAIK @boneskull was editing them recently

**Comment by pacozaa** [comment]
@mykola-mokhnach `Test - Current File` in https://github.com/appium/appium/blob/master/.vscode/launch.json looks like what I am looking for.

However, when I run it I got `Uncaught Error Error: Cannot find module '@babel/register'
Require stack:`. Maybe there is an additional step to do.

The reason I ask is that the latest unit test is failing on my machine, more info here https://discuss.appium.io/t/the-unit-test-failed-at-8db0122/37971

**Comment by mykola-mokhnach** [comment]
It's probably related to the changes made in https://github.com/appium/appium/pull/17564
@boneskull is it also necessary to update this config as well?

**Comment by boneskull** [comment]
yes that vscode config is out-of-date. didn't think anyone was using it! it should no longer require `@babel/register`

also the Mocha Test Explorer plugin tends to work pretty well, but I don't think I've gotten it working with yet the new `ts-node` setup

**Comment by mykola-mokhnach** [comment]
> yes that vscode config is out-of-date. didn't think anyone was using it! it should no longer require `@babel/register`

could you please update this config according to the recent project state when you have time?
which IDE do you use for debugging btw?

**Comment by boneskull** [comment]
I'm using VSCode, but I only use its debugger on E2E tests, and I don't think I've had occasion to do that yet, so I overlooked it.  For unit tests I use Wallaby
