### ISSUE TITLE
bug: Setting relaxed-security in config file doesn't seem to work

### ISSUE THREAD

**Issue by ValzRon** [appium/appium#17906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I start the Appium server with this config yaml:
```
server:
  base-path: /wd/hub
  keep-alive-timeout: 800
  relaxed-security: true
  use-plugins:
    - device-farm
    - appium-dashboard
  plugin:
    device-farm:
      platform: android
```
I run `appium --config /path/to/my/config`. The documentation tells me to use --config-file, however that argument doesn't seem to work, whereas --config works.
The server starts like this:
```
[Appium] Welcome to Appium v2.0.0-beta.44
[Appium] Non-default server args:
[Appium] {
[Appium]   basePath: '/wd/hub',
[Appium]   keepAliveTimeout: 800,
[Appium]   usePlugins: [
[Appium]     'device-farm',
[Appium]     'appium-dashboard'
[Appium]   ]
[Appium] }
```
Relaxed-security seems to be missing and when I do shell commands, it notifies me that I have to allow-insecure adb_shell.
However if I start the server with the flag: `appium --relaxed-security --config /path/to/my/config` it looks correct:
```
[Appium] Welcome to Appium v2.0.0-beta.44
[Appium] Non-default server args:
[Appium] {
[Appium]   basePath: '/wd/hub',
[Appium]   keepAliveTimeout: 800,
[Appium]   relaxedSecurityEnabled: true,
[Appium]   usePlugins: [
[Appium]     'device-farm',
[Appium]     'appium-dashboard'
[Appium]   ]
[Appium] }
```
I tried this with a json also. Any ideas?

### Expected Behavior

Setting the boolean value `relaxed-security: true` inside the config should enable this feature and notify me inside the Appium Log.

### Minimal Reproducible Example

Start the Appium server using a JSON or YAML config with the argument `relaxed-security: true`

### Environment

- Operating system: Windows 10
- Appium 2.0.0-beta.44
- Appium driver(s) and their version(s): Espresso Driver 2.13.8
- Appium plugin(s) and their version(s): Appium-Dashboard 1.10 + Device-Farm 3.4.0

**Comment by mykola-mokhnach** [comment]
Is the issue also reproducible in the recently release beta.46?

**Comment by ValzRon** [comment]
yes, issue present there too.

**Comment by mykola-mokhnach** [comment]
@boneskull Could you please take a look there?

**Comment by boneskull** [comment]
I can't reproduce this.  Will need more info about the environment.  @ValzRon Please run both `appium --show-config` (which will be not quite correct; PR incoming for this) and `appium server --log-level=debug` and attach the results for both (drag `.txt` files into the comment editor)

Also: where do you see reference to `--config-file`?

**Comment by ValzRon** [comment]
Starting Appium with the config and --show-config : 

```
Appium Configuration

from defaults:

{
  address: '0.0.0.0',
  allowCors: false,
  basePath: '',
  callbackPort: 4723,
  debugLogSpacing: false,
  keepAliveTimeout: 600,
  localTimezone: false,
  loglevel: 'debug',
  logNoColors: false,
  logTimestamp: false,
  longStacktrace: false,
  noPermsCheck: false,
  port: 4723,
  relaxedSecurityEnabled: false,
  sessionOverride: false,
  strictCaps: false,
  plugin: { 'device-farm': { deviceTypes: 'both' } }
}

from config file at C:\Users\BudovskiyVal\IdeaProjects\appium-tests\appium-device-farm-config.yaml:

{
  server: {
    basePath: '/wd/hub',
    keepAliveTimeout: 800,
    relaxedSecurity: true,
    usePlugins: [ 'device-farm', 'appium-dashboard' ],
    plugin: { 'device-farm': [Object] }
  }
}

via CLI or function call:

{
  basePath: '/wd/hub',
  keepAliveTimeout: 800,
  usePlugins: [ 'device-farm', 'appium-dashboard' ]
}

final configuration:

{
  address: '0.0.0.0',
  port: 4723,
  showConfig: true,
  configFile: 'C:/Users/BudovskiyVal/IdeaProjects/appium-tests/appium-device-farm-config.yaml',
  basePath: '/wd/hub',
  keepAliveTimeout: 800,
  relaxedSecurity: true,
  usePlugins: [ 'device-farm', 'appium-dashboard' ],
  plugin: { 'device-farm': { platform: 'android', deviceTypes: 'both' } },
  allowCors: false,
  callbackPort: 4723,
  debugLogSpacing: false,
  localTimezone: false,
  loglevel: 'debug',
  logNoColors: false,
  logTimestamp: false,
  longStacktrace: false,
  noPermsCheck: false,
  relaxedSecurityEnabled: false,
  sessionOverride: false,
  strictCaps: false
}
```
Now what sticks out to me is that relaxedSecurity is true however relaxedSecurityEnabled is false, the latter one being true if i pass the flag --relaxed-security directly. Running this exact config results in:
`Encountered internal error running command: Error: Potentially insecure feature 'adb_shell' has not been enabled.`
which doesnt appear if I use the --relaxed-security flag in my CLI.

About the --config-file reference: this repo contains a guides section with a markdown file called config.md, it says to use --config-file, not sure if that is outdated.

**Comment by jlipps** [comment]
this is what's in our config schema:

```
        'relaxed-security': {
          default: false,
          description:
            'Disable additional security checks, so it is possible to use some advanced features, provided by drivers supporting this option. Only enable it if all the clients are in the trusted network and it\'s not the case if a client could potentially break out of the session sandbox. Specific features can be overridden by using "deny-insecure"',
          title: 'relaxed-security config',
          type: 'boolean',
          appiumCliDest: 'relaxedSecurityEnabled',
        },
```

try using `relaxedSecurityEnabled` as the key in your config instead?

**Comment by jlipps** [comment]
it might work if you used `relaxed-security` as the key but you're using `relaxedSecurity`, which doesn't appear to be a thing anywhere.

@boneskull should we add warnings to config keys that are unrecognized by the server or any installed driver/plugin?

**Comment by ValzRon** [comment]
> 

Tried both camel-case and hyphen, both results in `relaxedSecurityEnabled is not expected to be here!` inside the server log

**Comment by ValzRon** [comment]
> it might work if you used `relaxed-security` as the key but you're using `relaxedSecurity`, which doesn't appear to be a thing anywhere.
```
server:
  base-path: /wd/hub
  keep-alive-timeout: 800
  relaxed-security: true
....
```
Thats the key im using

**Comment by boneskull** [comment]
@ValzRon @jlipps 

`relaxed-security` is how it should appear in the config file.  `relaxedSecurityEnabled` is the stored property.

There's definitely something fishy; the final configuration should _not_ have both `relaxedSecurity` and `relaxedSecurityEnabled`.  I made some fixes to `--show-config` (which was inaccurate) in #17908 which will get published soon.  When that version is released, please upgrade Appium, and attach:

1. The output of `appium --show-config`
2. The contents of config file

**Comment by boneskull** [comment]
@ValzRon OK, we've published; please update and try again

**Comment by ValzRon** [comment]
> @ValzRon OK, we've published; please update and try again

This works, thank you!
