### ISSUE TITLE
bug: <Can't connect Appium inspector to Simulator : "xcodebuild failure: xcodebuild failed with code 65">

### ISSUE THREAD

**Issue by balantain** [appium/appium#17904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello. 
I’m testing a React native app on iOS and Android OS. I’m running my app on iOS Simulator and and use Appium 1.22.3-4 server with Appium inspector to inspect elements. **Everything worked fine for a long period of time**, but once I faced an issue while connecting appium inspector to iOS Simulator **“Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message”**
I can build an app on simulator, but if I’m not mistaken, previously there was a WebDriverAgent installed with it. And moreover, I found, that I can’t run Appium Inspector even with clear simulator. I've looked into the appium logs and found, that there are a lot of attempts to connect to **127.0.0.1:8100.** I've read a lot of threads, but the only solution was to update the current version of appium server. But I have the latest one installed with .dmg and the latest through the command line Please, help me to solve this issue, it really blocks my work!
I have: 
Xcode version 14.1
Appium 1.22.3-4 
Carthage 0.38.0

My capabilities:
{
  "platformName": "iOS",
  "appium:platformVersion": "16.1",
  "appium:deviceName": "iPhone 14 Pro",
  "automationName": "XCUITest",
  "appium:udid": "F39CFF57-2C98-4DDA-AB54-3C050960FC36"
}

### Expected Behavior

Appium Inspector is connected to device and WebDriverAgent is installed on it.

### Minimal Reproducible Example

1. Start iOS Simulator
2. Start Appium server
3. Start Appium inspector
4. Connect Inspector to simulator device

### Environment

- Operating system: MacOS Ventura 13.0.1 (22A400)
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 1.22.3
  - Node.js version (output of `node --version`): 16.18.0 (it is also reproducible with node 18.4.0)
  - `npm` version (output of `npm --version`): 8.19.2
  - Last `appium` version which did _not_ exhibit the problem: the problem was not reproducible at first and appeared with the same version of appium
- If running Appium Desktop, its version: 1.22.3-4
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator: ios simulator

### Link to Appium Logs

https://gist.github.com/balantain/364775a96dd806c2fb2f97ee9f8f1451

**Comment by balantain** [comment]
@mykola-mokhnach, thanks for the reply. Could you tell me, please, what is the latest XCode version pupported by appium 1, and where can I download Appium 2?

**Comment by jlipps** [comment]
@balantain here are the current [appium 2 docs](https://appium.github.io/appium/docs/en/2.0/) which contain getting started and migration instructions.
