### ISSUE TITLE
[Feat]: appium:reduceTransparency option to xcuitest driver

### ISSUE THREAD

**Issue by rerorero** [appium/appium#17905]
**Is your feature request related to a problem? Please describe.**
I sometimes get a screenshot with a keyboard having a strange color background (see below).
Apparently, this is because I run the simulator on a VM with poor machine resources. I've never seen this on a baremetal with the same configurations. Even on VMs, it not always happens.
(I use Appium + xcuitest-driver + mjpeg server)

**Describe the solution you'd like**
This is apparently due to the transparency of the UI. If I enable `Reduce Transparency` in the preference, this doesn't happen at all. I hope capabilities provide `appium:reduceTransparency` that allows switching `Reduce Transparency` in the accessibility preference.

**Describe alternatives you've considered**
none.

**Additional context**
Example screenshot.
<img width="544" alt="スクリーンショット 2022-12-09 20 25 51" src="https://user-images.githubusercontent.com/8503062/206692550-4ce7d06b-17ec-453d-bdfd-d095eec6815e.png">

**Comment by rerorero** [comment]
I started looking into it and submitted a PR https://github.com/appium/appium-ios-simulator/pull/342
If you're happy with this direction, I'd like to move forward.

**Comment by mykola-mokhnach** [comment]
The PR has been merged and published. Now you can add the necessary changes to xcuitest driver

**Comment by mykola-mokhnach** [comment]
The feature has been released. Thanks for working on it @rerorero
