### ISSUE TITLE
bug: Appium - Web view context for Windows App not working

### ISSUE THREAD

**Issue by Prabu-Mithran** [appium/appium#17914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are using the Appium automation framework to automate our hybrid App which supports Windows, iOS and Android platforms. Recently we are exploring webview context for windows app but we are not able to get webview inspector and also not able to fetch all the webview HTML DOM elements. 

Appium version used : v1.22.3-4
Platform : Windows

### Expected Behavior

Appium should allow to fetch all the webview HTML DOM elements in windows

### Minimal Reproducible Example

N/A

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
This is expected. Windows driver does not support context switching. Consider operating two different drivers on the client side
