### ISSUE TITLE
[installCertificate] driver execute_script downloads certificate but not installing it

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#17917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to install certificate with the following code:
```
        cer = '-----BEGIN CERTIFICATE-----rOFP9NZCKjpHxiP1EgbZ7Aj8OfTTXMHYzhVejNK6LBS2X-----END CERTIFICATE-----'
        message_bytes = cer.encode('ascii')
        base64_bytes = base64.b64encode(message_bytes)
        base64_message = base64_bytes.decode('ascii')

       response = self.driver_.execute_script(
            'mobile: installCertificate', {"content": base64_message}
        )
```
The action does working correctly and I am able to see that message on my iPhone device:
![Screenshot 2022-12-12 at 10 34 05](https://user-images.githubusercontent.com/5571230/206998501-ae923878-6fae-4668-9bf6-c27c3ca26d9a.png)

But it does not really help me in my scenario since that the profile is only being downloaded but not installed, in order to install I need to got to the iPhone settings and install the downloaded certificate manually 

### Expected Behavior

certificate should be downloaded and installed 

### Minimal Reproducible Example

```
        cer = '-----BEGIN CERTIFICATE-----rOFP9NZCKjpHxiP1EgbZ7Aj8OfTTXMHYzhVejNK6LBS2X-----END CERTIFICATE-----'
        message_bytes = cer.encode('ascii')
        base64_bytes = base64.b64encode(message_bytes)
        base64_message = base64_bytes.decode('ascii')

       response = self.driver_.execute_script(
            'mobile: installCertificate', {"content": base64_message}
        )
```

### Environment

- Operating system: Mac OS
- If running via `appium` 
  - Appium CLI version (output of `appium --version`):  Appium v2.0.0-beta.46
  - Node.js version (output of `node --version`):v16.13.0
  - `npm` version (output of `npm --version`): 8.1.0
  - Last `appium` version which did _not_ exhibit the problem: Never
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:real device iOS 16

### Link to Appium Logs

https://github.com/bwomsm1/AppiumLogs/blob/master/certificate.log

**Comment by bwomsm1** [comment]
@mykola-mokhnach can you please help me with that problem? 
**THANKS!**

**Comment by mykola-mokhnach** [comment]
Everything the driver does there is execution of [py-ios-device](https://github.com/YueChen-C/py-ios-device) utility:

> [debug] [35m[XCUITest][39m Executing /Library/Frameworks/Python.framework/Versions/3.9/bin/pyidevice profiles install --path /var/folders/xg/f91604_d5wl2t7l0_rrz4mw80000gn/T/20221112-9775-8j6rgx.zkyzn/cert.pem --udid 00008030-0012345A0C01402E --format json

Consider creating an issue for that tool if you have question regarding its functionality.
