### ISSUE TITLE
bug: Dart Observatory URI undefined

### ISSUE THREAD

**Issue by VGVTKH** [appium/appium#17919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While running tests at MAC mini (12.6.1 Monterey) for iOS (iPhone SE2 16.1.1) occurs error when trying to run dart observatory: 
E       selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Failed to connect 30 times. Aborting.
E       Stacktrace:
E       UnknownError: An unknown server-side error occurred while processing the command. Original error: Failed to connect 30 times. Aborting.
E           at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:956:9)
E           at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:435:35)

Log from appium: 

[35m[FlutterDriver][39m Attempt #1
[35m[FlutterDriver][39m Connecting to Dart Observatory: undefined
[35m[FlutterDriver][39m [object Object]
[35m[FlutterDriver][39m Check Dart Observatory URI undefined
[35m[FlutterDriver][39m Waiting 3 seconds before trying...
[35m[FlutterDriver][39m Attempt #2
[35m[FlutterDriver][39m Connecting to Dart Observatory: undefined
[35m[FlutterDriver][39m [object Object]
[35m[FlutterDriver][39m Check Dart Observatory URI undefined
[35m[FlutterDriver][39m Waiting 3 seconds before trying...
[35m[FlutterDriver][39m Attempt #3
[35m[FlutterDriver][39m Connecting to Dart Observatory: undefined
[35m[FlutterDriver][39m [object Object]
[35m[FlutterDriver][39m Check Dart Observatory URI undefined
[35m[FlutterDriver][39m Waiting 3 seconds before trying...
[35m[FlutterDriver][39m Attempt #4
[35m[FlutterDriver][39m Connecting to Dart Observatory: undefined
[35m[FlutterDriver][39m [object Object]
[35m[FlutterDriver][39m Check Dart Observatory URI undefined
[35m[FlutterDriver][39m Waiting 3 seconds before trying...

Flutter app, built in debug mode, all things needed for running it at iOS is done (cert singed, developer team added in cape act)

Script is able to install app, run WebDriverAgent, and then stop at the first app screen
Everything works at android, but not at ios

### Expected Behavior

Dart observatory is working

### Minimal Reproducible Example

@pytest.fixture(scope='session')
def appium_service():
    logger.info('Starting appium service on port: %s.', APPIUM_PORT)
    appium_service = AppiumService()
    with open(file='logs/appium.log', mode="w", encoding='utf8') as appium_logs:
        appium_service.start(
            args=['-p', str(APPIUM_PORT), '--base-path', '/wd/hub'],
            stdout=appium_logs,
            stderr=subprocess.STDOUT
        )
        yield
        logger.info('Stopping appium service.')
        appium_service.stop()

@pytest.fixture(scope='function')
def appium_driver_function(remote_run, appium_service):
    phone_udid = LOCAL_PHONE_ADDRESS
    url = f'http://127.0.0.1:{APPIUM_PORT}/wd/hub'
    logger.info('Starting webdriver')
    stf_capabilities = {
        'udid': f'{phone_udid}',
        'platformName': 'iOS',
        "platformVersion": "16.1.1",
        'appium:automationName': 'Flutter',
        'appium:autoAcceptAlerts': True,
        'appium:autoGrantPermissions': True,
        'xcodeOrgId': 'ID',
        'noReset': True,
        'xcodeSigningId': 'iPhone Developer',
        'app': APP_PATH,
        'appium:bundleId': "bundle.id",
        'appium:appPackage': APP_NAME,
        'appium:appActivity': '.MainActivity',
        'appium:clearSystemFiles': True
    }
    logger.info(url)
    driver = webdriver.Remote(url, stf_capabilities)
    yield driver
    driver.quit()
    logger.info('Stopping webdriver')

### Environment

- Operating system: MAC mini (12.6.1 Monterey)
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.46
  - Node.js version (output of `node --version`): v16.0.0
  - `npm` version (output of `npm --version`): 8.19.2
  - Last `appium` version which did _not_ exhibit the problem: X
- If running Appium Desktop, its version: X
- Appium driver(s) and their version(s): flutter@1.11.0
- Appium plugin(s) and their version(s): X
- Platform and version under test:  X
- Real device or emulator/simulator: iOS (iPhone SE2 16.1.1)

-App in flutter (3.0+)

**Comment by mykola-mokhnach** [comment]
Please create an issue to Flutter driver repository. Appium team does not maintain that driver.

**Comment by yadsandy** [comment]
I am facing the same issue in iOS for real device. Is there any solution for it.
