### ISSUE TITLE
[Feat]: [iOS] keyboard parsing option

### ISSUE THREAD

**Issue by andrew-clear** [appium/appium#17913]
Is it possible to add a parsing option for the keyboard for iOS devices?
Today when I want to hide the keyboard, I use the `hide_keyboard()` method, but for the iOS device, I need to pass the button name. I want to be able to parse all buttons that I have on the keyboard and press the button that I need. In my example, I press 'return.' The problem is that sometimes I need to press a different button to continue the flow, so I need to press on "go" button on the keyboard. It can be "return," "next," or "go," etc.
Of course, I can create a helper function that will check the platform name and then pass the button name that I need to press, something like this:
```
def hide_keyboard(driver, button):
    if driver.capabilities["platformName"] == 'Android':
        Helper(driver).hide_keyboard()
    elif driver.capabilities["platformName"] == "iOS":
        Helper(driver).hide_keyboard(button)
```
But I need to do this per screen.
![Screen Shot 2022-12-11 at 15 53 02](https://user-images.githubusercontent.com/81910554/206908313-8d7deba2-9bc4-4c0d-9953-634b50cf3bbe.jpg)

**Comment by mykola-mokhnach** [comment]
btw, pressing "return" or any other action button does not theoretically hide the keyboard. It is rather just a side effect of submitting a value.

**Comment by andrew-clear** [comment]
> iOS keyboard is available via accessibility and buttons names could be retrieved from the client code. 
I want to be able to get all buttons from the keyboard before I press them.
As I can get the page source via the `driver.page_source` I want to get all button names from the keyboard.

**Comment by mykola-mokhnach** [comment]
What stops you from parsing the page source xml and extracting appropriate attributes from approperiate XCUITypeKeyboard descendants?

**Comment by andrew-clear** [comment]
I will try, thank you
