### ISSUE TITLE
bug: Custom Appium Home location is not a recognized argument

### ISSUE THREAD

**Issue by CRYPTO-7CA** [appium/appium#17926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to install the Appium Drivers in a path, that is accessible to all users instead of only the current user.
I am referring to the reading material provided here (from Appium's Github reference): https://appiumpro.com/editions/122-installing-appium-20-and-the-driver-and-plugins-cli
When I perform any of these commands in PowerShell:

```
appium -ah C:\Programs\npm driver install windows
appium -ah "C:\Programs\npm" driver install windows
appium --home "C:\Programs\npm" driver install windows
appium --appium-home "C:\Programs\npm" driver install windows
appium --home="C:\Programs\npm" driver install windows
```

I get an error of the argument not being recognized. See screenshot below:

![image](https://user-images.githubusercontent.com/61016421/207370855-7acf84a1-341d-4377-9101-752bcbe67406.png)

### Expected Behavior

Appium Drivers install in a custom location alongside where Appium 2 via NPM was installed at E.G. Appium is installed in "C:\Programs\npm" and i expect the Appium Drivers to be installed there as well.

### Minimal Reproducible Example

All I did was the following through PowerShell with Administrator privileges:

```
npm i -g appium@next --prefix="C:\Programs\npm"
```

And then the Appium commands listed above in the 'current behavior' section.

### Environment

- Operating system: Windows 10 Enterprise
- If running via appium CLI...
  - Appium CLI version (output of appium --version): 2.0.0-beta.46
  - Node.js version (output of node --version): v18.12.1
  - npm version (output of npm --version): 8.19.2
  - Last appium version which did not exhibit the problem: N/A
- If running Appium Desktop, its version: N/A
- Appium driver(s) and their version(s): 8.7.3
- Appium plugin(s) and their version(s): N/A
- Platform and version under test: Windows 10 Enterprise
- Real device or emulator/simulator: N/A

### Futher Information

I want to also install the "uiautomator2" driver in that specific location but I have not tried it yet.

**Comment by KazuCocoa** [comment]
Tried `APPIUM_HOME` as an environment variable?
https://appium.github.io/appium/docs/en/2.0/guides/migrating-1-to-2/#drivers-installation-path

**Comment by mykola-mokhnach** [comment]
I assume this command line argument has been removed. Have you tried to set the `APPIUM_HOME` environment variable instead?

**Comment by CRYPTO-7CA** [comment]
Something went wrong this time.
I set the `APPIUM_HOME` environment variable to the install location "C:\Programs\npm" as seen here
![image](https://user-images.githubusercontent.com/61016421/207389060-4b572b33-aae7-4678-9f1b-34d9c9a0f7a9.png)
During installation something went wrong.

Installing Windows Drivers results in this error:

`npm ERR! Error: Cannot find module 'appium/support'`

and running a `appium driver list` results in an appium NPM not found type of error.

![image](https://user-images.githubusercontent.com/61016421/207389473-dc1390ee-bd0c-4946-b5f2-61143c2c17e1.png)

But uiautomator2 was installed just fine it seems.

My current installation sequence is as follows (PowerShell with Admin privileges):

```
$NPM_INSTALL_LOCATION = "C:\Programs\npm"

# Install appium 2 beta in different location
& npm i -g appium@next --prefix "$NPM_INSTALL_LOCATION"

# Set Environment Variables
$env:Path += ";$NPM_INSTALL_LOCATION"
[System.Environment]::SetEnvironmentVariable("PATH", $Env:PATH + ";$NPM_INSTALL_LOCATION", [EnvironmentVariableTarget]::Machine)
[System.Environment]::SetEnvironmentVariable("PATH", $Env:PATH + ";$NPM_INSTALL_LOCATION", [EnvironmentVariableTarget]::Process)
[System.Environment]::SetEnvironmentVariable("APPIUM_HOME", $NPM_INSTALL_LOCATION, [System.EnvironmentVariableTarget]::Machine)
[System.Environment]::SetEnvironmentVariable("APPIUM_HOME", $NPM_INSTALL_LOCATION, [System.EnvironmentVariableTarget]::Process)

# Install Appium Drivers
Start-Process -Wait -FilePath npm -ArgumentList "install @appium/doctor --location=global --prefix `"$NPM_INSTALL_LOCATION`""
& appium driver install windows
& appium driver install uiautomator2
```

Has something been broken during any point of this sequence?

**Comment by mykola-mokhnach** [comment]
I'm not quite sure what exactly you are trying to achieve there. I would expect APPIUM_HOME folder to be different from the one where other npm modules are installed to avoid unexpected conflicts.

https://github.com/appium/appium/issues/16580 looks similar to me.

**Comment by CRYPTO-7CA** [comment]
My goal is to get Appium2 and it's drivers installed in a location, that is accessible to all users by generating a fixed path `C:\Programs\npm` and perform the installations in there. This is gonna be utilized by CI/CD systems, which is why we avoid user specific installations.

**Comment by CRYPTO-7CA** [comment]
I just figured it out at random what the other issue was.

For some reason `& npm i -g appium@next --prefix "$NPM_INSTALL_LOCATION"` is not enough to install it in the specified location. I had to run the same command without the `-g` like so `& npm i appium@next --prefix "$NPM_INSTALL_LOCATION"` so that a normal user would get the drivers (in my case "windows" and "uiautomator2") installed and so that `appium driver list` does not return a NPM error.

What is going on with the installation of appium2 and why did this tiny `-g` make all the difference in my issue?

BTW - setting the environment variable `APPIUM_HOME` beforehand did help. I also put `$env:APPIUM_HOME = "$NPM_INSTALL_LOCATION"` in the PowerShell Scripz to have it loaded in the same PowerShell instance.

**Comment by boneskull** [comment]
@CRYPTO-7CA I'm having trouble understanding the current issue(s) you are having.  If you wish to install Appium _and_ its extensions into a specific directory, it may be easier to do this (whatever the powershell equivalent is):

```bash
cd C:\Programs\npm
npm init -y # creates a package.json
npm install --save appium@next appium-windows-driver appium-uiautomator2-driver 
```

`appium` and its extensions will now live in `C:\Programs\npm\node_modules`.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by CRYPTO-7CA** [comment]
> I would not set APPIUM_HOME to an npm managed directory. Why not `C:\Programs\appium` or something instead?
> 
> If you're not running a Node.js based project I would disregard @boneskull's latest comment.

Consider it done. I have renamed the install location. And yes, we do not use a Node.js based project. We do need Appium still.

> @CRYPTO-7CA I'm having trouble understanding the current issue(s) you are having. If you wish to install Appium _and_ its extensions into a specific directory, it may be easier to do this (whatever the powershell equivalent is):
> 
> ```shell
> cd C:\Programs\npm
> npm init -y # creates a package.json
> npm install --save appium@next appium-windows-driver appium-uiautomator2-driver 
> ```
> 
> `appium` and its extensions will now live in `C:\Programs\npm\node_modules`.

This alone doesn't get me Appium launcher. When I installed it in this manner I got Appium and its drivers installed in that location now (just like I wanted) but I can't call Appium. I got only 3 items under "C:\Programs\Appium" and these are "node_modules", "package.json" and "package-lock.json".

If I additionally copy-paste the Appium launch command files (appium, appium.cmd, appium.ps1) to "C:\Programs\Appium" then I can run Appium just fine. Can I generate these launcher files using NPM?

**Comment by jlipps** [comment]
the way to launch a node program when you have installed it locally (not globally) is `npx <bin name>`, so `npx appium`, if you're using the local install and npm package options

**Comment by CRYPTO-7CA** [comment]
This works, although only if i perform `cd C:\Programs\Appium` first. Otherwise NPX will look for the package in `C:\Users\USERNAME_HERE\AppData\Roaming\npm`. That's good enough for me. Thanks mates.

**Comment by jlipps** [comment]
that's right. `npx` is used for running locally installed packages. it will look up the directory tree for any package.json including the global folder. so you need to be in the directory where your package.json is which references appium and the drivers.
