### ISSUE TITLE
bug: selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not load a driver for platformName 'iOS'. Please verify your Appium installation

### ISSUE THREAD

**Issue by xiubojin** [appium/appium#17921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1.My iphone running the WebDriverAgentRunner target.
2.Xcode control console output: http://xxx.xxx.xx.xxx:8100/, i can see some infos at http://xxx.xxx.xx.xxx:8100(/status).
3.Copy WebDriverAgent file to `/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent` folder, cover the original project.
4.Open Appium Server GUI desktop and click 'startServer'.
5.The desktop output: Appium REST http interface listener started on 0.0.0.0:4723.
6.I wrote some python script.
7.Run the python code.
8.Pycharm control console output log:
```
Traceback (most recent call last):
  File "/Users/a/Documents/PycharmProjects/Container3/demo.py", line 13, in <module>
    driver = webdriver.Remote(command_executor='http://127.0.0.1:4723/wd/hub', desired_capabilities=config)
  File "/Users/a/Documents/PycharmProjects/Container3/venv/lib/python3.7/site-packages/appium/webdriver/webdriver.py", line 235, in __init__
    options=options,
  File "/Users/a/Documents/PycharmProjects/Container3/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/a/Documents/PycharmProjects/Container3/venv/lib/python3.7/site-packages/appium/webdriver/webdriver.py", line 320, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
  File "/Users/a/Documents/PycharmProjects/Container3/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/Users/a/Documents/PycharmProjects/Container3/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not load a driver for platformName 'iOS'. Please verify your Appium installation
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not load a driver for platformName 'iOS'. Please verify your Appium installation
    at getResponseForW3CError (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)
```

### Expected Behavior

The python service should start successfully.

### Minimal Reproducible Example

python script:
```
from appium import webdriver

config = dict()
config['platformName'] = 'iOS'
config['platformVersion'] = '16.0'
config['deviceName'] = 'iPhone 13 Pro'
config['app'] = 'com.huber.JXBContainer'
config['udid'] = '00009221-000526473RDB326J'

driver = webdriver.Remote(command_executor='http://127.0.0.1:4723/wd/hub', desired_capabilities=config)
```

### Environment

Appium Desktop Version: Appium-Server-GUI-mac-1.22.3-4
WebDriverAgent: V4.10.12
node: v18.12.1
npm: 8.19.2
mac os: 12.6 Apple M1

real device:
iphone 13 pro
iOS 16.0

### Link to Appium Logs
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/23068582/207058167-7270f739-7cb4-46c2-a661-c9b5464693c0.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/23068582/207058248-d96254ef-ea1b-49e8-94ce-1e967656a042.png">
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/23068582/207058853-2107bc94-8be7-4e07-bb68-371772b3cd0d.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/23068582/207058412-d8f73086-faf2-4999-b636-2c985e563bd2.png">

**Comment by xiubojin** [comment]
I spent a long long long time researching this issue, but i get nowhere, please help me.

**Comment by bwomsm1** [comment]
@xiubojin try adding to your config that:
```
config['automationName'] = 'XCUITest'
```

If you are running against real device you also need:
```
xcodeOrgId = BX9====47
xcodeSigningId = iPhone Developer
```

**Comment by mykola-mokhnach** [comment]
Sorry, we cannot help with hacking. 
Consider installing the most recent version of XCUTest driver supplied with Appium 2 and use Appium Inspector, which is compatible to it.

If you are still much into making it work your way then feel free to ask questions at Appium forum.
Closed as not an issue

**Comment by xiubojin** [comment]
> xcodeOrgId

Oh my god, you are a good man!👍🏻👍🏻👍🏻 I upgrade appium to 2.X version, and install xcuitest driver, my python script start work, thank u very much!!!

**Comment by xiubojin** [comment]
Oh my god, you are a good man!👍🏻👍🏻👍🏻 I upgrade appium to 2.X version, and install xcuitest driver, my python script start work, thank u very much!!!
