### ISSUE TITLE
Activity name '.com.google.android.gms.wallet.service.BIND' used to start the app doesn't exist or cannot be launched

### ISSUE THREAD

**Issue by SuryaSP97** [appium/appium#17925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

error

### Expected Behavior

should launch the application successfully bcz the same package and activity name working for appium inspector

### Minimal Reproducible Example

public class tvamapp {
	public AppiumDriverLocalService service;
	public AndroidDriver driver;
	@Test
	public void login() throws MalformedURLException
	{
		 service= new AppiumServiceBuilder().withAppiumJS(new File("C:\\Users\\surya.p\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib//main.js"))
				.withIPAddress("127.0.0.1").usingPort(4723).withTimeout(Duration.ofSeconds(10000)).build();
				service.start();
				//DesiredCapabilities caps=new DesiredCapabilities();
			UiAutomator2Options options=new UiAutomator2Options();
			options.setDeviceName("Android Device");
			options.setApp("C:\\Users\\surya.p\\eclipse-workspace1\\appium\\src\\test\\java\\resources\\tvam_D2.1.27_internal.apk");
			options.setAppActivity("com.google.android.gms.wallet.service.BIND");
			options.setAppPackage("com.google.android.gms");
			driver=new AndroidDriver(new URL("http://127.0.0.1:4723"), options);
			 
			driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
	
}
}

### Environment

host: 'ATDEV122L1', ip: '192.168.183.175'
Build info: version: '4.6.0', revision: '79f1c02ae20'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4.1'

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly and provide the requested information. Have you tried to start the app manually from terminal using the same command? Have you checked the troubleshooting tutorial?

**Comment by SuryaSP97** [comment]
No not tried from cmd, Cz i don't know the commands to try from terminal.
But tried through appium inspector, it worked for same activity and package.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-uiautomator2-driver/blob/master/docs/activity-startup.md

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
