### ISSUE TITLE
We are seeing Unknown mobile command "audio:inject" while trying to inject audio for voice commands using appium

### ISSUE THREAD

**Issue by SharathVarganti** [appium/appium#17937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are seeing unknown command mobile command "audio:inject". Only shell,execEmuConsoleCommand,dragGesture,flingGesture,doubleClickGesture,longClickGesture,pinchCloseGesture,pinchOpenGesture,swipeGesture,scrollGesture,scrollBackTo,scroll,viewportScreenshot,viewportRect,deepLink,startLogsBroadcast,stopLogsBroadcast,acceptAlert,dismissAlert,batteryInfo,deviceInfo,getDeviceTime,changePermissions,getPermissions,performEditorAction,startScreenStreaming,stopScreenStreaming,getNotifications,listSms,type,sensorSet,deleteFile,clearApp,startActivity,startService,stopService,broadcast,getContexts,installMultipleApks,unlock commands are supported. on trying to inject audio file for voice commands

### Expected Behavior

We are seeing perfecto saying appium supports this command 

if you work with a Selenium/Appium driver, you need to call the commands using the Selenium/Appium driver (or, in the case of Reporting commands, through the [Reporting SDK](https://help.perfecto.io/perfecto-help/content/perfecto/test-analysis/download_the_reporting_sdk.htm) that works with the driver) and not as part of a UFT test or another framework.

Plays an audio file into the device audio-in. Supported file types: MP3 and WAV

I played .mp3 file on injecting , but command is not supportable using appium

### Minimal Reproducible Example

trying to automate voice command using audio:inject command 

seeing above error

Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started

appium 1.22.3

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by SharathVarganti** [comment]
Can we know what command we can use for Android for voice recognition

**Comment by jlipps** [comment]
this is not an appium feature. best to explore other tools.
