### ISSUE TITLE
Please ask the developer of `appium-gestures-plugin` to add a peer dependency on `^appium@2.0.0-beta.46`

### ISSUE THREAD

**Issue by fayeemajidul** [appium/appium#17940]
The problem

I have made some tries to run tests on android using UiAutomato2, the problem specifically involves using gestures. I am a novice to Appium, however I have tried every solution/syntax found on stackoverflow. Is there any fix, I just want to be able to use long press, however I keep running into the warning message below and unable to do any gestures.

"WARN Appium Appium encountered 1 warning while validating plugins found in manifest /Users/gangbuddah/node_modules/.cache/appium/extensions.yaml
WARN Appium Plugin "gestures" has 1 potential problem: 
WARN Appium   - Plugin "gestures" (package `appium-gestures-plugin`) may be incompatible with the current version of Appium (v2.0.0-beta.46) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-gestures-plugin` to add a peer dependency on `^appium@2.0.0-beta.46`."

My Environment:

    Appium version v2.0.0-beta 46:
    Node.js version: v19.2.0
    Npm or Yarn package manager: NPM
    Mobile platform/version under test: Android
    Real device or emulator/simulator: Simulator
    Appium CLI or Appium.app|exe: Appium command line

Details

I have installed the drivers:

    uiautomator2 V2.11.1 

____________________________

Thank you in advanced.

**Comment by vnuta9** [comment]
What is the suggested solution to this issue ? The question was closed with out any said direction.

**Comment by saikrishna321** [comment]
@vnuta9 this is just a warning. Please raise this issue under plugin repo.
