### ISSUE TITLE
check JS types in all monorepo workspaces

### ISSUE THREAD

**Issue by boneskull** [appium/appium#17946]
The following workspaces' `tsconfig.json` files are not (yet) configured to typecheck everything at build time:

- [ ] `packages/doctor`
- [ ] `packages/docutils`
- [ ] `packages/execute-driver-plugin`
- [ ] `packages/fake-plugin`
- [ ] `packages/images-plugin`
- [ ] `packages/opencv`
- [ ] `packages/relaxed-caps-plugin`
- [ ] `packages/universal-xml-plugin`

> Note: Some individual source files may have a `// @ts-check` pragma.  If _all_ JS sources in a workspace have this pragma, it can be removed and `checkJs: true` can be added to the workspace's `tsconfig.json`.

Eventually, I'd like to set `checkJs: true` in all of those configs and get everything typed.  Once all workspace `tsconfig.json` files contain `checkJs: true`, we can add `checkJs: true` to the `./config/tsconfig.base.json` and remove it from all workspace-specific configs.

This doesn't have to be done all at once, but it's good to track progress here.

Also: Don't worry about test files for now.

* * *

To get an up-to-date list, run:

```bash
❯ grep -riL '"checkJs": true' ./packages/*/tsconfig.json
./packages/doctor/tsconfig.json
./packages/docutils/tsconfig.json
./packages/execute-driver-plugin/tsconfig.json
./packages/fake-plugin/tsconfig.json
./packages/images-plugin/tsconfig.json
./packages/opencv/tsconfig.json
./packages/relaxed-caps-plugin/tsconfig.json
./packages/universal-xml-plugin/tsconfig.json
```

**Comment by pacozaa** [comment]
@boneskull Question, I see `@linkcode` is used in the code but I check here at  https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#link looks like it changes to just `@link` or `@see`. Would you like me to change them as well?

**Comment by boneskull** [comment]
@pacozaa `@linkcode` is supported by VSCode but apparently not documented.  

In addition to what TypeScript understands, some tags are purely for documentation, however.  See [the TypeDoc docs](https://typedoc.org/guides/overview/) for what we can use.

**Comment by pacozaa** [comment]
Just a short note, some of the work in this issue are done in 
https://github.com/appium/appium/pull/17962
https://github.com/appium/appium/pull/17922

I am working on the rest of the packages.

**Comment by zeufack** [comment]
Is this issues still open ? If so, I would like to work on it
