### ISSUE TITLE
bug: Unable run appium after upgrading to Appium 2

### ISSUE THREAD

**Issue by yudi1812** [appium/appium#17961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was upgrading from Appium 1.22 to Appium 2.0, I uninstalled appium and install appium 2 with the following command:

npm install -g appium@next

I don't see any error but when I type appium I got an error as follows:

Fatal Error: Appium had trouble loading the extension installation cache file (/usr/local/lib/node_modules/appium/build/lib/main.js/node_modules/.cache/appium/extensions.yaml). It may be invalid YAML. Specific error: ENOTDIR: not a directory, open '/usr/local/lib/node_modules/appium/build/lib/main.js/node_modules/.cache/appium/extensions.yaml'

at /usr/local/lib/node_modules/appium/lib/extension/manifest.js:351:19

at Manifest.read (/usr/local/lib/node_modules/appium/lib/extension/manifest.js:389:7)

at loadExtensions (/usr/local/lib/node_modules/appium/lib/extension/index.js:22:3)

at init (/usr/local/lib/node_modules/appium/lib/main.js:175:40)

at main (/usr/local/lib/node_modules/appium/lib/main.js:283:22)

### Expected Behavior

I can run Appium

### Minimal Reproducible Example

node version: 18.12.1
npm version: 8.19.2

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by yudi1812** [comment]
OS: MacOS Monterey 12.4

**Comment by pacozaa** [comment]
@yudi1812 What's the driver you are trying to use? Because Appium 2 required you to install the driver separately.

**Comment by yudi1812** [comment]
I have not installed the driver yet.
Just checked the Appium version, appium -v and got that error

**Comment by pacozaa** [comment]
What driver are you intending to use? Can you try `appium driver install uiautomator2`?

**Comment by mykola-mokhnach** [comment]
Maybe try to uninstall appium package and then manually delete all leftovers from `/usr/local/lib/node_modules/appium`. Then install again.

**Comment by yudi1812** [comment]
> What driver are you intending to use? Can you try `appium driver install uiautomator2`?

@pacozaa I tried `appium driver install uiautomator2` and got the same error

**Comment by yudi1812** [comment]
> Maybe try to uninstall appium package and then manually delete all leftovers from `/usr/local/lib/node_modules/appium`. Then install again.

I uninstalled appium and reinstalled it but still no luck.

**Comment by pacozaa** [comment]
Can you check what inside the

 /usr/local/lib/node_modules/appium/build/lib/main.js/node_modules/.cache/appium/

For example, are there any files in there or what it looks like?

**Comment by mykola-mokhnach** [comment]
> > Maybe try to uninstall appium package and then manually delete all leftovers from `/usr/local/lib/node_modules/appium`. Then install again.
> 
> I uninstalled appium and reinstalled it but still no luck.

Did you delete the leftovers manually?

**Comment by jlipps** [comment]
do you have `APPIUM_HOME` set as an environment variable? obviously `/usr/local/lib/node_modules/appium/build/lib/main.js/node_modules/.cache/appium/extensions.yaml` is not a valid path, but it is unclear where it is coming from.

**Comment by yudi1812** [comment]
Thank you all for trying to resolve this issue.
Thanks @jlipps Yes, you're right. I have removed APPIUM_Home from .zprofile and working fine now.
