### ISSUE TITLE
investigate ajv optimization

### ISSUE THREAD

**Issue by boneskull** [appium/appium#17960]
ajv is heavy. assuming I know how to read a flame graph--which is a big assumption--appium spends more cycles in ajv than anything else upon initial load. 

while appium startup time is not intolerably slow, we _may_ be able to see a decent speedup by using ajv's "validator compiler" functionality (read the docs). 

because the final schema is built on-the-fly based on what extensions are installed, this may prove challenging. I'd expect the strategy to be something where we could cache the resulting validator based on a hash of installed extensions. 

anyway: nice-to-have but might be fun to figure out.

**Comment by jlipps** [comment]
Yeah, not a huge issue. Appium 2 initial startup is definitely slower than it was with Appium 1, I'm guessing for this reason.

**Comment by KazuCocoa** [comment]
Yes, I’m good to close this issue
