### ISSUE TITLE
[Feat]: prepare prebuilt WDA packages in appium/WebDriverAgent GitHub releases

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#17963]
**Is your feature request related to a problem? Please describe.**

To make usable prebuilt packages for simulators like real devices already have in GitHub releases.

**Describe the solution you'd like**

We should check what kind of prebuilt packages help, and how we can use them.
Context: https://github.com/appium/WebDriverAgent/pull/641

If no easy way, maybe we can prepare documentation to create/use prebuilt ones for simulators in xcuitest driver repo

**Describe alternatives you've considered**

**Additional context**

**Comment by mykola-mokhnach** [comment]
I assume we should also document it somewhere about how to use these prebuilt packages

**Comment by KazuCocoa** [comment]
I remember in https://github.com/appium/WebDriverAgent/pull/687#discussion_r1181176604 coversation, probably we could prepare entire

```
/path/to/Xcode/DerivedData/WebDriverAgent-fdaixnwvimgqhucjjimjjbtfwdou/Build/Products
```

that has xctestrun such as `WebDriverAgentRunner_iphonesimulator16.2-x86_64.xctestrun`. Then, 

```
{
  "appium:automationName": "xcuitest",
  "platformName": "ios",
  "appium:platformVersion": "16.2",
  "appium:useXctestrunFile": "true",
  "appium:bootstrapPath": "/Users/kazuaki/Library/Developer/Xcode/DerivedData/WebDriverAgent-fdaixnwvimgqhucjjimjjbtfwdou/Build/Products"
}
```
should help to run the package. The xcodebuild would be like:

> xcodebuild test-without-building -xctestrun /Users/kazuaki/Library/Developer/Xcode/DerivedData/WebDriverAgent-fdaixnwvimgqhucjjimjjbtfwdou/Build/Products/16701675-9293-4211-B3C6-D04838C74BE3_16.2.xctestrun -destination id=16701675-9293-4211-B3C6-D04838C74BE3 IPHONEOS_DEPLOYMENT_TARGET=16.2 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO

**Comment by KazuCocoa** [comment]
So, my current plan for this is:

1. the WDA repo will create a package which has entire `Build/Products`
2. download it and set the path as `bootstrapPath` and `useXctestrunFile` as true

Not sure how widely this idea can use for simulators.

**Comment by saikrishna321** [comment]
@KazuCocoa Is it possible we build the IPA and then users can resign the process for real device?

**Comment by KazuCocoa** [comment]
Can sign like https://stackoverflow.com/questions/13204407/how-to-codesign-an-existing-mac-os-x-app-file-for-gatekeeper, but maybe cannot create ipa to distribute it. You should install the app.

**Comment by KazuCocoa** [comment]
https://appium.github.io/appium-xcuitest-driver/4.24/real-device-config/ also may help

**Comment by KazuCocoa** [comment]
Remaining task in this ticket is uploading packages built in https://github.com/appium/WebDriverAgent/actions/workflows/wda-package.yml to proper GH releases https://github.com/appium/WebDriverAgent

**Comment by rmarinho** [comment]
So I can just download an artifact from that build and have that runner app always installed ? instead of dealing with signing it ?

**Comment by KazuCocoa** [comment]
You should do the signing by yourself since it is unavoidable, but the https://github.com/appium/WebDriverAgent/releases could help to skip building modules.
https://appium.github.io/appium-xcuitest-driver/5.4/run-preinstalled-wda/
https://appium.github.io/appium-xcuitest-driver/5.4/run-prebuilt-wda/
https://appium.github.io/appium-xcuitest-driver/5.4/real-device-config/

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Can this issue be closed now?

**Comment by KazuCocoa** [comment]
We can close this now. (still maybe can tune further for simulators, but this issue's main scope has been resolved.
