### ISSUE TITLE
bug: cannot use NFC ReadCard application when io.appium.settings running on Android Phone

### ISSUE THREAD

**Issue by stone89son** [appium/appium#17973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm testing NFC card. using C# language.
when killed package " io.appium.settings", NFC ReadCard test item can read info NFC card.
but when io.appium.settings running on Phone, cannot read.
if io.appium.settings has supported.
how to enable NFC for Android Test Item?

### Expected Behavior

Read value of NFC card.

### Minimal Reproducible Example

```
                AppiumOptions options = new AppiumOptions();
                options.AddAdditionalCapability(MobileCapabilityType.DeviceName, "Android");
                options.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Android");

                options.AddAdditionalCapability(MobileCapabilityType.Orientation, "PORTRAIT");
                options.AddAdditionalCapability("appium:appPackage", "com.google.android.dialer");
                options.AddAdditionalCapability("appium:appActivity", "com.google.android.dialer.extensions.GoogleDialtactsActivity");
                //noReset=false->remove app end test
                options.AddAdditionalCapability(MobileCapabilityType.Orientation, "PORTRAIT");
                options.AddAdditionalCapability("appium:noReset", true);
                options.AddAdditionalCapability("appium:getMatchedImageResult", true);
                //options.AddAdditionalCapability("appium:autoGrantPermissions", true);

                //options.AddAdditionalCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, Constants.TIMEOUT);
                options.AddAdditionalCapability(MobileCapabilityType.NewCommandTimeout, TimeSpan.FromDays(3).TotalSeconds);
                //options.AddAdditionalCapability(MobileCapabilityType.NewCommandTimeout, TimeSpan.FromMinutes(2).TotalSeconds);

                Uri url = new Uri(_windowsApplicationDriverUrl);

                _driver = new AndroidDriver<AndroidElement>(url, options);
                _driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(5000);

```

### Environment

- Operating system: win 10
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 1.22.3
  - Node.js version (output of `node --version`): v18.12.1
  - `npm` version (output of `npm --version`):  8.19.2
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): Appium.WebDriver 4.3.2
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
I'm not so familiar with NFC related implementation in Android, but I wonder if it gets restricted when the device has a background process which has some of https://github.com/appium/io.appium.settings/blob/master/app/src/main/AndroidManifest.xml#L6-L29 permissions


I found https://stackoverflow.com/questions/57202157/android-nfc-read-fails-after-fullscreen-launcher-app-comes-from-background
`android.permission.DISABLE_KEYGUARD`
So... I wonder if without https://github.com/appium/io.appium.settings/blob/6214c0a74510c3ad5b4bdf0740bb56724622d8e6/app/src/main/java/io/appium/settings/Unlock.java#L28-L29 one can work. Could you try out without these flags?

**Comment by mykola-mokhnach** [comment]
You could try to provide `appium:unlockType` capability valuer or set `appium:skipUnlock` to true in order to avoid Unlocker activity execution.

**Comment by KazuCocoa** [comment]
You also could try out Appium 2 and UIA2 driver [2.12.1](https://github.com/appium/appium-uiautomator2-driver/compare/v2.12.0...v2.12.1)

**Comment by stone89son** [comment]
> You could try to provide `appium:unlockType` a custom capability value or set `appium:skipUnlock` to true in order to avoid Unlocker activity execution.

 In Appium, the case phone lock but not set password, how to do unlock phone?

**Comment by mykola-mokhnach** [comment]
> > You could try to provide `appium:unlockType` a custom capability value or set `appium:skipUnlock` to true in order to avoid Unlocker activity execution.
> 
> In Appium, the case phone lock but not set password, how to do unlock phone?

Update the UIA2 driver to the most recent version like @KazuCocoa mentioned above and do not provide any value to `unlockType`

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by stone89son** [comment]
no . i worked everyone comment, but cannot unlock with swipe mode.

**Comment by stone89son** [comment]
thank [KazuCocoa](https://github.com/KazuCocoa), worked!
