### ISSUE TITLE
bug: <I can't run tests in 2 threads, the socket crashes>

### ISSUE THREAD

**Issue by Ex3mal282** [appium/appium#17987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello everyone. I am trying to run tests in 2 threads using pytest-xdist, but this error occurs - selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up.

desired_caps = dict(
    platformName='Android',
    platformVersion='11',
    automationName='uiautomator2',
    deviceName='sdk_gphone_x86', #Nexus 5 API 30
    app='D:/05.ru/app-release4.1.0.apk',
    noReset='false',
    newCommandTimeout = "30000",
    udid = '35b77ee6',
    systemPort = 8200
)

@pytest.fixture(scope="function", autouse=True)
def get_driver(request):
    driver: webdriver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
    request.cls.driver = driver
    
desired_caps1 = dict(
    platformName='Android',
    platformVersion='11',
    automationName='uiautomator2',
    deviceName='Nexus 5 API 30',
    app='D:/05.ru/app-release4.1.0.apk',
    noReset='false',
    newCommandTimeout = "30000",
    udid = 'emulator-5554',
    systemPort = 8215
)
@pytest.fixture(scope="function", autouse=True)
def get_driver1(request):
    driver1: webdriver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps1)
    request.cls.driver = driver1
    
     Command - pytest -n2 --dist loadgroup -m "run_test or lololo" -s -vv
    
    

### Expected Behavior

I expect to run on two devices without errors and socket drop

### Minimal Reproducible Example

///j

### Environment

- Operating system: Windows 10

  - Appium CLI version (output of `appium --version`):

- Real device or emulator/simulator:1 real, 1 emulator (android studio)

### Link to Appium Logs

https://gist.github.com/Ex3mal282/b39f25c726f083c01d91826a33bd2933

**Comment by jlipps** [comment]
we no longer support appium 1. please try with appium 2 and resubmit logs
