### ISSUE TITLE
bug: Blocked a frame with origin "https://appapi.dollar-phil.net" from accessing a cross-origin frame

### ISSUE THREAD

**Issue by nikolapopovic** [appium/appium#17989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I’m trying to automate a checkout process with Appium.
Once the checkout page is opened in WebView I switch context from Native to WebView.
Afterwards I try to switch to an iframe and getting following error:

```
Blocked a frame with origin "https://appapi.dollar-phil.net" from accessing a cross-origin frame. Protocols, domains, and ports must match.
```

Maybe this is not a bug, but any help on how can I solve this?

### Expected Behavior

I'm expecting to switch to iframe without any issues.

### Minimal Reproducible Example

Is this is needed?

### Environment

Appium: 2.0.0-beta.46
Xcode: 14.0.1
Simulator: iPhone 14 (iOS 16.0)

### Link to Appium Logs

https://gist.github.com/nikolapopovic/83217b43a6b5a7f9bb3f46710b8c4c55

**Comment by mykola-mokhnach** [comment]
This behaviour is expected. Unfortunately we do not know (or rather Apple does not provide) any ways to workaround it. See https://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame for more details.

**Comment by jacksonw111** [comment]
I found the workaround for this issue. May someone need it. 
https://hughmccamphill.com/appium-iframes-and-ios
