### ISSUE TITLE
How do i set the date or time using date picker on Android?

### ISSUE THREAD

**Issue by SRVFLLN** [appium/appium#17983]
**Environment:
Win10 
C# 
Android 11 emulator (Pixel 2 API 30)
Appium.WebDriver 4.4.0
UIAutomator2**

Hi! I'm trying to understand how to use Appium and perform mobile testing. So, for some practice i found [open-source Android application](https://github.com/avjinder/Minimal-Todo), and i'm trying to do some basic test. I want to set notification times within the application, but i can't understand how do it or if i can do it. I've googled this, and i found different issues, but no one has helped me. Here is my problem:

![image](https://user-images.githubusercontent.com/93190152/209692094-0b4c6933-9328-4064-8d1c-1a3bb34b5995.png)

You can see that there is no "TimePicker" element or anything like that on this screen. I can't use the `element.sendKeys()` method because it doesn't select the actual date.

![image](https://user-images.githubusercontent.com/93190152/209692295-d8ec2a14-f75f-4702-a963-96853696cb17.png)

Do you have any idea how I could set the time? Any help would be appreciated.

P.S. I have read about the mobile command for the Espresso driver, but it seems useless here, because there is no item on this screen that can be used to change the date by sending the command

**Comment by KazuCocoa** [comment]
Only appium espresso driver can issue https://github.com/appium/appium-espresso-driver#mobile-setdate to DatePicker or TimePicker via https://developer.android.com/reference/androidx/test/espresso/contrib/PickerActions#setdate. Maybe you already read these as your comment.


I wonder if via `mobile:shell` can send texts to focused element (ascii only) https://stackoverflow.com/questions/7789826/adb-shell-input-events

https://discuss.appium.io/ may also help to ask questions

**Comment by kopax-polyconseil** [comment]
Hello, I want to set date in react-native-date-picker, why only espresso can do it? How do I set the date without it ? I believe a big warning would make sens on the doc, also the appium-boilerplate from webdriverio does not use it.

**Comment by KazuCocoa** [comment]
Because the API https://developer.android.com/reference/androidx/test/espresso/contrib/PickerActions#setdate is available only via Espresso framework. I assume it depends on the implementation. For example, adding keyboard input like https://github.com/material-components/material-components-android/blob/master/docs/components/DatePicker.md may help to set time via UIA2 (which is accessibility node info based one) though keyboard. I don't know the  react-native-date-picker though.
