### ISSUE TITLE
bug: Unable to view expanded React Native DropDownPicker options.

### ISSUE THREAD

**Issue by Sergius64** [appium/appium#18005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

 I'm having a few problems with Automating testing of our React Native app - wanted to see if I could get some guidance on the most obvious one to see if Appium is a viable tool for testing it.

 The application under test has a little window for creating a new Phone Book entry. That window has a DropDown list for picking the type of Phone book entry - currently with the options of 'Receiver' and 'Email'. It's source code is:

```
<DropDownPicker
            open={open}
            value={value}
            placeholder="Select Contact Type"
            items={items}
            setOpen={setOpen}
            setValue={setValue}
            setItems={setItems}
            style={{
              backgroundColor: colors.background,
              borderColor:colors.primary,
              borderRadius:0,
              borderBottomColor: colors.primary
            }}
            containerStyle={{
              backgroundColor: colors.background
            }}
            disabledStyle={{
              opacity: 0.5
            }}
            labelStyle={{
              fontWeight: 'bold',
              fontFamily:colors.fontFamily
            }}
            textStyle={{
              fontSize: 15,
              color: colors.primary,
              fontFamily:colors.fontFamily
            }}
          />
```

Now - when I try to view the Dropdown element in Appium Inspector before it has been expanded - it shows up just fine:

![image](https://user-images.githubusercontent.com/121878448/210378750-86757005-f6f0-4f0e-9386-90e601221dd6.png)

But when I expand it - the only "new" element Appium inspector sees is a new 3 pixel tall android.view.ViewGroup. That element has no children and there's no way to tell what options are available for selection. So I'm able to tell that the dropdown was expanded - but am forced to approximate the coordinate locations of each of the options based on the location of the dropdown field. This is pretty ugly and will break when more options are added, and possibly on devices with different resolutions:

![image](https://user-images.githubusercontent.com/121878448/210379438-256a4d9a-de37-42f1-ac3a-9eb83ea936fe.png)

I've tried finding child elements with the text of those options at Run Time - but such FindElementByXPath("/*[@text='" + type + "']") calls are not finding anything either. Does Appium not really support React Native very well? Are our developers doing something strange with it to cause this issue?

### Expected Behavior

I would like Appium Inspector to be able to represent the expanded DropDownPicker correctly and find the sub-elements of each one of visible options.

### Minimal Reproducible Example

The app under test is on the playstore - but it requires an authenticated account that I'm loathe to share in such an open setting. If you guys really need it - I guess I can provide a minimum access account on a case by case basis.

### Environment

- Operating system: Windows

- If running Appium Desktop, its version: Appium Desktop 2022.11.1, Electron: 13.6.9, Node.js: 14.16.0
- Appium driver(s) and their version(s): v1.22.3
- Appium plugin(s) and their version(s):
- Platform and version under test: React Native App.
- Real device or emulator/simulator: Emulator, Pixel 4 API 29.

**Comment by mykola-mokhnach** [comment]
XCTest only "sees" what is exposed to the accessibility. If this particular menu is not properly made accessible then this behaviour is expected.

**Comment by Sergius64** [comment]
So you're saying accessibilityLabel needs to be declared on the DropDownPicker by our App developers and that will make Appium Inspector find the expanded field?

**Comment by mykola-mokhnach** [comment]
Sorry, I cannot help there, not a react developer myself. Consider reading the language tutorial.

**Comment by Sergius64** [comment]
Ok, I guess according to https://dev.to/nextlevelbeard/an-end-to-the-abuse-of-accessibility-ids-5d2j they changed accessibilityLabel to testID anyway. I'll get our developers to try to include that, but who knows when they'll have time to. Will close this for now.

**Comment by AngelCampa** [comment]
@Sergius64 any luck adding testIDs to the options of the dropdown?
