### ISSUE TITLE
How to unlock in screen "confirm your pattern"

### ISSUE THREAD

**Issue by stone89son** [appium/appium#18008]
I setting C# appium driver 4.3.2:
```
options.AddAdditionalCapability("appium:forceAppLaunch", true);
options.AddAdditionalCapability("appium:autoGrantPermissions", true);
options.AddAdditionalCapability("appium:unlockType", "pattern");
options.AddAdditionalCapability("appium:unlockKey", "12369");
```
When io.appium.settings startup run on phone unlocked sucessful,
but I goto pressed button "Erase all data" will show "confirm your pattern", alter i call ：
`driver.Unlock();`
Cannot unlock with pattern "12369"

**Comment by KazuCocoa** [comment]
Please attach the full appium server log as GIST (and fill in the bug report template).
https://github.com/appium/appium-android-driver/blob/89da9a1728c39aeceae18a1eb8f04e7bf0ba9602/docs/UNLOCK.md

Potentially it needs some adjustment in the code as each element coordinate could vary by depending on devices 
https://github.com/appium/appium-android-driver/blob/a3b619e60210686c95ee9fcb6d67cec4388b28d1/lib/unlock-helpers.js#L194-L236

**Comment by mykola-mokhnach** [comment]
Closed because of no response
