### ISSUE TITLE
[Feat]: Pass/inject simulation headers when I test the web app

### ISSUE THREAD

**Issue by andrew-clear** [appium/appium#18011]
Is it possible to test the web app via the Appium and, during the testing, pass/inject simulation headers, as I can do it via the selenium-wire?

**Comment by mykola-mokhnach** [comment]
not sure what headers you mean. If we are talking about request headers then W3c Selenium API does not provide any methods to modify these. Check https://stackoverflow.com/questions/15645093/setting-request-headers-in-selenium

**Comment by andrew-clear** [comment]
I checked the answer on StackOverflow that you gave me, and I saw this comment:
https://stackoverflow.com/a/51919307
This is what I need.

**Comment by jlipps** [comment]
Yep, you'd need to handle this with some kind of mitm proxy or the python package you found, outside of Appium itself.
