### ISSUE TITLE
bug: mobile:type unicode text exception on 2nd execution with same text

### ISSUE THREAD

**Issue by tripfish** [appium/appium#18022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you execute the Mobile Command `"mobile: type"` twice in a row with the same word containing unicode characters, an exception occurs on the 2nd execution.

In the log you can see missing quotes during the execution.

### Expected Behavior

Multiple execution should also be possible without errors.

### Minimal Reproducible Example

```
driver.execute_script("mobile: type", {'text': 'Verfügbarkeit'})
driver.execute_script("mobile: type", {'text': 'Verfügbarkeit'})
```

### Environment

- Operating system: Windows 10 64bit
- If running Appium Desktop, its version: 1.22.3-4
- Appium driver(s) and their version(s): Appium-Python-Client 2.7.1, selenium 4.7.2
- Platform and version under test: Android 8
- Real device or emulator/simulator: real

### Link to Appium Logs

https://gist.github.com/tripfish/03c701e664ff602a57a7344e46890097

**Comment by mykola-mokhnach** [comment]
Please use the most recent driver version supplied with Appium 2. We do not support Appium 1 anymore

**Comment by tripfish** [comment]
Just updated to appium 2. The issue does not appear here. 
Thanks for the hint.
