### ISSUE TITLE
[Feat]:migration from opencv4nodejs  to @u4/opencv4nodejs.

### ISSUE THREAD

**Issue by UrielCh** [appium/appium#18026]
Hi, I want to try Appium, so I start to read the getting start section, and I found a section about installing opencv4nodejs.

This opencv4nodejs that I call the legacy opencv4nodejs, is not maintains and @u4/opencv4nodejs replace it.

Since I'm the maintainer of [@u4/opencv4nodejs](https://www.npmjs.com/package/@u4/opencv4nodejs) maybe I can help switching to the current main fork.

**Comment by mykola-mokhnach** [comment]
Thanks for your effort @UrielCh 
We have already migrated to [opencv-bindings](https://github.com/appium/appium/blob/master/packages/opencv/package.json#L47) in the Appium 2 [image-plugin](https://github.com/appium/appium/tree/master/packages/images-plugin)

Not sure if we want to do any further changes. cc @jlipps

**Comment by UrielCh** [comment]
Did you made some benchmark?
I fork opencv4nodejs 2 years ago to remote control some android device, and I also fork [adbkit](https://www.npmjs.com/package/adbkit) to [@u4/adbkit](https://www.npmjs.com/package/@u4/adbkit)

At the end my solution used a lot of cv template image matching, some tesseract, and some Chrome Remote Protocol to control browser.

the final version works within a kubernetes, able ton control android device plug on multiple host.

an overview schema of the project is visible in the [readme](https://hub.docker.com/r/urielch/remote-droid)

I only recently discover appium, and I would like to merge some part of my project in it.

---
the last experimental changer are:
- integrate CUDA in my OpenCV usage
- capture screen content from a video stream using my [@u4/beamcoder](https://github.com/UrielCh/beamcoder) to extract image from video stream.

**Comment by jlipps** [comment]
thanks @UrielCh but we don't have any need for opencv4nodejs anymore. we'd prefer not to include it at this point since it requires native bindings. we've had good success with the js opencv bindings. happy for you to contribute anything else you find valuable, just let us know your ideas!
