### ISSUE TITLE
bug: xcodebuild failed with code 65 -  “WebDriverAgentRunner” couldn’t be loaded because its executable couldn’t be located. The bundle’s executable couldn’t be located

### ISSUE THREAD

**Issue by sboli20** [appium/appium#18027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting xcodebuild failed with 65 Error with below error logs

```
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:

The bundle “WebDriverAgentRunner” couldn’t be loaded because its executable couldn’t be located. Try reinstalling the bundle.


```

### Expected Behavior

Tried to build appium manually using this steps 

### Minimal Reproducible Example

I have manually configured the appium webdriver agent by following this link  - https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md#basic-manual-configuration

I am getting build succeeded message when trying to run in simulator and real device. I could see the webdriverAgent app installed into devices. but as soon as it installed i got message in xcode editor that 'Test Failed'

### Environment

- Operating system: Mac 12.6.1
- Appium - 1.21.0
- node - v18.12.1
- npm - 8.19.2
- Platform and version under test: iOS 16.1 (20B72) 
- Real device or emulator/simulator: Simulator 

Facing the same issue while running in emulator also

### Link to Appium Logs

https://gist.github.com/sboli20/3502a1c3b336750e6700cfddef4ca808

### Futher Information

Facing this issue in simulator and real devices as well

**Comment by mykola-mokhnach** [comment]
xcuitest driver bundled with Appium 1 does not support Xcode 14+. Consider using the one available for Appium 2
Closed as duplicate

**Comment by sboli20** [comment]
Hi @mykola-mokhnach Thanks for the quick response. May i know which version of xCode is compatible with appium 1.21.0?
