### ISSUE TITLE
test flake in images plugin

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18030]
I've seen a few failures in the tests for the images plugin in CI which are resolved by simply rerunning the job.  I've attached a log of one of the failures.

Could be just a timeout, or a race condition, or something _more sinister_

[1_Tests (14.x).txt](https://github.com/appium/appium/files/10378052/1_Tests.14.x.txt)

**Comment by jlipps** [comment]
:-(

**Comment by krishtoautomate** [comment]
Facing same issue randomly. Caused by screenshot method

**Comment by mykola-mokhnach** [comment]
I don't see this happening anymore
