### ISSUE TITLE
bug: appium doesnt show context webview

### ISSUE THREAD

**Issue by nimairodrigues** [appium/appium#18034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i used getContextHundles() in hybrid app to see the contexts and only show the NATIVE_APP, but i need see the WEBVIEW and is not showing
when i set **setCapability("autoWebview", true);** the appium doesnt show me anything even the native app(only show in the appium's log, but not in the console).
i did try put a "wait" before all the page load for me, but the result is the same.
i tryed also these capability that i saw searching for my problem **setCapability("additionalWebviewBundleIds", "process-awesomeAppDebug");** and **setCapability("locationContextEnabled", true);** but didnt work.

### Expected Behavior

i'm expecting to show WEBVIEW when i use getContextHundles() for me interact with webview in my tests

### Minimal Reproducible Example

https://gist.github.com/nimairodrigues/541cf1df790154f3000d09bacd5f7a92

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

### Link to Appium Logs

https://gist.github.com/nimairodrigues/cd03246ce972746ed33baff53560a17d

### Futher Information

![image](https://user-images.githubusercontent.com/112123854/211585150-994ee70b-eb46-40d5-bb86-1dec1886bc65.png)

**Comment by jlipps** [comment]
Those Appium logs are formatted strangely. Please reupload as basic text.

**Comment by jlipps** [comment]
The main issue I see is that you are using ancient versions of Appium and the UiAutomator2 driver. Use Appium 2 and the latest version of the driver and see if the issue persists.

**Comment by mykola-mokhnach** [comment]
^ This is most likely happening because of an outdated client. Make sure not only the server but also the client is up to date.

**Comment by mykola-mokhnach** [comment]
> are u saying about my eclipse?

under "client" I mean the particular API library for your language. In case of java it is https://github.com/appium/java-client

**Comment by mykola-mokhnach** [comment]
It has nothing to do with java language version. Make sure you use the most recent version of the java-client lib

**Comment by jlipps** [comment]
yes, the driver is only finding the NATIVE_APP context. that's why i recommended upgrading the server/driver.

**Comment by jlipps** [comment]
```
[Appium] Appium v1.22.3 creating new AndroidUiautomator2Driver (v1.70.1) session
```

this is not the latest appium. make sure you've followed [the instructions](https://appium.github.io/appium/docs/en/2.0/quickstart/) to install appium 2

**Comment by mykola-mokhnach** [comment]
You should also make sure the web view is detected by Chrome as described in https://developer.chrome.com/docs/devtools/remote-debugging/

If the above does not detect it then there is no chance something could be seen in the Appium driver.

**Comment by jlipps** [comment]
`/wd/hub/session/session` is not a valid webdriver url. it looks like you have entered an incorrect server url in your connection string in your test. by default appium 2 does not accept commands on `/wd/hub` but on `/`

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by jlipps** [comment]
that version of chromedriver is ancient, and unfortunately not supported by the latest drivers

**Comment by jlipps** [comment]
@nimairodrigues you're using an invalid locator strategy. `id` is not one of the strategies that chromedriver knows about.
