### ISSUE TITLE
driver.setLocation() not working - exited with code 255

### ISSUE THREAD

**Issue by RahulNethi** [appium/appium#18043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating to Appium 2, driver.setLocation stopped working for Android.

[debug] [38;5;32m[AndroidUiautomator2Driver@db17 (36ea3fa5)][0m Encountered internal error running command: Error executing adbExec. Original error: 'Command '/Users/rahul/Library/Android/sdk/platform-tools/adb -P 5037 -s 3043493454573398 shell am start-foreground-service -e longitude -79.8013 -e latitude 43.4026 -e altitude 10 io.appium.settings/.LocationService' exited with code 255'; Command output: Error: Not found; no service started.

### Expected Behavior

Set the device location successfully and continue the execution.

### Minimal Reproducible Example

driver.setLocation(new Location(latitude, longitude, altitude));

### Environment

- Appium version: v2.0.0-beta.48
- Last Appium version that did not exhibit the issue (if applicable): v1.22.3
- Node.js: 6.17.1
- Npm: 8.15.0
- Android 10
- Real Device
- macOS 13.0.1

### Link to Appium Logs

https://gist.github.com/RahulNethi/97f0bfc35062e7d84402c93e6f05d436

**Comment by mykola-mokhnach** [comment]
Please provide the device logcat output for the time period when the error happens

**Comment by RahulNethi** [comment]
[logcat.txt](https://github.com/appium/appium/files/10395647/logcat.txt)

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't find any suspicious traces in the log above

**Comment by RahulNethi** [comment]
When i try to execute the following command in terminal,

adb -s 3043493454573398 shell am start-foreground-service -e longitude -79.8013 -e latitude 43.4026 -e altitude 10 io.appium.settings/.LocationService

I see,

Starting service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=io.appium.settings/.LocationService (has extras) }
Error: Not found; no service started.

**Comment by mykola-mokhnach** [comment]
does it work is you start the service like `adb -s 3043493454573398 shell am start-foreground-service -e longitude -79.8013 -e latitude 43.4026 -e altitude 10 -n io.appium.settings/.LocationService` ?

**Comment by RahulNethi** [comment]
Nope does not work. Same error.

**Comment by mykola-mokhnach** [comment]
Also check https://stackoverflow.com/questions/12347440/android-adb-shell-am-startservice-error-not-found

**Comment by RahulNethi** [comment]
Same Error, tried following:

$ adb -s 3043493454573398 shell am start -n io.appium.settings/io.appium.settings.Settings
Starting: Intent { cmp=io.appium.settings/.Settings }

$ adb -s 3043493454573398 shell am start-foreground-service -e longitude -79.8013 -e latitude 43.4026 -e altitude 10 -n io.appium.settings/.LocationService
Starting service: Intent { cmp=io.appium.settings/.LocationService (has extras) }
Error: Not found; no service started.

**Comment by mykola-mokhnach** [comment]
maybe try another device...

**Comment by RahulNethi** [comment]
The above command works on Appium Settings v4.2.3 but not on Appium Settings v5.0.0

**Comment by mykola-mokhnach** [comment]
I was not able to repro this issue. If someone has more ideas on how to approach it then feel free to join this thread.

**Comment by mykola-mokhnach** [comment]
The issue seems to be specific to the local testing env. Thus closing.

**Comment by jaswirs** [comment]
Is there any solution to this issue? I am facing the same issue for Android 10 devices when using appium 2.0.1.  Did not face the issue on other Android version (9, 11, & 12)

## Environment
Appium version: v2.0.1
Node.js: v20.5.1
Npm: 9.8.0
**Android 10** - Both real device & android emulator
macOS 12.6.1
 

### Steps to repro:

1. Install [appium settings](https://github.com/appium/io.appium.settings/releases) v5.x.x
2. Run set location ADB command. E.q.  `adb shell am start-foreground-service -e longitude 103.9885585809751 -e latitude 1.3546854637089758 -e altitude 10 io.appium.settings/.LocationService`
3. Getting error `Error: Not found; no service started.`

The only related logcat is `W ActivityManager: Appop Denial: Accessing service io.appium.settings/.LocationService from pid=19371, uid=2000 requires appop FINE_LOCATION`

[location_logcat.log](https://github.com/appium/appium/files/12783849/location_logcat.log)
