### ISSUE TITLE
Getting NoSuchElement exception on webview even when the driver context has been switched to web view

### ISSUE THREAD

**Issue by kushalchitransh** [appium/appium#18054]
I am trying to automate my app on Android Simulator in Android Studio using Java and Appium.
My code works fine in Native view however in case of webview it gives nosuchelementexception.
Same locators are working fine on mobile web chrome browser in similar flow.

 DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "Android Test");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.xyz.mobile");
        capabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, "com.xyz.mobile.common.splash.SplashActivity");
        capabilities.setCapability("enableWebviewDetailsCollection", "true");
        capabilities.setCapability("newCommandTimeout", 180);
        capabilities.setCapability("autoAcceptAlerts", "true");
        capabilities.setCapability("autoWebviewTimeout", 20);
        capabilities.setCapability("ensureWebviewsHavePages", "true");
        capabilities.setCapability("fullContextList", "true");
        capabilities.setCapability("automationName", "UiAutomator2");
        capabilities.setCapability("appium:chromeOptions", ImmutableMap.of("androidPackage", "com.android.chrome"));
        capabilities.setCapability("appium:chromeOptions", ImmutableMap.of("w3c", false));
        driver = new AndroidDriver(new URL("http://localhost:4723/wd/hub"), capabilities);
[webview context switch logs.txt](https://github.com/appium/appium/files/10411450/webview.context.switch.logs.txt)

Can you please suggest some solution with Appium version 1.21.0

**Comment by mykola-mokhnach** [comment]
Elements location in web context is fully controlled by chromedriver. UIA2 driver acts as a simple proxy there. Consider reporting the issue to Google if you assume this is a bug.
