### ISSUE TITLE
WDA | Crashed during the test

### ISSUE THREAD

**Issue by nskcashHH** [appium/appium#18068]
Used:
Appium v2.0.0-beta.52
Xcuitest@4.16.9 
WebDriverAgent-4.10.19
Simulator iOS 15.2

In some places of the application, after performing a certain step, the WDA crashes. Stable crashes occur in places where there are memory leaks in the application, searching for an element and clicking on it takes longer than usual at this moment. 

There are no crashes on the WebDriverAgent-4.10.1 version, newer versions all fall.
I attach the log:

`-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 984E9EF6-FFB4-4C03-9EE0-5F32D10226BB
CrashReporter Key:   07B10086-EA53-1AF2-2B8C-67017A9BE250
Hardware Model:      MacBookPro17,1
Process:             WebDriverAgentRunner-Runner [84204]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/911782CF-F35F-4AAC-90A7-87840516D14D/data/Containers/Bundle/Application/70943DF8-DA41-4C1F-B610-C63674F5A2C7/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner
Identifier:          com.facebook.WebDriverAgentRunner.xctrunner
Version:             1.0 (1)
Code Type:           ARM-64 (Native)
Role:                Non UI
Parent Process:      launchd_sim [64714]
Coalition:           com.apple.CoreSimulator.SimDevice.911782CF-F35F-4AAC-90A7-87840516D14D [44730]
Responsible Process: SimulatorTrampoline [10513]

Date/Time:           2023-01-16 11:55:58.2207 +0300
Launch Time:         2023-01-16 11:50:41.9108 +0300
OS Version:          macOS 13.1 (22C65)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	       0x1803e1174 __exceptionPreprocess + 216
1   libobjc.A.dylib               	       0x180193384 objc_exception_throw + 56
2   WebDriverAgentLib             	       0x1055ff448 -[XCUIElement(FBUtilities) fb_takeSnapshot] + 712
3   WebDriverAgentLib             	       0x1055bc5d8 -[XCUIApplication(FBAlert) fb_alertElement] + 308 (XCUIApplication+FBAlert.m:87)
4   WebDriverAgentLib             	       0x1055d688c __35-[FBAlertsMonitor scheduleNextTick]_block_invoke.1 + 256 (FBAlertsMonitor.m:53)
5   libdispatch.dylib             	       0x180108db0 _dispatch_call_block_and_release + 24
6   libdispatch.dylib             	       0x18010a5a4 _dispatch_client_callout + 16
7   libdispatch.dylib             	       0x180117fc8 _dispatch_main_queue_callback_4CF + 996
8   CoreFoundation                	       0x18034fcd4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
9   CoreFoundation                	       0x18034a244 __CFRunLoopRun + 2448
10  CoreFoundation                	       0x1803493a8 CFRunLoopRunSpecific + 572
11  Foundation                    	       0x180811e14 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
12  WebDriverAgentLib             	       0x1055c0910 -[FBWebServer startServing] + 324 (FBWebServer.m:80)
13  WebDriverAgentRunner          	       0x1036a76c0 -[UITestingUITests testRunner] + 72 (UITestingUITests.m:44)
14  CoreFoundation                	       0x1803e75f0 __invoking___ + 144
15  CoreFoundation                	       0x1803e4b90 -[NSInvocation invoke] + 300
16  XCTestCore                    	       0x10350db58 +[XCTFailableInvocation invokeStandardConventionInvocation:completion:] + 64
17  XCTestCore                    	       0x10350db10 __90+[XCTFailableInvocation invokeInvocation:withTestMethodConvention:lastObservedErrorIssue:]_block_invoke_3 + 24
18  XCTestCore                    	       0x10350d5b8 __81+[XCTFailableInvocation invokeWithAsynchronousWait:lastObservedErrorIssue:block:]_block_invoke.5 + 80
19  XCTestCore                    	       0x1034d5570 +[XCTSwiftErrorObservation observeErrorsInBlock:] + 132
20  XCTestCore                    	       0x10350d44c +[XCTFailableInvocation invokeWithAsynchronousWait:lastObservedErrorIssue:block:] + 388
21  XCTestCore                    	       0x10350d8d0 +[XCTFailableInvocation invokeInvocation:withTestMethodConvention:lastObservedErrorIssue:] + 252
22  XCTestCore                    	       0x10350dbc8 +[XCTFailableInvocation invokeInvocation:lastObservedErrorIssue:] + 68
23  XCTestCore                    	       0x1034fdee4 __24-[XCTestCase invokeTest]_block_invoke.78 + 96
24  XCTestCore                    	       0x1034ce8cc -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 156
25  XCTestCore                    	       0x1034fdb2c -[XCTestCase invokeTest] + 732
26  XCTestCore                    	       0x1034fef64 __26-[XCTestCase performTest:]_block_invoke.119 + 32
27  XCTestCore                    	       0x1034ce8cc -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 156
28  XCTestCore                    	       0x1034fead4 __26-[XCTestCase performTest:]_block_invoke.110 + 404
29  XCTestCore                    	       0x1034e7a60 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
30  XCTestCore                    	       0x1034e798c +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
31  XCTestCore                    	       0x1034fe7a0 -[XCTestCase performTest:] + 248
32  XCTestCore                    	       0x1034bea78 -[XCTest runTest] + 44
33  XCTestCore                    	       0x1034ea300 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64
34  XCTestCore                    	       0x1034ea1e4 __27-[XCTestSuite performTest:]_block_invoke + 160
35  XCTestCore                    	       0x1034e9cf8 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
36  XCTestCore                    	       0x1034e7a60 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
37  XCTestCore                    	       0x1034e798c +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
38  XCTestCore                    	       0x1034e9ca0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152
39  XCTestCore                    	       0x1034e9f10 -[XCTestSuite performTest:] + 188
40  XCTestCore                    	       0x1034bea78 -[XCTest runTest] + 44
41  XCTestCore                    	       0x1034ea300 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64
42  XCTestCore                    	       0x1034ea1e4 __27-[XCTestSuite performTest:]_block_invoke + 160
43  XCTestCore                    	       0x1034e9cf8 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
44  XCTestCore                    	       0x1034e7a60 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
45  XCTestCore                    	       0x1034e798c +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
46  XCTestCore                    	       0x1034e9ca0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152
47  XCTestCore                    	       0x1034e9f10 -[XCTestSuite performTest:] + 188
48  XCTestCore                    	       0x1034bea78 -[XCTest runTest] + 44
49  XCTestCore                    	       0x1034ea300 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64
50  XCTestCore                    	       0x1034ea1e4 __27-[XCTestSuite performTest:]_block_invoke + 160
51  XCTestCore                    	       0x1034e9cf8 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
52  XCTestCore                    	       0x1034e7a60 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
53  XCTestCore                    	       0x1034e798c +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
54  XCTestCore                    	       0x1034e9ca0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152
55  XCTestCore                    	       0x1034e9f10 -[XCTestSuite performTest:] + 188
56  XCTestCore                    	       0x1034bea78 -[XCTest runTest] + 44
57  XCTestCore                    	       0x1034c02ec __89-[XCTTestRunSession executeTestsWithIdentifiers:skippingTestsWithIdentifiers:completion:]_block_invoke + 100
58  XCTestCore                    	       0x1034e7a60 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
59  XCTestCore                    	       0x1034e798c +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
60  XCTestCore                    	       0x1034c01e8 -[XCTTestRunSession executeTestsWithIdentifiers:skippingTestsWithIdentifiers:completion:] + 252
61  XCTestCore                    	       0x1035199d0 __72-[XCTExecutionWorker enqueueTestIdentifiersToRun:testIdentifiersToSkip:]_block_invoke_2 + 108
62  XCTestCore                    	       0x103519af0 -[XCTExecutionWorker runWithError:] + 100
63  XCTestCore                    	       0x1034e4f90 __25-[XCTestDriver _runTests]_block_invoke.184 + 52
64  XCTestCore                    	       0x1034c8224 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 256
65  XCTestCore                    	       0x1034e4c2c -[XCTestDriver _runTests] + 1016
66  XCTestCore                    	       0x1034bef60 _XCTestMain + 84
67  WebDriverAgentRunner-Runner   	       0x102e39cbc -[_XCTRunnerAppDelegate application:didFinishLaunchingWithOptions:] + 0
68  WebDriverAgentRunner-Runner   	       0x102e39ca0 _XCTRunnerRunTests + 0
69  CoreFoundation                	       0x180350030 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
70  CoreFoundation                	       0x18034f2f4 __CFRunLoopDoBlocks + 408
71  CoreFoundation                	       0x180349bb0 __CFRunLoopRun + 764
72  CoreFoundation                	       0x1803493a8 CFRunLoopRunSpecific + 572
73  GraphicsServices              	       0x18c03c5ec GSEventRunModal + 160
74  UIKitCore                     	       0x184d937ac -[UIApplication _run] + 992
75  UIKitCore                     	       0x184d982e8 UIApplicationMain + 112
76  WebDriverAgentRunner-Runner   	       0x102e39e70 main + 160
77  dyld_sim                      	       0x102fd5ca0 start_sim + 20
78  dyld                          	       0x103171e50 start + 2544
79  ???                           	0x1012000000000000 ???

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1c997d0cc __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1c99d21e8 pthread_kill + 256
2   libsystem_c.dylib             	       0x1800fe3d8 abort + 120
3   libc++abi.dylib               	       0x18022de94 abort_message + 128
4   libc++abi.dylib               	       0x18021fc98 demangling_terminate_handler() + 296
5   libobjc.A.dylib               	       0x180176e84 _objc_terminate() + 124
6   libc++abi.dylib               	       0x18022d358 std::__terminate(void (*)()) + 16
7   libc++abi.dylib               	       0x18022d300 std::terminate() + 60
8   libdispatch.dylib             	       0x18010a5b8 _dispatch_client_callout + 36
9   libdispatch.dylib             	       0x180117fc8 _dispatch_main_queue_callback_4CF + 996
10  CoreFoundation                	       0x18034fcd4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
11  CoreFoundation                	       0x18034a244 __CFRunLoopRun + 2448
12  CoreFoundation                	       0x1803493a8 CFRunLoopRunSpecific + 572
13  Foundation                    	       0x180811e14 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
14  WebDriverAgentLib             	       0x1055c0910 -[FBWebServer startServing] + 324 (FBWebServer.m:80)
15  WebDriverAgentRunner          	       0x1036a76c0 -[UITestingUITests testRunner] + 72 (UITestingUITests.m:44)
16  CoreFoundation                	       0x1803e75f0 __invoking___ + 144
17  CoreFoundation                	       0x1803e4b90 -[NSInvocation invoke] + 300
18  XCTestCore                    	       0x10350db58 +[XCTFailableInvocation invokeStandardConventionInvocation:completion:] + 64
19  XCTestCore                    	       0x10350db10 __90+[XCTFailableInvocation invokeInvocation:withTestMethodConvention:lastObservedErrorIssue:]_block_invoke_3 + 24
20  XCTestCore                    	       0x10350d5b8 __81+[XCTFailableInvocation invokeWithAsynchronousWait:lastObservedErrorIssue:block:]_block_invoke.5 + 80
21  XCTestCore                    	       0x1034d5570 +[XCTSwiftErrorObservation observeErrorsInBlock:] + 132
22  XCTestCore                    	       0x10350d44c +[XCTFailableInvocation invokeWithAsynchronousWait:lastObservedErrorIssue:block:] + 388
23  XCTestCore                    	       0x10350d8d0 +[XCTFailableInvocation invokeInvocation:withTestMethodConvention:lastObservedErrorIssue:] + 252
24  XCTestCore                    	       0x10350dbc8 +[XCTFailableInvocation invokeInvocation:lastObservedErrorIssue:] + 68
25  XCTestCore                    	       0x1034fdee4 __24-[XCTestCase invokeTest]_block_invoke.78 + 96
26  XCTestCore                    	       0x1034ce8cc -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 156
27  XCTestCore                    	       0x1034fdb2c -[XCTestCase invokeTest] + 732
28  XCTestCore                    	       0x1034fef64 __26-[XCTestCase performTest:]_block_invoke.119 + 32
29  XCTestCore                    	       0x1034ce8cc -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 156
30  XCTestCore                    	       0x1034fead4 __26-[XCTestCase performTest:]_block_invoke.110 + 404
31  XCTestCore                    	       0x1034e7a60 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
32  XCTestCore                    	       0x1034e798c +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
33  XCTestCore                    	       0x1034fe7a0 -[XCTestCase performTest:] + 248
34  XCTestCore                    	       0x1034bea78 -[XCTest runTest] + 44
35  XCTestCore                    	       0x1034ea300 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64
36  XCTestCore                    	       0x1034ea1e4 __27-[XCTestSuite performTest:]_block_invoke + 160
37  XCTestCore                    	       0x1034e9cf8 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
38  XCTestCore                    	       0x1034e7a60 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
39  XCTestCore                    	       0x1034e798c +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
40  XCTestCore                    	       0x1034e9ca0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152
41  XCTestCore                    	       0x1034e9f10 -[XCTestSuite performTest:] + 188
42  XCTestCore                    	       0x1034bea78 -[XCTest runTest] + 44
43  XCTestCore                    	       0x1034ea300 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64
44  XCTestCore                    	       0x1034ea1e4 __27-[XCTestSuite performTest:]_block_invoke + 160
45  XCTestCore                    	       0x1034e9cf8 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
46  XCTestCore                    	       0x1034e7a60 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
47  XCTestCore                    	       0x1034e798c +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
48  XCTestCore                    	       0x1034e9ca0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152
49  XCTestCore                    	       0x1034e9f10 -[XCTestSuite performTest:] + 188
50  XCTestCore                    	       0x1034bea78 -[XCTest runTest] + 44
51  XCTestCore                    	       0x1034ea300 -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64
52  XCTestCore                    	       0x1034ea1e4 __27-[XCTestSuite performTest:]_block_invoke + 160
53  XCTestCore                    	       0x1034e9cf8 __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40
54  XCTestCore                    	       0x1034e7a60 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
55  XCTestCore                    	       0x1034e798c +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
56  XCTestCore                    	       0x1034e9ca0 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152
57  XCTestCore                    	       0x1034e9f10 -[XCTestSuite performTest:] + 188
58  XCTestCore                    	       0x1034bea78 -[XCTest runTest] + 44
59  XCTestCore                    	       0x1034c02ec __89-[XCTTestRunSession executeTestsWithIdentifiers:skippingTestsWithIdentifiers:completion:]_block_invoke + 100
60  XCTestCore                    	       0x1034e7a60 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172
61  XCTestCore                    	       0x1034e798c +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 140
62  XCTestCore                    	       0x1034c01e8 -[XCTTestRunSession executeTestsWithIdentifiers:skippingTestsWithIdentifiers:completion:] + 252
63  XCTestCore                    	       0x1035199d0 __72-[XCTExecutionWorker enqueueTestIdentifiersToRun:testIdentifiersToSkip:]_block_invoke_2 + 108
64  XCTestCore                    	       0x103519af0 -[XCTExecutionWorker runWithError:] + 100
65  XCTestCore                    	       0x1034e4f90 __25-[XCTestDriver _runTests]_block_invoke.184 + 52
66  XCTestCore                    	       0x1034c8224 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 256
67  XCTestCore                    	       0x1034e4c2c -[XCTestDriver _runTests] + 1016
68  XCTestCore                    	       0x1034bef60 _XCTestMain + 84
69  WebDriverAgentRunner-Runner   	       0x102e39cbc _XCTRunnerRunTests + 28
70  WebDriverAgentRunner-Runner   	       0x102e39ca0 __46-[_XCTRunnerAppDelegate runTestsInBackground:]_block_invoke + 12
71  CoreFoundation                	       0x180350030 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
72  CoreFoundation                	       0x18034f2f4 __CFRunLoopDoBlocks + 408
73  CoreFoundation                	       0x180349bb0 __CFRunLoopRun + 764
74  CoreFoundation                	       0x1803493a8 CFRunLoopRunSpecific + 572
75  GraphicsServices              	       0x18c03c5ec GSEventRunModal + 160
76  UIKitCore                     	       0x184d937ac -[UIApplication _run] + 992
77  UIKitCore                     	       0x184d982e8 UIApplicationMain + 112
78  WebDriverAgentRunner-Runner   	       0x102e39e70 main + 160
79  dyld_sim                      	       0x102fd5ca0 start_sim + 20
80  dyld                          	       0x103171e50 start + 2544

Thread 1:: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib        	       0x1c99752ac mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1c9986154 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x1c997d4b8 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1c997561c mach_msg + 20
4   CoreFoundation                	       0x18034f810 __CFRunLoopServiceMachPort + 368
5   CoreFoundation                	       0x180349d24 __CFRunLoopRun + 1136
6   CoreFoundation                	       0x1803493a8 CFRunLoopRunSpecific + 572
7   Foundation                    	       0x180811e14 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
8   Foundation                    	       0x1808120cc -[NSRunLoop(NSRunLoop) runUntilDate:] + 88
9   UIKitCore                     	       0x184e47b64 -[UIEventFetcher threadMain] + 472
10  Foundation                    	       0x18083b97c __NSThread__start__ + 788
11  libsystem_pthread.dylib       	       0x1c99d24e4 _pthread_start + 116
12  libsystem_pthread.dylib       	       0x1c99cd6cc thread_start + 8

Thread 2:
0   libsystem_pthread.dylib       	       0x1c99cd6b8 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x1c99cd6b8 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x1c99cd6b8 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x1c99cd6b8 start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	       0x1c99cd6b8 start_wqthread + 0

Thread 7:
0   libsystem_pthread.dylib       	       0x1c99cd6b8 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000180230f81   x5: 0x000000016cfc5a30   x6: 0x000000000000006e   x7: 0x0000000000000000
    x8: 0x0000000103204240   x9: 0x876293e411656474  x10: 0x000000016cfc5490  x11: 0x000000000000000b
   x12: 0x0000000000000000  x13: 0x000000007883a800  x14: 0x0000000000000010  x15: 0x0000000000000000
   x16: 0x0000000000000148  x17: 0x0000000000000002  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000103204240  x21: 0x0000000000000103  x22: 0x0000000103204320  x23: 0x00000001d80a8d40
   x24: 0x000000000000000f  x25: 0x0000600002827f00  x26: 0x0000600005c1f800  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016cfc59a0   lr: 0x00000001c99d21e8
    sp: 0x000000016cfc5980   pc: 0x00000001c997d0cc cpsr: 0x40001000
   far: 0x0000000180220000  esr: 0x56000080  Address size fault

Binary Images:
       0x1c9974000 -        0x1c99abfff libsystem_kernel.dylib (*) <eb0327ee-cb9c-37ed-ab6a-e9af74e814f0> /usr/lib/system/libsystem_kernel.dylib
       0x1c99cb000 -        0x1c99d7fff libsystem_pthread.dylib (*) <51c613e3-4abf-359c-b275-2608bb1be0b6> /usr/lib/system/libsystem_pthread.dylib
       0x18008a000 -        0x180106fff libsystem_c.dylib (*) <9c7d30ea-2487-32d2-a022-bca0a15628c4> /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib
       0x18021b000 -        0x180233fff libc++abi.dylib (*) <b009c23d-e020-341d-b65b-f75fa69813fb> /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libc++abi.dylib
       0x180172000 -        0x1801a2fff libobjc.A.dylib (*) <22330d97-ba81-30f1-ba94-b9879f9f23bf> /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libobjc.A.dylib
       0x180107000 -        0x180149fff libdispatch.dylib (*) <00a1d5e5-18c3-3ff6-b4b1-34e1d3856727> /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib
       0x1802cb000 -        0x180677fff com.apple.CoreFoundation (6.9) <3b05273d-3bbf-321d-8274-b848d167fd37> /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
       0x1806eb000 -        0x1809acfff com.apple.Foundation (6.9) <19f16173-af39-3bfe-aef4-ec9cb4d4ffa0> /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
       0x1055b0000 -        0x105673fff com.facebook.wda.lib (1.0) <a279a9a3-87c9-39b3-b918-342a2e2e2d25> /Users/USER/Library/Developer/Xcode/DerivedData/WebDriverAgent-aiaphpwopgkfxrfipsuendpqcjzt/Build/Products/Debug-iphonesimulator/WebDriverAgentLib.framework/WebDriverAgentLib
       0x1036a4000 -        0x1036a7fff com.facebook.wda.runner (1.0) <948a8e67-63e5-3950-bc13-af9ddb759c65> /Users/USER/Library/Developer/CoreSimulator/Devices/911782CF-F35F-4AAC-90A7-87840516D14D/data/Containers/Bundle/Application/70943DF8-DA41-4C1F-B610-C63674F5A2C7/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner
       0x1034bc000 -        0x103557fff com.apple.dt.XCTestCore (14.2) <c85382ff-589b-390c-8762-b2b4acf75d13> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCTestCore.framework/XCTestCore
       0x102e34000 -        0x102e3bfff com.facebook.WebDriverAgentRunner.xctrunner (1.0) <1d3d7207-3688-3183-85da-936d57a99258> /Users/USER/Library/Developer/CoreSimulator/Devices/911782CF-F35F-4AAC-90A7-87840516D14D/data/Containers/Bundle/Application/70943DF8-DA41-4C1F-B610-C63674F5A2C7/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner
       0x18c039000 -        0x18c041fff com.apple.GraphicsServices (1.0) <01858b6b-f559-3623-9aaf-d03b35fccf3c> /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
       0x184189000 -        0x185613fff com.apple.UIKitCore (1.0) <08a5560d-3f2b-3b52-a202-add2a39b5d30> /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
       0x102fd4000 -        0x10300ffff dyld_sim (*) <4f051b2d-f44f-31d5-8c60-061d25c5d57e> /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/dyld_sim
       0x10316c000 -        0x1031f7fff dyld (*) <487cfdeb-9b07-39bf-bfb9-970b61aea2d1> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

EOF
`

**Comment by mykola-mokhnach** [comment]
The crash seems to be specific to the local env
