### ISSUE TITLE
Unable to create session with Appium CLI 1.22.0 

### ISSUE THREAD

**Issue by JYOTIPRAKASH225** [appium/appium#18069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to create session with Appium CLI 1.22.0.

### Expected Behavior

I should be able to create session.

### Minimal Reproducible Example

https://gist.github.com/JYOTIPRAKASH225/e5e7e82795a206e0276ff88dcfb990a1

### Environment

Operating system: Mac OS
Appium CLI version: 1.22.0
Node.js version: v18.8.0
npm version:  8.19.0

### Link to Appium Logs

https://gist.github.com/JYOTIPRAKASH225/e5e7e82795a206e0276ff88dcfb990a1

**Comment by jlipps** [comment]
appium 1.x is no longer supported. Use Appium 2.x.
