### ISSUE TITLE
Appium Inspector fails to run because XCode build fails with error 70

### ISSUE THREAD

**Issue by takeshi-yanagita** [appium/appium#18077]
### The Problem
I'm trying to set up Appium 2 for iOS testing by running Appium Inspector.
However, I'm running into an issue where whenever I try to initiate a session, it fails to run because XCode fails to build webdriveragent.

### Environment
Appium version: 2.0.0-beta.44
Appium Inspector version: 2022.11.1
MacOS Monterey: 12.5.1
XCode: 14.1
Simulator iOS Version: 14.5

### Logs
GIST: [appium with xcode logs](https://gist.github.com/takeshi-yanagita/b065bf08996667ac85e017bdf8d0ef15#file-appium-logs-with-xcode-enabled)

### Details
I have an iPhone 12 Pro Simulator running iOS 14.5.
The simulator is running fine, and whenever I build the webdriveragent project directly from XCode, it works.
However the build command that appium inspector calls seems to fail every single time.

**Comment by mykola-mokhnach** [comment]
I can observe several potential issues that are mentioned in logs:

> [XCUITestDriver@be59] 'platformVersion' capability ('undefined') is not a valid version number. Consider fixing it or be ready to experience an inconsistent driver behavior.

The second issue is that the same session is started at least twice. Make sure you only start it once or consider running the server with --session-override option enabled.

Also, what is the output of the below xcodebuild command being executed manually from Terminal?

> [debug] [XCUITestDriver@be59 (888ee87f)] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/takeshi.yanagita/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=E760D93C-4D75-44C6-B9D0-AA49C435AC6F IPHONEOS_DEPLOYMENT_TARGET=14.5 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory

**Comment by takeshi-yanagita** [comment]
@mykola-mokhnach 
Thanks for the response.

> Consider fixing it or be ready to experience an inconsistent driver behavior.

I had omitted it to try and have as generic a session as possible.  I re-added it into future calls.

> The second issue is that the same session is started at least twice. Make sure you only start it once or consider running the server with --session-override option enabled.

I have added '--session-override option' into my appium server call.
However, the multiple sessions being started is actually Appium Inspector's doing, I only click "Start Session" once.

>Also, what is the output of the below xcodebuild command being executed manually from Terminal?

It outputs the same as what's outputted in the appium logs.

`JP-FVFZ91FSL414:~ takeshi.yanagita$ /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -verbose build-for-testing test-without-building -project /Users/takeshi.yanagita/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/takeshi.yanagita/Library/Developer/Xcode/DerivedData/WebDriverAgent-gaejngjcrfawkgaxbemvhslsrmrw -destination id=E760D93C-4D75-44C6-B9D0-AA49C435AC6F IPHONEOS_DEPLOYMENT_TARGET=14.5 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -verbose build-for-testing test-without-building -project /Users/takeshi.yanagita/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/takeshi.yanagita/Library/Developer/Xcode/DerivedData/WebDriverAgent-gaejngjcrfawkgaxbemvhslsrmrw -destination id=E760D93C-4D75-44C6-B9D0-AA49C435AC6F IPHONEOS_DEPLOYMENT_TARGET=14.5 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO

User defaults from command line:
    IDEDerivedDataPathOverride = /Users/takeshi.yanagita/Library/Developer/Xcode/DerivedData/WebDriverAgent-gaejngjcrfawkgaxbemvhslsrmrw
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    COMPILER_INDEX_STORE_ENABLE = NO
    GCC_TREAT_WARNINGS_AS_ERRORS = 0
    IPHONEOS_DEPLOYMENT_TARGET = 14.5

Prepare packages
2023-01-18 14:49:39.329 xcodebuild[3583:18443772] Writing error result bundle to /var/folders/bz/4r2jmvvj4xg19_lrskvcpkkjgwl0_6/T/ResultBundle_2023-18-01_14-49-0039.xcresult
xcodebuild: error: Failed to build project WebDriverAgent with scheme WebDriverAgentRunner.
	Reason: Could not initialize core
JP-FVFZ91FSL414:~ takeshi.yanagita$ 
`

**Comment by mykola-mokhnach** [comment]
> However, the multiple sessions being started is actually Appium Inspector's doing, I only click "Start Session" once.

This could be an issue of the inspector itself. Consider reporting it to https://github.com/appium/appium-inspector

> It outputs the same as what's outputted in the appium logs. I even added the -verbose option.

This looks like an Xcode issue to me. I've found multiple matches to https://www.google.com/search?client=firefox-b-d&q=%22Reason%3A+Could+not+initialize+core%22 search request. Perhaps Xcode installation itself is buggy/broken or there is something wrong with the simulator. In any case there is nothing that could be done on Appium side if xcodebuild is unable to build the project.

**Comment by takeshi-yanagita** [comment]
Understood, I'll try and ask in the Appium discussion board.
