### ISSUE TITLE
Bug:Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by satyagy** [appium/appium#18073]
We are trying to set up appium in macOS 13.0.1 to open a website in safari browser but it is throwing error. Please find the attached logs. Also it is  giving "No WDAs on the device". So please suggest required steps to setup properly.
[appium-server-logs.txt](https://github.com/appium/appium/files/10434589/appium-server-logs.txt)

**Comment by nskcashHH** [comment]
> We are trying to set up appium in macOS 13.0.1 to open a website in safari browser but it is throwing error. Please find the attached logs. Also it is giving "No WDAs on the device". So please suggest required steps to setup properly.
> [appium-server-logs.txt](https://github.com/appium/appium/files/10434589/appium-server-logs.txt)

You need to use Appium 2.0

**Comment by KazuCocoa** [comment]
And please fill in the issue template
