### ISSUE TITLE
bug: driver.launchApp with safari and url is launching siri command rather than opening url

### ISSUE THREAD

**Issue by krishtoautomate** [appium/appium#18070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 driver.executeScript("mobile:launchApp", ImmutableMap.of("bundleId","com.apple.mobilesafari")
                    ,"args", url);

opening siri command with url

### Expected Behavior

the behaviour should be similar to -

capability :
 browserName = safari
driver.geturl(url)
which navigates to url without invoking siri

### Minimal Reproducible Example

capability:
bundleId = appBundleid

 driver.executeScript("mobile:launchApp", ImmutableMap.of("bundleId","com.apple.mobilesafari")
                    ,"args", url);

### Environment

- Operating system: mac-os
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): xcuitest
- Appium plugin(s) and their version(s): xcuitest
- Platform and version under test: ios 
- Real device

**Comment by jlipps** [comment]
This is actually the expected behaviour. This is just what happens on iOS unfortunately. To make it reliable, just open safari without args, type the url into the address bar and hit the button. see https://www.headspin.io/blog/reliably-opening-deep-links-across-platforms-and-devices for more info

**Comment by krishtoautomate** [comment]
@jlipps may I know why behaviour is different if capability is set as browserName:Safari where i am able to make driver.get(url) without handling url text fields

**Comment by KazuCocoa** [comment]
It works in WebView context by default if browserName:Safari was given while the above case works in native app context, it is deeplink. After launching mobilesafari, you can manually switch to WebView context, then can do the same thing

**Comment by jlipps** [comment]
oh yeah, if you want to launch a web url, make sure you're in a web context first and then just call navigate/seturl.

**Comment by jlipps** [comment]
there's no way to load a web url while launching safari as an argument.

**Comment by krishtoautomate** [comment]
I tried switching to safari bundleid and changing to web context and calling driver.get(url) still no luck. The magic only lies when default launch is safari with capabilities. Would like to understand why their is difference  in two ways of launching. Only 1 case navigate url is working

**Comment by KazuCocoa** [comment]
Could you share the full log as GIST when you tried _I tried switching to safari bundleid and changing to web context and calling driver.get(url) still no luck_?

I only tried on a real device right now, but both worked as same.

**Comment by krishtoautomate** [comment]
Did u use safari in capability or start safari bundle id with mobile command launch app?

Using safari with browserName capability and url navigate is working for me as well.

**Comment by krishtoautomate** [comment]
> Could you share the full log as GIST when you tried _I tried switching to safari bundleid and changing to web context and calling driver.get(url) still no luck_?
> 
> I only tried on a real device right now, but both worked as same.

            driver.executeScript("mobile:launchApp", ImmutableMap.of("bundleId", "com.apple.mobilesafari"));

            sleep(2);

            switchToNativeContext("WEBVIEW");


  protected boolean switchToNativeContext(String context) {
        ArrayList<String> contexts =
                new ArrayList<String>(((IOSDriver) driver).getContextHandles());
        for (String cntext : contexts) {
            log.info("context : " + cntext);
            if (cntext.contains(context)) {
                ((IOSDriver) driver).context(cntext);
                return true;
            }
        }
        return false;
    }

**Comment by KazuCocoa** [comment]
Maybe the get contexts command needs to do a couple of times for iOS.
https://appium.github.io/appium-xcuitest-driver/4.16/execute-methods/#mobile-getcontexts may help to set timeout for the command to get context by one call.

**Comment by krishtoautomate** [comment]
none of them are working. tried reloading contxt twice or adding for/while loop with wait for 10 seconds and tried with capabilities for webcontext or wait for webcontext.

found the issue : if you load some url manually after switching to safari bundleId. Web context is found. if UI is not touched after loading safari browser with launch command -- only NATIVE context is found.

this may be reason why lauching with capabilities dont have any issues as it loads appium default url on launch.

**Comment by jlipps** [comment]
yes, this is a known issue. in some versions of ios the user must interact with a webview first before the webview is made available for debugging. a tap in the webview region might suffice also.

**Comment by krishtoautomate** [comment]
is it possible to load url on launch command similar to -- capability : browser:safari where default appium url will load.

**Comment by jlipps** [comment]
you can try the [`appium:safariInitialUrl`](https://appium.github.io/appium-xcuitest-driver/4.16/capabilities/) capability

**Comment by juanfeeld** [comment]
I used this in a simulator and worked perfect. But in Browserstack (which I think the behaviors is the same than real devices) opens a suggestion to turn on Siri. @krishtoautomate 

this is the module that I used in iOS: 
```
    driver.execute('mobile: deepLink', {
      url: link,
    });
```

**Comment by krishtoautomate** [comment]
It should change to WEB_context and launch url instead of triggering siri.

may be the best way is : if safari is active, the context should be default to web context instead of user trying to switch.
