### ISSUE TITLE
Vulnerability in deprecated xmldom

### ISSUE THREAD

**Issue by eppisapiafsl** [appium/appium#18082]
`appium-ios-driver` and `appium-faker-driver`  requires install `xmldom` which was migrated to `@xmldom/xmldom`

This lead to a vulnerability report due xmldom versions 0.6.0 and older do not correctly escape special characters when serializing elements removed from their ancestor.

As the `xmldom` was migrating a resolution (yarn override) can't be applied

Can you update these dependencies to use @xmldom/xmldom instead?

**Comment by KazuCocoa** [comment]
What version did you use? I wonder if you reference older modules
appium-ios-driver is no longer maintained as https://github.com/appium-boneyard/appium-ios-driver
appium-fake-driver uses 0.8.6 as https://github.com/appium/appium/blob/master/packages/fake-driver/package.json#L49

**Comment by eppisapiafsl** [comment]
@KazuCocoa I am in the appium version 1.22.3

**Comment by KazuCocoa** [comment]
Then, you may need to use Appium 2 and newer XCUITest etc.
https://appium.github.io/appium/docs/en/2.0/guides/migrating-1-to-2/
At least current developing packages do not have them. We do not apply patches to outdated versions.
