### ISSUE TITLE
bug: Tests run slow when multiple Android emulators are used

### ISSUE THREAD

**Issue by RichardHoOoOo** [appium/appium#18080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used Appium to develop an automated testing tool for Android apps. It basically reads the UI layouts, randomly pick a widget to send event, reads the updated UI layouts, and send new events again...

When I test my tool on a single Android emulator, it can trigger around 3000 events in 1 hour. But when I launch 16 emulators together, it can trigger around 2500 events in 1 hour.

I was testing on a CentOS server with 32 threads and 128G memory. I can observe my testing tool, even running on 16 emulators in parallel, occupies at most 20-22 threads and 32g memory. So the machine's cpu/memory assumption is not high. In this case, why the Appium's script is much slower?

### Expected Behavior

The same number of events should be triggered in the same time budget when running in a single emulator or multiple emulators.

### Minimal Reproducible Example

N.A.

### Environment

- Operating system: CentOS stream 8
- If running via `appium` CLI...
  - Appium CLI version 1.22.2

### Futher Information

Do you have any idea to solve this problem? Is any settings that I missed?

**Comment by mykola-mokhnach** [comment]
Unfortunately the provided information is not enough to make any assumptions.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by artyres1** [comment]
@mykola-mokhnach We experience same issue. Slow script when running multiple emulators. You can simply use an script that start two emulator with unique ports but the result is same. slow

**Comment by artyres1** [comment]
[RichardHoOoOo](https://github.com/RichardHoOoOo) Hey , were you able to solve it?
