### ISSUE TITLE
iautomator2 driver installation in appium 2(ap2.0.0-beta.52) fails

### ISSUE THREAD

**Issue by userUsr38** [appium/appium#18099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

C:\WINDOWS\system32>appium driver install uiautomator2@2.12.1

 Installing 'uiautomator2@2.12.1' using NPM install spec 'appium-uiautomator2-driver@2.12.1'
Error: × Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver@2.12.1 --json' failed with code 1.

STDOUT:OWS\system32>npm -v
8.19.3

STDERR:OWS\system32>appium driver install uiautomator2@2.12.1
npm ERR! code 1
npm ERR! path C:\Users\<>\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install-npm.js
npm ERR! [16:24:22] Error installing Chromedriver: socket hang up
npm ERR! [16:24:22] Error: socket hang up
npm ERR!     at Function.AxiosError.from (C:\Users\ \.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\AxiosError.js:89:14)
npm ERR!     at RedirectableRequest.handleRequestError (C:\Users\ \.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\adapters\http.js:526:25)
npm ERR!     at RedirectableRequest.emit (node:events:525:35)
npm ERR!     at ClientRequest.eventHandlers.<computed> (C:\Users\ \.appium\node_modules\appium-uiautomator2-driver\node_modules\follow-redirects\index.js:14:24)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at Socket.socketOnEnd (node:_http_client:518:9)
npm ERR!     at Socket.emit (node:events:525:35)
npm ERR!     at endReadableNT (node:internal/streams/readable:1358:12)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! [16:24:22] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.
{
  "error": {

### Expected Behavior

should successfully install

### Minimal Reproducible Example

wi also tried to downgrade to npm 6, but i get the same error

### Environment

C:\WINDOWS\system32>node -v
v16.19.0

C:\WINDOWS\system32>npm -v
8.19.3

C:\WINDOWS\system32>appium -v
2.0.0-beta.52

**Comment by mykola-mokhnach** [comment]
> npm ERR! [16:24:22] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.

Have you tried to apply this suggestion?

**Comment by userUsr38** [comment]
i want to have chromedriver downloaded also

**Comment by mykola-mokhnach** [comment]
> Error: socket hang up

This error means the script is unable to contact Google CDN from your network. Either consider using a different accessible mirror CDN or download Chromedriver manually afterwards.

**Comment by userUsr38** [comment]
if i try to download chrome driver before:
C:\Users\ \.appium\node_modules>npm install -g appium-chromedriver@latest
npm ERR! code 1
npm ERR! path C:\Users\\AppData\Roaming\npm\node_modules\appium-chromedriver
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install-npm.js
npm ERR! [17:06:55] Error installing Chromedriver: socket hang up
npm ERR! [17:06:55] Error: socket hang up
npm ERR!     at Function.AxiosError.from (C:\Users\\AppData\Roaming\npm\node_modules\appium-chromedriver\node_modules\axios\lib\core\AxiosError.js:89:14)
npm ERR!     at RedirectableRequest.handleRequestError (C:\Users\\AppData\Roaming\npm\node_modules\appium-chromedriver\node_modules\axios\lib\adapters\http.js:533:25)
npm ERR!     at RedirectableRequest.emit (node:events:525:35)
npm ERR!     at ClientRequest.eventHandlers.<computed> (C:\Users\\AppData\Roaming\npm\node_modules\appium-chromedriver\node_modules\follow-redirects\index.js:14:24)

**Comment by mykola-mokhnach** [comment]
yes, the error is no different from the previous one. Do you have any specific question?

**Comment by userUsr38** [comment]
how can i install uiautomator2? this is the question and you gave me no answer

**Comment by mykola-mokhnach** [comment]
>  Either consider using a different accessible mirror CDN or download Chromedriver manually afterwards.

Does this answer not work?

**Comment by userUsr38** [comment]
```
C:\WINDOWS\system32>appium driver install uiautomator2 APPIUM_SKIP_CHROMEDRIVER_INSTALL=1

[ERROR] Unrecognized arguments: APPIUM_SKIP_CHROMEDRIVER_INSTALL=1
```

how should i use this command?

>

**Comment by mykola-mokhnach** [comment]
https://www3.ntu.edu.sg/home/ehchua/programming/howto/Environment_Variables.html

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
