### ISSUE TITLE
appium 2.0 fails to load chromdriver which is already installed.

### ISSUE THREAD

**Issue by Nfactor26** [appium/appium#18096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I installed chromium driver using command "appium driver install chromium" which was completed successfully. However, when I try to start appium server from cmd by typing appium, it fails to load chromium driver with an error message.

`[Appium] Welcome to Appium v2.0.0-beta.52
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\xxxx\.appium\node_modules\appium-uiautomator2-driver
[Appium] Attempting to load driver chromium...
[Appium] Could not load driver 'chromium', so it will not be available. Error in loading the driver was: Could not find a driver installed at C:\Users\xxxx\.appium\node_modules\appium-chromium-driver
[debug] [Appium] ReferenceError: Could not find a driver installed at C:\Users\xxxx\.appium\node_modules\appium-chromium-driver
[debug] [Appium]     at DriverConfig.require (C:\Users\xxxx\AppData\Roaming\npm\node_modules\appium\lib\extension\extension-config.js:539:13)
[debug] [Appium]     at C:\Users\xxxx\AppData\Roaming\npm\node_modules\appium\lib\extension\index.js:83:46
[debug] [Appium]     at Array.map (<anonymous>)
[debug] [Appium]     at getActiveDrivers (C:\Users\xxxx\AppData\Roaming\npm\node_modules\appium\lib\extension\index.js:80:10)
[debug] [Appium]     at main (C:\Users\xxxx\AppData\Roaming\npm\node_modules\appium\lib\main.js:303:41)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - uiautomator2@2.12.2 (automationName 'UiAutomator2')
[Appium]   - chromium@1.0.19 (automationName 'Chromium')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.`

I have verified that the directory C:\Users\xxxx\.appium\node_modules\appium-chromium-driver exists along with files in it. I have also tried uninstalling and re-installing chromium driver.

### Expected Behavior

appium server should be able to load chromium driver if it is already installed.

### Minimal Reproducible Example

start appium from cmd after installing chromium plugin.

### Environment

- Operating system: Windows 10
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.52
  - Node.js version (output of `node --version`): v16.17.0
  - `npm` version (output of `npm --version`): 9.2.0
  - Last `appium` version which did _not_ exhibit the problem: I haven't tried other versions.
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):  uiautomator2@2.12.2 , chromium@1.0.19
- Appium plugin(s) and their version(s): 
- Platform and version under test: Android 
- Real device or emulator/simulator:  emulator

### Futher Information

Having installed appium 2 , I also had to manually install  @appium/types without which appium driver install chromium kept failing with error message ""Error installing chromdriver: Cannot find module '@appium/types' ". Not sure if this is related.

**Comment by mykola-mokhnach** [comment]
cc @boneskull @jlipps

**Comment by jlipps** [comment]
Please let us know your node and npm versions, then run the following steps and report the result after starting the server again.

```
C:\package.json
C:\Users\package.json
C:\Users\xxx\package.json
C:\Users\xxx\.appium
```

now uninstall and reinstall appium

```
npm uninstall -g appium && npm install -g appium
```

make sure you are in a directory without a package.json, then

```
appium driver install chromium
```

then run the appium server

```
appium
```

what happens?

**Comment by Nfactor26** [comment]
Please find requested details below : 

**node and  npm versions**
-  node --version  v16.17.0
- npm --version    9.2.0

**package.json**

- C:\package.json : c:\package.json' is not recognized as an internal or external command,
operable program or batch file.
- C:\Users\package.json : C:\Users\package.json' is not recognized as an internal or external command,
operable program or batch file.
- C:\Users\xxx\package.json : File opened in vs code with content - {} . No data inside braces.
- explorer C:\Users\xxx\.appium : Directory opened in explorer with some content.

**uninstall and reinstall appium**
- npm uninstall -g appium
   removed 455 packages in 16s
- npm install -g appium
  added 686 packages in 43s
- appium driver install chromium
  C:\Users\xxxx\AppData\Roaming\npm\node_modules\appium\build\lib\main.js: error: unrecognized arguments: driver install chromium

Additionally, I also tried 
- npm uninstall -g appium@next
  up to date in 57ms
  However, it is not uninstalled.
- I also deleted .appium folder and did a npm install -g appium@next followed by installing chromium driver using appium driver install chromium. However, It did not help with the issue.

**Comment by jlipps** [comment]
sorry, yes i meant `npm install -g appium@next`.

what was the error when you installed the chromium driver after this?

**Comment by Nfactor26** [comment]
- npm uninstall -g appium@next 
  `up to date in 201ms`
  It doesn't uninstall appium. I can continue to start 'appium' server after this.
- npm uninstall -g appium
  `removed 428 packages in 6s`
  I can uninstall appium. Note that I had already uninstalled appium before and only installed appium@next after that.
  I can't start 'appium' server at this point.
- npm install -g appium@next
 ` added 428 packages in 49s`
- appium --version
  `2.0.0-beta.53`
- appium driver list
```
  ✔ Listing available drivers
        - uiautomator2 [not installed]
        - xcuitest [not installed]
        - mac2 [not installed]
        - espresso [not installed]
        - safari [not installed]
        - gecko [not installed]
        - chromium [not installed]
```
- appium  driver install chromium
```
  ⠇ Installing 'chromium' using NPM install spec 'appium-chromium-driver'
  ℹ Driver chromium@1.0.23 successfully installed
  - automationName: Chromium
  - platformNames: ["Windows","macOS","Linux"]
```

- appium
```
[Appium] Welcome to Appium v2.0.0-beta.53
[Appium] Attempting to load driver chromium...
[Appium] Could not load driver 'chromium', so it will not be available. Error in loading the driver was: Could not find a driver installed at C:\Users\xxxx\.appium\node_modules\appium-chromium-driver
[debug] [Appium] ReferenceError: Could not find a driver installed at C:\Users\xxxx\.appium\node_modules\appium-chromium-driver
[debug] [Appium]     at DriverConfig.require (C:\Users\xxxx\AppData\Roaming\npm\node_modules\appium\lib\extension\extension-config.js:539:13)
[debug] [Appium]     at C:\Users\xxxx\AppData\Roaming\npm\node_modules\appium\lib\extension\index.js:83:46
[debug] [Appium]     at Array.map (<anonymous>)
[debug] [Appium]     at getActiveDrivers (C:\Users\xxxx\AppData\Roaming\npm\node_modules\appium\lib\extension\index.js:80:10)
[debug] [Appium]     at main (C:\Users\xxxx\AppData\Roaming\npm\node_modules\appium\lib\main.js:303:41)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - chromium@1.0.23 (automationName 'Chromium')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.

```

**Comment by jlipps** [comment]
what is in `C:\Users\xxxx\.appium\node_modules` then? Did you check based on the error message?

@boneskull wonder if something might be not working correctly in our windows use case? Do you see anything here to investigate?

**Comment by boneskull** [comment]
could be a windows thing. @Nfactor26 can you please retry the install after removing `C:\Users\xxxx\.appium`?

**Comment by boneskull** [comment]
if that fails please paste the contents of C:\Users\xxxx\.appium\node_modules\.cache\appium\extensions.yaml

**Comment by Nfactor26** [comment]
1. After deleting .appium folder 
    - appium driver list
```
✔ Listing available drivers
- uiautomator2 [not installed]
- xcuitest [not installed]
- mac2 [not installed]
- espresso [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]
```
    - appium driver install chromium
```
✔ Installing 'chromium' using NPM install spec 'appium-chromium-driver'
ℹ Driver chromium@1.0.23 successfully installed
- automationName: Chromium
- platformNames: ["Windows","macOS","Linux"]
```
  - appium
    same error as before

2. C:\Users\xxxx\.appium\node_modules -- I have checked that it is a non empty folder with size on disk 70 mb and It has a 
 non-empty 'appium-chromium-driver' folder as well  with size 69.8 mb.
4. Contents of C:\Users\xxxx.appium\node_modules.cache\appium\extensions.yaml
```
 drivers:
  chromium:
    pkgName: appium-chromium-driver
    version: 1.0.23
    installType: npm
    installSpec: chromium
    installPath: C:\Users\xxxx\.appium\node_modules\appium-chromium-driver
    appiumVersion: ^2.0.0-beta.47
    automationName: Chromium
    platformNames:
      - Windows
      - macOS
      - Linux
    mainClass: ChromiumDriver
plugins: {}
schemaRev: 3
```

**Comment by jlipps** [comment]
Just to confirm, when you say:

> C:\Users\xxxx.appium\node_modules -- I have checked that it is a non empty folder with size on disk 70 mb and It has a
non-empty 'appium-chromium-driver' folder as well with size 69.8 mb.

Do you actually mean `C:\Users\xxxx\.appium\node_modules`? Because if there is a folder called `xxxx.appium` that is a bug.

**Comment by Nfactor26** [comment]
Sorry for that...Directory is C:\Users\xxxx\.appium\node_modules\.cache\appium

**Comment by jlipps** [comment]
ah ok cool. just making sure. that is what we expect.

**Comment by jlipps** [comment]
@boneskull all that looks in order to me, what do you think?

**Comment by 7999** [comment]
same issue when I use xcuitest driver
--node version 16.15.0
--npm version 8.5.5

administrator@Administrators-MacBook-Pro ~ % appium driver install xcuitest
✔ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver'
ℹ Driver xcuitest@4.16.10 successfully installed
- automationName: XCUITest
- platformNames: ["iOS","tvOS"]
administrator@Administrators-MacBook-Pro ~ % appium
[Appium] Welcome to Appium v2.0.0-beta.53
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at /Users/administrator/.appium/node_modules/appium-xcuitest-driver
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - xcuitest@4.16.10 (automationName 'XCUITest')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.

**Comment by jlipps** [comment]
@7999 i don't see any issues there...?

**Comment by jlipps** [comment]
@Nfactor26 I just published chromium driver 1.0.28. Please run `appium driver update chromium` and try again?

**Comment by 7999** [comment]
> @7999 i don't see any issues there...?

I already installed the "appium-xcuitest-driver":
✔  Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver'
ℹ Driver xcuitest@4.16.10 successfully installed

but when I run command "appium" in terminal, it show the message "[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use." , because this I can not start appium server in client side that ues C#  with script "AppiumLocalService.Start()".

**Comment by Nfactor26** [comment]
Did a quick update and tried to start Appium server and I don't seem to be getting the issue any more. Will play around with the chrome automation later tomorrow.
Thanks a ton for such a quick fix. 

`[Appium] Welcome to Appium v2.0.0-beta.53
[Appium] Attempting to load driver chromium...
[debug] [Appium] Requiring driver at C:\Users\xxxx\.appium\node_modules\appium-chromium-driver
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\xxxx\.appium\node_modules\appium-uiautomator2-driver
`

**Comment by mykola-mokhnach** [comment]
Closed as fixed
