### ISSUE TITLE
elements not get clicked on mac 13.1 with appium 2.0 beta

### ISSUE THREAD

**Issue by abhijeetkange** [appium/appium#18107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i have installed appium 2.0 beta as my previous appium 1.22 start giving error of xcode = Cannot link directly with dylib/framework XCTAutomationSupport for architecture arm64  
to solve this i installed 2.0 beta 
but in this i am not able to click on element which are deeply nested. used { "snapshotMaxDepth": 1000 } but still no luck 

Please fix this or suggest me workaround i am stuck.

### Expected Behavior

Nested Element should get clicked after giving { "snapshotMaxDepth": 1000 }

### Minimal Reproducible Example

			 
			PS.PatientTab.click();
			
			 
			if(PS.PatientTabHeader.isDisplayed()==true){
				System.out.println("We are on patient screen");
			}else{
				Assert.fail("not on patient tab");
			}
			 
			
			PS.searchSubTab.click();
			//Here i am not able to click on radio button which are deeply nested
                         try {
				PS.IDRadioButton.click();
			} catch (Exception e) {
				PS.IDRadioButtonXpath.click();
			}
			
			PS.patientSearchInput.click();
			PS.patientSearchInput.sendKeys(PatientID);
			
			driver.hideKeyboard();
			//Same for search result as it is deeply nested
			if(PS.SearchedPatientResult.isDisplayed()==true){
				PS.SearchedPatientResult.click();
			}else{
				
				Assert.fail();
			}
				 

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):2.0.0-beta.53
  - Node.js version (output of `node --version`):v16.13.2
  - `npm` version (output of `npm --version`): 9.3.1
  - Last `appium` version which did _not_ exhibit the problem: 1.22.3
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator: Real device ios16.3

### Futher Information

[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [XCUITestDriver@bad7 (65cf05f1)] Waited for 9535 ms so far
[debug] [XCUITestDriver@bad7 (65cf05f1)] Matched '/element' to command name 'findElement'
[debug] [XCUITestDriver@bad7 (65cf05f1)] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/38617BAD-E536-4023-9A16-8DDF040352ED/element] with body: {"using":"id","value":"patientName0"}
[XCUITestDriver@bad7 (65cf05f1)] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'id', value 'patientName0'","traceback":"(\n\t0   WebDriverAgentLib                   0x0000000108561410 FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x0000000108561240 +[FBFindElementCommands handleFindElement:] + 304\n\t2   WebDriverAgentLib                   0x00000001085297cc -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x0000000108516550 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 396\n\t4   WebDriverAgentLib                   0x0000000108549e68 -[RoutingHTTPServer handleRoute:withRequest:response:] + 160\n\t5   WebDriverAgentLib                   0x000000010854a8f4 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x00000001c6e747c8 9FA81DCE-81CF-3E8B-A1BB-FB64744769B2 + 411592\n\t7   libdispatch.dylib                   0x00000...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [XCUITestDriver@bad7 (65cf05f1)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [XCUITestDriver@bad7 (65cf05f1)]     at XCUITestDriver.doNativeFind (/Users/abhijeetkange/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:129:11)
[debug] [XCUITestDriver@bad7 (65cf05f1)]     at runMicrotasks (<anonymous>)
[debug] [XCUITestDriver@bad7 (65cf05f1)]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [XCUITestDriver@bad7 (65cf05f1)]     at XCUITestDriver.findNativeElementOrElements (/Users/abhijeetkange/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:89:10)
[debug] [XCUITestDriver@bad7 (65cf05f1)]     at XCUITestDriver.findElOrEls (/Users/abhijeetkange/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:22:12)
[debug] [XCUITestDriver@bad7 (65cf05f1)]     at XCUITestDriver.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.js:81:16)
[debug] [XCUITestDriver@bad7 (65cf05f1)]     at XCUITestDriver.findElement (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.js:21:14)

**Comment by razvan-avi** [comment]
@abhijeetkange a workaround for this could be using an older xcuitest driver. I have a similar issue and using `xcuitest@4.12.2` resolved it

**Comment by abhijeetkange** [comment]
Thank you!!!
I have tried all the ways with old driver and old xcode also but no luck. 
So I have used appium 2.0.0-Beta 53 with Xcode 14.2 , iOS 16.3(real Device), Mac os 13.1.
Below code used for clicking on elements which are deeply nested.

public static AppiumDriver Setup() throws Exception {
	
		DesiredCapabilities dc = new DesiredCapabilities();
		dc.setCapability("deviceName", DesiredCapabilities_ios.deviceName); 
		dc.setCapability("platformName", DesiredCapabilities_ios.platformName); 
		dc.setCapability("platformVersion",DesiredCapabilities_ios.platformVersion); 
		dc.setCapability("udid",DesiredCapabilities_ios.udid ); 
		dc.setCapability("app", "/Users/abhijeetkange/Desktop/MobileApp.ipa");
		dc.setCapability("appPackage" , DesiredCapabilities_ios.appPackage);
		dc.setCapability("automationName","XCUITest");   
		dc.setCapability("noReset", DesiredCapabilities_ios.noReset);   
		dc.setCapability("newCommandTimeout",99999);
		IOSDriver driver = new IOSDriver(new URL(DesiredCapabilities_ios.IOSDriver), dc);   
		driver.setSetting("snapshotMaxDepth", 1000);
		 
		return driver;
		
	}
