### ISSUE TITLE
renovate setup for official drivers

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18102]
What do we think of configuring renovate for `appium-xcuitest-driver` and its ilk?

One thing I noticed was that these repos explicitly exclude `package-lock.json` from VCS, which is incompatible with our usual Renovate configuration.  I assume this is because we are distributing shrinkwrapped packages, and want to ensure whatever works in our CI is what we distribute.  Using pinned deps & `package-lock.json` via Renovate means that each new version of a dependency will be tested via CI _before_ it is upgraded. Currently, this only happens when CI runs for whatever reason it runs.

The tradeoff for more thorough checking of upgrades (and out-of-range checks for upgrades--Renovate's default behavior is to upgrade to the latest version of each dependency as it is published, regardless of whether that satisfies the requested version range) is that dependency management _may_ require more manual intervention.  If an upgrade breaks the build, then a PR will exist containing a broken build, and someone will have to do something about it (either fix it or don't upgrade).  Right now, it seems like dependency upgrades would need to be rolled back _post-facto_; local dev environments are more likely to pull down new deps that fail the build and someone will have to manually intervene anyway.  Or a PR could contain a "surprise" upgrade otherwise unrelated to the PR which would fail the build.  What _doesn't_ currently happen is the automatic creation of PRs failed out-of-range upgrade attempts--thus creating more work for maintainers.  This behavior can be disabled, of course.

cc @jlipps @mykola-mokhnach @KazuCocoa

**Comment by jlipps** [comment]
I'm generally in favour of pinning deps vs shrinkwrap, and letting renovate automerge patch/minor updates on green PRs.

**Comment by KazuCocoa** [comment]
I'm fine to enable it. Probably..., my memory may be wrong though, the original motivation to use the shrinkwrap was old package-lock.json did not lock the dependencies actually. So we needed a way to lock dependencies. Maybe current our supported npm versions are much newer, so I guess we can use the official lock file only(?) to lock dependencies

https://github.com/search?q=org%3Aappium+%22npm+shrinkwrap%22&type=code

**Comment by mykola-mokhnach** [comment]
closed as obsolete.
dependabot does just fine
