### ISSUE TITLE
[Feat]: Appium should install .ipa files faster while testing in real device.

### ISSUE THREAD

**Issue by Shubham-Jaiswal21** [appium/appium#18111]
The problem
Whenever i am trying to open my app in IOS device using correct desired capabilities . It is taking too much time in few steps which is :
[XCUITest] Proceeding to serial files push
[WebDriverAgent] Parsed BUILD_DIR configuration value: '/Users/rapido/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou/Build/Products'
[WebDriverAgent] Got derived data root: '/Users/rapido/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou'
[HTTP] <-- POST /wd/hub/session - - ms - -
[HTTP]
[XCUITest] Successfully pushed 421 folders and 1287 files within 400406ms

Now due to this huge amount being taken to install the app the appium inspector is throwing "Request time out" error.
Please help.

Posting full log of appium server :

`[Appium] Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[BaseDriver] Creating session with W3C capabilities: {
[BaseDriver]   "alwaysMatch": {
[BaseDriver]     "platformName": "iOS",
[BaseDriver]     "appium:automationName": "XCUITest",
[BaseDriver]     "appium:deviceName": "iPhone",
[BaseDriver]     "appium:platformVersion": "16.2",
[BaseDriver]     "appium:udid": "00008030-000A65EC3CE0402E",
[BaseDriver]     "appium:bundleId": "bike.rapidodev.customer",
[BaseDriver]     "appium:xcodeOrgId": "3N9858UQG8",
[BaseDriver]     "appium:xcodeSigningId": "iPhone Developer",
[BaseDriver]     "appium:app": "/Users/rapido/Documents/Rapido StagingIOS.ipa",
[BaseDriver]     "appium:includeSafariInWebviews": true,
[BaseDriver]     "appium:newCommandTimeout": 3600,
[BaseDriver]     "appium:connectHardwareKeyboard": true
[BaseDriver]   },
[BaseDriver]   "firstMatch": [
[BaseDriver]     {}
[BaseDriver]   ]
[BaseDriver] }
[BaseDriver] Session created with session id: 400dcbb2-fb18-4c28-a024-31909a72453f
[XCUITest] Current user: 'rapido'
[XCUITest] Available devices: 00008030-000A65EC3CE0402E
[XCUITest] Creating iDevice object with udid '00008030-000A65EC3CE0402E'
[XCUITest] Determining device to run tests on: udid: '00008030-000A65EC3CE0402E', real device: true
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1674203921696 (14:08:41 GMT+0530 (India Standard Time))
[BaseDriver] Using local app '/Users/rapido/Documents/Rapido StagingIOS.ipa'
[BaseDriver] Will reuse previously cached application at '/var/folders/6r/rx3y9p9d4gnd8k10r6609zbc0000gn/T/2023020-77568-lj2nj1.mq0wj/Rapido Staging.app'
[BaseDriver] Event 'appConfigured' logged at 1674203922027 (14:08:42 GMT+0530 (India Standard Time))
[XCUITest] Checking whether app '/var/folders/6r/rx3y9p9d4gnd8k10r6609zbc0000gn/T/2023020-77568-lj2nj1.mq0wj/Rapido Staging.app' is actually present on file system
[XCUITest] App is present
[BaseDriver] Event 'resetStarted' logged at 1674203922032 (14:08:42 GMT+0530 (India Standard Time))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1674203922032 (14:08:42 GMT+0530 (India Standard Time))
[WebDriverAgent] Using WDA path: '/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent'
[WebDriverAgent] Using WDA agent: '/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[XCUITest] Crash reports root '/Users/rapido/Library/Logs/CrashReporter/MobileDevice/iPhone' does not exist. Got nothing to gather.
[BaseDriver] Event 'logCaptureStarted' logged at 1674203922483 (14:08:42 GMT+0530 (India Standard Time))
[XCUITest] Setting up real device
[XCUITest] Verifying application platform
[XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] Installing '/var/folders/6r/rx3y9p9d4gnd8k10r6609zbc0000gn/T/2023020-77568-lj2nj1.mq0wj/Rapido Staging.app' on device with UUID '00008030-000A65EC3CE0402E'...
[XCUITest] Using 'serial' app deployment strategy. You could change it by providing another value to the 'appInstallStrategy' capability
[XCUITest] Getting bundle ID from app '/var/folders/6r/rx3y9p9d4gnd8k10r6609zbc0000gn/T/2023020-77568-lj2nj1.mq0wj/Rapido Staging.app': 'bike.rapidodev.customer'
[XCUITest] Successfully scanned the tree structure of '/var/folders/6r/rx3y9p9d4gnd8k10r6609zbc0000gn/T/2023020-77568-lj2nj1.mq0wj/Rapido Staging.app'
[XCUITest] Got 421 folders and 1287 files to push
[XCUITest] Successfully created the remote folder structure (422 items)
[XCUITest] Proceeding to serial files push
[WebDriverAgent] Parsed BUILD_DIR configuration value: '/Users/rapido/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou/Build/Products'
[WebDriverAgent] Got derived data root: '/Users/rapido/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou'
[HTTP] <-- POST /wd/hub/session - - ms - -
[HTTP] 
[XCUITest] Successfully pushed 421 folders and 1287 files within 400406ms
[XCUITest] A new application installation is going to be performed
[XCUITest] App installation succeeded after 404468ms`
Environment
I am running Appium Desktop version : 1.22.3
I am on (pick one):
Mac and trying to run app on Iphone Se (Real Device.)

**Describe the solution you'd like**
Simply it should not take this much time to install the app and then it would not lead to server timeout on Appium Inspector.

**Comment by mykola-mokhnach** [comment]
>  [XCUITest] Using 'serial' app deployment strategy. You could change it by providing another value to the 'appInstallStrategy' capability

Have you actually tried to use different strategies?

**Comment by Shubham-Jaiswal21** [comment]
Hey @mykola-mokhnach ,
No I didn't use any different strategies.
I tried to find out but can you please tell what are other 'appInstallStrategy' capability. I will use them and let you know the results.

**Comment by mykola-mokhnach** [comment]
there is a project documentation for this purpose: https://appium.github.io/appium-xcuitest-driver/4.16/capabilities/

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
