### ISSUE TITLE
bug: The following desired capabilities were provided, but not recognized by appium: locationServicesEnabled, locationServicesAuthorized

### ISSUE THREAD

**Issue by Idoserovitz** [appium/appium#18119]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hi guys,
I was setting up a new VM(mac, M1) to run Android and iOS tests on it.
Android works great.
When I tried to run iOS tests, I could not automatically accept the location alert popping up at the beginning of my tests.
When I looked on appium logs, I saw the error mentioned on the title, it could not recognize "locationServicesEnabled" and "locationServicesAuthorized" capabilities(used 'appium:' prefix).
My previous setup worked great(same capabilities) and the same goes for my local setup.
Since I upgraded Xcode and Mac versions as well, I tried different combination at the beginning and it did not change.

Basically, on my previous setup I used **appium-xcuitest-driver@4.7.4** and it worked great, when I installed xcuitest driver on the new machine it was **appium-xcuitest-driver@4.16.10**
So, I tried different versions and I found out that **appium-xcuitest-driver@4.10.0** works well and can receive the above capabilities.

So, somewhere between 4.10.0 and 4.16.10 the issue occurred.

### Expected Behavior

To automatically accept the location alert when starting the test.

### Minimal Reproducible Example

{
  "platformName": "IOS",
  "appium:deviceName": "iPhone 13",
  "appium:platformVersion": "15.5",
  "appium:automationName": "XCUITest",
  "appium:app": "/***",
  "appium:wdaStartupRetryInterval": 20000,
  "appium:wdaStartupRetries": 4,
  "appium:wdaLaunchTimeout": 120000,
  "appium:fullReset": true,
  "appium:bundleId": "com.***",
  "appium:locationServicesEnabled": true,
  "appium:locationServicesAuthorized": true
}

### Environment

- Operating system: MacOS Ventura(13.0)
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.52
  - Node.js version (output of `node --version`): 18.13.0
  - `npm` version (output of `npm --version`):  8.19.3
  - Last `appium` version which did _not_ exhibit the problem: none(appium-xcuitest-driver@4.10.0 works fine)
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): appium-xcuitest-driver@4.16.10*
- Appium plugin(s) and their version(s):
- Platform and version under test: IOS 15.5, 16.2
- Real device or emulator/simulator: simulator

### Futher Information

Note that I did not change my code and more specifically, my capabilities when testing different versions.
The change was caused by appium-xcuitest-driver.

**Comment by mykola-mokhnach** [comment]
This behaviour is expected. Both these capabilities have been removed as obsolete on Simulator as they were actually partially implementing what  [appium:permissions](https://appium.github.io/appium-xcuitest-driver/4.16/capabilities/) does

**Comment by Idoserovitz** [comment]
Thanks @mykola-mokhnach 
I was following: [appium caps](https://appium.io/docs/en/writing-running-appium/caps/#:~:text=locationServicesAuthorized)
Will definitely try it out.

**Comment by Idoserovitz** [comment]
@mykola-mokhnach, thanks.
Works great, you can close this issue.

**Comment by awhisler** [comment]
@Idoserovitz 
Thank you for asking this!!!! I have spent 3 days pulling my hair out trying to get this to work or trying to find a selector to click it haha.

But, how did you get it to work? When I do this, it just hangs and never runs the code:
![image](https://github.com/appium/appium/assets/2396250/ba1c4fe1-5e8c-46f0-aa51-bb618428eaea)

**Comment by awhisler** [comment]
[mykola-mokhnach](https://github.com/mykola-mokhnach) Any idea why `"appium:autoAcceptAlerts": true` doesn't work? See video
[Accept.mp4.zip](https://github.com/appium/appium/files/14226896/Accept.mp4.zip)

But when I use this `"appium:autoDismissAlerts": true,` it does? See video
[Dismiss.mp4.zip](https://github.com/appium/appium/files/14226890/Dismiss.mp4.zip)
