### ISSUE TITLE
bug: visible is "false" but the button is shown&clickable on the app.

### ISSUE THREAD

**Issue by cong-yao** [appium/appium#18113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

All the buttons are visible to users and clickable. But the "visible" status is "false".
For example, the "login" button, I can see it and click on the app.
But there is no response when I try to tap it on appium inspector.

1. Is it possible to click the button even the visible is false?
2. Could you help to check the root cause? we're trying to fix this visible=false issue.

<img width="1262" alt="スクリーンショット 2023-01-27 11 16 02" src="https://user-images.githubusercontent.com/103723412/214996855-71925aaf-14b7-4297-b8ae-1a0e276c0879.png">

### Expected Behavior

The "visible" status should be true and I can click it on appium inspector.

### Minimal Reproducible Example

el4 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="login_button")
el4.click()

### Environment

- Operating system: mac os 12.5.1
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version: appium inspector 2022.5.4
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test: ios 15.4
- Real device or emulator/simulator: iPhone 13 Simulator

**Comment by charlieperdana** [comment]
from development side is iOS native, there is no change regarding to the UI visible related on it. Since this visible parameter only appears on appium. If we test the locator in Accessibility Inspector in Xcode, there is none of visible parameter. So it means from codes in iOS, there is no changes.
Thats really weird why the element shows visible false although this element accessible and show in the screen, and clickable too.

We tried it once in iOS 16 iPhone 14 and the result is some elements has parameter visible but false value.

Then we tried to run and check it on iOS 15 iPhone 11, and the result is the visible parameter is true and nothing issue like above one.
![image](https://user-images.githubusercontent.com/20263549/215014330-31f0064c-0b96-4be7-8336-391ee2f845d3.png)


I though this is about Appium issue for iOS 16 to higher. Since we don't face any issue like that when we tried it on iOS 15 lower.
Kindly help and check it. Thanks.

**Comment by mykola-mokhnach** [comment]
The value of `visible` is retrieved from `XC_kAXXCAttributeIsVisible` iOS accessibility properly and we cannot do anything on WDA side is order to change this behaviour. Please let us know if you know which application/system settings affects it from the operating system perspective.

https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement%2BFBIsVisible.m contains the actual visibility detection logic

**Comment by charlieperdana** [comment]
So you mean this is about the architecture?

**Comment by charlieperdana** [comment]
Why does it not happen on iOS 15 Iphone 11?

**Comment by mykola-mokhnach** [comment]
> So you mean this is about the architecture?

yes

> Why does it not happen on iOS 15 Iphone 11?

I don't know, maybe Appile did some internal changes

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by lparry** [comment]
@charlieperdana did you ever find a workaround for this?

**Comment by shylendramadda** [comment]
Hi, @cong-yao  Facing a similar issue in iOS 16+ Did you find a solution?

**Comment by mate0515** [comment]
Facing the same issue on iOS 17.2

**Comment by Shailendra-3Frames** [comment]
Any solution to this?

**Comment by viduuuur** [comment]
@Shailendra-3Frames 
Try using the capability XCUITestOptions.SIMPLE_IS_VISIBLE_CHECK_OPTION to true https://github.com/appium/WebDriverAgent/commit/fa1a7c5e575c54319593d0b5e033e59ccf34dfbc

**Comment by SaiSunandaAlluri** [comment]
@Shailendra-3Frames @viduuuur @mate0515 @lparry @shylendramadda 

As per this resource link, when we set the capability to true then we can handle the visibility issue in iOS. 
https://github.com/appium/WebDriverAgent/commit/fa1a7c5e575c54319593d0b5e033e59ccf34dfbc 
 **setCapability(XCUITestOptions.SIMPLE_IS_VISIBLE_CHECK_OPTION, true)** 

In edge cases it won't work all the time, in those scenarios 
 * First set the above capability 
* next to perform click action try like this 
```
val actions = Actions(driver)
actions.click(YOUR_UI_ELEMENT).perform()
```

**Comment by nandanmagdum** [comment]
@lparry @shylendramadda @mykola-mokhnach @charlieperdana @viduuuur  is any solution proposed over this, I'm facing same issue, please help.

Appium Version is 2.19.0
Flutter app ipa in release mode
Driver: XCUITest
Testing on real iphone device: iPhone 12
