### ISSUE TITLE
SET GEOLOCATION does not work on  16.1 IOS real device

### ISSUE THREAD

**Issue by Abhinav-Anand-Lambdatest** [appium/appium#18115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

SET GEOLOCATION does not work on  16.1 IOS real device

I tried with idevicesetlocation also. but it didn't gave any  error and the geolocation didnot change

### Expected Behavior

the gps location should change

### Minimal Reproducible Example

uset set_location of appium to change gps location and it  does not work.

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
It depends on how iOS internally handles it.

It worked with an iOS 16.3 real device on my local with Apple's Maps app. I observed that it did not reflect immediately sometimes, so I guess iOS caches the location data or something. Afaik, iOS does not provide force refresh etc, so we cannot do so much.

Appium controls the location data via https://github.com/appium/appium-ios-device/blob/master/lib/simulatelocation/index.js#L4 (com.apple.dt.simulatelocation), which is the same with idevicesetlocation

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
