### ISSUE TITLE
Change user agent in safari ios appium 

### ISSUE THREAD

**Issue by shub22396** [appium/appium#18128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a user trying to change user agent in safari ios in appium test then it doesn't do any effect over the browser

### Expected Behavior

User agent will change in the browser as per the argument we have passed in the capabilities of the test.

### Minimal Reproducible Example

Steps to reproduce:
1. Run any sample appium test and user below mentioned capabilities 
2. DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("browserName", "safari");
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("deviceName", "iPhone X");
capabilities.setCapability("safari.options.technologyPreview", false);
capabilities.setCapability("safari.options.useSimulator", true);
capabilities.setCapability("safari.options.userAgent", "YOUR_USER_AGENT");
3.Navigate to 'What is my user agent' 
4 .Then we'll able to see not able to change the user agent

### Environment

Appium

### Link to Appium Logs

https://github.com/appium/appium/issues/new?assignees=&labels=Bug%2CNeeds+Triage&template=bug_report.yml&title=bug%3A+%3Ctitle%3E

**Comment by mykola-mokhnach** [comment]
Such feature has never been implemented  in xcuitest driver web context.

You could try https://github.com/appium/appium-safari-driver though

**Comment by shub22396** [comment]
@mykola-mokhnach I am testing on remote ios devices on which I want to override user agent to suffice my usecase, is it possible we can handle it using capabilities

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't know any other ways to achieve that.

**Comment by KazuCocoa** [comment]
Hm, maybe we cannot implement it via remote control at least for now.

Our https://github.com/appium/appium-remote-debugger to manage web context depends on https://github.com/WebKit/webkit/tree/main/Source/JavaScriptCore/inspector/protocol . They do not have `setUserAgentOverride` command chrome devtools protocol does it. Afaik, safaridriver does not provide the feature.

**Comment by KazuCocoa** [comment]
I tried if this is possible via https://github.com/appium/appium-remote-debugger/pull/283#event-8610627168

It seems like mobile safari did not allow us to change the UIA via the WebInspector's command. Some articles in the interned explained a way to change the UA by modifying the Info.plist directly, so potentially this is not possible because of current mobile safari's limitation
