### ISSUE TITLE
bug: [MacOS M1 (ARM)]Chromedriver for intel processor is installed with uiautomator2 driver instead of chromedriver for apple arm procesor

### ISSUE THREAD

**Issue by Dzejnieks** [appium/appium#18136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Chromedriver for intel processor is installed with uiautomator2 driver when setting up appium@next on macbook with apple processor (M1)

### Expected Behavior

Chromedriver for apple processor (arm) is installed with uiautomator2 driver when setting up appium@next on macbook with apple processor (arm)

### Minimal Reproducible Example

1. install appium@next
2. install uiautomator2 driver
3. run tests that interact with webview elements

=> error is returned which says that it could not find any chromedrivers that could interact with mobile chrome app.

4. go to uiautomator2 folder where chromedrivers are stored
=> only Mac_x64 chromedriver is installed

NOTE: I fixed issue by manually downloading Mac_64arm chromedriver from https://chromedriver.storage.googleapis.com/index.html?path=109.0.5414.74/ and added it to the uiautomator2 folder.

### Environment

Appium: 2.0.0-beta.46
NPM: 8.19.2
MacOS Ventura 13.1
Device: Macbook Pro 2020, M1, 13"

**Comment by mykola-mokhnach** [comment]
It looks like execution `uname -m` from a process running under Rosetta 2 (and Node.js could be such) returns x86_64. So I have changed the detection method to a more reliable one in https://github.com/appium/appium-chromedriver/pull/287

**Comment by mykola-mokhnach** [comment]
The patch has been published in the recent UIA2 driver release
