### ISSUE TITLE
bug: cannot install driver | feat: stop global install support | feat: add local install support

### ISSUE THREAD

**Issue by kopax-polyconseil** [appium/appium#18135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently doc advise to install globally appium and make my system dirty.

That's a bad practice.

I want to follow best practice and install it not globally, within my project.

### Expected Behavior

I expect this to be possible, but it fail.

### Minimal Reproducible Example

```bash
npm install
npm install appium@next
export PATH=$PATH:./node_modules/.bin/
```

All `appium driver install` commands will fail

### Environment

- Operating system: linux
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.53
  - Node.js version (output of `node --version`): v18.7.0
  - `npm` version (output of `npm --version`):  8.15.0
  - Last `appium` version which did _not_ exhibit the problem:  NA
- If running Appium Desktop, its version: NA
- Appium driver(s) and their version(s): uiautomator2@2.9.0
- Appium plugin(s) and their version(s): NA
- Platform and version under test: NA
- Real device or emulator/simulator: NA

**Comment by mykola-mokhnach** [comment]
- We do not support yarn neither test with it. Only npm is supported
- We cannot help anything without detailed logs

**Comment by kopax-polyconseil** [comment]
I have replaced yarn command with npm, issue here is not related to the package manager, but how appium advise to  install itself.

**Comment by jlipps** [comment]
if you're using a local appium instance, you shouldn't use `appium driver install`. if appium is in a local directory's package json that is a sign you are using npm to manage drivers, and not appium. the recommended way to use appium is to install it as a global package. to do that, first delete whatever folder you installed appium in, then:

```
npm install -g appium@next
# now you can run this globally
appium driver install xcuitest
```

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by jlipps** [comment]
And if you want local only installs, follow the supported method of simply using package.json to manage Appium and drivers instead.

**Comment by jlipps** [comment]
Docs on options for managing drivers: https://appium.github.io/appium/docs/en/2.0/guides/managing-exts/
