### ISSUE TITLE
i am not able install uiautomator2....plz help

### ISSUE THREAD

**Issue by rahulv-tech** [appium/appium#18148]
C:\WINDOWS\system32>appium driver install uiautomator2
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.

STDOUT:

STDERR:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@npmcli%2fdocs - Not found
npm ERR! 404
npm ERR! 404  '@npmcli/docs@^1.0.0' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
{
  "error": {
    "code": "E404",
    "summary": "Not Found - GET https://registry.npmjs.org/@npmcli%2fdocs - Not found",
    "detail": "\n '@npmcli/docs@^1.0.0' is not in this registry.\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rahul\AppData\Local\npm-cache\_logs\2023-02-04T18_26_03_022Z-debug-0.log

**Comment by KazuCocoa** [comment]
Please fill out the but template with system info etc

My end had no issue as below with 2.0.0-beta.53 on macOS, npm v8.11, node v16
```
kazu$ appium driver install uiautomator2
✔ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
ℹ Driver uiautomator2@2.12.3 successfully installed
- automationName: UiAutomator2
- platformNames: ["Android"]
```

**Comment by mykola-mokhnach** [comment]
Do you use custom npm registry or the computer is under a corporate firewall? In such case please ask your system administrator for help.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by AbdelHalim007** [comment]
> C:\WINDOWS\system32>appium driver install uiautomator2 × Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver' Error: × Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.
> 
> STDOUT:
> 
> STDERR: npm ERR! code E404 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@npmcli%2fdocs - Not found npm ERR! 404 npm ERR! 404 '@npmcli/docs@^1.0.0' is not in this registry. npm ERR! 404 npm ERR! 404 Note that you can also install from a npm ERR! 404 tarball, folder, http url, or git url. { "error": { "code": "E404", "summary": "Not Found - GET https://registry.npmjs.org/@npmcli%2fdocs - Not found", "detail": "\n '@npmcli/docs@^1.0.0' is not in this registry.\n\nNote that you can also install from a\ntarball, folder, http url, or git url." } }
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Rahul\AppData\Local\npm-cache_logs\2023-02-04T18_26_03_022Z-debug-0.log

Hello rahulv-tech did found any solution for it ?
