### ISSUE TITLE
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'POST /elements' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more detailsbug: <title>

### ISSUE THREAD

**Issue by arghyamukherjee007** [appium/appium#18140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Device: Mac OS X
App: Android Mi A3 (6 gb ram)

Everytime app crashing when trying to access element (like wait for element to be visible or click element etc.)

error shown

```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'POST /elements' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more detailsbug: <title>
```

as part of workaround

- deleted io.uiautomator and io.uiautomator.server app from settings->app and let appium install it.
- added driver.quit()

no luck . always failing

### Expected Behavior

appium should able to perform ui activity successfully

### Minimal Reproducible Example

Always

```
 [java] Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:03.216Z'
     [java] System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.2', java.version: '1.8.0_362'
     [java] Driver info: io.appium.java_client.android.AndroidDriver
     [java] org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'POST /elements' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
     [java] Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T15:15:03.216Z'
     [java] Capabilities {appActivity: com.amazon.dee.app.ui.main...., appPackage: com.amazon.dee.app, databaseEnabled: false, desired: {appActivity: com.amazon.dee.app.ui.main...., appPackage: com.amazon.dee.app, deviceName: Mi A3, platformName: android}, deviceApiLevel: 30, deviceManufacturer: Xiaomi, deviceModel: Mi A3, deviceName: ee6f384f6a3b, deviceScreenDensity: 320, deviceScreenSize: 720x1560, deviceUDID: ee6f384f6a3b, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, pixelRatio: 2, platform: LINUX, platformName: Android, platformVersion: 11, statBarHeight: 70, takesScreenshot: true, viewportRect: {height: 1341, left: 0, top: 70, width: 720}, warnings: {}, webStorageEnabled: false}
  
```

### Environment

- Operating system: Mac OS X , Android R
- If running Appium Desktop, its version: 1.22
- Appium driver(s) and their version(s): 
- Appium plugin(s) and their version(s):
- Platform and version under test: Android Mi A3  , OS - R
- Real device or emulator/simulator: Real device

### Link to Appium Logs

[_log_
](https://gist.github.com/arghyamukherjee007/11100df1522cb4d629e811e340517137)

**Comment by mykola-mokhnach** [comment]
- Appium 1 is not maintained anymore. Consider using UIA2 supplied with Appium 2
- I can observe multiple session creation requests. Make sure you only create a session once. Consider using `--session-override` server option if you don't need to manage parallel sessions.

**Comment by arghyamukherjee007** [comment]
@mykola-mokhnach  can you please share the appium2 link for mac and linux?
i am creating session only once


```
DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName","Mi A3");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("appPackage", "com.amazon.dee.app");
        capabilities.setCapability("appActivity", "com.amazon.dee.app.ui.main.MainActivity");

        URL url = new URL("http://127.0.0.1:4723/wd/hub");
        driver = new AndroidDriver<>(url, capabilities);
```


this is the code snippet

and driver.quit() as well at the end of the 1st test

can you suggest what should be the correct config

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach can you please share the appium2 link for mac and linux? i am creating session only once

https://github.com/appium/appium#server

> 
> ```
> DesiredCapabilities capabilities = new DesiredCapabilities();
>         capabilities.setCapability("deviceName","Mi A3");
>         capabilities.setCapability("platformName", "Android");
>         capabilities.setCapability("appPackage", "com.amazon.dee.app");
>         capabilities.setCapability("appActivity", "com.amazon.dee.app.ui.main.MainActivity");
> 
>         URL url = new URL("http://127.0.0.1:4723/wd/hub");
>         driver = new AndroidDriver<>(url, capabilities);
> ```
> 
> this is the code snippet
> 
> and driver.quit() as well at the end of the 1st test
> 
> can you suggest what should be the correct config

I don' know what is happening there. I only acknowledge what I see in the server log. Perhaps it makes sense to hire a consultant for reviewing/debugging the client code.

**Comment by arghyamukherjee007** [comment]
@mykola-mokhnach can you print the server log snippet here where it is printed multiple timers? , it would help me to debug the code at runtime better
also the link you provided is appium cli link. do we have appium2 desktop link.
i have downloaded 1.22.3 from here https://github.com/appium/appium-desktop/releases/tag/v1.22.3-4

**Comment by mykola-mokhnach** [comment]
Unfortunately Appium desktop has been discontinued. You may use Appium Inspector instead.

https://gist.github.com/arghyamukherjee007/11100df1522cb4d629e811e340517137#file-appium_log-L172 is where the second session creation requests is sent

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
