### ISSUE TITLE
[Feat]: Appium server no longer support random port assignment

### ISSUE THREAD

**Issue by pr4bh4sh** [appium/appium#18147]
**Is your feature request related to a problem? Please describe.**
When passing `-p 0` in Appium 1.x  was starting with the random port number. 
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/6311526/216782712-a152b4a9-7f04-4005-bf79-bb47b08f020d.png">

Now on Appium 2.0 it doesn't start the server and shows below error

```bash
appium -p 0
usage: appium server [-h] [--address ADDRESS] [--allow-cors] [--allow-insecure ALLOW_INSECURE] [--base-path BASE_PATH]
                     [--callback-address CALLBACK_ADDRESS] [--callback-port CALLBACK_PORT] [--debug-log-spacing]
                     [--default-capabilities DEFAULT_CAPABILITIES] [--deny-insecure DENY_INSECURE] [--keep-alive-timeout KEEP_ALIVE_TIMEOUT]
                     [--local-timezone] [--log LOG] [--log-filters LOG_FILTERS] [--log-level LOG_LEVEL] [--log-no-colors] [--log-timestamp]
                     [--long-stacktrace] [--no-perms-check] [--nodeconfig NODECONFIG] [--port PORT] [--relaxed-security] [--session-override]
                     [--strict-caps] [--tmp TMP] [--trace-dir TRACE_DIR] [--use-drivers USE_DRIVERS] [--use-plugins USE_PLUGINS]
                     [--webhook WEBHOOK] [--shell] [--show-build-info] [--show-config] [--config CONFIGFILE]

appium server: error: argument --port/-p:

MINIMUM must be >= 1

> 1 | "0"
    | ^^^ 👈🏽  minimum must be >= 1

```

**Describe the solution you'd like**
Getting the old way of running random port would solve the issue.

**Describe alternatives you've considered**
I tried finding out a free port to assign it to the Appium. However, it has the possibility to port already in use situation when running test in parallelly. 

**Additional context**
When using any programming language other than java/Konlin/C#, the appium support library does not have support for starting the appium server from code. Starting it with shell command and then finding the port with process id was the way I used to do it.

Maybe having the option to let the Appium server decide the port would ensure the port conflict doesn't happen.

**Comment by saikrishna321** [comment]
@pr4bh4sh  Try appium server -p 5678

**Comment by jlipps** [comment]
This was never an intentionally supported feature, rather an artifact of how Node's [server.listen](https://nodejs.org/api/net.html#serverlistenport-host-backlog-callback) works. How did you get the port information before when it was started this way? Was it printed in the server start output?

**Comment by pr4bh4sh** [comment]
@saikrishna321 I tried assigning a port, and it works as intended. What I'm looking for is, the Appium server to decide the free port rather than me passing it from the command line. From @jlipps comment, it seems like it was never an intentional feature, it's just how the node server behaves.

@jlipps The Appium server start command doesn't print anything about what port it picked to use. Please check the screen shot in the first comment. It logs that the server has been started at `0.0.0.0:0` which is incorrect. 

I use the process id of the executed Appium server start command and then find what port the process is using. 

Here's how it works for me
```bash
# run Appium server in headless mode
❯ node_modules/.bin/appium -p 0 > ./appium.log 2>&1&
[1] 98362

# get the process id
❯ echo $!
98362

# find the port the process is using
❯ lsof -aPi -p 98362
COMMAND   PID          USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    98362 prabhashsingh   21u  IPv4 0xdb8adfaa0cb35509      0t0  TCP *:56294 (LISTEN)

# verify the  Appium server is running on the port
❯ curl --max-time 2 http://localhost:56294/wd/hub/status
{"value":{"build":{"version":"1.23.0-beta.0"}},"sessionId":null,"status":0}%

```

**Comment by mykola-mokhnach** [comment]
I assume you don't need Appium to find a random port. Also, the script above might be unstable because of its asynchronous nature. I would rather use something like `port=$(python -c "import socket; s = socket.socket(); s.bind(('', 0));print(s.getsockname()[1]);s.close()")` to find the first unused port and then simply pass the resulting `$port` value to the Appium server command line

**Comment by pr4bh4sh** [comment]
@mykola-mokhnach Yes, I'm using a similar mechanism for finding a free port.

I don't think this feature is needed anymore. I raised the issue under the impression that this was an intended feature of the Appium server in 1.x version, and was missing in 2.x version. This assumption has been clarified by @jlipps's comment.

I believe the issue can be closed if the maintainers agree that it is not something Appium should support.

**Comment by mykola-mokhnach** [comment]
Ok, closing as not an issue

**Comment by jlipps** [comment]
thanks for the discussion. yes assigning a random port was an accident and not a feature, and i don't think it something we want to support from the appium side.

**Comment by jlipps** [comment]
i'll make a note to add this to the 2.0 migration guide since it is technically a breaking change
