### ISSUE TITLE
setClipboardText() doesn't work

### ISSUE THREAD

**Issue by VadimVM** [appium/appium#18164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm new on automatization via Appium.
I try to set to android clipboard some text with this code:
```
        var driver = ((AndroidDriver) WebDriverRunner.getWebDriver());
        driver.setClipboardText("text");
```
and see this error: 
`org.openqa.selenium.InvalidArgumentException: Only '[PLAINTEXT]' content types are supported. 'PLAINTEXT' is given instead
Build info: version: '4.7.2', revision: '4d4020c3b7'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.2', java.version: '19.0.1'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [ca89617d-758e-4738-afaa-4b11bf290484, setClipboard {content=dGV4dA==, contentType=plaintext}]
Capabilities {appium:adbExecTimeout: 1200000, appium:androidInstallTimeout: 1200000, appium:app: <myApp>, appium:appPackage: <myAppPackage>, appium:automationName: UiAutomator2, appium:databaseEnabled: false, appium:desired: {adbExecTimeout: 1200000, androidInstallTimeout: 1200000, app: <myApp>, appPackage: <myAppPackage>, automationName: UiAutomator2, deviceName: emulator-5554, fullReset: false, idleTimeout: 350, language: az, locale: AZ, newCommandTimeout: 90, noReset: false, platformName: android, platformVersion: 12, resetKeyboard: true, unicodeKeyboard: true}, appium:deviceApiLevel: 31, appium:deviceManufacturer: Google, appium:deviceModel: sdk_gphone64_arm64, appium:deviceName: emulator-5554, appium:deviceScreenDensity: 560, appium:deviceScreenSize: 1440x3040, appium:deviceUDID: emulator-5554, appium:fullReset: false, appium:idleTimeout: 350, appium:javascriptEnabled: true, appium:language: az, appium:locale: AZ, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:newCommandTimeout: 90, appium:noReset: false, appium:pixelRatio: 3.5, appium:platformVersion: 12, appium:resetKeyboard: true, appium:statBarHeight: 84, appium:takesScreenshot: true, appium:unicodeKeyboard: true, appium:viewportRect: {height: 2788, left: 0, top: 84, width: 1440}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: ca89617d-758e-4738-afaa-4b11bf290484`

I use Appium Server GUI 1.22.0
Node.js v19.6.0

### Expected Behavior

driver should set expected text to android clipboard

### Minimal Reproducible Example

<img width="1085" alt="Снимок экрана 2023-02-07 в 14 45 14" src="https://user-images.githubusercontent.com/67012544/217248584-96a9376b-53dc-4929-8188-d3a9073ce48f.png">

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
Could you share the full appium server log as GitHub GIST?

**Comment by VadimVM** [comment]
@KazuCocoa will that be enough? https://gist.github.com/VadimVM/1a24e994cae6aabdc9db058937d81aaa

**Comment by KazuCocoa** [comment]
thanks. Hm... the request body looks ok with uia2 server 4.24.0

```
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session/c0c6c014-7947-46bd-a7b6-17a449211140/element/00000000-0000-0033-ffff-ffff0000024d/click [39m[32m200[39m [90m39 ms - 14[39m
[info] [35m[HTTP][39m [90m[39m
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/c0c6c014-7947-46bd-a7b6-17a449211140/appium/device/set_clipboard[39m
[info] [35m[HTTP][39m [90m{"content":"c2VuZF9tb25leV90b19jYXJkX3Rlc3Q=","contentType":"plaintext"}[39m
[info] [35m[W3C (c0c6c014)][39m Driver proxy active, passing request on via HTTP proxy
[debug] [35m[WD Proxy][39m Matched '/wd/hub/session/c0c6c014-7947-46bd-a7b6-17a449211140/appium/device/set_clipboard' to command name 'setClipboard'
[debug] [35m[WD Proxy][39m Proxying [POST /wd/hub/session/c0c6c014-7947-46bd-a7b6-17a449211140/appium/device/set_clipboard] to [POST http://127.0.0.1:8200/wd/hub/session/8cbdddcc-65c2-4e4f-a5c0-b038fe0adbcd/appium/device/set_clipboard] with body: {"content":"c2VuZF9tb25leV90b19jYXJkX3Rlc3Q=","contentType":"plaintext"}
[info] [35m[WD Proxy][39m Got response with status 400: {"sessionId":"8cbdddcc-65c2-4e4f-a5c0-b038fe0adbcd","value":{"error":"invalid argument","message":"Only '[PLAINTEXT]' content types are supported. 'PLAINTEXT' is given instead","stacktrace":"io.appium.uiautomator2.common.exceptions.InvalidArgumentException: Only '[PLAINTEXT]' content types are supported. 'PLAINTEXT' is given instead\n\tat io.appium.uiautomator2.handler.SetClipboard.safeHandle(SetClipboard.java:58)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:264)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:258)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chan...
[debug] [35m[W3C][39m Matched W3C error code 'invalid argument' to InvalidArgumentError
[info] [35m[HTTP][39m [37m<-- POST
```


Server version etc also seems good.

My example below, which was succeeded in setting the content. (uia2 server 4.27.0)
```
[HTTP] --> POST /wd/hub/session/22fb6e80-1035-47d1-928f-62347a1cd468/appium/device/set_clipboard
[HTTP] {"contentType":"plaintext","content":"44GC"}
[W3C (22fb6e80)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/22fb6e80-1035-47d1-928f-62347a1cd468/appium/device/set_clipboard' to command name 'setClipboard'
[debug] [WD Proxy] Proxying [POST /wd/hub/session/22fb6e80-1035-47d1-928f-62347a1cd468/appium/device/set_clipboard] to [POST http://127.0.0.1:1933/wd/hub/session/6b489d85-8790-4093-aa55-16f79f3f4b71/appium/device/set_clipboard] with body: {"contentType":"plaintext","content":"44GC"}
debug] [WD Proxy] Got response with status 200: {"sessionId":"6b489d85-8790-4093-aa55-16f79f3f4b71","value":null}
[WD Proxy] Replacing sessionId 6b489d85-8790-4093-aa55-16f79f3f4b71 with 22fb6e80-1035-47d1-928f-62347a1cd468
HTTP] <-- POST /wd/hub/session/22fb6e80-1035-47d1-928f-62347a1cd468/appium/device/set_clipboard 200 105 ms - 65

```

What about the getClipboard in your environment?

**Comment by VadimVM** [comment]
surprisedly getClipboard() is working!

**Comment by VadimVM** [comment]
I see that in your request arguments content and contentType are in other order
```
 [HTTP] --> POST /wd/hub/session/22fb6e80-1035-47d1-928f-62347a1cd468/appium/device/set_clipboard
[HTTP] {"contentType":"plaintext","content":"44GC"}
```
or it doesn't matter?

**Comment by KazuCocoa** [comment]
thanks. Then, perhaps the `contentType` was handled properly... The order should not be an issue in general since they are not list stuff.

Then, what about giving the setClipboard with `driver.setClipboard("label", ClipboardContentType.PLAINTEXT, base64Content);` style? Actually it should be what `setClipboardText` does in behind though.

**Comment by VadimVM** [comment]
Unfortunately `driver.setClipboard("label", ClipboardContentType.PLAINTEXT, base64Content);` doesn't work also. I had having the same exception.

**Comment by KazuCocoa** [comment]
Hm...
then https://github.com/appium/appium-uiautomator2-server/blob/68624fc41efd37288977da4b05d000330a51deb2/app/src/main/java/io/appium/uiautomator2/handler/SetClipboard.java#L55 got non-"plaintext" somehow, but it seems like your request `{"content":"c2VuZF9tb25leV90b19jYXJkX3Rlc3Q=","contentType":"plaintext"}` was correct

**Comment by KazuCocoa** [comment]
Could you try out with the latest UIA2 driver version with Appium 2.0?
