### ISSUE TITLE
Appium connection to ios fails in windows environment

### ISSUE THREAD

**Issue by Sun-GoKu** [appium/appium#18165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
[XCUITest]
at getPathFromsymlink (C:\Users\Hinsi\AppData\Local\Programs\Appium Server
GUI\resources\app\node_modules\appium\node_modules\appium-xcode\lib\xcode.js:84:9)
[XCUITest]
at getversionwithoutRetry (C:\Users\Hinsi\AppData\Local\Programs\Appium Server
GUI\resources\app\node_modules\appium\node_modules\appium-xcode\lib\xcode.js:114:21)
[XCUITest]
at retry (C:\Users\Hinsi\AppData\Local\Programs\Appium Server
GUI\resources\app\node_modules\appium\node_modules\asyncbox\lib\asyncbox.js:43:13)
[XCUITest]
at object.getversion (C:\Users\Hinsi\AppData\Local\Programs\Appium Server
GUI\resources\app\node_modules\appium\node_modules\appium-xcode\lib\xcode.js:135:19)
[XCUITest]
at getAndCheckXcodeversion (C:\Users\Hinsi\AppData\Local\Programs\Appium Server
GUI\resources\app\node_modules\appium\node_modules\appium-xcuitest-driver\lib\utils.js:41:15)
[XCUITest]
at XCUITestDriver.start (C:\Users\Hinsi\AppData\Local\Programs\Appium Server
GUI\resources\app\node_modules\appium\node_modules\appium-xcuitest-driver\lib\driver.js:350:27)
[XCUITest]
at XCUITestDriver.createSession (C:\Users\Hinsi\AppData\Local\Programs\Appium Server
GUI\resources\app\node_modules\appium\node_modules\appium-xcuitest-driver\lib\driver.js:255:7)
[XCUITest]
at AppiumDriver.createSession (C:\Users\Hinsi\AppData\Local\Programs\Appium Server
GUI\resources\app\node_modules\appium\lib\appium.js:387:35)

### Expected Behavior

can connect successfully

### Minimal Reproducible Example

{
  "platformName": "ios",
  "appium:deviceName": "iPhone18",
  "appium:platformVersion": "15.7",
  "appium:udid": "uid",
  "appium:noReset": true,
  "appium:usePrebuiltWDA": false,
  "appium:useXctestrunFile": false,
  "appium:skipLogCapture": true,
  "appium:bundleId": "com.facebook.sadApp.xctrunner",
  "appium:WebDriverAgentUrl": "http://127.0.0.1:8100",
  "appium:automationName": "XCUITest",
  "appium:allowProvisioningDeviceRegistration": true
}

### Environment

- Operating system:windows 10
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:1.22.2
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
https://appium.github.io/appium-xcuitest-driver/4.16/setup/

> Only macOS is supported as the host platform


Closed as not an issue
