### ISSUE TITLE
Remove Appium Desktop link in getting started on https://appium.io/docs since it is deprecated 

### ISSUE THREAD

**Issue by jonbeacherdomuso** [appium/appium#18160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. https://appium.io/docs/en/about-appium/getting-started/?lang=en
2. Appium can be installed in one of two ways: via [NPM](https://npmjs.com/) or by downloading [Appium Desktop](https://github.com/appium/appium-desktop), which is a graphical, desktop-based way to launch the Appium server.
3. Actual: "downloading [Appium Desktop](https://github.com/appium/appium-desktop)"

### Expected Behavior

3. Expect: Not to see "download Appium Deskop" since it is depreciated
4. https://github.com/appium/appium-desktop/issues/2139#issuecomment-1377637702

### Minimal Reproducible Example

1. Go to https://appium.io/docs/en/about-appium/getting-started/?lang=en
2. Appium can be installed in one of two ways: via [NPM](https://npmjs.com/) or by downloading [Appium Desktop](https://github.com/appium/appium-desktop), which is a graphical, desktop-based way to launch the Appium server.
3. Actual: "downloading [Appium Desktop](https://github.com/appium/appium-desktop)"
5. Not to see "download Appium Deskop" since it is depreciated/not maintained 
6. https://github.com/appium/appium-desktop/issues/2139#issuecomment-1377637702

### Environment

Docs on website https://appium.io/docs/en/about-appium/getting-started/?lang=en

**Comment by KazuCocoa** [comment]
As 

> Note that this documentation explains about Appium 1.x. Please refer to [the README in the Appium repository](https://github.com/appium/appium) or [Appium 2.0 documentation](https://appium.github.io/appium) about Appium 2.0

in the top of the getting-started page, we're moving to a new website for Appium 2.0. Perhaps we should remove content from the old one and leave the new link, or redirect to the new page instead of checking all URLs int he old webpage...

**Comment by jonbeacherdomuso** [comment]
I would either update the url to add 1.0 in https://appium.io/docs/en/about-appium/getting-started/?lang=en to https://appium.io/docs/en/1.0/about-appium/getting-started/?lang=en for parity with the new url including 2.0 in the url

or re direct to https://appium.github.io/appium/docs/en/2.0/quickstart/ when someone goes to https://appium.io/docs/en/about-appium/getting-started/?lang=en

**Comment by jlipps** [comment]
Yeah, we probably want either a per-page redirect or just a global redirect on everything from appium.io at this point, unless/until we want to maintain a marketing site there again.

**Comment by eglitise** [comment]
The current version of appium.io does not have any references to Appium Desktop anymore. Closing as fixed.
