### ISSUE TITLE
bug: Incorrect resolution is obtained when using Xiaomi phone。  

### ISSUE THREAD

**Issue by wantwinwinwin** [appium/appium#18161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using a Xiaomi phone, the resolution obtained by appinum is 1080*2028, but the actual resolution is 1080*2244. An error occurs when using appinum to click on [316, 2099], but it can be clicked normally using adb shell input tap.
![image](https://user-images.githubusercontent.com/114279746/216961056-f8e800c2-6306-4539-aeea-6f43c8d82728.png)

### Expected Behavior

Can obtain the correct resolution of Xiaomi phone screen.

### Minimal Reproducible Example

RF:
click A point x y

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:
appinum --version   1.21.0

### Futher Information

[appium-server-logs.txt](https://github.com/appium/appium/files/10662541/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
The resolution is retrieved directly from Google's UiAutomator. AFAIK it had a known bug in the stable version 2.2, which we use now and which was declared as fixed in 2.3-alpha, which we don't use as it is not stable yet. You could create a custom uia2 server build and try the alpha build there.

Closed as third party issue
