### ISSUE TITLE
bug: appium 2.0.0-beta53 seems to ignore `appium:options` object

### ISSUE THREAD

**Issue by radoslaw-karasinski-sauce** [appium/appium#18191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`derivedDataPath` and `usePrebuiltWDA` setting seems to be ignored in appium 2.0.0-beta53 - `xcodebuild test-without-building` call doesn't use provided values. 

Appium 2.0.0-beta53 seems to also ignore other caps provided in `appium:options`, i.e. `connectHardwareKeyboard`. This method was working for 2.0.0-beta44.

Appium beta53 CLI call: `Appium command is: /Volumes/Sauce/selenium/appium-v2.0.0-beta53/node-darwin --max_old_space_size=1024 /Volumes/Sauce/selenium/appium-v2.0.0-beta53 --log-timestamp --callback-address 127.0.0.1 --address 127.0.0.1 --port 4443 --log-no-colors --default-capabilities {"appium:options": {"usePrebuiltWDA": true, "preventWDAAttachments": true, "orientation": "PORTRAIT", "launchTimeout": 180000, "showIOSLog": false, "noReset": true, "eventTimings": true, "backendRetries": 4, "derivedDataPath": "/Volumes/Sauce/wda/wda-v2.0.0-beta53-xcode13.0/WebDriverAgent/DerivedData/WebdriverAgent", "bootstrapPath": "/Volumes/Sauce/wda/wda-v2.0.0-beta53-xcode13.0/WebDriverAgent", "maxTypingFrequency": 8, "newCommandTimeout": 0, "connectHardwareKeyboard": true, "simulatorPasteboardAutomaticSync": "on", "app": "/var/folders/z9/rg8m2_gs5yq64gd5h71df2cc0000kr/T/tmpC2WXHT/TestApp7.2.app.zip", "keepKeyChains": true}} --relaxed-security --base-path /wd/hub`

Appium beta44 CLI call: `Appium command is: /Volumes/Sauce/selenium/appium-v2.0.0-beta44-separate-homes/node-darwin --max_old_space_size=1024 /Volumes/Sauce/selenium/appium-v2.0.0-beta44-separate-homes --log-timestamp --callback-address 127.0.0.1 --address 127.0.0.1 --port 4443 --log-no-colors --default-capabilities {"appium:options": {"usePrebuiltWDA": true, "preventWDAAttachments": true, "orientation": "PORTRAIT", "launchTimeout": 180000, "showIOSLog": false, "noReset": true, "eventTimings": true, "backendRetries": 4, "derivedDataPath": "/Volumes/Sauce/wda/wda-v2.0.0-beta44-xcode14.0/WebDriverAgent/DerivedData/WebdriverAgent", "maxTypingFrequency": 8, "newCommandTimeout": 0, "connectHardwareKeyboard": true, "simulatorPasteboardAutomaticSync": "on", "app": "/var/folders/z9/rg8m2_gs5yq64gd5h71df2cc0000kr/T/tmpkPWe1U/TestApp7.2.app.zip", "keepKeyChains": true}} --relaxed-security --base-path /wd/hub`

### Expected Behavior

Appium should use provided `derivedDataPath` to pass it to `xcodebuild test-without-building` call.

### Minimal Reproducible Example

Start any session with `derivedDataPath` and `usePrebuiltWDA` inside `appium:options` caps.

### Environment

All informations in attached gist.

### Link to Appium Logs

https://gist.github.com/radoslaw-karasinski-sauce/3bac813bf3080f05cae22cd15ff0a8e7

**Comment by jlipps** [comment]
this should be fixed in the next release. previously there was no intentional support for using `appium:options` together with `--default-capabilities`; it only worked accidentally! (though of course it _should_ be possible to combine these features). the reason it regressed is because we changed where `appium:options` was processed to fix another issue. now we have tests for both cases to prevent further regressions.
