### ISSUE TITLE
How to specify the chromedriver executable path when starting the appium server in 2.0?

### ISSUE THREAD

**Issue by shreyansh1991** [appium/appium#18200]
I am getting below error when using the below command in command prompt.
Command --->  appium --chromedriver-executable "C:\Users\HP\Desktop\chromedriver.exe"

[ERROR] Unrecognized arguments: --chromedriver-executable C:\Users\HP\Desktop\chromedriver.exe

Please suggest how to specify chromdriver.exe path while starting the appium server 2.0?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-uiautomator2-driver#hybrid-mode

Please use Appium forum to ask questions

**Comment by shreyansh1991** [comment]
Thanks a lot. it resolved my issue.
