### ISSUE TITLE
appium 2 web view context not available and can not switch to it for ios hybrid app

### ISSUE THREAD

**Issue by 7999** [appium/appium#18205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I installed appium and start server, run IOSDriver.Contexts just return one context of 'NATIVE_APP', so I can not switch to the web view context.

### Expected Behavior

web view context available

### Minimal Reproducible Example

start appium with plugin xcuitest

### Environment

- Operating system: mac os
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): v2.0.0-beta.55
  - Node.js version (output of `node --version`):v16.15.0
  - `npm` version (output of `npm --version`): 8.5.5
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version: no Appium Desktop
- Appium driver(s) and their version(s): xcuitest@4.16.12
- Appium plugin(s) and their version(s):
- Platform and version under test: ios 15.6
- Real device or emulator/simulator: real device

**Comment by mykola-mokhnach** [comment]
Is the web context visible via Safari Remote Debugger? Sometimes it is also necessary to interact with the web context area (e.g. click it) before web context becomes visible. This is known iOS security limitation

**Comment by 7999** [comment]
@mykola-mokhnach 
thanks for your reply, your are right. when I repacking the app with enable debug mode, the web view context available
