### ISSUE TITLE
bug: `activate_app` hangs forever on invalid app name

### ISSUE THREAD

**Issue by eyJhb** [appium/appium#18206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When launching an invalid app on iOS using `activate_app`, the iOS WDA will hang forever, and does not respond to any commands after that. It seems that the Appium server tries to relay the messages sent to it, however, the WDA does not show much.

### Expected Behavior

Expect it to timeout after X time, instead of just hanging forever.

### Minimal Reproducible Example

```python
from appium import webdriver

caps = {
    "appium:deviceName": "blabla",
    "appium:automationName": "XCUITest",
    "platformName": "iOS",
    # "browserName": "Safari",
    "appium:udid": "auto",
    "appium:usePrebuiltWDA": True,
    "appium:startIWDP": True,
    "appium:webDriverAgentUrl": "http://localhost:7777",
    "appium:newCommandTimeout": 30,
}

driver = webdriver.Remote("http://127.0.0.1:4723", caps)

driver.activate_app("something-invalid")
```

### Environment

- Operating system: NixOS Unstable
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.53
  - Node.js version (output of `node --version`): v18.12.1
  - `npm` version (output of `npm --version`): 8.19.2
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): xcuitest@4.16.12 [installed (NPM)]
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator: Real device

I am running the WDA revision a191d51afc546622b502e23175bfe4dc15633e79 from https://github.com/appium/WebDriverAgent .
I am starting the WDA using go-ios, which I doubt is an issue, but might be important.

### Futher Information

Small logs

go-ios wda
```
{"fields.msg":"    t =    10.79s Open something-invalid\n","fields.time":399180494663,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":630,"time":"2023-02-15T13:41:24+01:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:willStartActivity:","time":"2023-02-15T13:41:24+01:00"}
{"fields.msg":"    t =    10.79s     Launch something-invalid\n","fields.time":399180529167,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":630,"time":"2023-02-15T13:41:24+01:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:willStartActivity:","time":"2023-02-15T13:41:24+01:00"}
{"fields.msg":"2023-02-15 13:41:24.432571+0100 WebDriverAgentRunner-Runner[630:79142] Enqueue Failure: Failed to launch something-invalid: The request to open \"something-invalid\" failed. (Underlying Error: The operation couldn’t be completed. Application info provider (FBSApplicationLibrary) returned nil for \"something-invalid\") /Users/morgan/appium/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 44 1\n","fields.time":399181118206,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":630,"time":"2023-02-15T13:41:24+01:00"}
```

appium

```
[HTTP] --> POST /session/78c651a4-c16a-4cbd-a62f-6fc84ec1a987/appium/device/activate_app
[HTTP] {"appId":"something-invalid"}
[debug] [XCUITestDriver@cbf5 (78c651a4)] Calling AppiumDriver.activateApp() with args: ["something-invalid",null,null,null,"78c651a4-c16a-4cbd-a62f-6fc84ec1a987"]
[debug] [XCUITestDriver@cbf5 (78c651a4)] Executing command 'activateApp'
[debug] [XCUITestDriver@cbf5 (78c651a4)] Proxying [POST /wda/apps/launch] to [POST http://localhost:7777/session/13D6D250-32DB-4224-A78C-95048DD61FF1/wda/apps/launch] with body: {"bundleId":"something-invalid"}
```

**Comment by mykola-mokhnach** [comment]
I don't think there is anything we could there. The call is simply proxied to XCTest and we cannot do much if the latter does not react properly to it. You could [list apps](https://appium.github.io/appium-xcuitest-driver/4.16/execute-methods/#mobile-listapps) available on the device prior to calling this API to make sure the given app bundle exists there.

**Comment by eyJhb** [comment]
I might be reading this wrong @mykola-mokhnach , but doesn't the last line state that it actually failed, and afterwards one should be able to sent commands to WDA again?

> {"fields.msg":"2023-02-15 13:41:24.432571+0100 WebDriverAgentRunner-Runner[630:79142] Enqueue Failure: Failed to launch something-invalid: The request to open \"something-invalid\" failed. (Underlying Error: The operation couldn’t be completed. Application info provider (FBSApplicationLibrary) returned nil for \"something-invalid\") /Users/morgan/appium/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 44 1\n","fields.time":399181118206,"level":"info","msg":"outputReceived:fromProcess:atTime:","pid":630,"time":"2023-02-15T13:41:24+01:00"}

Because the hanging part, is mostly WDA that stops responding. As far as I can see, an error is returned.

Also, good idea wit the listing of apps. That could be a good workaround for now :)

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by eyJhb** [comment]
> Closed as third party issue

Could you please elaborate on the concerns above, before closing? It doesn't seem like it fails without error, and could be handled in WDA.

**Comment by mykola-mokhnach** [comment]
Sure, here's is the documentation for the [XCUIApplication launch] API:

```
/*!
 * Launches the application synchronously. On return the application ready to handle events. If the
 * application is already running, the existing instance will be terminated to ensure a clean state
 * for the launched instance.
 *
 * Any failure in the launch sequence will be reported as a test failure and the test will be halted
 * at that point.
*/
- (void)launch;
```

If you could find anything which would prevent the test to be halted then please let us know.

**Comment by eyJhb** [comment]
Thank for for this answer, it helps me understand why this is the case.
I am fairly (very) new to this entire project, and still have trouble finding out where I need to look.

Thanks! :)
