### ISSUE TITLE
bug: WDA crashing with FBStaleElementException since updating to Appium 2.0

### ISSUE THREAD

**Issue by grant-mccarriagher** [appium/appium#18214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We're getting a lot of crashes in WDA since migrating to Appium 2.0 earlier today.

### Expected Behavior

WDA doesn't crash intermittently.

### Minimal Reproducible Example

I don't see any common set of requests to Appium that cause this crash to happen. They're pretty intermittent, but common enough to bomb most of our testing runs.

### Environment

- Operating system: macOS 13.2.1
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.55
  - Node.js version (output of `node --version`): 16.13.2
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 1.22.3
- Appium driver(s) and their version(s): xcuitest@4.16.12
- Appium plugin(s) and their version(s): none
- Platform and version under test: iOS 16.3.1
- Real device or emulator/simulator: real

### Link to Appium Logs

https://gist.github.com/grant-mccarriagher/6bd7f363db549c2a1c1b964e57578d03 (WDA log)

### Futher Information

Just for extra context in case it matters, each of our test runners is a Mac Mini with 8 iPhones connected to it, running a single Appium server. We maintain each phone's WDA connection outside of the test runs (loosely based on https://github.com/appium/appium-xcuitest-driver/blob/master/docs/wda-custom-server.md, using iproxy).

**Comment by grant-mccarriagher** [comment]
These are our capabilities, in case it's needed:

```
  {
    'appium:automationName': "XCUITest",
    'appium:bundleId': bundleId,
    'appium:deviceName': "iPhone",
    'appium:platformName': "iOS",
    'appium:platformVersion': '16.3',
    'appium:xcodeOrgId': "editing this out",
    'appium:xcodeSigningId': "iPhone Developer",
    'appium:udid': udid || process.env.UDID,
    'appium:orientation': "PORTRAIT",
    'appium:app': process.env.APP,
    'appium:newCommandTimeout': 240,
    'appium:noReset': true,
    'appium:mjpegServerPort': mpegPort,
    'appium:autoAcceptAlerts': true,
    'appium:appPushTimeout': 200000,
    'appium:locationServicesEnabled':true,
    'appium:locationServicesAuthorized':true,
    'appium:webDriverAgentUrl': webDriverAgentUrl,
  }
```

**Comment by mykola-mokhnach** [comment]
Normally all exceptions should be caught by the web server: https://github.com/appium/WebDriverAgent/blob/a191d51afc546622b502e23175bfe4dc15633e79/WebDriverAgentLib/Routing/FBWebServer.m#L205

I assume this particular one happens in the monitoring thread created as a result of autoAcceptAlerts enablement. 
I will try to add a patch there, although it would be nice if you could provide the full stacktrace by compiling WDA if debug mode.

**Comment by grant-mccarriagher** [comment]
@mykola-mokhnach Not sure what you mean by compiling WDA in debug mode; we already are using the `-configuration Debug` flag when building it using Xcode, if that's what you mean.

**Comment by mykola-mokhnach** [comment]
> *** First throw call stack:
> (0x18cd28e38 0x185ebf8d8 0x106ccfdc0 0x106c8ceac 0x106ca7204 0x19433f460 0x194340f88 0x19434f7f4 0x19434f444 0x18cdb96c8 0x18cd9b02c 0x18cd9feb0 0x1870d4054 0x106c911e4 0x10493f9d4 0x18cd936b4 0x18cd3fb1c 0x104ba18e8 0x104ba189c 0x104ba1228 0x104b5f938 0x104ba1088 0x104ba15f4 0x104ba1970 0x104b8e8c0 0x104b6cc1c 0x104b98220 0x104b8e840 0x104b58518 0x104b8e3dc 0x104b8f9dc 0x104b58518 0x104b8f530 0x104b76348 0x104b7625c 0x104b8f1bc 0x104b473cc 0x104b78fa4 0x104b78e84 0x104b78934 0x104b76348 0x104b7625c 0x104b788d0 0x104b78b8c 0x104b473cc 0x104b78fa4 0x104b78e84 0x104b78934 0x104b76348 0x104b7625c 0x104b788d0 0x104b78b8c 0x104b473cc 0x104b78fa4 0x104b78e84 0x104b78934 0x104b76348 0x104b7625c 0x104b788d0 0x104b78b8c 0x104b473cc 0x104b48f14 0x104b76348 0x104b7625c 0x104b48e08 0x104bae4c0 0x104bae610 0x104b7354c 0x104b51670 0x104b731a8 0x104b479bc 0x104565d1c 0x104565d00 0x18cd62514 0x18cdcad6c 0x18cd9ab90 0x18cd9feb0 0x1c6f95368 0x18f295668 0x18f2952cc 0x104565ed0 0x1ab698960)

It would be interesting if it is possible to make WDA to print a proper stacktrace instead of the set of numbers above.

**Comment by grant-mccarriagher** [comment]
Sorry, not sure how to get Xcode to symbolicate those traces in the xcodebuild output. I dug around in the derived data logs as well, but the xctestresult files seem to always be corrupt and unreadable by Xcode.

If you know if a setting we can change when building WDA, let me know and we can try and get the logs you want.

**Comment by grant-mccarriagher** [comment]
In the meantime, I'll try testing the changes from that PR manually and I'll keep you updated on the results.

**Comment by grant-mccarriagher** [comment]
@mykola-mokhnach In our local testing of the fix, this did seem to resolve the issue. I see that it's also been released to xcuitest-driver, so we'll pull that.

Thanks for the quick turnaround!
