### ISSUE TITLE
bug: <WebDriverAgentRunner-Runner[727:75424] The bundle “WebDriverAgentRunner” couldn’t be loaded because its executable couldn’t be located. Try reinstalling the bundle.>

### ISSUE THREAD

**Issue by manojagarwal0712** [appium/appium#18225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Description: 
Unable to run WebDriverAgentRunner on IOS real device or simulator. The issue started happening after upgraded to MacOS: Ventura : 13.2 (22D49), which also must to have Xcode 14+

macOS: 13.2 (22D49)
XCode: 14.2
Appium: 1.22.0

2023-02-20 11:44:52.528447+0530 WebDriverAgentRunner-Runner[727:75424] Running tests...
2023-02-20 11:44:52.570960+0530 WebDriverAgentRunner-Runner[727:75424] The bundle “WebDriverAgentRunner” couldn’t be loaded because its executable couldn’t be located. Try reinstalling the bundle.

### Expected Behavior

WebDriverAgentRunner agent should work find and corresponding test should run fine.  

### Minimal Reproducible Example

macOS: 13.2 (22D49)
XCode: 14.2
Appium: 1.22.0
iPhone 12 / 14.8

Run Product -> Test (WebDriverAgentRunner) on the device

### Environment

- Operating system: 
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s): 1.20
- Platform and version under test:: IOS
- Real device or emulator/simulator: - Real device iPhone 12/14.8

**Comment by KazuCocoa** [comment]
Please try the latest XCUITest with Appium 2.0
https://appium.github.io/appium/docs/en/2.0/guides/migrating-1-to-2/

**Comment by manojagarwal0712** [comment]
Hi [KazuCocoa](https://github.com/KazuCocoa),
Thanks for responding. 
Is there a reason to why appium 2.0 shall work.? can I not use Appium: 1.22.0.?

**Comment by KazuCocoa** [comment]
Xcode 14 get failed to build the WebDriverAgent version. Newer one has the fix.

**Comment by manojagarwal0712** [comment]
wow, This worked fine. Thank you so much! It took a precious day of mine thinking somethings wrong with Xcode! Xcode and Appium sucks!

> npm install -g appium@next
> appium driver install xcuitest
> appium driver install uiautomator2
> appium -v
