### ISSUE TITLE
Unable to put the device in airplane mode for tosca automation testing in sauce labs

### ISSUE THREAD

**Issue by madhusmitananda1** [appium/appium#18229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are unable to put the IOS device on flight mode and we have test cases to check offline functionality .hence please update.

### Expected Behavior

we should be able to put the device in flight mode but as per saucelabs appium has a limitation . Added ticket details with sauce labs as well.

### Minimal Reproducible Example

1) pick a device in sauce labs
2) Try to put device in airplane mode using tosca automation. It does not work for IOS.

### Environment

Sauce labs device -iPhone 11 pro with 14.8 version .

### Futher Information

[issue.docx](https://github.com/appium/appium/files/10787847/issue.docx)

**Comment by KazuCocoa** [comment]
Could you share the full Appium log? XCUITest driver may return not implemented error. Btw, when you change the network preference in the middle of a session, probably the Appium XCUITest driver session may stop as XCTest session's behavior (by Apple).

**Comment by mykola-mokhnach** [comment]
Apple does not provide any API to do that in XCTest. The only way to switch Airplane mode state would be to do this via UI, like a normal user would.

**Comment by madhusmitananda1** [comment]
Can we add it as a feature request?


From: Mykola Mokhnach ***@***.***>
Date: Tuesday, February 21, 2023 at 1:39 AM
To: appium/appium ***@***.***>
Cc: Nanda, Madhusmita ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [appium/appium] Unable to put the device in airplane mode for tosca automation testing in sauce labs (Issue #18229)

Apple does not provide any API to do that in XCTest. The only way to switch Airplane mode state would be to do this via UI, like a normal user would.
