### ISSUE TITLE
Appium doesn't recognise In App purchase, Apple ID and password Text field 

### ISSUE THREAD

**Issue by devlove1C** [appium/appium#18238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just want to implement the sandbox In- App purchase flow for my App, Where I can **Sign In With Apple ID** and perform the my flow. I tried to access the Apple Id text filed via "`els1 = driver.find_elements(by=AppiumBy.IOS_CLASS_CHAIN, value="Class chain value here")", els1[0].send_keys("dev@gmail.com")`. But its not entring any value in the Apple ID text filed, 
Same process i have tried by XPath, facing the same issue 

### Expected Behavior

In - App Purchase popup filed should be accessible via XPATH or Class chain. 
Pleasse guide us, how we can handle the In App purchase Popup for sandbox purchasing flow.

### Minimal Reproducible Example

```
options = XCUITestOptions()
options.platform_name = 'iOS'
options.udid = 'Abcd'
options.device_name = 'iPhone'
options.app = '/iOSApp.app'
driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', options=options)
driver.find_element(AppiumBy.XPATH,'//XCUIElementTypeStaticText[@name="Buy"]').click()
driver.find_element(AppiumBy.XPATH,'//XCUIElementTypeAlert[@name="Sign in with Apple ID"]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeCollectionView/XCUIElementTypeCell[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]')
els1 = driver.find_elements(by=AppiumBy.IOS_CLASS_CHAIN, value="**/XCUIElementTypeAlert[`label == \"Sign in with Apple ID\"`]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeCollectionView/XCUIElementTypeCell[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]")
els1.send_keys("abcd@gmail.com")
```

### Environment

- Operating system: Mac 
- If running via `appium` CLI...
  - Appium CLI version `1.22.3`
  - Node.js version  `v19.6.1`
  - `npm` version `9.4.0`
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test: iOS , XCUITest
- Real device or emulator/simulator: iPhone 11

### Futher Information

Could you share a documents link to handle the In - App purchase Alert popup.

**Comment by mykola-mokhnach** [comment]
I assume Apple has blocked it because of their security requirements. You could verify it by just running a vanilla UI XCTest on the same dialog. 
I would try to copy and paste the desired text into this textfield as a possible workaround.

**Comment by devlove1C** [comment]
Thanks @mykola-mokhnach for replying on my comment, 
I have also one more query on this issue,
I have tried to access the In app purchase dialog box by Appium inspector and successfully send the value to Apple id Text field. For your reference I am sharing the video clip.

https://user-images.githubusercontent.com/21331129/220760631-a5496f97-2d8c-421c-956d-171aa4d5c348.mp4


If we are able to access the  In app purchase dailog box text field by the appium inspector, So Can we access it using the script? 
Please help us here

**Comment by mykola-mokhnach** [comment]
First, make sure the inspector and your automated test use the same xcuitest driver version (btw we do not support or maintain Appium 1 anymore). Second, make sure your locator is targeting an appropriate element and there is no race condition. The way current locator looks is just super suboptimal.

**Comment by mykola-mokhnach** [comment]
```
els1 = driver.find_elements(by=AppiumBy.IOS_CLASS_CHAIN, value="**/XCUIElementTypeAlert[`label == \"Sign in with Apple ID\"`]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeCollectionView/XCUIElementTypeCell[1]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]")
els1.send_keys("abcd@gmail.com")
```

this code is not supposed to work as find_elements returns an array and `send_keys` could only be invoked on an element instance

**Comment by mykola-mokhnach** [comment]
Closed because of no response
