### ISSUE TITLE
Unable to scan controls in tosca for automation as we get a blank screen 

### ISSUE THREAD

**Issue by madhusmitananda1** [appium/appium#18230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we scan controls in tosca for mobile application we don't see the controls. added snapshot for tosca and saucelabs discussion where its mentioned that its appium limitation.hence please update

### Expected Behavior

we should be able to scan controls

### Minimal Reproducible Example

1.login to tosca and pick up a device in saucelabs
2,click scan in tosca and we will see blank screen.

### Environment

device is picked up in saucelabs

### Futher Information

[issue.docx](https://github.com/appium/appium/files/10787894/issue.docx)
[issue.docx](https://github.com/appium/appium/files/10787896/issue.docx)

**Comment by KazuCocoa** [comment]
Could you explain more concrete example here? What endpoint in appium did not show "controls" (what this "controls"?)

**Comment by KazuCocoa** [comment]
>  its appium limitation

It is helpful to understand the situation to provide the full Appium server log as well

**Comment by mykola-mokhnach** [comment]
xcuitest driver is based on XCTest. And XCTest itself uses accessibility. Hence there is no way it could show any controls in the page source if these are not accessible. Check https://applevis.com/developers for more details

**Comment by mykola-mokhnach** [comment]
Also we don not support .docx attachments. Consider providing them as GIST in plain text. Not everybody have word processors installed on their machines. 
Regarding tosca - Appium team itself neither supports nor knows about such tool. It is an utility used purely Sauce Labs, so please contact their customer regarding its functionality. We could only help here with issues related to Appium server itself or its drivers (if enough information is provided, e.g. that is requested in the issue template)

**Comment by madhusmitananda1** [comment]
Can we add it as a feature request?

From: Mykola Mokhnach ***@***.***>
Date: Tuesday, February 21, 2023 at 1:42 AM
To: appium/appium ***@***.***>
Cc: Nanda, Madhusmita ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [appium/appium] Unable to scan controls in tosca for automation as we get a blank screen (Issue #18230)

xcuitest driver is based on XCTest. And XCTest itself uses accessibility. Hence there is no way it could show any controls in the page source if these are not accessible. Check https://applevis.com/developers<https://urldefense.com/v3/__https:/applevis.com/developers__;!!Fto3Xw!oKwDzFW7yPwoJ0mPlnCDokpjWFc1E1tTIuMoeWgDvxift-BbWA6nhZ7iYp06sjr1ZgwKKRJCPm20sB4EKP8iT195PJB-yg$> for more details

**Comment by jlipps** [comment]
> Can we add it as a feature request?

No. It would be a feature request for Apple.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
