### ISSUE TITLE
appium-webdriveragent not showing in appium 2.0.0-beta.48

### ISSUE THREAD

**Issue by vigneshviacom** [appium/appium#18254]
Am facing problem in Appium installation 2.0.0-beta.48. After run the command npm install -g appium@2.0.0-beta.48
Appium is installed but in the appium -> node_modules -> appium-webdriveragent is not present. Because of this i am not able to build the WebDriverAgent.xcodeproj.

Version details
mac Monterey 12.6.3, Xcode -  14.0, AppleTV - 15.4.1
installed  
- xcuitest@4.18.1 [installed (NPM)]
- uiautomator2@2.12.6 [installed (NPM)]

In package.json
{
  "name": "appium",
  "version": "2.0.0-beta.48",
  "description": "Automation for Apps.",
  "keywords": [
    "automation",
    "javascript",
    "selenium",
    "webdriver",
    "ios",
    "android",
    "firefoxos",
    "testing"
  ],
  "homepage": "https://appium.io",
  "bugs": {
    "url": "https://github.com/appium/appium/issues"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/appium/appium.git",
    "directory": "packages/appium"
  },
  "license": "Apache-2.0",
  "author": "https://github.com/appium",
  "types": "./build/lib/main.d.ts",
  "bin": {
    "appium": "index.js"
  },

**Comment by mykola-mokhnach** [comment]
This is expected. Drivers are not supplied with Appium 2 server by default and must be installed separately, for example `appium driver install xcuitest` to install xcuitest driver. Afterwards you could use the `appium driver run xcuitest open-wda` command to open the folder where WDA is installed in Finder.

**Comment by vigneshviacom** [comment]
@mykola-mokhnach  Yes, Now the Appium is build success. And facing another issue while trying to launch the App.

Failed to create session. An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70 xcodebuild error message: . Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

[debug] [XCUITestDriver@6a51 (5d7503df)] Matched '/status' to command name 'getStatus'
[debug] [XCUITestDriver@6a51 (5d7503df)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [iProxy@71f916e0:8100] Unexpected data: {"header":{"length":294,"version":1,"type":8,"tag":1},"payload":{"MessageType":"Result","Number":2}}
[XCUITestDriver@6a51 (5d7503df)] socket hang up
[Xcode] xcodebuild exited with code '70' and signal 'null'
[debug] [XCUITestDriver@6a51 (5d7503df)] Event 'wdaStartFailed' logged at 1677489251887 (14:44:11 GMT+0530 (India Standard Time))
[debug] [XCUITestDriver@6a51 (5d7503df)] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
[debug] [XCUITestDriver@6a51 (5d7503df)] xcodebuild error message:
[debug] [XCUITestDriver@6a51 (5d7503df)] . Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITestDriver@6a51 (5d7503df)] Quitting and uninstalling WebDriverAgent
[XCUITestDriver@6a51 (5d7503df)] Shutting down sub-processes
[debug] [XCUITestDriver@6a51 (5d7503df)] No WDAs on the device.
[XCUITestDriver@6a51 (5d7503df)] {}
[DevCon Factory] Releasing connections for 71f916e0990bab7fc46401e0abea4ce5fa9b699f device on any port number
[DevCon Factory] Found cached connections to release: ["71f916e0990bab7fc46401e0abea4ce5fa9b699f:8100"]
[DevCon Factory] Releasing the listener for '71f916e0990bab7fc46401e0abea4ce5fa9b699f:8100'
[debug] [iProxy@71f916e0:8100] Closing the connection
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITestDriver@6a51 (5d7503df)] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iProxy@71f916e0:8100] The connection has been closed
[debug] [AppiumDriver@9956] Event 'newSessionStarted' logged at 1677489252228 (14:44:12 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@9956] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
[debug] [AppiumDriver@9956] xcodebuild error message:
[debug] [AppiumDriver@9956] . Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [AppiumDriver@9956]     at quitAndUninstall (/Users/devolper/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:584:15)
[debug] [AppiumDriver@9956]     at /Users/devolper/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:619:11
[debug] [AppiumDriver@9956]     at wrapped (/Users/devolper/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:95:13)
[debug] [AppiumDriver@9956]     at retry (/Users/devolper/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:68:13)
[debug] [AppiumDriver@9956]     at retryInterval (/Users/devolper/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:105:10)
[debug] [AppiumDriver@9956]     at /Users/devolper/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:599:7
[HTTP] <-- POST /session 500 73033 ms - 1332
[HTTP]

**Comment by mykola-mokhnach** [comment]
try to look for existing issues. Usually xcodebuild failures are caused by local deployment or signing issues.
