### ISSUE TITLE
bug: Unable to install espresso driver from github source

### ISSUE THREAD

**Issue by pr4bh4sh** [appium/appium#18264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When following instructions to install the driver from https://github.com/appium/appium#drivers from source as github I get the below error
```
appium driver install --source=github appium/appium-espresso-driver
Error: ✖ When using --source=github, must also use --package
```

Adding --package gives below error 
```
appium driver install --source=github --package appium/appium-espresso-driver
usage: appium driver install [-h] [--json] [--source {git,github,local,npm}] [--package PACKAGENAME] driver

appium driver install: error: the following arguments are required: driver
```

### Expected Behavior

The driver should be installed, maybe the instruction has not been updated in the Readme.

### Minimal Reproducible Example

an example is added to the current behaviour section

### Environment

- Operating system: MacOS 13.2.1
- Appium CLI version (output of `appium --version`): 2.0.0-beta.56
- Node.js version (output of `node --version`): v18.12.1
- `npm` version (output of `npm --version`):  8.19.2

**Comment by mykola-mokhnach** [comment]
Try maybe `appium driver install --source=github --package=appium/appium-espresso-driver appium-espresso-driver`

**Comment by jlipps** [comment]
no, it would be the other way around I think:

```
appium driver install --source=github --package=appium-espresso-driver appium/appium-espresso-driver
```

**Comment by pr4bh4sh** [comment]
Thanks, @jlipps, your command worked.

**Comment by mykola-mokhnach** [comment]
Updated the readme
