### ISSUE TITLE
[Feat]: skip installation with app capability if the installed app was the same or greater version

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#18279]
**Is your feature request related to a problem? Please describe.**

To avoid installing app every session with `app` capability

**Describe the solution you'd like**

This is an idea right now.

If the installed app has the same app version, we may be able to skip the app installation to avoid unnecessary install/upgrade. It should be configurable via capabilities, and should be false by default (keep current behavior by default).

So, like https://github.com/appium/appium-xcuitest-driver/blob/2d1685b660e96e8834edc264216fd5efa955eeac/lib/ios-deploy.js#L145-L153 , a method will return the installed app version and compare the version with `app` capability's one.
(Need to check if it is possible first)

**Describe alternatives you've considered**

**Additional context**

**Comment by mykola-mokhnach** [comment]
I can add a helper to appium-ios-simulator to read the info about installed apps

**Comment by mykola-mokhnach** [comment]
Perhaps we already have a Simulator alternative: https://github.com/appium/node-simctl/blob/f42bb0355837f95ba793216276067505569fb40e/lib/subcommands/appinfo.js#L4

**Comment by mykola-mokhnach** [comment]
I have prepared https://github.com/appium/appium-xcuitest-driver/pull/1514
