### ISSUE TITLE
bug: appium 2.0.0-beta56 doesn't allow to use browserName in appium:options passed via CLI --default-capabilities

### ISSUE THREAD

**Issue by radoslaw-karasinski-sauce** [appium/appium#18274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It's not possible to use `browserName` inside `appium:options` object passed via CLI `--default-capabilities`.

This worked for appium-2.0.0-beta.44, so I'm not sure if this is regression related to https://github.com/appium/appium/issues/18191 or maybe this is intentional change. If so, what would be proper way of specifying that cap?

Working CLI command for appium beta 44:
`Appium command is: /Volumes/Sauce/selenium/appium-v2.0.0-beta44-separate-homes/node-darwin --max_old_space_size=1024 /Volumes/Sauce/selenium/appium-v2.0.0-beta44-separate-homes --log-timestamp --callback-address 127.0.0.1 --address 127.0.0.1 --port 4443 --log-no-colors --default-capabilities {"appium:options": {"usePrebuiltWDA": true, "orientation": "PORTRAIT", "launchTimeout": 180000, "showIOSLog": false, "noReset": true, "bootstrapPath": "/Volumes/Sauce/wda/wda-v2.0.0-beta44-xcode13.0/WebDriverAgent", "backendRetries": 4, "derivedDataPath": "/Volumes/Sauce/wda/wda-v2.0.0-beta44-xcode13.0/WebDriverAgent/DerivedData/WebdriverAgent", "browserName": "safari", "maxTypingFrequency": 8, "newCommandTimeout": 0, "preventWDAAttachments": true, "eventTimings": true, "keepKeyChains": true}} --relaxed-security --base-path /wd/hub`

Not working CLI command for appium beta 56:
`Appium command is: /Volumes/Sauce/selenium/appium-v2.0.0-beta56/node-darwin --max_old_space_size=1024 /Volumes/Sauce/selenium/appium-v2.0.0-beta56 --log-timestamp --callback-address 127.0.0.1 --address 127.0.0.1 --port 4443 --log-no-colors --default-capabilities {"appium:options": {"orientation": "PORTRAIT", "launchTimeout": 180000, "showIOSLog": false, "noReset": true, "backendRetries": 4, "browserName": "safari", "maxTypingFrequency": 8, "newCommandTimeout": 0, "preventWDAAttachments": true, "eventTimings": true, "keepKeyChains": true}} --relaxed-security --base-path /wd/hub` 

### Expected Behavior

It should be possible to use `browserName` capability inside `appium:options`. 

### Minimal Reproducible Example

Start session with `browserName` inside  `appium:options` caps passed via `--default-capabilities`.

### Environment

Logs with difference between beta56 and beta44 in gist.

### Link to Appium Logs

https://gist.github.com/radoslaw-karasinski-sauce/5d2177511987521b85a3a24b78101526

**Comment by wswebcreation** [comment]
`browserName` is part of the W3C caps, see also https://appium.github.io/appium/docs/en/2.0/guides/caps/, which would confirm why this is not working. The question would be if this is regression

**Comment by mykola-mokhnach** [comment]
I also don't think that standard W3C caps should be put into appium:options

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
