### ISSUE TITLE
[Feat]: Get Text for Button element should not get value attribute

### ISSUE THREAD

**Issue by taupenot-autify** [appium/appium#18285]
**Is your feature request related to a problem? Please describe.**
When trying to get the text of a Button element with WebDriver, the current logic will return the first non-empty value out of `value` and `label` attribute. Despite the fact that `value` attribute of a Button element is not the displayed text. As a result, if value is set, it will return a value that is not the displayed text.

This line: https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBElementCommands.m#L138

**Describe the solution you'd like**
Get text logic for Button elements never return the value attribute.

**Describe alternatives you've considered**
By considering the type of element (ex: a XCUIElementTypeButton), get text logic only return possible displayed text.

**Additional context**

This line in WebDriverAgent is responsible for the error: https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBElementCommands.m#L138

Given this element:
<XCUIElementTypeButton type="XCUIElementTypeButton" value="1" name="本文" label="本文">
The current output of get text logic is "1" while the actual displayed is "本文" so there is a mismatch.

**Comment by mykola-mokhnach** [comment]
This logic was always there, so we cannot change simply it without breaking the previous algorithms.

 Try to explicitly fetch the attribute you need by its name as a workaround.

**Comment by mykola-mokhnach** [comment]
I don't think there is anything more to do on this issue
