### ISSUE TITLE
bug: windows-driver Error: Could not find any Visual Studio installation to use

### ISSUE THREAD

**Issue by CRYPTO-7CA** [appium/appium#18291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am installing a standalone Appium 2 beta Server in a dedicated directory on my Windows 10 machine. I dedicated a location "C:\Programs\Appium" to install Appium and it's drivers. I use PowerShell with Administrative rights to perform the installation.

Right now the installation fails only when I attempt to install `appium-windows-driver`. The error message is

```
You need to install the latest version of Visual Studio
including the "Desktop development with C++" workload.
For more information consult the documentation at:
https://github.com/nodejs/node-gyp#on-windows
```

`npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use`

Visual Studio however is not listed as part of requirements to install the appium windows driver.

### Expected Behavior

Appium and it's drivers used to install just fine with the steps described minimal reproducible example. It used to work on my Windows 10 machine and now it does not for some reason. Someone else attempted to reproduce this using my steps but the installation was successful on their side.

### Minimal Reproducible Example

Use Windows
Open PowerShell with Administrative Rights.
Go to a dedicated location e.g. "C:\Programs\Appium"
Run these 2 commands in PowerShell
`npm init -y`
`npm install --save appium@next appium-windows-driver appium-uiautomator2-driver`

### Environment

- Operating system: Windows 10
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): N/A
  - Node.js version (output of `node --version`): v18.12.1
  - `npm` version (output of `npm --version`): 8.19.2
  - Last `appium` version which did _not_ exhibit the problem: 2.0.0-beta.46

### Link to Appium Logs

https://gist.github.com/CRYPTO-7CA/d0e1903bdf41ea732c05768e49d7b43e

**Comment by mykola-mokhnach** [comment]
We've recently added several gesture extensions, which require WinAPI access. The latter is only possible via ffi-napi Node.js module that requires Visual Studio in order to be installed properly. 

Although it does make sense to make it optional if one does not plan to invoke these specific extensions. https://github.com/appium/appium-windows-driver/pull/167 changes the native modules loading logic, so it will only error out if the corresponding APIs are invoked instead on driver load/install

**Comment by mykola-mokhnach** [comment]
The patch has been merged. Now all napi-modules are optional
