### ISSUE TITLE
UnknownError: An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000

### ISSUE THREAD

**Issue by trangle972501** [appium/appium#18296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

os.name: 'Mac OS X', 
os.arch: 'aarch64', os.version: '13.2.1', 
java.version: '19.0.2'
Xcode: 14.2
appium: 1.22.3

I got the error as below when I try to connect ios real devices

UnknownError: An unknown server-side error occurred while processing the command. Original error: Failed to receive any data within the timeout: 5000
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)

<img width="996" alt="Screenshot 2023-03-04 at 22 28 29" src="https://user-images.githubusercontent.com/26322065/222914760-3db83604-b499-4ef7-bfb4-e0c1be28367a.png">

### Expected Behavior

The error should not display. We can connect to ios real devices sucessfully 

### Minimal Reproducible Example

<img width="996" alt="Screenshot 2023-03-04 at 22 28 29" src="https://user-images.githubusercontent.com/26322065/222914861-a552e083-dc62-44e8-92cb-8f3f70dd78e5.png">

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Appium 1 does not support Xcode 14+
Consider switching to xcuitest driver supplied with Appium 2.

Closed as duplicate
