### ISSUE TITLE
bug: Unable to select the value from the dropdown using Appium IOS Real Device

### ISSUE THREAD

**Issue by FWDQK** [appium/appium#18306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to select a value from the dropdown but when I tried to inspect the element, dropdown objects not seen in the App Source.
It only shows the field on which we click and drop down gets open.
Object type is XCUIElementTypeOther
Appium is v2.0.0-beta.46

We have tried to identify object using text (dropdown value) as xpath but script fails, as it does not find any object with this locator.

### Expected Behavior

Need option using which we can select drop down values for such drop down fields.

### Minimal Reproducible Example

![MicrosoftTeams-image (20)](https://user-images.githubusercontent.com/111964982/223115136-d0a91756-2d68-40b4-9b42-66a8ebc7c5ef.png)
#10727

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
The page source only shows elements that are accessible. Please double check with your developers this is true for the above control.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
