### ISSUE TITLE
IOS multi devices parallel test can not get screenshot in second device and have error logs

### ISSUE THREAD

**Issue by 7999** [appium/appium#18301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

first ipad get screenshot succeed, but can not get screenshot in second device, there have error logs: Could not proxy command to the remote server. Original error: socket hang up

### Expected Behavior

get screenshot on every device

### Minimal Reproducible Example

    capabilities: {
        iPadOne: {
            capabilities: {
                "platformName": "iOS",
                "appium:platformVersion": "15.6",
                "appium:udid": "86bd628114a441d94016e1f005f480756425eb5c",
                "appium:deviceName": "iPad(6th generation)",
                "appium:bundleId": "xxx",
                "appium:automationName": "XcuiTest",
                "appium:noReset": true,               
                "appium:webDriverAgentUrl": "http://localhost:8100",
                "appium:derivedDataPath": "/Users/administrator/Documents/iPadOne"
            }
        },
        iPadTwo: {
            capabilities: {
                "platformName": "iOS",
                "appium:platformVersion": "15.7",
                "appium:udid": "d9467c94573c02c5c306de5c627c76c9b6cbb7e1",
                "appium:deviceName": "iPad(6th generation)",
                "appium:bundleId": "xxx",
                "appium:automationName": "XcuiTest",
                "appium:noReset": true,               
                "appium:webDriverAgentUrl": "http://localhost:8101",
                "appium:derivedDataPath": "/Users/administrator/Documents/iPadTwo"

            }
        }
    }

### Environment

- Operating system: mac os
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.55
  - Node.js version (output of `node --version`): v16.15.0
  - `npm` version (output of `npm --version`): 8.5.5
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): xcuitest@4.16.12
- Appium plugin(s) and their version(s): --
- Platform and version under test: ipad os 15.7 and ipad os 15.6
- Real device or emulator/simulator: real device

### Link to Appium Logs

[wdio-appium.log](https://github.com/appium/appium/files/10895974/wdio-appium.log)

### Futher Information

use client of WebDriverIO

**Comment by 7999** [comment]
> > [debug] [38;5;32m[XCUITestDriver@9a40 (cc647556)][0m Matched '/screenshot' to command name 'getScreenshot'
> > [debug] [38;5;32m[XCUITestDriver@9a40 (cc647556)][0m Proxying [GET /screenshot] to [GET http://localhost:8101/session/5C079171-31F8-48A8-9D01-8A57113C21A6/screenshot] with no body
> > [38;5;32m[XCUITestDriver@9a40 (cc647556)][0m socket hang up
> > [38;5;32m[XCUITestDriver@9a40 (cc647556)][0m Error getting screenshot: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
> > [debug] [38;5;32m[XCUITestDriver@9a40 (cc647556)][0m Taking screenshot with WDA
> > [debug] [38;5;32m[XCUITestDriver@9a40 (cc647556)][0m Matched '/screenshot' to command name 'getScreenshot'
> > [debug] [38;5;32m[XCUITestDriver@9a40 (cc647556)][0m Proxying [GET /screenshot] to [GET http://localhost:8101/session/5C079171-31F8-48A8-9D01-8A57113C21A6/screenshot] with no body
> > [38;5;32m[XCUITestDriver@9a40 (cc647556)][0m Error: read ECONNRESET
> 
> It looks like at this point WebDriverAgent has died, probably because of some internal failure. You could try to fetch the device logs for this time period and check if there are any exception traces there.

fine, but how can I to collect the devices logs? enable appium:showIOSLog:true ?

**Comment by mykola-mokhnach** [comment]
Set showIOSLog to true or get logs directly from Xcode. Just make sure logs for the correct time range have been collected.

**Comment by 7999** [comment]
a sock connect error

**Comment by 7999** [comment]
caused by a socket error
