### ISSUE TITLE
Did anyone used "mobile: expectNotification" command successfully for verification of notifications on iOS real devices?

### ISSUE THREAD

**Issue by ferozk** [appium/appium#18304]
I have tried following ways

`driver.execute(mobile: expectNotification, [{"name": "com.test.connect", "type":"plain", "timeoutSeconds": 60}])`
`driver.execute(mobile: expectNotification, [{"name": "You have new messages", "type":"plain", "timeoutSeconds": 60}])`
`driver.execute(mobile: expectNotification, [{"name": "TEST CONNECT", "type":"plain", "timeoutSeconds": 60}])`

Appium version v1.22.3
iOS version - 14.0
Xcode - 13.4.1
Node - v16.9.0

I could see the request in appium logs like this

> [debug] [W3C (f947969d)] Calling AppiumDriver.execute() with args: ["mobile: expectNotification",[{"name":"You have new messages","timeoutSeconds":30}],"f947969d-7510-436d-bbb8-c79677f5b63a"]
> [debug] [XCUITest] Executing command 'execute'
> [XCUITest] Proxying to WDA with an unknown route: POST /wda/expectNotification

Did anyone used this mobile script command successfully for verification of notifications on iOS real devices ?
Please share the example of working code

**Comment by mykola-mokhnach** [comment]
It looks like nobody here knows the answer. Please try asking at Appium forum
