### ISSUE TITLE
bug: Unable to select the value from the dropdown using Appium IOS Real Device

### ISSUE THREAD

**Issue by FWDQK** [appium/appium#18305]
I am trying to select a value from the dropdown but when I tried to inspect the element, dropdown objects not seen in the App Source.
It only shows the field on which we click and drop down gets open.
Object type is XCUIElementTypeOther
Appium is v2.0.0-beta.46

> Github shows it automatically every time a new issue is created

**Comment by FWDQK** [comment]
> Please fill out the issue report properly according to the given template

Please help to confirm from where to refer the template

**Comment by mykola-mokhnach** [comment]
Github shows it automatically every time a new issue is created
