### ISSUE TITLE
[Question] Automation android apps on a user build 

### ISSUE THREAD

**Issue by anunay1** [appium/appium#18314]
Hi Team,

I have a requirement to automate android apps on the production build which will have the developer options hidden? 
Can you please suggest and option to enable developer options for the production builds using Appium? 

@jlipps It will be a great help if you could respond?

**Comment by anunay1** [comment]
@mykola-mokhnach can you please help me with this?

**Comment by mykola-mokhnach** [comment]
Sorry, I don't understand the question

**Comment by anunay1** [comment]
For appium to work the mandatory condition is the developer option to be enabled, i am planning to have my night automation tests on a SW which will not have the developer options enabled by default after I flash the software to the device, how do I handle this kind of scenario with appium.

**Comment by mykola-mokhnach** [comment]
> mandatory condition is the developer option to be enabled

I still don't get what option we are talking about. Could you link to the official tutorial with such requirement?

**Comment by anunay1** [comment]
I am looking for the option below: ![Screenshot_2023-03-08-17-43-57-53_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://user-images.githubusercontent.com/7989610/223710754-34f6dd00-cfd8-4df0-900e-c7502fa20586.jpg)

If the software is newly flashed  to the device the developer option will not be available in the settings menu, to enable USB debugging I  have to go and tap on the build version 6 times.

**Comment by mykola-mokhnach** [comment]
I don't know any way to automate enablement of developer options. It would be a major security hole in Android OS if there was one.
The only possible way I see there would be to modify the firmware itself and flash a device with such prebaked snapshot.

**Comment by jlipps** [comment]
Yep, Appium provides no way to turn dev mode on for an Android device. It is a pre-requisite for Android automation via Appium. There might be other Android forums that discuss whether it is possible to do something like @mykola-mokhnach or use some other strategy.
