### ISSUE TITLE
bug: plugin list showing stderr debug messages when called with --json

### ISSUE THREAD

**Issue by vrunoa** [appium/appium#18311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When calling `plugin list` with  `--json` flag, debug messages are part of output:

i.e:
```
node packages/appium/index.js plugin list --installed --json 
dbug Support No package.json having current Appium dep in /Users/vrunoa/Projects/appium
dbug Support Using default APPIUM_HOME: /Users/vrunoa/.appium
dbug Support No package.json having current Appium dep in /Users/vrunoa/.appium
{
  "Boost": {
     "pkgNam
...
```

These debug messages are going to stderr so im able to avoid them from output by running
```
node packages/appium/index.js plugin list --installed --json 2>/dev/null
```

but it would be good to avoid this workaround and skip any debug message when using `--json` flag

### Expected Behavior

No debug messages when using `--json` flag

### Minimal Reproducible Example

```sh
node packages/appium/index.js plugin list --installed --json 
```

### Environment

- Operating system: **macOS Ventura Version 13.2.1**
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): **appium@2.0.0-beta.48**
  - Node.js version (output of `node --version`): **v16.16.0**
  - `npm` version (output of `npm --version`): **8.11.0**
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by boneskull** [comment]
so: ugh.

This is because of the order in which files are loaded, essentially.  

Appium's main entry point imports logsink which imports stuff from `@appium/support`, but `@appium/support` also imports its own `env`, which imports its own logger.  This logger is initialized before Appium's, and so regardless of what Appium does with the log level, that module in `@appium/support` will have something else.
