### ISSUE TITLE
bug: Android Streaming using mjpegServerPort is not working

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#18325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using _mjpegServerPort_ in my capabilities with unique port assigned. When the android tests are running if I access localhost:_mjpegServerPort_ I don't see the android screen and just keeps loading. 

Once the session is terminated I'm able to see the screen in the browser.

### Expected Behavior

Android screen should be streaming.

### Minimal Reproducible Example

Simple test with capability `"appium:mjpegServerPort": 62739`

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): Latest Beta - 55
  - Node.js version (output of `node --version`): v16.18.1
  - `npm` version (output of `npm --version`): 8.19.3
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): - uiautomator2@2.10.1 [installed (NPM)]
- Appium plugin(s) and their version(s):
- Platform and version under test: Android
- Real device or emulator/simulator: Both

### Link to Appium Logs

https://gist.github.com/saikrishna321/84513de4e9dc50aa4e0dab6603bcb3af

### Futher Information

During Test Execution

![Screenshot 2023-03-10 at 9 28 44 AM](https://user-images.githubusercontent.com/4045041/224221091-64c6e2a9-1376-462e-918e-0b53df58bea3.png)

Post Session

![Screenshot 2023-03-10 at 9 29 51 AM](https://user-images.githubusercontent.com/4045041/224221147-ce924089-6cd9-4e27-986a-9eaf50bddf1b.png)

**Comment by mykola-mokhnach** [comment]
> [debug] [ADB] Forwarding system: 62739 to device: 7810
> [debug] [ADB] Running '/Users/saikrishna/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward tcp:62739 tcp:7810'

I can observe that the port forwarding has been done properly, so no issues from the driver. Could you also attach the logcat output?

**Comment by saikrishna321** [comment]
@mykola-mokhnach Here is the adb logcat - https://gist.github.com/saikrishna321/84513de4e9dc50aa4e0dab6603bcb3af?permalink_comment_id=4497845#gistcomment-4497845

**Comment by mykola-mokhnach** [comment]
Are you sure this log is collected within the correct time range? I would expect to see "https://github.com/appium/appium-uiautomator2-server/blob/a800c9c94590174ded8f3da5b69e2bfa42eef207/app/src/main/java/io/appium/uiautomator2/server/mjpeg/MjpegScreenshotClient.java#L89" log traces there, but there are none

**Comment by saikrishna321** [comment]
@mykola-mokhnach Updated logs - https://gist.github.com/saikrishna321/84513de4e9dc50aa4e0dab6603bcb3af?permalink_comment_id=4497904#gistcomment-4497904

I can't find >> "https://github.com/appium/appium-uiautomator2-server/blob/a800c9c94590174ded8f3da5b69e2bfa42eef207/app/src/main/java/io/appium/uiautomator2/server/mjpeg/MjpegScreenshotClient.java#L89" in the adb logs

**Comment by saikrishna321** [comment]
@mykola-mokhnach I can see two open connections 

```
03-10 12:50:20.067  9099  9119 I appium  : Screenshot broadcast client opened a connection 127.0.0.1:33927
03-10 12:50:20.068  9099  9119 I appium  : Screenshot broadcast starting for 127.0.0.1:33927
03-10 12:50:20.069  9099  9119 I appium  : Screenshot broadcast client opened a connection 127.0.0.1:60955
``

**Comment by mykola-mokhnach** [comment]
This looks OK to me. Means the client has connected and got the starting data chunk. Now look for possible logged errors from https://github.com/appium/appium-uiautomator2-server/blob/master/app/src/main/java/io/appium/uiautomator2/server/mjpeg/MjpegScreenshotStream.java

Also verify the streaming data you get in the browser itself

**Comment by mykola-mokhnach** [comment]
I don't think there is anything more to do on this issue without the full logcat output. Shall I close the issue @saikrishna321 ?

**Comment by saikrishna321** [comment]
I looked into the adb logs and can't find any other error logs. Could be my machine issue. Will close for now and re-open if its the same on another machine

**Comment by meerkatriptide** [comment]
Hi @saikrishna321 , by any chance did you find a resolution for this issue? I am seeing exact same issue on a mac machine. Any input would be appreciated

**Comment by krishtoautomate** [comment]
this might provide hint to fix this issue: https://github.com/Genymobile/scrcpy/pull/4075/files
