### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure after upgrade to appium2 on xcode 14.2

### ISSUE THREAD

**Issue by LayMui** [appium/appium#18324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After I follow this link to use newer xcuitest driver with appium 2.

[Xcode 14 beta 3: Failed to build WDA as XCTAutomationSupport.framework/XCTAutomationSupport linking failure · Issue #17174 · appium/appium](https://github.com/appium/appium/issues/17174)

and build and install the WDA

cd ~/Desktop/WebDriverAgent-4.9.0
open WebDriverAgent.xcodeproj
at xcode 14.2 and build

and using the command 
 xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'platform=iOS Simulator,id=679FA46B-D348-4F4B-AF5E-C2E2821B309B'

when I run my automation code with webdriverio

I got this error
[0-2] 2023-03-09T07:38:27.850Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[0-2] xcodebuild error message:

### Expected Behavior

The automation should kick off as in previous appium version
in my package.json
I am using 
"appium": "^1.22.2",
"appium-doctor": "^1.16.0",

### Minimal Reproducible Example

NA

### Environment

- Operating system: macOS Ventura 13.2.1 
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - appium --version
2.0.0-beta.57

  - Node.js version (output of `node --version`):
  - node --version
v16.19.1

  - `npm` version (output of `npm --version`): 
  -  npm --version
8.19.3

  - Last `appium` version which did _not_ exhibit the problem: 
  - appium 1.22
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:
iOS Simulator: iPhone 14 Pro iOS 16.2

### Link to Appium Logs

https://gist.github.com/LayMui/9505c529cd70cef645ec96f07f9949d4949d4

**Comment by mykola-mokhnach** [comment]
The log link above is not accessible

**Comment by LayMui** [comment]
https://gist.github.com/LayMui/d2a624840ea37cb48e414aa11b47d50c

**Comment by mykola-mokhnach** [comment]
Unfortunately the above log in not a server one

**Comment by LayMui** [comment]
May I know where I can find the appium server log?

**Comment by mykola-mokhnach** [comment]
I don't know because it depends on how you manage the server startup itself. Consider using Appium forum to ask questions

**Comment by LayMui** [comment]
sure thanks @mykola-mokhnach
