### ISSUE TITLE
xcuitest: downgrade webdriverio

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18322]
wdio v8 does not claim compat with Node.js v14; though it may work now it is liable to break at any time.  Best to downgrade this to v7.x

cc @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
- wdio is a dev dependency, which means it won't break anything in prod
- node.js 14 support will end at April 30th 2023. By this date Appium can also freely drop supporting it
- downgrade might be a significant effort, which does not worth it assuming the above facts

**Comment by jlipps** [comment]
I'm with @mykola-mokhnach on this one. Good to know we can drop support for node 14 in just a matter of weeks!
