### ISSUE TITLE
bug: iOS app is being uninstalled on every launch of test, even if noReset=True and fullReset=False are set

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#18338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a regression that is seeing in the past latest versions of appium 2.0.0, currently I am seeing it with `2.0.0-beta.57` and with latest Appium plugins versions.

The problem is that each test I run the Appium server uninstalls the previous install of the iOS application.

### Expected Behavior

Application from previous run should remain on the device

### Minimal Reproducible Example

Run iOS application test twice. 

The second test run will uninstall the app before starting the test. 

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.57
  - Node.js version (output of `node --version`): v18.12.1
  - `npm` version (output of `npm --version`): 9.4.2
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator: **iOS 16.3.1**

### Link to Appium Logs

https://github.com/bwomsm1/AppiumLogs/blob/master/appium_uninstall.log

**Comment by bwomsm1** [comment]
@mykola-mokhnach can you please help with that issue? I think that I started seeing it since I upgraded to the latest Appium 2.0.0 beta and latest plugins versions. and with upgrading to latest iOS OS version/

Thanks!!!

**Comment by mykola-mokhnach** [comment]
This seems to be a valid bug. Please upgrade to 4.19.1+ and check if the issue is still relevant.

**Comment by bwomsm1** [comment]
Thanks @mykola-mokhnach for the response, 
upgrade what to `4.19.1+`? I am currently running with appium `2.0.0-beta.57`

**Comment by mykola-mokhnach** [comment]
> Thanks @mykola-mokhnach for the response,
> **upgrade what to `4.19.1+`?** I am currently running with appium `2.0.0-beta.57`

Upgrade appium-xcuitest-driver, of course

**Comment by bwomsm1** [comment]
> > Thanks @mykola-mokhnach for the response,
> > **upgrade what to `4.19.1+`?** I am currently running with appium `2.0.0-beta.57`
> 
> Upgrade appium-xcuitest-driver, of course

Thanks @mykola-mokhnach I can confirm that upgrading to xcuitest version `4.19.1` solved the issue.
We can close the issue from my side.
