### ISSUE TITLE
bug : Finding elements is taking more time on iOS 16.1 simulators using appium 2.0

### ISSUE THREAD

**Issue by jagadish970** [appium/appium#18330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently it is taking more time to find each element, this is happening especially with form fields

### Expected Behavior

Speeding up element finding

### Minimal Reproducible Example

WebElement element = getElement(accessId);
                   element.click();
                   element = getElement(accessId);
                   if(element.getAttribute("value")!=null)
                       element.clear();
                   if(!ctrl.value.equals("")) {
                       ((IOSElement) element).setValue(ctrl.value);

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):v2.0.0-beta.46
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 19.2
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by pratikshajb** [comment]
Hi @mykola-mokhnach 

These are the logs from Appium v1.22.2

[Element finding taking too long.pdf](https://github.com/appium/appium/files/10954478/Element.finding.taking.too.long.pdf)

**Comment by mykola-mokhnach** [comment]
Closed because of no response
