### ISSUE TITLE
bug: Appium crashing with OOM error

### ISSUE THREAD

**Issue by grant-mccarriagher** [appium/appium#18342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting some intermittent crashes with Appium. For context, we run one instance of Appium with 8 real iOS devices. We manage the WDA on each iOS device manually.

In the middle of our e2e runs (which run eight-threaded across all the phones), we're seeing Appium crash with OOM errors.

### Expected Behavior

Appium does not crash with an OOM error.

### Minimal Reproducible Example

I don't think I can provide a reproducible example here, let me know if I can provide more info to diagnose the issue.

### Environment

- Operating system: macOS 13.2.1
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.55 (also happening on the latest, 2.0.0-beta.57)
  - Node.js version (output of `node --version`): v16.13.2
  - `npm` version (output of `npm --version`):  8.1.2
  - Last `appium` version which did _not_ exhibit the problem: Unsure
- Appium driver(s) and their version(s): xcuitest 4.19.0
- Platform and version under test: iOS 16.3.1
- Real device or emulator/simulator: Real

### Link to Appium Logs

https://gist.github.com/grant-mccarriagher/7bc33e9a55d6ea8b4f14aff14adee551

### Futher Information

An important note: we have this same setup duplicated on two other Mac Minis without issue (same versions of Appium, xcuitest, macOS, node, etc). The only difference that I can see is that this Mac Mini is Apple Silicon (M2), and the other Mac Minis were Intel.

**Comment by mykola-mokhnach** [comment]
Try to increase the maximum memory size (--max-old-space-size) for the node process and see if that helps.

In order to investigate such issues we need a process memory dump when it is close to fail. Check https://marmelab.com/blog/2018/04/03/how-to-track-and-fix-memory-leak-with-nodejs.html for more details.

**Comment by grant-mccarriagher** [comment]
Increasing the max heap size seems to have worked here. Thanks!

**Comment by mykola-mokhnach** [comment]
It would still be helpful for us if you could provide the heap snapshot. Perhaps, there is still some data structure that is leaking.
