### ISSUE TITLE
Bug: iOS + XCUITest - Unexpected navigation to static pages

### ISSUE THREAD

**Issue by VladimirPodolyan** [appium/appium#18354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm automating web application on iOS + XCUITest with real device and simulators. Right now, after some manipulation of the screenshots on the test page, the driver unexpectedly navigates to the static pages "about:blank"/"data:text/html" (line 2431 in gist with logs)

### Expected Behavior

I don't expect some navigations from test page without such code

### Minimal Reproducible Example

Can't reproduce on test environment

### Environment

- Operating system: MacOS 12.3.1
- If running via `appium` CLI...
  - Appium CLI version: 1.22.3 & 2.0.0-beta.56
  - Node.js version: v16.19.1
  - `npm` version: 8.19.3
  - Last `appium` version which did _not_ exhibit the problem: faced recently
- Appium driver(s): xcuitest@4.19.1
- Appium plugin(s): - 
- Real device or emulator/simulator: iphone xr real device 15.4 / iphone 12 mini simulator 15.5

### Link to Appium Logs

[logs](https://gist.github.com/VladimirPodolyan/57228a5861e6546c285faffb92410c10)

### Futher Information

This page is unique, that it can automatically provide alert with asking of permissions to camera and mic. In described test there is no any alert, but in the logs I have NoSuchAlertError error. It might be unrelated because of main issue in unexpected redirect

**Comment by jlipps** [comment]
I don't see anything in the logs that indicates Appium has caused this redirect. It is merely cataloguing the redirect that has happened, and adjusting the internal URL tracking to suit. If you open up this page in a simulator and attach to it via the Safari debugger, does it eventually redirect in that context outside of Appium as well?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
