### ISSUE TITLE
appium: remove longjohn dependency

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18357]
[longjohn](https://npm.im/longjohn) is a lib which enables "longer stack traces".

I'm not sure why we need longer stack traces in the first place?  This lib mutates Node.js globals and builtins liberally, and contains this code:

```js
  if (process.env.NODE_ENV === 'production') {
    console.warn('NOTICE: Longjohn is known to cause CPU usage due to its extensive data collection during runtime.\nIt generally should not be used in production applications.');
  }
```

While I'm under no illusions that removing this will give us any sort of notable performance boost, it smells and I'd like to remove it.

cc @jlipps @mykola-mokhnach

**Comment by boneskull** [comment]
if we _do_ want something special with stack traces, there are other ways to shear that sheep

**Comment by mykola-mokhnach** [comment]
yep, I agree. Perhaps, it made sense for earlier Node.js versions, where async stack traces were quite shallow.

**Comment by jlipps** [comment]
yep, let's get rid of it.
