### ISSUE TITLE
Appium does not work after installing driver

### ISSUE THREAD

**Issue by MonoRight** [appium/appium#18356]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

I just started to use appium and the problem with installation appeared:

I downloaded appium@next using npm. I tried to check the version 'appium -v' and there was result: 2.0.0-beta.57. I tried to start appium server using 'appium' command and it started, but without any driver. When I downloaded driver using 'appium driver install uiautomator2' it was successfully downloaded, but after that, I tried to check the version of appium once again and I had such a problem: 
![image](https://user-images.githubusercontent.com/55757671/225664006-bdb0efff-79ed-4ee7-be84-14c034160992.png)

Full trace:
C:\Users\d.parkhomenko>appium -v

C:\Users\d.parkhomenko\AppData\Roaming\npm\node_modules\appium\lib\config.js:14
const MIN_NODE_VERSION = ENGINES.node;
                                 ^
TypeError: Cannot read properties of undefined (reading 'node')
    at Object.<anonymous> (C:\Users\d.parkhomenko\AppData\Roaming\npm\node_modules\appium\lib\config.js:14:34)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Function.Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (C:\Users\d.parkhomenko\AppData\Roaming\npm\node_modules\appium\lib\appium.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Function.Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (C:\Users\d.parkhomenko\AppData\Roaming\npm\node_modules\appium\lib\main.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)

I can't use 'appium' command anymore. I can't look at the list of drivers, versions and etc.

I tried to parse the problem and found config.js file, as I understand variable 'ENGINE' is undefined, so package.json does not contain object "engines" with properties "node" and "npm", so I just added it in package.json with path C:\Users\<MYUSER>\AppData\Roaming\npm\node_modules\appium\build\lib\package.json
![image](https://user-images.githubusercontent.com/55757671/225664635-e3d43a1e-d7ce-43a3-ac85-20eb5ff62911.png)

New look of package.json:

![image](https://user-images.githubusercontent.com/55757671/225665745-a6b9d6c6-7bac-4f85-9fb5-73113fc2467a.png)

After that I tried to check driver list by 'appium driver list':
![image](https://user-images.githubusercontent.com/55757671/225666174-7d8a93b8-5b97-47fc-86fd-c98af461f10d.png)

It works and does not even drops as prevoius time, but new WARN message appeared: 

WARN Appium Appium encountered 1 warning while validating drivers found in manifest C:\Users\d.parkhomenko\AppData\Roaming\npm\node_modules\appium\build\lib\node_modules\.cache\appium\extensions.yaml
WARN Appium Driver "uiautomator2" has 1 potential problem:
WARN Appium   - Driver "uiautomator2" (package `appium-uiautomator2-driver`) may be incompatible with the current version of Appium (v) due to its peer dependency on older Appium v^2.0.0-beta.40. Please ask the developer of `appium-uiautomator2-driver` to update the peer dependency on Appium to v.

When I try to start appium, it starts, but the same message is presented:
![image](https://user-images.githubusercontent.com/55757671/225666880-0f35c255-26f5-4ee9-8e48-d67155d2f7e4.png)

I tried with different versions of appium, nodejs, npm and appium drivers, but it does not work correctly.

### Expected Behavior

After installation appium and appium driver, appium server starts without exceptions

### Minimal Reproducible Example

1) install nodejs (latest version)
2) install appium: npm i -g appium@next
3) check the version of appium: appium -v
4) install driver: appium driver install uiautomator
5) check the version of appium once again
6) exception of config.js is presented

### Environment

- Operating system: Windows 10
- If running via `appium` 
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.57
  - Node.js version (output of `node --version`): v19.7.0
  - `npm` version (output of `npm --version`): 9.6.2
  - uiautomator2 version (output of 'appium driver list'): 2.12.6

**Comment by jlipps** [comment]
hmm i can't repro on macos. @boneskull can you?

**Comment by mykola-mokhnach** [comment]
It is expected that appium is installed globally (e.g. `npm i --global appium@next`)

**Comment by mykola-mokhnach** [comment]
Maybe try to downgrade node to the LTS release (v18)?

**Comment by mykola-mokhnach** [comment]
I'm not quite sure why do you have package.json inside appium/build dir. There should be only one package manifest and it should be located in the module root (e.g. appium/) and it is also not supposed to have uia2 driver as dev dependency as on the screenshot above. The server and drivers are installed separately, so driver could use the server package as peer dependency

**Comment by MonoRight** [comment]
Yeah, I have package.json in the module root:
![image](https://user-images.githubusercontent.com/55757671/226325643-a0068ecd-b213-4130-b366-4bb58ed6f90d.png)

And the content includes 'engines':
![image](https://user-images.githubusercontent.com/55757671/226326031-b04305e6-02a1-4154-8197-87121fcd8450.png)


But I just installed the server and it worked, and after installing any driver (seperately) using the command "appium driver install [driver]" the exception always appears. If exploring the message of exception, it tries to search property 'engines' in package.json that is not in the root folder... it's kinda strange because package.json includes this property...

**Comment by mykola-mokhnach** [comment]
what is you working folder while the `appium driver install` command is being executed? Make sure it's not the same folder where the server is installed.

**Comment by MonoRight** [comment]
Working folder: C:\Users\[MY_USER]

**Comment by mykola-mokhnach** [comment]
maybe try from the root (`c:\`) 

Also try to fully reinstall the server (e.g. delete appium server plus the content of `.appium` folder)

**Comment by MonoRight** [comment]
By the way, I do not have .appium folder in C:\Users\[MY_USER]. Two weeks ago I deleted it while reinstalling appium. After reinstallation several times this folder was not created. 

It works! No more exceptions about 'ENGINES === undefined'.
![image](https://user-images.githubusercontent.com/55757671/226415312-26883e96-2a4a-4140-a002-3a7051624c93.png)

 I need to test it

**Comment by MonoRight** [comment]
So, I found the problem why did this happen. I have testing framework where I need to find the path to appium, so there was added global variable APPIUM_HOME (like JAVA_HOME but to appium). And after starting test, appium tries to search driver in another folder and does not find it. Test failed -> appium message is about "no driver", but it was installed before. After another try it fails on the step of starting server (underfined (reading 'node')). 

I reinstalled appium, deleted all variables (global and local for user APPIUM_HOME), deleted pathes from PATH and it worked
I still dont understand why variables blocked this process, I just hardcoded this path to appium folder in this framework.

If you faced with such problem try this solution, but dont forget to reopen your cmd and IDE after deleting variables APPIUM_HOME, because it saves last

**Comment by jlipps** [comment]
`APPIUM_HOME` is not designed to point to the path to where Appium itself lives. Rather it is the path where Appium is free to manage its own extensions. Therefore it is not analogous to `JAVA_HOME`. `JAVA_HOME` exists to help other tools find out where Java lives. `APPIUM_HOME` exists to let Appium know where it can install things on your filesystem.
