### ISSUE TITLE
Error: An unknown server-side error, Unable to rotate device 

### ISSUE THREAD

**Issue by Tzachc** [appium/appium#18367]
Hello,
I'm trying to rotate device from Portrait to LANDSCAPE on emulator while automation test is running and I'm getting Unable to rotate device exception.
Manually I can rotate on the emulator but when execute:
driver.orientation = "LANDSCAPE", I'm getting:

![image](https://user-images.githubusercontent.com/57837594/226302031-ac17e3de-591a-4f9c-8c80-d5aaaf2ca05e.png)

I'm using Appium 1.22.3.
IOS emulator: iPhone 12
MacOS 12.2.

would like for suggestions,
Thanks.

**Comment by mykola-mokhnach** [comment]
- Appium 1 is not supported anymore, consider switching to Appium 2
- Please provide the full server log
- Is the device rotatable with the particular view being active on phone screen when the rotation api is invoked?

**Comment by Tzachc** [comment]
@KazuCocoa Is it true that python client doesn't support rotate?

![image](https://user-images.githubusercontent.com/57837594/226375635-6a4641da-c07b-468e-b00d-b7ad7f8f36f6.png)

**Comment by KazuCocoa** [comment]
You should use orientation:
https://appium.io/docs/en/commands/session/orientation/set-orientation/
https://github.com/appium/python-client/blob/cbcc539827658c7aaa16147f8da7907405c59031/appium/webdriver/webdriver.py#L472-L496

The error itself not client level. The device itself maybe had an issue to change the rotation via Android API. The previous Mykola's comment is proper one to check more about possible reasons.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
