### ISSUE TITLE
bug:  No Chromedriver found that can automate Chrome error on MacOS - Appium 2

### ISSUE THREAD

**Issue by erolstt** [appium/appium#18368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am getting this error when I try to run a test on Android Simulator

```Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '109.0.5414'. You could also try to enable automated chromedrivers download as a possible workaround.```

I did try the possible workaround but still getting the same issue. Also, I checked if the driver exists and it does exist `chromedriver_mac64_v109.0.5414.25 ` under `.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac`

I also tried to provide the `chromedriberExecutableDIr` option and install the driver locally but got exactly the same error.
`'appium:chromedriverExecutableDir': '/Users/eselitektay/Downloads/chd'`

I am using webdriverio version 8.3.8. The same test works on Iphone Simulator using XCUITest driver.

Android simulator that I am using has 33 API version (UpsideDownCake)

### Expected Behavior

Appium 2 should be able to use the existing chromedriver.

### Minimal Reproducible Example

webdriverio capabilities:
```        
platformName: 'Android',
        browserName: 'chrome',
        maxInstances: 1,
        'appium:deviceName': process.env.androidDeviceName,
        'appium:orientation': 'PORTRAIT',
        'appium:automationName': 'uiautomator2',
        'appium:newCommandTimeout': 240
```

### Environment

- Operating system:  macOS Ventura Version 13.2.1 (22D68)
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.57
  - Node.js version (output of `node --version`): v18.15.0
  - `npm` version (output of `npm --version`): 9.5.0
 - uiautomator2@2.12.6 [installed (NPM)]

### Link to Appium Logs

[appium.log](https://github.com/appium/appium/files/11039463/appium.log)

### Futher Information

Full appium logs
```[Chromedriver@e786] No Chromedriver found that can automate Chrome '109.0.5414'. You could also try to enable automated chromedrivers download as a possible workaround.
[debug] [AndroidUiautomator2Driver@5aad (3ef5280d)] Deleting UiAutomator2 session
[debug] [AndroidUiautomator2Driver@5aad (3ef5280d)] Deleting UiAutomator2 server session
[debug] [AndroidUiautomator2Driver@5aad (3ef5280d)] Matched '/' to command name 'deleteSession'
[debug] [AndroidUiautomator2Driver@5aad (3ef5280d)] Proxying [DELETE /] to [DELETE http://127.0.0.1:8200/session/a7505e49-3048-40ff-889d-0a5bd91266f8] with no body
[debug] [AndroidUiautomator2Driver@5aad (3ef5280d)] Got response with status 200: {"sessionId":"a7505e49-3048-40ff-889d-0a5bd91266f8","value":null}
[debug] [ADB] Running '/Users/eselitektay/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200 
[debug] [ADB] Running '/Users/eselitektay/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 forward --remove tcp:8200'
[AndroidUiautomator2Driver@5aad (3ef5280d)] Restoring hidden api policy to the device default configuration
[debug] [ADB] Running '/Users/eselitektay/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [Instrumentation] .
[debug] [Instrumentation] Time: 3.067
[debug] [Instrumentation] 
[debug] [Instrumentation] OK (1 test)
[debug] [Instrumentation] The process has exited with code 0
[debug] [AppiumDriver@13c9] Event 'newSessionStarted' logged at 1679321300170 (14:08:20 GMT+0000 (Greenwich Mean Time))
[debug] [AppiumDriver@13c9] Encountered internal error running command: Error: No Chromedriver found that can automate Chrome '109.0.5414'. You could also try to enable automated chromedrivers download as a possible workaround.
[debug] [AppiumDriver@13c9]     at Object.wrappedLogger.errorAndThrow (/Users/eselitektay/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/lib/logging.js:115:34)
[debug] [AppiumDriver@13c9]     at Chromedriver.start (/Users/eselitektay/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:659:16)
[debug] [AppiumDriver@13c9]     at AndroidUiautomator2Driver.setupNewChromedriver (/Users/eselitektay/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:471:3)
[debug] [AppiumDriver@13c9]     at AndroidUiautomator2Driver.startChromeSession (/Users/eselitektay/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context.js:324:23)
[debug] [AppiumDriver@13c9]     at AndroidUiautomator2Driver.startUiAutomator2Session (/Users/eselitektay/.appium/node_modules/appium-uiautomator2-driver/lib/driver.js:440:7)
[debug] [AppiumDriver@13c9]     at AndroidUiautomator2Driver.createSession (/Users/eselitektay/.appium/node_modules/appium-uiautomator2-driver/lib/driver.js:240:7)
[debug] [AppiumDriver@13c9]     at AppiumDriver.createSession (/Users/eselitektay/.nvm/versions/node/v18.15.0/lib/node_modules/appium/lib/appium.js:349:35)```

**Comment by KazuCocoa** [comment]
Please provide the full appium log

**Comment by erolstt** [comment]
Hi @KazuCocoa , I updated the issue and added the full appium logs.
Thank you,

**Comment by KazuCocoa** [comment]
The attached log was v74.0.3729. Was your env M1/2 mac, or intel?

**Comment by erolstt** [comment]
Hi @KazuCocoa , yes the log was v74.0.3729. I was trying with a different version of chrome but was getting the same error. My env is macOS Ventura 13.2.1 Intel i7.

**Comment by KazuCocoa** [comment]
Thanks.

> You could also try to enable automated chromedrivers download as a possible workaround.

Did you try out `appium server --allow-insecure chromedriver_autodownload` for v111?
https://github.com/appium/appium-uiautomator2-driver/#automatic-discovery-of-compatible-chromedriver


Your attached log had errors below. I wonder something was weird about running chromedriver on the env. I'll try the functionlity on my local later.
> Cannot parse the version string

**Comment by mykola-mokhnach** [comment]
> 2023-03-22 09:58:48:401 [Chromedriver@8c03] Cannot retrieve version number from 'chromedriver_mac64_v99.0.4844.51' Chromedriver binary. Make sure it returns a valid version string in response to '--version' command line argument. Cannot parse the version string

It looks like downloaded chromedrivers cannot be executed or they are damaged. Try to manually run the downloaded /Users/eselitektay/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v74.0.3729.6/chromedriver binary with `--version` argument to check why it cannot be executed

**Comment by KazuCocoa** [comment]
I saw the same error, ` Make sure it returns a valid version string in response to '--version' command line argument. Cannot parse the version string`, when appium download chromedrivers. The next new session request worked without issue. Maybe something is broken..?

The output of `--version` was below. Hm..

```
kazu $ /Users/kazuaki/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v112.0.5615.28 --version
ChromeDriver 112.0.5615.28 (e01c41304994a51cedfb5f0fac134687ba993bfb-refs/branch-heads/5615@{#494})
kazu $kazu $ /Users/kazuaki/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v112.0.5615.28 --version
ChromeDriver 112.0.5615.28 (e01c41304994a51cedfb5f0fac134687ba993bfb-refs/branch-heads/5615@{#494})
```

**Comment by KazuCocoa** [comment]
It seems like https://github.com/appium/appium-chromedriver/pull/291 fixed this issue

**Comment by KazuCocoa** [comment]
Can you try UIA2 v2.12.7 out?

**Comment by erolstt** [comment]
Hi @KazuCocoa , I got the  uiautomator2@2.12.7 version and ran my tests again. Now it works. I don't get any errors and am able to see older versions of chrome lunching. Closing the issue. I appreciate your help!

**Comment by VinitaPatil11** [comment]
Running the command **appium server --allow-insecure chromedriver_autodownload** worked for me. Thanks!!

**Comment by crazyones110** [comment]
As of appium 3.x, you have to use `appium server --allow-insecure uiautomator2:chromedriver_autodownload` or `appium server --allow-insecure *:chromedriver_autodownload`
