### ISSUE TITLE
bug: Appium unable to find iOS elements after switched to Swift UI

### ISSUE THREAD

**Issue by JonathonFord** [appium/appium#18376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After a UI update I tried to run my tests to make sure no ID's were changed, but I found that nothing on the page could be interacted with (including thigs that experienced no change, and that have the same ID). When I went to appium inspector (assuming that the ID's/tags changed at first) and navigated to the page with the updates, Appium inspector could not load the source tree and was caught in an infinite loop. 

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/111521482/226639314-e7e3a1f6-3dbe-4d7c-b45d-d6c9e0d8afea.png)

### Expected Behavior

Expected result is you go to the app and elements can be found

### Minimal Reproducible Example

I was reluctant to write this bug, but was told by my devs that I should. I cannot share the app that this issue is appearing. And we have not been able to recreate the issue with test apps that do a similar thing with SwiftUI elements appearing inside a UIKit frame. But I wanted to document the issue in case others are running into it because I have not found anything similar online

### Environment

- Operating system: Windows
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): 1.21.0
- Appium plugin(s) and their version(s): 1.21.0
- Platform and version under test: iOS 15
- Real device or emulator/simulator: Iphone 13 pro max

**Comment by mykola-mokhnach** [comment]
Appium 1 is not maintained anymore. Please use xcuitest driver available in Appium 2. Also, provide the full server log

**Comment by mykola-mokhnach** [comment]
Closed because of no response
