### ISSUE TITLE
uiAutomator2 won't activate app from the background

### ISSUE THREAD

**Issue by DmytroChuchmaiBarges** [appium/appium#18375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After sending app to background I query the app state, it states '3'
When I try to activate an app, it just launches it from scratch.

Note: After fresh-installing an appUnderTest, and manually doing actions, it works as expected, after running an appium test, the issue starts to occur. Could be related to the activity flags that appium sets for appUnderTest.

### Expected Behavior

App state should recover, same as I would do it manually:
- after launching app from app manager
- after launching an app by clicking the dashboard icon.

### Minimal Reproducible Example

driver.background(-1);

driver.activateApp(appPackage);
or driver.execute('mobile:activateApp'{appId: appPackage});

### Environment

- Operating system:
  - Appium CLI 2.0.0-beta.55
  - Node.js 16
  - `npm` 9.4.2
  - Last `1.22` version which did _not_ exhibit the problem: 
- mac m2
- uiautomator2 (2.12.6)
- Real device Android 8

**Comment by amedvedjev** [comment]
what if try `runInBackground(1)` ?

**Comment by mykola-mokhnach** [comment]
UIA2 driver is not very advanced about activating apps. It is just trying to figure out what app's launchable activity name is and starts it when found. If the app needs another activity launched in order to be restored to the particular state then consider providing its name manually using [mobile: startActivity](https://github.com/appium/appium-uiautomator2-driver#mobile-startactivity) extension

**Comment by DmytroChuchmaiBarges** [comment]
> when

When I tried starting activity other than the appActivity in my capabilities, it thrown some permission errors, 

Also, as it was working in appium 1.22 uiautomator2 this seams a kind of regression.

I also tried setting appium:intentFlags capability to '0x00020000' which corresponds to FLAG_ACTIVITY_REORDER_TO_FRONT
And also '131072', but still no effect.
Seams strange that the appUnderTest works ok until I run appium at least once. After that, such behaviour occur and only re-installing the app helps.

**Comment by mykola-mokhnach** [comment]
It looks it only happens to this particular app. Try to add more logs there to figure out what does not work as expected. I don't think we can help much without detailed cause description.

**Comment by DmytroChuchmaiBarges** [comment]
> what if try `runInBackground(1)` again ?

I tried, the app did not activate at all.

**Comment by DmytroChuchmaiBarges** [comment]
found a workaround by sending 
'keycode 187' 2 times sequentially.

**Comment by KazuCocoa** [comment]
activate_app command launches a launchable activity as the apk's Manifest by getting it from `shell cmd package resolve-activity`, so it could be different from your desired one at this time. (Perhaps you'd like to start not launchable specified activity)

If you need to start different activity firectly, https://github.com/appium/appium-uiautomator2-driver#mobile-startactivity helps. The command is for it.
Your security issue is related to https://stackoverflow.com/questions/49471423/android-manifests-androidexported-false-prevents-app-from-running-on-device . Maybe the activity does not allow to start directly.

The app switch could be a workaround as you commented.
https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_APP_SWITCH

**Comment by mykola-mokhnach** [comment]
> [debug] [38;5;32m[AndroidUiautomator2Driver@cf25 (db97f8a2)][0m Calling AppiumDriver.activateApp() with args: ["co.package2.android.staging_new",null,null,null,"db97f8a2-0e78-497c-bbdf-61a2b7aa7509"]
> [debug] [38;5;32m[AndroidUiautomator2Driver@cf25 (db97f8a2)][0m Activating 'co.package2.android.staging_new'
> [debug] [38;5;48m[ADB][0m Running '/Users/JohnDoe/Library/Android/sdk/platform-tools/adb -P 5037 -s 2de6f58a shell cmd package resolve-activity --brief co.package2.android.staging_new'
> [debug] [38;5;48m[ADB][0m Running '/Users/JohnDoe/Library/Android/sdk/platform-tools/adb -P 5037 -s 2de6f58a shell am start-activity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n co.package2.android.staging_new/co.package1.android.splash.SplashActivity'
> [debug] [38;5;32m[AndroidUiautomator2Driver@cf25 (db97f8a2)][0m Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=co.package2.android.staging_new/co.package1.android.splash.SplashActivity }

I don't observe any issues there. The driver works as expected - it resolves the launchable activity and runs it. Consider passing custom activity names if you need to change this behavior as mentioned above.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
