### ISSUE TITLE
unable to launch Web Driver Agen Runnner when phone is kept in Air Plane Mode. 

### ISSUE THREAD

**Issue by AlbertSimonAppium** [appium/appium#18381]
Hi, I am not able to launch the WDA when the Airplane mode is enabled in my iphone. 

WDA launches when the Airplane mode is turned OFF.. 

Do we have any way to start WDA when Airplane mode is ON? .. I need this to test some scenarios like Turning Airplane mode ON, Turning Airplane mode OFF, etc. 

Appium Version - 1.21
xcode - xcode 13
ios - 15.6.1

Please advise.

**Comment by mykola-mokhnach** [comment]
This does not depend on xcuitest driver, but rather xcodebuild (e.g. if the latter cannot start a test then we fail as well). Consider reporting your issue to Apple.
