### ISSUE TITLE
[Feat]: Pin dependencies to SemVer major

### ISSUE THREAD

**Issue by eps1lon** [appium/appium#18385]
**Is your feature request related to a problem? Please describe.**
Installing Appium in a monorepo adds a lot of additional dependencies that can't be deduplicated

**Describe the solution you'd like**
Relax version pinning. Ideall to SemVer Major i.e. `^`

**Describe alternatives you've considered**
Adding resolutions but it's unclear if these are always supported and with a growing dependency tree it will be hard to maintain these list since we just want to force the version ranges for Appium dependencies.

**Additional context**
Not at the moment

**Comment by boneskull** [comment]
You can attempt to override the dependencies using [overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json?v=true#overrides), but pinning our dependencies and running automated updates via Renovate provides the most suitable balance of flexibility and stability for Appium. 

I'm unsure what you mean by "installing Appium in a monorepo" and what is uniquely problematic about this setup?

**Comment by eps1lon** [comment]
Adding resolutions is not a sollution for everybody. It spreads the work to every dependent who needs to be aware of this issue. If you recommend to add resolutions/overrides, why not relax to minor or major to begin with?

If every package pins their dependencies to patches the dependency tree will be huge the more packages you use. The number of used packages is especially big in a monorepo.

Can you explain how pinning to patches helps stability? NPM relies on SemVer to provide that stability. Only packages not following SemVer should be pinned. But I don't think that applies to evey dependency you have. E.g. Babel follows SemVer so there is no reason to pin that.

Can you give me a concrete example when pinning prevented a bug?

**Comment by jlipps** [comment]
https://docs.renovatebot.com/dependency-pinning/ is a good overview of the issues at play.

We have indeed had issues in the past where broken packages within semver ranges have caused issues that were difficult to track down due to differing versions of dependencies in different installs.

There are definitely tradeoffs to this issue. Appium is primarily used as an end-user CLI tool, not a dep in other projects, which is one factor that weighed in favour of pinning deps. At any rate, the Appium team decided to go with pinning deps some time ago after a lot of discussion, and that's what we're likely to continue doing for the foreseeable future.

**Comment by levibuzolic** [comment]
Would it be possible to revisit this discussion?

In our experience using Appium across several large-scale projects, we've consistently encountered issues that require manual intervention to address CVEs. This has become a recurring pain point.

The Renovate documentation linked in this thread is now over seven years old, and much of the guidance reflects practices that were more relevant in 2018. Today, lockfiles are standard across all major JavaScript package managers and are the recommended approach for managing fine-grained package pinning.

While I understand that semver operators may not be appropriate for every dependency—especially those that don't adhere strictly to semantic versioning—they generally work well for the vast majority of packages. For the few problematic ones, using stricter version ranges or pinning specific versions is a reasonable exception.

Thanks for considering this, and I’d be happy to help if further input is needed.
