### ISSUE TITLE
Commands are executed slow on the iOS after "Connecting" loader in app

### ISSUE THREAD

**Issue by VadimGlibovi4** [appium/appium#18406]
Hello, please help to clarify. When I run iOS tests we have issue with visible of elements ( I see "Connecting" loader in app and after that commands are executed really slow, on android the same suite works well). This issue always reproduce. 

For research I tried to:

- Update Appium version to 2
- Change sim to real device
- Use different devices and iOS versions 

If I use appium inspector, there is no problems with visible of elements (Loader is not shown and we can find any elements). 
-
Extra info:
Same behaviour I can see, when I turn on airplane mode (No internet connection, and loader) and commands also executed really slow. This behaviour reproduce only for iOS (simulator and real device), on android loader is not affect commands and tests works well.
-
Files:

Appium Logs: https://gist.github.com/VadimGlibovi4/b980657c24a0906727af92f8661a703a
Page Source: https://gist.github.com/VadimGlibovi4/46c650891c3ec18047cd29331baf1e3c

**Comment by mykola-mokhnach** [comment]
Elements lookup is controlled by xctest. We cannot do much about it, especially if you use non-xpath locators. Usually the main reason of the slowness is the fact that the app under test is blocking the main events loop. A possible workaround for it might be to customise `waitForIdleTimeout` and/or `animationCoolOffTimeout` [settings](https://appium.github.io/appium-xcuitest-driver/4.19/settings/). Generally, check the app under test with its developer and make sure it is idling long enough (e.g. no infinite background animations are running)

**Comment by amedvedjev** [comment]
@mykola-mokhnach 
```
Appium v2.0.0-beta.53 creating new XCUITestDriver (v4.16.11)
....
2023-03-28 08:00:14:928 - [XCUITestDriver@dd9c] The following capabilities were provided, but are not recognized by Appium:
2023-03-28 08:00:14:929 - [XCUITestDriver@dd9c]   animationCoolOffTimeout
2023-03-28 08:00:14:929 - [XCUITestDriver@dd9c]   sendKeyStrategy
2023-03-28 08:00:14:929 - [XCUITestDriver@dd9c]   snapshotMaxDepth
2023-03-28 08:00:14:929 - [XCUITestDriver@dd9c]   tapWithShortPressDuration
2023-03-28 08:00:14:929 - [XCUITestDriver@dd9c]   waitForAppScript
```

just wonder docs outdated or ?

**Comment by mykola-mokhnach** [comment]
these are settings, not capabilities, so the message above makes sense

**Comment by amedvedjev** [comment]
thanks @mykola-mokhnach 

still left remove from caps docs
```
IOSMobileCapabilityType.SEND_KEY_STRATEGY
IOSMobileCapabilityType.TAP_WITH_SHORT_PRESS_DURATION
IOSMobileCapabilityType.WAIT_FOR_APP_SCRIPT
```

**Comment by VadimGlibovi4** [comment]
@mykola-mokhnach thanks, tests works well after update settings
