### ISSUE TITLE
Unable to get a available drivers list 

### ISSUE THREAD

**Issue by iniyavans** [appium/appium#18412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'll using a latest appium version and I'll execute a sudo appium --list-drivers comment

### Expected Behavior

usage: /usr/local/bin/appium [-h] [--shell] [--allow-cors] [--reboot]
                             [--ipa IPA] [-a ADDRESS] [-p PORT] [-pa BASEPATH]
                             [-ka KEEPALIVETIMEOUT] [-ca CALLBACKADDRESS]
                             [-cp CALLBACKPORT] [-bp BOOTSTRAPPORT]
                             [-r BACKENDRETRIES] [--session-override] [-l]
                             [-g LOGFILE]
                             [--log-level {info,info:debug,info:info,info:warn,info:error,warn,warn:debug,warn:info,warn:warn,warn:error,error,error:debug,error:info,error:warn,error:error,debug,debug:debug,debug:info,debug:warn,debug:error}]
                             [--log-timestamp] [--local-timezone]
                             [--log-no-colors] [-G WEBHOOK] [--safari]
                             [--default-device] [--force-iphone]
                             [--force-ipad]
                             [--tracetemplate AUTOMATIONTRACETEMPLATEPATH]
                             [--instruments INSTRUMENTSPATH]
                             [--nodeconfig NODECONFIG] [-ra ROBOTADDRESS]
                             [-rp ROBOTPORT]
                             [--chromedriver-executable CHROMEDRIVEREXECUTABLE]
                             [--show-config] [--no-perms-check]
                             [--strict-caps] [--isolate-sim-device]
                             [--tmp TMPDIR] [--trace-dir TRACEDIR]
                             [--debug-log-spacing]
                             [--suppress-adb-kill-server] [--long-stacktrace]
                             [--webkit-debug-proxy-port WEBKITDEBUGPROXYPORT]
                             [--webdriveragent-port WDALOCALPORT]
                             [-dc DEFAULTCAPABILITIES] [--relaxed-security]
                             [--allow-insecure ALLOWINSECURE]
                             [--deny-insecure DENYINSECURE]
                             [--command-timeout DEFAULTCOMMANDTIMEOUT] [-k]
                             [--platform-name PLATFORMNAME]
                             [--platform-version PLATFORMVERSION]
                             [--automation-name AUTOMATIONNAME]
                             [--device-name DEVICENAME]
                             [--browser-name BROWSERNAME] [--app APP]
                             [-lt LAUNCHTIMEOUT] [--language LANGUAGE]
                             [--locale LOCALE] [-U UDID]
                             [--orientation ORIENTATION] [--no-reset]
                             [--full-reset] [--app-pkg APPPACKAGE]
                             [--app-activity APPACTIVITY]
                             [--app-wait-package APPWAITPACKAGE]
                             [--app-wait-activity APPWAITACTIVITY]
                             [--device-ready-timeout DEVICEREADYTIMEOUT]
                             [--android-coverage ANDROIDCOVERAGE] [--avd AVD]
                             [--avd-args AVDARGS] [--use-keystore]
                             [--keystore-path KEYSTOREPATH]
                             [--keystore-password KEYSTOREPASSWORD]
                             [--key-alias KEYALIAS]
                             [--key-password KEYPASSWORD]
                             [--intent-action INTENTACTION]
                             [--intent-category INTENTCATEGORY]
                             [--intent-flags INTENTFLAGS]
                             [--intent-args OPTIONALINTENTARGUMENTS]
                             [--dont-stop-app-on-reset]
                             [--calendar-format CALENDARFORMAT]
                             [--native-instruments-lib] [--keep-keychains]
                             [--localizable-strings-dir LOCALIZABLESTRINGSDIR]
                             [--show-ios-log] [--async-trace]
                             [--chromedriver-port CHROMEDRIVERPORT]
                             [--log-filters LOGFILTERS] [-v]
/usr/local/bin/appium: error: unrecognized arguments: --list-drivers

### Minimal Reproducible Example

/usr/local/bin/appium: error: unrecognized arguments: --list-drivers

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
It seems like you still have Appium 1 installed. Make sure you follow the readme: https://github.com/appium/appium#server

**Comment by jlipps** [comment]
also, there is no flag/command called `--list-drivers`, not sure where you saw that
