### ISSUE TITLE
support: deprecate AppiumLogger.errorAndThrow()

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18414]
`AppiumLogger.errorAndThrow()` (see https://github.com/appium/appium/blob/master/packages/support/lib/logging.js#L112-L124)  is a function which--as you would expect--writes an "error"-level message to the log, then subsequently throws a new `Error` with the same message.

This method is problematic vis-a-vis types because it never returns.  TS has limited understanding of this method.  The method returns a value of type `never`, but **TS cannot infer that a _call_ to the function acts the same as a `throw` keyword** (there have likely been countless feature requests raised about this in TS, but I don't know about any future plans here).  

This means there almost certainly be type errors when using the method, because while _you_ know execution will not continue, TS won't.  If method `x` is supposed to return `T`, but `errorAndThrow()` is called somewhere, TS is unable to understand that execution halts, and would expect a subsequent statement to return `T`.  

An attempted workaround like `return log.errorAndThrow(args)` would not work either, since the method returns `never`.  _However_, something like `throw log.errorAndThrow(args)` _would_ work--though that's a filthy hack that's both semantically redundant and syntactically meaningless.  

To that end, we should deprecate this method (regardless of whatever happens in #16970).

A reasonable replacement would be a hypothetical `logAndReturnError()` which logs an error message and returns a new `Error` to be thrown.

**Comment by mykola-mokhnach** [comment]
Not sure why should we change our code just because TS does not support this and that. From the pragmatic perspective there might be also other functions whose purpose is only to throw an exception...

Right now I have noticed that log.errorAndThrow gets replaced with `log.error` and `throw new Error`. 
We may also change `log.errorAndThrow` to just return an error instance, so the replacement would look like `throw log.errorAndThrow`

**Comment by boneskull** [comment]
> Not sure why should we change our code just because TS does not support this and that. 

Because we will have to deal with it one way or the other; it impedes compilation and typechecking.  The alternative would be to add (possibly multiple) `// @ts-expect-error` in every function in which `logErrorAndThrow()` is used.

**Comment by mykola-mokhnach** [comment]
Added an alternative `errorWithException`, which is supposed to return an exception instead of throwing it. The legacy method has been marked as deprecated
