### ISSUE TITLE
bug: chromedriver autodownload not working

### ISSUE THREAD

**Issue by jlipps** [appium/appium#18431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Seems like we can't parse the correct info anymore from the google storage site? I get this error even though my computer can indeed access this host:

```
[Chromedriver@a076] Cannot synchronize local chromedrivers with the remote storage at https://chromedriver.storage.googleapis.com: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com
```

### Expected Behavior

Chromedriver should be automatically downloaded

### Minimal Reproducible Example

See appium log

### Environment

See appium log

### Link to Appium Logs

https://gist.github.com/jlipps/548017d74c2fd87117bba7d9d3f39667

**Comment by jlipps** [comment]
@mykola-mokhnach any ideas?

**Comment by mykola-mokhnach** [comment]
Works for me. Maybe an issue with your firewall?

**Comment by KazuCocoa** [comment]
Tried with latest uia2?
https://github.com/appium/appium-uiautomator2-driver/pull/587 might be related. Or I also I met a bad internet connection on my local machine before, then the error occurred.

**Comment by jlipps** [comment]
hmm worked today after upgrading the uiauto2 driver. maybe it was an unrelated issue.
