### ISSUE TITLE
xcuitest: improve bad parameters error message

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18438]
Currently, if the client sends invalid parameters to an endpoint, they will receive a message such as:

```
invalid argument: Parameters were incorrect. We wanted {"optional":["name","direction","predicateString","toVisible","distance","elementId","sessionId","id"],"required":[]} and you sent ["whatever you sent"]
```

This could be friendlier.  Note that `required` and `optional` can be of type `string[]` or `string[][]`.

**Comment by Chaitya62** [comment]
@boneskull, can you give an example how it could look like vs what you have shared.

**Comment by boneskull** [comment]
@Chaitya62 I was thinking more human-readable formatting.  Something like

```
Command {command} received invalid parameters.  The allowed parameters are:

- {type} {param} {required/optional}
- {type} {param} {required/optional}
- {type} {param} {required/optional}
```

**Comment by zeufack** [comment]
Hello, please is someone working on this ??

**Comment by mykola-mokhnach** [comment]
Closed as fixed
