### ISSUE TITLE
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed).

### ISSUE THREAD

**Issue by PashaAlthaf** [appium/appium#18436]
UiAutomator2 is crashing randomly during Android script executions.   

Android version : 13
Device : Google Pixel 4
Appium version : 1.22.3
Host machine : MAC.

Android automation executions are failing due to UiAutomator2 crashing issue. Required help. Please provide solution for this.

Log as below : 

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
Build info: version: '3.141.59', revision: 'e82be7d358'
System info: host: 'C02F5443ML7J', ip: 'fe80:0:0:0:1c05:d6ca:1a08:3a88%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.3.1', java.version: '15.0.2'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {app: /Users/althafpasha/Download..., appActivity: com.librelink.app.ui.Splash..., appPackage: com.freestylelibre.app.fr, automationName: UiAutomator2, databaseEnabled: false, desired: {app: /Users/althafpasha/Download..., appActivity: com.librelink.app.ui.Splash..., appPackage: com.freestylelibre.app.fr, automationName: UiAutomator2, deviceName: 9B081FFAZ0043N, newCommandTimeout: 1800, noReset: true, platformName: android, platformVersion: 13, udid: 9B081FFAZ0043N}, deviceApiLevel: 33, deviceManufacturer: Google, deviceModel: Pixel 4, deviceName: 9B081FFAZ0043N, deviceScreenDensity: 440, deviceScreenSize: 1080x2280, deviceUDID: 9B081FFAZ0043N, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 1800, noReset: true, pixelRatio: 2.75, platform: LINUX, platformName: android, platformVersion: 13, statBarHeight: 83, takesScreenshot: true, udid: 9B081FFAZ0043N, viewportRect: {height: 2065, left: 0, top: 83, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 7bd86989-afab-412f-9c4e-2d6e9da2dc58
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/

**Comment by mykola-mokhnach** [comment]
We do not maintain Appium 1 anymore. Please use the most recent driver version supplied with Appium2.
Also provide the full server logs and the logcat one.
