### ISSUE TITLE
Trying to run automation on simulator. Opens app and then nothing happens "Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body"

### ISSUE THREAD

**Issue by Lept14** [appium/appium#18440]
Hey y'all, I'm trying to run some automation via Robot Framework, Appium, and Xcode. Trying to just run some simple robot tests, it will connect to my iOS simulator, it opens the app, and then nothing happens and sits forever on the app homepage. Which is really weird cause it was working just fine before, able to do everything. I keep seeing in the appium logs "GET /status... with no body", it just keeps spamming it. What went wrong? 

[info] [35m[HTTP][39m Waiting until the server is closed
[info] [35m[HTTP][39m Received server close event
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/03fefc5d-b694-4e34-8d04-0aa36cf995f5/source [39m[32m-[39m [90m- ms - -[39m
[info] [35m[HTTP][39m [90m[39m
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n  <XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"QA APP\" label=\"QA APP\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n    <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n            <XCUIElementTypeOth...
[debug] [35m[W3C (03fefc5d)][39m Responding to client with driver.getPageSource() result: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n  <XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"QA APP\" label=\"QA APP\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n    <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n            <XCUIElementTypeOther type=\...
[info] [35m[Appium][39m Welcome to Appium v1.22.3
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[debug] [35m[HTTP][39m Request idempotency key: db1a3cf1-cb82-4877-addf-3e78365059f7
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"capabilities":{"firstMatch":[{"appium:automationName":"XCUITest","platformName":"iOS","appium:platformVersion":"","appium:deviceName":"iPhone 14 Pro","appium:udid":null,"appium:xcodeOrgId":null,"appium:app":"/Users/Bob.Ross/Library/Developer/Xcode/DerivedData/Mobile-btsnkibtotricihaidjzshggjutm/Build/Products/DebugQA-iphonesimulator/Mobile.app"}]},"desiredCapabilities":{"automationName":"XCUITest","platformName":"iOS","platformVersion":"","deviceName":"iPhone 14 Pro","udid":null,"xcodeOrgId":null,"app":"/Users/Bob.Ross/Library/Developer/Xcode/DerivedData/Mobile-btsnkibtotricihaidjzshggjutm/Build/Products/DebugQA-iphonesimulator/Mobile.app"}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","platformName":"iOS","platformVersion":"","deviceName":"iPhone 14 Pro","udid":null,"xcodeOrgId":null,"app":"/Users/Bob.Ross/Library/Developer/Xcode/DerivedData/Mobile-btsnkibtotricihaidjzshggjutm/Build/Products/DebugQA-iphonesimulator/Mobile.app"},null,{"firstMatch":[{"appium:automationName":"XCUITest","platformName":"iOS","appium:platformVersion":"","appium:deviceName":"iPhone 14 Pro","appium:udid":null,"appium:xcodeOrgId":null,"appium:app":"/Users/Bob.Ross/Library/Developer/Xcode/DerivedData/Mobile-btsnkibtotricihaidjzshggjutm/Build/Products/DebugQA-iphonesimulator/Mobile.app"}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1678839215866 (17:13:35 GMT-0700 (Pacific Daylight Time))
[info] [35m[Appium][39m Appium v1.22.3 creating new XCUITestDriver (v3.59.0) session
[info] [35m[Appium][39m Applying relaxed security to 'XCUITestDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [35m[BaseDriver][39m W3C capabilities and MJSONWP desired capabilities were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {
[debug] [35m[BaseDriver][39m   "alwaysMatch": {
[debug] [35m[BaseDriver][39m     "platformName": "iOS",
[debug] [35m[BaseDriver][39m     "appium:automationName": "XCUITest",
[debug] [35m[BaseDriver][39m     "appium:platformVersion": "",
[debug] [35m[BaseDriver][39m     "appium:deviceName": "iPhone 14 Pro",
[debug] [35m[BaseDriver][39m     "appium:udid": null,
[debug] [35m[BaseDriver][39m     "appium:xcodeOrgId": null,
[debug] [35m[BaseDriver][39m     "appium:app": "/Users/Bob.Ross/Library/Developer/Xcode/DerivedData/Mobile-btsnkibtotricihaidjzshggjutm/Build/Products/DebugQA-iphonesimulator/Mobile.app"
[debug] [35m[BaseDriver][39m   },
[debug] [35m[BaseDriver][39m   "firstMatch": [
[debug] [35m[BaseDriver][39m     {}
[debug] [35m[BaseDriver][39m   ]
[debug] [35m[BaseDriver][39m }
[warn] [35m[XCUITest][39m 'platformVersion' capability ('') is not a valid version number. Consider fixing it or be ready to experience an inconsistent driver behavior.
[info] [35m[BaseDriver][39m Session created with session id: 20408025-68a3-461c-ac04-3fbf98848287
[debug] [35m[XCUITest][39m Current user: 'Bob.Ross'
[info] [35m[XCUITest][39m iOS SDK Version set to '16.2'
[info] [35m[XCUITest][39m No platformVersion specified. Using the latest version Xcode supports: '16.2'. This may cause problems if a simulator does not exist for this platform version.[info] [35m[iOSSim][39m Constructing iOS simulator for Xcode version 14.2 with udid '7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C'
[info] [35m[XCUITest][39m Determining device to run tests on: udid: '7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C', real device: false
[debug] [35m[BaseDriver][39m Event 'xcodeDetailsRetrieved' logged at 1678839216925 (17:13:36 GMT-0700 (Pacific Daylight Time))[info] [35m[XCUITest][39m Not scrubbing third party app in anticipation of uninstall
[debug] [35m[BaseDriver][39m Event 'resetComplete' logged at 1678839218521 (17:13:38 GMT-0700 (Pacific Daylight Time))
[info] [35m[WebDriverAgent][39m Using WDA path: '/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent'
[info] [35m[WebDriverAgent][39m Using WDA agent: '/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'[debug] [35m[IOSSimulatorLog][39m Starting log capture for iOS Simulator with udid '7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C' using simctl[debug] [35m[BaseDriver][39m Event 'logCaptureStarted' logged at 1678839220111 (17:13:40 GMT-0700 (Pacific Daylight Time))
[info] [35m[XCUITest][39m Setting up simulator
[debug] [35m[XCUITest][39m No reason to set locale
[debug] [35m[XCUITest][39m No iOS / app preferences to set
[debug] [35m[XCUITest][39m Setting did not need to be updated
[debug] [35m[iOSSim][39m Setting preferences of 7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C Simulator to {"ConnectHardwareKeyboard":false}
[debug] [35m[iOSSim][39m Setting common Simulator preferences to {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false,"PasteboardAutomaticSync":false}[debug] [35m[iOSSim][39m Updated 7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C Simulator preferences at '/Users/Bob.Ross/Library/Preferences/com.apple.iphonesimulator.plist' with {"RotateWindowWhenSignaledByGuest":true,"ConnectHardwareKeyboard":false,"PasteboardAutomaticSync":false,"DevicePreferences":{"7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C":{"SimulatorExternalDisplay":2114,"ConnectHardwareKeyboard":false,"SimulatorWindowRotationAngle":0,"SimulatorWindowOrientation":"Portrait","SimulatorWindowGeometry":{"BEAF0B29-CEC1-4CDD-BD8F-49CAAC774BA2":{"WindowCenter":"{1567.5, 547}","WindowScale":1},"B12F43D3-AF70-49F4-8256-01DE34304CB4":{"WindowCenter":"{3601.5, 575}","WindowScale":1}},"ChromeTint":""}}}[debug] [35m[iOSSim][39m Got Simulator UI client PID: 55106
[info] [35m[iOSSim][39m Both Simulator with UDID '7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C' and the UI client are currently running[debug] [35m[BaseDriver][39m Event 'simStarted' logged at 1678839222305 (17:13:42 GMT-0700 (Pacific Daylight Time))
[debug] [35m[XCUITest][39m Verifying application platform
[debug] [35m[XCUITest][39m CFBundleSupportedPlatforms: ["iPhoneSimulator"][debug] [35m[XCUITest][39m Reset requested. Removing app with id 'com.uvnv.MobileQA' from the device[debug] [35m[XCUITest][39m Installing '/Users/Bob.Ross/Library/Developer/Xcode/DerivedData/Mobile-btsnkibtotricihaidjzshggjutm/Build/Products/DebugQA-iphonesimulator/Mobile.app' on Simulator with UUID '7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C'...[debug] [35m[WebDriverAgent][39m Parsed BUILD_DIR configuration value: '/Users/Bob.Ross/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou/Build/Products'
[debug] [35m[WebDriverAgent][39m Got derived data root: '/Users/Bob.Ross/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou'[debug] [35m[XCUITest][39m The app has been installed successfully.
[debug] [35m[BaseDriver][39m Event 'appInstalled' logged at 1678839244516 (17:14:04 GMT-0700 (Pacific Daylight Time))[debug] [35m[WebDriverAgent][39m No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[info] [35m[DevCon Factory][39m Requesting connection for device 7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C on local port 8100
[debug] [35m[DevCon Factory][39m Cached connections count: 1
[info] [35m[DevCon Factory][39m Found cached connections on port #8100: ["7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C:8100"]
[info] [35m[DevCon Factory][39m Successfully requested the connection for 7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C:8100
[debug] [35m[XCUITest][39m Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"15.4","version":"16.2"},"ios":{"simulatorVersion":"16.2","ip":"10.0.0.91"},"ready":true,"build":{"upgradedAt":"1652581048000","time":"Jan 18 2023 07:23:51","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"D9FB465B-359D-43C3-9579-4304160BE0AA"}
[debug] [35m[WebDriverAgent][39m Upgrade timestamp of the currently bundled WDA: 1652581048000
[debug] [35m[WebDriverAgent][39m Upgrade timestamp of the WDA on the device: 1652581048000
[info] [35m[WebDriverAgent][39m Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [35m[XCUITest][39m Trying to start WebDriverAgent 2 times with 10000ms interval
[debug] [35m[XCUITest][39m These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [35m[BaseDriver][39m Event 'wdaStartAttempted' logged at 1678839244678 (17:14:04 GMT-0700 (Pacific Daylight Time))
[info] [35m[WebDriverAgent][39m Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"15.4","version":"16.2"},"ios":{"simulatorVersion":"16.2","ip":"10.0.0.91"},"ready":true,"build":{"upgradedAt":"1652581048000","time":"Jan 18 2023 07:23:51","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"D9FB465B-359D-43C3-9579-4304160BE0AA"}
[debug] [35m[BaseDriver][39m Event 'wdaSessionAttempted' logged at 1678839244685 (17:14:04 GMT-0700 (Pacific Daylight Time))
[debug] [35m[XCUITest][39m Sending createSession command to WDA
[debug] [35m[WD Proxy][39m Matched '/session' to command name 'createSession'
[debug] [35m[WD Proxy][39m Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"com.uvnv.MobileQA","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true,"forceAppLaunch":true,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":true}],"alwaysMatch":{}}}[warn] [35m[BaseDriver][39m Shutting down because we waited 60 seconds for a command
[warn] [35m[Appium][39m Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[info] [35m[Appium][39m Removing session '03fefc5d-b694-4e34-8d04-0aa36cf995f5' from our master session list
[info] [35m[DevCon Factory][39m Releasing connections for 7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C device on any port number
[info] [35m[DevCon Factory][39m Found cached connections to release: ["7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C:8100"]
[debug] [35m[DevCon Factory][39m Cached connections count: 0
[debug] [35m[XCUITest][39m Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":{"sessionId":"853DB105-2148-4BBC-8454-E635A3674512","capabilities":{"device":"iphone","browserName":"QA APP","sdkVersion":"16.2","CFBundleIdentifier":"com.uvnv.MobileQA"}},"sessionId":"853DB105-2148-4BBC-8454-E635A3674512"}
[info] [35m[WD Proxy][39m Determined the downstream protocol as 'W3C'
[debug] [35m[BaseDriver][39m Event 'wdaSessionStarted' logged at 1678839256476 (17:14:16 GMT-0700 (Pacific Daylight Time))
[debug] [35m[BaseDriver][39m Event 'wdaStarted' logged at 1678839256476 (17:14:16 GMT-0700 (Pacific Daylight Time))
[info] [35m[XCUITest][39m Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [35m[BaseDriver][39m Event 'orientationSet' logged at 1678839256477 (17:14:16 GMT-0700 (Pacific Daylight Time))
[debug] [35m[BaseDriver][39m The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [35m[BaseDriver][39m The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[info] [35m[Appium][39m New XCUITestDriver session created successfully, session 20408025-68a3-461c-ac04-3fbf98848287 added to master session list
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1678839256478 (17:14:16 GMT-0700 (Pacific Daylight Time))
[debug] [35m[W3C (20408025)][39m Cached the protocol value 'W3C' for the new session 20408025-68a3-461c-ac04-3fbf98848287
[debug] [35m[W3C (20408025)][39m Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"iOS","automationName":"XCUITest","platformVersion":"","deviceName":"iPhone 14 Pro","udid":"7F2AC827-5AFA-483D-9EBC-F7C3F0CA409C","xcodeOrgId":null,"app":"/Users/Bob.Ross/Library/Developer/Xcode/DerivedData/Mobile-btsnkibtotricihaidjzshggjutm/Build/Products/DebugQA-iphonesimulator/Mobile.app"}}
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m200[39m [90m40615 ms - 591[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/20408025-68a3-461c-ac04-3fbf98848287/source[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (20408025)][39m Calling AppiumDriver.getPageSource() with args: ["20408025-68a3-461c-ac04-3fbf98848287"]
[debug] [35m[XCUITest][39m Executing command 'getPageSource'
[debug] [35m[WD Proxy][39m Matched '/source?scope=AppiumAUT' to command name 'getPageSource'
[debug] [35m[WD Proxy][39m Proxying [GET /source?scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/853DB105-2148-4BBC-8454-E635A3674512/source?scope=AppiumAUT] with no body
[debug] [35m[WD Proxy][39m Got response with status 200: {"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n  <XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"QA APP\" label=\"QA APP\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n    <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n            <XCUIElementTypeOth...
[debug] [35m[W3C (20408025)][39m Responding to client with driver.getPageSource() result: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n  <XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"QA APP\" label=\"QA APP\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n    <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n            <XCUIElementTypeOther type=\...
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/20408025-68a3-461c-ac04-3fbf98848287/source [39m[32m200[39m [90m194 ms - 1529[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/20408025-68a3-461c-ac04-3fbf98848287/source[39m
[info] [35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (20408025)][39m Calling AppiumDriver.getPageSource() with args: ["20408025-68a3-461c-ac04-3fbf98848287"]
[debug] [35m[XCUITest][39m Executing command 'getPageSource'
[debug] [35m[WD Proxy][39m Matched '/source?scope=AppiumAUT' to command name 'getPageSource'
[debug] [35m[WD Proxy][39m Proxying [GET /source?scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/853DB105-2148-4BBC-8454-E635A3674512/source?scope=AppiumAUT] with no body[debug] [35m[WD Proxy][39m Got response with status 200: {"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n  <XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"QA APP\" label=\"QA APP\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n    <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n            <XCUIElementTypeOth...
[debug] [35m[W3C (20408025)][39m Responding to client with driver.getPageSource() result: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n  <XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"QA APP\" label=\"QA APP\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n    <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" visible=\"true\" accessible=\"false\" x=\"0\" y=\"0\" width=\"393\" height=\"852\" index=\"0\">\n            <XCUIElementTypeOther type=\...
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/20408025-68a3-461c-ac04-3fbf98848287/source [39m[32m200[39m [90m167 ms - 1529[39m
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/20408025-68a3-461c-ac04-3fbf98848287/source[39m
[info] [35m[HTTP][39m [90m{}[39m

**Comment by KazuCocoa** [comment]
The new session request succeeded, and the next get page source was returned as below:
```
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[32m200[39m [90m40615 ms - 591[39m
```

```
[info] [35m[HTTP][39m [90m[39m[info] [35m[HTTP][39m [37m-->[39m [37mGET[39m [37m/wd/hub/session/20408025-68a3-461c-ac04-3fbf98848287/source[39m
...
[info] [35m[HTTP][39m [37m<-- GET /wd/hub/session/20408025-68a3-461c-ac04-3fbf98848287/source [39m[32m200[39m [90m194 ms - 1529[39m
```

The logs seem normal for me. If you have a general question. https://discuss.appium.io/ may help

**Comment by Lept14** [comment]
Yeah it seems like the simulator opens just fine, but wondering why it's not receiving commands from my robot framework. And I noticed it kept spamming "[GET http://127.0.0.1:8100/session/853DB105-2148-4BBC-8454-E635A3674512/source?scope=AppiumAUT] with no body" which it never used to do in previous builds.
