### ISSUE TITLE
Appium 2.0 installation fails

### ISSUE THREAD

**Issue by kdave47** [appium/appium#18443]
### Discussed in https://github.com/appium/appium/discussions/18422

<div type='discussions-op-text'>

<sup>Originally posted by **kdave47** March 30, 2023</sup>
appium -v

Fatal Error: Appium had trouble loading the extension installation cache file (/usr/local/bin/appium/node_modules/.cache/appium/extensions.yaml). It may be invalid YAML. Specific error: ENOTDIR: not a directory, open ‘/usr/local/bin/appium/node_modules/.cache/appium/extensions.yaml’
at /usr/local/lib/node_modules/appium/lib/extension/manifest.js:410:19
at Manifest.read (/usr/local/lib/node_modules/appium/lib/extension/manifest.js:463:7)
at loadExtensions (/usr/local/lib/node_modules/appium/lib/extension/index.js:22:3)
at init (/usr/local/lib/node_modules/appium/lib/main.js:175:40)
at main (/usr/local/lib/node_modules/appium/lib/main.js:283:22)

Unable to install appium using npm on mac.</div>

**Comment by mykola-mokhnach** [comment]
Make sure to delete all leftovers from the previous installations, unset APPIUM_HOME and clean the npm cache (npm cache clean –force). Then try to perform a new Appium 2 install.

**Comment by kdave47** [comment]
Thank you for your response, I did same steps as you suggested and was able to install appium 2.0 version. What i observed is once I am able to get --version If i set the APPIUM_HOME  again in zshrc it is causing issue again.

Steps I followed:

1. Uninstalled Appium 
2. Cleared npm cache 
3. Removed APPIUM_HOME from zshrc
4. Installed next version of appium
5. Checked version [Successful installation]
6.  Set APPIUM_HOME  again in  .zshrc
7. Checked version  [THROWS Error as below screenshot]


Note: Removing APPIUM_HOME from zshrc works and shows successful installed APPIUM 2.0.

Kindly advice if anything wrong or unexpected step in above walkthrough.

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/4139979/229985441-a0ab34af-fec7-47bd-a7d8-2273e20323ae.png">

**Comment by mykola-mokhnach** [comment]
I don't think /usr/local/bin/appium is the correct value for APPIUM_HOME. A valid value should a path to a WRITEABLE FOLDER where the server keeps driver and plugin packages plus the config manifest. By default it is pointing to ~/.appium

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
