### ISSUE TITLE
bug: appium-ios-device throws `Unexpected data: ${JSON.stringify(data)}` error

### ISSUE THREAD

**Issue by chmiiller** [appium/appium#18450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using `appium-ios-device` in a tool I'm working on that allows users to simulate location on their iOS devices. Some Windows users have reported the following bug. (see below image for more details)

### Expected Behavior

Lockdown should just work

### Minimal Reproducible Example

I have a small NodeJS project with `appium-ios-device` as its only dependency and when running the code below with `node app.js` I get the
`{"Error": "InvalidService", "Request": "StartService", "Service": "com.apple.dt .simulatelocation"}` message.

```js
import Usbmux from 'appium-ios-device';
const utilities = Usbmux.utilities;

const AMSTERDAM = { lat: 52.379184, lon: 4.900437 };
let firstDeviceId = '';

async function getDevices() {
  try {
    const connectedDevices = await utilities.getConnectedDevices();
    if(connectedDevices && connectedDevices.length > 0) {
      firstDeviceId = connectedDevices[0];
    }  
  } catch (error) {
    console.log(`on getDevices: ${error}`);
  }
}

async function getDeviceInfo(id) {
  try {
    const deviceInfo = await Usbmux.utilities.getDeviceInfo(id);
    console.log(`deviceInfo: ${JSON.stringify(deviceInfo, null, '    ')}`);
  } catch (error) {
    console.log(`on getDeviceInfo: ${error}`);
  }
}

async function setGeoLocation(id, lat, lon) {
  try {
    const locationService = await Usbmux.services.startSimulateLocationService(id);
    locationService.setLocation(lat, lon);
  } catch (error) {
    console.log(`on setGeoLocation: ${error}`);
  }
}

async function resetGeoLocation(id) {
  try {
    const locationService =  await Usbmux.services.startSimulateLocationService(id);
  locationService.resetLocation();
  } catch (error) {
    console.log(`on resetGeoLocation: ${error}`);
  }
}

async function simulate() {
  await getDevices();
  await getDeviceInfo(firstDeviceId);
  console.log(` ------------------------------------- sending you to Amsterdam ------------------------------------- `);
  await setGeoLocation(firstDeviceId, AMSTERDAM.lat, AMSTERDAM.lon);
  setTimeout(async() => {
    console.log(` ------------------------------------- now back home ------------------------------------- `);
    await resetGeoLocation(firstDeviceId);
  }, 5000);
}

simulate();
```

To me, it looks like the simulatelocation service doesn't have access to the device's lockdown/developer's image.
I know that this problem is specific to `appium-ios-device` but in the repository's README file it's said to open issues here instead.

### Environment

- Operating system: macOS or Windows
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator: real device

NodeJS v16

### Futher Information

![216087434-1936d402-47c2-4c41-8e73-ccd32b65220c](https://user-images.githubusercontent.com/1013632/230069260-935cf6d0-1480-4192-b3e5-d686add363cb.png)

_Edited by @boneskull: reformatting_

**Comment by chmiiller** [comment]
What is weird, is that I was having this problem when trying to set a location on my iPhone, but it worked fine after I opened Xcode. I have the impression that Xcode reads the device once and everything is ready to go. How can I do something similar to this in a Windows machine?

**Comment by boneskull** [comment]
AFAIK Windows is not a supported platform for any of Appium's iOS stuff, but I could be wrong.  If that's true and it's not mentioned in the docs somewhere, it should be...

**Comment by KazuCocoa** [comment]
Correct, I think it may have some issues for non macOS env as no Xcode.
The project was for xcuitest deiver, so it expected only for macOS as https://appium.github.io/appium-xcuitest-driver/latest/setup/

We may be able to address that the repository is for macOS as well as the parent xcuitest project.

**Comment by mykola-mokhnach** [comment]
@tomriddly Could you please help with this issue?

**Comment by tomriddly** [comment]
This happens when using lower version Xcode with higher version iOS devices. During this parts, a develop image is required to mount and then it will work properly.
The full procedure is to download a ios device support file and call ´ideviceimagemounter´ before calling service. And of cource Xcode do this for you. for some case, when a new device plugin, you will also see a loading progress for device with "Device is busing: feching develop symbol". This is happened also in same progress.
I think I can add such methods to ´appium-ios-device´ which downloads and mount devicesupport from repos like  [https://github.com/iGhibli/iOS-DeviceSupport](https://github.com/iGhibli/iOS-DeviceSupport) or [https://github.com/filsv/iOSDeviceSupport](https://github.com/filsv/iOSDeviceSupport) if we failed to start service.

**Comment by chmiiller** [comment]
you're absolutely right @tomriddly, I had the exact same examples in both macOS and Windows. The idea of adding the image download is also good, but I have a question: Where are the support files read from on Windows? And if `appium-iOS-device` would download it, where would you save these?
Thanks for looking into it

**Comment by tomriddly** [comment]
> you're absolutely right @tomriddly, I had the exact same examples in both macOS and Windows. The idea of adding the image download is also good, but I have a question: Where are the support files read from on Windows? And if `appium-iOS-device` would download it, where would you save these? Thanks for looking into it nvm, just saw the opened PR [appium/appium-ios-device#112](https://github.com/appium/appium-ios-device/pull/112)

I've tested my code of mounting image on linux which works as expected, it should be effective on windows as well.
But auto downloading from public repo could be a dangerous thing which actually  happened on Xcode mirror once before. So I changed to allow users to pass a repo and sub folders to download and mount images. Maybe appium will make a mirror in the future, but this is still under discussion and not decided yet, so no promise could be make.
You can try the `imagemounter` branch of `appium-ios-device` as a test on windows. But as I said above, I could not make sure the safety of image in public repo and won't take responsibility for any unforeseen consequence.
