### ISSUE TITLE
UiAutomator2 install fails due to Chromedriver download issue

### ISSUE THREAD

**Issue by spinning10** [appium/appium#18468]
I can't successfully run the following command on Windows 10 OS: 
_appium driver install uiautomator2_

Getting a big error log (most of it not pasted here, not relevant) like:
`× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.

STDOUT:
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "C:\\WINDOWS\\system32\\cmd.exe /d /s /c node install-npm.js\n[16:40:28] Error installing Chromedriver: socket hang up`

npm -v
9.5.0
node -v
v18.15.0

**Comment by jlipps** [comment]
It looks like your machine is not able to download Chromedriver for some reason. try this instead maybe:

```
APPIUM_SKIP_CHROMEDRIVER_INSTALL=1 appium driver install uiautomator2
```

That might get you a working uiautomator2 driver (though without Chromedriver you won't be able to automate webviews).

**Comment by boneskull** [comment]
Transient network problem?

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
