### ISSUE TITLE
Question: does Appium support WebView on Windows

### ISSUE THREAD

**Issue by kishorenadiger** [appium/appium#18467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to get webView with "appium:autoWebview": true with "platformName": "Windows".
<img width="1174" alt="Screenshot 2023-04-06 at 7 49 27 PM" src="https://user-images.githubusercontent.com/33542654/230405835-af2548c3-9500-4e03-8c42-c66b45cabe1b.png">

### Expected Behavior

We must expect the webview to be generated as appium:autoWebview is set to true.
If there is any other alternate way where we can achieve to get webview for windows application.

### Minimal Reproducible Example

 "platformName": "Windows",
 "appium:autoWebview": true

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
What automationName did you use? https://github.com/appium/appium-windows-driver does not provide WebView functionality if you used the driver

**Comment by kishorenadiger** [comment]
My Capabilities: 
{
  "platformName": "Windows",
  "appium:platformVersion": "10",
  "appium:deviceName": "WindowsPC",
  "appium:app": "WebView2-WinSample_z6x1pfa4wctbe!App",
  "appium:autoWebview": "true"
}

Have not specified any automationName explicitly.
If appium windows driver is not supporting ,then can we change to a different driver that support webView in appium for windows application.
What capabilities can we add to switch drivers in Appium inspector ?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-chromium-driver is the only driver to manage chromedriver for desktop browser via Appium. This is not WebView2 as the primary usage we expect, but perhaps you can use it for https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver

**Comment by kishorenadiger** [comment]
We are not using a desktop  browser via appium , We are using windows UWP Hybrid application.
Can we the same chromium driver to get the web view for UWP Hybrid application?

**Comment by KazuCocoa** [comment]
Appium does not provide WebView sruff for Windows applications, so no. We only provide https://github.com/appium/appium-windows-driver for native windows app (no WebView)  and https://github.com/appium/appium-chromium-driver .

Potentially https://github.com/appium/appium-chromium-driver can work for WebView2 as  
https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver. That's everything for now.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. Hybrid functionality is not supported in Windows driver
