### ISSUE TITLE
Failed to install reactive Native app

### ISSUE THREAD

**Issue by umadevidokka** [appium/appium#18475]
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

the above is the error facing while installing the app

**Comment by mykola-mokhnach** [comment]
https://stackoverflow.com/questions/24572052/install-failed-no-matching-abis-when-install-apk

Looks like you are trying to install a package that does not match the device's under test architecture. 
Closed as not an issue
