### ISSUE TITLE
bug: throw no such element Error when switcing to context (webview)

### ISSUE THREAD

**Issue by MaryWX1118** [appium/appium#18476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium not able to detect webview, however, we areable to use chrome dev tool to detect the control, but when running the script, got No such element error.

### Expected Behavior

Appium should be able to detect webview controls.

### Minimal Reproducible Example

Set<String>contextNames=driver.getContextHandles();
for(String contextName: contextNames){
 System.out.print(contextName);

}
driver.context(String.valueOf(contextNames.toArray()[1]));
click(driver, homePageObjects.pagecontrol);

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
Could you share the full appium server log as GIST?
