### ISSUE TITLE
bug: <build project error c99>

### ISSUE THREAD

**Issue by Ives236** [appium/appium#18488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

mixing declarations and code is incompatible with standards before c99

### Expected Behavior

build project successd

### Minimal Reproducible Example

..

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
closed as incomplete
