### ISSUE TITLE
xcuitest: filter e2e workflows

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18492]
The (very slow) E2E workflows run on every change to every PR. 

For some subset of file changes, we should not need to run these E2E tests--much like we do [here](https://github.com/appium/appium/blob/master/.github/workflows/build.yml#L5-L21).

In the case of `appium-xcuitest-driver`, It may make more sense to create a "deny list" of files that _shouldn't_ trigger the build; e.g., `.releaserc`, `**/*.md`, `docs/**/*`, `.wallaby.js`, `.renovaterc.json`, etc.

`appium-xcuitest-driver`'s "docs" build is already filtered similarly.

**Comment by mykola-mokhnach** [comment]
Added exceptions to all drivers where we have function tests
