### ISSUE TITLE
Appium Not Loading UIAutomator2 Driver 

### ISSUE THREAD

**Issue by krarpitgupta** [appium/appium#18499]
### OS Info : Mac 13.3.1 (22E261)

**Appium Version**  2.0.0-beta.62

**Installed Driver**  uiautomator2@2.14.0 [installed (npm)]

**Node Version**   v18.15.0

**NPM version**     9.5.0

`arpitgupta@C02ZR5V0MD6M libexec % appium -v
2.0.0-beta.62
arpitgupta@C02ZR5V0MD6M libexec % appium driver list --installed
✔ Listing installed drivers
- uiautomator2@2.14.0 [installed (npm)]
arpitgupta@C02ZR5V0MD6M libexec % appium
[Appium] Welcome to Appium v2.0.0-beta.62
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /Users/arpitgupta/.appium/node_modules/appium-uiautomator2-driver
[Appium] Could not load driver 'uiautomator2', so it will not be available. Error in loading the driver was: Cannot find module '/Users/arpitgupta/.appium/node_modules/appium-uiautomator2-driver/node_modules/bluebird/js/release/bluebird.js'. Please verify that the package.json has a valid "main" entry
[debug] [Appium] Error: Cannot find module '/Users/arpitgupta/.appium/node_modules/appium-uiautomator2-driver/node_modules/bluebird/js/release/bluebird.js'. Please verify that the package.json has a valid "main" entry
[debug] [Appium]     at tryPackage (node:internal/modules/cjs/loader:436:19)
[debug] [Appium]     at Function.Module._findPath (node:internal/modules/cjs/loader:678:18)
[debug] [Appium]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
[debug] [Appium]     at Function.Module._load (node:internal/modules/cjs/loader:920:27)
[debug] [Appium]     at Module.require (node:internal/modules/cjs/loader:1141:19)
[debug] [Appium]     at require (node:internal/modules/cjs/helpers:110:18)
[debug] [Appium]     at Object.<anonymous> (/Users/arpitgupta/.appium/node_modules/appium-uiautomator2-driver/node_modules/asyncbox/lib/asyncbox.js:3:1)
[debug] [Appium]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
[debug] [Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
[debug] [Appium]     at Module.load (node:internal/modules/cjs/loader:1117:32)
[debug] [Appium]     at Function.Module._load (node:internal/modules/cjs/loader:958:12)
[debug] [Appium]     at Module.require (node:internal/modules/cjs/loader:1141:19)
[debug] [Appium]     at require (node:internal/modules/cjs/helpers:110:18)
[debug] [Appium]     at Object.<anonymous> (/Users/arpitgupta/.appium/node_modules/appium-uiautomator2-driver/lib/uiautomator2.js:3:1)
[debug] [Appium]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
[debug] [Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - uiautomator2@2.14.0 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.

`

**Comment by Fathimasifa2023** [comment]
how to uninstall ?
