### ISSUE TITLE
tabbed multi-language code blocks for docs

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18498]
[Here's how we can do this](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#grouping-code-blocks). 

I think it's just a matter of translating our `@example` tags into this output. Half of it is done already--the typedoc plugin recognizes multiple-language examples and creates an appropriate data structure for the template. So we need to have the handlebars template render it this way (and maybe enable something in the mkdocs config?).

**Comment by jlipps** [comment]
we already have this enabled in our mkdocs config
