### ISSUE TITLE
xcuitest: get jpeg screenshot instead of png

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#18506]
(this issue is my work note:)

`/screenshot?format=png` or `/screenshot?format=jpeg` as WDA in https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Commands/FBScreenshotCommands.m#L22-L23

As xcuitest, the command will be `mobile:screenshot`. Maybe when `compressionQuality` is 1 or 2, we can response them as-is or just to adjust their orientation?

As this, users may be able to expect the file size (response body size as well) will decrease. (slightly(?) it will improve performance to get screenshots over network like internal network route)

I'm not sure how this format change helps, so i need to measure the diff though.

**Comment by mykola-mokhnach** [comment]
I would say compressionQuality does the trick anyway. The standard says screenshots must be returned in .png format anyway.
