### ISSUE TITLE
WebDriverAgentRunner build failed

### ISSUE THREAD

**Issue by evserykh** [appium/appium#18502]
I've installed Appium 2 (2.0.0-beta.61) via NPM with xcuitest driver (4.21.28). 

When I try the command with the real device's id I've got the error:

```
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=real-device-id' test
```

I've got the errors:

```
Testing failed:
        No visible @interface for 'XCUIDevice' declares the selector 'pressButton:'
        No visible @interface for 'XCUIDevice' declares the selector 'pressButton:'
        Unknown type name 'XCUIDeviceButton'; did you mean 'XCUIRemoteButton'?
        Use of undeclared identifier 'XCUIDeviceButtonHome'; did you mean 'XCUIRemoteButtonHome'?
        Use of undeclared identifier 'XCUIDeviceButtonVolumeUp'
        Use of undeclared identifier 'XCUIDeviceButtonVolumeDown'
        No visible @interface for 'XCUIDevice' declares the selector 'pressButton:'
        Use of undeclared identifier 'XCUIDeviceButtonHome'
        Use of undeclared identifier 'XCUIDeviceButtonHome'
        Testing cancelled because the build failed.

** TEST FAILED **


The following build commands failed:
        CompileC /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-grkfbrzvpmnylxeyutthrhtnztqz/Build/Intermediates.noindex/WebDriverAgent.build/Debug-maccatalyst/WebDriverAgentLib.build/Objects-normal/x86_64/XCUIDevice+FBHelpers.o /Users/user/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
(1 failure)
```

**Comment by evserykh** [comment]
I use Xcode 14.3 and iPhone with 16.4.1 installed iOS.

**Comment by KazuCocoa** [comment]
What about the below?

macOS 13.2.1 x Xcode 14.3 env worked with below command on my local. This was what https://github.com/appium/WebDriverAgent/blob/master/.github/workflows/wda-package.yml does.
```
xcodebuild clean build-for-testing -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination generic/platform=iOS CODE_SIGNING_ALLOWED=NO ARCHS=arm64
```

I wonder if once calls clean in your env:

```
xcodebuild clean -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=real-device-id' test
```

**Comment by evserykh** [comment]
I've tried. Here is the result. I've got `** CLEAN SUCCEEDED **` message. But still the error:

```
Test session results, code coverage, and logs:                                                                                                                                                                                                                
        /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-grkfbrzvpmnylxeyutthrhtnztqz/Logs/Test/Run-WebDriverAgentRunner-2023.04.12_10-06-17-+0000.xcresult
                                                                                                                                                                                                                                                              
Testing failed:                                                                                                                                                                                               
        No visible @interface for 'XCUIDevice' declares the selector 'pressButton:'                          
        Use of undeclared identifier 'XCUIDeviceButtonHome'                                                                                                                                                                                                   
        Testing cancelled because the build failed.
                                                                                                 
** TEST FAILED **                                                                                                                                                                                                                            

                                                                                                                                                                                                                                                              
The following build commands failed:                                                             
        CompileC /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-grkfbrzvpmnylxeyutthrhtnztqz/Build/Intermediates.noindex/WebDriverAgent.build/Debug-maccatalyst/WebDriverAgentLib.build/Objects-normal/x86_64/XCUIDevice+FBHealthCheck.o /User
s/user/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgentLib/Categories/XCUIDevice+FBHealthCheck.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'WebDriverAgentLib' from projec
t 'WebDriverAgent')                                                                                                                                                                                                                            
(1 failure) 
```
![image](https://user-images.githubusercontent.com/129432/231427443-9459ddad-bf52-4208-bd5e-729202d7de4f.png)

**Comment by evserykh** [comment]
Running the command using a simulator's id has no error 🤷‍♂️
![image](https://user-images.githubusercontent.com/129432/231430323-4e55a09d-1d33-4c42-b316-0e95629c787a.png)

**Comment by mykola-mokhnach** [comment]
What is your device OS version? Are you sure all caches are clean?

**Comment by evserykh** [comment]
I’m not really sure about caches. How do I check it or clean it completely? My device is iphone 13 mini

**Comment by KazuCocoa** [comment]
> How do I check it or clean it completely?

Removing `/Users/user/Library/Developer/Xcode/DerivedData/`

**Comment by evserykh** [comment]
Still the same :(

**Comment by KazuCocoa** [comment]
Hm...
I thought https://github.com/appium/WebDriverAgent/blob/master/PrivateHeaders/XCTest/XCUIDevice.h needed `- (void)pressButton:(long long)arg1;` but actually Xcode raised an error about duplication because of the `#import <XCTest/XCUIDevice.h>` on my local (expected). 

What about manually adding `- (void)pressButton:(long long)arg1;` in `PrivateHeaders/XCTest/XCUIDevice.h` on your local?


```
- (void)pressLockButton;
- (void)holdHomeButtonForDuration:(double)arg1;
- (void)_silentPressButton:(long long)arg1;
// Since Xcode 11
- (_Bool)supportsPressureInteraction;

// added
- (void)pressButton:(long long)arg1;
@end
```

**Comment by evserykh** [comment]
> Hm... I thought [appium/WebDriverAgent@`master`/PrivateHeaders/XCTest/XCUIDevice.h](https://github.com/appium/WebDriverAgent/blob/master/PrivateHeaders/XCTest/XCUIDevice.h?rgh-link-date=2023-04-13T07%3A09%3A58Z) needed `- (void)pressButton:(long long)arg1;` but actually Xcode raised an error about duplication because of the `#import <XCTest/XCUIDevice.h>` on my local (expected).
> 
> What about manually adding `- (void)pressButton:(long long)arg1;` in `PrivateHeaders/XCTest/XCUIDevice.h` on your local?
> 
> ```
> - (void)pressLockButton;
> - (void)holdHomeButtonForDuration:(double)arg1;
> - (void)_silentPressButton:(long long)arg1;
> // Since Xcode 11
> - (_Bool)supportsPressureInteraction;
> 
> // added
> - (void)pressButton:(long long)arg1;
> @end
> ```
> 
> and what macOS version did you use?

Let me try. I use Ventura 13.3

**Comment by KazuCocoa** [comment]
I confirmed not the same, but similar error in 13.3 x Xcode 14.3 environment.
Below worked then:
```
xcodebuild clean build-for-testing test-without-building -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<device id>' -allowProvisioningUpdates 
```

I guess the old `test` did something caused unexpected behavior...?

**Comment by Jellyswat** [comment]
@KazuCocoa  Hi，I just encountering the same problem. Is there any suggestion?

**Comment by evserykh** [comment]
> @KazuCocoa Hi，I just encountering the same problem. Is there any suggestion?

I'm able to build the project if I use a simulator's id as destination value. But building with using a real device's id failed

**Comment by Jellyswat** [comment]
> @Jellyswat what are your macOS, iOS and Xcode versions?

iOS：16.3 （iPhone 14）
macOS：13.3.1
Xcode：14.3

**Comment by Jellyswat** [comment]
`The following build commands failed:
    CompileC /Users/donogxiaoqin/Library/Developer/Xcode/DerivedData/WebDriverAgent-hdeptzudnzkbzfbvrklbrfivfriw/Build/Intermediates.noindex/WebDriverAgent.build/Debug-maccatalyst/WebDriverAgentLib.build/Objects-normal/x86_64/XCUIDevice+FBHealthCheck.o /Applications/LazyOne.app/Contents/Resources/public/bat-wda/WebDriverAgentLib/Categories/XCUIDevice+FBHealthCheck.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
(1 failure)

Testing failed:
    No visible @interface for 'XCUIDevice' declares the selector 'pressButton:'
    Use of undeclared identifier 'XCUIDeviceButtonHome'
    Testing cancelled because the build failed.`

It's seem like the same problem...

**Comment by Jellyswat** [comment]
@KazuCocoa @mykola-mokhnach  
Hi~
Gently ask. Do we have any suggestion?

**Comment by KazuCocoa** [comment]
No idea, unfortunately. Did you use `build-for-testing test-without-building` to build, btw?

**Comment by evserykh** [comment]
I downgraded xcuitest driver to 4.12.0 and try the command: 
```
xcodebuild clean build-for-testing test-without-building -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=real-device-id'
```

Here is what I got:

```
** TEST BUILD FAILED **


The following commands produced analyzer issues:
        Analyze /Users/user/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgentLib/Utilities/FBClassChainQueryParser.m normal arm64 (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
(1 command with analyzer issues)

The following build commands failed:
        CodeSign /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-grkfbrzvpmnylxeyutthrhtnztqz/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
(1 failure)
Testing started
2023-04-21 07:19:46.058 xcodebuild[14301:649480] [MT] IDETestOperationsObserverDebug: 0.012 elapsed -- Testing started completed.
2023-04-21 07:19:46.058 xcodebuild[14301:649480] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2023-04-21 07:19:46.059 xcodebuild[14301:649480] [MT] IDETestOperationsObserverDebug: 0.012 sec, +0.012 sec -- end

Test session results, code coverage, and logs:
        /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-grkfbrzvpmnylxeyutthrhtnztqz/Logs/Test/Run-WebDriverAgentRunner-2023.04.21_07-18-08-+0000.xcresult

Testing failed:
        Command CodeSign failed with a nonzero exit code
        Test target WebDriverAgentRunner encountered an error (The bundle identifier for WebDriverAgentRunner-Runner.app couldn’t be read. The application may be damaged or incomplete: “/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-grkfbrzvpmnylxeyutthrhtnztqz/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app”.)

** TEST EXECUTE FAILED **
```

What do I miss?

**Comment by KazuCocoa** [comment]
How did you resolve the codesign? The error was not a build error, codesigning related e.g. https://appium.github.io/appium-xcuitest-driver/4.19/real-device-config/#basic-manual-configuration

**Comment by evserykh** [comment]
To be honest my setup is quite tricky. I use Linux PC with connected iPhone and run macOS using Docker (https://github.com/sickcodes/Docker-OSX) 🤷‍♂️ 

But I was able to fix the issue and run the simple test on the real device 🎉 

So I installed xcuitest 4.12.0. And set up certificates and signing munually and it did the trick

**Comment by KazuCocoa** [comment]
oh, i see.

`test` is an old method to run test, so Appium has been using `build-for-testing test-without-building`. Potentially `test` did not resolve dependencies properly.

**Comment by skbt27i** [comment]
In my case, developer mode was already on. We had to restart the phone and then clear trusted computers. Then we plugged it back into the mac and selected "Trust", and finally it worked
