### ISSUE TITLE
xcuitest: mobile: removeCertificate doesn't return anything

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18507]
Per the docs:

> Returns status acknowledgment `{'Status': 'Acknowledged'}` if successfully removed certificate or `None` if unable to remove certificate.

This is the implementation of the command:

https://github.com/appium/appium-xcuitest-driver/blob/5588d26e6f7f44cd70361d1ddaeebf97250110ec/lib/commands/certificate.js#L442-L460

This is the implementation of `Pyidevice.removeProfile()`:

https://github.com/appium/appium-xcuitest-driver/blob/5588d26e6f7f44cd70361d1ddaeebf97250110ec/lib/py-ios-device-client.js#L99-L101

As you can see, the latter returns `undefined`, which means the former also returns `undefined`.

This landed in appium/appium-xcuitest-driver#1529.

cc @joelwhitney

**Comment by mykola-mokhnach** [comment]
closed as fixed
