### ISSUE TITLE
typedoc-plugin-appium: link resolution problems in CommandDeclarations

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18508]
A `CommandDeclaration` is the data source for a command as displayed in the command reference docs.  These commands are declared within `newMethodMap`, but the implementation lives in a class or mixin.  The comments from the implementation are modified and copied into the `CommandDeclaration` for display in this context.

`{@link}` tags referencing other methods within the docstring of the method implementation work fine when rendering classes and methods, but generally fail when rendering `CommandDeclaration`s.  This is because the scope is used to determine the symbol being referenced.  For example, `XCUITestDriver.getSession` is a perfectly valid link target, but a `CommandDeclaration` knows nothing about `XCUITestDriver`.  In fact, the parent of a `CommandDeclaration` is the driver module itself--just like the main driver class.  

Unsure offhand the best way to address this; haven't looked at TypeDoc's link resolution implementation before.  Could possibly change the parent of the `CommandDeclaration`, make a reference that's currently broken, or manually determine or rewrite the link targets.

**Comment by mykola-mokhnach** [comment]
no plugin - no issues
