### ISSUE TITLE
AppleTV-TVOS 16.4 - Xcode build failure 70

### ISSUE THREAD

**Issue by pmsviacom** [appium/appium#18517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This issue is throwing when my TVOS got updated to 16.4, having latest version of Xcode 14.3 and Appium 2.0.0 beta 62. XuiTest- 4.21.28. The app launches intermittently when invoked via appium inspector as well as through scripts after device unpair and pair, but not all time. Xcode project built successfully and upon testing(Product->Test), the wda launches properly. 
Unable to see a permanent way to fix for this for automation run.

Adding the error details from the Script:-
_Driver info: driver.version: AppiumDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
xcodebuild error message:
. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.

at getResponseForW3CError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1067:9)*
at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)*
at runNextTicks (node:internal/process/task_queues:60:5)*
at processImmediate (node:internal/timers:446:9)_

Tried multiple times the suggestions given as per the error message and still seeing error. Request to identify and fix the issue.

Adding references of the previously addressed ones:-
https://developer.apple.com/forums/thread/715187
https://discuss.appium.io/t/unable-to-launch-webdriveragent-because-of-xcodebuild-failure-xcodebuild-failed-with-code-70/37366
https://github.com/appium/appium/issues/17896 

### Expected Behavior

The App under test should be launched successfully without any errors

### Minimal Reproducible Example

[debug] [XCUITestDriver@272b (c8702132)] Matched '/status' to command name 'getStatus'
[debug] [XCUITestDriver@272b (c8702132)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [iProxy@de07529a:8100] Unexpected data: {"header":{"length":294,"version":1,"type":8,"tag":1},"payload":{"MessageType":"Result","Number":2}}
[XCUITestDriver@272b (c8702132)] socket hang up
[debug] [XCUITestDriver@272b (c8702132)] Matched '/status' to command name 'getStatus'
[debug] [XCUITestDriver@272b (c8702132)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [iProxy@de07529a:8100] Unexpected data: {"header":{"length":294,"version":1,"type":8,"tag":1},"payload":{"MessageType":"Result","Number":2}}
[XCUITestDriver@272b (c8702132)] socket hang up
[Xcode] xcodebuild exited with code '70' and signal 'null'
[debug] [XCUITestDriver@272b (c8702132)] Event 'wdaStartFailed' logged at 1681464084472 (14:51:24 GMT+0530 (India Standard Time))
[debug] [XCUITestDriver@272b (c8702132)] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
[debug] [XCUITestDriver@272b (c8702132)] xcodebuild error message:
[debug] [XCUITestDriver@272b (c8702132)] . Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITestDriver@272b (c8702132)] Quitting and uninstalling WebDriverAgent
[XCUITestDriver@272b (c8702132)] Shutting down sub-processes
[debug] [XCUITestDriver@272b (c8702132)] No WDAs on the device.
[XCUITestDriver@272b (c8702132)] {}
[DevCon Factory] Releasing connections for de07529aac56d1337651bab0c5a0ec8093f5447b device on any port number
[DevCon Factory] Found cached connections to release: ["de07529aac56d1337651bab0c5a0ec8093f5447b:8100"]
[DevCon Factory] Releasing the listener for 'de07529aac56d1337651bab0c5a0ec8093f5447b:8100'
[debug] [iProxy@de07529a:8100] Closing the connection
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITestDriver@272b (c8702132)] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iProxy@de07529a:8100] The connection has been closed
[debug] [AppiumDriver@ca01] Event 'newSessionStarted' logged at 1681464084730 (14:51:24 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@ca01] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70

### Environment

- Operating system: MAC OS Ventura 13.2.1
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version: 2023.3.1
- Appium driver(s) and their version(s): 2.0.0 beta 62
- Appium plugin(s) and their version(s):
- Platform and version under test: TVOS 16.4
- Real device or emulator/simulator: Real Device

**Comment by mykola-mokhnach** [comment]
Could you please attach the full server log with xcodebuild logging capability enabled?

**Comment by pmsviacom** [comment]
attaching the server log for more details, please let me know if anything further needed.
https://gist.github.com/pmsviacom/5b4295f18db61b98521462e3241190c6

Thanks

**Comment by mykola-mokhnach** [comment]
Unfortunately the attached log does not contain xcodebuild output. Make sure to set showXcodeLog capability to true

**Comment by pmsviacom** [comment]
Hello @mykola-mokhnach , Sorry for the delay..
I have added the ShowXcodeLog cap and the execution logs attached in the gist. Please review
https://gist.github.com/pmsviacom/ce5b812cc038aa8af77aeb1cd699731b
Thanks

**Comment by mykola-mokhnach** [comment]
> [Xcode] --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> [Xcode] { platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Any tvOS Device }
> [Xcode] { platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Any tvOS Simulator Device }
> [Xcode] { platform:tvOS, id:de07529aac56d1337651bab0c5a0ec8093f5447b, name:Bedroom }
> [Xcode] { platform:tvOS Simulator, id:A15ACA45-CD25-4D5E-9B8D-16B8A4EBE250, OS:16.4, name:Apple TV }
> [Xcode] { platform:tvOS Simulator, id:A15ACA45-CD25-4D5E-9B8D-16B8A4EBE250, OS:16.4, name:Apple TV }
> [Xcode] { platform:tvOS Simulator, id:6F4F3A69-4F31-4E35-818D-8A6D1C5BFB15, OS:16.4, name:Apple TV 4K (3rd generation) }
> [Xcode] { platform:tvOS Simulator, id:6F4F3A69-4F31-4E35-818D-8A6D1C5BFB15, OS:16.4, name:Apple TV 4K (3rd generation) }
> [Xcode] { platform:tvOS Simulator, id:BD71A5A8-7395-4F0C-9AC4-B2F5E1762B95, OS:16.4, name:Apple TV 4K (3rd generation) (at 1080p) }
> [Xcode] { platform:tvOS Simulator, id:BD71A5A8-7395-4F0C-9AC4-B2F5E1762B95, OS:16.4, name:Apple TV 4K (3rd generation) (at 1080p) }


This is probably your issue. Try to provide the destination device udid instead of deviceName, which is not used there

**Comment by pmsviacom** [comment]
Hello @mykola-mokhnach ,

I have removed the device name and kept the udid as it is. But the issue is still persists.
adding the gist logs again for review - https://gist.github.com/pmsviacom/51158858d69757a907a5e0da29c1cb1f

As you mentioned, it can be some device detection issue between xcode and wda.

**Comment by mykola-mokhnach** [comment]
Like I said it is more an Xcode issue that something we can fix. Does the below command work if executed manually?

xcodebuild build-for-testing test-without-building -project /Users/784968/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner_tvOS -destination id=de07529aac56d1337651bab0c5a0ec8093f5447b GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO

**Comment by pmsviacom** [comment]
Executed the command and seeing the same error. Can you please tell me how to reach out to Xcode support as call support tech team did not provide any much details about this issue.

xcodebuild[32174:142501] Writing error result bundle to /var/folders/jw/_ckhvky90rn4t8jn45f1j9p00000gq/T/ResultBundle_2023-18-04_09-28-0002.xcresult
xcodebuild: error: Failed to build project WebDriverAgent with scheme WebDriverAgentRunner_tvOS.: Cannot test target “WebDriverAgentRunner_tvOS” on “Any tvOS Device”: Tests must be run on a concrete device

**Comment by KazuCocoa** [comment]
The message generally means the xcodebuild itself failed t o find the device. Hm.. then probably nothing can do so much in Appium side unfortunately as xcodebuild internal.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by JoelWhitney** [comment]
I am all of a sudden seeing [this](https://github.com/appium/appium/issues/18517#issuecomment-1512409060) issue as well. I only had an issue starting test on this device after updating my Apple TV and Xcode. I'm going to see if I can revert Xcode versions to narrow down the issue. 

What's interesting is I can test the `WebDriverAgentRunner_tvOS` scheme on the device from Xcode UI without issue, so it seems like there is a difference between how Xcode starts the test verse Appium and the command below:
`xcodebuild test-without-building -allowProvisioningUpdates -allowProvisioningDeviceRegistration -project $HOME/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner_tvOS -derivedDataPath $HOME/Library/Developer/Xcode/DerivedData/WebDriverAgent-00008110-000E2C160C01401E -destination id=00008110-000E2C160C01401E TVOS_DEPLOYMENT_TARGET=16.5 -xcconfig /var/folders/z_/2prs3wt52sl2c082p0vtkz2h0000gp/T/2023513-63976-7zjs4w.dmy5n/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO`

**Comment by JoelWhitney** [comment]
FWIW I was able to successfully start the test by reverting Xcode-14.3 -> Xcode-14.0.1

**Comment by pmsviacom** [comment]
Hi, i contacted Apple Tech support reg this issue and as per them, i may need to update and try in xcode 15 beta. 
But when i try to open the web driver agent project in xcode beta 15, not able to build the project due to the following error.

.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/PrivateHeaders/XCTest/XCTestCase.h:54:42 Parameter of overriding method should be annotated with __attribute__((noescape))

Request to help on this to fix.
CC: @mykola-mokhnach , @KazuCocoa

**Comment by KazuCocoa** [comment]
Please use the latest xcuitest driver

**Comment by kandji-joel** [comment]
For more context, the device I was having trouble working with was an Apple TV 4K paired to the host machine over my WiFi network. I had a lot of issues starting WDA on the network device reliably (Apple TV HD connected via USB has never had any issues).

I ultimately found that if you leave the Apple TV 4K on the `General > Remotes and Devices > Remote App and Devices` screen otherwise the device would fail to connect to from xcodebuild 🤷
