### ISSUE TITLE
ElementId changes for the same element

### ISSUE THREAD

**Issue by rafi4135** [appium/appium#18521]
Is there an existing issue for this?

- I have searched the existing issues

### Current Behavior
Element id for the same element changes in the same session

### Expected Behavior
Element id should remain same to uniquely identify elements

### Minimal Reproducible Example
1. Turn on appium server
2. Connect android mobile
3. Turn on appium inspector
4. Open samsung contacts app
5. Click on create contact element
6. Select Save button and check its elementId attribute from appium inspector
7. Click on Save button
8. Again, click on create contact element
9. Select Save button and check its elementId attribute from appium inspector
10. See that the elementId has changed

### Environment
Operating system: Windows 10
Appium Server: Appium-Server-GUI-windows-1.22.3-4
Appium Inspector: Appium-Inspector-windows-2022.5.4
Platform and version under test: Android 12
Real device or emulator/simulator: Real device

### Link to Appium Logs
No response

### Futher Information
No response

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description according to the given template

**Comment by rafi4135** [comment]
> Please provide a proper issue description according to the given template

I have modified the issue description according to the given template

**Comment by mykola-mokhnach** [comment]
The server log is still missing. Also, we do not support Appium 1 anymore. Please use the latest version of UIA2 driver supplied with Appium2

**Comment by jlipps** [comment]
In general there is no guarantee that subsequent retrievals of the same element will result in the same id. You should never check element equality by comparing ids. There is an element equality check command for that purpose instead.

**Comment by jlipps** [comment]
Hmm I guess that command got removed from the w3c spec. What are you trying to do with this equals check anyway?

**Comment by rafi4135** [comment]
> Hmm I guess that command got removed from the w3c spec. What are you trying to do with this equals check anyway?

I am trying to generate menu tree of an app. For that, trying to omit the same element afterwards

**Comment by jlipps** [comment]
If you want to generate a tree based on the UI hierarchy, you're better off just getting the html source and using an xml parser. Otherwise you'll never have any guarantee that the elements you find are all on the screen at the same time.

**Comment by rafi4135** [comment]
> If you want to generate a tree based on the UI hierarchy, you're better off just getting the html source and using an xml parser. Otherwise you'll never have any guarantee that the elements you find are all on the screen at the same time.

I am using an xml parser. Problem is, sometimes some new elements appear after a click, like clicking on a radio button opens some new elements, I have to omit the previous elements and add those new elements under the clicked element. But i am not able to identify the previous elements as there is no sure unique identifier for each element

**Comment by jlipps** [comment]
yeah in that case you'll need to use some other unique fact about the element, like its menu text

**Comment by rafi4135** [comment]
> yeah in that case you'll need to use some other unique fact about the element, like its menu text

I am using combination of text, resource-id, class and content-desc of each element. Still sometimes, there are other unique elements with the same combination. I can't assure it's uniqueness

**Comment by jlipps** [comment]
in that case, how could a user determine its uniqueness?

**Comment by rafi4135** [comment]
I am not sure how uniqueness can be determined

**Comment by jlipps** [comment]
In that case I think you are probably out of luck. There may be another strategy for doing what you want to do.
