### ISSUE TITLE
[Feat]: startRecordingScreen is not recording more than 3 minutes

### ISSUE THREAD

**Issue by shreyansh791** [appium/appium#18548]
**Is your feature request related to a problem? Please describe.**
startRecordingScreen should record more than 3 minutes depending upon the no of minutes provided.
      ((CanRecordScreen) getDriver()).startRecordingScreen(
                new AndroidStartScreenRecordingOptions().withVideoSize("1280x720")
                        .withTimeLimit(Duration.ofMinutes(5)));

**Describe the solution you'd like**
A clear and concise description of what you want to happen. startRecordingScreen should record more than 3 minutes depending upon the no of minutes provided.

**Describe alternatives you've considered**

**Additional context**

**Comment by mykola-mokhnach** [comment]
Please provide the requested information along with the full server log

**Comment by mykola-mokhnach** [comment]
Closed because of no response
