### ISSUE TITLE
feature request (appium-uiautomator2-driver): ability to provide axios timeout in stopMediaProjectionRecording

### ISSUE THREAD

**Issue by mohanjith** [appium/appium#18549]
Uploading 45-minute screen recording to S3 can take longer than 4 minutes. It would be ideal if axios timeout can be provided in stopMediaProjectionRecording command.

**Comment by mykola-mokhnach** [comment]
Makes sense. You are welcome to create a PR @mohanjith if you have time

**Comment by mohanjith** [comment]
I believe the change is only needed in documentation in appium-android-driver. Does the read me automatically get generated?

**Comment by mykola-mokhnach** [comment]
> I believe the change is only needed in documentation in appium-android-driver. Does the read me automatically get generated?

Where exactly? A link to the actual code would be useful.

In general android-driver is used as a common code storage for uia2 and espresso driver, so we only document things in these two driver repositories

**Comment by mohanjith** [comment]
PR made, not sure whether I need to update the appium-uiautomator2-driver README.md or whether that will be automatically updated.

**Comment by mykola-mokhnach** [comment]
Yes, you'll need to bump the minimum version of appium-android-driver and update the README manually. @boneskull is currently working on a solution which would allow to autogenerate the markdown based on docstrings in the future.

**Comment by mohanjith** [comment]
I'll make a new PR when the appium-android-driver is released

**Comment by mykola-mokhnach** [comment]
I've merged the PR, so it will be published automatically in a while.

also, I have renamed the actual parameter to `uploadTimeout` to not mix it with media-recording-specific options

**Comment by mohanjith** [comment]
It looks like pipelines failed.

**Comment by mykola-mokhnach** [comment]
Closed as fixed. Thanks @mohanjith
