### ISSUE TITLE
appium-adb: is it possible to set adb log level?

### ISSUE THREAD

**Issue by mitsukuri** [appium/appium#18544]
As it currently stands, `ADB.createADB ()` always logs these three lines:
```
info ADB Found 1 'build-tools' folders under '<my $ANDROID_HOME>' (newest first):
info ADB     <my build-tools path>
info ADB Using 'adb' from '<my platform-tools path>'
```
Is it possible to set adb log level to error only or disable completely?

**Comment by mykola-mokhnach** [comment]
this module uses the logger imported from `@appium/support`, which runs on top of npmlog. So, it would be logical to assume it could be configured same way the server normally does it: https://github.com/appium/appium/blob/b9ef676b73a0542a7895e74db0a709c1650eba26/packages/appium/lib/logsink.js#L204

Please use appium forum to ask questions
