### ISSUE TITLE
bug: Can't start device-farm for iOS

### ISSUE THREAD

**Issue by tking16** [appium/appium#18545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting Appium device farm when setting platform to `ios` will fail to execute, giving: `Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: ENOENT: no such file or directory, scandir '/Users/theo.king/code/testing/app-at/node_modules/appium-device-farm/node_modules/go-ios/dist/'`

### Expected Behavior

Appium runs, works when setting platform to `android`, I have it set to `both` which is failing

### Minimal Reproducible Example

https://github.com/tking16/SampleProj-deviceFarm

### Environment

- Operating system: 13.2.1 (22D68)
  - appium 2.0.0-beta.65
  - Node.js version (output of `node --version`):  v19.5.0
  - `npm` version (output of `npm --version`):  9.3.1
- Appium driver(s) and their version(s):
    - xcuitest@4.23.0 [installed (npm)]
    - uiautomator2@2.15.0 [installed (npm)]
- Appium plugin(s) and their version(s):
    - "appium-device-farm": "^7.2.0"
    - "appium-dashboard": "2.0.2"

### Link to Appium Logs

https://gist.github.com/tking16/70e6943c22af5f9e555105298259b0bf

**Comment by mykola-mokhnach** [comment]
This error is thrown by the device farm plugin. Please report your issue to plugin maintainers.

**Comment by tking16** [comment]
@mykola-mokhnach sorry I had multiple tabs open and have just posted to the completely wrong repo 🤣 apologies
