### ISSUE TITLE
Is there a way to set SystemDate for both iOS and Android?

### ISSUE THREAD

**Issue by yerokhinoleksii** [appium/appium#18552]
Some of my tests involve changing system data, i.e. adding 1 day (simple example). 
Is there a way to set SystemDate for both iOS and Android?

**Comment by KazuCocoa** [comment]
Perhaps you should do it via UI. For Android, it maybe can via adb (with root), but no method for iOS at least.

https://discuss.appium.io/ may also help to ask some possible ways.
