### ISSUE TITLE
CountingIdlingResource for Espresso

### ISSUE THREAD

**Issue by kerenpas** [appium/appium#18550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

not to get the error: org.openqa.selenium.InvalidElementStateExceptio

### Expected Behavior

I am using Appium with an Espresso driver to test an Android app. In one of my tests I am getting this error: org.openqa.selenium.InvalidElementStateException: The application is expected to be in idle state in order for Espresso to interact with it. Review the threads dump below to know more on which entity is hogging the events loop ThreadName: main: State: RUNNABLE
in this video the https://www.youtube.com/watch?v=gU9EEUV5n9U there is a solution to this problem using the androidx.test.espresso.idling.CountingIdlingResource But how can I access the CountingIdlingResource in the app code from my Appium test code? can someone get this problem and can give me some code examples, of how to do it?

### Minimal Reproducible Example

can not add code 

### Environment

Real device. Appium Server 2.0. Android 13
Espresso driver 2.15.4

**Comment by mykola-mokhnach** [comment]
Looks like nobody knows here. Maybe try asking at Appium forum
