### ISSUE TITLE
self.driver.execute_script("mobile:deviceInfo").get('model') no longer works?

### ISSUE THREAD

**Issue by tking16** [appium/appium#18551]
I have a test that checks if the device is an iPad using the function in the title. I've recently updated and now I get `Method is not Implemented`?

```
E       selenium.common.exceptions.WebDriverException: Message: Method is not implemented
E       Stacktrace:
E       NotImplementedError: Method is not implemented
E           at XCUITestDriver.execute (/Users/theo.king/code/xxx/testing/app-at/node_modules/appium-xcuitest-driver/lib/commands/execute.js:122:13)
```

I checked the release notes of latest versions for both Appium and XCUITestDriver, couldn't see anything related (I've tested 2.0.0-beta.63,62,60, doesn't work)

The last working version I can find is 2.0.0-beta.46 (xcuitestdriver: 4.18.0)

Did I miss some documentation? What do we use instead now?

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by mykola-mokhnach** [comment]
does it work if you add one space after the colon?

**Comment by tking16** [comment]
I have other tests failing on this version but due to something different, the error states `E       selenium.common.exceptions.StaleElementReferenceException: Message: The element identified by "null" is either not present or it has expired from the internal cache. Try to find it again`, works perfectly fine on older versions. If I can't figure out what's going on I'll raise a new issue

**Comment by boneskull** [comment]
@tking16 can you please provide a log?

**Comment by boneskull** [comment]
does it work if you put a space after `mobile:`? 

maybe we can allow that for now but deprecate the behavior? @jlipps

**Comment by tking16** [comment]
Yeah it does work with a space, I just undid the change to grab the logs 🙂
