### ISSUE TITLE
UiAutomator2 dont see the hint or label on flutter widget

### ISSUE THREAD

**Issue by nazarenkod** [appium/appium#18568]
I have a hybrid app (native + flutter).
From Flutter version 3.3.10+ UiAutomator2 stopped recognizing placeholder, labels, or hints on flutter screens. 
As flutter devs said - they update some code for Talkback and VoiceAccess features. 
Please, can u help? 

**Example flutter code to reproduce:**

```
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    const appTitle = 'Form Styling Demo';
    return MaterialApp(
      title: appTitle,

      home: Scaffold(
        appBar: AppBar(
          title: const Text(appTitle),
        ),
        body: const MyCustomForm(),
      ),
    );
  }
}

class MyCustomForm extends StatelessWidget {
  const MyCustomForm({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        const Padding(
          padding: EdgeInsets.symmetric(horizontal: 8, vertical: 16),
          child: TextField(
            decoration: InputDecoration(
              hintStyle: TextStyle(fontSize: 20.0, color: Colors.redAccent),
              hintText: 'Enter a search term',
            ),
          ),
        ),
      ],
    );
  }
}
```
**Steps to reproduce:**

1. Install Flutter 3.7.10 (or any other after 3.3.10)
2. Build a flutter app from the sample (or any code which includes TextField with hintText)
3. Analizy UI with appium inspector

**Actual result:** hint text is absent
Screenshot from Flutter version 3.7.10
<img width="1601" alt="actual" src="https://user-images.githubusercontent.com/13256486/234060391-2bb32889-bd3b-4720-a065-735d7fb1ae37.png">

**Expected result:** hint text is present
Screenshot from Flutter version 3.3.10
<img width="1392" alt="expected" src="https://user-images.githubusercontent.com/13256486/234060425-0d632a2c-e1ea-48bb-a22b-1de68b8b833f.png">

Link to flutter [issue](https://github.com/flutter/flutter/issues/124493)

**Comment by mykola-mokhnach** [comment]
It is possible to fetch element hint as attribute value on Android O and above, it is not exposed to the page source xml though:  

https://github.com/appium/appium-uiautomator2-server/blob/a800c9c94590174ded8f3da5b69e2bfa42eef207/app/src/main/java/io/appium/uiautomator2/model/UiObject2Element.java#L137

**Comment by nazarenkod** [comment]
@mykola-mokhnach 
ok, thanks, I will try.
Maybe u can recommend any other solution in appium to test hybrid (native + flutter) apps? 
Now, trying to use flutter driver, but seems like it is not working well

**Comment by supertgtline** [comment]
With flutter we should user appium-flutter-driver
