### ISSUE TITLE
bug: JavaScript heap out of memory

### ISSUE THREAD

**Issue by eyJhb** [appium/appium#18566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running Appium w/ WebDriverAgent on a real device, stopped running after three days (ran from the 14th to the 17th this month), with a JavaScript heap out of memory error.

### Expected Behavior

For Appium not to encounter JavaScript heap out of memory error/crash.

### Minimal Reproducible Example

I have none. Just clicking around in apps for a long time.

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.58
  - Node.js version (output of `node --version`): v18.12.1
  - `npm` version (output of `npm --version`): 8.19.2
  - Last `appium` version which did _not_ exhibit the problem: ?
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): - xcuitest@4.21.1 [installed (npm)]
- Appium plugin(s) and their version(s): go-ios (gist attached later)
- Platform and version under test: iOS 16.4.1
- Real device or emulator/simulator: real device

### Link to Appium Logs

https://gist.github.com/eyJhb/538bfcbeb8e17f37abe714c5d9e0f5c8
https://gist.github.com/eyJhb/de715c1ccfd8f2614841b33d9be0af2a

### Futher Information

I am using this custom plugin, that I've written to automate the `go-ios` part of my setup.
I can't really see anything in here, that should leak, but I might be wrong -> https://gist.github.com/eyJhb/02d21807e51795b5f0b0ecf25c1fc2ea (shouldn't be seen as me trying to ask for a code review, but rather give the  complete picture).

EDIT: added more logs, didn't catch it before it went under

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot help much without having the heap snapshot

**Comment by eyJhb** [comment]
How would I be able to acquire that? Can I set it to dump it on failure? :)

**Comment by eyJhb** [comment]
Perfect, I'll try that.
Also, is there a limit to how many sessions can be open in Appium at any time?

**Comment by mykola-mokhnach** [comment]
> Perfect, I'll try that.
> Also, is there a limit to how many sessions can be open in Appium at any time?

Nothing I know of. The amount is only limited by the available Node memory heap space

**Comment by eyJhb** [comment]
Perfect, I'll try running it and see if I get the same issue again.
I suspect, that it might be because I created too many sessions, but not quite sure.

But I'll try to report back in a week or so, as it takes a long time before the error occurs :) Thank you

**Comment by eyJhb** [comment]
I didn't catch it using the method in the issue thread, however I got a bunch of heap snapshots by using the `-heapsnapshot-near-heap-limit=20` command (170GB worth of snapshots, didn't realize the size).

Here is the 1st and 20th snapshots

- [Heap.20230429.051938.3332135.0.001.heapsnapshot.xz](https://www.mediafire.com/file/c6sqi85fcffq8e4/Heap.20230429.051938.3332135.0.001.heapsnapshot.xz/file)
- [Heap.20230429.073515.3332135.0.020.heapsnapshot.xz](https://www.mediafire.com/file/zvxh65d9fgxx4d5/Heap.20230429.073515.3332135.0.020.heapsnapshot.xz/file)

I am unsure how long these links will live. But, if they die I can upload them once more.
I've compressed them as good as I can, hopefully it's enough.

Are these files okay @mykola-mokhnach, and can you use them?

**Comment by mykola-mokhnach** [comment]
Unfortunately Chrome refuses to load such a huge snapshot

**Comment by eyJhb** [comment]
Yeah, same thing happened for me. I hoped it was just my Chrome install being funky.

Would it work, if I let the Appium server run for lets say, a day or something, could that reveal anything?

**Comment by eyJhb** [comment]
I've gotten another snapshot, after running for ~1 day. I can grap another tomorrow, when it has run for ~2 days, if nothing is shown atm. I am unsure when it crashes, but I think it is mostly after 3 days or so and I am not at the computer when it does, sadly.

[Heap.20230502.074015.2849825.0.001.heapsnapshot.xz](https://www.mediafire.com/file/yguptrudlh4gdit/Heap.20230502.074015.2849825.0.001.heapsnapshot.xz/file)

**Comment by mykola-mokhnach** [comment]
Unfortunately Chrome Inspector is unable to load the above one as well

**Comment by eyJhb** [comment]
What about the previous one? Does that give any indication? 

I wonder what the limit of Google Chrome is.

**Comment by mykola-mokhnach** [comment]
You can easily try it yourself: https://nodejs.org/en/docs/guides/diagnostics/memory/using-heap-snapshot#how-to-find-a-memory-leak-with-heap-snapshots

**Comment by eyJhb** [comment]
I've token two new snapshots

- https://www.mediafire.com/file/fx29pzturgx23ee/Heap.20230510.085549.631414.0.001.heapsnapshot.xz/file
- https://www.mediafire.com/file/mf3lj3g39jha99t/Heap.20230510.150804.631414.0.002.heapsnapshot.xz/file

Both load in Chrome just fine.

I've tried to use the link you sent, but I still find it hard to find the cause.
I can see a lot of concatenated string, and quite a few new objects created. 

![imgur-2023_05_11-08:44:43](https://github.com/appium/appium/assets/25955146/9ea87d68-817a-48cc-bb8d-df9f5786d0c9)

**Comment by mykola-mokhnach** [comment]
Do you have iPhone device logs enabled? Try to disable them and then check the memory usage again

**Comment by eyJhb** [comment]
I don't explicitly enable them, so I will try to find the disable flag somewhere, and do that :)

**Comment by mykola-mokhnach** [comment]
The patch has been released in xcuitest driver 4.27.1. 
Please test it locally and provide the updated memory snapshot if memory issues are still being observed

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by eyJhb** [comment]
Still testing. There have been holidays here in Denmark :)

**Comment by eyJhb** [comment]
@mykola-mokhnach restarting my test now, and checking again this friday.

**Comment by eyJhb** [comment]
And... I have to restart the test because I tested #18641

**Comment by eyJhb** [comment]
been running for 9 days now, without any issue. Thanks! :)
