### ISSUE TITLE
Is there still a way to run WebDriveAgent on ios 10?

### ISSUE THREAD

**Issue by Dimpagger** [appium/appium#18573]
I use the latest version of WebDriveAgent and run it on a M1 Pro Macbook Pro / M1 Macmini with Xcode 14.2, every time I try to install wda to an ios 10.x device, show this dialog:
<img width="260" alt="image" src="https://user-images.githubusercontent.com/4070286/234461732-c6100470-29dc-41e1-a706-19f8c1487c27.png">

This is my test env:
* M1 Pro Macbook Pro / M1 Macmini 
* Xcode 14.2
* ios 10.x [iphone7 with ios 10.1.1, iphone7 with ios 10.0.2, iphone7 with ios 10.3.2, iphoneSE with ios 10.3.3]
* WebDriveAgent 4.13.1

I change the "Deployment Info", "Minimum Deployments" config in TARGETS, but have no effect.

Is there still a way to run WDA on ios 10, how can I do this ?

**Comment by KazuCocoa** [comment]
I think no in newer Xcode environment.

The version support was dropped around appium 1.20.0. The only way is probably to prepare an WDA app with loser Xcode version with lower Appium.
https://appium.github.io/appium-xcuitest-driver/4.19/real-device-config/#build-for-generic-iostvos-devices-run-manually may help.
