### ISSUE TITLE
Test open with functionality in Mobile

### ISSUE THREAD

**Issue by NiladriPadhy** [appium/appium#18583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have built a document viewer mobile app for both Android and iOS. Whenever user select a file, if my app supports that file, then in open with context menu my app will be populated. As soon as user selects that file, then that file will be opened in my viewer app.

Which appium script I need to write to test above scenario?

### Expected Behavior

Need some sample appium script to test the above file.

### Minimal Reproducible Example

Need some sample appium script to test the above file.

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask question. This is the place for issues
