### ISSUE TITLE
bug: <title>Capabilities appium:noReset is not working on Android with Appium 2x.

### ISSUE THREAD

**Issue by KRNM7** [appium/appium#18595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Before my update to Appium 2x, the noReset=False would restart the app to it's default state without reinstalling after each def test function. 

### Expected Behavior

noReset=False should restart the app to it's default state after each def test function. Not keep the app at it's last screen or state.

### Minimal Reproducible Example

appium:noReset = False

### Environment

- Operating system:  Mac OS Big Sur
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): Appium 2.0.0-beta.64
  - Node.js version (output of `node --version`): v19.8.1
  - `npm` version (output of `npm --version`): 9.5.1
  - Last `appium` version which did _not_ exhibit the problem: Appium 1x
- If running Appium Desktop, its version: v1.22.0
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test: Android Studio Dolphin 2021.3.1 Patch 1
- Real device or emulator/simulator: Emulator Pixel 6 Pro API R Android 11.0 Google API x86_64

### Futher Information

I tried FullReset. But it reinstalls the app which is not what I need. I also tried different combinations of capabilities like AutolaunchApp, etc, and none worked.

**Comment by amedvedjev** [comment]
see https://github.com/appium/appium/issues/17594
now you need add `forceAppLaunch` = true

**Comment by Haibo-Zhou** [comment]
> see #17594 now you need add `forceAppLaunch` = true

Thanks, keep app cache needs this 2 lines together.

```
"noReset": "true",
"forceAppLaunch": "true"
```
