### ISSUE TITLE
[Feat]: Add "focused" attribute for iOS in XCUITest driver

### ISSUE THREAD

**Issue by jacky-dave** [appium/appium#18600]
**Is your feature request related to a problem? Please describe.**
- Driver: `XCUITest driver`
- OS: `iOS`
- Appium version: `2.0.0-beta.61`
- Issue:

Trying to get element's attribute "focused" but getting following error 
```
unknown error: An unknown server-side error occurred while processing the command. 
Original error: The attribute 'focused' is unknown. Valid attribute names are: (
    UID,
    accessibilityContainer,
    accessible,
    enabled,
    frame,
    index,
    label,
    name,
    rect,
    selected,
    type,
    value,
    visible,
    wdAccessibilityContainer,
    wdAccessible,
    wdEnabled,
    wdFrame,
    wdIndex,
    wdLabel,
    wdName,
    wdRect,
    wdSelected,
    wdType,
    wdUID,
    wdValue,
    wdVisible
)
```

**Describe the solution you'd like**
Would like to support getting "focused" element attribute for iOS testing

**Additional context:**
Based on the documentation of Appium https://appium.github.io/appium-xcuitest-driver/4.24/element-attributes/, focused seems only supported for tvOS in XCUITest driver.

**Comment by mykola-mokhnach** [comment]
I'll add a separate field to reflect https://developer.apple.com/documentation/xctest/xcuielementattributes/1627636-hasfocus?language=objc value

**Comment by mykola-mokhnach** [comment]
the attribute has been added

**Comment by shubham0803** [comment]
@mykola-mokhnach We tried running our test (which makes use of `focused` attribute) on WebdriverAgent-Runner 4.15.0  but we are still getting the same error on iOS - 

```
unknown error: An unknown server-side error occurred while processing the command. Original error: The attribute 'isFocused' is unknown. Valid attribute names are: (
    UID,
    accessibilityContainer,
    accessible,
    enabled,
    frame,
    index,
    label,
    name,
    rect,
    selected,
    type,
    value,
    visible,
    wdAccessibilityContainer,
    wdAccessible,
    wdEnabled,
    wdFrame,
    wdIndex,
    wdLabel,
    wdName,
    wdRect,
    wdSelected,
    wdType,
    wdUID,
    wdValue,
    wdVisible
)
```

Do we need to upgrade any library in package.json or is there anything else we are missing ? Please do needful here
cc: @jacky-dave

**Comment by hdesai-dave** [comment]
@mykola-mokhnach `$('id=textInput').getAttribute('focused');` always returns false even though the textInput changes border color on the UI.

**Comment by KazuCocoa** [comment]
it seems like XCTest framework itself behaves so. In my past testing https://github.com/appium/WebDriverAgent/pull/692#issuecomment-1532112724, tvOS env returned expected true/false but iOS env returned false always. (not Appium/WDA specific at that time)

**Comment by hdesai-dave** [comment]
@KazuCocoa maybe hasKeyboardFocus you mention https://github.com/appium/WebDriverAgent/pull/692#issuecomment-1532102963 would work. We have a text input and once user taps into it we give a green border and cursor shows up green as well. We would like to verify it in iOS. Android works fine.
