### ISSUE TITLE
bug: Its process com.apple.mobilesafari does not exist in the list of Simulator processes

### ISSUE THREAD

**Issue by AvallaSD** [appium/appium#18604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After launching test on iPhone Simulator I face the error

`OpenQA.Selenium.WebDriverException: 'An unknown server-side error occurred while processing the command. Original error: Mobile Safari cannot open 'http://0.0.0.0:4723/welcome' after 25.351s. Its process com.apple.mobilesafari does not exist in the list of Simulator processes'`

Browser is opened on Simulator, when error happens

![image](https://user-images.githubusercontent.com/60776606/235881351-950d3c5b-7912-47c4-9480-2284f935551b.png)

### Expected Behavior

I expected to create Driver instance in my C# code, but fased this error

### Minimal Reproducible Example

Here is my capabilities
https://gist.github.com/AvallaSD/ac4197152f3e8bf3031ff91a67140c68.js
https://gist.github.com/AvallaSD/d50f0ecdbb6ce8ae8620f095593c8d7c.js

### Environment

- Operating system:  macOS Ventura 13.2.1
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.66
  - Node.js version (output of `node --version`): v18.16.0
  - `npm` version (output of `npm --version`): 9.5.1
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version: 1.22.3-4
- Appium driver(s) and their version(s): xcuitest@4.25.0
- Appium plugin(s) and their version(s):
- Platform and version under test: iPhone 14 Plus iOS 16.4
- Real device or emulator/simulator: Simulator

### Link to Appium Logs

https://gist.github.com/AvallaSD/1e700ed940df70c1ab36f15bebd6a6ae

**Comment by KazuCocoa** [comment]
Could you try with latest Appium/XCUITest driver?

From the attached appium log:

> [info] [35m[Appium][39m Welcome to Appium v1.22.3
> [info] [35m[Appium][39m Non-default server args:
> [info] [35m[Appium][39m   relaxedSecurityEnabled: true
> [info] [35m[Appium][39m   allowInsecure: {
> [info] [35m[Appium][39m   }
