### ISSUE TITLE
bug: Documentation error in README.MD for appium-uiautomator2-driver 

### ISSUE THREAD

**Issue by PHYSI6** [appium/appium#18606]
- [x] I have searched the existing issues

### Current Behavior

In description README.MD for appium-uiautomator2-driver in Settings API "ignoreUnimportantViews" the default value is true, but in the source code is false
![image](https://user-images.githubusercontent.com/71766321/235923164-71cdee73-f4f6-433e-99e8-69aa80eef84c.png)
![image](https://user-images.githubusercontent.com/71766321/235923190-496f22ff-b10d-41e5-b70e-9a6de6a4d12e.png)

### Expected Behavior

"ignoreUnimportantViews" the default value in documentation is false

### Minimal Reproducible Example

1. Open https://github.com/appium/appium-uiautomator2-driver#readme
2. Scroll to Settings API

### Futher Information

https://github.com/appium/appium-uiautomator2-driver#readme

**Comment by jlipps** [comment]
@PHYSI6 want to create a simple PR to update the documentation to reflect the code?

**Comment by PHYSI6** [comment]
> @PHYSI6 want to create a simple PR to update the documentation to reflect the code?

Sure
