### ISSUE TITLE
compareImages is not a function 

### ISSUE THREAD

**Issue by andwaee** [appium/appium#18616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am getting 'compareImages is not a function' even though I successfully setup everything below.

-appium plugin install images
-appium --use-plugins=images
-npm i @appium/images-plugin

### Expected Behavior

I am expecting that this will work without issues since I installed everything required.

### Minimal Reproducible Example

const { compareImages } = require('@appium/images-plugin');

  async function compareTwoImages() {
    const image1 = 'App/Reference.png';
    const image2 = 'App/Reference.png';
    const tolerance = 0.01;
  
    const result = await compareImages(image1, image2, tolerance);
    console.log(`Images match: ${result}`);
  }
  await compareTwoImages();

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by jlipps** [comment]
You're not supposed to use the code of an Appium plugin directly. You activate the plugin in the Appium server, and then call the appropriate client-side method in an Appium client. So if you're using JS you should use WebdriverIO or similar to start an Appium session. I believe the WebdriverIO client also implements the compare images command.
