### ISSUE TITLE
Docs no longer available

### ISSUE THREAD

**Issue by juancoan** [appium/appium#18611]
Hi,
I tried to go over the documentation on the link https://appium.io/docs/en/writing-running-appium/android/uiautomator-uiselector/ and seems the link is not accessible or broken.

Is there a way to get access to Appium 2.0 documentation.?

thanks

**Comment by saikrishna321** [comment]
check here https://appium.io/docs/en/2.0/

**Comment by jlipps** [comment]
for uiautomator2 driver specific information, you'll want https://github.com/appium/appium-uiautomator2-driver
