### ISSUE TITLE
bug:  After "start_activity", the "find_element" method executes abnormally

### ISSUE THREAD

**Issue by pennyyy** [appium/appium#18619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am testing hybrid application with appium,
when the case execution fails, I set ”start_activity“ , but I found after that ”find_element“ method executes abnormally.

### Expected Behavior

After using "start_actvity",can find elements in webview

### Minimal Reproducible Example

**hybrid application**

from appium.webdriver.common.appiumby import AppiumBy
from appium import webdriver

server_url = 'http://127.0.0.1:4723'
desired_caps = dict(platformName="android",
            appPackage="com.company.cpy_hd.uat",
            appActivity="com.company.cpy_hd.MainActivity",
            noReset=True,
            udid='emulator-5554',
            deviceName='emulator-5554',
            automationName='uiautomator2'
                    )
driver = webdriver.Remote(server_url, desired_caps)
driver.implicitly_wait(20)

driver.switch_to.context("WEBVIEW_com.company.cpy_hd.uat")
driver.find_element(by=AppiumBy.XPATH, value='//span[text()="processing"]')

driver.start_activity("com.company.cpy_hd.uat", "com.company.cpy_hd.MainActivity")
driver.switch_to.context("WEBVIEW_com.company.cpy_hd.uat")
driver.find_element(by=AppiumBy.XPATH, value='//span[text()="processing"]')

### Environment

- Operating system:MAC
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):v2.0.0-beta.66
  - Node.js version (output of `node --version`):v20.0.0
  - `npm` version (output of `npm --version`): 9.6.4
  - Last `appium` version which did _not_ exhibit the problem: I don't known
- If running Appium Desktop, its version:/
- Appium driver(s) and their version(s): - chromium@1.1.5 (automationName 'Chromium')/- uiautomator2@2.21.0 (automationName 'UiAutomator2')
- Appium plugin(s) and their version(s): - device-farm@7.3.0/- appium-dashboard@v2.0.2
- Platform and version under test:android 12.0
- Real device or emulator/simulator:simulator
<img width="575" alt="image" src="https://user-images.githubusercontent.com/26864226/236591697-149b3089-afcd-492f-9b92-a785464df075.png">

### Link to Appium Logs

https://gist.github.com/pennyyy/9bf402253cae0208c0dc01362cd98577

**Comment by KazuCocoa** [comment]
I wondered if the chromedriver process attached to a webview got something issue when the script started `driver.start_activity("com.company.cpy_hd.uat", "com.company.cpy_hd.MainActivity")`.
What about switching the context with NATIVE_APP before calling the start_activity?

**Comment by pennyyy** [comment]
wow, it works.Thank you very much.
