### ISSUE TITLE
bug: if "element" is null, execute_script("mobile: swipe") will break

### ISSUE THREAD

**Issue by tking16** [appium/appium#18615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have function which is as follows `driver.execute_script("mobile: swipe", {"direction": direction.drag_direction, "element": self._within, "velocity": self._swipe_intensity})`

sometimes `self._within` will be set to an element which appium will scroll, if not, just swipe the page. recently if `self._within` has no value the test will completely fail

```
E       selenium.common.exceptions.StaleElementReferenceException: Message: The element identified by "null" is either not present or it has expired from the internal cache. Try to find it again
E       Stacktrace:
E       StaleElementReferenceError: The element identified by "null" is either not present or it has expired from the internal cache. Try to find it again
E           at errorFromW3CJsonCode (/Users/theo.king/code/xxx/testing/app-at/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1034:25)
E           at ProxyRequestError.getActualError (/Users/theo.king/code/xxx/testing/app-at/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:909:14)
E           at JWProxy.command (/Users/theo.king/code/xxx/testing/app-at/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:340:19)
E           at processTicksAndRejections (node:internal/process/task_queues:95:5)
E           at XCUITestDriver.proxyCommand (/Users/theo.king/code/xxx/testing/app-at/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:110:14)
E           at XCUITestDriver.mobileSwipe (/Users/theo.king/code/xxx/testing/app-at/node_modules/appium-xcuitest-driver/lib/commands/gesture.js:355:12)
E           at XCUITestDriver.executeMethod (/Users/theo.king/code/xxx/testing/app-at/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/basedriver/commands/execute.ts:36:12)
E           at XCUITestDriver.execute (/Users/theo.king/code/xxx/testing/app-at/node_modules/appium-xcuitest-driver/lib/commands/execute.js:119:14)
```

_env/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:245: StaleElementReferenceException

### Expected Behavior

If element has been given a null value then `execute_script("mobile: swipe")` function can still run. This is working fine in beta.46 version

### Minimal Reproducible Example

driver.execute_script("mobile: swipe", { "element": "", "velocity": 0.3})

### Environment

Appium beta.66
xcuitest@4.25.3

**Comment by jlipps** [comment]
I believe if you don't want to use an element as the scroll basis then the 'element' key should not be included at all. Does it work if you omit the element key entirely?

**Comment by tking16** [comment]
Hi @jlipps, yes it does work. I managed to work around the issue with an `if self._within is None` statement

**Comment by mykola-mokhnach** [comment]
I would say the current behavior is the correct one. No argument and argument with null value are different cases
