### ISSUE TITLE
 Issue with Topic Selection in a React-Native Application using Appium/Appium-Inspector

### ISSUE THREAD

**Issue by apxthexsis** [appium/appium#18634]
Hello Appium

I am currently experiencing an issue with my automation process, specifically when trying to select a topic in my React-Native application. The selection works fine when performed manually without using Appium/Appium-Inspector. However, during automation or manual selection while Appium is running, the process fails.

In the attached video, you can see two demonstrations of the issue. In the first part, I successfully select the topic without automation. In the second part, I attempt to select the topic using automation, which unfortunately fails. I also tried to manually click on the topic while Appium was running, but this too was unsuccessful.

I'm unsure of the root cause of this issue, and I would greatly appreciate any guidance or assistance you can provide. I've ensured that I'm using the latest version of Appium, and I've tried using different methods for element interaction (click(), tap(), press()), but the issue persists.

First try it was as intended without automation and appium: 

https://github.com/appium/appium/assets/118632903/fc0be452-f21d-4238-9a32-95e54f9e9747

Then with automation it fails: 

https://github.com/appium/appium/assets/118632903/bc9dee50-c11d-433a-a9aa-aa6f474e9b1a

**Comment by mykola-mokhnach** [comment]
Maybe there is a race condition. Try to wait for a while after the corresponding button is clicked which opens the list before selecting an item from it

**Comment by mykola-mokhnach** [comment]
There are no server logs, but I assume you might have auto accepting of alerts enabled. This dialog might be implicitly detected as an alert and handled there. What if you disable it?

**Comment by mykola-mokhnach** [comment]
If this is Android then I would make sure to use the most recent driver version (only supplied with Appium 2)
And for the click itself - try to perform it using [W3C actions](https://appiumpro.com/editions/29-automating-complex-gestures-with-the-w3c-actions-api) or using a [click gesture extension](https://github.com/appium/appium-uiautomator2-driver/blob/master/docs/android-mobile-gestures.md#mobile-clickgesture). It also worth trying to click by absolute coordinates

**Comment by mykola-mokhnach** [comment]
Check the logcat output, maybe it contains some interesting errors

**Comment by mykola-mokhnach** [comment]
If you don't provide the activity name explicitly then uia2 driver tries to detect it automatically. It might be the autodetected name is different (correct) from the manually provided one. Check the server logs for more details.

**Comment by mykola-mokhnach** [comment]
Try to explicitly provide appWaitActivity as described in https://github.com/appium/appium-uiautomator2-driver/blob/master/docs/activity-startup.md

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
