### ISSUE TITLE
import * as dependencies from './lib/check-dependencies'; SyntaxError: Cannot use import statement outside a module. Encountered internal error running command: Error: Could not load a driver for automationName 'XCUITest' and platformName 'iOS'. Please verify your Appium installation

### ISSUE THREAD

**Issue by chetnaag95** [appium/appium#18637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
Can't launch appium session for ios simulator, get an error

<img width="581" alt="Screenshot 2023-05-12 at 11 46 08 AM" src="https://github.com/appium/appium/assets/82748928/0657338f-7b61-468b-8a5a-37c6a2b45b5e">

Appium- v1.22.3
WDA v4.9.0
Node v14.21.3
MacOS Ventura 13.2
Xcode 14.2

Appium server log

<img width="1446" alt="Screenshot 2023-05-12 at 12 29 27 PM" src="https://github.com/appium/appium/assets/82748928/d8f21094-c828-4fdf-85f8-cf4f23d28271">

### Expected Behavior

I am trying to connect ios simulator to appium inspector. 

### Minimal Reproducible Example

Capabilities for connecting ios simulator to appium

{
  "platformName": "iOS",
  "appium:platformVersion": "16.2",
  "appium:deviceName": "iPhone 13",
  "appium:automationName": "XCUITest",
  "appium:udid": "XXXXXXXXXX",
  "appium:xcodeOrgId": "XXXXXX",
  "appium:xcodeSigningId": "iPhone Developer"
}

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Appium 1 is not maintained anymore and does not support Xcode 14+. Consider switching to Appium2

Closed as duplicate

**Comment by chetnaag95** [comment]
Hi @mykola-mokhnach Is this the correct document to upgrade from Appium 1 to 2 -http://appium.io/docs/en/2.0/guides/migrating-1-to-2/

**Comment by jlipps** [comment]
Yes
