### ISSUE TITLE
 Could not load a driver for automationName 'XCUITest' and platformName 'iOS'. Please verify your Appium installation

### ISSUE THREAD

**Issue by chetnaag95** [appium/appium#18638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
I Can't launch appium session for ios simulator, get an error

<img width="581" alt="Screenshot 2023-05-12 at 11 46 08 AM" src="https://github.com/appium/appium/assets/82748928/6820dcad-a596-48f5-8996-3b86680c5be2">

Appium - v2.0.0-beta.66
WDA - v4.9.0
Node - v14.21.3
MacOS - Ventura 13.2
Xcode - 14.2
npm - 9.6.6

Appium server log

<img width="1446" alt="Screenshot 2023-05-12 at 12 29 27 PM" src="https://github.com/appium/appium/assets/82748928/10506a34-60da-459d-82d4-b25bc14bb289">

### Expected Behavior

I am trying to connect ios simulator to appium inspector.

### Minimal Reproducible Example

{
  "platformName": "iOS",
  "appium:platformVersion": "16.2",
  "appium:deviceName": "iPhone 13",
  "appium:automationName": "XCUITest",
  "appium:udid": "XXXXXXXX"
}

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Make sure node.js is up to date. Version 14 is currently EOLed. Consider using version 16 or 18

**Comment by jlipps** [comment]
It looks like yu're using Appium Desktop (which is 1.x) and not Appium 2. Please use Appium 2.

**Comment by chetnaag95** [comment]
It worked after reinstalling appium 2.0.0-beta.66 for node v14. Thanks

**Comment by PruthviGowda-novo** [comment]
Java.util.concurrent.ExecutionException: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not load a driver for automationName 'XCUITest' and platformName 'ios'. Please verify your Appium installation


Appium - 1.22.3
WDA - 5.9.1
Node - v16.9.1
MacOS - Ventura 13.6
Xcode - 15
npm - 7.21.1

**Comment by bwomsm1** [comment]
Hi @mykola-mokhnach and @jlipps ,
I am facing the same error, more details can be found here: https://github.com/appium/appium/issues/19984
