### ISSUE TITLE
mobile:pinch not work on iPad real device

### ISSUE THREAD

**Issue by 7999** [appium/appium#18646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

command of "mobile:pinch" with parameter {"scale":1.1,"velocity":1.1,"elementId","xxx"} works well, but with parameter {"scale":0.5,"velocity":-1,"elementId","xxx"} did not work.
from log, the command executed successfully, but nothing affected
log:
[debug] [38;5;32m[XCUITestDriver@89da (c9dde1c9)][0m Proxying [POST /wda/element/01000000-0000-0000-F221-000000000000/pinch] to [POST http://localhost:8101/session/24A310C1-59F8-45DE-90B0-3286B8635C34/wda/element/01000000-0000-0000-F221-000000000000/pinch] with body: {"scale":0.5,"velocity":-1}
[debug] [38;5;32m[XCUITestDriver@89da (c9dde1c9)][0m Got response with status 200: {"value":null,"sessionId":"24A310C1-59F8-45DE-90B0-3286B8635C34"}
[debug] [38;5;32m[XCUITestDriver@89da (c9dde1c9)][0m Responding to client with driver.execute() result: null

-----

same issue with #10315

### Expected Behavior

zoom out also work well.

### Minimal Reproducible Example

execute_script 'mobile: pinch', scale: 0.5, velocity: -1, element: element

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): v2.0.0-beta.67
  - Node.js version (output of `node --version`): v16.20.0
  - `npm` version (output of `npm --version`): 8.19.4
  - Last `appium` version which did _not_ exhibit the problem: n.a
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): appium-xcuitest-driver@4.29.2
- Appium plugin(s) and their version(s): n.a
- Platform and version under test: ios 16.4.1
- Real device or emulator/simulator: real device

**Comment by KazuCocoa** [comment]
The command calls https://developer.apple.com/documentation/xctest/xcuielement/1618669-pinchwithscale , so if it did not work, maybe it is the XCTest method internal thing. Perhaps you could verify if it did not work with vanilla XCTest and report it to Apple.

**Comment by 7999** [comment]
@KazuCocoa 
thanks for your reply.

**Comment by KazuCocoa** [comment]
It could, but I don't know since it is XCTest internal. Only Apple could see more details. In our past experience, iPad has more issues than iPhone

**Comment by mykola-mokhnach** [comment]
https://developer.apple.com/documentation/xctest/xcuielement/1618669-pinchwithscale?language=objc

> scale

>    The scale of the pinch gesture. Use a scale between 0 and 1 to "pinch close" or zoom out and a scale greater than 1 to "pinch open" or zoom in.

> velocity

>    The velocity of the pinch in scale factor per second.

So according to the description both values cannot be negative

**Comment by 7999** [comment]
@mykola-mokhnach 
I got the error message "velocity must be less than zero when scale is less than 1" when use { "scale": 0.5, "velocity": 0.5},
log:
[debug] [38;5;32m[XCUITestDriver@eab4 (0a7bca5d)][0m Proxying [POST /wda/element/01000000-0000-0000-6D22-000000000000/pinch] to [POST http://localhost:8101/session/885F1E45-39E6-4F23-B247-D6AF94F811BB/wda/element/01000000-0000-0000-6D22-000000000000/pinch] with body: {"scale":0.5,"velocity":0.5}
[38;5;32m[XCUITestDriver@eab4 (0a7bca5d)][0m Got response with status 500: {"value":{"error":"unknown error","message":"velocity must be less than zero when scale is less than 1","traceback":"(\n\t0   CoreFoundation                      0x00000001c0479588 3F529C4A-5003-3E5D-84F7-03806108055E + 38280\n\t1   libobjc.A.dylib                     0x00000001b97ed050 objc_exception_throw + 56\n\t2   CoreFoundation                      0x00000001c055b84c 3F529C4A-5003-3E5D-84F7-03806108055E + 964684\n\t3   XCUIAutomation                      0x00000001052d0a2c -[XCUIElement(XCUIElementTouchEvents) pinchWithScale:velocity:] + 300\n\t4   WebDriverAgentLib                   0x0000000108f4bc60 +[FBElementCommands handlePinch:] + 428\n\t5   WebDriverAgentLib                   0x0000000108edadec -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t6   WebDriverAgentLib                   0x0000000108ec6bd4 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 408\n\t7   WebDriverAgentLib                   0x0000000108efd204 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\...
[debug] [38;5;144m[W3C][0m Matched W3C error code 'unknown error' to UnknownError
[debug] [38;5;32m[XCUITestDriver@eab4 (0a7bca5d)][0m Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: velocity must be less than zero when scale is less than 1
[debug] [38;5;32m[XCUITestDriver@eab4 (0a7bca5d)][0m     at errorFromW3CJsonCode (/Users/juan/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1034:25)
[debug] [38;5;32m[XCUITestDriver@eab4 (0a7bca5d)][0m     at ProxyRequestError.getActualError (/Users/juan/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:909:14)
[debug] [38;5;32m[XCUITestDriver@eab4 (0a7bca5d)][0m     at JWProxy.command (/Users/juan/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:340:19)
[debug] [38;5;32m[XCUITestDriver@eab4 (0a7bca5d)][0m     at runMicrotasks (<anonymous>)
[debug] [38;5;32m[XCUITestDriver@eab4 (0a7bca5d)][0m     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [38;5;32m[XCUITestDriver@eab4 (0a7bca5d)][0m     at XCUITestDriver.proxyCommand (/Users/juan/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:112:35)
[debug] [38;5;32m[XCUITestDriver@eab4 (0a7bca5d)][0m     at XCUITestDriver.mobilePinch (/Users/juan/.appium/node_modules/appium-xcuitest-driver/lib/commands/gesture.js:403:12)
[debug] [38;5;32m[XCUITestDriver@eab4 (0a7bca5d)][0m     at XCUITestDriver.executeMethod (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/execute.ts:36:12)
[debug] [38;5;32m[XCUITestDriver@eab4 (0a7bca5d)][0m     at XCUITestDriver.execute (/Users/juan/.appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:119:14)

**Comment by mykola-mokhnach** [comment]
This error message is coming from the corresponding XCTest call. Perhaps, they did not document their stuff properly. Anyway, there is nothing we could do there. Consider creating an issue to Apple instead.

**Comment by 7999** [comment]
@mykola-mokhnach 
thanks for your info
