### ISSUE TITLE
bug: error is showing when starting appium with "appium --base-path=/wd/hub"

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#18643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I installed latest appium 2 beta version and installed the android and ios plugins.

When I start the appium server from terminal app I get the below error.
`appium --base-path=/wd/hub`

I am trying to run the command in Mac OS 13.3.1 and the new apple chip M1

### Expected Behavior

Appium server should start

### Minimal Reproducible Example

From mac `terminal` app run:
`appium --base-path=/wd/hub`

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta66
  - Node.js version (output of `node --version`): 16.20.0
  - `npm` version (output of `npm --version`): 8.19.4
  - Last `appium` version which did _not_ exhibit the problem: one of the beta version 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test: iOS
- Real device or emulator/simulator: real device

### Futher Information

Appium logs:
[35m[Appium][39m Welcome to Appium v2.0.0-beta.66
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { basePath: [32m'/wd/hub'[39m }
[35m[Appium][39m Attempting to load driver xcuitest...
[debug] [35m[Appium][39m Requiring driver at /Users/mac-auto-03/.appium/node_modules/appium-xcuitest-driver
[debug] [35m[Appium][39m Error: Cannot find module 'appium/driver'
[debug] [35m[Appium][39m Require stack:
[debug] [35m[Appium][39m - /Users/mac-auto-03/.appium/node_modules/appium-xcuitest-driver/build/lib/driver.js
[debug] [35m[Appium][39m - /Users/mac-auto-03/.appium/node_modules/appium-xcuitest-driver/build/index.js
[debug] [35m[Appium][39m - /usr/local/lib/node_modules/appium/build/lib/extension/extension-config.js
[debug] [35m[Appium][39m - /usr/local/lib/node_modules/appium/build/lib/cli/extension-command.js
[debug] [35m[Appium][39m - /usr/local/lib/node_modules/appium/build/lib/cli/driver-command.js
[debug] [35m[Appium][39m - /usr/local/lib/node_modules/appium/build/lib/cli/extension.js
[debug] [35m[Appium][39m - /usr/local/lib/node_modules/appium/build/lib/main.js
[debug] [35m[Appium][39m - /usr/local/lib/node_modules/appium/index.js
[debug] [35m[Appium][39m     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
[debug] [35m[Appium][39m     at Function.Module._load (node:internal/modules/cjs/loader:871:27)
[debug] [35m[Appium][39m     at Module.require (node:internal/modules/cjs/loader:1098:19)
[debug] [35m[Appium][39m     at require (node:internal/modules/cjs/helpers:108:18)
[debug] [35m[Appium][39m     at Object.<anonymous> (/Users/mac-auto-03/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:4:1)
[debug] [35m[Appium][39m     at Module._compile (node:internal/modules/cjs/loader:1196:14)
[debug] [35m[Appium][39m     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
[debug] [35m[Appium][39m     at Module.load (node:internal/modules/cjs/loader:1074:32)
[debug] [35m[Appium][39m     at Function.Module._load (node:internal/modules/cjs/loader:909:12)
[debug] [35m[Appium][39m     at Module.require (node:internal/modules/cjs/loader:1098:19)
[debug] [35m[Appium][39m     at require (node:internal/modules/cjs/helpers:108:18)
[debug] [35m[Appium][39m     at Object.<anonymous> (/Users/mac-auto-03/.appium/node_modules/appium-xcuitest-driver/build/index.js:4:18)
[debug] [35m[Appium][39m     at Module._compile (node:internal/modules/cjs/loader:1196:14)
[debug] [35m[Appium][39m     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
[debug] [35m[Appium][39m     at Module.load (node:internal/modules/cjs/loader:1074:32)
[debug] [35m[Appium][39m     at Function.Module._load (node:internal/modules/cjs/loader:909:12)
[debug] [35m[Appium][39m     at Module.require (node:internal/modules/cjs/loader:1098:19)
[debug] [35m[Appium][39m     at require (node:internal/modules/cjs/helpers:108:18)
[debug] [35m[Appium][39m     at DriverConfig.require (/usr/local/lib/node_modules/appium/lib/extension/extension-config.js:578:23)
[debug] [35m[Appium][39m     at /usr/local/lib/node_modules/appium/lib/extension/index.js:83:46
[debug] [35m[Appium][39m     at Array.map (<anonymous>)
[debug] [35m[Appium][39m     at getActiveDrivers (/usr/local/lib/node_modules/appium/lib/extension/index.js:80:10)
[35m[Appium][39m Attempting to load driver uiautomator2...
[debug] [35m[Appium][39m Requiring driver at /Users/mac-auto-03/.appium/node_modules/appium-uiautomator2-driver
[debug] [35m[Appium][39m Error: Cannot find module 'appium/driver'
[debug] [35m[Appium][39m Require stack:
[debug] [35m[Appium][39m - /Users/mac-auto-03/.appium/node_modules/appium-uiautomator2-driver/build/lib/driver.js
[debug] [35m[Appium][39m - /Users/mac-auto-03/.appium/node_modules/appium-uiautomator2-driver/build/index.js
[debug] [35m[Appium][39m - /usr/local/lib/node_modules/appium/build/lib/extension/extension-config.js
[debug] [35m[Appium][39m - /usr/local/lib/node_modules/appium/build/lib/cli/extension-command.js
[debug] [35m[Appium][39m - /usr/local/lib/node_modules/appium/build/lib/cli/driver-command.js
[debug] [35m[Appium][39m - /usr/local/lib/node_modules/appium/build/lib/cli/extension.js
[debug] [35m[Appium][39m - /usr/local/lib/node_modules/appium/build/lib/main.js
[debug] [35m[Appium][39m - /usr/local/lib/node_modules/appium/index.js
[debug] [35m[Appium][39m     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
[debug] [35m[Appium][39m     at Function.Module._load (node:internal/modules/cjs/loader:871:27)
[debug] [35m[Appium][39m     at Module.require (node:internal/modules/cjs/loader:1098:19)
[debug] [35m[Appium][39m     at require (node:internal/modules/cjs/helpers:108:18)
[debug] [35m[Appium][39m     at Object.<anonymous> (/Users/mac-auto-03/.appium/node_modules/appium-uiautomator2-driver/lib/driver.js:2:1)
[debug] [35m[Appium][39m     at Module._compile (node:internal/modules/cjs/loader:1196:14)
[debug] [35m[Appium][39m     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
[debug] [35m[Appium][39m     at Module.load (node:internal/modules/cjs/loader:1074:32)
[debug] [35m[Appium][39m     at Function.Module._load (node:internal/modules/cjs/loader:909:12)
[debug] [35m[Appium][39m     at Module.require (node:internal/modules/cjs/loader:1098:19)
[debug] [35m[Appium][39m     at require (node:internal/modules/cjs/helpers:108:18)
[debug] [35m[Appium][39m     at Object.<anonymous> (/Users/mac-auto-03/.appium/node_modules/appium-uiautomator2-driver/index.js:3:1)
[debug] [35m[Appium][39m     at Module._compile (node:internal/modules/cjs/loader:1196:14)
[debug] [35m[Appium][39m     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
[debug] [35m[Appium][39m     at Module.load (node:internal/modules/cjs/loader:1074:32)
[debug] [35m[Appium][39m     at Function.Module._load (node:internal/modules/cjs/loader:909:12)
[debug] [35m[Appium][39m     at Module.require (node:internal/modules/cjs/loader:1098:19)
[debug] [35m[Appium][39m     at require (node:internal/modules/cjs/helpers:108:18)
[debug] [35m[Appium][39m     at DriverConfig.require (/usr/local/lib/node_modules/appium/lib/extension/extension-config.js:578:23)
[debug] [35m[Appium][39m     at /usr/local/lib/node_modules/appium/lib/extension/index.js:83:46
[debug] [35m[Appium][39m     at Array.map (<anonymous>)
[debug] [35m[Appium][39m     at getActiveDrivers (/usr/local/lib/node_modules/appium/lib/extension/index.js:80:10)
[35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723/wd/hub
[35m[Appium][39m Available drivers:
[35m[Appium][39m   - xcuitest@4.26.0 (automationName 'XCUITest')
[35m[Appium][39m   - uiautomator2@2.24.0 (automationName 'UiAutomator2')
[35m[Appium][39m No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[35m[Appium][39m Received SIGINT - shutting down
[debug] [38;5;0m[AppiumDriver@565b][0m There are no active sessions for cleanup
[38;5;16m[HTTP][0m Waiting until the server is closed
[38;5;16m[HTTP][0m Received server close event

**Comment by jlipps** [comment]
Please run the following commands:

```
npm uninstall -g appium && npm install -g appium@next
rm -rf ~/.appium
appium driver install xcuitest
```

and then try to start the Appium server again.

Appium is not installed to `~/.appium`. Appium installs the drivers there.

**Comment by bwomsm1** [comment]
It feels like that the problem is with the command `appium driver install xcuitest`, the command installs the `xcuitest` to `~/.appium` instead of `/usr/local/lib/node_modules`, but I am not 100% sure

(@jlipps @mykola-mokhnach)

**Comment by bwomsm1** [comment]
@jlipps @mykola-mokhnach sorry for pushing, but any news about this issue? some workarround I can do?

**Comment by eglitise** [comment]
Appium 2 installs all drivers in `~/.appium`, this is normal and expected. If you want to change this location, you can set the `APPIUM_HOME` environment variable to your desired path, before installing a driver.
[See documentation here](http://appium.io/docs/en/2.0/guides/migrating-1-to-2/#drivers-installation-path).

**Comment by jlipps** [comment]
yes that's correct. Appium manages its own driver installations. it does not install them in the global node modules folder. if you want to use NPM to install and manage drivers then follow the [do-it-yourself driver management guide](https://appium.io/docs/en/2.0/guides/managing-exts/#do-it-yourself-with-npm).

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by bwomsm1** [comment]
@mykola-mokhnach , guys, why you are closing the ticket? we are still forced to delete the `~/.appium`, before installing any appium plugin.

See @jlipps advice above. 

Thanks

**Comment by mykola-mokhnach** [comment]
> why you are closing the ticket?

Because I don't observe any issues there. The server code works as expected. What @jlipps meant is if you want to have a custom setup then you need to deal with packaging on your own.

**Comment by bwomsm1** [comment]
Just saying,
When the user installs appium with the follow CMD only:
`npm -g install appium@next` on Mac OS, 
he gets the error above when he is running `appium --base-path=/wd/hub`

**Comment by jlipps** [comment]
No, I don't think that's the case. I think you must have had some previous broken stuff in `~/.appium`. That's why I asked you to remove it. I don't see any issues here either.
