### ISSUE TITLE
[Feat]: Support open url for iOS real device (ios > 16.4)

### ISSUE THREAD

**Issue by xiaoPierre** [appium/appium#18644]
**Is your feature request related to a problem? Please describe.**

Related previous issues : 
https://github.com/appium/appium/issues/9066 
https://github.com/appium/appium/issues/11497 

This issue reported to apple has been fixed since iOS 16.4, so maybe we could integrate the fix in appium2 ? 
https://developer.apple.com/forums/thread/25355?answerId=753311022&replyId=753311022

**Describe the solution you'd like**
Integrate the open url action for iOS > 16.4. 

**Describe alternatives you've considered**
One alternative to open url is through [this workaround](https://appiumpro.com/editions/84-reliably-opening-deep-links-across-platforms-and-devices). 

**Additional context**

**Comment by KazuCocoa** [comment]
I cannot see the forum, but is it not https://github.com/appium/WebDriverAgent/blob/master/CHANGELOG.md#4110-2023-02-19 , which is available in latest xcuitest driver? (it may require Xcode 16.4 environment)

**Comment by mykola-mokhnach** [comment]
Yes, it's there: https://github.com/appium/WebDriverAgent/pull/661
Along with the simulated geolocation: https://github.com/appium/WebDriverAgent/pull/662

**Comment by xiaoPierre** [comment]
Thanks 🙏 Sorry I saw that Apple just replied in the thread yesterday and didn't imagine you're so fast. 🎉

**Comment by mykola-mokhnach** [comment]
Then it must be an XCTest issue, which has been fixed in iOS 17. The client code is the same for both cases - we cannot change the actual API behaviour, only Apple could.
