### ISSUE TITLE
bug: <driver.getPageSource() takes more than 8 seconds to response in iOS>

### ISSUE THREAD

**Issue by amuthansakthivel** [appium/appium#18665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

driver.getPageSource is taking more than 8 seconds to respond in iOS whereas it takes less than 3 seconds in android.

=====Android===========

[AndroidUiautomator2Driver@70d8 (9b276400)] Driver proxy active, passing request on via HTTP proxy
[debug] [AndroidUiautomator2Driver@70d8 (9b276400)] Matched '/session/9b276400-fa4c-4297-a99d-4ad8ff4e8586/source' to command name 'getPageSource'
[debug] [AndroidUiautomator2Driver@70d8 (9b276400)] Proxying [GET /session/9b276400-fa4c-4297-a99d-4ad8ff4e8586/source] to [GET http://127.0.0.1:8200/session/4ba934cc-bfcb-4c1d-8c3b-9f0de7e68fc6/source] with no body
[debug] [AndroidUiautomator2Driver@70d8 (9b276400)] Got response with status 200: {"sessionId":"4ba934cc-bfcb-4c1d-8c3b-9f0de7e68fc6","value":""] Replacing sessionId 4ba934cc-bfcb-4c1d-8c3b-9f0de7e68fc6 with 9b276400-fa4c-4297-a99d-4ad8ff4e8586
[HTTP] <-- GET /session/9b276400-fa4c-4297-a99d-4ad8ff4e8586/source 200 212 ms - 54619

=======IOS=============
[debug] [XCUITestDriver@4f46 (c26e59f2)] Calling AppiumDriver.getPageSource() with args: ["c26e59f2-7898-4f57-90f7-5b1219ec6ed9"]
[debug] [XCUITestDriver@4f46 (c26e59f2)] Executing command 'getPageSource'
[debug] [XCUITestDriver@4f46 (c26e59f2)] Matched '/source?scope=AppiumAUT' to command name 'getPageSource'
[debug] [XCUITestDriver@4f46 (c26e59f2)] Proxying [GET /source?scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/535B6ABF-8EAD-4904-A5A8-5C1B57BCE9E5/source?scope=AppiumAUT] with no body
[debug] [XCUITestDriver@4f46 (c26e59f2)] Got response with status 200: {"value":"}

[debug] [XCUITestDriver@4f46 (c26e59f2)] Responding to client with driver.getPageSource() result: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n  ............XML source"

[HTTP] <-- GET /session/c26e59f2-7898-4f57-90f7-5b1219ec6ed9/source 200 6045 ms - 81506

I think the additional debug log have caused to increased time.

### Expected Behavior

driver.getPageSource should be as fast as android in iOS

### Minimal Reproducible Example

https://github.com/amuthansakthivel/SelenideAppiumFramework - clone/fork this framework

start appium server : "appium --base-path=/wd/hub"

mvn clean test -Dselenide.browser=com.provider.SauceLabIosDriverProvider -Dtests=scroll-test

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.66
  - Node.js version (output of `node --version`): 18.16.0
  - `npm` version (output of `npm --version`): 9.5.1
  - Last `appium` version which did _not_ exhibit the problem: I think the problem with extra logging. 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - uiautomator2@2.12.6 (automationName 'UiAutomator2')
[Appium]   - xcuitest@4.29.1 (automationName 'XCUITest')
[Appium] Available plugins:
[Appium]   - device-farm@5.4.0
[Appium]   - element-wait@1.2.0
[Appium]   - appium-dashboard@v2.0.2
- Platform and version under test: Mac M1
- Real device or emulator/simulator: emulator/simulator

**Comment by mykola-mokhnach** [comment]
There might be multiple reasons to such slowness, although they all are related to how Apple's XCTest framework operates and nothing about it could be changed on the client side. 

I would try to get the page source with particular attributes being excluded via [mobile: source](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/execute-methods.md#mobile-source) extensions as a workaround.

Also you could try to reduce the maximum tree depth by changing the [snapshotMaxDepth](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/settings.md) setting value and/or reduce the animation timeout by [waitForIdleTimeout and/or animationCoolOffTimeout](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/settings.md) settings
