### ISSUE TITLE
Appium 2.0 not able to find WebContext on Cordova iOS app

### ISSUE THREAD

**Issue by ravindra-bairagi** [appium/appium#18672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

I am trying to setup automation for Cordova based hybrid app on iOS and this [link ](https://appium.io/docs/en/writing-running-appium/web/hybrid/)from documentation is not working. Below are version details of libs which I am using:

![image](https://github.com/appium/appium/assets/7116797/3ec028f7-4691-47ed-a36d-75df074efac9)

C# client: 

![image](https://github.com/appium/appium/assets/7116797/951297ad-8c05-4c0c-883a-4ea2acc1cdb2)

After installing WebDriverAgent app on iOS 14 simulator, I have to launch it manually so it allows server to launch app.

Once app is launched then C# client only returns Native Context and Appium server times out before WebContext is returned by server.  I have attached appium logs as well.

Thanks

### Expected Behavior

My app should be launch automatically and Appium should return WebContext for 

### Minimal Reproducible Example

Appium Server config: {
  "server": {
    "address": "127.0.0.1",
    "allow-cors": true,
    "base-path": "/wd/hub",
    "debug-log-spacing": true,
    "keep-alive-timeout": 600,
    "local-timezone": true,
    "log": "/appium.log",
    "log-level": "debug",
    "log-no-colors": false,
    "log-timestamp": true,
    "long-stacktrace": false,
    "no-perms-check": false,
    "port": 4725,
    "relaxed-security": true,
    "session-override": true,
    "strict-caps": false,
    "tmp": "/tmp",
    "trace-dir": "/tmp/appium-instruments"
  }
}

Capabilities:
![image](https://github.com/appium/appium/assets/7116797/bb3aa7ef-d41d-452d-8f9b-c405f4508b73)

### Environment

- Operating system: MacOS Ventura 13
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0-beta
  - Node.js version (output of `node --version`): 18.13.0
  - `npm` version (output of `npm --version`): 8.19.3
  - Last `appium` version which did _not_ exhibit the problem: None
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): xcuitest@4.29.2
- Appium plugin(s) and their version(s):
- Platform and version under test: iPhone 14 iOS 16.1
- Real device or emulator/simulator: simulator

### Link to Appium Logs

https://gist.github.com/ravindra-bairagi/a2f9c465fe5b02fc2795e066442e39fd

**Comment by ravindra-bairagi** [comment]
@mykola-mokhnach Yes, it is. I can use Safari Remote debugger to inspect web elements

**Comment by jlipps** [comment]
@ravindra-bairagi we have made some updates to web contexts in the latest xcuitest driver. can you please try with latest appium and xcuitest driver and submit a new log link?

**Comment by eglitise** [comment]
Closing due to no response
