### ISSUE TITLE
bug: API Get Window Rect return value unexpected in some AUT

### ISSUE THREAD

**Issue by kidmtt94** [appium/appium#18675]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hi team,

Here is my capabilities:
{
   "platformName":"iOS",
   "app":"/Users/test/Documents/ipa/sample_iOS.ipa",
   "deviceName":"test-2325",
   "automationName":"XCUITest",
   "udid":"<udid>",
   "newCommandTimeout":600
}

I try to get size and position on the screen with Restful API `getWindowRect`. 
`API endpoint /session/{session id}/window/rect`

But it always return width and height number is smaller than logical size if I start with my AUT. If I try with another application, it's ok.
Here is my screenshot of my application
![image](https://github.com/webdriverio/webdriverio/assets/12729125/f29cbd0b-3560-4d1c-9154-3e6d80e304f4)

I think the AUT is not support full screen, so it made the API return not correctly. And the value x, y is always zero

### Expected Behavior

I expect the value x and y must be greater than zero because the window rect is not in postion (0, 0)

### Minimal Reproducible Example

Just try this API `/session/{session id}/window/rect` with an AUT does not full screen like above image

### Environment

- Real device
- Try with cloud provider remote testkit, on-premise appium

**Comment by kidmtt94** [comment]
> Is the AUT built for older SDK versions, but installed for newer version? For example the app itself is built for iOS 12 (sdk). I experienced XCTest itself returned wrong coordinate before. I'm not sure this case is related the case and still Xcode behaves as same though

Thanks for your answer. I try to upgrade AUT from an old source to latest.
My device iOS version is 16.3.1 and I had selected following build configuration:
- xcode version 14.2
- iOS deployment target 16.2
- Project document xcode 14.0
- Minimum deployment iOS: 16.2
So I think the AUT is built with iOS 14.

Do you have any workaround solution to get position of application window ?

**Comment by kidmtt94** [comment]
> This API always returns the size of the application's window: https://github.com/appium/WebDriverAgent/blob/1be93e7e2d8f1330680cb72196e8647bf41e1bd0/WebDriverAgentLib/Commands/FBElementCommands.m#L573
> 
> I assume it is related to how XCTest works, because its basic primitive is XCUIApplication object and all in-session commands are proxied to the active application element.

Do you have another API to get position or logical device size ?

**Comment by KazuCocoa** [comment]
> Do you have any workaround solution to get position of application window ?

No, my experienced case was the XCTest itself returned a wrong value. Appium/WDA depends on XCTest framework by Apple, so it meant the root dependency itself returned the wrong value.
The only workaround is to click a place with coordinate without any find_element etc. So you click (x, y) explicitly kind of hardcode way.
