### ISSUE TITLE
upgrade typedoc

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18677]
TypeDoc v0.24.x introduces breaking changes which very much break `@appium/typedoc-plugin-appium` .  The plugin must be updated to use the new multi-module strategy introduced in this version.

1. [ ] Upgrade TypeDoc wherever `typedoc` is mentioned in a `package.json`. 
2. [ ] See [this comment](https://github.com/TypeStrong/typedoc/issues/2236#issuecomment-1509985073) and apply the suggested change to the plugin.
3. [ ] Remove references to `typedoc-plugin-resolve-crossmodule-references`, since TypeDoc v0.24.x deprecates it.
4. [ ] Upgrade `typedoc-plugin-markdown`, since newer version(s) need v0.24.x and older versions won't work with it (yes, this pkg broke semver)
5. [ ] Verify `appium-docs` (from `@appium/docutils`) works as expected

I'm not sure if I'll be able to get to this myself.

**Comment by ramanand-rv** [comment]
Any lead on how to start the Appium2.0 server via running a program?
