### ISSUE TITLE
appium(2.0) can't launch whatsapp

### ISSUE THREAD

**Issue by chenying99** [appium/appium#18685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

appium(2.0) can't launch whatsapp，the WhatsApp application on the Android emulator UI interface does not respond.

### Expected Behavior

Appium (2.0) launches WhatsApp and the interface of the WhatsApp application is observed in the emulator.

### Minimal Reproducible Example

const {remote} = require('webdriverio');

const capabilities = {
    platformName: 'Android',
    'appium:automationName': 'UiAutomator2',
    'appium:deviceName': 'emulator-5554',
    'appium:appPackage': 'com.whatsapp',
    'appium:appActivity': 'com.whatsapp.Main',
    'appium:noReset': true,
    'appium:fullReset': false
};

const wdOpts = {
    host: process.env.APPIUM_HOST || 'localhost',
    port: parseInt(process.env.APPIUM_PORT, 10) || 4723,
    logLevel: 'info',
    capabilities,
};

async function runTest() {
    const driver = await remote(wdOpts);
    await driver.pause(10000);
    await driver.deleteSession();
}

runTest()

### Environment

- Operating system: windows 10
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):  2.0.0-beta.71
  - Node.js version (output of `node --version`):  v18.15.0
  - `npm` version (output of `npm --version`):  9.5.0
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):  uiautomator2@2.25.0 (automationName 'UiAutomator2')
- Appium plugin(s) and their version(s):
- Platform and version under test: android 11
- Real device or emulator/simulator: emulator

### Link to Appium Logs

https://gist.github.com/chenying99/1a261e04d854a688bda44901eef62043

**Comment by jlipps** [comment]
I don't see any issues in the log. You simply create and delete the session. You are not sending any automation commands. What do you expect to happen?

**Comment by chenying99** [comment]
After running the program above, the UI for opening WhatsApp was not seen in the Android emulator.

( If another app is launched using Appium, the UI of the launched app can be seen.)

**Comment by chenying99** [comment]
If I manually launch the UI interface of WhatsApp in the emulator beforehand, I can initiate events from the Appium client; otherwise, an error message saying that the element could not be found is prompted.

**Comment by mykola-mokhnach** [comment]
I don't see any issues with the driver itself. Perhaps, the application under test has some internal protection in the release version.

**Comment by mykola-mokhnach** [comment]
Try a development release instead

**Comment by mykola-mokhnach** [comment]
Also make sure the `appActivity` value is valid. I would check it with the app developer, because there were situations, where the "entrance" activity was a "splash" one. And if main activity was provided instead, different UI artefacts have been observed.

**Comment by chenying99** [comment]
thanks for your reply

The AndroidManifest.xml of WhatsApp, obtained through reverse engineering tools, contains the following node:

```
<activity android:theme="0x7f140405" android:label="0x7f1221ab" android:name="com.whatsapp.Main" android:exported="true" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:hardwareAccelerated="false">
            <intent-filter android:label="0x7f1221ab">
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
                <category android:name="android.intent.category.MULTIWINDOW_LAUNCHER"/>
            </intent-filter>
            <meta-data android:name="android.app.shortcuts" android:resource="0x7f16000a"/>
            <meta-data android:name="com.oculus.vrshell.uses_secure_layer" android:value="inhibit_capture"/>
        </activity>
```

**Comment by mykola-mokhnach** [comment]
FYI, Reverse engineering of WhatsApp's legally not allowed.

Altogether I see no problems on the server side. It is the app itself that does not behave the way it is expected to behave. And only its developer would know the reason for that.

**Comment by jlipps** [comment]
could it be that whatsapp was already running in the background and so launching it did not foreground it?

**Comment by chenying99** [comment]
> could it be that whatsapp was already running in the background and so launching it did not foreground it?

 can't initiate events from the Appium client;
