### ISSUE TITLE
Not able to install Appium 2 in MAC

### ISSUE THREAD

**Issue by chetnaag95** [appium/appium#18681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to install appium -

npm install -g appium@next

Error

npm WARN deprecated typedoc-plugin-resolve-crossmodule-references@0.3.3: Upgrade to typedoc >= 0.24 and remove typedoc-plugin-resolve-crossmodule-references from your dependencies
npm ERR! code 1
npm ERR! path /Users/u1152487/.nvm/versions/node/v18.14.2/lib/node_modules/appium/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm ERR! sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.2/libvips-8.14.2-darwin-x64.tar.br
npm ERR! sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! sharp: Installation error: write EPROTO 4046454CF87F0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:../deps/openssl/openssl/ssl/statem/extensions.c:922:

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/u1152487/.npm/_logs/2023-05-23T08_29_42_639Z-debug-0.log

### Expected Behavior

To install appium 2

### Minimal Reproducible Example

node -v
v18.14.2

npm -v
9.5.0

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by chetnaag95** [comment]
@mykola-mokhnach can you please help me with this

**Comment by mykola-mokhnach** [comment]
Ley me guess - you are behind the great firewall of China?

Maybe try to provide a mirror as described in https://sharp.pixelplumbing.com/install#custom-prebuilt-binaries

**Comment by chetnaag95** [comment]
@mykola-mokhnach Sorry I didn't get you can you explain

**Comment by mykola-mokhnach** [comment]
> npm ERR! sharp: Installation error: write EPROTO 4046454CF87F0000:error:0A000152:SSL 

This error usually means your network client is unable to negotiate a secure connection with the server, where the necessary library components are located. As a workaround you could try to provide an alternative/mirror download URL to fetch binaries that are required for sharp library to work properly. The article below contains detailed examples on how to do that.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
