### ISSUE TITLE
XCUiTest Resets the app creating a session

### ISSUE THREAD

**Issue by JuanCarlos-Arce** [appium/appium#18694]
Hi, 

I'm not sure if it's a bug or a feature request.

Since the change from appium to appium2 with the new architecture I've seen that XCUITest driver resets the app each time that a session is created. 

With appium 1 when I was debugging any of my tests, if the test failed I could open the appium inspector to check the elements of the current screen. But since I change to appium2, if I try to open a new session the device closes the current app and I have to navigate to the same screen manually.

On Android with UiAutomator2 is still working even with appium2.

Is there any way or capabilities to set in order to achieve this ?

**Comment by JuanCarlos-Arce** [comment]
Hi @mykola-mokhnach .

My fault, I try to explain better.

When I debug any of my tests and it fails, I pause the test without closing the session and I open the appium inspector to check the elements of the failing page.

With UiAutomator2, appium inspector creates a new session and gets the snapshot and the elements of the current page without any problem. 

On the other hand, XCUITest closes the app and when appium inspector retrieves the snapshot the app has been closed.

This behavior isn’t the same with appium 1.21 that creates the session and gets the current screen without closing the apps.

**Comment by jlipps** [comment]
@JuanCarlos-Arce how are you starting an inspector session? If you create a new session, yes this will happen. But you can just attach to a running session instead.

**Comment by JuanCarlos-Arce** [comment]
Hi @jlipps , 

I've tried this way and it works like a charm. Thank you so much for your support.
