### ISSUE TITLE
bug: findElement by image not working with fixImageTemplateScale

### ISSUE THREAD

**Issue by BrightApple32** [appium/appium#18695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am attempting to use images plugin to find elements by images on iOS devices.
On appium v1.xx, it was working fine, but now with Appium 2, if I set _fixImageTemplateScale_ setting, I receive interesting errors, probably related to _sharp_ dependency on images plugin.

Current behavior:

1. Creating driver and setting template scale setting: 
`driver = new IOSDriver(new URI("http://127.0.0.1:4723/wd/hub").toURL(), options);
            driver.setSetting(Setting.FIX_IMAGE_TEMPLATE_SCALE, true);`
2. Attempt WebElement location:
`byte[] fileContent = FileUtils.readFileToByteArray(new File("youtube_search_iphone.png"));
            String encodedString = Base64.getEncoder().encodeToString(fileContent);
            WebElement el = driver.findElement(AppiumBy.image(encodedString));`

3. Getting error:
`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Input file contains unsupported image format`
And element location is not even found. It seems that error might happen at resizing step.

If option FIX_IMAGE_TEMPLATE_SCALE is set to False, this step passes, and element location is attempted.

Image used as an example:
![youtube_lithuanianSong_iphone](https://github.com/appium/appium/assets/134607807/c7c248d2-b92e-4ecd-b876-98f5f8ca3a5c)

If using a smaller image, a different error is thrown:
Image:
![youtube_search_iphone](https://github.com/appium/appium/assets/134607807/1090c930-ca68-4db1-a601-b82320686ea9)

Error: 
`side error occurred while processing the command. Original error: Input file is missing: iVBORw0KGgoAAAANSUhEUgAAAD8AAAA9EAYAAABKB22XAAABYWlDQ1BrQ0dDb2xvclNwYWNlRGlzcGxheVAzAAAokWNgYFJJLCjIYWFgYMjNKykKcndSiIiMUmB/yMAOhLwMYgwKicnFBY4BAT5AJQwwGhV8u8bACKIv64LMOiU1tUm1XsDXYqbw1YuvRJsw1aMArpTU4mQg/QeIU5MLikoYGBhTgGzl8pICELsDyBYpAjoKyJ4DYqdD2BtA7CQI+whYTUiQM5B9A8hWSM5IBJrB+API1klCEk9HYkPtBQFul8zigpzESoUAYwKuJQOUpFaUgGjn/ILKosz0jBIFR2AopSp45iXr6SgYGRiaMzCAwhyi+nMgOCwZxc4gxJrvMzDY7v////9uhJjXfgaGjUCdXDsRYhoWDAyC3AwMJ3YWJBYlgoWYgZgpLY2B4dNyBgbeSAYG4QtAPdHFacZGYHlGHicGBtZ7//9/VmNgYJ/MwPB3wv//vxf9//93MVDzHQaGA3kAFSFl7jXH0fsAAACCZVhJZk1NACoAAAAIAAIBEgADAAAAAQABAACHaQAEAAAAAQAAACYAAAAAAASQAwACAAAAFAAAAFyShgAHAAAAEgAAAHCgAgAEAAAAAQAAAD+gAwAEAAAAAQAAAD0AAAAAMjAyMDoxMDoyOSAxNjozODoxNgBBU0NJSQAAAFNjcmVlbnNob3RtFA4SAAACy2lUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNS40LjAiPgogICA..`

### Expected Behavior

Expected that image recognition would work with template scale fix option set to True.

### Minimal Reproducible Example

https://gist.github.com/BrightApple32/11b1f09f187f495acb76757b267450e8

### Environment

- Operating system: macOS Ventura 13.4
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.71
  - Node.js version (output of `node --version`): v18.16.0
  - `npm` version (output of `npm --version`): 9.5.1
  - Last `appium` version which did _not_ exhibit the problem: 1.xx
- Appium driver(s) and their version(s):
uiautomator2@2.25.1 [installed (npm)] [Up to date]
xcuitest@4.29.6 [installed (npm)] [Up to date]

- Appium plugin(s) and their version(s): 
relaxed-caps@1.0.5 [installed (npm)] [Up to date]
images@2.1.1 [installed (npm)] [Up to date]

- Platform and version under test: iOS 16
- Real device or emulator/simulator: Real device

### Link to Appium Logs

https://gist.github.com/BrightApple32/166889b75043aa06d7a9fcab5bf71ccf

**Comment by mykola-mokhnach** [comment]
I hope https://github.com/appium/appium/pull/18696 would do the job

**Comment by BrightApple32** [comment]
Thank you! Did some quick tests and seems like issue is gone with #18696

**Comment by BrightApple32** [comment]
While running some tests using fix from #18696 , it was noticed that if there's a loop with frequent image searches, there's a memory leak and node process consumes more and more RAM, until images-plugin starts throwing exceptions, even when creating a new session. Only restarting appium itself fixes the problem until another loop starts.

Error:
`[ImageElementPlugin] Verifying screenshot size and aspect ratio
[ImageElementPlugin] When trying to find an element, determined that the screen aspect ratio and screenshot aspect ratio are different. Screen is 1080x2168 whereas screenshot is 1080x2400.
[ImageElementPlugin] Resizing screenshot to 1080x2400 to match screen aspect ratio so that image element coordinates have a greater chance of being correct.
[AppiumDriver@ab1f] Command 'findElement' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["images"].
[AndroidUiautomator2Driver@68d9 (b645caf8)] The thrown error object does not seem to be a valid instance of the Error class. This might be a genuine bug of a driver or a plugin.
[debug] [AndroidUiautomator2Driver@68d9 (b645caf8)] Encountered internal error running command: undefined
[HTTP] <-- POST /wd/hub/session/b645caf8-ed34-4755-93a0-6bda4f0a9b47/element 500 919 ms - 574
[HTTP] 
[HTTP] --> DELETE /wd/hub/session/b645caf8-ed34-4755-93a0-6bda4f0a9b47
[HTTP] {}
[debug] [AndroidUiautomator2Driver@68d9 (b645caf8)] Calling AppiumDriver.deleteSession() with args: ["b645caf8-ed34-4755-93a0-6bda4f0a9b47"]
[AppiumDriver@ab1f] Plugins which can handle cmd 'deleteSession': images
[AppiumDriver@ab1f] Plugin images is now handling cmd 'deleteSession'
[AppiumDriver@ab1f] Executing default handling behavior for command 'deleteSession'
[debug] [AppiumDriver@ab1f] Event 'quitSessionRequested' logged at 1685369694516 (17:14:54 GMT+0300 (Eastern European Summer Time))
[AppiumDriver@ab1f] Removing session b645caf8-ed34-4755-93a0-6bda4f0a9b47 from our master session list
[debug] [AndroidUiautomator2Driver@68d9 (b645caf8)] Deleting UiAutomator2 session
[debug] [AndroidUiautomator2Driver@68d9 (b645caf8)] Deleting UiAutomator2 server session
[debug] [AndroidUiautomator2Driver@68d9 (b645caf8)] Matched '/' to command name 'deleteSession'
[debug] [AndroidUiautomator2Driver@68d9 (b645caf8)] Proxying [DELETE /] to [DELETE http://127.0.0.1:8200/session/59e33c8c-b287-4f66-8876-da98c6872b3d] with no body
[debug] [AndroidUiautomator2Driver@68d9 (b645caf8)] Got response with status 200: {"sessionId":"59e33c8c-b287-4f66-8876-da98c6872b3d","value":null}
`

Fuller server logs: https://gist.github.com/BrightApple32/26c8d5053fe4d5b775b4f0ff9f0d90e4

Client-side error:

`An unknown server-side error occurred while processing the command. Original error: 6619144
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.4', java.version: '20.0.1'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [b645caf8-ed34-4755-93a0-6bda4f0a9b47, findElement {using=-image, value=iVBORw0KGgoAAAANSUhEUgAAA9IAAAG/CAYAAAC0Zu9zAAAAAXNSR0IArs...`

Any follow-up test runs result in similar client-side error, but with a different number. E.g.

`org.openqa.selenium.WebDriverException: 
An unknown server-side error occurred while processing the command. Original error: 6620184
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.4', java.version: '20.0.1'
`

Node process memory after crash:
![image](https://github.com/appium/appium/assets/134607807/bd3611b1-b932-49aa-9a7f-dad14632012c)


**Minimal reproducible example**

https://gist.github.com/BrightApple32/4f1b14c1c3127b5d807ff2cb69fb3e98

Image was used from the original post.

**Comment by mykola-mokhnach** [comment]
@BrightApple32 If you think the recent plugin version from the master branch then I don't think there is anything else we could do in order to avoid memory leaks. The problem most likely lies in the https://github.com/opencv/opencv library (or the node.js wrapper to it) itself.

**Comment by mykola-mokhnach** [comment]
Lets close after the release

**Comment by mykola-mokhnach** [comment]
The fix has been released in rc.1
