### ISSUE TITLE
Toolbar above keyboard is not accessible on iOS 16.4 and 16.5

### ISSUE THREAD

**Issue by dejvidq** [appium/appium#18724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On iOS 16.4 and 16.5 toolbar above keyboard (e.g. button "Done") is not recognized by Appium nor Appium Inspector. It is however working correctly on iOS 16.3 and below.
What's really strange is that this toolbar and buttons there can be interacted with when the tested app is opened for the first time after the phone restart. But if the app was simply put to background and opened again, cable is reconnected or app reinstalled, these buttons are disappearing from Inspector. 

Please have a look at two screenshots of an Inspector, one of them, where it's working correctly is from iPhone with iOS 16.3. Second one not working correctly is from iPhone with 16.4.
![ios_16 4_done_button_not_visible](https://github.com/appium/appium/assets/15433565/5099c348-6f8b-4b7a-8383-f88a9ff365cb)
![ios16 3_DoneVisible](https://github.com/appium/appium/assets/15433565/6ccc90e7-f5d5-4756-85b4-d6a68848625a)

### Expected Behavior

Toolbar above keyboard is accessible for Appium and Appium Inspector on all iOS versions.

### Minimal Reproducible Example

Unfortunately, it's not possible for me to provide code snippet

### Environment

- Operating system: MacOS
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): v2.0.0-beta.71
  - Node.js version (output of `node --version`): v19.4.0
  - `npm` version (output of `npm --version`): 9.3.1
  - Last `appium` version which did _not_ exhibit the problem: n/a
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): xcuitest@4.30.2
- Appium plugin(s) and their version(s):
- Platform and version under test: iOS 16.4 and above
- Real device or emulator/simulator: iPhone SE 2020

**Comment by mykola-mokhnach** [comment]
I don't think we can do anything about it from WebDriverAgent side. The page source is retrieved by XCTest itself.

I remember earlier Apple did a similar change to the system status bar, so it did not belong to the active application anymore, but rather to the system one (Springboard). Maybe this time the same thing happened, so I would try to request the page source of the springboard app instead.

**Comment by dejvidq** [comment]
Thanks for your answer, Mykola!

I checked Springboard, and the same happens. Please have a look at attached screenshot.
![screenshot](https://github.com/appium/appium/assets/15433565/6bb64e6b-42e1-4d01-b40e-1996b94d642b)

**Comment by mykola-mokhnach** [comment]
Then I assume only Apple can you there

**Comment by dejvidq** [comment]
Sure, I get it. Thank you!

I'm not sure what to do with this ticket, should I close it, you'll do it, or maybe let it stay open?

**Comment by mykola-mokhnach** [comment]
I don't think it makes sense to keep this issue open. Try to create one for Apple about making the above control accessible.

**Comment by dejvidq** [comment]
Ok, clear.

**Comment by rakeshd2325** [comment]
Has this issue fixed? or any solutions found? Same issue on iOS 17.0

**Comment by dejvidq** [comment]
Hi @rakeshd2325, unfortunately we haven't found any solution nor fix for that 😞

**Comment by dejvidq** [comment]
Hi @rakeshd2325 
I think I found the solution. Your team has to make the element explicitly inspectable, because starting with iOS 16.4 it's disabled by default: https://developer.apple.com/documentation/webkit/wkwebview/4111163-inspectable/

**Comment by rakeshd2325** [comment]
Thanks for your inputs @dejvidq. I tried this with webView.isInspectable = true. Doesn't seem to be working on 16.4 and 17.0. Still at same stage works for the first time when you initiate the simulator for first time this was working before as well. Shutdown simulator and reopen. Here it identifies Done button. Let me know if you find any other solutions.
