### ISSUE TITLE
Cannot get application documents using ’pullFile’ when a file is downloaded during runtime on iOS

### ISSUE THREAD

**Issue by BhumikaBBrowserstack** [appium/appium#18726]
I'm trying to download a file during runtime on a remote server on ios and then download the same using pull file on my local machine, but I'm unable to do that.

`package android;

import io.appium.java_client.AppiumBy;
import io.appium.java_client.ios.IOSDriver;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.MutableCapabilities;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.SessionId;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Comparator;
import java.util.HashMap;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

public class DownloadAndImportFolderLocally901367 {
	
   public static final int BUFFER_SIZE = 4096;
    public static String userName = "username";
    public static String accessKey = "accesskey";
    public static String pdfFilePath = "src/test/resources/Downloads/TestPDF.pdf";
    public static String pdfSrcPath = "src/test/resources/downloaded_files/";
    public static String pdfDestPath = "/Users/username/Documents/testpdf";
    
   

	    public static void main(String args[]) throws InterruptedException, IOException {
	    MutableCapabilities caps = new MutableCapabilities();
	    HashMap<String, Object> browserstackOptions = new HashMap<String, Object>();
	    browserstackOptions.put("osVersion", "16");
	    browserstackOptions.put("deviceName", "iPad 10th");
	    browserstackOptions.put("buildName", "testfiledownload");
	    caps.setCapability("bstack:options", browserstackOptions);
        
	    for (int i=0; i<20; i++) {
	    
	    IOSDriver driver = new IOSDriver(new URL("https://" + userName + ":" + accessKey + "@hub- 
        cloud.browserstack.com/wd/hub"), caps);
        driver.get("file url");
        Thread.sleep(10000);
        driver.findElement(By.xpath(".//a[text()='TestPDF.pdf']")).click();
        Thread.sleep(10000);
        driver.context("NATIVE_APP");
        driver.findElement(By.name("Download")).click();
        Thread.sleep(10000);
        driver.findElement(AppiumBy.accessibilityId("DownloadsButton")).click();
        Thread.sleep(5000);
        driver.findElement(AppiumBy.accessibilityId("DownloadStatus")).click();
        Thread.sleep(5000);
        driver.findElement(AppiumBy.accessibilityId("QLOverlayDefaultActionButtonAccessibilityIdentifier")).click();
        Thread.sleep(10000);
        driver.findElement(By.name("Save to Files")).click();
        Thread.sleep(10000);
        driver.findElement(AppiumBy.accessibilityId("New Folder")).click();
        Thread.sleep(5000);
        driver.findElement(AppiumBy.accessibilityId("TextSelectionStartGrabber")).sendKeys("Test1234");
        Thread.sleep(5000);
        //driver.findElement(AppiumBy.accessibilityId("Save")).click();
        driver.findElement(AppiumBy.iOSNsPredicateString("label == 'done'")).click();
        Thread.sleep(5000);
        driver.findElement(AppiumBy.accessibilityId("Save")).click();
        Thread.sleep(5000);
        driver.findElement(AppiumBy.accessibilityId("QLOverlayDoneButtonAccessibilityIdentifier")).click();
        Thread.sleep(5000);
        
        
        SessionId sessionId = driver.getSessionId();
        JavascriptExecutor jse = (JavascriptExecutor) driver;

        try {
            byte[] fileBase64_2 = driver.pullFile("On My iPad/Test1234/TestPDF.pdf");
            String encodedString = new String(Base64.getEncoder().encode(fileBase64_2));
            byte[] data = Base64.getDecoder().decode(encodedString);

            OutputStream stream = new FileOutputStream("/Users/username/Documents/testpdf/test.pdf");
 
            stream.write(data);
            stream.close();
            jse.executeScript("browserstack_executor: {\"action\": \"setSessionStatus\", \"arguments\": {\"status\": \"passed\", \"reason\": \"file downloaded\"}}");
            
        } catch (Exception e) {
            System.out.println("Pull file Exception:" + e.getMessage());
            jse.executeScript("browserstack_executor: {\"action\": \"setSessionStatus\", \"arguments\": {\"status\": \"failed\", \"reason\": \"file not downloaded\"}}");
        }

        Thread.sleep(5000);
        driver.quit();
	    }
    }	    
`

but for all the different paths that I tried, I'm getting the error that path does not exist.
Is there a way to achieve this use case for real ios devices.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
