### ISSUE TITLE
[Feat]: Implement js command execution in xcuitest/androiduiautomator drivers (or guidance and collaboration)

### ISSUE THREAD

**Issue by ScgCast** [appium/appium#18727]
**Is your feature request related to a problem? Please describe.**
We are in the process of creating a new test framework where we can test all browsers, TVs and native applications at the same time from one test case. To do this we decided to use our own SDK js commands instead of locators (as we don't want to maintain a test UI for our SDK, also don't want different set of element definitions for multitude of devices)

**Describe the solution you'd like**
We can easily use execute_script capability on web platforms as the web drivers have the execute_script capability but androidUIautomator and xcuitest is missing this (It is fair as native normally dont support js commands anyways) But we have the scenario that we already created a bridge between js and native SDK through React Native and if we can simply pass this js commands through these drivers to RN we will be able to execute our own commands on native platforms.

**Describe alternatives you've considered**
Alternative would be to implement Detox Test library along with appium for native part but it would be better if we don't have to switch our python framework to javascript to be able to use Detox. Also it would be cool to just be able to do it with Appium drivers without implementing more test libraries.

**Additional context**
To remind that using RN for building native apps is getting more demand now so it could be possible that people may want to use this feature (as we do) on xcuitest and androiduiautomator drivers so I believe this would be a good addition.

We could work in collaboration to add this functionality to drivers but would need guidance and support on how to implement it to be fair. Before I had defined new driver capabilities for Selenium but not on Appium and of course appium native drivers are a bit more complex.

Thanks in advance!

**Comment by mykola-mokhnach** [comment]
Usually in Appium2 world you could override/patch the default API call handlers by using plugins. Have you investigated such possibility?

**Comment by jlipps** [comment]
@ScgCast as you mentioned there is no way to execute javascript for ios/android. how did you intend to inject javascript into the react native js engine? if you can find some way to do that, then yes, you could write an appium plugin which overrides the executeScript command for ios/android and sends those js snippets to react native instead. but this is not really a design goal for the appium drivers.

**Comment by jlipps** [comment]
i could also see there being a special 'react native driver' that allows sending javascript and allows working with the react native component tree as elements instead of native mobile ui elements. not sure how such a driver would be implemented though.

**Comment by mykola-mokhnach** [comment]
@ScgCast Is there anything else we can help with in scope of this issue?

**Comment by ScgCast** [comment]
@mykola-mokhnach After consideration we decided to solve it via our own test app, thank you
