### ISSUE TITLE
bug: [debug] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed. 

### ISSUE THREAD

**Issue by Auto81** [appium/appium#18728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

#10749 and #12019 Seem to be related over the years

When starting a session it crashes and logs out '[debug] [Instrumentation] INSTRUMENTATION_RESULT: shortMsg=Process crashed.'

Everything will be working as expected in a test run, but eventually the emulator will get into a weird state when appium is trying to start a session.

On the emulator the screen the app will flash up as forceAppLaunch is on, then the session will end.

Picture attached of log, sorry it's the only thing we have, I will try get full text logs next time it happens

### Expected Behavior

Tests to start up and run as normal

### Minimal Reproducible Example

Can't easily reproduce it unfortunately. 

4 thread/device parallel test suite on grid. Could do a full test suite (1000s of tests) and not have an issue on any emulator).

But then could also have it where each of the emulators ends up doing this in the same suite. Once it begins happening it doesnt recover and requires a manual emulator restart. 

### Environment

- Operating system: Mac
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.71
  - Node.js version (output of `node --version`): 18.16.0
  - `npm` version (output of `npm --version`): 9.5.1
  - Last `appium` version which did _not_ exhibit the problem: Happening on and off for a while
- Appium driver(s) and their version(s):
✔ Listing available drivers
xcuitest@4.11.1 [installed (npm)]
uiautomator2@2.25.2 [installed (npm)]
- Appium plugin(s) and their version(s):
✔ Listing available plugins
images@1.3.7 [installed (npm)]
- Platform and version under test: Android 11
- Real device or emulator/simulator: Emulator

### Futher Information

![Screenshot 2023-06-02 at 15 32 52](https://github.com/appium/appium/assets/48491431/f4852850-4b04-4c42-8cbd-f3a5a6d435a0)

**Comment by mykola-mokhnach** [comment]
Please provide the full logcat output for the same time period

**Comment by mykola-mokhnach** [comment]
it is also weird to me that the process crashed Lin is repeated twice. Are you sure the session management works as expected from your side and previous sessions are being closed properly before starting new ones?

**Comment by Auto81** [comment]
I'd imagine session management is correct, works for 100s of android tests during the same run, and also works all the time for iOS when we swap over to use the iosdriver. The next logcat that i can get will hopefully help!

From the previous github issues mentioned it looks like previous sessions havent closed properly? Is there any extra logging or options i can enable during a run to help get info?

**Comment by mykola-mokhnach** [comment]
If you use one-server->one session strategy then adding --session-override param to server arguments may help to ensure session uniqueness.  Otherwise I don't have any good ideas

**Comment by mykola-mokhnach** [comment]
Closed because of no response
