### ISSUE TITLE
No context for WebView of React Native App

### ISSUE THREAD

**Issue by huseyin-tumer** [appium/appium#18725]
Hello Guys!

I have react native app. And i want to write automated tests for the app.
In the app, there is WebView component but no context for WebView in appium.
There is context with name "NATIVE_APP" only.

My react native WebView component like below.  What should i do?

import * as React from 'react';
import { Keyboard } from 'react-native';
import {WebView} from 'react-native-webview';
import { StyleSheet } from 'react-native';
import CookieManager from '@react-native-cookies/cookies';
import {useIsFocused} from '@react-navigation/native';
import {Box} from '@xx/bb';
import {deviceWidth, deviceHeight, getVersion, postMessage} from '@xx/yy';
import { ONE_MIN, ONE_MONTH } from '@xx/zz';
import LoadingScreen from '../components/Loading';

type WebViewProps = {
    uri: string;
    withCookies: boolean;
    loading: boolean;
    [key: string]: any;
};
export default React.forwardRef((props: WebViewProps, ref: any) => {
    const { state } = global.engine.useAuth();
    const isFocused = useIsFocused();
    let uri = props.uri;
    let loading = props.loading ?? true;
    if (props.withCookies) {
        let uriUrl = new URL(uri);

        const oneMonthExp = new Date(
            new Date().getTime() + ONE_MONTH,
        ).toISOString();
        const fourMinExp = new Date(
            new Date().getTime() + ONE_MIN * 4,
        ).toISOString();

        // version
        const version = {
            name: 'mobile_version',
            value: getVersion(),
            domain: uriUrl.host,
            path: '/',
            expires: oneMonthExp,
            version: '1',
        };
        CookieManager.set(uriUrl.href, version);

        // refresh token
        if (state.refreshToken) {
            const refreshToken = {
                name: 'mobile_refresh_token',
                value: state.refreshToken,
                domain: uriUrl.host,
                path: '/',
                expires: oneMonthExp,
                version: '1',
            };

            CookieManager.set(uriUrl.href, refreshToken);
        }

        // access token
        if (state.accessToken) {
            const accessToken = {
                name: 'mobile_access_token',
                value: state.accessToken,
                domain: uriUrl.host,
                path: '/',
                expires: fourMinExp,
                version: '1',
            };

            CookieManager.set(uriUrl.href, accessToken);
        }
    }

    if (loading && !isFocused) {
        return <LoadingScreen/>;
    }

    Keyboard.dismiss();

    Keyboard.addListener('keyboardWillShow', (e) => {
        postMessage(ref, {
            keyboardShow: true,
            height: e.endCoordinates.height,
        });
    });

    Keyboard.addListener('keyboardDidHide', () => {
        postMessage(ref, {
            keyboardShow: false,
        });
    });

    return (
        <Box
            flex={1}
            alignItems="center"
            justifyContent="space-between"
            accessible={true}>
            <WebView
                bounces={false}
                accessible={true}
                accessibilityLabel="web-view-screen"
                showsVerticalScrollIndicator={false}
                applicationNameForUserAgent={`MyUserAgent/${getVersion()}`}
                style={styles.webview}
                startInLoadingState={true}
                cacheEnabled={false}
                sharedCookiesEnabled={true}
                source={{ uri }}
                ref={ref}
                {...props}
            />
        </Box>
    )
});

const styles = StyleSheet.create({
    webview: {
        height: deviceHeight,
        width: deviceWidth,
    },
});

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot suggest anything about react development. You should look for such kind of help in other places.

Regarding web views - make sure the web view is visible in Safari remote debugger. If it is not then it won't be visible by xcuitest driver as well

**Comment by mykola-mokhnach** [comment]
Sorry, I am talking about https://appletoolbox.com/use-web-inspector-debug-mobile-safari/

Are you able to debug the web view there?
