### ISSUE TITLE
What specific commands or processes does Appium use to install an application on an iOS device or emulator?

### ISSUE THREAD

**Issue by apxthexsis** [appium/appium#18737]
What specific commands or processes does Appium use to install an application on an iOS device or emulator? Are different tools or methods used depending on the type of device (real or emulator) or the file type of the application (like .app or .ipa files)? Could you please provide examples of these commands or processes?"

If my assumptions right
ios-deploy --bundle /path/to/your/app.app
or 
ideviceinstaller -u <device_udid> -i /path/to/your/app.ipa

For simulators 
xcrun simctl install <simulator_udid> /path/to/your/app.app

**Comment by mykola-mokhnach** [comment]
Yes, for Simulators xcuitest driver uses simctl. For real devices though it uses APIs exported by appium-ios-device module. Check https://github.com/appium/appium-xcuitest-driver/blob/52b0b4812372495b5c8a85aed5fa178ff66efa41/lib/real-device-management.js#L70 for more details.
