### ISSUE TITLE
bug: Appium Inspector for iOS Simulator not working with XCode 14.3 Upgrade (Spinning)

### ISSUE THREAD

**Issue by KRNM7** [appium/appium#18734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium Inspector tool stuck spinning afte XCode 14.3 upgrade.

<img width="1254" alt="Inspector tool spinning" src="https://github.com/appium/appium/assets/92329463/9f73dc0d-7f04-4be7-9688-7b9793da3af0">

### Expected Behavior

The inspector tool should connect and capture the app's screen and App Source.

### Minimal Reproducible Example

- Open and run Appium Server GUI  (v1.22.2)
- Open Inspector Tool (v2023.5.2 & v2021.9.2)
- Select the iOS 16.4 iPhone 14 Pro  or 11 Pro (I tried with different versions)
- Start Session 
- ** Inspector Tool Screen Stuck Spinning **

### Environment

- Operating system: MacOS = Ventura 13.4
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0
  - Node.js version (output of `node --version`):  19.8.1
  - `npm` version (output of `npm --version`):   9.5.1
  - Last `appium` version which did _not_ exhibit the problem:  XCode 12
- If running Appium Desktop, its version: 1.22.2
- Appium driver(s) and their version(s):  ✔ Listing available drivers
                        > - uiautomator2@2.12.7 [installed (npm)] [2.25.2 available]
                        > - xcuitest@4.19.1 [installed (npm)] [4.30.2 available]
                        > - espresso@2.20.0 [installed (npm)] [2.23.1 available]
                        > - gecko@1.1.8 [installed (npm)] [1.1.9 available]
                        > - safari@3.3.2 [installed (npm)] [3.3.3 available]
                        > - mac2 [not installed]
                        > - chromium [not installed]

- Appium plugin(s) and their version(s):
- Platform and version under test:  iOS iPhone14 Pro iOS 16.4
- Real device or emulator/simulator:  iOS iPhone14 Pro iOS 16.4

### Futher Information

Remote Host: 127.0.0.1
Remote Port:  4723

desired capabilities:
appium:automationName: "XCUITest

Appium Server Logs:

[HTTP] --> GET /wd/hub/session/5f24ad2a-7d92-4599-a1e4-65a8bdaf2c63/timeouts
[HTTP] {}
[W3C (5f24ad2a)] Calling AppiumDriver.getTimeouts() with args: ["5f24ad2a-7d92-4599-a1e4-65a8bdaf2c63"]
[XCUITest] Executing command 'getTimeouts'
[W3C (5f24ad2a)] Responding to client with driver.getTimeouts() result: {"command":0,"implicit":0}
[HTTP] <-- GET /wd/hub/session/5f24ad2a-7d92-4599-a1e4-65a8bdaf2c63/timeouts 304 1

**Comment by mykola-mokhnach** [comment]
This is expected. You need to upgrade to Appium 2 in order to test newer iOS versions

**Comment by KRNM7** [comment]
@mykola-mokhnach  i had already upgraded to Appium 2 before I upgraded XCode.  how can I confirm?

**Comment by mykola-mokhnach** [comment]
The actual version is visible in server logs

**Comment by KRNM7** [comment]
I upgraded the Appium Drivers. I was already using Appium 2.  I'm not following on the solution.  What do I need to upgrade or how can I confirm i'm running the correct versions exactly?

**Comment by KRNM7** [comment]
Still not working.

![image](https://github.com/appium/appium/assets/92329463/1214f690-6a37-4f89-8c57-1c631e021813)

**Comment by KazuCocoa** [comment]
appium-inspector does not have built in appium server. Your env maybe still used Appium Desktop and Appium v1.
https://github.com/appium/appium-inspector#installation may help, https://discuss.appium.io/

**Comment by KRNM7** [comment]
@eglitise Thank you for your thorough response. It’s working now with your instructions.
