### ISSUE TITLE
eslint config: disable warning about assigning to prototype

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18738]
This is a custom warning I added about assigning to `prototype` when I was exploring how best to support the "mixin" pattern Appium is using.  The original strategy used a pipeline of class factories (which turned out to be too confusing and painful); in that strategy, we did not want to assign to `prototype`.  However, after further exploration, I've settled on _declaration merging_ as the most straightforward way to support mixins.  In this case, we _will_ be using `Object.assign(Ctor.prototype, someMixin)`; so we can remove this warning.

**Comment by boneskull** [comment]
cc @mykola-mokhnach

**Comment by jlipps** [comment]
👍

**Comment by mykola-mokhnach** [comment]
Closed as resolved
