### ISSUE TITLE
bug: calling to "set_clipboard_text" api throws an error: The pasteboard name com.apple.UIKit.pboard.general is not valid

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#18730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running iOS test against iOS 16.5.

The problem that I am experiencing was not reproducing in iOS version 14.4.

When I am calling to 
`self.driver_.set_clipboard_text(text)`
I get the following error in appium server: 
[Xcode] 2023-06-04 14:35:26.460937+0300 WebDriverAgentRunner-Runner[14911:587041] [Pasteboard] ...retrieving pasteboard named com.apple.UIKit.pboard.general failed with error: Error Domain=PBErrorDomain Code=10 "Pasteboard com.apple.UIKit.pboard.general is not available at this time." UserInfo={NSLocalizedDescription=Pasteboard com.apple.UIKit.pboard.general is not available at this time.}
[Xcode]
[Xcode] 2023-06-04 14:35:26.465187+0300 WebDriverAgentRunner-Runner[14911:587041] [Pasteboard] ...retrieving pasteboard named com.apple.UIKit.pboard.general failed with error: Error Domain=PBErrorDomain Code=10 "Pasteboard com.apple.UIKit.pboard.general is not available at this time." UserInfo={NSLocalizedDescription=Pasteboard com.apple.UIKit.pboard.general is not available at this time.}
[Xcode]
[debug] [XCUITestDriver@de7b (1fa9aa78)] Got response with status 200: {"value":null,"sessionId":"13F9DDA0-E6E0-49AF-9F08-ED2E44873987"}
[debug] [XCUITestDriver@de7b (1fa9aa78)] Responding to client with driver.setClipboard() result: null
[HTTP] <-- POST /wd/hub/session/1fa9aa78-cd74-4da3-881e-8d6f25ec405b/appium/device/set_clipboard 200 25 ms - 14
[HTTP]
[Xcode] 2023-06-04 14:35:26.469013+0300 WebDriverAgentRunner-Runner[14911:596373] [Pasteboard] ...saving pasteboard failed with error: Error Domain=PBErrorDomain Code=11 "The pasteboard name com.apple.UIKit.pboard.general is not valid." UserInfo={NSLocalizedDescription=The pasteboard name com.apple.UIKit.pboard.general is not valid.}
[Xcode]
[Xcode] 2023-06-04 14:35:26.469220+0300 WebDriverAgentRunner-Runner[14911:596373] Could not save pasteboard named com.apple.UIKit.pboard.general. Error: Error Domain=PBErrorDomain Code=11 "The pasteboard name com.apple.UIKit.pboard.general is not valid." UserInfo={NSLocalizedDescription=The pasteboard name com.apple.UIKit.pboard.general is not valid.}
[Xcode]

### Expected Behavior

The test which I am setting should be copied to clipboard, but it is not.

### Minimal Reproducible Example

described above

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2 beta 66
  - Node.js version (output of `node --version`):v18.12.1
  - `npm` version (output of `npm --version`): 9.6.4
  - Last `appium` version which did _not_ exhibit the problem: 2 beta, the last iOS that it was working with was 14.4
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): xcuitest@4.24.3 (automationName 'XCUITest')
- Appium plugin(s) and their version(s):
- Platform and version under test: iOS
- Real device or emulator/simulator: real device

### Link to Appium Logs

https://github.com/bwomsm1/AppiumLogs/blob/master/appium_ios.log

### Futher Information

[HTTP] --> POST /wd/hub/session/1fa9aa78-cd74-4da3-881e-8d6f25ec405b/appium/device/set_clipboard
[HTTP] {"content":"VlVQZlVIemRmUWlDcDdqbUt4b0VyaWdXejZCWU5zeWVBWjV6SndGczdNMi9EdVREbzcyaVliZ3VlbEVTRlFvRmdnVzFkeTQwTXVOK1E0d1ltaGhTbHk4ZVZVWjdsY2NrZmNIOW5pRXVrUDdvcG0zaVVHV2dHby9rV1BaN1BQNW9WUkI5UWIyZDQ3REw2VWg4blhYdUhVTHNUZkFFdHNKUHBQUEpYTUd1UC9sWE5CdG44Zzc2RTE2UXRJZnZZSTNlMVN2RUZCajFFSWhhZzhtR29JMnhKOUlkZXk3VUhqQTJSd0RZM0xZQzZ2djNlUytlWnBVT0YxY2VJU3Rqc2RSTUtwKzgzWFZKdlZ6V28wNzVLZ2VkbTZEU2gzdWM0aC9Bb01mZEFLL20vVHgrK3ZwT2h4bFd1MWk1dHBUSkF3UE9ZTDNZMEdZVUFKOVdjMHd1YWxvc3BTQmU0a1pHZmRadkc0Y0RzSjFqanNoM0JOaTR2VmZNUlkrUERKSU01dExzMGgxN0x0UWVNRGE2Y0JjS0hrb0tMeG1QeFQydjB4NVJoaWlYMW82bzdIeGh2L2piZW85cTBrd1ZZWGh4VWpMSkVCU2MzVGp5TGZYbW5LUEJPR1M4eHRaNGg5Yk1kVTI0ZGN6Q0pMT3JLWFVhTjdyaTU5aVIwdjZKL1c3a25WOG9GRHVmdzZUU2U4eGJMa2VRYXppQ0RrcGxxZitwd2s5WXN1T2srcDB0aEZYaWJPZlc5RHFSVXVTdm40MjFyWVJyUmhieDloNWM4cmU4alAxL1pQZ3kzL0ZUekZCRVhlY1Q5ZGUvcGtYNVdRd0JLa1NsblFQT2M1K09qQS9LQ2t4OTBBYzJkMjRmeHlUaWJPZlc5RHFSVWtYVCtBem5aZ1pYNG16bjF2UTZrVklHa0VKeFBZWWZYN080WjM4UEVXK0E4MGJzYkJLQkFibUx5aXAwVXd6RVEzTUU5RFNpZ0YzUm9NQU0yMzNPWnRmbVliTmJPS29HQ...
[debug] [XCUITestDriver@de7b (1fa9aa78)] Calling AppiumDriver.setClipboard() with args: ["VlVQZlVIemRmUWlDcDdqbUt4b0VyaWdXejZCWU5zeWVBWjV6SndGczdNMi9EdVREbzcyaVliZ3VlbEVTRlFvRmdnVzFkeTQwTXVOK1E0d1ltaGhTbHk4ZVZVWjdsY2NrZmNIOW5pRXVrUDdvcG0zaVVHV2dHby9rV1BaN1BQNW9WUkI5UWIyZDQ3REw2VWg4blhYdUhVTHNUZkFFdHNKUHBQUEpYTUd1UC9sWE5CdG44Zzc2RTE2UXRJZnZZSTNlMVN2RUZCajFFSWhhZzhtR29JMnhKOUlkZXk3VUhqQTJSd0RZM0xZQzZ2djNlUytlWnBVT0YxY2VJU3Rqc2RSTUtwKzgzWFZKdlZ6V28wNzVLZ2VkbTZEU2gzdWM0aC9Bb01mZEFLL20vVHgrK3ZwT2h4bFd1MWk1dHBUSkF3UE9ZTDNZMEdZVUFKOVdjMHd1YWxvc3BTQmU0a1pHZmRadkc0Y0RzSjFqanNoM0JOaTR2VmZNUlkrUERKSU01dExzMGgxN0x0UWVNRGE2Y0JjS0hrb0tMeG1QeFQydjB4NVJoaWlYMW82bzdIeGh2L2piZW85cTBrd1ZZWGh4VWpMSkVCU2MzVGp5TGZYbW5LUEJPR1M4eHRaNGg5Yk1kVTI0ZGN6Q0pMT3JLWFVhTjdyaTU5aVIwdjZKL1c3a25WOG9GRHVmdzZUU2U4eGJMa2VRYXppQ0RrcGxxZitwd2s5WXN1T2srcDB0aEZYaWJPZlc5RHFSVXVTdm40MjFyWVJyUmhieDloNWM4cmU4alAxL1pQZ3kzL0ZUekZCRVhlY1Q5ZGUvcGtYNVdRd0JLa1NsblFQT2M1K09qQS9LQ2t4OTBBYzJkMjRmeHlUaWJPZlc5RHFSVWtYVCtBem5aZ1pYNG16bjF2UTZrVklHa0VKeFBZWWZYN080WjM4UEVXK0E4MGJzYkJLQkFibUx5aXAwVXd6RVEzTUU5RFNpZ0YzUm9NQU0yMzNPWnRmbVliTmJPS29HQmVIZENZZHp...
[debug] [XCUITestDriver@de7b (1fa9aa78)] Executing command 'setClipboard'
[XCUITestDriver@de7b (1fa9aa78)] Proxying to WDA with an unknown route: POST /wda/setPasteboard
[debug] [XCUITestDriver@de7b (1fa9aa78)] Proxying [POST /wda/setPasteboard] to [POST http://127.0.0.1:8100/session/13F9DDA0-E6E0-49AF-9F08-ED2E44873987/wda/setPasteboard] with body: {"content":"VlVQZlVIemRmUWlDcDdqbUt4b0VyaWdXejZCWU5zeWVBWjV6SndGczdNMi9EdVREbzcyaVliZ3VlbEVTRlFvRmdnVzFkeTQwTXVOK1E0d1ltaGhTbHk4ZVZVWjdsY2NrZmNIOW5pRXVrUDdvcG0zaVVHV2dHby9rV1BaN1BQNW9WUkI5UWIyZDQ3REw2VWg4blhYdUhVTHNUZkFFdHNKUHBQUEpYTUd1UC9sWE5CdG44Zzc2RTE2UXRJZnZZSTNlMVN2RUZCajFFSWhhZzhtR29JMnhKOUlkZXk3VUhqQTJSd0RZM0xZQzZ2djNlUytlWnBVT0YxY2VJU3Rqc2RSTUtwKzgzWFZKdlZ6V28wNzVLZ2VkbTZEU2gzdWM0aC9Bb01mZEFLL20vVHgrK3ZwT2h4bFd1MWk1dHBUSkF3UE9ZTDNZMEdZVUFKOVdjMHd1YWxvc3BTQmU0a1pHZmRadkc0Y0RzSjFqanNoM0JOaTR2VmZNUlkrUERKSU01dExzMGgxN0x0UWVNRGE2Y0JjS0hrb0tMeG1QeFQydjB4NVJoaWlYMW82bzdIeGh2L2piZW85cTBrd1ZZWGh4VWpMSkVCU2MzVGp5TGZYbW5LUEJPR1M4eHRaNGg5Yk1kVTI0ZGN6Q0pMT3JLWFVhTjdyaTU5aVIwdjZKL1c3a25WOG9GRHVmdzZUU2U4eGJMa2VRYXppQ0RrcGxxZitwd2s5WXN1T2srcDB0aEZYaWJPZlc5RHFSVXVTdm40MjFyWVJyUmhieDloNWM4cmU4alAxL1pQZ3kzL0ZUekZCRVhlY1Q5ZGUvcGtYNVdRd0JLa1NsblFQT2M1K09qQS9LQ2t4OTBBYzJkMjRmeHlUaWJPZlc5RHFSVWtYVCtBem5aZ1pYNG16bjF2UTZrVklHa0VKeFBZWWZYN080WjM4UEVXK0E4MGJzYkJLQkFibUx5aXAwVXd6RVEzTUU5RFNpZ0YzUm9NQU0yMzNPWnRmbVliTmJPS29HQ...
[Xcode] 2023-06-04 14:35:26.460937+0300 WebDriverAgentRunner-Runner[14911:587041] [Pasteboard] ...retrieving pasteboard named com.apple.UIKit.pboard.general failed with error: Error Domain=PBErrorDomain Code=10 "Pasteboard com.apple.UIKit.pboard.general is not available at this time." UserInfo={NSLocalizedDescription=Pasteboard com.apple.UIKit.pboard.general is not available at this time.}
[Xcode]
[Xcode] 2023-06-04 14:35:26.465187+0300 WebDriverAgentRunner-Runner[14911:587041] [Pasteboard] ...retrieving pasteboard named com.apple.UIKit.pboard.general failed with error: Error Domain=PBErrorDomain Code=10 "Pasteboard com.apple.UIKit.pboard.general is not available at this time." UserInfo={NSLocalizedDescription=Pasteboard com.apple.UIKit.pboard.general is not available at this time.}
[Xcode]
[debug] [XCUITestDriver@de7b (1fa9aa78)] Got response with status 200: {"value":null,"sessionId":"13F9DDA0-E6E0-49AF-9F08-ED2E44873987"}
[debug] [XCUITestDriver@de7b (1fa9aa78)] Responding to client with driver.setClipboard() result: null
[HTTP] <-- POST /wd/hub/session/1fa9aa78-cd74-4da3-881e-8d6f25ec405b/appium/device/set_clipboard 200 25 ms - 14
[HTTP]
[Xcode] 2023-06-04 14:35:26.469013+0300 WebDriverAgentRunner-Runner[14911:596373] [Pasteboard] ...saving pasteboard failed with error: Error Domain=PBErrorDomain Code=11 "The pasteboard name com.apple.UIKit.pboard.general is not valid." UserInfo={NSLocalizedDescription=The pasteboard name com.apple.UIKit.pboard.general is not valid.}
[Xcode]
[Xcode] 2023-06-04 14:35:26.469220+0300 WebDriverAgentRunner-Runner[14911:596373] Could not save pasteboard named com.apple.UIKit.pboard.general. Error: Error Domain=PBErrorDomain Code=11 "The pasteboard name com.apple.UIKit.pboard.general is not valid." UserInfo={NSLocalizedDescription=The pasteboard name com.apple.UIKit.pboard.general is not valid.}
[Xcode]

**Comment by bwomsm1** [comment]
@mykola-mokhnach can you please help with this issue?

**Comment by bwomsm1** [comment]
Calling to
```
        self.driver_.set_clipboard(str(text).encode())
        self.driver_.set_clipboard_text(text)
```
either did not work

**Comment by mykola-mokhnach** [comment]
This is expected. In order to interact with the clipboard WDA application must be active. See https://developer.apple.com/forums/thread/706761

**Comment by bwomsm1** [comment]
> This is expected. In order to interact with the clipboard WDA application must be active. See https://developer.apple.com/forums/thread/706761

@mykola-mokhnach if I get you right, your link is referring to a case when the app is in background?
In my case the app was not in bg, it was in foreground

**Comment by mykola-mokhnach** [comment]
The request to fetch the clipboard context is coming from WebDriverAgent, not the app under test.

**Comment by bwomsm1** [comment]
@mykola-mokhnach @KazuCocoa thanks,
What is the easiest way to open WebAgentDriver app on iOS?

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions

**Comment by bwomsm1** [comment]
> Please use Appium forum to ask questions

ok, thanks
(https://github.com/appium/appium/discussions/18731)
