### ISSUE TITLE
Use the nox simulator to open the application flashover

### ISSUE THREAD

**Issue by Chen-Ban** [appium/appium#18743]
Here is the simple appium python-client code（）：

from appium import webdriver

desired_caps = {}
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '9'
desired_caps['deviceName'] = '127.0.0.1:62025'
desired_caps['appPackage'] = 'com.netease.lglr.yeshen'
desired_caps['appActivity'] = 'com.netease.lagrange.Client'
desired_caps['noReset'] = True
desired_caps['automationName']="UiAutomator2"
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

When I ran this code, appium's server log was all right and I got this result: POST /wd/hub/session 200 5701 ms-959, but on my emulator, I checked in the background afterwards and the emulator opened the software I wanted, but then it quit after a white screen.

Here is the complete log file.
[logcat.txt](https://github.com/appium/appium/files/11684152/logcat.txt)
Thanks a ton！！！！！！！

**Comment by mykola-mokhnach** [comment]
We do not support/maintain appium 1 anymore. Consider using the most recent uia2 driver version supplied with Appium 2
