### ISSUE TITLE
bug: On iOS Safari while running tests that involve window switching, it takes significant amount of time to open a new window and switch to it

### ISSUE THREAD

**Issue by SujaySawant** [appium/appium#18750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For the test that I'm running, the automation involves navigating through a website and then clicking on a link that opens up a new window. While I'm running this test on iOS Safari, the opening up of the new window and switching to it takes significant amount of time (40 seconds to 2 minutes). The same test if I run on Android or Desktop Chrome, the window switch happens quickly (2 to 5 seconds). This is happening when I'm running test on a local handheld device and on Public cloud. I've provided recording of the test execution on my local handheld device. For the execution on Public cloud, you can refer to [this](https://automate.browserstack.com/dashboard/v2/public-build/ZDArQ1pPeHVielVFQTZJZnpwSFV1M09ONHExeTNEMGVpZ3hleXFGbkJlQm1QYlRXZDlZUnhuWEVYaGF1Q1A5L0p1MWxDcnVCSlg1OWU3WEk3a2ZwSmc9PS0tTmdWZlVtMGo5alZTMnE2aXgwSURMZz09--633c7152dadb9a828ce9d4c9d0cc06e5daff1082) build

https://github.com/appium/appium/assets/82949654/fe190cad-7a8b-4c0e-92de-f9f027416dbe

### Expected Behavior

On iOS Safari, the opening up of the new window and switching to it should not take more that couple of seconds.

### Minimal Reproducible Example

[sample.java.txt](https://github.com/appium/appium/files/11706154/sample.java.txt)

### Environment

- Operating system: iOS
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 1.21.0
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s): io.appium:java-client: 7.5.1
- Appium plugin(s) and their version(s):
- Platform and version under test: iOS 15
- Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
We do not support or maintain Appium 1. Consider using the newest driver supplied with Appium 2

**Comment by mykola-mokhnach** [comment]
Closed because of no response
