### ISSUE TITLE
bug: `maxObjectCount exceeded` when checking `app_installed`

### ISSUE THREAD

**Issue by eyJhb** [appium/appium#18753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When check if the app `com.bhappdevelopment.containerapp` is installed on the phone, a error will be thorwn `Error:  maxObjectCount exceeded`.
This ONLY happens after the app has been installed, if it is not installed, it will just return `False`.

I haven't found other apps where this happens.

### Expected Behavior

That it returns `True` when the app is installed, instead of erroring out.

### Minimal Reproducible Example

1. Install the app in the appstore, id is `com.bhappdevelopment.containerapp` and link is `https://apps.apple.com/dk/app/online-personal-training/id1249635424?uo=4`
2. Initialise a iOS driver
3. Execute `driver.is_app_installed("com.bhappdevelopment.containerapp")`
4. See appium server crashing

```python
from appium import webdriver

ios_caps = {
    "appium:automationName": "XCUITest",
    "platformName": "iOS",
    "appium:udid": "auto",
    "appium:newCommandTimeout": 120,
}

driver = webdriver.Remote("http://localhost:4723", ios_caps, keep_alive=False)
driver.is_app_installed("com.bhappdevelopment.containerapp")
```

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`): 2.0.0-beta.71
  - Node.js version (output of `node --version`): v18.16.0
  - `npm` version (output of `npm --version`): 9.5.1
  - Last `appium` version which did _not_ exhibit the problem: Unknown 
- If running Appium Desktop, its version: 
- Appium driver(s) and their version(s): `xcuitest@4.31.0 (automationName 'XCUITest')`
- Appium plugin(s) and their version(s): Running private `go-ios` plugin, only affects driver creation.
- Platform and version under test: iPhone Xs version 16.5
- Real device or emulator/simulator: Real device

### Link to Appium Logs

https://gist.github.com/eyJhb/10af2d88ded445136ffce1d66f49d305

**Comment by mykola-mokhnach** [comment]
@tomriddly Could you please take a look?

**Comment by tomriddly** [comment]
`bplist-parser` set a limit of `maxObjectCount=32768`, this error will be thrown if numObjects read from header is larger than this value.
But it is weird to have so may objects. I will check for this app later.

**Comment by tomriddly** [comment]
I've got the root cause.
We are checking whether the app is installed by:
https://github.com/appium/appium-xcuitest-driver/blob/d809dd63c657d713d3e28085b8e991ea6b06f97c/lib/ios-deploy.js#LL171C3-L171C3
```js
      return (await service.lookupApplications({bundleIds: bundleId}))[bundleId];
```

The count of returning attributes of specific app `com.bhappdevelopment.containerapp` exceed the default maximum limit of the bplist-parser library which causes the issue.

Actually, we don't need all the attributes for checking installation. We can solve this just limit the return attributes by change the line to:
```
return (await service.lookupApplications({bundleIds: bundleId , returnAttributes: 'CFBundleIdentifier'}))[bundleId];
```
I'm not sure if this is the only part which should be modified. So, @mykola-mokhnach could you please make the pr?

**Comment by tomriddly** [comment]
If we need more attributes, we can set `returnAttributes` as a `string[]` like
```js
await service.lookupApplications({ bundleIds: 'com.bhappdevelopment.containerapp', returnAttributes: ['CFBundleIdentifier', 'CFBundleVersion'] })
```
AFAIK, `CFBundleVersion` is also used in some case. Maybe the wrapper function should make `returnAttributes` as  a parameter in `device.fetchAppInfo()`, and we only request the required key

**Comment by mykola-mokhnach** [comment]
Thanks for the hint @tomriddly 
Created a PR https://github.com/appium/appium-xcuitest-driver/pull/1753

**Comment by eyJhb** [comment]
I've tried the new release, and it seems to solve the issue for the particular app I mentioned.
Thanks for the prompt fix! Highly appreciated.

Closing issue as fixed :)
