### ISSUE TITLE
through automation script on Flutter application webelement getting clicked and status code showing 200 on console but no change is reflected on ui

### ISSUE THREAD

**Issue by Rahul1970** [appium/appium#18757]
through automation script on Flutter application webelement getting clicked and status code showing 200 but no change is reflected on ui.The issue persist on both emulator and real device. I am using java jdk 8 appium 1.22.3 android studio flamingo
I have tried to write xpath using different ways like through index and content-desc but the issue still persist.driver.findElement(By.xpath("//android.widget.ImageView[@content-desc='Leads']")).click();

**Comment by Rahul1970** [comment]
Hi mykola i am automating flutter application on mobile by using jdk 1.8 appium 1.22 android studio flamingo, Eclipse  and i am using uiautomatorviewer for native view element inspect and chrome//urls for webview element inspect. After a certain version of ui on mobile app my scripts written in java are not working for new ui and new apk version. when looking at the console i find that the scripts are getting passed with status code 200 but no change is reflected on ui as a result of those scripts running successfully.

**Comment by mykola-mokhnach** [comment]
- We do not maintain Appium 1 anymore. Consider switching to version 2
- Please provide a proper server log snippet along with proper repro steps, actual and expected results descriptions.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by Rahul1970** [comment]
Hi mykola,
                 As suggested by you i have used appium 2.0 version but the issue still persist. I am attching my logs for your reference.
  [38;5;0m[HTTP][0m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/ce9eb9c1-0523-4dea-8036-36534beab3a7/element[39m
[38;5;0m[HTTP][0m [90m{"using":"xpath","value":"//android.widget.Button[@index='0']"}[39m
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.Button[@index='0']","ce9eb9c1-0523-4dea-8036-36534beab3a7"]
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Waiting up to 30000 ms for condition
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Matched '/element' to command name 'findElement'
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Proxying [POST /element] to [POST http://127.0.0.1:8200/session/ff869601-f4ad-42f6-a604-078e5a89c3ea/element] with body: {"strategy":"xpath","selector":"//android.widget.Button[@index='0']","context":"","multiple":false}
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Got response with status 200: {"sessionId":"ff869601-f4ad-42f6-a604-078e5a89c3ea","value":{"ELEMENT":"00000000-0000-0032-0000-001a00000004","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0032-0000-001a00000004"}}
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0032-0000-001a00000004","ELEMENT":"00000000-0000-0032-0000-001a00000004"}
[38;5;0m[HTTP][0m [37m<-- POST /wd/hub/session/ce9eb9c1-0523-4dea-8036-36534beab3a7/element [39m[32m200[39m [90m163 ms - 137[39m
[38;5;0m[HTTP][0m [90m[39m
[38;5;0m[HTTP][0m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/ce9eb9c1-0523-4dea-8036-36534beab3a7/element/00000000-0000-0032-0000-001a00000004/click[39m
[38;5;0m[HTTP][0m [90m{"id":"00000000-0000-0032-0000-001a00000004"}[39m
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Calling AppiumDriver.click() with args: ["00000000-0000-0032-0000-001a00000004","ce9eb9c1-0523-4dea-8036-36534beab3a7"]
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Matched '/element/00000000-0000-0032-0000-001a00000004/click' to command name 'click'
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Proxying [POST /element/00000000-0000-0032-0000-001a00000004/click] to [POST http://127.0.0.1:8200/session/ff869601-f4ad-42f6-a604-078e5a89c3ea/element/00000000-0000-0032-0000-001a00000004/click] with body: {"element":"00000000-0000-0032-0000-001a00000004"}
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Got response with status 200: {"sessionId":"ff869601-f4ad-42f6-a604-078e5a89c3ea","value":null}
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Responding to client with driver.click() result: null
[38;5;0m[HTTP][0m [37m<-- POST /wd/hub/session/ce9eb9c1-0523-4dea-8036-36534beab3a7/element/00000000-0000-0032-0000-001a00000004/click [39m[32m200[39m [90m84 ms - 14[39m
[38;5;0m[HTTP][0m [90m[39m
[38;5;0m[HTTP][0m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/ce9eb9c1-0523-4dea-8036-36534beab3a7/element[39m
[38;5;0m[HTTP][0m [90m{"using":"xpath","value":"//android.widget.ImageView[@content-desc='Leads']"}[39m
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Calling AppiumDriver.findElement() with args: ["xpath","//android.widget.ImageView[@content-desc='Leads']","ce9eb9c1-0523-4dea-8036-36534beab3a7"]
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Waiting up to 30000 ms for condition
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Matched '/element' to command name 'findElement'
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Proxying [POST /element] to [POST http://127.0.0.1:8200/session/ff869601-f4ad-42f6-a604-078e5a89c3ea/element] with body: {"strategy":"xpath","selector":"//android.widget.ImageView[@content-desc='Leads']","context":"","multiple":false}
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Got response with status 200: {"sessionId":"ff869601-f4ad-42f6-a604-078e5a89c3ea","value":{"ELEMENT":"00000000-0000-0032-0000-004c00000004","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0032-0000-004c00000004"}}
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0032-0000-004c00000004","ELEMENT":"00000000-0000-0032-0000-004c00000004"}
[38;5;0m[HTTP][0m [37m<-- POST /wd/hub/session/ce9eb9c1-0523-4dea-8036-36534beab3a7/element [39m[32m200[39m [90m123 ms - 137[39m
[38;5;0m[HTTP][0m [90m[39m
[38;5;0m[HTTP][0m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/ce9eb9c1-0523-4dea-8036-36534beab3a7/element/00000000-0000-0032-0000-004c00000004/click[39m
[38;5;0m[HTTP][0m [90m{"id":"00000000-0000-0032-0000-004c00000004"}[39m
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Calling AppiumDriver.click() with args: ["00000000-0000-0032-0000-004c00000004","ce9eb9c1-0523-4dea-8036-36534beab3a7"]
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Matched '/element/00000000-0000-0032-0000-004c00000004/click' to command name 'click'
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Proxying [POST /element/00000000-0000-0032-0000-004c00000004/click] to [POST http://127.0.0.1:8200/session/ff869601-f4ad-42f6-a604-078e5a89c3ea/element/00000000-0000-0032-0000-004c00000004/click] with body: {"element":"00000000-0000-0032-0000-004c00000004"}
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Got response with status 200: {"sessionId":"ff869601-f4ad-42f6-a604-078e5a89c3ea","value":null}
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Responding to client with driver.click() result: null
[38;5;0m[HTTP][0m [37m<-- POST /wd/hub/session/ce9eb9c1-0523-4dea-8036-36534beab3a7/element/00000000-0000-0032-0000-004c00000004/click [39m[32m200[39m [90m81 ms - 14[39m
[38;5;0m[HTTP][0m [90m[39m
[38;5;0m[HTTP][0m [37m-->[39m [37mDELETE[39m [37m/wd/hub/session/ce9eb9c1-0523-4dea-8036-36534beab3a7[39m
[38;5;0m[HTTP][0m [90m{}[39m
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Calling AppiumDriver.deleteSession() with args: ["ce9eb9c1-0523-4dea-8036-36534beab3a7"]
[debug] [38;5;16m[AppiumDriver@62e0][0m Event 'quitSessionRequested' logged at 1689145665397 (12:37:45 GMT+0530 (India Standard Time))
[38;5;16m[AppiumDriver@62e0][0m Removing session ce9eb9c1-0523-4dea-8036-36534beab3a7 from our master session list
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Deleting UiAutomator2 session
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Deleting UiAutomator2 server session
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Matched '/' to command name 'deleteSession'
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Proxying [DELETE /] to [DELETE http://127.0.0.1:8200/session/ff869601-f4ad-42f6-a604-078e5a89c3ea] with no body
[debug] [38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Got response with status 200: {"sessionId":"ff869601-f4ad-42f6-a604-078e5a89c3ea","value":null}
[debug] [38;5;64m[ADB][0m Running 'C:\Users\Rahul Singh\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
[debug] [38;5;64m[ADB][0m Running 'C:\Users\Rahul Singh\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.mobileapp.offlineplay'
[debug] [38;5;112m[Instrumentation][0m .
[debug] [38;5;112m[Instrumentation][0m Time: 124.287

[debug] [38;5;112m[Instrumentation][0m 

[debug] [38;5;112m[Instrumentation][0m OK (1 test)
[debug] [38;5;96m[Logcat][0m Stopping logcat capture
[debug] [38;5;64m[ADB][0m Removing forwarded port socket connection: 8200 
[debug] [38;5;64m[ADB][0m Running 'C:\Users\Rahul Singh\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:8200'
[38;5;32m[AndroidUiautomator2Driver@e5f4 (ce9eb9c1)][0m Restoring hidden api policy to the device default configuration
[debug] [38;5;64m[ADB][0m Running 'C:\Users\Rahul Singh\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s emulator-5554 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[debug] [38;5;16m[AppiumDriver@62e0][0m Event 'quitSessionFinished' logged at 1689145665886 (12:37:45 GMT+0530 (India Standard Time))
[debug] [38;5;16m[AppiumDriver@62e0][0m Received response: null
[debug] [38;5;16m[AppiumDriver@62e0][0m But deleting session, so not returning
[debug] [38;5;16m[AppiumDriver@62e0][0m Responding to client with driver.deleteSession() result: null
[38;5;0m[HTTP][0m [37m<-- DELETE /wd/hub/session/ce9eb9c1-0523-4dea-8036-36534beab3a7 [39m[32m200[39m [90m493 ms - 14[39m
[38;5;0m[HTTP][0m [90m[39m

Total tests run: 1, Passes: 1, Failures: 0, Skips: 0

**Comment by Rahul1970** [comment]
In the logs the first element "//android.widget.Button[@index='0']" get sclicked and the ui changes. but the second element "//android.widget.ImageView[@content-desc='Leads']" is shown to be clicked in the console but the ui stays unchanged

**Comment by mykola-mokhnach** [comment]
Clicks are processed by Google's UiAutomator framework itself. We cannot influence that. You could try to click by absolute coordinates s a possible workaround or report your issue to Google.

**Comment by Rahul1970** [comment]
Hi mykola if you could let me know which community on github or email to reach out to for this issue.

**Comment by mykola-mokhnach** [comment]
https://issuetracker.google.com/issues and/or https://github.com/appium-userland/appium-flutter-driver
