### ISSUE TITLE
bug: <Failed to create session. An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'UiAutomator2' and platformName 'Andriod'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Driver 'uiautomator2' supports automationName 'UiAutomator2', but Appium could not find support for platformName 'Andriod'. Supported platformNames are: ["Android"])>

### ISSUE THREAD

**Issue by pinkikukreti** [appium/appium#18752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

node --version
v18.16.0
NPM --version
9.5.1
appium --version
2.0.0-beta.71
uiautomator2@2.25.3 [installed (npm
<img width="1119" alt="Screenshot22" src="https://github.com/appium/appium/assets/48516830/22eab288-0593-41be-bd67-2d4286d0a640">

Tried changing "Andriod" and "UiAutomator2" with upper case and lower case 

### Expected Behavior

It should start inspecting the device 

### Minimal Reproducible Example

NA

### Environment

- Operating system:
- If running via `appium` CLI...
  - Appium CLI version (output of `appium --version`):
  - Node.js version (output of `node --version`):
  - `npm` version (output of `npm --version`): 
  - Last `appium` version which did _not_ exhibit the problem: 
- If running Appium Desktop, its version:
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by eglitise** [comment]
You have a typo in your capabilities list. It's `Android`, not `Andriod`.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
