### ISSUE TITLE
Issue with added sharp dependency

### ISSUE THREAD

**Issue by camoles** [appium/appium#18762]
Hello everyone. Thank you for all the effort put into appium. I am tasked with packaging appium for an environment with special requirements, and one of them is that there should be no network access during build time. The "sharp" package dependency recently added does reach for the network, as it tries to get a compiled binary. That means I need to find a way around this, ant this is the reason I am asking for your help. Please bear with me and keep in mind that I am not a node developer.

Right now we are running appium 2 beta 57, for which we have saved a package-lock.json. So far we are getting appium from npm registry to package. We need to upgrade because of compatibility issues with xcode 14.3, and the recent inclusion of sharp on beta 67 makes it hard due to the requirements of our environment. We are currently unable to npm install appium for the latest beta release (currently 71). Not only that, but also due to the way that node requirements work (I guess), we are currently unable to use anything newer than beta 47, as the recent inclusion "contaminates" previous versions (I believe due to the "caret" version dependency). That means that, if you now npm install appium@2.0.0-beta.48, the resulting package-lock.json WILL depend on sharp, even though the last commit on beta 48 happened in 2022, and  the sharp dependency was only introduced on April 2023.

I see that a recent commit intends to [make sharp an optional dependency](https://github.com/appium/appium/commit/798274767718783b828c6ddfe5d92e273813dbe9). So my line of thinking here to solve my problem goes, okay, so maybe I should just use the most recent version of appium from github, since that change have not reached a release yet. Now my problem is, how do I even build appium from source? As far as I can tell it is not currently documented. I went the most obvious way and tried to just clone the repo and run npm install at the root of the project. That builds me a package-lock.json which does contain sharp as a dependency, even if I tell npm to not install optional dependencies. Same happens if I try to use yarn telling it not to use the optional dependencies; sharp still is there in the generated yarn.lock. If I run node_modules/.bin/appium --version, it tells me I have beta 71. I am not sure I am doing the right process to build from source locally though; is it npm install the right way to do it? Am I actually running the version I cloned instead of beta 71 as reported?

Any help or pointers with this will be greatly appreciated. A new release that actually makes sharp optional, that is, it won´t be in the generated lock file, would solve my problems. Hints on how to properly build from the cloned revision could also be helpful. 

Thank you very much for any help you are able to provide.

**Comment by mykola-mokhnach** [comment]
Yes, after a new server version is released where it is moved to optional dependencies.

**Comment by mykola-mokhnach** [comment]
If we ask gently then I believe @jlipps or @boneskull could do it soon.

**Comment by jlipps** [comment]
`appium@2.0.0-rc.1` has been released
