### ISSUE TITLE
Problem with launchApp and activationApp

### ISSUE THREAD

**Issue by jaroslawjalocha** [appium/appium#18760]
Hey, I have a problem with launching the application on my IOS 16.1, I have appium 2.0, although I use the correct dependencies, the driver.launchApp() and driver.activationApp() functions do not work. The application does not start. My capabilities:
 "platformName": "IOS",
    "appium:platformVersion": "15.0",
    "appium:udid": "001db2ed975d5d505109bc112a629488561ec3c0",
    "appium:deviceName": "IPhone X",
    "appium:autoLaunch": true,
    "appium:automationName": "XCUITest",
    "appium:autoGrantPermissions": true,
    "appium:bundleid": "XXX",
    "appium:systemPort": 4724
Logs from appium: 
er Time))
[Appium] Attempting to find matching driver for automationName 'XCUITest' and platformName 'IOS'
[Appium] The 'xcuitest' driver was installed and matched caps.
[Appium] Will require it at /Users/neontri-jj/.appium/node_modules/appium-xcuitest-driver
[debug] [Appium] Requiring driver at /Users/neontri-jj/.appium/node_modules/appium-xcuitest-driver
[AppiumDriver@136b] Appium v2.0.0-beta.66 creating new XCUITestDriver (v4.12.2) session
[AppiumDriver@136b] Checking BaseDriver versions for Appium and XCUITestDriver
[AppiumDriver@136b] Appium's BaseDriver version is 9.3.7
[AppiumDriver@136b] XCUITestDriver's BaseDriver version is 9.3.7
[debug] [XCUITestDriver@726b] Creating session with W3C capabilities: {
[debug] [XCUITestDriver@726b]   "alwaysMatch": {
[debug] [XCUITestDriver@726b]     "platformName": "IOS",
[debug] [XCUITestDriver@726b]     "appium:platformVersion": "15.0",
[debug] [XCUITestDriver@726b]     "appium:udid": "001db2ed975d5d505109bc112a629488561ec3c0",
[debug] [XCUITestDriver@726b]     "appium:deviceName": "IPhone X",
[debug] [XCUITestDriver@726b]     "appium:autoLaunch": true,
[debug] [XCUITestDriver@726b]     "appium:automationName": "XCUITest",
[debug] [XCUITestDriver@726b]     "appium:autoGrantPermissions": true,
[debug] [XCUITestDriver@726b]     "appium:bundleid": "XXX",
[debug] [XCUITestDriver@726b]     "appium:systemPort": 4724
[debug] [XCUITestDriver@726b]   },
[debug] [XCUITestDriver@726b]   "firstMatch": [
[debug] [XCUITestDriver@726b]     {}
[debug] [XCUITestDriver@726b]   ]
[debug] [XCUITestDriver@726b] }
[XCUITestDriver@726b] The following capabilities were provided, but are not recognized by Appium:
[XCUITestDriver@726b]   autoGrantPermissions
[XCUITestDriver@726b]   bundleid
[XCUITestDriver@726b]   systemPort
[XCUITestDriver@726b] The desired capabilities include neither an app nor a bundleId. WebDriverAgent will be started without the default app
[XCUITestDriver@726b (4ef95222)] Session created with session id: 4ef95222-33e4-4814-93ac-b3d495ebdf4b
[debug] [XCUITest] Current user: 'neontri-jj'
[debug] [XCUITestDriver@726b (4ef95222)] Available devices: 001db2ed975d5d505109bc112a629488561ec3c0
[debug] [XCUITest] Creating iDevice object with udid '001db2ed975d5d505109bc112a629488561ec3c0'
[XCUITestDriver@726b (4ef95222)] Determining device to run tests on: udid: '001db2ed975d5d505109bc112a629488561ec3c0', real device: true
[debug] [XCUITestDriver@726b (4ef95222)] Event 'xcodeDetailsRetrieved' logged at 1686661257374 (15:00:57 GMT+0200 (Central European Summer Time))
[debug] [XCUITestDriver@726b (4ef95222)] Event 'appConfigured' logged at 1686661257374 (15:00:57 GMT+0200 (Central European Summer Time))
[debug] [XCUITestDriver@726b (4ef95222)] Event 'resetStarted' logged at 1686661257374 (15:00:57 GMT+0200 (Central European Summer Time))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [XCUITestDriver@726b (4ef95222)] Event 'resetComplete' logged at 1686661257374 (15:00:57 GMT+0200 (Central European Summer Time))
[XCUITestDriver@726b (4ef95222)] Using WDA path: '/Users/neontri-jj/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
[XCUITestDriver@726b (4ef95222)] Using WDA agent: '/Users/neontri-jj/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] Crash reports root '/Users/neontri-jj/Library/Logs/CrashReporter/MobileDevice/iPhone X (Eldurnbel) 47' does not exist. Got nothing to gather.
[debug] [XCUITestDriver@726b (4ef95222)] Event 'logCaptureStarted' logged at 1686661257618 (15:00:57 GMT+0200 (Central European Summer Time))
[XCUITestDriver@726b (4ef95222)] Setting up real device
[debug] [XCUITestDriver@726b (4ef95222)] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device 001db2ed975d5d505109bc112a629488561ec3c0 on local port 8100, device port 8100
[debug] [DevCon Factory] Cached connections count: 1
[DevCon Factory] Found cached connections on port #8100: ["001db2ed975d5d505109bc112a629488561ec3c0:8100"]
[DevCon Factory] Port #8100 is busy. Did you quit the previous driver session(s) properly?
[DevCon Factory] Trying to release the port
[DevCon Factory] Releasing the listener for '001db2ed975d5d505109bc112a629488561ec3c0:8100'
[debug] [iProxy@001db2ed:8100] Closing the connection
[iProxy@001db2ed:8100] The connection has been closed
[DevCon Factory] Port #8100 has been successfully released after 2ms
[DevCon Factory] Successfully requested the connection for 001db2ed975d5d505109bc112a629488561ec3c0:8100
[debug] [XCUITestDriver@726b (4ef95222)] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"16.1","version":"16.1.2"},"ios":{"ip":"192.168.1.20"},"ready":true,"build":{"time":"Jun 13 2023 13:46:07","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"078D3ED1-9BF7-4611-B80F-7BDD54A51EF4"}
[debug] [XCUITestDriver@726b (4ef95222)] Upgrade timestamp of the currently bundled WDA: 1683121554567
[debug] [XCUITestDriver@726b (4ef95222)] Upgrade timestamp of the WDA on the device: undefined
[XCUITestDriver@726b (4ef95222)] Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [XCUITestDriver@726b (4ef95222)] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [XCUITestDriver@726b (4ef95222)] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [XCUITestDriver@726b (4ef95222)] Event 'wdaStartAttempted' logged at 1686661257706 (15:00:57 GMT+0200 (Central European Summer Time))
[XCUITestDriver@726b (4ef95222)] Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"16.1","version":"16.1.2"},"ios":{"ip":"192.168.1.20"},"ready":true,"build":{"time":"Jun 13 2023 13:46:07","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"078D3ED1-9BF7-4611-B80F-7BDD54A51EF4"}
[debug] [XCUITestDriver@726b (4ef95222)] Event 'wdaSessionAttempted' logged at 1686661257716 (15:00:57 GMT+0200 (Central European Summer Time))
[debug] [XCUITestDriver@726b (4ef95222)] Sending createSession command to WDA
[debug] [XCUITestDriver@726b (4ef95222)] Matched '/session' to command name 'createSession'
[debug] [XCUITestDriver@726b (4ef95222)] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true,"forceAppLaunch":true,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":true}],"alwaysMatch":{}}}
[debug] [XCUITestDriver@726b (4ef95222)] Got response with status 200: {"value":{"sessionId":"E476ACC5-566C-48CF-B8A9-F2DB229A929E","capabilities":{"device":"iphone","browserName":" ","sdkVersion":"16.1.2","CFBundleIdentifier":"com.apple.springboard"}},"sessionId":"E476ACC5-566C-48CF-B8A9-F2DB229A929E"}
[XCUITestDriver@726b (4ef95222)] Determined the downstream protocol as 'W3C'
[debug] [XCUITestDriver@726b (4ef95222)] Event 'wdaSessionStarted' logged at 1686661257919 (15:00:57 GMT+0200 (Central European Summer Time))
[debug] [XCUITestDriver@726b (4ef95222)] Event 'wdaStarted' logged at 1686661257920 (15:00:57 GMT+0200 (Central European Summer Time))
[XCUITestDriver@726b (4ef95222)] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [XCUITestDriver@726b (4ef95222)] Event 'orientationSet' logged at 1686661257920 (15:00:57 GMT+0200 (Central European Summer Time))
[debug] [BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[AppiumDriver@136b] New XCUITestDriver session created successfully, session 4ef95222-33e4-4814-93ac-b3d495ebdf4b added to master session list
[debug] [AppiumDriver@136b] Event 'newSessionStarted' logged at 1686661257921 (15:00:57 GMT+0200 (Central European Summer Time))
[debug] [XCUITestDriver@726b (4ef95222)] Cached the protocol value 'W3C' for the new session 4ef95222-33e4-4814-93ac-b3d495ebdf4b
[debug] [XCUITestDriver@726b (4ef95222)] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"IOS","platformVersion":"15.0","udid":"001db2ed975d5d505109bc112a629488561ec3c0","deviceName":"IPhone X","autoLaunch":true,"automationName":"XCUITest","autoGrantPermissions":true,"bundleid":"com.neontri.ibmp.debug.iPKO","systemPort":4724}}
[HTTP] <-- POST /wd/hub/session 200 592 ms - 528
[HTTP] 
[HTTP] --> GET /wd/hub/session/4ef95222-33e4-4814-93ac-b3d495ebdf4b/window/rect
[HTTP] {}
[debug] [XCUITestDriver@726b (4ef95222)] Calling AppiumDriver.getWindowRect() with args: ["4ef95222-33e4-4814-93ac-b3d495ebdf4b"]
[debug] [XCUITestDriver@726b (4ef95222)] Executing command 'getWindowRect'
[debug] [XCUITestDriver@726b (4ef95222)] Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/E476ACC5-566C-48CF-B8A9-F2DB229A929E/window/size] with no body
[HTTP] --> POST /wd/hub/session/4ef95222-33e4-4814-93ac-b3d495ebdf4b/appium/app/launch
[HTTP] {}
[debug] [XCUITestDriver@726b (4ef95222)] Calling AppiumDriver.launchApp() with args: ["4ef95222-33e4-4814-93ac-b3d495ebdf4b"]
[debug] [XCUITestDriver@726b (4ef95222)] Executing command 'launchApp'
[debug] [XCUITestDriver@726b (4ef95222)] Got response with status 200: {"value":{"width":375,"height":812},"sessionId":"E476ACC5-566C-48CF-B8A9-F2DB229A929E"}
[debug] [XCUITestDriver@726b (4ef95222)] Responding to client with driver.getWindowRect() result: {"width":375,"height":812,"x":0,"y":0}
[HTTP] <-- GET /wd/hub/session/4ef95222-33e4-4814-93ac-b3d495ebdf4b/window/rect 200 251 ms - 48
[HTTP] 
[debug] [XCUITest] Current user: 'neontri-jj'
[debug] [XCUITestDriver@726b (4ef95222)] Available devices: 001db2ed975d5d505109bc112a629488561ec3c0
[debug] [XCUITest] Creating iDevice object with udid '001db2ed975d5d505109bc112a629488561ec3c0'
[XCUITestDriver@726b (4ef95222)] Determining device to run tests on: udid: '001db2ed975d5d505109bc112a629488561ec3c0', real device: true
[debug] [XCUITestDriver@726b (4ef95222)] Event 'xcodeDetailsRetrieved' logged at 1686661258269 (15:00:58 GMT+0200 (Central European Summer Time))
[debug] [XCUITestDriver@726b (4ef95222)] Event 'appConfigured' logged at 1686661258269 (15:00:58 GMT+0200 (Central European Summer Time))
[debug] [XCUITestDriver@726b (4ef95222)] Event 'resetStarted' logged at 1686661258269 (15:00:58 GMT+0200 (Central European Summer Time))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [XCUITestDriver@726b (4ef95222)] Event 'resetComplete' logged at 1686661258269 (15:00:58 GMT+0200 (Central European Summer Time))
[XCUITestDriver@726b (4ef95222)] Using WDA path: '/Users/neontri-jj/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
[XCUITestDriver@726b (4ef95222)] Using WDA agent: '/Users/neontri-jj/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[XCUITest] Trying to start iOS log capture but it has already started!
[debug] [XCUITestDriver@726b (4ef95222)] Event 'logCaptureStarted' logged at 1686661258285 (15:00:58 GMT+0200 (Central European Summer Time))
[XCUITestDriver@726b (4ef95222)] Setting up real device
[debug] [XCUITestDriver@726b (4ef95222)] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device 001db2ed975d5d505109bc112a629488561ec3c0 on local port 8100, device port 8100
[debug] [DevCon Factory] Cached connections count: 1
[DevCon Factory] Found cached connections on port #8100: ["001db2ed975d5d505109bc112a629488561ec3c0:8100"]
[DevCon Factory] Port #8100 is busy. Did you quit the previous driver session(s) properly?
[DevCon Factory] Trying to release the port
[DevCon Factory] Releasing the listener for '001db2ed975d5d505109bc112a629488561ec3c0:8100'
[debug] [iProxy@001db2ed:8100] Closing the connection
[DevCon Factory] Port #8100 has been successfully released after 2ms
[DevCon Factory] Successfully requested the connection for 001db2ed975d5d505109bc112a629488561ec3c0:8100
[debug] [XCUITestDriver@726b (4ef95222)] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"16.1","version":"16.1.2"},"ios":{"ip":"192.168.1.20"},"ready":true,"build":{"time":"Jun 13 2023 13:46:07","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"E476ACC5-566C-48CF-B8A9-F2DB229A929E"}
[debug] [XCUITestDriver@726b (4ef95222)] Upgrade timestamp of the currently bundled WDA: 1683121554567
[debug] [XCUITestDriver@726b (4ef95222)] Upgrade timestamp of the WDA on the device: undefined
[XCUITestDriver@726b (4ef95222)] Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [XCUITestDriver@726b (4ef95222)] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [XCUITestDriver@726b (4ef95222)] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [XCUITestDriver@726b (4ef95222)] Event 'wdaStartAttempted' logged at 1686661258445 (15:00:58 GMT+0200 (Central European Summer Time))
[XCUITestDriver@726b (4ef95222)] Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"message":"WebDriverAgent is ready to accept commands","state":"success","os":{"testmanagerdVersion":28,"name":"iOS","sdkVersion":"16.1","version":"16.1.2"},"ios":{"ip":"192.168.1.20"},"ready":true,"build":{"time":"Jun 13 2023 13:46:07","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"}},"sessionId":"E476ACC5-566C-48CF-B8A9-F2DB229A929E"}
[debug] [XCUITestDriver@726b (4ef95222)] Event 'wdaSessionAttempted' logged at 1686661258478 (15:00:58 GMT+0200 (Central European Summer Time))
[debug] [XCUITestDriver@726b (4ef95222)] Sending createSession command to WDA
[debug] [XCUITestDriver@726b (4ef95222)] Matched '/session' to command name 'createSession'
[debug] [XCUITestDriver@726b (4ef95222)] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true,"forceAppLaunch":true,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":true}],"alwaysMatch":{}}}
[debug] [XCUITestDriver@726b (4ef95222)] Got response with status 200: {"value":{"sessionId":"8C28A83F-EDAB-40EF-865E-8B9DE37729C1","capabilities":{"device":"iphone","browserName":" ","sdkVersion":"16.1.2","CFBundleIdentifier":"com.apple.springboard"}},"sessionId":"8C28A83F-EDAB-40EF-865E-8B9DE37729C1"}
[XCUITestDriver@726b (4ef95222)] Determined the downstream protocol as 'W3C'
[debug] [XCUITestDriver@726b (4ef95222)] Event 'wdaSessionStarted' logged at 1686661258653 (15:00:58 GMT+0200 (Central European Summer Time))
[debug] [XCUITestDriver@726b (4ef95222)] Event 'wdaStarted' logged at 1686661258653 (15:00:58 GMT+0200 (Central European Summer Time))
[XCUITestDriver@726b (4ef95222)] Skipping setting of the initial display orientation. Set the "orientation" capability to either "LANDSCAPE" or "PORTRAIT", if this is an undesired behavior.
[debug] [XCUITestDriver@726b (4ef95222)] Event 'orientationSet' logged at 1686661258654 (15:00:58 GMT+0200 (Central European Summer Time))
[XCUITestDriver@726b (4ef95222)] Successfully launched the 'undefined' app.
[debug] [XCUITestDriver@726b (4ef95222)] Responding to client with driver.launchApp() result: null
[HTTP] <-- POST /wd/hub/session/4ef95222-33e4-4814-93ac-b3d495ebdf4b/appium/app/launch 200 622 ms - 14
[HTTP] 
[HTTP] --> POST /wd/hub/session/4ef95222-33e4-4814-93ac-b3d495ebdf4b/element
[HTTP] {"using":"xpath","value":"//XCUIElementTypeButton[@name=\"LoggedOutDashboard_btn_Primary\"]"}
[debug] [XCUITestDriver@726b (4ef95222)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeButton[@name=\"LoggedOutDashboard_btn_Primary\"]","4ef95222-33e4-4814-93ac-b3d495ebdf4b"]
[debug] [XCUITestDriver@726b (4ef95222)] Executing command 'findElement'
[debug] [XCUITestDriver@726b (4ef95222)] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[debug] [XCUITestDriver@726b (4ef95222)] Waiting up to 0 ms for condition
[debug] [XCUITestDriver@726b (4ef95222)] Matched '/element' to command name 'findElement'
[debug] [XCUITestDriver@726b (4ef95222)] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/8C28A83F-EDAB-40EF-865E-8B9DE37729C1/element] with body: {"using":"xpath","value":"//XCUIElementTypeButton[@name=\"LoggedOutDashboard_btn_Primary\"]"}
[XCUITestDriver@726b (4ef95222)] Got response with status 404: {"value":{"error":"no such element","message":"unable to find an element using 'xpath', value '//XCUIElementTypeButton[@name=\"LoggedOutDashboard_btn_Primary\"]'","traceback":"(\n\t0   WebDriverAgentLib                   0x0000000103cfc210 FBNoSuchElementErrorResponseForRequest + 252\n\t1   WebDriverAgentLib                   0x0000000103cfc040 +[FBFindElementCommands handleFindElement:] + 308\n\t2   WebDriverAgentLib                   0x0000000103cc3744 -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t3   WebDriverAgentLib                   0x0000000103cafdb0 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 400\n\t4   WebDriverAgentLib                   0x0000000103ce465c -[RoutingHTTPServer handleRoute:withRequest:response:] + 160\n\t5   WebDriverAgentLib                   0x0000000103ce50e8 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t6   libdispatch.dylib                   0x00000001c505e7c8 19F4CD59-AB92-3ED4-9730-174FA4B1468E + 4...
[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError
[debug] [XCUITestDriver@726b (4ef95222)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [XCUITestDriver@726b (4ef95222)]     at XCUITestDriver.doNativeFind (/Users/neontri-jj/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:129:11)
[debug] [XCUITestDriver@726b (4ef95222)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [XCUITestDriver@726b (4ef95222)]     at XCUITestDriver.findNativeElementOrElements (/Users/neontri-jj/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:89:10)
[debug] [XCUITestDriver@726b (4ef95222)]     at XCUITestDriver.findElOrEls (/Users/neontri-jj/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:22:12)
[debug] [XCUITestDriver@726b (4ef95222)]     at XCUITestDriver.findElOrElsWithProcessing (/Users/neontri-jj/.nvm/versions/node/v18.13.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:66:14)
[debug] [XCUITestDriver@726b (4ef95222)]     at XCUITestDriver.findElement (/Users/neontri-jj/.nvm/versions/node/v18.13.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:13:12)
[HTTP] <-- POST /wd/hub/session/4ef95222-33e4-4814-93ac-b3d495ebdf4b/element 404 6530 ms - 1083
[HTTP] 
[

**Comment by jaroslawjalocha** [comment]
Successfully launched the 'undefined' app.
[debug] [XCUITestDriver@726b (4ef95222)] Responding to client with driver.launchApp() result: null
[HTTP] <-- POST /wd/hub/session/4ef95222-33e4-4814-93ac-b3d495ebdf4b/appium/app/launch 200 622 ms - 14

**Comment by eglitise** [comment]
Capability names are case sensitive. Please change `appium:bundleid` to `appium:bundleId` and try again.

**Comment by eglitise** [comment]
Also, the XCUITest driver does not support UiAutomator2 driver's `appium:systemPort` and `appium:autoGrantPermissions` capabilities (you can see in the log that they are not recognised).
For `appium:systemPort`, you can use `appium:wdaLocalPort` instead.
For `appium:autoGrantPermissions`, the closest thing would probably be `appium:autoAcceptAlerts`. If you're using a simulator, you can also take a look at `appium:permissions`.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
