### ISSUE TITLE
There is a link in the appium-xcuitest-driver documentation that goes to a 404 page

### ISSUE THREAD

**Issue by ollie-iterators** [appium/appium#18767]
There is a link in the documentation for appium-xcuitest-driver that is named "None" that goes to a 404 page. The page that the link goes to is: https://appium.github.io/appium-xcuitest-driver/4.32/reference/commands/appium-xcuitest-driver.md.

The button that you press to see the link with the 404 error:
<img width="1187" alt="2023-06-14_10-14-08" src="https://github.com/appium/appium/assets/46904826/1d391b76-9c74-4d75-a884-2d64905bee83">

The link with the 404 error:
<img width="1186" alt="2023-06-14_10-14-23" src="https://github.com/appium/appium/assets/46904826/6a745ef7-bdac-4ebb-8cc3-e8fa7b654089">

**Comment by jlipps** [comment]
This was just fixed.
