### ISSUE TITLE
update display of curious command return types

### ISSUE THREAD

**Issue by boneskull** [appium/appium#18763]
In the command reference documentation, those commands which return `void`, `undefined` or `null` will all be displayed as `null`.

There are more cases which should be covered:

- **Fix:** Commands which return `T|undefined` will still display this verbatim.  Essentially, any occurrence of the above nullish types  within a union should be displayed as `null`.  I think I'm probably going to be the only person able to fix this for now, but it's also not a high priority.
- Commands which return undocumented types will likely display as `any` (if they display at all).  The extension author should address this by adding the expected return type.  Don't know if the status quo here is fine or not.  Maybe display `object`?  Don't worry about it?
- **Fix:** Commands can return `unknown` (e.g. `getLog()`). _Why_ these return `unknown` is a separate issue, and needs to also be addressed, but: `unknown` should not be displayed. Use same strategy as above?

**Comment by jlipps** [comment]
> but it's also not a high priority.

👍 

> Commands which return undocumented types will likely display as any (if they display at all). The extension author should address this by adding the expected return type. Don't know if the status quo here is fine or not. Maybe display object? Don't worry about it?

I think `any` is fine for now. If someone complains we can just document the types better.

> Commands can return unknown (e.g. getLog()). Why these return unknown is a separate issue, and needs to also be addressed, but: unknown should not be displayed. Use same strategy as above?

I'm not off the top of my head sure why getLog would return unknown, probably because different drivers return different formats for historical reasons. Flagging as `any` is probably OK.
