### ISSUE TITLE
bug: Cannot take a screenshot with iOS 14 simulator + mjpeg server

### ISSUE THREAD

**Issue by rerorero** [appium/appium#18779]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

MJPE server endpoint never responds with a screenshot. Appium server keeps logging this error.
```
2023-06-16 10:31:04:655 [Xcode] [Xcode] 2023-06-16 19:31:04.651737+0900 WebDriverAgentRunner-Runner[85604:2599354] Error Domain=com.facebook.WebDriverAgent Code=1 "Cannot take a screenshot within 20000 ms timeout" UserInfo={NSLocalizedDescription=Cannot take a screenshot within 20000 ms timeout}
```

### Expected Behavior

MJPE server endpoint returns a screenshot.

### Minimal Reproducible Example

Use WDA v5.4.0 or later.
Start a new session with Appium inspector
```
{
  "platformName": "iOS",
  "appium:automationName": "XCUITest",
  "appium:platformVersion": "14.4",
  "appium:deviceName": "iPhone 12 Pro",
  "appium:mjpegServerPort": 9100
}
```
Open http://localhost:9100

### Environment

- Operating system: Mac OS + iOS simulator
- Appium server version (output of `appium --version`): 2.0.0-rc.3
- Appium driver(s) and their version(s): xcuitest@4.32.3 and WDA v5.5.0
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v16.15.1
- `npm` version (output of `npm --version`): 8.11.0op
- Last component(s) version which did _not_ exhibit the problem: WDA v5.3.2
- Platform and version under test: Xcode 14.2
- Real device or emulator/simulator: simulator

### Link to Appium Logs

https://gist.github.com/rerorero/e1b92a1bb9bb31c80bd635b5018cf796

### Futher Information

Looks like this issue happens since WebDriverAgent v5.4.0. I confirmed that it has no issue with v5.3.2.
Also, it reproduces with iOS14.4 but iOS 15.2 is okay.
i.e. I only see issue with iOS14.4 and WDA v5.4.0+

I found [this comment](https://github.com/appium/WebDriverAgent/pull/721#discussion_r1222509149), that sounds to me that iOS14.2 should be still working, is it correct? or no longer supported?

**Comment by mykola-mokhnach** [comment]
Yes, this is correct. We are only looking to support iOS 15 and 16 (+17-beta)
iOS 14 was built using Xcode 12 SDK, which we do not support anymore

**Comment by rerorero** [comment]
Thanks, Then let me close this issue.

**Comment by KazuCocoa** [comment]
fyi:
https://github.com/appium/appium-xcuitest-driver/blob/master/CHANGELOG.md#4280-2023-05-14
https://github.com/appium/WebDriverAgent/blob/master/CHANGELOG.md#500-2023-05-14
