### ISSUE TITLE
bug: <Android emulator gets closed on running appium test cases>

### ISSUE THREAD

**Issue by krishnaChaitanyaAripaka** [appium/appium#18772]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Due to appium, android emulator gets closed very frequently. May be once in every 5 - 10 minutes 

### Expected Behavior

Emulator should never get closed 

### Minimal Reproducible Example

1. Run Appium server
2. Open android emulator 
3. Run appium test on android emulator for react native project
4. Observer running the test, emulator gets closed 

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Futher Information

INFO    | Android emulator version 32.1.12.0 (build_id 9751036) (CL:N/A)
INFO    | Found systemPath /Users/aripaka.chaitanya/Library/Android/sdk/system-images/android-30/google_apis/arm64-v8a/
INFO    | Storing crashdata in: /tmp/android-aripaka.chaitanya/emu-crash.db, detection is enabled
INFO    | Duplicate loglines will be removed, if you wish to see each indiviudal line launch with the -log-nofilter flag.
WARNING | Please update the emulator to one that supports the feature(s): Vulkan
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_new_posture_requested(int) ((null):0, (null))
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_dismiss_posture_selection_dialog() ((null):0, (null))
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_new_resizable_requested(PresetEmulatorSizeType) ((null):0, (null))
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_dismiss_resizable_dialog() ((null):0, (null))
INFO    | Crash reports will be automatically uploaded to: https://clients2.google.com/cr/report
WARNING | cannot add library /Users/aripaka.chaitanya/Library/Android/sdk/emulator/qemu/darwin-aarch64/lib64/vulkan/libvulkan.dylib: failed
INFO    | added library /Users/aripaka.chaitanya/Library/Android/sdk/emulator/lib64/vulkan/libvulkan.dylib
WARNING | *** No gRPC protection active, consider launching with the -grpc-use-jwt flag.***
INFO    | Started GRPC server at 127.0.0.1:8554, security: Local, auth: none
INFO    | Advertising in: /Users/aripaka.chaitanya/Library/Caches/TemporaryItems/avd/running/pid_8147.ini
INFO    | Setting display: 0 configuration to: 1080x2340, dpi: 440x440
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600003606640, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=3 ts=0 pos=0,0 scn=566.547,243.595 gbl=566.547,243.595 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-566.547,-243.595 last=-566.547,-243.595 Δ 566.547,243.595) : no target window ((null):0, (null))
INFO    | Boot completed in 17054 ms
INFO    | Increasing screen off timeout, logcat buffer size to 2M.
INFO    | Revoking microphone permissions for Google App.
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600003606640, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=2 ts=0 pos=0,0 scn=565.064,101.496 gbl=565.064,101.496 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-565.064,-101.496 last=-565.064,-101.496 Δ 565.064,101.496) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600003606640, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=404.88,98.3004 gbl=404.88,98.3004 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-404.88,-98.3004 last=-404.88,-98.3004 Δ 404.88,98.3004) : no target window ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=2 ts=0 pos=0,0 scn=627.902,146.721 gbl=627.902,146.721 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-627.902,-146.721 last=-627.902,-146.721 Δ 627.902,146.721) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600003606640, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=2 ts=0 pos=0,0 scn=1501.48,294.674 gbl=1501.48,294.674 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1501.48,-294.674 last=-1501.48,-294.674 Δ 1501.48,294.674) : no target window ((null):0, (null))
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_rgbcSensorValueWidget_valueChanged() ((null):0, (null))
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_posture_valueChanged(int) ((null):0, (null))
INFO    | Info:

GLImplementation:
Surface Type: OpenGL
Surface Profile: CoreProfile
Surface Version: 4.1
Using Default SG Backend: no
Using Software Dynamic GL: no
Using Angle: no

Init Parameters:
  *  application-name Emulator
  *  browser-subprocess-path /Users/aripaka.chaitanya/Library/Android/sdk/emulator/lib64/qt/libexec/QtWebEngineProcess
  *  disable-features DnsOverHttpsUpgrade,ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture
  *  disable-gpu
  *  disable-speech-api
  *  enable-features TracingServiceInProcess
  *  enable-threaded-compositing
 ((null):0, (null))
INFO    | Warning: No functional TLS backend was found ((null):0, (null))
INFO    | Warning: No functional TLS backend was found ((null):0, (null))
 (2x)
INFO    | Warning: No TLS backend is available ((null):0, (null))
INFO    | Warning: No functional TLS backend was found ((null):0, (null))
INFO    | Warning: No functional TLS backend was found ((null):0, (null))
 (3x)
INFO    | Warning: No TLS backend is available ((null):0, (null))
INFO    | Warning: No functional TLS backend was found ((null):0, (null))
INFO    | Warning: No functional TLS backend was found ((null):0, (null))
 (2x)
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600003606640, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=2 ts=0 pos=0,0 scn=1617.83,1113.08 gbl=1617.83,1113.08 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1617.83,-1113.08 last=-1617.83,-1113.08 Δ 1617.83,1113.08) : no target window ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=3 ts=0 pos=0,0 scn=1434.23,929.479 gbl=1434.23,929.479 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1434.23,-929.479 last=-1434.23,-929.479 Δ 1434.23,929.479) : no target window ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=4 ts=0 pos=0,0 scn=1189.61,850.459 gbl=1189.61,850.459 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1189.61,-850.459 last=-1189.61,-850.459 Δ 1189.61,850.459) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600003606640, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=1595.34,554.55 gbl=1595.34,554.55 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1595.34,-554.55 last=-1595.34,-554.55 Δ 1595.34,554.55) : no target window ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=6 ts=0 pos=0,0 scn=1355.4,419.549 gbl=1355.4,419.549 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1355.4,-419.549 last=-1355.4,-419.549 Δ 1355.4,419.549) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600003606640, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=1265.43,665.896 gbl=1265.43,665.896 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1265.43,-665.896 last=-1265.43,-665.896 Δ 1265.43,665.896) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600003606640, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=1306.03,40.4306 gbl=1306.03,40.4306 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1306.03,-40.4306 last=-1306.03,-40.4306 Δ 1306.03,40.4306) : no target window ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=2 ts=0 pos=0,0 scn=1509.25,221.868 gbl=1509.25,221.868 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1509.25,-221.868 last=-1509.25,-221.868 Δ 1509.25,221.868) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600003606640, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=2 ts=0 pos=0,0 scn=1461.49,874.298 gbl=1461.49,874.298 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1461.49,-874.298 last=-1461.49,-874.298 Δ 1461.49,874.298) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600003606640, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=3 ts=0 pos=0,0 scn=1216.36,178.914 gbl=1216.36,178.914 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1216.36,-178.914 last=-1216.36,-178.914 Δ 1216.36,178.914) : no target window ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=4 ts=0 pos=0,0 scn=1427.68,396.177 gbl=1427.68,396.177 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1427.68,-396.177 last=-1427.68,-396.177 Δ 1427.68,396.177) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600003606640, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=1396.75,776.908 gbl=1396.75,776.908 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1396.75,-776.908 last=-1396.75,-776.908 Δ 1396.75,776.908) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600003606640, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=1225.61,545.659 gbl=1225.61,545.659 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1225.61,-545.659 last=-1225.61,-545.659 Δ 1225.61,545.659) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600003606640, name="EmulatorContainerClassWindow") ((null):0, (null))
[8149:33403:20230615,123447.443312:ERROR directory_reader_posix.cc:42] opendir /tmp/android-aripaka.chaitanya/emu-crash.db/attachments/822b3658-1695-46dc-aefc-81a9fcfd4cdf: No such file or directory (2)
[8149:33402:20230615,123447.445121:WARNING crash_report_exception_handler.cc:235] UniversalExceptionRaise: (os/kern) failure (5)
zsh: segmentation fault  emulator @Pixel5
aripaka.chaitanya@blr-aripaka ~ %
aripaka.chaitanya@blr-aripaka ~ %
aripaka.chaitanya@blr-aripaka ~ %
aripaka.chaitanya@blr-aripaka ~ %
aripaka.chaitanya@blr-aripaka ~ % emulator @Pixel5
INFO    | Android emulator version 32.1.12.0 (build_id 9751036) (CL:N/A)
INFO    | Found systemPath /Users/aripaka.chaitanya/Library/Android/sdk/system-images/android-30/google_apis/arm64-v8a/
INFO    | Storing crashdata in: /tmp/android-aripaka.chaitanya/emu-crash.db, detection is enabled
INFO    | Duplicate loglines will be removed, if you wish to see each indiviudal line launch with the -log-nofilter flag.
WARNING | Please update the emulator to one that supports the feature(s): Vulkan
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_new_posture_requested(int) ((null):0, (null))
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_dismiss_posture_selection_dialog() ((null):0, (null))
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_new_resizable_requested(PresetEmulatorSizeType) ((null):0, (null))
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_dismiss_resizable_dialog() ((null):0, (null))
INFO    | Crash reports will be automatically uploaded to: https://clients2.google.com/cr/report
INFO    | Report 822b3658-1695-46dc-aefc-81a9fcfd4cdf is available remotely as: 211c8f0b3d7320aa, deleting.
WARNING | cannot add library /Users/aripaka.chaitanya/Library/Android/sdk/emulator/qemu/darwin-aarch64/lib64/vulkan/libvulkan.dylib: failed
INFO    | added library /Users/aripaka.chaitanya/Library/Android/sdk/emulator/lib64/vulkan/libvulkan.dylib
WARNING | *** No gRPC protection active, consider launching with the -grpc-use-jwt flag.***
INFO    | Started GRPC server at 127.0.0.1:8554, security: Local, auth: none
INFO    | Advertising in: /Users/aripaka.chaitanya/Library/Caches/TemporaryItems/avd/running/pid_13237.ini
INFO    | Setting display: 0 configuration to: 1080x2340, dpi: 440x440
INFO    | Boot completed in 15263 ms
INFO    | Increasing screen off timeout, logcat buffer size to 2M.
INFO    | Revoking microphone permissions for Google App.
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600001674300, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=2 ts=0 pos=0,0 scn=713.24,133.655 gbl=713.24,133.655 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-713.24,-133.655 last=-713.24,-133.655 Δ 713.24,133.655) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600001674300, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=584.794,99.0227 gbl=584.794,99.0227 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-584.794,-99.0227 last=-584.794,-99.0227 Δ 584.794,99.0227) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600001674300, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=656.766,68.1897 gbl=656.766,68.1897 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-656.766,-68.1897 last=-656.766,-68.1897 Δ 656.766,68.1897) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600001674300, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=1413.42,665.68 gbl=1413.42,665.68 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1413.42,-665.68 last=-1413.42,-665.68 Δ 1413.42,665.68) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600001674300, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=1 ts=0 pos=0,0 scn=1374.96,563.928 gbl=1374.96,563.928 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1374.96,-563.928 last=-1374.96,-563.928 Δ 1374.96,563.928) : no target window ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=2 ts=0 pos=0,0 scn=1622.46,727.366 gbl=1622.46,727.366 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1622.46,-727.366 last=-1622.46,-727.366 Δ 1622.46,727.366) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600001674300, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=3 ts=0 pos=0,0 scn=1426.72,884.046 gbl=1426.72,884.046 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1426.72,-884.046 last=-1426.72,-884.046 Δ 1426.72,884.046) : no target window ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=4 ts=0 pos=0,0 scn=1296.4,770.464 gbl=1296.4,770.464 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1296.4,-770.464 last=-1296.4,-770.464 Δ 1296.4,770.464) : no target window ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=5 ts=0 pos=0,0 scn=1712.56,1030.21 gbl=1712.56,1030.21 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1712.56,-1030.21 last=-1712.56,-1030.21 Δ 1712.56,1030.21) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600001674300, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=32 ts=0 pos=0,0 scn=1239.1,472.713 gbl=1239.1,472.713 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1239.1,-472.713 last=-1239.1,-472.713 Δ 1239.1,472.713) : no target window ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=33 ts=0 pos=0,0 scn=1516.66,653.252 gbl=1516.66,653.252 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1516.66,-653.252 last=-1516.66,-653.252 Δ 1516.66,653.252) : no target window ((null):0, (null))
INFO    | Warning: delivering touch release to same window QWindow(0x0) not QWidgetWindow(0x600001674300, name="EmulatorContainerClassWindow") ((null):0, (null))
INFO    | Warning: skipping QEventPoint(id=7 ts=0 pos=0,0 scn=1508.66,109.899 gbl=1508.66,109.899 Released ellipse=(1x1 ∡ 0) vel=0,0 press=-1508.66,-109.899 last=-1508.66,-109.899 Δ 1508.66,109.899) : no target window ((null):0, (null))
[13239:58709:20230615,124041.934121:ERROR directory_reader_posix.cc:42] opendir /tmp/android-aripaka.chaitanya/emu-crash.db/attachments/11c002bf-10ec-45bc-ae1b-165414a8c671: No such file or directory (2)
[13239:58708:20230615,124041.934451:WARNING crash_report_exception_handler.cc:235] UniversalExceptionRaise: (os/kern) failure (5)
zsh: segmentation fault  emulator @Pixel5

**Comment by mykola-mokhnach** [comment]
This looks like an issue with the emulator itself. Please report it to Google
