### ISSUE TITLE
Unable to ignore sertificate

### ISSUE THREAD

**Issue by AvallaSD** [appium/appium#18775]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After opening page I see sertificate error. When I tap "details", then "visit this website" nothing happens. I can tap 100 times, but page still displayed. It happens only when I open it in appium session. I also use acceptInsecureCerts capability, but it doesn't wort either

### Expected Behavior

Sertificate error page shouldn't appear in the first place. Or at least disappear after clicking "visit"

### Minimal Reproducible Example

-

### Environment

- Operating system: MacOS Ventura 13
- Appium server version (output of `appium --version`): v2.0.0-beta.66
- Appium driver(s) and their version(s): xcuitest
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v18.16.0
- `npm` version (output of `npm --version`) :9.5.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iPhone 11, iOS 16.4
- Real device or emulator/simulator: Simulator

### Futher Information

![image](https://github.com/appium/appium/assets/60776606/7f8c0bdc-54a6-4232-a0b6-3d9f0b517d15)

**Comment by mykola-mokhnach** [comment]
Not sure why exactly you are trying to achieve, but in the log it is clearly visible that `acceptInsecureCerts` capability is not known. Where it is documented?

**Comment by AvallaSD** [comment]
> Not sure what exactly you are trying to achieve, but in the log it is clearly visible that `acceptInsecureCerts` capability is not known. Where it is documented?

It is base w3c driver capability, so I suppose it could be passed to webdriver after launching session with safari and switching to web context
Am I wrong? Is there a way to ignore certificate without manual manipulations imitation?
May be you faced same problem with visit button?

**Comment by KazuCocoa** [comment]
> for acceptInsecureCerts

You're right as W3C spec definition, but it is not achievable on macOS/iOS env so far. safaridriver by Apple also does not accept it. I haven't figured out if we can achieve acceptInsecureCerts yet, so our remote debugger (via web inspector) also should follow it. if you find the way, perhaps Appium can have the availability. It seems like Apple does not allow such things (at least for now). (for example, chrome accepts the capability)

For simulator usage, you can bypass the error by saving the certificate as system trusted in the keychain, it may require manual configuration, or can automate by `security` command in macOS. (sudo permission might be required)
https://support.apple.com/guide/keychain-access/change-the-trust-settings-of-a-certificate-kyca11871/mac


> for "visit this website" nothing happens

Potentially the behavior happens in xctest session to run Appium/WebDriverAgent process. (if so, perhaps no way to bypass the behavior as system restrictions) You could try out safaridriver https://github.com/appium/appium-safari-driver if to see it could help

**Comment by KazuCocoa** [comment]
`acceptInsecureCerts` via safaridriver worked with safariver 15.4+. I'll try to find if the option is available via the remote debugger (xcuitest driver).

https://github.com/appium/appium-safari-driver
https://github.com/appium/appium-safari-driver/pull/63

**Comment by KazuCocoa** [comment]
It seems not possible via web inspector.
I expected to have like https://chromedevtools.github.io/devtools-protocol/tot/Security/#method-setIgnoreCertificateErrors in WebKit but maybe not.
https://github.com/WebKit/WebKit/blob/4e68a149e83d28ec2963a292147c15e412b7ce0b/Source/JavaScriptCore/inspector/remote/glib/RemoteInspectorServer.cpp#L49-L50 has the flag, but probably no method to access to this value via https://github.com/appium/appium-remote-debugger/blob/master/lib/protocol/index.js right now.
https://github.com/WebKit/WebKit/tree/main/Source/JavaScriptCore/inspector/protocol
