### ISSUE TITLE
bug: rc.3 - unable to resolve dependency tree

### ISSUE THREAD

**Issue by Higgens75** [appium/appium#18785]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when installing the latest appium2.0.0-rc.3 client and afterwards installing the xcuitest drivers i get this dependency error.

`✔ Successfully uninstalled driver 'xcuitest'
✔ Successfully uninstalled plugin 'images'
✖ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev appium-xcuitest-driver --json' failed with code 1.

STDOUT:

STDERR:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: appium_installation@1.1.0
npm ERR! Found: appium@2.0.0-rc.3
npm ERR! node_modules/appium
npm ERR!   appium@"^2.0.0-rc.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer appium@"2.0.0-rc.2" from appium-xcuitest-driver@4.32.5
npm ERR! node_modules/appium-xcuitest-driver
npm ERR!   dev appium-xcuitest-driver@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/stephan.bast/.npm/eresolve-report.txt for a full report.
{
  "error": {
    "code": "ERESOLVE",
    "summary": "unable to resolve dependency tree",
    "detail": "\nWhile resolving: appium_installation@1.1.0\nFound: appium@2.0.0-rc.3\nnode_modules/appium\n  appium@\"^2.0.0-rc.3\" from the root project\n\nCould not resolve dependency:\npeer appium@\"2.0.0-rc.2\" from appium-xcuitest-driver@4.32.5\nnode_modules/appium-xcuitest-driver\n  dev appium-xcuitest-driver@\"*\" from the root project\n\nFix the upstream dependency conflict, or retry\nthis command with --force, or --legacy-peer-deps\nto accept an incorrect (and potentially broken) dependency resolution.\n\nSee /Users/stt/.npm/eresolve-report.txt for a full report."
  }
}`

### Expected Behavior

installing drivers works

### Minimal Reproducible Example

installing appium and drivers with npm

"scripts": {
    "postinstall": "npx appium driver uninstall xcuitest || true && npx appium plugin uninstall images || true && npx appium driver install xcuitest || true && npx appium plugin install images || true"
  },

### Environment

- Operating system:
- Appium server version (output of `appium --version`): rc.3
- Appium driver(s) and their version(s): 
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): 16.19.1
- `npm` version (output of `npm --version`): 8.19.3
- Last component(s) version which did _not_ exhibit the problem: rc.2
- Platform and version under test: MacOS 13.2.1
- Real device or emulator/simulator: emulator

**Comment by P4radise** [comment]
I encountered the same problem. When will it be solved?

**Comment by jlipps** [comment]
I cannot reproduce. Please follow these steps and say if there is still an issue:

```
npm uninstall -g appium && npm install -g appium@next
rm -rf ~/.appium
appium driver install xcuitest
```

**Comment by Higgens75** [comment]
> I cannot reproduce. Please follow these steps and say if there is still an issue:
> 
> ```
> npm uninstall -g appium && npm install -g appium@next
> rm -rf ~/.appium
> appium driver install xcuitest
> ```

i do not install global. Instead i use an system variable with an specific APPIUM_HOME location.

But i also get this error message

 - Driver "xcuitest" (package `appium-xcuitest-driver`) may be incompatible with the current version of Appium (v2.0.0-rc.3) due to its peer dependency on older Appium v2.0.0-rc.2. Please ask the developer of `appium-xcuitest-driver` to update the peer dependency on Appium to v2.0.0-rc.3
 
 Doesnt that mean that the latest xcuitest-driver has a dependency to rc.2 ?
 Than i would post this on the driver board.

**Comment by Higgens75** [comment]
had a look into the xcuitestdriver repo and there is a peer dependency to rc.3

![image](https://github.com/appium/appium/assets/39295103/00431c02-1a3e-461e-a255-ab40971afb33)

**Comment by Higgens75** [comment]
Hmm good question. The complete installation process worked over all beta versions up to rc2.
Everything is cleared before installation also on ci systems.  There are no leftovers as appium and appium_home folders are within the project folder which is deleted after test has run. This worked on 4 identical CI machines and my personal Mac.
is it helpful when I post the package.json ?


> that peer dependency on rc 2 is ok. and the 'error' message is not an error but a warning. there shouldn't be any issues. is there something else going wrong?

**Comment by Higgens75** [comment]
Hmm good question. The complete installation process worked over all beta versions up to rc2.
Everything is cleared before installation also on ci systems.  There are no leftovers as appium and appium_home folders are within the project folder which is deleted after test has run. This worked on 4 identical CI machines and my personal Mac.
is it helpful when I post the package.json ?

**Comment by jlipps** [comment]
If the installation process worked, what is the problem you are reporting?

**Comment by Higgens75** [comment]
That with rc3 it is not running anymore

**Comment by jlipps** [comment]
What is not running? Can you provide the full set of commands that you ran, and the error output?

**Comment by Higgens75** [comment]
Thanks for your help I will post this information tomoorow

**Comment by Higgens75** [comment]
seems that the new XCUTestdriver 4.32.6 solved the problem.
Don't know what changed there but the installation on my machine works again.
I test this on the CIs and than close this issue.
Thanks again for your time and efforts :)

**Comment by Higgens75** [comment]
fixed
