### ISSUE TITLE
[Feat]:Appium Multi screen support

### ISSUE THREAD

**Issue by jinwenchaobaby** [appium/appium#18787]
I am testing an Android device with two screens, the right screen (main screen) and the left screen (secondary screen). I can test programs running on the right screen normally, but I cannot test programs running on the left screen because the left screen is a secondary screen. org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters.

![image](https://github.com/appium/appium/assets/65697132/451c84aa-7cd0-47f4-9b35-2c03ff1627b0)

**Comment by mykola-mokhnach** [comment]
Have you tried setting [enableMultiWindows](https://github.com/appium/appium-uiautomator2-driver#settings-api) setting to true?

**Comment by jinwenchaobaby** [comment]
> 您是否尝试过启用[enableMultiWindows](https://github.com/appium/appium-uiautomator2-driver#settings-api)设置？

I have tried, but the property enableMultiWindows also cannot support sub screen program testing

**Comment by mykola-mokhnach** [comment]
I don't think there is anything more we can do about it. UIA2 driver is completely based on Google's UiAutomator framework, and I don't observe any multiscreen support there.

**Comment by jinwenchaobaby** [comment]
> 我认为我们对此无能为力。UIA2 驱动程序完全基于 Google 的 UiAutomator 框架，我在那里没有观察到任何多屏支持。

Thank you for your reply. May I ask which other tools or tutorials I can refer to based on your experience to complete my testing?

**Comment by mykola-mokhnach** [comment]
I would also try https://github.com/appium/appium-espresso-driver

**Comment by jinwenchaobaby** [comment]
> 我也会尝试https://github.com/appium/appium-espresso-driver

Thank you, I will make these attempts

**Comment by jayeliu** [comment]
about multi-screen:
https://developer.android.com/jetpack/androidx/releases/test-uiautomator?hl=zh-cn#2.3.0
