### ISSUE TITLE
Android: Appium 2 with Java Client 8.3.0 is incompatible with Dynatrace version of 8.265.1.1002 : Android Application getting crashed when entering value into Textfield/Password field

### ISSUE THREAD

**Issue by kaika10** [appium/appium#18782]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Issue Description:** 

An issue is being faced with respect to one of the latest versions (8.265.1.1002) of Dynatrace which seems to be incompatible with Appium/Android. 
  

**For scenario:**  

When executing an automation script , a value is entered into simple Text field/ Password Masked Text field using strategy of Ui-Automator, and it is observed that value cannot be entered and mobile application gets crashed which is happening due to the reason - On entering the data in Text field a trigger to Dynatrace happens which blocks  entering the values in the textfields 
  

**Root-Cause:** 

The root cause of the issue is the specific version of Dynatrace: 8.265.1.1002 causing this problem. 

On trying the same mobile application but with earlier version of Dynatrace (8.263.1.1002, 8.261.2.1013), as such no issues can be seen (Value can be entered into the Text Field / Password field successfully) 

 

**System Specifications** 

- Java JDK -17 
- Maven 3.9.1 
- Apium GUI: 1.22.3 
- Appium terminal mode: 1.22.3 / 2.0.0-rc.2
- Android SDK: Electric Eel 2.22.1.1 Patch 2 
- Java-Client library (Maven Dependency):8.3.0 
- Operating System : Mac M1 chip :Ventura  13.3.1 (22E261)
- Appium driver(s) and their version(s): uiautmator2
- Appium plugin(s) and their version(s): no plugins 
- Node.js version (output of `node --version`): v20.3.0
- `npm` version (output of `npm --version`):  9.6.7
- Last component(s) version which did _not_ exhibit the problem: Dynatrace 8.263.1.1002 - works fine on both Appium 1 and 2 

Note: - Also tried with Appium-2 (beta version: 2.0.0-rc.2), still getting the same issue 

**Error:**
[HTTP] {"using":"-android uiautomator","value":"new UiSelector().resourceId(\"userName\")"} 

[debug] [AndroidUiautomator2Driver@8880 (e57fa82a)] Calling AppiumDriver.findElement() with args: ["-android uiautomator","new UiSelector().resourceId(\"userName\")","e57fa82a-1ea0-4037-9796-e07e18bd8ac4"] 

[debug] [AndroidUiautomator2Driver@8880 (e57fa82a)] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator 

[debug] [AndroidUiautomator2Driver@8880 (e57fa82a)] Waiting up to 0 ms for condition 

[debug] [AndroidUiautomator2Driver@8880 (e57fa82a)] Matched '/element' to command name 'findElement' 

[debug] [AndroidUiautomator2Driver@8880 (e57fa82a)] Proxying [POST /element] to [POST http://127.0.0.1:8200/session/08893484-238d-4b7a-bc1a-cc35ca976c67/element] with body: {"strategy":"-android uiautomator","selector":"new UiSelector().resourceId(\"userName\")","context":"","multiple":false} 

[AndroidUiautomator2Driver@8880 (e57fa82a)] Got response with status 404: {"sessionId":"08893484-238d-4b7a-bc1a-cc35ca976c67","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:63)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:277)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:271)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann... 

[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError 

[debug] [AndroidUiautomator2Driver@8880 (e57fa82a)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters. 

### Expected Behavior

With latest version of Appium 2 (Beta version , with java-client : 8.3.0) and Dynatrace : 8.265.1.1002 , when entering value into the textfield which triggers Dynatarce , android application should not get crash and value can be entered successfully 

### Minimal Reproducible Example

na

### Environment

**System Specifications** 

- Operating system: Mac M1 chip 13.3.1 (22E261)
- Appium server version (output of `appium --version`):2.0.0-rc.2
- Appium driver(s) and their version(s): uiautmator2
- Appium plugin(s) and their version(s): no plugins 
- Node.js version (output of `node --version`): v20.3.0
- `npm` version (output of `npm --version`):  9.6.7
- Last component(s) version which did _not_ exhibit the problem: Dynatrace 8.263.1.1002 - works fine on both Appium 1 and 2 
- Platform and version under test: Platform : Android Studio Electric Eel | 2022.1.1 Patch 2
- Real device or emulator/simulator: Real Device (Pixel 3 , 
- Java JDK -17 
- Maven 3.9.1 
- Apium GUI: 1.22.3 
- Appium terminal mode: 1.22.3 
- Android SDK: Electric Eel 2.22.1.1 Patch 2 
- Java-Client library (Maven Dependency):8.3.0 
- Operating System : Mac M1 chip :Ventura  13.3.1 (22E261)

### Futher Information

Error:
**Error:**
[HTTP] {"using":"-android uiautomator","value":"new UiSelector().resourceId(\"userName\")"} 

[debug] [AndroidUiautomator2Driver@8880 (e57fa82a)] Calling AppiumDriver.findElement() with args: ["-android uiautomator","new UiSelector().resourceId(\"userName\")","e57fa82a-1ea0-4037-9796-e07e18bd8ac4"] 

[debug] [AndroidUiautomator2Driver@8880 (e57fa82a)] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator 

[debug] [AndroidUiautomator2Driver@8880 (e57fa82a)] Waiting up to 0 ms for condition 

[debug] [AndroidUiautomator2Driver@8880 (e57fa82a)] Matched '/element' to command name 'findElement' 

[debug] [AndroidUiautomator2Driver@8880 (e57fa82a)] Proxying [POST /element] to [POST http://127.0.0.1:8200/session/08893484-238d-4b7a-bc1a-cc35ca976c67/element] with body: {"strategy":"-android uiautomator","selector":"new UiSelector().resourceId(\"userName\")","context":"","multiple":false} 

[AndroidUiautomator2Driver@8880 (e57fa82a)] Got response with status 404: {"sessionId":"08893484-238d-4b7a-bc1a-cc35ca976c67","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:63)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:277)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:271)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann... 

[debug] [W3C] Matched W3C error code 'no such element' to NoSuchElementError 

[debug] [AndroidUiautomator2Driver@8880 (e57fa82a)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.

**Comment by mykola-mokhnach** [comment]
I am not quite sure what could be done there from our side. The lookup is executed by Google's UiAutomator framework. UIA2 is just a client to it.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
