### ISSUE TITLE
bug: <title>create a driver

### ISSUE THREAD

**Issue by 1337328542** [appium/appium#18791]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Because the official driver function does not support the application I need to test, I tried to develop the driver by myself.

 I installed the latest node.js, npm, appium and made it by reference to fak-driver, but I still could not use the driver normally and there would be various errors.

 It had already taken me about 3 days of Googling and github, so I came to ask for help

### Expected Behavior

I just want it to be easy to create a driver

### Minimal Reproducible Example

>> easy-pc\my-driver\package.json

"main": "./build/driver.js",
"appium": {
        "driverName": "mydriver",
        "automationName": "mydriver",
        "platformNames": [
            "mydriver"
        ],
        "mainClass": "MyDriver"
    },
"devDependencies": {
        "appium": "^2.0.0-rc.3"
    },

>> easy-pc\my-driver\src\driver.js

// or: import {BaseDriver} from 'appium/driver';
const { BaseDriver } = require('appium/driver');

class MyDriver extends BaseDriver {
}

export { MyDriver }

### Environment

- Operating system: win 10
- Appium server version (output of `appium --version`):2.0.0-rc.2
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):v18.12.1
- `npm` version (output of `npm --version`):8.19.2
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Futher Information

![image](https://github.com/appium/appium/assets/132647029/265008e5-bc83-48b6-ab81-206f315f25d9)

**Comment by mykola-mokhnach** [comment]
> "main": "./build/driver.js",

Do you use a transpiler in your package, so there is a `build`  folder?

> "devDependencies": {
> "appium": "^2.0.0-rc.3"
> },

The log above actually complains about the missing peer dependency


Which command do you use to add your driver to appium dist?

**Comment by Higgens75** [comment]
maye the same report as
https://github.com/appium/appium/issues/18785

**Comment by jlipps** [comment]
This seems unrelated to #18785. Did you follow all the driver developer docs?

**Comment by Higgens75** [comment]
had a look into the xcuitestdriver repo and there is a dev dependecy to rc.2

![image](https://github.com/appium/appium/assets/39295103/00431c02-1a3e-461e-a255-ab40971afb33)

**Comment by mykola-mokhnach** [comment]
Closed because of no response
