### ISSUE TITLE
bug: Appium downloaded apk file as zip from remote URL led to error that Appium couldn't find any apk file in bundles.

### ISSUE THREAD

**Issue by kle97** [appium/appium#18793]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I specified a remote URL to our apk file to "app" capability (i.e. "app": "url-to-app.apk"). Appium should download the apk file and install the app properly. This worked as intended before, but recently, I've updated Appium version, the download and install process doesn't work any more. There was an error thrown:
```
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: Could not start a new session. Could
 not start a new session. Error while creating session with the service http://localhost:51183. Could not start a new session. Response code 500. Message: An unknown server-side error occur
red while processing the command. Original error: App unzipped OK, but we could not find any '.apk,.apks' bundles in it. Make sure your archive contains at least one package having '.apk,.a
pks' extensio
```
I traced the appium server log and this is the error I found:
![Screenshot 2023-06-21 113058](https://github.com/appium/appium/assets/60417540/dd979353-c11e-4fc5-9a3b-7993267b0610)

It seems like Appium downloaded the apk file as zip file instead of apk file like before, and then it tried to unzip this file and looked for an apk file in it. 

Current appium version: 2.0.0-beta.69
Current base-driver version: 9.3.10

Appium version that worked
Old appium version: 2.0.0-beta.57
Old base-driver version: 9.3.3

### Expected Behavior

Appium should download apk file and install app correctly.

### Minimal Reproducible Example

The current behavior section should describe the steps needed.

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.0.0-beta.69
- Appium driver(s) and their version(s): uiautomator2@2.27.0
- Appium plugin(s) and their version(s): N/A
- Node.js version (output of `node --version`): v20.2.0
- `npm` version (output of `npm --version`): 9.6.6
- Last component(s) version which did _not_ exhibit the problem: 2.0.0-beta.57
- Platform and version under test: MacOS
- Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
Have you checked the file manually? Does it actually contain any files having .apk or .apks extension?
Also, what is the point of zipping an .apk? It is already a zip file.

**Comment by kle97** [comment]
@mykola-mokhnach I checked the archive file that Appium downloaded in the var folder, and it's actually the apk file, but Appium downloaded it as appium-app.zip file. I didn't zip the apk file or anything. The remote URL I was using contains only apk file to download, but Appium somehow recognized it as zip file.

**Comment by kle97** [comment]
This is from the appium log of the old Appium version that worked. As you can see, Appium downloaded the apk file as is from the same remote URL to the temporary folder.
![Screenshot 2023-06-21 132443](https://github.com/appium/appium/assets/60417540/44ebb057-c873-4dd7-b8fc-3c75055b28c5)

**Comment by KazuCocoa** [comment]
Then, your url indicated the file was zip as the content type:
![Screenshot 2023-06-21 at 1 51 05 PM](https://github.com/appium/appium/assets/5511591/91aee0cd-27d8-4011-aa83-f91e41734b17)
but the file was not `zip`?
At some points, Appium handles file extension properly by referencing the header information as well. I guess ideally the response header you use should be something like `application/octet-stream` for file download then.

**Comment by kle97** [comment]
@KazuCocoa Thanks for your suggestion! Changing content-type made app installing work again.
Closed.
