### ISSUE TITLE
bug: appium server is showing 500 error when calling to get_screenshot_as_base64 while running Windows app test

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#18794]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While running windows app appium test, once I am calling to `driver.get_screenshot_as_base64()` I am getting the following error in appium server log:
```
[debug] [WindowsDriver@b02c (94a11461)] Calling AppiumDriver.getScreenshot() with args: ["94a11461-2ced-4895-b689-7cd4e44c6446"]
[debug] [WindowsDriver@b02c (94a11461)] Matched '/screenshot' to command name 'getScreenshot'
[debug] [WindowsDriver@b02c (94a11461)] Proxying [GET /screenshot] to [GET http://127.0.0.1:4724/wd/hub/session/B70CACF5-8A7E-4E2C-91BD-55B62AD131F1/screenshot] with no body
[debug] [WindowsDriver@b02c (94a11461)] ഀ਀ഀ਀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀ഀ਀䜀䔀吀 ⼀眀搀⼀栀甀戀⼀猀攀猀猀椀漀渀⼀䈀㜀　䌀䄀䌀䘀㔀ⴀ㠀䄀㜀䔀ⴀ㐀䔀㈀䌀ⴀ㤀㄀䈀䐀ⴀ㔀㔀䈀㘀㈀䄀䐀㄀㌀㄀䘀㄀⼀猀挀爀攀攀渀猀栀漀琀 䠀吀吀倀⼀㄀⸀㄀ഀഀ਀䄀挀挀攀瀀琀㨀 愀瀀瀀氀椀挀愀琀椀漀渀⼀樀猀漀渀Ⰰ ⨀⼀⨀ഀഀ਀䄀挀挀攀瀀琀ⴀ䔀渀挀漀搀椀渀最㨀 最稀椀瀀Ⰰ 挀漀洀瀀爀攀猀猀Ⰰ 搀攀昀氀愀琀攀Ⰰ 戀爀ഀഀ਀䌀漀渀渀攀挀琀椀漀渀㨀 欀攀攀瀀ⴀ愀氀椀瘀攀ഀഀ਀䌀漀渀琀攀渀琀ⴀ吀礀瀀攀㨀 愀瀀瀀氀椀挀愀琀椀漀渀⼀樀猀漀渀㬀 挀栀愀爀猀攀琀㴀甀琀昀ⴀ㠀ഀഀ਀䠀漀猀琀㨀 ㄀㈀㜀⸀　⸀　⸀㄀㨀㐀㜀㈀㐀ഀഀ਀唀猀攀爀ⴀ䄀最攀 渀琀㨀 愀瀀瀀椀甀洀ഀഀ਀ഀഀ਀ഀ਀
[debug] [WindowsDriver@b02c (94a11461)] 䠀吀吀倀⼀㄀⸀㄀ 㔀　　 䤀渀琀攀爀渀愀氀 䔀爀爀漀爀ഀഀ਀䌀漀渀琀攀渀琀ⴀ䰀攀渀最琀栀㨀 ㄀㌀㌀ഀഀ਀䌀漀渀琀攀渀琀ⴀ吀礀瀀攀㨀 愀瀀瀀氀椀挀愀琀椀漀渀⼀樀猀漀渀ഀഀ਀ഀഀ਀笀∀猀琀愀琀甀猀∀㨀㄀㌀Ⰰ∀瘀愀氀甀攀∀㨀笀∀攀爀爀漀爀∀㨀∀甀渀欀渀漀眀渀 攀爀爀漀爀∀Ⰰ∀洀攀猀猀愀最攀∀㨀∀䄀渀 甀渀欀渀漀眀渀 攀爀爀漀爀 漀挀挀甀爀爀攀搀 椀渀 琀栀攀 爀攀洀漀琀攀 攀渀搀 眀栀椀氀攀 瀀爀漀挀攀猀猀椀渀最 琀栀攀 挀漀洀洀愀渀搀⸀∀紀紀ഀ਀
[WindowsDriver@b02c (94a11461)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [WindowsDriver@b02c (94a11461)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: An unknown error occurred in the remote end while processing the command.
[debug] [WindowsDriver@b02c (94a11461)]     at errorFromW3CJsonCode (C:\Users\qahw\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1040:25)
[debug] [WindowsDriver@b02c (94a11461)]     at ProxyRequestError.getActualError (C:\Users\qahw\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:909:14)
[debug] [WindowsDriver@b02c (94a11461)]     at WADProxy.command (C:\Users\qahw\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:352:19)
[debug] [WindowsDriver@b02c (94a11461)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [WindowsDriver@b02c (94a11461)]     at WinAppDriver.sendCommand (C:\Users\qahw\.appium\node_modules\appium-windows-driver\lib\winappdriver.js:223:12)
[debug] [WindowsDriver@b02c (94a11461)]     at WindowsDriver.getScreenshot (C:\Users\qahw\.appium\node_modules\appium-windows-driver\lib\commands\general.js:48:22)
[HTTP] <-- GET /session/94a11461-2ced-4895-b689-7cd4e44c6446/screenshot 500 27 ms - 1221
[HTTP]
```

### Expected Behavior

Screen short from windows application should be captured successfully 

### Minimal Reproducible Example

`driver.get_screenshot_as_base64()`

### Environment

- Operating system: Windows 10 OS, 64 bit
- Appium server version (output of `appium --version`): appium 2.0.0 RC3
- Appium driver(s) and their version(s): uiautomator2@2.10.2 (automationName 'UiAutomator2')
- Appium plugin(s) and their version(s): uiautomator2@2.10.2 (automationName 'UiAutomator2')
- Node.js version (output of `node --version`): v18.12.0
- `npm` version (output of `npm --version`): 8.19.2
- Last component(s) version which did _not_ exhibit the problem: never worked
- Platform and version under test: Windows
- Real device or emulator/simulator: real windows app

### Link to Appium Logs

https://github.com/bwomsm1/AppiumLogs/blob/master/win_app_appium.log

**Comment by bwomsm1** [comment]
@mykola-mokhnach can you please advice with that issue? Thanks!

**Comment by bwomsm1** [comment]
Windows OS info:
```
Device name	KDT-AUTO28
Full device name	KDT-AUTO28.Corp.aeroscout.com
Processor	Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz   3.10 GHz
Installed RAM	16.0 GB (15.8 GB usable)
Device ID	-------------------------
Product ID	------------------------------
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display


Edition	Windows 10 Pro
Version	22H2
Installed on	‎11/‎01/‎2022
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0
```

**Comment by mykola-mokhnach** [comment]
> [debug] [WindowsDriver@b02c (94a11461)] ഀ਀ഀ਀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀ഀ਀䜀䔀吀 ⼀眀搀⼀栀甀戀⼀猀攀猀猀椀漀渀⼀䈀㜀　䌀䄀䌀䘀㔀ⴀ㠀䄀㜀䔀ⴀ㐀䔀㈀䌀ⴀ㤀㄀䈀䐀ⴀ㔀㔀䈀㘀㈀䄀䐀㄀㌀㄀䘀㄀⼀猀挀爀攀攀渀猀栀漀琀 䠀吀吀倀⼀㄀⸀㄀ഀഀ਀䄀挀挀攀瀀琀㨀 愀瀀瀀氀椀挀愀琀椀漀渀⼀樀猀漀渀Ⰰ ⨀⼀⨀ഀഀ਀䄀挀挀攀瀀琀ⴀ䔀渀挀漀搀椀渀最㨀 最稀椀瀀Ⰰ 挀漀洀瀀爀攀猀猀Ⰰ 搀攀昀氀愀琀攀Ⰰ 戀爀ഀഀ਀䌀漀渀渀攀挀琀椀漀渀㨀 欀攀攀瀀ⴀ愀氀椀瘀攀ഀഀ਀䌀漀渀琀攀渀琀ⴀ吀礀瀀攀㨀 愀瀀瀀氀椀挀愀琀椀漀渀⼀樀猀漀渀㬀 挀栀愀爀猀攀琀㴀甀琀昀ⴀ㠀ഀഀ਀䠀漀猀琀㨀 ㄀㈀㜀⸀　⸀　⸀㄀㨀㐀㜀㈀㐀ഀഀ਀唀猀攀爀ⴀ䄀最攀 渀琀㨀 愀瀀瀀椀甀洀ഀഀ਀ഀഀ਀ഀ਀
> [debug] [WindowsDriver@b02c (94a11461)] 䠀吀吀倀⼀㄀⸀㄀ 㔀　　 䤀渀琀攀爀渀愀氀 䔀爀爀漀爀ഀഀ਀䌀漀渀琀攀渀琀ⴀ䰀攀渀最琀栀㨀 ㄀㌀㌀ഀഀ਀䌀漀渀琀攀渀琀ⴀ吀礀瀀攀㨀 愀瀀瀀氀椀挀愀琀椀漀渀⼀樀猀漀渀ഀഀ਀ഀഀ਀笀∀猀琀愀琀甀猀∀㨀㄀㌀Ⰰ∀瘀愀氀甀攀∀㨀笀∀攀爀爀漀爀∀㨀∀甀渀欀渀漀眀渀 攀爀爀漀爀∀Ⰰ∀洀攀猀猀愀最攀∀㨀∀䄀渀 甀渀欀渀漀眀渀 攀爀爀漀爀 漀挀挀甀爀爀攀搀 椀渀 琀栀攀 爀攀洀漀琀攀 攀渀搀 眀栀椀氀攀 瀀爀漀挀攀猀猀椀渀最 琀栀攀 挀漀洀洀愀渀搀⸀∀紀紀ഀ਀


Could you help with the translation? It looks like a WAD issue to me

**Comment by bwomsm1** [comment]
> > [debug] [WindowsDriver@b02c (94a11461)] ഀ਀ഀ਀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀㴀ഀ਀䜀䔀吀 ⼀眀搀⼀栀甀戀⼀猀攀猀猀椀漀渀⼀䈀㜀　䌀䄀䌀䘀㔀ⴀ㠀䄀㜀䔀ⴀ㐀䔀㈀䌀ⴀ㤀㄀䈀䐀ⴀ㔀㔀䈀㘀㈀䄀䐀㄀㌀㄀䘀㄀⼀猀挀爀攀攀渀猀栀漀琀 䠀吀吀倀⼀㄀⸀㄀ഀഀ਀䄀挀挀攀瀀琀㨀 愀瀀瀀氀椀挀愀琀椀漀渀⼀樀猀漀渀Ⰰ ⨀⼀⨀ഀഀ਀䄀挀挀攀瀀琀ⴀ䔀渀挀漀搀椀渀最㨀 最稀椀瀀Ⰰ 挀漀洀瀀爀攀猀猀Ⰰ 搀攀昀氀愀琀攀Ⰰ 戀爀ഀഀ਀䌀漀渀渀攀挀琀椀漀渀㨀 欀攀攀瀀ⴀ愀氀椀瘀攀ഀഀ਀䌀漀渀琀攀渀琀ⴀ吀礀瀀攀㨀 愀瀀瀀氀椀挀愀琀椀漀渀⼀樀猀漀渀㬀 挀栀愀爀猀攀琀㴀甀琀昀ⴀ㠀ഀഀ਀䠀漀猀琀㨀 ㄀㈀㜀⸀　⸀　⸀㄀㨀㐀㜀㈀㐀ഀഀ਀唀猀攀爀ⴀ䄀最攀 渀琀㨀 愀瀀瀀椀甀洀ഀഀ਀ഀഀ਀ഀ਀
> > [debug] [WindowsDriver@b02c (94a11461)] 䠀吀吀倀⼀㄀⸀㄀ 㔀　　 䤀渀琀攀爀渀愀氀 䔀爀爀漀爀ഀഀ਀䌀漀渀琀攀渀琀ⴀ䰀攀渀最琀栀㨀 ㄀㌀㌀ഀഀ਀䌀漀渀琀攀渀琀ⴀ吀礀瀀攀㨀 愀瀀瀀氀椀挀愀琀椀漀渀⼀樀猀漀渀ഀഀ਀ഀഀ਀笀∀猀琀愀琀甀猀∀㨀㄀㌀Ⰰ∀瘀愀氀甀攀∀㨀笀∀攀爀爀漀爀∀㨀∀甀渀欀渀漀眀渀 攀爀爀漀爀∀Ⰰ∀洀攀猀猀愀最攀∀㨀∀䄀渀 甀渀欀渀漀眀渀 攀爀爀漀爀 漀挀挀甀爀爀攀搀 椀渀 琀栀攀 爀攀洀漀琀攀 攀渀搀 眀栀椀氀攀 瀀爀漀挀攀猀猀椀渀最 琀栀攀 挀漀洀洀愀渀搀⸀∀紀紀ഀ਀
> 
> Could you help with the translation? It looks like a WAD issue to me

No idea my self,
My current Windows Application Driver is `1.2.1.0`

**Comment by mykola-mokhnach** [comment]
I don't think we can help there. WAD server is owned by [Microsoft](https://github.com/microsoft/WinAppDriver) and is not open-sourced. Try to report your issue there

**Comment by bwomsm1** [comment]
> I don't think we can help there. WAD server is owned by [Microsoft](https://github.com/microsoft/WinAppDriver) and is not open-sourced. Try to report your issue there

thanks, low chances that I would get something from Microsoft, that WAD version of `1.2.1.0`is already that version for long time

**Comment by mykola-mokhnach** [comment]
Yes, unfortunately this particular project is maintained very poorly from their side. 
We could probably help with the maintenance if it would be open-sources. Otherwise 🤷

**Comment by bwomsm1** [comment]
WinAppDriver issue ticket:
https://github.com/microsoft/WinAppDriver/issues/1910
