### ISSUE TITLE
bug: ipad iOS 17 unable to get the screen in appium inspector

### ISSUE THREAD

**Issue by manojkanur** [appium/appium#18790]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to open a ipad screen in appium inspector after creating the 'Start Session'
Infra:
iPad OS: 17.0;
xcode version: 15; 
appium version v1.22.3-4

WDA build successful and WDA installed in the ipad too.

Below issue we are facing once we start the session:
**[debug] [35m[XCUITest][39m Not clearing log files. Use `clearSystemFiles` capability to turn on.
[info] [35m[iProxy@00008112:8100][39m The connection has been closed
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1687259270850 (04:07:50 GMT-0700 (Pacific Daylight Time))
[debug] [35m[W3C][39m Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [35m[W3C][39m xcodebuild error message:**

Attaching the appium logs
[appium-server-logs.txt](https://github.com/appium/appium/files/11804131/appium-server-logs.txt)

### Expected Behavior

Ipad screen should be comes in appium inspector.

### Minimal Reproducible Example

Desired capabilities:

[debug] [35m[BaseDriver][39m W3C capabilities and MJSONWP desired capabilities were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {
[debug] [35m[BaseDriver][39m   "alwaysMatch": {
[debug] [35m[BaseDriver][39m     "platformName": "iOS",
[debug] [35m[BaseDriver][39m     "appium:deviceName": "interop's iPad (2)",
[debug] [35m[BaseDriver][39m     "appium:platformVersion": "17.0",
[debug] [35m[BaseDriver][39m     "appium:udid": "xxxxxxxxx-xxxxxxxxxxxxxxxxxx",
[debug] [35m[BaseDriver][39m     "appium:bundleId": "com.apple.Preferences",
[debug] [35m[BaseDriver][39m     "appium:automationName": "XCUITest",
[debug] [35m[BaseDriver][39m     "appium:noReset": "true",
[debug] [35m[BaseDriver][39m     "appium:autoDismissAlerts": "true",
[debug] [35m[BaseDriver][39m     "appium:includeSafariInWebviews": true,
[debug] [35m[BaseDriver][39m     "appium:newCommandTimeout": 3600,
[debug] [35m[BaseDriver][39m     "appium:connectHardwareKeyboard": true
[debug] [35m[BaseDriver][39m   },

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Link to Appium Logs

logs attached

**Comment by jlipps** [comment]
> Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

Seems like the xcode build failed. To get more information follow the recommendation already in the logs:

> Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability

**Comment by mykola-mokhnach** [comment]
> appium version v1.22.3-4

This behaviour is expected. Consider using the most recent xcuitest driver version supplied with Appium 2.
Closed as duplicate

**Comment by manojkanur** [comment]
Thanks for responding @mykola-mokhnach and @jlipps . My issue fixed :)
