### ISSUE TITLE
WebDriverAgent's build is getting succeeded , it's running on simulator but it's getting failed on real device

### ISSUE THREAD

**Issue by SahilBharti89** [appium/appium#18795]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using macOS version 13.4 and Xcode version 14.3.1, when I am selecting test under product for the real device it's getting failed and doesn't show any error, only shows an error dialogue. But it's working fine on the simulator.

### Expected Behavior

It should work on a simulator and a real device.

### Minimal Reproducible Example

I am using macOS version 13.4 and Xcode version 14.3.1, when I am selecting test under product for the real device it's getting failed and doesn't show any error, only shows an error dialogue. But it's working fine on the simulator.

### Environment

- Operating system: MacOS
- Appium server version (output of `appium --version`): 1.22.3
- Appium driver(s) and their version(s): 5.5.1
- Appium plugin(s) and their version(s): 
- Node.js version (output of `node --version`): 17
- `npm` version (output of `npm --version`): 8.3
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: iPhone 14/14

### Futher Information

I am using macOS version 13.4 and Xcode version 14.3.1, when I am selecting test under product for the real device it's getting failed and doesn't show any error, only shows an error dialogue. But it's working fine on the simulator.

**Comment by KazuCocoa** [comment]
Could you try out latest XCUITest with Appium 2.0?
Then, please share the full appium log with `appium:showXcodeLog` and check https://appium.github.io/appium-xcuitest-driver/4.32.5/real-device-config/

**Comment by mykola-mokhnach** [comment]
The driver supplied with Appium 1 won't support Xcode 14. We do not support or maintain it anymore.

**Comment by SahilBharti89** [comment]
I have upgraded my appium version to 2.0.0-rc.3. Still I am facing the same issue.

**Comment by jlipps** [comment]
Please paste your full Appium log.

**Comment by SahilBharti89** [comment]
Hello @jlipps, Thanks for your reply. following are the complete logs : 

2023-07-03 16:41:54.331352+0530 IntegrationTests_3-Runner[1857:416239] Running tests...
2023-07-03 16:41:54.376661+0530 IntegrationTests_3-Runner[1857:416239] [loading] Error loading /var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/PlugIns/IntegrationTests_3.xctest/IntegrationTests_3 (154):  dlopen(/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/PlugIns/IntegrationTests_3.xctest/IntegrationTests_3, 0x0109): Library not loaded: @rpath/WebDriverAgentLib.framework/WebDriverAgentLib
  Referenced from: <FHGGHJJQWW> /private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/PlugIns/IntegrationTests_3.xctest/IntegrationTests_3
  Reason: tried: '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/PlugIns/IntegrationTests_3.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/PlugIns/IntegrationTests_3.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/PlugIns/IntegrationTests_3.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/PlugIns/IntegrationTests_3.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/System/Developer/Library/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/preboot/Cryptexes/OS/System/Developer/Library/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/System/Developer/usr/lib/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/preboot/Cryptexes/OS/System/Developer/usr/lib/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/Developer/Library/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/preboot/Cryptexes/OS/Developer/Library/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/Developer/usr/lib/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/preboot/Cryptexes/OS/Developer/usr/lib/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/System/Library/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file, not in dyld cache)
2023-07-03 16:41:54.378024+0530 IntegrationTests_3-Runner[1857:416239] The bundle “IntegrationTests_3” couldn’t be loaded. Try reinstalling the bundle.
2023-07-03 16:41:54.378059+0530 IntegrationTests_3-Runner[1857:416239] (dlopen(/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/PlugIns/IntegrationTests_3.xctest/IntegrationTests_3, 0x0109): Library not loaded: @rpath/WebDriverAgentLib.framework/WebDriverAgentLib
  Referenced from: <FHGGHJJQWW> /private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/PlugIns/IntegrationTests_3.xctest/IntegrationTests_3
  Reason: tried: '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/PlugIns/IntegrationTests_3.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/PlugIns/IntegrationTests_3.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/PlugIns/IntegrationTests_3.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/PlugIns/IntegrationTests_3.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/var/containers/Bundle/Application/FHGGHJJQWW/IntegrationTests_3-Runner.app/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/System/Developer/Library/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/preboot/Cryptexes/OS/System/Developer/Library/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/System/Developer/usr/lib/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/preboot/Cryptexes/OS/System/Developer/usr/lib/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/Developer/Library/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/preboot/Cryptexes/OS/Developer/Library/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/Developer/usr/lib/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/private/preboot/Cryptexes/OS/Developer/usr/lib/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file), '/System/Library/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib' (no such file, not in dyld cache))

**Comment by jlipps** [comment]
Those don't look like Appium logs.
