### ISSUE TITLE
Could not sign with the default certificate

### ISSUE THREAD

**Issue by venkatprassu** [appium/appium#18797]
Hi Appium Support Team,

I'm currently facing an issue while trying to run my test automation using Appium. I am using the following configuration:

Platform: Android
Device Name: Samsung Galaxy Tab A
Platform Version: 11
UDID: R52MA099ZNN
Automation Name: UiAutomator2
APK Path: C:\Program Files\NoCodeBDD\app\vgo2.apk
The error message I am receiving is as follows:
'An unknown server-side error occurred while processing the command. Original error: Could not sign with the default certificate. Original error Command ''C:\Program Files\Java\jdk-17\bin\java.exe' -jar 'C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\jars\sign.jar' 'C:\Program Files\NoCodeBDD\app\vgo.apk' --override' exited with code 1".

I have already verified the following:

The Java JDK path (C:\Program Files\Java\jdk-17\bin\java.exe) is correct and JDK 17 is installed.
The Appium installation path (C:\Program Files\Appium) is correct.
The APK file path (C:\Program Files\NoCodeBDD\app\vgo.apk) is valid and accessible.
I am using Appium version 1.15.1 and Java JDK 17.

Could you please help me resolve this issue? Any guidance or suggestions would be greatly appreciated.

Thank you for your assistance.

Best regards,
Venkatesh.

**Comment by mykola-mokhnach** [comment]
> I am using Appium version 1.15.1 and Java JDK 17.

We do not support or maintain Appium 1 anymore. Consider using the UIA2 driver supplied with Appium 2.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
