### ISSUE TITLE
getText api does not return `\n` since WDA 4.13.0

### ISSUE THREAD

**Issue by mwakizaka** [appium/appium#18801]
## The problem

As described in https://github.com/appium/appium/issues/17554, when finding an element with XPath and getting the text, I assume it can contain `\n` (i.e. `\n` does not get replaced with a space) since WDA 4.8.0. However, it does not contain `\n` anymore (i.e. `\n` gets replaced with a space) since WDA 4.13.0. I've also confirmed the new behaviour persists on WDA 5.5.0. Which of the behaviours should we expect?

## Current behaviour
Given the following app page,
![193752913-29f5c2c8-6528-4608-86f4-1a5cdb919157](https://github.com/appium/appium/assets/21286384/61717128-9d38-4224-bf2e-ace837baedbe)

when running the following curl commands to WDA,
```
curl -X POST $JSON_HEADER \
-d "{\"using\":\"xpath\",\"value\":\"//XCUIElementTypeStaticText[@name='line break line break']\"}" \
$DEVICE_URL/session/$SESSION_ID/elements
curl -X GET $JSON_HEADER $DEVICE_URL/session/$SESSION_ID/element/${ELEMENT_ID}/text
```

the second curl call returns like
```
{
  "value" : "line break line break",
  "sessionId" : "A6A27CA9-65E1-466F-8B47-EFFC0D03C414"
}
```

## Expected behaviour
The second curl call should return like
```
{
  "value" : "line break\nline break",
  "sessionId" : "1DE744B8-7EC7-4F25-8645-9EC59BDDEADD"
}
```

## Environment

- Appium version (or git revision) that exhibits the issue: WDA 4.13.0
- Last Appium version that did not exhibit the issue (if applicable): WDA 4.12.2
- Desktop OS/version used to run Appium: 
- Node.js version (unless using Appium.app|exe): nodejs 16
- Npm or Yarn package manager: npm 
- Mobile platform/version under test: iOS 16.1 in my env, but this may happen other versions as well. 
- Xcode: 14.1
- Real device or emulator/simulator: at least on simulators
- Appium CLI or Appium.app|exe:

## Code To Reproduce Issue [ Good To Have ]
You can find this new lines text in [iOSWebView.app.zip](https://github.com/appium/appium/files/11844568/iOSWebView.app.zip)
(a sample app for simulator).
SPECIAL CHARACTERS -> \n LINE BREAK -> then, the alert prepare

**Comment by mykola-mokhnach** [comment]
It would be interesting to know what vanilla xctest returns in such case. Could you please run [mobile: source](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/execute-methods.md#mobile-source) with `format` being set to `description` on this alert and attach the output?

**Comment by mwakizaka** [comment]
Thank you checking! Here you are

- [description_wda4.12.2.txt](https://github.com/appium/appium/files/11845729/description_wda4.12.2.txt)
- [description_wda4.13.0.txt](https://github.com/appium/appium/files/11845730/description_wda4.13.0.txt)

**Comment by mykola-mokhnach** [comment]
I don't know what needs to be changed for getText to return line breaks. As far as I can see WDA fetches labels/values without adding any changes to them:

https://github.com/appium/WebDriverAgent/blob/c4853da316f3b8da8520de38f07b9388413a9f8a/WebDriverAgentLib/Categories/XCUIElement%2BFBWebDriverAttributes.m#L120

https://github.com/appium/WebDriverAgent/blob/c4853da316f3b8da8520de38f07b9388413a9f8a/WebDriverAgentLib/Categories/XCUIElement%2BFBWebDriverAttributes.m#L80

**Comment by mykola-mokhnach** [comment]
@Dan-Maor Maybe you have some ideas?

**Comment by Dan-Maor** [comment]
The behavior change is most likely caused by the different kinds of predicates used before and after the aforementioned WDA versions (string vs block predicates) since in 4.13.0 we use string predicates again for XPath (which are faster than block predicates).

See my comment here:
https://github.com/appium/appium/issues/17554#issuecomment-1266666834

We can either bring back block predicates to retain the behavior of 4.8.0 at the cost of performance, or perhaps make it optional with a setting.

@mykola-mokhnach how would you like to proceed?

**Comment by mykola-mokhnach** [comment]
my vote goes for better performance. Ofc, we might introduce a new setting, so people could have more control over that behavior

**Comment by mwakizaka** [comment]
Thank you! I don't think we need it right now. So I'll close this issue once.

**Comment by legionevil** [comment]
hi everyone.
can someone say, what can i do to retrieve those \n in elements values?
i need pure values, not replaced ones.
used drivers 5.2.0 , 4.35.0, 4.12.2 no luck so far.

i can get it through mobile: source with format being set to description, but i need xml source for caching...
