### ISSUE TITLE
bug: <ffmpeg died unexpectedly>

### ISSUE THREAD

**Issue by RakeshKumar8** [appium/appium#18800]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When IOS automation TCs are executed which are housed in two different test classes, the error "ffmpeg died unexpectedly" occurs when the execution of the test case which is in the second test class.
The error is not seen when the execution of TCs are in the same test class

### Expected Behavior

Execution should happen correctly without throwing error

### Minimal Reproducible Example

ffmpeg died unexpectedly

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
Could you share the appium log?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
