### ISSUE TITLE
New to appium and seeing a syntax error when trying to run appium in the command prompt. Please Help!

### ISSUE THREAD

**Issue by zshig235** [appium/appium#18819]
### Discussed in https://github.com/appium/appium/discussions/18818

<div type='discussions-op-text'>

<sup>Originally posted by **zshig235** June 29, 2023</sup>
I tried uninstalling and reinstalling appium but still have this issue where when i try to run appium the latest version, it throws the syntax error before appium starts. 
Here is a snippet of the error, you can view the image for more details.
Fatal SyntaxError: Expected ',' or '}' after property value in JSON at position 9558

Whats weird is that i installed the older version and it is able to start but i cant use that. 
The latest version was working for me last couple of weeks but started seeing this error today. 

<img width="661" alt="appium issue" src="https://github.com/appium/appium/assets/138105847/e687a3f7-6871-4756-855e-ed65435b7ac2">

</div>

**Comment by mykola-mokhnach** [comment]
- make sure node.js is up to date
- If it is then try to delete the .appium folder inside your home dir and uninstall then install the server again

**Comment by zshig235** [comment]
Thank you so much for such a quick response, 
I tried removing .appium and then downloading it again, did not work. 
I'm currently running on node v19.5 
any other suggestions?

**Comment by mykola-mokhnach** [comment]
> downloading it again

What do you mean? Do you use npm to install the server?

> v19.5

I would advice to use an LTS release: either 18 or 20.

**Comment by zshig235** [comment]
yes i use npm i -g appium@next

I was able to solve the problem, thanks to your help i looked in the home directory and found package.json file which the jsonloader function is using. 
This package.json file mustve been updated and had some syntax errors. 
Dude thank you so much!! 

We can close this issue but just a follow up question, should i not be installing via npm?

**Comment by jlipps** [comment]
Yes, installing Appium via NPM is correct. Glad it works! Unfortunately having `package.json` in root user directories can indeed mess with any NPM projects.
