### ISSUE TITLE
Fails to install uiautomator2

### ISSUE THREAD

**Issue by ramanand-rv** [appium/appium#18815]
# Hi, I tried installing uiautomator with different npm versions but it fails.
## Below is the version of the dependencies

C:\Users\ramanand_thakur>node --version
v18.16.1

C:\Users\ramanand_thakur>npm --version
9.7.2

C:\Users\ramanand_thakur>appium --version
2.0.0-rc.3

## It throws the following error:

× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.

STDOUT:
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "C:\\WINDOWS\\system32\\cmd.exe /d /s /c node install-npm.js\n[14:51:52] Error installing Chromedriver: unable to get local issuer certificate\n[14:51:52] Error: unable to get local issuer certificate\n    at Function.AxiosError.from (C:\\Users\\ramanand_thakur\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\core\\AxiosError.js:89:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\ramanand_thakur\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\adapters\\http.js:591:25)\n    at RedirectableRequest.emit (node:events:525:35)\n    at ClientRequest.eventHandlers.<computed> (C:\\Users\\ramanand_thakur\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\follow-redirects\\index.js:14:24)\n    at ClientRequest.emit (node:events:513:28)\n    at TLSSocket.socketErrorListener (node:_http_client:502:9)\n    at TLSSocket.emit (node:events:513:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n[14:51:52] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable."
  }
}

npm ERR! code 1
npm ERR! path C:\Users\ramanand_thakur\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install-npm.js
npm ERR! [14:51:52] Error installing Chromedriver: unable to get local issuer certificate
npm ERR! [14:51:52] Error: unable to get local issuer certificate
npm ERR!     at Function.AxiosError.from (C:\Users\ramanand_thakur\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\AxiosError.js:89:14)
npm ERR!     at RedirectableRequest.handleRequestError (C:\Users\ramanand_thakur\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\adapters\http.js:591:25)
npm ERR!     at RedirectableRequest.emit (node:events:525:35)
npm ERR!     at ClientRequest.eventHandlers.<computed> (C:\Users\ramanand_thakur\.appium\node_modules\appium-uiautomator2-driver\node_modules\follow-redirects\index.js:14:24)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:502:9)
npm ERR!     at TLSSocket.emit (node:events:513:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! [14:51:52] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.

**Comment by mykola-mokhnach** [comment]
It looks like it is not possible to access the chromedriver download CDN for your network. Check https://github.com/appium/appium-uiautomator2-driver#troubleshooting-chromedriver-download-issues or contact your system administrator to resolve the original issue

**Comment by ramanand-rv** [comment]
Hi @mykola-mokhnach 
I managed to resolve this issue by adding the following Environment variable 
![image](https://github.com/appium/appium/assets/80584888/658863fc-dba3-4a73-93cc-f70800bccc3a)

Thanks🤘
