### ISSUE TITLE
Bug: <Appium Inspector is returning the wrong coordinates (images plugin is suspected)>

### ISSUE THREAD

**Issue by JKVelan** [appium/appium#18823]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Tap By Coordinates function is selecting the wrong coordinates (X and Y) on an actual iOS device for the Appium Inspector. The Output displays the correct X and Y axis but for some reason the actual screen position that is clicked is off within the application. 

### Expected Behavior

The Tap Coordinates function should select the appropriate coordinate on a real iOS device. The X Value should have been 821 and Y should have been 224. Instead X was around 824 and Y was around 7.

### Minimal Reproducible Example

1. Launch Appium via Mac Terminal shell command: "appium -ka 10000 --base-path /wd/hub --use-plugins=images"
2. With iOS device attached and proper desired capabilities set, launch Appium with correct Remote Host, Remote Port, and Remote Path
3. After the application boots and passcode is entered into the device (for the driver to initiate) refresh the screen (via Appium Inspector)
4. Select the Tap By Coordinates feature and select an element that should be able to be interacted with via tap. 
5. Observe wrong coordinates are tapped. 
Attaching a capture of this behavior. 

<img width="660" alt="Wrong_Axis" src="https://github.com/appium/appium/assets/138134263/092484eb-31bc-4689-987a-c06f9b4cdc72">

### Environment

**- Operating system:** macOS Ventura 13.4.1
**- Appium server version (output of `appium --version`):** 2.0.0-rc.3
**- Appium driver(s) and their version(s):** Xcuitest: 4.32.10
**- Appium plugin(s) and their version(s):** Images: 2.1.2
**- Node.js version (output of `node --version`):** v20.3.1
**- `npm` version (output of `npm --version`):** 9.6.7
**- Last component(s) version which did _not_ exhibit the problem:** I'm not sure of the exact version but it was working on 6/13 (everything was up to date Appium/driver/plugin wise)
**- Platform and version under test:** iPad Pro 11 inch Gen 3 (1TB variant), issue exhibited on OS version 16.3.1 and 16.5.1.
**- Real device or emulator/simulator:** Real Device

### Link to Appium Logs

https://gist.github.com/JKVelan/62ce7e59218e58973455e424ebdb4e08

### Futher Information

Hello Appium Team,
I've seem to run into a bug with Appium, which seems to revolve around the images plugin potentially. Not only does the Appium Inspector return the wrong coordinates on a Real iOS device but so does the strategy of matching image features as well as finding element by images. In each case the wrong coordinates are returned or visually sampled (in the case of CV comparison). This seemed to be the easiest repro (Appium Inspector) so I figured I would start with this and see if other tickets are needed (or if this is the root cause). In either case I'll be happy to pull further information where needed or log further issues if it helps. 
Thanks in advance for any help!

**Comment by mykola-mokhnach** [comment]
I don't think there is much we could do there. I saw several cases where coordinates for  particular control were shifted and did not match to global screens coordinates. These coordinates are returned by XCTest and there is no way for us to influence that behaviour. The only workaround I know of would be to either calculate gesture coordinates relatively to the container element or to calculate the absolute coordinate shift manually before applying the gesture.

**Comment by JKVelan** [comment]
Thanks for the quick response!
As a curiosity would that also account for this behavior? Or would this be a separate issue?
The example attached is comparing an image with the template (taken via a screenshot) on the iOS device. The blurred part is just EULA text.

![match_result_visual](https://github.com/appium/appium/assets/138134263/451d3282-6da8-4de9-9cf7-516f627c72ef)

**Comment by mykola-mokhnach** [comment]
Images matching is done by OpenCV. I would test different matching methods and verify their results. The images plugin acts as a proxy which translates selenium APIs to corresponding OpenCV calls.

**Comment by JKVelan** [comment]
That makes sense, thanks for the clarification in each case! I'll dig in there and see if I run aground again. FWIW get_images_similarity does seem to be pulling accurate results (score) on a different comparison of UI.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
