### ISSUE TITLE
iOS Bundle ID非xxx.xx.xxx格式，例如（youdaoPro）此类自动化点击应用启动失败

### ISSUE THREAD

**Issue by nanyangzai001** [appium/appium#18827]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![截屏2023-06-30 15 16 50](https://github.com/appium/appium/assets/16077498/717e02f1-f22b-4e3e-b6a0-6fb859107b79)

### Expected Behavior

自动化点击启动成功

### Minimal Reproducible Example

<img width="773" alt="image" src="https://github.com/appium/appium/assets/16077498/fef82806-08d3-4bea-b625-909ab64f93a2">

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Unfortunately we can only process issues reported in English 
Also, Appium 1 is not supported anymore. Consider switching to Appium 2.

**Comment by eglitise** [comment]
The `app` capability expects a path to an application file. You are passing a bundle id, so you need to use the `bundleId` capability.
