### ISSUE TITLE
Appium Flutter Driver | An unknown server-side error occurred while processing the command. 

### ISSUE THREAD

**Issue by chathunm** [appium/appium#18837]
Hi team, I'm a noob for test automation using appium. And don't have much idea about resolving current issue came across while setting up appium-flutter driver.
I've pretty much simple flutter apk build already with the enableFlutterDriverExtension(); capability inside main app method. And following are the configuration in pubspec.yaml
dev_dependencies:
  test : any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

Now when I'm trying to access that apk through my appium test suite it is giving me this error.
my test suite code : 
`const app_config = require('../../config/app_config')
const { beforeEach } = require("mocha");
const wdio = require('webdriverio');

beforeEach(async function () {
    console.log('------------------- Initializing the Platform Driver --------------------------')
    const capabilities = await app_config.data.app_Os_Config()
    /*  capabilities = {
        platformName: 'Android',
        'appium:deviceName': 'sdk_gphone64_x86_64',
        'appium:udid': 'emulator-5554',
        'appium:automationName': 'Flutter',
        'appium:app': '...\app\\android\\app-debug.apk'} 
    */
    return await wdio.remote(capabilities);
});`

Error: Failed to create session.
An unknown server-side error occurred while processing the command. Original error: Cannot read property 'match' of undefined

OS : Windows
and my AndroidWebdriverIO capabilities as this 
{
    port: 4723,
    path: '/wd/hub',
    capabilities: { 
        platformName: 'Android',
        'appium:deviceName': 'sdk_gphone64_x86_64',
        'appium:udid': 'emulator-5554',
        'appium:automationName': 'Flutter',
        'appium:app': app_path
    }

Note : Same behavior observed when initiating this application through Appium Inspector as well. 
But, If I were trying to connect to the app without giving 'appium:automationName': 'Flutter' then connection created without any issue. (applicable for Appium Inspector as well)

Appium Server Log : -----------------------------------
[appium-server-logs.txt](https://github.com/appium/appium/files/11945028/appium-server-logs.txt)

**Comment by mykola-mokhnach** [comment]
- We do not support Appium 1 anymore. Please use Appium 2
- Flutter driver is a third party component which is not maintained by Appium team. Please report your issue into the driver-specific tracker.
