### ISSUE TITLE
Android app automation initialization failed for uiautomator2, the phone is Motorola x30

### ISSUE THREAD

**Issue by yanyun212** [appium/appium#18845]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Android app automation initialization failed for uiautomator2, the phone is Motorola x30; If you use other Android phones, they can run normally

### Expected Behavior

Can automate apps on Moto x30

### Minimal Reproducible Example

....

### Environment

- Operating system:
- Appium server version (output of `appium --version`):2.0.0-rc.5
- Appium driver(s) and their version(s):uiautomator2@2.29.2
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):v18.16.1
- `npm` version (output of `npm --version`):9.5.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:Android 12
- Real device or emulator/simulator:moto x30 

### Futher Information

[appium2.log](https://github.com/appium/appium/files/11957143/appium2.log)
[adb.log](https://github.com/appium/appium/files/11957171/adb.log)

**Comment by mykola-mokhnach** [comment]
```
07-05 18:53:53.005  2362  2521 I ActivityManager: Start proc 12345:io.appium.uiautomator2.server/u0a292 for added application io.appium.uiautomator2.server
07-05 18:53:53.005  5097  9100 W DeviceGuard: [AutoRunServices] onProcessStarted --> pid:12345; uid:10292; process: io.appium.uiautomator2.server; type: [added application]; hostingName = io.appium.uiautomator2.server
07-05 18:53:53.006  5097  5556 I DeviceGuard: [AutoRunServices] onProcessStarted 12345 10292 io.appium.uiautomator2.server snap 121, callBean = null
07-05 18:53:53.006  5097  5556 I DeviceGuard: [AutoRunServices] info.mCount = 0
07-05 18:53:53.006  5097  5556 I DeviceGuard: [AutoRunServices] onProcessStarted waitUids add uid 10292
07-05 18:53:53.006  5097  5556 I DeviceGuard: [AutoRunServices] PackageName :: pkg : io.appium.uiautomator2.server, uid: 0
07-05 18:53:53.006  5097  5556 I DeviceGuard: [AutoRunServices] io.appium.uiautomator2.server top status : 0
07-05 18:53:53.013  5097  5556 I DeviceGuard: [AppCategory] appwidget get com.motorola.timeweatherwidget/com.motorola.commandcenter.row2.RowProvider2
07-05 18:53:53.013 12345 12345 I tomator2.serve: Late-enabling -Xcheck:jni
07-05 18:53:53.014  5097  5556 W DeviceGuard: [AutoRunServices] Find new process: io.appium.uiautomator2.server
07-05 18:53:53.014  5097  5556 W DeviceGuard: [AutoRunServices] sendKillRequest: pkgName = io.appium.uiautomator2.server, pid = 12345, OtherPids = null
07-05 18:53:53.016  5097  5097 I DeviceGuard: [AppCategory] appwidget get com.motorola.timeweatherwidget/com.motorola.commandcenter.row2.RowProvider2
07-05 18:53:53.016  5097  5097 W DeviceGuard: [AutoRunServices] killApp: pkgName = io.appium.uiautomator2.server, uid = 10292, type = 0, component = null, traceId = 0
07-05 18:53:53.017  5097  5097 I DeviceGuard: [AppCategory] appwidget get com.motorola.timeweatherwidget/com.motorola.commandcenter.row2.RowProvider2
07-05 18:53:53.018  5097  5097 I DeviceGuard: [AutoRunServices] before kill app =io.appium.uiautomator2.server
07-05 18:53:53.018  5097  5097 I DeviceGuard: [AutoRunServices] onProcessStarted waitUids remove uid 10292
07-05 18:53:53.019  2362  2978 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10292 user=0: from pid 5097
07-05 18:53:53.020  2362  2978 I ActivityManager: Killing 12345:io.appium.uiautomator2.server/u0a292 (adj -10000, setSvc -10000): stop io.appium.uiautomator2.server due to from pid 5097
07-05 18:53:53.021  5097  9100 I DeviceGuard: [AutoRunServices] onProcessDied --> pid:12345; uid:10292; process: io.appium.uiautomator2.server; reason: stop io.appium.uiautomator2.server due to from pid 5097; setAdj: -10000; setState: 20
07-05 18:53:53.022  2362  2978 W ActivityManager: Crash of app io.appium.uiautomator2.server running instrumentation ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner}
07-05 18:53:53.022  2362  2978 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10292 user=0: finished inst
07-05 18:53:53.024  1148  1148 I Zygote  : Process 12345 exited due to signal 9 (Killed)
07-05 18:53:53.024 12318 12318 D AndroidRuntime: Shutting down VM
07-05 18:53:53.024  5097  5097 W DeviceGuard: [AutoRunServices] Force Stop Package: io.appium.uiautomator2.server uid : 10292
07-05 18:53:53.024  5097  5097 W DeviceGuard: [AutoRunServices] killAppCount: io.appium.uiautomator2.server bean.count = 1
07-05 18:53:53.026  5097  5097 W DeviceGuard: [PackageMonitor] package restarted : data = package:io.appium.uiautomator2.server, uid = 10292
07-05 18:53:53.026  5097  5097 I DeviceGuard: [AutoRunServices] AppStopped : io.appium.uiautomator2.server
07-05 18:53:53.026  5097  5097 I DeviceGuard: [AutoRunServices] onProcessStarted waitUids remove uid 10292
07-05 18:53:53.026  5097  5097 I DeviceGuard: [AutoRunServices] Remove MSG_KILL_RESPONSE_TIMEOUT = io.appium.uiautomator2.server
07-05 18:53:53.027  5097  5464 I DeviceGuard: [GTREE] removeNode uid = 1029
```

It looks like there is some service called "DeviceGuard", which kills the server. Not sure what it is and why it does that though

**Comment by mykola-mokhnach** [comment]
I have found a similar issue mentioned in https://www.mobibrw.com/2021/30885

Seems like it is specific for devices running modified Android firmwares from Chinese manufacturers.

**Comment by yanyun212** [comment]
I learned from a source that some mobile phones will default to disabling the self start permission of io.appium.uiautomatior2. server. I successfully ran the app after opening the self start permission of io.appium.uiautomatior2. server in Motox30 Phone Manager Reference Management Application Self Start

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by shiyeling** [comment]
> I learned from a source that some mobile phones will default to disabling the self start permission of io.appium.uiautomatior2. server. I successfully ran the app after opening the self start permission of io.appium.uiautomatior2. server in Motox30 Phone Manager Reference Management Application Self Start



> I learned from a source that some mobile phones will default to disabling the self start permission of io.appium.uiautomatior2. server. I successfully ran the app after opening the self start permission of io.appium.uiautomatior2. server in Motox30 Phone Manager Reference Management Application Self Start

hi How do you manage to "opening the self start permission of io.appium.uiautomatior2. server in Motox30 Phone Manager Reference Management Application Self Start" I can't find that in settings.

**Comment by shiyeling** [comment]
> > I learned from a source that some mobile phones will default to disabling the self start permission of io.appium.uiautomatior2. server. I successfully ran the app after opening the self start permission of io.appium.uiautomatior2. server in Motox30 Phone Manager Reference Management Application Self Start
> 
> > I learned from a source that some mobile phones will default to disabling the self start permission of io.appium.uiautomatior2. server. I successfully ran the app after opening the self start permission of io.appium.uiautomatior2. server in Motox30 Phone Manager Reference Management Application Self Start
> 
> hi How do you manage to "opening the self start permission of io.appium.uiautomatior2. server in Motox30 Phone Manager Reference Management Application Self Start" I can't find that in settings.

找到了，
新版本的Myui手机管家入口移动到了系统设置里面
