### ISSUE TITLE
bug: Appium WebDriver instance failed to connect to Appium server：Encountered internal error running command: Error executing adbExec. Original error:

### ISSUE THREAD

**Issue by chinawuchen** [appium/appium#18855]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="657" alt="截屏2023-07-08 11 02 35" src="https://github.com/appium/appium/assets/45548406/7e0ec17c-225d-43c2-ad7a-07c4887446be">

<img width="680" alt="截屏2023-07-07 22 28 33" src="https://github.com/appium/appium/assets/45548406/9f154b13-1a2e-4a93-8ca8-8d67871882a8">

<img width="1440" alt="截屏2023-07-08 11 48 33" src="https://github.com/appium/appium/assets/45548406/54c4ae4b-ba3f-4f91-b2ce-1ed87c374aeb">

### Expected Behavior

Can start the App normally

### Minimal Reproducible Example

from appium import webdriver

desired_caps = {
    'platformName': 'Android',
    'deviceName': 'PQY0220A10019160',
    'platformVersion': '12',
    'automationName': 'UiAutomator2',
    'uiautomator2ServerInstallTimeout': 30000,
    'appPackage': 'com.tencent.mm',  
    'appActivity': 'com.tencent.mm.ui.LauncherUI',  
}

driver = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)

driver.launch_app()

### Environment

- Operating system:macOS Monterey12.2.1
- Appium server version (output of `appium --version`):   2.0.0
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):v20.4.0
- `npm` version (output of `npm --version`):9.7.2
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Android 12
- Real device or emulator/simulator:Huawei mate40pro

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description and the full server log as a gist
Also, please translate your report into English

**Comment by chinawuchen** [comment]
> 请提供正确的问题描述和完整的服务器日志作为要点 此外，请将您的报告翻译成英文
Question translated into English

**Comment by chinawuchen** [comment]
> Please provide a proper issue description and the full server log as a gist Also, please translate your report into English

Question translated into English

**Comment by KazuCocoa** [comment]
How long did it take to run `adb install -r --no-incremental /path/to/appium-uiautomator2-server-debug-androidTest.apk` (in the error message) to complete the command against the device?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
