### ISSUE TITLE
How to eliminate the Watermarks of "Automation Running Hold both volume buttons to stop" ?

### ISSUE THREAD

**Issue by lvsejunzhuang** [appium/appium#18853]
When I run WebDriverAgent, a watermark of “Automation Running Hold both volume buttons to stop”appears, which greatly affects user experience. How to modify the code to disable the watermark?

**Comment by KazuCocoa** [comment]
It is a limitation by Apple to run xctest session (Appium's WDA), so we cannot avoid it unfortunately.

**Comment by lvsejunzhuang** [comment]
When I run WebDriverAgent, the screen becomes dark after a while without operating the screen. How can I solve this problem?

**Comment by KazuCocoa** [comment]
Is it a kind of transparent black color? It is also by Apple's design. Only when you manually interact with the device, the dark color will be more normal.

**Comment by lvsejunzhuang** [comment]
But when I don't run WebDriverAgent, it doesn't appear.

**Comment by lvsejunzhuang** [comment]
And running other apps doesn't appear either.

**Comment by KazuCocoa** [comment]
Yes, so the behavior is when xctest session is running like Appium's WDA.

> It is a limitation by Apple to run xctest session (Appium's WDA), so we cannot avoid it unfortunately.

**Comment by lvsejunzhuang** [comment]
Okay, thank you very much for your answer.

**Comment by KazuCocoa** [comment]
https://appium.github.io/appium-xcuitest-driver/4.32/troubleshooting/

> iPhone/iPad real devices show overlay, which has Automation Running Hold both volume buttons to stop text, since iOS/iPadOS 15. This is a known limitation of XCTest framework. This limitation does not affect screenshooting APIs though (e.g. the overlay is not visible on taken screenshots).

**Comment by lvsejunzhuang** [comment]
But I running Hold both volume buttons to stop text，the WebDriverAgent is Stop running，then I can't use appium to automate testing of IOS devices

**Comment by KazuCocoa** [comment]
Yes, stopping the overlay behavior means stopping the xctest session process such as appium/WDA. It is the Apple's limitation for XCTest framework
