### ISSUE TITLE
Lost connection to DTServiceHub

### ISSUE THREAD

**Issue by imvishu11** [appium/appium#18869]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a requirement of settings system permission like Airplane mode and Mobile Data to 'ON'. For that, I am automating it using Appium. Now every time I am changing the Switch status, getting this error- 'Lost connection to DTServiceHub'.  Tried to do the opposite and it is happening in that case too. Attaching small log around the switch toggle for references - 

[debug] [XCUITestDriver@1030 (c443ce06)] Calling AppiumDriver.getTimeouts() with args: ["c443ce06-fc70-4e0b-b919-a18792b62f77"]
[debug] [XCUITestDriver@1030 (c443ce06)] Executing command 'getTimeouts'
[debug] [XCUITestDriver@1030 (c443ce06)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/c443ce06-fc70-4e0b-b919-a18792b62f77/timeouts 304 4 ms - -
[HTTP] 
[Xcode] 
[Xcode] *** If you believe this error represents a bug, please attach the result bundle at /Users/vishalsingh/Library/Developer/Xcode/DerivedData/WebDriverAgent-eptpflukprltwpaoihzeppkcqrgo/Logs/Test/Test-WebDriverAgentRunner-2023.07.11_15-08-15-+0530.xcresult
[Xcode] 
[Xcode] 
[Xcode] 2023-07-11 15:08:36.098 xcodebuild[89159:936312] [MT] IDETestOperationsObserverDebug: 14.936 elapsed -- Testing started completed.
[Xcode] 2023-07-11 15:08:36.099 xcodebuild[89159:936312] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[Xcode] 2023-07-11 15:08:36.099 xcodebuild[89159:936312] [MT] IDETestOperationsObserverDebug: 14.936 sec, +14.936 sec -- end
[Xcode] 
[Xcode] 
[Xcode] Test session results, code coverage, and logs:
[Xcode]     /Users/vishalsingh/Library/Developer/Xcode/DerivedData/WebDriverAgent-eptpflukprltwpaoihzeppkcqrgo/Logs/Test/Test-WebDriverAgentRunner-2023.07.11_15-08-15-+0530.xcresult
[Xcode] 
[Xcode] 
[Xcode] Testing failed:
[Xcode]     Lost connection to DTServiceHub
[Xcode]     testRunner encountered an error (Encountered a problem with the test runner after launch. If you believe this error represents a bug, please attach the result bundle at /Users/vishalsingh/Library/Developer/Xcode/DerivedData/WebDriverAgent-eptpflukprltwpaoihzeppkcqrgo/Logs/Test/Test-WebDriverAgentRunner-2023.07.11_15-08-15-+0530.xcresult. (Underlying Error: Lost connection to DTServiceHub))
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] Testing started
[Xcode] 
[Xcode] xcodebuild exited with code '65' and signal 'null'
[HTTP] --> GET /wd/hub/session/c443ce06-fc70-4e0b-b919-a18792b62f77/timeouts
[HTTP] {}
[text]

### Expected Behavior

Test should run properly after the switch is toggled.

### Minimal Reproducible Example

Start Appium driver on iPhone. While driver is running, try to change Airplane mode state or Mobile Data state.

### Environment

- Operating system:
- Appium server version : 2.0.0
- Appium driver(s) and their version(s): appium-xcuitest-driver - 4.32.19
- Appium plugin(s) and their version(s): execute-driver - 3.0.14
- Node.js version : 20.4.0
- `npm` version : 9.7.2
- Last component(s) version which did _not_ exhibit the problem: Not sure, doing it first time
- Platform and version under test:  iOS - 16.5.1
- Device Info - iPhone 14
- Xcode version: 14.3.1
- Desktop OS/version used to run Appium: macOs Ventura
- Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
I would say this is expected. By changing network state the phone also resets all other connections including the connection to the forwarding proxy. The only possible workaround  I know of might be to recreate the connection with `noReset` option.

**Comment by imvishu11** [comment]
[mykola-mokhnach](https://github.com/mykola-mokhnach) can you explain what do you mean by `noReset` option?

**Comment by KazuCocoa** [comment]
It is one of Appium capabilities > `noReset`

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
