### ISSUE TITLE
Automation issue | Flutter App Date Picker using CupertinoDatePicker library automation issue on iOS

### ISSUE THREAD

**Issue by rajeshgupta42** [appium/appium#18865]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am currently automating a Flutter app, and the developer has implemented a CupertinoDatePicker for date selection (screenshot attached). Upon inspecting the element properties, I found the relevant property specifically for the month selector. Although I can successfully inspect the element, I encounter an issue when attempting to select a different month using the sendKeys function. I have also attempted to use the JavaScript executor, but unfortunately, it has not resolved the problem. I am currently stuck at this point and seeking assistance. Any suggestions would be greatly appreciated. Thank you in advance.
<img width="1252" alt="Screenshot" src="https://github.com/appium/appium/assets/55284420/85bf5206-ed93-4309-b893-883b8d1faeef">

Element Properties:
[{“key”:“elementId”,“value”:“54000000-0000-0000-4719-000000000000”,“name”:“elementId”},{“key”:“type”,“value”:“XCUIElementTypeOther”,“name”:“type”},{“key”:“value”,“value”:“7”,“name”:“value”},{“key”:“enabled”,“value”:“true”,“name”:“enabled”},{“key”:“visible”,“value”:“true”,“name”:“visible”},{“key”:“accessible”,“value”:“true”,“name”:“accessible”},{“key”:“x”,“value”:“213”,“name”:“x”},{“key”:“y”,“value”:“553”,“name”:“y”},{“key”:“width”,“value”:“47”,“name”:“width”},{“key”:“height”,“value”:“183”,“name”:“height”},{“key”:“index”,“value”:“3”,“name”:“index”}]

### Expected Behavior

sendKeys function should work to select date attribute, as we were using it earlier for element havibg tyepe as XCUIElementTypePickerWheel

### Minimal Reproducible Example

Try to automated date picker in flutter app
Select day or month or year and try to set value using send keys

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
> sendKeys function should work to select date attribute, as we were using it earlier for element havibg tyepe as XCUIElementTypePickerWheel

This is defined by XCTest and we cannot influence this functionality. You could probably create an issue to component developers or to Apple. 

There is also a [dedicated driver](https://www.npmjs.com/package/appium-flutter-driver) for flutter apps, which is not maintained by Appium team, but worth trying.

Closed as not an issue

**Comment by rajeshgupta42** [comment]
Thanks @mykola-mokhnach for input
