### ISSUE TITLE
Focused attribute is not present in DOM

### ISSUE THREAD

**Issue by shubham0803** [appium/appium#18863]
### Do I have the most recent component updates?

- [x] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@mykola-mokhnach  We tried running our test (which makes use of focused attribute) on WebdriverAgent-Runner 4.15.0 but we are still getting the same error on iOS -

unknown error: An unknown server-side error occurred while processing the command. Original error: The attribute 'isFocused' is unknown. Valid attribute names are: (
    UID,
    accessibilityContainer,
    accessible,
    enabled,
    frame,
    index,
    label,
    name,
    rect,
    selected,
    type,
    value,
    visible,
    wdAccessibilityContainer,
    wdAccessible,
    wdEnabled,
    wdFrame,
    wdIndex,
    wdLabel,
    wdName,
    wdRect,
    wdSelected,
    wdType,
    wdUID,
    wdValue,
    wdVisible
)
Do we need to upgrade any library in package.json or is there anything else we are missing ? Please do needful here

### Expected Behavior

**Focused** attribute should be accessible in DOM

### Minimal Reproducible Example

https://github.com/appium/appium/issues/18600

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
The most recent module version as of now is 5.5.2
Make sure xcuitest driver is up to date

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
