### ISSUE TITLE
bug: application builds are downloaded multiple times instead of being reused

### ISSUE THREAD

**Issue by dlenroc** [appium/appium#18873]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A normal request is made instead of a conditional request, which causes the application to be re-downloaded.
```bash
---------- App should be reused from cache ----------
info BaseDriver Using downloadable app 'https://github.com/SimpleMobileTools/Simple-Calendar/releases/download/6.22.1/calendar-fdroid-release.apk'
dbug BaseDriver Etag: null -> "0x8DB7ADA06A4E7D0"
dbug BaseDriver Last-Modified: undefined -> Sun, 02 Jul 2023 08:55:03 GMT
dbug BaseDriver Cache-Control: undefined -> undefined
dbug BaseDriver Content-Type: application/vnd.android.package-archive
dbug BaseDriver Content-Disposition: attachment; filename=calendar-fdroid-release.apk
dbug BaseDriver The application (9.31 MB) has been downloaded to '/var/folders/m6/n21qg7xd58l7s725ljt_x7xm0000gq/T/2023614-21586-z5pz8i.iqe9s/calendar-fdroid-release.apk' in 0.134s
```

### Expected Behavior

The previously downloaded app needs to be reused since the conditional request finish with `304 Not Modified`.
```bash
---------- App should be reused from cache ----------
info BaseDriver Using downloadable app 'https://github.com/SimpleMobileTools/Simple-Calendar/releases/download/6.22.1/calendar-fdroid-release.apk'
dbug BaseDriver Last-Modified: Sun, 02 Jul 2023 08:55:03 GMT
dbug BaseDriver Cache-Control: undefined
dbug BaseDriver The application at https://github.com/SimpleMobileTools/Simple-Calendar/releases/download/6.22.1/calendar-fdroid-release.apk has not been modified since Sun Jul 02 2023 11:55:03 GMT+0300 (Eastern European Summer Time)
info BaseDriver Reusing previously downloaded application at '/var/folders/m6/n21qg7xd58l7s725ljt_x7xm0000gq/T/2023614-21660-1dp6tc2.gmvp/calendar-fdroid-release.apk'
```

### Minimal Reproducible Example

```typescript
/**
 * Affected appium package versions:
 *  - appium-uiautomator2-driver: 2.3.0 - 2.29.2 (latest)
 *  - appium-xcuitest-driver: 4.7.1 - 4.32.20 (latest)
 *  - @appium/base-driver: 9.3.4 - 9.3.15 (latest)
 */

// -- android driver
// const { AndroidUiautomator2Driver } = require('appium-uiautomator2-driver');
// const helper = new AndroidUiautomator2Driver().helpers;

// -- xcuitest driver
// const { XCUITestDriver } = require('appium-xcuitest-driver');
// const helper = new XCUITestDriver().helpers;

// -- base driver
const { BaseDriver } = require('@appium/base-driver');
const helper = new BaseDriver().helpers;

(async () => {
  const appUrl = 'https://github.com/SimpleMobileTools/Simple-Calendar/releases/download/6.22.1/calendar-fdroid-release.apk';
  const appExtensions = ['.apk', '.apks'];

  console.log("---------- App should be downloaded ----------");
  await helper.configureApp(appUrl, appExtensions);
  console.log("---------- App should be reused from cache ----------");
  await helper.configureApp(appUrl, appExtensions);
})();
```

**NOTE:** Same is reproducible through the appium java-client when an URL is passed instead of absolute path to build.

### Environment

- Operating system: `macOS 13.4 (22F66)`
- Appium server version: `2.0.0-rc.5`
- Appium driver(s) and their version(s):
   - appium-uiautomator2-driver: `2.3.0` - `2.29.2` (latest)
   - appium-xcuitest-driver: `4.7.1` - `4.32.20` (latest)
   - @appium/base-driver: `9.3.4` - `9.3.15` (latest)
- Node.js version: `v20.3.1`
- `npm` version: `9.6.7`
- Last component(s) version which did _not_ exhibit the problem:
   - appium-uiautomator2-driver: `2.2.0`
   - appium-xcuitest-driver: `4.7.0`
   - @appium/base-driver: `9.3.3`

### Futher Information

It seems that an adjustment is needed here (lines `153`, `155`)

https://github.com/appium/appium/blob/d303527c3da4f657a28b97a2d82eb1a709c6b9bc/packages/base-driver/lib/basedriver/helpers.js#L134-L156

`remoteAppProps.etag/lastModified` are `null` since weren't yet set and either they had to be set or `cachedAppInfo` be used instead.

**Comment by mykola-mokhnach** [comment]
Good catch. https://github.com/appium/appium/pull/18874 should fix it

**Comment by dlenroc** [comment]
Thanks @mykola-mokhnach that's awesome.

For `etag` it will work,
but I'm not sure about `if-modified-since` header since MDN suggests a different value format but I don't have a server that returns `Last-Modified` without `etag` to test that case.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since#syntax

```
> new Date().toString()
'Fri Jul 14 2023 13:17:08 GMT+0300 (Eastern European Summer Time)'
```

```
> new Date().toUTCString()
'Fri, 14 Jul 2023 10:17:28 GMT'
```

**Comment by mykola-mokhnach** [comment]
changed it to `toUTCString`. This is anyway intended to be used as a fallback. The If-None-Match-based caching strategy is much more reliable in general and should be used everywhere.
