### ISSUE TITLE
'touchAction' --> 'tap' is not working 

### ISSUE THREAD

**Issue by 16dec12** [appium/appium#18872]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[0-0] 2023-07-13T10:51:25.776Z INFO webdriver: COMMAND touchPerform(<object>)
[0-0] 2023-07-13T10:51:25.776Z INFO webdriver: [POST] http://127.0.0.1:4723/session/33726ce6-d745-483e-a547-a90f7e2fa082/touch/perform
[0-0] 2023-07-13T10:51:25.776Z INFO webdriver: DATA { actions: [ { action: 'tap', options: [Object] } ] }
[0-0] 2023-07-13T10:51:26.332Z INFO webdriver: RESULT null

### Expected Behavior

tap action to be performed

### Minimal Reproducible Example

code snippet used :

await driver.touchAction({ action: 'tap', x: 60, y: 38 });

### Environment

capabilities : [
  {
    platformName: 'iOS',
    maxInstances: 1,
    'appium:deviceName': 'ADMIN’s iPhone',
    // 'appium:deviceName': 'iPhone 12 mini',
    'appium:platformVersion': '16.5.1',
    'appium:orientation': 'PORTRAIT',
    'appium:automationName': 'XCUITest',
    'appium:newCommandTimeout': 24000,
    //  'appium:autoWebview': false,
    'appium:noReset': true,
    'appium:autoAcceptAlerts' : true,
    'appium:bundleId' : 'com.siemens.commissioning',
    // 'appium:bundleId' : 'com.siemens.evsesg',
    'appium:udid' : '00008110-001649C91A2A401E',
    // 'appium:udid' : '00008101-001570D626A0001E',
    'appium:xcodeSigningId' : 'iPhone Developer',
    'appium:xcodeOrgId' : 'P4R742TV3P',
    'appium:autoGrantPermissions' : true,
    'appium:appiumLogs' : true
  },

appium version : 2.0.0-beta.58
XCODE Version : 14.3.1

**Comment by Higgens75** [comment]
As i know touchActions are deprecated and not longer in Selenium v4
Maybe actionChains working better for you
https://appium.readthedocs.io/en/latest/en/commands/interactions/actions/

**Comment by mykola-mokhnach** [comment]
Please also provide the full server log

**Comment by mykola-mokhnach** [comment]
Make sure you use the most recent driver version. Also, it makes sense to provide gesture coordinates that are relative to an element rather than absolute ones for this driver

**Comment by meghnaec17** [comment]
appium version : 2.0.0-beta.58
XCODE Version : 14.3.1
appium:automationName': 'XCUITest

these are the versions of appium/drivers we have used. 
We are using appium along with webdriverIO for automation. 

We tried using relative coordinates using percentage but that did not work, hence using absolute ones. So based on first comment, do you want us to use Action class to perform 'tap'

**Comment by Higgens75** [comment]
if mykola think it should work with appium2 in your setup, you can try to fix it :)
Only commented this because i had also trouble with touchActions in the past and switched to actionChains which working very good.

**Comment by mykola-mokhnach** [comment]
> We tried using relative coordinates using percentage but that did not work, hence using absolute ones. So based on first comment, do you want us to use Action class to perform 'tap'

It is important to select the correct container there. Eventually "absolute" coordinates in xcuitest app are anyway relative coordinates of the particular XCUIApplication element.

And yes, it always makes sense to drop the usage of touch actions in favour of W3C ones. You could also use [mobile: tap](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/execute-methods.md#mobile-tap) extension as a possible alternative

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
