### ISSUE TITLE
[Feat]: tweak error message for INSTALL_PARSE_FAILED_NO_CERTIFICATES 

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#18878]
**Is your feature request related to a problem? Please describe.**

Allow singing to specify arguments like `--v2-signing-enabled true` for apk signing in Appium.

**Describe the solution you'd like**

Allow `apksigner sign` to give more arguments such as below ones:
```
--v1-signing-enabled  Whether to enable signing using JAR signing scheme (aka v1
                      signing scheme) used in Android since day one. By default,
                      signing using this scheme is enabled based on min and max
                      SDK version (see --min-sdk-version and --max-sdk-version).

--v2-signing-enabled  Whether to enable signing using APK Signature Scheme v2
                      (aka v2 signing scheme) introduced in Android Nougat,
                      API Level 24. By default, signing using this scheme is
                      enabled based on min and max SDK version (see
                      --min-sdk-version and --max-sdk-version).

--v3-signing-enabled  Whether to enable signing using APK Signature Scheme v3
                      (aka v3 signing scheme) introduced in Android P,
                      API Level 28. By default, signing using this scheme is
                      enabled based on min and max SDK version (see
                      --min-sdk-version and --max-sdk-version).  Multiple
                      signers are not supported when using v3 signing, but
                      multiple signers may be provided in conjunction with the
                      "lineage" option to make sure that the app is signed by
                      an appropriate signer on all supported platform versions.

--v4-signing-enabled  Whether to enable signing using APK Signature Scheme v4
                      (aka v4 signing scheme) introduced in Android 11,
                      API Level 30. By default, signing using this scheme is
                      enabled based on min and max SDK version (see
                      --min-sdk-version and --max-sdk-version).
```

to control signing.

e.g. `appium:signArgs: "--v2-signing-enabled true"`

Maybe just a string is sufficient.

**Describe alternatives you've considered**

Apply the sign outside appium

**Additional context**

Usually apksigner apply scheme version by reading the manifecto, but i met a use case to make old apk work for newer os versions. Then, some devices (manufactures?) do not strictly check the sign scheme but some do. so it may be helpful to allow users to specify arguments for `apksigner sign` to run the same script across various devices.

**Comment by mykola-mokhnach** [comment]
- I would rather add some abstract option(s) there rather than a specific one. Maybe in the future we are going to rely on another signing tool
- Not sure how much helpful it would be to have such feature. I mean how we could provide users a hint about using it in the case described above? 
- Can we instead resolve such type of issues automatically?

**Comment by KazuCocoa** [comment]
After some consideration, maybe this won't help so much. The error usually means the app's sign must be fixed to publish it. Maybe the manifest file also need to be fixed. Then, failing properly is expected behavior as test tool.

**Comment by mykola-mokhnach** [comment]
maybe we could improve the actual error message the user sees to make it more helpful?

**Comment by KazuCocoa** [comment]
ah, maybe it makes sense in case the adb install got `INSTALL_PARSE_FAILED_NO_CERTIFICATES` error message to guide the signing tool stuff

**Comment by KazuCocoa** [comment]
Considered again. The error message has the obvious "INSTALL_PARSE_FAILED_NO_CERTIFICATES" word, so.. probably  searching with the word is easier to find the reason than wrapping some additional messages in this case
