### ISSUE TITLE
newCommandTimeout not working in Android/iOS for Appium 2.0.0-beta.46

### ISSUE THREAD

**Issue by aaroncarry** [appium/appium#18871]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use Appium for automated testing on Android/iOS platforms. When creating a session, I set the `newCommandTimeout` to 1200. However, in actual testing, the corresponding session continues to exist for more than two days, and I can still see the session information through the `/wd/hub/sessions` endpoint.

### Expected Behavior

The session automatically quit if no new commands are received after 1200 seconds.

### Minimal Reproducible Example

It seems like this is not a consistent example. 
Set the newCommandTimeout to 1200 when creating the Appium session, but even after waiting for 1200 seconds and using the "get sessions" request, you found that the session is still active in the returned values.

I am unable to accurately reproduce the scenario as the corresponding error occurs during our CI/CD execution. However, I can provide the complete Appium log when the error occurred. Please click on the following gist link. After successfully creating the Appium session, a series of actions were performed, and then further operations on this session were stopped. However, another server requests the session list from this Appium server. The newCommandTimeout time is set to 20 minutes, but even after several hours or even a day or two, the session still persists.

(Gist link: [Click Here](https://gist.github.com/aaroncarry/1e628a1380f61a771d43171e859425a5))

### Environment

- Operating system:
- Appium server version (output of `appium --version`):2.0.0-beta.46
- Appium driver(s) and their version(s): xcuitest driver is 8.7.3
- Appium plugin(s) and their version(s): 
- Node.js version (output of `node --version`):v14.18.0
- `npm` version (output of `npm --version`):8.19.3
- Last component(s) version which did _not_ exhibit the problem: no sure, this is an intermittent issue.
- Platform and version under test: MacOS 13.3.1
- Real device or emulator/simulator: both of real device/emulator

### Link to Appium Logs

https://gist.github.com/aaroncarry/1e628a1380f61a771d43171e859425a5

### Futher Information

when i get session list：
<img width="1238" alt="image" src="https://github.com/appium/appium/assets/24429337/11c76731-f79f-43f2-8361-fe4f96411837">

When I get the specific session using this session ID...
<img width="1272" alt="image" src="https://github.com/appium/appium/assets/24429337/68e551cb-448f-4753-9afd-2eaf32bc3679">

**Comment by mykola-mokhnach** [comment]
This is probably expected. `newCommandTimeout` is only checked before a new `session` command is delivered. `/sessions` is a "global" command though, it is not counted there. So the steps to make it work would be:
- Run some in-session command
- Wait until newCommandTimeout expires
- Run another in-session command, so the session is deleted
- Check the output of /sessions and make sure the session is not present there anymore

**Comment by aaroncarry** [comment]
> This is probably expected. `newCommandTimeout` is only checked before a new `session` command is delivered. `/sessions` is a "global" command though, it is not counted there. So the steps to make it work would be:
> 
> * Run some in-session command
> * Wait until newCommandTimeout expires
> * Run another in-session command, so the session is deleted
> * Check the output of /sessions and make sure the session is not present there anymore

Thank you for your prompt response.

I apologize for the confusion. What I want to express is that the session does not end automatically after exceeding newCommandTimeout.
Continuous polling of the session list is done by another internal service of ours to collect Appium/device status information. It is also by constantly checking the session list that we find that the session that should have ended still exists.

**Comment by Dor-bl** [comment]
@aaroncarry appium 2 is out of beta stage, please update to latest version and try again.

**Comment by mykola-mokhnach** [comment]
> I apologize for the confusion. What I want to express is that the session does not end automatically after exceeding newCommandTimeout.

This is just how newCommandTimeout works and always worked. It does not execute session shutdown timer, but instead just remembers the timestamp of the last session command and then compares it with the current one when the next one gets triggered.

**Comment by aaroncarry** [comment]
> > I apologize for the confusion. What I want to express is that the session does not end automatically after exceeding newCommandTimeout.
> 
> This is just how newCommandTimeout works and always worked. It does not execute session shutdown timer, but instead just remembers the timestamp of the last session command and then compares it with the current one when the next command gets triggered.

But according to my experience, Appium will output the log of shut down the session after newCommandTimeout.
like:
```
2023-07-13 15:20:49:325 - [35m[XCUITestDriver@2d7f (9ead914a)][39m Shutting down because we waited 60 seconds for a command
2023-07-13 15:20:49:325 - [35m[AppiumDriver@2988][39m Ending session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
```
![image](https://github.com/appium/appium/assets/24429337/a3f3ee22-c0a1-4759-81de-eaa8d78ed8f5)


And can't get session info from session list anymore:
<img width="826" alt="image" src="https://github.com/appium/appium/assets/24429337/0dbc154b-e5c7-47af-a4a2-619f8749be5f">


Is there something wrong with my use or understanding?

**Comment by mykola-mokhnach** [comment]
I have double checked the code responsible for this functionality and it definitely looks differently from what I remember. 

What If you try to perform the same scenario with the images plugin disabled, does it make any diff?

**Comment by mykola-mokhnach** [comment]
Also please try it using the most recent driver version like @Dor-bl mentioned above

**Comment by aaroncarry** [comment]
> I have double checked the code responsible for this functionality and it definitely looks differently from what I remember.
> 
> What If you try to perform the same scenario with the images plugin disabled, does it make any diff?


Now no matter whether I enable the image plugin or not, newCommandTimeout can work well.
It seems to be an occasional problem.
I can't directly distinguish whether the image plugin has an impact from the user's perspective...

**Comment by aaroncarry** [comment]
> Also please try it using the most recent driver and server version like @Dor-bl mentioned above

sure, i will try and report if it reproduce in latest version

**Comment by jlipps** [comment]
for the record, pretty sure that newCommandTimeout expiry has always shut down the session. that was always the point of it (to account for a situation where the client goes away while a session is in progress. this is a very common situation when people have exceptions in their test code that don't result in a teardown/cleanup being run to quit the session).

**Comment by mykola-mokhnach** [comment]
@jlipps My assumption here was that getSessions call (umbrella API), which must not reset the command timeout timer for active drivers, might have an issue related to plugins enablement.

**Comment by jlipps** [comment]
@mykola-mokhnach ok makes sense.

I wonder if there is a bug here in that `startNewCommandTimeout` ends up calling `this.deleteSession` on timeout, but in this case `this` is the inner driver. So that driver is indeed shutdown, but the umbrella driver doesn't know that it went away and therefore doesn't remove its session id from the list of session ids?

@aaroncarry can you confirm which of the following is the issue you encountered: 
- after the command timeout, the session shuts down (is no longer able to receive commands without error), but still shows up in the get sessions list
- after the command timeout, the session is still active (is able to receive commands), and so also shows up in the get sessions list

**Comment by aaroncarry** [comment]
@jlipps 
Based on the behavior of the session at that time, it seems to be the first case because when I tried to get the session by ID, I received the following error message: `An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up.`

**Comment by jlipps** [comment]
OK thanks, I'll investigate this

**Comment by jlipps** [comment]
@aaroncarry I went to look at this but am having trouble reproducing an issue. And in the gist you provided, I don't see any new command timeout happening at all. Do you have any more information that might help?

**Comment by aaroncarry** [comment]
> @aaroncarry I went to look at this but am having trouble reproducing an issue. And in the gist you provided, I don't see any new command timeout happening at all. Do you have any more information that might help?

@jlipps 
I believe this is a very sporadic issue. In our daily automated testing, we create over 5k sessions every day, and this problem may occur once or twice a month. This is the information I can provide because even during my local debugging, it's hard to reproduce this issue.

From the logs, I can see that the new command timeout is provided in the capabilities. However, in practice, when the corresponding timeout is reached, Appium doesn't seem to take any action to terminate the session.

BTW,we start Appium using the following command:
`appium -p %APPIUM_PORT% --relaxed-security --log-timestamp --local-timezone --base-path /wd/hub --use-plugins=relaxed-caps,images > ~/appium_logs/appium_%APPIUM_PORT%.log 2>&1 &`

**Comment by jlipps** [comment]
Hmm yeah a 0.001% failure rate is a bit hard to reproduce/diagnose.

I wrote a new test that proves `getSessionDetails` does not circumvent a driver timeout, at any rate.

**Comment by jlipps** [comment]
@aaroncarry how often do you restart your appium servers?

**Comment by aaroncarry** [comment]
> @aaroncarry how often do you restart your appium servers?

everyday

**Comment by aaroncarry** [comment]
@jlipps we reproduce this issue in our daily testing.

session id: c6369f3a-a92d-4cf7-8998-7c058d441cab create at **2023-07-25 22:16**.
After a period of testing, despite the client not actively sending a delete session command to server, there have been no further command sent to this session.
But session still exist at **2023-07-26 09:17**

Appium Version:2.0.0-beta.53
Appium log:https://gist.github.com/aaroncarry/58c2d64e3d1476b6f8808e2ab05d4dd3

**Comment by jlipps** [comment]
@aaroncarry in that log, i see that in addition to calling `GET /sessions` you're also calling `GET /session/:id/screenshot`, which would prevent the timeout from happening. could this be the cause?

**Comment by aaroncarry** [comment]
@jlipps The last request for `GET /session/:id/screenshot` was sent around 11:14 PM, and after that, there were no new screenshot requests sent. the session still exists in the sessions list until 9 AM the next morning...

From that log, i don't think that is screenshot request refreshed the newCommandTimeout Timer

**Comment by jlipps** [comment]
@aaroncarry do you have the log of that timeframe? if this log isn't even representing the window of time where the problem pops up I don't think it will be useful.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by linyayu** [comment]
appium 2.1.3 still can reproduce this issue

**Comment by linyayu** [comment]
It happened on commad appear exception(like NoSuchElement) with plugin(image)
