### ISSUE TITLE
bug: test is not launching application with new appium 2.0.0

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#18880]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to run a simple test which is only reaching my tested app home screen, but Appium server is showing the famous 65 error code from the webDriverAgent

```
08:24:09  IosAppiumWrapper: activate application with desired capabilities:
08:24:09  {'noReset': True, 'fullReset': False, 'platformVersion': '16.5.1 (c)', 'deviceName': 'qa_iphone_04', 'udid': '00008110-001115E41185401E', 'bundleId': 'com.shs.DeploymentManager', 'xcodeOrgId': 'BX9P2F4G47', 'xcodeSigningId': 'iPhone Developer', 'automationName': 'XCUITest', 'app': 'http://mv-nexus-new.corp.aeroscout.com:8081/repository/mobile-products/ios/development/deployment/master/Deployment.ipa', 'platformName': 'iOS'}
08:25:17  Fatal Error, test failed connecting with Appium server
08:25:17  Message: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
08:25:17  xcodebuild error message:
08:25:17  . Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
```

I can confirm that I managed to build the webAgentDriver runner ios app correctly, and this is really not the case. 
The issue is started showing after installing the new Appium 2.0.0, I did not experience the problem with Appium 2 beta versions. 

### Expected Behavior

Application should be launched

### Minimal Reproducible Example

Shared above,

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.0.0
- Appium driver(s) and their version(s): latest
- Appium plugin(s) and their version(s):latest
- Node.js version (output of `node --version`): 16.20.0
- `npm` version (output of `npm --version`): 9.8.0
- Last component(s) version which did _not_ exhibit the problem: appium 2.0.0-Beta66
- Platform and version under test: iOS, mac 13.4.1
- Real device or emulator/simulator: real device

### Link to Appium Logs

https://github.com/bwomsm1/AppiumLogs/blob/master/appium_ios.log

### Futher Information

```
08:24:09  IosAppiumWrapper: activate application with desired capabilities:
08:24:09  {'noReset': True, 'fullReset': False, 'platformVersion': '16.5.1 (c)', 'deviceName': 'qa_iphone_04', 'udid': '00008110-001115E41185401E', 'bundleId': 'com.shs.DeploymentManager', 'xcodeOrgId': 'BX9P2F4G47', 'xcodeSigningId': 'iPhone Developer', 'automationName': 'XCUITest', 'app': 'http://mv-nexus-new.corp.aeroscout.com:8081/repository/mobile-products/ios/development/deployment/master/Deployment.ipa', 'platformName': 'iOS'}
08:25:17  Fatal Error, test failed connecting with Appium server
08:25:17  Message: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
08:25:17  xcodebuild error message:
08:25:17  . Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
```

**Comment by bwomsm1** [comment]
@mykola-mokhnach @jlipps this is super weird, I did not get this error for years (5+) and my WegbAgentDriver is build as I always used to work with it.
But I still getting this `xcodebuild failed with code 65` since I upgraded to the new Appium 2.0.0 (with the beta versions) I did not have any problems. 
The appium server log is not showing anything that can point the problem.

Do you mind taking a look?

**Comment by mykola-mokhnach** [comment]
This does not look like xcuidriver issue to me, but rather a codesigning error. Have you tried to build WDA manually with the same parameters?

**Comment by bwomsm1** [comment]
@mykola-mokhnach "build manually" you mean to open the `WebDriverAgent project` in xCode and build it.
**Yes**, I cleared the prev build in xCode and rebuild it from scratch, also uninstalled the build from the iPhone device.

**Comment by KazuCocoa** [comment]
What happens when you run the command below?

> xcodebuild build-for-testing test-without-building -project /Users/mac-auto-03/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/mac-auto-03/Desktop/xcode/WebDriverAgent-gumfbzqdnxozvhfskwicepuzaxuz -destination id=00008110-001115E41185401E IPHONEOS_DEPLOYMENT_TARGET=16.5 -xcconfig /var/folders/rp/3z7xhhfd09j62ntn209c8rxh0000gn/T/2023616-1446-j309y6.nlxw/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO

`showXcodeLog` capability may help to see the xcodebuild log details. Generally, code 65 is singing stuff.

**Comment by bwomsm1** [comment]
@KazuCocoa it is actually stuck in the last line here: https://github.com/bwomsm1/AppiumLogs/blob/master/build.log

**Comment by KazuCocoa** [comment]
It is expected. It means the WDA process was running.

The build did not have `xcodebuild failed with code 65`. What happens when you run appium session again? Then, please check if the new session has the same command, at least `-project` and `-derivedDataPath` are the same

**Comment by bwomsm1** [comment]
@KazuCocoa not sure what was the problem exactly but eventually I uninstalled and reinstalled  appium and the WebAgentDriver app, these actions workaround the problem.

**Comment by swapnilGirishPawar** [comment]
Hi @bwomsm1, @KazuCocoa @mykola-mokhnach, I am a newbie in appium2.0, and I am facing the same issue.
I just raised it as an issue -  https://github.com/appium/appium/issues/18917
I am able to run the tests on an iOS simulator, but not able to install WDA on a real device.
can you please help me to resolve it?

**Comment by bwomsm1** [comment]
@swapnilGirishPawar are you sure you managed to build on xCode the WAD?
(`No WDAs on the device.`)

**Comment by swapnilGirishPawar** [comment]
@bwomsm1

**Steps I followed in manual installation of WDA:-** 
1. I Opened WebDriverAgent.xcodeproj file in Xcode
2. Changed the product bundle identifier for webDriverAgentLib and webDriverAgentRunner to something else.
3. I tried to build those files on a real device.
4. It gave me "/Users/swapnil/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj No profiles for 'com.full.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.full.WebDriverAgentRunner.xctrunner'." this error.

I don't know the other alternatives. @bwomsm1 you are talking about the same I guess, if not can you please explain about that?

**Comment by bwomsm1** [comment]
Not sure you need to change the bundle identifier, 
make sure that this well defined on your local:
![Screenshot 2023-07-26 at 14 09 15](https://github.com/appium/appium/assets/5571230/1cca831c-d7a8-4e42-9163-000f5f913995)


and build the runner

**Comment by swapnilGirishPawar** [comment]
@bwomsm1 - yes I tried the same way. But I got the same error - 

1.

<img width="1429" alt="Screenshot 2023-07-26 at 5 23 36 PM" src="https://github.com/appium/appium/assets/85121754/56e5facd-b656-457a-a14a-b3764278ac04">

2.  I got this error after running the WebDriverAgentRuner file on a real Device.

<img width="567" alt="Screenshot 2023-07-26 at 5 21 27 PM" src="https://github.com/appium/appium/assets/85121754/8a6ad35d-d6a5-4984-8bae-e0559a027905">

**Comment by bwomsm1** [comment]
I am not sure that your apple id is allowed to build app against real device. but maybe I am wrong.

**Comment by swapnilGirishPawar** [comment]
Oh okay, that might be the reason. btw Thanks for the help @bwomsm1.
