### ISSUE TITLE
Unable to connect ios simulator with appium inspector 

### ISSUE THREAD

**Issue by rushanmr** [appium/appium#18884]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting error while connecting appium inspctor with iOS simulator
![Screenshot 2023-07-17 at 11 59 33 AM](https://github.com/appium/appium/assets/131346428/c736c174-3d64-4e18-9b11-984ac5f0b2db)

### Expected Behavior

shpuld needs to connect iOS simulator

### Minimal Reproducible Example

trying to connect iOS Simulator with appium inspector . 

### Environment

- Operating system:Mac OS ventura 13
- Appium server version (output of `appium --version`):2.0.0
- Appium driver(s) and their version(s):latest
- Appium plugin(s) and their version(s):latest
- Node.js version (output of `node --version`):18.16.1
- `npm` version (output of `npm --version`):9.5.1
- Last component(s) version which did _not_ exhibit the problem:NA
- Platform and version under test:iOS 
- Real device or emulator/simulator:Simulator 16.4

### Link to Appium Logs

No plugins activated. Use the --use-plugins flag with names of plugins to activate [HTTP] --> GET /wd/hub/sessions [HTTP] {} [debug] [HTTP] No route found for /wd/hub/sessions [HTTP] <-- GET /wd/hub/sessions 404 9 ms - 211 [HTTP]  [HTTP] --> POST /wd/hub/session [HTTP] {"capabilities":{"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"16.4","appium:deviceName":"iPhone 14 Pro","appium:automationName":"XCUITest","appium:bundleId":"com.hotake.Hotake","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"iOS","appium:platformVersion":"16.4","appium:deviceName":"iPhone 14 Pro","appium:automationName":"XCUITest","appium:bundleId":"com.hotake.Hotake","appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}} [debug] [HTTP] No route found for /wd/hub/session [HTTP] <-- POST /wd/hub/session 404 6 ms - 211 [HTTP]

**Comment by mykola-mokhnach** [comment]
The error is expected. Please make sure you've carefully read the migration guide: https://github.com/appium/appium/blob/master/packages/appium/docs/en/guides/migrating-1-to-2.md
