### ISSUE TITLE
bug: Appium setting "boundElementsByIndex" doesn't work with Appium 2.0

### ISSUE THREAD

**Issue by MishkaTheCub** [appium/appium#18886]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium returns the following error:

_org.openqa.selenium.StaleElementReferenceException: The previously found element ""Watch Live" Button" is not present in the current view anymore. Make sure the application UI has the expected state. You could also try to switch the binding strategy using the 'boundElementsByIndex' setting for the element lookup. Original error: No matches found for Identity Binding from input {(
         Button, {{101.7, 391.7}, {171.7, 60.0}}, label: 'Watch Live',
         StaticText, {{140.0, 411.7}, {95.0, 20.0}}, label: 'Watch Live'
     )}
     For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html_

Even though the appium setting is enabled in the capabilities: capabilities.setCapability("settings[boundElementsByIndex]", true);

### Expected Behavior

Expected: the element is found and clicked.

### Minimal Reproducible Example

https://gist.github.com/MishkaTheCub/006dd61ae9cb39f8139baa2df28c0581

### Environment

- Operating system: macOS Ventura 13.4.1
- Appium server version (output of `appium --version`): 2.0.0 release
- Appium driver(s) and their version(s): xcuitest@4.32.21
- Appium plugin(s) and their version(s): relaxed-caps@1.0.5
- Node.js version (output of `node --version`): 18.30.0
- `npm` version (output of `npm --version`): 8.11.0
- Last component(s) version which did _not_ exhibit the problem: appium 2.0 beta 44
- Platform and version under test: iOS 16.5.1
- Real device or emulator/simulator: real device
 

### Link to Appium Logs

https://gist.github.com/MishkaTheCub/b3431514a6cadc9544d55e04655003cb

**Comment by KazuCocoa** [comment]
What the result of the below command to the appium/WDA directly? `boundElementsByIndex` may have `true` or `false`. It helps to check if `boundElementsByIndex` was enabled.

e.g.:
`http://127.0.0.1:8100/session/<your appium/WDA session id>/appium/settings`
```
{
  "value" : {
    "boundElementsByIndex" : true,
    "mjpegServerFramerate" : 10,
    "screenshotOrientation" : "auto",
    "reduceMotion" : false,
    "elementResponseAttributes" : "type,label",
    "screenshotQuality" : 3,
    "mjpegScalingFactor" : 100,
    "keyboardPrediction" : 0,
    "defaultActiveApplication" : "auto",
    "mjpegServerScreenshotQuality" : 25,
    "defaultAlertAction" : "",
    "keyboardAutocorrection" : 0,
    "useFirstMatch" : false,
    "shouldUseCompactResponses" : true,
    "customSnapshotTimeout" : 15,
    "dismissAlertButtonSelector" : "",
    "activeAppDetectionPoint" : "64.00,64.00",
    "snapshotMaxDepth" : 50,
    "waitForIdleTimeout" : 10,
    "includeNonModalElements" : false,
    "acceptAlertButtonSelector" : "",
    "animationCoolOffTimeout" : 2
  },
  "sessionId" : "70990394-5C4E-493A-A661-ED4F9734E39B"
}
```

> Last component(s) version which did not exhibit the problem: appium 2.0 beta 44

Do you have the xcuitest driver version and the full log?
