### ISSUE TITLE
iOS Bundle ID non-xxx.xx.xxx format, for example (youdaoPro) such as automated click application startup failurebug: <title>

### ISSUE THREAD

**Issue by nanyangzai001** [appium/appium#18882]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

iOS Bundle ID non-xxx.xx.xxx format, for example (youdaoPro) such as automated click application startup failure.
Appium 1 and Appium 2 both have this problem, the App Store download link for the case is: https://apps.apple.com/cn/app/%E7%BD%91%E6%98%93%E6%9C%89%E9%81%93%E8%AF%8D%E5%85%B8-%E9%AB%98%E6%95%88%E5%AD%A6%E4%B9%A 0app/id353115739

![1111250021956-717e02f1-f22b-4e3e-b6a0-6fb859107b79](https://github.com/appium/appium/assets/16077498/895f08dd-7d96-4081-a4c8-79ed6e231717)

### Expected Behavior

Startup success

### Minimal Reproducible Example

<img width="773" alt="2250022409-fef82806-08d3-4bea-b625-909ab64f93a2" src="https://github.com/appium/appium/assets/16077498/7b9b494c-9128-434c-8b69-b65e183f76b0">

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
This behaviour is expected. `app` must be a valid path to an app or an URL. If you want to provide a bundle identifier of an already installed app then use the `bundleId` capability instead.

**Comment by nanyangzai001** [comment]
The bundleId problem has been solved. Thank you very much
