### ISSUE TITLE
[Feat]: Update chromedriver download logic for v115+

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#18897]
**Is your feature request related to a problem? Please describe.**

Chromedriver moved the place to download from https://chromedriver.storage.googleapis.com/index.html to `https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/<version>/<platform>/file.zip`. The path is available in https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints but we should update some auto downlaod logic for it.

https://github.com/appium/appium-chromedriver

**Describe the solution you'd like**

Update the auto download logic

**Describe alternatives you've considered**

Not special.

As a short term workaround, users can specify `appium:chromedriverExecutable` or `appium:chromedriverExecutableDir ` with a proper config to find a proper chrome version in https://googlechromelabs.github.io/chrome-for-testing/
Please read these capabilities in https://github.com/appium/appium-uiautomator2-driver

**Additional context**

**Comment by aristeia** [comment]
From my testing, `chromedriver_autodownload` now seems non-functional by default for Android devices running Chrome version 115, which version has rolled out from the app store in the past day

**Comment by KazuCocoa** [comment]
Yes, maybe still v115 is on the way to staged rollout but we should update the autodownload in https://github.com/appium/appium-chromedriver to make the autodownload again for 115+.

I'll do that by finding time to work on it

**Comment by mykola-mokhnach** [comment]
I'll work on that

**Comment by KazuCocoa** [comment]
thank you, appreciate it

**Comment by garg3133** [comment]
Can we not somehow use [selenium-manager](https://github.com/SeleniumHQ/selenium/tree/trunk/rust) for automatically downloading the required drivers, like it does for selenium?

**Comment by KazuCocoa** [comment]
appium-chromedriver has it for us. This issue is Google changed the url etc suince chromedriver v115 so the logic needs to be updated

**Comment by mykola-mokhnach** [comment]
Done in https://github.com/appium/appium-chromedriver/pull/333
