### ISSUE TITLE
Error when executing script to launch

### ISSUE THREAD

**Issue by rushanmr** [appium/appium#18891]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have successfully connected ios sim thoru=ough appium inspector.But when i try to execute via script getting these error.
[RemoteTestNG] detected TestNG version 7.8.0
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 5 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 12 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.collectMethodsByGroup() took 0 ms.
[main] INFO org.testng.internal.Utils - [Utils] MethodGroupsHelper.sortMethods() took 0 ms.
[main] INFO org.testng.internal.Utils - [TestNG] Running:
  /private/var/folders/b7/_gnptsqx6k33xn10c33d39h00000gn/T/testng-eclipse--241914905/testng-customsuite.xml

[main] INFO org.testng.internal.Utils - [Utils] DynamicGraphHelper.createDynamicGraph() took 3 ms.
FAILED CONFIGURATION: @BeforeSuite com.stunt.base.BaseClass.initialization
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 63 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Rushans-Mac-mini.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.4.1', java.version: '17.0.7'
Driver info: driver.version: AndroidDriver
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Rushans-Mac-mini.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.4.1', java.version: '17.0.7'
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
	at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:86)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)
	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:94)
	at com.stunt.base.BaseClass.initialization(BaseClass.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
	... 33 more

### Expected Behavior

It should needs to launch application

### Minimal Reproducible Example

scripts which i am using:
@BeforeSuite
		public void initialization() {
			String OS = configprop.getProperty("OS").toLowerCase();
			if (OS.equals("iOS")) {
				DesiredCapabilities cap = new DesiredCapabilities();
				cap.setCapability(IOSMobileCapabilityType.BUNDLE_ID, configprop.getProperty("Bundleid"));
				cap.setCapability(MobileCapabilityType.DEVICE_NAME, configprop.getProperty("IOSDeviceName"));
				cap.setCapability(MobileCapabilityType.PLATFORM_NAME, configprop.getProperty("IOSPlatformName"));
				cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, configprop.getProperty("IOSPlatformVersion"));
				cap.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
				cap.setCapability(MobileCapabilityType.NO_RESET, true);
				// cap.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, 500000);
				// cap.setCapability("commandTimeouts", "12000");
				// cap.setCapability("udid", configprop.getProperty("IOSudid"));
				// cap.setCapability("appPackage", configprop.getProperty("AppPackage"));
				// cap.setCapability("appActivity", configprop.getProperty("AppActivity"));
				try {
					URL url;
					url = new URL("http://127.0.0.1:4723/");
					driver = new IOSDriver<WebElement>(url, cap);
					driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
				} catch (MalformedURLException e) {
					e.printStackTrace();
				}
				try {
					Thread.sleep(5000);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				System.out.println("Application launched....");
				driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
			} else {
				DesiredCapabilities caps = new DesiredCapabilities();
				caps.setCapability("Device Name", configprop.getProperty("AndroidDeviceName"));
				caps.setCapability("udid", configprop.getProperty("Androidudid"));
				caps.setCapability("platformName", configprop.getProperty("AndroidPlatformName"));
				caps.setCapability("platformVersion", configprop.getProperty("AndroidPlatformVersion"));
				caps.setCapability(MobileCapabilityType.NO_RESET, true);
				caps.setCapability("appPackage", configprop.getProperty("AppPackage"));
				caps.setCapability("appActivity", configprop.getProperty("AppActivity"));
				try {
					URL url;
					url = new URL("http://0.0.0.0:4723/wd/hub");
					driver1 = new AndroidDriver<WebElement>(url, caps);
					driver1.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
				} catch (MalformedURLException e) {
					e.printStackTrace();
				}
				try {
					Thread.sleep(5000);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				System.out.println("Application launched....");
				driver1.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
			}
		}

### Environment

- Operating system:mac
- Appium server version (output of `appium --version`):2
- Appium driver(s) and their version(s):latest
- Appium plugin(s) and their version(s):latest
- Node.js version (output of `node --version`):v18.16.1
- `npm` version (output of `npm --version`):9.5.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:iOS
- Real device or emulator/simulator:Simulator

### Link to Appium Logs

] No route found for /wd/hub/session [HTTP] <-- POST /wd/hub/session 404 0 ms - 211 [HTTP]  [HTTP] --> GET /session/adc91eed-186a-45bd-841b-7a8ae9163a53/timeouts [HTTP] {} [debug] [XCUITestDriver@87f9 (adc91eed)] Calling AppiumDriver.getTimeouts() with args: ["adc91eed-186a-45bd-841b-7a8ae9163a53"] [debug] [XCUITestDriver@87f9 (adc91eed)] Executing command 'getTimeouts' [debug] [XCUITestDriver@87f9 (adc91eed)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0} [HTTP] <-- GET /session/adc91eed-186a-45bd-841b-7a8ae9163a53/timeouts 304 1 ms - - [HTTP]  [HTTP] --> POST /wd/hub/session [HTTP] {"desiredCapabilities":{"appActivity":"com.hotake.hotake.MainActivity","appPackage":"com.hotake.hotake","noReset":true,"platformVersion":"11","Device Name":"sdk_gphone64_x86_64","platformName":"Android","udid":"emulator-5554"},"capabilities":{"firstMatch":[{"Device Name":"sdk_gphone64_x86_64","appium:appActivity":"com.hotake.hotake.MainActivity","appium:appPackage":"com.hotake.hotake","appium:noReset":true,"platformName":"android","appium:platformVersion":"11","appium:udid":"emulator-5554"}]}} [debug] [HTTP] No route found for /wd/hub/session [HTTP] <-- POST /wd/hub/session 404 0 ms - 211 [HTTP]  [HTTP] --> GET /session/adc91eed-186a-45bd-841b-7a8ae9163a53/timeouts

**Comment by KazuCocoa** [comment]
The attached code had two URL patterns. In your case, perhaps `http://127.0.0.1:4723/` might be the expected one.

```
				try {
					URL url;
					url = new URL("http://127.0.0.1:4723/");
					driver = new IOSDriver<WebElement>(url, cap);
					driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
				} catch (MalformedURLException e) {
					e.printStackTrace();
				}
```

```
				try {
					URL url;
					url = new URL("http://0.0.0.0:4723/wd/hub");
					driver1 = new AndroidDriver<WebElement>(url, caps);
					driver1.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
				} catch (MalformedURLException e) {
					e.printStackTrace();
				}
```

**Comment by rushanmr** [comment]
Thanks @KazuCocoa .It worked .

**Comment by farukuraz16** [comment]
how to fix that? I have same issue..

**Comment by KazuCocoa** [comment]
No logs, then we could not say anything. Although, the message above is TestNG related log I guess
