### ISSUE TITLE
opening application in simulator leads to slow down the process.

### ISSUE THREAD

**Issue by rushanmr** [appium/appium#18898]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I open application in simulator then its loading like(stucked).It leads to slow down my whole mac mini. My whole system is working too slow. 
Tried with lower/higher version of simulator too,Still hanging
system configuration:
Processor: 3 GHz 6-Core Intel Core i5 
Graphics:Intel UHD Graphics 630 1536 MB
Memory:16 GB 2667 MHz DDR4
macOS:Ventura Version 13.4.1 

### Expected Behavior

It should work smoothly.

### Minimal Reproducible Example

installed app in simulator
opening application 

### Environment

- Operating system:Mac iOS
- Appium server version (output of `appium --version`):2
- Appium driver(s) and their version(s):latest
- Appium plugin(s) and their version(s):latest
- Node.js version (output of `node --version`):18
- `npm` version (output of `npm --version`):14
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:iOS
- Real device or emulator/simulator:simulator.

**Comment by KazuCocoa** [comment]
It seems like you should report it to Apple rather than here as simulator itself.
