### ISSUE TITLE
bug: uiautomator2 locale capability docs confusion

### ISSUE THREAD

**Issue by HazzMan2409** [appium/appium#18904]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the docs for the uiautomator2 driver the locale capability is [specified as](https://github.com/appium/appium-uiautomator2-driver#app-localization):

_"Sets the locale for the app under test. See https://developer.android.com/reference/java/util/Locale.html for more details. If locale is provided then language is also required to be set. The combination of both capability values must be a known locale and should be present in the list of available locales returned by the ICU's [getAvailableULocales()](https://unicode-org.github.io/icu/userguide/locale/#usage-retrieving-locales) method. The full list of supported locales is also dumped into the logcat output on failure. Example: EN, JA"_

It states that the value should be the locale and gives an example of EN or JA which are ISO 639-2 language codes. And it states that this should combine with the appium:language (another ISO 639-2 language code) to give a known locale. How would a value of en_EN give a known locale?

I am assuming that the value actually corresponds to the country (region) section of an [Android locale object](https://developer.android.com/reference/java/util/Locale).

This got me a little confused so I assumed it is a bug in the docs. If not, please dispel my confusion and I'll close the issue. 

### Expected Behavior

N/A

### Minimal Reproducible Example

n/A

### Environment

N/A

**Comment by KazuCocoa** [comment]
Thanks, that was probably old copy&paste issue in the docs. It should be US, JP etc for the `appium:locale`. I'll update them
