### ISSUE TITLE
[Feat]:Fast Forwarding/REWIND video On APPLE TV DEVICES

### ISSUE THREAD

**Issue by rENAntony** [appium/appium#18900]
Currently for apple tv automation using xcuitest driver, its not able to fastforward a video to the end easily...

In automation, we are currently using the logic of pressing the right button on apple tv remote with some interval gap, which will seek the video to 10sec.... Its lot more time consuming...also not accurate sometimes video will automatically rewind to previous position...

The problem is,...
1. We are not able to use swipe by coordinate(which will move the focus to targeted position in apple tv progress bar)
2. Since this is not mobile native, we cannot use touchaction class methods for fastforwarding....

NOTE:
WE CAN FAST FORWARD VIDEO IN APPLE TV USING 3 WAYS.

1.Use the 10-second Rewind and Fast-Forward buttons. (slow)
2.Tap and hold on the left/right side of the touchpad area on remote app. (medium)
3.Pause playback and drag your finger left/right over the touchpad area on remote app. (fast)
You can pause playback by using the play/pause button or by tapping the touchpad area on remote app.

As mentioned for automation we are using the method 1.its really difficult to automate player related cases because of this issue... 

So the point is..
Using appium 2.can we automate the method 2 or 3 which i mentioned above in apple TV..Can anyone help me on this...

**Comment by rENAntony** [comment]
@KazuCocoa it would be very helpful if you could help us on this🙂

**Comment by Higgens75** [comment]
Have you tried actionChains instead of touchActions? Maybe it works better in your scenario

https://appium.readthedocs.io/en/latest/en/commands/interactions/actions/

**Comment by KazuCocoa** [comment]
Do you know that how to achieve it using XCTest framework?


Afaik, Apple provides https://developer.apple.com/design/human-interface-guidelines/remotes 's button action via https://developer.apple.com/documentation/xctest/xcuidevice/1619052-pressbutton (WDA's code https://github.com/appium/WebDriverAgent/blob/c204c73081ed210399427917ab43056c07f6f491/WebDriverAgentLib/Categories/XCUIDevice+FBHelpers.m#L291) but I have no idea if it can do gesture actions. Perhaps still tvOS does not provide coordinate related actions. (e.g https://developer.apple.com/documentation/xctest/xcuielement/1618668-swipeleft may not work for tvOS)
It is appreciated to share findings if you find something to do actions.

**Comment by mykola-mokhnach** [comment]
@KazuCocoa What would you like to improve there? I assume we have everything available in WDA that XCTest provides to us. Linking https://alexilyenko.github.io/apple-tv-automated-tests/ for the reference

**Comment by KazuCocoa** [comment]
i was curious about something new thing was available since last my investigation. But maybe not new thing like gesture availability yet
