### ISSUE TITLE
[Feat]: Appium 2 documentation is properly documented as appium 1 was documented

### ISSUE THREAD

**Issue by abubakarafzal** [appium/appium#18908]
**Appium 2 should have the proper docuemntation for the command it supports.**
Need to add the appium 2 api calls like it has been added before with the snippets the way it was documented before

**Comment by abubakarafzal** [comment]
For example like this in appium 1.x

https://appium.github.io/appium.io/docs/en/commands/device/interactions/shake/

**Comment by abubakarafzal** [comment]
Its very hard to use appium 2 as appium 1 was well documented and easier to go but now with the migration to appium 2. It has been difficult which command is deprecated and what are the list of commands we can use

**Comment by jlipps** [comment]
@abubakarafzal command documentation has been moved to each driver. whether drivers include snippets will be up to each driver author.

**Comment by jlipps** [comment]
a major problem with appium 1 documentation was that it required huge manual effort to stay in sync. with appium 2 command documentation is generated from the code itself. so it will always be accurate. see the [xcuitest docs](https://appium.github.io/appium-xcuitest-driver) for example.
