### ISSUE TITLE
Setlocation is not working properly in Appium 2

### ISSUE THREAD

**Issue by Jayarams99** [appium/appium#18913]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we setlocation using the location keeps switching back to the current device location and the mocked location set using appium . This is observed on Google Maps also.

### Expected Behavior

Setlocation should set the mocked location through the appium session

### Minimal Reproducible Example

driver.setLocation ( new Location (22,11,1)):

### Environment

- Operating system: mac
- Appium server version (output of `appium --version`):2.0.1
- Appium driver(s) and their version(s):uiAutomator 9.3.16
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):20.5.0
- `npm` version (output of `npm --version`):9.8.0
- Last component(s) version which did _not_ exhibit the problem:1.18.0
- Platform and version under test: Android 12 and Android 13
- Real device or emulator/simulator: Real device

**Comment by jlipps** [comment]
Please link to a gist of your full appium logs

**Comment by Jayarams99** [comment]
Here is the logs:
https://gist.github.com/Jayarams99/091490a0d2868d28904fbd46715411e3

**Comment by Jayarams99** [comment]
getlocation before changing the location:

![image](https://github.com/appium/appium/assets/31212963/629d06f7-ea5f-4e2a-97c8-4457d1058410)

Setgeolocation

![image](https://github.com/appium/appium/assets/31212963/9f04ecf2-085f-43ff-bee9-a64456c726ca)

Setgeolocation result:

![image](https://github.com/appium/appium/assets/31212963/9b88e793-42a9-43ba-90ee-b9fdd8bc5c04)

**Comment by Dor-bl** [comment]
I think that also GetLocation don't work
https://gist.github.com/Dor-bl/ccce5c261558c1352b3e5a48f100cb3a

**Comment by mykola-mokhnach** [comment]
the actual location might not be reflected immediately by the OS. Try the https://github.com/appium/appium-uiautomator2-driver#mobile-refreshgpscache extension as a possible workaround

**Comment by mykola-mokhnach** [comment]
Also it makes sense to check the device logcat output for more details

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot help more without the information requested above
You may also play directly with the appium settings app to debug your issue as described in its readme: https://github.com/appium/io.appium.settings#retrieval-of-system-settings
