### ISSUE TITLE
bug: <title> when I am run the testcase in real device I am getting this error

### ISSUE THREAD

**Issue by iampavan222** [appium/appium#18919]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Failed to create session. An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 5000ms

### Expected Behavior

Expected Result is just start the session 

### ### ### ### 
 Real device or emulator/simulator: When I am run the test script in real devices i am getting that error
### ### ### ### ### ### 

Failed to create session. An unknown server-side error occurred while processing the command. Original error: Appium Settings app is not running after 5000ms

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
Please attach the full appium log

**Comment by bijitbiswas** [comment]
Hi @iampavan222 you can download the appium-settings app manually from  here https://github.com/appium/io.appium.settings on your mobile and try

**Comment by mykola-mokhnach** [comment]
Closed because of no response
