### ISSUE TITLE
Is there any way to modify/create appium config files to lower de default value of 10000ms to this setting waitForIdleTimeout?

### ISSUE THREAD

**Issue by andrewem244** [appium/appium#18926]
I spoken with 4 AI in the last 8 hours and searched all over the internet

If anyone could help me what file should i modify to lower that ms value. I'm not good at coding but i understand some basics.. or what should i do so that all my future Appium sessions to have a lower ms value. I'm thinking to put it 1000ms.

My appium version is 2.0.1

Appreciate any info i could get

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.
