### ISSUE TITLE
Appium crashed when page is having huge dom structure on ios native application 

### ISSUE THREAD

**Issue by bijitbiswas** [appium/appium#18921]
When trying to inspect or load page having a huge dom structure the appium is crashing. The page has more than 40k XCUIElementTypeCell in scrollable view and inside it few XCUIElementTypeText. Is there a way that I can stop appium from identifying elements or like just load page till the part its visible. Please urgently needed help

**Comment by mykola-mokhnach** [comment]
Please fill out the information requested in the issue reporting template.

Have you tried to fetch the page source using vanilla XCTest? If the native approach fails then there is no way WDA would work.

**Comment by bijitbiswas** [comment]
Created as per issue template https://github.com/appium/appium/issues/18925
