### ISSUE TITLE
Issue with appium installation

### ISSUE THREAD

**Issue by Annjames1** [appium/appium#18927]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently facing issues in automation setup for tvOS

tvOS version -15.6
xcode -14.0.1
macOS version -ventura 13.2.1

So i have installed node by giving the following command
brew install node
and current version is v20.5.0
after installing node ,i installed appium 2 by using command 
npm install -g appium@2.0.0-beta.46 and along with that installed other drivers and plugins

now after installation of the appium i am not able to see .appium folder in the default location,where as while giving the command in terminal it is showing as 
<img width="558" alt="Screenshot 2023-07-31 at 4 51 57 PM" src="https://github.com/appium/appium/assets/94349457/d2aab320-0152-44c3-b4c9-b6cf4dae712d">

here while refering to the document reference(https://appium.io/docs/en/2.0/guides/migrating-1-to-2/) once the appium is installed the .appium folder must be visible in the following path 
.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent

Attaching the screenshot from my machine
<img width="679" alt="Screenshot 2023-07-31 at 4 46 15 PM" src="https://github.com/appium/appium/assets/94349457/d210b530-53ce-484f-855b-d244e5ce4f0c">

not sure what is the exact reason of .appium folder missing there ,because of this not able to build the webdriveragent project from xcode ,which blocks us from automation.

### Expected Behavior

The expected behavior is that the .appium folder must be present in the default loaction and should be able to build the project.

### Minimal Reproducible Example

<img width="817" alt="Screenshot 2023-07-31 at 5 14 52 PM" src="https://github.com/appium/appium/assets/94349457/91e4ac11-3aef-4495-b8e1-7a15e1325bc9">

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
- Do you have APPIUM_HOME environment variable set to a custom path?
- How did you install drivers and plugins? What is the output of the list command?
- Appium 2 is out of beta as of now. Make sure you run the most recent server version.

**Comment by Annjames1** [comment]
Hi @mykola-mokhnach i used the following command
appium driver install xcuitest
appium plugin install relaxed-caps

and i am not sure on how to set APPIUM_HOME path

**Comment by mykola-mokhnach** [comment]
Try to run `appium driver list --verbose` to see exact paths where drivers are installed

**Comment by mykola-mokhnach** [comment]
`env | grep APPIUM_HOME` should show the actual value of the env variable if it is set

**Comment by Annjames1** [comment]
i tried by installing the normal command npm install -g appium, still facing the same issue,
but i see the drivers getting installed in different path which is not inside the .appium

<img width="934" alt="Screenshot 2023-07-31 at 7 13 01 PM" src="https://github.com/appium/appium/assets/94349457/0a15989a-c912-4b87-b551-ff5f77475a9f">
<img width="563" alt="Screenshot 2023-07-31 at 7 10 39 PM" src="https://github.com/appium/appium/assets/94349457/9896e1c6-2b0f-4e9f-88a9-ef3a1596ed7e">

<img width="563" alt="Screenshot 2023-07-31 at 7 15 16 PM" src="https://github.com/appium/appium/assets/94349457/5641c830-4fcf-4288-875e-d034fc34e3ec">

**Comment by mykola-mokhnach** [comment]
Make sure you don't have `package.json` file present in the current folder from whereto command for driver installation is being triggered. The server then assumes it is in dev mode, which should not be the case for you.
