### ISSUE TITLE
bug: 'appium-uiautomator2-server-v5.12.1.apk' does not exist or is not accessible

### ISSUE THREAD

**Issue by Dor-bl** [appium/appium#18933]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After I updated [appium-uiautomator2-driver](https://github.com/appium/appium-uiautomator2-driver) to the latest version and then did an update for appium from [beta57 ](https://github.com/appium/appium/compare/appium@2.0.0-beta.56...appium@2.0.0-beta.57)to [2.1.0](https://github.com/appium/appium/compare/appium@2.0.0...appium@2.0.1)
I encounter this issue when trying to start a new driver:
`node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v5.12.1.apk' does not exist or is not accessible`

I've checked and a file does exist in that path, but the version there is appium-uiautomator2-server-v5.12.2

I've also tried to re-install appium-uiautomator2-driver , but didn't helped as well
Maybe I need to clean some cache? 

### Expected Behavior

The driver should initialize properly as in previous versions 

### Minimal Reproducible Example

Running https://github.com/appium/python-client/blob/master/test/functional/android/applications_tests.py will fail for me in the current setup

### Environment

- Operating system: Win10
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s): Driver uiautomator2@2.29.3
- Appium plugin(s) and their version(s): none
- Node.js version (output of `node --version`): v16.18.0
- `npm` version (output of `npm --version`): 8.19.2
- Last component(s) version which did _not_ exhibit the problem:  appium@2.0.0-beta.57 + appium-uiautomator2-driver v2.29.1
- Platform and version under test: android 13
- Real device or emulator/simulator: emulator
 

### Link to Appium Logs

https://gist.github.com/Dor-bl/3ac680d9b7c0ee4c15fe47fc9f091cac

**Comment by mykola-mokhnach** [comment]
The server version is read from the package index: https://github.com/appium/appium-uiautomator2-server/blob/master/index.js

It could be that something got cached inside of the NPM. Try to delete the driver clear/reset the NPM cache and install it again.

**Comment by mykola-mokhnach** [comment]
https://www.javatpoint.com/npm-clear-cache

**Comment by mykola-mokhnach** [comment]
I really don't know why this is happening. You could maybe rename the corresponding apk as a possible workaround.

**Comment by mykola-mokhnach** [comment]
Closing this issue for now as it seems to be related to the particular local setup
