### ISSUE TITLE
bug: macOS and Windows have different results

### ISSUE THREAD

**Issue by NisStrom** [appium/appium#18942]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have Appium@2.0.1 with uiautomator2@2.29.3 running on macOS 12 Monterey and on a Windows 10 computer. Both use the following configuration:

```json
{
  "server": {
    "allow-cors": true,
    "allow-insecure": [],
    "base-path": "wd/hub",
    "log-level": "debug:debug"
  }
}
```

The sessions are being created from the Windows machine. Creating them on the macOS-System works perfectly. However, when trying the same 'locally' on the Windows machine itself, the Webdriver Session cannot be started with the following error message: `Error: SessionNotCreatedError: A new session could not be created. Details: Session capabilities format must comply to the W3C standard. Make sure your client is up to date. See https://www.w3.org/TR/webdriver/#new-session for more details.`

Because we use the exact same versions of Appium (and node) on both machines, we would expect the session creation to function on both machines. When analyzing this issue further, we discovered a difference:

#### Original request body

```json
{
  "desiredCapabilities": {
    "browserName":"",
    "platformName":"Android",
    "count":1,
    "goog:chromeOptions":{...},
    "appium:options":{
    "platformVersion":"12",
    ... },
  ... }
}
```

#### Received on the windows machine (exactly the same)

```json
{
  "desiredCapabilities": {
    "browserName":"",
    "platformName":"Android",
    "count":1,
    "goog:chromeOptions":{...},
    "appium:options":{
    "platformVersion":"12",
    ... },
  ... }
}
```

#### Received on the macOS computer (notice the capabilities with firstMatch)
```json
{
  "desiredCapabilities": {
    "browserName":"",
    "platformName":"Android",
    "count":1,
    "goog:chromeOptions":{...},
    "appium:options":{
    "platformVersion":"12",
    ... },
  ... },
  "capabilities": {
    "firstMatch": {
        "browserName":"",
        "platformName":"Android",
        "count":1,
        "goog:chromeOptions":{...},
        "appium:options":{
        "platformVersion":"12",
        ... },
      ... }
    }
}
```

Appium doesn't show the entire request, so there is maybe also an `alwaysMatch` Object inside `capabilities` with the same contents.

### Expected Behavior

The session can be created on the Windows 10 machine.

### Minimal Reproducible Example

Run Appium on Windows 10 and macOS 12, use Postman (or any other tool) to POST to the Windows 10 and macOS's Appium endpoint (/wd/hub/session). Use the "Original request body" from above.

### Environment

- Operating system: Windows 10 / macOS 12
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s):  uiautomator2@2.29.3
- Appium plugin(s) and their version(s): none
- Node.js version (output of `node --version`): 18.16.0
- `npm` version (output of `npm --version`): 9.8.1
- Last component(s) version which did _not_ exhibit the problem: Appium 1
- Platform and version under test:
- Real device or emulator/simulator: using real devices, always plugged in directly to the computers.

### Link to Appium Logs

https://gist.github.com/NisStrom/2aafa4d5201a13c0a6da369d00354ce1

**Comment by mykola-mokhnach** [comment]
Not sure what this has to do with the server. Capabilities JSON is sent by your client, so you it gets exactly what's provided

**Comment by NisStrom** [comment]
@mykola-mokhnach Thanks for your quick answer!
That's exactly the point, on macOS, what it receives does NOT match what I sent, which is a good thing, because it works on macOS.

**Comment by NisStrom** [comment]
@mykola-mokhnach Please look at the received json above. They are different, even though the sent json (top-most) ist the same.

**Comment by mykola-mokhnach** [comment]
These are not really helpful without the log. Eventually it is not clear to me what you want to achieve there. Simply send the capabilities in W3C-compatible format to get things running.

**Comment by NisStrom** [comment]
@mykola-mokhnach We cannot change the format the capabilities get sent in, because they get sent by the Protractor tests we execute. Also both machines receive the same non-W3C-compatible input, but on macOS Appium somehow manages to correct it. How can I get that same behaviour on Windows?

**Comment by mykola-mokhnach** [comment]
I don't know. It actually shouldn't as Appium 2 must only understand W3C.
Consider either downgrading the server (which is anyway ill-advised) or changing/upgrading the client.

**Comment by NisStrom** [comment]
@mykola-mokhnach 
> It actually shouldn't as Appium 2 must only understand W3C.

Alright, this is a valid bug report then? Because on macOS it works without valid W3C. And we actually like that 'feature'..

> Consider either downgrading the server

That does not work, because of the new url Chrome 115+ uses [to distribute the chromedriver](https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE)

> or changing/upgrading the client.

This isn't a possibility either, because we are (for now) still using Protractor to execute our tests. It however will not get any updates anymore.

**Comment by KazuCocoa** [comment]
You can use older Appium with v115 as https://github.com/appium/appium/issues/18897#issue-1815162934 's description's workaround, btw.

**Comment by jlipps** [comment]
did you try activating the relaxed-caps plugin?

**Comment by NisStrom** [comment]
@jlipps Yes we did try that, sadly, this leads to another error, most likely for the same reason:

```
[AppiumDriver@48df] Plugins which can handle cmd 'createSession': relaxed-caps
[AppiumDriver@48df] Plugin relaxed-caps is now handling cmd 'createSession'
[AppiumDriver@48df] Command 'createSession' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["relaxed-caps"].
[debug] [AppiumDriver@48df] Encountered internal error running command: TypeError: Cannot read properties of undefined (reading 'firstMatch')
[debug] [AppiumDriver@48df]     at RelaxedCapsPlugin.createSession ([redacted]\.appium\node_modules\@appium\relaxed-caps-plugin\lib\plugin.js:52:24)
```

**Comment by jlipps** [comment]
Ah yes, this plugin only allows relaxing the rule around capability prefixes. The capabilities object overall must still be W3C compatible. I think the only path forward will be an upgrade at this point! Unfortunately Protractor is pretty ancient :-/

**Comment by mykola-mokhnach** [comment]
Closed as not an issue.
