### ISSUE TITLE
feat: How to install 2 versions of Appium?

### ISSUE THREAD

**Issue by fatahillahardhi** [appium/appium#18945]
I am planning to migrate from Appium 1.22.3 to Appium 2, but currently, I am working on a project using Appium 1.22.3. While working on that project, I also want to set up Appium 2 on another branch.

At the moment, my global npm installation is using Appium 1.22.3. I tried to install Appium 2 using the local npm with command 
`npm install appium@next` (without global) but I faced issues with installing drivers and other dependencies.

Is there any solution for this? Thank you.

**Comment by mykola-mokhnach** [comment]
I would try to put both versions into different global repositories: https://stackoverflow.com/questions/14742553/how-to-set-custom-location-for-local-installation-of-npm-package

Although we have never been testing or planning such feature, it is expected that v1 is uninstalled before the v2 could be deployed. So I would be surprised if it works properly.

Please use Appium forum to ask questions.
