### ISSUE TITLE
Feature request: Support arch x86_64 in Simctl

### ISSUE THREAD

**Issue by tcobbs-bentley** [appium/appium#18966]
We have an app which uses a binary library that does not have an Apple Silicon Simulator build available. When testing on the command line, I determined that the following command can successfully launch an app on the Simulator in Rosetta 2 mode:

```sh
arch -arch x86_64 xcrun simctl launch --console --terminate-running-process ${SIM_DEVICE_ID} ${SIM_APP_ID}
```

I'd like to request an option in Simctl to have `xcrun` run under arch x86_64.

Note: nvm doesn't produce universal builds, so running an nvm version of node from inside an x86_64 shell results in an Apple Silicon process due to the node executable being arm64-only.

**Comment by mykola-mokhnach** [comment]
I somehow have a feeling that such feature may become obsolete quite fast.

Do you use simctl as a separate module?

**Comment by tcobbs-bentley** [comment]
> I somehow have a feeling that such feature may become obsolete quite fast.

I can see that, and I definitely respect that implementing this could have low long-term utility. Having said that, I don't really know if this is a trivial change or not, so I figured it couldn't hurt to request.

> Do you use simctl as a separate module?

We import simctl into a ts file that is run via npx.

**Comment by mykola-mokhnach** [comment]
Depending on how to actually implement it. There is always a choice. https://github.com/appium/node-simctl/pull/188 is fairly simple, but not sure this is exactly what you'd need

**Comment by tcobbs-bentley** [comment]
Thanks. Since I was already calling exec directly (to add `--console` and `--terminate-running-process`), this should make it trivial to just set `architecture: "x86_64"` in `opts`.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
