### ISSUE TITLE
[Feat]: Android - Add capability for ignore battery optimizations

### ISSUE THREAD

**Issue by ddello32** [appium/appium#18965]
**Is your feature request related to a problem? Please describe.**
Some apps require Ignore Battery Optimizations permission in Android, this permission follows a different flow as is not granted by autoGrantPermissions, instead we need to invoke ADB to add our tested app to deviceIdle whitelist.

**Describe the solution you'd like**
We should add a capability to UIAutomator2 drive to setup the installed apk to device idle whitelist (as it already does with the test server apk, and the settings manager).

**Describe alternatives you've considered**
Currently I'm manually calling:
```
        driver.executeScript("mobile: shell", mapOf(
            "command" to "dumpsys",
            "args" to listOf("deviceidle", "whitelist", "+my.package.name")
        ))
```
But this requires the relaxed-security flag.

**Comment by mykola-mokhnach** [comment]
the extension method has been added in the recent uia2 driver version: https://github.com/appium/appium-uiautomator2-driver#mobile-deviceidle
