### ISSUE TITLE
bug: Element position are offset in iPad in horizontal layout

### ISSUE THREAD

**Issue by Reeta-L** [appium/appium#18968]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to automate an internal app on iPad. I am using appium 2 and xcuitest driver 4.18.4. Using appium inspector the elements are highlighted offset. And tap by coordinates also does not work.
See below screenshot the settings button is not highlighted correctly.
![image](https://github.com/appium/appium/assets/141804385/f50cc140-cba6-463f-b900-0f1bc883b73a)
I even try on the home screen, and the buttons are highlighted incorrectly. I suppose there is a problem with landscape mode on iPad.

### Expected Behavior

The settings button should be highlighted correctly and tap by coordinates should also work.

### Minimal Reproducible Example

Steps: 
1. Connect iPad in landscape mode. 
2. Try to capture buttons on homescreen using appium inspector. 
3. The buttons are offset
![pic1](https://github.com/appium/appium/assets/141804385/2203c272-15d3-45b8-b8de-c7213cd0f356)

### Environment

- Operating system: Windows 10, macOS Monterery (12.5.1)
- Appium server version (output of `appium --version`): 2.0.0-beta.56
- Appium driver(s) and their version(s): xcuitest 4.18.4
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v19.6.0
- `npm` version (output of `npm --version`): 9.4.0
- Last component(s) version which did _not_ exhibit the problem: n/a
- Platform and version under test:  iPad 16.3.1
- Real device or emulator/simulator: Real device - iPad (10th generation)

### Futher Information

[appium3.log](https://github.com/appium/appium/files/12299816/appium3.log)
![Picture1](https://github.com/appium/appium/assets/141804385/f0712672-82eb-41a8-b46e-37a258425e9b)
![Picture2](https://github.com/appium/appium/assets/141804385/50e179fb-a2b2-45c5-a7e9-6bfef1e406b0)

**Comment by mykola-mokhnach** [comment]
Element coordinates are returned by XCTest and we cannot influence this logic. According to what I observed before it may returns portrait coordinates for elements in landscape because they are transformed implicitly in the framework internals afterwards.

Consider reporting the issue to Apple.

**Comment by eglitise** [comment]
This may also be a problem in the Inspector, not Appium. @Reeta-L can you try again with the latest Inspector version (2023.8.1)?
