### ISSUE TITLE
bug: Cannot install drivers when using workspace:* with yarn 3

### ISSUE THREAD

**Issue by rurikoaraki** [appium/appium#18978]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am working on a repository that recently converted to using yarn 3. I am trying to change the repository to use workspace:* for local package versions, but am running into issues with running appium after the change.

When I run `yarn appium driver install <driver name>` I get the following:

![image](https://github.com/appium/appium/assets/4602628/cc13bd46-64c5-4de7-9810-5e0b177b9a38)

I have tried other menthods such as:

- Installing appium globally and running `appium driver install <driver name>` instead
- Using the --github install method
- Tried using the local driver install method, but this fails in other ways (at least with the appium-windows-driver)

Based on what I see online it seems that there are issues with using npm to install packages in repos with workspace:* used to mark a dependency version. Since the command uses npm under the hood there doesn't seem to be a way to avoid this behavior. Is there a workaround?

### Expected Behavior

Able to install appium drivers via the driver install command

### Minimal Reproducible Example

PR with the change can be seen here:
https://github.com/microsoft/fluentui-react-native/pull/3025

As for a minimum repro you can probably set up a test project to use workspace:* for one of its dependencies and then try using appium. 

### Environment

- Operating system: Windows 11
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s):
    "appium-windows-driver": "2.9.2"
    "appium-mac2-driver": "1.6.3",
    "appium-uiautomator2-driver": "2.29.4",
    "appium-windows-driver": "2.9.2",
    "appium-xcuitest-driver": "4.33.2",
- Appium plugin(s) and their version(s): N/A
- Node.js version (output of `node --version`): v16.19.0
- `npm` version (output of `npm --version`): 8.19.3
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Windows 11
- Real device or emulator/simulator: Real device

### Further Information
[2023-08-11T20_24_19_396Z-debug-0.log](https://github.com/appium/appium/files/12324947/2023-08-11T20_24_19_396Z-debug-0.log)

**Comment by rurikoaraki** [comment]
Whoops, sent before fully filled out. More details coming

**Comment by rurikoaraki** [comment]
With more testing, installing appium globally and running it works but only if we don't declare appium as a devDependency. But not declaring it would be odd since we do use it for out e2e testing

**Comment by mykola-mokhnach** [comment]
Unfortunately we only support npm. yarn has never been officially supported or tested. 
Also the only officially supported way of adding drivers as submodules is described in https://appium.io/docs/en/2.0/guides/managing-exts/#using-appiums-extension-cli

You are welcome to create a PR which would add proper yarn support though.

**Comment by rurikoaraki** [comment]
Thanks @mykola-mokhnach. I probably won't have bandwidth to add yarn support at least in the immediate future, unfortunately. But I'll keep the option in mind.

**Comment by jlipps** [comment]
@rurikoaraki if you're using appium as a devDependency, just make the appium drivers you want also a devDependency. The Appium CLI is only for use with a globally installed Appium. The link @mykola-mokhnach shared includes more details about how to manage appium and dependencies as node deps if you're in a node project and want to keep everything in the project itself.
