### ISSUE TITLE
Connecting to Dart Observatory: undefined Check Dart Observatory URI no URI found in the device log

### ISSUE THREAD

**Issue by Rahul1970** [appium/appium#18976]
Hi Team i am working on mobile automation of flutter application using appium 2.0.1 eclipse java 8 Android studio Flamingo Flutter Version 3.7.12 while running my automation script i am getting the message "2023-08-10 11:54:49:925 [FlutterDriver] Connecting to Dart Observatory: undefined
2023-08-10 11:54:49:927 [FlutterDriver] {}
2023-08-10 11:54:49:927 [FlutterDriver] Check Dart Observatory URI no URI found in the device log  " 

The appium logs are mentioned here in this gist link for your reference :   https://gist.github.com/Rahul1970/7f6d18164de022c14bb5199a4950ce0c

**Comment by KazuCocoa** [comment]
Could you report it to https://github.com/appium-userland/appium-flutter-driver ?
