### ISSUE TITLE
bug: Could not load plugin 'universal-xml'

### ISSUE THREAD

**Issue by shibupanda** [appium/appium#18977]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

appium --use-plugins=universal-xml
WARN Appium Appium encountered 4 warnings while validating drivers found in manifest /Users/radmin/.appium/node_modules/.cache/appium/extensions.yaml
WARN Appium Driver "fake" has 1 potential problem: 
WARN Appium   - Driver "fake" (package `appium-fake-driver`) may be incompatible with the current version of Appium (v2.0.0) due to an invalid or missing peer dependency on Appium. Please ask the developer of `appium-fake-driver` to add a peer dependency on `^appium@2.0.0`.
[Appium] Attempting to load plugin universal-xml...
[debug] [Appium] Requiring plugin at /Users/radmin/.appium/node_modules/@appium/universal-xml-plugin
[Appium] Could not load plugin 'universal-xml', so it will not be available. Error in loading the plugin was: Could not find a class named "UniversalXMLPlugin" exported by plugin "universal-xml"
[debug] [Appium] ReferenceError: Could not find a class named "UniversalXMLPlugin" exported by plugin "universal-xml"
[debug] [Appium]     at PluginConfig.require (/usr/local/avm/versions/2.0.0/node_modules/appium/lib/extension/extension-config.js:580:13)
[debug] [Appium]     at /usr/local/avm/versions/2.0.0/node_modules/appium/lib/extension/index.js:52:46
[debug] [Appium]     at Array.map (<anonymous>)
[debug] [Appium]     at getActivePlugins (/usr/local/avm/versions/2.0.0/node_modules/appium/lib/extension/index.js:49:10)
[debug] [Appium]     at main (/usr/local/avm/versions/2.0.0/node_modules/appium/lib/main.js:378:41)
[Appium] Welcome to Appium v2.0.0
[Appium] Non-default server args:
[Appium] {
[Appium]   usePlugins: [
[Appium]     'universal-xml'
[Appium]   ]
[Appium] }

### Expected Behavior

It should activate like other plugins example images, relaxed-caps etc

### Minimal Reproducible Example

Start appium v2.0.0 with universal-xml latest plugin

### Environment

- Operating system: Mac
- Appium server version (output of `appium --version`): v2.0.0
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s): v1.0.9
- Node.js version (output of `node --version`): v16.20.0
- `npm` version (output of `npm --version`): v8.19.4
- Last component(s) version which did _not_ exhibit the problem: I tried it for the first time
- Platform and version under test:
- Real device or emulator/simulator: Real device

**Comment by KazuCocoa** [comment]
Any idea? @jlipps 
(i haven't checked well yet tho)
