### ISSUE TITLE
bug: Original error: Unable to parse cpu usage data

### ISSUE THREAD

**Issue by Dor-bl** [appium/appium#18973]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I try to GetPerformanceData I encounter this issue:

`Original error: Unable to parse cpu usage data`

### Expected Behavior

GetPerformanceData will return the information of the system state which is supported to read e.g. cpu, memory, network
CpuInfo in this case.

### Minimal Reproducible Example

https://gist.github.com/Dor-bl/75afd2f402cd2a305a1db7fef1b310c2

### Environment

- Operating system: win 10
- Appium server version (output of `appium --version`):2.0.1
- Appium driver(s) and their version(s): uiautomator2@2.29.3 
- Appium plugin(s) and their version(s): none
- Node.js version (output of `node --version`): v16.18.0
- `npm` version (output of `npm --version`): 8.19.2
- Last component(s) version which did _not_ exhibit the problem: Unkown 
- Platform and version under test: Android 11
- Real device or emulator/simulator: emulator 

### Link to Appium Logs

https://gist.github.com/Dor-bl/d74f473c4b66f1ba001643b806bb1558

### Futher Information

dotnet client is passing `getPerformanceData` command , I also tried with `mobile: getPerformanceData` but same error
maybe related to the issue: https://github.com/appium/appium/issues/16074

**Comment by mykola-mokhnach** [comment]
I assume it is just somehow confusing error message. The actual problem is that there is no cpu info for the given process name in the above command output, so the error itself is expected.

**Comment by Dor-bl** [comment]
we had this integration test since 2020.
@laolubenson, maybe you recall something about it? 
was this running on a real device perhaps?

**Comment by Dor-bl** [comment]
@mykola-mokhnach If `getSuppportedPerformanceDataTypes` returns "cpuinfo" as one of the Types doesn't it mean it should work?

**Comment by mykola-mokhnach** [comment]
it works. Simply provide one of process names that exist in the actual cpuinfo output to check that.

**Comment by Dor-bl** [comment]
I see the `io.appium.android.apis` process in the `dumpsys cpuinfo`:
`+0% 29294/io.appium.android.apis: 0% user + 0% kernel`
But the appium server still fails to parse the cpu usage data

**Comment by Dor-bl** [comment]
I got the integration test pass with : `string packageName = "com.google.android.apps.docs";`
The question is if I should just change the packageName and move on.

**Comment by mykola-mokhnach** [comment]
> I see the `io.appium.android.apis` process in the `dumpsys cpuinfo`:
> `+0% 29294/io.appium.android.apis: 0% user + 0% kernel`
> But the appium server still fails to parse the cpu usage data

yes, although the requested process name is `com.google.android.apps.nexuslauncher`

**Comment by mykola-mokhnach** [comment]
> I got the integration test pass with : `string packageName = "com.google.android.apps.docs";`
> The question is if I should just change the packageName and move on.

I assume yes. You should select some process name, which is supposed to be preserved while changing Android OS version

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
