### ISSUE TITLE
bug: WindowsDriver fails to getScreenSize() when using images plugin

### ISSUE THREAD

**Issue by littlegeek01** [appium/appium#18988]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am connecting to appium windows driver using "appium:app":"Root" in my capabilities.  I am also using the images plugin.  When I do this and I try to findElement by image, an error is thrown:
```
[WindowsDriver@73b1 (90e0c3ef)] Cannot retrieve window size from WinAppDriver
[WindowsDriver@73b1 (90e0c3ef)] Falling back to Windows Forms to calculate dimensions
[AppiumDriver@49a0] Command 'findElement' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["images"].
[debug] [AppiumDriver@49a0] Restarting new command timeout via umbrella driver since plugin did not allow default handler to execute
[debug] [WindowsDriver@73b1 (90e0c3ef)] Encountered internal error running command: TypeError: Cannot read properties of undefined (reading 'execPowerShell')
```

### Expected Behavior

The element should be found.  I did some digging, and it looks like the call chain first tries to proxy to WinAppDriver to get the screen size, and if it can't get it from there, it attempts to execute a powershell command and parse that response.  I opened the node repl on my machine and created a new WindowsDriver object which I then used to call execPowershell() in powershell.js.  That worked great and I got the powershell response just fine, so I don't think there is a problem with my execution environment.  The stack trace I got from appium leads me to believe that in general.js, getScreenSize() where this command is executed: 
```
const dimensions = await this.execPowerShell({
    command: 'Add-Type -AssemblyName System.Windows.Forms;[System.Windows.Forms.Screen]::PrimaryScreen.Bounds.Size',
  });
```
this must be undefined and therefore execPowerShell cannot be called. 
I am not much of a javascript dev so I'm not sure why that would be the case or how to fix it, or if that is even the actual problem.

### Minimal Reproducible Example

```
public class AppiumWindowsTest
{
    public void doTheStuffs() throws Exception
    {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("app", "Root");
        capabilities.setPlatform(Platform.WINDOWS);
        //I just to a snapshot of my recycle bin for this test, you could use any icon on your desktop
        URL filterImageUrl = this.getClass().getClassLoader().getResource("RecycleBin.PNG");
        File filterImage = new File(filterImageUrl.toURI());
        String b64image = Base64.getEncoder().encodeToString(Files.readAllBytes(filterImage.toPath()));        
        WindowsDriver appiumDriver = null;
        try
        {
            appiumDriver = new WindowsDriver(new URL("http://127.0.0.1:4444"), capabilities);
            WebElement recycleBin = appiumDriver.findElement(AppiumBy.image(b64image));
            recycleBin.click();
            appiumDriver.addCommand(HttpMethod.POST, "/session/:sessionId/doubleclick", "doubleclick");
            appiumDriver.execute("doubleclick");
            Thread.sleep(5000);
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        finally
        {
            if(appiumDriver != null)
            {
                appiumDriver.closeApp();
            }
        }
    }
    
    public static void main(String[] args) throws Exception
    {
        AppiumWindowsTest awt = new AppiumWindowsTest();
        awt.doTheStuffs();
    }
}
```

### Environment

- Operating system: Windows 10 Enterprise
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s):  windows@2.9.3 [installed (npm)]
- Appium plugin(s) and their version(s):  images@2.1.2 [installed (npm)]
- Node.js version (output of `node --version`): 18.17.1
- `npm` version (output of `npm --version`): 9.6.7
- Last component(s) version which did _not_ exhibit the problem: N/A
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

[appiumLog.txt](https://github.com/appium/appium/files/12348466/appiumLog.txt)

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-windows-driver/pull/189 should fix that

**Comment by mykola-mokhnach** [comment]
the patch has been published

**Comment by littlegeek01** [comment]
Verified.  Thanks for the quick turnaround!
