### ISSUE TITLE
Install appium on macOS13.3.1 get error bug: <title>

### ISSUE THREAD

**Issue by LittleSmart** [appium/appium#18980]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hi, I'm freshman on appium, i try to install appium on macOS13.3.1 with this command
`npm i --location=global appium`
but terminal shows following error:
<img width="780" alt="image" src="https://github.com/appium/appium/assets/13567785/a61ee396-b1b0-4630-80fd-179e2839eed0">

### Expected Behavior

install appium successfully on macOS13.3.1

### Minimal Reproducible Example

macOS: 13.3.1 
node:v18.17.0
npm: 9.6.7
python : 3.9.6

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Link to Appium Logs

https://gist.github.com/LittleSmart/2afb03b13fb9c647c9218ae803227013

**Comment by KazuCocoa** [comment]
Was your `nodejs`/`npm` installed as a root user?

**Comment by LittleSmart** [comment]
I just install node and npm with node-v18.17.1.pkg  download from https://nodejs.org/en

**Comment by LittleSmart** [comment]
> Was your `nodejs`/`npm` installed as a root user?
I just install node and npm with node-v18.17.1.pkg download from https://nodejs.org/en

**Comment by mykola-mokhnach** [comment]
Unfortunately this issue has nothing to do with Appium. Make sure your user has proper permissions on the folder where npm installs global dependencies or use a different prefix folder for your global installations.

Consider asking at NPM or Appium forum if you have further questions regarding the above.

Closed as not an issue.
