### ISSUE TITLE
[Feat]: Set appium-webdriveragent path using cli arguments 

### ISSUE THREAD

**Issue by krishtoautomate** [appium/appium#18982]
**Is your feature request related to a problem? Please describe.**
yes,latest webdriveragent donot support ios14 and less, so if a machine is connected with multiple devices of ios12, ios13, ios14 and so on. if only one appium-webdriveragent is available in system, random tests fail based on supported version. so adding cli argument as --wdaRepoPath will solve issues

**Describe the solution you'd like**
adding cli argument as appium --wdaRepoPath "PATH_TO_APPIUM_WEBDRIVERAGNET"  will solve issues to choose webdrivergent build folder

**Comment by mykola-mokhnach** [comment]
We do not plan on adding such arguments. There is a `bootstrapPath` session capability, which does the same thing already.

**Comment by krishtoautomate** [comment]
That is for already built from derived data path. Mapping build from derived data is not ideal as we cannot differentiate which is for what device version

**Comment by mykola-mokhnach** [comment]
> That is for already built from derived data path
not sure what you mean there. This capability sets a custom path to WDA root folder. It is not officially documented to avoid extra confusion between users as its possible usage scenarios are fairly advanced ones. Check https://github.com/appium/WebDriverAgent/blob/c204c73081ed210399427917ab43056c07f6f491/lib/webdriveragent.js#L119 for more details.

**Comment by KazuCocoa** [comment]
https://appium.github.io/appium-xcuitest-driver/4.33/run-prebuilt-wda/#how-to-use-appiumusexctestrunfile-and-appiumbootstrappath-capabilities also address it a bit

**Comment by krishtoautomate** [comment]
Got it. I ll test with both boothstrapPath and agentPath and see what will best fit for me. Thanks

**Comment by krishtoautomate** [comment]
With latest xcode15 this is not working as older releases are not compatible, failing with 65 error
