### ISSUE TITLE
[proposal]: transfer appium-flutter-driver repository into this org

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#18986]
I've maintained https://github.com/appium-userland/appium-flutter-driver for years alone, but Mykola could find time to help the repo's maintenance recently. (thanks so much). So currently two core Appium project members are working/could find time to work on the repository.

So, if we don't mind, i'd like to transfer the flutter driver repository into this repository to simplify the maintenance work.

The driver has "Flutter" context to communicate with the Dart VM directly, but other parts depend on UIA2/XCUITest. So the driver has `FLUTTER`, `NATIVE_APP` and `WEBVIEW` context in total. It allows users to switch contexts flexibly because the FLUTTER context cannot interact with NATIVE_APP area directly as outside the Dart VM area. It actually brings benefits for users that is not available only via Fluter's native testing tools. e.g. open XXX, then interact with the system elements like permission popup, then back to the Flutter layer and do something. 

The flutter driver's 'FLUTTER' context has a bit different syntax. For example, it does not provide regular `find_element :id, 'xxx'` as the structure. It needs to send one action at a time as base64 encoded one to the Dart VM to let the VM execute the command. 

e.g, get a text
```
const counterTextFinder = byValueKey('counter');
await driver.getElementText(counterTextFinder)

```

Thus, this appium-flutter-driver does not follow well as regular WebDriver commands in some cases. To achieve this, the driver provides client-side extension, called 'finder' as https://github.com/appium-userland/appium-flutter-driver/tree/main/finder . If we could move the repository into this appium repo, we can also merge such Finder into each client to support the flutter driver as top tier (if it's ok).

The result of page source is also currently returning not implemented yet since the Flutter returns a string source tree, available as `flutter:getRenderTree` as-is. The response format by Flutter requires us to part the string as xml, or something implementation would be required further. The `getRenderTree` is only for Flutter layer.

One technical concern is the driver itself is it depends on https://api.flutter.dev/flutter/flutter_driver/flutter_driver-library.html , which is provided by Flutter team officially although the library is probably not actively maintained by the team as they are guiding users to use integration_test instead https://docs.flutter.dev/testing/integration-tests , thus not sure how long can we keep maintaining the repository.

I wrote a few things about the flutter driver. What do you think about this...? @jlipps  @mykola-mokhnach @boneskull 
(or need more active members to mention?)

**Comment by mykola-mokhnach** [comment]
Like mentioned above I am ok about moving this driver into the Appium org. We should update its readme though and be explicit about the dependencies and their maintenance state (same we do for the Windows drivers)

**Comment by saikrishna321** [comment]
@KazuCocoa >>the team as they are guiding users to use integration_test instead https://docs.flutter.dev/testing/integration-tests , thus not sure how long can we keep maintaining the repository.

Does it make sense for us to make the move to integration-tests at this time when moving inside the org?

**Comment by KazuCocoa** [comment]
Not sure. It needs investigation. I haven't had much time to focus on the integration_test module. Maybe no one spent much time on it (at least no one contributed to the rep, afaik). Maybe the driver can involve methods in the integration_test module as same but maybe they will be additional commands rather than flutter_driver's replacement as the appium-flutter-driver.

Their official documentation still addresses flutter_driver in espresso integration for example, so probably they are still not a complete "replacement". https://docs.flutter.dev/release/breaking-changes/plugin-api-migration
The integration_test is closer to the Widge test, so it is more kind of white box testing side rather than black box testing (grey box, but more white side), looks like.

Personally, basically, users should add `semanticLabel` and `hintText` to make elements accessible via UIA2/XCUITest is preferred as black box testing so that they can run tests against release modules as well (Note that this appium-flutter-driver cannot test release modules). Flutter v3 has enhanced the way.
(it means users also should take care of accessibility functionality in their apps)

Thus, for the driver, probably it can append new command calls that sends integration_test module but it might be additional commands, not a replacement.


If we can spend time on the driver, probably we could try [adding Web capability (Flutter web)](https://github.com/appium-userland/appium-flutter-driver/issues/263).

**Comment by mykola-mokhnach** [comment]
@jlipps Any thoughts?

**Comment by jlipps** [comment]
Sure I'm OK to move it in so long as we note that it's not super robustly supported!

**Comment by KazuCocoa** [comment]
Thanks, let me do a couple of cleanups in the repo. then I'll transfer the repository. After moving the repo into this appium org, I'll close this issue

**Comment by KazuCocoa** [comment]
Transdered to: https://github.com/appium/appium-flutter-driver

I have updated a few in the readme.
I'll check npm side as well later
