### ISSUE TITLE
bug: Mobile Script scrollToElement is throwing false InvalidElementStateException iOS

### ISSUE THREAD

**Issue by cdubwisdom** [appium/appium#18984]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The mobile script "scrollToElement" is throwing a InvalidElementStateException even though the script is running successfully and does scroll the iOS app page element into view and is intractable.

### Expected Behavior

When calling the mobile script "scrollToElement" Appium should scroll the iOS app page until the given element is visible.
Element then should be intractable.

### Minimal Reproducible Example

```java
public void scrollElementIntoView(WebElement element){
    driver.executeScript("mobile: scrollToElement", ImmutableMap.of("element", ((RemoteWebElement) element).getId()));
}
```

### Environment

- Operating system: macOS 13.5
- Appium server version (output of `appium --version`): 2.0.0-beta.57
- Appium driver(s) and their version(s): xcuitest@4.27.0
- Appium plugin(s) and their version(s): relaxed-caps@1.0.5
- Node.js version (output of `node --version`): v20.5.0
- `npm` version (output of `npm --version`): 9.8.0
- Last component(s) version which did _not_ exhibit the problem: Unknown
- Platform and version under test: iPhone X iOS 16.6
- Real device or emulator/simulator: Real Device

### Link to Appium Logs

[Appium Log](https://gist.github.com/cdubwisdom/84fe696ee21c4fa389ab057555cbeeb7)

### Further Information

Currently I am wrapping the script in a try-catch block as a work around

```java
public void scrollElementIntoView(WebElement element){
    try{
        driver.executeScript("mobile: scrollToElement", ImmutableMap.of("element", ((RemoteWebElement) element).getId()));
    }
    catch(InvalidElementStateException e){
        //do nothing
    }
}
```

**Comment by jlipps** [comment]
Looks like the element went away or something. I'm not sure there's anything Appium can do about it. XCUITest itself is the one that complained about not being able to find a hitpoint for the element.

**Comment by cdubwisdom** [comment]
I can see the element is visible on the screen and if I tell my code to ignore the exception it proceeds to interact with it no problem

**Comment by jlipps** [comment]
I dunno. Maybe @mykola-mokhnach has an idea? In this case it seems like the workaround you've found is the best way to approach it.

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot influence this logic. This method is a thin wrapper over XCTest's  `_hitPointByAttemptingToScrollToVisibleSnapshot:error:` API call, so only Apple could change that.
