### ISSUE TITLE
Appium can only obtain native apps when obtaining contexts

### ISSUE THREAD

**Issue by yanyun212** [appium/appium#18987]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can debug and view the webview in the app on the Safari browser on the Mac side, but when I automatically run get contexts, I can only obtain the native app， I have already opened the web inspector of the Safari browser on my phone

### Expected Behavior

I want to know how to obtain the webview parameters in the app and switch between them

### Minimal Reproducible Example

无

### Environment

- Operating system:
- Appium server version (output of `appium --version`):v2.0.0-rc.5
- Appium driver(s) and their version(s):xcuitest@4.32.11
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):v18.16.1
- `npm` version (output of `npm --version`):9.5.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:16.0
- Real device or emulator/simulator:iphone 12promax

### Further Information

[appium_ios.log](https://github.com/appium/appium/files/12342330/appium_ios.log)

**Comment by mykola-mokhnach** [comment]
According to the attached log the context switch did succeed. What particular line there does not work as expected?

**Comment by yanyun212** [comment]
Responding to client with driver.getContexts() result: ["NATIVE_APP"],I cannot return webview_xxx by getting contexts in the app, I want to know if the iOS package needs it

**Comment by mykola-mokhnach** [comment]
Which line of the log it is?

**Comment by yanyun212** [comment]
![屏幕截图 2023-08-16 143455](https://github.com/appium/appium/assets/50688134/64bc826b-0013-4ff3-bf66-b541702f5888)

**Comment by mykola-mokhnach** [comment]
I assume this is expected. Web contexts needs some time for initialization, so the next request to getContexts after this one did return the proper one.

**Comment by yanyun212** [comment]
So do I need to add sleep wait before getting contexts

**Comment by KazuCocoa** [comment]
What about calling getting cntexts a few times, or trying out https://appium.github.io/appium-xcuitest-driver/4.33/execute-methods/#mobile-getcontexts?

**Comment by yanyun212** [comment]
Thank you, I will give it a try

**Comment by yanyun212** [comment]
At the beginning, I iterated to obtain contexts, and the third time I obtained the webview I needed; Later, I added webviewConnectTimeout=${5000} to the startup parameters to obtain the webview I need without loop retrieval
