### ISSUE TITLE
bug: Call to 'switchContext' failed

### ISSUE THREAD

**Issue by Vijayadhas** [appium/appium#18990]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using Appium inspector to find the element path/id/xpath for testing. I am testing hybrid android app. So I try to switch to webview from the dropdown. But I am not able to switch to webview. I am getting following issue. ```
Call to 'switchContext' failed
An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '115.0.5790'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details
```

I tried `appium --default-capabilities '{\"appium:chromedriverExecutable\": \"D:\\Projects\\chrome driver\\chromedriver.exe\"}'`

`appium --allow-insecure chromedriver_autodownload`

But still issue is happaning. Please help me on this. I want to get the element path/id/xpath from the webview.


### Expected Behavior

Can able to switch between the `NATIVE_APP` and `WEBVIEW_com.sam.tes`

### Minimal Reproducible Example

```
<img width="523" alt="222" src="https://github.com/appium/appium/assets/8545184/5734fe80-2fea-4e03-8fef-a94de2063daf">
```


```
{
  "platformName": "android",
  "appium:platformVersion": 13,
  "appium:deviceName": "c6c470e4",
  "appium:AppPackage": "com.sam.tes",
  "appium:AppActivity": "com.sam.tes.MainActivity",
  "appium:autoGrantPermissions": true,
  "appium:ignoreHiddenApiPolicyError": true,
  "appium:noReset": true,
  "appium:automationName": "UiAutomator2",
  "appium:chromedriverExecutable": "D:\\Projects\\chrome driver\\chromedriver.exe"
}
```

### Environment

- Operating system:
- Appium server version : 2.0.1
- Appium driver(s) and their version(s): -  chromium@1.1.42, uiautomator2@2.29.4
- Appium plugin(s) and their version(s): - 
- Node.js version : v18.17.1
- `npm` version : 9.6.7
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Android 13
- Real device or emulator/simulator: Real device


### Link to Appium Logs

_No response_

### Further Information

_No response_

**Comment by KazuCocoa** [comment]
Related to https://github.com/appium/appium/issues/18897 
Perhaps your `"appium:chromedriverExecutable": "D:\\Projects\\chrome driver\\chromedriver.exe"` was not for the chrome v115. Please download proper chromedriver version

**Comment by Vijayadhas** [comment]
Hi @KazuCocoa  I attached the log. Yes you are correct. Version mismatch. But I not able to find 115 version chrome driver.

[Chromedriver] The following Chromedriver executables were found:
[Chromedriver] 'C:/Users/Vijay/AppData/Local/Programs/Appium Server GUI/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/win/chromedriver_win32_v114.0.5735.90.exe' (version '114.0.5735.90', minimum Chrome version '114')
[Chromedriver] 'C:/Users/Vijay/AppData/Local/Programs/Appium Server GUI/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/win/chromedriver_win32_v114.0.5735.16.exe' (version '114.0.5735.16', minimum Chrome version '114')
[Chromedriver] Browser version in the supplied details: Chrome/115.0.5790.166
[Chromedriver] Found Chrome bundle 'undefined' version '115.0.5790'
[Chromedriver] Error: No Chromedriver found that can automate Chrome '115.0.5790'. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/chromedriver.md for more details



I tried 
`npm install chromedriver --chromedriver_cdnurl=https://npmmirror.com/metadata --chromedriver_cdnbinariesurl=https://npmmirror.com/binaries`

added 14 packages, and audited 2138 packages in 7s

50 packages are looking for funding
  run `npm fund` for details

13 vulnerabilities (10 moderate, 3 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

But still I am getting the same issue. Where I can find the downloaded chrome driver??

**Comment by mykola-mokhnach** [comment]
Automated chromedriver download for v115+ won't work if you use Appium 1. Consider using the most recent driver version supplied with Appium 2.

**Comment by mykola-mokhnach** [comment]
Please provide the complete server log.

**Comment by mykola-mokhnach** [comment]
From the log above it looks like the driver being used is a very old one

**Comment by Vijayadhas** [comment]
Yes. Now update the Appium server to latest. Now Appium inspector is working fine. Now I am able to switch to WEBVIEW and NATIVE. Able to locate the elements. But when I try by selenium code, I am facing the following issue. 
https://stackoverflow.com/questions/76919145/org-openqa-selenium-invalidargumentexception-invalid-argument-invalid-locator
Can you help me on this?

**Comment by jlipps** [comment]
Please submit a new appium log

**Comment by KazuCocoa** [comment]
Correct, we no longer maintain appium v1
