### ISSUE TITLE
Fix grant location permission on ios

### ISSUE THREAD

**Issue by fleytman** [appium/appium#18991]
Currently, there are two methods for providing permissions, both of which are experiencing challenges:

* Capability: autoAcceptAlert - There is a known issue with this capability, as reported in [this GitHub issue](https://github.com/appium/WebDriverAgent/issues/730).
* Capability: permissions - Another challenge arises with this capability, as detailed in [this GitHub issue](https://github.com/wix/AppleSimulatorUtils/issues/111). Unfortunately, the issue with the "wix" repository has been unresponsive since December 2022.

Ironically, both of these issues pertain to granting location access. In light of these challenges, I would like to propose the following steps:

1. Fix the Issue: Address the bug related to [GitHub issue 730](https://github.com/appium/WebDriverAgent/issues/730) to ensure proper functionality of the autoAcceptAlert capability.
2. Explore Workaround: Attempt to work around the issue documented in [GitHub issue 111](https://github.com/wix/AppleSimulatorUtils/issues/111). It's worth noting that the bug seems to be specific to AppleSimulatorUtils and not reproducible with simctl and idb. Considering this, it could be reasonable to default to simctl for most cases, except for permissions that require AppleSimulatorUtils, such as userTracking and notifications.

Your insights and contributions in addressing these challenges would be greatly appreciated. Thank you for your time and consideration.

**Comment by fleytman** [comment]
Additionally, I haven't figured out if there's a way I can use the Appium java-client to send a simctl or idb command in code to grant the required permission until the issue is fixed.

**Comment by jlipps** [comment]
I added a comment to #730. I'm not sure there's anything that can / should be fixed there.

**Comment by jlipps** [comment]
As for exploring workarounds, I'll leave it to one of the xcuitest maintainers to comment, but it sounds like a good idea to me.

**Comment by fleytman** [comment]
Еще одна проблема, на которую я хотел бы обратить внимание, - это отсутствие ясности относительно того, существует ли способ использования Appium java-client для выполнения команд simctl или idb напрямую из кода. Этот подход, возможно, мог бы предоставить обходное решение для решения текущих проблем путем непосредственного взаимодействия с simctl или idb и мог бы служить промежуточным решением в ожидании устранения существующих проблем.

**Comment by fleytman** [comment]
It is possible to execute idb commands in appium tests - https://github.com/SergKhram/IdbClient

But I would like a general solution from the Appium team

**Comment by KazuCocoa** [comment]
Perhaps XCTest driver can have a mobile command to send commands to idb via https://github.com/appium/appium-idb so at least you can send ab idb command over Appium. idb itself didn't work on my local well so not suer it could be helpful.

**Comment by fleytman** [comment]
How i can use https://github.com/appium/appium-idb from java-client to execute idb commands?

>idb itself didn't work on my local well so not suer it could be helpful.
Do you know anybody, who can help me?

**Comment by KazuCocoa** [comment]
No, I meant XCUITest driver could have `mobile: idb` and proxy commands to the `appium-idb` dependency as a new feature. Then your code can send idb commands via `mobile: idb`. This is just an idea.


No, I'm afraid that none in the core team has idb working environment. Then, someone from Appium community interested in this idb feature would help.

**Comment by KazuCocoa** [comment]
Btw, have you tried out `xcrun simctl privacy` command by Apple?

```
% xcrun simctl privacy
Grant, revoke, or reset privacy and permissions
Usage: simctl privacy <device> <action> <service> [<bundle identifier>]

	action
	     The action to take:
	         grant - Grant access without prompting. Requires bundle identifier.
	         revoke - Revoke access, denying all use of the service. Requires bundle identifier.
	         reset - Reset access, prompting on next use. Bundle identifier optional.
	     Some permission changes will terminate the application if running.
	service
	     The service:
	         all - Apply the action to all services.
	         calendar - Allow access to calendar.
	         contacts-limited - Allow access to basic contact info.
	         contacts - Allow access to full contact details.
	         location - Allow access to location services when app is in use.
	         location-always - Allow access to location services at all times.
	         photos-add - Allow adding photos to the photo library.
	         photos - Allow full access to the photo library.
	         media-library - Allow access to the media library.
	         microphone - Allow access to audio input.
	         motion - Allow access to motion and fitness data.
	         reminders - Allow access to reminders.
	         siri - Allow use of the app with Siri.
	bundle identifier
	     The bundle identifier of the target application.

Examples:
	reset all permissions: privacy <device> reset all
	grant test host photo permissions: privacy <device> grant photos com.example.app.test-host

Warning:
Normally applications must have valid Info.plist usage description keys and follow the API guidelines to request access to services. Using this command to bypass those requirements can mask bugs.
```

I wondered if we could drop the wix's one since our support Xcode version no longer needs to be old. We can probably use `xcrun simctl privacy` as the primary method for mobile permission commands

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-xcuitest-driver/pull/2275 will help this

**Comment by KazuCocoa** [comment]
Please try out the xcuitest driver v5.11.0. 
https://github.com/appium/appium-xcuitest-driver/blob/master/docs/execute-methods.md#mobile-setpermission

**Comment by spulberatorul** [comment]
The solution that worked for me on real IOS device (Iphone XR ...iOS 17.4.1 + XCode 15.4)(Java version ... after many days of frustation)

       public void acceptIOSLocationAlert() {

        SWUtils.waitBeforeNextAction(5000);

        WebDriverWait wait = new WebDriverWait(appiumDriver, Duration.ofSeconds(30));
        wait.until(ExpectedConditions.alertIsPresent());

        appiumDriver.switchTo().alert();
        SWUtils.waitBeforeNextAction(2000);

        HashMap args = new HashMap<>();
        args.put("action", "accept");
        args.put("buttonLabel", "Allow While Using App");
        appiumDriver.executeScript("mobile: alert", args);

        SWUtils.waitBeforeNextAction(2000);
    }

Where "waitBeforeNextAction" method is a simple wait like this:

        public static void waitBeforeNextAction(int milisecongs) {
        try {
            Thread.sleep(milisecongs);
        } catch (InterruptedException ex) {
            Logger.getLogger(SWUtils.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

What is have installed on MAC (MacBook Pro with Apple M2 pro):

xxxxxxxxxxx@admins-MacBook-Pro ~ % appium -v
2.5.4
xxxxxxxxxxx@admins-MacBook-Pro ~ % appium driver list
✔ Listing available drivers
- xcuitest@7.15.2 [installed (npm)]
- uiautomator2@3.5.0 [installed (npm)]
- mac2 [not installed]
- espresso [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]
xxxxxxxxxxx@admins-MacBook-Pro ~ % node -v
v22.1.0
xxxxxxxxxxx@admins-MacBook-Pro ~ % npm -v
10.7.0

On my project(maven one) I have these versions for appium and selenium:
appium: 9.2.2
selenium 4.20.0

Note: Another thing that I guess will work is to dismiss the alert (when you install app) and then (after app is installed...close app and ...) enter in phone menu (automate this) General -> Privacy and Security-> Location service-> "your app" and even select "Allways". I guess I will also do this because at some point ... even with app closed ... iOS shows anoter popup that ask you to preserve current location setting or change to "Always".
