### ISSUE TITLE
bug: Unable to download apk from remote using URL with credentials in appium@2.x

### ISSUE THREAD

**Issue by VolkovPetr** [appium/appium#18999]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

capability:
"appium:app": "https://{user}:{pass}@{URL to apk}"
don't work with Appium 2.1.0

Get error:
Encountered internal error running command: Error: Cannot download the app from https://.apk: Request failed with status code 401

### Expected Behavior

On first version of appium everething works

### Minimal Reproducible Example

i can't find example repository on internet to download apk with in URL credentials and i can't show mine

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by jlipps** [comment]
Please attach a complete Appium log

**Comment by VolkovPetr** [comment]
[appium.log](https://github.com/appium/appium/files/12386602/appium.log)

**Comment by VolkovPetr** [comment]
> Please attach a complete Appium log

[appium.log](https://github.com/appium/appium/files/12388844/appium.log)

**Comment by VolkovPetr** [comment]
fixed
