### ISSUE TITLE
[Feat]: view Live screen of devices in novnc of selenium grid 4 via novnc port

### ISSUE THREAD

**Issue by krishtoautomate** [appium/appium#19009]
**Is your feature request related to a problem? Please describe.**
selenium grid 4 supports live view of browsers via no-vnc port but appium session cannot be viewed live though we use mjpegurl or port

**Describe the solution you'd like**
would like to see live view of devices screen wheres tests being executed on selenium grid with relay appium

**Describe alternatives you've considered**
is it possible to point appium mjpegurl to selenium grid sessions novnc port to see it live. 
we have similar feature in appium inspector.

**Comment by KazuCocoa** [comment]
Didn't `appium:mjpegServerPort` in UIA2 and XCUITest driver help?

**Comment by mykola-mokhnach** [comment]
novnc uses RFB protocol to communicate (also wrapped into websockets), which is something completely different from what MJPEG client would expect. 
In theory it would be possible to write a plugin, which may connect to the RFB server, periodically request screen buffers, convert them to JPEGs if necessary and then expose it on some other local port, which MJPEG client could consume. In order to do it one must have a deep knowledge of the Remote Frame Buffer protocol and binary data processing in node.js ;)

**Comment by krishtoautomate** [comment]
> Didn't `appium:mjpegServerPort` in UIA2 and XCUITest driver help?

this doesn't show in same grid 4 UI. each URL needed to be opened in separate tab and also for large scale, this will not be ideal.

**Comment by krishtoautomate** [comment]
> novnc uses RFB protocol to communicate (also wrapped into websockets), which is something completely different from what MJPEG client would expect. In theory it would be possible to write a plugin, which may connect to the RFB server, periodically request screen buffers, convert them to JPEGs if necessary and then expose it on some other local port, which MJPEG client could consume. In order to do it one must have a deep knowledge of the Remote Frame Buffer protocol and binary data processing in node.js ;)

ya something like this can be done : 

`const WebSocket = require('ws');
const axios = require('axios');

// Fetch the MJPEG stream from appium-wda
const mjpegUrl = 'your_appium_wda_mjpeg_url';
const response = await axios.get(mjpegUrl, { responseType: 'stream' });

// Create a WebSocket connection to the noVNC server
const ws = new WebSocket('ws://your_novnc_server_address:your_novnc_port');

response.data.on('data', frameData => {
  // Forward the frame data to the noVNC server
  ws.send(frameData, { binary: true });
});

response.data.on('end', () => {
  // Close the WebSocket connection when the stream ends
  ws.close();
});`

**Comment by jlipps** [comment]
Seems like a great idea for a plugin @krishtoautomate! Let us know when you build it and we will link to it in the docs 😉

**Comment by krishtoautomate** [comment]
need help.

I buffered mjpeg video to nonvnc port : 7900

and specified below capabilities in selenium node stereotype configs

  "se:noVncPort": 7900,
  "se:vncEnabled": true,

and failed to see vnc stream in grid while tests are running.

**Comment by krishtoautomate** [comment]
stream need to be sent through following websocket url, for video to appear in selenium grid ui similar to novnc view of browsers :
*does not require to stream to 5900 or 7900 as this is not handled in appium unlike docker chrome nodes

ws://{node-id}:{node-port}/session/{session-id}/se/vnc

**Comment by jlipps** [comment]
This is not something the core team will work on, I don't think.
