### ISSUE TITLE
Not able to install Ui automator2

### ISSUE THREAD

**Issue by DeliaLing** [appium/appium#19005]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is no error when installing the ui automator2 driver, it stays installing status the whole day

Chrome browser version: 116
Last login: Fri Aug 18 15:48:27 on ttys002
linzha02@16810-lt-x0141 ~ % node -v
v18.17.1
linzha02@16810-lt-x0141 ~ % npm -v
9.6.7
linzha02@16810-lt-x0141 ~ % appium -v
2.0.1
linzha02@16810-lt-x0141 ~ % appium driver list
✔ Listing available drivers
- xcuitest@4.33.2 [installed (npm)]
- uiautomator2 [not installed]
- mac2 [not installed]
- espresso [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]
linzha02@16810-lt-x0141 ~ % appium driver install uiautomator2
⠧ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'

### Expected Behavior

Expect UI automator can be installed successfullynot

### Minimal Reproducible Example

run Appium driver install uiautomator2 on Mac 13.4.1

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by jlipps** [comment]
what happens when you run the driver install command?

**Comment by DeliaLing** [comment]
Hello all, I restart my Mac, and disconnect the company vpn app. and run the Appium driver install uiautomator2 again. getting error below, it looks like cache issue for my old npm version. I follow the bottom instruction to run the command.  and then it works .

linzha02@SRM-AP-489 ~ % appium driver install uiautomator2    
✖ Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.

STDOUT:
{
  "error": {
    "code": "EACCES",
    "summary": "\nYour cache folder contains root-owned files, due to a bug in\nprevious versions of npm which has since been addressed.\n\nTo permanently fix this problem, please run:\n  sudo chown -R 792468883:1027045583 \"/Users/linzha02/.npm\"",
    "detail": ""
  }
}

STDERR:
npm WARN config global-style This option has been deprecated in favor of `--install-strategy=shallow`
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /Users/linzha02/.npm/_cacache/index-v5/40/1e/381772a47efd50bb78f25d9e93fdb1884d89e3dfc24e502cc54d6695280d
npm ERR! errno EACCES
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 792468883:1027045583 "/Users/linzha02/.npm"
