### ISSUE TITLE
[Feat]: Appium compatibility with XCode 15 beta visionOS simulator 

### ISSUE THREAD

**Issue by cyablecki** [appium/appium#19003]
Hi, 

Just to clarify this is not related to an issue.

I am currently using Appium with XCode Beta to test with various different iOS simulators and I noticed that it had the visionOS SDK. I tried to connect to the simulator with Appium but I am having issues due to the OS and version being completely different compared to the other simulated iOS devices through XCode. (visionOS and 1.0).

Is there planned support for the visionOS simulator through XCode?

Thank you for your time.

**Comment by mykola-mokhnach** [comment]
No, we do not have any plans in the team regarding VisionOS support. Although the architecture is open, so everybody could create a driver to support this OS if they are motivated to do it.
