### ISSUE TITLE
appium 2.1.0: find_element_by_image fails with error

### ISSUE THREAD

**Issue by DanielHaimMayberg** [appium/appium#19010]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading from appium 2 beta version to Appium 2.1.0 the find_element_by image method fails with the following error:

`Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: support_1.imageUtil.getJimpImage is not a function
UnknownError: An unknown server-side error occurred while processing the command. Original error: support_1.imageUtil.getJimpImage is not a function
    at getResponseForW3CError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1073:9)
    at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:491:57)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

### Expected Behavior

I expect the imager plugin and method to work properly

### Minimal Reproducible Example

@@driver.find_element_by_image './test/functional/data/test_element_image.png'

### Environment

- Operating system: MacOS ventura 13.5
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s): 
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: iOS simulator

**Comment by mykola-mokhnach** [comment]
It looks like you have some obsolete stuff cached. Try to uninstall and install the server and the images plugin fresh (maybe also clear the npm cache).

Also provide the full server log if the above does not help

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by DanielHaimMayberg** [comment]
Will send a response today, sorry for the late reply

**Comment by DanielHaimMayberg** [comment]
@mykola-mokhnach followed your advice and after reinstalling the image plugin everything worked properly. Thanks appreciate it!
