### ISSUE TITLE
Could not load plugin 'universal-xml' 

### ISSUE THREAD

**Issue by relax2code** [appium/appium#19025]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Universal-xml plugin failed to loaded

### Expected Behavior

Universal-XML plugin should be loaded

### Minimal Reproducible Example

appium --use-plugins=universal-xml

### Environment

- Operating system: Ubuntu 22
- Appium server version (output of `appium --version`): 2.1.1
- Appium driver(s) and their version(s): uiautomator2@2.29.5
- Appium plugin(s) and their version(s): universal-xml@1.0.11
- Node.js version (output of `node --version`): v19.2.0
- `npm` version (output of `npm --version`):8.19.3
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Link to Appium Logs

[Appium] Could not load plugin 'universal-xml', so it will not be available. Error in loading the plugin was: Unexpected token 'export'
[debug] [Appium] /home/relax/.appium/node_modules/@appium/universal-xml-plugin/index.js:7
[debug] [Appium] export {UniversalXMLPlugin};

### Further Information

First , I want to thank you for this great project , thank you for the maintainers and all contributors.
I've seen unable to load universal-xml issue and already closed ,  so I try the newest version  but it still failed to load the plugin.

**Comment by mykola-mokhnach** [comment]
cc @jlipps

**Comment by relax2code** [comment]
Thank you very much , universal-xml can now be successfully loaded

**Comment by jlipps** [comment]
you're welcome!
