### ISSUE TITLE
Appium should be able to run when installed via `sudo npm`

### ISSUE THREAD

**Issue by jlipps** [appium/appium#1902]
We're making use of some files that can't be read when Appium is installed via sudo. We could perhaps chmod these files on install so they can be read without error. And we should make sure we're only ever writing to /tmp in this case too.

**Comment by jaleksynas** [comment]
Does this actually resolve #3144 as promised?   Using --no-perms-check and --tmp <private user dir> still results in the don't use sudo error message.  This is with 1.4.13 (using the MacOSX dmg installer).  The intention is to allow several users to run individual instances (with individual ports) without each installing a copy of node/appium.

**Comment by jlipps** [comment]
appium 1.5+ no longer restrict when running as root
