### ISSUE TITLE
Error while connecting real iphone with appium inspector

### ISSUE THREAD

**Issue by Rushann** [appium/appium#19038]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

getting this error message while connecting real iphone with appium inspector. 
Failed to create session. An unknown server-side error occurred while processing the command. Original error: '16.5.1' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 16.4
![Screenshot 2023-08-23 at 3 25 38 PM](https://github.com/appium/appium/assets/88871439/8c665f5e-ba66-42d5-ab37-2c463ec28db7)

### Expected Behavior

Should needs to connect iphone successfully with appium inspector.

### Minimal Reproducible Example

trying to connect appium inspector with iphone.

### Environment

- Operating system:Mac
- Appium server version (output of `appium --version`):2
- Appium driver(s) and their version(s):latest
- Appium plugin(s) and their version(s):latest
- Node.js version (output of `node --version`):18.16.1
- `npm` version (output of `npm --version`):9.5.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:iOS
- Real device or emulator/simulator:Real device

### Link to Appium Logs

Last login: Wed Aug 23 13:07:45 on console rushan@Rushans-Mac-mini ~ % appium [Appium] Welcome to Appium v2.0.0 [Appium] Attempting to load driver xcuitest... [debug] [Appium] Requiring driver at /Users/rushan/.appium/node_modules/appium-xcuitest-driver [Appium] Attempting to load driver uiautomator2... [debug] [Appium] Requiring driver at /Users/rushan/.appium/node_modules/appium-uiautomator2-driver [Appium] Appium REST http interface listener started on http://0.0.0.0:4723 [Appium] You can provide the following URLS in your client code to connect to this server: [Appium] 	http://127.0.0.1:4723/ (only accessible from the same host) [Appium] 	http://192.168.1.4:4723/ [Appium] 	http://169.254.184.169:4723/ [Appium] Available drivers: [Appium]   - xcuitest@4.32.19 (automationName 'XCUITest') [Appium]   - uiautomator2@2.29.2 (automationName 'UiAutomator2') [Appium] Available plugins: [Appium]   - execute-driver@3.0.14 [Appium]   - element-wait@2.0.3 [Appium]   - gestures@3.0.0 [Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate [HTTP] --> POST /session [HTTP] {"capabilities":{"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"16.5.1","appium:deviceName":"iPhone Xs Max","appium:automationName":"XCUITest","appium:bundleId":"com.hotake.Hotake","appium:noReset":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"iOS","appium:platformVersion":"16.5.1","appium:deviceName":"iPhone Xs Max","appium:automationName":"XCUITest","appium:bundleId":"com.hotake.Hotake","appium:noReset":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}} [debug] [AppiumDriver@7975] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","appium:platformVersion":"16.5.1","appium:deviceName":"iPhone Xs Max","appium:automationName":"XCUITest","appium:bundleId":"com.hotake.Hotake","appium:noReset":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"16.5.1","appium:deviceName":"iPhone Xs Max","appium:automationName":"XCUITest","appium:bundleId":"com.hotake.Hotake","appium:noReset":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}] [debug] [AppiumDriver@7975] Event 'newSessionRequested' logged at 1692784215016 (15:20:15 GMT+0530 (India Standard Time)) [Appium] Attempting to find matching driver for automationName 'XCUITest' and platformName 'iOS' [Appium] The 'xcuitest' driver was installed and matched caps. [Appium] Will require it at /Users/rushan/.appium/node_modules/appium-xcuitest-driver [debug] [Appium] Requiring driver at /Users/rushan/.appium/node_modules/appium-xcuitest-driver [AppiumDriver@7975] Appium v2.0.0 creating new XCUITestDriver (v4.32.19) session [AppiumDriver@7975] Checking BaseDriver versions for Appium and XCUITestDriver [AppiumDriver@7975] Appium's BaseDriver version is 9.3.15 [AppiumDriver@7975] XCUITestDriver's BaseDriver version is 9.3.15 [debug] [XCUITestDriver@a9c3] Creating session with W3C capabilities: { [debug] [XCUITestDriver@a9c3]   "alwaysMatch": { [debug] [XCUITestDriver@a9c3]     "platformName": "iOS", [debug] [XCUITestDriver@a9c3]     "appium:platformVersion": "16.5.1", [debug] [XCUITestDriver@a9c3]     "appium:deviceName": "iPhone Xs Max", [debug] [XCUITestDriver@a9c3]     "appium:automationName": "XCUITest", [debug] [XCUITestDriver@a9c3]     "appium:bundleId": "com.hotake.Hotake", [debug] [XCUITestDriver@a9c3]     "appium:noReset": true, [debug] [XCUITestDriver@a9c3]     "appium:includeSafariInWebviews": true, [debug] [XCUITestDriver@a9c3]     "appium:newCommandTimeout": 3600, [debug] [XCUITestDriver@a9c3]     "appium:connectHardwareKeyboard": true [debug] [XCUITestDriver@a9c3]   }, [debug] [XCUITestDriver@a9c3]   "firstMatch": [ [debug] [XCUITestDriver@a9c3]     {} [debug] [XCUITestDriver@a9c3]   ] [debug] [XCUITestDriver@a9c3] } [XCUITestDriver@a9c3 (b0b2c425)] Session created with session id: b0b2c425-96e8-41fb-bccf-fd4d208260e4 [debug] [XCUITest] Current user: 'rushan' [XCUITestDriver@a9c3 (b0b2c425)] iOS SDK Version set to '16.4' [XCUITestDriver@a9c3 (b0b2c425)] {} [DevCon Factory] Neither device UDID nor local port is set. Did not know how to release the connection [debug] [AppiumDriver@7975] Event 'newSessionStarted' logged at 1692784218610 (15:20:18 GMT+0530 (India Standard Time)) [debug] [AppiumDriver@7975] Encountered internal error running command: Error: '16.5.1' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 16.4 [debug] [AppiumDriver@7975]     at Simctl.getDevices (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/node_modules/node-simctl/lib/subcommands/list.js:171:9) [debug] [AppiumDriver@7975]     at getExistingSim (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/lib/simulator-management.js:122:52) [debug] [AppiumDriver@7975]     at XCUITestDriver.determineDevice (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:1298:22) [debug] [AppiumDriver@7975]     at XCUITestDriver.start (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:488:40) [debug] [AppiumDriver@7975]     at XCUITestDriver.createSession (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:404:7) [debug] [AppiumDriver@7975]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:346:35) [HTTP] <-- POST /session 500 3658 ms - 756

### Further Information

Last login: Wed Aug 23 13:07:45 on console
rushan@Rushans-Mac-mini ~ % appium
[Appium] Welcome to Appium v2.0.0
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at /Users/rushan/.appium/node_modules/appium-xcuitest-driver
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /Users/rushan/.appium/node_modules/appium-uiautomator2-driver
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLS in your client code to connect to this server:
[Appium] 	http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] 	http://192.168.1.4:4723/
[Appium] 	http://169.254.184.169:4723/
[Appium] Available drivers:
[Appium]   - xcuitest@4.32.19 (automationName 'XCUITest')
[Appium]   - uiautomator2@2.29.2 (automationName 'UiAutomator2')
[Appium] Available plugins:
[Appium]   - execute-driver@3.0.14
[Appium]   - element-wait@2.0.3
[Appium]   - gestures@3.0.0
[Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"16.5.1","appium:deviceName":"iPhone Xs Max","appium:automationName":"XCUITest","appium:bundleId":"com.hotake.Hotake","appium:noReset":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"iOS","appium:platformVersion":"16.5.1","appium:deviceName":"iPhone Xs Max","appium:automationName":"XCUITest","appium:bundleId":"com.hotake.Hotake","appium:noReset":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[debug] [AppiumDriver@7975] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","appium:platformVersion":"16.5.1","appium:deviceName":"iPhone Xs Max","appium:automationName":"XCUITest","appium:bundleId":"com.hotake.Hotake","appium:noReset":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"16.5.1","appium:deviceName":"iPhone Xs Max","appium:automationName":"XCUITest","appium:bundleId":"com.hotake.Hotake","appium:noReset":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[debug] [AppiumDriver@7975] Event 'newSessionRequested' logged at 1692784215016 (15:20:15 GMT+0530 (India Standard Time))
[Appium] Attempting to find matching driver for automationName 'XCUITest' and platformName 'iOS'
[Appium] The 'xcuitest' driver was installed and matched caps.
[Appium] Will require it at /Users/rushan/.appium/node_modules/appium-xcuitest-driver
[debug] [Appium] Requiring driver at /Users/rushan/.appium/node_modules/appium-xcuitest-driver
[AppiumDriver@7975] Appium v2.0.0 creating new XCUITestDriver (v4.32.19) session
[AppiumDriver@7975] Checking BaseDriver versions for Appium and XCUITestDriver
[AppiumDriver@7975] Appium's BaseDriver version is 9.3.15
[AppiumDriver@7975] XCUITestDriver's BaseDriver version is 9.3.15
[debug] [XCUITestDriver@a9c3] Creating session with W3C capabilities: {
[debug] [XCUITestDriver@a9c3]   "alwaysMatch": {
[debug] [XCUITestDriver@a9c3]     "platformName": "iOS",
[debug] [XCUITestDriver@a9c3]     "appium:platformVersion": "16.5.1",
[debug] [XCUITestDriver@a9c3]     "appium:deviceName": "iPhone Xs Max",
[debug] [XCUITestDriver@a9c3]     "appium:automationName": "XCUITest",
[debug] [XCUITestDriver@a9c3]     "appium:bundleId": "com.hotake.Hotake",
[debug] [XCUITestDriver@a9c3]     "appium:noReset": true,
[debug] [XCUITestDriver@a9c3]     "appium:includeSafariInWebviews": true,
[debug] [XCUITestDriver@a9c3]     "appium:newCommandTimeout": 3600,
[debug] [XCUITestDriver@a9c3]     "appium:connectHardwareKeyboard": true
[debug] [XCUITestDriver@a9c3]   },
[debug] [XCUITestDriver@a9c3]   "firstMatch": [
[debug] [XCUITestDriver@a9c3]     {}
[debug] [XCUITestDriver@a9c3]   ]
[debug] [XCUITestDriver@a9c3] }
[XCUITestDriver@a9c3 (b0b2c425)] Session created with session id: b0b2c425-96e8-41fb-bccf-fd4d208260e4
[debug] [XCUITest] Current user: 'rushan'
[XCUITestDriver@a9c3 (b0b2c425)] iOS SDK Version set to '16.4'
[XCUITestDriver@a9c3 (b0b2c425)] {}
[DevCon Factory] Neither device UDID nor local port is set. Did not know how to release the connection
[debug] [AppiumDriver@7975] Event 'newSessionStarted' logged at 1692784218610 (15:20:18 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@7975] Encountered internal error running command: Error: '16.5.1' does not exist in the list of simctl SDKs. Only the following Simulator SDK versions are available on your system: 16.4
[debug] [AppiumDriver@7975]     at Simctl.getDevices (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/node_modules/node-simctl/lib/subcommands/list.js:171:9)
[debug] [AppiumDriver@7975]     at getExistingSim (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/lib/simulator-management.js:122:52)
[debug] [AppiumDriver@7975]     at XCUITestDriver.determineDevice (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:1298:22)
[debug] [AppiumDriver@7975]     at XCUITestDriver.start (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:488:40)
[debug] [AppiumDriver@7975]     at XCUITestDriver.createSession (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:404:7)
[debug] [AppiumDriver@7975]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:346:35)
[HTTP] <-- POST /session 500 3658 ms - 756

**Comment by mykola-mokhnach** [comment]
The error above seems expected to me. What exactly is unclear about it?

**Comment by Rushann** [comment]
I can able to connect with simulator. But showing this error while connecting real iphone. The iphone version is 16.5.1 .But here its showing like not supported @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Consider providing the `udid` capability if you want to connect to a real phone. Currently the driver to select a matching simulator

**Comment by Rushann** [comment]
That error is resolved now. But now getting this error . In my simulator when i try to connect with appium inspector Webdriver agent will get installed automatically.But here(real device) its showing error related to that. FYI:There is no Webdriver agent in my iphone.
![Screenshot 2023-08-23 at 5 44 11 PM](https://github.com/appium/appium/assets/88871439/ee83719f-9a13-409d-aa0a-af9e6367620f)

**Comment by mykola-mokhnach** [comment]
Consider checking existing issue regarding error code 70: https://github.com/appium/appium/issues?q=is%3Aissue+%22code+70%22+is%3Aclosed

there might be multiple reasons to it, mostly related to incorrect setup on the client side. Please use Appium forum to ask further  questions.
