### ISSUE TITLE
Appium server crash: Fatal RangeError: Invalid string length

### ISSUE THREAD

**Issue by SergiyBelevitnevSFLY** [appium/appium#19039]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run the tests in parallel - after 40 minutes of run appium server crashes with the next message

Fatal RangeError: Invalid string length
    at Socket.patchedWriter (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/express/idempotency.js:42:25)
    at Socket.patchedWriter [as write] (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/express/idempotency.js:44:12)
    at ServerResponse._writeRaw (node:_http_outgoing:403:17)
    at ServerResponse._send (node:_http_outgoing:380:15)
    at write_ (node:_http_outgoing:946:15)
    at ServerResponse.end (node:_http_outgoing:1030:5)
    at ServerResponse.send (/usr/local/lib/node_modules/appium/node_modules/express/lib/response.js:232:10)
    at ServerResponse.json (/usr/local/lib/node_modules/appium/node_modules/express/lib/response.js:278:15)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:513:30)
[debug] [BaseDriver] Performing cleanup of 1 cached application

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

It started repro after I updated
MacOS to 13.5.1
Xcode to 14.3.1
Appium to 2.1.2
Xcuitest driver to 4.34.1 

### Expected Behavior

Appium should run without crashing

### Minimal Reproducible Example

Run tests in parallel on iOS real devices with described environment and observe

### Environment

- Operating system:
- Appium server version: 2.1.2
- Appium driver: 4.34.1
- Appium plugin(s) and their version(s): images@2.1.2
- Node.js version (output of `node --version`): 20.5.1
- `npm` version (output of `npm --version`): 9.8.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS
- Real device or emulator/simulator: Real device (15.1 iOS)

**Comment by SergiyBelevitnevSFLY** [comment]
Repro on several machines
Also repro when run in one thread

**Comment by SergiyBelevitnevSFLY** [comment]
@mykola-mokhnach please see gist https://gist.github.com/SergiyBelevitnevSFLY/e6e1b08e3b9ea6601427c8ca77cae90e
If you need more extended log let me know pls

**Comment by mykola-mokhnach** [comment]
The patch has been merged and will be published in the next server release

**Comment by qxq000** [comment]
我也遇到了一样的问题。
[HTTP] <-- GET /session/b4d9b2e0-aadd-4bc5-a88b-e60d2b9e1b7e/screenshot 200 452 ms - 553612
[HTTP] 
[HTTP] --> GET /session/b4d9b2e0-aadd-4bc5-a88b-e60d2b9e1b7e/screenshot
[HTTP] {}
[debug] [AndroidUiautomator2Driver@33fd (b4d9b2e0)] Calling AppiumDriver.getScreenshot() with args: ["b4d9b2e0-aadd-4bc5-a88b-e60d2b9e1b7e"]
[debug] [AndroidUiautomator2Driver@33fd (b4d9b2e0)] Matched '/screenshot' to command name 'getScreenshot'
[debug] [AndroidUiautomator2Driver@33fd (b4d9b2e0)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8201/session/fe680884-90db-4538-996b-829eaa6ef482/screenshot] with no body
[debug] [AndroidUiautomator2Driver@33fd (b4d9b2e0)] Got response with status 200: {"sessionId":"fe680884-90db-4538-996b-829eaa6ef482","value":"iVBORw0KGgoAAAANSUhEUgAAAtAAAAUACAYAAABuzmU9AAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7L3dmvQorib6CuyIzOo1a2bPnO37v7h9vLqrMiNs0D4QPwKE7cjMr6r6mUV3femw+REgxCsQgn773/8vAwABYABhe4BDAAMgIvjbDRwjyHkQOQAAmOU7ABCBmcEMAAyOEXF/AADcsoCcQww7yN1ARAAo/ZVQn2bhPAYAxLgjbg8wx0vxc7Y0yZ/B0iCngUF+hVtuuEprn/6sHDaeLuWcolP5JweafRA+YAbvD/C+NfGkTbjtP3KAI+EP78AxAjEC/q3E4472lhQCYkB8fko6CN/lvJgZ/v4Gt6y6ZoAjyUgIrmUxgyI3lc/lhW1H3DfEEEGOcL+tcN5h33bEEKUrOCIySzrncH+7YVkW/PH7B2i9wy1rwxt9jzBzyoebPgAAl2gk3TeTLo0cER6/gzk07f13CWX8H7z5ZYEA8sJvAEDvN2BdQACcc4gxCu9sO3iPaJhAU6n6o7x0DrT4xINU4rDZB4T6ukqSVr5N2uSoqaym5PIP+icG4ABs//od4fkEOYd9D1iWFf/zf/0/YCL8ET4TT3LKiuGCZESAyO1tB6Py8Kz8TB4zpI1W37QHP3bwHhD3HRQu1PeHg26+mcT8+42oGhgMcgv8/T9xXpOfKjSC8ASIEB5P6bvlBn/7DQzC4oH981+ITPC3d3Cax5kBIsZtIXz8/l+IIcC5Fe7+DxA5qctQ2MjcvH3AYQNA2PdY5GcZU+sb3PqOth30PJRkKvVfroSMfo5p/KWBbCrOKMlp7PqOco+ZsT8+wDFA8xaRyLr7AiwuYbr01ZWn/K7Fb1meMAiBHSKqfAgxIoZQ4xPh7ebKXFjqk0ROjIw91P5P1IGZ4ZzH/R//A+Q8rodWGjC334b2zvUu...
[debug] [AndroidUiautomator2Driver@33fd (b4d9b2e0)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAtAAAAUACAYAAABuzmU9AAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7L3dmvQorib6CuyIzOo1a2bPnO37v7h9vLqrMiNs0D4QPwKE7cjMr6r6mUV3femw+REgxCsQgn773/8vAwABYABhe4BDAAMgIvjbDRwjyHkQOQAAmOU7ABCBmcEMAAyOEXF/AADcsoCcQww7yN1ARAAo/ZVQn2bhPAYAxLgjbg8wx0vxc7Y0yZ/B0iCngUF+hVtuuEprn/6sHDaeLuWcolP5JweafRA+YAbvD/C+NfGkTbjtP3KAI+EP78AxAjEC/q3E4472lhQCYkB8fko6CN/lvJgZ/v4Gt6y6ZoAjyUgIrmUxgyI3lc/lhW1H3DfEEEGOcL+tcN5h33bEEKUrOCIySzrncH+7YVkW/PH7B2i9wy1rwxt9jzBzyoebPgAAl2gk3TeTLo0cER6/gzk07f13CWX8H7z5ZYEA8sJvAEDvN2BdQACcc4gxCu9sO3iPaJhAU6n6o7x0DrT4xINU4rDZB4T6ukqSVr5N2uSoqaym5PIP+icG4ABs//od4fkEOYd9D1iWFf/zf/0/YCL8ET4TT3LKiuGCZESAyO1tB6Py8Kz8TB4zpI1W37QHP3bwHhD3HRQu1PeHg26+mcT8+42oGhgMcgv8/T9xXpOfKjSC8ASIEB5P6bvlBn/7DQzC4oH981+ITPC3d3Cax5kBIsZtIXz8/l+IIcC5Fe7+DxA5qctQ2MjcvH3AYQNA2PdY5GcZU+sb3PqOth30PJRkKvVfroSMfo5p/KWBbCrOKMlp7PqOco+ZsT8+wDFA8xaRyLr7AiwuYbr01ZWn/K7Fb1meMAiBHSKqfAgxIoZQ4xPh7ebKXFjqk0ROjIw91P5P1IGZ4ZzH/R//A+Q8rodWGjC334b2zvUuc3ieqAn75x+I+7PkR0RwbTEE5xZVXgVMDTAlKg2eXkB+9izA5XuNN4Ln77Mm...
[HTTP] <-- GET /session/b4d9b2e0-aadd-4bc5-a88b-e60d2b9e1b7e/screenshot 200 442 ms - 553804
[HTTP] 
[HTTP] --> GET /session/b4d9b2e0-aadd-4bc5-a88b-e60d2b9e1b7e/screenshot
[HTTP] {}
[debug] [AndroidUiautomator2Driver@33fd (b4d9b2e0)] Calling AppiumDriver.getScreenshot() with args: ["b4d9b2e0-aadd-4bc5-a88b-e60d2b9e1b7e"]
[debug] [AndroidUiautomator2Driver@33fd (b4d9b2e0)] Matched '/screenshot' to command name 'getScreenshot'
[debug] [AndroidUiautomator2Driver@33fd (b4d9b2e0)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8201/session/fe680884-90db-4538-996b-829eaa6ef482/screenshot] with no body
[debug] [AndroidUiautomator2Driver@33fd (b4d9b2e0)] Got response with status 200: {"sessionId":"fe680884-90db-4538-996b-829eaa6ef482","value":"iVBORw0KGgoAAAANSUhEUgAAAtAAAAUACAYAAABuzmU9AAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7H1rl+woju0W4IjMU31nZs3H+///312ru+pkhm3Q/SAe4mU7IvNUVa8ZuutkhAODACFtgRD047//LwMAAWAAfnuAvQcDICLY2w0cAshYEBkAAJjldwAgAjODGQAYHALC/gAAGOdAxiD4HWRuICIAFP9KKp9m6TwHAISwI2wPMIdL+VOxNCmfwdIhp4lBdoFxN1yltX3/rB4efLpUcsxO+Z+UaPaD8AEzeH+A963KJ33C9fiRAQwJf1gDDgEIAbBvOR83tNekEBA8wvop70H4LpXFzLD3Nxi36JYBhqQgIbjUxQwKXDU+1ee3HWHfEHwAGcL9tsBYg33bEXyQoeCAwCzvGYP72w3OOfz84wO03GHcUvFGOyLMHMvhagwAwEQaSY/NZEgDB/jHH2D2VX//XVKe/wdPflkigKzwGwDQ+w1YLAgEYwxCCMI72w7ee3nQ9qf+SpZAzgGRB8lEvgeBqZ8taQolOUKR4fJI68/jpuQ0n91c/8bqaWRFQ8D2z39hX1eQMdh3D7fc8F//9d8IhvBz/wQjlHeZYTxk7oBEbm87hH0HMolLxWmkmaW/sNjSHwTwYwfvHmHfQX7Q0F+cNCfO+vTvN6NKYjDIONj7f+C8Jd9VaQBhBYjgH6uMnbvB3n6AQXAW2D9/R2CCvb2Dox5nBogYN0f4+OOfCN7DmAXm/huIjLSlq6x9wuDtAwYbAMK+hyw/U05a3mCWd9T9oPVQlKnU/nIlJfRzTOMvTTSm4oyS9M5UulCTlxn74wMcPDRvERFAhLsDnImYLv5q8qf0rMZvIhpkpD0bBBT54ENA8L7kJ8LbzWRdmNsTRU4IjN2X8Y/UibwyFvff/g/IWFxPtTRgrn/r...
[debug] [AndroidUiautomator2Driver@33fd (b4d9b2e0)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAtAAAAUACAYAAABuzmU9AAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7H1rl+woju0W4IjMU31nZs3H+///312ru+pkhm3Q/SAe4mU7IvNUVa8ZuutkhAODACFtgRD047//LwMAAWAAfnuAvQcDICLY2w0cAshYEBkAAJjldwAgAjODGQAYHALC/gAAGOdAxiD4HWRuICIAFP9KKp9m6TwHAISwI2wPMIdL+VOxNCmfwdIhp4lBdoFxN1yltX3/rB4efLpUcsxO+Z+UaPaD8AEzeH+A963KJ33C9fiRAQwJf1gDDgEIAbBvOR83tNekEBA8wvop70H4LpXFzLD3Nxi36JYBhqQgIbjUxQwKXDU+1ee3HWHfEHwAGcL9tsBYg33bEXyQoeCAwCzvGYP72w3OOfz84wO03GHcUvFGOyLMHMvhagwAwEQaSY/NZEgDB/jHH2D2VX//XVKe/wdPflkigKzwGwDQ+w1YLAgEYwxCCMI72w7ee3nQ9qf+SpZAzgGRB8lEvgeBqZ8taQolOUKR4fJI68/jpuQ0n91c/8bqaWRFQ8D2z39hX1eQMdh3D7fc8F//9d8IhvBz/wQjlHeZYTxk7oBEbm87hH0HMolLxWmkmaW/sNjSHwTwYwfvHmHfQX7Q0F+cNCfO+vTvN6NKYjDIONj7f+C8Jd9VaQBhBYjgH6uMnbvB3n6AQXAW2D9/R2CCvb2Dox5nBogYN0f4+OOfCN7DmAXm/huIjLSlq6x9wuDtAwYbAMK+hyw/U05a3mCWd9T9oPVQlKnU/nIlJfRzTOMvTTSm4oyS9M5UulCTlxn74wMcPDRvERFAhLsDnImYLv5q8qf0rMZvIhpkpD0bBBT54ENA8L7kJ8LbzWRdmNsTRU4IjN2X8Y/UibwyFvff/g/IWFxPtTRgrn/r+ju1O+vwpKgJ++dPhH3N5RERTF0NwRin6iuAqQKmRLnD4wPI15YFOP9e8vXg...
Fatal RangeError: Invalid string length
    at Socket.patchedWriter [as write] (/usr/lib/node_modules/appium/node_modules/@appium/base-driver/lib/express/idempotency.js:42:25)
    at ServerResponse._writeRaw (node:_http_outgoing:404:17)
    at ServerResponse._send (node:_http_outgoing:381:15)
    at write_ (node:_http_outgoing:942:15)
    at ServerResponse.end (node:_http_outgoing:1026:5)
    at ServerResponse.send (/usr/lib/node_modules/appium/node_modules/express/lib/response.js:232:10)
    at ServerResponse.json (/usr/lib/node_modules/appium/node_modules/express/lib/response.js:278:15)
    at asyncHandler (/usr/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:513:30)
