### ISSUE TITLE
bug: When using complex xpath with attribute @visible='true', there will be AxiosError: timeout of 90000ms exceeded

### ISSUE THREAD

**Issue by klauslaiRC** [appium/appium#19030]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using complex xpath with attribute @visible='true' , The WDA will be no responding, and throw AxiosError: timeout of 90000ms exceeded by appium server

Xpath example: "//XCUIElementTypeOther[(@label ='Normal post A' or @label ='Normal post A,') and @name=\"TextViewText\" and @visible='true']/ancestor::XCUIElementTypeCell//XCUIElementTypeOther[@label='NEW MESSAGES' or @label='NEW MESSAGE']"

### Expected Behavior

Can get element by complex xpath with attribute @visible='true'

### Minimal Reproducible Example

Error message:
```
[debug] [XCUITestDriver@db03 (5d82e64d)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeOther[(@label ='Normal post A' or @label ='Normal post A,') and @name=\"TextViewText\" and @visible='true']/ancestor::XCUIElementTypeCell//XCUIElementTypeOther[@label='NEW MESSAGES' or @label='NEW MESSAGE']","5d82e64d-96ca-42c8-8dd0-72911ba585c7"]
[debug] [AppiumDriver@a935] Clearing new command timeout pre-emptively since plugin(s) will handle this command
[AppiumDriver@a935] Plugins which can handle cmd 'findElement': images
[AppiumDriver@a935] Plugin images is now handling cmd 'findElement'
[AppiumDriver@a935] Executing default handling behavior for command 'findElement'
[debug] [XCUITestDriver@db03 (5d82e64d)] Executing command 'findElement'
[debug] [XCUITestDriver@db03 (5d82e64d)] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[debug] [XCUITestDriver@db03 (5d82e64d)] Waiting up to 0 ms for condition
[debug] [XCUITestDriver@db03 (5d82e64d)] Matched '/element' to command name 'findElement'
[debug] [XCUITestDriver@db03 (5d82e64d)] Proxying [POST /element] to [POST http://127.0.0.1:8100/session/F9BC3DF1-7FFE-4AB2-A011-D667BB7D311F/element] with body: {"using":"xpath","value":"//XCUIElementTypeOther[(@label ='Normal post A' or @label ='Normal post A,') and @name=\"TextViewText\" and @visible='true']/ancestor::XCUIElementTypeCell//XCUIElementTypeOther[@label='NEW MESSAGES' or @label='NEW MESSAGE']"}
[XCUITestDriver@db03 (5d82e64d)] AxiosError: timeout of 90000ms exceeded
[XCUITestDriver@db03 (5d82e64d)]     at RedirectableRequest.handleRequestTimeout (/Users/klaus.lai/.appium/node_modules/appium-xcuitest-driver/node_modules/axios/lib/adapters/http.js:628:16)
[XCUITestDriver@db03 (5d82e64d)]     at RedirectableRequest.emit (node:events:514:28)
[XCUITestDriver@db03 (5d82e64d)]     at Timeout.<anonymous> (/Users/klaus.lai/.appium/node_modules/appium-xcuitest-driver/node_modules/follow-redirects/index.js:169:12)
[XCUITestDriver@db03 (5d82e64d)]     at listOnTimeout (node:internal/timers:569:17)
[XCUITestDriver@db03 (5d82e64d)]     at processTimers (node:internal/timers:512:7)
[debug] [XCUITestDriver@db03 (5d82e64d)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [XCUITestDriver@db03 (5d82e64d)]     at XCUITestDriver.doNativeFind (/Users/klaus.lai/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:143:13)
[debug] [XCUITestDriver@db03 (5d82e64d)]     at runNextTicks (node:internal/process/task_queues:60:5)
[debug] [XCUITestDriver@db03 (5d82e64d)]     at listOnTimeout (node:internal/timers:538:9)
[debug] [XCUITestDriver@db03 (5d82e64d)]     at processTimers (node:internal/timers:512:7)
[debug] [XCUITestDriver@db03 (5d82e64d)]     at XCUITestDriver.findNativeElementOrElements (/Users/klaus.lai/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:97:12)
[debug] [XCUITestDriver@db03 (5d82e64d)]     at XCUITestDriver.findElOrEls (/Users/klaus.lai/.appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:24:14)
[debug] [XCUITestDriver@db03 (5d82e64d)]     at XCUITestDriver.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)
[debug] [XCUITestDriver@db03 (5d82e64d)]     at XCUITestDriver.findElement (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)
[HTTP] <-- POST /wd/hub/session/5d82e64d-96ca-42c8-8dd0-72911ba585c7/element 404 90545 ms - 1099
[HTTP] 

```

### Environment

- Operating system: MacOS Ventura 13.4.1
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s): 
   - uiautomator2@2.29.2
   - xcuitest@4.34.1 
- Appium plugin(s) and their version(s):
  - images@2.1.2
  - relaxed-caps@1.0.5
  - execute-driver@3.0.15
- Node.js version (output of `node --version`): v18.17.0
- `npm` version (output of `npm --version`): 9.6.7
- Last component(s) version which did _not_ exhibit the problem: xcuitest@4.11.1
- Platform and version under test: iOS 17.0
- Real device or emulator/simulator: simulator

### Link to Appium Logs

https://gist.github.com/klauslaiRC/dfa017ce5d3278a26db48d98ae5fdda2

**Comment by mykola-mokhnach** [comment]
This timeout is defined in your capabilities by `wdaConnectionTimeout`. 
You may try to increase it and see if it helps. Although, it may still not work if XCTest needs more time to fetch the page source. In such case only Apple could improve that (which I don't think they are going to because the visibility attribute is not an "official" one in their framework).

**Comment by klauslaiRC** [comment]
> This timeout is defined in your capabilities by `wdaConnectionTimeout`. You may try to increase it and see if that helps. Although, it may still not work if XCTest needs more time to fetch the page source. In such case only Apple could improve that (which I don't think they are going to do because the visibility attribute is not an "official" one in their framework).

At this time, WDA and the Simulator are almost stuck, and more waiting time is useless

**Comment by klauslaiRC** [comment]
And is there any other property that can replace visible？

**Comment by mykola-mokhnach** [comment]
yes, `hittable` could be added to this driver as well. Please create a feature request

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
