### ISSUE TITLE
[Feat]: Support hittable attribute for xcuitest driver

### ISSUE THREAD

**Issue by klauslaiRC** [appium/appium#19033]
**Is your feature request related to a problem? Please describe.**

[bug: When using complex xpath with attribute @visible='true', there will be AxiosError: timeout of 90000ms exceeded #19030](https://github.com/appium/appium/issues/19030)

**Describe the solution you'd like**
Currently, using the visible attribute in xpath can easily cause WDA to not respond, XCTest provides a similar attribute isHittable, I suggest adding it to the xcuitest driver support list

Apple Doc: https://developer.apple.com/documentation/xctest/xcuielement/1500561-ishittable

**Comment by mykola-mokhnach** [comment]
The `hittable` attribute has been added since xcuitest driver 4.35
See https://github.com/appium/appium-xcuitest-driver/blob/master/docs/element-attributes.md
