### ISSUE TITLE
Continuing without capturing device logs: Failed to receive any data within the timeout: 5000

### ISSUE THREAD

**Issue by mugeunal** [appium/appium#19040]
Server Log : 

CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITest] {}
[DevCon Factory] Releasing connections for F9D4F787-5476-4036-9959-CE20CB8168F4 device on any port number
[DevCon Factory] No cached connections have been found
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [IOSSimulatorLog] Stopping iOS log capture
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1692789027236 (13:10:27 GMT+0200 (Central European Summer Time))
[debug] [W3C] Encountered internal error running command: Error: Simulator architecture is unsupported by the '/var/folders/yz/ssg2f1hj2qlc2ypnsszfzl7w0000gn/T/2023723-13657-nju2mc.mor7h/Getcontact.app' application. Make sure the correct deployment target has been selected for its compilation in Xcode.
[debug] [W3C]     at verifyApplicationPlatform (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/app-utils.js:64:11)
[debug] [W3C]     at XCUITestDriver.installAUT (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:1189:5)
[debug] [W3C]     at XCUITestDriver.start (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:474:7)
[debug] [W3C]     at XCUITestDriver.createSession (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:255:7)
[debug] [W3C]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 32280 ms - 973

--
MacOS v : 13.5.1
Xcode v : 14.3.1 
iPhoneOS v: 16.6
Appium v : 1.22.3

**Comment by mykola-mokhnach** [comment]
This error is expected if you try to run a test on an app which has been built for real devices on simulators. Consider either providing a correct build or changing the type of the target device.

closed as not an issue
