### ISSUE TITLE
unable to connect ios Real device with appium inspector.

### ISSUE THREAD

**Issue by Rushann** [appium/appium#19049]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Giving error code 70 when connecting ios Real device with appium Inspector. If i try to connect simulator WDA is installed automatically but in ios Giving some error code.
![Screenshot 2023-08-24 at 1 12 18 PM](https://github.com/appium/appium/assets/88871439/9ca54989-e46c-4de4-a77e-677954c4f12e)

### Expected Behavior

should needs to install WDA When we try to connect with appium inspector.

### Minimal Reproducible Example

Try to connect iOS real device with appium inspector.

### Environment

- Operating system:Mac
- Appium server version (output of `appium --version`):2
- Appium driver(s) and their version(s):latest
- Appium plugin(s) and their version(s):latest
- Node.js version (output of `node --version`):18.16.1
- `npm` version (output of `npm --version`):9.5.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:iOS
- Real device or emulator/simulator:Real Device

### Link to Appium Logs

[debug] [AppiumDriver@a6b7] Event 'newSessionRequested' logged at 1692862832494 (13:10:32 GMT+0530 (India Standard Time)) [Appium] Attempting to find matching driver for automationName 'XCUITest' and platformName 'iOS' [Appium] The 'xcuitest' driver was installed and matched caps. [Appium] Will require it at /Users/rushan/.appium/node_modules/appium-xcuitest-driver [debug] [Appium] Requiring driver at /Users/rushan/.appium/node_modules/appium-xcuitest-driver [AppiumDriver@a6b7] Appium v2.0.0 creating new XCUITestDriver (v4.32.19) session [AppiumDriver@a6b7] Checking BaseDriver versions for Appium and XCUITestDriver [AppiumDriver@a6b7] Appium's BaseDriver version is 9.3.15 [AppiumDriver@a6b7] XCUITestDriver's BaseDriver version is 9.3.15 [debug] [XCUITestDriver@0b56] Creating session with W3C capabilities: { [debug] [XCUITestDriver@0b56]   "alwaysMatch": { [debug] [XCUITestDriver@0b56]     "platformName": "iOS", [debug] [XCUITestDriver@0b56]     "appium:platformVersion": "16.5.1", [debug] [XCUITestDriver@0b56]     "appium:deviceName": "iPhone Xs Max", [debug] [XCUITestDriver@0b56]     "appium:automationName": "XCUITest", [debug] [XCUITestDriver@0b56]     "appium:bundleId": "com.stunt.dev.application", [debug] [XCUITestDriver@0b56]     "appium:noReset": true, [debug] [XCUITestDriver@0b56]     "appium:udid": "00008020-001279AA1AF2002E", [debug] [XCUITestDriver@0b56]     "appium:xcodeOrgId": "S4353HXJFX", [debug] [XCUITestDriver@0b56]     "appium:xcodeSigningId": "iPhone Developer", [debug] [XCUITestDriver@0b56]     "appium:includeSafariInWebviews": true, [debug] [XCUITestDriver@0b56]     "appium:newCommandTimeout": 3600, [debug] [XCUITestDriver@0b56]     "appium:connectHardwareKeyboard": true [debug] [XCUITestDriver@0b56]   }, [debug] [XCUITestDriver@0b56]   "firstMatch": [ [debug] [XCUITestDriver@0b56]     {} [debug] [XCUITestDriver@0b56]   ] [debug] [XCUITestDriver@0b56] } [XCUITestDriver@0b56 (65771619)] Session created with session id: 65771619-3182-4de5-8bda-feb0b92ad72c [debug] [XCUITest] Current user: 'rushan' [debug] [XCUITestDriver@0b56 (65771619)] Available devices: 00008020-001279AA1AF2002E [debug] [XCUITest] Creating iDevice object with udid '00008020-001279AA1AF2002E' [XCUITestDriver@0b56 (65771619)] Determining device to run tests on: udid: '00008020-001279AA1AF2002E', real device: true [XCUITestDriver@0b56 (65771619)] Normalized platformVersion capability value '16.5.1' to '16.5' [debug] [XCUITestDriver@0b56 (65771619)] Event 'xcodeDetailsRetrieved' logged at 1692862832513 (13:10:32 GMT+0530 (India Standard Time)) [debug] [XCUITestDriver@0b56 (65771619)] Event 'appConfigured' logged at 1692862832513 (13:10:32 GMT+0530 (India Standard Time)) [debug] [XCUITestDriver@0b56 (65771619)] Event 'resetStarted' logged at 1692862832513 (13:10:32 GMT+0530 (India Standard Time)) [debug] [XCUITest] Reset: fullReset not set. Leaving as is [debug] [XCUITestDriver@0b56 (65771619)] Event 'resetComplete' logged at 1692862832513 (13:10:32 GMT+0530 (India Standard Time)) [XCUITestDriver@0b56 (65771619)] Using WDA path: '/Users/rushan/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent' [XCUITestDriver@0b56 (65771619)] Using WDA agent: '/Users/rushan/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj' [debug] [XCUITest] Crash reports root '/Users/rushan/Library/Logs/CrashReporter/MobileDevice/iPhone Xs Max' does not exist. Got nothing to gather. [debug] [XCUITestDriver@0b56 (65771619)] Event 'logCaptureStarted' logged at 1692862832741 (13:10:32 GMT+0530 (India Standard Time)) [XCUITestDriver@0b56 (65771619)] Setting up real device [debug] [XCUITestDriver@0b56 (65771619)] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found [DevCon Factory] Requesting connection for device 00008020-001279AA1AF2002E on local port 8100, device port 8100 [debug] [DevCon Factory] Cached connections count: 0 [DevCon Factory] Successfully requested the connection for 00008020-001279AA1AF2002E:8100 [debug] [XCUITestDriver@0b56 (65771619)] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver' [debug] [WD Proxy] Matched '/status' to command name 'getStatus' [debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [WD Proxy] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] WDA is not listening at 'http://127.0.0.1:8100/' [debug] [XCUITestDriver@0b56 (65771619)] WDA is currently not running. There is nothing to cache [debug] [XCUITestDriver@0b56 (65771619)] Trying to start WebDriverAgent 1 times with 10000ms interval [debug] [XCUITestDriver@0b56 (65771619)] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities [debug] [XCUITestDriver@0b56 (65771619)] Event 'wdaStartAttempted' logged at 1692862833007 (13:10:33 GMT+0530 (India Standard Time)) [XCUITestDriver@0b56 (65771619)] Launching WebDriverAgent on the device [XCUITestDriver@0b56 (65771619)] Cleaning up the WebDriverAgent project after the module upgrade has happened (5.0.0 < 5.5.2) [debug] [XCUITestDriver@0b56 (65771619)] Cleaning the project scheme 'WebDriverAgentLib' to make sure there are no leftovers from previous installs [debug] [XCUITestDriver@0b56 (65771619)] Parsed BUILD_DIR configuration value: '/Users/rushan/Library/Developer/Xcode/DerivedData/WebDriverAgent-bmzmjbvtdvxrdhhadcuciwhfesmf/Build/Products' [debug] [XCUITestDriver@0b56 (65771619)] Got derived data root: '/Users/rushan/Library/Developer/Xcode/DerivedData/WebDriverAgent-bmzmjbvtdvxrdhhadcuciwhfesmf' [debug] [XCUITestDriver@0b56 (65771619)] Cleaning the project scheme 'WebDriverAgentRunner' to make sure there are no leftovers from previous installs [debug] [WebDriverAgent] Killing running processes 'xcodebuild.*00008020-001279AA1AF2002E' for the device 00008020-001279AA1AF2002E... [debug] [WebDriverAgent] 'pgrep -if xcodebuild.*00008020-001279AA1AF2002E' didn't detect any matching processes. Return code: 1 [debug] [WebDriverAgent] Generating xcode config file for orgId 'S4353HXJFX' and signingId 'iPhone Developer' [debug] [WebDriverAgent] Writing xcode config file to /var/folders/b7/_gnptsqx6k33xn10c33d39h00000gn/T/2023724-15154-25s7ux.l40zr/appium-temp.xcconfig [debug] [XCUITestDriver@0b56 (65771619)] Using Xcode configuration file: '/var/folders/b7/_gnptsqx6k33xn10c33d39h00000gn/T/2023724-15154-25s7ux.l40zr/appium-temp.xcconfig' [debug] [XCUITestDriver@0b56 (65771619)] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/rushan/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/rushan/Library/Developer/Xcode/DerivedData/WebDriverAgent-bmzmjbvtdvxrdhhadcuciwhfesmf -destination id=00008020-001279AA1AF2002E IPHONEOS_DEPLOYMENT_TARGET=16.5 -xcconfig /var/folders/b7/_gnptsqx6k33xn10c33d39h00000gn/T/2023724-15154-25s7ux.l40zr/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Users/rushan/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent' [debug] [XCUITestDriver@0b56 (65771619)] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability [debug] [XCUITestDriver@0b56 (65771619)] Waiting up to 60000ms for WebDriverAgent to start [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [Xcode] xcodebuild exited with code '70' and signal 'null' [XCUITestDriver@0b56 (65771619)] Launching WebDriverAgent on the device [XCUITestDriver@0b56 (65771619)] Cleaning up the WebDriverAgent project after the module upgrade has happened (5.0.0 < 5.5.2) [debug] [XCUITestDriver@0b56 (65771619)] Cleaning the project scheme 'WebDriverAgentLib' to make sure there are no leftovers from previous installs [debug] [XCUITestDriver@0b56 (65771619)] Cleaning the project scheme 'WebDriverAgentRunner' to make sure there are no leftovers from previous installs [debug] [WebDriverAgent] Killing running processes 'xcodebuild.*00008020-001279AA1AF2002E' for the device 00008020-001279AA1AF2002E... [debug] [WebDriverAgent] 'pgrep -if xcodebuild.*00008020-001279AA1AF2002E' didn't detect any matching processes. Return code: 1 [debug] [XCUITestDriver@0b56 (65771619)] Using Xcode configuration file: '/var/folders/b7/_gnptsqx6k33xn10c33d39h00000gn/T/2023724-15154-25s7ux.l40zr/appium-temp.xcconfig' [debug] [XCUITestDriver@0b56 (65771619)] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/rushan/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/rushan/Library/Developer/Xcode/DerivedData/WebDriverAgent-bmzmjbvtdvxrdhhadcuciwhfesmf -destination id=00008020-001279AA1AF2002E IPHONEOS_DEPLOYMENT_TARGET=16.5 -xcconfig /var/folders/b7/_gnptsqx6k33xn10c33d39h00000gn/T/2023724-15154-25s7ux.l40zr/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Users/rushan/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent' [debug] [XCUITestDriver@0b56 (65771619)] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability [debug] [XCUITestDriver@0b56 (65771619)] Waiting up to 60000ms for WebDriverAgent to start [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [debug] [XCUITestDriver@0b56 (65771619)] Matched '/status' to command name 'getStatus' [debug] [XCUITestDriver@0b56 (65771619)] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body [debug] [iProxy@00008020:8100] Connection was refused to port 8100 [XCUITestDriver@0b56 (65771619)] socket hang up [Xcode] xcodebuild exited with code '70' and signal 'null' [debug] [XCUITestDriver@0b56 (65771619)] Event 'wdaStartFailed' logged at 1692862858925 (13:10:58 GMT+0530 (India Standard Time)) [debug] [XCUITestDriver@0b56 (65771619)] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70 [debug] [XCUITestDriver@0b56 (65771619)] xcodebuild error message: [debug] [XCUITestDriver@0b56 (65771619)] . Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device. [XCUITestDriver@0b56 (65771619)] Quitting and uninstalling WebDriverAgent [XCUITestDriver@0b56 (65771619)] Shutting down sub-processes [debug] [XCUITestDriver@0b56 (65771619)] No WDAs on the device. [XCUITestDriver@0b56 (65771619)] {} [DevCon Factory] Releasing connections for 00008020-001279AA1AF2002E device on any port number [DevCon Factory] Found cached connections to release: ["00008020-001279AA1AF2002E:8100"] [DevCon Factory] Releasing the listener for '00008020-001279AA1AF2002E:8100' [debug] [iProxy@00008020:8100] Closing the connection [debug] [DevCon Factory] Cached connections count: 0 [debug] [XCUITestDriver@0b56 (65771619)] Not clearing log files. Use `clearSystemFiles` capability to turn on. [iProxy@00008020:8100] The connection has been closed [debug] [AppiumDriver@a6b7] Event 'newSessionStarted' logged at 1692862859139 (13:10:59 GMT+0530 (India Standard Time)) [debug] [AppiumDriver@a6b7] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70 [debug] [AppiumDriver@a6b7] xcodebuild error message: [debug] [AppiumDriver@a6b7] . Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device. [debug] [AppiumDriver@a6b7]     at quitAndUninstall (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:808:15) [debug] [AppiumDriver@a6b7]     at /Users/rushan/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:894:13 [debug] [AppiumDriver@a6b7]     at wrapped (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:95:13) [debug] [AppiumDriver@a6b7]     at retry (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:68:13) [debug] [AppiumDriver@a6b7]     at retryInterval (/Users/rushan/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:105:10) [debug] [AppiumDriver@a6b7]     at /Users/rushan/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:833:7

**Comment by jlipps** [comment]
Run with `appium:showXcodeLog` capability set to true, and look for errors in the xcode output.

**Comment by Rushann** [comment]
@jlipps I am getting this error when running tests in my real iphone device. 

Last login: Fri Aug 25 10:06:09 on ttys002
rushan@Rushans-Mac-mini ~ % appium
[Appium] Welcome to Appium v2.0.0
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at /Users/rushan/.appium/node_modules/appium-xcuitest-driver
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /Users/rushan/.appium/node_modules/appium-uiautomator2-driver
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLS in your client code to connect to this server:
[Appium] 	http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] 	http://192.168.1.4:4723/
[Appium] Available drivers:
[Appium]   - xcuitest@4.32.19 (automationName 'XCUITest')
[Appium]   - uiautomator2@2.29.2 (automationName 'UiAutomator2')
[Appium] Available plugins:
[Appium]   - execute-driver@3.0.14
[Appium]   - element-wait@2.0.3
[Appium]   - gestures@3.0.0
[Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate
[HTTP] --> POST /session
[HTTP] {"desiredCapabilities":{"noReset":true,"platformVersion":"16.5.1","automationName":"00008020-001279AA1AF2002E","bundleId":"iPhone Developer","platformName":"iOS","deviceName":"iPhone Xs Max"},"capabilities":{"firstMatch":[{"appium:automationName":"00008020-001279AA1AF2002E","appium:bundleId":"iPhone Developer","appium:deviceName":"iPhone Xs Max","appium:noReset":true,"platformName":"ios","appium:platformVersion":"16.5.1"}]}}
[debug] [AppiumDriver@c4c0] Calling AppiumDriver.createSession() with args: [{"noReset":true,"platformVersion":"16.5.1","automationName":"00008020-001279AA1AF2002E","bundleId":"iPhone Developer","platformName":"iOS","deviceName":"iPhone Xs Max"},null,{"firstMatch":[{"appium:automationName":"00008020-001279AA1AF2002E","appium:bundleId":"iPhone Developer","appium:deviceName":"iPhone Xs Max","appium:noReset":true,"platformName":"ios","appium:platformVersion":"16.5.1"}]}]
[debug] [AppiumDriver@c4c0] Event 'newSessionRequested' logged at 1692946204666 (12:20:04 GMT+0530 (India Standard Time))
[Appium] Attempting to find matching driver for automationName '00008020-001279AA1AF2002E' and platformName 'ios'
[debug] [AppiumDriver@c4c0] Event 'newSessionStarted' logged at 1692946204670 (12:20:04 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@c4c0] Encountered internal error running command: Error: Could not find a driver for automationName '00008020-001279AA1AF2002E' and platformName 'ios'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)
[debug] [AppiumDriver@c4c0]     at DriverConfig.findMatchingDriver (/usr/local/lib/node_modules/appium/lib/extension/driver-config.js:175:13)
[debug] [AppiumDriver@c4c0]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:273:29)
[debug] [AppiumDriver@c4c0]     at commandExecutor (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:107:18)
[debug] [AppiumDriver@c4c0]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:124:15)
[debug] [AppiumDriver@c4c0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [AppiumDriver@c4c0]     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:680:16)
[debug] [AppiumDriver@c4c0]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:774:16)
[debug] [AppiumDriver@c4c0]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:696:17)
[debug] [AppiumDriver@c4c0]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:393:19)
[HTTP] <-- POST /session 500 40 ms - 1052
[HTTP] 




FAILED CONFIGURATION: @BeforeSuite com.stunt.base.BaseClass.initialization
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName '00008020-001279AA1AF2002E' and platformName 'ios'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Rushans-Mac-mini.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.4.1', java.version: '17.0.7'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName '00008020-001279AA1AF2002E' and platformName 'ios'. Have you installed a driver that supports those capabilities? Run 'appium driver list --installed' to see. (Lower-level error: Could not find installed driver to support given caps)
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1073:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:491:57)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Rushans-Mac-mini.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.4.1', java.version: '17.0.7'
Driver info: driver.version: IOSDriver

**Comment by eglitise** [comment]
@Rushann your capabilities are incorrect here: `automationName` should be `XCUITest`, `bundleId` should be your application bundle ID, etc. The ones in your first screenshot look correct, so try setting the same ones.

**Comment by KazuCocoa** [comment]
Right, the attached one in https://github.com/appium/appium/issues/19049#issuecomment-1692858967 had wrong capabilities.

> [HTTP] {"desiredCapabilities":{"noReset":true,"platformVersion":"16.5.1","automationName":"00008020-001279AA1AF2002E","bundleId":"iPhone Developer","platformName":"iOS","deviceName":"iPhone Xs Max"},"capabilities":{"firstMatch":[{"appium:automationName":"00008020-001279AA1AF2002E","appium:bundleId":"iPhone Developer","appium:deviceName":"iPhone Xs Max","appium:noReset":true,"platformName":"ios","appium:platformVersion":"16.5.1"}]}}


- automationName should be xcuitest
- udid should exist
- `showXcodeLog` also as requested to check the xcodebuild's log

etc

It seems like the `xcodebuild` was not able to detect the device (from the original report)

> codebuild build-for-testing test-without-building -project /Users/rushan/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/rushan/Library/Developer/Xcode/DerivedData/WebDriverAgent-bmzmjbvtdvxrdhhadcuciwhfesmf -destination id=00008020-001279AA1AF2002E IPHONEOS_DEPLOYMENT_TARGET=16.5 -xcconfig /var/folders/b7/_gnptsqx6k33xn10c33d39h00000gn/T/2023724-15154-25s7ux.l40zr/appium-temp.xcconfig GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO

I guess the xcodebuild was not able to handle `destination` arg well (as the xcodebuild internally)

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
