### ISSUE TITLE
Need assistance to automate a automate/inspect the Assistive Touch(floating button) Button in iPhone using Selenium Appium C# 

### ISSUE THREAD

**Issue by pallavichandrashekarjetty** [appium/appium#19057]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Appium AssistiveTouch Button](https://github.com/appium/appium/assets/79142459/e7a1a643-f156-4587-b0cd-dfe5a934a70c)

### Expected Behavior

I am trying to automate/inspect the Assistive Touch(floating button) Button in iPhone using Selenium Appium C#. However, I am unable to obtain the web element for it. I also attempted to tap on specific X and Y coordinates, but no luck :(

If anyone has succeded on this please let me know.

### Minimal Reproducible Example

![Appium AssistiveTouch Button](https://github.com/appium/appium/assets/79142459/0017a5eb-3ffe-4d6f-9d03-17d613e77e64)

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by eglitise** [comment]
For what it's worth, Appium Inspector also does not see this button, so Apple probably isn't exposing it. Tapping on its coordinates does work, though.

**Comment by pallavichandrashekarjetty** [comment]
The floating point will not be in the same position always.. I didn't find a way to automate the same.

**Comment by mykola-mokhnach** [comment]
If the element is not exposed to the accessibility layer then there is no way XCTest can detect it. Please report the issue to Apple

**Comment by pallavichandrashekarjetty** [comment]
@mykola-mokhnach Is there a platform where I can report the same?

**Comment by mykola-mokhnach** [comment]
https://developer.apple.com/bug-reporting/ ?

**Comment by pallavichandrashekarjetty** [comment]
Just reported and will get back to you!

Thanks!
Pallavi

**Comment by KazuCocoa** [comment]
Yea, assistive touch is not detectable
