### ISSUE TITLE
Appium works very slowly ONLY with Android 9+

### ISSUE THREAD

**Issue by Skala05reg** [appium/appium#19069]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello everyone! I have Appium 2.1.1 on my computer and installed UIAutomator2 on it. I automate physical devices via C# with Appium library, some of them have Android 8.1.0 and some have Android 9 and 10. Items are found and clicked on all the handsets, however:
On Android 8.1.0 the item is detected almost instantly, but on Android 9/10 the click takes 30-40 seconds. To be more precise, first the http request to the server goes 10 seconds, the element is detected, and then the response request goes to C# also a few seconds. Then http-request for click is sent, after 15 seconds the click itself happens on the phone, and after 15 seconds there is http-request that the click was successful.

### Expected Behavior

Regardless of the Android version, clicks are expected to be made almost instantly, just like on Android 8.1.0
Phones are recognized by the computer, with the 'adb devices' command all displayed. Clicks also happen on all versions, just very slow on Android 9/10

### Minimal Reproducible Example

Logs from Appium Console
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Available contexts: ["NATIVE_APP"]
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /session/9936cb70-d9eb-430e-b23c-107e941c0a08/contexts 200 152 ms - 24
[HTTP]
[debug] [HTTP] Request idempotency key: 8ec4b7a0-7132-4c17-9e9a-6aa0c4df7422
[HTTP] --> POST /session/9936cb70-d9eb-430e-b23c-107e941c0a08/context
[HTTP] {"name":null}
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Calling AppiumDriver.setContext() with args: [null,"9936cb70-d9eb-430e-b23c-107e941c0a08"]
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /session/9936cb70-d9eb-430e-b23c-107e941c0a08/context 200 10 ms - 14
[HTTP]
[debug] [HTTP] Request idempotency key: ace0680b-24b7-4147-bbfd-5edfbc9be058
[HTTP] --> POST /session/9936cb70-d9eb-430e-b23c-107e941c0a08/element
[HTTP] {"using":"xpath","value":"//*[@text='Download']"}
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Calling AppiumDriver.findElement() with args: ["xpath","//*[@text='Download']","9936cb70-d9eb-430e-b23c-107e941c0a08"]
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Waiting up to 1000 ms for condition
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Matched '/element' to command name 'findElement'
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Proxying [POST /element] to [POST http://127.0.0.1:8200/session/a73dc6b4-fd0c-42d5-8e3f-f9ad2bd6afa1/element] with body: {"strategy":"xpath","selector":"//*[@text='Download']","context":"","multiple":false}
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Got response with status 200: {"sessionId":"a73dc6b4-fd0c-42d5-8e3f-f9ad2bd6afa1","value":{"ELEMENT":"00000000-0000-0235-ffff-ffff00000047","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0235-ffff-ffff00000047"}}
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0235-ffff-ffff00000047","ELEMENT":"00000000-0000-0235-ffff-ffff00000047"}
[HTTP] <-- POST /session/9936cb70-d9eb-430e-b23c-107e941c0a08/element 200 12403 ms - 137
[HTTP]
[debug] [HTTP] Request idempotency key: d3531be5-8c94-4924-978e-d81f46aac7a4
[HTTP] --> POST /session/9936cb70-d9eb-430e-b23c-107e941c0a08/element/00000000-0000-0235-ffff-ffff00000047/click
[HTTP] {}
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Calling AppiumDriver.click() with args: ["00000000-0000-0235-ffff-ffff00000047","9936cb70-d9eb-430e-b23c-107e941c0a08"]
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Matched '/element/00000000-0000-0235-ffff-ffff00000047/click' to command name 'click'
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Proxying [POST /element/00000000-0000-0235-ffff-ffff00000047/click] to [POST http://127.0.0.1:8200/session/a73dc6b4-fd0c-42d5-8e3f-f9ad2bd6afa1/element/00000000-0000-0235-ffff-ffff00000047/click] with body: {"element":"00000000-0000-0235-ffff-ffff00000047"}
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Got response with status 200: {"sessionId":"a73dc6b4-fd0c-42d5-8e3f-f9ad2bd6afa1","value":null}
[debug] [AndroidUiautomator2Driver@07d8 (9936cb70)] Responding to client with driver.click() result: null
[HTTP] <-- POST /session/9936cb70-d9eb-430e-b23c-107e941c0a08/element/00000000-0000-0235-ffff-ffff00000047/click 200 30236 ms - 14

I have posted the full log since the Appium server started here - https://pastebin.com/RWxZgY9d

I also made a C# script that displays the start time of the search, the time at which the http request to find the item arrived, and the time the request to click on the item arrived:
27.08.2023 14:22:48 - starting to find element
27.08.2023 14:23:00 - element found, starting to click
27.08.2023 14:23:31 - element clicked

### Environment

- Operating system: Windows 10
- Appium server version (output of `appium --version`): Appium v2.1.1
- Appium driver(s) and their version(s): UiAutomator2@2.29.5
- Appium plugin(s) and their version(s): no
- Node.js version (output of `node --version`): v18.17.1
- `npm` version (output of `npm --version`): 9.6.7
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: C#, Appium libriary
- Real device or emulator/simulator: Android 8.1.0, Android 9, Android 10, all are physical devices

**Comment by mykola-mokhnach** [comment]
Try https://github.com/appium/appium-uiautomator2-driver#poor-elements-interaction-performance

**Comment by Skala05reg** [comment]
> Try https://github.com/appium/appium-uiautomator2-driver#poor-elements-interaction-performance

Thanks a lot! Do you know how to enable this option in C#? I found this in sources, bot can not connect this to my project
![image](https://github.com/appium/appium/assets/99641472/e0dbde63-e97b-44da-99c8-0e684c686b09)

**Comment by Skala05reg** [comment]
> Try https://github.com/appium/appium-uiautomator2-driver#poor-elements-interaction-performance

You are a legend, this worked in my case. Thanks!=)
