### ISSUE TITLE
Wich version of Jdk, selenium webdriver and appium are compatible? 

### ISSUE THREAD

**Issue by Maximiliano-Consiss** [appium/appium#19076]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Now i´m using java 1.8.0, appium 8.2.1 and Selenium webdriver  4.1.0

Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 

### Expected Behavior

I want to test a desktop aplication and  I think that the versions are not compatible, I dont find any set of versions that are compatible

### Minimal Reproducible Example

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.windows.WindowsDriver;

public class TestClassAppium {

	public static void main (String[] args) throws InterruptedException, MalformedURLException {

		  DesiredCapabilities cap = new DesiredCapabilities();
		  cap.setCapability("app", "C:\\Windows\\System32\\calc.exe");
		  
		  WindowsDriver driver = new WindowsDriver(new URL("http://127.0.0.1:4723/"),cap);
		  
		  Thread.sleep(5000);
		  
		  driver.quit();
		
	}
	
	
}

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
https://github.com/appium/java-client?tab=readme-ov-file#compatibility-matrix may help to check the compatibility
