### ISSUE TITLE
Support edge browser on android

### ISSUE THREAD

**Issue by dileepkusuma** [appium/appium#19075]
Support automating Microsoft edge browser on android.

**Comment by mykola-mokhnach** [comment]
Could you please be more concrete about it? Does Microsoft provide a WebDriver-compatible driver for mobile version of it? Or maybe Chromedriver supports Edge? It is obvious that such task cannot be done if the vendor support is missing.

**Comment by dileepkusuma** [comment]
Not sure whether the existing msedgedriver supports mobile or not. I have contacted the edge team regarding that. I wanted to create a ticket in appium-uiautomator2-driver, but the repo description states that the ticket should be created here. I tried to use uiautomator2 to auotmate edge android app UI automation, but it didn't work.

**Comment by KazuCocoa** [comment]
The edge was not debuggable so it was not able to establish a chromedriver/edgedriver session with it. I have double checked with latest edgedriver.

e.g.
```
server_url = 'http://localhost:9515'
caps = {
  "platformName": "android",
  "browserName": :msedge,
  "ms:edgeOptions": {
    androidPackage: "com.microsoft.emmx",
    androidDeviceSerial: "D0AA002182JC0202126",
    androidActivity: "org.chromium.chrome.browser.ChromeTabbedActivity"
  }
}
```

```
Selenium::WebDriver::Error::UnknownError: unknown error: Failed to get sockets matching: @weblayer_devtools_remote_.*5334
  (make sure the app has its WebView/WebLayer configured for debugging)
from 0   msedgedriver                        0x0000000100f08f88 msedgedriver + 5177224
```

`chrome://inspect` was available so DevTools Protocol might work but this is not current WebDriver based automation method in Appium.

Some contents drawn by edge are available via NATIVE_APP though.

**Comment by mykola-mokhnach** [comment]
If devtools are supported then https://github.com/dlenroc/appium-html-driver might be a solution.
Otherwise if chromedriver does not support edge then there is not much we could do there. And we don't have any plans yet about creating more drivers

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Thanks for checking it

**Comment by jlipps** [comment]
did not know about appium-html-driver. cool project @dlenroc !
