### ISSUE TITLE
[Feat]:how to setup ios device in windows10 pc

### ISSUE THREAD

**Issue by venkatprassu** [appium/appium#19070]
Hello Appium Team,

I am seeking assistance on setting up automation testing for an iOS mobile device using a Windows 10 PC. Could you please provide guidance on the required properties and software installations for Windows 10?
i am already running android mobile automation on same windows10 pc.

Thank you.

**Comment by KazuCocoa** [comment]
We support only macOS for the XCUITest driver usage officially.
https://appium.github.io/appium-xcuitest-driver/4.35/setup/#requirements

**Comment by venkatprassu** [comment]
Hi
If Appium is crashing and closing automatically when you try to run Appium  with the provided desired capabilities.How to resolve it.
Desire capabilities.
{
  "platformName": "ios",
  "deviceName": "iPhone7",
  "platformVersion": "15.7.8",
  "udid": "MN8X2HN/A",
  "automationName": "XCUITest",
  "app": "D:\\ViscenarioGoNewDesign.ipa"
}
Please help me how to resolve this?

**Comment by KazuCocoa** [comment]
https://discuss.appium.io/ may help to ask questions if someone tried to run ios automation on Windows
