### ISSUE TITLE
driver stuck after executing 'mobile: deeplink' script 

### ISSUE THREAD

**Issue by bronik** [appium/appium#19085]
Hi everyone!
I'm trying to open my app with deeplink, but after dialog displayed - driver stucks for a while
actually, after native dialog displayed - I can't do nothing with the app
I'm talking about this dialog: 
![Знімок екрана 2023-08-30 о 09 16 58](https://github.com/appium/appium/assets/19311882/f7a6e047-a7e4-4f29-ad03-7e6175ff8751)

I'm using:
Appium v1.22.3 
XCUITestDriver v4.35.0
webdriveragent 5.8.2
iPhone 14 Pro 16.4 iOS (simulator)

some logs:
https://gist.github.com/bronik/1ddeb8db7b929f8d245c79faffe1a551

does it works only for real device? I can't google some useful info, can someone help me?

**Comment by mykola-mokhnach** [comment]
We do not support Appium 1 anymore. Please update to Appium 2 and make sure you have the most recent driver version installed to try again.

**Comment by mykola-mokhnach** [comment]
You could also try to invoke [nativateTo](https://www.w3.org/TR/webdriver2/#dfn-navigate-to) API as a possible workaround
