### ISSUE TITLE
Nominations Needed For Appium CPC Voting Members

### ISSUE THREAD

**Issue by bensternthal** [appium/appium#19084]
This issue tracks the nomination of two persons to serve as CPC voting members. More information can be found in the following tracking issue. 

https://github.com/openjs-foundation/cross-project-council/issues/1143

Note I did ping a few folks in the above issue and slack, I am filing the issue here in hopes it gets more 👀 

Please comment on the above issue once you have made a final selection.

**Comment by jlipps** [comment]
Thanks @bensternthal. The current voting members are no longer with the project. We'll have a chat and get back to you.

**Comment by KazuCocoa** [comment]
I can help this ✋

**Comment by jlipps** [comment]
@bensternthal I'll also volunteer. That's two!

**Comment by bensternthal** [comment]
Got it, thanks @jlipps & @KazuCocoa !
