### ISSUE TITLE
Not able to use --bootstrap-port

### ISSUE THREAD

**Issue by Prajwalgn-07** [appium/appium#19100]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 The given Node.js executable: /opt/homebrew/bin/node Arguments: [/opt/homebrew/lib/node_modules/appium/build/lib/main.js, --port, 15778, --address, 0.0.0.0, --log, /Users/prajwal/Desktop/TestVagrant/ekam repos/ekam-examples/build/ekam-execution-timeline/LoginTests/loginWithValidCredentials/logs/appium.log, --bootstrap-port, 62289, --session-override,] 
Process output: 
[ERROR] Unrecognized arguments: --bootstrap-port 62289

### Expected Behavior

The server should run

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by Prajwalgn-07** [comment]
I'm using `appium --version 2.1.3`

**Comment by jlipps** [comment]
That's an android specific CLI flag which no longer exists in Appium 2. See the [migration guide](https://appium.io/docs/en/2.1/guides/migrating-1-to-2/#driver-specific-command-line-options). You should use a default capability instead. (But in any case bootstrapPort was only for the only uiautomator 1 driver, which is no longer supported). Whatever's suggesting that you use `--bootstrap-port` is way out of date.

**Comment by Prajwalgn-07** [comment]
@jlipps Thanks for the info, I have attached the snippet of what we are trying to achieve can u share any alternative way
```
    AppiumServiceBuilder appiumServiceBuilder =
        new AppiumServiceBuilder()
            .withArgument(SESSION_OVERRIDE)
            .usingAnyFreePort()
           .withArgument(
               AndroidServerFlag.BOOTSTRAP_PORT_NUMBER,
               String.valueOf(randomOpenPortOnAllLocalInterfaces()))
            .withArgument(
                AppiumServerFlags.WDA_PORT, String.valueOf(randomOpenPortOnAllLocalInterfaces()))
            .withLogFile(new File(logFilePath));
```

**Comment by Prajwalgn-07** [comment]
@jlipps anything on the above?, when I use `appium server --driver-uiautomator2-webdriveragent-port 8104` the appium server will start but same when I try with other driver its not able to recognise, any leads?
```
➜  appium server --driver-uiautomator2-webdriveragent-port 8104

[ERROR] Unrecognized arguments: --driver-uiautomator2-webdriveragent-port 8104
```

**Comment by KazuCocoa** [comment]
> For example, the XCUITest driver used to expose a parameter --webdriveragent-port. 

I assume you tried the XCUITest example. Have you tried "bootstrap-port"?

**Comment by Prajwalgn-07** [comment]
@KazuCocoa From 2.0 its giving unrecognized arguments, as @jlipps explained its deprecated, for xcui test I'm using as you said `WDA_PORT("--driver-xcuitest-webdriveragent-port")`  its working fine but for uiautomator2 I'm not sure how it can be done in 2.0

**Comment by jlipps** [comment]
I don't know how to do this using the java client appium service builder. I don't use that feature myself. You could ask in the forums how to set default capabilities in the java appium service builder.
