### ISSUE TITLE
bug: device not found that starts with numbers

### ISSUE THREAD

**Issue by iPurya** [appium/appium#19109]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is output of `adb devices` :

97ca6ac00506    device
E65HIZDIRCXG7TBM        device
R9JN30FAR7J     device
R9JR406LL8J     device
UW4TZTJVUKEUNN6D        device

but in appium logs i can see this result:
Connected devices: [{"udid":"E65HIZDIRCXG7TBM","state":"device"},{"udid":"R9JN30FAR7J","state":"device"},{"udid":"R9JR406LL8J","state":"device"},{"udid":"UW4TZTJVUKEUNN6D","state":"device"}]

you can see its not detecting first device named 97ca6ac00506    

and after that when i want to connect to this device i see:

Encountered internal error running command: Error executing adbExec. Original error: 'Command '/usr/lib/android-sdk/platform-tools/adb -P 5037 -s 97ca6ac00506 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 1'; Command output: error: device '97ca6ac00506' not found

### Expected Behavior

i tested on windows and its working fine. but on ubuntu server 23.04 i got this.

### Minimal Reproducible Example

Appium v2.1.3
uiautomator2@2.29.5
caps : {
  "platformName": "Android",
  "appium:deviceName": "97ca6ac00506",
  "appium:udid": "97ca6ac00506",
  "appium:automationName": "UiAutomator2",
  "appium:newCommandTimeout": 1200
}

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Please provide the full server log and the output of `adb devices` with -l option. It might be the device is present in the list, but is offline

**Comment by iPurya** [comment]
i think its adb version issue i use 34 on windows and its ok but on my raspberry its 29 and this happens.
i tried to install latest version of platform tools but no one compiled latest version on aarch64 architect :(

**Comment by iPurya** [comment]
i just found this repo : https://github.com/nmeum/android-tools
and build latest version of adb and my problem fixed.
