### ISSUE TITLE
bug: <when use idb and ffmepg to record video, Appium Session lose>

### ISSUE THREAD

**Issue by boumelon** [appium/appium#19122]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When use Appium to start the session and open app in iOS, connection will lost after using idb and ffmepg command to record video in java process. At the same time, Xcode will occur connection lost issue. If i open WDA again by manual in iPhone, tests again and connection will be normal. I tied switching port for WDA, unluckily it's the same result. Have any ideas for this, graceful for advice.

### Expected Behavior

test normal when use this way to record video.

### Minimal Reproducible Example

command in java process:
/opt/homebrew/bin/idb video-stream --fps 25 --format h264 --udid ***** | /opt/homebrew/bin/ffmpeg -i - -f h264 -b 600k -framerate 30 /Applications/1693988735965.mp4

Appium log:
[Xcode] xcodebuild exited with code '65' and signal 'null' [HTTP] --> GET /session/f70eef73-ef99-4341-822f-d285d74a8614/timeouts [HTTP] {} [debug] [AppiumDriver@8f28] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started [debug] [AppiumDriver@8f28] at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:315:15) [debug] [AppiumDriver@8f28] at /opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:518:15 [debug] [AppiumDriver@8f28] at Layer.handle [as handle_request] (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5) [debug] [AppiumDriver@8f28] at next (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/route.js:144:13) [debug] [AppiumDriver@8f28] at Route.dispatch (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/route.js:114:3) [debug] [AppiumDriver@8f28] at Layer.handle [as handle_request] (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5) [debug] [AppiumDriver@8f28] at /opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:15 [debug] [AppiumDriver@8f28] at param (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14) [debug] [AppiumDriver@8f28] at param (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:376:14) [debug] [AppiumDriver@8f28] at Function.process_params (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:421:3) [debug] [AppiumDriver@8f28] at next (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10) [debug] [AppiumDriver@8f28] at logger (/opt/homebrew/lib/node_modules/appium/node_modules/morgan/index.js:144:5) [debug] [AppiumDriver@8f28] at Layer.handle [as handle_request] (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5) [debug] [AppiumDriver@8f28] at trim_prefix (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13) [debug] [AppiumDriver@8f28] at /opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9 [debug] [AppiumDriver@8f28] at Function.process_params (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12) [debug] [AppiumDriver@8f28] at next (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:280:10) [debug] [AppiumDriver@8f28] at jsonParser (/opt/homebrew/lib/node_modules/appium/node_modules/body-parser/lib/types/json.js:113:7) [debug] [AppiumDriver@8f28] at Layer.handle [as handle_request] (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5) [debug] [AppiumDriver@8f28] at trim_prefix (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:328:13) [debug] [AppiumDriver@8f28] at /opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:286:9 [debug] [AppiumDriver@8f28] at Function.process_params (/opt/homebrew/lib/node_modules/appium/node_modules/express/lib/router/index.js:346:12) [HTTP] GET /session/66e1fdca-4e8c-418e-a0d1-6d98779b874c/screenshot

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
I believe idb physically resets the connection to the device upon video recording startup, so the above behaviour is expected. Try maybe to start video recording before the xcuitest session. Or restart the session with noReset afterwards.

**Comment by boumelon** [comment]
> I believe idb physically resets the connection to the device upon video recording startup, so the above behaviour is expected. Try maybe to start video recording before the xcuitest session. Or restart the session with noReset afterwards.
thanks, u are right. It works if start video recording before the Appium session.

**Comment by boumelon** [comment]
> I believe idb physically resets the connection to the device upon video recording startup, so the above behaviour is expected. Try maybe to start video recording before the xcuitest session. Or restart the session with noReset afterwards.
noReset doesn't work. In addition, videos output by idb and ffmpeg would crash if I click forward or drag timeline.
