### ISSUE TITLE
bug: Appium can't get Text propriety

### ISSUE THREAD

**Issue by Correia87** [appium/appium#19127]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have an Android app where sometimes Appium can get the text and other times even though the text is on the screen, Appium can't get that text. I've tried setting a 60-second wait, but it still sometimes fails.

### Expected Behavior

Let Appium always get the full context

### Minimal Reproducible Example

 UiAutomator2Options options = new UiAutomator2Options();
        options.setDeviceName("7.4 Rollable API 30");
        options.setApp(System.getProperty("C:\\APK\\mayApp.apk"));
        options.setPlatformName("Android");
        options.setAutomationName("UiAutomator2");
        // options.setAppPackage("oracle.retail.sim.mobile.client.SimMobile");
        // options.setCapability("appActivity", "oracle.retail.sim.mobile.client.SimMobile");
        options.setCapability("autoGrantPermissions", "true");
        options.setPrintPageSourceOnFindFailure(true);

### Environment

- Operating system: Android
- Appium server version (output of `appium --version`): V2.1.3
- Appium driver(s) and their version(s):UiAutomator 2.29.5
- Appium plugin(s) and their version(s):8.1.5
- Node.js version (output of `node --version`):18.12.1
- `npm` version (output of `npm --version`):8.19.2
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Android SDK 30
- Real device or emulator/simulator:Emulator/simulator

**Comment by KazuCocoa** [comment]
Please attache the full appium log

**Comment by Correia87** [comment]
the Text como with "-" but the real text is "1010 - Store Name -`[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                                             <android.view.View index="0" package="oracle.retail.sim.mobile.client.SimMobile" class="android.view.View" text="-" resource-id="lv1:5:li1" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,372][1600,475]" displayed="true" hint="Store List" />
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                                             <android.view.View index="1" package="oracle.retail.sim.mobile.client.SimMobile" class="android.view.View" text="-" resource-id="lv1:1:li1" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,472][1600,577]" displayed="true" hint="Store List" />
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                                             <android.view.View index="2" package="oracle.retail.sim.mobile.client.SimMobile" class="android.view.View" text="-" resource-id="lv1:2:li1" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,574][1600,679]" displayed="true" hint="Store List" />
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                                             <android.view.View index="3" package="oracle.retail.sim.mobile.client.SimMobile" class="android.view.View" text="-" resource-id="lv1:3:li1" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,674][1600,779]" displayed="true" hint="Store List" />
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                                             <android.view.View index="4" package="oracle.retail.sim.mobile.client.SimMobile" class="android.view.View" text="-" resource-id="lv1:4:li1" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,777][1600,882]" displayed="true" hint="Store List" />
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                                             <android.view.View index="5" package="oracle.retail.sim.mobile.client.SimMobile" class="android.view.View" text="-" resource-id="lv1:0:li1" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,879][1600,987]" displayed="true" hint="Store List" />
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                                           </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                                         </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                                       </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                                     </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                                   </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                                 </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                               </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                             </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                           </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                         </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                       </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                     </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                   </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                   <android.view.View index="1" package="oracle.retail.sim.mobile.client.SimMobile" class="android.view.View" text="" resource-id="amx-loading-live-region" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[0,63][1600,2302]" displayed="true" hint="" />
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                                 </android.view.View>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                               </android.webkit.WebView>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                             </android.webkit.WebView>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                           </android.widget.RelativeLayout>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                         </android.widget.LinearLayout>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                       </android.widget.FrameLayout>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                     </android.widget.FrameLayout>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                   </android.widget.LinearLayout>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]                 </android.widget.RelativeLayout>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]               </android.widget.LinearLayout>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]             </android.widget.LinearLayout>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]           </android.widget.RelativeLayout>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]         </android.widget.TabHost>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]       </android.widget.FrameLayout>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]     </android.widget.LinearLayout>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]   </android.widget.FrameLayout>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)] </hierarchy>
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]     at AndroidUiautomator2Driver.findElOrEls (C:\Users\a\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.js:75:11)
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]     at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\Users\a\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:60:12)
[debug] [AndroidUiautomator2Driver@eaa1 (87d09199)]     at AndroidUiautomator2Driver.findElement (C:\Users\a\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:75:12)`

**Comment by jlipps** [comment]
@Correia87 please link to a gist of your full appium logs

**Comment by mykola-mokhnach** [comment]
Closed because of no response
