### ISSUE TITLE
Help: flutter_driver can't find material for automated testing of desktop applications

### ISSUE THREAD

**Issue by Jermin2020** [appium/appium#19157]
The desktopApp technology stack is flutter
What are some of the programs that do automated testing of desktop applications?  
Have tried using WAD, is there any other option besides this?

**Comment by KazuCocoa** [comment]
Afaik, no. https://github.com/appium/appium-flutter-driver does not support Win env right now. (I'm not sure it could, but prs are welcome)


https://discuss.appium.io/ may help to ask such questions.

**Comment by Jermin2020** [comment]
> Afaik, no. https://github.com/appium/appium-flutter-driver does not support Win env right now. (I'm not sure it could, but prs are welcome)
> 
> https://discuss.appium.io/ may help to ask such questions.

Thanks
