### ISSUE TITLE
Unable to install uiautomator2

### ISSUE THREAD

**Issue by reshma-sabu** [appium/appium#19150]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error while trying to install uiautomator2. Have tried with both appium and npm

### Expected Behavior

Uiautomator2 should get downloaded successfully.

### Minimal Reproducible Example

appium driver install uiautomator2
npm i appium-uiautomator2-driver@2.2.0

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s): none
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v18.17.1
- `npm` version (output of `npm --version`): 9.6.7
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: emulator

### Link to Appium Logs

<script src="https://gist.github.com/reshma-sabu/66efc982471096cabe7374ea1b8cdbdf.js"></script>

**Comment by reshma-sabu** [comment]
GIST link: https://gist.github.com/reshma-sabu/66efc982471096cabe7374ea1b8cdbdf

**Comment by mykola-mokhnach** [comment]
It looks like the machine has troubles fetching chromedriver. Try https://github.com/appium/appium-uiautomator2-driver#troubleshooting-chromedriver-download-issues

**Comment by reshma-sabu** [comment]
@mykola-mokhnach where is system variables should i add 'APPIUM_SKIP_CHROMEDRIVER_INSTALL' ?
I am getting error 'APPIUM_SKIP_CHROMEDRIVER_INSTALL' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot help there.
You need to understand what environment variables are and how then work in the OS being used as a host.

**Comment by reshma-sabu** [comment]
> Unfortunately I cannot help there. You need to understand what environment variables are and how they work in the OS being used as a host.

I am using this in windows.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
