### ISSUE TITLE
[Feat]: Use `devicectl` command to handle files for real devices as an option

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#19166]
**Is your feature request related to a problem? Please describe.**

Xcode 15 introduces `xcrun devicectl` to manage devices. We could use them in some cases. So far, I see overhead than appium-ios-device while considering iOS 17+, probably we could use the `devicectl` in some places instead of implementing appium-ios-device for ios 17+, it may help our future maintenance.

Then, maybe file management could help:

```
xcrun devicectl device info files
xcrun devicectl device copy
```

**Describe the solution you'd like**

Current existing implementation

**Describe alternatives you've considered**

**Additional context**

**Comment by mykola-mokhnach** [comment]
It would probably make sense to add a custom devicectl wrapper like with did for simctl (e.g. node-simctl)

**Comment by KazuCocoa** [comment]
Yes, agree with that

**Comment by KazuCocoa** [comment]
Found that the devicectl command did not identify iOS 16 device on my local. the command raised:

```
ERROR: The specified device was not found. (com.apple.dt.CoreDeviceError error 1000.)
```

**Comment by KazuCocoa** [comment]
Noticed that maybe no methods to "delete" files from a device via `xcrun devicectl device` right now...?

**Comment by mykola-mokhnach** [comment]
> We cannot "delete" a file, but can override with zero size file with:
> 
> ```
> % xcrun devicectl device copy to --device=00008020-000E5CDA0A23002E --domain-type=appDataContainer --user mobile --domain-identifier=com.apple.testmanagerd --source 08B61FA8-80CC-47F1-A214-64988F827E7A --destination Attachments/08B61FA8-80CC-47F1-A214-64988F827E7A
> 01:12:02  Acquired tunnel connection to device.
> 01:12:02  Enabling developer disk image services.
> 01:12:02  Acquired usage assertion.
> File Path on Device
> /private/var/mobile/Containers/Data/InternalDaemon/F55E307B-2720-4D1D-8F81-79DBF2AC50E1/Attachments/08B61FA8-80CC-47F1-A214-64988F827E7A
> ```
> 
> Then, `08B61FA8-80CC-47F1-A214-64988F827E7A` on the device can be replaced with `08B61FA8-80CC-47F1-A214-64988F827E7A` on the host machine. It might be help to prevent making size big, but not sure how we can actually delete them

I had the same idea. It might be a good workaround for now

**Comment by KazuCocoa** [comment]
another note. an emopty dir cannot override existing dir.

```
% xcrun devicectl device copy to --device=00008020-000E5CDA0A23002E --domain-type=appDataContainer --user mobile --domain-identifier=com.apple.testmanagerd --source "empty" --destination Attachments
01:23:28  Acquired tunnel connection to device.
01:23:28  Enabling developer disk image services.
01:23:28  Acquired usage assertion.
ERROR: The specified file could not be transferred. (com.apple.dt.CoreDeviceError error 7000.)
         NSURL = file:///Users/kazu/tmp/videos/empty
--------------------------------------------------------------------------------
ERROR: I/O Error: Could not remove existing file at path Attachments: Operation not permitted (com.apple.dt.remoteservices.error error 11001.)
```

These also actually did nothing.

```
% xcrun devicectl device copy to --device=00008020-000E5CDA0A23002E --domain-type=appDataContainer --user mobile --domain-identifier=com.apple.testmanagerd --source "empty-dir" --destination Attachments
01:24:43  Acquired tunnel connection to device.
01:24:43  Enabling developer disk image services.
01:24:43  Acquired usage assertion.
File Path on Device
/private/var/mobile/Containers/Data/InternalDaemon/F55E307B-2720-4D1D-8F81-79DBF2AC50E1/Attachments

% xcrun devicectl device copy to --device=00008020-000E5CDA0A23002E --domain-type=appDataContainer --user mobile --domain-identifier=com.apple.testmanagerd --source "empty-dir" --destination ./
01:25:14  Acquired tunnel connection to device.
01:25:14  Enabling developer disk image services.
01:25:14  Acquired usage assertion.
File Path on Device
/private/var/mobile/Containers/Data/InternalDaemon/F55E307B-2720-4D1D-8F81-79DBF2AC50E1/.
```

**Comment by mykola-mokhnach** [comment]
It is also possible to set attachment lifetime. I assume one of possible values there must be set to delete attachment as soon as the test competes/WDA is killed

**Comment by KazuCocoa** [comment]
oh, it would be nice if can

**Comment by mykola-mokhnach** [comment]
I will add some methods that allow to set lifetime today, so you could try that

**Comment by mykola-mokhnach** [comment]
We do use devicectl, so the feature could be closed as resolved

**Comment by IshanG97** [comment]
Does anyone know how to load a url on safari on a real connected iPhone? I've tried things like `xcrun devicectl device process launch --device <device-udid> com.apple.mobilesafari --payload-url http://www.google.com` but no luck

**Comment by KazuCocoa** [comment]
We do it via WDA/remote debugger. Perhaps I tried the method but did not work.
https://github.com/appium/appium-xcuitest-driver/blob/f00d231d6ab0986de7c6d5fa090ec4f9f283dc80/lib/commands/general.js#L158-L174
