### ISSUE TITLE
bug: element.clearValue() not clearing leading whitespace in iOS testing

### ISSUE THREAD

**Issue by hbc007** [appium/appium#19174]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

During our testing using Appium for iOS, we have encountered an issue with the element.clearValue() function. While the function successfully clears non-space characters, it's unable to clear strings in input fields when the string starts with whitespace characters.

### Expected Behavior

The text field should be cleared out completely, including the leading whitespace characters.

### Minimal Reproducible Example

1. Launch the application using Appium on iOS.
2. Navigate to the text input field.
3. Input a text string that starts with one or more whitespace characters, for example, "  abc".
4. Call element.clearValue() on the text field.
5. The leading whitespace characters still in input, for example, "  ".

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.1.2
- Appium driver(s) and their version(s): appium-xcuitest-driver: 4.32.23
- Platform and version under test: Windows 10
- Real device or emulator/simulator: iPhone X, ios16.3.1

**Comment by mykola-mokhnach** [comment]
Please provide the server log

**Comment by mykola-mokhnach** [comment]
Closed because of no response.
Also I was not able to reproduce the issue
