### ISSUE TITLE
bug: <title>appium:noReset = True，Cannot open the same app again，On Xiaomi 11 phone。

### ISSUE THREAD

**Issue by Yesisyes** [appium/appium#19173]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I test opening the app on my Xiaomi 11 phone, ['appium: noReset ']=True. The first time you open it, it can be successful. If you run the code to open the app again, the app will not be opened. If ['apium: noReset '] is not set to True, the app on the phone can be opened repeatedly.

### Expected Behavior

I can continuously open the same app without clearing the app data

### Minimal Reproducible Example

import time
from appium import webdriver

def device_driver():
    desired_caps = dict()
    desired_caps['appium:udid'] = "dad22b45"
    desired_caps['appium:platformName'] ="Android"
    desired_caps['appium:noReset'] = True
    desired_caps['appium:unicodeKeyboard'] = True
    desired_caps['appium:resetKeyboard'] = False
    desired_caps['appium:appPackage'] = "com.tencent.qqlive"
    desired_caps['appium:appActivity'] = "com.tencent.qqlive.ona.activity.SplashHomeActivity"
    desired_caps['appium:automationName'] = "uiautomator2"
    driver = webdriver.Remote('http://127.0.0.1:4723',  desired_caps)
    print('connect')
    time.sleep(10)
    driver.press_keycode(3)
    print('exit')
    # driver.quit()
device_driver()
print('Reconnect')
time.sleep(10)
device_driver()
print('Success Again')

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.1.3
- Appium driver(s) and their version(s): uiautomator2@2.29.8，xcuitest@4.12.2
- Appium plugin(s) and their version(s): No plugins
- Node.js version (output of `node --version`): v18.17.1
- `npm` version (output of `npm --version`): 9.6.7
- Last component(s) version which did _not_ exhibit the problem: appium1
- Platform and version under test: Android 11
- Real device or emulator/simulator:  Real device MI 11

### Further Information

[test_log.txt](https://github.com/appium/appium/files/12667845/test_log.txt)

**Comment by KazuCocoa** [comment]
Have you tried out `forceAppLaunch` capability as the log?
```
[debug] [ADB] Running 'D:\android_sdk\platform-tools\adb.exe -P 5037 -s dad22b45 shell dumpsys window'
[AndroidDriver] Screen already unlocked, doing nothing
[AndroidUiautomator2Driver@b521 (0f58d917)] Starting 'com.tencent.qqlive/com.tencent.qqlive.ona.activity.SplashHomeActivity and waiting for 'com.tencent.qqlive/com.tencent.qqlive.ona.activity.SplashHomeActivity'
[debug] [ADB] Getting IDs of all 'com.tencent.qqlive' processes
[debug] [ADB] Running 'D:\android_sdk\platform-tools\adb.exe -P 5037 -s dad22b45 shell pgrep -f \(\[\[:blank:\]\]\|\^\)com\.tencent\.qqlive\(\[\[:blank:\]\]\|\$\)'
[AndroidUiautomator2Driver@b521 (0f58d917)] 'com.tencent.qqlive' is already running and noReset is enabled. Set forceAppLaunch capability to true if the app must be forcefully restarted on session startup.
[debug] [AndroidUiautomator2Driver@b521 (0f58d917)] Proxying [GET /appium/device/pixel_ratio] to [GET http://127.0.0.1:8201/session/1d990b34-38ff-4b69-9ce3-cb935cd79179/appium/device/pixel_ratio] with no body
[debug] [AndroidUiautomator2Driver@b521 (0f58d917)] Got response with status 200: {"sessionId":"1d990b34-38ff-4b69-9ce3-cb935cd79179","value":3.5}
[debug] [AndroidUiautomator2Driver@b521 (0f58d917)] Matched '/appium/device/system_bars' to command name 'getSystemBars'
```

**Comment by mykola-mokhnach** [comment]
As @KazuCocoa mentioned above such behavior is expected. UIA2 driver does not try to restart the app on session startup if it is already running and noReset is enabled. You should either control the app lifecycle by calling appropriate APIs (e.g. activateApp, terminateApp) or try the proposed capability

**Comment by Yesisyes** [comment]
> As @KazuCocoa mentioned above such behavior is expected. UIA2 driver does not try to restart the app on session startup if it is already running and noReset is enabled. You should either control the app lifecycle by calling appropriate APIs (e.g. activateApp, terminateApp) or try the proposed capability

Ok,i get it. I also found that the terminate_app() method mentioned the uninstall time, which confused me. Can the terminate_app() method not only terminate the process, but also uninstall the program? Keyword Args:
            `timeout` (int): [Android only] how much time to wait for the uninstall to complete.
                500ms by default.

**Comment by KazuCocoa** [comment]
not sure that you referenced, but `mobile:terminateApp` for example https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-terminateapp terminates the given package name via adb in Android. it does not have such an uninstallation.
https://github.com/appium/appium-android-driver/blob/43688b961dd0f6f97733621c3857ff95f2bfb55c/lib/commands/app-management.js#L119-L149
