### ISSUE TITLE
bug: [Android] Image validation is getting failed when tested across different device resolutions {Image-plugin}

### ISSUE THREAD

**Issue by ShanmugaPrasanth94** [appium/appium#19172]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running the Image validation on Tab Active 2 and Tab Active 3 devices. 
The validation **fails** when the image captured on **Tab Active 2** is validated against **Tab Active 3** & vice-versa.
I inferred the resolution changes.
Tried adding the Settings still facing the issue.
           appiumDriver.setSetting("fixImageTemplateSize", true);
            appiumDriver.setSetting("fixImageTemplateScale", true);

### Expected Behavior

Image validation should be passed

### Minimal Reproducible Example

 public boolean verifyIsDisplayedWithImage(String imageToVerify) {
        boolean verifyImageDisplayed = false;
        try {
            String strImagePath = FilePath.getImagePath().concat(imageToVerify).concat(".PNG");
            File template = new File(strImagePath);
            appiumDriver.setSetting("fixImageTemplateSize", true);
            appiumDriver.setSetting("fixImageTemplateScale", true);
            By image = AppiumBy.image(Base64.getEncoder().encodeToString(Files.readAllBytes(template.toPath())));
            verifyImageDisplayed = new WebDriverWait(appiumDriver, Duration.ofSeconds(2)).until(ExpectedConditions.presenceOfElementLocated(image)).isDisplayed();
        } catch (AssertionError | Exception e) {
            verifyImageDisplayed = false;
            logger.error(e); }

### Environment

- Operating system: Windows
- Appium server version : 2.0.1
- Appium driver(s) and their version(s): Ui Automator2/ 2.29.3
- Appium plugin(s) and their version(s): 2.1.2
- Node.js version (output of `node --version`):v18.15.0
- `npm` version (output of `npm --version`): 9.5.0
- Last component(s) version which did _not_ exhibit the problem: -
- Platform and version under test: Android, 9 & 13
- Real device or emulator/simulator: Samsung Tab active2 & Tab active 3

**Comment by mykola-mokhnach** [comment]
Not sure there is anything for us to do there. The comparison itself is done by opencv, so if no match is happening then it is probably something to tune on their side.

**Comment by ShanmugaPrasanth94** [comment]
> Not sure there is anything for us to do there. The comparison itself is done by opencv, so if no match is happening then it is probably something to tune on their side.

@mykola-mokhnach Thanks. but for a few images, the comparison happens across both devices. is there any settings to make the resolution adaptive?
Any help would be appreciated

**Comment by jlipps** [comment]
There's probably a local library you could use to ensure the images are the same size. Unfortunately this kind of image manipulation is probably not something that is generically useful enough to be added to the plugin.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
