### ISSUE TITLE
API or Method to Interrupt Scrolling on iOS Devices

### ISSUE THREAD

**Issue by merih-sakarya** [appium/appium#19189]
I am working on a project similar to BrowserStack App Live, and we are utilizing WebDriverAgent to communicate with iOS devices. We are facing a scenario where we need to mimic the default iOS behavior where a scrolling process is interrupted when a click is made on the device screen.

I have explored the available APIs and documentation but couldn't find a direct method or endpoint to achieve this behavior through WebDriverAgent.

Is there an existing feature or workaround in WebDriverAgent that allows for interrupting a scroll action on an iOS device? If not, could you suggest any alternatives or best practices to simulate this user interaction programmatically?

Any insights or suggestions would be greatly appreciated.

Thank you for your time and assistance!

**Comment by mykola-mokhnach** [comment]
Seems like nobody here could help with that. Consider asking at Appium forum.
