### ISSUE TITLE
bug: system prompts are not appropriately translated with specified language capability on iOS simulators

### ISSUE THREAD

**Issue by mwakizaka** [appium/appium#19181]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since appium-xcuitest-driver 4.14.0, system prompts are not translated appropriately on iOS simulators.
When I tried using `language: ja, locale: ja_JP` as below, some texts on the system dialog remains English.

<img width="382" alt="appium_xcuitest@4 14 0" src="https://github.com/appium/appium/assets/21286384/b131d2ee-b4df-49ca-843e-9dec8847eefb">

### Expected Behavior

- When using  appium-xcuitest-driver 4.13.4, system prompts are appropriately translated as below.
- You can refer to the appium log [here](https://gist.github.com/mwakizaka/91f63aa86a16254ffadb71f51397e112#file-expected_appium_xcuitest-4-13-4-log)
<img width="373" alt="appium_xcuitest@4 13 4" src="https://github.com/appium/appium/assets/21286384/8db7e741-5beb-49bd-aaf0-3b85ec171047">

### Minimal Reproducible Example

Start a session at https://inspector.appiumpro.com/ with the following capabilities
```
{
  "platformName": "iOS",
  "appium:platformVersion": "16.4",
  "appium:deviceName": "iPhone 12 Pro",
  "appium:automationName": "XCUITest",
  "appium:showXcodeLog": false,
  "appium:showIOSLog": false,
  "appium:language": "ja",
  "appium:locale": "ja_JP",
  "appium:app": "com.apple.reminders"
}
```

### Environment

- Operating system: macOS 13.5.2 (22G91)
- Appium server version (output of `appium --version`): 2.1.0
- Appium driver(s) and their version(s): xcuitest@4.14.0 
- Appium plugin(s) and their version(s): N/A
- Node.js version (output of `node --version`): v16.13.2
- `npm` version (output of `npm --version`): 8.1.2
- Last component(s) version which did _not_ exhibit the problem: xcuitest@4.13.4
- Platform and version under test: iOS 16.4 (Xcode 14.3.1)
- Real device or emulator/simulator: simulator

### Link to Appium Logs

https://gist.github.com/mwakizaka/91f63aa86a16254ffadb71f51397e112#file-unexpected_appium_xcuitest-4-14-0-log

### Further Information

- I guess this issue happened due to https://github.com/appium/appium-xcuitest-driver/pull/1463 (the change intends not to reboot simulators after changing preferences)
- Although it might be possible to resolve this issue by killing daemon(?) processes (e.g. by running `xcrun simctl spawn booted launchctl kill 9 user/foreground/com.apple.locationd`), we should simply reboot iOS simulators when we change simulator language? 🤔

**Comment by mykola-mokhnach** [comment]
I would really like to avoid rebooting the simulator if possible as it invalidates the cached connection to testmanagerd. You could probably try fullReset as a possible workaround, although I believe there should be a way to restart some particular services there like mentioned above. Just needs some experimenting.

**Comment by mykola-mokhnach** [comment]
Maybe something like `xcrun simctl spawn booted launchctl stop com.apple.SpringBoard` would do the job

**Comment by mwakizaka** [comment]
Thank you! As far as I checked at my end 
- `xcrun simctl spawn booted launchctl stop com.apple.SpringBoard` works for permission dialog for push notification.
- We also need `xcrun simctl spawn booted launchctl stop com.apple.locationd` for permission dialog for location.
- As for permission dialogs for camera, microphone and contacts, they are translated as expected.

I'll check some other system prompt variants as well and try submitting a PR.
