### ISSUE TITLE
always got xcode failed with code 70 when using setXcodeCertificate, but sometimes it can run when not using setXcodeCertificate

### ISSUE THREAD

**Issue by fatahillahardhi** [appium/appium#19190]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to run with Real Devices, but I always got **xcode failed with code 70** if using setXcodeCertificate, but if I'm not using setXcodeCertificate it can run sometimes (sometimes it can run normally, but sometimes got xcode failed with code 65)

I don't know what happens, because the xcodeSigningId and xcodeOrgId are correct. When I run with Appium 1 it can run normally without getting errors code 70 or 65.

### Expected Behavior

Can run normally with Real Devices

### Minimal Reproducible Example

```
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
xcodebuild error message:
. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
Host info: host: 'AP00044-MP', ip: 'fe80:0:0:0:c61:90d3:8e89:e9d5%en0'
Build info: version: '4.12.0', revision: '249f2a7d1b*'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '13.0', java.version: '17.0.8'
Driver info: io.appium.java_client.ios.IOSDriver
Command: [null, newSession {capabilities=[{appium:udid=**sensored**, appium:xcodeOrgId=**sensored**, appium:wdaLocalPort=59272, appium:xcodeSigningId=**sensored**, appium:autoAcceptAlerts=true, appium:deviceName=Fatahillah's iPhone, appium:maxTypingFrequency=30, platformName=IOS, appium:automationName=XCuiTest, appium:app=/Users/fatahillahardhi/Desktop/Automation/bibit-automated-ui-test-ios/apk/BibitStaging.ipa, appium:autoWebview=true}], desiredCapabilities=Capabilities {appium:app: /Users/fatahillahardhi/Desk..., appium:autoAcceptAlerts: true, appium:autoWebview: true, appium:automationName: XCuiTest, appium:deviceName: Fatahillah's iPhone, appium:maxTypingFrequency: 30, appium:udid: **sensored**, appium:wdaLocalPort: 59272, appium:xcodeOrgId: **sensored**, appium:xcodeSigningId: **sensored** platformName: IOS}}]
Capabilities {appium:app: /Users/fatahillahardhi/Desk..., appium:autoAcceptAlerts: true, appium:autoWebview: true, appium:automationName: XCuiTest, appium:deviceName: Fatahillah's iPhone, appium:maxTypingFrequency: 30, appium:udid: **sensored**, appium:wdaLocalPort: 59272, appium:xcodeOrgId: **sensored**, appium:**sensored**, platformName: IOS}
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:133)
        at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
        at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:182)
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)
        at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:274)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:163)
        at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
        at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:101)
        at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:104)
        at demo.webdriver.IOSDriverInstance.initialize(IOSDriverInstance.java:77)
        at demo.hooks.IOSDriverHooks.initializeWebdriver(IOSDriverHooks.java:19)

java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.TakesScreenshot.getScreenshotAs(org.openqa.selenium.OutputType)" because "demo.webdriver.IOSDriverInstance.iosDriver" is null
        at demo.hooks.IOSDriverHooks.quitWebdriver(IOSDriverHooks.java:30)
```

### Environment

- Operating system: Mac OS Ventura 13.0
- Appium server version (output of `appium --version`): v2.1.3
- Appium driver(s) and their version(s): XCUITest 5.3.0
- Appium plugin(s) and their version(s): - 
- Node.js version (output of `node --version`): v18.17.1
- `npm` version (output of `npm --version`): 9.8.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS 16.6.1
- Real device or emulator/simulator: Real Device
- Selenium: 4.11.0 (I tried with 4.12.0 but the result was still the same)
- Appium Java Client: 8.5.1

### Further Information

capabilities:
`options.setXcodeCertificate(new XcodeCertificate(env("ORGID"),env("SIGNID")));
`

**Comment by mykola-mokhnach** [comment]
Please provide the full server log with xcodebuild logging enabled

**Comment by mykola-mokhnach** [comment]
Also Appium 1 is not supported anymore. We only support driver supplied with Appium 2

**Comment by fatahillahardhi** [comment]
@mykola-mokhnach Yes now I'm using Appium 2, I mean when I tried Appium 1 it can run normally using SignId and OrgId. But when I try with Appium 2 I face that problem.

Here's the full log
https://gist.github.com/fatahillahardhi/f0d4f1b1787020899d5c45937116432c

**Comment by mykola-mokhnach** [comment]
> [Xcode] /Users/fatahillahardhi/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj: error: WebDriverAgentLib has conflicting provisioning settings. WebDriverAgentLib is automatically signed, but code signing identity Fatahillah Ardhi (JZ4BTT3489) has been manually specified. Set the code signing identity value to "Apple Development" in the build settings editor, or switch to manual signing in the Signing & Capabilities editor. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')

I assume this is the problem. Try to manually set what it wants. You may use the `appium driver run xcuitest open-wda` command to open WDA in Xcode.

**Comment by KazuCocoa** [comment]
or could `xcodeSigningId` be `Apple Development`?
https://appium.github.io/appium-xcuitest-driver/5.3/real-device-config/

**Comment by fatahillahardhi** [comment]
> > [Xcode] /Users/fatahillahardhi/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj: error: WebDriverAgentLib has conflicting provisioning settings. WebDriverAgentLib is automatically signed, but code signing identity Fatahillah Ardhi (JZ4BTT3489) has been manually specified. Set the code signing identity value to "Apple Development" in the build settings editor, or switch to manual signing in the Signing & Capabilities editor. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
> 
> I assume this is the problem. Try to manually set what it wants. You may use the `appium driver run xcuitest open-wda` command to open WDA in Xcode.

@mykola-mokhnach  so if I use manual configuration, I don't need to use setXcodeCertificate on capabilities?



> or could `xcodeSigningId` be `Apple Development`? https://appium.github.io/appium-xcuitest-driver/5.3/real-device-config/

@KazuCocoa hmm I still got error 70

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach so if I use manual configuration, I don't need to use setXcodeCertificate on capabilities?

yes, you can configure WDA signing manually, although you'd need to repeat this procedure every time the driver is updated or reinstalled.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
