### ISSUE TITLE
Appium 2.x on real devices: fully reset app and clean state (like logged in user)

### ISSUE THREAD

**Issue by DmitriiKrupinECM** [appium/appium#19203]
Environment: iOS (16-17), real device/sim

Previously for my Node.js WebdriverIO Appium tests, when using Appium 1.x.x and the commands 
`driver.launchApp() `at the beginning of a test, and then `driver.closeApp()` the state of my app was fully cleared as expected: the current user was logged out automatically, push notifications settings reset etc.
However, now these commands are deprecated. I'm trying to switch to the recommended
`driver.execute('mobile: launchApp', { bundleId: 'my.bundleId' })` and 
`driver.execute('mobile: terminateApp', { bundleId: 'my.bundleId' })` at the end, but this seems not to do the same job as the next test starts with the user already logged in, and that's not what I'd expect at the beginning of the test.
Please note I also use the following capabilities:
```
    'appium:fullReset': true,
    'appium:noReset': false,
```
But looks like these do not help either. Please advise what would be the best approach to clean the iOS app state in the newest Appium and start each test from the initial login screen (like after a clean app installation)?

**Comment by KazuCocoa** [comment]
For iOS, uninstall the app, then install it again does the same thing. (launchApp did it the same)
This is not Android, but for Android, you could use https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-clearapp

**Comment by deepakarorawins** [comment]
> For iOS, [uninstall the app](https://appium.github.io/appium-xcuitest-driver/5.3/execute-methods/#mobile-removeapp), then [install it again](https://appium.github.io/appium-xcuitest-driver/5.3/execute-methods/#mobile-installapp) does the same thing. (launchApp endpoint did it the same) This is not Android, but for Android, you could use https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-clearapp

Thank you @KazuCocoa  for the help, however my observation is that removeApp then installApp and then launchApp/ActivateApp takes more time in comparison  to just old launchApp() method, is this expected?

For our iOS app **Old launchApp()** is taking: **21 seconds** approximately.
`getDriver().launchApp();`


For our iOS app **New removeApp-->installApp-->launchApp** is taking **28 seconds** approximately.
String bundleId = getDriver().getCapabilities().getCapability("bundleId").toString();
            String app = getDriver().getCapabilities().getCapability("app").toString();
            Map<String, Object> args = new HashMap<>();
            args.put("bundleId", bundleId);
            args.put("app", app);
            getDriver().executeScript("mobile: removeApp", args);
            getDriver().executeScript("mobile: installApp", args);
            getDriver().executeScript("mobile: launchApp", args);

**Comment by KazuCocoa** [comment]
Could you share the full appium log? I wondered if the comparison compared recent ones such as xcuitest driver v4.35.0 (still existed) and the latest v5 (no longer exist).
It could have some factors to take longer time, so we'd like to see the full log with timestamp.

It depends on the bottleneck, but for example the installApp can use `parallel` https://appium.github.io/appium-xcuitest-driver/5.3/execute-methods/#mobile-installapp to improve the installation speed

**Comment by deepakarorawins** [comment]
> Could you share the full appium log? I wondered if the comparison compared recent ones such as xcuitest driver v4.35.0 (still existed) and the latest v5 (no longer exist). It could have some factors to take longer time, so we'd like to see the full log with timestamp.
> 
> It depends on the bottleneck, but for example the installApp can use `parallel` https://appium.github.io/appium-xcuitest-driver/5.3/execute-methods/#mobile-installapp to improve the installation speed

sure let me prepare logs with `parallel`

**Comment by KazuCocoa** [comment]
thanks. the performance could depend on app, so in your case, maybe ios-deploy was the best as the installation performance...?

Btw, do you have the below log as well?

> For our iOS app Old launchApp() is taking: 21 seconds approximately.
> getDriver().launchApp();

**Comment by deepakarorawins** [comment]
> thanks. the performance could depend on app, so in your case, maybe ios-deploy was the best as the installation performance...?
> 
> Btw, do you have the below log as well?
> 
> > For our iOS app Old launchApp() is taking: 21 seconds approximately.
> > getDriver().launchApp();

yes, give me some time, I'll add here.

**Comment by KazuCocoa** [comment]
Good question. We had conversations about that in https://github.com/appium/appium/issues/15807 in the past. We usually recommend cloud providers to define their method to care about that. For example `cloud: installApp, {id: <their internal app id>}` command to resolve such cloud provider thing and install it behind that for their local Appium.
You might need to ask about the possibility to them first. @DmitriiKrupinECM

**Comment by KazuCocoa** [comment]
`server_old_launchApp_21_seconds.log`:

```
2023-09-26 06:40:57:653 [XCUITest] Using 'serial' app deployment strategy. You could change it by providing another value to the 'appInstallStrategy' capability
2023-09-26 06:40:57:764 [XCUITest] Getting bundle ID from app '/var/folders/38/dssdk4m564g4v3czyvlxcyb40000gn/T/2023826-87798-w4eihk.ssa6/your.app': your app bundle id'
2023-09-26 06:40:57:837 [XCUITest] Successfully scanned the tree structure of '/var/folders/38/dssdk4m564g4v3czyvlxcyb40000gn/T/2023826-87798-w4eihk.ssa6/your.app'
2023-09-26 06:40:57:838 [XCUITest] Got 98 folders and 562 files to push
2023-09-26 06:40:57:882 [XCUITest] Successfully created the remote folder structure (99 items)
2023-09-26 06:40:57:882 [XCUITest] Proceeding to serial files push
2023-09-26 06:41:00:163 [XCUITestDriver@9cec (0122f30a)] Parsed BUILD_DIR configuration value: '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-deynhngatgscmwhgxommlusrwbwq/Build/Products'
2023-09-26 06:41:00:163 [XCUITestDriver@9cec (0122f30a)] Got derived data root: '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-deynhngatgscmwhgxommlusrwbwq'
2023-09-26 06:41:05:418 [XCUITest] Successfully pushed 98 folders and 562 files within 7653ms
2023-09-26 06:41:05:800 [XCUITest] A new application installation is going to be performed
```


Others:
```
2023-09-26 03:15:15:758 [XCUITest] Getting bundle ID from app '/var/folders/kr/zpp435d90p90r1rpxg6qr8hh0000gn/T/2023826-98754-hew0qe.rqiy/your.app': 'your app bundle id'
2023-09-26 03:15:15:762 [XCUITest] Successfully scanned the tree structure of '/var/folders/kr/zpp435d90p90r1rpxg6qr8hh0000gn/T/2023826-98754-hew0qe.rqiy/your.app'
2023-09-26 03:15:15:762 [XCUITest] Got 99 folders and 562 files to push
2023-09-26 03:15:15:826 [XCUITest] Successfully created the remote folder structure (100 items)
2023-09-26 03:15:15:826 [XCUITest] Proceeding to serial files push
2023-09-26 03:15:27:778 [XCUITest] Successfully pushed 99 folders and 562 files within 12020ms
2023-09-26 03:15:28:163 [XCUITest] A new application installation is going to be performed
2023-09-26 03:15:41:919 [XCUITest] App installation succeeded after 26268ms
```

These installation diffs existed in each new session request as well. So, even the same new session request, server_old_launchApp_21_seconds side ended around 7653ms but others were 12020ms for `Successfully pushed` for example. So the diff potentially came from the app's folder number (and size?) or device OS diff I assume. I also noticed you used different device/os versions. What about using the same app/device as a fare comparison? @deepakarorawins 

(replaced your app with `your.app`.)

**Comment by deepakarorawins** [comment]
> `server_old_launchApp_21_seconds.log`:
> 
> ```
> 2023-09-26 06:40:57:653 [XCUITest] Using 'serial' app deployment strategy. You could change it by providing another value to the 'appInstallStrategy' capability
> 2023-09-26 06:40:57:764 [XCUITest] Getting bundle ID from app '/var/folders/38/dssdk4m564g4v3czyvlxcyb40000gn/T/2023826-87798-w4eihk.ssa6/your.app': your app bundle id'
> 2023-09-26 06:40:57:837 [XCUITest] Successfully scanned the tree structure of '/var/folders/38/dssdk4m564g4v3czyvlxcyb40000gn/T/2023826-87798-w4eihk.ssa6/your.app'
> 2023-09-26 06:40:57:838 [XCUITest] Got 98 folders and 562 files to push
> 2023-09-26 06:40:57:882 [XCUITest] Successfully created the remote folder structure (99 items)
> 2023-09-26 06:40:57:882 [XCUITest] Proceeding to serial files push
> 2023-09-26 06:41:00:163 [XCUITestDriver@9cec (0122f30a)] Parsed BUILD_DIR configuration value: '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-deynhngatgscmwhgxommlusrwbwq/Build/Products'
> 2023-09-26 06:41:00:163 [XCUITestDriver@9cec (0122f30a)] Got derived data root: '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-deynhngatgscmwhgxommlusrwbwq'
> 2023-09-26 06:41:05:418 [XCUITest] Successfully pushed 98 folders and 562 files within 7653ms
> 2023-09-26 06:41:05:800 [XCUITest] A new application installation is going to be performed
> ```
> 
> Others:
> 
> ```
> 2023-09-26 03:15:15:758 [XCUITest] Getting bundle ID from app '/var/folders/kr/zpp435d90p90r1rpxg6qr8hh0000gn/T/2023826-98754-hew0qe.rqiy/your.app': 'your app bundle id'
> 2023-09-26 03:15:15:762 [XCUITest] Successfully scanned the tree structure of '/var/folders/kr/zpp435d90p90r1rpxg6qr8hh0000gn/T/2023826-98754-hew0qe.rqiy/your.app'
> 2023-09-26 03:15:15:762 [XCUITest] Got 99 folders and 562 files to push
> 2023-09-26 03:15:15:826 [XCUITest] Successfully created the remote folder structure (100 items)
> 2023-09-26 03:15:15:826 [XCUITest] Proceeding to serial files push
> 2023-09-26 03:15:27:778 [XCUITest] Successfully pushed 99 folders and 562 files within 12020ms
> 2023-09-26 03:15:28:163 [XCUITest] A new application installation is going to be performed
> 2023-09-26 03:15:41:919 [XCUITest] App installation succeeded after 26268ms
> ```
> 
> These installation diffs existed in each new session request as well. So, even the same new session request, server_old_launchApp_21_seconds side ended around 7653ms but others were 12020ms for `Successfully pushed` for example. So the diff potentially came from the app's folder number (and size?) or device OS diff I assume. I also noticed you used different device/os versions. What about using the same app/device as a fare comparison? @deepakarorawins
> 
> (replaced your app with `your.app`.)

Thank you @KazuCocoa for the comparison, Yes those logs are from, different versions the new one is all latest softwares on my mac book, which is flaky. I'll try to provide logs in same conditions.
