### ISSUE TITLE
Can't run tests on iOS device

### ISSUE THREAD

**Issue by rmarinho** [appium/appium#19211]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, I m trying to run some appium tests on iOS device, we have this running on simulator fine. When I m trying to run on device, even following the instructions i get issues with signing the webdriver.xcodeproject. Seems even when using `Apple Development` as specified on the docs, it is look for an iPhone Developer signing .

### Expected Behavior

Can sign and install the WebDriverAgent on device using my own cert or automatic mode should at least work.

### Minimal Reproducible Example

Use this link to setup the environment. https://github.com/dotnet/maui/wiki/UITests
install .net on Mac
clone maui. - https://github.com/dotnet/maui/

``` 
./build.ps1 --target=dotnet-buildtasks --configuration="Debug" --workloads=global
./build.ps1 --target=dotnet-samples --configuration="Debug" --workloads=global --ios --usenuget=false
./build.ps1 -Script eng/devices/ios.cake --target=uitest --device=ios-device --apiversion="16.4" --configuration="Debug"
```

### Environment

- Operating system: macO 13,6
- Appium server version (output of `appium --version`):  2.1.1
- Appium driver(s) and their version(s): xcuitest 5.2.0
- Appium plugin(s) and their version(s): none
- Node.js version (output of `node --version`): 20.7.0
- `npm` version (output of `npm --version`): 10.1.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS 
- Real device or emulator/simulator: RealDevice

### Link to Appium Logs

https://gist.github.com/rmarinho/b03a285d767e76bc49b2c486cc99f302

**Comment by mykola-mokhnach** [comment]
> [38;5;128m[Xcode][0m /Users/ruimarinho/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj: error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "*******

I believe this is an issue with signing. I don't think there is anything we can do about it. Consider following https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by KazuCocoa** [comment]
`updatedWDABundleId` in the real-device-config.md might also need to set the WDA's bundle id properly for your provisioning profile

>  error: No profiles for 'com.facebook.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner.xctrunner'.

**Comment by rmarinho** [comment]
It's definitely an issue with the signing, I just wanted to also understand if I m doing something wrong. There are some assumptions made for default profile that I don't quite understand. Why is is logging this 

```
 signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "*******
 ```
 
I have a wildcard profile, it should use that one no?  that works for my other apps. I m trying to figure why is using iOS development and not Apple Development that we can see here https://gist.github.com/rmarinho/b03a285d767e76bc49b2c486cc99f302#file-appium-log-L126

**Comment by rmarinho** [comment]
> `updatedWDABundleId` in the real-device-config.md might also need to set the WDA's bundle id properly for your provisioning profile
> 
> > error: No profiles for 'com.facebook.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner.xctrunner'.

is doing the manual dance on opening on Xcode, made it work. But I need to setup this on CI, where we are using a 2nd keychain, and I would need to have a way to manual sign with certs. I wonder if we have an extra property for the provision profile we can use both to sign the runner.
also I saw in other thread, don't you build now the runner as a iPA to be installed manually? I wonder if that could be a 2nd approach.

**Comment by KazuCocoa** [comment]
The iOS development looks like handled by xcodebuild internal, so kind of hidden from us. Below is what Appium issued to run xcodebuild in your log. Running the command directly could show something further.

> xcodebuild build-for-testing test-without-building -project /Users/ruimarinho/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=be55f9d660554c6894a598be9a6fd0e0d8018f6f IPHONEOS_DEPLOYMENT_TARGET=16.5 DEVELOPMENT_TEAM=******* CODE_SIGN_IDENTITY=Apple Development GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO


In case you changed bundle id only directly via Xcode, then set team id etc via `xcodebuild` the above worked, it might show setting `updatedWDABundleId` capability is the only remain thing to make our xcodebuild work

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
