### ISSUE TITLE
Couldn't find windows driver in supported driver list

### ISSUE THREAD

**Issue by ashalyn** [appium/appium#19214]
I want to install windows driver , but return  it not in supported drivers,  Anyone met this problem? Please help!

![image](https://github.com/appium/appium/assets/139414923/f186a7bf-be0a-4112-91db-078ffbc43e2a)

**Comment by KazuCocoa** [comment]
It is expected. Please check:

https://github.com/appium/appium-windows-driver

> Note
> Since version 2.0.0 Windows driver has dropped the support of Appium 1, and is only compatible to Appium 2. Use the appium driver install --source=npm appium-windows-driver command to add it to your Appium 2 dist.
