### ISSUE TITLE
Cannot run appium inspector on real device (Xcode couldn't find any iOS App Development provisioning profiles matching bundleID0

### ISSUE THREAD

**Issue by murigregori** [appium/appium#19223]
Hello. I am a newbie in setting up appium to run on real iOS devices and I am having an issue with trying to use the. appium inspector on an iPhone 14. I am using Xcode 15 on iPhone 14 os 16.6 and I have tries to follow the real device config documentation  by appium to edit the WebdriverAgent.xcodeproj file and fit my team and to be able to generate my own provisioning profile. However, it still does not work. Please see errors below: 

`[debug] [AppiumDriver@4a2a] /Users/meryl.gregori/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj: error: No profiles for 'com.core-team01.WebDriverAgentRunner.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.core-team01.WebDriverAgentRunner.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')`

`[debug] [AppiumDriver@4a2a] /Users/meryl.gregori/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj: error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "<team_id>" with a private key was found. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')`

When I try to run the WebdriverAgent on Xcode, it succeeds and it gets installed in the device. I also get the same error when I try to run it on the CLI.

Needing some insights on this. Thanks!

Capabilities used: 

`{
  "appium:platformName": "iOS",
  "appium:deviceName": "iPhone 14",
  "appium:automationName": "XCUITest",
  "appium:udid": "<iphone_udid>",
  "appium:platformVersion": "16.6",
  "appium:bundleId": "com.core-team01.IntegrationApp",
  "appium:xcodeOrgId": "<team_id_from_certificate>",
  "appium:xcodeSigningId": "iPhone Developer",
  "appium:showXcodeLog": true,
  "appium:allowProvisioningDeviceRegistration": true
}`

**Comment by KazuCocoa** [comment]
Did you set `updatedWDABundleId` capability with `com.core-team01.WebDriverAgentRunner`?
https://appium.github.io/appium-xcuitest-driver/5.4/real-device-config/

https://discuss.appium.io/ might help to ask such a question as well

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
