### ISSUE TITLE
Unable to restart app in different language

### ISSUE THREAD

**Issue by lorecioata** [appium/appium#19225]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Before updating to the latest versions of Appium Inspector, iOS, MacOS, xCode, I was able to run an entire test suite in the language that I set as a driver capability, but that is not the case anymore. 
Whenever the tearDown method is called, the next test starts the app in the language of the device instead of the language I set. 

This happens to my teammates as well.

### Expected Behavior

The app should restart in the language set for the driver. 

### Minimal Reproducible Example

Written in Current Behavior

### Environment

- Operating system: macOS - Sonoma 14.0
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s): xcuitest@5.4.0
- Appium plugin(s) and their version(s): images@2.1.2
- Node.js version (output of `node --version`): 18.18.0
- `npm` version (output of `npm --version`): 9.8.1
- Last component(s) version which did _not_ exhibit the problem: Ventura 13.0, iOS 16.4
- Platform and version under test: iPad Pro, iOS 17.0.1
- Real device or emulator/simulator: iPad Pro, iOS, 17.0.1

**Comment by mykola-mokhnach** [comment]
Please provide the server log where the feature worked and the one where it does not

**Comment by lorecioata** [comment]
The logs look the same. The app just doesn't open in the language set as driver capability after it's terminated in the first test.

**Comment by lorecioata** [comment]
Event 'newSessionRequested' logged at 1695909826609 (17:03:46 GMT+0300 (Eastern European Summer Time))
[Appium] Attempting to find matching driver for automationName 'XCUITest' and platformName 'iOS'
[Appium] The 'xcuitest' driver was installed and matched caps.
[Appium] Will require it at /Users/loree/node_modules/appium-xcuitest-driver
[debug] [Appium] Requiring driver at /Users/loree/node_modules/appium-xcuitest-driver
[AppiumDriver@3366] Appium v2.0.1 creating new XCUITestDriver (v5.4.0) session
[AppiumDriver@3366] Checking BaseDriver versions for Appium and XCUITestDriver
[AppiumDriver@3366] Appium's BaseDriver version is 9.3.16
[AppiumDriver@3366] XCUITestDriver's BaseDriver version is 9.3.20
[debug] [XCUITestDriver@19be] Creating session with W3C capabilities: {
[debug] [XCUITestDriver@19be]   "alwaysMatch": {
[debug] [XCUITestDriver@19be]     "platformName": "iOS",
[debug] [XCUITestDriver@19be]     "appium:platformVersion": "17",
[debug] [XCUITestDriver@19be]     "appium:deviceName": "iPad",
[debug] [XCUITestDriver@19be]     "appium:app": "/Users/loree/Library/Developer/Xcode/DerivedData/sum-hiwowuhmxhshiccfchbimjmhbmfr/Build/Products/Debug-iphoneos/.ipa",
[debug] [XCUITestDriver@19be]     "appium:udid": "",
[debug] [XCUITestDriver@19be]     "appium:xcodeOrgId": "",
[debug] [XCUITestDriver@19be]     "appium:xcodeSigningId": "iPhone Developer",
[debug] [XCUITestDriver@19be]     "appium:bundleId": "",
[debug] [XCUITestDriver@19be]     "appium:idleTimeout": 600,
[debug] [XCUITestDriver@19be]     "appium:language": "es",
[debug] [XCUITestDriver@19be]     "appium:locale": "es",
[debug] [XCUITestDriver@19be]     "appium:fullReset": false,
[debug] [XCUITestDriver@19be]     "appium:noReset": true,
[debug] [XCUITestDriver@19be]     "appium:orientation": "PORTRAIT",
[debug] [XCUITestDriver@19be]     "appium:useNewWDA": false,
[debug] [XCUITestDriver@19be]     "appium:automationName": "XCUITest",
[debug] [XCUITestDriver@19be]     "appium:includeSafariInWebviews": true,
[debug] [XCUITestDriver@19be]     "appium:newCommandTimeout": 3600,
[debug] [XCUITestDriver@19be]     "appium:connectHardwareKeyboard": true
[debug] [XCUITestDriver@19be]   },
[debug] [XCUITestDriver@19be]   "firstMatch": [
[debug] [XCUITestDriver@19be]     {}
[debug] [XCUITestDriver@19be]   ]
[debug] [XCUITestDriver@19be] }
[XCUITestDriver@19be] The following capabilities were provided, but are not recognized by Appium:
[XCUITestDriver@19be]   idleTimeout
[XCUITestDriver@19be (69240df7)] Session created with session id: 69240df7-365a-4a61-b7e9-a5a75fa31a58
[debug] [XCUITest] Current user: 'loree'
[debug] [XCUITestDriver@19be (69240df7)] Available devices: 
[debug] [XCUITest] Creating iDevice object with udid ''
[XCUITestDriver@19be (69240df7)] Determining device to run tests on: udid: '', real device: true
[XCUITestDriver@19be (69240df7)] Normalized platformVersion capability value '17' to '17.0'
[debug] [XCUITestDriver@19be (69240df7)] Event 'xcodeDetailsRetrieved' logged at 1695909826708 (17:03:46 GMT+0300 (Eastern European Summer Time))
[BaseDriver] Using local app '/Users/loree/Library/Developer/Xcode/DerivedData/sum-hiwowuhmxhshiccfchbimjmhbmfr/Build/Products/Debug-iphoneos/.ipa'
[debug] [Support] Found 'unzip' at '/usr/bin/unzip'
[debug] [XCUITestDriver@19be (69240df7)] Found 1 bundle in '.ipa': Payload/.app
[XCUITestDriver@19be (69240df7)] 'Payload/.app' is the resulting application bundle selected from '/Users/loree/Library/Developer/Xcode/DerivedData/sum-hiwowuhmxhshiccfchbimjmhbmfr/Build/Products/Debug-iphoneos/.ipa'
[debug] [XCUITestDriver@19be (69240df7)] Event 'appConfigured' logged at 1695909830240 (17:03:50 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITest] Checking whether app '/var/folders/yv/yj_6t_d944jb1kq7sx0chfz80000gn/T/2023828-67055-19rv35k.ko91/.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [XCUITestDriver@19be (69240df7)] Event 'resetStarted' logged at 1695909830241 (17:03:50 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITest] Reset: fullReset not set. Leaving as is
[debug] [XCUITestDriver@19be (69240df7)] Event 'resetComplete' logged at 1695909830241 (17:03:50 GMT+0300 (Eastern European Summer Time))
[XCUITestDriver@19be (69240df7)] Using WDA path: '/Users/loree/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
[XCUITestDriver@19be (69240df7)] Using WDA agent: '/Users/loree/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[debug] [XCUITest] Crash reports root '/Users/loree/Library/Logs/CrashReporter/MobileDevice/Assist’s iPad (2)' does not exist. Got nothing to gather.
[debug] [XCUITestDriver@19be (69240df7)] Event 'logCaptureStarted' logged at 1695909830510 (17:03:50 GMT+0300 (Eastern European Summer Time))
[XCUITestDriver@19be (69240df7)] Setting up real device
[debug] [XCUITest] Verifying application platform
[debug] [XCUITest] CFBundleSupportedPlatforms: ["iPhoneOS"]
[XCUITestDriver@19be (69240df7)] App '' is already installed
[XCUITestDriver@19be (69240df7)] noReset is requested. The app will not be be (re)installed
[debug] [XCUITestDriver@19be (69240df7)] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[DevCon Factory] Requesting connection for device on local port 8100, device port 8100
[debug] [DevCon Factory] Cached connections count: 0
[DevCon Factory] Successfully requested the connection for :8100
[debug] [XCUITestDriver@19be (69240df7)] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"build":{"upgradedAt":"1695805786893","time":"Sep 28 2023 14:49:43","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iPadOS","sdkVersion":"17.0","version":"17.0.1"},"device":"ipad","ios":{"ip":"192.168.0.102"},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":"661A1A44-AC3F-45A5-A568-180F1607155A"}
[debug] [XCUITestDriver@19be (69240df7)] Upgrade timestamp of the currently bundled WDA: 1695805786893
[debug] [XCUITestDriver@19be (69240df7)] Upgrade timestamp of the WDA on the device: 1695805786893
[XCUITestDriver@19be (69240df7)] Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[debug] [XCUITestDriver@19be (69240df7)] Trying to start WebDriverAgent 1 times with 10000ms interval
[debug] [XCUITestDriver@19be (69240df7)] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
[debug] [XCUITestDriver@19be (69240df7)] Event 'wdaStartAttempted' logged at 1695909830881 (17:03:50 GMT+0300 (Eastern European Summer Time))
[XCUITestDriver@19be (69240df7)] Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
[debug] [WD Proxy] Matched '/status' to command name 'getStatus'
[debug] [WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[debug] [WD Proxy] Got response with status 200: {"value":{"build":{"upgradedAt":"1695805786893","time":"Sep 28 2023 14:49:43","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iPadOS","sdkVersion":"17.0","version":"17.0.1"},"device":"ipad","ios":{"ip":""},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":"661A1A44-AC3F-45A5-A568-180F1607155A"}
[debug] [XCUITestDriver@19be (69240df7)] Event 'wdaSessionAttempted' logged at 1695909830895 (17:03:50 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITestDriver@19be (69240df7)] Sending createSession command to WDA
[debug] [XCUITestDriver@19be (69240df7)] Matched '/session' to command name 'createSession'
[debug] [XCUITestDriver@19be (69240df7)] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"","arguments":["-AppleLanguages","(es)","-NSLanguages","(es)","-AppleLocale","es"],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":false,"forceAppLaunch":false,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":false}],"alwaysMatch":{}}}
[debug] [XCUITestDriver@19be (69240df7)] Got response with status 200: {"value":{"sessionId":"95EA3338-7FB3-4F39-A12F-400642EB5632","capabilities":{"sdkVersion":"17.0.1","device":"ipad"}},"sessionId":"95EA3338-7FB3-4F39-A12F-400642EB5632"}
[XCUITestDriver@19be (69240df7)] Determined the downstream protocol as 'W3C'
[debug] [XCUITestDriver@19be (69240df7)] Event 'wdaSessionStarted' logged at 1695909830914 (17:03:50 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITestDriver@19be (69240df7)] Event 'wdaStarted' logged at 1695909830914 (17:03:50 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITestDriver@19be (69240df7)] Setting initial orientation to 'PORTRAIT'
[debug] [XCUITestDriver@19be (69240df7)] Matched '/orientation' to command name 'setOrientation'
[debug] [XCUITestDriver@19be (69240df7)] Proxying [POST /orientation] to [POST http://127.0.0.1:8100/session/95EA3338-7FB3-4F39-A12F-400642EB5632/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [XCUITestDriver@19be (69240df7)] Got response with status 200: {"value":null,"sessionId":"95EA3338-7FB3-4F39-A12F-400642EB5632"}
[debug] [XCUITestDriver@19be (69240df7)] Event 'orientationSet' logged at 1695909830997 (17:03:50 GMT+0300 (Eastern European Summer Time))
[debug] [BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[AppiumDriver@3366] New XCUITestDriver session created successfully, session 69240df7-365a-4a61-b7e9-a5a75fa31a58 added to master session list
[debug] [AppiumDriver@3366] Event 'newSessionStarted' logged at 1695909830999 (17:03:50 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITestDriver@19be (69240df7)] Cached the protocol value 'W3C' for the new session 69240df7-365a-4a61-b7e9-a5a75fa31a58

**Comment by mykola-mokhnach** [comment]
> [debug] [XCUITestDriver@19be (69240df7)] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"","arguments":["-AppleLanguages","(es)","-NSLanguages","(es)","-AppleLocale","es"],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":false,"forceAppLaunch":false,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":false}],"alwaysMatch":{}}}

Capabilities are correct, although it might be the app is already running and thus such settings have no effect.
Either make sure the app is not running before starting the test or set `noReset` to `false`.

**Comment by lorecioata** [comment]
No reset reinstalls the app which I don't want to happen because it takes a really long time and I have loads of tests. 
Here are my steps:
1. Start server
2. Starting Session in Appium inspector in Spanish
3. The app starts in Spanish.
4. I start running a test suite which has multiple test methods.
5. The first test method runs in Spanish, it get tearDown (terminate_app(bundle_id)) and the second test method starts running but in English this time (the language of the device). 

As I previously stated, it used to run in the language set by me till the end of the test suite but it stopped working once I update the macOS, the iPadOS and xCode.

Please help me! The localized tests are the most important for my team.

**Comment by mykola-mokhnach** [comment]
try to set `forceAppLaunch` capability to true

**Comment by lorecioata** [comment]
It opens it in English.

**Comment by mykola-mokhnach** [comment]
It could be something is now broken there from Apple side. @KazuCocoa @Dan-Maor do you know about any changes?

**Comment by KazuCocoa** [comment]
it sounds like iOS 17 changed the behavior. Afaik, their release notes haven't addressed these. Let me check a few quickly for preinstalled settings app

**Comment by KazuCocoa** [comment]
Checked below for Safari. 
```
caps = {
  "platformName": "ios",
  "automationName": "xcuitest",
  "appium:udid": "00008020-000E5CDA0A23002E",
  "browserName": "safari",
  "language": "ja",
  "locale": "JP",
}
...
driver = core.start_driver # start a new session with Japanese, expected
...
driver.terminate_app 'com.apple.mobilesafari'
driver.quit

# then
driver = core.start_driver # to start a new session with Japanese, expected
```

> The first test method runs in Spanish, it get tearDown (terminate_app(bundle_id)) and the second test method starts running but in English this time (the language of the device).

I wonder if this meant your new session request was once, but others were via activate_app after the terminate_app. If so, you should launch an app via https://appium.github.io/appium-xcuitest-driver/5.4/execute-methods/#mobile-launchapp like `driver.execute_script 'mobile: launchApp', {bundleId: "com.apple.mobilesafari", arguments: ["-AppleLanguages","(ja)","-NSLanguages","(ja)","-AppleLocale","JP"]}` to start an app process with these arguments. (These arguments came from https://github.com/appium/appium/issues/19225#issuecomment-1739337093 )

If you just started an app process with activate_app, for example, then English is expected behavior. (Then, if that worked in iOS 16 and lower, I wonder the app process was not terminated? by XCTest. anyway this case also could be XCTest internal issue though)

**Comment by lorecioata** [comment]
I tried the driver.execute_script() as you recommended and now it works as expected. Thank you very much!! :)

My new session request was done once and then the others were with activate_app and terminate_app and since it worked in previous versions, I thought that was "the right way".

**Comment by mykola-mokhnach** [comment]
activateApp does not apply any arguments on app startup, so that behaviour is expected. 
Also, no usage of this API was visible from the included log.
Closed as not an issue.
