### ISSUE TITLE
Appium is able to locate an element only if there is a content description on it

### ISSUE THREAD

**Issue by yanislavg** [appium/appium#19228]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium 2.1.3 is not able to locate an element by Id although the element has id identificator.
Driver.FindElement(MobileBy.Id("email_TypedEditText")); returns errors#no-such-element-exception

![image](https://github.com/appium/appium/assets/6173779/c2cb8c5c-e2d6-491e-82aa-93297583a3f2)

NOTE: If the same element has a content-description the Appium is able to locate it by Id.

### Expected Behavior

Appium is able to locate any element using MobileBy.Id("identificator") or By.Id("identificator") despite content-description attribute!

NOTE; Appium server version 1.19.1 is able to locate the same element.

### Minimal Reproducible Example

var emailTextField = Driver.FindElement(MobileBy.Id("email_TypedEditText"));

### Environment

- Operating system: Windows
- Appium server version (output of `appium --version`): 2.1.3
- Appium driver(s) and their version(s): 2.29.10
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): 18.17.1
- `npm` version (output of `npm --version`): 10.1.0
- Last component(s) version which did _not_ exhibit the problem: Appium server 1.19.1
- Platform and version under test: Android 10.0
- Real device or emulator/simulator: simulator

### Further Information

[appium no such element by id log.txt](https://github.com/appium/appium/files/12763492/appium.no.such.element.by.id.log.txt)

**Comment by lorecioata** [comment]
Try to use: Driver.FindElement(By.Id("com.[abcds].app.automation:id/email_TypedEditText"));

**Comment by mykola-mokhnach** [comment]
Content description and resource id are different entities and required different locator types. Check https://github.com/appium/appium-uiautomator2-driver#element-location

Also, it might be the autodetected identifier prefix is not correct. In such case provide fully specified locators like it is described above.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by yanislavg** [comment]
Sorry for the delay. Even though the issue is closed I'll try to clarify and simplify cause apparently there is misunderstanding what actually the issiue is:
there is an android element with identificator and Appium 2.1.3 is not able to locate the given element By.Id nor By.MobileId. But when I put content-description on that same element "magically" the Appium 2.1.3 is now able to locate the element with By.Id or By.MobileId. Somehow the existence of content-description enables Appium 2.13 to locate that element. Please note I am not searching the element by content-description I am using the same Id strategy as before ( and I am aware of the different locator strategies).
Please also note that for ex. Appium 1.19.1 is able to locate the element By.Id or By.MobileId as the element itself has identificator and that is expected behaviour ( and the is no need to put content-description on it).
For me this is a strange issue with the new Appium 2 not able to locate given elements although they have identificator. For my example the problem is with the EditText fields.

**Comment by jlipps** [comment]
Do you see the element in the source before you attempt to find it? If so, then there must be some other way to find it. If not, you could try setting `appium:ignoreUnimportantViews` to `true` since it might change how Android decides what's important for accessibility. Seems like it might not have much effect though since that capability will show fewer views if anything.

**Comment by yanislavg** [comment]
As per shown at the screenshot above I am able to see the element via Inspector v2023.8.4 and more over I am able to find that same element using the Inspector by Id. Not sure why the Inspector and Appium server differ in behavior which for me is a inconsistency issue.

**Comment by jlipps** [comment]
If it's there in the Inspector, it's there in the server. The inspector just uses the server. It's only an appium client. If the element isn't there in your script it's likely a timing issue.
