### ISSUE TITLE
Appium 2 failed to set location for Android 10

### ISSUE THREAD

**Issue by jaswirs** [appium/appium#19238]
I am facing an issue where the `driver.setLocation()` does not work for Android 10 devices when using appium 2.0.1 (or using Appium Settings 5.x.x).  Such issue is not happened on other Android versions (9, 11, & 12) using the same appium version.

Looks like similar issue have been reported and closed before  https://github.com/appium/appium/issues/18043

### Environment
Appium version: v2.0.1
Node.js: v20.5.1
Npm: 9.8.0
**Android 10** - Both real device & android emulator
macOS 12.6.1

### Alternate manual steps to repro:

1. Install [appium settings](https://github.com/appium/io.appium.settings/releases) v5.x.x
2. Run these commands.
```
adb shell pm grant io.appium.settings android.permission.ACCESS_FINE_LOCATION
adb shell appops set io.appium.settings android:mock_location allow
adb shell am start-foreground-service -e longitude 103.9885585809751 -e latitude 1.3546854637089758 -e altitude 10 io.appium.settings/.LocationService
```
3. Verify the mocked location. E.q. `adb shell dumpsys location > dumpsys.txt`

I tried above scenario for both emulator Android 10 & 12;

- Android 12 : Location mocked successfully
- Android 10 : giving `Error: Not found; no service started`. The only related logcat is `W ActivityManager: Appop Denial: Accessing service io.appium.settings/.LocationService from pid=19371, uid=2000 requires appop FINE_LOCATION`. Though I have manually set the location permission to `allow all the time`. [android10_logcat.txt](https://github.com/appium/appium/files/12784682/android10_logcat.txt)

Several tickets for similar issues have been raised on appium settings [repo](https://github.com/appium/io.appium.settings/issues) as well but no response so far.

Issue is not happened when I installed Appium Settings v4.2.4. 
Since I need to use appium 2, is there any way to configure appium 2 so that it installs specific/desired Appium Settings version (e.q. 4.x.x)?

**Comment by mykola-mokhnach** [comment]
This might be an issue in Android itself. I can observe similar issue reports happening on Chinese phones: https://github.com/microg/GmsCore/issues/986

At least I have no idea on what could be changed in Appium settings to address the issue.

P. S. The main change since v4.2.4 was bumping of the minimum/target Android versions. We cannot make version pinning configurable as each driver version relies on partilcular features that the settings tool provides. The only way to use an older settings version is to downgrade the driver itself.

**Comment by jaswirs** [comment]
Will there be any concerns for removing `android:permission="android.permission.ACCESS_FINE_LOCATION"`  from `.LocationService`  as mentioned on [this](https://github.com/appium/io.appium.settings/issues/109#issuecomment-1517687202) post?

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/13802 might help to control the device's configuration/background service state

**Comment by jaswirs** [comment]
@KazuCocoa Yes, I was able to reproduce the issue on emulator as well.

**Comment by jccdg1995** [comment]
Encountered this also org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '~/Library/Android/sdk/platform-tools/adb -P 5037 -s 26184d7b27057ece shell am start-foreground-service -e longitude 103.8448 -e latitude 1.3709 -e altitude 0.1 io.appium.settings/.LocationService' exited with code 255'; Command output: Error: Not found; no service started.

Tried many ways to resolve but don't seem to be able to resolve this. Ran the same script on Android OS 13 and there wasn't any issues

**Comment by mthms** [comment]
Any updates here, please? Encountering the same on the latest java client as well

**Comment by mthms** [comment]
This issue seems extending to android 12 as well not just android 10.

**Comment by KazuCocoa** [comment]
Will https://github.com/appium/io.appium.settings/pull/128 help?

**Comment by KazuCocoa** [comment]
Perhaps https://github.com/appium/appium-adb/pull/715 and https://github.com/appium/appium-android-driver/pull/895 will fix some foreground service launches in a new session request.
I wondered if io.appium.settings process did not start from the `.Settings` activity, which start the package as a foreground service. These PRs will fix foreground service detection so that appium can start the settings app as a foreground service

**Comment by KazuCocoa** [comment]
Please try out uia2 driver 2.40.1. If the settings app launches as a foreground service, the no service error won't occur.
(A new session request fixed to detect the foreground service state, so it will launch the settings app activity if no the foreground app)

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by jaswirs** [comment]
Has anyone found the solution to this? I tried appium-settings [v5.12.23](https://github.com/appium/io.appium.settings/releases/tag/v5.12.23) and still able to reproduce this.
