### ISSUE TITLE
[Feat]: faster text input on iOS

### ISSUE THREAD

**Issue by colmaengus** [appium/appium#19245]
**Is your feature request related to a problem? Please describe.**
Using sendKeys with iOS devices is slow for interactive use.

**Describe the solution you'd like**
The [key handling in WDA](https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L556): includes a hardcoded timeout of 1 second, though if no visible keyboard is found after the timeout the keys are injected anyway. Changing the timeout to 0 would mean that keys are injected without a delay which would improve usability for interactive use cases.

Having a capability or setting to control this would be great as maybe changing the timeout isn't suitable for all use cases (though the hardcoding of 1 second seems a little arbitrary). Of course if a delay of 0 would work for all cases then changing the default would also work.

I'm using snapshotMaxDepth of 0 to improve interactive performance so the waitUntilVisibleForApplication call usually times out giving a key press latency of around 1100ms. Changing the timeout in handleKeys reduces the latency to around 360ms.

**Describe alternatives you've considered**
I can't see any other option to improve key handling since the remaining time in inside xcuitest.

**Comment by mykola-mokhnach** [comment]
I think you are right. There is no need to have that delay there: https://github.com/appium/WebDriverAgent/pull/784

**Comment by colmaengus** [comment]
I've also tried using W3C actions and they work well for sending keyboard events (even faster than sendKeys). However in both cases not having the virtual keyboard visible leads to around a 5 second delay but no error is thrown.

**Comment by mykola-mokhnach** [comment]
this is probably some internal xctest delay, not sure there is a way to tune that

**Comment by mykola-mokhnach** [comment]
The best way to address that would be to make sure the target input received the cursor/keyboard focus before typing anything

**Comment by DanMPerfecto** [comment]
> I've also tried using W3C actions and they work well for sending keyboard events (even faster than sendKeys). However in both cases not having the virtual keyboard visible leads to around a 5 second delay but no error is thrown.

This is because XCTest sends the key and then waits for 5 seconds until it receives a `KeyEventCompleted` event before injecting the next character. Given the first character wasn't injected an event wouldn't be sent, and thus waiting for the event would time out.

**Comment by mykola-mokhnach** [comment]
The patch has been merged
