### ISSUE TITLE
unable to connect real android with appium Inspector.

### ISSUE THREAD

**Issue by Rushann** [appium/appium#19249]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Previously i have connect my real device using same capabilities.But now i don't know why its showing error like this. Can't able to connect my Phone. 

### Expected Behavior

It should need to connect sucessfully.

### Minimal Reproducible Example

Try to connect real android device with appium Inspector.

### Environment

- Operating system:Mac
- Appium server version (output of `appium --version`):latest
- Appium driver(s) and their version(s):latest
- Appium plugin(s) and their version(s):latest
- Node.js version (output of `node --version`):18.6.1
- `npm` version (output of `npm --version`):9.5.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:iOS
- Real device or emulator/simulator:Real device
![Screenshot 2023-10-04 at 12 35 08 PM](https://github.com/appium/appium/assets/88871439/cf636ff8-5a32-490c-97fc-b00613ae48e5)

### Link to Appium Logs

rushan@Rushans-Mac-mini ~ % appium [Appium] Welcome to Appium v2.0.0 [Appium] Attempting to load driver xcuitest... [debug] [Appium] Requiring driver at /Users/rushan/.appium/node_modules/appium-xcuitest-driver [Appium] Attempting to load driver uiautomator2... [debug] [Appium] Requiring driver at /Users/rushan/.appium/node_modules/appium-uiautomator2-driver [Appium] Appium REST http interface listener started on http://0.0.0.0:4723 [Appium] You can provide the following URLS in your client code to connect to this server: [Appium] 	http://127.0.0.1:4723/ (only accessible from the same host) [Appium] 	http://192.168.1.4:4723/ [Appium] Available drivers: [Appium]   - xcuitest@4.32.19 (automationName 'XCUITest') [Appium]   - uiautomator2@2.29.2 (automationName 'UiAutomator2') [Appium] Available plugins: [Appium]   - execute-driver@3.0.14 [Appium]   - element-wait@2.0.3 [Appium]   - gestures@3.0.0 [Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate [HTTP] --> POST /session [HTTP] {"capabilities":{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"9","appium:deviceName":"Redmi Note 6 Pro","appium:automationName":"UiAutomator2","appium:appActivity":"com.hotake.hotake.MainActivity","appium:appPackage":"com.google.android.packageinstaller","appium:noReset":true,"appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","appium:platformVersion":"9","appium:deviceName":"Redmi Note 6 Pro","appium:automationName":"UiAutomator2","appium:appActivity":"com.hotake.hotake.MainActivity","appium:appPackage":"com.google.android.packageinstaller","appium:noReset":true,"appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}} [debug] [AppiumDriver@b4e1] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","appium:platformVersion":"9","appium:deviceName":"Redmi Note 6 Pro","appium:automationName":"UiAutomator2","appium:appActivity":"com.hotake.hotake.MainActivity","appium:appPackage":"com.google.android.packageinstaller","appium:noReset":true,"appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"9","appium:deviceName":"Redmi Note 6 Pro","appium:automationName":"UiAutomator2","appium:appActivity":"com.hotake.hotake.MainActivity","appium:appPackage":"com.google.android.packageinstaller","appium:noReset":true,"appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}] [debug] [AppiumDriver@b4e1] Event 'newSessionRequested' logged at 1696403085659 (12:34:45 GMT+0530 (India Standard Time)) [Appium] Attempting to find matching driver for automationName 'UiAutomator2' and platformName 'Android' [Appium] The 'uiautomator2' driver was installed and matched caps. [Appium] Will require it at /Users/rushan/.appium/node_modules/appium-uiautomator2-driver [debug] [Appium] Requiring driver at /Users/rushan/.appium/node_modules/appium-uiautomator2-driver [AppiumDriver@b4e1] Appium v2.0.0 creating new AndroidUiautomator2Driver (v2.29.2) session [AppiumDriver@b4e1] Checking BaseDriver versions for Appium and AndroidUiautomator2Driver [AppiumDriver@b4e1] Appium's BaseDriver version is 9.3.15 [AppiumDriver@b4e1] AndroidUiautomator2Driver's BaseDriver version is 9.3.15 [debug] [AndroidUiautomator2Driver@1e82] Creating session with W3C capabilities: { [debug] [AndroidUiautomator2Driver@1e82]   "alwaysMatch": { [debug] [AndroidUiautomator2Driver@1e82]     "platformName": "Android", [debug] [AndroidUiautomator2Driver@1e82]     "appium:platformVersion": "9", [debug] [AndroidUiautomator2Driver@1e82]     "appium:deviceName": "Redmi Note 6 Pro", [debug] [AndroidUiautomator2Driver@1e82]     "appium:automationName": "UiAutomator2", [debug] [AndroidUiautomator2Driver@1e82]     "appium:appActivity": "com.hotake.hotake.MainActivity", [debug] [AndroidUiautomator2Driver@1e82]     "appium:appPackage": "com.google.android.packageinstaller", [debug] [AndroidUiautomator2Driver@1e82]     "appium:noReset": true, [debug] [AndroidUiautomator2Driver@1e82]     "appium:ensureWebviewsHavePages": true, [debug] [AndroidUiautomator2Driver@1e82]     "appium:nativeWebScreenshot": true, [debug] [AndroidUiautomator2Driver@1e82]     "appium:newCommandTimeout": 3600, [debug] [AndroidUiautomator2Driver@1e82]     "appium:connectHardwareKeyboard": true [debug] [AndroidUiautomator2Driver@1e82]   }, [debug] [AndroidUiautomator2Driver@1e82]   "firstMatch": [ [debug] [AndroidUiautomator2Driver@1e82]     {} [debug] [AndroidUiautomator2Driver@1e82]   ] [debug] [AndroidUiautomator2Driver@1e82] } [AndroidUiautomator2Driver@1e82] The following capabilities were provided, but are not recognized by Appium: [AndroidUiautomator2Driver@1e82]   deviceName [AndroidUiautomator2Driver@1e82]   connectHardwareKeyboard [AndroidUiautomator2Driver@1e82 (07bdaa66)] Session created with session id: 07bdaa66-84df-4574-98f8-ccbb495b2a83 [AndroidUiautomator2Driver@1e82 (07bdaa66)] Starting 'com.google.android.packageinstaller' directly on the device [ADB] Found 2 'build-tools' folders under '/Users/rushan/Library/Android/sdk' (newest first): [ADB]     /Users/rushan/Library/Android/sdk/build-tools/34.0.0 [ADB]     /Users/rushan/Library/Android/sdk/build-tools/30.0.3 [ADB] Using 'adb' from '/Users/rushan/Library/Android/sdk/platform-tools/adb' [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 start-server' [AndroidDriver] Retrieving device list [debug] [ADB] Trying to find a connected android device [debug] [ADB] Getting connected devices [debug] [ADB] Connected devices: [{"udid":"258e023e","state":"device"}] [AndroidDriver] Looking for a device with Android '9.0.0' [debug] [ADB] Setting device id to 258e023e [ADB] Getting device platform version [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell getprop ro.build.version.release' [debug] [AndroidUiautomator2Driver@1e82 (07bdaa66)] Deleting UiAutomator2 session [debug] [AppiumDriver@b4e1] Event 'newSessionStarted' logged at 1696403105730 (12:35:05 GMT+0530 (India Standard Time)) [debug] [AppiumDriver@b4e1] Encountered internal error running command: Error: Error getting device platform version. Original error: Error executing adbExec. Original error: 'Command '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell getprop ro.build.version.release' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability [debug] [AppiumDriver@b4e1]     at ADB.getPlatformVersion (/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-adb/lib/tools/adb-commands.js:176:11) [debug] [AppiumDriver@b4e1]     at Object.getDeviceInfoFromCaps (/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/android-helpers.js:259:29) [debug] [AppiumDriver@b4e1]     at AndroidUiautomator2Driver.startUiAutomator2Session (/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/lib/driver.js:352:26) [debug] [AppiumDriver@b4e1]     at AndroidUiautomator2Driver.createSession (/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/lib/driver.js:241:7) [debug] [AppiumDriver@b4e1]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:346:35) [HTTP] <-- POST /session 500 20124 ms - 1174

**Comment by KazuCocoa** [comment]
What happens if you calls below command when the error occurs?

```
/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell getprop ro.build.version.release
```

I wondered if the device needed to be rebooted

**Comment by Rushann** [comment]
@KazuCocoa getting output 9.
Last login: Wed Oct  4 13:18:12 on ttys000
rushan@Rushans-Mac-mini ~ % /Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell getprop ro.build.version.release
9
rushan@Rushans-Mac-mini ~ % 

I tried by rebooting everything .

**Comment by KazuCocoa** [comment]
Thanks. How long did it take?

The appium log just waited for the result of `/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell getprop ro.build.version.release`, so the command might not show the result in 20000ms. I have no good idea about the slowness except host machine, device or adb server restart, but what could happen was the command did not show the result at that time.

**Comment by Rushann** [comment]
After starting the session its taking more than 1 and less than 2 minutes to show the error. The platform is 9. Here i have attached few more capabilities but still not working 
![Screenshot 2023-10-04 at 1 31 26 PM](https://github.com/appium/appium/assets/88871439/96393e3a-917e-4617-bafd-72a2a3f68f94)

**Comment by KazuCocoa** [comment]
_How long did it take?_ meant for https://github.com/appium/appium/issues/19249#issuecomment-1746326204 's adb command

**Comment by Rushann** [comment]
its giving result immediately @KazuCocoa

**Comment by mykola-mokhnach** [comment]
This seems like an issue with adb itself. Maybe try to update SDK and build tools to the latest version.

**Comment by Rushann** [comment]
From where or how to do this? @mykola-mokhnach Please provide me some steps .

**Comment by mykola-mokhnach** [comment]
Sorry, how to do what? How to replace the phone? I am confused

**Comment by Rushann** [comment]
@mykola-mokhnach how to perform this ? update SDK and build tools to the latest version.

**Comment by mykola-mokhnach** [comment]
There are multiple ways to do it - use Google. We also have Appium forum to ask questions.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
