### ISSUE TITLE
bug: <title>Error adb: device unauthorized during connecting with smartphones.

### ISSUE THREAD

**Issue by wojciu94** [appium/appium#19241]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I run a few smartphone tests on Jenkins. Almost every time the first test failed because of:
"Command output: adb: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong. "
This problem started showing after an update the appium server to version 2.1.3 (the previous version was 1.22.3). 
Very often the next test doesn't have this problem, so there is no general problem with adb connecting with smartphones. 

### Expected Behavior

No problem with connecting to smartphones via adb.

### Minimal Reproducible Example

Start the Instagram application with capabilities:

 Creating session with W3C capabilities: {
 "alwaysMatch": {
   "platformName": "Android",
   "appium:automationName": "UiAutomator2",
   "appium:platformVersion": "13",
   "appium:udid": "172.29.8.214:7417",
   "appium:appActivity": "com.instagram.android.activity.MainTabActivity",
   "appium:appPackage": "com.instagram.android",
   "appium:appWaitActivity": "com.instagram.mainactivity.MainActivity",
   "appium:forceAppLaunch": true,
   "appium:systemPort": 8200,
   "appium:noReset": true,
   "appium:newCommandTimeout": 1800

### Environment

- Operating system:
- Appium server version (output of `appium --version`): Appium v2.1.3
- Appium driver(s) and their version(s): uiautomator2@2.29.10 (automationName 'UiAutomator2')
- Appium plugin(s) and their version(s): Appium-Python-Client 2.11.1
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem: appium 1.22.3
- Platform and version under test: Device API level: 33
- Real device or emulator/simulator: real device Android 13

### Further Information

[2023-10-03_05-58-59_appium_server_smartphone.log](https://github.com/appium/appium/files/12790127/2023-10-03_05-58-59_appium_server_smartphone.log)

**Comment by mykola-mokhnach** [comment]
The error is expected. Devices must be authorized to ADB first. 

> Otherwise check for a confirmation dialog on your device.

Adb itself has a hint for it

**Comment by wojciu94** [comment]
The smartphone is authorized with the computer (the popup on a smartphone when it is connected to the PC and USB debugging is enabled and it was checked the always option).
I do nothing between tests and the second test doesn't have this problem, but the first does.
What hint does adb itself for that?

**Comment by KazuCocoa** [comment]
I wondered if the host missed `adbkey` and `adbkey.pub` in `~/.android/` (if not configured) somehow. Then, after restarting the adb server, connected devices start from an unauthorized state.  As below log in your attached one, I guess such possible removal was before the Appium process started.

Jenkins may have its own configuration, so the file may not be in ~/.android/`.

```
2023-10-03 05:59:04:821 [ADB]     /home/autjenkins/android/build-tools/33.0.1
2023-10-03 05:59:04:821 [ADB] Using 'adb' from '/home/autjenkins/android/platform-tools/adb'
2023-10-03 05:59:04:822 [ADB] Running '/home/autjenkins/android/platform-tools/adb -P 5037 start-server'
2023-10-03 05:59:04:829 [AndroidDriver] Retrieving device list
2023-10-03 05:59:04:829 [ADB] Trying to find connected Android devices
2023-10-03 05:59:04:829 [ADB] Getting connected devices
2023-10-03 05:59:04:835 [ADB] Connected devices: [{"udid":"172.29.8.214:7417","state":"unauthorized"},{"udid":"172.29.8.214:7441","state":"unauthorized"}]
2023-10-03 05:59:04:836 [AndroidDriver] Using device: 172.29.8.214:7417
2023-10-03 05:59:04:836 [ADB] Using 'adb' from '/home/autjenkins/android/platform-tools/adb'
```

**Comment by wojciu94** [comment]
Hi, I should have added that info earlier, but I forgot.
We use also the Device Farmer (OpenSTF) and those smartphones are fully operative via the OpenSTF Web page.
It looks like the Appium server 2.1.3 tries to connect with smartphones, but gets 'unauthorized':
2023-10-03 05:59:04:835 [ADB] Connected devices: [{"udid":"172.29.8.214:7417","state":"unauthorized"},{"udid":"172.29.8.214:7441","state":"unauthorized"}]
It was done very fast, maybe too fast. The time between the start of the connection to getting 'unauthorized'  is less than 0.1 s. Maybe this time should be longer?

**Comment by mykola-mokhnach** [comment]
🤷 

I can say for sure this is not something that could be addressed from Appium driver side. You could also use Appium forum to ask questions.

Closed as not an issue.
