### ISSUE TITLE
Could not start a new session

### ISSUE THREAD

**Issue by Nifargo** [appium/appium#19254]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

im testing android app with some webview pages and got this error:

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 117.0.5938.149 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome 

I set in my server code:
        server = new AppiumServiceBuilder()
                .withAppiumJS(new File("//usr//local//lib//node_modules//appium//build//lib//main.js"))
                .withIPAddress(ipAddress)
                .usingPort(Integer.parseInt(port))
                .withLogFile(new File("appium.log"))
                .withTimeout(Duration.ofSeconds(30))
                .withArgument(()->"--relaxed-security")
                .withArgument(()->"--allow-insecure=chromedriver_autodownload")
//                .withArgument(()->"--chromedriver-executable","/Users/nifargo/Downloads/chromedriver-mac-arm64/chromedriver")
                .build();
        server.start();
And now I don't see error message that - Automated Chromedriver download is disabled. Use ‘chromedriver_autodownload’ server feature to enable it

but I still faced with this error

here is a log of it - https://gist.github.com/Nifargo/2397c9bedf3367bc965b2803fab2f8c5

### Expected Behavior

expect that i can run my method -         WebElement feedbackWebTitle = new ChromeDriver().findElement(By.cssSelector("#title"));
        return feedbackWebTitle.getText();

in this code 
@Test
    @DisplayName("DAF-T14 Check feedback form after clicking it from profile page")
    public void ProfileAppFeedbackFlow() throws Exception {

        String expectedFeedbackTitle = "Feedback";
        String expectedFeedbackWebTitle = "What are your experiences with the DKV app?";

        var onboardingPage = new OnboardingPage();
        var onboardingLinearLayout = onboardingPage.clickSkipButton();
        var locationPopUp = onboardingLinearLayout.clickLaterButton();
        var analysisPopUp = locationPopUp.clickAllowAllTimeButton();
        analysisPopUp.clickActivateButton();
        var feedbackProfilePage = new DoYouLikePopUp().clickNoButton();

        Set<String> strcontext = null;
        try{
            strcontext = ((AndroidDriver) AppiumInit.getAppiumDriver()).getContextHandles();
            System.out.println("Found contexts size: '" + strcontext.size() + "'");
            for (String s :strcontext) {
                System.out.println("Found context: '" + s + "'");
                if (s.contains("WEBVIEW")) {
                    System.out.println("Switching context to: '" + s + "'");
                    ((AndroidDriver) AppiumInit.getAppiumDriver()).context(s);
                    break;
                }
            }
        } catch (Exception e){
            e.printStackTrace();
        }

        String currentContext = ((AndroidDriver) AppiumInit.getAppiumDriver()).getContext();
        System.out.println("Current Context: " + currentContext);

        Thread.sleep(3000);

       Thread.sleep(3000);
        Assertions.assertEquals(feedbackProfilePage.getFeedbackWebTitl(), expectedFeedbackWebTitle);
    }

### Minimal Reproducible Example

@Test
    @DisplayName("DAF-T14 Check feedback form after clicking it from profile page")
    public void ProfileAppFeedbackFlow() throws Exception {

        String expectedFeedbackTitle = "Feedback";
        String expectedFeedbackWebTitle = "What are your experiences with the DKV app?";

        var onboardingPage = new OnboardingPage();
        var onboardingLinearLayout = onboardingPage.clickSkipButton();
        var locationPopUp = onboardingLinearLayout.clickLaterButton();
        var analysisPopUp = locationPopUp.clickAllowAllTimeButton();
        analysisPopUp.clickActivateButton();
        var feedbackProfilePage = new DoYouLikePopUp().clickNoButton();

        Set<String> strcontext = null;
        try{
            strcontext = ((AndroidDriver) AppiumInit.getAppiumDriver()).getContextHandles();
            System.out.println("Found contexts size: '" + strcontext.size() + "'");
            for (String s :strcontext) {
                System.out.println("Found context: '" + s + "'");
                if (s.contains("WEBVIEW")) {
                    System.out.println("Switching context to: '" + s + "'");
                    ((AndroidDriver) AppiumInit.getAppiumDriver()).context(s);
                    break;
                }
            }
        } catch (Exception e){
            e.printStackTrace();
        }

        String currentContext = ((AndroidDriver) AppiumInit.getAppiumDriver()).getContext();
        System.out.println("Current Context: " + currentContext);

        Thread.sleep(3000);

       Thread.sleep(3000);
        Assertions.assertEquals(feedbackProfilePage.getFeedbackWebTitl(), expectedFeedbackWebTitle);
    }

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Please read https://github.com/appium/appium-uiautomator2-driver#hybrid-mode

**Comment by Nifargo** [comment]
fixed this error with command - brew install chromedriver

**Comment by mykola-mokhnach** [comment]
I am also not sure if the attached log corresponds to the issue report. I don't observe any errors there

**Comment by Nifargo** [comment]
you can find error on 557 line I think - 
2023-10-05 11:57:31:490 - [debug] [AppiumDriver@30c8] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started

**Comment by mykola-mokhnach** [comment]
This is not what is mentioned in the issue description. 

Nevertheless such exception is usually thrown if the remote session is not active anymore or has been terminated. 
There might be multiple reasons to it, for example the remote server crash or a network issue. Try to fetch the logcat output from the device under test for this time range, maybe it has some useful hints
