### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70

### ISSUE THREAD

**Issue by AnjanaCNair** [appium/appium#19250]

**Comment by AnjanaCNair** [comment]
macOS        	Ventura 13.5
xcode        	14.3.1
appium       	2.0.0
brew         	4.1.5
npm          	9.8.0
node         	20.5.1
java         	20.0.2
carthage     	0.39.0
appium-doctor	1.16.2
ios-deploy   	1.12.2

**Comment by AnjanaCNair** [comment]
I am trying to build wda using Automation and it gives above error , but when trying to do manually using appium inspector it works. 

Please suggest the possible reason for this issue

**Comment by mykola-mokhnach** [comment]
Please fill out your issue report properly according to the given template.
Also, please enable xcodebuild logging in the server logs

**Comment by mykola-mokhnach** [comment]
Unfortunately it is not possible to suggest anything without xcodebuld logs

**Comment by mykola-mokhnach** [comment]
Closed because of no response
