### ISSUE TITLE
Reset: failed to terminate Simulator application with id 

### ISSUE THREAD

**Issue by bronik** [appium/appium#19252]
### Do I have the most recent component updates?

- [x] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello everyone 
After update appium 1.22.3 -> 2.1.3 I found weird behaviour on iOS platform
After first test passed - my app should reinstall, but I'm getting error:

```
[debug] [simctl] Error running 'terminate': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Simulator device returned an error for the requested operation.
found nothing to terminate
Underlying error (domain=NSPOSIXErrorDomain, code=3):
	The operation couldn’t be completed. found nothing to terminate
	found nothing to terminate
[XCUITest] Reset: failed to terminate Simulator application with id "com.app.name"
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [XCUITestDriver@b970 (26fdf94a)] Event 'resetComplete' logged at 1696480668937 (07:37:48 GMT+0300 (Eastern European Summer Time))
```

I have no capabilities such as appium:noReset or appium:fullReset, so my app should reinstall after each test finished

### Expected Behavior

after each test app being deleted and reinstalled 

### Minimal Reproducible Example

- start test
- grant some permission (notification, for example)
- make test pass
- start second test
- check granted permissions on simulator
Actual result: permissions from prev session saved
Expected result: permissions from prev session dropped

### Environment

- Operating system: macOS Ventura 13.3.1
- Appium server version (output of `appium --version`): 2.1.3
- Appium driver(s) and their version(s): xcuitest@5.3.3 [installed (npm)]
- Appium plugin(s) and their version(s): no additional plugin installed
- Node.js version (output of `node --version`): v20.7.0
- `npm` version (output of `npm --version`): 10.1.0
- Last component(s) version which did _not_ exhibit the problem: didn't get the question. appium v1 doesn't have that issue
- Platform and version under test: ios 16.4, xcode 14.3
- Real device or emulator/simulator: simulator

### Further Information

https://gist.github.com/bronik/03a6c14c8accd94a632a93f48618b081

**Comment by mykola-mokhnach** [comment]
Does this log affect the test execution in any way? This is just an internal debug output

**Comment by bronik** [comment]
actually it does 
as I mentioned above - permissions doesn't clean after each test, so my 2nd test(and all next tests) will fails

maybe I didn't pay attention on this log in appium 1, but behaviour of test run changed after I update appium to v.2.x

more interesting, that I have 3 different CI servers. 2 of them facing this issue, but 3rd works fine
all of the servers were updated in same way from appium 1 to 2 (delete appium1, install appium2, install drivers, update drivers, profit)

one more: when I add fullReset:true capability, everything work like a charm (app being cleaned as expected)
and one more:) : this behaviour doesn't occur on android platform. 

I can try reset permission using mobile:resetPermission, but I still believe that we can figure what exactly leads to my current behaviour

**Comment by mykola-mokhnach** [comment]
Please provide the full log. I would expect the app under test to be uninstalled and then freshly installed in noReset is not enabled. This should also reset its permissions.

**Comment by bronik** [comment]
too many string to change in appium.log file :) 

I have last question: does this log looks normal to you?

`2023-10-05 08:44:42:147 [XCUITest] Reset requested. Removing app with id 'com.my.app' from the device
2023-10-05 08:44:42:409 [XCUITest] Installing 'appPath.app' on Simulator with UUID 'DB3793C9-A854-4DAD-956B-795381336271'...
2023-10-05 08:44:43:437 [XCUITest] The app has been installed successfully.`


actually I see **Reset requested**, but I can't find any status of this action. (as like install says: **The app has been installed successfully**)

**Comment by mykola-mokhnach** [comment]
The above log lines look fine to me - the app has been reinstalled, so its data should be properly reset

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
