### ISSUE TITLE
 I'm getting an error when trying to install webdriveragent on my iOS 17.0 device. 

### ISSUE THREAD

**Issue by hakantektas** [appium/appium#19268]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium 2.x and Xcode 15, ventura 13.5.2
I'm getting an error when trying to install webdriveragent on my iOS 17.0 device. Also, when the integrationApp is built, it fails. I'm getting xcode 70 error when trying to run a test on my iOS 17 real device. Cannot install webdriveragent runner.

### Expected Behavior

Running tests on my iOS 17 device

### Minimal Reproducible Example

The problem with '\n' is solved, Very grateful for your help. And I am facing a new issue, xcodebuild exited with code '65' and signal 'null' when start a new session with iOS 17.0 Simulator.
Is this a known issue with xcode 15?

<img width="876" alt="Screenshot 2023-10-02 at 10 54 45" src="https://github.com/appium/appium/assets/72494835/7c78ccef-bde3-4497-9cf1-6ee36ee5d517">
<img width="378" alt="Screenshot 2023-10-02 at 10 53 07" src="https://github.com/appium/appium/assets/72494835/b8af88d9-32ab-4b18-be6e-65ab9c21d7dd">

### Environment

- Operating system: ventura 13.5.2
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s): xcuitest@5.6.0  , uiautomator2@2.29.10 ,mac2@1.8.2
- Appium plugin(s) and their version(s):images@2.1.4 
- Node.js version (output of `node --version`): v20.4.0
- `npm` version (output of `npm --version`):9.8.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: XCode 15
- Real device or emulator/simulator: iOS 17 reel device

**Comment by mykola-mokhnach** [comment]
Please provide the server log with xcodebuild logging enabled. 

Screenshots above look like there are issues with digital signing. Try to delete Xcode caches and make sure both the app under test and WDA are signed properly

**Comment by hakantektas** [comment]
I cleared all caches in the ~/DriverData files and ran it again, the problem was solved. The integration app error continues, I think it is related to XCode.
