### ISSUE TITLE
Unable to Install Appium in Ubuntu

### ISSUE THREAD

**Issue by RYenike** [appium/appium#19262]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to install Appium in Ubuntu

ram@administrator-Latitude-3420:~$ npm i --location=global appium
npm WARN deprecated typedoc-plugin-resolve-crossmodule-references@0.3.3: Upgrade to typedoc >= 0.24 and remove typedoc-plugin-resolve-crossmodule-references from your dependencies
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/appium
npm ERR! command failed
npm ERR! command sh -c node ./scripts/autoinstall-extensions.js

### Expected Behavior

Appium to be successfully install

### Minimal Reproducible Example

npm i --location=global appium
npm WARN deprecated typedoc-plugin-resolve-crossmodule-references@0.3.3: Upgrade to typedoc >= 0.24 and remove typedoc-plugin-resolve-crossmodule-references from your dependencies
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/appium
npm ERR! command failed
npm ERR! command sh -c node ./scripts/autoinstall-extensions.js

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):18.18.0
- `npm` version (output of `npm --version`):9.8.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

npm i --location=global appium
npm WARN deprecated typedoc-plugin-resolve-crossmodule-references@0.3.3: Upgrade to typedoc >= 0.24 and remove typedoc-plugin-resolve-crossmodule-references from your dependencies
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/appium
npm ERR! command failed
npm ERR! command sh -c node ./scripts/autoinstall-extensions.js

**Comment by mykola-mokhnach** [comment]
Please provide the full error report. NPM should also generate a detailed debug log

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by jpmorrison** [comment]
@RYenike I had the same issue with the snap store version of node.js

In the system logs I saw apparmor denying snap-confine every time npm i failed. 

See: https://github.com/nodejs/snap/issues/56  

I'm pretty sure this is the problem: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1849753

After I removed the snap version and installed the .deb packages from nodesource.com appium installed
