### ISSUE TITLE
bug: unable to boot android emulators using appium-adb

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#19266]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm currently using appium-adb module to boot emulators for one of the plugins. I bumped into an issue on emulator boot ready check. 

Please check the gist for all the information. 

https://gist.github.com/saikrishna321/bd0b487dd312b2659c8757e7982e7e3f

### Expected Behavior

Should be able boot emulators without any errors.

### Minimal Reproducible Example

https://gist.github.com/saikrishna321/bd0b487dd312b2659c8757e7982e7e3f?permalink_comment_id=4717521#gistcomment-4717521

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.1.3
- Appium driver(s) and their version(s): 
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v16.18.1
- `npm` version (output of `npm --version`): 8.19.3
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Android
- Real device or emulator/simulator: emulator

**Comment by mykola-mokhnach** [comment]
The patch has been published

**Comment by saikrishna321** [comment]
@mykola-mokhnach Thanks works fine now.
