### ISSUE TITLE
Using ActionChains to report an error, the error message is：Encountered internal error running command: io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Unable to perform W3C actions. Check the logcat output for possible error reports and make sure your input actions chain is valid.

### ISSUE THREAD

**Issue by Jermin2020** [appium/appium#19269]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Double click the element on the mobile end

### Expected Behavior

normal operation

### Minimal Reproducible Example

actions = ActionChains(driver)
actions.click(ele)
actions.click(ele).perform()

### Environment

[Appium] Welcome to Appium v2.0.1
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\zm-ye\node_modules\appium-uiautomator2-driver
[Appium] Attempting to load driver chromium...
[debug] [Appium] Requiring driver at C:\Users\zm-ye\node_modules\appium-chromium-driver
[Appium] Attempting to load driver windows...
[debug] [Appium] Requiring driver at C:\Users\zm-ye\node_modules\appium-windows-driver
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLS in your client code to connect to this server:
[Appium]        http://192.168.82.157:4723/
[Appium]        http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] Available drivers:
[Appium]   - uiautomator2@2.29.2 (automationName 'UiAutomator2')
[Appium]   - chromium@1.1.55 (automationName 'Chromium')
[Appium]   - windows@2.12.2 (automationName 'Windows')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.

### Further Information

[debug] [AndroidUiautomator2Driver@405c (ea36e817)] Proxying [POST /actions] to [POST http://127.0.0.1:60981/session/56ac8cf1-13da-49a9-9abd-97009206666e/actions] with body: {"actions":[{"type":"pointer","parameters":{"pointerType":"touch"},"id":"mouse","actions":[{"type":"pointerMove","duration":250,"x":0,"y":0,"origin":{"ELEMENT":"00000000-0000-3f5f-0000-031500000003","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-3f5f-0000-031500000003"}},{"type":"pointerDown","duration":0,"button":0},{"type":"pointerUp","duration":0,"button":0},{"type":"pointerMove","duration":250,"x":0,"y":0,"origin":{"ELEMENT":"00000000-0000-3f5f-0000-031500000003","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-3f5f-0000-031500000003"}},{"type":"pointerDown","duration":0,"button":0},{"type":"pointerUp","duration":0,"button":0}]},{"type":"key","id":"key","actions":[{"type":"pause","duration":0},{"type":"pause","duration":0},{"type":"pause","duration":0},{"type":"pause","duration":0},{"type":"pause","duration":0},{"type":"pause","duration":0}]}]}
[AndroidUiautomator2Driver@5a13 (109089ce)] Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [ADB] Creating ADB subprocess with args: ["-P","5037","-s","C7YNW19C04000184","shell","am","instrument","-w","-e","disableAnalytics",true,"io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [AndroidUiautomator2Driver@5a13 (109089ce)] Matched '/status' to command name 'getStatus'
[debug] [AndroidUiautomator2Driver@5a13 (109089ce)] Proxying [GET /status] to [GET http://127.0.0.1:60787/status] with no body
[AndroidUiautomator2Driver@5a13 (109089ce)] connect ECONNREFUSED 127.0.0.1:60787
[AndroidUiautomator2Driver@405c (ea36e817)] Got response with status 400: {"sessionId":"56ac8cf1-13da-49a9-9abd-97009206666e","value":{"error":"invalid element state","message":"Unable to perform W3C actions. Check the logcat output for possible error reports and make sure your input actions chain is valid.","stacktrace":"io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Unable to perform W3C actions. Check the logcat output for possible error reports and make sure your input actions chain is valid.\n\tat io.appium.uiautomator2.handler.W3CActions.safeHandle(W3CActions.java:82)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:277)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:271)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.ch...
[debug] [W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[debug] [AndroidUiautomator2Driver@405c (ea36e817)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Unable to perform W3C actions. Check the logcat output for possible error reports and make sure your input actions chain is valid.
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.appium.uiautomator2.handler.W3CActions.safeHandle(W3CActions.java:82)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:277)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:271)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]     at java.lang.Thread.run(Thread.java:929)
[debug] [AndroidUiautomator2Driver@405c (ea36e817)]
[HTTP] <-- POST /session/ea36e817-6e66-420f-8b74-1ae8ea2570a9/actions 400 722 ms - 3890

**Comment by mykola-mokhnach** [comment]
- Please provide the logcat output
- Make sure the uia2 driver is updated to the most recent version

**Comment by mykola-mokhnach** [comment]
You could also use gesture shortcuts as a workaround: https://github.com/appium/appium-uiautomator2-driver#mobile-gesture-commands

**Comment by Jermin2020** [comment]
> * Please provide the logcat output
> * Make sure the uia2 driver is updated to the most recent version

[appium.log](https://github.com/appium/appium/files/12843427/appium.log)

**Comment by Jermin2020** [comment]
> You could also use gesture shortcuts as a workaround: https://github.com/appium/appium-uiautomator2-driver#mobile-gesture-commands



> You could also use gesture shortcuts as a workaround: https://github.com/appium/appium-uiautomator2-driver#mobile-gesture-commands

Using this can indeed solve the problem

**Comment by mykola-mokhnach** [comment]
> > * Please provide the logcat output
> > * Make sure the uia2 driver is updated to the most recent version
> 
> [appium.log](https://github.com/appium/appium/files/12843427/appium.log)

Unfortunately the attached file has zero bytes in size. Also note the logcat output is not the same as Appium server log.

**Comment by Jermin2020** [comment]
> > > * Please provide the logcat output
> > > * Make sure the uia2 driver is updated to the most recent version
> > 
> > 
> > [appium.log](https://github.com/appium/appium/files/12843427/appium.log)
> 
> Unfortunately the attached file has zero bytes in size. Also note the logcat output is not the same as Appium server log.

Sorry, I don't quite understand where to obtain the log output

**Comment by mykola-mokhnach** [comment]
I believe google can help there: https://www.google.com/search?q=logcat

**Comment by Jermin2020** [comment]
> I believe google can help there: https://www.google.com/search?q=logcat

Thank you.see if this log meets the requirements
[appium.log](https://github.com/appium/appium/files/12844002/appium.log)
[logcat.txt](https://github.com/appium/appium/files/12844003/logcat.txt)

**Comment by Jermin2020** [comment]
> I don't see any traces in the logcat output. Was it taken within a proper time range?

Yes, the timestamp inside is accurate

**Comment by Jermin2020** [comment]
The logcat output command is:  adb logcat -d -v time > C:\Users\zm-ye\Desktop\logcat.txt

**Comment by mykola-mokhnach** [comment]
It is not about timestamp, but about the time period while the test was running.

**Comment by Jermin2020** [comment]
resolve it in a different way

You could also use gesture shortcuts as a workaround: https://github.com/appium/appium-uiautomator2-driver#mobile-gesture-commands
