### ISSUE TITLE
Uiautomator issue and appium please i need help

### ISSUE THREAD

**Issue by amclaire** [appium/appium#19272]
i created a program in python to open mobile app on my emulator , this program runs great on my personal pc where i created and compiled it but the, i took this program to another device 
my purchased dedicated server to run it , it keeps giving me the error below
below is the full log 

Microsoft Windows [Version 10.0.17763.1339]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>appium --use-plugins uiautomator2
[Appium] Welcome to Appium v2.1.3
[Appium] Non-default server args:
[Appium] {
[Appium]   usePlugins: [
[Appium]     'uiautomator2'
[Appium]   ]
[Appium] }
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\Administrator\.appium\node_modules\appium-uiautomator2-driver
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium] 127.0.0.1:4723/ (only accessible from the same host)
[Appium] Available drivers:
[Appium]   - uiautomator2@2.29.10 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[debug] [HTTP] Request idempotency key: 2437d19a-753c-4331-a974-384e8a8e72a5
[HTTP] --> POST /session
[HTTP] {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"Android","appium:skipServerInstallation":true,"appium:automationName":"UiAutomator2","appium:udid":"127.0.0.1:21503","appium:appPackage":"com.blissfulmeet.com","appium:appActivity":"com.blissfulmeet.com.MainActivity","appium:uiautomator2ServerInstallTimeout":600000,"appium:newCommandTimeout":1800,"appium:adbExecTimeout":600000,"appium:uiautomator2ServerReadTimeout":600000,"appium:settings[waitForIdleTimeout]":60000,"appium:settings[waitForSelectorTimeout]":60000,"appium:uiautomator2ServerLaunchTimeout":600000}}}
[debug] [AppiumDriver@90b8] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"Android","appium:skipServerInstallation":true,"appium:automationName":"UiAutomator2","appium:udid":"127.0.0.1:21503","appium:appPackage":"com.blissfulmeet.com","appium:appActivity":"com.blissfulmeet.com.MainActivity","appium:uiautomator2ServerInstallTimeout":600000,"appium:newCommandTimeout":1800,"appium:adbExecTimeout":600000,"appium:uiautomator2ServerReadTimeout":600000,"appium:settings[waitForIdleTimeout]":60000,"appium:settings[waitForSelectorTimeout]":60000,"appium:uiautomator2ServerLaunchTimeout":600000}}]
[debug] [AppiumDriver@90b8] Event 'newSessionRequested' logged at 1696866558841 (08:49:18 GMT-0700 (Pacific Daylight Time))
[Appium] Attempting to find matching driver for automationName 'UiAutomator2' and platformName 'Android'
[Appium] The 'uiautomator2' driver was installed and matched caps.
[Appium] Will require it at C:\Users\Administrator\.appium\node_modules\appium-uiautomator2-driver
[debug] [Appium] Requiring driver at C:\Users\Administrator\.appium\node_modules\appium-uiautomator2-driver
[AppiumDriver@90b8] Appium v2.1.3 creating new AndroidUiautomator2Driver (v2.29.10) session
[AppiumDriver@90b8] Checking BaseDriver versions for Appium and AndroidUiautomator2Driver
[AppiumDriver@90b8] Appium's BaseDriver version is 9.3.20
[AppiumDriver@90b8] AndroidUiautomator2Driver's BaseDriver version is 9.3.20
[debug] [AndroidUiautomator2Driver@465a] Creating session with W3C capabilities: {
[debug] [AndroidUiautomator2Driver@465a]   "alwaysMatch": {
[debug] [AndroidUiautomator2Driver@465a]     "platformName": "Android",
[debug] [AndroidUiautomator2Driver@465a]     "appium:skipServerInstallation": true,
[debug] [AndroidUiautomator2Driver@465a]     "appium:automationName": "UiAutomator2",
[debug] [AndroidUiautomator2Driver@465a]     "appium:udid": "127.0.0.1:21503",
[debug] [AndroidUiautomator2Driver@465a]     "appium:appPackage": "com.blissfulmeet.com",
[debug] [AndroidUiautomator2Driver@465a]     "appium:appActivity": "com.blissfulmeet.com.MainActivity",
[debug] [AndroidUiautomator2Driver@465a]     "appium:uiautomator2ServerInstallTimeout": 600000,
[debug] [AndroidUiautomator2Driver@465a]     "appium:newCommandTimeout": 1800,
[debug] [AndroidUiautomator2Driver@465a]     "appium:adbExecTimeout": 600000,
[debug] [AndroidUiautomator2Driver@465a]     "appium:uiautomator2ServerReadTimeout": 600000,
[debug] [AndroidUiautomator2Driver@465a]     "appium:uiautomator2ServerLaunchTimeout": 600000
[debug] [AndroidUiautomator2Driver@465a]   },
[debug] [AndroidUiautomator2Driver@465a]   "firstMatch": [
[debug] [AndroidUiautomator2Driver@465a]     {}
[debug] [AndroidUiautomator2Driver@465a]   ]
[debug] [AndroidUiautomator2Driver@465a] }
[AndroidUiautomator2Driver@465a (fff0daa9)] Session created with session id: fff0daa9-cf4c-4b78-885e-807d841cd15c
[AndroidUiautomator2Driver@465a (fff0daa9)] Starting 'com.blissfulmeet.com' directly on the device
[ADB] Found 1 'build-tools' folders under 'C:\Users\Administrator\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:\Users\Administrator\AppData\Local\Android\Sdk\build-tools\34.0.0
[ADB] Using 'adb.exe' from 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find connected Android devices
[debug] [ADB] Getting connected devices
[debug] [ADB] Connected devices: [{"udid":"127.0.0.1:21503","state":"device"}]
[AndroidDriver] Using device: 127.0.0.1:21503
[ADB] Using 'adb.exe' from 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[debug] [ADB] Setting device id to 127.0.0.1:21503
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1:21503 shell getprop ro.build.version.sdk'
[debug] [ADB] Current device property 'ro.build.version.sdk': 25
[debug] [ADB] Device API level: 25
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Getting package info for 'io.appium.settings'
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1:21503 shell dumpsys package io.appium.settings'
[debug] [ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('5.1.2' >= '5.1.2')
[debug] [ADB] There is no need to install/upgrade 'C:\Users\Administrator\.appium\node_modules\appium-uiautomator2-driver\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [ADB] Getting IDs of all 'io.appium.settings' processes
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1\:21503 shell 'pgrep --help; echo $?''
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1\:21503 shell 'pgrep ^appium\\.settings$ || pgrep ^io\\.appium\\.setti$''
[debug] [AndroidDriver] io.appium.settings is already running. There is no need to reset its permissions.
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1:21503 shell appops set io.appium.settings android:mock_location allow'
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1\:21503 shell "[ -e '/data/local/tmp/mock_apps.json' ] && echo __PASS__"'
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1:21503 shell cat /data/local/tmp/mock_apps.json'
[debug] [Logcat] Starting logs capture with command: C:\\Users\\Administrator\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 127.0.0.1\:21503 logcat -v threadtime
[debug] [AndroidUiautomator2Driver@465a (fff0daa9)] Forwarding UiAutomator2 Server port 6790 to local port 8200
[debug] [ADB] Forwarding system: 8200 to device: 6790
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1:21503 forward tcp:8200 tcp:6790'
[AndroidUiautomator2Driver@465a (fff0daa9)] 'skipServerInstallation' is set. Skipping UIAutomator2 server installation.
[debug] [AndroidUiautomator2Driver@465a (fff0daa9)] No app capability. Assuming it is already on the device
[debug] [ADB] Getting install status for com.blissfulmeet.com
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1:21503 shell pm path com.blissfulmeet.com'
[debug] [ADB] 'com.blissfulmeet.com' is installed
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1:21503 shell am force-stop com.blissfulmeet.com'
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1:21503 shell pm clear com.blissfulmeet.com'
[debug] [AndroidDriver] Performed fast reset on the installed 'com.blissfulmeet.com' application (stop and clear)
[debug] [AndroidUiautomator2Driver@465a (fff0daa9)] Performing shallow cleanup of automation leftovers
[debug] [AndroidUiautomator2Driver@465a (fff0daa9)] No obsolete sessions have been detected (socket hang up)
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1:21503 shell am force-stop io.appium.uiautomator2.server.test'
[AndroidUiautomator2Driver@465a (fff0daa9)] 'skipServerInstallation' is set. Attempting to use UIAutomator2 server from the device
[AndroidUiautomator2Driver@465a (fff0daa9)] Waiting up to 600000ms for UiAutomator2 to be online...
[debug] [ADB] Creating ADB subprocess with args: ["-P","5037","-s","127.0.0.1:21503","shell","am","instrument","-w","-e","disableAnalytics",true,"io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [AndroidUiautomator2Driver@465a (fff0daa9)] Matched '/status' to command name 'getStatus'
[debug] [AndroidUiautomator2Driver@465a (fff0daa9)] Proxying [GET /status] to [GET 127.0.0.1:8200/status] with no body
[AndroidUiautomator2Driver@465a (fff0daa9)] socket hang up
[debug] [Instrumentation] android.util.AndroidException: INSTRUMENTATION_FAILED: io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner
[debug] [Instrumentation]       at com.android.commands.am.Am.runInstrument(Am.java:898)
[debug] [Instrumentation]       at com.android.commands.am.Am.onRun(Am.java:406)
[debug] [Instrumentation]       at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
[debug] [Instrumentation]       at com.android.commands.am.Am.main(Am.java:124)
[debug] [Instrumentation]       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[debug] [Instrumentation] INSTRUMENTATION_STATUS: id=ActivityManagerService
[debug] [Instrumentation] INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner}
[debug] [Instrumentation] INSTRUMENTATION_STATUS_CODE: -1
[debug] [Instrumentation] at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
[debug] [Instrumentation] The process has exited with code 1
[AndroidUiautomator2Driver@465a (fff0daa9)] The instrumentation process has been unexpectedly terminated. Retrying UiAutomator2 startup (#1 of 1)
[debug] [AndroidUiautomator2Driver@465a (fff0daa9)] Performing strict cleanup of automation leftovers
[debug] [AndroidUiautomator2Driver@465a (fff0daa9)] No obsolete sessions have been detected (socket hang up)
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1:21503 shell am force-stop io.appium.uiautomator2.server.test'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting IDs of all 'uiautomator' processes
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1\:21503 shell 'pgrep ^uiautomator$ || pgrep ^uiautomator$''
[ADB] No 'uiautomator' process has been found
[AndroidUiautomator2Driver@465a (fff0daa9)] Waiting up to 600000ms for UiAutomator2 to be online...
[debug] [ADB] Creating ADB subprocess with args: ["-P","5037","-s","127.0.0.1:21503","shell","am","instrument","-w","-e","disableAnalytics",true,"io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [AndroidUiautomator2Driver@465a (fff0daa9)] Matched '/status' to command name 'getStatus'
[debug] [AndroidUiautomator2Driver@465a (fff0daa9)] Proxying [GET /status] to [GET 127.0.0.1:8200/status] with no body
[AndroidUiautomator2Driver@465a (fff0daa9)] socket hang up
[debug] [Instrumentation] android.util.AndroidException: INSTRUMENTATION_FAILED: io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner
[debug] [Instrumentation] INSTRUMENTATION_STATUS: id=ActivityManagerService
[debug] [Instrumentation] INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner}
[debug] [Instrumentation] INSTRUMENTATION_STATUS_CODE: -1
[debug] [Instrumentation] at com.android.commands.am.Am.runInstrument(Am.java:898)
[debug] [Instrumentation]       at com.android.commands.am.Am.onRun(Am.java:406)
[debug] [Instrumentation]       at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
[debug] [Instrumentation]       at com.android.commands.am.Am.main(Am.java:124)
[debug] [Instrumentation]       at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[debug] [Instrumentation]       at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
[debug] [Instrumentation] The process has exited with code 1
[AndroidUiautomator2Driver@465a (fff0daa9)] The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
[debug] [AndroidUiautomator2Driver@465a (fff0daa9)] Deleting UiAutomator2 session
[debug] [AndroidUiautomator2Driver@465a (fff0daa9)] Deleting UiAutomator2 server session
[AndroidUiautomator2Driver@465a (fff0daa9)] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'DELETE /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1:21503 shell am force-stop com.blissfulmeet.com'
[debug] [Logcat] Stopping logcat capture
[debug] [ADB] Removing forwarded port socket connection: 8200
[debug] [ADB] Running 'C:\Users\Administrator\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 127.0.0.1:21503 forward --remove tcp:8200'
[debug] [AppiumDriver@90b8] Event 'newSessionStarted' logged at 1696866567272 (08:49:27 GMT-0700 (Pacific Daylight Time))
[debug] [AppiumDriver@90b8] Encountered internal error running command: Error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
[debug] [AppiumDriver@90b8]     at Object.errorAndThrow (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\support\lib\logging.js:115:34)
[debug] [AppiumDriver@90b8]     at UiAutomator2Server.startSession (C:\Users\Administrator\.appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:249:18)
[debug] [AppiumDriver@90b8]     at AndroidUiautomator2Driver.startUiAutomator2Session (C:\Users\Administrator\.appium\node_modules\appium-uiautomator2-driver\lib\driver.js:430:5)
[debug] [AppiumDriver@90b8]     at AndroidUiautomator2Driver.createSession (C:\Users\Administrator\.appium\node_modules\appium-uiautomator2-driver\lib\driver.js:241:7)
[debug] [AppiumDriver@90b8]     at AppiumDriver.createSession (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\lib\appium.js:374:35)
[HTTP] <-- POST /session 500 8497 ms - 856
[HTTP]

**Comment by mykola-mokhnach** [comment]
> [AndroidUiautomator2Driver@465a (fff0daa9)] 'skipServerInstallation' is set. Attempting to use UIAutomator2 server from the device

You get what you ask. Are UIA2 server binaries installed on the device under test?

**Comment by amclaire** [comment]
> > [AndroidUiautomator2Driver@465a (fff0daa9)] 'skipServerInstallation' is set. Attempting to use UIAutomator2 server from the device
> 
> You get what you ask. Are UIA2 server binaries installed on the device under test?

i installed this first https://github.com/appium/appium-uiautomator2-server/releases/tag/v5.12.6"
before running the test

**Comment by mykola-mokhnach** [comment]
Maybe something is still missing otherwise it wouldn't compain

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
