### ISSUE TITLE
！！！HELP：About XCTAutomationSupport.framework file of xcode15.

### ISSUE THREAD

**Issue by summerlife** [appium/appium#19278]
When I used xcode15 to build webdriveragent, I got an error. I initially suspected that it was caused by the lack of the XCTAutomationSupport.framework file of xcode15. I couldn't find the relevant files online. Can anyone provide the relevant files?

**Comment by amedvedjev** [comment]
and your version of xcuitest Appium driver is 5.6.0 ?

**Comment by KazuCocoa** [comment]
Please try out the latext XCUITest as https://github.com/appium/appium/issues/19278#issuecomment-1755167447
Old ones such as Appium 1.22.3 might have the issue
https://github.com/search?q=repo%3Aappium%2Fappium+XCTAutomationSupport&type=issues

**Comment by summerlife** [comment]
Appium does not apply to me, so I must need XCTAutomationSupport.framework that is applicable to xcode15. I really need help. Can anyone help? Thanks

**Comment by KazuCocoa** [comment]
Have you used the latest Appium and XCUITest driver?
https://appium.github.io/appium-xcuitest-driver/5.6/setup/

The file was provided by Xcode, not Appium. I guessed you addressed https://github.com/appium/appium/issues/17174 error but if not, please create a bug issue by following the template.
