### ISSUE TITLE
Appium cannot find the page label

### ISSUE THREAD

**Issue by JiuJiang-w** [appium/appium#19287]
hello，On the Appnum page, keyboard input can be used, and input boxes can also be seen on the page. However, driver. getPageSource() does not have an EditText tag, and the corresponding label displayed in the corresponding position is the LinearLayout tag. It is also impossible to navigate to the input box, and the sendkeys() method cannot be used

All interactive elements on the page cannot be found, such as text tags, button tags, and EditText tags. However, these elements on the page can be seen and manually operated, but Appium cannot obtain and locate them. Even if it is getPageSoul, the elements cannot be found

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description according to the given template

**Comment by JiuJiang-w** [comment]
hello，On the Appnum page, keyboard input can be used, and input boxes can also be seen on the page. However, driver. getPageSource() does not have an EditText tag, and the corresponding label displayed in the corresponding position is the LinearLayout tag. It is also impossible to navigate to the input box, and the sendkeys() method cannot be used

**Comment by mykola-mokhnach** [comment]
unfortunately the above description is not sufficient to advice anything

**Comment by mykola-mokhnach** [comment]
Closed because of no response
