### ISSUE TITLE
error invalid json value: "'{wdaLocalPort:" when trying to run Appium server with default capability

### ISSUE THREAD

**Issue by hangbuitb96** [appium/appium#19289]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I tried to run this command on my terminal
appium -p 4700 --default-capabilities '{"wdaLocalPort": 8100, "systemPort": 8200}'
I got this error:
usage: index.js server [-h] [--address ADDRESS] [--allow-cors] [--allow-insecure ALLOW_INSECURE]
                       [--base-path BASE_PATH] [--callback-address CALLBACK_ADDRESS] [--callback-port CALLBACK_PORT]
                       [--debug-log-spacing] [--default-capabilities DEFAULT_CAPABILITIES]
                       [--deny-insecure DENY_INSECURE] [--keep-alive-timeout KEEP_ALIVE_TIMEOUT] [--local-timezone]
                       [--log LOG] [--log-filters LOG_FILTERS] [--log-level LOG_LEVEL] [--log-no-colors]
                       [--log-timestamp] [--long-stacktrace] [--no-perms-check] [--nodeconfig NODECONFIG]
                       [--port PORT] [--relaxed-security] [--session-override] [--strict-caps] [--tmp TMP]
                       [--trace-dir TRACE_DIR] [--use-drivers USE_DRIVERS] [--use-plugins USE_PLUGINS]
                       [--webhook WEBHOOK] [--shell] [--show-build-info] [--show-config] [--config CONFIGFILE]

index.js server: error: argument --default-capabilities/-dc: invalid json value: "'{wdaLocalPort:"

### Expected Behavior

The Appium server with configured port and capabilities should be running successfully.

### Minimal Reproducible Example

Run this command in terminal:
appium -p 4700 --default-capabilities '{"wdaLocalPort": 8100, "systemPort": 8200}'

(I'm trying to setup Appium parallel environment)

### Environment

- Operating system: Windows 11 x64
- Appium server version (output of `appium --version`): 2.1.3
- Appium driver(s) and their version(s): uiautomator2@2.29.9
- Appium plugin(s) and their version(s): none
- Node.js version (output of `node --version`): v18.18.0
- `npm` version (output of `npm --version`): 9.8.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Escaping in Windows cmd does not work the same way it works in *nix shells. Check https://stackoverflow.com/questions/14966989/escaping-curl-command-in-windows

Closed as not an issue.
