### ISSUE TITLE
iOS simulator mock location methods

### ISSUE THREAD

**Issue by adelZilberman0** [appium/appium#19294]
### Discussed in https://github.com/appium/appium/discussions/19293

<div type='discussions-op-text'>

<sup>Originally posted by **adelZilberman0** October 13, 2023</sup>
Hi everyone, I'm building an Appium automation project for my app.
In order to test the app I need to set the location to different places in each test I execute. (on IOS simulator)
I have tried everything I found on the internet and nothing seems to work:
1. driver.setLocation() doesn't seem to be supported by appium. getting a syntax error as if it doesn't exist...
2. executeScript doesn't seem to work either. 
driver.executeScript("mobile: setLocation",
                "{ \"latitude\": " + latitude + ", \"longitude\": " + longitude + " }"); 
getting this error -> org.openqa.selenium.UnsupportedCommandException

The only option left is to mock location through the simulator itself but it's not practical at all since I need to change it a few times while the automation runs...

Does anyone know of a way I could make this work? Or did anyone encounter such a problem?</div>

**Comment by KazuCocoa** [comment]
for ios, please use https://appium.github.io/appium-xcuitest-driver/5.7/execute-methods/#mobile-setsimulatedlocation

**Comment by adelZilberman0** [comment]
> for ios, please use https://appium.github.io/appium-xcuitest-driver/5.7/execute-methods/#mobile-setsimulatedlocation

I can't get this to work. getting this error: 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot use 'in' operator to search for 'elementId' in {"latitude": 32.073346, "longitude": 34.793256}

I have tried updating appium, xcuitest and I can't find anything wrong with the code.
String jsonLocation = "{\"latitude\": " + 32.073346 + ", \"longitude\": " + 34.793256 + "}";
        driver.executeScript("mobile: setSimulatedLocation", jsonLocation);

**Comment by KazuCocoa** [comment]
Could you attach the full appium log as GIST?

**Comment by jlipps** [comment]
> String jsonLocation = "{"latitude": " + 32.073346 + ", "longitude": " + 34.793256 + "}";

This won't work. You'll need to construct a hashmap or similar in java. It needs to be an object with latitude and longitude fields. Not a string. Serialization is done by the client.

**Comment by adelZilberman0** [comment]
@jlipps @KazuCocoa Thank you! It works now
