### ISSUE TITLE
How do I get photos in webview?

### ISSUE THREAD

**Issue by ahmetozalp** [appium/appium#19301]
I'm developing to solve captcha, but I couldn't get the image address, can you help?

`[{"key":"elementId","value":null,"name":"elementId"},{"key":"index","value":"0","name":"index"},{"key":"package","value":"com.zhiliaoapp.musically","name":"package"},{"key":"class","value":"android.widget.Image","name":"class"},{"key":"text","value":"","name":"text"},{"key":"resource-id","value":"captcha-verify-image","name":"resource-id"},{"key":"checkable","value":"false","name":"checkable"},{"key":"checked","value":"false","name":"checked"},{"key":"clickable","value":"true","name":"clickable"},{"key":"enabled","value":"true","name":"enabled"},{"key":"focusable","value":"false","name":"focusable"},{"key":"focused","value":"false","name":"focused"},{"key":"long-clickable","value":"false","name":"long-clickable"},{"key":"password","value":"false","name":"password"},{"key":"scrollable","value":"false","name":"scrollable"},{"key":"selected","value":"false","name":"selected"},{"key":"bounds","value":"[142,661][937,1155]","name":"bounds"},{"key":"displayed","value":"true","name":"displayed"}]`

![image](https://github.com/appium/appium/assets/7665820/de15d173-a005-4fa9-be48-b85c129c3bf2)

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.

Are you a tiktok developer? If not then consider checking their license. Perhaps what you are doing or trying to do is not completely legal.

**Comment by ahmetozalp** [comment]
Of course it is not legal. If I had authority, I wouldn't need these photos.

**Comment by mykola-mokhnach** [comment]
Thanks for being honest, but we don't really support such initiatives or want to :)
