### ISSUE TITLE
bug: <title>iOS 17, Xcode 15 ，appium can not connect to iphone via wifi

### ISSUE THREAD

**Issue by HaoWShi** [appium/appium#19311]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1)
I can run test case in appium when iphone connect to mac by usb. And I make iphone and mac connect to same Wifi(other iphone's wifi hotspot). Then I disconnect usb between Mac and Iphone, XCode connect to Iphone via Wifi successfully
<img width="1157" alt="截屏2023-10-17 19 28 58" src="https://github.com/appium/appium/assets/20752268/1b22dd19-7e07-4b0c-96b0-db99aecdcfd3">

2)
Next, I run my script again, there is a error(details in further info)
**
No Real device with udid '*****', Looking for a simulator
Encountered internal error running command: Error: Unknow device or simulator UUID:'****'
at XCUITestDriver.determineDevice
atXCUITestDriver.start()
at XCUITestDriver.createSession()
at AppiumDriver.createSession()
**
<img width="957" alt="截屏2023-10-17 19 44 51" src="https://github.com/appium/appium/assets/20752268/3c807434-4e2b-4283-969f-191874008e6b">

3)
I run command 'idevice_id -n' and 'idevice_id -l' can not find the iphone connect to mac via wifi
![image](https://github.com/appium/appium/assets/20752268/f2eb97e0-e732-4095-8246-d36e472d9265)

When I use Appium Inspector to connect , there is a same error.

### Expected Behavior

when I make the Mac and iPhone connect to the same wifi, and config Xcode connect via network to enable, I can get the result
1)
I can see device info when I run the command 'device_id -n'
2)
I can run appium inspector success
3)
I can run my script as except

### Minimal Reproducible Example

The problem occurs based on my local environment configure
Mac::2019 MacBook Pro, MacOS Sonoma 14.0
Xcode: 15.0
Iphone: Iphone14 Pro ,IOS17.0.3
Appium2

### Environment

- Operating system: IOS
- Appium server version (output of `appium --version`): 2.1.3
- Appium driver(s) and their version(s):
admin@AdmindeMBP ~ % appium driver list
✔ Listing available drivers
- xcuitest@5.6.0 [installed (npm)]
- mac2@1.8.2 [installed (npm)]
- chromium@1.2.16 [installed (npm)]
- gecko@1.2.2 [installed (npm)]
- uiautomator2 [not installed]
- espresso [not installed]
- safari [not installed]

- Appium plugin(s) and their version(s):
admin@AdmindeMBP ~ % appium plugin list
✔ Listing available plugins
- images [not installed]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]

- Node.js version (output of `node --version`):18.18.1
- `npm` version (output of `npm --version`): 10.2.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: 2019 MacBook Pro, MacOS Sonoma 14.0
- Real device or emulator/simulator: real device,Iphone14 Pro ,IOS17.0.3

### Link to Appium Logs

info in further information

### Further Information

appium log
[debug] [AppiumDriver@33f9] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","appium:platformVersion":"17.0","appium:deviceName":"Haohao的iPhone","appium:automationName":"XCUITest","appium:udid":"00008120-001668D13AE8201E","appium:xcodeOrgId":"8HYJK2588L","appium:xcodeSigningId":"iPhone Developer","appium:showXcodeLog":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"17.0","appium:deviceName":"Haohao的iPhone","appium:automationName":"XCUITest","appium:udid":"00008120-001668D13AE8201E","appium:xcodeOrgId":"8HYJK2588L","appium:xcodeSigningId":"iPhone Developer","appium:showXcodeLog":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[debug] [AppiumDriver@33f9] Event 'newSessionRequested' logged at 1697542408481 (19:33:28 GMT+0800 (北美中部标准时间))
[Appium] Attempting to find matching driver for automationName 'XCUITest' and platformName 'iOS'
[Appium] The 'xcuitest' driver was installed and matched caps.
[Appium] Will require it at /Users/admin/.appium/node_modules/appium-xcuitest-driver
[debug] [Appium] Requiring driver at /Users/admin/.appium/node_modules/appium-xcuitest-driver
[AppiumDriver@33f9] Appium v2.1.3 creating new XCUITestDriver (v5.6.0) session
[AppiumDriver@33f9] Checking BaseDriver versions for Appium and XCUITestDriver
[AppiumDriver@33f9] Appium's BaseDriver version is 9.3.20
[AppiumDriver@33f9] XCUITestDriver's BaseDriver version is 9.3.20
[debug] [XCUITestDriver@7901] Creating session with W3C capabilities: {
[debug] [XCUITestDriver@7901]   "alwaysMatch": {
[debug] [XCUITestDriver@7901]     "platformName": "iOS",
[debug] [XCUITestDriver@7901]     "appium:platformVersion": "17.0",
[debug] [XCUITestDriver@7901]     "appium:deviceName": "Haohao的iPhone",
[debug] [XCUITestDriver@7901]     "appium:automationName": "XCUITest",
[debug] [XCUITestDriver@7901]     "appium:udid": "00008120-001668D13AE8201E",
[debug] [XCUITestDriver@7901]     "appium:xcodeOrgId": "8HYJK2588L",
[debug] [XCUITestDriver@7901]     "appium:xcodeSigningId": "iPhone Developer",
[debug] [XCUITestDriver@7901]     "appium:showXcodeLog": true,
[debug] [XCUITestDriver@7901]     "appium:includeSafariInWebviews": true,
[debug] [XCUITestDriver@7901]     "appium:newCommandTimeout": 3600,
[debug] [XCUITestDriver@7901]     "appium:connectHardwareKeyboard": true
[debug] [XCUITestDriver@7901]   },
[debug] [XCUITestDriver@7901]   "firstMatch": [
[debug] [XCUITestDriver@7901]     {}
[debug] [XCUITestDriver@7901]   ]
[debug] [XCUITestDriver@7901] }
[XCUITestDriver@7901] The desired capabilities include neither an app nor a bundleId. WebDriverAgent will be started without the default app
[XCUITestDriver@7901 (7f721685)] Session created with session id: 7f721685-9df2-47db-bbc7-89a4317e127a
[debug] [XCUITest] Current user: 'admin'
[debug] [XCUITestDriver@7901 (7f721685)] Available devices: 
[debug] [XCUITestDriver@7901 (7f721685)] No real device with udid '00008120-001668D13AE8201E'. Looking for a simulator
[XCUITestDriver@7901 (7f721685)] {}
[DevCon Factory] Releasing connections for 00008120-001668D13AE8201E device on any port number
[DevCon Factory] No cached connections have been found
[debug] [AppiumDriver@33f9] Event 'newSessionStarted' logged at 1697542408696 (19:33:28 GMT+0800 (北美中部标准时间))
[debug] [AppiumDriver@33f9] Encountered internal error running command: Error: Unknown device or simulator UDID: '00008120-001668D13AE8201E'
[debug] [AppiumDriver@33f9]     at XCUITestDriver.determineDevice (/Users/admin/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:1271:19)
[debug] [AppiumDriver@33f9]     at XCUITestDriver.start (/Users/admin/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:488:40)
[debug] [AppiumDriver@33f9]     at XCUITestDriver.createSession (/Users/admin/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:408:7)
[debug] [AppiumDriver@33f9]     at AppiumDriver.createSession (/usr/local/lib/node_modules/appium/lib/appium.js:374:35)
[HTTP] <-- POST /session 500 217 ms - 622
[HTTP]

**Comment by mykola-mokhnach** [comment]
Unfortunately we do not support testing devices connected via WiFi. Only wired connections are supported

**Comment by Prabudeva9** [comment]
@HaoWShi Please try below steps to resolve this, We did face the same issue to connect Wirelessly with latest iPhone's via Appium but the error was "Unknown device or Simulator UUID". 

Steps to Resolve:
•	Connect the MAC and the iPhone to the same Wifi ( it should be a private Wifi not public one)
•	Connect the iPhone using cable
•	Select the option “Show this iPhone when on WIFI” in the Finder window of the MAC

![Image](https://github.com/user-attachments/assets/e9ff6bcf-ec07-46fb-a935-c9a05028d02f) 
 
•	Start the Appium server and the Appium inspector with the specific desired capabilities
•	When the “automation is running “ is shown on the iPhone then unplug the phone and close the Appium inspector
•	Open Appium inspector again and start a new session with the specific desired capabilities
•	Once its enabled for the device, then it has be carried on thereafter for that device.

Thanks!
