### ISSUE TITLE
WebDriverAgent does not start on the simulator for xcode 15 

### ISSUE THREAD

**Issue by jus2026** [appium/appium#19312]
### Do I have the most recent component updates?

- [ ] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [x] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Appium 2.0.0,  Xcode 15, sonoma 14.0 (23A344)

Good day,
could you help me with the problem below?

I get an error when running autotests or running appium inspector:
`[Xcode] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITestDriver@d0ce (abe393c1)] Event 'wdaStartFailed' logged at 1697547478837 (15:57:58 GMT+0300 (Eastern European Summer Time))
[debug] [XCUITestDriver@d0ce (abe393c1)] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITestDriver@d0ce (abe393c1)] xcodebuild error message:
[debug] [XCUITestDriver@d0ce (abe393c1)] `

in xcode WebDriverAgent is built successfully
The command also runs successfully:
`xcodebuild build-for-testing -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=A4A1D1BD-0479-4903-A059-B0DC1C20FDFC IPHONEOS_DEPLOYMENT_TARGET=17.0 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO`

[appium.log](https://github.com/appium/appium/files/12930110/appium.log)

I cleared the cache, reinstalled components, deleted simulators - nothing helps

could you help me with this problem?

### Expected Behavior

Running tests on iOS 17 simulator

### Minimal Reproducible Example

example from appium inspector:
{
  "platformName": "ios",
  "appium:deviceName": "iPhone 15",
  "appium:platformVersion": "17.0",
  "appium:automationName": "XCUITest",
  "appium:useNewWDA": false
}

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.0.0
- Appium driver(s) and their version(s):  xcuitest@4.16.10 (automationName 'XCUITest'),  uiautomator2@2.12.2 (automationName 'UiAutomator2')
- Node.js version (output of `node --version`): 20.6.0
- `npm` version (output of `npm --version`): 9.8.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: xcode 15
- Real device or emulator/simulator: simulator iphone 15, ios 17.0

**Comment by jus2026** [comment]
@mykola-mokhnach i hope you mean this
sorry, if i wrong
[xcodebuild.log](https://github.com/appium/appium/files/12929682/xcodebuild.log)

**Comment by mykola-mokhnach** [comment]
Not really, I mean the appium log with the capability enabled:

> [debug] [XCUITestDriver@d0ce (abe393c1)] Output from xcodebuild will not be logged. To change this, use 'showXcodeLog' desired capability

**Comment by jus2026** [comment]
@mykola-mokhnach oh, sure
sorry
here it is
[showXcodeLog.log](https://github.com/appium/appium/files/12929862/showXcodeLog.log)

**Comment by jus2026** [comment]
@mykola-mokhnach unfortunately I can't use the latest versions since my autotests use driver.launchApp(); which is not available in latest versions(

but autotests worked 3 days ago on my laptop
I can't understand why they stopped running(

**Comment by mykola-mokhnach** [comment]
Unfortunately we do not provide patches to older versions. You could also ask your questions at Appium forum.
Closed as not an issue
