### ISSUE TITLE
[Feat]: ability to skip "build-for-testing" in case the build was already done in XCUITest

### ISSUE THREAD

**Issue by PinhoL** [appium/appium#19324]
**Is your feature request related to a problem? Please describe.**
I have a scenario where I want my tests to be as agnostic as possible. I don't know, or don't have to know, how many simulators I have and if new ones (fresh simulators) were added to my selenium grid. Just to be on the safe side, I want to use the `"appium:useNewWDA": true` capability to create a new webdriveragent on the device where the test will be run, however, if a second test runs on the same simulator I don't want to spend time waiting for the webdriver agent to be built again.

**Describe the solution you'd like**
I think the easiest solution is to have a flag/capability that always builds the webdriveragent in case it is not build, however if it exists already skip the `build-for-testing` phase.

I think that the `useXctestrunFile` and `bootstrapPath ` flags serve a different purpose where we specifically want to point to an existing build, my use case is directed to a more agnostic approach to the WDA management

**Comment by KazuCocoa** [comment]
> The same thing could achieve with derivedDataPath and usePrebuiltWDA capabilities, but it may fail if the xcodebuild cannot find or handle the .xctestrun properly. The stability depends on Xcode.

What's about `derivedDataPath` and `usePrebuiltWDA`?
https://appium.github.io/appium-xcuitest-driver/5.7/run-prebuilt-wda/

**Comment by PinhoL** [comment]
Hello @KazuCocoa thanks for the quick answer!

Yes, `derivedDataPath` does exactly what I described, if there's a WDA uses it, if there isn't just build it again. I read the docs but this behaviour was not very obvious for me, sorry!

I will close this because the flag already exists 👍
