### ISSUE TITLE
bug: Repeatedly reducing the template image

### ISSUE THREAD

**Issue by gointoit** [appium/appium#19331]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**when set implicitlyWait**
 Image matching fail will rerty within this implicitlyWait interval
 But every time try, scaling template image repeatedly which is incorrect,
 It causes template images to become smaller and smaller

**use: findByImage()**
**config:**
`drv.manage().timeouts().implicitlyWait(DEFAULT_APPIUM_IMPLICITLY_WAIT)`

`setting(drv, Setting.IMAGE_MATCH_THRESHOLD.toString(), "0.82");

setting(drv, Setting.FIX_IMAGE_FIND_SCREENSHOT_DIMENSIONS.toString(), true);
        setting(drv, Setting.FIX_IMAGE_TEMPLATE_SIZE.toString(), false);
        setting(drv, Setting.FIX_IMAGE_TEMPLATE_SCALE.toString(), true);
        setting(drv, Setting.CHECK_IMAGE_ELEMENT_STALENESS.toString(), false);
        setting(drv, Setting.UPDATE_IMAGE_ELEMENT_POSITION.toString(), false);`

**Log:**
![image](https://github.com/appium/appium/assets/14820842/745fb8a8-4175-477d-a95d-be0865bf7ce8)

### Expected Behavior

just scaling template image only Once when matching failed and retry

### Minimal Reproducible Example

Just give a picture that doesn't match and  set implicitlyWait = 5s,
Then trigger a matching retry，

### Environment

- Operating system: MAC
- Appium server version (output of `appium --version`): v2.2.1
- Appium driver(s) and their version(s): uiautomator2@2.29.2,xcuitest@4.34.0
- Appium plugin(s) and their version(s):images@2.1.6
- Node.js version (output of `node --version`):v16.18.0
- `npm` version (output of `npm --version`):8.19.2
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: ios 15.2 ,iPhone 12
- Real device or emulator/simulator: both

**Comment by mykola-mokhnach** [comment]
It is a valid bug. Thanks for the detailed description

**Comment by mykola-mokhnach** [comment]
The issue has been fixed in master and will be available in the next server release
