### ISSUE TITLE
Why don't other methods such as driver.press_keycode(3) work when driver.activate_app("com.wandoujia.phoenix2") work?

### ISSUE THREAD

**Issue by Yesisyes** [appium/appium#19338]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

from appium import webdriver

def device_driver(app_package: str = "", app_activity: str = ""):
    desired_caps = {"appium:appWaitDuration": 60000, 'appium:enforceXPath1': True,
                    "appium:disableSuppressAccessibilityService": True, "platformName": "Android",
                    "appium:automationName": "uiautomator2", "appium:newCommandTimeout": 80000,
                    "appium:adbExecTimeout": 120000,
                    "unicodeKeyboard": True, "resetKeyboard": False, "appium:autoGrantPermissions": True,
                    'appium:udid': "17201JECB11533", 'appium:systemPort': 8205}
    if app_activity:
        desired_caps['appium:appPackage'] = app_package
        desired_caps['appium:appActivity'] = app_activity
    driver = webdriver.Remote('http://127.0.0.1:4723', desired_caps)
    driver.implicitly_wait(10)
    return driver

driver = device_driver()
driver.activate_app("com.wandoujia.phoenix2")
time.sleep(3)
driver_2 = device_driver("com.bigmax.app", "com.bigmax.core.presentation.LoadingActivity")
time.sleep(3)
driver_2.press_keycode(3)
driver_2.terminate_app("com.bigmax.app")
driver_2.quit()
driver.activate_app("com.wandoujia.phoenix2")
driver.press_keycode(3)

### Expected Behavior

Why execute the above code,the last one driver.activate_app("com.wandoujia.phoenix2") can work,the last one driver.press_keycode(3) unable to work?
Error report: selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /appium/device/press_keycode' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details.

### Minimal Reproducible Example

from appium import webdriver

def device_driver(app_package: str = "", app_activity: str = ""):
    desired_caps = {"appium:appWaitDuration": 60000, 'appium:enforceXPath1': True,
                    "appium:disableSuppressAccessibilityService": True, "platformName": "Android",
                    "appium:automationName": "uiautomator2", "appium:newCommandTimeout": 80000,
                    "appium:adbExecTimeout": 120000,
                    "unicodeKeyboard": True, "resetKeyboard": False, "appium:autoGrantPermissions": True,
                    'appium:udid': "17201JECB11533", 'appium:systemPort': 8205}
    if app_activity:
        desired_caps['appium:appPackage'] = app_package
        desired_caps['appium:appActivity'] = app_activity
    driver = webdriver.Remote('http://127.0.0.1:4723', desired_caps)
    driver.implicitly_wait(10)
    return driver

driver = device_driver()
driver.activate_app("com.wandoujia.phoenix2")
time.sleep(3)
driver_2 = device_driver("com.bigmax.app", "com.bigmax.core.presentation.LoadingActivity")
time.sleep(3)
driver_2.press_keycode(3)
driver_2.terminate_app("com.bigmax.app")
driver_2.quit()
driver.activate_app("com.wandoujia.phoenix2")
driver.press_keycode(3)

### Environment

[Appium] Welcome to Appium v2.2.1
[Appium] Attempting to load driver uiautomator2...
[Appium] Requiring driver at C:\Users\yizijian\.appium\node_modules\appium-uiautomator2-driver
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium]        http://192.168.51.220:4723/
[Appium]        http://192.168.79.1:4723/
[Appium]        http://192.168.102.1:4723/
[Appium]        http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] Available drivers:
[Appium]   - uiautomator2@2.32.3 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.

### Further Information

[appiumlog.log](https://github.com/appium/appium/files/13110737/appiumlog.log)

**Comment by KazuCocoa** [comment]
Did `driver = device_driver()` and `driver_2 = device_driver("com.bigmax.app", "com.bigmax.core.presentation.LoadingActivity")` use the same `'appium:systemPort': 8205`? then, the `driver_2` stopped the `driver`'s session since both uses the same `'appium:systemPort': 8205`, then `driver` expected to be called as session error

I guess you'd like to manage both `driver` and `driver_2` manage on the same device. Then, you should achieve it with one Appium session.

https://discuss.appium.io/ may help to ask questions

**Comment by Yesisyes** [comment]
> Did `driver = device_driver()` and `driver_2 = device_driver("com.bigmax.app", "com.bigmax.core.presentation.LoadingActivity")` use the same `'appium:systemPort': 8205`? then, the `driver_2` stopped the `driver`'s session since both uses the same `'appium:systemPort': 8205`, then `driver` expected to be called as session error
> 
> I guess you'd like to manage both `driver` and `driver_2` manage on the same device. Then, you should achieve it with one Appium session.
> 
> https://discuss.appium.io/ may help to ask questions

Yes,I want to manage two drivers on the same phone on the same 'appium:systemPort': 8205 without them affecting each other

**Comment by Yesisyes** [comment]
> Did `driver = device_driver()` and `driver_2 = device_driver("com.bigmax.app", "com.bigmax.core.presentation.LoadingActivity")` use the same `'appium:systemPort': 8205`? then, the `driver_2` stopped the `driver`'s session since both uses the same `'appium:systemPort': 8205`, then `driver` expected to be called as session error
> 
> I guess you'd like to manage both `driver` and `driver_2` manage on the same device. Then, you should achieve it with one Appium session.
> 
> https://discuss.appium.io/ may help to ask questions

Thanks you.Yes,I want to manage two drivers on the same phone on the same 'appium:systemPort': 8205 without them affecting each other

**Comment by Yesisyes** [comment]
I have one more question.
def device_driver(app_package: str = "", app_activity: str = "", browser: bool = False):
    desired_caps = {"appium:appWaitDuration": 60000, 'appium:enforceXPath1': True,
                    "appium:disableSuppressAccessibilityService": True, "platformName": "Android",
                    "appium:automationName": "uiautomator2", "appium:newCommandTimeout": 80000,
                    "appium:adbExecTimeout": 120000, 
  'appium:appPackage':"com.hyx.maizuo.main",'appium:appActivity':"com.hyx.maizuo.main.MainActivity",
                    "unicodeKeyboard": True, "resetKeyboard": False, "appium:autoGrantPermissions": True,
                    'appium:udid': "17201JECB11533", 'appium:systemPort': 8205, 'appium:noRest': True}
    driver = webdriver.Remote('http://127.0.0.1:4723', desired_caps)
    driver.implicitly_wait(10)
    return driver

driver = device_driver().
This way the app doesn't have an Android pop-up asking for location authorization.But,
def device_driver(app_package: str = "", app_activity: str = "", browser: bool = False):
    desired_caps = {"appium:appWaitDuration": 60000, 'appium:enforceXPath1': True,
                    "appium:disableSuppressAccessibilityService": True, "platformName": "Android",
                    "appium:automationName": "uiautomator2", "appium:newCommandTimeout": 80000,
                    "appium:adbExecTimeout": 120000, 
                    "unicodeKeyboard": True, "resetKeyboard": False, "appium:autoGrantPermissions": True,
                    'appium:udid': "17201JECB11533", 'appium:systemPort': 8205, 'appium:noRest': True}
    driver = webdriver.Remote('http://127.0.0.1:4723', desired_caps)
    driver.implicitly_wait(10)
    return driver

driver = device_driver().
driver.activate_app("com.hyx.maizuo.main") or driver.start_activity("com.hyx.maizuo.main", "com.hyx.maizuo.main.MainActivity").Open the application will appear Android system request location information popup.
The "appium:autoGrantPermissions": True,How does it work?
 I don't find a solution on the https://discuss.appium.io/

**Comment by KazuCocoa** [comment]
Because no app was specified. Appium did not know of the target to grant permissions.

> appium:autoGrantPermissions
> Whether to grant all the requested application permissions automatically when a test starts(true). The targetSdkVersion in the application manifest must be greater or equal to 23 and the Android version on the device under test must be greater or equal to Android 6 (API level 23) to grant permissions. Applications whose targetSdkVersion is lower than or equal to 22 must be reinstalled to grant permissions, for example, by setting the appium:fullReset capability as true for Android 6+ devices. If your app needs some special security permissions, like access to notifications or media recording, consider using mobile: changePermissions extension with appops target. false by default

https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-changepermissions

**Comment by Yesisyes** [comment]
> Because no app was specified. Appium did not know of the target to grant permissions.
> 
> > appium:autoGrantPermissions
> > Whether to grant all the requested application permissions automatically when a test starts(true). The targetSdkVersion in the application manifest must be greater or equal to 23 and the Android version on the device under test must be greater or equal to Android 6 (API level 23) to grant permissions. Applications whose targetSdkVersion is lower than or equal to 22 must be reinstalled to grant permissions, for example, by setting the appium:fullReset capability as true for Android 6+ devices. If your app needs some special security permissions, like access to notifications or media recording, consider using mobile: changePermissions extension with appops target. false by default
> 
> https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-changepermissions

Ok.It seems that this is the same reason as I suspect. Thank you for your clarification.
