### ISSUE TITLE
Unable to connect Real Android device

### ISSUE THREAD

**Issue by RushanMohammed** [appium/appium#19349]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Showing error message when trying to connect real Android device. Able to connect Emulator.
Note: I have connected earlier and worked fine.Getting this error message recently . Also i have updated SDK tools . Re-started everything. 

### Expected Behavior

It should connect successfully.

### Minimal Reproducible Example

Try to connect android real device with appium inspector. 
Unable to connect.

**Note**: I have connected earlier and worked fine.Getting this error message recently . Also i have updated SDK tools . Re-started everything. 

### Environment

- Operating system:Mac
- Appium server version (output of `appium --version`):latest 2
- Appium driver(s) and their version(s):latest
- Appium plugin(s) and their version(s):lates
- Node.js version (output of `node --version`):18.6.1
- `npm` version (output of `npm --version`):9.5.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:Android
- Real device or emulator/simulator:Real device . 

### Link to Appium Logs

rue}} [debug] [AppiumDriver@ca89] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","appium:platformVersion":"9","appium:deviceName":"Redmi Note 6 Pro","appium:automationName":"UiAutomator2","appium:appActivity":"com.hotake.hotake.MainActivity","appium:appPackage":"com.google.android.packageinstaller","appium:noReset":true,"appium: adbExecTimeout":"60000","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"9","appium:deviceName":"Redmi Note 6 Pro","appium:automationName":"UiAutomator2","appium:appActivity":"com.hotake.hotake.MainActivity","appium:appPackage":"com.google.android.packageinstaller","appium:noReset":true,"appium: adbExecTimeout":"60000","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}] [debug] [AppiumDriver@ca89] Event 'newSessionRequested' logged at 1698316545356 (16:05:45 GMT+0530 (India Standard Time)) [Appium] Attempting to find matching driver for automationName 'UiAutomator2' and platformName 'Android' [Appium] The 'uiautomator2' driver was installed and matched caps. [Appium] Will require it at /Users/rushan/.appium/node_modules/appium-uiautomator2-driver [debug] [Appium] Requiring driver at /Users/rushan/.appium/node_modules/appium-uiautomator2-driver [AppiumDriver@ca89] Appium v2.1.3 creating new AndroidUiautomator2Driver (v2.29.2) session [AppiumDriver@ca89] Checking BaseDriver versions for Appium and AndroidUiautomator2Driver [AppiumDriver@ca89] Appium's BaseDriver version is 9.3.20 [AppiumDriver@ca89] AndroidUiautomator2Driver's BaseDriver version is 9.3.15 [debug] [AndroidUiautomator2Driver@873c] Creating session with W3C capabilities: { [debug] [AndroidUiautomator2Driver@873c]   "alwaysMatch": { [debug] [AndroidUiautomator2Driver@873c]     "platformName": "Android", [debug] [AndroidUiautomator2Driver@873c]     "appium:platformVersion": "9", [debug] [AndroidUiautomator2Driver@873c]     "appium:deviceName": "Redmi Note 6 Pro", [debug] [AndroidUiautomator2Driver@873c]     "appium:automationName": "UiAutomator2", [debug] [AndroidUiautomator2Driver@873c]     "appium:appActivity": "com.hotake.hotake.MainActivity", [debug] [AndroidUiautomator2Driver@873c]     "appium:appPackage": "com.google.android.packageinstaller", [debug] [AndroidUiautomator2Driver@873c]     "appium:noReset": true, [debug] [AndroidUiautomator2Driver@873c]     "appium: adbExecTimeout": "60000", [debug] [AndroidUiautomator2Driver@873c]     "appium:ensureWebviewsHavePages": true, [debug] [AndroidUiautomator2Driver@873c]     "appium:nativeWebScreenshot": true, [debug] [AndroidUiautomator2Driver@873c]     "appium:newCommandTimeout": 3600, [debug] [AndroidUiautomator2Driver@873c]     "appium:connectHardwareKeyboard": true [debug] [AndroidUiautomator2Driver@873c]   }, [debug] [AndroidUiautomator2Driver@873c]   "firstMatch": [ [debug] [AndroidUiautomator2Driver@873c]     {} [debug] [AndroidUiautomator2Driver@873c]   ] [debug] [AndroidUiautomator2Driver@873c] } [AndroidUiautomator2Driver@873c] The following capabilities were provided, but are not recognized by Appium: [AndroidUiautomator2Driver@873c]   deviceName [AndroidUiautomator2Driver@873c]    adbExecTimeout [AndroidUiautomator2Driver@873c]   connectHardwareKeyboard [AndroidUiautomator2Driver@873c (5ed7bfed)] Session created with session id: 5ed7bfed-22e6-4001-974e-97f543419d18 [AndroidUiautomator2Driver@873c (5ed7bfed)] Starting 'com.google.android.packageinstaller' directly on the device [ADB] Using 'adb' from '/Users/rushan/Library/Android/sdk/platform-tools/adb' [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 start-server' [AndroidDriver] Retrieving device list [debug] [ADB] Trying to find a connected android device [debug] [ADB] Getting connected devices [debug] [ADB] Connected devices: [{"udid":"258e023e","state":"device"}] [AndroidDriver] Looking for a device with Android '9.0.0' [debug] [ADB] Setting device id to 258e023e [ADB] Getting device platform version [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell getprop ro.build.version.release' [debug] [ADB] Current device property 'ro.build.version.release': 9 [AndroidDriver] Using device: 258e023e [ADB] Using 'adb' from '/Users/rushan/Library/Android/sdk/platform-tools/adb' [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 start-server' [debug] [ADB] Setting device id to 258e023e [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell getprop ro.build.version.sdk' [debug] [ADB] Current device property 'ro.build.version.sdk': 28 [ADB] Getting device platform version [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell getprop ro.build.version.release' [debug] [ADB] Current device property 'ro.build.version.release': 9 [debug] [ADB] Device API level: 28 [AndroidUiautomator2Driver@873c (5ed7bfed)] Relaxing hidden api policy [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1'' [AndroidDriver] No app sent in, not parsing package/activity [debug] [AndroidDriver] Pushing settings apk to device... [debug] [ADB] Getting package info for 'io.appium.settings' [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell dumpsys package io.appium.settings' [debug] [ADB] App '/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk' is not installed [debug] [ADB] Installing '/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk' [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e features' [ADB] The application at '/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk' will not be cached, because the device under test has confirmed the support of streamed installs [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e install -g /Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk' [debug] [ADB] Getting package info for 'io.appium.settings' [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell dumpsys package io.appium.settings' [debug] [ADB] Error: Error executing adbExec. Original error: 'Command '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell dumpsys package io.appium.settings' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability [debug] [ADB]     at Timeout._onTimeout (/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/teen_process/lib/exec.js:140:19) [debug] [ADB]     at listOnTimeout (node:internal/timers:573:17) [debug] [ADB]     at processTimers (node:internal/timers:514:7) [ADB] Got an unexpected error while dumping package info: Error executing adbExec. Original error: 'Command '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell dumpsys package io.appium.settings' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability [debug] [ADB] App '/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk' is not installed [debug] [ADB] Installing '/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk' [ADB] The application at '/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk' will not be cached, because the device under test has confirmed the support of streamed installs [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e install -g /Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk' [debug] [ADB] Getting package info for 'io.appium.settings' [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell dumpsys package io.appium.settings' [debug] [ADB] Error: Error executing adbExec. Original error: 'Command '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell dumpsys package io.appium.settings' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability [debug] [ADB]     at Timeout._onTimeout (/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/teen_process/lib/exec.js:140:19) [debug] [ADB]     at listOnTimeout (node:internal/timers:573:17) [debug] [ADB]     at processTimers (node:internal/timers:514:7) [ADB] Got an unexpected error while dumping package info: Error executing adbExec. Original error: 'Command '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell dumpsys package io.appium.settings' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability [debug] [ADB] App '/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk' is not installed [debug] [ADB] Installing '/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk' [ADB] The application at '/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk' will not be cached, because the device under test has confirmed the support of streamed installs [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e install -g /Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/io.appium.settings/apks/settings_apk-debug.apk' [debug] [AndroidUiautomator2Driver@873c (5ed7bfed)] Deleting UiAutomator2 session [AndroidUiautomator2Driver@873c (5ed7bfed)] Restoring hidden api policy to the device default configuration [debug] [ADB] Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' [debug] [AppiumDriver@ca89] Event 'newSessionStarted' logged at 1698316796022 (16:09:56 GMT+0530 (India Standard Time)) [debug] [AppiumDriver@ca89] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability [debug] [AppiumDriver@ca89]     at Timeout._onTimeout (/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/teen_process/lib/exec.js:140:19) [debug] [AppiumDriver@ca89]     at listOnTimeout (node:internal/timers:573:17) [debug] [AppiumDriver@ca89]     at processTimers (node:internal/timers:514:7) [HTTP] <-- POST /session 500 250676 ms - 1284

### Further Information

![Screenshot 2023-10-26 at 4 11 08 PM](https://github.com/appium/appium/assets/147793025/c5ea30ea-fc81-41b4-be20-6a1e1c4f3595)

**Comment by mykola-mokhnach** [comment]
> Running '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell dumpsys package io.appium.settings' [debug] [ADB] Error: Error executing adbExec. Original error: 'Command '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell dumpsys package io.appium.settings' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability [debug] [ADB] at Timeout._onTimeout (/Users/rushan/.appium/node_modules/appium-uiautomator2-driver/node_modules/teen_process/lib/exec.js:140:19) [debug] [ADB] at listOnTimeout (node:internal/timers:573:17) [debug] [ADB] at processTimers (node:internal/timers:514:7) [ADB] Got an unexpected error while dumping package info: Error executing adbExec. Original error: 'Command '/Users/rushan/Library/Android/sdk/platform-tools/adb -P 5037 -s 258e023e shell dumpsys package io.appium.settings' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'adbExecTimeout' capability

Maybe the device is really slow to respond. You could try to bump the timeout as stated above or just replace the device under test to something that timely handles adb connections. It could also be these Chinese devices require some special configuration, but I cannot help there much.
