### ISSUE TITLE
bug: socket hang up problems in iOS real device tests

### ISSUE THREAD

**Issue by jatalahd** [appium/appium#19358]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We cannot run Appium XCUIDriver tests with any reliability at the moment in iOS real devices. We are getting random socket hang-ups during test execution. When updating new Software-Under-Test to devices, we need to switch WiFi connection to public network for about 30 seconds, then back to local network. Typically the socket hang up comes at this point or right after the switching operation has been done. But also without the network switch, there are random socket hang ups appearing.

We believe that the problems started appearing when updating to XCode 15 and MacOS 14. iOS version does not seem to matter, we have several devices using iOS 17 or 16 and both iOS versions behave the same. We are using the following capabilities and using appium-python-client version 2.11.1:

            "deviceName": ios_devices.get_device_name(udid),
            "platformVersion": ios_devices.get_device_platform_version(udid),
            "platformName": "iOS",
            "automationName": "XCUITest",
            "xcodeOrgId": self.xcode_org_id,
            "xcodeSigningId": self.xcode_signing_id,
            "maxTypingFrequency": 20,
            'derivedDataPath': data_path,
            'newCommandTimeout': '600',
            'usePrebuiltWDA': 'true',
            'wdaLaunchTimeout': 600000,
            'bundleId': ios_devices.get_app_bundle_id(app_path),
            'autoLaunch': 'false',
            'showXcodeLog': 'true',
            'shouldUseSingletonTestManager': 'false',
            'wdaLocalPort': self.get_dynamic_port(),

The "shouldUseSingletonTestManager" was added in the hopes of fixing the hang up issues, but no luck there. For further information, according to the appium.log, the problem most often appears after executing mobile:tap command on the device. We need to do long (2 second) taps to switch the WiFi in iOS control centre.

Unfortunately we do not have logs from the iOS devices, since the problem appears in Nightly tests when no one is looking (or logging). If we try to reproduce this at office hours, it seems to work fine :( We will try to get logs from iOS device to see what happens.

### Expected Behavior

Tests need to be run reliably for them to be useful. Unexpected socket hang-ups cause lots of false-failures to tests and make the results unusable.

### Minimal Reproducible Example

Unfortunately I cannot really give any systematic way to reproduce this. Our environment requires that phone code is set and we always wait for 8 hours, start xcodebuild from commandline to launch webdriveragent and then use a solenoid system to input the passcode required by XCUITest. After that we start test execution via Robot Framework. The webdriveragent is then installed by Appium. We can provide more info when we debug more.

### Environment

- Operating system: MacOS 14
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s): xcuitest@5.8.1
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): 20.6.1
- `npm` version (output of `npm --version`): 9.8.1
- Last component(s) version which did _not_ exhibit the problem: Half a year ago  no problems, but system was different
- Platform and version under test: iOS 16 and iOS 17
- Real device or emulator/simulator: Real device

### Further Information

Attaching appium.log:
[appium.log](https://github.com/appium/appium/files/13234944/appium.log)

first socket hang up:
2023-11-02 02:02:37:317 [XCUITestDriver@a898 (0561c9c4)] [XCUITestDriver@a898 (0561c9c4)] socket hang up

**Comment by KazuCocoa** [comment]
Do you have the device log as well?

**Comment by jatalahd** [comment]
No, but I will try to get one. Is there something special logging you need or is the syslog enough?

**Comment by KazuCocoa** [comment]
testmanagerd, or WebDrivetAgent related log would help. Entire syslog is also fine

**Comment by jatalahd** [comment]
Here are the zipped logs. The test execution was triggered by crontab at 02:00 AM, the logs start at 01:59 AM. Logs from both devices involved in testing:

[device_logs.zip](https://github.com/appium/appium/files/13235615/device_logs.zip)

**Comment by KazuCocoa** [comment]
Maybe the reason itself was around the below lines. Does this occur with a specific command, or kind of randomly?

```
default	2023-11-02 02:02:04.397028 +0200	WebDriverAgentRunner-Runner	Using general test manager
default	2023-11-02 02:02:04.397815 +0200	testmanagerd	Requesting screenshot.
default	2023-11-02 02:02:04.398495 +0200	testmanagerd	Got system UI orientation (<AXUIElementRef 0x956b91580> {pid=33} {uid=[ID:1 hash:0x0]}[kAXApplicationOrientationAttribute]) 1
default	2023-11-02 02:02:04.398617 +0200	testmanagerd	Preparing screenshot for request: ScreenshotRequest(screenID: 1, rect: nil, orientation: .up, encoding: Encoding(uniformTypeIdentifier: public.jpeg, compressionQuality: 0.100000), options: [])
default	2023-11-02 02:02:04.398674 +0200	testmanagerd	Taking screenshot for request: ScreenshotRequest(screenID: 1, rect: nil, orientation: .up, encoding: Encoding(uniformTypeIdentifier: public.jpeg, compressionQuality: 0.100000), options: [])
error	2023-11-02 02:02:04.408046 +0200	WebDriverAgentRunner-Runner	Exiting due to IDE disconnection.
default	2023-11-02 02:02:04.409071 +0200	SpringBoard	[0x6c8bdb550] invalidated after getting a no-senders notification - client is gone
default	2023-11-02 02:02:04.409192 +0200	backboardd	Connection removed: IOHIDEventSystemConnection uuid:C3FEE7E0-B3C0-443B-B09E-35D5038EA067 pid:670 process:WebDriverAgentRunner-Runner type:Passive entitlements:0x0 caller:BackBoardServices: <redacted> + 280 attributes:{
    HighFrequency = 1;
    bundleID = "appium.A800.WebDriverAgentRunner.xctrunner";
    pid = 670;
} state:0x1 events:0 mask:0x0 dropped:0 dropStatus:0 droppedMask:0x0 lastDroppedTime:NONE
default	2023-11-02 02:02:04.409568 +0200	SpringBoard	[app<appium.A800.WebDriverAgentRunner.xctrunner(98058CCA-E6A3-455D-A3B6-54CB518908CC)>:670] Workspace connection invalidated.
default	2023-11-02 02:02:04.409632 +0200	SpringBoard	[app<appium.A800.WebDriverAgentRunner.xctrunner(98058CCA-E6A3-455D-A3B6-54CB518908CC)>:670] Now flagged as pending exit for reason: workspace client connection invalidated
info	2023-11-02 02:02:04.409840 +0200	backboardd	0x10000093e: Set batch interval current:0 new:1 result:0
default	2023-11-02 02:02:04.410015 +0200	backboardd	Removing client connection <BKHIDClientConnection: 0x63cdf7340; IOHIDEventSystemConnectionRef: 0x64140bcd0; vpid: 670(v758); taskPort: 0x75273; bundleID: appium.A800.WebDriverAgentRunner.xctrunner> for client: IOHIDEventSystemConnection uuid:C3FEE7E0-B3C0-443B-B09E-35D5038EA067 pid:670 process:WebDriverAgentRunner-Runner type:Passive entitlements:0x0 caller:BackBoardServices: <redacted> + 280 attributes:{
    HighFrequency = 1;
    bundleID = "appium.A800.WebDriverAgentRunner.xctrunner";
    pid = 670;
} state:0x1 events:0 mask:0x0 dropped:0 dropStatus:0 droppedMask:0x0 lastDroppedTime:NONE source:HID
default	2023-11-02 02:02:04.410202 +0200	backboardd	HIDAnalytics Unregister Send event com.apple.hid.queueUsage
default	2023-11-02 02:02:04.410223 +0200	cfprefsd	[0x6a8a22b60] invalidated after getting a no-senders notification - client is gone
default	2023-11-02 02:02:04.410459 +0200	testmanagerd	[0x956d216f0] invalidated after getting a no-senders notification - client is gone
default	2023-11-02 02:02:04.410604 +0200	testmanagerd	Test process connection invalidated or interrupted, closing test session <XCTestSession: 0x95680ee40> pid 670.
default	2023-11-02 02:02:04.410711 +0200	testmanagerd	Closed <XCTestSession: 0x95680ee40> pid 670, removing from (
    "<XCTestSession: 0x95680ee40> pid 670"
)
default	2023-11-02 02:02:04.410756 +0200	testmanagerd	Tearing down <XCTestSession: 0x95680ee40> pid 670.
default	2023-11-02 02:02:04.410803 +0200	testmanagerd	{"msg":"getDaemonProxy called"}
default	2023-11-02 02:02:04.410936 +0200	launchd	exited due to exit(74)
default	2023-11-02 02:02:04.410950 +0200	launchd	service state: exited
default	2023-11-02 02:02:04.410962 +0200	launchd	internal event: EXITED, code = 0
default	2023-11-02 02:02:04.410965 +0200	launchd	job state = exited
default	2023-11-02 02:02:04.410996 +0200	launchd	service inactive: UIKitApplication:appium.A800.WebDriverAgentRunner.xctrunner[e3dc][rb-legacy]
default	2023-11-02 02:02:04.411040 +0200	launchd	service state: not running
default	2023-11-02 02:02:04.411051 +0200	launchd	shutting down
default	2023-11-02 02:02:04.411057 +0200	launchd	cleaning up
default	2023-11-02 02:02:04.411065 +0200	launchd	removing child: pid/670
default	2023-11-02 02:02:04.412710 +0200	runningboardd	Invalidating assertion 32-400-2663 (target:[app<appium.A800.WebDriverAgentRunner.xctrunner(98058CCA-E6A3-455D-A3B6-54CB518908CC)>:670]) from originator [osservice<com.apple.instruments.deviceservice>:400]
default	2023-11-02 02:02:04.413019 +0200	runningboardd	E06925AE-6709-4070-8C88-99834EAD5C53 monitor: got an update with info exited, wait4() status=18944
default	2023-11-02 02:02:04.413177 +0200	runningboardd	[app<appium.A800.WebDriverAgentRunner.xctrunner(98058CCA-E6A3-455D-A3B6-54CB518908CC)>:670] termination reported by launchd (0, 0, 18944)
default	2023-11-02 02:02:04.413496 +0200	runningboardd	Removing process: [app<appium.A800.WebDriverAgentRunner.xctrunner(98058CCA-E6A3-455D-A3B6-54CB518908CC)>:670]
default	2023-11-02 02:02:04.414180 +0200	cfprefsd	[0xdbcd0d820] invalidated after getting a no-senders notification - client is gone
default	2023-11-02 02:02:04.414205 +0200	runningboardd	Removing launch job for: [app<appium.A800.WebDriverAgentRunner.xctrunner(98058CCA-E6A3-455D-A3B6-54CB518908CC)>:670]
default	2023-11-02 02:02:04.414566 +0200	lsd	[0xeeeb296e0] invalidated after getting a no-senders notification - client is gone
default	2023-11-02 02:02:04.414648 +0200	launchd	removing job: caller = runningboardd
default	2023-11-02 02:02:04.414657 +0200	launchd	removing service: UIKitApplication:appium.A800.WebDriverAgentRunner.xctrunner[e3dc][rb-legacy]
default	2023-11-02 02:02:04.414681 +0200	launchd	internal event: PETRIFIED, code = 0
```

**Comment by jatalahd** [comment]
I would say randomly, but most often in the beginning of testing where we need to switch WiFi connection to public WiFi for a short time to enable installing enterprise app. The switching is done via ControlCentre, where we use sequential mobile:tap -commands. In my mind I that as problematic part. Also we have the MJPEG screenrecording enabled, so it uses the screencapture quite extensively, so that could also be something to be considered as culprit. But it happens also randomly.

**Comment by mykola-mokhnach** [comment]
It looks like the WDA server that runs on the device under test simply dies thus we cannot talk to it anymore. This might be an expected behaviour due to the network state switch (e.g. iOS itself resets all connection as a result and it cannot be changed). Try to restart the test session afterwards as a possible workaround.

**Comment by jatalahd** [comment]
The problem does not reproduce systematically, so it would be nice to know what actually triggers this situation. Is there any better logs I can take to see why WDA server dies?

**Comment by mykola-mokhnach** [comment]
> The problem does not reproduce systematically, so it would be nice to know what actually triggers this situation. Is there any better logs I can take to see why WDA server dies?

Unfortunately I don't have any answer to this question. We have never investigated that behaviour. Also, afaik Apple itselt does not provide any recommendations on how to use xctest for network switching scenarios nor provides direct APIs to do that. which means it's totally a "grey area". We are always open to any improvements you can propose though

**Comment by jatalahd** [comment]
Ok. I will just try the workaround you suggested. I think this issue can be closed, since there is nothing that can be done.

**Comment by jatalahd** [comment]
.

**Comment by KazuCocoa** [comment]
Yea, I also have experience to get xctest process disconnection when the device's network condition changed. (not Appium/WDA specific at that time)

**Comment by myungkyojung** [comment]
I have same problem...
