### ISSUE TITLE
WiFi toggle fails to turn off WiFi

### ISSUE THREAD

**Issue by aniket-21** [appium/appium#1935]
Toggle WiFi functionality uses KeyEvents to turn off and on the WiFI

While WiFi is off, Sending KeyEvent 22 twice takes the control to WiFi toggle switch and KeyEvent 23 clicks on toggle switch.

This works for turning ON WiFi but doesn't work while turning OFF WiFi. For turning Off, KeyEvents 19, 19 , 23 should be fired

**Comment by gourav999** [comment]
adb shell svc wifi disable
adb shell svc wifi enable 

these commands are not working. i am using windows 7, Android version 5.0,

**Comment by kamal2141037** [comment]
This solution works for AndroidDriver not for IosDriver and AppiumDriver

To Enable WI-FI
NetworkConnectionSetting networkConnection = new NetworkConnectionSetting(false, true, false);
networkConnection.setData(false); 
networkConnection.setWifi(true);
driver.setNetworkConnection(networkConnection);

To Disable WI-FI
NetworkConnectionSetting networkConnection = new NetworkConnectionSetting(false, true, false);
networkConnection.setData(false); 
networkConnection.setWifi(false); 
driver.setNetworkConnection(networkConnection);
