### ISSUE TITLE
bug: Image comparison fails when code is executed via buildkite

### ISSUE THREAD

**Issue by ShanmugaPrasanth94** [appium/appium#19352]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Image comparison is not working on buildkite server execution 

### Expected Behavior

Image comparison should work proper 

### Minimal Reproducible Example

While executing the scripts to validate the image comparison using image plugin fails with below issue but works well in the same machine when executed locally using intellij.

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: support_1.imageUtil.getJimpImage is not a function.

Any help would be appreciated thanks.

### Environment

- Operating system: Window
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by ShanmugaPrasanth94** [comment]
@jlipps @saikrishna321 @KazuCocoa @SrinivasanTarget

**Comment by mykola-mokhnach** [comment]
This looks like a dependencies issue. Make sure you have the most recent server version installed.

**Comment by ShanmugaPrasanth94** [comment]
> This looks like a dependencies issue. Make sure you have the most recent server version installed.

@mykola-mokhnach tried reinstalling the appium server to 2.0.1 still facing the same issue.

**Comment by mykola-mokhnach** [comment]
2.0.1 is not the latest version

**Comment by ShanmugaPrasanth94** [comment]
@mykola-mokhnach thanks for the response. Issue is resolved. 
It was happening due to the appium nodemodules was present on two different locations.
