### ISSUE TITLE
[Feat]: WebDriverAgent, enhancing the /performAccessibilityAudit method to include detailed XCUIElement information

### ISSUE THREAD

**Issue by IlyaUA** [appium/appium#19354]
Dear Appium Team!
I am reaching out with a suggestion to enhance the functionality of the `/performAccessibilityAudit` method, which was recently introduced in **Xcode** and **WebDriverAgent**. The current response format from the method provides a limited set of data about the interface elements.

**Current response format:**
```
{
   "value": [
      {
         "detailedDescription": "User will not be able to change the font size of this UIButtonLabel",
         "auditType": "XCUIAccessibilityAuditTypeDynamicType",
         "element": "\"Click me\" StaticText",
         "compactDescription": "Dynamic Type font sizes are unsupported"
      }
   ],
   "sessionId": "0056AE7D-AB7D-4CF6-9979-18128C627BAB"
}
```

**Proposed enhancement:**
For better integration and backward compatibility, I propose introducing a new key, `elementObj`, that would provide the full details of the element. This would precisely match the format of the `/source` command output, ensuring consistency and ease of use in automated tests.
```
{
   "value": [
      {
         "detailedDescription": "User will not be able to change the font size of this UIButtonLabel",
         "auditType": "XCUIAccessibilityAuditTypeDynamicType",
         "element": "\"Click me\" StaticText",
         "compactDescription": "Dynamic Type font sizes are unsupported",
         "elementObj": {
            // Exact data format as in `/source` command
            "rect": {
               "width": 135,
               "height": 18,
               "y": 65,
               "x": 129
            },
            "frame": "{{129, 65}, {135, 18}}",
            "isEnabled": true,
            "value": "clickMeButton",
            "name": "clickMeButton",
            "type": "StaticText",
            "isVisible": true,
            "label": "clickMeButton",
            "isAccessible": false
         }
      }
   ],
   "sessionId": "0056AE7D-AB7D-4CF6-9979-18128C627BAB"
}
```

**Arguments for the change:**
1. **Simplified debugging process:** Precise data on elements significantly accelerates the process of identifying and resolving accessibility issues.
2. **Effective mapping and integration with other tools:** Having a uniform data format with the `/source` command facilitates element mapping and use them in various testing tools and reporting systems.
3. **Unambiguous element identification:** The current response format may not always clearly identify elements with similar labels, especially if there are elements with similar properties on the screen. Comprehensive data will eliminate this ambiguity.

**Examples from real use.** 
I have several ImageButtons with the same image in my application, and one of them has problems with the auditing type - `XCUIAccessibilityAuditTypeSufficientElementDescription`. But because only the element name comes in the element field, I can't figure out which element is having problems.
**Example output:**
```
{
    "value": [
        {
            "detailedDescription": "The label of this UIButton is an image file name.",
            "auditType": "XCUIAccessibilityAuditTypeSufficientElementDescription",
            "element": "\"infoIcon\" Button",
            "compactDescription": "Image name used in description"
        }
    ],
    "sessionId": "00D589B6-F209-465B-9596-AA17AC882DF1"
}
```

**Second example:** 
I have some images that I am using in `base64` format. Because of this, in the element field I only see the element type, even without its `accessibilityLabel`. This makes it very difficult to identify the element to fix it.
**Example output:**
```
{
    "value": [
        {
            "detailedDescription": "This UIButton is missing useful accessibility information.",
            "auditType": "XCUIAccessibilityAuditTypeSufficientElementDescription",
            "element": "Button",
            "compactDescription": "Element has no description"
        }
    ],
    "sessionId": "00D589B6-F209-465B-9596-AA17AC882DF1"
}
```

**Conclusion:**
Incorporating full element data in the `/performAccessibilityAudit` method’s response will greatly enhance the automated testing and debugging process, making it more efficient and less time-consuming. I trust in your understanding and support in implementing this enhancement.

**Additional Information**
[PR in which performAccessibilityAudit was implemented](https://github.com/appium/WebDriverAgent/pull/727)
PR author - @mykola-mokhnach, please pay attention to this request

**Comment by mykola-mokhnach** [comment]
I could add the debug description of an element, which also contains the path to it in the source tree

**Comment by mykola-mokhnach** [comment]
The patch was merged and will be published in the next xcuitest driver version

**Comment by mykola-mokhnach** [comment]
Published in v5.8.1+

**Comment by IlyaUA** [comment]
@mykola-mokhnach This is not exactly what I was suggesting.
Now the output looks like this:
```
{
    "value": [
        {
            "elementDescription": "Attributes: Button, 0x100c50d00, {{186.7, 84.0}, {20.0, 20.0}}\nElement subtree:\n →Button, 0x100c50d00, {{186.7, 84.0}, {20.0, 20.0}}\n    StaticText, 0x100c50e20, {{186.7, 84.0}, {0.0, 0.0}}\nPath to element:\n →Application, 0x100c4d4e0, pid: 90105, label: 'test'\n  ↳Window (Main), 0x100c505e0, {{0.0, 0.0}, {393.0, 852.0}}\n   ↳Other, 0x100c509a0, {{0.0, 0.0}, {393.0, 852.0}}\n    ↳Other, 0x100c50ac0, {{0.0, 0.0}, {393.0, 852.0}}\n     ↳Other, 0x100c50700, {{0.0, 0.0}, {393.0, 852.0}}\n      ↳Other, 0x100c50820, {{5.0, 64.0}, {383.0, 40.0}}\n       ↳Button, 0x100c50d00, {{186.7, 84.0}, {20.0, 20.0}}\nQuery chain:\n →Find: Application 'illiakharebashvili.test-app'\n  Output: {\n    Application, 0x1028630a0, pid: 90105, label: 'test'\n  }\n  ↪︎Find: Descendant with identity binding to AX element pid: 90105, elementOrHash.elementID: 4359037232.4\n    Output: {\n      Button, 0x102862e60, {{186.7, 84.0}, {20.0, 20.0}}\n    }\n",
            "detailedDescription": "This UIButton is missing useful accessibility information.",
            "auditType": "XCUIAccessibilityAuditTypeSufficientElementDescription",
            "compactDescription": "Element has no description"
        }
    ],
    "sessionId": "2FD0C977-7667-48D7-B30F-69840113EFD6"
}
```
And in this case, the `debugDescription` field does not solve the problem described above, since it is inconvenient to parse it as JSON and use it for automation and other things.

**Suggestion:**
Can we use `[self.class dictionaryForElement:snapshot recursive:FALSE];`  to provide a structured description of an element?

**Comment by mykola-mokhnach** [comment]
I've implemented what was quick to implemented. Feel free to create another PR yourself if a more sophisticated data is needed.

**Comment by IlyaUA** [comment]
@mykola-mokhnach Thank you!
Can I ask for help if needed?
This will be my first PR in WDA, I'm afraid of breaking something.

**Comment by IlyaUA** [comment]
Yes, you are right)
Thanks a lot.

**Comment by IlyaUA** [comment]
@mykola-mokhnach Review please this PR https://github.com/appium/WebDriverAgent/pull/808
