### ISSUE TITLE
bug: XCUITestDriver unable to find simulator uuid or create new simulator

### ISSUE THREAD

**Issue by dmertins** [appium/appium#19350]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to start a new session on Appium Server, XCUITestDriver is unable to find any existing simulator device, or create a new one, raising the error "Unknown device or simulator UDID: '6912C729-4C42-4A6E-B874-CFEF71FF8BD2'", even though the simulator uuid exists:
![Screen Shot 2023-10-27 at 13 47 27 PM](https://github.com/appium/appium/assets/40676549/54f3ddb7-26d1-41fc-896d-174ec78c8891)
![Screen Shot 2023-10-27 at 13 55 56 PM](https://github.com/appium/appium/assets/40676549/66973471-e23a-44bc-83d4-e77a61d2e52f)

### Expected Behavior

XCUITestDriver was expected to find the simulator devices, since they exist, or to be able to create a new one.

### Minimal Reproducible Example

```
{
    "platformName": "IOS",
    "appium:app": "/absolute/path/to/app/ios-app.app.zip",
    "appium:autoAcceptAlerts": true,
    "appium:automationName": "XCuiTest",
    "appium:deviceName": "iPhone SE (3rd generation)",
    "appium:platformVersion": "17.0"
}
```

### Environment

- Operating system: macOS 13.6 (22G120)
- Appium server version (output of `appium --version`): 2.2.1
- Appium driver(s) and their version(s): xcuitest@5.7.0
- Node.js version (output of `node --version`): v18.18.0
- `npm` version (output of `npm --version`): 10.1.0
- Last component(s) version which did _not_ exhibit the problem: Xcode 15 (before 15.0.1 upgrade)
- Platform and version under test: iOS 17.0 (21A328)
- Real device or emulator/simulator: iPhone SE (3rd generation)

### Link to Appium Logs

https://gist.github.com/dmertins/220ebdcc3b14d89d25cb3df8d844fce6

### Further Information

The session was being created successfully (with Xcode 15.0.0) before Xcode automatically upgraded to 15.0.1. The iOS simulator then stoped working after this, so I've downgraded Xcode to 15.0.0. Now the simulator started working again, but the Appium session creation stoped working, showing the error described above.

**Comment by mykola-mokhnach** [comment]
What is the output of `xcrun simctl device list` ?

**Comment by mykola-mokhnach** [comment]
The above error on simulator creation is usually thrown if the creation process takes more than 10 seconds. Did you measure how long it is on your system?

**Comment by mykola-mokhnach** [comment]
The exception is thrown if the simulator is still in 'Creating' state after 10 seconds or its udid is not present in the devices list: https://github.com/appium/node-simctl/blob/55d12e5f47473bb81e06ee5152643647202b991a/lib/subcommands/create.js#L102

**Comment by dmertins** [comment]
> What is the output of `xcrun simctl device list` ?

`xcrun simctl device list` outputs `Unrecognized subcommand: device`
`xcrun simctl list devices` outputs: https://gist.github.com/dmertins/490ec5b8c0033f6479dde40028725664

**Comment by dmertins** [comment]
> The above error on simulator creation is usually thrown if the creation process takes more than 10 seconds. Did you measure how long it is on your system?

What is the appropriate procedure for me to measure this time?

**Comment by mykola-mokhnach** [comment]
You could do it manually, e.g. create device using `xcrun simctl create` command and then check how much time it takes for the device to exit from the `Creating` state in the `xcrun simctl list devices` output.

Another possible solution would be to try patching the timeout itself and see how if it would be enough. 
The place to do that would usually be `~/.appium/node_modules/appium-xcuitest-driver/node_modules/node-simctl/build/lib/subcommands/create.js` ->  DEFAULT_CREATE_SIMULATOR_TIMEOUT
After changing this value just restart the server and run your test

**Comment by dmertins** [comment]
It seens to take less than 1 second to create a simulator on my environment:
```
dmertins:~/ $ xcrun simctl create "iPhone SE (3rd generation)" "iPhone SE (3rd generation)"                                           [18:32:04]
No runtime specified, using 'iOS 17.0 (17.0.1 - 21A342) - com.apple.CoreSimulator.SimRuntime.iOS-17-0'
9E804083-47EE-4FC6-B69B-4EB3052667E3
dmertins:~/ $                                                                                                                         [18:32:10]
```

**Comment by mykola-mokhnach** [comment]
This looks like some issue with the local deployment. I have tried to reproduce the simulator creation issue locally using Xcode 15.1-beta2 and was not able to do that.

Maybe try to delete installed simulator platforms from Xcode Settings->Platforms and install them fresh.

If that does not work then we could try to add additional debug logs into the source code.

**Comment by dmertins** [comment]
I have deleted iOS 17.0 simulator, on Xcode Sttings > Platforms, and reinstalled. When trying to start a session now, the existing simulator uuid was found and started:
```
[iOSSim] Simulator with UDID 61454A31-6011-4A9B-AE96-A9917D6893BC booted in 36.393s
```
It seems the issue was really related to my environment after Xcode upgrade-downgrade procedure. I think it's a progress.

But now I'm facing a different error: it looks like WebDriverAgent is never starting:
```
[AppiumDriver@904f] Encountered internal error running command: Error: Unable to start WebDriverAgent session because of xcodebuild failure: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: connect ECONNREFUSED 127.0.0.1:8100
[AppiumDriver@904f]     at quitAndUninstall (/Users/dmertins/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:794:15)
[AppiumDriver@904f]     at /Users/dmertins/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:914:11
[AppiumDriver@904f]     at wrapped (/Users/dmertins/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:95:13)
[AppiumDriver@904f]     at retry (/Users/dmertins/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:68:13)
[AppiumDriver@904f]     at retryInterval (/Users/dmertins/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:105:10)
[AppiumDriver@904f]     at /Users/dmertins/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:819:7
[HTTP] <-- POST /session 500 532075 ms - 1068
[HTTP]
```
Here is the full appium server log:
https://gist.github.com/dmertins/b6d46245a894b107511a86139257b200

**Comment by mykola-mokhnach** [comment]
It could be WDA needs more time to finish the compilation. Try to increase the default value of wdaLaunchTimeout capability

**Comment by dmertins** [comment]
Yes, that was the problem. I have increased `wdaLaunchTimeout` capability to 120 seconds and it successfully started the session. I guess my system became much slower after the last macOS updates.

It looks like all issues I was facing are resolved. Thank you so much @mykola-mokhnach for your help on the troubleshooting. I think we can close this issue now.
