### ISSUE TITLE
Chromedriver processes not getting cleaned-up

### ISSUE THREAD

**Issue by afathonih** [appium/appium#19355]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm currently running test with Appium-Espresso and I see a lot for chromedriver processes running. 

### Expected Behavior

Ideally, only one chromedriver process is running for a single session.

### Minimal Reproducible Example

Run appium espresso against an app with webview.
Switch to the webview during test.
Repeat the tests couple of times.

Run:
ps ax | grep chromedriver

### Environment

- Operating system: MacOS Ventura 13.6
- Appium server version (output of `appium --version`): 2.2.1
- Appium driver(s) and their version(s): 
  - uiautomator2@2.29.8 [installed (npm)]
  - xcuitest@5.1.0 [installed (npm)]
  - espresso@2.28.0 [installed (npm)]
  - mac2 [not installed]
  - safari [not installed]
  - gecko [not installed]
  - chromium [not installed]
- Appium plugin(s) and their version(s):
  - images@2.1.4 [installed (npm)]
  - execute-driver@3.0.17 [installed (npm)]
  - device-farm@8.2.4 [installed (linked from /Users/foo/Github/appium-device-farm)]
  - appium-dashboard@v2.0.2 [installed (linked from /Users/foo/Github/appium-dashboard-plugin)]
  - relaxed-caps [not installed]
  - universal-xml [not installed]
- Node.js version (output of `node --version`): v20.8.1
- `npm` version (output of `npm --version`): 10.1.0
- Last component(s) version which did _not_ exhibit the problem: I don't know
- Platform and version under test: emulator API 33, real device Android 10
- Real device or emulator/simulator: both

### Further Information

Appium log:
```
[Chromedriver@48c7] Browser version in the supplied details: Chrome/118.0.0.0
[Chromedriver@48c7] Found Chrome bundle 'undefined' version '118.0.0'
[Chromedriver@48c7] Found 1 executable capable of automating Chrome '118.0.0'.
[Chromedriver@48c7] Choosing the most recent, '/Users/foo/.appium/node_modules/appium-espresso-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-arm64_v118.0.5993.70'.
[Chromedriver@48c7] If a specific version is required, specify it with the `chromedriverExecutable`desired capability.
[Chromedriver@48c7] Set chromedriver binary as: /Users/foo/.appium/node_modules/appium-espresso-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-arm64_v118.0.5993.70
[Chromedriver@48c7] Killing any old chromedrivers, running: pkill -15 -f "/Users/foo/.appium/node_modules/appium-espresso-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-arm64_v118.0.5993.70.*--port=52272"
```

Process list:
```
base) ➜  ~ ps ax | grep chromedriver                    
44031 s000  S+     0:39.76 node /opt/homebrew/bin/appium --relaxed-security --allow-insecure chromedriver_autodownload,execute_driver_script,adb_shell -pa=wd/hub
47308 s000  S+     0:01.06 /Users/foo/.appium/node_modules/appium-espresso-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-arm64_v118.0.5993.70 --port=63140 --adb-port=5037 --verbose
49329 s000  S+     0:00.62 /Users/foo/.appium/node_modules/appium-espresso-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-arm64_v118.0.5993.70 --port=52272 --adb-port=5037 --verbose
49348 s004  R+     0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox chromedriver
```

The issue is in the [pkill command](https://github.com/appium/appium-chromedriver/blob/48bebe94b14fd98f8fd5eceafa399a117d9b5584/lib/chromedriver.js#L806):
`chromedriver-mac-arm64_v118.0.5993.70.*` should have been just `chromedriver-mac-arm64_v118.0.5993.70`

**Comment by mykola-mokhnach** [comment]
> chromedriver-mac-arm64_v118.0.5993.70.* should have been just chromedriver-mac-arm64_v118.0.5993.70

pkill uses regular expressions to match process names. `.*` is a correct pattern for it, so I don't observe any problems with the above pattern

**Comment by afathonih** [comment]
You're right. I tried again the pkill command and it correctly terminated the process.

Let me close this and re-open later when I have more information.
