### ISSUE TITLE
Query - WebDriverAgent install prompts for passcode / Touch ID to Enable UI Automation

### ISSUE THREAD

**Issue by Reeta-L** [appium/appium#19363]
When doing UI automation, WebDriverAgent is installed and it prompts for passcode/ Touch Id to "Enable UI Automation".  Then it works for some hours or days, but after some time it prompts again, even when WebDriverAgent is already installed. "Enable UI Automation" is already enabled in "Settings" - "Developer" menu.
The devices are located remotely and we can't access them directly, so this is a big issue for us right now. Removing the passcode is no valid workaround since we have apps that require the passcode to start.

Why it is random even when "Enable UI Automation" is already enabled and WebDriverAgent is already installed or no change.

**Comment by mykola-mokhnach** [comment]
> Removing the passcode is no valid workaround since we have apps that require the passcode to start.

We usually advice to disable passcode, but if it required for the app then I don't have any good suggestions. This is a security requirement from Apple and we cannot do anything to change that.

**Comment by Reeta-L** [comment]
We already raised this query with Apple that why it is asks only sometime or there is a criteria and they mention that it is app specific issue, so raised it here.

**Comment by KazuCocoa** [comment]
Right, the passcode lock is unavoidable for XCTest (not Appium/WDA specific. General XCTest for UI also behaves the same).

> iPhone/iPad real devices [require passcode or touch id](https://github.com/appium/appium/issues/15898#issuecomment-927340411) when they start a XCTest session since iOS/iPadOS 15. Disabling passcode/touch id in the device preference allows to workaround the behaviour above.

https://appium.github.io/appium-xcuitest-driver/5.8/troubleshooting/#known-problems
