### ISSUE TITLE
bug: Connection was refused to port XXXX - socket hang up

### ISSUE THREAD

**Issue by JumBe08** [appium/appium#19365]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I try to start my IOSDriver and open an app on my iPhone, like the Phone app. The appium session logs stars to throw a "Connection refused to port XXXX - Socket hang up" recurrently until it turns into a ECONNREFUSED error that is also recurrent.

### Expected Behavior

It should just open the app, without issues.

### Minimal Reproducible Example

Working with Java:

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("platformVersion", "15.7");
capabilities.setCapability("deviceName", "My iPhone");
capabilities.setCapability("udid", "my phone's udid...");
capabilities.setCapability("bundleId", "com.apple.mobilephone");
capabilities.setCapability("xcodeOrgId", "my org id...");
capabilities.setCapability("xcodeSigningId", "iPhone Developer");
capabilities.setCapability("updatedWDABundleId", "com.google.chrome.ios");
capabilities.setCapability("AutomationName", "XCUITest");
capabilities.setCapability("autoDismissAlerts", "false");
capabilities.setCapability("newCommandTimeout", 30000);
capabilities.setCapability("noRest", "true");
capabilities.setCapability("useNewWDA", "false");

driver = new IOSDriver<>(new URL("http://localhost:4723/wd/hub"), capabilities);

### Environment

- Operating system: macOS 12.5.1
- Appium server version (output of `appium --version`): 2.2.1
- Appium driver(s) and their version(s): xcuitest@4.35.0
- Appium plugin(s) and their version(s): relaxed-caps@1.0.5
- Node.js version (output of `node --version`): 19.9.0
- `npm` version (output of `npm --version`): 9.6.3
- Last component(s) version which did _not_ exhibit the problem: I was able to have this working with this same setup, but the last time i have built the WDA project I had an older version of Appium 2 and the XCUITest driver, can't recall which ones though =/
- Platform and version under test: iOS 15.7
- Real device or emulator/simulator: Real device

### Further Information

I can build successfully the WebDriverAgentRunner at xCode, which is also not accusing anything at it's Signing & Capabilities section. I'm using a Development Signing Certificate. I noticed that at my Apple's account web page, there is a Info label telling me that the program license agreement has been updated, and that i need to accept it to continue integrating new technologies. Can this be the cause?

Btw I have no other signed app at the device. I've used "ideviceinstaller -l" though and it is also not showing me the WebDriverAgent app, despite the successful build. Shouldn't it show up here?

I've found [this](https://github.com/appium/appium/issues/13836) issue which is similar, but it is in Appium 1 and it is not taking me anywhere. I've also tried restarting the phone and the mac machine, like suggested [here](https://github.com/appium/appium/discussions/19031).

Error Log:
[error log.txt](https://github.com/appium/appium/files/13244152/error.log.txt)

[Error logs 2.log](https://github.com/appium/appium/files/13245848/Error.logs.2.log)

**Comment by mykola-mokhnach** [comment]
> [XCUITestDriver@6273 (1eb60a85)] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability

Please enable xcodebuild logging and attach the updated logs

**Comment by JumBe08** [comment]
> > [XCUITestDriver@6273 (1eb60a85)] Output from xcodebuild will only be logged if any errors are present there. To change this, use 'showXcodeLog' desired capability
> 
> Please enable xcodebuild logging and attach the updated logs

Done, I've added a new file with the new logs.

**Comment by mykola-mokhnach** [comment]
> 2023-11-03 00:18:44:167 [Xcode] CodeSign /Users/myUser/Library/Developer/Xcode/DerivedData/WebDriverAgent-fciwhdyfhaeecybqeclrzefhhnpr/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
> 2023-11-03 00:18:44:167 [Xcode]     cd /Users/myUser/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent
> 2023-11-03 00:18:44:167 [Xcode]     
> 2023-11-03 00:18:44:167 [Xcode]     Signing Identity:     "Apple Development: Filipe Costa (576XHCYHQ4)"
> 2023-11-03 00:18:44:167 [Xcode]     
> 2023-11-03 00:18:44:167 [Xcode]     /usr/bin/codesign --force --sign EBFB0825E9FEB9CDCD50345B95DCFF9F619CDDD0 --timestamp\=none --generate-entitlement-der /Users/myUser/Library/Developer/Xcode/DerivedData/WebDriverAgent-fciwhdyfhaeecybqeclrzefhhnpr/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework
> 2023-11-03 00:18:44:167 [Xcode] 
> 2023-11-03 00:18:44:313 [Xcode] /Users/myUser/Library/Developer/Xcode/DerivedData/WebDriverAgent-fciwhdyfhaeecybqeclrzefhhnpr/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework: errSecInternalComponent
> 2023-11-03 00:18:44:313 [Xcode] 
> 2023-11-03 00:18:44:314 [Xcode] Command CodeSign failed with a nonzero exit code
> 2023-11-03 00:18:44:314 [Xcode] 

Obviously codesigning is an issue. [Google](https://stackoverflow.com/questions/24023639/xcode-command-usr-bin-codesign-failed-with-exit-code-1-errsecinternalcomponen) says it might be a problem with process access to the keychain though.

**Comment by JumBe08** [comment]
I went to KeyChain Access and deleted some expired certificates I had in there. After that I restarted my machine and I was able to run things normally again.

Thanks @mykola-mokhnach  for pointing me in the right direction :)
