### ISSUE TITLE
Documentation link throws 404

### ISSUE THREAD

**Issue by gauravgandhi1315** [appium/appium#19380]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

http://appium.io/docs/en/drivers/ios-xcuitest throws 404

### Expected Behavior

it shouldn't throw 404

### Minimal Reproducible Example

click on the link (http://appium.io/docs/en/drivers/ios-xcuitest/

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by jlipps** [comment]
Where did you find this URL? current xcuitest docs are https://appium.github.io/appium-xcuitest-driver/5.8/

**Comment by KazuCocoa** [comment]
I guess duplicated of https://github.com/appium/appium/issues/18761, then the latest doctor is already has the fix.
Once will be released, this will be ok https://github.com/appium/appium/pull/19305
