### ISSUE TITLE
bug: <WebDriverAgent project is unable to build(find) the AppleTV( tvOS-17.2 Beta version)>

### ISSUE THREAD

**Issue by Chetantn** [appium/appium#19381]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm working with latest AppleTV 4k upgraded with beta version i.e 17.2 tvOS(real device) , on which we execute some automated tests using appium for some of our in-house app's 

when i'm trying to build the tvOS webDriverAgent project with below command( running from webdriver agent default project path) it is throwing following error.

**command** :
             xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner_tvOS -destination 
             'id=4d61282d6871dd9006c73a8e7e8f20298ed82e00' test
**response**: 
 Ineligible destinations for the "WebDriverAgentRunner_tvOS" scheme:
{ platform:tvOS, id:4d61282d6871dd9006c73a8e7e8f20298ed82e00, name:Living Room, error:Living Room’s tvOS 17.0 doesn’t match WebDriverAgentRunner_tvOS.xctest’s tvOS 17.2 deployment target. Upgrade Living Room’s tvOS version or lower WebDriverAgentRunner_tvOS.xctest’s deployment target. }

**Note**: I'm able to successfully build the tvos **webDriverAgentLib_tvOS** and **webDriverAgentRunner_tvOS**  tvOS runner from Xcode, no error for Target devices there i have set it to **17.2** image attached

![image](https://github.com/appium/appium/assets/62075128/0587d7d4-c7c8-4613-8190-2b4a77a1b6c9)
![image](https://github.com/appium/appium/assets/62075128/67abd63b-25d1-4e94-98ca-514d153208a4)
 

but when i tried to run the command xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner_tvOS -destination  'id=4d61282d6871dd9006c73a8e7e8f20298ed82e00' test, it is complaining about deployment target. 

Even i tried to set the tvOS deployment target to 17.0 and build the i had below issue which was expected because my AppleTV is deployed with 17.2 version
 when u tried to run above command by downgrading the target got below  response: 

**Response Logs :**  
2023-11-07 13:25:40.722 xcodebuild[19962:485925]  DTDeviceKit: Started connection with 00008020-0011188A1A50003A
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
{ id:4d61282d6871dd9006c73a8e7e8f20298ed82e00 }

Available destinations for the "WebDriverAgentRunner_tvOS" scheme:
{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Any tvOS Device }
{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Any tvOS Simulator Device }

### Expected Behavior

since i'm using all the latest drivers, plugin's, appium , xcode and macos it should build the tvOS webdriverAgent properly. since i'm able to launch the app for iphone with 17.1 os version with the same setup. 

### Minimal Reproducible Example

xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner_tvOS -destination 'id=4d61282d6871dd9006c73a8e7e8f20298ed82e00' test

### Environment

and i have the following versions installed on mac, all are almost latest and some are beta version's too.
1. MAC ----SONOMA 14.1
2. XCODE --- 15.1 beta (15C5042i)
3. Appium --- 2.2.1  CLI version
4.  ✔ Listing installed plugins for appium
- [execute-driver@3.0.19](mailto:execute-driver@3.0.19) [installed (npm)]
5. ✔ Listing available drivers for appium
- [uiautomator2@2.34.0](mailto:uiautomator2@2.34.0) [installed (npm)] [Up to date]
- [xcuitest@5.8.1](mailto:xcuitest@5.8.1) [installed (npm)] [Up to date]
- mac2 [not installed]
- espresso [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]
6. NPM version ---8.15.0
7. NODE version --v16.17.1
8. Real Device --AppleTV 4k upgraded with beta version i.e 17.2 tvO

### Further Information

with this issue, want to know whether tvOS beta version is supported by latest webdriverAgent Project.

**Comment by mykola-mokhnach** [comment]
I think this might a bug in xcodebuild itself that it cannot match the device identifier properly. Have you tried to report it to Apple?

**Comment by Chetantn** [comment]
Yes i have reported the same to Apple developers forum 
![image](https://github.com/appium/appium/assets/62075128/a43fa19b-3ba8-4ac1-abb1-c9048774bea5)

waiting for their response.  will try to skip the device check once

**Comment by KazuCocoa** [comment]
Yea, i noticed this xcodebuild in https://github.com/appium/appium/issues/19343#issuecomment-1797900457 yesterday.

`xcrun devicectl list devices` and `xcrun xctrace list devices` show such a device in the list, but `xcodebuild` did not as the destination.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by Chetantn** [comment]
Hi All, 
It's been 3+ Weeks i'm not getting any response from Apple Team for the issue i raised 
![image](https://github.com/appium/appium/assets/62075128/a8892272-6f98-48ad-bf6a-86286fb8d41c)
, can somebody tell me if there is any workaround for this issue. we are completely blocked for tvOS 17.2 app testing.  Any experts at this forum please suggest me how to contact apple team in other way if any. or please suggest any workaround. I tried to downgrade the AppleTV but i have difficulty in doing so.

**Comment by adriandumitrascu19** [comment]
hello, any updates on this ?
