### ISSUE TITLE
bug: [WebDriverAgent, Xcode 15] - Long wait time to fetch screen /source when WebView is present

### ISSUE THREAD

**Issue by IlyaUA** [appium/appium#19382]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the update to Xcode 15, the `/source` request execution is extremely delayed, now taking over 4 minutes. This was not an issue with Xcode 14 where the response was considerably quicker.

#### Logs
```
Using singleton test manager
Detected on-screen application: com.apple.WebKit.WebContent
Getting the most recent active application (out of 1 total items)
Waiting up to 10s until com.test.test-app is in idle state (including animations)
    t =    10.78s Wait for com.test.test.test-app to idle
Cannot take a snapshot with attribute(s) (
    "XC_kAXXCAttributeLabel",
    "XC_kAXXCAttributeTraits",
    "XC_kAXXCAttributeHorizontalSizeClass",
    "XC_kAXXCAttributePlaceholderValue",
    "XC_kAXXCAttributeBannerIsStickyAttribute",
    "XC_kAXXCAttributeIdentifier",
    "XC_kAXXCAttributeWindowDisplayId",
    "XC_kAXXCAttributeIsUserInteractionEnabled",
    "XC_kAXXCAttributeURL",
    "XC_kAXXCAttributeUserTestingElements",
    "XC_kAXXCAttributeHasNativeFocus",
    "XC_kAXXCAttributeVerticalSizeClass",
    "XC_kAXXCAttributeTruncatedValue",
    "XC_kAXXCAttributeViewControllerTitle",
    "XC_kAXXCAttributeFrame",
    "XC_kAXXCAttributeWindowContextId",
    "XC_kAXXCAttributeSystemAutomationProperties",
    "XC_kAXXCAttributeParent",
    "XC_kAXXCAttributeAutomationType",
    "XC_kAXXCAttributeViewControllerClassName",
    "XC_kAXXCAttributeElementType",
    "XC_kAXXCAttributeElementBaseType",
    "XC_kAXXCAttributeIsVisible",
    "XC_kAXXCAttributeIsElement"
) of 'XCUIElementTypeApplication' after 15.00 seconds
This timeout could be customized via 'customSnapshotTimeout' setting
Internal error: Error kAXErrorIPCTimeout getting snapshot for element <AXUIElementRef 0x600000c24270> {pid=33688} {uid=[ID:1 hash:0x0]}
Falling back to the default snapshotting mechanism for the element 'XCUIElementTypeApplication' (some attribute values, like visibility or accessibility might not be precise though)
Cannot retrieve element attribute(s) (
    "XC_kAXXCAttributeIsElement"
). Original error: Error Domain=com.apple.dt.xctest.automation-support.error Code=11 "Accessibility error kAXErrorIPCTimeout from AXUIElementCopyMultipleAttributeValues for 2016" UserInfo={accessibility-error=-25216, NSLocalizedDescription=Accessibility error kAXErrorIPCTimeout from AXUIElementCopyMultipleAttributeValues for 2016}
[User Defaults] Source was stale 251 times within the last 342 ms (55 (latestGeneration) != 0 (lastKnownShmemState)): CFPrefsManagedSource<0x600003004510> (Domain: kCFPreferencesAnyApplication, User: kCFPreferencesCurrentUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes)

```

### Expected Behavior

The `/source` request should complete in a reasonable time, similar to how it performed before updating to Xcode 15.

### Minimal Reproducible Example

1. Update to Xcode version 15.
2. Run WebDriverAgent version 5.13.1+ on an iOS 17 device.
3. Execute the `/source` request.
4. Experience a delay exceeding 4 minutes to get a response.

### Environment

- **WebDriverAgent version**: 5.13.1
- **Xcode version**: 15.0
- **iOS version**: 17
- **Device**:  Real, Simulator

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we could do about it. Snapshotting is done by XCTest and only Apple itself can fix that

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by DSpalato** [comment]
"appium:settings[customSnapshotTimeout]": 0 
This one helped me to solve issue.

**Comment by OleksiiRudyi** [comment]
> "appium:settings[customSnapshotTimeout]": 0 This one helped me to solve issue.

Thank you @DSpalato ! This solution helped me with the same issue! Here is the documentation for the suggested Appium settings: https://appium.github.io/appium-xcuitest-driver/5.14/reference/settings/

**Comment by Morph93** [comment]
If anyone here is still dealing with this, I've been using Spectra as my daily inspector. It bypasses the Appium server entirely in Turbo Mode so screenshots and element trees load almost instantly. Has a free tier for basic inspection: https://usespectra.dev
