### ISSUE TITLE
Use of a TestFlight app in appium project

### ISSUE THREAD

**Issue by adelZilberman0** [appium/appium#19384]
### Discussed in https://github.com/appium/appium/discussions/19383

<div type='discussions-op-text'>

<sup>Originally posted by **adelZilberman0** November  8, 2023</sup>
Hello everyone, I'm having an issue with creating the right iOS app file for my appium project.
We have the app generated in TestFlight, so I tried to use it in the project but it didn't work. 
So I was wondering if anyone succeeded using a TestFlight app in appium or if not,
what do you find the best way to create an iOS app to work with appium?</div>

**Comment by KazuCocoa** [comment]
https://discuss.appium.io/ would help to ask such general questions
