### ISSUE TITLE
Can't Install UiAutomator2 in appium 

### ISSUE THREAD

**Issue by MahmudolHasan** [appium/appium#19395]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Trying to install UiAutomator2 gives me an error**
" × Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code null. "
---------------------------------
node version: v20.9.0
npm version: 10.1.0

### Expected Behavior

**Expected to Install UiAutomator2**

### Minimal Reproducible Example

`appium driver install uiautomator2`

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.2.1
- Appium driver(s) and their version(s):  N/A
- Appium plugin(s) and their version(s): N/A
- Node.js version (output of `node --version`): 20.9.0
- `npm` version (output of `npm --version`): 10.1.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Windows 10
- Real device or emulator/simulator: emulator

**Comment by mykola-mokhnach** [comment]
Please provide the full log

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by yuanshirenasdas24525** [comment]
![image](https://github.com/appium/appium/assets/150315853/8fd8aadd-c964-4610-9466-6b65c7535923)
