### ISSUE TITLE
bug: <mjpeg server not bind network card IP>

### ISSUE THREAD

**Issue by gointoit** [appium/appium#19390]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For android real service:
`"mjpeg_server_port":"7811",`

when do startRecordingScreen i can visit mobile screen  from http://127.0.0.1:7811 but i cannot visit from  http://LAN IP:7811

Through this command, it seems that 127.0.0.1 has been listening to this port since then：

` lsof -i -P -n | grep LISTEN | grep 7811 `
 `adb   1294 xxx   14u  IPv4 0x5d80687aff6bd379      0t0  TCP 127.0.0.1:7811 (LISTEN)`

### Expected Behavior

i can visit mobile screen  from  http://LAN IP:7811

### Minimal Reproducible Example

Use the latest version:
1. appium,
2. iautomator2
Using a real machine of android, and do startRecordingScreen after create session.
visit http://YOUR_LAN_IPL:mjpeg_server_port

### Environment

- Operating system: mac os 11.7.10 
- Appium server version (output of `appium --version`): 2.2.1
- Appium driver(s) and their version(s): uiautomator2@2.29.2
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v16.18.0
- `npm` version (output of `npm --version`): 8.19.2
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: android 11
- Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
This behaviour is expected for adb forward (and secure). Consider creating your own localhost forwarder to workaround that.
