### ISSUE TITLE
Getting Found no active devtools sockets, application is launching but not performing any action, can any one help me out to resolve the issue

### ISSUE THREAD

**Issue by Santhuravi05** [appium/appium#19391]
[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/18589ec0-4b94-4498-bd7b-b113919d7157/appium/app/close[39m
[35m[HTTP][39m [90m{}[39m
[debug] [35m[W3C (18589ec0)][39m Calling AppiumDriver.closeApp() with args: ["18589ec0-4b94-4498-bd7b-b113919d7157"]
[debug] [35m[ADB][39m Running 'C:\Users\arakes\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 93EAY0A2KT shell am force-stop com.cat.digital.mobile.sis2go'
[debug] [35m[AndroidDriver][39m Getting a list of available webviews
[debug] [35m[ADB][39m Running 'C:\Users\arakes\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 93EAY0A2KT shell cat /proc/net/unix'
[debug] [35m[AndroidDriver][39m **Found no active devtools sockets**
[debug] [35m[AndroidDriver][39m Other sockets are: [
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000002 00000000 00010000 0001 01 31635 @com.android.internal.os.WebViewZygoteInit/b443b83d-4a90-4695-b315-f4df591a1768",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000002 00000000 00010000 0001 01 16844 @time_genoff",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000002 00000000 00010000 0005 01 1490379 @jdwp-control",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000002 00000000 00000000 0002 01 23683 @gplisnr@",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000003 00000000 00000000 0005 03 1526563 @jdwp-control",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000003 00000000 00000000 0005 03 1519724 @jdwp-control",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000003 00000000 00000000 0005 03 1486494 @jdwp-control",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000003 00000000 00000000 0001 03 29502 @com.android.internal.os.WebViewZygoteInit/b443b83d-4a90-4695-b315-f4df591a1768",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000003 00000000 00000000 0005 03 1514208 @jdwp-control",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000003 00000000 00000000 0005 03 1510250 @jdwp-control",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000003 00000000 00000000 0005 03 1492121 @jdwp-control",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000003 00000000 00000000 0005 03 1492127 @jdwp-control",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000003 00000000 00000000 0005 03 1486495 @jdwp-control",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000003 00000000 00000000 0005 03 1513131 @jdwp-control",
[debug] [35m[AndroidDriver][39m   "0000000000000000: 00000003 00000000 00000000 0005 03 1492122 @jdwp-control"
[debug] [35m[AndroidDriver][39m ]
[debug] [35m[AndroidDriver][39m Found 0 webviews: []
[debug] [35m[AndroidDriver][39m Available contexts: ["NATIVE_APP"]
[debug] [35m[W3C (18589ec0)][39m Responding to client with driver.closeApp() result: null
[INFO ] 2023-11-09 15:26:56.997 [main] DateTimeUtil - Just closing browser session if exists
[35m[HTTP][39m [37m<-- POST /wd/hub/session/18589ec0-4b94-4498-bd7b-b113919d7157/appium/app/close [39m[32m200[39m [90m988 ms - 14[39m
[35m[HTTP][39m [90m[39m
[INFO ] 2023-11-09 15:26:57.034 [main] Hooks - 
***********************************************************************************

**Comment by mykola-mokhnach** [comment]
Closed because of no repsonse
