### ISSUE TITLE
Appium-adb uses adbkit-apkreader which is dependent on vulnerable debug version

### ISSUE THREAD

**Issue by RemigijusMazulis** [appium/appium#19396]
**Is your feature request related to a problem? Please describe.**
I am getting a security notices due to adbkit-apkreader being dependent on vulnerable debug version

`appium-uiautomator2-driver > appium-adb > adbkit-apkreader > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
`

**Describe the solution you'd like**
https://github.com/openstf/adbkit-apkreader is no longer maintained, so I believe the solution would be to use an alternative.
I also found a similar 3 years old issue (https://github.com/appium/appium/issues/13910) which comments show that someone from appium has got access to this repo, so maybe it is possible to upgrade/downgrade debug to non vulnerable version

**Additional context**

**Comment by mykola-mokhnach** [comment]
Could you propose any alternative to this package?
Would you be interested of supporting and maintaining the deprecated package yourself?

**Comment by saikrishna321** [comment]
https://github.com/DeviceFarmer/adbkit-apkreader

**Comment by RemigijusMazulis** [comment]
> Could you propose any alternative to this package? Would you be interested of supporting and maintaining the deprecated package yourself?

As stated in their readme 
![image](https://github.com/appium/appium/assets/92092655/3fc14b35-564a-4b9d-8185-08681d6089e2)

so I believe the one @saikrishna321 mentioned would be the one to be used instead of the deprecated one.
As for maintaining - no, I do not have enough knowledge for that and I do not want to commit myself to learn it

**Comment by mykola-mokhnach** [comment]
I can observe the forked module still depends on the [vulnerable](https://github.com/DeviceFarmer/adbkit-apkreader/blob/5fc5b28cb8c92e516d3ddd31d9c935847bc9cd04/package.json#L24) version of "debug" module.

Maybe report this issue there and then we consider switching to this module instead of the non-maintained one after it is fixed

**Comment by mykola-mokhnach** [comment]
I see @KazuCocoa was fast and has already created a PR. Thanks for that

**Comment by RemigijusMazulis** [comment]
> I can observe the forked module still depends on the [vulnerable](https://github.com/DeviceFarmer/adbkit-apkreader/blob/5fc5b28cb8c92e516d3ddd31d9c935847bc9cd04/package.json#L24) version of the "debug" module.

4.3.1 is no longer vulnerable. so it is not

**Comment by mykola-mokhnach** [comment]
The PR has been merged. All depending modules with get the new adb version soon
