### ISSUE TITLE
bug: can't install appium 

### ISSUE THREAD

**Issue by MohoWu** [appium/appium#19409]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running `npm i --location=global appium` gives me 7 moderate severity vulnerabilities.
Running `npm audit fix --force` doesn't really fix the issue, but keeps me in the loop of new severity vulnerabilities.
![image](https://github.com/appium/appium/assets/17207125/4caf7d13-4a57-49b2-8505-4163efa4c393)

### Expected Behavior

Install without any issues

### Minimal Reproducible Example

`npm i --location=global appium`

### Environment

- Operating system: macOS Sonoma 14.1.1

**Comment by mykola-mokhnach** [comment]
I don't see any issues in the above output. Some third party modules might have security vulnerabilities, but this does not prevent them from being installed. From the output above it is visible the package was installed just fine.

**Comment by MohoWu** [comment]
But when I run `appium`, it still says command not found.
![image](https://github.com/appium/appium/assets/17207125/6d733a83-be66-49f4-9a8a-7892840bcc77)

**Comment by mykola-mokhnach** [comment]
It is most likely happening because you don't have the PATH environment varibale configured properly.
The issue has nothing to do with Appium itself.

**Comment by MohoWu** [comment]
I really don't know what happened. I tried today using `npm i -g appium` then it gives me some useful error saying permission denied. Then I tried `sudo npm i -g appium`, it worked.
