### ISSUE TITLE
bug: Hang on getPageSource due to 

### ISSUE THREAD

**Issue by baovu2512** [appium/appium#19413]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [ ] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

App hang when get page source due to WDA xcode error
```
[Xcode] 2023-11-14 12:02:21.191610+0700 WebDriverAgentRunner-Runner[67165:11000236] Cannot retrieve element attribute(s) (
[Xcode]     "XC_kAXXCAttributeIsElement"
[Xcode] ). Original error: Error Domain=com.apple.dt.xctest.automation-support.error Code=11 "Accessibility error kAXErrorInvalidUIElement from AXUIElementCopyMultipleAttributeValues for 2016" UserInfo={accessibility-error=-25202, NSLocalizedDescription=Accessibility error kAXErrorInvalidUIElement from AXUIElementCopyMultipleAttributeValues for 2016}
[Xcode] 
```

### Expected Behavior

Get page source get element successful and bind attribute correct.

### Minimal Reproducible Example

not sure

### Environment

- Operating system:
- Appium server version (output of `appium --version`): tried with both 1.22.3 and 2.2.1
- Appium driver(s) and their version(s): xcuitest 4.9.4 or 4.35.0
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): 16.15.0
- `npm` version (output of `npm --version`): 9.8.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: IOS 16.1
- Real device or emulator/simulator: simulator

### Link to Appium Logs

https://gist.github.com/baovu2512/1a11ca0635104ec2954f8cc336f3cdea

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot do anything about such errors as hey are coming from xctest. Consider reporting it to Apple.
