### ISSUE TITLE
XCUITestDriver connect ECONNREFUSED 127.0.0.1:8100

### ISSUE THREAD

**Issue by yyuanmeme** [appium/appium#19412]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Initially the XCUITestDriver session is created successfully, but after running for a minute I get an error XCUITestDriver connect ECONNREFUSED 127.0.0.1:8100
![image](https://github.com/appium/appium/assets/145118150/16277882-7e41-4ed7-bb12-047e83bd1125)

### Expected Behavior

XCUITestDriver does not report errors

### Minimal Reproducible Example

public XCUITestOptions initXCUITestOptions(CaseContext caseContext) {
        return new XCUITestOptions()
                .setAutomationName(AutomationName.IOS_XCUI_TEST)
                .setPlatformName(caseContext.getPlatformName())
                .setPlatformVersion(caseContext.getPlatformVersion())
                .setDeviceName(caseContext.getDeviceName())
                .setFullReset(caseContext.getFullReset())
                .setNoReset(caseContext.getNoReset())
                .setUdid(caseContext.getUdid())
                .setNewCommandTimeout(Duration.ofMillis(20000))
                .setClearSystemFiles(true)
                .setBundleId(caseContext.getBundleId())
                .setAutoAcceptAlerts(true)
                .setShowIosLog(false)
                .setAutoDismissAlerts(true)
                .setWdaStartupRetries(4)
                .setWdaStartupRetryInterval(Duration.ofMillis(20000));
    }

 if (MobilePlatform.IOS.equalsIgnoreCase(caseContext.getPlatformName())) {
                XCUITestOptions options = initXCUITestOptions(caseContext);
                IOSDriver iosDriver = new IOSDriver(appiumDriverLocalService.get(), options);
                new WebDriverWait(iosDriver, ofSeconds(2));
                caseContext.setIosDriver(iosDriver);
            }

### Environment

- Operating system:
- Appium server version (output of `appium --version`):2.2.1
- Appium driver(s) and their version(s):xcuitest 4.12.2
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):21.1.0
- `npm` version (output of `npm --version`):10.2.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:ios 16.2
- Real device or emulator/simulator:simulator

**Comment by mykola-mokhnach** [comment]
- Make sure the driver is up to date
- Check the device logs. It might be that WDA crashes or there is some network issue, which makes it to disconnect

**Comment by yyuanmeme** [comment]
> * WDA crashes
How to solve the WDA crash

**Comment by yyuanmeme** [comment]
I got the error :webdriveragent runner unexpectedly exited
![image](https://github.com/appium/appium/assets/145118150/03b29f05-a110-4902-8d1c-75c4b70e699a)

**Comment by yyuanmeme** [comment]
I update the driver and xcuitest, but i still get this error
driver version is 2.2.1 
xcuitest version is 4.35.0

**Comment by mykola-mokhnach** [comment]
The most recent xciotest driver version is 5.8.2
I cannot advice anything without having the device log

**Comment by yyuanmeme** [comment]
I update the xcuitest to 5.8.2,but still get the error.
driverlog:
[driverlog.txt](https://github.com/appium/appium/files/13348802/driverlog.txt)
I use two emulators to run appium automation at the same time。
Is this problem caused by two emulators to run appium automation at the same time

**Comment by mykola-mokhnach** [comment]
> xcodebuild clean -project /Users/ibu_mini4/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner

Have you tried to run this command manually? what is the actual output?

**Comment by yyuanmeme** [comment]
![image](https://github.com/appium/appium/assets/145118150/050d1621-1854-499b-80ea-b7c2cba36ec2)


> > xcodebuild clean -project /Users/ibu_mini4/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner
> 
> Have you tried to run this command manually? what is the actual output?

![image](https://github.com/appium/appium/assets/145118150/2e3fece1-dd74-4e20-9826-57249195d3da)

**Comment by yyuanmeme** [comment]
> If it works manually then you probably have your parallel tests not configured properly. Do you follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/parallel-tests.md ?

I remove the --session-override,but when i restart the app still get connect ECONNREFUSED 127.0.0.1:8100

this is start appium code:
AppiumServiceBuilder builder = new AppiumServiceBuilder()
.withIPAddress("127.0.0.1")
.withArgument("--local-timezone")
.withArgument("--relaxed-security")
// .withArgument(GeneralServerFlag.SESSION_OVERRIDE) 
.withArgument("--log-level", "info:debug")
.withArgument(() -> "-g", driverLogPath)
.withTimeout(Duration.ofMillis(50000))
.usingAnyFreePort(); 
AppiumDriverLocalService service = AppiumDriverLocalService.buildService(builder);

this is restart app code:
public void iosRestart(IOSDriver iosDriver, String bundleId) {
        CpLogContext.getCpLog().info("terminate app {}", bundleId);
        iosDriver.terminateApp(bundleId);
        ThreadUtil.sleep(1000);
        CpLogContext.getCpLog().info("active app {}", bundleId);
        iosDriver.activateApp(bundleId);
        ThreadUtil.sleep(1000);
    }

logs:
[log.txt](https://github.com/appium/appium/files/13362018/log.txt)

**Comment by mykola-mokhnach** [comment]
The above error is expected. The recent WDA version does not support iOS 14. Only iOS 15+ is supported.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
