### ISSUE TITLE
bug: The button text is not visible in XML inspection but is displayed in the visual view of the hybrid app.

### ISSUE THREAD

**Issue by luissanchez0305** [appium/appium#19423]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The button text when the element in android.widget.button is inspected appears as empty text, but it strangely appears in the view. As I show in the attached image, the error happens on some buttons, not all of them, in addition to that it usually happens on some Android devices regardless of the version. The application is a hybrid app built with ionic and angular.

<img width="1439" alt="appnium" src="https://github.com/appium/appium/assets/1278025/570b5283-6043-4162-bc1d-a5afbf335815">

### Expected Behavior

It should show the text of the selected button on appium inspector

### Minimal Reproducible Example

N/A

### Environment

- Operating system: MacOs Sonoma v14
- Platform and version under test: browserstack, integrate appium inspector
- Real device or emulator/simulator: Real devices: Pixel 5, Pixel 4, s10, s10 +

**Comment by mykola-mokhnach** [comment]
Check with your developers regarding proper attributes exposal to the accessibility framework. UIA2 (to be precise the downstream Google's UiAutomator framework) driver receives all values from there.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by KazuCocoa** [comment]
Appium's element information basically depends on https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo, thus it possibly indicates the framework behaves so for Android API. (or the parent element has the value? I don't know though)

**Comment by luissanchez0305** [comment]
> Appium's element information basically depends on https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo, thus it possibly indicates the framework behaves so for Android API. (or the parent element has the value? I don't know though)

Thanks for the answer @KazuCocoa 
I checked the parent element and the Text is not there. 
Thanks for the hint on the AccessibilityNodeInfo view element, curiously that raised another question, how is it possible that the Android API set a Text to the button and shows in the view, but it doesn't show in the inspector?

**Comment by aabirdaneshyar** [comment]
Hello @luissanchez0305 ,

Are you able to find the solution to your problem ?
