### ISSUE TITLE
Error with typedoc while installing appium

### ISSUE THREAD

**Issue by PhantomMizuchi** [appium/appium#19421]
C:\Users\lenovo>npm i --location=global appium
npm WARN deprecated typedoc-plugin-resolve-crossmodule-references@0.3.3: Upgrade to typedoc >= 0.24 and remove typedoc-plugin-resolve-crossmodule-references from your dependencies

changed 490 packages in 16s

61 packages are looking for funding
  run `npm fund` for details
When the installation reaches this point ,it cannot continue

**Comment by mykola-mokhnach** [comment]
I don't observe any errors above. Could you please be more specific?

**Comment by PhantomMizuchi** [comment]
C:\Users\lenovo>npm i --location=global appium
npm WARN deprecated typedoc-plugin-resolve-crossmodule-references@0.3.3: Upgrade to typedoc >= 0.24 and remove typedoc-plugin-resolve-crossmodule-references from your dependencies

When this error message appears, my installation of Appium failed. Where is the problem?

**Comment by mykola-mokhnach** [comment]
This is not an error, but a warning about package deprecation. It does not affect the installation process.

**Comment by PhantomMizuchi** [comment]
C:\Users\lenovo>npm i --location=global appium
npm WARN deprecated typedoc-plugin-resolve-crossmodule-references@0.3.3: Upgrade to typedoc >= 0.24 and remove typedoc-plugin-resolve-crossmodule-references from your dependencies

changed 490 packages in 1m

C:\Users\lenovo>appium
“‘appium’ is not recognized as an internal or external command, operable program or batch file.”

C:\Users\lenovo>

The installation process only had the above information. When I entered ‘appium’ to test whether the installation was successful, I got the message “‘appium’ is not recognized as an internal or external command, operable program or batch file.” The installation failed.

**Comment by mykola-mokhnach** [comment]
Most likely the folder where npm installs global binaries is not included into PATH. Check https://stackoverflow.com/questions/27344045/installing-node-js-and-npm-on-windows-10

**Comment by PhantomMizuchi** [comment]
![jpg](https://github.com/appium/appium/assets/149344213/ab85eac9-4f33-48be-a798-788bb59d3ae3)
“When I use the Appium Inspector, the mobile interface cannot be loaded.”

**Comment by mykola-mokhnach** [comment]
Unfortunately we cannot help by just looking at screenshots.

Please consider providing a proper issue report according to the given template. If you think this is the bug of Inspector then please report it to the appropriate issue tracker. 

We also have [forum](https://discuss.appium.io) for asking questions.

Closed as incomplete
