### ISSUE TITLE
There is an error for my device - Oneplus nord CE2 Lite

### ISSUE THREAD

**Issue by Vijaykumar2004** [appium/appium#19432]
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Check https://forum.xda-developers.com/t/i-cant-enable-write_secure_settings-for-an-app-over-adb.________/ for throubleshooting. Error executing adbExec. Original error: 'Command 'C:\\Users\\Vijay\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P ____ -s _______shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy'' exited with code 255'; Command output: Exception occurred while executing 'delete': java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:2562) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1562) at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1554) at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1525) at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:568) at android.content.ContentProvider.call(ContentProvider.java:2511) at android.content.ContentProvider$Transport.call(ContentProvider.java:525) at com.android.providers.settings.SettingsService$MyShe

**Comment by Vijaykumar2004** [comment]
For privacy reasons I removed the device details

**Comment by mykola-mokhnach** [comment]
What exactly is unclear with the error message above?

**Comment by Vijaykumar2004** [comment]
In appium inspector after giving the desired capabilities when click on start session I'm getting this kind of error. Which is required some more security settings have to enable but don't know what exactly happening.

**Comment by KazuCocoa** [comment]
One of https://github.com/appium/appium/issues/13802 might help.
https://github.com/appium/appium-uiautomator2-driver/blob/91d9c3430fbf4039ea1a18fb361abd0f1e568528/lib/driver.ts#L451

**Comment by mykola-mokhnach** [comment]
@KazuCocoa It looks like the link above has expired. We probably need to replace it with something less volatile

**Comment by mykola-mokhnach** [comment]
Updated the link in appium-adb and published it.
