### ISSUE TITLE
bug: Invalid value of 'value' and 'text' properties in the page source of a react-native app on `appium-xcuitest-driver@5.9.0`

### ISSUE THREAD

**Issue by qarify** [appium/appium#19434]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Invalid property values in a page source XML

```xml
<!-- INPUT: react-native jsx -->
<Text accessibilityLabel='displayLarge'>
  Display Large
</Text>

<!-- OUTPUT: page source XML -->
<Text
  value="displayLarge"
  visible="true" accessible="true" x="16" y="131" width="358" height="65"
  axId="displayLarge"
  text="displayLarge">
</Text>
```

### Expected Behavior

- Output: page source XML
```diff
 <Text 
-  value="displayLarge" 
+  value="display Large" 
   visible="true" accessible="true" x="16" y="131" width="358" height="65"
   axId="displayLarge"
-  text="displayLarge">
+  text="display Large">
 </Text>
```

### Minimal Reproducible Example

```jsx
// INPUT: react-native jsx
<Text accessibilityLabel='displayLarge'>
  Display Large
</Text>
```

### Environment

- Operating system: macOS 14.1.1
- Appium server version (output of `appium --version`): v2.2.2
- Appium driver(s) and their version(s): appium-xcuitest-driver@5.9.0, uiautomator2@2.32.0
- Appium plugin(s) and their version(s): universal-xml@1.0.12
- Node.js version (output of `node --version`): v20.8.1
- `npm` version (output of `npm --version`): 10.1.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: 

### Further Information

- `uiautomator2@2.32.0` works as expected:
```xml
<!-- OUTPUT: page source XML -->
<Text
  text="Display Large"
  x="42" y="284" width="996" height="168"
  axId="displayLarge"
  visible="true">
</Text>
```

- `appium-xcuitest-driver@5.9.0` works as expected with `textID`:
```xml
<!-- INPUT: react-native jsx -->
<Text testID='displayLarge'>
  Display Large
</Text>

<!-- OUTPUT: page source XML -->
<Text 
  value="display Large" 
  visible="true" accessible="true" x="16" y="131" width="358" height="65"
  axId="displayLarge"
  text="display Large">
</Text>
```

**Comment by mykola-mokhnach** [comment]
Please report the issue to Apple. We cannot influence the way element attributes are retrieved.
