### ISSUE TITLE
[CI/CD] - Fix WebDriverAgent CI/CD release workflow

### ISSUE THREAD

**Issue by IlyaUA** [appium/appium#19447]
**Issue:** At this time, releases for WebDriverAgent are not being built or published. 
It can be seen in the GitHub Actions logs 

**Example**
WDA release version [5.15.0](https://github.com/appium/WebDriverAgent/actions/runs/6889428876)
WDA release version [5.15.1](https://github.com/appium/WebDriverAgent/actions/runs/6896584337)

**Build error:** `Process completed with exit code 1.`

**Comment by KazuCocoa** [comment]
It looks like npm token was expired or invalid for the package. We updated the repository's npm token with the same one used by other npm releases in this org, thus should be ok for new ones.

**Comment by IlyaUA** [comment]
@KazuCocoa Thanks!
