### ISSUE TITLE
bug: <Appium Documentation switch to Chinese language display 404>

### ISSUE THREAD

**Issue by dengnao-tw** [appium/appium#19458]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![ED4g7a](https://cdn.jsdelivr.net/gh/naodeng/blogimg@master/uPic/ED4g7a.png)

### Expected Behavior

Appium Documentation switches to Chinese language to display pages properly.

### Minimal Reproducible Example

https://appium.io/docs/zh/

### Environment

- Operating system: Mac OS

### Further Information

https://appium.io/docs/zh/

**Comment by KazuCocoa** [comment]
Let me check.
https://appium.io/docs/zh/latest/ is expected one right now

**Comment by KazuCocoa** [comment]
Hm, the issue itself was no index.hml in the `zh` resource: https://github.com/appium/appium/tree/gh-pages/docs

**Comment by KazuCocoa** [comment]
Added the missing index.html

**Comment by dengnao-tw** [comment]
@KazuCocoa  Thanks for the quick response.
