### ISSUE TITLE
bug: Child Elements of flatlist unreachable 

### ISSUE THREAD

**Issue by Harsh121998** [appium/appium#19464]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have multiple components inside a flatlist in my iOS app. These include custom button's, labels and touchable opacity. I am not able to inspect these individually in Appium Inspector. 

### Expected Behavior

Like other elements in my iOS app, i should be able to inspect each component, built-in or custom individually on Appium inspector, with seperate Test-Ids.

### Minimal Reproducible Example

                                   <Flatlist
                     accessibilityLabel = {AccessibilityLabelStrings.1} accessibilityHint = {AccessibilityHintStrings.1} testID = 
                     {TestIds.1}
                     renderItem={(data) =>
                      
                                  <View style={{ padding: 10, height: 100, width: '100%' }} accessibilityLabel = 
                         {AccessibilityLabelStrings.2}
                    accessibilityHint = {AccessibilityHintStrings.2}
                    testID = {TestIds.2}>
                                  <View style={{ backgroundColor: 'green', flex: 1, flexDirection: 'row' }}accessibilityLabel = {AccessibilityLabelStrings.3}
                    accessibilityHint = {AccessibilityHintStrings.3}
                    testID = {TestIds.3}>
                                  <ActionButton text='Tap Me' onPress={() => console.log('tappedd')} accessibilityLabel = {AccessibilityLabelStrings.4}
                    accessibilityHint = {AccessibilityHintStrings.4}
                    testID = {TestIds.4}/>
                                <View style={{ backgroundColor: 'yellow', flex: 1 }} accessibilityLabel = {AccessibilityLabelStrings.5}
                    accessibilityHint = {AccessibilityHintStrings.5}
                    testID = {TestIds.5}>
                                    <ActionButton text='Tap Me-44' onPress={() => console.log('tappedd')} accessibilityLabel = {AccessibilityLabelStrings.6}
                    accessibilityHint = {AccessibilityHintStrings.6}
                    testID = {TestIds.6}/>
                                </View>
                            </View>
                        </View>
                    }
                   />

### Environment

{
  "platformName": "iOS",
  "appium:deviceName": "iPad Pro (12.9-inch) (6th generation)",
  "appium:automationName": "XCUITest",
  "appium:platformVersion": "17.0",
}

**Comment by eglitise** [comment]
This is likely related to #14825. Try changing the `snapshotMaxDepth` setting in your capabilities like so: `"appium:settings[snapshotMaxDepth]": 62`
Please note that 62 is the maximum supported value - check the issue for more details.

**Comment by Harsh121998** [comment]
I tried this resolution, it is still not working as expected

**Comment by mykola-mokhnach** [comment]
Unfortunately don't know other possible workarounds aside these described in the above issue. You could also try to report the issue to Apple.
