### ISSUE TITLE
The help documentation for creating WebDriverAgentRunner-Runner.app is out of date,I need help.

### ISSUE THREAD

**Issue by Yesisyes** [appium/appium#19462]
My Apple developer account is free.Then I followed the help document to the steps shown in the figure.
![test](https://github.com/appium/appium/assets/55627281/a9371673-fb61-4625-a94d-93cb7fef2a41)
Then I was told that my developer account needed to be tied to a device. 
![test2](https://github.com/appium/appium/assets/55627281/4e80bc95-1338-4b2c-b2d4-de4762041c59)
But free developers account on the https://developer.apple.com website without registration equipment functions, what should I do?
Or can someone provide a WebDriverAgentRunner-Runner.app that is common on ios14.4? Thank you so much!

**Comment by Yesisyes** [comment]
@KazuCocoa,Do you have any suggestions?

**Comment by KazuCocoa** [comment]
What value was shown in the _The important part is to use a unique "Product Name" and "Organization Name". Also, at this point, specify your "Team"._ step? `io.appium` should be invalid for you. Proper one was probably preset.

**Comment by KazuCocoa** [comment]
Asking such a question https://discuss.appium.io/ also may help

**Comment by Yesisyes** [comment]
I've set all of those points correctly. Is it because my iPhone hasn't been updated to the latest iOS? Because I see the red line in the picture below
![test3](https://github.com/appium/appium/assets/55627281/e5a6d0e2-24a6-4885-b26c-9262d3bcf929)

**Comment by Yesisyes** [comment]
> What was the organization name/identifier when you created a new project? Probably it should not have been `io.appium`

I started by following the help document in the first screenshot.

![help_documents](https://github.com/appium/appium/assets/55627281/a5f5efe9-0bfc-442d-bf80-531a7e620536)

Below is a screenshot of my steps, which failed.

![1](https://github.com/appium/appium/assets/55627281/1f533da4-743b-475f-877c-5257cd528971)
![2](https://github.com/appium/appium/assets/55627281/4447aa7f-6312-470e-b6c2-04be4e210f75)
![3](https://github.com/appium/appium/assets/55627281/06ec41ba-da80-486c-857e-9d58e117a5c5)
![4](https://github.com/appium/appium/assets/55627281/53f0aadc-2d77-415b-bc58-e385df92df1a)

I then ran the "appium driver run xcuitest open-wda" command, with the intention of doing the full manual configuration. So here we are in the screenshot of my first question.
No matter what I do, this Xcode tells me that I must have a device attached to my developer account. My Xcode version is 15.0.1.

**Comment by Yesisyes** [comment]
I started by following the help document in the first screenshot.
![help_documents](https://github.com/appium/appium/assets/55627281/a5f5efe9-0bfc-442d-bf80-531a7e620536)
Below is a screenshot of my steps, which failed.
![1](https://github.com/appium/appium/assets/55627281/1f533da4-743b-475f-877c-5257cd528971)
![2](https://github.com/appium/appium/assets/55627281/4447aa7f-6312-470e-b6c2-04be4e210f75)
![3](https://github.com/appium/appium/assets/55627281/06ec41ba-da80-486c-857e-9d58e117a5c5)
![4](https://github.com/appium/appium/assets/55627281/53f0aadc-2d77-415b-bc58-e385df92df1a)
I then ran the "appium driver run xcuitest open-wda" command, with the intention of doing the full manual configuration. So here we are in the screenshot of my first question.
No matter what I do, this Xcode tells me that I must have a device attached to my developer account. My Xcode version is 15.0.1.

**Comment by Yesisyes** [comment]
I started by following the help document in the first screenshot.
![help_documents](https://github.com/appium/appium/assets/55627281/5b7efee9-5969-4013-9fef-30dc732c8dd7)

Below is a screenshot of my steps, which failed.
![1](https://github.com/appium/appium/assets/55627281/2c5b78b4-1398-43e6-8b5e-5b36df05a65b)
![2](https://github.com/appium/appium/assets/55627281/355543bd-6372-4352-8209-5c9891779e4e)
![3](https://github.com/appium/appium/assets/55627281/0db1bcc8-d3e1-4e8d-bc11-51a8dd43786a)
![4](https://github.com/appium/appium/assets/55627281/76b094f9-7297-4796-956a-b2a2b5db8b5e)

I then ran the "appium driver run xcuitest open-wda" command, with the intention of doing the full manual configuration. So here we are in the screenshot of my first question.
No matter what I do, this Xcode tells me that I must have a device attached to my developer account. My Xcode version is 15.0.1.

**Comment by Yesisyes** [comment]
> What was the organization name/identifier when you created a new project? Probably it should not have been `io.appium`

Can you see the screenshot I sent? I just noticed that the screenshots in my reply are gone.

**Comment by KazuCocoa** [comment]
I haven't seen your case's format... but perhaps `-87718696-qq.com` is your account's identifier. Or `487718696@qq.com`. I don't know of the correct one, but probably either. Then, you should use this value instead if `io.appium` for your account.
 
![Screenshot 2023-11-30 at 8 43 37 PM](https://github.com/appium/appium/assets/5511591/babc6078-2c2f-423f-b6c1-6c0abd441668)

The singing itself does not require connected device.

**Comment by Yesisyes** [comment]
![2](https://github.com/appium/appium/assets/55627281/4f855ce1-8ca7-4d5d-9845-94e4ee6bf052)
  I'm an individual Developer and not part of the Apple Developer Program.
  Maybe it has something to do with Internet speed? I can see the screenshot I sent. But when I clicked on the screenshot from my response, GitHub told me I couldn't download it because it was empty... My Apple Developer is 487718696@qq.com.So, under "Organization Identifier: "I wrote 487718696@qq.com.However, the "Bundle Identifier:" field is filled in automatically by Xcode.
  How do I install "WebDriverAgentRunner-Runner.app" on my iPhone if I don't build an APP? Does this "appium-xcuitest-driver" require the iPhone to have "WebDriverAgentRunner-Runner.app" installed in order to work?

**Comment by eglitise** [comment]
I would suggest resolving the Xcode warning and installing iOS 17. This will install the iOS 17 _simulator_, which will not affect your real device, but it may fix the error.
Then you may want to try changing the WDA bundle identifier value to something closer to the default format (`com.facebook.WebDriverAgentRunner`). I usually only change the `facebook` part, so you can try something like `com.Mybk-IOS.WebDriverAgentRunner`.
Finally, if you want to run your tests on a device with iOS 14.4, please note that the current version of `appium-xcuitest-driver` (`5.11.0`) only supports iOS 15 and newer. The latest version that supports iOS 14 is `4.27.2`.

**Comment by Yesisyes** [comment]
@KazuCocoa  If you have time, can I send you an email to discuss APP testing? Because I want to interact with any APP as much as possible, so that I can capture the various network traffic of this APP and extract more network traffic characteristics about this APP.But I have yet to find a satisfactory open source framework that can make any APP as interactive as possible.

**Comment by KazuCocoa** [comment]
Interesting case, My free account's org identifier was `com.kazucocoa`, so in my case, `com.kazucocoa.WDA` for example, was valid. In your case, I wonder if you should use `-87718696-qq.com` in the latest your comment in https://github.com/appium/appium/issues/19462#issuecomment-1835572599 . If it does not work, I'm not sure how you can get valid prefix for your free account.

I think you firstly need to check what bundlle id works for you by creating a blank app from Xcode template before doing something with Appium's WDA. So, create a project from Xcode template like https://github.com/appium/appium/issues/19462#issuecomment-1835572599 -> installs the template app with your free account. Then for example if the app `-87718696-qq.com.Mybk0-iOIS` bundle id succeed in installing to a real device, maybe `-87718696-qq.com.WebDriverAgentRunner` bundle id (for example) will work for you

**Comment by Yesisyes** [comment]
> Interesting case, My free account's org identifier was `com.kazucocoa`, so in my case, `com.kazucocoa.WDA` for example, was valid. In your case, I wonder if you should use `-87718696-qq.com` in the latest your comment in https://github.com/appium/appium/issues/19462#issuecomment-1835572599 . If it does not work, I'm not sure how you can get valid prefix for your free account.
> 
> I think you firstly need to check what bundlle id works for you by creating a blank app from Xcode template before doing something with Appium's WDA. So, create a project from Xcode template like https://github.com/appium/appium/issues/19462#issuecomment-1835572599 -> installs the template app with your free account. Then for example if the app `-87718696-qq.com.Mybk0-iOIS` bundle id succeed in installing to a real device, maybe `-87718696-qq.com.WebDriverAgentRunner` bundle id (for example) will work for you
> 
> I can respond email when I have time. Feel free to send an email to my github profile's one if needed. 

    My Apple account is bound to a mobile phone number in Chinese Mainland, so I can't register an Apple developer account. So I registered an Apple developer account with my email(487718696@qq.com), and linked it to my Apple account.I don't know why Xcode automatically fills "87718696-qq.com" for me.
    I've already started to try those methods, but Saturday and Sunday are coming, you know 😏. We'll find out next week. I think I will email you tomorrow to ask questions about the deep test App framework, happy weekend friends.

**Comment by Yesisyes** [comment]
I downloaded the iOS emulator and opened it, then I logged in with Xcode using my phone number instead of the developer email associated with my phone number. Now when I create an APP, I don't see a warning in the "Signing & Capabilities" screen, it just says it's valid for 6 days.
![new](https://github.com/appium/appium/assets/55627281/b0f76323-b46a-46ec-8050-c70831a2a972)

**Comment by KazuCocoa** [comment]
Yes, it is expected. Free accounts can use the same certificate in a week. So, apps signed with the free account's signature can work on a device for a week. Then, you should re-sign the app.
