### ISSUE TITLE
bug: iOS getAppearance always returns light

### ISSUE THREAD

**Issue by DzmitryIlyin** [appium/appium#19486]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

iOS 'mobile: getAppearance' always returns light even when dark mode is enabled.

### Expected Behavior

iOS 'mobile: getAppearance' returns currently enabled UI mode on iOS device.

### Minimal Reproducible Example

Set dark mode on iOS device either in Settings or via 'mobile: setAppearance' xcuitest's command, then execute mobile: getAppearance' and result is 'style -> light'.

### Environment

- Operating system: MacOS
- Appium server version (output of `appium --version`): 2.1.3
- Appium driver(s) and their version(s): xcuitest 5.12.0
- Appium plugin(s) and their version(s): -
- Node.js version (output of `node --version`): v21.1.0
- `npm` version (output of `npm --version`): 10.2.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS16.7
- Real device or emulator/simulator: Real iPhone 13

**Comment by KazuCocoa** [comment]
Could you attach the full appium log? It worked on my environment with the same ios 16.7 device.

**Comment by KazuCocoa** [comment]
Thank you, the, could you try out the latest xcuitest?

I fixed the setting appearance for ios 17 I found. I wonder if it is also needed for ios 16.7.

I assume theme configured via Siri did not change something ios internal that the getAppearance command referred to. (via XCTest frameworks by Apple)

**Comment by DzmitryIlyin** [comment]
Seems like it also needs to be fixed for iOS16, please check those logs https://gist.github.com/DzmitryIlyin/323140f7cacb0b1283ba9e7a80bb4229.
So test started with Dark mode enabled on the iOS device, then command to change it to Light was sent twice (and device's ui appearance was actually changed to light), but when trying to getAppearance it's still Dark.

**Comment by KazuCocoa** [comment]
Then, it looks like the iOS 16.7 internal issue, which was fixed in iOS 17. Appium refers to `appearanceMode` provided by XCTest https://github.com/appium/WebDriverAgent/blob/de124e1bb02a5897da7b1b99cb6fbfc5569ab6bd/WebDriverAgentLib/Categories/XCUIDevice%2BFBHelpers.m#L360

**Comment by KazuCocoa** [comment]
Hm, iOS 16.7 device I could try out had no issue. It might have a more specific condition to return the incorrect value in iOS, I assume.

**Comment by DzmitryIlyin** [comment]
I've checked on iPhone SE with iOS17.0.3 and issue reproduced there as well, here are the logs https://gist.github.com/DzmitryIlyin/323140f7cacb0b1283ba9e7a80bb4229.

**Comment by KazuCocoa** [comment]
Please try out xcuitest driver 5.12.2. It is currently what we can do. If your case still occurs, then it would be iOS internal, thus nothing can do as appium

**Comment by DzmitryIlyin** [comment]
@KazuCocoa , sorry for the late response, I've tried xcuitest driver 5.12.2 and issue didn't reproduced, so it's fixed.
