### ISSUE TITLE
bug: Building WebdriverAgentRunner failed due to link error 

### ISSUE THREAD

**Issue by hishamo76** [appium/appium#19535]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

building WebdriverAgentRunner is failing due to link error. 

### Expected Behavior

Build should succeed 

### Minimal Reproducible Example

N/A

### Environment

- Operating system: Mac OS Sonoma v 14.2
- Appium server version (output of `appium --version`): 2.2.3
- Appium driver(s) and their version(s): xcuitest@4.35.0 
- Appium plugin(s) and their version(s): 
- Node.js version (output of `node --version`): v21.4.0
- `npm` version (output of `npm --version`): 10.2.4
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: Real iOS Device

### Link to Appium Logs

hishamo76/gist:b1b53f845ac3fdca4cc58774abd1b5be

**Comment by KazuCocoa** [comment]
Please attach the full appium log to help our understanding, and please try out the latest XCUITest driver version, `xcuitest@4.35.0` which is old.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
