### ISSUE TITLE
Mobile app interface cannot be loaded in appium inspector for iOS simulator

### ISSUE THREAD

**Issue by abishekkulkarni** [appium/appium#19544]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run the Appium Inspector, the iOS mobile app interface cannot be loaded, and it just keeps loading.
I’ve updated the appium inspector, xcode, node, npm, and appium to the latest version, but I'm still facing the same issue.

<img width="1520" alt="Screenshot 2023-12-18 at 10 15 19 AM" src="https://github.com/appium/appium/assets/82461401/f8b0b4af-d7c3-4bbb-b2ea-e1c70324c7c0">
<img width="1515" alt="Screenshot 2023-12-18 at 9 59 24 AM" src="https://github.com/appium/appium/assets/82461401/4f91598f-b785-4b6e-a3dd-cf26db7d8f14">

### Expected Behavior

When we run the Appium Inspector, the iOS mobile app interface should be loaded.

### Minimal Reproducible Example

Run `appium --base-path /wd/hub` in the terminal.
Start the appium inspector, provide the required details in JSON file format and start the session.
The appium inspector will hit the simulator based on the JSON submitted.

```
[XCUITestDriver@5774 (fec9a095)] Calling AppiumDriver.getWindowRect() with args: ["fec9a095-b87e-43e3-9a4a-58cb696a3cc5"]
[XCUITestDriver@5774 (fec9a095)] Executing command 'getWindowRect'
[XCUITestDriver@5774 (fec9a095)] Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/9127B76A-6C3B-4E75-B9B9-A442C449F1A9/window/size] with no body
[XCUITestDriver@5774 (fec9a095)] Got response with status 200: {"value":{"width":430,"height":932},"sessionId":"9127B76A-6C3B-4E75-B9B9-A442C449F1A9"}
[XCUITestDriver@5774 (fec9a095)] Responding to client with driver.getWindowRect() result: {"width":430,"height":932,"x":0,"y":0}
[HTTP] <-- GET /wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/window/rect 304 218 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/source
[HTTP] {}
[XCUITestDriver@5774 (fec9a095)] Calling AppiumDriver.getPageSource() with args: ["fec9a095-b87e-43e3-9a4a-58cb696a3cc5"]
[XCUITestDriver@5774 (fec9a095)] Executing command 'getPageSource'
[XCUITestDriver@5774 (fec9a095)] Matched '/source?format=xml&scope=AppiumAUT' to command name 'getPageSource'
[XCUITestDriver@5774 (fec9a095)] Proxying [GET /source?format=xml&scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/9127B76A-6C3B-4E75-B9B9-A442C449F1A9/source?format=xml&scope=AppiumAUT] with no body
[HTTP] --> GET /wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/timeouts
[HTTP] {}
[XCUITestDriver@5774 (fec9a095)] Calling AppiumDriver.getTimeouts() with args: ["fec9a095-b87e-43e3-9a4a-58cb696a3cc5"]
[XCUITestDriver@5774 (fec9a095)] Executing command 'getTimeouts'
[HTTP] --> GET /wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/timeouts
[HTTP] {}
[XCUITestDriver@5774 (fec9a095)] Calling AppiumDriver.getTimeouts() with args: ["fec9a095-b87e-43e3-9a4a-58cb696a3cc5"]
[XCUITestDriver@5774 (fec9a095)] Executing command 'getTimeouts'
[HTTP] --> GET /wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/timeouts
[HTTP] {}
[XCUITestDriver@5774 (fec9a095)] Calling AppiumDriver.getTimeouts() with args: ["fec9a095-b87e-43e3-9a4a-58cb696a3cc5"]
[XCUITestDriver@5774 (fec9a095)] Executing command 'getTimeouts'
[HTTP] --> GET /wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/timeouts
[HTTP] {}
[XCUITestDriver@5774 (fec9a095)] Calling AppiumDriver.getTimeouts() with args: ["fec9a095-b87e-43e3-9a4a-58cb696a3cc5"]
[XCUITestDriver@5774 (fec9a095)] Executing command 'getTimeouts'
[HTTP] --> GET /wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/timeouts
[HTTP] {}
[XCUITestDriver@5774 (fec9a095)] Calling AppiumDriver.getTimeouts() with args: ["fec9a095-b87e-43e3-9a4a-58cb696a3cc5"]
[XCUITestDriver@5774 (fec9a095)] Executing command 'getTimeouts'
[XCUITestDriver@5774 (fec9a095)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/timeouts 304 2 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/timeouts
[HTTP] {}
[XCUITestDriver@5774 (fec9a095)] Calling AppiumDriver.getTimeouts() with args: ["fec9a095-b87e-43e3-9a4a-58cb696a3cc5"]
[XCUITestDriver@5774 (fec9a095)] Executing command 'getTimeouts'
[XCUITestDriver@5774 (fec9a095)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/timeouts 304 1 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/timeouts
[HTTP] {}
[XCUITestDriver@5774 (fec9a095)] Calling AppiumDriver.getTimeouts() with args: ["fec9a095-b87e-43e3-9a4a-58cb696a3cc5"]
[XCUITestDriver@5774 (fec9a095)] Executing command 'getTimeouts'
[XCUITestDriver@5774 (fec9a095)] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
[HTTP] <-- GET /wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/timeouts 304 2 ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/timeouts
[HTTP] {}
```

### Environment

- Operating system: MacOS
- Appium server version (output of `appium --version`): 2.2.3
- Appium driver(s) and their version(s): xcuitest@5.7.0 [installed (npm)] , uiautomator2@2.32.3 [installed (npm)]
- Appium plugin(s) and their version(s): n/a
- Node.js version (output of `node --version`):v21.4.0
- `npm` version (output of `npm --version`):10.2.4
- Last component(s) version which did _not_ exhibit the problem: n/a
- Platform and version under test: iOS 17.0
- Real device or emulator/simulator: iOS simulator

### Further Information

Reference issue: https://github.com/appium/appium/issues/19421#issuecomment-1818452504 

I'm facing the exact issue mentioned, “When I use the Appium Inspector, the mobile interface cannot be loaded," in one of the comments in above link. The issue is closed as incomplete.

**Comment by KazuCocoa** [comment]
It was because the `/wd/hub/session/fec9a095-b87e-43e3-9a4a-58cb696a3cc5/source` took a long time, and maybe never responded.

`"appium:settings[pageSourceExcludedAttributes]": ["visible"]` https://appium.github.io/appium-xcuitest-driver/5.12/settings/ or decreasing `"appium:settings[snapshotMaxDepth]"` would help to not calculate expensive attribute or limit the page source depth

**Comment by abishekkulkarni** [comment]
Thank you for your reply. After making the changes as suggested by you, my issue is resolved.
