### ISSUE TITLE
bug:  Swipe in Android devices show 'Not implemented' error

### ISSUE THREAD

**Issue by EduuMaia** [appium/appium#19558]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When executing automation on Android devices and using the 'SWIPE' keyword of the Robot Framework, the following Appium error is returned: "Not implemented."

### Expected Behavior

A swipe should be performed according to the provided coordinates.

### Minimal Reproducible Example

```
Test Swipe   
    Switch To Context    ${NATIVE_CONTEXT}
    Wait Until Keyword Succeeds    10 sec    2 sec    Swipe   0    540    240    2500
```

### Environment

- Operating system: Windows 11
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s):- chromium@1.2.62 [installed (npm)]
  uiautomator2@2.35.0 [installed (npm)]
- Appium plugin(s) and their version(s): NONE
- Node.js version (output of `node --version`): v20.10.0
- `npm` version (output of `npm --version`): 10.2.5
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: ANDROID
- Real device or emulator/simulator: REAL

### Link to Appium Logs

https://gist.github.com/EduuMaia/efa4cbd78c6ac96756dc28c5a419116b

### Further Information

![image](https://github.com/appium/appium/assets/87287705/45035631-2b0b-4faa-807a-3ddb895a4f59)
![image](https://github.com/appium/appium/assets/87287705/0652491b-b282-45a6-9473-6b6a8b813a99)

**Comment by jlipps** [comment]
This is expected. The old touch endpoints are not part of the w3c spec and are no longer supported. Robot Framework needs to be updated to use the correct endpoints.
