### ISSUE TITLE
bug:  After installing the Appium server (dashboard, device farm installation, and Android virtual device installation) on the in-house cloud, when accessing the inspector from another PC, the virtual device screen is not displayed.

### ISSUE THREAD

**Issue by jun-x-nova** [appium/appium#19552]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After installing the Appium server (dashboard, device farm installation, and Android virtual device installation) on the in-house cloud, when accessing the inspector from another PC, the virtual device screen is not displayed.

locally, but a problem occurs when accessing remotely.

![image](https://github.com/appium/appium/assets/153141744/a64301eb-2624-4108-981f-d27b9f749334)

Live video does not load on the Appium dashboard.
![image](https://github.com/appium/appium/assets/153141744/7fbd8853-e771-4104-bb20-5e561ef8b5db)

https://private-user-images.githubusercontent.com/153141744/291522258-418ab445-9e74-4932-913b-31d88790aa94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjA0MTksIm5iZiI6MTcwMzEyMDExOSwicGF0aCI6Ii8xNTMxNDE3NDQvMjkxNTIyMjU4LTQxOGFiNDQ1LTllNzQtNDkzMi05MTNiLTMxZDg4NzkwYWE5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwMDU1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjIxNTExY2MwNGZkOTc2ZmI4ZjkyMThiZTI1NzQxZjc1ZjgxNjg4OGQ4OGNkZGZhNjc1ZmI4MmZiNjUzYjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PJY-_6rWcrh4y4gx6DgIma-A1mf-_EQFuHZ_-ai9V30

### Expected Behavior

It should be displayed properly on the screen, inspector, and dashboard of the connected device. It prints normally locally, but a problem occurs when accessing remotely.

### Minimal Reproducible Example

- Create a Windows instance in your company’s cloud
- Appium server installation
- Install Appium plugin
- Install Appium driver

### Environment

- Operating system: windows 2019 server (cloud instance)
- Appium server version (output of `appium --version`): 2.2.3
- Appium driver(s) and their version(s): uiautomator2@2.34.2
- Appium plugin(s) and their version(s): device-farm@8.4.3, appium-dashboard@v2.0.2
- Node.js version (output of `node --version`): node v20.10.0
- `npm` version (output of `npm --version`): npm 10.2.3
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: emulator/simulator

**Comment by KazuCocoa** [comment]
Do you mean https://github.com/AppiumTestDistribution/appium-device-farm ? Then asking in their github issue first may help

**Comment by mykola-mokhnach** [comment]
Also, without logs there is nothing we could help there

**Comment by jun-x-nova** [comment]
> 또한, 로그아웃하여 우리가 버릴 수 있는 것은 없습니다.
hi, log info
https://private-user-images.githubusercontent.com/153141744/291522258-418ab445-9e74-4932-913b-31d88790aa94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjA0MTksIm5iZiI6MTcwMzEyMDExOSwicGF0aCI6Ii8xNTMxNDE3NDQvMjkxNTIyMjU4LTQxOGFiNDQ1LTllNzQtNDkzMi05MTNiLTMxZDg4NzkwYWE5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwMDU1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjIxNTExY2MwNGZkOTc2ZmI4ZjkyMThiZTI1NzQxZjc1ZjgxNjg4OGQ4OGNkZGZhNjc1ZmI4MmZiNjUzYjFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PJY-_6rWcrh4y4gx6DgIma-A1mf-_EQFuHZ_-ai9V30

**Comment by jun-x-nova** [comment]
> Also, without logs there is nothing we could help there

hi, log info add

**Comment by KazuCocoa** [comment]
I think the attached link is broken

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
