### ISSUE TITLE
unable to recognize each element separately for places in our native app, but able to identify a block consisting of several elements. It works perfectly on iOS 13.3 or earlier, but not on iOS 14.0 or later.

### ISSUE THREAD

**Issue by jenjoy258** [appium/appium#19567]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The automation code works fine on devices with iOS 13.3 and below. Each element is being identified as an individual object, but this didn’t work on later iOS versions. Group of elements identified as a block. This issue is only in a few places in our native app.

### Expected Behavior

Elements should be identified individually

### Minimal Reproducible Example

inspect the elements using Appium inspector

### Environment

- Operating system: iOS 14 and later
- Appium server version (output of `appium --version`):1.17.0
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem: Appium 1.17.0 and iOS13.3
- Platform and version under test: iOS 14.0
- Real device or emulator/simulator: Real device

### Link to Appium Logs

https://gist.github.com/jenjoy258/baa63e4bafc308f80030789f8afcc31b

**Comment by KazuCocoa** [comment]
> Appium server version (output of appium --version):1.17.0

We no longer maintain lower Appium versions.
For iOS 15, please try out the latest XCUITest driver. For iOS 14 and lower, please use XCUITest driver 5.0 or around as the latest supported XCUITest driver versions.
https://appium.github.io/appium-xcuitest-driver/5.12/setup/
