### ISSUE TITLE
[Feat]:Does Appium support automated testing for Harmony App(.hap)?

### ISSUE THREAD

**Issue by ghsy0519** [appium/appium#19564]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KazuCocoa** [comment]
The short answer is no.
I guess it is only for Huawei's  Harmonay OS, Android OS bases still...?
If the `.hap` can work as same as `.apk`, maybe uia2 driver can accept it but I haven't investigated the Harmony OS well.

In case the OS is pretty different from Android for now, and uia2 driver does not work completely, we have no way to achieve the automation. Possibly you or someone interested in building appium driver for the OS could build its own driver https://appium.io/docs/en/2.0/ecosystem/build-drivers/

**Comment by KazuCocoa** [comment]
Hm, it looks like they provide their own device tools, then probably a new driver for the OS would be better than extending uia2 driver somehow (even they work similar, Android base, tech)
https://developer.harmonyos.com/en/docs/documentation/doc-guides/harmonyos_jnit_jsunit-0000001092459608
