### ISSUE TITLE
[Feat]: remove `^` from dependencies in appium package.json?

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#19573]
**Is your feature request related to a problem? Please describe.**

[update]

https://github.com/appium/appium/issues/19573#issuecomment-1867402267

Maybe what i expected when I wrote this issue up was to remove ^ from https://github.com/appium/appium/blob/master/packages/appium/package.json#L63-L68 like other dependencies in the package.json. At least maybe the dependencies have ^ so long, so we haven't locked the version in the appium package

Every release bumps the mini version https://github.com/appium/appium/commit/5c1d20517cfc8773cd5ffb0f8bb996668d71116b#diff-924340cfae1b8cf67b9e29eb9b6afb510ce67089dcb565083c35b11861f2fcd5 

[original]

Current `appium` package does not have any lock file, so every `appium` module installation installs the latest dependencies follows `package.json`. So for example `appium@2.0.0` and `appium@2.3.0`'s base driver versions are the same when we install both versions at the same date. e.g. if i install both version today, both base-driver dependency will be `9.4.4`.

In case a user who wants to lock the `appium` dependency (not individual drivers), should we recommend them to create their own package lock by their end, or would it be nice to add lock file in the `appium` package so that each appium package release will have the release timing's dependencies for sure?

Perhaps... when we keep current behavior, it would be nice to address this dependencies's thing in our documentation since probably users expect `appium@2.0.0` and `appium@2.3.0` have different dependencies, 2.0.0 is old one and 2.3.0 is newer one for the base-driver for example.

**Describe the solution you'd like**

**Describe alternatives you've considered**

Maybe create user's own lock file for the `appium`  module installation. Each driver has their own lock file at the publication time, so it is ok.

**Additional context**

**Comment by KazuCocoa** [comment]
I'm not sure if we could add lock file with `lerna` only for `appium` package, but I wonder that is the best way as us.

Following package.json every installation is also fine for me (so not so strong opinion for the lock itself to be honest), then maybe it would be nice to leave guidance how to manage deps of `appium` package for users...?

(I just thought this deps lock thing when I saw https://github.com/appium/appium/pull/19571)

What do you think...? @mykola-mokhnach @jlipps @eglitise

**Comment by mykola-mokhnach** [comment]
I assume it might be ok as soon as we have a proper mechanism in drivers and plugins to determine their required minimum version. E.g. I have server version 2.0.1 installed and now I want to upgrade one of my drivers. The latest driver version has peerDependency` `appium: ^2.2.0` in package.json.

I expect that on install the server won't let you install this diver and throw an error instead.

Let say we have upgraded the server and now the driver can be installed, but then there are other drivers and plugins, which are old and, probably, need an older server version to work properly. What to do with them in such case?

**Comment by KazuCocoa** [comment]
Maybe what i expected when I wrote this issue up was to remove `^` from https://github.com/appium/appium/blob/master/packages/appium/package.json#L63-L68 like other dependencies in the package.json. At least maybe the dependencies have `^` so long, so we haven't locked the version in the appium package

**Comment by KazuCocoa** [comment]
yea, i recalled such a topic. Maybe we discussed it before, then probably haven't decided strictly then

**Comment by KazuCocoa** [comment]
(update the description and title to address https://github.com/appium/appium/issues/19573#issuecomment-1867402267 instead of full lock with lock file)

**Comment by eglitise** [comment]
Yes, I think removing the `^` from Appium-specific dependencies is the safer way to do it. I would also be in favor of doing the same for drivers, maybe also appium-doctor and any other packages intended for the end user. Dependabot/Renovate will take care of the version bump anyway.
At the same time, it may be worth customizing the title for such dependency bump commits, to reflect the fix/feature coming from the dependency. For this repo, `lerna` already takes care of this (e.g. `doctor` `v2.0.30` only bumped `support` to `v4.1.11`, but it added the changes from `support` in `doctor`'s changelog). I believe driver repos have Dependabot, but it is not configured for automatic merges, so the titles can then still be changed.

**Comment by mykola-mokhnach** [comment]
I would rather then replace `^` with `~` as we still want to get patches

**Comment by KazuCocoa** [comment]
`~` makes sense to me
