### ISSUE TITLE
Failed to create session. A new session could not be created. Details: Appium's losDriver does not support Xcode version 15.0.1. Apple has deprecated UlAutomation. Use the "XCUITest" automationName capability instead

### ISSUE THREAD

**Issue by ShibiKP** [appium/appium#19574]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi Team, 

I have upgrade the Mac machine with latest version and also I have upgraded the Xcode when I try to find the web element on Appium inspector. But I'm getting the error message 
"Failed to create session. A new session could not be created. Details: Appium's losDriver does not support Xcode version 15.0.1. Apple has deprecated UlAutomation. Use the "XCUITest" automationName capability instead"

 

### Expected Behavior

Appium inspector should show the web element of the iOS devices.

### Minimal Reproducible Example

<img width="1106" alt="iOS appium inspector Issue" src="https://github.com/appium/appium/assets/12896310/707cd8bd-af7f-4742-b907-57e21d6bba28">

Capability 
 "appium:DeviceName": "iPhone 15",
  "appium:PlatformVersion": "17.0",
  "platformName": "iOS",
  "appium:BundleId": "App bundled id",
  "appium:app": "path Location",
  "appium:wdaLocalPort": "8100",
  "appium:noReset": true,
  "appium:updatedWDABundleId": "com.tewbie.test.WebDriverAgentRunner"

### Environment

Please find the below details,
MAC OS version :- Sonoma version 14.1.1
iOS devices OS :- iOS 17.1 version 
Xcode:- 15.1 version 
Appium inspector :- 2023.11.1
Appium service GUI version :- v1.22.3

### Further Information

<img width="1106" alt="iOS appium inspector Issue" src="https://github.com/appium/appium/assets/12896310/457e303d-1976-469d-9cb0-a45724861b9f">

**Comment by eglitise** [comment]
>Appium service GUI version :- v1.22.3

Appium Server GUI and Appium 1 are no longer supported. Please upgrade to the command-line version of Appium 2, install the XCUITest driver and add the `"appium:automationName": "XCUITest"` capability to your capability set.

See the [Appium documentation](https://appium.io/docs/en/latest/) and [XCUITest driver documentation](https://appium.github.io/appium-xcuitest-driver/latest/capabilities/) for more details.
