### ISSUE TITLE
disable naive location permission iOS 17 not working 

### ISSUE THREAD

**Issue by asmayonis1** [appium/appium#19583]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to disable native location permission from iOS app on iOS 17 but never worked 
<img width="268" alt="Screenshot 2023-12-25 at 8 58 29 AM" src="https://github.com/appium/appium/assets/87483154/e4fbac02-f702-46b5-9654-bf006b6ea135">

`capabilities.setCapability("locationServicesEnabled", false);
 capabilities.setCapability("locationServicesAuthorized", false);
 capabilities.setCapability("autoAcceptAlerts", false);
 capabilities.setCapability("autoGrantPermissions", true);
 capabilities.setCapability("gpsEnabled", false);
 capabilities.setCapability("noReset", false);
 capabilities.setCapability("fullReset", "false");`
 
 and trying also by element location `driver.setSetting("acceptAlertButtonSelector", "**/XCUIElementTypeButton[label == 'Don't Allow']");`

### Expected Behavior

location should be disabled and app should continue on steps normally

### Minimal Reproducible Example

https://stackoverflow.com/questions/77712762/appium-how-to-disable-native-location-permission-on-ios-17-its-now-working-by
app required location permission to detect delivery area on onboarding screen 

### Environment

- Operating system:
- Appium server version (output of `appium --version`): v2.2.2
- Appium driver(s) and their version(s): xcuitest@5.11.0 (automationName 'XCUITest')
- Appium plugin(s) and their version(s):  uiautomator2@2.34.1 (automationName 'UiAutomator2')
- Node.js version (output of `node --version`):  v20.10.0
- `npm` version (output of `npm --version`): 10.2.3
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: simulator iPhone 15 pro

### Link to Appium Logs

"https://gist.github.com/asmayonis1/4ca76c9ac8937486b522bca6c4d1ce40.js"

**Comment by eglitise** [comment]
All Appium-specific capabilities require the `appium:` prefix. For example:
```
capabilities.setCapability("appium:noReset", false);
```
Please refer to the [XCUITest documentation ](https://appium.github.io/appium-xcuitest-driver/latest/capabilities/) for a list of valid capabilities. You can probably try something like `appium:autoDismissAlerts`.

**Comment by KazuCocoa** [comment]
> and trying also by element location driver.setSetting("acceptAlertButtonSelector", "**/XCUIElementTypeButton[label == 'Don't Allow']");

Should it escape to be `**/XCUIElementTypeButton[label == "Don't Allow"]`?


https://github.com/appium/appium-xcuitest-driver/blob/master/CHANGELOG.md#5118-2023-12-04 would also help to change permission, which should be xcuitest driver 5.11.8

**Comment by asmayonis1** [comment]
@eglitise  tried to update capabilities made no difference on disable location access

**Comment by asmayonis1** [comment]
@KazuCocoa doesn't affect at all, also tried detect location element by xpath failed to disable

**Comment by asmayonis1** [comment]
<img width="740" alt="Screenshot 2023-12-27 at 11 33 26 PM" src="https://github.com/appium/appium/assets/87483154/523ee727-dd5f-41ba-810e-0792dc904b95">
![Uploading Screenshot 2023-12-27 at 11.33.56 PM.png…]()

**Comment by eglitise** [comment]
Your screenshot has a typo, it's `autoDismissAlerts`, not `autoDissmissAlerts`. I would advise to check the Appium log upon creating a new session - the driver will identify and print out the capabilities it does not recognise, so you can correct or remove them from your test.

**Comment by KazuCocoa** [comment]
How did you set the location service with xcuitest driver 5.12.2?

```ruby
> driver.execute_script 'mobile: setPermission', {bundleId: 'com.apple.Maps', access: {location: "no"}}
> driver.activate_app 'com.apple.Maps'
```

Then:

![Screenshot 2023-12-27 at 6 19 29 PM](https://github.com/appium/appium/assets/5511591/6278d567-fa3d-4e26-962b-2ee0d81cce78)


For the class chain, below may work:

```ruby
driver.find_element :class_chain, '**/XCUIElementTypeButton[`label=="Don’t Allow"`]'
```

so

```ruby
driver.settings.update({acceptAlertButtonSelector: '**/XCUIElementTypeButton[`label=="Don’t Allow"`]'})
```

https://github.com/facebookarchive/WebDriverAgent/wiki/Class-Chain-Queries-Construction-Rules
(the link is from `acceptAlertButtonSelector` in https://appium.github.io/appium-xcuitest-driver/5.12/settings/ . It looks like the `Don’t` 's `'` is not `'` in the keyboard according to the page source)

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by OMK903** [comment]
How to enable location permissison in ios  xcuitest driver
