### ISSUE TITLE
[Feat]: Support androidx.test.uiautomator:uiautomator:2.3.0

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#19597]
I'll keep linking issues to this main issue for future 2.3.0 investigation

`androidx.test.uiautomator:uiautomator` 2.3.0 includes a screen size fix in the lib. 
https://github.com/appium/appium-uiautomator2-server/issues/490

The lib is still beta01 on Dec, 2023, thus probably we should wait for more to be a stable release, but we could start fixing known issues with that.

For example https://github.com/appium/appium-uiautomator2-server/pull/588 was for the upcoming 2.3.0 update.

## What we should do

- Set `compileSdk` version to `34`: https://github.com/appium/appium-uiautomator2-server/pull/587/
    - targetSdk version is not necessary but probably it would be nice to update both to keep latest version compatibility
- Update `androidx.test.uiautomator:uiautomator` in the uia2 server https://github.com/appium/appium-uiautomator2-server
- Update `UiObject2 toUiObject2(@Nullable Object selector, @Nullable AccessibilityNodeInfo node)`
    - The `selector` and `node` should not be null to the method's `(UiObject2) uiObject2Constructor.newInstance(constructorParams);`
        - https://github.com/appium/appium-uiautomator2-server/pull/590
        - https://github.com/appium/appium-uiautomator2-server/pull/591
    - https://github.com/appium/appium-uiautomator2-server/pull/589 is for the `node` case

## Current status
- UIA2 driver `2.38.0` has the beta01

**Comment by KazuCocoa** [comment]
UIA2 driver 2.38.0 has the library beta01. Let me keep this issue open until the lib's stable release

**Comment by Comeodore** [comment]
@KazuCocoa @mykola-mokhnach Thank you very much for your work, guys!

**Comment by KazuCocoa** [comment]
3.0.1 has the stable release of 2.3.0. We didn't see any changes from the previous rc, so maybe it does not break anything
