### ISSUE TITLE
[Feat]: FullReset capability only for when a test fails

### ISSUE THREAD

**Issue by tking16** [appium/appium#19590]
Sometimes tests fail due to something like a native dialog appearing, in the case of iOS, this dialog won't go away when the next tests begins so all other tests will just fail immediately. Only options are to reset the device or manually click away the dialog. Frameworks such as Playwright have the option to take screenshots and video only on failures, would be good to be able to set certain capabilities only when a test fails in Appium too

**Comment by mykola-mokhnach** [comment]
Appium drivers are designed to be general-purpose entities. They must not know what "fail" or "pass" is. This is the job of the higher layer. 
You may also propose a plugin that implements such functionality.
