### ISSUE TITLE
Do-It-Yourself with npm only works if the appium dependency refers to a static version

### ISSUE THREAD

**Issue by laurence79** [appium/appium#19601]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The behaviour described in [Do-It-Yourself with npm](https://appium.io/docs/en/2.0/guides/managing-exts/) only works if the dependency in the package.json refers to a static version.

This works:
```json
{
  "dependencies": {
    "appium": "2.3.0"
  }
}
```

This does not:
```json
{
  "dependencies": {
    "appium": "^2.3.0"
  }
}
```

### Expected Behavior

Do-It-Yourself works with any supported npm dependency version specifier

### Minimal Reproducible Example

```sh
npm init
npm i appium appium-xcuitest-driver
npx appium
```
> [Appium] No drivers have been installed in /Users/xxxx/.appium. Use the "appium driver" command to install the one(s) you want to use.
```sh
# changes dependencies.appium from "^2.3.0" to "2.3.0"
npm i --save-exact appium

npx appium
```
> [Appium] The autodetected Appium home path: /Users/xxx/Development/appium-diy-repro
> [Appium] Attempting to load driver xcuitest...

### Environment

- Operating system: macOS 14.2.1
- Appium server version (output of `appium --version`): 2.3.0
- Appium driver(s) and their version(s): xcuitest 5.12.2
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): 18.19.0
- `npm` version (output of `npm --version`): 10.2.3
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

Issue seems to be [here](https://github.com/appium/appium/blob/5070a3473974a77121fb5bf7fd904f10d2bd133f/packages/support/lib/env.js#L61) with `semver.clean`

**Comment by jlipps** [comment]
@mykola-mokhnach is this a result of your recent changes?

**Comment by mykola-mokhnach** [comment]
Thanks for the report. This seems to be a regression issue. https://github.com/appium/appium/pull/19602 should do the job
