### ISSUE TITLE
bug: activateApp after terminateApp does not respond to driver actions

### ISSUE THREAD

**Issue by MagdelineNg** [appium/appium#19614]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to launch 2 instances of an app, terminate one instance, and then relaunch the instance. When I relaunch the instance using activateApp, the driver does not execute any action until I manually click on my screen (My guess is the instance is relaunched in the foreground?)

What should the fullreset and noreset options be?

### Expected Behavior

The driver should automatically send "Hello world" to TextEdit after relaunching the app instance.

### Minimal Reproducible Example

```
import time
import subprocess
import subprocess

from appium import webdriver as appium_webdriver
from appium.options.mac import Mac2Options
from appium.webdriver.appium_service import AppiumService
from appium.webdriver.common.appiumby import AppiumBy

APPIUM_PORT = '4723'
APPIUM_HOST = '127.0.0.1'
BUNDLE_ID = "com.apple.TextEdit"
APPLICATION_NAME = "TextEdit"

options = Mac2Options()
options.bundle_id = BUNDLE_ID
options.show_server_logs = True
options.system_port = 10101
options.no_reset = False
options.full_reset = True
options.wait_for_quiescence = False

appium_service = AppiumService()
appium_service.start()

driver = appium_webdriver.Remote(f"http://{APPIUM_HOST}:{APPIUM_PORT}", options=options)

subprocess.run(["open", "-na", APPLICATION_NAME]) 

time.sleep(3)
driver.execute_script('macos: terminateApp', {'bundleId': BUNDLE_ID})
time.sleep(3)

driver.execute_script('macos: launchApp', {'bundleId': BUNDLE_ID})

#Have to manually click on the app to trigger driver to continue the flow below
edit_field = driver.find_element(by=AppiumBy.CLASS_NAME, value='XCUIElementTypeTextView')
edit_field.send_keys('hello world')
```

### Environment

- Operating system: MacOS
- Appium server version (output of `appium --version`): 2.2.3
- Appium driver(s) and their version(s): Mac2 Driver
- Real device or emulator/simulator: simulator

**Comment by mykola-mokhnach** [comment]
The driver is simply [proxying](https://github.com/appium/appium-mac2-driver/blob/48906b685ca8f594fc129b827e8c420c4ee4e1d7/WebDriverAgentMac/WebDriverAgentLib/Routing/FBSession.m#L88) commands to Apple XCTest. Consider asking at Apple forums.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
