### ISSUE TITLE
bug: ENOTEMPTY: directory not empty, rename '/Users/xxxx/.appium/node_modules/appium' -> '/Users/xxxx/.appium/node_modules/.appium-7XLjeons'". 

### ISSUE THREAD

**Issue by kkallu2** [appium/appium#19619]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

    "summary": "ENOTEMPTY: directory not empty, rename '/Users/pawan/.appium/node_modules/appium' -> '/Users/pawan/.appium/node_modules/.appium-7XLjeons'"

### Expected Behavior

it should install appium drivers successfully

### Minimal Reproducible Example

install latest version of appium in apple m2 air
now try to install drivers using appium driver install uiautomator2 or any other driver

### Environment

- Operating system: Apple M2 air
- Appium server version (output of `appium --version`): Appium 2.4.1
- Appium driver(s) and their version(s): Not able to install
- Appium plugin(s) and their version(s): NA
- Node.js version (output of `node --version`):Node version 20 plus im using

### Further Information

<img width="1470" alt="Screenshot 2024-01-06 at 4 23 54 PM" src="https://github.com/appium/appium/assets/64024175/9d1edff4-e7f2-4a92-8fac-b9ef19096013">

**Comment by kkallu2** [comment]
@KazuCocoa pls help

**Comment by mykola-mokhnach** [comment]
Try to delete the `/Users/pawan/.appium/node_modules/appium` folder manually and then repeat the install

**Comment by kkallu2** [comment]
thank you very much @mykola-mokhnach  ....it worked...
