### ISSUE TITLE
How to identifiy all element handlers in wechat miniapp through Appium APIs

### ISSUE THREAD

**Issue by codingman-aiwass** [appium/appium#19624]
Now I have to identify all clickable elements on a wechat miniapp page. In the Appium Inspector, we can click the `Show Element Handles` and then it will circle all the clickable elements on this page. I wonder whether we can do the same thing by appium-python-client. If there are some APIs which is able to return these clickable elements in appium. If not, is there any relative technologies can do so. Thank you!
<img width="263" alt="screenshot of appium inspector" src="https://github.com/appium/appium/assets/65451457/e2d51428-1cb6-4050-b50b-971498b7da0d">

**Comment by mykola-mokhnach** [comment]
please use Appium forum to ask questions

**Comment by codingman-aiwass** [comment]
Thank you! I'll go to forum insead.

**Comment by jlipps** [comment]
To answer your question in case no one on the forums knows, no, this functionality is only available in the inspector. You could reproduce its logic on the client side but you would need to read the code and do so yourself.
