### ISSUE TITLE
Scroll Into element in a Table

### ISSUE THREAD

**Issue by dsa45632** [appium/appium#19632]
I am trying to scroll into element, in order to do that I need to scroll on the table to find the element and then hover on the element but when https://github.com/appium/appium-windows-driver?tab=readme-ov-file#windows-hover I use this hover feature as far as I understand there needs to be start and end point when I pass those it only hover on the element location but it needs to scroll on the table to make the element visible first is there any way I could just move on the element or hover? or scroll on the table ?
this only does hover to the element location not hover on the element
windowsDriver.ExecuteScript("windows: hover", new Dictionary<string, object>
{
{ "startX",0 },
{ "startY", 0},
{ "endX",startElement.Location.X },
{ "endY", startElement.Location.Y }
});
any suggestions will be thankful.

**Comment by mykola-mokhnach** [comment]
> this only does hover to the element location not hover on the element

Are you sure you understand the purpose of the API? "hover" means it just puts the cursor over the given area/element without doing anything else. 

Please use Appium forum to ask questions.
