### ISSUE TITLE
Caching appears to be partially broken since uia2 server 5.15.0

### ISSUE THREAD

**Issue by eglitise** [appium/appium#19638]
(will add more environment details later)

After updating to Appium `2.4.1` + UiAutomator2 driver `2.40.0`, I started seeing some strange test failures: some elements that were previously being found, were no longer being identified.
This is a fairly rare occurrence, and appears to affect Jetpack Compose structures, where, when the children of the compose root element are changed, the new children cannot be found. The app source does still contain them, and the Inspector can also identify them (although after one or more additional refreshes), so it appears that something may be wrong with caching.
I tested earlier UiA2 driver versions, and discovered that the problem first manifested in UiA2 server `5.15.0` (the previous `5.14.0`, which I installed manually, was still fine).

I could reproduce the problem on devices with Android 12 and 14, but not Android 9.
I also checked the Appium logs, but at the very least on the default logging level, there was nothing unusual, just a 404 response due to the element not being found. So some additional logging is probably needed.
Will investigate more...

**Comment by KazuCocoa** [comment]
I'm not sure what kind of logs helps to check cache relevant behavior, but what about adb logcat...?

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-uiautomator2-server/pull/597

**Comment by mykola-mokhnach** [comment]
UIA2 driver 2.40.2 should have the patch

**Comment by eglitise** [comment]
Thanks, will test this on all of my devices tomorrow.

**Comment by eglitise** [comment]
I ran some tests on 3 devices (Android 9, 12 and 14) using 6 different UiA2 driver/server versions. Each test was run 5 times just to be sure. Here's the results:
| Device | Driver 2.36.0 (Server 5.13.0) | Driver 2.37.0 (Server 5.15.0) | Driver 2.37.1 (Server 5.15.3) | Driver 2.38.0 (Server 6.0.0) | Driver 2.40.1 (Server 6.0.2) | Driver 2.40.2 (Server 6.0.3) |
| --- | --- |--- | --- |--- | --- |--- |
| Android 14 | 5/5 pass | 0/5 pass | 0/5 pass | 0/5 pass | 0/5 pass | 5/5 pass |
| Android 12 | 5/5 pass | 0/5 pass | 0/5 pass | 0/5 pass | 0/5 pass | 5/5 pass |
| Android 9 | 5/5 pass | 5/5 pass | 5/5 pass | 5/5 pass | 5/5 pass | 5/5 pass |

I think it's safe to say that UiA2 driver 2.40.2 + server 6.0.3 fixed the problem 👌 Thanks!

**Comment by KazuCocoa** [comment]
Thank you for the tests. Not clear why Android 12 was affected even the different method was only for api level 33+, but glad to hear that
