### ISSUE TITLE
bug: <there is no windows driver in "appium driver list">

### ISSUE THREAD

**Issue by pppppino** [appium/appium#19644]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in cmd, run `appium  driver list`,

![image](https://github.com/appium/appium/assets/129264630/56c1b726-6a23-4e4b-8b48-a5ced2f88f3f)

### Expected Behavior

expect for windows driver, but not found

### Minimal Reproducible Example

in cmd, run `appium  driver list`,

### Environment

- Operating system:
- Appium server version (output of `appium --version`):2.3.0
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): 10.2.3

- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
This is expected: and is documented: https://github.com/appium/appium-windows-driver#appium-windows-driver
