### ISSUE TITLE
bug: TypeError: Unexpected External value as type specifier, expected string or type

### ISSUE THREAD

**Issue by Auto81** [appium/appium#19659]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Get the error on the attached gist. Highlights i can see are potentially a case sensitive name somewhere? windows vs Windows

At start of log
```
[Appium] Could not load driver 'windows', so it will not be available. Error in loading the driver was: Unexpected External value as type specifier, expected string or type
[Appium] TypeError: Unexpected External value as type specifier, expected string or type
```

At end of log
```
[Appium] Available drivers:
[Appium]   - windows@2.12.15 (automationName 'Windows')
```

### Expected Behavior

Driver to load as previous versions

### Minimal Reproducible Example

Have windows driver installed
Run `appium server`

### Environment

- Operating system: Windows 10
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s): windows@2.12.15 [installed (npm)]
- Appium plugin(s) and their version(s): images@3.0.1 [installed (npm)]
- Node.js version (output of `node --version`): v21.6.0
- `npm` version (output of `npm --version`): 10.3.0
- Last component(s) version which did _not_ exhibit the problem: unknown previous version
- Platform and version under test: Appium Server

### Link to Appium Logs

https://gist.github.com/Auto81/5c1e43e120a93810321e9dedde34b4bf

**Comment by jlipps** [comment]
If you go back to Nodejs 18, is the problem still there?

**Comment by mykola-mokhnach** [comment]
I can successfully load the driver using Node 21.5.0. It might be a bug in Node.js itself. Try to use the LTS version of it instead

**Comment by Auto81** [comment]
Node LTS v20.11.0 seems to make it happy, thanks both
