### ISSUE TITLE
bug: `snapshotMaxDepth` setting is not working on iOS

### ISSUE THREAD

**Issue by Dor-bl** [appium/appium#19661]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When passing `snapshotMaxDepth` setting with value 20, the server still looks for all nested elements and is not limited to the max depth 

### Expected Behavior

Nested elements should be limited to the value been passed to the server.
in this case 20.

`Changes the value of maximum depth for traversing elements source tree. It may help to prevent out of memory or timeout errors while getting the elements source tree, but it might restrict the depth of source tree. Please consider restricting this value if you observed an error like Timed out snapshotting com.apple.testmanagerd... message or Cannot get 'xml' source of the current application in your Appium log since they are possibly timeout related. A part of elements source tree might be lost if the value was too small. Defaults to 50`

### Minimal Reproducible Example

Start a session with the below JSON, using Appium inspector i.e.
```

{
  "platformName": "iOS",
  "appium:automationName": "XCUITest",
  "appium:deviceName": "iPhone 14 Plus",
  "appium:platformVersion": "16.4",
  "appium:app": "****",
  "appium:newCommandTimeout": "2000",
  "appium:options": {
    "autoGrantPermissions": "true",
    "autoAcceptAlerts": "true"
  },
  "appium:appPackage": "com.scr.sensetime",
  "showXcodeLog": true,
  "noReset": true,
  "appium:settings[snapshotMaxDepth]": 20
}
```

### Environment

- Operating system: macOS
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s):XCUITestDriver (v5.12.1
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):v20.9.0
- `npm` version (output of `npm --version`):10.1.0
- Last component(s) version which did _not_ exhibit the problem: never did
- Platform and version under test: iOS 16.4 
- Real device or emulator/simulator: Simulator

### Link to Appium Logs

https://gist.github.com/Dor-bl/59bb8c0b1eeb1f8250e9face19038106

### Further Information

https://appium.github.io/appium-xcuitest-driver/5.14/settings/
https://github.com/appium/appium/issues/18085

**Comment by mykola-mokhnach** [comment]
> still looks for all nested elements and is not limited to the max depth

Could you please describe in details how you check that.
Maybe the above doc could be improved as we only fetch snapshots for xpath lookup and to retrieve the page source. Other locators use native XCTest APIs and they are not affected by this limit

**Comment by Dor-bl** [comment]
I pass the setting to Appium inspector and open the page where I have around 400 `//XCUIElementTypeTable/XCUIElementTypeCell`, From what I understood it should limit that number to 20 locatable Elements 
![image](https://github.com/appium/appium/assets/59066376/aea41366-40eb-4b34-aad8-8e5436576f3b)

btw why don't I see this setting when the session starts? maybe that's the issue?
Although, it's been passed in the POST/session call:

```
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"iOS","appium:automationName":"XCUITest","appium:deviceName":"iPhone 14 Plus","appium:platformVersion":"16.4","appium:app":"/Users/blayzer/Downloads/F1MobileiOS.app","appium:appActivity":"crc64312edd13c4752188.SplashScreen","appium:newCommandTimeout":"2000","appium:options":{"autoGrantPermissions":"true","autoAcceptAlerts":"true"},"appium:appPackage":"com.scr.sensetime","appium:showXcodeLog":true,"appium:noReset":true,"appium:settings":{"snapshotMaxDepth":20},"appium:includeSafariInWebviews":true,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"iOS","appium:automationName":"XCUITest","appium:deviceName":"iPhone 14 Plus","appium:platformVersion":"16.4","appium:app":"/Users/blayzer/Downloads/F1MobileiOS.app","appium:appActivity":"crc64312edd13c4752188.SplashScreen","appium:newCommandTimeout":"2000","appium:options":{"autoGrantPermissions":"true","autoAcceptAlerts":"true"},"appium:appPackage":"com.scr.sensetime","ap...
[AppiumDriver@2e84] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","appium:automationName":"XCUITest","appium:deviceName":"iPhone 14 Plus","appium:platformVersion":"16.4","appium:app":"/Users/blayzer/Downloads/F1MobileiOS.app","appium:appActivity":"crc64312edd13c4752188.SplashScreen","appium:newCommandTimeout":"2000","appium:options":{"autoGrantPermissions":"true","autoAcceptAlerts":"true"},"appium:appPackage":"com.scr.sensetime","appium:showXcodeLog":true,"appium:noReset":true,"appium:settings":{"snapshotMaxDepth":20},"appium:includeSafariInWebviews":true,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"iOS","appium:automationName":"XCUITest","appium:deviceName":"iPhone 14 Plus","appium:platformVersion":"16.4","appium:app":"/Users/blayzer/Downloads/F1MobileiOS.app","appium:appActivity":"crc64312edd13c4752188.SplashScreen","appium:newCommandTimeout":"2000","appium:options":{"autoGrantPermissions":"true","autoAcceptAlerts":"true"},"appium:appPackage":"com.scr.sensetime","appium:showXcodeLog":true,"appium:noReset":true,"appi...
```

```
XCUITestDriver@5f4b] Creating session with W3C capabilities: {
[XCUITestDriver@5f4b]   "alwaysMatch": {
[XCUITestDriver@5f4b]     "platformName": "iOS",
[XCUITestDriver@5f4b]     "appium:automationName": "XCUITest",
[XCUITestDriver@5f4b]     "appium:deviceName": "iPhone 14 Plus",
[XCUITestDriver@5f4b]     "appium:platformVersion": "16.4",
[XCUITestDriver@5f4b]     "appium:app": "/Users/blayzer/Downloads/F1MobileiOS.app",
[XCUITestDriver@5f4b]     "appium:appActivity": "crc64312edd13c4752188.SplashScreen",
[XCUITestDriver@5f4b]     "appium:newCommandTimeout": "2000",
[XCUITestDriver@5f4b]     "appium:appPackage": "com.scr.sensetime",
[XCUITestDriver@5f4b]     "appium:showXcodeLog": true,
[XCUITestDriver@5f4b]     "appium:noReset": true,
[XCUITestDriver@5f4b]     "appium:includeSafariInWebviews": true,
[XCUITestDriver@5f4b]     "appium:connectHardwareKeyboard": true,
[XCUITestDriver@5f4b]     "appium:autoGrantPermissions": "true",
[XCUITestDriver@5f4b]     "appium:autoAcceptAlerts": "true"
[XCUITestDriver@5f4b]   },
[XCUITestDriver@5f4b]   "firstMatch": [
[XCUITestDriver@5f4b]     {}
[XCUITestDriver@5f4b]   ]
[XCUITestDriver@5f4b] }
```

**Comment by amedvedjev** [comment]
`From what I understood it should limit that number to 20 locatable Elements` - no
snapshotMaxDepth means that path to element limited 20 elements from root. e.g. below depth = 5
```
<XCUIElementTypeApplication type="XCUIElementTypeApplication" enabled="true" visible="true" x="0" y="0" width="414" height="896" name="xxx" label="xxx">
    <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" visible="true" x="0" y="0" width="414" height="896">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="414" height="896" name="generated_UITransitionView">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="414" height="896" name="generated_UIDropShadowView">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" visible="true" x="0" y="0" width="414" height="896">
```

**Comment by Dor-bl** [comment]
And there is a way to limit the child elements somehow so it won't load the entire tree?
regardless, why I do not see the setting I passed in the server logs

**Comment by eglitise** [comment]
> And there is a way to limit the child elements somehow so it won't load the entire tree?

I don't think there is. It probably also wouldn't be straightforward to implement (which elements should be kept, and which should be removed?)

> regardless, why I do not see the setting I passed in the server logs

Parsed settings seem to be logged in a separate message (which sorta makes, sense since they are not capabilities). In this case, on line 120:

> [AppiumDriver@7ba3] Applying the initial values to Appium settings parsed from W3C caps: {"snapshotMaxDepth":20}

**Comment by Dor-bl** [comment]
I assume the first 20 child elements of the parent element?

**Comment by mykola-mokhnach** [comment]
@amedvedjev provided the correct answer above. 20 is the DEPTH, which means the nesting level of the XML tree must not be greater than 20. What you are talking about is the amount of sibling elements and we don't control this parameter.

Closed as not an issue

**Comment by Dor-bl** [comment]
@mykola-mokhnach Is it possible to implement? 
Should I open a feat request on the XCUITEST driver side?
