### ISSUE TITLE
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation target package: io.appium.uiautomator2.server

### ISSUE THREAD

**Issue by timdau** [appium/appium#19666]
Appium is version 2.4.1.  uiautomator2 is version 2.42.1

I am trying to run appium in two different android accounts on the same real device. It works with user `0` but it fails with any other user.  It seems like it verifies the uiautomator2 is installed but its not running for that account.  I have attached two logs.  One is when it can't find the instrumentation package.  The second one is even weirder, it thinks everything is working fine but my app never gets run.

```
# adb -s priapos:5555 shell pm list users
Users:
	UserInfo{0:priapos:c13} running
	UserInfo{14:zephyr:410} running
```
 When I run my python test script with user 0
```
# adb -s priapos:5555 shell am switch-user 0
# adb -s priapos:5555 shell am get-current-user
0
```
the test passes.

When I run my python test script with user 14
```
# adb -s priapos:5555 shell am switch-user 14
# adb -s priapos:5555 shell am get-current-user
14
```
It fails.

Here are my capabilities
```
  options.load_capabilities({
    "appium:deviceName": "Android",
    "appium:appPackage": "com.mypkg.global",
    "appium:language": "en",
    "appium:locale": "US",
    "platformName": "Android",
    "appium:automationName": "UiAutomator2",
    "appium:appActivity": "com.mypkg.global.MyMainPlayerActivity",
    "appium:udid": f"{node_name}:5555",
    "appium:noReset": True,
    "appium:autoLaunch": True,
    "appium:dontStopAppOnReset": True,
    "appium:newCommandTimeout": 360000
  })
```
I tried running `appium driver run uiautomator2 reset` and it ran successfully but without impacting things.

And finally here are the logs. 
[logfile.txt](https://github.com/appium/appium-uiautomator2-server/files/13958937/logfile.txt)
[logfile2.txt](https://github.com/appium/appium-uiautomator2-server/files/13958969/logfile2.txt)

**Comment by KazuCocoa** [comment]
Did you try out `appium:userProfile`?
https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#other

**Comment by mykola-mokhnach** [comment]
The multi user testing strategy has never been verified/tested using UIA2, at least on our side. I would be surprised if something like that it just works by default. Maybe we could label it as a feature request.

**Comment by timdau** [comment]
> Did you try out `appium:userProfile`? https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#other

So I did try that and I couldn't get it to work but I think it was a misunderstanding on my part.  I *think* it is actually working now.  Part of my misunderstanding was that I thought appium would switch the user, so I kind of gave up on that capability.  You have to manually switch the user AND use the userProfile cap.

I also got confused because I figured userProfile would allow appium to distinguish between the android accounts, but it doesn't look like there is.  So the app can only be running once per device.

For the record, here is what I am doing:
```
adb -s priapos:5555 shell am force-stop com.mypkg.global #The app can only be running once at a time per device
adb -s priapos:5555 shell am switch-user $USER
adb -s priapos:5555 shell am get-current-user
```

And here are is my configuration where android_user = $USER above.  In my case `0` or `14`.
```
  options.load_capabilities({
    "appium:deviceName": "Android",
    "appium:appPackage": "com.mypkg.global",
    "appium:language": "en",
    "appium:locale": "US",
    "platformName": "Android",
    "appium:automationName": "UiAutomator2",
    "appium:appActivity": "com.mypkg.global.MyMainPlayerActivity",
    "appium:udid": f"{node_name}:5555",
    "appium:userProfile": android_user,
    "appium:noReset": True,
    "appium:autoLaunch": True,
    "appium:dontStopAppOnReset": True,
    "appium:newCommandTimeout": 360000
  })
```
