### ISSUE TITLE
AppiumBy method is taking more time to identify the element in popup

### ISSUE THREAD

**Issue by suhas2404** [appium/appium#19667]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

AppiumBy method is taking more time to identify the element in popup like more than 15 sec 

### Expected Behavior

AppiumBy method should be able to identify the element within max of 5 sec 

### Minimal Reproducible Example

AppiumBy method should be able to identify the element within max of 5 sec 

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly and provide the requested information

**Comment by mykola-mokhnach** [comment]
Closed because of no response
