### ISSUE TITLE
bug: `mobile: getContexts` returns incorrect pages for multiple webviews on Node.js v19

### ISSUE THREAD

**Issue by yaumu3** [appium/appium#19678]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When

- Appium server is running on Node.js v19
- There are 2 webview apps running and pages are open

-> one of webview's pages are incorrectly retrieved and seems overwritten by data from the other webview.

For example,

- webview app A with a page A1
- webview app B with a page B1

App B's `pages` is identical to App A's.

```
[
  {
    ...
    "pages": [
      <-- data from page A1 -->
    ],
    "webviewName": "WEBVIEW_A"
  },
  {
    ...
    "pages": [
      <-- data from page A1 -->
    ],
    "webviewName": "WEBVIEW_B"
  }
]
```

### Expected Behavior

The retrieved pages should correspond to the running app.

```
[
  {
    ...
    "pages": [
      <-- data from page A1 -->
    ],
    "webviewName": "WEBVIEW_A"
  },
  {
    ...
    "pages": [
      <-- data from page B1 -->
    ],
    "webviewName": "WEBVIEW_B"
  }
]
```

### Minimal Reproducible Example

1. Start android emulator
2. Start appium server on Node.js v19
3. Start appium session with the emulator
4. Open a webview app (e.g. Microsoft Edge)
5. Go to a website A
6. Background the app
5. Open chrome browser
7. Go to a website B
8. Execute `mobile: getContexts` on the session
9. Verify the retrieved pages are same for both webviews

- [result_node_v19.0.0.json](https://github.com/appium/appium/files/13983871/result_node_v19.0.0.json) (bug response)
- [result_node_v18.15.0.json](https://github.com/appium/appium/files/13983872/result_node_v18.15.0.json) (expected response)

### Environment

- Operating system: macOS 14.2.1
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s): uiautomator2@2.42.1
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v19.0.0
- `npm` version (output of `npm --version`): 8.19.2
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Android 13
- Real device or emulator/simulator: Emulator

### Further Information

[appium_log_excerpt.log](https://github.com/appium/appium/files/13983903/appium_log_excerpt.log)

As [Node.js v19 enabled HTTP(S)/1.1 KeepAlive by default](https://nodejs.org/en/blog/announcements/v19-release-announce#https11-keepalive-by-default), we may have to explicitly disable keep-alive using feature like https://github.com/axios/axios/issues/1846.

**Comment by mykola-mokhnach** [comment]
have you actually tried to disable keepAlive locally in the code? Did it work for the above scenario?

**Comment by yaumu3** [comment]
> have you actually tried to disable keepAlive locally in the code?

Yes, I have tried it by setting `httpAgent: new http.Agent({ keepAlive: false })` to [axios Request Config](https://axios-http.com/docs/req_config) at the followings. 

- https://github.com/appium/appium-android-driver/blob/7a9f6540ec010c73e08034fbbba73b8454bed5bf/lib/helpers/webview.ts#L357-L360
- https://github.com/appium/appium-android-driver/blob/7a9f6540ec010c73e08034fbbba73b8454bed5bf/lib/helpers/webview.ts#L367-L370

> Did it work for the above scenario?

This tweak resolved this issue.

**Comment by mykola-mokhnach** [comment]
this is great. Would you mind creating a PR?

**Comment by yaumu3** [comment]
Sure! I'd pleased to.
