### ISSUE TITLE
bug: [XCUITest-driver] Key Down action  must have a closing Key Up successor in

### ISSUE THREAD

**Issue by wswebcreation** [appium/appium#19670]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sending key actions according to the W3C ([simple](https://github.com/jlipps/simple-wd-spec?tab=readme-ov-file#perform-actions)) spec with a `pause` is breaking the implementation for iOS, but not for Android

### Expected Behavior

Pauses are working as expected in the keys implementation for iOS

### Minimal Reproducible Example

This is with WebdriverIO, but can be done with all other languages

# Failing
```ts 
            await driver.performActions(
                [
                    {
                        'id': 'action1',
                        'type': 'key',
                        'actions': [
                            {
                                'type': 'keyDown',
                                'value': '3'
                            },
                            {
                                'type': 'pause',
                                'duration': 10
                            },
                            {
                                'type': 'keyUp',
                                'value': '3'
                            }
                        ]
                    }
                ]
            )
```

# Works
```ts 
            await driver.performActions(
                [
                    {
                        'id': 'action1',
                        'type': 'key',
                        'actions': [
                            {
                                'type': 'keyDown',
                                'value': '3'
                            },
                            {
                                'type': 'keyUp',
                                'value': '3'
                            }
                        ]
                    }
                ]
            )
```

### Environment

- Operating system: MacOS 14.2
- Appium server version (output of `appium --version`): `v2.4.1 (REV bab86d5de571015b63fd8fc30b47bbe072a1290e)`
- Appium driver(s) and their version(s): `xcuitest@5.13.2 (automationName 'XCUITest')`
- Appium plugin(s) and their version(s): -
- Node.js version (output of `node --version`): `v18.19.0`
- `npm` version (output of `npm --version`): `10.2.3`
- Last component(s) version which did _not_ exhibit the problem: not
- Platform and version under test: iOS 17.2
- Real device or emulator/simulator: Sims

```logs
Welcome to Appium v2.4.1 (REV bab86d5de571015b63fd8fc30b47bbe072a1290e)
Available drivers:
  - uiautomator2@2.41.0 (automationName 'UiAutomator2')
  - xcuitest@5.13.2 (automationName 'XCUITest')
  - espresso@2.32.2 (automationName 'Espresso')
  - flutter@2.3.0 (automationName 'Flutter')
```

### Further Information

[appium.failing.log](https://github.com/appium/appium/files/13963393/appium.failing.log)
[appium.succeeds.log](https://github.com/appium/appium/files/13963394/appium.succeeds.log)

**Comment by mykola-mokhnach** [comment]
It was designed like that from the very beginning. XCTest API only allows to send keypresses (e.g. keydown+keyup). There is no way to "split" them

**Comment by wswebcreation** [comment]
I'll close this one then, fixed in WDIO, see [this](https://github.com/webdriverio/webdriverio/pull/12040) PR

And also great to see you, been doing some Appium stuff lately for WDIO

**Comment by jlipps** [comment]
We could provide a helpful error message to the user if they provide a pause action? Something like `Pause between keypresses is not supported on this platform`. Or simply ignore the pause, and log a warning?

**Comment by wswebcreation** [comment]
Depends on what you guys want to do, according to the specs it should work, if the driver doesn't support it a filter + warning might be the best
