### ISSUE TITLE
bug: wrong/missing warnings for unmet peer dependency (older server + newer extension)

### ISSUE THREAD

**Issue by eglitise** [appium/appium#19671]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using Appium `< 2.4.1` in combination with extensions that require `^2.4.1`, there are two problems:
* Extension CLI (`install` & `update`) does not warn about unmet peer dependencies
* Launching the server shows that the driver is incompatible due to its peer dependency on `older Appium v^2.4.1`

### Expected Behavior

* Installing or updating an extension should at least warn about an unmet peer dependency. Ideal case would probably be to also install only the last extension version compatible with the current server version. 
* The warning when launching the server should refer to a _newer_ Appium version. I _think_ this warning comes from `npm` though, so I dunno if that can be fixed.

### Minimal Reproducible Example

(assuming Appium and all extensions are uninstalled)
```
npm i -g appium@2.2.3
appium driver install uiautomator2 # 2.42.1 -> Appium ^2.4.1
appium
```

OR

```
npm i -g appium@2.2.3
appium driver install --source=npm appium-uiautomator2-driver@2.38.0 # Appium ^2.0.0
appium driver update uiautomator2
appium
```

### Environment

- Operating system: macOS 14.2
- Appium server version (output of `appium --version`): 2.2.3
- Appium driver(s) and their version(s): uiautomator2 2.38.0 & 2.42.1
- Appium plugin(s) and their version(s): n/a
- Node.js version (output of `node --version`): 20.10.0
- `npm` version (output of `npm --version`): 10.2.3
- Last component(s) version which did _not_ exhibit the problem: n/a
- Platform and version under test: n/a
- Real device or emulator/simulator: n/a

**Comment by mykola-mokhnach** [comment]
this is known. Unfortunately we cannot patch older server versions to it will stay like that. the recent version has the fix

**Comment by eglitise** [comment]
Are both issues fixed in newer versions? A quick search showed that my second issue (the incorrect message) is likely fixed in #19612. Not sure about the first one, maybe #19607?

**Comment by mykola-mokhnach** [comment]
The version compatibility check is verified in https://github.com/appium/appium/blob/c3bea4cf14e2a7ce5c4ec98960476175dc5c8e28/packages/appium/lib/cli/extension-command.js#L253

PR: https://github.com/appium/appium/pull/19575

**Comment by eglitise** [comment]
Great, thanks!
