### ISSUE TITLE
bug: [Appium] Error: Cannot find module '@appium/base-plugin'

### ISSUE THREAD

**Issue by adi-tubachi** [appium/appium#19676]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have installed appium2 - 2.4.1
installed element-wait using - appium plugin install --source=npm appium-wait-plugin
ran appium server - appium --use-plugins=element-wait   

getting below error and it is not waiting for elements automatically in automation runs

info Appium Discovered installed plugin "element-wait"
[Appium] Attempting to load plugin element-wait...
[Appium] Requiring plugin at /Users/adarshtubachi/.appium/node_modules/appium-wait-plugin/lib/index.js
[Appium] Could not load plugin 'element-wait', so it will not be available. Error in loading the plugin was: Cannot find module '@appium/base-plugin'
[Appium] Require stack:
[Appium] - /Users/adarshtubachi/.appium/node_modules/appium-wait-plugin/lib/plugin.js
[Appium] - /Users/adarshtubachi/.appium/node_modules/appium-wait-plugin/lib/index.js
[Appium] Error: Cannot find module '@appium/base-plugin'
[Appium] Require stack:
[Appium] - /Users/adarshtubachi/.appium/node_modules/appium-wait-plugin/lib/plugin.js
[Appium] - /Users/adarshtubachi/.appium/node_modules/appium-wait-plugin/lib/index.js
[Appium]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:985:27)
[Appium]     at Module.require (node:internal/modules/cjs/loader:1235:19)
[Appium]     at require (node:internal/modules/helpers:176:18)
[Appium]     at Object.<anonymous> (/Users/adarshtubachi/.appium/node_modules/appium-wait-plugin/lib/plugin.js:15:39)
[Appium]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[Appium]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
[Appium]     at Module.require (node:internal/modules/cjs/loader:1235:19)
[Appium]     at require (node:internal/modules/helpers:176:18)
[Appium]     at Object.<anonymous> (/Users/adarshtubachi/.appium/node_modules/appium-wait-plugin/lib/index.js:7:34)
[Appium]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[Appium]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
[Appium] Welcome to Appium v2.4.1
[Appium] Non-default server args:
[Appium] {
[Appium]   usePlugins: [
[Appium]     'element-wait'
[Appium]   ]
[Appium] }
[Appium] The autodetected Appium home path: /Users/adarshtubachi/.appium/node_modules/appium-wait-plugin

### Expected Behavior

It should not give the error and it should wait for elements in automation automatically

### Minimal Reproducible Example

install appium 2 
install wait element plugin
run appium server using element-wait plugin

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s): UIautomator 
- Appium plugin(s) and their version(s): element-wait@3.0.0
- Node.js version (output of `node --version`): v20.10.0
- `npm` version (output of `npm --version`): 10.2.3
- Last component(s) version which did _not_ exhibit the problem: NA
- Platform and version under test: Running on for android automation
- Real device or emulator/simulator: real device samsung s20 plus

**Comment by mykola-mokhnach** [comment]
Please report the issue to the plugin author.
