### ISSUE TITLE
Cannot Run on iOS 17.2.1

### ISSUE THREAD

**Issue by fatahillahardhi** [appium/appium#19685]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I just updated to iOS 17.2.1, but I always get an error, even though when the device was still on iOS 17.1, everything was fine.
 
the error is:
`org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of failure: Unexpected data: {"Error":"InvalidService","Request":"StartService","Service":"com.apple.testmanagerd.lockdown.secure"}. Please make sure if the com.facebook.WebDriverAgentRunner.xctrunner exists and it is launchable. https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md may help to complete the preparation`

### Expected Behavior

running well without getting this error

### Minimal Reproducible Example

1. Setup WDA from this documentation https://appium.github.io/appium-xcuitest-driver/5.14/preparation/prov-profile-full-manual/ (Xcode Version 15.1 beta 3 (15C5059c))
2. Run Test

### Environment

- Operating system: Mac OS Sonoma 14.4.1
- Appium server version (output of `appium --version`): Appium 2.4.1
- Appium driver(s) and their version(s): XCUITest 5.14.0
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): 18.17.1
- `npm` version (output of `npm --version`): 9.8.1
- Last component(s) version which did _not_ exhibit the problem: iOS 17.1, Appium 2.2.2, XCUitest 5.11
- Platform and version under test: iOS 17.2.1
- Real device or emulator/simulator: Real Device

### Link to Appium Logs

https://gist.github.com/fatahillahardhi/ecca812f1b7c4d89a28e69801fbcecac

**Comment by KazuCocoa** [comment]
It is expected right now. Your capabilities had `"appium:usePreinstalledWDA": true`, then:

https://appium.github.io/appium-xcuitest-driver/5.14/guides/run-preinstalled-wda/

> This method currently does not work for iOS 17/tvOS 17 due to platform changes. Please use the default xcodebuild approach.
