### ISSUE TITLE
|org.openqa.selenium.SessionNotCreatedException: Failed to set language: en and country: EN  

### ISSUE THREAD

**Issue by devikabontalakoti** [appium/appium#19695]
|org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Failed to set language: en and country: EN 

Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.4', java.version: '17.0.6'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [null, newSession {capabilities=[{appium:appActivity=com.zodiac.fluidrapro.MainActivity, appium:appPackage=com.zodiac.fluidrapro, appium:autoDismissAlerts=true, appium:automationName=UiAutomator2, appium:deviceName=26171JEGR06223, appium:language=en, appium:locale=EN, platformName=ANDROID, appium:platformVersion=14, appium:unicodeKeyboard=true}], desiredCapabilities=Capabilities {appActivity: com.zodiac.fluidrapro.MainA..., appPackage: com.zodiac.fluidrapro, autoDismissAlerts: true, automationName: UiAutomator2, deviceName: 26171JEGR06223, language: en, locale: EN, platformName: ANDROID, platformVersion: 14, unicodeKeyboard: true}}]
Capabilities {appActivity: com.zodiac.fluidrapro.MainA..., appPackage: com.zodiac.fluidrapro, autoDismissAlerts: true, automationName: UiAutomator2, deviceName: 26171JEGR06223, language: en, locale: EN, platformName: ANDROID, platformVersion: 14, unicodeKeyboard: true}

Need inputs to resolve this issue. Thank you !!

**Comment by KazuCocoa** [comment]
Please fill in the bug template. Also, please check the usage of `locale` https://github.com/appium/appium-uiautomator2-driver I don't know if `EN` country exists, btw. https://en.wikipedia.org/wiki/ISO_3166-1

**Comment by mykola-mokhnach** [comment]
The error is expected. Make sure you set a correct locale abbreviation as mentioned above.
