### ISSUE TITLE
bug: ios Accept the alert for using the network error

### ISSUE THREAD

**Issue by aerfafish** [appium/appium#19691]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/appium/appium/assets/53930117/4b26c352-e505-4742-a911-cffa304a0b7d)

### Expected Behavior

click WLAN and Celluar or WLAN ONLY

### Minimal Reproducible Example

self.driver.switch_to.alert.accept()

### Environment

- Operating system:
- Appium server version (output of `appium --version`):2.4.1
- Appium driver(s) and their version(s): xcuitest@4.21.25
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):19.5.0
- `npm` version (output of `npm --version`):9.3.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: macos
- Real device or emulator/simulator: some iPhone

**Comment by aerfafish** [comment]
[38;5;0m[HTTP][0m [37m-->[39m [37mGET[39m [37m/wd/hub/session/e9bbccc2-9de0-424b-9728-65bdb6ad2ae0/alert/text[39m
[38;5;0m[HTTP][0m [90m{}[39m
[38;5;32m[XCUITestDriver@7a65 (e9bbccc2)][0m Calling AppiumDriver.getAlertText() with args: ["e9bbccc2-9de0-424b-9728-65bdb6ad2ae0"]
[38;5;32m[XCUITestDriver@7a65 (e9bbccc2)][0m Executing command 'getAlertText'
[38;5;32m[XCUITestDriver@7a65 (e9bbccc2)][0m Matched '/alert/text' to command name 'getAlertText'
[38;5;32m[XCUITestDriver@7a65 (e9bbccc2)][0m Proxying [GET /alert/text] to [GET http://localhost:2324/session/6FD910ED-43CE-46F0-9F0E-9C879D1D8FB2/alert/text] with no body
[38;5;32m[XCUITestDriver@7a65 (e9bbccc2)][0m Got response with status 200: {"value":"Allow “” to use wireless data?\nSome functionality may not work when wireless data is turned off.","sessionId":"6FD910ED-43CE-46F0-9F0E-9C879D1D8FB2"}
[38;5;32m[XCUITestDriver@7a65 (e9bbccc2)][0m Responding to client with driver.getAlertText() result: "Allow “” to use wireless data?\nSome functionality may not work when wireless data is turned off."
[38;5;0m[HTTP][0m [37m<-- GET /wd/hub/session/e9bbccc2-9de0-424b-9728-65bdb6ad2ae0/alert/text [39m[32m200[39m [90m357 ms - 124[39m
[38;5;0m[HTTP][0m [90m[39m
[38;5;0m[HTTP][0m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/e9bbccc2-9de0-424b-9728-65bdb6ad2ae0/alert/accept[39m
[38;5;0m[HTTP][0m [90m{}[39m
[38;5;32m[XCUITestDriver@7a65 (e9bbccc2)][0m Calling AppiumDriver.postAcceptAlert() with args: ["e9bbccc2-9de0-424b-9728-65bdb6ad2ae0"]
[38;5;32m[XCUITestDriver@7a65 (e9bbccc2)][0m Executing command 'postAcceptAlert'
[38;5;32m[XCUITestDriver@7a65 (e9bbccc2)][0m Matched '/alert/accept' to command name 'postAcceptAlert'
[38;5;32m[XCUITestDriver@7a65 (e9bbccc2)][0m Proxying [POST /alert/accept] to [POST http://localhost:2324/session/6FD910ED-43CE-46F0-9F0E-9C879D1D8FB2/alert/accept] with body: {}
[38;5;32m[XCUITestDriver@7a65 (e9bbccc2)][0m Got response with status 200: {"value":null,"sessionId":"6FD910ED-43CE-46F0-9F0E-9C879D1D8FB2"}
[38;5;32m[XCUITestDriver@7a65 (e9bbccc2)][0m Responding to client with driver.postAcceptAlert() result: null

**Comment by aerfafish** [comment]
I will try updating the WebDriverAgent

**Comment by SayWeeeXuZhongyuan** [comment]
Is this issue be resolved?

**Comment by aerfafish** [comment]
> Is this issue be resolved please? @aerfafish

It seems that it works fine after updating wda. You can try it.

**Comment by SayWeeeXuZhongyuan** [comment]
> > Is this issue be resolved please? @aerfafish
> 
> It seems that it works fine after updating wda. You can try it.

which version for wda please? 
and then use driver.switch_to.alert.accept()?
