### ISSUE TITLE
bug: Running Appium from JavaScript has invalid signature for subcommand "driver"

### ISSUE THREAD

**Issue by aristotelos** [appium/appium#19709]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to install the Appium Windows driver in a "BeforeAll" hook in Cucumber. This doesn't work if I use the following code:
```
import { BeforeAll } from "@cucumber/cucumber";
import { init } from "appium";

BeforeAll({ timeout: 150 * 1000 }, async () => {
    await init({
        subcommand: "driver",
        driverCommand: "list",
        installType: "npm",
        driver: "appium-windows-driver",
    });
});
```
This gives a type error:
```
Argument of type '{ subcommand: string; driverCommand: string; installType: string; driver: string; }' is not assignable to parameter of type 'undefined'.ts(2345)
```
It seems that as soon as I use `subcommand: "driver"` the signature of `init` does not allow any `args` anymore.

### Expected Behavior

The code should not give a type exception.

### Minimal Reproducible Example

```
import { init } from "appium";

await init({
    subcommand: "driver",
    driverCommand: "list",
    installType: "npm",
    driver: "appium-windows-driver",
});
```

### Environment

- Operating system: Windows
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s): n.a.
- Appium plugin(s) and their version(s): n.a.
- Node.js version (output of `node --version`): v18.18.2
- `npm` version (output of `npm --version`): 9.8.1
- Last component(s) version which did _not_ exhibit the problem: unknown
- Platform and version under test: n.a.
- Real device or emulator/simulator: n.a.

**Comment by jlipps** [comment]
Why are you using the Appium package directly? This isn't an officially supported use case

**Comment by mykola-mokhnach** [comment]
Closed as not an issue. The server itself is supposed to be executed as a "black box". We do not guarantee types compatibility between minor versions, only API compatibility.

**Comment by aristotelos** [comment]
> Why are you using the Appium package directly? This isn't an officially supported use case

Are there other ways to execute Appium from JavaScript directly? I have noticed that e.g. the [WebDriverIO Appium Service uses `spawn`](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-appium-service/src/launcher.ts#L160) to run Appium, so I could try to switch to that, although it seems a bit cumbersome.

**Comment by jlipps** [comment]
Appium is designed to be run as a separate process from the client script. The way to use it "directly" is to do what you've been doing, it's just that as @mykola-mokhnach said this is not really a supported use case so you might run into these internal type signature changes being an issue from time to time, and would need to keep more up to date with Appium development. Appium isn't really published as a node lib.

**Comment by jlipps** [comment]
But yes, what I would do if I were executing `appium driver` commands is use subprocesses and ensure the `--json` flag is set so output can be easily parsed by a script.
