### ISSUE TITLE
MacOS: appium-doctor cannot find bundletool.jar

### ISSUE THREAD

**Issue by itkhanz** [appium/appium#19704]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i installed the bundletool on my MAC as follows:

- Downloaded the latest bundletool jar from [releases](https://github.com/google/bundletool/releases
) page i.e. 1.15.6
- Added a new folder with name `bundle-tool` inside my `ANDROID_HOME,` and pasted the downloaded jar file in this folder
- Renamed it to `bundletool.jar`
- Inside bundle-tool folder executed commands `chmod +x bundletool.jar` and `chmod 655 bundletool.jar`
- Added bundle-tool to PATH

```
export ANDROID_HOME=${HOME}/Library/Android/sdk

export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/bundle-tool
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
```

- source it by executing the command `source ~/.zshrc`
- running the command 'appium-doctor --android' does not recognize the bundletool.jar

I get the following output:-

```
WARN AppiumDoctor  ✖ bundletool.jar cannot be found
WARN AppiumDoctor  ➜ bundletool.jar is used to handle Android App Bundle. Please read http://appium.io/docs/en/writing-running-appium/android/android-appbundle/ to install it
```

- Also running the command `which 'bundletool.jar'` gives `bundletool not found` error message

Additional Context:
If you install it via homebrew with `brew install bundletool`, then running command `which bundletool` shows it in the path `/opt/homebrew/bin/bundletool` but `appium-doctor --android` still throws the same error message
Reference Links:
https://github.com/appium/appium/blob/1.x/docs/en/writing-running-appium/android/android-appbundle.md
https://github.com/google/bundletool/releases
https://formulae.brew.sh/formula/bundletool

### Expected Behavior

Running the commands 'appium-doctor --android' should recognize the bundletool installation and presence in path
Running the command `which 'bundletool.jar'` should show the path of bundletool

### Minimal Reproducible Example

Described in current behavior.

### Environment

- Operating system: macOS Sonoma 14.2.1 (Silicon Chip)
- Appium server version (output of `appium --version`): 2.4.1
- Appium-doctor version: 2.0.31
- Node.js version (output of `node --version`): 20.11.0
- `npm` version (output of `npm --version`): 10.2.4

**Comment by mykola-mokhnach** [comment]
Make sure the node process where doctor is running gets the correct environment: https://github.com/appium/java-client/blob/master/docs/environment.md

**Comment by mykola-mokhnach** [comment]
> export PATH=$PATH:$ANDROID_HOME/emulator
> export PATH=$PATH:$ANDROID_HOME/tools
> export PATH=$PATH:$ANDROID_HOME/tools/bin
> export PATH=$PATH:$ANDROID_HOME/platform-tools
> export PATH=$PATH:$ANDROID_HOME/bundle-tool
> export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin

Also I don't see that the folder where you put bundle tool is present in the list of PATH.

**Comment by itkhanz** [comment]
> https://github.com/appium/java-client/blob/master/docs/environment.md

bundle-tool folder is placed directly under the ANDROID_HOME 
This bundle-tool folder path is then exported to Path as:

```
export ANDROID_HOME=${HOME}/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/bundle-tool
```

`bundletool.jar` is placed inside bundle-tool folder in ANDROID_HOME

**Comment by itkhanz** [comment]
Ok so I figured out the issue. In my case, a new `.zprofile` file was created automatically to set PATH after I installed Python and this was perhaps contradicting with the PATH set in `.zshrc` which caused it to not recognize the Path for buildtool.

I copied the stuff from .zprofile to .zshrc, and later removed the .zprofile. Here's the final look of .zshrc:

```
export ANDROID_HOME=${HOME}/Library/Android/sdk

export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
export PATH=$PATH:$ANDROID_HOME/bundle-tool
```


This resolved the issue, and now all the dependencies are shown to be good for `appium-doctor --android`.

```
info AppiumDoctor 
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor 
```

Also the output of running which 'bundletool.jar' displays the correct path for it now.
/Users/xxxx/Library/Android/sdk/bundle-tool/bundletool.jar
