### ISSUE TITLE
bug: latest XCUItest driver does not show system dialogs (alerts) in hierarchy

### ISSUE THREAD

**Issue by RSM-SBA** [appium/appium#19716]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Camera permission dialog is not shown anymore in the DOM hierarchy
![image](https://github.com/appium/appium/assets/90029825/a5253958-27dc-4911-a549-c9d32c178600)

### Expected Behavior

in driver version xcuitest@5.14.0 this dialog was shown and could be interacted with

### Minimal Reproducible Example

start an app with camera permissions required and do a getPageSource() when the permission dialog is open

### Environment

- Operating system: MacOS Ventura
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s):  XCUITestDriver 5.14.1
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v20.10.0
- `npm` version (output of `npm --version`): 10.2.3
- Last component(s) version which did _not_ exhibit the problem: 5.14.0
- Platform and version under test: iOS
- Real device or emulator/simulator: Simulator

**Comment by mykola-mokhnach** [comment]
Most likely this alert belongs to another application (e.g. springboard). Switch to it using `mobile: activateApp` API and then it will be possible to interact with the dialog. AFAIK apis that work with alerts check both the active app and the system one.

**Comment by RSM-SBA** [comment]
ok so i have to create a workaround for this change in XCUITest driver ? because it worked the last version...

**Comment by RSM-SBA** [comment]
@mykola-mokhnach ok added now the workaround to switch to springboard and that works.

**Comment by KazuCocoa** [comment]
Or:

```
driver.settings.update({acceptAlertButtonSelector: '**/XCUIElementTypeButton[`label=="Allow Once"`]'})
driver.switch_to.alert.accept
```

or

```
driver.execute_script 'mobile: alert', {action: 'accept', buttonLabel: 'Allow Once'}
```

like these commands also should help.

**Comment by wswebcreation** [comment]
@KazuCocoa 

I've been trying to implement the workarounds that are suggested

- open springboard
- use the `mobile:alert`

But it's not working in all cases. Here's one that is not working (you can download the app from [here](https://github.com/webdriverio/native-demo-app/releases)). When you 
- have setup Face ID for the sim, 
- open the app
- Go to Form
- Click on the Face ID logo
- Select a "Non-matching face"

Then the dialog can not be found (`An attempt was made to operate on a modal dialog when one was not open`). Going to the home screen will close the dialog, and the `mobile:alert` is not returning any data

![image](https://github.com/appium/appium/assets/11979740/e78bea5a-7f06-4abf-ae9e-bc50ac407ec7)

**Appium:**
- Appium v2.5.1
- xcuitest@7.9.1

Secondly, we were able to get the text of a dialog in the past, this is also not possible anymore

**Comment by KazuCocoa** [comment]
Did you try out defaultActiveApplication settings way?

**Comment by wswebcreation** [comment]
Nope, will try that in a few second, thanks, will update the post in a few min

**Comment by wswebcreation** [comment]
Ok, that works, I'll update my code and will add some context here for people who are facing this issue. Thanks @KazuCocoa

**Comment by wswebcreation** [comment]
Hi @KazuCocoa 

Thanks for pointing this out, if now works and I've created this wrapper for it

```ts
/**
 * Typically, app dialogs are initiated by the application itself and can be interacted with via standard Appium commands. However, there are occasions
 * when a dialog is initiated by the operating system, rather than the app. An example of this is the "Touch/Face ID" permission dialog on iOS. Since this
 * dialog is outside the app's context, normal Appium interactions within the app context won't work. To interact with such dialogs, a strategy is to switch
 * the interaction context to the home screen. The `executeInHomeScreenContext` function is designed for this purpose. For iOS, it temporarily changes the
 * interaction context to the home screen (com.apple.springboard), allowing interaction with the system dialog, and then switches back to the original app context
 * post-interaction.
 * Src: https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#interact-with-dialogs-managed-by-comapplespringboard
 */
export async function executeInHomeScreenContext(action:() => Promise<void>): Promise<any> {
    // For Android, directly execute the action as this workaround isn't necessary
    if (driver.isAndroid) {
        return action();
    }

    // Retrieve the currently active app information
    const activeAppInfo: AppInfo = await driver.execute('mobile: activeAppInfo');
    // Switch the active context to the iOS home screen
    await driver.updateSettings({ 'defaultActiveApplication': 'com.apple.springboard' });
    let result;

    try {
        // Execute the action in the home screen context
        result = await action();
    } catch (e) {
        // Ignore any exceptions during the action
    }

    // Revert to the original app context
    await driver.updateSettings({ 'defaultActiveApplication': activeAppInfo.bundleId });

    return result;
}
```

**Comment by wswebcreation** [comment]
As far as I understood this is not a bug but "expected" behaviour of the WDA/XCUITest/iOS. So my suggestion would be to also write a wrapper in Python and share it here so other people can learn from it

**Comment by pespinel** [comment]
@mykola-mokhnach Can you make this behavior optional? We don't mind if the WebDriverAgent waits more in order to check that the app is in foreground. This change breaks a lot of our code because We were treating all the native popups as page objects from our app. Also We have an algorithm to auto-navigate to page-objects from certain starting points so in our case is not as simple as adding an activateApp at certain points.

> Most likely this alert belongs to another application (e.g. springboard). Switch to it using `mobile: activateApp` API and then it will be possible to interact with the dialog. AFAIK apis that work with alerts check both the active app and the system one.

**Comment by KazuCocoa** [comment]
Didn't `defaultActiveApplication` https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/ with keeping springboard help?

**Comment by pespinel** [comment]
> Didn't `defaultActiveApplication` https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/ with keeping springboard help?

Setting `defaultActiveApplication` to `auto` didn't work. We cannot update the bundleID before searching for native alerts because We use generic code for all the elements (Elements from our app and native elements). We don't mind an "unnecessary delay while selecting a proper application to interact with" if We can still use all of our codebase.

**Comment by KazuCocoa** [comment]
No, I meant setting it as `com.apple.springboard` and don't set `auto` again. Then, perhaps appium searches available all elements every time.

**Comment by pespinel** [comment]
It hasn't worked either 😢

**Comment by KazuCocoa** [comment]
Then, the method below in https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/ behaves as same as the old detection logic. So, if your session can start without app/bundled and activate the test app after the session creation separately, it could be an alternative in current implementation.

> Start a session without appium:app nor appium:bundleId ...

**Comment by pespinel** [comment]
We can't do it (Without a big refactor) either... our framework supports multiple apps with different bundle IDs 😿

**Comment by pespinel** [comment]
The only 'simple' workaround is to fetch the FBSession.m from the v5.15.6 tag (The last one without this change) and update it with the new changes in master of appium/WebDriverAgent:

https://www.diffchecker.com/hmMAKvvI/

I have compiled the WDA-Runner with this changes and everything works like before.

**Comment by pespinel** [comment]
Actually, it works with only this diff:

```
❯ git diff WebDriverAgentLib/Routing/FBSession.m
diff --git a/WebDriverAgentLib/Routing/FBSession.m b/WebDriverAgentLib/Routing/FBSession.m
index 82134e0c..d6f878fa 100644
--- a/WebDriverAgentLib/Routing/FBSession.m
+++ b/WebDriverAgentLib/Routing/FBSession.m
@@ -166,25 +166,21 @@ - (void)kill

 - (XCUIApplication *)activeApplication
 {
-  BOOL isAuto = [self.defaultActiveApplication isEqualToString:FBDefaultApplicationAuto];
-  NSString *defaultBundleId = isAuto ? nil : self.defaultActiveApplication;
-
-  if (nil != defaultBundleId && [self applicationStateWithBundleId:defaultBundleId] >= XCUIApplicationStateRunningForeground) {
-    return [self makeApplicationWithBundleId:defaultBundleId];
-  }
-
-  if (nil != self.testedApplication) {
-    XCUIApplicationState testedAppState = self.testedApplication.state;
-    if (testedAppState >= XCUIApplicationStateRunningForeground) {
-      return (XCUIApplication *)self.testedApplication;
-    }
-    if (self.isTestedApplicationExpectedToRun && testedAppState <= XCUIApplicationStateNotRunning) {
-      NSString *description = [NSString stringWithFormat:@"The application under test with bundle id '%@' is not running, possibly crashed", self.testedApplication.bundleID];
-      @throw [NSException exceptionWithName:FBApplicationCrashedException reason:description userInfo:nil];
-    }
-  }
-
-  return [XCUIApplication fb_activeApplicationWithDefaultBundleId:defaultBundleId];
+  NSString *defaultBundleId = [self.defaultActiveApplication isEqualToString:FBDefaultApplicationAuto]
+    ? nil
+    : self.defaultActiveApplication;
+  XCUIApplication *application = [XCUIApplication fb_activeApplicationWithDefaultBundleId:defaultBundleId];
+  XCUIApplication *testedApplication = nil;
+  if (self.testedApplication && self.isTestedApplicationExpectedToRun) {
+    testedApplication = nil != application && [application.bundleID isEqualToString:self.testedApplication.bundleID]
+      ? application
+      : [[XCUIApplication alloc] initWithBundleIdentifier:self.testedApplication.bundleID];
+  }
+  if (testedApplication && !testedApplication.running) {
+    NSString *description = [NSString stringWithFormat:@"The application under test with bundle id '%@' is not running, possibly crashed", self.testedApplication];
+    [[NSException exceptionWithName:FBApplicationCrashedException reason:description userInfo:nil] raise];
+  }
+  return application;
 }

 - (XCUIApplication *)launchApplicationWithBundleId:(NSString *)bundleIdentifier
```

**Comment by KazuCocoa** [comment]
Perhaps in case we need to add an option, the flow would be:

1. xcuitest driver starts WDA process without bundleId
2. xcuitest driver activates the given bundle id via launchApp/activateApp endpoint
3. return new session request's response

So, xcuitest driver layer does the without app/bundleId method in a new session request

**Comment by pespinel** [comment]
> Perhaps in case we need to add an option, the flow would be:
> 
> 1. xcuitest driver starts WDA process without bundleId
> 2. xcuitest driver activates the given bundle id via launchApp/activateApp endpoint
> 3. return new session request's response
> 
> So, xcuitest driver layer does the without app/bundleId method in a new session request

We did a dirty test starting the session without bundle_id nor app capabilities and it seems to work. We can do medium refactor to start the iOS sessions without those capabilities and then call `activate_app` with the bundleID. This way We can avoid to modify internal files of the WDALib.
Thank you for the help.

**Comment by KazuCocoa** [comment]
Thank you. i meant in case Appium XCUITest driver needs to have an option. So for example `appium:legacyActiveAppDetection: true`, then XCUITest driver will do:

1. xcuitest driver starts WDA process without bundleId
2. xcuitest driver activates the given bundle id via launchApp/activateApp endpoint
3. return new session request's response

Then, this behavior could be an optional.

**Comment by eglitise** [comment]
@Aubbles01 that was an example name, the finalised name of the setting is `appium:respectSystemAlerts`, added in XCUITest driver 7.17.0.

**Comment by Aubbles01** [comment]
Huh....I tried that setting and it didn't seem to work for me.  I tried setting appium:respectSystemAlerts to true via boolean and string just in case that was my issue.

Here's my desired capabilities in case anyone can spot my issue (removed any sensitive info):
{
  "platformName": "iOS",
  "appium:deviceName": "My iPad",
  "appium:automationName": "XCUITest",
  "appium:app": _"app location and name removed for privacy"_,
  "appium:noReset": true,
  "appium:udid": "_udid removed fro privacy"_,
  "appium:xcodeOrgId": "_orgId removed for privacy_",
  "appium:xcodeSigningId": "iPhone Developer",
  "appium:updateWDABundleId": "com.companyName.WebDriverAgentRunner",
  "appium:installStrategy": "parallel",
  "appium:respectSystemAlerts": true
}

I did double check my XCUI driver version as well:
✔ Listing available drivers
- uiautomator2@3.5.3 [installed (npm)]
- xcuitest@7.17.4 [installed (npm)]
- windows@2.12.24 [installed (npm)]
- espresso [not installed]
- mac2 [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]

**Comment by KazuCocoa** [comment]
It is via settings api https://appium.github.io/appium-xcuitest-driver/latest/reference/settings/

**Comment by eglitise** [comment]
Correct. Refer to the documentation on how to specify settings as part of your capability set: https://appium.io/docs/en/latest/guides/settings/#initializing-settings-via-capabilities

**Comment by natan-abolafya** [comment]
I have had this issue with the following scenario:
- Our app starts with one appium instance
- Then we start the Safari with another appium instance on another port
- Then we close the session on that instance right after going back to the app with `'mobile: activateApp'`
- Then our app prompts the user for allowing VPN connections.

If we don't start the Safari first, this is not an issue and we can accept the alert easily. But somehow this flow makes the prompt owned by some other app.
`respectSystemAlerts` setting did not work on this. Neither did changing `defaultActiveApplication` as it kept getting "socket hang up" error.
I have tried starting a new session without `appium:app` nor `appium:bundleId` and that worked 🥳.

I just wanted to share in case somebody else hits this. Also that it might be something to fix for `respectSystemAlerts` though there might be other explanations.
