### ISSUE TITLE
[Feat]: check the support of non-WebKit browser in xcuitest driver

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#19729]
**Is your feature request related to a problem? Please describe.**

Apple will allow the use of a non-bundled WebKit engine browser (for EU).
https://www.theverge.com/2024/1/25/24050478/apple-ios-17-4-browser-engines-eu

I don't know if it will add another method to automate webview, so let me leave an issue here.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Is this task still relevant?

**Comment by KazuCocoa** [comment]
I have not this env as non-EU region work environment, so... I think we can close this for now. Current my guess for this is chromedriver for iOS, but not sure how possible it is. Let's consider this when we meet non-WebKit (remote controller) case
