### ISSUE TITLE
May I ask what happens when clicking and swiping on an Android phone with an error message and there is no operation on the phone

### ISSUE THREAD

**Issue by xiaoliangjia111** [appium/appium#19733]
May I ask what happens when clicking and swiping on an Android phone with an error message and there is no operation on the phone

error LOG:[HTTP] <-- POST /wd/hub/session/a43472e4-a1c5-461a-9753-10e09bb35b07/touch/perform 400 10902 ms - 3684
[HTTP]
[HTTP] --> POST /wd/hub/session/a43472e4-a1c5-461a-9753-10e09bb35b07/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":800,"y":1600}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":800,"y":200}},{"action":"release","options":{}}]}
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":800,"y":1600}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":800,"y":200}},{"action":"release","options":{}}],"a43472e4-a1c5-461a-9753-10e09bb35b07"]
[AppiumDriver@8aeb] Plugins which can handle cmd 'performTouch': device-farm
[AppiumDriver@8aeb] Plugin device-farm is now handling cmd 'performTouch'
[device-farm] Received performTouch request on driver - [object Object]
[AppiumDriver@8aeb] Executing default handling behavior for command 'performTouch'
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] Matched '/touch/perform' to command name 'performTouch'
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] Proxying [POST /touch/perform] to [POST http://127.0.0.1:49839/session/8ab3536e-b0df-4371-ad33-9e1374fdb525/touch/perform] with body: {"startX":800,"startY":1600,"endX":800,"endY":200,"steps":28}
[AndroidUiautomator2Driver@2b57 (a43472e4)] Got response with status 400: {"sessionId":"8ab3536e-b0df-4371-ad33-9e1374fdb525","value":{"error":"invalid element state","message":"Swipe action cannot be performed","stacktrace":"io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Swipe action cannot be performed\n\tat io.appium.uiautomator2.handler.Swipe.safeHandle(Swipe.java:78)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:277)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:271)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)\n\t...
[debug] [W3C] Matched W3C error code 'invalid element state' to InvalidElementStateError
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] Encountered internal error running command: io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Swipe action cannot be performed
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.appium.uiautomator2.handler.Swipe.safeHandle(Swipe.java:78)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:277)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:271)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] at java.lang.Thread.run(Thread.java:930)
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)]
[HTTP] <-- POST /wd/hub/session/a43472e4-a1c5-461a-9753-10e09bb35b07/touch/perform 400 10850 ms - 3684
[HTTP]
[HTTP] --> POST /wd/hub/session/a43472e4-a1c5-461a-9753-10e09bb35b07/touch/perform
[HTTP] {"actions":[{"action":"press","options":{"x":300,"y":2000}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":300,"y":200}},{"action":"release","options":{}}]}
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":300,"y":2000}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":300,"y":200}},{"action":"release","options":{}}],"a43472e4-a1c5-461a-9753-10e09bb35b07"]
[AppiumDriver@8aeb] Plugins which can handle cmd 'performTouch': device-farm
[AppiumDriver@8aeb] Plugin device-farm is now handling cmd 'performTouch'
[device-farm] Received performTouch request on driver - [object Object]
[AppiumDriver@8aeb] Executing default handling behavior for command 'performTouch'
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] Matched '/touch/perform' to command name 'performTouch'
[debug] [AndroidUiautomator2Driver@2b57 (a43472e4)] Proxying [POST /touch/perform] to [POST http://127.0.0.1:49839/session/8ab3536e-b0df-4371-ad33-9e1374fdb525/touch/perform] with body: {"startX":300,"startY":2000,"endX":300,"endY":200,"steps":28}

**Comment by KazuCocoa** [comment]
The endpoint is deprecated with the latest driver. https://github.com/appium/appium-uiautomator2-driver/blob/cb47b41705108522faf42db2c164a6874556aec0/lib/commands/touch.js#L5 If you used newer client/appium, they may show deprecated messages.

Could you try out w3c actions or swipe gesture actions in https://github.com/appium/appium-uiautomator2-driver ? Also, it would be helpful to share the full appium log.

Asking questions in https://discuss.appium.io/ would also help

**Comment by mykola-mokhnach** [comment]
You can also use corresponding gesture shortcuts: https://github.com/appium/appium-uiautomator2-driver/blob/master/docs/android-mobile-gestures.md#mobile-swipegesture

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
