### ISSUE TITLE
Infinite search for correct app iOS 16.4

### ISSUE THREAD

**Issue by accelq** [appium/appium#19757]
Hi, there during an execution there are multiple app switches that happens as part of testing flow. During this at one point of time it falls into a sort of infinite loop. Attaching the logs here, the app we wish to switch for "com.example.secondapp"

The appium session was started with bundle ID "com.example.firstapp".

Here the complete logs:
[21679.txt](https://github.com/appium/appium/files/14191892/21679.txt)

Snippet of code from the above txt file

`
[RemoteDebugger] Current applications available:

[RemoteDebugger]     Application: "PID:25883"

[RemoteDebugger]         id: "PID:25883"

[RemoteDebugger]         isProxy: false

[RemoteDebugger]         name: "com.apple.WebKit.WebContent"

[RemoteDebugger]         bundleId: "process-com.apple.WebKit.WebContent"

[RemoteDebugger]         hostId: undefined

[RemoteDebugger]         isActive: true

[RemoteDebugger]         isAutomationEnabled: "Unknown"

[RemoteDebugger]     Application: "PID:25887"

[RemoteDebugger]         id: "PID:25887"

[RemoteDebugger]         isProxy: false

[RemoteDebugger]         name: "com.apple.WebKit.WebContent"

[RemoteDebugger]         bundleId: "process-com.apple.WebKit.WebContent"

[RemoteDebugger]         hostId: undefined

[RemoteDebugger]         isActive: false

[RemoteDebugger]         isAutomationEnabled: "Unknown"

[RemoteDebugger]     Application: "PID:25872"

[RemoteDebugger]         id: "PID:25872"

[RemoteDebugger]         isProxy: false

[RemoteDebugger]         name: "com.apple.WebKit.WebContent"

[RemoteDebugger]         bundleId: "process-com.apple.WebKit.WebContent"

[RemoteDebugger]         hostId: undefined

[RemoteDebugger]         isActive: true

[RemoteDebugger]         isAutomationEnabled: "Unknown"

[RemoteDebugger]     Application: "PID:25665"

[RemoteDebugger]         id: "PID:25665"

[RemoteDebugger]         isProxy: false

[RemoteDebugger]         name: "Example"

[RemoteDebugger]         bundleId: "com.example.secondapp"

[RemoteDebugger]         hostId: undefined

[RemoteDebugger]         isActive: false

[RemoteDebugger]         isAutomationEnabled: "Unknown"

[RemoteDebugger]     Application: "PID:25681"

[RemoteDebugger]         id: "PID:25681"

[RemoteDebugger]         isProxy: false

[RemoteDebugger]         name: "com.apple.WebKit.WebContent"

[RemoteDebugger]         bundleId: "process-com.apple.WebKit.WebContent"

[RemoteDebugger]         hostId: undefined

[RemoteDebugger]         isActive: false

[RemoteDebugger]         isAutomationEnabled: "Unknown"

[RemoteDebugger]     Application: "PID:25867"

[RemoteDebugger]         id: "PID:25867"

[RemoteDebugger]         isProxy: false

[RemoteDebugger]         name: "Example"

[RemoteDebugger]         bundleId: "com.example.firstapp"

[RemoteDebugger]         hostId: undefined

[RemoteDebugger]         isActive: true

[RemoteDebugger]         isAutomationEnabled: "Unknown"

[RemoteDebugger] Checking for bundle identifiers: com.apple.WebKit.WebContent, process-com.apple.WebKit.WebContent, process-SafariViewService, com.apple.SafariViewService, *, com.example.secondapp

[RemoteDebugger] Found app id key 'PID:25883' for bundle 'com.apple.WebKit.WebContent'

[RemoteDebugger] Found app id key 'PID:25883' for bundle 'process-com.apple.WebKit.WebContent'

[RemoteDebugger] Found app id key 'PID:25883' for bundle 'process-SafariViewService'

[RemoteDebugger] Found app id key 'PID:25883' for bundle 'com.apple.SafariViewService'

[RemoteDebugger] Found app id key 'PID:25883' for bundle '*'

[RemoteDebugger] Found app id key 'PID:25665' for bundle 'com.example.secondapp'

[RemoteDebugger] Trying out the possible app ids: PID:25883, PID:25665 (try #1 of 20)

`

**Comment by Dan-Maor** [comment]
Perhaps try to add `com.bostonscientific.synergy2test` using the `appium:additionalWebviewBundleIds` capability.
See https://appium.github.io/appium-xcuitest-driver/6.0/reference/capabilities/

**Comment by mykola-mokhnach** [comment]
I don't see any major issues there. The code retries 20 times and then gives up (probably because the chatter web view is inactive):

```
[RemoteDebugger]     Application: "PID:25665"

[RemoteDebugger]         id: "PID:25665"

[RemoteDebugger]         isProxy: false

[RemoteDebugger]         name: "Salesforce"

[RemoteDebugger]         bundleId: "com.salesforce.chatter"

[RemoteDebugger]         hostId: undefined

[RemoteDebugger]         isActive: false

[RemoteDebugger]         isAutomationEnabled: "Unknown"
```

Maybe try the suggestion above from @Dan-Maor and/or make sure the target web view can be interacted with.

**Comment by accelq** [comment]
Hi, will try this out and update

**Comment by accelq** [comment]
It worked thanks.
