### ISSUE TITLE
[Feat]: add checkVersion for mobile:installApp to add version comparison  in Appium as same as new session request

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#19754]
From https://github.com/appium/appium/issues/15807#issuecomment-1926750630 as a note:

So that the endpoint behaves the same as the installed version check as a new session request.

If the installed app version is lower than the currently installed one, the install will do nothing. `enforceAppInstall` `true` does the app uninstallation in the command. No the option keeps current behavior, just calls installation method.

https://github.com/appium/appium-android-driver/blob/acaf50709b96e95e05f7b5d0851893407718dea1/lib/commands/app-management.js#L224
https://github.com/appium/appium-xcuitest-driver/blob/ca6d06155ac3046f9d8ffaa67904ebb80c191d37/lib/commands/app-management.js#L168

I also wondered if we could define a new mobile command naming to control the response more. Still just an idea.

**Comment by mykola-mokhnach** [comment]
I am not sure if this is really necessary. There is the `mobile: uninstallApp` endpoint, which does app uninstall.

**Comment by KazuCocoa** [comment]
Yes, uninstalling part is not main thing, if app install occurs by comparing version is main motivation instead

**Comment by KazuCocoa** [comment]
Added `checkVersion` option for uia2, espresso and xcuitest driver's `mobile:installApp`
