### ISSUE TITLE
Drag and drop a widget to home screen

### ISSUE THREAD

**Issue by pmedinaNGTI** [appium/appium#19765]
I am trying to drag and drop a native widget to the home screen and I see that the widget moves but I do not see that the widget is displayed on the home screen. I am looking for some example where I can see this working, I saw some posts where the team has shared some examples but when I try to access to the links I get 404. Example:

> Android doesn't handle `longPress`-`wait`-`moveTo`-`release` as
> drag-and-drop. Without the `wait` Appium translates it into a native
> drag-and-drop, which should work. The test [here](https://github.com/appium/appium/blob/master/test/functional/android/apidemos/touch/drag-specs.js#L53)
> is how it should be done, I think.
> Originally posted by @imurchie in https://github.com/appium/appium/issues/3104#issuecomment-48512058_

            
Here the code that I have:
```
public async swipeByCoordinates(xStart: number, yStart: number, xFinish: number, yFinish: number): Promise<void> {
    await this.switchToNativeContext();
    await driver.touchAction([
      { action: 'press', x: xStart, y: yStart },
      {action: 'wait', ms: 500 },
      { action: 'moveTo', x: xFinish, y: yFinish },
      'release',
      {action: 'wait', ms: 500 },
    ]);
  }
```

**Comment by mykola-mokhnach** [comment]
Please fill out your issue report properly according to the given reporting template.
Are you sure your issue is with the server and not the client? It is eventually the client's task to compile the W3C actions JSON . The server simply executes it.

**Comment by pmedinaNGTI** [comment]
Hello @mykola-mokhnach, thank you for reacting to my post,
where can I find the reporting template?
About your question: **"Are you sure your issue is with the server and not the client?"**: I believe it is because I not giving it the correct end coordinates maybe, but I am not sure; and I am calculating manually the location of the widget, is there a better way to do this? Do you have some example with a generic widget like Calendar?

**Comment by mykola-mokhnach** [comment]
> where can I find the reporting template?

It is already pre-filled when creating a new issue. You can also check https://github.com/appium/appium/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml

> I believe it is because I not giving it the correct end coordinates maybe, but I am not sure; and I am calculating manually the location of the widget, is there a better way to do this? Do you have some example with a generic widget like Calendar?

Not sure what it has to do with coordinates. Do you have the basic understanding of W3C web driver protocol and how the communication between clients and the server is designed? Otherwise we are talking about different things.

Eventually, this is the place for reporting server-related issues or feature requests. If you are not sure if this is an issue or want to ask more questions then consider using our forum instead: https://discuss.appium.io

**Comment by pmedinaNGTI** [comment]
> It is already pre-filled when creating a new issue. You can also check https://github.com/appium/appium/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
Thank you for the information, I created the ticket when I tap on 
![Screenshot 2024-02-08 at 14 28 13](https://github.com/appium/appium/assets/5577682/2b5aae54-24d8-4cce-9b70-e761ad5b6af9)

> Eventually, this is the place for reporting server-related issues or feature requests. If you are not sure if this is an issue or want to ask more questions then consider using our forum instead: https://discuss.appium.io/
I will make a post then on the forum, because the only thing I need is an example about to how to add a native widget on the phone's screen, because the following links do not work:
https://github.com/appium/appium/blob/master/test/functional/android/apidemos/touch/drag-specs.js#L53
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/AndroidGestureTest.java#L84-85

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
