### ISSUE TITLE
appium:autoAcceptAlerts: true does not work

### ISSUE THREAD

**Issue by awhisler** [appium/appium#19772]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adding the capability `"appium:autoAcceptAlerts": true` to wdio.config.js does not work

### Expected Behavior

Adding the capability `"appium:autoAcceptAlerts": true` should select clic the native popups according to: https://appium.github.io/appium-xcuitest-driver/6.1/reference/capabilities/

### Minimal Reproducible Example

- create wdio project
- add capabilities:
```
capabilities: [
    {
      // capabilities for local Appium web tests on iOS
      "appium:app": `${__dirname}/ios/xxx.app`,
      "platformName": "iOS",
      "appium:deviceName": "iPhone 15",
      "appium:platformVersion": "17.0",
      "appium:automationName": "XCUITest",
      "appium:autoAcceptAlerts": true,
    },
  ],
```

### Environment

- Operating system: Mac 14.3
- Appium server version (output of `appium --version`): 
- Appium driver(s) and their version(s): appium-xcuitest-driver 6.0.0
- Appium plugin(s) and their version(s): X
- Node.js version (output of `node --version`): 21.1.0
- `npm` version (output of `npm --version`): 10.2.0
- Real device or emulator/simulator: Simulator iPhone 15

### Further Information

Video with the capabilities `"appium:autoAcceptAlerts": true`
[Accept.mp4.zip](https://github.com/appium/appium/files/14226937/Accept.mp4.zip)

It does click 'allow once if I add the capabilities: `"appium:autoDismissAlerts": true` but I cannot do that because then that will dismiss the next popup for the camera module which I need it to accept.

**Comment by KazuCocoa** [comment]
It is https://github.com/appium/appium/issues/17754 

So the root cause is our accept alert tries to click the first button in the alert (as no "accept" button) and dismiss is the bottom. But only the location permission has "Precise" button on the top in newer iOS versions, so it behaves as "tapping Precise".

To customize the behavior, we could offer:

- Explicit alert handling https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-alert
- Customize alert selector logic: `acceptAlertButtonSelector`/`dismissAlertButtonSelector` https://appium.github.io/appium-xcuitest-driver/latest/reference/settings/

**Comment by awhisler** [comment]
@KazuCocoa Thank you! So I have seen people mention the acceptAlertButtonSelector logic but have tried myself and cannot figure out the syntax. Can you help me with that?

Also tried the settings:
```
const field = await $("**/XCUIElementTypeOther[`label == 'Don't Allow'`].click();
```
And:
```
const field = await $("XCUIElementTypeButton[label*='Don't Allow']").click();
```
Neither worked.

**Comment by KazuCocoa** [comment]
It is via settings api > acceptAlertButtonSelector

https://appium.github.io/appium-xcuitest-driver/latest/reference/settings/

**Comment by KazuCocoa** [comment]
Please use `buttonLabel` to explicitly set the target. As my above comment, basically automatic accept/dismiss is guessing basis as no such APIs in XCTest framework.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
