### ISSUE TITLE
bug: adbExecTimeout capability does not work

### ISSUE THREAD

**Issue by didental** [appium/appium#19785]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Based on the docker appium/appium image, I created an image that runs the test on an Android device using Appium-python-client library. Note that the Android device is connected remotely via STF.
In that image, the test is performed for about 5 minutes and the test is recorded. However, when it ends the video recording, an adbExecTimeout error occurs.
When I created the session, I set the corresponding capability value to 5 minutes (3*60*1000), but the error log shows that the timeout was set to 60 seconds.

- 세션 생성 시
  <img width="1765" alt="image" src="https://github.com/appium/appium/assets/18693233/5ffd17b9-aa59-4ced-ad3e-16f827ba59db">
- 타임아웃 에러 발생
  <img width="2119" alt="image" src="https://github.com/appium/appium/assets/18693233/68309479-fc11-45a8-9617-594f1881db07">

### Expected Behavior

It should wait for the adbExecTimeout value you set.
If it doesn't end after waiting, the log should be printed for the timeout time that was set.

### Minimal Reproducible Example

-

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

I've seen this issue; https://github.com/appium/appium/issues/18522.
But the code was changed. It does not pass options parameter (may include timeout info)
- https://github.com/appium/appium-android-driver/blob/master/lib/commands/recordscreen.js#L137

**Comment by mykola-mokhnach** [comment]
I see two ways of addressing it: simple and complicated.
A simple way would be to just hardcode the timeout to 5 minutes for this particular pull call
A complicated one would be to add the pullTimeout parameter to stop recording options. It would also require to update this data structure for all clients.

**Comment by mykola-mokhnach** [comment]
Also you probably don't want to change adbExecTimeout as it affects all other adb commands in the suite

**Comment by didental** [comment]
Thanks. 
I modified the `build/lib/commands/recordscreen.js` file in the `{appiumDir}/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver` as below this.
> (line 111) await this.adb.pull(pathOnDevice, relativePath, { timeout: 5 * 60 * 1000 });

And I found it works well :)

**Comment by mykola-mokhnach** [comment]
Feel free to make a PR and bump this timeout for the next driver release

**Comment by didental** [comment]
I think my change is not so good.
As you mentioned, adding a pullTimeout field and using it seems to be the right direction. However, if this field is added, does its value come from the capability at session created?

**Comment by mykola-mokhnach** [comment]
> I think my change is not so good. As you mentioned, adding a pullTimeout field and using it seems to be the right direction. However, if this field is added, does its value come from the capability at session created?

No it does not, although I don't think we need a separate capability for it. Setting it to a value that is large enough should cover needs of 99% of users
