### ISSUE TITLE
Unhandled endpoint: /session/A1804522-69EA-4741-A1F2-D73744F02462/touch/perform

### ISSUE THREAD

**Issue by richdownie-med** [appium/appium#19791]
I started seeing this error yesterday when using the appium TouchAction.tap method.  I did update to the latest version of xcuitest-driver 7.0.1   Any suggestions?

<img width="1315" alt="Screenshot 2024-02-15 at 10 04 13" src="https://github.com/appium/appium/assets/76957123/ebd70067-5249-47ee-81ce-e5f0efa79abc">

**Comment by mykola-mokhnach** [comment]
This is [expected](https://github.com/appium/appium-xcuitest-driver/releases/tag/v7.0.0)

Consider suing W3C actions instead or gesture extesnions

**Comment by smnchoi** [comment]
@richdownie-med @mykola-mokhnach 
Thank you for creating this issue.
For people like me who are new to appium, but had to use old scripts, are easy to miss these changes.
You guys saved my time to debug appium's crash issues. Thanks again!
