### ISSUE TITLE
[Feat]: testing with Android 15

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#19799]
- https://developer.android.com/about/versions/15/overview
- https://developer.android.com/about/versions/15/release-notes

I haven't tested anything yet but it looks like no big breaking changes in the release notes yet. We could do some testing in beta 1 or around, but beta 3 would be nice as https://developer.android.com/about/versions/15/overview#platform_stability

----

Review test note:

https://github.com/appium/ruby_lib_core/issues/535

Curren preview is handled as 14. This is expected since older version also so. Maybe beta will have proper one.

```
[ADB] Current device property 'ro.build.version.release': 14
```

In an early device case, it is handled as sdk level 14.

Currently  we may need to take a look location service
```
ERROR AppiumLibCoreTest::WebDriver::DeviceTest#test_location (205.82s)
Minitest::UnexpectedError:         Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s <device> shell am start-foreground-service -e longitude 100 -e latitude 100 -e altitude 75 io.appium.settings/.LocationService' exited with code 255'; Command output: Error: Not found; no service started.
        
            UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/kazu/Library/Android/sdk/platform-tools/adb -P 5037 -s <device> shell am start-foreground-service -e longitude 100 -e latitude 100 -e altitude 75 io.appium.settings/.LocationService' exited with code 255'; Command output: Error: Not found; no service started.
            
                at getResponseForW3CError (/Users/kazu/.nvm/versions/node/v16.15.1/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1118:9)
                at asyncHandler (/Users/kazu/.nvm/versions/node/v16.15.1/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:491:57)
            /Users/kazu/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.18.1/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
            /Users/kazu/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.18.1/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
            /Users/kazu/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.18.1/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
            /Users/kazu/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.18.1/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
            /Users/kazu/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.18.1/lib/selenium/webdriver/remote/http/default.rb:103:in `request'
            lib/appium_lib_core/common/base/http_default.rb:66:in `request'
            /Users/kazu/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.18.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
            /Users/kazu/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/selenium-webdriver-4.18.1/lib/selenium/webdriver/remote/bridge.rb:607:in `execute'
            lib/appium_lib_core/common/base/bridge.rb:303:in `set_location'
            lib/appium_lib_core/common/base/has_location.rb:47:in `location='
            lib/appium_lib_core/common/base/has_location.rb:67:in `set_location'
            test/functional/android/webdriver/device_test.rb:63:in `test_location'
```

**Comment by aaroncarry** [comment]
Android 15 beta 3 has been released, but I've encountered some issues when using Appium to perform certain operations on Android 15 beta 3. These operations work perfectly fine on Android 15 VanillaIceCream.

When I try to swipe the screen or a element, Appium throws an error: 
**Encountered internal error running command: io.appium.uiautomator2.common.exceptions.UnknownCommandException: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.**
<img width="1727" alt="image" src="https://github.com/appium/appium/assets/24429337/04bb2106-7ed8-4a70-af9d-521925c3c032">
![image](https://github.com/appium/appium/assets/24429337/382263c2-9187-46b6-a791-eefc5d0d7e37)


I am using an Android emulator for testing. After encountered this issue, I tested it on an Android 15 physical device, and it works fine on the physical device.

**OS**: MacOS 14.5 with M1 Pro chip
**Appium**: 2.0.1
**driver**: uiautomator2@2.29.3 [installed (NPM)

My Appium version is not the latest, but under the same Appium version, Android VanillaIceCream works fine.
I'm not sure if this is an issue with Android 15 beta 3 or with Appium, but I'm just sharing the situation I encountered.
thx.

**Comment by KazuCocoa** [comment]
It is not related to Android OS. I guess you used newer UIA2 driver over https://github.com/appium/appium-uiautomator2-driver/blob/master/CHANGELOG.md#300-2024-02-10 . Please attach the full appium server log as GIST.

**Comment by aaroncarry** [comment]
> It is not related to Android OS. I guess you used newer UIA2 driver over https://github.com/appium/appium-uiautomator2-driver/blob/master/CHANGELOG.md#300-2024-02-10 . Please attach the full appium server log as GIST.

thx for your reply.
Appium log: https://gist.github.com/aaroncarry/ab29f208a22f12b3a6498abb0662cbc1

From the log of Appium server, I also think that there is a problem with my Appium server or uiautomator2 driver, but what is confusing is that the same interface can work normally on Android VanillaIceCream.

**Comment by KazuCocoa** [comment]
I guess you tried newer UIA2 driver before for the device. You might need to uninstall UIA2 server from the device once.
```
2024-06-21 10:08:51:267 - [debug] [ADB] Running '/Users/aaron.lin/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
2024-06-21 10:08:51:434 - [debug] [ADB] The version code of the installed 'io.appium.uiautomator2.server' is greater than the application version code (175 > 129)
2024-06-21 10:08:51:434 - [debug] [AndroidUiautomator2Driver@6fed] Server packages status: [{"wasSigned":true,"installState":"newerVersionInstalled","appPath":"/Users/aaron.lin/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v5.12.2.apk","appId":"io.appium.uiautomator2.server"},{"wasSigned":true,"installState":"sameVersionInstalled","appPath":"/Users/aaron.lin/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk","appId":"io.appium.uiautomator2.server.test"}]
2024-06-21 10:08:51:434 - [AndroidUiautomator2Driver@6fed] Server packages are not going to be (re)installed
```

**Comment by aaroncarry** [comment]
> I guess you tried newer UIA2 driver before for the device. You might need to uninstall UIA2 server from the device once.
> 
> ```
> 2024-06-21 10:08:51:267 - [debug] [ADB] Running '/Users/aaron.lin/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell dumpsys package io.appium.uiautomator2.server'
> 2024-06-21 10:08:51:434 - [debug] [ADB] The version code of the installed 'io.appium.uiautomator2.server' is greater than the application version code (175 > 129)
> 2024-06-21 10:08:51:434 - [debug] [AndroidUiautomator2Driver@6fed] Server packages status: [{"wasSigned":true,"installState":"newerVersionInstalled","appPath":"/Users/aaron.lin/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-v5.12.2.apk","appId":"io.appium.uiautomator2.server"},{"wasSigned":true,"installState":"sameVersionInstalled","appPath":"/Users/aaron.lin/node_modules/appium-uiautomator2-driver/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk","appId":"io.appium.uiautomator2.server.test"}]
> 2024-06-21 10:08:51:434 - [AndroidUiautomator2Driver@6fed] Server packages are not going to be (re)installed
> ```

Yes, I tested this device with a newer version of uia2 driver  before encountering this issue.
 Due to the lower version of java-client in my testing framework, it caused some compatibility issues. Therefore, I downgraded the version of uia2 again.
 It looks like the problem has been identified. Thank you for troubleshooting.

**Comment by mykola-mokhnach** [comment]
There might be unexpected issues related to screen recording on Android 15: https://www.androidpolice.com/android-15-screen-sharing-protections/

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Is this task still relevant?

**Comment by KazuCocoa** [comment]
I don't have planned work right now. The observed error before as this description didn't occur on a real device thus I think we can close this for now. Let's do something needed when we get a new report
