### ISSUE TITLE
Failed to create session. An unknown server-side error occurred while processing the command. 

### ISSUE THREAD

**Issue by HUSBRO150** [appium/appium#19798]
Error
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s 7TD5T21402009689 install -r --no-incremental C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
![image](https://github.com/appium/appium-uiautomator2-driver/assets/104379197/bb2e97ba-3ee0-4683-8083-37669a84d4fd)

the follow is server log
C:\Users\mayn>appium --base-path /wd/hub
[Appium] Welcome to Appium v2.5.1
[Appium] Non-default server args:
[Appium] {
[Appium]   basePath: '/wd/hub'
[Appium] }
[Appium] The autodetected Appium home path: C:\Users\mayn\.appium
[Appium] Attempting to load driver uiautomator2...
[Appium] Requiring driver at C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\build\index.js
[Appium] AndroidUiautomator2Driver has been successfully loaded in 0.387s
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723/wd/hub
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium]        http://192.168.238.1:4723/wd/hub
[Appium]        http://192.168.58.1:4723/wd/hub
[Appium]        http://192.168.3.12:4723/wd/hub
[Appium]        http://127.0.0.1:4723/wd/hub (only accessible from the same host)
[Appium] Available drivers:
[Appium]   - uiautomator2@3.0.0 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"12","appium:appPackage":"com.tencent.mm","appium:appActivity":".ui.LauncherUI","appium:automationName":"UiAutomator2","appium:deviceName":"NOH-AN01","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","appium:platformVersion":"12","appium:appPackage":"com.tencent.mm","appium:appActivity":".ui.LauncherUI","appium:automationName":"UiAutomator2","appium:deviceName":"NOH-AN01","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[AppiumDriver@900f] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","appium:platformVersion":"12","appium:appPackage":"com.tencent.mm","appium:appActivity":".ui.LauncherUI","appium:automationName":"UiAutomator2","appium:deviceName":"NOH-AN01","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"12","appium:appPackage":"com.tencent.mm","appium:appActivity":".ui.LauncherUI","appium:automationName":"UiAutomator2","appium:deviceName":"NOH-AN01","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[AppiumDriver@900f] Event 'newSessionRequested' logged at 1708095635619 (23:00:35 GMT+0800 (中国标准时间))
[Appium] Attempting to find matching driver for automationName 'UiAutomator2' and platformName 'Android'
[Appium] The 'uiautomator2' driver was installed and matched caps.
[Appium] Will require it at C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver
[Appium] Requiring driver at C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\build\index.js
[AppiumDriver@900f] Appium v2.5.1 creating new AndroidUiautomator2Driver (v3.0.0) session
[AppiumDriver@900f] Checking BaseDriver versions for Appium and AndroidUiautomator2Driver
[AppiumDriver@900f] Appium's BaseDriver version is 9.5.2
[AppiumDriver@900f] AndroidUiautomator2Driver's BaseDriver version is 9.5.2
[AndroidUiautomator2Driver@d13f] Creating session with W3C capabilities: {
[AndroidUiautomator2Driver@d13f]   "alwaysMatch": {
[AndroidUiautomator2Driver@d13f]     "platformName": "Android",
[AndroidUiautomator2Driver@d13f]     "appium:platformVersion": "12",
[AndroidUiautomator2Driver@d13f]     "appium:appPackage": "com.tencent.mm",
[AndroidUiautomator2Driver@d13f]     "appium:appActivity": ".ui.LauncherUI",
[AndroidUiautomator2Driver@d13f]     "appium:automationName": "UiAutomator2",
[AndroidUiautomator2Driver@d13f]     "appium:deviceName": "NOH-AN01",
[AndroidUiautomator2Driver@d13f]     "appium:ensureWebviewsHavePages": true,
[AndroidUiautomator2Driver@d13f]     "appium:nativeWebScreenshot": true,
[AndroidUiautomator2Driver@d13f]     "appium:newCommandTimeout": 3600,
[AndroidUiautomator2Driver@d13f]     "appium:connectHardwareKeyboard": true
[AndroidUiautomator2Driver@d13f]   },
[AndroidUiautomator2Driver@d13f]   "firstMatch": [
[AndroidUiautomator2Driver@d13f]     {}
[AndroidUiautomator2Driver@d13f]   ]
[AndroidUiautomator2Driver@d13f] }
[AndroidUiautomator2Driver@d13f] The following provided capabilities were not recognized by this driver:
[AndroidUiautomator2Driver@d13f]   connectHardwareKeyboard
[AndroidUiautomator2Driver@d13f (a1e55946)] Session created with session id: a1e55946-30d5-4075-8d92-8b537772ee85
[ADB] Found 1 'build-tools' folders under 'D:\android-sdk-windows' (newest first):
[ADB]     D:\android-sdk-windows\build-tools\29.0.3
[ADB] Using 'adb.exe' from 'D:\android-sdk-windows\platform-tools\adb.exe'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 start-server'
[AndroidUiautomator2Driver@d13f (a1e55946)] Retrieving device list
[ADB] Trying to find connected Android devices
[ADB] Getting connected devices
[ADB] Connected devices: [{"udid":"7TD5T21402009689","state":"device"}]
[AndroidUiautomator2Driver@d13f (a1e55946)] Looking for a device with Android '12.0.0'
[ADB] Setting device id to 7TD5T21402009689
[ADB] Getting device platform version
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 12
[AndroidUiautomator2Driver@d13f (a1e55946)] Using device: 7TD5T21402009689
[ADB] Using 'adb.exe' from 'D:\android-sdk-windows\platform-tools\adb.exe'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 start-server'
[ADB] Setting device id to 7TD5T21402009689
[AndroidUiautomator2Driver@d13f (a1e55946)] Starting 'com.tencent.mm' directly on the device
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 31
[ADB] Getting device platform version
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 12
[ADB] Device API level: 31
[AndroidUiautomator2Driver@d13f (a1e55946)] Relaxing hidden api policy
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''
[AndroidUiautomator2Driver@d13f (a1e55946)] No app sent in, not parsing package/activity
[AndroidUiautomator2Driver@d13f (a1e55946)] Pushing settings apk to the device...
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell dumpsys package io.appium.settings'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('5.7.5' >= '5.7.5')
[ADB] There is no need to install/upgrade 'C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell dumpsys activity services io.appium.settings'
[AndroidUiautomator2Driver@d13f (a1e55946)] io.appium.settings is already running. There is no need to reset its permissions.
[Logcat] Starting logs capture with command: D:\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s 7TD5T21402009689 logcat -v threadtime
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell appops set io.appium.settings android:mock_location allow'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell "[ -e '/data/local/tmp/mock_apps.json' ] && echo __PASS__"'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell cat /data/local/tmp/mock_apps.json'
[AndroidUiautomator2Driver@d13f (a1e55946)] Forwarding UiAutomator2 Server port 6790 to local port 8201
[ADB] Forwarding system: 8201 to device: 6790
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 forward tcp:8201 tcp:6790'
[AndroidUiautomator2Driver@d13f (a1e55946)] No app capability. Assuming it is already on the device
[ADB] Getting install status for com.tencent.mm
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell pm path com.tencent.mm'
[ADB] Checking app cert for C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v7.0.0.apk
[ADB] Checking app cert for C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[ADB] Using 'apksigner.jar' from 'D:\android-sdk-windows\build-tools\29.0.3\lib\apksigner.jar'
[ADB] Starting apksigner: 'D:\\Program Files\\Java\\jdk1.8.0_101\\bin\\java.exe' -Xmx1024M -Xss1m -jar D:\\android-sdk-windows\\build-tools\\29.0.3\\lib\\apksigner.jar verify --print-certs C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk
[ADB] Starting apksigner: 'D:\\Program Files\\Java\\jdk1.8.0_101\\bin\\java.exe' -Xmx1024M -Xss1m -jar D:\\android-sdk-windows\\build-tools\\29.0.3\\lib\\apksigner.jar verify --print-certs C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v7.0.0.apk
[ADB] 'com.tencent.mm' is installed
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell am force-stop com.tencent.mm'
[ADB] apksigner stdout: Signer appium/appium-uiautomator2-driver#1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[ADB] Signer appium/appium-uiautomator2-driver#1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[ADB] Signer appium/appium-uiautomator2-driver#1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[ADB] Signer appium/appium-uiautomator2-driver#1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[ADB]
[ADB] sha256 hash did match for 'appium-uiautomator2-server-debug-androidTest.apk'
[ADB] 'C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is signed with the default certificate
[ADB] Getting install status for io.appium.uiautomator2.server.test
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell pm path io.appium.uiautomator2.server.test'
[ADB] 'io.appium.uiautomator2.server.test' is not installed
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell pm clear com.tencent.mm'
[AndroidUiautomator2Driver@d13f (a1e55946)] Performed fast reset on the installed 'com.tencent.mm' application (stop and clear)
[ADB] apksigner stdout: Signer appium/appium-uiautomator2-driver#1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[ADB] Signer appium/appium-uiautomator2-driver#1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[ADB] Signer appium/appium-uiautomator2-driver#1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[ADB] Signer appium/appium-uiautomator2-driver#1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[ADB]
[ADB] sha256 hash did match for 'appium-uiautomator2-server-v7.0.0.apk'
[ADB] 'C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v7.0.0.apk' is signed with the default certificate
[ADB] Getting package info for 'io.appium.uiautomator2.server'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell dumpsys package io.appium.uiautomator2.server'
[ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('7.0.0' >= '7.0.0')
[AndroidUiautomator2Driver@d13f (a1e55946)] Server packages status: [{"wasSigned":true,"installState":"sameVersionInstalled","appPath":"C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v7.0.0.apk","appId":"io.appium.uiautomator2.server"},{"wasSigned":true,"installState":"notInstalled","appPath":"C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk","appId":"io.appium.uiautomator2.server.test"}]
[AndroidUiautomator2Driver@d13f (a1e55946)] Server packages are going to be (re)installed
[AndroidUiautomator2Driver@d13f (a1e55946)] Full packages reinstall is going to be performed
[ADB] Uninstalling io.appium.uiautomator2.server
[ADB] Getting install status for io.appium.uiautomator2.server
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell pm path io.appium.uiautomator2.server'
[ADB] Uninstalling io.appium.uiautomator2.server.test
[ADB] Getting install status for io.appium.uiautomator2.server.test
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell pm path io.appium.uiautomator2.server.test'
[ADB] 'io.appium.uiautomator2.server' is installed
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell am force-stop io.appium.uiautomator2.server'
[ADB] 'io.appium.uiautomator2.server.test' is not installed
[ADB] io.appium.uiautomator2.server.test was not uninstalled, because it was not present on the device
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 uninstall io.appium.uiautomator2.server'
[ADB] 'adb uninstall io.appium.uiautomator2.server' command output: Success
[ADB] io.appium.uiautomator2.server was successfully uninstalled
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 version'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 features'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 help'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 help'
[ADB] The application at 'C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v7.0.0.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 install -r --no-incremental C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v7.0.0.apk'
[ADB] The application at 'C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 install -r --no-incremental C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk'
[ADB] The installation of 'appium-uiautomator2-server-v7.0.0.apk' took 7618ms
[ADB] Install command stdout: Performing Streamed Install
[ADB] Success
[AndroidUiautomator2Driver@d13f (a1e55946)] Deleting UiAutomator2 session
[AndroidUiautomator2Driver@d13f (a1e55946)] Deleting UiAutomator2 server session
[AndroidUiautomator2Driver@d13f (a1e55946)] Matched '/' to command name 'deleteSession'
[AndroidUiautomator2Driver@d13f (a1e55946)] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell am force-stop com.tencent.mm'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8201
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 forward --remove tcp:8201'
[AndroidUiautomator2Driver@d13f (a1e55946)] Restoring hidden api policy to the device default configuration
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[AppiumDriver@900f] Event 'newSessionStarted' logged at 1708095658511 (23:00:58 GMT+0800 (中国标准时间))
[AppiumDriver@900f] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'D:\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s 7TD5T21402009689 install -r --no-incremental C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
[AppiumDriver@900f]     at Timeout.<anonymous> (C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\teen_process\lib\exec.js:140:19)
[AppiumDriver@900f]     at listOnTimeout (node:internal/timers:573:17)
[AppiumDriver@900f]     at processTimers (node:internal/timers:514:7)
[HTTP] <-- POST /wd/hub/session 500 22908 ms - 1528
[HTTP]

i want to open the application wechat through the appium,but when i start the session ,it appears a problem of timeout. After i modify  the time ,it also didn't work.

**Comment by HUSBRO150** [comment]
> What happens when you call the below command directly? For example, a typical case is when the device shows up a security popup and blocks the installation command. Then, you would need to allow that, or configure the device's security/developer preferences.
> 
> ```
> [AppiumDriver@900f] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 install -r --no-incremental C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
> ```

after i called the comand directly, "Success" shows up. 
![image](https://github.com/appium/appium/assets/104379197/5750a270-76ed-44d8-a078-f5e1ee178531)
and i have configured the device's security/developer preferences.

~~~
from appium.webdriver import Remote  # 引入打开软件的包

# app的启动参数
desired_cap = {
    "platformName": "Android",  # 手机系统
    "platformVersion": "12",  # 手机系统版本
    "deviceName": 'NOH-AN01',  # 手机的名字，不会进行校验，但是没有会报错
    "appPackage": "com.tencent.mm",  # app包名
    "appActivity": ".ui.LauncherUI",  # app的启动页面
    "automationName": "UiAutomator2",
    "noReset": True,
}

driver = Remote(command_executor='http://127.0.0:4723/wd/hub', desired_capabilities=desired_cap)
~~~

this code is used to open the wechat windows, but when i ran the code,after i was required to install the apps(appium settings\io.appium.uiautomator2.server) and they were installed successfully ,there's nothing happened until timeout

**Comment by HUSBRO150** [comment]
just now, i find that wechat logged out. I think that it could happened after the code ran. Can i enter the wechat window by appium under the condition that wechat has logged in?

**Comment by KazuCocoa** [comment]
If that command succeeded in 20000ms, perhaps the command took a longer time to complete and thus it did not reach completion. Does it keep occurring?

I don't know about wechat's details.  Appium calls `am clean` command in a new session request, so `noReset: true` potentially could help to not clear the app local data. https://github.com/appium/appium-uiautomator2-driver

Asking such a general question in https://discuss.appium.io/ would help.

**Comment by HUSBRO150** [comment]
thank you very much.
it suddenly worked.

**Comment by leoShen917** [comment]
I'm having the same problem.

**Comment by chahongwu** [comment]
我今天遇到了类似的错误，提示相关权限问题的错误：
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.max.xiaoheihe' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command 'D:\\Android\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s 89879572 shell am start -n com.max.xiaoheihe/.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 255'; Command output: Exception occurred while executing 'start': java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.max.xiaoheihe/.MainActivity } from null (pid=18634, uid=2000) not exported from uid 10184 at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1059) at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:983) at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:672) at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1243) at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1215) at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:2958) at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:572) at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:201) at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97) at android.os.ShellCommand.exec(ShellCommand.java:38) at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:8668) at android.os.Binder.shellCommand(Binder.java:950)

**Comment by chahongwu** [comment]
最后我发现我填写appActivity的名字不是这个应用程序真实的活动名；比如之前通过这个命令得到的活动名字：apollo:/ $ dumpsys activity | grep "ResumedActivity"
    topResumedActivity=ActivityRecord{dd8658a u0 com.max.xiaoheihe/.MainActivity t318}
  ResumedActivity: ActivityRecord{dd8658a u0 com.max.xiaoheihe/.MainActivity t318}  活动名其实不是.MainActivity，最终我通过dumpsys package com.max.xiaoheihe找到了真正的活动名信息是android.intent.action.MAIN:
  64b6316 com.max.xiaoheihe/.SplashActivity filter f4e1497
    Action: "android.intent.action.MAIN"
    Category: "android.intent.category.LAUNCHER"，这里的.SplashActivit才是这个应用程序的真正活动名，这通常发生在某个APP有多个活动名导致

**Comment by han68** [comment]
在我更新了appnium对应的chromedriver版本之后，执行self.driver.switch_to.context("WEBVIEW_com.tencent.mm")这句代码的时候就会报错 from unknown error: com.tencent.mm is not installed on device 0000000f0f46b9ae，但是明明前面的步骤都对微信进行了操作，为什么会报没有安装微信的错误呢
