### ISSUE TITLE
The elements in the XCUIElementTypeTable cannot be loaded in the system above ios16, and the elements in the XCUIElementTypeTable in the system below iOS16 can be loaded normally

### ISSUE THREAD

**Issue by tinysheepyang** [appium/appium#19797]
macos 14.2 (23C64)
appium desktop server 1.22.3
Appium-Inspector-mac-2024.2.2
wda 7.0
xcuitest@7.0.1
appium 2.5.1
ios 17.3
xcode 15.2
<img width="801" alt="image" src="https://github.com/appium/appium/assets/13714343/bfd5ff41-8f7c-44c7-910b-a0e7c1029c24">

**Comment by mykola-mokhnach** [comment]
The source tree is loaded by XCTest. Unfortunately we cannot do much there. Please report your issue to Apple.
