### ISSUE TITLE
bug: --log-filters is broken while --config with log-filters worked

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#19822]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The same rule with `--log-filters` did not work while `--config` like below applied the filter rule properly.

as `filter.json`
```json
{
  "server": {
    "log-filters": [
      {
        "text": "XCUITest",
        "replacer": "bar"
      }
    ]
  }
}
```

e.g.

```
appium --config filter.json
```

worked but

```
[
      {
        "text": "XCUITest",
        "replacer": "bar"
      }
]
```
with `appium --log-filters filter.json` did not. Maybe parsing the given json file had an issue ( i guess)

### Expected Behavior

`--log-filters` should work as same as `--config`

### Minimal Reproducible Example

```
[
      {
        "text": "XCUITest",
        "replacer": "bar"
      }
]
```
json file and run `appium --log-filters filter.json`. Then if the local installed XCUITest driver, the XCUITest driver word in available drivers section should be replaced with `**SECURE**`

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
will take a look at this later

**Comment by jlipps** [comment]
is `--log-filters` supposed to support a json file? or just a json string?

**Comment by KazuCocoa** [comment]
according to the docs, it should be a json file. I tried both json file and just a valid json string, both did not work btw, but I think it should be json file as the documentation

**Comment by KazuCocoa** [comment]
hm, expected behavior is the `--log-filters` is parsed as JSON, but it was parsed as an arrary of `[{,"text": "XCUITest","replacer": "bar",}]`. The index 0 was `[{`, 1 was `"text": "XCUITest"`
for
```
[
      {
        "text": "XCUITest",
        "replacer": "bar"
      }
]
```
So something was wrongly parsed, but the same scheme definition parses `--config` properly

**Comment by KazuCocoa** [comment]
It looks like the json scheme was good for appium config's parse, but `--log-filters` usage needed to be JSON parsed once...? Existing test code for `loadRules` was good, but the input was not JSON parsed object in current master.
https://github.com/appium/appium/compare/log-filters?expand=1 is a piece of code that works expectedly at leas.
It could be a temporary fix potentially... but we may need to have better fix. Ideally updating scheme for both usage...?
