### ISSUE TITLE
bug: Server crash for iOS real device

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#19834]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to create a session on real ios device.

### Expected Behavior

Should be able to create a session on real device.

### Minimal Reproducible Example

https://gist.github.com/saikrishna321/a5c664a82b9b8778a6a1d5e16d297799

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.5.1
- Appium driver(s) and their version(s):
```
❯ appium driver list
✔ Listing available drivers
- xcuitest@7.1.2 [installed (npm)]
```
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): `v18`
- `npm` version (output of `npm --version`): `8.19.2`
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS
- Real device or emulator/simulator: Real

### Link to Appium Logs

https://gist.github.com/saikrishna321/a5c664a82b9b8778a6a1d5e16d297799

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by saikrishna321** [comment]
@KazuCocoa @mykola-mokhnach Sorry for late response. I have my the gist with logs. 

I already have WDA installed on device.

**Comment by mykola-mokhnach** [comment]
This issue might be resolved by https://github.com/appium/appium-xcuitest-driver/pull/2355
