### ISSUE TITLE
WebDriverAgent crashes after running for some time

### ISSUE THREAD

**Issue by rohanp-91** [appium/appium#19849]
### Do I have the most recent component updates?

- [ ] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Before running appium server and tests, I build the WebDriverAgent and install it on the target simulator device. Within appium capabilities, I provide the webDriverAgentUrl as http://localhost:8081. In my script, I even ping http://localhost:8081/status to make sure that the webDriverAgent has started listening and only then start the tests. 

But, on running, from the XCUITest Driver logs (find the logs here: https://gist.github.com/rohanp-91/a2d9c040aadf266992a4edaed395cd9c), it still gives ECONNREFUSED, even though seconds ago I verified that the WebDriverAgent is listening. Below is the script I use to verify:

```
agentUrl="http://localhost:8100/status"
while true; do
    response_code=$(curl -s -o /dev/null -w "%{http_code}" $agentUrl)
    echo -e $(date) "$debugTag Response code from http://localhost:8100/status: $response_code"
    if [ $response_code -eq 200 ]; then
        echo -e $(date) "$debugTag Appium WebDriver Agent is now listening on http://localhost:8100"
        break
    else
        echo -e $(date) "$debugTag Appium WebDriver Agent is not yet listening on http://localhost:8100. Waiting for it to start..."
        sleep 5
    fi
  done
```

Also, here is the log from the WebDriverAgent:

```
Command line invocation:
    /Applications/Xcode_15.2.app/Contents/Developer/usr/bin/xcodebuild test-without-building -project ../../node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath ../../wda_build -destination id=7E8AA23E-DC8D-4549-904A-7AEEC1DA5578 IPHONEOS_DEPLOYMENT_TARGET=17.2 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO

User defaults from command line:
    IDEDerivedDataPathOverride = /Users/runner/work/1/s/wda_build
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    COMPILER_INDEX_STORE_ENABLE = NO
    GCC_TREAT_WARNINGS_AS_ERRORS = 0
    IPHONEOS_DEPLOYMENT_TARGET = 17.2

2024-03-02 19:27:37.184784+0000 WebDriverAgentRunner-Runner[32244:121630] [Default] Running tests...
Test Suite 'All tests' started at 2024-03-02 19:28:45.046.
Test Suite 'WebDriverAgentRunner.xctest' started at 2024-03-02 19:28:45.047.
Test Suite 'UITestingUITests' started at 2024-03-02 19:28:45.047.
    t =      nans Suite Set Up
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s Start Test at 2024-03-02 19:28:45.703
    t =     0.01s Set Up
2024-03-02 19:28:45.708034+0000 WebDriverAgentRunner-Runner[32244:121630] Built at Mar  2 2024 19:21:52
2024-03-02 19:28:45.732125+0000 WebDriverAgentRunner-Runner[32244:121630] ServerURLHere->http://192.168.64.23:8100<-ServerURLHere
2024-03-02 19:28:46.824572+0000 WebDriverAgentRunner-Runner[32244:121630] Using singleton test manager
2024-03-02 19:30:46.572641+0000 WebDriverAgentRunner-Runner[39649:140922] [Default] Running tests...

Restarting after unexpected exit, crash, or test timeout in -[UITestingUITests testRunner]; summary will include totals from previous launches.

Test Suite 'Selected tests' started at 2024-03-02 19:31:10.196.
Test Suite 'WebDriverAgentRunner.xctest' started at 2024-03-02 19:31:10.198.
Test Suite 'UITestingUITests' started at 2024-03-02 19:31:10.198.
    t =      nans Suite Set Up
Test Suite 'UITestingUITests' failed at 2024-03-02 19:31:10.254.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.056) seconds
Test Suite 'WebDriverAgentRunner.xctest' failed at 2024-03-02 19:31:10.255.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.057) seconds
Test Suite 'Selected tests' failed at 2024-03-02 19:31:10.255.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.000 (0.060) seconds
2024-03-02 19:32:18.526 xcodebuild[26000:104474] [MT] IDETestOperationsObserverDebug: 510.522 elapsed -- Testing started completed.
2024-03-02 19:32:18.526 xcodebuild[26000:104474] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2024-03-02 19:32:18.526 xcodebuild[26000:104474] [MT] IDETestOperationsObserverDebug: 510.522 sec, +510.522 sec -- end

Test session results, code coverage, and logs:
	/Users/runner/work/1/s/wda_build/Logs/Test/Test-WebDriverAgentRunner-2024.03.02_19-23-47-+0000.xcresult

Failing tests:
	-[UITestingUITests testRunner]

** TEST EXECUTE FAILED **

Testing started
```

### Expected Behavior

WebDriverAgent should be running and should not crash. ECONNREFUSED should not be thrown.

### Minimal Reproducible Example

N/A

### Environment

- Operating system: macOS 13.x
- Appium server version (output of `appium --version`): 2.0.1
- Appium driver(s) and their version(s):
-  XCUITestDriver 4.35.0
- Appium plugin(s) and their version(s): none
- Node.js version (output of `node --version`): 16.20.2
- `npm` version (output of `npm --version`): yarn 1.22.19
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: XCode 15.2 & iOS 17.2 (iphone 15 pro max simulator)
- Real device or emulator/simulator: simulator

**Comment by mykola-mokhnach** [comment]
> Restarting after unexpected exit, crash, or test timeout in -[UITestingUITests testRunner]; summary will include totals from previous launches.

Please provide device logs for this time range

**Comment by rohanp-91** [comment]
@mykola-mokhnach I'll provide that tomorrow. But I have a constant heartbeat check which keeps pinging http://localhost:8100/status every 2 seconds. I can see that the response changes from 200 to 000 immediately after this:

```
Sun Mar  3 08:03:35 UTC 2024 (DEBUG) Response code from http://localhost:8100/status: **200**
2024-03-03 08:03:35:520 - [debug] [simctl] Error running 'get_app_container': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
The operation couldn’t be completed. No such file or directory
No such file or directory
Sun Mar  3 08:03:37 UTC 2024 (DEBUG) Response code from http://localhost:8100/status: **200**
Sun Mar  3 08:03:40 UTC 2024 (DEBUG) Response code from http://localhost:8100/status: **000**

```
I think in the beginning, maybe because I have some reset option enabled, it tries to uninstall my app from simulator. But since the app is not there in the beginning, the get_app_container fails? I think this causes WDA to restart or something. 

Soon after this I can see the following:

```
App 'com.company.CompanyApp-DF' is not installed on the device yet
2024-03-03 08:03:57:261 - [debug] [XCUITest] Installing '/Users/runner/runners/3.234.0/CompanyApp/ios/output/iphonesimulator/Dogfood/build.sym/Dogfood-iphonesimulator/CompanyApp.app' on Simulator with UUID '7E8AA23E-DC8D-4549-904A-7AEEC1DA5578'...
Sun Mar  3 08:03:58 UTC 2024 (DEBUG) Response code from http://localhost:8100/status: 000
2024-03-03 08:04:00:449 - [debug] [XCUITest] The app has been installed successfully.
```

On a different note, what I am trying here is below:

1) Launch simulator
2) Build WDA (use prebuiltWDA cap)
3) Start wda using xcode test-without-building command (also set webDriverAgentUrl cap)

 And then start appium server and tests.

In this case, if I start WDA by myself, is it not recommended to do so? And can I not have any reset caps set if I do this?

**Comment by mykola-mokhnach** [comment]
Providing webDriverAgentUrl means you manage WDA building and running completely on your own. It must not be mixed with any other capabilities related to how WDA is prepared.

**Comment by rohanp-91** [comment]
This is how I build and start the WDA:

```
# Start WDA
  echo -e $(date) "$debugTag Start Web Driver Agent"
  WDA_LOG_FILE_PATH="$wda_log_file_path" node -e "require('./__tests__/appium/library/get-ios-devices').startWebDriverAgent()" &
  sleep 30

  # Wait for WDA to start
  while true; do
    response_code=$(curl -s -o /dev/null -w "%{http_code}" $agentUrl)
    echo -e $(date) "$debugTag Response code from http://localhost:8100/status: $response_code"
    if [ $response_code -eq 200 ]; then
        echo -e $(date) "$debugTag Appium WebDriver Agent is now listening on http://localhost:8100"
        break
    else
        echo -e $(date) "$debugTag Appium WebDriver Agent is not yet listening on http://localhost:8100. Waiting for it to start..."
        sleep 5
    fi
  done
```

The node functions are below:

```
const buildWebDriverAgent = () => {
  const { udid } = getDeviceIdAndState();
  const buildCommand = `xcodebuild build-for-testing -project ../../node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -derivedDataPath ../../wda_build -scheme WebDriverAgentRunner -destination id=${udid} IPHONEOS_DEPLOYMENT_TARGET=${IOS_VERSION} GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO`;

  try {
    execSync(buildCommand, { stdio: 'ignore' });
  } catch (error) {
    console.error('FAILED TO BUILD WDA: ', error);
  }
}

const startWebDriverAgent = () => {
  const { udid } = getDeviceIdAndState();
  const startCommand = `xcodebuild test-without-building -project ../../node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath ../../wda_build -destination id=${udid} IPHONEOS_DEPLOYMENT_TARGET=${IOS_VERSION} GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO`;

  const logFilePath = process.env.WDA_LOG_FILE_PATH;

  try {
    const stdoutStream = fs.openSync(logFilePath, 'a');
    execSync(startCommand, { stdio: ['ignore', stdoutStream, stdoutStream] });
  } catch (error) {
    console.error('FAILED TO START WDA: ', error);
  }
}
```

I was passing in the following caps:

```
    "platformName": IOS_PLATFORM_NAME,
    "allowW3C": true,
    "appium:automationName": AUTOMATION_NAME,
    "appium:platformVersion": IOS_PLATFORM_VERSION,
    "appium:deviceName": 'iPhone15ProMax',
    "appium:app": IOS_APP_PATH,
    "appium:appPackage": IOS_APP_PACKAGE,
    "appium:fullReset": false,
    "appium:noReset": true,
    "appium:showIOSLog": false,
    "appium:showXcodeLog": true,
    "appium:allowTouchIdEnroll": true,
    "appium:wdaLocalPort": 8100,
    "appium:processArguments": { "args": processArgs, "env": {} },
    "appium:language": 'en',
    "appium:usePrebuiltWDA": true,
    "appium:derivedDataPath": '../../wda_build',
    "appium:webDriverAgentUrl": 'http://localhost:8100',
    "appium:wdaLaunchTimeout": 300000,
    "appium:wdaConnectionTimeout": 60000,
    "appium:wdaStartupRetryInterval": 5000,
    "appium:wdaStartupRetries": 2,
```


It seems like WDA is not stable. Just to check, does this have anything to do with architecture? I am running it on Intel Macs.

**Comment by rohanp-91** [comment]
@mykola-mokhnach @KazuCocoa Also, to confirm, if I set the webDriverAgentUrl cap, appium will not attempt to launch WDA again, right? Cause I was testing out locally, and it seems, I get the same error if I try to start 2 WDAs on the same device with same port config, etc. Like, from the above script, if I run the startWebDriverAgent twice without killing the first one, I get similar errors.

**Comment by KazuCocoa** [comment]
> appium will not attempt to launch WDA again, right?

Yes. Appium believes the given `webDriverAgentUrl` is everything to communicate with WDA. https://appium.github.io/appium-xcuitest-driver/latest/guides/attach-to-running-wda/
https://appium.github.io/appium-xcuitest-driver/latest/guides/wda-custom-server/#wda-startup-via-code
It means Appium does not configure anything for Appium/WDA usually Appium does with `wdaLocalPort` for example.

How did you set the listening port, `8100` by default, for WDA? Appium sets `USE_PORT` as https://github.com/appium/WebDriverAgent/blob/21f9af8b51dd05aa041ee26b7496445a14f5322e/lib/xcodebuild.js#L275C7-L275C15 for xcodebuild behind the `wdaLocalPort` caps to configure WDA. Perhaps you might need to set the env var to the xcodebuild to configure the local port for xcodebuild/WDA. Without this, at least your local WDA on the same host might get conflict with each listening ports.

I wonder if multiple xcodebuild on the same machine also works without issues. I met xcodebuild issue long before in parallel xcodebuild process run on the same host. I haven't used this method so long, so I don't know the stability.

**Comment by mykola-mokhnach** [comment]
> I get the same error if I try to start 2 WDAs on the same device with same port config

Such scenario is not supported. You must only run a single WDA instance at a time.

Also, again, all the caps that are related to WDA startup, like usePrebuiltWDA, wdaLaunchTimeout, wdaStartupRetries will be ignored if webDriverAgentUrl is provided

**Comment by rohanp-91** [comment]
@KazuCocoa Sorry, I'm slightly confused about the port thing. 

But what I'm doing is:

I saw from appium logs that appium starts the webdriver agent using the following command:

`xcodebuild test-without-building -project ../../node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath ../../wda_build -destination id=${udid} IPHONEOS_DEPLOYMENT_TARGET=${IOS_VERSION} GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO`

So, instead of appium doing, I do it myself before starting appium server and then provide the webDriverAgentUrl cap. 

Is something wrong with this approach?

**Comment by mykola-mokhnach** [comment]
> So, instead of appium doing, I do it myself before starting appium server and then provide the webDriverAgentUrl cap.

It depends on what your usage scenario is and what you want to achieve with that. Maybe just hire a consultant to explain all differences between different approaches.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
