### ISSUE TITLE
bug: <title>Memory leak

### ISSUE THREAD

**Issue by Yesisyes** [appium/appium#19854]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My computer is a Mac Mini. I run appium --session-override in the terminal. I created three threads that were constantly searching for UI elements and typing characters into UI input fields. I noticed that the memory size of my terminal increased over time and even overwhelmed my Mac Mini memory after one night. One terminal eventually reached 16GB memory size. Why is that?

### Expected Behavior

No memory leak

### Minimal Reproducible Example

    def select_word(self, rule_1, rule_2, package_name, devices_no):
        text_set = set()
        text_no = []
        element = self.driver.find_elements(AppiumBy.XPATH, f'//*[@enabled="true" and normalize-space(@{rule_1})!=""]')
        if len(element) >= 25:
            time.sleep(self.total_timeout - time.time())
            return True
        elif 0 < len(element) < 25:
            for i in element:
                w = i.get_attribute(f'{rule_2}')
                ww = w.lower().replace(' ', '')
                if ww in self.actions_text:
                    self.weights.update({w: self.weights[ww]})
                    text_set.add(w)
                else:
                    text_no.append(w)
            if not text_set:
                if self.step == 1:
                    self.status = True
                    pic_path = create_dir_today(Config.move_file)
                    screen(f'/sdcard/{package_name}.png', pic_path, devices_no)
            else:
                max_weight_string = max(text_set, key=lambda x: self.weights.get(x, 0))
                self.driver.find_element(AppiumBy.XPATH,
                                         f'//*[@enabled="true" and @{rule_2}="{max_weight_string}"]').click()
                time.sleep(2)
            return True
        else:
            time.sleep(1)
            return False

    def app_click(self, package_name, devices_no):
        input_select = len(self.driver.find_elements(AppiumBy.XPATH, "//android.widget.EditText"))
        if input_select:
            for n in range(input_select):
                self.driver.find_elements(AppiumBy.XPATH, "//android.widget.EditText")[n].clear()
                time.sleep(1)
                self.driver.find_elements(AppiumBy.XPATH, "//android.widget.EditText")[n].send_keys('dafq4464@gmail.com')
                time.sleep(1)
        if self.select_word('text', 'text', package_name, devices_no):
            pass
        else:
            self.select_word('description', 'content-desc', package_name, devices_no)

### Environment

- Operating system:
- Appium server version (output of `appium --version`):appium@2.5.1
- Appium driver(s) and their version(s):uiautomator2@3.0.1
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Please attach the following information to your report:
- It is not clear which process is leaking. Please make a heap snapshot of the leaking process when it uses unusually high amount of memory and share it.
- After identifying which process is leaking try to isolate the leaking API, e.g. remove all other calls from your script but only one that creates leaks.

**Comment by Yesisyes** [comment]
During testing, the app under test changed constantly. New apps are being installed and uninstalled all the time. But each simulator only tests one app

**Comment by Yesisyes** [comment]
> Please attach the following information to your report:
> 
> * It is not clear which process is leaking. Please make a heap snapshot of the leaking process when it uses unusually high amount of memory and share it.
> * After identifying which process is leaking try to isolate the leaking API, e.g. remove all other calls from your script but only one that creates leaks.

Sorry, I don't know how to make a heap snapshot。But, when I just use appium to connect to these simulators and exit the connection, the memory doesn't change. It's only when I'm constantly running code looking for interface elements that the memory increases.

**Comment by mykola-mokhnach** [comment]
It has nothing to do with terminal. there are basically two processes that might consume the memory: the client (Python) or the server (Node.js). You need to figure out which one does this.
If the server then follow https://nodejs.org/en/learn/diagnostics/memory/using-heap-snapshot
If the client - https://github.com/humu/heapprof

> It's only when I'm constantly running code looking for interface elements that the memory increases.

Unfortunately this is not helpful. The code above contains too many API calls.

**Comment by Yesisyes** [comment]
I found a very strange place. After my emulator connected to the appium server normally to generate a session ID, running the code cs = driver.find_elements(AppiumBy.XPATH, '//.[@text=" 系统界面无响应"]') immediately gave me an error that it could not find the session ID. Isn't it normal to return an empty list if the UI element can't be found? Below is my appium log
[appium.log](https://github.com/appium/appium/files/14489205/appium.log)

**Comment by Yesisyes** [comment]
> It has nothing to do with terminal. there are basically two processes that might consume the memory: the client (Python) or the server (Node.js). You need to figure out which one does this. If the server then follow https://nodejs.org/en/learn/diagnostics/memory/using-heap-snapshot If the client - https://github.com/humu/heapprof
> 
> > It's only when I'm constantly running code looking for interface elements that the memory increases.
> 
> Unfortunately this is not helpful. The code above contains too many API calls.

I noticed that my terminal memory kept increasing when appium searched for phone UI elements and kept getting the above error. I think if I can figure out why this error is happening, I should be able to stop the terminal memory from growing.

**Comment by Yesisyes** [comment]
I noticed that the first time the appium server connected to the emulator, it didn't automatically execute the appium test script as it did when I used Appium version 2.2.1. The log output to the [Instrumentation] IO. Appium. Uiautomator2. Server test. AppiumUiAutomator2Server: is over.

**Comment by mykola-mokhnach** [comment]
> I found a very strange place. After my emulator connected to the appium server normally to generate a session ID, running the code cs = driver.find_elements(AppiumBy.XPATH, '//.[@text=" 系统界面无响应"]') immediately gave me an error that it could not find the session ID. Isn't it normal to return an empty list if the UI element can't be found? Below is my appium log [appium.log](https://github.com/appium/appium/files/14489205/appium.log)

This might happen when the server crashes unexpectedly. Check the logcat output, it may contain more details.

**Comment by Yesisyes** [comment]
> > I found a very strange place. After my emulator connected to the appium server normally to generate a session ID, running the code cs = driver.find_elements(AppiumBy.XPATH, '//.[@text=" 系统界面无响应"]') immediately gave me an error that it could not find the session ID. Isn't it normal to return an empty list if the UI element can't be found? Below is my appium log [appium.log](https://github.com/appium/appium/files/14489205/appium.log)
> 
> This might happen when the server crashes unexpectedly. Check the logcat output, it may contain more details.

I uninstalled everything about appium from my Mac Mini. Since i had to sudo npm i-g appium to install it, I set the npm environment variable again. This allowed me to install npm i-g appium. Then I tested again and everything worked fine.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we can do to address this issue without having the data requested above. Thus closing
