### ISSUE TITLE
[Feat]: add sessions in `/status` endpoint

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#19857]
```
{
  "ready": true or false
  "message": "current string",
  "sessions": {the same body with /sessions}
}
```

The `sessions` format would be the same as `/sessions` endpoint.
```
[
  {"id": "session id", "capabilities": {capabilities}}.
  {"id": "session id2", "capabilities": {capabilities2}}
]
```

since `/sessions` is deprecated as W3C capability

(Or the `sessions` key would be `active_sessions`?)

References:
https://github.com/appium/appium/pull/19851
https://github.com/appium/appium/issues/19856

**Comment by mykola-mokhnach** [comment]
I think this might be a serious security issue. Also it us usually not a good idea to add too much stuff into the /status API as it gets called frequently to verify server liveness by multiple clients

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/19856 seems like a better idea for me because:
- it is secure, only people that need sessions info to be exposed are going to enable the plugin
- we don't put unnecessary payload/add performance hit on the /status API

**Comment by eglitise** [comment]
Hmm.... I am inclined to agree on both points here. Current `/sessions` can indeed be treated a security issue, and if `/status` does get called often, it is definitely beneficial to keep its response compact.

**Comment by KazuCocoa** [comment]
Ordinary this idea is for https://github.com/appium/appium/issues/19856
