### ISSUE TITLE
During the use of iOS automated test cases, there were multiple instances of equipment farm issues with the test cases

### ISSUE THREAD

**Issue by xiaoliangjia111** [appium/appium#19850]
During the use of iOS automated test cases, there were no issues with a single test case, but there were issues with device farm links when using multiple test cases in iOS. Please refer to the logs for details

e.tech' is not running in foreground after 5.00 seconds
[Xcode] 
[Xcode] 2024-03-04 13:47:43.406582+0800 WebDriverAgentRunner-Runner[9532:2418462] Getting the most recent active application (out of 1 total items)
[Xcode] 
[Xcode]     t =   683.27s Find the Application 'com.apple.springboard'
[Xcode] 
[Xcode]     t =   683.28s     Requesting snapshot of accessibility hierarchy for app with pid 59
[Xcode] 
[debug] [XCUITestDriver@2a10 (0bef1864)] Got response with status 200: {"value":{"sessionId":"9C5E3A89-A78D-48F0-907E-4B1749B92826","capabilities":{"device":"iphone","browserName":" ","sdkVersion":"14.0","CFBundleIdentifier":"com.apple.springboard"}},"sessionId":"9C5E3A89-A78D-48F0-907E-4B1749B92826"}
[XCUITestDriver@2a10 (0bef1864)] Determined the downstream protocol as 'W3C'
[debug] [XCUITestDriver@2a10 (0bef1864)] Event 'wdaSessionStarted' logged at 1709531263431 (13:47:43 GMT+0800 (China Standard Time))
[debug] [XCUITestDriver@2a10 (0bef1864)] Event 'wdaStarted' logged at 1709531263431 (13:47:43 GMT+0800 (China Standard Time))
[debug] [BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
[debug] [BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
[AppiumDriver@256c] New XCUITestDriver session created successfully, session 0bef1864-1a14-4e97-af5c-9c98cb1f7b19 added to master session list
[debug] [AppiumDriver@256c] Event 'newSessionStarted' logged at 1709531263433 (13:47:43 GMT+0800 (China Standard Time))
[device-farm] 馃摫 Updating Device 00008020-0001101A2284003A with session ID 0bef1864-1a14-4e97-af5c-9c98cb1f7b19
[debug] [XCUITestDriver@2a10 (0bef1864)] Cached the protocol value 'W3C' for the new session 0bef1864-1a14-4e97-af5c-9c98cb1f7b19
[debug] [XCUITestDriver@2a10 (0bef1864)] Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"IOS","account":"lhtest02","app":"/Users/sxw/Documents/ios/707/build/lehai-live_20240229_1457_v3.7.7_remote.ipa","appActivity":"com.showself.ui.LoadingActivity","appPackage":"com.lehai.ui","autoGrantPermissions":true,"automationName":"XCUITest","clearSystemFiles":true,"deviceOrientation":"portrait","legionaccount":"hxcs014","legionpassword":"hxcs014","maxTypingFrequency":10,"notlegionaccount":"hxcs016","notlegionpassword":"hxcs016","password":"lh123456","preventWDAAttachments":true,"shouldUseSingletonTestManager":false,"showXcodeLog":true,"simpleIsVisibleCheck":true,"testroom":"8040558","udids":"00008020-0001101A2284003A","useNewWDA":false,"usePrebuiltWDA":true,"wdaConnectionTimeout":80000,"wdaLaunchTimeout":80000,"udid":"00008020-0001101A2284003A","deviceName":"CS001鐨刬Phone","platf...
[HTTP] <-- POST /wd/hub/session 200 129521 ms - 1257
[HTTP] 
No tvOS simulators found!
[HTTP] --> DELETE /wd/hub/session/0bef1864-1a14-4e97-af5c-9c98cb1f7b19
[HTTP] {}
[debug] [XCUITestDriver@2a10 (0bef1864)] Calling AppiumDriver.deleteSession() with args: ["0bef1864-1a14-4e97-af5c-9c98cb1f7b19"]
[AppiumDriver@256c] Plugins which can handle cmd 'deleteSession': device-farm
[AppiumDriver@256c] Plugin device-farm is now handling cmd 'deleteSession'
Found device with udid 00008020-0001101A2284003A to unblock with filter {"session_id":"0bef1864-1a14-4e97-af5c-9c98cb1f7b19"}
[device-farm] 馃摫 Unblocking the device that is blocked for session 0bef1864-1a14-4e97-af5c-9c98cb1f7b19
[AppiumDriver@256c] Executing default handling behavior for command 'deleteSession'
[debug] [AppiumDriver@256c] Event 'quitSessionRequested' logged at 1709531268622 (13:47:48 GMT+0800 (China Standard Time))
[AppiumDriver@256c] Removing session 0bef1864-1a14-4e97-af5c-9c98cb1f7b19 from our master session list
[debug] [XCUITestDriver@2a10 (0bef1864)] Matched '/session/0bef1864-1a14-4e97-af5c-9c98cb1f7b19' to command name 'deleteSession'
[debug] [XCUITestDriver@2a10 (0bef1864)] Proxying [DELETE /session/0bef1864-1a14-4e97-af5c-9c98cb1f7b19] to [DELETE http://127.0.0.1:51130/session/9C5E3A89-A78D-48F0-907E-4B1749B92826] with no body
[Xcode]     t =   688.63s Terminate com.lhlive.tech:9573
[Xcode] 
[Xcode]     t =   689.70s Wait for com.lhlive.tech to become Not Running
[Xcode] 
[debug] [XCUITestDriver@2a10 (0bef1864)] Got response with status 200: {"value":null,"sessionId":null}
[DevCon Factory] Releasing connections for 00008020-0001101A2284003A device on any port number
[DevCon Factory] Found cached connections to release: ["00008020-0001101A2284003A:51130"]
[DevCon Factory] Releasing the listener for '00008020-0001101A2284003A:51130'
[debug] [iProxy@00008020:51130] Closing the connection
[debug] [DevCon Factory] Cached connections count: 0
[debug] [XCUITest] Did not find the temporary XCTest logs root at '/var/folders/yn/8wwxlcq162nb23pl45yvqj2c0000gn/T/com.apple.dt.XCTest*/'
[XCUITest] There is no /Users/sxw/Library/Developer/Xcode/DerivedData/WebDriverAgent-00008020-0001101A2284003A/Logs folder, so not cleaning files
[debug] [AppiumDriver@256c] Event 'quitSessionFinished' logged at 1709531269752 (13:47:49 GMT+0800 (China Standard Time))
[debug] [AppiumDriver@256c] Received response: null
[debug] [AppiumDriver@256c] But deleting session, so not returning
[debug] [AppiumDriver@256c] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/0bef1864-1a14-4e97-af5c-9c98cb1f7b19 200 1141 ms - 14
[HTTP] 
FAILED CONFIGURATION: @BeforeMethod setUp
java.lang.NullPointerException
	at com.appium.pages.LoginPage.<init>(LoginPage.java:23)
	at com.appium.tests.LoginTest.setUp(LoginTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[appium_logs的副本.txt](https://github.com/appium/appium/files/14477069/appium_logs.txt)
![企业微信截图_a824d472-b292-4a37-8229-a1b6adb1016a](https://github.com/appium/appium/assets/56531549/2ead4dc1-5bc5-4f9b-a0b4-0e90db1ec6d8)
![企业微信截图_e52d5196-5e24-492c-ad9c-12e179e11c26](https://github.com/appium/appium/assets/56531549/30a3ceb6-e59a-40f4-adfa-20d5066161bc)

**Comment by mykola-mokhnach** [comment]
Please report your issue to the plugin developer
