### ISSUE TITLE
iOS : Unable to see the first element in a Xamarin forms List view while running the automated UI iOS tests using Appium 

### ISSUE THREAD

**Issue by anubPep122** [appium/appium#19865]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Upgraded to Xamarin.Forms v5.0.0.2622 and started observing the below issue
Element with property in Xamarin forms "ListViewCachingStrategy.RetainElement" , the first element is missing from the list view while running the tests in iOS using appium.

Inbetween the tests if we remove the WDA and tried the same scenario, it works as expected.
The first element was displayed when working with xamarin forms (v4.7.0.1351) and it is observed with only the current version.

Manually trying the same scenario does not have any issues , Elements are displayed as expected, issue is observed only through automation

### Expected Behavior

The first element should be displayed always on the Xamarin forms list view through UI Automation tests.

### Minimal Reproducible Example

This issue is observed on the latest Xamarin forms (5.0) List View with elements having property  "ListViewCachingStrategy.RetainElement"
For reference a similar ticket was created with Xamarin forms as well https://github.com/xamarin/Xamarin.Forms/issues/15354

### Environment

- Operating system: Mac/iOS
- Appium server version (output of `appium --version`): 2.5
- Appium driver(s) and their version(s): XCUITest driver 6.0
- Appium plugin(s) and their version(s): NA
- Node.js version (output of `node --version`): 
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem: Xamarin.Forms v4.7.0.1351: Working 
- Platform and version under test: iOS 16.3
- Real device or emulator/simulator: Real device

### Further Information

 https://github.com/xamarin/Xamarin.Forms/issues/15354

**Comment by mykola-mokhnach** [comment]
you can only see what's exposed to the accessibility. WDA sees the same page tree that XCTest. We cannot influence which elements are present there and which aren't.

**Comment by anubPep122** [comment]
@mykola-mokhnach  Could you please elaborate this ? "WDA sees the same page tree that XCTest. We cannot influence which elements are present there and which aren't.",  
Only when WDA agent is installed and running we are unable to see the first element in List view, this is happening only with the newer version (v5.0.0.2622 a) of Xamarin forms List view elements with property "ListViewCachingStrategy.RetainElement". others are working as expected.
This is actually blocking our execution and request your help here.

**Comment by mykola-mokhnach** [comment]
I mean there is nothing we could do there. XCTest is owned by Apple. What you could try is to run your test using vanilla XCTest, fetch the page tree there, and then report it as a bug to Apple if the expected element is accessible, but is not present in the output.
