### ISSUE TITLE
WebDriverAgent does not install after updating iOS to 17.3.1

### ISSUE THREAD

**Issue by paulohvalipio** [appium/appium#19862]
Hello,

After updating the iOS version to 17.3.1 appium-xcuitest-driver no longer installs WebDriverAgent, causing the 
error "2024-03-05 14:54:44:454 - [38;5;160m[Xcode] [0m / Users/fabricacrm/JenkinsAgent/workspace/QA_CloverCRM_AppV6_iOS_TestesNoturnos/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 17.3, but the range of supported deployment target versions is 12.0 to 17.2.99. (in target 'WebDriverAgentRunner' from project 'WebDriverAgent')
2024-03-05 14:54:44:454 - [38;5;160m[Xcode] [0m error: unexpected service error: The Xcode build system has crashed. Build again to continue".
It is possible to install WebDriverAgent from the outside with xcodebuild, but the server is not started and depending on the capability it does not use WebDriverAgent. Could help?

Thanks!

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly according to the provided template

**Comment by paulohvalipio** [comment]
How do I get the template?

**Comment by eglitise** [comment]
https://github.com/appium/appium/issues/new/choose -> Bug Report
