### ISSUE TITLE
Get timeout error when running test with Appium CLI test

### ISSUE THREAD

**Issue by Ranjithlevine** [appium/appium#19867]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[Appium] Welcome to Appium v1.22.3
[Appium] Non-default server args:
[Appium]   address: 127.0.0.1
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[debug] [HTTP] Request idempotency key: d3f26848-63fe-4c2b-8e50-ff427dd5f8cc
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"webkitResponseTimeout":60000,"noReset":true,"commandTimeouts":20000,"bundleId":"org.heartsapp.heartsapp.qa","webviewConnectTimeout":20000,"deviceName":"Automation iPhone","wdaLocalPort":4723,"wdaLaunchTimeout":60000,"newCommandTimeout":60,"automationName":"XCUITest","platformName":"ios","udid":"00008101-000879012481401E","wdaConnectionTimeout":60000},"capabilities":{"firstMatch":[{"appium:automationName":"XCUITest","appium:bundleId":"org.heartsapp.heartsapp.qa","appium:commandTimeouts":20000,"appium:deviceName":"Automation iPhone","appium:newCommandTimeout":60,"appium:noReset":true,"platformName":"ios","appium:udid":"00008101-000879012481401E","appium:wdaConnectionTimeout":60000,"appium:wdaLaunchTimeout":60000,"appium:wdaLocalPort":4723,"webkitResponseTimeout":60000,"webviewConnectTimeout":20000}]}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"webkitResponseTimeout":60000,"noReset":true,"commandTimeouts":20000,"bundleId":"org.heartsapp.heartsapp.qa","webviewConnectTimeout":20000,"deviceName":"Automation iPhone","wdaLocalPort":4723,"wdaLaunchTimeout":60000,"newCommandTimeout":60,"automationName":"XCUITest","platformName":"ios","udid":"00008101-000879012481401E","wdaConnectionTimeout":60000},null,{"firstMatch":[{"appium:automationName":"XCUITest","appium:bundleId":"org.heartsapp.heartsapp.qa","appium:commandTimeouts":20000,"appium:deviceName":"Automation iPhone","appium:newCommandTimeout":60,"appium:noReset":true,"platformName":"ios","appium:udid":"00008101-000879012481401E","appium:wdaConnectionTimeout":60000,"appium:wdaLaunchTimeout":60000,"appium:wdaLocalPort":4723,"webkitResponseTimeout":60000,"webviewConnectTimeout":20000}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1709845489473 (02:34:49 GMT+0530 (India Standard Time))
[BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
[BaseDriver]   webkitResponseTimeout
[BaseDriver]   webviewConnectTimeout
[Appium] Appium v1.22.3 creating new XCUITestDriver (v3.59.0) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "ios",
[debug] [BaseDriver]     "appium:webkitResponseTimeout": 60000,
[debug] [BaseDriver]     "appium:webviewConnectTimeout": 20000,
[debug] [BaseDriver]     "appium:automationName": "XCUITest",
[debug] [BaseDriver]     "appium:bundleId": "org.heartsapp.heartsapp.qa",
[debug] [BaseDriver]     "appium:commandTimeouts": 20000,
[debug] [BaseDriver]     "appium:deviceName": "Automation iPhone",
[debug] [BaseDriver]     "appium:newCommandTimeout": 60,
[debug] [BaseDriver]     "appium:noReset": true,
[debug] [BaseDriver]     "appium:udid": "00008101-000879012481401E",
[debug] [BaseDriver]     "appium:wdaConnectionTimeout": 60000,
[debug] [BaseDriver]     "appium:wdaLaunchTimeout": 60000,
[debug] [BaseDriver]     "appium:wdaLocalPort": 4723
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[XCUITest] 'platformVersion' capability ('undefined') is not a valid version number. Consider fixing it or be ready to experience an inconsistent driver behavior.
[BaseDriver] Session created with session id: 10f2eb92-9525-475c-94d1-7486ddd569e8
[debug] [XCUITest] Current user: 'htcuser'
[debug] [XCUITest] Available devices: 00008101-000879012481401E
[debug] [XCUITest] Creating iDevice object with udid '00008101-000879012481401E'
[XCUITest] Determining device to run tests on: udid: '00008101-000879012481401E', real device: true
[XCUITest] No platformVersion specified. Using device version: '14.1'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1709845489838 (02:34:49 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'appConfigured' logged at 1709845489839 (02:34:49 GMT+0530 (India Standard Time))
[debug] [BaseDriver] Event 'resetStarted' logged at 1709845489839 (02:34:49 GMT+0530 (India Standard Time))
[debug] [XCUITest] Reset: fullReset not set. Leaving as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1709845489839 (02:34:49 GMT+0530 (India Standard Time))
[WebDriverAgent] Using WDA path: '/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent'
[WebDriverAgent] Using WDA agent: '/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
[debug] [WebDriverAgent] Parsed BUILD_DIR configuration value: '/Users/htcuser/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou/Build/Products'
[debug] [WebDriverAgent] Got derived data root: '/Users/htcuser/Library/Developer/Xcode/DerivedData/WebDriverAgent-aghlrsejdreqngftgvcqwnjgrbou'
[XCUITest] Continuing without capturing device logs: Failed to receive any data within the timeout: 5000
[XCUITest] Setting up real device
[XCUITest] {}
[DevCon Factory] Releasing connections for 00008101-000879012481401E device on any port number
[DevCon Factory] No cached connections have been found
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1709845500032 (02:35:00 GMT+0530 (India Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Failed to receive any data within the timeout: 5000
[debug] [W3C]     at Timeout._onTimeout (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-ios-device/lib/plist-service/index.js:67:16)
[debug] [W3C]     at listOnTimeout (node:internal/timers:573:17)
[debug] [W3C]     at processTimers (node:internal/timers:514:7)
[HTTP] <-- POST /wd/hub/session 500 10588 ms - 687
[HTTP] 

### Expected Behavior

    run the appium

### Minimal Reproducible Example

test.

### Environment

- Operating system:14.3.1
- Appium server version (output of `appium --version`):1.22.3
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):20.11.3
- `npm` version (output of `npm --version`):10.2.4
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:ios
- Real device or emulator/simulator: real device

**Comment by jlipps** [comment]
Appium 1.22 is no longer supported. Please use Appium 2.
