### ISSUE TITLE
iOS 16+ visible value returns false incorrectly for XCUIElementTypeImage

### ISSUE THREAD

**Issue by Shailendra-3Frames** [appium/appium#19863]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to inspect the Flutter app in SauceLabs but I am always getting a visible flag as false for a few elements even though it is visible. Due to this, all the automation scripts are stopped as the visible flag is false.

### Expected Behavior

The visible property should be true for the visible elements in the widget tree when we inspect in SauceLabs inspector.

### Minimal Reproducible Example

1. Upload the iPA to SauceLabs
2. Choose iOS 16+  device and start the test
3. Inspect the elements
4. Check the visible flag in the DOM tree

### Environment

- Operating system: Windows
- Appium server version (output of `appium --version`): 2.0.0
- Appium driver(s) and their version(s): 
- Appium plugin(s) and their version(s): 
- Node.js version (output of `node --version`): 
- `npm` version (output of `npm --version`): 
- Last component(s) version which did _not_ exhibit the problem: iOS 15
- Platform and version under test: iOS 16
- Real device or emulator/simulator: Real Devices which are in SauceLabs

### Further Information

I am trying to inspect the Flutter app in SauceLabs but I am always getting a visible flag as false for a few elements even though it is visible. Due to this, all the automation scripts are stopped as the visible flag is false.

Note: This is happening only in iOS 16+ OS.(working fine below iOS 16 OS and Android too)

Appium version: 2.0.0
WebDriverAgent version: 8.5.1
iOS: 16.0
Flutter SDK: 3.7.10 (and also tried with latest 3.16.2)

Any suggestions would be very helpful to solve this issue.

![image](https://github.com/appium/appium/assets/136445969/0cb59792-d514-40c9-90b5-8fce9ed76cdb)

**Comment by mykola-mokhnach** [comment]
The value for this attribute is returned by XCTest/Accessibility layer.  We cannot influence it.

Closed as third party issue
