### ISSUE TITLE
Accepting alert in Ios Simulator failing intermittently - appium 2.0.0

### ISSUE THREAD

**Issue by aksh-02** [appium/appium#19886]
### Environment
Appium version - 2.0.0
Xcui Driver - 5.12.1
Ios - 16.0 (Simulator)
Xcode version - 14.0

### Appium Capabilities
automationName - XCUITest
includeSafariInWebviews - True
nativeWebTap - True
autoAcceptAlerts - False (intentional)
waitForQuiescence - False

### Current Behavior

In my simulator test, I get a popup which I'm trying to accept using
`
driver.execute_script("mobile: alert", {"action": "accept"})
`
But this is failing intermittently

### Expected Behavior
Popup should disappear

### Appium Logs
https://gist.github.com/aksh-02/2a75797c093e12c7aa4c512ecc4013bf

**Comment by eglitise** [comment]
Please provide the full Appium log, not just a snippet.

**Comment by mykola-mokhnach** [comment]
Please update the xcuitest driver to the most recent version. We do not patch older versions of it.
Sometimes there might be a race condition. Either make sure the alert is present before accepting it or have an explicit timer there.

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach interesting what labels trying to tap command while we have just `accept` or `dismiss` action without specifying label text?

https://github.com/appium/WebDriverAgent/blob/0a28987a7a1adb265e4b1251087b46f40ef968fd/WebDriverAgentLib/FBAlert.m#L160

**Comment by aksh-02** [comment]
@eglitise I've updated the full appium logs in the gist

> Either make sure the alert is present before accepting it or have an explicit timer there.
The alert is there, and is visible in simulator, can't change xcui driver above 7.0.0 for now

**Comment by amedvedjev** [comment]
@aksh-02 are you sure this is not your app custom alert? is it some kind permission or ?

**Comment by aksh-02** [comment]
@amedvedjev yeah this is an alert from the app, asking if the url should be opened in the app. 
Regardless of that, shouldn't the alert acceptance be successful every time or never

**Comment by amedvedjev** [comment]
@aksh-02 if it custom alert that is inside your app, why not you just accept/decline it in same way as you tap on any app button?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
