### ISSUE TITLE
Can't start Appium Inspector - Error: Failed to create session. Bad capabilities. Specify either app or appTopLevelWindow to create a session

### ISSUE THREAD

**Issue by kenzoviski** [appium/appium#19880]
I use Windows 11 and I'm not able to "Start Session" in the "Appium Inspector". I have this "JSON Representation" of appCapabilities:

{
  "appium:app": "D:\\Trabalho Freelancer\\FLOWApps\\Applications\\FLOW2BO\\flow2bo.exe"
}

I'm connecting to http://127.0.0.1:4723 and when click on the "Start session" button I get:
"Error: Failed to create session. Bad capabilities. Specify either app or appTopLevelWindow to create a session"

Also have WinAppDriver running on the cmd (tried with and without elevated rights) and I get the bellow error/log.
Can please someone help me, I'm trying to identify elements (specially xPaths) of my desktop app (flow2bo.exe) on Windows 11.

WinAppDriver log
==========================================
POST /session HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-PT
Connection: keep-alive
Content-Length: 386
Content-Type: application/json
Host: 127.0.0.1:4723
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) appium-inspector/2024.3.1 Chrome/91.0.4472.164 Electron/13.6.9 Safari/537.36

{"capabilities":{"alwaysMatch":{"appium:app":"D:\\Trabalho Freelancer\\FLOWApps\\Applications\\FLOW2BO\\flow2bo.exe","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"appium:app":"D:\\Trabalho Freelancer\\FLOWApps\\Applications\\FLOW2BO\\flow2bo.exe","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
HTTP/1.1 400 Bad Request
Content-Length: 141
Content-Type: application/json

{"status":100,"value":{"error":"invalid argument","message":"Bad capabilities. Specify either app or appTopLevelWindow to create a session"}}

**Comment by eglitise** [comment]
Logs will be created in the terminal window where you have launched the Appium server. What versions of the Appium server / Windows driver / WinAppDriver are you using?

**Comment by mykola-mokhnach** [comment]
It won't work if you use WAD directly without appium-windows-driver. The error above happens because inspector sends W3C capabilities, which WAD does not understand (and probably won't because MS does not really care about maintaining it). appium-windows-driver works as a proxy and translates W3C commands into JWP ones understandable for the server.

**Comment by kenzoviski** [comment]
> Logs will be created in the terminal window where you have launched the Appium server. What versions of the Appium server / Windows driver / WinAppDriver are you using?

**My Appium Server version through command:** `appium --version`
2.5.1

**Appium Inspector (latest release on github):** [2024.3.1](https://github.com/appium/appium-inspector/releases/tag/v2024.3.1)

**My Windows driver installed through command:** `appium driver install --source=npm appium-windows-driver` 
windows@2.12.18 [installed (npm)]

**WinAppDriver (latest release candidate) installed on Windows 11:** [WinAppDriver v1.3 Release Candidate 1 (1.2.99)](https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.99)

On VS Code bash terminal I start Appium: `appium -a 127.0.0.1 -p 4723`

And get the following log/error:

```
[Appium] Welcome to Appium v2.5.1
[Appium] Non-default server args:
[Appium] {
[Appium]   address: '127.0.0.1'
[Appium] }
[Appium] The autodetected Appium home path: D:\Trabalho Freelancer\FlowAutomation\DesktopAutomationCSharp
[Appium] Attempting to load driver windows...
[Appium] Requiring driver at D:\Trabalho Freelancer\FlowAutomation\DesktopAutomationCSharp\node_modules\appium-windows-driver\build\index.js
[Appium] Could not load driver 'windows', so it will not be available. Error in loading the driver was: Unexpected External value as type specifier, expected string or type
[Appium] TypeError: Unexpected External value as type specifier, expected string or type
[Appium]     at Object.<anonymous> (D:\Trabalho Freelancer\FlowAutomation\DesktopAutomationCSharp\node_modules\appium-windows-driver\lib\commands\winapi\user32.js:102:49)
[Appium]     at Module._compile (node:internal/modules/cjs/loader:1378:14)
[Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
[Appium]     at Module.load (node:internal/modules/cjs/loader:1212:32)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
[Appium]     at Module.require (node:internal/modules/cjs/loader:1237:19)
[Appium]     at require (node:internal/modules/helpers:176:18)
[Appium]     at Object.<anonymous> (D:\Trabalho Freelancer\FlowAutomation\DesktopAutomationCSharp\node_modules\appium-windows-driver\lib\commands\gestures.js:2:1)
[Appium]     at Module._compile (node:internal/modules/cjs/loader:1378:14)
[Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
[Appium]     at Module.load (node:internal/modules/cjs/loader:1212:32)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
[Appium]     at Module.require (node:internal/modules/cjs/loader:1237:19)
[Appium]     at require (node:internal/modules/helpers:176:18)
[Appium]     at Object.<anonymous> (D:\Trabalho Freelancer\FlowAutomation\DesktopAutomationCSharp\node_modules\appium-windows-driver\lib\commands\index.js:9:1)
[Appium]     at Module._compile (node:internal/modules/cjs/loader:1378:14)
[Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
[Appium]     at Module.load (node:internal/modules/cjs/loader:1212:32)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
[Appium]     at Module.require (node:internal/modules/cjs/loader:1237:19)
[Appium]     at require (node:internal/modules/helpers:176:18)
[Appium]     at Object.<anonymous> (D:\Trabalho Freelancer\FlowAutomation\DesktopAutomationCSharp\node_modules\appium-windows-driver\lib\driver.js:6:1)
[Appium]     at Module._compile (node:internal/modules/cjs/loader:1378:14)
[Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
[Appium]     at Module.load (node:internal/modules/cjs/loader:1212:32)
[Appium]     at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
[Appium]     at Module.require (node:internal/modules/cjs/loader:1237:19)
[Appium]     at require (node:internal/modules/helpers:176:18)
[Appium] Appium REST http interface listener started on http://127.0.0.1:4723
[Appium] Available drivers:
[Appium]   - windows@2.12.18 (automationName 'Windows')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
```

It says "- windows@2.12.18 (automationName 'Windows')" is an available driver but can't start it.
I'm confused now... I usally execute WinAppDriver.exe through cmd and let it run. I though Appium would connect to it but it doesn't seem to be the case.

How do I test desktop apps using Appium and WinAppDriver then?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/19659

**Comment by kenzoviski** [comment]
> Check #19659

After installing Node.js_20.11.1 I managed to start Appium server successfully.
But still, I'm getting and error while executing the Appium Inspector when I click on "Start Sessions".

These are my "Capabilities":
`{
  "appium:app": "D:\\Trabalho Freelancer\\FLOWApps\\Applications\\FLOW2BO\\flow2bo.exe",
  "platformName": "windows",
  "appium:automationName": "windows"
}`

And on Appium server I get the following error:
```
Appium] Attempting to find matching driver for automationName 'windows' and platformName 'windows'
[Appium] The 'windows' driver was installed and matched caps.
[Appium] Will require it at D:\Trabalho Freelancer\FlowAutomation\node_modules\appium-windows-driver
[Appium] Requiring driver at D:\Trabalho Freelancer\FlowAutomation\node_modules\appium-windows-driver\build\index.js
[AppiumDriver@ce67] Appium v2.5.1 creating new WindowsDriver (v2.12.18) session
[AppiumDriver@ce67] Checking BaseDriver versions for Appium and WindowsDriver
[AppiumDriver@ce67] Appium's BaseDriver version is 9.5.2
[AppiumDriver@ce67] WindowsDriver's BaseDriver version is 9.5.2
[WindowsDriver@1b02] Creating session with W3C capabilities: {
[WindowsDriver@1b02]   "alwaysMatch": {
[WindowsDriver@1b02]     "platformName": "windows",
[WindowsDriver@1b02]     "appium:app": "D:\\Trabalho Freelancer\\FLOWApps\\Applications\\FLOW2BO\\flow2bo.exe",
[WindowsDriver@1b02]     "appium:automationName": "windows",
[WindowsDriver@1b02]     "appium:newCommandTimeout": 3600,
[WindowsDriver@1b02]     "appium:connectHardwareKeyboard": true
[WindowsDriver@1b02]   },
[WindowsDriver@1b02]   "firstMatch": [
[WindowsDriver@1b02]     {}
[WindowsDriver@1b02]   ]
[WindowsDriver@1b02] }
[WindowsDriver@1b02] The following provided capabilities were not recognized by this driver:
[WindowsDriver@1b02]   connectHardwareKeyboard
[WindowsDriver@1b02 (b60ea8e7)] Session created with session id: b60ea8e7-b05f-43be-8842-6051c26c16bf
[WindowsDriver@1b02 (b60ea8e7)] Spawning 'C:\Program Files\Windows Application Driver\WinAppDriver.exe' with args: ["4724/wd/hub"]
[WindowsDriver@1b02 (b60ea8e7)] Matched '/status' to command name 'getStatus'
[WindowsDriver@1b02 (b60ea8e7)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[WindowsDriver@1b02 (b60ea8e7)] connect ECONNREFUSED 127.0.0.1:4724
[WindowsDriver@1b02 (b60ea8e7)] Windows Application Driver listening for requests at: http://127.0.0.1:4724/wd/hub
[WindowsDriver@1b02 (b60ea8e7)] Press ENTER to exit.
[WindowsDriver@1b02 (b60ea8e7)] Matched '/status' to command name 'getStatus'
[WindowsDriver@1b02 (b60ea8e7)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
[WindowsDriver@1b02 (b60ea8e7)] ==========================================
[WindowsDriver@1b02 (b60ea8e7)] GET /wd/hub/status HTTP/1.1
[WindowsDriver@1b02 (b60ea8e7)] Accept: application/json, */*
[WindowsDriver@1b02 (b60ea8e7)] Accept-Encoding: gzip, compress, deflate, br
[WindowsDriver@1b02 (b60ea8e7)] Connection: keep-alive
[WindowsDriver@1b02 (b60ea8e7)] Content-Type: application/json; charset=utf-8
[WindowsDriver@1b02 (b60ea8e7)] Host: 127.0.0.1:4724
[WindowsDriver@1b02 (b60ea8e7)] User-Agent: appium
[WindowsDriver@1b02 (b60ea8e7)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
[W3C] Matched W3C error code 'unknown error' to UnknownError
```

How do I fix the `[W3C] Matched W3C error code 'unknown error' to UnknownError` so I can hook my app to Appium Inspector and start identifying the elements?

**Comment by mykola-mokhnach** [comment]
This is an issue with the server itself. Try https://github.com/appium/appium-windows-driver?tab=readme-ov-file#various-winappdriver-calls-dont-work-as-expected-or-throw-weird-errors

**Comment by kenzoviski** [comment]
> This is an issue with the server itself. Try https://github.com/appium/appium-windows-driver?tab=readme-ov-file#various-winappdriver-calls-dont-work-as-expected-or-throw-weird-errors

Well, that didn't help at all.
Since it's a problem related directly to WinAppDriver, I opened an issue on their repo and refering this issue.

I just don't understand how people test desktop apps on Windows. I suppose no one test them at all or have to pay thousands for a software that does the job. Going open-source on Windows is not a good idea.

**Comment by mykola-mokhnach** [comment]
> Well, that didn't help at all.

What exactly have you tried? Did you try with a different WAD version?

**Comment by kenzoviski** [comment]
> > Well, that didn't help at all.
> 
> What exactly have you tried? Did you try it with a different WAD version?

Yes, I installed the previous version of WAD and Appium Inspector hooked to my app. No errors on Appium Server.
Although, I realized it can't identify all the items on my desktop app. It's not a suitable solution to automate tests, at least on the app I'm trying to test.

Guess I have to go for a paid software that has a better "Spy tool", like Ranorex.

**Comment by mykola-mokhnach** [comment]
I'm sorry to hear that, but yes, MS has its own plans regarding windows automation and open sourcing policies in general.

Closed as not an issue.

**Comment by jialibee** [comment]
> 如果没有appium-windows-driver直接使用WAD是不行的。发生上述错误是因为检查器发送了 W3C 功能，而 WAD 无法理解（并且可能不会，因为 MS 并不真正关心维护它）。 appium-windows-driver 充当代理，并将 W3C 命令转换为服务器可以理解的 JWP 命令。

**Comment by OhJeasus** [comment]
Hey @kenzoviski I am also facing the same issue, Can you please help me also correct the issue
