### ISSUE TITLE
Issue trying to switch context from NATIVE_APP to WEBVIEW in Appium 2.5.1

### ISSUE THREAD

**Issue by HarshdeepSingh3009** [appium/appium#19884]
I am trying to switch context from Native_App tp Webview but it fails with timed out after 240 seconds.  I am using following set up :

**Appium - 2.5.1
uiautomator2 - 2.45.1
AppiumBaseDriver - 9.5.2
AndroidUiAutomator2Driver - 9.5.1
Android Platform - 14.0
appium-chromedriver- 5.6.37**

I am using appium inspector to switch contexts and see following error:

[AndroidUiautomator2Driver@5b98 (4c6e763e)] Calling AppiumDriver.getCurrentPackage() with args: ["4c6e763e-fb90-4439-b538-30154541d991"]
[Chromedriver@4a2e] AxiosError: timeout of 240000ms exceeded
[Chromedriver@4a2e]     at RedirectableRequest.handleRequestTimeout (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\adapters\http.js:647:16)
[Chromedriver@4a2e]     at RedirectableRequest.emit (node:events:518:28)
[Chromedriver@4a2e]     at Timeout.<anonymous> (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\follow-redirects\index.js:210:12)
[Chromedriver@4a2e]     at listOnTimeout (node:internal/timers:573:17)
[Chromedriver@4a2e]     at processTimers (node:internal/timers:514:7)
[Chromedriver@4a2e]     at Axios.request (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\Axios.js:45:41)
[Chromedriver@4a2e]     at runNextTicks (node:internal/process/task_queues:60:5)
[Chromedriver@4a2e]     at listOnTimeout (node:internal/timers:540:9)
[Chromedriver@4a2e]     at processTimers (node:internal/timers:514:7)
[Chromedriver@4a2e]     at JWProxy.request (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:100:14)
[Chromedriver@4a2e]     at JWProxy.proxy (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:234:39)
[Chromedriver@4a2e]     at ProtocolConverter.convertAndProxy (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\@appium\base-driver\lib\jsonwp-proxy\protocol-converter.js:222:14)
[Chromedriver@4a2e]     at JWProxy.proxyCommand (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:336:12)
[Chromedriver@4a2e]     at JWProxy.command (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:350:32)
[Chromedriver@4a2e]     at Chromedriver.startSession (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver\lib\chromedriver.js:743:7)
[Chromedriver@4a2e]     at Chromedriver.start (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver\lib\chromedriver.js:667:14)
[Chromedriver@4a2e]     at AndroidUiautomator2Driver.setupNewChromedriver (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\helpers.js:745:3)
[Chromedriver@4a2e]     at AndroidUiautomator2Driver.startChromedriverProxy (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\exports.js:229:10)
[Chromedriver@4a2e]     at AndroidUiautomator2Driver.switchContext (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\exports.js:108:5)
[Chromedriver@4a2e]     at AndroidUiautomator2Driver.setContext (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\exports.js:64:3)
[Chromedriver@4a2e] UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[Chromedriver@4a2e]     at JWProxy.command (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:355:13)
[Chromedriver@4a2e]     at runNextTicks (node:internal/process/task_queues:60:5)
[Chromedriver@4a2e]     at listOnTimeout (node:internal/timers:540:9)
[Chromedriver@4a2e]     at processTimers (node:internal/timers:514:7)
[Chromedriver@4a2e]     at Chromedriver.startSession (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver\lib\chromedriver.js:743:7)
[Chromedriver@4a2e]     at Chromedriver.start (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver\lib\chromedriver.js:667:14)
[Chromedriver@4a2e]     at AndroidUiautomator2Driver.setupNewChromedriver (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\helpers.js:745:3)
[Chromedriver@4a2e]     at AndroidUiautomator2Driver.startChromedriverProxy (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\exports.js:229:10)
[Chromedriver@4a2e]     at AndroidUiautomator2Driver.switchContext (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\exports.js:108:5)
[Chromedriver@4a2e]     at AndroidUiautomator2Driver.setContext (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\exports.js:64:3)
[Chromedriver@4a2e] Chromedriver exited unexpectedly with code null, signal SIGTERM
[Chromedriver@4a2e] Changed state to 'stopped'
[Chromedriver@4a2e] An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[AndroidUiautomator2Driver@5b98 (4c6e763e)] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: timeout of 240000ms exceeded
[AndroidUiautomator2Driver@5b98 (4c6e763e)]     at Object.wrappedLogger.errorWithException (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\@appium\support\lib\logging.js:114:43)
[AndroidUiautomator2Driver@5b98 (4c6e763e)]     at Object.wrappedLogger.errorAndThrow (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\@appium\support\lib\logging.js:120:16)
[AndroidUiautomator2Driver@5b98 (4c6e763e)]     at Chromedriver.start (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver\lib\chromedriver.js:695:16)
[AndroidUiautomator2Driver@5b98 (4c6e763e)]     at AndroidUiautomator2Driver.setupNewChromedriver (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\helpers.js:745:3)
[AndroidUiautomator2Driver@5b98 (4c6e763e)]     at AndroidUiautomator2Driver.startChromedriverProxy (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\exports.js:229:10)
[AndroidUiautomator2Driver@5b98 (4c6e763e)]     at AndroidUiautomator2Driver.switchContext (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\exports.js:108:5)
[AndroidUiautomator2Driver@5b98 (4c6e763e)]     at AndroidUiautomator2Driver.setContext (C:\Users\Support User\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\context\exports.js:64:3)
[HTTP] <-- POST /wd/hub/session/4c6e763e-fb90-4439-b538-30154541d991/context 500 241391 ms - 928

**Comment by mykola-mokhnach** [comment]
Are you able to connect to the same web view via Chrome?

To me it looks like there is an issue with the chromedriver itself as we don't get any response from it.

**Comment by HarshdeepSingh3009** [comment]
I just tried to  access the webview on my android device via chrome devtools on desktop browser and I am able to detect and interact with the elements on the screen.

**Comment by mykola-mokhnach** [comment]
Then it must a chromedriver issue. Fetch chromedriver logs and create an issue report to Google. I remember there was already a known issue related to chromedriver freeze on connection if the target webview contained empty windows.

**Comment by HarshdeepSingh3009** [comment]
Seems like the chromedriver is up and running 
 Proxying [GET /status] to [GET http://127.0.0.1:51079/status] with no body
[Chromedriver@6c34] Got response with status 200: {"value":{"build":{"version":"122.0.6261.111 (9d4c1072da62b411b351a38b9ed6214ab236aa7b-refs/branch-heads/6261@{#1015})"},"message":"ChromeDriver ready for new sessions.","os":{"arch":"x86_64","name":"Windows NT","version":"10.0.19042"},"ready":true}}

but then it sends a POST request to createSession and this is where it timesout after 240 seconds. It is able to get WebviewVersion Webview version: 'Chrome/122.0.6261.64'.

**Comment by KazuCocoa** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=4577&q=webview&can=2 could be similar issue. Chromedriver has no response for a new session request.

**Comment by HarshdeepSingh3009** [comment]
Yes, this seems like exactly the same issue.  Thanks for sharing it.

**Comment by KazuCocoa** [comment]
Then, maybe the only thing you could do is using older Chrome/system WebView, or try out latest chrome/webview engine. I heard 122 or 121 fixed a case that had the link's issue.
