### ISSUE TITLE
Running: setGeoLocation, report unexpected data: {"Error":"InvalidService","Request":"StartService","Service":"com.apple.dt.simulatelocation"} (xcode: 15.3, iOS:17.4)

### ISSUE THREAD

**Issue by wuyan-grabtaxi** [appium/appium#19893]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium: v2.5.1
uiautomator2@3.0.2
xcode: 15.3, 
iOS:17.4
macOS: 14.4

when executing command 'setGeoLocation'
report error:  Encountered internal error running command: Error: Unexpected data: {"Error":"InvalidService","Request":"StartService","Service":"com.apple.dt.simulatelocation"}

### Expected Behavior

Can set geolocation

### Minimal Reproducible Example

location":{"latitude":"1.264698","longitude":"103.822346","altitude":10}

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
> uiautomator2@3.0.2

Is it XCUITest driver?
Please attatch the full appium server log.


The latest driver may have logs and proxies to `mobile:setSimulatedLocation` internally
https://github.com/appium/appium-xcuitest-driver/blob/ec3b4c7032bbd85f12f634b730ff7fa8c798021d/lib/commands/location.js#L86-L87

**Comment by wuyan-grabtaxi** [comment]
[38;5;32m[XCUITestDriver@a603 (883eabd3)][0m Responding to client with driver.createSession() result: {"capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"iOS","autoAcceptAlerts":true,"autoDismissAlerts":true,"autoGrantPermissions":true,"automationName":"XCUITest","deviceName":"iPhone","noReset":true,"agentPath":"/opt/homebrew/lib/node_modules/appium/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj","bootStrapPath":"/opt/homebrew/lib/node_modules/appium/node_modules/appium-webdriveragent","platformVersion":"15.7","udid":"00008120-000418893A6BC01E","bundle_id":"com.grab.passenger.dogfood.debug"}}
[38;5;0m[HTTP][0m [37m<-- POST /wd/hub/session [39m[32m200[39m [90m356 ms - 748[39m
[38;5;0m[HTTP][0m [90m[39m
[38;5;0m[HTTP][0m [37m-->[39m [37mPOST[39m [37m/wd/hub/session/883eabd3-d03a-4c01-9c6f-510efcb2b461/location[39m
[38;5;0m[HTTP][0m [90m{"location":{"latitude":"1.264698","longitude":"103.822346","altitude":10}}[39m
[38;5;32m[XCUITestDriver@a603 (883eabd3)][0m Calling AppiumDriver.setGeoLocation() with args: [{"latitude":"1.264698","longitude":"103.822346","altitude":10},"883eabd3-d03a-4c01-9c6f-510efcb2b461"]
[38;5;32m[XCUITestDriver@a603 (883eabd3)][0m Executing command 'setGeoLocation'
[38;5;32m[XCUITestDriver@a603 (883eabd3)][0m Encountered internal error running command: Error: Unexpected data: {"Error":"InvalidService","Request":"StartService","Service":"com.apple.dt.simulatelocation"}
[38;5;32m[XCUITestDriver@a603 (883eabd3)][0m     at Lockdown.startService (/Users/xx/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/lockdown/index.js:104:13)
[38;5;32m[XCUITes~tDriver@a603 (883eabd3)][0m     at startService (/Users/xx/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/services.js:119:21)
[38;5;32m[XCUITestDriver@a603 (883eabd3)][0m     at Object.startSimulateLocationService (/Users/xx/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/services.js:27:18)
[38;5;32m[XCUITestDriver@a603 (883eabd3)][0m     at XCUITestDriver.setGeoLocation (/Users/xx/.appium/node_modules/appium-xcuitest-driver/lib/commands/location.js:70:23)
[38;5;0m[HTTP][0m [37m<-- POST /wd/hub/session/883eabd3-d03a-4c01-9c6f-510efcb2b461/location

**Comment by KazuCocoa** [comment]
Could you attach the full log? The log has various information to guess your environment for us.

**Comment by KazuCocoa** [comment]
Btw,

> It is recommended for iOS 17+ real devices to simulate the device location.

https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-setsimulatedlocation

The latest XCUITest driver handles iOS 17+ case internally as https://github.com/appium/appium/issues/19893#issuecomment-1996386465 . If not, please use the `mobile:setSimulatedLocation` for iOS 17.

**Comment by mykola-mokhnach** [comment]
> set location function does not take effect

it just triggers the downstream [XCTest APIs](https://developer.apple.com/documentation/xcode/simulating-location-in-tests). Consider reporting an issue to Apple if this API does not work as expected.

**Comment by KazuCocoa** [comment]
Based on my experience, it could take time (~ 10 sec) to reflect on the simulated location. (I tested with `com.apple.Maps`) I also met a case in which I needed to bring the test app to the background by activating the springboard and re-activating the test app again. It could very system OS state I guess though.

**Comment by wuyan-grabtaxi** [comment]
Thanks [KazuCocoa](https://github.com/KazuCocoa), 
[mykola-mokhnach](https://github.com/mykola-mokhnach), I resolve the issue at last. In my test app, it also have a function to mock location, when i disable it,  appium mock location works.  
Thank you for your help
