### ISSUE TITLE
Page Source in webview context empty for emulator app - appium 2.0.0

### ISSUE THREAD

**Issue by aksh-02** [appium/appium#19890]
### Environment
Appium - 2.0.0
AndroidUiautomator2Driver - 3.0.2
Android - 14 (emulator, API 34.0.0)
Uiautomator2-server - 7.0.3
Chrome - 113.0.5672.136 (also reproducible on Chrome 103.x)
Chromedriver - 113.0.5672.24

### Current Behavior
After switching to a webview context, I should be able to see the html page source, this is visible with chrome devtools and rendered fine in Emulator GUI but via appium page source I'm getting
`<html><head><meta name="color-scheme" content="light dark"></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">Not found
</pre></body></html>`

### Expected Behavior
After switching to webview context, I should be getting full page source

### Appium Logs
https://gist.github.com/aksh-02/3868a2aff9ac865ce94332ea619871eb

**Comment by mykola-mokhnach** [comment]
uia2 driver does not have any influence on the page source output, it just proxies requests to chromedriver.
I would try to make sure a proper window is selected from the web view and/or this is not a race condition issue.
Otherwise consider creating an issue to Google.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue.
