### ISSUE TITLE
bug: Accessing WebView cookies makes test session hang

### ISSUE THREAD

**Issue by szarlatan** [appium/appium#19895]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a test that is expected to capture the load time of given page with our custom built-in web browser.
Test steps are listed below, assuming the app is already opened:
1. Open built-in browser
2. Navigate to page
3. Switch context to WebView
4. Get all cookies to find navigation start/stop timestamp data saved by our browser
5. Clear all cookies
6. Switch context to NATIVE_APP
7. Close browser

Whole list is configured to work in loop for e.g. 20 times, but hangs after few (circa 5)

### Expected Behavior

All repeats are completed without any timeouts

### Minimal Reproducible Example

[GIST with server logs](https://gist.github.com/szarlatan/5834da0c0d70ffb8b65c3fed75d480d1)

### Environment

- Operating system: Sonoma 14.3.1 (23D60)
- Appium server version (output of `appium --version`): v2.5.1
- Appium driver(s) and their version(s): **xcuitest@7.1.2** (automationName 'XCUITest'); **uiautomator2@3.0.1** (automationName 'UiAutomator2')
- Appium plugin(s) and their version(s): None
- Node.js version (output of `node --version`): v.18.17.0
- `npm` version (output of `npm --version`): v.9.6.7
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: iPhone 12 mini (17.4), Samsung S21 (13)

### Link to Appium Logs

https://gist.github.com/szarlatan/5834da0c0d70ffb8b65c3fed75d480d1

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing we could do about it. The part that refuses to respond is chromedriver itself. Please collect its logs and raise an issue to Google. UIA2 simply acts as a proxy there.
