### ISSUE TITLE
Unable to interact with iOS paste permission dialog

### ISSUE THREAD

**Issue by rolandmoldovan** [appium/appium#19908]
I'm testing an app where I need to deal with several OS permission dialogs. When dealing with each dialog, I activate "com.apple.springboard" and successfully tap the suitable button. However, I encounter difficulties interacting with the "Allow Paste" permission. Is there something different about this one in particular?

I'm using Appium 2.5.1 and xcuitest 7.3.1. 

This is what I do (and works on any other dialog except this one):

`await driver.execute('mobile: activateApp', { bundleId: 'com.apple.springboard' });

const allowButton = await $('~Allow Paste');
await allowButton.waitForDisplayed({
  timeout: 15000
});
await allowButton.click();`

It seems that the it fails with error: element ("~Allow Paste") still not displayed after 15000ms

I've tried finding the element also by -ios class chain, -ios predicate string, xpath, nothing seem to help.

<img width="344" alt="Screenshot 2024-03-20 at 14 32 44" src="https://github.com/appium/appium/assets/46964104/e3037a0c-961a-4e0b-8984-d58e79f5f3f5">

It is really interesting that I can interact with the element via Appium Inspector:

<img width="1090" alt="Screenshot 2024-03-20 at 17 12 58" src="https://github.com/appium/appium/assets/46964104/432d7566-a3d4-4a63-a3b9-66d616be1550">

**Comment by KazuCocoa** [comment]
Could you share the appium log with the inspector? I'll check paste case as well a bit later. 
https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#interact-with-dialogs-managed-by-comapplespringboard is maybe everything but the paste could have another case.

**Comment by rolandmoldovan** [comment]
Sure, there you go.
[appium.log](https://github.com/appium/appium/files/14669708/appium.log)

**Comment by KazuCocoa** [comment]
The case might be matched with:

> Start a session without appium:app nor appium:bundleId.

in https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#interact-with-dialogs-managed-by-comapplespringboard . Then, how about the script's appium log?

I wondered if `mobile:alert` with `buttonLabel: Allow Paste` could be the alternative method for the script run.

**Comment by rolandmoldovan** [comment]
You are right, works with:

```
await driver.getAlertText();
await driver.acceptAlert();
```

I got so focused on using the "com.apple.springboard" method for this permission dialog that I overlooked the simpler approach.

Thank you for your support!
