### ISSUE TITLE
 The selector "*" used with strategy "css selector" is invalid!

### ISSUE THREAD

**Issue by JaniceSaldanha03** [appium/appium#19903]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating Android studio version I encountered the above error. 
It's a node js code with appium framework. 

### Expected Behavior

na

### Minimal Reproducible Example

----Code Snippet for reference-------
const driver = require("webdriverio"); //webdriverio
const assert = require("assert");
const keycode = require('keycode');
const sleep = require('sleep-promise');
const colors = require('colors');
//const Database1 = require('./database_connection.js'); 
//const DATABASE = new Database1() 
const fs = require('fs');
const { default: click } = require("webdriverio/build/commands/element/click");
const { default: waitUntil } = require("webdriverio/build/commands/browser/waitUntil");
const { now } = require("moment");
const { addAbortSignal } = require("stream");

// Lenovo TB-8504F
// adbexectimeout: 20000,

const opts = {
  path: '/wd/hub',
  port: 5736,
  capabilities: {
    platformName: "Android",
    platformVersion: "10",
    deviceName: "HA1AMGE8",
    appPackage: "com.example.terraoperatorandroid2020",
    appActivity: "com.example.terraoperatorandroid2020.features.new_designs.main.MainActivityNd",
    automationName: "UiAutomator2",
    autoGrantPermissions: true,
    disableWindowAnimation: true,
    waitForIdleTimeout: 0,
    waitForQuiescence: false
  }
};

// -- Add any other needed values
const fixString = (string) => {
  string = string.replace("V", "");
  string = string.replace(" ", "");
  string = string.replace("%", "");
  string = string.replace("F", "");
  return string;
}

var total_testcases = 0;
var pass_testcases = 0;
var fail_testcases = 0;

exports.field_regression_flow = async function () {

  var timeBegin = (new Date()).getTime();
  var obj = JSON.parse(fs.readFileSync('./Configuration_ccr.json', 'utf8'));
  const Reporter = require('./testreport.js');
  const REPORTER = new Reporter('./', 'Field TestCases', `./Configuration_ccr.json`);
  const client = await driver.remote(opts);

  await client.setImplicitTimeout(10000);

  const result_table = (total_testcases, pass_testcases, fail_testcases) => {
    var total = total_testcases;
    var pass = pass_testcases;
    var fail = fail_testcases;
    REPORTER.writeResultEntry(total, pass, fail)

  }

  const testcase_name = (test_id, element, output, time_of_exec) => {
    var id = test_id
    var test_case = element
    var out = output
    var execution_time = time_of_exec

    REPORTER.writeSummaryEntry(id, test_case, out, execution_time)
    //DATABASE.tableEntry(id,test_case,out,execution_time)
  }

  const clickItem = async (client, element) => {
    var timeStart = (new Date()).getTime();
    await element.click();
    var timeStop = (new Date()).getTime();
    var id = "No ID";
    var issue = "-";
    try {
      id = await element.getAttribute("resourceId")
    } catch (e) {
      issue = "No ID found for element.";
    }
    var clientAct = await client.getCurrentActivity();
    REPORTER.writeExecutionTableEntry(clientAct, id, "Click", 'None', timeStop - timeStart, issue);
  }

  const moveElementByPercentage = async (client, element, px1, py1, px2, py2, msTime) => {
    var sizeJson = await element.getSize();
    var locJson = await element.getLocation();
    var x1 = ((px1 / 100) * sizeJson.width) + locJson.x;
    var y1 = ((py1 / 100) * sizeJson.height) + locJson.y;
    var x2 = ((px2 / 100) * sizeJson.width) + locJson.x;
    var y2 = ((py2 / 100) * sizeJson.height) + locJson.y;
    await moveTouch(client, x1, y1, x2, y2, msTime);
  }

  const holdTouch = async (client, x1, y1, msTime) => {
    await client.touchPerform([
      { action: 'press', options: { x: 300, y: 100 } },
      { action: 'wait', options: { ms: 10000 } },
      { action: 'release' }
    ]);
  }

  const holdTouchByPercentage = async (client, element, px1, py1, msTime) => {

    var timeStart = (new Date()).getTime();
    var sizeJson = await element.getSize();
    var locJson = await element.getLocation();
    var x1 = ((px1 / 100) * sizeJson.width) + locJson.x;
    var y1 = ((py1 / 100) * sizeJson.height) + locJson.y;

    await client.touchPerform([
      { action: 'press', options: { x: x1, y: y1 } },
      { action: 'wait', options: { ms: msTime } },
      { action: 'moveTo', options: { x: x1, y: y1 } },
      { action: 'release' }
    ]);
    var timeStop = (new Date()).getTime();

    REPORTER.writeExecutionTableEntry(await client.getCurrentActivity(), `x:${x1} y:${y1}`, "HoldTouch", `Time : ${String(msTime)}`, timeStop - timeStart, "-");
  }

  const moveTouch = async (client, x1, y1, x2, y2, msTime) => {
    var timeStart = (new Date()).getTime();
    await client.touchPerform([
      { action: 'press', options: { x: x1, y: y1 } },
      { action: 'wait', options: { ms: msTime } },
      { action: 'moveTo', options: { x: x2, y: y2 } },
      { action: 'release' }
    ]);
    var timeStop = (new Date()).getTime();
    REPORTER.writeExecutionTableEntry(await client.getCurrentActivity(), `x:${x1} y:${y1} -> x:${x2} y:${y2}`, "Move", `Time : ${String(msTime)}`, timeStop - timeStart, "-");

  }

  const waitForActivity = async (client) => {
    var timeStart = (new Date()).getTime();
    await client.$("*")
    var timeStop = (new Date()).getTime();
    REPORTER.writeExecutionTableEntry(await client.getCurrentActivity(), "None", "Wait", "", timeStop - timeStart, "-");
  }

  const findItemByName = async (client, className, text) => {
    var timeStart = (new Date()).getTime();
    const items = await client.$$(className);
    for (const item of items) {
      var itemText = (await item.getText());
      if (itemText == null) continue;
      if (itemText == text) {
        var timeStop = (new Date()).getTime();
        REPORTER.writeExecutionTableEntry(await client.getCurrentActivity(), `@text/${text}`, "Find", "", timeStop - timeStart, "-");
        return item;
      }
    }
    var timeStop = (new Date()).getTime();
    REPORTER.writeExecutionTableEntry(await client.getCurrentActivity(), `@text/${text}`, "Find", "", timeStop - timeStart, "NOT FOUND");
    return null;
  }

  const findItemById = async (client, className, id) => {
    var timeStart = (new Date()).getTime();
    const items = await client.$$(className);
    for (const item of items) {
      var itemText = (await item.getAttribute("resourceId"));
      if (itemText == null) continue;
      console.log(colors.cyan("ID : " + itemText));
      if (itemText.includes("id/" + id)) {
        var timeStop = (new Date()).getTime();
        REPORTER.writeExecutionTableEntry(await client.getCurrentActivity(), `@id/${id}`, "Find", "", timeStop - timeStart, "-");
        console.log(colors.yellow("Found : " + id));
        return item;
      }
    }
    var timeStop = (new Date()).getTime();
    REPORTER.writeExecutionTableEntry(await client.getCurrentActivity(), `@id/${id}`, "Find", "", timeStop - timeStart, "NOT FOUND");
    return null;
  }

  const findItem = async (client, className) => {
    return await client.$(className);
  }

  const readValueWaitFromElementMatch = async (client, element, matchValue, description, waitTimeMs) => {
    var timeStart = (new Date()).getTime();
    var waitDivides = parseInt(waitTimeMs / 200);
    var itemText = "";
    for (var i = 0; i < waitDivides; i++) {
      itemText = (await element.getText());
      if (String(itemText).replace(" ", "") == String(matchValue).replace(" ", "")) {
        break;
      }
      await sleep(200);
    }
    var timeStop = (new Date()).getTime();
    var act = await client.getCurrentActivity();
    var itemId = (await element.getAttribute("resourceId"));
    REPORTER.writeExecutionTableEntry(await client.getCurrentActivity(), itemId, "ReadValueWait", `Time : ${String(waitTimeMs)}`, timeStop - timeStart, "-");
    REPORTER.writeValuesTableEntry(act, `WaitMax(${waitTimeMs}) : ${description}`, itemText, matchValue, timeStop - timeStart);
  }

  const readValueWaitFromElementRange = async (client, element, lowerValue, higherValue, description, waitTimeMs) => {
    var timeStart = (new Date()).getTime();
    var waitDivides = parseInt(waitTimeMs / 200);
    var itemText = "";
    for (var i = 0; i < waitDivides; i++) {
      try {
        itemText = parseFloat(fixString(await element.getText()));
        if ((itemText) <= (higherValue) || (lowerValue) <= (itemText)) {
          break;
        }
      } catch (exception) {

      }
      await sleep(200);
    }
    if (String(itemText) == "NaN" || itemText == "") {
      itemText = await element.getText();
    }
    var timeStop = (new Date()).getTime();
    var act = await client.getCurrentActivity();
    var itemId = (await element.getAttribute("resourceId"));
    REPORTER.writeExecutionTableEntry(await client.getCurrentActivity(), itemId, "ReadRangeWait", `Time : ${String(waitTimeMs)}`, timeStop - timeStart, "-");
    REPORTER.writeReadValuesRangeLog(act, `WaitMax(${waitTimeMs}) : ${description}`, itemText, lowerValue, higherValue, timeStop - timeStart);
  }

  const readValueFromElementMatch = async (client, element, matchValue, description) => {
    var timeStart = (new Date()).getTime();
    var itemText = (await element.getText());
    var timeStop = (new Date()).getTime();
    var act = await client.getCurrentActivity();
    var itemId = (await element.getAttribute("resourceId"));
    REPORTER.writeExecutionTableEntry(await client.getCurrentActivity(), itemId, "ReadValue", '', timeStop - timeStart, "-");
    REPORTER.writeValuesTableEntry(act, description, itemText, matchValue, timeStop - timeStart);
    //  writeValuesTableEntry = (activity, description, valueRead, expectedValue, msTime)
  }

  const readValueFromElementRange = async (client, element, lowerValue, higherValue, description) => {
    var itemText = parseFloat(fixString(await element.getText()));
    // await client.getCurrentActivity() 
    // writeReadValuesRangeLog = (activity, description, valueRead, expectedValueLower, expectedValueHigher, msTime)
    var timeStart = (new Date()).getTime();
    var itemText = (await element.getText());
    var timeStop = (new Date()).getTime();
    var act = await client.getCurrentActivity();
    REPORTER.writeExecutionTableEntry(await client.getCurrentActivity(), itemId, "ReadValue", '', timeStop - timeStart, "-");
    REPORTER.writeReadValuesRangeLog(act, description, itemText, lowerValue, higherValue, timeStop - timeStart);

  }

  const setValueEditText = async (client, element, value) => {
    var timeStart = (new Date()).getTime();
    await element.setValue(value);
    var timeStop = (new Date()).getTime();
    var id = "No ID";
    var issue = "-";
    try {
      id = await element.getAttribute("resourceId")
    } catch (e) {
      issue = "No ID found for element.";
    }
    var clientAct = await client.getCurrentActivity();
    REPORTER.writeExecutionTableEntry(clientAct, id, "setValue", value, timeStop - timeStart, issue);
  }

  const findElementByIndex = async (client, className, index) => {
    var timeStart = (new Date()).getTime();
    const items = await client.$$(className);
    var timeStop = (new Date()).getTime();
    REPORTER.writeExecutionTableEntry(await client.getCurrentActivity(), `@ALL/${className}`, "Find", `Found ${items.length} items.`, timeStop - timeStart, "-");
    return items[index];
  }

  readAutomationFile = (automationFilePath) => {
    var obj = JSON.parse(fs.readFileSync(automationFilePath, 'utf8'));
    var keys = Object.keys(obj);
    console.log("mission name " + obj.mission_name);
    console.log("Keys " + keys);
    return {
      "keys": keys,
      "object": obj
    }
  }

  await waitForActivity(client);

 
  const types = await findItemById(client, "android.widget.TextView", "tv_robot_mode")

  if (types !== null) {//To check if user can view the Robot Type drop-down list
    var timeStart = (new Date()).getTime();
    const types1 = await findItemById(client, "android.widget.TextView", "tv_robot_mode")
    await types1.click()
    var timeEnd = (new Date()).getTime();

    if (types1 !== null) {
      total_testcases++;
      pass_testcases++;
      testcase_name("CCR", "To check if user can view the Robot Type drop-down list", "Pass", (((timeEnd - timeStart) % 60000) / 1000).toFixed(2))
      console.log(colors.yellow("Pass"))
    } else {
      total_testcases++;
      fail_testcases++;
      testcase_name("CCR", "To check if user can view the Robot Type drop-down list", "Fail", (((timeEnd - timeStart) % 60000) / 1000).toFixed(2))
      console.log(colors.red("Fail"))
      await waitForActivity(client)
    }

### Environment

- Operating system: Windows 11
npm version
8.19.4
node version
v16.15.0
appium version
1.12.0
webdriver io version
v7
- Real device

### Further Information

---Appium Server Logs---------
[HTTP] --> POST /wd/hub/session/667d7463-04d8-4e2c-8f30-b3c8eb73bfd1/element
[HTTP] {"using":"css selector","value":"*"}
[debug] [W3C (667d7463)] Calling AppiumDriver.findElement() with args: ["css selector","*","667d7463-04d8-4e2c-8f30-b3c8eb73bfd1"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [W3C (667d7463)] Encountered internal error running command: InvalidSelectorError: Locator Strategy 'css selector' is not supported for this session
[debug] [W3C (667d7463)]     at AndroidUiautomator2Driver.validateLocatorStrategy (C:\Users\pooja\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:344:13)
[debug] [W3C (667d7463)]     at AndroidUiautomator2Driver.validateLocatorStrategy [as findElOrElsWithProcessing] (C:\Users\pooja\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\find.js:28:8)
[debug] [W3C (667d7463)]     at AndroidUiautomator2Driver.findElOrElsWithProcessing [as findElement] (C:\Users\pooja\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\commands\find.js:50:21)
[debug] [W3C (667d7463)]     at C:\Users\pooja\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\basedriver\driver.js:291:18
[debug] [W3C (667d7463)]     at tryCatcher (C:\Users\pooja\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\util.js:26:23)
[debug] [W3C (667d7463)]     at Promise._settlePromiseFromHandler (C:\Users\pooja\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:510:31)
[debug] [W3C (667d7463)]     at Promise._settlePromiseAt (C:\Users\pooja\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:584:18)
[debug] [W3C (667d7463)]     at Promise._settlePromiseAtPostResolution (C:\Users\pooja\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\promise.js:248:10)
[debug] [W3C (667d7463)]     at Async._drainQueue (C:\Users\pooja\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:128:12)
[debug] [W3C (667d7463)]     at Async._drainQueues (C:\Users\pooja\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:133:10)
[debug] [W3C (667d7463)]     at Immediate.Async.drainQueues (C:\Users\pooja\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\node_modules\bluebird\js\main\async.js:15:14)
[debug] [W3C (667d7463)]     at processImmediate (node:internal/timers:466:21)
[HTTP] <-- POST /wd/hub/session/667d7463-04d8-4e2c-8f30-b3c8eb73bfd1/element 400 6 ms - 2325

**Comment by mykola-mokhnach** [comment]
Unfortunately we do not support Appium 1
Please update the driver and the server to the most recent version.

**Comment by JaniceSaldanha03** [comment]
The issue was fixed after updating the appium version
