### ISSUE TITLE
bug: "Error: Appium Settings app is not running after 30000ms"

### ISSUE THREAD

**Issue by QwetaDoja** [appium/appium#19909]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am facing an issue while executing my appium robot framework test script. 
I have a docker container in which an android emulator and appium server are running.
I am getting the following error "Appium Settings app is not running after 30000ms", I couldn't fix this issue after reading forums and trying everything and I am still getting the same issue while running my test script.

### Expected Behavior

I expect the test to pass without having errors.

### Environment

- Docker Base Image to run Appium: openjdk:18-jdk-slim
- Host OS : Windows
- Appium server version: 2.5.1
- Appium driver(s) and their version(s): uiautomator2@3.0.2
- Node.js version: v20.11.1
- `npm` version: 10.5.0
- Platform and version under test: google pixel 4 xl  & android version 14 (api level 34)
- Real device or emulator/simulator: Emulator

### Link to Appium Logs

https://gist.github.com/QwetaDoja/a51f7d48c340555373d52989129786f4

### Further Information

adb logcat logs: https://gist.github.com/QwetaDoja/ae3bfafc381c41891c5fdc9dd4ecb33e

**Comment by mykola-mokhnach** [comment]
Unfortunately the provided logcat does not contain any details about Settings app execution. Please make sure it is taken for the correct time range. You may also try to run the app manually and see if it shows any explicit error messages

**Comment by QwetaDoja** [comment]
> Unfortunately the provided logcat does not contain any details about Settings app execution. Please make sure it is taken for the correct time range. You may also try to run the app manually and see if it shows any explicit error messages

New adb logcat logs : https://gist.github.com/QwetaDoja/7a1f850d0d5bd089e8a4b01e2bd79f3c, the error happened at 10:52:46. When I install and run the app manually, I don't get any error messages.

**Comment by mykola-mokhnach** [comment]
I still cannot see any traces of the settings app, but like it was mentioned above I can observe multiple traces of slowness issues and related crash reports:

> 03-21 10:50:00.158  1852  1879 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.location.geocode.GeocodeService in 132229ms for connection

I don't think there is anything we could help with the given information.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by SanskarTx** [comment]
I am also getting the same issue .
I want to run the emultaor in headless , but in doing so i am getting the issue as

“Error: Appium Settings app is not running after 30000ms” while everything is running fine when i am not using headless mode.
I had attached the appium logs .
I am using appium version 2.5.4 and appium java client 9.2.2
In my case when i am running adb logcat to see the logs in that case sometimes .I am not getting this issue.
[Appium logs.txt](https://github.com/appium/appium/files/15220501/Appium.logs.txt)
