### ISSUE TITLE
bug: <title>appium server session error

### ISSUE THREAD

**Issue by shoumik121** [appium/appium#19902]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

C:\Users\TalentPro>appium
[Appium] Welcome to Appium v2.5.1
[Appium] The autodetected Appium home path: C:\Users\TalentPro
[Appium] Attempting to load driver flutter...
[Appium] Attempting to load driver uiautomator2...
[Appium] Requiring driver at C:\Users\TalentPro\node_modules\appium-flutter-driver\build\lib\driver.js
[Appium] Requiring driver at C:\Users\TalentPro\node_modules\appium-uiautomator2-driver\build\index.js
[Appium] FlutterDriver has been successfully loaded in 2.659s
[Appium] AndroidUiautomator2Driver has been successfully loaded in 2.660s
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium]        http://192.168.10.13:4723/
[Appium]        http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] Available drivers:
[Appium]   - flutter@2.5.0 (automationName 'Flutter')
[Appium]   - uiautomator2@3.0.0 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> GET /session/ee5f3952-7d67-4ab1-8c0d-88a339032e86/timeouts
[HTTP] {}
[AppiumDriver@583d] Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started
[AppiumDriver@583d]     at asyncHandler (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:315:15)
[AppiumDriver@583d]     at C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:518:15
[AppiumDriver@583d]     at Layer.handle [as handle_request] (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[AppiumDriver@583d]     at next (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\route.js:144:13)
[AppiumDriver@583d]     at Route.dispatch (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\route.js:114:3)
[AppiumDriver@583d]     at Layer.handle [as handle_request] (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[AppiumDriver@583d]     at C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:284:15
[AppiumDriver@583d]     at param (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:365:14)
[AppiumDriver@583d]     at param (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:376:14)
[AppiumDriver@583d]     at Function.process_params (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:421:3)
[AppiumDriver@583d]     at next (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:280:10)
[AppiumDriver@583d]     at logger (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\morgan\index.js:144:5)
[AppiumDriver@583d]     at Layer.handle [as handle_request] (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[AppiumDriver@583d]     at trim_prefix (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:328:13)
[AppiumDriver@583d]     at C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:286:9
[AppiumDriver@583d]     at Function.process_params (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:346:12)
[AppiumDriver@583d]     at next (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:280:10)
[AppiumDriver@583d]     at jsonParser (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\body-parser\lib\types\json.js:113:7)
[AppiumDriver@583d]     at Layer.handle [as handle_request] (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[AppiumDriver@583d]     at trim_prefix (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:328:13)
[AppiumDriver@583d]     at C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:286:9
[AppiumDriver@583d]     at Function.process_params (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:346:12)
[AppiumDriver@583d]     at next (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:280:10)
[AppiumDriver@583d]     at Layer.handle [as handle_request] (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:91:12)
[AppiumDriver@583d]     at trim_prefix (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:328:13)
[AppiumDriver@583d]     at C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:286:9
[AppiumDriver@583d]     at Function.process_params (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:346:12)
[AppiumDriver@583d]     at next (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:280:10)
[AppiumDriver@583d]     at methodOverride (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\method-override\index.js:65:14)
[AppiumDriver@583d]     at Layer.handle [as handle_request] (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[AppiumDriver@583d]     at trim_prefix (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:328:13)
[AppiumDriver@583d]     at C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:286:9
[AppiumDriver@583d]     at Function.process_params (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:346:12)
[AppiumDriver@583d]     at next (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:280:10)
[AppiumDriver@583d]     at urlencodedParser (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\body-parser\lib\types\urlencoded.js:91:7)
[AppiumDriver@583d]     at Layer.handle [as handle_request] (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[AppiumDriver@583d]     at trim_prefix (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:328:13)
[AppiumDriver@583d]     at C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:286:9
[AppiumDriver@583d]     at Function.process_params (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:346:12)
[AppiumDriver@583d]     at next (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:280:10)
[AppiumDriver@583d]     at defaultToJSONContentType (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\express\middleware.js:58:3)
[AppiumDriver@583d]     at Layer.handle [as handle_request] (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\layer.js:95:5)
[AppiumDriver@583d]     at trim_prefix (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:328:13)
[AppiumDriver@583d]     at C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:286:9
[AppiumDriver@583d]     at Function.process_params (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:346:12)
[AppiumDriver@583d]     at next (C:\Users\TalentPro\AppData\Roaming\npm\node_modules\appium\node_modules\express\lib\router\index.js:280:10)
[HTTP] <-- GET /session/ee5f3952-7d67-4ab1-8c0d-88a339032e86/timeouts 404 34 ms - 6771
[HTTP]
[HTTP] --> GET /session/ee5f3952-7d67-4ab1-8c0d-88a339032e86/timeouts

![image](https://github.com/appium/appium/assets/52488167/fd06c6b2-99d0-43d0-b722-0b2cfff18389)

### Expected Behavior

C:\Users\TalentPro>appium
[Appium] Welcome to Appium v2.5.1
[Appium] The autodetected Appium home path: C:\Users\TalentPro
[Appium] Attempting to load driver flutter...
[Appium] Attempting to load driver uiautomator2...
[Appium] Requiring driver at C:\Users\TalentPro\node_modules\appium-flutter-driver\build\lib\driver.js
[Appium] Requiring driver at C:\Users\TalentPro\node_modules\appium-uiautomator2-driver\build\index.js
[Appium] FlutterDriver has been successfully loaded in 2.605s
[Appium] AndroidUiautomator2Driver has been successfully loaded in 2.605s
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium]        http://192.168.10.13:4723/
[Appium]        http://127.0.0.1:4723/ (only accessible from the same host)
[Appium] Available drivers:
[Appium]   - flutter@2.5.0 (automationName 'Flutter')
[Appium]   - uiautomator2@3.0.0 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.

### Minimal Reproducible Example

just install appium 2.5.1

and got to cmd run>> appium

for more info
https://github.com/appium/appium/discussions/19901

### Environment

- Operating system:
- Appium server version (output of `appium --v 2.5.1`):
- Appium driver(s) and their version(s): 
      uiautomator2 version -3.0.2
      flutter driver version -2.5.0
- Appium plugin(s) and their version(s):
      NA
- Node.js version (output of `node --v 18.18.1`):
- `npm` version (output of `npm --v 10.2.0`):
- Last component(s) version which did _not_ exhibit the problem: in same versions 2 days earlier
- Platform and version under test:
- Real mobile device -Xiomi redmi A10
- Operating system -windows 10
- Ide -IntelIJ
- JDK - 17

### Link to Appium Logs
I don't know how to put it!
https://github.com/appium

### Further Information

I also created a discussion about it if i am not wrong
https://github.com/appium/appium/discussions/19901

**Comment by shoumik121** [comment]
appium version -2.5.1
uiautomator2 version -3.0.2
flutter driver version -2.5.0
node version -18.18.1
operating system -windows 10
mobile device -Xiomi redmi A10
Ide -IntelIJ
jdk -17

**Comment by mykola-mokhnach** [comment]
The error message looks totally valid to me. The client tries to send a session command without actually creating a session.

**Comment by shoumik121** [comment]
Today I tried running the same test cases & everything went perfect with the same code base. It was such a relief & I thank the Appium team and it's all contributors, programmers, engineers.
Thank you for your attention to this matter. Best wishes
