### ISSUE TITLE
[Feat]: Enroll biometrics on a single simulator

### ISSUE THREAD

**Issue by lhimo** [appium/appium#19912]
We are running Appium tests on a mac runner, using Pabot to run them on more than one simulator simultaneously. 

A few scenarios are enrolling faceId but doing so with the script `mobile: enrollBiometric` interferes with other simulators. Would it be possible to run a command like the following in order to enable it only on a given device?

```
xcrun simctl spawn "{simulator name}" notifyutil -s com.apple.BiometricKit.enrollmentChanged "{value}" && xcrun simctl spawn "{simulator name}" notifyutil -p com.apple.BiometricKit.enrollmentChanged
```

**Comment by mykola-mokhnach** [comment]
Sorry, I don't understand what the issue is. biometric enrolment is already done like that: https://github.com/appium/appium-ios-simulator/blob/723f16f0f08f24a92c23ac70ce18261e3378f8c8/lib/simulator-xcode-9.js#L449

**Comment by lhimo** [comment]
I think we got this wrong, thanks for checking!
