### ISSUE TITLE
[Feat]: Is it possible to display the version number within the WebDriverAgent (WDA) service API.

### ISSUE THREAD

**Issue by youngfreeFJS** [appium/appium#19921]
**Is your feature request related to a problem? Please describe.**
This will help me handle the incompatible upgrade logic of the WDA interface. Like ```/tap/0``` to ```/tap```

**Describe the solution you'd like**
add version in /status API or add /version API.

**Comment by youngfreeFJS** [comment]
Any feedback would be appreciated. 😊 @KazuCocoa

**Comment by KazuCocoa** [comment]
No, for now.
`CFBundleVersion` in info.plist as config is set 1 in test bundle (by xcodebuild) so we cannot use general method to configure app version.

You may be able to forcefully set `CFBundleVersion` in the info.plist by directly modifying on your local (after creating  WDA package, not before building) and refer to the version info via https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-listapps . This method does not require Appium's modification.

Or we possibly could hardcode version in WDA's code internally and reply the number for `/status` endpoint. In this case, we must add automatic increment somehow to not forget the version info incrementation.

**Comment by youngfreeFJS** [comment]
> 不，暂时。 `CFBundleVersion`在 info.plist 中，因为测试包中的配置设置为 1（由 xcodebuild），因此我们不能使用通用方法来配置应用程序版本。
> 
> 您可以通过直接在本地修改（创建 WDA 包之后，而不是构建之前）来强制设置info.plist，并通过[https://appium.github.io/appium-xcuitest-driver](https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-listapps)`CFBundleVersion`参考版本信息[/latest/reference/execute-methods/#mobile-listapps](https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-listapps)。该方法不需要Appium的修改。
> 
> 或者我们可以在 WDA 代码内部对版本进行硬编码，并回复`/status`端点的号码。在这种情况下，我们必须在 WDA 的代码中以某种方式添加自动递增数字，以免忘记版本信息递增。

I prefer the second, it avoids modifying the WDA source code and is more general. For now, could auto update version use Github Action at release node :) @KazuCocoa

**Comment by youngfreeFJS** [comment]
> No, for now. `CFBundleVersion` in info.plist as config is set 1 in test bundle (by xcodebuild) so we cannot use general method to configure app version.
> 
> You may be able to forcefully set `CFBundleVersion` in the info.plist by directly modifying on your local (after creating WDA package, not before building) and refer to the version info via https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-listapps . This method does not require Appium's modification.
> 
> Or we possibly could hardcode version in WDA's code internally and reply the number for `/status` endpoint. In this case, we must add automatic increment the number somehow in WDA's code to not forget the version info incrementation.

I prefer the second, it avoids modifying the WDA source code and is more general. For now, could auto update version use Github Action at release node :) @KazuCocoa

**Comment by youngfreeFJS** [comment]
when WDA project release, create a version number file in package.json through the github action, and the ```FBSessionCommands.m#handleGetStatus``` method get this version number from the file?

**Comment by mykola-mokhnach** [comment]
I think it would be possible to do something like that, but the support would be limited. The version change itself should be a part of the version bump script, similarly to how it's done for Android packages (https://github.com/appium/io.appium.settings/blob/master/scripts/gradle-version-update.js or https://github.com/appium/appium-uiautomator2-server/blob/master/scripts/gradle-version-update.js)

**Comment by mykola-mokhnach** [comment]
Prepared https://github.com/appium/WebDriverAgent/pull/878

**Comment by mykola-mokhnach** [comment]
Closed as resolved
