### ISSUE TITLE
bug: getWindowHandles return 1 when open a new window on Safari (iOS 17.4)

### ISSUE THREAD

**Issue by gnoucoad** [appium/appium#19924]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot switch to latest tab and handle elements there
- Open https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target
- Click home button with id="tryhome" (New window will opened)
- New window is opened but getWindowHandles always return 1

### Expected Behavior

getWindowHandles return 2 and be able to handle elements in latest tab

### Minimal Reproducible Example

```java
            driver.get("https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_target");
            Thread.sleep(2000);
            WebElement home = driver.findElement(By.id("tryhome"));
            driver.setSettings(new HashMap<>() {{
                put("nativeWebTap", true);
                put("nativeWebTapStrict", true);
            }});
            home.click();
            driver.setSettings(new HashMap<>() {{
                put("nativeWebTap", false);
                put("nativeWebTapStrict", false);
            }});
            Thread.sleep(4000);
            Set<String> handles =  driver.getWindowHandles();
            System.out.println("WindowHandles Size: "+handles.size());
```

### Environment

- Operating system: MacOS 14.2（23C64）
- Appium server version (output of `appium --version`): 2.5.1
- Appium driver(s) and their version(s): xcuitest@7.5.4
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): 20.11.1
- `npm` version (output of `npm --version`): 10.2.4
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: IOS 17.4
- Real device or emulator/simulator: Real device 

### Further Information

Click command succeeds and new window is opened but no new window handle
The problem doesn't happen on iOS 17.2 and older IOS version.

**Appium logs**
[Appium logs](https://github.com/appium/appium/files/14752198/getwindowhandles.log)

**Comment by Dan-Maor** [comment]
I've ran this flow manually on my iOS 17.5 device without Appium, the issue is reproducible with the Safari web inspector it self (the page is not inspectable in the pages list).

**Comment by mykola-mokhnach** [comment]
Thanks for checking it @Dan-Maor 
In such case I don't think we can do anything on our side. It may only be reported as an issue to Apple.

**Comment by DukeYe** [comment]
@mykola-mokhnach I wonder if apple has fixed this issue? thank you
