### ISSUE TITLE
WebDriverAgent use-prebuilt-wda is broken

### ISSUE THREAD

**Issue by johanblumenberg** [appium/appium#19923]
## Description

Using `use-prebuilt-wda` seems to be broken.

The project inside `~/Library/Developer/Xcode/DerivedData` is cleared when starting, and then the process fails when trying to install WDA.

The root cause is probably that the call to `box.getItem()` in [^1] will always return `undefined`. The `@appium/strongbox` API is not very well documented, but looking at the implementation of `getItem()` at [^2], it will probably always return `undefined`. The collection of items is empty on creation, and the only way to add an item is to call one of the create methods.

The result is that after the if statement in [^3] is executed, the recent module version is always either the hardcoded `5.0.0` version if the timestamp file did exist, or the current version if it did not exist. This means that:
- If the timestamp file did exist, it will always clean the project. This means that `use-prebuilt-wda` is broken, and that building WDA never uses incremental builds, being slower than necessary.
- If the timestamp file did not exist, it will never clean the project. I think this means that old stuff is kept when the WDA is upgraded, which I think is the problem that this code tries to solve.

[^1]: https://github.com/appium/WebDriverAgent/blob/411669b2ef4760b8aff324d642c0e21cb8ecd4da/lib/webdriveragent.js#L236
[^2]: https://github.com/appium/appium/blob/63d7550d02f049a5c3bea5d27e7e8385d7698a4f/packages/strongbox/lib/index.ts#L260
[^3]: https://github.com/appium/WebDriverAgent/blob/b23b38a13ae5864842ed38792d9fae1dae7297a6/lib/webdriveragent.js#L236

**Comment by mykola-mokhnach** [comment]
strongbox is just a simple key-value storage, which should persist between appium resinstalls. The idea behind this code is to perform project cleanup after webdriveragent upgrade. The `getItem` API returns undefined if no value has been written to the box previously (e.g. WDA has never been built successfully on the platform with xCode). Perhaps, the right fix there would be to add one more condition to https://github.com/appium/WebDriverAgent/blob/411669b2ef4760b8aff324d642c0e21cb8ecd4da/lib/webdriveragent.js#L230, so it returns without performing the cleanup if prebuilt WDA is requested. WDYT @KazuCocoa ?

**Comment by mykola-mokhnach** [comment]
@johanblumenberg  Could you also provide the full server log and point out where exactly in the log the unexpected behaviour is observed?

**Comment by KazuCocoa** [comment]
> it returns without performing the cleanup if prebuilt WDA is requested

yea, it sounds reasonable to me

**Comment by KazuCocoa** [comment]
btw, we already skip the cleanup when `(this.derivedDataPath && this.usePrebuiltWDA)` which indicates clearly the client manages the path.

```
    if (this.idb || this.useXctestrunFile || (this.derivedDataPath && this.usePrebuiltWDA)) {
      this.log.info('Skipped WDA project cleanup according to the provided capabilities');
    } else {
      const synchronizationKey = path.normalize(this.bootstrapPath);
      await SHARED_RESOURCES_GUARD.acquire(synchronizationKey,
        async () => await this._cleanupProjectIfFresh());
    }
```

https://github.com/appium/WebDriverAgent/blob/411669b2ef4760b8aff324d642c0e21cb8ecd4da/lib/webdriveragent.js#L420C1-L426C6

The usage is addressed in:

> The same thing can be achieved with the appium:derivedDataPath and appium:usePrebuiltWDA capabilities, but this may fail if xcodebuild cannot find or handle the .xctestrun file properly. The stability depends on Xcode.

https://appium.github.io/appium-xcuitest-driver/latest/guides/run-prebuilt-wda/#capabilities-for-prebuilt-wda

Perhaops we could address the usage in the capabilities as well(?), although full appium log may help to check the capabilities set

**Comment by johanblumenberg** [comment]
@mykola-mokhnach 

> The getItem API returns undefined if no value has been written to the box previously 

If you check the implementation of `getItem()` it doesn't read any existing value. It only checks if an item is present the `this.items` collection. I don't see where this is populated, unless you call any of the create methods first.

https://github.com/appium/appium/blob/63d7550d02f049a5c3bea5d27e7e8385d7698a4f/packages/strongbox/lib/index.ts#L260

**Comment by johanblumenberg** [comment]
@KazuCocoa 

> btw, we already skip the cleanup when (this.derivedDataPath && this.usePrebuiltWDA) which indicates clearly the client manages the path.

This requires that you set both the `usePrebuiltWDA` and `derivedDataPath` capabilities.

In my case I am happy to use the path to the already built WDA inside `~/Library/Developer/Xcode/DerivedData`, so I have set `usePrebuiltWDA` to `true` but I have not set any value for `derivedDataPath`.

This means that I need to run once having `usePrebuiltWDA` set to `false`, to build and use the version of WDA that is bundled with `appium`. After that I can run with `usePrebuiltWDA` set to `true`.

Is it a requirement that whenever you set `usePrebuiltWDA` you must also use a manually downloaded WDA?

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach
> 
> > The getItem API returns undefined if no value has been written to the box previously
> 
> If you check the implementation of `getItem()` it doesn't read any existing value. It only checks if an item is present the `this.items` collection. I don't see where this is populated, unless you call any of the create methods first.
> 
> https://github.com/appium/appium/blob/63d7550d02f049a5c3bea5d27e7e8385d7698a4f/packages/strongbox/lib/index.ts#L260

Not sure what you mean under `doesn't read any existing value`. 

```
    const ref = this.items.get(id);
    return ref?.deref();
```

here we get the value of a weak reference

**Comment by johanblumenberg** [comment]
@mykola-mokhnach The call to `this.items.get(id)` returns `undefined`. The `this.items` value is a `Map` with no items in it. The `this.items` collection is only populated if you call any of the create methods. If you don't, it will be empty.

Here for example:
https://github.com/appium/appium/blob/63d7550d02f049a5c3bea5d27e7e8385d7698a4f/packages/strongbox/lib/index.ts#L211

**Comment by KazuCocoa** [comment]
With `usePrebuiltWDA`, appium uses `build-for-testing` so if the project does not have prebuilt modules, the xcodebuild itself may fail. Local Xcode could randomly generates the build place and re-use it but it depends on the Xcode/xcodebuild itself. We usually recommend using `appium:useXctestrunFile` and `appium:bootstrapPath` or `appium:derivedDataPath` and `appium:usePrebuiltWDA` to control the build place. Hm, then maybe it would be nice to address it in capabilities as well. (the original implementation was maybe old, so we haven't documented it well)
https://appium.github.io/appium-xcuitest-driver/latest/guides/run-prebuilt-wda/

> This means that I need to run once

I guess yes. The prebuild caps expects a directory generated by `xcodebuild`. Maybe Appium does not have explicit capability to run xcodebuild first fully, and run with prebuilt option after the first run., such a behavior.


in your case, I wondered if https://appium.github.io/appium-xcuitest-driver/latest/guides/run-preinstalled-wda/ would also help.

I need to check and write down documentation but recently we added the availability for simulators. https://github.com/appium/appium-xcuitest-driver/pull/2345
Then `prebuiltWDAPath` with https://github.com/appium/WebDriverAgent/actions/workflows/wda-package.yml prebuild wda package would help. It may reduce xcodebuild running time completely.

**Comment by johanblumenberg** [comment]
@KazuCocoa 

If I understand correctly, I have these options:

1. Use `appium:derivedDataPath` together with `appium:usePrebuiltWDA`. In this case I cannot rely on the default value being set for `appium:derivedDataPath`, I need to set it explicitly.
2. Use `appium:useXctestrunFile` and `appium:bootstrapPath`. In this case I should first build WDA once, and copy the required files to `appium:bootstrapPath`.
3. Download a prebuilt WDA and make sure it is preinstalled on the device, using `appuim:prebuiltWDAPath`, or to have it installed using `appium:prebuiltWDAPath`.

Using (2) or (3) means I have to manage the WDA version myself, but (1) would mean that when I upgrade `appium-xcuitest-driver`, either directly or indirectly, I would automatically get a matching version of WDA.

Also, if I understand correctly, the reason that I cannot rely on the default value for `appium:derivedDataPath` is the bug described above in this ticket?


I can certainly work with any of these options.

It's just quite annoying when you try to upgrade a dependency, and then everything breaks because somewhere you indirectly got a new minor version of the WDA, where everything has changed.

**Comment by KazuCocoa** [comment]
I haven't tested/tuned yet, but perhaps  https://github.com/appium/appium-xcuitest-driver/compare/tune-useprebuiltwda?expand=1 could help a few with/without `appium:derivedDataPath`. Without `derivedDataPath` is the best guess.

**Comment by KazuCocoa** [comment]
`appium:prebuildWDA` capability may help, btw. I found that it was added long before: https://github.com/appium/appium-xcuitest-driver/pull/2375 . Latest XCUITest driver and the caps would help for the case.
