### ISSUE TITLE
[iOS] bug: executing script 'mobile: swipe' with no element specified fails proxying to unknown route /wda/swipe 

### ISSUE THREAD

**Issue by szarlatan** [appium/appium#19932]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Having following input for the `executeScript('mobile: swipe')`
```
{ "direction": "down", "velocity": 1000 }
```
action fails with following output
```
Got response with status 404: {
    "value": {
        "error": "unknown command",
        "message": "Unhandled endpoint: /session/C9717BDA-07ED-4B07-BCEA-7D48EAB1E2E9/wda/swipe -- http://127.0.0.1:8100/ with parameters {
    wildcards =  (\"session/C9717BDA-07ED-4B07-BCEA-7D48EAB1E2E9/wda/swipe\");
}",
        "traceback":""
    },
    "sessionId":"C9717BDA-07ED-4B07-BCEA-7D48EAB1E2E9"
}
```

### Expected Behavior

I would expect that swipe action was executed on entire screen rectangle.

### Minimal Reproducible Example

`await driver.executeScript('mobile: swipe', [{ "direction": "up" }])`

### Environment

- Operating system: Sonoma 14.3.1 (23D60)
- Appium server version (output of `appium --version`): 2.5.1
- Appium driver(s) and their version(s): xcuitest@7.7.0
- Appium plugin(s) and their version(s): n/a
- Node.js version (output of `node --version`): v.18.17.0
- `npm` version (output of `npm --version`): v.9.6.7
- Last component(s) version which did _not_ exhibit the problem: unknown
- Platform and version under test: iOS 17.4
- Real device or emulator/simulator: iPhone 12 mini

### Link to Appium Logs

https://gist.github.com/szarlatan/5834da0c0d70ffb8b65c3fed75d480d1

### Further Information

According to [documentation](https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-swipe):
> This gesture performs a simple "swipe" gesture on the particular screen element or on the application element, which is usually the whole screen. This method does not accept coordinates and simply emulates single swipe with one finger.

**Comment by mykola-mokhnach** [comment]
It looks like the device has an older WDA cached. Try to clear the Xcode caches and rebuild/install WDA manually

**Comment by szarlatan** [comment]
You're right. For some reason we had `"appium-webdriveragent": "^5.15.5"` defined in root package.json resolutions. Without it everything is working as expected 👍
