### ISSUE TITLE
bug: minor documentation syntax issue

### ISSUE THREAD

**Issue by fire332** [appium/appium#19942]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [x] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The [basic requirements section in build-drivers](https://github.com/appium/appium/blob/9a0c059c3ae3f762fa31b91eb903fd76e827f96d/packages/appium/docs/en/developing/build-drivers.md#nodejs-package-with-appium-extension-metadata) has a broken code block.

    ```json
    {
      ...,
      "appium": {
        "driverName": "fake",
        "automationName": "Fake",
        "platformNames": [
          "Fake"
        ],
        "mainClass": "FakeDriver"
      },
      ...
    }
    ```

### Expected Behavior

```json
{
  ...,
  "appium": {
    "driverName": "fake",
    "automationName": "Fake",
    "platformNames": [
      "Fake"
    ],
    "mainClass": "FakeDriver"
  },
  ...
}
```

### Minimal Reproducible Example

N/A

**Comment by mykola-mokhnach** [comment]
Thanks for the heads-up. We'd appreciate it if you could create a PR and fix the doc.

**Comment by mykola-mokhnach** [comment]
That was quick :)
Thanks
