### ISSUE TITLE
[Feat]:"Automaton Running hold both volume buttons to stop"

### ISSUE THREAD

**Issue by LiuShuai66** [appium/appium#19952]
**Is your feature request related to a problem? Please describe.**
Run WebDriverAgent Run screen appears' auto run by pressing two volume buttons stop 'prompt content how to fix

**Describe the solution you'd like**
 mask"Automaton Running hold both volume buttons to stop"

**Describe alternatives you've considered**
I tried to locate automation running's controller and look at the xctest library

**Additional context**

**Comment by KazuCocoa** [comment]
Possible duplicate of https://github.com/appium/appium/issues/15898 If you meant to not show the overlay, it is not possible because of Apple's limitation.
