### ISSUE TITLE
bug: Continuously getting alert text in webview

### ISSUE THREAD

**Issue by TheXby** [appium/appium#19960]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have hybrid app with a lot of webview contexts. Currently on iOS version, randomly i start getting messages that unable to get alert text. But there are no alerts at all. Also, i don't get any alert text explicitly.
When this message came to log, test start to run slowly and slowly. Sometimes it stops.

### Expected Behavior

Test should work smoothly

### Minimal Reproducible Example

No code, sorry, really it happens at random places.

### Environment

- Operating system: MacOs 14.3.1
- Appium server version 2.5.1
- Appium driver(s) and their version(s): xcuitest@7.9.1 
- Appium plugin(s) and their version(s): no
- Node.js version (output of `node --version`): v21.7.1
- `npm` version (output of `npm --version`): 10.5.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: simulator

### Link to Appium Logs

https://gist.github.com/TheXby/c86b66469d38cb0192f99ee5009af0fb

**Comment by mykola-mokhnach** [comment]
This is expected. While we are waiting for a response from the remote debugger for more than (1 second) we start checking the native context for possible alerts and throw an exception upon timeout. Such alerts would block any interaction with the remote debugger if present.

**Comment by TheXby** [comment]
@mykola-mokhnach 
So slowleness of tests execution doesn't depend on this behavior?
