### ISSUE TITLE
[Feat]: documentation does not remind users that they have to start the server by actually running "appium".

### ISSUE THREAD

**Issue by zaphodikus** [appium/appium#19973]
**Is your feature request related to a problem? Please describe.**
documentation does not remind users that they have to start the server by actually running "appium".

**Describe the solution you'd like**
Update the get started to actually explain what happens after they start the server and draw their attention to the console window so they remember that step, it's probably the biggest blocker to getting a test running and generates far too many forum questions. Maybe even make them understand what the log levels are and they will then always remember to check that the window has not hung or shows any errors.

**Describe alternatives you've considered**
I use a tool to do this for me, but most of the questions on forums are people who dont know and don't use a tool

**Additional context**
None

**Comment by eglitise** [comment]
[It does already say this in the Installation part](http://appium.io/docs/en/latest/quickstart/install/). Or is there another page you were thinking of?

**Comment by zaphodikus** [comment]
It then continues to tell you to stop the server.
"That's it! If you see this, the Appium server is up and running. Go ahead and quit it (Ctrl-C) and move on to the next step"

Now I've seen so many forum threads where people make the assumption that the test engine clients will start the server for you since it's just one command. Being able to pass in a port number for example is critical to being able to make really useful remote machine connections later, which are the true power of the driver server. The quick start guide is all about simple local connections only, but we need to remind users to check and start the server whenever it hangs up or errors out, and not wait for the client driver to error with an invalid session message.

**Comment by eglitise** [comment]
Thanks, I see what you mean and I fully agree that this should be clarified.
