### ISSUE TITLE
Appium and Appium Inspector cannot detect my iOS device (using xcuitest 7.10.0 on iPhone 14 iOS 16.6.1)

### ISSUE THREAD

**Issue by murigregori** [appium/appium#19980]
Hello. I encountered a pretty weird scenario today. I connected my iPhone 14 device to check some automation elements on the appium inspector. I updated my xcuitest driver to 7.10.0 and proceeded to check on appium inspector. However, it gives out this error even if my device is connected to my Macbook.

<img width="1127" alt="Screenshot 2024-04-08 at 3 09 05 PM" src="https://github.com/appium/appium/assets/20291195/764166b8-0b8d-4eb9-a68b-898834aaed82">

This issue just happened today after upgrading my xcuitest driver. I checked in the Finder and the device is connected to my macbook

<img width="924" alt="Screenshot 2024-04-08 at 3 10 17 PM" src="https://github.com/appium/appium/assets/20291195/5833719e-0ba0-4e2d-a28f-8f4e9e1a05d2">
<img width="1342" alt="Screenshot 2024-04-08 at 3 09 17 PM" src="https://github.com/appium/appium/assets/20291195/10155633-9820-46dc-9716-8d64fdad31ed">

Here are the appium driver versions i use btw: 
<img width="1342" alt="Screenshot 2024-04-08 at 3 09 48 PM" src="https://github.com/appium/appium/assets/20291195/4642f02a-91e4-48bc-ae1d-56b8bfbc5d6a">

I tried checking if it also happens with my android devices just to check if my ports are the ones having the issue but Android is working as expected. 

Hopefully this reaches someone who's encountered this problem.  Thank you!

**Comment by mykola-mokhnach** [comment]
There was a regression issue in the recent xcuitest driver patch. Please update to version 7.11.1+

**Comment by murigregori** [comment]
All good once I updated to 7.11.1. Thanks for the help!
