### ISSUE TITLE
iOS real device test screen recording 0 bytes

### ISSUE THREAD

**Issue by zhouhyi** [appium/appium#19987]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running the test on an iOS real device, using driver.startRecordingScreen() to start video recording and driver.stopRecordingScreen() to end it, but the final video file is 0 bytes. Could anyone help check this issue?
<img width="861" alt="image" src="https://github.com/appium/appium/assets/28880427/e4a58aad-819e-4022-a538-e5412a7e9bd1">

And check the appium service log and find the following exception information:
`[38;5;96m[DevCon Factory] [0m Releasing connections for 00008020-000248E602D8002E device on 9100 port number
[38;5;96m[DevCon Factory] [0m No cached connections have been found
[38;5;64m[XCUITest] [0m The size of the file is 0 B`
![image](https://github.com/appium/appium/assets/28880427/e450b162-cd39-457d-a637-c8c69df4118b)

### Expected Behavior

Get a video from start screen recording to end screen recording.

### Minimal Reproducible Example

```
// start
((IOSDriver) WebDriverUtils.getDriver()).startRecordingScreen(new IOSStartScreenRecordingOptions().withVideoQuality(IOSStartScreenRecordingOptions.VideoQuality.LOW).withFps(4).withVideoType("h264").withVideoScale("trunc(iw/2)*2:trunc(ih/2)*2").withTimeLimit(
                    Duration.ofMinutes(30)));
                    
// The testing process is omitted here

// stop
String video = ((CanRecordScreen) WebDriverUtils.getDriver()).stopRecordingScreen();
String filename = "videoRecording_" + System.getProperty("appium.deviceName") + ".mp4";
FileUtils.writeByteArrayToFile(new File(filename),  Base64.getMimeDecoder().decode(video)); 
                   
```

### Environment

- Operating system:
- Appium server version (output of `appium --version`):2.2.3
- Appium driver(s) and their version(s): xcuitest@5.11.8
- Node.js version (output of `node --version`): v20.8.0
- `npm` version (output of `npm --version`): 10.1.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:  iPhone XR IOS 17.0
- Real device or emulator/simulator: Real device
- Selenium version: 4.9.1
- java-client version: 8.5.0
- ffmpeg version: 6.0

### Further Information

[recording_appium_server.log](https://github.com/appium/appium/files/14928808/recording_appium_server.log)

**Comment by mykola-mokhnach** [comment]
> [38;5;96m[DevCon Factory][0m Requesting connection for device 00008020-000248E602D8002E on local port 9100, device port 9100
> [38;5;96m[DevCon Factory][0m Cached connections count: 1
> [38;5;96m[DevCon Factory][0m Port #9100 is busy. Did you quit the previous driver session(s) properly?
> [38;5;32m[XCUITestDriver@0ae3 (12b7d5fa)][0m Cannot forward the local port 9100 to 9100 on the device 00008020-000248E602D8002E. Set the custom value to 'mjpegServerPort' capability if this is an undesired behavior.
> [38;5;144m[ffmpeg][0m ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
> [38;5;144m[ffmpeg][0m   built with Apple clang version 14.0.3 (clang-1403.0.22.14.1)
> [38;5;144m[ffmpeg][0m   configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.0 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
> [38;5;144m[ffmpeg][0m 
> [38;5;144m[ffmpeg][0m   libavutil      58.  2.100 / 58.  2.100
> [38;5;144m[ffmpeg][0m   libavcodec     60.  3.100 / 60.  3.100
> [38;5;144m[ffmpeg][0m   libavformat    60.  3.100 / 60.  3.100
> [38;5;144m[ffmpeg][0m   libavdevice    60.  1.100 / 60.  1.100
> [38;5;144m[ffmpeg][0m   libavfilter     9.  3.100 /  9.  3.100
> [38;5;144m[ffmpeg][0m   libswscale      7.  1.100 /  7.  1.100
> [38;5;144m[ffmpeg][0m   libswresample   4. 10.100 /  4. 10.100
> [38;5;144m[ffmpeg][0m   libpostproc    57.  1.100 / 57.  1.100
> [38;5;144m[ffmpeg][0m 
> [38;5;144m[ffmpeg][0m [http @ 0x6000029a2700] Will reconnect at 924 in 0 second(s), error=End of file.
> [38;5;144m[ffmpeg][0m 
> [38;5;32m[XCUITestDriver@0ae3 (12b7d5fa)][0m Screen capture process did not start within 5000ms. Continuing anyway

This is expected. Make sure you manage local ports properly.

**Comment by zhouhyi** [comment]
Hi @mykola-mokhnach, Unfortunately it still doesn't work, "mjpegServerPort" uses an unoccupied port, but prompts this error:
"Encountered internal error running command: Error: The screen capture process 'ffmpeg' died unexpectedly. Check server logs for more details". 
![image](https://github.com/appium/appium/assets/28880427/e3cbb5c7-d5b8-42e2-98da-338840fd6c59)

appium server log:
[appium_server.log](https://github.com/appium/appium/files/14940933/appium_server.log)

**Comment by mykola-mokhnach** [comment]
There might be multiple reasons to that.

You may try to start WDA and then manually connect to the device's Wi-Fi IP address on port 9100 to check if mjpeg screen streaming could be started in general. Also make sure you use the most recent driver version and there are no exceptions from WebDriverAgent present in logs.

Then try to create a new port forward manually, for example using the [iproxy](https://www.npmjs.com/package/iproxy) tool and check if you can start ffmpeg on the localhost

It might also be some firewall or other restrictions on the host machine that prevent the port forwarding from working properly.

**Comment by zhouhyi** [comment]
@mykola-mokhnach  Following your tips, I manually checked whether mjpeg screen streaming was enabled, and after being connected for a while, the connection was closed:
<img width="693" alt="image" src="https://github.com/appium/appium/assets/28880427/4b9d0f06-a5f7-42eb-8b2f-24891f3fd3d9">


But I tried another device (iphone 11, IOS 15.4), and it could record the screen normally using the same port.
![image](https://github.com/appium/appium/assets/28880427/5d81d614-8cdb-4e35-a420-49859cb91a08)


So this may be a device issue rather than an appium issue. Thank you for your help.

**Comment by mykola-mokhnach** [comment]
Yes it also could be a device issue. I don't think we could do anything in such case from the driver side.

**Comment by zhouhyi** [comment]
Hi @mykola-mokhnach You may not be aware of this closed ticket, but I have a recent update on the issue.

I found a way to reproduce, when setting appium:mjpegServerPort to "9100", the mjpeg screen stream works fine.
After setting appium:mjpegServerPort to a value other than "9100" (such as: 9111), only the first time the mjpeg screen stream is executed can work normally, but after the second time, "'ffmpeg' unexpected death" will be faced.

No matter which port is used, the same environment is used (appium:2.5.1; XCUITest: 5.16.1)
appium server log:
1. appium:mjpegServerPort='9100' :
[use_port_9100_pass.log](https://github.com/appium/appium/files/14956887/use_port_9100_pass.log)

2. The first time to use port 9111, appium:mjpegServerPort='9111':
[first_time_use_port_9111_pass.log](https://github.com/appium/appium/files/14956897/first_time_use_port_9111_pass.log)

3. Not the first time to use port 9111, appium:mjpegServerPort='9111':
[other_times_using_port_9111_fails.log](https://github.com/appium/appium/files/14956899/other_times_using_port_9111_fails.log)

Did I lose some configuration? Or is it that ffmpeg cannot use ports other than 9100 for video streaming? It would be greatly appreciated if anyone could help resolve this.

**Comment by zhouhyi** [comment]
Solved the problem of "'ffmpeg' died unexpectedly." on that device and restarted the WDA of this device.

```
cd ${appium-webdriveragent_path}

xcodebuild build-for-testing test-without-building -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=${device_UDID}'
```
