### ISSUE TITLE
start appium and specified --port and --extendPort,but called port 8750

### ISSUE THREAD

**Issue by MelonHjy** [appium/appium#19994]
Hello team.
I started appium and specified --port=8500 --extendPort=8900, but an error occurred during execution:
Original error: The port #8750 is occupied by an other process. You can either quit that process or select another free port
I'm a little confused as to why port 8750 is called.
I hope the team can help find the problem.Thanks

**Comment by KazuCocoa** [comment]
Please follow the bug report template https://github.com/appium/appium/issues/new/choose if you think it was a bug.
Appium does not have `extendPort`, btw. https://appium.io/docs/en/latest/cli/args/

https://discuss.appium.io/ would help to ask a general question.
