### ISSUE TITLE
bug: <Appium 2.x. ResetApp and Auto grant permissions>

### ISSUE THREAD

**Issue by Olgap38** [appium/appium#19991]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I migrated my Android Automation project from Appium 1.x to Appium 2.x, I faced a lot of problems starting with deleting resetApp.
The test lifecycle is based on each test, starting with logging into the app using different and same user credentials - test wise. Each test suite ends with a logout. If any test failed, it caught the exception, cleared the session, and the next test was run on the log screen. This lifecycle allowed me to run all tests, a set of tests, tests by suite, or just one test.
So I don't have to completely reset the app every time and granting all permissions automatically did its job in setup. 

In Appium 2.x I was able to implement closing and restarting the application using only a hard reset, which is too far from ideal.  time increased significantly. 
And now I'm struggling with another problem: AutoGrantPermissions no longer works. This is a tracking/wireless_form app, so after hard app reset: before logging in I have to click on 6 permission pop ups and after logging in another 4 clicks are just for location and notifications with their disclosure. Then I have to test the forms and here I need to accept the camera, video, and contacts. At the moment I have about 200 test scripts. So not only does time increase significantly, but it has also simply reached the point of? where is a sense of it?

https://github.com/appium/appium/issues/15807 and https://github.com/appium/appium/issues/17169 related to these issues, but still, I didn't find an answer with a clear solution.

### Expected Behavior

Alternative method for resetting the app. So the test(s) can be run from any state of the app, for example, a user is logged in and the app states on some screen, on run - this session can be closed and the app relaunched and returned to the login screen. 
At the setup - all permissions are accepted automatically.  
It worked on Appium 1.x with:
using System;
using AppiumAutomation.Source.Utils;
using OpenQA.Selenium.Appium;
using OpenQA.Selenium.Appium.Android;
using OpenQA.Selenium.Appium.Enums;

namespace AppiumAutomation.Source.Base
{
    public class DriverFactory
    {
        public AppiumDriver<AndroidElement> Init()
        {   
            AppiumOptions appiumOptions = new AppiumOptions();
            
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Android");
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.DeviceName, "06051FDD4000JH");
            appiumOptions.AddAdditionalCapability(AndroidMobileCapabilityType.AutoGrantPermissions, true);
            string appPath = DirectoryManager.GetBinFolder() + "//External//customAppBuilder-internal-base-release.apk";            
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.App, appPath);
            AppiumDriver<AndroidElement> driver = new AndroidDriver<AndroidElement>(
                new Uri("http://127.0.0.1:4723/wd/hub"),
                appiumOptions
            );
            return driver;
        }
    }
}
using System;
using System.IO;
using System.Reflection;
using System.Windows.Forms;
using AppiumAutomation.Source.Base;
using AppiumAutomation.Source.Utils;
using AppiumAutomation.TestCases.Pages;
using NUnit.Framework;
using OpenQA.Selenium.Appium;
using OpenQA.Selenium.Appium.Android;
using OpenQA.Selenium.Appium.Enums;

namespace AppiumAutomation.TestCases
{
    [TestFixture]
    public class TestBase
    {
        private DriverFactory _driverFactory = new DriverFactory();
        public AndroidDriver<AndroidElement> Driver;
        protected PageFactory PageFactory;

        [OneTimeSetUp]
        public void Setup()
        {
            Driver = (AndroidDriver<AndroidElement>)_driverFactory.Init();
            Driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
            PageFactory = new PageFactory(Driver);
    }

        [OneTimeTearDown]
        public void TearDown()
        {
            if (Driver != null)
            {
                Driver.Close();
                Driver.Quit();
            }
        }

### Minimal Reproducible Example

[HTTP] Request idempotency key: 8b7e607a-5425-451e-86ef-c2fa112ec80d
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appium:automationName":"UIAutomator2","platformName":"Android","autoGrantPermissions":true,"app":"C:\\Projects\\AndroidAutomation\\AndroidAutomation\\bin\\Debug\\net8.0\\External\\customAppBuilder-internal-base-release.apk","appPackage":"com.actsoft.customappbuilder","appActivity":"com.actsoft.customappbuilder.ui.activity.MainActivity"},"capabilities":{"firstMatch":[{"appium:automationName":"UIAutomator2","platformName":"Android"}]}}
[AppiumDriver@ea2c] Calling AppiumDriver.createSession() with args: [{"appium:automationName":"UIAutomator2","platformName":"Android","autoGrantPermissions":true,"app":"C:\\Projects\\AndroidAutomation\\AndroidAutomation\\bin\\Debug\\net8.0\\External\\customAppBuilder-internal-base-release.apk","appPackage":"com.actsoft.customappbuilder","appActivity":"com.actsoft.customappbuilder.ui.activity.MainActivity"},null,{"firstMatch":[{"appium:automationName":"UIAutomator2","platformName":"Android"}]}]
[AppiumDriver@ea2c] Event 'newSessionRequested' logged at 1712769900198 (13:25:00 GMT-0400 (Eastern Daylight Time))
[Appium] Attempting to find matching driver for automationName 'UIAutomator2' and platformName 'Android'
[Appium] The 'uiautomator2' driver was installed and matched caps.
[Appium] Will require it at C:\Users\OShaposhnikova\.appium\node_modules\appium-uiautomator2-driver
[Appium] Requiring driver at C:\Users\OShaposhnikova\.appium\node_modules\appium-uiautomator2-driver\build\index.js
[AppiumDriver@ea2c] Appium v2.5.1 creating new AndroidUiautomator2Driver (v2.45.1) session
[AppiumDriver@ea2c] Checking BaseDriver versions for Appium and AndroidUiautomator2Driver
[AppiumDriver@ea2c] Appium's BaseDriver version is 9.5.2
[AppiumDriver@ea2c] AndroidUiautomator2Driver's BaseDriver version is 9.5.2
[AndroidUiautomator2Driver@efa5] Creating session with W3C capabilities: {
[AndroidUiautomator2Driver@efa5]   "alwaysMatch": {
[AndroidUiautomator2Driver@efa5]     "platformName": "Android",
[AndroidUiautomator2Driver@efa5]     "appium:automationName": "UIAutomator2"
[AndroidUiautomator2Driver@efa5]   },
[AndroidUiautomator2Driver@efa5]   "firstMatch": [
[AndroidUiautomator2Driver@efa5]     {}
[AndroidUiautomator2Driver@efa5]   ]
[AndroidUiautomator2Driver@efa5] }
[AndroidUiautomator2Driver@efa5 (10f4640a)] Session created with session id: 10f4640a-ee80-4eea-b939-0b5f069d2a2a
[ADB] Found 14 'build-tools' folders under 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk' (newest first):
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\34.0.0
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\34.0.0-rc3
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\34.0.0-rc2
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\34.0.0-rc1
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\33.0.2
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\33.0.1
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\33.0.0
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\32.1.0-rc1
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\32.0.0
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\31.0.0
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\30.0.3
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\30.0.2
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\30.0.1
[ADB]     C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\build-tools\30.0.0
[ADB] Using 'adb.exe' from 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[ADB] Running 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[AndroidUiautomator2Driver@efa5 (10f4640a)] Retrieving device list
[ADB] Trying to find connected Android devices
[ADB] Getting connected devices
[ADB] Connected devices: [{"udid":"06051FDD4000JH","state":"device"}]
[AndroidUiautomator2Driver@efa5 (10f4640a)] Using device: 06051FDD4000JH
[ADB] Using 'adb.exe' from 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\platform-tools\adb.exe'
[ADB] Running 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 start-server'
[ADB] Setting device id to 06051FDD4000JH
[AndroidUiautomator2Driver@efa5 (10f4640a)] Neither 'app' nor 'appPackage' was set. Starting UiAutomator2 without the target application
[ADB] Running 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 06051FDD4000JH shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 34
[ADB] Getting device platform version
[ADB] Running 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 06051FDD4000JH shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 14
[ADB] Device API level: 34
[AndroidUiautomator2Driver@efa5 (10f4640a)] Relaxing hidden api policy
[ADB] Running 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 06051FDD4000JH shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''
[AndroidUiautomator2Driver@efa5 (10f4640a)] No app sent in, not parsing package/activity
[AndroidUiautomator2Driver@efa5 (10f4640a)] Pushing settings apk to the device...
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 06051FDD4000JH shell dumpsys package io.appium.settings'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('5.7.5' >= '5.7.5')
[ADB] There is no need to install/upgrade 'C:\Users\OShaposhnikova\.appium\node_modules\appium-uiautomator2-driver\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Running 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 06051FDD4000JH shell dumpsys activity services io.appium.settings'
[AndroidUiautomator2Driver@efa5 (10f4640a)] io.appium.settings is already running. There is no need to reset its permissions.
[Logcat] Starting logs capture with command: C:\\Users\\OShaposhnikova\\AppData\\Local\\Android\\Sdk\\platform-tools\\adb.exe -P 5037 -s 06051FDD4000JH logcat -v threadtime
[ADB] Running 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 06051FDD4000JH shell appops set io.appium.settings android:mock_location allow'
[ADB] Running 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 06051FDD4000JH shell "[ -e '/data/local/tmp/mock_apps.json' ] && echo __PASS__"'
[ADB] Running 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 06051FDD4000JH shell cat /data/local/tmp/mock_apps.json'
[AndroidUiautomator2Driver@efa5 (10f4640a)] Forwarding UiAutomator2 Server port 6790 to local port 8200
[ADB] Forwarding system: 8200 to device: 6790
[ADB] Running 'C:\Users\OShaposhnikova\AppData\Local\Android\Sdk\platform-tools\adb.exe -P 5037 -s 06051FDD4000JH forward tcp:8200 tcp:6790'
[AndroidUiautomator2Driver@efa5 (10f4640a)] No app capability. Assuming it is already on the device

### Environment

- : C#, Selenium 
- Appium server version (output of `appium --version`): Appium v2.5.1
- Appium driver(s) and their version(s): uiautomator2@2.45.1
- Appium plugin(s) and their version(s): execute-driver@3.0.23, images@2.1.4
- Node.js version (output of `node --version`): Node.js v20.8.1.
- `npm` version (output of `npm --version`): npm --version 10.2.0
- Last component(s) version which did _not_ exhibit the problem: Appium 1.x
- Platform and version under test: Android, OS versions from 10 to 14
- Real device or emulator/simulator: real devices

### Further Information

C:\Users\OShaposhnikova>appium --use-driver uiautomator2 --base-path /wd/hub --use-plugin execute-driver --allow-cors
[Appium] Attempting to load plugin execute-driver...
[Appium] Requiring plugin at C:\Users\OShaposhnikova\.appium\node_modules\@appium\execute-driver-plugin\index.js
[Appium] ExecuteDriverPlugin has been successfully loaded in 0.149s
[Appium] Welcome to Appium v2.5.1
[Appium] Non-default server args:
[Appium] {
[Appium]   allowCors: true,
[Appium]   basePath: '/wd/hub',
[Appium]   useDrivers: [
[Appium]     'uiautomator2'
[Appium]   ],
[Appium]   usePlugins: [
[Appium]     'execute-driver'
[Appium]   ]
[Appium] }
[Appium] The autodetected Appium home path: C:\Users\OShaposhnikova\.appium
[Appium] Attempting to load driver uiautomator2...
[Appium] Requiring driver at C:\Users\OShaposhnikova\.appium\node_modules\appium-uiautomator2-driver\build\index.js
[Appium] AndroidUiautomator2Driver has been successfully loaded in 1.799s
[Appium] You have enabled CORS requests from any host. Be careful not to visit sites which could maliciously try to start Appium sessions on your machine
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723/wd/hub
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium]        http://192.168.1.176:4723/wd/hub
[Appium]        http://127.0.0.1:4723/wd/hub (only accessible from the same host)
[Appium]        http://172.27.48.1:4723/wd/hub
[Appium] Available drivers:
[Appium]   - uiautomator2@2.45.1 (automationName 'UiAutomator2')
[Appium] Available plugins:
[Appium]   - execute-driver@3.0.23 (ACTIVE)
[Appium]   - images@2.1.4
[HTTP] Request idempotency key: 8b7e607a-5425-451e-86ef-c2fa112ec80d
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"appium:automationName":"UIAutomator2","platformName":"Android","autoGrantPermissions":true,"app":"C:\\Projects\\AndroidAutomation\\AndroidAutomation\\bin\\Debug\\net8.0\\External\\customAppBuilder-internal-base-release.apk","appPackage":"com.actsoft.customappbuilder","appActivity":"com.actsoft.customappbuilder.ui.activity.MainActivity"},"capabilities":{"firstMatch":[{"appium:automationName":"UIAutomator2","platformName":"Android"}]}}
[AppiumDriver@ea2c] Calling AppiumDriver.createSession() with args: [{"appium:automationName":"UIAutomator2","platformName":"Android","autoGrantPermissions":true,"app":"C:\\Projects\\AndroidAutomation\\AndroidAutomation\\bin\\Debug\\net8.0\\External\\customAppBuilder-internal-base-release.apk","appPackage":"com.actsoft.customappbuilder","appActivity":"com.actsoft.customappbuilder.ui.activity.MainActivity"},null,{"firstMatch":[{"appium:automationName":"UIAutomator2","platformName":"Android"}]}]
[AppiumDriver@ea2c] Event 'newSessionRequested' logged at 1712769900198 (13:25:00 GMT-0400 (Eastern Daylight Time))
[Appium] Attempting to find matching driver for automationName 'UIAutomator2' and platformName 'Android'
[Appium] The 'uiautomator2' driver was installed and matched caps.
[Appium] Will require it at C:\Users\OShaposhnikova\.appium\node_modules\appium-uiautomator2-driver
[Appium] Requiring driver at C:\Users\OShaposhnikova\.appium\node_modules\appium-uiautomator2-driver\build\index.js
[AppiumDriver@ea2c] Appium v2.5.1 creating new AndroidUiautomator2Driver (v2.45.1) session
[AppiumDriver@ea2c] Checking BaseDriver versions for Appium and AndroidUiautomator2Driver
[AppiumDriver@ea2c] Appium's BaseDriver version is 9.5.2
[AppiumDriver@ea2c] AndroidUiautomator2Driver's BaseDriver version is 9.5.2
[AndroidUiautomator2Driver@efa5] Creating session with W3C capabilities: {
[AndroidUiautomator2Driver@efa5]   "alwaysMatch": {
[AndroidUiautomator2Driver@efa5]     "platformName": "Android",
[AndroidUiautomator2Driver@efa5]     "appium:automationName": "UIAutomator2"
[AndroidUiautomator2Driver@efa5]   },
[AndroidUiautomator2Driver@efa5]   "firstMatch": [
[AndroidUiautomator2Driver@efa5]     {}
[AndroidUiautomator2Driver@efa5]   ]
[AndroidUiautomator2Driver@efa5] }
[AndroidUiautomator2Driver@efa5 (10f4640a)] Session created with session id: 10f4640a-ee80-4eea-b939-0b5f069d2a2a

Capabilities:
namespace AndroidAutomation.Source.Base
{
    public class DriverFactory
    {
        public AndroidDriver<AndroidElement> driver;
        private string serverUri = "http://127.0.0.1:4723/wd/hub";
        private string appPath = DirectoryManager.GetBinFolder() + @"\External\customAppBuilder-internal-base-release.apk";
        public AppiumDriver<AndroidElement> Init()
        {
            AppiumOptions appiumOptions = new AppiumOptions();
            appiumOptions.AddAdditionalCapability("appium:automationName", AutomationName.AndroidUIAutomator2);
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Android");
            appiumOptions.AddAdditionalCapability(AndroidMobileCapabilityType.AutoGrantPermissions, true);
            appiumOptions.AddAdditionalCapability(MobileCapabilityType.App, appPath);
            appiumOptions.AddAdditionalCapability(AndroidMobileCapabilityType.AppPackage, "com.actsoft.customappbuilder");
            appiumOptions.AddAdditionalCapability(AndroidMobileCapabilityType.AppActivity, "com.actsoft.customappbuilder.ui.activity.MainActivity");
            driver = new AndroidDriver<AndroidElement>(
                new Uri(serverUri),
                appiumOptions
            );
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
            return driver;
        }

/// in case: i tried with these capabilities
//appiumOptions.AddAdditionalCapability(MobileCapabilityType.FullReset, true);
//appiumOptions.AddAdditionalCapability(MobileCapabilityType.NoReset, false);
//appiumOptions.AddAdditionalCapability("allowSessionOverride", true);

namespace AndroidAutomation.TestCases
{
    [TestFixture]
    public class TestBase
    {
        private DriverFactory _driverFactory = new DriverFactory();
        public AndroidDriver<AndroidElement> Driver;
        private string appPath = DirectoryManager.GetBinFolder() + @"\External\customAppBuilder-internal-base-release.apk";
        [SetUp]
        public void Setup()
        {          
            Driver = (AndroidDriver<AndroidElement>)_driverFactory.Init();
            Driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
            Driver.TerminateApp("com.actsoft.customappbuilder");
            Driver.ActivateApp("com.actsoft.customappbuilder");
//for accepting permissions before login
            //Message().ClickPositive();
            //PermissionForApp().ForegroundAllow();
            //Message().ClickPositive();
            //PermissionForApp().NotificationAllow();
        }
        [TearDown]
        public void TearDown()
        {
            Driver.TerminateApp("com.actsoft.customappbuilder");
            HardResetApp("com.actsoft.customappbuilder");
        }
       private void HardResetApp(string packageName)
        {
            Process.Start("adb", $"shell pm clear {packageName}");
            Process.Start("adb", $"shell am force-stop {packageName}");
        }

**Comment by amedvedjev** [comment]
`In Appium 2.x I was able to implement closing and restarting the application using only a hard reset, which is too far from ideal. time increased significantly.`
-> just add capability
`optionsUiAutomator2.setCapability("appium:forceAppLaunch", true);`

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-uiautomator2-driver#mobile-installapp  would help to modify the permission info in the middle, so after the `pm clear`

**Comment by hiChandravanshi** [comment]
hi, @Olgap38 did you find any solution for `AutoGrantPermissions` on re-launch? I am facing the same issue.

**Comment by Olgap38** [comment]
Hi @hiChandravanshi unfortunately nope, I have been spinning my wheels trying to find a solution for months with no luck and ended up returning to Appium 1 (deprecated version). Here I don't have such problems.

**Comment by KazuCocoa** [comment]
As https://github.com/appium/appium-uiautomator2-driver#mobile-changepermissions, `permissions: all` might do the same granting permission stuff before starting the app process. It is what Appium UIA2 driver does behind the auto grant permissions caps

**Comment by hiChandravanshi** [comment]
Thanks @KazuCocoa for the response. It works for me. @Olgap38 try doing the below in mid-session after clearing the app and relaunching or the hard reset you are doing. It will auto-grant the permissions.

```
await browser.execute("mobile: changePermissions", { permissions: "all" });
```
