### ISSUE TITLE
Unable to install appium drivers on windows 11

### ISSUE THREAD

**Issue by aadityaawas** [appium/appium#20008]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to install the appium drivers like, uiautomator2, chromium, on my windows, it is observed that an permission error is been detected. It is throwing EINVAL error which is regarding the file permission. I have tried with admin user as well but it is throwing the same error. I have verified that node, npm & appium are successfully installed. On using _appium driver list_, I am getting all the drivers but can't install any drivers using _appium driver install uiautomator2_

I am adding logs for your reference. I am not getting any STOUT & STDERR messages as well.

### Expected Behavior

uiautomator2 should be installed successfully

### Minimal Reproducible Example

C:\Windows\system32>appium driver install uiautomator2
√ Checking if 'appium-uiautomator2-driver' is compatible
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev --no-progress --no-audit --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code EINVAL.

STDOUT:

STDERR:

### Environment

- Operating system: windows 11
- Appium server version (output of `appium --version`): v2.5.3
- Appium driver(s) and their version(s): Only name of drivers are getting displayed in the list not version
- Appium plugin(s) and their version(s): NA
- Node.js version (output of `node --version`): v20.12.2
- `npm` version (output of `npm --version`): 10.5.2
- Last component(s) version which did _not_ exhibit the problem: NA
- Platform and version under test: Windows 11
- Real device or emulator/simulator: NA
- java:  java 11.0.22 2024-01-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.22+9-LTS-219)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.22+9-LTS-219, mixed mode)

**Comment by aadityaawas** [comment]
Hi @mykola-mokhnach Thanks for your suggestion. I have downgraded my nodejs version to the 20.11.1 and now it working fine. 
If you want any other information than let me know else you may close this ticket as it resolved now.

Cheers!
Aaditya

**Comment by mykola-mokhnach** [comment]
I have created a bugreport to node.js
Let see what they reply to us. If this behavior is not going to be changed then we should consider applying [this](https://github.com/appium/appium/pull/20010) patch to the upcoming server version.

**Comment by aadityaawas** [comment]
Do we have any bug bounties? 🥇

**Comment by mykola-mokhnach** [comment]
The patch has been published in the server version 2.5.4
