### ISSUE TITLE
[Feat]: alternate sendkey strategy/ies for iOS web

### ISSUE THREAD

**Issue by jlipps** [appium/appium#20004]
iOS web automation relies on injecting JS. Different web app frameworks respond to this in different ways. Sometimes setting a field's value directly as full strings as the atoms do doesn't trigger input events. But sending them one key at a time does. Here's a proposal for a capability like `appium:sendKeyStrategy`, with values like `default` (just do what the atoms do) or `oneByOne`, which iteratively calls send keys internally for each character in the string.

**Comment by KazuCocoa** [comment]
We had `sendKeyStrategy` as `oneByOne` and `grouped` before for ios driver (not xcuitest driver). Possibly we could follow the naming...?

Then, https://github.com/appium/appium-remote-debugger/pull/376 can be closed with this idea.
