### ISSUE TITLE
Any plans to support appium-windows-driver for windows 11

### ISSUE THREAD

**Issue by sureshkumar-skc** [appium/appium#20005]
I am trying to install appium-windows-driver for Windows 11 using the command `appium driver install --source=npm appium-windows-driver`. I stuck in the installation step, whereas the same step is working fine in the windows10. PFA screenshot. 

![Screenshot 2024-04-17 at 11 35 11 AM](https://github.com/appium/appium/assets/12427607/4f333086-0dfe-487f-9983-b54ed8291c7c)

**Comment by mykola-mokhnach** [comment]
The server part is ~~not~~ maintained by Microsoft, so there is not much we could do there. We've seen some open-source alternatives to it, but unfortunately we cannot find anyone who would like to maintain and develop them on constant basis.
