### ISSUE TITLE
Large DOM structure takes long time and sometimes crashed appium

### ISSUE THREAD

**Issue by bijitbiswas1994** [appium/appium#20018]
**Is your feature request related to a problem? Please describe.**
On iOS applications the DOM structure is huge approx 1000s of XCUIElementTypeCell and has few more XCUIElementTypeStaticText inside it.
Now if we inspect the page it takes a huge long time and appium crashes sometimes 

**Describe the solution you'd like**
I was expecting a capability where we can only load the DOM structure which are on current view and not all the scrollable view. `loadOnlyViewableElement : true`

**Describe alternatives you've considered**
I tried increasing the idleWaitTimeout but the DOM structure is dynamic and time taken will keep increasing if we try to load all the scrollable DOM.

**Additional context**
Adding an example where 300 records are present, which took around 45 secs, but I have scenarios where 1000-5000 record

https://github.com/appium/appium/assets/56245858/491536eb-22e1-4561-8e98-9d4d6addb7e1

**Comment by eglitise** [comment]
This has been previously requested in #19758, but currently this does not seem possible. You can try to decrease the value of `snapshotMaxDepth` to reduce the chance of crashes, and/or use the [`mobile:source`](https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-source) execute method to exclude attributes that you may find less relevant, which should also help.

**Comment by KazuCocoa** [comment]
`pageSourceExcludedAttributes` in Settings API https://appium.github.io/appium-xcuitest-driver/latest/reference/settings/ also might help to get response with `excludedAttributes` in the mobile:source via general source endpoint
