### ISSUE TITLE
Unable to start appium session using appium GUI inspector even after upgrading or installing appium v2.5

### ISSUE THREAD

**Issue by shyam6363** [appium/appium#20026]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi 

I read through the following document
*Link 1:* https://appium.io/docs/en/2.4/quickstart/requirements/

The above document says that Node.js version in the SemVer range ^14.17.0 || ^16.13.0 || >=18.0.0
So I installed node js v18.20.2 & npm v10.5.0. 

After that i executed the command
 npm i -g appium. The appium v2.5.4 got installed. Along with this installed Appium-Inspector-windows-2024.3.1-x64
After that, i executed the command appium --allow-cors. & then opened the appium inspector.

Still i am facing the following.

Error
Could not connect to Appium server URL '[http://127.0.0.1:4723/wd/hub'](javascript:void(0);). Please check if the server is running and the URL is correct (valid URLs can be found at the start of the Appium server log). If you are using the Inspector's browser version, ensure the server has been started with '--allow-cors'.

I am unable to install the uiautomator 2.

Here are my questions, kindly request you to help me with same.
1. What is node js version that we need to install in order to support appium v2.5.4?.
2. What is appium inspector version which we need to install to support v2.5.4
3. what is the additional drivers that we need to install to support android automation.

![image](https://github.com/appium/appium/assets/34148561/e6b926b7-510b-45cc-9723-4fa9c8a61d93)

### Expected Behavior

NA

### Minimal Reproducible Example

NA

### Environment

- Operating system: Windows 10
- Appium server version (v2.5.4`):
- Appium driver(s) and their version(s): NA
- Appium plugin(s) and their version(s):NA
- Node.js version (output of `node --version`):  v18.20.2 
- `npm` version (output of `npm --version`):  v10.5.0. 
- Last component(s) version which did _not_ exhibit the problem: NA
- Platform and version under test: Android 11
- Real device or emulator/simulator: Real device.

### Link to Appium Logs

Unable to install uiautomator2
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev --no-progress --no-audit --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.

STDOUT:
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "C:\\WINDOWS\\system32\\cmd.exe /d /s /c node install-npm.js\n[15:08:34] Error installing Chromedriver: unable to verify the first certificate\n[15:08:35] Error: unable to verify the first certificate\n    at Function.AxiosError.from (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\core\\AxiosError.js:89:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\adapters\\http.js:610:25)\n    at RedirectableRequest.emit (node:events:529:35)\n    at ClientRequest.eventHandlers.<computed> (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\follow-redirects\\index.js:38:24)\n    at ClientRequest.emit (node:events:517:28)\n    at TLSSocket.socketErrorListener (node:_http_client:501:9)\n    at TLSSocket.emit (node:events:517:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at retrieveData (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-chromedriver\\lib\\utils.js:92:5)\n[15:08:35] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable."
  }
}

STDERR:
npm WARN config global-style This option has been deprecated in favor of `--install-strategy=shallow`
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Healthcubed\\.appium\\node_modules\\appium\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Healthcubed\.appium\node_modules\appium\node_modules'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Healthcubed\\.appium\\node_modules\\appium\\node_modules'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install-npm.js
npm ERR! [15:08:34] Error installing Chromedriver: unable to verify the first certificate
npm ERR! [15:08:35] Error: unable to verify the first certificate
npm ERR!     at Function.AxiosError.from (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\AxiosError.js:89:14)
npm ERR!     at RedirectableRequest.handleRequestError (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\adapters\http.js:610:25)
npm ERR!     at RedirectableRequest.emit (node:events:529:35)
npm ERR!     at ClientRequest.eventHandlers.<computed> (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\follow-redirects\index.js:38:24)
npm ERR!     at ClientRequest.emit (node:events:517:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:501:9)
npm ERR!     at TLSSocket.emit (node:events:517:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!     at Axios.request (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\Axios.js:45:41)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at retrieveData (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver\lib\utils.js:92:5)
npm ERR! [15:08:35] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.

npm ERR! A complete log of this run can be found in: C:\Users\Healthcubed\AppData\Local\npm-cache\_logs\2024-04-22T09_38_10_224Z-debug-0.log

### Further Information

Here are my questions, kindly request you to help me with same.

1. What is node js version that we need to install in order to support appium v2.5.4?.
2. What is appium inspector version which we need to install to support v2.5.4
3. what is the additional drivers that we need to install to support android automation.

**Comment by mykola-mokhnach** [comment]
> "detail": "C:\WINDOWS\system32\cmd.exe /d /s /c node install-npm.js\n[15:08:34] Error installing Chromedriver: unable to verify the first certificate\n[15:08:35] Error: unable to verify the first certificate\n at Function.AxiosError.from 

It looks like there is an issue with your network or the google server, so it couldn't verify the remote certificate. Please follow 
https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#troubleshooting-chromedriver-download-issues

**Comment by eglitise** [comment]
Also, [please follow the Inspector quickstart instructions](https://appium.github.io/appium-inspector/latest/quickstart/starting-a-session/). You do not need to change `Remote Path` to `/wd/hub` if you are launching Appium with `appium --allow-cors`. You also need to specify valid capabilities.

**Comment by shyam6363** [comment]
I am unable to install uiautomator2 with npm as well.

npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Healthcubed\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Healthcubed\node_modules\appium-uiautomator2-driver\node_modules\appium'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Healthcubed\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Healthcubed\\node_modules\\appium-uiautomator2-driver\\node_modules\\portscanner',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Healthcubed\node_modules\appium-uiautomator2-driver\node_modules\portscanner'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Healthcubed\\node_modules\\appium-uiautomator2-driver\\node_modules\\portscanner'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Healthcubed\\node_modules\\appium-uiautomator2-driver',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Healthcubed\node_modules\appium-uiautomator2-driver\node_modules\winston-transport\node_modules'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Healthcubed\\node_modules\\appium-uiautomator2-driver\\node_modules\\winston-transport\\node_modules'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\Healthcubed\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install-npm.js
npm ERR! [18:58:39] Error installing Chromedriver: unable to verify the first certificate
npm ERR! [18:58:39] Error: unable to verify the first certificate
npm ERR!     at Function.AxiosError.from (C:\Users\Healthcubed\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\AxiosError.js:89:14)
npm ERR!     at RedirectableRequest.handleRequestError (C:\Users\Healthcubed\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\adapters\http.js:610:25)
npm ERR!     at RedirectableRequest.emit (node:events:529:35)
npm ERR!     at ClientRequest.eventHandlers.<computed> (C:\Users\Healthcubed\node_modules\appium-uiautomator2-driver\node_modules\follow-redirects\index.js:38:24)
npm ERR!     at ClientRequest.emit (node:events:517:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:501:9)
npm ERR!     at TLSSocket.emit (node:events:517:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!     at Axios.request (C:\Users\Healthcubed\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\Axios.js:45:41)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at retrieveData (C:\Users\Healthcubed\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver\lib\utils.js:92:5)
npm ERR! [18:58:39] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.

npm ERR! A complete log of this run can be found in: C:\Users\Healthcubed\AppData\Local\npm-cache\_logs\2024-04-22T13_28_25_408Z-debug-0.log

**Comment by shyam6363** [comment]
![image](https://github.com/appium/appium/assets/34148561/324602b2-323f-49d7-997f-273ffe7cf885)

**Comment by shyam6363** [comment]
Please help. I am stuck here.

**Comment by KazuCocoa** [comment]
Did you set `APPIUM_SKIP_CHROMEDRIVER_INSTALL` as https://github.com/appium/appium/issues/20026#issuecomment-2069123185  (https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#troubleshooting-chromedriver-download-issues) to avoid _Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable._?

**Comment by shyam6363** [comment]
Hi,

My Appium version is v2.5.4
Node version is 18.20.2
Npm version is 10.5.2

I set the environment variable to "APPIUM_SKIP_CHROMEDRIVER_INSTALL". Still i am unable to install "uiautomator2"

![image](https://github.com/appium/appium/assets/34148561/3c7b1b04-00de-4be6-b5ed-d66bbedd5ff4)

![Screen_3](https://github.com/appium/appium/assets/34148561/fe99ea6a-cf10-43fb-a394-b807ef5bf19a)

Logs
C:\>appium driver install uiautomator2
√ Checking if 'appium-uiautomator2-driver' is compatible
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev --no-progress --no-audit --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.

STDOUT:
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "C:\\WINDOWS\\system32\\cmd.exe /d /s /c node install-npm.js\n[14:01:15] Error installing Chromedriver: unable to verify the first certificate\n[14:01:15] Error: unable to verify the first certificate\n    at Function.AxiosError.from (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\core\\AxiosError.js:89:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\adapters\\http.js:610:25)\n    at RedirectableRequest.emit (node:events:529:35)\n    at ClientRequest.eventHandlers.<computed> (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\follow-redirects\\index.js:38:24)\n    at ClientRequest.emit (node:events:517:28)\n    at TLSSocket.socketErrorListener (node:_http_client:501:9)\n    at TLSSocket.emit (node:events:517:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at retrieveData (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-chromedriver\\lib\\utils.js:92:5)\n[14:01:15] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable."
  }
}

STDERR:
npm WARN config global-style This option has been deprecated in favor of `--install-strategy=shallow`
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\@devicefarmer',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\@devicefarmer'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\@devicefarmer'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\resolve\test\resolver'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\resolve\\test\\resolver'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\spdy-transport'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\spdy-transport'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install-npm.js
npm ERR! [14:01:15] Error installing Chromedriver: unable to verify the first certificate
npm ERR! [14:01:15] Error: unable to verify the first certificate
npm ERR!     at Function.AxiosError.from (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\AxiosError.js:89:14)
npm ERR!     at RedirectableRequest.handleRequestError (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\adapters\http.js:610:25)
npm ERR!     at RedirectableRequest.emit (node:events:529:35)
npm ERR!     at ClientRequest.eventHandlers.<computed> (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\follow-redirects\index.js:38:24)
npm ERR!     at ClientRequest.emit (node:events:517:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:501:9)
npm ERR!     at TLSSocket.emit (node:events:517:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!     at Axios.request (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\Axios.js:45:41)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at retrieveData (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver\lib\utils.js:92:5)
npm ERR! [14:01:15] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.

npm ERR! A complete log of this run can be found in: C:\Users\Healthcubed\AppData\Local\npm-cache\_logs\2024-04-23T08_30_37_242Z-debug-0.log

**Comment by eglitise** [comment]
Please follow the instructions properly. The variable name is `APPIUM_SKIP_CHROMEDRIVER_INSTALL` and the value is `1`.

**Comment by shyam6363** [comment]
Hi eglitise.

I tried but it's still not happening. Can you please show step by step?
However here's my result
C:\Users\Healthcubed>set CHROME_SKIP
CHROME_SKIP=APPIUM_SKIP_CHROMEDRIVER_INSTALL=1

C:\Users\Healthcubed>appium driver install uiautomator2
√ Checking if 'appium-uiautomator2-driver' is compatible
× Installing 'uiautomator2' using NPM install spec 'appium-uiautomator2-driver'
Error: × Encountered an error when installing package: npm command 'install --save-dev --no-progress --no-audit --omit=peer --save-exact --global-style --no-package-lock appium-uiautomator2-driver --json' failed with code 1.

STDOUT:
{
  "error": {
    "code": 1,
    "summary": "command failed",
    "detail": "C:\\WINDOWS\\system32\\cmd.exe /d /s /c node install-npm.js\n[15:55:22] Error installing Chromedriver: unable to verify the first certificate\n[15:55:22] Error: unable to verify the first certificate\n    at Function.AxiosError.from (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\core\\AxiosError.js:89:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\adapters\\http.js:610:25)\n    at RedirectableRequest.emit (node:events:529:35)\n    at ClientRequest.eventHandlers.<computed> (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\follow-redirects\\index.js:38:24)\n    at ClientRequest.emit (node:events:517:28)\n    at TLSSocket.socketErrorListener (node:_http_client:501:9)\n    at TLSSocket.emit (node:events:517:28)\n    at emitErrorNT (node:internal/streams/destroy:151:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at retrieveData (C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-chromedriver\\lib\\utils.js:92:5)\n[15:55:22] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable."
  }
}

STDERR:
npm WARN config global-style This option has been deprecated in favor of `--install-strategy=shallow`
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\hpack.js'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Healthcubed\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\hpack.js'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install-npm.js
npm ERR! [15:55:22] Error installing Chromedriver: unable to verify the first certificate
npm ERR! [15:55:22] Error: unable to verify the first certificate
npm ERR!     at Function.AxiosError.from (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\AxiosError.js:89:14)
npm ERR!     at RedirectableRequest.handleRequestError (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\adapters\http.js:610:25)
npm ERR!     at RedirectableRequest.emit (node:events:529:35)
npm ERR!     at ClientRequest.eventHandlers.<computed> (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\follow-redirects\index.js:38:24)
npm ERR!     at ClientRequest.emit (node:events:517:28)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:501:9)
npm ERR!     at TLSSocket.emit (node:events:517:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:151:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR!     at Axios.request (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\axios\lib\core\Axios.js:45:41)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at retrieveData (C:\Users\Healthcubed\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-chromedriver\lib\utils.js:92:5)
npm ERR! [15:55:22] Downloading Chromedriver can be skipped by setting the'APPIUM_SKIP_CHROMEDRIVER_INSTALL' environment variable.

npm ERR! A complete log of this run can be found in: C:\Users\Healthcubed\AppData\Local\npm-cache\_logs\2024-04-23T10_24_43_094Z-debug-0.log

**Comment by eglitise** [comment]
@shyam6363 does starting a session in the Inspector also work?
