### ISSUE TITLE
Is there a way or any desired capabilities in which we can stop Appium from launching the app after installation.

### ISSUE THREAD

**Issue by ishan2788** [appium/appium#20027]
Hello,

I need some help. Is there a way or a any desired capabilities in which we can stop Appium from launching the app after installation. Or is there any other way.?
{
 "platformName": "iOS",
 "appium:automationName": "XCUITest",
"appium:udid": "00008101-001D444A1EC2001E",
"appium:deviceName": "9 iPhone 12 mini",
"appium:platformVersion": "17.3",
"appium:clearSystemFiles": true,
"appium:newCommandTimeout": 60,
"appium:app": "https://appcenter.web.mediaworks.de/apps/category/1/app/772318/download?authorization=5sdsjdesjb1hss",
}

**Comment by mykola-mokhnach** [comment]
You may start the session without `app` capability and then call [installApp](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/reference/execute-methods.md#mobile-installapp) and [launchApp](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/reference/execute-methods.md#mobile-launchapp) extensions

Please use appium forum to ask questions
