### ISSUE TITLE
bug: updating appium, driver or plugin, is not synchronized in node_modules/.cache/appium/extensions.yaml 

### ISSUE THREAD

**Issue by hassineabd** [appium/appium#20032]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installing appium version 2.0.0-beta71 / plugin / driver

installing newer appium version / newer plugin version / newer plugin driver 

performing : appium --version 

--------
WARN Appium Appium encountered 1 warning while validating plugins found in manifest /Users/abdelkaderhassine/node_modules/.cache/appium/extensions.yaml
WARN Appium Plugin "images" has 1 potential problem: 
WARN Appium   - Plugin "images" (package `@appium/images-plugin`) may be incompatible with the current version of Appium (v2.0.0-beta.71) due to an invalid or missing peer dependency on Appium. A newer version of `@appium/images-plugin` is available; please attempt to upgrade "images" to v1.3.7 or newer.
WARN Appium Appium encountered 1 warning while validating drivers found in manifest /Users/abdelkaderhassine/node_modules/.cache/appium/extensions.yaml
WARN Appium Driver "uiautomator2" has 1 potential problem: 
WARN Appium   - Driver "uiautomator2" (package `appium-uiautomator2-driver`) may be incompatible with the current version of Appium (v2.0.0-beta.71) due to its peer dependency on older Appium v^2.4.1. Please ask the developer of `appium-uiautomator2-driver` to update the peer dependency on Appium to v2.0.0-beta.71.

--------

after uninstalling plugins/driver/ appiumrm and reinstalling it, still have the issue : 
WARN Appium Appium encountered 1 warning while validating plugins found in manifest /Users/abdelkaderhassine/node_modules/.cache/appium/extensions.yaml
WARN Appium Plugin "images" has 1 potential problem: 
WARN Appium   - Plugin "images" (package `@appium/images-plugin`) may be incompatible with the current version of Appium (v2.5.4) due to an invalid or missing peer dependency on Appium. A newer version of `@appium/images-plugin` is available; please attempt to upgrade "images" to v1.3.7 or newer.
2.5.4
--------------

### Expected Behavior

Without uninstalling, upgrading any dependencies to a newer version handle the old packages automatically

### Minimal Reproducible Example

[terminal.zip](https://github.com/appium/appium/files/15078114/terminal.zip)

Find all terminal command performed attached here (I exported the terminal it )

and here is the screenshot of extensions.yml in the cache 

<img width="583" alt="image" src="https://github.com/appium/appium/assets/43172181/567c843b-fd79-47d8-bff0-e3dc58606d3d">

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
How did you manage Appium? Usually the path to module installation would be like:
`~/.appium/node_modules/.cache/appium/extensions.yaml`

So I guess your local has custom `APPIUM_HOME` to... perhaps `APPIUM_HOME=~/`?
For images plugin installation. you may need to run `appium plugin install images`
https://appium.io/docs/en/latest/cli/extensions/

**Comment by mykola-mokhnach** [comment]
>  handle the old packages automatically

Not sure what you mean by that. Could you please describe in more details what is expected, step by step?

**Comment by hassineabd** [comment]
The expected behavior is :  I upgrade appium / appium plugin / appium driver , the file extensions.yaml should be updated automatically 
the current behavior : extensions.yml (as attached here) had the old version of appium and images plugin after upgrading it ... when I deleted appium and reinstall it the appium version in extensions.yml has been updated but when I did the same thing to appium image plugin it didn't manage to solve the problem 
the actual workaround : delete the appium -> delete its ecosystem (plugins , driver etc ..)  -> delete the file extensions.yml manually -> reinstall it again

**Comment by KazuCocoa** [comment]
Did you try out `update`? (this is not the latest appium though)

```
% appium plugin install images@3.0.0
✔ Installing 'images@3.0.0' using NPM install spec '@appium/images-plugin@3.0.0'
ℹ Plugin images@3.0.0 successfully installed
% cat ~/.appium/node_modules/.cache/appium/extensions.yaml
drivers: {}
plugins:
  images:
    pkgName: "@appium/images-plugin"
    version: 3.0.0
    installType: npm
    installSpec: images@3.0.0
    installPath: /Users/kazu/.appium/node_modules/@appium/images-plugin
    appiumVersion: ^2.0.0
    mainClass: ImageElementPlugin
schemaRev: 4
% appium plugin update images@3.0.6
Error: ✖ The plugin "images@3.0.6" was not installed, so can't be updated
% appium plugin update images
✔ Checking if plugin 'images' is updatable
✔ Checking if plugin 'images' needs an update
✔ Installing 'images' using NPM install spec '@appium/images-plugin@3.0.6'
✔ Updating driver 'images' from 3.0.0 to 3.0.6
ℹ Update report:
✔   - plugin images updated: 3.0.0 => 3.0.6
% cat ~/.appium/node_modules/.cache/appium/extensions.yaml
drivers: {}
plugins:
  images:
    pkgName: "@appium/images-plugin"
    version: 3.0.6
    installType: npm
    installSpec: images
    installPath: /Users/kazu/.appium/node_modules/@appium/images-plugin
    appiumVersion: ^2.0.0
    mainClass: ImageElementPlugin
schemaRev: 4
```

**Comment by hassineabd** [comment]
I think that I got it why: I had appium running in another terminal that's why it kept cache file

**Comment by KazuCocoa** [comment]
It could be. Perhaps file update timing issue occurred then.
