### ISSUE TITLE
My automation tests are flaky- get alert text returns empty string sometimes

### ISSUE THREAD

**Issue by NirupaBox** [appium/appium#20031]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

my automation tests are failing when I tried to get the alert text.
It returns empty string and sometimes it returns the text 

### Expected Behavior

The tests should be consistent with getting the text on the alert and be able to perform some actions on the alert displayed

### Minimal Reproducible Example

if (_commonContext.Driver?.Driver != null)
            if (_commonContext.Driver.Os == Enums.AppOs.Android)
            {
                _commonContext.WaitForAlertIsVisible(30);
                Thread.Sleep(TimeSpan.FromSeconds(5));
                var popupText = _commonContext.Driver.Driver.SwitchTo().Alert().Text;
                Assert.That(popupText, Does.Contain(errorMsg));
            }   

public void WaitForAlertIsVisible(int time)
        {
            try
            {
                WebDriverWait wait = new WebDriverWait(_driver.Driver, TimeSpan.FromSeconds(time));
                wait.Until(SeleniumExtras.WaitHelpers.ExpectedConditions.AlertIsPresent());
            }catch (Exception ex)
            {
                throw ex;
            }
        }

### Environment

- Operating system: android 13.0
- Appium server version (output of `appium --version`): 1.22.0
- Appium driver(s) and their version(s):appium web driver 4.3.1
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: selenium 3.1.4
- Real device or emulator/simulator: simulator android os 13.0

**Comment by NirupaBox** [comment]
Appium logs
[Appium logs (10).txt](https://github.com/appium/appium/files/15073618/Appium.logs.10.txt)

**Comment by NirupaBox** [comment]
@KazuCocoa how do i get the uia2 driver latest version

**Comment by NirupaBox** [comment]
i'm not running tests locally, I run my tests on BrowserStack

**Comment by NirupaBox** [comment]
i did add capability options.AddAdditionalCapability("automationName", "UiAutomator2");

**Comment by eglitise** [comment]
@NirupaBox we do not support Appium 1 anymore. Please change your BrowserStack session configuration to use Appium 2. [I assume this is the relevant documentation.](https://www.browserstack.com/docs/app-automate/appium/set-up-tests/set-appium-version)
