### ISSUE TITLE
Issue when perform gestures on both Android and iOS

### ISSUE THREAD

**Issue by hassineabd** [appium/appium#20034]
### Discussed in https://github.com/appium/appium/discussions/20033

<div type='discussions-op-text'>

<sup>Originally posted by **hassineabd** April 23, 2024</sup>
Trying to execute this command on top of robot framework

Execute Script    ('mobile: doubleClickGesture', {'x': 100, 'y': 100})

and I got this error : 
`
UnknownMethodException: Message: Unknown mobile command "('mobile: doubleClickGesture', {'x': 100, 'y': 100})". Only shell, execEmuConsoleCommand, dragGesture, flingGesture, doubleClickGesture, clickGesture, longClickGesture, pinchCloseGesture, pinchOpenGesture, swipeGesture, scrollGesture, scrollBackTo, scroll, viewportScreenshot, viewportRect, deepLink, startLogsBroadcast, stopLogsBroadcast, deviceidle, acceptAlert, dismissAlert, batteryInfo, deviceInfo, getDeviceTime, changePermissions, getPermissions, performEditorAction, startScreenStreaming, stopScreenStreaming, getNotifications, openNotifications, listSms, type, replaceElementValue, pushFile, pullFile, pullFolder, deleteFile, isAppInstalled, queryAppState, activateApp, removeApp, terminateApp, installApp, clearApp, backgroundApp, getCurrentActivity, getCurrentPackage, startActivity, startService, stopService, broadcast, getContexts, getAppStrings, installMultipleApks, lock, unlock, isLocked, refreshGpsCache, startMediaProjectionRecording, isMediaProjectionRecordingRunning, stopMediaProjectionRecording, getConnectivity, setConnectivity, toggleGps, isGpsEnabled, hideKeyboard, isKeyboardShown, pressKey, getDisplayDensity, getSystemBars, fingerprint, sendSms, gsmCall, gsmSignal, gsmVoice, powerAc, powerCapacity, networkSpeed, sensorSet, getPerformanceData, getPerformanceDataTypes, statusBar, screenshots, scheduleAction, getActionHistory, unscheduleAction, getUiMode, setUiMode, sendTrimMemory commands are supported.
    [ Message content over the limit has been removed. ]
    at /Users/abdelkaderhassine/node_modules/appium-uiautomator2-driver/node_modules/async-lock/lib/index.js:171:12
    at AsyncLock._promiseTry (/Users/abdelkaderhassine/node_modules/appium-uiautomator2-driver/node_modules/async-lock/lib/index.js:306:31)
    at exec (/Users/abdelkaderhassine/node_modules/appium-uiautomator2-driver/node_modules/async-lock/lib/index.js:170:9)
    at AsyncLock.acquire (/Users/abdelkaderhassine/node_modules/appium-uiautomator2-driver/node_modules/async-lock/lib/index.js:189:3)
    at AndroidUiautomator2Driver.executeCommand (/Users/abdelkaderhassine/node_modules/appium-uiautomator2-driver/node_modules/@appium/base-driver/lib/basedriver/driver.ts:122:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:1109:14)
    at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:1215:16)
    at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:1121:17)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:393:19)
    
    `
    
    here is my setup : 
    
Appium-Python-Client==3.2.1
browserstack-local==1.2.7
browserstack_sdk==1.18.9
GitPython==3.1.43
opencv-python-headless==4.9.0.80
pyobjc-framework-Cocoa==10.2
pyobjc-framework-SystemConfiguration==10.2
robotframework==6.0.2
robotframework-appiumlibrary==2.0.0
robotframework-imagecompare==0.2.0
robotframework-lsp==1.10.1
robotframework-pabot==2.16.0
robotframework-pythonlibcore==4.1.2
robotframework-requests==0.9.6
robotframework-seleniumlibrary==6.1.0
robotframework-stacktrace==0.4.1
selenium==4.12.0

and here is my appium version : 2.5.4
- xcuitest@7.14.0
- uiautomator2@3.1.0</div>

**Comment by mykola-mokhnach** [comment]
> Message: Unknown mobile command "('mobile: doubleClickGesture', {'x': 100, 'y': 100})"

I assume there is an error in client arguments. the script itself should look like `mobile: doubleClickGesture`. The other part should belong to arguments. Do you follow the RF library documentation?

**Comment by mykola-mokhnach** [comment]
Closed as not issue
