### ISSUE TITLE
[Feat]: Can I specify my own registry in "appium driver install --source=npm"

### ISSUE THREAD

**Issue by pppppino** [appium/appium#20050]
Hi, I write my own driver and published it in my own registry(like verdaccio),  and I don't know how to install it with appium.
Since 'appium driver install --source=npm <drivername>' get packages from https://www.npmjs.com/.
Besides, I don't wanner set registry for npm, I just want to may be you can add one shot command like "--registry"
Thanks

**Comment by mykola-mokhnach** [comment]
If you want to change the packages registry then consider using npm configurations, like https://stackoverflow.com/questions/41136444/how-to-reset-the-npm-registry-in-global-npm-config.
So, the cli script to install a driver or a plugin would look like
```
set custom npm registry
perform Appium driver install CLI command
set default npm registry
```

**Comment by pppppino** [comment]
@mykola-mokhnach Thanks! 
I know this method, but it's complicated because I need change registry config twice； 
Hope you could give a '--registry' in CLI command, just like npm, which allow me get packages from my own registry just this time, instead of change config forever.

**Comment by mykola-mokhnach** [comment]
in Appium we'd have to do exactly the same. NPM does not have an easy way to change config per command.
Also from a batch execution perspective it makes more sense for a client to set such parameters.

**Comment by jlipps** [comment]
Currently Appium only has plans to support the default NPM repository as a place where `appium driver install` can pull from. For custom repositories there is the method that @mykola-mokhnach provided. Alternatively, you could install the package locally using any method you like, and then `appium driver install --source=local`.
