### ISSUE TITLE
Appium server crashes and shuts down on first test

### ISSUE THREAD

**Issue by tking16** [appium/appium#20061]
Hi, I have absolutely no idea why this is happening, the appium servers on the node machines connect fine to the hub, but the test will run for about 10 seconds and then close down the Appium server resulting in `Unable to execute request: java.net.ConnectException: Connection refused: /127.0.0.1:4723` errors. Can't see much info from the log, just seems to get cut off.

[appium.log](https://github.com/appium/appium/files/15191768/appium.log)

[node.log](https://github.com/appium/appium/files/15191642/node.log)

Appium1.yml
```yml
server:
  port: 4723
  use-drivers:
    - xcuitest
  default-capabilities:
    appium:wdaLocalPort: 8100
    appium:derivedDataPath: ~/nodeData4
    appium:wdaLaunchTimeout: 720000 # 2 minutes per Simulator
    appium:usePrebuiltWDA: true
    appium:settings[pageSourceExcludedAttributes]: "visible"
    appium:newCommandTimeout: 9999
    appium:mjpegServerPort: 9103
    appium:mjpegScreenshotUrl: "http://127.0.0.1:9103"
```
Node file
```
# node4.toml
[server]
port = 5555

[node]
detect-drivers = false
session-timeout=900

[relay]
url = "http://127.0.0.1:4723"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"iOS\", \"appium:platformVersion\": \"17.0\", \"appium:deviceName\": \"iPhone 15 Pro Max\", \"appium:automationName\": \"XCUITest\"}"
]
```

Edit: Adding the run command as well
```
_env/bin/py.test \
    tests \
    --html=${REPORT_HTML_FILENAME} \
    --junitxml=${REPORT_XML_FILENAME} \
    --reruns 1 \
    --variables variables/pytest/ios_test_parallel_caps.json \
    --capability appium:app "${APP_PATH}" \
    --capability appium:isHeadless true \
    --brand "${BRAND}" \
    --appium_port 4444 \
    -k "${TEST_REGEX}" \
    -n ${NODE_COUNT}
    #--appium_wait_for_condition appium \
    #--appium_wait_for_seconds 60 \
```

**Comment by tking16** [comment]
Have just uploaded a newer version of the appium log, I had to reload the console to grab more logs

**Comment by mykola-mokhnach** [comment]
I don't observe any suspicious traces in the server log. Have you tried to ask at the Selenium hub issues tracker?

**Comment by tking16** [comment]
@mykola-mokhnach I did, unfortunately didn't get much help with a resolution, can see [here](https://github.com/SeleniumHQ/selenium/issues/13887)

**Comment by mykola-mokhnach** [comment]
As @diemol mentioned in the issue report above the exception means the server just stops responding to network requests. 
I cannot see any hints in the server log above. Try to collect the Appium's node.js process output on that server - maybe it contains some more details or a stack trace.

**Comment by tking16** [comment]
> Try to collect the Appium's node.js process output on that server - maybe it contains some more details or a stack trace.

Will do, could you please advise on how I can do this?

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot help there. It highly depends on how the server is configured. Maybe hire a consultant to help you with that

**Comment by tking16** [comment]
I've added `--long-stacktrace=true` to the server command, will share here once it fails and see if we can find anything else

**Comment by mykola-mokhnach** [comment]
> 2024-05-03 09:10:08:373 uncaughtException: write EPIPE
> Error: write EPIPE

This error means that the server logging lib (winston) was not able to write its logs into one of the requested destinations. Make sure all log destinations are writeable while the server is running.

**Comment by tking16** [comment]
> Make sure all log destinations are writeable while the server is running.

Don't know how to do that, but wouldn't Winston be failing _because_ the server is shutting down? So there would technically be no way to know what went wrong

**Comment by mykola-mokhnach** [comment]
> Don't know how to do that, but wouldn't Winston be failing because the server is shutting down

I am not sure what exactly you mean by that. Winston allows to forward logs to one or more pipes. These could be files, consoles or TCP streams. If any of these streams is unsuspectedly closed during the lifecycle of the node server then the EPIPE exception is triggered

**Comment by alokkr016** [comment]
I am also facing the same issue.
<img width="1358" alt="image" src="https://github.com/appium/appium/assets/59285395/3b916e3f-a651-4565-ac73-ab29f552207f">

**Comment by mykola-mokhnach** [comment]
@alokkr016 Your issue is related to https://github.com/SeleniumHQ/selenium/issues/13481

**Comment by alokkr016** [comment]
I am facing the same exception when I am using the selenium-server-4.13.0.jar 
`Unable to execute request: java.net.ConnectException: Connection refused: /127.0.0.1:4723`
but when I am using the selenium-server-4.21.0-SNAPSHOT.jar then I am getting the:
`java.io.UncheckedIOException: java.io.IOException: HTTP/1.1 header parser received no bytes`

**Comment by diemol** [comment]
@alokkr016 please create an issue in the Selenium repo with the details when you use the snapshot jar.

**Comment by alokkr016** [comment]
Could you please tell me why I encounter these exceptions when I run the grid and Appium server programmatically, but not when I run them manually?

**Comment by diemol** [comment]
@alokkr016, what you are commenting is not related to this issue; please create an issue as I mentioned above. This will help the Appium maintainers focus on what they need to check.

**Comment by tking16** [comment]
@alokkr016 Please let me know when you create that issue so I can track also, as I see similar problems - it works for me locally but when running through Github Actions I get all the errors

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by alokkr016** [comment]
The issue still persists. Can anyone help?

For reference, please see this GitHub issue: https://github.com/SeleniumHQ/selenium/issues/13913

**Comment by alokkr016** [comment]
> @alokkr016 Your issue is related to [SeleniumHQ/selenium#13481](https://github.com/SeleniumHQ/selenium/issues/13481)

@mykola-mokhnach They have told me that it is an Appium-related issue. Can you help, please?

**Comment by mykola-mokhnach** [comment]
maker sure the installed server version is up to date

**Comment by alokkr016** [comment]
> make sure the installed server version is up to date

Do you mean Appium 2.6.0? I have already checked Appium 2.5.4, and it did not work well with that version either.
