### ISSUE TITLE
Real device architecture is not supported application after upgraded xcuitest driver to 7.15.1

### ISSUE THREAD

**Issue by CarsonFobo** [appium/appium#20063]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The problem:

Failed to create session. An unknown server-side error occurred while processing the command. Original error: Real device architecture is not supported by the my.com.salutica.fobotpms application. Make sure the correct deployment target has been selected for its compilation in Xcode.

### Expected Behavior

Install the ipa file successfully after start session

### Minimal Reproducible Example

my capabilities:
{
  "appium:deviceName": "iPhone 12",
  "platformName": "ios",
  "appium:automationName": "XCUITest",
  "appium:platformVersion": "17.1.2",
  "appium:udid": "00008101-001C6C993061401E",
  "appium:xcodeOrgId": "UCU4RKBR27",
  "appium:xcodesigningId": "iPhone Developer",
  "appium:bundleId": "my.com.salutica.fobotpms",
  "appium:app": "//Users//carson//Desktop//FOBO APP IPA File//FOBO TPMS v1.9.ipa"
}

### Environment

- Operating system:
- Appium server version (output of `appium --version`):2.5.4
- Appium driver(s) and their version(s): xcuitest driver@7.15.1
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`): v16.17.0
- `npm` version (output of `npm --version`): 8.15.0
- Last component(s) version which did _not_ exhibit the problem: xcuitest driver @5.16.1
- Platform and version under test: iOS
- Real device or emulator/simulator: Real devices, iPhone 12 with iOS version 17.1.2

### Link to Appium Logs

https://gist.github.com/CarsonFobo/69114c8f93dc142080e18440bf178327

**Comment by mykola-mokhnach** [comment]
> [XCUITestDriver@f0a7 (bf00538d)] CFBundleSupportedPlatforms: ["WatchOS"]

The error seems legit. The application only declares WatchOS support in its manifest.

**Comment by CarsonFobo** [comment]
> > [XCUITestDriver@f0a7 (bf00538d)] CFBundleSupportedPlatforms: ["WatchOS"]
> 
> The error seems legit. The application only declares WatchOS support in its manifest.

How to fix this?

**Comment by mykola-mokhnach** [comment]
I assume you must rebuild the app with the fixed manifest. Check Apple dev forum for more details.

**Comment by CarsonFobo** [comment]
Ok, thanks. I will try discuss with my iOS developer to investigate it

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by mykola-mokhnach** [comment]
@CarsonFobo You may experience the same issue as in https://github.com/appium/appium/issues/20075
Please try again with the updated driver
