### ISSUE TITLE
"Error:Appium Settings app is not running after 30000ms" while running emulator in headless in Android version 13 and 14

### ISSUE THREAD

**Issue by SanskarTx** [appium/appium#20074]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to run the emultaor in headless , on Android 10 it is running fine but in Android 13 and 14  i am getting the issue as

“Error: Appium Settings app is not running after 30000ms” while everything is running fine when i am not using headless mode.
Due to which app is not launching

### Expected Behavior

Want app to launch without getting the below error

“Error: Appium Settings app is not running after 30000ms”

### Minimal Reproducible Example

I am using Android Studio to create emulator and i am using below code to run in headless. I am getting this issue with Android version 13 and 14 on Android 10 it is running fine

UiAutomator2Options options=new UiAutomator2Options();
        options.setAutomationName(property.returnProperty("automationName"));
        options.setPlatformName(Platform.ANDROID.name());
        options.setPlatformVersion(platformVersion);
        options.setAppPackage(property.returnProperty("appPackage"));
        options.setAppActivity(property.returnProperty("appActivity"));
        options.noReset();
        options.autoGrantPermissions();
        options.setNewCommandTimeout(Duration.ofSeconds(120));
        options.setIsHeadless(true);
        options.setAvdArgs("-no-window");
        options.setAvdArgs("-no-skin");
        options.setAvdArgs("-no-audio");
        options.setAvdArgs("--log-level debug");
        options.setAvdLaunchTimeout(Duration.ofMillis(120000));
        options.setAvdReadyTimeout(Duration.ofMillis(120000));
        options.setCapability("avd",emulatorName());
        options.setCapability("ignoreHiddenApiPolicyError",true);
        options.setCapability("avdArgs","-netfast -no-boot-anim");

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s):
- Appium plugin(s) and their version(s):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Link to Appium Logs

https://gist.github.com/SanskarTx/35324127d0da5fe59a048fa72159c321

**Comment by mykola-mokhnach** [comment]
It looks like the emulator startup performs too slow. Try to preboot it before the test starts or get a faster machine

**Comment by SanskarTx** [comment]
@mykola-mokhnach  One more info , it sometimes run fine . When i hit adb logcat simultaneously .

**Comment by mykola-mokhnach** [comment]
closing as third party issue, which is related to the host machine slowness
