### ISSUE TITLE
bug: Appium Inspector loads some app screens slowly/not at all

### ISSUE THREAD

**Issue by DHutchings-AG** [appium/appium#20081]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While using the Appium Inspector GUI app (latest version at time of writing this), some pages of an iOS application under test takes 2+ minutes to refresh and display on the GUI. Sometimes they do not load at all and the GUI leaves us on the previously loaded page. Note that this was not seen prior to the screens being converted to use SwiftUI, but other screens in the app which also use SwiftUI do not exhibit this issue.

### Expected Behavior

Inspector refreshes faster without chance of failing to load the screen.

### Minimal Reproducible Example

[Appium-log-May7.txt](https://github.com/appium/appium/files/15250173/Appium-log-May7.txt)
[WDA-log-May7.txt](https://github.com/appium/appium/files/15250174/WDA-log-May7.txt)

Attached logs that we collected after refreshing one of the problematic screens, in which it took ~3min to display it. Most screens on the app load almost instantly with the exception of two. This was **NOT** an issue prior to these screens getting migrated to use SwiftUI.

### Environment

Operating system: MAC OS
- Appium server version (output of `appium --version`): 2.1.3
- Appium driver(s) and their version(s):
- uiautomator2@2.12.6 (automationName 'UiAutomator2')
- xcuitest@4.35.0 (automationName 'XCUITest')
- Appium plugin(s) and their version(s): No plugins have been installed.
- Node.js version (output of `node --version`): v20.8.0
- `npm` version (output of `npm --version`): 10.1.0
- Last component(s) version which did _not_ exhibit the problem: it’s the same as above
- Platform and version under test: iOS with os 16.0
- Real device or emulator/simulator: Real Device

### Link to Appium Logs

https://gist.github.com/DHutchings-AG/3695dafb6ed0debd23d823e3dea8248c

### Further Information

This issue has been seen across multiple devices + machines, all of which are running on environments similar to the one described above.

**Comment by mykola-mokhnach** [comment]
The slowness has nothing to do with inspector. It needs to load the page screenshot and the page source in order to show anything and the latter could sometimes be slow. Read https://github.com/appium/appium-xcuitest-driver/blob/master/docs/guides/wda-slowness.md for more details.
