### ISSUE TITLE
The picture stream of ios device is displayed with black edges

### ISSUE THREAD

**Issue by Giteers** [appium/appium#20092]
When I set the font size to a larger font in iOS Settings-Display and Brightness-Scale Display, I will find that the iOS screenshots taken back from the wda service have black edges. like this：

![screen_example](https://github.com/appium/WebDriverAgent/assets/36150640/3b574b7f-aecb-4d4d-b271-a05a5a70eba6)

so, how to deal with it?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
