### ISSUE TITLE
PrebuiltWDA for iOS 17 not working well and always got Timeout

### ISSUE THREAD

**Issue by fatahillahardhi** [appium/appium#20096]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to use PrebuiltWDA for iOS 17 on my Mac Mini, but it always failed. However, when I tried it on my laptop, it worked well. The setup, tools version, and code are the same on both devices.

### Expected Behavior

It works well without any errors.

### Minimal Reproducible Example

1. Build WDA using these steps: [Preparation and Provisioning Profile](https://appium.github.io/appium-xcuitest-driver/latest/preparation/prov-profile-full-manual/).
2. Build the .app for WDA using the following command: (This is used for parallel testing.)
```
xcodebuild clean build-for-testing -project WebDriverAgent.xcodeproj -derivedDataPath appium_wda_ios -scheme WebDriverAgentRunner -destination generic/platform=iOS CODE_SIGNING_ALLOWED=YES
```
3. Delete` /Framework/XC**` using these steps: [Additional Requirement for iOS 17/tvOS 17](https://appium.github.io/appium-xcuitest-driver/latest/guides/run-preinstalled-wda/#additional-requirement-for-ios-17tvos17).
4. Add these capabilities to the driver:
```
options.setCapability("usePreinstalledWDA", true);
options.setUpdatedWdaBundleId("com.bibit.WebDriverAgentRunner");
options.setCapability("prebuiltWDAPath", env("WDA_PATH_IOS_17"));
```

### Environment

- Operating system: mac os sonoma
- Appium server version (output of `appium --version`): Appium V2.5.4
- Appium driver(s) and their version(s): XCUITest 7.12.0
- Appium plugin(s) and their version(s): device-farm 8.4.6
- Node.js version (output of `node --version`): 16.5.1
- `npm` version (output of `npm --version`): 8.11.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iPhone with iOS 17
- Real device or emulator/simulator: Real Device

### Link to Appium Logs

https://gist.github.com/fatahillahardhi/9acf5e6c2ebb596b4ff4579e593ece56

### Further Information

I also use this caps
```
options.setCommandTimeouts(Duration.ofSeconds(300));
options.setWdaLaunchTimeout(Duration.ofSeconds(300));
options.setWdaConnectionTimeout(Duration.ofSeconds(240));
options.setShouldUseSingletonTestManager(false);
options.setAppInstallStrategy("ios-deploy");
options.setUseNewWDA(false);
options.setWebviewConnectTimeout(Duration.ofSeconds(300));
```

**Comment by KazuCocoa** [comment]
What happens when you run below command without Appium? (Please make sure the device has the WDA)

> devicectl device process launch --device 00008101-001D491A2146001E --terminate-existing --environment-variables '{"USE_PORT":"54377","WDA_PRODUCT_BUNDLE_IDENTIFIER":"com.bibit.WebDriverAgentRunner.xctrunner","MJPEG_SERVER_PORT":"54378"}' com.bibit.WebDriverAgentRunner.xctrunner

It will start listening `54377` port on the device, so you would get response by `http://<device ip>:54377` if it works. The log said the port might not respond in the timeout.


```
[XCUITestDriver@54d4 (d1493bf3)] Installing prebuilt WDA at '/Users/devicefarm/Documents/WDA/Bibit/WDA17/WebDriverAgentRunner-Runner.app'. Bundle identifier: com.bibit.WebDriverAgentRunner.xctrunner.
[XCUITestDriver@54d4 (d1493bf3)] Installing '/Users/devicefarm/Documents/WDA/Bibit/WDA17/WebDriverAgentRunner-Runner.app' on the device with UUID '00008101-001D491A2146001E'...
[XCUITestDriver@54d4 (d1493bf3)] Using 'ios-deploy' app deployment strategy. You could change it by providing another value to the 'appInstallStrategy' capability
[XCUITestDriver@54d4 (d1493bf3)] App installation succeeded after 2228ms
[XCUITestDriver@54d4 (d1493bf3)] The app has been installed successfully.
[XCUITestDriver@54d4 (d1493bf3)] Launching WebDriverAgent on the device without xcodebuild
[XCUITestDriver@54d4 (d1493bf3)] Executing xcrun devicectl device process launch --device 00008101-001D491A2146001E --terminate-existing --environment-variables '{"USE_PORT":"54377","WDA_PRODUCT_BUNDLE_IDENTIFIER":"com.bibit.WebDriverAgentRunner.xctrunner","MJPEG_SERVER_PORT":"54378"}' com.bibit.WebDriverAgentRunner.xctrunner
[WD Proxy] Matched '/status' to command name 'getStatus'
[WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:54377/status] with no body
[iProxy@00008101:54377] Connection was refused to port 54377
[WD Proxy] socket hang up
```

**Comment by fatahillahardhi** [comment]
I try to run this
```
xcrun devicectl device process launch --device 00008101-001D491A2146001E --terminate-existing --environment-variables '{"USE_PORT":"54377","WDA_PRODUCT_BUNDLE_IDENTIFIER":"com.bibit.WebDriverAgentRunner.xctrunner","MJPEG_SERVER_PORT":"54378"}' com.bibit.WebDriverAgentRunner.xctrunner
```

and the result is
```
13:36:34  Acquired tunnel connection to device.
13:36:34  Enabling developer disk image services.
13:36:35  Acquired usage assertion.
Launched application with com.bibit.WebDriverAgentRunner.xctrunner bundle identifier.
```

**Comment by fatahillahardhi** [comment]
umm sorry, how to check device ip?

**Comment by KazuCocoa** [comment]
Connect to WiFi and check the ip address from settings. If you have iproxy on your local, using iproxy will be also fine.

**Comment by amedvedjev** [comment]
I am using `.setLaunchWithIdb(true)` without issues while have `.setUsePrebuiltWda(true)`

**Comment by KazuCocoa** [comment]
Thank you.

https://github.com/appium/appium/issues/20096#issuecomment-2111968172 Then, perhaps WDA stopped immediately after the `xcrun devicectl device process launch` for some reason. I don't have devices/host combinations that could have the behavior, so I'm not able to debug, but perhaps the ios device's syslog may have more info. @fatahillahardhi do you have Xcode version diff between the mac mini and laptop?

`setLaunchWithIdb` worked, which means that the XCTest session would work at least.

**Comment by fatahillahardhi** [comment]
I see...

For Xcode, on the Mac Mini is version 15.1, while Xcode on my laptop is version 15.2.

@KazuCocoa

**Comment by KazuCocoa** [comment]
Thank you.
`xcrun devicectl device process launch` is a new method so possibly they have diff internally. I'll take a look a bit later by getting the Xcode version. I probably checked only Xcode 15.2+.

**Comment by KazuCocoa** [comment]
Hm, while I downloaded the Xcode 15.1, the `devicectl` looks the same in the `Xcode.app/Contents/Developer/usr/bin/devicectl` in 15.1 and 15.2. I'll take a look further if I could find/learn something new

**Comment by nick-mlnk** [comment]
_xcode 15.4
appium 2.6.0_
have the same **WDA troubles** with REAL DEVICE (iPhone 13, os 17.1)
what have helped me:
- from the appium docs - build WDA with Xcode, setting unique Product Bundle Identifier for WebdriverAgentLib & WebDriverAgentRunner(i.e. com.anything.WebDriverAgentRunner), "clean build folder - test" within XCODE
- set the proper caps:
    caps.automationName = "XCUITest"
    caps.platformName = "iOS"
    caps.platformVersion = "17.5"
    caps.deviceName = "iPhone 13"
    caps.showXcodeLog = true
    caps.udid = "00000000-00000000000"                                  // your UDID
    caps.xcodeOrgId = "TEAM_ID"                                                  // probably optional cap
    caps.xcodeSigningId = "iPhone Developer"
    caps.updatedWDABundleId = "com.anything.WebDriverAgentRunner"        // from XCode Build
    caps.useNewWDA = "false"
    caps.wdaLaunchTimeout = 130000
----------------------------
finally :crossed_fingers: works fine :rocket:
