### ISSUE TITLE
[Feat]: help initial steps to use appium

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#20097]
**Is your feature request related to a problem? Please describe.**

e.g. when a new user wants to achieve appium automation.

```
npm install -g appium
appium driver install uiautomator2
appium doctor run driver (if necessary)
appium
```

The `appium driver install uiautomator2` part is one extra step from appium v1. In case a user want to use xcuitest driver, `appium driver install xcuitest` will be added. Perhaps...  could we define a command like `appium init` or `appium setup` then appium command can ask users to use which driver they want etc, and appium command takes care of these installations behind that..?

This is just to reduce reading  https://appium.io/docs/en/latest/quickstart after `npm install -g appium` for beginners. Just an idea.

**Describe the solution you'd like**

For advanced usage, we could guide users to check documentation etc, so this is if we could help beginners to use Appium as their first step.

**Describe alternatives you've considered**

**Additional context**

**Comment by KazuCocoa** [comment]
`appium setup-standard` is another naming idea.

Perhaps... we could offer drivers:

- uia2
- xcuitest

and plugins..

- images

Perhaps sufficient...?

**Comment by KazuCocoa** [comment]
let me grab this up

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/pull/20102 is this idea (still wip)

**Comment by KazuCocoa** [comment]
Created https://github.com/appium/appium/pull/20102 for this ticket.

- `appium setup`
- `appium setup all`

then it installs multiple drivers/plugins. We can add more code in the future to reduce user setup.
As future work, possibly it could also be nice to run doctor command as part of this `setup` as well? Just an idea.

**Comment by KazuCocoa** [comment]
I wondered if `appium setup reset` could do https://github.com/appium/appium/issues/17348, which start removing APPIUM_HOME and install packages. Current doctor is `appium driver doctor` so maybe `setup` could include such a cleaning task

**Comment by KazuCocoa** [comment]
Done the initial implementation

**Comment by jlipps** [comment]
Yeha I like a `reset` idea too
