### ISSUE TITLE
Unable to switch to WebView after upgarding to chrome driver 124

### ISSUE THREAD

**Issue by manish-mn** [appium/appium#20107]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am unable to switch to webview using chrome driver 124. I get the list of contexts but unable to switch to that.

### Expected Behavior

It should switch to webview.

### Minimal Reproducible Example

I am using following capabilities-
var option = new AppiumOptions();
            option.AddAdditionalCapability(MobileCapabilityType.PlatformName, "Android");
            option.AddAdditionalCapability("appium:udid", "RZ8N906362E");
            option.AddAdditionalCapability("appium:automationName", "UiAutomator2");
            option.AddAdditionalCapability("appium:appPackage", "net.soti.snap");
            option.AddAdditionalCapability("appium:appActivity", "net.soti.snap.ui.activities.SplashActivity");
            option.AddAdditionalCapability("appium:newCommandTimeout", "30000");
            option.AddAdditionalCapability("appium:noReset", "true");
            option.AddAdditionalCapability("appium:showChromedriverLog", "true");
            option.AddAdditionalCapability("recreateChromeDriverSessions", "true");
            var driver = new AndroidDriver<AppiumWebElement>(new Uri("http://localhost:4723"), option);
            try
            {
                driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
                driver.FindElementByXPath("//android.widget.TextView[@resource-id='net.soti.snap:id/ctlg_txt_vw' and @text='asfdasfasf']").Click();
                var contexts = driver.Contexts;
                var act = driver.CurrentActivity;
                driver.Context = "NATIVE_APP";
                driver.Context = "WEBVIEW_net.soti.snap";
            }
            catch (Exception ex)
            {
                driver.Quit();
            }
            driver.Quit();
I am using following command to start appium -
appium --allow-insecure chromedriver_autodownload

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.5.4
- Appium driver(s) and their version(s) (`appium driver list`): uiautomator2 - 3.5.0
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: Real Device

### Link to Appium Logs

https://gist.github.com/manish-mn/c09cbae77f8adbb9d8618c5723daf0a0

**Comment by mykola-mokhnach** [comment]
This looks like an issue with chromedriver itself. Please report your issue to Google.
