### ISSUE TITLE
[Feat]: print appium relevant information with one command

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#20101]
**Is your feature request related to a problem? Please describe.**

The main motivation here is how to help users to collect info for bug report etc. The best is to attach full appium log, but maybe we could prepare a command to copy and paste info to share env summary to bug report template or cloud vendors.

**Describe the solution you'd like**

An idea is:

`appium --info`

then:

- APPIUM_HOME
- current nodejs/npm versions
- installed drivers
- installed plugins

**Describe alternatives you've considered**

Current method to share these info is:

`node --version`
`npm --version`
`appium driver list`
`appium plugin list`

**Additional context**

**Comment by mykola-mokhnach** [comment]
I like the idea

**Comment by mykola-mokhnach** [comment]
Closed as fixed
