### ISSUE TITLE
bug: <After updating Android project with gradle 8.3, some xml resource ids are missing from appium inspector>

### ISSUE THREAD

**Issue by pc-anuruddha** [appium/appium#20129]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot 2024-05-21 at 12 43 48 PM](https://github.com/appium/appium/assets/119362348/5c356b1d-2129-4e15-b5ab-0d91cefc7346)

### Expected Behavior

Need resource id on this. 
`<com.google.android.material.textfield.TextInputEditText
                        android:id="@+id/feet_input"`

### Minimal Reproducible Example

Update gradle version to `"8.3.1"` and check the resource ids that we used before in automation. some ids are missing and we can reproduce it from appium inspector following version. 
App Version: 2023.12.2
Electron: 13.6.9
Node.js: 14.16.0

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
Appium depends on `AccessibilityNodeInfo` by Android. This could indicate that the Gradle version update affected something internal to Android. What version of greadle did you use before the 8.3.1? Did you bump android gradle plugin as well, etc?

**Comment by pc-anuruddha** [comment]
> Appium depends on `AccessibilityNodeInfo` by Android. This could indicate that the Gradle version update affected something internal to Android. What version of greadle did you use before the 8.3.1? Did you bump android gradle plugin as well, etc? Also, please try out the latest uia2 driver

Yes. we are using 8.3.1 and we tried updating driver 'uiautomator2' to 2.42.1

**Comment by KazuCocoa** [comment]
What version of gradle version worked? I guess this occurred when your test app upgraded gradle from a specific version to 8.3.1, but no other changes in other env like Appium UIA2. Then, usually, it means it affected [AccessibilityNodeInfo](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo) behavior, which is out of control by Appium.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
