### ISSUE TITLE
API 文档完善建议

### ISSUE THREAD

**Issue by pyc-ycy** [appium/appium#20132]
Appium 功能很强大，但受限于缺乏相关 API 文档，对于刚接触的人来说，很不好用，因而强烈建议尽快完善 API 文档，让更多的测试人员了解和上手 Appium，从而助力 Appium 的发展和市场开拓。

**Comment by mykola-mokhnach** [comment]
Please report your issue according to the provided template. Also, we only speak English.

**Comment by pyc-ycy** [comment]
你好，我已经收到你的邮件
