### ISSUE TITLE
Original error: No Chromedriver found that can automate Chrome '121.0.6167'. 

### ISSUE THREAD

**Issue by GitAnusha93** [appium/appium#20145]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Scenario: I am currently trying to use automate MS login integrated to native app. To enter password, it opens a webview, upon successfully entering password, it reverts back to the native app. 

I am currently using robotframework, Appium, Python and currently facing issue when trying to add password in webview (before it was working fine, not sure whats causing issue now). 

These are the keywords that I am using before, with appium library:
```
            Input Text                                 xpath=//android.widget.Button[@index="0"]    password
            Click Element                           xpath=//android.widget.Button[@text="enter"]
```

I tried to add  - Switch To Context    WEBVIEW_Terrace as I read thats more appropriate to use when handling webview in appium automation. So before performing entering password I try to switch WEBVIEW_Terrace ,  and lit giving me the error:
_WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: No Chromedriver found that can automate Chrome '121.0.6167'. You could also try to enable automated chromedrivers download as a possible workaround._
          
How can we fix this?

### Expected Behavior

User should be able to inspect webview in appium automation

### Minimal Reproducible Example

 appium -v2.5.4
appium-uiautomator2-driver@3.1.0

pip3 list
Package                         Version
------------------------------- -----------
Appium-Python-Client            3.2.1
attrs                           23.2.0
certifi                         2024.2.2
cffi                            1.16.0
charset-normalizer              3.3.2
click                           8.1.7
cryptography                    42.0.5
cx_Oracle                       8.3.0
decorator                       5.1.1
docutils                        0.21
grpcio                          1.62.1
grpcio-tools                    1.62.1
h11                             0.14.0
idna                            3.7
kitchen                         1.2.6
numpy                           1.26.4
opencv-python                   4.9.0.80
openvino                        2024.0.0
oracledb                        2.1.2
outcome                         1.3.0.post0
overrides                       7.7.0
packaging                       24.0
pillow                          10.2.0
pip                             24.0
protobuf                        4.25.3
pycparser                       2.22
PySocks                         1.7.1
pytesseract                     0.3.10
pytz                            2024.1
requests                        2.31.0
robotframework                  7.0
robotframework-appiumlibrary    2.0.0
robotframework-archivelibrary   0.4.2
robotframework-assertion-engine 3.0.3
robotframework-browser          18.3.0
robotframework-oracledb         2.0.2
robotframework-pythonlibcore    4.4.1
robotframework-requests         0.9.7
robotframework-seleniumlibrary  6.2.0
selenium                        4.14.0

### Environment

- Operating system: Mac
- Appium server version (output of `appium --version`): 2.5.4
- Appium driver(s) and their version(s) (`appium driver list`):  uiautomator2@3.1.0 [installed (npm)]
- Appium plugin(s) and their version(s) (`appium plugin list`): none
- Node.js version (output of `node --version`):v21.7.2
- `npm` version (output of `npm --version`): 10.5.2
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Android Device
- Real device or emulator/simulator: Real device

### Link to Appium Logs
[Chromedriver@a544] Changed state to 'starting'
[Chromedriver@a544] Using the static Chromedriver->Chrome mapping
[Chromedriver@a544] The most recent known Chrome version: 123.0.6312
[Chromedriver@a544] Found 0 executables in '/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac'
[Chromedriver@a544] No Chromedrivers were found in '/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac'
[Chromedriver@a544] Browser version in the supplied details: Chrome/121.0.6167.180
[Chromedriver@a544] Found Chrome bundle 'undefined' version '121.0.6167'
[Chromedriver@a544] Error: No Chromedriver found that can automate Chrome '121.0.6167'. You could also try to enable automated chromedrivers download as a possible workaround.
[Chromedriver@a544]     at Chromedriver.getCompatibleChromedriver (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:468:15)
[Chromedriver@a544]     at Chromedriver.initChromedriverPath (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:500:11)
[Chromedriver@a544]     at Chromedriver.start (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:620:32)
[Chromedriver@a544]     at AndroidUiautomator2Driver.setupNewChromedriver (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/helpers.js:745:3)
[Chromedriver@a544]     at AndroidUiautomator2Driver.startChromedriverProxy (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:229:10)
[Chromedriver@a544]     at AndroidUiautomator2Driver.switchContext (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:108:5)
[Chromedriver@a544]     at AndroidUiautomator2Driver.setContext (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:64:3)
[Chromedriver@a544] No Chromedriver found that can automate Chrome '121.0.6167'. You could also try to enable automated chromedrivers download as a possible workaround.
[AndroidUiautomator2Driver@f409 (061aef9a)] Encountered internal error running command: Error: No Chromedriver found that can automate Chrome '121.0.6167'. You could also try to enable automated chromedrivers download as a possible workaround.
[AndroidUiautomator2Driver@f409 (061aef9a)]     at Object.wrappedLogger.errorWithException (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/lib/logging.js:114:43)
[AndroidUiautomator2Driver@f409 (061aef9a)]     at Object.wrappedLogger.errorAndThrow (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/@appium/support/lib/logging.js:120:16)
[AndroidUiautomator2Driver@f409 (061aef9a)]     at Chromedriver.start (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/chromedriver.js:706:16)
[AndroidUiautomator2Driver@f409 (061aef9a)]     at AndroidUiautomator2Driver.setupNewChromedriver (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/helpers.js:745:3)
[AndroidUiautomator2Driver@f409 (061aef9a)]     at AndroidUiautomator2Driver.startChromedriverProxy (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:229:10)
[AndroidUiautomator2Driver@f409 (061aef9a)]     at AndroidUiautomator2Driver.switchContext (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:108:5)
[AndroidUiautomator2Driver@f409 (061aef9a)]     at AndroidUiautomator2Driver.setContext (/Users/shettya/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/context/exports.js:64:3)
[HTTP] <-- POST /wd/hub/session/061aef9a-6b26-47e4-90a1-c1ee39ba73da/context 500 146 ms - 802
[HTTP]
[HTTP] --> GET /wd/hub/session/061aef9a-6b26-47e4-90a1-c1ee39ba73da/screenshot
[HTTP] {}
[AndroidUiautomator2Driver@f409 (061aef9a)] Calling AppiumDriver.getScreenshot() with args: ["061aef9a-6b26-47e4-90a1-c1ee39ba73da"]
[AndroidUiautomator2Driver@f409 (061aef9a)] Matched '/screenshot' to command name 'getScreenshot'
[AndroidUiautomator2Driver@f409 (061aef9a)] Proxying [GET /screenshot] to [GET http://127.0.0.1:8201/session/92f6744f-26a6-4875-ad05-8ad0018475d9/screenshot] with no body
[AndroidUiautomator2Driver@f409 (061aef9a)] Got response with status 200: {"sessionId":"92f6744f-26a6-4875-ad05-8ad0018475d9","value":"iVBORw0KGgoAAAANSUhEUgAABDgAAAlgCAYAAABtGofVAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7N13fFNV/wfwz0060wGFtpTZsmmrzBZw0JahAi5U4FFkqaiA+jgRB7J9VMSFyHCxHMhyAvoTpS0io2UJbdkdjJamLbQ06ci4vz/SXpImaZO2aRL8vF8vXuTe3Htyzm3Gvd97zvcIhcUlIoiIiIiIiIiI3JjM2RUgIiIiIiIiImooBjiIiIiIiIiIyO0xwEFEREREREREbo8BDiIiIiIiIiJyewxwEBEREREREZHbY4CDiIiIiIiIiNweAxxERERERERE5PYY4CAiIiIiIiIit8cABxERERERERG5PQY4iIiIiIiIiMjtMcBBRERERERERG6PAQ4iIiIiIiIicnsMcBARERERERGR22OAg4iIiIiIiIjcHgMcREREREREROT2GOAgIiIiIiIiIrfHAAcRERERERERuT0GOIiIiIiIiIjI7THAQURERERERERujwEOIiIiIiIiInJ7DHAQERERERERkdtjgIOIiIiIiIiI3B4DHERERERERETk9hjgICIiIiIiIiK3xwAHEREREREREbk9BjiIiIiIiIiIyO0xwEFEREREREREbo8BDiIiIiIiIiJyewxwEBEREREREZHbY4CDiIiIiIiIiNweAxxERERERERE5PYY4CAiIiIiIiIit8cABxERERERERG5PQY4iIiIiIiIiMjtMcBBRERERERERG6PAQ4iIiIiIiIicnsMcBARERERERGR22OAg4iIiIiIiIjcHgMcREREREREROT2GOAgIiIiIiIiIrfHAAcRERERERERuT0PZ1eAiBpG0JXB48oOeF9YB4+iFEBXAVErQtCLhg30IkS5PzTBt0DT6QloggYCAj/6RERERER0fREKi0tEZ1eC...
[AndroidUiautomator2Driver@f409 (061aef9a)] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABDgAAAlgCAYAAABtGofVAAAAAXNSR0IArs4c6QAAAARzQklUCAgICHwIZIgAACAASURBVHic7N13fFNV/wfwz0060wGFtpTZsmmrzBZw0JahAi5U4FFkqaiA+jgRB7J9VMSFyHCxHMhyAvoTpS0io2UJbdkdjJamLbQ06ci4vz/SXpImaZO2aRL8vF8vXuTe3Htyzm3Gvd97zvcIhcUlIoiIiIiIiIiI3JjM2RUgIiIiIiIiImooBjiIiIiIiIiIyO0xwEFEREREREREbo8BDiIiIiIiIiJyewxwEBEREREREZHbY4CDiIiIiIiIiNweAxxERERERERE5PYY4CAiIiIiIiIit8cABxERERERERG5PQY4iIiIiIiIiMjtMcBBRERERERERG6PAQ4iIiIiIiIicnsMcBARERERERGR22OAg4iIiIiIiIjcHgMcREREREREROT2GOAgIiIiIiIiIrfHAAcRERERERERuT0GOIiIiIiIiIjI7THAQURERERERERujwEOIiIiIiIiInJ7DHAQERERERERkdtjgIOIiIiIiIiI3B4DHERERERERETk9hjgICIiIiIiIiK3xwAHEREREREREbk9BjiIiIiIiIiIyO0xwEFEREREREREbo8BDiIiIiIiIiJyewxwEBEREREREZHbY4CDiIiIiIiIiNweAxxERERERERE5PYY4CAiIiIiIiIit8cABxERERERERG5PQY4iIiIiIiIiMjtMcBBRERERERERG6PAQ4iIiIiIiIicnsMcBARERERERGR22OAg4iIiIiIiIjcHgMcREREREREROT2GOAgIiIiIiIiIrfHAAcRERERERERuT0PZ1eAiBpG0JXB48oOeF9YB4+iFEBXAVErQtCLhg30IkS5PzTBt0DT6QloggYCAj/6RERERER0fREKi0tEZ1eCiOwnq8hFYMbdwNVLELV6QC9e+yfCdFkvQtQDEEVAFCC26I6rg5MY6CAiIiIi...
[HTTP] <-- GET /wd/hub/session/061aef9a-6b26-47e4-90a1-c1ee39ba73da/screenshot 200 651 ms - 155172
[HTTP]

**Comment by mykola-mokhnach** [comment]
> [AndroidUiautomator2Driver@b2f2]     "appium:chromedriverExecutable": "'/Users/shettya/Downloads/Appium/chromedriver'",

the value probably contains extra quotes

**Comment by mykola-mokhnach** [comment]
> Added appium capabilities: setWebContentsDebuggingEnabled=${True}

This won't work. The web view must one made debugabble in the app source code

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions.
Closing this thread as not issue.

**Comment by mykola-mokhnach** [comment]
I'm sorry about your previous experience, but this is how open source works. It is usually easier for people to answer questions that have all the necessary details and the background info provided.

Eventually it would probably be the best to simply hire a consultant to solve an issue fast.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium/issues/16031 could be the case
