### ISSUE TITLE
bug: <Appium is unable to find a compatible Chromedriver version>

### ISSUE THREAD

**Issue by balajitoverto** [appium/appium#20144]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![23](https://github.com/appium/appium/assets/127953007/e17fe66f-f09b-458f-8617-f9fe67651436)

### Expected Behavior

Needs to run Appium testing as expected

### Minimal Reproducible Example

We tried to run Appium automation testing in our Angular Ionic Capacitor project. However, when we started the Appium server and executed the command to run the test case, we received a message indicating that Appium was unable to find the ChromeDriver. Despite having installed the stable version of ChromeDriver, the issue persists.
<script src="https://gist.github.com/balajitoverto/cf785c27c81b18e77697e587b88f99ec.js"></script>
![23](https://github.com/appium/appium/assets/127953007/81d4e10e-35d3-4368-b162-55854ee828f6)
`[AndroidDriver] A port was not given, using random free port: 8000
[AndroidDriver] Passing web view details to the Chromedriver constructor: {
[AndroidDriver]   "info": {
[AndroidDriver]     "Android-Package": "Android-Pacakage",
[AndroidDriver]     "Browser": "Chrome/124.0.6367.172",
[AndroidDriver]     "Protocol-Version": "1.3",
[AndroidDriver]     "User-Agent": "Mozilla/5.0 (Linux; Android 14; moto g34 5G Build/U1UGS34.23-28-2-3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.172 Mobile Safari/537.36",
[AndroidDriver]     "V8-Version": "12.4.254.15",
[AndroidDriver]     "WebKit-Version": "537.36 (@c56b583cb293b6482070736e2ff7ca2d99775a4e)",
[AndroidDriver]     "webSocketDebuggerUrl": "ws://127.0.0.1:10900/devtools/browser"
[AndroidDriver]   },
[AndroidDriver]   "process": {
[AndroidDriver]     "name": "Android-PacakageName",
[AndroidDriver]     "id": "3803"
[AndroidDriver]   }
[AndroidDriver] }
[AndroidDriver] Precalculated Chromedriver capabilities: {
[AndroidDriver]   "androidPackage": "Android-PacakageName",
[AndroidDriver]   "androidUseRunningApp": true,
[AndroidDriver]   "androidProcess": "Android-PacakageName",
[AndroidDriver]   "androidDeviceSerial": "ZA222JQ39L"
[AndroidDriver] }
[AndroidDriver] Before starting chromedriver, androidPackage is 'Android-PacakageName'
[Chromedriver] Changed state to 'starting'
[Chromedriver] Using the static Chromedriver->Chrome mapping
[Chromedriver] The most recent known Chrome version: 91.0.4472
[Chromedriver] Found 1 executable in 'C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win'
[Chromedriver] The following Chromedriver executables were found:
[Chromedriver]     'C:/Program Files/Appium Server GUI/resources/app/node_modules/appium/node_modules/appium-chromedriver/chromedriver/win/chromedriver.exe' (version '125.0.6422.76', minimum Chrome version '125')
[Chromedriver] Found 1 Chromedriver, which is missing in the list of known versions: {"125.0.6422.76":"125"}
[Chromedriver] Browser version in the supplied details: Chrome/124.0.6367.172
[Chromedriver] Found Chrome bundle 'undefined' version '124.0.6367'
[ChromedriverStorageClient] Parsed 776 entries from storage XML
[ChromedriverStorageClient] The entry '2.0/chromedriver_linux32.zip' does not contain any notes. Skipping it
[ChromedriverStorageClient] The entry '2.0/chromedriver_linux64.zip' does not contain any notes. Skipping it
[ChromedriverStorageClient] The entry '2.0/chromedriver_mac32.zip' does not contain any notes. Skipping it
[ChromedriverStorageClient] The entry '2.0/chromedriver_win32.zip' does not contain any notes. Skipping it
[ChromedriverStorageClient] The entry '2.1/chromedriver_linux32.zip' does not contain any notes. Skipping it
[ChromedriverStorageClient] The entry '2.1/chromedriver_linux64.zip' does not contain any notes. Skipping it
[ChromedriverStorageClient] The entry '2.1/chromedriver_mac32.zip' does not contain any notes. Skipping it`

### Environment

- Operating system: Windows
- Appium server version (output of `appium --version`): v1.22.3
- Platform and version under test: Android 14
- Real device or emulator/simulator: Real device

### Link to Appium Logs

https://gist.github.com/balajitoverto/cf785c27c81b18e77697e587b88f99ec.js

**Comment by KazuCocoa** [comment]
The chrome browser version running on the device was 124, but you gave 125. What about giving chromedriver 124 as the device has? Also, using latest UIA2 driver with Appium v2 with auto download https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#automatic-discovery-of-compatible-chromedriver might help as well.
