### ISSUE TITLE
[Feat]: Remove inflight dependency because it's no longer supported

### ISSUE THREAD

**Issue by einsteinsfool** [appium/appium#20154]
**Is your feature request related to a problem? Please describe.**
Installing appium returns a warning:
```
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
```

**Describe the solution you'd like**
Remove inflight dependency and use lru-cache instead.

**Additional context**
https://www.npmjs.com/package/inflight
Published 8 years ago

**Comment by KazuCocoa** [comment]
it looks like mostly by `rimraf` (only dev deps) and `glob`. https://github.com/isaacs/node-glob/issues/573
We've been using the latest version, so as the author, they might be sufficient as the lib usage.

It would be appreciated if you could share more concrete issues with logs about the issue or report it to the author.

**Comment by einsteinsfool** [comment]
To be honest, I didn't understand your reply at all. But feel free to ignore my questions since there seem to be no issue as you closed it.

| it looks like mostly by `rimraf`
I don't understand the grammar. What looks like rimraf?

| so as the author
As the author of what?

| might be sufficient
What might be sufficient?

| as the lib usage
What does that mean?

| share more concrete issues with logs
I'd need instructions what should I execute to get wanted logs.

| report it to the author
To the author of what? If inflight, then it is no longer supported so no fixed will be made.

**Comment by mykola-mokhnach** [comment]
The inflight dependenncy is not directly used by any appium modules, but only as a transitive dependency, most likely bundled with rimraf. This means we don't have much control over its usage and the issue must be reported to appropriate module authors instead.

**Comment by einsteinsfool** [comment]
Got it. I thought it's the case but checked npmlog (from my other issue) by mistake and saw it's directly in appium dependencies.
Thank you and my apologies.

**Comment by einsteinsfool** [comment]
I came to the conclusion that it's because of mocha and reported it [here](https://github.com/mochajs/mocha/issues/5148).

**Comment by eglitise** [comment]
I'm not fully sure that it's `mocha`, because Appium only imports it as a dev dependency, and packages that actually use it (`driver-test-support` and `plugin-test-support`) are not imported by the core `appium` package anyway.

**Comment by einsteinsfool** [comment]
@S-ee-n You can't (unless you modify Appium's code and build it yourself). It's mocha (which Appium uses) who would have to do it. It's a package that's used and you can't just switch it to another one without rewriting the code that uses it.
It's not a big problem since everything seems to be working but it's better to use a package that is maintained which inflight isn't.

**Comment by S-ee-n** [comment]
Thank you for your fast and accurate answer ! I’ll do what I can 
Have a nice day 👍🏻 👍🏻
