### ISSUE TITLE
when app starts and app home page comes， appium can only locate systemui, I need locate app home page  

### ISSUE THREAD

**Issue by 605775776** [appium/appium#20155]
when I use driver.page_source method, the result is a xml which only contains systemui page locatos, i need locate app home page elements , i need help thanks. [for example: package="com.android.systemui"]

**Comment by mykola-mokhnach** [comment]
Please fill out the report according to the given template. Closed as incomplete

**Comment by mykola-mokhnach** [comment]
If this is a question then please use Appium forum to ask it
