### ISSUE TITLE
[Feat]: Remove npmlog dependency because it's no longer supported

### ISSUE THREAD

**Issue by einsteinsfool** [appium/appium#20153]
**Is your feature request related to a problem? Please describe.**
Installing appium returns a warning:
`npm warn deprecated npmlog@7.0.1: This package is no longer supported.`

**Describe the solution you'd like**
Remove npmlog dependency from `package-lock.json` and `packages/support/README.md` and other files.

**Additional context**
https://www.npmjs.com/package/npmlog

**Comment by mykola-mokhnach** [comment]
The npmlog dependency has been replaced with the local fork.
