### ISSUE TITLE
 Original error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS' exited with code 1

### ISSUE THREAD

**Issue by prachisingla** [appium/appium#20162]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi All, 

I am facing issue with carthage on ios automation using python 

 Original error: Unable to launch WebDriverAgent because of xcodebuild failure: Command 'carthage bootstrap --platform iOS' exited with code 1

I have tried reinstalling appium , carthage and ran appium doctor as well but when i run via code getting the above issue.

<img width="770" alt="Screenshot 2024-05-30 at 10 39 22 PM" src="https://github.com/appium/appium/assets/59165741/5365ca72-52d0-4452-8e21-a26366d373a5">

Xcode version : 15.3
Appium version:1.22.3
carthage version : 0.39.1
carthage path : /usr/local/bin/carthage

### Expected Behavior

Should be able to run it successfully

### Minimal Reproducible Example

 if not device_name:
                pytest.exit('No attached device found')
            log.info('Initializing Driver for %s , %s, %s' % (tstEnv, device_name, app_os))
            log.info(' Data are %s , %s, %s, %s' % (tstEnv, device_name, device, app_os))
            setupObj = localSetUp(tstEnv, device, device_name, app_os, deviceUid = device_udid)
            return setupObj

### Environment

- Operating system: MAC
- Appium server version (output of `appium --version`): 1.22.3
- Node.js version (output of `node --version`): v22.2.0
- `npm` version (output of `npm --version`): 10.7.0
- Platform and version under test: Iphone , ios17
- Real device or emulator/simulator: Real device

**Comment by mykola-mokhnach** [comment]
We do not support Appium 1 anymore. Please upgrade to v2

**Comment by prachisingla** [comment]
But Android automation is working fine using same appium version , does carthage doesnot support this version ?

**Comment by prachisingla** [comment]
This is still not fixed for me, pls check

**Comment by KazuCocoa** [comment]
Newer Xcode/iOS versions have no compatibility with old appium versions
