### ISSUE TITLE
[Feat]: add company logo icons in SPONSORS.md

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#20167]
(from https://github.com/appium/appium/pull/20166#issuecomment-2142849381)

Current logos in SPONSORS.md is a list of names and links. They could be an image to improve the visualization as sponsors.

Then, perhaps we may need to consider:

1. the size of each tir
    - Should we modify the logo size? e.g. Dev/Strategic should be larger than others
2. where should we bring logo icons from
    - the sponsor's website, opencollective's page etc
3. update opencollective/GOVERNANCE.md description and announce existing sponsors about this update

cc @jlipps @mykola-mokhnach  @eglitise

**Comment by eglitise** [comment]
Is this really worth making a separate ticket for...? The opencollective description already mentions logo placement, so in my opinion the logos should have been added from the start.

**Comment by KazuCocoa** [comment]
Oh, i see. Then, the initial change https://github.com/appium/appium/pull/20054 needed to add more then.

Either is fine for me. Since the list already has one name, I thought I would add additional names first and then modify the list with icons

**Comment by eglitise** [comment]
I think #20166 is a small enough change that it might as well also include the logos

**Comment by KazuCocoa** [comment]
I wondered if opencollevtive has https://opencollective.com/appium/backers.svg for each tir. It is the most easy to maintain. This is only for individual contributors.

**Comment by KazuCocoa** [comment]
I found the proper URLs I originally wanted to get as https://github.com/appium/appium/pull/20166#issuecomment-2142853160. We don't need to manage images/lists by us with this. So we can embed these SVGs in each tire. Some are currently blank. Dev and Strategic may need to be handled separately, but thy could be later. 

https://opencollective.com/appium/tiers/platinum-sponsor.svg?avatarHeight=80
https://opencollective.com/appium/tiers/gold-sponsor.svg?avatarHeight=70
https://opencollective.com/appium/tiers/silver-sponsor.svg?avatarHeight=60
https://opencollective.com/appium/tiers/sponsors.svg?avatarHeight=50

I'll create a pr with this later
