### ISSUE TITLE
[Feat]: Support for JavaFX / Swing Desktop applications

### ISSUE THREAD

**Issue by philipp-michelfeit** [appium/appium#20172]
Currently, there is no driver to support JavaFX / Swing desktop applications.

It would be really nice to have such a driver.

**Comment by mykola-mokhnach** [comment]
Unfortunately we don't have any plans for working on something like that in the near future and we also don't have JavaFX expertise in the team.  But if someone would like to create a driver to automate this type of apps then let us know. We would be happy to provide insights or perform code review

**Comment by Vampire** [comment]
Maybe you would not need too much of such expertise @mykola-mokhnach.
https://github.com/jalian-systems/marathonv5 implemented WebDriver for driving Swing and / or JavaFX applications.
Unfortunately, it seems the company maintaining that project died away.
But probably the WebDriver parts should still be usable, so maybe you only need a proxy driver like mentioned on https://appium.io/docs/en/2.17/intro/drivers/#proxy-mode to support it or something like that? :-)
