### ISSUE TITLE
iOS 17 always get driver-to-platform version mismatch on Real Devices

### ISSUE THREAD

**Issue by fatahillahardhi** [appium/appium#20173]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The XCUITest on real devices has suddenly stopped working properly. It always shows:
`org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Error: Unable to launch WebDriverAgent. Original error: xcodebuild failed with code 65. This usually indicates an issue with the local Xcode setup or WebDriverAgent project configuration or the driver-to-platform version mismatch. Consider checking the WebDriverAgent configuration guide for real iOS devices at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md.. Make sure you follow the tutorial at https://appium.github.io/appium-xcuitest-driver/latest/preparation/real-device-config/ `
 
even though I didn't change any iOSDriver settings or capabilities from [here](https://github.com/appium/appium/issues/20096#issuecomment-2112196846).

I don't know why in Appium Logs always show's:
`Test target WebDriverAgentRunner encountered an error (The bundle identifier for WebDriverAgentRunner-Runner.app couldn’t be read. No such file or directory: “/Users/devicefarm/Library/Developer/Xcode/DerivedData/WebDriverAgent-00008030-001419043428C02E/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app”.)`

### Expected Behavior

It will work well.

### Minimal Reproducible Example

1. Setup PreinstalledWda
2. Run Appium

### Environment

- Operating system: Mac OS Sonoma
- Appium server version (output of `appium --version`): 2.5.4
- Appium driver(s) and their version(s) (`appium driver list`): XCUITest 7.17.0
- Appium plugin(s) and their version(s) (`appium plugin list`): Device Farm 8.4.6
- Node.js version (output of `node --version`): 16.5.1
- `npm` version (output of `npm --version`): 8.11.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iPhone iOS 17
- Real device or emulator/simulator: Real Device

### Link to Appium Logs

https://gist.github.com/fatahillahardhi/cb5f5d0cf196aaa957f4d51adba554c2

### Further Information

my capabilities are
 ```
        options.setCommandTimeouts(Duration.ofSeconds(30));
        options.setWdaLaunchTimeout(Duration.ofSeconds(90));
        options.setWdaConnectionTimeout(Duration.ofSeconds(90));
        options.setShouldUseSingletonTestManager(false);
        options.setLaunchWithIdb(true);
        options.setAppInstallStrategy("ios-deploy");
        options.setUseNewWDA(false);
        options.showXcodeLog();
        options.setUsePrebuiltWda(true);
        options.setUpdatedWdaBundleId("com.bibit.WebDriverAgentRunner");
        options.setCapability("prebuiltWDAPath", env("WDA_PATH_IOS_17"));
```

XCODE Version 15.3

**Comment by KazuCocoa** [comment]
What happens when you run the `xcodebuild` command directly as the log? You might also check if the signature works with Xcode. Afaik, the xcodebuild error 65 is signing related by the `xcodebuild` command. 
```
[XCUITestDriver@18b2 (dea021d2)] Beginning test with command 'xcodebuild test-without-building -project /Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/devicefarm/Library/Developer/Xcode/DerivedData/WebDriverAgent-00008030-001419043428C02E -destination id=00008030-001419043428C02E IPHONEOS_DEPLOYMENT_TARGET=17.2 DEVELOPMENT_TEAM=82PW96YW65 CODE_SIGN_IDENTITY=Apple Developer GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
[XCUITestDriver@18b2 (dea021d2)] Output from xcodebuild will be logged. To change this, use 'showXcodeLog' desired capability
[XCUITestDriver@cf00] Matched '/status' to command name 'getStatus'
[XCUITestDriver@cf00] Proxying [GET /status] to [GET http://127.0.0.1:56184/status] with no body
[iProxy@00008030:56184] Connection was refused to port 56184
[XCUITestDriver@cf00] socket hang up
[Xcode] Command line invocation:
[Xcode]
[XCUITestDriver@18b2 (dea021d2)] Waiting up to 90000ms for WebDriverAgent to start
[XCUITestDriver@18b2 (dea021d2)] Matched '/status' to command name 'getStatus'
[XCUITestDriver@18b2 (dea021d2)] Proxying [GET /status] to [GET http://127.0.0.1:56184/status] with no body
[Xcode] /Users/devicefarm/Downloads/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -project /Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/devicefarm/Library/Developer/Xcode/DerivedData/WebDriverAgent-00008030-001419043428C02E -destination id=00008030-001419043428C02E IPHONEOS_DEPLOYMENT_TARGET=17.2 DEVELOPMENT_TEAM=82PW96YW65 "CODE_SIGN_IDENTITY=Apple Developer" GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
...
[Xcode] 2024-06-02 22:23:37.632 xcodebuild[57102:3026918] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[Xcode] 2024-06-02 22:23:37.632 xcodebuild[57102:3026918] [MT] IDETestOperationsObserverDebug: 0.135 sec, +0.135 sec -- end
[Xcode]
[Xcode]
[Xcode] Test session results, code coverage, and logs:
[Xcode] 	/Users/devicefarm/Library/Developer/Xcode/DerivedData/WebDriverAgent-00008030-001419043428C02E/Logs/Test/Test-WebDriverAgentRunner-2024.06.02_22-23-37-+0700.xcresult
[Xcode]
[Xcode]
[Xcode] Testing failed:
[Xcode] 	Test target WebDriverAgentRunner encountered an error (The bundle identifier for WebDriverAgentRunner-Runner.app couldn’t be read. No such file or directory: “/Users/devicefarm/Library/Developer/Xcode/DerivedData/WebDriverAgent-00008030-001419043428C02E/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app”.)
[Xcode]
[Xcode] ** TEST EXECUTE FAILED **
```


Your capabilities has `prebuiltWDAPath`. I guess you would also try out the `app` without xcodebuild the above. Then `appium:usePreinstalledWDA` would help https://appium.github.io/appium-xcuitest-driver/latest/guides/run-preinstalled-wda/

**Comment by fatahillahardhi** [comment]
When I try 
`xcodebuild test-without-building -project /Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/devicefarm/Library/Developer/Xcode/DerivedData/WebDriverAgent-00008030-001419043428C02E -destination id=00008030-001419043428C02E IPHONEOS_DEPLOYMENT_TARGET=17.2 DEVELOPMENT_TEAM=82PW96YW65 CODE_SIGN_IDENTITY=Apple Developer GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent`

I get errors
```
Command line invocation:
    /Users/devicefarm/Downloads/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -project /Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath /Users/devicefarm/Library/Developer/Xcode/DerivedData/WebDriverAgent-00008030-001419043428C02E -destination id=00008030-001419043428C02E IPHONEOS_DEPLOYMENT_TARGET=17.2 DEVELOPMENT_TEAM=82PW96YW65 CODE_SIGN_IDENTITY=Apple Developer GCC_TREAT_WARNINGS_AS_ERRORS=0 "COMPILER_INDEX_STORE_ENABLE=NO in directory /Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent"

User defaults from command line:
    IDEDerivedDataPathOverride = /Users/devicefarm/Library/Developer/Xcode/DerivedData/WebDriverAgent-00008030-001419043428C02E
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    CODE_SIGN_IDENTITY = Apple
    COMPILER_INDEX_STORE_ENABLE = NO in directory /Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent
    DEVELOPMENT_TEAM = 82PW96YW65
    GCC_TREAT_WARNINGS_AS_ERRORS = 0
    IPHONEOS_DEPLOYMENT_TARGET = 17.2

2024-06-02 23:48:29.800 xcodebuild[7061:40480] Writing error result bundle to /var/folders/1c/fkr003qs15vbk4s5927d3_k40000gn/T/ResultBundle_2024-02-06_23-48-0029.xcresult
xcodebuild: error: Unknown build action 'Developer'.
```

----
I don't understand about  `I guess you would also try out the app without xcodebuild the above` because my capabilities has 

```
options.setUsePrebuiltWda(true);
options.setUpdatedWdaBundleId("com.bibit.WebDriverAgentRunner");
options.setCapability("prebuiltWDAPath", env("WDA_PATH_IOS_17"));
```
but still build with xcodebuild(?)

**Comment by KazuCocoa** [comment]
You set `setUsePrebuiltWda`. It runs xcodebuild with `test-without-building` for the given `derivedDataPath`. ( https://appium.github.io/appium-xcuitest-driver/latest/guides/run-prebuilt-wda/ )

```
[XCUITestDriver@cf00]     "appium:usePrebuiltWDA": true,
[XCUITestDriver@cf00]     "appium:derivedDataPath": "/Users/devicefarm/Library/Developer/Xcode/DerivedData/WebDriverAgent-00008030-001419043428C02E"
```


If you would like to try out https://appium.github.io/appium-xcuitest-driver/latest/guides/run-preinstalled-wda/, it requires `appium:usePreinstalledWDA`. Then, to avoid possible confusion in the capabilities, please remove `usePrebuiltWDA` and `derivedDataPath`.
https://appium.github.io/appium-xcuitest-driver/latest/reference/capabilities/

**Comment by fatahillahardhi** [comment]
ok so I just use this capabilites?

```
options.setUpdatedWdaBundleId("com.bibit.WebDriverAgentRunner");
options.setCapability("prebuiltWDAPath", env("WDA_PATH_IOS_17"));
```

anyway I didn't use `derivedDataPath` maybe it's automatically from Appium

**Comment by mykola-mokhnach** [comment]
In order to use the prebuilt WDA it must be built properly first. If there is nothing to use then the command would fail which is expected.

**Comment by fatahillahardhi** [comment]
Thank you @KazuCocoa when i used this caps [here](https://github.com/appium/appium/issues/20173#issuecomment-2143951684) it works well🍻

**Comment by bwomsm1** [comment]
@KazuCocoa I am getting the same issue, 
I tried running with:
```
options.setUpdatedWdaBundleId("com.bibit.WebDriverAgentRunner");
options.setCapability("usePreinstalledWDA",true);
options.setCapability("prebuiltWDAPath", env("WDA_PATH_IOS_17"));
```
But it seems that the webDriverAgent crashes on launch, if I remember correctly when you click manually open the webAgentDriver you should get to a black screen, in my case it is crahsing,
Any idea what is the problem?

**Comment by KazuCocoa** [comment]
Did you do https://appium.github.io/appium-xcuitest-driver/latest/guides/run-preinstalled-wda/#additional-requirement-for-ios-17tvos17 ?

**Comment by KazuCocoa** [comment]
So, do you want to launch WDA by clicking the icon, but the device's crashlog showed WDA got crashed immediately? Then, please share the device log to see what caused the crash. Perhaps it is not library referencing one.

Then, please create a new issue as different issue here since it is not with usePreinstalledWDA.

**Comment by bwomsm1** [comment]
> usePreinstalledWDA

@KazuCocoa hi,
First, I am taking my words back, after checking again, the `WebDriverAgentRunner` app did not crash on launch, the behavior is correct as I see it.
<br>

Secondly, I am not sure I fully understand what to open another ticket about? 

Anyhow, <br>
I created additional 2 logs, on both I have `showXcodeLog = true`:<br>
Failure **with** `usePreinstalledWDA = true`: https://github.com/bwomsm1/AppiumLogs/blob/master/with_usePreinstalledWDA.log
<br>
Failure **without** `usePreinstalledWDA` flag: https://github.com/bwomsm1/AppiumLogs/blob/master/withOUT_usePreinstalledWDA.log


Something else you need here?

**Comment by KazuCocoa** [comment]
> what to open another ticket about?

I meant create a new GitHub issue to not mix up various topics in one issue.
Your commend in https://github.com/appium/appium/issues/20173#issuecomment-2402107989 said _in my case it is crahsing_, so I thought yours were mainly WDA crashing related. It is different from this issue's main point.

> Failure without usePreinstalledWDA flag:

This one is with xcodebuild. The session issued `xcodebuild build-for-testing test-without-building -project /Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=00008110-0012150921E2401E IPHONEOS_DEPLOYMENT_TARGET=18.1 DEVELOPMENT_TEAM=WGYJF9YTP7 CODE_SIGN_IDENTITY=iPhone Developer GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO` command but it raised:
> [614edc67][Xcode] xcodebuild: error: Failed to build project WebDriverAgent with scheme WebDriverAgentRunner.: Cannot test target “WebDriverAgentRunner” on “qa_iphone_06”: qa_iphone_06’s iOS 18.0.1 doesn’t match WebDriverAgentRunner’s iOS 18.1 deployment target.

So, did `00008110-0012150921E2401E`expected to be iOS 18.1 as your capabilities, or the xcodebuild's detection was correct? Appium just gives `-destination id=00008110-0012150921E2401E` to the xcodebuild command in this case, thus the detection comes from iOS/xcodebuild side. If the `00008110-0012150921E2401E` was not `“qa_iphone_06”: qa_iphone_06’s iOS 18.0.1`, xcodebuild could has an issue. You may need to report it to Apple so that Apple will be able to fix xcodebuild target issue.


Please share logs with `appium:showIOSLog` for _Failure with usePreinstalledWDA = true_. I assume WDA failed to start by some reasons.
