### ISSUE TITLE
bug: iOS - XCUITest - WDA crash during parallel Appium automation

### ISSUE THREAD

**Issue by avivdodi** [appium/appium#20184]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- 2 real iPhones with a unique installed WDA and 2 appium servers on iMac 14.1.2 (23B92).
I'm running Appium tests. The devices are running in parallel, and after 2-3 tests, one of the WDAs crashed, and the tests failed with "xcodebuild failed with code 65."

- **Attached is the log of the failed device.**

### Expected Behavior

2 real iPhones with a unique installed WDA and 2 Appium servers will run tests in parallel without any interruptions.

### Minimal Reproducible Example

- commands to run the 2 appium servers:
- `appium server --address 0.0.0.0 --port 4801 --driver-xcuitest-webdriveragent-port 8205 --relaxed-security`
- `appium server --address 0.0.0.0 --port 4800 --driver-xcuitest-webdriveragent-port 8200 --relaxed-security`
- commands to run the 2 WDA's:
- `xcodebuild build-for-testing test-without-building -project /Users/automobile/Projects/WDA/appium-webdriveragent_dairy/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=00008110-001E14613A04801E -configuration Debug USE_PORT=8200 test -allowProvisioningUpdates -derivedDataPath /Users/automobile/Projects/WDA/appium-webdriveragent_dairy/DerivedData`
- `xcodebuild build-for-testing test-without-building -project /Users/automobile/Projects/WDA/appium-webdriveragent_beef/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=00008110-001138182668401E -configuration Debug USE_PORT=8205 test -allowProvisioningUpdates -derivedDataPath /Users/automobile/Projects/WDA/appium-webdriveragent_beef/DerivedData`

### Environment

- Operating system: iMac 14.1.2 (23B92).
- Appium server version (output of `appium --version`): **2.1.3 (due to company restrictions im using that version)**
- Appium driver(s) and their version(s) (`appium driver list`): 
**- flutter@1.12.0 [installed (npm)]
- xcuitest@4.34.1 [installed (npm)]
- uiautomator2@2.34.1 [installed (npm)]**
- Appium plugin(s) and their version(s) (`appium plugin list`): none.
- Node.js version (output of `node --version`):
- **v22.2.0**
- `npm` version (output of `npm --version`):
- **10.7.0**
- Last component(s) version which did _not_ exhibit the problem: none.
- Platform and version under test:
- iPhone13
- os 16.3.1 
- Real device or emulator/simulator:
Real device

### Further Information

[appium.log](https://github.com/user-attachments/files/15545410/appium.log)
[wda.log](https://github.com/user-attachments/files/15545411/wda.log)

**Comment by KazuCocoa** [comment]
Did a single run have no issue? I wondered if two `xcodebuild` with the same derivedDataPath could cause building material conflicts.

**Comment by mykola-mokhnach** [comment]
Do you follow https://github.com/appium/appium-xcuitest-driver/blob/master/docs/guides/parallel-tests.md while configuring tests?

**Comment by avivdodi** [comment]
@KazuCocoa Yes, a single run passed with no interruptions. 
In the start, the WDA paths in the Appium log was the shared project, even that the flow of the unique WDA build was implemented. the old logs contained the follows:

`[38;5;32m[XCUITestDriver@1038 (12305082)][0m Using WDA path: '/Users/automobile/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
[38;5;32m[XCUITestDriver@1038 (12305082)][0m Using WDA agent: '/Users/automobile/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'`

@mykola-mokhnach yes. in my example you will not find the key `mjpegServerPort` because I remove in that test to see if it affect something. you can see in the Appium logs.

**Comment by mykola-mokhnach** [comment]
Unfortunately even if there is a bug there we won't be able to address it as we don't patch older driver versions.

Regarding the log itself I can observe that at some point of time 

> [debug] [38;5;32m[XCUITestDriver@5fb3 (f03f24bf)][0m Proxying [GET /source?scope=AppiumAUT] to [GET http://127.0.0.1:8205/session/786008DA-072E-4D39-B85C-6AF68799EEDA/source?scope=AppiumAUT] with no body
> [debug] [38;5;128m[iProxy@00008110:8205][0m Connection was refused to port 8205
> [38;5;32m[XCUITestDriver@5fb3 (f03f24bf)][0m socket hang up

The server stopped responding and the server got a new session request without deleting the old one. Always make sure you close/quit previous sessions before starting new ones on the same device.

**Comment by KazuCocoa** [comment]
I wondered if `bootstrapPath` / `derivedDataPath` paths need to be unique per xcodebuild.

**Comment by avivdodi** [comment]
@mykola-mokhnach I will validate that the session is closed and test it a few times.
@KazuCocoa it looks like each driver instance should get a unique path (https://github.com/appium/appium-xcuitest-driver/blob/master/docs/guides/parallel-tests.md)
