### ISSUE TITLE
[Feat]: Appium to generate .gcov, .gcna, .gcda files for iOS apps code coverage

### ISSUE THREAD

**Issue by kmvkrish** [appium/appium#20196]
**Is your feature request related to a problem? Please describe.**
When appium tests are finished, require to have the Appium to generate .gcov files for code coverage in the app.

**Describe the solution you'd like**
Generated .gcov/.gcda/.gcna files can be used to fetch the code coverage report for our decision making.

**Describe alternatives you've considered**
No alternatives found. But we used the following articles and able to generate code coverage files for few files, but not for .swift files.

https://developer.apple.com/library/archive/qa/qa1514/_index.html
https://stackoverflow.com/questions/39233514/code-coverage-with-appium-for-ios
https://github.com/appium/appium/issues/1013
https://stackoverflow.com/questions/13453715/uiautomation-with-code-coverage

But could not file any success

**Comment by mykola-mokhnach** [comment]
Code coverage only makes sense for whitebox/greybox testing frameworks. XCUITest is a blackbox solution, it knows nothing about app internals and thus is unable to generate any coverage reports.

**Comment by kmvkrish** [comment]
Hi @mykola-mokhnach ,
We are looking for Appium to generate code coverage for the iOS app, when XCUITests are ran.
