### ISSUE TITLE
Appium can't reach elements in iOS source tree and it works fine in android (with the same codebase)

### ISSUE THREAD

**Issue by imanekaabouche** [appium/appium#20204]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In iOS, I'm unable to access the element **request.answer.list**, as shown in the screenshot.

![IOS](https://github.com/appium/appium/assets/118836066/d6c43b39-59ec-4b91-9a57-a3fff0aaa2b1)

### Expected Behavior

In Android, everything appears to be correct. I can inspect elements under **request.answer.list**

![Android](https://github.com/appium/appium/assets/118836066/bd277b0f-0292-41c8-b7a4-9a4574a8e9c9)

### Environment

i use Appium live in BrowserStack 
I use Iphone 13 
<img width="786" alt="appLive" src="https://github.com/appium/appium/assets/118836066/14196f0b-c3c3-49f8-8a7d-723c1d8fad36">

**Comment by eglitise** [comment]
This is a known issue if your app is written in React Native. [Please check the Inspector documentation on ways to handle this problem.](https://appium.github.io/appium-inspector/latest/troubleshooting/#cannot-see-full-source-tree-with-xcuitest-driver-react-native-app)

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
