### ISSUE TITLE
WebDriverAgent v8.7.2 cause Appium touch error

### ISSUE THREAD

**Issue by zypdominate** [appium/appium#20218]
environment:
**WebDriverAgent**：https://github.com/appium/WebDriverAgent/releases/tag/v8.7.2
MacOS: Sonoma 14.5
Xcode: 15.4
Python: 3.7
appium: '1.2.0'

when I  execute this automation python code on iOS platform: 
```python
from appium import webdriver
from appium.webdriver.common.touch_action import TouchAction
...
TouchAction(self.driver).tap(x=int(x), y=int(y), count=1).perform() 
``` 
there is erorr:
```
Unhandled endpoint: /session/8D9453B1-DA56-4CBF-9502-CEEFCA9ECD9E/wda/touch/perform -- http://127.0.0.1:8100/ with parameters { wildcards = ( "session/8D9453B1-DA56-4CBF-9502-CEEFCA9ECD9E/wda/touch/perform" ); }' 
```

test 'OK' button:
![image](https://github.com/appium/appium/assets/29668552/c30c5166-e408-4d1a-8669-06e500e2f211)

debug code:
![image](https://github.com/appium/appium/assets/29668552/881f69a4-a72e-412c-b1fc-780b9b5391b1)

**Comment by eglitise** [comment]
[TouchActions have been removed in WDA 7.0](https://github.com/appium/WebDriverAgent/pull/847). Please use W3C Actions instead.
Also, we do not support Appium 1 anymore - please upgrade to Appium 2.
