### ISSUE TITLE
bug:  Unable to build plugin with latest appium server version

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#20243]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently adding the peerDepdencies version 2.9.0 to one of the plugins is breaking to build the plugin. 

https://gist.github.com/saikrishna321/1954dde28ba95b55efd4f848092f54f1

### Expected Behavior

Should be able to build the plugin.

### Minimal Reproducible Example

https://gist.github.com/saikrishna321/1954dde28ba95b55efd4f848092f54f1

### Environment

https://gist.github.com/saikrishna321/1954dde28ba95b55efd4f848092f54f1

### Link to Appium Logs

https://gist.github.com/saikrishna321/1954dde28ba95b55efd4f848092f54f1

**Comment by mykola-mokhnach** [comment]
In the recent server version we have replaced the deprecated npmlog package with the local fork. This should not affect external interfaces unless you invoke unwrap() on the logger, which is an internal call

**Comment by saikrishna321** [comment]
@mykola-mokhnach No I'm not using unwrap

My logger looks like this 

```
import { logger } from '@appium/support';
const which_appium = process.env.APPIUM_HOME || 'main';
const log = logger.getLogger(`device-farm-${which_appium}`);
export default log;

```

**Comment by mykola-mokhnach** [comment]
> src/iProxy.ts:24:5 - error TS2322: Type 'import("/Users/saikrishna/Downloads/git/appium-device-farm/node_modules/@appium/support/node_modules/@appium/types/build/lib/logger").AppiumLogger' is not assignable to type 'import("/Users/saikrishna/Downloads/git/appium-device-farm/node_modules/@appium/types/build/lib/logger").AppiumLogger'.


then probably there is a type conflict somewhere between dependencies. Make sure they all use the most recent version of type definitions module rather than depend on different ones.

**Comment by saikrishna321** [comment]
@mykola-mokhnach Updated all the dependencies to the latest and now I see the above error gone, but with others remaining 

```
❯ npm run bundle

> appium-device-farm@8.4.7-rc.38 bundle
> npm run build && webpack


> appium-device-farm@8.4.7-rc.38 build
> rm -rf lib && npx tsc -b && npm run buildAndCopyWeb && npm run copy-files

node_modules/@appium/logger/lib/log.ts:11:3 - error TS4104: The type 'readonly ["silly", number, { readonly inverse: true; }, "sill"]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.

11   ['silly', -Infinity, {inverse: true}, 'sill'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@appium/logger/lib/log.ts:12:3 - error TS4104: The type 'readonly ["verbose", 1000, { readonly fg: "cyan"; readonly bg: "black"; }, "verb"]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.

12   ['verbose', 1000, {fg: 'cyan', bg: 'black'}, 'verb'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@appium/logger/lib/log.ts:13:3 - error TS4104: The type 'readonly ["info", 2000, { readonly fg: "green"; }]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.

13   ['info', 2000, {fg: 'green'}],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@appium/logger/lib/log.ts:14:3 - error TS4104: The type 'readonly ["timing", 2500, { readonly fg: "green"; readonly bg: "black"; }]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.

14   ['timing', 2500, {fg: 'green', bg: 'black'}],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@appium/logger/lib/log.ts:15:3 - error TS4104: The type 'readonly ["http", 3000, { readonly fg: "green"; readonly bg: "black"; }]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.

15   ['http', 3000, {fg: 'green', bg: 'black'}],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@appium/logger/lib/log.ts:16:3 - error TS4104: The type 'readonly ["notice", 3500, { readonly fg: "cyan"; readonly bg: "black"; }]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.

16   ['notice', 3500, {fg: 'cyan', bg: 'black'}],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@appium/logger/lib/log.ts:17:3 - error TS4104: The type 'readonly ["warn", 4000, { readonly fg: "black"; readonly bg: "yellow"; }, "WARN"]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.

17   ['warn', 4000, {fg: 'black', bg: 'yellow'}, 'WARN'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@appium/logger/lib/log.ts:18:3 - error TS4104: The type 'readonly ["error", 5000, { readonly fg: "red"; readonly bg: "black"; }, "ERR!"]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.

18   ['error', 5000, {fg: 'red', bg: 'black'}, 'ERR!'],
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@appium/logger/lib/log.ts:19:3 - error TS4104: The type 'readonly ["silent", number]' is 'readonly' and cannot be assigned to the mutable type 'any[]'.

19   ['silent', Infinity],
     ~~~~~~~~~~~~~~~~~~~~


Found 9 errors.
```

**Comment by mykola-mokhnach** [comment]
this one is really weird, I don't see any errors when compiling the server source locally.
Perhaps, it has something to do with typescript version/settings.
I've created a simple patch that would probably address that error: https://github.com/appium/appium/pull/20244

**Comment by saikrishna321** [comment]
Once published will give it a try!

**Comment by dlenroc** [comment]
@mykola-mokhnach I've encountered a similar issue today when tried to upgrade to latest `@appium/*`. Most likely, it is related to the usage of `index.ts` instead of `index.d.ts` in:
https://github.com/appium/appium/blob/c670010ec7ea1c2730839e86b308837a83fc026e/packages/logger/package.json#L12

The change below will fix the issue, as the use of `.d.ts` in types will allow derived TypeScript projects to build their code using their own `tsconfig.json` preferences without need to rebuild `@appium/logging` too.
```diff
- "types": "index.ts",
+ "types": "build/index.d.ts",
```

**Comment by mykola-mokhnach** [comment]
thanks for the hint @dlenroc 
Would you like to propose a PR containing this fix?

**Comment by dlenroc** [comment]
@mykola-mokhnach, I've created https://github.com/appium/appium/pull/20247.
@saikrishna321, could you please make the same change in `node_modules/@appium/logger/package.json` directly and try rebuilding your project to see if that fixes the issue on your side too?
