### ISSUE TITLE
blank screenshot of chromecast when playing video that rendered by surface view

### ISSUE THREAD

**Issue by Jiyvn** [appium/appium#20258]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

blank screenshot when playing video
<img width="782" alt="image" src="https://github.com/appium/appium/assets/73217816/8d24e0fa-3197-42c4-a776-c504906858e7">
<img width="1351" alt="image" src="https://github.com/appium/appium/assets/73217816/d6351c37-1cb8-4792-b9c8-3d7f33f6b624">

### Expected Behavior

UI should be rendered in the screenshot

### Minimal Reproducible Example

start app with caps:
```
{
  "appium:deviceName": "GZ Chromecast",
  "platformName": "android",
  "appium:platformVersion": "12",
  "appium:udid": "18101HFDD3900G",
  "appium:automationName": "UIAutomator2",
  "appium:app": "/Users/macmini_gz01/workspace/tv/androidtv/tv_app.apk",
  "appium:noReset": true,
  "appium:bundleID": "com.viu.tv",
  "appium:appWaitActivity": "com.viu.tv.mvp.ui.activity.WelcomeActivity",
  "appium:enableWebviewDetailsCollection": true,
  "appium:autoGrantPermissions": true,
  "appium:appWaitDuration": "90000"
}
```

### Environment

- Operating system: macos 14.5 
- Appium server version (output of `appium --version`): 2.10.3
- Appium driver(s) and their version(s) (`appium driver list`): uiautomator2@3.5.5
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`): v20.14.0
- `npm` version (output of `npm --version`): 10.7.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: android 12
- Real device or emulator/simulator: chromecast

### Further Information

[blank-screenshot-on-android-tv.log](https://github.com/user-attachments/files/15866137/blank-screenshot-on-android-tv.log)
timestamp: utc+8 2024-06-17 18:30~18:35

confirmed that screenshot is normal with build using texture view but it is blank using surface view https://developer.android.com/reference/android/view/SurfaceView

**Comment by mykola-mokhnach** [comment]
We use the standard screenshotting API from UiAutomator: https://github.com/appium/appium-uiautomator2-server/blob/2dc5c830506e51b4b70eda58533eb6ba9a07200e/app/src/main/java/io/appium/uiautomator2/utils/ScreenshotHelper.java#L85

Please report the issue to Google as we cannot do much to change anything there.

**Comment by amedvedjev** [comment]
interesting if try adb commands in such case -> https://adbshell.com/commands/adb-shell-screencap

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
