### ISSUE TITLE
Session error with videoTimeLimit > 1800

### ISSUE THREAD

**Issue by nskcashHH** [appium/appium#20265]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi! In the appium-device-farm plugin, it is now possible to change the recording time of the video session and now if you specify a value > 1800, the driver issues an error. Подобное поведение на iOS и android.
the appeal in the plugin
https://github.com/AppiumTestDistribution/appium-device-farm/issues/1183

### Expected Behavior

What is the reason for this restriction? I would like to indicate a value of at least 2-3 hours in seconds that the tests were recorded in full.

### Minimal Reproducible Example

https://gist.github.com/nskcashHH/87dd3d222bedf81e8e0e48650142150f

### Environment

- Operating system: MAC OS 14.4.1
- Appium server version (output of `appium --version`): 2.9.0
- Appium driver(s) and their version(s) (`appium driver list`): uiautomator2@2.45.1 , xcuitest@7.14.0
- Appium plugin(s) and their version(s) (`appium plugin list`): device-farm@8.4.7-rc.40
- Node.js version (output of `node --version`): v22.2.0
- `npm` version (output of `npm --version`): 10.7.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: real device and emulator simulator

**Comment by KazuCocoa** [comment]
As the error message, 1800 is the max value for the endpoint usage as Appium.

```
[HTTP] --> POST /wd/hub/wd-internal/session/0cf65adc-d8e5-41c0-baec-5ba9bbe51a5b/appium/start_recording_screen
[HTTP] {"options":{"videoType":"libx264","videoFps":10,"videoScale":"1280:720","videoSize":"1280x720","timeLimit":1801}}
[XCUITestDriver@d3b8 (0cf65adc)] Calling AppiumDriver.startRecordingScreen() with args: [{"videoType":"libx264","videoFps":10,"videoScale":"1280:720","videoSize":"1280x720","timeLimit":1801},"0cf65adc-d8e5-41c0-baec-5ba9bbe51a5b"]
[device-farm-main] 📱 Plugin Args: {"platform":"both","iosDeviceType":"both","androidDeviceType":"both"}
[AppiumDriver@dfb2] Clearing new command timeout pre-emptively since plugin(s) will handle this command
[AppiumDriver@dfb2] Plugins which can handle cmd 'startRecordingScreen': device-farm
[AppiumDriver@dfb2] Plugin device-farm is now handling cmd 'startRecordingScreen'
[AppiumDriver@dfb2] Executing default handling behavior for command 'startRecordingScreen'
[XCUITestDriver@d3b8 (0cf65adc)] Executing command 'startRecordingScreen'
[XCUITestDriver@d3b8 (0cf65adc)] Checking if there is/was a previous screen recording. Set 'forceRestart' option to 'true' if you'd like to skip this step.
[XCUITestDriver@d3b8 (0cf65adc)] Screen recording is not running. There is nothing to stop.
[device-farm-main] Updating lastCmdExecutedAt for device 4FBCECAB-C544-4346-9551-BE2769F642AA in session 0cf65adc-d8e5-41c0-baec-5ba9bbe51a5b
[DevCon Factory] Releasing connections for 4FBCECAB-C544-4346-9551-BE2769F642AA device on 53757 port number
[DevCon Factory] No cached connections have been found
[XCUITestDriver@d3b8 (0cf65adc)] The timeLimit value must be in range [1, 1800] seconds. The value of '1801' has been passed instead.
[XCUITestDriver@d3b8 (0cf65adc)] Encountered internal error running command: Error: The timeLimit value must be in range [1, 1800] seconds. The value of '1801' has been passed instead.
[XCUITestDriver@d3b8 (0cf65adc)]     at Object.wrappedLogger.errorWithException (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/support/lib/logging.js:114:43)
[XCUITestDriver@d3b8 (0cf65adc)]     at Object.wrappedLogger.errorAndThrow (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/support/lib/logging.js:120:16)
[XCUITestDriver@d3b8 (0cf65adc)]     at XCUITestDriver.startRecordingScreen (/Users/alekseybulygin/.appium/node_modules/appium-xcuitest-driver/lib/commands/recordscreen.js:248:16)
[HTTP] <-- POST /wd/hub/session/0cf65adc-d8e5-41c0-baec-5ba9bbe51a5b/appium/start_recording_screen 500 11 ms - 706
```

**Comment by nskcashHH** [comment]
@KazuCocoa What is the reason for this restriction? Why not more?

**Comment by nskcashHH** [comment]
@KazuCocoa I tried to increase the value locally, I came across this limitation
[ffmpeg] [http @ 0x138808e00] Value 5401.000000 for parameter 'reconnect_delay_max' out of range [0 - 4294]

I was able to run without an error with a value of 4293, at least something, thank you

**Comment by nskcashHH** [comment]
@KazuCocoa thank you so much for making this fix, and will this revision be for uiautomator2 ?

**Comment by KazuCocoa** [comment]
Not possible for Android since the time comes from adb's limitation
https://github.com/appium/appium-adb/blob/01f3dbd8e2be4bd967906c24bb444651f7bcbae7/lib/tools/adb-commands.js#L1772
