### ISSUE TITLE
bug: Environment variables must be get from environment, that activate driver

### ISSUE THREAD

**Issue by aTanW** [appium/appium#20266]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently ANDROID_HOME JAVA_HOME used by driver must be set in environment, starting the server.

### Expected Behavior

When, for example, more, than one version of cvd must be used in different processes, activating driver, it is not possible to have only one copy of server

### Minimal Reproducible Example

nothing to show here

### Environment

- Operating system:
Ubuntu 22.04
- Appium server version (output of `appium --version`):
2.5.4
- Appium driver(s) and their version(s) (`appium driver list`):
✔ Listing available drivers
- uiautomator2@3.5.2 [installed (npm)]
- xcuitest [not installed]
- mac2 [not installed]
- espresso [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]

- Appium plugin(s) and their version(s) (`appium plugin list`):
✔ Listing available plugins
- images [not installed]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]

- Node.js version (output of `node --version`):
v22.2.0
- `npm` version (output of `npm --version`):
10.8.0
- Last component(s) version which did _not_ exhibit the problem: everywhere
- Platform and version under test: Android arm 13
- Real device or emulator/simulator: emu

**Comment by mykola-mokhnach** [comment]
I don't think this would be possible as drivers are loaded into the same node process that is running the server and thus shares the environment. Changing it the way where each driver runs in its own process and communicates with the server via IPC would require major architectural changes in the ecosystem.

**Comment by aTanW** [comment]
But can it be made driver running in its own "context" (guessing this is already done), that can carry driver environment, keeping all in server process? And all needed variables can be passed as driver parameters in activating call...
