### ISSUE TITLE
Appium server encounters internal error on 'shell ime enable io.appium.settings/.EmptyIME' exited with code 255'; Unknown input method io.appium.settings/.EmptyIME cannot be enabled for user #0 in real android device

### ISSUE THREAD

**Issue by DeepakSurya10** [appium/appium#20277]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm running parallel tests in android app and always in one of the 2 devices shows error as

Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/<myMachineName>/Library/Android/sdk/platform-tools/adb -P 5037 -s <deviceUdid> shell ime enable io.appium.settings/.EmptyIME' exited with code 255'; Command output: Unknown input method io.appium.settings/.EmptyIME cannot be enabled for user #0

Used devices are Samsung S23 and Fold 4. issue occurs in both devices randomly

### Expected Behavior

Appium server should be started smoothly

### Minimal Reproducible Example

Could not start a new session. Response code 500. Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/<machineName>/Library/Android/sdk/platform-tools/adb -P 5037 -s <deviceUDID> shell ime enable io.appium.settings/.EmptyIME' exited with code 255'; Command output: Unknown input method io.appium.settings/.EmptyIME cannot be enabled for user #0

### Environment

- Operating system: MacOS
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s) (`appium driver list`): uiautomator2@2.45.1 [installed (npm)]
- Appium plugin(s) and their version(s) (`appium plugin list`): -
- Node.js version (output of `node --version`): 16.13.0
- `npm` version (output of `npm --version`): 8.1.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Android 14
- Real device or emulator/simulator: Real devices - Samsung S23 and Fold 4

**Comment by mykola-mokhnach** [comment]
Please provide the full server log. Also, please use the most recent server and driver versions.

**Comment by DeepakSurya10** [comment]
[appium_logs_20_06_24_11_15_40_pm.txt](https://github.com/user-attachments/files/15928211/appium_logs_20_06_24_11_15_40_pm.txt)


Using latest version of uiautomator version 3.5.2 and appium version of 2.10.3

**Comment by mykola-mokhnach** [comment]
> 2024-06-20 23:15:41:467 [Appium] Welcome to Appium v2.4.1 (REV 4b947ec92d0195756709e5b563569cf48aef1e09)

The above log is still from the older server version.

Also, please only provide logs from the session that fails. the current output is mixed, so it is not clear what is what

**Comment by mykola-mokhnach** [comment]
Closed because of no response
