### ISSUE TITLE
Always Getting 'createSession' Error When Popup Alert Appears Before Installing WDA

### ISSUE THREAD

**Issue by fatahillahardhi** [appium/appium#20270]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I always get the following error:
`
java.lang.RuntimeException: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 408. Message: Appium did not get any response from the 'createSession' command in 30000 ms 
`

when the WebDriverAgent is trying to install and when the permission dialog is showing.

### Expected Behavior

When installing WDA, it will install normally, and the scenarios can run well.

### Minimal Reproducible Example

1. Keep the Popup Alert still showing
2. Run Appium and Run the scenario's
3. When WDA Trying to install, it will blank screen or in several cases it will also open the apps but cannot interact with the PopUp Alerts (I also using autoAcceptAlerts) and then get `createSession` errors

### Environment

- Operating system: MacOS Sonoma
- Appium server version (output of `appium --version`): 2.9.0
- Appium driver(s) and their version(s) (`appium driver list`): XCUITest 7.17.4
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`): 16.5.1
- `npm` version (output of `npm --version`): 8.11.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iPhone iOS 16 and iOS 17
- Real device or emulator/simulator: Real Devices

### Further Information

The popup alerts look like:

<img width="262" alt="Screenshot 2024-06-20 at 1 16 09 PM" src="https://github.com/appium/appium/assets/21995370/6462cc57-aa9c-4cac-86af-a875f6e0ac65">

**Comment by KazuCocoa** [comment]
Please attach the full Appium server log

**Comment by fatahillahardhi** [comment]
When I try to replicate, it shows another error (I don't know why), but still Appium cannot continue the scenarios. Maybe the `createSession` error can be replicated in the middle of the run (not in the first run)

I also give you 2 evidence when the popup alert shows before install the WDA and without popup alert

here's the log
errors/failed
- https://gist.github.com/fatahillahardhi/e88e7cf239f8cedd101c30cd2003a043
- video: https://drive.google.com/file/d/1eOIwyRDFmX7cJ_C-cYkmsml64Ev2OaUi/view?usp=sharing

success
- https://gist.github.com/fatahillahardhi/206618ae492f22db068cb6cc38dc532f
- video: https://drive.google.com/file/d/11D91aog7dvBgtsqynPxDkzHhCINI99-G/view?usp=sharing

**Comment by mykola-mokhnach** [comment]
> 3|appium bibit 3  | [XCUITestDriver@3be3]     "appium:platformVersion": "16.6",

Are you sure the platform version is set properly? Otherwise it looks similar to https://github.com/appium/appium/issues/20093

**Comment by fatahillahardhi** [comment]
Hmm, I think the platform version is set properly. If the platform version were the issue, I wouldn't be able to run it at all. However, in this https://github.com/appium/appium/issues/20270#issuecomment-2180253089, I also provided evidence that when the popup alert does not show, it runs properly. But on the contrary, it fails when the popup alert appears.

**Comment by mykola-mokhnach** [comment]
By checking the platform version we decide which approach to use in order to run preinstalled WDA. Apple changed that completely since iOS 17 and the above exception is usually shown if you try to use the old method with the new iOS.

**Comment by fatahillahardhi** [comment]
okay and then I still not get it, how to solve the problem?

**Comment by KazuCocoa** [comment]
Do you have the device log (syslog) as well? It looks like XCTest session failed to start.
```
3|appium bibit 3  | [ios-device] removing /tmp/WebDriverAgentRunner-5DF26161-6CB2-4DDC-8733-9DFF374CC506.xctestconfiguration
3|appium bibit 3  | [ios-device] Xctest for com.bibit.WebDriverAgentRunner.xctrunner on device 00008110-00165C180E9A201E has stopped!
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)] Event 'wdaStartFailed' logged at 1718874892309 (16:14:52 GMT+0700 (Western Indonesia Time))
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)] Error: TypeError: Cannot perform 'get' on a proxy that has been revoked
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)]     at InstrumentService._callChannel (/Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/instrument/index.js:159:15)
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)]     at InstrumentService.makeChannel (/Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/instrument/index.js:116:5)
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)]     at InstrumentService.callChannel (/Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/instrument/index.js:134:25)
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)]     at Xctest._launchAppRunner (/Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/xctest.js:100:9)
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)]     at Xctest.start (/Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-ios-device/lib/xctest.js:261:25)
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)]     at WebDriverAgent.launchWithPreinstalledWDA (/Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/lib/webdriveragent.js:402:9)
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)]     at WebDriverAgent.launch (/Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/lib/webdriveragent.js:462:14)
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)]     at /Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:825:34
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)]     at wrapped (/Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:93:13)
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)]     at retry (/Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:66:13)
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)]     at retryInterval (/Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/node_modules/asyncbox/lib/asyncbox.js:103:10)
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)]     at /Users/devicefarm/.appium/node_modules/appium-xcuitest-driver/lib/driver.js:815:7
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)] The executable name for the bundle id 'com.bibit.WebDriverAgentRunner.xctrunner' was 'WebDriverAgentRunner-Runner'
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)] Failed to kill 'com.bibit.WebDriverAgentRunner.xctrunner'. Original error: Error: reply channel data timeout
3|appium bibit 3  | [XCUITestDriver@3be3 (ef677587)] {}
3|appium bibit 3  | [DevCon Factory] Releasing connections for 00008110-00165C180E9A201E device on any port number
3|appium bibit 3  | [DevCon Factory] Found cached connections to release: ["00008110-00165C180E9A201E:8391"]
3|appium bibit 3  | [DevCon Factory] Releasing the listener for '00008110-00165C180E9A201E:8391'
```

**Comment by mykola-mokhnach** [comment]
> okay and then I still don't get it, how to solve the problem?

Try to disable/exclude usePreinstalledWDA capability for iOS 16 or only use it with iOS 17+

**Comment by fatahillahardhi** [comment]
After I tried the same conditions also with prebuilt WDA on iOS 16 (I tried removing Frameworks/XC* on WDA for iOS 16), the results are as follows:

iOS 16:
- So far, I have tried it on iOS 16. When the Pop-Up Alert appears before installing WDA, it runs well.

iOS 17:
- However, on iOS 17, it fails in the first scenario, and the pop-up disappears after installing WDA (the error is "socket hang up"). In the second scenario, it runs well.
- Gist: https://gist.github.com/fatahillahardhi/4497d266fc8984e5f9d421e17ce78305
- Video: https://drive.google.com/file/d/170BlMq8xjb7QkfLZYARWOGlui7eTEqPF/view?usp=sharing (the video stops after showing the failure)

Hmm, why does it result in a socket hang-up in the first scenario on iOS 17, while it runs well from the first scenario on iOS 16?

**Comment by mykola-mokhnach** [comment]
In the failed logs I can observe that everything worked the way it was supposed to work:

> 3|appium bibit 3  | [XCUITestDriver@f2ef (cbcdf78b)] Executing xcrun devicectl device process launch --device 00008030-001419043428C02E --terminate-existing --environment-variables '{"USE_PORT":"8351","WDA_PRODUCT_BUNDLE_IDENTIFIER":"com.bibit123.WebDriverAgentRunner.xctrunner","MJPEG_SERVER_PORT":"9101"}' com.bibit123.WebDriverAgentRunner.xctrunner

It's just that WDA itself did never listen on the expected port. The answer to why it happened might be found in the device log

**Comment by fatahillahardhi** [comment]
can you tell where is the path for device log?

**Comment by KazuCocoa** [comment]
`appium:showIOSLog` capability might help (if you don't know how to get them). Then, the appium server log will be huge, please using GIST or attach a test file

**Comment by fatahillahardhi** [comment]
oh wow, yes that's very huge 😅

here's the gist:
https://gist.github.com/fatahillahardhi/4da68b3cc9ad398d5c20731f75f533f2

**Comment by fatahillahardhi** [comment]
Ahh I see, okay thanks for the response @KazuCocoa @mykola-mokhnach 🙌🏻

**Comment by candialala** [comment]
Is there any way to fix it? I also encountered this problem. If there is a system alert, has been unable to create a session when usePreinstalledWDA = true. 
If I use xcodebuild to launch, pop-up system alert can also be created normally. @KazuCocoa @mykola-mokhnach
