### ISSUE TITLE
bug: Standard caps value validation should have done in the base driver

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#20273]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Standard caps such as `pageLoadStrategy` is not handled as:

```
[XCUITestDriver@b618] The following provided capabilities were not recognized by this driver:
[XCUITestDriver@b618]   pageLoadStrategy
[XCUITestDriver@b618] The desired capabilities include neither an app nor a bundleId. WebDriverAgent will be started without the default app
[XCUITestDriver@b618] Session created with session id: 609c241a-fcf6-44a6-be40-c5eff0cde7fe
```

https://github.com/appium/appium-xcuitest-driver/pull/2411#discussion_r1646997536

### Expected Behavior

Maybe base driver should handle validation for all standard caps by default without each driver's own config such as https://github.com/appium/appium-xcuitest-driver/pull/2411

### Minimal Reproducible Example

Without https://github.com/appium/appium-xcuitest-driver/pull/2411 change, and with `pageLoadStrategy` caps

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by saikrishna321** [comment]
Fixed and released in version  7.18.0 appium-xcuitest-driver
