### ISSUE TITLE
Android: Elements disappear in DOM after multiple swipe down in a long screen

### ISSUE THREAD

**Issue by stefanthr** [appium/appium#20281]
OS: ANDROID

Appium version : 2.5.1
Mobile platform/version under test: Android 13
Real device or emulator/simulator: Real device accessed via Webmate

Hi, guys. I have noticed a strange behaviour of Appium on my Galaxy S22 Android Device which I use via Webmate. When I open the dashboard of my app (see first screenshot), Appium finds all visible elements and displays them in DOM. When I scroll down  more than two times because the screen is long, all elements disappear and I see just the WebView (see second screenshot). When I scroll up again to the beginning, the elements appear. I need to scroll down down to the bottom to access the last elements. The behaviour occurs only on Android. I tried clicking somewhere random on the page as a workaround, but they do not load. On Ios all elements are loaded from the beginning, so I don't even have to scroll down to get one. I would appreciate any help :) 

![image](https://github.com/appium/appium/assets/83087927/415fcb6f-ed83-41c3-89cc-3d5b80d0e237)
![image](https://github.com/appium/appium/assets/83087927/b77fc52d-131e-4e8d-a4e3-c8314be9052f)

**Comment by mykola-mokhnach** [comment]
I assume the described behaviour has nothing to do with UIA2 driver. It works as expected. It is the app or Android accessibility itself that recycles invisible elements. Although you may also try to play with ignoreUnimportantViews and/or allowInvisibleElements [settings](https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#settings-api) to see how they influence the displayed data. Check https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#elements-cannot-be-found for more details

**Comment by stefanthr** [comment]
Allowing invisible elements solved my issue. Thanks @mykola-mokhnach!
