### ISSUE TITLE
bug: Unable to connect Simulator with Appium Inspector

### ISSUE THREAD

**Issue by dksoni812** [appium/appium#20289]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using below capabilities
`{
  "platformName": "iOS",
  "appium:deviceName": "iPhone 15 Pro",
  "appium:platformVersion": "17.5",
  "appium:app": "/Users/dhrumilsoni/Documents/wdio-appium-v8/app/ios/UIKitCatalog.app",
  "appium:automationName": "XCUITest"
}`

I am getting below error while starting session from the Appium Inspector.

`Failed to create session. An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message:`

### Expected Behavior

It should connect to the simulator successfully.

### Minimal Reproducible Example

Failed to create session. An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 xcodebuild error message:

### Environment

- Operating system: 14.5 (23F79)
- Appium server version (output of `appium --version`): 2.10.3
- Appium driver(s) and their version(s) (`appium driver list`): ✔ Listing available drivers
       - xcuitest@4.21.12 [installed (npm)]
       - uiautomator2@2.14.0 [installed (npm)]
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`): 18.15.0
- `npm` version (output of `npm --version`): 9.5.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator: Simulator iPhone 15 Pro

### Further Information

<img width="1715" alt="Screenshot 2024-06-24 at 12 28 48 PM" src="https://github.com/appium/appium/assets/129929508/2348b537-817e-4c66-9d25-c0765d434f06">

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by mykola-mokhnach** [comment]
> - xcuitest@4.21.12 [installed (npm)]

Also it seems your driver is out of date. Please upgrade to the most recent version of it

**Comment by dksoni812** [comment]
Thanks, @mykola-mokhnach 
I'm able to connect my simulator with Appium Inspector by upgrading xcuitest to latest version.
✔ Updating driver 'xcuitest' from 4.21.12 to 4.35.0
ℹ Update report:
✔   - driver xcuitest updated: 4.21.12 => 4.35.0

And, it works. Thanks for your quick input. I am closing this ticket.

**Comment by mykola-mokhnach** [comment]
Please note that the above one is not the latest driver version. You could check the output of `npm info appium-xcuitest-driver` or check https://github.com/appium/appium-xcuitest-driver/releases to know what the most recent driver version is.

**Comment by dksoni812** [comment]
@mykola-mokhnach 
In the project, when I'm installing the xcuitest driver

**npx appium driver install xcuitest**

`✔ Checking if 'appium-xcuitest-driver' is compatible
✔ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver'
ℹ Driver xcuitest@7.18.0 successfully installed
- automationName: XCUITest
- platformNames: ["iOS","tvOS"]`

but when I installed the xcuitest driver through the command line in my system

`dhrumilsoni@Dhrumil-Soni-TH ~ % appium driver list --installed 
✔ Listing installed drivers
- xcuitest@4.35.0 [installed (npm)]
- uiautomator2@2.14.0 [installed (npm)]`

**Comment by mykola-mokhnach** [comment]
Try to uninstall it completely and then perform a new install

**Comment by dksoni812** [comment]
<img width="547" alt="image" src="https://github.com/appium/appium/assets/129929508/4e12f221-ffdc-4e8c-bde2-6ca598ce373a">

Thanks, @mykola-mokhnach

**Comment by dksoni812** [comment]
Similarly, I've updated "uiautomator2" to the latest one. Now all are in sync with the latest versions.
