### ISSUE TITLE
bug: Identified session is not known

### ISSUE THREAD

**Issue by lcsmobileqa** [appium/appium#20291]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This was working Friday (6/21/2024) no changes made (is a work machine so no changes that I'm aware of) yet this morning, I started getting errors when running the same tests. The session identified by <ID> is now known. The screenshot shows the session ID  is different than the one being used by the test execution, I'm not sure if this has always been the case, or if not, why it would change.

![image](https://github.com/appium/appium/assets/74318070/235d3142-2be1-4965-9690-500ddf1d00b1)

Troubleshooting actions taken today:

NPM Update to Appium, 

NPM update to @WDIO appium-services, 

re-installed appium-uiautomator2-driver

Re-set APPIUM_HOME in system environment variables

Same results, no change.

### Expected Behavior

The test should run as it did 3 days ago.

### Minimal Reproducible Example

https://gist.github.com/lcsmobileqa/e5cb9512f35a2edbf8b9d307bdae6762

### Environment

- Operating system: Windows
- Appium server version (output of `appium --version`): 2.10.3
- Appium driver(s) and their version(s) (`appium driver list`): appium_uiautomator2 v 3.1.0
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`): 20.11.1
- `npm` version (output of `npm --version`): 10.2.4
- Last component(s) version which did _not_ exhibit the problem: appium-service 8.36.1, Appium 2.5.4
- Platform and version under test: Android 14
- Real device or emulator/simulator: Real device Samsung S21 5G

### Link to Appium Logs

https://gist.github.com/lcsmobileqa/e5cb9512f35a2edbf8b9d307bdae6762

### Further Information

I installed OpenSDK 8 today at the request of our IT department. There is an attempt to free up Java licenses.

**Comment by KazuCocoa** [comment]
Please attach the full appium server side log, not webdriverio log.

**Comment by mykola-mokhnach** [comment]
I can observe socket hangup errors in the above client log. Check https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#socket-hangup-error

**Comment by lcsmobileqa** [comment]
Thank you both! I hadn't run into the socket error issue before so it didn't stand out to me. Now that that's all fixed up, it's running perfectly again. I'll go ahead and close this ticket. I appreciate your time and knowledge!
