### ISSUE TITLE
bug: wdaRemotePort is initialized with wdaLocalPort value in WebDriverAgent

### ISSUE THREAD

**Issue by oleg-digital-ai** [appium/appium#20300]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

According to documentation wdaRemotePort can be configured:
https://appium.github.io/appium-xcuitest-driver/5.14/reference/capabilities/

However, in WebDriverAgent code, the wdaRemotePort value is assigned to wdaLocalPort value, which seems incorrect.
this.wdaLocalPort = args.wdaLocalPort;
this.wdaRemotePort = args.wdaLocalPort || WDA_AGENT_PORT;

https://github.com/appium/WebDriverAgent/blob/master/lib/webdriveragent.js

### Expected Behavior

It should be possible to configure wdaRemotePort to value different from wdaLocalPort.

### Minimal Reproducible Example

appium --driver-xcuitest-webdriveragent-port 8120

This command should change wdaLocalPort only and wdaRemotePort should be 8100 (default value)

### Environment

- Operating system: Mac OS
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
The patch has been merged
