### ISSUE TITLE
bug: It's taking more than 5 minutes to create a session in Appium 2 for iOS Native App in MacOS. In Appium 1, it used to be created in 30 seconds.

### ISSUE THREAD

**Issue by JYOTIPRAKASH225** [appium/appium#20317]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Appium 2 session creation process for an iOS native app on MacOS is taking longer than five minutes. It used to create in 30 seconds in Appium 1.
It also malfunctions occasionally. 
The test suites are quite sloppy as a result.

### Expected Behavior

Every time, a session should be created in less than 30 seconds.

### Minimal Reproducible Example

`	public AppiumDriver getDriver(String SuiteName) throws Exception {
		try {
			System.out.println("at : AppiumDriver : " + port);
			try {
				service = AppiumDriverLocalService.buildService(
						new AppiumServiceBuilder().usingPort(port).withArgument(GeneralServerFlag.LOG_LEVEL, "debug")
								.withLogFile(new File(System.getProperty("user.dir") + "appium.log"))
								.withArgument(GeneralServerFlag.RELAXED_SECURITY));
			} catch (Exception e) {
				System.out.println("service is not launching...");
				System.out.println(e);
				System.exit(1);
			}
			DesiredCapabilities capabilities = new DesiredCapabilities();
			capabilities.setCapability("app", AppIDs.launcher);
			capabilities.setCapability("deviceName", InitializeSetup.properties.get("model"));
			capabilities.setCapability("udid", InitializeSetup.properties.get("udid"));
			capabilities.setCapability("platformVersion", InitializeSetup.properties.get("deviceOS"));
			capabilities.setCapability("platformName", InitializeSetup.properties.get("deviceType"));
			capabilities.setCapability("wdaLocalPort", devicePort);
			capabilities.setCapability("wdaConnectionTimeout", 600000);
			capabilities.setCapability("clearSystemFiles", true);
			capabilities.setCapability("sendKeyStrategy", "grouped");
			capabilities.setCapability("maxTypingFrequency", 300);
			capabilities.setCapability("commandTimeouts", "360000");
			capabilities.setCapability("includeSafariInWebviews", true);
			capabilities.setCapability("connectHardwareKeyboard", false);
			capabilities.setCapability("interKeyDelay", 10);
			capabilities.setCapability("automationName", "XCUITest");

			driver = new IOSDriver(service, capabilities);
			new WebDriverWait(driver, Duration.ofSeconds(6));
		}
		catch (Exception e) {
			System.out.println();
			e.printStackTrace();
			Logger.log("Error in creating appium instance");
			System.exit(0);
		}
		return driver;
	}

`

### Environment

- Operating system: Mac OS
- Appium server version (output of `appium --version`): 2.4.1
- Appium driver(s) and their version(s) (`appium driver list`): xcuitest@5.16.1
- Appium plugin(s) and their version(s) (`appium plugin list`): 
- Node.js version (output of `node --version`):  v21.7.1
- `npm` version (output of `npm --version`): 10.5.2
- Last component(s) version which did _not_ exhibit the problem: Appium 1.22.3
- Platform and version under test: iOS
- Real device or emulator/simulator: Real Device

### Link to Appium Logs

https://gist.github.com/JYOTIPRAKASH225/76c14b96745eab0978c2198b0447f4d9

**Comment by mykola-mokhnach** [comment]
- Please use the most recent driver version
- It might be your machine is too slow to compile WDA sources. You may try to optimise the flow by precompiling/preinstalling WDA as it is described in https://github.com/appium/appium-xcuitest-driver/blob/master/docs/guides/run-preinstalled-wda.md and https://github.com/appium/appium-xcuitest-driver/blob/master/docs/guides/run-prebuilt-wda.md

**Comment by KazuCocoa** [comment]
Yea, it looks like the xcodebuild didn't complete in the timeout. I guess that was because the version was a fresh xcodebuild target for your env.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
