### ISSUE TITLE
When I jump from one webview page to another, appium sometimes cannot find the element

### ISSUE THREAD

**Issue by gouxiangfei** [appium/appium#20311]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 the first time I open it, appium only finds the element named <android.webkit.WebView>
appium found other elements when i open second time
It has an 80% chance of appearing, which prevents me from performing automated testing on my Android app.

### Expected Behavior

Is this a bug and how can I avoid it?

### Minimal Reproducible Example

If you could give me some help, I would be very grateful

### Environment

gxf@rakumadeMac-mini0934 ~ % appium --version
2.9.0
gxf@rakumadeMac-mini0934 ~ % appium driver list
✔ Listing available drivers
- uiautomator2@2.29.2 [installed (npm)]
- xcuitest@4.32.21 [installed (npm)]
- espresso [not installed]
- mac2 [not installed]
- windows [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]
gxf@rakumadeMac-mini0934 ~ % appium plugin list
✔ Listing available plugins
- images [not installed]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]
gxf@rakumadeMac-mini0934 ~ % node --version
v21.7.3
gxf@rakumadeMac-mini0934 ~ % npm --version
10.2.5
android.system.webview 126.0.6478.133
android.chrome.app 126.0.6478.122

**Comment by mykola-mokhnach** [comment]
You may try https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#elements-cannot-be-found

Otherwise I'm afraid we cannot help much as elements lookup is controlled by UiAutomator framework itself.

**Comment by KazuCocoa** [comment]
You could also try out WEBVIEW context.
https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#hybrid-mode

**Comment by gouxiangfei** [comment]
> context

Sorry, I encountered this problem when I tried to use WebView context(https://github.com/appium/appium/issues/20107),and my client wanted me to use Native Context for testing

**Comment by gouxiangfei** [comment]
> You could also try out WEBVIEW context. https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#hybrid-mode
Sorry, I encountered this problem when I tried to use WebView context(https://github.com/appium/appium/issues/20107) and my client wanted me to use Native Context for testing

**Comment by KazuCocoa** [comment]
I see, then what Appium could offer is only previous Mykola's comment since the result of page source depends on [AccessibilityNodeInfo](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo), which is not controllable in Appium layer.

**Comment by KazuCocoa** [comment]
I don't have any answer, but for example, https://stackoverflow.com/questions/31685514/talkback-accessibility-in-webview could be related to make WebView contents accessible in NATIVE_APP context. It is talkback-related in WebView. They might be similar in terms of making contents in WebView accessible via accessibility functionality.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue

**Comment by SongQA** [comment]
@mykola-mokhnach
I'm experiencing the same issue as this issue, how do I solve this issue?

**Comment by SongQA** [comment]
I solved the problem with this. `appium:settings[allowInvisibleElements]`

**Comment by gouxiangfei** [comment]
> I solved the problem with this. `appium:settings[allowInvisibleElements]`

Sorry this configuration doesn't work for me, I would be very grateful if I could see your code configuration
![image](https://github.com/user-attachments/assets/0b6e05d5-18c5-4035-b519-b65802020016)
![image](https://github.com/user-attachments/assets/991ba28e-abcf-4bf4-b9bd-9c78bc84a81d)

**Comment by SongQA** [comment]
{
  "platformName": "Android",
  "appium:platformVersion": "14.0",
  "appium:deviceName": "Pixel 8 Pro API 34",
  "appium:automationName": "UiAutomator2",
  "appium:udid": "emulator-5554",
  "appium:settings[allowInvisibleElements]": true
}
cc. @gouxiangfei

**Comment by gouxiangfei** [comment]
Sorry, this method didn't work for me. I found a description of this issue on the Chromium official website, you can track it if you are interested
https://issues.chromium.org/issues/42323621
@SongQA
