### ISSUE TITLE
Appium inspector/ XCUITestDriver can't "see" a WebElement (cell from a table) which is horizontally out of the UI view of the screen

### ISSUE THREAD

**Issue by RSV7** [appium/appium#20326]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium inspector/XCUITestDriver (while run time) doesn’t see one element in the view controller (analog DOM) on iOS? 
My context:
- We're running on Sauce labs with: Appium v2.11.1 creating new XCUITestDriver (v7.21.1). Appium's BaseDriver version is 9.11.1. XCUITestDriver's BaseDriver version is 9.11.1
- iOS 17.4.1/ iPhone 13
- Screen with table of 7 columns(!), screenshot is below
![Screenshot 2024-07-01 at 10 10 07](https://github.com/appium/appium/assets/23527348/8f016d8a-ea24-4c6c-9fb0-f3e1795b5cee)

On the screen, currently 3 columns are visible from the UI part. Evaluating by inspector -> 6th is in the DOM but 7th cell is not, why?
I mean 6th cell is also out of the screen -> but inspector sees it. Why is 7th not visible and does not exist in the elements structure (DOM/view controller)?

Additional information:
- If scroll table to 7th cell -> inspector/driver can see it
- Tried to fetch page source of the current screen, with:
`private String getIOSPageSource() {
        Map<String, Object> params = new HashMap<>();
        params.put("format", "description");
        return (String) ((JavascriptExecutor) driver).executeScript("mobile: source", params);
    }`
  
Result is here: 
[page source without cell_1_7.pdf](https://github.com/user-attachments/files/16085742/page.source.without.cell_1_7.pdf)
- information from developers about this screen implementation: 
[UICollectionView](https://developer.apple.com/documentation/uikit/uicollectionview). And UIKid

### Expected Behavior

Appium inspector/XCUITestDriver (while run time) "see" the cell_1_7 element in the view controller (analog DOM) on iOS.
Moreover, all elements should be visible while page source 

### Minimal Reproducible Example

All details are in the description. I'm afraid for real reproduction I have to provide an access to the app. This can be done by private contact. Please let me know if that possible?

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
Could I confirm that the number of `Column name` could be the identification to check the 6th cell, 7th cell.... ?

e.g.
`StaticText, 0x10f3a9880, {{71.0, 205.7}, {110.0, 65.0}}, label: 'Column name'`

Then, the attached page source with `description` had 6, so actually Appium/WDA got only 6 items from the system (via XCTest framework by iOS/Apple).

It could depend on app implementation and how OS parses them. For example, let's consider a view has a list. The list implementation has multiple ways like grid, collection and list view. (sorry I forget exact class names.) Based on my past experience, some implementation shows up available items at once while they were not in the view, but some implementation loads content incrementally so you may need to scroll etc to get elements outside view.

So, in your case, it looks like how OS parses the elements dependent stuff.

**Comment by RSV7** [comment]
@KazuCocoa 
>>Could I confirm that the number of Column name could be the identification to check the 6th cell, 7th cell.... ?
Not really. We use `label` attribute to identify each cell `label == "cell_1_1", label == "cell_1_2" etc...` (where 1 - is row number, and e.g. 2 - is column)

Based on your explanation you don't see an issue from appium/wda, correct?

It's actually closer to what iOS devs explained. Based on UICollectionView implementation from UIKid it's kinda "dynamic" (if I can say that) loading happens. And for some of cells to be loaded/visible for wda, scroll is required. 

Though for me still unclear part, what exact logic of loading cells in this case?! (because as explained initially 6th is visible but 7th is not, in time when both are out of the screen) And devs answer: we can't say exactly

Ok, looks that scroll in my case is only a way to go (to get 7th cell).

If you don't see Appium/XCUITest can do something, please close the issue.

Thank you for assistance

**Comment by KazuCocoa** [comment]
> Though for me still unclear part, what exact logic of loading cells in this case?!

Only Apple internal person could answer for it.

When I had implement of paginations of probably a collection view before, it called a web api to get the next page when XCTest framework got a snapshot (driver.page_source in Appium) while it was out of screen. Usually such web api call should have called only when a user scroll down the view. That was mysterious behavior but it occurred actually.
This is one example about unclear behavior but actually occurred and XCTest framework or accessibility related that Appium/WDA depends on.
