### ISSUE TITLE
UserName, Password etc Login elements are not identifiable on iOS version 16 and 17 version

### ISSUE THREAD

**Issue by Shubha-09** [appium/appium#20332]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

UserName, password, etc Login elements are not identifiable on iOS version 16 and 17. It works on os 15 version.And if we navigate manually, the elements are identifiable. Only on automation; it's not working

![image](https://github.com/appium/appium/assets/174758648/ee0afd94-ebf4-4759-829b-9ce303497b4f)

### Expected Behavior

It should identify the elements 

### Minimal Reproducible Example

Launch the app

### Environment

- Operating system: Mac
- Appium server version (output of `appium --version`): Appium 2.10.3
- Appium driver(s) and their version(s) (`appium driver list`):  xcuitest@7.18.0
- Appium plugin(s) and their version(s) (`appium plugin list`): No 
- Node.js version (output of `node --version`): Node V20.15.0
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS 
- Real device or emulator/simulator: real device

**Comment by mykola-mokhnach** [comment]
The source tree is built by xctest itself. We cannot influence this process.
