### ISSUE TITLE
bug: Installing Windows driver installs the latest (broken) dev version of WinAppDriver

### ISSUE THREAD

**Issue by omghb** [appium/appium#20336]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Installing the Windows driver:
`appium driver install --source=npm appium-windows-driver`

will install the WinAppDriver as well. Unfortunately, it installs the very latest dev version which is broken.

### Expected Behavior

Please, install the latest released version 1.2.1 of WinAppDriver instead.

This is mentioned in the Microsoft Blog too:
- https://devblogs.microsoft.com/dotnet/dotnet-maui-ui-testing-appium/

### Minimal Reproducible Example

-

### Environment

-

**Comment by bmajkut** [comment]
I found the problem.

I had to install WInAppDriver 1.2.1 and application started to work.

**Comment by mykola-mokhnach** [comment]
For me it does not make much sense to revert the WAD version as all of have not been not maintained for years by Microsoft.
We had an idea to replace WAD with a compatible open-source module, like for example https://github.com/FlaUI/FlaUI.WebDriver. Although we don't observe much engagement there from anyone regarding further compatibility maintenance and features development.

**Comment by omghb** [comment]
It's true that WAD was not maintained since years. This topic was brought up in a recent MS blog discussion (2024, June). Here is the answer of Gerald Versluis (Microsoft, MAUI):
- https://devblogs.microsoft.com/dotnet/dotnet-maui-ui-testing-appium/#comment-20891

But it would be better to reference the last stable release 1.2.1 and not the very last "broken" development release in `appium-windows-driver`.

**Comment by Aubbles01** [comment]
@omghb - how did you install the correct version of WAD and make sure Appium was using it?  Did you still use the "appium driver install --source=npm appium-windows-driver" command and then install the WAD 1.2.1 version after?  

We're trying to use Appium with our new MAUI app (so it's using WinUI) and Appium doesn't seem to be able to see a majority of the elements.  Wondering if this issue is our problem.

**Comment by mykola-mokhnach** [comment]
We've decided to change the logic there and since driver version 3.0.0 the server part does not get deployed automatically, but the client might decide on their own which version to install. See https://github.com/appium/appium-windows-driver/pull/277
