### ISSUE TITLE
bug: Why does the driver.page_source method only get the app layout on Android 12, but not the layout of the status bar and navigation bar? The device is in landscape mode, and the navigation bar is on the right.

### ISSUE THREAD

**Issue by dkzdiker** [appium/appium#20341]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Why does the driver.page_source method only get the app layout on Android 12, but not the layout of the status bar and navigation bar? The device is in landscape mode, and the navigation bar is on the right.

### Expected Behavior

Why does the driver.page_source method only get the app layout on Android 12, but not the layout of the status bar and navigation bar? The device is in landscape mode, and the navigation bar is on the right.

### Minimal Reproducible Example

Why does the driver.page_source method only get the app layout on Android 12, but not the layout of the status bar and navigation bar? The device is in landscape mode, and the navigation bar is on the right.

### Environment

- Operating system:win10 64
- Appium server version (output of `appium --version`):appium-python-client:4.0.0
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

Why does the driver.page_source method only get the app layout on Android 12, but not the layout of the status bar and navigation bar? The device is in landscape mode, and the navigation bar is on the right.

**Comment by eglitise** [comment]
Please provide more information: your Appium server version, your UiAutomator2 driver version, screenshots, page sources, etc.

**Comment by mykola-mokhnach** [comment]
Please check https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#elements-cannot-be-found
