### ISSUE TITLE
Scroll Element Into View : NotImplementedError: Method is not implemented

### ISSUE THREAD

**Issue by revathikanakachalam** [appium/appium#20358]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appium Version: 2.11.1
xcuitest : 7.23.0
iOS device: iPhone 14 plus
iOS version: 17.4.1
App type: Native App
RF version: 6.1.1

I am new to iOS automation. I am automating native iOS app using appium with robotframework. When I try to scroll the page using "Scroll Element Into View" appium is throwing error as "Encountered internal error running command: NotImplementedError: Method is not implemented"

### Expected Behavior

Code:
Scroll Element Into View    accessibility_id=device_listview_deviceListCell_13

Expected behaviour: Scroll to the element

### Minimal Reproducible Example

Code:
Scroll Element Into View    accessibility_id=device_listview_deviceListCell_13

### Environment

- Operating system: **MacBook Pro**
- Appium server version (output of `appium --version`): **2.11.1**
- Appium driver(s) and their version(s) (`appium driver list`): 
**$appium driver list
✔ Listing available drivers
- xcuitest@7.23.0 [installed (npm)]
- uiautomator2@3.7.1 [installed (npm)]
- chromium@1.3.27 [installed (npm)]
- espresso [not installed]
- mac2 [not installed]
- windows [not installed]
- safari [not installed]
- gecko [not installed]**
- Appium plugin(s) and their version(s) (`appium plugin list`): 
**- ✔ Listing available plugins
- images [not installed]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]**
- Node.js version (output of `node --version`): **v22.2.0**
- `npm` version (output of `npm --version`): **10.7.0**
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: 
**iOS device: iPhone 14 plus
iOS version: 17.4.1
App type: Native App
RF version: 6.1.1**
- Real device or emulator/simulator: **Real device**

### Link to Appium Logs

https://gist.github.com/revathikanakachalam/965036e2b3114d38ba362d93e3fe65df

**Comment by mykola-mokhnach** [comment]
> [a9c2d7e2][XCUITestDriver@9578 (a9c2d7e2)] Calling AppiumDriver.execute() with args: ["arguments[0].scrollIntoView()",[{"element-6066-11e4-a52e-4f735466cecf":"31000000-0000-0000-6C12-000000000000"}],"a9c2d7e2-e8ec-4a1d-8c47-0ca5aa7390a1"]


The error is expected. This API is only supposed to work in web view mode and is not supported in native context.

**Comment by revathikanakachalam** [comment]
@mykola-mokhnach  
Is it the same case for Scroll Down and Scroll Up commands in iOS? I am receiving the below error for these keywords

```
[dd5becdb][HTTP] --> POST /session/dd5becdb-9772-4d46-bc19-dab1438ca8c7/execute/sync {"script":"mobile: scroll","args":[{"direction":"down","elementid":"31000000-0000-0000-6C12-000000000000"}]}
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)] Calling AppiumDriver.execute() with args: ["mobile: scroll",[{"direction":"down","elementid":"31000000-0000-0000-6C12-000000000000"}],"dd5becdb-9772-4d46-bc19-dab1438ca8c7"]
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)] Executing command 'execute'
[dd5becdb][BaseDriver] The following script arguments are not known and will be ignored: elementid
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)] Proxying to WDA with an unknown route: POST /wda/scroll
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)] Proxying [POST /wda/scroll] to [POST http://127.0.0.1:8100/session/8785E91A-4512-4AA5-B5ED-E7D7DB075CE3/wda/scroll] with body: {"direction":"down"}
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)] Got response with status 404: {"value":{"error":"unknown command","message":"Unhandled endpoint: /session/8785E91A-4512-4AA5-B5ED-E7D7DB075CE3/wda/scroll -- http://127.0.0.1:8100/ with parameters {\n    wildcards =     (\n        \"session/8785E91A-4512-4AA5-B5ED-E7D7DB075CE3/wda/scroll\"\n    );\n}","traceback":""},"sessionId":"8785E91A-4512-4AA5-B5ED-E7D7DB075CE3"}
[dd5becdb][W3C] Matched W3C error code 'unknown command' to UnknownCommandError
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)] Encountered internal error running command: UnknownCommandError: Unhandled endpoint: /session/8785E91A-4512-4AA5-B5ED-E7D7DB075CE3/wda/scroll -- http://127.0.0.1:8100/ with parameters {
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)]     wildcards =     (
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)]         "session/8785E91A-4512-4AA5-B5ED-E7D7DB075CE3/wda/scroll"
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)]     );
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)] }
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)]     at errorFromW3CJsonCode (/Users/revathikanakachalam/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)]     at ProxyRequestError.getActualError (/Users/revathikanakachalam/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)]     at JWProxy.command (/Users/revathikanakachalam/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:353:19)
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)]     at XCUITestDriver.proxyCommand (/Users/revathikanakachalam/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)]     at XCUITestDriver.mobileScroll (/Users/revathikanakachalam/.appium/node_modules/appium-xcuitest-driver/lib/commands/gesture.js:233:12)
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)]     at XCUITestDriver.executeMethod (/Users/revathikanakachalam/node_modules/@appium/base-driver/lib/basedriver/commands/execute.ts:36:12)
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)]     at XCUITestDriver.execute (/Users/revathikanakachalam/.appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:118:14)
[dd5becdb][HTTP] <-- POST /session/dd5becdb-9772-4d46-bc19-dab1438ca8c7/execute/sync 404 23 ms - 1674 
[dd5becdb][HTTP] --> GET /session/dd5becdb-9772-4d46-bc19-dab1438ca8c7/screenshot {}
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)] Calling AppiumDriver.getScreenshot() with args: ["dd5becdb-9772-4d46-bc19-dab1438ca8c7"]
[dd5becdb][XCUITestDriver@b7ea (dd5becdb)] Executing command 'getScreenshot'
```

**Comment by mykola-mokhnach** [comment]
No, it's not the same. 

> [dd5becdb][XCUITestDriver@b7ea (dd5becdb)] Encountered internal error running command: UnknownCommandError: Unhandled endpoint: /session/8785E91A-4512-4AA5-B5ED-E7D7DB075CE3/wda/scroll -- http://127.0.0.1:8100/ with parameters {


This most likely means your driver and server versions don't match. You must make sure the WebDriverAgent running on the device is not cached from previous driver versions.

**Comment by revathikanakachalam** [comment]
@mykola-mokhnach Thanks for your response.
How to clear cache of WebDriverAgent in iOS device? Deleting the WebDriverAgent is not helping.
Request your inputs
