### ISSUE TITLE
Not able to click with JavascriptExecutor on mobile web (chrome) after switching to appium 2.6.0

### ISSUE THREAD

**Issue by ramit1mg** [appium/appium#20356]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We were earlier using appium 1.22.3 for mobile web automation and operations with JavascriptExecutor used to work fine.
Recently we have switched to appium version 2.6.0 for mobile web automation (chrome) and while using below code, we are getting error :

JavascriptExecutor jsExecutor = (JavascriptExecutor) DriverManager.getDriver();
jsExecutor.executeScript(“arguments[0].click();”, element);

Error : arguments[0].click is not a function

Note : With driver.click() method, we are sometimes facing error like element not clickable at point (x,y) hence we decided to use JavascriptExecutor

### Expected Behavior

Ideally the element should be clickable with js executor as well.

### Minimal Reproducible Example

Provided above.

### Environment

- Operating system: Apple M3 Pro MacOS 14.5
- Appium server version (output of `appium --version`): 2.6.0
- Appium driver(s) and their version(s) (`appium driver list`):  uiautomator2@3.7.1 [installed (npm)] , xcuitest@7.23.0 [installed (npm)]
- Appium plugin(s) and their version(s) (`appium plugin list`): execute-driver@3.0.31 [installed (npm)]
- Node.js version (output of `node --version`): v22.3.0
- `npm` version (output of `npm --version`): 10.8.1
- Last component(s) version which did _not_ exhibit the problem: 1.22.3
- Platform and version under test:
- Real device or emulator/simulator: Emulator

**Comment by KazuCocoa** [comment]
Please attach the full appium server log. It looks like the behavior depends on chromedriver version.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
