### ISSUE TITLE
Cannot install APK despite enabling capability to do so

### ISSUE THREAD

**Issue by tking16** [appium/appium#20389]
Running `install_app(self.capabilities['app'])` gives me the classic error 
```
Failure [INSTALL_FAILED_TEST_ONLY: Failed to install test-only apk. Did you forget to add -t?]
```
But this is supposed to be resolved with Appium 2, I have as one of my capabilites: `"allowTestPackages": "true"`. Appreciate the help.

Appium v2.10.3
uiautomator2@3.5.2
Using a Physical device

**Comment by mykola-mokhnach** [comment]
Please provide the full server log

**Comment by tking16** [comment]
[appiumAdbLogs.log](https://github.com/user-attachments/files/16265340/appiumAdbLogs.log)

**Comment by mykola-mokhnach** [comment]
this behaviour is expected. The capability value is only applied to the app installed from capabilities. The `installApp` API above has its own set of capabilities: https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-installapp

**Comment by tking16** [comment]
Oh I see. Thank you that's sorted it it seems
