### ISSUE TITLE
bug: Unable to change the window size with Java and Selenium 4

### ISSUE THREAD

**Issue by lucasandre22** [appium/appium#20390]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to change the window size in Java by using Selenium 4 and appium-windows-driver (not 100% sure that it applies to any other driver) I get an error saying that parameters x and y needs to be sent.

I am trying to change the window size executing the following Java code:
`driver = new WindowsDriver(new URL(windowsDriverUrl), caps);  
driver.manage().window().setSize(new Dimension(1000, 1000));`

Appium receives it and displays the following error, which says that it is expecting parameters x and y:
![image](https://github.com/user-attachments/assets/90ceb865-69fc-4e7c-96ab-3dcc84258608)

According to W3C WebDriver rules, when the parameter x or y does not exist, it must be set as null:
![image](https://github.com/user-attachments/assets/90b9fc8a-b3e0-46a6-ac70-5d3b26aa59a1)

### Expected Behavior

Set the parameters x and y as null or do not validate if they exist or not.

### Minimal Reproducible Example

`import io.appium.java_client.windows.WindowsDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;

import java.net.URL;

public class Test
{
    @Test
    public void test(String hubUrl) throws Exception {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("app", "calc");
        WindowsDriver driver = new WindowsDriver(new URL(hubUrl), capabilities);
        driver.manage().window().setSize(new Dimension(1000, 1000));
    }
}
`

### Environment

- Operating system: Windows 10
- Appium server version (output of `appium --version`): 2.11.2
- Appium driver(s) and their version(s) (`appium driver list`):
√ Listing available drivers
- windows@2.12.26 [installed (npm)]
- uiautomator2 [not installed]
- xcuitest [not installed]
- espresso [not installed]
- mac2 [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]
- Appium plugin(s) and their version(s) (`appium plugin list`):
√ Listing available plugins
- images [not installed]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]
- Node.js version (output of `node --version`): v18.16.1
- `npm` version (output of `npm --version`): 9.5.1

### Link to Appium Logs

https://gist.github.com/lucasandre22/158d834e81874d9da489a9c36d996507

### Further Information

When I send the POST request to WinAppDriver directly to the endpoint /wd/hub/session/<session>/window/rect
with the parameters {"width":1000,"height":1000}, it works with no issues.
So appium itself is trying to validate the parameters and the request is not sent to WinAppDriver, failing my test.

**Comment by mykola-mokhnach** [comment]
This is applicable to all drivers as the validation happens in the base driver

**Comment by lucasandre22** [comment]
Thank you all for the quick response and code fix submission.
