### ISSUE TITLE
Invalid Service com.apple.dt.simulatelocation when set location in iOS Real Device

### ISSUE THREAD

**Issue by luckhiem** [appium/appium#20403]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unexpected data: {"Error":"InvalidService","Request":"StartService","Service":"com.apple.dt.simulatelocation"}
`

### Expected Behavior

Should work

### Minimal Reproducible Example

```
Location location = new Location(13.7627145118467, 100.568213720897, 10);
driver.setLocation(location);
```

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.2.2
- xcuitest@4.35.0 [installed (npm)]
- flutter@2.4.1 [installed (npm)]
- uiautomator2@3.0.4 [installed (npm)]
- Real device or emulator: Xcode 15, iPhone 13 pro max 17.0.1

**Comment by mykola-mokhnach** [comment]
Please use the most recent driver version

**Comment by KazuCocoa** [comment]
Check also -> https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-setsimulatedlocation
(newer xcuitest driver does this method behind the `driver.setLocation`)

**Comment by mykola-mokhnach** [comment]
Closed because of no response
