### ISSUE TITLE
Need  simultaneously update when changes happen in codebase

### ISSUE THREAD

**Issue by MdTaufiqurRahman** [appium/appium#20411]
I clone the main Appium repo.

My problem is that when I change anything from the code, it is not auto-updated.  why?

after changing the code and without building, the project does not show the changes.

I want to know when I change code and then simultaneously update the output without building. 
How can I do it?

**Comment by eglitise** [comment]
Are you referring to a dev/watch mode? It should be working fine if you run `npm run dev`. [Check the Contributing docs](https://appium.io/docs/en/latest/contributing/develop/#watch-files) for more information.

**Comment by MdTaufiqurRahman** [comment]
> Are you referring to a dev/watch mode? It should be working fine if you run `npm run dev`. [Check the Contributing docs](https://appium.io/docs/en/latest/contributing/develop/#watch-files) for more information.

not working. it's also same without the build does not show the changes
