### ISSUE TITLE
Ios 13.3 Appium WebDriverAgent issue with endpoint wda/tap

### ISSUE THREAD

**Issue by EmpireST1** [appium/appium#20416]
Request target: http://localhost:8230/session/9CD2CABA-8321-4436-B4DD-927BCB98AD76/wda/tap
With body: {"x": 352, "y": 384}

Gave me exception on all ios 13.0-13.9

`{
  "value" : {
    "error" : "unknown error",
    "message" : "Invalid parameter not satisfying: allAttributesForKey != nil",
    "traceback" : "(\n\t0   CoreFoundation                      0x0000000194d96a5c 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 1227356\n\t1   libobjc.A.dylib                     0x0000000194abdfa4 objc_exception_throw + 56\n\t2   CoreFoundation                      0x0000000194c98e88 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 188040\n\t3   Foundation                          0x00000001950ce6c4 503900AF-2ECD-329F-B742-C07C3E672BEB + 554692\n\t4   XCTAutomationSupport                0x0000000102920a00 -[XCElementSnapshot _fetchSimpleValueForKey:] + 1168\n\t5   XCTAutomationSupport                0x000000010292291c -[XCElementSnapshot systemAutomationProperties] + 100\n\t6   XCUIAutomation                      0x000000010312743c __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke.19 + 148\n\t7   XCTestCore                          0x0000000102f6488c +[XCTFuture futureWithDescription:block:] + 108\n\t8   XCUIAutomation                      0x0000000103127024 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke_2 + 332\n\t9   XCTestCore                          0x0000000102f932f0 -[XCTContext _runActivityNamed:type:block:] + 196\n\t10  XCTestCore                          0x0000000102f91ed8 -[XCTContext runInternalActivityNamed:block:] + 124\n\t11  XCUIAutomation                      0x0000000103126e88 __137+[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:]_block_invoke + 204\n\t12  XCTestCore                          0x0000000102f93934 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t13  XCTestCore                          0x0000000102f93a74 -[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 80\n\t14  XCUIAutomation                      0x0000000103126c70 +[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:eventSynthesizer:withSnapshot:applicationSnapshot:process:error:] + 364\n\t15  XCUIAutomation                      0x0000000103127c74 -[XCUIElement(XCUIElementEventSynthesis) _dispatchEventWithEventBuilder:error:] + 1044\n\t16  XCUIAutomation                      0x0000000103127f7c __70-[XCUIElement(XCUIElementEventSynthesis) _dispatchEvent:eventBuilder:]_block_invoke + 116\n\t17  XCTestCore                          0x0000000102f932f0 -[XCTContext _runActivityNamed:type:block:] + 196\n\t18  XCTestCore                          0x0000000102f91ed8 -[XCTContext runInternalActivityNamed:block:] + 124\n\t19  XCUIAutomation                      0x0000000103127e4c -[XCUIElement(XCUIElementEventSynthesis) _dispatchEvent:eventBuilder:] + 228\n\t20  XCUIAutomation                      0x000000010315659c -[XCUICoordinate(XCUICoordinateTouchEvents) tap] + 376\n\t21  WebDriverAgentLib                   0x0000000105e0b9b0 +[FBElementCommands handleTap:] + 276\n\t22  WebDriverAgentLib                   0x0000000105d97464 -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t23  WebDriverAgentLib                   0x0000000105d808c8 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 408\n\t24  WebDriverAgentLib                   0x0000000105db9d58 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t25  WebDriverAgentLib                   0x0000000105dba848 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 64\n\t26  libdispatch.dylib                   0x0000000194a63184 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 377220\n\t27  libdispatch.dylib                   0x0000000194a15cd4 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 60628\n\t28  libdispatch.dylib                   0x0000000194a63184 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 377220\n\t29  libdispatch.dylib                   0x0000000194a15190 A3849F96-1C9F-36C5-A15F-70C566F14CFF + 57744\n\t30  CoreFoundation                      0x0000000194d145e4 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 693732\n\t31  CoreFoundation                      0x0000000194d0f5d8 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 673240\n\t32  CoreFoundation                      0x0000000194d0eadc CFRunLoopRunSpecific + 464\n\t33  Foundation                          0x000000019504e7f4 503900AF-2ECD-329F-B742-C07C3E672BEB + 30708\n\t34  WebDriverAgentLib                   0x0000000105d7f710 -[FBWebServer startServing] + 328\n\t35  WebDriverAgentRunner                0x0000000105d60210 -[UITestingUITests testRunner] + 80\n\t36  CoreFoundation                      0x0000000194d9cc20 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 1252384\n\t37  CoreFoundation                      0x0000000194c6cd30 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 7472\n\t38  XCTestCore                          0x0000000102fbdba4 +[XCTFailableInvocation invokeStandardConventionInvocation:completion:] + 64\n\t39  XCTestCore                          0x0000000102fbdb5c __90+[XCTFailableInvocation invokeInvocation:withTestMethodConvention:lastObservedErrorIssue:]_block_invoke_3 + 24\n\t40  XCTestCore                          0x0000000102fbd3dc __81+[XCTFailableInvocation invokeWithAsynchronousWait:lastObservedErrorIssue:block:]_block_invoke + 300\n\t41  XCTestCore                          0x0000000102f79c0c +[XCTSwiftErrorObservation observeErrorsInBlock:] + 256\n\t42  XCTestCore                          0x0000000102fbd1bc +[XCTFailableInvocation invokeWithAsynchronousWait:lastObservedErrorIssue:block:] + 184\n\t43  XCTestCore                          0x0000000102fbd8ac +[XCTFailableInvocation invokeInvocation:withTestMethodConvention:lastObservedErrorIssue:] + 432\n\t44  XCTestCore                          0x0000000102fbdc30 +[XCTFailableInvocation invokeInvocation:lastObservedErrorIssue:] + 68\n\t45  XCTestCore                          0x0000000102faf5f8 __24-[XCTestCase invokeTest]_block_invoke_2 + 84\n\t46  XCTestCore                          0x0000000102f87b14 -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] + 76\n\t47  XCTestCore                          0x0000000102fb2684 -[XCTestCase assertInvalidObjectsDeallocatedAfterScope:] + 88\n\t48  XCTestCore                          0x0000000102faf560 __24-[XCTestCase invokeTest]_block_invoke.78 + 144\n\t49  XCTestCore                          0x0000000102f70c40 -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 160\n\t50  XCTestCore                          0x0000000102faf0d4 -[XCTestCase invokeTest] + 668\n\t51  XCTestCore                          0x0000000102fb0a28 __26-[XCTestCase performTest:]_block_invoke.117 + 32\n\t52  XCTestCore                          0x0000000102f70c40 -[XCTestCase(XCTIssueHandling) _caughtUnhandledDeveloperExceptionPermittingControlFlowInterruptions:caughtInterruptionException:whileExecutingBlock:] + 160\n\t53  XCTestCore                          0x0000000102fb04d4 __26-[XCTestCase performTest:]_block_invoke.107 + 492\n\t54  XCTestCore                          0x0000000102f93934 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t55  XCTestCore                          0x0000000102f93834 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 100\n\t56  XCTestCore                          0x0000000102faff80 -[XCTestCase performTest:] + 248\n\t57  XCTestCore                          0x0000000102f5cadc -[XCTest runTest] + 44\n\t58  XCTestCore                          0x0000000102f968dc -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64\n\t59  XCTestCore                          0x0000000102f967a8 __27-[XCTestSuite performTest:]_block_invoke + 160\n\t60  XCTestCore                          0x0000000102f9625c __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40\n\t61  XCTestCore                          0x0000000102f93934 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t62  XCTestCore                          0x0000000102f93834 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 100\n\t63  XCTestCore                          0x0000000102f961d8 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152\n\t64  XCTestCore                          0x0000000102f96480 -[XCTestSuite performTest:] + 192\n\t65  XCTestCore                          0x0000000102f5cadc -[XCTest runTest] + 44\n\t66  XCTestCore                          0x0000000102f968dc -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64\n\t67  XCTestCore                          0x0000000102f967a8 __27-[XCTestSuite performTest:]_block_invoke + 160\n\t68  XCTestCore                          0x0000000102f9625c __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40\n\t69  XCTestCore                          0x0000000102f93934 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t70  XCTestCore                          0x0000000102f93834 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 100\n\t71  XCTestCore                          0x0000000102f961d8 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152\n\t72  XCTestCore                          0x0000000102f96480 -[XCTestSuite performTest:] + 192\n\t73  XCTestCore                          0x0000000102f5cadc -[XCTest runTest] + 44\n\t74  XCTestCore                          0x0000000102f968dc -[XCTestSuite runTestBasedOnRepetitionPolicy:testRun:] + 64\n\t75  XCTestCore                          0x0000000102f967a8 __27-[XCTestSuite performTest:]_block_invoke + 160\n\t76  XCTestCore                          0x0000000102f9625c __59-[XCTestSuite _performProtectedSectionForTest:testSection:]_block_invoke + 40\n\t77  XCTestCore                          0x0000000102f93934 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t78  XCTestCore                          0x0000000102f93834 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 100\n\t79  XCTestCore                          0x0000000102f961d8 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 152\n\t80  XCTestCore                          0x0000000102f96480 -[XCTestSuite performTest:] + 192\n\t81  XCTestCore                          0x0000000102f5cadc -[XCTest runTest] + 44\n\t82  XCTestCore                          0x0000000102f5ec2c __89-[XCTTestRunSession executeTestsWithIdentifiers:skippingTestsWithIdentifiers:completion:]_block_invoke + 100\n\t83  XCTestCore                          0x0000000102f93934 +[XCTContext _runInChildOfContext:forTestCase:markAsReportingBase:block:] + 172\n\t84  XCTestCore                          0x0000000102f93834 +[XCTContext runInContextForTestCase:markAsReportingBase:block:] + 100\n\t85  XCTestCore                          0x0000000102f5eaf4 -[XCTTestRunSession executeTestsWithIdentifiers:skippingTestsWithIdentifiers:completion:] + 252\n\t86  XCTestCore                          0x0000000102fd1bd0 __72-[XCTExecutionWorker enqueueTestIdentifiersToRun:testIdentifiersToSkip:]_block_invoke_2 + 108\n\t87  XCTestCore                          0x0000000102fd1d50 -[XCTExecutionWorker runWithError:] + 124\n\t88  XCTestCore                          0x0000000102f903dc __25-[XCTestDriver _runTests]_block_invoke.183 + 52\n\t89  XCTestCore                          0x0000000102f691c8 -[XCTestObservationCenter _observeTestExecutionForTestBundle:inBlock:] + 180\n\t90  XCTestCore                          0x0000000102f8fe38 -[XCTestDriver _runTests] + 1024\n\t91  XCTestCore                          0x0000000102f5d0b8 _XCTestMain + 88\n\t92  WebDriverAgentRunner-Runner         0x00000001028d1130 -[_XCTRunnerAppDelegate application:didFinishLaunchingWithOptions:] + 0\n\t93  WebDriverAgentRunner-Runner         0x00000001028d10cc _XCTRunnerRunTests + 0\n\t94  CoreFoundation                      0x0000000194d14834 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 694324\n\t95  CoreFoundation                      0x0000000194d13fd4 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 692180\n\t96  CoreFoundation                      0x0000000194d0f250 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 672336\n\t97  CoreFoundation                      0x0000000194d0eadc CFRunLoopRunSpecific + 464\n\t98  GraphicsServices                    0x000000019ec94328 GSEventRunModal + 104\n\t99  UIKitCore                           0x0000000198e09ae0 UIApplicationMain + 1936\n\t100 WebDriverAgentRunner-Runner         0x00000001028d1390 main + 160\n\t101 libdyld.dylib                       0x0000000194b98360 2E3F4750-8B67-398B-8530-8417651B1718 + 4960\n)"
  },
  "sessionId" : "9CD2CABA-8321-4436-B4DD-927BCB98AD76"
}`

How i can fix it?

**Comment by KazuCocoa** [comment]
I'm not sure what version of WDA did you use, but current XCUITest/WDA supports only iOS 15+, so some feature might not work. You could install expected WDA by installing lower version's `appium-xcuitest-driver`
https://appium.github.io/appium-xcuitest-driver/latest/installation/requirements/
(e.g. 4.27.2)

**Comment by EmpireST1** [comment]
so which driver version i should to use for 13.3 IOS? I tried from [8.7.9](https://github.com/appium/WebDriverAgent/releases/tag/v8.7.9) to [v4.11.0](https://github.com/appium/WebDriverAgent/releases/tag/v4.11.0)

**Comment by KazuCocoa** [comment]
Searched the error in our repositories. Perhaps these are related:

- https://github.com/appium/WebDriverAgent/issues/716
- https://github.com/appium/WebDriverAgent/issues/683

Then, the error itself comes from the XCTest internal. Potentially lower Xcode version build WDA would work, but I have no such old environment.
