### ISSUE TITLE
bug: optionalIntentArguments cannot be passed inside activateApp on Android

### ISSUE THREAD

**Issue by maryna-k** [appium/appium#20415]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We pass optionalIntentArguments to Android app where we put a mock server URL. We have to clean the data of the app before each test, to make sure that the state of the app does not affect the tests. Until appium 2.0 we were able to use launchApp() command that relaunched the app with our capabilities. Now, since this command is depracated, we are using `browser.execute("mobile: activateApp")` command and passing there optionalIntentArguments, however they are not applied to the app any more and we cannot run the tests using mocks. 

The capabilities are set as follows in config file:

```
appiumConfig = {
	...
	capabilities: [
		{
			platformName: Android,
			...
			"appium:processArguments": {
				env: { "baseURL": `${MOBILE_API}` }
			},
			"appium:optionalIntentArguments": `tt://config?baseUrl=${MOBILE_API}`
		},
	]
```

This is how we are cleaning and relaunching the app and trying to pass arguments to `mobile: activateApp` command:

```
public static async resetApp() {
		const appPackage = browser.capabilities["appPackage"];
		await browser.terminateApp(appPackage);

		await browser.execute("mobile: clearApp", {
			appId: appPackage,
			appPackage: appPackage,
			bundleId: appPackage,
		});

		const API = "our url"

		if (browser.isAndroid) {
			try {
				await browser.execute("mobile: activateApp", {
					appId: appPackage,
					appPackage: appPackage,
					"appium:optionalIntentArguments": `touchtunes://m4/config?baseUrl=${API.replace(/(\r\n|\n|\r)/gm, "").trim()}`
				});
			} catch (error) {
				console.log("\nCommand: 'mobile: activateApp' error\nError: ", error);
			}
		} else {
			....
		}
	}
}
```

We also tried with the following instead of `"appium:optionalIntentArguments"`:
```
await browser.execute("mobile: activateApp", {
					appId: appPackage,
					appPackage: appPackage,
					optionalIntentArguments: `touchtunes://m4/config?baseUrl=${API.replace(/(\r\n|\n|\r)/gm, "").trim()}`
				});
```

### Expected Behavior

We want to be able to pass optionalIntentArguments with mock server URL when the app is cleaned and restarted between each test. Should be done with `mobile: activateApp` command or any other working solution.

### Minimal Reproducible Example

- 

### Environment

- Operating system: MacOS Ventura 13.4
- Appium server version (output of `appium --version`): Appium v2.11.2
- Appium driver(s) and their version(s) (`appium driver list`): uiautomator2@3.7.4
- Node.js version (output of `node --version`):  v18.9.0
- `npm` version (output of `npm --version`): 8.19.1
- Last component(s) version which did _not_ exhibit the problem: Appium 2.0.0-beta.71
- Client: Webdriverio v8

### Link to Appium Logs

https://gist.github.com/maryna-k/ee57f06ab2b87ca717af4887407c1e64https://gist.github.com/maryna-k/ee57f06ab2b87ca717af4887407c1e64

**Comment by KazuCocoa** [comment]
I assume I would use startActivity instead of activateApp to customize the launching method.
https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-activateapp
https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-startactivity

**Comment by KazuCocoa** [comment]
https://discuss.appium.io/ also might help to ask a question.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
