### ISSUE TITLE
Appium is crashing as soon as test is triggered

### ISSUE THREAD

**Issue by tking16** [appium/appium#20412]
I've never seen this before. I'm running Appium on a different machine which the Appium server starts fine. But then when I run a test (through pytest) the server shuts down immediately.

Node Version: v19.8.0
Same issue on latest Appium version (2.11) and 2.5.4

Logs: 
[appiumCrash.log](https://github.com/user-attachments/files/16377142/appiumCrash.log)

Sorry if it's trivial. Thanks for the help

**Comment by mykola-mokhnach** [comment]
This might be a node bug. Make sure you use a LTS version of Node.js

**Comment by tking16** [comment]
Thank you, it indeed worked when I switched to the latest node version
