### ISSUE TITLE
App crashes when WDA interacts (e.g. clicks) with UI developed using Flutter v3.22

### ISSUE THREAD

**Issue by Implementist** [appium/appium#20413]
We have been using WDA and Python scripts to test our app for a long time, and some of the interfaces in our app are developed using Flutter. Everything was working fine until recently when we upgraded Flutter from version 3.10 to 3.22. The problem occurred: after WDA performs some operations in the Flutter-developed interfaces and exits these interfaces, any operation performed by WDA (such as clicking, waiting for a widget to appear) would cause our app to crash.

Looking forward to any meaningful replies and help.

**Comment by mykola-mokhnach** [comment]
Please provide the device log for the time period this crash happens

**Comment by mykola-mokhnach** [comment]
From the description I feel like it might be something Flutter/XCTest specific. You may try to confirm that assumption by running a vanilla XCTest UI integration test with the app.

**Comment by Implementist** [comment]
Here is a zip package of the device logs: [device_logs.zip](https://github.com/user-attachments/files/16378585/device_logs.zip). The most recent crash occurred on 2024/07/25 between 21:39 and 21:40.

> Please provide the device log for the time period this crash happens

**Comment by Implementist** [comment]
> unfortunately I cannot find any useful info in the above archive. Could you please only gather the device syslog for the mentioned time range?

Thank you for your reply. Here is the syslog I just obtained during the Crash. The Crash occurred at 20:36.
[sys.log](https://github.com/user-attachments/files/16391889/sys.log)

**Comment by mykola-mokhnach** [comment]
> Jul 26 20:36:01 iPhone WebDriverAgentRunner-Runner(WebDriverAgentLib)[2898] <Notice>: Quiescence checks are disabled for com.tencent.wework.dailybuild application. Making it to believe it is idling

This error message repeats quite often often it means the app is not idling so that XCTest is unable to acquire the access to its accessibility or do any interactions with it. Double check the app under test is idling enough and leaves enough "gaps" on the main thread for XCTest.

> Jul 26 20:36:08 iPhone WebDriverAgentRunner-Runner(libxpc.dylib)[2898] <Notice>: [0x15517d470] Re-initialization successful; calling out to event handler with XPC_ERROR_CONNECTION_INTERRUPTED

This is a native XCTest error. I don't think there is anything from WDA side to influence that.

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
