### ISSUE TITLE
macOs: WebDriverAgentRunner-Runner signing

### ISSUE THREAD

**Issue by grokys** [appium/appium#20429]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every time I run and connect to appium with the mac2 driver on a macOS machine running Sonoma I see the following dialog:

![photo_2024-07-30_13-11-32](https://github.com/user-attachments/assets/02c15f9f-0857-40f1-b6ff-ffbff88c8664)

I am trying to use appium in an unattended CI setting and this causes a problem.

### Expected Behavior

No dialog should be displayed.

### Minimal Reproducible Example

- Run appium with mac2 driver installed
- Connect to it
- Dialog appears

### Environment

- Operating system: macOS Sonoma 14.5
- Appium server version (output of `appium --version`): 2.11.2
- Appium driver(s) and their version(s) (`appium driver list`):  mac2@1.18.2
- Appium plugin(s) and their version(s) (`appium plugin list`): none
- Node.js version (output of `node --version`): v22.4.1
- `npm` version (output of `npm --version`): 10.8.1
- Last component(s) version which did _not_ exhibit the problem: 
- Platform and version under test:
- Real device or emulator/simulator: real macOS machine

### Further Information

I have seen [this issue](https://github.com/appium/appium-mac2-driver/issues/251) which says:

> You may reconfigure WDA and sign it with a digital signature to prevent the above message

But no more details were provided. The only documents I could find which seemed to describe this is are listed below, but these seem to be referring to iOS and not macOS:

https://appium.github.io/appium-xcuitest-driver/5.4/run-preinstalled-wda/
https://appium.github.io/appium-xcuitest-driver/5.4/run-prebuilt-wda/

**Comment by mykola-mokhnach** [comment]
This is a macOS security feature and it cannot be disabled. The only way to workaround this behaviour is to configure digital signing for WDA: https://stackoverflow.com/questions/41062607/osx-complains-that-app-is-from-unidentified-developer-although-it-passes-all-va

**Comment by grokys** [comment]
Thank you @mykola-mokhnach - at first glance that looks like the information I was searching for. Might be a good idea to add that information to the appium docs, but in the meantime I'll close the issue and reopen if I hit any problems.

**Comment by mykola-mokhnach** [comment]
Feel free to create a PR and improve driver documentation. We'd be happy to review it.
