### ISSUE TITLE
Appium error:  Did not get any response for atom execution after 120002ms

### ISSUE THREAD

**Issue by sanjaypatidar1** [appium/appium#20428]
### Do I have the most recent component updates?

- [ ] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are running our regression suite daily based on CRON Job and getting the error ": **Did not get any response for atom execution after 120002ms"**

**Note : I don't get this error always. It is intermittent.**

I can't shared screenshot as well as code due to privacy.

### Expected Behavior

This error should not be come -  "Did not get any response for atom execution after 120002ms". which is unknown.

### Minimal Reproducible Example

It is intermittent error and I don't know about the pattern for this issue.

But when you run more then 10 test case parallel for Android and iOS then getting the error.

### Environment

- MAC
- Appium server version : Appium v1.22.3
- Node.js version : v16.16.0
- `npm` version : 8.11.0
- Last component(s) version which did _not_ exhibit the problem: 8.11.0
- Real iPhone - iPhone 13 Pro, OS : 15
- Running in BrowserStack cloud

### Further Information

I can' share my logs and details of test cases due to some privacy.

Reference someone created the same issue earlier but now we are facing the same issue from today.

**Comment by mykola-mokhnach** [comment]
> Appium v1.22.3

This version is out of date, we do not support it anymore. Please update to Appium 2.

> I can' share my logs and details of test cases due to some privacy.

Unfortunately we cannot help much without having all the necessary details. You may also try to ask your question at the Appium forum.

Closed as not an issue.

**Comment by sanjaypatidar1** [comment]
thanks @mykola-mokhnach , I will check how can shared my Appium logs with you.
