### ISSUE TITLE
Misleading warning message about driver compatibility in `appium --version`

### ISSUE THREAD

**Issue by algot** [appium/appium#20423]
I encountered an issue where the command `appium --version` reports the correct version **(2.1.0)**, but there is a misleading warning message indicating that the *uiautomator2* driver, which has a peer dependency on Appium version **2.4.1**, may be incompatible with the current Appium version.

**Steps to Reproduce:**

Run `node --version` to confirm the Node.js version.
```powershell
node --version
v16.20.2
```
Run `appium --version` to check the Appium version.

```powershell
appium --version
WARN Appium Appium encountered 1 warning while validating drivers found in manifest C:\Users\ohotvian\node_modules\.cache\appium\extensions.yaml
WARN Appium Driver "uiautomator2" has 1 potential problem:
WARN Appium   - Driver "uiautomator2" (package `appium-uiautomator2-driver`) may be incompatible with the current version of Appium (v2.1.0) due to its peer dependency on older Appium v^2.4.1. 
Please ask the developer of `appium-uiautomator2-driver` to update the peer dependency on Appium to v2.1.0.
2.1.0
```

**Expected Behavior:** 
The version reported by `appium --version` should match the actual installed version of Appium, and the warning message should correctly reflect version compatibility.

**Actual Behavior:** 
The command `appium --version` reports 2.1.0 correctly, but there is a warning suggesting that version 2.4.1 is older than 2.1.0, which is incorrect.

**Environment:**

Node.js version: v16.20.2
Appium version: 2.1.0
Operating System: Windows 10

Logs: Here is the output from the appium --version command:

```powershell
WARN Appium Appium encountered 1 warning while validating drivers found in manifest C:\Users\ohotvian\node_modules\.cache\appium\extensions.yaml
WARN Appium Driver "uiautomator2" has 1 potential problem:
WARN Appium   - Driver "uiautomator2" (package `appium-uiautomator2-driver`) may be incompatible with the current version of Appium (v2.1.0) due to its peer dependency on older Appium v^2.4.1. Please ask the developer of `appium-uiautomator2-driver` to update the peer dependency on Appium to v2.1.0.
2.1.0
Additional Information: It seems like there might be a discrepancy in versioning, causing the warning message to incorrectly state that version 2.4.1 is older than 2.1.0.
```

**Comment by mykola-mokhnach** [comment]
This message has been fixed in the later server versions
