### ISSUE TITLE
bug: driver timeout for finding element is not correctly respected

### ISSUE THREAD

**Issue by shadow2720** [appium/appium#20430]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems that in certain cases appium is not able to respect timeout configured for location elements. According to logs it seems that the problem could be appium apps running on Android phone, but I´m not sure about that.

I´m attaching logs from server & logcat from phone. In these logs I first try to look for "inCallFragment" by accessibility ID. Timeout is set to 500ms. This element is NOT present in layout. I´d expect to receive an error right after 500ms is gone, but it took 4s to get the error. Right after that another element request is done, now looking by resource ID of "txtErrorMessage" and timeout 200ms. Response took almost 9s.

I tried to tackle the timeouts hoping that increasing the timeout value would actually speed the response (for some reason) but it does not.

Tested on real device (Samsung SM-T220, Android 14). However I am expecting responses after bigger times then timeout states quiet often on other devices as well.

[appium_problemLog.log](https://github.com/user-attachments/files/16457988/appium_problemLog.log)
[R9PW102GG1T_All.txt](https://github.com/user-attachments/files/16457987/R9PW102GG1T_All.txt)

### Expected Behavior

As I mentioned, I´d expect to receive an error after the given timeout is reached no matter what happens.

### Minimal Reproducible Example

This is the code I use where the issue occurs. Wont be of use I believe since it uses custom interfaces I built arround driver itself.
EDIT: Sorry for formating, for some reason I cannot format it as codeblock

`while (true) {
            logMessage(adbId, "Checking call status...");
            phoneFunctions.setDriverWait(-500);
            if (checkActiveCall) {
                callScreenFound = phoneFunctions.findElementByAccessibilityId(Resources.ACTIVE_CALL_LAYOUT_FRAGMENT, Constants.ELEMENT_LOOKUP_STRING) != null;
                if (callScreenFound) {
                    logMessage(adbId, "Active call screen found, stopping waiting...");
                    break;
                }
                phoneFunctions.setDriverWait(-200);
                errorScreenFound = phoneFunctions.findElementById(Resources.CALL_ERROR_MESSAGE, Constants.ELEMENT_LOOKUP_STRING) != null;
                if (errorScreenFound) {
                    logMessage(adbId, "Call Error screen found, stopping waiting...");
                    break;
                }
            } else {
                callScreenFound = phoneFunctions.findElementById(Resources.OUTGOING_CALL_SCREEN_RINGING, Constants.ELEMENT_LOOKUP_STRING) != null;
                if (callScreenFound) {
                    logMessage(adbId, "Outgoing call screen found, stopping waiting...");
                    break;
                }
            }
            if ((System.currentTimeMillis() - startTime) >= timeout * 1000) {
                logMessage(adbId, "Could not connect call in within timeout of: " + timeout);
                break;
            }
            logMessage(adbId, "Call screen or Error screen not found, waiting...");
        }`

### Environment

- Operating system: Server on Debian 12
- Appium server version (output of `appium --version`): 2.10.3
- Appium driver(s) and their version(s) (`appium driver list`): uiautomator2@3.5.4
- Appium plugin(s) and their version(s) (`appium plugin list`): appium-dashboard@2.0.3, device-farm@8.4.7-rc. 41
- Node.js version (output of `node --version`): 20.12.0
- `npm` version (output of `npm --version`): 10.8.1
- Last component(s) version which did _not_ exhibit the problem: none, it is there for a long time
- Platform and version under test: Android 14
- Real device or emulator/simulator: real device, Samsung SM-T220

**Comment by mykola-mokhnach** [comment]
This might be related to the fact that UIAutomator always waits for the main thread to be in idle state and this timeout is set to 10 seconds by default. You may try to play with [waitForIdleTimeout](https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#settings-api) setting value in order to customise this timeout.

**Comment by mykola-mokhnach** [comment]
Also make sure you don't have any implicit waits set in your code.

**Comment by shadow2720** [comment]
Hello, thanks for response. Playing with waitForIdleTimeout did not help, but you mentioned that I´m not supposed to use implicit waits (which I am). Generaly I change implicit wait on driver whenever I look for an element and the timeout value depends on that element (how quickly I expect it to appear). This approach worked for me really well because driver waits exactly the time I specified and then I receive an error if element does not appear.

Removing implicit wait is not an option because by default implicit wait is set to 0 and therefore I get an error everytime element is not present right away. I tried to use "waitForSelectorTimeout" but it does not override implicit wait either.

So in case you dont think the mentioned issue is not a bug, could you help me making my approach correct for following case?

_I´m on application screen one where I press button to start a call. Outgoing call screen is supposed to appear and within few seconds active call screen is supposed to appear.
In my code I´m calling a method startCall() with a timeout. That method has a while(true) construction and its supposed to wait until active call screen appears or timeout happens_

Lets assume the initial state before this happens is implicit wait set to 0, waitForIdleTimeout and waitForSelectorTimeout are default as well. What would be correct approach for while condition to iterate as fast as possible checking visible elements and looking for active call screen?

**Comment by mykola-mokhnach** [comment]
> So in case you dont think the mentioned issue is not a bug, could you help me making my approach correct for following case?

Unfortunately I don't provide this type of consulting services here. Here we try to address server or driver issues. You may try to ask your question in discussions or at the Appium forum.

**Comment by shadow2720** [comment]
I see, well nobody ever answered me there...
Nevermind. Back to the original report then: waitForIdleTimeout did not change anything, the response is still stuck. What else can I try?

**Comment by mykola-mokhnach** [comment]
if setting both waitForIdleTimeout and the implicit wait to zero did not help to remove delays then it is probably an issue with low level accessibility interactions, which is beyond our control. The UiAutomator framework itself must interact with the application accessibility layer on the main thread and it might be blocked from that because of various internal reasons, that only Google knows about. You may verify this assumption by preparing a vanilla UiAutomator integration test doing the similar set of actions without using Appium's UIA2 driver.

**Comment by shadow2720** [comment]
ok, thank you for your help, you can close this ticket
