### ISSUE TITLE
Installing APKs on Android Devices via Dockerized Appium: Path and File Handling

### ISSUE THREAD

**Issue by omercagriyilmaz** [appium/appium#20435]
Hello,

I am using Appium Java Client 9.2.2, with UI2 version 3.7.4 and Appium version 2.5.1.

What I want to do is install applications on real Android devices. For this, I am using the "install app" method within the "Appium Java Client Library." However, my setup is a bit different. Appium is running in a Docker container.

The issue is that the "installApp" method asks for a path. When I provide this file path, it says the file path cannot be found. It’s likely that the file path needs to be within the Appium container. However, the Java project where the Appium Java Client is used is running in a different container. So, I actually need to push this file to Appium.

I am using Appium’s "pushFile" for this, but "pushFile" tries to directly push the file to the phone.

How can I resolve this? Is it possible to provide a URL (e.g., AWS S3 URL) via the Appium library to install the APK?

Thanks!

**Comment by mykola-mokhnach** [comment]
Yes, it is possible to provide a direct url to the app.
Yes, if you want to provide a path to the local file then this file must be located on the same physical host where the server is running.

**Comment by omercagriyilmaz** [comment]
Thank you for the information and your response.
