### ISSUE TITLE
mobile: launchApp does not launch the app in the language set in desired capabilities

### ISSUE THREAD

**Issue by RahulNethi** [appium/appium#20438]
Since driver.launchApp is deprecated, I started using driver.executeScript("mobile: launchApp", ImmutableMap.of("bundleId", bundleId)).
The app is initialized successfully with original desired capabilities where I added caps.setCapability("appium:language", "es");
However when I use mobile: launchApp to relaunch the app, it launches the app in English not honoring the language capability (es).

iOS - XCUITest

**Comment by KazuCocoa** [comment]
Please specify language with `arguments` https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-launchapp

In fact that the language config in iOS is process argument:
https://github.com/appium/appium-xcuitest-driver/blob/855c400adc308343c0694ec6528c3d7a2c6933c6/lib/driver.js#L1237-L1243

Perhaps the xcuitest document could address it.

**Comment by mykola-mokhnach** [comment]
This is expected. The [launchApp](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/reference/execute-methods.md#mobile-launchapp) API supports its own set of arguments. You may pass the language and locale to it by setting the appropriate command line arguments as described in [Testing Specific Languages and Regions](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/TestingYourInternationalApp/TestingYourInternationalApp.html)

**Comment by RahulNethi** [comment]
@KazuCocoa Can you help me with that? is the following arugment correct?
driver.execute("mobile: launchApp", ImmutableMap.of("bundleId", bundleId, "arguments", "language:es"));

**Comment by KazuCocoa** [comment]
I think like https://github.com/appium/java-client/blob/567deee4ae069965e7da4f4e9bd1a05a09dfcfb5/src/e2eAndroidTest/java/io/appium/java_client/android/AndroidDriverTest.java#L153

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
