### ISSUE TITLE
[Feat]: Get clipboard in iOS real machine without switch app

### ISSUE THREAD

**Issue by wabicai** [appium/appium#20448]
I want to get cllipboard from iOS real device. But in [https://developer.apple.com/forums/thread/706761](https://developer.apple.com/forums/thread/706761) show that i don't have permission to get clipboard when appium is running background.

[https://appium.github.io/appium-xcuitest-driver/latest/guides/clipboard/](https://appium.github.io/appium-xcuitest-driver/latest/guides/clipboard/)
In the official documentation, it shows that I need to switch the active application. But unfortunately, I can't. Because it will refresh my app. That's not what I want to see

So i try to provide a method in my app, for getting clipboard context. Just like $backgroundApi.serviceE2E.getClipboard();

I try this in appium, but it does's work. Showing error log with "Method is not implemented"
```
browser.execute(async done => {
      const data = $backgroundApi.serviceE2E.getClipboard();
      done(data);
    });
```

**Comment by mykola-mokhnach** [comment]
> browser.execute(async done => {
>       const data = $backgroundApi.serviceE2E.getClipboard();
>       done(data);
>     });

This won't work. XCUITest is a blackbox framework. It obviously does not have access to app internals.

> In the official documentation, it shows that I need to switch the active application. But unfortunately, I can't. Because it will refresh my app. That's not what I want to see

Unfortunately we don't know any other possibilities to do that.
