### ISSUE TITLE
[Feat]: Is there has any way to run js thread in real device app context? 

### ISSUE THREAD

**Issue by wabicai** [appium/appium#20444]
I want to get cllipboard from iOS real device. But in https://developer.apple.com/forums/thread/706761 show that i don't have permission to get clipboard when appium is running background.

So i try to provide a method in my app, for getting clipboard context. Just like $backgroundApi.serviceE2E.getClipboard();

I try this in appium, but it does's work. Showing error log with "Method is not implemented"
```js
browser.execute(async done => {
      const data = $backgroundApi.serviceE2E.getClipboard();
      done(data);
    });
```

**Comment by KazuCocoa** [comment]
I'm not sure that command reached appium server without appium server log, but perhaps https://appium.io/docs/en/2.0/guides/execute-methods/ in WebView context? Asking question in https://discuss.appium.io/ would also help.
