### ISSUE TITLE
Pop up "The file WebDriverAgent.xcodeproj could not be unlocked"

### ISSUE THREAD

**Issue by Iwonk** [appium/appium#20446]
When I opened the **WebDriverAgent.xcodeproj** I always get this pop-up, before that it asked me to Unlock, then I pressed Unlock and this pop-up always appeared and I couldn't save the progress or close the WDA project because of this pop-up.![image](https://github.com/user-attachments/assets/23b72d23-943c-4ce9-b491-c3b4aaf87e07)

I also change/edit the permission on finder to **Read & Write**![image](https://github.com/user-attachments/assets/1b387360-f768-4bee-90f7-243cbdd967ae)

And also tried to update XCUITest driver to the latest version and re-installing it but still gave me pop-up issue. Any advice for toubleshooting this issue?

npm : 10.1.0
node : 20.9.0
Appium : 2.11.3
XCUITest : 7.24.12
XCODE : 15.4

**Comment by KazuCocoa** [comment]
Where did you install the module? Usually appium installs it in `~/.appium` with `appium driver install xcuitest` so the same login should have write permission for it.

**Comment by Iwonk** [comment]
Yes, I installed the modules on `~/.appium`, so  the path it should be like this `/Users/inaji/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent`

**Comment by KazuCocoa** [comment]
Then, I have no idea because Appium's installation itself installed the node modules in your home directory, which usually means you are allowed to write on that. Appium itself does not modify file permissions. Possibly, https://discuss.appium.io/ has a similar user who met such a situation.

**Comment by mykola-mokhnach** [comment]
According to https://stackoverflow.com/questions/20182676/unlock-xcode-files the reason could be that the module has been installed with sudo privileges. A solution would be to reinstall it with normal privileges
