### ISSUE TITLE
Android - Tests failing with urllib3.exceptions.MaxRetryError

### ISSUE THREAD

**Issue by tking16** [appium/appium#20443]
I've switched my Android tests to run with parallel execution (via device farm), but I'm getting a lot of failures with "connection refused" errors. Hard to understand the issue myself so hoping for some guidance

Pytest report ⬇️

Appium log ⬇️

Log from node on remote machine, not sure where the error is coming from exactly ⬇️

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly. 
Also the attached log is impossible to read. Please highlight the part where the issue happens.
Are you sure this is a server issue? If you use third party plugins then please disable them first and try to repro it with a "clean" server setup .

**Comment by tking16** [comment]
No idea where it is in the logs. All I can see this error from the test report 
```
E           urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=31337): Max retries exceeded with url: /session/44d15359-5830-4e2a-a931-d7ba2f620a0c/appium/start_recording_screen (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104ed45b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
```
So it has something to do with Appium's `start_recording_screen` function. We've put it in the code so that it will grab a screen recording after a re-run fails

**Comment by mykola-mokhnach** [comment]
> No idea where it is in the logs. All I can see this error from the test report

Unfortunately I cannot scan megabytes of logs looking for an unknown issue. The above exception is too generic and might happen because of various reasons as described in https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#socket-hangup-error

Perhaps, it would make sense for you to hire a consultant.
