### ISSUE TITLE
[Feat]: add notarization to the macOS releases

### ISSUE THREAD

**Issue by 426652** [appium/appium#20453]
Notarization of macOS apps has been around for more than 5 years and is now a security requirement when deploying any app to managed Mac systems in the enterprise. Without it we can't maintain or advertise Appium in our internal stores. (Downloading from the Internet is restricted)

The next macOS release will also make it more difficult to run unnotarized apps for any user in any environment so  taking care of the notarization now  will also be a great user experience improvement for everyone.

**Comment by eglitise** [comment]
Appium is just a JS package distributed through npm, so (correct me if I'm wrong) notarization is not relevant here. At the very least, I could not find any information about notarizing npm packages.
Are you perhaps referring to Appium Inspector, which is an Electron app with dedicated macOS versions?

**Comment by mykola-mokhnach** [comment]
Closed because of no response
