### ISSUE TITLE
appium-windows-driver - does it support WinUI?

### ISSUE THREAD

**Issue by Aubbles01** [appium/appium#20452]
My organization is currently migrating our Xamarin cross-platform application (iOS and Android) to Microsoft's replacement cross-platform technology, MAUI.

We are hoping to include Windows in our automated testing now that we are moving to MAUI, but Appium doesn't seem to be able to see much of the DOM of the application.  Microsoft touts Appium as a way to automate the UI for MAUI (https://learn.microsoft.com/en-us/samples/dotnet/maui-samples/uitest-appium-nunit/) but it looks like this may not be true as MAUI apps must use the WinUI technology (rather than WPF or WinForms, for example).

From the ReadMe on the appium-windows-driver repo, it doesn't mention support WinUI.  However, the very old WinAppDriver does have some mention of WinUI, although I'm not clear on where that was left.

Does anyone know if it's possible to automate WinUI applications with appium?  Has anyone done it or know of plans to support it in the future if it's not supported now?

**Comment by KazuCocoa** [comment]
I wondered if https://discuss.appium.io/ would help to ask such a question

**Comment by mykola-mokhnach** [comment]
It would be the beat to ask such questions at https://github.com/microsoft/WinAppDriver

Appium windows driver is just a wrapper to this server
