### ISSUE TITLE
WebDriverAgentRunner is conflicting with VPN

### ISSUE THREAD

**Issue by RSV7** [appium/appium#20459]
There is a connection issue with WebDriverAgentRunner and iOS device (iPhone XR) when VPN (paloalto) is ON.

It's required in my case to have VPN connection ON while running automation tests locally on my device. But WDA is failing to connect to run test on the device (screenshots with errors will be attached)

Withought VPN -> all works as expected (connection is successful)

I tried a workaround:
- turn VPN OFF
- start running (test) WDA in xcode (connection is successful and wda is installed on a device. Automation is running)
- turn VPN ON
Actual result: in this case connection with the device is successful and automation test can run for a while but further it is dropped in the middle and connection errors appear (see screenshots)

Notes:
Perhaps, I could wrongly conclude that the issue is only in WDA. Might be in xcode or other nuances. 
Could you please clarify/advise/fix?
In case more details are required from my end, please let me know

Thank you in advance 🤝 

My setup:
Macbook M3 (Sonoma 14.6.1)/ Appium v2.5.1/ WDA v8.9.1 / xcuitest@7.3.1
iPhone XR/ iOS  17.6.1

<img width="250" alt="Screenshot 2024-08-15 at 09 27 04" src="https://github.com/user-attachments/assets/39ce740b-2ffb-4082-8740-09704e0f09c8">
<img width="218" alt="Screenshot 2024-08-15 at 09 32 53" src="https://github.com/user-attachments/assets/8b055d44-c481-47f2-89a3-a35e8aa5e076">

**Comment by RSV7** [comment]
Additional error log probably can be useful: 

A connection to this device could not be established.
Domain: com.apple.dt.CoreDeviceError
Code: 4000
User Info: {
    DVTErrorCreationDateKey = "2024-08-15 08:13:21 +0000";
    IDERunOperationFailingWorker = IDELaunchCoreDeviceWorker;
}
--
A connection to this device could not be established.
Domain: com.apple.dt.CoreDeviceError
Code: 4000
User Info: {
    IDERunOperationFailingWorker = IDELaunchCoreDeviceWorker;
}
--
The operation couldn’t be completed. Device error
Domain: NSPOSIXErrorDomain
Code: 83
Failure Reason: Device error
--

Event Metadata: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_isCoreDevice" = 1;
    "device_isWireless" = 1;
    "device_model" = "iPhone11,8";
    "device_osBuild" = "17.6.1 (21G93)";
    "device_platform" = "com.apple.platform.iphoneos";
    "dvt_coredevice_version" = "355.28";
    "dvt_mobiledevice_version" = "1643.120.2";
    "launchSession_schemeCommand" = Test;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 26167;
    "operation_errorCode" = 83;
    "operation_errorDomain" = "com.apple.dt.CoreDeviceError.4000.NSPOSIXErrorDomain";
    "operation_errorWorker" = IDELaunchCoreDeviceWorker;
    "operation_name" = IDERunOperationWorkerGroup;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 0;
    "param_debugger_type" = 1;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 0;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 0;
    "param_diag_gpu_frameCapture_enable" = 3;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 1;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 0;
    "param_install_style" = 2;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 8256;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_structuredConsoleMode" = 0;
    "param_testing_launchedForTesting" = 1;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos17.5";
    "sdk_osVersion" = "17.5";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 14.6.1 (Build 23G93)
Xcode 15.4 (22622) (Build 15F31d)
Timestamp: 2024-08-15T10:13:21+02:00

**Comment by RSV7** [comment]
And this:
<img width="1401" alt="Screenshot 2024-08-15 at 10 17 06" src="https://github.com/user-attachments/assets/01c4c88f-7fbb-4cd4-bfd9-100c46b54c5f">

**Comment by KazuCocoa** [comment]
It looks like... the connection issue was Xcode/xcodebuild and iOS related rather than WDA itself. What happens with https://appium.github.io/appium-xcuitest-driver/latest/guides/run-preinstalled-wda/ for example? So, if we do not use xcodebuild to keep running WDA process on the device.

**Comment by RSV7** [comment]
> It looks like... the connection issue was Xcode/xcodebuild and iOS related rather than WDA itself. What happens with https://appium.github.io/appium-xcuitest-driver/latest/guides/run-preinstalled-wda/ for example? So, if we do not use xcodebuild to keep running WDA process on the device.

I learned a way how to run WDA without starting "test" in xcode. Thanks for this nice hint! 
BUT the same issues I'm still facing. 

More details:
This was my command to start it without xcodebuild:
`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<my device UDID> test`

This was working when VPN was OFF! 

But when VPN was ON -> same issue:
`Ineligible destinations for the "WebDriverAgentRunner" scheme:
		{ platform:iOS, arch:arm64, id:<my device UDID>, name:Radkevich, Sergei’s iPhone, error:Device is busy (Connecting to Radkevich, Sergei’s iPhone) }`
		
And same "workaround" I tried as mentioned initially, only difference is that:
- when I start "test" from the command line
- turn ON VPN
Actual: The test is running without being dropped in the middle. But I'm not sure if this will be stably work further or not

To conclude it: Still looking like a WDA issue or Apple. 

And still, please assist? 😄

**Comment by RSV7** [comment]
Just to make it clear. After test it several times -> the same issue as for xcode build (workaround)

>>But I'm not sure if this will be stably work further or not
Same behavior. It's dropped in the middle.

Overall. So far I'm blocked to test on real device locally. Need backup!

**Comment by jlipps** [comment]
Can you run a vanilla XCUITest while the VPN is on?

I.e., if you remove WDA/Appium entirely from the stack, and just rely on Apple's XCTest tooling, does it work?
