### ISSUE TITLE
bug: Unable to access elements in Appium

### ISSUE THREAD

**Issue by Skisperd** [appium/appium#20454]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm facing an issue where, despite all components being updated and configured correctly, I can't access specific elements when testing with Appium. Even after following the recommendations and configuring the environment as per the official guide, the issue persists.

### Expected Behavior

Elements should be accessible and interactable without errors during automated testing execution.

### Minimal Reproducible Example

![Captura de Tela 2024-08-13 às 11 50 42](https://github.com/user-attachments/assets/bca3a7a2-2ea9-463b-a6e3-fb96aacb2b45)

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.11.3
- Appium driver(s) and their version(s) (`appium driver list`):
- ✔ Listing available drivers
- uiautomator2@3.7.6 [installed (npm)]
- xcuitest@7.24.15 [installed (npm)]
- fake@5.5.2 [installed (npm)]
- Appium plugin(s) and their version(s) (`appium plugin list`):
- ✔ Listing available plugins
- images [not installed]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]
- Node.js version (output of `node --version`):20.16.0
- `npm` version (output of `npm --version`):10.8.1
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: 17.5.1
- Real device or emulator/simulator: Iphone 13 Pro max

### Further Information

➜  ~ appium-doctor     
WARN AppiumDoctor [Deprecated] Please use appium-doctor installed with "npm install @appium/doctor --location=global"
info AppiumDoctor Appium Doctor v.1.16.2
info AppiumDoctor ### Diagnostic for necessary dependencies starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 20.16.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed in: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage. Installed version is: 0.39.1
info AppiumDoctor  ✔ HOME is set to: /Users/tfdias
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/tfdias/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home

**Comment by eglitise** [comment]
It looks like your app source contains a webview.
* Please check that you have [enabled Web Inspector in mobile Safari settings](https://appium.github.io/appium-xcuitest-driver/latest/preparation/real-device-config/)
* Please check if [the webview is accessible through desktop Safari](https://appletoolbox.com/use-web-inspector-debug-mobile-safari/)

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#elements-cannot-be-found

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
