### ISSUE TITLE
bug: <title>Unable to get location of device.

### ISSUE THREAD

**Issue by najeer97** [appium/appium#20477]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For androidDriver.location().getLongitude(), getting exception as 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot parse the actual location values from the command output: Broadcasting: Intent { act=io.appium.settings.location flg=0x400000 cmp=io.appium.settings/.receivers.LocationInfoReceiver }
Broadcast completed: result=0, data=""
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.8'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [15d22179-2250-40d7-a57c-048c5aff657e, getLocation {}]
Capabilities {appium:automationName: UIAutomator2, appium:databaseEnabled: false, appium:desired: {automationName: UIAutomator2, deviceName: Regression5, newCommandTimeout: 1200, platformName: ANDROID, udid: R9ZW90G00BX, uiautomator2ServerInstallTimeout: 300000}, appium:deviceApiLevel: 34, appium:deviceManufacturer: samsung, appium:deviceModel: SM-M045F, appium:deviceName: R9ZW90G00BX, appium:deviceScreenDensity: 300, appium:deviceScreenSize: 720x1600, appium:deviceUDID: R9ZW90G00BX, appium:javascriptEnabled: true, appium:locationContextEnabled: false, appium:networkConnectionEnabled: true, appium:newCommandTimeout: 1200, appium:pixelRatio: 1.875, appium:platformVersion: 14, appium:statBarHeight: 44, appium:takesScreenshot: true, appium:udid: R9ZW90G00BX, appium:uiautomator2ServerInstallTimeout: 300000, appium:viewportRect: {height: 1421, left: 0, top: 44, width: 720}, appium:warnings: {}, appium:webStorageEnabled: false, platformName: ANDROID}
Session ID: 15d22179-2250-40d7-a57c-048c5aff657e

Note: The issue is inconsistence. It's working fine with appium version 2.0.0 but not working with appium 2.2.1/2.11.0.

### Expected Behavior

androidDriver.location().getLongitude()/androidDriver.location().getLatitude() should give the proper value of device latitude and longitude.

### Minimal Reproducible Example

public void test4() {
		final double longitude = androidDriver.location().getLongitude();
		System.out.println(longitude);
	}

### Environment

- Operating system: Windows
- Appium server version (output of `appium --version`): 2.11.0
- Appium driver(s) and their version(s) (`appium driver list`): uiautomator2@2.34.1 [installed (npm)]
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`): v18.15.0
- `npm` version (output of `npm --version`): 9.5.0
- Last component(s) version which did _not_ exhibit the problem: 2.0.0
- Platform and version under test:
- Real device or emulator/simulator: Real Device

**Comment by mykola-mokhnach** [comment]
Please update UIA2 driver to the most recent version and try again.
If the location retrieval still does not work then please provide the device logcat output for the appropriate time range.

**Comment by najeer97** [comment]
It's working fine with latest UIA2 version, hence closing the issue.
Thank you.
