### ISSUE TITLE
[Feat]: Add to mobile:simctl command for appium-xcuitest-driver 

### ISSUE THREAD

**Issue by fleytman** [appium/appium#20481]
**Is your feature request related to a problem? Please describe.**
The built-in appium-xcuitest-driver commands are not always enough for custom actions. For example, there was a problem https://github.com/appium/appium/issues/18991 and I had to wait for the appium developers to fix it. At the moment, I need to run a custom simctl command, but it's not clear how to do this.

**Describe the solution you'd like**
1. I want commands similar to `mobile: shell` (for android adb) to appear, for example `mobile: simctl'`,`mobile: idb` that allow you to execute custom commands
2. I want this to be reflected in the documentation

**Describe alternatives you've considered**
For the idb, there is also no way to run custom commands, to fix this, my former colleague even developed his own client https://github.com/SergKhram/IdbClient . But it is unlikely that this tool will have support in the future. Moreover, it is not clear why to drag a separate client, when appium in fact already knows everything that is necessary

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-xcuitest-driver/pull/2461
