### ISSUE TITLE
Unable to get the button text after migrating the application from Xamarin to .NET MAUI

### ISSUE THREAD

**Issue by aabirdaneshyar** [appium/appium#20499]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After migrating the application from the Xamarin to .NET MAUI i am unable to get the button text on the Appium inspector. 
The text attribute is showing blank on the Appium inspector although the button text is present.
driver.getPagSource() is also returning text= "" for the button.
This happens for both Android and iOS versions of the application.

In the Xamarin version of the application I was able to get the button text on the Appium inspector. 

![Screenshot 2024-08-27 201506](https://github.com/user-attachments/assets/b153ad25-ad8b-4a0f-bca6-4fb7860c76cc)

### Expected Behavior

I should be able to get the button text on the Appium inspector for the .NET MAUI application. 

### Minimal Reproducible Example

**Steps to Reproduce:**
1. Launch the application
2. Inspect the Login button using the Appium inspector
3. Observe that the text attribute does not have a value 

### Environment

**Environment Details:**
Appium Version (java) - 9.30
Appium Sever version - 2.11.3
Appium Inspector version - 2024.6.1
XCUITest-driver version - 7.24.16
UIAutomator-driver version - 3.7.7
Android device - Samsung Galaxy Tab A9 (Android 14)
iOS device - iPad mini 6th Generation (iOS 16.4)

**Comment by eglitise** [comment]
The page source is returned by Google's UiAutomator / Apple's XCTest, which is outside Appium's control. I would advise contacting your application developers to add accessibility identifiers to this button according to the MAUI documentation.
