### ISSUE TITLE
[Feat]: Allow custom path for adb, android, emulator, and apkanalyzer.bat

### ISSUE THREAD

**Issue by RicardoBritoBrens** [appium/appium#20492]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated as a MAUI Android platform user that some tool require to download android studio when the tools to build the app and deploy are already downloaded by the visual studio IDE, in this case some tool like adb, android, emulator, and apkanalyzer.bat. are in different folders but appium does not have a way of set each individualy.

**Describe the solution you'd like**
it would be beneficial to have a way to specify the paths for the following tools: adb, android, emulator, and apkanalyzer.bat. This would avoid the need to download Android Studio and the same SDKs that are already installed when downloaded from Visual Studio.

**Comment by mykola-mokhnach** [comment]
I don't see a need in such feature. Google itself advices to use [sdkmanager](https://developer.android.com/tools/sdkmanager) command line tool, which does the same thing that the studio could do just via the command line.

**Comment by eglitise** [comment]
Indeed, the Appium documentation even mentions the option of using `sdkmanager` [in the quickstart](https://appium.io/docs/en/latest/quickstart/uiauto2-driver/#android-sdk).
