### ISSUE TITLE
bug: android app is not opening even that the appium server shows  200 OK

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#20504]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am launching the test with the following dc:
```
{'noReset': True, 'fullReset': False, 'appPackage': 'com.stanley.deployment', 'appActivity': 'com.stanley.deployment.view.MainActivity', 'udid': '36141JEHN03534', 'platformVersion': '14', 'automationName': 'UiAutomator2', 'uiautomator2ServerInstallTimeout': '120000', 'app': 'http://mv-nexus-new.corp.aeroscout.com:8081/repository/mobile-products/android/android-deployment-manager/securitas/latest/deployment-manager-debug.apk', 'platformName': 'Android'}
```
But the application is not launching, see linked appium server log

### Expected Behavior

Android app should be presented on the real Android pixel device

### Minimal Reproducible Example

Just call the following launch command:
```
self.driver_ = webdriver.Remote(
                    self.__appium_server_ip, options=self.__get_desired_capabilities_options__()
                )
```

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium v2.11.3
- Appium driver(s) and their version(s) (`appium driver list`):
- [Appium]   - uiautomator2@3.7.7 (automationName 'UiAutomator2')
[Appium]   - xcuitest@7.24.18 (automationName 'XCUITest')

- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):  v18.20.2
- 
- `npm` version (output of `npm --version`): 10.8.2
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Mac OS, version 14.6.1 (23G93
- Real device or emulator/simulator:Real device

### Link to Appium Logs

https://github.com/bwomsm1/AppiumLogs/blob/master/android.log

**Comment by mykola-mokhnach** [comment]
> [6c692f7b][AndroidUiautomator2Driver@7e5e] 'com.stanley.deployment' is already running and noReset is enabled. Set forceAppLaunch capability to true if the app must be forcefully restarted on session startup.


The above behaviour is expected. I don't see any issues with it

**Comment by bwomsm1** [comment]
@mykola-mokhnach like always, thanks for the quick response. 
It seems that adding `forceAppLaunch` as `true` solved the problem.
Thanks
