### ISSUE TITLE
Phone Call Audio Not Captured in Screen Recording

### ISSUE THREAD

**Issue by omercagriyilmaz** [appium/appium#20505]
Hello,

I am able to perform screen recording on Android devices using Appium, and I can also record both screen and sound. For example, when I start screen recording while playing a video on YouTube, I can hear the audio in the recording. However, I am unable to achieve the same result during a phone call. For instance, when I make a call from an Android phone, set the audio to speaker mode, and start recording, the voice of the person I'm calling is not captured in the video recording.

What could be the reason for this? Is there a different command in Appium for recording phone calls?

Thank you.

**Comment by mykola-mokhnach** [comment]
This is a usual Android security limitation. I don't see any possibilities of recording calls using available system APIs. Maybe it could be worked around via some custom setups, like recording from audio output or via bluetooth, although this is not something provided or supported by the UIA2 driver.

**Comment by omercagriyilmaz** [comment]
Thank you for your answer.
