### ISSUE TITLE
bug: Element not found if using a character like ° or accents

### ISSUE THREAD

**Issue by lhimo** [appium/appium#20503]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I try finding an element containing text with ° or accents, I get element not found.

### Expected Behavior

The element is found

### Minimal Reproducible Example

The error is not reproduced locally, only on our CI with Jenkins/Docker

### Environment

- Operating system: MacOS with appium installed through npm and docker running robot framework scripts
- Appium server version (output of `appium --version`): 2.11.3
- Appium driver(s) and their version(s) (`appium driver list`): xcuitest@7.24.18 and uiautomator2@3.7.7
- Appium plugin(s) and their version(s) (`appium plugin list`): none
- Node.js version (output of `node --version`): v22.7.0
- `npm` version (output of `npm --version`): 10.8.2
- Last component(s) version which did _not_ exhibit the problem: the same scripts running via VSCode
- Platform and version under test: Android 14 and iOS 17.5
- Real device or emulator/simulator: emulator/simulator

### Further Information

log of the error from Appium logs
```
[38;5;98m[124300d8][0m[38;5;198m[XCUITestDriver@8d32][0m Matched '/elements' to command name 'findElements'
[38;5;98m[124300d8][0m[38;5;198m[XCUITestDriver@8d32][0m Proxying [POST /elements] to [POST http://127.0.0.1:8120/session/87BC4940-78EE-488B-AD36-001B2037C7A8/elements] with body: {"using":"predicate string","value":"label contains \"Device n°\""}
[38;5;98m[124300d8][0m[38;5;198m[XCUITestDriver@8d32][0m Got response with status 400: {"value":{"error":"invalid argument","message":"Invalid locator requested: (null)","traceback":"(\n\t0   CoreFoundation                      0x00000001804ae0f8 __exceptionPreprocess + 172\n\t1   libobjc.A.dylib                     0x0000000180087db4 objc_exception_throw + 56\n\t2   WebDriverAgentLib                   0x00000001034e1e10 +[FBFindElementCommands elementsUsing:withValue:under:shouldReturnAfterFirstMatch:] + 1144\n\t3   WebDriverAgentLib                   0x00000001034e0d7c +[FBFindElementCommands handleFindElements:] + 256\n\t4   WebDriverAgentLib                   0x00000001034a50e4 -[FBRoute_TargetAction mountRequest:intoResponse:] + 168\n\t5   WebDriverAgentLib                   0x0000000103490538 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 404\n\t6   WebDriverAgentLib                   0x00000001034c7024 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t7   WebDriverAgentLib                   0x00000001034c7b14 __72-[RoutingHTTPServer routeMethod:withPath:paramet...
 [38;5;98m[124300d8][0m[38;5;123m[W3C][0m` Matched W3C error code 'invalid argument' to InvalidArgumentError
[38;5;98m[124300d8][0m[38;5;198m[XCUITestDriver@8d32][0m Responding to client with driver.findElements() result: []
```

**Comment by mykola-mokhnach** [comment]
The above error looks valid to me. XCUITest driver only supports following locator types: 
```
      'xpath',
      'id',
      'name',
      'class name',
      '-ios predicate string',
      '-ios class chain',
      'accessibility id',
      'css selector',
```

`predicate string` does not belong to the list

**Comment by mykola-mokhnach** [comment]
The exception is actually about unmatched locator strategy, not about the value.

I'm not sure why it happens though. According to the WDA logic this particular locator type, should be [handled properly](https://github.com/appium/WebDriverAgent/blob/fb7932255359460b6962b14abada08ca70333195/WebDriverAgentLib/Commands/FBFindElementCommands.m#L171), but it gets assigned to null instead. Are you sure the WebDriverAgent source did not get modified in any way?

**Comment by mykola-mokhnach** [comment]
> The error is not reproduced locally, only on our CI with Jenkins/Docker

If you use a cloud provider to run your CI tests then consider reporting a bug to them

**Comment by lhimo** [comment]
Sometimes in the Robot logs we get this message:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 6627: invalid continuation byte`

**Comment by mykola-mokhnach** [comment]
> Sometimes in the Robot logs we get this message: `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 6627: invalid continuation byte`

This error has nothing to do with the driver. It's either an issue in the client code or in the corresponding RF library

**Comment by amedvedjev** [comment]
Try use `normalizeTagNames` settings https://github.com/appium/appium-uiautomator2-driver

**Comment by mykola-mokhnach** [comment]
If this works locally but fails on the CI then try to figure out what's the difference there. Maybe the system/console locale is not setup properly or there was some other misconfig. I cannot reproduce this issue, so it rather looks like local-setup-related problem to me than a server issue.

**Comment by lhimo** [comment]
I reproduced it locally, will try to pinpoint exactly which version of appium is causing this for us (likely the latest one though).. the weird thing is that it doesn't happen on every session apparently.

**Comment by lhimo** [comment]
I noticed in the logs that the base driver is taken from the latest version, while I have running appium 2.10.3 so it should be linked to 9.10.3 I suppose?
```
Appium's BaseDriver version is 9.11.3
AndroidUiautomator2Driver's BaseDriver version is 9.11.3
```

**Comment by lhimo** [comment]
Is there any way to install a specific version of the base-driver instead of the latest one?

**Comment by lhimo** [comment]
Looks like it happens only after a few sessions, not on the first ones after an Appium server restart

**Comment by lhimo** [comment]
The issue seems to have been resolved on its own!

**Comment by ol-le** [comment]
The issue was also reproducible to me.

The issue might be related to the node.js encoding bug in 22.7.0
Upgrading to 22.9.0 helped to resolve it

See https://github.com/nodejs/node/issues/54543
