### ISSUE TITLE
Issue when running multiple tests sessions on iOS simulators/devices

### ISSUE THREAD

**Issue by dragos-panzaru-md** [appium/appium#20512]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Start appium server 2.11.3 with xcuitest driver 7.24.18, using command: appium --allow-cors --allow-insecure chromedriver_autodownload
Open a manual testing session on iOS Simulator (e.g. iPhone 15 simulator) using appium inspector
Go through different screens in the app and validate that page source refresh in appium inspector works ok.
Then run an automated test on different iOS Simulator (e.g iPhone 15 Pro simulator) or just open another manual session in appium inspector on a real device.
After the automated starts (you don't even have to wait for it to finish) or after the new manual session opens in appium inspector, if I go to the iPhone 15 simulator and go to another screen inside the app, then if I try to refresh the page it no longer works, and it looks like my initial session was killed, because a new one was opened (does webdriver agent not support more than one session in parallel???)

### Expected Behavior

Refresh page source in appium inspector should work as expected, even if I have more than one session opened with appium inspector or via code.

### Minimal Reproducible Example

Capabilities for manual test session on simulator:
{
  "platformName": "iOS",
  "appium:deviceName": "iPhone 15",
  "appium:newCommandTimeout": 360,
  "appium:platformVersion": "17.5",
  "appium:automationName": "XCUITest",
  "appium:ignoreUnimportantViews": false,
  "appium:app": "/Users/xyz/Desktop/APPS/app.zip",
  "appium:enableMultiWindows": true
}
Capabilities for automated test on simulator:
{
  "platformName": "iOS",
  "appium:deviceName": "iPhone 15 Pro",
  "appium:platformVersion": "17.5",
  "language": "en",
  "appium:automationName": "XCUITest",
  "appium:ignoreUnimportantViews": false,
  "appium:app": "/Users/xyz/Desktop/APPS/app.zip",
  "appium:enableMultiWindows": true,
  "appium:newCommandTimeout": 30000,
  "appium:appiumVersion": "latest",
  "appium:deviceOrientation": "portrait",
  "appium:autoAcceptAlerts": true
}
Capabilities for manual test session on real device:
{
  "platformName": "iOS",
  "appium:deviceName": "iPhone 11",
  "appium:newCommandTimeout": 360,
  "appium:platformVersion": "17.5.1",
  "appium:automationName": "XCUITest",
  "appium:ignoreUnimportantViews": false,
  "appium:udid": "auto",
  "appium:showXcodeLog": true,
  "appium:app": "/Users/xyz/Desktop/APPS/app.ipa",
  "appium:enableMultiWindows": true
}
Here is the error from the appium server logs, after  the second test session is opened and I try to refresh page source of first test session:
[de29c006][HTTP] --> GET /session/de29c006-f6fa-4363-8604-43ddae9459b0/timeouts {}
[de29c006][XCUITestDriver@f855] Calling AppiumDriver.getTimeouts() with args: ["de29c006-f6fa-4363-8604-43ddae9459b0"]
[de29c006][XCUITestDriver@f855] Executing command 'getTimeouts'
[de29c006][XCUITestDriver@f855] Responding to client with driver.getTimeouts() result: {"command":360000,"implicit":0}
[de29c006][HTTP] <-- GET /session/de29c006-f6fa-4363-8604-43ddae9459b0/timeouts 304 11 ms - -
[de29c006][HTTP] --> GET /session/de29c006-f6fa-4363-8604-43ddae9459b0/screenshot {}
[de29c006][XCUITestDriver@f855] Calling AppiumDriver.getScreenshot() with args: ["de29c006-f6fa-4363-8604-43ddae9459b0"]
[de29c006][XCUITestDriver@f855] Executing command 'getScreenshot'
[de29c006][XCUITestDriver@f855] Taking screenshot with WDA
[de29c006][XCUITestDriver@f855] Matched '/screenshot' to command name 'getScreenshot'
[de29c006][XCUITestDriver@f855] Proxying [GET /screenshot] to [GET http://127.0.0.1:8100/session/7F34E120-A38C-4814-A114-529725BC10B5/screenshot] with no body
[de29c006][XCUITestDriver@f855] Got response with status 404: {"value":{"error":"invalid session id","message":"Session does not exist","traceback":"(\n\t0   CoreFoundation                      0x00000001804ae0f8 __exceptionPreprocess + 172\n\t1   libobjc.A.dylib                     0x0000000180087db4 objc_exception_throw + 56\n\t2   CoreFoundation                      0x00000001804adc9c -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x00000001091b7e54 -[FBRoute raiseNoSessionException] + 80\n\t4   WebDriverAgentLib                   0x00000001091b7da8 -[FBRoute decorateRequest:] + 244\n\t5   WebDriverAgentLib                   0x00000001091b7248 -[FBRoute_TargetAction mountRequest:intoResponse:] + 92\n\t6   WebDriverAgentLib                   0x00000001091a0dac __37-[FBWebServer registerRouteHandlers:]_block_invoke + 404\n\t7   WebDriverAgentLib                   0x00000001091d91d4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t8   WebDriverAgentLib                   0x00000001091d9cc4 __72-[RoutingHTTPServer routeMethod:withPath...
[de29c006][W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
[de29c006][XCUITestDriver@f855] Error getting screenshot: Session does not exist
[de29c006][XCUITestDriver@f855] Falling back to 'simctl io screenshot' API
[de29c006][XCUITestDriver@f855] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABJsAAAn8CAYAAABF0eA/AAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAEm6ADAAQAAAABAAAJ/AAAAAD60AIQAABAAElEQVR4AezdB2AUVf7A8V9CQugl9CIdBKWJomDvXdFT7L2hd2c9/+edZ9fTK97ZTrEdZzv17F2xYkFRUBFRQZEmvYQOCSTh/34TJpnszmSzye7s7Mz33Y27O+XNe59ZJru/fSVHBl2xVUgIIIAAAggggAACCCCAAAIIIIAAAgikQCA3BXmQBQIIIIAAAggggAACCCCAAAIIIIAAApYAwSbeCAgggAACCCCAAAIIIIAAAggggAACKRMg2JQySjJCAAEEEEAAAQQQQAABBBBAAAEEECDYxHsAAQQQQAABBBBAAAEEEEAAAQQQQCBlAgSbUkZJRggggAACCCCAAAIIIIAAAggggAACBJt4DyCAAAIIIIAAAggggAACCCCAAAIIpEyAYFPKKMkIAQQQQAABBBBAAAEEEEAAAQQQQIBgE+8BBBBAAAEEEEAAAQQQQAABBBBAAIGUCRBsShklGSGAAAIIIIAAAggggAACCCCAAAIIEGziPYAAAggggAACCCCAAAIIIIAAAgggkDIBgk0poyQjBBBAAAEEEEAAAQQQQAABBBBAAAGCTbwHEEAAAQQQQAABBBBAAAEEEEAAAQRSJkCwKWWUZIQAAggggAACCCCAAAIIIIAAAgggQLCJ9wACCCCAAAIIIIAAAggggAACCCCAQMoECDaljJKMEEAAAQQQQAABBBBAAAEEEEAAAQQINvEeQAABBBBAAAEEEEAAAQQQQAABBBBImQDBppRRkhECCCCAAAIIIIAAAggggAACCCCAAMEm3gMIIIAAAggggAACCCCAAAIIIIAAAikTINiUMkoyQgABBBBAAAEEEEAAAQQQQAABBBAg2MR7...
[de29c006][HTTP] <-- GET /session/de29c006-f6fa-4363-8604-43ddae9459b0/screenshot 200 455 ms - 388196
[de29c006][HTTP] --> GET /session/de29c006-f6fa-4363-8604-43ddae9459b0/window/rect {}
[de29c006][XCUITestDriver@f855] Calling AppiumDriver.getWindowRect() with args: ["de29c006-f6fa-4363-8604-43ddae9459b0"]
[de29c006][XCUITestDriver@f855] Executing command 'getWindowRect'
[de29c006][XCUITestDriver@f855] Proxying [GET /window/size] to [GET http://127.0.0.1:8100/session/7F34E120-A38C-4814-A114-529725BC10B5/window/size] with no body
[de29c006][XCUITestDriver@f855] Got response with status 404: {"value":{"error":"invalid session id","message":"Session does not exist","traceback":"(\n\t0   CoreFoundation                      0x00000001804ae0f8 __exceptionPreprocess + 172\n\t1   libobjc.A.dylib                     0x0000000180087db4 objc_exception_throw + 56\n\t2   CoreFoundation                      0x00000001804adc9c -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x00000001091b7e54 -[FBRoute raiseNoSessionException] + 80\n\t4   WebDriverAgentLib                   0x00000001091b7da8 -[FBRoute decorateRequest:] + 244\n\t5   WebDriverAgentLib                   0x00000001091b7248 -[FBRoute_TargetAction mountRequest:intoResponse:] + 92\n\t6   WebDriverAgentLib                   0x00000001091a0dac __37-[FBWebServer registerRouteHandlers:]_block_invoke + 404\n\t7   WebDriverAgentLib                   0x00000001091d91d4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t8   WebDriverAgentLib                   0x00000001091d9cc4 __72-[RoutingHTTPServer routeMethod:withPath...
[de29c006][W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
[de29c006][XCUITestDriver@f855] Encountered internal error running command: NoSuchDriverError: Session does not exist
    at errorFromW3CJsonCode (/Users/dragos.panzaru/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)
    at ProxyRequestError.getActualError (/Users/dragos.panzaru/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)
    at JWProxy.command (/Users/dragos.panzaru/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:353:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at XCUITestDriver.proxyCommand (/Users/dragos.panzaru/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)
    at XCUITestDriver.getWindowSizeNative (/Users/dragos.panzaru/.appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:277:12)
    at XCUITestDriver.getWindowSize (/Users/dragos.panzaru/.appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:52:14)
    at XCUITestDriver.getWindowRect (/Users/dragos.panzaru/.appium/node_modules/appium-xcuitest-driver/lib/commands/general.js:121:29)
[de29c006][HTTP] <-- GET /session/de29c006-f6fa-4363-8604-43ddae9459b0/window/rect 404 35 ms - 1251
[de29c006][HTTP] --> GET /session/de29c006-f6fa-4363-8604-43ddae9459b0/source {}
[de29c006][XCUITestDriver@f855] Calling AppiumDriver.getPageSource() with args: ["de29c006-f6fa-4363-8604-43ddae9459b0"]
[de29c006][XCUITestDriver@f855] Executing command 'getPageSource'
[de29c006][XCUITestDriver@f855] Matched '/source?format=xml&scope=AppiumAUT' to command name 'getPageSource'
[de29c006][XCUITestDriver@f855] Proxying [GET /source?format=xml&scope=AppiumAUT] to [GET http://127.0.0.1:8100/session/7F34E120-A38C-4814-A114-529725BC10B5/source?format=xml&scope=AppiumAUT] with no body
[de29c006][XCUITestDriver@f855] Got response with status 404: {"value":{"error":"invalid session id","message":"Session does not exist","traceback":"(\n\t0   CoreFoundation                      0x00000001804ae0f8 __exceptionPreprocess + 172\n\t1   libobjc.A.dylib                     0x0000000180087db4 objc_exception_throw + 56\n\t2   CoreFoundation                      0x00000001804adc9c -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x00000001091b7e54 -[FBRoute raiseNoSessionException] + 80\n\t4   WebDriverAgentLib                   0x00000001091b7da8 -[FBRoute decorateRequest:] + 244\n\t5   WebDriverAgentLib                   0x00000001091b7248 -[FBRoute_TargetAction mountRequest:intoResponse:] + 92\n\t6   WebDriverAgentLib                   0x00000001091a0dac __37-[FBWebServer registerRouteHandlers:]_block_invoke + 404\n\t7   WebDriverAgentLib                   0x00000001091d91d4 -[RoutingHTTPServer handleRoute:withRequest:response:] + 168\n\t8   WebDriverAgentLib                   0x00000001091d9cc4 __72-[RoutingHTTPServer routeMethod:withPath...
[de29c006][W3C] Matched W3C error code 'invalid session id' to NoSuchDriverError
[de29c006][XCUITestDriver@f855] Encountered internal error running command: NoSuchDriverError: Session does not exist
    at errorFromW3CJsonCode (/Users/dragos.panzaru/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)
    at ProxyRequestError.getActualError (/Users/dragos.panzaru/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)
    at JWProxy.command (/Users/dragos.panzaru/.appium/node_modules/appium-xcuitest-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:353:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at XCUITestDriver.proxyCommand (/Users/dragos.panzaru/.appium/node_modules/appium-xcuitest-driver/lib/commands/proxy-helper.js:103:35)
    at XCUITestDriver.mobileGetSource (/Users/dragos.panzaru/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:50:35)
    at XCUITestDriver.getPageSource (/Users/dragos.panzaru/.appium/node_modules/appium-xcuitest-driver/lib/commands/source.js:25:9)
[de29c006][HTTP] <-- GET /session/de29c006-f6fa-4363-8604-43ddae9459b0/source 404 9 ms - 1107
[de29c006][HTTP] --> GET /session/de29c006-f6fa-4363-8604-43ddae9459b0/timeouts {}
[de29c006][XCUITestDriver@f855] Calling AppiumDriver.getTimeouts() with args: ["de29c006-f6fa-4363-8604-43ddae9459b0"]
[de29c006][XCUITestDriver@f855] Executing command 'getTimeouts'
[de29c006][XCUITestDriver@f855] Responding to client with driver.getTimeouts() result: {"command":360000,"implicit":0}
[de29c006][HTTP] <-- GET /session/de29c006-f6fa-4363-8604-43ddae9459b0/timeouts 304 15

### Environment

- Operating system: macOS Sonoma 14.5
- Appium server version (output of `appium --version`): 2.11.3
- Appium driver(s) and their version(s) (`appium driver list`): xcuitest 7.24.18
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`): 20.15.1
- `npm` version (output of `npm --version`): 10.7.0
- Last component(s) version which did _not_ exhibit the problem: always encountered this issue
- Platform and version under test: iOS 17.5 (I don't believe the iOS version is the issue because same behavior occurred for older iOS versions also)
- Real device or emulator/simulator: it happens on simulator, 

### Further Information

I tried also opening two instances of appium server on different ports and open first session on first appium server and the second on the other appium server instance, and the problem still occurs.

**Comment by dragos-panzaru-md** [comment]
After In the first test session I can no longer refresh the page source from appium inspector, and with the second test session opened on real device, if I close first test session and try to start again a test session with same capabilities I get this:
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session. Original error: A new session could not be created. Details: Error Domain=FBSOpenApplicationServiceErrorDomain Code=4 "The request to open "digital.x.y.z.dev" failed." UserInfo={BSErrorCodeDescription=InvalidRequest, NSLocalizedDescription=The request to open "digital.x.y.z.dev" failed., FBSOpenApplicationRequestID=0x7ae2, NSUnderlyingError=0x300c94960 {Error Domain=FBSOpenApplicationErrorDomain Code=4 "Application info provider (FBSApplicationLibrary) returned nil for "digital.x.y.z.dev"" UserInfo={BSErrorCodeDescription=NotFound, NSLocalizedFailureReason=Application info provider (FBSApplicationLibrary) returned nil for "digital.x.y.z.dev"}}}

**Comment by mykola-mokhnach** [comment]
> (does webdriver agent not support more than one session in parallel???)

Definitely not on the same device. Only one session could be running at the same time. If a second one is opened while the previous one is active then WDA will kill the previous session automatically.

**Comment by dragos-panzaru-md** [comment]
I was referring to having more than one session on same appium server instance, but on different devices/simulators. But I am guessing that it does not work to have this on same appium server instance, but rather I would need two appium server instances running on different ports, and also with different webdriveragent ports set. @mykola-mokhnach Can you confirm this is the case?

**Comment by mykola-mokhnach** [comment]
It is also possible using the same server instance. You just need to make sure there are no port conflicts. Check https://github.com/appium/appium-xcuitest-driver/blob/master/docs/guides/parallel-tests.md

**Comment by dragos-panzaru-md** [comment]
@mykola-mokhnach Ok. So I read the documentation from your link, but there are a few things still unclear for me:
1. If you have one server instance, doesn't it use by default port 8100 for wda? If so, if I use a server instance started without specifying a custom wda port, can I just put in the capabilities of one session port 8100 for wda and for another session on same appium server put port 8200, for example, and both will run ok?
2. What value should I specify in the capabilities for "derivedDataPath"? Can you give me an example, since there aren't any on the documentation page?
Thanks in advance.
P.S.: What I managed to do so far to get a working setup the allows me to test the app manually while also running automated tests locally on simulators is this:
I have two appium server instances, one started without specifying wda port (which means it will use default wda port 8100), and another started with '-driver-xcuitest-webdriveragent-port 8200 -p 4727', which will use port 8200 for wda
The automated tests I now run on the second instance and the manual testing sessions I start from appium inspector using the first appium server instance

**Comment by mykola-mokhnach** [comment]
> 1. If you have one server instance, doesn't it use by default port 8100 for wda? If so, if I use a server instance started without specifying a custom wda port, can I just put in the capabilities of one session port 8100 for wda and for another session on same appium server put port 8200, for example, and both will run ok?

I don't see any problems with that. Just make sure these two sessions run on different devices

> What value should I specify in the capabilities for "derivedDataPath"? Can you give me an example, since there aren't any on the documentation page?

Any unique empty local folder. This folder is used by xcodebuild to keep the compiled WDA application. See https://stackoverflow.com/questions/33044633/command-line-option-to-change-xcode-deriveddata-location
This folder may be reused afterwards if the session is executed for the same device

**Comment by dragos-panzaru-md** [comment]
@mykola-mokhnach Is there somewhere written what is the default derived data path, if I don't specify it myself?

**Comment by dragos-panzaru-md** [comment]
@mykola-mokhnach Follow-up question: if I used a directory for derived data path of a specific device/simulator, I can re-use it even if the iOS version changed on that device/simulator?

**Comment by KazuCocoa** [comment]
> Is there somewhere in the documentation written what is the default derived data path

It depends on Xcode itself, so by Apple. It is usually something like `/Users/<user>/Library/Developer/Xcode/DerivedData/<scheme name and random value>`. Appium lets you specify the path with `appium:derivedDataPath`.

> even if the iOS version changed on that device/simulator?

It could depend on xcodebuild by Apple. My experience is limited, but if you would like to run parallel session on a host, it is safe to have the path per session.
https://appium.github.io/appium-xcuitest-driver/latest/guides/parallel-tests/

**Comment by dragos-panzaru-md** [comment]
@mykola-mokhnach @KazuCocoa Thank for your help. Will close this issue since I managed to run test sessions in parallel. As a side note, both approaches work, meaning using just one server instance, but specifying different wda port and derived data path, or multiple server instances started on different ports with specifying different wda port via `-driver-xcuitest-webdriveragent-port` command line argument
