### ISSUE TITLE
Can not find any way to differentiate between visible and not visible elements in an android screen

### ISSUE THREAD

**Issue by dragos-panzaru-md** [appium/appium#20516]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have one toggle that is visible only if I click another button in the page. However, that toggle will actually be visible only for a few seconds after which it disappears, although in the appium page source, the toggle is rendered as an element, no matter if you click the button or not.
Because of the fact the element is rendered in the page, no matter if it is actually visible or not, the click action on the element will not throw any exception, even if the toggle is not visible (for some reason, all elements in android page source have 'displayed' attribute set to "true", even if they are not actually visible to the human eye).
This situation causes issues for me, in the sense that I can not differentiate between the situation when the enabling of the toggle did not succeed because of a bug that doesn't allow me to enable the toggle, or just because the click was performed after the toggle disappeared from the screen (although, still existing in the appium page source xml).
Also, using tap by coordinates instead of click does not help in any way, since the tap may also occur after the element is no longer visible to the human eye, which of often occurs when running test on test platform, like Saucelabs.

### Expected Behavior

There should be a way to differentiate between the situation when an element (that appears in the appium page source, no matter what) is visible to the human eye and the situation when it is not visible to the human eye.
On iOS, for this situation, the 'visible' attribute works just fine, but on android, however, the 'displayed' doesn't help me at all, since it is always set to 'true'

### Minimal Reproducible Example

Capabilities for manual test session on simulator:
{
  "platformName": "Android",
  "appium:platformVersion": "12",
  "appium:automationName": "UiAutomator2",
  "appium:ignoreUnimportantViews": false,
  "appium:app": "/Users/xyz/Desktop/APP/latest.apk",
  "appium:appActivity": "x.y.z.Activity",
  "appium:appWaitActivity": "x.y.z.Activity",
  "appium:disableIdLocatorAutocompletion": true,
  "appium:enableMultiWindows": true
}

### Environment

- Operating system: macOS Sonoma 14.5
- Appium server version (output of `appium --version`): 2.11.3
- Appium driver(s) and their version(s) (`appium driver list`): uiautomator2 3.7.7
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`): 20.15.1
- `npm` version (output of `npm --version`): 10.7.0
- Last component(s) version which did _not_ exhibit the problem: always encountered this issue
- Platform and version under test: any emulator or real device with android that supports uiautomator2 driver
- Real device or emulator/simulator: both

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing that could be done from UIA2 driver side. The "displayed" attribute is retrieved from the accessibility layer, and this layer gets this data from the particular application. See https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo

Closed as third party issue.
