### ISSUE TITLE
bug: MJPEG server isn't running

### ISSUE THREAD

**Issue by ekiwi111** [appium/appium#20521]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

MJPEG server isn't running. Getting:
```
Error getting MJpeg screenshot chunk: connect ECONNREFUSED 127.0.0.1:9100
```

### Expected Behavior

MJPEG server runs

### Minimal Reproducible Example

Fresh install of Appium and Appium Inspector. Capabilities:
```
{
  "platformName": "iOS",
  "appium:deviceName": "iPhoneDeviceName",
  "appium:udid": "00000000-00ABCABCABC",
  "appium:platformVersion": "18.0",
  "appium:bundleId": "com.org.Cal_v1",
  "appium:automationName": "XCUITest",
  "appium:xcodeOrgId": "ORGID",
  "appium:xcodeSigningId": "Apple Development",
  "appium:mjpegServerPort": 9100,
  "appium:mjpegScreenshotUrl": "http://127.0.0.1:9100"
}
```

Running appium with: 
```
appium server --use-plugins images
```
Running xcodebuild with: 
```
xcodebuild -project "/Users/USER/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj" -scheme WebDriverAgentRunner -destination "id=$(idevice_id -l | head -n1)" test
```

### Environment

- Operating system: 
```
MacOS Sonoma 14.6.1 (23G93)
```
- Appium server version (output of `appium --version`): 
```
2.0.1
```
- Appium driver(s) and their version(s) (`appium driver list`):
```
✔ Listing available drivers
- uiautomator2@3.7.8 [installed (npm)]
- xcuitest@7.25.0 [installed (npm)]
- espresso@3.3.1 [installed (npm)]
- mac2 [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]
```
- Appium plugin(s) and their version(s) (`appium plugin list`):
```
✔ Listing available plugins
- images@3.0.18 [installed (npm)]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]
```
- Node.js version (output of `node --version`):
```
v18.18.2
```
- `npm` version (output of `npm --version`):
```
10.2.1
```
- Last component(s) version which did _not_ exhibit the problem: N/A, fresh install
- Platform and version under test: N/A
- Real device or emulator/simulator: 
```
iPhone 7 - iOS 15.8.3
iPhone XS Max - iOS 18.0
```

### Link to Appium Logs

https://gist.github.com/ekiwi111/dbaa09ef114eddfbc0d64991ff5208a0

**Comment by KazuCocoa** [comment]
How did you do port-forward to the port 9100? Perhaps it works if you set the device's ip address over wifi instead of `127.0.0.1` right now or add port-forward to the port by yourself. Appium's `appium:mjpegScreenshotUrl` itself does not handle port-forward. Appium just tries to listen to the given url.
https://github.com/appium/appium/blob/7fe67a286a15a917ce3b1b47a08e982e65bbd9e4/packages/support/lib/mjpeg.js#L33
https://github.com/appium/appium-xcuitest-driver/blob/1af61e5cd54cf8748b8be6263778666540f749e9/lib/driver.js#L463

**Comment by ekiwi111** [comment]
hey @KazuCocoa
> Perhaps it works if you set the device's ip address over wifi instead of 127.0.0.1 right now
Yeah, you are right, I completely missed that, works now!
