### ISSUE TITLE
Bug in Appium App: Delete Cache in Appium Settings

### ISSUE THREAD

**Issue by ichman** [appium/appium#20526]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A toaster is displayed on the device with the message Delete Cache in Appium Settings (cf screenshot)
<img width="422" alt="Capture d’écran 2024-09-03 à 08 35 46" src="https://github.com/user-attachments/assets/803c2ea6-9499-404c-b777-6233c7c048de">

### Expected Behavior

Not have this toaster displayed

### Minimal Reproducible Example

it seems that the error appears at the launch of the appium app. 

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by eglitise** [comment]
Please fill out the issue details about your environment, and provide your full Appium log.

**Comment by ichman** [comment]
[Appium_logs.txt](https://github.com/user-attachments/files/16849905/Appium_logs.txt)

 find attached the Appium logs
 Env: nodejs / webdriverio / browserstack

**Comment by mykola-mokhnach** [comment]
> 2024-09-03 08:42:14:387 - [Appium] Appium v1.17.0 creating new AndroidUiautomator2Driver (v1.46.0) session


this version is old and is not supported anymore. Consider using the most recent server and driver versions.
