### ISSUE TITLE
Appium ignores webview version and keep using chrome version to start chromedriver

### ISSUE THREAD

**Issue by afathonih** [appium/appium#20536]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given AUT has both chrome webview UI and system webview UI. Appium keep starting chromedriver based on  chrome version instead of system webview version when switching context to system webview.

### Expected Behavior

Appium choose the correct chromedriver version. In this case based on system webview version. 

### Minimal Reproducible Example

First: switch context to `webview_chrome`.
Then, Switch to `webview_aut_package_name`.

### Environment

- Operating system:
- Appium server version (output of `appium --version`):2.11.3
- Appium driver(s) and their version(s) (`appium driver list`):

- uiautomator2@2.34.1 [installed (npm)]
- xcuitest@5.8.2 [installed (npm)]
- espresso@2.29.2 [installed (npm)]
- mac2 [not installed]
- windows [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]
- Appium plugin(s) and their version(s) (`appium plugin list`):

- appium-dashboard@v2.0.2 [installed (npm)]
- images@3.0.3 [installed (npm)]
- device-farm@8.4.7-rc.5 [installed (linked from /Users/ci/Github/appium-device-farm)]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]- Node.js version (output of `node --version`): v22.7.0
- `npm` version (output of `npm --version`): 10.8.2
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Android 12
- Real device or emulator/simulator: Real device

### Link to Appium Logs

https://gist.github.com/afathonih/d971b6dada531e3f824ca89742163357

**Comment by mykola-mokhnach** [comment]
I am not quite sure how it would be possible to know the destination web view version is advance in such case...

**Comment by mykola-mokhnach** [comment]
I can also observe that pretty old driver versions are used. Make sure they are up to date.

**Comment by afathonih** [comment]
@mykola-mokhnach  I downgraded the chrome version just to make it easy to reproduce the issue.
The android sytem webview version can be obtained by the following command:  `adb shell dumpsys webviewupdate`.
Which will return as follows for the same deviceas above :
Current WebView Update Service state
  Multiprocess enabled: true
  Current WebView package (name, version): (com.google.android.webview.beta, 129.0.6668.9)
  Minimum targetSdkVersion: 31
  Minimum WebView version code: 500512533
  Number of relros started: 2
  Number of relros finished: 2
  WebView package dirty: false
  Any WebView package installed: true
  Preferred WebView package (name, version): (com.google.android.webview.beta, 129.0.6668.9)
  WebView packages:
    Valid package com.google.android.webview (versionName: 127.0.6533.103, versionCode: 653310333, targetSdkVersion: 35) is  installed/enabled for all users
    Valid package com.google.android.webview.beta (versionName: 129.0.6668.9, versionCode: 666800933, targetSdkVersion: 35) is  installed/enabled for all users
    com.google.android.webview.dev is NOT installed.
    com.google.android.webview.canary is NOT installed.
    com.google.android.webview.debug is NOT installed.
    com.android.webview is NOT installed.

Maybe we can use this version to start chromedriver when the webview name matches AUT package name? I'm not sure about backward compatibility against other webview backend tho.

**Comment by KazuCocoa** [comment]
Could you share the full Appium log as well to track logs? Then, it would be appreciated if you could share the result of https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-getcontexts as well.


I tried to reproduce the error case with our https://github.com/appium/android-apidemos under `com.android.chrome` 120.0.6099.193 and `om.google.android.webvie` 127.0.6533.64 emulator environment.

Then, switch to `WEBVIEW_chrome ` and `WEBVIEW_io.appium.android.apis` both worked. 

https://gist.github.com/KazuCocoa/6812cfb3704267caeb215387dc6fb5d5

If this was only on real devices, then I'll try it out, but I guess this is not device-specific but installed web view combination related.

**Comment by mykola-mokhnach** [comment]
Closed because of no response.
