### ISSUE TITLE
iOS string with accented characters can be found, but cannot be clicked

### ISSUE THREAD

**Issue by tking16** [appium/appium#20538]
I have some tests that require me to click on a Podcast with the title: `'Then & Now with Babatúndé and Leonie Aléshé'`. Finding the element works perfectly. But running a `click` event on it won't fail or present an error, however it will not click on the element! So the test will continue as if it did and fail. Similar elements with no accent characters work perfectly

Logs from click event:
[click.log](https://github.com/user-attachments/files/16886434/click.log)

Appium version: v2.5.4
xcuitest version: 4.35.0
Python: v3.9

**Comment by mykola-mokhnach** [comment]
Clicks are performed by XCTest itself. There is nothing we could do to change that behaviour. You may try to click by coordinates as a possible workaround

**Comment by tking16** [comment]
Is there a simple way to do that without using ActionChain?

**Comment by tking16** [comment]
Tried making a new function. This is scrolling the screen and then clicking instead of the moving the "mouse" to that specified location and then clicking. When `pause()` is not included the command does nothing

```
    def tap_coordinate(self, el):
        """
        Tap a specific point on the page rather than relying on finding an element
        Only recommended for extreme edge cases
        """
        actions = ActionChains(self._driver)
        actions.w3c_actions = ActionBuilder(self._driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
        actions.w3c_actions.pointer_action.move_to_location(x=page_x, y=page_y).pause(3).click()
        actions.perform()
```

There's no easy to find documentation on this ActionChain stuff so just an awful experience overall whenever I try to use it

**Comment by KazuCocoa** [comment]
Didn't https://github.com/appium/python-client?tab=readme-ov-file#multiactiontouchaction-to-w3c-actions help in the client's README?
Or you could use https://appium.github.io/python-client-sphinx/webdriver.extensions.html#webdriver.extensions.action_helpers.ActionHelpers.tap instead. It wraps the w3c actions.

It is appreciated to contribute documentation if you have a good idea to improve them.

**Comment by tking16** [comment]
Thank you @KazuCocoa That's helped me in the past. Completely forgot about it. And the ReadMe never showed up no matter how varied google searches I put in. 

My one suggestion is the Action Helper stuff could have it's own dedicated page in https://appium.io/docs/en/2.0/

**Comment by KazuCocoa** [comment]
I see. Thanks.
I'm wondering if we have a better method to let Google search create index README etc well. It looks like... if this indexing is improved, decentralizing docs will work better as well, I guess.

**Comment by KazuCocoa** [comment]
Btw, copilot from MS's bing search also show me code below with "writing clicking a coordinate with W3C actions," something like this prompt. It would also help.

x = 100
y = 200

# Create a pointer input instance
pointer = PointerInput(Interaction.POINTER_TOUCH, "finger")

# Create an action sequence
actions = ActionBuilder(driver, mouse=pointer)
actions.pointer_action.move_to_location(x, y)
actions.pointer_action.pointer_down()
actions.pointer_action.pointer_up()

# Perform the action
actions.perform()
