### ISSUE TITLE
bug: If a 'newSession' request specifies both 'appium:app' and 'browserName', the specified application should take precedence

### ISSUE THREAD

**Issue by sbabcoc** [appium/appium#20533]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This bug relates to https://github.com/SeleniumHQ/selenium/issues/14216
Currently, the standard behavior in Selenium **RelaySessionFactory** is to merge defined node capabilities with requested capabilities before forwarding the `newSession` request to the endpoint node. A change was applied in the session factory to explicitly filter out the browser name, but handling of vendor-specific capabilities should be performed by the endpoint node instead of applying special-case handling in the intermediary. In this case, the specified application should take precedence over the browser name.

### Expected Behavior

When processing the `newSession` request, `appium:app` should take precedence over `browserName`.

### Minimal Reproducible Example

https://github.com/SeleniumHQ/selenium/issues/14216

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Link to Appium Logs

https://github.com/SeleniumHQ/selenium/issues/14216

**Comment by mykola-mokhnach** [comment]
Not sure what is meant under "take precedence" . Both XCUITest and UIA2 drivers currently assume this is a request for a hybrid chrome/safari session if browserName is provided. Changing that behaviour would be a major breaking change on both server and client side.

@jlipps @KazuCocoa What do you think?

**Comment by KazuCocoa** [comment]
Agree with the major breaking change thing. 

I'm not so familiar with the combination of via grid, but https://github.com/SeleniumHQ/selenium/issues/14216 behavior explained `stereotype` added the `browserName` for all nodes. Probably... ideally the grid needs to be configured which node wants to not add `browserName` etc...? So this is... maybe how to let grid proxy requests to the registered node.

**Comment by jlipps** [comment]
I assume the OP means that if both `appium:app` and `browserName` caps are included, that Appium should obey `appium:app` and ignore `browserName`.

I guess I'm not following why the user should just avoid using both at the same time?

**Comment by mykola-mokhnach** [comment]
I don't think we want to do any changes to the current behaviour, thus closing
