### ISSUE TITLE
[Feat]:how to impletement screen split in appium

### ISSUE THREAD

**Issue by fancy45daddy** [appium/appium#20549]
![Screenshot_20240907-233548](https://github.com/user-attachments/assets/d1458b51-6534-4ecc-8c39-c95a13a730af)
 
You can see from the attachment. I want to split the screen into above and below half. One half to run one app. But both of them are in the same screen. I have no idea how to implement in appium webdriverio. Could you give me a mininum working example. 

I try to do that in the browserstack platform to use the following code.

import * as webdriverio from 'webdriverio'
import * as commander from '/usr/share/nodejs/commander/esm.mjs'

commander.program.requiredOption('--browserstackName <>').requiredOption('--browserstackKey <>')
commander.program.parse()
const opts =
{
    protocol:'https',
    hostname:'hub-cloud.browserstack.com',
    path:'/wd/hub',
    user:commander.program.opts().browserstackName,
    key:commander.program.opts().browserstackKey,
    capabilities:
    {
        device:'Google Pixel 7',
        os_version:'13.0',
        app:'bs://sample.app',
        autoGrantPermissions:true,
        interactiveDebugging:true,
        enableMultiWindows:true,
        'browserstack.idleTimeout':'300'
    }
}
const client = await webdriverio.remote(opts)
await client.startActivity('com.android.chrome', 'com.google.android.apps.chrome.Main')
//console.log(await client.getContexts())
await client.switchContext('WEBVIEW_chrome')
await client.url('https://www.dailymotion.com/video/x87ytjz') //https://www.zenrows.com/blog/perimeterx-bypass#how-perimeterx-work
globalThis.setInterval(async () => await client.execute(() => globalThis.document.title), 1000 * 30)
await client.startActivity('com.android.chrome', 'com.google.android.apps.chrome.Main')
await client.switchContext('WEBVIEW_chrome')
await client.url('https://www.dailymotion.com/video/x87ytjz') //https://www.zenrows.com/blog/perimeterx-bypass#how-perimeterx-work

But I never success. I just can see one screen and one app.

I try to ask the question in appium forum. But I never receive conformation letter. So I ask the question here. Thank you

**Comment by jlipps** [comment]
I don't think Appium has any special facility for triggering a split screen mode. Try to emulate what a user would do to put apps into split screen instead.

**Comment by fancy45daddy** [comment]
i just know how to do split screen manually, but it is difficult do that in automatic test. any one know how to do split screen in adb？
