### ISSUE TITLE
bug: iOS system elements are not visible and i can't interact with them while running a test on latest appium and xcuitest driver

### ISSUE THREAD

**Issue by eplamadeala-ellation** [appium/appium#20543]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've updated to the latest Appium 2.11.3 and XCUItest driver 7.26.0. I am testing a streaming app and I have some tests that require interaction with the control center on iOS, after the update Appium can't find the elements for the control center if my app is running. It's not an app issue as I tried with previous versions that I know worked fine. 
See screenshots:
With app running:
<img width="1096" alt="SCR-20240906-lauy" src="https://github.com/user-attachments/assets/4dc35233-95c9-4874-bd07-c87b2b4a549d">

With app in background:
<img width="1092" alt="SCR-20240906-lbdn" src="https://github.com/user-attachments/assets/b5afc142-b40c-47fd-b4bf-cc46791cb6e2">

 Also when I downgraded the XCUItest driver to 5.16.1 the elements from the control center are visible and I can interact with them while my app is running, but I get another issue:
 
![2024-09-06 12 11 03](https://github.com/user-attachments/assets/3280d802-8981-4652-aa79-f01de9aef64c)

Any help will be useful, as i am trying to figure out this for the past 4-5 days.

### Expected Behavior

Should be able to see the system elements and interact with them

### Environment

- Operating system: iOS
- Appium server version (output of `appium --version`): 2.11.3, 2.11.2
- Appium driver(s) and their version(s) (`appium driver list`): 7.26.0, 7.25.0
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`): v22.8.0
- `npm` version (output of `npm --version`): 10.8.3
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS 17.6.1, 16.6.1, 18.0 beta
- Real device or emulator/simulator: Real Device

### Link to Appium Logs

https://gist.github.com/eplamadeala-ellation/cebe19c1987bfecba6f4e65d37d84ded

**Comment by mykola-mokhnach** [comment]
You need to explicitly activate the springboard app in order to interact with it. See https://github.com/appium/appium-xcuitest-driver/blob/master/docs/guides/troubleshooting.md#interact-with-dialogs-managed-by-comapplespringboard for more details

**Comment by mykola-mokhnach** [comment]
closed as not an issue
