### ISSUE TITLE
一直弹出很多信息，我重新安装了都没有用

### ISSUE THREAD

**Issue by heliqingshidasheng** [appium/appium#20542]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![微信图片_20240906165654](https://github.com/user-attachments/assets/b737b4d2-556d-4d97-9bef-50bc389675b8)
一直弹出很多信息，我重新安装了都没有用

### Expected Behavior

一直弹出很多信息，我重新安装了都没有用

### Minimal Reproducible Example

一直弹出很多信息，我重新安装了都没有用

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

一直弹出很多信息，我重新安装了都没有用

**Comment by mykola-mokhnach** [comment]
Please fill out the reporting form properly.
Also, sorry, but we only speak English.
