### ISSUE TITLE
bug:  iOS WebDriverAgentRunner uses large memory (~950MB) while executing 30+ tests in a test suite. (iOS 16 and 17) . Is there  a way to clear cache and other files from webdriveragent runner on ios after test completion ?

### ISSUE THREAD

**Issue by HarshdeepSingh3009** [appium/appium#20558]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

WebdriverAgentRunner memory use on the real device keeps on increasing with each test. After around 30-35 tests it reaches around 900MB.  Is there  a way to clear cache and etc from webdriver agent itself after test is done ? I have tried on both iOS 16 and iOS 17 and with different devices. The memory usage keeps on increasing and app under test crashes sometimes fighting for memory.

### Expected Behavior

There should be a way to clear up webdriveragent-runner's memory to get rid of cached files etc.  Is there a way to put cap on the memory usage of the webdriveragent-runner and/or clear cache/logs after that ?

### Minimal Reproducible Example

N/A

### Environment

- Operating system: iOS 16, 17 
- Appium server version (output of `appium --version`): 2.11.2
- Appium driver(s) and their version(s) (`appium driver list`): xcuitest 5.8.0
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`): 22.6.0
- `npm` version (output of `npm --version`): 10.8.2
- Last component(s) version which did _not_ exhibit the problem: N/A
- Platform and version under test: iOS 16, 17
- Real device or emulator/simulator: Real Device

**Comment by mykola-mokhnach** [comment]
>  xcuitest 5.8.0

This driver version is outdated. Please use the most recent version as we don't patch older ones.

In general, the current issue report does not really help to fix anything. Please collect a proper memory dump of the process when it uses excessive memory and attach it.

**Comment by mykola-mokhnach** [comment]
Closed because of no response
