### ISSUE TITLE
bug: logcat timestamps don't match the timestamps displayed in the message

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#20568]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

When I call `driver.get_log('logcat')` the response has wrong values for `timestamp` attributes compared to the timestamp displayed directly in the logcat `message`.

For instance, in the linked gist (line 313), the first entry has `timestamp` 1726149004329 (Thursday, 12 September 2024 16:50:04.329 GMT+03:00 DST) which is different from 09-12 15:51:33.947 displayed in the `message`.

### Expected Behavior

The `timestamp` should match the timestamp in the message.

### Minimal Reproducible Example

Call `driver.get_log('logcat')`  on Android using Python

### Environment

- Operating system: Windows
- Appium server version (output of `appium --version`): 2.11.3
- Appium driver(s) and their version(s) (`appium driver list`): uiautomator2@3.7.9 [installed (npm)]
- Appium plugin(s) and their version(s) (`appium plugin list`): no plugins
- Node.js version (output of `node --version`): v20.17.0
- `npm` version (output of `npm --version`): 10.8.2
- Last component(s) version which did _not_ exhibit the problem: ...
- Platform and version under test: Android
- Real device or emulator/simulator: Emulator

### Link to Appium Logs

https://gist.github.com/cosminstirbu/bb484d637ed47b07721f7aad756d28fd

**Comment by mykola-mokhnach** [comment]
I assume this is expected. The timestamp field contains the time when the host machine where the server is running actually retrieved the log line from the logcat service, while logcat log line contains the timestamp of when the line has been recorded adjusted to the device local clock. Obviously both timestamp cannot match, because there is always a delay between log line is recorded and delivered to the server (not even talking about time diff on the device and the server host).

As a possible workaround you may try to parse timestamp strings from actual messages if they contain such.

**Comment by cosminstirbu** [comment]
My use case is the following - I want to attach to the test results the logcat output that occurred **only** during the test run.

Currently I'm recording when the tests starts, and then I filter the logcat messages to only include the ones that were logged after the test started.

However, it seems that I will need to go down the path of parsing the timestamp string from the actual message, and not the `timestamp` from the dictionary response.

**Comment by mykola-mokhnach** [comment]
For your particular case I would rather consider an asynchronous solution that only captures logs while the test case is running. Try either https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-startlogsbroadcast/https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-stoplogsbroadcast or the [BiDi solution](https://github.com/appium/appium-android-driver/pull/955) that has been added quite recently

**Comment by cosminstirbu** [comment]
Understood, will look into those options as well.

On a small different topic - how can I get rid of the special characters from the Appium server logs such as:

[HTTP] **[37m-->[39m [37**mPOST[39m [37m/session[39m [90m{"capabilities":{"firstMatch":[{}],"alwaysMatch":{"appium:automationName":"uiautomator2","platformName":"Android","appium:language":"en","appium:locale":"US","appium:udid":"emulator-5554"}}}[39m

Is there an argument that I can pass to Appium server?

**Comment by mykola-mokhnach** [comment]
Yes, use the `--log-no-colors` server command line argument

**Comment by cosminstirbu** [comment]
I'm already using this `--log-no-colors` when starting AppiumService using Pyhon, however in `driver.get_log('server')` these special symbols are still there.

**Comment by mykola-mokhnach** [comment]
Then it's actually a bug. Please create another issue to track it

**Comment by mykola-mokhnach** [comment]
Lets just decide one by one. Putting everything into a big pile won't help to get it resolved faster

**Comment by cosminstirbu** [comment]
Here they are:

https://github.com/appium/appium/issues/20573
https://github.com/appium/appium/issues/20574
