### ISSUE TITLE
bug: `driver.get_log('server')` doesn't honour `--log-no-colors` argument

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#20573]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I instantiate AppiumService with `--log-no-colors` and then I call `driver.get_log('server')` it seems that the output still include color information making it hard to read (see line 2 in the attached [gist](https://gist.github.com/cosminstirbu/bb484d637ed47b07721f7aad756d28fd))

### Expected Behavior

No color symbols should be present in `driver.get_log('server')`  when AppiumService is instantiated with `--log-no-colors` 

### Minimal Reproducible Example

Instantiate AppiumService with `--log-no-colors` and then call `driver.get_log('server')`

### Environment

- Operating system: Windows
- Appium server version (output of appium --version): 2.11.3
- Appium driver(s) and their version(s) (appium driver list): uiautomator2@3.7.9 [installed (npm)]
- Appium plugin(s) and their version(s) (appium plugin list): no plugins
- Node.js version (output of node --version): v20.17.0
- npm version (output of npm --version): 10.8.2
- Last component(s) version which did not exhibit the problem: ...
- Platform and version under test: Android
- Real device or emulator/simulator: Emulator

### Link to Appium Logs

https://gist.github.com/cosminstirbu/bb484d637ed47b07721f7aad756d28fd

**Comment by mykola-mokhnach** [comment]
Actually, it makes no sense to have colors at all in the logs collected programatically, independently of the above command line argument value:

https://github.com/appium/appium-xcuitest-driver/pull/2466
https://github.com/appium/appium-android-driver/pull/958

**Comment by mykola-mokhnach** [comment]
Both patches have been published. Please update the driver and check again

**Comment by cosminstirbu** [comment]
I confirm that the issue is fixed now. Thank you!
