### ISSUE TITLE
bug: <title>get_attribute('text') is too slow to get a value

### ISSUE THREAD

**Issue by Yesisyes** [appium/appium#20572]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The app opens with a pop-up window, followed by a video that keeps playing.
I used the following code to find the list of nodes I needed and then iterate through the list to get the value of the text attribute d for each node. My question is, why does it take 10 seconds to get the list of nodes and 20 seconds to get the value of the text property?

element = driver.find_elements(
            AppiumBy.XPATH, '//*[@enabled="true" and normalize-space(@text)!=""]'
        )
for i in element:
    w = i.get_attribute('text')
    print(w)
print('ok')

### Expected Behavior

I wish it would be faster to get the text value of a node.

### Minimal Reproducible Example

from appium import webdriver
from appium.webdriver.common.appiumby import AppiumBy
from appium.options.android import UiAutomator2Options

def android_driver(device: dict):
    desired_caps = {
        "appium:appWaitDuration": 60000,
        "skipServerInstallation": True,
        "skipDeviceInitialization": True,
        "appium:disableSuppressAccessibilityService": True,
        "platformName": "Android",
        "appium:automationName": "uiautomator2",
        "appium:newCommandTimeout": 0,
        "autoGrantPermissions": True,
        "appium:adbExecTimeout": 120000,
        "appium:noReset": True,
        "appium:uiautomator2ServerLaunchTimeout": 60000,
        "appium:udid": device.get("appium:udid"),
        "appium:systemPort": device.get("appium:systemPort"),
        "enforceXPath1": True,
    }
    driver = webdriver.Remote(
        "http://127.0.0.1:4723",
        options=UiAutomator2Options().load_capabilities(desired_caps),
    )
    return driver
    
 driver = android_driver({"appium:udid": '9a47fcc5', "appium:systemPort": 8210})
element = driver.find_elements(
            AppiumBy.XPATH, '//*[@enabled="true" and normalize-space(@text)!=""]'
        )
for i in element:
    w = i.get_attribute('text')
    print(w)
print('ok')

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

Below I tested the app installation package and the appium terminal output log.
Method 1: adb shell uiautomator dump
Method 2: driver.page_source()
I tried to use these two methods to obtain the source code of the mobile phone interface at this time, and to speed up the realization of my purpose by analyzing the source code. But I could not obtain the source code because the video behind the current mobile phone interface was playing.
This is the apk file for my test app: https://drive.google.com/file/d/19LQrrg4_ibdvaRoQmPPbv6c7n6hWwY6j/view?usp=drive_link

[appium.log](https://github.com/user-attachments/files/16991112/appium.log)

**Comment by mykola-mokhnach** [comment]
This is most likely related to the fact that the app is not idling. Check https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#poor-elements-interaction-performance for more details.

**Comment by Yesisyes** [comment]
> This is most likely related to the fact that the app is not idling. Check https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#poor-elements-interaction-performance for more details.

Sorry, I kept reading this document: https://appium.io/docs/en/latest/guides/settings/,
but I'm still confused about how to set waitForIdleTimeout to 0 in my Python code. Can you give me a code example? Thank you very much. By the way, do you think it's right for me to set ignoreUnimportantViews to True?

**Comment by KazuCocoa** [comment]
This test code might help https://github.com/appium/python-client/blob/f47fe5b8cd1d1ed1f6ea100a677c71a4b0146f15/test/functional/android/settings_tests.py#L24-L27

**Comment by KazuCocoa** [comment]
> do you think it's right for me to set ignoreUnimportantViews to True?

It depends on your app. If your test works with ignoreUnimportantViews: true, it will help to reduce the amount of element retrieval. How it will help depends on Android internal, so i cannot say 100% sure thing but it would be worth to try it out to improve performance.

**Comment by Yesisyes** [comment]
> This test code might help https://github.com/appium/python-client/blob/f47fe5b8cd1d1ed1f6ea100a677c71a4b0146f15/test/functional/android/settings_tests.py#L24-L27

Oh. i get it. Thank you very much.
