### ISSUE TITLE
bug: `driver.get_log('server')` doesn't honour `--log-timestamp` argument

### ISSUE THREAD

**Issue by cosminstirbu** [appium/appium#20574]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I instantiate AppiumService with `--log-timestamp` and then I call `driver.get_log('server')` it seems that the `message` property in the entries in the output doesn't include the timestamp.

See attached [gist](https://gist.github.com/cosminstirbu/bb484d637ed47b07721f7aad756d28fd)

### Expected Behavior

The `message` string should also include the timestamp.

### Minimal Reproducible Example

Instantiate AppiumService with `--log-timestamp` and then call `driver.get_log('server')`

### Environment

- Operating system: Windows
- Appium server version (output of appium --version): 2.11.3
- Appium driver(s) and their version(s) (appium driver list): uiautomator2@3.7.9 [installed (npm)]
- Appium plugin(s) and their version(s) (appium plugin list): no plugins
- Node.js version (output of node --version): v20.17.0
- npm version (output of npm --version): 10.8.2
- Last component(s) version which did not exhibit the problem: ...
- Platform and version under test: Android
- Real device or emulator/simulator: Emulator

### Link to Appium Logs

https://gist.github.com/cosminstirbu/bb484d637ed47b07721f7aad756d28fd

**Comment by mykola-mokhnach** [comment]
> [AndroidUiautomator2Driver@1816] Responding to client with driver.getLog() result: [{"timestamp":1726149009062,"level":"ALL","message":"09-12 15:59:31.424   565   714 W IPCThreadState: Sending oneway calls to frozen process."},{"timestamp":1726149009062,"level":"ALL","message":"09-12 15:59:31.426  1479  2329 I BugleRcsEngine: handleMessage processing message:[NOTIFY_UPTIME_IGNORE_STATE_CHANGED] with [non-null]:RcsEngineImpl reference [CONTEXT log_prefix=\"RcsEngineImpl[DUAL_REG]:[2c37e27a-477d]>Handler\" thread_id=64 ]"},{"timestamp":1726149009062,"level":"ALL","message":"09-12 15:59:31.426  1479  1795 I BugleRcsEngine: Connected state: [1], networkType: [WIFI] [CONTEXT thread_id=56 ]"},{"timestamp":1726149009062,"level":"ALL","message":"09-12 15:59:31.433  1479  2329 I BugleRcsEngine: No RCS Configuration was found in Bugle for simID: redacted-pii:sim_id[chars:20,last3:897] [CONTEXT log_prefix=\"ProvisioningEngineDataRetriever\" thread_id=64 ]"},{"timestamp":1726149009062,"level":"ALL","message":"09-12 15:59:42.980   868  1560 D ApfFilter: (wlan0): Adding RA fe80::2 -> ff02::1 1800s fec...


Not sure what exactly is expected there. I can observe each of the above entries does contain the `timestamp` field

**Comment by cosminstirbu** [comment]
The output of `driver.get_log('server')` has two interesting attributes `timestamp` and `message`

I'd like the timestamp to be included in the `message` out of the box, when `--log-timestamp` is passed.

So message should be 

`2024-09-13 11:53:13:579 - [Appium] Welcome to Appium v2.11.3`

instead of 

`[Appium] Welcome to Appium v2.11.3`

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't think there is an easy way to make it work because of the way the logging system is designed. The log messages we retrieve by this API are stored in the internal appium logging buffer, while log messages that we see in the terminal or other output sources get passed through Winston, which decorates them with other data, including timestamps.

You may try to use an internal server "hack" to workaround this limitation for now. Set the `_LOG_TIMESTAMP` environment variable to `1` before running it.

**Comment by cosminstirbu** [comment]
Would an alternative be to use the `timestamp` attribute and concatenate it with the `message` myself?

Would it achieve the same result, or would the `timestamp` attribute be different from the actual timestamp when the log event occurred? (like in the logcat scenario)

**Comment by mykola-mokhnach** [comment]
> would the timestamp attribute be different from the actual timestamp when the log event occurred? (like in the logcat scenario)

exactly

**Comment by cosminstirbu** [comment]
> > would the timestamp attribute be different from the actual timestamp when the log event occurred? (like in the logcat scenario)
> 
> exactly

So it seems if I'd like to select the logs that occurred during a test run, I cannot use the `timestamp` attribute. Instead I need to set `_LOG_TIMESTAMP` environment variable to 1 and parse the timestamp from the message itself.

Alternatively, could I use `stdout` from AppiumService and process the logs as they are emitted?

**Comment by mykola-mokhnach** [comment]
> Alternatively, could I use stdout from AppiumService and process the logs as they are emitted?

yes if this process under your control. You may even consider changing the output format to JSON which would significantly simplify parsing (`--log-format=json`)

**Comment by cosminstirbu** [comment]
What I'm noticing in practice though, after setting _LOG_TIMESTAMP = 1, is that the `timestamp` attribute of the is in fact matching the one included out of the box in the `message` string.

Please see this [gist](https://gist.github.com/cosminstirbu/991f1931608e0f680725abbc9ecb54ab).

**2024-09-13 15:53:16.235000** [[_15-53-16:235_] HTTP] Request idempotency key: cd2be50a-8b29-4c33-8da0-9967243fa00d

The **bold** part is the `timestamp` attribute, concatenated manually to `message` attribute. The _italic_ part is the timestamp as included out of the box in the `message` attribute.

So hopefully the `timestamp` attribute does indeed reflect the time when the log event occurred (as opposed to the logcat scenario).

**Comment by mykola-mokhnach** [comment]
It is quite possible as the delay between server logs are generated and put into an internal buffer should be minimal. Eventually this all happens in scope of a single Node.js process in opposite to the logcat scenario.

**Comment by mykola-mokhnach** [comment]
I don't think we'd like to do anymore changes related to this issue.
