### ISSUE TITLE
bug: Application fails finding element by resource-id

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#20585]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am seeing in my element tree the following `node`:<br>
`<android.widget.EditText index="1" package="com.shs.iot" class="android.widget.EditText" text="" resource-id="input-username-login" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[105,614][979,674]" displayed="true" hint="Username" />`

**resource-id="input-username-login"**

But when I am calling to:
`driver.find_element(AppiumBy.ID, "input-username-login")` 
I am getting an error:
```
NoSuchElementException: Message: An element could not be located on the page using the given search parameters.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
```

### Expected Behavior

`find_element` method should return the `WebElement` of that edit input text element

### Minimal Reproducible Example

Presented above.

### Environment

- Operating system: Mac OS
- Appium server version (output of `appium --version`): 2.11.4
- Appium driver(s) and their version(s) (`appium driver list`):  uiautomator2@3.7.11
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):v18.20.2
- `npm` version (output of `npm --version`):10.8.3
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Android
- Real device or emulator/simulator: Real device

### Link to Appium Logs

https://github.com/bwomsm1/AppiumLogs/blob/master/android.log

**Comment by bwomsm1** [comment]
@mykola-mokhnach can you please help with this problem? thank you!

**Comment by mykola-mokhnach** [comment]
Check https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#elements-cannot-be-found

**Comment by bwomsm1** [comment]
> Check https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#elements-cannot-be-found

Thanks, following to that page what helped me solving my problem is adding this flag to the desire capabilities:
`disableIdLocatorAutocompletion = true`

**Comment by bwomsm1** [comment]
Add `disableIdLocatorAutocompletion = true` to the desire capabilities.

**Comment by eglitise** [comment]
Just to clarify, `disableIdLocatorAutocompletion` is a _setting_, not a _capability_. [Check the documentation for more details](https://appium.io/docs/en/latest/guides/settings/).
