### ISSUE TITLE
Populate photos for Android/iOS

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#2058]
To [populate photos](http://stackoverflow.com/a/16847750) on iOS:
1. Delete `~/Library/Application Support/iPhone Simulator/7.1-64/Media/PhotoData`
2. Copy photos to `~/Library/Application Support/iPhone Simulator/7.1-64/Media/DCIM/100APPLE`
3. Start simulator

To send the initial photos to the appium server on iOS, they could be included as a base64 zip in a desired capability.

Edit: To avoid the duplicate photo issue, we may need an [upload app for the simulator](https://github.com/basilhe/iOS-Simulator-Photo-Importer).

For android, there should be a generic adb push which can be used for photos or any other file type.

/cc @jlipps Does this sound reasonable?

**Comment by bootstraponline** [comment]
`xcrun simctl addphoto` is the preferred approach for seeding iOS simulators with photos.

**Comment by jlipps** [comment]
bumping priority since `xcrun simctl addphoto` makes this easy and it's a requested feature

**Comment by jlipps** [comment]
with https://github.com/appium/appium-xcuitest-driver/pull/516, this should now be possible, using `pushFile`:

```js
driver.pushFile("photoname.jpg", b64PhotoData)
```

The only restriction is that the path should end in a photo file name. Other than that the path doesn't really matter.

For Android, I guess we're still waiting on https://github.com/appium/appium/issues/3172

**Comment by jlipps** [comment]
After some more discussion, we think it's a good idea to have a `pushPhoto` command.

* new route added to mjsonwp, analogous to `push_file` but called `push_photo`
* takes b64 photo data and either a file name or file type (if either is necessary)

then on ios it will call `addMedia` under the hood and on android it will push the file and trigger the broadcast as specified in #3172.

**Comment by Kranthi9704** [comment]
Hi @jlipps
How can inspect elements in appium 1.7? and How can upload image or capture image in Android and IOS?

**Comment by mykola-mokhnach** [comment]
This is fixed in the recent beta
