### ISSUE TITLE
bug: mock location does not get reset after relaunching session

### ISSUE THREAD

**Issue by itkhanz** [appium/appium#20589]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using Appium inspector to mock the location of android and iOS device to test GPS location specific features.
I have encountered this issue that when I close the Appium Session, then the mock location does not get reset. 

For Android, I have to then manually execute ADB commands to get it to reset the applied mock location:

```
adb uninstall io.appium.uiautomator2.server.test
adb uninstall io.appium.uiautomator2.server
adb uninstall io.appium.settings
```

For iOS, i do not know how to reset the location to actual location when I chose the alert option "**Allow location while using App/ Allow once**"
On starting the Appium session, and accepting this alert, Google/Apple maps continue to show the previously applied mock location when current location option is tapped on map screen.

### Expected Behavior

Please provide a mechanism to reset the applied mock location on new session launch. In my opinion, on a new Appium session, the previously set mocked location should not be applied.
I also tested with appium:fullReset to true and uninstalling WDA but still the previously applied mock location is not removed.
Even uninstalling the WDA does not help to get back the actual device location as current location.

### Minimal Reproducible Example

Launch Appium Session and set the mock location to a different location than current location
Close and relaunch the new app session.
Select the current location marker which should move the map coordinates to the location of device.

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.6.0
- Appium driver(s) and their version(s) (`appium driver list`): XCUITest - 7.16.2 UIAutomator2 - 3.5.2
- Platform and version under test: iPhone 13 iOS 17.6, Samsung Galaxy S20 Android 13
- Real device or emulator/simulator: Real Device

**Comment by itkhanz** [comment]
Update: For iOS, it started showing the actual location as current location after sometime when I exited the app, and started it again.

Still I do not understand if and how can we reset the previously applied mock location from previous session.
Would be helpful to have this functoonality within Appium Inspector Session Execute Commands to reset the location, and also in the Appium clients so we do not have to kill the app, and possibly also uninstall WDA, UiAutomator2 server, appium settings etc.

**Comment by mykola-mokhnach** [comment]
For XCUITest driver use https://github.com/appium/appium-xcuitest-driver/blob/master/docs/reference/execute-methods.md#mobile-resetsimulatedlocation

For UIA2 driver set the `appium:mockLocationApp` capability to `null` (only works for real devices)

**Comment by itkhanz** [comment]
> For XCUITest driver use https://github.com/appium/appium-xcuitest-driver/blob/master/docs/reference/execute-methods.md#mobile-resetsimulatedlocation
> 
> For UIA2 driver set the `appium:mockLocationApp` capability to `null` (only works for real devices)

This did the trick. Thank you very much for your prompt answer (as always) and saving me headache.

I will also try to search in docs next time before posting these questions 😄 I did the google search but could not find any thing related to it, but as they say, read the documentation 📖
