### ISSUE TITLE
bug: waitForQuiescenceIncludingAnimationsIdle error triggers when trying to connect to iOS device with Appium Inspector and when doing swipe actions

### ISSUE THREAD

**Issue by andinica-idea** [appium/appium#20597]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to connect with Appium Inspector to any iOS devices or when trying to do any swipe actions using XCUITestDriver, we receive the following error: 
[XCUITestDriver@ee5b (b3402fd9)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCUIApplicationProcess waitForQuiescenceIncludingAnimationsIdle:]: unrecognized selector sent to instance 0x303caae00
This occurs even when trying to connect with Appium Inspector to an iOS device that just has the home screen opened, so it's not related to any application. 

### Expected Behavior

Connecting to Appium Inspector or doing swipe actions on iOS works fine.

### Minimal Reproducible Example

This has started occurring since updating xcode to version 16. I cannot see why this is related, but it's the only valid information I can provide

### Environment

- Operating system: macOS Sonoma 14.5 (23F79)
- Appium server version (output of `appium --version`): 2.6.0
- Appium driver(s) and their version(s) (`appium driver list`): XCUITest 7.26.4
- Appium plugin(s) and their version(s) (`appium plugin list`): device-farm@8.4.7-rc.18 (but this was run without it)
- Node.js version (output of `node --version`): v22.5.1
- `npm` version (output of `npm --version`): 10.8.2
- Last component(s) version which did _not_ exhibit the problem: XCode version 15.4
- Platform and version under test: iOS versions 17.1, 17.5, 17.6, 17.7
- Real device or emulator/simulator: real devices. iPhone 12, iPhone 14 Pro, iPhone 15

### Link to Appium Logs

https://gist.github.com/andinica-idea/f75c2abd7a216cfa3df870489c417f27

**Comment by KazuCocoa** [comment]
It has been fixed part of iOS 18/Xcode 16 updates in https://github.com/appium/appium/issues/20239 . Please use the latest XCUITest and re-build WDA if needed.

```
[38;5;32m[XCUITestDriver@b269 (2acf38b4)][0m Got response with status 200: {"value":{"build":{"upgradedAt":"1726753876687","version":"8.7.12","time":"Sep 19 2024 11:48:14","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iOS","sdkVersion":"18.0","version":"17.7"},"device":"iphone","ios":{"ip":"192.168.1.176"},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":null}
[38;5;32m[XCUITestDriver@b269 (2acf38b4)][0m WebDriverAgent information:
[38;5;32m[XCUITestDriver@b269 (2acf38b4)][0m {
[38;5;32m[XCUITestDriver@b269 (2acf38b4)][0m   "build": {
[38;5;32m[XCUITestDriver@b269 (2acf38b4)][0m     "upgradedAt": "1726753876687",
[38;5;32m[XCUITestDriver@b269 (2acf38b4)][0m     "version": "8.7.12",
[38;5;32m[XCUITestDriver@b269 (2acf38b4)][0m     "time": "Sep 19 2024 11:48:14",
[38;5;32m[XCUITestDriver@b269 (2acf38b4)][0m     "productBundleIdentifier": "com.facebook.WebDriverAgentRunner"
[38;5;32m[XCUITestDriver@b269 (2acf38b4)][0m   },
[38;5;32m[XCUITestDriver@b269 (2acf38b4)][0m   "os": {
```

The WDA version should be greater than 8.9.1 for over XCUITest driver 7.24.15+.

https://gist.github.com/andinica-idea/f75c2abd7a216cfa3df870489c417f27

**Comment by andinica-idea** [comment]
@KazuCocoa yeah, apparently we were using an outdated WDA after the upgrade to Xcode 16. Thank you for the input, you saved us 😄
