### ISSUE TITLE
bug: XCUITestDriver interactions with XCUIElementTypeSwitch provide no changes on iOS 16 

### ISSUE THREAD

**Issue by andinica-idea** [appium/appium#20600]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Interacting with XCUIElementTypeSwitch elements through XCUITestDriver on iOS 16.3.1 devices provides no changes of the switch element. If it is on and Appium presses on it, it stays on. If it is off, it stays off. Also tried changing the attribute value from 0 to 1 (or the other way around), still no changes. In the Appium logs, everything seems ok, no errors, but the state of the toggle button never changes.

### Expected Behavior

When pressed through XCUITestDriver, the switch button changes its state.

### Minimal Reproducible Example

Stated above. I do not believe Appium logs would be of much help but if needed, I will provide them

### Environment

- Operating system: macOS Sonoma 14.5
- Appium server version (output of `appium --version`): 2.6.0
- Appium driver(s) and their version(s) (`appium driver list`): xcuitest@7.26.4
- Appium plugin(s) and their version(s) (`appium plugin list`): - 
- Node.js version (output of `node --version`): v22.5.1
- `npm` version (output of `npm --version`): 10.8.2
- Last component(s) version which did _not_ exhibit the problem: iOS versions above 17
- Platform and version under test: iOS 16.3.1
- Real device or emulator/simulator: real device, tried on 3 phones with same OS

**Comment by mykola-mokhnach** [comment]
It could be an internal XCTest compatibility issue. Try to use a compatible Xcode SDK (14.3) to build WDA for this iOS version . You may also verify the actual behaviour by running a vanilla XCTest script with the same set of controls

**Comment by andinica-idea** [comment]
Thanks for the answer @mykola-mokhnach . I will check and come back to you

**Comment by mykola-mokhnach** [comment]
Closed because of no response
