### ISSUE TITLE
[Feat]:Connect without USB for IOS (Apple TV 4K and IPAD) using XCUITEST Driver

### ISSUE THREAD

**Issue by veenadevi** [appium/appium#20602]
**Is your feature request related to a problem? Please describe.** 
As Apple TV 4k, Dont have USB connectivity, XCUITEST Driver does not deduct real devices connected in same network .However able to run WebDriver Agent

**Describe the solution you'd like**

As Like UIAutomator 2, XCUITEST Driver should connect with Deviced in WIFI

**Comment by mykola-mokhnach** [comment]
In order to support this functionality it is necessary to update the https://github.com/appium/appium-ios-device to support iOS 17+ tunnelling over network or to find and implement an alternative to this module.

Unfortunately we don't have experts in the team to do neither of the above.
