### ISSUE TITLE
bug: don't propagate `webSocketUrl` capability until Appium has support for Bidi

### ISSUE THREAD

**Issue by christian-bromann** [appium/appium#20604]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using Appium to start a browser session, e.g. Chrome, it propagates all resolved capabilities from the driver back to the client. This can cause confusion on the client side, e.g. WebdriverIO, which assumes that the driver supports Bidi. However Appium doesn't propagate WebSocket messages to the Chromedriver in this case causing an unexpected behavior.

### Expected Behavior

I would suggest to remove `webSocketUrl` from the returned capabilities object until Appium has a way to propagate socket messages.

### Minimal Reproducible Example

n/a

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
I guess the issue is https://github.com/appium/appium-chromium-driver specific. Actually bidi support added in https://github.com/appium/appium-chromium-driver/pull/206 started failing in wdio v9 update renovate PR: https://github.com/appium/appium-chromium-driver/pull/330

**Comment by KazuCocoa** [comment]
Probably... will https://github.com/appium/appium/pull/20603 / https://github.com/appium/appium/pull/20590 fix this issue...?

https://github.com/appium/appium-chromium-driver/actions/runs/11007193524/job/30562700066?pr=330
```
[HTTP] 
2024-09-24T04:50:37.960Z INFO webdriver: Register BiDi handler for session with id 5074a287-7f7d-40af-87aa-5aac5b2b1ea4
2024-09-24T04:50:37.960Z INFO webdriver: Connect to webSocketUrl ws://0.0.0.0:4780/bidi/5074a287-7f7d-40af-87aa-5aac5b2b1ea4
[AppiumDriver@dd5f] Bidi websocket connection made for session 5074a287-7f7d-40af-87aa-5aac5b2b1ea4
[AppiumDriver@dd5f] Bidi connection for ChromiumDriver will be proxied to ws://127.0.0.1:9515/session/074c54[351](https://github.com/appium/appium-chromium-driver/actions/runs/11007193524/job/30562700066?pr=330#step:9:352)c145d908ffbadbde4e79a5f
2024-09-24T04:50:37.964Z INFO webdriver: Connected session to Bidi protocol
2024-09-24T04:50:37.964Z INFO webdriver: Connected session to Bidi protocol
2024-09-24T04:50:37.964Z INFO webdriver: Connected to WebDriver Bidi interface at ws://0.0.0.0:4780/bidi/5074a287-7f7d-40af-87aa-5aac5b2b1ea4
2024-09-24T04:50:37.964Z INFO webdriver: COMMAND getWindowHandle()
```

I wondered if the issue was because of the `0.0.0.0`.

**Comment by jlipps** [comment]
bidi fix published in appium 2.11.5. check to see if that helps?

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by Maxim-Mazurok** [comment]
I get this on 2.13.1:
ERROR webdriver: invalid argument: WebDriverError: Unknown capability encountered: 'webSocketUrl' = '1'

**Comment by christian-bromann** [comment]
Sorry, yeah I think we are good with this one being resolved as Appium now actually does support Bidi. Thanks for all your work @mykola-mokhnach
