### ISSUE TITLE
bug: Appium iOS Simulator Startup Extremely Slow with WDA Reuse on iOS 17.5

### ISSUE THREAD

**Issue by Icchy-cho** [appium/appium#20606]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm experiencing slow startup times when running iOS automation on an iOS 17.5 simulator using Appium with XCUITest. The app launch is delayed, particularly during WebDriverAgent (WDA) initialization, even though I’ve set usePreinstalledWDA: true and noReset: true. The delay persists, taking over a minute to start the session. I've tried different settings without success.

### Expected Behavior

The app should launch much faster, ideally reusing WDA without needing to initialize every time.

### Minimal Reproducible Example

    "platformName": "iOS",
    "appium:automationName": "XCUITest",
    "appium:platformVersion": "17.5",
    "appium:bundleId": "com.com-com",
    "appium:deviceName": "iPhone 15 Pro",
    "appium:noReset": "true",
    "appium:fullReset": "false",
    "appium:newCommandTimeout": "300",
    "appium:usePreinstalledWDA": "true",
    "appium:wdaStartupRetries": "1",
    "appium:wdaStartupRetryInterval": "5000",
    "appium:waitForIdleTimeout": "10",
    "appium:reduceMotion": "true",
    "appium:showXcodeLog": "true"

### Environment

- Operating system: MacOS 15.0
- Appium server version: 2.11.4
- Appium driver(s) and their version(s): xcuitest@7.26.4
- Xcode Version: 16.0 (16A242d
- Node.js version: 22.9.0
- `npm` version: 10.8.3
- WebDriverAgent: 8.9.2
- Last component(s) version which did _not_ exhibit the problem: Appium 1.22.3, MacOS 14.0
- Platform and version under test: iPhone 15 Pro (iOS 17.5)
- Real device or emulator/simulator: Simulator 

### Link to Appium Logs

https://gist.github.com/Icchy-cho/e0b24a2479513601e37b2d18af2276b4

### Further Information

There are significant time gaps in the logs between setting simulator preferences and updating simulator preferences, there's a delay of nearly 40 seconds, indicating the simulator is taking much longer than expected to configure itself.

**Comment by mykola-mokhnach** [comment]
Not sure if there is anything that could affect this behaviour. The driver uses the standard macOS `defaults` command line tool to write preferences. Perhaps, there is an issue with macOS or Simulator SDK itself that makes it to delay for so long

**Comment by Icchy-cho** [comment]
This is Appium Log with showIOSLog
https://gist.github.com/Icchy-cho/c7b0098a91a24008e434d77fe9cf14ef

**Comment by mykola-mokhnach** [comment]
Unfortunately I don't see any traces or useful hints in the above log. Try to update Xcode/Simulator to the recent version and see if that changes anything

**Comment by Icchy-cho** [comment]
It seems that the issue is caused by having two Appium installations on your Mac: one installed via Homebrew and the other via npm. 
I uninstall Appium on homebrew and reinstall on npm.
Worked fine now Thank you
