### ISSUE TITLE
bug: <title>iPhone 6sp 启动WDA失败

### ISSUE THREAD

**Issue by liuyabin-svg** [appium/appium#20626]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Crash: WebDriverAgentRunner-Runner (14304) 0x1057d8000: Namespace SIGNAL, Code 0xb

### Expected Behavior

Crash: WebDriverAgentRunner-Runner (14304) 0x1057d8000: Namespace SIGNAL, Code 0xb

### Minimal Reproducible Example

Crash: WebDriverAgentRunner-Runner (14304) 0x1057d8000: Namespace SIGNAL, Code 0xb

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

Crash: WebDriverAgentRunner-Runner (14304) 0x1057d8000: Namespace SIGNAL, Code 0xb

**Comment by mykola-mokhnach** [comment]
Please fill out the issue report properly. We cannot help without having this required information available.

**Comment by liuyabin-svg** [comment]
这个问题修复了么
