### ISSUE TITLE
JavaScript unit test code coverage?

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#2062]
It'd be nice to have some [code coverage](https://github.com/karma-runner/karma-coverage) for the JavaScript appium tests.

**Comment by jlipps** [comment]
Added to our CI improvements epic, we still need to get good code coverage generated

**Comment by rkavalap** [comment]
Reference bug for tracking. 
https://github.com/appium/appium-gulp-plugins/issues/21

**Comment by dpgraham** [comment]
Code coverage is built into V8 now. May be worth having a look into it this upcoming sprint:

http://www.mattzeunert.com/2017/03/29/how-does-chrome-code-coverage-work.html

**Comment by imurchie** [comment]
More info: https://v8project.blogspot.com/2017/12/javascript-code-coverage.html

We could do this, though we also have coverage through instanbul/coveralls at the moment, which works pretty well. This would require making sure we're using the latest V8.

**Comment by dpgraham** [comment]
@imurchie Are we satisfied with our code coverage then and I can just close this issue?

**Comment by imurchie** [comment]
Well! I'm satisfied with our code coverage reporting, and am ok with closing this. I am **not** happy with our code coverage (save a few modules) but that is a different story.
