### ISSUE TITLE
bug: Appium UiAutomator2 driver fails to recognize the same element it found before

### ISSUE THREAD

**Issue by itkhanz** [appium/appium#20624]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, I have an android screen with a text element which has accesibility ID. The same element can be recognized by Appium on the screen, but when on the same screen, user does login and gets redirected back to it, this element is no longer recognized by Appium. I have even tried to set waits, tried different locators such as XPath and text etc. but still Appium fails to find this element. I also created new instance of page object but this also did not resolve the issue. Aparently there is nothing happening on the screen which might cause this element to get overlayed, and the test fails after retrying for upto 30 seconds. Intresting things is that this happens intermittently, and not always.

I tested with Appium Inspector, and in the Appium Inspector element is clearly visible and can be found with this locator and has display attribute set to true.

This problem is only happening with me when I try to run automated Appium script with Appium Java client.

This is how element is defined.

```
@WithTimeout(time = 30, chronoUnit = SECONDS)
@AndroidFindBy(accessibility = "PricingUsageCost") 
public WebElement usageCostTitle;
```

I have even used different locators such as `@AndroidFindBy(xpath = "//*[contains(@text, 'Usage cost')]")` which all work fine with Appium Inspector.

Here is the screenshot of element from Appium Inspector:-

First screenshot is when user is logged-out and Appium is able to recognize the element:-
![Screenshot 2024-09-27 at 11 26 53](https://github.com/user-attachments/assets/5b5be047-ca97-4f98-94f2-03f85daf191d)

Below is the second screenshot where Appium fails to recognize the element even though apparently this element has same accessibility ID as before and there is only single element on screen with this accessibility ID. I also tried XPath with text attribute which also does not work.

![Screenshot 2024-09-27 at 11 24 35](https://github.com/user-attachments/assets/f0b9fee4-e41b-4866-8d25-b1b7166c5893)

These are the server logs:

First logs are when the user is logged-out and Appium is able to find the element:

```
[HTTP] <-- GET /session/b2df5baa-bbd6-4719-bfd9-8dd73828657a/context 200 2 ms - 22 
[HTTP] --> POST /session/b2df5baa-bbd6-4719-bfd9-8dd73828657a/element {"using":"accessibility id","value":"PricingUsageCost"}
[AndroidUiautomator2Driver@e151] Calling AppiumDriver.findElement() with args: ["accessibility id","PricingUsageCost","b2df5baa-bbd6-4719-bfd9-8dd73828657a"]
[AndroidUiautomator2Driver@e151] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
[AndroidUiautomator2Driver@e151] Waiting up to 0 ms for condition
[AndroidUiautomator2Driver@e151] Matched '/element' to command name 'findElement'
[AndroidUiautomator2Driver@e151] Proxying [POST /element] to [POST http://127.0.0.1:8007/session/1889a149-8b6d-4ef1-9315-fd9c7702d02b/element] with body: {"strategy":"accessibility id","selector":"PricingUsageCost","context":"","multiple":false}
[AndroidUiautomator2Driver@e151] Got response with status 200: {"sessionId":"1889a149-8b6d-4ef1-9315-fd9c7702d02b","value":{"ELEMENT":"00000000-0000-0054-0000-00ba00000103","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0054-0000-00ba00000103"}}
[AndroidUiautomator2Driver@e151] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0054-0000-00ba00000103","ELEMENT":"00000000-0000-0054-0000-00ba00000103"}
[HTTP] <-- POST /session/b2df5baa-bbd6-4719-bfd9-8dd73828657a/element 200 74 ms - 137 
[HTTP] --> GET /session/b2df5baa-bbd6-4719-bfd9-8dd73828657a/element/00000000-0000-0054-0000-00ba00000103/displayed {}
[AndroidUiautomator2Driver@e151] Calling AppiumDriver.elementDisplayed() with args: ["00000000-0000-0054-0000-00ba00000103","b2df5baa-bbd6-4719-bfd9-8dd73828657a"]
[AndroidUiautomator2Driver@e151] Matched '/element/00000000-0000-0054-0000-00ba00000103/attribute/displayed' to command name 'getAttribute'
[AndroidUiautomator2Driver@e151] Proxying [GET /element/00000000-0000-0054-0000-00ba00000103/attribute/displayed] to [GET http://127.0.0.1:8007/session/1889a149-8b6d-4ef1-9315-fd9c7702d02b/element/00000000-0000-0054-0000-00ba00000103/attribute/displayed] with no body
[AndroidUiautomator2Driver@e151] Got response with status 200: {"sessionId":"1889a149-8b6d-4ef1-9315-fd9c7702d02b","value":"true"}
[AndroidUiautomator2Driver@e151] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /session/b2df5baa-bbd6-4719-bfd9-8dd73828657a/element/00000000-0000-0054-0000-00ba00000103/displayed 200 23 ms - 14 
```

Second logs are below when user is logged-in and Appium fails to find the element after retrying for 30 seconds.

```
[HTTP] --> POST /session/b375ac1f-48c4-4c99-bd19-fc19a53e3d83/element {"value":"PricingUsageCost","using":"accessibility id"}
[AndroidUiautomator2Driver@24c8] Calling AppiumDriver.findElement() with args: ["accessibility id","PricingUsageCost","b375ac1f-48c4-4c99-bd19-fc19a53e3d83"]
[AndroidUiautomator2Driver@24c8] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
[AndroidUiautomator2Driver@24c8] Waiting up to 0 ms for condition
[AndroidUiautomator2Driver@24c8] Matched '/element' to command name 'findElement'
[AndroidUiautomator2Driver@24c8] Proxying [POST /element] to [POST http://127.0.0.1:8007/session/cd2308da-878c-48c2-b3e6-526724e73540/element] with body: {"strategy":"accessibility id","selector":"PricingUsageCost","context":"","multiple":false}
[AndroidUiautomator2Driver@24c8] Got response with status 404: {"sessionId":"cd2308da-878c-48c2-b3e6-526724e73540","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:63)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:259)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:253)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:77)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann...
[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[AndroidUiautomator2Driver@24c8] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (/Users/xxxx/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.ts:86:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/xxxx/.nvm/versions/node/v20.11.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)
    at AndroidUiautomator2Driver.findElement (/Users/xxxx/.nvm/versions/node/v20.11.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)
[HTTP] <-- POST /session/b375ac1f-48c4-4c99-bd19-fc19a53e3d83/element 404 82 ms - 891
```

Below are the logs when Appium was able to find the element after logging-in, but this case is on different app. in my observation, this is not app specific, because on same app with same code, somtimes Appium is able to find the element while at other times, it fails.

```
[HTTP] --> POST /session/ae6d04dd-dca6-4ea3-89a6-e99839c89ce8/element {"using":"accessibility id","value":"PricingUsageCost"}
[AndroidUiautomator2Driver@cfa8] Calling AppiumDriver.findElement() with args: ["accessibility id","PricingUsageCost","ae6d04dd-dca6-4ea3-89a6-e99839c89ce8"]
[AndroidUiautomator2Driver@cfa8] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
[AndroidUiautomator2Driver@cfa8] Waiting up to 0 ms for condition
[AndroidUiautomator2Driver@cfa8] Matched '/element' to command name 'findElement'
[AndroidUiautomator2Driver@cfa8] Proxying [POST /element] to [POST http://127.0.0.1:8009/session/9e047b30-2562-4dad-b5d2-946180918e4b/element] with body: {"strategy":"accessibility id","selector":"PricingUsageCost","context":"","multiple":false}
[AndroidUiautomator2Driver@cfa8] Got response with status 200: {"sessionId":"9e047b30-2562-4dad-b5d2-946180918e4b","value":{"ELEMENT":"00000000-0000-0090-0000-00a500000103","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0090-0000-00a500000103"}}
[AndroidUiautomator2Driver@cfa8] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0090-0000-00a500000103","ELEMENT":"00000000-0000-0090-0000-00a500000103"}
[HTTP] <-- POST /session/ae6d04dd-dca6-4ea3-89a6-e99839c89ce8/element 200 74 ms - 137 
[HTTP] --> GET /session/ae6d04dd-dca6-4ea3-89a6-e99839c89ce8/element/00000000-0000-0090-0000-00a500000103/displayed {}
[AndroidUiautomator2Driver@cfa8] Calling AppiumDriver.elementDisplayed() with args: ["00000000-0000-0090-0000-00a500000103","ae6d04dd-dca6-4ea3-89a6-e99839c89ce8"]
[AndroidUiautomator2Driver@cfa8] Matched '/element/00000000-0000-0090-0000-00a500000103/attribute/displayed' to command name 'getAttribute'
[AndroidUiautomator2Driver@cfa8] Proxying [GET /element/00000000-0000-0090-0000-00a500000103/attribute/displayed] to [GET http://127.0.0.1:8009/session/9e047b30-2562-4dad-b5d2-946180918e4b/element/00000000-0000-0090-0000-00a500000103/attribute/displayed] with no body
[AndroidUiautomator2Driver@cfa8] Got response with status 200: {"sessionId":"9e047b30-2562-4dad-b5d2-946180918e4b","value":"true"}
[AndroidUiautomator2Driver@cfa8] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /session/ae6d04dd-dca6-4ea3-89a6-e99839c89ce8/element/00000000-0000-0090-0000-00a500000103/displayed 200 22 ms - 14 

```

Could you please look into this issue and suggest any possible error.

### Expected Behavior

Appium should be able to find the element that is clearly visible on screen.

### Minimal Reproducible Example

This example is only reproducible with one of our internal apps.

### Environment

- Operating system: macOS 14.6.1
- Appium Java Client 9.3.0
- Appium server version (output of `appium --version`): 2.6.0
- Appium driver(s) and their version(s) (`appium driver list`): UiAutomator2 3.5.2
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Android 13 and 14
- Real device or emulator/simulator: real device Samsung Galaxy S20 and S24

### Further Information

This is how the element is defined in Android app with accessibility ID  "PricingUsageCost" which is a Jetpack Compose screen:

```
Row {
                Text(
                    text = stringResource(id = R.string.pool_details_costs_usage_cost),
                    modifier = Modifier
                        .alignByBaseline()
                        .testSemantics("PricingUsageCost"),
                    maxLines = 2,
                    style = BrandTheme.typography.largeBodyBold,
                    color = BrandTheme.colors.textTitleColor,
                )
                Spacer(modifier = Modifier.width(4.dp))
                Text(
                    text = stringResource(id = taxTextId),
                    modifier = Modifier
                        .alignByBaseline()
                        .testSemantics("PricingUsageCostTax"),
                    maxLines = 2,
                    style = BrandTheme.typography.caption,
                    color = BrandTheme.colors.textSecondaryColor,
                )
}
```

**Comment by mykola-mokhnach** [comment]
Try to fetch the page source right before locating the element and check if it's there.
In general, element location is controlled by UiAutomator framework itself, we cannot influence anything there much.
You could also try the troubleshooting at https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#elements-cannot-be-found

**Comment by itkhanz** [comment]
> Try to fetch the page source right before locating the element and check if it's there.

I checked right before locating the element and element is present in the page source for one of the white label app, while for the other app it is not present in which case the test is failing even though both apps have same source code for this particular screen:-

`<android.widget.TextView index="0" package="com.digitalchargingsolutions.hyundai.integ" class="android.widget.TextView" text="Usage cost" content-desc="PricingUsageCost" checkable="false" checked="false" clickable="false" enabled="true" focusable="false" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[72,915][367,975]" displayed="true" />`


About the above settings, I tried with setting below to true but this also did not resolve the issue.

```
((HasSettings) driver).setSettings(Map.of("allowInvisibleElements", true));
((HasSettings) driver).setSettings(Map.of("enableMultiWindows", true));
```

so it could be something related to that app where some background process is causing UiAutomator2 framework to not run properly on this specific screen? Also, it is not just this element, i noticed that some other elements with accessibility ID are also missing from page source.

What i do not understand is why then Appium Inspector is able to identify the element and not Appium Java Client although both are connected to same Appium Server and driver versions.

**Comment by mykola-mokhnach** [comment]
Have you also tried disableIdLocatorAutocompletion?

It might also be a race condition, try to wait for elements for a while before giving up.

Otherwise I don't have any good ideas except of reporting the issue to Google.

**Comment by itkhanz** [comment]
> Have you also tried disableIdLocatorAutocompletion?

But isn't this for resource-id? In my case, the ID is accessibility ID being set by content-desc attribute.

**Comment by itkhanz** [comment]
> It might also be a race condition, try to wait for elements for a while before giving up.
> 
> Otherwise I don't have any good ideas except of reporting the issue to Google.

could you please provide some insights on what possible race conditions could prevent UiAutomator2 to not identify all the elements on screen? I will then discuss this with Devs to try to understand why the problem is intermittent and possibly only for one of the app.

**Comment by mykola-mokhnach** [comment]
> > Have you also tried disableIdLocatorAutocompletion?
> 
> But isn't this for resource-id? In my case, the ID is accessibility ID being set by content-desc attribute.

Please read https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#element-location

**Comment by itkhanz** [comment]
> > > Have you also tried disableIdLocatorAutocompletion?
> > 
> > 
> > But isn't this for resource-id? In my case, the ID is accessibility ID being set by content-desc attribute.
> 
> Please read https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#element-location

Yes I did read that but as I said in my case the element that is missing in page source does not have any resource-id so using this setting did not make sense to me as this element locator is defined using accessibility which targets content-desc attribute. I may be missing some point here.

In any case, I did try this setting but this then causes test to fail at very beginning because of locators not being properly setup, so then i used this setting right before the problematic element interaction which also did not solve the issue .

**Comment by grishukov** [comment]
@itkhanz Hi! 
You indicated that it could be multiple white label apps. Most likely they are built using product flavors in the Android project. In this case applications will have the same id but different package names.

 for example id="com.digitalchargingsolutions.kia.integ:id/map_holder"&gt; 
 one application will have com.digitalchargingsolutions.kia.integ and another will have a different name. 
 
 So when running tests in capabilities/appiumOptions check that you specify the correct package. 
The problem could be this.
 And yes, it is better to ask developers to specify it in the application code just in case
 .semantics { testTagsAsResourceId = true}

**Comment by itkhanz** [comment]
> In this case applications will have the same id but different package names.

Hi you are correct but in this case I am not locating elements via resource-id (ID) but the content-des  (accessibility) which does not have anything to do with package name.
As far as package name is concerned, I am supplying correct package name in the session capability.

**Comment by mykola-mokhnach** [comment]
I don't think there is anything more we could help there. Like I said elements location is controlled by Google's UiAutomator framework.

Closed as third party issue

**Comment by itkhanz** [comment]
This issue turned out to be happening when user swipes up to view the content appearing on bottom. This swipe operation appartently caused the partial elements on screen to be removed from display as they got scrolled up, which led to this issue. This could be related to how this screen is implemented with Compose columns and rows when a certain section has to be completely visible on screen in order for UiAutomator2 to find all its elements from page source.
