### ISSUE TITLE
unable to target element with testID if Textinput is wrappedn in View element

### ISSUE THREAD

**Issue by mubashiralisiddiqui** [appium/appium#20636]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have  my text input component which is working fine in android for e2e but in ios its not working
it only works if i remove the View element. `  <View style={styleContainer}>` 

### Expected Behavior

it should work fine for nested element

### Minimal Reproducible Example

 `

const TextInput =()=>{

    return (

      <TouchableWithoutFeedback onPress={onPress}>

        <View style={styleContainer}>

          {this._renderLabel.bind(this)()}

          <TextInput
            onTouchStart={onTouch}
            ref={input => (this.textInput = input)}
            style={styleInput}
            value={this.props.value}
            placeholder={placeholder}
            maxLength={this.props.maxLength}
            multiline={multiline}
            placeholderTextColor={placeholderTextColor}
            onChangeText={onChangeText}
            onEndEditing={onEndEditing}
            onFocus={onFocus}
            defaultValue={defaultValue}
            keyboardType={keyboardType}
            onSubmitEditing={Keyboard.dismiss}
            disabled={disabled}
            editable={disabled ? false : true}
            underlineColorAndroid={'transparent'}
            pointerEvents={pointerEvent ? pointerEvent : hasPointerEvent}
            secureTextEntry={secureTextEntry}
            returnKeyType="done"
            caretHidden={caretHidden || false}
            textAlignVertical={this.props.textAlignVertical || 'auto'}
            testID={testID}
          />
          {errorMessage !== '' && (
            <Text
              fontSize={commonStyles.fontSizes.s.h2}
              style={{
                color: 'red',
                maxWidth: '95%',
                fontFamily: commonStyles.fonts.regular,
                marginTop: moderateScale(3),
              }}>
              {errorMessage}
            </Text>
          )}
        </View>
      </TouchableWithoutFeedback>
    );
  }
}
export default TextInput;
`

### Environment

- Operating system: MAC OS
- Appium server version (output of `appium --version`):2.11.5
- Appium driver(s) and their version(s) (`appium driver list`):- xcuitest@7.26.3 ,uiautomator2@3.7.11 
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):18.17.1
- `npm` version (output of `npm --version`):9.6.7
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: ios
- Real device or emulator/simulator: simulator

**Comment by mykola-mokhnach** [comment]
Please ask your question at React development forums
