### ISSUE TITLE
2024 OpenJS Foundation CPC Selections as a Impact project

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#20631]
https://github.com/openjs-foundation/cross-project-council/issues/1370

@jlipps and @KazuCocoa are the voting members voluntary right now from Appium project. The next selection should be by October 11, 2024.

Based on my experience, it doesn't require many things so far.

**Comment by KazuCocoa** [comment]
@mykola-mokhnach @eglitise are you interested in being the member from Appium?

I didn't get many things to work as the member in the past, so I guess this year will be also the same or similar. If not so interested in, perhaps @jlipps and I could keep the member.

**Comment by eglitise** [comment]
I'm fine, but thanks for the offer.

**Comment by KazuCocoa** [comment]
<img width="704" alt="Screenshot 2024-10-10 at 6 10 26 PM" src="https://github.com/user-attachments/assets/4d8f4cfa-6bec-47c3-b919-eccec3d5bc4e">

jlipps and I will keep the voluntary spots for now
