### ISSUE TITLE
bug: <title>inspector  v2009.9.1 could not get page source after run app successfully on ios18.1, 

### ISSUE THREAD

**Issue by pritesh848** [appium/appium#20647]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have successfully run app on real device(ios18) through appium mac app on Mac but the page keeps showing 'Gathering initial app source...' and could not show the page source as before when using xcode 16 and ios16 device.

Environment
Appium version (or git revision) that exhibits the issue:V2.11
Last Appium version that did not exhibit the issue (if applicable):I can't remember
Desktop OS/version used to run Appium:.2.11
Node.js version (unless using Appium.app|exe):
Mobile platform/version under test:ios16
Real device or emulator/simulator:real device iphone 16 pro plus
Appium CLI or Appium.app|exe:

### Expected Behavior

The inspector is loading only not able to see mobile scree in inspector

### Minimal Reproducible Example

Connect the device and start appium inspector

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

On connecting the device and launching the app in inspector the loader is loading

**Comment by eglitise** [comment]
Please provide your full Appium server log.

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by pritesh848** [comment]
[appium logs.txt](https://github.com/user-attachments/files/17362734/appium.logs.txt)
Please find attached logs
