### ISSUE TITLE
Im using latest appium and uiautomator but getting No Chromedriver found that can automate Chrome 

### ISSUE THREAD

**Issue by RedaV88** [appium/appium#20646]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting appium with 
"appium", "--allow-insecure", "chromedriver_autodownload"

### Expected Behavior

Chrome is autodownloaded

### Minimal Reproducible Example

5/5

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
Please attach the full Appium server log

**Comment by RedaV88** [comment]
@KazuCocoa sure, here it is 
[appiumlogs.txt](https://github.com/user-attachments/files/17275182/appiumlogs.txt)

**Comment by eglitise** [comment]
> [e2f23247][Chromedriver@cf30] Error: Cannot retrieve the information about available Chromedrivers from https://chromedriver.storage.googleapis.com, https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json. Please make sure these URLs are avilable within your local network, check Appium server logs and/or consult the driver troubleshooting guide.

Please check if these URLs are accessible from your test executor machine.

**Comment by RedaV88** [comment]
@eglitise yes, its available 
![image](https://github.com/user-attachments/assets/00d1527c-59cd-4a13-be4d-fc03efa659ba)
![image](https://github.com/user-attachments/assets/803daa81-078a-411e-9448-2463a06c770e)

**Comment by RedaV88** [comment]
@eglitise yes, available
![image](https://github.com/user-attachments/assets/ac8a960f-97b4-4fb6-b836-2d5b027fd3b5)
![image](https://github.com/user-attachments/assets/0798c43c-db75-4c33-8f22-07880f09cf03)

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
