### ISSUE TITLE
bug: application cannot activate because of WebAgentDriver "code 70" althogh that WebAgentDriver was build successfully on xCode

### ISSUE THREAD

**Issue by bwomsm1** [appium/appium#20654]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am getting the famous `code 70` error when I did build the WebAgentDriver application successfully in xcode, I can also say that I am able to see the `app` file in the xcode builds folder. 

### Expected Behavior

Application should be launched. 

### Minimal Reproducible Example

`active_applicaiton`

### Environment

- Operating system:
- Appium server version (output of `appium --version`): `2.11.5`
- Appium driver(s) and their version(s) (`appium driver list`):
- ✔ Listing available drivers
- uiautomator2@3.8.0 [installed (npm)]
- xcuitest@7.27.0 [installed (npm)]
- espresso [not installed]
- mac2 [not installed]
- windows [not installed]
- safari [not installed]
- gecko [not installed]
- chromium [not installed]
- 
- Appium plugin(s) and their version(s) (`appium plugin list`):
- ✔ Listing available plugins
- images [not installed]
- execute-driver [not installed]
- relaxed-caps [not installed]
- universal-xml [not installed]
- 
- Node.js version (output of `node --version`):v22.9.0
- `npm` version (output of `npm --version`): 10.8.3
- Last component(s) version which did _not_ exhibit the problem: 
- Platform and version under test: Mac OS, 
- Real device or emulator/simulator: real device

### Link to Appium Logs

https://github.com/bwomsm1/AppiumLogs/blob/master/appium_ios.log

**Comment by bwomsm1** [comment]
@mykola-mokhnach can you please help with this issue? Thank You!

**Comment by bwomsm1** [comment]
I can also say that when I am opening the `WebAgentDriver` app manually by clicking it, it is crashing.

**Comment by itkhanz** [comment]
please also share
XCode version?
iOS version?
macOS version?

have you tried with the older version of XCUITest driver or any other device?

**Comment by bwomsm1** [comment]
> please also share XCode version? iOS version? macOS version?
> 
> have you tried with the older version of XCUITest driver or any other device?

Xcode Version 16.0 (16A242d)
iOS vertion 18.1 (iPhone 14)
Mac os 15.0.1


I must say that it does working with some other devices, but I don't understand what is wrong with that device? My device is registered correctly in the apple acount, and as I said the WebAgentDriver does build.

**Comment by itkhanz** [comment]
> I must say that it does working with some other devices, but I don't understand what is wrong with that device?

could be specific to XCode 16 update? I am yet to upgrade macOS so I cannot really test it on my environment if the problem comes from mac/XCode update.

try building with lower version of iOS and possibly with XCode 15 to see if you still get the same error. Not really sure if it is possible to downgrade XCode version but you can try to build the project for iOS 17 device simulator.

This will help to figure out where the problem lies.

**Comment by bwomsm1** [comment]
> > I must say that it does working with some other devices, but I don't understand what is wrong with that device?
> 
> could be specific to XCode 16 update? I am yet to upgrade macOS so I cannot really test it on my environment if the problem comes from mac/XCode update.
> 
> try building with lower version of iOS and possibly with XCode 15 to see if you still get the same error. Not really sure if it is possible to downgrade XCode version but you can try to build the project for iOS 17 device simulator.
> 
> This will help to figure out where the problem lies.

I understand your point, thanks for answering,
But guys, I think you should upgrade to the latest Mac OS, xCode and so on, 
All our mac devices in the company were upgraded to the latest OS's, 
Is it possible to download earlier versions of xCode?
(the iOS thing and mac os is of course not something which I can downgrade)

**Comment by bwomsm1** [comment]
> > I must say that it does working with some other devices, but I don't understand what is wrong with that device?
> 
> could be specific to XCode 16 update? I am yet to upgrade macOS so I cannot really test it on my environment if the problem comes from mac/XCode update.
> 
> try building with lower version of iOS and possibly with XCode 15 to see if you still get the same error. Not really sure if it is possible to downgrade XCode version but you can try to build the project for iOS 17 device simulator.
> 
> This will help to figure out where the problem lies.

Crazy apple team:
![Screenshot 2024-10-09 at 18 57 47](https://github.com/user-attachments/assets/aa29d2c4-66dd-4d07-8e3c-69a0b1f59072)

I cannot install older xcode on Mac latest of

**Comment by mykola-mokhnach** [comment]
> [38;5;46m[8bf26d97][0m[38;5;79m[XCUITestDriver@9e24][0m Error: xcodebuild failed with code 70. This usually indicates an issue with the local Xcode setup or WebDriverAgent project configuration or the driver-to-platform version mismatch. Consider setting 'showXcodeLog' capability to true in order to check the Appium server log for build-related error messages.

Have you tried to do what's advised in the error message?

**Comment by bwomsm1** [comment]
> showXcodeLog

When I run with `showXcodeLog`, where do I see the logs in? in Appium server log?
thanks.

**Comment by bwomsm1** [comment]
> > �[38;5;46m[8bf26d97]�[0m�[38;5;79m[XCUITestDriver@9e24]�[0m Error: xcodebuild failed with code 70. This usually indicates an issue with the local Xcode setup or WebDriverAgent project configuration or the driver-to-platform version mismatch. Consider setting 'showXcodeLog' capability to true in order to check the Appium server log for build-related error messages.
> 
> Have you tried to do what's advised in the error message?

I created additional 2 logs, on both I have `showXcodeLog = true`:<br>
Failure **with** `usePreinstalledWDA = true`: https://github.com/bwomsm1/AppiumLogs/blob/master/with_usePreinstalledWDA.log
<br>
Failure **without** `usePreinstalledWDA` flag: https://github.com/bwomsm1/AppiumLogs/blob/master/withOUT_usePreinstalledWDA.log

**Comment by mykola-mokhnach** [comment]
>[614edc67][Xcode] /Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 18.1, but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')

This error message seems pretty clear. Update the platformVersion to satisfy the above range.

**Comment by bwomsm1** [comment]
> > [614edc67][Xcode] /Users/boazwarshawsky/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 18.1, but the range of supported deployment target versions is 12.0 to 18.0.99. (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
> > [614edc67][Xcode] xcodebuild: error: Failed to build project WebDriverAgent with scheme WebDriverAgentRunner.: Cannot test target “WebDriverAgentRunner” on “qa_iphone_06”: qa_iphone_06’s iOS 18.0.1 doesn’t match WebDriverAgentRunner’s iOS 18.1 deployment target.
> 
> This error message seems pretty clear. Update the platformVersion to satisfy the above range.

**Shame on me!**

<br>
@mykola-mokhnach I really appreciate your kindness and sharpness, my issue is indeed the `platformVersion = 18.1` to change to `platformVersion = 18.0.1`.

Thank you !
