### ISSUE TITLE
why appium  delete the session?   appium  : Delete session command

### ISSUE THREAD

**Issue by huaianlb** [appium/appium#20661]
[Appium] Welcome to Appium v1.15.1
[Appium] Non-default server args:
[Appium]   allowInsecure: {
[Appium]   }
[Appium]   denyInsecure: {
[Appium]   }
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
10-14 11:25:41.393 30596 30634 I appium  : channel read invoked!
10-14 11:25:41.394 30596 30634 I appium  : channel read: DELETE /wd/hub/session/73c7965c-32af-44f1-b07f-39c1c59f1a0c
10-14 11:25:41.399 30596 30634 I appium  : Delete session command
10-14 11:25:41.406 30596 30634 I appium  : Stopping uiautomator2 io.appium.uiautomator2.http io.appium.uiautomator2.server
10-14 11:25:41.410 30596 30634 I appium  : AppiumResponse: {"sessionId":"73c7965c-32af-44f1-b07f-39c1c59f1a0c","value":null}
10-14 11:25:41.565 30596 30618 I TestRunner: finished: startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server)
10-14 11:25:41.571 30596 30596 I MonitoringInstr: Activities that are still in CREATED to STOPPED: 0
10-14 11:25:41.574 30596 30618 I TestRunner: run finished: 1 tests, 0 failed, 0 ignored
10-14 11:25:41.614 30812 30815 I cmd     : oneway function results will be dropped but finished with status OK and parcel size 4
10-14 11:25:41.717 30820 30822 I cmd     : oneway function results will be dropped but finished with status OK and parcel size 4
10-14 11:25:41.892 30596 30596 I MonitoringInstr: Activities that are still in CREATED to STOPPED: 0
10-14 11:25:41.892 30596 30618 I MonitoringInstr: waitForActivitiesToComplete() took: 0ms
10-14 11:25:41.895   396 28059 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@f931d7e
10-14 11:25:41.896 30596 30622 V UiAutomation: Init UiAutomation@f174e9[id=-1, flags=0]
10-14 11:25:41.903   396   410 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10201 user=0: finished inst
10-14 11:25:41.905 30581 30581 D AndroidRuntime: Shutting down VM
10-14 11:25:41.907   396   410 I ActivityManager: Killing 30596:io.appium.uiautomator2.server/u0a201 (adj 0): stop io.appium.uiautomator2.server due to finished inst

**Comment by KazuCocoa** [comment]
> [Appium] Welcome to Appium v1.15.1

The version is very old. Please try out the latest Appium and issue bug template to give proper information
