### ISSUE TITLE
bug: After updating XCUITest to 7.27.1 version, I couldn't find an element for push notifications

### ISSUE THREAD

**Issue by SongQA** [appium/appium#20662]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Previously, push notifications were identified as "name = NotificationShortLookView".

This time, after updating to Xcode16, XCUITest has also been updated to 7.27.1 version.

I haven't been able to find elements of push notification and cystim pop-up as inspectors since the update.

### Expected Behavior

It should be able to find elements of push notification and system pop-up with inspector.

### Minimal Reproducible Example

Notification consent pop-ups after application execution are also not being identified.

### Environment

- Operating system: MacOS 14.5
- Appium server version (output of `appium --version`): 2.11.3
- Appium driver(s) and their version(s) (`appium driver list`): xcuitest@7.27.1
- Appium plugin(s) and their version(s) (`appium plugin list`): images@2.1.8
- Node.js version (output of `node --version`): v22.7.0
- `npm` version (output of `npm --version`): v10.8.2
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS 18
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#interact-with-dialogs-managed-by-comapplespringboard might help

**Comment by SongQA** [comment]
- Identify system pop-up elements : [respectSystemAlerts setting](https://appium.github.io/appium-xcuitest-driver/latest/reference/settings/) to true
- Identify push elements : [mobile: activateApp](https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-activateapp), "com.apple.springboard"

It works for me. Thank you!
