### ISSUE TITLE
Appium plugin execution order

### ISSUE THREAD

**Issue by Simmon12** [appium/appium#20676]
In the Appium plugin ecosystem, if two plugins both override the same method, and the Appium server starts with both plugins activated, what is the execution order?

**Comment by saikrishna321** [comment]
@Simmon12 It handles in the same order given during server start. `plugins=plugin-a,plugin-b` 

Refer this link:
https://discuss.appium.io/t/how-can-you-control-order-of-how-cmds-are-handled-by-appium-when-shared-by-multiple-plugins/40769

Please use the discuss.appium.io for questions. Thanks
