### ISSUE TITLE
bug: <Selectors from iOS connection bar not available>

### ISSUE THREAD

**Issue by gexon92** [appium/appium#20685]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[Initial state]:
- appium with 2.12.0 installed 
-  xcuitest with 7.28.1 installed 
- xcode 16.0 installed

[Procedure]:
- after app under test is open, swipe down the connection menu on iOS 
=> menu opened
- interact with wifi/airplane in the menu 

[Result]:
- none of those selectors are available, when checking the source of the page using "Get source" the previous context is used not the new one

### Expected Behavior

New context to be available. 
In appium inspector the new context is available

### Minimal Reproducible Example

[Procedure]:
- after app under test is open, swipe down the connection menu on iOS 
=> menu opened
- interact with wifi/airplane in the menu 

[Result]:
- none of those selectors are available, when checking the source of the page using "Get source" the previous context is used not the new one

### Environment

- Operating system: 15.0.1 (24A348)
- Appium server version (output of `appium --version`): 2.12.0 
- Appium driver(s) and their version(s) (`appium driver list`): xcuitest: 7.28.1 
- Appium plugin(s) and their version(s) (`appium plugin list`): - 
- Node.js version (output of `node --version`): 22.9.0 
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: ios18 and 17 
- Real device or emulator/simulator: real device

**Comment by eglitise** [comment]
The control center is not part of your application, but instead a part of the iOS springboard. [Please check the XCUITest driver documentation for interacting with springboard items.](https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#interact-with-dialogs-managed-by-comapplespringboard)
I personally use the `defaultActiveApplication` setting approach.

**Comment by gexon92** [comment]
@eglitise  I agree, now, it was working before updates to latest builds an also for different types of alerts within the app, which comes from the OS, seems to be ok. 
And there is a thing. why in appium inspector, even if I start my session using the app, i can still switch to control center and see the selectors.

**Comment by eglitise** [comment]
Yes, this behavior was changed in XCUITest driver 6.0.0.

**Comment by gexon92** [comment]
I see, so there is no way to interact with those elements, unless I open a new session for the iOS sprinboard?

**Comment by eglitise** [comment]
Please check the linked documentation again. `defaultActiveApplication` is a setting, which means you can change its value during a session. There is no need to start a new session.

**Comment by gexon92** [comment]
I see, many thx @eglitise
