### ISSUE TITLE
bug: <title>Failed to create session ios

### ISSUE THREAD

**Issue by pritesh848** [appium/appium#20694]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Failed to create session. An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent. Original error: xcodebuild failed with code 65. This usually indicates an issue with the local Xcode setup or WebDriverAgent project configuration or the driver-to-platform version mismatch. Consider setting 'showXcodeLog' capability to true in order to check the Appium server log for build-related error messages.. Make sure you follow the tutorial at https://appium.github.io/appium-xcuitest-driver/latest/preparation/real-device-config/

### Expected Behavior

session should be created

### Minimal Reproducible Example

I have done appium for mac, it was working fine after 1 week getting this error if I re-setup all it will work using appium 2.11.5

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

[appium log.txt](https://github.com/user-attachments/files/17489513/appium.log.txt)
added appium logs

**Comment by mykola-mokhnach** [comment]
> [XCUITestDriver@15d8] socket hang up[4637d6f0][Xcode]     NSUnderlyingError = "Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402620395 \"A valid provisioning profile for this executable was not found.\" UserInfo={MobileDeviceErrorCode=(0xE8008015), com.apple.dtdevicekit.stacktrace=(\n\t0   DTDeviceKitBase                     0x000000010b4589c8 DTDKCreateNSErrorFromAMDErrorCode + 312\n\t1   DTDeviceKitBase                     0x000000010b481e78 


I assume the error message is pretty much self-descriptive. Make sure WDA sources are properly signed and could be built manually from Xcode. Check https://github.com/appium/appium-xcuitest-driver/blob/master/docs/preparation/real-device-config.md for more details.

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
