### ISSUE TITLE
create unit test for reset & setPreferences & setLocServicesPrefs interop

### ISSUE THREAD

**Issue by dandoveralba** [appium/appium#2071]
We need to create a unit test to verify the scenario:

1) set the language & locale to non-EN
2) walk through an app that requests access to contacts and location services
3) mobile:reset
3) walk through the app again and verify access alerts are shown

**Comment by jlipps** [comment]
closing as too low priority to track. if a bug is reported around this we'll fix and add the test with respect to that issue.
