### ISSUE TITLE
bug: <title>Appium Settings app is not running after 5000ms

### ISSUE THREAD

**Issue by ziguiway** [appium/appium#20725]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用官网示例报错

### Expected Behavior

不报错

### Minimal Reproducible Example

import unittest

from appium import webdriver
from appium.options.android import UiAutomator2Options
from appium.webdriver.common.appiumby import AppiumBy

capabilities = dict(
    platformName='Android',
    automationName='uiautomator2',
    deviceName='Android',
    appPackage='com.android.settings',
    appActivity='.Settings',
    udid="28918606999183",
    settingsWaitTimeout=10000,  # 增加超时
    commandTimeout=10000,  # 增加超时60
    newCommandTimeout=10000,  # 增加超时60
    autoGrantPermissions=True,
    autoAcceptAlerts=True,
    autoWebview=True,
    autoScroll=True,
)

appium_server_url = 'http://localhost:4723'

class TestAppium(unittest.TestCase):
    def setUp(self) -> None:
        self.driver = webdriver.Remote(appium_server_url, options=UiAutomator2Options().load_capabilities(capabilities))

    def tearDown(self) -> None:
        if self.driver:
            self.driver.quit()

    def test_find_battery(self) -> None:
        el = self.driver.find_element(by=AppiumBy.XPATH, value='//*[@text="Battery"]')
        el.click()

if __name__ == '__main__':
    unittest.main()

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

### Further Information

[log.txt](https://github.com/user-attachments/files/17617920/log.txt)
[
[info.txt](https://github.com/user-attachments/files/17617927/info.txt)
](url)

**Comment by mykola-mokhnach** [comment]
> [AndroidUiautomator2Driver@4921] Creating session with W3C capabilities: {
>   "alwaysMatch": {
>     "platformName": "Android",
>     "appium:automationName": "uiautomator2",
>     "appium:deviceName": "Android",
>     "appium:appPackage": "com.android.settings",
>     "appium:appActivity": ".Settings",
>     "appium:udid": "28918606999183",
>     "appium:settingsWaitTimeout": 10000,
>     "appium:commandTimeout": 10000,
>     "appium:newCommandTimeout": 10000,
>     "appium:autoGrantPermissions": true,
>     "appium:autoAcceptAlerts": true,
>     "appium:autoWebview": true,
>     "appium:autoScroll": true
>   },

Not sure if above capabilities make sense - are you sure you want to start Appium Settings as the app under test? It does not have a UI and  is not supposed to be running in foreground.

**Comment by eglitise** [comment]
The capabilities seem fine to me - it's the native Android settings app, not Appium settings. I use the same package and activity in my tests.

**Comment by mykola-mokhnach** [comment]
oh, makes sense. Try to check the logcat output for more details on why Settings app fails to start.

**Comment by ziguiway** [comment]
我把appium的uiautomator驱动切换到uiautomator2@2.45.1解决该问题，`appium driver install uiautomator2@2.45.1`

**Comment by mykola-mokhnach** [comment]
Unfortunately there is nothing more we could help on that without having actual logs
