### ISSUE TITLE
Not able to Start Appium session in iOS simulator with latest XCode 16.1 and latest ios platform - 18.1

### ISSUE THREAD

**Issue by sandy-tpp** [appium/appium#20723]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to create an Appium session from Appium inspector on a runninf iOS simulator, Error is thrown on running xcodebuild for WebDriverAgentRunner.

[d704a883][Xcode] /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stddef.h:64:10: error: Cyclic dependency in module 'DarwinFoundation': DarwinFoundation -> _stddef -> DarwinFoundation (in target 'WebDriverAgentLib' from project 'WebDriverAgent')

[appium-logs.txt](https://github.com/user-attachments/files/17611351/appium-logs.txt)

Attached full log file

### Expected Behavior

WebDriverAgent should be installed and Appium session should be started.

### Minimal Reproducible Example

1. Install latest Appium, Xcode, ios platform
2. Start ios Simulator
3. Open Appium inspector and use below capabilities to start session:
```
{
  "appium:platformName": "iOS",
  "appium:automationName": "XCUITest",
  "appium:udid": "ED18BCAD-9713-4962-B4EE-E3F23A36B1DD",
  "appium:showXcodeLog": true,
}
```

### Environment

- Operating system: Mac OS
- Appium server version (output of `appium --version`): 2.12.1
- Appium driver(s) and their version(s) (`appium driver list`): - xcuitest@7.28.3 [installed (npm)]
- Appium plugin(s) and their version(s) (`appium plugin list`): none
- Node.js version (output of `node --version`): v19.2.0
- `npm` version (output of `npm --version`): 9.2.0
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS platform 18.1 . Tried with multiple simulators - 18.1, 18.0, 17.5
- Real device or emulator/simulator: Simulator

**Comment by mykola-mokhnach** [comment]
The error looks like an issue with Xcode itself. Maybe try another Xcode version.

**Comment by KazuCocoa** [comment]
I had no issue with XCUITest driver v7.28.3 with:
- Xcode 16.1 build 16B40
- iOS simulator 18.1
- macOS 14.5 (23F79) on M3

Perhaps you could check if the same error occurs via Xcode directly as well. Then, clearing the local `/Users/<local uesr name>/Library/Developer/Xcode/DerivedData` would help to avoid local caching stuff.

**Comment by sandy-tpp** [comment]
> I had no issue with XCUITest driver v7.28.3 with:
> 
> * Xcode 16.1 build 16B40
> * iOS simulator 18.1
> * macOS 14.5 (23F79) on M3
> 
> Perhaps you could check if the same error occurs via Xcode directly as well. Then, clearing the local `/Users/<local uesr name>/Library/Developer/Xcode/DerivedData` would help to avoid local caching stuff.

Except for macOS version, rest is same. My mac version is 15.0, tried with 15.1 too. The error is there when Appium builds WebDriverAgentRunner with xcodebuild. When I build the  WebDriverAgentRunner with xcode it's working fine.

**Comment by sandy-tpp** [comment]
It worked! 
Thank you @Dan-Maor for pointing it out. Even after switching path in xcode-select some SDKs were picked from `/Library/Developer/CommandLineTools`. I had to remove this folder entirely and xcodebuild started picking from Xcode app folder.
