### ISSUE TITLE
bug: Software keyboard won't be shown in headless mode after fb_clearTextWithSnapshot is called

### ISSUE THREAD

**Issue by ppken** [appium/appium#20727]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using headless mode (`appium:isHeadless: true`) with `xcode16` and simulator, software keyboard won't be shown after the WDA's method `fb_clearTextWithSnapshot` is called.

In headful mode, the problem didn't occur. Software keyboard is shown even after `fb_clearTextWithSnapshot` is called.

### Expected Behavior

Software keyboard is shown even after `fb_clearTextWithSnapshot` is called in headless mode with xcode16.

### Minimal Reproducible Example

In the taken screenshot, software keyboard is not shown. But if you use `appium:isHeadless: true`, it is shown.
```javascript
const {remote} = require('webdriverio');
const fs = require('fs');

const capabilities = {
  "platformName": "iOS",
  "appium:useJSONSource": true,
  "appium:automationName": "XCUITest",
  "appium:platformVersion": "18.0",
  "appium:deviceName": "iPhone 12",
  "appium:isHeadless": true,
  "appium:app": "/path/to/UIKitCatalog.app",
};

const wdOpts = {
  hostname: process.env.APPIUM_HOST || '127.0.0.1',
  port: parseInt(process.env.APPIUM_PORT, 10) || 4723,
  logLevel: 'info',
  capabilities,
};

async function runTest() {
  const driver = await remote(wdOpts);
  try {
    let target = await driver.$("//XCUIElementTypeStaticText[@name='Text Fields']/preceding-sibling::XCUIElementTypeOther[2]/XCUIElementTypeOther[1]");
    await target.click();
    target = await driver.$("(//XCUIElementTypeOther[@name='TINTED'])[1]/preceding-sibling::XCUIElementTypeCell[1]/XCUIElementTypeTextField[1]");
    await target.setValue('sample text');
    await driver.pause(1000);
    await target.clearValue();
    const screenshot = await driver.takeScreenshot();
    const tmp = Buffer.from(screenshot, 'base64');
    fs.writeFileSync("screenshot.png", tmp)
  } finally {
    await driver.pause(1000);
    await driver.deleteSession();
  }
}

runTest().catch(console.error);
```

### Further Information

As far as I checked, [this text clear logic](https://github.com/appium/WebDriverAgent/blob/v8.9.4/WebDriverAgentLib/Categories/XCUIElement%2BFBTyping.m#L172-L175) is causing this problem since when I removed it, software keyboard was shown even after `fb_clearTextWithSnapshot` was called.

Can I send a PR not to use above text clear logic in xcode 16 (or later)?

**Comment by mykola-mokhnach** [comment]
Does the keyboard show up after the field is clicked again or it disappears and does not appear anymore after calling clearValue?

**Comment by ppken** [comment]
@mykola-mokhnach 
> Does the keyboard show up after the field is clicked again or it disappears and does not appear anymore after calling clearValue?

It disappears and does not appear anymore after calling clearValue. Keyboard won't show up after the text field is clicked again.

**Comment by mykola-mokhnach** [comment]
It looks more like an issue with headless simulator itself, although I don't think that Apple is ever going to address it. We might consider adding a setting that allows to customise this behavior and disable the HID hack whenever necessary

**Comment by ppken** [comment]
@mykola-mokhnach 
Thank you for your confirmation.

> We might consider adding a setting that allows to customise this behavior and disable the HID hack whenever necessary

May I send a PR to add a setting / capability to enable / disable the HID hack?

**Comment by mykola-mokhnach** [comment]
Of course. Also, feel free to ask any dev-related question in our [Slack](appium.slack.com)

**Comment by mykola-mokhnach** [comment]
Closed as fixed.
