### ISSUE TITLE
bug: [Android] optionalIntentArguments is not passed into app with mobile: startActivity

### ISSUE THREAD

**Issue by szarlatan** [appium/appium#20730]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When opening the application with 

`await driver.execute('mobile: startActivity', { intent: 'com.acme/com.acme.MainActivity', extras: [ ['s', 'disableLogbox', '1'] ] })`

it triggers the following `start-activity` command which does not pass extras to the app: `adb -P 5037 -s R5CR80ZJHMH shell am start-activity com.acme/com.acme.MainActivity --es disableLogbox 1`

### Expected Behavior

While initial launch after creating the test session, or during opening the app session using Appium inspector following command is called `start` command `adb -P 5037 -s R5CR80ZJHMH shell am start -W -n com.acme/com.acme.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 --es disableLogbox 1`, which passes the extras as expected.

### Minimal Reproducible Example

n/a

### Environment

- Operating system: `Sonoma 14.7.1 (23H222)`
- Appium server version (output of `appium --version`): `2.12.0`
- Appium driver(s) and their version(s) (`appium driver list`): `uiautomator2@3.8.0 (automationName 'UiAutomator2')`, `xcuitest@7.27.1 (automationName 'XCUITest')`
- Appium plugin(s) and their version(s) (`appium plugin list`): `n/a`
- Node.js version (output of `node --version`): `v18.17.0`
- `npm` version (output of `npm --version`): `9.6.7`
- Last component(s) version which did _not_ exhibit the problem: `unknown`
- Platform and version under test: `Android 14`
- Real device or emulator/simulator: `Samsung Galaxy S21 (SM-G991B)`
- adb: `Android Debug Bridge version 1.0.41, Version 35.0.2-12147458`

### Link to Appium Logs

https://gist.github.com/szarlatan/62af94c6499885c4a3e6de5143cadb1f

### Further Information

I found [this issue](https://github.com/appium/appium/issues/20415) that suggests to use `mobile: startActivity` but it looks like it now calls wrong activity manager function, as I haven't found `adb shell am start-activity` anywhere in Android documentation.

You can find app launching in log:
- with test session in lines: 171 (initial), 212 (after restart, so using `mobile: startActivity` script)
- with Inspector in line 174

**Comment by szarlatan** [comment]
Made a workaround for now using `mobile: shell` with bunch of arguments covering the working solution of `adb shell am start`

**Comment by KazuCocoa** [comment]
You could find out the `start-activity` in `am` command's help:
```
% adb shell am
Activity manager (activity) commands:
  help
      Print this help text.
  start-activity [-D] [-N] [-W] [-P <FILE>] [--start-profiler <FILE>]
          [--sampling INTERVAL] [--clock-type <TYPE>] [--streaming]
          [-R COUNT] [-S] [--track-allocation]
          [--user <USER_ID> | current] [--suspend] <INTENT>
      Start an Activity.  Options are:
      -D: enable debugging
      --suspend: debugged app suspend threads at startup (only with -D)
      -N: enable native debugging
      -W: wait for launch to complete
      --start-profiler <FILE>: start profiler and send results to <FILE>
      --sampling INTERVAL: use sample profiling with INTERVAL microseconds
          between samples (use with --start-profiler)
      --clock-type <TYPE>: type can be wall / thread-cpu / dual. Specify
          the clock that is used to report the timestamps when profiling
          The default value is dual. (use with --start-profiler)
      --streaming: stream the profiling output to the specified file
          (use with --start-profiler)
      -P <FILE>: like above, but profiling stops when app goes idle
      --attach-agent <agent>: attach the given agent before binding
      --attach-agent-bind <agent>: attach the given agent during binding
      -R: repeat the activity launch <COUNT> times.  Prior to each repeat,
          the top activity will be finished.
      -S: force stop the target app before starting the activity
      --track-allocation: enable tracking of object allocations
      --user <USER_ID> | current: Specify which user to run as; if not
          specified then run as the current user.
      --windowingMode <WINDOWING_MODE>: The windowing mode to launch the activity into.
      --activityType <ACTIVITY_TYPE>: The activity type to launch the activity as.
      --display <DISPLAY_ID>: The display to launch the activity into.
      --splashscreen-icon: Show the splash screen icon on launch.
```

Lower than api level 26 Android have `start`. So Appium follows the command's documentation by OS.
https://github.com/appium/appium-adb/blob/1b7e85903ecb09104b539d4b723e375235b83e3a/lib/tools/apk-utils.js#L1215

**Comment by KazuCocoa** [comment]
With my previous comment,
```
driver.execute_script 'mobile: startActivity', {
    wait: true,
    stop: true,
    action: 'android.intent.action.MAIN',
    component: 'com.acme/com.acme.MainActivity',
    categories: ['android.intent.category.LAUNCHER'],
    flags: '0x10200000',
    extras: [['s', 'disableLogbox', '1']]
}
```

generates:

```
adb -P <user> -s <device> shell am start-activity -W -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -n com.acme/com.acme.MainActivity --es disableLogbox 1 -f 0x10200000'
```

for API Level 26+ and `start` for lower than the version so I guess `optionalIntentArguments` in capabilities is not necessary for this case

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Could you please add the above example to the docs? I think it would be useful for other people to observe how an actual shell command may be transformed to method args

**Comment by KazuCocoa** [comment]
That's just that we missed something, or the one used in the session creation is still using legacy code. No diff technically, so they are fine.
Yea, I guess Google hasn't updated public docs yet to avoid explaining differences between OS versions since newer one still accept the old syntax. Once they drop lower versions, I guess they will update the public doc.
