### ISSUE TITLE
bug: xcuitest driver fails to click in the right place

### ISSUE THREAD

**Issue by JonathanWylie** [appium/appium#20731]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using  nativeWebTapStrict and calibrateWebToRealCoordinatesTranslation sometimes the coordinates clicked on are wrong.
In particular, the test is filling in a form with small inputs. Safari will zoom in automatically. Then when it gets to click on a submit button, it clicks in the wrong place.
This is because the calibration is now wrong after the zoom. It's not practical to re-calibrate mid zoom.

### Expected Behavior

It should click in the correct place, after noticing the zoom change.

### Minimal Reproducible Example

Sorry not a full code example.
But the steps required to recreate are this:

Load: "https://httpbin.org/forms/post"
Type: "name" into input box with name="custname"
Close: Keyboard
Click: button with xpath="//button[contains(., 'Submit order')]"

### Environment

- Operating system:
- Appium server version: 2.12.0
- Appium driver(s) and their version(s) (`appium driver list`):
    xcuitest@7.28.1 (automationName 'XCUITest')
    uiautomator2@3.8.0 (automationName 'UiAutomator2')
- Appium plugin(s): No plugins
- Node.js version: v22.9.0
- `npm` version: 10.8.3
- Platform:
    iPhone
    ios 18.0
    ios simulator

### Further Information

If the viewport meta tag is: `<meta name="viewport" width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no`

then some zooming still seems to happen, but clicking starts to work.

**Comment by mykola-mokhnach** [comment]
> This is because the calibration is now wrong after the zoom. It's not practical to re-calibrate mid zoom.

Unfortunately there is no other way to precisely calculate coordinates transformation. You may also consider performing a manual calculation and clicking by coordinates as I don't think we could do much there from the driver perspective.

**Comment by JonathanWylie** [comment]
Unfortunately I can't find it, but I thought I saw @mykola-mokhnach say there may be a way to calculate without calibrating. Something about using an overlay.

**Comment by mykola-mokhnach** [comment]
There are alternatives, although neither of them guarantees 100% accuracy or the absence of side effects.
You are welcome to propose a PR if you could confirm this strategy works well or is more reliable in comparison to the current approach

**Comment by mykola-mokhnach** [comment]
Closed as third party issue
