### ISSUE TITLE
bug: 'noReset' : 'false' doesn't work for ios devices

### ISSUE THREAD

**Issue by dudn521** [appium/appium#20748]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ios device was not reset.

### Expected Behavior

ios device was reset.

### Minimal Reproducible Example

Run pytest to open the software without any other operations

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by mykola-mokhnach** [comment]
Please provide a proper issue description

**Comment by KazuCocoa** [comment]
Please check noReset and fullReset description in https://appium.github.io/appium-xcuitest-driver/latest/reference/capabilities/ (and https://appium.github.io/appium-xcuitest-driver/latest/guides/troubleshooting/#leftover-application-data-on-real-devices linked to their description) for real devices as well (if yours were real devices)

**Comment by mykola-mokhnach** [comment]
Closed because of no response
