### ISSUE TITLE
[Feat]: introduce Appium Bidi event for notifying mobile context changes

### ISSUE THREAD

**Issue by christian-bromann** [appium/appium#20741]
**Is your feature request related to a problem? Please describe.**
A lot of commands and automation behavior depends on the mobile context someone is in, e.g. native or web context. Currently we can only determine the state of the context by making an extra command call. Requesting the current context can become a common pattern for automation frameworks like WebdriverIO, e.g. for every element interaction in iOS we may want to scroll the element into view beforehand and need to know if we are in native context to understand if this is required.

**Describe the solution you'd like**
With Appium adopting Bidi capabilities, we can use them to have Appium share more information about the mobile environment. In order to avoid making these context calls it would be awesome if Appium could just have an event that is triggered:

1. when the session starts in order to set the initial context the user is in
2. whenever the user switches the context (manually or through the device)

This would make things a lot easier on the framework side.

**Describe alternatives you've considered**
We currently determine the initial context by looking into the capabilities and then have a command listener that fetches the context data whenever the user switches it. I am not sure though if this is the best approach: can we be 100% that we can assume the right context from the capabilities? Are there scenarios where the context changes without the user calling the command?

**Additional context**
We are adding more mobile commands to WebdriverIO to simplify mobile automation and came across this DX problem.

**Comment by mykola-mokhnach** [comment]
@christian-bromann Would you propose creating a new event for this purpose or use an existing from https://w3c.github.io/webdriver-bidi/ ? If a custom event would be used then would it be possible to provide its model?

**Comment by mykola-mokhnach** [comment]
The event has been added to both UIA2 and xcuitest drivers. The event schema was set according to the above comment, just the event name has been changed to `appium.contextUpdated`, so it's in sync with other BiDi events naming schema, where all events are in the past, for example `log.entryAdded`.
