### ISSUE TITLE
bug: Setting _TESTING=1 environment variable causes ReferenceError to MOCK_LOG

### ISSUE THREAD

**Issue by pathwirejames** [appium/appium#20749]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Attempting to use `appium-adb` package with the `_TESTING` environment variable set to `1` causes a JavaScript error: `ReferenceError: Cannot access 'MOCK_LOG' before initialization`

If `_TESTING=1` is left unset, the code works as expected.

### Expected Behavior

The call to `ADB.createADB()` completes without error, and the `_TESTING=1` environment variable omits the extra logging output.

### Minimal Reproducible Example

https://gist.github.com/pathwirejames/a46d590e78643d926405712441b02ed2

### Environment

- Operating system: MacOS 14.5
- Appium server version (output of `appium --version`): 2.12.1
- Appium driver(s) and their version(s) (`appium driver list`):  uiautomator2@3.8.2
- Appium plugin(s) and their version(s) (`appium plugin list`): (none)
- Node.js version (output of `node --version`): v20.10.0
- `npm` version (output of `npm --version`): 10.2.3
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: Android, version n/a
- Real device or emulator/simulator: n/a

### Link to Appium Logs

https://gist.github.com/pathwirejames/54661e530ab5b97da6b2dd9736861cf5

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/pull/20750 should fix that

**Comment by mykola-mokhnach** [comment]
The new server version including this fix has been published
