### ISSUE TITLE
Random timeout error after Xcode upgrade, retrieve the /status response from the WebDriverAgent server after 10000ms timeout

### ISSUE THREAD

**Issue by abhijeetkange** [appium/appium#20758]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not able to start appium inspector and log says "Encountered internal error running command: Error: Unable to launch WebDriverAgent. Original error: Unable to start WebDriverAgent: Error: We were not able to retrieve the /status response from the WebDriverAgent server after 10000ms timeout.Try to increase the value of 'appium:wdaLaunchTimeout' capability as a possible workaround.. Make sure you follow the tutorial at https://appium.github.io/appium-xcuitest-driver/latest/preparation/real-device-config/"  
--Increased the WDA Launch timeout from 6000 to 10000 but still giving same error.

### Expected Behavior

Should able to inspect the element using appium inspector. Even i execute my code it should start the execution but webdriver agent app not get installed and it gives above error 

### Minimal Reproducible Example

Desired capabilities for Appium Inspector 
{
  "appium:deviceName": "Abhijeet’s iPhone",
  "platformName": "iOS",
  "appium:platformVersion": "18.1",
  "appium:udid": "00008120-***********",
  "appium:noReset": true,
  "appium:automationName": "XCUITest",
  "appium:bundleId ": "com.***.****.dev",
  "appium:app": "/Users/abhijeetkange/Downloads/VM.ipa",
  "appium:settings[customSnapshotTimeout]": "1000",
  "appium:snapshotMaxDepth": "1000",
  "appium:wdaLaunchTimeout": "10000"
}

### Environment

- Operating system:MacOS-15.0.1 
- Appium server version (output of `appium --version`):2.12.1
- Appium driver(s) and their version(s) (`appium driver list`):xcuitest@7.32.0 
- Appium plugin(s) and their version(s) (`appium plugin list`):no plugins 
- Node.js version (output of `node --version`):v20.18.0
- `npm` version (output of `npm --version`):10.8.2
- Last component(s) version which did _not_ exhibit the problem: After Xcode , MacOS and Iphone 18.1 update it started giving the error 
- Platform and version under test: 
- Real device or emulator/simulator:Real Device Iphone 14 Pro Max

### Further Information

<img width="1505" alt="Screenshot 2024-11-18 at 3 04 35 PM" src="https://github.com/user-attachments/assets/def0e2ab-9922-4e5d-b41c-80b5c457db52">

**Comment by mykola-mokhnach** [comment]
I assume 10 seconds is not enough to compile the tool. Try to compile WDA in Xcode manually and see how long it takes then bump the value in capabilities (usually 2-3 minutes should be enough if the build is not cached yet).

I would also enable the `showXcodeLog` capability to see the actual xcode output

**Comment by mykola-mokhnach** [comment]
Closed because of no rsponse
