### ISSUE TITLE
Unable to inspect SwiftUI view embedded inside UITableView

### ISSUE THREAD

**Issue by rahulnair199131** [appium/appium#20759]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have been trying to migrate screens that were developed using UITool Kit to SwiftUI. In the process we have some screens that have SwiftUI embedded inside the UITool kit view. Our developers have defined accessibility ids for all elements in these views and these are inspectable using the native iOS xcode inspector. However when i try inspecting it with the appium inspector i get an empty list with no elements in the hierarchy tree. Attaching a screenshot of the element when inspecting through the native xcode accessibility inspector,

Attaching a screenshot of the same screen when inspected through the appium inspector,

I get the same response attached above when i try inspecting the app using the native Xcode accessibility inspector after WebDriver agent is installed. 

**Appium Version - 2.12.1**
**WebDriver Agent - Latest version from the WeDriver agent repo**
**Simulator OS - 18.1**
**Appium inspector version - 2023.12.2**

### Expected Behavior

I should be able to inspect elements that have been developed using SwiftUI embedded inside UITool kit.

### Minimal Reproducible Example

**Appium Version - 2.12.1**
**WebDriver Agent - Latest version from the WeDriver agent repo**
**Simulator OS - 18.1**
**Appium inspector version - 2023.12.2**

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
Could XCTest by Apple find the element? Appium depends on XCTest's element tree retrieval, which could be different from Xcode's view hierarchy.

e.g.

> The 60 depth maximum was added to prevent apps from slowing down system performance when UI queries occur during an XCTest UI test. Unfortunately React Native often creates nested hierarchies that are larger than 60 levels of depth on iOS. That said, you should be able to use webdriverIO for testing, which would not face this 60 depth maximum limit.

https://developer.apple.com/forums/thread/749918?answerId=800794022#800794022

**Comment by ArunVicky001** [comment]
@KazuCocoa adding similar issue which I facing https://github.com/appium/appium/issues/9249#issuecomment-2476027026

**Comment by KazuCocoa** [comment]
> Could XCTest by Apple find the element? Appium depends on XCTest's element tree retrieval, which could be different from Xcode's view hierarchy.

Did you confirm that vanilla XCTest had no issue? Technically Appium/WDA's element handling depends on the XCTest by Apple. https://appium.github.io/appium-xcuitest-driver/latest/reference/execute-methods/#mobile-source `format: description` also help to check what the element is. If the element is not in the result, it is possibly XCTest framework-related. Repositing it to Apple with a minimal implementation will help Apple to fix it potentially. I'm not sure how the SwiftUI is pretty mature today. (I saw in the past SwitUI implementation missed accessibility stuff before unlike UIKit)

**Comment by rahulnair199131** [comment]
Hi @KazuCocoa i tried printing the UI element hierarchy using `driver.executeScript("mobile:source", Map.ofEntries(Map.entry("format","description")))`. Was not able to see the nested elements in the output. Will also check once in XCTest and see if this is still the case.

**Comment by rahulnair199131** [comment]
Closing this issue as we have found an alternative to this.

**Comment by ArunVicky001** [comment]
I had fixed this issue by setting below property to hosting view controller view 
            ```
            view.isAccessibilityElement = true
            view.accessibilityIdentifier = "viewidentifier"
```

**Comment by KazuCocoa** [comment]
`accessibilityIdentifier` is well known, but think [isAccessibilityElement](https://developer.apple.com/documentation/uikit/uiaccessibilityelement/1619580-isaccessibilityelement) is helpful

> The default value for this property is NO. If the receiver is a UIKit control, the default value is YES.

**Comment by ArunVicky001** [comment]
but it's not accepting the tab event. since that control's visible is false

**Comment by mykola-mokhnach** [comment]
Closed as not an issue

**Comment by ArunVicky001** [comment]
@rahulnair199131 is that @KazuCocoa suggestion works for you?
