### ISSUE TITLE
[Feat]: Native Binary Support

### ISSUE THREAD

**Issue by firefinchdev** [appium/appium#20756]
**Is your feature request related to a problem? Please describe.**
Is it possible that appium can provide binaries that run directly on the system, without having to use npm to install appium.

**Describe the solution you'd like**
We can utilize [pkg](https://www.npmjs.com/package/pkg) (along with [esbuild](https://www.npmjs.com/package/esbuild)) or something similar to this for packaging appium in a binary executable.

**Comment by mykola-mokhnach** [comment]
We don't have any plans about having such feature. Feel free to propose a PR if you'd like to implement it yourself.

**Comment by eglitise** [comment]
IMO native binaries also don't really make sense with Appium's modular architecture. Appium on its own doesn't really do anything, and you would need to download at least one driver, whose installation is primarily done using npm.
