### ISSUE TITLE
bug: Appium returns the incorrect UI states of the element

### ISSUE THREAD

**Issue by srajendran123** [appium/appium#20769]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The application has a sign-in page. The submit button is disabled until the credentials are entered. However, Get element attribute for that submit button returns true for the 'enabled' property, even when the button is disabled.

### Expected Behavior

Appium displays the correct UI state of the element

### Minimal Reproducible Example

         Click Element          //XCUIElementTypeButton[@name="Don’t Allow"]
         Click element           //XCUIElementTypeButton[@name="Menú de navegación de hamburguesas"]
	Click element           //XCUIElementTypeStaticText[@name="Iniciar sesión"]
	Sleep       5s
	${temp}             Get Element Attribute           	//XCUIElementTypeButton[@name="INICIAR SESIÓN"]            enabled
	Log to Console          ${temp}

${temp} returns true

### Environment

- Operating system:  mac
- Appium server version (output of `appium --version`):   AppiumLibrary 2.1.0
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):  20.11.1
- `npm` version (output of `npm --version`):  10.2.4
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test: iOS Phone 15 and 17.5
- Real device or emulator/simulator: Real device

### Further Information

[log.html.zip](https://github.com/user-attachments/files/17836364/log.html.zip)

Also, Appium Inspector displays the enabled as true irrespective of the button state (ie., enabled = true even when the button is disabled).
![Screen Shot 2024-11-20 at 11 04 10 AM](https://github.com/user-attachments/assets/c623de93-b8b0-4333-aa07-f1a1691ef148)

**Comment by mykola-mokhnach** [comment]
We do not have any control over what is returned by the app under test to the accessibility layer. See the comment to the similar [issue](https://github.com/appium/appium/issues/20759#issuecomment-2484866721) fore more details.


Closed as third party issue
