### ISSUE TITLE
Unable to start appium server GUI by Azure devops pipeline in Microsoft hosted agent 

### ISSUE THREAD

**Issue by JanbaskDevops** [appium/appium#20771]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are getting issue while setting up connection-

Error Message-
ERROR] TestcaseName >BaseClassTest.configAppium:51 » SessionNotCreated Could not start a new session. Response code 404. Message: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource

### Expected Behavior

We should get connection and testcase execution should start

### Minimal Reproducible Example

Not applicable, it's generic suggestion.

### Environment

Mac hosted agent

**Comment by eglitise** [comment]
Appium Server GUI has been deprecated for nearly 2 years, and is also not compatible with Appium 2.
Please use [Appium Inspector](https://github.com/appium/appium-inspector) instead.
