### ISSUE TITLE
No such context found. when running appium within docker

### ISSUE THREAD

**Issue by RedaV88** [appium/appium#20782]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

        options.setCapability("appium:remoteAdbHost","host.docker.internal");
        options.setCapability("autoWebview", true);
        driver = new AndroidDriver(new URL("http://127.0.0.1:4723/"), options);
        
        giving
        Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 400. Message: No such context found. 
        
        local run (without docker) works fine

### Expected Behavior

webview is recognized while running within docker appium

### Minimal Reproducible Example

10/10

### Environment

- Operating system:
- Appium server version (output of `appium --version`):
- Appium driver(s) and their version(s) (`appium driver list`):
- Appium plugin(s) and their version(s) (`appium plugin list`):
- Node.js version (output of `node --version`):
- `npm` version (output of `npm --version`):
- Last component(s) version which did _not_ exhibit the problem:
- Platform and version under test:
- Real device or emulator/simulator:

**Comment by KazuCocoa** [comment]
Please attach the full appium server log

**Comment by RedaV88** [comment]
Sure, here is code
```
 AndroidDriver driver;

        UiAutomator2Options options = new UiAutomator2Options();
        options.setDeviceName("Android Device");
        options.setPlatformName("Android");
        options.setAutomationName(AutomationName.ANDROID_UIAUTOMATOR2);

        options.setAppPackage("com.here.hnod.client.fieldtest");
        options.setAppActivity("com.here.hnod.client.fieldtest.activities.MainActivity");
        options.setNoReset(true);
        options.setCapability("appium:udid", getDeviceId());
        options.setCapability("appium:remoteAdbHost","host.docker.internal");
        options.setCapability("appium:remoteAdbPort", 5037);
        options.setCapability("autoWebview", true);
         driver = new AndroidDriver(new URL("http://127.0.0.1:4723/"), options);
```
         
         and that's how Im running docker
         
`         docker run --privileged -d -p 4723:4723 -e ANDROID_ADB_SERVER_ADDRESS=host.docker.internal -v /dev/bus/usb:/dev/bus/usb --name appium-container --platform linux/amd64 appium/appium`

here is logfile from docker, attached
[dockerLogs.txt](https://github.com/user-attachments/files/17930726/dockerLogs.txt)

**Comment by KazuCocoa** [comment]
This is chrom/chromedriver's security reason from a remote host request. You could do a similar method to make the request from local host to the chromedriver in #11206. Or as the error message by chromedriver, `remoteAdbHost` can be IP address I guess.

```
024-11-27 00:51:25     validateStatus: [Function: validateStatus],
2024-11-27 00:51:25     headers: Object [AxiosHeaders] {
2024-11-27 00:51:25       Accept: 'application/json, text/plain, */*',
2024-11-27 00:51:25       'Content-Type': undefined,
2024-11-27 00:51:25       'User-Agent': 'axios/1.7.7',
2024-11-27 00:51:25       'Accept-Encoding': 'gzip, compress, deflate, br'
2024-11-27 00:51:25     },
...
2024-11-27 00:51:25       socket: [Socket],
2024-11-27 00:51:25       _header: 'GET /json/version HTTP/1.1\r\n' +
2024-11-27 00:51:25         'Accept: application/json, text/plain, */*\r\n' +
2024-11-27 00:51:25         'User-Agent: axios/1.7.7\r\n' +
2024-11-27 00:51:25         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
2024-11-27 00:51:25         'Host: host.docker.internal:10900\r\n' +
2024-11-27 00:51:25         'Connection: close\r\n' +
2024-11-27 00:51:25         '\r\n',
2024-11-27 00:51:25       _keepAliveTimeout: 0,
...
2024-11-27 00:51:25       [Symbol(kHighWaterMark)]: 16384,
2024-11-27 00:51:25       [Symbol(kRejectNonStandardBodyWrites)]: false,
2024-11-27 00:51:25       [Symbol(kUniqueHeaders)]: null
2024-11-27 00:51:25     },
2024-11-27 00:51:25     data: 'Host header is specified and is not an IP address or localhost.'
2024-11-27 00:51:25   },
2024-11-27 00:51:25   status: 500
2024-11-27 00:51:25 }
```

**Comment by mykola-mokhnach** [comment]
I will add a workaround to it similar to what puppeteer did in https://github.com/puppeteer/puppeteer/issues/2242

**Comment by KazuCocoa** [comment]
I'm not sure if it works for Android's this case but it could do when `remoteAdbHost` is set.

**Comment by RedaV88** [comment]
@KazuCocoa @mykola-mokhnach  can you pls advice what is workaround for this? Or once merge request will be merged the issue will be solved?

**Comment by mykola-mokhnach** [comment]
I think with the above patch you might be able to fetch web view details, but chromedriver itself still does not support the scenario where adb server is running not on localhost. You'd need to change your setup, so that chromedriver and adb server are running on the same host

**Comment by mykola-mokhnach** [comment]
Closed because of no response

**Comment by RedaV88** [comment]
@mykola-mokhnach @KazuCocoa I've updated the uiautomator to the uiautomator2@3.9.1 (it contains your fix)
Now 'no such context issue gone, but I got another one, that device is offline, but 'adb devices' on docker gives me my device. Can you please check what can be possible issue here? Attaching the log file
[log.txt](https://github.com/user-attachments/files/17991143/log.txt)

**Comment by mykola-mokhnach** [comment]
This error is expected as it is coming from Chromedriver itself. See my comment above. You'd need to change your setup to make remote adb host work with chromedriver, for example, by creating a port forward from the remote host.
