### ISSUE TITLE
appium driver install fails for xcuitest

### ISSUE THREAD

**Issue by muvaf** [appium/appium#20796]
I'm getting the following error in both my macOS and docker build happening in Github Actions:
```
> appium driver install xcuitest

✔ Checking if 'appium-xcuitest-driver' is compatible
✖ Installing 'xcuitest' using NPM install spec 'appium-xcuitest-driver'
Error: ✖ Encountered an error when installing package: Cannot find module 'undefined/package.json'
Require stack:
- /Users/muvaf/.appium/noop.js
```

Versions:
```
> appium --version
2.12.1

> npm --version
10.8.2

> node --version
v20.18.0
```

**Comment by enifsieus** [comment]
We are encountering the same problem on MacOS in in Linux container builds installing xcuitest and uiuatomator2 with:

$ appium --version
2.11.5
$ npm --version
10.8.1
$ node --version
v20.16.0

There is no package.json in the subtree where the install is run. This is happening in build pipelines that are unchanged and worked just fine days ago.

**Comment by KazuCocoa** [comment]
I assume support package's parameter naming change affected this behavior. So maybe firstly we should updated the support package's major version or add a new naming and newer appium package needed to use newer version or the new naming method:

https://github.com/appium/appium/pull/20788/files#diff-5a0ff15212d3a9d4c0b14516e9ce13bcb9362748e4ac76eef4403d1b5a8948ba

**Comment by gmariscales** [comment]
We are experiencing the same issue
It can be reproduced by attempting to install any driver from a git source:
`appium driver install --source=git --package appium-uiautomator2-driver@3.9.1 git+ssh://git@github.com:appium/appium-uiautomator2-driver.git`
or
`appium driver install --source=git --package appium-xcuitest-driver@7.32.0 git+ssh://git@github.com:appium/appium-xcuitest-driver.git`

**Comment by KazuCocoa** [comment]
Should be ok for now. Please re-install the same appium version and do the installation.

For the git command, please use latest appium server. I think the case would need https://github.com/appium/appium/pull/20788
