### ISSUE TITLE
bug: xcodebuild exited with code 'null' and signal 'SIGILL'

### ISSUE THREAD

**Issue by candialala** [appium/appium#20806]
### Do I have the most recent component updates?

- [X] I use the most recent available driver/plugin and server versions

### Is the component officially supported by the Appium team?

- [X] I have verified the component repository is present under the Appium organization in GitHub

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

xcodebuild exited when meet "DVTDeveloperPaths: Failed to get length of DARWIN_USER_CACHE_DIR from confstr(3), error = Error Domain=NSPOSIXErrorDomain Code=5 "Input/output error". Using NSCachesDirectory instead." this error.
Then wda couldn't start up.

### Expected Behavior

wda can be started normally

### Minimal Reproducible Example

This problem is probabilistic, but once it occurs, it will always appear this error, and other devices on the same computer are also this error. And I have to restart computer to recover.

But I actually went straight to the computer and started the test with xcodebuild "xcodebuild test-without-building -project ~/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath ~/Library/Developer/Xcode/DerivedData/WebDriverAgent-fefatlpmvhqwtkfiwmprxcqfhoia -destination id=XXXX IPHONEOS_DEPLOYMENT_TARGET=17.4 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO", which was normally, but kept failing to start wda with appium.

### Environment

- Operating system:
- Appium server version (output of `appium --version`): 2.10.3
- Appium driver(s) and their version(s) (`appium driver list`): xcuitest@7.24.15
- Appium plugin(s) and their version(s) (`appium plugin list`): 
- - relaxed-caps@1.0.6 [installed (npm)]
- - images@2.1.2 [installed (npm)]
- Node.js version (output of `node --version`): v16.20.1
- `npm` version (output of `npm --version`): 8.19.4
- Last component(s) version which did _not_ exhibit the problem: 
- Platform and version under test:  iOS
- Real device or emulator/simulator: Real device 17.4

### Link to Appium Logs

https://gist.github.com/candialala/83fbeb0dbd07802d033274555f2a23ba

**Comment by candialala** [comment]
The first log in which this error occurs is  https://gist.github.com/candialala/10e2a71509e8c148b3273ce867db9d67
the user from rcadmin change to ->501

**Comment by KazuCocoa** [comment]
I wondered if the host needed to keep a login session. This could be related to xcodebuild and app signing. What happens to run the same one without app signing capabilities against a simulator (on the same machine) instead of a real device?

**Comment by candialala** [comment]
> I wondered if the host needed to keep a login session. This could be related to xcodebuild and app signing. What happens to run the same one without app signing capabilities against a simulator (on the same machine) instead of a real device?
This is the error on the simulator
<img width="1689" alt="image" src="https://github.com/user-attachments/assets/b0b2cc3f-b2af-4919-9e4b-66ec1ec1b6df">

**Comment by KazuCocoa** [comment]
It could indicate that the environment has some limitations regarding access to simulator services on the macOS. Then, I assume this issue is basically related to the Apple toolchain and login session. What kind of CI env are you using?

**Comment by candialala** [comment]
> * Operating system: Sonoma 14.5
> * Appium server version (output of `appium --version`): 2.10.3
> * Appium driver(s) and their version(s) (`appium driver list`): xcuitest@7.24.15
> * Appium plugin(s) and their version(s) (`appium plugin list`):
> * * relaxed-caps@1.0.6 [installed (npm)]
> * * images@2.1.2 [installed (npm)]
> * Node.js version (output of `node --version`): v16.20.1
> * `npm` version (output of `npm --version`): 8.19.4
> * Last component(s) version which did _not_ exhibit the problem:
> * Platform and version under test:  iOS
> * Real device or emulator/simulator: Real device 17.4

**Comment by KazuCocoa** [comment]
> I directly use terminal to start wda

Do you mean the issue occurred when you started Appium via the same terminal instead of xcodebuild? So, you used the same terminal to start both appium and xcodebuild

**Comment by candialala** [comment]
> > I directly use terminal to start wda
> 
> Do you mean the issue occurred when you started Appium via the same terminal instead of xcodebuild? So, you used the same terminal to start both appium and xcodebuild as same.

I mean I run xcodebuild directly through terminal, it was work.
“xcodebuild test-without-building -project ~/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -derivedDataPath ~/Library/Developer/Xcode/DerivedData/WebDriverAgent-fefatlpmvhqwtkfiwmprxcqfhoia -destination id=XXXX IPHONEOS_DEPLOYMENT_TARGET=17.4 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO”
<img width="1345" alt="image" src="https://github.com/user-attachments/assets/64d4879a-72c2-4454-aa9c-3d63a2a26f34">

But at appium, it meet this error
<img width="1725" alt="image" src="https://github.com/user-attachments/assets/6ae92dac-e63b-4deb-b553-0c884ee49436">

**Comment by KazuCocoa** [comment]
In the Google, `DARWIN_USERCACHE_DIR` error you got was possibly user permission related. For example, xcodebuild's running user and the appium's running user are different. (I have no idea if such a case could occur though)

```
Current user: '501'
```

What is the output of `whoami` from your terminal? `id` command also could help to see user ids and user names on your environment.

This value in your attached appium log prints the result of `whoami`. It is username in generael, but it looks UID in your case. https://github.com/appium/appium-xcuitest-driver/blob/d26c20899dbdfb80a95bba2e96f6789392b6076e/lib/utils.js#L314-L315

**Comment by candialala** [comment]
> In the Google, `DARWIN_USERCACHE_DIR` error you got was possibly user permission related. For example, xcodebuild's running user and the appium's running user are different. (I have no idea if such a case could occur though)
> 
> ```
> Current user: '501'
> ```
> 
> What is the output of `whoami` from your terminal? `id` command also could help to see user ids and user names on your environment.
> 
> This value in your attached appium log prints the result of `whoami`. It is username in generael, but it looks UID in your case.

whoami from terminal is rcadmin, not 501. 501 is the UID of rcadmin.
It first appeared when this case appeared. Can you see it?
https://gist.github.com/candialala/10e2a71509e8c148b3273ce867db9d67

The driver is created three times, the first two times current user is rcadmin, the last time current user is 501. And since then appium has been getting 501. But terminal has been getting rcadmin.

**Comment by KazuCocoa** [comment]
I haven't seen the case, but it looks like the host machine was in weird condition...? What about stopping the appium node process every time? Would using newer nodejs help?

**Comment by candialala** [comment]
> I haven't seen the case, but it looks like the host machine was in weird condition...? What about stopping the appium node process every time? Would using newer nodejs help?

But when I restart appium server, nothing works. It can only be recovered by restarting the computer.

**Comment by KazuCocoa** [comment]
Then, it looks like OS's user handling issue for me, perhaps it is not NodeJS process level (Appium works as a nodejs process)

**Comment by KazuCocoa** [comment]
Closing this issue since this behavior is more OS's user handling rather than Appium itself right now.

Btw, does your machine run nodejs env on native env or on rosetta? (if your env is on Apple Silicon env)
If it was on rosetta, I think it would be worth trying out without rosetta (native arm)
