### ISSUE TITLE
Unable to load Atom 'getElementScreenshot' on IOS

### ISSUE THREAD

**Issue by 7999** [appium/appium#20830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Appium Version

v2.5.4

### Appium Host Type

Command Line

### Is this issue reproducible using the latest components?

- [X] I confirm the issue is still reproducible with the latest component versions

### Current Behavior

can't get element screenshot, but can get app screenshot

### Expected Behavior

able to get element screenshot

### Environment Details

- Debug details (`appium --show-debug-info`):
- Last component version(s) which did _not_ exhibit the problem: n.a.
- Platform and version of device under test: ios 18.0.1 
- Real device or emulator/simulator: real device

### Minimal Reproducible Example

can't provide example, we use real device

### Further Information

[wdio-canvas.log](https://github.com/user-attachments/files/18058622/wdio-canvas.log)
[canvas-appium.log](https://github.com/user-attachments/files/18058626/canvas-appium.log)

**Comment by mykola-mokhnach** [comment]
Please use the most recent server and driver versions

**Comment by 7999** [comment]
still failed on newest version 2.13.1

**Comment by mykola-mokhnach** [comment]
It looks like this functionality was never present in the driver and should be implemented

**Comment by mykola-mokhnach** [comment]
the web element screenshotting feature has been added to XCUITest driver v7.33.0+
