### ISSUE TITLE
Open new tab functionality in iOS driver (XCUITest)

### ISSUE THREAD

**Issue by BhavikaTibrewal** [appium/appium#20848]
We see that the endpoint to open new tab was implemented in [this issue](https://github.com/appium/appium/issues/16749))
But when i try to use this endpoint on ios I receive this error 
![image (4)](https://github.com/user-attachments/assets/6cfab145-03c5-4b6c-9ecf-6644d5b7fdd6)

Script used 
```
import axios from 'axios';
const APPIUM_URL = 'https://hub.browserstack.com/wd/hub/session';
const currentTime = new Date();
const sessionName = `Appium CURL session at ${currentTime}`;
const response = await fetch(APPIUM_URL, {
  method: 'POST',
  body: JSON.stringify({
    capabilities: {
      firstMatch: [{}],
      alwaysMatch: {
        browserName: 'chrome',
        'bstack:options': {
          userName: '',
          accessKey: '',
          consoleLogs: 'verbose',
          networkLogs: true,
          debug: true,
          seleniumVersion: '4.10.0',
          seleniumCdp: true,
          osVersion: '15.0',
          deviceName: 'iPhone 14',
        //   osVersion: '12.0',
        //   deviceName: 'Samsung Galaxy S22',
          buildName: 'Appium build',
          sessionName: sessionName,
          interactiveDebugging: true,
          appiumVersion: '2.4.1',
          local: undefined
        },
        'goog:chromeOptions': {}
      }
    }
  })
});

const responseBody = await response.json();
console.log(responseBody);
const sessionId = responseBody.value.sessionId;
console.log(`sessionId: ${sessionId}`);
const sessionIdUrl = `${APPIUM_URL}/${sessionId}`;
// visit the url
console.log('Visiting url');
const response2 = await axios({
  url: `${sessionIdUrl}/url`,
  method: 'POST',
  data: { url: 'http://google.com' }
});


console.log(response2.data);

// open new tab
console.log('Opening new tab');
const response3 = await axios(`${sessionIdUrl}/window/new`, {
  method: 'POST',
  data: {
    type: 'tab'
  }
});

console.log(response3.data);

// delete session
console.log('Deleting session');
const response4 = await fetch(sessionIdUrl, {
  method: 'DELETE'
});
```

**Comment by mykola-mokhnach** [comment]
AFAIK Safari remote debugger protocol does not provide any APIs that would allow to open new windows or tabs. Please let us know if you find any which we could use to be able to implement such feature.

**Comment by KazuCocoa** [comment]
Yes, remote debugger doesn’t support the endpoint as no method to achieve that well

**Comment by garg3133** [comment]
Can't we proxy this request directly to safaridriver for browser or web-view automation as we do in UiAutomator2? Because safaridriver does support this endpoint on iOS and if we use safaridriver directly to automate the Safari browser on iOS, the `/window/new` endpoint opens a new tab as expected. But if we use Appium in between, this endpoint gives "method has not yet been implemented" error.

**Comment by mykola-mokhnach** [comment]
using safaridriver forcefully switches the browser to work in the automation mode, which prevents it from being smoothly used in xcuitest driver. You may try to use https://github.com/appium/appium-safari-driver instead, which proxies requests directly to Apple's safaridriver.

**Comment by KazuCocoa** [comment]
Yes, safaridriver can. It is unavailable for the combination with WDA so it may help for mobile safari automation only. It should not have system permissions.
