### ISSUE TITLE
🐞 bug: Plattform Website does not allow to Sign Up for new Accounts - Email to approve the Email-Address is not sent

### ISSUE THREAD

**Issue by MAUIoxo** [appium/appium#20850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Appium Version

2.12.1

### Appium Host Type

Other

### Is this issue reproducible using the latest components?

- [X] I confirm the issue is still reproducible with the latest component versions

### Current Behavior

I am posting this as a Bug not for Appium itself, but the Website.
I wanted to sign up on https://discuss.appium.io, but no approval Email is sent to approve my Email-Address

Looked also in my Spam-Folder, but no Email sent at all. I tried it with a different Email-Address I own, but same there. I checked the spelling of both precisely.

Process ends at this point

![grafik](https://github.com/user-attachments/assets/0710ce6f-17ff-4053-98f8-60bb6a5697d9)

The Email-Address is of the form:
surname.lastname@googlemail.com

Question, does anybody have to approve and send out die Email manually or as expected should it be sent out automatically which is not working anymore?

Right now, I also don't know how I can try again with my Email and/or Username as the system says they are both taken (this is correact as I created the account already with them)

### Expected Behavior

An Email is sent to the Email of the Account that should be singed up

### Environment Details

- Debug details (`appium --show-debug-info`):
- Last component version(s) which did _not_ exhibit the problem:
- Platform and version of device under test:
- Real device or emulator/simulator:

### Minimal Reproducible Example

![grafik](https://github.com/user-attachments/assets/68f7642f-2826-446b-8d89-a8579b8de80f)

**Comment by mykola-mokhnach** [comment]
This is a known limitation, we do not have any SMTP server to use in the forum. Currently the only possible auth method is to use a third-party auth, for example GitHub.
