### ISSUE TITLE
element(s) method retrieving hidden elements, bug or feature?

### ISSUE THREAD

**Issue by sebv** [appium/appium#2163]
Seems like ios >7.0 returns hidden elements, should we filter them?

**Comment by amedvedjev** [comment]
for me the worse problem is that visible elements that are outside screen. really boring to control that.
Example: 
   Gallery: driver.findElements(MobileBy.Id("some_elem_of_galery_single_item")) = ALL elements. Now i need to control element position during tap any of element to make sure that it is on screen.

**Comment by naveenjammula** [comment]
when it is going to fix.In my opinion element(s) method should not retrieve hidden elements. It retrieves only visible elements.

**Comment by ToddGlover** [comment]
Was there an implemented option for this? I really need to disable to ability to find invisible items. My test cases are finding a menu item that is hidden, passing my method check to determine if the menu is open, and then attempting to click another menu item which gives me an unknown server error. This issue is random though and some test cases are passing but this is a sporadic issue for me.

**Comment by amedvedjev** [comment]
is it pure problem of iOS. with android only elements in screen borders are visible (no matter visible or not) but with iOS all elements are visible even outside screen.

you can see this behavior is valid using native test tools also.

thus right now it is pure problem in test code to check is element on screen or not with iOS,

**Comment by bootstraponline** [comment]
> Was there an implemented option for this?

Yes, [in the Ruby bindings](https://github.com/appium/ruby_lib/blob/252e83806318df7df28e9060d3f8e1e56dc732ba/lib/appium_lib/ios/helper.rb#L520) via the `_elementOrElementsByType` server method. You can call the same method in the other bindings via execute script.

**Comment by ToddGlover** [comment]
Awesome. I'll give that a try. Thanks.

**Comment by bhumireddy100** [comment]
Hi,
Appium 1.6.3 with xcuitest
Any one Please provide the code for making ios native element visible true.

**Comment by jlipps** [comment]
this is now a moot point with xcuitest. i believe we're returning whatever it is is visible to xctest.
