### ISSUE TITLE
deprecate superfluous gesture methods in favor of official API

### ISSUE THREAD

**Issue by jlipps** [appium/appium#2234]
All of these methods should be handled by use of the TouchAction and MultiAction APIs instead of being their own "mobile: xxx" methods:

- [ ] `tap`
- [ ] `drag`
- [ ] `flick`
- [ ] `swipe`
- [ ] `scroll` (should be subsumed into regular JSONWP scroll)
- [ ] `longClick`
- [ ] `up`
- [ ] `down`
- [ ] `move`
- [ ] `pinchClose`
- [ ] `pinchOpen`
- [ ] `scrollTo`

Before removing, we should ensure that there is a client-side command which works to perform these methods with appropriate parameters, so we have something to recommend instead of these methods.

**Comment by SrinivasanTarget** [comment]
@imurchie I think this has been done in server on 1.5 re arch or before that. Also all these methods are handled by TouchActions and MultiAction API's in java-client already. Can we close this or is there anything left behind on this?

**Comment by jlipps** [comment]
you're right @SrinivasanTarget
