### ISSUE TITLE
jacoco code coverage

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#2448]
Google has integrated jacoco code coverage support into the Gradle build system for Android. This should enable appium to easily capture code coverage.

http://tools.android.com/tech-docs/new-build-system

**Comment by 404-** [comment]
any progress on this?

**Comment by bootstraponline** [comment]
I'm hoping to set this up with one of the droiddriver examples at some point this year. I know some teams have already figured it out, I haven't seen any examples though.

**Comment by bootstraponline** [comment]
Enabling code coverage can be done in a single line of code with the new Android Studio + gradle:

`buildTypes { debug { testCoverageEnabled true } }`

There's [an example in the droiddriver samples repo]((https://github.com/appium/droiddriver_examples/blob/eedcb261ddcabab5111cdc7c0f420428a0918f82/espresso_sample/espresso/BasicSample/app/build.gradle#L40)). The code I added to the appium server for emma should work the same with jacoco. I think the tasks for this issue are verifying the code works and then updating the doc.

- [ ] verify existing code coverage method works with appium
- [ ] update documentation

**Comment by bootstraponline** [comment]
Google broke jacoco so we'd need a custom [instrumentation runner](https://code.google.com/p/android/issues/detail?id=170607) using the code provided in that issue. I've set one up for my Espresso tests at work.

**Comment by nikhil969** [comment]
Do we have any proper documentation for the usage of Jacoco with TestNG. Pleas can you point it or provide some steps over here.

**Comment by nikhil969** [comment]
Any progress on this..

**Comment by bootstraponline** [comment]
I don't think anyone is actively working on it.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by Thirumalaivigneshm** [comment]
Hi,

I am trying to generate code coverage for my android application. 

1. The developers code uses grade and it's a studio project. 
2. There are no code coverage tools implemented from the developers end.


Let me know the possibilities so I can give a try . 


Thanks, 
Thiru

**Comment by Yajan** [comment]
Hi,
Can anything be done to get code coverage without source code.
