### ISSUE TITLE
Access to appium logs through WebDriver Logging API

### ISSUE THREAD

**Issue by vgrigoruk** [appium/appium#2676]
Is it possible to get Appiim log through webdriver logging API?
https://code.google.com/p/selenium/wiki/Logging

I've posted a question in the Appium-discuss group, but didn't get any response yet: https://groups.google.com/forum/#!topic/appium-discuss/No9XETPn1TE

**Comment by TikhomirovSergey** [comment]
#4835

**Comment by jlipps** [comment]
closing as dupe
