### ISSUE TITLE
Can't set headers after they are sent.

### ISSUE THREAD

**Issue by prolificcoder** [appium/appium#2868]
This is happening intermittently and all the times there is a set_context to webview. 
In appium server: 
uncaughtException: Can't set headers after they are sent. date=Mon Jun 16 2014 09:16:15 GMT-0700 (MST), pid=9143, uid=1524986637, gid=386085923, cwd=/Users/smalugu/code/appium, execPath=/usr/local/Cellar/node/0.10.28/bin/node, version=v0.10.28, argv=[node, /Users/smalugu/code/appium], rss=76894208, heapTotal=61307648, heapUsed=30246840, loadavg=[1.9013671875, 1.57373046875, 1.61865234375], uptime=175686, trace=[column=11, file=http.js, function=ServerResponse.OutgoingMessage.setHeader, line=689, method=OutgoingMessage.setHeader,
in client:
   Connection refused - connect(2) (Errno::ECONNREFUSED)

**Comment by ShiranDadon** [comment]
It is now happening to a colleague of mine.
@bootstraponline , I am trying to help fix it. In the git you referenced to it says to remove CB.
What does it mean? I am not familiar with the abbreviation...

**Comment by bootstraponline** [comment]
CB refers to callback.
