### ISSUE TITLE
simctl support

### ISSUE THREAD

**Issue by swizzlr** [appium/appium#2924]
In Xcode 6 DP there is now a command line tool, `xcrun simctl`, that allows creation of custom simulators and control, in particular opening URLs.

I wonder if such a tool might be useful in testing application interoperability, e.g. oauth flow, which is one of our big testing bugbears. So you could open a URL from the app, verify that the app had gone to background, then call openURL on the simulator from simctl.

I should also say that I get the feeling from simctl that it's architected to support devices, too, though I haven't tried and it doesn't pretend to.

As I'm not a member of the appium dev team I encourage any of them with iOS investment to try `xcrun simctl` and see what they can come up with. Sorry if the issue is vague – I wanted to give you a heads up!

**Comment by NecoleYu** [comment]
+1

**Comment by SrinivasanTarget** [comment]
@jlipps @imurchie @scottdixon We support this feature in existing arch.Can we close this please?
