### ISSUE TITLE
Android L - UiAutomation enhancements

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#2977]
The stats methods might be nice. I'm not sure if the other enhancements make sense for appium.

> - You can use the new android.app.UiAutomation.getWindowAnimationFrameStats() and android.app.UiAutomation.getWindowContentFrameStats() methods to capture frame statistics for window animations and content. This lets you write instrumentation tests to evaluate if the app under test is rendering frames at a sufficient refresh frequency to provide a smooth user experience.
- You can execute shell commands from your instrumentation test with the new android.app.UiAutomation.executeShellCommand(). The command execution is similar to running adb shell from a host connected to the device. This allows you to use shell based tools such as dumpsys, am, content, and pm.
Accessibility services and test tools that use the accessibility APIs (such as uiautomator) can now retrieve detailed information about the properties of windows on the screen that sighted users can interact with. To retrieve a list of android.view.accessibility.AccessibilityWindowInfo objects representing the windows information, call the new android.accessibilityservice.AccessibilityService.getWindows() method.
- You can use the new android.view.accessibility.AccessibilityNodeInfo.AccessibilityAction to define standard or customized actions to perform on an AccessibilityNodeInfo. The new AccessibilityAction class replaces the actions-related APIs previously found in AccessibilityNodeInfo."
>
> http://developer.android.com/preview/api-overview.html

**Comment by jlipps** [comment]
do we have any more idea about what we could add with this?

**Comment by bootstraponline** [comment]
We should upgrade to [uiautomator v2](http://developer.android.com/reference/android/support/test/uiautomator/package-summary.html). I'd expect it to be a drop in replacement (after the package names are updated).

**Comment by jlipps** [comment]
interesting, uiautomator v2 looks like it comes with some cool new stuff

**Comment by SrinivasanTarget** [comment]
@bootstraponline @jlipps I'm closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close
