### ISSUE TITLE
 Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#2996]
- [logs](https://gist.github.com/bootstraponline/057faa7aacf792bb3ad6)
- https://github.com/appium/ruby_lib/issues/220

**Comment by SrinivasanTarget** [comment]
@scottdixon Please close this as its not reproducible on Appium 1.5

**Comment by scottdixon** [comment]
@bootstraponline have you experienced the issue in recent releases?

**Comment by SrinivasanTarget** [comment]
@triager please close
