### ISSUE TITLE
iOS touch move and other actions fix needed 

### ISSUE THREAD

**Issue by varzan** [appium/appium#3021]
Hi.

I'm on Appium 1.1 trying to use TouchActions with screen coordinates, not elements.
On iOS move_to accepts relative coordinates (i.e. move_to(x=100, y=100) will move 100 pixels right and 100 down from the current position; correspondingly negative coordinates will move left/up), on Android it uses absolute coordinates (move_to(x=100, y=100) means you go to position (100, 100) on screen).

Tested with an iOS simulator, an iPhone 5 and a Nexus 5 on Appium 1.1.0.

**Comment by SrinivasanTarget** [comment]
@triager please close
