### ISSUE TITLE
Add instance numbers to Android XML

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3026]
I added [instance number support](https://github.com/appium/ruby_lib/commit/9c4672ba9e5912d7a7aee0b80c78144295c0d5a0) in the Ruby bindings via a SAX parser. This seems like something that should be handled in the server though.

**Comment by Jonahss** [comment]
We do this now, don't we?

**Comment by bootstraponline** [comment]
> We do this now, don't we?

yep
