### ISSUE TITLE
Rename TouchLongClick to longPress

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3111]
`long_press` is the name used for the `TouchAction` API. On Android this is translated into a touchLongClick call. The Java name should match the JavaScript name so it's less confusing.

https://github.com/appium/ruby_lib/issues/231

**Comment by bootstraponline** [comment]
I'm assuming we don't want to do this anymore since it's from 2014 and renaming routes will cause all kinds of issues.

**Comment by jlipps** [comment]
correct 👍
