### ISSUE TITLE
View or Webview?

### ISSUE THREAD

**Issue by AprilZhao** [appium/appium#3112]
I use this example:https://github.com/appium/appium/blob/master/sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidWebViewTest.java

when I use a virtual device to view the webview, it's webview as follows
![moni](https://cloud.githubusercontent.com/assets/8121578/3535267/71f36ef0-07fd-11e4-87fb-da3f316eeafe.jpg)
when I use a real device(NEXUS7), it turns out to be a view, and I'm not able to get the input by 
WebElement input = driver.findElementByClassName("android.widget.EditText")
![zhenji](https://cloud.githubusercontent.com/assets/8121578/3535288/bb3dd712-07fd-11e4-95b1-83df15f07616.jpg)
SDK VERSION: 4.4.2

**Comment by nolanlawson** [comment]
Any update on this? Still wondering if I can use Appium to test a WebView.

**Comment by Jonahss** [comment]
Are you switching Contexts to the webview context? Like described in the answer on this post:
https://discuss.appium.io/t/what-does-the-autowebview-desired-capability-really-do/69

**Comment by nolanlawson** [comment]
@Jonahss OK, I just re-tested, and this is working as of Appium 1.3.7. I can actually type text into a WebView's `textarea` field!

Here is [a live test](https://github.com/nolanlawson/appium-android-demo/blob/2754bfb6212bc9cd5b514aeffe85999afa7111b8/appium/test/test-webview.js#L5-L34) to demonstrate that everything is hunky-dory. To run it, just do:

```
git clone https://github.com/nolanlawson/appium-android-demo.git --branch appium-3112-success
cd appium-android-demo
./gradlew assembleDebug
cd appium
npm install && npm test
```

Thanks!

**Comment by Jonahss** [comment]
Awesome!
