### ISSUE TITLE
app_strings should return the string for current language

### ISSUE THREAD

**Issue by paymand** [appium/appium#3152]
I changed the iPhone language to French and `driver.app_strings()` is returning English (Default) strings! I know that `driver.app_strings(language="fr")` works, but I think we should detect the current language and default to that if `language` is not specified.
This will make the behavior consistent on iOS and Android (Android does this already).

**Comment by mykola-mokhnach** [comment]
```js
commands.getStrings = async function (language) {
  if (!language) {
    language = await this.adb.getDeviceLanguage();
    log.info(`No language specified, returning strings for: ${language}`);
  }

  if (this.apkStrings[language]) {
    // Return cached strings
    return this.apkStrings[language];
  }

  // TODO: This is mutating the current language, but it's how appium currently works
  this.apkStrings[language] = await androidHelpers.pushStrings(language, this.adb, this.opts);
  await this.bootstrap.sendAction('updateStrings');

  return this.apkStrings[language];
};
```

Closed as fixed

**Comment by mariotaku** [comment]
Hi, this has some special cases so it should be reopened.

If device language is zh-Hans-CN, its language is `zh` and locale is `CN`. While appium tries to load strings with `zh` locale, those strings are actually in `zh-CN` locale, which causes `app_strings()` calls returns incomplete result.
