### ISSUE TITLE
Screenshots on android should be rotated

### ISSUE THREAD

**Issue by sbruno** [appium/appium#3158]
Screenshots on android are always taken in normal portrait orientation. If the device is positioned in other of the 4 possible positions the image will look rotated.

This happens only in android uiautomator mode, it does not happen in selendroid mode or iOS. So for consistency I think it should save the screenshots in the same way.

For some of my tests this causes problems because I need to find something in the screenshot based on elements coordinates and they do not match.

I can rotate the screenshots myself but I couldn't find a way of getting the current rotation (0, 90, 180, 270) I can only get the orientation (landscape or portrait)

I managed to get the rotation from the page source by searching for texts such as hierarchy rotation="1" but this causes me problems because of #3156 

I think that the screenshot should be saved as how the mobile app user is supossed to be viewing the app, as selendroid and iOS does. Otherwise having a reliable method for getting the rotation could help.

**Comment by vvvvaib** [comment]
Hi, I am still facing the same issue with appium 1.4. Did anyone manage to get a workaround?

**Comment by tr4n2uil** [comment]
Facing it in 1.4.13, any capabilities or fixes ?

**Comment by tiagoshibata** [comment]
Is anyone working on this issue? If not, I'd like to fix it myself for Android devices.
