### ISSUE TITLE
Enhancement Request: autoAcceptAlerts

### ISSUE THREAD

**Issue by SquareTheBase** [appium/appium#3159]
Request that autoAcceptAlerts become a dynamic method instead of only a device capability.  I'd like to auto accept during app startup then toggle the capability to off during my tests.

https://groups.google.com/forum/#!topic/appium-discuss/YZS8qKxCQPg

Using python script language, iOS, and appium 1.2.

**Comment by jlipps** [comment]
since it looks like autoAcceptAlerts cannot be implemented on the supported driver (xcuitest) moving forward, i'm going to close this. but if we ever re-implement it, it should indeed be a setting in addition to a cap.
