### ISSUE TITLE
Prelaunch server args too complex.

### ISSUE THREAD

**Issue by sebv** [appium/appium#3164]
Whats happening now is we are duplicating the desired args into server args just for the prelaunch use case.

It'll be much easier to have --desired and --desired-defaults server args taking either inline json or reference to json file and reuse the caps code.

Food for thought for next major version.

**Comment by SrinivasanTarget** [comment]
@jlipps @sebv @imurchie I think we have this in our current 1.5 arch. Can we please close this?
