### ISSUE TITLE
Appium 1.2.0 can't find android hybrid app's webview content

### ISSUE THREAD

**Issue by wensj** [appium/appium#3165]
I use appium1.2.0 and appium_lib 4.0.0 ,my device is android 4.4.2 ,when I try to find webview content,I can't find them.I am sure it's a hybrid app.This is my code:
    contexts = available_contexts
    contexts.each do |context|
        puts context
    end 
I can only find "NATIVE_APP" 
I have also use appium_inspector to find webview content,I can't find them too.Now I can't find webview ,so I can't use css to locate.For example I can't locate all textfields on this screen.please help me.
![2014-07-18 2 30 53](https://cloud.githubusercontent.com/assets/5563918/3623063/b71e0028-0e45-11e4-9e39-e38e5e09ce76.png)

**Comment by Jonahss** [comment]
Closed due to inactivity. Reopen if still an issue.
