### ISSUE TITLE
Broadcast arbitrary intents

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3172]
Appium should allow broadcasting arbitrary intents on Android.

https://groups.google.com/forum/#!topic/appium-discuss/QWkhvs_rEtk

Acceptance Criteria:
* [ ] Implement in appium base driver
* [ ] Document in appium
* [ ] Implement in appium-android-driver
* [ ] Implement in WD
* [ ] Open PR's for other clients

**Comment by rickybscs** [comment]
Hi, is there a plan to enable this functionality?

**Comment by jlipps** [comment]
`adb.broadcast(intent)` already exists in `appium-adb`. just need to wire it into an endpoint in base-driver and android/uiautomator2-drivers.
