### ISSUE TITLE
Downloaded application is not removed when session ends.

### ISSUE THREAD

**Issue by vgrigoruk** [appium/appium#3179]
I'm running iOS tests in a grid of OSX virtual machines and I noticed that VMs are running our of space, because appium doesn't clean the cached version of downloaded iOS app here: 

```
guest2:114621-2287-1boqtyc vagrant$ pwd
/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/114621-2287-1boqtyc
guest2:114621-2287-1boqtyc vagrant$ ls 
MyApp.app   appium-app.zip
```

There is a huge amount of folders with the same appium-app.zip and MyApp.app/ inside `/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/`

My app is hosted through http and url is passed to appium server via DesiredCapabilities. I expect that after session is terminated, this cache should be cleaned.

**Comment by SrinivasanTarget** [comment]
@imurchie Do we have this in latest?

**Comment by imurchie** [comment]
Not that I know of, no.

**Comment by Obvious1992** [comment]
We have the same problem on a machine with limited storage. Is there a workarround for this bug?

**Comment by mykola-mokhnach** [comment]
the temporary .zip archive is now always removed. Android also removes the temporarily downloaded app if `clearSystemFiles` capability is enabled. Not sure if the same works for xcuitest driver though

**Comment by SergheiRidico** [comment]
I have faced the same issue with Appium 1.8.2-beta. It works properly when I use iOS application with `.app` extension.  I case when I use application with `.ipa` extension, Appium creates huge number of folders like this one: `/private/var/folders/38/56t_3hn111z6ddyrl4nbmm640000gp/T/201854-36151-lu6j31.qoelg`. Half of this folders contains unzipped iOS application, which Appium does not delete, even if `clearSystemFiles` is set to `true`. This leads to lack of free memory on my computer after each test run.

**Comment by dkdodson3** [comment]
This is still happening for me too. When I delete the folders, somehow my mac is still holding onto the disk space. Even sudo purge is not clearing it up, I have to reboot and then the mac lets go of the space.

**Comment by mykola-mokhnach** [comment]
clearSystemFiles works for iOS as well. Also, the recent appium version can properly cache the unpacked files to avoid ineffective disk space usage.
