### ISSUE TITLE
Expose model info / screen size and other device details

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3210]
It'd be nice if tests could detect 1) the android model that's being used 2) the screen size

http://developer.android.com/guide/practices/screens_support.html

**Comment by sravanmedarapu** [comment]
@jlipps What should be route for this feature ?

**Comment by jlipps** [comment]
@sravanmedarapu i guess somehow the driver would get those details and then return them in the response to `GET /session/:id`?
