### ISSUE TITLE
Extend support for ADB commands

### ISSUE THREAD

**Issue by willosser** [appium/appium#3218]
In order to support testing our Android app with Appium, we would like the following adb commands supported (if there are no other alternatives already in existence)

getprop, with options
pm, with options
am, with options
install -r
rm 
mkdir
mv
cp
dumpsys, with options
ping, with options
bugreport

**Comment by esoests** [comment]
@jlipps  Can you help confirm which version should the "updated launchApp" (mentioned in your comment below) be included?
 the launchApp in java-client 2.0 method doesn't support parameters, it only launches the one set in capabilities.  Want to use it to open an intent.

    am start -a : We use this to bring up the playstore with a specific app, e.g.
    am start -a android.intent.action.VIEW -d "market://details?id=" + PKG_NAME
    but also to bring up settings, e.g.
    am start -a android.app.action.SET_NEW_PASSWORD
    or to send a text message
    am start -a android.intent.action.SENDTO -d sms:#{recipient} --es sms_body '#{text}' --ez exit_on_sent true
   The updated launchApp should probably support intents as well as app packages

**Comment by derek1106** [comment]
We just released Appium 1.3.5, so what kind of commands Appium supported, like adb, mkdir, cp?

**Comment by jlipps** [comment]
@derek1106 it's in the appium 1.4 milestone

**Comment by nicolasavenza** [comment]
What about support for starting the android monkey? It would be useful to have appium bring the monkey to a certain screen in the app and then unleash the monkey:

<code>adb shell monkey -p your.package.name -v 500</code>
http://developer.android.com/tools/help/monkey.html

**Comment by ronnelpinto** [comment]
Hi is it possible for me to execute 'adb shell logcat' command through Appium? Along with the flexibility to get the logs by using some filters?

**Comment by jlipps** [comment]
@ronnelpinto just use the built-in selenium log retrieval commands. logcat is an option there. we are not building in the ability to execute arbitrary adb commands. if you want to do that, just mix those into your test code by calling out to shell.

**Comment by ronnelpinto** [comment]
@jlipps, what's the status of the appium-adb project?

**Comment by jlipps** [comment]
@ronnelpinto it's being actively developed as part of appium, however the work is happening on the 2.0 branch: https://github.com/appium/appium-adb/tree/2.0

**Comment by email2vimalraj** [comment]
@jlipps : Just a question, how can I execute the command which are supported by appium-adb library through appium?
The reason I'm asking is, I would like to reboot and wait for the device till the reboot completes. As a workaround I tried this:
- execute system command **adb reboot**

But appium v1.5.3 deletes the session as soon as I issue **adb reboot**.

**Comment by jlipps** [comment]
@email2vimalraj you can't execute appium-adb library commands via an appium client. that's not how it's designed to work. if you want a device reboot feature in appium it would need to be added to appium with a bunch of logic around restarting the test session and app and so on.

for your current case, what's wrong with simply ending the appium session, then rebooting, then starting a new one?

**Comment by chetand24** [comment]
I am looking to adb -d/-e option to run the test on specific device or emulator, is it possible?

**Comment by amias-channer** [comment]
I am testing an app that is a controller for complex IOT devices , we need to access the logs on the device via our ruby scripts. I really don't want to use ADB directly because it prevents us using remote Appium servers and a lot of cloud testing solutions.  Our App uses several complex protocols that are not bound the UI (an important principle in app design) so we cannot see their via the UI unless we treat them as a black box, we need to get log messages from the devices to verify progress. Surely its possible to make the adb on the Appium server relay to the log data and make it available on a given port kind of like syslog.

**Comment by jlipps** [comment]
@amias-channer can you make another issue with your feature request please?

**Comment by jlipps** [comment]
i'm going to close this issue as it is tracking way too many things. we have been gradually adding support for the use cases listed here, but if your use case was not addressed yet, please create a new issue requesting support for it specifically.

**Comment by amias-channer** [comment]
here it is - https://github.com/appium/appium/issues/8878

**Comment by monsam** [comment]
"We already have driver.installApp which should work or could be extended to use -r if it doesn't already. "

--This doesn't work still
