### ISSUE TITLE
clarify noReset docs

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3241]
> "The flag also affects whether or not the app is left installed or uninstalled, but it doesn't mention anything about that."
- https://groups.google.com/forum/#!topic/appium-discuss/oN7pvuQ2jR0

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md

**Comment by rkavalap** [comment]
no-reset is currently deprecated and this does is no longer relevant.
