### ISSUE TITLE
appium should have a way to set mock geo location on a real android device

### ISSUE THREAD

**Issue by jlipps** [appium/appium#3259]
I don't think our telnet strategy will work on a real device.

Here's some info from StackOverflow: http://stackoverflow.com/questions/2531317/android-mock-location-on-device

Maybe what we could do is create a tiny android app that we invoke with parameters from the command line that sets the mock location? (Kind of like unlock.apk?)

**Comment by jlipps** [comment]
is there a reason we can't add facility for this in Bootstrap.jar so we can call it directly from the appium server?

**Comment by filmaj** [comment]
This feature would be so neat :>

**Comment by clample** [comment]
I just tried setting mock location on a real device with Appium 1.5.3 and it worked. I think that this issue could be closed

**Comment by neilk** [comment]
We're doing it at Sauce Labs with real devices now, so yes, close this.

**Comment by imurchie** [comment]
Awesome!

**Comment by vikas-thange-twc** [comment]
I think we need to reopen this as appium mocking device location only working till android 5 (Lollipop). I tried Android real device 6 and 7 mocking location in not working. 

I used Appium 1.6.4-beta CLI, Java Client 5.0.0-BETA6
