### ISSUE TITLE
Java 6 EOL

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3279]
[Java 6](http://www.oracle.com/technetwork/java/eol-135779.html) is end of life. Java 7 will be end of life next year. Java 8 has been available since March 2014.

Is the plan to remain on Java 6 forever?

**Comment by SrinivasanTarget** [comment]
@bootstraponline @jlipps @imurchie Have few queries on this. Are we using the above stated repo's in current architecture? I see compiler pulgin is still in 1.6 here:https://github.com/appium/appium_apk_tools/blob/master/pom.xml#L28.

I'm able to execute my scripts without any issues on jdk 8 for a long time now. Please clarify is it the same still in current architecture?

**Comment by bootstraponline** [comment]
It's been two years and [Java 7 is EOL now](https://java.com/en/download/faq/java_7.xml). We should update to Java 8. This will break people on older JDKs though.

Java 6 is forwards compatible which is why the existing jars work on JDK 8.

**Comment by bootstraponline** [comment]
Also Android officially requires `Java Development Kit (JDK) 8` on Windows/Linux so appium has fallen behind.

- http://developer.android.com/sdk/index.html

**Comment by SrinivasanTarget** [comment]
Thanks for clarification @bootstraponline Appium is behind two versions now :(

**Comment by SrinivasanTarget** [comment]
@jlipps Can we prioritise this?

**Comment by jlipps** [comment]
yeah I think we should. @bootstraponline will this potentially be a breaking change for appium users? shouldn't right? just potentially for appium developers? or would someone using appium with 1.6 on their system have it stop working if we compile for 1.8?

if so we'll need to batch this with other breaking changes and make it part of appium 2.0

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey ping

**Comment by bootstraponline** [comment]
> @bootstraponline will this potentially be a breaking change for appium users?

yes, we'll be moving forward two major versions of Java. users on old JDKs will break.

**Comment by jlipps** [comment]
ok. let's make sure to get this done in appium 2.0.0 then

**Comment by bootstraponline** [comment]
sounds good

**Comment by SrinivasanTarget** [comment]
@jlipps @bootstraponline Selenium has moved to Java 8 as their minimum version now: https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG

**Comment by jlipps** [comment]
marking this as high priority, but because of the breaking change will need to wait till appium 2.0. with appium 2.0 we won't have to worry about such changes anymore because the breaking aspect will be in the individual drivers, not appium itself.

**Comment by mykola-mokhnach** [comment]
For now all occurrences of custom jars usage in appium-adb are only used as fallbacks if the standard Android tools from SDK package fail to do their job or not installed on the user system.
