### ISSUE TITLE
Feature request: Allow fresh app install but leave app installed at the end

### ISSUE THREAD

**Issue by sthompson0** [appium/appium#3286]
Right now the reset functionality allows the app to be installed and then uninstalled at the end of the test (or not with fullReset/noReset).  I have cases where I'd like to install the app at the beginning but leave it installed for further tests/sessions/debugging/etc.

preReset: True, postReset: False ?

Also, what if I wanted to conditionally change the state of the reset when exiting at run-time?

**Comment by Jonahss** [comment]
If I'm not mistaken, the takeway from the thread above is that we should add a configuration setting that allows for installing apps, but not uninstalling them post-test.

**Comment by mykola-mokhnach** [comment]
Im assume it's not the case anymore
