### ISSUE TITLE
Better docs and bootstrap for Sample Code

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#3313]
For somebody who wants to get started with a bunch of sample code and apps, it should be reasonably easy to get everything they need right away.

For example: There's a README file for the Android sample code, but it doesn't mention the dependency on `ant`

**Comment by SrinivasanTarget** [comment]
@jlipps Is this what you are mentioning here: https://github.com/appium/sample-code.Shall we close this?

**Comment by jlipps** [comment]
this is an issue that should probably be in that repo, so i'm fine to close this one.
