### ISSUE TITLE
get coverage report in gradle builld app?

### ISSUE THREAD

**Issue by sunhao111999** [appium/appium#3314]
@bootstraponline 
I saw the doc get coverage in ant build. how to get coverage in a gradle build app?

**Comment by bootstraponline** [comment]
It's only a [few lines of code](https://github.com/appium/droiddriver_examples/blob/eedcb261ddcabab5111cdc7c0f420428a0918f82/espresso_sample/espresso/BasicSample/app/build.gradle#L40) to get jacoco reports from a gradle project. The technique described in the ant doc should still work.

**Comment by bootstraponline** [comment]
closing since this is a dupe of #2448
