### ISSUE TITLE
Replace fruitstrap with ios-deploy in the docs

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3323]
phonegap maintains a version of fruitstrap that works. we should [recommend this](https://github.com/appium/appium/blob/master/docs/en/appium-setup/ios-deploy.md) instead of the 2012 fruitstrap.

https://github.com/phonegap/ios-deploy

**Comment by xliuxu06** [comment]
How can I manually replace fruitstrap with ios-deploy?

**Comment by Jonahss** [comment]
I think @sebv can answer this better than I can?

**Comment by srikanthsadhu** [comment]
please shed some light to this , how do we deploy to real devices?

**Comment by paymand** [comment]
We don't use ``fruitstrap`` anymore and are using ``ideviceinstaller`` everywhere. See https://github.com/appium/appium/pull/4790.
Please make sure that you have the latest version of ``ideviceinstaller`` installed.

**Comment by paymand** [comment]
@bootstraponline: I'm going to close this issue. Re-open if you disagree.

**Comment by srikanthsadhu** [comment]
so do I have to change version of appium to a specific ?

**Comment by paymand** [comment]
The fix is on master and it's not released (yet). So either run from master or wait for the next release.
