### ISSUE TITLE
add unlockDevice method

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3342]
appium supports locking the device within a session, however there's no method to unlock.

**Comment by adamf663** [comment]
The unlocker is seriously broken for android 5.x.  It borks the phone and makes accessing the launcher impossible, requiring a reboot.

PLEASE PROVIDE A WAY TO DISABLE THE UNLOCKER!!

**Comment by jlipps** [comment]
@adamf663 what you're asking is different than what this issue describes. please raise a new issue with your request.

**Comment by jlipps** [comment]
`commands.unlock` now exists in appium-android-driver.

**Comment by TonyHe1989** [comment]
Does ios driver have the unlock method?

**Comment by jlipps** [comment]
@TonyHe1989 no, it does not
