### ISSUE TITLE
Request to add isAppStatusEnabled() method.

### ISSUE THREAD

**Issue by saimadhu** [appium/appium#3352]
We need this capability while testing MDM (Mobile Device Management) application. We are exploring appium for our application testing on various devices. 
Please consider this request.
## Usecase:

As part our MDM (Mobile Device Management) application testing, there will be policies like disable/ enable apps like camera, any games applications, etc.
Once the policy is applied we need to verify the status of the apps whether it is in disabled/ enabled, etc as per the applied policies.

Thanks
Saimadhu

**Comment by mykola-mokhnach** [comment]
It is possible now to execute any adb shell commands: https://github.com/appium/appium/blob/fd0a0dc234998cd2b3c79a8e66b2da6e77506273/docs/en/writing-running-appium/android/android-shell.md
