### ISSUE TITLE
When running reset.sh --dev Android ApiDemo build fails

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium#3384]
Here is a description of the issue I encountered when running reset.sh with the "--dev" switch, along with the likely solution. We should ensure Eclipse is closed when the reset script starts and then we should run "ant clean release" on the ApiDemo project.

http://stackoverflow.com/questions/20549397/ant-build-fails-inside-eclipse

**Comment by Jonahss** [comment]
@0x1mason what's the actionable item in this issue? We want to close Eclipse? Or issue some warning?

**Comment by 0x1mason** [comment]
You can close this.
