### ISSUE TITLE
Automate HTML5 video actions in iOS mobile Safari

### ISSUE THREAD

**Issue by openMinix** [appium/appium#3406]
I read in the HTML5 iOS Sfarari reference that starting iOS 7 all player interactions will be disabled
until there is user interaction.

I tried using RemoteTouchScreen wrapper around RemoteWebDriver from Selenium with the SingleTap
method, but there was no result.

My question is if there is any way to simulate the initial user action using Appium ( or anything else).

**Comment by dannyfinks** [comment]
@openMinix did you ever get this to work on a real device?

**Comment by mzbedat** [comment]
Have a similar issue with clicking on HTML5 player (in www.dailymotion.com site).
Is there a WA for this?

Robotframework code:
`Play DailyMotion 

	## Step 1 - Open browser with site url
	${url}=	Set Variable	http://www.dailymotion.com
	Go To URL	${url}
	
	## Step 2 - Select a random element from playable elements
	${locator}=	Set Variable	class=preview_link
	Wait Until Page Contains Element	${locator}
	
	${index}	${element}=	Get Random Element	${locator}
	${index}=	Evaluate	${index}/5+1
	
	# Option 1
	#Click Element	xpath=.//*[@id='content']/div[1]/div[1]/div/div[${index}]/div[2]/a/img
	# Option 2
	Trigger Attr    ${element}    click		#Implemented method in python
	
	Wait Until Page Contains Element	class=dmp_StartView-logo	10
	${href}=	Get Element Attribute	class=dmp_StartView-logo	href
	Log To Console	href: ${href}
	
	## Step 3 - Play content	
	#document.getElementsByClassName("dmp_PlaybackButton-icon-play")[0].click();
	#MobileUtil.Execute JavaScript	document.getElementsByClassName("dmp_PlaybackButton-icon-play")[0].click();
	
	:FOR	${i}	IN RANGE	1	4	
		\	# Option 1 - Not working
		\	#Press Keycode	KEYCODE_SPACE
		\	# Option 2 - Not working
		\	#Click A Point	500	500
		\	# Option 3
		\	#Click Element	class=dmp_PlaybackButton-icon-play
		
		\	Builtin.Sleep	30
		\	Go To URL	${href}	`
