### ISSUE TITLE
Windows shell issue.

### ISSUE THREAD

**Issue by swapnil-kotwal-sp** [appium/appium#3408]
I'm tring Sample code given here https://github.com/appium/sample-code/blob/master/sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/AndroidContactsTest.java

I also able to see my connected devices by running command in cmd

**adb devices**
*List of devices attached
075xxxxxxxxxxxxx        device*

But, When I ran my Junit test I got **Could not find a connected Android device.**

Here is full stack trace.

```
> info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Users\\abc\\appium-master\\sample-code\\apps\\ContactManager\\ContactManager.apk","appPackage":"com.example.android.contactmanager","appActivity":".ContactManager","platformVersion":"4.4","browserName":"","platformName":"Android","deviceName":"Android Emulator"}}
> debug: Appium request initiated at /wd/hub/session
> debug: Request received with params: {"desiredCapabilities":{"app":"C:\\Users\\abc\\appium-master\\sample-code\\apps\\ContactManager\\ContactManager.apk","appPackage":"com.example.android.contactmanager","appActivity":".ContactManager","platformVersion":"4.4","browserName":"","platformName":"Android","deviceName":"Android Emulator"}}
> debug: Using local app from desired caps: C:\Users\abc\appium-master\sample-code\apps\ContactManager\ContactManager.apk
> debug: Creating new appium session 9ba7c619-7352-4024-8f1c-2a8deb199a67
> info: Starting android appium
> debug: Using fast reset? true
> info: Retrieving device
> debug: Preparing device for session
> debug: Checking whether app is actually present
> debug: Checking whether adb is present
> debug: Using adb from C:\Users\abc\android-sdks\platform-tools\adb.exe
> debug: Trying to find a connected android device
> debug: Getting connected devices...
> debug: executing: "C:\Users\abc\android-sdks\platform-tools\adb.exe" devices
> warn:  killed=false, code=1, signal=null
> debug: Could not find devices, restarting adb server...
> debug: executing: "C:\Users\abc\android-sdks\platform-tools\adb.exe" kill-server
> warn:  killed=false, code=1, signal=null
> debug: Getting connected devices...
> debug: executing: "C:\Users\abc\android-sdks\platform-tools\adb.exe" devices
> warn:  killed=false, code=1, signal=null
> debug: Could not find devices, restarting adb server...
> debug: executing: "C:\Users\abc\android-sdks\platform-tools\adb.exe" kill-server
> warn:  killed=false, code=1, signal=null
> error: Error killing ADB server, going to see if it's online anyway
> debug: Getting connected devices...
> debug: executing: "C:\Users\abc\android-sdks\platform-tools\adb.exe" devices
> warn:  killed=false, code=1, signal=null
> debug: Could not find devices, restarting adb server...
> debug: executing: "C:\Users\abc\android-sdks\platform-tools\adb.exe" kill-server
> warn:  killed=false, code=1, signal=null
> error: Error killing ADB server, going to see if it's online anyway
> debug: Getting connected devices...
> debug: executing: "C:\Users\abc\android-sdks\platform-tools\adb.exe" devices
> warn:  killed=false, code=1, signal=null
> debug: Could not find devices, restarting adb server...
> debug: executing: "C:\Users\abc\android-sdks\platform-tools\adb.exe" kill-server
> error: Error killing ADB server, going to see if it's online anyway
> debug: Getting connected devices...
> debug: executing: "C:\Users\abc\android-sdks\platform-tools\adb.exe" devices
> warn:  killed=false, code=1, signal=null
> debug: Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> debug: Cleaning up android objects
> debug: Cleaning up appium session
> info: <-- POST /wd/hub/session 500 28211.925 ms - 206 
> error: Failed to start an Appium session, err was: Error: Could not find a connected Android device.
> debug: Error: Could not find a connected Android device.
>     at ADB.getDevicesWithRetry (C:\Users\abc\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:600:15)
>     at androidCommon.prepareActiveDevice (C:\Users\abc\Appium\node_modules\appium\lib\devices\android\android-common.js:349:12)
>     at null.<anonymous> (C:\Users\abc\Appium\node_modules\appium\lib\devices\android\android-common.js:289:26)
>     at C:\Users\abc\Appium\node_modules\appium\node_modules\async\lib\async.js:610:21
>     at C:\Users\abc\Appium\node_modules\appium\node_modules\async\lib\async.js:249:17
>     at iterate (C:\Users\abc\Appium\node_modules\appium\node_modules\async\lib\async.js:149:13)
>     at C:\Users\abc\Appium\node_modules\appium\node_modules\async\lib\async.js:160:25
>     at C:\Users\abc\Appium\node_modules\appium\node_modules\async\lib\async.js:251:21
>     at C:\Users\abc\Appium\node_modules\appium\node_modules\async\lib\async.js:615:34
>     at androidCommon.prepareEmulator (C:\Users\abc\Appium\node_modules\appium\lib\devices\android\android-common.js:339:5)
> debug: Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find a connected Android device.)","origValue":"Could not find a connected Android device."},"sessionId":null}

```

**Comment by 0x1mason** [comment]
No repro.  Assuming workaround listed here will work if others encounter the issue.

**Comment by a373648449** [comment]
I encountered the same problem, I resolved
The solution
Check the path configuration

check in path:

%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\

**Comment by hks225** [comment]
Hello, Guys! I faced with same issue on AppiumForWindows_1_4_16_1 version.
Error from appium:
>     at [object Object].<anonymous> (C:\Appium\node_modules\appium\lib\devices\android\android-common.js:1057:17)
>     at ChildProcess.exithandler (child_process.js:758:5)
>     at ChildProcess.emit (events.js:110:17)
>     at maybeClose (child_process.js:1016:16)
>     at Socket.<anonymous> (child_process.js:1184:11)
>     at Socket.emit (events.js:107:17)
>     at Pipe.close (net.js:484:11)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: 'java -version' failed. Error: Command failed: C:\\Windows\\system32\\cmd.exe /s /c \"java -version\"\n\"java\" пїЅпїЅ пў«пїЅпїЅпїЅпїЅпїЅ пїЅпїЅпїЅпїЅаҐ­пїЅпїЅпїЅ пїЅпїЅпїЅ пїЅпїЅпїЅи­ҐпїЅ\r\nпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ, пїЅбЇ®пїЅпїЅпҐ¬пїЅпїЅ пїЅа®Ја ¬пїЅпїЅпїЅ пїЅпїЅпїЅ пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ д ©пїЅпїЅпїЅ.\r\n)","origValue":"'java -version' failed. Error: Command failed: C:\\Windows\\system32\\cmd.exe /s /c \"java -version\"\n\"java\" пїЅпїЅ пў«пїЅпїЅпїЅпїЅпїЅ пїЅпїЅпїЅпїЅаҐ­пїЅпїЅпїЅ пїЅпїЅпїЅ пїЅпїЅпїЅи­ҐпїЅ\r\nпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ, пїЅбЇ®пїЅпїЅпҐ¬пїЅпїЅ пїЅа®Ја ¬пїЅпїЅпїЅ пїЅпїЅпїЅ пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ д ©пїЅпїЅпїЅ.\r\n"},"sessionId":null}

My path variable:
PATH=C:\Program Files (x86)\PC Connectivity Solution\;C:\Program Files (x86)\Int
el\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windo
ws;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Progr
am Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\
Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R)
Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Managemen
t Engine Components\IPT;C:\Program Files\TortoiseSVN\bin;C:\Program Files\OpenVP
N\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\Wirel
essCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Fil
es (x86)\Skype\Phone\;C:\android-sdk\tools;C:\android-sdk\platforms;C:\android-s
dk\platform-tools;C:\Program Files\Java\jdk1.7.0_45;C:\Windows\system32;C:\Windo
ws;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;%SYSTEM3
2%;C:\WINDOWS\system32;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common
Files\Intel\WirelessCommon\;C:\Windows\system32;C:\Windows;C:\Windows\System32\W
bem;C:\Windows\System32\WindowsPowerShell\v1.0\;%SYSTEM32%;C:\WINDOWS\system32

java -version command works from cmd in any folder

**Comment by dungrani** [comment]
Is there anything to do with user account appium is running under?  Does
Java -version command returns Correct version?

On Apr 5, 2016 8:19 PM, "hks225" <notifications@github.com> wrote:
>
> Hello, Guys! I faced with same issue on AppiumForWindows_1_4_16_1 version.
> Error from appium:
>>
>> at [object Object].<anonymous>
(C:\Appium\node_modules\appium\lib\devices\android\android-common.js:1057:17)
>> at ChildProcess.exithandler (child_process.js:758:5)
>> at ChildProcess.emit (events.js:110:17)
>> at maybeClose (child_process.js:1016:16)
>> at Socket.<anonymous> (child_process.js:1184:11)
>> at Socket.emit (events.js:107:17)
>> at Pipe.close (net.js:484:11)
>>
>> info: [debug] Responding to client with error:
{"status":33,"value":{"message":"A new session could not be created.
(Original error: 'java -version' failed. Error: Command failed:
C:\Windows\system32\cmd.exe /s /c \"java -version\"\n\"java\" пїЅпїЅ
пў«пїЅпїЅпїЅпїЅпїЅ пїЅпїЅпїЅпїЅаҐ­пїЅпїЅпїЅ пїЅпїЅпїЅ
пїЅпїЅпїЅи­ҐпїЅ\r\nпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ, пїЅбЇ®пїЅпїЅпҐ¬пїЅпїЅ
пїЅа®Ја ¬пїЅпїЅпїЅ пїЅпїЅпїЅ пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ
д ©пїЅпїЅпїЅ.\r\n)","origValue":"'java -version' failed. Error: Command
failed: C:\Windows\system32\cmd.exe /s /c \"java -version\"\n\"java\"
пїЅпїЅ пў«пїЅпїЅпїЅпїЅпїЅ пїЅпїЅпїЅпїЅаҐ­пїЅпїЅпїЅ пїЅпїЅпїЅ
пїЅпїЅпїЅи­ҐпїЅ\r\nпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ, пїЅбЇ®пїЅпїЅпҐ¬пїЅпїЅ
пїЅа®Ја ¬пїЅпїЅпїЅ пїЅпїЅпїЅ пїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ
д ©пїЅпїЅпїЅ.\r\n"},"sessionId":null}
>
> My path variable:
> PATH=C:\Program Files (x86)\PC Connectivity Solution\;C:\Program Files
(x86)\Int
> el\iCLS Client\;C:\Program Files\Intel\iCLS
Client\;C:\Windows\system32;C:\Windo
>
ws;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Progr
> am Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program
Files\Intel\
> Intel(R) Management Engine Components\IPT;C:\Program Files
(x86)\Intel\Intel(R)
> Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R)
Managemen
> t Engine Components\IPT;C:\Program Files\TortoiseSVN\bin;C:\Program
Files\OpenVP
> N\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common
Files\Intel\Wirel
> essCommon\;C:\Program Files (x86)\NVIDIA
Corporation\PhysX\Common;C:\Program Fil
> es
(x86)\Skype\Phone\;C:\android-sdk\tools;C:\android-sdk\platforms;C:\android-s
> dk\platform-tools;C:\Program
Files\Java\jdk1.7.0_45;C:\Windows\system32;C:\Windo
>
ws;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;%SYSTEM3
> 2%;C:\WINDOWS\system32;C:\Program Files\Intel\WiFi\bin\;C:\Program
Files\Common
>
Files\Intel\WirelessCommon\;C:\Windows\system32;C:\Windows;C:\Windows\System32\W
>
bem;C:\Windows\System32\WindowsPowerShell\v1.0\;%SYSTEM32%;C:\WINDOWS\system32

**Comment by hks225** [comment]
C:\Windows\System32>java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

and by direct path from error it works too

**Comment by hks225** [comment]
fixed by adding %JAVA_HOME%\bin to Path variable
