### ISSUE TITLE
Android driver should trap log requests so it can return logcat logs even when in webview mode

### ISSUE THREAD

**Issue by paymand** [appium/appium#3412]
Using Opera browser on Android, which has an embedded chromium context, `driver.get_log("logcat")` stops working after switching to chromium context using:

``` Python
driver.switch_to.context("CHROMIUM")
```

After the first switch (regardless of whether I switch back to native app context or not) I keep getting the following server error when trying to get the logcat:

```
unknown error: log type 'logcat' not found\n  (Session info: content shell with embedded Chromium )\n
```

Looks like the context switch breaks the logcat capture functionality.

**Comment by gentrified** [comment]
@jlipps I'd like to reopen this. A significant part of the app that my team is running UIA tests on comprise of webview screens. Waiting until we switch back to native view to obtain logcat is not truly a good workaround for us because the logcat buffer may have been overfilled, and we would lose prior logs.

**Comment by jlipps** [comment]
ok, reopening it as a feature request

**Comment by jlipps** [comment]
title updated to more accurately reflect what needs to happen here

**Comment by sjrjanardhana** [comment]
I was also facing this issue, Any plans to implement this feature near future? Though our app is completely Webview but it mostly interacts with Native app. during test runs we were not able to get the adb logs

**Comment by mykola-mokhnach** [comment]
The feature is now available in appium@beta, UIAutomator2 driver. Please verify it and let us know if there are any issues
