### ISSUE TITLE
ios webviews should be cached

### ISSUE THREAD

**Issue by jlipps** [appium/appium#3418]
that way we can switch back and forth without issue. some work already in progress here:
#3339

**Comment by jlipps** [comment]
@imurchie did we take care of this as part of the 1.5 rewrite?

**Comment by jlipps** [comment]
@imurchie ping again?

**Comment by jlipps** [comment]
@imurchie ping again?

**Comment by SrinivasanTarget** [comment]
@imurchie Is this been taken care on our latest arch?

**Comment by jlipps** [comment]
@imurchie still wondering about this one
