### ISSUE TITLE
Device.prototype.configureDownloadedApp should check if app already is downloaded. 

### ISSUE THREAD

**Issue by djonsson** [appium/appium#3439]
### Steps to reproduce:
- Upload your app as a .zip file to a web server 
- Set the capability to the location of the app, java example: `capabilities.setCapability("app", http://yourwebserver/App.zip);`
- Run a test
### Problem:

It seems like the Application is downloaded for each test which takes a lot of time. 
### Solution:

Add a capability `capabilities.setCapability("cacheDownloadedApp", true);` that only re-downloads the app if the filename of the app/zip have changed since the last time it was downloaded, and store the latest downloaded filename on disk. This would allow users to automatically only download new builds, instead of downloading the same build over and over again. The capability would be set to `false` if the capability is left unset.

**Comment by jlipps** [comment]
I think the way we would do this is to store the url -> filename cache on the BaseDriver class object, rather than a particular instance.

**Comment by mykola-mokhnach** [comment]
Now the remote url is considered as cached in the Last-Modified header value returned by the server is less or equal to the previously cached one.
