### ISSUE TITLE
Android prototype function signatures use inconsistent patterns

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium#3456]
See this in lib/devices/android/android.js, but might be elsewhere

`Android.prototype.pushStrings = function (cb, language) { `
vs
`Android.prototype.getStrings = function (language, cb) `

These should follow the same pattern.

**Comment by SrinivasanTarget** [comment]
This is how it is now: https://github.com/appium/appium-android-driver/blob/master/lib/android-helpers.js#L305

**Comment by jlipps** [comment]
yep, rearch took care of this
