### ISSUE TITLE
Write more browser automation (Chrome/Safari) examples

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3477]
In NYC a bunch of people were asking about browser automation. The [sample code](https://github.com/appium/sample-code) has a lot of tests for native apps. It'd be nice if we had more for browser automation.

**Comment by pmneve** [comment]
Got my vote too!

**Comment by Simon-Kaz** [comment]
I've been thinking about writing appium tests for the-internet https://github.com/tourdedave/the-internet

I've done this some time ago with C# and Selenium (see my github), and am planning to redo it with Java, cucumber and Selenium.

I wouldn't mind working on an Appium solution as well (cucumber and junit), as I'll be automating webviews soon.

**Comment by jlipps** [comment]
@Simon-Kaz that'd be great! Would love to accept a PR for the sample-code repo.

**Comment by saikrishna321** [comment]
@jlipps @imurchie this can be closed? we already have webview tests 

https://github.com/appium/sample-code/tree/master/sample-code/examples
