### ISSUE TITLE
On iPad the application is not removed when we use cap.setCapability("noReset", false);

### ISSUE THREAD

**Issue by gabifericean** [appium/appium#3487]
Appium version: 1.2.1
iPad3,  version 7.0.4
io.appium - java-client 1.6.2			

Steps to reproduce:
1. Install the application using next DesiredCapabilities
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability("deviceName", "iPad");
		cap.setCapability("udid", udid);
		cap.setCapability("platformName", platformName);
		cap.setCapability("platformVersion", platformVersion);
		cap.setCapability("app", app.getAbsolutePath());
		cap.setCapability("noReset", false);
2. make some actions against the application
3. 		driver.closeApp();
		driver.quit();

Expected result:
When execute driver.quite() the application should be removed from device. This had worked on the previous version of appium 1.2.0

Actual result:
The application is not removed.

**Comment by Jonahss** [comment]
Closed due to inactivity.
Is this still an issue?
