### ISSUE TITLE
Add tracing when logging in debug mode

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium#3493]
This is a nice feature that would be fairly trivial to implement. When logging in debug mode, we should:

1) append all logs (including info and warn) with the line # and file name at which they're invoked. This would create a visibile stack trace.
2) Add full stack traces for errors. This is especially helpful given the difficulty in tracing asynchronous calls. There are performance penalties for tracing, so for now we can restrict this to debug mode.

There are several tracing modules for node, but this one looks esp nice since it handles async really nicely: https://www.npmjs.org/package/asynctrace

Implementing this feature would be simple and could follow the same pattern as our logger debug stderr-to-stdout hack in lib/server/logger.js:

```js
  if (levels[loglevel] === levels.debug) {
    var func = logger.info;
    logger.info = function (msg) { func(msg + getTrace()); };
  }
```

If we implement this feature, however, we should consider forking winston so we can change the the app internals directly rather than hacking.

**Comment by moizjv** [comment]
@jlipps can you at this one? I am not very sure of context here ?

**Comment by jlipps** [comment]
this is fixed.
