### ISSUE TITLE
appium 1.2.2: In iOS, SafariLauncher folder NOT getting installed

### ISSUE THREAD

**Issue by saimadhu** [appium/appium#3499]
I am trying to launch safari browser with appium 1.2.2, but getting ENOENT error. 
I am blocked currently. Please help.

APPIUM 1.2.2 installation steps:
--------------------------------------------
1. git clone https://github.com/appium/appium.git
2. cd appium
3. ./reset.sh //tried with --dev option also
4. started iOS webkit
5. started appium

reset.sh logs:
------------------
./reset.sh --ios --real-safari --code-sign '<code signing idendity>' --profile '<retrieved profile identity code>'

---- Resetting / Initializing Appium ----
RESETTING NPM
* Installing new or updated NPM modules (including devDeps)
npm WARN package.json assert@1.1.1 assert is also the name of a node core module.
npm WARN package.json md5calculator@0.0.3 No repository field.
npm WARN package.json node-idevice@0.1.2 No repository field.
npm WARN package.json path@0.4.9 path is also the name of a node core module.
npm WARN package.json vargs@0.1.0 No repository field.
npm WARN package.json utf7@1.0.0 No repository field.
RESETTING GENERAL
* Setting git revision data
Running "setGitRev" task
Config file exists, updating it
{"git-sha":"81d2e9cb74dccfa49a57a9539a0c22999235c9c9","ios":{"version":"1.2.2"},"built":"2014-08-26T14:13:18.479Z"}
Done, without errors.
RESETTING IOS
* Setting iOS config to Appium's version
Running "setConfigVer:ios" (setConfigVer) task
Config file exists, updating it
{"git-sha":"81d2e9cb74dccfa49a57a9539a0c22999235c9c9","ios":{"version":"1.2.2"},"built":"2014-08-26T14:13:18.479Z"}
Done, without errors.
* Installing ios-sim-locale
* Cloning/updating udidetect
* Building udidetect
~/madhu/appium/submodules/udidetect ~/madhu/appium
gcc -o udidetect -framework CoreFoundation -framework MobileDevice -F/System/Library/PrivateFrameworks udidetect.c
~/madhu/appium
* Moving udidetect into build/udidetect
* Cloning/updating fruitstrap
* Making fruitstrap
~/madhu/appium/submodules/fruitstrap ~/madhu/appium
make: `fruitstrap' is up to date.
~/madhu/appium
* Copying fruitstrap to build
* Cloning/updating libimobiledevice-macosx
* Copying libimobiledevice-macosx to build
* Cloning/updating deviceconsole
* Building deviceconsole
~/madhu/appium/submodules/deviceconsole ~/madhu/appium
Making deviceconsole...
~/madhu/appium
* Copying deviceconsole to build
CLEANING UP
* Cleaning any temp files
* Setting build time and SHA info
Running "setBuildTime" task
Config file exists, updating it
{"git-sha":"81d2e9cb74dccfa49a57a9539a0c22999235c9c9","ios":{"version":"1.2.2"},"built":"2014-08-27T05:07:32.178Z"}
Done, without errors.
---- reset.sh completed successfully ----
admins-mbp-2:appium admin$ pwd
/Users/admin/madhu/appium
admins-mbp-2:appium admin$ ls
AUTHORS			Gruntfile.js		RELEASE.pdf		build			grunt-helpers.js	package.json		sample-code
CHANGELOG.txt		LICENSE			assets			ci			lib			reset.bat		submodules
CONTRIBUTING.md		README.md		bin			docs			node_modules		reset.sh		test

No SafariLaucher folder even after running reset:
---------------------------------------------------------------
admins-mbp-2:appium admin$ cd build/
deviceconsole/           fruitstrap/              ios-sim-locale           libimobiledevice-macosx/ udidetect/               
admins-mbp-2:appium admin$ 

APPIUM Server logs:
--------------------------
$ node lib/server/main.js -U b8ab55cd1d036a1a6d2d6951a06fb6e6ce83c49e --native-instruments-lib
info: Welcome to Appium v1.2.2 (REV 81d2e9cb74dccfa49a57a9539a0c22999235c9c9)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"udid":"b8ab55cd1d036a1a6d2d6951a06fb6e6ce83c49e","nativeInstrumentsLib":true}
info: LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"safari","platformName":"iOS","deviceName":"iPad","browserName":"safari","udid":"b8ab55cd1d036a1a6d2d6951a06fb6e6ce83c49e","version":"6.1.3"}}
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : version
info: [debug] Configuring Safari session
info: [debug] Using local .zip from desired caps: /Users/admin/madhu/appium/build/SafariLauncher/SafariLauncher.zip
info: [debug] Copying local zip to tmp dir
info: [debug] Got configuration error, not starting session
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: ENOENT, stat '/Users/admin/madhu/appium/build/SafariLauncher/SafariLauncher.zip'
info: [debug] Error: ENOENT, stat '/Users/admin/madhu/appium/build/SafariLauncher/SafariLauncher.zip'
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: ENOENT, stat '/Users/admin/madhu/appium/build/SafariLauncher/SafariLauncher.zip')","errno":34,"code":"ENOENT","path":"/Users/admin/madhu/appium/build/SafariLauncher/SafariLauncher.zip","origValue":"ENOENT, stat '/Users/admin/madhu/appium/build/SafariLauncher/SafariLauncher.zip'"},"sessionId":null}
info: <-- POST /wd/hub/session 500 7.230 ms - 384 a

**Comment by Jonahss** [comment]
Is anyone still getting this error?
