### ISSUE TITLE
Unable to view the elements of the UIATableCell

### ISSUE THREAD

**Issue by Vibhorgaur8** [appium/appium#3532]
Appium Version : 1.2.1
Java-client : 1.6.2
Application : iOS Native app
Running over Simulator : iPhone Retina (4-inch 64-bit), Version : 7.1

I have a table view in my app. Each UIATableCell is collapsable/ Expandable. When expanded it shows  following :- 
1. UIAStaticText
2. UIAPageIndicator (There are 5 swipe able views for each UIAStaticText horizontally)
3. UIAButton
![screen shot 2014-08-30 at 11 56 16 pm](https://cloud.githubusercontent.com/assets/7780015/4099824/4011f656-3073-11e4-98dc-f90baad8dbc0.png)

The problem is that in the UIAStaticText there are a number of tappable buttons present in the highlighted area of cell (see screenshot) 
![screen shot 2014-08-30 at 11 56 38 pm](https://cloud.githubusercontent.com/assets/7780015/4099825/47765a86-3073-11e4-8725-d38bf4f58530.png)

But Appium Inspector shows none of these button locators. Please suggest a solution for same

**Comment by Jonahss** [comment]
Closed due to inactivity.

**Comment by d9kgit** [comment]
I have the same problem with large UIATableViews. 
When I export to XML -> find by Xpath in some web-xpath-testers - it can find it. 

Appium 1.3.6
