### ISSUE TITLE
Unity Integration for Android

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3534]
At Unite 2014, Unity presented their open source Unity Test Tools (UTT) for unit tests, assertions, and integration testing. Unity currently doesn't have the ability to do UI testing.

![unite_2014](https://cloud.githubusercontent.com/assets/1173057/4102088/abaffe2c-3117-11e4-9c36-f311fec4d692.png)

A [virtual view hierarchy](http://developer.android.com/guide/topics/ui/accessibility/apps.html) for Unity's soon to be open sourced UI framework would enable appium automation of Unity on Android. Any project using the official UI would be able to test with appium.

Unity also announced a [Continuous Integration service in the cloud](https://www.youtube.com/watch?v=-EjAjl26itM) which makes builds and runs tests. This seems like a natural partnership opportunity once Unity is accessibility enabled and can be tested with appium.
- [Unite 2014 presentation](https://www.youtube.com/watch?v=ii2hIcyGHuI)
- [Open source details](http://blogs.unity3d.com/2014/08/20/more-open-source-initiatives-from-unity/)
- [Example virtual view hierarchy](https://github.com/appium/android-apidemos/blob/master/src/io/appium/android/apis/accessibility/AccessibilityNodeProviderActivity.java).

**Comment by bootstraponline** [comment]
Unity published a [blog post](http://blogs.unity3d.com/2015/06/26/leveraging-unity-cloud-build-for-testing-large-projects/) on how they're testing large projects.

**Comment by bootstraponline** [comment]
Unity published [numbers on API level adoption](http://unity3d.com/profiles/unity3d/themes/unity/images/company/pr/ByTheNumbersUnityTechnologies.pdf).

**Comment by bootstraponline** [comment]
Riot has a [great post on game automation](https://engineering.riotgames.com/news/automated-testing-league-legends) that was [discussed on ycombinator](https://news.ycombinator.com/item?id=11601278). In their architecture, I'm not sure WebDriver is a great abstraction even though the overall concept is similar.

**Comment by abhilashcae** [comment]
This is awesome. Appreciate @bootstraponline @jlipps and Appium team for taking this up. Do we still have this in pipeline? It would be great if we can have this soon.

**Comment by juhlila** [comment]
👍

**Comment by jjlehtinen** [comment]
As far as I'm aware the app under test would need to have some sort of component installed to it to be able to fetch any UI related information out of it. Does anyone have any idea about a possible implementation for this other than that, I would be curious to discuss it.

**Comment by mykola-mokhnach** [comment]
https://www.youtube.com/watch?v=KwmanWMTh10&t=0s&list=PLhr2WKNPXcZOmOf1k2aqkbMZwnZb2pSZL&index=8

**Comment by jjlehtinen** [comment]
Nice indeed, looks like it's pretty much identical to the approach we have taken in our project, just more polished. One thing to consider as part of this is to enable sending keys without an element on Appium, as with Unity you won't be able to grab any native Elements as references.

**Comment by pusoktimea** [comment]
From [version 1.4.0 ](https://altom.com/altunitytester-v-1-4-0-now-with-keyboard-input/), AltUnity Tester can simulate keyboard buttons, mouse and joysticks so you can use it to test games on Windows, Linux and Mac (and game consoles).
It's open source and it can be downloaded from asset store: https://assetstore.unity.com/packages/tools/utilities/altunity-tester-ui-test-automation-112101

**Comment by mykola-mokhnach** [comment]
I assume https://github.com/headspinio/appium-altunity-plugin does the job
