### ISSUE TITLE
ios xpath search should be done in appium-uiauto

### ISSUE THREAD

**Issue by jlipps** [appium/appium#3560]
now that we are using a js-only xpath library, we should port it to be able to run in uiauto code and see if that improves the reliability of xpath searches (not having to send a huge data stream over the wire for every find)

**Comment by SrinivasanTarget** [comment]
@jlipps Was it done in latest architecture?

**Comment by bootstraponline** [comment]
I think it's done for android in the new uiautomator v2, don't think iOS has changed at all.

**Comment by jlipps** [comment]
@SrinivasanTarget it was not done but this is lower priority than getting XCUITest support going

**Comment by jlipps** [comment]
closing as obsolete now that we are not supporting the old ios driver.
