### ISSUE TITLE
predicate docs out of date

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3567]
- dot is required now, it's not automagically added
- full UIA can be used, not limited to the default window

**Comment by jlipps** [comment]
the acceptance criteria for this one are now that the predicate docs should be effective for xcuitest driver. cc @dpgraham

**Comment by mykola-mokhnach** [comment]
WDA maintainer @marekcirkos added a comment that he does not like current predicate search implementation, since it discloses internal classes implementation. It would be good to have some kind of string transformation there, so we can standardise all public property names.

**Comment by jlipps** [comment]
predicate docs for XCUITest were already added. if WDA changes how they work we can update them. closing for now.
