### ISSUE TITLE
Reverting/Uninstalling appium

### ISSUE THREAD

**Issue by RamonBoza** [appium/appium#3573]
Hi guys, 

I was working happy with appium 1.0.0 when moving to appium 1.2.0 in order to check what would be the impact if we upgrade the system.

The impact would be: (sent .ipa instead of .app, use some other parameters app-package instead of appPackage, or both), etc etc.

Then I installed back Appium 1.0.0 and got crazy, sorry for that expression, because now I cannot send again .app, I need to send .ipa and configure all the properties that I didn't need to configure before moving to appium 1.2.0, so, something is wrong when downgrading the version of appium, some configuration or external application are not correctly updated in the process.

Can you provide me with a wiki or a guide on how to downgrade correctly the appium version?

Thanks!!!

**Comment by Jonahss** [comment]
Closed due to inactivity

**Comment by vbutzke** [comment]
@RamonBoza I know this is a closed forum, but it may help out who is having the same issue. For the downgrade to work, you have to use -g option:
npm install -g appium@<version>

**Comment by Amar-Incture** [comment]
Hi,
I tried the above step but finally I got the following error and it continued to throw this. Can anyone please help?

Error trying to install Chromedriver binary. Waiting and trying again. Cannot find module 'babel-runtime/helpers/sliced-to-array'

**Comment by imurchie** [comment]
@Amar-Incture What version of Appium are you trying to install? What command are you running?

**Comment by Amar-Incture** [comment]
Currently I am using 1.6.2 and I want to downgrade to the previous version just before this.

**Comment by mthompsonpop** [comment]
I'm having the same problem with appium 1.10 the new version that caused XCIUTest to fail because it wants 1.6 or greater.  Now I can't get rid of 1.10 even with npm uninstall -g appium

**Comment by djangofan** [comment]
Strangely,  i have Appium installed on my Mac , via npm , with version 1.7.1 .    When i download the APpium desktop app version 1.7.1,   when i start up my Appium desktop app, it says its 1.9.1  .   Why?  Is it caching a previous install I had?  I don't remember ever installing 1.9.1.
