### ISSUE TITLE
Get/Set Network Connection is not working in Selendroid mode

### ISSUE THREAD

**Issue by Hassan-Radi** [appium/appium#3581]
I am using Appium 1.2.1 in Selendroid mode. Selendroid fails to get/set the network connection settings that I pass and hence fails my tests:

On my device, this is the current status of the network settings:
>Wifi: ON
Data: ON
Air Plane: OFF

I am executing:
> NetworkConnectionSetting networkConnection =_driver.getNetworkConnection();
networkConnection.setWifi(false);
networkConnection.setData(false);
_driver.setNetworkConnection(networkConnection);

It should disable Wifi and Data connections, but it doesn't do the expected function. I tried to debug and found that the current network status before I execute the code lines was:
>Wifi: OFF
Data: OFF
Air Plane: ON

which is the exact opposite of the device correct status.

**Here are my device details:**
Samsung Galaxy tab 2 (10.1) running OS 4.0.4

**OS details:**
Windows 7 x64

**Capabilities:**
capabilities.setCapability("app", "app path");
capabilities.setCapability("udid", "device udid");
capabilities.setCapability("appPackage", "package name");
capabilities.setCapability("appActivity", "activity name");
capabilities.setCapability("newCommandTimeout", 6000);
capabilities.setCapability("automationName", "Selendroid");
capabilities.setCapability("platformName", "Android");
capabilities.setCapability("platformVersion", "4.0.4");
capabilities.setCapability("deviceName", "Android");
capabilities.setCapability("androidDeviceReadyTimeout", 5);
 

**Appium log:**
https://gist.github.com/Hassan-Radi/6fa8d14db032656044d3

**Comment by eliasnogueira** [comment]
There is an update about this issue. It still occurs in Appium java_client 2.1.0

**Comment by SrinivasanTarget** [comment]
There is a rewrite of this on both client and server side.Please do raise a new bug incase if you face any issues along with logs.Closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close
