### ISSUE TITLE
Allow setting network delay

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3640]
Testing on different network conditions is important. The emulator has a netdelay setting. Appium should allow using this feature.
- http://android-developers.blogspot.com/2014/09/android-one-bringing-apps-to-next-five-billion.html
- http://developer.android.com/tools/devices/emulator.html#netdelay

**Comment by jlipps** [comment]
looks like appium can only set network delay if it manages the emulator. but yes we can add this option.

**Comment by jlipps** [comment]
sounds like @vrunoa knows how to fix this one

**Comment by mykola-mokhnach** [comment]
The necessary methods have been merged to Appium 1.6.6-beta. See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md
