### ISSUE TITLE
Replace static sleep with timed-out polling

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium#3654]
We use `sleep` in our tests, but I've also seen `$.delay` in our production code.  The latter should be dealt with first since it impacts our users.

I like this pattern, but it's just a suggestion.  Whatever we can do to reduce blocking times is good with me:
```js
tryWaitForCondition (timeout, testCondition) {
  var increment = 50; // ms
  var totalTime = 0;

  while(totalTime < timeout && !testCondition()) {
    totalTime += increment;
    sleep(increment);
  }

  return testCondition();
}

// wait for cb to return true or 3 seconds has elapsed
if(!tryWaitForCondition(3000, checkAConditionAndReturnABool)) {
  throw new Error('Noooooooooooooooooooooo...');
}
```

**Comment by jlipps** [comment]
our test code has in most places been updated with elastic waits, and it is our requirement moving forward!
