### ISSUE TITLE
Clarify hideKeyboard documentation

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium#3661]
We need to update the docs to clarify that hideKeyboard is a convenience method for common ways of closing the keyboard.  The keyboard closes whenever resignFirstResponder is called on the control to which the kb is attached--it has nothing to do with the kb itself.  It's up to the application developer to decide when a control loses focus. Because of this variability in behavior, there's no way for Appium to guarantee its strategies will close the keyboard.  All we can do is provide a convenience feature representing common approaches.  If hideKeyboard fails to hide the keyboard, there's a good chance it's due to the app's behavior rather than Appium's. However, the test developer should still be able to close the keyboard by having Appium emulate the gesture or tap the app is expecting.

**Comment by jlipps** [comment]
this has been clarified in the 1.5 docs
