### ISSUE TITLE
Not able to handle popupmenu in android app

### ISSUE THREAD

**Issue by sjrjanardhana** [appium/appium#3666]
Hi, our application has popupmenu when when i tap on a button it popupmenu list, i am not able to get the details from either UIautomator nor appium inspector. do we have a way to select a popupmenu item in androi apps?

**Comment by iSravyaS** [comment]
Has this issue been solved @sjrjanardhana, as I face the same issue even after all this time? It would be a great help if you can let me know how you solved this.

**Comment by sjrjanardhana** [comment]
It was long back worked on, sorry to say that I didn't even remember how
the issue was resolved. Only thing i remember is that some of the UI
components we have disabled.

**Comment by iSravyaS** [comment]
Thank you for trying to help. @sjrjanardhana
