### ISSUE TITLE
Appium should set implicit wait for proxied sessions automatically

### ISSUE THREAD

**Issue by Hassan-Radi** [appium/appium#3682]
I am using Appium 1.2.2 in Selendroid mode and setting implicit wait for locating elements. Everything is working fine until I switch context to WEBVIEW (Implicit wait stops working and everything fails) .... 

The workaround is to set it manually every time I switch context. I was thinking that it should be done internally by Appium inside the context method

**Comment by SrinivasanTarget** [comment]
I think @imurchie has fixed this recently
