### ISSUE TITLE
Android: openNotifications does not work while client in foreground

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#3714]
when app is running in foreground "openNotifications"

when send app into background and do "openNotifications" - notifications opening correctly and visible.

tested with two real devices: Nexus7, LG G2.

NOT working code:
        sleep(3);
        driver.openNotifications();

working code:
        driver.sendKeyEvent(AndroidKeyCode.HOME);
        sleep(3);
        driver.openNotifications();

**Comment by imurchie** [comment]
In both web and hybrid context you will need to get out into the native app and run the command.

**Comment by imurchie** [comment]
Is the underlying issue still in effect?

**Comment by priyankshah217** [comment]
Let me verify, and get back to you.

**Comment by imurchie** [comment]
Any movement?

**Comment by moizjv** [comment]
Closing issue. @priyankshah217  please test and reopen if this is still an issue.
