### ISSUE TITLE
[Appium 1.2.3][iOS Safari][Real Device] Appium doesn't always navigate to most recently opened web view

### ISSUE THREAD

**Issue by aniket-21** [appium/appium#3723]
After every suite we are quitting and restarting  the appium driver. This invokes safari launcher, and it in turns invoke a new Web View in Safari.

But sometime , we cannot see steps having in the browser even though server log is showing success responses cos I guess these actions are happening in a back ground web view and hence not seen in front most web view.

We can see processing icon of browser which confirms that actions are happening but in some other web view

**Comment by imurchie** [comment]
Does this still happen?

**Comment by aniket-21** [comment]
Didnt check for a long time now. You can close this issue for now
