### ISSUE TITLE
Get context handles in two simultaneous sessions

### ISSUE THREAD

**Issue by Hassan-Radi** [appium/appium#3732]
I am running two Appium sessions simultaneously each one in a separate server instance with unique server IP address and port number. Both sessions are in Selendroid mode. I am using a hybrid app and switching back and forth between contexts in both sessions.

I noticed that whenever a device is in WEBVIEW context and the other is in NATIVE_APP context, the one in WEBVIEW context stops responding and can't find the WEBVIEW context anymore until the other device switches to the WEBVIEW context also.

I am using Appium server 1.2.3 on Windows 7. Devices are: Samsung Galaxy S4 & Samsung Tab2 (10.1)

**Comment by jlipps** [comment]
It should be totally possible to run Selendroid sessions on older devices through Appium, and we do our best to log everything (especially if you choose to show logcat in the appium log). But if you're fine running Selendroid on its own, then so far so good.

If you do run into this problem again, I welcome a set of logs, and we can reopen this issue to continue to diagnose. Thanks!
