### ISSUE TITLE
Selendroid 0.12.0 is release, need to incroporate this to appium

### ISSUE THREAD

**Issue by priyankshah217** [appium/appium#3742]
Hi,

Selendroid 0.12.0 is release, hence new changes should be incorporatred with  new releases of appium.

https://oss.sonatype.org/content/repositories/snapshots/io/selendroid/selendroid-standalone/0.12.0-SNAPSHOT/

Kindly consider this as tool enhancement.

Thanks,
Priyank Shah

**Comment by jlipps** [comment]
we've now upgraded to 0.17.0
