### ISSUE TITLE
extend closeApp for Android to allow stopping of arbitrary apps, not just AUT

### ISSUE THREAD

**Issue by RamonBoza** [appium/appium#3743]
What title says:
"Is there a way to close all the running applications in the phone?"

I have been investigation through the documentation but found nothing, is it a way?

because we are executing test of different application on the same device and sometimes it crashes because, for some reason, the other one is still open.

Thank you!

**Comment by mykola-mokhnach** [comment]
Added terminateApp endpoint for this purpose
