### ISSUE TITLE
delete cookies by passing (name, path, domain)

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#3832]
Following discussion in #3740 

Safari requires one to specify the domain of cookies one wants to delete, but the JsonWire protocol doesn't have a field for that.

There exists a workaround.

We could propose an amendment to the JsonWire protocol or create a special appium endpoint.

**Comment by jlipps** [comment]
haven't heard much about this in 1.5+ years, so closing as won't do unless it becomes a priority for someone.
