### ISSUE TITLE
Unable to switch from hybrid app to com.mobile.safari with Appium & Protractor

### ISSUE THREAD

**Issue by ericraio** [appium/appium#3843]
I have an ionic/angularjs/cordova application that uses the cordova facebook plugin. I have appium with cucumber and protractor setup and I can test everything on the app within the simulator. In the app itself I have facebook authentication setup and I am trying to test this on an iOS simulator.

If you look at this step below

    And I input my facebook credentials

The app will redirect to facebook mobile web, waits for the browser to load and then will infinitely refresh itself. 

When I console.log the browser url after the cordova app redirects to facebook on safari, the url is the app's local file path and now the browser url of facebook.

config.js

    exports.config = {
    
      capabilities: {
        browserName: 'iOS',
        app: '/Users/username/Projects/app-directory/platforms/ios/build/emulator/appname.app',
        deviceName: 'iPhone Simulator',
        'appium-version': '1.3.0-beta1',
        version: '8.0',
        platformName: 'iOS',
        platformVersion: '8.0',
        autoWebview: true,
        autoWebviewTimeout: 10
      },
     
      allScriptsTimeout: 30000,
    
      seleniumAddress: 'http://localhost:4723/wd/hub',
    
      baseUrl: 'http://localhost:8100',
     
      onPrepare: function() {
        var wd = require('wd'),
        _ = require('underscore'),
        wdBridge = require('wd-bridge')(protractor, wd);
        wdBridge.initFromProtractor(exports.config);
      },
    
      framework: 'cucumber',
    
      cucumberOpts: {
        require: '../features/**/*.js',
        format: 'pretty'
      },

      specs: [ '../features/*.feature' ]
    };

root.feature

    Feature: Root Screen
      As a user who is not logged in
      I want to be greeted with a menu screen
      So that I know where to sign up or login

      Scenario: Successfully logging into the app through facebook
        Given I am a user on facebook
        When I click on the facebook button
        And I input my facebook credentials
        And I accept the facebook permissions
        Then I should be at the home screen

root steps

    var rootSteps = function() {

      this.Given(/^I am a user on facebook$/, function (done) {
        this.app.createFbUser().then(done); // helper that returns a promise and creates a fb test user object and sets it to this.app.fbUser;
      });

      this.When(/^I click on the facebook button$/, function (done) {
        browser.driver.findElement(by.css('[ng-click="fbLogin()"]')).click().then(done);
      });

      this.When(/^I input my facebook credentials$/, function (done) {
        browser.sleep( 8000 );  // wait for facebook to completely load

        wdBrowser.contexts().then(function(ctxs) {
          var webCtx = _(ctxs).find(function(ctx) { return ctx.match(/WEBVIEW/)});
          wdBrowser.context(webCtx) ;
        }).then(function() {
          browser.ignoreSynchronization = true
          var emailElem = browser.driver.findElement(by.name('email'));
          var passwordElem = browser.driver.findElement(by.name('password'));
          var submitElem = browser.driver.findElement(by.name('login'));

          emailElem.sendKeys(this.app.fbUser.email);
          passwordElem.sendKeys(this.app.fbUser.password);
          submitElem.click().then(done);
        });
      });

      this.When(/^I accept the facebook permissions$/, function (done) {
        done.pending();
      });

      this.Then(/^I should be at the home screen$/, function (done) {
        done.pending();
      })
    };

    module.exports = rootSteps;

Here is the error logs from Appium.

    info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP","WEBVIEW_1"],"sessionId":"a93509a3-3cce-4f03-be58-c59474b40e92"}
    info: <-- GET /wd/hub/session/a93509a3-3cce-4f03-be58-c59474b40e92/contexts 200 2.140 ms - 98 {"status":0,"value":["NATIVE_APP","WEBVIEW_1"],"sessionId":"a93509a3-3cce-4f03-be58-c59474b40e92"}
    info: [debug] [REMOTE] Receiving data from remote debugger
    info: [debug] [REMOTE] got applicationSentData response
    info: [debug] [REMOTE] Got a blank data response from debugger
    info: [debug] [REMOTE] Receiving data from remote debugger
    info: [debug] [REMOTE] Receiving data from remote debugger
    info: [debug] [REMOTE] {"__argument" {"WIRApplicationIdentifierKey":"PID:34459","WIRIsApplicationProxyKey":false,"WIRApplicationNameKey":"Safari","WIRApplicationBundleIdentifierKey":"com.apple.mobilesafari","WIRIsApplicationActiveKey":1},"__selector":"_rpc_applicationConnected:"}
    info: [REMOTE] We were notified that we connected to possibly the wrong application. Ignoring for now and hoping we're going to retry looking for apps

**Comment by Jonahss** [comment]
It looks like we designed appium to only connect to webviews on the app under test, whereas in this case we are switching to a webview in a different app (MobileSafari). If that will work, we might as well support switching to the detected webview.

**Comment by jlipps** [comment]
@ericraio can you try with the latest Appium 1.5 beta? Our webview handling code has been completely reworked

**Comment by ericraio** [comment]
@jlipps sorry man, i abandoned the project that was using appium, I hope it works out! maybe someone else can check it out.

**Comment by jlipps** [comment]
no worries, we've gotten way backed up on our issues, sorry we weren't able to get to this when it was relevant to you. closing for now unless someone else wants us to look into this case.
