### ISSUE TITLE
/session should return 200 not 303

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#3860]
selenium changed the /session endpoint to return a 200 not 303. We should follow suite.

Can't find the source this second, but santi says jason leyba is the one who made the commit, so we can look for it there.

**Comment by ellenmobify** [comment]
Any updates on this?

**Comment by Jonahss** [comment]
@ellenmobify hasn't been done. Is this preventing you from using appium in some way?

**Comment by Jonahss** [comment]
And if so, which client are you using?

**Comment by ellenmobify** [comment]
We're using Nightwatch.js. The problem I'm seeing is not entirely related to this issue -  Nightwatch outputs an error when Appium starts because Nightwatch is expecting a JSON response. Nevertheless, it can follow the redirect, and the error has no effect on test outcomes.

**Comment by jlipps** [comment]
in Appium 1.5 we return a 200 not a 303
