### ISSUE TITLE
Appium should disable Android's system animations to reduce flakiness [uiautomator2]

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium#3868]
According to Google's test team:

> System animations can introduce timing errors that make your tests flaky. Google's test runner infrastructure uses an instrumentation to turn off animations before running tests. A similar approach can be adapted to other CI builds. 

https://code.google.com/p/android-test-kit/wiki/DisablingAnimations

We should do this asap and maybe expose a setting to re-enable it.

**Comment by jlipps** [comment]
@bootstraponline this should be possible for uiautomation2 as well, correct?

**Comment by bootstraponline** [comment]
> @bootstraponline this should be possible for uiautomation2 as well, correct?

correct

**Comment by bootstraponline** [comment]
- https://code.google.com/p/android/issues/detail?id=187727

**Comment by SrinivasanTarget** [comment]
@triager please close
