### ISSUE TITLE
Allow pullFile() to get files relative to app, from the Data directory [iOS]

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#3883]
https://github.com/appium/appium/commit/818765c4e53095f7332df69e9e17f854c8e7ad99#commitcomment-8276133

The real solution here is to fix it up so there's no `exec()` going on. Just use node to find the files we want in both the Bundle and Data directories.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium-xcuitest-driver/pull/574
