### ISSUE TITLE
Appium V2 Architecture

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#3911]
[discussion link](https://github.com/appium/appium/pull/3886#issuecomment-60537749)

Goals:
- Avoid Spaghetti code:
  Use monocle-js, or ES7 async/await syntax (both use generators under the hood). 
- Exception Handling:
  promises (with async await syntax)
* Clearer structure, greater use of OO patterns. [E.g., discussion of lib/devices](https://groups.google.com/forum/#!topic/appium-developers/MO1ojX7dGoY).
  * Evaluate move to [TypeScript](http://www.typescriptlang.org/)
*  Evaluate gulp (It uses Javascript feature better.)

Links:
- ES6/ES7 features list in Traceur https://github.com/google/traceur-compiler/wiki/LanguageFeatures
- monocle: https://github.com/jlipps/monocle-js
- async/await/es7 overview: http://www.joezimjs.com/javascript/synchronizing-asynchronous-javascript-es7/
- promise https://www.youtube.com/watch?v=MNxnHbyzhuo (focus is on error handling/composition rather than syntax. Dominic has since joined Google and is working on es7/traceur).
- [AtScript presentation](https://www.youtube.com/watch?v=lGdnh8QSPPk)

**Comment by jlipps** [comment]
\o/ we have finished rewriting appium
