### ISSUE TITLE
[IOS, Hybrid-app, Real device] Interactions fail with an element that extends offscreen

### ISSUE THREAD

**Issue by SirApropos** [appium/appium#3921]
We have a webpage which works in a strange way -- it will sometimes move elements partially offscreen (to the left in our case). Let's say the viewport is 400px and our div is 1200px (three "pages"). When on the first "page", interactions work fine. Our app then moves to the next "page" by positioning the div at -400px (so only the middle 400px is displayed). When attempting to interact with an element inside this div (for example, clicking on a button), the Appium server appears to translate the coordinates into "real" coordinates (which are negative). Because of the offset, it then tries to click on negative coordinates rather than the actual position of the element and silently fails.

Appium version: 1.3.1, but this existed on at least 1.2.x. It was working in earlier versions, but I don't recall the last working version (I think 1.1.x).
Device: iPhone 5 (iOS 7.0.4 and 8.0.2). Have not tried this on a simulator.

This issue does not appear to be present in Android. This is being run through a selenium grid (v2.41.0) and we are using Appium java-client v2.0.0.

**Comment by jlipps** [comment]
@SirApropos what I meant was, can you set the nativeWebTap capability to false?
