### ISSUE TITLE
Check Appium moveTo against JsonWirespecs. 

### ISSUE THREAD

**Issue by sebv** [appium/appium#3934]
This is about the regular moveTo method, not the touch moveTo.

On iOS: Reading the code, I am getting the feeling that the behavior is wrong when el is null.

On Android: it's is unimplemented, when we have a touch version of it, not very logical.

Better do that after we have setup the test net.

**Comment by SrinivasanTarget** [comment]
Android: https://github.com/appium/appium-android-driver/blob/master/lib/commands/touch.js#L19

iOS: https://github.com/appium/appium-ios-driver/blob/master/lib/commands/gesture.js#L367

**Comment by jlipps** [comment]
given that `moveTo` is not a part of the W3C spec moving forward, i don't think we should spend time implementing it correctly.
