### ISSUE TITLE
Do we have any Appium API to get the iOS device date and time?

### ISSUE THREAD

**Issue by sjrjanardhana** [appium/appium#3937]
Do we have any Appium API to get the iOS device date and time?

**Comment by gferreri** [comment]
I'd like to upvote this request. Running tests on Sauce Labs in a different time zone than where the test is executing is leading to some test flakiness. Our app behaves differently based on the current time on the device, and testing this feature requires us to be sure of the device time.

**Comment by su-agrawal** [comment]
I would like to upvote it as well. Some features in our app are time dependent and it would be good if I can get and set the device date time through appium. Thanks!! @bootstraponline

**Comment by jhuska** [comment]
This would be handy for Android as well. Using ``adb`` is a bit cumbersome when emulator/device is running/connected to a different machine than tests are running on.

Should I create different issue for Android?

**Comment by imurchie** [comment]
This is implemented in Appium 1.5 in both iOS (https://github.com/appium/appium-ios-driver/commit/35a2d82803170d2a7edac869cac6c55d8f7d7e09; only for real devices) and Android (https://github.com/appium/appium-android-driver/commit/cab1249ffd244edcc865aed30ee253f43499bbba). We just need to get implementations into the clients (see https://github.com/appium/node-mobile-json-wire-protocol/issues/40).

**Comment by SrinivasanTarget** [comment]
(y)

**Comment by jlipps** [comment]
closing since this is done on the server side

**Comment by BhaskarVj** [comment]
Do we have any function call for getting current date and time that is present on Sauce virtual device?

Any suggestions would help us.

Thanks  & Regards,
Vijay Bhaskar.

**Comment by BhaskarVj** [comment]
FYI, We've done trouble shooting by using adb commands, but no luck. 
"adb shell -s date yyyymmdd".

**Comment by imurchie** [comment]
@BhaskarVj If you have an unrelated question (this ticket is specifically iOS) a new issue ought to be made in preference.
