### ISSUE TITLE
Move to ideviceinstaller.

### ISSUE THREAD

**Issue by sebv** [appium/appium#3942]
Replace fruitstrap by ideviceinstaller everywhere.

**Comment by ijazsarwar** [comment]
install app function does not work (looks like still using fruitstrap) but if you provide the ipa path as part of the launch app it installs the app just fine (if the bundle id does not exist on device).

**Comment by xliuxu06** [comment]
I installed Appium 1.3.6 and also  ideviceinstaller.  My iOS app is installed without a problem. But I still see the fruitstrap error message showing. is there a way to get rid of the message? Thanks!

**Comment by Jonahss** [comment]
@sebv ^^
