### ISSUE TITLE
Appium Inspector improvement/revamp.

### ISSUE THREAD

**Issue by sebv** [appium/appium#3952]
At a point we will need to start to iterate on redesign/improvement.

Those are the shortcoming in the current design (please add to it):
- promote the use of xPath, subpar index based xPath selectors. (default locator, and showing in element details windows)
- lack of spinning feature.

**Comment by jlipps** [comment]
This is really more of an epic, we need a complete rewrite of the inspectors.

**Comment by jlipps** [comment]
duplicate of #7167
