### ISSUE TITLE
Unable to install /tmp/Appium-MobileSafari-8.1.app on iphone 5

### ISSUE THREAD

**Issue by amarnathrayudu** [appium/appium#3965]
Hi Team,

I am facing below issue when I try to run UI tests on iphone 5 (iOS 8.1) + Appium 1.3.1, please help me to resolve the issue.

error: Failed to start an Appium session, err was: Error: Unable to install [/tmp/Appium-MobileSafari-8.1.app] to device with id [31e4476c94819c48abb352ca4763b6bd5c89a905]. Error [Error: Command failed: ]

info: [debug] Cleaning up appium session
info: [debug] Error: Unable to install [/tmp/Appium-MobileSafari-8.1.app] to device with id [31e4476c94819c48abb352ca4763b6bd5c89a905]. Error [Error: Command failed: ]
at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/common.js:147:10
at ChildProcess.exithandler (child_process.js:652:7)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:756:16)
at Socket. (child_process.js:969:11)
at Socket.emit (events.js:95:17)
at Pipe.close (net.js:465:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Unable to install [/tmp/Appium-MobileSafari-8.1.app] to device with id [31e4476c94819c48abb352ca4763b6bd5c89a905]. Error [Error: Command failed: ])","origValue":"Unable to install [/tmp/Appium-MobileSafari-8.1.app] to device with id [31e4476c94819c48abb352ca4763b6bd5c89a905]. Error [Error: Command failed: ]"},"sessionId":null}
info: <-- POST /wd/hub/session 500 4934.171 ms - 414 
info: [IOS_SYSLOG_ROW ] Nov 3 12:15:22 Amarnath-Amisettys-iPhone mobile_installation_proxy[218] : ERROR: MobileInstallationInstallForLaunchServices returned nil

info: [IOS_SYSLOG_ROW ] Nov 3 12:15:22 Amarnath-Amisettys-iPhone mobile_installation_proxy[218] : 0x581000 handle_install: Installation failed: Error Domain=LaunchServicesError Code=0 "The operation couldn’t be completed. (LaunchServicesError error 0.)" UserInfo=0x166701f0 {Error=ApplicationAlreadyInstalled, ErrorDescription=Rejecting downgrade of system/internal app com.apple.mobilesafari: installed version is 600.1.4, proposed version is 600.1.4}

Thanks,
Amarnath Rayudu

**Comment by Jonahss** [comment]
Closed due to inactivity (and being outdated)
