### ISSUE TITLE
iOS WebView scroll up

### ISSUE THREAD

**Issue by wilcollins** [appium/appium#3974]
We are currently able to scroll down in our webview using 

jse.executeScript("arguments[0].scrollIntoView(false);", element);

but it is only able to scroll DOWN to elements, not up. I have used numerous methods to try to work around this issue, but none of them have been successful so far. 

I have tried using IOSDriver.scrollTo but for some reason it is unable to locate the element with the provided text even though I use driver.findElement("//someXpathLocator").getText()

I also tried to use a similar approach I use for some Android tests where I utilize HasTouchScreen .down(), .move(), and .up() methods, but this is not yet implemented.

I even used "mobile: scroll" on a native element but the entire webview was scrolled, not just the list view, leaving the top third of the screen black/empty (without moving the listview) until the next UI interaction occurred. 

I don't think you guys would have shipped without full scrolling functionality within iOS webview, but I can't find a method that works and it is blocking our testing so any help would be greatly appreciated!

**Comment by wilcollins** [comment]
((JavascriptExecutor) (MobileUtil.getDriver())).executeScript("window.scrollTop=1000");
returns null and performs no actions on the webview

**Comment by wilcollins** [comment]
jse.executeScript("arguments[0].scrollIntoView(false);", element);
works but only for down-scrolling

**Comment by wilcollins** [comment]
Advice: Any function that works in one direction should work for both. Being able to scroll directly to an element is a good API endpoint so the user doesn't have to determine the coordinates and then pass that to the function. And if you could encapsulate all of the scrolling functions into a universal "scrollTo" that picks the appropriate method depending on the current state (OS, context, etc), that would be awesome.

**Comment by wilcollins** [comment]
I have also tried TouchActions in the native context with no success:

public static void scrollTo(WebElement we) {
		Point p = we.getLocation();
		while (!we.isDisplayed()) {
			try {
				MobileUtil.switchToNativeView();
				AppiumDriver driver = (AppiumDriver) MobileUtil.getDriver();
				Point appLoc = driver.findElement(By.xpath("//UIAWebView[1]")).getLocation();

				TouchAction action = new TouchAction(driver);
				action.press(1, 1);
				action.moveTo(1, 100);
				action.release();
				((MobileDriver) MobileUtil.getDriver()).performTouchAction(action); << does nothing

				driver.swipe(1, 1, 1, 100, 1); << "An error occurred while executing user supplied JavaScript."
			}
			catch (Exception e) {
				e.printStackTrace();
			}
			finally {
				MobileUtil.switchToWebView();
			}
		}
	}

**Comment by wilcollins** [comment]
Update: "mobile: swipe" works on Appium 1.3.0 in both the Native and WebView contexts (both UP and DOWN scroll work). However, in 1.3.4, this function returns "Not Yet Implemented" in both contexts. So, for now, I have reverted to 1.3.0 -- please fix iOS scrolling so we can use the latest features :-)

**Comment by wilcollins** [comment]
```
/**
	 * This method scrolls the page
	 * 
	 * @param pageToScroll
	 *            - need to specify the page to perform the scroll
	 * @param speed
	 *            - speed to scroll in pixels/second
	 * @return boolean
	 *         return if the scroll was successful
	 * @throws InterruptedException
	 */
	@SuppressWarnings("serial")
	private static boolean scroll(WebElement viewToScroll, int speed, boolean scrollDown) {
		int offSize = 0;
		String logMessage = "";
		logMessage = (scrollDown) ? "Scrolling page down" : "Scrolling page up";

		RemoteWebDriver remoteWebDriver = (RemoteWebDriver) MobileUtil.getDriver();

		offSize = remoteWebDriver.manage().window().getSize().getHeight() / 3;
		int screenSize = remoteWebDriver.manage().window().getSize().getHeight();
		Double initialYPos = 0.0;
		Double finalYPos = 0.0;
		// final Double scrollSpeed = (double) speed / speedControl;
		final Double scrollSpeed = 30.0 / speed;
		final Double xPosition = remoteWebDriver.manage().window().getSize().getWidth() - 15.0;

		if (scrollDown) {
			// Code to scroll down
			initialYPos = (double) screenSize - offSize;
			finalYPos = initialYPos - offSize;
		}
		else {
			// Code to scroll up
			finalYPos = (double) screenSize - offSize;
			initialYPos = finalYPos - offSize;

		}
		final Double initialY = initialYPos;
		final Double finalY = finalYPos;

		System.out.println("Start Y: " + initialY + "; Final Y: " + finalY + "; Scroll duration: " + scrollSpeed);

		remoteWebDriver.executeScript("mobile: swipe", new HashMap<String, Double>() {
			{
				put("touchCount", 1.0);
				put("startX", xPosition);
				put("startY", initialY);
				put("endX", xPosition);
				put("endY", finalY);
				put("duration", scrollSpeed);
			}
		});

		return true;
	}
```

**Comment by jlipps** [comment]
what about `"mobile: scroll"`?

**Comment by wilcollins** [comment]
We have currently reverted to 1.3.0 and are using "mobile: swipe". What are the parameters for "mobile: scroll"? And which versions should that be supported in?

**Comment by jlipps** [comment]
it's supported in all recent versions. something like this in Java, maybe?

```java
        remoteWebDriver.executeScript("mobile: scroll", new HashMap<String, Double>() {
            {
                put("direction", "down");
            }
        });
```

**Comment by wilcollins** [comment]
That hashmap should be String, String but I'll give that a shot when I get
some time and I'll let you know how it goes.

**Comment by wilcollins** [comment]
That HashMap<String, String> but I'll give that a shot when I get some time and I'll let you know how it goes. I had tried it before with no success but hopefully that won't be the case again. 

Also, is it supported for WebViews? I have noticed that certain functionality was limited (at least at some point) within webviews

**Comment by jlipps** [comment]
you can always go back to the native context to use that command, so I would say it doesn't matter whether it works specifically within webviews, no?

**Comment by wilcollins** [comment]
Read my first post in this thread. I mentioned my attempt to use it in
native context

**Comment by jlipps** [comment]
@wilcollins I see. You can also pass in an "element" parameter to mobile: scroll. This has to be the ID of a native element, of course.

**Comment by bhaskar-appium** [comment]
Could you please put some code for scroll to an element(not scrollTo("text")), using in java.

@0x1mason  @jlipps  @Jonahss

**Comment by jlipps** [comment]
the documentation has been updated appropriately, so I'm closing this issue. @bhaskar-appium the correct way to achieve what you want is to use `mobile: scroll` and then check that the element in question is within the bounds of the viewport.

**Comment by VenkiDeveloper** [comment]
Try this code, its worked for me...to swipe up/down without using any element

Map<String, Object> params = new HashMap<String, Object>();
params.put("direction", "up/down");
appiumIOSDriver.executeScript("mobile: scroll", params);
