### ISSUE TITLE
Test fails because of alert dialog, but no dialog is seen/detected

### ISSUE THREAD

**Issue by andry-tino** [appium/appium#3999]
I am having a very strange issue when running tests. Find below all information related to my test environment,

* Tests run on a Windows machine (8.0) and they are coded in C# using the [https://github.com/appium/appium-dotnet-driver](C# adapter).
* Appium server runs on a Windows 8.1
* Appium version is 1.2.4
* Testing on Android real device

The test I execute is very simple:

```c#
[Test]
public void LoginTestCase() {
            Thread.Sleep(1000);
            var addressInput = driver.FindElementById(addressInputId);
            addressInput.Clear();
            addressInput.SendKeys("http://myserver:34987");

            var submitAddressButton = driver.FindElementByClassName(submitAddressButtonCssClass);
            submitAddressButton.Click();
            Thread.Sleep(1000);
            var userNameInput = driver.FindElementById(userNameInputId);
            userNameInput.Clear();
            userNameInput.SendKeys("user125");

            var passwordInput = driver.FindElementById(passwordInputId);
            passwordInput.Clear();
            passwordInput.SendKeys(TempPassword.GetPassword());

            var submitCredentials = driver.FindElementByClassName(submitAddressButtonCssClass);
            submitCredentials.Click();

            var homePageElement = driver.FindElementByClassName(homePageCssClass);
            Expect(homePageElement, Is.Not.Null);

            var homePageElement1 = driver.FindElementByClassName(homePageCssClass);
            Expect(homePageElement1, Is.Not.Null);
}
```

When reaching the last part of the test something strange happens. An error is thrown:

> info: [debug] Responding to client with error: {"status":26,"value":{"message":"A modal dialog was open, blocking this operation","origValue":"unexpected alert open\n  (Session info: webview=)\n  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.3 x86_64)"},"sessionId":"965ba51e54f682559e5b8378095bc3d4"}

My test fails because a javascript dialog is open in my web app. But I actually inspect my app in that scenario and there is no alert dialog the app ever shows and no javascript error that might cause it to be shown.

I tried replacing the last part of the test with the following code:

```c#
try {
    Expect(homePageElement1, Is.Not.Null);
} catch (OpenQA.Selenium.UnhandledAlertException exception) {
    driver.SwitchTo().Alert().Accept();
}
```

So if a dialog is open I will handle it and my test will not fail, however I get this:

> info: [debug] Responding to client with error: {"status":26,"value":{"message":"A modal dialog was open, blocking this operation","origValue":"unexpected alert open\n  (Session info: webview=)\n  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.3 x86_64)"},"sessionId":"965ba51e54f682559e5b8378095bc3d4"}
> info: [37m<-- POST /wd/hub/session/965ba51e54f682559e5b8378095bc3d4/element [39m[31m500[39m[90m 10.392 ms - 269[39m [90m[39m
> info: [37m-->[39m [37mGET[39m [37m/wd/hub/session/965ba51e54f682559e5b8378095bc3d4/alert_text[39m [90m{}[39m
> info: [debug] Proxying command to 127.0.0.1:9515
> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/965ba51e54f682559e5b8378095bc3d4/alert_text","method":"GET"}
> info: [debug] Proxied response received with status 200: "{\"sessionId\":\"965ba51e54f682559e5b8378095bc3d4\",\"status\":0,\"value\":\"\"}"
> info: [37m<-- GET /wd/hub/session/965ba51e54f682559e5b8378095bc3d4/alert_text [39m[32m200[39m[90m 5.261 ms - 70[39m [90m[39m
> info: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/965ba51e54f682559e5b8378095bc3d4/accept_alert[39m [90m{}[39m
> info: [debug] Proxying command to 127.0.0.1:9515
> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/965ba51e54f682559e5b8378095bc3d4/accept_alert","method":"POST","json":{}}
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"unknown error: unhandled inspector error: {\"code\":-32603,\"message\":\"No JavaScript dialog to handle\"}\n  (Session info: webview=)\n  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.3 x86_64)"},"sessionId":"965ba51e54f682559e5b8378095bc3d4"}

So Appium fails because of a dialog, but when reporting a dialog it fails because there is no dialog...
Can you tell me if there is some problem in the code maybe not correctly detecting alerts?

**Comment by 0x1mason** [comment]
Closing as third-party issue.
