### ISSUE TITLE
Appium 1.3.1 + simulator 8.1 :: IOS Simulator crashes after prepunching successfully

### ISSUE THREAD

**Issue by p00j4** [appium/appium#4002]
Ios simulator 8.1 crashes every-time after pre-launching successfully [road blocker :-( ]
Xcode : 6.1, Mac os: 10.9.5

appium log after prelaunch

info: <-- GET /wd/hub/status 200 3.316 ms - 178 {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"97f93807-2a50-48c8-b173-3bcf9f5ccc4f"}

info: [debug] [INST] 2014-10-29 05:43:32 +0000 Fail: The target application appears to have died

info: [debug] [INST] Instruments Trace Complete (Duration : 169.825500s; Output : /tmp/appium-instruments/instrumentscli0.trace)

info: [debug] [INSTSERVER] Instruments exited with code 0

info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly

info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons

info: [debug] Cleaning sim data files

info: [debug] Executing: xcrun simctl erase 28363892-7285-4E10-8E4A-5ED8DEB92D31

info: [debug] Executing: xcrun simctl erase 28363892-7285-4E10-8E4A-5ED8DEB92D31

info: [debug] Executing: xcrun simctl erase 28363892-7285-4E10-8E4A-5ED8DEB92D31

info: [debug] Executing: xcrun simctl erase 28363892-7285-4E10-8E4A-5ED8DEB92D31

info: [debug] Executing: xcrun simctl erase 28363892-7285-4E10-8E4A-5ED8DEB92D31

error: Could not reset simulator. Leaving as is. Error: Command failed: An error was encountered processing the command (code=146):
Unable to erase contents and settings in current state: Booted
 // stderr: An error was encountered processing the command (code=146):
Unable to erase contents and settings in current state: Booted

**Comment by imurchie** [comment]
Are you still seeing this issue?

**Comment by p00j4** [comment]
@imurchie : I haven't used prelaunch in from long time, so I just tested, it works now in 1.3.4. 
Though still instruments behaves maturely  very few of the times.
![image](https://cloud.githubusercontent.com/assets/6470509/6200068/29c1d008-b48d-11e4-835a-02eb3a923601.png)

**Comment by imurchie** [comment]
Yes. But that is being covered elsewhere. Closing.
