### ISSUE TITLE
Command timeout seem to be broken.

### ISSUE THREAD

**Issue by sebv** [appium/appium#4025]
DEVICE=ios81 mocha  -g  'timeout short timeout should die with short command timeout' test/functional/ios/testapp/timeout/short-timeout-specs.js
 
nfo: [debug] We shut down because no new commands came in
info: [debug] Pushing command to appium work queue: "au.getElementByName('dont exist dogg')"
info: [debug] Waited for 1008ms so far
info: [debug] Pushing command to appium work queue: "au.getElementByName('dont exist dogg')"
info: [debug] Waited for 1511ms so far
info: [debug] Pushing command to appium work queue: "au.getElementByName('dont exist dogg')"
info: [debug] Waited for 2013ms so far
info: [debug] Pushing command to appium work queue: "au.getElementByName('dont exist dogg')"
info: [debug] Waited for 2516ms so far
info: [debug] Pushing command to appium work queue: "au.getElementByName('dont exist dogg')"
info: [debug] Waited for 3023ms so far
info: [debug] Pushing command to appium work queue: "au.getElementByName('dont exist dogg')"
info: [debug] Waited for 3527ms so far
info: [debug] Pushing command to appium work queue: "au.getElementByName('dont exist dogg')"
info: [debug] Waited for 4031ms so far
info: [debug] Pushing command to appium work queue: "au.getElementByName('dont exist dogg')"
info: [debug] Waited for 4536ms so far
info: [debug] Pushing command to appium work queue: "au.getElementByName('dont exist dogg')"
info: [debug] Condition unmet after 5039ms. Timing out.
info: [debug] Respondin

 1) testapp - timeout short timeout should die with short command timeout:
     AssertionError: expected promise to be rejected with an error matching /status: (13|6)/ but got '[elementByName("dont exist dogg")] Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters. Selenium error: An element could not be located on the page using the given search parameters.'

**Comment by SrinivasanTarget** [comment]
`command-timeout` is deprecated and `newCommandTimeout` works fine for me.Closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close
