### ISSUE TITLE
issues with non-English UIs on iOS 8

### ISSUE THREAD

**Issue by hectorv** [appium/appium#4029]
Hi,
we've been using language and locale in the desired capabilities to
test how our app behaves on non-English UIs.
On iOS 7 things are fine. On iOS 8 it seems like the app doesn't honor the desired capabilities
and it defaults to English.
Here's the appium log for the same basic test being run twice: first for iOS 7.1 and then for iOS 8.1:
http://pastebin.mozilla.org/7249901

**Comment by djjwhw** [comment]
I have the same issue - impossible to run tests on a different language on iOS8, although the simulator starts on the language I requested, the app starts in english. Using the iOS7 simulator works fine.

Any workaround?

Thanks.

**Comment by hectorv** [comment]
I just verified that this is now fixed in iOS 8.2
