### ISSUE TITLE
Unable to automate using selendroid automation

### ISSUE THREAD

**Issue by Sendlink** [appium/appium#4034]
android - 4.0.3 real device
java client - 2.0.0
appium - 1.3.1
Windows 7 OS

Below is the code
         capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "Selendroid");
    	 capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
     	 capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "4.0.3");
     	 capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "HTC Desire V");
     	 capabilities.setCapability("udid","HT34APG02807");
       	 capabilities.setCapability(MobileCapabilityType.APP_PACKAGE,"eWallet.Android");
     	 capabilities.setCapability(MobileCapabilityType.APP_ACTIVITY,".ewallet.android.activities.SplashActivity");

Following is the log

C:\Users\Raghuram>appium &
info: Welcome to Appium v1.3.1 (REV 1160ce02bb89c354cb99317985123acf39f0e7d3)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"eWallet.And
roid","appActivity":".ewallet.android.activities.SplashActivity","platformVersio
n":"4.0.3","automationName":"Selendroid","platformName":"Android","udid":"HT34AP
G02807","deviceName":"HTC Desire V"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
info: [debug] Didn't get app but did get Android package, will attempt to launch
 it on the device
info: [debug] Creating new appium session 3b1f17cf-8f4f-490e-8143-f16911a110d1
info: [debug] Starting selendroid server
info: [debug] Checking whether selendroid is built yet
info: [debug] Selendroid server exists!
info: [debug] Preparing device for session
info: [debug] Not checking whether app is present since we are assuming it's alr
eady on the device
info: [debug] Checking whether adb is present
info: [debug] Using adb from E:\Automation\MobileAutomation\adt\adt-bundle\sdk\p
latform-tools\adb.exe
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing: "E:\Automation\MobileAutomation\adt\adt-bundle\sdk\plat
form-tools\adb.exe" devices
info: [debug] 2 device(s) connected
info: Found device HT34APG02807
info: [debug] Setting device id to HT34APG02807
info: [debug] Waiting for device to be ready and to respond to shell commands (t
imeout = 5)
info: [debug] executing: "E:\Automation\MobileAutomation\adt\adt-bundle\sdk\plat
form-tools\adb.exe" -s HT34APG02807 wait-for-device
info: [debug] executing: "E:\Automation\MobileAutomation\adt\adt-bundle\sdk\plat
form-tools\adb.exe" -s HT34APG02807 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from E:\Automation\MobileAutomation\adt\adt-bundle\sdk\
build-tools\android-4.4W\aapt.exe
info: [debug] hasInternetPermissionFromManifest: "E:\Automation\MobileAutomation
\adt\adt-bundle\sdk\build-tools\android-4.4W\aapt.exe" dump badging "null"
warn: W/asset   ( 9968): Asset path null is neither a directory nor file (type=1
).
ERROR: dump failed because assets could not be loaded

info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: hasInternetPermissionF
romManifest failed. Error: Command failed: W/asset   ( 9968): Asset path null is
 neither a directory nor file (type=1).
ERROR: dump failed because assets could not be loaded

info: [debug] Error: hasInternetPermissionFromManifest failed. Error: Command fa
iled: W/asset   ( 9968): Asset path null is neither a directory nor file (type=1
).
ERROR: dump failed because assets could not be loaded

    at C:\Users\Raghuram\AppData\Roaming\npm\node_modules\appium\node_modules\ap
pium-adb\lib\adb.js:1674:19
    at ChildProcess.exithandler (child_process.js:652:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"
A new session could not be created. (Original error: hasInternetPermissionFromMa
nifest failed. Error: Command failed: W/asset   ( 9968): Asset path null is neit
her a directory nor file (type=1).\r\nERROR: dump failed because assets could no
t be loaded\r\n)","origValue":"hasInternetPermissionFromManifest failed. Error:
Command failed: W/asset   ( 9968): Asset path null is neither a directory nor fi
le (type=1).\r\nERROR: dump failed because assets could not be loaded\r\n"},"ses
sionId":null}
info: <-- POST /wd/hub/session 500 143.439 ms - 526

**Comment by Jonahss** [comment]
I think your app manifest file needs this set?: `hasInternetPermissionFromManifest failed`

**Comment by moizjv** [comment]
Closing this issue. @Sendlink reopen if this is still an issue.
