### ISSUE TITLE
Unable to automate selendroid

### ISSUE THREAD

**Issue by Sendlink** [appium/appium#4035]
appium - 1.3.1
android - 4.0.3
java client - 1.2.0

Below is the code
 capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "Selendroid");
    	 capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
     	 capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "4.0.3");
     	 capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "HTC Desire V");
     	 capabilities.setCapability(MobileCapabilityType.APP, new File("C:/Users/Raghuram/Desktop/iSend/eWallet.Android-Signed.apk"));
     	 capabilities.setCapability("udid","HT34APG02807");
       	 capabilities.setCapability(MobileCapabilityType.APP_PACKAGE,"eWallet.Android");
     	 capabilities.setCapability(MobileCapabilityType.APP_ACTIVITY,".ewallet.android.activities.SplashActivity");

Below is the log

C:\Users\Raghuram>appium
info: Welcome to Appium v1.3.1 (REV 1160ce02bb89c354cb99317985123acf39f0e7d3)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Users\\Raghura
m\\Desktop\\iSend\\eWallet.Android-Signed.apk","appPackage":"eWallet.Android","a
ppActivity":".ewallet.android.activities.SplashActivity","platformVersion":"4.0.
3","automationName":"Selendroid","platformName":"Android","udid":"HT34APG02807",
"deviceName":"HTC Desire V"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
info: [debug] Using local app from desired caps: C:\Users\Raghuram\Desktop\iSend
\eWallet.Android-Signed.apk
info: [debug] Creating new appium session b1e984dd-cdb4-4194-b7b8-fe070a107424
info: [debug] Starting selendroid server
info: [debug] Checking whether selendroid is built yet
info: [debug] Selendroid server exists!
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present
info: [debug] Checking whether adb is present
info: [debug] Using adb from E:\Automation\MobileAutomation\adt\adt-bundle\sdk\p
latform-tools\adb.exe
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing: "E:\Automation\MobileAutomation\adt\adt-bundle\sdk\plat
form-tools\adb.exe" devices
info: [debug] 2 device(s) connected
info: Found device HT34APG02807
info: [debug] Setting device id to HT34APG02807
info: [debug] Waiting for device to be ready and to respond to shell commands (t
imeout = 5)
info: [debug] executing: "E:\Automation\MobileAutomation\adt\adt-bundle\sdk\plat
form-tools\adb.exe" -s HT34APG02807 wait-for-device
info: [debug] executing: "E:\Automation\MobileAutomation\adt\adt-bundle\sdk\plat
form-tools\adb.exe" -s HT34APG02807 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from E:\Automation\MobileAutomation\adt\adt-bundle\sdk\
build-tools\android-4.4W\aapt.exe
info: [debug] hasInternetPermissionFromManifest: "E:\Automation\MobileAutomation
\adt\adt-bundle\sdk\build-tools\android-4.4W\aapt.exe" dump badging "C:\Users\Ra
ghuram\Desktop\iSend\eWallet.Android-Signed.apk"
info: [debug] Rebuilt selendroid server already exists, no need to rebuild it wi
th a new manifest
info: [debug] Checking signed status of C:\Windows\Temp\selendroid.eWallet.Andro
id.apk
info: [debug] Checking app cert for C:\Windows\Temp\selendroid.eWallet.Android.a
pk: java -jar "C:\Users\Raghuram\AppData\Roaming\npm\node_modules\appium\node_mo
dules\appium-adb\jars\verify.jar" "C:\Windows\Temp\selendroid.eWallet.Android.ap
k"
info: [debug] Checking signed status of C:\Users\Raghuram\Desktop\iSend\eWallet.
Android-Signed.apk
info: [debug] Checking app cert for C:\Users\Raghuram\Desktop\iSend\eWallet.Andr
oid-Signed.apk: java -jar "C:\Users\Raghuram\AppData\Roaming\npm\node_modules\ap
pium\node_modules\appium-adb\jars\verify.jar" "C:\Users\Raghuram\Desktop\iSend\e
Wallet.Android-Signed.apk"
info: [debug] App already signed.
info: [debug] Zip-aligning C:\Windows\Temp\selendroid.eWallet.Android.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from E:\Automation\MobileAutomation\adt\adt-bundle\
sdk\build-tools\android-4.4W\zipalign.exe
info: [debug] zipAlignApk: "E:\Automation\MobileAutomation\adt\adt-bundle\sdk\bu
ild-tools\android-4.4W\zipalign.exe" -f 4 "C:\Windows\Temp\selendroid.eWallet.An
droid.apk" "C:\Users\Raghuram\AppData\Local\Temp\appium1141012-9972-9w6kwq.tmp"
info: [debug] App already signed.
info: [debug] Zip-aligning C:\Users\Raghuram\Desktop\iSend\eWallet.Android-Signe
d.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from E:\Automation\MobileAutomation\adt\adt-bundle\
sdk\build-tools\android-4.4W\zipalign.exe
info: [debug] zipAlignApk: "E:\Automation\MobileAutomation\adt\adt-bundle\sdk\bu
ild-tools\android-4.4W\zipalign.exe" -f 4 "C:\Users\Raghuram\Desktop\iSend\eWall
et.Android-Signed.apk" "C:\Users\Raghuram\AppData\Local\Temp\appium1141012-9972-
1hipz6c.tmp"
info: [debug] Rebuilt selendroid apk does not exist, uninstalling any instances
of it on device to make way for new one
info: [debug] Uninstalling eWallet.Android.selendroid
info: [debug] executing: "E:\Automation\MobileAutomation\adt\adt-bundle\sdk\plat
form-tools\adb.exe" -s HT34APG02807 shell "am force-stop eWallet.Android.selendr
oid"
info: [debug] executing: "E:\Automation\MobileAutomation\adt\adt-bundle\sdk\plat
form-tools\adb.exe" -s HT34APG02807 uninstall eWallet.Android.selendroid
info: [debug] App was not uninstalled, maybe it wasn't on device?
info: [debug] Getting install status for eWallet.Android.selendroid
info: [debug] Getting device API level
info: [debug] executing: "E:\Automation\MobileAutomation\adt\adt-bundle\sdk\plat
form-tools\adb.exe" -s HT34APG02807 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 15
info: [debug] executing: "E:\Automation\MobileAutomation\adt\adt-bundle\sdk\plat
form-tools\adb.exe" -s HT34APG02807 shell "pm list packages -3 eWallet.Android.s
elendroid"
info: [debug] App is not installed
info: [debug] Rebuilt selendroid is not installed, installing it
info: [debug] executing: "E:\Automation\MobileAutomation\adt\adt-bundle\sdk\plat
form-tools\adb.exe" -s HT34APG02807 install -r "C:\Windows\Temp\selendroid.eWall
et.Android.apk"
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Command failed: can't
find 'C:\Windows\Temp\selendroid.eWallet.Android.apk' to install

info: [debug] Error: Command failed: can't find 'C:\Windows\Temp\selendroid.eWal
let.Android.apk' to install

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"
A new session could not be created. (Original error: Command failed: can't find
'C:\\Windows\\Temp\\selendroid.eWallet.Android.apk' to install\r\n)","killed":fa
lse,"code":1,"signal":null,"origValue":"Command failed: can't find 'C:\\Windows\
\Temp\\selendroid.eWallet.Android.apk' to install\r\n"},"sessionId":null}
info: <-- POST /wd/hub/session 500 4192.586 ms - 346

**Comment by 0x1mason** [comment]
Closing as no repro.
