### ISSUE TITLE
support starting an android session with multiple apps installed

### ISSUE THREAD

**Issue by jlipps** [appium/appium#4063]
Since we can switch between apps on Android, it'd be nice to add the ability for the app cap to be a comma-separated list of apks, or add a new cap 'extraApps' that install extra apps in the session start flow. This ensures that if a user is trying to test between-app interaction, they can use appium to get set up with all the apps they need to test, even though they are only going to start one.

**Comment by sindhu2990** [comment]
Is this implemented in Appium 1.4 and above? If so, could you please share the usage?

**Comment by jlipps** [comment]
This is just a feature request, it is not implemented yet.

**Comment by crtlib** [comment]
@jlipps I'd like to implement this feature, because without it we're bound to local testing only. Could you please give some insights / summarize most important points?

**Comment by jlipps** [comment]
@crtlib that'd be great! It's not actually too difficult, I don't think. First of all, the work would need to be done in the appium-android-driver repo/package. In my mind it looks like simply adding a new capability `extraApps` which takes an array of app paths or urls, and on startup, for each of these extra apps, goes through the same process of downloading and installation as the driver already goes through for the 'default' app. All the logic for that is already there! And of course there might be some small refactoring to support this, but for the most part the change should be localized and straightforward.

**Comment by mykola-mokhnach** [comment]
This has been implemented by @dpgraham
