### ISSUE TITLE
StaleElementReferenceException not thrown until 600 seconds later 

### ISSUE THREAD

**Issue by jackwhitney** [appium/appium#4064]
I am using Appium/Selendroid. Most of the time when a StaleElementReferenceException is thrown it happens right away, but sometimes it doesn't get thrown for 600 seconds.

More detail here: https://discuss.appium.io/t/staleelementreferenceexception-not-thrown-until-600-seconds-later/915

**Comment by moizjv** [comment]
@jackwhitney can you retry it latest version ? And also mention steps to reproduce the issue and logs so we can look into it

**Comment by Jonahss** [comment]
How should we reproduce this issue?

**Comment by sebv** [comment]
This kind of errors should be taken care of by the appium rewrite.

**Comment by jlipps** [comment]
@jackwhitney this should be fixed in the 1.5 beta. if you can still repro, please let us know!
