### ISSUE TITLE
support requestOrigins and user agent origins for all appium bindings

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#4065]
It'd be nice to know what binding is making webdriver requests. There are currently two approaches:
- [request origins](https://groups.google.com/d/msg/selenium-developers/Zj1ikTz632o/jZDxVvZkCy4J)
- [user agent](https://github.com/admc/wd/pull/342) in the form of: `author/libraryName/version`

I think the appium clients shouldn't use the same user agent as the selenium clients. Even if we're not using the user agent for data tracking, it still makes sense to differentiate an appium client user agent from the upstream selenium client.

The request origins approach is better for collecting data. The appium clients should adopt this in addition to the useragent.

Some progress has been made already:
- [appium's server prints out the user agent of the client](https://github.com/appium/appium/pull/3622)
- [appium's ruby client supports the user agent](../../ruby_lib/commit/af6d44c6ccd3f32a9553be3c290000421edae92d)
- [wd](https://github.com/admc/wd/pull/342) has an open pull request to support the user agent
- [webdriver.io implements both the user agent and the cap](https://github.com/webdriverio/webdriverio/issues/296)
# Implementation Status

| project | user agent | cap |
| :-: | :-: | :-: |
| appium server | :white_check_mark: | :red_circle: |
| appium ruby | :white_check_mark: | :red_circle: |
| webdriver.io | :white_check_mark: | :white_check_mark: |
| appium python | :white_check_mark: | :red_circle: |
| other bindings | :red_circle: | :red_circle: |

Ideally each appium client should support both the cap & user agent.

**Comment by mykola-mokhnach** [comment]
@KazuCocoa I suppose both python and ruby clients do support this feature now?

**Comment by KazuCocoa** [comment]
Yes. They have

**Comment by mykola-mokhnach** [comment]
Closed as resolved
