### ISSUE TITLE
Error is displayed while using selendroid in appium 1.3.2 beta 2

### ISSUE THREAD

**Issue by Sendlink** [appium/appium#4070]
appium - 1.3.2 beta 2
java-client - 2.0.0
OS - windows 7
android - 4.0.3 real device

	DesiredCapabilities capabilities = new DesiredCapabilities();
    	capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "Selendroid");
   	 	capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
    	capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "4.0.3");
    	capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "HTC Desire V");
    	    	
    	capabilities.setCapability(MobileCapabilityType.APP, new File("C:/Users/raghuadmin1.ZENQATEST2/Downloads/eBay_Recent.apk"));
    	capabilities.setCapability("udid","HT34APG02807");   
    	driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);

Below is log:- 

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\raghuadmin1.ZENQATEST2>appium &
info: Welcome to Appium v1.3.2-beta2 (REV c28942bdd0f377b14ab6b88a268760d08f9ad2
fc)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Users\\raghuad
min1.ZENQATEST2\\Downloads\\eBay_Recent.apk","platformVersion":"4.0.3","automati
onName":"Selendroid","platformName":"Android","udid":"HT34APG02807","deviceName"
:"HTC Desire V"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
info: [debug] No appActivity desired capability or server param. Parsing from ap
k.
info: [debug] No appPackage desired capability or server param. Parsing from apk
.
info: [debug] Using local app from desired caps: C:\Users\raghuadmin1.ZENQATEST2
\Downloads\eBay_Recent.apk
info: [debug] Creating new appium session 83edd880-9da6-4ca1-9573-5d7bbadf1a89
info: [debug] Starting selendroid server
info: [debug] Checking whether selendroid is built yet
info: [debug] Selendroid server exists!
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present
info: [debug] Checking whether adb is present
info: [debug] Using adb from C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\s
dk\platform-tools\adb.exe
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" devices
info: [debug] 1 device(s) connected
info: Found device HT34APG02807
info: [debug] Setting device id to HT34APG02807
info: [debug] Waiting for device to be ready and to respond to shell commands (t
imeout = 5)
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 wait-for-device
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\
sdk\build-tools\android-4.4W\aapt.exe
info: [debug] hasInternetPermissionFromManifest: "C:\Users\raghuadmin1.ZENQATEST
2\Downloads\adt\adt\sdk\build-tools\android-4.4W\aapt.exe" dump badging "C:\User
s\raghuadmin1.ZENQATEST2\Downloads\eBay_Recent.apk"
info: [debug] Parsing package and activity from app manifest
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\
sdk\build-tools\android-4.4W\aapt.exe
info: [debug] packageAndLaunchActivityFromManifest: "C:\Users\raghuadmin1.ZENQAT
EST2\Downloads\adt\adt\sdk\build-tools\android-4.4W\aapt.exe" dump badging "C:\U
sers\raghuadmin1.ZENQATEST2\Downloads\eBay_Recent.apk"
info: [debug] badging package: com.ebay.mobile
info: [debug] badging act: com.ebay.mobile.activities.eBay
info: [debug] Parsed package and activity are: com.ebay.mobile/com.ebay.mobile.a
ctivities.eBay
info: [debug] Rebuilt selendroid server already exists, no need to rebuild it wi
th a new manifest
info: [debug] Checking signed status of C:\Windows\Temp\selendroid.com.ebay.mobi
le.apk
info: [debug] Checking app cert for C:\Windows\Temp\selendroid.com.ebay.mobile.a
pk: java -jar "C:\Users\raghuadmin1.ZENQATEST2\AppData\Roaming\npm\node_modules\
appium\node_modules\appium-adb\jars\verify.jar" "C:\Windows\Temp\selendroid.com.
ebay.mobile.apk"
info: [debug] Checking signed status of C:\Users\raghuadmin1.ZENQATEST2\Download
s\eBay_Recent.apk
info: [debug] Checking app cert for C:\Users\raghuadmin1.ZENQATEST2\Downloads\eB
ay_Recent.apk: java -jar "C:\Users\raghuadmin1.ZENQATEST2\AppData\Roaming\npm\no
de_modules\appium\node_modules\appium-adb\jars\verify.jar" "C:\Users\raghuadmin1
.ZENQATEST2\Downloads\eBay_Recent.apk"
info: [debug] App already signed.
info: [debug] Zip-aligning C:\Windows\Temp\selendroid.com.ebay.mobile.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\
adt\sdk\build-tools\android-4.4W\zipalign.exe
info: [debug] zipAlignApk: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sd
k\build-tools\android-4.4W\zipalign.exe" -f 4 "C:\Windows\Temp\selendroid.com.eb
ay.mobile.apk" "C:\Windows\Temp\appium1141014-3348-ik2vqg.tmp"
info: [debug] App already signed.
info: [debug] Zip-aligning C:\Users\raghuadmin1.ZENQATEST2\Downloads\eBay_Recent
.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\
adt\sdk\build-tools\android-4.4W\zipalign.exe
info: [debug] zipAlignApk: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sd
k\build-tools\android-4.4W\zipalign.exe" -f 4 "C:\Users\raghuadmin1.ZENQATEST2\D
ownloads\eBay_Recent.apk" "C:\Windows\Temp\appium1141014-3348-1l4byms.tmp"
info: [debug] Rebuilt selendroid apk does not exist, uninstalling any instances
of it on device to make way for new one
info: [debug] Uninstalling com.ebay.mobile.selendroid
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "am force-stop com.ebay.mobile.sel
endroid"
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 uninstall com.ebay.mobile.selendroid
info: [debug] App was uninstalled
info: [debug] Getting install status for com.ebay.mobile.selendroid
info: [debug] Getting device API level
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 15
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "pm list packages -3 com.ebay.mobi
le.selendroid"
info: [debug] App is not installed
info: [debug] Rebuilt selendroid is not installed, installing it
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 install -r "C:\Windows\Temp\selendroid.c
om.ebay.mobile.apk"
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "getprop persist.sys.language"
info: [debug] Current device language: en
info: [debug] java -jar "C:\Users\raghuadmin1.ZENQATEST2\AppData\Roaming\npm\nod
e_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFrom
Apk" "C:\Users\raghuadmin1.ZENQATEST2\Downloads\eBay_Recent.apk" "C:\Windows\Tem
p\com.ebay.mobile" en
info: [debug] No strings.xml for language 'en', getting default strings.xml
info: [debug] java -jar "C:\Users\raghuadmin1.ZENQATEST2\AppData\Roaming\npm\nod
e_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFrom
Apk" "C:\Users\raghuadmin1.ZENQATEST2\Downloads\eBay_Recent.apk" "C:\Windows\Tem
p\com.ebay.mobile"
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Checking app cert for C:\Users\raghuadmin1.ZENQATEST2\Downloads\eB
ay_Recent.apk: java -jar "C:\Users\raghuadmin1.ZENQATEST2\AppData\Roaming\npm\no
de_modules\appium\node_modules\appium-adb\jars\verify.jar" "C:\Users\raghuadmin1
.ZENQATEST2\Downloads\eBay_Recent.apk"
info: [debug] App already signed.
info: [debug] Zip-aligning C:\Users\raghuadmin1.ZENQATEST2\Downloads\eBay_Recent
.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\
adt\sdk\build-tools\android-4.4W\zipalign.exe
info: [debug] zipAlignApk: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sd
k\build-tools\android-4.4W\zipalign.exe" -f 4 "C:\Users\raghuadmin1.ZENQATEST2\D
ownloads\eBay_Recent.apk" "C:\Windows\Temp\appium1141014-3348-1jkbh1f.tmp"
info: [debug] MD5 for app is c7f66b63c024464e687ed693c723e99b
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "ls /data/local/tmp/c7f66b63c02446
4e687ed693c723e99b.apk"
info: [debug] Getting install status for com.ebay.mobile
info: [debug] Getting device API level
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 15
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "pm list packages -3 com.ebay.mobi
le"
info: [debug] App is installed
info: App is already installed, resetting app
info: [debug] Running fast reset (stop and clear)
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "am force-stop com.ebay.mobile"
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "pm clear com.ebay.mobile"
info: [debug] Forwarding system:8080 to device:8080
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 forward tcp:8080 tcp:8080
info: [debug] Pushing settings apk to device...
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 install "C:\Users\raghuadmin1.ZENQATEST2
\AppData\Roaming\npm\node_modules\appium\build\settings_apk\settings_apk-debug.a
pk"
info: [debug] Pushing unlock helper app to device...
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 install "C:\Users\raghuadmin1.ZENQATEST2
\AppData\Roaming\npm\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "dumpsys window"
info: [debug] Screen already unlocked, continuing.
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "am instrument -e main_activity 'c
om.ebay.mobile.activities.eBay' com.ebay.mobile.selendroid/io.selendroid.ServerI
nstrumentation"
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hu
b/status","method":"GET"}
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hu
b/status","method":"GET"}
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hu
b/status","method":"GET"}
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hu
b/status","method":"GET"}
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hu
b/status","method":"GET"}
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hu
b/status","method":"GET"}
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hu
b/status","method":"GET"}
info: [debug] Selendroid server is alive!
info: [debug] Listening for Selendroid logs
info: [debug] Creating Selendroid session
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hu
b/session","method":"POST","json":{"desiredCapabilities":{"warnings":{},"desired
":{"app":"C:\\Users\\raghuadmin1.ZENQATEST2\\Downloads\\eBay_Recent.apk","platfo
rmVersion":"4.0.3","automationName":"Selendroid","platformName":"Android","udid"
:"HT34APG02807","deviceName":"HTC Desire V"},"app":"C:\\Users\\raghuadmin1.ZENQA
TEST2\\Downloads\\eBay_Recent.apk","platformVersion":"4.0.3","automationName":"S
elendroid","platformName":"Android","udid":"HT34APG02807","deviceName":"HTC Desi
re V"}}}
info: [debug] Successfully started selendroid session
info: [debug] Waiting for pkg "com.ebay.mobile" and activity "com.ebay.mobile.ac
tivities.eBay" to be focused
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "dumpsys window windows"
info: [debug] [SELENDROID] http://localhost:8080/wd/hub/session/05effec4-5126-69
ae-4d94-9b95b809c775
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "dumpsys window windows"
error: com.ebay.mobile/.activities.eBay never started. Current: com.ebay.mobile/
.activities.TermsOfUseActivity
info: [debug] Selendroid hasn't started app yet, let's do it manually with adb.s
tartApp
info: [debug] Getting device API level
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 15
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "am start -S -a android.intent.act
ion.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.ebay.mobile/co
m.ebay.mobile.activities.eBay"
info: [debug] [SELENDROID] com.android.server.SystemServer.init1(Native Method)
info: [debug] [SELENDROID] com.android.server.SystemServer.main(SystemServer.jav
a:979)
info: [debug] [SELENDROID] @@@- disable SystemServer HW acceleration
info: [debug] Waiting for pkg "com.ebay.mobile" and activity "com.ebay.mobile.ac
tivities.eBay" to be focused
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\Users\raghuadmin1.ZENQATEST2\Downloads\adt\adt\sdk\
platform-tools\adb.exe" -s HT34APG02807 shell "dumpsys window windows"
info: [debug] Overriding session id with "05effec4-5126-69ae-4d94-9b95b809c775"
info: [debug] Device launched! Ready for commands
info: [debug] Setting command timeout to the default of 60 secs
info: [debug] Appium session started with sessionId 05effec4-5126-69ae-4d94-9b95
b809c775
info: <-- POST /wd/hub/session 303 63425.428 ms - 9
info: --> GET /wd/hub/session/05effec4-5126-69ae-4d94-9b95b809c775 {}
info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hu
b/session/05effec4-5126-69ae-4d94-9b95b809c775","method":"GET"}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"
An unknown server-side error occurred while processing the command.","origValue"
:"Did not successfully proxy server command"},"sessionId":"05effec4-5126-69ae-4d
94-9b95b809c775"}
info: <-- GET /wd/hub/session/05effec4-5126-69ae-4d94-9b95b809c775 500 17.658 ms
 - 210

**Comment by Jonahss** [comment]
Closed due to inactivity. Reopen if more information provided.
