### ISSUE TITLE
multiple devices parallel execution is not working for longer time .

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#4072]
I have launched multiple appium server instances with different port bindings to run two devices parallely . It is working for sometime and after sometime it throws web driver exception and the test stops in one device and the other device it is working.Can we get any fix for this in appium version 1.3.2

**Comment by poojaverma-2611** [comment]
I am also facing the same issue...For me adb get closed after 1 hr and execution gets interrupted, but there is no discrepancy in the port number for me as mentioned above.

**Comment by naveenjammula** [comment]
we have given different bootstrap ports for each server and it is working fine after that..closing the issue. If required i will repopen again

**Comment by Janardhanrao** [comment]
@naveenjammula  hey can u share your code to run test cases on multiple devices at a time. I tried but it always running on sequential order
