### ISSUE TITLE
Appium 1.3 - SendKeys not working on REAL ANDROID Device (OS - 4.4)

### ISSUE THREAD

**Issue by shailendrajain1208** [appium/appium#4093]
I have appium 1.3 , Android Real device 4.4 and trying to use send keys method to type in username and password and it fails. It type in Username field correctly then it goes to password field and then jump to  username and remove it and then jump to password and type it. Finally I lost username which I entered. Please suggest.

NOTE: NO ISSUES WITH EMULATOR.

Solution: I switched back to APPIUM 1.2 and it works fine.

Tried in below ways:
 on(WalletISSOLoginPage).set_user_name_txt(data("username"))
  on(WalletISSOLoginPage).set_pass_word_txt(data("password”))
OR
  first_textview = $driver.find_element(:uiautomator, 'new UiSelector().className("android.widget.EditText").instance(0)')
 #first_textview.click
  first_textview.sendKeys('foo')
 #first_textview.setValue('foo')
 # first_textview.type 'foo'
 # first_textview.type 'ooo'
  first_textview1 = $driver.find_element(:uiautomator, 'new UiSelector().className("android.widget.EditText").instance(1)')
  first_textview1.sendKeys('foomnnn’)

**Comment by imurchie** [comment]
This, iirc, has been fixed.
