### ISSUE TITLE
support iOS 8.2

### ISSUE THREAD

**Issue by jlipps** [appium/appium#4097]
this is now in beta. adding to next feature milestone

**Comment by 0x1mason** [comment]
@jlipps @imurchie Associating 8.2 support with 1.3.5.

**Comment by 0x1mason** [comment]
Nm, closing because duplicate with #4278 .

**Comment by imurchie** [comment]
Reopening, in case there is something that needs to happen when the full 6.2 xcode is released.

**Comment by moizjv** [comment]
duplicate of #4828
