### ISSUE TITLE
IOS: senKeys to pickerwheel [found by className] doesnt work

### ISSUE THREAD

**Issue by p00j4** [appium/appium#4106]
the given alternative for locating strategy <b>tagName</b> is <b>className</b>, which works while finding but fails while sending keys into it [though same thing works with xpath, but I dont want to rely on xpath because of its dynamic nature]
is it issue with className or sendkeys implementation for pickerwheel in ios !

info: [debug] Sending command to instruments: au.getElementByType('UIAPickerWheel')
info: [debug] [INST] 2014-11-19 15:15:31 +0000 Debug: Got new command 57 from instruments: au.getElementByType('UIAPickerWheel')
info: [debug] Socket data received (39 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"14"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"14"},"sessionId":"212f929a-37e4-4c03-b759-b89818e26983"}
info: <-- POST /wd/hub/session/212f929a-37e4-4c03-b759-b89818e26983/element 200 152.661 ms - 88 {"status":0,"value":{"ELEMENT":"14"},"sessionId":"212f929a-37e4-4c03-b759-b89818e26983"}
info: [debug] [INST] 2014-11-19 15:15:31 +0000 Debug: evaluating au.getElementByType('UIAPickerWheel')
info: [debug] [INST] 2014-11-19 15:15:31 +0000 Debug: evaluation finished
info: [debug] [INST] 2014-11-19 15:15:31 +0000 Debug: responding with:
info: [debug] [INST] 2014-11-19 15:15:31 +0000 Debug: Running system command #58: /usr/local/Cellar/node/0.10.26/bin/node /Users/pooja/Documents/Automation/openSource/Appium_versions/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"14"}}...
info: --> POST /wd/hub/session/212f929a-37e4-4c03-b759-b89818e26983/element/14/value {"id":"14","value":["ECONOMY CLASS"]}
info: [debug] Pushing command to appium work queue: "au.getElement('14').setValueByType('ECONOMY CLASS')"
info: [debug] Sending command to instruments: au.getElement('14').setValueByType('ECONOMY CLASS')
info: [debug] [INST] 2014-11-19 15:15:44 +0000 Debug: Got new command 58 from instruments: au.getElement('14').setValueByType('ECONOMY CLASS')
info: [debug] [INST] 2014-11-19 15:15:44 +0000 Debug: evaluating au.getElement('14').setValueByType('ECONOMY CLASS')
info: [debug] [INST] 2014-11-19 15:15:44 +0000 Debug: - selectValue requires a valid value
info: [debug] Socket data received (62 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":17,"value":"- selectValue requires a valid value"}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"- selectValue requires a valid value"},"sessionId":"212f929a-37e4-4c03-b759-b89818e26983"}
info: <-- POST /wd/hub/session/212f929a-37e4-4c03-b759-b89818e26983/element/14/value 500 521.331 ms - 197 
info: [debug] [INST] 2014-11-19 15:15:44 +0000 Error: VerboseError: - selectValue requires a valid value
info: [debug] [INST] 2014-11-19 15:15:44 +0000 Error: Error during eval: selectValue@[native code]
       setValueByType@file:///Users/pooja/Documents/Automation/openSource/Appium_versions/appium/0B0BD200-91B1-48EE-BC21-DE477632523C/bootstrap-566356f7a7a8c502.js:1972:23

![image](https://cloud.githubusercontent.com/assets/6470509/5112361/582057a0-704d-11e4-9fd8-b06510b0d66c.png)

**Comment by cjtcwyk** [comment]
my env is OSX10.9.4, appium1.3.6, java client2.2, I encountered the same problem. In a day picker, I can find UIAPickerWheel[0], UIAPickerWheel[1], UIAPickerWheel[2] in one UIAPicker, I can sendKeys to UIAPickerWheel[0] and it just works fine, but when I sendKeys to UIAPickerWheel[1] and UIAPickerWheel[2] appium doesn't work, it looks like less a selectValue when sendKeys to the second UIAPickerWheel, the log as:

info: [debug] Got result from instruments: {"status":17,"value":"- selectValue requires a valid value"}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"- selectValue requires a valid value"},"sessionId":"faa53713-c311-4e65-a06b-d0251b9e8e52"}
info: <-- POST /wd/hub/session/faa53713-c311-4e65-a06b-d0251b9e8e52/element/0/value 500 290.213 ms - 197
info: [debug] [INST] 2015-03-31 02:25:12 +0000 Error: VerboseError: - selectValue requires a valid value
info: [debug] [INST] 2015-03-31 02:25:12 +0000 Error: Error during eval: selectValue@[native code]
setValueByType@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/8727E22B-81C7-4F30-8045-3F6A76C672F4/bootstrap-516354d056bc7b25.js:1994:23
eval code
eval@[native code]
startProcessing@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/8727E22B-81C7-4F30-8045-3F6A76C672F4/bootstrap-516354d056bc7b25.js:2685:30
bootstrap@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/8727E22B-81C7-4F30-8045-3F6A76C672F4/bootstrap-516354d056bc7b25.js:2753:31
global code@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/8727E22B-81C7-4F30-8045-3F6A76C672F4/bootstrap-516354d056bc7b25.js:2762:10
info: [debug] [INST] 2015-03-31 02:25:12 +0000 Debug: responding with:
info: [debug] [INST] 2015-03-31 02:25:12 +0000 Debug: Running system command #6: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":17,"value":"- selectValue requires a valid value"}...

**Comment by Jonahss** [comment]
Hm. ok looks like there's enough information here to reproduce the bug ourselves.

**Comment by concertman** [comment]
Any new information on this one?

I'm seeing this as well. I'm also seeing it happen when accessing the element via the xpath. Here's the log output...
```
info: [debug] [INST] 2015-06-18 16:14:04 +0000 Debug: Got new command 43 from instruments: au.getElementByIndexPath('/0/1/1/0')
info: [debug] Socket data received (38 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"8"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"8"},"sessionId":"36e8cdce-4779-4b32-835a-1ccf454da0ce"}
info: <-- POST /wd/hub/session/36e8cdce-4779-4b32-835a-1ccf454da0ce/element 200 382.467 ms - 87 {"status":0,"value":{"ELEMENT":"8"},"sessionId":"36e8cdce-4779-4b32-835a-1ccf454da0ce"}
info: --> POST /wd/hub/session/36e8cdce-4779-4b32-835a-1ccf454da0ce/element/8/value {"value":["2 - (€ 4.00)"]}
info: [debug] Pushing command to appium work queue: "au.getElement('8').setValueByType('2 - (€ 4.00)')"
info: [debug] Sending command to instruments: au.getElement('8').setValueByType('2 - (€ 4.00)')
info: [debug] [INST] 2015-06-18 16:14:04 +0000 Debug: evaluating au.getElementByIndexPath('/0/1/1/0')
info: [debug] [INST] 2015-06-18 16:14:04 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-06-18 16:14:04 +0000 Debug: responding with:
info: [debug] [INST] 2015-06-18 16:14:04 +0000 Debug: Running system command #44: /usr/local/Cellar/node/0.12.2_1/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"8"}}...
info: [debug] [INST] 2015-06-18 16:14:04 +0000 Debug: Got new command 44 from instruments: au.getElement('8').setValueByType('2 - (€ 4.00)')
info: [debug] [INST] 2015-06-18 16:14:04 +0000 Debug: evaluating au.getElement('8').setValueByType('2 - (€ 4.00)')
info: [debug] [INST] 2015-06-18 16:14:04 +0000 Debug: - selectValue requires a valid value
info: [debug] Socket data received (62 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":17,"value":"- selectValue requires a valid value"}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"- selectValue requires a valid value"},"sessionId":"36e8cdce-4779-4b32-835a-1ccf454da0ce"}
info: <-- POST /wd/hub/session/36e8cdce-4779-4b32-835a-1ccf454da0ce/element/8/value 500 221.926 ms - 197 
info: [debug] [INST] 2015-06-18 16:14:04 +0000 Error: VerboseError: - selectValue requires a valid value
info: [debug] [INST] 2015-06-18 16:14:04 +0000 Error: Error during eval: selectValue@[native code]
       setValueByType@file:///usr/local/lib/node_modules/appium/7D2EB2DE-F75A-4DBD-A313-5C76FEE9D2F0/bootstrap-33fd17bc4e457098.js:1994:23
eval code
eval@[native code]
startProcessing@file:///usr/local/lib/node_modules/appium/7D2EB2DE-F75A-4DBD-A313-5C76FEE9D2F0/bootstrap-33fd17bc4e457098.js:2693:30
bootstrap@file:///usr/local/lib/node_modules/appium/7D2EB2DE-F75A-4DBD-A313-5C76FEE9D2F0/bootstrap-33fd17bc4e457098.js:2761:31
global code@file:///usr/local/lib/node_modules/appium/7D2EB2DE-F75A-4DBD-A313-5C76FEE9D2F0/bootstrap-33fd17bc4e457098.js:2770:10
info: [debug] [INST] 2015-06-18 16:14:04 +0000 Debug: responding with:
info: [debug] [INST] 2015-06-18 16:14:04 +0000 Debug: Running system command #45: /usr/local/Cellar/node/0.12.2_1/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":17,"value":"- selectValue requires a valid value"}...

```

**Comment by cjtcwyk** [comment]
update to Appium 1.4 and looks like still not fixed.

**Comment by sebv** [comment]
@cjtcwyk since it is open and marked open...probably not

**Comment by VTINFOJames** [comment]
I'm having a very similar problem testing a Native mobile iOS 8.4 app with Appium 1.4.8.
However, using the className location strategy and swiping DOWN on a UIAPickerWheel works for me.
When swiping UP the entire UIAPickerWheel is selected and swiped up as a whole object; the wheel does not scroll. I had opened another issue a few days ago before I found this discussion:
https://github.com/appium/appium/issues/5465

**Comment by VTINFOJames** [comment]
Update: I just tried using sendKeys for a particular date String and it worked. So now my test is able to scroll DOWN to a value with (SwipeElementDirection.DOWN, 1000) and then move UP to a given date using SendKeys("dateString"). This is enough for me to verify that the picker wheel can be swiped, verify  that it contains multiple values and then position back to a desired date.

**Comment by chrisjywu** [comment]
i used same method to send keys to UIAPickerWheels. 

some are working, some not working. 

is it possible that it is related to the implementation of the UIAPickerWheel in the app?

**Comment by chrisjywu** [comment]
`2016-04-14 17:57:40:760 - info: [debug] Socket data being routed.
2016-04-14 17:57:40:761 - info: [debug] Got result from instruments: {"status":17,"value":"- selectValue requires a valid value"}
2016-04-14 17:57:40:761 - info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"- selectValue requires a valid value"},"sessionId":"e79f7480-0a2b-407e-871f-8467fbae35de"}
2016-04-14 17:57:40:764 - info: <-- POST /wd/hub/session/e79f7480-0a2b-407e-871f-8467fbae35de/element/46/value 500 10990.743 ms - 197 
2016-04-14 17:57:40:839 - info: [debug] [INST] 2016-04-14 09:57:40 +0000 Error: VerboseError: - selectValue requires a valid value

2016-04-14 17:57:41:068 - info: [debug] [INST] 2016-04-14 09:57:40 +0000 Error: Error during eval: selectValue@[native code]
       setValueByType@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/8897486F-C942-4263-9394-3F68C292142F/bootstrap-9a1136664d01e391.js:2002:23
eval code
eval@[native code]
startProcessing@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/8897486F-C942-4263-9394-3F68C292142F/bootstrap-9a1136664d01e391.js:2710:30
bootstrap@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/8897486F-C942-4263-9394-3F68C292142F/bootstrap-9a1136664d01e391.js:2778:31
global code@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/8897486F-C942-4263-9394-3F68C292142F/bootstrap-9a1136664d01e391.js:2787:10
2016-04-14 17:57:41:080 - info: [debug] [INST] 2016-04-14 09:57:40 +0000 Debug: responding with:
2016-04-14 17:57:41:091 - info: [debug] [INST] 2016-04-14 09:57:40 +0000 Debug: Running system command #77: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":17,"value":"- selectValue requires a valid value"}...`

**Comment by imurchie** [comment]
What is the value being sent? That snippet of the logs does not say, so it's hard to know what is happening. The _full_ logs are generally helpful.

**Comment by 18516329677** [comment]
is there any other way to set value for pickerwheel ?

**Comment by imurchie** [comment]
Not generally. But you could ask on [appium discuss](https://discuss.appium.io/) to see if anyone else has a way.

**Comment by shekhar-ireslab** [comment]
Hi 
i have found the solution how to handle wheel picker.
update java client jar file and add below code 
((IOSElement)driver.findElements(By.className("UIAPickerWheel")).get(indexvalue)).sendKeys("12");
