### ISSUE TITLE
Issues with the tap option in the appium version 1.3.2-beta2 in iOS

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#4111]
I am using appium version 1.3.2-beta2 in the mac machine and i am testing with the iphone of IOS-7.
 When i select a precise tap with duration as 0 sec, its performing a long tap instead of tap.

**Comment by naveenjammula** [comment]
can you please provide update on this when it is going to fix...It is blocking our automation scenarios

**Comment by imurchie** [comment]
Have you tried to use the Touch Action API? That would be preferred to this mobile tap.

**Comment by naveenjammula** [comment]
Yes we have used the API  "tap(self, positions, duration=None):" . Here when we give the duration as 0 but still it is performing the long press.

**Comment by naveenjammula** [comment]
When i select a tap with duration as 0 sec, its performing a long tap instead of tap

**Comment by imurchie** [comment]
And not using `0`? The duration is, as well, is in milliseconds, not seconds.

**Comment by naveenjammula** [comment]
I am selecting tap with duration as 0 or more  milli secs  ,  its performing a long tap instead of tap . Can you please fix it ASAP .Its blocking issue for us.

**Comment by naveenjammula** [comment]
Any update on this?

**Comment by imurchie** [comment]
Update: I can't reproduce this. Running the `tap` method triggers a `tap` event (caught by the `UITapGestureRecognizer` delegate). As you can see in the logs, under the hood Apple's [`UIAElement.tapWithOptions`](https://developer.apple.com/library/ios/documentation/ToolsLanguages/Reference/UIAElementClassReference/index.html#//apple_ref/javascript/instm/UIAElement/tapWithOptions) action. You could try manually doing one of those to see if a long tap is still engaged.

**Comment by naveenjammula** [comment]
Hi,
We are using appium client for running our test case, In that we are internally calling tap function (def tap(self, positions, duration=None))  with the duration as None, but when i run the test I observered from logs that its taking duration as 0.2? I am not sure why that is happening and its performing long tap. below are the logs:
[36minfo[39m: [debug] Responding to client with success: {"status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAKQWlDQ1BJQ0MgUHJvZmlsZQAASA2dlndUU9kWh8+9N73QEiIgJfQaegkg0jtIFQRRiUmAUAKGhCZ2RAVGFBEpVmRUwAFHhyJjRRQLg4Ji1wnyEFDGwVFEReXdjGsJ7601896a/cdZ39nnt9fZZ+9917oAUPyCBMJ0WAGANKFYFO7rwVwSE8vE9wIYEAEOWAHA4WZmBEf4RALU/L09mZmoSMaz9u4ugGS72yy/UCZz1v9/kSI3QyQGAApF1TY8fiYX5QKUU7PFGTL/BMr0lSkyhjEyFqEJoqwi48SvbPan5iu7yZiXJuShGlnOGbw0noy7UN6aJeGjjAShXJgl4GejfAdlvVRJmgDl9yjT0/icTAAwFJlfzOcmoWyJMkUUGe6J8gIACJTEObxyDov5OWieAHimZ+SKBIlJYqYR15hp5ejIZvrxs1P5YjErlMNN4Yh4TM/0tAyOMBeAr2+WRQElWW2ZaJHtrRzt7VnW5mj5v9nfHn5T/T3IevtV8Sbsz55BjJ5Z32zsrC+9FgD2JFqbHbO+lVUAtG0GQOXhrE/vIADyBQC03pzzHoZsXpLE4gwnC4vs7GxzAZ9rLivoN/ufgm/Kv4Y595nL7vtWO6YXP4EjSRUzZUXlpqemS0TMzAwOl89k/fcQ/+PAOWnNycMsnJ/AF/GF6FVR6JQJhIlou4U8gViQLmQKhH/V4X8YNicHGX6daxRodV8AfYU5ULhJB8hvPQBDIwMkbj96An3rWxAxCsi+vGitka9zjzJ6/uf6Hwtcim7hTEEiU+b2DI9kciWiLBmj34RswQISkAd0oAo0gS4wAixgDRyAM3AD3iAAhIBIEAOWAy5IAmlABLJBPtgACkEx2AF2g2pwANSBetAEToI2cAZcBFfADXALDIBHQAqGwUswAd6BaQiC8BAVokGqkBakD5lC1hAbWgh5Q0FQOBQDxUOJkBCS...","sessionId":"f2f2a44a-0f8b-4495-9e1e-1fa44bece032"}
[36minfo[39m: [37m<-- GET /wd/hub/session/f2f2a44a-0f8b-4495-9e1e-1fa44bece032/screenshot [39m[32m200[39m[90m 2440.921 ms - 473898[39m [90m{"status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAKQWlDQ1BJQ0MgUHJvZmlsZQAASA2dlndUU9kWh8+9N73QEiIgJfQaegkg0jtIFQRRiUmAUAKGhCZ2RAVGFBEpVmRUwAFHhyJjRRQLg4Ji1wnyEFDGwVFEReXdjGsJ7601896a/cdZ39nnt9fZZ+9917oAUPyCBMJ0WAGANKFYFO7rwVwSE8vE9wIYEAEOWAHA4WZmBEf4RALU/L09mZmoSMaz9u4ugGS72yy/UCZz1v9/kSI3QyQGAApF1TY8fiYX5QKUU7PFGTL/BMr0lSkyhjEyFqEJoqwi48SvbPan5iu7yZiXJuShGlnOGbw0noy7UN6aJeGjjAShXJgl4GejfAdlvVRJmgDl9yjT0/icTAAwFJlfzOcmoWyJMkUUGe6J8gIACJTEObxyDov5OWieAHimZ+SKBIlJYqYR15hp5ejIZvrxs1P5YjErlMNN4Yh4TM/0tAyOMBeAr2+WRQElWW2ZaJHtrRzt7VnW5mj5v9nfHn5T/T3IevtV8Sbsz55BjJ5Z32zsrC+9FgD2JFqbHbO+lVUAtG0GQOXhrE/vIADyBQC03pzzHoZsXpLE4gwnC4vs7GxzAZ9rLivoN/ufgm/Kv4Y595nL7vtWO6YXP4EjSRUzZUXlpqemS0TMzAwOl89k/fcQ/+PAOWnNycMsnJ/AF/GF6FVR6JQJhIlou4U8gViQLmQKhH/V4X8YNicHGX6daxRodV8AfYU5ULhJB8hvPQBDIwMkbj96An3rWxAxCsi+vGitka9zjzJ6/uf6Hwtcim7hTEEiU+b2DI9kciWiLBmj34RswQISkAd0oAo0gS4wAixgDRyAM3AD3iAAhIBIEAOWAy5IAmlABLJBPtgACkEx2AF2g2pwANSBetAEToI2cAZcBFfADXALDIBHQAqGwUswAd6BaQiC8BAVokGqkBakD5lC1hAbWgh5Q0FQOBQDxUOJkBCS...","sessionId":"f2f2a44a-0f8b-4495-9e1e-1fa44bece032"}[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/f2f2a44a-0f8b-4495-9e1e-1fa44bece032/touch/perform[39m [90m{"sessionId":"f2f2a44a-0f8b-4495-9e1e-1fa44bece032","actions":[{"action":"tap","options":{"y":546,"x":46.5,"count":1}},{"action":"release","options":{}}]}[39m
[36minfo[39m: [debug] Pushing command to appium work queue: "target.touch([{\"touch\":[{\"x\":46.5,\"y\":546}],\"time\":0.2}])"
[36minfo[39m: [debug] Sending command to instruments: target.touch([{"touch":[{"x":46.5,"y":546}],"time":0.2}])
[36minfo[39m: [debug] [32m[INST] 2015-02-11 05:46:14 +0000 Debug: Got new command 92 from instruments: target.touch([{"touch":[{"x":46.5,"y":546}],"time":0.2}])[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-11 05:46:14 +0000 Debug: evaluating target.touch([{"touch":[{"x":46.5,"y":546}],"time":0.2}])[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-11 05:46:14 +0000 Debug: target.touch(__NSCFArray)[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-11 05:46:15 +0000 Debug: evaluation finished[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-11 05:46:15 +0000 Debug: responding with:[39m
[36minfo[39m: [debug] [32m[INST] 2015-02-11 05:46:15 +0000 Debug: Running system command #93: /usr/local/Cellar/node/0.10.33/bin/node /Users/wipro/Documents/appium_version_1.3.4/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...

**Comment by naveenjammula** [comment]
and i also observed that In appium inspector  there are two options : tap and precise tap, If i do tap its working fine, but when i do precise tap with duration as 0 its performing long tap, could you please let me know the difference between those two options.

**Comment by naveenjammula** [comment]
Posting the tap action  from the logs :

Pushing command to appium work queue: "target.touch([{\"touch\":[{\"x\":46.5,\"y\":546}],\"time\":0.2}])"

From this line you can observe the duration as 0.2 sec.

**Comment by imurchie** [comment]
`Tap` seems to produce a `click`:

```shell
info: --> POST /wd/hub/session/9e23ea19-7600-4370-9757-8beb08a4e360/element/0/click {}
info: [debug] Pushing command to appium work queue: "au.tapById('0')"
info: [debug] Sending command to instruments: au.tapById('0')
info: [debug] [INST] 2015-02-11 17:02:07 +0000 Debug: Got new command 8 from instruments: au.tapById('0')
info: [debug] [INST] 2015-02-11 17:02:07 +0000 Debug: evaluating au.tapById('0')
info: [debug] [INST] 2015-02-11 17:02:07 +0000 Debug: UIATextField.tap()
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"9e23ea19-7600-4370-9757-8beb08a4e360"}
info: <-- POST /wd/hub/session/9e23ea19-7600-4370-9757-8beb08a4e360/element/0/click 200 267.200 ms - 74 {"status":0,"value":"","sessionId":"9e23ea19-7600-4370-9757-8beb08a4e360"}
```

This, on my app, fires a `Tap` gesture event.

While `Precise Tap` appears to produce a `mobile: tap` action:

```shell
info: --> POST /wd/hub/session/9e23ea19-7600-4370-9757-8beb08a4e360/execute {"script":"mobile: tap","args":[{"y":65,"touchCount":1,"x":147,"tapCount":1,"duration":0.5}]}

info: [debug] Pushing command to appium work queue: "au.complexTap({\"tapCount\":1,\"touchCount\":1,\"duration\":0.5,\"x\":147,\"y\":65})"
info: [debug] Sending command to instruments: au.complexTap({"tapCount":1,"touchCount":1,"duration":0.5,"x":147,"y":65})
info: [debug] [INST] 2015-02-11 17:04:41 +0000 Debug: Got new command 13 from instruments: au.complexTap({"tapCount":1,"touchCount":1,"duration":0.5,"x":147,"y":65})
info: [debug] [INST] 2015-02-11 17:04:41 +0000 Debug: evaluating au.complexTap({"tapCount":1,"touchCount":1,"duration":0.5,"x":147,"y":65})
info: [debug] [INST] 2015-02-11 17:04:41 +0000 Debug: target.tapWithOptions({x:"147", y:"65"}, {touchCount:"1", tapCount:"1", duration:"0.5"})
info: [debug] [INST] 2015-02-11 17:04:41 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-02-11 17:04:41 +0000 Debug: responding with:
info: [debug] [INST] 2015-02-11 17:04:41 +0000 Debug: Running system command #14: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"9e23ea19-7600-4370-9757-8beb08a4e360"}
info: <-- POST /wd/hub/session/9e23ea19-7600-4370-9757-8beb08a4e360/execute 200 1102.634 ms - 74 {"status":0,"value":"","sessionId":"9e23ea19-7600-4370-9757-8beb08a4e360"}
```

This produces, in my app, a `LongPress` event.

**Comment by naveenjammula** [comment]
We are using appium python client for running our test case We are calling tap function (def tap(self, positions, duration=None)) When we call this function for android devices its performing tap but when i call the same function for IOS devices its performing long tap instead of tap.

**Comment by naveenjammula** [comment]
can you please update on this issue ??

**Comment by imurchie** [comment]
I uploaded a new version of the client (0.14) which ought to fix this. Let me know if it does not.
