### ISSUE TITLE
When I only send one chinese characters,nothing input

### ISSUE THREAD

**Issue by sanlengjingvv** [appium/appium#4128]
Appium 1.2.4
Android 4.4
unicodeKeyboard = true

Nothing input into EditText when I use:
```
driver.findElement(By.id("")).sendKeys("中");
```
It works when send two characters:
```
driver.findElement(By.id("")).sendKeys("中文");
```

**Comment by 0x1mason** [comment]
Have you tried this with newer appium versions?

**Comment by sanlengjingvv** [comment]
I tried Appium 1.3.7，It works.
