### ISSUE TITLE
Add capability to turn on recursing into webview elements in native contexts for iOS

### ISSUE THREAD

**Issue by danail-branekov** [appium/appium#4153]
Hi,

It seems that WebElement.clear() does not work for web elements located inside a web view. The method works perfectly fine for elements which are part of the native context. 
Steps to reproduce
1. Start Appium on the WebViewApp (https://github.com/appium/sample-code/tree/master/sample-code/apps/WebViewApp)
2. Execute the following test:

``` java
    @Test
    public void test() throws InterruptedException {
        final WebElement navigationBarElement = driver.findElement(By.name("Enter URL"));
        navigationBarElement.clear();
        navigationBarElement.sendKeys("https://mail.google.com");

        final WebElement goToURLButton = driver.findElement(By.xpath("//UIATextField[@name='Enter URL']/following-sibling::UIAButton[1]"));
        goToURLButton.click();
        Thread.sleep(3000);

        locateMailTextField().click();
        locateMailTextField().sendKeys("mymail@example.com");
        assertEquals("mymail@example.com", locateMailTextField().getText());
        locateMailTextField().clear();
        assertEquals("", locateMailTextField().getText());

    }

    private WebElement locateMailTextField() {
        return driver.findElement(By.xpath("//UIAStaticText[@name='One account. All of Google.']/following-sibling::UIATextField[1]"));
    }
```

The last assertion would fail because the email text field is not cleared.

Using Appium 1.3.0 on OSX 10.10.1 with iPhone 6 simulator, iOS SDK 8.1

**Comment by talarari** [comment]
any update on this? 
we have an app that is part native part webview based.

in android we're experiencing trouble with switching back and forth between native and web context.
since we don't have many webviews, we're interacting with everything based on accessibility id in native context. this works quite well on android.

we'd like to write the same tests for ios and android.

is this currently possible somehow?

**Comment by jlipps** [comment]
We won't implement this since UIAutomation has been removed from iOS

**Comment by erajanraja24** [comment]
If you haven't installed the ios webkit install that first. 

Even if web page is not interacting then use the command "brew reinstall --HEAD ios-webkit-debug-proxy" to reinstall it again properly. This worked for me.

Note: In case of conflict, that will give some comment to remove the conflict. Copy and execute the same
