### ISSUE TITLE
crashes are not seen in the adb logs captured by get_log("logcat") sometimes

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#4154]
i have got the application crash and i captured the logs though get_log("logcat") but when i checked the logs i see there are no crashes.Is the adb logs are not captured properly by using get_log("logcat").

**Comment by naveenjammula** [comment]
Can you please update the fix on this issue ??

**Comment by naveenjammula** [comment]
Can you please update the fix on this issue ??

**Comment by jlipps** [comment]
Still haven't found a way to repro this with our own apps, but we'll add it to the list.

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
