### ISSUE TITLE
touchAction.Tap(element).perform() gives unknow command error

### ISSUE THREAD

**Issue by agnoerskov** [appium/appium#4157]
Hi

I have an android application where all the code is HTML and javascript hosted in a webview.
 
I am writing the test in C# using the appium-dotnet-driver v. 1.2.0.5 and the Appium 1.3.1 server. My test is running on a real Android device.

I am doing a simple test case where I want to mimic the user pushing a button. I looked through your documentation to try to figure out how to do it(http://appium.io/slate/en/master/?csharp#running-your-test-app-with-appium-(android-devices-<-4.2,-and-hybrid-tests)).

But when I use the touchaction I get an "unknow command .. touch/perform" error.

Should I be doing this in another way?

Test code:

var test = driver.FindElementsByClassName("elementClass");
var element = test[0];
var elementLocation = element.Location;           
var action = new TouchAction(driver);
action.Tap(elementLocation.X, elementLocation.Y).Perform();

Log:

info: --> GET /wd/hub/session/97c43717aeffcd6df0ca5bbad745739b/element/0.11985369073227048-2/location {}
info: [debug] Proxying command to 127.0.0.1:9515
info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/97c43717aeffcd6df0ca5bbad745739b/element/0.11985369073227048-2/location","method":"GET"}
info: [debug] Proxied response received with status 200: "{\"sessionId\":\"97c43717aeffcd6df0ca5bbad745739b\",\"status\":0,\"value\":{\"toString\":{},\"x\":160,\"y\":150.65625}}"
info: <-- GET /wd/hub/session/97c43717aeffcd6df0ca5bbad745739b/element/0.11985369073227048-2/location 200 34.070 ms - 105
info: --> POST /wd/hub/session/97c43717aeffcd6df0ca5bbad745739b/touch/perform {"actions":[{"action":"tap","options":{"x":160,"y":151}}]}
info: [debug] Proxying command to 127.0.0.1:9515
info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/97c43717aeffcd6df0ca5bbad745739b/touch/perform","method":"POST","json":{"actions":[{"action":"tap","options":{"x":160,"y":151}}]}}
info: [debug] Proxied response received with status 404: "unknown command: session/97c43717aeffcd6df0ca5bbad745739b/touch/perform"
info: <-- POST /wd/hub/session/97c43717aeffcd6df0ca5bbad745739b/touch/perform 404 11.818 ms - 71
info: --> DELETE /wd/hub/session/97c43717aeffcd6df0ca5bbad745739b {}

**Comment by andry-tino** [comment]
Having the same problem. Same exact problem.

**Comment by paymand** [comment]
I don't think Appium's ``TouchAction`` works in webview context. You need to use Selenium webdriver's ``TouchActions``. However, that doesn't work either at the moment, see https://github.com/appium/appium/pull/4005.

You have to options:
1. Use the Selendroid backend + webdriver's ``TouchActions``.
2. Determine the coordinates where you want to perform your touch gesture, switch to native context and use appium's ``TouchAction`` as you did.

**Comment by 0x1mason** [comment]
Paymand summed it up.
