### ISSUE TITLE
error: Could not pre-launch appium: Error: Instruments crashed on startup

### ISSUE THREAD

**Issue by igalep** [appium/appium#4158]
Running on real 6+ device ...

The log I'm getting

info: Launching instruments

info: [debug] Attempting to run app on real device with UDID 2*********************************************6

info: [debug] Spawning instruments with command: /Applications/Xcode-Beta.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode-Beta.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 2*********************************************6 com.citigroup.cvm -e UIASCRIPT "/Users/ie54553/Library/Application Support/appium/bootstrap/bootstrap-60f23230385b0cfa.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2014-11-24 17:45:12.335 instruments[2606:19255] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [debug] [INST STDERR] 2014-11-24 17:45:13.051 instruments[2606:19234] Automation Instrument ran into an exception while trying to run the script. UIAScriptAgentSignaledException

info: [debug] [INST] 2014-11-24 15:45:13 +0000 Fail: An error occurred while trying to run the script.

info: [debug] [INST] Instruments Trace Complete (Duration : 1.194740s; Output : /tmp/appium-instruments/instrumentscli0.trace)

info: [debug] [INSTSERVER] Instruments exited with code 0

error: Could not pre-launch appium: Error: Instruments crashed on startup

info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Cleaning up appium session

Any ideas ?

**Comment by imurchie** [comment]
Any progress on this?
