### ISSUE TITLE
Add capability to define port on which avd is started

### ISSUE THREAD

**Issue by finspin** [appium/appium#4171]
It would be nice to have an additional capability which would define on which port an emulator is started. Something like:

```
desired_caps['avd'] = 'Nexus_5'
desired_caps['avd-port'] = '5546'
```

or maybe avd could take a list:

```
desired_caps['avd'] = 'Nexus_5', '5546'
```

This would simplify running tests on multiple emulators. Currently we need to use custom solution for launching several emulators because we need to pass emulator's uuid in the desired capabilities which is in form of 'emulator-port' (e.g. emulator-5546').

**Comment by imurchie** [comment]
This exists as `adbPort`.
