### ISSUE TITLE
Not able to swipe in WebView in Android Devices

### ISSUE THREAD

**Issue by dhiren2013** [appium/appium#4182]
Appium Version : 1.3.3
Platform: MAC
Android Device : 4.0+

I am testing a scenario where my page opens in webview where I have to swipe from right to left. But after the page opens in webview I am not able to swipe and I am getting exception

appium server logs

Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/53107599-7470-d255-0c4b-a4edae38cb09/touch/perform","method":"POST","json":{"actions":[{"action":"press","options":{"element":":wdc:1417057375502"}},{"action":"moveTo","options":{"element":":wdc:1417057375503"}},{"action":"release","options":{}}]}}
info: [debug] Proxied response received with status 404: undefined
info: <-- POST /wd/hub/session/53107599-7470-d255-0c4b-a4edae38cb09/touch/perform 404 8.167 ms - -

Here is my code where I am trying to swipe
WebElement slider = driver.findElement(By.id("Element_6df0360d")); // finds element where slider is their
WebElement div = slider.findElement(By.tagName("img")); //find element of the center till where i have to slide

TouchAction slide = new TouchAction(driver);   // java-client 2.1.0
//slide.longPress(slider).moveTo(div).release();
slide.press(slider).moveTo(div).release();
slide.perform();

Test exception logs

org.openqa.selenium.UnsupportedCommandException: Build info: version: '2.44.0', revision: '76d78cf323ce037c5f92db6c1bba601c2ac43ad8', time: '2014-10-23 13:11:40'

**Comment by 0x1mason** [comment]
Unfortunately Webview doesn't support touch actions.

**Comment by ikermart** [comment]
@0x1mason  any prevission to support, swipe action in a webview?

**Comment by 0x1mason** [comment]
We'd like to but we're limited by the component (chromedriver) that we use
for webview automation.

**Comment by bchand1748** [comment]
What would be the work around ?

**Comment by 0x1mason** [comment]
You have 2 options:

   1. You can use any method available in ChromeDriver. That doesn't
   include gestures, but it does include clicking, moving the mouse, etc, so
   you can emulate touch actions.
   2. If you have absolute coordinates for the actions you want to perform,
   you can scope out to NATIVE_APP context and perform touch actions there.


On Thu, Mar 19, 2015 at 4:10 PM, bchand1748 <notifications@github.com>
wrote:

> What would be the work around ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/4182#issuecomment-83744032>.
>



-- 

*Eric Millin*
*Software Engineer, Ecosystems*
Twitter: @etmillin <http://twitter.com/jlipps>
GitHub: @0x1mason <https://github.com/jlipps>
Sauce Labs <http://saucelabs.com/> | Sauce blog <http://sauceio.com/>
