### ISSUE TITLE
Issue in TouchAction Class. the Step list need to be clean up in a flexibility way.

### ISSUE THREAD

**Issue by EthanJiang** [appium/appium#4197]
While I test with the TouchAction class, got the issue. 
the Step list need to be clean up in a flexibility way.
Test example:

ITouchAction touch = new TouchAction(driver);
IWebElement element1= driver.FindElementByXPath("//android.widget.Button[@text='Discover']");
            touch.Tap(element1).Perform();

IWebElement element2= driver.FindElementById("discovery_button");
            touch.Tap(element2).Perform();

In my case, the Tap action on element2 will fail. the error prompt can't find the element. 
but If I set the touch with a new TouchAction, (touch = new TouchAction(driver);) the test will pass. 

There is a Cancel method to clean up the Steps list but it also clean the driver. So eventhough I call the Cancel Method, I also have to new the TouchAction to setup the driver. So I can't reuse the old one. 

the Solution:
1. automatically Clean up the Steps list after a perform action.
2. open a method to user to manually clean up step list. but keep the driver for reuse.

another:
the name of "Cancel" method should be set a good name. its purpose is not to cancel the action, is to clean up the driver and setup list.

**Comment by 0x1mason** [comment]
Please post this on the github site for the appium C# repo. Thanks :)
