### ISSUE TITLE
Unable to set the platform version to 7.1 -appium 1.3.2. and 1.3.3 and defaults to ios SDK Version 8.1

### ISSUE THREAD

**Issue by khyatid** [appium/appium#4202]
I'm using xcode 6.1 , appium 1.3.3 ,  built my app with iphone 5 s ios 7.1 simulator and set the app path  and set the platform version to 7.1  and device to iphone 5 s in appium ios settings .
On clicking launch it identifies  ios sdk 8.1 and launches the app in 8.1 simulator and not 7.1 … can some one please tell me how can I get appium to identify  and set Platform version 7.1 or is it a bug ?

**Comment by moizjv** [comment]
@khyatid can you use the work around suggested by @imurchie . Opened issue in .app repo
