### ISSUE TITLE
use DeDupe when packaging node modules

### ISSUE THREAD

**Issue by Astro03** [appium/appium#4203]
https://www.npmjs.org/doc/cli/npm-dedupe.html

the node modules path's folder depth gets extremely long and sometimes surpasses the windows file length limit of 255. If we use dedupe, this should no longer happened.

This happened in a previous version of appium (don't recall which and the appium-dot-exe had to skip that version since it could not package it properly).

Thanks,
ASTRO

**Comment by jlipps** [comment]
npm v3's flatter tree solves this issue.
