### ISSUE TITLE
Rebuilt Selendroid should be ignored on Selendriod upgrades

### ISSUE THREAD

**Issue by paymand** [appium/appium#4215]
I just upgraded to 1.3.4 and I'm getting an error running tests with Selendroid:
`
2014-12-03 14:14:53:605 - error: Selendroid create session did not work. Status was 301 and body was [object Object]
`
301 is what Selendroid 0.11.0 used to send, 0.12.0 should send 200...the error is like we still have the old Selendroid.

After debugging a bit, the issue was because a previously rebuilt Selendroid already existed in /tmp and we did not bother to build a new apk with the new version of Selendroid.

A good fix for this is to include the Selendoid version in temp file path.

**Comment by jlipps** [comment]
yeah, this should be as easy as naming the file selendroid-server-0.13.apk or whatever
