### ISSUE TITLE
Crash report not found on the appium logs whereas it can be captured from syslog

### ISSUE THREAD

**Issue by anupa13** [appium/appium#4222]
I am Testing on iPhone (IOS-7.1.2) with the appium version 1.3.4-beta1. I am running some test on it and i got a crash in the middle and i am using libimobiledevice to capture a sys logs. I can see the crash report in the sys logs but its not captured in the appium logs is there any work around for it.

**Comment by naveenjammula** [comment]
Can you please update the fix on this issue ??

**Comment by moizjv** [comment]
@sebv any ideas?

**Comment by sebv** [comment]
From iOS 8 the system logs will for sure be in the Appium log if the option is enable. 

For iOS7 and below the way we locate system logs is no really good (https://github.com/appium/appium/blob/master/lib/devices/ios/ios-log.js#L90), so they might be missing. Specially the first time you start the emulator, it is missing.

**Comment by sebv** [comment]
Closing, may be reopened if needed.
