### ISSUE TITLE
modifying android.settings from appium 

### ISSUE THREAD

**Issue by yahman72** [appium/appium#4223]
is there a possiblity to start an application/activity by defining only the activity?

To be more precise, with adb it's possible to open different settings (http://developer.android.com/reference/android/provider/Settings.html) pages by e.g. 
<pre>
adb shell am start -a android.settings.SETTINGS
adb shell am start -a android.settings.WIRELESS_SETTINGS
</pre>

I'd need this to change some settings before a test case/test suite but I haven't found a way of doing this with appium, is this possible?

Another way of doing this would be the "usual" way i.e. run the settings as any other application. If we look at behind the scenes (`adb shell dumpsys activity`) of that `adb shell am start -a android.settings.WIRELESS_SETTINGS` we'll see that :
<pre>
    TaskRecord{42496c88 #43 A com.android.settings U 0}
    Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.settings/.Settings$WirelessSettingsActivity }
      Hist #6: ActivityRecord{41f97ba8 u0 com.android.settings/.Settings$WirelessSettingsActivity}
        Intent { act=android.settings.WIRELESS_SETTINGS flg=0x10400000 cmp=com.android.settings/.Settings$WirelessSettingsActivity }
        ProcessRecord{41fa0330 29363:com.android.settings/1000}
      Hist #5: ActivityRecord{41cc8d58 u0 com.android.settings/.Settings$WirelessSettingsActivity}
        Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.settings/.Settings$WirelessSettingsActivity }
        ProcessRecord{41fa0330 29363:com.android.settings/1000}
</pre>

I.e. running `com.android.settings` with `app_activity=.Settings$WirelessSettingsActivity` should work, but it doesn't = the settings page is not displayed.
This is most likely because appium is not escaping the `$` character. 
Another try with `app_activity=.Settings\$WirelessSettingsActivity` is a bit better = the settings page is displayed, but fails in the next step because appium does not realise that the settings page is already open.
This is most likely because appium compares "com.android.settings/.Settings\$WirelessSettingsActivity" with "com.android.settings/.Settings$WirelessSettingsActivity". See logs below.

<pre>
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.android.settings/.Settings\$WirelessSettingsActivity"
info: [debug] Waiting for pkg "com.android.settings" and activity ".Settings\$WirelessSettingsActivity" to be focused
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
info: [debug] Getting focused package and activity
info: [debug] executing: "C:\java\adt\bundle-20140702\sdk\platform-tools\adb.exe" -s 3cdfbd8ffa9e shell "dumpsys window windows"
error: com.android.settings/.Settings\$WirelessSettingsActivity never started. Current: com.android.settings/.Settings$WirelessSettingsActivity
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 21.808
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] UiAutomator shut down normally
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: com.android.settings/.Settings\$WirelessSettingsActivity never started. Current: com.android.settings/.Settings$WirelessSettingsActivity
info: [debug] Error: com.android.settings/.Settings\$WirelessSettingsActivity never started. Current: com.android.settings/.Settings$WirelessSettingsActivity
    at null.<anonymous> (C:\java\appium\appium1.2.4.1\node_modules\appium\node_modules\appium-adb\lib\adb.js:1317:12)
    at null.<anonymous> (C:\java\appium\appium1.2.4.1\node_modules\appium\node_modules\appium-adb\lib\adb.js:1259:7)
    at null.<anonymous> (C:\java\appium\appium1.2.4.1\node_modules\appium\node_modules\appium-adb\lib\adb.js:172:9)
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: com.android.settings/.Settings\\$WirelessSettingsActivity never started. Current: com.android.settings/.Settings$WirelessSettingsActivity)","origValue":"com.android.settings/.Settings\\$WirelessSettingsActivity never started. Current: com.android.settings/.Settings$WirelessSettingsActivity"},"sessionId":null}
info: <-- POST /wd/hub/session 500 25588.347 ms - 396
</pre>

**Comment by jlipps** [comment]
I believe this should be fixed with the move to using `teen_process`. Feel free to reopen if you still see this behavior in the Appium 1.5 beta
