### ISSUE TITLE
Failed to Dump Window Hierarchy

### ISSUE THREAD

**Issue by aluedeke** [appium/appium#4227]
am currently experiencing a lot of "Failed to Dump Window Hierarchy" Errors.

Example Request Response:

REQUEST
{"using":"xpath","value":"//*[@text='AppLock is running']"}
RESPONSE
{"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Failed to Dump Window Hierarchy"},"sessionId":"68ee59cb-e1c0-42d3-b1c7-12081e877fbb"}

The issue seems to be a temporary one as the test afterwards continues properly (e.g. i am always dumping the page source and a screenshot after a failure)

Any ideas why this happens?

Appium Version is 1.3.4

**Comment by 0x1mason** [comment]
#4252 merged.
