### ISSUE TITLE
The Appium 1.2.4.1 server crashes in Windows 8.1 when attempted to start

### ISSUE THREAD

**Issue by abhiju20** [appium/appium#4232]
I have been trying to start my Appium server through the binary ( .exe) in my Windows 8.1 PC.  Unfortunately, after I mention my .apk name in the settings and start the server, it crashed immediately with a message ' Appium has stopped working'.

Update : I realised that even If do not chnage any settings and continue with my default configuration, it still keeps crashing.

**Comment by moizjv** [comment]
@abhiju20 looks like [appium-dot-exe](https://github.com/appium/appium-dot-exe/issues) issue. Raised [issue](https://github.com/appium/appium-dot-exe/issues/145) in that repo
