### ISSUE TITLE
No .git/hooks/pre-commit  when ./reset.sh --ios --dev

### ISSUE THREAD

**Issue by lichuanjun** [appium/appium#4233]
When I Compiling the iOS sample app followed by Tutorial:http://appium.io/slate/en/tutorial/ios.html?java#native-ios-automation.It says"/Users/lcj/Desktop/Github/appiumV1.3.4/.git/hooks/pre-commit: No such file or directory",what should I do to fix it?thanks.
BTW,how to fix the following warning:
[* Installing new or updated NPM modules (including devDeps)
npm WARN package.json md5calculator@0.0.3 No repository field.
npm WARN package.json node-idevice@0.1.2 No repository field.
npm WARN package.json path@0.4.9 path is also the name of a node core module.
npm WARN package.json utf7@1.0.0 No repository field.
npm WARN package.json vargs@0.1.0 No repository field.
npm WARN package.json assert@1.1.2 assert is also the name of a node core module]

**Comment by moizjv** [comment]
Closing as there is no response. Reopen if still an issue.
