### ISSUE TITLE
 android.util.AndroidException: INSTRUMENTATION_FAILED error in Appium running with eclipse on windows 7

### ISSUE THREAD

**Issue by cseabhi** [appium/appium#4234]
HI,
 I am getting this error. Struggled a lot but couldn't found any solution for this.

adb.exe" -s TA93300RY0 shell "am instrument -e main_activity 'com.example.androidtest.SplashActivity' com.example.androidtest.selendroid/io.selendroid.ServerInstrumentation"
> error: android.util.AndroidException: INSTRUMENTATION_FAILED: com.example.androidtest.selendroid/io.selendroid.ServerInstrumentation
> 
> 	at com.android.commands.am.Am.runInstrument(Am.java:865)
> 
> 	at com.android.commands.am.Am.onRun(Am.java:282)
> 
> 	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
> 
> 	at com.android.commands.am.Am.main(Am.java:76)
> 
> 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
> 
> 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:243)
> 
> 	at dalvik.system.NativeStart.main(Native Method)
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: android.util.AndroidException: INSTRUMENTATION_FAILED: com.example.androidtest.selendroid/io.selendroid.ServerInstrumentation
> 
> info: [debug] Error: android.util.AndroidException: INSTRUMENTATION_FAILED: com.example.androidtest.selendroid/io.selendroid.ServerInstrumentation
> 
>     at E:\Softwares\Appium\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:1397:17
>     at null.<anonymous> (E:\Softwares\Appium\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:172:9)
>     at ChildProcess.exithandler (child_process.js:635:7)
>     at ChildProcess.EventEmitter.emit (events.js:98:17)
>     at maybeClose (child_process.js:743:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: android.util.AndroidException: INSTRUMENTATION_FAILED: com.example.androidtest.selendroid/io.selendroid.ServerInstrumentation\r\r)","origValue":"android.util.AndroidException: INSTRUMENTATION_FAILED: com.example.androidtest.selendroid/io.selendroid.ServerInstrumentation\r\r"},"sessionId":null}
> info: [37m<-- POST /wd/hub/session [39m[31m500[39m[90m 65119.699 ms - 380[39m [90m[39m

**Comment by chethangowda** [comment]
HI, any one got the solution for this.?

**Comment by imurchie** [comment]
Can you open a new issue with the details of your issue, rather than commenting on a closed two year old one? We can proceed from there.
