### ISSUE TITLE
Be able to set newCommandTimeout dynamically for single test in a run

### ISSUE THREAD

**Issue by concertman** [appium/appium#4248]
Scenario:
Multiple tests running via Cucumber with one test that takes longer than the newCommandTimeout is set to.

It would be great to be able to set newCommandTimeout temporarily for a single test or for certain flagged tests that are known to take a long time (i.e. scrolling through a very long UIAPickerWheel)

**Comment by jlipps** [comment]
now that newCommandTimeout is a capability, this should be easy to manage on a per-session basis!
