### ISSUE TITLE
Log warning instead of erroring when someone tries to use page load timeout (since it does nothing)

### ISSUE THREAD

**Issue by swappatel** [appium/appium#4262]
Have started receiving this error - not sure, where to look for it. Any idea what's going wrong?

Using wd-bridge, tests in protractor, capabilities = {
        browserName: 'safari',
        'appium-version': '1.3',
        platformName: 'iOS',
        platformVersion: '8.0',
        deviceName: 'iPhone Simulator'
    },

Have been working so far, until I uninstalled and re-installed appium package via npm. 

info: [debug] Responding to client with error: {"status":9,"value":{"message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource. (Original error: Invalid timeout 'page load')","origValue":"Invalid timeout 'page load'"},"sessionId":"0aed66b2-45bf-4179-9be1-ab9704391a05"}
info: <-- POST /wd/hub/session/0aed66b2-45bf-4179-9be1-ab9704391a05/timeouts 500 2.559 ms - 309

**Comment by 0x1mason** [comment]
Are you still experiencing this?  Someone is trying to set a "page load" timeout, which isn't supported in Appium.  Remove that and you should be good.  Let me know if this doesn't resolve your issue.

**Comment by jlipps** [comment]
we could also add a page load timeout to appium (i.e., treat this as a feature request); i think it's something selenium supports so we'd want to support it in our ios hybrid modality as well.

**Comment by 0x1mason** [comment]
Ok.

**Comment by truebit** [comment]
### Now using appium 1.5.2 and java-client with page load method:
```java
driver.manage().timeouts().pageLoadTimeout(timeOutDuration.getTime(), timeOutDuration.getTimeUnit());
```
### iOS would not throw exception, log as follows:

> [MJSONWP] Calling AppiumDriver.timeouts() with args: ["page load",5000,"f24986e6-9469-4163-9246-c7c434f2e455"]
> [debug] [iOS] Executing iOS command 'timeouts'
> [debug] [iOS] Set page load timeout to 5000ms
> [MJSONWP] Responding to client with driver.timeouts() result: null

### Android would throw exception as below:

> [HTTP] --> POST /wd/hub/session/3187860d-0936-4bb0-928b-0a9701d97a44/timeouts {"type":"page load","ms":5000}
> [MJSONWP] Calling AppiumDriver.timeouts() with args: ["page load",5000,"3187860d-0936-4bb0-928b-0a9701d97a44"]
> [MJSONWP] Encountered internal error running command: Error: Invalid timeout 'page load'
>     at AndroidDriver.callee$0$0$ (lib/commands/timeout.js:19:13)
>     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
>     at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
>     at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.export.js:30:36)
>     at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
>     at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
>     at AndroidDriver.callee$0$0 [as timeouts] (lib/commands/timeout.js:10:9)
>     at lib/driver.js:163:24
>     at tryCatcher (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/util.js:26:23)
>     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:507:31)
>     at Promise._settlePromiseAt (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:581:18)
>     at Promise._settlePromiseAtPostResolution (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/promise.js:245:10)
>     at Async._drainQueue (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:128:12)
>     at Async._drainQueues (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:133:10)
>     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/async.js:15:14)
>     at tryOnImmediate (timers.js:543:15)
>     at processImmediate [as _immediateCallback] (timers.js:523:5)

**Comment by imurchie** [comment]
Appium does not support `page load` timeout for Android. There is no functionality that it covers.

**Comment by mykola-mokhnach** [comment]
I second @imurchie that the current behaviour is the expected one. There should be a way to let the client know about his setting is not going to work.
