### ISSUE TITLE
sendKeys without clearing field (/appending to existing text)

### ISSUE THREAD

**Issue by hughstephens** [appium/appium#4263]
Hi all

Been trying to grapple with this one for a while now. Is there some way to sendKeys to a field *without* clearing it first? I.e. appending it to something existing?

It's a convoluted use case I'm sure but I would be surprised if it's impossible (?). The problem I'm experiencing is that I run a custom version of the unicode keyboard (closer to the original utf7ime than the Appium one, which kept being unable to send carriage breaks), and it seems to bork itself, at least with one particular text field, if it is used to put in >~500 keys at once. I want to do something like:

driver.findElement(By.id("com.myapp.android:id/caption_text_view")).sendKeys(string1);
driver.findElement(By.id("com.myapp.android:id/caption_text_view")).sendKeys(string2);

But obviously currently the second line will clear the edittext and then type string2. I get the same crashing behaviour with using string1+string2, string1+""+string2 and a few other similar attempts, including adding Keys.ARROW_RIGHT or Keys.END which seem to instead pop up the spellchecker -_-

Is there an easy way to do it? Or am I going to need to write a custom method into a fork, like sendKeysWithoutClear(str)? Is there something obvious that I'm missing?

Cheers!

**Comment by jlipps** [comment]
closing, no response
