### ISSUE TITLE
Test with device which is 2nd in the adb devices list

### ISSUE THREAD

**Issue by serefbulbul** [appium/appium#4265]
Hello everyone,

I am using Appium with Genymotion and Genymotion virtual devices act like real device according to Appium capabilities. When 2 virtual devices are opened at the same time, Appium directs test to the first device at the adb devices list all the time.

I am writing "deviceName", "U", capabilities and I am also specifying different bootstrap ports. In fact, I tried really much combination of them;

I just opened a Appium server and changed capabilities from code(Java) side to direct another device,

I opened 2 Appium servers with different ports, bootstrap ports, and -U parameters to direct another device which is not the first device in the adb devices list.

I used Selenium grid and defined different Appium nodes in the same Mac.

Unfortunately, they are all failed but there should be a way to test different devices when they are both plugged. I will be really glad if you can help me.

Btw I tried these combinations with Appium 1.3.3, 1.3.1 and 1.2.2 versions. I use Mac OS X 10.10.1.

Thanks for reading.

**Comment by sebv** [comment]
Please use appium discuss for this kind of issues: https://discuss.appium.io/
