### ISSUE TITLE
Verify and test send keycodes for android  

### ISSUE THREAD

**Issue by iceicerickert** [appium/appium#4267]
I am looking for a way to tap the search-key on a soft-keyboard. The proper way to do this is by using keycode 84. But this one does not work (others do).
Is there a good work around or do I have to manually tap on a coordinate? Or can I calculate that coordinate maybe?

**Comment by moizjv** [comment]
@iceicerickert can you try `IME_ACTION_SEARCH` value 3. I am not sure if this is appium bug. Can you provide more information as logs so we can fix issue if any.

**Comment by imurchie** [comment]
This seems to be an issue with the emulator. Doing it manually (i.e., `adb shell input keyevent 84`) doesn't work either.

**Comment by moizjv** [comment]
tracking #4815 #4504

**Comment by jlipps** [comment]
If it doesn't work through `adb` it's not something we can fix and should be reported to Google.
