### ISSUE TITLE
Appium 1.3.3 / Android swipe/moveTo/touch events / Node.js

### ISSUE THREAD

**Issue by peteweb** [appium/appium#4268]
Hello everyone,

I've been hitting a repeated problem with implementing touchActions for a set of Android tests that need to look for visible elements in a scrollview, then move down to the next set of elements (or just swipe down 'x' given number of points). 

I've made use of the wd.TouchAction method as follows:

```javascript
// code within helper lib, based almost entirely on action helper - q and wd included at top

exports.swipeNew = function (driver, opts) {
  var action = new wd.TouchAction();
  action
    .press({x: opts.startX, y: opts.startY})
    .wait(opts.duration)
    .moveTo({x: opts.endX, y: opts.endY})
    .release();
  return driver.performTouchAction(action);
};
```

```javascript
// code from within test (currently written purely to visually prove it moves / works):

return self.actionsHelper.swipeNew(self.browser, [{startX: 200, startY: 400, endX: 200, endY: 150, duration: 1}]);
```

When I watch the test run, I see the app 'hang' at this point, performing no touch / swipe action. The Appium logs output the following:

```
info: --> POST /wd/hub/session/6cec9f7f-d12a-4219-b062-3a1dbbb7b67f/touch/perform [{"action":"press","options":{}},{"action":"wait","options":{}},{"action":"moveTo","options":{}},{"action":"release","options":{}}]
info: [debug] Pushing command to appium work queue: ["swipe",{"startX":0.5,"startY":0.5,"endX":0.5,"endY":0.5,"steps":22}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"swipe","params":{"startX":0.5,"startY":0.5,"endX":0.5,"endY":0.5,"steps":22}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: swipe
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][480,800]
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][480,800]
info: [debug] [BOOTSTRAP] [debug] Swiping from [x=240.0, y=400.0] to [x=240.0, y=400.0] with steps: 22

info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"The swipe did not complete successfully"},"sessionId":"6cec9f7f-d12a-4219-b062-3a1dbbb7b67f"}
info: <-- POST /wd/hub/session/6cec9f7f-d12a-4219-b062-3a1dbbb7b67f/touch/perform 500 1437.145 ms - 208 
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"The swipe did not complete successfully","status":13}
```

Having also tried to implement the same kind of logic with moveTo(element) and execute('mobile: swipe', opts) - I'm getting a bit stuck as to where I should turn to next.

Looking at the tests within the Appium repo, it looks as though this is a known issue (as several tests are commented for Android out that appear to emit the same error). Could you give me any ideas of what I could use as an alternative, or if there's a timescale for a fix / potential solution to this issue?

It might be a red herring, but I can't help noticing that the swipe from coords and the swipe to coords from the logs seem to be quite similar. Is there a bit of doubling up going on somewhere maybe?

This test is being run on OSX Yosemite, using the packaged 1.3.3 dmg and a simple Node.js script.

**Comment by sriramkannan** [comment]
@jlipps I tried your proposed solution and I am having the same effect that the original poster. 
Is there a better way to handle this scrolling thing? I am stuck on the scrolling issue for quite some time now. I tried scrollTo, scroll, scrollToExact and mobile: scroll . They all seem to fail.

**Comment by appiumams** [comment]
Hi I have tried two of the methods and they work fine for me. Note:- i am using WD and appium library

Scroll by x y coordinates : -

`public async scrollByXYCoordinates(xstart: number, ystart: number, xend: number, yend: number) {
		const action = new wd.TouchAction(this._driver);
		action.press({ x: xstart, y: ystart }).wait(1000).moveTo({ x: xend, y: yend }).release();
		return this._driver.performTouchAction(action);
	}`

mobile:scroll : -

`public async scrollDown() {
		return this._driver.execute("mobile: scroll", { direction: "down" });
	}

	public async scrollUp() {
		return this._driver.execute("mobile: scroll", { direction: "up" });
	}

	public async scrollRight() {
		return this._driver.execute("mobile: scroll", { direction: "right" });
	}

	public async scrollLeft() {
		return this._driver.execute("mobile: scroll", { direction: "left" });
	}`
