### ISSUE TITLE
launching the Corporate App with same package name as non- corporate app has a issue.

### ISSUE THREAD

**Issue by yeruva7** [appium/appium#4271]
launching the Corporate App with same package name as non- corporate app has a issue. Example if Adobe reader app is present in both corporate domain and User Apps list of Android 5 ( Now Android 5 provides Enterprise App feature)  Launching App with same package name has a issue. Please let us know how to fix it.

**Comment by imurchie** [comment]
Closing, since this seems to have gone nowhere.
