### ISSUE TITLE
Can't launch appium inspector 

### ISSUE THREAD

**Issue by astgh** [appium/appium#4274]
Hello. 

I am new in appium, so don't know many things, so I hope someone will help me to understand why inspector can't be launch when I use my app's .app file, but it launches when I try to work with an app file downloaded from here (from assets folder).
I use Mac OS Mavericks 10.9 on wmware, Xcode's version - 5.0.2, Appium's version - 1.3.3

this is my log

info: Welcome to Appium v1.3.3 (REV 34e21b01b87d4e3959e1c97c0a8d0b1a610bdc78)

info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"app":"/Users/admin/Downloads/APIO.app","deviceName":"iPhone 4s","showSimulatorLog":true,"robotAddress":"127.0.0.1","robotPort":4,"defaultCommandTimeout":7200}
warn: Deprecated server args: {"--show-sim-log":"use instead: --show-ios-log"}
info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.3","revision":"34e21b01b87d4e3959e1c97c0a8d0b1a610bdc78"}}}

info: <-- GET /wd/hub/status 200 7.964 ms - 104 {"status":0,"value":{"build":{"version":"1.3.3","revision":"34e21b01b87d4e3959e1c97c0a8d0b1a610bdc78"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.3","revision":"34e21b01b87d4e3959e1c97c0a8d0b1a610bdc78"}}}

info: <-- GET /wd/hub/status 200 3.642 ms - 104 {"status":0,"value":{"build":{"version":"1.3.3","revision":"34e21b01b87d4e3959e1c97c0a8d0b1a610bdc78"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.3","revision":"34e21b01b87d4e3959e1c97c0a8d0b1a610bdc78"}}}
info: <-- GET /wd/hub/status 200 0.958 ms - 104 {"status":0,"value":{"build":{"version":"1.3.3","revision":"34e21b01b87d4e3959e1c97c0a8d0b1a610bdc78"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.3","revision":"34e21b01b87d4e3959e1c97c0a8d0b1a610bdc78"}}}

info: <-- GET /wd/hub/status 200 3.245 ms - 104 {"status":0,"value":{"build":{"version":"1.3.3","revision":"34e21b01b87d4e3959e1c97c0a8d0b1a610bdc78"}}}
info: --> GET /wd/hub/sessions {}
info: [debug] Responding to client with success: {"status":0,"value":[]}
info: <-- GET /wd/hub/sessions 200 0.878 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"7.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone 4s"}}
info: Client User-Agent string: Appium (unknown version) CFNetwork/673.0.3 Darwin/13.0.0 (x86_64) (VMware7%2C1)

info: [debug] Using local app from command line: /Users/admin/Downloads/APIO.app
info: [debug] Creating new appium session e7131fff-7059-4d61-8633-d9f7ba5394ab
info: [debug] Removing any remaining instruments sockets

info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder

info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 7.0

info: [debug] Instruments v < 7.1, not checking device string support
info: [debug] Detecting automation tracetemplate

info: [debug] Not auto-detecting udid, running on sim

info: [debug] Parsed app Info.plist (as binary)

info: [debug] Parsed app Localizable.strings
info: [debug] Getting bundle ID from app

info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/admin/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"oneByOne"}

info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/admin/Library/Application Support/appium/bootstrap/bootstrap-a4a902c9cce7b6cb.js

info: [debug] Reusing dynamic bootstrap: /Users/admin/Library/Application Support/appium/bootstrap/bootstrap-a4a902c9cce7b6cb.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.0.2","iOSSDKVersion":"7.0","deviceName":"iPhone 4s","platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone'

info: [debug] Parsed app Info.plist (as binary)

info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iPhoneSimulator

info: [debug] Killing any other simulator daemons

info: [debug] Cleaning sim data files

info: [debug] Deleting /Users/admin/Library/Application Support/iPhone Simulator/7.0.3/Library/TCC

info: [debug] Deleting /Users/admin/Library/Application Support/iPhone Simulator/7.0.3/Library/Caches/locationd

info: [debug] Deleting /Users/admin/Library/Application Support/iPhone Simulator/7.0.3/Library/BackBoard/applicationState.plist

info: [debug] Deleting /Users/admin/Library/Application Support/iPhone Simulator/7.0.3/Media

info: [debug] Deleting /Users/admin/Library/Application Support/iPhone Simulator/7.0.3/Library/Keychains
info: [debug] Deleting /Users/admin/Library/Application Support/iPhone Simulator/7.0.3-64/Library/TCC

info: [debug] Deleting /Users/admin/Library/Application Support/iPhone Simulator/7.0.3-64/Library/Caches/locationd

info: [debug] Deleting /Users/admin/Library/Application Support/iPhone Simulator/7.0.3-64/Library/BackBoard/applicationState.plist

info: [debug] Deleting /Users/admin/Library/Application Support/iPhone Simulator/7.0.3-64/Media

info: [debug] Deleting /Users/admin/Library/Application Support/iPhone Simulator/7.0.3-64/Library/Keychains
info: [debug] Cleaning sim preferences

info: [debug] Cleaning app data files

info: Couldn't find app directories to delete. Probably it's not installed

info: [debug] Not setting locale
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS 7.* simulator log capture

info: [debug] Pre-launching simulator

info: [debug] Killing the simulator process

info: [debug] Killall iPhoneSimulator

info: [debug] Killing any other simulator daemons

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.0.2","iOSSDKVersion":"7.0","deviceName":"iPhone 4s","platformVersion":"7.1"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone'
info: [debug] Launching device: iPhone
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.0.2","iOSSDKVersion":"7.0","deviceName":"iPhone 4s","platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone'

info: [debug] Waited 10 seconds for simulator to start.

info: [debug] No device id or app, not installing to real device.
info: [debug] Starting command proxy.

info: [debug] Instruments socket server started at /tmp/instruments_sock

info: [debug] Starting instruments

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: Launching instruments

info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace /Users/admin/Downloads/APIO.app -e UIASCRIPT "/Users/admin/Library/Application Support/appium/bootstrap/bootstrap-a4a902c9cce7b6cb.js" -e UIARESULTSPATH /tmp/appium-instruments

info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd5/InstrumentsShim.dylib","LIB_PATH":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd5"}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.3","revision":"34e21b01b87d4e3959e1c97c0a8d0b1a610bdc78"},"isShuttingDown":false},"sessionId":"e7131fff-7059-4d61-8633-d9f7ba5394ab"}
info: <-- GET /wd/hub/status 200 1.895 ms - 178 {"status":0,"value":{"build":{"version":"1.3.3","revision":"34e21b01b87d4e3959e1c97c0a8d0b1a610bdc78"},"isShuttingDown":false},"sessionId":"e7131fff-7059-4d61-8633-d9f7ba5394ab"}

info: [debug] [INST STDERR] posix spawn failure; aborting launch (binary == /Users/admin/Downloads/APIO.app/APIO).

info: [debug] [INST STDERR] 2014-12-16 17:43:16.809 instruments[1943:507] Recording cancelled : At least one target failed to launch; aborting run

info: [debug] [INST STDERR] Instruments Trace Error : Error Domain=com.apple.instruments Code=1 "Error Starting Recording" UserInfo=0x7f80dc1421b0 {NSLocalizedDescription=Error Starting Recording, NSLocalizedRecoverySuggestion=At least one target failed to launch; aborting run}
Instruments Trace Error : Failed to start trace.

info: [debug] [INSTSERVER] Instruments exited with code 253

info: [debug] Killall instruments

info: [debug] Instruments crashed on startup

info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iPhoneSimulator

info: Launching instruments

info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace /Users/admin/Downloads/APIO.app -e UIASCRIPT "/Users/admin/Library/Application Support/appium/bootstrap/bootstrap-a4a902c9cce7b6cb.js" -e UIARESULTSPATH /tmp/appium-instruments

info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd5/InstrumentsShim.dylib","LIB_PATH":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd5"}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] posix spawn failure; aborting launch (binary == /Users/admin/Downloads/APIO.app/APIO).

info: [debug] [INST STDERR] 2014-12-16 17:43:23.840 instruments[1956:507] Recording cancelled : At least one target failed to launch; aborting run

info: [debug] [INST STDERR] Instruments Trace Error : Error Domain=com.apple.instruments Code=1 "Error Starting Recording" UserInfo=0x7ffe9306ea20 {NSLocalizedDescription=Error Starting Recording, NSLocalizedRecoverySuggestion=At least one target failed to launch; aborting run}
info: [debug] [INST STDERR] Instruments Trace Error : Failed to start trace.

info: [debug] [INSTSERVER] Instruments exited with code 253

info: [debug] Killall instruments

info: [debug] Instruments crashed on startup

**Comment by imurchie** [comment]
Is the path correct? 

If so, is the app built for the simulator? See [here](https://github.com/appium/appium/blob/master/docs/en/appium-setup/troubleshooting.md#ios) and [here](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/running-tests.md#preparing-your-app-for-test-ios).

**Comment by imurchie** [comment]
Closing. Reopen if this persists.
