### ISSUE TITLE
 Failed to start an Appium session, err was: Error: Log capture did not start in a reasonable amount of time &Could not parse app Localizable.strings assuming it doesn’t exist 

### ISSUE THREAD

**Issue by ravisingh171989** [appium/appium#4281]
How to fix this?? I am using Mac Os 10.10.1 & Xcode 6.1 and 
trying to launch the ios app through eclipse to perform some testing but
 getting this error dont know how to reseolve this issue. I have updated
 the appium to 1.3.4 but still same. Tried to launch same ios app with 
appium 1.3.3 GUI this app launches properly. Anyone can suggest 
anything.

Above issue is observed with simulator 7.1,8.1 etc
By any chance can this be happening bcoz of "No signing Identity found" in xcode

info: Welcome to Appium v1.3.4 (REV 056f5bd277987bed391aef04acf2be38ea161e50)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info:
 --> POST /wd/hub/session 
{"desiredCapabilities":{"app":"/Users/Anand/Library/Developer/Xcode/DerivedData/TestApp-dtutyhtjuncbbnhacstomnqkjttc/Build/Products/Debug-iphonesimulator/TestApp.app","appium-version":"1.0","platformVersion":"7.1","browserName":"","platformName":"iOS","udid":"13FF8920-587E-4AF6-A3B9-AA32E81624EC","deviceName":"iPhone
 5s"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
info:
 [debug] The following desired capabilities were provided, but not 
recognized by appium. They will be passed on to any other services 
running on this server. : appium-version
info: [debug] Using local 
app from desired caps: 
/Users/Anand/Library/Developer/Xcode/DerivedData/TestApp-dtutyhtjuncbbnhacstomnqkjttc/Build/Products/Debug-iphonesimulator/TestApp.app
info: [debug] Creating new appium session 2eb74755-4582-46cf-97b9-78b548cfa1b9
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.1
info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info:
 [debug] Could not parse plist file (as binary) at 
/Users/Anand/Library/Developer/Xcode/DerivedData/TestApp-dtutyhtjuncbbnhacstomnqkjttc/Build/Products/Debug-iphonesimulator/TestApp.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info:
 [debug] Could not parse plist file (as XML) at 
/Users/Anand/Library/Developer/Xcode/DerivedData/TestApp-dtutyhtjuncbbnhacstomnqkjttc/Build/Products/Debug-iphonesimulator/TestApp.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info:
 On some xcode 6 platforms, instruments-without-delay does not work. If 
you experience this, you will need to re-run appium with the 
--native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/Anand/Library/Application Support/appium/bootstrap
info:
 [debug] Dynamic env: 
{"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/Users/Anand/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"grouped"}
...o: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
info: [debug] Dynamic bootstrap path: /Users/Anand/Library/Application Support/appium/bootstrap/bootstrap-723f69bfa90dadc3.js
info: [debug] Reusing dynamic bootstrap: /Users/Anand/Library/Application Support/appium/bootstrap/bootstrap-723f69bfa90dadc3.js
info:
 [debug] Getting device string from opts: 
{"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone
 5s","platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 5s (7.1 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] On a real device; cannot clean device state
info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole
error: Log capture did not start in a reasonable amount of time
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Log capture did not start in a reasonable amount of time
info: [debug] Error: Log capture did not start in a reasonable amount of time
    at null._onTimeout (/Users/Anand/appium/lib/devices/ios/ios-log.js:137:10)
    at Timer.listOnTimeout as ontimeout
info:
 [debug] Responding to client with error: 
{"status":33,"value":{"message":"A new session could not be created. 
(Original error: Log capture did not start in a reasonable amount of 
time)","origValue":"Log capture did not start in a reasonable amount of 
time"},"sessionId":null}
info: <-- POST /wd/hub/session 500 11780.237 ms - 234 
info: [debug] Not pre-launching simulator
info: [debug] Creating iDevice object with udid 13FF8920-587E-4AF6-A3B9-AA32E81624EC
info:
 [debug] Couldn't find ideviceinstaller, trying built-in at 
/Users/Anand/appium/build/libimobiledevice-macosx/ideviceinstaller
info:
 [debug] Checking app install status using: 
/Users/Anand/appium/build/fruitstrap/fruitstrap isInstalled --id 
13FF8920-587E-4AF6-A3B9-AA32E81624EC --bundle com.TestAppparking.mobile

**Comment by ravisingh171989** [comment]
I did install the app from Xcode and using the same to perform testing but its not launching the app only

**Comment by sebv** [comment]
Could you post the a log where the `app=<bundleId>`.

**Comment by chuyaoyao** [comment]
me to,on appium 1.3.4

**Comment by ThreeWind** [comment]
I have the same issue.

**Comment by sebv** [comment]
Looks like the udid is wrong, it should look like this: `94c8f29b955e4c73613d9e54ee83e1b71d599d94`

**Comment by sebv** [comment]
See https://github.com/appium/appium/issues/4216, looks like a duplicate.

Closing, reopen if needed

**Comment by ThreeWind** [comment]
I solved my problem. I wrongly used the udid in Appium's ios configuration when I tested it on a simulator. After I unchecked the option, everything was ok.

**Comment by prabmand** [comment]
I am getting this issue with appium 1.3.6 when I try to use it with a iOS native app on iPad or iPhone(real device)
