### ISSUE TITLE
When running "com.android.commands.monkey", get error: UiAutomator quit before it successfully launched

### ISSUE THREAD

**Issue by lijiancheng0614** [appium/appium#4284]
When the process "com.android.commands.monkey" in the process list, I got the error:

> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\Android\android-sdk\platform-tools\adb.exe -s 169.254.109.177:5555 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\Android\android-sdk\platform-tools\adb.exe -s 169.254.109.177:5555 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] WARNING: linker: libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_RESULT: shortMsg=java.lang.IllegalStateException
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_RESULT: longMsg=UiAutomationService android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@b15adbe8already registered!
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_CODE: 0
> info: [debug] UiAutomator exited
> info: [debug] executing cmd: C:\Android\android-sdk\platform-tools\adb.exe -s 169.254.109.177:5555 shell "echo 'ping'"
> info: [debug] Attempting to uninstall app
> error: UiAutomator quit before it successfully launched
> error: Failed to start an Appium session, err was: Error: UiAutomator quit before it successfully launched
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Error: UiAutomator quit before it successfully launched
>     at null.<anonymous> (D:\Program Files\AppiumForWindows-1.3.4.1\node_modules\appium\lib\devices\android\android.js:204:23)
>     at Object.async.eachSeries (D:\Program Files\AppiumForWindows-1.3.4.1\node_modules\appium\node_modules\async\lib\async.js:145:20)
>     at androidHybrid.stopChromedriverProxies (D:\Program Files\AppiumForWindows-1.3.4.1\node_modules\appium\lib\devices\android\android-hybrid.js:234:9)
>     at null.<anonymous> (D:\Program Files\AppiumForWindows-1.3.4.1\node_modules\appium\lib\devices\android\android.js:199:10)
>     at null.<anonymous> (D:\Program Files\AppiumForWindows-1.3.4.1\node_modules\appium\lib\devices\android\android.js:221:9)
>     at androidCommon.uninstallApp (D:\Program Files\AppiumForWindows-1.3.4.1\node_modules\appium\lib\devices\android\android-common.js:479:5)
>     at null.<anonymous> (D:\Program Files\AppiumForWindows-1.3.4.1\node_modules\appium\lib\devices\android\android.js:219:12)
>     at null.<anonymous> (D:\Program Files\AppiumForWindows-1.3.4.1\node_modules\appium\lib\devices\android\android.js:228:11)
>     at D:\Program Files\AppiumForWindows-1.3.4.1\node_modules\appium\node_modules\appium-adb\lib\adb.js:890:7
>     at null.<anonymous> (D:\Program Files\AppiumForWindows-1.3.4.1\node_modules\appium\node_modules\appium-adb\lib\adb.js:172:9)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: UiAutomator quit before it successfully launched)","origValue":"UiAutomator quit before it successfully launched"},"sessionId":null}

And then I kill the process, it works fine.
So the monkey would affect the Appium?

**Comment by jlipps** [comment]
What I'm asking you to do is:

1) Create your own UiAutomatorTestCase (see Google's docs on that)
2) Start your monkey process
3) Start your own test case with `uiautomator` on your device

And see if that works. If that _does_ work, then maybe the issue is with Appium. If that _doesn't_ work, then it's a Google problem we'll be unable to solve.

**Comment by ngocthanh** [comment]
Hi all,

I got error "UiAutomator quit before it successfully launched" 
I'm use appium version 1.3.3
device: 
F-02G (Docomo arrows) and SH-01G (Docomo aquos) have android version is 4.4.4 => got this error
Samsung note edge (android version 4.4.4) => work fine with appium

Do you have any idea for this issue?

**Comment by moizjv** [comment]
@ngocthanh can you past complete appium log?

**Comment by ngocthanh** [comment]
@moizjv  I found issue, some device from japanese  not enable for UIAutomator test. I will try with UIautomator test case and it fail. MonkeyRunner is OK.

**Comment by moizjv** [comment]
@ngocthanh looks like issue with device. Closing the ticket.
