### ISSUE TITLE
How to identify the xpath of the element using Appium Inspector and use it

### ISSUE THREAD

**Issue by nkytgupta** [appium/appium#4285]
I am not able to find the xpath of any element on the screen using Appium. All I'm getting is the class and the index value of the element in the node details which are again not specific. I've already set up appium and selendroid.

(*I DON'T HAVE THE SOURCE CODE OF THE APPLICATION)

I am using this code to tap on an element:

Thread.sleep(10000);
WebElement pages = driver.findElement(By.xpath("//android.widget.TextView[contains(@text,'RENT')]"));
TouchActions singleTap = new TouchActions(driver).singleTap(pages);
singleTap.perform();

![121](https://cloud.githubusercontent.com/assets/10163534/5485034/a037f2ae-86ba-11e4-84c4-1287e38cc937.jpg)

Need assistance on this. Thanks.

**Comment by prattpratt** [comment]
I guess you're using Android 4.2. ID is accessible only starting from Android 4.3

**Comment by sebv** [comment]
Can this be closed?

**Comment by momenimohammad23** [comment]
@nkytgupta  Hi , I have Same problem . did you solve it ?
thanks

**Comment by karthikpagadala** [comment]
driver.find_element_by_accessibility_id('RENT')
this may work
