### ISSUE TITLE
iOS 8.1 location services issues

### ISSUE THREAD

**Issue by hungl** [appium/appium#4287]
I have just upgraded to Appium 1.3.4.
I tried to run tests on iphone 5s simulator iOS 8.1 (I have Xcode 6.1 installed).
My app needs location services turned on to be able to run.
Location services is on most of the time, but sometimes it is off.

Does anyone experience the same issue?

**Comment by sebv** [comment]
Did you use the `locationServicesEnabled` and `locationServicesAuthorized` caps?

**Comment by sebv** [comment]
Closing, reopen if needed.
