### ISSUE TITLE
Unable to perform Tap on a UIAButton under UIActionSheet using appium 1.3.3

### ISSUE THREAD

**Issue by kohitij** [appium/appium#4295]
Below is the link to detailed issue, with JavaCode/appium-server-logs and logElementTree() output:
https://discuss.appium.io/t/unable-to-tap-uiabutton-under-uiactionsheet-in-appium-1-3-3/2077?u=kohiti_das

**Comment by SrinivasanTarget** [comment]
@kohitij can you please try this in Appium 1.5.x and java client 3.4.1 and raise a new issue with the logs inform of gist incase if you hit the same issue.

**Comment by SrinivasanTarget** [comment]
@triager please close
