### ISSUE TITLE
Annotate webview source vs native source

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#4300]
Currently client bindings have no idea what content type to expect when the page source is requested. The source from a native view is very different from the webview context. To branch based on the type, I've had to resort to content matching against the source which is brittle.

```
info: [debug] Proxying command to 127.0.0.1:9515
info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/a77d36bb8a13c807da5439e7b2bb5527/source","method":"GET"}
info: [debug] Proxied response received with status 200: "{\"sessionId\":\"a77d36bb8a13c807da5439e7b2bb5527\",\"status\":0,\"value\":\"\\u003C!DOCTYPE html>\\u003Chtml xmlns=\\\"http://www.w3.org/1999/xhtml\\\">\\u003Chead>\\n  \\u003Ctitle>I am a page title\\u003C/title>\\n\\u003C/head>\\n\\u003Cbody>\\n  \\u003Ch1>This page is a Selenium sandbox\\u003C/h1>\\n\\n  I am some page content\\n  \\u003Ca href=\\\"linked.html\\\" id=\\\"i am a link\\\">i am a link\\u003C/a>\\u003Cbr />\\n\\n  \\u003Cform id=\\\"the_forms_id\\\">\\n    \\u003Cp>\\n      \\u003Cinput id=\\\"i_am_a_textbox\\\" name=\\\"i_am_a_textbox\\\" type=\\\"text\\\" value=\\\"i has no focus\\\" />\\n    \\u003C/p>\\n  \\u003C/form>\\n\\n\\n\\u003Ciframe src=\\\"about:blank\\\">\\u003C/iframe>\\u003C/body>\\u003C/html>\"}"
```

The [previous logic used in the Ruby bindings](https://github.com/appium/ruby_lib/blob/d4517b878763523068f99b89b38a1ea3b0a98c4b/lib/appium_lib/android/helper.rb#L129) is:

```
if source.start_with? '<html>' # parse html from webview
```

However this breaks surprisingly often because there's no guarantee that the HTML starts with that tag. 
One alternative would be to inspect the name of the current_context. That's not ideal as there aren't any rules about what to expect from a particular context name. When there are problems the response may be empty and in that case matching on the data doesn't help.

It would be awesome if appium added a new JSON attribute to the return of the source command so client bindings are aware of the expected content type.

**Comment by jlipps** [comment]
Doing this would afaik take us out of JSONWP conformance. I think your solution is adequate, let's just stay with that for now.
