### ISSUE TITLE
Simple touchaction hangs forever on appium master

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#4301]
Running this action (part of the Ruby binding test suite) always fails:

```ruby
Appium::TouchAction.new.press(:element => e, x: 0.5, y: 0.5).release(:element => e).perform
```

- [Logs posted via gist](https://gist.github.com/bootstraponline/d7df4157d40c55a175f0)

At one point this worked so I'm not sure what's going on.

**Comment by sebv** [comment]
Is it still happening?

**Comment by bootstraponline** [comment]
no
