### ISSUE TITLE
Issues with the Precise tap option in the appium version 1.3.4-beta1in IOS

### ISSUE THREAD

**Issue by anupa13** [appium/appium#4304]
I am using appium version 1.3.4-beta1 in the mac machine and i am testing with the iphone of IOS-8.
When i select a precise tap  its performing a long tap instead of tap.

**Comment by anupa13** [comment]
Any updates on this?

**Comment by dickeylth** [comment]
Same issue encouted...

**Comment by naveenjammula** [comment]
Can you please provide the update on this issue ??

**Comment by 0x1mason** [comment]
Hi @naveenjammula.  As far as I am aware, this issue has not been addressed yet.

**Comment by sebv** [comment]
Moving to 1.3.6, could someone provide a log showing the issue.

**Comment by jlipps** [comment]
Closing since the old uiautomation driver is defunct and no logs were produced.
