### ISSUE TITLE
Android scrolling code is completely busted

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#4311]
If only we had CI. I am in the process of fixing up one of the Ruby examples.

- [xunit_android](https://github.com/appium/sample-code/commit/02cbe23f463cc0d996a6a02270c41b7a71e81da4) is failing every time on the scroll command.

```ruby
> scroll_to 'Android version'
post /element
{
    :using => "-android uiautomator",
    :value => [
        [0] "new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains("Android version").instance(0));",
        [1] "new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().descriptionContains("Android version").instance(0));"
    ]
}
```

The [full server logs are in this gist](https://gist.github.com/bootstraponline/5aa58824efd848b9b8c7).

This passes (as expected):

> find_element(:uiautomator, 'new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains("Android version").instance(0));')

This fails (as expected):

> find_element(:uiautomator, 'new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().descriptionContains("Android version").instance(0));')

However the problem is when both are sent together, it should pass because one of the selectors matched. At one point I fixed this in the server. We don't know when it broke due to no CI.

The problem is also impacting end users as [reported on discuss.appium.io](https://discuss.appium.io/t/problems-using-scroll-to-and-scroll-to-exact-ruby-and-android/2127)

**Comment by juandelgado** [comment]
Hello there,

Does this break *all* scrolling on Android? Is there a workaround?

Also if you give a bit more information (is this an error on the server, the Ruby lib...) or pointers we might try to give it a go, because this is so very fundamental that impacts a lot of our tests.

Cheers,

Juan

**Comment by bootstraponline** [comment]
Are you using multiple UiScrollables? Or the built in scroll methods in ruby_lib? If not then this appium server bug doesn't impact you.

> Does this break all scrolling on Android? Is there a workaround?

No, send each UiScrollable individually as a work around. Or use touch actions.

> this is so very fundamental that impacts a lot of our tests.

I agree, it's breaking a bunch of the tests I use to validate the appium ruby bindings.

**Comment by jlipps** [comment]
@bootstraponline what exactly is the failure case that we shouldn't be seeing? are we not getting an element back that we expect? or is it not scrolling to something that we expect? @moizjv is trying to repro and fix

**Comment by bootstraponline** [comment]
In summary it's the same as https://github.com/appium/appium/issues/4859 except ignore non-matching selectors when using multiple UiSelectors. The intent of the code is to match on textContains or descriptionContains. The current implementation gives up immediately if textContains doesn't match even though we've supplied an additional selector that does match. This use to work however it changed and broke the samples (such as xunit_android.rb).

I explained this a bit on Slack to @moizjv so hopefully the issue is clearer now. I think the fix for #4859 would also resolve this issue.

**Comment by bootstraponline** [comment]
```
$ ruby xunit_android.rb 
Run options: 

# Running tests:

[1/1] SettingsTest#test_about_phone_versionVersion is: 5.1
Finished tests in 26.775215s, 0.0373 tests/s, 0.0373 assertions/s.
1 tests, 1 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by willosser** [comment]
Tested against 1.4.6, and this code has either not been fixed correctly/sufficiently, or it is broken again.
