### ISSUE TITLE
> error: Failed to start an Appium session, err was: Error: Permission to start activity denied.

### ISSUE THREAD

**Issue by vikasana787** [appium/appium#4313]
I am getting following error in Appium when try to run application on Real Device. In Emulator it is working fine.

> error: Failed to start an Appium session, err was: Error: Permission to start activity denied.

Log
===========
info: [debug] Error: Permission to start activity denied.
>     at null.<anonymous> (D:\Downloads\AppiumForWindows-1.2.0.1\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:1135:19)
>     at null.<anonymous> (D:\Downloads\AppiumForWindows-1.2.0.1\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:172:9)
>     at ChildProcess.exithandler (child_process.js:635:7)
>     at ChildProcess.EventEmitter.emit (events.js:98:17)
>     at maybeClose (child_process.js:743:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Permission to start activity denied.)","origValue":"Permission to start activity denied."},"sessionId":null}
> info: <-- POST /wd/hub/session 500 12954.715 ms - 194 
> error: Failed to start an Appium session, err was: Error: Permission to start activity denied.

**Comment by nkpatnis** [comment]
I am getting this  error too

**Comment by Jonahss** [comment]
Hmm. It's possible there's something you would need to add to your app manifest file?

**Comment by Jonahss** [comment]
This could be related:
http://stackoverflow.com/questions/4162447/android-java-lang-securityexception-permission-denial-start-intent

**Comment by d9kgit** [comment]
Jonahss is right, try to add android:exported="true" to manifest file.

**Comment by moizjv** [comment]
@vikasana787 closing the issue, try @Jonahss suggestion. Also try to launch app with out appium to see if there is issue with the app. Closing issue reopen if this is still an issue.
