### ISSUE TITLE
How to launch Two apps one after the other in same session using appium?

### ISSUE THREAD

**Issue by yeruva7** [appium/appium#4314]
How to launch Two apps one after the other in same session using appium?

**Comment by emirozer** [comment]
You should probably ask these kind of questions on discuss.appium.io

**Comment by imurchie** [comment]
The discussion list would be the better place for this. 

The short answer: in iOS, you cannot do it. In Android, use whatever version of `startActivity` your language binding provides.

**Comment by yeruva7** [comment]
Can you give example? I dint Undestand

**Comment by imurchie** [comment]
In Python, `driver.start_activity(appPackage='my.package', appActivity='.activityIWantToStart')`. Other clients have similar methods.

**Comment by yeruva7** [comment]
But What if my second package is same name as first in Work profile with new Android 21 API's

**Comment by imurchie** [comment]
I have no idea. Can you explain how that works, or point me to documentation?
