### ISSUE TITLE
Appium: can we run parallel tests on multiple devices from the same machine

### ISSUE THREAD

**Issue by hzy00** [appium/appium#4316]
okay, I have tried to start multiple sessions of Appium on different ports. It worked well, but the tests were just ran on port 4723. so I modified the driver.rb: 
i changed  "@appium_port      = appium_lib_opts.fetch :por,4723 " to " @appium_port      = appium_lib_opts.fetch :port,@caps[:port] || 4723" 
then i can add "port" parameter in caps
caps: {
        platformName: 'iOS',
        app: 'me.andpay.apos-cal',
        deviceName: 'iphone',
        udid: '2638de3431aae34b4865df23cafc11e6066feb19',
        port:'4720',
    },
so the tests could be ran on different ports, while i checked the ports, it seemed okay:

COMMAND  PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    7231 install   12u  IPv4 0xe8be068ed3f010d1      0t0  TCP *:4723 (LISTEN)
node    7231 install   13u  IPv4 0xe8be068ecd9300d1      0t0  TCP localhost:4723->localhost:58078 (ESTABLISHED)
ruby    8204 install    7u  IPv4 0xe8be068ed3efaf31      0t0  TCP localhost:58078->localhost:4723 (ESTABLISHED)
COMMAND  PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    7113 install   12u  IPv4 0xe8be068ed709f801      0t0  TCP *:4720 (LISTEN)
node    7113 install   13u  IPv4 0xe8be068ed4517d91      0t0  TCP localhost:4720->localhost:58080 (ESTABLISHED)
ruby    8244 install    7u  IPv4 0xe8be068ed1e910d1      0t0  TCP localhost:58080->localhost:4720 (ESTABLISHED)

two tests were ran on port 4732 and 4730 respectively.
however, the two tests failed immediately. The app started up and just shuted down.
What's wrong with my work?
Any idea, please ?

**Comment by jlipps** [comment]
You can't run against multiple iOS devices on the same machine, unfortunately. This is an Apple limitation.
