### ISSUE TITLE
WebdriverException: Messages: '{"sessionId":null,"Status": 6, "value": " "}'

### ISSUE THREAD

**Issue by kvelukux** [appium/appium#4323]
While trying to tap on Xpath, getting below Appium error all the time,

error:  WebdriverException: Messages: '{"sessionId":null,"Status": 6, "value": " "}'

Appium version: 13.4.beta1 and 1.3.4
IOS version : 8.1.2

**Comment by imurchie** [comment]
Can you provide the commands you are sending, and the Appium server log?

**Comment by imurchie** [comment]
Closing. Reopen if this persists and there is more info.
