### ISSUE TITLE
Can't see Android webview when creating a libraray jar from gradle

### ISSUE THREAD

**Issue by ozadi3** [appium/appium#4326]
Hi,
My Android app uses a jar which opens a webview.

When the jar is build in the bin folder using the eclipse build - appium recognize the webview.
When the the jar is built with gradle  - appium doesn't recognize the webview.

Iv'e made the same test with a "dummy" jar iv'e created which only open an empty webview and the problem occurred.

Can you please let me know if this problem is in appium? or what is the difference between creating a jar using eclipse or through gradle.

Thanks!

**Comment by jlipps** [comment]
That's strange. I don't know what the difference would be, except maybe with gradle the webview debugging flag is set to false instead of true?

**Comment by ozadi3** [comment]
Hi,
Regarding your question - the debugging flag is set to true as expected.
Today we've tried to create a JAR based on a solution we found on stackOverFlow and it solves the problem. (solution can be found here - https://gist.github.com/kellyfj/9666950)

We still cannot find the webview on appium when we build our APP using the SDK as a library.

**Comment by jlipps** [comment]
Are you currently happy with the workaround you found on SO?  Not sure if there's anything Appium can do differently to discover webviews.

**Comment by ozadi3** [comment]
The workaround is not a good solution, but right now we are able to progress.
I still believe that testing why Appium is not recognizing a webview that is opened from within a library is something interesting. I'll be happy to help if that's possible.

**Comment by jlipps** [comment]
I agree. I'll add this to a milestone so we can build a version of our test app with that library and see if we can reproduce the issue.

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
