### ISSUE TITLE
iOS native application testing

### ISSUE THREAD

**Issue by michaazran** [appium/appium#4330]
Hi

I need to start testing iOS native application which is already on the device
can i launch it and automate it even though it was not compiled by the  xcode? 
is it possible to do it just like in android ?

**Comment by imurchie** [comment]
As long as it is provisioned correctly it should work. See [here](https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices.md#appium-on-real-ios-devices).

In the future, such inquiries are better suited for the Appium [discussion list](https://discuss.appium.io/).

**Comment by michaazran** [comment]
i am not talking about an app i developed but an app from the store or any other app
is it possible ?

**Comment by imurchie** [comment]
No, Apple does not allow random apps to be automated.

**Comment by michaazran** [comment]
so if i want to automate let say the "whats up" or the calculator  application
how can i do it ? is it possible ?

**Comment by imurchie** [comment]
You will be able to automate built-in apps running on the simulator. I don't know what "Whats up" is.
