### ISSUE TITLE
sendKeys not handling input with spaces on Android

### ISSUE THREAD

**Issue by xx1501xx** [appium/appium#4334]
I am currently working to get a mobile web test working in sauce labs through the Android Driver. I've been pretty successful except for hitting one major road bump. When we try to populate an address form through sendKeys, the spaces in the address are removed in the input field. For example, "100 main st" becomes "100mainst" and the test fails every time. Is there a known defect with appium or selenium that would cause this or a known work-around?

I have tried a number of different approaches to populating the input field, such as:

sendKeys("100 main st")

or

sendKeys("100")
sendKeys(Keys.SPACE)
sendKeys("main")
...

or
clicking the field first and then sending the keys

and a few other different things.

My desired capabilities pretty much look like the following:

desiredCapabilities = DesiredCapabilities.android()
desiredCapabilities.setCapability("appiumVersion", "1.3.4");
desiredCapabilities.setCapability("deviceName","Android Emulator");
desiredCapabilities.setCapability("device-orientation", "portrait");
desiredCapabilities.setCapability("browserName", "Browser");
desiredCapabilities.setCapability("platformVersion", "4.4");
desiredCapabilities.setCapability("platformName","Android");

**Comment by xx1501xx** [comment]
Hey! Sorry, but I'm not able to paste logs from my locked down virtual machine. If needed, I can try to reproduce this again outside of the vm. Basically, I'm using geb/appium with sauce labs and I can see this issue even when entering a search parameter into google or bing like the following:

I defined an inputBox for bing.com by inputBox { $("input#sb_form_q") }

Then I tried to populate it with searchParam = "This string has spaces" in the following ways and they all fail:

// attempt #1
//		inputBox << searchParam
// attempt #2
//		inputBox.value(searchParam)
// attempt #3
//		inputBox.click()
//		inputBox << searchParam
// attempt #4
		inputBox.click()
		inputBox << "This"
//		driver.sendKeyEvent(AndroidKeyCode.SPACE)
//		inputBox << "\uE00D"
//		inputBox << "\u0020"
//		inputBox << Keys.SPACE
                inputBox << " "
		inputBox << "string"

Please let me know if you have any more questions or if I can help in any other ways. I'm also looking into the issues documented for chromedriver to see if anything matches what I'm seeing. This one looks similar [https://code.google.com/p/chromedriver/issues/detail?id=986]?

**Comment by imurchie** [comment]
If you're on Sauce Labs you ought to be able to make a public link to the job, which will include the Appium server logs.

**Comment by imurchie** [comment]
ChromeDriver does, however, have issues with spaces in text. The one I've run into is spaces being interpreted as newlines (https://code.google.com/p/chromedriver/issues/detail?id=467).

**Comment by xx1501xx** [comment]
Here's a public link to a job that I ran...

https://saucelabs.com/tests/e7641d6964ef4ba398cf34e8f0274080

I just went to motorola.com and tried to enter an address into a shipping page. See the error around 4:40 in the video. Let me know if you have any questions. Thanks again for the help!

**Comment by denisha** [comment]
Hi, I am also experiencing the same issue:         

        capabilities.setCapability("browserName", "Browser");
        capabilities.setCapability("deviceName", "Android Emulator");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("platformVersion", "4.4");
        capabilities.setCapability("appium-version", "1.3.4");

**Comment by jlipps** [comment]
Looking at the logs, Appium is passing the string to Chromedriver correctly. I think it is a Chromedriver issue. You could try with Appium from master, which has a new version of Chromedriver. Otherwise, the only option is to create an issue with the Chromedriver team itself.

**Comment by khangx** [comment]
I am facing this same problem for Android App.
Android 6.0 GenyMotion Emulator for Galaxy S7
appium@1.6.3
appium-adb-2.11.0

setvalue doesn't send text to Android EditText field
sendKeys crashes after a space is entered (ie: text to enter) will send "text " then crash. If I remove all spaces, the test will send "texttoenter" and have no problem.

Since I am not testing against chrome browser, I am not sure where to proceed from here. Any advise?

**Comment by Arkhypov** [comment]
Same issue in 
 Android 5.1
Appium v1.6.5 
appium-artefact: 4.1.2
for sendKeys("Samsung Galaxy S8")
setValue("Samsung Galaxy S8")
driver.getKeyboard().sendKeys("Samsung Galaxy S8")

**Entered text result:**
SamsungG alaxyS 8
