### ISSUE TITLE
Appium/Chromedrive does not recognise web elements

### ISSUE THREAD

**Issue by jflores5** [appium/appium#4335]
Hi,

I am trying to run a very simple test launching Chrome on a real Android device and then going to http://www.google.com and search for something. However, Appium seems to fail when recognising the webElements. When I try to inspect the application (Chrome), Appium complains stating that "Could not launch Appium Inspector. Could not start a new session. Be sure the Appium server ...".

When I try to configure the Android Settings, I am not able to see the complete dialog box, since it does not fits on my screen and I don't see how to scroll down. I am running Appium on a Mac Book.

I appreciate any light to solve these issues.

Thank you.

**Comment by jflores5** [comment]
Since I am not able to inspect Chrome, because Appium cannot launch the inspector, I decided to get all the objects in a list and then try to interact with some of them.  This is the code:

import io.appium.java_client.remote.MobileCapabilityType;
import java.net.URL;
import java.util.List;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

public class FirstTest
{
	public static void main(String[] argv)
		throws Exception
	{
		DesiredCapabilities capabilities = new DesiredCapabilities().chrome();
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "4.4");
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Nexus7");
		capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Chrome");
		ChromeOptions options = new ChromeOptions();

		options.setExperimentalOption("androidPackage", "com.android.chrome");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
		driver.get("http://www.google.com");

		try
		{
			List<WebElement> elementList = driver.findElements(By.xpath("//*"));
			System.out.println("list length: " + elementList.size());

			String attr = null;
			
			for (WebElement we : elementList)
			{
				attr = we.getAttribute("text");
				if (attr != null && attr.equalsIgnoreCase("search"))
				{
					System.out.println("Attr: " + attr);
					System.out.println("Tag: " + we.getTagName());
					System.out.println("Text: " + we.getText());
					System.out.println("To String: " + we.toString());
					we.sendKeys("Appium tutorial");
					we.submit();
				}
			}
		}
		catch (Exception ex)
		{
			System.out.println("Exception: " + ex.getMessage());
		}
		finally
		{
			try
			{
				driver.close();
				driver.quit();
			}
			catch (Exception e)
			{
				System.out.println("Exception when trying to close driver");
				e.printStackTrace(System.err);
			}
		}
	}
}

When running it, I can see how Chrome is launched on the Nexus 7 tablet (real device) and how the browser opens www.google.com.  However, when I try to type a string into an object I get this error:

«An element could not be located on the page using the given search parameters.»

I thought the object was already fetched (it is an element of the list) and therefore I could interact with it, but that's not the case.

Again, any help would be highly appreciated.

**Comment by imurchie** [comment]
Is this issue supposed to be closed? Or was that a mistake?

If it is still an issue, can you provide the server log?

**Comment by jflores5** [comment]
Hi Isaac,

No, it should not be closed.  I guess I accidentally closed it.

Please find attached Appium server log after running the following code (slightly different than the one I originally posted) :


package com.qa.mobile.website;

import io.appium.java_client.remote.MobileCapabilityType;
import java.io.File;
import java.net.URL;
import java.util.List;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

public class FirstTest
{
	public static void main(String[] argv)
		throws Exception
	{
		DesiredCapabilities capabilities = new DesiredCapabilities().chrome();
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "4.4");
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Nexus7");
		capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Chrome");
		ChromeOptions options = new ChromeOptions();

		options.setExperimentalOption("androidPackage", "com.android.chrome");
		capabilities.setCapability(ChromeOptions.CAPABILITY, options);
		File chromeDriverFile = new File("/Users/jaflores/local/bin/chromedriver");
		System.setProperty("webdriver.chrome.driver", chromeDriverFile.getAbsolutePath());
		WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4723/wd/hub"), capabilities);
		driver.get("http://www.google.com");

		try
		{
			List<WebElement> elementList = driver.findElements(By.xpath("//*"));
			System.out.println("list length: " + elementList.size());
			WebElement element = driver.findElement(By.id("com.android.chrome:id/back_button"));
			element.click();
			Thread.sleep(5000);

			element = driver.findElement(By.className("android.widget.Spinner"));
			element.sendKeys("Something to search for");
			
			element = driver.findElement(By.className("android.widget.Button"));
			element.click();
			
			String attr = null;
			int i = 0;
			for (WebElement we : elementList)
			{
				attr = we.getTagName();
				if (i == 1 && attr != null && attr.equalsIgnoreCase("button"))
				{
					System.out.println("Attr " + i + " : " + attr);
					Thread.sleep(3000);
					we.click();
					Thread.sleep(3000);
				}
				i++;
			}
		}
		catch (Exception ex)
		{
			System.out.println("Exception: " + ex.getMessage());
		}
		finally
		{
			System.out.println("Finally");
			try
			{
				driver.close();
				driver.quit();
			}
			catch (Exception e)
			{
				System.out.println("Exception when trying to close driver");
				e.printStackTrace(System.err);
			}
		}
	}
}


==========================================

I am attaching also a screenshot of Appium Console to show how Android-Setttings window is truncated.  I don’t know how to scroll it up to see the bottom of it.

Thank you,


Jaime A. Flores

**Comment by bootstraponline** [comment]
issues are difficult to read when there's a bunch of inline code or server logs. It's best to use gist.github.com and then link to the gist.

**Comment by jflores5** [comment]
Hi bootstraponline,

I don't know how to do what you suggest.  I tried to download the git client, but there is no one for the OS's version I have (OS X Yosemite).

**Comment by imurchie** [comment]
If you're logged in to GitHub on the web, just go to https://gist.github.com/ and copy into the forms there, setting the language, etc. Then post the link created here.

**Comment by jflores5** [comment]
OK.  Thanks for your answer.  I hope this is what is requested:

Appium log: <script src="https://gist.github.com/jflores5/8c38fb41909480691e2a.js"></script>

Java code: <script src="https://gist.github.com/jflores5/98ca556ad2b4a7bbeeb1.js"></script>

**Comment by imurchie** [comment]
At this point, I'm not sure what the problem is. The call to 

```java
WebElement element = driver.findElement(By.id("com.android.chrome:id/back_button"));
```

Doesn't work since the element cannot be found. Is this back button on the web page? Or it in the Chrome browser? If the latter, you need to change context out of the webview into the native context in order to press back (see [here](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/hybrid.md) for how to switch contexts).

**Comment by jflores5** [comment]
Yes, you are right: I should have switched context, since "Back button" is on the Chrome browser.  But initially I tried with several other IDs and class names and Xpath expressions for objects on the web page, such as Spinner:

WebElement element = driver.findElement(By.id("android.widget.Spinner"));

**Comment by jlipps** [comment]
Any reason you don't want to just use driver.back()?

**Comment by jflores5** [comment]
I declared drive as a WebDriver, so the compiler complains if I try to use driver.back.  Perhaps I should have declared it as a different class driver.  I have tried with ChromeDriver as well, thought.

**Comment by jflores5** [comment]
Thank you all for your help.  I finally was able to interact with some of the web elements using different locators instead of using those yielded by uiautomatorviewer.

Still, I would like to know if there is a solution for the truncated Android-Settings window.

**Comment by erajanraja24** [comment]
If you haven't installed the ios webkit install that first. 

Even if web page is not interacting then use the command "brew reinstall --HEAD ios-webkit-debug-proxy" to reinstall it again properly. This worked for me.

Note: In case of conflict, that will give some comment to remove the conflict. Copy and execute the same
