### ISSUE TITLE
JavaScriptExecutor not working for Android application testing (Appium)

### ISSUE THREAD

**Issue by rahulkiwiqa** [appium/appium#4336]
HI ,I'm working on testing an android app,
I can't find any important parameters to find elements,it contains only class name and index ,I tried xpath also but wasn't work so I'm trying it to execute it from JavaScriptExecutor...
Code is..

    if (appiumDriver instanceof JavascriptExecutor) {
        js = (JavascriptExecutor)appiumDriver; 
        System.out.println("INSTANCE FOUND");
    }
    js.executeScript("var list = document.getElementsByClassName(\"android.view.View\");
             list[5].click(); ");

when I run this code an error occurred said ,

ERROR MESSAGE: org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html (WARNING: The server did not provide any stack trace information)

I google it but some blogs said I can't use JS in appium(Android)

**Comment by moizjv** [comment]
Currently android does not support javascript execution. You can ask in [forum](https://discuss.appium.io/) for other ways of finding element.
