### ISSUE TITLE
hideKeyboard - An error occurred while executing user supplied JavaScript

### ISSUE THREAD

**Issue by jvanderwee** [appium/appium#4338]
Attempting to hide the keyboard using the AppiumDriver hideKeyboard method results in the following exception:
``` java 
org.openqa.selenium.WebDriverException: An error occurred while executing user supplied JavaScript
```
I have created a gist containing the log output [here](https://gist.github.com/jvanderwee/62bd84aca21f42af1973).

Using Appium 2.43.1, Java client 2.1.0

**Comment by sebv** [comment]
Could we get full log, Sauce Labs job id (looks like it was running on Sauce Labs).

**Comment by jimberley** [comment]
Here's a full log:

https://gist.github.com/jimberley/79e04b8e3f1373e4bc06

I'm running into the same issue. My logs are dumping the activity into a crash log, so, maybe instruments is crashing?

**Comment by sebv** [comment]
@jimberley yours is not the same, it is happening during `type`, could you open separate issue? (You may try to tap in the field first, might be a focus thing.)

**Comment by sebv** [comment]
@jvanderwee looks like you have this error while closing the keyboard:
`Error: The bundle â€œCloudDocsFileProviderâ€ couldnâ€™t be loaded because it is damaged or missing necessary resources.`

**Comment by jimberley** [comment]
Thank you, @sebv. Opening a new issue.
