### ISSUE TITLE
 Appium 1.3.1 and above broken for click on WEBVIEW element

### ISSUE THREAD

**Issue by braghome** [appium/appium#4340]
css selector lookup is broken on 1.3.1 please go through the gist. Broken from line 286 which manifest into a element not found issue on line 418 https://gist.github.com/braghome/851ef328cc41177793ff

the same test runs fine on 1.2.0

https://gist.github.com/braghome/f1146e4d8c9cd7fb3cfc

on a Rendr.js based web app the only way to predictable with automation is to poll for web elements as the time in which dom elements show is unpredictable at best i.e. 
two example of a good passing test on sauce
```
POST element
1m 13s (+0.02s)
using: "css selector"
value: "button[data-action='signinForm']"
=> {"ELEMENT":"5008"}
GET element/5008/displayed
1m 13s (+0.02s)
=> true
GET element/5008/enabled
1m 13s (+0.02s)
=> true
POST element/5008/click
1m 13s (+0.10s)
id: "5008"
=> null
POST element
1m 14s (+0.06s)
using: "css selector"
value: "a[data-tracking='account']"
=> {"ELEMENT":"5009"}
GET element/5009/displayed
1m 14s (+0.08s)
=> true
GET element/5009/text
1m 14s (+0.04s)
=> "Beakthis"
DELETE /session/1b1cc861e7f1406495237a69c08b6fd9
1m 14s (+1h 0s)
=> ""
```
different run of the same passing test 
```
POST element
1m 32s (+0.01s)
using: "css selector"
value: "button[data-action='signinForm']"
=> {"ELEMENT":"5008"}
GET element/5008/displayed
1m 32s (+0.01s)
=> true
GET element/5008/enabled
1m 32s (+0.01s)
=> true
POST element/5008/click
1m 32s (+0.03s)
id: "5008"
=> null
POST element
1m 32s (+0.01s)
using: "css selector"
value: "a[data-tracking='account']"
=> An element could not be located on the page using the given search parameters.
POST element
1m 32s (+0.01s)
using: "css selector"
value: "a[data-tracking='account']"
=> An element could not be located on the page using the given search parameters.
POST element
1m 32s (+0.01s)
using: "css selector"
value: "a[data-tracking='account']"
=> An element could not be located on the page using the given search parameters.
POST element
1m 32s (+0.01s)
using: "css selector"
value: "a[data-tracking='account']"
=> An element could not be located on the page using the given search parameters.
POST element
1m 33s (+0.01s)
using: "css selector"
value: "a[data-tracking='account']"
=> An element could not be located on the page using the given search parameters.
POST element
1m 33s (+0.01s)
using: "css selector"
value: "a[data-tracking='account']"
=> An element could not be located on the page using the given search parameters.
POST element
1m 33s (+0.01s)
using: "css selector"
value: "a[data-tracking='account']"
=> An element could not be located on the page using the given search parameters.
POST element
1m 33s (+0.01s)
using: "css selector"
value: "a[data-tracking='account']"
=> An element could not be located on the page using the given search parameters.
POST element
1m 33s (+0.01s)
using: "css selector"
value: "a[data-tracking='account']"
=> {"ELEMENT":"5009"}
GET element/5009/displayed
1m 33s (+0.02s)
=> true
GET element/5009/text
1m 33s (+0.02s)
=> "Beakthis"
DELETE /session/3b4b647a493346b5a90119c4f13af054
1m 33s (+1h 7m 0s)
=> ""
```

**Comment by braghome** [comment]
sorry should be fixed now also see this error on 1.3.4 https://gist.github.com/braghome/6bb637330c368c8ca6e4

**Comment by sebv** [comment]
I cannot find `data-tracking='account'` in your log, is it the right one?

**Comment by braghome** [comment]
a[data-tracking='account'] is the last step on the test, you will only see that at end of the test which will be visible only with appium 1.2.0 https://gist.github.com/braghome/f1146e4d8c9cd7fb3cfc

**Comment by sebv** [comment]
Sorry it is not clear to me what is broken? Could you point the exact line in the log?

**Comment by braghome** [comment]
adding screen cast 1.3.4 https://www.screenr.com/vJqN
vs passing test https://www.screenr.com/5JqN

**Comment by braghome** [comment]
before their is any suggestion of tap it is broken 
* tap on WEBVIEW_1 not supported https://gist.github.com/braghome/89673d694e6bc6f29752
* tap with the switch(from WEBVIEW_1 to NATIVE_APP) which is often suggested https://gist.github.com/braghome/9ec2aaf479079b321764

will take any other suggestions are always welcome

**Comment by sebv** [comment]
I think you need to find the element and tap on it within the native context. There is a similar thread here: https://github.com/appium/appium/issues/3896

**Comment by sebv** [comment]
Closing, reopen if needed.

**Comment by normanlopez** [comment]
did you find a solution? where is it?
