### ISSUE TITLE
Chrome command line options for "save password" does not work. No option to handle "location prompt".

### ISSUE THREAD

**Issue by suratdas** [appium/appium#4341]
I referred to the solution of chrome options in Android for translate prompt ( #4119 ) and this works for translate correctly. But when I try to use the same solution for "save password" prompt, it does not work. It does not throw any error but still prompts to save password. I used gmail login to get this prompt. Java code snippet below

ChromeOptions options = new ChromeOptions();
options.addArguments("--enable-automatic-password-saving");
//options.addArguments("--disable-save-password-bubble");
capabilities.setCapability(ChromeOptions.CAPABILITY, options);

Appium log file:
> info: [debug] [CHROMEDRIVER] Starting ChromeDriver (v2.10.267521) on port 9515
> Only local connections are allowed.
> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","args":["--enable-automatic-password-saving"],"extensions":[],"androidDeviceSerial":"YT910J4TTC"}}}}
> info: [debug] Successfully started chrome session 9348c663c22374de163aa4d52cd9cac1
> info: [debug] Overriding session id with "9348c663c22374de163aa4d52cd9cac1"
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId 9348c663c22374de163aa4d52cd9cac1
>

Also, I did not find any way of disabling or setting the option of accepting the location prompt - "http://www.baidu.com wants to use your device's location.". One example is baidu.com

**Comment by jlipps** [comment]
Does passing this arg via capabilities work when using Chromedriver on its own? Appium is sending it correctly, so the next thing I'd check is whether it works to pass this as an arg in the caps to Chromedriver (rather than using it as a flag when invoking Chromedriver's binary)

**Comment by suratdas** [comment]
Same issue when tried with Chromedriver on its own. So, the behavior is same regardless of Appium or chromedriver ( as remotedriver with androidPackage attribute) 
I logged issue https://code.google.com/p/chromedriver/issues/detail?id=1015  with chromedriver.
Please let me know if anything else can be done as a workaround from Appium project ?

**Comment by jlipps** [comment]
One other thing to try: does it work with Chromedriver when you actually launch chromedriver with --disable-save-password-bubble as a command line argument (not a desired cap)?

**Comment by suratdas** [comment]
No, even that does not help. I tried running as a command line argument but still it asks for saving password. Command used is below.
$chromedriver.exe --disable-save-password-bubble

**Comment by jlipps** [comment]
Then yes, it's completely a Chromedriver issue. I don't think we can do anything as a workaround in Appium. Best to keep pinging them on the issue you raised!

**Comment by Karankang007** [comment]
This can be fixed in Chrome 57 as follows:

```
ChromeOptions options = new ChromeOptions();
Map<String, Object> prefs = new HashMap<String, Object>();
prefs.put("credentials_enable_service", false);
prefs.put("profile.password_manager_enabled", false);
options.setExperimentalOption("prefs", prefs);
```

**Comment by Scr34mik** [comment]
vb.net: 
`Dim Chromeoptions = New ChromeOptions
Chromeoptions.AddUserProfilePreference("credentials_enable_service", False)
Chromeoptions.AddUserProfilePreference("profile.password_manager_enabled", False)`

C# : 
`ChromeOptions options = new ChromeOptions();
options.AddUserProfilePreference("credentials_enable_service", false);
options.AddUserProfilePreference("profile.password_manager_enabled", false);`
