### ISSUE TITLE
Unable to click on element by content-desc

### ISSUE THREAD

**Issue by rasagjnya** [appium/appium#4342]
Hi, 

I need to click on a menu link - 'Calendar' and it has properties shown below in the screenshot.
I have tried the following ways and have failed.
1. driver.find_element_by_xpath("//android.view.View[@content-desc='Calendar Link']").click()
2. driver.find_element_by_name("Calendar Link").click()
Anyone has any other idea regarding this?
Please advise.
Thank You.

![untitled](https://cloud.githubusercontent.com/assets/10301689/5624807/15e3657e-9593-11e4-99e3-402787e0a31e.png)

**Comment by suratdas** [comment]
This is what I would do in Java -

1. Import the appium jar file to the build path
2. Define desiredcapability and driver
//Define DesiredCapabilities
AppiumDriver driver=new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
3. Use Android UISelector. Note: UiSelector().description maps to content-desc property of the widget.
driver.findElementByAndroidUIAutomator("UiSelector().description(\"Calendar Link\")").click();

**Comment by rasagjnya** [comment]
Tried this but it's still not working!! :-(

**Comment by imurchie** [comment]
This would be better suited to be asked on the [discussion list](https://discuss.appium.io/).

In the meantime, have you tried to use class name?

**Comment by rasagjnya** [comment]
There are number of android.view.views..so I guess class name would not help...Also, strangely, the code does not throw any error but it just does not click. However tapping by coordinates works (which is something my manager would not appreciate using it).

and @imurchie, i would surely re-post it in the discussion list.

**Comment by bchand1748** [comment]
@rasagjnya were you will to find a solution to this ?
