### ISSUE TITLE
How to test TableView and TableCell?

### ISSUE THREAD

**Issue by kakaluo** [appium/appium#4343]
My app has a tableview, and there are many cells in it. Every time I try to get the first cell, it will failed.
Any idea to solve this issue?
And I also found that you are working on fix the issue in the page:
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/finding-elements.md

I can make the tableview stable In UIAutomation, so I have tried in my way(use execute_script() execute js), but it didn't work.

**Comment by moizjv** [comment]
Do you steps to reproduce the issue? also can you ask this question in [forum](https://discuss.appium.io/)

**Comment by sebv** [comment]
Closing please ask on forum.
