### ISSUE TITLE
Create platform-specific Docker containers for Android (maybe also iOS?)

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium#4347]
I noticed during Windows setup that there are a bunch of steps involved in installation, eg installing git, Maven, etc.  The move to npm packages will make some of the steps redundant, but we should create installers that either make these steps opaque to new users or abstracts them in a wizard.   This would make it easier to get started with Appium.

**Comment by jlipps** [comment]
A more robust solution is to provide containers that have everything ready to go. Trying to create a wizard or installer that works for everyone is a path to insanity!

**Comment by SrinivasanTarget** [comment]
@jlipps Is there anything interesting that you are working on this? Is it something like this: https://hub.docker.com/r/srinivasansekar/docker-appium/

**Comment by jlipps** [comment]
Yes, like that! Maybe we could move that to the appium org and maintain it. I also want to explore a mac image.

**Comment by SrinivasanTarget** [comment]
@jlipps I'm happy to move https://github.com/SrinivasanTarget/docker-appium to Appium Org. But how to do it? Also I don't think so there is a mac image, i see there are ubuntu images and other's.

**Comment by saikrishna321** [comment]
Closing as we have official docker image for android

https://github.com/appium/appium-docker-android
