### ISSUE TITLE
Does appium support hybird app to Chrome test?

### ISSUE THREAD

**Issue by esoests** [appium/appium#4353]
I am trying to use appium 1.3.4 on AndroidPhone 4.4+ devices using "Appium" automationName to automate a hybird app and Chrome.

There are three questions:

1. Does appium support hybirdapp to Chrome test?
Appium can not recognize the Chrome webview, how to operate Chrome then?

2. Does appium suport Chrome to hybirdapp?
Appium can launch Chrome, and find native element in hybirdapp, but can not distinguish the hybirdapp's webview, so we can not switch context to hybird app webview

3. Does appium support cross hybird apps test?
 There are two hybird apps A and B, launch A first and open B, execute getContextHandles(), appium can return both hybird app's webviews like WebView_com.android.A and WebView_com.android.B, but after switch to  the second(B) app's webview,  appium still stays at my test app(A) because getDriver().getPageSource() is the test app(A)'s resource.

Appium support to test hybird app, but after redirects to another's hybird app, appium can not find the web elements? is it an issue?

**Comment by imurchie** [comment]
You should be able to get into a webview and find elements in it. 

Can you provide the server logs so we can see what is going on when you try to switch contexts?

**Comment by esoests** [comment]
Sure. Please help check
Here are some of the logs:

For scenario 2: Chrome to Hybird App(On Samsung Note 3, 4.4.2 OS)
https://gist.github.com/esoests/b9bdafc01d82c09d26cd 

For scenario 3: Hybird App to Hybird App(On LG G3, 4.4.2 OS)
https://gist.github.com/esoests/4eda72b43e0d9e57c4ad

**Comment by esoests** [comment]
@imurchie  Can you help take a look?

**Comment by imurchie** [comment]
I think ChromeDriver can't handle the multiple webviews. You will need to find a way to kill the first webview, at which time Appium can reinitialize the ChromeDriver instance and attach to the new one.

**Comment by esoests** [comment]
If that's a limitation of ChromeDriver, then appium cannot support testing across hybird apps.
Will try your idea.

**Comment by moizjv** [comment]
@esoests did it work?

**Comment by esoests** [comment]
Tried to kill the first app, and it doesn't work.

**Comment by sebv** [comment]
So the answer is we don't support multiple "hybird" apps, moving to new feature.

**Comment by jlipps** [comment]
@esoests can you try again with the latest appium 1.5 beta? This might be fixed with the new architecture

**Comment by jlipps** [comment]
closing until we hear otherwise
