### ISSUE TITLE
Failed Searching element on android by ID

### ISSUE THREAD

**Issue by michaazran** [appium/appium#4354]
hi

i am trying to use the FindElementById or FindElementByAndroidUIAutomator methods of AppiumDriver while searching for an element with it's given ID taken from UI Automator Viewer, the field ID is taken from 
resource-id selector but it keep failing
is there a way to search by this selector? is it possible to search by ID as in the regular  web driver of selenium ?

**Comment by sebv** [comment]
It should work, see this test:
test/functional/android/apidemos/find/basics-specs.js

**Comment by sebv** [comment]
Closing, reopen if needed.
