### ISSUE TITLE
[Android] Can't entering non ascii chars in a TextEdit

### ISSUE THREAD

**Issue by kkesselring-rockta** [appium/appium#4355]
Hi,

I have a problem entering non ascii chars in  a TextEdit field. I already tried the solutions I found in other issues but I can't get it working. I'm using Appium 1.3.4 and Android 4.3. Here is what I'm doing:

caps = {platformName: :android, deviceName: :android_emulator, app: '/Users/me/android/apks/my_app.apk', automationName: 'Appium', platformName: 'Android', language: :de, locale: :de_DE, unicodeKeyboard: true }

app_driver = Appium::Driver.new(caps: caps)
app_driver.appium_port = 4444
app_driver.start_driver
search_box = active_driver.find_element :id, "my.app.android:id/search_src_text"
search_box.send_keys "ü"

The result is that the TextEdit is activated and the cursor is blinking but no text is entered. I don't get any error messages. It is working with ascii chars e.g. search_box.send_keys "a" and is working with Appium using Selendroid. Switching to Selendroid is unfortunately no option due to some other issues with SauceLabs. 

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","deviceName":"android_emulator","app":"/Users/me/android/apks/my_app.apk","automationName":"Appium","language":"de","locale":"de_DE","unicodeKeyboard":true}}
info: Client User-Agent string: Ruby
info: [debug] No appActivity desired capability or server param. Parsing from apk.
info: [debug] No appPackage desired capability or server param. Parsing from apk.
info: [debug] Using local app from desired caps: /Users/me/android/apks/my_app.apk
info: [debug] Creating new appium session e419d6fd-05bd-4c56-beef-f3480020c778
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.7.0_71
info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present
info: [debug] Checking whether adb is present
info: [debug] Using adb from /Users/me/android/sdk/platform-tools/adb
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb shell "getprop persist.sys.language"
info: [debug] Current device persist.sys.language: de
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb shell "getprop persist.sys.country"
info: [debug] Current device persist.sys.country: DE
info: [debug] Setting Android Device Country to de_DE
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb shell "setprop persist.sys.country DE_DE;"
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb shell "stop; sleep 2; setprop sys.boot_completed 0; start"
info: [debug] waiting for reboot, this takes time.
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb shell "getprop sys.boot_completed"
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb shell "getprop sys.boot_completed"
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb shell "getprop sys.boot_completed"
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb shell "getprop sys.boot_completed"
info: [debug] still waiting for reboot.
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb shell "getprop sys.boot_completed"
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb shell "getprop sys.boot_completed"
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb shell "getprop sys.boot_completed"
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb shell "getprop sys.boot_completed"
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb devices
info: [debug] 1 device(s) connected
info: Found device emulator-5554
info: [debug] Setting device id to emulator-5554
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 wait-for-device
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Parsing package and activity from app manifest
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /Users/me/android/sdk/build-tools/21.1.1/aapt
info: [debug] Extracting package and launch activity from manifest.
info: [debug] executing cmd: /Users/me/android/sdk/build-tools/21.1.1/aapt dump badging /Users/me/android/apks/my_app.apk
info: [debug] badging package: my.app.android
info: [debug] badging act: my.app.android.MainActivity
info: [debug] Parsed package and activity are: my.app.android/my.app.android.MainActivity
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 18
info: Device API level is: 18
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "getprop persist.sys.language"
info: [debug] Current device persist.sys.language: de
info: [debug] java -jar "/usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/Users/me/android/apks/my_app.apk" "/tmp/my.app.android" de
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 push "/tmp/my.app.android/strings.json" /data/local/tmp
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /Users/me/android/sdk/build-tools/21.1.1/aapt
info: [debug] Retrieving process from manifest.
info: [debug] executing cmd: /Users/me/android/sdk/build-tools/21.1.1/aapt dump xmltree /Users/me/android/apks/my_app.apk AndroidManifest.xml
info: [debug] Set app process to: my.app.android
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Checking app cert for /Users/me/android/apks/my_app.apk.
info: [debug] executing cmd: java -jar /usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/verify.jar /Users/me/android/apks/my_app.apk
info: [debug] App already signed.
info: [debug] Zip-aligning /Users/me/android/apks/my_app.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from /Users/me/android/sdk/build-tools/21.1.1/zipalign
info: [debug] Zip-aligning apk.
info: [debug] executing cmd: /Users/me/android/sdk/build-tools/21.1.1/zipalign -f 4 /Users/me/android/apks/my_app.apk /var/folders/dg/lfc57f7n043858hlzc7ly9p80000gn/T/appium11507-1764-3nv0dl.tmp
info: [debug] MD5 for app is 274b4a7edd7f8be6cf293c018915a8ec
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "ls /data/local/tmp/274b4a7edd7f8be6cf293c018915a8ec.apk"
info: [debug] Getting install status for my.app.android
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 18
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "pm list packages -3 my.app.android"
info: [debug] App is installed
info: App is already installed, resetting app
info: [debug] Running fast reset (stop and clear)
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "am force-stop my.app.android"
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "pm clear my.app.android"
info: [debug] Forwarding system:4724 to device:4724
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 forward tcp:4724 tcp:4724
info: [debug] Pushing appium bootstrap to device...
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 push "/usr/local/lib/node_modules/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/
info: [debug] Enabling Unicode keyboard support
info: [debug] Pushing unicode ime to device...
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 install "/usr/local/lib/node_modules/appium/build/unicode_ime_apk/UnicodeIME-debug.apk"
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "settings get secure default_input_method"
info: [debug] Unsetting IME 'io.appium.android.ime/.UnicodeIME'
info: [debug] Setting IME to 'io.appium.android.ime/.UnicodeIME'
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "ime enable io.appium.android.ime/.UnicodeIME"
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "ime set io.appium.android.ime/.UnicodeIME"
info: [debug] Pushing settings apk to device...
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 install "/usr/local/lib/node_modules/appium/build/settings_apk/settings_apk-debug.apk"
info: [debug] Pushing unlock helper app to device...
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 install "/usr/local/lib/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"
info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "ps 'uiautomator'"
info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] Waking up device if it's not alive
info: [debug] Pushing command to appium work queue: ["wake",{}]
info: [debug] [BOOTSTRAP] [debug] json loading complete.
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: wake
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window"
info: Unlocking screen
info: [debug] Screen is locked, trying to unlock
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 18
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window"
info: [debug] Screen is unlocked, continuing
info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data","status":0}
info: [debug] dataDir set to: /data
info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
info: [debug] Device is at API Level 18
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n my.app.android/my.app.android.MainActivity"
info: [debug] Waiting for pkg "my.app.android" and activity "my.app.android.MainActivity" to be focused
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /Users/me/android/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Device launched! Ready for commands
info: [debug] Setting command timeout to the default of 60 secs
info: [debug] Appium session started with sessionId e419d6fd-05bd-4c56-beef-f3480020c778
info: <-- POST /wd/hub/session 303 21593.636 ms - 9
info: --> GET /wd/hub/session/e419d6fd-05bd-4c56-beef-f3480020c778 {}
info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.1","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","deviceName":"android_emulator","app":"/Users/me/android/apks/my_app.apk","automationName":"Appium","language":"de","locale":"de_DE","unicodeKeyboard":true},"platformName":"Android","deviceName":"android_emulator","app":"/Users/me/android/apks/my_app.apk","automationName":"Appium","language":"de","locale":"de_DE","unicodeKeyboard":true},"sessionId":"e419d6fd-05bd-4c56-beef-f3480020c778"}
info: <-- GET /wd/hub/session/e419d6fd-05bd-4c56-beef-f3480020c778 200 1.736 ms - 815 {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.1","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","deviceName":"android_emulator","app":"/Users/me/android/apks/my_app.apk","automationName":"Appium","language":"de","locale":"de_DE","unicodeKeyboard":true},"platformName":"Android","deviceName":"android_emulator","app":"/Users/me/android/apks/my_app.apk","automationName":"Appium","language":"de","locale":"de_DE","unicodeKeyboard":true},"sessionId":"e419d6fd-05bd-4c56-beef-f3480020c778"}
info: --> POST /wd/hub/session/e419d6fd-05bd-4c56-beef-f3480020c778/timeouts/implicit_wait {"ms":30000}
info: [debug] Set Android implicit wait to 30000ms
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"e419d6fd-05bd-4c56-beef-f3480020c778"}
info: <-- POST /wd/hub/session/e419d6fd-05bd-4c56-beef-f3480020c778/timeouts/implicit_wait 200 1.582 ms - 76 {"status":0,"value":null,"sessionId":"e419d6fd-05bd-4c56-beef-f3480020c778"}
info: --> POST /wd/hub/session/e419d6fd-05bd-4c56-beef-f3480020c778/element {"using":"id","value":"my.app.android:id/search_src_text"}
info: [debug] Waiting up to 30000ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"id","selector":"my.app.android:id/search_src_text","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"my.app.android:id/search_src_text","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding my.app.android:id/search_src_text using ID with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=my.app.android:id/search_src_text]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"ELEMENT":"1"},"status":0}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"e419d6fd-05bd-4c56-beef-f3480020c778"}
info: <-- POST /wd/hub/session/e419d6fd-05bd-4c56-beef-f3480020c778/element 200 14.127 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"e419d6fd-05bd-4c56-beef-f3480020c778"}
info: --> POST /wd/hub/session/e419d6fd-05bd-4c56-beef-f3480020c778/element/1/value {"value":["ü"]}
info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"1","text":"ü","replace":false,"unicodeKeyboard":true}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"ü","replace":false,"unicodeKeyboard":true}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: setText
info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
info: [debug] [BOOTSTRAP] [debug] Updating class "class com.android.uiautomator.core.UiDevice" to enable field "mUiAutomationBridge"
info: [debug] [BOOTSTRAP] [debug] Updating class "class com.android.uiautomator.core.UiAutomatorBridge" to enable field "mInteractionController"
info: [debug] [BOOTSTRAP] [debug] Finding methods on class: class com.android.uiautomator.core.InteractionController
info: [debug] [BOOTSTRAP] [debug] Text remains after clearing, but it appears to be hint text.
info: [debug] [BOOTSTRAP] [debug] Text not cleared. Assuming remainder is hint text.
info: [debug] [BOOTSTRAP] [debug] Sending Unicode text to element: ü
info: [debug] [BOOTSTRAP] [debug] Encoded text: &APw
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"e419d6fd-05bd-4c56-beef-f3480020c778"}

**Comment by jlipps** [comment]
Interesting, this definitely isn't the intended behavior. @imurchie can you think of anything that's going wrong with the unicodeKeyboard here?

**Comment by imurchie** [comment]
If you get the text after having done the `send_keys`, do you get the correct letter? Some Android emulators (which is to say, all before API level 20) don't have the fonts to display some glyphs, though they get in there.

**Comment by imurchie** [comment]
Exploring a bit more, this is indeed a bug. It seems that the end of the encoding is not getting added, so it doesn't get recoded. I'm looking into it.

**Comment by kkesselring-rockta** [comment]
Great job guys thanks. :thumbsup:
