### ISSUE TITLE
How to open notification message on android?

### ISSUE THREAD

**Issue by michaazran** [appium/appium#4357]
hi

i am trying to a open the notification message on the top of the screen like when getting new SMS
is it possible to open such message?
i noticed that there is driver.openNotifications() but i cannot find it in my driver 
i am using appium-dotnet-driver on appium server 1.3.4
AppiumDriver iDriver = new AppiumDriver(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities, new TimeSpan(0, 0, 30));
any idea ?

**Comment by imurchie** [comment]
Have you looked at https://github.com/appium/appium-dotnet-driver/blob/master/appium-dotnet-driver/Appium/Android/AndroidDriver.cs#L214

**Comment by michaazran** [comment]
so let say i need to automate the following scenario
i am getting a new SMS or i have a missed call and i want to open that screen from the notifications area
in order to create appium driver i need to find the package and the activity
and idea how to do it ?
thanks.

**Comment by imurchie** [comment]
Package and activity of what? What app are you automating? You should be able to find the appropriate values from the apk.

**Comment by michaazran** [comment]
lets for example take the regular SMS chat, when i get SMS i see a notification in the top area of the mobile, not i need to open it , click on it

![untitled](https://cloud.githubusercontent.com/assets/4409879/5654258/ee4a63ea-96c9-11e4-96a5-6f0774da437a.png)

**Comment by michaazran** [comment]
when i create the appium driver from the code i need to populate the package and activity for the DesiredCapabilities, what are the values ? is it possible ?

**Comment by imurchie** [comment]
If you are already in a test, you ought to have started the driver with the app under test, no? When an SMS comes in, you can open the notifications using the same driver. Or am I confusing something?

**Comment by michaazran** [comment]
I downloaded the updated dot net driver and i managed to use the OpenNotification method
thank you very much for your help, i managed to automate it
