### ISSUE TITLE
Can there be FindElemenetByNameContaining(some data) ?

### ISSUE THREAD

**Issue by arijain28** [appium/appium#4359]
I have come across the text of the elements in the mobile automation which are case sensitive. Therefore i had to write lot of try catch..Thinking of a function which could check the case sensitive elements and is also fast in execution at the same time

**Comment by 0x1mason** [comment]
I'm afraid I don't understand the relationship between case sensitivity (which your message addresses) and substring searches (which is the ostensible purpose of `FindElemenetByNameContaining`).  Are you asking for case insensitive searches?  A concrete example would be helpful.

**Comment by arijain28** [comment]
I added the code in the bootstrap and other files to resolve my query...
for instance i am searching element with name "Privacy" and in other mobile it is "privacy"..so of i write find element by name containing "privacy"...this one statement should run in both the mobile automation

**Comment by arijain28** [comment]
This happens in uiautomator testing of android

**Comment by 0x1mason** [comment]
If you've got the code to do it, submit a pull request and we'll take a look at it.  Otherwise, I'm not convinced this is something we need to support.  Eg, in UiAutomator, matching is case-sensitive and don't think it can be turned off. Users can implement this on the client side quite easily.
