### ISSUE TITLE
Could not Start appium inspector error

### ISSUE THREAD

**Issue by astgh** [appium/appium#4361]
I have downloaded an app from github, and tried to launch it. it worked fine with simulator (iPhone 5s, 7.1), but when I tried to use other simulators, they didn't work. I came back to the one which worked for me, and now I see this 

info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find a device to launch. You requested 'iPhone 5s (FBC69920-78B2-4E41-BEB8-F8A0FE008D80) (7.1 Simulator)', but the available devices were: [\"iPad 2 (7.1 Simulator) [EC6F011A-3DDE-4C7C-A57B-5839B428A05C]\",\"iPad 2 (8.1 Simulator) [C6075030-DB03-446B-9D50-C5EEB18880AA]\",\"iPad Air (7.1 Simulator) [8EB536C4-C9F6-43D4-A00E-ACBE349BCF24]\",\"iPad Air (8.1 Simulator) [8518DE27-64CB-4A99-8E97-833DF2F68F58]\",\"iPad Retina (7.1 Simulator) [52E8180D-3AE4-44BE-8CB3-8E1961CDB82F]\",\"iPad Retina (8.1 Simulator) [2A378351-FFBC-4909-9A31-16004171241A]\",\"iPhone 4s (7.1 Simulator) [62E6EC64-6C9F-41B1-9E8C-75557D688917]\",\"iPhone 4s (8.1 Simulator) [29B2A53F-6C83-4EA3-A045-8537664A1614]\",\"iPhone 5 (7.1 Simulator) [1634D7C5-3F98-442D-8112-727DB9D81D17]\",\"iPhone 5 (8.1 Simulator) [11239088-B5EF-4EAB-8873-8598579CD23B]\",\"iPhone 5s (7.1 Simulator) [FBC69920-78B2-4E41-BEB8-F8A0FE008D80]\",\"iPhone 5s (8.1 Simulator) [5F86F3B2-001E-4B52-98C5-4AADDE0EE939]\",\"iPhone 6 (8.1 Simulator) [DC3BEEB7-21B0-4D58-999A-8177AEAA7578]\",\"iPhone 6 Plus (8.1 Simulator) [B90F64F2-534C-4B42-B915-63B5108D03DF]\"])","origValue":"Could not find a device to launch. You requested 'iPhone 5s (FBC69920-78B2-4E41-BEB8-F8A0FE008D80) (7.1 Simulator)', but the available devices were: [\"iPad 2 (7.1 Simulator) [EC6F011A-3DDE-4C7C-A57B-5839B428A05C]\",\"iPad 2 (8.1 Simulator) [C6075030-DB03-446B-9D50-C5EEB18880AA]\",\"iPad Air (7.1 Simulator) [8EB536C4-C9F6-43D4-A00E-ACBE349BCF24]\",\"iPad Air (8.1 Simulator) [8518DE27-64CB-4A99-8E97-833DF2F68F58]\",\"iPad Retina (7.1 Simulator) [52E8180D-3AE4-44BE-8CB3-8E1961CDB82F]\",\"iPad Retina (8.1 Simulator) [2A378351-FFBC-4909-9A31-16004171241A]\",\"iPhone 4s
 (7.1 Simulator) [62E6EC64-6C9F-41B1-9E8C-75557D688917]\",\"iPhone 4s (8.1 Simulator) [29B2A53F-6C83-4EA3-A045-8537664A1614]\",\"iPhone 5 (7.1 Simulator) [1634D7C5-3F98-442D-8112-727DB9D81D17]\",\"iPhone 5 (8.1 Simulator) [11239088-B5EF-4EAB-8873-8598579CD23B]\",\"iPhone 5s (7.1 Simulator) [FBC69920-78B2-4E41-BEB8-F8A0FE008D80]\",\"iPhone 5s (8.1 Simulator) [5F86F3B2-001E-4B52-98C5-4AADDE0EE939]\",\"iPhone 6 (8.1 Simulator) [DC3BEEB7-21B0-4D58-999A-8177AEAA7578]\",\"iPhone 6 Plus (8.1 Simulator) [B90F64F2-534C-4B42-B915-63B5108D03DF]\"]"},"sessionId":null}

notice, that the one I request is also in the list of available simulators. The problem exists both in appium 1.3.3 and 1.3.4. can you help me somehow ?

**Comment by jlipps** [comment]
Sure, I think I can see what's going on. Can you provide the full log for that run, please?

**Comment by amedvedjev** [comment]
had same problem. fixed by erasing in settings "'iPhone 5s (FBC69920-78B2-4E41-BEB8-F8A0FE008D80) (7.1 Simulator)" to "'iPhone 5s". boring that it needed to do during every start or GUI. (i am on Mac. in case)

**Comment by jlipps** [comment]
Looks like the appium dot app is populating the device name incorrectly, then

**Comment by jlipps** [comment]
I'd say to raise this as an issue with the appium-dot-app project---it should either use brackets instead of parens, or leave off the udid entirely.

**Comment by astgh** [comment]
this is the whole log in appium 1.3.4

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --address "127.0.0.1" --command-timeout "7200" --robot-address "127.0.0.1" --robot-port "4723" --platform-version "7.1" --platform-name "iOS" --app "/Users/admin/Downloads/TestApp.app" --show-sim-log --device-name "iPhone 5s (FBC69920-78B2-4E41-BEB8-F8A0FE008D80)" --launch-timeout "90000"

info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)

info: Appium REST http interface listener started on 127.0.0.1:4723
info: [debug] Non-default server args: {"app":"/Users/admin/Downloads/TestApp.app","address":"127.0.0.1","launchTimeout":"90000","deviceName":"iPhone 5s (FBC69920-78B2-4E41-BEB8-F8A0FE008D80)","platformName":"iOS","platformVersion":"7.1","showSimulatorLog":true,"robotAddress":"127.0.0.1","robotPort":4723,"defaultCommandTimeout":7200}
warn: Deprecated server args: {"--show-sim-log":"use instead: --show-ios-log"}
info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}

info: <-- GET /wd/hub/status 200 13.490 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}

info: <-- GET /wd/hub/status 200 3.042 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}
info: <-- GET /wd/hub/status 200 2.097 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}
info: --> GET /wd/hub/sessions {}
info: [debug] Responding to client with success: {"status":0,"value":[]}
info: <-- GET /wd/hub/sessions 200 1.088 ms - 23 {"status":0,"value":[]}
info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"7.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone 5s (FBC69920-78B2-4E41-BEB8-F8A0FE008D80)"}}
info: Client User-Agent string: Appium (unknown version) CFNetwork/720.1.1 Darwin/14.0.0 (x86_64)
info: [debug] Using local app from command line: /Users/admin/Downloads/TestApp.app
info: [debug] Creating new appium session 9bd9af4c-38ab-43b1-852f-68f04e00ffb7
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder

info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 8.1
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone 5s (FBC69920-78B2-4E41-BEB8-F8A0FE008D80)","platformVersion":"7.1"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 5s (FBC69920-78B2-4E41-BEB8-F8A0FE008D80) (7.1 Simulator)'
info: [debug] Cleaning up appium session

error: Could not find a device to launch. You requested 'iPhone 5s (FBC69920-78B2-4E41-BEB8-F8A0FE008D80) (7.1 Simulator)', but the available devices were: ["iPad 2 (7.1 Simulator) [EC6F011A-3DDE-4C7C-A57B-5839B428A05C]","iPad 2 (8.1 Simulator) [C6075030-DB03-446B-9D50-C5EEB18880AA]","iPad Air (7.1 Simulator) [8EB536C4-C9F6-43D4-A00E-ACBE349BCF24]","iPad Air (8.1 Simulator) [8518DE27-64CB-4A99-8E97-833DF2F68F58]","iPad Retina (7.1 Simulator) [52E8180D-3AE4-44BE-8CB3-8E1961CDB82F]","iPad Retina (8.1 Simulator) [2A378351-FFBC-4909-9A31-16004171241A]","iPhone 4s (7.1 Simulator) [62E6EC64-6C9F-41B1-9E8C-75557D688917]","iPhone 4s (8.1 Simulator) [29B2A53F-6C83-4EA3-A045-8537664A1614]","iPhone 5 (7.1 Simulator) [1634D7C5-3F98-442D-8112-727DB9D81D17]","iPhone 5 (8.1 Simulator) [11239088-B5EF-4EAB-8873-8598579CD23B]","iPhone 5s (7.1 Simulator) [FBC69920-78B2-4E41-BEB8-F8A0FE008D80]","iPhone 5s (8.1 Simulator) [5F86F3B2-001E-4B52-98C5-4AADDE0EE939]","iPhone 6 (8.1 Simulator) [DC3BEEB7-21B0-4D58-999A-8177AEAA7578]","iPhone 6 Plus (8.1 Simulator) [B90F64F2-534C-4B42-B915-63B5108D03DF]"]
error: Failed to start an Appium session, err was: Error: Could not find a device to launch. You requested 'iPhone 5s (FBC69920-78B2-4E41-BEB8-F8A0FE008D80) (7.1 Simulator)', but the available devices were: ["iPad 2 (7.1 Simulator) [EC6F011A-3DDE-4C7C-A57B-5839B428A05C]","iPad 2 (8.1 Simulator) [C6075030-DB03-446B-9D50-C5EEB18880AA]","iPad Air (7.1 Simulator) [8EB536C4-C9F6-43D4-A00E-ACBE349BCF24]","iPad Air (8.1 Simulator) [8518DE27-64CB-4A99-8E97-833DF2F68F58]","iPad Retina (7.1 Simulator) [52E8180D-3AE4-44BE-8CB3-8E1961CDB82F]","iPad Retina (8.1 Simulator) [2A378351-FFBC-4909-9A31-16004171241A]","iPhone 4s (7.1 Simulator) [62E6EC64-6C9F-41B1-9E8C-75557D688917]","iPhone 4s (8.1 Simulator) [29B2A53F-6C83-4EA3-A045-8537664A1614]","iPhone 5 (7.1 Simulator) [1634D7C5-3F98-442D-8112-727DB9D81D17]","iPhone 5 (8.1 Simulator) [11239088-B5EF-4EAB-8873-8598579CD23B]","iPhone 5s (7.1 Simulator) [FBC69920-78B2-4E41-BEB8-F8A0FE008D80]","iPhone 5s (8.1 Simulator) [5F86F3B2-001E-4B52-98C5-4AADDE0EE939]","iPhone 6 (8.1 Simulator) [DC3BEEB7-21B0-4D58-999A-8177AEAA7578]","iPhone 6 Plus (8.1 Simulator) [B90F64F2-534C-4B42-B915-63B5108D03DF]"]

info: [debug] Error: Could not find a device to launch. You requested 'iPhone 5s (FBC69920-78B2-4E41-BEB8-F8A0FE008D80) (7.1 Simulator)', but the available devices were: ["iPad 2 (7.1 Simulator) [EC6F011A-3DDE-4C7C-A57B-5839B428A05C]","iPad 2 (8.1 Simulator) [C6075030-DB03-446B-9D50-C5EEB18880AA]","iPad Air (7.1 Simulator) [8EB536C4-C9F6-43D4-A00E-ACBE349BCF24]","iPad Air (8.1 Simulator) [8518DE27-64CB-4A99-8E97-833DF2F68F58]","iPad Retina (7.1 Simulator) [52E8180D-3AE4-44BE-8CB3-8E1961CDB82F]","iPad Retina (8.1 Simulator) [2A378351-FFBC-4909-9A31-16004171241A]","iPhone 4s (7.1 Simulator) [62E6EC64-6C9F-41B1-9E8C-75557D688917]","iPhone 4s (8.1 Simulator) [29B2A53F-6C83-4EA3-A045-8537664A1614]","iPhone 5 (7.1 Simulator) [1634D7C5-3F98-442D-8112-727DB9D81D17]","iPhone 5 (8.1 Simulator) [11239088-B5EF-4EAB-8873-8598579CD23B]","iPhone 5s (7.1 Simulator) [FBC69920-78B2-4E41-BEB8-F8A0FE008D80]","iPhone 5s (8.1 Simulator) [5F86F3B2-001E-4B52-98C5-4AADDE0EE939]","iPhone 6 (8.1 Simulator) [DC3BEEB7-21B0-4D58-999A-8177AEAA7578]","iPhone 6 Plus (8.1 Simulator) [B90F64F2-534C-4B42-B915-63B5108D03DF]"]
    at noDevicesError (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1101:10)
    at null.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1107:16)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:525:46
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:254:17
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:151:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:251:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:615:34
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:516:25
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:111:7
    at ChildProcess.exithandler (child_process.js:656:7)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find a device to launch. You requested 'iPhone 5s (FBC69920-78B2-4E41-BEB8-F8A0FE008D80) (7.1 Simulator)', but the available devices were: [\"iPad 2 (7.1 Simulator) [EC6F011A-3DDE-4C7C-A57B-5839B428A05C]\",\"iPad 2 (8.1 Simulator) [C6075030-DB03-446B-9D50-C5EEB18880AA]\",\"iPad Air (7.1 Simulator) [8EB536C4-C9F6-43D4-A00E-ACBE349BCF24]\",\"iPad Air (8.1 Simulator) [8518DE27-64CB-4A99-8E97-833DF2F68F58]\",\"iPad Retina (7.1 Simulator) [52E8180D-3AE4-44BE-8CB3-8E1961CDB82F]\",\"iPad Retina (8.1 Simulator) [2A378351-FFBC-4909-9A31-16004171241A]\",\"iPhone 4s (7.1 Simulator) [62E6EC64-6C9F-41B1-9E8C-75557D688917]\",\"iPhone 4s (8.1 Simulator) [29B2A53F-6C83-4EA3-A045-8537664A1614]\",\"iPhone 5 (7.1 Simulator) [1634D7C5-3F98-442D-8112-727DB9D81D17]\",\"iPhone 5 (8.1 Simulator) [11239088-B5EF-4EAB-8873-8598579CD23B]\",\"iPhone 5s (7.1 Simulator) [FBC69920-78B2-4E41-BEB8-F8A0FE008D80]\",\"iPhone 5s (8.1 Simulator) [5F86F3B2-001E-4B52-98C5-4AADDE0EE939]\",\"iPhone 6 (8.1 Simulator) [DC3BEEB7-21B0-4D58-999A-8177AEAA7578]\",\"iPhone 6 Plus (8.1 Simulator) [B90F64F2-534C-4B42-B915-63B5108D03DF]\"])","origValue":"Could not find a device to launch. You requested 'iPhone 5s (FBC69920-78B2-4E41-BEB8-F8A0FE008D80) (7.1 Simulator)', but the available devices were: [\"iPad 2 (7.1 Simulator) [EC6F011A-3DDE-4C7C-A57B-5839B428A05C]\",\"iPad 2 (8.1 Simulator) [C6075030-DB03-446B-9D50-C5EEB18880AA]\",\"iPad Air (7.1 Simulator) [8EB536C4-C9F6-43D4-A00E-ACBE349BCF24]\",\"iPad Air (8.1 Simulator) [8518DE27-64CB-4A99-8E97-833DF2F68F58]\",\"iPad Retina (7.1 Simulator) [52E8180D-3AE4-44BE-8CB3-8E1961CDB82F]\",\"iPad Retina (8.1 Simulator) [2A378351-FFBC-4909-9A31-16004171241A]\",\"iPhone 4s (7.1 Simulator) [62E6EC64-6C9F-41B1-9E8C-75557D688
917]\",\"iPhone 4s (8.1 Simulator) [29B2A53F-6C83-4EA3-A045-8537664A1614]\",\"iPhone 5 (7.1 Simulator) [1634D7C5-3F98-442D-8112-727DB9D81D17]\",\"iPhone 5 (8.1 Simulator) [11239088-B5EF-4EAB-8873-8598579CD23B]\",\"iPhone 5s (7.1 Simulator) [FBC69920-78B2-4E41-BEB8-F8A0FE008D80]\",\"iPhone 5s (8.1 Simulator) [5F86F3B2-001E-4B52-98C5-4AADDE0EE939]\",\"iPhone 6 (8.1 Simulator) [DC3BEEB7-21B0-4D58-999A-8177AEAA7578]\",\"iPhone 6 Plus (8.1 Simulator) [B90F64F2-534C-4B42-B915-63B5108D03DF]\"]"},"sessionId":null}
info: <-- POST /wd/hub/session 500 8301.837 ms - 2348

**Comment by astgh** [comment]
I followed @amedvedjev 's advice and it really help! thx a lot

**Comment by g-one** [comment]
Even i got the same error  as @amedvedjev  and checked the log, its because of the DEVICE STRING:

In ios.js file device string is adding (Verison + Simulator) but the actual simulator string is different..
![screen shot 2015-01-09 at 1 21 01 pm](https://cloud.githubusercontent.com/assets/1217480/5685899/41eb72b0-9804-11e4-9f5a-be8b39afd5d8.png)

Log:
![screen shot 2015-01-09 at 1 21 24 pm](https://cloud.githubusercontent.com/assets/1217480/5685926/7411bb28-9804-11e4-9eb2-e215788812b6.png)

Available Simulators:
![image](https://cloud.githubusercontent.com/assets/1217480/5685938/8babe98e-9804-11e4-975a-364e4c2e21cc.png)

As @amedvedjev said, did the same thing and it works fine :+1: .
Thanks,
Jeevan

**Comment by michelleXIE2014** [comment]
how to erase the list by changing the device list? thanks
