### ISSUE TITLE
multiple device launch

### ISSUE THREAD

**Issue by tarunHub** [appium/appium#4362]
how can we run our test case on multiple devices in one go.
For web applications we can run our test cases both on firefox and chrome and other browsers in parallel.
for reference : http://www.guru99.com/cross-browser-testing-using-selenium.html

To execute test cases with different browsers in the same machine at same time we can integrate TestNG framework with Selenium WebDriver.

**Comment by sebv** [comment]
Most likely you'll need several VMS, specially with ios.

**Comment by sebv** [comment]
Closing reopen if needed.
