### ISSUE TITLE
Swipe is not working on android dot net driver appium 1.3.4.1

### ISSUE THREAD

**Issue by michaazran** [appium/appium#4363]
hi

i am trying to do swipe on object on android device

element bounds are [0,490][768,1184]
i am trying to swipe from the middle to the right side in the middle

Am i missing something ???? it does not work

this is the command
OpenQA.Selenium.Appium.Interfaces.ITouchAction it = Swipe(iDriver, 384, 347, 600, 347, 1500);
it.Perform();

This is the function 
public static OpenQA.Selenium.Appium.Interfaces.ITouchAction Swipe(AppiumDriver driver, int startX, int startY, int endX, int endY,
                int duration)
        {
            OpenQA.Selenium.Appium.Interfaces.ITouchAction touchAction = new OpenQA.Selenium.Appium.MultiTouch.TouchAction(driver)
                .Press(startX, startY)
                .Wait(duration)
                .MoveTo(endX, endY)
                .Release();
            return touchAction;
        }

**Comment by imurchie** [comment]
Can you provide the server log?

**Comment by michaazran** [comment]
the log seems OK but i see nothing in the screen

this is the screen, i need to move the middle phone icon to the right side where the green phone icon
the whole black area is one object so i am trying to swipe from the middle of it to the right

![screen](https://cloud.githubusercontent.com/assets/4409879/5667878/e0a6e68c-9773-11e4-8ca5-669fdefbbdae.png)


info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":
"5"},"sessionId":"9702c04f-d142-4853-bf48-8dbfc245f208"}
info: <-- POST /wd/hub/session/9702c04f-d142-4853-bf48-8dbfc245f208/element 200
72.627 ms - 87 {"status":0,"value":{"ELEMENT":"5"},"sessionId":"9702c04f-d142-48
53-bf48-8dbfc245f208"}
info: --> POST /wd/hub/session/9702c04f-d142-4853-bf48-8dbfc245f208/touch/perfor
m {"actions":[{"action":"press","options":{"x":400,"y":347}},{"action":"wait","o
ptions":{"ms":1500}},{"action":"moveTo","options":{"x":600,"y":347}},{"action":"
release"}]}
info: [debug] Pushing command to appium work queue: ["swipe",{"startX":400,"star
tY":347,"endX":600,"endY":347,"steps":42}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action"
:"swipe","params":{"startX":400,"startY":347,"endX":600,"endY":347,"steps":42}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: swipe
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][768,1184]
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][768,1184]
info: [debug] [BOOTSTRAP] [debug] Swiping from [x=400.0, y=347.0] to [x=600.0, y
=347.0] with steps: 42
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessi
onId":"9702c04f-d142-4853-bf48-8dbfc245f208"}
info: <-- POST /wd/hub/session/9702c04f-d142-4853-bf48-8dbfc245f208/touch/perfor
m 200 723.874 ms - 76 {"status":0,"value":true,"sessionId":"9702c04f-d142-4853-b
f48-8dbfc245f208"}

**Comment by michaazran** [comment]
my X,Y were wrong, it is working :)
