### ISSUE TITLE
Appium vs TTTAttribuedLabel

### ISSUE THREAD

**Issue by Sergey-Kim** [appium/appium#4364]
Hi All.
I have an iPhone app that has elements of TTTAttribuedLabel class. Which are fully invisible for the Appium inspector. Is there anything i can do to interact with those elements? I'm using Appium 1.3.3 with 2.1.0 java bindings, xCode 6.1.1 with iPhone6 iOS 8.1 emulator.
https://github.com/TTTAttributedLabel/TTTAttributedLabel

**Comment by jlipps** [comment]
Unfortunately, no. Apple's UIAutomation framework unfortunately doesn't allow automation of custom UI controls. If you can mark your control _as_ a standard UI control from the accessibility perspective, it should then work (I'm not sure exactly how to do this)

**Comment by Sergey-Kim** [comment]
Just in case someone suffers from the same or similar problem: http://stackoverflow.com/questions/27843986/xcode-uiautomation-cant-interact-with-tttattributedlabel/27940550#27940550
