### ISSUE TITLE
support bluestack emulator

### ISSUE THREAD

**Issue by raynaya** [appium/appium#4366]
I am using bluestacks and launching the native android browser but when i am trying to navigateto a url I am getting the following exception - 

org.openqa.selenium.NoSuchWindowException: A request to switch to a different window could not be satisfied because the window could not be found. (WARNING: The server did not provide any stacktrace information)

The server log is as follows - 

> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/c9b9190806b769fd0ed1aaaab4510ecd","method":"GET"}
> info: [debug] Proxied response received with status 200: "{\"sessionId\":\"c9b9190806b769fd0ed1aaaab4510ecd\",\"status\":0,\"value\":{\"acceptSslCerts\":true,\"applicationCacheEnabled\":false,\"browserConnectionEnabled\":false,\"browserName\":\"chrome\",\"chrome\":{},\"cssSelectorsEnabled\":true,\"databaseEnabled\":false,\"handlesAlerts\":true,\"javascriptEnabled\":true,\"locationContextEnabled\":true,\"nativeEvents\":true,\"platform\":\"ANDROID\",\"rotatable\":false,\"takesHeapSnapshot\":true,\"takesScreenshot\":true,\"version\":\"\",\"webStorageEnabled\":true}}"
> info: <-- GET /wd/hub/session/c9b9190806b769fd0ed1aaaab4510ecd 200 8.183 ms - 463 
> info: --> POST /wd/hub/session/c9b9190806b769fd0ed1aaaab4510ecd/url {"url":"https://iq1.a.htm?c=2044375"}
> info: [debug] Proxying command to 127.0.0.1:9515
> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/c9b9190806b769fd0ed1aaaab4510ecd/url","method":"POST","json":{"url":"https://iq1.a.htm?c=2044375"}}
> info: [debug] Responding to client with error: {"status":23,"value":{"message":"A request to switch to a different window could not be satisfied because the window could not be found.","origValue":"no such window: window was already closed\n  (Session info: webview=)\n  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.1 SP1 x86_64)"},"sessionId":"c9b9190806b769fd0ed1aaaab4510ecd"}
> info: <-- POST /wd/hub/session/c9b9190806b769fd0ed1aaaab4510ecd/url 500 11.667 ms - 348 

But the browser windows is still open.

Appium Version - 1.3.4.1

**Comment by sebv** [comment]
Could you post full log?

**Comment by raynaya** [comment]
Server Log :  
info: --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"Appium","fullReset":"true","deviceName":"Android Emulator","platformName":"Android","browserName":"Browser"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
> warn: Converting cap fullReset from string to boolean. This might cause unexpected behavior.
> info: Set mode: Proxying straight through to Chromedriver
> info: [debug] Looks like we want chrome on android
> info: [debug] Creating new appium session 8751191d-46e3-4bce-b1fe-288c1bbe2a88
> info: [debug] Using fast reset? false
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device emulator-5554
> info: [debug] Setting device id to emulator-5554
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 wait-for-device
> info: [debug] executing cmd: C:\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 install "C:\Users\sray\Downloads\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: [debug] executing cmd: C:\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 push "C:\\Users\\sray\\Downloads\\AppiumForWindows-1.3.4.1\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Creating Chrome session
> info: [debug] Set chromedriver binary as: C:\Users\sray\Downloads\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] Ensuring Chromedriver exists
> info: [debug] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %b))
> info: [debug] No old chromedrivers seemed to exist
> info: [debug] Spawning chromedriver with: C:\Users\sray\Downloads\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] [CHROMEDRIVER] Starting ChromeDriver (v2.10.267521) on port 9515
> Only local connections are allowed.
> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"emulator-5554"}}}}
> info: [debug] Successfully started chrome session c9b9190806b769fd0ed1aaaab4510ecd
> info: [debug] Overriding session id with "c9b9190806b769fd0ed1aaaab4510ecd"
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId c9b9190806b769fd0ed1aaaab4510ecd
> info: <-- POST /wd/hub/session 303 6315.255 ms - 9 
> info: --> GET /wd/hub/session/c9b9190806b769fd0ed1aaaab4510ecd {}
> info: [debug] Proxying command to 127.0.0.1:9515
> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/c9b9190806b769fd0ed1aaaab4510ecd","method":"GET"}
> info: [debug] Proxied response received with status 200: "{\"sessionId\":\"c9b9190806b769fd0ed1aaaab4510ecd\",\"status\":0,\"value\":{\"acceptSslCerts\":true,\"applicationCacheEnabled\":false,\"browserConnectionEnabled\":false,\"browserName\":\"chrome\",\"chrome\":{},\"cssSelectorsEnabled\":true,\"databaseEnabled\":false,\"handlesAlerts\":true,\"javascriptEnabled\":true,\"locationContextEnabled\":true,\"nativeEvents\":true,\"platform\":\"ANDROID\",\"rotatable\":false,\"takesHeapSnapshot\":true,\"takesScreenshot\":true,\"version\":\"\",\"webStorageEnabled\":true}}"
> info: <-- GET /wd/hub/session/c9b9190806b769fd0ed1aaaab4510ecd 200 8.183 ms - 463 
> info: --> POST /wd/hub/session/c9b9190806b769fd0ed1aaaab4510ecd/url {"url":"https://iq1.m.dm/dp//a.htm?c=2044375&t=593143"}
> info: [debug] Proxying command to 127.0.0.1:9515
> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/c9b9190806b769fd0ed1aaaab4510ecd/url","method":"POST","json":{"url":"https://iq1.m.dm/dp//a.htm?c=2044375&t=593143"}}
> info: [debug] Responding to client with error: {"status":23,"value":{"message":"A request to switch to a different window could not be satisfied because the window could not be found.","origValue":"no such window: window was already closed\n  (Session info: webview=)\n  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.1 SP1 x86_64)"},"sessionId":"c9b9190806b769fd0ed1aaaab4510ecd"}
> info: <-- POST /wd/hub/session/c9b9190806b769fd0ed1aaaab4510ecd/url 500 11.667 ms - 348 
> info: [debug] Didn't get a new command in 60 secs, shutting down...
> info: Shutting down appium session
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 69.32
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] UiAutomator shut down normally
> info: [debug] Killing chromedriver
> info: [debug] Chromedriver exited with code null
> info: [debug] (killed by signal SIGTERM)
> info: [debug] executing cmd: C:\ADT\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s emulator-5554 shell "am force-stop com.android.browser"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Cleaning up appium session
> info: [debug] We shut down because no new commands came in

Exception : 
org.openqa.selenium.NoSuchWindowException: A request to switch to a different window could not be satisfied because the window could not be found. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30 milliseconds
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'IBM-SRAY-BL', ip: '192.168.0.107', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_55'
Session ID: c9b9190806b769fd0ed1aaaab4510ecd
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{platform=ANDROID, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={}, rotatable=false, locationContextEnabled=true, version=, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, nativeEvents=true, webStorageEnabled=true, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:304)
	at com.fiberlink.appium.AndroidWebViewTest.webView(AndroidWebViewTest.java:41)
	at com.fiberlink.appium.AndroidWebViewTest.main(AndroidWebViewTest.java:52)

**Comment by sebv** [comment]
I've tried with to go to `google.com` and it works, maybe it's windows specific issue. Could you try another site first?

**Comment by raynaya** [comment]
I tried for other sites and the issue still occurs. I think it is specific to blue stacks emulators native browser. It didn't happen with avd.

**Comment by sebv** [comment]
@0x1mason could you give it a check: 
This is bluestack emulator: http://www.bluestacks.com/
cc @bootstraponline

**Comment by sebv** [comment]
Investigate bluestacks emu support.

**Comment by jlipps** [comment]
this is probably not going to be a priority for a long time, if ever. closing.
