### ISSUE TITLE
android tests failing because appium's apidemos is crashing

### ISSUE THREAD

**Issue by jlipps** [appium/appium#4368]
Is anyone else experiencing this? @bootstraponline @0x1mason @imurchie 

Basically, certain appium tests try to start our apidemos with a certain activity (for example, `io.appium.android.apis/.app.StatusBarNotifications`). The app attempts to launch this activity, then it immediately crashes. Below is the logcat exception.

A number of tests are failing this way---the notifications tests and the touch action tests, most notably.

Adding to 1.3.5 since it seems like a pretty serious bug. I get it after a pull from master and a clean reset --dev --android so it seems legit.

```
E/AndroidRuntime( 3241): FATAL EXCEPTION: main
E/AndroidRuntime( 3241): Process: io.appium.android.apis, PID: 3241
E/AndroidRuntime( 3241): java.lang.RuntimeException: Unable to start activity ComponentInfo{io.appium.android.apis/io.appium.android.apis.app.StatusBarNotifications}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
E/AndroidRuntime( 3241):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
E/AndroidRuntime( 3241):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
E/AndroidRuntime( 3241):        at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime( 3241):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
E/AndroidRuntime( 3241):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3241):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 3241):        at android.app.ActivityThread.main(ActivityThread.java:5221)
E/AndroidRuntime( 3241):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3241):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 3241):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime( 3241):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/AndroidRuntime( 3241): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
E/AndroidRuntime( 3241):        at io.appium.android.apis.app.StatusBarNotifications.onCreate(StatusBarNotifications.java:54)
E/AndroidRuntime( 3241):        at android.app.Activity.performCreate(Activity.java:5933)
E/AndroidRuntime( 3241):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/AndroidRuntime( 3241):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
E/AndroidRuntime( 3241):        ... 10 more
W/ActivityManager( 1307):   Force finishing activity io.appium.android.apis/.app.StatusBarNotifications
```

**Comment by 0x1mason** [comment]
Does this include the cache change I made?

**Comment by jlipps** [comment]
No, it's from when I pulled this morning, I don't think you'd merged your change yet

**Comment by jlipps** [comment]
Seems like an error in apidemos, not sure who updated that last

**Comment by 0x1mason** [comment]
Yeah, I think something is seriously borked.

**Comment by bootstraponline** [comment]
maybe the api demos needs to be built using a higher API level sdk?

**Comment by bootstraponline** [comment]
relevant stackoverflows:

- http://stackoverflow.com/questions/18260170/nullpointerexception-at-onclicklistener
- http://stackoverflow.com/questions/21995264/attempt-to-invoke-virtual-method

api demos probably was broken in a commit that no one noticed since CI doesn't run the tests

**Comment by jlipps** [comment]
Yeah I dunno. I'm guessing it's something in the build process rather than ApiDemos code itself, since that code hasn't changed in a few releases

**Comment by jlipps** [comment]
Currently, the grunt helper builds ApiDemos at api level 19. But I was running on a level-19 emulator, so not sure why that wouldn't work.

**Comment by jlipps** [comment]
Still didn't work with a level-21 build. It's worth pointing out the problem exists independently of Appium. If you just build ApiDemos and try to navigate to the status bar notifications view, for example, it crashes.

**Comment by jlipps** [comment]
Actually scratch that---if you do a clean build from the apidemos repo itself, it works. So Appium is fubaring the build somehow

**Comment by jlipps** [comment]
Some more interesting info: if I use the version of ApiDemos I built by hand, and run the failing notification test against it, the test actually passes. But then if I run the whole suite, the test fails. There are two possibilities here:

1) Somewhere in the test suite we hard-uninstall the ApiDemos app and re-install the one Appium built (and that one is borked)
2) Somewhere in the test suite we do something that causes the app to not function correctly (like maybe the IME stuff that we install in the previous test)

**Comment by 0x1mason** [comment]
I can't repro this.  I'm using a 4.4 emulator that I start with
`-wipe-data`.  I run `./reset.sh --dev --android`.  Appium is running with
default options except for `--log-timestamp`.  Then I run `bin/test.sh
--android`.  `TapOut`, `unlock`, and the network connection details tests
flake, but otherwise everything passes.

**Comment by imurchie** [comment]
I can't repro it either. Everything other than the usual suspects pass.

**Comment by jlipps** [comment]
ok, good to know. i'm closing this then and assuming it's something with my env

**Comment by 0x1mason** [comment]
This did reappear.  It seems to be related to the fact we're not really doing clean builds, so that you can end up trying to use an old AndroidManifest to build an apk with incompatible changes.
