### ISSUE TITLE
add invisible elements to uiautomator2 page source

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#4369]
With some reflection magic, it's apparently possible to dump invisible elements. I'm not sure if they can be interacted with or not. Listing all elements (including invisible) would be useful for certain use cases. For example counting all elements without having to deal with scroll flakiness.

https://android.googlesource.com/platform/external/droiddriver/+/476f54bb2b1219b2a83960663860c76f172ba670/to-uiautomator.xsl

**Comment by bootstraponline** [comment]
I think droiddriver may make this possible since it has logic to dump invisible elements to xml.

**Comment by jlipps** [comment]
@bootstraponline what about uiautomator 2?

**Comment by bootstraponline** [comment]
@jlipps I wrote my own [view serializer](https://github.com/bootstraponline/view_to_uix) that has support for invisible elements since I needed this feature for work. It'd be easy to integrate invisible element support (at least for dumping) in the uiautomator v2 driver. uiautomator itself isn't going to be able to interact with invisible elements since it's limited by the accessibility layer. accessibility is only for user visible UI.

I'm not sure how useful it'd be to support dumping invisible elements if uiautomator can't do anything with them.

**Comment by jlipps** [comment]
ok, we'll leave this around as a uiautomator2 feature request

**Comment by KazuCocoa** [comment]
We can get invisible elements after set `allowInvisibleElements` by the following PRs.

- https://github.com/appium/appium-uiautomator2-driver/pull/76
- https://github.com/appium/appium-uiautomator2-server/pull/63
