### ISSUE TITLE
Add set `hw.battery=true` for emulators in test setup docs

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium#4374]
Or else the ApiDemos alerts tests don't work. Don't know why they didn't fail for me previously, but were failing today and this fixed it.

**Comment by 0x1mason** [comment]
@jlipps @sebv Is test/functional/android/apidemos/alerts-specs.js deprecated?  That might explain why I haven't run into this before.

**Comment by 0x1mason** [comment]
^These are the power tests.

**Comment by jlipps** [comment]
Hmm this is already documented somewhere I think

**Comment by jlipps** [comment]
Yeah, in /docs/en/appium-setup/android-setup.md

**Comment by 0x1mason** [comment]
k
