### ISSUE TITLE
get the IPAD SAFARI Browser cookies in java/js

### ISSUE THREAD

**Issue by spatchamatla** [appium/appium#4377]
Hi,

Can anyone let me know how i can get the IPAD SAFARI Browser cookies when running the selenium tests in IPAD using Appium Safari Launcher and ios-webkit-debug-proxy. I'm Running the tests on IPAD using IntelliJ on MAC.

Thank You,
Srujan.

**Comment by sebv** [comment]
Just check the specs, https://code.google.com/p/selenium/wiki/JsonWireProtocol, and your driver doc.
