### ISSUE TITLE
Replacement for '--quiet' argument

### ISSUE THREAD

**Issue by edgy360** [appium/appium#4378]
We have issues raised for Appium.app (https://github.com/appium/appium-dot-app/issues/419) and Appium.exe (https://github.com/appium/appium-dot-exe/issues/128) as to the `--quiet` argument being removed.

I checked the [documentation](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md), but it is unclear how to make the log 'quiet' from using `--log-level`. The only option appears to be `debug`?

**Comment by imurchie** [comment]
The [possible levels](https://github.com/appium/appium/blob/master/lib/server/parser.js#L160) for `--log-level` are:

```
'info', 'info:debug', 'info:info', 'info:warn', 'info:error', 'warn', 'warn:debug', 'warn:info', 'warn:warn', 'warn:error', 'error', 'error:debug', 'error:info', 'error:warn', 'error:error', 'debug', 'debug:debug', 'debug:info', 'debug:warn', 'debug:error'
```
