### ISSUE TITLE
Inspector screen is opened but show nothing

### ISSUE THREAD

**Issue by michaazran** [appium/appium#4381]
Hi

i am trying to open inspector on iOS application
i was not able to open the inspector when running the server from GUI so i ran the server from command line and i am trying to open the inspector from the GUI but inspector screen does not show the iphone screen

![image](https://cloud.githubusercontent.com/assets/4409879/5697308/79426b90-99f5-11e4-900d-6b00dbf96f86.png)

from the server log i do not get errors 
info: --> GET /wd/hub/session/8e764163-4337-4a6b-a7f6-c5f566374570/source {}
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: <-- GET /wd/hub/session/8e764163-4337-4a6b-a7f6-c5f566374570/source - - ms - - 
info: --> GET /wd/hub/session/8e764163-4337-4a6b-a7f6-c5f566374570/orientation {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: <-- GET /wd/hub/session/8e764163-4337-4a6b-a7f6-c5f566374570/orientation - - ms - - 
info: --> GET /wd/hub/session/8e764163-4337-4a6b-a7f6-c5f566374570/screenshot {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: <-- GET /wd/hub/session/8e764163-4337-4a6b-a7f6-c5f566374570/screenshot - - ms - - 
info: --> GET /wd/hub/session/8e764163-4337-4a6b-a7f6-c5f566374570/contexts {}
info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP"],"sessionId":"8e764163-4337-4a6b-a7f6-c5f566374570"}
info: <-- GET /wd/hub/session/8e764163-4337-4a6b-a7f6-c5f566374570/contexts 200 10.638 ms - 86 {"status":0,"value":["NATIVE_APP"],"sessionId":"8e764163-4337-4a6b-a7f6-c5f566374570"}

**Comment by 0x1mason** [comment]
If this is still an issue for you, please contact the appium-dot-app team on their repo. https://github.com/appium/appium-dot-app
