### ISSUE TITLE
Unable to launch Android Mms appcom.android.mms.ui.BootActivity

### ISSUE THREAD

**Issue by mayurkumarnara** [appium/appium#4383]
Hi,

I am getting error as "A new session could not be created. (Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity)"

Can anyone let me know what might go wrong here?Iam runnig on an Physical device.
Iam using appium version 1.2.4.1

DesiredCapabilities capabilities = new DesiredCapabilities();
//appassure.capabilities.SetCapability("app", "/system/priv-app/Mms.apk");
capabilities.SetCapability("appPackage", "com.android.mms.ui");
capabilities.SetCapability("appActivity", ".BootActivity" );

capabilities.SetCapability("deviceName", "Android");
capabilities.SetCapability("platformName", "Android");
capabilities.SetCapability("platformVersion", "4.4");
driver = new AppiumDriver(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities);

> info: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"appPackage":"com.android.mms.ui","appActivity":".BootActivity","deviceName":"Android","platformName":"Android","platformVersion":"4.4"}}[39m
> info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
> info: [debug] Creating new appium session efe35466-81dd-45aa-a585-5850f506b3c8
> info: Starting android appium
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from E:\Selendroid\platform-tools\adb.exe
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" devices
> info: [debug] 1 device(s) connected
> info: Found device 0123456789ABCDEF
> info: [debug] Setting device id to 0123456789ABCDEF
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF wait-for-device
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "echo 'ready'"
> info: [debug] Starting logcat capture
> warn: No app capability, can't parse package/activity
> info: [debug] Getting device API level
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: Device API level is: 19
> info: [debug] Apk doesn't exist locally
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "rm -rf /data/local/tmp/strings.json"
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Skipping install since we launched with a package instead of an app path
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF push "E:\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF install "E:\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF install "E:\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: E:\Selendroid\platform-tools\adb.exe -s 0123456789ABCDEF shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] tcp port:4724[39m
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window"
> info: [debug] Writing dumpsys output to E:\Appium\node_modules\appium\.dumpsys.log
> info: Unlocking screen
> info: [debug] Screen is locked, trying to unlock
> info: [debug] Getting device API level
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window"
> info: [debug] Writing dumpsys output to E:\Appium\node_modules\appium\.dumpsys.log
> info: [debug] Screen is locked, trying to unlock
> info: [debug] Getting device API level
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window"
> info: [debug] Writing dumpsys output to E:\Appium\node_modules\appium\.dumpsys.log
> info: [debug] Screen is unlocked, continuing
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
> info: [debug] Getting device API level
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.android.mms.ui/.BootActivity"
> error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
> info: [debug] [90m[UIAUTOMATOR STDOUT] [CDS]close[4724][39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] close [socket][/0.0.0.0:4724][39m
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] Time: 6.106[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] OK (1 test)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1[39m
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] UiAutomator shut down normally
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
>     at null.<anonymous> (E:\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:1143:21)
>     at null.<anonymous> (E:\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:172:9)
>     at ChildProcess.exithandler (child_process.js:635:7)
>     at ChildProcess.EventEmitter.emit (events.js:98:17)
>     at maybeClose (child_process.js:743:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity)","origValue":"Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity"},"sessionId":null}
> info: [37m<-- POST /wd/hub/session [39m[31m500[39m[90m 10728.478 ms - 346[39m [90m[39m
 
Regards
Mayur.

**Comment by mayurkumarnara** [comment]
I ran aapt dump badging Mms.apk command,from this i got the launchable activity path.Why Appium is not considering a .ui.BootActivity as a launchable activity
Below are the details
package:/system/priv-app/Mms.apk=com.android.mms

package: name='com.android.mms' versionCode='19' versionName='4.4.2' platformBui
ldVersionName=''
sdkVersion:'19'
application: label='Messaging' icon='res/mipmap-mdpi/ic_launcher_smsmms.png'
launchable-activity: name='com.android.mms.ui.BootActivity'  label='' icon=''
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-implied-permission: name='android.permission.READ_EXTERNAL_STORAGE' reason=
'requested WRITE_EXTERNAL_STORAGE'

**Comment by mayurkumarnara** [comment]
by mistake i closed it..sorry.

**Comment by mayurkumarnara** [comment]
When i changed appActivity also set to full path of activity com.android.mms.ui.BootActivity and appPackage set to com.android.mms ,then it is working,Can't it be fixed in appium,in case if it has not found launchable activity then retry with full path of activity?

DesiredCapabilities capabilities = new DesiredCapabilities();
//appassure.capabilities.SetCapability("app", "/system/priv-app/Mms.apk");
capabilities.SetCapability("appPackage", "com.android.mms");
capabilities.SetCapability("appActivity", "com.android.mms.ui.BootActivity" );

capabilities.SetCapability("deviceName", "Android");
capabilities.SetCapability("platformName", "Android");
capabilities.SetCapability("platformVersion", "4.4");

**Comment by jlipps** [comment]
You're sending in the wrong thing ('.BootActivity' is not a launchable activity---'.ui.Bootactivity' is). Try these instead:

> capabilities.SetCapability("appPackage", "com.android.mms");
> capabilities.SetCapability("appActivity", ".ui.BootActivity" );

**Comment by mayurkumarnara** [comment]
Hi,

 I HAVE TRIED IT ,App is successfully launched in the mobile but still i see exception in Appium server.

capabilities.SetCapability("appPackage", "com.android.mms");
capabilities.SetCapability("appActivity", ".ui.BootActivity" );

> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.android.mms/.ui.BootActivity"
> info: [debug] Waiting for pkg "com.android.mms" and activity ".ui.BootActivity" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing: "E:\Selendroid\platform-tools\adb.exe" -s 0123456789ABCDEF shell "dumpsys window windows"
> error: com.android.mms/.ui.BootActivity never started. Current: com.android.mms/.ui.ConversationList
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
> info: [debug] [90m[UIAUTOMATOR STDOUT] [CDS]close[4724][39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] close [socket][/0.0.0.0:4724][39m
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] Time: 21.977[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] OK (1 test)[39m
> info: [debug] [90m[UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1[39m
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] UiAutomator shut down normally
> error: Failed to start an Appium session, err was: Error: com.android.mms/.ui.BootActivity never started. Current: com.android.mms/.ui.ConversationList
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Error: com.android.mms/.ui.BootActivity never started. Current: com.android.mms/.ui.ConversationList
>     at null.<anonymous> (E:\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:1317:12)
>     at null.<anonymous> (E:\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:1259:7)
>     at null.<anonymous> (E:\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:172:9)
>     at ChildProcess.exithandler (child_process.js:635:7)
>     at ChildProcess.EventEmitter.emit (events.js:98:17)
>     at maybeClose (child_process.js:743:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: com.android.mms/.ui.BootActivity never started. Current: com.android.mms/.ui.ConversationList)","origValue":"com.android.mms/.ui.BootActivity never started. Current: com.android.mms/.ui.ConversationList"},"sessionId":null}
