### ISSUE TITLE
Android Real Device - Webview Not Visible

### ISSUE THREAD

**Issue by baclark77** [appium/appium#4384]
Executing a android test on a real device fails to find the webview context. The same test on an emulator finds the webview without issue. And the inspector sees the webview during the real device execution (screenshot attached).

Appium Version - 1.3.4

info: [debug] Creating new appium session 8510397e-cd46-4c07-aacc-532d4569e5d9
info: Starting android appium
info: [debug] Getting Java version

info: Java version is: 1.7.0_25

info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present

info: [debug] Checking whether adb is present
info: [debug] Using adb from /Applications/Test/android_adt/sdk/platform-tools/adb
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb devices

info: [debug] 1 device(s) connected

info: Found device a8e79692
info: [debug] Setting device id to a8e79692
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 60)
info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 wait-for-device

info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "echo 'ready'"

info: [debug] Starting logcat capture

info: [debug] Getting device API level

info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "getprop ro.build.version.sdk"

info: [debug] Device is at API Level 19

info: Device API level is: 19
info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "getprop persist.sys.language"

info: [debug] Current device persist.sys.language: en

info: [debug] java -jar "/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/Users/brandonclark/git/AppAuto-SportsCenter/main/src/test/resources/apppackages/sportscenter-release-4.1.3.apk" "/tmp/com.espn.score_center" en

info: [debug] No strings.xml for language 'en', getting default strings.xml

info: [debug] java -jar "/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/Users/brandonclark/git/AppAuto-SportsCenter/main/src/test/resources/apppackages/sportscenter-release-4.1.3.apk" "/tmp/com.espn.score_center"

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}

info: <-- GET /wd/hub/status 200 1.428 ms - 155 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}

info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 push "/tmp/com.espn.score_center/strings.json" /data/local/tmp

info: [debug] Checking whether aapt is present

info: [debug] Using aapt from /Applications/Test/android_adt/sdk/build-tools/android-4.2.2/aapt
info: [debug] Retrieving process from manifest.
info: [debug] executing cmd: /Applications/Test/android_adt/sdk/build-tools/android-4.2.2/aapt dump xmltree /Users/brandonclark/git/AppAuto-SportsCenter/main/src/test/resources/apppackages/sportscenter-release-4.1.3.apk AndroidManifest.xml

info: [debug] Set app process to: com.espn.score_center

info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Checking app cert for /Users/brandonclark/git/AppAuto-SportsCenter/main/src/test/resources/apppackages/sportscenter-release-4.1.3.apk.
info: [debug] executing cmd: java -jar /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/jars/verify.jar /Users/brandonclark/git/AppAuto-SportsCenter/main/src/test/resources/apppackages/sportscenter-release-4.1.3.apk

info: [debug] App already signed.

info: [debug] Zip-aligning /Users/brandonclark/git/AppAuto-SportsCenter/main/src/test/resources/apppackages/sportscenter-release-4.1.3.apk
info: [debug] Checking whether zipalign is present

info: [debug] Using zipalign from /Applications/Test/android_adt/sdk/build-tools/21.1.2/zipalign
info: [debug] Zip-aligning apk.
info: [debug] executing cmd: /Applications/Test/android_adt/sdk/build-tools/21.1.2/zipalign -f 4 /Users/brandonclark/git/AppAuto-SportsCenter/main/src/test/resources/apppackages/sportscenter-release-4.1.3.apk /var/folders/33/xf0ch4pd75qbhlq2gf2s58l40000gn/T/appium115012-89713-k0z4k7.tmp

info: [debug] MD5 for app is 6d16fbe2fbf24a61b4bf7a6e69709642

info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "ls /data/local/tmp/6d16fbe2fbf24a61b4bf7a6e69709642.apk"

info: [debug] Getting install status for com.espn.score_center

info: [debug] Getting device API level
info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "getprop ro.build.version.sdk"

info: [debug] Device is at API Level 19

info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "pm list packages -3 com.espn.score_center"

info: [debug] App is installed

info: App is already installed, resetting app
info: [debug] Running fast reset (stop and clear)
info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "am force-stop com.espn.score_center"

info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "pm clear com.espn.score_center"

info: [debug] Forwarding system:4724 to device:4724

info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 forward tcp:4724 tcp:4724

info: [debug] Pushing appium bootstrap to device...

info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 push "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/

info: [debug] Pushing settings apk to device...

info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/settings_apk/settings_apk-debug.apk"

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}
info: <-- GET /wd/hub/status 200 1.419 ms - 155 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}

info: [debug] Pushing unlock helper app to device...

info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"

info: Starting App

info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "ps 'uiautomator'"

info: [debug] No matching processes found

info: [debug] Running bootstrap
info: [debug] spawning: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap

info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1

info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1

info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724

info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] Waking up device if it's not alive
info: [debug] Pushing command to appium work queue: ["wake",{}]

info: [debug] [BOOTSTRAP] [debug] json loading complete.
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: wake
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "dumpsys window"

info: [debug] Screen already unlocked, continuing.

info: [debug] Pushing command to appium work queue: ["getDataDir",{}]

info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
info: [debug] dataDir set to: /data/local/tmp
info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy

info: [debug] Getting device API level
info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "getprop ro.build.version.sdk"
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}

info: [debug] Device is at API Level 19

info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.espn.score_center/com.espn.sportscenter.ui.LaunchActivity"

info: [debug] Waiting for pkg "com.espn.score_center" and activity "com.espn.onboarding.espnonboarding.EspnOnboardingActivity" to be focused

info: [debug] Getting focused package and activity
info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "dumpsys window windows"

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}
info: <-- GET /wd/hub/status 200 1.133 ms - 155 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}

info: [debug] Getting focused package and activity

info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "dumpsys window windows"

info: [debug] Device launched! Ready for commands

info: [debug] Setting command timeout to the default of 7200 secs
info: [debug] Appium session started with sessionId 8510397e-cd46-4c07-aacc-532d4569e5d9

info: <-- POST /wd/hub/session 303 11913.032 ms - 9 

info: --> GET /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9 {}

info: [debug] Responding to client with success: {"status":0,"value":{"platform":"MAC","browserName":"Android","platformVersion":"8.1","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platform":"MAC","platformVersion":"8.1","app":"/Users/brandonclark/git/AppAuto-SportsCenter/main/src/test/resources/apppackages/sportscenter-release-4.1.3.apk","deviceName":"Android Device","platformName":"Android","appActivity":"com.espn.sportscenter.ui.LaunchActivity","browserName":"Android","appWaitActivity":"com.espn.onboarding.espnonboarding.EspnOnboardingActivity","appPackage":"com.espn.score_center"},"app":"/Users/brandonclark/git/AppAuto-SportsCenter/main/src/test/resources/apppackages/sportscenter-release-4.1.3.apk","deviceName":"Android Device","platformName":"Android","appActivity":"com.espn.sportscenter.ui.LaunchActivity","appWaitActivity":"com.espn.onboarding.espnonboarding.EspnOnboardingActivity","appPackage":"com.espn.score_center"},"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}
info: <-- GET /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9 200 1.553 ms - 1082 {"status":0,"value":{"platform":"MAC","browserName":"Android","platformVersion":"8.1","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platform":"MAC","platformVersion":"8.1","app":"/Users/brandonclark/git/AppAuto-SportsCenter/main/src/test/resources/apppackages/sportscenter-release-4.1.3.apk","deviceName":"Android Device","platformName":"Android","appActivity":"com.espn.sportscenter.ui.LaunchActivity","browserName":"Android","appWaitActivity":"com.espn.onboarding.espnonboarding.EspnOnboardingActivity","appPackage":"com.espn.score_center"},"app":"/Users/brandonclark/git/AppAuto-SportsCenter/main/src/test/resources/apppackages/sportscenter-release-4.1.3.apk","deviceName":"Android Device","platformName":"Android","appActivity":"com.espn.sportscenter.ui.LaunchActivity","appWaitActivity":"com.espn.onboarding.espnonboarding.EspnOnboardingActivity","appPackage":"com.espn.score_center"},"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}

info: --> POST /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9/timeouts/implicit_wait {"ms":5000}

info: [debug] Set Android implicit wait to 5000ms
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}
info: <-- POST /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9/timeouts/implicit_wait 200 2.593 ms - 76 {"status":0,"value":null,"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}

info: --> POST /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9/element {"using":"name","value":"Sign In"}

warn: [DEPRECATED] The name locator strategy has been deprecated and will be removed.  Please use the accessibility id locator strategy instead.

info: [debug] Waiting up to 5000ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"name","selector":"Sign In","context":"","multiple":false}]

info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"name","selector":"Sign In","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding Sign In using NAME with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=Sign In, INSTANCE=0]

info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[TEXT=Sign In, INSTANCE=0]

info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"ELEMENT":"1"},"status":0}

info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}
info: <-- POST /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9/element 200 54.455 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}
info: --> GET /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9/element/1/displayed {}
info: [debug] Pushing command to appium work queue: ["element:getAttribute",{"elementId":"1","attribute":"displayed"}]

info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getAttribute","params":{"elementId":"1","attribute":"displayed"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getAttribute

info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"true","status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}
info: <-- GET /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9/element/1/displayed 200 28.090 ms - 76 {"status":0,"value":true,"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}

info: --> POST /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9/element/1/click {"id":"1"}
info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"1"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"1"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: click

info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}

info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}
info: <-- POST /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9/element/1/click 200 376.091 ms - 76 {"status":0,"value":true,"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}

info: --> POST /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9/timeouts/implicit_wait {"ms":0}

info: [debug] Set Android implicit wait to 0ms
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}
info: <-- POST /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9/timeouts/implicit_wait 200 0.964 ms - 76 {"status":0,"value":null,"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}

info: --> GET /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9/contexts {}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /Applications/Test/android_adt/sdk/platform-tools/adb -s a8e79692 shell "cat /proc/net/unix"

info: [debug] Available contexts: 

info: [debug] []
info: [debug] Available contexts: NATIVE_APP
info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP"],"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}
info: <-- GET /wd/hub/session/8510397e-cd46-4c07-aacc-532d4569e5d9/contexts 200 39.594 ms - 86 {"status":0,"value":["NATIVE_APP"],"sessionId":"8510397e-cd46-4c07-aacc-532d4569e5d9"}

![appium_inspector](https://cloud.githubusercontent.com/assets/5147624/5704797/a52e6fb8-9a42-11e4-833f-e0694d410364.png)

**Comment by wilcollins** [comment]
I am also unable to locate the webview context on an HTC One Max (emulator works as expected)

**Comment by imurchie** [comment]
Does the webview element have `setWebContentsDebuggingEnabled` set to true? Generally speaking, ChromeDriver can automate webviews on emulators without it, but not on real devices.

See https://developer.chrome.com/devtools/docs/remote-debugging#configure-webview

**Comment by baclark77** [comment]
This was indeed the issue! My dev team added the setting and all is well.

**Comment by sagarsheth27** [comment]
Hi In which platform I have to set this property "setWebContentsDebuggingEnabled". Either phone developers or FE developers?. Where to put it exactly.

**Comment by imurchie** [comment]
In your app code, when the WebView is created.

**Comment by sagarsheth27** [comment]
Hi

Means in automation code. Either I have to set capabilities or something
else. Can you please give me exact code.!

**Comment by sagarsheth27** [comment]
Ok thanks
