### ISSUE TITLE
Appium on Windows has undocumented dependency on MSVC/Visual Studio 

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium#4386]
socket.io and ws (possibly others) require MSVC compiler and libraries to build.  Even with VS and C++ libraries installed, the build does not always succeed.  I was not able to get the build working but since I didn't need websockets, I didn't put much effort into fixing the issue.  In my case, the linker couldn't find libcmt.lib, which is part of MS's C runtime.

Removing this dependency by providing pre-built binaries could be done at the same time as #4347.

**Comment by jlipps** [comment]
we removed the websocket dep
