### ISSUE TITLE
Error: EPERM, rename 'd:\Users\ltyao\AppData\Local\Temp\selendroid.com.demo.view.apk'

### ISSUE THREAD

**Issue by cosyman** [appium/appium#4390]
Hi,

I run two Appium server on one windows 7,and the apps under test are same,I copied it for each android device。my question is why give the selendroid server apk a solid name.maybe we can concatenate it with timestamp or current process id to avoid file writing competition

the following is details 

info: [debug] executing cmd: E:\sdk\sdk\build-tools\21.1.2\zipalign.exe -f 4 d:\Users\ltyao\AppData\Local\Temp\selendroid.ctrip.android.view.apk d:\Users\ltyao\AppData\Local\Temp\appium115013-7260-1x0cbxl.tmp
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: EPERM, rename 'd:\Users\ltyao\AppData\Local\Temp\selendroid.ctrip.android.view.apk'
info: [debug] Error: EPERM, rename 'd:\Users\ltyao\AppData\Local\Temp\selendroid.ctrip.android.view.apk'
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: EPERM, rename 'd:\\Users\\ltyao\\AppData\\Local\\Temp\\selendroid.ctrip.android.view.apk')","errno":50,"code":"EPERM","path":"d:\\Users\\ltyao\\AppData\\Local\\Temp\\selendroid.ctrip.android.view.apk","origValue":"EPERM, rename 'd:\\Users\\ltyao\\AppData\\Local\\Temp\\selendroid.ctrip.android.view.apk'"},"sessionId":null}
info: <-- POST /wd/hub/session 500 4670.269 ms - 409 
error: Logcat capture failed: spawn OK

**Comment by sebv** [comment]
Yeah that could be improved.

**Comment by sebv** [comment]
Moving to 1.4.

**Comment by punit-bisht** [comment]
I am also having same issue . version I am using is 1.4.7 .

**Comment by venustran** [comment]
I am facing issues with appium while running 2 android devices on 1 windows laptop
> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --bootstrap-port 5790 --nodeconfig C:\Users\venus\Downloads\json.json --platform-name Android --platform-version 19 --automation-name Appium --log-no-color
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","bootstrapPort":5790,"logNoColors":true,"platformName":"Android","platformVersion":"19","automationName":"Appium","nodeconfig":"C:\\Users\\venus\\Downloads\\json.json"}
> info: Console LogLevel: debug
> info: [debug] starting auto register thread for grid. Will try to register every 5000 ms.
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 22.810 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: [debug] Appium successfully registered with the grid on 127.0.0.1:4444
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 9.316 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 2.767 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Users\\venus\\Downloads\\udio.apk","VERSION":"4.4.4","deviceName":"Venus","platformName":"Android","BROWSER_NAME":"Android"}}
> info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.7.0_79)
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : VERSION, BROWSER_NAME
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from desired caps: C:\Users\venus\Downloads\udio.apk
> info: [debug] Creating new appium session f5102d8c-56f6-4718-98d5-139dcfac58d3
> info: Starting android appium
> info: [debug] Getting Java version
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"f5102d8c-56f6-4718-98d5-139dcfac58d3"}
> info: <-- GET /wd/hub/status 200 2.705 ms - 156 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"f5102d8c-56f6-4718-98d5-139dcfac58d3"}
> info: Java version is: 1.7.0_79
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\venus\AppData\Local\Android\sdk\platform-tools\adb.exe
> info: [debug] Parsing package and activity from app manifest
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\venus\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe
> info: [debug] Extracting package and launch activity from manifest.
> info: [debug] executing cmd: C:\Users\venus\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe dump badging C:\Users\venus\Downloads\udio.apk
> info: [debug] badging package: in.shmart.consumer
> info: [debug] badging act: in.shmart.consumer.ui.LauncherActivity
> info: [debug] Parsed package and activity are: in.shmart.consumer/in.shmart.consumer.ui.LauncherActivity
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\venus\AppData\Local\Android\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device c097e86
> info: [debug] Setting device id to c097e86
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\Users\venus\AppData\Local\Android\sdk\platform-tools\adb.exe -s c097e86 wait-for-device
> info: [debug] executing cmd: C:\Users\venus\AppData\Local\Android\sdk\platform-tools\adb.exe -s c097e86 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\venus\AppData\Local\Android\sdk\platform-tools\adb.exe -s c097e86 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: Device API level is: 19
> info: [debug] Extracting strings for language: default
> info: [debug] executing cmd: C:\Users\venus\AppData\Local\Android\sdk\platform-tools\adb.exe -s c097e86 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\venus\Downloads\udio.apk" "C:\Users\venus\AppData\Local\Temp\in.shmart.consumer" en
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"f5102d8c-56f6-4718-98d5-139dcfac58d3"}
> info: <-- GET /wd/hub/status 200 2.831 ms - 156 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"f5102d8c-56f6-4718-98d5-139dcfac58d3"}
> info: [debug] No strings.xml for language 'en', getting default strings.xml
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\venus\Downloads\udio.apk" "C:\Users\venus\AppData\Local\Temp\in.shmart.consumer"
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"f5102d8c-56f6-4718-98d5-139dcfac58d3"}
> info: <-- GET /wd/hub/status 200 2.241 ms - 156 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"f5102d8c-56f6-4718-98d5-139dcfac58d3"}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"f5102d8c-56f6-4718-98d5-139dcfac58d3"}
> info: <-- GET /wd/hub/status 200 2.373 ms - 156 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"f5102d8c-56f6-4718-98d5-139dcfac58d3"}
> info: [debug] Reading strings from converted strings.json
> info: [debug] Setting language to default
> info: [debug] executing cmd: C:\Users\venus\AppData\Local\Android\sdk\platform-tools\adb.exe -s c097e86 push "C:\\Users\\venus\\AppData\\Local\\Temp\\in.shmart.consumer\\strings.json" /data/local/tmp
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\venus\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe
> info: [debug] Retrieving process from manifest.
> info: [debug] executing cmd: C:\Users\venus\AppData\Local\Android\sdk\build-tools\23.0.2\aapt.exe dump xmltree C:\Users\venus\Downloads\udio.apk AndroidManifest.xml
> info: [debug] Set app process to: in.shmart.consumer
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Checking app cert for C:\Users\venus\Downloads\udio.apk.
> info: [debug] executing cmd: java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar" C:\Users\venus\Downloads\udio.apk
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"f5102d8c-56f6-4718-98d5-139dcfac58d3"}
> info: <-- GET /wd/hub/status 200 2.984 ms - 156 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"f5102d8c-56f6-4718-98d5-139dcfac58d3"}
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Users\venus\Downloads\udio.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\venus\AppData\Local\Android\sdk\build-tools\23.0.2\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\venus\AppData\Local\Android\sdk\build-tools\23.0.2\zipalign.exe -f 4 C:\Users\venus\Downloads\udio.apk C:\Users\venus\AppData\Local\Temp\116013-9128-31ki04\appium.tmp
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"f5102d8c-56f6-4718-98d5-139dcfac58d3"}
> info: <-- GET /wd/hub/status 200 1.873 ms - 156 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}},"sessionId":"f5102d8c-56f6-4718-98d5-139dcfac58d3"}
> warn: UiAutomator did not shut down fast enough, calling it gone
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: EPERM, rename 'C:\Users\venus\Downloads\udio.apk'
> info: [debug] Error: EPERM, rename 'C:\Users\venus\Downloads\udio.apk'
>     at Error (native)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: EPERM, rename 'C:\\Users\\venus\\Downloads\\udio.apk')","errno":-4048,"code":"EPERM","path":"C:\\Users\\venus\\Downloads\\udio.apk","origValue":"EPERM, rename 'C:\\Users\\venus\\Downloads\\udio.apk'"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 29376.041 ms - 304 
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 2.090 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 6.713 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 2.017 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 3.167 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 2.175 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 2.841 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 2.856 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 1.975 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 2.326 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 4.532 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 2.218 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 4.640 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 2.186 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 2.596 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 2.270 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: --> GET /wd/hub/status {}
> info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> info: <-- GET /wd/hub/status 200 3.181 ms - 105 {"status":0,"value":{"build":{"version":"1.4.16","revision":"ae6877eff263066b26328d457bd285c0cc62430d"}}}
> Killed Node Server.
> Appium server process ended


GIving me EPERM error

**Comment by jlipps** [comment]
I believe this has been fixed in Appium 1.5
