### ISSUE TITLE
Missing .appiumconfig.json file and Unrecognized arguments: configure.

### ISSUE THREAD

**Issue by GokhanArik** [appium/appium#4391]
I installed Appium using npm on a Mac device, I am trying to run Appium and I'm getting "Missing .appiumconfig.json" error.

It tells me to run reset.sh or appium configure command. I know npm distrubution doesn't need reset.sh file, so I tried to run appium configure but there is no command in appium like that.

I checked similar posts, they recommend to uninstall and install again. I did but the result is the same.

Thanks

**Comment by imurchie** [comment]
What version are you trying to run?

**Comment by GokhanArik** [comment]
Latest version. npm installs latest version right? I just did `npm install -g appium`. It is 1.3.4

**Comment by GokhanArik** [comment]
It is funny it works now. Yesterday I uninstalled and deleted 4 times and I was getting same error. I did it again and now it works. I don't know if you guys released any minor version between yesterday and today.

**Comment by imurchie** [comment]
Nothing was changed between then and now. Not sure what the problem was (but it works for me at the moment, too).

**Comment by GokhanArik** [comment]
That's really strange. I'm closing ticket now.
