### ISSUE TITLE
Screen recording feature

### ISSUE THREAD

**Issue by thebeekeeper** [appium/appium#4395]
I'm interested in adding commands to start and stop a screen recording.  Something like this:

    rest.put('/wd/hub/session/:sessionId?/start_recording', controller.startRecording);
    rest.put('/wd/hub/session/:sessionId?/stop_recording', controller.stopRecording);

Which would launch the screen_recording app with the platform that the session is currently running on (ios/android).  The stopRecording method would probably return the path to the saved video file.

How likely would it be for a pull request with this feature to be accepted?  I'd rather not maintain my own branch, and I can figure out something else if this feature wouldn't be accepted.

**Comment by jlipps** [comment]
Interesting idea. I don't see why I wouldn't accept something like this. Here are some concerns though:

1. for Android it would need to work on Linux, Windows, and Mac. Is there one screencap package that works this way?
2. I wouldn't want to add a crazy build step to Appium's install. Is there a package that works on all systems without additional config? (I.e., a binary that "just works")

Oh, and the endpoints should look like:

```
/wd/hub/session/:sessionId?/appium/start_recording
```

(behind the appium namespace)

Thoughts from others? @0x1mason @bootstraponline

**Comment by 0x1mason** [comment]
I'm open to it.  My biggest concerns are the additional maintenance overhead and the complexity of any dependencies.  If it's not going to make things a lot more complicated, then I think it'd be a nice feature.

**Comment by bootstraponline** [comment]
As of API 19, android offers built in screen recording using [adb shell screenrecord](http://developer.android.com/tools/help/adb.html). This is built into the platform and works across operating systems.

Apple [added something similar](https://developer.apple.com/app-store/app-previews/) in iOS 8. There's also the [airplay approach](http://www.airsquirrels.com/reflector/) which can be comboed with standard desktop [screen recording](https://github.com/appium/screen_recording). 

Some projects even send screenshots over the wire and then encode them into a video on the host computer.

**Comment by jlipps** [comment]
The main alternative to this approach is to build language-specific wrappers for these tools that can be mixed into appium test code, but exist as an independent project. Not sure if that makes the overall usage more or less complex.

**Comment by bootstraponline** [comment]
I think the screenrecord command would fit nicely into [appium-adb](https://github.com/appium/appium-adb). iOS seems significantly more complicated due to the lack of an open API.

**Comment by 0x1mason** [comment]
Encoding is the type of thing I'd rather avoid ftm, but if we're wrapping
extant features and we can hand off the stream to the client and forget
about it, then that sounds good to me.

The short version is, if we're just proxying video streams then I'm for it,
but if we're assuming responsibility for de/encoding, then I'm hesitant. If
thebeeguy wants to own it long term, then I'm less hesitant.

On Jan 15, 2015 5:25 PM, "Jonathan Lipps" <notifications@github.com> wrote:
>
> The main alternative to this approach is to build language-specific
wrappers for these tools that can be mixed into appium test code, but exist
as an independent project. Not sure if that makes the overall usage more or
less complex.

**Comment by bootstraponline** [comment]
Another idea for old Android versions < API 19 (which don't support screenrecord via adb) is to use VNC and then record that.

**Comment by 0x1mason** [comment]
I think my short version is longer than the not short version.

**Comment by 0x1mason** [comment]
If its going to be something like vnc, then I think we should probably
provide proxying for it and then document how to do it, but not take on
responsibility for offering it.

Anyway, interested to hear more on what thebeechap has in mind.

**Comment by thebeekeeper** [comment]
Wow, I didn't expect such a rich discussion in response to this.  I'd only gotten as far as how it would work for my use case - iOS on a mac, so the existing screen recorder would work just fine.  I've done a tiny bit of research on open source screen recorders, but haven't found anything that looks like it could be a single binary that works on all platforms. 

I like the idea of delegating the recording to an existing app, and nothing happening if you don't set it up right.  To make sure I understand this, is this a valid approach:
 - Client sends request to start_recording
 - Appium tries calling some command to record the active window, returns a 200 status code if it's able to start a recording, returns some error if it can't
 - Client runs test
 - Client sends request to stop_recording
 - Appium either returns video file location/binary data if recording was successful, and an error if it's unsuccessful

**Comment by bootstraponline** [comment]
Cross platform desktop capture is kind of difficult because the APIs aren't the same. [chrome remote desktop](http://src.chromium.org/viewvc/chrome/trunk/src/remoting/host/shaped_desktop_capturer.cc?revision=289020) uses webrtc. It looks like they've figured out how to screen record windows across win/mac/linux plus it's open source.

**Comment by 0x1mason** [comment]
@thebeekeeper How does the existing solution work on iOS?

**Comment by thebeekeeper** [comment]
@0x1mason I don't have an existing solution on iOS at this point.  I was planning to just write a node server to start the Appium screen_recording app based on client commands if nobody was interested in adding this feature to Appium.

**Comment by 0x1mason** [comment]
Sounds like we're all open to supporting an API for this.  As to how we support the endpoint solutions, I think depends on what you work out for iOS.  My 5 seconds of research didn't turn up any obvious ways to start a recording externally.  Recording on Android 4.4+ is super simple, so we don't need to worry too much about a cross platform solution.

Can you get back to us with some ideas on how the iOS part might work and then we'll start figuring out how to put all the pieces together?  Something along the lines of "QuickTime exposes the Foo command that Appium can invoke from the command line."

**Comment by thebeekeeper** [comment]
Yep, I'm currently researching on a good way to do it for iOS.  If I can get my dev environment set up I should have something within a few days.

**Comment by 0x1mason** [comment]
Awesome.  A couple of us stumbled on this independently, so you may have
too, but if not, might be helpful.
https://github.com/coolstar/RecordMyScreen

**Comment by penguinho** [comment]
GOOD NEWS!
Yosemite includes iphone screen recording support in Quicktime. Just create a new movie recording and select the video input source as the connected iPhone.

BAD NEWS!
The applescript support for this in quicktime is totally broken. You cannot change the video recording source as far as I can tell.

**Comment by penguinho** [comment]
I'm currently looking in to doing it with AVFoundation where in theory this functionality exists somewhere.

**Comment by penguinho** [comment]
https://gist.github.com/FriendlyTester/67c7ad26ab62849aea91

**Comment by phamhiepst** [comment]
Thank you so much :)

-----Original Message-----

**Comment by jlipps** [comment]
added to the 'features' bucket

**Comment by bootstraponline** [comment]
this [open source](https://github.com/espes/Slave-in-the-Magic-Mirror) air play implementation could be used for physical iOS screen recording.

**Comment by jlipps** [comment]
After mulling this over more, I think the right approach is to link to various screen recording solutions and allow users to implement it client-side (perhaps sharing frameworks). It seems like a very complex set of features (ios, android, multi-platform, sim + real device, etc...) to support.

**Comment by bootstraponline** [comment]
sounds good, I agree it's very complex.
