### ISSUE TITLE
Cant change to the correct webview context

### ISSUE THREAD

**Issue by BarTsouri** [appium/appium#4398]
Hi,

My app has multiple webviews, and I need to choose the one in the foreground for testing. I thought about iterating through all the webviews and retrieving the url from each one, checking if it matches the one I need.

The problem is that I could find any method to get the webview's URL.

If anyone has an idea how to solve it, even in alternative ways I will be so glad.

Thanks in advance.

**Comment by imurchie** [comment]
You need to go into the webview context and then use the Selenium method for getting the current url, in whatever language you are using (e.g., in Python this is `driver.current_url`, in Java, `driver.getCurrentUrl();`).

**Comment by BarTsouri** [comment]
I get an exception: TypeError: Object #<Object> has no method 'getCurrentUrl'

var driver = require('wd');
describe('sanity', function(){

it('should change to one of the webviews', function(){
        driver.contexts().then(function (contexts) {
            console.log(contexts);
            driver.context(contexts[2]);
        });
    });

var url;
it('should give the current url', function(){
    url = driver.getCurrentUrl(); // exception is thrown
});
});

**Comment by imurchie** [comment]
What is `contexts[2]`? Are you sure it is a webview? Also, can you put the server log in a [gist](https://gist.github.com/) and link it here?

**Comment by BarTsouri** [comment]
I am sure that it is a webview, when I print the contexts array it has the substring webview in it.

I forgot to mention that I use Protractor for running Appium, and they said that I should approach you with the problem.

Attached a gist with all the relevant information.
https://gist.github.com/anonymous/b3f40698c3a4a470e410

**Comment by jlipps** [comment]
you're looking for `driver.url()` if you're using wd.js (which it looks like you are?)
