### ISSUE TITLE
Appium extremely unstable with iOS 7.1 Simulator

### ISSUE THREAD

**Issue by amake** [appium/appium#4399]
I am experiencing an issue where Appium is unusable with the iOS 7.1 Simulator.

Environment: Appium 1.3.4, OS X 10.10.1, Xcode 6.1.1

Basically Appium will successfully launch and communicate with my app *exactly once*, and then will fail on all subsequent launches. This only happens with the iOS 7.1 Simulator, not with the iOS 8.1 Simulator, which always works. It even happens even in a cleanly installed Yosemite VM.

The app itself works just fine on iOS 7.

Here is a typical failure log:
~~https://gist.github.com/amake/cc8c0859d0b544e78d14~~
https://gist.github.com/amake/b0e6776f69ab2fc2a9d2 (Appium 1.4; SHA: 42aca68)

(I did post about this on appium-discuss, but have not yet gotten any responses: https://discuss.appium.io/t/unable-to-launch-ios-7-1-simulator-test-with-xcode-6/2398)

If other people are having no issues with the same environment, then any diagnostic advice would be much appreciated.

**Comment by jlipps** [comment]
I'm curious what happens if you try the Xcode 6.2 beta?

**Comment by amake** [comment]
@jlipps Good question. Xcode 6.2b4 with iOS 8.1 Simulator works fine, but the iOS 7.1 Simulator still fails. The reported errors are different, though:
https://gist.github.com/amake/668d46a843a42b74fc5b

**Comment by jlipps** [comment]
what happens if you use --native-instruments-lib

**Comment by amake** [comment]
@jlipps I did try that as well. Unfortunately the results are the same as without that arg.

**Comment by sebv** [comment]
Is it still happening with latest appium?

**Comment by amake** [comment]
I just tested with the latest Appium (42aca68) and Xcode 6.3.2. I'm not sure if it's exactly the same issue as before, but I am still unable to get Appium to successfully manipulate my app when using the iOS 7.1 Simulator (the 8.2 simulator is fine).

Log:
https://gist.github.com/amake/b0e6776f69ab2fc2a9d2

**Comment by jlipps** [comment]
maybe xcode 6.3 changed the way alert handling code is supposed to work? @sebv can you repro? does ios 7.1 + xcode 6.3 work?

**Comment by Jonahss** [comment]
I ran the alert tests for appium v1.4.6 on  ios 7.1 simulators using xcode 6.3.2 on yosemite. they passed.
https://github.com/appium/appium/blob/master/test/functional/ios/uicatalog/alerts-specs.js

@amake any reason those tests would pass but you see a failure?

**Comment by amake** [comment]
Sorry, I did not have time to investigate any more into this. It is officially moot for me, however—we have dropped iOS 7 support entirely.

Thanks for everyone's time and efforts with this issue.
