### ISSUE TITLE
Appium Multiple Elements Were Found when Instruments only shows one!

### ISSUE THREAD

**Issue by fwaraich78** [appium/appium#4403]
Appium versions reproduced on: 1.3.3 & 1.3.4 (didn't try 1.3.2)
There is one unique name/id for the element that I'm using ("ABC").  But when using appium inspector it shows 2 elements found, this is on iOS v8.1, device iPhone 6 -see message below:

"Multiple Elements Were Found
2 elements were found using the locator value "ABC" and the locator strategy "id"

I also checked in Instruments by dumping the app log and confirmed only one unique value "ABC" exists.  Can anyone please help in this or point me to a bug if one exists for appium?  Because of this our tests are failing, each run makes a different test fail.

I'd appreciate any help on this!

**Comment by bootstraponline** [comment]
Are you checking each one to see if they are visible or not?

**Comment by fwaraich78** [comment]
Hi,

visible shows up as 'false'.  Here is the something interesting:

Appium version: 1.3.4
iphone 6 > 8.1 >>> 2 elements found
iphone 6 plus > 8.1 >>> 2 elements found
iphone 5s > 8.1 >>> 2 elements found
iphone 5 > 8.1 >>> 1 found!! (for this visible also shows 'false')

Thanks for your help!

**Comment by stevechun** [comment]
I'm having this issue as well. It happens randomly, 3 elements found sometimes.

**Comment by sukh48** [comment]
same issue on tableViewController cells...has anyone come up with a solution yet?

**Comment by moizjv** [comment]
@fwaraich78 can you paste appium logs? And also if possible steps to reproduce?

**Comment by sebv** [comment]
Closing, no, activity, please continue discussion in https://discuss.appium.io/

**Comment by nootfly** [comment]
the same issue on 1.4.8

**Comment by PeymanEshtiagh** [comment]
I am also having this issue, is there a work around?

**Comment by OdysseyUA** [comment]
Same issue (1.6). Does any way to select concrete element from multiple elements?
