### ISSUE TITLE
Android:  Element.displayed? still picking up non-visible items

### ISSUE THREAD

**Issue by shermanericSF** [appium/appium#4404]
Device:
Samsung Galaxy S4
OS 4.4
Appium Version: 1.3.3  ( i can try with 1.3.4, but didn't see anything in the release notes for 1.3.4 that addressed this)
Also tried this with arc.

Steps to Reproduce:
=================
1. I sign into my app under test.
2. The app shows courses grouped by terms
3. You use the arrows to swipe between previous and future terms

*Expected*:  When I swipe through the previous terms, at some point I'm at the oldest term, no "previous" (left ) arrow should be displayed, and .displayed? should return false
*Actual*:  All of the expected events happen, except that in this case .displayed? still returns TRUE.

More information
===============
I have something like this:
```
@previous_term_arrow = {id: "com.blackboard.android.bbstudent:id/sibling_header_left_arrow"}
And a method like this:

def click_to_oldest_term()
         while (find_element(@previous_term_arrow).displayed? )
          wait {find_element(@previous_term_arrow).click }
         end
      end
```
Expected:   @previous_term_arrow equals true, then false at the oldest term of courses.
Actual:  @previous_term gets into an endless loop, always returning true.

Screen shot attached.  Note that appium inspector indeed correctly views the "missing" arrow correctly as visible: false.  It's just that .displayed? returns true in this situation.

Let me know if you need any other information.
Thanks!
Eric

![2cde0a10f4_690x487](https://cloud.githubusercontent.com/assets/10579118/5791078/e4cf7b38-9e6d-11e4-84ed-00bc9aeca81e.png)

**Comment by bootstraponline** [comment]
It'd be great to have the server logs in a [gist](https://gist.github.com). Are you using Selendroid mode or uiautomator?

**Comment by bootstraponline** [comment]
Also another thing to check, what does uiautomatorviewer report about the element?

**Comment by bootstraponline** [comment]
> ( i can try with 1.3.4, but didn't see anything in the release notes for 1.3.4 that addressed this)

On master, we recently had a [patch](https://github.com/appium/appium/pull/4365) for uiautomator that may help. It's not currently in a released version so you'd have to [run from source](https://github.com/appium/appium/blob/96dc94037c3f5747d173f6bc6e3abe249026090d/docs/en/contributing-to-appium/appium-from-source.md).

**Comment by bootstraponline** [comment]
I'm guessing you're using selendroid as I don't see [visible](https://github.com/testobject/android-testing/blob/f9b3351f18ae617ea4debddce931a9381ab76a4c/uiautomator/library/core-src/com/android/uiautomator/core/AccessibilityNodeInfoDumper.java#L101) in uiautomator. This is fixed in [selendroid 0.13.0](https://github.com/selendroid/selendroid/commit/efdfda8fdf99142442645e7e33e07e85a06d2a00) which will be in the next release of appium.

**Comment by shermanericSF** [comment]
Hi Bootstraponline.  It's Definiitely with UIAutomator.  Here's the gist.  I'll try running now on master source.  Note to save time, I'm providing the arc trace which hopefully suffices.  Let me know what else you need.
Thanks!
Eric
https://gist.github.com/shermanericSF/b2de67f127b824f73db2#file-issue4404_line206_returns_true_should_be_false

**Comment by bootstraponline** [comment]
Thanks for the logs. [For uiautomator](https://github.com/appium/appium/blob/bdb8221d18b6edadb2c39a450fc3b11a5c58008a/lib/devices/android/bootstrap/src/io/appium/android/bootstrap/AndroidElement.java#L101), we're calling the [exists() method](http://developer.android.com/tools/help/uiautomator/UiObject.html#exists()) in response to the displayed request which looks correct to me.

I'm not sure where `visible: false` is coming from. Tracking that down will probably resolve this issue.

**Comment by shermanericSF** [comment]
Thanks for the quick responses, @bootstraponline ! What you say makes sense.

For what it's worth, I ran ./reset.sh and re-ran appium from source. Ran the same arc test as above and got the same result. Let me know if you need more info. Thanks!

**Comment by bootstraponline** [comment]
I think we have all the info required to identify the problem. Thanks for reporting the issue!

**Comment by shermanericSF** [comment]
awesome, thanks!

**Comment by bootstraponline** [comment]
Unfortunately it looks like I've solved the mystery. Appium.app incorrectly calculates the visibility property. Instead of checking for visible, they're using the clickable attribute. 

- https://github.com/appium/appium-dot-app/blob/ef1d051ddeab736cad9bc10268a5c8e7bf766a47/Appium/Inspector/WebDriverElementNode.m#L43

If you try with `uiautomatorviewer` (a tool by Google which is specifically engineered to work with uiautomator), I'd expect that visible doesn't show up at all. By default, uiautomator only returns viewable nodes. The "fix" in this case is to check if the element is `clickable`.

**Comment by bootstraponline** [comment]
Fixed upstream: https://github.com/appium/appium-dot-app/pull/448

**Comment by shermanericSF** [comment]
Thanks so much @bootstraponline and @penguinho for the quick responses!  I'll try master out.
Just curious, if I wanted to check for the .clickable? property in find_element, I don't see one offhand in ruby.
Is there a way to execute_script on android?  Or should I do a try/catch?  
Thanks again for everything.  you can keep this ticket closed.  more of a question

**Comment by bootstraponline** [comment]
@shermanericSF I'll try and figure out the method call, it will work in any appium version. It's probably something like element.attribute('clickable')

**Comment by bootstraponline** [comment]
@shermanericSF ok, it's like this:

```ruby
# find element, see if it's clickable
find_element(:accessibility_id, 'Animation').attribute('clickable') == 'true'

**Comment by shermanericSF** [comment]
Thanks so much!! Will give it a try later. Yeah open-source!
