### ISSUE TITLE
How to call a native method of an app's codebase [IOS/Android] from appium script

### ISSUE THREAD

**Issue by p00j4** [appium/appium#4405]
I'm wondering if there is any way to call a native function of the app from Appium script
Ex. in IOS I want to invoke "[[OptionsVC sharedInstance] accountTapped:nil];" ,
had given a wild try with Javascript but looks like its not designed to act on IOS/Android code
Is there any other Strategy or instruments command which can make it work !

**Comment by penguinho** [comment]
Apple's UIAutomation framework does not support this. Since Objective C is a compiled language and not an interpreted one, I don't think there's a way to add this even with a framework that requires you to modify the app.

You'd have to add invisible items to your app that when interacted with triggered the code.

**Comment by p00j4** [comment]
thanks @penguinho for the info, having invisible item was on my mind but is the worst option since dev build has to be modified in many screens.
well, I how to do -' have an HTTP server in the app' !

**Comment by penguinho** [comment]
You would need the developers to add a HTTP server that you can call from your tests that when you call a specific URL it would run the command you want.

**Comment by p00j4** [comment]
thanks @penguinho

**Comment by jstawski** [comment]
Hello, wondering if this is still the case. Xamarin UI Test allows you to do so: https://developer.xamarin.com/guides/testcloud/uitest/working-with/backdoors/

**Comment by imurchie** [comment]
Yes, it is still the case. Xamarin builds into your app so it can do so. Appium has no access to anything other than the UI of your app.
