### ISSUE TITLE
Observed error while running appium with latest codebase "96dc94037c3f5747d173f6bc6e3abe249026090d"

### ISSUE THREAD

**Issue by priyankshah217** [appium/appium#4407]
Hi All,

I have same script running in two devices API17 and API 19 respectively in Appium mode, but while running same script in device with API 17, it got error. however as it installs application.

Please find attached server logs.
https://gist.github.com/priyankshah217/ef5ac27e820866bc8f77

Thanks,
Priyank Shah

**Comment by jlipps** [comment]
@priyankshah217 do you still see this issue? if so, which caps are you using for the failing test?

**Comment by priyankshah217** [comment]
Hi Jonathan,

You can close this now.

Thanks,
Priyank
