### ISSUE TITLE
Android native test on Samsung Galaxy S5 with 4.4 text field showing different value

### ISSUE THREAD

**Issue by pamepros** [appium/appium#4410]
When filling an input with a value of "Name" and asking for the value of the text field, the returning value shows "Name. Double tap to edit"
This are the commands:
`textfields = self.find_elements_by_tag_name("textfield")`
`textfields[0].send_keys("Name")`
`self.assertEqual(textfields[0].text, "Name")`

Getting:
`Returning result: {"value":"Name. Double tap to edit.","status":0}`

But on the device screen I see the value 'Name' in the text field.

**Comment by moizjv** [comment]
@pamepros can you please send appium log. But looks like its returning hint text

**Comment by sebv** [comment]
Didn't we fix that? cc @paymand.

**Comment by paymand** [comment]
Hard to tell. The log may be helpful.

**Comment by dman009** [comment]
Has this been fixed? Currently getting the same thing on real Samsung Galaxy device. Using Appium 1.5.3
