### ISSUE TITLE
Your NPM version is not matching

### ISSUE THREAD

**Issue by thevinci** [appium/appium#4413]
Also you should specify that you require Android API19 to run the install.sh.

**Comment by jlipps** [comment]
what do you mean when you say the NPM version is not matching?

**Comment by sebv** [comment]
Please provide more details.

**Comment by thevinci** [comment]
appium@beta is supposedly the latest master branch, yes? i also switched to appium@1.3.4. when i checked out version 1.3.4 from npm, i noticed that chromeoptions is missing from the source and the build. so i had to drag the files from master and manual rebuild them. 1.3.4 is NOT 1.3.4 as in your github branch.

**Comment by sebv** [comment]
appium@beta is not the latest master branch. It's what we test before releasing.

 The commit for 1.3.4 tag is correct: c8c79a85fbd6870cd6fc3d66d038a115ebe22efe. But you need to use the tag, not the branch.

**Comment by sebv** [comment]
Closing, reopen if needed.
