### ISSUE TITLE
How to swipe on iOS simulator using appium ?

### ISSUE THREAD

**Issue by astgh** [appium/appium#4415]
Hello guys. I am trying to swipe a screen, but I don't know how to do ? I used the code generated by appium, also tried some other codes found in internet, but nothing worked (through in general I see my test ran, but swipe didn't happen). Can someone tell me how to do it ? Or is it possible to do ? Thanks in advance.
btw I write on Java, use Appium 1.3.4, intelliJ 14.

**Comment by 0x1mason** [comment]
https://discuss.appium.io/t/java-client-2-1-0-released/1462

If you have further questions on implementation, please ask the Discuss community.  Thanks for using Appium!
