### ISSUE TITLE
Different Locating by id (ressource-id) with Appium and Selendroid

### ISSUE THREAD

**Issue by mgehlen** [appium/appium#4416]
Hello all,

I want to use Appium to automate an App, which is developed for iOS and Android.
Regarding Android the App has several small webviews included and supports Android versions back to 2.3.7. 
Since most users aren't on Android 4.4 I need to use Selendroid to test most of the configurations. When time goes by our users will migrate their Android versions and I can switch to Appium completely.

I know there are differences in locating elements in Selendroid and Appium, for example different nodes when using xpath. What strikes me as odd is that Appium and Selendroid differ when trying to locate elements by ID.

Here is and example (using Java, PageFactory and Annotations)

Here is *Appium*:
```
@AndroidFindBy(id = "de.myApp.client.android:id/welcome_button_login")
private MobileElement btn_Login ;
```

And here is *Selendroid*:
```
@AndroidFindBy(id = "welcome_button_login")
private MobileElement btn_Login ;
```
I personally prefer the way Selendroid does it, because it locates by the specified ID only and not by the complete package and id name. This makes my life easier especially since our app is shipped to different countries and sadly with different package names (e.g. fr.myApp.client.android or es.myApp.client.android). 

Therefore my question is:

Is there a reason why Appium does not locate by the ID alone but needs the whole package name or will this be changed in a future release?

Thank you very much,

  mgehlen

**Comment by esoests** [comment]
I guess that's how appium suport multiple apps but selendroid only works under one app.

**Comment by mgehlen** [comment]
Hello esoests,

thank you very much for your quick reply.

I think it is the other way around that Selendroid is able to support multiple apps regarding ID locating, not Appium.  

In my case with three Apps using different package names but the same ID for the login button in Appium I have to write the locating by ID something like this:

````
   @AndroidFindAll({@AndroidFindBy(id = "de.myApp.client.android:id/welcome_button_login"),
                    @AndroidFindBy(id = "fr.myApp.client.android:id/welcome_button_login"),
                    @AndroidFindBy(id= "es.myApp.client.android:id/welcome_button_login")})
````
So one identification strategy for each country App.

In Selendroid on the other hand I am able to identify the login button regardless of the app package by strictly asking for the defined ID only:

````
@AndroidFindBy(id = "welcome_button_login")
private MobileElement btn_Login ;
````

So in Appium I have to Add a locating strategy for each country App. In Selendroid I have one strategy, which identifies the button across all my App versions regardless of the country.

This is why I prefer the solution implemented by Selendroid.

Am I missing something?

Thank you very much,

  Marcel

**Comment by jlipps** [comment]
Does this not work?

```java
@AndroidFindBy(id = "android:id/welcome_button_login")
private MobileElement btn_Login ;
```

I thought it would. And if it does, then it'd be easy to write a locator function that gives you the right locator based on whether you're in a selendroid or appium session.

**Comment by mgehlen** [comment]
Hello jips,

thank you for your answer - sadly it does not work. I get a NoSuchElementException, which I don't get with the complete package.

Here is my current usage:

````
    @AndroidFindAll({@AndroidFindBy(id = "de.payback.client.android:id/welcome_button_login"),
                     @AndroidFindBy(id = "welcome_button_login")})
    private MobileElement btn_Login ;
````

And here is my StackTrace:

````
org.openqa.selenium.NoSuchElementException: Cann't locate an element by this strategy: By.all({By.id: android:id/welcome_button_login,By.id: welcome_button_login})
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
System info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.7.0_60'
Driver info: driver.version: unknown
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElement(AppiumElementLocator.java:132)
	at io.appium.java_client.pagefactory.ElementInterceptor.intercept(ElementInterceptor.java:26)
	at io.appium.java_client.MobileElement$$EnhancerByCGLIB$$f9fb405d.click(<generated>)
	at myApp.Pages.WelcomePage.moveToLoginPage(WelcomePage.java:35)
	at myApp.TestCases.PaybackLoginTest.setUp(MyAppTest.java:24)
````

Thank you very much,

mgehlen

**Comment by jlipps** [comment]
Interesting. I've never had to use the full package for the ID before. Maybe that's an idiosyncrasy of your particular app?

@bootstraponline have you run into this? Could we solve the problem by prepending the package name to "android" in Bootstrap.jar?

**Comment by bootstraponline** [comment]
> @bootstraponline have you run into this? 

Yes.  Selendroid is limited to one app so the package name is known. uiautomator works across apps and needs the fully qualified id.

> Could we solve the problem by prepending the package name to "android" in Bootstrap.jar?

Yep,  I think it'd be simple to do a fallback id search using the app package the session was started with.

**Comment by jlipps** [comment]
OK, adding it to the next feature milestone to deal with then.

**Comment by mgehlen** [comment]
Hello jipps,
Hello bootstraponline,

thank you very much for your support.
The fallback feature in the next feature milestone is terrific for me.

Best regards,

  mgehlen

**Comment by amedvedjev** [comment]
have similar problem but with more complex scenario:
1) Some elements on page are like @FindBy(id = "android:id/action_bar_title")
2) others like @FindBy(id = "bundle_Identifier:id/txt_badge")
3) when changing bundle (we do not know in advance what bundle will be) @FindBy(id = "other_bundle_Identifier:id/txt_badge")

it will be nice to solve this problem also. thanks.

**Comment by bootstraponline** [comment]
I added support for `android:id` and `package:id` in https://github.com/appium/appium/issues/4467

Appium only knows about the package used to start the session and the default `android` package. If you have multiple packages within a session, then you'd still need the fully qualified id.

**Comment by mgehlen** [comment]
by the way finally came around to actually use this and it works like a charm. 

Thank you very much!
