### ISSUE TITLE
An element could not be located on the page using the given search parameters

### ISSUE THREAD

**Issue by runnerhuang** [appium/appium#4419]
It will happen when the activity responses too slow. Actually the element exists, how to avoid this case?

**Comment by jlipps** [comment]
Are you already using an implicit wait timeout? Can you increase the timeout? Otherwise, the next step is to print the app source at the time you're finding the element to see whether it really exists according to the app at that time.

**Comment by runnerhuang** [comment]
Increase the timeout works. it's ok now. thanks
