### ISSUE TITLE
"No app set" error on Appium 1.3.4, Xcode 6.1.1 and safari on iOS 8.1 simulator 

### ISSUE THREAD

**Issue by princeulrich2** [appium/appium#4420]
I just upgraded Appium to version 1.3.4 and I since then I run into the following error:

No app set; either start appium with --app or pass in an 'app' value in desired capabilities, or set androidPackage to launch pre-existing app on device
  
I am automating a browser so  i don't understand why an app is required in the capabilities. below are my current capabilities:
               
DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("browserName", "Safari");
		capabilities.setCapability("deviceName", "iPhone Simulator");
		capabilities.setCapability("automationName", "Appium");
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("platformVersion", "8.1");

Can anyone please help me out?

**Comment by sebv** [comment]
Those caps works fine for me, could it be a client binding issue?

**Comment by princeulrich2** [comment]
Not sure, I reverted to Appium 1.3.1 and it works fine

**Comment by sebv** [comment]
Has this been solved? If not, it would  be good if we could take a look at the appium server log.

**Comment by sebv** [comment]
reopen if needed.
