### ISSUE TITLE
iOS: Arabic text oddness

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#4421]
have problem with testing client in Arabic layout.

the problem is that some characters changing while getting into Java client or MAC GUI client.
although compared strings looking same actually they have different length and thus this cause tests to fail.

while investigating issue it was found that characters under test shown correctly in Appium GUI client for MAC logs but further transforming somehow.

Example of test:
  original: رأيي بيل
  catalog name on phone visible in java client when getting some text of element: رأيي بيل
  in pageSource() of Java client: label="رأيي بيل" value="رأيي بيل" dom=
  in GUI Appium inspector: value: رأيي بيل
  in GUI Appium logs: "UIAStaticText":{"@":{"name":"menuTitle","label":"رأيي بيل","value":"رأيي بيل"

although it is look like all the same actually only "GUI Appium logs" is correct as original - see screenshot here http://screencast.com/t/OWPj92giFYt

there are also some other characters behave in same way.

Can you suggest any way to workaround the problem?

Mine config:
Appium 1.3.4
Java client: 2.1.0
Mac OSX 10.10.1 Yosemite
Xcode 6.1.1
iOS Simulator 8.1

**Comment by 0x1mason** [comment]
I believe we've made some changes to our unicode that dealt with characters that can be represented as one or 2 glyphs, but I'm only superficially familiar with these types of issues.  @imurchie Is this addressed by your recent unicode changes?  Can you shed any light on what's going on?

**Comment by imurchie** [comment]
This is usually a problem that can be handled by "normalization". See [here](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/unicode.md).

**Comment by amedvedjev** [comment]
so i need do normalization of original string to compare that they are equal?

**Comment by imurchie** [comment]
You will need to play around, because some applications use a certain format, and some test runners, etc. `nfd` is what I have found works, but the side the normalization needs to happen on changes depending on your system. That is why Appium does not do it automatically.

**Comment by amedvedjev** [comment]
but what normalization uses Appium when we get e.g. in Java client some element text?

**Comment by imurchie** [comment]
None. Appium simply passes the text along that the device/app gave.

**Comment by amedvedjev** [comment]
not true cause string in Appium Logs <> what is in Appium Inspector+what returns in Java client.
see screenshot in first post. point to my mistake pls.

**Comment by imurchie** [comment]
Yes, this is the text going through a number of systems that treat it differently. This is why Appium does not do anything to it. You, as developer and/or tester, need to make sure that both ends are the same. If you switch languages/test runners, the results may be different (I just did a test with JavaScript and mocha and the straight text works fine, for instance).

**Comment by amedvedjev** [comment]
but at least Appium Logs and Appium inspector are components of Appium system only (e.g. Mac GUI for Appium in mine case). and i do not see a reason why they should show different results based on some test system settings...

**Comment by imurchie** [comment]
Why should they? The text as shown in the inspector has gone through the Mac GUI program, so it might mess with things in its handling of Unicode. As I said, every system through which the text moves has the potential to change how the text is handled.

**Comment by amedvedjev** [comment]
but inspector is part of Mac GUI program. they both show same thing but in different way. MAC GUI program shows raw logs in log window then these logs go to MAC GUI Inspector which transforming it in Tree view plus image. i expect that at least these two part should show the same.

ok. tomorrow will try "normalization" and will write results.

**Comment by amedvedjev** [comment]
NFD normalization fixed problem. thanks.

 so if you are sure that shwoing dirrefent strings in this (http://screencast.com/t/xjRvREGs) screenshot is OK we can close issue.

**Comment by imurchie** [comment]
I'm pretty sure. One is the output of Appium, the other is the going through a Mac (i.e., Objective-C) app, that has its own way of doing things.
