### ISSUE TITLE
How to kill the session which was running on the Appium server from the Client? pls help

### ISSUE THREAD

**Issue by runnerhuang** [appium/appium#4423]
The case was interrupted, i need to restart the case from the client, but it showed that another session was running. So how to kill the session from client to make sure I can restart the case?

**Comment by runnerhuang** [comment]
Java:  
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Requested a new session but one was in progress) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 190 milliseconds
Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'

**Comment by sebv** [comment]
You can start appium with `--session-overide`, or get the list of sessions attach to them and close them.

**Comment by runnerhuang** [comment]
Could u show the code? close sessions

**Comment by sebv** [comment]
```
var wd = require('wd'),
    Q = require('q'),
    _ = require('lodash');

var localConfig = {
  host: 'localhost',
  port: 4723
};

var driver = wd.promiseChainRemote(localConfig);
driver.sessions()
  .then(function(sessions) {
    var quitPromises = _(sessions).map(function(session) {
      console.log('Closing session ->', session.id);
      var d = wd.promiseChainRemote(localConfig);
      return d.attach(session.id).quit()
        .then(function() { console.log('Closed session ->', session.id); });
    });
    return Q.all(quitPromises);
  }).done();
```

**Comment by runnerhuang** [comment]
ok now,thanks.
