### ISSUE TITLE
Build error while running reset.sh --android --selendroid command.

### ISSUE THREAD

**Issue by priyankshah217** [appium/appium#4425]
Hi All,

I got error while updating appium directly from master in Ubuntu (14.04). I was able to build previous versions.

Please find attached logs.
https://gist.github.com/priyankshah217/7803dbc73ac8974dad83#file-builderror-log

Thanks,
Priyank Shah

**Comment by kikyoungkwon** [comment]
FYI, I checked out to previous commit (git checkout ec3fb9f84f1d2ee189fb47c544103fc220cb82ad) and works.

commit ec3fb9f84f1d2ee189fb47c544103fc220cb82ad
Author: Jonathan Lipps <jlipps@gmail.com>
Date:   Tue Jan 20 12:40:09 2015 -0800
fix some tests for the 5.0 emu / new app

**Comment by jlipps** [comment]
I'm seeing this too. I think it is related to @aluedeke's changes that @0x1mason just merged in?

**Comment by jlipps** [comment]
I'm confused how it was even possible for @0x1mason to build appium 1.3.5 beta with this code. Also, I had checked out @aluedeke's branch earlier and it built fine. Not sure what's going on.

**Comment by 0x1mason** [comment]
Fix awaiting merge.  I had created a new branch for the beta and fixed the problem there, but neglected to push the missing references to master.  Apologies.
