### ISSUE TITLE
How to handle default system generated pop ups for android browser(google chrome) automation?

### ISSUE THREAD

**Issue by patilsneh** [appium/appium#4426]
I have tried using driver.switchTo().alert().dismiss()//or accept() but it is throwing NoAlertPresentException: no alert open.
i also set capability to capabilities.setCapability("autoAcceptAlerts", true); and it is working but i am still able to see popup on the screen.

As it might server side issue (As suggested by Sergey Tichomirov )i am sharing my appium server logs here.

Here is the appium server logs:

> Starting Node Server
> info: Welcome to Appium v1.1.0 (REV e433bbc31511f199287db7724e1ce692bcb32117)
> info: Appium REST http interface listener started on 127.0.0.1:4721
> info: socket.io started
> info: Non-default server args: {"address":"127.0.0.1","port":4721,"logNoColors":true,"platformName":"Android","platformVersion":"19","automationName":"Appium"}
> ERROR: debug: Appium request initiated at /wd/hub/session
> warn: Converting cap chromeOptions to string, since it was an object. This might be a user error. Original value was: {"androidPackage":"com.android.chrome","args":[],"extensions":[]}
> ERROR: debug: Request received with params: {"desiredCapabilities":{"autoAcceptAlerts":true,"platform":"Win8","App":"Chrome","platformName":"Android","browserName":"chrome","device":"Android","chromeOptions":{"androidPackage":"com.android.chrome","args":[],"extensions":[]},"version":"4.4.2"}}
> info: Looks like we want chrome on android
> info: Creating new appium session e146756a-7e86-4b4b-b660-b5881b8c2519
> info: Preparing device for session
> info: Not checking whether app is present since we are assuming it's already on the device
> info: Checking whether adb is present
> info: [ADB] Using adb from D:\Appium\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\adb.exe
> info: Trying to find a connected android device
> info: [ADB] Getting connected devices...
> info: [ADB] 1 device(s) connected
> ERROR: debug: executing: "D:\Appium\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\adb.exe" -s 000e2be7630321 wait-for-device
> info: Setting device id to 000e2be7630321
> info: [ADB] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> ERROR: debug: executing: "D:\Appium\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\adb.exe" -s 000e2be7630321 shell "echo 'ready'"
> info: Starting logcat capture
> ERROR: debug: Pushing unlock helper app to device...
> ERROR: debug: executing: "D:\Appium\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\adb.exe" -s 000e2be7630321 install "C:\Users\snehp\Downloads\AppiumForWindows-1.1.0.0\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> ERROR: debug: executing: "D:\Appium\adt-bundle-windows-x86_64-20140321\sdk\platform-tools\adb.exe" -s 000e2be7630321 shell "dumpsys window"
> info: Writing dumpsys output to C:\Users\snehp\Downloads\AppiumForWindows-1.1.0.0\Appium\node_modules\appium\.dumpsys.log
> ERROR: debug: Screen already unlocked, continuing.
> info: Creating Chrome session
> info: Ensuring Chromedriver exists
> info: Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %b))
> info: No old chromedrivers seemed to exist
> info: Spawning chromedriver with: C:\Users\snehp\Downloads\AppiumForWindows-1.1.0.0\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [CHROMEDRIVER] Starting ChromeDriver (v2.9.248315) on port 9515
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"000e2be7630321"}}}}
> info: Successfully started chrome session
> info: Overriding session id with "583df60f29d3c2bf4d3a91ebe7aa7fa4"
> info: Device launched! Ready for commands
> info: Setting command timeout to the default of 60 secs
> info: Appium session started with sessionId 583df60f29d3c2bf4d3a91ebe7aa7fa4
> POST /wd/hub/session 303 7923ms - 9b
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4","method":"GET"}
> GET /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4 200 0ms - 475b
> ERROR: debug: Request received with params: {}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: "{\"sessionId\":\"583df60f29d3c2bf4d3a91ebe7aa7fa4\",\"status\":0,\"value\":{\"acceptSslCerts\":true,\"applicationCacheEnabled\":false,\"browserConnectionEnabled\":false,\"browserName\":\"chrome\",\"chrome\":{},\"cssSelectorsEnabled\":true,\"databaseEnabled\":false,\"handlesAlerts\":true,\"javascriptEnabled\":true,\"locationContextEnabled\":true,\"nativeEvents\":true,\"platform\":\"ANDROID\",\"rotatable\":false,\"takesHeapSnapshot\":true,\"takesScreenshot\":true,\"version\":\"39.0.2171.93\",\"webStorageEnabled\":true}}"
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/url
> ERROR: debug: Request received with params: {"url":"http://***@***.com"}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":null}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/url 200 8230ms - 85b
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element","method":"POST","json":{"using":"xpath","value":"//*[@id='hc_r_hd']/nav/ul/li[2]/a"}}
> ERROR: debug: Request received with params: {"using":"xpath","value":"//*[@id='hc_r_hd']/nav/ul/li[2]/a"}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":{"ELEMENT":"0.6544341163244098-1"}}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element 200 281ms - 124b
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-1/click
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-1/click","method":"POST","json":{"id":"0.6544341163244098-1"}}
> ERROR: debug: Request received with params: {"id":"0.6544341163244098-1"}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":null}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-1/click 200 313ms - 85b
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element","method":"POST","json":{"using":"xpath","value":"//*[@id='hc_r_config']/div/a[2]"}}
> ERROR: debug: Request received with params: {"using":"xpath","value":"//*[@id='hc_r_config']/div/a[2]"}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":{"ELEMENT":"0.6544341163244098-2"}}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element 200 218ms - 124b
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-2/click
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-2/click","method":"POST","json":{"id":"0.6544341163244098-2"}}
> ERROR: debug: Request received with params: {"id":"0.6544341163244098-2"}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":null}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-2/click 200 328ms - 85b
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element","method":"POST","json":{"using":"xpath","value":"//*[@id='hc_f_EmailLogin']"}}
> ERROR: debug: Request received with params: {"using":"xpath","value":"//*[@id='hc_f_EmailLogin']"}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":{"ELEMENT":"0.6544341163244098-3"}}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element 200 204ms - 124b
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-3/click
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-3/click","method":"POST","json":{"id":"0.6544341163244098-3"}}
> ERROR: debug: Request received with params: {"id":"0.6544341163244098-3"}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":null}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-3/click 200 288ms - 85b
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element","method":"POST","json":{"using":"xpath","value":"//*[@id='hc_f_EmailLogin']"}}
> ERROR: debug: Request received with params: {"using":"xpath","value":"//*[@id='hc_f_EmailLogin']"}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":{"ELEMENT":"0.6544341163244098-3"}}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element 200 78ms - 124b
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-3/value
> ERROR: debug: Request received with params: {"id":"0.6544341163244098-3","value":["sam@sam.com"]}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":null}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-3/value 200 672ms - 85b
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element","method":"POST","json":{"using":"xpath","value":"//*[@id='hc_f_PasswordLogin']"}}
> ERROR: debug: Request received with params: {"using":"xpath","value":"//*[@id='hc_f_PasswordLogin']"}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":{"ELEMENT":"0.6544341163244098-4"}}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element 200 203ms - 124b
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-4/click","method":"POST","json":{"id":"0.6544341163244098-4"}}
> ERROR: debug: Request received with params: {"id":"0.6544341163244098-4"}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":null}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-4/click 200 344ms - 85b
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element","method":"POST","json":{"using":"xpath","value":"//*[@id='hc_f_PasswordLogin']"}}
> ERROR: debug: Request received with params: {"using":"xpath","value":"//*[@id='hc_f_PasswordLogin']"}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element 200 47ms - 124b
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":{"ELEMENT":"0.6544341163244098-4"}}
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-4/value","method":"POST","json":{"id":"0.6544341163244098-4","value":["samsam"]}}
> ERROR: debug: Request received with params: {"id":"0.6544341163244098-4","value":["samsam"]}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":null}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-4/value 200 359ms - 85b
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element
> ERROR: debug: Request received with params: {"using":"xpath","value":"//*[@id='hc_r_login']/div[2]/div/form[1]/fieldset/div[3]/a"}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element","method":"POST","json":{"using":"xpath","value":"//*[@id='hc_r_login']/div[2]/div/form[1]/fieldset/div[3]/a"}}
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":{"ELEMENT":"0.6544341163244098-5"}}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element 200 187ms - 124b
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-5/click
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-5/click","method":"POST","json":{"id":"0.6544341163244098-5"}}
> ERROR: debug: Request received with params: {"id":"0.6544341163244098-5"}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: {"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4","status":0,"value":null}
> POST /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/element/0.6544341163244098-5/click 200 344ms - 85b
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/alert_text
> info: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/alert_text","method":"GET"}
> ERROR: debug: Request received with params: {}
> ERROR: debug: Proxying command to 127.0.0.1:9515
> ERROR: debug: Proxied response received with status 200: "{\"sessionId\":\"583df60f29d3c2bf4d3a91ebe7aa7fa4\",\"status\":27,\"value\":{\"message\":\"no alert open\\n  (Session info: chrome=39.0.2171.93)\\n  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.2 x86_64)\"}}"
> GET /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4/alert_text 200 16ms - 208b
> info: Shutting down appium session...
> ERROR: debug: Appium request initiated at /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4
> ERROR: debug: Request received with params: {}
> info: Killing chromedriver
> info: Chromedriver exited with code null
> info: (killed by signal SIGTERM)
> info: Cleaning up appium session
> info: Responding to client with success: {"status":0,"value":null,"sessionId":"583df60f29d3c2bf4d3a91ebe7aa7fa4"}
> DELETE /wd/hub/session/583df60f29d3c2bf4d3a91ebe7aa7fa4 200 875ms - 85b

**Comment by patilsneh** [comment]
attaching image for reference:
![dump_4875461215172251648](https://cloud.githubusercontent.com/assets/10653733/5856241/485bd6ea-a267-11e4-9c3e-196505f0106b.png)

**Comment by jlipps** [comment]
This is a chromedriver bug: https://code.google.com/p/chromedriver/issues/detail?id=1015

**Comment by knreddy036** [comment]
How to disable download pop up dialog in android chrome browser ?
