### ISSUE TITLE
Cannot open iOS application on real device

### ISSUE THREAD

**Issue by michaazran** [appium/appium#4427]
I ran appium with app_path point to my application
it managed to install the application via fruitstrap command 
but when it tried to launch the application i am getting the below error

any idea ?

info: [debug] Attempting to run app on real device with UDID *******
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w ********  beta.pounce.Pounce -e UIASCRIPT "/Users/amirzur/Library/Application Support/appium/bootstrap/bootstrap-807d2e4a76836393.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] 2015-01-22 17:06:27.410 instruments[35614:707] Permission to debug beta.pounce.Pounce was denied.  The app must be signed with a development identity (e.g. iOS Developer).
info: [debug] [INST STDERR] Instruments Trace Error : Error Starting Recording
info: [debug] [INSTSERVER] Instruments exited with code 253
info: [debug] Killall instruments

**Comment by imurchie** [comment]
Is the app signed with a developer identity?

**Comment by michaazran** [comment]
I don't know, I got it from a member from thevdev team, can you tell me exactly how to.create the ipa /app file? I will ask the dev team to prepare such

Thanks

**Comment by imurchie** [comment]
See
https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices.md

**Comment by michaazran** [comment]
just last question, i got the ipa wirh debug permissions but it compiled on different mac under different user profile, now i want to run it under my mac using my appium, is it possible?
or if i want to run it on my MAC i MUST compile it under my xcode using my profile ?

**Comment by imurchie** [comment]
I'm not sure. You would be better served asking this on the [Appium discuss list](https://discuss.appium.io/).
