### ISSUE TITLE
Missing `chromeOptions` in documentation for caps

### ISSUE THREAD

**Issue by bayandin** [appium/appium#4432]
According to changelog in v1.2.2 was added ability to specify `chromeOptions` in caps ([Changelog](https://github.com/appium/appium/blob/v1.2.2/CHANGELOG.txt#L27)). But it missing in [doc for caps](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md).
I think it should be added.

**Comment by jlipps** [comment]
Really what we did is allowed that options hash to be passed into chromedriver directly. I don't think it belongs in the appium caps doc---it's really part of the chromedriver doc. But if you feel strongly about it, I would merge a pull request that adds it!
