### ISSUE TITLE
appium failed on real ios8 device

### ISSUE THREAD

**Issue by hzy00** [appium/appium#4434]
I run my test on real ios 6 or 7 device. It works fine. On real ios 8 device, it starts up successfully. On the former pages,I mean the pages of my app, it appears no problem. However, when it goes to a normal page, it fails! So strange! I've tried different ios8 devices for many times. All goes to the same result. Here's the key log：

info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","origValue":"connect ECONNREFUSED"},"sessionId":"5ef8dd2e-1502-4d9f-b504-a4e0f110585f"}
info: <-- GET /wd/hub/session/5ef8dd2e-1502-4d9f-b504-a4e0f110585f/contexts 500 8.240 ms - 293 

error: [REMOTE] Could not connect to WebKitRemoteDebugger server

Anyone could help me out of this?

**Comment by jchuong** [comment]
It looks like ios-webkit-debug-proxy crashed for your ios 8 device.  Check ios-webkit-debug-proxy log and see if that's the case.  I have made a fork of i-w-d-p that might fix the issue which a few people have said it works: https://github.com/jchuong/ios-webkit-debug-proxy .

**Comment by hzy00** [comment]
sorry, I don't really get it. Here is the ios-webkit-debug-proxy log:

ss.recv fd=4 len=686
ss.add_server_fd(5)
Could not start com.apple.webinspector!: Undefined error: 0
ss.remove_server_fd(5)
Unable to attach 7f856e9cbdf5f8f30e79e8015c07c5bd5ab13a22 inspector

And I don't see my device in 127.0.0.1:9221.
it seems ios-webkit-debug-proxy causes this problem. But I'm confused:
the appium can work in the former pages! It failed in the same page every time. If ios-webkit-debug-proxy causes this, the appium should failed in the beginning. 

What's more, I'm sorry not to catch the fork of i-w-d-p. How can I solve the problem that ios-webkit-debug-proxy cannot attach my device?
Any response appreciated.

**Comment by jchuong** [comment]
The fork fixes a problem that isn't related to your problem.  What do you mean by normal and former pages?  It actually looks like you don't have Web Inspector turned on in your devices.

`Settings -> Safari -> Advanced -> Web Inspector = ON`, and make sure that UI Automation is on.
`Developer ->  UI Automation -> Enable`

**Comment by hzy00** [comment]
@jchuong sorry, I don't make it clear. First, I do enable those settings. It goes to the same result.
  As for the pages, I mean the pages of my app. Appium fails with a normal page in the middle of my test.
Is it really the reason of ios-webkit-debug-proxy? 
Additionally, I have some new findings:
with libimobiledevice v1.1.6, ios-webkit-debug-proxy fails with the error 
"Invalid idevice_connection struct?: Undefined error: 0
Unable to get connection file descriptor.: Undefined error: 0
ss.remove_server_fd(5)
Unable to attach f4c3fe032926fbc5da231ee02794da82354785ed inspector". But ideviceinstaller works fine.

with libimobiledevice v1.1.5, ios-webkit-debug-proxy fails with the error 
"Could not start com.apple.webinspector!: Undefined error: 0
ss.remove_server_fd(5)
Unable to attach d0f71f092a14ff114ca8c2565a8769bb3de1f326 inspector". Ideviceinstaller also fails with the error "Could not start com.apple.mobile.installation_proxy!"

now, I'm really confused...

**Comment by hzy00** [comment]
okay, ios-webkit-debug-proxy problem solved. I just update libimobiledevice to v1.1.7. Both ios-webkit-debug-proxy and ideviceinstaller work well. But appium still fails. Things don't get better.

**Comment by hzy00** [comment]
@jchuong  it seems not the reason of ios-webkit-debug-proxy! I just find the log of successful ios6 device also includes the error "error: [REMOTE] Could not connect to WebKitRemoteDebugger server".
But the whole test succeeds every time! It seems I should go for the other direction.

**Comment by hzy00** [comment]
okay, I've found the root of the problem. It's that the debug log of my app blocks appium. Just use the release version. More solution： https://discuss.appium.io/t/app-freezes-when-automated/1030/8

**Comment by vyvanand** [comment]
Hi, I connected to real ios device. I can able to see real device in appium inspector screen. 
If I trying to tap button from appium inspector screen, the refresh button loads and remains in same page also I be getting "Could not connect to webkitremotedebugger server error" in log. 
Please help me on this. Thanks
![screen shot 2015-08-17 at 2 47 39 pm](https://cloud.githubusercontent.com/assets/4377090/9322924/fbbf5d32-4597-11e5-96dd-6d0ddfd003ac.png)

**Comment by vinay3579** [comment]
Hi ,
Pls help me as i am stuck in web browser testing in iOS real device but i am able to run automation steps in app on same iOS real device.
I have installed Safari launcher in my iOS phone using Xcode and my app is signed with dev account .
when i am running my code its open safari launcher click on open button but when safari browser open my iOS webkit getting crash 
in logs i am getting bellow error 
info: [debug] Navigating to most recently opened web view

 info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray

info: [debug] Cleaning up appium session

error: [REMOTE] Could not connect to WebKitRemoteDebugger server

and in iOS webkit i am getting error 
Last login: Mon Sep 14 11:25:33 on ttys000

 Administrators-Mac-mini:~ administrator$ ios_webkit_debug_proxy

Listing devices on :9221

Connected :9222 to iPhone 5S (90a0078ff099927f79ba49043a3240147a6f0efb)

Unknown app_id PID:184

Invalid message _rpc_applicationSentListing: <dict>

<key>WIRApplicationIdentifierKey</key>

<string>PID:184</string>

<key>WIRListingKey</key>

<dict>

</dict>

</dict>

Disconnected :9222 from iPhone 5S (90a0078ff099927f79ba49043a3240147a6f0efb)

my code is 

  WebDriver wd;
	

		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("appium-version", "1.4.8");
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("platformVersion", "8.4");
        capabilities.setCapability("deviceName", "iPhone 5s");
		capabilities.setCapability("bundleId", "com.pyramidci.SafariLauncher");
		capabilities.setCapability("autoWebView", "true");
		capabilities.setCapability("udid", "90a0078ff099927f79ba49043a3240147a6f0efb");
	
		capabilities.setCapability("app", "/Users/administrator/Library/Developer/Xcode/DerivedData/iOSSampleApp-hgjbrohpjbndcfhiazafhzdvnlet/Build/Products/Debug-iphoneos/iOSSampleApp.app");
		wd = new RemoteWebDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
		wd.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
	
		wd.findElement(By.name("launch safari")).click();

**Comment by mani9786** [comment]
Hi hzy00
              Could you please explain the steps to resolve this issue . It will more useful to me. I am doing automation for  native app.

![screen shot 2016-02-06 at 1 40 26 am](https://cloud.githubusercontent.com/assets/17089075/12857892/bf24d962-cc72-11e5-8985-9997ce012f5f.png)

**Comment by mi2pankaj** [comment]
Did you run tests after starting ios_webkit_debug_proxy server along with appium server, if not start it by using command: ios_webkit_debug_proxy -c <udid>:27753 -d
If you don't have ios_webkit_debug_proxy then install it by using command:  brew install ios-webkit-debug-proxy

**Comment by mani9786** [comment]
Hi 
     Thanks for your reponse. installed the ios-webkit now issue is resloved. But when clicking the appium inspector empty screen is displaying. 

![empty screen](https://cloud.githubusercontent.com/assets/17089075/13254700/7a357a2e-da68-11e5-9e7b-5e81e259bb14.png)
![ios_webkit_debug](https://cloud.githubusercontent.com/assets/17089075/13254707/8b05fad6-da68-11e5-857a-41380b1cc5e0.png)

**Comment by mi2pankaj** [comment]
the ios-webkit-debug-proxy requires the "web inspector" to be turned on to allow a connection to be established. Turn it on by going to settings > safari > advanced > web inspector - On.

**Comment by mani9786** [comment]
Hi

      Thanks again. I have turn on the web inspector. But my app is not browser based it's native app. Sorry I am  new to appium.

Thanks
Mani.v

**Comment by ShibiKP** [comment]
pankaj how to pass the command to windows to mac using cmd for auto launching the appium and to run the ios proxy
