### ISSUE TITLE
Ability to set size of a widget

### ISSUE THREAD

**Issue by gauravgandhi15** [appium/appium#4438]
I am using an android app where i need to set the dimension of a widget to different sizes. In other words, i need to stretch it to different size. I can move it by using TouchAction. Is there any way to resize it? Is that possible in Appium? Please help @Jonahss @jlipps @sah @jmathes @tanob

**Comment by jlipps** [comment]
Please direct such usage questions to the appium forums. Also, please refrain from @-mentioning random people.

To answer your question, if you can do something with a gesture in the UI, you should be able to encode that gesture and execute it using Appium.

**Comment by gauravgandhi15** [comment]
@jlipps sorry got it. Thanks
