### ISSUE TITLE
Parallel execution only runs in one device,  second device Appium shutdowns.

### ISSUE THREAD

**Issue by gualber98** [appium/appium#4441]
Hello, I have been working in this issue for days I still cannot solve it, Anyone, knows what I could be wrong.   The issue that I have is that when I run parallel test two devices one device runs in one appium instance the second appium instances shuts down for unknown reason.  

Here is my settings (Android):
- Selenium grid with two appium nodes.
- two devices usb attached.

Appium instance A
appium --address 10.207.33.106 --port 4723 --bootstrap-port 4725 --udid 066e8977f0ec851f  --chromedriver-port 2725 --no-reset --command-timeout 1200 --session-override --nodeconfig /Users/name/MobileAutomation/nexus5Node.json

Appium instance B
appium --address 10.207.33.106 --port 4733 --bootstrap-port 4735 --udid 9a588123 --chromedriver-port 2735 --no-reset --command-timeout 1200 --session-override --nodeconfig /Users/name/MobileAutomation/galaxys4Node.json

capabilities includes
capabilities.setCapability("udid", uid);
capabilities.setCapability("platformVersion", "4.4");
capabilities.setCapability("platformName", "ANDROID");
capabilities.setCapability("appPackage", "com.----");
capabilities.setCapability("appWaitPackage", "com.-----");		
capabilities.setCapability("appActivity", "com.-----");
capabilities.setCapability("appWaitActivity", "com.----");

driver = new AndroidDriver(new URL("http://10.207.33.106:4444"/wd/hub"), capabilities);

>>>Appium instance A  shuts down log<<<<
info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
info: Appium REST http interface listener started on 10.207.33.106:4723
info: [debug] Non-default server args: {"udid":"066e8977f0ec851f","address":"10.207.33.106","bootstrapPort":4725,"sessionOverride":true,"noReset":true,"nodeconfig":"/Users/name/Documents/MobileAutomation/nexus5Node.json","chromeDriverPort":2725,"defaultCommandTimeout":1200}
info: Console LogLevel: debug
info: [debug] starting auto register thread for grid. Will try to register every 5000 ms.
info: [debug] Appium successfully registered with the grid on 10.207.33.106:4444
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}
info: <-- GET /wd/hub/status 200 5.305 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}
info: <-- GET /wd/hub/status 200 1.899 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}
info: <-- GET /wd/hub/status 200 0.965 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}
info: --> POST /wd/hub/session {"desiredCapabilities":{"appActivity":"com.nfl.fantasy.core.android.activities.MainActivity","appPackage":"com.nfl.fantasy.core.android","platformVersion":"4.4","appWaitPackage":"com.nfl.fantasy.core.android","appWaitActivity":"com.nfl.fantasy.core.android.activities.MainActivity","platformName":"Android","udid":"066e8977f0ec851f","deviceName":"nexus5","version":"3.3","platform":"ANDROID"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : version, platform
info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
info: [debug] Creating new appium session 539804b5-64cc-4d85-971d-ddd2986b6c9a
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.8.0_25
info: [debug] Using fast reset? false
info: [debug] Preparing device for session
info: [debug] Not checking whether app is present since we are assuming it's already on the device
info: [debug] Checking whether adb is present
info: [debug] Using adb from /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb devices
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: <-- GET /wd/hub/status 200 1.205 ms - 155 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: [debug] Could not find devices, restarting adb server...
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb kill-server
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb devices
info: [debug] 3 device(s) connected
info: Found device 066e8977f0ec851f
info: [debug] Setting device id to 066e8977f0ec851f
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f wait-for-device
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f shell "echo 'ready'"
info: [debug] Starting logcat capture
warn: No app capability, can't parse package/activity
info: [debug] Getting device API level
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: Device API level is: 19
info: [debug] Apk doesn't exist locally
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f shell "rm -rf /data/local/tmp/strings.json"
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Skipping install since we launched with a package instead of an app path
info: [debug] Forwarding system:4725 to device:4724
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f forward tcp:4725 tcp:4724
info: [debug] Pushing appium bootstrap to device...
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f push "/Users/jobi.mathai/local/lib/node_modules/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/
info: [debug] Pushing settings apk to device...
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f install "/Users/jobi.mathai/local/lib/node_modules/appium/build/settings_apk/settings_apk-debug.apk"
info: [debug] Pushing unlock helper app to device...
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f install "/Users/name/local/lib/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"
info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f shell "ps 'uiautomator'"
info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] Waking up device if it's not alive
info: [debug] Pushing command to appium work queue: ["wake",{}]
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: wake
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f shell "dumpsys window"
info: Unlocking screen
info: [debug] Screen is locked, trying to unlock
info: [debug] Getting device API level
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f shell "dumpsys window"
info: [debug] Screen is unlocked, continuing
info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
info: [debug] dataDir set to: /data/local/tmp
info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
info: [debug] Getting device API level
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.nfl.fantasy.core.android/com.nfl.fantasy.core.android.activities.MainActivity"
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: <-- GET /wd/hub/status 200 2.338 ms - 155 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: [debug] Waiting for pkg "com.nfl.fantasy.core.android" and activity "com.nfl.fantasy.core.android.activities.MainActivity" to be focused
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f shell "dumpsys window windows"
info: [debug] Device launched! Ready for commands
info: [debug] Setting command timeout to the default of 1200 secs
info: [debug] Appium session started with sessionId 539804b5-64cc-4d85-971d-ddd2986b6c9a
info: <-- POST /wd/hub/session 303 12100.502 ms - 9 
info: --> GET /wd/hub/session/539804b5-64cc-4d85-971d-ddd2986b6c9a {}
info: [debug] Responding to client with success: {"status":0,"value":{"platform":"ANDROID","browserName":"Android","platformVersion":"4.4","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"appActivity":"com.nfl.fantasy.core.android.activities.MainActivity","appPackage":"com.nfl.fantasy.core.android","platformVersion":"4.4","appWaitPackage":"com.nfl.fantasy.core.android","appWaitActivity":"com.nfl.fantasy.core.android.activities.MainActivity","platformName":"Android","udid":"066e8977f0ec851f","deviceName":"nexus5","version":"3.3","platform":"ANDROID"},"appActivity":"com.nfl.fantasy.core.android.activities.MainActivity","appPackage":"com.nfl.fantasy.core.android","appWaitPackage":"com.nfl.fantasy.core.android","appWaitActivity":"com.nfl.fantasy.core.android.activities.MainActivity","platformName":"Android","udid":"066e8977f0ec851f","deviceName":"nexus5","version":"3.3"},"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: <-- GET /wd/hub/session/539804b5-64cc-4d85-971d-ddd2986b6c9a 200 3.002 ms - 1020 {"status":0,"value":{"platform":"ANDROID","browserName":"Android","platformVersion":"4.4","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"appActivity":"com.nfl.fantasy.core.android.activities.MainActivity","appPackage":"com.nfl.fantasy.core.android","platformVersion":"4.4","appWaitPackage":"com.nfl.fantasy.core.android","appWaitActivity":"com.nfl.fantasy.core.android.activities.MainActivity","platformName":"Android","udid":"066e8977f0ec851f","deviceName":"nexus5","version":"3.3","platform":"ANDROID"},"appActivity":"com.nfl.fantasy.core.android.activities.MainActivity","appPackage":"com.nfl.fantasy.core.android","appWaitPackage":"com.nfl.fantasy.core.android","appWaitActivity":"com.nfl.fantasy.core.android.activities.MainActivity","platformName":"Android","udid":"066e8977f0ec851f","deviceName":"nexus5","version":"3.3"},"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: <-- GET /wd/hub/status 200 1.720 ms - 155 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: <-- GET /wd/hub/status 200 0.936 ms - 155 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: <-- GET /wd/hub/status 200 1.817 ms - 155 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}},"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: --> DELETE /wd/hub/session/539804b5-64cc-4d85-971d-ddd2986b6c9a {}
info: Shutting down appium session
info: [debug] Pressing the HOME button
info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140624/sdk/platform-tools/adb -s 066e8977f0ec851f shell "input keyevent 3"
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 34.454
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] UiAutomator shut down normally
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: <-- DELETE /wd/hub/session/539804b5-64cc-4d85-971d-ddd2986b6c9a 200 619.050 ms - 76 {"status":0,"value":null,"sessionId":"539804b5-64cc-4d85-971d-ddd2986b6c9a"}
info: --> GET /wd/hub/status {}

Any help will be greatly appreciated

**Comment by gualber98** [comment]
Copy and paste mistake

Appium instance B
appium --address 10.207.33.106 --port 4733 --bootstrap-port 4735 --udid 066e8977f0ec851f --chromedriver-port 2735 --no-reset --command-timeout 1200 --session-override --nodeconfig /Users/name/MobileAutomation/galaxys4Node.json

**Comment by shubhansha21** [comment]
hi gualber98, were you able to solve this issue?

**Comment by moizjv** [comment]
@gualber98 @shubhansha21 can you look at this [discussion](https://discuss.appium.io/t/connecting-appium-server-to-selenium-grid-for-android/804/89) this might your issues. Also can you raise these issues in discussion forum.

**Comment by tsreenivash-pk** [comment]
Hi all,

I am also facing the same problem, it always picks the first device irrespective of the device capabilities which I have set for the second device name in the appium test class. please suggest me a solution.

**Comment by deepikashekar37** [comment]
Hi All,
I am able to execute parallel on two android device.

But after closing and launching app execution stops working.
driver.closeApp();
driver.launchApp();
 
I am creating two separate instances of appium server with different ports as follows: 
        int port = Integer.parseInt(ap.getPort());
        String chromePort = ap.getPort();
        String bootstrapPort = ap.getPort();

        AppiumDriverLocalService service = AppiumDriverLocalService
            .buildService(new AppiumServiceBuilder()
. usingPort(port)
. withArgument(AndroidServerFlag.BOOTSTRAP_PORT_NUMBER, chromePort)
 .withArgument(GeneralServerFlag.SESSION_OVERRIDE)
.withArgument(AndroidServerFlag.CHROME_DRIVER_PORT, bootstrapPort));
service.start();


Capbilities 👍 
 DesiredCapabilities capabilities = DesiredCapabilities.android();
        capabilities.setCapability("deviceName", deviceName);
        capabilities.setCapability("platformName", "android");
        capabilities.setCapability(CapabilityType.VERSION, osVersion);
        capabilities.setCapability("udid", deviceId);
        capabilities.setCapability("appActivity", "");
        capabilities.setCapability("appPackage", "");
        capabilities.setCapability("noReset", "true");
        capabilities.setCapability("fullReset", "false");
        capabilities.setCapability("recreateChromeDriverSessions", true);
        capabilities.setCapability("nativeWebScreenshot", true);
 this.driver = new AndroidDriver(new URL("http://127.0.0.1:" + port + "/wd/hub"), capabilities);

Attached pom.xml

Appium version - 1.8.0beta



am i missing anything?


I am able to e
