### ISSUE TITLE
Appium iOS could enable faux-multi-app sessions

### ISSUE THREAD

**Issue by jlipps** [appium/appium#4442]
We could have a command that does a no-reset shutdown/restart with a designated bundle ID or app path. This would enable users to have the experience of automating multiple apps even though under the hood they're with different sessions, working around Apple's limitations with Instruments.

**Comment by ijazsarwar** [comment]
Does that mean we would be able to have multiple iOS devices connected to same mac and run tests parallel on all those devices (which is currently not possible)?

**Comment by jlipps** [comment]
i believe with xcuitest we can do multiple apps; closing this in favor of xcuitest support
