### ISSUE TITLE
Implement getSystemProperty(property)

### ISSUE THREAD

**Issue by willosser** [appium/appium#4444]
While testing android, we'd like to be able to obtain system properties for android devices. Adb provides us with the getprop comment. Can we get a method to obtain this information?  For example:
  driver.getSystemProperty(propertyName)
or specifically
  driver.getSystemProperty('ro.product.name')

I'm breaking this out from https://github.com/appium/appium/issues/3218

**Comment by jlipps** [comment]
Sure, I'll add it to a feature milestone

**Comment by artkoshelev** [comment]
:+1: waiting for this or could help implementing if you provide some guidance

**Comment by vietch2612** [comment]
awesome

**Comment by imurchie** [comment]
Device information is now collected.

**Comment by TheEmpty** [comment]
How is this exposed? I didn't see it in the Java Client API so I'm trying to dig through the commit history now to see if there is any information there. Perhaps it was renamed?
