### ISSUE TITLE
Implement bugreport as a log type for Android

### ISSUE THREAD

**Issue by willosser** [appium/appium#4446]
We'd like to gather the output of "adb bugreport".  Can this be added as a logtype?

Breaking out from https://github.com/appium/appium/issues/3218 into an individual issue

**Comment by jlipps** [comment]
yes, seems reasonable. adding to feature milestone.

**Comment by mykola-mokhnach** [comment]
@jlipps do we really need this feature? I mean the purpose bugreport is to report bug of the OS itself. Does it make any sense in scope of Appium automated testing?
