### ISSUE TITLE
error: Unexpected error: Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#4447]
The appium server got stopped by throwing the error: Unexpected error: Error: Can't set headers after they are sent." when i ran long run stability test in Iphone 6 with appium ver 1.3.4

Below is the detailed logs 
info: --> POST /wd/hub/session/4e01f703-8641-4698-a651-820deba2dd02/appium/app/close {"sessionId":"4e01f703-8641-4698-a651-820deba2dd02"}
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments
info: [debug] Instruments didn't terminate after 3 seconds; trying to kill it
info: [debug] Killall instruments
info: [debug] Stopping iOS log capture
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Responding to client with success: {"status":0,"value":"Successfully closed the [/var/folders/tr/29c5mtbs70qbyb055kdfp3wh0000gn/T/115025-511-1282x82/Payload/PocketAvatars.app] app.","sessionId":"4e01f703-8641-4698-a651-820deba2dd02"}
info: <-- POST /wd/hub/session/4e01f703-8641-4698-a651-820deba2dd02/appium/app/close 200 5008.283 ms - 198 {"status":0,"value":"Successfully closed the [/var/folders/tr/29c5mtbs70qbyb055kdfp3wh0000gn/T/115025-511-1282x82/Payload/PocketAvatars.app] app.","sessionId":"4e01f703-8641-4698-a651-820deba2dd02"}
info: --> POST /wd/hub/session/4e01f703-8641-4698-a651-820deba2dd02/appium/app/launch {"sessionId":"4e01f703-8641-4698-a651-820deba2dd02"}
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.1
info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /var/folders/tr/29c5mtbs70qbyb055kdfp3wh0000gn/T/115025-511-1282x82/Payload/PocketAvatars.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /var/folders/tr/29c5mtbs70qbyb055kdfp3wh0000gn/T/115025-511-1282x82/Payload/PocketAvatars.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings; assuming it doesn't exist
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/pocketavatar4/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.10.35/bin/node","commandProxyClientPath":"/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is automatically generat... Do not manually modify!
info: [debug] Dynamic bootstrap path: /Users/pocketavatar4/Library/Application Support/appium/bootstrap/bootstrap-147c7b56226ecf6b.js
info: [debug] Reusing dynamic bootstrap: /Users/pocketavatar4/Library/Application Support/appium/bootstrap/bootstrap-147c7b56226ecf6b.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone6","platformVersion":null}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone6 (8.1 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole
info: [debug] Not pre-launching simulator
info: [debug] Creating iDevice object with udid f8a82c6fd903b4e5fbcbf7ac029306a38fd4f5d8
info: [debug] Checking app install status using: /Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id f8a82c6fd903b4e5fbcbf7ac029306a38fd4f5d8 --bundle devcom.intel.pa.amsg.legacy
info: [debug] App is installed.
info: [debug] fullReset not requested. No need to install.
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID f8a82c6fd903b4e5fbcbf7ac029306a38fd4f5d8
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w f8a82c6fd903b4e5fbcbf7ac029306a38fd4f5d8 devcom.intel.pa.amsg.legacy -e UIASCRIPT "/Users/pocketavatar4/Library/Application Support/appium/bootstrap/bootstrap-147c7b56226ecf6b.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] 2015-01-25 03:44:24.248 instruments[35103:288720] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: Instruments is ready to receive commands
info: [debug] Instruments launched. Starting poll loop for new commands.
info: [debug] Setting bootstrap config keys/values
info: [debug] Pushing command to appium work queue: "target = $.target();\nau = $;\n$.isVerbose = true;\n"
info: [debug] Socket data received (2 bytes)
info: [debug] Socket data being routed.
info: [debug] Sending command to instruments: target = $.target();
au = $;
$.isVerbose = true;

info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Cleaning up after instruments exit
info: [debug] Stopping iOS log capture
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Responding to client with success: {"status":0,"value":"Successfully closed the [/var/folders/tr/29c5mtbs70qbyb055kdfp3wh0000gn/T/115025-511-1282x82/Payload/PocketAvatars.app] app.","sessionId":"4e01f703-8641-4698-a651-820deba2dd02"}
error: Unexpected error: Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    at ServerResponse.res.set.res.header (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/express/lib/response.js:561:10)
    at ServerResponse.res.send (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/express/lib/response.js:133:12)
    at ServerResponse.res.json (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/express/lib/response.js:210:15)
    at ServerResponse.res.send (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/express/lib/response.js:121:21)
    at /Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/lib/server/responses.js:89:9
    at safely (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/lib/server/helpers.js:306:5)
    at exports.respondSuccess (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/lib/server/responses.js:88:3)
    at /Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/lib/server/controller.js:159:5
    at null.<anonymous> (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/lib/devices/ios/ios.js:1348:5) context: [POST /wd/hub/session/4e01f703-8641-4698-a651-820deba2dd02/appium/app/close {"sessionId":"4e01f703-8641-4698-a651-820deba2dd02"}]
info: [debug] Socket data received (27 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":true}
info: [debug] Setting initial orientation to PORTRAIT
info: [debug] Pushing command to appium work queue: "au.setScreenOrientation('PORTRAIT')"
error: uncaughtException: Cannot read property 'status' of undefined date=Sun Jan 25 2015 03:44:29 GMT+0530 (IST), pid=511, uid=501, gid=20, cwd=/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium, execPath=/usr/local/Cellar/node/0.10.35/bin/node, version=v0.10.35, argv=[node, /usr/bin/appium, --address, 127.0.0.1, --port, 4725, --udid, f8a82c6fd903b4e5fbcbf7ac029306a38fd4f5d8, --app, /Users/pocketavatar4/Documents/pocketavatar/PA_3.5.32_ENG_US3D_20150123_133642.ipa], rss=102453248, heapTotal=79013584, heapUsed=47935176, loadavg=[1.9267578125, 1.7392578125, 1.6318359375], uptime=63018, trace=[column=21, file=/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/lib/devices/ios/ios.js, function=, line=417, method=null, native=false, column=43, file=/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/async/lib/async.js, function=next, line=801, method=null, native=false, column=16, file=/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/async/lib/async.js, function=null, line=32, method=null, native=false, column=36, file=/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/lib/devices/ios/ios.js, function=, line=1409, method=null, native=false, column=21, file=/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/async/lib/async.js, function=Object.q.process, line=809, method=q.process, native=false, column=27, file=/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/async/lib/async.js, function=next, line=806, method=null, native=false, column=16, file=/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/async/lib/async.js, function=null, line=32, method=null, native=false, column=9, file=/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/lib/devices/common.js, function=exports.respond, line=28, method=respond, native=false, column=18, file=/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/lib/devices/ios/ios.js, function=, line=1449, method=null, native=false, column=20, file=/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/appium-uiauto/lib/command-proxy.js, function=getResultAndSendNext, line=146, method=null, native=false], stack=[TypeError: Cannot read property 'status' of undefined,     at null.<anonymous> (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/lib/devices/ios/ios.js:417:21),     at next (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/async/lib/async.js:801:43),     at /Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/async/lib/async.js:32:16,     at null.<anonymous> (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/lib/devices/ios/ios.js:1409:36),     at Object.q.process (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/async/lib/async.js:809:21),     at next (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/async/lib/async.js:806:27),     at /Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/async/lib/async.js:32:16,     at exports.respond (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/lib/devices/common.js:28:9),     at null.<anonymous> (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/lib/devices/ios/ios.js:1449:18),     at getResultAndSendNext (/Users/pocketavatar4/Documents/appium_1.3.4/node_modules/appium/node_modules/appium-uiauto/lib/command-proxy.js:146:20)]
pocketavatar4s-Mac-mini:~ pocketavatar4$ appium --address "127.0.0.1" --port "4725" --udid "f8a82c6fd903b4e5fbcbf7ac029306a38fd4f5d8" --app "/Users/pocketavatar4/Documents/pocketavatar/PA_3.5.32_ENG_US3D_20150123_133642.ipa" 
pocketavatar4s-Mac-mini:~ pocketavatar4$ appium --address "127.0.0.1" --port "4725" --udid "f8a82c6fd903b4e5fbcbf7ac029306a38fd4f5d8" --app "/Users/pocketavatar4/Documents/pocketavatar/PA_3.5.32_ENG_US3D_20150123_133642.ipa"

**Comment by naveenjammula** [comment]
can you please provide the update when it is going to fix...

**Comment by naveenjammula** [comment]
can you please provide the update when it is going to fix...

**Comment by sebv** [comment]
Those errors are hard to track and it will improve with re-architecture/CI, but I suspect we need to wrap the response sending in _.once as a short term mesure, moving to next release.

**Comment by asnaith** [comment]
I just seen this same error happen on 1.3.6 with Android not iOS, hopefully this is helpful? It occurred during a test suite run of about 500 scenarios. All tests failed after the error was incurred. 

```
error: Unhandled error: Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19) context: [POST /wd/hub/session/4eaa0fe0-b53a-4
0f8-a54d-156a1e0ac88f/appium/app/launch {}]
info: [debug] UiAutomator exited
info: [debug] executing cmd: C:\AndroidSDK\platform-tools\adb.exe -s 0317f6bd216
0d377 shell "echo 'ping'"
info: [debug] Logcat terminated with code 0, signal null
info: [debug] Stopping logcat capture
info: [debug] Logcat already stopped
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] Error: ADB ping failed, returned: * daemon not running. starting i
t now on port 5037 *
* daemon started successfully *
ping
info: [debug] executing cmd: C:\AndroidSDK\platform-tools\adb.exe -s 0317f6bd216
0d377 kill-server
info: [debug] Waiting for device to be ready and to respond to shell commands (t
imeout = 640)
info: [debug] executing cmd: C:\AndroidSDK\platform-tools\adb.exe -s 0317f6bd216
0d377 wait-for-device
info: [debug] executing cmd: C:\AndroidSDK\platform-tools\adb.exe -s 0317f6bd216
0d377 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Attempting to uninstall app
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Cleaning up android objects
info: [debug] Responding to client with error: {"status":1,"value":{"message":"U
nable to launch the app: Error: UiAutomator died"},"sessionId":null}
error: Unexpected error: Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.set.res.header (c:\Users\andy\AppData\Roaming\npm\node
_modules\appium\node_modules\express\lib\response.js:561:10)
    at ServerResponse.res.send (c:\Users\andy\AppData\Roaming\npm\node_modules\a
ppium\node_modules\express\lib\response.js:133:12)
    at ServerResponse.res.json (c:\Users\andy\AppData\Roaming\npm\node_modules\a
ppium\node_modules\express\lib\response.js:210:15)
    at ServerResponse.res.send (c:\Users\andy\AppData\Roaming\npm\node_modules\a
ppium\node_modules\express\lib\response.js:121:21)
    at c:\Users\andy\AppData\Roaming\npm\node_modules\appium\lib\server\response
s.js:69:9
    at safely (c:\Users\andy\AppData\Roaming\npm\node_modules\appium\lib\server\
helpers.js:306:5)
    at exports.respondError (c:\Users\andy\AppData\Roaming\npm\node_modules\appi
um\lib\server\responses.js:68:3)
    at onErr (c:\Users\andy\AppData\Roaming\npm\node_modules\appium\lib\server\c
ontroller.js:147:5)
    at null.uiautomatorExitCb (c:\Users\andy\AppData\Roaming\npm\node_modules\ap
pium\lib\server\controller.js:153:5) context: [POST /wd/hub/session/4eaa0fe0-b53
a-40f8-a54d-156a1e0ac88f/appium/app/launch {}]
info: [debug] Logcat terminated with code 0, signal null
```

**Comment by naveenjammula** [comment]
duplicate of 4162
