### ISSUE TITLE
Appium 1.3.4-> Android-> Native App-> Missing addText possibility

### ISSUE THREAD

**Issue by ShiranDadon** [appium/appium#4449]
Using sendKeys() in current appium versions performs clear text before hand, to avoid stupid bugs, like the hint text etc.
However, for automation I need the ability to add text to a web element.
This is crucial for "special" text, like @mention or recipients in an email.
Why is that? Because, one I add @mention, I select a user or group from a list, and I want to add more text or more @mention... If I will simply append the text of the webElement and add everything from scratch, it will use the @mention is simple text (the name of the selected user)...
Same goes for all other types of "special" content (pictures, recipients, etc...).
We must have that possibility back...Please:)

**Comment by bootstraponline** [comment]
@jlipps we had this discussion before (added setText) and then ended up removing it. I think this use case supports bringing back the setText method.

**Comment by bootstraponline** [comment]
I guess since sendKeys is now effectively setText, the new method would be appendText.

**Comment by ShiranDadon** [comment]
@bootstraponline , small clarification: no need in iOS label, as in iOS sendKeys is still appendText

**Comment by bootstraponline** [comment]
I think we'd need appendText on iOS because send_keys should be clearing text on both Android and iOS. One of the other devs might be able to clarify how this is suppose to work.

**Comment by ShiranDadon** [comment]
Hi,
Can you tell me when are you planning on handling this?
Thanks!
Shiran

**Comment by ShiranDadon** [comment]
Hi, @bootstraponline  this is really urgent for us.
Any idea when will this be handled?

**Comment by Jonahss** [comment]
Can you clarify what we need to do for this ticket again? On iOS inside webviews, you need to do `setText` instead of `appendText`?

**Comment by ShiranDadon** [comment]
iOS behavior is less a concern for me. I mean, I am fine with having clearText as a separate action. Just change sendKeys on android to not clear the text for me

**Comment by jlipps** [comment]
the uiautomator `.setText()` method clears the text whether we want it to or not. maybe there's another way to input text using adb? isn't there already a ticket about this @bootstraponline ?

**Comment by bootstraponline** [comment]
> maybe there's another way to input text using adb?

adb shell input text

> isn't there already a ticket about this @bootstraponline ?

yes, https://github.com/appium/appium/issues/4864#issuecomment-90738035

**Comment by bootstraponline** [comment]
what we need to do is implement setImmediateValue on Android using adb shell input text. the bindings already support this method.

**Comment by bootstraponline** [comment]
[setValueImmediate](https://github.com/appium/appium/blob/84e84584042d0242704c8a98e92b87a7ac74ceda/lib/server/routing.js#L140) is what it's called on the node.js server

**Comment by bootstraponline** [comment]
Also as of [API 21](https://developer.android.com/reference/android/app/UiAutomation.html#executeShellCommand(java.lang.String)) uiautomation (the API behind droiddriver/uiautomator) is able to execute adb shell commands for us on the device itself. I think it'd be worth using this execution method when possible for better reliability (adb is flaky).

**Comment by jlipps** [comment]
> I think it'd be worth using this execution method when possible for better reliability (adb is flaky).

Absolutely

**Comment by jlipps** [comment]
closing this as a duplicate, then will create a new issue for the adb topic
