### ISSUE TITLE
Invalid coordinates on iOS

### ISSUE THREAD

**Issue by marcopashkov** [appium/appium#4450]
I am running custom monkey tests on **Android** and **iOS**. For *Android* everything works just fine, but for *iOS* it **crashes** with `tap point is not within the bounds of the screen`. It seems like there is a bug with the `TouchAction` on iOS.

Here is a sample code:

```python
from appium.webdriver.common.touch_action import TouchAction

def test_max_screen_size(appium_driver):

    driver = appium_driver

    window_size = driver.get_window_size()
    max_width = window_size["width"] - 1
    max_height = window_size["height"] - 1 

    action = TouchAction(driver)
    action.tap(None, max_width, max_height).perform()
```

Is there a way to debug this and figure out if this is an Appium bug or if something else might go wrong?

Could this be connected to #4360 ?

**Comment by marcopashkov** [comment]
I added more info [here](http://stackoverflow.com/questions/28199128/how-to-get-the-maximum-width-and-height-coordinates-of-an-ios-device-display-in).

**Comment by marcopashkov** [comment]
Ok - found the **bug**! 

What is going on is that on **Android** the `get_window_size` function implicitly returns the size of the application window - (not the device resolution as I expected). 
On **iOS** however the function returns the device-resolution. 

The reason why my test crashes on **iOS** is that the clicks are always performed relative to the application window and not the full device screen. (Personally I think this is very limiting, as for instance iOS allows you to click anywhere with `UIAutomation`, but that's another story). As **iOS** returns the *wrong* dimensions my script crashes. 

At the very least Appium should be coherent between **iOS** and **Android**. Meaning, `get_window_size` should return either the device-resolution OR application-window-size. 

You can get more background in my [stackoverflow question](http://stackoverflow.com/questions/28199128/how-to-get-the-maximum-width-and-height-coordinates-of-an-ios-device-display-in).

**Comment by moizjv** [comment]
interesting we can look into this.

**Comment by SrinivasanTarget** [comment]
@triager please close
