### ISSUE TITLE
Is it possible to hide the android keyboard [Soft Keyboard] while automating the websites in Google Chrome using appium.

### ISSUE THREAD

**Issue by Ankit9568** [appium/appium#4452]
I am trying  to hide keyboard like this
Code
{
  AndroidDriver driver = new Android Driver()
  driver.hideKeyboard()
}
 
Above Code produces an Exception:
unknown command: session/7e2d986344b962e3dc4dbc52cfb5e111/appium/device/hide_keyboard"

Also I am trying the press the Back Button
{
  driver.sendKeyEvent(AndroidKeyCode.BACK);
}

Exception:
unknown command: session/df47b665af02780b174571e427169401/appium/device/keyevent

Resources using:
Appium Server -                    1.3.4.1
Appium Java Client library-    2.1.0

Any help is greatly appreciated.

**Comment by tarunHub** [comment]
you can use driver.navigate.back() by creating an object of selenium web driver

**Comment by Ankit9568** [comment]
Thanks tarunHub for reply
driver.navigate.back()  
driver navigate the back page of website

**Comment by tarunHub** [comment]
but sir same is working for mobile as well.... its tried and tested sir....
i have used it in my scripts and its working fine.

**Comment by Ankit9568** [comment]
Thanks tarunHub For reply

Please try with MyScript 

{
         driver = new AndroidDriver(new URL("http://localhost" + ":" + 4723 + "/wd/hub"),     chromeCapabilities());
				driver.navigate().to("https://login.live.com/");
				WebElement btnSighnIn = driver.findElement(By.id("idSIButton9"));
				btnSighnIn.click();

				Thread.sleep(5000);
				driver.navigate().back();
                              // After back It navigates back on previous page of website			

				WebElement signLink = driver.findElement(By.id("idA_SignUp"));
				signLink.click();

}

Any help will be greatly appreciated

**Comment by tarunHub** [comment]
I have tried hiding my android keyboard for my native app by creating an object of webdriver.
here the sample code:

package AndriodAutomatioSession;

import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.Test;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.*;

public class OssCampTestScript {
	public WebDriver driver;
	 @BeforeMethod
		public void setUp() {
			
		File classpathRoot=new File(System.getProperty("user.dir"));
		File appDir = new File(classpathRoot,"/app");
		File app = new File(appDir, "OssCamp.apk");
		DesiredCapabilities capabilities=new DesiredCapabilities();
		capabilities.setCapability("browserName","");
		capabilities.setCapability("deviceName","Android");
		capabilities.setCapability("platformVersion","4.2.2");
		capabilities.setCapability("platformName","Android");
		capabilities.setCapability("app", app.getAbsolutePath());
		capabilities.setCapability("appPackage","com.xyz.camp");
	        capabilities.setCapability("appActivity","xyzActivity");
//		capabilities.setCapability("appWaitActivity","com.xyz.AuthActivity");
		try {		
		    driver =new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
				} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	try {
		Thread.sleep(5000);
	} catch (InterruptedException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	}
	 @AfterMethod
	 	 public void quitdriver(){
		 driver.quit();
	 }
	 @Test(priority=1)
		public void logInValid(){
	List<WebElement> credentials = driver.findElements(By.className("android.widget.EditText")); 
	List<WebElement> buttons = driver.findElements(By.className("android.widget.Button"));
	credentials.get(0).sendKeys("campuser");
	credentials.get(1).sendKeys("messi");
	driver.navigate().back();
		
	buttons.get(1).click();
			try {
				Thread.sleep(5000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	String loginSuccess=driver.findElement(By.className("android.widget.TextView")).getText();
	Assert.assertEquals(loginSuccess,"OSSCamp");		
	 }
}

**Comment by Ankit9568** [comment]
Thanks tarunHub For reply

driver.hideKeyboard() method  and  driver.navigate().back() is working for Android application 
But both methods is not working while automating the websites in Google Chrome using appium
Exception shown in the first dicussion.

Any help will be highly appreciated

**Comment by tarunHub** [comment]
you can use javascript exectuor for the same
HashMap<String, Integer> keycode = new HashMap<String, Integer>();
keycode.put("keycode", 4);
((JavascriptExecutor)driver).executeScript("mobile: keyevent", keycode);

**Comment by Ankit9568** [comment]
Thanks tarunHub For Reply

When I am Using the javascript exectuor for down the keyboard

Facing  the Exception 
  Not yet implemented. Please help us: http://appium.io/get-involved.html

Appium Server Log:
> info: --> POST /wd/hub/session/645c518d065ac08d784987a26396f680/execute {"script":"mobile: keyevent","args":[{"keycode":4}]}
> info: [debug] Tried to execute non-existent mobile command 'keyevent'. Most mobile commands have been ported to official client library methods. Please check your Appium library for more information and documentation
> info: [debug] Responding to client that a method is not implemented

Any help would be greatly appreciated

**Comment by sebv** [comment]
You need to switch context if you want to use appium specific method, otherwise Appium just automate using Chromedriver.

**Comment by Ankit9568** [comment]
Thanks sebv for replying After switch context its working

**Comment by dipti076** [comment]
((AndroidDriver) driver).sendKeyEvent(AndroidKeyCode.BACK);

**Comment by dipti076** [comment]
Try this code

**Comment by praveentata** [comment]
When I am trying to hide the keyboard using driver.hideKeyboard() --> it works but after that it deleted two characters for the field where the focus is.
For eg. --> First Name field has --> 'Test'
hideKeyboard(); --> will hide the keyboard
then it will delete two character and First Name field will then have --> 'Te'

Is this a know issue? Or am I doing something wrong?

**Comment by abvijay** [comment]
@Ankit9568  "Thanks sebv for replying After switch context its working" can u plz post the code here to switch context and hiding keypad
