### ISSUE TITLE
Manage ios-webkit-debug-proxy within appium.

### ISSUE THREAD

**Issue by sebv** [appium/appium#4454]
On real device, when the whole thing hangs and we don't get webviews anymore, the solution would be to restart the proxy, which we cannot do from within appium.

**Comment by jlipps** [comment]
This is also a general user experience improvement, since users would not have to remember to start it, and we could vary the port to support multiple device scenarios.

**Comment by mayureshshirodkar** [comment]
@jlipps  is this feature available in the 1.6.4 Beta release to test?

**Comment by dpgraham** [comment]
No, it's still in progress. I'm working on it right now and we should have it by the next release.

**Comment by dpgraham** [comment]
Acceptance criteria:

*[ ] Add API to appium-ios-simulator that adds calendar access to TCC.db
*[ ] Update https://github.com/appium/ios-test-app to include a use case where authorization status for calendar access is displayed
*[ ] Update https://github.com/appium/appium-xcuitest-driver to include a new dcap for enabling calendar and a functional test that proves that it has authority to access calendar
