### ISSUE TITLE
Switch Browser Window Node.js

### ISSUE THREAD

**Issue by amaanmemon** [appium/appium#4458]
return driver.getWindowHandle()
            .then(function(data_first) {
                console.log(data_first);
                windowObjects.push(data_first); // i am clicking after this step
                console.log(windowObjects[0]);
                driver.switchTo().window(windowObjects[0]);   
            }, function(err) {
                console.log(err)
            });

**Comment by imurchie** [comment]
I'm not sure what your problem is or what you want.

**Comment by amaanmemon** [comment]
Hey @imurchie  i was struggling to switch between two tabs of chrome on android using node.js
and i found the solution: 

  it("Should Switch Between Two Windows", function() {

        return driver.getAllWindowHandles()
            .then(function(windowObjects) {
                driver.switchTo().window(windowObjects[1]);
                driver.close();
                driver.switchTo().window(windowObjects[0]);
            }, function(err) {
                console.log(err)
            });
    });
