### ISSUE TITLE
Instruments crashed on startup iphone 6 plus

### ISSUE THREAD

**Issue by nabeel-ibrahim** [appium/appium#4459]
I cannot start the app on my iPhone 6 plus which has iOS 8.1.3. I can start the app on my iPhone 6 which also has iOS 8.1.3. I checked the UDID and the app location as well as enabling the UI Automation button in Developer settings. The log is below. I am using Appium 3.15-beta and XCode 6.1.1 on OSX 10.10.1

[36minfo[39m: Welcome to Appium v1.3.5-beta (REV 63e51239d06aa517ffb8ac45ac108c506b470335)
[36minfo[39m: Appium REST http interface listener started on 127.0.0.1:4723
[36minfo[39m: [debug] Non-default server args: {"address":"127.0.0.1","bootstrapPort":4725,"noReset":true}
[36minfo[39m: Console LogLevel: debug
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"app":"/Users/nibrahim/Documents/workspace/myApp/iOS/myApp.ipa","nativeInstrumentsLib":"false","platformVersion":"8.1.3","bundleid":"com.myApp.ios.develop","udid":"4583929daf9dc9cde1683a2ec5fd802fd1feece1","platformName":"iOS","deviceName":"iPhone","autoAcceptAlerts":"true"}}[39m
[36minfo[39m: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
[33mwarn[39m: Converting cap nativeInstrumentsLib from string to boolean. This might cause unexpected behavior.
[33mwarn[39m: Converting cap autoAcceptAlerts from string to boolean. This might cause unexpected behavior.
[36minfo[39m: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : bundleid
[36minfo[39m: [debug] Using local .ipa from desired caps: /Users/nibrahim/Documents/workspace/myApp/iOS/myApp.ipa
[36minfo[39m: [debug] Copying local zip to tmp dir
[36minfo[39m: [debug] /Users/nibrahim/Documents/workspace/myApp/iOS/myApp.ipa copied to /var/folders/t3/pvzg022d6f30z9q1lysnkmx98fvgxw/T/115029-69502-17zjy5l/appium-app.zip
[36minfo[39m: [debug] Unzipping /var/folders/t3/pvzg022d6f30z9q1lysnkmx98fvgxw/T/115029-69502-17zjy5l/appium-app.zip
[36minfo[39m: [debug] Testing zip archive: /var/folders/t3/pvzg022d6f30z9q1lysnkmx98fvgxw/T/115029-69502-17zjy5l/appium-app.zip
[36minfo[39m: [debug] Zip archive tested clean
[36minfo[39m: [debug] Unzip successful
[36minfo[39m: [debug] Using locally extracted app: /var/folders/t3/pvzg022d6f30z9q1lysnkmx98fvgxw/T/115029-69502-17zjy5l/Payload/myApp.app
[36minfo[39m: [debug] Creating new appium session 818b154c-1f84-4343-9273-89e94b626105
[36minfo[39m: [debug] Removing any remaining instruments sockets
[36minfo[39m: [debug] Cleaned up instruments socket /tmp/instruments_sock
[36minfo[39m: [debug] Setting Xcode folder
[36minfo[39m: [debug] Setting Xcode version
[36minfo[39m: [debug] Setting iOS SDK Version
[36minfo[39m: [debug] Getting sdk version from xcrun with a timeout
[36minfo[39m: [debug] iOS SDK Version set to 8.1
[36minfo[39m: [debug] Not checking whether simulator is available since we're on a real device
[36minfo[39m: [debug] Detecting automation tracetemplate
[36minfo[39m: [debug] Not auto-detecting udid, running on sim
[36minfo[39m: [debug] Could not parse plist file (as binary) at /var/folders/t3/pvzg022d6f30z9q1lysnkmx98fvgxw/T/115029-69502-17zjy5l/Payload/myApp.app/en.lproj/Localizable.strings
[36minfo[39m: Will try to parse the plist file as XML
[36minfo[39m: [debug] Could not parse plist file (as XML) at /var/folders/t3/pvzg022d6f30z9q1lysnkmx98fvgxw/T/115029-69502-17zjy5l/Payload/myApp.app/en.lproj/Localizable.strings
[33mwarn[39m: Could not parse app Localizable.strings assuming it doesn't exist
[36minfo[39m: [debug] Getting bundle ID from app
[36minfo[39m: [debug] Parsed app Info.plist (as binary)
[36minfo[39m: [debug] Creating instruments
[36minfo[39m: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
[36minfo[39m: [debug] Preparing uiauto bootstrap
[36minfo[39m: [debug] Dynamic bootstrap dir: /Users/nibrahim/Library/Application Support/appium/bootstrap
[36minfo[39m: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":true,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
[36minfo[39m: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
[36minfo[39m: [debug] Dynamic bootstrap path: /Users/nibrahim/Library/Application Support/appium/bootstrap/bootstrap-228b5fe9dfaaccb0.js
[36minfo[39m: [debug] Reusing dynamic bootstrap: /Users/nibrahim/Library/Application Support/appium/bootstrap/bootstrap-228b5fe9dfaaccb0.js
[36minfo[39m: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone","platformVersion":"8.1.3"}
[36minfo[39m: [debug] fixDevice is on
[36minfo[39m: [debug] Final device string is: 'iPhone (8.1.3 Simulator)'
[36minfo[39m: [debug] Not setting device type since we're on a real device
[36minfo[39m: [debug] Checking whether we need to set app preferences
[36minfo[39m: [debug] Not setting iOS and app preferences since we're on a real device
[36minfo[39m: [debug] Reset not set, not ending sim or cleaning up app state
[36minfo[39m: [debug] Not setting locale because we're using a real device
[36minfo[39m: [debug] No iOS / app preferences to set
[36minfo[39m: [debug] Starting iOS device log capture via deviceconsole
[36minfo[39m: [debug] Not pre-launching simulator
[36minfo[39m: [debug] Creating iDevice object with udid 4583929daf9dc9cde1683a2ec5fd802fd1feece1
[36minfo[39m: [debug] Checking app install status using: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id 4583929daf9dc9cde1683a2ec5fd802fd1feece1 --bundle com.myApp.ios.develop
[36minfo[39m: [debug] App is installed.
[36minfo[39m: [debug] fullReset not requested. No need to install.
[36minfo[39m: [debug] Starting command proxy.
[36minfo[39m: [debug] Instruments socket server started at /tmp/instruments_sock
[36minfo[39m: [debug] Starting instruments
[36minfo[39m: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
[36minfo[39m: Launching instruments
[36minfo[39m: [debug] Attempting to run app on real device with UDID 4583929daf9dc9cde1683a2ec5fd802fd1feece1
[36minfo[39m: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 4583929daf9dc9cde1683a2ec5fd802fd1feece1 com.myApp.ios.develop -e UIASCRIPT "/Users/nibrahim/Library/Application Support/appium/bootstrap/bootstrap-228b5fe9dfaaccb0.js" -e UIARESULTSPATH /tmp/appium-instruments
[36minfo[39m: [debug] And extra without-delay env: {}
[36minfo[39m: [debug] And launch timeouts (in ms): {"global":90000}
[36minfo[39m: [debug] [90m[INSTSERVER] Instruments exited with code 253[39m
[36minfo[39m: [debug] Killall instruments
[36minfo[39m: [debug] Instruments crashed on startup
[36minfo[39m: [debug] Attempting to retry launching instruments, this is retry #1
[36minfo[39m: [debug] Killall iOS Simulator
[36minfo[39m: Launching instruments
[36minfo[39m: [debug] Attempting to run app on real device with UDID 4583929daf9dc9cde1683a2ec5fd802fd1feece1
[36minfo[39m: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 4583929daf9dc9cde1683a2ec5fd802fd1feece1 com.myApp.ios.develop -e UIASCRIPT "/Users/nibrahim/Library/Application Support/appium/bootstrap/bootstrap-228b5fe9dfaaccb0.js" -e UIARESULTSPATH /tmp/appium-instruments
[36minfo[39m: [debug] And extra without-delay env: {}
[36minfo[39m: [debug] And launch timeouts (in ms): {"global":90000}
[36minfo[39m: [debug] [90m[INSTSERVER] Instruments exited with code 253[39m
[36minfo[39m: [debug] Killall instruments
[36minfo[39m: [debug] Instruments crashed on startup
[36minfo[39m: [debug] Attempting to retry launching instruments, this is retry #2
[36minfo[39m: [debug] Killall iOS Simulator
[36minfo[39m: Launching instruments
[36minfo[39m: [debug] Attempting to run app on real device with UDID 4583929daf9dc9cde1683a2ec5fd802fd1feece1
[36minfo[39m: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 4583929daf9dc9cde1683a2ec5fd802fd1feece1 com.myApp.ios.develop -e UIASCRIPT "/Users/nibrahim/Library/Application Support/appium/bootstrap/bootstrap-228b5fe9dfaaccb0.js" -e UIARESULTSPATH /tmp/appium-instruments
[36minfo[39m: [debug] And extra without-delay env: {}
[36minfo[39m: [debug] And launch timeouts (in ms): {"global":90000}
[36minfo[39m: [debug] [90m[INSTSERVER] Instruments exited with code 253[39m
[36minfo[39m: [debug] Killall instruments
[36minfo[39m: [debug] Instruments crashed on startup
[36minfo[39m: [debug] Attempting to retry launching instruments, this is retry #3
[36minfo[39m: [debug] Killall iOS Simulator
[36minfo[39m: Launching instruments
[36minfo[39m: [debug] Attempting to run app on real device with UDID 4583929daf9dc9cde1683a2ec5fd802fd1feece1
[36minfo[39m: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 4583929daf9dc9cde1683a2ec5fd802fd1feece1 com.myApp.ios.develop -e UIASCRIPT "/Users/nibrahim/Library/Application Support/appium/bootstrap/bootstrap-228b5fe9dfaaccb0.js" -e UIARESULTSPATH /tmp/appium-instruments
[36minfo[39m: [debug] And extra without-delay env: {}
[36minfo[39m: [debug] And launch timeouts (in ms): {"global":90000}
[36minfo[39m: [debug] [90m[INSTSERVER] Instruments exited with code 253[39m
[36minfo[39m: [debug] Killall instruments
[36minfo[39m: [debug] Instruments crashed on startup
[36minfo[39m: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
[36minfo[39m: [debug] Stopping iOS log capture
[36minfo[39m: [debug] Reset not set, not ending sim or cleaning up app state
[36minfo[39m: [debug] Cleaning up appium session
[31merror[39m: Failed to start an Appium session, err was: Error: Instruments crashed on startup
[36minfo[39m: [debug] Error: Instruments crashed on startup
    at Instruments.onInstrumentsExit (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:389:31)
    at null.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:308:12)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)
[36minfo[39m: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments crashed on startup)","origValue":"Instruments crashed on startup"},"sessionId":null}
[36minfo[39m: [37m<-- POST /wd/hub/session [39m[31m500[39m[90m 25750.132 ms - 182[39m [90m[39m

**Comment by kirillzh** [comment]
I am facing this issue as well. Log errors are the same.

**Comment by ateremetskyi** [comment]
Same problem... Appium: 1.3.5 iOS: 8.1.3

**Comment by nabeel-ibrahim** [comment]
any luck getting this resolved? @kirillzh @ateremetskyi

**Comment by kirillzh** [comment]
Yes, I found solution:
https://github.com/appium/appium/issues/4126#issuecomment-73761613

**Comment by nabeel-ibrahim** [comment]
@kirillzh were you having this issue on all devices? I am having the issue only on my 6+. I have the same provisioning profiles on both my devices (iPhone 6 and iPhone 6+) but for the 6+ i keep getting instruments crashed on startup error.  I have tried two different 6+s and both have the same error.

**Comment by kirillzh** [comment]
I was having this issue on iPhone 6 and iPhone 5s devices. Another iPhone 5s was fine.

**Comment by nabeel-ibrahim** [comment]
I updated to the latest appium ap (1.3.5) and instruments still crashes but I get some more info. The log is below.
info: Launching instruments

info: [debug] Attempting to run app on real device with UDID 5ea052a6fd72d004232fd86da7bcec0a138b0472
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 5ea052a6fd72d004232fd86da7bcec0a138b0472 com.thescore.ios.develop -e UIASCRIPT "/Users/nibrahim/Library/Application Support/appium/bootstrap/bootstrap-2911698fabce8e2c.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2015-02-11 14:56:49.326 instruments[61665:4026989] Connection peer refused channel request for "com.apple.instruments.server.services.capabilities"; channel canceled <DTXChannel: 0x7f7f9caa51d0>
info: [debug] [INST STDERR] 2015-02-11 14:56:49.327 instruments[61665:4026990] Connection peer refused channel request for "com.apple.instruments.server.services.launchdaemon"; channel canceled <DTXChannel: 0x7f7f9caa12e0>

info: [debug] [INST STDERR] 2015-02-11 14:56:49.328 instruments[61665:4026990] Connection peer refused channel request for "com.apple.instruments.server.services.device.xpccontrol"; channel canceled <DTXChannel: 0x7f7f9ca6b260>
info: [debug] [INST STDERR] 2015-02-11 14:56:49.329 instruments[61665:4026990] Connection peer refused channel request for "com.apple.instruments.server.services.deviceinfo"; channel canceled <DTXChannel: 0x7f7f9caa36d0>
2015-02-11 14:56:49.329 instruments[61665:4026990] Connection peer refused channel request for "com.apple.instruments.server.services.processcontrol"; channel canceled <DTXChannel: 0x7f7f9ca62c00>
2015-02-11 14:56:49.329 instruments[61665:4026990] Connection peer refused channel request for "com.apple.instruments.server.services.processcontrol.posixspawn"; channel canceled <DTXChannel: 0x7f7f9cd53ac0>
info: [debug] [INST STDERR] 2015-02-11 14:56:49.330 instruments[61665:4026990] Connection peer refused channel request for "com.apple.instruments.server.services.mobilenotifications"; channel canceled <DTXChannel: 0x7f7f9cd51940>
info: [debug] [INST STDERR] 2015-02-11 14:56:49.330 instruments[61665:4026990] Connection peer refused channel request for "com.apple.instruments.server.services.device.applictionListing"; channel canceled <DTXChannel: 0x7f7f9ca60c00>
info: [debug] [INST STDERR] 2015-02-11 14:56:49.361 instruments[61665:4026989] Connection peer refused channel request for "com.apple.instruments.server.services.wireless"; channel canceled <DTXChannel: 0x7f7f9cd44fc0>

info: [debug] [INST STDERR] 2015-02-11 14:56:49.518 instruments[61665:4026983] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [debug] [INSTSERVER] Instruments exited with code 253
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Cleaning up appium session
info: [debug] Error: Instruments crashed on startup
    at Instruments.onInstrumentsExit (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:389:31)
    at null.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:308:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments crashed on startup)","origValue":"Instruments crashed on startup"},"sessionId":null}

error: Failed to start an Appium session, err was: Error: Instruments crashed on startup

**Comment by kirillzh** [comment]
Did you try method, which I provided in previous comment?

**Comment by nabeel-ibrahim** [comment]
I build the app locally from XCode and it worked!!!

**Comment by kirillzh** [comment]
Great! You're welcome.
