### ISSUE TITLE
Add public method to unlock screen

### ISSUE THREAD

**Issue by willosser** [appium/appium#4465]
The Appium server can unlock the screen, but that method is not exposed to the driver.

We'd also like to detect if the screen is on or not, and to turn it on if it's not, which is needed before unlocking the screen.

**Comment by imurchie** [comment]
Adding to next milestone.

**Comment by jlipps** [comment]
moved to feature milestone

**Comment by jlipps** [comment]
I believe this exists, somehow it must have been added in the interim?
