### ISSUE TITLE
Can't unlock android screen

### ISSUE THREAD

**Issue by brbrr** [appium/appium#4470]
Unable to unlock real Samsung GT-I9195 device with appium test. same test goes well on emulator
here is logcat log: http://pastebin.com/5WYGnWmx
and appium server log: http://pastebin.com/rZ44H8Ft

**Comment by bhaskar-appium** [comment]
Try this in your code for unlock the screen: 
Runtime.getRuntime().exec("adb shell am start -n io.appium.unlock/.Unlock");

Hope this works fine :)

**Comment by moizjv** [comment]
@brbrr any update?

**Comment by brbrr** [comment]
@moizjv yes, problem is actually voided. I have pattern lock screen, so it's caused that issues. when I switch it to swipe lock - everything smooth now.

So I closing this one

**Comment by brbrr** [comment]
Recently appear again. Same device, appium 1.4.0, appium_lib 7.0.0
Problem with Unlock app - it unlock screen successfully, but cant recognize it. (so after 1t unlock try I can tap on any icon)

New logcat log: http://pastebin.com/V7JFMZDX
new appium log: http://pastebin.com/6mU2pBRW

**Comment by moizjv** [comment]
#5080 we are tracking it there so closing it because of duplicate
