### ISSUE TITLE
Cant launch Settings app on iPhone using Appium

### ISSUE THREAD

**Issue by kani19** [appium/appium#4471]
I need to change some settings before automating my application. But i am not able to launch Settings app on iPhone.
________________
Error
________________
info: [debug] [INST STDERR] 2015-02-02 23:49:46.344 instruments[35142:507] unable to locate CFBundleIdentifier for path: com.apple.Preferences

info: [debug] [INST STDERR] Instruments Trace Error : Error Starting Recording

info: [debug] [INSTSERVER] Instruments exited with code 253

This is the error i am getting.

Logs:

info: [debug] Responding to client with success: {"status":0,"value":[]}
info: <-- GET /wd/hub/sessions 200 1.356 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"7.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone"}}

info: Client User-Agent string: Appium (unknown version) CFNetwork/673.2.1 Darwin/13.1.0 (x86_64) (MacBookPro8%2C1)

info: [debug] App is an iOS bundle, will attempt to run as pre-existing

info: [debug] Creating new appium session 3134a0e7-7749-49ec-a801-020e759be6f7

info: [debug] Removing any remaining instruments sockets

info: [debug] Cleaned up instruments socket /tmp/instruments_sock

info: [debug] Setting Xcode folder

info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 7.1

info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate

info: [debug] Not auto-detecting udid, running on sim

parseFileSync() is deprecated. Use parseStringSync() instead.

info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.apple.Preferences/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.apple.Preferences/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings; assuming it doesn't exist
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/kvedi/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"grouped"}

info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

info: [debug] Dynamic bootstrap path: /Users/....../appium/bootstrap/bootstrap-0943baae6b1d6f5b.js

info: [debug] Creating or overwritting dynamic bootstrap: /Users/....../appium/bootstrap/bootstrap-0943baae6b1d6f5b.js

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.1","iOSSDKVersion":"7.1","deviceName":"iPhone","platformVersion":"7.1"}

info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone - Simulator - iOS 7.1" to: "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1"
info: [debug] Final device string is: 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Not setting locale because we're using a real device

info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole

info: [debug] Not pre-launching simulator

info: [debug] Creating iDevice object with udid c8.............eb3
info: [debug] Couldn't find ideviceinstaller, trying built-in at /Applications/Appium.app/Contents/Resources/node_modules/appium/build/libimobiledevice-macosx/ideviceinstaller
info: [debug] Checking app install status using: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id c..........eb3 --bundle com.apple.Preferences

info: [debug] App is installed.

info: [debug] fullReset not requested. No need to install.
info: [debug] Starting command proxy.

info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID c..................eb3
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w c.............eb3 com.apple.Preferences -e UIASCRIPT "/Users/kvedi/Library/Application Support/appium/bootstrap/bootstrap-0943baae6b1d6f5b.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2015-02-02 23:49:39.193 instruments[35139:507] unable to locate CFBundleIdentifier for path: com.apple.Preferences

info: [debug] [INST STDERR] Instruments Trace Error : Error Starting Recording

info: [debug] [INSTSERVER] Instruments exited with code 253

info: [debug] Killall instruments

info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iPhoneSimulator

**Comment by jlipps** [comment]
It's not possible to launch the settings app on a real device, only the simulator.

**Comment by vinothannamalai** [comment]
Hi jlipps,

Then how should i automate enabling Wifi through Appium?

Please answer me.

Thanks in advance,

Vinoth

**Comment by rajeshchaudhary1** [comment]
Hi Lipps,

Please let me know the command to launch the settings in simulator using appium? Is is possible to launch setting during app automation and do some changes and again resume the app testing? 

Thanks,

**Comment by jlipps** [comment]
You can just set the `app` capability to "settings" to launch the settings app. You can only automate one app per session. But if you use multiple sessions you can automate both apps.

**Comment by dankiiing** [comment]
@jlipps Hi Jonathan, has there been any improvements to this ?

**Comment by raysurc** [comment]
Hi @jlipps. Has there been any changes to this? I have a similar situation where I want to make changes in the real devices' iOS settings, then verify changes in my app. Is there still no way to do this context switching in one session? If not, can you show me how to manage multiple sessions to get this test situation developed?
