### ISSUE TITLE
android webview tests failing

### ISSUE THREAD

**Issue by jlipps** [appium/appium#4472]
chromedriver seems to be confused:

```
~/C/appium-jlipps git:new-chromedriver ❯❯❯ DEVICE=android mm test/functional/android/webview-specs.js


  android - webview @skip-ci
    ✓ should list all contexts
    ✓ should raise NoSuchContext (status: 35)
    ✓ should find and click an element
    ✓ should clear input @skip-selendroid-all
    ✓ should find and enter key sequence in input @skip-selendroid-all
    ✓ should be able to handle selendroid special keys @skip-android-all
    ✓ should get web source
    ✓ should be able to move into and out of webview with proper proxying (6860ms)
    1) should be able to get into a webview even after the webview ChromeDriver has is closed @skip-selendroid-all


  8 passing (22s)
  1 failing

  1) android - webview @skip-ci should be able to get into a webview even after the webview ChromeDriver has is closed @skip-selendroid-all:
     AssertionError: expected promise not to be rejected but it was rejected with { Object (message, showDiff, ...) }
```

Relevant bit from appium logs:

```
info: --> POST /wd/hub/session/3ade6108-e0d1-4769-a996-45f5abd994a9/context {"name":"WEBVIEW"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /usr/local/adt/sdk/platform-tools/adb -s emulator-5554 shell "cat /proc/net/unix"
info: [debug] WEBVIEW_2171 mapped to pid 2171
info: [debug] Getting process name for webview
info: [debug] executing cmd: /usr/local/adt/sdk/platform-tools/adb -s emulator-5554 shell "ps"
info: [debug] WEBVIEW_4921 mapped to pid 4921
info: [debug] Getting process name for webview
info: [debug] executing cmd: /usr/local/adt/sdk/platform-tools/adb -s emulator-5554 shell "ps"
info: [debug] Parsed pid: 2171 pkg: com.android.browser
info: [debug] from: u0_a15,2171,959,1313184,103740,ffffffff,74373a2a,S,com.android.browser
info: [debug] returning process name: com.android.browser
info: [debug] Parsed pid: 4921 pkg: io.appium.android.apis
info: [debug] from: u0_a60,4921,959,1232508,90712,ffffffff,74373a2a,S,io.appium.android.apis
info: [debug] returning process name: io.appium.android.apis
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_io.appium.android.apis,WEBVIEW_com.android.browser
info: [debug] ["WEBVIEW_com.android.browser","WEBVIEW_io.appium.android.apis"]
info: [debug] Available contexts: NATIVE_APP,WEBVIEW_com.android.browser,WEBVIEW_io.appium.android.apis
info: [debug] Connecting to chrome-backed webview
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: We already have a chromedriver instance running)","origValue":"We already have a chromedriver instance running"},"sessionId":"3ade6108-e0d1-4769-a996-45f5abd994a9"}
info: <-- POST /wd/hub/session/3ade6108-e0d1-4769-a996-45f5abd994a9/context 500 142.814 ms - 282
info: --> DELETE /wd/hub/session/3ade6108-e0d1-4769-a996-45f5abd994a9 {}
info: Shutting down appium session
info: [debug] Pressing the HOME button
info: [debug] executing cmd: /usr/local/adt/sdk/platform-tools/adb -s emulator-5554 shell "input keyevent 3"
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] Stopping chromedriver for context WEBVIEW_com.android.browser
info: Proxying [DELETE /] to [DELETE http://127.0.0.1:9515/wd/hub/session/c0a7862561a3ab57c8f724c3c5587bde] with no body
info: Got response with status 200: {"sessionId":"c0a7862561a3ab57c8f724c3c5587bde","status":0,"value":null}
info: [debug] Chromedriver for context WEBVIEW_com.android.browser stopped
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 14.64
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] UiAutomator shut down normally
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"3ade6108-e0d1-4769-a996-45f5abd994a9"}
info: <-- DELETE /wd/hub/session/3ade6108-e0d1-4769-a996-45f5abd994a9 200 406.843 ms - 76 {"status":0,"value":null,"sessionId":"3ade6108-e0d1-4769-a996-45f5abd994a9"}
```

Could it be related to the bug I thought I uncovered in working on #4388?

> I also wonder if I've come across a bug in our handling of android webviews. Every time we create a new chromedriver, we run a command that kills all chromedrivers on the port we want to use. But we want to have multiple chromedrivers active---one for each webview. However we don't do any cleverness with making sure each Chromedriver instance runs on a different port. So my hypothesis is that with the current code (in appium master), we kill all the non-active context chromedrivers whenever we switch to a new chromedriver context. It seemed odd to me that we'd be doing this, so I didn't do anything to fix it in this pull request, but it probably warrants investigation.

**Comment by jlipps** [comment]
@0x1mason I added this to 1.3.5. Can you see if you can repro?

**Comment by 0x1mason** [comment]
On it.

**Comment by 0x1mason** [comment]
@jlipps These tests are super flaky.

**Comment by 0x1mason** [comment]
Have repro'd but it's intermittent.

**Comment by 0x1mason** [comment]
Related issue:
https://code.google.com/p/android/issues/detail?id=69132

Logcat shows the same content when the WebView tests fail.

**Comment by 0x1mason** [comment]
I'm taking another look at your logs and realize that I'm not seeing the issue described there.  My problem is the test fails because android.webkit.WebView is never found.  I've run the test probably 100 times and not had an issue with `We already have a chromedriver instance running`.

**Comment by 0x1mason** [comment]
Good news and bad news.

Good:
* I never repro'd the ChromeDriver issue in your logs. (this is possibly bad, I guess)
* The WebView tests passed without issue on API 21.  I ran them ~50x.
* Confirmed the failure to find the WebView exists in 1.3.4.
* I ran the `find` tests on API 19 around 20x and they passed consistently.

Bad:
* The failure rate of `should be able to get into a webview even after the webview ChromeDriver has is closed` is 15-20% on API 19.  The others pass consistently.
* I don't think the problem is in our code.
* Can't try possible hacks because Bootstrap is based on UIAutomator and cannot interact with system services other than UIAutomation.
* Unless we're willing to leave our codebase, afaict it isn't fixable.


We should get rid of ChromeDriver.
* We don't need it since the WebKit Remote Debugging Protocol is public.  There's [a Node module for WRDP](https://github.com/cyrus-and/chrome-remote-interface), though it's not very complicated from what I've seen so far.
* WebView touch actions have been available the entire time, we just have to contact the WebView directly via WRDP.
* We should make the removal part of a larger 3rd party component and dependency cull.

**Comment by jlipps** [comment]
> We should get rid of ChromeDriver.

I don't agree. ChromeDriver is a large project maintained well that has native access to Chrome. We already use the webkit remote debugging protocol for our iOS hybrid/web automation and we've encountered various limitations with it. No way to do performance logging, has to do everything via javascript so it gets confused automating some apps, etc...

I also don't agree that 3rd-party dependencies are bad. They are good if they work well and it limits the amount of code we have to write and maintain.

If there's something wrong with ChromeDriver we should raise a bug and they'll fix it. They've done this a number of times in the past based on our feedback.

**Comment by 0x1mason** [comment]
@jlipps They're not "bad", but they're not free nor do they necessarily
result in a smaller support burden than if we provide our own
implementation.  If we can figure out how to use CD as a library, that'd be
preferable.  As a separate WD process it's redundant, inefficient, and
managing it has already been the source of numerous issues. If we can
figure out how to get rid of it altogether without a large cost, I'm not
sure how that's objectionable.

**Comment by jlipps** [comment]
One of my points is that ChromeDriver can just do things that we can't with WKRD because it has privileged native access to Chrome.

I don't think we're going to settle this issue here, and at any rate it's not high priority to figure this out right now.

(Also you might be interested to know that I actually implemented WKRD-based Android hybrid support  before switching to ChromeDriver long ago.)

**Comment by 0x1mason** [comment]
I think that's a great point re privileged access--one I didn't know and
certainly won't argue with.  I'd still prefer to use it as a library.
Definitely agree about it not being high priority.
