### ISSUE TITLE
unable to swipe using appium on any of my app screens which are scollable???

### ISSUE THREAD

**Issue by srk9ravi** [appium/appium#4474]
ios, I am unable to swipe using appium on any of my app screens which are scrollable.

how to resolve this issue??

**Comment by srk9ravi** [comment]
my ios screen contains kind of two seperations... one is with card image and other part with data ... we can scroll at any part of the screen to got to the next on the device... but it is not working with appium.

**Comment by moizjv** [comment]
@srk9ravi can you see if `mobile: scroll` works? [documentation](https://github.com/moizjv/appium/blob/scroll-doc/docs/en/writing-running-appium/touch-actions.md)

**Comment by sebv** [comment]
duplicate.
