### ISSUE TITLE
Is there any way i can send key events to ios device

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#4479]
I want to press the Home key in iOS by using the python script. Please let me know how to proceed

**Comment by amedvedjev** [comment]
only in simulator:

Runtime runtime = Runtime.getRuntime();
String[] args = {"osascript", "-e", "tell application \"System Events\" \n tell application \"iOS Simulator\" to activate \n tell application \"System Events\" to keystroke \"h\" using {command down, shift down} \n end tell"};
runtime.exec(args);

**Comment by naveenjammula** [comment]
i want to send Home key on real iOS device

**Comment by omoskovko** [comment]
I want too but as I understand there is no possibility to do it on real iOS device because of xcode limitation.

**Comment by imurchie** [comment]
Given that you cannot automate another app, why do you want to press the `Home` key?

**Comment by omoskovko** [comment]
With Android I can press Home button and send application to the background or start another application. I need it to test notification message that my application send when it appear in background.

**Comment by imurchie** [comment]
But you cannot do that in iOS. Android allows you to open multiple apps and automate them. iOS does not. Unfortunately.

**Comment by omoskovko** [comment]
It's not true. In iOS-7 you can open notification window and press calc button. After that my application go to the background and calculator we'll be in foreground. And I can receive notification message from my application. If you want to see how I do that look in code bellow.

```
    def start_calc(self):
        CR_Window = self.driver.find_element_by_ios_uiautomation('UIATarget.localTarget().frontMostApp().mainWindow()')
        end_y = CR_Window.size['height']
        self.driver.swipe(20, end_y, 20, 100)
        self.check_elem_by_name('Calculator').click()
        self.check_elem_by_name('Result')
```

**Comment by moizjv** [comment]
Does not look like an issue.  Unfortunately is a limitation by iOS

**Comment by rutin31** [comment]
imurchie commented on 4 Feb 2015
But you cannot do that in iOS. Android allows you to open multiple apps and automate them. iOS does not. Unfortunately.
--
Has something changed in the last appium(betta 1.6.6) version for ios ?
