### ISSUE TITLE
[Android] UIAutomator method scrollIntoView does not work with strings containing commas

### ISSUE THREAD

**Issue by ktronic80** [appium/appium#4482]
Appium 1.3.4
Java client: 2.1.0
Android 4.3 (Emulator)

Hi,

regarding to my workaround to #4481 another problem popped up for me. I'm doing the following to scroll an element in to the view:

String uiSelector = "new UiSelector().textContains(\"" + idValue + "\")";
String command = "new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(" + uiSelector + ".instance(0));";
driver.findElementByAndroidUIAutomator(command);

This works fine until the string in idValue contains commas, in this case I see the following error 
"Could not parse UiSelector argument: UiScrollable has no \"scrollIntoView\" method that takes 2 arguments"

Appium log:

info: [debug] Pushing command to appium work queue: ["find",{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\"Star Wars 37819, Electronic Blaster, Trooper\").instance(0));","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\"Star Wars 37819, Electronic Blaster, Trooper\").instance(0));","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains("Star Wars 37819, Electronic Blaster, Trooper").instance(0)); using ANDROID_UIAUTOMATOR with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains("Star Wars 37819, Electronic Blaster, Trooper").instance(0))
info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Could not parse UiSelector argument: UiScrollable has no \"scrollIntoView\" method that takes 2 arguments","status":9}
info: [debug] Condition unmet after 7ms. Timing out.
info: [debug] Responding to client with error: {"status":9,"value":{"message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.","origValue":"Could not parse UiSelector argument: UiScrollable has no \"scrollIntoView\" method that takes 2 arguments"},"sessionId":"8a00cf11-13ed-438b-8933-b3e787c71581"}
info: <-- POST /wd/hub/session/8a00cf11-13ed-438b-8933-b3e787c71581/element 500 7.661 ms - 341

I have no idea what I'm doing wrong. Is it necessary to escape the the commas somehow?

**Comment by gualber98** [comment]
Hello @ktronic80 
have you try .textStartsWith(String text) instead of .textContains(String text)

**Comment by ktronic80** [comment]
Its the same for textStartsWith(String text).

info: [debug] Pushing command to appium work queue: ["find",{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textStartsWith(\"RAYHER - 14396420 - Acryl-Mosaik, Glitter, selbstklebend, 5mm, quad., SB-Btl. 144 Stück,3 Farben, wiesengrün\").instance(0));","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textStartsWith(\"RAYHER - 14396420 - Acryl-Mosaik, Glitter, selbstklebend, 5mm, quad., SB-Btl. 144 Stück,3 Farben, wiesengrün\").instance(0));","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textStartsWith("RAYHER - 14396420 - Acryl-Mosaik, Glitter, selbstklebend, 5mm, quad., SB-Btl. 144 Stück,3 Farben, wiesengrün").instance(0)); using ANDROID_UIAUTOMATOR with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textStartsWith("RAYHER - 14396420 - Acryl-Mosaik, Glitter, selbstklebend, 5mm, quad., SB-Btl. 144 Stück,3 Farben, wiesengrün").instance(0))
info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Could not parse UiSelector argument: UiScrollable has no \"scrollIntoView\" method that takes 4 arguments","status":9}

**Comment by ktronic80** [comment]
I think the cause for the problem is in the splitArgs methods in io.appium.android.bootstrap.utils.UiScrollableParser. If get it right it just ignores the quotes and treats the string as parameter list in which the values are separated by commas.

**Comment by gualber98** [comment]
ScrollTo() method is very unstable, therefore and work around it is that I make my own ways of scrolling.  You can also scroll to an element instead of using text description.  For example
uiScript =
		"new UiScrollable("+uiScroller+")"+
		".setMaxSearchSwipes("+maxSearchSwipes+")"+
		".scrollIntoView("+ uiElement+ ")";
uiScroller = scroller object.  (Element that is scrollable)	
uiElement = The element to search
maxSearchSwipes = (integer) sets number of swipes to search for element.

Hope this helps.

**Comment by ktronic80** [comment]
Thanks, I already have solution build around the Appium swipe method and thought the scrollTo would be an easier solution. Your solution looks nice, I will try it.

**Comment by jlipps** [comment]
@Jonahss looks like there's something weird with the uiautomator parsing here (it's treating a comment in a string as an argument separator?)

**Comment by Jonahss** [comment]
Yeah, looks like a comma in the string is getting parsed as an arg separator. Definitely a bug and shouldn't be hard to fix.

**Comment by vietnq254** [comment]
Please help to fix this problem in the next version 1.4.0.
I see the version 1.4.0-beta still has this problem.

**Comment by Jonahss** [comment]
Yes, 1.4-beta still has this problem, if the problem had been solved then we would close the issue.
I can request to see if we can put this on the roadmap for the next release.

You can also take a look at the code in appium-uiauto project if you want to submit a pull request to fix this.

**Comment by thezaria** [comment]
up! are there any news about this bug? When it supposed to be fixed?

**Comment by SrinivasanTarget** [comment]
We have deprecated this in java client.So closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by smaspe** [comment]
@SrinivasanTarget Hi! Can you explain what exactly you have deprecated that makes this issue obsolete? It seems it appears whenever you use `findElementByAndroidUIAutomator` with a `UiScrollable.scrollIntoView`, does it not?
