### ISSUE TITLE
Cam we automate Phonegap applications using Appium ?

### ISSUE THREAD

**Issue by priyanka-agarwal** [appium/appium#4486]
I am trying to automate Phonegap application using Appium . Till now I have tried for Android. I am trying to capture element locators using UI Automator viewer & Appium Inspector but I am unable to do so . On the Inspector it is shoeing only upto WebView , the remaining part I am not able to capture .I think the reason behind this is Phonegap applications are build using HTML.

Also I tried to capture the locators on Browser and then tried to automate using this locators. However it failed saying "Locator not found"

Can you please tell me whether it is possible to automate Phonegap applications using Appium . If so how can we capture locators here. 
Plz help.

Thanks, Priyanka

**Comment by 0x1mason** [comment]
Please look at our documentation on hybrid applications. If you have further questions, try the community at http://discuss.appium.io. Thanks :)
