### ISSUE TITLE
Document usage of chromeOptions

### ISSUE THREAD

**Issue by thevinci** [appium/appium#4487]
How do I set this to the chrome driver?

```
Map<String, Object> contentSettings = new HashMap<String, Object>();
contentSettings.put("images", 2);

Map<String, Object> preferences = new HashMap<String, Object>();
preferences.put("profile.default_content_settings", contentSettings);

DesiredCapabilities caps = DesiredCapabilities.chrome();
caps.setCapability("chrome.prefs", preferences);
```

https://code.google.com/p/chromedriver/issues/detail?id=20

**Comment by kirillzh** [comment]
I think, that's similar to WebDriver:
Try this: http://stackoverflow.com/questions/14480717/load-chrome-profile-using-selenium-webdriver

**Comment by moizjv** [comment]
Looks like a feature request

**Comment by SrinivasanTarget** [comment]
@scottdixon @imurchie @moizjv can we please close this? We have this in https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md
