### ISSUE TITLE
getFocusedPackageAndActivity should be better at finding the current activity

### ISSUE THREAD

**Issue by willosser** [appium/appium#4489]
From a discussion at https://discuss.appium.io/t/obtaining-the-current-activity/2676/5

"I think it's common for them (mCurrentFocus and mFocusedApp) to not match such as when the keyguard is up. It sounds like this is a bug in our getFocusedPackageAndActivity method. The regex should be updated to search for both mCurrentFocus and mFocusedApp. If mCurrentFocus is found then that's the more accurate value. Sometimes mCurrentFocus is empty and then we'd fall back to mFocusedApp."

**Comment by 0x1mason** [comment]
Will take a look at this, thanks.

**Comment by mykola-mokhnach** [comment]
Closed as fixed
