### ISSUE TITLE
Multitouch api fails for double tap with cannot read property 'element' of undefined 

### ISSUE THREAD

**Issue by glorylo** [appium/appium#4491]
This issue is likely another issue of #4310.  

I am using the C# client with :  

```
          new TouchAction(driver)
                .Tap(point.X, point.Y, count: 2)
                .Perform(); 
```

Here's the trace:
```
> info: --> POST /wd/hub/session/8d6776f8-b84f-4fb5-ba04-4237bef7ba74/touch/perform {"actions":[{"action":"press","options":{"x":540,"y":1050}},{"action":"wait","options":{"ms":50}},{"action":"release"},{"action":"wait","options":{"ms":100}},{"action":"press","options":{"x":540,"y":540}},{"action":"wait","options":{"ms":50}},{"action":"release"}]}
> info: <-- POST /wd/hub/session/8d6776f8-b84f-4fb5-ba04-4237bef7ba74/touch/perform 500 0.804 ms - 97 
>     at Array.filter (native)
>     at Function._.filter._.select (C:\Workspace\appium\node_modules\underscore\underscore.js:173:65)
>     at _.(anonymous function) [as filter] (C:\Workspace\appium\node_modules\underscore\underscore.js:1178:39)
>     at null.<anonymous> (C:\Workspace\appium\lib\devices\android\android-controller.js:912:47)
>     at androidController.performTouch (C:\Workspace\appium\lib\devices\android\android-controller.js:990:5)
>     at Object.exports.performTouch [as handle] (C:\Workspace\appium\lib\server\controller.js:331:14)
>     at next_layer (C:\Workspace\appium\node_modules\express\lib\router\route.js:113:13)
>     at Route.dispatch (C:\Workspace\appium\node_modules\express\lib\router\route.js:117:5)
>     at C:\Workspace\appium\node_modules\express\lib\router\index.js:222:24

```

NOTE:  The {"action":"press","options":{"x":540,"y":540}} looks very suspicious as the "y" I am expecting it to be 1050

**Comment by imurchie** [comment]
Yes, it seems like this is ill-implemented in the C# client. Can you open an issue there?

**Comment by glorylo** [comment]
i created this issue under https://github.com/appium/appium-dotnet-driver/issues/79

**Comment by glorylo** [comment]
can someone investigate the part about y coordinates likely incorrect.  That may likely be an issue with appium once i get pass the this issue.

The part with {"action":"press","options":{"x":540,"y":540}} expecting "y" to to be 1050

**Comment by imurchie** [comment]
That is just what the client is sending. The error is on that side. (The error on the other issue was also on the client side, but that could be checked and fixed in the server. This one cannot, as there is no way to know that it is not what you actually want to do.)

**Comment by imurchie** [comment]
Closing. The client needs to be updated.
