### ISSUE TITLE
In Appium 1.3.5-beta version user is not able to "Choose" iOS app path

### ISSUE THREAD

**Issue by ShreyasPatil** [appium/appium#4492]
Hi,

I have downloaded Appium 1.3.5-beta version.
When I tried to set iOS app path I observed that "Choose" button is not functioning as expected. i.e. I am not able to browse my iOS app path.

Note: Setting app path for android app is working as expected.

Please refer screen recording.
https://docs.google.com/file/d/0B0AtHlSAkXSQNDlGMTFoSFRzM00/edit

**Comment by moizjv** [comment]
@ShreyasPatil looks like a .app issue. Raising it there https://github.com/appium/appium-dot-app/issues/485
