### ISSUE TITLE
Safari stuck at apple.com, with 2 drivers (iPhone Simulator)

### ISSUE THREAD

**Issue by kani19** [appium/appium#4496]
So this is the scenario:

1. Launch my app on iPhone Simulator (7.1). [XCode 5.1] in one session:
DesiredCapabilities capabilities_cc = new DesiredCapabilities();  
	     	capabilities_cc.setCapability("automationName", "Appium"); 
	     	capabilities_cc.setCapability("platformName", "iOS");
	     	capabilities_cc.setCapability("deviceName", "iPhone Simulator");
	     	capabilities_cc.setCapability("platformVersion", "7.1");
	     	capabilities_cc.setCapability("app", "myApp.app");  
	     	capabilities_cc.setCapability("showIOSLog", "true");
	       driver1 = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities_cc);  
	       driver1.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
	      driver1.quit();

2. Launch Safari with another driver:

	       	DesiredCapabilities capabilities_safari = new DesiredCapabilities();  
	        capabilities_safari.setCapability("automationName", "Appium"); 
	       	capabilities_safari.setCapability("platformName", "iOS");
	       	capabilities_safari.setCapability("deviceName", "iPhone Simulator");
	       	capabilities_safari.setCapability("platformVersion", "7.1");
	       	capabilities_safari.setCapability("browserName", "Safari");
	       	capabilities_safari.setCapability("newCommandTimeout", "120");
	       	capabilities_safari.setCapability("app", "Safari");
	        driver2 = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities_safari);  
	        Thread.sleep(3000);
	        driver2.get("http://google.com/");	        
	        driver2.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
	        System.out.println(driver2.getPageSource()); 

	        driver2.quit();

Now, everything works, but Safari does not open google.com. Instead, it stays at apple.com

Any help ?

**Comment by Jonahss** [comment]
Try removing the `app` capability. Just saying `browserName: Safari` should be enough.
Using `app: Safari` is opening safari, but not switching you to the Webview Context (I think)
