### ISSUE TITLE
how to inspect the elements in android and iOS in chrome or mozilla browser..

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#4497]

**Comment by naveenjammula** [comment]
How to inspect the elements in android and iOS in chrome or mozilla browser. I am not able to inspect the elements through ui automator or appium inspecter

**Comment by Jonahss** [comment]
Hmm, well you can automate those browsers using Appium, and can get the elements inside of the webviews. Read the documentation on [Context Switching](https://discuss.appium.io/t/what-does-the-autowebview-desired-capability-really-do/69).
