### ISSUE TITLE
No documentation available for appium source code

### ISSUE THREAD

**Issue by sjrjanardhana** [appium/appium#4498]
Hi,
I thought start working on appium source and start contributing to open source.
But i don't know where to start and proper documentation available. If possible can you provide some instruction how to start  which IDE is the best to use it?

**Comment by p00j4** [comment]
checkout: https://github.com/appium/appium/blob/master/CONTRIBUTING.md

**Comment by p00j4** [comment]
Though these IDEs doesn't give full support for development since debugging doesn't seem feasible [or may be there is different way to debug node js application in these IDE which I'm not aware of as of now]  I wonder, if from Saucelabs, anyone can talk about a right IDE

**Comment by sjrjanardhana** [comment]
yes we do have some documentation about running sources, but if some one newbie like me can not understand the architecture of the Appium server ( i mean the flow between the components ). i feel if this can be provided more users will be able start contributing to Appium.

**Comment by sebv** [comment]
You can debug in Chrome using node-inspector. I suspect most of us don't use IDE, just vim or Sublime Text.

Yeah we should have this kind of doc, but the best place to start is to understand how the devices send command in and out.

**Comment by sjrjanardhana** [comment]
Please let me know the module path for the above

**Comment by sebv** [comment]
For iOS it's in the `appium-uiauto` package, for Android it's in lib/devices/android/bootstrap.

**Comment by sebv** [comment]
@sjrjanardhana please open an issue in the discussion forum if needed, we try to keep this for bugs.
