### ISSUE TITLE
ios 8.1 Real Device Safari throwing error

### ISSUE THREAD

**Issue by tarunsujit** [appium/appium#4499]
I am using Mac OS X 10.10
iPhon5 8.1.1
Xcode 6.1.1
Appium Running from Git Source.
starting proxy by: ios_webkit_debug_proxy -c ffeb80d83ee1ff4fcffe91ae9dd6d7aa57018506:27753-27758 -d
Created Provisioning Profile with this SafariLauncher https://github.com/budhash/SafariLauncher

Using Caps: 
capabilities.setCapability("deviceName", "iPhones"); 
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("platformVersion", "8.1.1");
capabilities.setCapability("browserName", "safari");

I am getting below error message in ios WebKit Debug Log:

 62 70 6C 69 73 74 30 30 D1 01 02 5F 10 12 57 49 52 46 69  bplist00..._..WIRFi
 6E 61 6C 4D 65 73 73 61 67 65 4B 65 79 4F 11 01 74 62 70  nalMessageKeyO..tbp
 6C 69 73 74 30 30 D2 01 02 03 04 5A 5F 5F 73 65 6C 65 63  list00.....Z__selec
 74 6F 72 5A 5F 5F 61 72 67 75 6D 65 6E 74 5F 10 18 5F 72  torZ__argument_.._r
 70 63 5F 61 70 70 6C 69 63 61 74 69 6F 6E 55 70 64 61 74  pc_applicationUpdat
 65 64 3A D6 05 06 07 08 09 0A                             ed:.......
 0B 0C 0D 0E 0F 10 5F 10 21 57 49 52 41 70 70 6C 69 63 61  ......_.!WIRApplica
 74 69 6F 6E 42 75 6E 64 6C 65 49 64 65 6E 74 69 66 69 65  tionBundleIdentifie
 72 4B 65 79 5F 10 1F 57 49 52 48 6F 73 74 41 70 70 6C 69  rKey_..WIRHostAppli
 63 61 74 69 6F 6E 49 64 65 6E 74 69 66 69 65 72 4B 65 79  cationIdentifierKey
 5F 10 15 57 49 52 41 70 70 6C 69 63 61 74 69 6F 6E 4E 61  _..WIRApplicationNa
 6D 65 4B 65 79 5F 10 18 57 49 52 49 73 41 70 70 6C 69 63  meKey_..WIRIsApplic
 61 74 69 6F 6E 50 72 6F 78 79 4B 65 79 5F 10 19 57 49 52  ationProxyKey_..WIR
 49 73 41 70 70 6C 69 63 61 74 69 6F 6E 41 63 74 69 76 65  IsApplicationActive
 4B 65 79 5F 10 1B 57 49 52 41 70 70 6C 69 63 61 74 69 6F  Key_..WIRApplicatio
 6E 49 64 65 6E 74 69 66 69 65 72 4B 65 79 5F 10 1B 63 6F  nIdentifierKey_..co
 6D 2E 61 70 70 6C 65 2E 57 65 62 4B 69 74 2E 57 65 62 43  m.apple.WebKit.WebC
 6F 6E 74 65 6E 74 58 50 49 44 3A 31 36 30 31 50 09 10 00  ontentXPID:1601P...
 58 50 49 44 3A 31 36 30 33 00 08 00 0D 00 18 00 23 00 3E  XPID:1603.......#.>
 00 4B 00 6F 00 91 00 A9 00 C4 00 E0 00 FE 01 1C 01 25 01  .K.o.............%.
 26 01 27 01 29 00 00 00 00 00 00 02 01 00 00 00 00 00 00  &.'.)..............
 00 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 32 00  .................2.
 08 00 0B 00 20 00 00 00 00 00 00 02 01 00 00 00 00 00 00  .... ..............
 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 98     ..................
wi.recv_packet[450]:
 00 00 01 BE 62 70 6C 69 73 74 30 30 D1 01 02 5F 10 12 57  ....bplist00..._..W
 49 52 46 69 6E 61 6C 4D 65 73 73 61 67 65 4B 65 79 4F 11  IRFinalMessageKeyO.
 01 74 62 70 6C 69 73 74 30 30 D2 01 02 03 04 5A 5F 5F 73  .tbplist00.....Z__s
 65 6C 65 63 74 6F 72 5A 5F 5F 61 72 67 75 6D 65 6E 74 5F  electorZ__argument_
 10 18 5F 72 70 63 5F 61 70 70 6C 69 63 61 74 69 6F 6E 55  .._rpc_applicationU
 70 64 61 74 65 64 3A D6 05 06 07 08 09 0A                 pdated:.......
 0B 0C 0D 0E 0F 10 5F 10 21 57 49 52 41 70 70 6C 69 63 61  ......_.!WIRApplica
 74 69 6F 6E 42 75 6E 64 6C 65 49 64 65 6E 74 69 66 69 65  tionBundleIdentifie
 72 4B 65 79 5F 10 1F 57 49 52 48 6F 73 74 41 70 70 6C 69  rKey_..WIRHostAppli
 63 61 74 69 6F 6E 49 64 65 6E 74 69 66 69 65 72 4B 65 79  cationIdentifierKey
 5F 10 15 57 49 52 41 70 70 6C 69 63 61 74 69 6F 6E 4E 61  _..WIRApplicationNa
 6D 65 4B 65 79 5F 10 18 57 49 52 49 73 41 70 70 6C 69 63  meKey_..WIRIsApplic
 61 74 69 6F 6E 50 72 6F 78 79 4B 65 79 5F 10 19 57 49 52  ationProxyKey_..WIR
 49 73 41 70 70 6C 69 63 61 74 69 6F 6E 41 63 74 69 76 65  IsApplicationActive
 4B 65 79 5F 10 1B 57 49 52 41 70 70 6C 69 63 61 74 69 6F  Key_..WIRApplicatio
 6E 49 64 65 6E 74 69 66 69 65 72 4B 65 79 5F 10 1B 63 6F  nIdentifierKey_..co
 6D 2E 61 70 70 6C 65 2E 57 65 62 4B 69 74 2E 57 65 62 43  m.apple.WebKit.WebC
 6F 6E 74 65 6E 74 58 50 49 44 3A 31 36 30 31 50 09 10 00  ontentXPID:1601P...
 58 50 49 44 3A 31 36 30 33 00 08 00 0D 00 18 00 23 00 3E  XPID:1603.......#.>
 00 4B 00 6F 00 91 00 A9 00 C4 00 E0 00 FE 01 1C 01 25 01  .K.o.............%.
 26 01 27 01 29 00 00 00 00 00 00 02 01 00 00 00 00 00 00  &.'.)..............
 00 11 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 32 00  .................2.
 08 00 0B 00 20 00 00 00 00 00 00 02 01 00 00 00 00 00 00  .... ..............
 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 98     ..................
Invalid message _rpc_applicationUpdated: <dict>
	<key>WIRApplicationBundleIdentifierKey</key>
	<string>com.apple.WebKit.WebContent</string>
	<key>WIRHostApplicationIdentifierKey</key>
	<string>PID:1601</string>
	<key>WIRApplicationNameKey</key>
	<string></string>
	<key>WIRIsApplicationProxyKey</key>
	<true/>
	<key>WIRIsApplicationActiveKey</key>
	<integer>0</integer>
	<key>WIRApplicationIdentifierKey</key>
	<string>PID:1603</string>
</dict>
ss.remove_fd(6)
Disconnected :27753 from iPhoneS (ffeb80d83ee1ff4fcffe91ae9dd6d7aa57018506)
ss.remove_server_fd(4)
ss.remove_fd(5)

I am getting these logs in Appium:

info: [debug] [INST] 2015-02-05 14:03:24 +0000 Debug: Running system command #3: /usr/local/bin/node /Users/sujittarun/GitHub/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"Safari","label":"Safari","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","...
info: [debug] Socket data received (7215 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"Safari","label":"Safari","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":20,"width":320,"height":548},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"vali
info: [debug] Waiting for 4000 ms before navigating to view.
info: [debug] Navigating to most recently opened webview
info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
info: [debug] Picking webview WEBVIEW_2
info: [debug] Attempting to set context to 'WEBVIEW_2'
info: [debug] [REMOTE] Debugger web socket connected to url [ws://localhost:27753/devtools/page/2]
info: [debug] [REMOTE] Unregistering from page readiness notifications
info: [debug] Device launched! Ready for commands
info: [debug] Setting command timeout to the default of 60 secs
info: [debug] Appium session started with sessionId e6d90816-df1e-4987-9277-c88dc68d5cfd
info: <-- POST /wd/hub/session 303 20267.060 ms - 9 
info: --> GET /wd/hub/session/e6d90816-df1e-4987-9277-c88dc68d5cfd {}
info: [debug] Responding to client with success: {"status":0,"value":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"safari","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"platformVersion":"8.1","deviceName":"iPhoneS","platformName":"iOS","browserName":"safari"},"platformVersion":"8.1","deviceName":"iPhoneS","platformName":"iOS","safari":true},"sessionId":"e6d90816-df1e-4987-9277-c88dc68d5cfd"}
info: <-- GET /wd/hub/session/e6d90816-df1e-4987-9277-c88dc68d5cfd 200 2.382 ms - 474 {"status":0,"value":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"safari","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"platformVersion":"8.1","deviceName":"iPhoneS","platformName":"iOS","browserName":"safari"},"platformVersion":"8.1","deviceName":"iPhoneS","platformName":"iOS","safari":true},"sessionId":"e6d90816-df1e-4987-9277-c88dc68d5cfd"}
info: [debug] [REMOTE] Disconnecting from remote debugger
info: --> POST /wd/hub/session/e6d90816-df1e-4987-9277-c88dc68d5cfd/url {"url":"http://www.gmail.com"}
info: [debug] [REMOTE] Navigating to new URL: http://www.gmail.com
info: [debug] [REMOTE] Remote debugger data sent [{"method":"Page.navigate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"url":"http://www.gmail.com"},"id":1}...]
info: <-- POST /wd/hub/session/e6d90816-df1e-4987-9277-c88dc68d5cfd/url 500 6.057 ms - 87 
TypeError: Cannot call method 'send' of null
    at WebKitRemoteDebugger.send (/Users/sujittarun/GitHub/appium/lib/devices/ios/webkit-remote-debugger.js:164:15)
    at RemoteDebugger.navToUrl (/Users/sujittarun/GitHub/appium/lib/devices/ios/remote-debugger.js:366:8)
    at iOSController.url (/Users/sujittarun/GitHub/appium/lib/devices/ios/ios-controller.js:1468:17)
    at Object.exports.postUrl [as handle] (/Users/sujittarun/GitHub/appium/lib/server/controller.js:989:16)
    at next_layer (/Users/sujittarun/GitHub/appium/node_modules/express/lib/router/route.js:113:13)
    at Route.dispatch (/Users/sujittarun/GitHub/appium/node_modules/express/lib/router/route.js:117:5)
    at /Users/sujittarun/GitHub/appium/node_modules/express/lib/router/index.js:222:24
    at param (/Users/sujittarun/GitHub/appium/node_modules/express/lib/router/index.js:307:14)
    at param (/Users/sujittarun/GitHub/appium/node_modules/express/lib/router/index.js:323:14)
    at Function.proto.process_params (/Users/sujittarun/GitHub/appium/node_modules/express/lib/router/index.js:367:3)
info: [debug] Didn't get a new command in 60 secs, shutting down...
info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments
info: [debug] [INST] 2015-02-05 14:04:38 +0000 Stopped: Script was stopped by the user
info: [debug] [INST] Instruments Trace Complete (Duration : 84.811821s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Stopping iOS log capture
info: [debug] [REMOTE] Executing 'execute_script' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Remote debugger data sent [{"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var g=this;\nfunctio...]
error: Unhandled error: TypeError: Cannot call method 'send' of null
    at WebKitRemoteDebugger.send (/Users/sujittarun/GitHub/appium/lib/devices/ios/webkit-remote-debugger.js:164:15)
    at RemoteDebugger.execute (/Users/sujittarun/GitHub/appium/lib/devices/ios/remote-debugger.js:336:10)
    at RemoteDebugger.executeAtom (/Users/sujittarun/GitHub/appium/lib/devices/ios/remote-debugger.js:267:8)
    at iOSController.executeAtom (/Users/sujittarun/GitHub/appium/lib/devices/ios/ios-controller.js:646:15)
    at iOSController.closeWindow (/Users/sujittarun/GitHub/appium/lib/devices/ios/ios-controller.js:1749:10)
    at iOSHybrid.stopRemote [as _stopRemote] (/Users/sujittarun/GitHub/appium/lib/devices/ios/ios-hybrid.js:226:12)
    at Safari.stopRemote (/Users/sujittarun/GitHub/appium/lib/devices/ios/safari.js:150:8)
    at IOS.postCleanup (/Users/sujittarun/GitHub/appium/lib/devices/ios/ios.js:1350:10)
    at IOS.shutdown (/Users/sujittarun/GitHub/appium/lib/devices/ios/ios.js:1402:8)
    at null.<anonymous> (/Users/sujittarun/GitHub/appium/lib/devices/ios/ios.js:1393:14) context: [POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"8.1","deviceName":"iPhoneS","platformName":"iOS","browserName":"safari"}}]

**Comment by imurchie** [comment]
This is a problem with the ios-webkit-debug-proxy library. Can you try out the fix [here](https://github.com/google/ios-webkit-debug-proxy/issues/79)?

**Comment by 0x1mason** [comment]
@imurchie Do you think we should consider switching to the iwdp fork?

**Comment by tarunsujit** [comment]
This has been fixed by using (jchuong fix)[https://github.com/jchuong/ios-webkit-debug-proxy] myself. thanks.
You can close this ticket

**Comment by 0x1mason** [comment]
@tarunsujit, we still need to fix it for others, hopefully by getting an updated version of iwdp in our next release.

**Comment by 0x1mason** [comment]
Glad you got it working tho!

**Comment by tarunsujit** [comment]
@0x1mason Can me put this proxy inside our Appium server. instead of starting it manually all the time?

**Comment by imurchie** [comment]
@0x1mason I think given the fellow's willingness and interest in working on it, we should wait a bit for that, and keep in mind the sorts of errors that come up. It might be worthwhile getting someone on the Appium crew up to speed on it and become a contributor.

**Comment by tarunsujit** [comment]
@imurchie @0x1mason I will be glad to help you out.. Let me know if I can contribute in any way. Thanks!
I want to be involved more.

**Comment by 0x1mason** [comment]
@tarunsujit If you don't see any bugs or issues that intrigue you, feel free to email me: eric saucelabs dot com. Let me know what kinds of things you're interested in or are most useful to you and I'll see if I can find some things for you to work on.

**Comment by tarunsujit** [comment]
Thanks @0x1mason I had dropped you an email : eric at saucelabs dot com. shoot me back with your comments.
I am also having a very weird scenario, will drop you my problem in a separate email.
Thanks!

**Comment by kchuykov** [comment]
I get similar error, here is my log:

info: --> POST /wd/hub/session/e05494f0-0894-4433-a97a-59413c42ad51/element {"using":"id","value":"yucs-btn-nav"}
info: [debug] Waiting up to 30000ms for condition
info: [debug] [REMOTE] Executing 'find_element' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Remote debugger data sent [{"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){function h(a){return...]
info: <-- POST /wd/hub/session/e05494f0-0894-4433-a97a-59413c42ad51/element 500 7.342 ms - 87 
TypeError: Cannot call method 'send' of null
    at WebKitRemoteDebugger.send (/Users/admin/awetest/node_modules/appium/lib/devices/ios/webkit-remote-debugger.js:164:15)
    at RemoteDebugger.execute (/Users/admin/awetest/node_modules/appium/lib/devices/ios/remote-debugger.js:345:10)
    at RemoteDebugger.executeAtom (/Users/admin/awetest/node_modules/appium/lib/devices/ios/remote-debugger.js:276:8)
    at iOSController.executeAtom (/Users/admin/awetest/node_modules/appium/lib/devices/ios/ios-controller.js:647:15)
    at null.<anonymous> (/Users/admin/awetest/node_modules/appium/lib/devices/ios/ios-controller.js:311:10)
    at null.<anonymous> (/Users/admin/awetest/node_modules/appium/lib/devices/common.js:90:13)
    at null.<anonymous> (/Users/admin/awetest/node_modules/appium/lib/devices/common.js:66:5)
    at exports.waitForCondition (/Users/admin/awetest/node_modules/appium/lib/devices/common.js:81:3)
    at exports.implicitWaitForCondition (/Users/admin/awetest/node_modules/appium/lib/devices/common.js:92:8)
    at iOSController.findWebElementOrElements (/Users/admin/awetest/node_modules/appium/lib/devices/ios/ios-controller.js:315:8)
info: --> GET /wd/hub/session/e05494f0-0894-4433-a97a-59413c42ad51/screenshot {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
