### ISSUE TITLE
[Android] element.findElements() returns wrong result

### ISSUE THREAD

**Issue by prattpratt** [appium/appium#4500]
Hi,

I'm using **Appium@1.3.4** and **Android 4.4.4**.

Our app has a page that contains a list of TV channels. Each channel MAY have a little LIVE icon.
This is how it looks on the UI :
![screenshot_5569483670517986414](https://cloud.githubusercontent.com/assets/5451824/6063607/93632046-ad69-11e4-8997-910ad00ac6b9.png)

And this is the UI hierarchy for the channel w/o LIVE icon :

![2015-02-05_18h42_10](https://cloud.githubusercontent.com/assets/5451824/6063271/fd416f8e-ad66-11e4-9437-93f84eb69524.png)
and with LIVE icon :

![2015-02-05_18h42_34](https://cloud.githubusercontent.com/assets/5451824/6063272/ffb18ede-ad66-11e4-8682-7ecfc351b4ba.png)

At first I'm finding the channel element using :

``` java
WebElement firstChannel = driver.findElements(By.id("com.company.app:id/visibleChannel")).get(0);
```

Then I'm looking for child LIVE element under the channel. And the problem is that if the channel element does not contain LIVE icon, appium anyway returns some element. I found out that it is the nearest available LIVE icon from the nearest channel in the UI tree.
So for that case the following code returns `1` :

``` java
firstChannel.findElements(By.id("com.company.app:id/listing_live_btn")).size();
```

And here's corresponding appium log :

``` java
info: --> POST /wd/hub/session/e52db23d-bd9e-470f-98d7-1358a4f94afc/elements {"using":"id","value":"com.company.app:id/visibleChannel"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"id","selector":"com.company.app:id/visibleChannel","context":"","multiple":true}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.company.app:id/visibleChannel","context":"","multiple":true}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding com.company.app:id/visibleChannel using ID with the contextId:  multiple: true
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[RESOURCE_ID=com.company.app:id/visibleChannel]
info: [debug] [BOOTSTRAP] [debug] getElements selector:UiSelector[RESOURCE_ID=com.company.app:id/visibleChannel]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (0)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=com.company.app:id/visibleChannel]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (1)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[INSTANCE=1, RESOURCE_ID=com.company.app:id/visibleChannel]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (2)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[INSTANCE=2, RESOURCE_ID=com.company.app:id/visibleChannel]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (3)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[INSTANCE=3, RESOURCE_ID=com.company.app:id/visibleChannel]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (4)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[INSTANCE=4, RESOURCE_ID=com.company.app:id/visibleChannel]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (5)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[INSTANCE=5, RESOURCE_ID=com.company.app:id/visibleChannel]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (6)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[INSTANCE=6, RESOURCE_ID=com.company.app:id/visibleChannel]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (7)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[INSTANCE=7, RESOURCE_ID=com.company.app:id/visibleChannel]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (8)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[INSTANCE=8, RESOURCE_ID=com.company.app:id/visibleChannel]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":[{"ELEMENT":"195"},{"ELEMENT":"196"},{"ELEMENT":"197"},{"ELEMENT":"198"},{"ELEMENT":"199"},{"ELEMENT":"200"},{"ELEMENT":"201"},{"ELEMENT":"202"}],"status":0}
info: [debug] Responding to client with success: {"status":0,"value":[{"ELEMENT":"195"},{"ELEMENT":"196"},{"ELEMENT":"197"},{"ELEMENT":"198"},{"ELEMENT":"199"},{"ELEMENT":"200"},{"ELEMENT":"201"},{"ELEMENT":"202"}],"sessionId":"e52db23d-bd9e-470f-98d7-1358a4f94afc"}
info: <-- POST /wd/hub/session/e52db23d-bd9e-470f-98d7-1358a4f94afc/elements 200 139.860 ms - 217 {"status":0,"value":[{"ELEMENT":"195"},{"ELEMENT":"196"},{"ELEMENT":"197"},{"ELEMENT":"198"},{"ELEMENT":"199"},{"ELEMENT":"200"},{"ELEMENT":"201"},{"ELEMENT":"202"}],"sessionId":"e52db23d-bd9e-470f-98d7-1358a4f94afc"}
info: --> POST /wd/hub/session/e52db23d-bd9e-470f-98d7-1358a4f94afc/element/195/elements {"id":"195","using":"id","value":"com.company.app:id/listing_live_btn"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"id","selector":"com.company.app:id/listing_live_btn","context":"195","multiple":true}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.company.app:id/listing_live_btn","context":"195","multiple":true}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding com.company.app:id/listing_live_btn using ID with the contextId: 195 multiple: true
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[RESOURCE_ID=com.company.app:id/listing_live_btn]
info: [debug] [BOOTSTRAP] [debug] getElements selector:UiSelector[RESOURCE_ID=com.company.app:id/listing_live_btn]
info: [debug] [BOOTSTRAP] [debug] Element[195] is 195, counter: 0
info: [debug] [BOOTSTRAP] [debug] Element[195] is 195, counter: 1
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":[{"ELEMENT":"203"}],"status":0}
info: [debug] Responding to client with success: {"status":0,"value":[{"ELEMENT":"203"}],"sessionId":"e52db23d-bd9e-470f-98d7-1358a4f94afc"}
info: <-- POST /wd/hub/session/e52db23d-bd9e-470f-98d7-1358a4f94afc/element/195/elements 200 37.645 ms - 91 {"status":0,"value":[{"ELEMENT":"203"}],"sessionId":"e52db23d-bd9e-470f-98d7-1358a4f94afc"}
```

Interesting thing is that if I will use Xpath then corresponding code will return `0` as expected :

``` java
driver.findElementsByXPath("//*[@resource-id='com.company.app:id/visibleChannel'][1]//*[@resource-id='com.company.app:id/listing_live_btn']").size()
```

Also log for that case :

``` java
info: --> POST /wd/hub/session/e52db23d-bd9e-470f-98d7-1358a4f94afc/elements {"using":"xpath","value":"//*[@resource-id='com.company.app:id/visibleChannel'][1]//*[@resource-id='com.company.app:id/listing_live_btn']"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"xpath","selector":"//*[@resource-id='com.company.app:id/visibleChannel'][1]//*[@resource-id='com.company.app:id/listing_live_btn']","context":"","multiple":true}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[@resource-id='com.company.app:id/visibleChannel'][1]//*[@resource-id='com.company.app:id/listing_live_btn']","context":"","multiple":true}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding //*[@resource-id='com.company.app:id/visibleChannel'][1]//*[@resource-id='com.company.app:id/listing_live_btn'] using XPATH with the contextId:  multiple: true
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":[],"status":0}
info: [debug] Condition unmet after 85ms. Timing out.
info: [debug] Responding to client with success: {"status":0,"value":[],"sessionId":"e52db23d-bd9e-470f-98d7-1358a4f94afc"}
info: <-- POST /wd/hub/session/e52db23d-bd9e-470f-98d7-1358a4f94afc/elements 200 90.834 ms - 74 {"status":0,"value":[],"sessionId":"e52db23d-bd9e-470f-98d7-1358a4f94afc"}
```

**Comment by prattpratt** [comment]
It is still reproducible on Appium 1.3.5. Could somebody have a look at this ?

**Comment by 0x1mason** [comment]
Yes, we will take a look, thanks.  Is there any way you can share you app with me? Just the build would be fine. eric # saucelabs.com I promise it will be not be shared and can sign NDA, etc.

**Comment by prattpratt** [comment]
So here's how it could be done:
* on the Google Play Market find and install **Horizon Go** app:
https://play.google.com/store/apps/details?id=com.lgi.orionandroid
* select any country (e.g. *Ireland*), skip *Sign in* page and go to *TV Guide* page
* tap Search icon on the top-right corner and type any short search keyword (like *th*)
* you will see a list of TV programs (search items) and some of them will have LIVE icon
* try to find an item without LIVE icon, and then try to search for LIVE icon inside it:
```java
WebElement e = driver.findElements(By.id("com.lgi.orionandroid:id/stickyItem")).get(0);
e.findElements(By.id("com.lgi.orionandroid:id/listing_live_btn")).size();
/* (int) 1 */
```
* if you will execute `findElements()` and use XPath you will see other result - as expected:
```java
driver.findElements(By.xpath("//*[@resource-id='com.lgi.orionandroid:id/stickyItem'][1]//*[@resource-id='com.company.app:id/listing_live_btn']")).size();
/* (int) 0 */
```
* screen layout may look smth like this :
![image](https://cloud.githubusercontent.com/assets/5451824/6348318/83ce4000-bc2f-11e4-996c-ab7f2eeaabb9.png)

**Comment by 0x1mason** [comment]
Excellent, thanks!

**Comment by nabeel-ibrahim** [comment]
I'm experiencing a similar issue but with findelement method. I have about 5 LinearLayouts with TextView children that have the same ID, however, im trying to get the last TextView. Im using the following command :
driver.findelement(By.xpath("//android.widget.TextView[@resource-id='com.companyx.myApp:id/txt_name'][last()]"); 

This will always select the first TextView with the following resource-id and not the last one.

**Comment by jlipps** [comment]
Please try with the latest version of Appium and I'll be happy to reopen if the issue persists.

**Comment by vVv-AA** [comment]
I believe the problem is still present.

Here's a function I wrote.

`private static MobileElement findChildOfElement(AppiumDriver driver, MobileElement parent, By locator, int instance) throws NoSuchElementException {
        Dimension size = driver.manage().window().getSize();
        int x = size.getWidth() / 2;
        int y = size.getHeight() / 2;
        Point previousCenter = parent.getCenter();
        while (parent.isDisplayed()) {
            try {
                MobileElement mobileElement = parent.findElements(locator).get(instance);
                mobileElement.isEnabled();
                return mobileElement;
            } catch (IndexOutOfBoundsException | NoSuchElementException ignored) {
                driver.swipe(x, y, x, y - 50, 500);
            }
            if (previousCenter.equals(parent.getCenter())) break;
            previousCenter = parent.getCenter();
        }
        throw new NoSuchElementException("No such child found");
    }
`

When I use this I get children from siblings of parent.

**Comment by Irena90** [comment]
Hi, I am having same issue. I am using findElementsById method. Could you please send me wht you need to reopen this issue (appium logs etc.)?

Thanks in advance!

Irena

**Comment by mzaatar** [comment]
I have the same issue on Appium v1.6.4 on Android.
It works on a the first screen and when I try to locate by Element it fails
`var listItems = _driver.FindElementsById("arrowNext");`

Log:
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'arrowNext' using 'ID' with the contextId: '' multiple: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[RESOURCE_ID=au.com.XYZ.mobile.debug:id/arrowNext]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements selector:UiSelector[RESOURCE_ID=au.com.XYZ.mobile.debug:id/arrowNext]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Element[] is null: (0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=au.com.XYZ.mobile.debug:id/arrowNext]
