### ISSUE TITLE
fruitstrap has been out of maintenance

### ISSUE THREAD

**Issue by zhong88** [appium/appium#4501]
Since Fruitstrap has been out of support now, so why appium still uses this tool to download the app file to the device? it doesn't make for us since we're using Mac Yosemite and every time when we attempted to use Appium to install .app  file to the iOS, Fruitstrap always pops up a crash message.

**Comment by hughvidos** [comment]
What about using iOS-deploy?  https://github.com/phonegap/ios-deploy  It is forked from fruitstrap and is being supported.

**Comment by JessicaSachs** [comment]
You can't install .app files to iOS. You have to install compiled, development signed .ipa files to iOS.

**Comment by zhong88** [comment]
Actually I can installed .app files with Fruitstrap. My point is that  the annoying pop-up warning message from fruitstrap would pop up when installing the .app file.

Thanks,
Zhong

**Comment by zhong88** [comment]
good point! we’re using ios-deply somewhere in our own project. But for Appium, could they replace fruitstrap with iso-deploy in their build? if so, it would be super nice. 

Thanks,
Zhong

**Comment by bootstraponline** [comment]
I have an issue from last year about using ios-deploy. I agree it's better than fruitstrap.

https://github.com/appium/appium/issues/3323

**Comment by paymand** [comment]
We don't use ``fruitstrap`` anymore and are using ``ideviceinstaller`` everywhere. See https://github.com/appium/appium/pull/4790.
Please make sure that you have the latest version of ``ideviceinstaller`` installed.

**Comment by zhong88** [comment]
Great work! Thanks

On Tue, Apr 7, 2015 at 3:27 AM, Payman Delshad <notifications@github.com>
wrote:

> We don't use fruitstrap anymore and are using ideviceinstaller
> everywhere. See #4790 <https://github.com/appium/appium/pull/4790>.
> Please make sure that you have the latest version of ideviceinstaller
> installed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/4501#issuecomment-90499675>.
>



-- 
This email and all attachments are confidential and are intended solely for
the individual or entity to whom the email is addressed. If you believe
that you are not an intended recipient, please stop reading immediately.
Do not disclose, copy, forward, or rely on the contents in any way.  Please
notify Tile by emailing the original Tile sender and then delete or destroy
any copy of this email and its attachments.  The sender reserves and
asserts all rights to confidentiality, including all privileges that may
apply.
