### ISSUE TITLE
Failed to start appium in command line with error or warn log level

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#4503]
Yosemite 10.10
Appium 1.3.4

appium --command-timeout 90 --log-level error --port 4725 --session-override - nothing happens no error.

appium --command-timeout 90 --log-level info --port 4725 --session-override - starting successfully

**Comment by p00j4** [comment]
--log-level error will print log only if errors are present [so appium server starts successfully but you don't see anything in log until you execute a script which causes ERROR ] ,
 - though why appium server doesn't listen can be an issue to worry if your script says -"session not created or found"

**Comment by amedvedjev** [comment]
ok. i understood. the problem in way i am starting server in Java. closing...
