### ISSUE TITLE
Menu option inside native browser in android 4.4.2, unable to sendKeyevent(82)

### ISSUE THREAD

**Issue by bibekSahoo** [appium/appium#4504]
driver.sendKeyEvent(82)

Which generally helps to generate key event for menu while on native as well hybrid apps,
But in browser ot working

error:

info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/1d7904122d304ada1e8e4b2751c11128/appium/device/keyevent","method":"POST","json":{"keycode":82}}
info: [debug] Proxied response received with status 404: "unknown command: session/1d7904122d304ada1e8e4b2751c11128/appium/device/keyevent"
info: <-- POST /wd/hub/session/1d7904122d304ada1e8e4b2751c11128/appium/device/keyevent 404 21.645 ms - 80

**Comment by SeanShi** [comment]
Appium may not work well with Android 4.4.2. You may have to try it on Android 4.3.
