### ISSUE TITLE
Failed: Install from source by using reset.sh

### ISSUE THREAD

**Issue by vietnq254** [appium/appium#4508]
Hello,

I want to use the newest source of Appium so I used Git to download its source and then I run reset.sh.
But there was a problem when i run it:
```
npm WARN 'git config --get remote.origin.url' returned wrong result <git://github.com/vojtajina/traceur-compiler>
npm ERR! git clone git://github.com/vojtajina/traceur-compiler Cloning into bare repository 'C:\Users\user\AppData\Roaming\npm,-cache\_git-remotes\git-github-com-vojtajina-traceur-compiler-f4c43c65'...
npm ERR! git clone git://github.com/vojtajina/traceur-compiler fatal: unable to connect to github.com
npm ERR! git clone git://github.com/vojtajina/traceur-compiler github.com[0: 192.30.252.128] errno=No error
```
```
node -v
v0.12.0
npm -v
2.5.1
```
```
Windows 7 64 bit
```
Can somebody help me?

**Comment by p00j4** [comment]
Are you behind any firewall !
fatal: unable to connect to github.com
suggests that github.com can't be reached

**Comment by vietnq254** [comment]
It can get other libraries from github by using npm except traceur-compiler

**Comment by jlipps** [comment]
I just ran it and it worked for me; can you try again?

**Comment by smolenskij** [comment]
I'm having almost the exact same issue.  

It seems to be trouble with using the url git://github.com/fojtajina/traceur-compiler, which times out when I try to manually clone.

I can manually clone if I switch git:// to https:// but I can't tell node to do this, which seems to be causing the trouble.

**Comment by 0x1mason** [comment]
Can you try running `npm clear cache` then reinstalling?

**Comment by vietnq254** [comment]
Unfortunately ```npm clear cache``` is not useful.

**Comment by 0x1mason** [comment]
We haven't tested with Node 0.12 yet. That's probably not the issue, but you might try downgrading and upgrading npm.

**Comment by jlipps** [comment]
I think the issue is that some people don't have ssh set up with git, so a git url that starts with git:// is never going to work. And one of our submodules uses it as a dependency. We just need to track down what that is and if its within our domain (I bet it is), switch to https:// rather than git://

**Comment by smolenskij** [comment]
That seems to describe the symptoms I see perfectly, and you've given me some new things to try!

**Comment by vietnq254** [comment]
I cannot really let ```reset.sh``` works without error although I already changed the git config from ```git://``` to ```https://```
So i only have one choice: using npm!

**Comment by jlipps** [comment]
for future reference, the workaround is here: http://stackoverflow.com/questions/4891527/git-protocol-blocked-by-company-how-can-i-get-around-that

**Comment by lamp12** [comment]
I tried npm install nice-date and it worked successfully. (Reference issue 4751)
I also  followed the steps mentioned in the stack over flow link.
Tried changing the below commands:

git config --global url."https://".insteadOf git://

git remote set-url origin https://github.com/<my_user_name>/<my_repo_name>.git

Still no success.

**Comment by 0x1mason** [comment]
Try this:
```
git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://
```

**Comment by 0x1mason** [comment]
Afaik, the changes the remote aren't necessary

**Comment by smolenskij** [comment]
Thanks Mason, that solved my own issues perfectly.

**Comment by lamp12** [comment]
i have tried above commands as well.
Still no success. There is no proxy set in my Mac.
Please help in installing the appium.
