### ISSUE TITLE
Unable to get the snapshot from Android simulator on Sauce labs 

### ISSUE THREAD

**Issue by Ankit9568** [appium/appium#4510]
I am trying to Fetch the snapshot from AndroidSimulators using Appium on sauce labs 

Faces below Exception: 
unknown error: unhandled inspector error: {"code":-32603,"message":"Unable to capture screenshot"} 

Code for take a snapshot

AppiumDriver driver = new AppiumDriver(); 
File scrFile = driver.getScreenshotAs(OutputType.FILE); 
FileUtils.copyFile(scrFile, new File("D:/a.txt"));

But when i am trying to get the snapshot from RealDevice in my local environment using appium code is worked

Any help will be greatly appreciated

**Comment by moizjv** [comment]
@Ankit9568 thanks for reporting issue. We can look into it. Do you have appium logs?

**Comment by Ankit9568** [comment]
Hello Moiz Virani for reply, 
Kindly find appium logs

942015-04-28 07:32:49:584 - info: [debug] Proxied response received with status 200: {"sessionId":"4fe93843c4c5d8837d6ace7821075185","status":0,"value":null}

952015-04-28 07:32:49:585 - info: <-- POST /wd/hub/session/4fe93843c4c5d8837d6ace7821075185/element/0.9941945194732398-1/value 200 3487.291 ms - 72

962015-04-28 07:32:50:292 - info: --> GET /wd/hub/session/4fe93843c4c5d8837d6ace7821075185/screenshot {}

972015-04-28 07:32:50:292 - info: [debug] Proxying command to 127.0.0.1:9515

982015-04-28 07:32:50:292 - info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/4fe93843c4c5d8837d6ace7821075185/screenshot","method":"GET"}

992015-04-28 07:32:50:339 - info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"unknown error: cannot activate web view\n (Session info: chrome=37.0.0.0)\n (Driver info: chromedriver=2.12-lollipop-emu-support.303674 (4f47d05563ab928b29e84a4f3be2cb4de49a0965),platform=Linux 3.13.0-46-generic x86)"},"sessionId":"4fe93843c4c5d8837d6ace7821075185"}

1002015-04-28 07:32:50:340 - info: <-- GET /wd/hub/session/4fe93843c4c5d8837d6ace7821075185/screenshot 500 48.665 ms - 383

101

**Comment by moizjv** [comment]
@Ankit9568 thanks for reporting the issue. Can you email to our support team help@saucelabs.com with details, so we can track it on sauce. I am closing this issue as it is not appium issue. Thanks

**Comment by Ankit9568** [comment]
Hello moizjv,
thanks for suggestion, I have already reported issue on sauce lab support 
Issue ID- #18453 
  
Thanks
