### ISSUE TITLE
Android: How to click button "Activate" of Device Administrator window?

### ISSUE THREAD

**Issue by vietnq254** [appium/appium#4511]
Hello,

I am using: Appium 1.3.5-beta, Selendroid mode (Hybrid-app, API 17).
A Device Administrator window will be shown and need to be clicked on the button "Activate".
How can I do it?

I tried with:
Alert alert = driver.switchTo().alert();
alert.accept();

but it was not successful.

**Comment by p00j4** [comment]
in Android, for no reason I know, Alert API doesn't work with appium.
work around:  just locate element by.name = "Activate" followed by click()

**Comment by vietnq254** [comment]
Unfortunately it cannot work that way.

Because of using Selendroid mode so I think here is the  problem of Selendroid. Of course that we also care the way Appium wrap Selendroid for the old APIs.

Do you know Appium can support well in this case for API>=19 (hybrid app) or not?

**Comment by vietnq254** [comment]
We will wait for the better version in the future.
