### ISSUE TITLE
Appium unbale to parse package name and lanchable activity.

### ISSUE THREAD

**Issue by clmathuriya** [appium/appium#4516]
Hello,

Getting launchable actvity null for gmail app.

2015-02-10 09:09:17:281 - debug: Parsing package and activity from app manifest
2015-02-10 09:09:17:282 - debug: Checking whether aapt is present
2015-02-10 09:09:17:283 - debug: Using aapt from /home/chhagan/android/adt/sdk/build-tools/android-4.4W/aapt
2015-02-10 09:09:17:283 - debug: Extracting package and launch activity from manifest.
2015-02-10 09:09:17:284 - debug: executing cmd: /home/chhagan/android/adt/sdk/build-tools/android-4.4W/aapt dump badging /home/chhagan/Downloads/com.google.android.gm.apk
2015-02-10 09:09:17:349 - debug: badging package: com.google.android.gm
2015-02-10 09:09:17:349 - debug: badging act: null
2015-02-10 09:09:21:712 - debug: Parsed package and activity are: com.google.android.gm/ConversationListActivityGoogleMail

Getting below error while creating driver instance.

 executing cmd: /home/chhagan/android/adt/sdk/platform-tools/adb -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.google.android.gm/.ConversationListActivityGoogleMail
"
2015-02-10 09:10:01:866 - error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity

**Comment by p00j4** [comment]
@clmathuriya : there can be multiple activities in a app and appium tries to wait for the main activity which is supposed to launch for an app, 
![image](https://cloud.githubusercontent.com/assets/6470509/6127840/78574c4c-b155-11e4-8c9f-233c9d12ecd9.png)


and as suggests, ConversationListActivityGoogleMail is not the main activity or is not launchable, so you have to manually set the right activity to be launched and for doing this you need to know whats gmail's main activity name

**Comment by clmathuriya** [comment]
@p00j4 :
Thanks for your response.
Is there any other ways apart from entering wait actvity maually ?
I am providing app location, in case of other apps appium is able to find main activity and launch by specifying app location only.
i am providing below capabilities:
DesiredCapabilities capabilities = new DesiredCapabilities();
		File app = new File("/home/chhagan/AppsTest/com.google.android.gm.apk");

		capabilities.setCapability(MobileCapabilityType.APP,
				app.getAbsolutePath());
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,
				"emulator-5554");
		capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT,
				1800);

		try {
			AndroidDriver driver = new AndroidDriver(new URL(
					"http://127.0.0.1:4723/wd/hub"), capabilities);
			System.out.println(driver.currentActivity());
		} catch (MalformedURLException e) {

			e.printStackTrace();
		}

**Comment by p00j4** [comment]
yes,  just add another capability
 capabilities.setCapability(appActivity, "activityName");

**Comment by clmathuriya** [comment]
Actually I wanted to launch apps with taking input as APK file only.
In case of other apps like facebook or whatsapp appium is able to launch with app location only.
I am not able to understand why appium not able to launch gmail app with app location.

**Comment by moizjv** [comment]
@p00j4 thanks ! @clmathuriya please ask questions on [forum] (https://discuss.appium.io). Please try to set appActivity if appium is unable to launch activity. appium tries to get main launchable activity info if it is not provided and tries to launch it.

**Comment by clmathuriya** [comment]
Thanks @moizjv !!
