### ISSUE TITLE
Selenium::WebDriver::Error::WebDriverError: chrome not reachable

### ISSUE THREAD

**Issue by randoum** [appium/appium#4527]
I am trying to test for my application behavior when not connected to internet.

After calling `toggle_airplane_mode`, I receive `Selenium::WebDriver::Error::WebDriverError: chrome not reachable`

Any insights on this?

**Comment by sebv** [comment]
Could you provide more idetails and server log. thx.

**Comment by randoum** [comment]
@sebv thanks for your answer after 4 months.
I think you got the complete information to try and reproduce. Did you reproduce?

**Comment by sebv** [comment]
Sorry information is incomplete, we need the server log to know what is your setup, api version, git commit etc, error message from server log also help.

**Comment by moizjv** [comment]
@randoum any update?

**Comment by randoum** [comment]
Later

**Comment by moizjv** [comment]
@randoum closing the issue for now. Reopen when you have more information.
