### ISSUE TITLE
Not able to Automate the Date picker wheel in Android using Protractor-Appium test

### ISSUE THREAD

**Issue by bhawani2008** [appium/appium#4528]
Hello,
I am using Protractor along with appium server to automate an hybrid app in Android. I am not able to automate the date picker wheel.
I tried using appium className or xpath , but protractor is unable to recognize the xpath or className and test is failing..
DO we need to first to switch to Native App mode, as i am using autowebview = true. Kindly Advise and how to switch to Native mode.

I tried using the code, but fails to recognize the date picker: 
1>>>   var date = browser.findElement(By.xpath("//android.widget.DatePicker//android.widget.LinearLayout[0]/EditText")); date.click(); date.clear();
  date.sendKeys("Apr");   Gets error and unable to find xpath.

2>> List<WebElement> date  = browser.element(by.className("android.widget.DatePicker")); Gets error Invalid left hand side assignments

3>>  browser.switchTo().frame('android.widget.DatePicker');
var day1=browser.findElement(By.className("android.widget.DatePicker"));
findElement(By.id("android:id/day")); day1.clear(); day1.sendKeys('05');

Kindly Suggests.
![datepicker-android](https://cloud.githubusercontent.com/assets/6057224/6146289/2e989f40-b211-11e4-8bb9-d7cb79bd6a93.png)

**Comment by gualber98** [comment]
I recommend using: findElement(MobileBy.AndroidUIAutomator("new UiSelector().className("android.widget.DatePicker").childSelector(new UiSelector().className("android.widget.LinearLayout")"));

you can view more about UiAutomator here: http://developer.android.com/tools/testing/testing_ui.html

**Comment by jlipps** [comment]
Yes, protractor starts you in webview mode. You need to switch contexts to the native context. There are docs for that in the appium.io docs page.

(Not sure how that works from protractor exactly)
