### ISSUE TITLE
Finding an Android status bar notification element

### ISSUE THREAD

**Issue by YoniH** [appium/appium#4530]
Hi,

I am writing an automated test for my Android app, using Appium 1.3.4.

My app sends a status bar notification. In my automated test, I'm trying to find the notification and click it. How can I find the notification in the notification area?

I tried to explore the elements of the notifications page using UI-Automator. It looks like all the IDs are set by the Android OS and there's nothing unique I can identify my notification with.

I do not want to identify by text, because the text changes.

Perhaps there is a way to assign an Id for the notification from my app's code, an id which will be visible to Appium?

Thanks

**Comment by sebv** [comment]
If you cannot do it with UI Automator, you cannot do it with Appium. @0x1mason any idea?

**Comment by amedvedjev** [comment]
not clear: did you try (with Java) driver.openNotifications() ?

**Comment by YoniH** [comment]
amedvedjev, driver.openNotifications() just opens the shade. My problem is to identify a specific notification.

**Comment by amedvedjev** [comment]
well but now you have on screen all notification area. and you can reach any it element e.g. either by xpath to some element OR by searching element with specific text in notification area that is coming with your notification push.

**Comment by YoniH** [comment]
As I said, I do not want to identify by text. I also don't have enough info for xpath identification. also clearing notifications just clears unpinned notifications which means i can't be sure what will be the position of my notification

**Comment by amedvedjev** [comment]
Then it is not clear how you going to search for your notification that can
mix inside pinned notifications in any random way inside notification list
:-)

**Comment by YoniH** [comment]
but i do have control over my app which sends the notification. please read my question.

**Comment by 0x1mason** [comment]
Try setting the `content-description` for the component in your app and then using the `accessbility id` strategy to find it.  There are some other ways for you to set the id we can explore if that doesn't work, but that is the recommended way.

**Comment by 0x1mason** [comment]
This is really a more suitable question for http://discuss.appium.io.  Content-description should get you started.  You can also use the resource id.  If you need more help, as the user community on the forum.  Thanks for using Appium :)

**Comment by zcmgyu** [comment]
You can use UIAutomation to inspect a status bar resource-id.
Hope it will help you.
![screen_shot_2017-02-09_at_2_00_18_pm](https://cloud.githubusercontent.com/assets/13638569/22772659/99b866ae-eed0-11e6-8d1a-a10e7e3ac992.png)

**Comment by Warren25** [comment]
You can get a list of your notifications with this:

@AndroidFindBy(uiAutomator = "new UiSelector().resourceId(\"android:id/title\")")
    private List<MobileElement> notificationTitles;

And use Java to retrieve which notification you want:

notificationTitles.get(i)

if(notificationTitles.get(i).getText().equals("some expected string"))
notificationTitles.get(i).........
