### ISSUE TITLE
setLocation() error on Ubuntu when try run telnet [REAL DEVICE]

### ISSUE THREAD

**Issue by andrealorenzo88** [appium/appium#4536]
Appium Log:

...
info: --> POST /wd/hub/session/dd4f2d84-0767-4555-9172-2aa72064962f/location {"location":{"altitude":1000,"class":"org.openqa.selenium.html5.Location","longitude":2.1361,"latitude":41.3648,"hCode":2038505063}}
info: [debug] Sending telnet command to device: geo fix 2.1361 41.3648
info: [debug] Getting running emulator port
error: Unhandled error: Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19) context: [POST /wd/hub/session/dd4f2d84-0767-4555-9172-2aa72064962f/location {"location":{"altitude":1000,"class":"org.openqa.selenium.html5.Location","longitude":2.1361,"latitude":41.3648,"hCode":2038505063}}]
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Could not set geolocation via telnet to device"},"sessionId":"dd4f2d84-0767-4555-9172-2aa72064962f"}
info: <-- POST /wd/hub/session/dd4f2d84-0767-4555-9172-2aa72064962f/location 500 1.381 ms - 215 
info: --> DELETE /wd/hub/session/dd4f2d84-0767-4555-9172-2aa72064962f {}
....

adb devices:
List of devices attached 
0bd083bc048e3973	     device

**Comment by imurchie** [comment]
Yes. This won't work on a real device, unless you feel like rooting it and
getting `telnetd` running.
