### ISSUE TITLE
branch clean up. 17 branches?

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#4537]
do we really need 17 branches? I think it'd be nice to clean up the old branches if they're no longer useful.

**Comment by sebv** [comment]
how about those: 2,601 remote branches.

```
Seen branch in repository origin/v1.3.5-branch
Seen branch in repository origin/v_1_3_5_beta
Seen branch in repository origin/zarkonnen-testsuitefix
Seen 2,601 remote branches
```
Cloudbees is having a hard time taking it in.

**Comment by sebv** [comment]
Tempting:
```
git branch -r --merged | 
grep origin | 
grep -v '>' | 
grep -v master | 
xargs -L1 | 
cut -d"/" -f2- | 
xargs git push origin --delete
```

**Comment by bootstraponline** [comment]
:+1:

**Comment by jlipps** [comment]
let's at least clean up the appium branches

**Comment by sebv** [comment]
Should be quick let's plan it next sprint.

**Comment by rkavalap** [comment]
The current no of remote branches don't seem to be that many for the main appium repo. Closing legacy bug
