### ISSUE TITLE
Unable to push big file to android

### ISSUE THREAD

**Issue by nwlunatic** [appium/appium#4542]
Trying to push 8mb file:

``` python
with open('temp', 'w') as f:
    # write 8Mb of data for example
    f.write('a' * 1024 * 1024 * 8)
with open('temp', 'r') as f:
    driver.push_file('/sdcard/', f.read().encode("base64"))
```

ends up with:

``` bash
info: [debug] executing cmd: android-sdk-macosx/platform-tools/adb -s emulator-5554 push "/var/folders/xn/2svfnj416wv_dfb6mx6x4d140000gn/T/appium115116-42101-1066u0o.tmp" /sdcard/
Assertion failed: (end <= source_len), function SliceOnto, file ../src/smalloc.cc, line 280.
Abort trap: 6
```

No problems with push using adb by itself:

``` bash
$ android-sdk-macosx/platform-tools/adb -s emulator-5554 push "/var/folders/xn/2svfnj416wv_dfb6mx6x4d140000gn/T/appium115116-42101-1066u0o.tmp" /sdcard/
1690 KB/s (8388608 bytes in 4.846s)
```

Environment:
- Appium version: 1.3.\* including current master
- Android emulator: android 5.0.1 (api 21) x86 HAXM (hardware acceleration)

**Comment by 0x1mason** [comment]
IIUC, this is a bug in Node.  You could try upgrading to 0.12 to see if it's resolved, but we have not tested Appium with 0.12 yet.

**Comment by nwlunatic** [comment]
Already on node 0.12. By the way, all is working as expected, except for now
```bash
$ node --version
v0.12.0
```

Shouldn't user have an ability to run adb command in session to get around this kind of bugs?
Or, maybe, receive an actual device name in actual capabilities https://code.google.com/p/selenium/wiki/JsonWireProtocol#Actual_Capabilities?
```python
'deviceName': 'Android Emulator'
```
and receive
```python
'deviceName': 'emulator-<number>'
```
Both seems to me very useful

**Comment by lnnp1910** [comment]
I have this issue when using appium 1.3.6 on mac. 
failed to push everything that is larger than 1MB.
but then downgrading to 1.3.4, everything works fine. 

Version node was 0.10.26.

**Comment by rkavalap** [comment]
@nwlunatic  is this still an issue ?
