### ISSUE TITLE
Cannot install 1.3.5 using npm

### ISSUE THREAD

**Issue by ytonthat** [appium/appium#4543]
I see the following traces when executing the command npm install -g appium:

	vstest.console.exe %AUTOMATEDTESTS_HOME%\UserInterfaceTests\ScMobile.UserInterfaceTests.Phone.Android\bin\Debug\Genetec.ScMobile.AutomatedTests.UserInterfaceTests.Phone.Android.dll /InIsolation /Settings:%AUTOMATEDTESTS_HOME%\Default.testsettings /Logger:trx /Tests:Genetec.ScMobile.AutomatedTests.UserInterfaceTests.Phone.Android.Drawer
	> ws@0.4.32 install C:\Users\ytonthat\AppData\Roaming\npm\node_modules\appium\no
	de_modules\ws
	> (node-gyp rebuild 2> builderror.log) || (exit 0)

	C:\Users\ytonthat\AppData\Roaming\npm\node_modules\appium\node_modules\ws>node "
	C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modu
	les\node-gyp\bin\node-gyp.js" rebuild
	npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0"
	,"npm":"2.5.1"})
	|

	> ws@0.4.31 install C:\Users\ytonthat\AppData\Roaming\npm\node_modules\appium\no
	de_modules\socket.io\node_modules\engine.io\node_modules\ws
	> (node-gyp rebuild 2> builderror.log) || (exit 0)

	C:\Users\ytonthat\AppData\Roaming\npm\node_modules\appium\node_modules\socket.io
	\node_modules\engine.io\node_modules\ws>node "C:\Program Files (x86)\nodejs\node
	_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebu
	ild
	npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
	b.com/vojtajina/traceur-compiler)
	npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0",
	"npm":"2.5.1"})
	npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0",
	"npm":"2.5.1"})
	npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0",
	"npm":"2.5.1"})
	npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.1
	2.0","npm":"2.5.1"})
	npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
	"node":"0.12.0","npm":"2.5.1"})
	/

	> ws@0.4.31 install C:\Users\ytonthat\AppData\Roaming\npm\node_modules\appium\no
	de_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client
	\node_modules\ws
	> (node-gyp rebuild 2> builderror.log) || (exit 0)

	C:\Users\ytonthat\AppData\Roaming\npm\node_modules\appium\node_modules\socket.io
	\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws>nod
	e "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_m
	odules\node-gyp\bin\node-gyp.js" rebuild
	npm ERR! git clone git://github.com/vojtajina/traceur-compiler Cloning into bare
	 repository 'C:\Users\ytonthat\AppData\Roaming\npm-cache\_git-remotes\git-github
	-com-vojtajina-traceur-compiler-f4c43c65'...
	npm ERR! git clone git://github.com/vojtajina/traceur-compiler fatal: unable to
	connect to github.com:
	npm ERR! git clone git://github.com/vojtajina/traceur-compiler github.com[0: 192
	.30.252.130]: errno=No such file or directory
	npm ERR! Windows_NT 6.3.9600
	npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
	x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
	npm ERR! node v0.12.0
	npm ERR! npm  v2.5.1
	npm ERR! code 128

	npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\yt
	onthat\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.c
	om/vojtajina/traceur-compiler C:\Users\ytonthat\AppData\Roaming\npm-cache\_git-r
	emotes\git-github-com-vojtajina-traceur-compiler-f4c43c65
	npm ERR! Cloning into bare repository 'C:\Users\ytonthat\AppData\Roaming\npm-cac
	he\_git-remotes\git-github-com-vojtajina-traceur-compiler-f4c43c65'...
	npm ERR! fatal: unable to connect to github.com:
	npm ERR! github.com[0: 192.30.252.130]: errno=No such file or directory
	npm ERR!
	npm ERR!
	npm ERR!
	npm ERR! If you need help, you may report this error at:
	npm ERR!     <http://github.com/npm/npm/issues>
	npm ERR! Windows_NT 6.3.9600
	npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
	x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
	npm ERR! node v0.12.0
	npm ERR! npm  v2.5.1

	npm ERR! Uncaught, unspecified "error" event.
	npm ERR!
	npm ERR! If you need help, you may report this error at:
	npm ERR!     <http://github.com/npm/npm/issues>

	npm ERR! Please include the following file with any support request:
	npm ERR!     C:\Program Files (x86)\Microsoft Visual Studio 11.0\npm-debug.log

	pause

The workaround is installing the previous version with the command npm install -g appium@1.3.4

**Comment by GindiKhangura** [comment]
I'm encountering this issue as well.
I also tried using appium-version-manager and encountered the same issue. I thought that perhaps avm was messing with Appium, so I deleted avm and tried npm install for Appium, but it didn't help.

Console output:
<code>
npm install -g appium
 
> ws@0.4.32 install /usr/local/lib/node_modules/appium/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.5.1"})
 
> ws@0.4.31 install /usr/local/lib/node_modules/appium/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.5.1"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.5.1"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.5.1"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.33","npm":"2.5.1"})
 
> ws@0.4.31 install /usr/local/lib/node_modules/appium/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm ERR! git clone git://github.com/vojtajina/traceur-compiler Cloning into bare repository '/Users/gk025917/.npm/_git-remotes/git-github-com-vojtajina-traceur-compiler-f4c43c65'...
npm ERR! git clone git://github.com/vojtajina/traceur-compiler fatal: read error: Operation timed out
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v0.10.33
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/Users/gk025917/.npm/_git-remotes/git-github-com-vojtajina-traceur-compiler-f4c43c65'...
npm ERR! fatal: read error: Operation timed out
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gk025917/npm-debug.log
</code>

**Comment by Jonahss** [comment]
Hmm. Looks related specifically to the traceur compiler. What OS are you running?
@0x1mason would be interested in this one.

**Comment by ytonthat** [comment]
i have the same issue on win8.1 and osx 10.9.5

**Comment by 0x1mason** [comment]
Try running `npm cache clean` and then installing the latest stable version of npm.

See https://github.com/npm/npm/issues/5491

**Comment by vietnq254** [comment]
Same issue with [4508](https://github.com/appium/appium/issues/4508)
```
npm WARN 'git config --get remote.origin.url' returned wrong result <git://github.com/vojtajina/traceur-compiler>
npm ERR! git clone git://github.com/vojtajina/traceur-compiler Cloning into bare repository 'C:\Users\user\AppData\Roaming\npm,-cache\_git-remotes\git-github-com-vojtajina-traceur-compiler-f4c43c65'...
npm ERR! git clone git://github.com/vojtajina/traceur-compiler fatal: unable to connect to github.com
npm ERR! git clone git://github.com/vojtajina/traceur-compiler github.com[0: 192.30.252.128] errno=No error
```

**Comment by GindiKhangura** [comment]
@Jonahss @0x1mason I'm on OSX 10.9.5.

**Comment by GindiKhangura** [comment]
@0x1mason I tried <b>npm clean cache</b>, then did <b>npm install npm</b>, then uninstalled appium 1.3.4, then did <b>npm install -g appium</b>, and I get the same error originally stated:

<blockquote>
npm ERR! Command failed: Cloning into bare repository '/Users/gk025917/.npm/_git-remotes/git-github-com-vojtajina-traceur-compiler-f4c43c65'...
npm ERR! fatal: read error: Operation timed out
</blockquote>

**Comment by 0x1mason** [comment]
Ok, we'll look into this.

**Comment by 0x1mason** [comment]
@ytonthat @GindiKhangura Are you behind a proxy? Regardless, can you try running this command?
```
git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://
```
That will change your git config, so you may want to back it up first so you can undo the change.

**Comment by vietnq254** [comment]
Thanks @0x1mason 
It worked well!
```
git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://
```
```
npm install -g appium@1.3.5
```

**Comment by GindiKhangura** [comment]
@0x1mason The commands you mentioned helped to resolve the issue. Thank you!
Out of curiosity, why was this needed for 1.3.5 and not the previous versions? Was the release from a different source? Was the NPM installer told to download Appium 1.3.5 using a certain command with a different format than the previous versions'?

**Comment by jlipps** [comment]
@GindiKhangura it's because we added some NPM packages that in their dependency chains use this URL. We don't use it directly.

**Comment by 0x1mason** [comment]
https://github.com/appium/appium/issues/4627 Same issue.

**Comment by khallbec** [comment]
this is still happening but with a little different error in 1.3.7
> ws@0.4.31 install /usr/local/lib/node_modules/appium/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.31","npm":"2.1.2"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.31","npm":"2.1.2"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.31","npm":"2.1.2"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.31","npm":"2.1.2"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.31","npm":"2.1.2"})
npm ERR! git fetch -a origin (git://github.com/vojtajina/traceur-compiler) fatal: read error: Operation timed out
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v0.10.31
npm ERR! npm  v2.1.2
npm ERR! code 128

npm ERR! Command failed: fatal: read error: Operation timed out
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxx/npm-debug.log
