### ISSUE TITLE
Android - isDisplayed() function is not returning False

### ISSUE THREAD

**Issue by agyadav** [appium/appium#4547]
My Code Structure is:

if(driver.findElementById(resource1).isDisplayed()){
	    	.
                .
                .
	    }
	    else if(driver.findElementById(resource2).isDisplayed()){
	        .
                .
                .
	    }
	    else{
	    	.
                .
                .
	    }

On execution, the Appium Driver isn't returning 'false' value to the code and it is continuously searching for the resource1 present inside "if" block and finally the driver throws "resource not found" exception and code stops running

**Comment by imurchie** [comment]
Can you provide the Appium server logs in a [gist](https://gist.github.com/)?

**Comment by agyadav** [comment]
Hi Imurchie,

Sorry for the delay...
Had wrong understanding of the function..
Got it clarified and gotto know how to use the above function
