### ISSUE TITLE
How to click android fragments using appium

### ISSUE THREAD

**Issue by Mohanms** [appium/appium#4548]
please find the attachment.

i have 4 options in my apk and i have to click any one by id/xpath/class etc,but unable to click the elements.

the options are not activity, that is created by fragments

Please help..

![untitled](https://cloud.githubusercontent.com/assets/10113027/6227047/fb1c41bc-b6c0-11e4-9511-beabe6e17570.png)

**Comment by 0x1mason** [comment]
Can you please share your code and your appium log?

**Comment by eliezercazares** [comment]
Appium doesn't support Android Fragments.
