### ISSUE TITLE
unable to launch appium client

### ISSUE THREAD

**Issue by kaushal-jha** [appium/appium#4551]
getting error "the application was unable to start correctly(0xc000007b). Click OK to close the application" each time I am trying to launch the appium client.

**Comment by sebv** [comment]
Could you provide full server log?

**Comment by kaushal-jha** [comment]
I dont have a server log as this issue is coming when clicking on the appium client.

**Comment by sebv** [comment]
This needs to be report ed in the client repo: 
https://github.com/appium/appium-dot-exe or https://github.com/appium/appium-dot-app

**Comment by spkr22** [comment]
I got the same issue and it was resolved on installing .net framework .
