### ISSUE TITLE
What does this error indicates? Newbie to Appium for iOS . Help!!

### ISSUE THREAD

**Issue by Bhat123** [appium/appium#4553]
Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --address "127.0.0.1" --command-timeout "7200" --pre-launch --platform-version "7.1.1" --platform-name "iOS" --app "com.techendeavour.magcryptall" --show-ios-log --device-name "iPhone 5 (A5D1623F-EA8A-4F8D-86C2-EEBB271FA761)"

info: [debug] Starting Appium in pre-launch mode

info: Pre-launching app
info: [debug] App is an iOS bundle, will attempt to run as pre-existing
info: [debug] Creating new appium session 27456b78-42f4-4156-af06-3e85708f3904
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

error: Could not determine Xcode version:Could not parse Xcode version (xcodebuild output was: )

error: Could not get the iOS SDK version because the Xcode version could not be determined.

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 8.1

info: [debug] Checking whether instruments supports our device string

info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

error: Failed getting devices. Err: Error: Command failed: /bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices
. Stdout: . Stderr: .

info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

error: Failed getting devices. Err: Error: Command failed: /bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices
. Stdout: . Stderr: .

info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":null,"iOSSDKVersion":"8.1","deviceName":"iPhone 5 (A5D1623F-EA8A-4F8D-86C2-EEBB271FA761)","platformVersion":"7.1.1"}

error: uncaughtException: Cannot read property '0' of null date=Wed Feb 18 2015 01:44:00 GMT+0530 (IST), pid=25338, uid=157765039, gid=687221094, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.12.0, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --address, 127.0.0.1, --command-timeout, 7200, --pre-launch, --platform-version, 7.1.1, --platform-name, iOS, --app, com.techendeavour.magcryptall, --show-ios-log, --device-name, iPhone 5 (A5D1623F-EA8A-4F8D-86C2-EEBB271FA761)], rss=82575360, heapTotal=66926080, heapUsed=45250512, loadavg=[1.40380859375, 1.50927734375, 1.6484375], uptime=541603, trace=[column=35, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js, function=Function.IOS.getDeviceStringFromOpts, line=941, method=IOS.getDeviceStringFromOpts, native=false, column=14, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js, function=IOS.getDeviceString, line=1024, method=getDeviceString, native=false, column=24, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js, function=, line=1108, method=null, native=false, column=46, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=525, method=null, native=false, column=17, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=254, method=null, native=false, column=21, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=151, method=null, native=false, column=21, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=251, method=null, native=false, column=34, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=615, method=null, native=false, column=25, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=516, method=null, native=false, column=7, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js, function=null, line=111, method=null, native=false], stack=[TypeError: Cannot read property '0' of null,     at Function.IOS.getDeviceStringFromOpts (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:941:35),     at IOS.getDeviceString (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1024:14),     at null.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1108:24),     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:525:46,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:254:17,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:151:21,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:251:21,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:615:34,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:516:25,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:111:7]

**Comment by sebv** [comment]
just pass: "deviceName":"iPhone 5"

**Comment by Bhat123** [comment]
Thanks it worked.
