### ISSUE TITLE
How to open inspector from command line?

### ISSUE THREAD

**Issue by sujittarun** [appium/appium#4558]

**Comment by tarunsujit** [comment]
@Jonahss can you please look into this?

**Comment by 0x1mason** [comment]
Which inspector?

**Comment by tarunsujit** [comment]
@0x1mason appium inspector

**Comment by sujittarun** [comment]
I want to open Appium-inspector from terminal. Do we have any command for it?

**Comment by Jonahss** [comment]
You can just run the executable file.
