### ISSUE TITLE
setValue not working for UIASecureTextField [iOS]

### ISSUE THREAD

**Issue by kani19** [appium/appium#4559]
Not able to set value in UIASecureTextField for iOS

> ```
> info: [debug] Got result from instruments: {"status":0,"value":"Password"}
> ```
> 
> info: [debug] Responding to client with success: {"status":0,"value":"Password","sessionId":"c4bce046-5bb1-472b-a254-5f088e804ab3"}
> info: <-- GET /wd/hub/session/c4bce046-5bb1-472b-a254-5f088e804ab3/element/0/text 200 731.143 ms - 82 {"status":0,"value":"Password","sessionId":"c4bce046-5bb1-472b-a254-5f088e804ab3"}
> info: --> POST /wd/hub/session/c4bce046-5bb1-472b-a254-5f088e804ab3/appium/element/0/value {"id":"0","value":"hello"}
> info: [debug] Pushing command to appium work queue: "au.getElement('0').setValue('hello')"
> info: [debug] Sending command to instruments: au.getElement('0').setValue('hello')
> info: [debug] [INST] 2015-02-18 10:20:08 +0000 Debug: Got new command 12 from instruments: au.getElement('0').setValue('hello')
> info: [debug] [INST] 2015-02-18 10:20:08 +0000 Debug: evaluating au.getElement('0').setValue('hello')
> info: [debug] [INST] 2015-02-18 10:20:08 +0000 Debug: target.frontMostApp().elements()[0].elements()[1].elements()[0].elements()[0].tap()
> info: [debug] Didn't get a new command in 120 secs, shutting down...
> info: Shutting down appium session

Code used:

```
>   MobileElement myMobElem = (MobileElement) mydriver2.findElementByClassName("UIASecureTextField");
>   myMobElem.setValue("hello");
```

Any solution ?

Appium 1.3.4
Using Java Client

**Comment by imurchie** [comment]
Does it work to send keys rather than set value?

**Comment by kani19** [comment]
No. It doesn't work.

**Comment by imurchie** [comment]
Can you provide a log for that?

**Comment by kani19** [comment]
info: [debug] Pushing command to appium work queue: "au.getElementByType('UIASecureTextField')"
info: [debug] Sending command to instruments: au.getElementByType('UIASecureTextField')
info: [debug] [INST] 2015-02-19 06:25:32 +0000 Debug: Got new command 10 from instruments: au.getElementByType('UIASecureTextField')
info: [debug] [INST] 2015-02-19 06:25:32 +0000 Debug: evaluating au.getElementByType('UIASecureTextField')
info: [debug] [INST] 2015-02-19 06:25:34 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-02-19 06:25:34 +0000 Debug: responding with:
info: [debug] [INST] 2015-02-19 06:25:34 +0000 Debug: Running system command #11: /usr/local/Cellar/node/0.10.36/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"0"}}...
info: [debug] Socket data received (38 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"0"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"0"},"sessionId":"2074b347-7cc1-44dc-bc4c-5615f061ed9f"}
info: <-- POST /wd/hub/session/2074b347-7cc1-44dc-bc4c-5615f061ed9f/element 200 5601.569 ms - 87 {"status":0,"value":{"ELEMENT":"0"},"sessionId":"2074b347-7cc1-44dc-bc4c-5615f061ed9f"}
info: --> POST /wd/hub/session/2074b347-7cc1-44dc-bc4c-5615f061ed9f/element/0/value {"id":"0","value":["text"]}
info: [debug] Pushing command to appium work queue: "au.getElement('0').setValueByType('text')"
info: [debug] Sending command to instruments: au.getElement('0').setValueByType('text')
info: [debug] [INST] 2015-02-19 06:25:38 +0000 Debug: Got new command 11 from instruments: au.getElement('0').setValueByType('text')
info: [debug] [INST] 2015-02-19 06:25:38 +0000 Debug: evaluating au.getElement('0').setValueByType('text')
info: [debug] [INST] 2015-02-19 06:25:38 +0000 Debug: target.frontMostApp().keyboard().typeString("t")
info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments
info: [debug] [INST] 2015-02-19 06:27:38 +0000 Stopped: Script was stopped by the user
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] {"__argument":{"WIRApplicationNameKey":"Safari","WIRIsApplicationProxyKey":false,"WIRApplicationIdentifierKey":"com.apple.mobilesafari"},"__selector":"_rpc_applicationDisconnected:"}
info: [debug] [INST] Instruments Trace Complete (Duration : 184.258194s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Stopping iOS log capture
info: [debug] [REMOTE] Disconnecting from remote debugger
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Cleaning up appium session
info: [debug] We shut down because no new commands came in
info: [debug] [REMOTE] Debugger socket disconnected

**Comment by imurchie** [comment]
Interesting. I'm adding to the next milestone.

**Comment by kani19** [comment]
Thanks

**Comment by kornfan** [comment]
Looks like it is possible to send keys and set value when the UIASecureTextfield is referenced by XPath not by class name (iOS 8.2 iPad 2 Simulator)

**Comment by Jitu1888** [comment]
Hi Kornfan,

WebElement Login =findElement(getLocator("DA.LoginPage"));
			Login.click();
			((IOSElement)Login).setValue(username);

It is not sending any data to textfield.
UIAUTOMATOR for loginpage is DA.LoginPage=UIAUTOMATOR::target.frontMostApp().mainWindow().scrollViews()[0].webViews()[0].textFields()[0]

Can you please help me out why it is not sending any data.
Appium:1.3.7
Xcode 7
ipad 8.1.3

Thanks 
Jitu

**Comment by Jitu1888** [comment]
I will really appreciate if you help in this matter urgently.

Thanks
Jitu

**Comment by imurchie** [comment]
This works in current implementation. Closing.
