### ISSUE TITLE
iOS source code has text with & but page source has &amp;

### ISSUE THREAD

**Issue by chrigrahcisco** [appium/appium#4563]
Continuing my Appium adventure with the latest Appium.app 1.3.5, Appium-Python-Client 0.13, Xcode 6.1.1, iOS 8.x simulator.

I'm having issues with text comparisons when the text includes &

My AUT source code includes this:

`cell.textLabel.text=@"Cases & Contracts"; `

However, Appium reports the page source as this:

`<UIANavigationBar name="Cases &amp; Contracts" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/1/0" x="0" y="24.125" width="375" height="51.5625">`

When I obtain the name attribute it's reported back as:

`navbar_text = self.driver.find_element_by_xpath('//UIANavigationBar/UIAStaticText').get_attribute('name')
print navbar_text
Cases & Contracts`

That's great. However, when I attempt to invoke an assertion on the text the comparison fails:

`self.assertTrue(navbar_text is 'Cases & Contracts')
AssertionError: False is not true`

I'm assuming it's failing due to `&` vs `&amp;`

Interestingly, xpath finds the elements without issue:

`self.driver.find_element_by_xpath('//UIANavigationBar/UIAStaticText[contains(@name,"Cases & Contracts")]')`

**Comment by jlipps** [comment]
Are you sure you're not just dealing with this? http://stackoverflow.com/questions/2988017/string-comparison-in-python-is-vs

(I.e., try `self.assertEqual(navbar_text, 'Cases & Contracts')`)

**Comment by chrigrahcisco** [comment]
Thanks.

Not sure where I got into the 'is' comparitor, I've been using == elsewhere.

These all pass:
`if navbar_text == "Cases & Contracts"`
`self.assertTrue(navbar_text, 'Cases & Contracts')`
