### ISSUE TITLE
Android Clear Text errors with "Unknown error clearing text"

### ISSUE THREAD

**Issue by glorylo** [appium/appium#4565]
I noticed an obscure error that occurs with our app.  Using clear text, it tries multiple ways to clear text.

It first fails to do a select-all-delete initially (i do not see the cut/copy/paste icons), then it's fall back is to clear via 25 delete keys.  However, because the cursor is in the middle of the text, it fails to fully delete the text.  Aside from that, it fails abnormally with this error:

```
info: <-- POST /wd/hub/session/3a0d7fb4-ac65-4212-8c51-3894857ab812/element/26/click 200 3147.177 ms - 76 {"status":0,"value":true,"sessionId":"3a0d7fb4-ac65-4212-8c51-3894857ab812"}
info: --> POST /wd/hub/session/3a0d7fb4-ac65-4212-8c51-3894857ab812/element {"using":"xpath","value":"//android.widget.EditText[@resource-id='com.pof.android:id/caption']","locator":"xpath"}
info: [debug] Waiting up to 30000ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"xpath","selector":"//android.widget.EditText[@resource-id='com.pof.android:id/caption']","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.EditText[@resource-id='com.pof.android:id/caption']","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding //android.widget.EditText[@resource-id='com.pof.android:id/caption'] using XPATH with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CLASS=android.widget.EditText, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"27"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"27"},"sessionId":"3a0d7fb4-ac65-4212-8c51-3894857ab812"}
info: <-- POST /wd/hub/session/3a0d7fb4-ac65-4212-8c51-3894857ab812/element 200 69.193 ms - 88 {"status":0,"value":{"ELEMENT":"27"},"sessionId":"3a0d7fb4-ac65-4212-8c51-3894857ab812"}
info: --> POST /wd/hub/session/3a0d7fb4-ac65-4212-8c51-3894857ab812/element/27/clear {}
info: [debug] Pushing command to appium work queue: ["element:clear",{"elementId":"27"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:clear","params":{"elementId":"27"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: clear
info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
info: [debug] [BOOTSTRAP] [debug] Clearing text not successful. Attempting to clear by selecting all and deleting.
info: [debug] [BOOTSTRAP] [debug] Clearing text not successful. Attempting to clear by sending delete keys.
info: [debug] [BOOTSTRAP] [error] error while getting method injectInputEvent from class class com.android.uiautomator.core.UiAutomatorBridge with parameter types [class android.view.InputEvent, class java.lang.Boolean] injectInputEvent [class android.view.InputEvent, class java.lang.Boolean]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":13,"value":"Unknown error clearing text"}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Unknown error clearing text"},"sessionId":"3a0d7fb4-ac65-4212-8c51-3894857ab812"}

```

My workaround is to clear it manually with sending in right cursor keys to the end of the text, and then doing backspaces.  

```
            element.Click();
            // right arrow keys 
            for (var i = 0; i < maxChars; i++)
              Driver.KeyEvent(keyCode: 22);

            // backspaces
            for (var i = 0; i < maxChars; i++)
              Driver.KeyEvent(keyCode: 67); 
```

**Comment by imurchie** [comment]
What are the details of your environment? API version? 

The error I think is coming from the second set of delete keys, which should work forward, toward the end of the line.

**Comment by DmitryKa** [comment]
@glorylo thanks! Only one note: key_event was renamed to press_keycode.
https://discuss.appium.io/t/undefined-method-key-event-for-appium-driver/714/4

**Comment by glorylo** [comment]
@imurchie I am using api version 19.   This only happens on certain screens.

On other screens, my workaround does not work.  If the screen has paging, doing the arrow keys actually advance to the next screen.

**Comment by imurchie** [comment]
See also details in #4685.

**Comment by xsmaster** [comment]
I just got this error tonight on
Android API 17
Appium 1.3.7
API Demo project

find_element(:accessibility_id, :OS).click
find_element(:accessibility_id, 'Morse Code').click
find_element(:name, 'OS/Morse Code').type('value')
find_element(:name, 'OS/Morse Code').displayed?
find_element(:name, 'OS/Morse Code').clear


Error that showed on ARC

Selenium::WebDriver::Error::UnknownError: Unknown error clearing text
from /Users/ztw994/.rvm/gems/ruby-2.2.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'

I hope this helps.

**Comment by vikramvi** [comment]
Issue still exists with latest appium version 1.3.7.

Kindly prioritize

**Comment by imurchie** [comment]
@xsmaster Can you provide a [gist](https://gist.github.com/) of the server logs?

**Comment by xsmaster** [comment]
You bet. I'm traveling today. So I will be able to provide the logs in 2 -3
hours.

J

**Comment by xsmaster** [comment]
@imurchie,

Sorry it took me so long. See gist with all the logs. I pulled out everything I could.

To keep it easy to read through I added headers. "#########" for the staring and ending of the log files.

https://gist.github.com/xsmaster/2e34c69a16b815a2ca95

Let me know what else you need.

J

**Comment by imurchie** [comment]
I don't see anything in there indicating a call to `clear`.

**Comment by xsmaster** [comment]
https://gist.github.com/xsmaster/d528dffed98a973b07d7

I screwed up and provide the wrong logs in my last post. here is the goods.

**Comment by moizjv** [comment]
@glorylo @xsmaster @vikramvi thanks for reporting the issue with #5103 it should be fixed. It should be out in the next release

**Comment by d9kgit** [comment]
Could you tell, in which Appium version it will be fixed?

**Comment by moizjv** [comment]
@d9kgit new appium versions have this issue fixed. 1.4.6. Closing the issue, reopen if this is still an issue.

**Comment by yogeshdawkhar** [comment]
@moizjv :- 
I am facing issue on Mi 4i device. Andorid version 5.0.2. script not running but on other device script runs.

 info: [debug] Pushing command to appium work queue: ["find",{"strategy":"id","selector":"com.ifm:id/ed_login","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.ifm:id/ed_login","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding com.ifm:id/ed_login using ID with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.ifm:id/ed_login]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"1"}}
> info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"844df883-6e0d-432d-bafe-dc601f82c6b1"}
> info: <-- POST /wd/hub/session/844df883-6e0d-432d-bafe-dc601f82c6b1/element 200 12903.125 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"844df883-6e0d-432d-bafe-dc601f82c6b1"}
> info: --> POST /wd/hub/session/844df883-6e0d-432d-bafe-dc601f82c6b1/element/1/value {"id":"1","value":["8517003369"]}
> info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"1","text":"8517003369","replace":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"8517003369","replace":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: setText
> info: [debug] [BOOTSTRAP] [debug] Using element passed in.
> info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
> info: [debug] [BOOTSTRAP] [debug] Text not cleared. Assuming remainder is hint text.
> info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: 8517003369
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":13,"value":"Unknown error"}
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Unknown error"},"sessionId":"844df883-6e0d-432d-bafe-dc601f82c6b1"}
> info: <-- POST /wd/hub/session/844df883-6e0d-432d-bafe-dc601f82c6b1/element/1/value 500 727.150 ms - 182 
> info: --> DELETE /wd/hub/session/844df883-6e0d-432d-bafe-dc601f82c6b1 {}
> info: Shutting down appium session
> info: [debug] Pressing the HOME button
> info: [debug] executing cmd: E:\Android\sdk\platform-tools\adb.exe -s c7e8e4c7 shell "input keyevent 3"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 15.87
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] UiAutomator shut down normally
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"844df883-6e0d-432d-bafe-dc601f82c6b1"}

**Comment by imurchie** [comment]
@yogeshdawkhar Can you create a new issue with the information necessary, rather than adding to an issue that has been closed for a year and a half. Things have changed so the context of your problem is almost certainly different than this one.
