### ISSUE TITLE
Issue with launching 8.1 simulator with appium 1.3.4

### ISSUE THREAD

**Issue by adc-nbangale** [appium/appium#4566]
Hello,
I am trying to launch iPad Air(8.1) simulator with appium 1.3.4 and seeing the issue as below. 
I am using Xcode 6.1.1. 
I am stuck on running my automation tests because of this problem. 
Would really appreciate your help.

appium --device-name "iPad Air" --platform-version 8.1
info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"deviceName":"iPad Air","platformVersion":"8.1"}
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/Shared/Jenkins/Home/Documents/Auction.com.app","locationServicesAuthorized":true,"screenshotWaitTimeout":"90","newCommandTimeout":"100000","bundleId":"com.auction.ipad","waitForAppScript":true,"platformName":"iOS","locationServicesEnabled":true,"version":"8.1","deviceName":"iPad Air","launchTimeout":"900000","autoAcceptAlerts":false}}
info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : screenshotWaitTimeout, waitForAppScript, version
info: [debug] Using local app from desired caps: /Users/Shared/Jenkins/Home/Documents/Auction.com.app
info: [debug] Creating new appium session 0c16511f-d3f1-428a-8b31-8b5306bbd34b
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.1
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPad Air","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Air (8.1 Simulator)'
info: [debug] iOS sim UDID is EBC99CBC-80DB-40AE-BD7B-F8E24CCB109D
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.12.0/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"oneByOne"}
...o: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
info: [debug] Dynamic bootstrap path: /Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap/bootstrap-75c1a60be67c2ec8.js
info: [debug] Reusing dynamic bootstrap: /Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap/bootstrap-75c1a60be67c2ec8.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPad Air","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Air (8.1 Simulator)'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPad Air","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Air (8.1 Simulator)'
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] Cleaning sim data files
info: [debug] Executing: xcrun simctl erase EBC99CBC-80DB-40AE-BD7B-F8E24CCB109D
info: [debug] Not setting locale
info: [debug] Setting iOS and app preferences
info: [debug] Sim files for the 8.1 SDK do not yet exist, launching the sim to populate the applications and preference dirs
info: [debug] Not pre-launching simulator
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.12.0/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"oneByOne"}
...o: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
info: [debug] Dynamic bootstrap path: /Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap/bootstrap-75c1a60be67c2ec8.js
info: [debug] Reusing dynamic bootstrap: /Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap/bootstrap-75c1a60be67c2ec8.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPad Air","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Air (8.1 Simulator)'
info: Launching instruments briefly then killing it
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Attempting to run app on iPad Air (8.1 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPad Air (8.1 Simulator)" /Users/Shared/Jenkins/Home/Documents/Auction.com.app -e UIASCRIPT "/Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap/bootstrap-75c1a60be67c2ec8.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":900000}
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
warn: attempted to kill instruments 11 times. Could be stuck on the wait condition.
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
warn: attempted to kill instruments 12 times. Could be stuck on the wait condition.
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments

**Comment by adc-nbangale** [comment]
@imurchie , can you please help me out in this issue?

**Comment by imurchie** [comment]
Can you launch the simulator on your own?

**Comment by adc-nbangale** [comment]
Thanks @imurchie for getting back to me. Yes i can from xcode. I have ios 8.0 and 8.1 simulators installed which i can launch from xcode.

**Comment by ngochoan1011** [comment]
I have a similar issue. I can run the tests successfully on real devices but not the simulators.

The error logs are not easy to trace the problem. Look forward to some suggestions from @imurchie

**Comment by rajeshchaudhary1** [comment]
@ngochoan1011  Can you please post the appium log? May be i can help by with that.

**Comment by adc-nbangale** [comment]
Hi @ngochoan1011, I am still seeing this issue.
Here are my logs

appium --device-name "iPad Air" --platform-version 8.1
info: Welcome to Appium v1.3.4 (REV c8c79a8)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"deviceName":"iPad Air","platformVersion":"8.1"}
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/Shared/Jenkins/Home/Documents/Auction.com.app","locationServicesAuthorized":true,"screenshotWaitTimeout":"90","newCommandTimeout":"100000","bundleId":"com.auction.ipad","waitForAppScript":true,"platformName":"iOS","locationServicesEnabled":true,"version":"8.1","deviceName":"iPad Air","launchTimeout":"900000","autoAcceptAlerts":false}}
info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : screenshotWaitTimeout, waitForAppScript, version
info: [debug] Using local app from desired caps: /Users/Shared/Jenkins/Home/Documents/Auction.com.app
info: [debug] Creating new appium session 0c16511f-d3f1-428a-8b31-8b5306bbd34b
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.1
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPad Air","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Air (8.1 Simulator)'
info: [debug] iOS sim UDID is EBC99CBC-80DB-40AE-BD7B-F8E24CCB109D
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.12.0/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"oneByOne"}
...o: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
info: [debug] Dynamic bootstrap path: /Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap/bootstrap-75c1a60be67c2ec8.js
info: [debug] Reusing dynamic bootstrap: /Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap/bootstrap-75c1a60be67c2ec8.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPad Air","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Air (8.1 Simulator)'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPad Air","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Air (8.1 Simulator)'
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] Cleaning sim data files
info: [debug] Executing: xcrun simctl erase EBC99CBC-80DB-40AE-BD7B-F8E24CCB109D
info: [debug] Not setting locale
info: [debug] Setting iOS and app preferences
info: [debug] Sim files for the 8.1 SDK do not yet exist, launching the sim to populate the applications and preference dirs
info: [debug] Not pre-launching simulator
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.12.0/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"oneByOne"}
...o: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
info: [debug] Dynamic bootstrap path: /Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap/bootstrap-75c1a60be67c2ec8.js
info: [debug] Reusing dynamic bootstrap: /Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap/bootstrap-75c1a60be67c2ec8.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPad Air","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Air (8.1 Simulator)'
info: Launching instruments briefly then killing it
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Attempting to run app on iPad Air (8.1 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPad Air (8.1 Simulator)" /Users/Shared/Jenkins/Home/Documents/Auction.com.app -e UIASCRIPT "/Users/Shared/Jenkins/Home/Library/Application Support/appium/bootstrap/bootstrap-75c1a60be67c2ec8.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":900000}
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
warn: attempted to kill instruments 11 times. Could be stuck on the wait condition.
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
warn: attempted to kill instruments 12 times. Could be stuck on the wait condition.
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments

@rajeshchaudhary1 , have you seen this kind of issue earlier?

**Comment by rajeshchaudhary1** [comment]
Seeing it 1st time. can you uncheck the timeout and try? also are you able to launch the application in simulator using instrument?

**Comment by ngochoan1011** [comment]
Thanks @rajeshchaudhary1 for your reply. Here is the log:

```
hoan$ appium
info: Welcome to Appium v1.3.6 (REV 004f52f249d3513809e7d0734d9205d1fec19f8e)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"safariIgnoreFraudWarning":true,"platformVersion":"8.2","safariAllowPopups":false,"browserName":"Safari","platformName":"iOS","deviceName":"iPhone 6"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
info: [debug] Configuring Safari session
info: [debug] We're on iOS8+ so not copying mobile safari app
info: [debug] Creating new appium session 0b58f230-cc8b-410d-99f0-ea61d72bc666
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.2
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPhone 6","platformVersion":"8.2"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.2 Simulator)'
info: [debug] iOS sim UDID is 1C418B82-5D7A-4F41-A827-3C432DE4F05C
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Localizable.strings is not currently supported when using real devices.
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/user/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.12.0/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not...nually modify!
info: [debug] Dynamic bootstrap path: /Users/user/Library/Application Support/appium/bootstrap/bootstrap-dea1a1242b3bfb9b.js
info: [debug] Reusing dynamic bootstrap: /Users/user/Library/Application Support/appium/bootstrap/bootstrap-dea1a1242b3bfb9b.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPhone 6","platformVersion":"8.2"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.2 Simulator)'
info: [debug] Not setting device type since we're using bundle ID and assuming app is already installed
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] Cleaning sim data files
info: Executing: xcrun simctl erase 1C418B82-5D7A-4F41-A827-3C432DE4F05C with timeout 2000
info: [debug] Cleaning mobile safari data files
info: Couldn't find Safari support directories to clean out old data. Probably there's nothing to clean out
info: [debug] Not setting locale
info: [debug] Setting iOS and app preferences
info: [debug] Sim files for the 8.2 SDK do not yet exist, launching the sim to populate the applications and preference dirs
info: [debug] Not pre-launching simulator
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/user/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.12.0/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not...nually modify!
info: [debug] Dynamic bootstrap path: /Users/user/Library/Application Support/appium/bootstrap/bootstrap-dea1a1242b3bfb9b.js
info: [debug] Reusing dynamic bootstrap: /Users/user/Library/Application Support/appium/bootstrap/bootstrap-dea1a1242b3bfb9b.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPhone 6","platformVersion":"8.2"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.2 Simulator)'
info: Launching instruments briefly then killing it
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Attempting to run app on iPhone 6 (8.2 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 (8.2 Simulator)" com.apple.mobilesafari -e UIASCRIPT "/Users/user/Library/Application Support/appium/bootstrap/bootstrap-dea1a1242b3bfb9b.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
warn: attempted to kill instruments 11 times. Could be stuck on the wait condition.
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
warn: attempted to kill instruments 12 times. Could be stuck on the wait condition.
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
info: [debug] Checking condition to see if we should kill instruments
info: [debug] We launched the simulator but the required dirs don't yet exist. Waiting some more...
```

**Comment by ngochoan1011** [comment]
It's probably related to the Safari error: the simulator is started but it failed to open Safari.

I posted a comment in another ticket: https://github.com/appium/appium/issues/3966

**Comment by ngochoan1011** [comment]
Yes, I confirm it is the Safari-related error, I could run the test **successfully** with an app that does not touch the Safari.

**Comment by imurchie** [comment]
This feels like we're going through a setup step that we don't want to for Safari. Adding to the bug list to be looked at.

**Comment by rkavalap** [comment]
This does not seem to be relevant at this time. Closing legacy bug.
