### ISSUE TITLE
Is finding elements by xpath will be removed from appium in future?

### ISSUE THREAD

**Issue by Xotabu4** [appium/appium#4567]
automation guys in my project not allow to use XPATH, because they heard that find by xpath will be removed from appium in future. I cannot find any mentions about this. For me thats looks like a fake.

This is true?

**Comment by bootstraponline** [comment]
XPath will not be removed from appium, it's one of the most popular features.

**Comment by 0x1mason** [comment]
You are correct.  We have no plans to remove find by XPATH.
