### ISSUE TITLE
Running tests with XCode 5.1, Appium 1.3.4, iOS Simulator 7.1, TestNG first time gives error

### ISSUE THREAD

**Issue by kani19** [appium/appium#4571]
When i run my iOS tests using : XCode 5.1, Appium 1.3.4, iOS Simulator 7.1, TestNG, i get the following error:

> info: [debug] Getting sdk version from xcrun with a timeout
> error: xcrun threw an error Error: Command failed: 
> error: Stderr: 
> error: Stdout: 

This is a consistent error that appears only for the 1st run. Then i have to open XCode, run my application on iOS Simulator 7.1 and then quit. After this, if i run my tests, this error disappears.
Not sure if this is an issue with Appium or something else.

Logs:

>
info: --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"Appium","platformVersion":"7.1","app":"/Users/myuser/Desktop/ClientCertApps/7.1App/ClientCert.app","platformName":"iOS","deviceName":"iPhone Simulator","noReset":"true"}}
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
warn: Converting cap noReset from string to boolean. This might cause unexpected behavior.
info: [debug] Using local app from desired caps: /Users/myuser/Desktop/ClientCertApps/7.1App/ClientCert.app
info: [debug] Creating new appium session d3e9f56a-0fa2-4d44-96f0-13d6f6ec6f84
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
error: xcrun threw an error Error: Command failed: 
error: Stderr: 
error: Stdout: 
info: [debug] Getting sdk version from xcrun with a timeout
error: xcrun threw an error Error: Command failed: 
error: Stderr: 
error: Stdout: 
info: [debug] Getting sdk version from xcrun with a timeout
error: xcrun threw an error Error: Command failed: 
error: Stderr: 
error: Stdout: 
error: Could not determine iOS SDK version
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: xcrun threw an error Error: Command failed: 
info: [debug] Error: xcrun threw an error Error: Command failed: 
    at /usr/local/lib/node_modules/appium/lib/devices/ios/xcode.js:81:14
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: xcrun threw an error Error: Command failed: )","origValue":"xcrun threw an error Error: Command failed: "},"sessionId":null}
>

Logs after running XCode once:

>
info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
warn: Converting cap noReset from string to boolean. This might cause unexpected behavior.
info: [debug] Using local app from desired caps: /Users/myuser/Desktop/ClientCertApps/7.1App/ClientCert.app
info: [debug] Creating new appium session 45354bc9-5865-4b3f-80ce-9d79b665c284
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
error: xcrun threw an error Error: Command failed: 
error: Stderr: 
error: Stdout: 
info: [debug] Getting sdk version from xcrun with a timeout
error: xcrun threw an error Error: Command failed: 
error: Stderr: 
error: Stdout: 
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 7.1
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
error: Failed getting devices. Err: Error: Command failed: . Stdout: . Stderr: .
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.1","iOSSDKVersion":"7.1","deviceName":"iPhone Simulator","platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone - Simulator - iOS 7.1" to: "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1"
info: [debug] Final device string is: 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /Users/myuser/Desktop/ClientCertApps/7.1App/ClientCert.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
`parseFileSync()` is deprecated. Use `parseStringSync()` instead.
info: [debug] Could not parse plist file (as XML) at /Users/myuser/Desktop/ClientCertApps/7.1App/ClientCert.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings; assuming it doesn't exist
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/myuser/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.10.36/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. D...ot manually modify!
info: [debug] Dynamic bootstrap path: /Users/myuser/Library/Application Support/appium/bootstrap/bootstrap-1fb90a0f7e596c1d.js
info: [debug] Reusing dynamic bootstrap: /Users/myuser/Library/Application Support/appium/bootstrap/bootstrap-1fb90a0f7e596c1d.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.1","iOSSDKVersion":"7.1","deviceName":"iPhone Simulator","platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone - Simulator - iOS 7.1" to: "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1"
info: [debug] Final device string is: 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.1","iOSSDKVersion":"7.1","deviceName":"iPhone Simulator","platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone - Simulator - iOS 7.1" to: "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1"
info: [debug] Final device string is: 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Not setting locale
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS 7.* simulator log capture
info: [debug] Not pre-launching simulator
info: [debug] No device id or app, not installing to real device.
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1" /Users/myuser/Desktop/ClientCertApps/7.1App/ClientCert.app -e UIASCRIPT "/Users/myuser/Library/Application Support/appium/bootstrap/bootstrap-1fb90a0f7e596c1d.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd5/InstrumentsShim.dylib","LIB_PATH":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd5"}
>

**Comment by imurchie** [comment]
Hopefully this will be fixed by #4556
