### ISSUE TITLE
Session could not be created. stdout maxBuffer exceeded error.

### ISSUE THREAD

**Issue by GokulAthi** [appium/appium#4578]
While running scripts using appium. Error is popping up,

Session could not be created. stdout maxBuffer exceeded error. All the paths in 'Environment variables' are set without any spaces.

**Comment by GokulAthi** [comment]
![issue](https://cloud.githubusercontent.com/assets/5848908/6314345/6c003cec-ba01-11e4-8d12-2399dca2444c.jpg)

**Comment by sebv** [comment]
@0x1mason we probably want to have a look, maybe use spawn or improve adb another way, moving to 1.4.
