### ISSUE TITLE
getelements - Appium, doesn't work for several elements

### ISSUE THREAD

**Issue by igalep** [appium/appium#4580]
I'm trying to get all elemetns and their values. I have a table with several items in it (IOS)

All the items within the table have the same name but different values, while I'm trying to get elements in one try by using

List<WebElement> l = driver.findElements(By.name(name)); 
and then iterating trough the list and pulling the value by

((MobileElement) l.get(i)).getAttribute("value"); 
I'm getting the correct value only on first iteration (first element) , all others are return empty value...

if I'm changing the code to :

        //1
        List<WebElement> weList = driver.findElements(driver, By.name(name));
        String val = ((MobileElement) weList.get(0)).getAttribute("value");

        //2
        weList = driver.findElements(driver, By.name(name));
        val = ((MobileElement) weList.get(1)).getAttribute("value");

        //3
        weList = driver.findElements(driver, By.name(name));
        val = ((MobileElement) weList.get(2)).getAttribute("value");
I'm getting the correct values.

It seems that I need to pull the element each time I'm trying to access it. Is it a bug , or I just miss something ?

**Comment by moizjv** [comment]
@igalep so how are you iterating through a list other wise. Do you mean `weList`, how are you iterating through weList?

**Comment by igalep** [comment]
@moizjv - I've fixed the post with the correct list's name.

regarding the list's iteration - I've tried with traditional "for / list's length" & with Java's iterator , none of them worked ...

**Comment by moizjv** [comment]
@igalep does below code work?

```
//1
    List<WebElement> weList = driver.findElements(driver, By.name(name));
    String val = ((MobileElement) weList.get(0)).getAttribute("value");

    //2
    weList = driver.findElements(driver, By.name(name));
    val1 = ((MobileElement) weList.get(1)).getAttribute("value");
    val2= ((MobileElement) weList.get(2)).getAttribute("value");
```

**Comment by sebv** [comment]
This is a driver issue, please post in the driver project, or appium discuss.
