### ISSUE TITLE
Finding an element sometimes doesn't even though the element object is present

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#4581]
I have noticed that finding an element is not always working. First time if we navigate to a particular page and try to find an element, It may find. But in the same test run if we navigate to the same page for a second time and try to find the same element, it is not finding. I am using the find_element_by_id and find_element_by_text API's mostly.
Please provide a solution for this issue.

**Comment by glorylo** [comment]
I can say I have seen this issue on our end and I can't quite explain it.  We have a test that if we run individually it works consistently.. but if we run it in a suite the same test it can fail from not finding an element.  

failing log when trying to find the 'title':
``` 
info: [debug] Set Android implicit wait to 30000ms
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"37bd6847-773c-4a77-b5fd-5ecd
5237e22c"}
info: <-- POST /wd/hub/session/37bd6847-773c-4a77-b5fd-5ecd5237e22c/timeouts/implicit_wait 200 1.209 ms - 76 {"stat
us":0,"value":null,"sessionId":"37bd6847-773c-4a77-b5fd-5ecd5237e22c"}
info: --> POST /wd/hub/session//element {"using":"xpath","value":"//*[@resource-id='com.pof.android:id/thetitle']",
"locator":"xpath"}
info: <-- POST /wd/hub/session//element 404 0.763 ms - 40
info: --> GET /wd/hub/session/37bd6847-773c-4a77-b5fd-5ecd5237e22c/screenshot {}
info: [debug] executing cmd: C:\Apps\adt\sdk\platform-tools\adb.exe -s 02c80f85d0219250 shell "/system/bin/rm /data
/local/tmp/screenshot.png; /system/bin/screencap -p /data/local/tmp/screenshot.png "
```

What I don't understand is if the implicit wait is set to 30 seconds it can return so quickly without retrying.  You can see it returns a 404 error in 0.763 ms.  But the screenshot and dom trace we can see clearly see the element on screen.


Here's the working case when running the test individually:

```
info: [debug] Set Android implicit wait to 30000ms
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"47cf17ca-1852-432f-849f-f30a2b9ad64d"}
info: <-- POST /wd/hub/session/47cf17ca-1852-432f-849f-f30a2b9ad64d/timeouts/implicit_wait 200 1.066 ms - 76 {"status":0,"value":null,"sessionId":"47cf17ca-1852-432f-849f-f30a2b9ad64d"}
info: --> POST /wd/hub/session/47cf17ca-1852-432f-849f-f30a2b9ad64d/element {"using":"xpath","value":"//*[@resource-id='com.pof.android:id/thetitle']","locator":"xpath"}
info: [debug] Waiting up to 30000ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"xpath","selector":"//*[@resource-id='com.pof.android:id/thetitle']","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[@resource-id='com.pof.android:id/thetitle']","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding //*[@resource-id='com.pof.android:id/thetitle'] using XPATH with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CLASS=android.widget.TextView, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"20"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"20"},"sessionId":"47cf17ca-1852-432f-849f-f30a2b9ad64d"}
info: <-- POST /wd/hub/session/47cf17ca-1852-432f-849f-f30a2b9ad64d/element 200 158.733 ms - 88 {"status":0,"value":{"ELEMENT":"20"},"sessionId":"47cf17ca-1852-432f-849f-f30a2b9ad64d"}
info: --> GET /wd/hub/session/47cf17ca-1852-432f-849f-f30a2b9ad64d/element/20/text {}
info: [debug] Pushing command to appium work queue: ["element:getText",{"elementId":"20"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getText","params":{"elementId":"20"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getText
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"Search"}
info: [debug] Responding to client with success: {"status":0,"value":"Search","sessionId":"47cf17ca-1852-432f-849f-f30a2b9ad64d"}
info: <-- GET /wd/hub/session/47cf17ca-1852-432f-849f-f30a2b9ad64d/element/20/text 200 23.540 ms - 80 {"status":0,"value":"Search","sessionId":"47cf17ca-1852-432f-849f-f30a2b9ad64d"}
```

**Comment by naveenjammula** [comment]
can you please provide the update on this ??

**Comment by glorylo** [comment]
wondering if others have seen it as well.

**Comment by jlipps** [comment]
check out this line:

> info: --> POST /wd/hub/session//element {"using":"xpath","value":"//*[@resource-id='com.pof.android:id/thetitle']", "locator":"xpath"}

Notice the malformed URL. That means your client is not sending in the element ID. What client are you using? I'm wondering if there's something going on in that or the test code.

**Comment by glorylo** [comment]
I'm using the dotnet driver for android.   over lengthy periods we sometimes get a fail that will abort all other tests.  

I tried modifying the test suite to reconnect to the appium server for every test but doing so i get these odd issues.  the test code is the same so i doubt it's my test code.  running individually works just fine.  

@naveenjammula may differ.

**Comment by jlipps** [comment]
@glorylo It's almost guaranteed to be something your client is doing; Appium is simply transparently printing out the URL the client called. In this case it's an invalid URL. So it's either the dotnet client or what you've built on top of it that is causing the problem.

**Comment by glorylo** [comment]
Then it's likely the dotnet client.   I never specify the REST request of wd/hub/session//element as it's something underneath the covers.

**Comment by jlipps** [comment]
Do you ever try and reuse an element across driver instantiations?

**Comment by glorylo** [comment]
@jlipps actually no.. so it's like an stale element kind of condition.  

Hmm.. I haven't gotten the time to dig into the dotnet driver but I was hoping someone on that repo may know the source of the issue right away.

**Comment by jlipps** [comment]
OK, yeah it sounds like it's a dotnet client issue then! Thanks for creating the issue there.

**Comment by glorylo** [comment]
:+1: Thanks @jlipps for all you have done for appium :)

**Comment by srinivasfes** [comment]
try use 

wait = new WebDriverWait(driver, 10).pollingEvery(2, TimeUnit.SECONDS)
				.ignoring(NoSuchElementException.class);

---
WebElement wldoClickMoreIcon = driver.findElement(By.xpath("//*[@content-desc='More options'and @index='2']"));
		wait.until(ExpectedConditions.visibilityOf(wldoClickMoreIcon));
		wldoClickMoreIcon.click();

**Comment by naveenjammula** [comment]
The issue is no reproducible now so closing the ticket
