### ISSUE TITLE
How to reuse MobileElements while using Appium

### ISSUE THREAD

**Issue by igalep** [appium/appium#4582]
Hi, 
In my app I've a pattern code as a security authentication.

While I'm log in , I need to set up a new pattern , and then to repeat it for confirmation.

I was thinking to reuse the "dots" elements for second attempt of the pattern selection.

The problem is , each attempt , Appium's server set a new ID to the Mobile Element , and it seems that the step is fail due to NoSuchElement Exception.

Of course the first attempt with the same elements is working, but the second one is fails...

Any idea how I can reuse elements ?

**Comment by 0x1mason** [comment]
Can you share the Appium logs?

**Comment by igalep** [comment]
solved the problem , by storing an element's required properties and by that eliminating the second element's access
