### ISSUE TITLE
Driver.getPageSource() encoding

### ISSUE THREAD

**Issue by medy75** [appium/appium#4583]
If I try to get driver.getPageSource() it gives me XML with bad encoding like:

> \<android.widget.TextView 
index="1" 
text="**Florbal - mu?i**" 
class="android.widget.TextView"
...
bounds="[68,655][712,696]"
resource-id="my.app.test:id/sport_name"
instance="9" />

Bold text should be "**Florbal - muži**"

I can see right encoding in UI Automator Viewer.

java-client-2.1.0.jar with AppiumBootstrap.jar fix from https://github.com/appium/appium/issues/4200 & Appium 1.3.4.1

**Comment by 0x1mason** [comment]
Closing as DUP of #4611
