### ISSUE TITLE
log capture did not start in a reasonable amount of time

### ISSUE THREAD

**Issue by vijay0850** [appium/appium#4587]
Im using Xcode 4.6.3, appium 1.3.5 , Max OS x 10.8.3 Not able to connect my iphone simulator Im getting log capture did not start in a reasonable amount of time. While running the appium server.

**Comment by imurchie** [comment]
Can you provide the Appium server logs as a [gist](https://gist.github.com/).

**Comment by vijay0850** [comment]
https://gist.github.com/31e06b956925510ed22f.git

Please check the above link for appium log file

Error/Warning info:

error: Could not determine Xcode version:Could not parse Xcode version (xcodebuild output was: )
error: Log capture did not start in a reasonable amount of time

info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.example.apple-samplecode.UICatalog/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Creating instruments

**Comment by vijay0850** [comment]
any update on this issues?

**Comment by vijay0850** [comment]
any update on this?

**Comment by imurchie** [comment]
The server is failing to get the correct Xcode version, and assuming the wrong version. This _might_ be the issue. There is an open fix for this (#4556)

What happens if you run `xcodebuild -version` on the command line?

**Comment by vijay0850** [comment]
Its showing the build version correctly,

Xcode 4.6.3
Build version 4H1503

I tried with 3 version of appium 1.3.3 to 1.3.5 but same issues persist please look into the issues

**Comment by vijay0850** [comment]
I guess it working in newer version so you can close this issues as of now :)
