### ISSUE TITLE
Unable to run test script on multiple android devices on chrome browser

### ISSUE THREAD

**Issue by ssandy93** [appium/appium#4591]
Hello,

I am not able to run my test script on multiple android devices (parallel execution). It launches on 1 device and fails to launch on the other device.
Appium version 1.3.4.1
I have started two Appium instances with different ports by commands:

appium -p 4725 -bp 4726 -U "b0132538" --address "127.0.0.1" --chromedriver-port 9516
appium -p 4730 -bp 4731 -U "ZX1B32C997" --address "127.0.0.1" --chromedriver-port 9517

The problem is Chromedriver starts on the same port on both Appium instances i.e. on port 9515  

*Appium logs:* 

> info: [debug] No old chromedrivers seemed to exist
> info: [debug] Spawning chromedriver with: d:\Sandeep\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] [CHROMEDRIVER] Starting ChromeDriver (v2.10.289383) on port 9515
> Only local connections are allowed.
> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"ZX1B32C997"}}}}
> info: [debug] [CHROMEDRIVER STDERR] [0.004][SEVERE]: Could not bind socket to 127.0.0.1:9515
> info: [debug] [CHROMEDRIVER] Port not available. Exiting...
> info: [debug] Chromedriver exited with code 1
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Android\android-sdk\platform-tools\adb.exe -s ZX1B32C997 devices
> info: [debug] 2 device(s) connected

*Capabilities I am using:*

                               AppiumDriver driver = null;	
				        DesiredCapabilities capabilities = new DesiredCapabilities();
					capabilities.setCapability("platformName", "Android");
					capabilities.setCapability("deviceName", "Samsung");
					capabilities.setCapability("udid", "b0132538");
					capabilities.setCapability("browserName", "chrome");
					driver = new AppiumDriver(new URL("http://127.0.0.1:4725/wd/hub"), capabilities);	
					System.out.println("Samsung");
					driver.get("http://www.google.com");
					
			DesiredCapabilities capabilities1 = new DesiredCapabilities();
			capabilities1.setCapability("platformName", "Android");
			capabilities1.setCapability("deviceName", "Moto");
			capabilities1.setCapability("udid", "ZX1B32C997");
			capabilities1.setCapability("browserName", "chrome");
			AppiumDriver driver1 = new AppiumDriver(new URL("http://127.0.0.1:4730/wd/hub"), capabilities1);	
			System.out.println("Moto");
			driver1.get("http://www.google.com");

Please help me in this issue.

Thanks,
Sandeep

**Comment by iParasJain** [comment]
Hey,

Same issue i am also facing.

I have two Samsung devices.

Steps:
1. open two appium with different ports.
2. Execute the same scripts which "ssandy93" has written.
3. launch chrome in both of Samsung device.
4. In one Samsung device, url is opening and in another "chorme Driver" port are not available.

      debug: Spawning chromedriver with: C:\Users\Administrator.win7-PC\Desktop\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
     debug: [CHROMEDRIVER] Starting ChromeDriver (v2.9.248315) on port 9515
 debug: Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"b0132538"}}}}
> debug: [CHROMEDRIVER STDERR] [0.002][SEVERE]: Could not bind socket to 0.0.0.0:9515
> debug: [CHROMEDRIVER] Port not available. Exiting...
> debug: Chromedriver exited with code 1
> debug: Getting connected devices...
> debug: executing: "C:\android-sdk\platform-tools\adb.exe" -s b0132538 devices
> debug: 2 device(s) connected

**Comment by iParasJain** [comment]
Hey,

Same issue i am also facing.

I have two Samsung devices.

Steps:
1. open two appium with different ports.
2. Execute the same scripts which "ssandy93" has written.
3. launch chrome in both of Samsung device.
4. In one Samsung device, url is opening and in another "chorme Driver" port are not available.

     debug: Spawning chromedriver with: C:\Users\Administrator.win7-PC\Desktop\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
     debug: [CHROMEDRIVER] Starting ChromeDriver (v2.9.248315) on port 9515
     debug: Making http request with opts:   {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"b0132538"}}}}
     debug: [CHROMEDRIVER STDERR] [0.002][SEVERE]: Could not bind socket to 0.0.0.0:9515
     debug: [CHROMEDRIVER] Port not available. Exiting...
     debug: Chromedriver exited with code 1
     debug: Getting connected devices...
     debug: executing: "C:\android-sdk\platform-tools\adb.exe" -s b0132538 devices
     debug: 2 device(s) connected

**Comment by iParasJain** [comment]
Please look into this issue..ASAP

Thanks, 
Paras Jain

**Comment by jlipps** [comment]
@iParasJain have you tried with Appium 1.3.7?

**Comment by iParasJain** [comment]
yes, i already tried with Appium 1.3.7.

**Comment by amaanmemon** [comment]
@iParasJain Its Working!! with appium 1.3.7

**Comment by iParasJain** [comment]
ok, i will try once again.

**Comment by sebv** [comment]
Best to wait for appium 1.5 for this kind of setup.

**Comment by imurchie** [comment]
This works in 1.5.
