### ISSUE TITLE
Finding element in iOS taking comparitively more time than in Android

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#4592]
We are executing the same testcases for in both Android and iOS and we noticed that finding an element or tapping on an element in iOS is taking more time than in Android. We use the basic API's like find_element_by_id and click() for finding and clicking on elements. When Android takes less than a second, iOS takes around 2 to 3 seconds.
Could you provide a solution for this?

**Comment by imurchie** [comment]
Please inquire on the [discussion list](https://discuss.appium.io/).

**Comment by naveenjammula** [comment]
I am not sure why this bug is closed we did the time analysis of few events on ios and android devices.It clearly says the event times in iOS is more than android .so please reopen the bug .Below is the summary 

![event_comparision](https://cloud.githubusercontent.com/assets/9447465/6412428/a30d3fee-bea9-11e4-8b6b-815885a59676.png)

**Comment by jlipps** [comment]
It's not a bug because we use completely different technologies to automate iOS and Android. They can't be compared in terms of time relative to each other.

**Comment by naveenjammula** [comment]
I know you use completely different technologies to automate iOS and Android . Then don't compare it. Think from individual platform itself the time time to perform some events is taking more than 2-3 secs which is not acceptable. I am expecting the time should be reduced.Please reopen the bug
