### ISSUE TITLE
Appium's Chrome functional tests should just work with a real device

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium#4593]
We use the secret ip of 10.0.0.2 (or something like that)
which allows the emulator to get to localhost
(of the host machine)
on a real device, it would need to be an actual IP on your network
(like your computer's IP)
should probably have an env var that switches for that in the testsuite

**Comment by 0x1mason** [comment]
We've already got a magic switch, REAL_DEVICE

**Comment by jlipps** [comment]
amazing!
