### ISSUE TITLE
Screen capture on physical iOS device too slow

### ISSUE THREAD

**Issue by GindiKhangura** [appium/appium#4595]
Capturing screen shots on a physical iOS 8.1 device is taking upwards of ~20 seconds.

I initially installed the Appium app and provided a nodeconfig file to connect it to the hub, and using a JUnit test from a separate computer, I retrieved the image and it took too long. I then used the Appium app to start the inspector and view the screen locally, and it too took just as long as it did remotely (~20s).

We are integrating Selenium+Appium into our automation solution, and having users wait ~20 seconds to view the mobile screen is a major issue for us.

Are there any optimization/configuration changes or suggestions that anybody knows of to get the mobile device image remotely in a reasonable amount of time?

**Comment by jlipps** [comment]
What happens if you just use UIAutomation? Does it also take a long time?

**Comment by GindiKhangura** [comment]
It is very quick using UI Automation.

**Comment by jlipps** [comment]
What happens if you set Appium's log level to warn or error?

**Comment by GindiKhangura** [comment]
I set the Appium node's log level to error and I am still able to reproduce the issue.

**Comment by jlipps** [comment]
K, if Appium is taking 20x as long as UIAutomation, it's probably a bug.

**Comment by GindiKhangura** [comment]
This issue was originally on milestone 1.3.7 and it looks like it as pushed back to 1.3.8; as this is a high priority for us, can this issue be investigated and fixed in 1.3.7 please?

**Comment by marloncruz** [comment]
Any updates on this issue?

**Comment by jlipps** [comment]
@GindiKhangura @marloncruz are you still seeing this issue if you use appium 1.5 beta12?

**Comment by GindiKhangura** [comment]
I am not able to reproduce this issue anymore. I am on Appium 1.4.12 or above.

**Comment by jlipps** [comment]
excellent thank you.
