### ISSUE TITLE
Appium shows no GUI while running on Windows

### ISSUE THREAD

**Issue by coloredpanda** [appium/appium#4598]
I've installed appium, It worked fine until one day it stopped showing gui.
Problem has appeared after i've started several utilities from android-sdk and restarted pc. 
Such as monitor.bat, hierarchyviewer.bat, uiautomatorviewer.bat

After problem appeared my Steps to reproduce looks like:
1. Download latest version of Appium (1.3.4.1)
2. Start Appium.exe
3. Check if Appium.exe presents in processes (it presents)
4. Wait until appium's gui is showed (it's not)

So my questions are:
1. How can I debug appium to solve the problem?
2. Is there a way to see starting logs or smth?

Environment:
Appium.exe 1.3.4.1
Windows 6.3.9600 N/A Build 9600
Java.exe 8.0.31.13

Env Variables:
ANDROID_HOME C:\Users\%username%\AppData\Local\Android\android-sdk
ANDROID_NDK_PATH C:\Users\%username%\Documents\Android\ndk\android-ndk-r8d
JAVA_HOME C:\Program Files (x86)\Java\jre1.8.0_31\bin

**Comment by 0x1mason** [comment]
You can use procmon to see what system call is failing. Probably a load file failure or sim. Also you can capture a (mini, not full) dump when it hangs (starts but does nothing) and send it the appium-dot-executive team here on github. It comes with the pdb symbols so you can also easily analyze the dump yourself.

**Comment by 0x1mason** [comment]
Another thought, which should have been my first: the easiest way to debug this is to clone the [appium-dot-exe](https://github.com/appium/appium-dot-exe) repo, open the project with Visual Studio, and then launch Appium.exe with the debugger attached.
