### ISSUE TITLE
Original error: Could not get the iOS SDK version because the Xcode version could not be determined.

### ISSUE THREAD

**Issue by Changdeo** [appium/appium#4599]
Hi All,

I am facing this exception intermittently. I am using Xcode 6.1 and iPhone 6 (iOS 8.1) simulator.

I tried xcode-select -p and shows correct path "Application/Xcode.app/Developers/Content

(Original error: Could not get the iOS SDK version because the Xcode version could not be determined.) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 12.50 seconds
Build info: version: '2.43.0', revision: 'accb3003b9fb8f7cae30f9669b4c594a065396a6', time: '2014-09-09 22:22:51'
System info: host: 'pneitsh53097D-iMac.local', ip: '10.50.210.151', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.5', java.version: '1.6.0_65'
Driver info: io.appium.java_client.AppiumDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:88)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:44)

**Comment by sebv** [comment]
We don't really have enough information here, looks like there could be an issue with the XCode install.

The appium server log contains more relevant information, if you could post it.

**Comment by jervill** [comment]
Hi @sebv , I think I'm running into the same problem. I'm using XCode 6.1.1 and the iPhone 6 (iOS 8.1) Simulator. Here's the relevant snippet of appium's log:

```
info: [debug] Creating new appium session d4ee7202-8ade-4806-b134-8cf2bc149e1b
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
error: Could not determine Xcode version:Expected a path ending with '/Contents/Developer', but got /Applications/Xcode.app/Contents/Developer/
info: [debug] Setting iOS SDK Version
error: Could not get the iOS SDK version because the Xcode version could not be determined.
error: Could not get the iOS SDK version because the Xcode version could not be determined.
error: Could not get the iOS SDK version because the Xcode version could not be determined.
error: Could not determine iOS SDK version
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not get the iOS SDK version because the Xcode version could not be determined.
info: [debug] Error: Could not get the iOS SDK version because the Xcode version could not be determined.
    at /Users/jvillanueva/Code/austin-automation/appium/lib/devices/ios/xcode.js:111:10
    at /Users/jvillanueva/Code/austin-automation/appium/lib/devices/ios/xcode.js:80:14
    at /Users/jvillanueva/Code/austin-automation/appium/lib/devices/ios/xcode.js:57:9
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not get the iOS SDK version because the Xcode version could not be determined.)","origValue":"Could not get the iOS SDK version because the Xcode version could not be determined."},"sessionId":null}
```

**Comment by Changdeo** [comment]
I am using xcode 6.1 and iOS 6 (8.1) simulator.
I see that in xcode.js file we use "xcodebuild -version" command to get xcode version. I added some extra logs there and found that sometime "xcodebuild -version" returns empty string and next the parsing fails. 
error: Could not determine Xcode version:Could not parse Xcode version (xcodebuild output was: )
info: [debug] Setting iOS SDK Version
info: [debug] 
error: Could not get the iOS SDK version because the Xcode version could not be determined.
info: [debug] 
error: Could not get the iOS SDK version because the Xcode version could not be determined.
info: [debug] 
error: Could not get the iOS SDK version because the Xcode version could not be determined.
error: Could not determine iOS SDK version
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not get the iOS SDK version because the Xcode version could not be determined.
info: [debug] Error: Could not get the iOS SDK version because the Xcode version could not be determined.
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/xcode.js:62:10
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/xcode.js:44:13
    at ChildProcess.exithandler (child_process.js:652:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)

**Comment by mbknieri** [comment]
I got the same issue appium log output as @jervill. I am running Appium 1.3.7 without problems on my other machine so I ran appium-doctor to see the path of Xcode on the working machine. Turns out on the machine that had the error, there was a '/' at the end of the path. In other words, my path was /Applications/Xcode.app/Contents/Developer**/**   instead of   /Applications/Xcode.app/Contents/Developer. So I ran  **xcode-select --switch /Applications/Xcode.app/Contents/Developer** to remove the '/' from the end of my xcode path. When I ran appium again the error was gone.

**Comment by jlipps** [comment]
FWIW the path bug has been fixed and will be part of the next release, I think

**Comment by jervill** [comment]
Thanks for the tip @mbknieri ! I'm not sure how my path got the trailing '/' or which is correct. Good to hear that a fix might be part of the next release.

**Comment by sebv** [comment]
Is it fixed?

**Comment by jcesarmobile** [comment]
I'm having the same problem with appium app

**Comment by shardul** [comment]
adding to @jcesarmobile comment, You should select the XCode of corresponding command line tools installation, in case you have 2 versions on your computer.

**Comment by vinyasjain77** [comment]
I am having the same problem when I launch appium for a app of mine.

Error is as follows:
error: Could not determine iOS SDK version
error: Could not pre-launch appium: Error: Command failed: /bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version

Appium version: 1.4.13 (Draco)
xcode:7.1

**Comment by ivan-baranovski-intellectsoft** [comment]
I have the same problems.

Appium version: 1.4.13 (Draco)
xcode:7.1

**Comment by sundara-asm** [comment]
Is there any solution for this. I am facing the same issue on both simulator and real device

**Comment by jcesarmobile** [comment]
Did you try to manually selecting the path to xcode app? that worked for me

**Comment by sundara-asm** [comment]
I did by using Xcode 7.2 and it did not work. reinstalled 7.1 and even that did not work

**Comment by NareshSamala** [comment]
Am using real device with iOS 9.3.1 and  XCode 7.3, Facing same problem..
When am using iOS 8.4 with XCode 6.4, it  is working fine for me..

**Comment by anthonygreen** [comment]
Same issue trying to use appium 1.5.2 with Xcode 6.4 and 7.1 simulators 

[iOS] Could not determine iOS SDK version
[MJSONWP] Encountered internal error running command: Error: Command 'xcrun --sdk iphonesimulator --show-sdk-version' timed out after 3000ms

**Comment by imurchie** [comment]
Can you run `xcrun --sdk iphonesimulator --show-sdk-version` manually? What happens?

**Comment by iopoz** [comment]
when i perform "xcrun --sdk iphonesimulator --show-sdk-version manually" i get sdk version: 9.3. It works in terminal

**Comment by nareshkc** [comment]
Same when i run xcrun --sdk iphonesimulator --show-sdk-version in terminal it is showing 9.3

**Comment by shabana-parveen** [comment]
My problem gets resolved by enabling "Use Native Instrument Library"

**Comment by gologox** [comment]
@shabana-parveen Where do you enable that? I am having the same issue currently out of nowhere. Version 1.5.3 of Appium and iOS 9.2.

**Comment by shabana-parveen** [comment]
By Appium GUI, Please refer attached screenshot, but I think you app gets crashed with version 1.5.3. 
 
![screen shot 2016-09-01 at 2 02 49 pm](https://cloud.githubusercontent.com/assets/13347267/18160854/e6839434-704c-11e6-8f8c-54df1588b029.png)

**Comment by alexfradiani** [comment]
I started to get this error with Xcode 7.3.1.
For a reason unknown to me, if I launch the tests while having Xcode opened and after previously running the simulator from there, the error doesn't happen anymore.
