### ISSUE TITLE
Xpath locator Performance issue in actual iOS devices

### ISSUE THREAD

**Issue by vasudarch** [appium/appium#4604]
Any plans to improve performance of Xpath locator in actual iOS devices?

**Comment by imurchie** [comment]
@0x1mason any plans?

**Comment by 0x1mason** [comment]
We know performance is an issue on iOS real devices.  It's something we hope to tackle in the next several months but we dont have anything specific that I can share at this time. Wish I had something better for you.

**Comment by sebv** [comment]
Ok this is another xpath bug.

**Comment by jlipps** [comment]
This was for UIAutomation support which has gone away. Closing.
