### ISSUE TITLE
Session not created exception thrown when automating the Hybrid App 

### ISSUE THREAD

**Issue by bchand1748** [appium/appium#4605]
The Hybrid App does not intermittently load on the Phone. It throws out ,""status":33,"value":{"message":"A new session could not be created. (Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity)","origValue":"Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity"},"sessionId":null}."  The error only occurs if I run the entire code where App is switched to webview. However, if I comment out the code and use only the code to open the app it works every time without a fail. I have restarted the server to see if the issue goes away but it seems to be consistent.

**Comment by bchand1748** [comment]
@jlipps Any thoughts ? I could provide the Appium log and code used if needed. Thanks.

**Comment by sebv** [comment]
>> I could provide the Appium log and code used if needed.

@bchand1748 you could and you should.

**Comment by sebv** [comment]
Closing old issue (and sorry for the late response), may be reopened if needed.
