### ISSUE TITLE
Cannot unlock Android device with pin-code enabled

### ISSUE THREAD

**Issue by andry-tino** [appium/appium#4613]
I am trying to automate an app using latest version of Appium running on MacOS and testing an app on Android. The test is written in C# and uses the dotnet-appium-driver.

The problem is that the Android device (API 19) has a pincode. Appium, when session is requested, cannot unlock the device.

> --> POST /wd/hub/session {"desiredCapabilities":{"appium-version":"1.0","browserName":"","autoWebview":true,"app":"/Users/navdevuser/APKs/DynamicsNav.apk","platformName":"Android","platformVersion":"4.4","deviceName":"Android","fullReset":true}}
info: Client User-Agent string: undefined
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : appium-version
info: [debug] No appActivity desired capability or server param. Parsing from apk.
info: [debug] No appPackage desired capability or server param. Parsing from apk.
info: [debug] Using local app from desired caps: /Users/navdevuser/APKs/DynamicsNav.apk
info: [debug] Creating new appium session 7123eb9e-8481-4540-a5dd-9896a3360203
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.8.0_20
info: [debug] Using fast reset? false
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present
info: [debug] Checking whether adb is present
info: [debug] Using adb from /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb devices
info: [debug] 1 device(s) connected
info: Found device 32045315cf653127
info: [debug] Setting device id to 32045315cf653127
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 wait-for-device
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Parsing package and activity from app manifest
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/aapt
info: [debug] Extracting package and launch activity from manifest.
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/aapt dump badging /Users/navdevuser/APKs/DynamicsNav.apk
info: [debug] badging package: com.microsoft.dynamics.nav
info: [debug] badging act: com.microsoft.dynamics.nav.DynamicsNav
info: [debug] Parsed package and activity are: com.microsoft.dynamics.nav/com.microsoft.dynamics.nav.DynamicsNav
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: Device API level is: 19
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "getprop persist.sys.language"
info: [debug] Current device persist.sys.language: en
info: [debug] java -jar "/usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/Users/navdevuser/APKs/DynamicsNav.apk" "/tmp/com.microsoft.dynamics.nav" en
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 push "/tmp/com.microsoft.dynamics.nav/strings.json" /data/local/tmp
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/aapt
info: [debug] Retrieving process from manifest.
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/aapt dump xmltree /Users/navdevuser/APKs/DynamicsNav.apk AndroidManifest.xml
info: [debug] Set app process to: com.microsoft.dynamics.nav
info: [debug] Uninstalling com.microsoft.dynamics.nav
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "am force-stop com.microsoft.dynamics.nav"
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 uninstall com.microsoft.dynamics.nav
info: [debug] App was not uninstalled, maybe it wasn't on device?
info: [debug] Checking app cert for /Users/navdevuser/APKs/DynamicsNav.apk.
info: [debug] executing cmd: java -jar /usr/local/lib/node_modules/appium/node_modules/appium-adb/jars/verify.jar /Users/navdevuser/APKs/DynamicsNav.apk
info: [debug] App already signed.
info: [debug] Zip-aligning /Users/navdevuser/APKs/DynamicsNav.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/zipalign
info: [debug] Zip-aligning apk.
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/zipalign -f 4 /Users/navdevuser/APKs/DynamicsNav.apk /var/folders/4r/1_9mg9550zvchwlw96v0033c0000gr/T/appium115126-37506-15ecstf.tmp
info: [debug] MD5 for app is cfdd5948b2f1dfb0209fea8e2caa8a3d
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "ls /data/local/tmp/cfdd5948b2f1dfb0209fea8e2caa8a3d.apk"
info: [debug] Getting install status for com.microsoft.dynamics.nav
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "pm list packages -3 com.microsoft.dynamics.nav"
info: [debug] App is not installed
info: Installing App
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "mkdir -p /data/local/tmp/"
info: [debug] Removing any old apks
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "ls /data/local/tmp/*.apk"
info: [debug] Found an apk we want to keep at /data/local/tmp/cfdd5948b2f1dfb0209fea8e2caa8a3d.apk
info: [debug] Couldn't find any apks to remove
info: [debug] Uninstalling com.microsoft.dynamics.nav
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "am force-stop com.microsoft.dynamics.nav"
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 uninstall com.microsoft.dynamics.nav
info: [debug] App was not uninstalled, maybe it wasn't on device?
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "pm install -r /data/local/tmp/cfdd5948b2f1dfb0209fea8e2caa8a3d.apk"
info: [debug] Forwarding system:4724 to device:4724
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 forward tcp:4724 tcp:4724
info: [debug] Pushing appium bootstrap to device...
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 push "/usr/local/lib/node_modules/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/
info: [debug] Pushing settings apk to device...
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 install "/usr/local/lib/node_modules/appium/build/settings_apk/settings_apk-debug.apk"
info: [debug] Pushing unlock helper app to device...
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 install "/usr/local/lib/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"
info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "ps 'uiautomator'"
info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] [BOOTSTRAP] [debug] json loading complete.
info: [debug] Waking up device if it's not alive
info: [debug] Pushing command to appium work queue: ["wake",{}]
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: wake
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "dumpsys window"
info: Unlocking screen
info: [debug] Screen is locked, trying to unlock
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "dumpsys window"
info: [debug] Screen is locked, trying to unlock
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "dumpsys window"
info: [debug] Screen is locked, trying to unlock
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "dumpsys window"
info: [debug] Screen is locked, trying to unlock
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "dumpsys window"
info: [debug] Screen is locked, trying to unlock
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "dumpsys window"
info: [debug] Screen is locked, trying to unlock
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
info: [debug] executing cmd: /Users/navdevuser/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 32045315cf653127 shell "dumpsys window"
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 12.105
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] UiAutomator shut down normally
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Screen did not unlock
info: [debug] Error: Screen did not unlock
    at null.<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/android/android-controller.js:395:25)
    at /usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:1463:4
    at null.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:172:9)
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Screen did not unlock)","origValue":"Screen did not unlock"},"sessionId":null}
info: <-- POST /wd/hub/session 500 24056.037 ms – 164

Unfortunately, I cannot get rid of the pincode ad my tests need to work with it. How can I solve this problem? Thankyou

**Comment by 0x1mason** [comment]
Appium doesn't currently have this capability.  I have never tried to input a pin, so I cannot tell you with certainty how to do it.  However, the most obvious route is using `adb`.  You will need to run the commands yourself.  The first thing I would try is:

1. Wake the device.
2. Send the PIN using keyevents [as described here.](http://stackoverflow.com/a/28370951/347155) The KEYCODE constant strings are [listed here](http://developer.android.com/reference/android/view/KeyEvent.html).
3. Start the Appium-based automation.

If you need further feedback on implementation, try asking on http://discuss.appium.io.

Thanks for using Appium and good luck!

**Comment by andry-tino** [comment]
Thank you for providing some ideas to work on this problem. Looking forward to having this capability soon in Appium :)
