### ISSUE TITLE
Switching context does not work

### ISSUE THREAD

**Issue by hardik-d** [appium/appium#4615]
below is the code snippet:

set_context "WEBVIEW_1"
within_context('WEBVIEW_1') do
@driver.find_element(:id, "button-create-account").click
end
set_context "NATIVE_APP"
within_context('NATIVE_APP') do
@driver.find_element(:name, "icon close").click
end
//# sleep 2
set_context "WEBVIEW_1"
within_context('WEBVIEW_1') do
@driver.find_element(:id, "button-create-account").click
end

I am using appium 1.3.4 and above code looks okay to me but i still get Selenium::WebDriver::Error::NoSuchElementError: An element could not be located on the page using the given search parameters.

I am trying to interact with native and webview elements and thought this simple test should pass. Let me know if need more info.

Also notice the commented sleep. if i add sleep the test works.

**Comment by hardik-d** [comment]
@JessicaSachs let me know if need more info

**Comment by 0x1mason** [comment]
We need the appium logs. I can't tell what platform this is.  Ideally there would never be need to sleep or poll for state, but unfortunately sometimes you do. In this case there's a race condition of some kind. Are you certain the second element is immediately visible after you click the first?

**Comment by hardik-d** [comment]
hey @0x1mason ,

unfortunately logs are not much useful. let me explain my scenario again. 

1) i click on a button and go to next screen
2) click on x from the second screen and come back to previous screen

Issue is when i come back to the previous screen and try to click on the same element again it cannot locate the element. clearly suggests that it takes a while to load views and even waiting does not help. sleep works since that gives the app proper time to load the screen.

If you still insist on appium logs let me know i will give it to you.

**Comment by sebv** [comment]
@hardik-d click is asynchronous so the sleep or some kind of spinning is needed.

**Comment by sebv** [comment]
Closing, old issue, not a bug, please go to https://discuss.appium.io/ for support.
