### ISSUE TITLE
Writing a loop to open an App X number of times throws a Not yet implemented exception.

### ISSUE THREAD

**Issue by bchand1748** [appium/appium#4616]
int count = 1;
	
	while (count<3)
	{
	List<WebElement> button = driver.findElements(By.className("android.widget.Button"));// Find all the elements in the class and store in button
	
	
	
	System.out.println(button.size());
	
	button.get(3).click();// Click Sign In button 
	count ++; 
	driver.close();
	}
	
	}
	
	}

**Comment by 0x1mason** [comment]
Can you provide the appium log?

Also, you're closing the driver in the loop.  Is that intentional?

**Comment by bchand1748** [comment]
Yes, it is intentional. If I don't close the driver, the code fails to open the App second time and throws A new session could not be created exception.   I tried running the code, I am not getting the same error so I am closing the issue.
