### ISSUE TITLE
Finding ,clicking,tap an element is taking more time in Android

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#4618]
Finding ,clicking,tap an element is taking more time in Android. We did the time analysis of different events and below is the summary.
![event_comparision](https://cloud.githubusercontent.com/assets/9447465/6412700/4d8dc558-bead-11e4-94e8-9157f1690855.png)

**Comment by amedvedjev** [comment]
not clear what you are comparing. are BOTH some real devices or BOTH some simulators?

**Comment by 0x1mason** [comment]
What's behavior are you expecting? The ios and Android automation stacks are totally different.

**Comment by naveenjammula** [comment]
Time analysis for these events are done on real devices for both android and iOS.I am expecting the time should be reduced to perform these events in both android and iOS . To perform few events it is taking more than 2-3 secs which is not acceptable..

**Comment by naveenjammula** [comment]
I know ios and Android automation stacks are totally different but still the time should be reduced to perform these events in both android and iOS .

**Comment by Jonahss** [comment]
2-3 seconds for a find and tap command does seem unusual. We should make sure there have not been serious performance regressions.

@naveenjammula I notice that the find and tap command separately take much less time than when they are performed together. That's curious indeed.
I'm assuming you used the java-client, correct?
Also, why didn't you use Xpath on Android?

**Comment by amedvedjev** [comment]
is xPath has any benefit against ID? i thought ID best and fastest - is it?

**Comment by Jonahss** [comment]
Oh yeah definitely. Was just wondering why it wasn't on the chart.

**Comment by amedvedjev** [comment]
anyway e.g. with real iOS device delay is expected

**Comment by naveenjammula** [comment]
I am using the Python client

**Comment by 0x1mason** [comment]
I see your point now. The click delay on Android is strange. What version of Appium is this?

**Comment by naveenjammula** [comment]
It is appium version 1.3.4

**Comment by 0x1mason** [comment]
We'll look into this.  Can you try updating in the interim? Doubt it will make a difference, but worth trying.

**Comment by naveenjammula** [comment]
I tried in appium version 1.3.7 but still the same issue

**Comment by naveenjammula** [comment]
when this issue is going to fix

**Comment by 0x1mason** [comment]
I'm not certain. Not in the upcoming release. If this is an important issue
for you, I encourage you to submit a patch. If you need help with it, we're
happy to assist.

**Comment by naveenjammula** [comment]
any update on this bug ??

**Comment by giladna** [comment]
+1

**Comment by imurchie** [comment]
I just did a perfunctory test on the latest version, this seems to be fixed. Find by id takes 0.004819 seconds, and clicking takes another  0.000337.

**Comment by SrinivasanTarget** [comment]
@triager please close
