### ISSUE TITLE
Instruments crashed on startup (real device, safari browser test)

### ISSUE THREAD

**Issue by riverhead013** [appium/appium#4619]
Hello, 
I'm facing an issue when safari browser crashes on startup (real device).
I could see that safari launches on my device and then immediately crashes.

**Error that i could see in Appium Logs**
Instruments trace error: Target failed to run: Permission to debug com.mobilesafari was denied. The app must be signed with a development identity (e.g. iOS Development)
...
Instruments crashed on startup

**My capabilities**
DesiredCapabilities capabilities = new DesiredCapabilities();

capabilities.SetCapability("platformName", "iOS");
capabilities.SetCapability("deviceName", "myIphone");
capabilities.SetCapability("platformVersion", "8.1.3");
capabilities.SetCapability("udid", "c691fa47e3b2d384f3202bef7f622d65a10e9299");
capabilities.SetCapability("bundleId", "com.apple.mobilesafari");

driver = new IOSDriver(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities);

I've enabled "Enable UI Automation" option on device.
Please advice what i'm doing wrong? 

**Full Appium Logs**
https://www.dropbox.com/s/mjalj296tpab9qu/AppiumLogs.rtf?dl=0

**Comment by riverhead013** [comment]
Full Appium Logs:
https://www.dropbox.com/s/mjalj296tpab9qu/AppiumLogs.rtf?dl=0

**Comment by 0x1mason** [comment]
Does the test host machine have the cert you used to sign the app?

**Comment by sebv** [comment]
Please refer to the doc, you need to use browserName=safari, Safari need to be started with SafariLauncher.
