### ISSUE TITLE
Appium crosswalk- cordova application

### ISSUE THREAD

**Issue by Rajesh902** [appium/appium#4620]
I'd like to run Appium tests on a Crosswalk-Cordova application using cucumber with appium 1.3.5 version.But i am not able to switch to WEBVIEW context. Its returning only NATIVE_APP context. So I could not run the test.Can any one tell me, appium support Cross walk ?

**Comment by sebv** [comment]
Not sure never try, I'll put it as something we should investigate. But it says in the doc:

`Unlike Cordova, Crosswalk doesn't use the Android WebView`

**Comment by sebv** [comment]
@0x1mason assigning to you.

cc @bootstraponline , maybe you heard of it.

**Comment by bootstraponline** [comment]
I haven't heard of crosswalk before

**Comment by 0x1mason** [comment]
> Unlike Cordova, Crosswalk doesn't use the Android WebView: its features are more closely aligned with Chrome on Android (as Crosswalk and Chrome share the same ancestor, Chromium).

It sounds like we'd have to use Chromedriver, but I don't think it'd work ootb, since we launch the browsers using harcoded package names and I assume the Crosswalk-derived apps have their own package names.

We'd probably have to allow people to specify custom Chromium-based browsers to get this working. It's not a bad idea, but unless Crosswalk gets wider use, I think this would be something we'd look at down the road.

**Comment by jlipps** [comment]
We should probably fire one of these up and see if it's a simple tweak to our webview finding logic before opining much further on it. We've got it in the next feature release bucket so we can evaluate when to do this investigation later.

**Comment by 0x1mason** [comment]
@Rajesh902 there's an existing WD implementation for it that's based on ChromeDriver.

https://github.com/crosswalk-project/crosswalk-website/wiki/Crosswalk-WebDriver

**Comment by KITSGautamraojangili** [comment]
Looks like Crosswalk-WebDriver does not has a windows version for now, they have said they were going to to integrate it with Appium. I was not able to find any further information about it.

https://lists.crosswalk-project.org/pipermail/crosswalk-dev/2014-September/001974.html

Does any one has any further information on it?

**Comment by hypery2k** [comment]
there's an open issue for this: https://github.com/crosswalk-project/crosswalk-web-driver/issues/17

**Comment by chOOnz** [comment]
Any updates yet? Would be nice to at least get a short response on how things are.

**Comment by jlipps** [comment]
sorry @chOOnz nothing from our end

**Comment by chOOnz** [comment]
Thanks for the fast response @jlipps 
Seems like we have to wait until the developers of CrossWalk will adjust their code then.

**Comment by DariaTl** [comment]
Hi guys , any news ? is there a way to automate crosswalk apks with Appium desktop ?
