### ISSUE TITLE
Not able find the elements in Native App

### ISSUE THREAD

**Issue by vijay0850** [appium/appium#4621]
![image](https://cloud.githubusercontent.com/assets/10095173/6427681/0cd36bf6-bfae-11e4-8632-defd77c8fd8e.png)

Hi,

Anyone help me to find the elements from android.webkit.webview package to the java appium script

How to get the userText field and password field elements from apk file and so I can pass the value  to UI of the Appium script,.

Thanks,
Vijay

**Comment by vijay0850** [comment]
Please provide one working example for understanding

**Comment by vietnq254** [comment]
Hello,

Order to locate elements in Webview, we have 2 ways:
1. Use device that has ```API >=19``` and ```UIAutomator```
2. Get the url of the current page and open it in browser (Firefox, Chrome,...) and then see the IDs, ClassNames,... of the elements

Here is the code to detect the current url:
```
Set<String> contextNames = dr.getContextHandles();
Assert.assertTrue(contextNames.size() > 1); // ['NATIVE_APP', 'WEBVIEW_1', ...]

for (String contextName : contextNames)
{
	if (!contextName.equals("NATIVE_APP"))
	{
		dr.context(contextName);
                break;
	}
}

String url = dr.getCurrentUrl();
```
Order to work with Webview:
```
1. if API<19 then AutomationName = "Selendroid"
2. if API>=19 then AutomationName = "Appium" (by default)
```

Cheer!

**Comment by vijay0850** [comment]
Getting instrumentation failed error on running selendroid in appium

**Comment by vietnq254** [comment]
What is your code? version of Appium, Java client? and log?
I suggest you use Appium 1.3.5: ```npm install -g appium```

**Comment by vijay0850** [comment]
Launching Appium with command: '/Volumes/Appium 1/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --address "127.0.0.1" --port "4725" --command-timeout "7200" --session-override --log "/tmp/appium.log" --webhook "localhost:9876" --automation-name "Appium" --platform-name "Android" --platform-version "4.2" --app "/Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk" --no-reset --app-pkg "com.flipkart.android" --app-activity "com.flipkart.android.SplashActivity" --app-wait-package "com.flipkart.android" --app-wait-activity "com.flipkart.android.SplashActivity" --device-name "0123456789ABCDEF"

info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)

info: Appium REST http interface listener started on 127.0.0.1:4725

info: [debug] Non-default server args: {"app":"/Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk","address":"127.0.0.1","port":4725,"sessionOverride":true,"noReset":true,"log":"/tmp/appium.log","webhook":"localhost:9876","androidPackage":"com.flipkart.android","androidActivity":"com.flipkart.android.SplashActivity","androidWaitPackage":"com.flipkart.android","androidWaitActivity":"com.flipkart.android.SplashActivity","deviceName":"0123456789ABCDEF","platformName":"Android","platformVersion":"4.2","automationName":"Appium","defaultCommandTimeout":7200}

info: Console LogLevel: debug
info: File LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}

info: <-- GET /wd/hub/status 200 47.022 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}

info: <-- GET /wd/hub/status 200 35.345 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}

info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk","appPackage":"com.flipkart.android","appActivity":"com.flipkart.android.SplashActivity","platformVersion":"4.2.2","DEVICE":"Selendroid","automationName":"Selendroid","browserName":"","platformName":"Android","deviceName":"0123456789ABCDEF"}}

info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : DEVICE
info: [debug] Using local app from desired caps: /Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk

info: [debug] Creating new appium session d006bb75-82f1-4583-bf12-e8f4918bfb52
info: [debug] Starting selendroid server
info: [debug] Getting Java version

info: Java version is: 1.8.0_31

info: [debug] Checking whether selendroid is built yet

info: [debug] Selendroid server exists!

info: [debug] Using fast reset? false

info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present

info: [debug] Checking whether adb is present

info: [debug] Using adb from /Applications/android-sdk-macosx/platform-tools/adb

info: Retrieving device

info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb devices

info: [debug] 1 device(s) connected

info: Found device 0123456789ABCDEF

info: [debug] Setting device id to 0123456789ABCDEF
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF wait-for-device

info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF shell "echo 'ready'"

info: [debug] Starting logcat capture

info: [debug] Checking whether aapt is present

info: [debug] Using aapt from /Applications/android-sdk-macosx/build-tools/21.1.2/aapt

info: [debug] Checking if has internet permission from manifest.
info: [debug] executing cmd: /Applications/android-sdk-macosx/build-tools/21.1.2/aapt dump badging /Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk

info: [debug] Rebuilt selendroid server already exists, no need to rebuild it with a new manifest

info: [debug] Checking signed status of /tmp/selendroid.com.flipkart.android.apk
info: [debug] Checking app cert for /tmp/selendroid.com.flipkart.android.apk.
info: [debug] executing cmd: java -jar "/Volumes/Appium 1/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/jars/verify.jar" /tmp/selendroid.com.flipkart.android.apk

info: [debug] Checking signed status of /Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk

info: [debug] Checking app cert for /Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk.

info: [debug] executing cmd: java -jar "/Volumes/Appium 1/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/jars/verify.jar" /Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk

info: [debug] App already signed.

info: [debug] Zip-aligning /tmp/selendroid.com.flipkart.android.apk

info: [debug] Checking whether zipalign is present

info: [debug] Using zipalign from /Applications/android-sdk-macosx/build-tools/21.1.2/zipalign

info: [debug] Zip-aligning apk.

info: [debug] executing cmd: /Applications/android-sdk-macosx/build-tools/21.1.2/zipalign -f 4 /tmp/selendroid.com.flipkart.android.apk /var/folders/5v/kcnr5fls28d7mghxd5d0c67w0000gn/T/appium11523-618-nttmhc.tmp

info: [debug] App already signed.

info: [debug] Zip-aligning /Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk

info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from /Applications/android-sdk-macosx/build-tools/21.1.2/zipalign

info: [debug] Zip-aligning apk.
info: [debug] executing cmd: /Applications/android-sdk-macosx/build-tools/21.1.2/zipalign -f 4 /Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk /var/folders/5v/kcnr5fls28d7mghxd5d0c67w0000gn/T/appium11523-618-1d43hav.tmp

info: [debug] Rebuilt selendroid apk does not exist, uninstalling any instances of it on device to make way for new one

info: [debug] Uninstalling com.flipkart.android.selendroid

info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF shell "am force-stop com.flipkart.android.selendroid"

info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF uninstall com.flipkart.android.selendroid

info: [debug] App was not uninstalled, maybe it wasn't on device?

info: [debug] Getting install status for com.flipkart.android.selendroid
info: [debug] Getting device API level
info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF shell "getprop ro.build.version.sdk"

info: [debug] Device is at API Level 17
info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF shell "pm list packages -3 com.flipkart.android.selendroid"

info: [debug] App is not installed
info: [debug] Rebuilt selendroid is not installed, installing it
info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF install -r "/tmp/selendroid.com.flipkart.android.apk"

info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF shell "getprop persist.sys.language"

info: [debug] Current device persist.sys.language: en

info: [debug] java -jar "/Volumes/Appium 1/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk" "/tmp/com.flipkart.android" en

info: --> GET /wd/hub/status {}

info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}

info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Did not successfully proxy server command"},"sessionId":"d006bb75-82f1-4583-bf12-e8f4918bfb52"}

info: <-- GET /wd/hub/status 500 53.027 ms - 210 

info: [debug] No strings.xml for language 'en', getting default strings.xml

info: [debug] java -jar "/Volumes/Appium 1/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk" "/tmp/com.flipkart.android"

info: [debug] Not uninstalling app since server not started with --full-reset

info: [debug] Checking app cert for /Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk.

info: [debug] executing cmd: java -jar "/Volumes/Appium 1/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/jars/verify.jar" /Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk

info: [debug] App already signed.

info: [debug] Zip-aligning /Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk
info: [debug] Checking whether zipalign is present

info: [debug] Using zipalign from /Applications/android-sdk-macosx/build-tools/21.1.2/zipalign
info: [debug] Zip-aligning apk.
info: [debug] executing cmd: /Applications/android-sdk-macosx/build-tools/21.1.2/zipalign -f 4 /Users/suresh/Documents/workspace/Tester/apps/flip/com.flipkart.android.apk /var/folders/5v/kcnr5fls28d7mghxd5d0c67w0000gn/T/appium11523-618-1ftt5lw.tmp

info: [debug] MD5 for app is 7424b498e568f675a7d81f8522dfd08a

info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF shell "ls /data/local/tmp/7424b498e568f675a7d81f8522dfd08a.apk"

info: [debug] Getting install status for com.flipkart.android

info: [debug] Getting device API level

info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF shell "getprop ro.build.version.sdk"

info: [debug] Device is at API Level 17

info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF shell "pm list packages -3 com.flipkart.android"

info: [debug] App is installed

info: [debug] Forwarding system:8080 to device:8080
info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF forward tcp:8080 tcp:8080

info: [debug] Pushing settings apk to device...

info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF install "/Volumes/Appium 1/Appium.app/Contents/Resources/node_modules/appium/build/settings_apk/settings_apk-debug.apk"

info: [debug] Pushing unlock helper app to device...

info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF install "/Volumes/Appium 1/Appium.app/Contents/Resources/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"

info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF shell "dumpsys window"

info: [debug] Screen already unlocked, continuing.

info: [debug] executing cmd: /Applications/android-sdk-macosx/platform-tools/adb -s 0123456789ABCDEF shell "am instrument -e main_activity 'com.flipkart.android.SplashActivity' com.flipkart.android.selendroid/io.selendroid.ServerInstrumentation"

info: [debug] Cleaning up appium session

error: android.util.AndroidException: INSTRUMENTATION_FAILED: com.flipkart.android.selendroid/io.selendroid.ServerInstrumentation
	at com.android.commands.am.Am.runInstrument(Am.java:676)
	at com.android.commands.am.Am.run(Am.java:119)
	at com.android.commands.am.Am.main(Am.java:82)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:235)
	at dalvik.system.NativeStart.main(Native Method)

info: [debug] Error: android.util.AndroidException: INSTRUMENTATION_FAILED: com.flipkart.android.selendroid/io.selendroid.ServerInstrumentation
    at /Volumes/Appium 1/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/lib/adb.js:1378:17
    at null.<anonymous> (/Volumes/Appium 1/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/lib/adb.js:172:9)
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: android.util.AndroidException: INSTRUMENTATION_FAILED: com.flipkart.android.selendroid/io.selendroid.ServerInstrumentation\r)","origValue":"android.util.AndroidException: INSTRUMENTATION_FAILED: com.flipkart.android.selendroid/io.selendroid.ServerInstrumentation\r"},"sessionId":null}
info: <-- POST /wd/hub/session 500 55155.933 ms - 370 

error: Failed to start an Appium session, err was: Error: android.util.AndroidException: INSTRUMENTATION_FAILED: com.flipkart.android.selendroid/io.selendroid.ServerInstrumentation

info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}

info: <-- GET /wd/hub/status 200 47.264 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}

info: <-- GET /wd/hub/status 200 4.443 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"c8c79a85fbd6870cd6fc3d66d038a115ebe22efe"}}}

**Comment by vijay0850** [comment]
Code:-


		// set up appium
		File classpathRoot = new File(System.getProperty("user.dir"));
		File appDir = new File(classpathRoot,"/apps/flip/");
		File app = new File(appDir, "com.flipkart.android.apk");
		DesiredCapabilities mCapabilities = new DesiredCapabilities(); 
		//This capability is only required for device which has android older than 4.4(kitkat) - start. 
		mCapabilities.setCapability("DEVICE", "Selendroid"); 
		mCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"Selendroid"); 
		//This capability is only required for device which has android older than 4.4(kitkat) - end. 
		mCapabilities.setCapability(MobileCapabilityType.BROWSER_NAME, ""); 
		mCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android"); 
		mCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "4.2.2"); 
		mCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "0123456789ABCDEF"); 
		mCapabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath()); 
		mCapabilities.setCapability(MobileCapabilityType.APP_PACKAGE, "com.flipkart.android"); 
		mCapabilities.setCapability(MobileCapabilityType.APP_ACTIVITY, "com.flipkart.android.SplashActivity"); 
		driver = new AndroidDriver(new URL("http://127.0.0.1:4725/wd/hub"),mCapabilities){
 
		@Override 
		public MobileElement scrollToExact( String arg0 ) { 
		// TODO Auto-generated method stub 
		return null; 
		} 
		@Override 
		public MobileElement scrollTo( String arg0 ) { 
		// TODO Auto-generated method stub 
		return null; 
		} 
		}; 

	/*	//Waiting for 3 seconds to complete webview loading. 
		Thread.sleep(3000); 
		// This method returns all contexts supported by appium. 
		Set<String> contextNames = driver.getContextHandles(); 
		for (String contextName : contextNames) { 
		System.out.println(contextName); 
		if (contextName.contains("WEBVIEW")){ 
		//Swithching context to WEBVIEW. By default context is NATIVE_APP. 
		driver.context(contextName); 
		System.out.println(contextName); 
		}
		}
	*/
		//script start here
		
		
		 driver.switchTo().window("NATIVE_APP");
		
        driver.manage().timeouts().implicitlyWait(120, TimeUnit.SECONDS);
        Thread.sleep(2000);
    	
       	WebElement elClick = driver.findElement(By.xpath("//android.view.View[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[3]/android.widget.TextView[1]"));

**Comment by vijay0850** [comment]
not able installing using npm :( getting error

**Comment by vietnq254** [comment]
In your case, the inputs are:
+ Hybrid app
+ Android 4.2.2 (API 17)

The information need to be focused:
```
info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
...
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Did not successfully proxy server command"},"sessionId":"d006bb75-82f1-4583-bf12-e8f4918bfb52"}
```
But it is not clear.

You are using wrong argument for Appium server:``` "automationName":"Appium" ```
It must be:``` "automationName":"Selendroid" ```

In your code, this line is not necessary:
```mCapabilities.setCapability("DEVICE", "Selendroid"); ```

And you should delete the app after upgrading Appium.

**Comment by vietnq254** [comment]
Additional, with Appium 1.3.4.1 (Selendroid 12) there is a problem with Selendroid. So you should to update to Appium 1.3.5 (Selendroid 13).

Because ```Appium 1.3.5 for Windows``` does not exist yet, you can download ```Appium 1.3.4.1 for Windows```.
And then you need to run command:
```npm install -g appium```
It will download ```appium 1.3.5``` to ```C:\Users\[username]\AppData\Roaming\npm\node_modules\appium```.
Then copy this folder ```appium``` and override ```[Appium 1.3.4.1]\Appium\node_modules\appium```

**Comment by moizjv** [comment]
Looks like an discussion and not a bug @vietnq254 thank you for your contribution :+1:  . @vijay0850 can you use [forum](discuss.appium.io) for questions. thanks
