### ISSUE TITLE
Clarify autoAcceptAlerts capability description

### ISSUE THREAD

**Issue by vladisx** [appium/appium#4623]
According to the documentation http://appium.io/slate/en/master/?java#ios-only the autoAcceptAlerts  being used to automatically handle " iOS privacy access permission alerts" only, but from what I see it actually closes each iOS alert that comes up. I am using java client 2.1 and appium version 1.3.5

**Comment by JaniJegoroff** [comment]
Exactly what I was wondering yesterday: https://github.com/appium/appium/issues/6001
