### ISSUE TITLE
Update Selendroid 0.14.0

### ISSUE THREAD

**Issue by aaltat** [appium/appium#4629]
Could the Appium take selendroid 0.14.0 in use? 

Please note that before building new Selendroid, use this: 
https://github.com/selendroid/selendroid/blob/master/third-party/cordova-3.7.0/mvnInstall.sh

-Tatu

**Comment by sebv** [comment]
I suspect you'll need to build from source to use custom Selendroid. @paymand any idea on the best way to use custom Selendroid version?

Is it the Cordova/Selendroid fix you are pointing to?

**Comment by aaltat** [comment]
Yes it's: https://github.com/selendroid/selendroid/pull/788

I did build my own version of Appium with against selendroid 0.14.0 and it did work ok. But it would be nice to have it in the official version to support the latest selendroid.

**Comment by paymand** [comment]
Was just about to see if it works out of the box by upgrading. I think we should even go for Selendroid 0.15.0 now that it's available.

**Comment by paymand** [comment]
Fixed in https://github.com/appium/appium/pull/4671
