### ISSUE TITLE
Unable to find an element on Android emulator using Appium and C#

### ISSUE THREAD

**Issue by coloredpanda** [appium/appium#4631]
I want to automate mobile web site testing on Android emulator using c# and Appium. There is a simple test scenario I want to automate for the start:
1. Start Browser
2. Find an element
3. Clear it
4. Send keys

I've got a problem with the second step. Every time MSTest tries to execute FindElementById line in the code below, I get the error: "An element could not be located on the page using the given search parameters."

 [TestClass]
 public class UnitTest1
 {
     private DesiredCapabilities _capabilities;
     private AndroidDriver _driver;
 
     public void InitializeDriver()
     {
         Console.WriteLine("Connecting to Appium server");
         _capabilities = new DesiredCapabilities();
 
         _capabilities.SetCapability("deviceName", "test_02");
         _capabilities.SetCapability(CapabilityType.BrowserName, "Chrome");
         _capabilities.SetCapability(CapabilityType.Version, "5.0.1");
         _capabilities.SetCapability(CapabilityType.Platform, "Android");
 
         //Application path and configurations
         _driver = new AndroidDriver(new Uri("http://127.0.0.1:4723/wd/hub"), _capabilities);
     }
 
     [TestMethod]
     public void TestMethod1()
     {
         InitializeDriver();
 
         var element = _driver.FindElementById("com.android.browser:id/url");
         element.Clear();
         element.SendKeys(@"http://stackoverflow.com/");
     }
 }

Input string for the method I've got from UIAutomator that is shown below.
![uiautomator01](https://cloud.githubusercontent.com/assets/6676408/6440500/a2d518c0-c0ee-11e4-9e40-a545d810ef14.png)

I tried several combinations for the FindElementById input method:
"com.android.browser:id/url"
"id/url"
"url"
but no luck.

My environment:
Windows 8.1
Appium 1.3.4.1
ChromeDriver 2.14.313457
Android Device Monitor 24.0.2

**Comment by 0x1mason** [comment]
IIUC, ou're conflating the browser with the webpage. You're starting an automation session for Android Chrome.  Appium (via ChromeDriver) directs your queries to the DOM, but you're trying to query the native app.  If you search for a DOM element, you should find it with no problem. If you want to automate Chrome's native context, use the app package capability to launch Chrome.

Here's a Java example. The C# API is almost identical. https://eveningsamurai.wordpress.com/2014/05/16/mobile-web-automation-with-appium/

**Comment by jlipps** [comment]
You can also just scope back out to the native context once you've started chrome (I don't recommend launching Chrome as if it were a native app)

**Comment by coloredpanda** [comment]
@jlipps, how can i scope back?

**Comment by coloredpanda** [comment]
@0x1mason, in the example you've mentioned they use

Setup the Android RemoteWebDriver

driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
driver.get("http://www.google.com");

There is no driver.Get("http://www.google.com") in c# WebDriver, at least I couldn't find it?
Is it by design?
