### ISSUE TITLE
Come up with robust `Scroll` implementations for both iOS and Android

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#4633]
There's no agreed upon, single implementation/method for scrolling on both iOS and Android. At some point we should make an effort for simplifying this for our users and provide good documentation on the preferred method.

**Comment by jlipps** [comment]
what's wrong with the gestures api?

**Comment by Jonahss** [comment]
The gestures api is fine for creating gestures, but users always opt for using other Scroll commands instead, like the "mobile:" javascript commands.

Our clients tend to use things like UiScrollable and the Instruments `ScrollTo` command.

Do we think that the best method would be to implement our own scrolling logic into the clients, using Gestures?

**Comment by jlipps** [comment]
> Do we think that the best method would be to implement our own scrolling logic into the clients, using Gestures?

Yeah I'd prefer to keep it client-side

**Comment by Jonahss** [comment]
Oh really? Hm ok. Then we should switch to using gestures on the clients  :)

**Comment by bootstraponline** [comment]
How do gestures help us create UiScrollables? If they were sufficient then the automation APIs wouldn't have both gestures plus specialized scrolling methods.

**Comment by Fanch-** [comment]
Maybe not create but save time on Android. The scrolling method has to look over the whole Ui so there is time wasted.

**Comment by jlipps** [comment]
@bootstraponline do you have a proposal for a server-side API that does the right thing on both platforms? So far in people's use of the scroll methods I've seen mostly a lot of confusion and not-totally-functional behavior.

**Comment by Jonahss** [comment]
@bootstraponline what can UiScrollables accomplish that gestures cannot?

**Comment by SrinivasanTarget** [comment]
Closing this as we deprecated scrollTo & scrollToExact this in java-client.https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/IOSScrollingSearchingTest.java

**Comment by SrinivasanTarget** [comment]
@triager please close
