### ISSUE TITLE
Is there a way to hide keyboard on an mobile browser on a real Android device?

### ISSUE THREAD

**Issue by PriyaSilverback** [appium/appium#4636]
Hi there,
I have a code, where the website launches on the Android real device, the web site has 2 fields a user name and password. When I send keys to user name field, the keyboard pops up. How do I dismiss this keyboard or click on done/next?

I do know hidekeyboard works on a web app. But how do you handle this on a web browser on a real device, following is my code

**Comment by 0x1mason** [comment]
Send the back key.

**Comment by Jonahss** [comment]
Did sending the back key work @PriyaSilverback ?

**Comment by PriyaSilverback** [comment]
@Jonahss . Nope. It only took my browser back. What I tried is this

driver.getKeyboard().sendKeys(Keys.ENTER); and it worked.

Thank you

**Comment by jlipps** [comment]
I think the back key trick might only work with native apps. Good to know hitting enter works. Also, scoping back out to `NATIVE_APP` and running hideKeyboard would probably have also worked.
