### ISSUE TITLE
Can we set an array for APP_WAIT_ACTIVITY

### ISSUE THREAD

**Issue by vietnq254** [appium/appium#4645]
Hello,

I wrote a test script and want it work for both Selendroid and Appium.
The problem is Selendroid does not expect APP_WAIT_ACTIVITY activity as same as Appium does.

For example:
```
capabilities.setCapability(MobileCapabilityType.APP_WAIT_ACTIVITY, ".Home");
This work for Appium but cannot work for Selendroid
```
Selendroid expects different activities when I try to test:
+ if APP_WAIT_ACTIVITY=".Home" => Log said ".Home" nerver started, current activity is ".Splash"
+ if APP_WAIT_ACTIVITY=".Splash" => Log said ".Splash" nerver started, current activity is ".Spin"
+ if APP_WAIT_ACTIVITY=".Spin" => Log said ".Spin" nerver started, current activity is ".Home"

So I wonder if I can declare array by some way for APP_WAIT_ACTIVITY ```{".Home", ".Splash", ".Spin"}``` ?

I am using ```Appium 1.3.5```

Thank you.

**Comment by paymand** [comment]
I *think* we already support that. You just need to have them separated by comma:
``".Home,Splash,.Spin"``
See https://github.com/appium/appium-adb/blob/65fbc161a4b10227b65874a658e23fec0eee193d/lib/adb.js#L1287

**Comment by paymand** [comment]
@0x1mason wrote https://github.com/appium/appium-adb/commit/9b1bb9ca3396a7525ea2a9eadf877e7a484cd10b, so he should know.

**Comment by 0x1mason** [comment]
I did not account for that case. Interesting idea though. I'll mark it as a feature request and we will discuss it for 1.4.0.

**Comment by jlipps** [comment]
pretty sure this already exists, as @paymand mentioned.

**Comment by paymand** [comment]
@0x1mason: See the first link I posted above, I'm using this already.

**Comment by 0x1mason** [comment]
Well then there you go.
