### ISSUE TITLE
Appium in Java outside of JUnit

### ISSUE THREAD

**Issue by GindiKhangura** [appium/appium#4648]
I am unable to use Appium or Selenium outside of JUnits at all. I have the dependencies in the maven POM declared as:

&lt;dependency&gt;
	&lt;groupId&gt;org.seleniumhq.selenium&lt;/groupId&gt;
	&lt;artifactId&gt;selenium-java&lt;/artifactId&gt;
	&lt;version&gt;2.43.1&lt;/version&gt;
	&lt;scope&gt;compile&lt;/scope&gt;
&lt;/dependency&gt;
&lt;dependency&gt;
	&lt;groupId&gt;io.appium&lt;/groupId&gt;
	&lt;artifactId&gt;java-client&lt;/artifactId&gt;
	&lt;version&gt;2.0.0&lt;/version&gt;
	&lt;scope&gt;compile&lt;/scope&gt;
&lt;/dependency&gt;

Creating a driver fails with NoClassDefFound error on the Capabilities class (which is in the selenium-api JAR). I tried to instantiate an Appium-only class, MultiTouchAction, but that too results in the NoClassDefFound error. I am able to do these in a JUnit (in the same plug-in). It seems that Selenium and Appium were meant to be run only in test mode, but I am in dire need of using them in a normal Java application (we're incorporating Selenium and Appium into our automation solution).

Any help would be greatly appreciated.

**Comment by 0x1mason** [comment]
@Jonahss Any thoughts on this?

**Comment by 0x1mason** [comment]
Capabilities is an interface.  What if you use DesiredCapabilities?

**Comment by 0x1mason** [comment]
I created a Maven project with selenium + appium without issue.  I uploaded it for you. https://github.com/0x1mason/mavenexample

**Comment by GindiKhangura** [comment]
Previously, I was using DesiredCapabilities, but it was blowing up on Capabilities.

I created a Java project and added the selenium-api.jar and was able to use it without a junit.

I then went back to the maven project and added selenium-api and selenium-remote-driver to the dependencies, and ran the mvn eclipse:eclipse -DdownloadSources=true, the maven step to copy resources, and mvn install, and when I attempt to launch the application, I get another issue:
Missing Constraint: Import Package: org.openqa.selenium.remote; version="0.0.0".

**Comment by 0x1mason** [comment]
Take a look at the project I uploaded.  It has the remote dependency and
opens without issue.

**Comment by GindiKhangura** [comment]
It is clear that the issue is not with running the application vs junits as I now have an issue when attempting to run the application and encounter an issue with Missing Constraint: Import Package.

I checked your project and I see what you mean, though I'm still not sure why I'm seeing that issue in my project.

**Comment by GindiKhangura** [comment]
We think it is an issue with osgi, and are still working on a resolution. Has anyone been able to use Selenium or Appium in a project where osgi is used?

**Comment by 0x1mason** [comment]
Wow, I don't know.  You're probably better off asking on
http://discuss.appium.io
