### ISSUE TITLE
file authorization does not exsit in director /etc on Mac osx yosemite

### ISSUE THREAD

**Issue by qianyiliushang** [appium/appium#4650]
In the document appium/docs/en/contributing-to-appium/appium-from-source.md there is a phase: Manually modify the element following <allow-root> under <key>system.privilege.taskport</key> in your /etc/authorization file to <true/>.
I try to do this as the doc says, but cannot find the authorization file under /etc, my system is osx yosemite 10.10.2

**Comment by jlipps** [comment]
This step is unnecessary on 10.10. Adding this to 1.3.7 to fix up the documentation. All that's necessary is running `sudo authorize_ios`

**Comment by qianyiliushang** [comment]
ok，thank you

**Comment by rapidsp** [comment]
sudo: authorize_ios: command not found

**Comment by jlipps** [comment]
did you install appium using `npm install -g appium`?

**Comment by sebv** [comment]
I can repro on ci, this is a real issue, trying to figure out how to fix it.

**Comment by sebv** [comment]
Workaround for yosemite:
https://github.com/appium/appium/blob/master/ci/as_current_user

```
as_current_user "node ."
```
