### ISSUE TITLE
How to pass the additional emulator arguments in Appium 1.3.4.1

### ISSUE THREAD

**Issue by ashokkumarg** [appium/appium#4652]
In Windows 7, I have installed the additional emulator Genymotion and downloaded the virtual devices. 

Here my Launch AVD is: Nexus 5 - 4.4.4 - API 19 - 1080x1920(I have chosen this from the Launch Device Dropdown menu).

Now when I try to run/pre-launch the Appium, it gives some error like:

> Starting Node Server
> usage: main.js [-h] [-v] [--shell]
> main.js: error: Unrecognized arguments: Nexus 5 - 4.4.4 - API 19 - 1080x1920.
>                [--localizable-strings-dir LOCALIZABLESTRINGSDIR] [--app APP]
>                [--ipa IPA] [-U UDID] [-a ADDRESS] [-p PORT]
>                [-ca CALLBACKADDRESS] [-cp CALLBACKPORT] [-bp BOOTSTRAPPORT]
>                [-k] [-r BACKENDRETRIES] [--session-override] [--full-reset]
>                [--no-reset] [-l] [-lt LAUNCHTIMEOUT] [-g LOG]
>                [--log-level {info,info:debug,info:info,info:warn,info:error,warn,warn:debug,warn:info,warn:warn,warn:error,error,error:debug,error:info,error:warn,error:error,debug,debug:debug,debug:info,debug:warn,debug:error}]
>                [--log-timestamp] [--local-timezone] [--log-no-colors]
>                [-G WEBHOOK] [--native-instruments-lib]
>                [--app-pkg ANDROIDPACKAGE] [--app-activity ANDROIDACTIVITY]
>                [--app-wait-package ANDROIDWAITPACKAGE]
>                [--app-wait-activity ANDROIDWAITACTIVITY]
>                [--android-coverage ANDROIDCOVERAGE] [--avd AVD]
>                [--avd-args AVDARGS]
>                [--device-ready-timeout ANDROIDDEVICEREADYTIMEOUT] [--safari]
>                [--device-name DEVICENAME] [--platform-name PLATFORMNAME]
>                [--platform-version PLATFORMVERSION]
>                [--automation-name AUTOMATIONNAME] [--browser-name BROWSERNAME]
>                [--default-device] [--force-iphone] [--force-ipad]
>                [--language LANGUAGE] [--locale LOCALE]
>                [--calendar-format CALENDARFORMAT] [--orientation ORIENTATION]
>                [--tracetemplate AUTOMATIONTRACETEMPLATEPATH] [--show-sim-log]
>                [--show-ios-log] [--nodeconfig NODECONFIG] [-ra ROBOTADDRESS]
>                [-rp ROBOTPORT] [--selendroid-port SELENDROIDPORT]
>                [--chromedriver-port CHROMEDRIVERPORT]
>                [--chromedriver-executable CHROMEDRIVEREXECUTABLE]
>                [--use-keystore] [--keystore-path KEYSTOREPATH]
>                [--keystore-password KEYSTOREPASSWORD] [--key-alias KEYALIAS]
>                [--key-password KEYPASSWORD] [--show-config] [--no-perms-check]
>                [--command-timeout DEFAULTCOMMANDTIMEOUT] [--keep-keychains]
>                [--strict-caps] [--isolate-sim-device] [--tmp TMPDIR]
>                [--trace-dir TRACEDIR] [--intent-action INTENTACTION]
>                [--intent-category INTENTCATEGORY] [--intent-flags INTENTFLAGS]
>                [--intent-args OPTIONALINTENTARGUMENTS]
>                
> 
> 
> Node Server Process Ended

But when I try to run with normal sdk emulator it runs well. 
Whether the appium supports the additional emulator? if so how to overcome this problem?

**Comment by amedvedjev** [comment]
you need to start Genymotion emulator manually OR in your code. in code you can start Genymotion emulator with any parameter needed (e.g. start specific device installed with Genymotion). Then in appium you will pass device name of needed emulator. you may see it if manually start your Genymotion needed device and run "adb -devices". normally it is look like "some_ip:port".

**Comment by ashokkumarg** [comment]
Hi amedvedjev Thank you very much for your comment. 

Since am starting the appium in Pre-launch mode I don't need to touch the coding part right. Because in the normal sdk emulator the pre-launch mode is working well and good.

Let me attach the appium settings:

Here in arguments I have passed the "some_ip:port" as parameter. 
Even I tried with the Launch AVD name too but still it is giving the same error.

![appium](https://cloud.githubusercontent.com/assets/7566850/6520166/171b8c60-c3e6-11e4-8e72-d10512addbd6.png)

I think some argument value should be passed in that column. What it will be?

**Comment by ashokkumarg** [comment]
@jlipps Can you help me over this?

**Comment by jlipps** [comment]
either a string or an array of strings. if it's a string we turn it into an array, splitting on space.

**Comment by ashokkumarg** [comment]
@jlipps I still couldn't get yet. I don't know what is the parameter here?

**Comment by amedvedjev** [comment]
all you need is DISABLE "Launch AVD" and try again.

BUT i suggest do not start manually Genymotion but in code instead e.g. with Java and on MAC machine:

public void launchEmulator(String deviceName) throws IOException {
        CommandLine launchEmul = new CommandLine("/Applications/Genymotion.app/Contents/MacOS/player");
        launchEmul.addArgument("--vm-name");
        launchEmul.addArgument("\""+deviceName+"\"");

        executor.setExitValue(1);
        executor.execute(launchEmul, resultHandler);
        sleep(40);
    }

**Comment by ashokkumarg** [comment]
@amedvedjev

When I used the above code, I have error on the last two lines

executor.setExitValue(1); **(casting problem)**
executor.execute(launchEmul, resultHandler); **(What is a resultHandler here, did you handled as a separate class.)**

**Comment by amedvedjev** [comment]
add variables in parent class. updated example.

**Comment by ashokkumarg** [comment]
As you said I have made the changes in my code.

For device name whether I need to give the  "some_ip:port" or the Virtual box device name.

**My virtual device box:**

![1](https://cloud.githubusercontent.com/assets/7566850/6572553/1635074e-c739-11e4-8f7b-4fc6fc4e1e38.png)


When I try to run with the device name am getting an error like this

![2](https://cloud.githubusercontent.com/assets/7566850/6572590/4ca46a36-c739-11e4-8981-451542b951b2.png)

The code I have used is

public static void main(String[] args) throws InterruptedException, ExecuteException, IOException {
		// TODO Auto-generated method stub
		System.out.println("SetUp is started");
		
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(CapabilityType.BROWSER_NAME, "");

		DefaultExecutor executor = new DefaultExecutor();
		DefaultExecuteResultHandler resultHandler = new DefaultExecuteResultHandler();
						
		CommandLine launchEmul = new CommandLine("C:/Program Files/Genymobile/Genymotion/player");
		launchEmul.addArgument("--vm-name");
		launchEmul.addArgument("\""+deviceName+"\"");
		executor.setExitValue(1);
		executor.execute(launchEmul, resultHandler);
		Thread.sleep(40);

		capabilities.setCapability("platformVersion", "4.3");
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability("app","D:/SOFTWARES/Apks/GOA.apk");

		driver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
		System.out.println("SetUp is successful and Appium Driver is launched successfully");
	
	}

**Comment by ashokkumarg** [comment]
@amedvedjev 
Thank you. It works well and resolved my issue :+1:
