### ISSUE TITLE
Restart instruments if AUT does not start

### ISSUE THREAD

**Issue by paymand** [appium/appium#4653]
Sometimes AUT doesn't start, instead we end up in **Springboard** (home screen of iOS)!
See the interesting part of the log when this happens: https://gist.github.com/paymand/cc4db3b418999dbfee6b
So as you see, the instruments hasn't crashed, but totally fails to start AUT and ``au.mainApp().getTreeForXML()`` got a dump of ``SpringBoard``.

So I tried with the following approach:
```python
    if self.driver.execute_script("au.mainApp()").text != "Opera Mini":
    if retry < 2:
        retry += 1
        self.log("'Opera Mini' did not start, retrying #" + str(retry))
        self.driver.quit()
        self.start(retry)
    else:
        raise Exception("Failed to start 'Opera Mini' app")
```
Here I check if the AUT was successfully started, otherwise I try restarting a couple of times before giving up. This has worked for me so far and now I get much more stable results.
We also have a similar thing in @bootstraponline's ruby test framework: restart the test session on failure up to 3 times.
I suggest adding a similar work around in the Appium server itself. There's no reason to continue automation if there's no app or main window

**Comment by imurchie** [comment]
This sounds like a good idea to me. Adding to the next milestone so it gets looked at.

**Comment by bootstraponline** [comment]
:+1:

**Comment by jlipps** [comment]
@paymand have you tried using the `waitForAppScript` capability? it's designed so you can set custom logic for determining that your app has launched. would it work here?

**Comment by paymand** [comment]
What happens in the script and hence ``waitForAppLaunched`` fails? Do we try to restart the session/app?

**Comment by jlipps** [comment]
Yeah I think we re-run the whole instruments flow

**Comment by paymand** [comment]
In that case it should totally work :)
Closing this issue...
