### ISSUE TITLE
Tool Tip handling in the Android App

### ISSUE THREAD

**Issue by kiransweng** [appium/appium#4654]
Hi Team,

In our Android App , it will show tool tips in the few screens whenever we launch or navigate to particular screen , during this situation Android can't recognize / extract XML for identification. In this situation , UIAutomatorView also throwing XML can't extract. Please see the attached screenshot.

Please guide me handle this seamlessly.

Regards,
Kiran

**Comment by kiransweng** [comment]
Attached screenshot

**Comment by kiransweng** [comment]
Unable to attach screenshot here

**Comment by 0x1mason** [comment]
Can you upload it somewhere?

**Comment by kiransweng** [comment]
@ mason:
Thanks for taking care this.
I have uploaded screenshots to www.box.com , you can access below public links to see screenshots.
https://app.box.com/s/340e8tjop67ddpawdp9ac8ru4j75dqdk

https://app.box.com/s/xh84wpmd6lrcscze4330vmsrfplrtqxf

Regards,
Kiran

**Comment by kiransweng** [comment]
@0x1mason :
Do you have any update on this?

**Comment by kiransweng** [comment]
@0x1mason: Do you have any thoughts on this?

**Comment by 0x1mason** [comment]
No, I haven't had a chance to look at this yet. It might take a few days. Sorry for the inconvenience .You can also try asking the community on discuss.appium.io.

**Comment by kiransweng** [comment]
@0x1mason: Thanks for update , will initiate discussion on discuss.appium.io

**Comment by kiransweng** [comment]
@0x1mason : Just curious to know , do you have any update or suggestion on this?

**Comment by kiransweng** [comment]
Team, Can anyone support me in this. This is directly related to App control (Tool Tip) , Does the Appium has capability to handle this?

**Comment by moizjv** [comment]
@kiransweng interesting @bootstraponline @jlipps  any ideas?

**Comment by moizjv** [comment]
@kiransweng so what is happening i dont understand do you want to check if tooltip is present or want to ignore and continue with the test

**Comment by bootstraponline** [comment]
uiautomator relies on the android accessibility apis for the ability to identify text and elements on screen. There are certain elements that can't be automated with uiautomator (such as toast notifications). This type of tooltip doesn't have a content description which is why uiautomator can't see it in uiautomatorviewer. As a result, it's unlikely that appium can automate it. You may have some success by trying selendroid which can sometimes extract more information than uiautomator from widgets that aren't accessibility friendly.

**Comment by sebv** [comment]
It's probably not possible, but moving it to feature for investigation.
