### ISSUE TITLE
Arc crashes after "page" with huge amounts of data

### ISSUE THREAD

**Issue by shermaneric** [appium/appium#4657]
Appium:  1.3.5
iOS Simulator (iOS 8)
Steps to Reproduce:
1. I start up arc for the iOS simulator with my app under test.
2. If I type "page" through each window I navigate to, all is well.
3. If I click through several windows and then navigate to a screen with text heavy information..
4. And then I type "page", Instruments will crash.

You can find the gist here:
https://gist.github.com/shermaneric/fb39d0c65a9e58d9a7f7

Let me know if I can provide any more information.

Thanks in advance!
Eric

**Comment by bootstraponline** [comment]
Thanks for reporting. I've encountered this issue as well. Instruments appears to crash when dumping the page source on complex apps. Hopefully by sending the response in chunks or some other solution, the crash can be resolved in the appium server.
