### ISSUE TITLE
unable to install appium using npm v2.6.1 and node v0.12.0

### ISSUE THREAD

**Issue by spatchamatla** [appium/appium#4659]
npm ERR! git clone git://github.com/vojtajina/traceur-compiler Cloning into bare repository '/Users/spatchamatla/.npm/_git-remotes/git-github-com-vojtajina-traceur-compiler-f4c43c65'...
npm ERR! git clone git://github.com/vojtajina/traceur-compiler fatal: read error: Operation timed out
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "-g" "install" "appium"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.1
npm ERR! code 128

**Comment by 0x1mason** [comment]
Please see https://github.com/appium/appium/issues/4543

**Comment by spatchamatla** [comment]
i made the changes as per #4543 and im able to install appium v1.3.6. Thank you.
