### ISSUE TITLE
[ios] Swipe action do not work on my xcode simulator

### ISSUE THREAD

**Issue by xudafeng** [appium/appium#4664]
Swipe action not wrok, someone met the same problem?

This is my implement code:
```js
.performTouchAction((new TouchAction())
      .press({x: 20, y: 200})
      .wait({ms: 500})
      .moveTo({x: 200, y: 200})
      .release())
```

- appium 1.3.4
- ios 
- simulator iphone5s

**Comment by jlipps** [comment]
gestures don't work in many views on the ios simulator because Apple broke gesture recognition on the simulator. the only alternative is to use "mobile: scroll" if you're in a list or table view.

**Comment by xudafeng** [comment]
@jlipps I see,thx.

**Comment by xudafeng** [comment]
@lihuazhang

**Comment by xudafeng** [comment]
@lihuazhang for this.
