### ISSUE TITLE
info: [debug] Checking whether adb is present error: Unhandled error: Error: ENOENT, no such file or directory '/home/vinod/adt-bundle-linux/sdk/build-tools'     at Error (native)

### ISSUE THREAD

**Issue by vinodakumarsr** [appium/appium#4665]
Hi am using ubuntu 14.04 LTS when i run my code am getting this below error in terminal  pls help me

vinod@vinod-HP-540:~$ appium
info: Welcome to Appium v1.3.6 (REV 004f52f249d3513809e7d0734d9205d1fec19f8e)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"4.4.4","deviceName":"ZX1B338NH2","app":"/home/vinod/SanDiskMemoryZone-com.sandisk.mz-92-v2.1.2.apk","platformName":"Android"}}
info: Client User-Agent string: Python-urllib/2.7
info: [debug] No appActivity desired capability or server param. Parsing from apk.
info: [debug] No appPackage desired capability or server param. Parsing from apk.
info: [debug] Using local app from desired caps: /home/vinod/SanDiskMemoryZone-com.sandisk.mz-92-v2.1.2.apk
info: [debug] Creating new appium session 83b0df5a-eeaa-4b92-a3bb-cd7bae333d3f
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.8.0_40
info: [debug] Checking whether adb is present
error: Unhandled error: Error: ENOENT, no such file or directory '/home/vinod/adt-bundle-linux/sdk/build-tools'
    at Error (native)
    at Object.fs.readdirSync (fs.js:765:18)
    at exports.getDirectories (/home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/appium-adb/lib/helpers.js:100:18)
    at ADB.checkSdkBinaryPresent (/home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:97:25)
    at ADB.checkAdbPresent (/home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:134:8)
    at Function.ADB.createADB (/home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:73:7)
    at androidCommon.initAdb (/home/vinod/.linuxbrew/lib/node_modules/appium/lib/devices/android/android-common.js:1059:9)
    at /home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/async/lib/async.js:610:21
    at /home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/async/lib/async.js:249:17
    at iterate (/home/vinod/.linuxbrew/lib/node_modules/appium/node_modules/async/lib/async.js:149:13) context: [POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"4.4.4","deviceName":"ZX1B338NH2","app":"/home/vinod/SanDiskMemoryZone-com.sandisk.mz-92-v2.1.2.apk","platformName":"Android"}}]

**Comment by 0x1mason** [comment]
Does that directory exist? What's ANDROID_HOME set as?

**Comment by 0x1mason** [comment]
Add the adb dir to your path.

**Comment by vinodakumarsr** [comment]
Android home set like this 
ANDROID_HOME=/home/vinod/adt-bundle-linux
export ANDROID_HOME
PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export PATH

**Comment by vinodakumarsr** [comment]
this is what i set in my .bashrc

export JAVA_HOME=/usr/lib/java/jdk1.8.0_40
set PATH="$PATH:$JAVA_HOME/bin"

export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"

ANDROID_HOME=/home/vinod/adt-bundle-linux
export ANDROID_HOME

PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export PATH

export PATH="${PATH}:/home/vinod/adt-bundle-linux/tools/"
export PATH="${PATH}:/home/vinod/adt-bundle-linux/platform-tools/"

**Comment by 0x1mason** [comment]
Try `ln -s /home/vinod/adt-bundle-linux /home/vinod/adt-bundle-linux/sdk` and then run Appium.

**Comment by vinodakumarsr** [comment]
should i remove any lines from .bashrc file?
and where to add the "ln -s /home/vinod/adt-bundle-linux /home/vinod/adt-bundle-linux/sdk"  line?

1. i pasted the above line in terminal and ran appium after that also getting same issue
info: [debug] Checking whether adb is present
error: Unhandled error: Error: ENOENT, no such file or directory '/home/vinod/adt-bundle-linux/build-tools'
    at Error (native)

2. i added the "ln -s /home/vinod/adt-bundle-linux /home/vinod/adt-bundle-linux/sdk" line in .bashrc file and tried but same issue observed

**Comment by 0x1mason** [comment]
Does `/home/vinod/adt-bundle-linux/build-tools` exist?

**Comment by 0x1mason** [comment]
If not, where is your Android SDK build-tools directory?

**Comment by vinodakumarsr** [comment]
sorry sir, now it is working fine, it was a simple mistake i added a wrong path now i corrected


Thanks for ur help and sorry if i wasted ur precious time

**Comment by 0x1mason** [comment]
Glad you got it working. :)

**Comment by vinodakumarsr** [comment]
Hi i have a question pls help
how to write code in python for this below scenario
i want to copy 1000 files and i dont know how much time it takes, so i want to say webdriver to wait until my copy process gets completed please help me

**Comment by 0x1mason** [comment]
Please direct implementation questions to https://discuss.appium.io.
