### ISSUE TITLE
Fork ios WebKit debug proxy

### ISSUE THREAD

**Issue by 0x1mason** [appium/appium#4668]
@jlipps @sebv @imurchie IWDP looks to be abandoned and there are some good PRs sitting unmerged. We should fork, call ours "Mobile Safari Debug Proxy" and pull in the PRs and the branch belonging to @jchuong ([eg, the thread here](https://github.com/google/ios-webkit-debug-proxy/issues/79)) who has made some fixes that sound like they could help with the issues we see.

**Comment by 0x1mason** [comment]
@bootstraponline forgot to add you

**Comment by bootstraponline** [comment]
It's worth making an issue on the upstream repo to see if it's really abandoned or not.

**Comment by jlipps** [comment]
I agree with those points

**Comment by 0x1mason** [comment]
I saw one of the PRs where someone had said they were trying to contact the
owner. Worth another go. Assuming we can't, then fork.

**Comment by 0x1mason** [comment]
https://github.com/google/ios-webkit-debug-proxy/issues/93

**Comment by 0x1mason** [comment]
It's one of those questions to which one cannot answer "yes". Silence is our affirmation.

**Comment by 0x1mason** [comment]
@jlipps which points? Wait for the sound of silence?

**Comment by bootstraponline** [comment]
To clarify I'm fine with forking now, just want to make sure we're making an attempt to contact upstream. I think forking with no attempted contact is not a desired outcome.

**Comment by 0x1mason** [comment]
Good point.  Agree.

**Comment by wrightt** [comment]
Hi, I'm wrightt, the IWDP lead.

I've been swamped with other projects these past couple months, but I'd like to revive IWDP if possible.  I can work on the IWDP a couple days this month, then more (~one week)/in April.

Aside from critical bug fixes, I think the best long-term solution is for me to refactor the IWDP code to replace the low-level iOS calls (prone to plist/version/etc breakages) with subprocess calls to
https://github.com/libimobiledevice/libimobiledevice/blob/master/tools/idevicedebugserverproxy.c
This'd limit the IWDP code to the HTTP layer, which'll be more stable and easier to support.

I can start the above refactor or fix critical bugs.  Which sounds best to you?

**Comment by 0x1mason** [comment]
@wrightt Great to hear you're still around! Bug fixes would probably be the most helpful for our users in the short term.

**Comment by 0x1mason** [comment]
@wrightt If you need help with fixing bugs, let us know. This is a critical
component for us.

**Comment by jwagun** [comment]
@wrightt Appreciate for your contribution!
