### ISSUE TITLE
An error occurred while executing user supplied JavaScript on TYPE

### ISSUE THREAD

**Issue by jimberley** [appium/appium#4670]
Here's a full log:

https://gist.github.com/jimberley/79e04b8e3f1373e4bc06

It looks send_keys is failing during evaluation of the string to be sent. I've gotten around this problem by using the selenium command: element.native.type "string", but would prefer this be fixed so that we can use element.send_keys "string" again. :) 

Please, let me how I can help.

7552015-02-19 19:58:51:344 - info: [debug] Pushing command to appium work queue: "au.capture('screenshot3411782e-7819-468d-84dc-ca5091c9cbab')"
7562015-02-19 19:58:51:344 - info: [debug] Sending command to instruments: au.capture('screenshot3411782e-7819-468d-84dc-ca5091c9cbab')
7572015-02-19 19:58:51:367 - info: [debug] [INST] 2015-02-19 19:58:50 +0000 Error: VerboseError: target.frontMostApp().keyboard() failed to tap 'u'
7582015-02-19 19:58:51:476 - info: [debug] [INST] 2015-02-19 19:58:50 +0000 Error: Error during eval: typeString@[native code]
759 sendKeysToActiveElement@file:///Users/chef/appium/1F7D9403-53E2-428D-A606-D43836F6B96D/bootstrap-50949661197fe2cc.js:1266:32
760setValueByType@file:///Users/chef/appium/1F7D9403-53E2-428D-A606-D43836F6B96D/bootstrap-50949661197fe2cc.js:1964:38

**Comment by imurchie** [comment]
When this runs does the keyboard open?

**Comment by jimberley** [comment]
It doesn't actually. Not that I am able to see, at least.

**Comment by imurchie** [comment]
Alright. That is the problem. First, does the keyboard open ever? If you manually click on a text field does the soft keyboard come up?

**Comment by jimberley** [comment]
Yes. The soft keyboard comes up if you manually click the input fields.

**Comment by imurchie** [comment]
Ok. There is an issue wherein iOS 7.x simulators in Xcode 6.x are flakey with regard to opening the keyboard. The fix, unfortunately, came in Appium 1.3.5 (see [here](https://github.com/appium/appium-uiauto/commit/e4fabfb22c3fb650d631a41da888c7b9e0735b16)). You can either upgrade the server, or you can upgrade the `appium-uiauto` to at least 1.10.0 (Appium 1.3.4 uses `appium-uiauto` 1.9.0).

**Comment by jimberley** [comment]
Here's the bad news, my local env is using 1.3.5, and, this happens when I use SAUCELabs, which uses 1.3.5 as well.

**Comment by imurchie** [comment]
Really? The log you provided is from 1.3.4.

**Comment by imurchie** [comment]
If you have this problem on Saucelabs, can you provide a link to a job there?

**Comment by jimberley** [comment]
Shit. I sent the wrong logs. Alright. Let me see what I can cook up. Thank you for your help and patience.

**Comment by jimberley** [comment]
Okay. I cannot run my shit on 1.3.5 right now due to this:

https://github.com/appium/appium/pull/4556

I'll have to get back to you. Thank you again.

**Comment by imurchie** [comment]
Alright. Running from source will get you that fix now, hopefully.

**Comment by jlipps** [comment]
You don't want to run on 1.3.5, it's not supported on Sauce. 1.3.6 is, however, and has the fix for the keyboard.

**Comment by jimberley** [comment]
Neat! Thank you, @jlipps. I'll try upping my version for my SAUCELabs runs.

**Comment by 0x1mason** [comment]
@jimberley Can you email me at eric @ saucelabs.com please? We'd like to have you verify the #4556 fix on sauce.

**Comment by sebv** [comment]
Is this fix? Seem to remember we did some work on this kind of issues.

**Comment by sebv** [comment]
Closing, may be reopened if needed.
