### ISSUE TITLE
A new session could not be created

### ISSUE THREAD

**Issue by bchand1748** [appium/appium#4675]
I am trying to automate a Hybrid App in Android. The code only works half of the time. The code switches to the web view and all the commands are well received by appium. 
The other half I get an exception that a new session could not be created. I have stopped, restarted the server several times but the issue is consistent. Attached is the log : 

> Killed Node Server.
> Node Server Process Ended
> Starting Node Server
> info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"app":"C:\\Users\\bkbc011\\Desktop\\apk\\bk-mobile-native-android.apk","address":"127.0.0.1","fullReset":true,"logNoColors":true,"platformName":"Android","platformVersion":"19","automationName":"Selendroid"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Users\\bkbc011\\Desktop\\apk\\bk-mobile-native-android.apk","platformVersion":"4.4.2","automationName":"Selendroid","platformName":"Android","deviceName":"Android"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from desired caps: C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk
> info: [debug] Creating new appium session 69e54ac0-eb22-4ade-9648-88b6cd5710a5
> info: [debug] Starting selendroid server
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_31
> info: [debug] Checking whether selendroid is built yet
> info: [debug] Selendroid server exists!
> info: [debug] Using fast reset? false
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device 0506931ad84a9331
> info: [debug] Setting device id to 0506931ad84a9331
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 wait-for-device
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe
> info: [debug] Checking if has internet permission from manifest.
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe dump badging C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk
> info: [debug] Parsing package and activity from app manifest
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe
> info: [debug] Extracting package and launch activity from manifest.
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe dump badging C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk
> info: [debug] badging package: com.emn8.mobilem8.nativeapp.bk
> info: [debug] badging act: com.testfairy.sdk.activities.WelcomeActivity
> info: [debug] Parsed package and activity are: com.emn8.mobilem8.nativeapp.bk/com.testfairy.sdk.activities.WelcomeActivity
> info: [debug] Rebuilt selendroid server already exists, no need to rebuild it with a new manifest
> info: [debug] Checking signed status of C:\Users\bkbc011\AppData\Local\Temp\selendroid.com.emn8.mobilem8.nativeapp.bk.apk
> info: [debug] Checking app cert for C:\Users\bkbc011\AppData\Local\Temp\selendroid.com.emn8.mobilem8.nativeapp.bk.apk.
> info: [debug] executing cmd: java -jar C:\Users\bkbc011\Desktop\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar C:\Users\bkbc011\AppData\Local\Temp\selendroid.com.emn8.mobilem8.nativeapp.bk.apk
> info: [debug] Checking signed status of C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk
> info: [debug] Checking app cert for C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk.
> info: [debug] executing cmd: java -jar C:\Users\bkbc011\Desktop\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Users\bkbc011\AppData\Local\Temp\selendroid.com.emn8.mobilem8.nativeapp.bk.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\zipalign.exe -f 4 C:\Users\bkbc011\AppData\Local\Temp\selendroid.com.emn8.mobilem8.nativeapp.bk.apk C:\Users\bkbc011\AppData\Local\Temp\appium11529-2188-1sac73y.tmp
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\zipalign.exe -f 4 C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk C:\Users\bkbc011\AppData\Local\Temp\appium11529-2188-10biz75.tmp
> info: [debug] Rebuilt selendroid apk does not exist, uninstalling any instances of it on device to make way for new one
> info: [debug] Uninstalling com.emn8.mobilem8.nativeapp.bk.selendroid
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "am force-stop com.emn8.mobilem8.nativeapp.bk.selendroid"
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 uninstall com.emn8.mobilem8.nativeapp.bk.selendroid
> info: [debug] App was uninstalled
> info: [debug] Getting install status for com.emn8.mobilem8.nativeapp.bk.selendroid
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 21
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "pm list packages -3 com.emn8.mobilem8.nativeapp.bk.selendroid"
> info: [debug] App is not installed
> info: [debug] Rebuilt selendroid is not installed, installing it
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 install -r "C:\Users\bkbc011\AppData\Local\Temp\selendroid.com.emn8.mobilem8.nativeapp.bk.apk"
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] java -jar "C:\Users\bkbc011\Desktop\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk" "C:\Users\bkbc011\AppData\Local\Temp\com.emn8.mobilem8.nativeapp.bk" en
> info: [debug] No strings.xml for language 'en', getting default strings.xml
> info: [debug] java -jar "C:\Users\bkbc011\Desktop\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk" "C:\Users\bkbc011\AppData\Local\Temp\com.emn8.mobilem8.nativeapp.bk"
> info: [debug] Uninstalling com.emn8.mobilem8.nativeapp.bk
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "am force-stop com.emn8.mobilem8.nativeapp.bk"
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 uninstall com.emn8.mobilem8.nativeapp.bk
> info: [debug] App was uninstalled
> info: [debug] Checking app cert for C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk.
> info: [debug] executing cmd: java -jar C:\Users\bkbc011\Desktop\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\zipalign.exe -f 4 C:\Users\bkbc011\Desktop\apk\bk-mobile-native-android.apk C:\Users\bkbc011\AppData\Local\Temp\appium11529-2188-10e38t2.tmp
> info: [debug] MD5 for app is 5f5940ce294153a4f3f673b5240adc4d
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "ls /data/local/tmp/5f5940ce294153a4f3f673b5240adc4d.apk"
> info: [debug] Getting install status for com.emn8.mobilem8.nativeapp.bk
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 21
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "pm list packages -3 com.emn8.mobilem8.nativeapp.bk"
> info: [debug] App is not installed
> info: Installing App
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "mkdir -p /data/local/tmp/"
> info: [debug] Removing any old apks
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "ls /data/local/tmp/*.apk"
> info: [debug] Found an apk we want to keep at /data/local/tmp/5f5940ce294153a4f3f673b5240adc4d.apk
> info: [debug] Couldn't find any apks to remove
> info: [debug] Uninstalling com.emn8.mobilem8.nativeapp.bk
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "am force-stop com.emn8.mobilem8.nativeapp.bk"
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 uninstall com.emn8.mobilem8.nativeapp.bk
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "pm install -r /data/local/tmp/5f5940ce294153a4f3f673b5240adc4d.apk"
> info: [debug] Forwarding system:8080 to device:8080
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 forward tcp:8080 tcp:8080
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 install "C:\Users\bkbc011\Desktop\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 install "C:\Users\bkbc011\Desktop\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "dumpsys window"
> info: Unlocking screen
> info: [debug] Screen is locked, trying to unlock
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 21
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] Cleaning up appium session
> error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
> info: [debug] Error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
>     at null.<anonymous> (C:\Users\bkbc011\Desktop\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:1130:21)
>     at null.<anonymous> (C:\Users\bkbc011\Desktop\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:172:9)
>     at ChildProcess.exithandler (child_process.js:635:7)
>     at ChildProcess.EventEmitter.emit (events.js:98:17)
>     at maybeClose (child_process.js:743:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity)","origValue":"Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 36828.524 ms - 346

**Comment by tarunsujit** [comment]
@bchand1748 I am curious to know why is this capability is passed "automationName":"Selendroid". 
Though you are device is API Level 21

**Comment by bchand1748** [comment]
I get the following exception while using appium thus I decided to use it in Selendroid : 

An unknown server-side error occurred while processing the command. (Original error: Did not get session redirect from Chromedriver) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout

**Comment by bchand1748** [comment]
Closing this issue as the code seems to be working after unlocking the phone.
