### ISSUE TITLE
Error on Automating iOS Hybrid app: We're in the middle of processing a remote debugger command, waiting to run next command until done

### ISSUE THREAD

**Issue by bhawani2008** [appium/appium#4682]
Hello,
I am trying to automate an iOS hybrid app using Appium-1.3.4 and Protractor. 
I started: ios_webkit_debug_proxy -c b1863f83f4d9c9ea7ee1ac2f2a8a8e478dd3aa38:27753

When I run the protractor tests, gets an infinite error : Please find the Appium error logs below:
Kindly Advise......

info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"app":"/Users/qualcomm/Desktop/10MAR15Builds/Archive/AbbVie Care Global.app","ipa":"/Users/qualcomm/Desktop/10MAR15Builds/Archive/AbbVie Care Global.ipa","udid":"b1863f83f4d9c9ea7ee1ac2f2a8a8e478dd3aa38"}
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"iOS","appium-version":"1.3.4","platformName":"iOS","platformVersion":7.1,"deviceName":"iPhone","autoWebview":true,"count":1}}
info: Client User-Agent string: undefined
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : appium-version, count
info: [debug] Using local app from command line: /Users/qualcomm/Desktop/10MAR15Builds/Archive/AbbVie Care Global.app
info: [debug] Creating new appium session cf72104e-7ba6-4079-a9c5-3e5dfe1c0c82
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.1
info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/qualcomm/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. D...ot manually modify!
info: [debug] Dynamic bootstrap path: /Users/qualcomm/Library/Application Support/appium/bootstrap/bootstrap-d0f21a5b61bb08af.js
info: [debug] Reusing dynamic bootstrap: /Users/qualcomm/Library/Application Support/appium/bootstrap/bootstrap-d0f21a5b61bb08af.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone","platformVersion":7.1}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone (7.1 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] On a real device; cannot clean device state
info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole
info: [debug] Not pre-launching simulator
info: [debug] Creating iDevice object with udid b1863f83f4d9c9ea7ee1ac2f2a8a8e478dd3aa38
info: [debug] Checking app install status using: /usr/local/lib/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id b1863f83f4d9c9ea7ee1ac2f2a8a8e478dd3aa38 --bundle com.span.sampleTest
info: [debug] App is installed.
info: [debug] fullReset not requested. No need to install.
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID b1863f83f4d9c9ea7ee1ac2f2a8a8e478dd3aa38
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w b1863f83f4d9c9ea7ee1ac2f2a8a8e478dd3aa38 com.span.sampleTest -e UIASCRIPT "/Users/qualcomm/Library/Application Support/appium/bootstrap/bootstrap-d0f21a5b61bb08af.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST STDERR] 2015-03-10 14:22:42.231 instruments[489:7104] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: Instruments is ready to receive commands
info: [debug] Instruments launched. Starting poll loop for new commands.
info: [debug] Setting bootstrap config keys/values
info: [debug] Pushing command to appium work queue: "target = $.target();\nau = $;\n$.isVerbose = true;\n"
info: [debug] Socket data received (2 bytes)
info: [debug] Socket data being routed.
info: [debug] Sending command to instruments: target = $.target();
au = $;
$.isVerbose = true;

info: [debug] [INST] 2015-03-10 08:51:47 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-03-10 08:51:48 +0000 Debug: responding with:
       2015-03-10 08:51:48 +0000 Debug: Running system command #1: /usr/local/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":true}...
info: [debug] Socket data received (27 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":true}
info: [debug] Setting initial orientation to PORTRAIT
info: [debug] Pushing command to appium work queue: "au.setScreenOrientation('PORTRAIT')"
info: [debug] Sending command to instruments: au.setScreenOrientation('PORTRAIT')
info: [debug] [INST] 2015-03-10 08:51:49 +0000 Debug: Got new command 1 from instruments: au.setScreenOrientation('PORTRAIT')
       2015-03-10 08:51:49 +0000 Debug: evaluating au.setScreenOrientation('PORTRAIT')
info: [debug] [INST] 2015-03-10 08:51:49 +0000 Debug: target.setDeviceOrientation("1")
info: [debug] [INST] 2015-03-10 08:51:50 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-03-10 08:51:50 +0000 Debug: responding with:
info: [debug] [INST] 2015-03-10 08:51:50 +0000 Debug: Running system command #2: /usr/local/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"PORTRAIT"}...
info: [debug] Socket data received (33 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":"PORTRAIT"}
info: [debug] Setting auto webview
info: [debug] Navigating to most recently opened webview
info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
info: [debug] Picking webview WEBVIEW_2
info: [debug] Attempting to set context to 'WEBVIEW_2'
info: [debug] [REMOTE] Debugger web socket connected to url [ws://localhost:27753/devtools/page/2]
info: [debug] [REMOTE] Unregistering from page readiness notifications
info: [debug] Waiting for app source to contain elements
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done

**Comment by bhawani2008** [comment]
Hi,
Any Suggestions??

**Comment by sebv** [comment]
Try with this script: https://github.com/appium/appium/blob/master/bin/ios-webkit-debug-proxy-launcher.js

**Comment by sebv** [comment]
Closing please try solution above (and sorry for the late response), may be reopened if needed.

**Comment by glorylo** [comment]
this error still occurs and I have seen this pretty regularly.  I have seen this on 1.4.8 for hybrid.  I am not sure if this is the real culprit but I see it more often when going from webview->native->webview.

please reopen.

```
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done


info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done


info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done


info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done


info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done


info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done


info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"c6622f8f-63e6-4db7-bf40-d1a143dcdddc"}
info: <-- GET /wd/hub/status 200 0.957 ms - 178 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"c6622f8f-63e6-4db7-bf40-d1a143dcdddc"}
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done


info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done


info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done


info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done


info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [IOS_SYSLOG_ROW ] Aug  7 18:58:19 iPhone-5S-4-Gold kernel[0] <Notice>: 4556904.698129 wlan0.A[201807] AppleBCMWLANConfigManager::configureRoamingProfile(): Received new roaming profile 3 (was 3, flag=0x0)
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done


info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done


info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
```
