### ISSUE TITLE
Android app restarts automatically after performing a button click 

### ISSUE THREAD

**Issue by rakeshramesh** [appium/appium#4683]
- I executed a tap even on the button using the following command 
  find_element(:xpath , ''path').click
- After executing the above statement new resultant screen is displayed  and app restarts automatically.
- The same functionality works when I perform this action manually .

Logs - 

info: [debug] Pushing command to appium work queue: ["find",{"strategy":"xpath","selector":"//android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[1]","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[1]","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding //android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[1] using XPATH with the contextId:  multiple: false

info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CLASS=android.widget.Button, INSTANCE=0]

info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"ELEMENT":"47"},"status":0}

info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"47"},"sessionId":"c4f517f1-be2c-4799-b859-e71797ad2028"}
info: <-- POST /wd/hub/session/c4f517f1-be2c-4799-b859-e71797ad2028/element 200 192.734 ms - 88 {"status":0,"value":{"ELEMENT":"47"},"sessionId":"c4f517f1-be2c-4799-b859-e71797ad2028"}
info: --> POST /wd/hub/session/c4f517f1-be2c-4799-b859-e71797ad2028/element/47/click {}
info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"47"}]

info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"47"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: click

info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}

info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"c4f517f1-be2c-4799-b859-e71797ad2028"}
info: <-- POST /wd/hub/session/c4f517f1-be2c-4799-b859-e71797ad2028/element/47/click 200 430.993 ms - 76 {"status":0,"value":true,"sessionId":"c4f517f1-be2c-4799-b859-e71797ad2028"}

info: --> DELETE /wd/hub/session/c4f517f1-be2c-4799-b859-e71797ad2028 {}

info: Shutting down appium session
info: [debug] Pressing the HOME button
info: [debug] executing cmd: /Users/rameshrakesh/Library/Android/sdk/platform-tools/adb -s e0de6482037f6e82 shell "input keyevent 3"

info: [debug] Stopping logcat capture

info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}

info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 94.256
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] UiAutomator shut down normally
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"c4f517f1-be2c-4799-b859-e71797ad2028"}
info: <-- DELETE /wd/hub/session/c4f517f1-be2c-4799-b859-e71797ad2028 200 952.806 ms - 76 {"status":0,"value":null,"sessionId":"c4f517f1-be2c-4799-b859-e71797ad2028"}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}
info: <-- GET /wd/hub/status 200 0.919 ms - 104 {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

**Comment by sebv** [comment]
`DELETE session` was called, so the session was ended. Not sure what restarted, this is not apparent in the log.

**Comment by jlipps** [comment]
wonder if the client encountered an exception in the test code and it triggered the teardown logic

**Comment by sebv** [comment]
Closing, old issue (and sorry for the late response), may be reopened if needed.
