### ISSUE TITLE
Real Device Safari Error: Could not navigate to webview; there aren't any! 

### ISSUE THREAD

**Issue by kchuykov** [appium/appium#4691]
I have about 15% chance of getting an error on Safari real Device, other 85% everything works fine. 
Appium seem to die completely after the error.
 
I am running
Appium 1.3.6
iphone 5 ios 8.1
xcode 6.1
os 10.9
Running a proxy with luncher from appium/bin

log:
info: [debug] Socket data received (8164 bytes)
info: [debug] Socket data received (8190 bytes)
info: [debug] Socket data received (3691 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"Safari","label":"Safari","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":20,"width":320,"height":548},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"vali
info: [debug] Waiting for 4000 ms before navigating to view.
info: [debug] Navigating to most recently opened webview
info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
warn: Could not find any webviews yet, refreshing/retrying
info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
...## the 2 lines above repeat about 200 times
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not navigate to webview; there aren't any!
info: [debug] Error: Could not navigate to webview; there aren't any!
    at null.<anonymous> (/Users/admin/awetest/node_modules/appium/lib/devices/ios/ios.js:1659:14)
    at /Users/admin/awetest/node_modules/appium/lib/devices/ios/ios.js:1551:5
    at null.<anonymous> (/Users/admin/awetest/node_modules/appium/lib/devices/ios/ios.js:1538:5)
    at null.<anonymous> (/Users/admin/awetest/node_modules/appium/lib/devices/ios/ios-hybrid.js:69:5)
    at null.<anonymous> (/Users/admin/awetest/node_modules/appium/lib/devices/ios/webkit-remote-debugger.js:88:5)
    at /Users/admin/awetest/node_modules/appium/node_modules/underscore/underscore.js:883:21
    at IncomingMessage.<anonymous> (/Users/admin/awetest/node_modules/appium/lib/devices/ios/webkit-remote-debugger.js:101:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickDomainCallback (node.js:463:13)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not navigate to webview; there aren't any!)","origValue":"Could not navigate to webview; there aren't any!"},"sessionId":null}
info: <-- POST /wd/hub/session 500 109784.335 ms - 218 
info: --> DELETE /wd/hub/session/cab33508-6414-416e-9e0e-e5f02019f9bb {}
info: <-- DELETE /wd/hub/session/cab33508-6414-416e-9e0e-e5f02019f9bb 404 1.443 ms - 40

**Comment by tarunsujit** [comment]
@kchuykov Is your SafariLauncher is a dev certified ? Create a Provisioning profile that can be used deploy SafariLauncherApp [Follow steps from here] (https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/mobile-web.md#mobile-safari-on-a-real-ios-device)

**Comment by 0x1mason** [comment]
@kchuykov Can walk thru the instructions for [Safari on iOS real devices](http://appium.io/slate/en/master/?java#automating-mobile-web-apps)?

Are you certain you've got everything configured correctly?

**Comment by kchuykov** [comment]
I was trying to use the SafariLauncher I build in xcode, I am not getting this error anymore after following your steps. Thanks

**Comment by ASYB** [comment]
Even I am getting the error after some test cases running (Almost after 95% of test cases running).

**Comment by 0x1mason** [comment]
Can you open a new issue and include your appium logs?
