### ISSUE TITLE
send_keys clears the text field before appending the new keys

### ISSUE THREAD

**Issue by yahman72** [appium/appium#4694]
I'm trying to input text into a text field that is activated(=shown) on a key-press. An example could be the dialer on Andoid 4.4. phones, when you open the phone app you see the dialer numpad and after clicking the first digit you'll also see the text field with the numbers.

I.e. I'm trying to input the text in two steps e.g. 
1) click '3' on the dialer numpad
2) input '22222'.

So far so good, I can see the operation in the log

<pre>
info: --> POST /wd/hub/session/3437e745-7a83-4a73-b921-57c464c9bb26/element/2/value...
info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"2","text":"22222","replace":false}]
</pre>

... but for some reason, appium clears the text field before appending the '22222'

<pre>
info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
</pre>

This deletes the earlier '3' **and** makes the text field disappear (because it has no text in it anymore) ---> input '22222' fails, because the text field is not visible anymore

<pre>
info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.",...
</pre>

**correction**
Instead of clearing the text field:
1) select the text field
2) go to the end of the text field (e.g. send 'CTRL+END') 
3) input the desired text

**Comment by changusmc** [comment]
@yahman72 Thanks for reporting this!! I've seen this issue in our automation and thought that this was desired behavior on Appium's part.. 

I've put in a workaround for this in our code for now.

``` Java
        File adb = new File("<full path to your adb>")
        // Replace all spaces with %s, adb doesn't accept spaces
        String input = text.replaceAll(" ", "%s");
        Runtime.getRuntime().exec(adb.getAbsolutePath() + " shell input text " + input);
```

**Comment by changusmc** [comment]
It looks like this bug has been raised in the past.

https://github.com/appium/appium/issues/3812#issuecomment-60433195

**Comment by yahman72** [comment]
yeah, that seems to be the same issue - but I'm wondering if the "with Android, there is no way to concatenate without clearing" statement there is really valid? 

IMHO the above correction proposal should work,  at least I'm able to append text like that using adb i.e.
1) <on the device: click on the text field>
2) adb shell input keyevent 123
3) adb shell input text "22222"

The above works i.e. "22222" is appended at the end of the text field.

**Comment by sebv** [comment]
Moving to feature, people should not need to rely on workaround to do that.
