### ISSUE TITLE
appium not work on Android 5

### ISSUE THREAD

**Issue by zhong88** [appium/appium#4699]
Just update my appium to 1.3.6 but it doesn't work on Android 5 yet. but the same test works well on Android 4.4. anyone else has the same issue?

updated: This is for native android app automation and through the way find element(by.id) to locate the element.
the return element is null in Android 5.0

updated2: actually when I increase the command timeout to 300 ms(default is 60 secs), the test could work. so theoretically, it works for android 5 but extremely slow compared to the performance on android 4.4.
Thanks,

**Comment by zhong88** [comment]
any one else has similar issue? I compared the running time for the same test on Android 4.4 and Android 5.0 respectively and find that it takes over 30-40 seconds to locate one element in 5.0 whereas on 4.4 it's only 1-2 seconds. I tried element id, name and path and they show similar results.

**Comment by sebv** [comment]
What device are you using exactly?  It sounds like the app or android is just slower. This kind of issue would be better reported on the discussion forum.

**Comment by zhong88** [comment]
Thank you for your reply and I would create an issue on discussion forum
soon.

we are using samsung s5 as testing machine. I did a simple test bench and
noticed that even using UIAutomator instead of Appium, the running time is
still slow. however, our app does run quite smoothly on Android 4.4, so I'm
guessing there may be some incompatibility between our app and Lollipop.


On Mon, Apr 20, 2015 at 10:37 PM, seb vincent <notifications@github.com>
wrote:

> What device are you using exactly? It sounds like the app or android is
> just slower. This kind of issue would be better reported on the discussion
> forum.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/4699#issuecomment-94644260>.
>



-- 
This email and all attachments are confidential and are intended solely for
the individual or entity to whom the email is addressed. If you believe
that you are not an intended recipient, please stop reading immediately.
Do not disclose, copy, forward, or rely on the contents in any way.  Please
notify Tile by emailing the original Tile sender and then delete or destroy
any copy of this email and its attachments.  The sender reserves and
asserts all rights to confidentiality, including all privileges that may
apply.

**Comment by sebv** [comment]
reopen if needed.
