### ISSUE TITLE
Device specificities

### ISSUE THREAD

**Issue by Fanch-** [appium/appium#4701]
I would like to know if there is a standard way to retrieve a virtual button whatever is the OS/Maker (I mean with one selector or server-side object), using KeyEvent for example (which represents only hardware buttons I think).

Ex. : if I want to take a picture, I can use sendKeyEvent(27) -hardware button- but after; if I want to click on *the picture validation button*, the layout is different between OS/Versions/Makers, so what is the best way to do it ? 

Is there an appium object which takes into account these differences and modelizes some virtual buttons ?

**Comment by 0x1mason** [comment]
@bootstraponline Any suggestions?

You should also ask the community at http://discuss.appium.io.

**Comment by 0x1mason** [comment]
If I understand your question correctly, if you have the XPath, id, etc, you can use a locator to find the button and click on it.

**Comment by Fanch-** [comment]
I'll use the appium forum next time, thank you for the link.

Yes exactly, I can access the DOM and then click on this virtual button.

I could also create an object client-side with every specific selectors linked to their device (mobile) but I think these virtual buttons could be useful for everybody, so doing something server-side can be helpful. 

This way we could call functions like  findVirtualButton("Confirm Picture", "Samsung Galaxy Note 3"),  findVirtualButton("Cancel Picture", "iPhone 4") ...

Am I right thinking that Layout for this kind of virtual buttons are fixed by Mobile Device/Version ?

**Comment by sebv** [comment]
We don't keep track of all these button in appium (yet) as far as I know, but closing, this should go to appium discuss.
