### ISSUE TITLE
Mobile: scroll not working on iOS 8.x and appium 1.3.4 

### ISSUE THREAD

**Issue by TaylorTai** [appium/appium#4705]
JavascriptExecutor js = (JavascriptExecutor) getDriver();
    HashMap<String, String> scrollObject = new HashMap<String, String>();
    scrollObject.put("direction", "down");
    js.executeScript("mobile: scroll", scrollObject);
I tried above code on native page but seemed the scroll didn't work on iOS 8.x and appium 1.3.4. Also faied in appium 1.3.6. Any help?

**Comment by tarunsujit** [comment]
@TaylorTai Also add this, 
scrollObject.put("element", ((RemoteWebElement) element).getId());
You can refer [here] (https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md)

**Comment by TaylorTai** [comment]
@tarunsujit  i tried it and still didn't work.

**Comment by tarunsujit** [comment]
I just tried in one of our testapp it is working as expected in 1.3.6. Can you post your logs?

**Comment by TaylorTai** [comment]
@tarunsujit  it worked for me now. I only specified the element (RemoteWebElement) element).getId()); and it does work. But if i specified both direction and element, scroll didn't work. Not sure about the reason.

**Comment by tarunsujit** [comment]
@TaylorTai glad you got this resolved.
