### ISSUE TITLE
iOS - Appium reports "tap point is not within the bounds of the screen" for "Cancel" button on Game Center login 

### ISSUE THREAD

**Issue by rucindrea** [appium/appium#4711]
Appium version: 1.3.2
Testing on different iOS versions, I randomly get a "tap point is not within the bounds of the screen" error from appium when trying to tap "Cancel" on the Game Center login window that is brought up by the game I am testing. 

The button is found and is obviously not out of bounds, but appium reports it so. 

Below the relevat appium log:

[36minfo[39m: [debug] [32m[INST] 2015-03-13 08:12:34 +0000 Debug: Got new command 14 from instruments: au.getElementByName('Cancel')[39m
[36minfo[39m: [debug] [32m[INST] 2015-03-13 08:12:34 +0000 Debug: evaluating au.getElementByName('Cancel')[39m
[36minfo[39m: [debug] [32m[INST] 2015-03-13 08:12:41 +0000 Debug: evaluation finished[39m
[36minfo[39m: [debug] [32m[INST] 2015-03-13 08:12:41 +0000 Debug: Lookup returned [object UIAButton] with the name "Cancel" (id: 0).
       2015-03-13 08:12:41 +0000 Debug: responding with:[39m
[36minfo[39m: [debug] [32m[INST] 2015-03-13 08:12:41 +0000 Debug: Running system command #15: /usr/local/bin/node /opt/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"0"}}...[39m
[36minfo[39m: [debug] Socket data received (38 bytes)
[36minfo[39m: [debug] Socket data being routed.
[36minfo[39m: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"0"}}
[36minfo[39m: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"0"},"sessionId":"098973f9-b1a3-4d0e-9526-bc50b5be5dcb"}
[36minfo[39m: [37m<-- POST /wd/hub/session/098973f9-b1a3-4d0e-9526-bc50b5be5dcb/element [39m[32m200[39m[90m 7939.649 ms - 87[39m [90m{"status":0,"value":{"ELEMENT":"0"},"sessionId":"098973f9-b1a3-4d0e-9526-bc50b5be5dcb"}[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/098973f9-b1a3-4d0e-9526-bc50b5be5dcb/element/0/click[39m [90m{"id":"0"}[39m
[36minfo[39m: [debug] Pushing command to appium work queue: "au.tapById('0')"
[36minfo[39m: [debug] Sending command to instruments: au.tapById('0')
[36minfo[39m: [debug] [32m[INST] 2015-03-13 08:12:42 +0000 Debug: Got new command 15 from instruments: au.tapById('0')[39m
[36minfo[39m: [debug] [32m[INST] 2015-03-13 08:12:42 +0000 Debug: evaluating au.tapById('0')[39m
[36minfo[39m: [debug] [32m[INST] 2015-03-13 08:12:43 +0000 Debug: UIAButton.tap()[39m
[36minfo[39m: [debug] [32m[INST] 2015-03-13 08:12:43 +0000 Debug: tap point is not within the bounds of the screen[39m
[36minfo[39m: [debug] [32m[INST] 2015-03-13 08:12:43 +0000 Error: VerboseError: elementId 0 could not be tapped[39m
[36minfo[39m: [debug] Socket data received (57 bytes)
[36minfo[39m: [debug] Socket data being routed.
[36minfo[39m: [debug] Got result from instruments: {"status":13,"value":"elementId 0 could not be tapped"}
[36minfo[39m: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"elementId 0 could not be tapped"},"sessionId":"098973f9-b1a3-4d0e-9526-bc50b5be5dcb"}

**Comment by sebv** [comment]
One of those bugs...

**Comment by IntelloScooby** [comment]
I am also getting this error when I try to tap at an x,y coordinate on a slider object. The object is visible and the coordinates are correct but I still get the error "tap point is not within the bounds of the screen"

**Comment by imurchie** [comment]
Closing as Instruments is not being supported.
