### ISSUE TITLE
Instruments are getting crashed while performing tap operations on some buttons of ios app on IPOD

### ISSUE THREAD

**Issue by KarthikKakani** [appium/appium#4717]
Hi,

We are automating an app in IOS. While performing tap operations on few buttons the instruments are getting crashed and app is getting closed unexpectedly. Please find the error log below:
info: [debug] Pushing command to appium work queue: "au.tapById('9')"
info: [debug] Sending command to instruments: au.tapById('9')
info: [debug] [INST] 2015-02-12 13:47:28 +0000 Debug: Got new command 25 from instruments: au.tapById('9')
info: [debug] [INST] 2015-02-12 13:47:28 +0000 Debug: evaluating au.tapById('9')
info: [debug] [INST] 2015-02-12 13:47:28 +0000 Debug: UIAButton.tap()
info: [debug] [INST] 2015-02-12 13:47:28 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-02-12 13:47:28 +0000 Debug: responding with:
info: [debug] [INST] 2015-02-12 13:47:28 +0000 Debug: Running system command #26: /usr/local/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"6acae235-aba0-4f38-b41f-366d5a47c3e4"}
info: <-- POST /wd/hub/session/6acae235-aba0-4f38-b41f-366d5a47c3e4/element/9/click 200 1239.696 ms - 74 {"status":0,"value":"","sessionId":"6acae235-aba0-4f38-b41f-366d5a47c3e4"}
info: [debug] [INST] 2015-02-12 22:07:05 +0000 Fail: The target application appears to have died
info: [debug] [INST] Instruments Trace Complete (Duration : 52.767536s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Destroying instruments client socket.

We are automating the app in a real device IPOD. The details of my machine are:
Appium: 1.3.1
IOS: 10.10

Observation: The same tap operation is working fine on IPAD. We are facing this issue in IPOD only.

Could anyone please help me how to resolve the issue

Thanks and Regards,
Karthik

**Comment by KarthikKakani** [comment]
Hi,
Could anyone please provide the solution for the above issue

Thanks and Regards,
Karthik

**Comment by sebv** [comment]
Looks like your app is crashing.

**Comment by KarthikKakani** [comment]
The app is getting crashed when few tap operations are being performed by appium on some buttons. The error message observed is:
info: [debug] [INST] 2015-02-12 22:07:05 +0000 Fail: The target application appears to have died
info: [debug] [INST] Instruments Trace Complete (Duration : 52.767536s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly

As per my understanding, the above error indicates that after performing some tap operation on a button, the instruments are getting crashed unexpectedly.

**Comment by KarthikKakani** [comment]
So, is this issue is because of the application and not because of appium or instruments. Could you please confirm

**Comment by sebv** [comment]
I don't know, It's a guess, you could just try to run it with xCode/instrument and see if it happens without appium. 

One thing to keep in mind is that when you run a CI script, the sequence of events does not happen at the same speed than when you run it manually, and this could trigger synchronization issue you don't get otherwise, specially after tap events, you need to wait for the tap action to complete before continuing to the next step.

**Comment by sebv** [comment]
@KarthikKakani Did you manage to try in instruments?

**Comment by moizjv** [comment]
@KarthikKakani ping

**Comment by KarthikKakani** [comment]
Hi Seb,

I tried to perform operations on the application using instruments and the application is getting struck while tapping some of the elements.

Regards,
Karthik

**Comment by moizjv** [comment]
@KarthikKakani it seems to be an issue with your application then.

**Comment by moizjv** [comment]
try waiting little before and in between taps

**Comment by moizjv** [comment]
@sebv @KarthikKakani  I am closing it, as it seems to be an issue with your application.
