### ISSUE TITLE
Declare --no-reset and --full-reset in client side for DesiredCapabilities

### ISSUE THREAD

**Issue by vietnq254** [appium/appium#4719]
Is there anyway to declare --no-reset and --full-reset in client side for DesiredCapabilities?

**Comment by tarunsujit** [comment]
@vietnq254 Yes, you can use these caps [here] (https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md) is the full list

**Comment by vietnq254** [comment]
Here is the Enum list of MobileCapabilityType: 
![MobileCapabilityType](http://s21.postimg.org/wdl4qs6cn/2015_03_16_192548.png)

And we dont have these values that I requested.

**Comment by vietnq254** [comment]
Thank you! I was lazy, I didn't try to run it.
This code worked:
```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("fullReset", true);
```

@Jonahss, I suggest to improve the list of members of MobileCapabilityType.
