### ISSUE TITLE
prepareEmulator() should be a no-op when using a real device

### ISSUE THREAD

**Issue by willosser** [appium/appium#4723]
We've found inconsistent behavior​ for Android devices while starting Appium.​ The issue is raised from prepareDevice​()​​​ in android-common.js.  It calls one function, prepareEmulator​(), which calls ensureDeviceLocale() whether an emulator was specified or not.  The latter method calls adb.reboot().  This causes some actual devices to reboot.

adb.reboot() contains following cmd to perform a reboot: 
var adbCmd = "stop; sleep 2; setprop sys.boot_completed 0; start";​

The command behaves differently on different "real" devices​. For example, Alcatel OneTouch does not reboot the device, while LG G4 does.

**Comment by bootstraponline** [comment]
I think prepareEmulator should be a no-op on physical devices. There are a bunch of different ways for detecting if a device is an emulator or not. My guess is reading the IMEI number [via code](http://stackoverflow.com/a/24430325) would be reliable. Other ideas include, detecting the emulator- prefix from the serial number (from adb devices output) or reading the device info with `adb shell getprop ro.product.model` and looking for known strings. There are a bunch of emulator vendors (microsoft/xamarin/genymotion) and I'm not sure how well these detection methods would work there.

**Comment by amedvedjev** [comment]
17 March and real device LG G4 ..... interesting more the nmonth before official launch

**Comment by jlipps** [comment]
One comment on this: it looks like the reboot only happens in prepareEmulator when the 'language' or 'locale' caps are set. Otherwise, no reboot happens. @willosser are you perhaps using these caps?

If so, I don't see any way to avoid rebooting the device with the new settings (even if the reboot has other unintended consequences on a real device). At least not short of erroring on startup if we include those caps with a real device.

**Comment by willosser** [comment]
Well, we've set the language cap, but I don't see that we really need it just yet.  I can disable that for now and see if that fixes it.  The behavior sounds odd, though.

**Comment by moizjv** [comment]
@willosser did it solve the issue?

**Comment by jlipps** [comment]
@willosser the reason for this behavior is that a reboot is the way we have discovered to make language changes take effect reliably

**Comment by willosser** [comment]
Yes, @moizjv, that solved our problem.  I don't know how it's going to play out when we start testing in other languages, though.

**Comment by moizjv** [comment]
@willosser thanks closing issue for now.
