### ISSUE TITLE
automate Slack account invites

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#4724]
It'd be nice to setup Slack so people can join easily. The slackin that the react slack team uses is cool (node.js using babeljs).
- http://reactiflux.com/
- http://rauchg.com/slackin
- https://github.com/rauchg/slackin

**Comment by jlipps** [comment]
looks nice! do we want to use slack instead of gitter?

**Comment by jlipps** [comment]
@Jonahss could we run this on the same digitalocean server we use for discourse?

**Comment by Jonahss** [comment]
Sure :)

**Comment by bootstraponline** [comment]
I like Slack better than gitter. gitter will still be there if people want to use it.

**Comment by nicolamattina** [comment]
If you need to automate Slack invites, this tutorial can be useful for you:
https://blog.stamplay.com/launch-your-community-with-a-fully-automated-slack-signup-page/

**Comment by SrinivasanTarget** [comment]
@triager please close.
