### ISSUE TITLE
Be sure the Appium server is running with an application opened by using the "App Path" parameter in Appium.app (along with package and activity for Android) or by connecting with selenium client and supplying this in the desired capabilities object.

### ISSUE THREAD

**Issue by hardik-d** [appium/appium#4728]
Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --robot-address "0.0.0.0" --robot-port "4723" --platform-version "8.1" --platform-name "iOS" --app "/Users/hardik/PNM Consumer.app" --show-ios-log --device-name "iPhone 6 (70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497)" --native-instruments-lib

Could not set resource limits: 1: Operation not permitted

info: Welcome to Appium v1.3.4 (REV ed530cf462878ca9ab462992145a6ef3166b31e9)

info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"app":"/Users/hardik/PNM Consumer.app","nativeInstrumentsLib":true,"deviceName":"iPhone 6 (70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497)","platformName":"iOS","platformVersion":"8.1","showIOSLog":true,"robotPort":4723,"defaultCommandTimeout":7200}
info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"ed530cf462878ca9ab462992145a6ef3166b31e9"}}}

info: <-- GET /wd/hub/status 200 6.499 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"ed530cf462878ca9ab462992145a6ef3166b31e9"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"ed530cf462878ca9ab462992145a6ef3166b31e9"}}}

info: <-- GET /wd/hub/status 200 2.501 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"ed530cf462878ca9ab462992145a6ef3166b31e9"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"ed530cf462878ca9ab462992145a6ef3166b31e9"}}}
info: <-- GET /wd/hub/status 200 0.937 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"ed530cf462878ca9ab462992145a6ef3166b31e9"}}}
info: --> GET /wd/hub/sessions {}
info: [debug] Responding to client with success: {"status":0,"value":[]}
info: <-- GET /wd/hub/sessions 200 0.742 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone 6 (70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497)"}}
info: Client User-Agent string: Appium (unknown version) CFNetwork/720.2.4 Darwin/14.1.0 (x86_64)
info: [debug] Using local app from command line: /Users/hardik/PNM Consumer.app
info: [debug] Creating new appium session 826902a7-b63a-4465-ac0f-05f32751906f
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 8.2

info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPhone 6 (70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497)","platformVersion":"8.1"}

error: Could not find a device to launch. You requested 'iPhone 6 (70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497) (8.1 Simulator)', but the available devices were: ["iPad 2 (7.1 Simulator) [61298494-C84F-44A0-9C5B-14C2D10A8055]","iPad 2 (8.1 Simulator) [0D91A96F-3F4A-45F1-B015-EEA629FA2528]","iPad 2 (8.2 Simulator) [A4A44B0E-7BC0-4776-BC78-4C728BDCA9C1]","iPad Air (7.1 Simulator) [811010D6-1C27-44D4-92AE-4447924AB1FA]","iPad Air (8.1 Simulator) [688E0320-BA38-477D-BA36-E34C59712647]","iPad Air (8.2 Simulator) [982505D8-77C4-4E86-84E4-F5640B39F33D]","iPad Retina (7.1 Simulator) [5D54A6B7-EE40-4E59-B757-BA2D074E17EE]","iPad Retina (8.1 Simulator) [ED67FF24-9B92-4F2B-AAAC-EF19EC66F30F]","iPad Retina (8.2 Simulator) [4151EF3A-9915-4A03-B52F-4F7D787E6991]","iPhone 4s (7.1 Simulator) [C8149F7D-2221-48C4-B7F9-FB9CF7CEAAAE]","iPhone 4s (8.1 Simulator) [C10582BA-1564-40AA-8DC0-4F60F0298D4C]","iPhone 4s (8.2 Simulator) [ED2B4193-134C-4133-8FB0-4D5DBB7349CB]","iPhone 5 (7.1 Simulator) [EA60CC66-2B1E-44A6-B384-C0B1B135B56F]","iPhone 5 (8.1 Simulator) [C96F9D15-9D54-4DE7-8F68-DE72D7537F45]","iPhone 5 (8.2 Simulator) [94C9AAAB-3F47-454D-B9D0-841521F2677A]","iPhone 5s (7.1 Simulator) [A7BD52BC-9806-4074-BA3B-C4A82AB88BDF]","iPhone 5s (8.1 Simulator) [D40AF034-98B9-45D0-BDEB-A5D0585D85C8]","iPhone 5s (8.2 Simulator) [82726AC8-D2F6-4485-B98A-9EE1C1EC5108]","iPhone 6 (8.1 Simulator) [70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497]","iPhone 6 (8.2 Simulator) [3056C436-C268-47FC-B915-9E3FF0A44DAC]","iPhone 6 Plus (8.1 Simulator) [4043B17D-FAE8-4CBE-BD86-32CBF4BFC699]","iPhone 6 Plus (8.2 Simulator) [44F75698-5E4F-4D63-B490-938BC46601C3]"]

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497) (8.1 Simulator)'
info: [debug] Cleaning up appium session
info: [debug] Error: Could not find a device to launch. You requested 'iPhone 6 (70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497) (8.1 Simulator)', but the available devices were: ["iPad 2 (7.1 Simulator) [61298494-C84F-44A0-9C5B-14C2D10A8055]","iPad 2 (8.1 Simulator) [0D91A96F-3F4A-45F1-B015-EEA629FA2528]","iPad 2 (8.2 Simulator) [A4A44B0E-7BC0-4776-BC78-4C728BDCA9C1]","iPad Air (7.1 Simulator) [811010D6-1C27-44D4-92AE-4447924AB1FA]","iPad Air (8.1 Simulator) [688E0320-BA38-477D-BA36-E34C59712647]","iPad Air (8.2 Simulator) [982505D8-77C4-4E86-84E4-F5640B39F33D]","iPad Retina (7.1 Simulator) [5D54A6B7-EE40-4E59-B757-BA2D074E17EE]","iPad Retina (8.1 Simulator) [ED67FF24-9B92-4F2B-AAAC-EF19EC66F30F]","iPad Retina (8.2 Simulator) [4151EF3A-9915-4A03-B52F-4F7D787E6991]","iPhone 4s (7.1 Simulator) [C8149F7D-2221-48C4-B7F9-FB9CF7CEAAAE]","iPhone 4s (8.1 Simulator) [C10582BA-1564-40AA-8DC0-4F60F0298D4C]","iPhone 4s (8.2 Simulator) [ED2B4193-134C-4133-8FB0-4D5DBB7349CB]","iPhone 5 (7.1 Simulator) [EA60CC66-2B1E-44A6-B384-C0B1B135B56F]","iPhone 5 (8.1 Simulator) [C96F9D15-9D54-4DE7-8F68-DE72D7537F45]","iPhone 5 (8.2 Simulator) [94C9AAAB-3F47-454D-B9D0-841521F2677A]","iPhone 5s (7.1 Simulator) [A7BD52BC-9806-4074-BA3B-C4A82AB88BDF]","iPhone 5s (8.1 Simulator) [D40AF034-98B9-45D0-BDEB-A5D0585D85C8]","iPhone 5s (8.2 Simulator) [82726AC8-D2F6-4485-B98A-9EE1C1EC5108]","iPhone 6 (8.1 Simulator) [70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497]","iPhone 6 (8.2 Simulator) [3056C436-C268-47FC-B915-9E3FF0A44DAC]","iPhone 6 Plus (8.1 Simulator) [4043B17D-FAE8-4CBE-BD86-32CBF4BFC699]","iPhone 6 Plus (8.2 Simulator) [44F75698-5E4F-4D63-B490-938BC46601C3]"]
    at noDevicesError (/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/lib/devices/ios/ios.js:1106:10)
    at null.<anonymous> (/Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/lib/devices/ios/ios.js:1112:16)
    at /Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/node_modules/async/lib/async.js:525:46
    at /Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/node_modules/async/lib/async.js:254:17
    at /Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/node_modules/async/lib/async.js:151:21
    at /Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/node_modules/async/lib/async.js:251:21
    at /Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/node_modules/async/lib/async.js:615:34
    at /Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/node_modules/async/lib/async.js:516:25
    at /Users/hardik/projects/mobile/mobile_consumer/src/pnm_consumer/appium/node_modules/appium-instruments/lib/instruments.js:111:7
    at ChildProcess.exithandler (child_process.js:735:7)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find a device to launch. You requested 'iPhone 6 (70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497) (8.1 Simulator)', but the available devices were: [\"iPad 2 (7.1 Simulator) [61298494-C84F-44A0-9C5B-14C2D10A8055]\",\"iPad 2 (8.1 Simulator) [0D91A96F-3F4A-45F1-B015-EEA629FA2528]\",\"iPad 2 (8.2 Simulator) [A4A44B0E-7BC0-4776-BC78-4C728BDCA9C1]\",\"iPad Air (7.1 Simulator) [811010D6-1C27-44D4-92AE-4447924AB1FA]\",\"iPad Air (8.1 Simulator) [688E0320-BA38-477D-BA36-E34C59712647]\",\"iPad Air (8.2 Simulator) [982505D8-77C4-4E86-84E4-F5640B39F33D]\",\"iPad Retina (7.1 Simulator) [5D54A6B7-EE40-4E59-B757-BA2D074E17EE]\",\"iPad Retina (8.1 Simulator) [ED67FF24-9B92-4F2B-AAAC-EF19EC66F30F]\",\"iPad Retina (8.2 Simulator) [4151EF3A-9915-4A03-B52F-4F7D787E6991]\",\"iPhone 4s (7.1 Simulator) [C8149F7D-2221-48C4-B7F9-FB9CF7CEAAAE]\",\"iPhone 4s (8.1 Simulator) [C10582BA-1564-40AA-8DC0-4F60F0298D4C]\",\"iPhone 4s (8.2 Simulator) [ED2B4193-134C-4133-8FB0-4D
error: Failed to start an Appium session, err was: Error: Could not find a device to launch. You requested 'iPhone 6 (70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497) (8.1 Simulator)', but the available devices were: ["iPad 2 (7.1 Simulator) [61298494-C84F-44A0-9C5B-14C2D10A8055]","iPad 2 (8.1 Simulator) [0D91A96F-3F4A-45F1-B015-EEA629FA2528]","iPad 2 (8.2 Simulator) [A4A44B0E-7BC0-4776-BC78-4C728BDCA9C1]","iPad Air (7.1 Simulator) [811010D6-1C27-44D4-92AE-4447924AB1FA]","iPad Air (8.1 Simulator) [688E0320-BA38-477D-BA36-E34C59712647]","iPad Air (8.2 Simulator) [982505D8-77C4-4E86-84E4-F5640B39F33D]","iPad Retina (7.1 Simulator) [5D54A6B7-EE40-4E59-B757-BA2D074E17EE]","iPad Retina (8.1 Simulator) [ED67FF24-9B92-4F2B-AAAC-EF19EC66F30F]","iPad Retina (8.2 Simulator) [4151EF3A-9915-4A03-B52F-4F7D787E6991]","iPhone 4s (7.1 Simulator) [C8149F7D-2221-48C4-B7F9-FB9CF7CEAAAE]","iPhone 4s (8.1 Simulator) [C10582BA-1564-40AA-8DC0-4F60F0298D4C]","iPhone 4s (8.2 Simulator) [ED2B4193-134C-4133-8FB0-4D5DBB7349CB]","iPhone 5 (7.1 Simulator) [EA60CC66-2B1E-44A6-B384-C0B1B135B56F]","iPhone 5 (8.1 Simulator) [C96F9D15-9D54-4DE7-8F68-DE72D7537F45]","iPhone 5 (8.2 Simulator) [94C9AAAB-3F47-454D-B9D0-841521F2677A]","iPhone 5s (7.1 Simulator) [A7BD52BC-9806-4074-BA3B-C4A82AB88BDF]","iPhone 5s (8.1 Simulator) [D40AF034-98B9-45D0-BDEB-A5D0585D85C8]","iPhone 5s (8.2 Simulator) [82726AC8-D2F6-4485-B98A-9EE1C1EC5108]","iPhone 6 (8.1 Simulator) [70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497]","iPhone 6 (8.2 Simulator) [3056C436-C268-47FC-B915-9E3FF0A44DAC]","iPhone 6 Plus (8.1 Simulator) [4043B17D-FAE8-4CBE-BD86-32CBF4BFC699]","iPhone 6 Plus (8.2 Simulator) [44F75698-5E4F-4D63-B490-938BC46601C3]"]

5DBB7349CB]\",\"iPhone 5 (7.1 Simulator) [EA60CC66-2B1E-44A6-B384-C0B1B135B56F]\",\"iPhone 5 (8.1 Simulator) [C96F9D15-9D54-4DE7-8F68-DE72D7537F45]\",\"iPhone 5 (8.2 Simulator) [94C9AAAB-3F47-454D-B9D0-841521F2677A]\",\"iPhone 5s (7.1 Simulator) [A7BD52BC-9806-4074-BA3B-C4A82AB88BDF]\",\"iPhone 5s (8.1 Simulator) [D40AF034-98B9-45D0-BDEB-A5D0585D85C8]\",\"iPhone 5s (8.2 Simulator) [82726AC8-D2F6-4485-B98A-9EE1C1EC5108]\",\"iPhone 6 (8.1 Simulator) [70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497]\",\"iPhone 6 (8.2 Simulator) [3056C436-C268-47FC-B915-9E3FF0A44DAC]\",\"iPhone 6 Plus (8.1 Simulator) [4043B17D-FAE8-4CBE-BD86-32CBF4BFC699]\",\"iPhone 6 Plus (8.2 Simulator) [44F75698-5E4F-4D63-B490-938BC46601C3]\"])","origValue":"Could not find a device to launch. You requested 'iPhone 6 (70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497) (8.1 Simulator)', but the available devices were: [\"iPad 2 (7.1 Simulator) [61298494-C84F-44A0-9C5B-14C2D10A8055]\",\"iPad 2 (8.1 Simulator) [0D91A96F-3F4A-45F1-B015-EEA629FA2528]\",\"iPad 2 (8.2 Simulator) [A4A44B0E-7BC0-4776-BC78-4C728BDCA9C1]\",\"iPad Air (7.1 Simulator) [811010D6-1C27-44D4-92AE-4447924AB1FA]\",\"iPad Air (8.1 Simulator) [688E0320-BA38-477D-BA36-E34C59712647]\",\"iPad Air (8.2 Simulator) [982505D8-77C4-4E86-84E4-F5640B39F33D]\",\"iPad Retina (7.1 Simulator) [5D54A6B7-EE40-4E59-B757-BA2D074E17EE]\",\"iPad Retina (8.1 Simulator) [ED67FF24-9B92-4F2B-AAAC-EF19EC66F30F]\",\"iPad Retina (8.2 Simulator) [4151EF3A-9915-4A03-B52F-4F7D787E6991]\",\"iPhone 4s (7.1 Simulator) [C8149F7D-2221-48C4-B7F9-FB9CF7CEAAAE]\",\"iPhone 4s (8.1 Simulator) [C10582BA-1564-40AA-8DC0-4F60F0298D4C]\",\"iPhone 4s (8.2 Simulator) [ED2B4193-134C-4133-8FB0-4D5DBB7349CB]\",\"iPhone 5 (7.1 Simulator) [EA60CC66-2B1E-44A6-B384-C0B1B135B56F]\",\"iPhone 5 (8.1 Simulator) [C96F9D15-9D54-4DE7-8F68-DE72D7537F45]\",\"iPhone 5 (8.2 Simulator) [94C9AAAB-3F47-454D-B9D0-841521F2677A]\",\"iPhone 5s (7.1 Simulator) [A7BD52BC-9806-4074-BA3B-C4A82AB88BDF]\",\"iPhone 5s (8.1 Simulator) [D40AF034-98B9-45D0-BDEB-A5D0585D85C8]\",\"iPhone 5s (8.2 Simulator) [82726AC8-D2F6-4485-B98A-9EE1C1EC5108]\",\"iPhone 6 (8.1 Simulator) [70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497]\",\"iPhone 6 (8.2 Simulator) [3056C436-C268-47FC-B915-9E3FF0A44DAC]\",\"iPhone 6 Plus (8.1 Simulator) [4043B17D-FAE8-4CBE-BD86-32CBF4BFC699]\",\"iPhone 6 Plus (8.2 Simulator) [44F75698-5E4F-4D63-B490-938BC46601C3]\"]"},"sessionId":null}
info: <-- POST /wd/hub/session 500 651.505 ms - 3450 

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.4","revision":"ed530cf462878ca9ab462992145a6ef3166b31e9"}}}
info: <-- GET /wd/hub/status 200 0.769 ms - 104 {"status":0,"value":{"build":{"version":"1.3.4","revision":"ed530cf462878ca9ab462992145a6ef3166b31e9"}}}

**Comment by hardik-d** [comment]
more info:

xcrun simctl list
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
Resizable iPhone (com.apple.CoreSimulator.SimDeviceType.Resizable-iPhone)
Resizable iPad (com.apple.CoreSimulator.SimDeviceType.Resizable-iPad)
== Runtimes ==
iOS 7.1 (7.1 - 11D167) (com.apple.CoreSimulator.SimRuntime.iOS-7-1)
iOS 8.1 (8.1 - 12B411) (com.apple.CoreSimulator.SimRuntime.iOS-8-1)
iOS 8.2 (8.2 - 12D508) (com.apple.CoreSimulator.SimRuntime.iOS-8-2)
== Devices ==
-- iOS 7.1 --
    iPhone 4s (C8149F7D-2221-48C4-B7F9-FB9CF7CEAAAE) (Shutdown)
    iPhone 5 (EA60CC66-2B1E-44A6-B384-C0B1B135B56F) (Shutdown)
    iPhone 5s (A7BD52BC-9806-4074-BA3B-C4A82AB88BDF) (Creating)
    iPad 2 (61298494-C84F-44A0-9C5B-14C2D10A8055) (Shutdown)
    iPad Retina (5D54A6B7-EE40-4E59-B757-BA2D074E17EE) (Shutdown)
    iPad Air (811010D6-1C27-44D4-92AE-4447924AB1FA) (Shutdown)
-- iOS 8.1 --
    iPhone 4s (C10582BA-1564-40AA-8DC0-4F60F0298D4C) (Shutdown)
    iPhone 5 (C96F9D15-9D54-4DE7-8F68-DE72D7537F45) (Shutdown)
    iPhone 5s (D40AF034-98B9-45D0-BDEB-A5D0585D85C8) (Shutdown)
    iPhone 6 Plus (4043B17D-FAE8-4CBE-BD86-32CBF4BFC699) (Shutdown)
    iPhone 6 (70DFFC34-5F5F-4E81-AF72-6B1AD0AE4497) (Booted)
    iPad 2 (0D91A96F-3F4A-45F1-B015-EEA629FA2528) (Shutdown)
    iPad Retina (ED67FF24-9B92-4F2B-AAAC-EF19EC66F30F) (Shutdown)
    iPad Air (688E0320-BA38-477D-BA36-E34C59712647) (Shutdown)
    Resizable iPhone (7E28FC3A-1B07-496B-9182-389C780CF677) (Shutdown)
    Resizable iPad (BD7A22FD-D2F5-4EC3-8FD0-D89664955402) (Shutdown)
-- iOS 8.2 --
    iPhone 4s (ED2B4193-134C-4133-8FB0-4D5DBB7349CB) (Shutdown)
    iPhone 5 (94C9AAAB-3F47-454D-B9D0-841521F2677A) (Shutdown)
    iPhone 5s (82726AC8-D2F6-4485-B98A-9EE1C1EC5108) (Shutdown)
    iPhone 6 Plus (44F75698-5E4F-4D63-B490-938BC46601C3) (Shutdown)
    iPhone 6 (3056C436-C268-47FC-B915-9E3FF0A44DAC) (Shutdown)
    iPad 2 (A4A44B0E-7BC0-4776-BC78-4C728BDCA9C1) (Shutdown)
    iPad Retina (4151EF3A-9915-4A03-B52F-4F7D787E6991) (Shutdown)
    iPad Air (982505D8-77C4-4E86-84E4-F5640B39F33D) (Shutdown)
    Resizable iPhone (4431BDB0-5EEB-4498-BD6F-9F99217DD6A0) (Shutdown)
    Resizable iPad (B6CEECAB-A5CD-475F-A7CF-9BF327942E66) (Shutdown)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-8-0 --
    iPhone 4s (A037538C-B42F-4E25-A981-9AE3120F6848) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (A0297152-91EC-4C12-ADA8-9DED02B6A7E2) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (0B075D28-34D5-4EB8-A2DA-B01175C5A90E) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (E185A84C-3EA2-4114-8FA4-7ADB532CFD16) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (9837A1A2-9F49-4165-9E67-C71C087FF5BC) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (888C4BC5-4A01-43CC-9CA6-5B52842D04C6) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (1FB91091-0495-40BF-801B-1A90AC27F0AE) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (E4A1CF39-7322-4334-9F5F-A1EC09370795) (Shutdown) (unavailable, runtime profile not found)
    Resizable iPhone (AB5ACD1D-8CE0-4554-BF75-C2105743527B) (Shutdown) (unavailable, runtime profile not found)
    Resizable iPad (A442F7A0-42B0-487C-8E2C-348538BF146F) (Shutdown) (unavailable, runtime profile not found)

**Comment by hardik-d** [comment]
on xcode 6.2, OSX 10.10.2, appium 1.3.7 beta, appium.io 1.3.6

**Comment by hardik-d** [comment]
@sebv can you let me know if xcode 6.2 is even supported. since the update our development has kind of stopped since cannot inspect elements atm.

**Comment by hardik-d** [comment]
nevermind workaround mentioned here: https://discuss.appium.io/t/could-not-launch-appium-inspector-cannot-launch-the-appium-inspector-on-1-3-5-beta/2967 

worked.

**Comment by sebv** [comment]
nice!
