### ISSUE TITLE
Android UiScrollable - unable to use methods that do not result in a UiObject/UiSelector

### ISSUE THREAD

**Issue by Simon-Kaz** [appium/appium#4733]
I'm trying to implement my own version of scrollTo, and to do that on Android, I decided to use UiAutomator api methods.

Seeing how Appium supports both UiSelectors and UiScrollable, I figured the following would work to scroll to the top of the scrollable element:
`driver.findElement(MobileBy.AndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollToBeginning(10);"));`

It does not work, as I get the following:

```
2015-03-18 11:15:59:863 - info: [debug] Pushing command to appium work queue: ["find",{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollToBeginning(10);","context":"","multiple":false}]

2015-03-18 11:15:59:866 - info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollToBeginning(10);","context":"","multiple":false}}

2015-03-18 11:15:59:867 - info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION

2015-03-18 11:15:59:867 - info: [debug] [BOOTSTRAP] [debug] Got command action: find

2015-03-18 11:15:59:867 - info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollToBeginning(10); using ANDROID_UIAUTOMATOR with the contextId:  multiple: false

2015-03-18 11:15:59:867 - info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollToBeginning(10)

2015-03-18 11:15:59:867 - info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true

2015-03-18 11:15:59:867 - info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0

2015-03-18 11:15:59:868 - info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollToBeginning(int) throws com.android.uiautomator.core.UiObjectNotFoundException args: 10, 

2015-03-18 11:15:59:868 - info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: int arg: 10

2015-03-18 11:15:59:868 - info: [debug] [BOOTSTRAP] [debug] Method name: scrollToBeginning

2015-03-18 11:15:59:868 - info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Could not parse UiSelector argument: Must only call the 'scrollIntoView' method OR methods on UiScrollable which return UiScrollable or UiObject objects","status":9}

2015-03-18 11:15:59:868 - info: [debug] Condition unmet after 5136ms. Timing out.

2015-03-18 11:15:59:869 - info: [debug] Responding to client with error: {"status":9,"value":{"message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.","origValue":"Could not parse UiSelector argument: Must only call the 'scrollIntoView' method OR methods on UiScrollable which return UiScrollable or UiObject objects"},"sessionId":"851c3676-5f27-403e-b33d-67c093b6b2f4"}
```

I'm guessing that the log of interest is the following:

```
    {"value":"Could not parse UiSelector argument: Must only call the 'scrollIntoView' method OR methods on UiScrollable which return UiScrollable or UiObject objects","status":9}
```

My method doesn't return a UiScrollable or UiObject object. It simply scrolls to the top of the screen using the scrollable element, and I confirmed that the scrollable UiSelector is correct.

I tried ScrollToBeginning, flingToBeginning, flingToEnd and all related methods that scroll based on steps.

Am I doing something wrong or are the scrolling methods (other than scrollIntoView) not supported in Appium?

**Comment by Simon-Kaz** [comment]
I did some digging and found this ticket:

https://github.com/appium/appium/pull/2939#issuecomment-47007961

I understand @Jonahss 's remark about "find" method not returning an element, but there is no other way to use UiAutomator methods, is there?

If there isn't, has anyone found a good way to do a smart scroll to the top/bottom (one that stops scrolling when it reaches the top/bottom)?

**Comment by sebv** [comment]
@Jonahss could you look into this, I don't really know this part myself.

**Comment by Jonahss** [comment]
We've been trying to come up with a better system for scrolling. I guess we can support the other UiScrollable functions and just return nothing (or throw an ElementNotFound Exception) if an element isn't returned?
Looping in @jlipps

**Comment by jlipps** [comment]
why not just throw ElementNotFound (seems the right thing to do server-side) and then the client can always catch and do nothing with the error

**Comment by jlipps** [comment]
what i usually do in this case is use the gestures and the simply check the state of the app to determine whether i need to scroll more or stop

**Comment by sebv** [comment]
We need to figure out  better way.

**Comment by radamstx** [comment]
I've found that there is use in being able to execute UIAutomation Javascript for iOS testing. I'd like to see the same functionality in being able to execute UiAutomator commands for Android testing. I'm working on this now and should come up with a CR for both the Appium server and Appium java-client

**Comment by olka** [comment]
Totally agree with Robert here. 
It's totally inconsistent and non-flexible solution to allow script execution on one platform and deny it on another.
@radamstx have you managed to solve this issue?

**Comment by SrinivasanTarget** [comment]
ScrollTo is deprecated in java-client.please look into this for better approach https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/IOSScrollingSearchingTest.java

Closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by smaspe** [comment]
I don't understand why this is closed, and how it relates to `ScrollTo`. I'm trying to call `${scrollView.find_element_by_android_uiautomator('new UiScrollable(new UiSelector().scrollable(true)).flingToEnd(1)')}` in robot, to simply get to the end of the scrollview, but get that error that there are some methods that I am not allowed to call for some mysterious reason...

**Comment by SrinivasanTarget** [comment]
Hey @smaspe Thanks for pointing this. Would be good if you could paste the latest gist here inform of gist.

**Comment by smaspe** [comment]
Here is the full code I want to execute:

    @{elements}=    Get Elements  android=new UiSelector().scrollable(true)
    ${scrollView}=  Set Variable  @{elements}[0]
    Log  ${scrollView.find_element_by_android_uiautomator('new UiScrollable(new UiSelector().scrollable(true)).flingToEnd(1)')}

That's RobotFramework code, and is supposed to scroll the first scroll view (the only) on the screen to the end. Unfortunately the `flingToEnd` method is forbidden?

The result in the log is the same:

    {"value":"Could not parse UiSelector argument: Must only call the 'scrollIntoView' method OR methods on UiScrollable which return UiScrollable or UiObject objects","status":9}

**Comment by SrinivasanTarget** [comment]
@smaspe Looks interesting.Will look into this.

**Comment by SrinivasanTarget** [comment]
@triager please open

**Comment by smaspe** [comment]
@SrinivasanTarget I had another case where I would like to use a method that is not supported (`scrollBackward`. I am using a calendar, and searching for a specific date. But using `scrollIntoView`, it first tries to scroll the calendar up to the beginning of times, which would take forever. I added a limit to the number of authorized swipes, but that is still very suboptimal). Is there any update on this issue?

**Comment by gavrilfb** [comment]
Is this issue still under development? I see the original issue kinda sidetracked in the middle of discussions when this ticket got closed. I use appium 1.6.5 and it still only have the same limitation.

It works when you use scrollIntoView, but I need scrollToBeginning / scrollToEnd in my code.
Or maybe someone found a nice workaround for scrolling to beginning or end of the UiScrollable object?

Here is my log:

> [debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["-android uiautomator","new UiScrollable(new UiSelector().scrollable(true)).scrollToEnd(50)","02142886-bf92-48fa-a023-e86d3836835d"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 5000 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true)).scrollToEnd(50)","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true)).scrollToEnd(50)","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'new UiScrollable(new UiSelector().scrollable(true)).scrollToEnd(50)' using 'ANDROID_UIAUTOMATOR' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true)).scrollToEnd(50)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiSelector coerce type: boolean arg: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollToEnd(int) throws com.android.uiautomator.core.UiObjectNotFoundException args: 50,
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiScrollable coerce type: int arg: 50
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Method name: scrollToEnd
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":9,"value":"Could not parse UiSelector argument: Must only call the 'scrollIntoView' method OR methods on UiScrollable which return UiScrollable or UiObject objects"}

**Comment by Valentine11** [comment]
Same issue. I need scroll on the top and try use androidUiAutomation like this:
`await driver.elementByAndroidUIAutomator('new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollBackward()');`
but get error:
`Error: [elementByAndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollBackward()")] Error response status: 9, , UnknownCommand - The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource. Selenium error: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.`
I can workaround this using scroll into view to any element on top, but in this case I should determine this element for every screen.  A universal solution would be better.

**Comment by bhupi6314** [comment]
driver.findElementByAndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollToBeginning(10);")
Try using this might help as i am using driver.findElementByAndroidUIAutomator method to scroll

**Comment by bahunov** [comment]
Is there any update on this?? Getting the same issue:
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Method name: scrollToEnd
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":9,"value":"Could not parse UiSelector argument: Must only call the 'scrollIntoView' method OR methods on UiScrollable which return UiScrollable or UiObject objects"}

**Comment by russellpollock** [comment]
Just to add to the list...getting the same server error as others when using
`driver.findElement(MobileBy.AndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollToBeginning(10);"));`

`Could not parse UiSelector argument: Must only call the 'scrollIntoView' method OR methods on UiScrollable`

**Comment by shizhongping** [comment]
I am using java-client 5.0.4 with appium desktop 1.6.2.

Here is my work around:
>         try{
>            driver.findElementByAndroidUIAutomator("new UiScrollable(new >UiSelector().scrollable(true).instance(0)).scrollToEnd(9);");
>       } catch (Exception e) {
>            logger.info(e.getMessage());
>        }

**Comment by mike-pt** [comment]
Doing something similar with python (via try/except) but would be nice to get this fixed

**Comment by hasan-abbas86** [comment]
With Appium v1.16.0, scroll is not working for me either.

For following code:
`try {
			StepDefs.driver.findElement(MobileBy.AndroidUIAutomator("new UiScrollable(new UiSelector()).setAsVerticalList().flingToBeginning(5);"));
			//StepDefs.driver.findElement(MobileBy.AndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollToBeginning(20);"));
			//StepDefs.driver.findElement(MobileBy.AndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollToEnd(20);"));
		}
		catch (Exception e){
			e.printStackTrace();
		}
`

I have used scrollToEnd, scrollToBeginning as well as flingToBeginning, but none has worked for me so far, and I always get this exception in my logs:

`Could not parse expression `new UiScrollable(new UiSelector()).setAsVerticalList().flingToBeginning(5)`: Last method called on a UiScrollable object must return a UiObject object`

**Comment by hamzafarooq333** [comment]
Here is my code which works fine. Try this if you want to scroll down till the end of screen in android.

try {

Thread.sleep(5000);
StepDefs.driver.findElement(MobileBy.AndroidUIAutomator(“new UiScrollable(new UiSelector().scrollable(true))”+".scrollToEnd(55);"));

}
catch (Exception e)
{

System.out.println(e.getMessage());

}

Note: The Int value 55 is the number of maxSwipes you want to perform on the screen.

https://developer.android.com/reference/android/support/test/uiautomator/UiScrollable#scrolltoend

**Comment by mykola-mokhnach** [comment]
The patch has been published to appium@beta
