### ISSUE TITLE
Provide a way to retrieve device UDID (and possibly other server params) by client appium API

### ISSUE THREAD

**Issue by vladisx** [appium/appium#4734]
It sometimes helpful to know on which device the tests currently being executed. See for example this question in the appium discussion https://discuss.appium.io/t/getting-the-udid-or-serial-number-of-a-device-from-appium/3333

**Comment by Fanch-** [comment]
Up, see also https://discuss.appium.io/t/get-back-udid-from-command-line/3644

**Comment by Fanch-** [comment]
Linked to #4851

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/issues/6550#issuecomment-228610101

**Comment by SrinivasanTarget** [comment]
@triager please close
