### ISSUE TITLE
AppiumDriver is not working with java-client-2.2.0 jar

### ISSUE THREAD

**Issue by amitjaincoer191** [appium/appium#4737]
AppiumDriver is not working with java-client-2.2.0 jar

We are getting compile time error foe below instantiation

driver = new AppiumDriver(new URL("http://127.0.0.1:4725/wd/hub"), capabilities);

**Comment by amitjaincoer191** [comment]
![appium-error](https://cloud.githubusercontent.com/assets/7996111/6728496/226d8176-ce50-11e4-8907-0dea08fed0e6.PNG)

**Comment by vietnq254** [comment]
You must to use ```AndroidDriver``` instead of ```AppiumDriver``` in your case.

**Comment by tarunsujit** [comment]
@amitjaincoer191 Please change it to AndroidDriver
