### ISSUE TITLE
Appium 1.3.4 : IOS 6(8.2):: element display behaves weired

### ISSUE THREAD

**Issue by p00j4** [appium/appium#4741]
I was having really hard time to understand that why some element is visible while seeing with bare eyes upfront, appium claims- not displayed. and my test gives "false fail alarm"
After debugging from many angles finally 1 fits logically.
There are times @ runtime when getTreeForXML() returns more than 1 item for an element 
and so gives "display=false" when unfortunately the one which is hidden comes at first as per indexing [though @ the same time, trying with inspector clearly give only 1 item ]
Ex. in screenshot, here Email id field is recognized  sometimes and sometimes not [which is always displayed and only once "xpath=//UIATableCell[UIATextField[contains(@value,'Email')]]"
but isDisplayed returns false sometimes, then I checked the page source in this typical case and came to know there were 2 entries for the same xpath which could have caused it. [still I can't find why 2 entries, because there is no similar screen in back]
Also, why is the non-displayed is prior to the displayed one in indexing [ideally the visible item should have been @ index 0 and rest followed by]
![screen shot 2015-03-19 at 7 30 08 pm](https://cloud.githubusercontent.com/assets/6470509/6732074/67df62e6-ce6f-11e4-9d8d-66ee45f7452f.png)

**Comment by p00j4** [comment]
Also, there is another case when pagesource doesn't retrieve the element itself
I can see the item exists - an empty textbox
I'm trying to get it by xpath= //UIATableCell[UIATextField[contains(@value,'Email')]]
but in page-source previous test value is filled [why not refreshed when new test is launched ?]
and so it cant find the provided xpath
```
  <UIATableCell name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/1/12/3" x="0" y="233.890625" width="375" height="52.734375">
                    <UIATextField name="" label="" value="abc_auto@gmail.com" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/1/12/3/0" x="78.515625" y="239.75" width="274.21875" height="35.15625">
                        <UIATextField name="" label="" value="abc_auto@gmail.com" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/1/12/3/0/0" x="78.515625" y="239.75" width="274.21875" height="35.15625">
                        </UIATextField>
                    </UIATextField>
                </UIATableCell>
```

**Comment by p00j4** [comment]
1 more wired case:
the item -  xpath=//UIAStaticText[contains(@name,'agree to goibibo')] 
exists and locatable always, still webdriver's isDisplayed() returns "false" 
![screen shot 2015-03-25 at 6 45 51 pm](https://cloud.githubusercontent.com/assets/6470509/6825344/fcbbd912-d31f-11e4-9431-e9bf1da44499.png)
![screen shot 2015-03-25 at 6 49 01 pm](https://cloud.githubusercontent.com/assets/6470509/6825347/00de9908-d320-11e4-9e81-fc4f98e5ad3e.png)
![screen shot 2015-03-25 at 6 52 46 pm](https://cloud.githubusercontent.com/assets/6470509/6825359/1b99af12-d320-11e4-91a8-37539941d4f3.png)

here is the pageSource
```
{"UIAStaticText":{"@":{"name":"I agree to goibibo Terms and Conditions","label":"I agree to goibibo Terms and Conditions","value":"I agree to goibibo Terms and Conditions","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/1/25","x":0,"y":584.28125,"width":375,"height":25.78125},">":[]}}
```

**Comment by sebv** [comment]
I guess that should be added to the long list of xpath bugs.

**Comment by SrinivasanTarget** [comment]
@triager please close
