### ISSUE TITLE
[Android][Appium 1.3.6] Back button does not work when using unicode keyboard

### ISSUE THREAD

**Issue by ktronic80** [appium/appium#4742]
Hi,

I'm using the unicode keyboard in my tests. To enable it I use the capabilities
capabilities.setCapability("unicodeKeyboard", true);
capabilities.setCapability("resetKeyboard", true);

With the upgrade to Appium 1.3.6 it seems that when using the unicode keyboard the back button is not working. I'm doing something like this:

driver.findElement(MobileBy.id("my.android:id/tv_home_listview_catname")).click();
driver.findElement(MobileBy.id("my.android:id/lv_home_listviewcol")).click();
driver.navigate().back();

It is working fine with Appium 1.3.4. When  using Appium 1.3.6 (also occurs in 1.3.5) with unicode keyboard enabled the back() method is executed without any error but nothing happens in my app. When I set unicodeKeyboard to false it is also working with 1.3.6.
Sometimes it happens that even if Appium (1.3.6) is finished the Home or back button on a device is not working until I uninstall the Appium Input Manager for Unicode.

I used the following devices:
Nexus 7 and 10 Android 5.0.1
Samsung Galaxy Note 3 Android 4.4.2
Samsung Galaxy Tab 3 10.1 Android 4.4.2
Emulator with Android 4.4.2

**Comment by ktronic80** [comment]
Added a comment in the referenced issue  #4815

**Comment by vietnq254** [comment]
Will it be fixed in Appium 1.4 ?

**Comment by Jonahss** [comment]
Sorry no, 1.4 is already ready for release (going through the process today) so this bug won't make it in.

Thank you for the full reproduction cases in the referenced issue, that will make fixing this for the next release much easier.

**Comment by vsaraydarova** [comment]
Is there any progress on the issue, or any workaround?
