### ISSUE TITLE
Unable to enter tilde character on iOS

### ISSUE THREAD

**Issue by invertednz** [appium/appium#4743]
When running a test on iOS device I am unable to send a tilde character. The character works fine for Android but on iOS it goes to the special character keyboard and the tilde key isn't there and the test fails.

Appium 1.3.5, c# bindings.

Receive the following error target.frontMostApp().keyboard() failed to locate "`" key.

It may be caused by the fact that the tilde key is unavailable on the non-alphabet keyboard and is only available after holding down the "." key.

https://discuss.appium.io/uploads/default/710/749cca61d03f6778.JPG

**Comment by imurchie** [comment]
Seems like a reasonable thing to look into. Added to the next milestone.

**Comment by moizjv** [comment]
@invertednz  "`" yes it is available after a long press and hence sendKeys would not work. You should be using setValue instead. One way of doing it is by setting [sendKey](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md) strategy in caps to setValue. Other way is to use "setImmediateValue".

**Comment by invertednz** [comment]
Is there another way of using setvalue without changing the sendkeystrategy?  Would be good to only use setvalue where it must be used.

**Comment by bootstraponline** [comment]
> Is there another way of using setvalue without changing the sendkeystrategy?

[SetImmediateValue](https://github.com/appium/appium-dotnet-driver/blob/f9ae7a7c55dbc65ba7a2e2801a595fc7c927bcb5/appium-dotnet-driver/Appium/AppiumWebElement.cs#L79)
