### ISSUE TITLE
UiAutomator quit before it successfully launched

### ISSUE THREAD

**Issue by ashokkumarg** [appium/appium#4745]
Trying to launch the third party emulator Genymotion via Appium 1.3.4.1. But it fails.

I have done the following things.

I disable the Launch AVD from appium and launching the Genymotion AVD through the code.

I paste the overall code here:

       public static void main(String[] args) throws InterruptedException, ExecuteException, IOException {

        String deviceName = "Google Nexus 5 - 4.4.4 - API 19 - 1080x1920";

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(CapabilityType.BROWSER_NAME, ""); 
        capabilities.setCapability("deviceName","Google Nexus 5 - 4.4.4 - API 19 - 1080x1920"); 
        capabilities.setCapability("platformVersion", "4.4.4");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("app","D:/SOFTWARES/Apks/Hybrid.apk");

        DefaultExecutor executor = new DefaultExecutor();
        DefaultExecuteResultHandler resultHandler = new DefaultExecuteResultHandler();
        CommandLine launchEmul = new CommandLine("C:/Program Files/Genymobile/Genymotion/player");
        launchEmul.addArgument("--vm-name");
        launchEmul.addArgument("\""+deviceName+"\"");
        executor.setExitValue(1);
        executor.execute(launchEmul, resultHandler);
        Thread.sleep(40);
        driver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
    }

I couldn't able to start the Emulator through the code. Suggestions please.

**Comment by amedvedjev** [comment]
"Google Nexus 5 - 4.4.4 - API 19 - 1080x1920" - rename spaces to e.g. "_"

**Comment by ashokkumarg** [comment]
@amedvedjev
 It was working well for a long while. Actually I copied the folder name of the emulator from this system path:
C:\Users\ashokkumarg\AppData\Local\Genymobile\Genymotion\Genymobile\Genymotion\deployed
 I dont know what is the root cause for this.

The error log in Appium server:

> Starting Node Server
> info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"app":"D:\\SOFTWARES\\Apks\\Hybrid.apk","address":"127.0.0.1","logNoColors":true,"androidPackage":"com.htc.testApp","androidActivity":"TestApp","androidWaitPackage":"com.htc.testApp","platformName":"Android","platformVersion":"19","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"D:/SOFTWARES/Apks/Hybrid.apk","platformVersion":"4.4.4","browserName":"","platformName":"Android","deviceName":"Google Nexus 5 - 4.4.4 - API 19 - 1080x1920"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.6 (java 1.5)
> info: [debug] Using local app from desired caps: D:\SOFTWARES\Apks\Hybrid.apk
> info: [debug] Creating new appium session e51419cd-8e19-4748-9af4-fa83545fe8a5
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_31
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from D:\SOFTWARES\sdk\platform-tools\adb.exe
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] Could not find devices, restarting adb server...
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe kill-server
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe devices
> info: [debug] 0 device(s) connected
> info: [debug] Could not find devices, restarting adb server...
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe kill-server
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device 192.168.56.101:5555
> info: [debug] Setting device id to 192.168.56.101:5555
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 wait-for-device
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: Device API level is: 19
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: 
> info: [debug] java -jar "D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "D:\SOFTWARES\Apks\Hybrid.apk" "C:\Users\ASHOKK~1\AppData\Local\Temp\com.htc.testApp" 
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 push "C:\\Users\\ASHOKK~1\\AppData\\Local\\Temp\\com.htc.testApp\\strings.json" /data/local/tmp
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from D:\SOFTWARES\sdk\build-tools\android-4.2.2\aapt.exe
> info: [debug] Retrieving process from manifest.
> info: [debug] executing cmd: D:\SOFTWARES\sdk\build-tools\android-4.2.2\aapt.exe dump xmltree D:\SOFTWARES\Apks\Hybrid.apk AndroidManifest.xml
> info: [debug] Set app process to: com.htc.testApp
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Checking app cert for D:\SOFTWARES\Apks\Hybrid.apk.
> info: [debug] executing cmd: java -jar D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar D:\SOFTWARES\Apks\Hybrid.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning D:\SOFTWARES\Apks\Hybrid.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from D:\SOFTWARES\sdk\tools\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: D:\SOFTWARES\sdk\tools\zipalign.exe -f 4 D:\SOFTWARES\Apks\Hybrid.apk C:\Users\ASHOKK~1\AppData\Local\Temp\appium115220-6044-r58sfj.tmp
> info: [debug] MD5 for app is 99a830dc693e85f943ec4bf5f63ac7c1
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell "ls /data/local/tmp/99a830dc693e85f943ec4bf5f63ac7c1.apk"
> info: [debug] Getting install status for com.htc.testApp
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell "pm list packages -3 com.htc.testApp"
> info: [debug] App is not installed
> info: Installing App
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell "mkdir -p /data/local/tmp/"
> info: [debug] Removing any old apks
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell "ls /data/local/tmp/*.apk"
> info: [debug] Found an apk we want to keep at /data/local/tmp/99a830dc693e85f943ec4bf5f63ac7c1.apk
> info: [debug] Couldn't find any apks to remove
> info: [debug] Uninstalling com.htc.testApp
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell "am force-stop com.htc.testApp"
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 uninstall com.htc.testApp
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell "pm install -r /data/local/tmp/99a830dc693e85f943ec4bf5f63ac7c1.apk"
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 push "D:\\SOFTWARES\\AppiumForWindows-1.3.4.1\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 install "D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 install "D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_RESULT: shortMsg=java.lang.NullPointerException
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_RESULT: longMsg=null
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_CODE: 0
> info: [debug] UiAutomator exited
> info: [debug] executing cmd: D:\SOFTWARES\sdk\platform-tools\adb.exe -s 192.168.56.101:5555 shell "echo 'ping'"
> info: [debug] Attempting to uninstall app
> error: UiAutomator quit before it successfully launched
> error: Failed to start an Appium session, err was: Error: UiAutomator quit before it successfully launched
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Error: UiAutomator quit before it successfully launched
>     at null.<anonymous> (D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\lib\devices\android\android.js:204:23)
>     at Object.async.eachSeries (D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\async\lib\async.js:145:20)
>     at androidHybrid.stopChromedriverProxies (D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\lib\devices\android\android-hybrid.js:234:9)
>     at null.<anonymous> (D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\lib\devices\android\android.js:199:10)
>     at null.<anonymous> (D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\lib\devices\android\android.js:221:9)
>     at androidCommon.uninstallApp (D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\lib\devices\android\android-common.js:479:5)
>     at null.<anonymous> (D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\lib\devices\android\android.js:219:12)
>     at null.<anonymous> (D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\lib\devices\android\android.js:228:11)
>     at D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:890:7
>     at null.<anonymous> (D:\SOFTWARES\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:172:9)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: UiAutomator quit before it successfully launched)","origValue":"UiAutomator quit before it successfully launched"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 14525.992 ms - 218

**Comment by amedvedjev** [comment]
once again - 
1) create new Nexus5 device in Genymotion BUT name it without blanks e.g. "Nexus5_4.4.4"
2) update in code device name to new given name

**Comment by ashokkumarg** [comment]
@amedvedjev  Ok I will do it and tell you

**Comment by ashokkumarg** [comment]
@amedvedjev  I tried as you but, still the same issue is occuring.

**Comment by 0x1mason** [comment]
Please try:

1) Create your own UiAutomatorTestCase (see Google's docs on that)
2) Run your own test case with uiautomator on your device

Does it work?

**Comment by ashokkumarg** [comment]
@0x1mason  Since I use the Hybrid application, In UI Automator Viewer I couldn't able to access the properties/elements. 
![uiauto](https://cloud.githubusercontent.com/assets/7566850/6797385/500c7724-d227-11e4-8bf2-883ca2a09470.jpg)
In that case is there any use in creating the UiAutomatorTestCase?

**Comment by ashokkumarg** [comment]
Everytime I am starting the emulator manually and running the code. I couldn't able automatically invoke the emulator from the code (eclipse) or through Appium Launch AVD, Arguments.

**Comment by 0x1mason** [comment]
Does the vanilla Android emulator work?

**Comment by 0x1mason** [comment]
@tarunsujit You use Gennymotion.  Any suggestions?

**Comment by ashokkumarg** [comment]
@0x1mason  I never used the Vanilla Android Emulator before.  Currently using the Genymotion emulator.

**Comment by tarunsujit** [comment]
@ashokkumarg We can open Gennymotion by this command (This is on Mac, will be similar in Windows i guess.)
/Applications/Genymotion.app/Contents/MacOS/player --vm-name "xxxx"
You can write this in your code and open the Gennymotion Emulator.

**Comment by tarunsujit** [comment]
You can see it [here] (https://www.genymotion.com/?utm_source=dlvr.it&utm_medium=twitter#!/support?chapter=start-virtual-devices-command-prompt#faq)  for windows.

Java Code:
String cmd = <Genymotion installer path>\player --vm-name "<virtual device name>"
Runtime rt = Rintime.getRuntime() ;
Process p = rt.exec("cmd") ;

**Comment by ashokkumarg** [comment]
@tarunsujit  I have used your following code:

When the code executes the Process line an error message is flashing in the screen.


**CODE:**
    public static void main(String[] args) throws InterruptedException, ExecuteException, IOException     {
	String cmd = "C:\\Program Files\\Genymobile\\Genymotion\\player --vm-name Google Nexus 5    - 4.4.4 - API 19 - 1080x1920";
	Runtime rt = Runtime.getRuntime() ;
	**Process p = rt.exec(cmd) ;**

	DesiredCapabilities capabilities = new DesiredCapabilities();
	capabilities.setCapability(CapabilityType.BROWSER_NAME, ""); 
	capabilities.setCapability("deviceName","Google Nexus 5 - 4.4.4 - API 19 - 1080x1920");	
	capabilities.setCapability("platformVersion", "4.4.4");
	capabilities.setCapability("platformName", "Android");
	capabilities.setCapability("app","D:/SOFTWARES/Apks/Hybrid.apk");

	driver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);	
	System.out.println("SetUp is successful and Appium Driver is launched successfully");
    }


![geny2](https://cloud.githubusercontent.com/assets/7566850/6819373/21a6ae30-d2e6-11e4-8897-7dd528fed755.png)

**Comment by tarunsujit** [comment]
@ashokkumarg Then this is the problem of your Genymotion, please try to solve this issue by posting it on Genymotion website/Forum. This is not issue of Appium.
You need to open AVD from command line.

**Comment by ashokkumarg** [comment]
@tarunsujit 

I modified a little bit.
**CODE**
String deviceName = "Google Nexus 10 - 4.4.4 - API 19 - 2560x1600";
System.out.println("SetUp is started");
String cmd = "C:\\Program Files\\Genymobile\\Genymotion\\player --vm-name   \""+deviceName+"\"";
Runtime rt = Runtime.getRuntime();
Process p = rt.exec(cmd);

Now I can able to run the emulator from eclipse.

**Comment by tarunsujit** [comment]
Glad yo got this worked.

**Comment by ashokkumarg** [comment]
@tarunsujit 
But still after the emulator launches..
In the console view
A new session could not be created. (Original error: UiAutomator quit before it successfully launched) (WARNING: The server did not provide any stacktrace information)
I'm getting this error

**Comment by moizjv** [comment]
@ashokkumarg does not look as an appium issue. Can you use [Forum](http://discuss.appium.io) for such discussions? @tarunsujit Thanks!

**Comment by sachin2788** [comment]
package Appiumsample;

import static org.junit.Assert.*;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;

import org.junit.Test;
import org.openqa.selenium.remote.DesiredCapabilities;

public class desiredcap {

	@Test
	public void test() throws MalformedURLException {
	
		File appDir = new File("src");
		
//	File app = new File(appDir, "WhatsApp.apk");
		File app = new File(appDir, "BookMyShow.apk");
		
		
//		File classpathRoot = new File(System.getProperty("user.dir"));
//        File appDir = new File(classpathRoot, "E:/Selenium/WorkSpace/AppiumSample/src/");
//        File app = new File(appDir, "BookMyShow.apk");
//		
		
		
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.PLATFORM_NAME,MobilePlatform.ANDROID);
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "ANDROID EMULATOR");
	//	cap.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
		cap.setCapability(MobileCapabilityType.APP, "BookMyShow.apk");
	//	cap.setCapability(MobileCapabilityType.APP, "WhatsApp.apk");
		//Android Driver
		AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), cap);
		
		
	}

}

**Comment by sachin2788** [comment]
Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: UiAutomator quit before it successfully launched)","origValue":"UiAutomator quit before it successfully launched"},"sessionId":null}

How to resolve this

**Comment by igalep** [comment]
Same issue as well,
appium 1.4.15

**Comment by MahalakshmiSagar** [comment]
Hi,

When i run a script to install and launch a app on "Moto G4 Plus" I get the following error: 
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: UiAutomator quit before it successfully launched) (WARNING: The server did not provide any stacktrace information)

Appium Version: 1.4.16
Android version: 6.1.1

Any anyone please help me troubleshoot this issue?

Here is the Appium console log:
> Checking if an update is available
> Update not available
> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --platform-name Android --platform-version 23 --automation-name Appium --device-name "ZY223B9HBG" --log-no-color
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"deviceName":"ZY223B9HBG","platformName":"Android","platformVersion":"23","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:/Spectrum/TwctvMobileApp-adobePlayer-debug.apk","appPackage":"com.TWCableTV'","appActivity":"com.twc.android.ui.login.SplashScreen","platformVersion":"6.0.1","browserName":"","deviceOrientation":"portrait","platformName":"Android","deviceName":"ZY223B9HBG"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : deviceOrientation
> info: [debug] Using local app from desired caps: C:\Spectrum\TwctvMobileApp-adobePlayer-debug.apk
> info: [debug] Creating new appium session 3958bd74-3da5-42e8-afd4-fd89bde88a1f
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_101
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device ZY223B9HBG
> info: [debug] Setting device id to ZY223B9HBG
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG wait-for-device
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 23
> info: Device API level is: 23
> info: [debug] Extracting strings for language: default
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: 
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Spectrum\TwctvMobileApp-adobePlayer-debug.apk" "C:\Users\MAHALA~1.SAG\AppData\Local\Temp\com.TWCableTV'" 
> info: [debug] Reading strings from converted strings.json
> info: [debug] Setting language to default
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG push "C:\\Users\\MAHALA~1.SAG\\AppData\\Local\\Temp\\com.TWCableTV'\\strings.json" /data/local/tmp
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\build-tools\24.0.3\aapt.exe
> info: [debug] Retrieving process from manifest.
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\build-tools\24.0.3\aapt.exe dump xmltree C:\Spectrum\TwctvMobileApp-adobePlayer-debug.apk AndroidManifest.xml
> info: [debug] Set app process to: com.TWCableTV'
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Checking app cert for C:\Spectrum\TwctvMobileApp-adobePlayer-debug.apk.
> info: [debug] executing cmd: java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar" C:\Spectrum\TwctvMobileApp-adobePlayer-debug.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Spectrum\TwctvMobileApp-adobePlayer-debug.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\build-tools\24.0.3\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\build-tools\24.0.3\zipalign.exe -f 4 C:\Spectrum\TwctvMobileApp-adobePlayer-debug.apk C:\Users\MAHALA~1.SAG\AppData\Local\Temp\11693-10832-nkknrv\appium.tmp
> info: [debug] MD5 for app is 554108d8fbf71f5f57c8439c64227c48
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG shell "ls /data/local/tmp/554108d8fbf71f5f57c8439c64227c48.apk"
> info: [debug] Getting install status for com.TWCableTV'
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 23
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG shell "pm list packages -3 com.TWCableTV'"
> info: [debug] App is not installed
> info: Installing App
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG shell "mkdir -p /data/local/tmp/"
> info: [debug] Removing any old apks
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG shell "ls /data/local/tmp/*.apk"
> info: [debug] Found an apk we want to keep at /data/local/tmp/554108d8fbf71f5f57c8439c64227c48.apk
> info: [debug] Couldn't find any apks to remove
> info: [debug] Uninstalling com.TWCableTV'
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG shell "am force-stop com.TWCableTV'"
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG uninstall com.TWCableTV'
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG shell "pm install -r /data/local/tmp/554108d8fbf71f5f57c8439c64227c48.apk"
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.TWCableTV' -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] /system/bin/sh: no closing quote
> info: [debug] UiAutomator exited
> info: [debug] executing cmd: C:\Users\mahalakshmi.sagar\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZY223B9HBG shell "echo 'ping'"
> info: [debug] Attempting to uninstall app
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Cleaning up android objects
> error: UiAutomator quit before it successfully launched
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: UiAutomator quit before it successfully launched
> info: [debug] Error: UiAutomator quit before it successfully launched
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android.js:205:23)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-hybrid.js:249:5)
>     at Object.async.eachSeries (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:142:20)
>     at [object Object].androidHybrid.stopChromedriverProxies (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-hybrid.js:233:9)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android.js:200:10)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android.js:222:9)
>     at [object Object].androidCommon.uninstallApp (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-common.js:478:5)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android.js:220:12)
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android.js:229:11)
>     at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:901:7
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:180:9)
>     at ChildProcess.exithandler (child_process.js:742:7)
>     at ChildProcess.emit (events.js:110:17)
>     at maybeClose (child_process.js:1016:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: UiAutomator quit before it successfully launched)","origValue":"UiAutomator quit before it successfully launched"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 38457.536 ms - 218 
> Killed Node Server.
> Appium server process ended
