### ISSUE TITLE
INVALID_EXPRESSION_ERR: DOM XPath Exception 51

### ISSUE THREAD

**Issue by hardik-d** [appium/appium#4748]
ruby code:

@driver.find_element(:xpath, '//h4[starts-with(@id="payee-")]')

appium logs:

info: --> POST /wd/hub/session/4112d047-0691-4a26-be96-514f77258a36/element {"using":"xpath","value":"//h4[starts-with(@id=\"payee-\")]"}
.
.
.

info: [debug] Responding to client with error: {"status":32,"value":{"message":"Unable to locate an element with the xpath expression //h4[starts-with(@id=\"payee-\")] because of the following error:\nError: INVALID_EXPRESSION_ERR: DOM XPath Exception 51","origValue":"Unable to locate an element with the xpath expression //h4[starts-with(@id=\"payee-\")] because of the following error:\nError: INVALID_EXPRESSION_ERR: DOM XPath Exception 51"},"sessionId":"4112d047-0691-4a26-be96-514f77258a36"}

Not sure what this error means?

appium: 1.3.7 beta
iphone 6 ios8.2 simulator

**Comment by bootstraponline** [comment]
I checked in Chrome and that doesn't appear to be valid XPath.

> $x('//h4[starts-with(@id="payee-")]')
> Uncaught DOMException: Failed to execute 'evaluate' on 'Document': The string '//h4[starts-with(@id="payee-")]' is not a valid XPath expression.

**Comment by hardik-d** [comment]
sorry for not replying sooner @bootstraponline i agree it being an invalid xpath. fixed it with a css selector.
