### ISSUE TITLE
SafariLauncher on Real iOS 8.2 Device "connect ECONNREFUSED" about half of the time.

### ISSUE THREAD

**Issue by MJanach** [appium/appium#4753]
System Specs:
Appium v1.3.6
Yosemite 10.10.2
Xcode 6.2(6C131e)
iOS 8.2(12D508)

About 50% of the time Safari Launcher will launch on my iPad and navigate to a page other than Apple.com.  I can usually get it working if I close the the terminal between tests then type:
$ killall node
$ ios_webkit_debug_proxy -c xxxxxxxxxxxxxxxxxxxxxxxxxxxxx:27753
$ appium &
Then I run my code from eclipse.  It looks like the problem could be that the iPad losses its connection to the Mac during the test.

info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 0bc9fbc3731cabed9d89b6cecc2bbef4a8a8e8f7 io.appiumSafariLauncher -e UIASCRIPT "/Users/helpdesk/Library/Application Support/appium/bootstrap/bootstrap-8a852d5c6e8dd1ae.js" -e UIARESULTSPATH /tmp/appium-instruments

info: [debug] And extra without-delay env: {}

info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2015-03-22 20:26:48.098 instruments[1112:19046] WebKit Threading Violation - initial use of WebKit from a secondary thread.

Invalid message _rpc_applicationUpdated: <dict>

<key>WIRApplicationBundleIdentifierKey</key>

<string>com.apple.WebKit.WebContent</string>

<key>WIRHostApplicationIdentifierKey</key>

<string>PID:174</string>

<key>WIRApplicationNameKey</key>

<string></string>

<key>WIRIsApplicationProxyKey</key>

<true/>

<key>WIRIsApplicationActiveKey</key>

<integer>0</integer>

<key>WIRApplicationIdentifierKey</key>

<string>PID:270</string>

</dict>

Disconnected :27753 from RMurthy’s iPad (0bc9fbc3731cabed9d89b6cecc2bbef4a8a8e8f7)

When the test works I never see this "Disconnected" message in the logs.

**Comment by sebv** [comment]
The proxy frequently crashes, try with this script https://github.com/appium/appium/blob/master/bin/ios-webkit-debug-proxy-launcher.js

**Comment by sebv** [comment]
Closing, please try solution above, may be reopened if needed.
