### ISSUE TITLE
node appium throw err

### ISSUE THREAD

**Issue by seshav** [appium/appium#4754]
Unable to start 'node appium' at command line. I can start 'node' or 'appium' individually, but when we try to execute 'node appium' I get below error: I searched internet, found that I have to replace node.js file, which I did. Still I face this issue. Environment is windows7. I didn't install separate Android SDK. I installed Adroid Studio 1.1.0, I setup paths correctly in system variables. Please help 

C:\Users\sru>node appium
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\sru>appium'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by seshav** [comment]
Hi Experts,

 Any suggestions on how to overcome/fix this issues please? I am stuck with this issue and no progress.

Thanks

**Comment by imurchie** [comment]
Are you running from source? Try `node .` (that is `node` and a space and a period).

**Comment by seshav** [comment]
Hi imurchie, 
  Thank you for response. I set path for nodejs and appium in settings > environment variables.
I am able to run 'node' from any location also I can run 'appium' from any location in windows directory from command prompt. I can open Appium application and start server. Only issue I am facing is that when I try to run command 'node appium' than I get that error. I tried giving complete path of appium to that command like 'node C:\Appium\appium.exe' and also I tried running from Appium directory itself as 'C:\nodejs\node appium' . All these result in same issue. Please suggest how to get around this issue. I really appreciate your help.

Thank you
Sesha

**Comment by imurchie** [comment]
I'm confused about what you are trying to do. Have you installed the source code? Or from `npm`?

**Comment by 0x1mason** [comment]
Why do you need `node appium` if `appium` works?

Are you using the Windows gui and a separate install of Node?  If so, that's not going to work. Appium.exe uses a local installation of node rather than using the system one.  The system Node install doesn't know anything about Appium.exe.

If you have both the Appium.exe folder and a separate Node install on PATH, remove the Appium.exe directory.  Then run `npm install -g appium`.  Then you should be golden.

**Comment by jlipps** [comment]
`node appium` is not the way to launch appium. if you're trying to run appium as installed from npm, the command is `appium`. if you're trying to run appium from source (and are in the source dir), the command is `node .`.

**Comment by seshav** [comment]
Thank you for explaining. I am able to run Appium now

**Comment by bgrimes78** [comment]
If I attempt to run appium from the Jenkins executable shell as mentioned above, i get the following error

Appium will not work if used or installed with sudo. Please rerun/install as a non-root user. If you had to install Appium using `sudo npm install -g appium`, the solution is to reinstall Node using a method (Homebrew, for example) that doesn't require sudo to install global npm packages.
Build step 'Execute shell' marked build as failure

I have looked up everything I could find and I am still having no luck

**Comment by sebv** [comment]
This way is good with jenkins:

```
mkdir workdir
pushd workdir
echo "{}" > package.json
npm install appium
./node_modules/.bin/appium
```
