### ISSUE TITLE
Cannot start Appium on Windows 7

### ISSUE THREAD

**Issue by bodiam** [appium/appium#4755]
Hi all,

I'm trying to start Appium on my (unfortunately) Windows machine, but no luck so far. Whenever I start appium, I have to wait 1 second, and then it crashes. I've checked the eventviewer, and this is there:

```
    Toepassing: Appium.exe
    Framework-versie: v4.0.30319
    Beschrijving: het proces is beëindigd als gevolg van een onverwerkte uitzondering.
Uitzonderingsinformatie: System.Windows.Markup.XamlParseException
Stack:
   bij System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   bij System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   bij System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   bij System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   bij System.Windows.Application.LoadComponent(System.Uri, Boolean)
   bij System.Windows.Application.DoStartup()
   bij System.Windows.Application.<.ctor>b__1(System.Object)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   bij MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bij System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bij System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   bij System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bij System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bij System.Windows.Threading.DispatcherOperation.Invoke()
   bij System.Windows.Threading.Dispatcher.ProcessQueue()
   bij System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bij MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bij MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   bij MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bij System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   bij MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   bij MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   bij System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   bij System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   bij System.Windows.Threading.Dispatcher.Run()
   bij System.Windows.Application.RunDispatcher(System.Object)
   bij System.Windows.Application.RunInternal(System.Windows.Window)
   bij System.Windows.Application.Run(System.Windows.Window)
   bij Appium.App.Main()
```

Any suggestions I could try? 

Thanks, Erik

**Comment by 0x1mason** [comment]
Try installing .net 4.5.

**Comment by bodiam** [comment]
Thanks, but I'm a bit confused by that. I installed .net 4.5, and
installing it again says 'you already have 4.5 installed', but based on
this stacktrace it seems like it's using 4.0, right? How do I make sure
appium is really using 4.5? I also rebooted my machine, but no effect.

Thanks for the help!
Op 24 mrt. 2015 02:16 schreef "Eric Millin" <notifications@github.com>:

**Comment by 0x1mason** [comment]
I think the .net version is a red herring. A few questions:
What bitness is your OS?
What happens if you run as administrator?
Do you know how to use procmon?

**Comment by bodiam** [comment]
- My bitness is 64
- When I run as admin, I have exactly the same erro and stacktrace.
- Not very familiar with procmon, but I have it installed

I appreciate the help btw, thanks for that! Running appium on my mac works quite good, but I need to run it also on my (corporate) Windows machine. Me and 50 others :)

If there's an alternative to running the .net version, I'd be more than happy to try that.

**Comment by 0x1mason** [comment]
You can run the command line version. If you have node installed, run `npm
install -g appium`.  The `-g` is optional and signifies a global install.

Can you try this?
https://www.dropbox.com/s/75tu7fulaxhsxis/appium-installer.zip?dl=0

It's the unreleased new version of the GUI. The version number hasn't been
updated yet, so you'll get a popup when it's starts, but I want to see if
you can get that far.

On Tue, Mar 24, 2015 at 10:42 AM, Erik Pragt <notifications@github.com>
wrote:

>
>    - My bitness is 64
>    - When I run as admin, I have exactly the same erro and stacktrace.
>    - Not very familiar with procmon, but I have it installed
>
> I appreciate the help btw, thanks for that! Running appium on my mac works
> quite good, but I need to run it also on my (corporate) Windows machine. Me
> and 50 others :)
>
> If there's an alternative to running the .net version, I'd be more than
> happy to try that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/4755#issuecomment-85534353>.
>



-- 

*Eric Millin*
*Software Engineer, Ecosystems*
Twitter: @etmillin <http://twitter.com/jlipps>
GitHub: @0x1mason <https://github.com/jlipps>
Sauce Labs <http://saucelabs.com/> | Sauce blog <http://sauceio.com/>

**Comment by vietnq254** [comment]
Appium.exe for Windows:
[https://bitbucket.org/appium/appium.app/downloads/](https://bitbucket.org/appium/appium.app/downloads/)

**Comment by moizjv** [comment]
@bodiam i hope it worked for you on windows. I am closing this issue. If you think its still an defect raise it in [appium-dot-exe](https://github.com/appium/appium-dot-exe/issues) project. Thanks

**Comment by bodiam** [comment]
Hi @moizjv , thanks for the help. I didn't have the need for running appium on Windows for a while, but I tested the latest version, and it works. But is it also possible to start appium without the GUI?
