### ISSUE TITLE
Appium 1.3.4: Get error "target application is not frontmost" after long time run on real device

### ISSUE THREAD

**Issue by derek1106** [appium/appium#4756]
We have iOS devices like iPhone OS 6 and iPhone OS 7.
At first, we can run the Safari browser test on these devices with Appium 1.3.4.
But after running test for a long time, maybe 3 weeks or 1 month. We get the error "target application is not frontmost".

It seems Appium 1.3.4 left some things on the device since I still can use Appium 1.1.0 run the same test.
So I'd like to get some recommendations from you.
1. Where I need to look into to find the garbage?
2. How to cleanup the device to make it back to normal?

Here are what I tried and confirmed.
1. There is no any popup dialog when running test since this error maybe caused by popup dialog.
2. Restart device, no help.
3. Clear device console log, no help.

**Comment by tarunsujit** [comment]
Couple of things I can suggest here,
1. Try with the latest Appium
2. Try running with "fullReset" capability

**Comment by derek1106** [comment]
I tried with Appium 1.3.6 and "fullReset", but no any help.
I still get the error "target application is not frontmost".

**Comment by derek1106** [comment]
I can use Appium 1.1.0 to run test on the same device, but Appium 1.3.4 cannot.
In fact, when running test with Appium 1.1.0 and 1.3.4, from the log, we can see that both of them get the error "target application is not frontmost".
But reaction behavior is different.
Appium 1.1.0 doesn't do anything and continue to run test.
Appium 1.3.4 kills the instruments and fail the test run.

Why we made the change in Appium 1.3.4? What does the error "target application is not frontmost" stand for?

**Comment by 0x1mason** [comment]
Do you see this behavior with 1.3.7?

**Comment by derek1106** [comment]
Appium 1.3.7 is bad, it will give this kind of error as below.
Could not get the iOS SDK version because the Xcode version could not be determined

Check it from here, https://discuss.appium.io/t/appium-1-3-7-release/3547/14.

**Comment by derek1106** [comment]
Can you guys answer my question directly?

When running test with Appium 1.1.0 and 1.3.4, from the log, we can see that both of them get the error "target application is not frontmost".
But reaction behavior is different.
Appium 1.1.0 doesn't do anything and continue to run test.
Appium 1.3.4 kills the instruments and fail the test run.

Why we made the change in Appium 1.3.4? Oh, it's started from Appium 1.2.1.
What does the error "target application is not frontmost" stand for?

**Comment by 0x1mason** [comment]
Can you tell me more? Does it always give you that error?  What does
`xcode-select --print-path` return?

The "target application..." message could be related to a known issue with
Xcode 5. http://stackoverflow.com/a/20702535  The message also occurs when
a popup forces your application into the background.

Please provide logs and provide information that might help me reproduce
the issues you mention.

Appium 1.3.7 is bad, it will give this kind of error as below.
Could not get the iOS SDK version because the Xcode version could not be
determined

Check it from here, https://discuss.appium.io/t/appium-1-3-7-release/3547/14
.

—
Reply to this email directly or view it on GitHub
<https://github.com/appium/appium/issues/4756#issuecomment-91702652>.

**Comment by derek1106** [comment]
OK, let me say the issue again.

Device: IOS 6 and 7 devices
Xcode: version 5.1.1
Running test with Appium 1.1.0, it's Pass.
Running test with Appium 1.2.1 and 1.3.4, get the error "target application is not frontmost".
Note: There is no any popup dialog.

In fact, when running test with Appium 1.1.0 and 1.3.4, from the log, we can see that both of them get the error "target application is not frontmost".
But reaction behavior is different.
Appium 1.1.0 doesn't do anything and continue to run test.
Appium 1.2.1 and 1.3.4 kill the instruments and fail the test run.

So from Appium 1.2.1, we made the change to kill the instruments if get the error "target application is not frontmost".
Question 1: Why we make this kind of change?
Question 2: If I want to ignore the error "target application is not frontmost" like Appium 1.1.0, what I should change in Appium 1.2.1 and 1.3.4?

Why we made the change in Appium 1.3.4? Oh, it's started from Appium 1.2.1.
What does the error "target application is not frontmost" stand for?

**Comment by derek1106** [comment]
Ping...
Could you please answer my question? I appreciate it.

**Comment by raldred** [comment]
I'm getting the same issue but I've appium 1.3.7 and current latest master.
Log: https://gist.github.com/raldred/84c8999bfd1269f0fc90

I'm using Xcode 5.1.1 using the Ruby appium_lib to talk to an iPhone 4 running 6.1.3.


		desired_caps = {
			caps: {
				platformName: 'iOS',
				udid: device[:id],
				browserName: 'Safari',
				app: 'safari',
				deviceName: device[:model],
				device: device[:type],
				newCommandTimeout: 0
			},
			appium_lib: {
				sauce_username: nil,
				sauce_access_key: nil
			}
		}
		device[:driver] = Appium::Driver.new(desired_caps).start_driver

**Comment by jlipps** [comment]
omit the `app` capability if you're using `browserName`. they can't be used together

**Comment by raldred** [comment]
@jlipps thanks, I've tried using them both separated, it doesn't make any difference, I still get the same error: `Fail: Could not start script, target application is not frontmost.`

**Comment by jlipps** [comment]
@raldred please paste in your appium log

**Comment by raldred** [comment]
@jlipps https://gist.github.com/raldred/84c8999bfd1269f0fc90
just fyi everything works fine, with my ipad 2 running 6.1.3, same appium, same ruby test code

**Comment by jlipps** [comment]
@raldred can you try with master? there were some fixes for safarilauncher from @Jonahss that might help with this case

**Comment by raldred** [comment]
thanks @jlipps unfortunately it seems I'm getting exactly the same error with appium master.
I ran ./reset.sh which completed successfully.

New appium log:
https://gist.github.com/raldred/c23ef36955368a0912a7

**Comment by raldred** [comment]
I just tried again and it got further... but failed with error: `Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using`

    info: [debug] Socket data received (8158 bytes)
    info: [debug] Socket data received (8190 bytes)
    info: [debug] Socket data received (1118 bytes)
    info: [debug] Socket data being routed.
    info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"Safari","label":"Safari","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":20,"width":320,"height":460},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"vali
    info: [debug] On Safari Launcher. Tapping button to launch Safari
    info: [debug] Waiting up to 0ms for condition
    info: [debug] Pushing command to appium work queue: "au.getElementByAccessibilityId('launch safari')"
    info: [debug] Sending command to instruments: au.getElementByAccessibilityId('launch safari')
    info: [debug] [INST] 2015-05-06 10:43:40 +0000 Debug: Got new command 2 from instruments: au.getElementByAccessibilityId('launch safari')
    info: [debug] [INST] 2015-05-06 10:43:40 +0000 Debug: evaluating au.getElementByAccessibilityId('launch safari')
    info: [debug] [INST] 2015-05-06 10:43:40 +0000 Debug: evaluation finished
    info: [debug] [INST] 2015-05-06 10:43:40 +0000 Debug: responding with:
    info: [debug] [INST] 2015-05-06 10:43:40 +0000 Debug: Running system command #3: /usr/local/Cellar/node010/0.10.38_1/bin/node /Users/robaldred/Repos/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
    info: [debug] Socket data received (25 bytes)
    info: [debug] Socket data being routed.
    info: [debug] Got result from instruments: {"status":0,"value":""}
    info: [debug] Condition unmet after 1417ms. Timing out.
    error: Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using
    info: [debug] Cleaning up appium session
    error: Failed to start an Appium session, err was: Error: Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using
    info: [debug] Error: Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using
        at [object Object].<anonymous> (/Users/robaldred/Repos/appium/lib/devices/ios/safari.js:70:17)
        at [object Object].<anonymous> (/Users/robaldred/Repos/appium/lib/devices/common.js:77:12)
        at [object Object].iOSController.handleFindCb (/Users/robaldred/Repos/appium/lib/devices/ios/ios-controller.js:303:5)
        at [object Object].<anonymous> (/Users/robaldred/Repos/appium/lib/devices/ios/ios-controller.js:128:14)
        at next (/Users/robaldred/Repos/appium/node_modules/async/lib/async.js:801:43)
        at /Users/robaldred/Repos/appium/node_modules/async/lib/async.js:32:16
        at [object Object].exports.respond (/Users/robaldred/Repos/appium/lib/devices/common.js:28:9)
        at [object Object].<anonymous> (/Users/robaldred/Repos/appium/lib/devices/ios/ios.js:1473:18)
        at getResultAndSendNext (/Users/robaldred/Repos/appium/node_modules/appium-uiauto/lib/command-proxy.js:146:20)
        at Socket.<anonymous> (/Users/robaldred/Repos/appium/node_modules/appium-uiauto/lib/command-proxy.js:88:7)
        at Socket.emit (events.js:117:20)
        at _stream_readable.js:944:16
        at process._tickDomainCallback (node.js:492:13)
    info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using)","origValue":"Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using"},"sessionId":null}
    info: <-- POST /wd/hub/session 500 14644.712 ms - 378 
    info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","udid":"e509d0d6176d8277b8235c7f15aee0b6fc9a2420","browserName":"Safari","deviceName":"iPhone 4","device":"iphone","newCommandTimeout":0}}

**Comment by Jonahss** [comment]
There's a new version of SafariLauncher. Appium installs it automatically, but will not install it if you already have an older version of SafariLauncher on your device. Delete SafariLauncher from your device and run `reset.sh --real-safari`

**Comment by raldred** [comment]
Thanks @Jonahss i'll give that a try in the morning.

**Comment by raldred** [comment]
@Jonahss @jlipps ./reset.sh --real-safari fixed it!
Thanks

**Comment by Jonahss** [comment]
^.^
