### ISSUE TITLE
Could not parse xcode version. Could not get the iOS SDK version because the Xcode version could not be determined.

### ISSUE THREAD

**Issue by Changdeo** [appium/appium#4758]
Hi,
I am using appium for iOS application testing. Intermittently, I face following exception

error: Failed to start an Appium session, err was: Error: Could not get the iOS SDK version because the Xcode version could not be determined.
info: [debug] Error: Could not get the iOS SDK version because the Xcode version could not be determined.
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/xcode.js:62:10
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/xcode.js:44:13
    at ChildProcess.exithandler (child_process.js:652:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

I checked xcode.js line number 44. It uses xcodebuild command to determine xcode version. I checked "xcodebuild -version" command returns correct result all the time. 

I have added some more logs in xcode.js around the failing line, and it seems that "xcodebuild -version" returns emtpy string sometimes and that causes the issue.
Shall we add retries here to get correct xcode version.

**Comment by sebv** [comment]
@Jonahss has been doing some work on this.

**Comment by Jonahss** [comment]
We should already have retries. Are you using Appium v1.4.1?

**Comment by sebv** [comment]
Closing, old issue,may be reopened if needed.
