### ISSUE TITLE
[Android][Appium 1.3.6] Appium does not support to enter Unicode for EditText

### ISSUE THREAD

**Issue by vietnq254** [appium/appium#4760]
Hello,

I tried to enter Unicode strings for an EditText element, but it cannot work:
```
editText.sendKeys("ÀÁÂÃÄÅÇÑñÇçÈÉÊËÌÍÎÏÒÓÔÕÖØÙÚÛÜ");
or
editText.sendKeys("Ýàáâãäåçèéêëìíîïðòóôõöøùúûüýÿ");
```
After running the above command, the EditText element was empty.

**Comment by imurchie** [comment]
Have you followed these instructions? https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/unicode.md

**Comment by vietnq254** [comment]
Thank you very much!
It work for me:
```
capabilities.setCapability("unicodeKeyboard", true);
```
