### ISSUE TITLE
click() not working on ios device with 8.0 

### ISSUE THREAD

**Issue by Anishohri** [appium/appium#4767]
Hi 

Please guide me here, i have a object with a accessibility id "Flow button" but when i try to click () it a server side error occurs and script stops. below is the appium logs:

info: --> POST /wd/hub/session/b70df1d3-fbb8-4d01-87be-aafab67cedc2/element {"using":"accessibility id","value":"Flow Button"}

info: [debug] Waiting up to 0ms for condition

info: [debug] Pushing command to appium work queue: "au.getElementByAccessibilityId('Flow Button')"
info: [debug] Sending command to instruments: au.getElementByAccessibilityId('Flow Button')

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"b70df1d3-fbb8-4d01-87be-aafab67cedc2"}

info: <-- GET /wd/hub/status 200 0.964 ms - 178 {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"b70df1d3-fbb8-4d01-87be-aafab67cedc2"}

info: [debug] [INST] 2015-03-24 20:20:47 +0000 Debug: Got new command 3 from instruments: au.getElementByAccessibilityId('Flow Button')

info: [debug] [INST] 2015-03-24 20:20:47 +0000 Debug: evaluating au.getElementByAccessibilityId('Flow Button')

info: [debug] [INST] 2015-03-24 20:20:48 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-03-24 20:20:48 +0000 Debug: Lookup returned [object UIAElement] with the name "Flow Button" (id: 0).

info: [debug] [INST] 2015-03-24 20:20:48 +0000 Debug: responding with:
info: [debug] [INST] 2015-03-24 20:20:48 +0000 Debug: Running system command #4: /usr/local/bin/node /Applications/Appium 9.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"0"}}...

info: [debug] Socket data received (38 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"0"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"0"},"sessionId":"b70df1d3-fbb8-4d01-87be-aafab67cedc2"}

info: <-- POST /wd/hub/session/b70df1d3-fbb8-4d01-87be-aafab67cedc2/element 200 694.942 ms - 87 {"status":0,"value":{"ELEMENT":"0"},"sessionId":"b70df1d3-fbb8-4d01-87be-aafab67cedc2"}

info: --> POST /wd/hub/session/b70df1d3-fbb8-4d01-87be-aafab67cedc2/element/0/click {"id":"0"}

info: [debug] Pushing command to appium work queue: "au.getElement('0').rect()"
info: [debug] Sending command to instruments: au.getElement('0').rect()

info: [debug] [INST] 2015-03-24 20:20:49 +0000 Debug: Got new command 4 from instruments: au.getElement('0').rect()

info: [debug] [INST] 2015-03-24 20:20:49 +0000 Debug: evaluating au.getElement('0').rect()

info: [debug] [INST] 2015-03-24 20:20:49 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-03-24 20:20:49 +0000 Debug: responding with:
info: [debug] [INST] 2015-03-24 20:20:49 +0000 Debug: Running system command #5: /usr/local/bin/node /Applications/Appium 9.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"origin":{"x":3.9999139308929443,"y":3.9999160766601562},"size":{"width":32.00016784667969,"height":32.00016784667...

info: [debug] Socket data received (143 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"origin":{"x":3.9999139308929443,"y":3.9999160766601562},"size":{"width":32.00016784667969,"height":32.00016784667969}}}

info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","origValue":"connect ECONNREFUSED"},"sessionId":"b70df1d3-fbb8-4d01-87be-aafab67cedc2"}
info: <-- POST /wd/hub/session/b70df1d3-fbb8-4d01-87be-aafab67cedc2/element/0/click 500 948.127 ms - 293 

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"b70df1d3-fbb8-4d01-87be-aafab67cedc2"}
info: <-- GET /wd/hub/status 200 1.278 ms - 178 {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"b70df1d3-fbb8-4d01-87be-aafab67cedc2"}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"b70df1d3-fbb8-4d01-87be-aafab67cedc2"}

info: <-- GET /wd/hub/status 200 1.193 ms - 178 {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"b70df1d3-fbb8-4d01-87be-aafab67cedc2"}

Any would be greatly appreciated.

**Comment by Anishohri** [comment]
Complete logs from appium 1.3.6

Launching Appium with command: '/usr/local/bin/node' lib/server/main.js --address "127.0.0.1" --command-timeout "7200" --robot-address "0.0.0.0" --robot-port "4" --platform-version "8.1" --platform-name "iOS" --app "/Users/anish_ohri/Desktop/anishtest.ipa" --udid "922d63b60a99bba57c882508d3aff00b8aad665b" --full-reset --device-name "iPad Retina" --launch-timeout "90000" --native-instruments-lib --platform-version 8.0 --platform-version 8.1 

info: Welcome to Appium v1.3.6 (REV 004f52f249d3513809e7d0734d9205d1fec19f8e)

info: Appium REST http interface listener started on 127.0.0.1:4723
info: [debug] Non-default server args: {"app":"/Users/anish_ohri/Desktop/anishtest.ipa","udid":"922d63b60a99bba57c882508d3aff00b8aad665b","address":"127.0.0.1","fullReset":true,"launchTimeout":"90000","nativeInstrumentsLib":true,"deviceName":"iPad Retina","platformName":"iOS","platformVersion":"8.1","robotPort":4,"defaultCommandTimeout":7200}
info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: <-- GET /wd/hub/status 200 4.044 ms - 104 {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: <-- GET /wd/hub/status 200 0.949 ms - 104 {"status":0,"value":{"build":{"version":"1.3.6","revision":"004f52f249d3513809e7d0734d9205d1fec19f8e"}}}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"8.1","app":"/Users/anish_ohri/Desktop/anishtest.ipa","platformName":"iOS","deviceName":"iPad Retina","nativeWebTap":true,"appium-version":"1.0"}}

info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)

info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : appium-version
info: [debug] Using local .ipa from desired caps: /Users/anish_ohri/Desktop/anishtest.ipa
info: [debug] Copying local zip to tmp dir

info: [debug] /Users/anish_ohri/Desktop/anishtest.ipa copied to /var/folders/km/hhmgr13937s6c696vqc0s7m00000gp/T/115224-18096-5lmkit/appium-app.zip
info: [debug] Unzipping /var/folders/km/hhmgr13937s6c696vqc0s7m00000gp/T/115224-18096-5lmkit/appium-app.zip
info: [debug] Testing zip archive: /var/folders/km/hhmgr13937s6c696vqc0s7m00000gp/T/115224-18096-5lmkit/appium-app.zip

info: [debug] Zip archive tested clean

info: [debug] Unzip successful

info: [debug] Using locally extracted app: /var/folders/km/hhmgr13937s6c696vqc0s7m00000gp/T/115224-18096-5lmkit/Payload/container.app
info: [debug] Creating new appium session 1cf58cfa-df9d-47bb-a325-4fb458e752b4

info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 8.1

info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim

info: [debug] Could not parse plist file (as binary) at /var/folders/km/hhmgr13937s6c696vqc0s7m00000gp/T/115224-18096-5lmkit/Payload/container.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /var/folders/km/hhmgr13937s6c696vqc0s7m00000gp/T/115224-18096-5lmkit/Payload/container.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/anish_ohri/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/Applications/Appium 7.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/anish_ohri/Library/Application Support/appium/bootstrap/bootstrap-2a99743bc0c21ac5.js
info: [debug] Reusing dynamic bootstrap: /Users/anish_ohri/Library/Application Support/appium/bootstrap/bootstrap-2a99743bc0c21ac5.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPad Retina","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Retina (8.1 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons

info: [debug] On a real device; cannot clean device state

info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole

info: [debug] Not pre-launching simulator

info: [debug] Creating iDevice object with udid 922d63b60a99bba57c882508d3aff00b8aad665b
info: [debug] Checking app install status using: /Applications/Appium 7.app/Contents/Resources/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id 922d63b60a99bba57c882508d3aff00b8aad665b --bundle dk.area9.container

info: [debug] App is not installed. Will try to install the app.
info: [debug] Installing ipa found at /Users/anish_ohri/Desktop/anishtest.ipa
info: [debug] Creating iDevice object with udid 922d63b60a99bba57c882508d3aff00b8aad665b

info: [debug] Nothing found on device, going ahead and installing.

info: [debug] Starting command proxy.

info: [debug] Instruments socket server started at /tmp/instruments_sock

info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 922d63b60a99bba57c882508d3aff00b8aad665b
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 922d63b60a99bba57c882508d3aff00b8aad665b dk.area9.container -e UIASCRIPT "/Users/anish_ohri/Library/Application Support/appium/bootstrap/bootstrap-2a99743bc0c21ac5.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2015-03-24 16:25:25.140 instruments[18127:5d03] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: Instruments is ready to receive commands

info: [debug] Instruments launched. Starting poll loop for new commands.
info: [debug] Setting bootstrap config keys/values
info: [debug] Pushing command to appium work queue: "target = $.target();\nau = $;\n$.isVerbose = true;\n"

info: [debug] Socket data received (2 bytes)
info: [debug] Socket data being routed.
info: [debug] Sending command to instruments: target = $.target();
au = $;
$.isVerbose = true;


info: [debug] [INST] 2015-03-24 20:25:24 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-03-24 20:25:24 +0000 Debug: responding with:
info: [debug] [INST] 2015-03-24 20:25:24 +0000 Debug: Running system command #1: /usr/local/bin/node /Applications/Appium 7.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":true}...

info: [debug] Socket data received (27 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":true}
info: [debug] Setting initial orientation to PORTRAIT
info: [debug] Pushing command to appium work queue: "au.setScreenOrientation('PORTRAIT')"
info: [debug] Sending command to instruments: au.setScreenOrientation('PORTRAIT')

info: [debug] [INST] 2015-03-24 20:25:25 +0000 Debug: Got new command 1 from instruments: au.setScreenOrientation('PORTRAIT')

info: [debug] [INST] 2015-03-24 20:25:25 +0000 Debug: evaluating au.setScreenOrientation('PORTRAIT')

info: [debug] [INST] 2015-03-24 20:25:25 +0000 Debug: target.setDeviceOrientation("1")

info: [debug] [INST] 2015-03-24 20:25:26 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-03-24 20:25:26 +0000 Debug: responding with:

info: [debug] [INST] 2015-03-24 20:25:26 +0000 Debug: Running system command #2: /usr/local/bin/node /Applications/Appium 7.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"PORTRAIT"}...

info: [debug] Socket data received (33 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":"PORTRAIT"}
info: [debug] Waiting for app source to contain elements
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"

info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-03-24 20:25:27 +0000 Debug: Got new command 2 from instruments: au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-03-24 20:25:27 +0000 Debug: evaluating au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-03-24 20:25:27 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-03-24 20:25:27 +0000 Debug: responding with:ll,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0","x":0,"y":0,"width":768,"height":1024},">":[{"UIAElement":{"@":{"name":"Flow Button","label":"Flow Button","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0","x":4,"y":4,"width":32,"height":32},">":[]}},{"UIAScrollView":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/1","x":0,"y":0,"width":768,"height":1024},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/1/0","x":764.5,"y":-36,"width":3.5,"height":36},">":[]}},{"UIAWebView":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/1/1","x":0,"y":0,"width":768,"height":1024},">":[{"UIAImage":{"@":{"name":"Header-Logo","label":"Header-Logo","value":"","dom":{"id":""},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/1/1/0","x":227,"y":59,"width":316,"height":56},">":[]}},{"UIATextField":{"@":{"name":null,"label":null,"value":"E mail","dom":{"id":"ember385"},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/1/1/1","x":229,"y":145,"width":312,"height":57},">":[]}},{"UIASecureTextField":{"@":{"name":null,"label":null,"value":"Password","dom":{"id":"ember386"},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/1/1/2","x":229,"y":202,"width":312,"height":58},">":[]}},{"UIAButton":{"@":{"name":"SIGN IN","label":"SIGN IN","value":"","dom":{"id":""},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/1/1/3","x":227,"y":290,"width":316,"height":49},">":[]}},{"UIALink":{"@":{"name":"Forgot your password?","label":"Forgot your password?","value":"","dom":{"id":""},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/1/1/4","x":291,"y":369,"width":186,"height":20},">":[{"UIAStaticText":{"@":{"name":"Forgot your password?","label":"Forgot your password?","value":"","dom":{"id":""},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/1/1/4/0","x":291,"y":369,"width":186,"height":20},">":[]}}]}},{"UIAImage":{"@":{"name":"Footer-Logo","label":"Footer-Logo","value":"","dom":{"id":""},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/1/1/5","x":15,"y":959,"width":50,"height":50},">":[]}},{"UIALink":{"@":{"name":"McGraw-Hill Campus users sign in here →","label":"McGraw-Hill Campus users sign in here →","value":"","dom":{"id":""},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/1/1/6","x":240,"y":959,"width":289,"height":43},">":[]}}]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/1/2","x":-36,"y":1020.5,"width":36,"height":3.5},">":[]}}]}}]}},{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/1","x":0,"y":0,"width":768,"height":1024},">":[{"UIAStatusBar":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/1/0","x":0,"y":0,"width":768,"height":0},">":[]}}]}}]}}}

info: [debug] [INST] 2015-03-24 20:25:27 +0000 Debug: Running system command #3: /usr/local/bin/node /Applications/Appium 7.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"Container","label":"Container","value":null,"dom":null,"enabled":true,"valid":true,...

info: [debug] Socket data received (3564 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"Container","label":"Container","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":0,"width":768,"height":1024},">":[{"UIAWindow":{"@":{"name":"Flow Main Window","label":"Flow Main Window","value":nu
info: [debug] Device launched! Ready for commands
info: [debug] Setting command timeout to the default of 7200 secs
info: [debug] Appium session started with sessionId 1cf58cfa-df9d-47bb-a325-4fb458e752b4
info: <-- POST /wd/hub/session 303 12782.282 ms - 9 

info: --> GET /wd/hub/session/1cf58cfa-df9d-47bb-a325-4fb458e752b4 {}
info: [debug] Responding to client with success: {"status":0,"value":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"iOS","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"platformVersion":"8.1","app":"/Users/anish_ohri/Desktop/anishtest.ipa","platformName":"iOS","deviceName":"iPad Retina","nativeWebTap":true,"appium-version":"1.0"},"platformVersion":"8.1","app":"/Users/anish_ohri/Desktop/anishtest.ipa","platformName":"iOS","deviceName":"iPad Retina","nativeWebTap":true,"appium-version":"1.0"},"sessionId":"1cf58cfa-df9d-47bb-a325-4fb458e752b4"}
info: <-- GET /wd/hub/session/1cf58cfa-df9d-47bb-a325-4fb458e752b4 200 1.211 ms - 624 {"status":0,"value":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"iOS","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"platformVersion":"8.1","app":"/Users/anish_ohri/Desktop/anishtest.ipa","platformName":"iOS","deviceName":"iPad Retina","nativeWebTap":true,"appium-version":"1.0"},"platformVersion":"8.1","app":"/Users/anish_ohri/Desktop/anishtest.ipa","platformName":"iOS","deviceName":"iPad Retina","nativeWebTap":true,"appium-version":"1.0"},"sessionId":"1cf58cfa-df9d-47bb-a325-4fb458e752b4"}

info: --> POST /wd/hub/session/1cf58cfa-df9d-47bb-a325-4fb458e752b4/element {"using":"accessibility id","value":"Flow Button"}

info: [debug] Waiting up to 0ms for condition

info: [debug] Pushing command to appium work queue: "au.getElementByAccessibilityId('Flow Button')"
info: [debug] Sending command to instruments: au.getElementByAccessibilityId('Flow Button')

info: [debug] [INST] 2015-03-24 20:25:52 +0000 Debug: Got new command 3 from instruments: au.getElementByAccessibilityId('Flow Button')

info: [debug] [INST] 2015-03-24 20:25:52 +0000 Debug: evaluating au.getElementByAccessibilityId('Flow Button')

info: [debug] [INST] 2015-03-24 20:25:52 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-03-24 20:25:52 +0000 Debug: Lookup returned [object UIAElement] with the name "Flow Button" (id: 0).

info: [debug] [INST] 2015-03-24 20:25:52 +0000 Debug: responding with:
info: [debug] [INST] 2015-03-24 20:25:52 +0000 Debug: Running system command #4: /usr/local/bin/node /Applications/Appium 7.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"0"}}...

info: [debug] Socket data received (38 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"0"}}

info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"0"},"sessionId":"1cf58cfa-df9d-47bb-a325-4fb458e752b4"}
info: <-- POST /wd/hub/session/1cf58cfa-df9d-47bb-a325-4fb458e752b4/element 200 1030.474 ms - 87 {"status":0,"value":{"ELEMENT":"0"},"sessionId":"1cf58cfa-df9d-47bb-a325-4fb458e752b4"}

info: --> POST /wd/hub/session/1cf58cfa-df9d-47bb-a325-4fb458e752b4/element/0/click {"id":"0"}
info: [debug] Pushing command to appium work queue: "au.getElement('0').rect()"
info: [debug] Sending command to instruments: au.getElement('0').rect()

info: [debug] [INST] 2015-03-24 20:25:53 +0000 Debug: Got new command 4 from instruments: au.getElement('0').rect()

info: [debug] [INST] 2015-03-24 20:25:53 +0000 Debug: evaluating au.getElement('0').rect()

info: [debug] [INST] 2015-03-24 20:25:53 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-03-24 20:25:53 +0000 Debug: responding with:
info: [debug] [INST] 2015-03-24 20:25:53 +0000 Debug: Running system command #5: /usr/local/bin/node /Applications/Appium 7.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"origin":{"x":3.9999101161956787,"y":3.999908447265625},"size":{"width":32.000179290771484,"height":32.00017929077...

info: [debug] Socket data received (144 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"origin":{"x":3.9999101161956787,"y":3.999908447265625},"size":{"width":32.000179290771484,"height":32.000179290771484}}}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","origValue":"connect ECONNREFUSED"},"sessionId":"1cf58cfa-df9d-47bb-a325-4fb458e752b4"}
info: <-- POST /wd/hub/session/1cf58cfa-df9d-47bb-a325-4fb458e752b4/element/0/click 500 941.680 ms - 293

**Comment by sebv** [comment]
Looks like your app crashes when you click the button.

**Comment by Anishohri** [comment]
This was resolved by some changes on my end. we can close it.

**Comment by rucindrea** [comment]
@Anishohri what was the change you made on your side? I am having the exact same problem and can't figure out why. Thanks!

**Comment by majdy86** [comment]
@Anishohri if there is an changes on your end so please tell us how to solve this issue because i got same issue suddenly after updating my xCode and Mac OS.

**Comment by Pushpank** [comment]
hi, am facing  the same issue can any one pls suggest me ?
