### ISSUE TITLE
Unable to launch or use genymotion android emulator

### ISSUE THREAD

**Issue by chandrakanth1984** [appium/appium#4769]
Hi, 

We successfully used appium for iOS testing and we are trying to use genymotion android emulator for testing. But we are unable to start or launch emulator and console is showing below error,

error: Unable to start Emulator: PANIC: HOME is defined but could not find Google Nexus 5 - 4.4.4 - API 19 - 1080x1920.ini file in $HOME/.android/avd
(Note: avd is searched in the order of $ANDROID_AVD_HOME,$ANDROID_SDK_HOME/.android/avd and $HOME/.android/avd)

**Comment by tarunsujit** [comment]
@chandrakanth1984 Are trying to open Genymotion from your Code? if Yes, then this might help you #4745

**Comment by chandrakanth1984** [comment]
No, using appium-dot-app or appium properties not through code.

**Comment by imurchie** [comment]
You would probably be better served by asking on the [Appium discuss list](https://discuss.appium.io/). We don't have any particular expertise with Genymotion. I know people have used it, but we have not tested it.
