### ISSUE TITLE
Unable to find the Webview elements in Hybrid Application

### ISSUE THREAD

**Issue by ashokkumarg** [appium/appium#4770]
I have used the following code for a login page:

**CODE**
	public static void Login() throws InterruptedException
	{	
	  Set<String> contextNames = driver.getContextHandles();
	    for (String contextName : contextNames)
	    {
	    	System.out.println(contextName);    
	    	
	    	if (contextName.contains("WEBVIEW"))
	    	{
		     	driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS); 
		     	System.out.println("Enterted in to Webview"); 
	
		     	driver.findElement(By.id("txtUserName")).sendKeys("test1@gmail.com");
		     	driver.findElement(By.id("txtPassword")).sendKeys("test1");
		     	driver.findElement(By.id("btnLogin")).click();  
	    	}
	    }
	}

The error is occuring in the txtUserName line.

**Console Error:**
An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)

**Comment by ashokkumarg** [comment]
@tarunsujit  can you give some suggestions here?

**Comment by vietnq254** [comment]
You must switch to WebView first:
```
public static void Login() throws InterruptedException
{
	Set contextNames = driver.getContextHandles();
	for (String contextName : contextNames)
	{
		System.out.println(contextName);

		if (contextName.contains("WEBVIEW"))
		{
			driver.context(contextName);
			...
		}
    }
}
```

**Comment by ashokkumarg** [comment]
@vietnq254  Yes look at my code. I have switched to webview and then I'm trying to do the further events.

Even I used your above code, it is not working.

**Comment by ashokkumarg** [comment]
@0x1mason  Can you give any suggestions??

**Comment by 0x1mason** [comment]
@vietnq254 is correct. Note the `driver.context` invocation missing from your code. Once you've corrected that, double check  your locators and then share your Appium log.

**Comment by ashokkumarg** [comment]
@vietnq254 @0x1mason  Thank you very much it works :+1:
