### ISSUE TITLE
zipalign apk failed error while automating app

### ISSUE THREAD

**Issue by vikki978** [appium/appium#4772]
Hi,

I am automating a native app with appium.
I have following desired capabilities
             File appDir = new File("D:/Mobile_Testing");
        File app = new File(appDir, "Sop_2.1.1.apk");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
        capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
        capabilities.setCapability(MobileCapabilityType.VERSION,"4.4.2");
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 120);
        capabilities.setCapability(MobileCapabilityType.APP_WAIT_ACTIVITY, 1200);
        driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

While executing test i am getting following error:

 ERROR: D:\Mobile_Testing\adt\build-tools\19.1.0\zipalign.exe -f 4 "D:\Mobile_Testing\Sop_2.1.1.apk" "C:\Users\Dell\AppData\Local\Temp\appium115225-5224-whwz24.tmp"

> warn: Zip alignment utility
> Copyright (C) 2009 The Android Open Source Project
> 
> Usage: zipalign [-f] [-v] <align> infile.zip outfile.zip
>        zipalign -c [-v] <align> infile.zip
> 
>   <align>: alignment in bytes, e.g. '4' provides 32-bit alignment
>   -c: check alignment only (does not modify file)
>   -f: overwrite existing outfile.zip
>   -v: verbose output
> 
> info: Stopping logcat capture
> ERROR: debug: Logcat terminated with code null, signal SIGTERM
> info: Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> ERROR: error: Failed to start an Appium session, err was: Error: zipAlignApk failed. Error: Command failed: Zip alignment utility

I can run the zipalign command successfully on command prompt.

**Comment by jhuska** [comment]
I am getting similar (or same) exception when running tests on real devices. 

I pull the Appium master recently. With the same settings I was able to run the tests with older Appium, thus I suspect it a regression.

My error logs (executing on Linux):
```
[33mwarn[39m: Unable to open '/tmp/apks/app-debug-qe.apk' as zip archive

[36minfo[39m: [debug] Stopping logcat capture
[36minfo[39m: [debug] Logcat terminated with code null, signal SIGTERM
[36minfo[39m: [debug] Sent shutdown command, waiting for UiAutomator to stop...
[33mwarn[39m: UiAutomator did not shut down fast enough, calling it gone
[36minfo[39m: [debug] Cleaning up android objects
[36minfo[39m: [debug] Cleaning up appium session
[36minfo[39m: [debug] Error: zipAlignApk failed. Error: Command failed: Unable to open '/tmp/apks/app-debug-qe.apk' as zip archive

    at /home/jhuska/Downloads/appium/appium/node_modules/appium-adb/lib/adb.js:468:19
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```
