### ISSUE TITLE
Scrolling is not working for UICollectionViews 

### ISSUE THREAD

**Issue by sjrjanardhana** [appium/appium#4773]
ScrollTo method is not working for the Collection views. it always throws NoSuchElementException.

**Comment by sofaking** [comment]
Please, provide more information like logs, approximate view tree etc. ScrollTo definitely works for some people out there.

**Comment by Jonahss** [comment]
@sjrjanardhana Any news on this?

**Comment by sjrjanardhana** [comment]
hi sorry for the delay in responce....

here is the appium log.

info: --> POST /wd/hub/session/659f4f15-c8ee-4408-bf6f-ba1aaeb98505/element {"using":"name","value":"Storage Wars"}

warn: [DEPRECATED] The name locator strategy has been deprecated and will be removed.  Please use the accessibility id locator strategy instead.

info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByName('Storage Wars')"
info: [debug] Sending command to instruments: au.getElementByName('Storage Wars')

info: [debug] [INST] 2015-04-23 14:07:46 +0000 Debug: Got new command 72 from instruments: au.getElementByName('Storage Wars')

info: [debug] [INST] 2015-04-23 14:07:46 +0000 Debug: evaluating au.getElementByName('Storage Wars')

info: [debug] [INST] 2015-04-23 14:07:47 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-04-23 14:07:47 +0000 Debug: Lookup returned [object UIACollectionCell] with the name "Storage Wars" (id: 30).

info: [debug] [INST] 2015-04-23 14:07:47 +0000 Debug: responding with:

info: [debug] [INST] 2015-04-23 14:07:47 +0000 Debug: Running system command #73: /Applications/Appium_1.3.5.app/Contents/Resources/node/bin/node /Applications/Appium_1.3.5.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"30"}}...

info: [debug] Socket data received (39 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"30"}}

info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"30"},"sessionId":"659f4f15-c8ee-4408-bf6f-ba1aaeb98505"}
info: <-- POST /wd/hub/session/659f4f15-c8ee-4408-bf6f-ba1aaeb98505/element 200 1571.318 ms - 88 {"status":0,"value":{"ELEMENT":"30"},"sessionId":"659f4f15-c8ee-4408-bf6f-ba1aaeb98505"}

info: --> GET /wd/hub/session/659f4f15-c8ee-4408-bf6f-ba1aaeb98505/element/30/displayed {}

info: [debug] Pushing command to appium work queue: "au.getElement('30').isDisplayed()"
info: [debug] Sending command to instruments: au.getElement('30').isDisplayed()

info: [debug] [INST] 2015-04-23 14:07:50 +0000 Debug: Got new command 73 from instruments: au.getElement('30').isDisplayed()

info: [debug] [INST] 2015-04-23 14:07:50 +0000 Debug: evaluating au.getElement('30').isDisplayed()

info: [debug] [INST] 2015-04-23 14:07:50 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-04-23 14:07:50 +0000 Debug: responding with:

info: [debug] [INST] 2015-04-23 14:07:50 +0000 Debug: Running system command #74: /Applications/Appium_1.3.5.app/Contents/Resources/node/bin/node /Applications/Appium_1.3.5.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":false}...

info: [debug] Socket data received (28 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}
info: [debug] Responding to client with success: {"status":0,"value":false,"sessionId":"659f4f15-c8ee-4408-bf6f-ba1aaeb98505"}
info: <-- GET /wd/hub/session/659f4f15-c8ee-4408-bf6f-ba1aaeb98505/element/30/displayed 200 1179.888 ms - 77 {"status":0,"value":false,"sessionId":"659f4f15-c8ee-4408-bf6f-ba1aaeb98505"}

info: --> POST /wd/hub/session/659f4f15-c8ee-4408-bf6f-ba1aaeb98505/element {"using":"class name","value":"UIATableView"}

info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByType('UIATableView')"
info: [debug] Sending command to instruments: au.getElementByType('UIATableView')

info: [debug] [INST] 2015-04-23 14:07:53 +0000 Debug: Got new command 74 from instruments: au.getElementByType('UIATableView')

info: [debug] [INST] 2015-04-23 14:07:53 +0000 Debug: evaluating au.getElementByType('UIATableView')

info: [debug] [INST] 2015-04-23 14:07:53 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-04-23 14:07:53 +0000 Debug: responding with:

info: [debug] [INST] 2015-04-23 14:07:53 +0000 Debug: Running system command #75: /Applications/Appium_1.3.5.app/Contents/Resources/node/bin/node /Applications/Appium_1.3.5.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...

info: [debug] Socket data received (25 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}

info: [debug] Condition unmet after 408ms. Timing out.
info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":""},"sessionId":"659f4f15-c8ee-4408-bf6f-ba1aaeb98505"}
info: <-- POST /wd/hub/session/659f4f15-c8ee-4408-bf6f-ba1aaeb98505/element 500 408.651 ms - 179 

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"},"isShuttingDown":false},"sessionId":"659f4f15-c8ee-4408-bf6f-ba1aaeb98505"}
info: <-- GET /wd/hub/status 200 0.906 ms - 178 {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"},"isShuttingDown":false},"sessionId":"659f4f15-c8ee-4408-bf6f-ba1aaeb98505"}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"},"isShuttingDown":false},"sessionId":"659f4f15-c8ee-4408-bf6f-ba1aaeb98505"}
info: <-- GET /wd/hub/status 200 1.453 ms - 178 {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"},"isShuttingDown":false},"sessionId":"659f4f15-c8ee-4408-bf6f-ba1aaeb98505"}


and this is the view tree in xml

<?xml version="1.0" encoding="UTF-8"?>
<AppiumAUT>
    <UIAApplication name="Anywhere" label="Anywhere" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0" x="0" y="20" width="320" height="548">
        <UIAWindow name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0" x="0" y="0" width="320" height="568">
            <UIANavigationBar name="DVR" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0" x="0" y="20" width="320" height="44">
                <UIAImage name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0" x="0" y="0" width="320" height="64">
                    <UIAImage name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/0" x="0" y="64" width="320" height="0.5">
                    </UIAImage>
                </UIAImage>
                <UIAButton name="RECENTS" label="RECENTS" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/1" x="8" y="28" width="57" height="30">
                </UIAButton>
                <UIAStaticText name="DVR" label="DVR" value="DVR" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/2" x="138" y="28" width="44.5" height="27">
                </UIAStaticText>
                <UIAButton name="LIVE TV" label="LIVE TV" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/3" x="244" y="22" width="60" height="40">
                </UIAButton>
                <UIAButton name="Back" label="Back" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/4" x="8" y="31.5" width="21" height="21">
                </UIAButton>
            </UIANavigationBar>
            <UIAButton name="FILTER" label="FILTER" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1" x="8" y="64" width="60" height="40">
            </UIAButton>
            <UIAButton name="RECORDINGS" label="RECORDINGS" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/2" x="95.5" y="64" width="118" height="40">
            </UIAButton>
            <UIAButton name="EDIT" label="EDIT" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/3" x="273" y="64" width="40" height="40">
                <UIAStaticText name="EDIT" label="EDIT" value="EDIT" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/3/0" x="278" y="76" width="29.5" height="16">
                </UIAStaticText>
            </UIAButton>
            <UIAButton name="icon magnify normal" label="icon magnify normal" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/4" x="275" y="66" width="40" height="36">
            </UIAButton>
            <UIACollectionView name="" label="" value="page 1 of 2" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5" x="0" y="104" width="320" height="415">
                <UIACollectionCell name="BTV Business Info" label="BTV Business Info" value="BTV Business Info" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/0" x="7" y="111" width="150" height="142">
                    <UIAButton name="icon favorite normal" label="icon favorite normal" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/0/0" x="124" y="116" width="28" height="28">
                    </UIAButton>
                    <UIAStaticText name="BTV" label="BTV" value="BTV" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/0/1" x="11" y="225" width="24" height="24">
                    </UIAStaticText>
                    <UIAStaticText name="BTV Business Info" label="BTV Business Info" value="BTV Business Info" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/0/2" x="40" y="225" width="112" height="14">
                    </UIAStaticText>
                    <UIAStaticText name="5 mins" label="5 mins" value="5 mins" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/0/3" x="40" y="240" width="112" height="10">
                    </UIAStaticText>
                </UIACollectionCell>
                <UIACollectionCell name="Biblical Conspiracies" label="Biblical Conspiracies" value="Biblical Conspiracies" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/1" x="163" y="111" width="150" height="142">
                    <UIAButton name="icon favorite normal" label="icon favorite normal" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/1/0" x="280" y="116" width="28" height="28">
                    </UIAButton>
                    <UIAStaticText name="SCI" label="SCI" value="SCI" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/1/1" x="167" y="225" width="24" height="24">
                    </UIAStaticText>
                    <UIAStaticText name="Biblical Conspiracies" label="Biblical Conspiracies" value="Biblical Conspiracies" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/1/2" x="196" y="225" width="112" height="14">
                    </UIAStaticText>
                    <UIAStaticText name="5925 mins" label="5925 mins" value="5925 mins" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/1/3" x="196" y="240" width="112" height="10">
                    </UIAStaticText>
                </UIACollectionCell>
                <UIACollectionCell name="Henry Danger" label="Henry Danger" value="Henry Danger" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/2" x="7" y="260" width="150" height="142">
                    <UIAButton name="icon favorite normal" label="icon favorite normal" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/2/0" x="124" y="265" width="28" height="28">
                    </UIAButton>
                    <UIAStaticText name="NICK" label="NICK" value="NICK" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/2/1" x="11" y="374" width="24" height="24">
                    </UIAStaticText>
                    <UIAStaticText name="Henry Danger" label="Henry Danger" value="Henry Danger" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/2/2" x="40" y="374" width="112" height="14">
                    </UIAStaticText>
                    <UIAStaticText name="2 recordings" label="2 recordings" value="2 recordings" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/2/3" x="40" y="389" width="112" height="10">
                    </UIAStaticText>
                </UIACollectionCell>
                <UIACollectionCell name="His &amp; Hers" label="His &amp; Hers" value="His &amp; Hers" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/3" x="163" y="260" width="150" height="142">
                    <UIAButton name="icon favorite normal" label="icon favorite normal" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/3/0" x="280" y="265" width="28" height="28">
                    </UIAButton>
                    <UIAStaticText name="ESPN2" label="ESPN2" value="ESPN2" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/3/1" x="167" y="374" width="24" height="24">
                    </UIAStaticText>
                    <UIAStaticText name="His &amp; Hers" label="His &amp; Hers" value="His &amp; Hers" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/3/2" x="196" y="374" width="112" height="14">
                    </UIAStaticText>
                    <UIAStaticText name="15 mins" label="15 mins" value="15 mins" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/3/3" x="196" y="389" width="112" height="10">
                    </UIAStaticText>
                </UIACollectionCell>
                <UIACollectionCell name="Married at First Sight" label="Married at First Sight" value="Married at First Sight" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/4" x="7" y="409" width="150" height="142">
                    <UIAButton name="icon favorite normal" label="icon favorite normal" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/4/0" x="124" y="414" width="28" height="28">
                    </UIAButton>
                    <UIAStaticText name="FYI" label="FYI" value="FYI" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/4/1" x="11" y="523" width="24" height="24">
                    </UIAStaticText>
                    <UIAStaticText name="Married at First Sight" label="Married at First Sight" value="Married at First Sight" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/4/2" x="40" y="523" width="112" height="14">
                    </UIAStaticText>
                    <UIAStaticText name="17287 mins" label="17287 mins" value="17287 mins" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/4/3" x="40" y="538" width="112" height="10">
                    </UIAStaticText>
                </UIACollectionCell>
                <UIACollectionCell name="PAW Patrol" label="PAW Patrol" value="PAW Patrol" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/5" x="163" y="409" width="150" height="142">
                    <UIAButton name="icon favorite normal" label="icon favorite normal" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/5/5/0" x="280" y="414" width="28" height="28">
                    </UIAButton>
                    <UIAStaticText name="NICK" label="NICK" value="NICK" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/5/1" x="167" y="523" width="24" height="24">
                    </UIAStaticText>
                    <UIAStaticText name="PAW Patrol" label="PAW Patrol" value="PAW Patrol" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/5/2" x="196" y="523" width="112" height="14">
                    </UIAStaticText>
                    <UIAStaticText name="59 mins" label="59 mins" value="59 mins" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/5/3" x="196" y="538" width="112" height="10">
                    </UIAStaticText>
                </UIACollectionCell>
                <UIACollectionCell name="Storage Wars" label="Storage Wars" value="Storage Wars" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/6" x="0" y="0" width="150" height="142">
                    <UIAStaticText name="16229 mins" label="16229 mins" value="16229 mins" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/6/0" x="0" y="0" width="92" height="12">
                    </UIAStaticText>
                    <UIAStaticText name="Storage Wars" label="Storage Wars" value="Storage Wars" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/6/1" x="0" y="0" width="92" height="17">
                    </UIAStaticText>
                    <UIAButton name="icon favorite normal" label="icon favorite normal" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/6/2" x="0" y="0" width="32" height="32">
                    </UIAButton>
                    <UIAStaticText name="default-channel-white-icon.png" label="A&amp;E" value="A&amp;E" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/6/3" x="0" y="0" width="32" height="32">
                    </UIAStaticText>
                </UIACollectionCell>
                <UIACollectionCell name="Worst Cooks in America" label="Worst Cooks in America" value="Worst Cooks in America" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/7" x="0" y="0" width="150" height="142">
                    <UIAStaticText name="5925 mins" label="5925 mins" value="5925 mins" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/7/0" x="0" y="0" width="92" height="12">
                    </UIAStaticText>
                    <UIAStaticText name="Worst Cooks in America" label="Worst Cooks in America" value="Worst Cooks in America" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/7/1" x="0" y="0" width="92" height="17">
                    </UIAStaticText>
                    <UIAButton name="icon favorite normal" label="icon favorite normal" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/7/2" x="0" y="0" width="32" height="32">
                    </UIAButton>
                    <UIAStaticText name="FOOD" label="FOOD" value="FOOD" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/5/7/3" x="0" y="0" width="32" height="32">
                    </UIAStaticText>
                </UIACollectionCell>
            </UIACollectionView>
            <UIAActivityIndicator name="Progress halted" label="Progress halted" value="0" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/6" x="141.5" y="293" width="37" height="37">
                <UIAImage name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/6/0" x="141.5" y="293" width="37" height="37">
                </UIAImage>
            </UIAActivityIndicator>
            <UIATextView name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/7" x="155" y="291.5" width="10" height="40">
            </UIATextView>
            <UIAStaticText name="0 Titles" label="0 Titles" value="0 Titles" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/8" x="107" y="469" width="106" height="44">
            </UIAStaticText>
            <UIAStaticText name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/9" x="0" y="489" width="320" height="30">
            </UIAStaticText>
            <UIATabBar name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/10" x="0" y="519" width="320" height="49">
                <UIAImage name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/10/0" x="0" y="518.5" width="320" height="0.5">
                </UIAImage>
                <UIAImage name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/10/1" x="0" y="519" width="320" height="49">
                </UIAImage>
                <UIAButton name="Showcase" label="Showcase" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/10/2" x="2" y="520" width="60" height="48">
                </UIAButton>
                <UIAButton name="Guide" label="Guide" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/10/3" x="66" y="520" width="60" height="48">
                </UIAButton>
                <UIAButton name="Sports" label="Sports" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/10/4" x="130" y="520" width="60" height="48">
                </UIAButton>
                <UIAButton name="DVR" label="DVR" value="1" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/10/5" x="194" y="520" width="60" height="48">
                </UIAButton>
                <UIAButton name="More" label="More" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/10/6" x="258" y="520" width="60" height="48">
                </UIAButton>
            </UIATabBar>
        </UIAWindow>
        <UIAWindow name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/1" x="0" y="0" width="320" height="568">
        </UIAWindow>
        <UIAWindow name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2" x="0" y="0" width="320" height="568">
            <UIAStatusBar name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2/0" x="0" y="0" width="320" height="20">
                <UIAElement name="No SIM" label="No SIM" value="" dom="" enabled="true" valid="true" visible="true" hint="Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top" path="/0/2/0/0" x="6" y="0" width="42" height="20">
                </UIAElement>
                <UIAElement name="3 of 3 Wi-Fi bars" label="3 of 3 Wi-Fi bars" value="BTCWIRELESS" dom="" enabled="true" valid="true" visible="true" hint="Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top" path="/0/2/0/1" x="53" y="0" width="13" height="20">
                </UIAElement>
                <UIAElement name="7:40 pm" label="7:40 pm" value="" dom="" enabled="true" valid="true" visible="true" hint="Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top" path="/0/2/0/2" x="138" y="0" width="45" height="20">
                </UIAElement>
                <UIAElement name="Bluetooth on" label="Bluetooth on" value="" dom="" enabled="true" valid="true" visible="true" hint="Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top" path="/0/2/0/3" x="268" y="0" width="8" height="20">
                </UIAElement>
                <UIAElement name="100% battery power, Charging" label="100% battery power, Charging" value="" dom="" enabled="true" valid="true" visible="true" hint="Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top" path="/0/2/0/4" x="282" y="0" width="33" height="20">
                </UIAElement>
            </UIAStatusBar>
        </UIAWindow>
        <UIAWindow name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/3" x="0" y="0" width="320" height="568">
        </UIAWindow>
    </UIAApplication>
</AppiumAUT>

**Comment by sjrjanardhana** [comment]
i am trying to scoll to on of the collection cell element

**Comment by sebv** [comment]
You are not scrolling in the log, could you try to use the action/multiaction api to scroll.

**Comment by sjrjanardhana** [comment]
I did not get what do you mean by action/multiaction api, can you please give an example.

**Comment by sebv** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md

**Comment by sebv** [comment]
@jonah @jlipps  is there a doc sowhere about the ios scrolling issues?

**Comment by sebv** [comment]
Moving to doc, we need to document workarounds.

**Comment by jlipps** [comment]
yes, this is in the touch-actions doc...

> An unfortunate bug exists in the iOS 7.0 - 8.x Simulators where ScrollViews, CollectionViews, and TableViews don't recognize gestures initiated by UIAutomation (which Appium uses under the hood for iOS). To work around this, we have provided access to a different function, `scroll`, which in many cases
allows you to do what you wanted to do with one of these views, namely, scroll it!

And then there are examples.
