### ISSUE TITLE
Appium intermittently fails to create logfile

### ISSUE THREAD

**Issue by lundstrj** [appium/appium#4776]
I run Appium v1.3.7-beta (REV 545372b782e1b580bc8d0ea5f04be8c1600f9f00) in a CI environment of my own creation.

The specific line which launches Appium looks as follows:
```
appium_process = subprocess.Popen(['%s/appium.js' % self.appium_path, '-a', str(self.host), '-p', str(self.port), '--log', self.output_path+'appium.log'])
```

self.output_path will hold different values for different instances of run spawned by the CI-system.
Every now and then the logfile fails to get created. Appium still runs and my tests run but the logfile is nowhere to be found. Despite my best efforts I have failed to come up with a reproducible case but it still happens frequently.

One indicator could be that the logfile seems to always be created when appium has trouble launching. In which case it usually only contains one line:
```
2015-03-25 15:23:42:581 - error: Couldn't start Appium REST http interface listener. Requested port is already in use. Please make sure there's no other instance of Appium running already.
```
But it is sometimes created with regular log output such as:
```
2015-03-25 15:21:29:599 - info: Welcome to Appium v1.3.7-beta (REV 545372b782e1b580bc8d0ea5f04be8c1600f9f00)
2015-03-25 15:21:29:601 - info: Appium REST http interface listener started on localhost:4736
2015-03-25 15:21:29:603 - info: [debug] Non-default server args: {"address":"localhost","port":4736,"log":"/Users/lujo/dev/test_automation/tts/test_runs/2015-03-25_17-21-13/appium.log"}
2015-03-25 15:21:29:604 - info: Console LogLevel: debug
2015-03-25 15:21:29:604 - info: File LogLevel: debug
2015-03-25 15:21:33:643 - info: --> POST /wd/hub/session {"desiredCapabilities":
```

I programmatically parse and use the data in the logfiles to help determine why a test run failed (to filter out false positives and such).

If I can in anyway provide additional information to help debug this issue, just let me know and I'll get on it.

**Comment by amedvedjev** [comment]
to fix "Requested port is already in use" - add flag "--session-override true" with appium start

**Comment by lundstrj** [comment]
@amedvedjev thanks for the suggestion. I'm not quite sure if I want to override it though.

I am going to be running several instances of Appium in parallel and I will be bringing instances up and down all the time (all though, at the moment I am limited to one instance for debugging reasons.)

I have written logic to handle the resource such as ports and devices (in my case iOS devices) so that there should never be any conflicts.

Is it perhaps a known issue that Appium complains about ports being used even though they aren't actually being used? (I've spent a considerable amount of time debugging my own code to see why these port conflicts occur but I have yet to reach any conclusion. I'd be happy to write is off as an Appium issue, if that really is the case).

**Comment by amedvedjev** [comment]
each device to test = new Appium session = own port. you can set it also on appium start.

**Comment by lundstrj** [comment]
Well, yes. That is what I am doing but as it turned out my resources weren't released properly. I tracked it down late last night and I no longer have port conflicts. As it turns out, there are cases in which python doesn't call the destructor for an object and I thought it would.

A funny observation is that the non existing log issue seems to be a lot better today.

**Comment by moizjv** [comment]
@lundstrj is this still an issue?

**Comment by lundstrj** [comment]
@moizjv hey man, I had to put my project on a ice for a bit so I can't give you a straight answer right now. I'm hoping to get back to it in a week or so, I'll do my best to update. (It's in my todo list)

**Comment by sebv** [comment]
I would recommend run appium in separate VM until the appium rewrite is finished, then we'll be able to protect these complex setup with better unit tests.

**Comment by sebv** [comment]
Closing please continue discussion in appium discuss https://discuss.appium.io/

**Comment by VishJP** [comment]
Hey guys,

Please help me to disable appium server logs on console output.

[36minfo[39m: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
[36minfo[39m: Appium REST http interface listener started on 0.0.0.0:4723
[36minfo[39m: [debug] Non-default server args: 

Regards,
Vish
