### ISSUE TITLE
CRITICAL FRUIT STRAP ISSUE Biting all the versions of appium 

### ISSUE THREAD

**Issue by srikanthsadhu** [appium/appium#4779]
please see the logs : Switched all versions of appium from 1.3.4 to 1.3.7, Xcode 6.1.1 and 6.2 , Device OS 8.1.1 , 8.2 seeing the same error as in logs , please resolve....

[-------*************APPIUM_SERVER_LOGS:**************-------------------:info: Welcome to Appium v1.3.7 (REV a4e9d1347524fae6d722201fa300025a0168c3c8)
info: Appium REST http interface listener started on 0.0.0.0:4725
info: [debug] Non-default server args: {"udid":"9054a01991efbbbbc78e95fa4d8250e2bc11a8bf","port":4725,"fullReset":true}
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"autoLaunch":"true","launchTimeout":200000,"newCommandTimeout":600000,"device":null,"app":"/Users/listener/git/E2E_1427289419/e2e_framework/resources/apps/XXX-81199d48d26f-2015-03-20T1030.zip","orientation":"LANDSCAPE","showIOSLog":false,"autoDismissAlerts":true,"waitForAppScript":true,"nativeInstrumentsLib":true,"locationServicesEnabled":false,"locationServicesAuthorized":false,"autoAcceptAlerts":true,"screenshotWaitTimeout":5,"platformVersion":8.1,"browserName":null,"platformName":"iOS","deviceName":"iPad 2"}}
info: Client User-Agent string: appium/ruby_lib/5.0.1
warn: Converting cap autoLaunch from string to boolean. This might cause unexpected behavior.
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : device, screenshotWaitTimeout
info: [debug] Using local .zip from desired caps: /Users/listener/git/E2E_1427289419/e2e_framework/resources/apps/XXX-81199d48d26f-2015-03-20T1030.zip
info: [debug] Copying local zip to tmp dir
info: [debug] /Users/listener/git/E2E_1427289419/e2e_framework/resources/apps/XXX-81199d48d26f-2015-03-20T1030.zip copied to /var/folders/r4/1x1cvp5j3yg8slpp13pb4mvc0000gq/T/115225-8141-qcpvu9/appium-app.zip
info: [debug] Unzipping /var/folders/r4/1x1cvp5j3yg8slpp13pb4mvc0000gq/T/115225-8141-qcpvu9/appium-app.zip
info: [debug] Testing zip archive: /var/folders/r4/1x1cvp5j3yg8slpp13pb4mvc0000gq/T/115225-8141-qcpvu9/appium-app.zip
info: [debug] Zip archive tested clean
info: [debug] Unzip successful
info: [debug] Using locally extracted app: /var/folders/r4/1x1cvp5j3yg8slpp13pb4mvc0000gq/T/115225-8141-qcpvu9/XXX81199d48d26f-2015-03-20T1030/XXX.app
info: [debug] Creating new appium session f1e3e7cd-d2d1-42c4-9144-487a76a79fc5
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.2
info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/listener/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.10.35_1/bin/node","commandProxyClientPath":"/Users/listener/AppiumSource/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":true,"autoDismissAlerts":true,"sendKeyStrategy":"grouped"}
...o: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
info: [debug] Dynamic bootstrap path: /Users/listener/Library/Application Support/appium/bootstrap/bootstrap-16f0ee49fb657abc.js
info: [debug] Creating or overwritting dynamic bootstrap: /Users/listener/Library/Application Support/appium/bootstrap/bootstrap-16f0ee49fb657abc.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPad 2","platformVersion":8.1}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad 2 (8.1 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] On a real device; cannot clean device state
info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole
info: [debug] Not pre-launching simulator
info: [debug] Creating iDevice object with udid 9054a01991efbbbbc78e95fa4d8250e2bc11a8bf
info: [debug] Checking app install status using: /Users/listener/AppiumSource/appium/build/fruitstrap/fruitstrap isInstalled --id 9054a01991efbbbbc78e95fa4d8250e2bc11a8bf --bundle com.bskyb.XXX
info: [debug] App is not installed. Will try to install the app.
info: [debug] Installing app using cmd: /Users/listener/AppiumSource/appium/build/fruitstrap/fruitstrap install --id 9054a01991efbbbbc78e95fa4d8250e2bc11a8bf --bundle "/var/folders/r4/1x1cvp5j3yg8slpp13pb4mvc0000gq/T/115225-8141-qcpvu9/XXX-PR4.5-81199d48d26f-2015-03-20T1030/XXX.app"
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Unable to install [/var/folders/r4/1x1cvp5j3yg8slpp13pb4mvc0000gq/T/115225-8141-qcpvu9/XXX-PR4.5-81199d48d26f-2015-03-20T1030/XXX.app] to device with id [9054a01991efbbbbc78e95fa4d8250e2bc11a8bf]. Error [Error: Command failed: Assertion failed: (AMDeviceStartService(device, CFSTR("com.apple.afc"), &afcFd, NULL) == 0), function handle_device, file fruitstrap.c, line 523.
]
info: [debug] Error: Unable to install [/var/folders/r4/1x1cvp5j3yg8slpp13pb4mvc0000gq/T/115225-8141-qcpvu9/XXX-PR4.5-81199d48d26f-2015-03-20T1030/XXX.app] to device with id [9054a01991efbbbbc78e95fa4d8250e2bc11a8bf]. Error [Error: Command failed: Assertion failed: (AMDeviceStartService(device, CFSTR("com.apple.afc"), &afcFd, NULL) == 0), function handle_device, file fruitstrap.c, line 523.
]
    at /Users/listener/AppiumSource/appium/lib/devices/common.js:147:10
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Unable to install [/var/folders/r4/1x1cvp5j3yg8slpp13pb4mvc0000gq/T/115225-8141-qcpvu9/XXX-PR4.5-81199d48d26f-2015-03-20T1030/XXX.app] to device with id [9054a01991efbbbbc78e95fa4d8250e2bc11a8bf]. Error [Error: Command failed: Assertion failed: (AMDeviceStartService(device, CFSTR(\"com.apple.afc\"), &afcFd, NULL) == 0), function handle_device, file fruitstrap.c, line 523.\n])","origValue":"Unable to install [/var/folders/r4/1x1cvp5j3yg8slpp13pb4mvc0000gq/T/115225-8141-qcpvu9/XXX-PR4.5-81199d48d26f-2015-03-20T1030/XXX.app] to device with id [9054a01991efbbbbc78e95fa4d8250e2bc11a8bf]. Error [Error: Command failed: Assertion failed: (AMDeviceStartService(device, CFSTR(\"com.apple.afc\"), &afcFd, NULL) == 0), function handle_device, file fruitstrap.c, line 523.\n]"},"sessionId":null}
]

**Comment by srikanthsadhu** [comment]
Please help us to get you more information needed to debug this.

**Comment by srikanthsadhu** [comment]
We have been encountering this issue since we updated Brew and iDeviceinstaller.
Intially we were seeing Instruments never checked in or Instruments crashed on start up error , so we introduced steps to update brew and iDeviceInstaller and looked like it worked for couple of day and then started to break the FRUITSTRAP.

Tried most of the options.

**Comment by srikanthsadhu** [comment]
Tried uninstall , unlink , and install then link ideviceinstaller still no good.pls. suggest a way to fix this.

**Comment by srikanthsadhu** [comment]
Seems the issue has been fixed just by UnPlugging the device and plugging it back , Still to do in complete automated fashion we need to look in to option of disabling USB and enabling it , other wise this wont help for automation.Either Fruitstrap or Appium fixes it , it may be good.

**Comment by 0x1mason** [comment]
We've removed Fruitstrap entirely. https://github.com/appium/appium/pull/4790
