### ISSUE TITLE
Perfectly working app turns to a grey background 

### ISSUE THREAD

**Issue by bchand1748** [appium/appium#4780]
I am encountering this strange issue. I have been automating this Hybrid App for a while but never seem to encounter the issue. Now, when I run the code, the App opens on my phone but when the code reaches to switch from native to hybrid(webview), the app stalls and the background is changed to gray. Now, every time I manually open the App, I can see the gray background instead of the app loading. I tried uninstalling the App and installing it back again, however I still see the issue. The only immediate fix is to reset my phone to factory settings.Once that is complete, the App was running fine manually. However, once I run the code, I encountered the same issue. I reset the phone again and this time ,I just run the code upto loading and opening the App on the phone leaving out the code to switch from Native to Hybrid. I run the test more than 10 time and so no issue with loading the app. The moment I added the code to switch the context from Native to Webview, I encounter the same issue. 
I am willing to provide a log but for that I will have to reset the phone and run the code again. Below is what the App looks. 

![screen](https://cloud.githubusercontent.com/assets/10851759/6832176/236426a2-d2fb-11e4-878d-f2348613df2c.png)

**Comment by bchand1748** [comment]
@Jonahss @jlipps Any ideas why this is happening ? Clearly, the issue happens when there is a switch to webview to find Hybrid elements.

**Comment by Jonahss** [comment]
Wow!
It really shouldn't be possible for anything we're doing to permanently affect the state of the app.
Both Appium logs and device logs would be greatly appreciated.

**Comment by bchand1748** [comment]
Appium Log : 

> Starting Node Server
> info: Welcome to Appium v1.3.4 (REV c8c79a85fbd6870cd6fc3d66d038a115ebe22efe)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"app":"C:\\Users\\bkbc011\\Desktop\\apk\\2.61Build.apk","address":"127.0.0.1","fullReset":true,"logNoColors":true,"platformName":"Android","platformVersion":"19","automationName":"Selendroid"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Users\\bkbc011\\Desktop\\apk\\2.61Build.apk","automationName":"selendroid","platformName":"Android","deviceName":"Android","platformVersion":"4.4.2"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.6 (java 1.5)
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from desired caps: C:\Users\bkbc011\Desktop\apk\2.61Build.apk
> info: [debug] Creating new appium session 49d16410-5744-4af8-a516-7abcbd6e4cf2
> info: [debug] Starting selendroid server
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_31
> info: [debug] Checking whether selendroid is built yet
> info: [debug] Selendroid server exists!
> info: [debug] Using fast reset? false
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device 0506931ad84a9331
> info: [debug] Setting device id to 0506931ad84a9331
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 wait-for-device
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe
> info: [debug] Checking if has internet permission from manifest.
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe dump badging C:\Users\bkbc011\Desktop\apk\2.61Build.apk
> info: [debug] Parsing package and activity from app manifest
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe
> info: [debug] Extracting package and launch activity from manifest.
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe dump badging C:\Users\bkbc011\Desktop\apk\2.61Build.apk
> info: [debug] badging package: com.emn8.mobilem8.nativeapp.bk
> info: [debug] badging act: com.testfairy.sdk.activities.WelcomeActivity
> info: [debug] Parsed package and activity are: com.emn8.mobilem8.nativeapp.bk/com.testfairy.sdk.activities.WelcomeActivity
> info: [debug] Rebuilt selendroid server already exists, no need to rebuild it with a new manifest
> info: [debug] Checking signed status of C:\Users\bkbc011\AppData\Local\Temp\selendroid.com.emn8.mobilem8.nativeapp.bk.apk
> info: [debug] Checking app cert for C:\Users\bkbc011\AppData\Local\Temp\selendroid.com.emn8.mobilem8.nativeapp.bk.apk.
> info: [debug] executing cmd: java -jar C:\Users\bkbc011\Desktop\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar C:\Users\bkbc011\AppData\Local\Temp\selendroid.com.emn8.mobilem8.nativeapp.bk.apk
> info: [debug] Checking signed status of C:\Users\bkbc011\Desktop\apk\2.61Build.apk
> info: [debug] Checking app cert for C:\Users\bkbc011\Desktop\apk\2.61Build.apk.
> info: [debug] executing cmd: java -jar C:\Users\bkbc011\Desktop\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar C:\Users\bkbc011\Desktop\apk\2.61Build.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Users\bkbc011\AppData\Local\Temp\selendroid.com.emn8.mobilem8.nativeapp.bk.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\zipalign.exe -f 4 C:\Users\bkbc011\AppData\Local\Temp\selendroid.com.emn8.mobilem8.nativeapp.bk.apk C:\Users\bkbc011\AppData\Local\Temp\appium115231-7500-1ro2kou.tmp
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Users\bkbc011\Desktop\apk\2.61Build.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\zipalign.exe -f 4 C:\Users\bkbc011\Desktop\apk\2.61Build.apk C:\Users\bkbc011\AppData\Local\Temp\appium115231-7500-zadmdd.tmp
> info: [debug] Rebuilt selendroid apk does not exist, uninstalling any instances of it on device to make way for new one
> info: [debug] Uninstalling com.emn8.mobilem8.nativeapp.bk.selendroid
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "am force-stop com.emn8.mobilem8.nativeapp.bk.selendroid"
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 uninstall com.emn8.mobilem8.nativeapp.bk.selendroid
> info: [debug] App was uninstalled
> info: [debug] Getting install status for com.emn8.mobilem8.nativeapp.bk.selendroid
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 21
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "pm list packages -3 com.emn8.mobilem8.nativeapp.bk.selendroid"
> info: [debug] App is not installed
> info: [debug] Rebuilt selendroid is not installed, installing it
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 install -r "C:\Users\bkbc011\AppData\Local\Temp\selendroid.com.emn8.mobilem8.nativeapp.bk.apk"
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] java -jar "C:\Users\bkbc011\Desktop\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\bkbc011\Desktop\apk\2.61Build.apk" "C:\Users\bkbc011\AppData\Local\Temp\com.emn8.mobilem8.nativeapp.bk" en
> info: [debug] No strings.xml for language 'en', getting default strings.xml
> info: [debug] java -jar "C:\Users\bkbc011\Desktop\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\bkbc011\Desktop\apk\2.61Build.apk" "C:\Users\bkbc011\AppData\Local\Temp\com.emn8.mobilem8.nativeapp.bk"
> info: [debug] Uninstalling com.emn8.mobilem8.nativeapp.bk
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "am force-stop com.emn8.mobilem8.nativeapp.bk"
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 uninstall com.emn8.mobilem8.nativeapp.bk
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] Checking app cert for C:\Users\bkbc011\Desktop\apk\2.61Build.apk.
> info: [debug] executing cmd: java -jar C:\Users\bkbc011\Desktop\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar C:\Users\bkbc011\Desktop\apk\2.61Build.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Users\bkbc011\Desktop\apk\2.61Build.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\build-tools\21.1.2\zipalign.exe -f 4 C:\Users\bkbc011\Desktop\apk\2.61Build.apk C:\Users\bkbc011\AppData\Local\Temp\appium115231-7500-csqgfr.tmp
> info: [debug] MD5 for app is 0fac9b94cbaca409f323e8cde2769abe
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "ls /data/local/tmp/0fac9b94cbaca409f323e8cde2769abe.apk"
> info: [debug] Getting install status for com.emn8.mobilem8.nativeapp.bk
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 21
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "pm list packages -3 com.emn8.mobilem8.nativeapp.bk"
> info: [debug] App is not installed
> info: Installing App
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "mkdir -p /data/local/tmp/"
> info: [debug] Removing any old apks
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "ls /data/local/tmp/*.apk"
> info: [debug] Found an apk we want to keep at /data/local/tmp/0fac9b94cbaca409f323e8cde2769abe.apk
> info: [debug] Couldn't find any apks to remove
> info: [debug] Uninstalling com.emn8.mobilem8.nativeapp.bk
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "am force-stop com.emn8.mobilem8.nativeapp.bk"
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 uninstall com.emn8.mobilem8.nativeapp.bk
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "pm install -r /data/local/tmp/0fac9b94cbaca409f323e8cde2769abe.apk"
> info: [debug] Forwarding system:8080 to device:8080
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 forward tcp:8080 tcp:8080
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 install "C:\Users\bkbc011\Desktop\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 install "C:\Users\bkbc011\Desktop\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "am instrument -e main_activity 'com.testfairy.sdk.activities.WelcomeActivity' com.emn8.mobilem8.nativeapp.bk.selendroid/io.selendroid.ServerInstrumentation"
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Selendroid server is alive!
> info: [debug] Listening for Selendroid logs
> info: [debug] Creating Selendroid session
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session","method":"POST","json":{"desiredCapabilities":{"warnings":{},"desired":{"app":"C:\\Users\\bkbc011\\Desktop\\apk\\2.61Build.apk","automationName":"selendroid","platformName":"Android","deviceName":"Android","platformVersion":"4.4.2"},"app":"C:\\Users\\bkbc011\\Desktop\\apk\\2.61Build.apk","automationName":"selendroid","platformName":"Android","deviceName":"Android","platformVersion":"4.4.2"}}}
> info: [debug] Successfully started selendroid session
> info: [debug] Waiting for pkg "com.emn8.mobilem8.nativeapp.bk" and activity "com.testfairy.sdk.activities.WelcomeActivity" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "dumpsys window windows"
> info: [debug] Overriding session id with "aeb13d6b-aba9-ca99-2dcb-83979c3d75d6"
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId aeb13d6b-aba9-ca99-2dcb-83979c3d75d6
> info: <-- POST /wd/hub/session 303 35881.137 ms - 9 
> info: --> GET /wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6 {}
> info: [debug] Proxying command to localhost:8080
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6","method":"GET"}
> info: [debug] Proxied response received with status 200: "{\"sessionId\":\"aeb13d6b-aba9-ca99-2dcb-83979c3d75d6\",\"status\":0,\"value\":{\"warnings\":{},\"desired\":{\"app\":\"C:\\\\Users\\\\bkbc011\\\\Desktop\\\\apk\\\\2.61Build.apk\",\"automationName\":\"selendroid\",\"platformName\":\"Android\",\"deviceName\":\"Android\",\"platformVersion\":\"4.4.2\"},\"app\":\"C:\\\\Users\\\\bkbc011\\\\Desktop\\\\apk\\\\2.61Build.apk\",\"automationName\":\"selendroid\",\"platformName\":\"android\",\"deviceName\":\"Android\",\"platformVersion\":\"21\",\"takesScreenshot\":true,\"browserName\":\"selendroid\",\"rotatable\":true,\"platform\":\"android\",\"handlesAlerts\":true,\"javascriptEnabled\":true,\"networkConnectionEnabled\":true,\"version\":\"0.12.0\",\"acceptSslCerts\":true}}"
> info: <-- GET /wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6 200 57.356 ms - 623 
> info: --> POST /wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6/element {"using":"id","value":"button1"}
> info: [debug] Proxying command to localhost:8080
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6/element","method":"POST","json":{"using":"id","value":"button1"}}
> info: [debug] Proxied response received with status 200: {"sessionId":"aeb13d6b-aba9-ca99-2dcb-83979c3d75d6","status":0,"value":{"ELEMENT":"1a260ed9-1815-c80f-7d40-5b7ede1c27c2"}}
> info: <-- POST /wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6/element 200 46.574 ms - 122 
> info: --> POST /wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6/element/1a260ed9-1815-c80f-7d40-5b7ede1c27c2/click {"id":"1a260ed9-1815-c80f-7d40-5b7ede1c27c2"}
> info: [debug] Proxying command to localhost:8080
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6/element/1a260ed9-1815-c80f-7d40-5b7ede1c27c2/click","method":"POST","json":{"id":"1a260ed9-1815-c80f-7d40-5b7ede1c27c2"}}
> info: [debug] Proxied response received with status 200: {"sessionId":"aeb13d6b-aba9-ca99-2dcb-83979c3d75d6","status":0,"value":""}
> info: <-- POST /wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6/element/1a260ed9-1815-c80f-7d40-5b7ede1c27c2/click 200 676.815 ms - 74 
> info: [debug] [SELENDROID] on else with values 1280;1280;768;690;690
> info: --> GET /wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6/contexts {}
> info: [debug] Getting a list of available webviews
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "cat /proc/net/unix"
> info: [debug] WEBVIEW_8875 mapped to pid 8875
> info: [debug] Getting process name for webview
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "ps"
> info: [debug] Parsed pid: 8875 pkg: com.emn8.mobilem8.nativeapp.bk
> info: [debug] from: u0_a121,8875,203,2062676,238020,ffffffff,00000000,S,com.emn8.mobilem8.nativeapp.bk
> info: [debug] returning process name: com.emn8.mobilem8.nativeapp.bk
> info: [debug] Available contexts: undefined
> info: [debug] ["WEBVIEW_com.emn8.mobilem8.nativeapp.bk"]
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6/window_handles","method":"GET"}
> info: [debug] Available contexts: ["WEBVIEW_0","NATIVE_APP"]
> info: [debug] Responding to client with success: {"status":0,"value":["WEBVIEW_0","NATIVE_APP"],"sessionId":"aeb13d6b-aba9-ca99-2dcb-83979c3d75d6"}
> info: <-- GET /wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6/contexts 200 314.316 ms - 98 {"status":0,"value":["WEBVIEW_0","NATIVE_APP"],"sessionId":"aeb13d6b-aba9-ca99-2dcb-83979c3d75d6"}
> info: --> POST /wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6/context {"name":"WEBVIEW_0"}
> info: [debug] Getting a list of available webviews
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "cat /proc/net/unix"
> info: [debug] WEBVIEW_8875 mapped to pid 8875
> info: [debug] Getting process name for webview
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "ps"
> info: [debug] Parsed pid: 8875 pkg: com.emn8.mobilem8.nativeapp.bk
> info: [debug] from: u0_a121,8875,203,2063740,238212,ffffffff,00000000,S,com.emn8.mobilem8.nativeapp.bk
> info: [debug] returning process name: com.emn8.mobilem8.nativeapp.bk
> info: [debug] Available contexts: WEBVIEW_0,NATIVE_APP
> info: [debug] ["WEBVIEW_com.emn8.mobilem8.nativeapp.bk"]
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6/window_handles","method":"GET"}
> info: [debug] Available contexts: ["WEBVIEW_0","NATIVE_APP"]
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6/context","method":"POST","json":{"name":"WEBVIEW_0"}}
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"aeb13d6b-aba9-ca99-2dcb-83979c3d75d6"}
> info: <-- POST /wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6/context 200 343.522 ms - 76 {"status":0,"value":null,"sessionId":"aeb13d6b-aba9-ca99-2dcb-83979c3d75d6"}
> info: [debug] Didn't get a new command in 60 secs, shutting down...
> info: Shutting down appium session
> info: [debug] Stopping selendroid server
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/aeb13d6b-aba9-ca99-2dcb-83979c3d75d6","method":"DELETE"}
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "am force-stop com.emn8.mobilem8.nativeapp.bk"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Removing app from device
> info: [debug] Uninstalling com.emn8.mobilem8.nativeapp.bk
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 shell "am force-stop com.emn8.mobilem8.nativeapp.bk"
> info: [debug] executing cmd: C:\Users\bkbc011\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0506931ad84a9331 uninstall com.emn8.mobilem8.nativeapp.bk
> info: [debug] App was uninstalled
> info: [debug] Cleaning up appium session
> info: [debug] We shut down because no new commands came in

Eclipse Log: 

WEBVIEW_0
NATIVE_APP
Exception in thread "main" org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5.75 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'BKUSL-6QBN7W1', ip: '172.17.90.84', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_31'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{app=C:\Users\bkbc011\Desktop\apk\2.61Build.apk, rotatable=true, networkConnectionEnabled=true, warnings={}, handlesAlerts=true, deviceName=Android, version=0.12.0, platform=ANDROID, desired={app=C:\Users\bkbc011\Desktop\apk\2.61Build.apk, platformVersion=4.4.2, automationName=selendroid, platformName=Android, deviceName=Android}, acceptSslCerts=true, platformVersion=21, automationName=selendroid, takesScreenshot=true, browserName=selendroid, javascriptEnabled=true, platformName=android}]
Session ID: b48e3381-f9e0-303a-8f81-c2c8f06d1b26
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:176)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:393)
	at org.openqa.selenium.By$ById.findElement(By.java:214)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at registration.main(registration.java:69)

**Comment by Jonahss** [comment]
Hmm, everything seems in order. I'm wondering if this could be because of a weird interaction of your app and Selendroid? @jlipps: what do you think?

**Comment by jlipps** [comment]
i dunno the webview names look off to me

**Comment by Jonahss** [comment]
Off in what way?

**Comment by jlipps** [comment]
Oh, they're using Selendroid. I wonder why we're calling our own contexts function then; Selendroid should be doing that.

**Comment by Jonahss** [comment]
Still doesn't explain how it permanently breaks the app.

**Comment by jlipps** [comment]
I agree. I'm guessing you're right about it being a weird interaction of Selendroid and their app. What does logcat say?

**Comment by bchand1748** [comment]
Guys, 
Apparently, this is an intermittent issue with the App itself for 5.0 and above. Thank you for your time.

**Comment by Jonahss** [comment]
phew! I was getting worried there.
In that case Appium is a success! The tests caught your bug!
