### ISSUE TITLE
safariAllowPopups not applied on iOS 8.2

### ISSUE THREAD

**Issue by SBoudrias** [appium/appium#4784]
For some reason `safariAllowPopups` is not set using iOS 8.2

Here's my desired capabilities:

```python
config = {
    'deviceName': 'iPhone Simulator',
    'browserName': 'Safari',
    'platformVersion': '8.2',
    'platformName': 'iOS',
    'safariAllowPopups': True,
    'safariIgnoreFraudWarning': True,
    'safariOpenLinksInBackground': True,
}
```

I've traced the actual appium code and `IOS.prototype.setSafariPrefs` is correctly called and the option for the popup blocker is passing through. But then when I inspect the booted device, the popup blocker is still on preventing us from opening new windows.

if it helps further, here's a link to the saucelabs run https://saucelabs.com/tests/bbbf5aa6a39a4cc0aa322af294172826

**Comment by SBoudrias** [comment]
Not sure I'm looking at the right place, but this method seems wrong: https://github.com/appium/appium/blob/master/lib/devices/ios/settings.js#L236-L258

`settings` is the module object, so it won't have any of those config key the code is looking for. Maybe this is supposed to be `settingSet` (I can see this was `this.capabilities` in past code, so I'm not sure that's exactly equivalent)

**Comment by jlipps** [comment]
this whole method looks like it was refactored poorly. you're right about the module object, also we're creating an inner `settingSet` variable which doesn't seem right either. we'll need to dig in to figure out what is actually supposed to happen here. ouch.

**Comment by jlipps** [comment]
interesting this hasn't been getting caught by any of our tests, @imurchie did you run into any issues with this and your recent test runs?

**Comment by imurchie** [comment]
No. Our test suite runs fully for Safari on 8.2. I'm not sure what our test coverage is for this case.

**Comment by SBoudrias** [comment]
Do you open popup in your test suite?

**Comment by jlipps** [comment]
looks like we have some tests here: `test/functional/ios/prefs/safari-allows-popup-specs.js`

**Comment by SBoudrias** [comment]
Actually, in my tests, it seemed like the safari setting were correctly written to a file (safari user pref didn't seemed to be written though as explained earlier).

The test is only checking the config file is actually written, not that the setting is correctly applied when opening a device.

**Comment by jlipps** [comment]
interesting, sounds like we may need to make our tests better as part of fixing this

**Comment by SBoudrias** [comment]
Hey, any update on this? This seems like a fairly major issue.

**Comment by jlipps** [comment]
hey @SBoudrias i'm looking into this but can't get my initial conditions set up: i'm having trouble getting safari to block any popups at all, even when i have that pref set. do you have a good example of something that gets blocked, that i can test?

**Comment by SBoudrias** [comment]
The easiest way to reproduce is to inject a script in the page. This is because Safari won't block any pop-up that are opened via a click, but will block any popup opening without a user direct interaction.

```js
driver.execute_script('window.open("http://google.com", null)')
```

You can also always go check into `settings > safari > popup blocker` to see if the configuration have been applied or not. Currently this setting is always on.

**Comment by jlipps** [comment]
got it; yeah i was attaching to a click with a timeout, i thought that would bypass the click detection but apparently not

**Comment by jlipps** [comment]
think i've got it @SBoudrias, you can check out #4928 if you want, and let me know if it fixes things for you
