### ISSUE TITLE
Appium for IOS 7.0/7.1 on MAC 10.10

### ISSUE THREAD

**Issue by PavithraNavaneeth** [appium/appium#4788]
Can someone please suggest which Xcode version to use (for IOS 7.0 & 7.1) on MAC 10.10 for real device testing with appium.
I installed xcode 6.2 (and installed xcode 5.0, copied 7.0 sdk to 6.2 platforms). After copying I deleted xcode 5.0. Appium is throwing "unable to identify xcode version and hence not setting ios sdk"

Kindly suggest how can I achieve the above.

**Comment by Jonahss** [comment]
There is an `xcode-select` command which is useful. You can use that to switch the xcode being used by your system between different versions. Just keep both the Xcode.app files and pass the path to `xcode-select`
