### ISSUE TITLE
iOS webkit debug proxy is getting disconnected in iOS 8.2

### ISSUE THREAD

**Issue by vinothannamalai** [appium/appium#4789]
1. I have installed webkit proxy with below configuration

libusb-1.0.19
libplist-1.12 
usbmuxd-1.0.10
ios-webkit-debug-proxy-1.4_2.

2. Safari launcher app was also installed in iOS 8.2 device.

When we try to launch the safari launcher app, iOS webkit debug proxy is getting disconnected and showing following error.

Invalid message _rpc_applicationUpdated: <dict>
	<key>WIRApplicationIdentifierKey</key>
	<string>PID:460</string>
	<key>WIRIsApplicationProxyKey</key>
	<true/>
	<key>WIRApplicationNameKey</key>
	<string></string>
	<key>WIRApplicationBundleIdentifierKey</key>
	<string>com.apple.WebKit.WebContent</string>
	<key>WIRIsApplicationActiveKey</key>
	<integer>0</integer>
	<key>WIRHostApplicationIdentifierKey</key>
	<string>PID:446</string>
</dict>
ss.remove_fd(6)
Disconnected :27753 from iPhone ("Device UDID")
ss.remove_server_fd(4)
cz^Css.remove_fd(3)

I faced this kind of similar issue in iOS 8.0.1. After i did not try with iOS 8.x after that. 

Please help me to sort out this issue as soon as possible.

Thanks in advance,

Vinoth

**Comment by 0x1mason** [comment]
Can you try building IWDP from this repo and using it instead?

https://github.com/jchuong/ios-webkit-debug-proxy

**Comment by MiquelMittertreiner** [comment]
Having exactly the same issue

**Comment by 0x1mason** [comment]
@MiquelMittertreiner please try using IWDP from the repo I mentioned.

**Comment by MiquelMittertreiner** [comment]
@0x1mason How do i exactly use it on my mac? Im pretty new to this stuff

**Comment by 0x1mason** [comment]
@MiquelMittertreiner Clone jchuong's repo.  Build it.  Attach your iOS device to your machine. Then run
`ios_webkit_debug_proxy -c <UDID of iOS device>:27753 -d` from the directory containing the executable. Run your test.

**Comment by MiquelMittertreiner** [comment]
@0x1mason Where do I build it, i can't open it in Xcode and i can't build it in github client.

**Comment by MiquelMittertreiner** [comment]
@0x1mason Just to be clear, I'm not trying to automate any kind of application. Im working on test automation on mobile devices in browser, where i've finished windows and android already. Im running the test from a different (windows) pc where I'm using c# to build the tests, from there out I'm deploying them remotely (with my capabilities settings) throughout NUnit, which will send them to my iPad, which is connected to my mac.

**Comment by 0x1mason** [comment]
I'm assuming Appium is installed on your mac.  You build IWDP there.  Follow the instructions for installation on the repo I linked. They include the commands for building.

**Comment by MiquelMittertreiner** [comment]
I have Appium yes, I'm sorry, call me stupid, but can you guide me through stepwise? I'm still not sure on how to build it using Appium.

**Comment by 0x1mason** [comment]
Open the command terminal on your mac.  You can find instructions on how to open the terminal via your favorite search engine. Once that is open, enter the following commands (the `$` indicates the command line prompt, do not enter it).

First, make sure you have [Homebew](http://brew.sh/) installed:
```shell
$ brew -v
```

Assuming you have Homebrew setup, do the following:

```shell
$ cd  ~
$ git clone https://github.com/jchuong/ios-webkit-debug-proxy.git
$ cd ios-webkit-debug-proxy
$ brew install autoconf automake libusb libplist usbmuxd
$ brew install --HEAD ideviceinstaller
$ ./autogen.sh
$ ./configure
$ make
$ sudo make install
$ os_webkit_debug_proxy -c <UDID of iOS device>:27753
```

Replace **< UDID of iOS device >** with your device's unique id.  You can learn how to retrieve the UDID from Apple's developer resources.

**Comment by MiquelMittertreiner** [comment]
@0x1mason Thank you a lot for your information and im sorry for my late response. The connection is working now i guess, I can't tell for sure since my test isn't running the way it should. I have a really simple test where it should navigate to an url, but it's not moving from www.apple.com, ever. This is my testcode:

            Console.WriteLine("Navigating to fr12...")
            appiumdriver.Navigate.GoToUrl("http://www.fr12.nl")

**Comment by MiquelMittertreiner** [comment]
These are my settings in case you were wondering:

Dim uri As New Uri("http://192.168.204.30:4723/wd/hub")
    Public capabilities As DesiredCapabilities
    Public appiumdriver As AppiumDriver



        capabilities = New DesiredCapabilities
        capabilities.SetCapability("deviceName", "Infoland's iPad")
        capabilities.SetCapability("platformName", "iOS")
        capabilities.SetCapability("version", "8.1")
        capabilities.SetCapability("udid", "db704aa1b10034f0b4161d4a8d88762024baa12e")
        capabilities.SetCapability(CapabilityType.BrowserName, "Safari")
        'capabilities.SetCapability("appium-version", "1.3.5")
        'capabilities.SetCapability("autoAcceptAlerts", True)
        'capabilities.SetCapability("disable-popup-blocking", False)
        Console.WriteLine("binding info to driver..")
        appiumdriver = New IOSDriver(uri, capabilities, New TimeSpan(0, 0, 180))

**Comment by 0x1mason** [comment]
Make sure all your capabilities are camel cased. We no longer support hyphens. Next, upgrade to 1.3.7. If it's still not working, provide the Appium logs.

**Comment by MiquelMittertreiner** [comment]
@0x1mason You mean uppercammelcase like DeviceName and PlatformName?

**Comment by 0x1mason** [comment]
No, `camelCase`.  Notice most of your caps are camelCased except for a
couple you have hyphenated. See here:
http://appium.io/slate/en/master/?java#appium-server-capabilities

On Thu, Apr 2, 2015 at 9:08 AM, MiquelMittertreiner <
notifications@github.com> wrote:

> @0x1mason <https://github.com/0x1mason> You mean uppercammelcase like
> DeviceName and PlatformName?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/4789#issuecomment-88890673>.
>



-- 

*Eric Millin*
*Software Engineer, Ecosystems*
Twitter: @etmillin <http://twitter.com/jlipps>
GitHub: @0x1mason <https://github.com/jlipps>
Sauce Labs <http://saucelabs.com/> | Sauce blog <http://sauceio.com/>

**Comment by MiquelMittertreiner** [comment]
@0x1mason Yes but i have commented those out so that shouldn't be the problem but i'll try upgrading my appium and then let you'll know how it went.

**Comment by 0x1mason** [comment]
Also, note this, if you haven't already:

**NOTE:** the proxy requires the **"web inspector"** to be turned on to
allow a connection to be established. Turn it on by going to **settings >
safari > advanced**. Please be aware that the web inspector was **added as
part of iOS 6** and was not available previously.



On Thu, Apr 2, 2015 at 10:01 AM, MiquelMittertreiner <
notifications@github.com> wrote:

> @0x1mason <https://github.com/0x1mason> Yes but i have commented those
> out so that shouldn't be the problem but i'll try upgrading my appium and
> then let you'll know how it went.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/4789#issuecomment-88914015>.
>



-- 

*Eric Millin*
*Software Engineer, Ecosystems*
Twitter: @etmillin <http://twitter.com/jlipps>
GitHub: @0x1mason <https://github.com/jlipps>
Sauce Labs <http://saucelabs.com/> | Sauce blog <http://sauceio.com/>

**Comment by MiquelMittertreiner** [comment]
@0x1mason Thanks for all your info, I've updated appium and tried some other bunch of stuff, and I've got some progress. But the issue not is that it says the page has been loaded, but my iPad is stuck on apple.com. As you can see below it says https://www.google.com has been loaded.

info: [debug] [REMOTE] Navigating to new URL: https://www.google.com

info: [debug] [REMOTE] Remote debugger data sent [{"method":"Page.navigate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"url":"https://www.google.com"},"id":1}...]

info: [debug] [REMOTE] Waiting for frame navigated...

info: [debug] [REMOTE] Frame navigated, calling cbs

info: [debug] [REMOTE] Waiting for dom...
info: [debug] [REMOTE] Page loaded, verifying whether ready through readyState

**Comment by sebv** [comment]
There is a script to restart ios webkit proxy automatically. (Thought it would be good to fix the proxy itself)

https://github.com/appium/appium/blob/master/bin/ios-webkit-debug-proxy-launcher.js

If there are more errors needed to be caught they can be added here: 
https://github.com/appium/appium/blob/master/bin/ios-webkit-debug-proxy-launcher.js

**Comment by raldred** [comment]
I'm getting a similar symtoms with my real iPhone 4 running 6.1.3
Xcode 6.3.1 on OSX 10.10
Appium master (1.4.0-beta) 
ios-webkit-debug-proxy installed from the git repo above
ideviceinstaller latest installed with brew -HEAD

Driving tests with ruby appium_lib gem.

		desired_caps = {
			caps: {
				platformName: 'iOS',
				udid: device[:id],
				browserName: 'Safari',
				deviceName: device[:model],
				device: device[:type],
				newCommandTimeout: 0
			},
			appium_lib: {
				sauce_username: nil,
				sauce_access_key: nil
			}
		}
		device[:driver] = Appium::Driver.new(desired_caps).start_driver

Safari on the device is launched but remains on www.apple.com like the OP.
Ruby hangs on the start_driver call.
Appium gives up:

    info: [debug] [INST STDERR] 2015-05-05 12:59:16.828 instruments[16047:76858] WebKit Threading Violation - initial use of WebKit from a secondary thread.
    info: [debug] [INST] 2015-05-05 11:59:39 +0000 Fail: Could not start script, target application is not frontmost.
    info: [debug] [INST] Instruments Trace Complete (Duration : 22.533394s; Output : /tmp/appium-instruments/instrumentscli0.trace)
    info: [debug] [INSTSERVER] Instruments exited with code 0
    info: [debug] Cleaning up after instruments exit
    info: [debug] Not worrying about instruments exit since we're using SafariLauncher
warn: Instruments socket client never checked in; timing out (global)
    info: [debug] Killall instruments

**Comment by Jonahss** [comment]
Can you try on the 1.4 branch?

**Comment by sebv** [comment]
Summary be for closing:
- Make sure that "Web Inspector" is enabled
- use https://github.com/appium/appium/blob/master/bin/ios-webkit-debug-proxy-launcher.js

**Comment by sebv** [comment]
Shout if you need this reopened.

**Comment by smemane** [comment]
Hi, 
I am facing a similar issue, bt when I try to run the command, it gives me an error - "module.js: 388 throw err Error: Cannot find module 'underscore' at Function.Module_resolveFuleName (module.js:336:15) .... " 
As everyone had a similar problem, wondering if anyone seen this error before ?

**Comment by shermanericSF** [comment]
@smemane:  
1. If you look at line 22 in here:
https://github.com/appium/appium/blob/e6927c60e2264e32eade441dbfbf57f183310b43/bin/ios-webkit-debug-proxy-launcher.js

You'll see:  require('underscore')

2. Your error message is stating that the underscore node module is not installed locally from where you are trying to run things

3.  Firstly, make sure (as others have mentioned) that in iOS Device > Settings > Safari > Advanced > Web Inspector is turned on.

3a.  Secondly, make sure your device is attached via USB and you have the correct UDID (look in xcode > Devices)

4.  Then, you have 2 options:
a.  checkout the appium repo and run ./bin/ios-webkit-debug-proxy-launcher.js -c <UDID>:27753

b.  copy the ios-webkit-debug-proxy-launcher.js somewhere else that's more convenient.  If you do this route, you'll need to install the underscore module locally:
      ```cd <your directory>```
      ```cp ios-webkit-debug-proxy-launcher.js  <your directory>```
      ```npm install underscore```

That should do it.
Hope that helps!
Good luck
Eri
c

**Comment by smemane** [comment]
Thanks Eri, I got my issue resolved by following step a - "checkout the appium repo and run ./bin/ios-webkit-debug-proxy-launcher.js -c :27753"
