### ISSUE TITLE
Change iOS Perf Log to use Log format defined in Selenium

### ISSUE THREAD

**Issue by axemclion** [appium/appium#4797]
The Selenium Perf log format is defined here - https://code.google.com/p/selenium/wiki/JsonWireProtocol#Log_Entry_JSON_Object

PerfLog for iOS was introduced as a part of this commit - https://github.com/appium/appium/commit/6c6362f0a3f15ef27bd478212e6095eea4cbb26c

The PerfLog introduced in the above commit simply return JSON instead of serializing the log as a string. This could cause issues with some clients. Can I send in a pull request that serialized the perf log messages to a string ? Note that converting all messages to string format could slow down the call to getLog() function. 

Can I send in a pull request for fixing this ?

**Comment by jlipps** [comment]
I'm a little confused---that doc says that log entry messages should be strings. We're returning a list of log entries. Are you saying the `message` key of each entry has a value that is not a string, currently?

If so, then I'm a fan of making this change, but am not sure how to proceed given that it might be a breaking change. We'd have to evaluate what to do with this given semver conventions.

**Comment by axemclion** [comment]
@jlipps Yes, the messages cannot be JSON objects, they need to be strings. This is indeed a breaking change. Also, converting all messages to string may make the perfLogs much slower due to the serialization call for each record from the timeline.

**Comment by Jonahss** [comment]
That should be fine, feel free to submit a Pull Request.

**Comment by axemclion** [comment]
Just an update - Chrome has deprecated timline and now uses tracing instead. However, this is still needed since the format of the logs is a a String, so will do that.
