### ISSUE TITLE
Interactions outside of targeted application (Springboard, home screen, etc.)

### ISSUE THREAD

**Issue by GindiKhangura** [appium/appium#4802]
**iOS**
On iOS, I am able to get the page source of the Springboard and the Settings app (have not tried any others yet). This is achieved by creating a driver like you would normally do (have a targeted app to test), then calling (in Java):

*driver.runAppInBackground({some large value here});*
*driver.getPageSource();*

We can get all the elements from the Springboard along with their attributes (text, position, size, class, etc). This allows us to navigate to the Settings application and toggling the wifi, GPS, etc.

**Android**
I can do the same thing as with iOS, but when I call *driver.getPageSource()* the application that was forced to run in the background attains focus again and the page source returns the tested application's page source. **Is there a way to "fix" this and allow us to get the page source of the home screen?** I do realize that we can call  *driver.openNotifications()* and get the page source of that screen in order to toggle the wifi, but having the ability to interact with the rest of the device would be really nice :)

The devices that I was using for iOS and Android are (respectively):

iPad Air (retina) on iOS 8.1 using Appium 1.3.5
Samsung Galaxy Tab Pro on Android 4.4.2 using Appium 1.3.7

**Comment by GindiKhangura** [comment]
The Appium versions are different because I am running one from a Mac and the other from Windows. I was originally using Appium 1.3.1 for Android, but upgraded to 1.3.7 to check if there was a difference.

**Comment by GindiKhangura** [comment]
Also realized that there is a *setNetworkConnection(...)* method for Android devices, but still looking for full automation control over the device if possible.

**Comment by jlipps** [comment]
On Android you can just simulate pressing the Home button to get to the Home screen. You don't need to send your app to the background.

**Comment by GindiKhangura** [comment]
Nice, that worked!

**Comment by msahni09** [comment]
How did you handle/interact with alerts like "No Sim in device", "Low Battery" etc on springboard and alerts on any other application outside of targeted application?. I am stuck here and appium just hangs and all commands go in work queue but never executed.

**Comment by GindiKhangura** [comment]
We reduced the scope of our testing capabilities and so I have not tested the Springboard any further and never encountered the scenarios that you mentioned. You might have better luck asking your question on Appium's discussion board (https://discuss.appium.io/).
