### ISSUE TITLE
Unable to disconnect network on a device when working with 2 devices

### ISSUE THREAD

**Issue by sparklingAngel0706** [appium/appium#4803]
I am facing a new problem when using appium for two devices,
i have created two drivers 
driver1 for device1 and driver 2 for device 2 when i disconnect network on device 1 using setNetworkConnection my device 2 automatically disconnected , causes session not found exception.
android devices
windows os
appium version:1.3.4.1

**Comment by sebv** [comment]
As of now, you need to use 2 appium servers (easiest it to use 2 VMs.)

**Comment by Jonahss** [comment]
Yeah, you run two appium servers with different ports...
