### ISSUE TITLE
Use idevicescreenshot for saving screenshots on iOS devices

### ISSUE THREAD

**Issue by ghost** [appium/appium#4805]
idevicescreenshot takes screenshots on iOS much faster than WebDriver.
**Note:** idevicescreenshot saves screenshots in tiff format by default. I am using sips utility to convert to png:
`idevicescreenshot original_screenshot.tiff`
`sips -s format png original_screenshot.tiff --out converted_screenshot.png`

**Comment by mykola-mokhnach** [comment]
This is done in https://github.com/appium/appium-xcuitest-driver/pull/510
