### ISSUE TITLE
Question about driver.find_elements

### ISSUE THREAD

**Issue by xsmaster** [appium/appium#4808]
Hey all - I'm new to ruby so this might be a very noob question to ask.

3 Questions with this code from the driver.rb file.

What are the possible *args that can be passed?
How could I have found them myself without having to ask?
What does the @driver mean? Is it calling it self?

https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/driver.rb 
```
Calls @driver.find_elements
 @param args [*args] the args to use
 @return [Array<Element>] Array is empty when no elements are found.
     def find_elements *args
        @driver.find_elements *args
      end
```
Thanks!

**Comment by imurchie** [comment]
Please ask this over at the repo for the driver. https://github.com/appium/ruby_lib

**Comment by xsmaster** [comment]
Sorry about that. Thanks @imurchie
