### ISSUE TITLE
[Android][Appium 1.3.7] App Crash - NSInvalidArgumentException

### ISSUE THREAD

**Issue by xsmaster** [appium/appium#4811]
You can see I had the Appium 1.3.7 GUI running on a Mac. I was using ARC (Appium Ruby Console) and forgot about it. I was not finding the elment i wanted to see. So I opened the app inspector. App Crash.

I got the app to crash twice using those repro steps. 

I was running Genymotion with an Android Emulator. ping me if I forgot any details.

[appium.txt]
[caps]
platformName = "Android"
deviceName = "Android"
app = "PATH_TO_APK"

Process:               Appium [9900]
Path:                  /Applications/Appium.app/Contents/MacOS/Appium
Identifier:            com.appium.Appium
Version:               1.3.7 [Ophiuchus] (0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Appium [9900]

Date/Time:             2015-03-30 15:00:54.354 -0500
OS Version:            Mac OS X 10.10.2 (14C1514)
Report Version:        11

Time Awake Since Boot: 46000 seconds
Time Since Wake:       20000 seconds

Crashed Thread:        22

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument'
abort() called
terminating with uncaught exception of type NSException

**Comment by imurchie** [comment]
Please open an issue on the repo for the **.app** (https://github.com/appium/appium-dot-app/issues).
