### ISSUE TITLE
Did not get session redirect from Chrome Driver.

### ISSUE THREAD

**Issue by ashokkumarg** [appium/appium#4813]
I'm trying to run a Webivew application through the appium server with eclipse (selelnium).

Whenever I try to run, It works very well at the first time and it fails from the second time.

In the first time run, It enters the username, password and clicking the login button correctly.

But, When I run it for the second time I'm getting an error in eclipse console like

**(Original error: Did not get session redirect from Chromedriver)**

Then to make it run. 
I need to manually close the chromedriver in task manager.

**In Task Manager --> Process-->chromedriver.exe (End the process)**

![chrome](https://cloud.githubusercontent.com/assets/7566850/6913896/17cdefa6-d7a3-11e4-9864-7098cc9f60b5.png)

After that If I run the code it works good.

So it works very well when I run the first time and in the second time it fails.

**CODE**

    public class LoginPage {
	
	static AppiumDriver driver = null;	
	
	public static void main(String[] args) throws InterruptedException, ExecuteException, IOException 
	{
		String deviceName = "Google Nexus 5 - 4.4.4 - API 19 - 1080x1920";
		String cmd = "C:\\Program Files\\Genymobile\\Genymotion\\player --vm-name \""+deviceName+"\"";
		Runtime rt = Runtime.getRuntime();
		Process p = rt.exec(cmd);
		
		System.out.println("SetUp is started");
	
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(CapabilityType.BROWSER_NAME, ""); 
		capabilities.setCapability("automationName","appium");
		capabilities.setCapability("deviceName","Google Nexus 5 - 4.4.4 - API 19 - 1080x1920");	
		capabilities.setCapability("platformVersion", "4.4.4");
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability("app","D:/SOFTWARES/Apks/GOA.apk");
					
		driver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities); 
		System.out.println("SetUp is successful and Appium Driver is launched successfully");
		
		Set<String> contextNames = driver.getContextHandles();
		
		for (String contextName : contextNames)
	    {
	    	System.out.println(contextNames);      	    	 
	    		driver.context(contextName);
	    		if (contextName.contains("WEBVIEW"))
	    		{
		     	driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS); 
		     	driver.findElement(By.id("txtUserName")).sendKeys("test1@gmail.com");
		     	driver.findElement(By.id("txtPassword")).sendKeys("test1");
		     	driver.findElement(By.id("btnLogin")).click();
	    		}
	    }
	}
     }

**Comment by ashokkumarg** [comment]
@0x1mason Any suggestions?

**Comment by 0x1mason** [comment]
Yes, there's a fix for this in 1.3.7.

**Comment by ashokkumarg** [comment]
@0x1mason I have removed the older version and installed the new version of appium 1.3.7.1
When running the appium server I'm getting this error

> Starting Node Server
> info: Welcome to Appium v1.3.7 (REV 72fbfaa116d3d9f6a862600ee99cf02f6d0e2182)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"app":"D:\\SOFTWARES\\Apks\\GOA.apk","address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"18","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"D:/SOFTWARES/Apks/GOA.apk","platformVersion":"4.4.4","automationName":"appium","browserName":"","platformName":"Android","deviceName":"Google Nexus 5 - 4.4.4 - API 19 - 1080x1920"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from desired caps: D:\SOFTWARES\Apks\GOA.apk
> info: [debug] Creating new appium session 15a7dc11-8789-4dff-970b-05e2709bcab2
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_31
> info: [debug] Checking whether adb is present
> warn: The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
> info: [debug] executing cmd: where adb
> info: [debug] Cleaning up android objects
> error: Failed to start an Appium session, err was: Error: Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
> info: [debug] Cleaning up appium session
> info: [debug] Error: Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
>     at null.<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:126:12)
>     at ChildProcess.exithandler (child_process.js:641:7)
>     at ChildProcess.EventEmitter.emit (events.js:98:17)
>     at maybeClose (child_process.js:743:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.)","origValue":"Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path."},"sessionId":null}
> info: <-- POST /wd/hub/session 500 283.563 ms - 342 


But previously I have kept the environment variables.

**Comment by ashokkumarg** [comment]
@0x1mason  I have installed the latest version 1.3.7.1. Still the same issue exist.

**Comment by ashokkumarg** [comment]
@0x1mason  I freshly started the appium by **checking the Override existing session checkbox**.
I run it for more than 5 times. It goes well.
When I **uncheck the Override existing session checkbox**. It gets failed.

Is there any relationship occurring here?

**Comment by 0x1mason** [comment]
I'm assuming you resolved the adb issue.  The session override requirement
will be fixed in 1.4, which will be out in the next 3-4 weeks.

I didn't know they had published 1.3.7 for Appium.exe.  That's great.

**Comment by ashokkumarg** [comment]
@0x1mason  Thank you Eric !
