### ISSUE TITLE
[Android][Appium 1.3.7] Could not press button "OK" of the numeric keyboard

### ISSUE THREAD

**Issue by vietnq254** [appium/appium#4815]
Hello,

Manually, I enter a number in the edit text by using a numeric keyboard and then I press "OK" so the number will be saved in the list.
I tried to automate with Appium but nothing happen when I use this code:
```
AndroidDriver dr;

dr.sendKeyEvent(AndroidKeyCode.ENTER);
dr.sendKeyEvent(160);// KEYCODE_NUMPAD_ENTER
```
One more thing I have the same problem with #4742 when I use unicode keyboard.
```
capabilities.setCapability("unicodeKeyboard", true);
capabilities.setCapability("resetKeyboard", true);
```

**Comment by sebv** [comment]
Anyway  we can reproduce this using an opensource app? Maybe you need to select the keyboard before sending the key event.

**Comment by ktronic80** [comment]
I did a short test for #4742 which reproduces the problem with back button using the Selendroid test app.
https://gist.github.com/ktronic80/675abc2838d92005abdc
Appium Java Client: 2.2.0
Android Emulator with 4.2.2.

With Appium version 1.3.4 the test is passing and with 1.3.7 it is falling, the back button is not working.
When you run it with 1.3.7 on a fresh started emulator and set unicodeKeyboard to false all is working. When you run with unicodeKeyboard set to true and set it to false in the next run it is still falling until you manualy uninstall the Appium Android Input Manager App.

**Comment by moizjv** [comment]
duplicate
