### ISSUE TITLE
Version 1.3.4  Selendroid mode，can not start with intent arguments 

### ISSUE THREAD

**Issue by xiajikaluli** [appium/appium#4816]
My capabilities below:
	DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName","123");
        capabilities.setCapability("automationName", "Selendroid");
     
       capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("platformVersion", "4.1.2");
        capabilities.setCapability("udid", udid);
        capabilities.setCapability("appPackage", appPackage);
        capabilities.setCapability("appActivity", appActivity);
    capabilities.setCapability("optionalIntentArguments","--es key value");
 driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

When I start the app in testcase,the intent arguments  is not  delivered to app.
But I runing the adb command  show in the appium client Console to start the app  is success；
Has anybody encounter this issue？

**Comment by jlipps** [comment]
please send in your appium logs

**Comment by xiajikaluli** [comment]
Appium Log：

> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\adk\platform-tools\adb.exe -s 9306badf shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: D:\adk\platform-tools\adb.exe -s 9306badf shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] executing cmd: D:\adk\platform-tools\adb.exe -s 9306badf shell "dumpsys window"
> info: [debug] Screen is unlocked, continuing
> info: [debug] executing cmd: D:\adk\platform-tools\adb.exe -s 9306badf shell "am instrument -e main_activity 'com.zcresearch.longxingpursebankofliuzhou.CheckActivity' com.zcresearch.longxingpursebankofliuzhou.selendroid/io.selendroid.ServerInstrumentation"
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
> info: [debug] Selendroid server is alive!
> info: [debug] Listening for Selendroid logs
> info: [debug] Creating Selendroid session
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session","method":"POST","json":{"desiredCapabilities":{"warnings":{},"desired":{"automationName":"Selendroid","app":"D:\\workspace\\appAutoTest\\apk\\SPTSM.apk","deviceName":"123","platformName":"Android","appActivity":"com.zcresearch.longxingpursebankofliuzhou.CheckActivity","udid":"9306badf","appPackage":"com.zcresearch.longxingpursebankofliuzhou","optionalIntentArguments":"-e se_id 1400000A032002529563"},"automationName":"Selendroid","app":"D:\\workspace\\appAutoTest\\apk\\SPTSM.apk","deviceName":"123","platformName":"Android","appActivity":"com.zcresearch.longxingpursebankofliuzhou.CheckActivity","udid":"9306badf","appPackage":"com.zcresearch.longxingpursebankofliuzhou","optionalIntentArguments":"-e se_id 1400000A032002529563"}}}
> info: [debug] Successfully started selendroid session
> info: [debug] Waiting for pkg "com.zcresearch.longxingpursebankofliuzhou" and activity "com.zcresearch.longxingpursebankofliuzhou.CheckActivity" to be focused
> info: [debug] Getting focused package and activity

Sorry，I said before has some mistake。Using Selendroid ,the  Console did not show the "am start" command .

**Comment by xiajikaluli** [comment]
@jlipps
Appium Log：

info: [debug] Getting device API level
info: [debug] executing cmd: D:\adk\platform-tools\adb.exe -s 9306badf shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: D:\adk\platform-tools\adb.exe -s 9306badf shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
info: [debug] executing cmd: D:\adk\platform-tools\adb.exe -s 9306badf shell "dumpsys window"
info: [debug] Screen is unlocked, continuing
info: [debug] executing cmd: D:\adk\platform-tools\adb.exe -s 9306badf shell "am instrument -e main_activity 'com.zcresearch.longxingpursebankofliuzhou.CheckActivity' com.zcresearch.longxingpursebankofliuzhou.selendroid/io.selendroid.ServerInstrumentation"
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
info: [debug] Selendroid server is alive!
info: [debug] Listening for Selendroid logs
info: [debug] Creating Selendroid session
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session","method":"POST","json":{"desiredCapabilities":{"warnings":{},"desired":{"automationName":"Selendroid","app":"D:\workspace\appAutoTest\apk\SPTSM.apk","deviceName":"123","platformName":"Android","appActivity":"com.zcresearch.longxingpursebankofliuzhou.CheckActivity","udid":"9306badf","appPackage":"com.zcresearch.longxingpursebankofliuzhou","optionalIntentArguments":"-e se_id 1400000A032002529563"},"automationName":"Selendroid","app":"D:\workspace\appAutoTest\apk\SPTSM.apk","deviceName":"123","platformName":"Android","appActivity":"com.zcresearch.longxingpursebankofliuzhou.CheckActivity","udid":"9306badf","appPackage":"com.zcresearch.longxingpursebankofliuzhou","optionalIntentArguments":"-e se_id 1400000A032002529563"}}}
info: [debug] Successfully started selendroid session
info: [debug] Waiting for pkg "com.zcresearch.longxingpursebankofliuzhou" and activity "com.zcresearch.longxingpursebankofliuzhou.CheckActivity" to be focused
info: [debug] Getting focused package and activity
Sorry，I said before has some mistake。Using Selendroid ,the Console did not show the "am start" command .

**Comment by paymand** [comment]
It's known limitation of Selendroid. See https://github.com/selendroid/selendroid/issues/546#issuecomment-54981684

**Comment by xiajikaluli** [comment]
@paymand 
Thank you

**Comment by netd-eric** [comment]
So it's no way support intent arguments on Selendroid?
