### ISSUE TITLE
Version 1.3.4，Selendroid mode can not call startActivity() and lock() method

### ISSUE THREAD

**Issue by xiajikaluli** [appium/appium#4817]
Version 1.3.4，Selendroid mode can not call startActivity() and lock() method；
who knows the solution？

**Comment by jlipps** [comment]
I'm not sure these make sense in the Selendroid context. With Selendroid, you can only automate the app that you have started the test with. We could allow you to call `startActivity()`, but you wouldn't be able to automate the thing you started... Likewise with `lock()`, we could allow you to lock the screen, and even unlock it again, but that would end the test session.

**Comment by xiajikaluli** [comment]
I got it.
But how can I achieve lock and unlock  in Level  lower than  17.
I want to test an APP contain NFC ，so I want using the lock and unlock to reset NFC .
Or is there other method to  achieve this purpose?

**Comment by Jonahss** [comment]
You might not be able to at api level lower than 17. @jlipps would you agree?

**Comment by jlipps** [comment]
I would contact the Selendroid project and ask them to add these endpoints
