### ISSUE TITLE
iOS: Failed to execute simple press and MoveTo

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#4818]
server: 1.3.6, xcode 6.2, emulator 8.1

Java code:
ta1.press(100, 100).waitAction(300).moveTo(10, 0).release().perform();

Appium logs:
info: --> POST /wd/hub/session/af7884f8-ce6c-45bd-bbb8-05d986866e0f/touch/perform {"actions":[{"action":"press","options":{"y":100,"x":100}},{"action":"wait","options":{"ms":300}},{"action":"moveTo","options":{"y":0,"x":10}},{"action":"release","options":{}}]}
info: <-- POST /wd/hub/session/af7884f8-ce6c-45bd-bbb8-05d986866e0f/touch/perform 500 949.381 ms - 228 

But next code working correctly:
        ta1.press(100, 100).waitAction(300).moveTo(10, 0).release();
        ta2.press(100, 100).waitAction(300).moveTo(-10, 0).release();
        ma.add(ta1).add(ta2).perform();

**Comment by Jonahss** [comment]
It looks like 300ms is too small an amount of time to wait. It should be between 500 and 6000.
I'll add a check to the java-client.
