### ISSUE TITLE
[Android][Appium 1.3.7] Unlock messes up "home" button on lollipop

### ISSUE THREAD

**Issue by lawrencebautista** [appium/appium#4821]
Hey guys I am running Appium tests on several Lollipop devices, and noticed that after it unlocks the device, the Home button will no longer work. This occurs on every lollipop device i've tried so far (HTC One, Nexus 6, and emulator).

**Comment by moizjv** [comment]
@lawrencebautista can you paste appium logs?

**Comment by Jonahss** [comment]
Referencing #5080

**Comment by SrinivasanTarget** [comment]
@triager please close
