### ISSUE TITLE
Anable to get location of element in Ipad 

### ISSUE THREAD

**Issue by jainswati02** [appium/appium#4822]
Hi All,

I am using python with appium to automate our ipad app.
For one of my test case I need to get location of a toolbar but no luck.

I tried using get_element_attribute function that appium library provide.
But I get below error message 

The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.

I tried element .getLocation() but that also doesn't work.
Please let me know how I can get element location using python.

**Comment by apollo613** [comment]
element.location works for me.

**Comment by jainswati02** [comment]
Thanks. It worked for me too. I was trying some thing wrong.
