### ISSUE TITLE
Proposal how to support Toast Messages on Android

### ISSUE THREAD

**Issue by yahman72** [appium/appium#4824]
I decided to open a new issue for this enhancement since the #968 was closed with "closed because Google needs to add this to uiautomator" comment.

IMHO there would be a way to support this by using the `Accessiblity Services` i.e. 
1) implement a `ToastRecorder` app that catches & records the Toasts (see http://stackoverflow.com/questions/10659734/detecting-toast-messages) 
2) include that app in the appium apk's that are installed on the device
3) enhance the Appium API to access the `ToastRecorder` data

In that stackover thread is a link to an App that is recoding Toasts. Currently I'm using that App to verify Toasts. To support this in Appium would be much better because using an extra app is pretty cumbersome for the verification. Currently I need to do the following:
1) run the tests for my app "normally" with appium
2) After execution start that Toaster App and verify that all expected Toast were recorded.

**Comment by jlipps** [comment]
this could be a good approach. appium could even make the toastrecorder part of the bootstrap. i added this to the features milestone.

**Comment by yahman72** [comment]
A quick update on this:
Adding toastrecorder part of the bootstrap might be tricky, see #4910

I was running the first tests without appium (i.e. just started actions by adb commands) but as soon as I started using appium for the tests the toast recording stopped. I suspect that this is an issue with the UiAutomator, see #4910 for more details.

**Comment by bootstraponline** [comment]
This will probably be worked around by using droiddriver in instrumentation mode. I don't think we'll get uiautomator to stop clobbering the accessibility services.

**Comment by gourav999** [comment]
What is accessbility service class? How can we use this? Can anyone explain me in detail?

**Comment by jbxberg** [comment]
@bootstraponline , can you elaborate how a workaround using droiddriver might look like?

**Comment by bootstraponline** [comment]
With the new android backend we have access to Instrumentation and can thus take advantage of the android support test classes ([such as Espresso](http://stackoverflow.com/questions/28390574/checking-toast-message-in-android-espresso)). I have an [example of mixing & matching droiddriver/espresso](https://github.com/appium/droiddriver_examples/blob/eedcb261ddcabab5111cdc7c0f420428a0918f82/espresso_sample/espresso/BasicSample/app/src/androidTest/java/com/example/android/testing/espresso/BasicSample/DDTest.java). Unfortunately this doesn't do anything to help existing appium users until the new uiautomator v2 driver is ready.

**Comment by fruch** [comment]
+1

**Comment by proudSDET** [comment]
Hi Appium team,
Is this going to be supported by Appium anytime soon? Are there any plans to support this in near future?

**Comment by chrisjywu** [comment]
@proudSDET same question from me.. 

If appium ready to support toast in new 1.5.x version.  i will upgrade my appium version immediately (i am current in 1.4.13 using selendroid mode)

**Comment by jlipps** [comment]
There's no ETA for this feature. Once the UiAutomator v2 driver is out, we can prioritize it for that driver.

**Comment by Pastel001** [comment]
can appium support mobile blackbox test perfectly now?
i dont know how to get a toast
i dont kow how to get a SMS...
so many difficulties...
i am at a loss what to do

**Comment by xiaominwanglast** [comment]
no way

**Comment by Naresh-Edla** [comment]
As suggested, I implemented this Toast recorder by extending AccessibilityService and make it available to **adb shell am broadcast -a toastmessage.get** . However, It's not working with Appium since **Uiautomator kills all the running services** . Please let us know if you have any other alternative.

**Comment by SrinivasanTarget** [comment]
@triager please close
