### ISSUE TITLE
iOS 8.3 support

### ISSUE THREAD

**Issue by jlipps** [appium/appium#4828]
@imurchie is already working on this. Appium should fully support iOS 8.3 / xcode 6.3

**Comment by jwallis** [comment]
This is a catch-all bucket for ios 8.3?  Do we typically have a bucket like this for Xcode versions as well or does this overlap enough to contain those bugs as well?

**Comment by jlipps** [comment]
this is essentially the task of making sure that appium's existing testsuite passes on ios 8.3 (i.e., basic support). at that point we'll probably close this and track 8.3 issues independently. if you have an issue, go ahead and create a github issue to track it.

**Comment by jwallis** [comment]
Sounds good.  No issue thus far.

**Comment by imurchie** [comment]
If you do have an issue, linking to this one (e.g., "related to #4828") won't hurt and might help.

**Comment by r56ty** [comment]
Is this confirmed that iOS 8.3 /xcode 6.3 is supported with Appium. I am not able to launch tests after upgrading - neither on the Simulator nor on the device after upgrading (before the latest upgrades both were working well). On simulator i get- instruments crashed on startup and on device i get FRuitstrap crash. However, i am able to install the app on the simulator from Xcode - its just the Appium tests are failing for me. Not sure, if others have run into similar situation or if its a m/c /configuration issue at my end.

**Comment by amedvedjev** [comment]
we do not have problem with latest xcode 6.3, server 1.3.6, java-client 2.1.0 to start client with iOS 8.3.

**Comment by jlipps** [comment]
@imurchie has reported all the tests pass on ios 8.3 with recent updates. closing this basic tracking issue for now.

**Comment by mahvishsiddiqui** [comment]
This issue is closed but I am experiencing similar issue as @r56ty.  I am able to install the app on the device using Appium tests, but I get instruments crashed on startup on device as soon as test app is launched by Appium tests

**Comment by imurchie** [comment]
Can you link to the description of the issue? And can you provide details about your system. What version of Xcode? What version of Appium? Etc.
