### ISSUE TITLE
Textfields(1) method  throws the following error " Selenium::WebDriver::Error::WebDriverError:unexpected response, code=404, content-type="text/plain"        That URL did not map to a valid JSONWP resource" 

### ISSUE THREAD

**Issue by rakeshramesh** [appium/appium#4833]
Here goes my simple code - 
          
     def desired_caps
    {
      caps: 
    {
        platformName: 'Android',
        platformVersion: '4.3',
        deviceName: 'Samsung SM-T330',
        app: APP_PATH,
        appPackage: 'com.xxxx.main',
        appActivity:  '.MainActivity'

    },

    configuration:
    {
           url: 'http://0.0.0.0:4723/wd/hub/status',
     },

   
     }
     end

    Appium::Driver.new(desired_caps).start_driver
    Appium.promote_appium_methods Object
    find_element(:id,'android:id/action_bar_title').click
    textfields(1)

The last line "textfields(1)" throws the following error 
" Selenium::WebDriver::Error::WebDriverError:unexpected response, code=404, content-type="text/plain"        That URL did not map to a valid JSONWP resource"

**Comment by 0x1mason** [comment]
You're URL is wrong. `http://0.0.0.0:4723/wd/hub`
