### ISSUE TITLE
implement driver.manage().logs().get("server") to get the appium server log 

### ISSUE THREAD

**Issue by hyeung-trulia** [appium/appium#4835]
currently for appium, there are two types of log you can get, one is "logcat" and the other is "client". logcat is getting the "adb logcat" log back and actually I am not sure what "client" log type is about since everytime, when I try it, it always returns nothing. 

One improvement I really want is to be able to get back the appium server log so I can see what the last error is and attached back to my exception error message.

**Comment by TikhomirovSergey** [comment]
+1
I have just wanted to ask the same :)

**Comment by jlipps** [comment]
Interesting, seems like an easy feature to implement. Might be memory concerns though if the log grows too large.

**Comment by hyeung-trulia** [comment]
@jlipps  agree. so it would be even better if there is a way to control the amount of log I want to get back. I already did run into the problem when the logcat log size is too big and hung the test. Currently, to sort of work around this log size too big problem, I get the log once at the beginning of the test to "clear" it up.

**Comment by TikhomirovSergey** [comment]
>Interesting, seems like an easy feature to implement. Might be memory concerns though if the log grows too large.

What is this action 
```java
driver.manage().logs().get("server");
```
will extract logs only for current session? If it will extract all logs then clients can throw exceptions. OutOfMemoryException of the Java side, for example.

**Comment by TikhomirovSergey** [comment]
I think there is some work that has to be done on the client side...
@jlipps @hyeung-trulia 
What if there were an Appium-specific parameter for the log extracting? Like that 
```java
driver.manage().logs().get("appium_server");
```

**Comment by hyeung-trulia** [comment]
@TikhomirovSergey Right now, appium server only supports one session at a time (@jlipps : correct me if I am wrong) so there should not be any session mixing problem.

**Comment by TikhomirovSergey** [comment]
@hyeung-trulia I've meant that this action should extract logs of the CURRENT session, not all sessions that have been launched at the server :)

**Comment by jlipps** [comment]
Since this is a command that will be run from a client for a particular session, we will always want this to be scoped to the session.

But I don't think we've addressed my concerns that storing all the logs for one session in Appium's memory might lead to issues. I think the only thing to do is implement the feature and run some memory tests during long sessions.

**Comment by hyeung-trulia** [comment]
do we need to store all the log all in memory? can we store the log in a tmp file? and limit the size of the tmp file?

**Comment by jlipps** [comment]
We could do that but at some point have to get the whole thing in memory to send to the client anyway

**Comment by hyeung-trulia** [comment]
@Jonahss and @jlipps  is this being worked on already? if not, i can submit a pull request on this.

**Comment by jlipps** [comment]
No one is currently working on this, I'd be happy to take a look at a PR!

**Comment by agepox** [comment]
@jlipps 
Why this pull request was not accepted yet? this feature has huge value for grid tests...

**Comment by Jonahss** [comment]
Oh! the pull request was just never submitted. I can see @hyeung-trulia forked and made a commit, but didn't generate a pull request through github. Could you create a pull request?

**Comment by romainlouvet** [comment]
up

**Comment by Fanch-** [comment]
@hyeung-trulia Could you send a PR? , I'm also interested in getting back the appium server log, mostly to check appium issues.

**Comment by tewner** [comment]
Hi All! 
We would LOVE to be able to get the system.log from the running Simulator or Device! Any ideas?

**Comment by Jonahss** [comment]
Ok, we should mark this as something to get into a minor version after appium 1.5.

**Comment by romainlouvet** [comment]
+1

2015-12-01 19:19 GMT+01:00 Jonah <notifications@github.com>:

> Ok, we should mark this as something to get into a minor version after
> appium 1.5.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/4835#issuecomment-161053056>.
>



-- 
*Romain LOUVET*

*06.20.36.32.10*
*www.romainlouvet.fr <http://www.romainlouvet.fr>*

**Comment by bennid** [comment]
Has there been any planning / movement on this enhancement?

**Comment by mykola-mokhnach** [comment]
Done for android and ios in Appium@beta

**Comment by tfcardoso** [comment]
@mykola-mokhnach when I do driver.manage().logs().getAvailableLogTypes(); I only get logcat and client type (being that client is also always empty for me).

Can you point me in the right direction of acquiring server logs?

**Comment by mykola-mokhnach** [comment]
@tfcardoso Are you sure you have the recent beta? Any logs to show?

**Comment by tfcardoso** [comment]
This is running on windows:

https://gist.github.com/tfcardoso/0eeefbacb3ad2a9286f3a22c62e9d502

**Comment by mykola-mokhnach** [comment]
What if you uninstall you beta and install it again?

**Comment by tfcardoso** [comment]
https://image.prntscr.com/image/ms_xWyBrS__2xaHmltHLkA.png

nice 👍 Strange, but nice. thx

**Comment by tfcardoso** [comment]
I though it was everything until this commit https://github.com/appium/appium/commit/4bf6c6e8fc5be353eb689863d8446618dd87e02f

Anyway, should this "server" option work in real devices?

Its returning:

    Responding to client with driver.getLog() result: null


https://gist.github.com/tfcardoso/ccc2485f69603fdeff95321a2e2c581d

**Comment by mykola-mokhnach** [comment]
this might be a bug. Please report it separately if it is reproducible.

**Comment by ChauhanPandaNeha** [comment]
Hi All,

Can anyone please help me with my Appium Queries relevant to the information shared above?
Can we read the appium logs at run-time using c#?

Request you to please respond if anyone knows the solution to this.

Thanks & Regards,
