### ISSUE TITLE
Key log-timestamp don't work

### ISSUE THREAD

**Issue by urtow** [appium/appium#4838]
Hello!

I start appium (1.3.7) with --log-timestamp but here os log:

2015-04-01 19:35:10:864 - info: --> GET /wd/hub/status {}

No timestamp :(
Same in console or log file.

MacOS 10.10

**Comment by jlipps** [comment]
`2015-04-01 19:35:10:864` is a timestamp

**Comment by urtow** [comment]
i wait for timestamp as unix timestamp - seconds from epoch.

Thank you
