### ISSUE TITLE
send_keys input wrong characters onto the screen

### ISSUE THREAD

**Issue by nyi-aa** [appium/appium#4844]
Test device: Galaxy S4, Android 4.3
Appium Python client: 0.14
Appium server: 1.3.7

I use send_keys('123456789') but some times on the screen the final result may be "124567893". It doesn't always happen but it's annoyed when it happens.

**Comment by amaanmemon** [comment]
Youn can also send keys with driver.deviceKeyEvent(KEY_CODE)
This Link will help you a lot: http://developer.android.com/reference/android/view/KeyEvent.html

**Comment by nyi-aa** [comment]
@amaanmemon yeah, you are right. But it's a little tricky. 

When I used Appium server 1.3.5, there was no such a problem. So this would be a bug introduced in recent updates.

**Comment by jlipps** [comment]
I've heard reports of this for a long time. I think it's a UiAutomator-level issue that I don't think can be fixed in Appium. I guess we could validate the text after we input it and verify it matches what we expect, and retry if it doesn't. Could you pass in your Appium logs anyway? Just to verify that Appium thinks it did the right thing

**Comment by nyi-aa** [comment]
@jlipps Try several times today. I'm sorry that I cannot reproduce it temporarily.

**Comment by polaris007** [comment]
I also encountered this issue. And it happens frequently in my environment.
Test device: Coolpad 8730L, Android 4.3
Appium java-client: 2.2.0
Appium server: 1.3.7.2

I invoked sendKeys("admin@abc1.com") but often got "admin@abc.1com" on mobile. Here are logs of Appium server:
--------------------------------------------------------------------------------------------------
> info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"12"},"sessionId":"d8859016-cb39-4522-b71b-351410383488"}
> info: <-- POST /wd/hub/session/d8859016-cb39-4522-b71b-351410383488/element 200 86.450 ms - 88 {"status":0,"value":{"ELEMENT":"12"},"sessionId":"d8859016-cb39-4522-b71b-351410383488"}
> info: --> POST /wd/hub/session/d8859016-cb39-4522-b71b-351410383488/element/12/value {"id":"12","value":["admin@abc1.com"]}
> info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"12","text":"admin@abc1.com","replace":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"12","text":"admin@abc1.com","replace":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: setText
> info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
> info: [debug] [BOOTSTRAP] [debug] Text remains after clearing, but it appears to be hint text.
> info: [debug] [BOOTSTRAP] [debug] Text not cleared. Assuming remainder is hint text.
> info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: admin@abc1.com
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"d8859016-cb39-4522-b71b-351410383488"}
> info: <-- POST /wd/hub/session/d8859016-cb39-4522-b71b-351410383488/element/12/value 200 5172.418 ms - 76 {"status":0,"value":true,"sessionId":"d8859016-cb39-4522-b71b-351410383488"}
> info: --> POST /wd/hub/session/d8859016-cb39-4522-b71b-351410383488/element/13/clear {"id":"13"}
> info: [debug] Pushing command to appium work queue: ["element:clear",{"elementId":"13"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:clear","params":{"elementId":"13"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: clear
> info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"d8859016-cb39-4522-b71b-351410383488"}
> info: <-- POST /wd/hub/session/d8859016-cb39-4522-b71b-351410383488/element/13/clear 200 2510.650 ms - 76 {"status":0,"value":true,"sessionId":"d8859016-cb39-4522-b71b-351410383488"}
> info: --> POST /wd/hub/session/d8859016-cb39-4522-b71b-351410383488/element/13/value {"id":"13","value":["password"]}
