### ISSUE TITLE
Android real device - softkeyboard gets in the way

### ISSUE THREAD

**Issue by filipesperandio** [appium/appium#4847]
Running appium tests against a emulator or genymotion-vm where I can disable software keyboard works fine.
My problem is targeting real device. Keyboard stays on top and driver can't click in the right fields.
Is there a workaround for this?

**Comment by jlipps** [comment]
What would you do as a user to make the keyboard go away?

**Comment by filipesperandio** [comment]
I'd like to simulate an external keyboard only, but I solved the problem
making sure I hide the softkeyboard after filling each field.

**Comment by jlipps** [comment]
Great
