### ISSUE TITLE
Can I send  adb command  using  Appium?

### ISSUE THREAD

**Issue by xiajikaluli** [appium/appium#4848]
Can I send  adb command using  Appium?
I want to send "adb devices" to get udid of valid devices.
Or is there any other method to achieve this purpose？

**Comment by xiajikaluli** [comment]
@amaanmemon 
Is it right that add the javascript code to js File in Appium server？
Whick File I should edit？
How could I run the  method in testcase？

**Comment by paymand** [comment]
You can use [appium-adb](https://github.com/appium/appium-adb).

```js
var ADB = require('appium-adb');
var adb = new ADB({});
adb.getDevicesWithRetry(function (err, devices) {
  if (err) {
    console.log(err);
  } else {
    // you should have an array of connected devices in 'devices'
    console.log(devices);
  }
});
```

**Comment by xiajikaluli** [comment]
@paymand 
I develop with java ，which jar I should dependent？

**Comment by paymand** [comment]
@xiajikaluli: No idea, not sure if this is exposed to Java client bindings. @Jonahss might know.

**Comment by jlipps** [comment]
you should just use java's ability to execute system processes and build up your adb commands that way. there might even be another java library that interfaces with adb.

**Comment by xiajikaluli** [comment]
@jlipps 
Thank you for your advice.I resolved this Issue with TelnetClient.

**Comment by madhuCNKony** [comment]
Hi I want to use PUSH and PULL adb commands, in appium.
How can I achieve this?
