### ISSUE TITLE
Ignore invalid selectors when using multiple UiSelectors

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#4859]
Requesting a resourceId selector will always error on an API < 17 device.

> This is considered a multi-selection scenario where more than one UiSelector is provided. The appium server should simply ignore the resourceId selector on devices that are <= 18 when we've given other selectors that are valid for the current API level. This approach would also fix the problem in all the bindings instead of just for Ruby.
> 
> https://github.com/appium/ruby_lib/issues/316

I think we need a redesign to fix the underlying problem #4858. Until then, it'd be nice to patch this specific issue by making resourceId conditional based on the API level of the device. Clients can't do this because they don't know what API level the device is.

**Comment by jlipps** [comment]
:+1:

**Comment by mykola-mokhnach** [comment]
Devices running API < 17 are rare like dinosaurs nowadays. Thus closed.
