### ISSUE TITLE
Finding ,clicking,tap an element in iOS is taking very long time

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#4861]
We are executing the some testcases in iOS and we noticed that finding an element or tapping on an element in iOS is taking more time . We use the basic API's like find_element_by_id and click() for finding and clicking on elements. It takes 
![untitled](https://cloud.githubusercontent.com/assets/9447465/7005607/31412194-dc97-11e4-854b-f1ee0d04b011.png)
around 2 to 3 seconds.
Could you provide a solution for this?

**Comment by jlipps** [comment]
Are you using the simulator or a real device?

**Comment by naveenjammula** [comment]
Environment details ::

Device : Iphone5,Iphone 5+ , Iphone6 real device
Appium : ver 1.3.7
Client : appium python client 0.14

**Comment by amedvedjev** [comment]
with real iOS device no wonder that there is 1sec gap between find element and tap/click on it.
more info where it was fixed for emulator only (real device no fix) - https://github.com/facebook/instruments-without-delay

**Comment by Jonahss** [comment]
Has anyone yet figured out how to get around the 1second delay on a real
device?

**Comment by jlipps** [comment]
The 1s delay is unavoidable on a real device; it's on the phone side as well as the instruments side, I think.
