### ISSUE TITLE
my macbook have install ifuse ,but it cause fruitstrap no work, See below for details

### ISSUE THREAD

**Issue by wangcityboy** [appium/appium#4863]
info: [debug] Checking app install status using: /usr/local/lib/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id 2124531c7df6aec70b297ba79bdb2232c522e41a --bundle com.25pp.ppappinstaller2
info: [debug] App is not installed. Will try to install the app.
info: [debug] Installing app using cmd: /usr/local/lib/node_modules/appium/build/fruitstrap/fruitstrap install --id 2124531c7df6aec70b297ba79bdb2232c522e41a --bundle "com.25pp.ppappinstaller2"
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Unable to install [com.25pp.ppappinstaller2] to device with id [2124531c7df6aec70b297ba79bdb2232c522e41a]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.
]
info: [debug] Error: Unable to install [com.25pp.ppappinstaller2] to device with id [2124531c7df6aec70b297ba79bdb2232c522e41a]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.
]
    at /usr/local/lib/node_modules/appium/lib/devices/common.js:147:10
    at ChildProcess.exithandler (child_process.js:662:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Unable to install [com.25pp.ppappinstaller2] to device with id [2124531c7df6aec70b297ba79bdb2232c522e41a]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.\n])","origValue":"Unable to install [com.25pp.ppappinstaller2] to device with id [2124531c7df6aec70b297ba79bdb2232c522e41a]. Error [Error: Command failed: Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.\n]"},"sessionId":null}
info: <-- POST /wd/hub/session 500 6391.726 ms - 586 
^CPPdeMacBook:fruitstrap yunfeiyang$ 

PPdeMacBook:fruitstrap yunfeiyang$ /usr/local/lib/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id 2124531c7df6aec70b297ba79bdb2232c522e41a --bundle com.25pp.ppappinstaller2
[....] Waiting for iOS device to be connected
found device id
found device id
found device id
[  0%] Found device (2124531c7df6aec70b297ba79bdb2232c522e41a), beginning check
There is no app installed!
Assertion failed: (false), function checkAppExists, file fruitstrap.c, line 320.
Abort trap: 6

PPdeMacBook:fruitstrap yunfeiyang$ $ /usr/local/lib/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id a0ee9c874742cdd4bef1b43f148fe72068c58265 --bundle com.25pp.ppappinstaller2
[....] Waiting for iOS device to be connected
found device id
[  0%] Found device (a0ee9c874742cdd4bef1b43f148fe72068c58265), beginning check
App is installed!
Assertion failed: (AMDeviceStartService(device, CFSTR("com.apple.afc"), &afcFd, NULL) == 0), function handle_device, file fruitstrap.c, line 523.

PPdeMacBook:fruitstrap yunfeiyang$ appium -v
1.3.7

note: my app have install to my device

**Comment by wangcityboy** [comment]
below ifuse install command
sudo brew update
sudo brew install libimobiledevice
sudo brew install ifuse

**Comment by paymand** [comment]
We don't use ``fruitstrap`` anymore and are using ``ideviceinstaller`` everywhere. See https://github.com/appium/appium/pull/4790.
Please make sure that you have the latest version of ``ideviceinstaller`` installed.
