### ISSUE TITLE
Run appium scripts on multiple devices

### ISSUE THREAD

**Issue by ggonzalez3** [appium/appium#4866]
We are trying to run automated scripts on multiple iOS devices over WiFi connection. We are able to connect over WiFi from iTunes and sync the device, but, we are not able to detect the device over WiFi with appium. So, seems that appium only works with devices connected through USB cable, is this correct? Does someone knows a way to connect multiple iOS devices over WiFi and send automated tests from aapium? We are able to do that for android with UI Automator and adb over wifi, but not for iOS.

**Comment by jlipps** [comment]
No, instruments only works over USB, not wifi
