### ISSUE TITLE
ideviceinstaller should be properly bundled with appium and updated, or should be removed and listed as an external dependency

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#4867]
I'll look into which solution makes more sense. A lot of the libimobiledevice tools are really convenient for Appium, but it's not really easy to bundle right into our system.

Pre-compiled binaries might be the way to go. I'm thinking an npm module which determines your system architecture, then downloads compiled binaries from a hosted source.

**Comment by saikrishna321** [comment]
@jlipps this can be closed, as we already them in the xcuitest doc
