### ISSUE TITLE
Not be able to scroll UIACollectionView with ruby client API

### ISSUE THREAD

**Issue by djwgit** [appium/appium#4868]
- using appium server 1.3.7
- ruby client api, or arc command
- ios simulator 8.2, or 8.1
- a screen with UIACollectionView, try to scroll down as below, it does not scroll the list. 
but on a screen with a mapview, it does works, could pan the map.
<code>
Appium::TouchAction.new.press(x:150,y:200).move_to(x:0,y:300).release.perform
</code>

two issues:

1.  move_to, function name is misleading, its x,y are delta based on current position, not absolute position.

2.  in the server log, 
<code>
info: --> POST /wd/hub/session/6d78ba00-d572-49cb-9731-e75576fdcbfc/touch/perform {"actions":[{"action":"press","options":{"x":150,"y":200}},{"action":"moveTo","options":{"x":0,"y":300}},{"action":"release"}]}
info: [debug] Pushing command to appium work queue: "target.touch([{\"touch\":[{\"x\":150,\"y\":200}],\"time\":0.2},{\"touch\":[{\"x\":150,\"y\":500}],\"time\":0.4}])" 
info: [debug] Sending command to instruments: target.touch([{"touch":[{"x":150,"y":200}],"time":0.2},{"touch":[{"x":150,"y":500}],"time":0.4}])
info: [debug] [INST] 2015-04-07 03:47:45 +0000 Debug: Got new command 15 from instruments: target.touch([{"touch":[{"x":150,"y":200}],"time":0.2},{"touch":[{"x":150,"y":500}],"time":0.4}])
info: [debug] [INST] 2015-04-07 03:47:45 +0000 Debug: evaluating target.touch([{"touch":[{"x":150,"y":200}],"time":0.2},{"touch":[{"x":150,"y":500}],"time":0.4}])
</code>

looks like, appium server translates it into two touch actions, this is not right.
it should be press down on (x1,y1), then drag to (x2,y2), then up.

I saw some post about swipe not working, but in my case, it works on map view, not on a uiaCollectionView, seems, server not doing right job...
anyone, saw the same issue?

thanks..

**Comment by bootstraponline** [comment]
The touch action api is confusing and I'm not sure that the desired behavior is clearly documented. With issues like these in the past, it has been due to a misunderstanding of the API rather than the server having a bug. Hopefully one of the devs can clarify if this is a bug and if so if it's in the client or the server.

**Comment by djwgit** [comment]
@bootstraponline,  
Appium::TouchAction.new.press(x:150,y:200).move_to(x:0,y:300).release.perform  
translated into two touch actions, is this expected ?
if it is,  could you help, what should be the list of actions to perform a drag on UIACollectionView...
thanks.

**Comment by bootstraponline** [comment]
@jlipps Is there a spec somewhere that matches the touchactions in appium? I don't know what's a bug or "feature."

I'm looking for something along the lines of here are the supported methods, their arguments, and exactly what happens when they're invoked.

**Comment by jlipps** [comment]
@bootstraponline it's an earlier draft of the W3C spec. I guess if you look at latest they've updated the spec. matching the new spec is already an appium ticket. I think @imurchie knows the most about this and is probably best suited to evaluate whether this issue is a bug or not

**Comment by djwgit** [comment]
@bootstraponline, @jlipps   thanks for your help...
tried this below, it is translated into target.dragFromToForDuration,  but still does not scroll the UIACollectionView or UIATableView(has cells in it).  while works for MapView.
Appium::TouchAction.new.press(x:150,y:150).wait(2000).move_to(x:150,y:500).release.perform
or 
swipe start_x: 75, start_y: 200, end_x: 75, end_y: 300, duration: 600

info: --> POST /wd/hub/session/95284ae6-d33a-4489-aabc-dd02e473c1d6/touch/perform {"actions":[{"action":"press","options":{"x":150,"y":350}},{"action":"wait","options":{"ms":600}},{"action":"moveTo","options":{"x":150,"y":220}},{"action":"release"}]}
info: [debug] Pushing command to appium work queue: "au.dragApp(150,350,150,220,0.6)"
info: [debug] Sending command to instruments: au.dragApp(150,350,150,220,0.6)
info: [debug] [INST] 2015-04-08 00:47:59 +0000 Debug: Got new command 46 from instruments: au.dragApp(150,350,150,220,0.6)
info: [debug] [INST] 2015-04-08 00:47:59 +0000 Debug: evaluating au.dragApp(150,350,150,220,0.6)
info: [debug] [INST] 2015-04-08 00:47:59 +0000 Debug: target.dragFromToForDuration({x:"150", y:"350"}, {x:"150", y:"220"}, "0.6")
info: [debug] Socket data received (25 bytes)

**Comment by bootstraponline** [comment]
I know with swipe we figured out the server is treating out the args as offsets instead of absolute coordinates. Maybe that will help?

https://github.com/appium/ruby_lib/issues/293

You could also try manually invoking dragApp via execute_script until you find values that work and then try to reverse engineer what the appium server expects for input to get that result.

**Comment by djwgit** [comment]
@bootstraponline thanks, I figured out that is an offset,   the same command works for a mapview, but not for UIACollectionView and UIATableView.   
not sure how could use dragApp in execute_script, could you give an example...
thanks...

**Comment by jlipps** [comment]
the reason UICollectionView and TableView aren't working is that gesture recognition is broken in those views. Only limited gesture support is available for them in the form of the "mobile: scroll" script.

**Comment by djwgit** [comment]
@jlipps thanks for clarifying that.  is there an issue I can keep track of it... 

tried this, on a screen with UIATableView, it does not scroll up either... 
execute_script 'mobile: scroll', :direction => 'up'
thanks...

info: --> POST /wd/hub/session/c2f1dfe0-e4eb-4206-a2ea-493c7206bdd1/execute {"script":"mobile: scroll","args":[{"direction":"up"}]}
info: [debug] Pushing command to appium work queue: "au.scrollFirstView('Up')"
info: [debug] Sending command to instruments: au.scrollFirstView('Up')
info: [debug] [INST] 2015-04-08 01:33:50 +0000 Debug: Got new command 23 from instruments: au.scrollFirstView('Up')
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"c2f1dfe0-e4eb-4206-a2ea-493c7206bdd1"}
info: <-- POST /wd/hub/session/c2f1dfe0-e4eb-4206-a2ea-493c7206bdd1/execute 200 126.778 ms - 74 {"status":0,"value":"","sessionId":"c2f1dfe0-e4eb-4206-a2ea-493c7206bdd1"}
info: [debug] [INST] 2015-04-08 01:33:50 +0000 Debug: evaluating au.scrollFirstView('Up')
info: [debug] [INST] 2015-04-08 01:33:50 +0000 Debug: Looking for view of type scrollview
info: [debug] [INST] 2015-04-08 01:33:50 +0000 Debug: Looking for view of type tableview
info: [debug] [INST] 2015-04-08 01:33:50 +0000 Debug: target.frontMostApp().elements()[0].elements()[1].scrollUp()
info: [debug] [INST] 2015-04-08 01:33:50 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-04-08 01:33:50 +0000 Debug: responding with:
info: [debug] [INST] 2015-04-08 01:33:50 +0000 Debug: Running system command #24: /usr/local/Cellar/node/0.12.0/bin/node /Users/***/git-appium/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...

**Comment by bootstraponline** [comment]
https://github.com/appium/appium/issues/4664#issuecomment-77681742

**Comment by djwgit** [comment]
thanks @bootstraponline, hope the simulator will be fixed soon... :-(

**Comment by bootstraponline** [comment]
unfortunately I would not count on apple to fix their buggy software anytime soon. we can hope for the best though.

**Comment by djwgit** [comment]
btw, hope this issue/limitation is documented somewhere in the doc, then easier for users ...

**Comment by jlipps** [comment]
@djwgit it was in the docs [here](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md#bugs-and-workarounds) but I just updated it to reflect the current version situation
