### ISSUE TITLE
 How to execute one machine appium script to another machine(Remote machine)?

### ISSUE THREAD

**Issue by ayosuva** [appium/appium#4873]
I have 2 desktop machines in which Appium script is saved in machine 1 and Appium got installed in machine 2 and android devices also connected in machine 2. now i want to take the script from the machine 1 and execute it in the devices connected in the machine 2. how to achieve this. please suggest me.

**Comment by ayosuva** [comment]
package com.appiumproj.test;    
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.*;

public class Appium {

AppiumDriver driver;

@BeforeClass
public void setUp() throws MalformedURLException{

     //Set up desired capabilities and pass the Android app-activity and app-package to Appium

   DesiredCapabilities capabilities = new DesiredCapabilities();
   capabilities.setCapability(MobileCapabilityType.VERSION, "5.0.2");
   capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
   capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"ZX1D62FPVQ");
   capabilities.setCapability(MobileCapabilityType.APP_PACKAGE, "com.android.calculatord");
   capabilities.setCapability(MobileCapabilityType.APP_ACTIVITY, "com.android.calculator2.Calculator"); 
   driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
}

@Test
public void testCal(){


   WebElement two=driver.findElement(By.name("2"));
    two.click();
    WebElement plus=driver.findElement(By.name("+"));
    plus.click();
    WebElement four=driver.findElement(By.name("4"));
    four.click();
    WebElement equalTo=driver.findElement(By.name("="));
    equalTo.click();

    WebElement results=driver.findElement(By.className("android.widget.EditText"));

    assert results.getText().equals("6"):"Actual value is : "+results.getText()+" did not match with expected value: 6";

    System.out.println("Inside Test Function");
terClass
public void teardown(){


    driver.closeApp();
}
}



I want to execute the same script in remote machine.Android device connected in the remote machine and appium also running remote machine.But the script is in Local machine.

**Comment by jlipps** [comment]
instead of using 127.0.0.1 as the remote url, use the actual address of the remote machine. 127.0.0.1 is localhost.

**Comment by jlipps** [comment]
(also, when you start the appium server on the remote machine, use `-a 0.0.0.0` to get it to listen on all interfaces)

**Comment by ayosuva** [comment]
how to use -a 0.0.0.0 ? where i need to run -a 0.0.0.0? and

**Comment by jlipps** [comment]
when you launch the appium server

**Comment by ayosuva** [comment]
from command prompt? buit i am using appium windows tool

**Comment by jlipps** [comment]
I don't know how to do it from the windows GUI. You could ask the windows GUI project

**Comment by ayosuva** [comment]
ok can you suggest some link/video about appium remote execution?

**Comment by jlipps** [comment]
You could follow [the docs](http://appium.io/slate/en/master/?javascript#running-appium-on-windows)
