### ISSUE TITLE
How to use ideviceinstaller to instead fruitstrap

### ISSUE THREAD

**Issue by wangcityboy** [appium/appium#4874]
Currently appium 1.3.7 when it starts, it will default  check  the app is installed  at real device, But i don't  know How to use ideviceinstaller to instead fruitstrap
![qq20150408-3](https://cloud.githubusercontent.com/assets/5433502/7041116/2423c656-de09-11e4-80d6-bdc3112426e6.png)

**Comment by wangcityboy** [comment]
PPdeMacBook:~ yunfeiyang$ brew install ideviceinstaller
Warning: ideviceinstaller-1.1.0_1 already installed
PPdeMacBook:~ yunfeiyang$

**Comment by Simon-Kaz** [comment]
Current appium  (1.3.7) still uses fruitstrap. Try installing the app from command line using ideviceinstaller, and provide bundleID and UDID in the appium app (instead of .app) so that the app is loaded instead of installed.

**Comment by moizjv** [comment]
@wangcityboy this should be solved with `1.4.0` release

**Comment by amazingHH** [comment]
I 'm trying use the libmobiledevice series software on wince ,It's too hard to me.  Want to go die
