### ISSUE TITLE
./reset.sh --dev broken on mac

### ISSUE THREAD

**Issue by paymand** [appium/appium#4875]
Error:
``
Running "buildApp:UICatalog:iphonesimulator:8.2" (buildApp) task
Using sdk: iphonesimulator...
Cleaning build...
Failed cleaning app, maybe it doesn't exist?
Build settings from command line:
    SDKROOT = iphonesimulator8.2

xcodebuild: error: The directory /Users/opera/src/appium/sample-code/apps/UICatalog does not contain an Xcode project.
``

Looking at UICatalog.zip, it looks like that the Xcode project is not there anymore.

**Comment by jlipps** [comment]
@paymand does it do the same thing with a `./reset.sh --dev --hardcore`? @Jonahss was running into issues with this yesterday as well

**Comment by paymand** [comment]
mmm, ``--hardcore`` did the trick. Now it's even working without it. Let's call this a fix.

**Comment by Jonahss** [comment]
I can't get `/reset.sh --dev` to complete without `--hardcore`. Is that deserving of a second issue?

**Comment by paymand** [comment]
Not really, I'll reopen this issue.

**Comment by moizjv** [comment]
@paymand Thanks for pointing out fixed it. Closing issue.

**Comment by paymand** [comment]
:+1:
