### ISSUE TITLE
getLocation sometimes returning strange results

### ISSUE THREAD

**Issue by respectTheCode** [appium/appium#4878]
I have a UIView that is located at 10, 10 but I often get failing test results like this

```
{
      +  "x": 10
      +  "y": 10
      -  "x": 10.00000043711389
      -  "y": 10.00000043711384
}
```

**Comment by jlipps** [comment]
If you run the corresponding location commands directly in UIAutomation, does it show 10,  10, or the other values?

**Comment by amedvedjev** [comment]
+1. i just round it to (int) if needed tap on it.
