### ISSUE TITLE
"Error: Permission to start activity denied" is displayed for few devices

### ISSUE THREAD

**Issue by TrimNut** [appium/appium#4880]
I have been using a Nexus 5 device and appium is working perfectly fine with it. However, I changed the device to One Plus, the "Error: Permission to start activity denied" error is thrown. This shows that there is no fault with the app permissions.

Are there any device level settings that need to be done for appium to run? Am I missing something here?

**Comment by amedvedjev** [comment]
in settings disable "Protect against harmful apps"

**Comment by TrimNut** [comment]
My One Plus' android version is 5.0.2. There doesn't seem to be any such option. Do you mean enabling "Allow installation of apps from unknown sources?"

**Comment by moizjv** [comment]
@TrimNut did that help?

**Comment by kimbo-slice** [comment]
I had this issue and it was resolved after running "adb root". Hope this helps you as well.
