### ISSUE TITLE
MoveTo behaviour differs for iOS and Android

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#4885]
appium 1.3.6, java-client: 2.1.0
touchAction.press(100,100).moveTo(10,10).release()

with iOSDriver means release at: 110,110
with AndroidDriver means release at: 10,10

Why?

server logs with android:
info: --> POST /wd/hub/session/16983312-f309-49bb-9d6a-37a5d8a07b32/touch/perform {"actions":[{"action":"press","options":{"y":100,"x":100}},{"action":"moveTo","options":{"y":10,"x":10}},{"action":"release","options":{}}]}
info: [debug] Pushing command to appium work queue: ["element:touchDown",{"x":100,"y":100}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchDown","params":{"x":100,"y":100}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchDown
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1776]
info: [debug] [BOOTSTRAP] [debug] Performing TouchDown using element? false x: 100, y: 100
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":10,"y":10}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":10,"y":10}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1776]
info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 10, y: 10
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Pushing command to appium work queue: ["element:touchUp",{"x":10,"y":10}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchUp","params":{"x":10,"y":10}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchUp
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1776]
info: [debug] [BOOTSTRAP] [debug] Performing TouchUp using element? false x: 10, y: 10
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"16983312-f309-49bb-9d6a-37a5d8a07b32"}
info: <-- POST /wd/hub/session/16983312-f309-49bb-9d6a-37a5d8a07b32/touch/perform 200 53.039 ms - 76 {"status":0,"value":true,"sessionId":"16983312-f309-49bb-9d6a-37a5d8a07b32"}

**Comment by jlipps** [comment]
that's a good question. i thought it was an offset in both cases. any ideas @imurchie?

**Comment by imurchie** [comment]
It should be an offset in both cases. The code is there, and used for multi gestures, but not for normal ones. Strange.
