### ISSUE TITLE
Android: MultiTouch action does not take affect on device

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#4886]
appium 1.3.6, java-client 2.1.0, real phone Android 4.4.2

ZoomOut action with GoogleMap view:
ta1.press(center.getX(), center.getY() - 250).moveTo(0, 100).release();
ta2.press(center.getX(), center.getY() + 250).moveTo(0, -100).waitAction(2000).release();
ma.add(ta1).add(ta2).perform();

I see with enabled Development Menu option on phone that tap happening correctly and no any errors in server logs BUT no action happening on phone.

When i use only oneTouch action like: ta1.press(X1,Y1).moveTo(X2,Y2).release().perform() - no any problem and Google map moving in correct direction.

any help?

Example of server log:
info: --> POST /wd/hub/session/8668bfd7-fda2-42dd-9878-a389c4ba30c7/touch/multi/perform {"actions":[[{"action":"press","options":{"y":675,"x":540}},{"action":"moveTo","options":{"y":100,"x":0}},{"action":"release","options":{}}],[{"action":"press","options":{"y":1175,"x":540}},{"action":"moveTo","options":{"y":-100,"x":0}},{"action":"release","options":{}}]]}
info: [debug] Pushing command to appium work queue: ["performMultiPointerGesture",{"actions":[[{"touch":{"x":540,"y":675},"time":0.005},{"touch":{"x":540,"y":775},"time":0.01}],[{"touch":{"x":540,"y":1175},"time":0.005},{"touch":{"x":540,"y":1075},"time":0.01}]]}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"performMultiPointerGesture","params":{"actions":[[{"touch":{"x":540,"y":675},"time":0.005},{"touch":{"x":540,"y":775},"time":0.01}],[{"touch":{"x":540,"y":1175},"time":0.005},{"touch":{"x":540,"y":1075},"time":0.01}]]}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: performMultiPointerGesture
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK","status":0}
info: [debug] Responding to client with success: {"status":0,"value":"OK","sessionId":"8668bfd7-fda2-42dd-9878-a389c4ba30c7"}
info: <-- POST /wd/hub/session/8668bfd7-fda2-42dd-9878-a389c4ba30c7/touch/multi/perform 200 73.133 ms - 76 {"status":0,"value":"OK","sessionId":"8668bfd7-fda2-42dd-9878-a389c4ba30c7"}

**Comment by sebv** [comment]
Possible bug.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by SrinivasanTarget** [comment]
I don't see this in latest rewrite

**Comment by yqxxbomb** [comment]
多点触碰确实不会影响动作，不过最少也得 三点触点，点击触动执行目前弄得差不多了吧！两点的话，你是拉屏幕，不算触！
