### ISSUE TITLE
Not able to perform swipe by co-ordinates (with or without duration) on iphone 6 via inspector or via python scripts

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#4889]
Xcode version: 6.2
iOS: 8.0.2 and 8.1.2

Description: Not able to perform swipe by co-ordinates (with or without duration) on iphone 6 via inspector or via python scripts.
Able to perform same action via scripts on iphone 5 and android. I have tried changing co-ordinates for iphone 6 also, but still not working.

Appium server logs (for swipe via co-ordinates via inspector)

info: --> POST /wd/hub/session/e994ccf1-c136-4709-9e0e-088d77405e10/execute {"script":"mobile: swipe","args":[{"endX":189,"duration":2,"endY":620,"touchCount":1,"startX":188,"startY":574}]}

info: [debug] Tried to execute non-existent mobile command 'swipe'. Most mobile commands have been ported to official client library methods. Please check your Appium library for more information and documentation
info: [debug] Responding to client that a method is not implemented
info: <-- POST /wd/hub/session/e994ccf1-c136-4709-9e0e-088d77405e10/execute 501 1.801 ms - 158

info: --> GET /wd/hub/session/e994ccf1-c136-4709-9e0e-088d77405e10/source {}
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-04-10 10:27:35 +0000 Debug: Got new command 11 from instruments: au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-04-10 10:27:35 +0000 Debug: evaluating au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-04-10 10:27:35 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-04-10 10:27:35 +0000 Debug: responding with:ed":true,"valid":true,"visible":true,"hint":null,"path":"/0/0","x":0,"y":0,"width":375,"height":667},">":[{"UIANavigationBar":{"@":{"name":"Messages","label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0","x":0,"y":20,"width":375,"height":44},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/0","x":0,"y":0,"width":375,"height":64},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/0/0","x":0,"y":64,"width":375,"height":0},">":[]}}]}},{"UIAButton":{"@":{"name":"ico chatview group s","label":"ico chatview group s","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/1","x":319,"y":17,"width":50,"height":50},">":[]}},{"UIAButton":{"@":{"name":"Message Back Button","label":"Message Back Button","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/2","x":5,"y":26,"width":47,"height":30},">":[]}},{"UIAButton":{"@":{"name":"Back","label":"Back","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/3","x":8,"y":31.5,"width":21,"height":21},">":[]}},{"UIAButton":{"@":{"name":"group_15_54_44(3)","label":"group_15_54_44(3)","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/4","x":67.5,"y":25.5,"width":240,"height":33},">":[]}},{"UIAStaticText":{"@":{"name":null,"label":"","value":"","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/5","x":163.5,"y":25.5,"width":42,"height":33},">":[]}},{"UIAImage":{"@":{"name":"btn_chat_online","label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/6","x":210.5,"y":37.5,"width":9,"height":9},">":[]}}]}},{"UIAStaticText":{"@":{"name":"Created by","label":"Created by","value":"Created by","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/1","x":157.5,"y":67,"width":180,"height":16.5},">":[]}},{"UIAStaticText":{"@":{"name":"Publisher","label":"Publisher","value":"Publisher","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/2","x":157.5,"y":78.5,"width":180,"height":20.5},">":[]}},{"UIAStaticText":{"@":{"name":"create time","label":"create time","value":"create time","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/3","x":157.5,"y":92,"width":180,"height":21},">":[]}},{"UIAButton":{"@":{"name":"ico chat minimum","label":"ico chat minimum","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/4","x":321,"y":68,"width":46,"height":42},">":[{"UIAImage":{"@":{"name":"ico_chat_minimum","label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/4/0","x":334,"y":67,"width":20,"height":20},">":[]}}]}},{"UIAStaticText":{"@":{"name":"New","label":"New","value":"New","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/5","x":72.5,"y":71.5,"width":40,"height":15},">":[]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/6","x":107.5,"y":69,"width":40,"height":40},">":[]}},{"UIAImage":{"@":{"name":"ico_play_avatar","label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/7","x":127.5,"y":89,"width":15,"height":15},">":[]}},{"UIAButton":{"@":{"name":"Edit","label":"Edit","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/8","x":375,"y":64,"width":50,"height":50},">":[{"UIAStaticText":{"@":{"name":"Edit","label":"Edit","value":"Edit","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/8/0","x":383,"y":78,"width":33,"height":21.5},">":[]}}]}},{"UI

AButton":{"@":{"name":"Tap to create a new avatar headline","label":"Tap to create a new avatar headline","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/9","x":0,"y":64,"width":375,"height":50},">":[]}},{"UIATableView":{"@":{"name":"Message Chat TableView","label":"Message Chat TableView","value":"rows 1 to 3 of 3","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/10","x":0,"y":64,"width":375,"height":343},">":[]}},{"UIAButton":{"@":{"name":"Message Extension Button","label":"Message Extension Button","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/11","x":0,"y":407,"width":45,"height":45},">":[]}},{"UIATextView":{"@":{"name":"Message Input Text","label":"Message Input Text","value":"Enter message","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/12","x":44,"y":412,"width":285,"height":35},">":[]}},{"UIAButton":{"@":{"name":"Message Send Button","label":"Message Send Button","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/13","x":330,"y":407,"width":45,"height":45},">":[]}},{"UIAButton":{"@":{"name":"Message Extension New Avatar","label":"Message Extension New Avatar","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/14","x":55.5,"y":460,"width":75,"height":100},">":[]}},{"UIAButton":{"@":{"name":"Message Extension Avatar Gallery","label":"Message Extension Avatar Gallery","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/15","x":150.5,"y":460,"width":75,"height":100},">":[]}},{"UIAButton":{"@":{"name":"Message Extension Camera Roll","label":"Message Extension Camera Roll","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/16","x":245.5,"y":460,"width":75,"height":100},">":[]}},{"UIAButton":{"@":{"name":"Message Extension Camera","label":"Message Extension Camera","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/17","x":55.5,"y":568,"width":75,"height":100},">":[]}},{"UIAButton":{"@":{"name":"Message Extension Audio","label":"Message Extension Audio","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/18","x":150.5,"y":568,"width":75,"height":100},">":[]}},{"UIAToolbar":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/19","x":0,"y":667,"width":375,"height":44},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/19/0","x":0,"y":666.5,"width":375,"height":0.5},">":[]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/19/1","x":0,"y":667,"width":375,"height":44},">":[]}}]}},{"UIATabBar":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/20","x":0,"y":618,"width":375,"height":49},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/20/0","x":0,"y":609.5,"width":375,"height":57.5},">":[]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/20/1","x":0,"y":614,"width":375,"height":4},">":[]}},{"UIAButton":{"@":{"name":"bottom_record_button","label":"bottom_record_button","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/20/2","x":153.5,"y":610,"width":68,"height":57},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/20/2/0","x":153.5,"y":610,"width":68,"height":57},">":[]}}]}},{"UIAButton":{"@":{"name":"Messages","label":"Messages","value":1,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":nul

l,"path":"/0/0/20/3","x":2,"y":619,"
info: [debug] [INST] width":71,"height":48},">":[]}},{"UIAButton":{"@":{"name":"Contacts","label":"Contacts","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/20/4","x":77,"y":619,"width":71,"height":48},">":[]}},{"UIAButton":{"@":{"name":"Dummy","label":"Dummy","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/20/5","x":152,"y":619,"width":71,"height":48},">":[]}},{"UIAButton":{"@":{"name":"Avatars","label":"Avatars","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/20/6","x":227,"y":619,"width":71,"height":48},">":[]}},{"UIAButton":{"@":{"name":"Menu","label":"Menu","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/20/7","x":302,"y":619,"width":71,"height":48},">":[]}}]}},{"UIAStaticText":{"@":{"name":"Left Time Label","label":"Left Time Label","value":"Left Time Label","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/21","x":127.5,"y":402,"width":120,"height":30},">":[]}},{"UIAElement":{"@":{"name":"Level Meter","label":"Level Meter","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/22","x":315,"y":416,"width":40,"height":58},">":[]}},{"UIAStaticText":{"@":{"name":"Press and hold to record","label":"Press and hold to record","value":"Press and hold to record","dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/23","x":0,"y":502,"width":375,"height":13},">":[]}},{"UIAStaticText":{"@":{"name":"Release to send","label":"Release to send","value":"Release to send","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/24","x":0,"y":502,"width":375,"height":13},">":[]}},{"UIAButton":{"@":{"name":"btn msg option pointing down","label":"btn msg option pointing down","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/25","x":8,"y":498,"width":33,"height":37},">":[]}},{"UIAStaticText":{"@":{"name":"Time Label","label":"Time Label","value":"Time Label","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/26","x":0,"y":526,"width":375,"height":13},">":[]}},{"UIAStaticText":{"@":{"name":"Slide right to delete","label":"Slide right to delete","value":"Slide right to delete","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/27","x":79.5,"y":576,"width":210,"height":21},">":[]}},{"UIAImage":{"@":{"name":"ico-arrow-left-long","label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/28","x":79.5,"y":589,"width":210,"height":13},">":[]}},{"UIAStaticText":{"@":{"name":"Slide left","label":"Slide left","value":"Slide left","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/29","x":80.5,"y":582,"width":62,"height":11},">":[]}},{"UIAImage":{"@":{"name":"ico-arrow-left","label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/30","x":79.5,"y":592,"width":64,"height":8},">":[]}},{"UIAStaticText":{"@":{"name":"to preview","label":"to preview","value":"to preview","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/31","x":81.5,"y":596,"width":62,"height":11},">":[]}},{"UIAButton":{"@":{"name":"Recording Button","label":"Recording Button","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/32","x":147.5,"y":556,"width":80,"height":80},">":[]}},{"UIAStaticText":{"@":{"name":"Slide right","label":"Slide right","value":"Slide right","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/33","x":231.5,"y":582,"width":62,"height":11},">":[]}},{"UIAImage":{"@":{"name":"ico-arrow-right","label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/34","x":231.5,"y":592,"width":64,"height":8},">":[]}},{"UIAStaticText":{"@":{"name":"to delete","label

":"to delete","value":"to delete","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/35","x":231.5,"y":597,"width":62,"height":11},">":[]}},{"UIAImage":{"@":{"name":"Polygon","label":"Play Button","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/36","x":37.5,"y":578,"width":36,"height":36},">":[]}},{"UIAImage":{"@":{"name":"ico-trash","label":"Trash Button","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/37","x":301.5,"y":578,"width":30,"height":36},">":[]}}]}},{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/1","x":0,"y":0,"width":375,"height":667},">":[]}},{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/2","x":0,"y":0,"width":375,"height":667},">":[{"UIAStatusBar":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/2/0","x":0,"y":0,"width":375,"height":20},">":[{"UIAElement":{"@":{"name":"No SIM","label":"No SIM","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/2/0/0","x":6,"y":0,"width":42,"height":20},">":[]}},{"UIAElement":{"@":{"name":"3 of 3 Wi-Fi bars","label":"3 of 3 Wi-Fi bars","value":"NETGEAR47-5G-1","dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/2/0/1","x":53,"y":0,"width":13,"height":20},">":[]}},{"UIAElement":{"@":{"name":"3:57 pm","label":"3:57 pm","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/2/0/2","x":164,"y":0,"width":46,"height":20},">":[]}},{"UIAElement":{"@":{"name":"100% battery power, On AC Power","label":"100% battery power, On AC Power","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/2/0/3","x":303,"y":0,"width":67,"height":20},">":[]}}]}}]}}]}}}
info: [debug] [INST] 2015-04-10 10:27:35 +0000 Debug: Running system command #12: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"PocketAvatars","label":"PocketAvatars","value":...

info: [debug] Socket data received (8192 bytes)

info: [debug] Socket data received (6880 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"PocketAvatars","label":"PocketAvatars","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":20,"width":375,"height":647},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabl

info: [debug] Responding to client with success: {"status":0,"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n \n \n \n \n \n \n \n info: \n\n \n \n \n \n \n \n \n info: --> GET /wd/hub/session/e994ccf1-c136-4709-9e0e-088d77405e10/orientation {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: [debug] Sending command to instruments: au.getScreenOrientation()

info: [debug] [INST] 2015-04-10 10:27:36 +0000 Debug: Got new command 12 from instruments: au.getScreenOrientation()

info: [debug] [INST] 2015-04-10 10:27:36 +0000 Debug: evaluating au.getScreenOrientation()

info: [debug] [INST] 2015-04-10 10:27:36 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-04-10 10:27:36 +0000 Debug: responding with:
info: [debug] [INST] 2015-04-10 10:27:36 +0000 Debug: Running system command #13: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"PORTRAIT"}...

info: [debug] Socket data received (33 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":"PORTRAIT"}
info: [debug] Setting internal orientation to PORTRAIT
info: [debug] Responding to client with success: {"status":0,"value":"PORTRAIT","sessionId":"e994ccf1-c136-4709-9e0e-088d77405e10"}

info: <-- GET /wd/hub/session/e994ccf1-c136-4709-9e0e-088d77405e10/orientation 200 1073.882 ms - 82 {"status":0,"value":"PORTRAIT","sessionId":"e994ccf1-c136-4709-9e0e-088d77405e10"}
info: --> GET /wd/hub/session/e994ccf1-c136-4709-9e0e-088d77405e10/screenshot {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: [debug] Sending command to instruments: au.getScreenOrientation()

info: [debug] [INST] 2015-04-10 10:27:38 +0000 Debug: Got new command 13 from instruments: au.getScreenOrientation()

info: [debug] [INST] 2015-04-10 10:27:38 +0000 Debug: evaluating au.getScreenOrientation()

info: [debug] [INST] 2015-04-10 10:27:38 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-04-10 10:27:38 +0000 Debug: responding with:
info: [debug] [INST] 2015-04-10 10:27:38 +0000 Debug: Running system command #14: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"PORTRAIT"}...

info: [debug] Socket data received (33 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":"PORTRAIT"}
info: [debug] Setting internal orientation to PORTRAIT
info: [debug] Pushing command to appium work queue: "au.capture('screenshot22429377-8e4e-4971-b99f-13fbc060d5c5')"
info: [debug] Sending command to instruments: au.capture('screenshot22429377-8e4e-4971-b99f-13fbc060d5c5')

info: [debug] [INST] 2015-04-10 10:27:39 +0000 Debug: Got new command 14 from instruments: au.capture('screenshot22429377-8e4e-4971-b99f-13fbc060d5c5')

info: [debug] [INST] 2015-04-10 10:27:39 +0000 Debug: evaluating au.capture('screenshot22429377-8e4e-4971-b99f-13fbc060d5c5')

info: [debug] [INST] 2015-04-10 10:27:39 +0000 Debug: target.captureRectOnScreenWithName("{origin:{x:0.00,y:0.00}, size:{height:667.00,width:375.00}}", UIScreen, "screenshot22429377-8e4e-4971-b99f-13fbc060d5c5")

info: [debug] [INST] 2015-04-10 10:27:39 +0000 Screenshot captured.

info: [debug] [INST] 2015-04-10 10:27:39 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-04-10 10:27:39 +0000 Debug: responding with:

info: [debug] [INST] 2015-04-10 10:27:39 +0000 Debug: Running system command #15: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...

info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Waiting 10000 ms for screenshot to ge generated.

info: [debug] Responding to client with success: {"status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAAQABJREFUeAHsnQecJEd5t2vTbbq73ctJ0p2yTjlHlABlCSQyBtvkZGyDARuTwYAx2CQTbfNhMDkKJIEIyjnncIon3Z10eXO8Dd/79G7t9M51T+yZnd391++3OzPd1dXVT6d/vfXWW1V7v/lDo05JBERABERABERABERABESgoglUV3TtVDkREAEREAEREAEREAEREIGAgIS7LgQREAEREAEREAEREAERmAYEJNynwUlSFUVABERABERABERABERAwl3XgAiIgAiIgAiIgAiIgAhMAwIS7tPgJKmKIiACIiACIiACIiACIiDhrmtABERABERABERABERABKYBAQn3aXCSVEUREAEREAEREAEREAERkHDXNSACIiACIiACIiACIiAC04CAhPs0OEmqogiIgAiIgAiIgAiIgAhIuOsaEAEREAEREAEREAEREIEyEjjxwL0L2lttIVvV1tS4FQtbXJVtvL2z2/UODGYsZtG8ZtfcUO86evpcR29fxrxJrqyuqnLH7r/a7bN8iVuxoMW1dfe4jTva3Z2Pr3ftVpeoZJu4PRYvDI5tS3unG9g1NJFtwdwmN6+xIfjd1ddv5fVOrMv0ZfH8ua6pfk6Qpb2n13X29mfKntc6zsXJB+3jTrS/Q1evdHsvW+xamhrd3MZ61903EPBev2WHe/CZTe6WdU+5Wx55yu0aHs5rH8osAiIwmQD3NPf/8MjI5BX6JQIiIAKzlMD8pgZ38tp9XU//oLvhocfzovCSE45wbzn7FNMxq/LarpyZ0VH/88eb3G9vu6/o3R64xzL34iPXulvXPZ13WQUJ9z0XL3B//vR7HSL3T/c87N7x9R+60Qy7/thrL3QXHX+4++plV7sv/+aqDDmTW3XJSUe6d19wptt7+eLdCu3pH3Dfv/pW97XLr3V9g5MbHXNqa921n/0HO7Yq...","sessionId":"e994ccf1-c136-4709-9e0e-088d77405e10"}

info: <-- GET /wd/hub/session/e994ccf1-c136-4709-9e0e-088d77405e10/screenshot 200 2385.593 ms - 112706 {"status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAAQABJREFUeAHsnQecJEd5t2vTbbq73ctJ0p2yTjlHlABlCSQyBtvkZGyDARuTwYAx2CQTbfNhMDkKJIEIyjnncIon3Z10eXO8Dd/79G7t9M51T+yZnd391++3OzPd1dXVT6d/vfXWW1V7v/lDo05JBERABERABERABERABESgoglUV3TtVDkREAEREAEREAEREAEREIGAgIS7LgQREAEREAEREAEREAERmAYEJNynwUlSFUVABERABERABERABERAwl3XgAiIgAiIgAiIgAiIgAhMAwIS7tPgJKmKIiACIiACIiACIiACIiDhrmtABERABERABERABERABKYBAQn3aXCSVEUREAEREAEREAEREAERkHDXNSACIiACIiACIiACIiAC04CAhPs0OEmqogiIgAiIgAiIgAiIgAhIuOsaEAEREAEREAEREAEREIEyEjjxwL0L2lttIVvV1tS4FQtbXJVtvL2z2/UODGYsZtG8ZtfcUO86evpcR29fxrxJrqyuqnLH7r/a7bN8iVuxoMW1dfe4jTva3Z2Pr3ftVpeoZJu4PRYvDI5tS3unG9g1NJFtwdwmN6+xIfjd1ddv5fVOrMv0ZfH8ua6pfk6Qpb2n13X29mfKntc6zsXJB+3jTrS/Q1evdHsvW+xamhrd3MZ61903EPBev2WHe/CZTe6WdU+5Wx55yu0aHs5rH8osAiIwmQD3NPf/8MjI5BX6JQIiIAKzlMD8pgZ38tp9XU//oLvhocfzovCSE45wbzn7FNMxq/LarpyZ0VH/88eb3G9vu6/o3R64xzL34iPXulvXPZ13WQUJ9z0XL3B//vR7HSL3T/c87N7x9R+60Qy7/thrL3QXHX+4++plV7sv/+aqDDmTW3XJSUe6d19wptt7+eLdCu3pH3Dfv/pW97XLr3V9g5MbHXNqa921n/0HO7Yq...","sessionId":"e994ccf1-c136-4709-9e0e-088d77405e10"}

error: [REMOTE] Could not connect to WebKitRemoteDebugger server

info: --> GET /wd/hub/session/e994ccf1-c136-4709-9e0e-088d77405e10/contexts {}
info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","origValue":"connect ECONNREFUSED"},"sessionId":"e994ccf1-c136-4709-9e0e-088d77405e10"}
info: <-- GET /wd/hub/session/e994ccf1-c136-4709-9e0e-088d77405e10/contexts 500 4.623 ms - 293

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"e994ccf1-c136-4709-9e0e-088d77405e10"}

info: <-- GET /wd/hub/status 200 2.253 ms - 178 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"e994ccf1-c136-4709-9e0e-088d77405e10"}

**Comment by naveenjammula** [comment]
can you please provide the update on this ??

**Comment by sebv** [comment]
Error here:
``
info: [debug] Tried to execute non-existent mobile command 'swipe'. Most mobile commands have been ported to official client library methods. Please check your Appium library for more information and documentation`
``

You need to use the touch/multitouch api, see here: http://appium.io/slate/en/master/?python#touchaction

**Comment by sebv** [comment]
Closing, may be reopened if needed.
