### ISSUE TITLE
Pull File finds incorrect sim directory with XCode6.2

### ISSUE THREAD

**Issue by SquareTheBase** [appium/appium#4890]
It looks like Appium 1.3.7 will find the incorrect iOS sim directory when using an iPhone only?  I use the python-client to pull a file from the sim dir.  It raises a WebDriver exception when using an iPhone simulator, but not an iPad sim.  

Here is the directory it locates on iPhone:

```
WebDriverException: Message: u"An unknown server-side error occurred while processing the command. (Original error: ENOENT, open '/Users/<user>/Library/Developer/CoreSimulator/Devices/F7DF0BB3-ABEF-40E8-BDA6-D7FF087DDDD0/data/Containers/Bundle/Application/1525C417-AFBB-414E-9650-EED5A5417354/<app dir>\n/Users/<user>/Library/Developer/CoreSimulator/Devices/F7DF0BB3-ABEF-40E8-BDA6-D7FF087DDDD0/data/Containers/Bundle/Application/79705D9E-3989-4A8B-894B-9F8D1833B6F1/<app dir>/Info.plist')" 
```

**Comment by Jonahss** [comment]
Hm. it should be the same for both iPhone and iPad. What iOS SDK are the sims running on? (8.2, 7.1, etc)

**Comment by SquareTheBase** [comment]
Both are iOS8.2. Here is the code snippet that I'm using on both iPad and iPhone:

```
encoded_plist = self.driver.pull_file('<app dir>/Info.plist')
```

**Comment by SquareTheBase** [comment]
This is still an issue using iOS8.3 SDK with an app built from XCode6.3.1.

Is there any idea to what might be the cause?

Here is the same WebDriverException that is raised with Appium 1.3.7 and iOS8.3:
```
WebDriverException: Message: u"An unknown server-side error occurred while processing the command. (Original error: ENOENT, open '/Users/<user>/Library/Developer/CoreSimulator/Devices/47EB7371-DB7D-4D2C-B381-679B715B6138/data/Containers/Bundle/Application/15B6F67C-3F19-4173-8D83-9BF1F56B5DBC/<app dir>\n/Users/<user>/Library/Developer/CoreSimulator/Devices/47EB7371-DB7D-4D2C-B381-679B715B6138/data/Containers/Bundle/Application/4305FA0A-D436-4FEB-83C8-B3F7F8EC0C61/<app dir>/Info.plist')" 
```

**Comment by Jonahss** [comment]
Thanks for upgrading!
I'll try to reproduce this.

**Comment by Jonahss** [comment]
If you take a look at the test I ran here: https://github.com/Jonahss/appium-es7-example/blob/master/lib/test.es6.js

I used this command:
`driver.pullFile('/Containers/Bundle/Application/E60FFDE4-8C99-4DFB-98FD-81D3EBD8F558/TestApp-iphonesimulator.app/Info.plist')`
which worked.

Were you using the app-relative path, or full path like I did above?

It's possible that app-relative paths are broken.

**Comment by SquareTheBase** [comment]
Hmm - I'm using the app-relative path because the iOS sim paths move around depending on sim resets.   I'll give the full path a shot and report back.  

Thanks for looking into this!

**Comment by Jonahss** [comment]
I filed a bug for the app-relative paths: #5070

**Comment by Jonahss** [comment]
Looks like it's been assigned to appium 1.4.1, so that's soon ^.^

**Comment by SquareTheBase** [comment]
This fixed my issue - however, the path sent shouldn't be the absolute path (starting from the root dir) because the same path behavior is observed.  

Instead, send the simulator path as your example shows and the path will be accepted.

```
'Containers/Bundle/Application/F9077FE2-2E00-4460-A5F6-B4478628C0EC/<appdir>/<filename>'
```
