### ISSUE TITLE
Logcat capture failed: spawn ENOENT

### ISSUE THREAD

**Issue by hungl** [appium/appium#4891]
We are running our tests on an Android device and we are getting the error with the log that is below. There are no spaces in our path so that isn't the issue. 

Here is the Appium Log:

[36minfo[39m: Welcome to Appium v1.3.7 (REV 72fbfaa116d3d9f6a862600ee99cf02f6d0e2182)
[36minfo[39m: Appium REST http interface listener started on 127.0.0.1:4723
[36minfo[39m: [debug] Non-default server args: {"address":"127.0.0.1","nativeInstrumentsLib":true,"defaultCommandTimeout":7200}
[36minfo[39m: Console LogLevel: debug
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"automationName":"Appium","app":"/Users/administrator/Documents/jenkins/builds/android-core/app-ncr-auto-debug-unaligned.apk","deviceName":"Android Emulator","platformName":"Android","fullReset":true,"appActivity":"com.ncr.ao.core.ui.launch.LaunchActivity","appWaitActivity":".ui.login.LoginActivity,com.ncr.ao.core.ui.launch.LaunchActivity","appPackage":"com.ncr.ao.auto.beta"}}[39m
[36minfo[39m: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
[36minfo[39m: [debug] Using local app from desired caps: /Users/administrator/Documents/jenkins/builds/android-core/app-ncr-auto-debug-unaligned.apk
[36minfo[39m: [debug] Creating new appium session c148028c-4dbe-45ce-bdf5-eea4cd6e70f3
[36minfo[39m: Starting android appium
[36minfo[39m: [debug] Getting Java version
[36minfo[39m: Java version is: 1.7.0_75
[36minfo[39m: [debug] Checking whether adb is present
[33mwarn[39m: The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
[36minfo[39m: [debug] executing cmd: which adb
[36minfo[39m: [debug] Using adb from /Users/administrator/Library/Android/sdk/platform-tools/adb

[36minfo[39m: [debug] Using fast reset? false
[36minfo[39m: [debug] Preparing device for session
[36minfo[39m: [debug] Checking whether app is actually present
[36minfo[39m: Retrieving device
[36minfo[39m: [debug] Trying to find a connected android device
[36minfo[39m: [debug] Getting connected devices...
[36minfo[39m: [debug] executing cmd: "/Users/administrator/Library/Android/sdk/platform-tools/adb" devices
[36minfo[39m: [debug] 1 device(s) connected
[36minfo[39m: Found device e60778b9
[36minfo[39m: [debug] Setting device id to e60778b9
[36minfo[39m: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
[36minfo[39m: [debug] executing cmd: "/Users/administrator/Library/Android/sdk/platform-tools/adb" -s e60778b9 wait-for-device
[36minfo[39m: [debug] executing cmd: "/Users/administrator/Library/Android/sdk/platform-tools/adb" -s e60778b9 shell "echo 'ready'"
[36minfo[39m: [debug] Starting logcat capture
[31merror[39m: Logcat capture failed: spawn "/Users/administrator/Library/Android/sdk/platform-tools/adb" ENOENT
[36minfo[39m: [debug] Stopping logcat capture

**Comment by qazimusab** [comment]
Hung and I work together on this. We also wanted to ask what user does appium run as?

**Comment by imurchie** [comment]
Appium does not change the user, so whatever user is used to run the program, Appium runs as.

The easiest thing to do is to set your `ANDROID_HOME` environment variable to `/Users/administrator/Library/Android/sdk`.

**Comment by qazimusab** [comment]
it is set to that. in both the slave configuration and the actual machine

**Comment by imurchie** [comment]
Well, for whatever reason, Appium cannot find it.

```
�[33mwarn�[39m: The ANDROID_HOME environment variable is not set to the Android SDK root directory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking along PATH for adb.
```

What happens when you run `echo $ANDROID_HOME`?

**Comment by qazimusab** [comment]
it prints out /Users/administrator/Library/Android/sdk

**Comment by imurchie** [comment]
Can you try running the appium command preceded by `ANDROID_HOME=/Users/administrator/Library/Android/sdk`? This is very strange.

**Comment by jlipps** [comment]
yeah, is the variable exported? is appium using the same shell? (if you're using the GUI, it always uses bash even if you use a different terminal shell)

**Comment by qazimusab** [comment]
So basically we are building our UI tests project via jenkins and jenkins is running a shell script to start appium before the build starts. If i disable this and just start appium from the GUI and then run the project it works. But for some reason from the context of that shell script it doesn;t work. The environment variable is exported in the .bash_profile and even in the shell script. Neither conflict.

**Comment by qazimusab** [comment]
Never mind. Looks like there was a problem with my script. I fixed it. I removed 'export ANDROID_HOME=mypath' and 'export PATH=mypath' from my script and it worked

**Comment by qazimusab** [comment]
but the error message led me to think something else was the problem
