### ISSUE TITLE
'deviceName' required when 'udid' is already set

### ISSUE THREAD

**Issue by JamieEdge** [appium/appium#4895]
When starting the server and setting the `udid` flag, Appium fails to start a session because `deviceName` isn't set.

**Comment by jlipps** [comment]
i think we still require deviceName even in that case.

**Comment by jlipps** [comment]
(e.g., for an iphone, deviceName should be something like "iPhone 5s")

**Comment by edgy360** [comment]
I thought so too, but I just set it as ‘Jamie’ and it still started the device. When it communicates with Instruments, I don’t think that it looks at the deviceName and instead uses the UDID.

**Comment by jlipps** [comment]
that's true, we do ignore it, but we still require it to enforce good cap practices for when it eventually does matter.

**Comment by edgy360** [comment]
I can understand that, but is deviceName ever going to be required when sending a UDID? The UDID is just a more precise identifier surely?

For example, this would be like having to provide the bundle identifier along with an app path in my opinion.

**Comment by jlipps** [comment]
Maybe there would be two Android device providers that use different algorithms for generating device ids, and they could both be connected to the same machine. Then only the type of device would differentiate them. Or maybe two brands of emulators that both use the "emulator-*" namespace

**Comment by sebv** [comment]
I kind of agree it should not be needed.
