### ISSUE TITLE
1.3.7 android can't launch inspector

### ISSUE THREAD

**Issue by vascon8** [appium/appium#4896]
2015-04-12 12:54:05.273 Appium[3542:101630] *** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument
2015-04-12 12:54:05.274 Appium3542:101630] (
	0   CoreFoundation                      0x00007fff9039a66c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff9159d76e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff9039a51d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff8ba9ac39 -[NSRegularExpression(NSMatching) enumerateMatchesInString:options:range:usingBlock:] + 232
	4   Foundation                          0x00007fff8bb0c864 -[NSRegularExpression(NSMatching) firstMatchInString:options:range:] + 145
	5   Appium                               0x0000000100036d81 -[WebDriverElementNode initWithJSONDict:parent:showDisabled:showInvisible:] + 3553

in WebDriverElementNode.m, the bounds is nil,so crashed
			NSString *bounds = [_jsonDict objectForKey:@"bounds"];

            
			NSError *error;
			NSRegularExpression *regex = [NSRegularExpression regularExpressionWithPattern:@"\\[(\\d+),(\\d+)\\]\\[(\\d+),(\\d+)\\]" options:NSRegularExpressionCaseInsensitive error:&error];
			NSTextCheckingResult *firstResult = [regex firstMatchInString:bounds options:0 range:NSMakeRange(0, [bounds length])];

**Comment by jlipps** [comment]
inspector issues should be raised at the appium-dot-app repo
