### ISSUE TITLE
How can we say webdriver to  wait untill our copy process gets completed 

### ISSUE THREAD

**Issue by vinodakumarsr** [appium/appium#4897]
Hi i have a question pls help
how to write code in python for this below scenario
i want to copy 1000 files and i dont know how much time it takes, so i want to say webdriver to wait until my copy process gets completed.
 please help me

**Comment by imurchie** [comment]
Not sure I understand. Where is the copying going on? Just don't send commands and WebDriver will wait.

This question is better suited to the [Appium Discuss](https://discuss.appium.io/) forum.
