### ISSUE TITLE
Switching contexts using Java-client 2.2.0

### ISSUE THREAD

**Issue by praveenreddynarala** [appium/appium#4908]
Hi All,

Kindly help me out. I was struck up with switching contexts. I couldn't able to switch to WEBVIEW in Java. Getting following error while calling the statement driver.context("WEBVIEW"). 

Here I'm creating object for AppiumDriver as follows...

AppiumDriver driver = new AndroidDriver();
 
'error: Chromedriver create session did not work. Status was 200 and body was {"sessionId":"ca1f46ecff77de391bb861460ba2a7d6","status":13,"value":{"message":"unknown error: unable to discover open pages\n (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Windows NT 6.2 x86_64)"}}
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Did not get session redirect from Chromedriver)","origValue":"Did not get session redirect from Chromedriver"},"sessionId":null}
> info: <-- POST /wd/hub/session/7b194531-a5a9-422a-99d7-3237809d4529/context 500 62591.967 ms - 246' error while switching to WEBVIEW.

But my line of statement driver.getContextHandles() is returning all the available contexts.
 
Find my below code which I'm using for switching contexts.
Set<String> availableContexts = appiumdriver.getContextHandles();
   for(String context : availableContexts) {
       log.info("first context: "+ context);
       if(context.contains(contextType)) {
              appiumdriver.context(context);
             log.info("Successfully switched context to: "+ context);
        } 
}

I'm using latest java-client 2.2.0, Appium 1.3.4.2 and WebDriver 2.45. And my chromedriver is 2.15. My browser version is Chrome 41.0.2272.96.
I have tried with all the versions of chrome driver on top of above mentioned latest software. But no result. 

Guys, please help me, how to get out from here. It is very urgent. 

Thanks in Advance.

**Comment by sebv** [comment]
Try to upgrade Chromedriver. Easiest is to try to connect to your app using Chromedriver only (There is a built in webdriver) and make sure it works before you try from within Appium.

**Comment by praveenreddynarala** [comment]
Hi sebv, I tried it with latest chromedriver 2.15. But getting same error. Kindly let me know if you have any sample working to resolve.

**Comment by sebv** [comment]
Did you do this: `Make sure setWebContentsDebuggingEnabled is set to true `
http://appium.io/slate/en/master/?java#automating-hybrid-android-apps

**Comment by praveenreddynarala** [comment]
How and where we will do this. I don't have any idea on this. Actually I am using Linked .apk file for testing. Kindly let me know, you know any app that has been implemented above settings. 
I just want to give a try.

**Comment by sebv** [comment]
Please go here for support: https://discuss.appium.io/

**Comment by sebv** [comment]
Closing, this is the kind of issue better addressed in appium discuss.
