### ISSUE TITLE
`app_installed` endpoint is returning false for an installed app

### ISSUE THREAD

**Issue by redshirtrob** [appium/appium#4915]
I'm using the Python module to interact with the Appium web service.  I'm not 100% sure if this is a Python issue or an Appium issue, but my investigations indicate Appium.  I will try to reproduce with another library.

When I perform a simple `is_app_installed` on a real device request using the Python API, I get `false`.  I've tried explicitly setting `udid` (in device capabilities) to my device's UDID.  I've also used the `auto` value.  Neither works.

The issues seems to be the following line in `controller.js::isAppInstalled`.  This expression is false.
```
if ((req.appium.args.udid && req.appium.args.udid.length === 40) || (typeof stdout[0] !== "undefined")) {
```

Here's my Python code:

```
# This Python file uses the following encoding: utf-8

# iOS environment
import unittest
from appium import webdriver

desired_caps = {}
desired_caps['platformName'] = 'iOS'
desired_caps['deviceName'] = "...elided..."
#desired_caps['udid'] = '...elided...'
desired_caps['udid'] = 'auto'
desired_caps['bundleId'] = 'com.app.someapp'

driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

is_app_installed = driver.is_app_installed("com.app.someapp")

if is_app_installed:
    print "Installed!"
else:
    print "Not Installed..."
```

The only way I can get this to work is by passing the `-U <UDID>` arguments to Appium on launch.  It seems like I should be able to request a device via the Python client, but I cannot figure out how to do so.

If this is a bug, I'm happy to attempt a fix and PR, but I need some direction regarding the correct approach.  That is, in this case, should `typeof stdout[0] !== "undefined"` be the trigger condition?

**Comment by redshirtrob** [comment]
Hmmm, ok.  So, more investigation indicates that this is a problem down in `node-idevice`.  It's passing a boolean value as the second parameter in the callback (as can be seen below).  But the callback is expecting an array of file descriptors or something.  There's even a TODO message in the `controller.js` code to this effect.

So, I guess it seems like Appium is out of sync with node-idevice?  I've followed the setup instructions for running from source.

```
IDevice.prototype.isInstalled = function (appName, cb) {
    var self = this;

    self.listInstalled(function (err, apps) {
        if (err) {
            cb(err);
        } else {
            var i = 0,
                found = false;
            while (i < apps.length && !found) {
                if (apps[i]['name'].indexOf(appName) != -1 ||
                    apps[i]['fullname'].indexOf(appName) != -1) {
                    cb(null, true);
                    found = true;
                } else {
                    i++;
                }
            }
            if (!found)
                cb(null, false);
        }
    });
};
```

**Comment by imurchie** [comment]
Your PR looks good to me. If you have the latest ideviceinstaller you will also need to have the latest node-idevice installed or else it will always say the app is not installed.

**Comment by redshirtrob** [comment]
Yep, I'm synced between ideviceinstaller and node-idevice.  Thanks for the review.
