### ISSUE TITLE
Appium not working all the views (using ComponentKit)

### ISSUE THREAD

**Issue by 7ynk3r** [appium/appium#4917]
I'm using ComponentKit to render my collection view.

Using `po [[UIWindow keyWindow] recursiveDescription]` I can see the following hierarchy

      <UICollectionViewCell: 0x7fb9cad93170; frame = (0 28; 375 123.5); hidden = YES; layer = <CALayer: 0x7fb9ca8226a0>>
         | <UIView: 0x7fb9cad937a0; frame = (0 0; 375 123.5); gestureRecognizers = <NSArray: 0x7fb9cad93b10>; layer = <CALayer: 0x7fb9cad533b0>>
         |    | <UIView: 0x7fb9cad944e0; frame = (0 0; 375 123.5); layer = <CALayer: 0x7fb9cad945f0>>
         |    |    | <MMResponseScoreView: 0x7fb9cad95280; baseClass = UILabel; frame = (10 10; 40 40); text = '10'; clipsToBounds = YES; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x7fb9cad955c0>>
         |    |    | <UIView: 0x7fb9cafa0dd0; frame = (60 10; 305 26); clipsToBounds = YES; layer = <CALayer: 0x7fb9c856ede0>>
         |    |    |    | <CKTextComponentView: 0x7fb9cafa1a60; baseClass = UIControl; frame = (5 5; 251.5 16); userInteractionEnabled = NO; layer = <CKTextComponentLayer: 0x7fb9cafa1d20>>
         |    |    |    | <UIView: 0x7fb9cafa2910; frame = (261.5 0; 43.5 26); layer = <CALayer: 0x7fb9caf94cf0>>
         |    |    |    |    | <CKTextComponentView: 0x7fb9cafa2ff0; baseClass = UIControl; frame = (8 5; 27.5 16); userInteractionEnabled = NO; layer = <CKTextComponentLayer: 0x7fb9cafa3130>>
         |    |    | <CKTextComponentView: 0x7fb9cafa46e0; baseClass = UIControl; frame = (60 41; 270 21.5); userInteractionEnabled = NO; layer = <CKTextComponentLayer: 0x7fb9cafa4820>>
         |    |    | <CKTextComponentView: 0x7fb9cafa5980; baseClass = UIControl; frame = (330 44.5; 35 14.5); userInteractionEnabled = NO; layer = <CKTextComponentLayer: 0x7fb9cafa5760>>
         |    |    | <CKTextComponentView: 0x7fb9cafa6dd0; baseClass = UIControl; frame = (60 62.5; 290 32); userInteractionEnabled = NO; layer = <CKTextComponentLayer: 0x7fb9cafa6f10>>
         |    |    | <UIImageView: 0x7fb9cafa8320; frame = (60 99.5; 14 14); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x7fb9caf60010>>
         |    |    | <CKTextComponentView: 0x7fb9cafa8cc0; baseClass = UIControl; frame = (76 99.5; 274 14); userInteractionEnabled = NO; layer = <CKTextComponentLayer: 0x7fb9cafa8810>>

But when I see the same view in Appium with `Copy XML` I just see a custom view inside the cell:

    <UIACollectionCell name="{&quot;type&quot;:&quot;MMResponse&quot;,&quot;name&quot;:&quot;Griffin, Stewie&quot;,&quot;hasDraft&quot;:false,&quot;hasRead&quot;:false,&quot;index&quot;:&quot;0&quot;}" label="" value="0" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/12/0" x="0" y="92" width="320" height="60.5">
        <UIAStaticText name="10" label="10" value="10" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/12/0/0" x="10" y="102" width="40" height="40">
        </UIAStaticText>
    </UIACollectionCell>

What is the logic behind appium to define what is "present" or not?

Thanks,
JM

**Comment by Jonahss** [comment]
Oh dear. Sorry but if the view isn't appearing in the XML hierarchy that appium sees, it's doubtful that we can interact with it.
Your can still use TouchActions to tap screen coordinates....
@bootstraponline do you agree?

**Comment by bootstraponline** [comment]
> @bootstraponline do you agree?

yep

**Comment by bootstraponline** [comment]
If you use the [Apple accessibility inspector](https://developer.apple.com/library/ios/technotes/TestingAccessibilityOfiOSApps/TestAccessibilityiniOSSimulatorwithAccessibilityInspector/TestAccessibilityiniOSSimulatorwithAccessibilityInspector.html) and make the custom view accessible, then appium will be able to automate it. Apple has extensive documentation about accessibility on iOS.
