### ISSUE TITLE
Add argument to save output log to a log file for ios-webkit-debug-proxy-launcher.js

### ISSUE THREAD

**Issue by LimeDang** [appium/appium#4920]
When using java to redirect output of ProcessBuilder to a file (logFile), and when ios-webkit-debug-proxy get error and ios-webkit-debug-proxy-launcher.js launches a new one, .... the logFile could not get the new logs from ios-webkit-debug-proxy-launcher.js any more, because it launches a new process.
So I suggest to add argument to save output log to a log file for ios-webkit-debug-proxy-launcher.js

Now I get errors and hang out from Appium, and I think it may come from ios-webkit-debug-proxy, but I can not get logs from it to see what happening.

**Comment by mykola-mokhnach** [comment]
closing as obsolete, since the next Appium version won't use IWDP anymore
