### ISSUE TITLE
Swipe functionality is not working correctly

### ISSUE THREAD

**Issue by Ankit9568** [appium/appium#4922]
Hello Members,

I am unable to swipe with latest appium server 1.3.7.2

Code

driver = new AndroidDriver()
HashMap<String, Object> swipeObject = new HashMap<String, Object>();
		swipeObject.put("startX", 600);
		swipeObject.put("startY", 1212);
		swipeObject.put("endX", 600);
		swipeObject.put("endY", 912);
		swipeObject.put("duration", 5);
JavascriptExecutor javaScriptDriver = ((JavascriptExecutor) driver);
javaScriptDriver .executeScript("mobile: swipe", swipeObject);

Above code is working fine on Appium server version 1.2.4 but same code not working on appium server 1.3.7.2 shows following  exception 

Tried to execute non-existent mobile command 'swipe'. Most mobile commands have been ported to official client library methods. Please check your Appium library for more information and documentation
info: [debug] Responding to client that a method is not implemented

so we using inbuilt swipe from Appium-javaClient library
driver.swipe(600,1212,600,912,5);

Above code is not swiping,it clicks on given coordinates 

Resources Using:
Appium Server :1.3.7.2 & 1.2.4
Java Client library - 2.2.0

Any help will be appreciated

**Comment by ajit4848** [comment]
Check this out.....Its working fine for me.
    

             System.out.println("Swiping Now...");
	    JavascriptExecutor js = (JavascriptExecutor)webDrvrM1 ;
	    HashMap<String, Double> swipeObject = new HashMap<String, Double>();
	    swipeObject.put("startX", 382.0);
	    swipeObject.put("startY", 150.0);
	    swipeObject.put("endX", 382.0);
	    swipeObject.put("endY", 950.0);
	    swipeObject.put("duration", 1.8);
	    js.executeScript("mobile: swipe", swipeObject);
	    System.out.println("Swipped....!");

**Comment by Ankit9568** [comment]
Hi ajit4848,

Thanks for reply,

I mention same code in my post but code is working fine on Appium server version 1.2.4 but my concern is  that code is not not working on appium server 1.3.7.2 shows following exception

Tried to execute non-existent mobile command 'swipe'. Most mobile commands have been ported to official client library methods. Please check your Appium library for more information and documentation
info: [debug] Responding to client that a method is not implemented

I have already tried driver.swipe(),it click on given coordinates  
Is there any workaround for this problem?

Any help will be greatly appreciated

**Comment by Ankit9568** [comment]
Hello Members,

Finally ,I have found  an solution to swipe with Appium 1.3.7.2 , when I am using in-build Swipe and pass an argument "duration" above from 0 it click on given coordinates
But i wonder when I passes argument  "duration" 0 it swipe Successfully, Its work as blocker whose user who trying to swiping in slower motion also request to kindly treat as bug
