### ISSUE TITLE
AndroidDriver Webview App shows blank page

### ISSUE THREAD

**Issue by ynotdraw** [appium/appium#4923]
I've been using Sauce Labs to run tests against their Android Nexus device.  My test uses the AndroidDriver Webview App to launch a webpage and my automated test runs.  In my automated test, most of the pages are displayed and the test works; however, when it redirects to a URL after clicking a button, the screen just displays blank.  This happens for many tests which redirect to this URL.  I'm not sure what you need to troubleshoot, so please let me know and I'll add any info you may need.  Please note that this only happens with the Android tests - all other test environments work flawlessly and do not have this issue on a redirect. Thanks!

![tcsuccessfulorganizationactivationautomaticloginnavigationtotheusersdirectoryprofilepageandatouroffer](https://cloud.githubusercontent.com/assets/8069555/7160909/05ad877e-e35a-11e4-95e7-26ea0d358c43.png)
![tcsuccessfullyjoinyourteamautomaticloginnavigationtotheusersdirectoryprofilepageandchatpage](https://cloud.githubusercontent.com/assets/8069555/7160912/0816c458-e35a-11e4-9dd1-073b5bf2b589.png)

**Comment by jlipps** [comment]
The AndroidDriver app is not associated with the Appium project, and (AFAIK) is not supported anymore anyway. I'd recommend getting in touch with Sauce Labs support about this. I do know that Sauce supports web testing via Appium on newer versions of Android, so that could be an option for you.
