### ISSUE TITLE
Not able to launch chrome browser in real android device Error : > info: [debug] [CHROMEDRIVER STDERR] [0.020][SEVERE]: Could not bind socket to 127.0.0.1:9515 > info: [debug] [CHROMEDRIVER] Port not available. Exiting...

### ISSUE THREAD

**Issue by amitjaincoer191** [appium/appium#4924]
I am not able to launch chrome browser in real android device
Cap's I am passing are 

DesiredCapabilities cap = new DesiredCapabilities(); 
cap.setCapability(MobileCapabilityType.BROWSER_NAME,MobileBrowserType.CHROME);
 cap.setCapability(MobileCapabilityType.PLATFORM_VERSION,"4.4.4"); 
cap.setCapability(MobileCapabilityType.PLATFORM_NAME,"Android");
cap.setCapability(MobileCapabilityType.DEVICE_NAME,"ZX1B32HNBD");
cap.setCapability(MobileCapabilityType.APP_PACKAGE,"com.android.chrome");

**Comment by amitjaincoer191** [comment]
Appium logs 


> info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"4.4.4","platformName":"Android","deviceName":"ZX1B32HNBD","browserName":"Chrome","appPackage":"com.android.chrome"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.6 (java 1.5)
> info: Set mode: Proxying straight through to Chromedriver
> info: [debug] Looks like we want chrome on android
> info: [debug] Creating new appium session 18d09bfd-9b40-42c0-9d63-68db2632001b
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device ZX1B32HNBD
> info: [debug] Setting device id to ZX1B32HNBD
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 45)
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD wait-for-device
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD install "C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD push "C:\\Users\\amit.ja\\Desktop\\android\\AppiumForWindows-1.3.4.1\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD shell "ps 'uiautomator'"
> info: [debug] Attempting to kill process 6044
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD shell "kill 6044"
> info: [debug] UiAutomator exited
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD shell "echo 'ping'"
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap
> info: [debug] Attempting to uninstall app
> error: UiAutomator quit before it successfully launched
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Cleaning up android objects
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] json loading complete.
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Creating Chrome session
> info: [debug] Set chromedriver binary as: C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] Ensuring Chromedriver exists
> info: [debug] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %b))
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
> info: [debug] No old chromedrivers seemed to exist
> info: [debug] Spawning chromedriver with: C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] [CHROMEDRIVER] Starting ChromeDriver (v2.10.267521) on port 9515
> Only local connections are allowed.
> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"ZX1B32HNBD"}}}}
> info: [debug] [CHROMEDRIVER STDERR] [0.020][SEVERE]: Could not bind socket to 127.0.0.1:9515
> info: [debug] [CHROMEDRIVER] Port not available. Exiting...
> error: Chromedriver create session did not work. Status was 200 and body was {"sessionId":"252cb4152c4f627fe0efb7376641bd8e","status":13,"value":{"message":"unknown error: Device ZX1B32HNBD is already in use\n  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.1 SP1 x86)"}}
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: Did not get session redirect from Chromedriver
> info: [debug] Error: Did not get session redirect from Chromedriver
>     at null.<anonymous> (C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\lib\devices\android\chromedriver.js:222:12)
>     at Request._callback (C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\lib\devices\common.js:121:5)
>     at Request.self.callback (C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\request\request.js:121:22)
>     at Request.EventEmitter.emit (events.js:98:17)
>     at Request.<anonymous> (C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\request\request.js:985:14)
>     at Request.EventEmitter.emit (events.js:117:20)
>     at IncomingMessage.<anonymous> (C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\node_modules\request\request.js:936:12)
>     at IncomingMessage.EventEmitter.emit (events.js:117:20)
>     at _stream_readable.js:920:16
>     at process._tickDomainCallback (node.js:459:13)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Did not get session redirect from Chromedriver)","origValue":"Did not get session redirect from Chromedriver"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 3572.301 ms - 214 
> info: [debug] Chromedriver exited with code 1
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD devices
> info: [debug] 1 device(s) connected
> info: [debug] executing cmd: C:\amjain\adt-bundle-windows-x86-20130522\sdk\platform-tools\adb.exe -s ZX1B32HNBD shell "am force-stop com.android.chrome"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Cleaning up appium session

**Comment by amitjaincoer191** [comment]
Appium version 1.3.4.1
jave client 2.2
chrome driver version in real device chrine 41.0.2272.96

**Comment by amitjaincoer191** [comment]
Solutions tried
1. updated chrome driver in real device
2. verified cap's passed are correct
3. change port in appium android setting to 9725, also tried with port 4725 it is not working

"Jonahss" please help me in this ...........   :**(

**Comment by amitjaincoer191** [comment]
C:\>C:\Users\amit.ja\Desktop\android\AppiumForWindows-1.3.4.1\Appium\node_modules\appium\build\chromedriver\windows
\chromedriver.exe
Starting ChromeDriver (v2.10.267521) on port 9515
Only local connections are allowed.
[0.010][SEVERE]: Could not bind socket to 127.0.0.1:9515
Port not available. Exiting...

How can I update this chromedriver kindly suggest

**Comment by jlipps** [comment]
Sounds like you have an issue running chromedriver on your system, independently of Appium. I'd recommend getting in touch with the chromedriver project to troubleshoot why it's not working. Do you have permission to bind to port 9515? Maybe you need to be in administrator mode.

**Comment by Jonahss** [comment]
Closed due to inactivity. Comment here is still experiencing difficulty.
