### ISSUE TITLE
Android cannot get text from webview

### ISSUE THREAD

**Issue by nabeel-ibrahim** [appium/appium#4925]
I have a hybrid app that has a news article which is inside a webview. I do successfully change the driver context to webview and I am able to inspect the elements from my chrome browser through chrome://inspect. I can get elements by className, id, tagName but I cant get elements by Name. when I do a driver.findElementByName(name); it throws a noSuchElementException. If i find the element by any other locator, I get the element but when i do a .getText() on it, it returns an empty string.Below is my log. I am using appium 1.3.7

[36minfo[39m: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/543d9bb8ddfd2039072da3ec61f53947/element","method":"POST","json":{"using":"name","value":"Darren Staples / Reuters"}}
[36minfo[39m: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":"no such element\n  (Session info: webview=)\n  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Mac OS X 10.10.3 x86_64)"},"sessionId":"4e8b00b3-5293-4249-98a6-60d7b5b50f0a"}
[36minfo[39m: [37m<-- POST /wd/hub/session/4e8b00b3-5293-4249-98a6-60d7b5b50f0a/element [39m[31m500[39m[90m 82.328 ms - 341[39m [90m[39m
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 90 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-27 00:00:10'
System info: host: 'nibrahim-macbook-2.local', ip: 'xxx.xxx.xx.xx', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.8.0_20'
Driver info: io.appium.java_client.android.AndroidDriver
Session ID: 4e8b00b3-5293-4249-98a6-60d7b5b50f0a

**Comment by jlipps** [comment]
The response is coming directly from Chromedriver, so I'm not sure if there's anything Appium can do about this. Have you tried printing the page source immediately before the find command? It might highlight whether the page state is as you expect. If the element's text is being dynamically populated by javascript, for example, there could be a race condition in the test code.

**Comment by nabeel-ibrahim** [comment]
I am able to view all the elements including the text in the page source. The text is not generated dynamically, there might not be any race conditions.

**Comment by nabeel-ibrahim** [comment]
I was able to get the text by executing javascript using the innerHTML method.

**Comment by nabeel-ibrahim** [comment]
I'll close this issue
