### ISSUE TITLE
Android Unlock.apk crashing simulator, Api-Level 21

### ISSUE THREAD

**Issue by KimMatt** [appium/appium#4930]
I launch with prelaunch app as an argument. 
If I manually unlock the screen and launch again it works fine.

info: [debug] Screen is locked, trying to unlock
info: [debug] Getting device API level

info: [debug] executing cmd: /Users/mkim/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"

info: [debug] Device is at API Level 21

info: [debug] executing cmd: /Users/mkim/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"

info: [debug] [BOOTSTRAP] [debug] Emitting system alert message

info: [debug] Emitting alert message...

error: uncaughtException: Cannot read property 'sockets' of null date=Wed Apr 15 2015 21:01:24 GMT-0400 (EDT), pid=3149, uid=677516420, gid=90124439, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.12.1, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --command-timeout, 7200, --session-override, --pre-launch, --automation-name, Appium, --platform-name, Android, --platform-version, 5.1, --app, /Users/mkim/Documents/AUT/app/build/outputs/apk/app-debug-unaligned.apk, --avd, Nexus_5_API_21_x86], rss=54452224, heapTotal=71041792, heapUsed=39780320, loadavg=[2.1630859375, 1.91845703125, 1.81689453125], uptime=15972, trace=[column=25, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=, line=193, method=null, native=false, column=9, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js, function=Function._.each._.forEach, line=145, method=_.each._.forEach, native=false, column=5, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=UiAutomator.handleBootstrapOutput, line=183, method=handleBootstrapOutput, native=false, column=8, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js, function=UiAutomator.outputStreamHandler, line=172, method=outputStreamHandler, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=16, file=_stream_readable.js, function=readableAddChunk, line=163, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=126, method=Readable.push, native=false, column=20, file=net.js, function=Pipe.onread, line=529, method=onread, native=false], stack=[TypeError: Cannot read property 'sockets' of null,     at null.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:193:25),     at Function._.each._.forEach (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js:145:9),     at UiAutomator.handleBootstrapOutput (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:183:5),     at UiAutomator.outputStreamHandler (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/uiautomator.js:172:8),     at Socket.emit (events.js:107:17),     at readableAddChunk (_stream_readable.js:163:16),     at Socket.Readable.push (_stream_readable.js:126:10),     at Pipe.onread (net.js:529:20)]

**Comment by moizjv** [comment]
@KimMatt are you still facing this issue?

**Comment by Jonahss** [comment]
+1, we're seeing lots of android emulator issues with api level 21 and 22.

**Comment by Jonahss** [comment]
related to #5080

**Comment by KimMatt** [comment]
@moizjv Yes the issue is still present.

**Comment by sebv** [comment]
So it's a bug.

**Comment by SrinivasanTarget** [comment]
Fixed in latest and works fine in API 21.Closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close
