### ISSUE TITLE
Appium should not be translated in French, or must be fixed

### ISSUE THREAD

**Issue by pbernery** [appium/appium#4935]
Hello,

I just noticed that the http://appium.io web site has been translated in French. While the intention is good, the translation is poor (I believe it has been made with an automatic translation tool) and makes people feel that Appium is a poor/bad product. The sentences "Introduisant Appium." and "Manquez-vous l'automatisation..." make no sense in French.

The Web site should either not be translated or be translated by humans.

**Comment by jlipps** [comment]
I agree with you there. I'm not sure who introduced the french translation, but it's likely we didn't realize it was a machine translation.
