### ISSUE TITLE
Android emulator screen shot is blank and inspector not showing anything as well

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#4936]
Hi,

I am using android emulator  with below details

Target: Android 4.3.1 (API level 18)
Skin: 720x1280
SD Card: 100M

Use HOST GPU is checked.

Appium server latest version 1.3.7

screenshot method captures blank but works fine with real device

same case with Inspector , it is not showing any thing as well

Please look into this issue and fix

Thanks & Regards,
Vikram

**Comment by jlipps** [comment]
This is a known issue with that API level. Unfortunately UiAutomator broke screenshots :-(

**Comment by bootstraponline** [comment]
the [upstream issue is fixed](https://code.google.com/p/android/issues/detail?id=60359) as of API 22.
