### ISSUE TITLE
Hardcoded Android SDK Level API during './reset.sh --android --verbose'

### ISSUE THREAD

**Issue by agileseph** [appium/appium#4937]
Steps:
0) preconditions: you don't have installed Android SDK Level API 19 (you have installed another version)
1) checkout appium from git
2) try './reset.sh --android --verbose'

Expected: 
1) Appropriate error message

Actual:
1) please, see console log below

Extra Info:
1) Console Log: 
"... 
RESETTING ANDROID
Configuring Android bootstrap
Running "configAndroidBootstrap" task
Error: Target id is not valid. Use 'android list targets' to get the target ids.
Warning: Setup cmd /Users/username/Desktop/android-sdk-macosx/tools/android failed with code 1 Use --force to continue.
Aborted due to warnings."

Post-effects:
1) If you try './reset.sh --chromedriver-install-all' or other and then start 'node .' for example for Mobile Web autotests with ChromeDriver, then you will get the not obvious error like: "Device chrome not configured yet (Selenium::WebDriver::Error::WebDriverError)". It seems ChromeDriver is not downloaded because of previous errors with not compiled Android-related staff. But the final log doesn't contain any warning message about it if try './reset.sh --chromedriver-install-all' with not installed 19 Level API.

**Comment by moizjv** [comment]
@agileseph I am not sure if i follow you. Did you run `node bin/appium-doctor.js --dev` to see if all pre-conditions were followed? Here is the running from source [documentation](https://github.com/appium/appium/blob/master/docs/en/contributing-to-appium/appium-from-source.md)

**Comment by pbc** [comment]
The `node bin/appium-doctor.js --dev` should be plastered all over the docs with huge letters :)

thx @moizjv

**Comment by sebv** [comment]
We need to fix the error message. (We gonna get rid of reset.sh anyway.)

**Comment by acolby** [comment]
This is still an issue, the hardcoded version 19 is not downloaded by theAndroid SDK by default

**Comment by vvvvaib** [comment]
Yep, faced same issue with 1.4.13

**Comment by vikramvi** [comment]
Problem still exists with 1.4.16

**Comment by SrinivasanTarget** [comment]
@agileseph Closing this as we get rid of reset.sh in our current architecture.

**Comment by SrinivasanTarget** [comment]
@triager please close
