### ISSUE TITLE
How to use x-platform concept correctly in case of Mobile Web and Native Android operations automation?

### ISSUE THREAD

**Issue by agileseph** [appium/appium#4938]
For example:
1) I need automate some actions on MobileWeb platform using ChromeDriver. Some basic actions on the web page in Chrome browser. 
2) Then I need take picture via Android camera (or do some staff using Android OS or native Android app actions) and upload it into web-site. 
3) Then continue work on web page with ChromeDriver.

Questions:
1) What is the best practice with Appium to do it?
2) By the way, for what purposes Appium run UIAutomator during ChromeDriver start? It can be disabled? And how to use UIAutomator if ChromeDriver running? How to use them together without pain?

**Comment by Jonahss** [comment]
So you can use the Context commands to switch automation from applying to the webview, or applying to the native app (in this case the browser).
https://discuss.appium.io/t/what-does-the-autowebview-desired-capability-really-do/69

I *think* you should be able to access the camera via sending commands to press buttons on the screen. http://stackoverflow.com/questions/25015540/is-there-are-any-way-to-access-the-camera-functionality-through-appium

So I would do this:
1) start a browser test (automatically puts you in the WEBVIEW context)
2) switch to NATIVE_APP context
3) hit HOME button, open camera, automate that stuff
4) reopen app via more button pressing
5) switch to WEBVIEW context

Hope that helps :)
