### ISSUE TITLE
Unable to perform tap() on android device

### ISSUE THREAD

**Issue by robert-langenfeld** [appium/appium#4939]
Hello,

I'm trying to perform a tap on an android application. The application's login screen is a entirely a webview (context is WEBVIEW_0). Part of our requirements is that we must be able to perform click actions at any set of coordinates we desire. I'm using the following code:

driver.tap(1, x, y, 1);

However when I run that code on the device I get an unsupported command exception thrown and then the following terminal message:

info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/49a89083-6253-746f-d75d-6c301e5fe289/touch/perform","method":"POST","json":{"actions":[{"action":"press","options":{"y":180,"x":96}},{"action":"wait","options":{"ms":1}},{"action":"release","options":{}}]}}
info: [debug] Proxied response received with status 404: undefined
info: <-- POST /wd/hub/session/49a89083-6253-746f-d75d-6c301e5fe289/touch/perform 404 25.998 ms - - 
info: --> GET /wd/hub/status {}

I have tried this in both the native context and webview context. Is there something I am missing here? I got this exact same code to work just fine on IOS.

**Comment by robert-langenfeld** [comment]
@jlipps Do you have any thoughts on this? We are using selendroid in this scenario. Is there any way to perform an action like tap, swipe, or drag using selendroid and the X,Y coordinate? We've also tried using XPath to locate the element whose X,Y, matches are criteria, but that is painfully slow (since Selenium and Appium both run in serial). That method can take upwards of 5-6 minutes to perform depending on the application/web-page.  It's kind of road-blocking our development.

**Comment by jlipps** [comment]
@robert-langenfeld I don't think Selendroid supports that gesture API. You probably need to look at the Selendroid docs for how to do what you want to do within their framework.

**Comment by Jonahss** [comment]
Closed due to inactivity. Comment here and we can reopen the issue.

**Comment by imsardine** [comment]
@robert-langenfeld You may try ADB shell command `input` as a temporary workaround. For example, `adb shell input swipe x1 y1 x2 y2`. It seems like that it's usage is different from device to device.

@jlipps Per Selendroid's [document](http://selendroid.io/gestures.html), it does support touch gestures. I am curious about why Selendroid mode didn't integrate the support. If the integration doesn't work for some reason, how about using the `input` shell command mentioned above as a (temporary) workaround?

**Comment by jlipps** [comment]
@imsardine it's not a question of appium's selendroid implementation. it's a question of what endpoints your driver client is hitting. it looks like you're trying to use gesture commands which are not implemented in selendroid. presumably the endpoints selendroid implements are accessed through a different set of commands. did you try using the code samples provided by selendroid? what happens then?
