### ISSUE TITLE
Inspector doesn`t work for iOS simulator. 

### ISSUE THREAD

**Issue by Bohdan1304** [appium/appium#4946]
Hi,

Im using appium 1.3.6 (cause 1.3.7 cant operate with xCode 6.1 yet).  And Im trying to launch inspector, but I got  error:
*error: Failed to start an Appium session, err was: Error: ENOENT, no such file or directory '/Applications/Appium.app/Contents/Resources/node_modules/appium/com.myapp.app/Info.plist'*
I've found same issue in discussions for 1.3.1, It had been solved (as I remember) but now it appears again.
Could you please advice?

Thanks!

**Comment by Bohdan1304** [comment]
additional info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
*info: [debug] Dynamic bootstrap path: /Users/user/Library/Application Support/appium/bootstrap/bootstrap-516354d056bc7b25.js
info: [debug] Reusing dynamic bootstrap: /Users/userLibrary/Application Support/appium/bootstrap/bootstrap-516354d056bc7b25.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPad Air","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Air (8.1 Simulator)'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPad Air","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPad Air (8.1 Simulator)'
info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.muapp.app/Info.plist
info: Will try to parse the plist file as XML*

**Comment by moizjv** [comment]
@Bohdan1304 looks like https://github.com/appium/appium-dot-app issue, can you raise it there. Thanks
