### ISSUE TITLE
Note that appium runs with bash, not with zsh

### ISSUE THREAD

**Issue by mttrs** [appium/appium#4947]
The appium doesn't work if the PATHs such as ANDROID_HOME are set in **zsh**. It'd be great if you add the notation to use **bash** in the doc.
  http://appium.io/slate/en/master/?java#android-setup

**Comment by sebv** [comment]
Oups sorry this gave you some trouble, shells setup may involve some trickery at times.

The doc doesn't specifically mention `bash` except in gotchas. Really people should be able to set their shell the way they want, there are already plenty of post online explaining how to set bash/zsh...

**Comment by moizjv** [comment]
Yes @sebv is right mostly setting environment variables depending on the shell should solve most of the issues.

**Comment by mttrs** [comment]
Let me add more details. The problem is when I run the GUI. CLI works well. The GUI terminal looks work with bash. So, is there any way to change a shell setting for GUI?

- Launch from GUI
```bash
info: [debug] Error: Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.
    at null.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-adb/lib/adb.js:126:12)
    at ChildProcess.exithandler (child_process.js:751:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.)","origValue":"Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path."},"sessionId":null}

error: Failed to start an Appium session, err was: Error: Could not find adb. Please set the ANDROID_HOME environment variable with the Android SDK root directory path.

info: <-- POST /wd/hub/session 500 128.993 ms - 342 
```

Appium doctor says OK even there is no PATH setting in .bash_profile.

```bash
% '/Applications/Appium.app/Contents/Resources/node/bin/node' '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
Running iOS Checks
✔ Xcode is installed at /Applications/Xcode.app/Contents/Developer
✔ Xcode Command Line Tools are installed.
✔ DevToolsSecurity is enabled.
✔ The Authorization DB is set up properly.
✔ Node binary found using which command at /Users/mitsuteru.sawa/.nvm/v0.10.22/bin/node
✔ iOS Checks were successful.

Running Android Checks
✔ ANDROID_HOME is set to "/Users/mttrs/Library/Android/sdk"
✔ JAVA_HOME is set to "/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home."
✔ ADB exists at /Users/mttrs/Library/Android/sdk/platform-tools/adb
✔ Android exists at /Users/mttrs/Library/Android/sdk/tools/android
✔ Emulator exists at /Usersmttrs/Library/Android/sdk/tools/emulator
✔ Android Checks were successful.

✔ All Checks were successful
```

```bash
# My shell setting

% cat /etc/shells
# List of acceptable shells for chpass(1).
# Ftpd will not allow users to connect who are not using
# one of these shells.

/usr/local/bin/zsh
/bin/bash
/bin/csh
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh
```

```bash
# .bash_profile
# Comment out!

# # Android
# export ANDROID_HOME="$HOME/Library/Android/sdk"
#
# # JAVA
# export JAVA_HOME="`/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java_home`"
#
# export PATH="$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"
#
```

```bash
# .zshenv

# Android
export ANDROID_HOME="$HOME/Library/Android/sdk"

# JAVA
export JAVA_HOME="`/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java_home`"

export PATH="$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"
```

**Comment by sebv** [comment]
Just move the config to a separate file (e.g. .appium-env) and source it from both.

The appium doctor in the gui should probably be run within bash, this looks like a bug (cc @penguinho).

**Comment by mttrs** [comment]
Just move the config to a separate file (e.g. .appium-env) and source it from both.
>>> Yeah, it's a solution. It'd be great if you provide a shell configuration for GUI. Because I'd like to source it in only zsh. It could avoid any confusion happened when user has to consider bash and the other shells.

**Comment by sebv** [comment]
This needs to be adressed directly in this repo: https://github.com/appium/appium-dot-app, please open an issue and link to this.

That should not be a problem for apps to require bash to be configured, but the real issue here is that the doctor should fails within the gui. Btw there is a field in the gui to manually set ANDROID_HOME
https://www.dropbox.com/s/vmadrd7cl5mamfn/Screenshot%202015-04-23%2017.39.06.png?dl=0

**Comment by mttrs** [comment]
Thanks for letting me know the correct repository. I issued a ticket. https://github.com/appium/appium-dot-app/issues/484
