### ISSUE TITLE
reset command does not reset app data in iOS when noReset is set to true

### ISSUE THREAD

**Issue by Sanjo** [appium/appium#4956]
The reset command does not reset app data in iOS when noReset is set to true.
In Android the app data is reset. So it is an inconsistent behavior. I've tested this with the iOS Emulator (iPhone 6, 8.2) and Android 4.4.4 on a real device.

**Use case why this is relevant:**

I want to set noReset to `true`
so that I can restart the app with `closeApp -> launchApp` without losing the app data
and use `resetApp` to manually reset the app data before each test scenario.

Having a restartApp command (https://github.com/appium/appium/issues/4955) would be an alternative for my specific use case.

**Comment by kirillzh** [comment]
On iOS you cannot just reset app data. Reinstall app only. If you want to restart app, you need to set capabilities noReset to true and fullReset to false. Then you can restart app by simply creating new driver. To reset app you can uninstall it using ideviceinstaller and create driver again.

**Comment by IntelloScooby** [comment]
I was also facing the same issue. 
In iOS, when we have noReset=true, resetApp() does not reset the app but instead has the same behavior as closeApp(). In Android, with same setting, resetApp() resets the app and closeApp() just closes it. 
Below is a workaround that I followed, I created a custom method which would set the value of noReset setting and open a new driver. Another method, to reset the value of noReset and open new driver. Then I am calling these methods as and when required. 

Below is the sample code:
`public void setNoResetSetToTrue() throws Throwable {
        if (platformName.equals("iOS")){
            capabilities.setCapability("noReset",true);
            driver = new IOSDriver(appiumURL, capabilities);
        }
    }

    public void setNoResetToFalse() throws Throwable {
        if (platformName.equals("iOS")){
            capabilities.setCapability("noReset",false);
            driver = new IOSDriver(appiumURL, capabilities);
        }
    }`

**Comment by 03623170** [comment]
Our iOS app is supposed to ask the user at the first time of usage, if the gps is either allowed or not. Therefor we wanted to completely uninstall the app to test our use cases with gps on and gps off, but somehow it seems that the settings of the app are still saved on the iPhone. When we do autoDismissAlerts in our first test our second test (with fullReset setting) seems to have saved the setting before.

**Comment by mathias21** [comment]
Why is Android Label set in this issue? xD

It is also happening to me in Appium 1.6.4-beta2 with WebdriverAgent 2.5.3, MacOS Sierra 10.12.4 and iOS 9.3.1. 

In order to solve this, if your device is iOS device, you can do a driver.removeApp(bundleId). For android, driver.resetApp() is still working for me.
