### ISSUE TITLE
 [appium 1.3.7]Could not get the iOS SDK version because the Xcode version could not be determined.

### ISSUE THREAD

**Issue by wensj** [appium/appium#4961]
When I use appium 1.3.4 everything is ok,but when I use appium 1.3.7,I get this error:

error: Could not get the iOS SDK version because the Xcode version could not be determined.
error: Could not get the iOS SDK version because the Xcode version could not be determined.

info: [debug] Cleaning up appium session
info: [debug] Error: Could not get the iOS SDK version because the Xcode version could not be determined.
    at /Applications/Appium.app/Contents/Resourcesde_modules/appiumb/devices/ios/xcode.js:111:10
    at /Applications/Appium.app/Contents/Resourcesde_modules/appiumb/devices/ios/xcode.js:80:14
    at /Applications/Appium.app/Contents/Resourcesde_modules/appiumb/devices/ios/xcode.js:57:9
    at ChildProcess.exithandler (child_process.js:735:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not get the iOS SDK version because the Xcode version could not be determined.)","origValue":"Could not get the iOS SDK version because the Xcode version could not be determined."},"sessionId":null}
info: <-- POST /wd/hubssion 500 56.865 ms - 290 

error: Could not get the iOS SDK version because the Xcode version could not be determined.
error: Could not determine iOS SDK version
error: Failed to start an Appium session, err was: E

**Comment by wensj** [comment]
Please let me know is this a bug of appium 1.3.7?What should I do ?

**Comment by laxmiskava** [comment]
I am also getting the same issue when I use, appium 1.3.7.

**Comment by wensj** [comment]
Is this a bug of appium 1.3.7,anybody could confirm this ?

**Comment by wensj** [comment]
I have see this is a bug of appium,In another issue.

**Comment by Jonahss** [comment]
which issue?
