### ISSUE TITLE
Unable to launch the App [The app must be signed with a development identity (e.g. iOS Developer).]

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium#4962]
I wrote code to install App from the URL and launch. It is installed but happening launch and close multiple times. App is generated using Jenkins with distribution account and I have my own developer account with all the required profiles. 

code:
public class NewTest {
	WebDriver driver =null;
       @Test
        public void f() throws MalformedURLException, InterruptedException {
	        DesiredCapabilities capabilities = new DesiredCapabilities();
	        capabilities.setCapability("deviceName", "iPadAir");
		capabilities.setCapability("browserName","");
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("platformVersion", "8.2");
		capabilities.setCapability("app", "http://*********/ShureMobile.ipa");
		capabilities.setCapability("udid", "7c7a3d3626200bb38205013f479adf90fdf585f5");
		driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
}
}
Below is the appium log:

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}
info: <-- GET /wd/hub/status 200 0.938 ms - 104 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"}}}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"8.2","app":"http://sezdsk24772:8080/job/ios-Shure-ChannelsApp-CI/lastSuccessfulBuild/artifact/build/Release-iphoneos/ShureMobile.ipa","deviceName":"iPadAir","platformName":"iOS","browserName":"","udid":"7c7a3d3626200bb38205013f479adf90fdf585f5"}}

info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
info: [debug] Using downloadable app from desired caps: [object Object]

info: [debug] http://sezdsk24772:8080/job/ios-Shure-ChannelsApp-CI/lastSuccessfulBuild/artifact/build/Release-iphoneos/ShureMobile.ipa downloaded to /var/folders/76/g5b824fn1q94jwbryzhmxyhc0000gq/T/115320-3176-1uvdmes/appium-app.zip

info: [debug] Unzipping /var/folders/76/g5b824fn1q94jwbryzhmxyhc0000gq/T/115320-3176-1uvdmes/appium-app.zip
info: [debug] Testing zip archive: /var/folders/76/g5b824fn1q94jwbryzhmxyhc0000gq/T/115320-3176-1uvdmes/appium-app.zip

info: [debug] Zip archive tested clean

info: [debug] Unzip successful

info: [debug] Using extracted app: /var/folders/76/g5b824fn1q94jwbryzhmxyhc0000gq/T/115320-3176-1uvdmes/Payload/ShureMobile.app
info: [debug] Creating new appium session e873cad8-3bc5-4897-a6d7-8f5046d6a4bd
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder

info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.2
info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/shiva/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/shiva/Library/Application Support/appium/bootstrap/bootstrap-d5a0fb924946d8d3.js
info: [debug] Reusing dynamic bootstrap: /Users/shiva/Library/Application Support/appium/bootstrap/bootstrap-d5a0fb924946d8d3.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.2","iOSSDKVersion":"8.2","deviceName":"iPadAir","platformVersion":"8.2"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPadAir (8.2 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] On a real device; cannot clean device state
info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole

info: [debug] Not pre-launching simulator

info: [debug] Creating iDevice object with udid 7c7a3d3626200bb38205013f479adf90fdf585f5
info: [debug] Checking app install status using: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id 7c7a3d3626200bb38205013f479adf90fdf585f5 --bundle com.shure.channels

info: [debug] App is installed.
info: [debug] fullReset not requested. No need to install.
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 7c7a3d3626200bb38205013f479adf90fdf585f5
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 7c7a3d3626200bb38205013f479adf90fdf585f5 com.shure.channels -e UIASCRIPT "/Users/shiva/Library/Application Support/appium/bootstrap/bootstrap-d5a0fb924946d8d3.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2015-04-20 16:50:32.481 instruments[3204:103680] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: Permission to debug com.shure.channels was denied. The app must be signed with a development identity (e.g. iOS Developer).

info: [debug] [INSTSERVER] Instruments exited with code 253
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"e873cad8-3bc5-4897-a6d7-8f5046d6a4bd"}
info: <-- GET /wd/hub/status 200 1.536 ms - 178 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"e873cad8-3bc5-4897-a6d7-8f5046d6a4bd"}

info: Launching instruments

info: [debug] Attempting to run app on real device with UDID 7c7a3d3626200bb38205013f479adf90fdf585f5
info: [debug] Spawning instruments with command: /Applicatio

**Comment by shivakrishnach31** [comment]
@sebv / @jlipps , Could you please look into this. I am stuck with this issue.

**Comment by shivakrishnach31** [comment]
Working fine when App installed through Xcode. But I need solution for the App installed from the Jenkins build URL. Pls help me.

**Comment by sebv** [comment]
You can sign the archive from command line.

See here: http://stackoverflow.com/questions/2664885/xcode-build-and-archive-from-command-line

**Comment by sebv** [comment]
or here https://github.com/edgy360/appium-release-automation/blob/master/release-app.sh

**Comment by shivakrishnach31** [comment]
@sebv , for doing this I should have a downloaded .app or .ipa. Here this is not the case. My build manager will generate a build every week in Jenkins and I have to automatically install the build into my device using Appium script and execute the test cases. So, the procedure you sent me is not a good idea to do every week.

is .ipa with distribution account will work with appium or do I need .app with developer account?

**Comment by sebv** [comment]
Yeah my understanding is that you cannot do it without dev build.

**Comment by sebv** [comment]
This is a Instruments issue by the way, If you can automate your build with instrument, you should be able to do it with Appium.

**Comment by shivakrishnach31** [comment]
@sebv , When I try to automate using instrument, it is not accepting .ipa build. So, I think to automate app using instrument we need .app build. am I correct?
So, you are saying that, we can't automate build which in release mode? To overcome this we need dev/debug build? is it?

**Comment by sebv** [comment]
It must be explained somewhere in the xCode/iOS doc.

**Comment by jlipps** [comment]
I'm not sure you need a debug build for a real device, but it definitely needs the right provisioning profile. Maybe it also needs to be a debug build for instruments to automate it. @Jonahss can you confirm?

**Comment by sebv** [comment]
Appium doc seem to imply that you just need a "correctly-signed .ipa"
```
Native app support: Yes, with debug version of .app (simulator), or correctly-signed .ipa (real devices). Underlying support is provided by Apple’s UIAutomation framework.
```

**Comment by Jonahss** [comment]
I was able to run Instruments with a Release build of the TestApp, signed by me of course.
So debug build might not be necessary.

**Comment by Jonahss** [comment]
Still need to check a full app-store archived ipa file.

**Comment by Jonahss** [comment]
@shivakrishnach31 you should talk to the team that manages the Jenkins build for your app, try to get them a copy which is signed by their Developer profile. Sorry that there's not more we can do, this is a limitation placed by Apple.

**Comment by shivakrishnach31** [comment]
@Jonahss , They generates AppStore version build from jenkins with distribution profile, not with developer profile. So, I am not able to install the App which is build with distribution profile. But able to play with the App which is build with developer profile. I have to automate distribution profiled App. Any help still?

**Comment by Jonahss** [comment]
Nope, Instruments can only automate an app which has been built with a Developer Profile. This is a restriction put in place by Apple and we haven't found a way around it.

The code generated should be the same, so testing your Developer build with appium is the same as testing the actual Distribution-built app.

**Comment by shivakrishnach31** [comment]
Thanks @jonah

**Comment by Jonahss** [comment]
Welcome :)

**Comment by rakesh0404** [comment]
HI, 

Our .ipa is signed with developer identity with debug mode but still receiving below error 

All it does it open our app 3 times and instruments gets crashed 

info: [debug] [INST STDERR] 2015-11-26 15:16:27.254 instruments[26212:879059] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [debug] [INST STDERR] 2015-11-26 15:16:27.856 instruments[26212:879064] Attempting to change event horizon while disengage

info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: Permission to debug com.xxxxxxx.app was denied. The app must be signed with a development identity (e.g. iOS Developer).
info: [debug] [INST STDERR] 2015-11-26 15:16:27.856 instruments[26212:878991] Attempting to change event horizon while disengage

**Comment by subodhbrahmi** [comment]
Facing the same issue as above, any joy?

**Comment by imurchie** [comment]
There are multiple issues above. To what are you referring?
