### ISSUE TITLE
Broken link on appium page/github

### ISSUE THREAD

**Issue by TeamworkAnthony** [appium/appium#4965]
http://appium.io/slate/en/tutorial/ios.html?ruby#page-object-pattern when i click on the ruby-ios it tells me a 404, i think i need this for the rake file

**Comment by moizjv** [comment]
@TeamworkAnthony thanks for raising issue. We will fix it.

**Comment by moizjv** [comment]
Raised [issue](https://github.com/appium/appium.io/issues/71) in appium.io repo
