### ISSUE TITLE
Proxy settings doesn't work on Appium

### ISSUE THREAD

**Issue by sriramsantosh** [appium/appium#4968]
We have Mobile Execution Platform grid similar to Saucelabs grid where we can remotely get connected to devices via Appium. I have sample piece of code that runs fine on my local box. However if I run it a separated VM, I need a proxy to enable the outbound traffic. I enabled proxy in the desired capabilities and still not able to connect to a remote device.

			String PROXY = "myproxy.com";
			org.openqa.selenium.Proxy proxy = new org.openqa.selenium.Proxy();
			proxy.setHttpProxy(PROXY)
		       .setFtpProxy(PROXY)
		       .setSslProxy(PROXY);
			proxy.setProxyType(ProxyType.MANUAL);
			capability.setCapability(CapabilityType.PROXY, proxy);

Any idea what the issue might be ?

**Comment by jlipps** [comment]
Appium doesn't support proxies; it ignores those capabilities

**Comment by manasatr** [comment]
can we add this support ??

**Comment by jlipps** [comment]
no, this is outside the scope of appium's responsibilities right now. you can always set up your own proxy wherever appium is running.

**Comment by vm31** [comment]
Hi, Are there any ways within Appium version to integrate with HttpProxy service?

**Comment by go2null** [comment]
> @jlipps: you can always set up your own proxy wherever appium is running.

Any pointers on how to do this?

**Comment by ronnelpinto** [comment]
@jlipps, any pointers or workarounds to try and get, say BrowserMob proxy working with Appium would be very helpful.

**Comment by jlipps** [comment]
Sorry I don't have any pointers or workarounds. Appium doesn't do anything specifically to help or disable proxies, so I'm not sure how we could help.

**Comment by timrsfo** [comment]
@ronnelpinto I suggest google-ing "node js proxy settings" and/or "node js corporate proxy". from this I found [npm-config](https://docs.npmjs.com/misc/config) see "proxy"  You can also try `npm config ls -l | grep -i proxy` to see what your current proxy setting is (probably null the default). You can set a proxy via `npm config set proxy http://proxy.company.com:8080` - note I have not tried this yet
