### ISSUE TITLE
ios-webkit-debug-proxy gets disconnected randomly

### ISSUE THREAD

**Issue by mehulc** [appium/appium#4969]
I'm using appium 1.3.7 with a real device (iPad Retina) and running the selenium tests against it.
I have been using the ios-webkit-debug-proxy-launcher.js with my device to be able to interact with webviews and switch contexts occasionally and every thing works fine for a while (30 minutes or so)
But every now and then, the idwp gets disconnected with the following error message:
ss.remove_fd(6)
Disconnected :27753 from iPad (...the udid)
ss.remove_server_fd(4)
child process exited with code 0

after which unless I restart iwdp, I can no longer access my webviews. Could you please suggest why does the iwdp gets disconnected and what can I do to keep it connected to the device  ??

**Comment by sebv** [comment]
There is a script here:
https://github.com/appium/appium/blob/master/bin/ios-webkit-debug-proxy-launcher.js

**Comment by mehulc** [comment]
@sebv - Please correct me if I am wrong. This is the same script that I got when I cloned appium and I am using this very script and facing the issue.

**Comment by sebv** [comment]
Yes it is the same, sorry thought you were using iwdp directly. In this case it looks like the connection was closed from the browser, need to check what happen in this case. 

I think the next step would be to write unit tests for this script simulating this condition.

**Comment by brianmrock** [comment]
Anyone get a chance to dig into this, I am facing the same issue on mobile web tests.

**Comment by md29** [comment]
I am having the same issue, anybody have solution for this?

**Comment by SrinivasanTarget** [comment]
Start ```iwdp``` using ```pm2``` process monitoring.This issue is because iwdp hangs or disconnects from ports abruptly at times.If it is started via pm2 or any process monitoring tools it automatically restarts at same port during the disconnect.It's not an issue with appium server. Give a try and get back to us. pm2 is available here: https://github.com/Unitech/pm2

**Comment by SrinivasanTarget** [comment]
@triager please close
