### ISSUE TITLE
SpringBoard check on launch is problematic

### ISSUE THREAD

**Issue by amake** [appium/appium#4971]
A recent PR (#4855) introduced a check on iOS app launch to see if the app actually launched or if we're still on SpringBoard. Unfortunately this check fails in a way that makes Appium unusable for my app, and probably others as well.

The issue is that my app requests permission to send notifications and access photos immediately on first launch. This means that a successful initial launch on a clean install will result in SpringBoard-supplied dialogs which are reported by Instruments like this:

https://gist.github.com/amake/5c5617f1ab16bfa14730

The check for SpringBoard thus thinks that we have not successfully launched, and the session ends with `Error("App did not have elements")`.

At the very least, this SpringBoard check needs to be optional. More pessimistically, I think it may not be possible to conclusively determine if the launch was successful just by looking at the UI hierarchy.

**Comment by amake** [comment]
Followup: Specifying the `autoAcceptAlerts` capability does allow the SpringBoard check to work as expected, but there are legitimate use cases where this capability cannot be used.

**Comment by moizjv** [comment]
@amake we can look into this. Adding capability looks reasonable to me. I will add this to bugs list.

**Comment by jlipps** [comment]
@amake that is why we have the `waitForAppScript` capability, so people can define their own logic for determining that the app has loaded

**Comment by jlipps** [comment]
would that work for your case?

**Comment by amake** [comment]
@jlipps Sorry, I had overlooked that capability since the default behavior worked for us for so long. Yes, that's actually a great solution. Problem solved.
