### ISSUE TITLE
Appium inspector doesn't highlight element for app running on emulator + API 22

### ISSUE THREAD

**Issue by ghost** [appium/appium#4977]
Hi,
I've setup Nexus 7 emulator with API level 22.
This is showing in inspector but it's not highlighting elements as it does on actual device.

can you please have a look in to this issue

Thanks,
Vikram

**Comment by sebv** [comment]
Reproed, also found an issue with the api 22 setting:

https://github.com/appium/appium-dot-app/issues/482

@penguinho you think it's a client or server issue?

**Comment by SrinivasanTarget** [comment]
please raise here if you hit the same in latest version.https://github.com/appium/appium-dot-app/issues

**Comment by SrinivasanTarget** [comment]
@triager please close
