### ISSUE TITLE
Don't truncate instruments log when it crashes

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#4978]
When instruments crashes we don't capture the full log output? We should see if we can fix that.

**Comment by jlipps** [comment]
@Jonahss was this fixed in the instruments rewrite?

**Comment by imurchie** [comment]
I'm not sure this is fixable. We spawn an process and all of our logs are retrieved from that process. When Instruments crashes the process exits, so we no longer get the stdio from it. So no more logs.

**Comment by jlipps** [comment]
I thought this had to do with keeping the output from before it crashed? @Jonahss what did you mean here?

**Comment by Jonahss** [comment]
Yeah, we used to not get the last dozen log lines when it crashed. The logs
would be sent to stdout, but the appium logger would get killed as soon as
instruments crashed and we wouldn't output the last chunk to the appium
logs.

This is PROBABLY gone now because of SubProcess. But we should reproduce a
crashing instruments and make sure.

**Comment by imurchie** [comment]
Is there a way to reliably cause Instruments to crash and still be logging?

**Comment by Jonahss** [comment]
We don't need to "still be logging", we just want to make sure that the
last line of the instruments log makes it to the appium log.

We could probably crash instruments by killing the simulator mid-test?

**Comment by imurchie** [comment]
Yes, sorry, I was more meaning still be creating log output that we want to show. The only way I could get Instruments to crash was at startup, from the wrong arguments, and the log output happened before the process closed.

I'll give killing a sim a shot!

**Comment by imurchie** [comment]
Killing it mid-test didn't work. I'm going to try using an app built for a real device, and see what happens.

**Comment by Jonahss** [comment]
You can try throwing an error in bootstrap.js. That will cause instruments to quit with a scriptDidThrowError exception

**Comment by imurchie** [comment]
Hmm. Ok. I'll give that a shot.

**Comment by imurchie** [comment]
I am fairly certain this is solved, but it warrants a bit more experimentation. Moving to `appium-instruments` (https://github.com/appium/appium-instruments/issues/55).
