### ISSUE TITLE
Verify and fix send_text on android

### ISSUE THREAD

**Issue by rubixthegreat** [appium/appium#4981]
Appium Version: 1.3.5
Android Version: 4.4.2

I'm using automation to click on an element via X,Y coordinates. In this scenario I do not have the id of the object I want to type text in, just the X, Y coordinates that are inside of it. After performing the tap action on it, I attempt to send text like this:

Actions builder = new Actions(driver);
builder.sendKeys('test').perform();

The above code works fine on iOS but it doesn't work on Android. Here is the log statement I received:
info: --> POST /wd/hub/session/e01ceded-ca24-4d22-adc3-59daf2ccdc0f/keys {"value":["test"]}
info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"test"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"test"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: setText
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Unknown error","status":13}
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"}},"sessionId":"e01ceded-ca24-4d22-adc3-59daf2ccdc0f"}

The weird thing is that I'm not sending over an element id with this action but it's attempting to set the text on the element id. Why is this?

I did some research into how to get this to work and I ran accross this issue:
https://github.com/appium/appium/issues/856

I don't think that will work for me but is there something similar to that? Or is there a way for me to send text to the element that is currently in focus? Any inputs would be helpful!

**Comment by imurchie** [comment]
Yes, the `keys` function is broken. Not sure if it is broken in iOS or Android.

`lib/server/controller.js` takes the `value` received and passes it along. In iOS this is fine. In Android the method expects an element and a text value, and so we get the above error.

Controller: https://github.com/appium/appium/blob/master/lib/server/controller.js#L762
Android: https://github.com/appium/appium/blob/master/lib/devices/android/android-controller.js#L205
iOS: https://github.com/appium/appium/blob/master/lib/devices/ios/ios-controller.js#L1019

**Comment by robert-langenfeld** [comment]
Glad to know I wasn't going crazy. Is there a work-around that I can do for this in the meantime?

**Comment by GindiKhangura** [comment]
@imurchie My progress is also being blocked by this issue. Is there a work-around available?
If not, can the fix for this bug please be included in the next release?

**Comment by imurchie** [comment]
The Android side is wrong: `keys` [ought](https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/keys) to send the text to the currently focused element. We only support sending text to a particular element.

We need to figure out some logic to get the currently focused element (a cursory glance didn't yield anything promising out-of-the-box) and then reuse the [setText](https://github.com/appium/appium/blob/master/lib/devices/android/bootstrap/src/io/appium/android/bootstrap/handler/SetText.java) logic.

**Comment by moizjv** [comment]
https://github.com/appium/appium/issues/5042

**Comment by moizjv** [comment]
#4844 tracking similar issue

**Comment by robert-langenfeld** [comment]
Out of curiosity, is this going to be fixed in the near future or is this going to be for a much farther down milestone?

**Comment by imurchie** [comment]
This is in the works. I'm just fixing some issues with it on Selendroid.

**Comment by robert-langenfeld** [comment]
Thanks for getting this taken care of! Has a release date been given yet for 1.4? We can find a workaround until then. But if it's coming out in the next week or so then we won't bother with finding the work around. Or better yet, if this is in master, can we build this ourselves and run it?

**Comment by imurchie** [comment]
It is in master. If you run from source and reset with the latest code it ought to work!
