### ISSUE TITLE
Bootstrap.js on iOS should handle EOF from commandProxy

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#4983]
When appium ends a session, it closes the commandProxy to Instruments, sending an EOF. This causes the test script to throw an error.
It ends all the same, but this is messy.

Do this along with #4982 since they're closely related.

**Comment by sebv** [comment]
We should try to replace the error callback chain by a promise reject, and/or make use of promise.any, that'll simplify the code a lot.

**Comment by Jonahss** [comment]
Then we'd have to include a whole promise library in the bootatrap.js payload to the phone.

**Comment by sebv** [comment]
Didn't realise you were talking about uiauto, the javascript there is synchronous, so no need to use promise. Should open an issue in appium-uiauto and link to it.

**Comment by sebv** [comment]
Looks like we need to add a try/catch here: https://github.com/appium/appium-uiauto/blob/master/uiauto/lib/commands.js#L210
