### ISSUE TITLE
Inspector does not work for Android emulator.

### ISSUE THREAD

**Issue by rushmila** [appium/appium#4985]
Hi,

I am using Appium - Version 1.3.7 (Ophiuchus) on a Mac (Version - 10.10.2). I am using android emulator. When I launch the inspector, it starts perfectly but I couldn't able to perform the element inspection using the inspector. I am adding the screenshot of my Appium settings.

Can anyone suggest anything?

![android_settings_appium](https://cloud.githubusercontent.com/assets/2417354/7267962/a08e2c6a-e906-11e4-8b71-8bc9ee0c12ad.png)

**Comment by igalep** [comment]
Some problem for me as well

**Comment by sebv** [comment]
Please post an issue here: https://github.com/appium/appium-dot-app

**Comment by sebv** [comment]
Closing, not an appium server issue (see post above), you may also get support here: https://discuss.appium.io/
