### ISSUE TITLE
Press and Release (Long press) did not work in Appium 1.4.0 release while the same working fine for 1.3.7

### ISSUE THREAD

**Issue by priyankshah217** [appium/appium#5004]
Hi All,

I am trying to automate long press gesture using appium. I ran my script on same device with same java client version 2.2.0 but with different appium version (1.3.7 and 1.4.0). The issue which i had observed that, automation became unresponsive while simulating long press gesture in 1.4.0. It did not perform any action at all. But the same script worked fine when I executed it on appium 1.3.7.

I tried to find out some but did not get much clarity. You can refer line no 745 onwards in below to log file.

Appium 1.3.7:
https://gist.github.com/priyankshah217/bd371b60648024640ae5#file-android_press_release_1-3-7-log

Appium 1.4.0:
https://gist.github.com/priyankshah217/bd371b60648024640ae5#file-android_press_release_1-4-0-log

Just let me know, if you required much information.

Thanks,
Priyank Shah

**Comment by amedvedjev** [comment]
+ 1. same issue met. BUT the problem starting from TAP already.

tested with real Android phone (API 19).

driver.tap(1, element, 200) - cause just PressDown action
element.click() - working correctly.

**Comment by moizjv** [comment]
@priyankshah217 thanks for reporting issue. can you give sample code for which it is breaking

**Comment by priyankshah217** [comment]
@moizjv , Below is the sample code which were breaking.

private By captureButtonLocator = MobileBy
			.AndroidUIAutomator("new UiSelector().resourceId(\"com.test.app.android:id/btnCapture\")");

TouchAction action = new TouchAction(driver);
action.press(driver.findElement(captureButtonLocator)).waitAction(5000)			.release().perform();

**Comment by moizjv** [comment]
@priyankshah217 can you test from master i have fixed the issue. Thanks for reporting :)

**Comment by priyankshah217** [comment]
Its resolved now, checked in 81b90b599f8f1e0a5c7c39e7fb93f0314be0b328. 

Thanks,
Moiz

**Comment by Nitinvermaa1** [comment]
I am trying to perform drag and drop, but i am getting error. Below are the details.
Appium version: 1.4.0
Java_Client: 3.1.0 Jar
Source code: WebElement drag = driver.findElement(By.name("Gmail"));
		System.out.println(drag.isDisplayed());
		WebElement drop = driver.findElementByXPath("//android.widget.TextView[@text='']");
		Point location = drag.getLocation();
		Point location1=drop.getLocation();
		int x=location.getX();
		int y=location.getY();
		
		int x1=location1.getX();
		int y1=location1.getX()	;	
		Thread.sleep(2000);
		TouchAction action = new TouchAction(driver);
		action.longPress(drag, x, y).moveTo(drop,x1,y1).release().perform();

my testcase get passed but above code doesn't perform drag and drop. I also applied waitAction() but no success.

action.longPress(action.longPress(driver.findElement(By.name("Gmail"))).waitAction(5000);
action.moveTo(drop,x1,y1).release();
action.perform();).waitAction(5000);

Please help me out.
		action.moveTo(drop,x1,y1).release();
		action.perform();

**Comment by ShwetaHonna** [comment]
TouchAction action = new TouchAction(androidDriver);
    action.press(0, 500)
            .waitAction(200)
            .moveTo(0, 200)
            .release()
            .perform();
