### ISSUE TITLE
Appium - Getting error: Could not set the device type in Info.plist

### ISSUE THREAD

**Issue by karunakaranvrv** [appium/appium#5005]
@jlipps @moizjv 
When I launch Appium inspector with ios package details, I am unable to launch ios app using appium and getting the below error as follows:-

Used tools version are listed below:-

    Appium version:- 1.3.7
    Xcode version:- 6.1.1
    Mac os: 10.10.2

Error log:-

    Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --pre-launch --log "/tmp/appium.log" --platform-version "8.1" --platform-name "iOS" --app "com.vervewireless.iphone.qa.beta" --show-ios-log --device-name "iPhone 6"
    
    info: [debug] Starting Appium in pre-launch mode
    
    info: Pre-launching app
    
    info: [debug] App is an iOS bundle, will attempt to run as pre-existing
    
    info: [debug] Creating new appium session 62b3e6af-2864-4256-9559-97b5a17fcb44
    
    info: [debug] Removing any remaining instruments sockets
    
    info: [debug] Cleaned up instruments socket /tmp/instruments_sock
    info: [debug] Setting Xcode folder
    
    info: [debug] Setting Xcode version
    
    info: [debug] Setting iOS SDK Version
    
    info: [debug] Getting sdk version from xcrun with a timeout
    
    info: [debug] iOS SDK Version set to 8.1
    
    info: [debug] Checking whether instruments supports our device string
    
    info: [debug] Getting list of devices instruments supports
    
    info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
    
    info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}
    
    info: [debug] fixDevice is on
    info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
    
    info: [debug] iOS sim UDID is 4391D23F-BA21-4FB8-8887-0972D2911420
    info: [debug] Detecting automation tracetemplate
    
    info: [debug] Not auto-detecting udid, running on sim
    
    info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vervewireless.iphone.qa.beta/en.lproj/Localizable.strings
    info: Will try to parse the plist file as XML
    info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vervewireless.iphone.qa.beta/en.lproj/Localizable.strings
    warn: Could not parse app Localizable.strings assuming it doesn't exist
    info: [debug] Creating instruments
    info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
    info: [debug] Preparing uiauto bootstrap
    info: [debug] Dynamic bootstrap dir: /Users/alkaffkhan/Library/Application Support/appium/bootstrap
    
    info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
    info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
    ...
    info: [debug] Dynamic bootstrap path: /Users/alkaffkhan/Library/Application Support/appium/bootstrap/bootstrap-931e8d7703a594e3.js
    
    error: Could not set the device type in Info.plist
    
    info: [debug] Reusing dynamic bootstrap: /Users/alkaffkhan/Library/Application Support/appium/bootstrap/bootstrap-931e8d7703a594e3.js
    info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}
    info: [debug] fixDevice is on
    info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
    info: [debug] We're on iOS7.1+ so forcing defaultDevice on
    info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}
    info: [debug] fixDevice is on
    info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
    info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vervewireless.iphone.qa.beta/Info.plist
    info: Will try to parse the plist file as XML
    info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vervewireless.iphone.qa.beta/Info.plist
    info: [debug] Cleaning up appium session
    
    Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --pre-launch --log "/tmp/appium.log" --platform-version "8.1" --platform-name "iOS" --app "com.vervewireless.iphone.qa.beta" --show-ios-log --device-name "iPhone 6"
    
    info: [debug] Starting Appium in pre-launch mode
    
    info: Pre-launching app
    
    info: [debug] App is an iOS bundle, will attempt to run as pre-existing
    info: [debug] Creating new appium session 255637cf-2d12-41c3-8610-e53f804d229b
    info: [debug] Removing any remaining instruments sockets
    info: [debug] Cleaned up instruments socket /tmp/instruments_sock
    info: [debug] Setting Xcode folder
    
    info: [debug] Setting Xcode version
    
    info: [debug] Setting iOS SDK Version
    
    info: [debug] Getting sdk version from xcrun with a timeout
    
    info: [debug] iOS SDK Version set to 8.1
    info: [debug] Checking whether instruments supports our device string
    info: [debug] Getting list of devices instruments supports
    info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
    
    info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}
    
    info: [debug] fixDevice is on
    info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
    info: [debug] iOS sim UDID is 4391D23F-BA21-4FB8-8887-0972D2911420
    
    info: [debug] Detecting automation tracetemplate
    info: [debug] Not auto-detecting udid, running on sim
    info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vervewireless.iphone.qa.beta/en.lproj/Localizable.strings
    info: Will try to parse the plist file as XML
    info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vervewireless.iphone.qa.beta/en.lproj/Localizable.strings
    warn: Could not parse app Localizable.strings assuming it doesn't exist
    info: [debug] Creating instruments
    info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
    info: [debug] Preparing uiauto bootstrap
    info: [debug] Dynamic bootstrap dir: /Users/alkaffkhan/Library/Application Support/appium/bootstrap
    info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
    info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
    ...
    
    error: Could not set the device type in Info.plist

**Comment by amedvedjev** [comment]
same problem. working nice with 1.3.6 BUT starting from 1.3.7 same error when try to open drive.

there is only "version.plist" file in Xcode

**Comment by moizjv** [comment]
@amedvedjev @karunakaranvrv can you try with `1.4.0 beta`?

**Comment by amedvedjev** [comment]
tried with 1.4.0-beta. same problem. 

[36minfo[39m: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not get Xcode version. /Applications/Xcode.app/Contents/Info.plist/ does not exist on disk.)","origValue":"Could not get Xcode version. /Applications/Xcode.app/Contents/Info.plist/ does not exist on disk."},"sessionId":null}

**Comment by jlipps** [comment]
@Jonahss could this be related to appium-xcode refactor?

**Comment by jlipps** [comment]
@amedvedjev @karunakaranvrv have you guys ever actually opened the Xcode app? Does it work?

**Comment by Jonahss** [comment]
The error changed between versions, so it's related to my changes, but I think the error is more informative now. `/Applications/Xcode.app/Contents/Info.plist/` should exist, no? There's a way to set a custom xcode location if it's somewhere else I think.

**Comment by amedvedjev** [comment]
of cause working. npm install -g appium@1.3.6 - and everything working.

**Comment by amedvedjev** [comment]
and i manually checked that this info.list exists in xcode.app.

**Comment by amedvedjev** [comment]
are you sure that "/Applications/Xcode.app/Contents/Info.plist/" - is correct?

i believe it should be like - "/Applications/Xcode.app/Contents/Info.plist" - without last "/".

**Comment by jlipps** [comment]
I think so too, the slash is odd. why is it getting added? What version of appium-xcode is in node_modules, @amedvedjev ?

**Comment by hitesh02sharma** [comment]
anyone have final solution of acutal issue ? I am still facing the same

**Comment by strizhechenko** [comment]
Me too. Maybe it's because I use appium-desktop 1.2.6 release which probably has no fixes for this problem?

**Comment by YaakovRaif** [comment]
The issue still exits. somebody have a solution?
