### ISSUE TITLE
Unlock device

### ISSUE THREAD

**Issue by gilsha** [appium/appium#5006]
Hi
I work with Eclipse in Windows.
I manage to invoke Android Emulator device (AVD).
Appium manage to unlock it but then fails with error that it didn't.

If we can't solve this, is there an option to define in the device definition in Android AVD Manager to invoke it unlocked?

Thanks

**Comment by amedvedjev** [comment]
why not in Android emulator in Settings set Lock screen to None and just in case screenTimeout to e.g. 5min.

**Comment by gilsha** [comment]
You mean in the device menu?

**Comment by amedvedjev** [comment]
run emulator manually. then manually open settings menu and change Lock screen settings. once you did it one time with any later same emulator start it will start with changed settings.

**Comment by gilsha** [comment]
Thanks a lot!, did it, working.

**Comment by moizjv** [comment]
@amedvedjev  thanks!
