### ISSUE TITLE
Sinc on AVD

### ISSUE THREAD

**Issue by gilsha** [appium/appium#5007]
Hi

I manage to sync on the opening of Android Virtual Device (I invoke it from Java code), by searching windows processes. But the fact that the process is running doesn't mean the device is ready. How do I sync till its fully loaded?

Thanks, 

Gil

**Comment by amedvedjev** [comment]
you should manage in java code to start Android Emulator programmatically and just add some sleep time (easiest) or write activity in java to pull devices list and find if needed device exists in list (harder)

**Comment by gilsha** [comment]
Thanks Alex. That is exactly what I'm doing, but I don't wish to use sleep time. 
I tried:
capabilities.setCapability("deviceReadyTimeout", 120);
capabilities.setCapability("androidDeviceReadyTimeout", 120);

but it didn't work, maybe because of my second issue - screen unlock...

**Comment by moizjv** [comment]
@gilsha : Can you please use [forum](https://discuss.appium.io/) for questions. Here issues are for potential bugs. Feel free to raise an issue if you feel its a bug in appium. Thanks

**Comment by gilsha** [comment]
Sure
