### ISSUE TITLE
Appium mobile apps test

### ISSUE THREAD

**Issue by CharlieCorv** [appium/appium#5008]
I started recently testing mobile Apps using Appium. I am trying to understand difference in testingApps of type Native, WebApps, Hybrid. I did Google search for examples for these. I get details on what they are but not examples. Please give some examples for each category for me to test better. How do we identify which is which? Thanks in advance.

**Comment by moizjv** [comment]
@CharlieCorv can you use [forum](https://discuss.appium.io/) for asking questions? [Here](https://github.com/appium/sample-code/tree/master/sample-code/apps) are few apps that you can look into . Thanks
