### ISSUE TITLE
android can't get classname

### ISSUE THREAD

**Issue by vascon8** [appium/appium#5011]
rest.get('/wd/hub/session/:sessionId?/element/:elementId?/name', controller.getName);
this method can't return the correct classname,it's always return null

**Comment by vascon8** [comment]
i have tried 1.3.1 and 1.3.5

**Comment by jlipps** [comment]
not sure if this method is even supported outside of a web context. what would it even mean for a native element?

**Comment by Jonahss** [comment]
Closed due to inactivity. Comment here to reopen.
