### ISSUE TITLE
Chromerdriver functionality for non-proxy routes is broken, as we are not overriding chrome session id with appium session id

### ISSUE THREAD

**Issue by yaphatak** [appium/appium#5013]
https://github.com/appium/appium/blob/master/lib/devices/android/chrome.js#L104-L105

is not returning any chrome session id anymore so in turn this is not executing
https://github.com/appium/appium/blob/master/lib/appium.js#L274-L278

So any avoidProxy routes wont get executed as session ids wont match here and it will return 404
https://github.com/appium/appium/blob/master/lib/server/controller.js#L51-L54

Can we fix this sooner? I can try to fix it but with newer chromedriver i see we are exuting wd/gub/session here https://github.com/appium/appium-chromedriver/blob/master/lib/chromedriver.js#L123-L124

But we are not parsing session id? should we call this again in chrome.js to get session id?

Thanks

**Comment by jlipps** [comment]
this should be handled in the appium-jsonwp-proxy package. what version of appium-chromedriver is included with your appium? can you check in node_modules/appium-chromedriver/package.json? then also check the version of node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/package.json.

**Comment by yaphatak** [comment]
1.0.1 for chromedriver and 1.1.1 for appium-jsonwp-proxy
chromesriver.start should return session id ,right?

**Comment by jlipps** [comment]
those are correct. will look into fixing this

**Comment by jlipps** [comment]
@yaphatak thanks for the thorough investigation, I see what you're saying about sessionId. I'll add it to appium-chromedriver so we can get it in chrome.js

**Comment by jlipps** [comment]
@yaphatak can you pull https://github.com/appium/appium/pull/5019 and run `npm install` and give this a shot to see if it resolves your issue?

**Comment by bayandin** [comment]
Thanks!

**Comment by yaphatak** [comment]
@jlipps : sorry i ddint see this earlier. I will give a try today

**Comment by yaphatak** [comment]
Thanks. It works.
