### ISSUE TITLE
Automating 2 apps with 2 sessions is not working in Appium 1.3.7

### ISSUE THREAD

**Issue by kani19** [appium/appium#5014]
Hi,

My scenario is -
1. Launch my app 
2. Launch safari
3. Open some links and perform some task on those links
4. Go back to first app and perform some task

I am using 2 drivers. The problem is in 2nd step. As soon as Appium tries to launch Safari, it says "iOS Simulator can not install the application. It tries 3 times.

It was working with Appium version 1.3.4

Code -->

```
public IOSDriver driver1;
public IOSDriver driver2;

    DesiredCapabilities capabilities_cc = new DesiredCapabilities();  
    capabilities_cc.setCapability("automationName", "Appium"); 
    capabilities_cc.setCapability("platformName", "iOS");
    capabilities_cc.setCapability("deviceName", "iPhone Simulator");
    capabilities_cc.setCapability("platformVersion", "7.1");
    capabilities_cc.setCapability("app", appPath);  
    capabilities_cc.setCapability("noReset", true);

    driver1 = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities_cc);

    driver1.quit();

    DesiredCapabilities capabilities_safari = new DesiredCapabilities();  
    capabilities_safari.setCapability("automationName", "Appium"); 
    capabilities_safari.setCapability("platformName", "iOS");
    capabilities_safari.setCapability("deviceName", "iPhone Simulator");
    capabilities_safari.setCapability("platformVersion", "7.1");
    capabilities_safari.setCapability("noReset", "true");
    capabilities_safari.setCapability("browserName", "Safari");
    capabilities_safari.setCapability("newCommandTimeout", "7200");
    capabilities_safari.setCapability("autoAcceptAlerts", "true");

    driver2 = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities_safari);
```

Logs -->

info: <-- DELETE /wd/hub/session/c8ab9f3f-909c-4470-8fd9-1828fcf6ad1f 200 1284.149 ms - 76 {"status":0,"value":null,"sessionId":"c8ab9f3f-909c-4470-8fd9-1828fcf6ad1f"}

info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":"7200","autoAcceptAlerts":"true","platformVersion":"7.1","deviceName":"iPhone Simulator","platformName":"iOS","browserName":"Safari","Appium":null,"noReset":"true"}}

info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
warn: Converting cap autoAcceptAlerts from string to boolean. This might cause unexpected behavior.
warn: Converting cap noReset from string to boolean. This might cause unexpected behavior.

info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : Appium
info: [debug] Configuring Safari session
info: [debug] Creating new appium session 12e8ca08-afdb-4644-bbfc-5df70c60cfea
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder

info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 7.1

info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

error: Failed getting devices. Err: Error: Command failed: /bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices
. Stdout: Known Devices:
. Stderr: .

info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.1","iOSSDKVersion":"7.1","deviceName":"iPhone Simulator","platformVersion":"7.1"}

info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone - Simulator - iOS 7.1" to: "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1"
info: [debug] Final device string is: 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
info: [debug] Trying to use mobile safari, version 7.1
info: [debug] Looking for built in app MobileSafari

info: [debug] Got app, trying to move /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/MobileSafari.app to tmp dir

info: [debug] Copied MobileSafari to /tmp/Appium-MobileSafari-7.1.app

info: [debug] Copied MobileSafari to /tmp/Appium-MobileSafari-7.1.app

info: [debug] Copied MobileSafari to /tmp/Appium-MobileSafari-7.1.app

info: [debug] Temporarily deleted original app at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/MobileSafari.app

info: [debug] Using mobile safari app at /tmp/Appium-MobileSafari-7.1.app
info: [debug] Detecting automation tracetemplate

info: [debug] Not auto-detecting udid, running on sim

info: [debug] Temporarily deleted original app at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/MobileSafari.app

info: [debug] Using mobile safari app at /tmp/Appium-MobileSafari-7.1.app
info: [debug] Getting bundle ID from app

info: [debug] Temporarily deleted original app at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/MobileSafari.app

info: [debug] Using mobile safari app at /tmp/Appium-MobileSafari-7.1.app
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/user/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":true,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}

info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

info: [debug] Dynamic bootstrap path: /Users/user/Library/Application Support/appium/bootstrap/bootstrap-2f05865489dc146e.js
info: [debug] Could not parse plist file (as binary) at /tmp/Appium-MobileSafari-7.1.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /tmp/Appium-MobileSafari-7.1.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] We're on iOS7.1+ so forcing defaultDevice on

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.1","iOSSDKVersion":"7.1","deviceName":"iPhone Simulator","platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone - Simulator - iOS 7.1" to: "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1"
info: [debug] Final device string is: 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'

info: [debug] Reusing dynamic bootstrap: /Users/user/Library/Application Support/appium/bootstrap/bootstrap-2f05865489dc146e.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.1","iOSSDKVersion":"7.1","deviceName":"iPhone Simulator","platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone - Simulator - iOS 7.1" to: "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1"
info: [debug] Final device string is: 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
info: [debug] Checking whether we need to set app preferences
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Not setting locale
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS 7.\* simulator log capture
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Not pre-launching simulator
info: [debug] Not installing to real device since we're on sim
info: [debug] Starting command proxy.

info: [debug] Parsed app Info.plist (as binary)
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments

info: [debug] Attempting to run app on iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1" /tmp/Appium-MobileSafari-7.1.app -e UIASCRIPT "/Users/user/Library/Application Support/appium/bootstrap/bootstrap-2f05865489dc146e.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd5/InstrumentsShim.dylib","LIB_PATH":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd5"}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] Wrote new app Info.plist with device type
info: [debug] Instruments launched. Starting poll loop for new commands.
info: [debug] Copying app back to its original place

info: [debug] Setting bootstrap config keys/values

info: [debug] Pushing command to appium work queue: "target = $.target();\nau = $;\n$.isVerbose = true;\n"

info: [debug] Setting initial orientation to PORTRAIT

info: [debug] Pushing command to appium work queue: "au.setScreenOrientation('PORTRAIT')"

info: [IOS_SYSLOG_ROW ] Apr 28 14:23:17 user-mac SimulatorBridge[21296] <Warning>: LaunchServices: installing app for existing placeholder LSApplicationProxy: com.apple.mobilesafari

info: [IOS_SYSLOG_ROW ] Apr 28 14:23:17 user-mac SimulatorBridge[21296] <Warning>: LaunchServices: Not creating progress for LSApplicationProxy: com.apple.mobilesafari since it is not a placeholder.

info: [IOS_SYSLOG_ROW ] Apr 28 14:23:17 user-mac installd[21303] <Notice>: 0x105881000 handle_install_for_ls: Install of "/tmp/Appium-MobileSafari-7.1.app" requested by SimulatorBridge

info: [IOS_SYSLOG_ROW ] Apr 28 14:23:19 user-mac installd[21303] <Notice>: 0x105881000 MobileInstallationInstall_Server: Installing app com.apple.mobilesafari

info: [IOS_SYSLOG_ROW ] Apr 28 14:23:19 user-mac installd[21303] <Error>: 0x105881000 check_can_install: Cannot upgrade system/internal application com.apple.mobilesafari because it does not have the required entitlement.

info: [IOS_SYSLOG_ROW ] Apr 28 14:23:20 user-mac installd[21303] <Error>: 0x105881000 install_application: Could not preflight application install

info: [IOS_SYSLOG_ROW ] Apr 28 14:23:20 user-mac SimulatorBridge[21296] <Error>: 0x10296b310 MobileInstallationInstallForLaunchServices: failed with -1
info: [IOS_SYSLOG_ROW ] Apr 28 14:23:20 user-mac SimulatorBridge[21296] <Warning>: ERROR: MobileInstallationInstallForLaunchServices returned nil

info: [IOS_SYSLOG_ROW ] Apr 28 14:23:20 user-mac installd[21303] <Error>: 0x105881000 handle_install_for_ls: API failed

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"12e8ca08-afdb-4644-bbfc-5df70c60cfea"}
info: <-- GET /wd/hub/status 200 2.087 ms - 178 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"12e8ca08-afdb-4644-bbfc-5df70c60cfea"}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"12e8ca08-afdb-4644-bbfc-5df70c60cfea"}
info: <-- GET /wd/hub/status 200 1.608 ms - 178 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"12e8ca08-afdb-4644-bbfc-5df70c60cfea"}

warn: Instruments socket client never checked in; timing out (global)

info: [debug] Killall instruments

info: [debug] [INSTSERVER] Instruments exited with code null

info: [debug] Killall instruments

info: [debug] Instruments never checked in
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iPhoneSimulator

info: Launching instruments

info: [debug] Attempting to run app on iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1

info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1" /tmp/Appium-MobileSafari-7.1.app -e UIASCRIPT "/Users/user/Library/Application Support/appium/bootstrap/bootstrap-2f05865489dc146e.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd5/InstrumentsShim.dylib","LIB_PATH":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd5"}
info: [debug] And launch timeouts (in ms): {"global":90000}

**Comment by kani19** [comment]
Logs -- >


info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":"7200","autoAcceptAlerts":"true","platformVersion":"7.1","deviceName":"iPhone Simulator","platformName":"iOS","browserName":"Safari","Appium":null,"noReset":"true"}}

info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
warn: Converting cap autoAcceptAlerts from string to boolean. This might cause unexpected behavior.
warn: Converting cap noReset from string to boolean. This might cause unexpected behavior.
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : Appium

info: [debug] Configuring Safari session
info: [debug] Creating new appium session 63790b53-6e90-4f04-8f77-b95bee673a95

info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder

info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 7.1

info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.1","iOSSDKVersion":"7.1","deviceName":"iPhone Simulator","platformVersion":"7.1"}

info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone - Simulator - iOS 7.1" to: "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1"
info: [debug] Final device string is: 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
info: [debug] Trying to use mobile safari, version 7.1
info: [debug] Looking for built in app MobileSafari

info: [debug] Got app, trying to move /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/MobileSafari.app to tmp dir

info: [debug] Copied MobileSafari to /tmp/Appium-MobileSafari-7.1.app

info: [debug] Copied MobileSafari to /tmp/Appium-MobileSafari-7.1.app

info: [debug] Temporarily deleted original app at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/MobileSafari.app

info: [debug] Using mobile safari app at /tmp/Appium-MobileSafari-7.1.app
info: [debug] Detecting automation tracetemplate

info: [debug] Not auto-detecting udid, running on sim

info: [debug] Temporarily deleted original app at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/Applications/MobileSafari.app

info: [debug] Using mobile safari app at /tmp/Appium-MobileSafari-7.1.app
info: [debug] Getting bundle ID from app

info: [debug] Could not parse plist file (as binary) at /tmp/Appium-MobileSafari-7.1.app/en.lproj/Localizable.strings

info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /tmp/Appium-MobileSafari-7.1.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/user/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":true,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}

info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

info: [debug] Dynamic bootstrap path: /Users/user/Library/Application Support/appium/bootstrap/bootstrap-2f05865489dc146e.js

info: [debug] Reusing dynamic bootstrap: /Users/user/Library/Application Support/appium/bootstrap/bootstrap-2f05865489dc146e.js

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.1","iOSSDKVersion":"7.1","deviceName":"iPhone Simulator","platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone - Simulator - iOS 7.1" to: "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1"
info: [debug] Final device string is: 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"5.1","iOSSDKVersion":"7.1","deviceName":"iPhone Simulator","platformVersion":"7.1"}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone - Simulator - iOS 7.1" to: "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1"
info: [debug] Final device string is: 'iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1'
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Checking whether we need to set app preferences
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] Not setting locale

info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS 7.* simulator log capture
info: [debug] Parsed app Info.plist (as binary)

info: [debug] Wrote new app Info.plist with device type

info: [debug] Not pre-launching simulator
info: [debug] Not installing to real device since we're on sim
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone Retina (4-inch 64-bit) - Simulator - iOS 7.1" /tmp/Appium-MobileSafari-7.1.app -e UIASCRIPT "/Users/user/Library/Application Support/appium/bootstrap/bootstrap-2f05865489dc146e.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd5/InstrumentsShim.dylib","LIB_PATH":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd5"}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] Instruments launched. Starting poll loop for new commands.

info: [debug] Copying app back to its original place

info: [debug] Setting bootstrap config keys/values

info: [debug] Pushing command to appium work queue: "target = $.target();\nau = $;\n$.isVerbose = true;\n"

info: [IOS_SYSLOG_ROW ] Apr 28 14:39:17 user-mac SimulatorBridge[21748] <Warning>: LaunchServices: installing app for existing placeholder LSApplicationProxy: com.apple.mobilesafari

info: [IOS_SYSLOG_ROW ] Apr 28 14:39:17 user-mac SimulatorBridge[21748] <Warning>: LaunchServices: Not creating progress for LSApplicationProxy: com.apple.mobilesafari since it is not a placeholder.
info: [IOS_SYSLOG_ROW ] Apr 28 14:39:17 user-mac installd[21741] <Notice>: 0x102f81000 handle_install_for_ls: Install of "/tmp/Appium-MobileSafari-7.1.app" requested by SimulatorBridge

info: [IOS_SYSLOG_ROW ] Apr 28 14:39:19 user-mac installd[21741] <Notice>: 0x102f81000 MobileInstallationInstall_Server: Installing app com.apple.mobilesafari

info: [IOS_SYSLOG_ROW ] Apr 28 14:39:19 user-mac installd[21741] <Error>: 0x102f81000 check_can_install: Cannot upgrade system/internal application com.apple.mobilesafari because it does not have the required entitlement.

info: [IOS_SYSLOG_ROW ] Apr 28 14:39:19 user-mac installd[21741] <Error>: 0x102f81000 install_application: Could not preflight application install

info: [IOS_SYSLOG_ROW ] Apr 28 14:39:19 user-mac SimulatorBridge[21748] <Error>: 0x10296b310 MobileInstallationInstallForLaunchServices: failed with -1
info: [IOS_SYSLOG_ROW ] Apr 28 14:39:19 user-mac SimulatorBridge[21748] <Warning>: ERROR: MobileInstallationInstallForLaunchServices returned nil

info: [IOS_SYSLOG_ROW ] Apr 28 14:39:19 user-mac installd[21741] <Error>: 0x102f81000 handle_install_for_ls: API failed

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"63790b53-6e90-4f04-8f77-b95bee673a95"}

info: <-- GET /wd/hub/status 200 3.634 ms - 178 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"63790b53-6e90-4f04-8f77-b95bee673a95"}
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"63790b53-6e90-4f04-8f77-b95bee673a95"}
info: <-- GET /wd/hub/status 200 1.302 ms - 178 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"63790b53-6e90-4f04-8f77-b95bee673a95"}



![screen shot 2015-04-28 at 2 41 47 pm](https://cloud.githubusercontent.com/assets/4057145/7366292/ddb694bc-edb4-11e4-8ea9-64af167f8165.png)

**Comment by moizjv** [comment]
@kani19 does second cap work by itself?

**Comment by kani19** [comment]
@moizjv  yes it works by itself.

**Comment by kani19** [comment]
Some more logs:


info: [IOS_SYSLOG_ROW ] May  5 17:11:19 user-mac SimulatorBridge[3817] <Warning>: LaunchServices: installing app for existing placeholder LSApplicationProxy: com.apple.mobilesafari

info: [IOS_SYSLOG_ROW ] May  5 17:11:19 user-mac SimulatorBridge[3817] <Warning>: LaunchServices: Not creating progress for LSApplicationProxy: com.apple.mobilesafari since it is not a placeholder.
info: [IOS_SYSLOG_ROW ] May  5 17:11:19 user-mac installd[3824] <Notice>: 0x105881000 handle_install_for_ls: Install of "/tmp/Appium-MobileSafari-7.1.app" requested by SimulatorBridge

info: [IOS_SYSLOG_ROW ] May  5 17:11:22 user-mac installd[3824] <Notice>: 0x105881000 MobileInstallationInstall_Server: Installing app com.apple.mobilesafari

info: [IOS_SYSLOG_ROW ] May  5 17:11:22 user-mac installd[3824] <Error>: 0x105881000 check_can_install: Cannot upgrade system/internal application com.apple.mobilesafari because it does not have the required entitlement.

info: [IOS_SYSLOG_ROW ] May  5 17:11:22 user-mac installd[3824] <Error>: 0x105881000 install_application: Could not preflight application install

info: [IOS_SYSLOG_ROW ] May  5 17:11:22 user-mac SimulatorBridge[3817] <Error>: 0x10296b310 MobileInstallationInstallForLaunchServices: failed with -1
info: [IOS_SYSLOG_ROW ] May  5 17:11:22 user-mac SimulatorBridge[3817] <Warning>: ERROR: MobileInstallationInstallForLaunchServices returned nil

info: [IOS_SYSLOG_ROW ] May  5 17:11:22 user-mac installd[3824] <Error>: 0x105881000 handle_install_for_ls: API failed

**Comment by moizjv** [comment]
@kani19 can you try with `1.4.0 beta`

**Comment by Jonahss** [comment]
Oh huh. This is odd. It looks like appium isn't able to install MobileSafari on the device?
What happens if you run a regular Safari test with the `no-reset` capability. Then, modify your tests desired capabilities so they run the app `com.apple.mobilesafari` using the bundleId?

Instruments should skip the installation step, and mobileSafari should already be on your simulator.

**Comment by kani19** [comment]
@moizjv same issue with 1.4.0-beta

@Jonahss yes MobileSafari app disappears on its own when running the tests. I am sure this is an issue with Safari installation. In a regular safari test everything is smooth. Issue appears only when i run 2 apps

**Comment by Jonahss** [comment]
I was able to successfully reproduce this on appium master (commit 84669e81c81b5d9549707bd86a64638683a75147) here: https://github.com/Jonahss/appium-es7-example/tree/repro-appium-5014

I noticed that this error happens on 7.1 simulators, but works fine on 8.3 simulators. Didn't test other versions.
