### ISSUE TITLE
Unable to identify switch button

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium#5020]
Hi @jlipps ,
Appium inspector unable to identify the enable/disable switch button. I have one cell that have a text and a switch button. But appium inspector able to identify only text not switch button. 

Please see attached sceenshot
![screen shot 2015-04-29 at 11 53 45 am](https://cloud.githubusercontent.com/assets/8439309/7385658/5e350aee-ee67-11e4-8c9a-9c09f3b01a02.png)

**Comment by jlipps** [comment]
is it a custom control? uiautomation can't access custom controls

**Comment by shivakrishnach31** [comment]
Custom control means? How to handle if it is a custom control?

**Comment by shivakrishnach31** [comment]
Custom control means? How to handle if it is a custom control?

**Comment by shivakrishnach31** [comment]
@jlipps, any update?

**Comment by jlipps** [comment]
you can't automate custom controls with UIAutomation (and therefore, Appium)

**Comment by shivakrishnach31** [comment]
is there any other way to handle them. Because they have major part in my App. I have to handle them... or Can you implement this in next version?

**Comment by jlipps** [comment]
You can try to enable accessibility on them, as in [this article](http://www.mattmccomb.com/blog/2013/06/02/ios-functional-testing-with-uiautomation/):

> Additionally if you have written a custom control/view subclass you will need to enable accessibility using: `[myCustomView setAccessibilityEnabled:YES];`

**Comment by jlipps** [comment]
(added this to the docs in https://github.com/appium/appium/blob/master/docs/en/appium-setup/troubleshooting.md#ios)

**Comment by shivakrishnach31** [comment]
@jlipps , I informed about your suggestion to my dev team. They tried to add the line you suggested, but they didn't find it ie: "setAccessibilityEnabled:YES". is there a way to find it and add it to dev code.

**Comment by shivakrishnach31** [comment]
@jlipps , any update?

**Comment by jlipps** [comment]
Maybe the custom view is only defined in the interface builder? In which case you'd need to do some actual coding to set things up. Unfortunately this is as far as I can go in helping you with this issue. The official stance for Appium on custom views is that they're not supported (since they're not supported in UIAutomation)
