### ISSUE TITLE
Appium inspector crashes when swipe action fired in android

### ISSUE THREAD

**Issue by debugger89** [appium/appium#5021]
<b>Problem : </b>
When using the appium inspector for an Android application and when the swipe action is fired to the device inspector is crashing without even giving a error log.
(Issue exists when running on the real android device. Not tested with android emulator.)

<b>Stpes to re-create: </b>
<ol>
<li>Launch the inspector for android application through Appium.</li>
<li>Click on "Swipe" action under touch category</li>
<li>Click on anywhere on the preview to start swipe</li>
<li>Appium crashes.</li>
</ol>
<b>System information </b>
<ul>
<li>Mac osx 10.10 Yosemite </li>
<li>Appium 1.3.7</li>
<li>Android 4.4.2 (Samsung galaxy s5)</li>
</ul>

**Comment by Jonahss** [comment]
This sounds like more of an issue with the Appium inspector, and not the core appium repository. Could you repost your issue on the repository for the Inspector?
Thanks.
