### ISSUE TITLE
Replace uiwatchers with IActivityController 

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5023]
See https://github.com/appium/appium/issues/4698 for the details. Work in progress code is [available in this branch](https://github.com/bootstraponline/appium/commit/795b5f2ae3c1b346d5bd2a8e1c89eb131efc337f).

The summary is that by using an internal API to handle crash dialogs we're able to avoid a significant CPU penalty by not constantly polling via [uiautomator uiwatchers](https://github.com/appium/appium/blob/master/lib/devices/android/bootstrap/src/com/android/uiautomator/common/UiWatchers.java).

It looks like [dynamic proxies](tutorials.jenkov.com/java-reflection/dynamic-proxies.html) [would allow](http://stackoverflow.com/a/19440217) accessing the [Android hidden APIs](http://developer.sonymobile.com/2011/10/28/code-examples-using-hidden-android-apis/) via reflection then we wouldn't have to copy the code. I think recreating our own android.jar to avoid reflection is going to be more painful than it's worth.

**Comment by jlipps** [comment]
since we're going to focus on the uiautomator2 driver moving forward, i don't think this work is applicable any more.
