### ISSUE TITLE
How to reslove the appium crash?

### ISSUE THREAD

**Issue by valarmathivrv** [appium/appium#5024]
1.  I have installed appium 1.3.7 version in mac machine.
  2. I have started appium server for android app in android device.
  3.  In android device, the app get installed and opened successfully.
  4.  I have clicked the show inspector button and then I can able to see the inspector screen and then my appium inspector get crashed.

5. I have attached the screen shot below for reference.

![screen shot 2015-04-29 at 6 07 29 pm](https://cloud.githubusercontent.com/assets/9842215/7406117/063933c4-ef1b-11e4-9bb8-488bdae8d661.png)

**Comment by Jonahss** [comment]
If you are using the Appium Inspector, you should post your issue on that github repository. Issues here should relate directly to appium. Thanks :)
