### ISSUE TITLE
When I get a UIElement, how can I call some special method on it ?

### ISSUE THREAD

**Issue by zxhfirefox** [appium/appium#5027]
For example, in iOS, I got a UIASegmentedControl, how can I call its selectedButton method?

**Comment by Jonahss** [comment]
You could try using the `ios-uiautomation` locator strategy https://discuss.appium.io/t/how-to-use-findelements-byiosuiautomation/607

**Comment by zxhfirefox** [comment]
Hi, my question may not be very clear. What I want to know is that I already find the element, but I don't know how to call it's method which is documented in iOS UIAutomation Docs, and I use Python client.

**Comment by Jonahss** [comment]
Ah, you can't call UIAutomation commands on an element you've already found.
What are you trying to do with the 'selectedButton' method? Perhaps we could add it as a feature to appium.

**Comment by zxhfirefox** [comment]
Oh, I think it should be a feature that we can call these methods on the UIElement in a some kind of RPC ways(use string to name the methods maybe).
for my example, I found a UIASegmentedControl, but I can not find out which segment is selected in a easy. 
I would like have something like this:

myElement = find_element()
method_return = myElement.send_method(method_name, method_args)

I think, this may be hard to make it Android and iOS clear for this feature, but I think if has will be very good.

**Comment by Jonahss** [comment]
@jlipps what do you think?

We are usually against setting up commands that allow arbitrary execution of native automation methods.

**Comment by jlipps** [comment]
two options:

1) just use executeScript, as in `driver.execute_script("au.getElement('" + element.id + "').selected`;
2) we can add an attribute to this type of element so you can do `element.get_attribute("foo");`. just need to know what kind of attribute it is we're inspecting

**Comment by sebv** [comment]
Looks like this can be closed, shout if not.
