### ISSUE TITLE
how can i get element location on python?

### ISSUE THREAD

**Issue by ruthwe** [appium/appium#5028]
location=tf.get_attribute("location")
throws 
WebDriverException: Message: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.

**Comment by paymand** [comment]
Try:
```python
location = tf.location
```

**Comment by ruthwe** [comment]
thanks ur worked
On Apr 30, 2015, at 3:40 PM, Payman Delshad <notifications@github.com<mailto:notifications@github.com>> wrote:


Try:

location = tf.location

**Comment by ruthwe** [comment]
how come i don’t see that function on python-client<https://github.com/appium/python-client>/appium<https://github.com/appium/python-client/tree/master/appium>/webdriver<https://github.com/appium/python-client/tree/master/appium/webdriver>/webdriver.py ?
On Apr 30, 2015, at 3:40 PM, Payman Delshad <notifications@github.com<mailto:notifications@github.com>> wrote:


Try:

location = tf.location

**Comment by paymand** [comment]
``location`` is a property of ``WebElement``  (not ``WebDriver``), so had it been defined anywhere, it should have been in https://github.com/appium/python-client/blob/master/appium/webdriver/webelement.py. However, in the Python client we're just extending the Selenium ``WebElement`` which is where ``location`` is defined. See https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webelement.py.

**Comment by ruthwe** [comment]
how do i get web element path?
because getattribute(xpath)
or item.xpath
doesn’t work!!!
what do i do?
On May 28, 2015, at 7:09 PM, Payman Delshad <notifications@github.com<mailto:notifications@github.com>> wrote:


location is a property of WebElement (not WebDriver), so had it been defined anywhere, it should have been in https://github.com/appium/python-client/blob/master/appium/webdriver/webelement.py. However, in the Python client we're just extending the Selenium WebElement which is where location is defined. See https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webelement.py.

**Comment by paymand** [comment]
Don't think we support getting xpath like that.
