### ISSUE TITLE
`--app` server arg is broken when passing BundleId

### ISSUE THREAD

**Issue by valarmathivrv** [appium/appium#5029]
1. I have installed appium version 1.3.3.
2. I have launched appium server to inspect an ios app.
3. I have attached the screen shot for reference.
4. 
![screen shot 2015-04-30 at 4 30 50 pm](https://cloud.githubusercontent.com/assets/9842215/7412850/2c766806-ef64-11e4-99e4-8ba4d53e5655.png)
I am getting the below mentioned error message.

**Comment by imurchie** [comment]
This generally means that somewhere along the line MobileSafari.app has been lost from the sim directory. Alas. It should be, I think, `/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 8.1.simruntime/Contents/Resources/RuntimeRoot/Applications/MobileSafari.app`.

If it is not there, you can try to uninstall and reinstall the simulator through Xcode.

**Comment by jlipps** [comment]
I actually think the caps are weird here. With 8.x we don't need to reference MobileSafari.app, we just use bundleId. So somehow the caps are making Appium think we're on a lower version of safari.

**Comment by jlipps** [comment]
@valarmathivrv can you paste the entire appium log, please?

**Comment by valarmathivrv** [comment]
I have attached the full apium log below

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node'; lib/server/main.js --command-timeout "7200" --pre-launch --log "/tmp/appium.log" --platform-version "8.1" --platform-name "iOS" --app "com.vervewireless.iphone.qa.beta" --show-ios-log --device-name "iPhone 6"

info: [debug] Starting Appium in pre-launch mode

info: Pre-launching app

info: [debug] App is an iOS bundle, will attempt to run as pre-existing

info: [debug] Creating new appium session 62b3e6af-2864-4256-9559-97b5a17fcb44

info: [debug] Removing any remaining instruments sockets

info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder

info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 8.1

info: [debug] Checking whether instruments supports our device string

info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'

info: [debug] iOS sim UDID is 4391D23F-BA21-4FB8-8887-0972D2911420
info: [debug] Detecting automation tracetemplate

info: [debug] Not auto-detecting udid, running on sim

info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vervewireless.iphone.qa.beta/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vervewireless.iphone.qa.beta/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/alkaffkhan/Library/Application Support/appium/bootstrap

info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/alkaffkhan/Library/Application Support/appium/bootstrap/bootstrap-931e8d7703a594e3.js

error: Could not set the device type in Info.plist

info: [debug] Reusing dynamic bootstrap: /Users/alkaffkhan/Library/Application Support/appium/bootstrap/bootstrap-931e8d7703a594e3.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vervewireless.iphone.qa.beta/Info.plist
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vervewireless.iphone.qa.beta/Info.plist
info: [debug] Cleaning up appium session

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node'; lib/server/main.js --command-timeout "7200" --pre-launch --log "/tmp/appium.log" --platform-version "8.1" --platform-name "iOS" --app "com.vervewireless.iphone.qa.beta" --show-ios-log --device-name "iPhone 6"

info: [debug] Starting Appium in pre-launch mode

info: Pre-launching app

info: [debug] App is an iOS bundle, will attempt to run as pre-existing
info: [debug] Creating new appium session 255637cf-2d12-41c3-8610-e53f804d229b
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder

info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 8.1
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] iOS sim UDID is 4391D23F-BA21-4FB8-8887-0972D2911420

info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vervewireless.iphone.qa.beta/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vervewireless.iphone.qa.beta/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/alkaffkhan/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

error: Could not set the device type in Info.plist

**Comment by Jonahss** [comment]
@jlipps thoughts?

**Comment by jlipps** [comment]
first of all, the logs provided have nothing to do with the screenshot; the logs don't say anything about safari, while the screenshot does. secondly, there aren't enough of the logs to prove that there's even a problem. in the second set of logs, does the session start? or not?

**Comment by valarmathivrv** [comment]
@jlipps, same problem still persist, I have pasted the log below. 
Launching Appium with command: '/Applications/Appium 3.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --pre-launch --platform-version "8.1" --platform-name "iOS" --app "com.vr.iphone.vrnews" --show-ios-log --device-name "iPhone 6"

Launching Appium with command: '/Applications/Appium 3.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --pre-launch --platform-version "8.1" --platform-name "iOS" --app "com.vr.iphone.vrnews" --show-ios-log --device-name "iPhone 6"

info: [debug] Starting Appium in pre-launch mode

info: Pre-launching app
info: [debug] App is an iOS bundle, will attempt to run as pre-existing

info: [debug] Creating new appium session c3dfcfe4-2cca-4352-8065-9683c60c13d8
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.1
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] iOS sim UDID is 4391D23F-BA21-4FB8-8887-0972D2911420
info: [debug] Detecting automation tracetemplate

error: Could not set the device type in Info.plist

**Comment by Jonahss** [comment]
Thanks for supplying the code you are using to start the appium server.

You've found a bug. Looks like the `--app` server flag is broken for bundle IDs.

Change your command to supply the full path to your app file, instead of the bundleId as a workaround. I'm adding this to our bugs Milestone so it can be fixed.

(Depending on your use case, I expect you might want to pass in the app through the Desired Capabilities of your test script, rather than in the server args)

`'/Applications/Appium 3.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --pre-launch --platform-version "8.1" --platform-name "iOS" --app "com.vr.iphone.vrnews" --show-ios-log --device-name "iPhone 6"`

**Comment by SrinivasanTarget** [comment]
Refractored in latest architecture.Hence closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close
