### ISSUE TITLE
How to locate classname,id and xpath in appium inspector for android app?

### ISSUE THREAD

**Issue by valarmathivrv** [appium/appium#5030]
1. I have launched appium inspector.
   2. I can able to get always xpath alone.
   3. How can I get id,className,Name and tagName in appium inspector.
   
![screen shot 2015-04-30 at 6 26 33 pm](https://cloud.githubusercontent.com/assets/9842215/7413346/7b85737a-ef68-11e4-8a83-0161cf6d7bb5.png)
4. I have attached the screen shot below for reference.

**Comment by imurchie** [comment]
There doesn't seem to be an `id` there (it would be `resource-id`). Class name is the last one in the xpath descriptor. In this case, `android.widget.TextView`. If you scroll up there will also be a field for `type`. This is the class name. Name is an amalgam, but you can use what is in the `content-desc`, at the top. There is no `tagName` unless you are in a webview context.

Please, in the future, direct such queries to the [discussion list](https://discuss.appium.io/).

**Comment by moizjv** [comment]
@imurchie thanks for the response :) closing it as it does not seem to be a bug.

**Comment by valarmathivrv** [comment]
@imurchie  Thanks a lot for the response.
