### ISSUE TITLE
CRITICAL: On Mac Ideviceinstaller hangs with socker connection errors intermittently,only way to recover is replug the device to USB cable.

### ISSUE THREAD

**Issue by srikanthsadhu** [appium/appium#5034]
Ideviceinstaller on mac with latest version on YOSEMITE,IOS 8.2 seems to hang and the sys log show this msg below
com.apple.usbmuxd[17630]: SCEDeviceSocketCallback 0x1006027c0-libusbmuxd/org.libimobiledevice.usbmuxd remote peer closed connection for sce 0x1006027c0.

We are stuck that we cant install our app consistently through idevice. Please fix it.

**Comment by jlipps** [comment]
appium isn't in charge of ideviceinstaller, have you contacted that project?

**Comment by srikanthsadhu** [comment]
Yes already raised  with i device.
Reason raised with appium because, appium server hangs during launch I device object not found. Hangs infinitely at that point without any logs.
Also this will be issue when u move to official install to I device without fruitstrap.
I device didnt respond since 3 weeks. Seems none  looking.
Pls help.
