### ISSUE TITLE
Automate 2 apps with appium

### ISSUE THREAD

**Issue by melonieji** [appium/appium#5035]
Hi,
   My tests require me to connect to calendar app first and then head to my internal app built by my company, as there are some changes which happen to my internal app based on the set up I do at calendar app.

I did try a couple of options with appium 1.3.7-beta but did not find any luck.
Did try working with 2 drivers and that did not result in consistent/stable solution.
Also tried launching the calendar app with bundle id which didnt work either.

Could you let me know how I could achieve this with appium please?

Here is the flow:
Start iOS Simulator/Device.
Connect to Calendar app, create some appointments and save them
Close Calendar app
Connect to internal app and perform actions.
Close internal app
Close simulator session.

Not sure how I could get 2 apps connected via appium. Any feasible solution on this would be helpful please.

Thanks and best regards,
Melonie

**Comment by jlipps** [comment]
You can't automate 2 apps in one session with iOS (this is an Apple limitation). If your changes to the calendar app persist, then you should be able to do this as follows (make sure you pass in the `noReset`: `true` capability)

1. start session with calendar app
2. run calendar flow
3. quit session
4. start session with your app
5. make verifications
6. quit session

In other words, you need to do it using 2 separate sessions.

**Comment by melonieji** [comment]
Thanks for your quick update Jon,

Not sure how I can identify calendar app using desired capabilities.I tried using the bundleId which didnt work..

**Comment by jlipps** [comment]
on a sim you should be able to launch it using the bundle id. on a real device you won't be able to automate built-in apps (since you don't own them)
