### ISSUE TITLE
Site documentation/tutorial update

### ISSUE THREAD

**Issue by SConrad-Whoop** [appium/appium#5037]
Hello,

Just wondering when the documentation for 1.3.7 is going to be updated. Currently some of it is very out of date or just completely missing, such as http://appium.io/slate/en/v1.3.7-Beta/?java#running-appium-tests3 and http://appium.io/slate/en/v1.3.7-Beta/?java#overview2

Going through the documentation and the tutorial has left me very frustrated and unable to do anything but very, very basic tests.

Also, the documentation says 1.3.7-Beta. Does that mean 1.3.7 is a beta build? I ask because 1.3.7 is what you get when you hit Download on the homepage, but nothing anywhere mentions it as being in beta.

**Comment by jlipps** [comment]
@SConrad-Whoop there are some issues with the doc publishing right now. 1.3.7 final was not able to be published. If you want the truest docs, simply navigate around https://github.com/appium/appium/tree/master/docs/en. We'll be re-publishing docs for 1.4 soon, and that should also fix the 1.3.7 issue.

In terms of your specific issues, I'm not sure where you got the links but there are extraneous numbers at the end. The correct links are:

* http://appium.io/slate/en/v1.3.7-Beta/?java#running-appium-tests
* http://appium.io/slate/en/v1.3.7-Beta/?java#overview

We're aware of various content issues with the docs and will be addressing them soon. For now, if you run into specific problems, we recommend asking others for help at the [forum](https://discuss.appium.io)
