### ISSUE TITLE
Identify calendar app using appium

### ISSUE THREAD

**Issue by melonieji** [appium/appium#5038]
Not sure how I can identify calendar app using desired capabilities.
I tried using the bundleId which didnt work for some reason. Also tried to pass the "calendar" in app desired capabilities.

is there a different way of doing this on iOS simulator and android emulator? Because I can't identify the app as mentioned above.

**Comment by jlipps** [comment]
please paste in the logs when you tried to use bundleId on ios.

**Comment by melonieji** [comment]
I get a response saying undefined.. not sure what it means

**Comment by jlipps** [comment]
> please paste in the logs when you tried to use bundleId on ios.

**Comment by Jonahss** [comment]
What bundleId did you use?

**Comment by sebv** [comment]
http://stackoverflow.com/questions/9910366/what-is-the-bundle-identifier-of-apples-default-applications-in-ios
