### ISSUE TITLE
Sometimes ideviceinstaller hangs due to a bug in libimobiledevice

### ISSUE THREAD

**Issue by srikanthsadhu** [appium/appium#5039]
Hi we used fruitstrap,I device both had issues in install.
Appium has ocassional issues in launching due to log capture on device console.
The best resolution we figured was if we restart device BTW every test run, tests and tools are stable.
Is there a way appium can support restart of IOS device?
Even using settings app is fine but settings app bundle I'd not present.
Can any one please triage this so we can effectively use appium .

**Comment by moizjv** [comment]
@srikanthsadhu so you want capability to restart iOS from appium?

**Comment by srikanthsadhu** [comment]
Yes please, I need an automated way to restart iOS device without physically touching device. Like adb restart in android.
This will fix issues with ideviceinstaller object not found from appium start, also fixes log capture didnt start in time from appium

**Comment by yaphatak** [comment]
idevicediagnostics restart
If you have appium installed on machine then  you should have idevicediagnostics along with it

**Comment by srikanthsadhu** [comment]
Thanks for reply.I will try this but wondering when I device hangs due to remote peer socket connection closed error  on appium will this work or not?
Is there a command line option to restart attached USB port? I mean mount / unmount without kernel options?

**Comment by yaphatak** [comment]
it wont work if you see lockdown error from ideviceinstaller

**Comment by srikanthsadhu** [comment]
Does any one know solution to re-plug the USB port / cable through command line?
atleast issue will be resolved when we unplug and replug the USB cable , is there a way to automate this through any mount/unmount diskutil commands?

**Comment by srikanthsadhu** [comment]
When ideviceinstaller hangs with appium, I tried idevicediagnostics restart and it didnt reset the socketconnection after restart.

**Comment by Jonahss** [comment]
Hm. You can buy an expensive USB hub that allows you to programmatically connect/disconnect the cables attached to it....

OH!
Does ideviceinstaller hang for you? And then you unplug the phone and plug it back in and it works? I have actually been experiencing this but thought it was only my computer.

what do you see when you run `idevice_id -l`? Mine has the same Id twice :/

**Comment by Jonahss** [comment]
@srikanthsadhu can you answer my questions above?
 
Does ideviceinstaller hang for you? And then you unplug the phone and plug it back in and it works? I have actually been experiencing this but thought it was only my computer.

what do you see when you run idevice_id -l? Mine has the same Id twice :/

**Comment by srikanthsadhu** [comment]
Same with me, I see the same ID twice when it hangs where as when it works it was only once.
Do we know what does this imply?
Sys logs show an error like this when we do ideviceinstaller -l : 
com.apple.usbmuxd[54]: SCEDeviceSocketCallback 0x100625cd0-libusbmuxd/org.libimobiledevice.usbmuxd remote peer closed connection for sce 0x100625cd0.

This could be because of socket connections being closed intermittently from ipad ?

**Comment by srikanthsadhu** [comment]
this seemed to be a known issue with libusbmuxd and they are hoping to release in 1.4.0 , till then work around would be , with in itunes turnoff Synch ipad through wifi in iTunes and restart the ipad. this should be resolved temporarily till new relaease comes out OR fix the code and rebuild the libs.

**Comment by Jonahss** [comment]
Thanks for doing the research on that. Waiting on the fix.

**Comment by srikanthsadhu** [comment]
FYI there is a patch fix available with libimobile but not in any release , google for this patch fix and apply to existing libusbmuxd, I can consistently run Appium without any issue related to idevice now.

**Comment by Jonahss** [comment]
@srikanthsadhu awesome! Could you post a link to the patch?

**Comment by srikanthsadhu** [comment]
@Jonahss  I can send you privately, send me an email from your email address please.

**Comment by Jonahss** [comment]
@srikanthsadhu thanks. You can email me at jonahss@saucelabs.com

**Comment by felyppers** [comment]
3 years later and I found this same issue, even after upgrading libimobiledevice to HEAD. Any news on this? My device appears twice in "idevice_id -l", gets stuck with "ideviceinstaller" and works OK if I unplug and plug, but not if I restart.
