### ISSUE TITLE
Instruments crashes on startup

### ISSUE THREAD

**Issue by tfcardoso** [appium/appium#5041]
appium 1.3.7

Can anyone merge this with https://github.com/appium/appium/issues/4126 or just close this one and re-open other?

It installs the app in real device and then cannot lunch it.

This is the command where it fails:

    /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 39bcf05aabb1bddf783b79d452cca052b32e2f2f com.xxx.joynenter -e UIASCRIPT "/Users/wcs_mac/Library/Application Support/appium/bootstrap/bootstrap-c5bdf70fd65223c0.js" -e UIARESULTSPATH /tmp/appium-instruments
And the response error is:

    instruments[54794:4b1f] WebKit Threading Violation - initial use of WebKit from a secondary thread.
    Instruments Trace Error : Target failed to run: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 3.) : Failed to launch process with bundle identifier 'com.xxx.joynenter'

**Comment by Jonahss** [comment]
Is the app `com.xxx.joynenter` already installed to the device?
You can use [ideviceinstaller](https://github.com/libimobiledevice/ideviceinstaller) to get a list of the exact bundleIds for apps on the phone.

**Comment by tfcardoso** [comment]
It is correctly installed with ideviceinstaller during the launching of tests.

**Comment by Jonahss** [comment]
It is correctly installed, but Instruments always fails with that error?
Can you verify that the bundleIds listed when running `ideviceinstaller -l` exactly match "com.xxx.joynenter"?

**Comment by tfcardoso** [comment]
Hi, sorry for late reply. The result of that command is:

    mac$ ideviceinstaller -l
    Total: 2 apps
    com.swiftkey.SwiftKeyApp - SwiftKey 124.3.5772003
    com.xxx.joynenter - RCS+ 3.0.0
    mac$ 

In the meantime I updated my system, its running now:
XCode6.3 (10.10)
Device: ios8.3
Appium 1.4.0

But same exact error appears

**Comment by tfcardoso** [comment]
Apparently it was related to this:
http://stackoverflow.com/questions/19112794/xcode-could-not-launch-only-reports-security-as-error

Fixed now :) thanks for support

**Comment by Jonahss** [comment]
Thanks for posting solution :)

**Comment by ChethanGKC** [comment]
Hi @tfcardoso @Jonahss, 

Still i am facing the same issue.. 

Using below env.
Appium - 1.4.3
xcode - 7.3.1

I am unable to launch the Inspector, getting below error:

`info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 3.) : Failed to launch process with bundle identifier 'com.xxxx.platform.referenceapp'

info: [debug] [INSTSERVER] Instruments exited with code 253

info: [debug] Killall instruments

info: [debug] Instruments crashed on startup
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator

info: [debug] On a real device; cannot clean device state

info: [debug] Cleaning up appium session

error: Failed to start an Appium session, err was: Error: Instruments crashed on startup

info: [debug] Error: Instruments crashed on startup
    at [object Object].Instruments.onInstrumentsExit (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/lib/instruments.js:440:31)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/lib/instruments.js:353:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments crashed on startup)","origValue":"Instruments crashed on startup"},"sessionId":null}

undefined`

I have tried all the above solutions still, i am not able to resolve this issue can some please hep me on this.
