### ISSUE TITLE
Android sendKeys() doesn't work properly when text exists in text field

### ISSUE THREAD

**Issue by robert-langenfeld** [appium/appium#5042]
When attempting to send text over to an android webelement, it will work fine when the text field is empty. However when I attempt to send that same text when the text field has a value already in it, it does add it to the end of the line. Instead, it will place the cursor a couple characters in, attempt to delete them and then set the text. 

For example when I send the text "test" on a an empty text field it works fine. However when I send the word "test" again the value in the text field becomes "testst".

Here is the code I'm using:

```Java
WebElement element = getDriver().findElement(By.xpath(path));
if (element != null) {
     element.sendKeys("test");
}
```

Is this issue related to https://github.com/appium/appium/issues/4981 at all? Or is there something else going on? We want to be able to be able to clearText() but also have tests were we continue to add text to the text field.

Logs:

info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"7","text":"test","replace":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"7","text":"test","replace":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: setText
info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().

**Comment by moizjv** [comment]
related to #4981 will add reference and close this.
