### ISSUE TITLE
two-factor authentication for owners/contributors

### ISSUE THREAD

**Issue by jlipps** [appium/appium#5043]
We need turn on 2FA to make sure the security of the Appium org is in a good spot. Please do this for each of your accounts and report back here when done. If you have any concerns, let me know!

- [ ] @appium-ci (@sebv responsible)
- [x] @triager (@jlipps responsible)
- [x] @Astro03 
- [x] @ddkjin
- [x] @drpy 
- [x] @maudineormsby 
- [x] @paymand 
- [x] @peepa 
- [x] @penguinho 
- [x] @sbonebrake
- [x] @tarunsujit 
- [ ] @Zarkonnen

**Comment by sbonebrake** [comment]
done

**Comment by ddkjin** [comment]
done

**Comment by maudineormsby** [comment]
done

**Comment by penguinho** [comment]
done

**Comment by imurchie** [comment]
Pinging @appium-ci (@sebv responsible), @triager (@jlipps responsible) @drpy, @peepa, @tarunsujit, @Zarkonnen about 2-factor authentication.

**Comment by triager** [comment]
triager done

**Comment by peepa** [comment]
Done

**Comment by drpy** [comment]
done
