### ISSUE TITLE
Get GPS location on Android

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5047]
appium apparently supports setting the GPS location on Android however not getting it. appium should allow [getting the current location](https://github.com/appium/ruby_lib/pull/333).

**Comment by jlipps** [comment]
is there a way for the Bootstrap.jar to use the Android location methods so we can return this back to the user?

**Comment by bootstraponline** [comment]
I'm pretty sure we need to use the "buddy apk" approach the Espresso devs outlined to get this information since we need an instrumentation context (this is similar to how we're implementing unlock).

**Comment by dduphorn** [comment]
With this Enhancement, will be able to get current gps status?  Enabled/Disabled?  Or is there another way to get this information?  Thanks

**Comment by mykola-mokhnach** [comment]
Implemented in appium@beta

**Comment by antovrv** [comment]
@mykola-mokhnach 
I've updated the appium version to 1.9.2-beta.2. I'm getting the following error while getting the location using the driver.

**LOG:**
> org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot parse the actual location values from the command output: Broadcasting: Intent { act=io.appium.settings.location flg=0x400000 cmp=io.appium.settings/.receivers.LocationInfoReceiver }
> Broadcast completed: result=0, data=""

Updated the same in appium forum too.
https://discuss.appium.io/t/appium-1-9-1-issues-setting-location-on-android-device/23955/7
