### ISSUE TITLE
Set GPS on physical android device results in unhelpful message

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5048]
```
d = driver.driver
d.extend Selenium::WebDriver::DriverExtensions::HasLocation
d.set_location(1,2,3)
Selenium::WebDriver::Error::UnknownError: ERROR running Appium command: port should be a number or string: false
```

It'd be better to tell the user that set location requires an emulator and isn't supported on physical devices.

**Comment by jlipps** [comment]
I agree

**Comment by d9kgit** [comment]
I have:

ERROR running Appium command: port should be > 0 and < 65536: 0

**Comment by clample** [comment]
set location is now also supported on real Android devices: https://github.com/appium/appium/issues/3259

I think that this issue can be closed.
