### ISSUE TITLE
Page source is completely different between ios 8 and 7

### ISSUE THREAD

**Issue by aluedeke** [appium/appium#5052]
I am currently testing a app on ios7 and ios8 real devices.

To do that i am using a lot of xpath call. Fortunately the html source looks completely different.

I think the reason is:

https://github.com/appium/appium/blob/81b90b599f8f1e0a5c7c39e7fb93f0314be0b328/lib/devices/ios/ios-controller.js#L259

Did anyone ever investigate if it is possible to return same source for all platforms? 

Example:
On iOS 8 i usually get 3 UIAStaticText entries with 3 different values
```
<UIAStaticText name="1">
<UIAStaticText name="2">
<UIAStaticText name="3">
```

in iOS 7 we get one UIAStaticText containing 3 comma seperated values:
```
<UIAStaticText name="1, 2, 3">
```

**Comment by amedvedjev** [comment]
we have same problem. xcode backward compatibility i guess is problem. when we build client with Old xcode the problem absent. when moved to 8 we start see problems in 7.

**Comment by jlipps** [comment]
this is a known issue (that the source changes between ios releases); there's nothing we can do about it as Apple changed the internal representation we use.

but it's odd that it would be different for ios 7.1 on xcode 5 and ios 7.1 on xcode 6. is that what you're saying @amedvedjev?

**Comment by amedvedjev** [comment]
example of our problem:
 - some cell element has 2 text items. each text item has unique Accessibility Id. Cell itself also has Id.
When we build this with previous xcode we saw this correctly. 
When we build with latest xcode with target device 8.3 Simulator we see this correctly only with 8.X Simulator. With 7.1 Simulator we see only Cell with text value equal to both text items.

Thus we can not find each test item inside cell directly but need now compare text inside cell that it contains some text.

All our hopes are when 7.1 share reduce to 10% and we remove it from support. According to our dev we have also quite much pain remain supporting 7.1 (to many IF-s in code :-- )

**Comment by Jonahss** [comment]
Sorry we can't do more to help, this is Apple changing their implementation (hopefully they're improvements ;)
