### ISSUE TITLE
How to use locators in  the test cases?

### ISSUE THREAD

**Issue by valarmathivrv** [appium/appium#5053]
1. I have furnished the full details regarding the locator elements, which I have acquired from the appium inspector for android app.

2. I used text "CATEGORIES" as name and type "android.widget.TextView" as className and xpath="/android.widget.TextView[1]" in my test cases.

3. These are the possibilities I have tried it. But, the click action doesn't happens for me.

4. How can I use the locator to click the particular element? 

5. How can I identify the unique locator element in the appium inspector?

Details:
content-desc: 
type: android.widget.TextView
text: CATEGORIES
index: 0
enabled: true
visible: false
location: {0, 77}
size: {406, 42}
checkable: false
checked: false
focusable: false
long-clickable: false
package: com.vr.droid.qa
password: false
resource-id: com.vr.droid.qa:id/side_menu_top_title_text
scrollable: false
selected: false
xpath: //android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.support.v4.widget.SlidingPaneLayout[1]/android.widget.RelativeLayout[1]/android.widget.RelativeLayout[1]/android.support.v4.view.ViewPager[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.RelativeLayout[1]/android.widget.TextView[1]

**Comment by amedvedjev** [comment]
Java:
driver.tap(1,driver.findElement(MobileBy.id("com.vr.droid.qa:id/side_menu_top_title_text")),200)
or
driver.findElement(MobileBy.id("com.vr.droid.qa:id/side_menu_top_title_text")).click();

**Comment by valarmathivrv** [comment]
@amedvedjev , I have tried with the above solution. But, the click action doesn't occur. I am using java only.

**Comment by amedvedjev** [comment]
well can't help more you need investigate yourself.
enable on phone or emulator in developer options to show location of cursor = thus you will see where and when the tap happening.

**Comment by valarmathivrv** [comment]
@amedvedjev , ok thanks for your response. I will give try.

**Comment by moizjv** [comment]
@valarmathivrv can you use [forum] (http://discuss.appium.com) for discussions. Does not seem to be an appium defect.
