### ISSUE TITLE
iOS, webdriver expect_id return True for invisible elements   

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#5055]
I am using appium with python client to write automation for an application iOS (target devices are iPhone 5c). 
Issue:  Current implementation returns True even if item is  element is invisible.
I want expect_id to search the target id in from visible elements only.

Do we have any workaround for this ?

**Comment by amedvedjev** [comment]
please post here your element from driver.getPageSource() to see what is there.

**Comment by Jonahss** [comment]
You can use isEnabled() or isDisplayed() to check if the element is enabled or displayed.

**Comment by naveenjammula** [comment]
It works with isDisplayed() thanx
