### ISSUE TITLE
wrong location value in page source

### ISSUE THREAD

**Issue by vascon8** [appium/appium#5056]
i have a tool bar on top of phone screen, and the location value is x=0,y=44. i can get the correct location value of the tool bar and its subviews, but after i use the scroll to method, the location value are wrong.
appum v1.3.7

some of the page source result:
            <UIAScrollView name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0" x="0" y="0" width="320" height="568">
                <UIAWebView name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0" x="0" y="0" width="320" height="4025">
                    <UIALink name="↻, 刷新" label="↻, 刷新" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="刷新" path="/0/0/0/0/0" x="283" y="8" width="28" height="28">
                        <UIAStaticText name="↻" label="↻" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="刷新" path="/0/0/0/0/0/0" x="283" y="8" width="28" height="28">
                        </UIAStaticText>
                    </UIALink>
                    <UIALink name="D, 搜索" label="D, 搜索" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="搜索" path="/0/0/0/0/1" x="237" y="8" width="28" height="28">
                        <UIAStaticText name="D" label="D" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="搜索" path="/0/0/0/0/1/0" x="237" y="8" width="28" height="28">
                        </UIAStaticText>
                    </UIALink>
                    <UIALink name="G, 写微博" label="G, 写微博" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="写微博" path="/0/0/0/0/2" x="191" y="8" width="28" height="28">
                        <UIAStaticText name="G" label="G" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="写微博" path="/0/0/0/0/2/0" x="191" y="8" width="28" height="28">
                        </UIAStaticText>
                    </UIALink>
                    <UIAStaticText name="testq_lx" label="testq_lx" value="" dom="[object Object]" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/3" x="13" y="10" width="63" height="22">
                    </UIAStaticText>
                    <UIAStaticText name="e" label="e" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/4" x="78" y="15" width="11" height="13">
                    </UIAStaticText>
                    <UIALink name="首页" label="首页" value="" dom="[object Object]" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/5" x="0" y="44" width="80" height="40">
                    </UIALink>
                    <UIALink name="14 消息" label="14 消息" value="" dom="[object Object]" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/6" x="80" y="44" width="82" height="40">
                    </UIALink>
                    <UIALink name="发现" label="发现" value="" dom="[object Object]" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/7" x="186" y="55" width="28" height="18">
                        <UIAStaticText name="发现" label="发现" value="" dom="[object Object]" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/7/0" x="186" y="55" width="28" height="18">
                        </UIAStaticText>
                    </UIALink>
...
after scroll to:
            <UIAScrollView name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0" x="0" y="0" width="320" height="568">
                <UIAWebView name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0" x="0" y="-380" width="320" height="4025">
                    <UIALink name="↻, 刷新" label="↻, 刷新" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="刷新" path="/0/0/0/0/0" x="283" y="-372" width="28" height="28">
                        <UIAStaticText name="↻, 刷新" label="↻, 刷新" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="刷新" path="/0/0/0/0/0/0" x="283" y="-372" width="28" height="28">
                        </UIAStaticText>
                    </UIALink>
                    <UIALink name="D, 搜索" label="D, 搜索" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="搜索" path="/0/0/0/0/1" x="237" y="-372" width="28" height="28">
                        <UIAStaticText name="D, 搜索" label="D, 搜索" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="搜索" path="/0/0/0/0/1/0" x="237" y="-372" width="28" height="28">
                        </UIAStaticText>
                    </UIALink>
                    <UIALink name="G, 写微博" label="G, 写微博" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="写微博" path="/0/0/0/0/2" x="191" y="-372" width="28" height="28">
                        <UIAStaticText name="G, 写微博" label="G, 写微博" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="写微博" path="/0/0/0/0/2/0" x="191" y="-372" width="28" height="28">
                        </UIAStaticText>
                    </UIALink>
                    <UIAStaticText name="testq_lx" label="testq_lx" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/3" x="13" y="-370" width="63" height="22">
                    </UIAStaticText>
                    <UIAStaticText name="e" label="e" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/4" x="78" y="-365" width="11" height="13">
                    </UIAStaticText>
                    <UIALink name="首页" label="首页" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/5" x="0" y="-336" width="80" height="40">
                    </UIALink>
                    <UIALink name="14 消息" label="14 消息" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/6" x="80" y="-336" width="82" height="40">
                    </UIALink>
                    <UIALink name="发现" label="发现" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/7" x="186" y="-325" width="28" height="18">
                        <UIAStaticText name="发现" label="发现" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/7/0" x="186" y="-325" width="28" height="18">
                        </UIAStaticText>
                    </UIALink>
                    <UIALink name="1 我" labe

**Comment by vascon8** [comment]
<UIAScrollView name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0" x="0" y="0" width="320" height="568">
                <UIAWebView name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0" x="0" y="-380" width="320" height="4025">
                    <UIALink name="↻, 刷新" label="↻, 刷新" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="刷新" path="/0/0/0/0/0" x="283" y="-372" width="28" height="28">
                        <UIAStaticText name="↻, 刷新" label="↻, 刷新" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="刷新" path="/0/0/0/0/0/0" x="283" y="-372" width="28" height="28">
                        </UIAStaticText>
                    </UIALink>
                    <UIALink name="D, 搜索" label="D, 搜索" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="搜索" path="/0/0/0/0/1" x="237" y="-372" width="28" height="28">
                        <UIAStaticText name="D, 搜索" label="D, 搜索" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="搜索" path="/0/0/0/0/1/0" x="237" y="-372" width="28" height="28">
                        </UIAStaticText>
                    </UIALink>
                    <UIALink name="G, 写微博" label="G, 写微博" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="写微博" path="/0/0/0/0/2" x="191" y="-372" width="28" height="28">
                        <UIAStaticText name="G, 写微博" label="G, 写微博" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="写微博" path="/0/0/0/0/2/0" x="191" y="-372" width="28" height="28">
                        </UIAStaticText>
                    </UIALink>
                    <UIAStaticText name="testq_lx" label="testq_lx" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/3" x="13" y="-370" width="63" height="22">
                    </UIAStaticText>
                    <UIAStaticText name="e" label="e" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/4" x="78" y="-365" width="11" height="13">
                    </UIAStaticText>
                    <UIALink name="首页" label="首页" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/5" x="0" y="-336" width="80" height="40">
                    </UIALink>
                    <UIALink name="14 消息" label="14 消息" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/6" x="80" y="-336" width="82" height="40">
                    </UIALink>
                    <UIALink name="发现" label="发现" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/7" x="186" y="-325" width="28" height="18">
                        <UIAStaticText name="发现" label="发现" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/7/0" x="186" y="-325" width="28" height="18">
                        </UIAStaticText>
                    </UIALink>
                    <UIALink name="1 我" labe

**Comment by vascon8** [comment]
<UIALink name="↻, 刷新" label="↻, 刷新" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="刷新" path="/0/0/0/0/0" x="283" y="8" width="28" height="28">
                        <UIAStaticText name="↻" label="↻" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="刷新" path="/0/0/0/0/0/0" x="283" y="8" width="28" height="28">
                        </UIAStaticText>
                    </UIALink>
                    <UIALink name="D, 搜索" label="D, 搜索" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="搜索" path="/0/0/0/0/1" x="237" y="8" width="28" height="28">
                        <UIAStaticText name="D" label="D" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="搜索" path="/0/0/0/0/1/0" x="237" y="8" width="28" height="28">
                        </UIAStaticText>
                    </UIALink>
                    <UIALink name="G, 写微博" label="G, 写微博" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="写微博" path="/0/0/0/0/2" x="191" y="8" width="28" height="28">
                        <UIAStaticText name="G" label="G" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="写微博" path="/0/0/0/0/2/0" x="191" y="8" width="28" height="28">
                        </UIAStaticText>
                    </UIALink>
                    <UIAStaticText name="testq_lx" label="testq_lx" value="" dom="[object Object]" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/3" x="13" y="10" width="63" height="22">
                    </UIAStaticText>
                    <UIAStaticText name="e" label="e" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/4" x="78" y="15" width="11" height="13">
                    </UIAStaticText>
                    <UIALink name="首页" label="首页" value="" dom="[object Object]" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/5" x="0" y="44" width="80" height="40">
                    </UIALink>
                    <UIALink name="14 消息" label="14 消息" value="" dom="[object Object]" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/6" x="80" y="44" width="82" height="40">
                    </UIALink>
                    <UIALink name="发现" label="发现" value="" dom="[object Object]" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/7" x="186" y="55" width="28" height="18">
                        <UIAStaticText name="发现" label="发现" value="" dom="[object Object]" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/7/0" x="186" y="55" width="28" height="18">
                        </UIAStaticText>

**Comment by vascon8** [comment]
the tool bar was loated on the location x=0 y=44
<UIALink name="首页" label="首页" value="" dom="[object Object]" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/5" x="0" y="44" width="80" height="40">
after scroll to:
<UIALink name="首页" label="首页" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/5" x="0" y="-336" width="80" height="40">

**Comment by vascon8** [comment]
the tool bar was fixed at the location x=0 y=44
<UIALink name="首页" label="首页" value="" dom="[object Object]" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/5" x="0" y="44" width="80" height="40">
after scroll to:
<UIALink name="首页" label="首页" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/5" x="0" y="-336" width="80" height="40">

**Comment by vascon8** [comment]
the bar was fixed at the location of x=0 y=44
<UIALink name="首页" label="首页" value="" dom="[object Object]" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/5" x="0" y="44" width="80" height="40">
after scroll to:
<UIALink name="首页" label="首页" value="" dom="[object Object]" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/5" x="0" y="-336" width="80" height="40">

**Comment by Jonahss** [comment]
Whoah.
This on iOS right?
It looks like `position:fixed` has a lot of issues. Seems like this is a bug with iOS.

**Comment by Jonahss** [comment]
I suggest that you save the location of the element before scrolling, then you can still create a TouchAction on those coordinates.

**Comment by Jonahss** [comment]
Forgot to ask: is this on Safari, or a native app?

**Comment by vascon8** [comment]
web_view

**Comment by sebv** [comment]
Moving to bug, not sure if there is anything we can do though.
