### ISSUE TITLE
When Appium Android Node runs more than 50 tests , tests are skipped

### ISSUE THREAD

**Issue by ArchanaChalapalle** [appium/appium#5059]
When more than 50 tests are run continuously in a test suite , some tests are skipped. 
All of a sudden , this error appears in betweeen the runs
org.openqa.selenium.SessionNotCreatedException:
 A new session could not be created. (Original error: Did not get session redirect from Chromedriver) (WARNING: The server did not provide any stacktrace information)

**Comment by amedvedjev** [comment]
1) does it fail on "driver = new RemoteWebDriver(new URL("http://127.0.0.1:port/wd/hub"), some_capabilities);" ?
2) if YES - add retries here.

**Comment by ArchanaChalapalle** [comment]
Can you share the logic of how you add retries here ?

**Comment by amedvedjev** [comment]
google: "testNG retry failed tests"
solutions many e.g. example from search https://martinholladay.wordpress.com/2013/11/17/webdriver-2-0-automatically-retry-failed-tests/

**Comment by Jonahss** [comment]
I'll try to reproduce this myself. Should running 50 simple chrome tests on an android emulator do it, or are you using a real device?

**Comment by jlipps** [comment]
ultimately the solution will probably be to retry. the only question is whether this should be on the client side or on the appium side.

**Comment by ArchanaChalapalle** [comment]
It is on real device that I am getting this error.

**Comment by Jonahss** [comment]
What type of device is it, and what version of Android is it running?

**Comment by ArchanaChalapalle** [comment]
It runs on Samsung s5 and Samsung s3 . In both the devices I had same issue. In between tests , tests are skipped at line getRemotewebdriver .

-------- Original message --------

**Comment by yaphatak** [comment]
@jlipps : Its chromedriver issue. We run more than 3000  tests everyday and but we dont see failures anymore. Only code change that I did, i dont kill chromedriver per test session, we restart it only if we see failure during new session creation. Again I will try to send pull request soon but i have implementation with earlier chromdriver code (where you didnt seprate chromriver package in separate module)
Note:internalChromeDriver.js is kinda of static 

Chromedriver.prototype.proxyNewSession = function (data, cb) {
  var maxRetries = 3;
  var curRetry = 0;
  var retryInt = 500;
  var doProxy = function (alreadyRestarted) {
    this.proxyTo('/wd/hub/session', 'POST', data, function (err, res, body) {
      if (err) {
	  logger.info("Error after posting to chromedriver" + err);
        if (/ECONNREFUSED/.test(err.message) && curRetry < maxRetries) {
          logger.info("Could not connect yet; retrying in ECONNREFUSED");
          internalChromeDriver.start(this.chromedriver, this.proxyPort, function(){	
                curRetry++;
                setTimeout(doProxy, retryInt);
            }.bind(this));
            return;
        } else if (/ECONNRESET/.test(err.message) && curRetry < maxRetries) {
            logger.info("Could not connect yet; retrying ECONNRESET");
			internalChromeDriver.start(this.chromedriver, this.proxyPort, function(){	
                curRetry++;
                setTimeout(doProxy, retryInt);
            }.bind(this));
            return;
        }
        return cb(err);
      }

      // first checking if we get a well formed success response
      this.chromeSessionId = null;
      try {
        if (body.status === 0 && body.sessionId) {
          logger.info("Successfully started chrome session");
          this.chromeSessionId = body.sessionId;
        }
      } catch (ignore) {}
      if (this.chromeSessionId) return cb(null, this.chromeSessionId);

      // then check redirect success case
      try {
        if (res.statusCode === 303 && res.headers.location) {
          logger.info("Successfully started chrome session");
          var loc = res.headers.location;
          this.chromeSessionId = /\/([^\/]+)$/.exec(loc)[1];
        }
      } catch (ignore) {}
      if (this.chromeSessionId) return cb(null, this.chromeSessionId);

      // those are error cases
	  if (typeof body !== "undefined" &&
                 typeof body.value !== "undefined" &&
                 typeof body.value.message !== "undefined" &&
				 body.value.message.indexOf("Adb command timed out") !== -1){
		 logger.info("Rebooting Device");	
		 this.adb.exec("reboot", function (err, stdout) {
			if (err) 
			logger.error("Device rebooting failed."); 
		 });			 
         cb(new Error(body.value.message));	 
	  }
      else if (typeof body !== "undefined" &&
                 typeof body.value !== "undefined" &&
					typeof body.value.message !== "undefined") {
          logger.error("Chromedriver had trouble " + body.value.message);
          logger.error("Restarting chromedriver");
          internalChromeDriver.start(this.Chromedriver, this.proxyPort, function () {
              curRetry++;
              setTimeout(doProxy, retryInt);                
          }.bind(this));
      }
	  else {
        logger.error("Chromedriver create session did not work. Status was " +
                     res.statusCode + " and body was " +
                     JSON.stringify(body));
           this.killOldChromedrivers(function () {
               cb(new Error("Did not get session redirect from Chromedriver"));
          }.bind(this));
      }
    }.bind(this));
  }.bind(this);

  doProxy();
};

Chromedriver.prototype.deleteSession = function (cb) {
  logger.debug("Deleting Chrome session");
  var url = '/wd/hub/session/' + this.chromeSessionId;
  this.proxyTo(url, 'DELETE', null, function (err, res) {
    if (err) return cb(err);
    if (res.statusCode !== 200) return cb(new Error("Status was not 200"));
    cb();
  }.bind(this));
};

Chromedriver.prototype.stop = function (cb) {
  logger.debug('Killing chromedriver');
  this.exitCb = cb;
 // this.proc.kill();
	// if (this.exitCb !== null) {
      // return this.exitCb();
    // }
	this.deleteSession(function(){
		this.onDie();
		if (this.exitCb !== null) {
			return this.exitCb();
		}
	}.bind(this));
   // this.onDie();
};

**Comment by Jonahss** [comment]
We've been using this script to run chromedriver, it restarts it on failures.
https://github.com/appium/appium/blob/master/bin/ios-webkit-debug-proxy-launcher.js

**Comment by yaphatak** [comment]
isnt thisfor ios-webit-debug-proxy

**Comment by Jonahss** [comment]
Oh whoops, sorry about that. Sometimes my head gets stuck in iOS mode.

So the solution should be to add retry logic to Chromedriver and reset it when things fail?

**Comment by ArchanaChalapalle** [comment]
Ok. Thank you. Will give it a try.

**Comment by sebv** [comment]
So looks like we need to add some retry logic to appium code when chromedriver is crashing.
