### ISSUE TITLE
Touch actions with Real Device on Safari

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#5060]
It turns out that Instruments _does_ continue to run while the SafariLauncher is backgrounded and Safari is running.
Switching to the NATIVE context, one can still get the page source, find elements, tap screen coordinates, but **CANNOT** tap elements. Tapping an element causes instruments to hang, appium eventually quits and never returns a response (so the whole test suite is frozen).

Short-term solution: throw "command not implemented" on "element.tap" on real device safari tests.

Long-term solution: possibly remap "element.tap" to get the element coordinates and tap those coordinates when running a real device safari test.

@jlipps

**Comment by Nesaganesh** [comment]
Did you find any solution on this, I am also facing the same issue on 

Appium 1.4.13
Selenium webdriver 2.48.2

appium_dotnet_driver 1.3
