### ISSUE TITLE
Android. WebElement text is 0

### ISSUE THREAD

**Issue by glebPrischepa** [appium/appium#5066]
Hi, all,

I noticed one issue on Android while developing tests using Appium.
The problem is I am trying to get text from WebElement and I am getting empty text.

On Android WebElement is
 <EditText               
                android:layout_width="match_parent"
                android:layout_height="wrap_content"             
                android:inputType="numberPassword"
            />

So. I see that EditText has got 4 digits as dots but WebElement.getText().length() returns 0.

Everything works if
 <EditText               
                android:layout_width="match_parent"
                android:layout_height="wrap_content"             
                android:inputType="number"
            />
without "password".

I guess "password" causes this issue.

Does it make sense?
Any ideas or workarounds?

Thanks in advance

**Comment by Jonahss** [comment]
That's interesting. Sounds like a security feature, no?
Why are you trying to get the text out of a password field?

Is this in a webview, or a native app?

**Comment by glebPrischepa** [comment]
It happens in native app.
The reason why I am trying is to check that my logic replaces text in WebElement(EditText) correctly.
I am developing test that allows to examine that invalid user cannot be signed in and I have to replace text several times.

To clear text in input I use loop and action
getDriver().sendKeyEvent(AndroidKeyCode.BACKSPACE);

but before I should know length of the text...but in my case length is 0.

Get it?

**Comment by Jonahss** [comment]
Oh I get it!
Look here: https://discuss.appium.io/t/how-to-clear-prefilled-text-of-a-textbox-in-mac/406/4

You can call `clear()` to remove all text, or you can call `setValue()` instead of `sendKeys()` and it will overwrite the textfield and you don't need to loop to erase :)

**Comment by glebPrischepa** [comment]
Hm..."setValue" is not available for WebElement.
Also I noticed that "clear" and "sendKeys" are not stable when we use it more than 2 or 3 times.
It makes EditText does some strange things.

**Comment by glebPrischepa** [comment]
Also, "clear" does not work for EditText with inputType "password"

**Comment by Jonahss** [comment]
Wow that sounds like a whole host of issues.
Hm, ah well. It seems like a lot of the limitations come from this being a "password" input.
You could go back to the Backspace loop you had before. But you *know* the length of the previous password you typed into it, so you should know the length already.

**Comment by glebPrischepa** [comment]
Hm,,,I think I can create custom element extends WebElement to keep text but I would not rely on it much.

Any ideas?

**Comment by Jonahss** [comment]
Not being able to get the length or text inside of a Password textField is a security feature that prevent malicious javascript from getting your users' passwords, so I think removing that functionality wouldn't be productive.

Why not keep track of the length of the string you typed into the text field, then backspace that many times.

**Comment by glebPrischepa** [comment]
your idea to press backspace several times is good but I have to keep text
or length of the text somewhere.

2015-05-11 20:53 GMT+03:00 Jonah <notifications@github.com>:

**Comment by Jonahss** [comment]
Yeah, you can keep the text or length within your test suite.
