### ISSUE TITLE
Uninstalling Appium

### ISSUE THREAD

**Issue by prashantnagrecha** [appium/appium#5072]
Hi, I need steps in detail that can uninstall appium, node, etc related to Appium. Once uninstalled, I want to re-install everything from scratch. Does anyone have detailed steps for Mac.

**Comment by amedvedjev** [comment]
how you install Appium? What is your OS?

**Comment by prashantnagrecha** [comment]
Installed Appium via brew through terminal and via download for GUI version. I observed that by installing 2 different version of appium creates ambiguity when I initiate Appium through Java. #5033 so thought to uninstall and reinstall everything.

**Comment by amedvedjev** [comment]
well i guess in that case should be enough:
 - npm remove -g Appium
 - and delete Appium from Application

**Comment by Jonahss** [comment]
Can further discussion be moved to a post on discuss.appium.io ? Would be a good place to write a guide on uninstalling.

**Comment by prashantnagrecha** [comment]
Sure.
