### ISSUE TITLE
Unable to Invoke Software Keypad in iOS.

### ISSUE THREAD

**Issue by ajit4848** [appium/appium#5075]
Unable to Invoke Software Keypad in iOS.
As I need to to Toggle soft Keyboard on each time of each execution as if I need sendKeys work properly.

Is there any code snippet to get task done.

Please Help.
Thanks,
Ajit Jadhav.

**Comment by Jonahss** [comment]
I'm not sure I quite understand.
Unless you have a specific bug, try posting to the forum: http://discuss.appium.io
