### ISSUE TITLE
The way Appium install apk changes the behavior of the app

### ISSUE THREAD

**Issue by hungl** [appium/appium#5076]
Hi,

Lately, I have the same issue with https://github.com/appium/appium/issues/3782
My app does not behave the same way (crashes) when it is installed via Appium.
I wonder if anyone experience the same issue and have any solution. I would like to understand the way Appium pushing apk, and why it is different from the normal installing process.

Thanks.

**Comment by Jonahss** [comment]
https://discuss.appium.io/t/can-we-override-appiums-installing-apk-method/4193/8

I commented on your post, thanks for linking it.

**Comment by Jonahss** [comment]
If there's any more help I can give about the way Appium installs app, just comment here :)

**Comment by hungl** [comment]
I fixed my issue. See my comment in https://discuss.appium.io/t/can-we-override-appiums-installing-apk-method/4193/8

**Comment by johnwanggithub** [comment]
@hungl on which version did you fix the issue? thanks
