### ISSUE TITLE
Unlock.apk broken/unreliable on Android api level 21, 22

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#5080]

**Comment by Simon-Kaz** [comment]
Can confirm that this is an issue... I (temporarily) resolved it by removing the screen lock on the device, haven't seen the issue since but I understand that this might not be a long term solution.

**Comment by jlipps** [comment]
i've also noticed for myself that adb itself with the most recent rev of the platform-tools is really, really unreliable

**Comment by brbrr** [comment]
Have same issue but for 4.4.2 (samsung). Even removed screen lock did not help. After I've restart device - everything works ok. my logs are in #4470

**Comment by Leo38** [comment]
Seems to be fixed with rodrigomunoz fork : https://github.com/rodrigomunoz/unlock_apk

**Comment by Jonahss** [comment]
This commit? https://github.com/rodrigomunoz/unlock_apk/commit/8372ef71852a08ea19101fdea8b9ea5e2067d119

We can cherry-pick that into our unlock app if it works better.

**Comment by Jonahss** [comment]
I tried that branch just now and it causes my emulator to freeze and adb stops responding. It unlocks fine, but then won't end a session.

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium-android-driver/pull/149

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/unlock_apk/pull/5

**Comment by SrinivasanTarget** [comment]
It works fine in new release after the above fixes.Closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close
