### ISSUE TITLE
[Android API >=19][Appium 1.3.7] Wrong result when using getText() for EditText control

### ISSUE THREAD

**Issue by vietnq254** [appium/appium#5083]
With API 19 or higher, when I get the text of EditText, it will automatically add the hidden value in the result.
For example:
expected: ```example@gmail.com```
actual: ```Enter an email address. example@gmail.com```

The hidden text of EditText control is ```Enter an email address```

**Comment by Jonahss** [comment]
If you look at the actual device/emulator, does the EditText element just contain `example@gmail.com`?

**Comment by vietnq254** [comment]
In the real device Samsung Galaxy S5 (API19), I see just '''example@gmail.com'''
But Appium and UI Automator Viewer show '''Enter an email address. example@gmail.com'''

**Comment by Jonahss** [comment]
Ok, sounds like a bug.
@bootstraponline have you encountered this before? 

We get the text of an EditText just by calling the `getText()` UiAutomator method, so maybe the bug is within android.

**Comment by bootstraponline** [comment]
uiautomator returning the text value as displayed in uiautomatorviewer isn't a bug. I think this is a "feature."

**Comment by Jonahss** [comment]
Should we think about adding logic to strip the hint text from the beginning of the String? (Is that even possible?)

**Comment by jlipps** [comment]
we don't actually know what the hint text is without trying and failing to delete it, which is a bit of a heavy hammer

**Comment by bootstraponline** [comment]
issues like this are best addressed via a new automation backend. the hint text detection via clearing is slow, flaky, and doesn't always work.

**Comment by Jonahss** [comment]
Closed, since this is a bug with Android, yay.

**Comment by vietnq254** [comment]
Thank you.
