### ISSUE TITLE
use idevicescreenshot to take screenshot on ios. Add capability and server-argument to choose how to take screenshot (instruments or idevicescreenshot)

### ISSUE THREAD

**Issue by yaphatak** [appium/appium#5085]

**Comment by Jonahss** [comment]
:+1:
especially since screenshots on safari with real devices might work better with idevicescreenshot.

**Comment by TusharRastogi** [comment]
Any update on this thread??? @jlipps @Jonahss @yaphatak

**Comment by jlipps** [comment]
no, this is still a feature under consideration

**Comment by TusharRastogi** [comment]
Thanks @jlipps for replying. Is there any workaround as I'm facing the same "Timed out waiting for screenshot file" issue. And when I use
>  --log-level error/warn 

my appium server is not starting. I am using below command to start appium server;

> appium -p 4723 --tmp _some location_ --log-level error

OR
> appium -p 4723 --tmp _some location_ --log-level warn

However when I use debug (--log-level debug) it starts instantly. Please help.

**Comment by jlipps** [comment]
How do you know the server is not starting? It might just not be printing out startup info, since that is not "error" or "warn" level logging.

**Comment by TusharRastogi** [comment]
Right!!

**Comment by imurchie** [comment]
Duplicate of #4805
