### ISSUE TITLE
using appium for app automation, not for testing

### ISSUE THREAD

**Issue by tommedema** [appium/appium#5090]
I'd like to automate a text transformation app on android. My node.js script would read from a database, input text from the database into the android app using appium, and then store the output on the virtual machine in the database.

Would it be possible to do this? I.e. I don't need to do testing, but I need to automate an app and store its output.

**Comment by Simon-Kaz** [comment]
I'm not sure how you plan to achieve this - " then store the output on the virtual machine in the database."

But other than that, definitely possible. I've done this myself (In java and c#), in testing its called Data Driven Testing (where you specify the data and the values are iterated over).

**Comment by jlipps** [comment]
yes. appium is not a testing framework. it is an automation framework that most people use for testing. you of course are responsible for retrieving whatever output you require using the UI, and figuring out how to store it.
