### ISSUE TITLE
How to find click a element that don't have a text or any specificdescription.

### ISSUE THREAD

**Issue by vijay0850** [appium/appium#5091]
I can't able to click this menu button in this app. please help me to find the element id and make it clickable.

![image](https://cloud.githubusercontent.com/assets/10095173/7558517/ea9df97c-f7c3-11e4-8655-e486887f37cf.png)

I tried with following methods,

Absolute Xpath:-

driver.findElement(By.xpath("//android.widget.FrameLayout[0]/android.widget.LinearLayout[0]/android.widget.FrameLayout[0]/android.widget.RelativeLayout[0]/android.widget.LinearLayout[1]/android.widget.RelativeLayout[0]/android.widget.LinearLayout[2]/android.widget.RelativeLayout[0]/android.widget.ImageView[0]")).click();
    	
Relative Xpath:-

    	 driver.findElement(By.xpath("android.widget.ImageView[@clickable='true']")).click();

**Comment by moizjv** [comment]
Hi @vijay0850 can you use [forum](http://discuss.appium.io) to post questions? This space is raise bugs. On your question may be you can use `findElementsByClassName("android.widget.ImageView")` get the all elements and figure out which one is menu and then figure out other unique properties of the element which you can use.

**Comment by vijay0850** [comment]
Okay I posted the same in discussion forum, now u can close the issue here @moizjv if it possible can u please tell me how to find the unique properties of the element. I tried list method it showing classname only.
