### ISSUE TITLE
How to resolve the couldn't find a device to launch issue, while launching the appium for ios?

### ISSUE THREAD

**Issue by valarmathivrv** [appium/appium#5092]
I am using 1.3.6 appium version. When I click the launch button I am  getting the below issue .
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder

info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 8.1

info: [debug] Checking whether instruments supports our device string

info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1.1","iOSSDKVersion":"8.1","deviceName":"iPhone 5s (E5723F7E-05AC-4858-9C9F-495C1FA3A00B)","platformVersion":"7.1"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 5s (E5723F7E-05AC-4858-9C9F-495C1FA3A00B) (7.1 Simulator)'

info: [debug] Cleaning up appium session

error: Could not find a device to launch. You requested 'iPhone 5s (E5723F7E-05AC-4858-9C9F-495C1FA3A00B) (7.1 Simulator)', but the available devices were: ["iPad 2 (8.1 Simulator) [3DD93343-67D4-4EAD-92AA-C005B7933E6D]","iPad Air (8.1 Simulator) [77400AA8-80E0-4ECB-ADCD-08DF3767B57E]","iPad Retina (8.1 Simulator) [A6C0CF5A-255B-4029-AE95-569DA7B29B90]","iPhone 4s (8.1 Simulator) [9CA88BC6-E3ED-44CA-89D8-05487C88A944]","iPhone 5 (8.1 Simulator) [C68E6A43-DBE7-4D85-9CE5-BB87B9915BB0]","iPhone 5s (8.1 Simulator) [E5723F7E-05AC-4858-9C9F-495C1FA3A00B]","iPhone 6 (8.1 Simulator) [4391D23F-BA21-4FB8-8887-0972D2911420]","iPhone 6 Plus (8.1 Simulator) [71B23D13-3F3F-4828-910A-2FAEEABD1C1A]"]

error: Could not pre-launch appium: Error: Could not find a device to launch. You requested 'iPhone 5s (E5723F7E-05AC-4858-9C9F-495C1FA3A00B) (7.1 Simulator)', but the available devices were: ["iPad 2 (8.1 Simulator) [3DD93343-67D4-4EAD-92AA-C005B7933E6D]","iPad Air (8.1 Simulator) [77400AA8-80E0-4ECB-ADCD-08DF3767B57E]","iPad Retina (8.1 Simulator) [A6C0CF5A-255B-4029-AE95-569DA7B29B90]","iPhone 4s (8.1 Simulator) [9CA88BC6-E3ED-44CA-89D8-05487C88A944]","iPhone 5 (8.1 Simulator) [C68E6A43-DBE7-4D85-9CE5-BB87B9915BB0]","iPhone 5s (8.1 Simulator) [E5723F7E-05AC-4858-9C9F-495C1FA3A00B]","iPhone 6 (8.1 Simulator) [4391D23F-BA21-4FB8-8887-0972D2911420]","iPhone 6 Plus (8.1 Simulator) [71B23D13-3F3F-4828-910A-2FAEEABD1C1A]"]

**Comment by Jonahss** [comment]
It looks like you only have iOS 8.1 simulators installed. You will need to use Xcode to install iOS 7.1 simulators if you want to run tests with those.
