### ISSUE TITLE
Not able to start Appium session {"message":"A new session could not be created. (Original error: 'java -version' failed. Error: spawn ENOENT)","origValue":"'java -version' failed. Error: spawn ENOENT"},"sessionId":null}

### ISSUE THREAD

**Issue by Manasa-dd** [appium/appium#5093]
Checking if an update is available
Update not available
Starting Node Server
info: Welcome to Appium v1.3.7 (REV 72fbfaa116d3d9f6a862600ee99cf02f6d0e2182)
info: Appium REST http interface listener started on 127.0.0.1:4723
info: [debug] Non-default server args: {"app":"D:\apk\Calculator.apk","address":"127.0.0.1","logNoColors":true,"deviceName":"emulator-5554","platformName":"Android","platformVersion":"18","automationName":"Appium"}
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"appPath":"D:\apk\Calculator.apk","platformVersion":"4.4","platformName":"Android","deviceName":"tt","appActivity":"com.android.calculator2.Calculator","appPackage":"com.android.calculator2"}}
info: Client User-Agent string: Apache-HttpClient/4.3.2 (java 1.5)
info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : appPath
error: Failed to start an Appium session, err was: Error: 'java -version' failed. Error: spawn ENOENT
info: [debug] Using local app from command line: D:\apk\Calculator.apk
info: [debug] Creating new appium session fb45c483-63bb-4776-bf90-440fa066f539
info: Starting android appium
info: [debug] Getting Java version
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
info: [debug] Error: 'java -version' failed. Error: spawn ENOENT
at C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-common.js:1032:17
at exithandler (child_process.js:633:7)
at ChildProcess.errorhandler (child_process.js:649:5)
at ChildProcess.EventEmitter.emit (events.js:95:17)
at Process.ChildProcess.handle.onexit (childprocess.js:795:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: 'java -version' failed. Error: spawn ENOENT)","origValue":"'java -version' failed. Error: spawn ENOENT"},"sessionId":null}
info: <-- POST /wd/hub/session 500 13.133 ms - 208

Please help me in solving this error

**Comment by Jonahss** [comment]
Do you have the JAVA_HOME environment variable set to your java executable?
To check you installation, run `appium-doctor`

**Comment by imurchie** [comment]
Repeat of #4876.
