### ISSUE TITLE
Add ability to set ios-webkit-debug-proxy port

### ISSUE THREAD

**Issue by shadeimi** [appium/appium#5094]
Hi,
There's any plan to extend appium in order to accept a specific ios-webkit-debug-proxy port? Support for automating multiple devices simultaneously is missing at now

**Comment by jlipps** [comment]
yes, we should add an option for that.

**Comment by jlipps** [comment]
(changed title to reflect request)

**Comment by shadeimi** [comment]
Ok thank you :-)

**Comment by raldred** [comment]
Doesn't this already give us this functionaity using env REMOTE_DEBUGGER_PORT:
https://github.com/appium/appium/pull/2212

**Comment by jlipps** [comment]
ah yes, it does. however we should probably standardize on a server flag rather than an ENV var

**Comment by raldred** [comment]
@jlipps agreed. Although realistically this is pointless until Apple fix instruments so we can run multiple. Discussion on going #273

**Comment by Zoe1808** [comment]
any updates here?

**Comment by SrinivasanTarget** [comment]
"--webkit-debug-proxy-port" is available in current architecture. @imurchie @jlipps Can we close this?

**Comment by jlipps** [comment]
yes. it should also be available under the default capabilities in that case.

**Comment by SrinivasanTarget** [comment]
Yes will close it

**Comment by SrinivasanTarget** [comment]
@triager please close
