### ISSUE TITLE
I am not able to run iOS test without pre-launching an app. If I tried unchecking the pre-launch option , I get error that following desired capability is not provided :deviceName . But I have already provided them 

### ISSUE THREAD

**Issue by ashwiniadke** [appium/appium#5097]
Hi All ,

I am facing an issue with Appium 1.3.7 , where I am not able to run my test without per-launching the app. But I don't want to pre-launch app . My requirement is to launch app once the test is invoked . Please find the capability details below . I am able to run the test successfully if I checked the pre-launch option . 

capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
    capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "8.2");
    capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
    capabilities.setCapability("deviceName", "iPhone 5s (8.2 Simulator)");
    capabilities.setCapability(MobileCapabilityType.APP, "/Users/aadke/Desktop/ipa.ipa");
    capabilities.setCapability("launchTimeout", 15000);
    capabilities.setCapability("appiumVersion", "1.3.7");

And the error that I get

info: Client User-Agent string: Apache-HttpClient/4.3.1 (java 1.5)
error: The following desired capabilities are required, but were not provided: deviceName
info: [debug] Got configuration error, not starting session
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: The following desired capabilities are required, but were not provided: deviceName
info: [debug] Error: The following desired capabilities are required, but were not provided: deviceName

**Comment by Jonahss** [comment]
Are you using Appium.app or a similar desktop client? If so, could you post this issue on the github for that project?

**Comment by ashwiniadke** [comment]
I tried with both Appium.app and appium sever started using terminal.

**Comment by Jonahss** [comment]
It still seems like Appium.app is not sending the 'deviceName' capability when you don't click the prelaunch box.

You are still running with Appium.app, or do you run your tests in the terminal too.

**Comment by ashwiniadke** [comment]
I ran the test with terminal today morning and got the same error. I can see same behavior with Appium.app

**Comment by ashwiniadke** [comment]
these are the logs from terminal 

info: --> POST /wd/hub/session {"desiredCapabilities":{"acceptSslCerts":false,"platformName":"iOS","simulator":true,"timeHack":false,"variation":"Retina4","CFBundleName":"com.ebay.mobile","device":"iphone","CFBundleVersion":"NA","language":"en"}}
info: Client User-Agent string: Apache-HttpClient/4.3.1 (java 1.5)
error: The following desired capabilities are required, but were not provided: deviceName
info: [debug] Got configuration error, not starting session
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: The following desired capabilities are required, but were not provided: deviceName
info: [debug] Error: The following desired capabilities are required, but were not provided: deviceName
    at [object Object].Capabilities.checkValidity (/Users/aadke/.npm-packages/lib/node_modules/appium/lib/server/capabilities.js:145:13)
    at [object Object].Appium.configure (/Users/aadke/.npm-packages/lib/node_modules/appium/lib/appium.js:238:35)
    at [object Object].<anonymous> (/Users/aadke/.npm-packages/lib/node_modules/appium/lib/appium.js:118:10)
    at [object Object].Appium.start (/Users/aadke/.npm-packages/lib/node_modules/appium/lib/appium.js:129:5)
    at exports.createSession (/Users/aadke/.npm-packages/lib/node_modules/appium/lib/server/controller.js:188:16)
    at Layer.handle [as handle_request] (/Users/aadke/.npm-packages/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)

**Comment by ashwiniadke** [comment]
Can I get some updates on this? It's really very important for me.I appreciate your help.

**Comment by ashwiniadke** [comment]
@Jonahss : can you please take a look at this issue?

**Comment by sebv** [comment]
Please refer to doc here for new cpapabilities: http://appium.io/slate/en/master/?java#new-client-libraries
