### ISSUE TITLE
Question related to sudo requiring steps for appium setup on Mac OS X

### ISSUE THREAD

**Issue by binodpanta** [appium/appium#5099]
This doc says there are some setup steps to run that require sudo,
http://appium.io/slate/en/master/?ruby#running-appium-on-mac-os-x

In my organization this means I have to work with a separate department who manages the hosts, and I probably have to repeat for each appium/xcode upgrade?

It would be some much easier for me to develop my tooling if the sudo requirement was not there or if there was a way I could get those steps rolled up in my 'bootstrap' scripts. Is there such a way, other than turning off password requirements for sudo (which does not seem to be a nice thing to do assuming the sysadmins even agree to that)?

**Comment by Jonahss** [comment]
Unfortunately, it looks like it's an apple requirement. We aren't really in control of setting security for enabling DevTools and such.

This should only need to be run on the appium host machines, and only rerun when xcode is updated. Updating appium doesn't require `authorize_ios` to be run again.
