### ISSUE TITLE
Error while running Appium latest version 1.4.0

### ISSUE THREAD

**Issue by spatchamatla** [appium/appium#5100]
Hi,
MAC OS X 10.10.3

i updated the latest version of appium  to 1.4.0 using `npm install -g appium` and it installed without any errors. But when i try to run the tests it errors out saying
```
  error: Failed to start an Appium session, err was: Error: ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip  
info: [debug] Error: ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip at Error (native)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher
/SafariLauncher.zip')","errno":-2,"code":"ENOENT","path":"/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip","origValue":"ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'"},"sessionId":null}
info: <-- POST /wd/hub/session 500 13.397 ms - 411 
```

and when i cd into `/usr/local/lib/node_modules/appium/build` i couldn't find SafariLauncher folder at all. I saw the dependecy Safari Launcher 2.0.5 and confirmed the folder in /usr/local/lib/node_modules/appium/node_modules

The test working fine with 1.3.7

**Comment by Jonahss** [comment]
Thanks for reporting in. Looks like we didn't bundle SafariLauncher into the build process. We should push out a patch release to fix this.

More details:

It looks like publish.sh doesn't run reset.sh with the `--real-safari` flag.

**Comment by Jonahss** [comment]
Pulling version 1.4 from github (via the 1.4 branch) and running `reset.sh --real-safari` will enable you to run Safari tests on Real Devices.

**Comment by spatchamatla** [comment]
@Jonahss is the patch been fixed? where do you want me to run the reset.sh --real-safari?

**Comment by spatchamatla** [comment]
and when i looked at reset.sh, i see only ```reset_ios()``` no real-safari

**Comment by spatchamatla** [comment]
i git clones the 1.4 branch and tried to run ```reset.sh --real-safari``` and see the error::
```-bash: reset.sh: command not found```

**Comment by spatchamatla** [comment]
i ran the cmd ```./reset.sh --real-safari``` and the i see the failure
```
* Determining platform
* Platform is mac
---- Resetting / Initializing Appium ----
RESETTING NPM
* Installing new or updated NPM modules (including devDeps)
RESETTING GENERAL
* Setting git revision data
---- FAILURE: reset.sh exited with status 1 ----
---- Retry with --verbose to see errors ----
```

**Comment by Jonahss** [comment]
Can you run the command again with the `--verbose` option and post the log here?

**Comment by spatchamatla** [comment]
```
npm WARN package.json appium@1.4.0 No license field.
RESETTING GENERAL
* Setting git revision data
Running "setGitRev" task
Config file exists, updating it
{"git-sha":"dc30dae9e8fe8c85eeea707dbdbd60350fdff55b","ios":{"version":"1.4.0"}}
Done, without errors.
RESETTING IOS
* Setting iOS config to Appium's version
Running "setConfigVer:ios" (setConfigVer) task
Config file exists, updating it
{"git-sha":"dc30dae9e8fe8c85eeea707dbdbd60350fdff55b","ios":{"version":"1.4.0"}}
Done, without errors.
* Building SafariLauncher for real devices
Running "buildSafariLauncherApp:iphoneos:/Users/spatchamatla/Documents/Automation/workspace/appium/build/SafariLauncher/target.xcconfig" (buildSafariLauncherApp) task
Using sdk: iphoneos...
Cleaning build...
Building app...

Done, without errors.
* Copying SafariLauncher for real devices to build
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/ (stored 0%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/_CodeSignature/ (stored 0%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/_CodeSignature/CodeResources (deflated 77%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/AUTHORS (deflated 3%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/Default-568h@2x.png (deflated 69%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/Default.png (deflated 50%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/Default@2x.png (deflated 67%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/embedded.mobileprovision (deflated 63%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/en.lproj/ (stored 0%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/en.lproj/InfoPlist.strings (deflated 45%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/Info.plist (deflated 38%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/LICENSE (deflated 38%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/PkgInfo (stored 0%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/README.md (deflated 29%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/SafariLauncher (deflated 84%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/Settings.bundle/ (stored 0%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/Settings.bundle/en.lproj/ (stored 0%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/Settings.bundle/en.lproj/Root.strings (deflated 58%)
  adding: node_modules/safari-launcher/build/Release-iphoneos/SafariLauncher.app/Settings.bundle/Root.plist (deflated 65%)
* Cloning/updating libimobiledevice-macosx
* Copying libimobiledevice-macosx to build
* Cloning/updating deviceconsole
* Building deviceconsole
~/Documents/Automation/workspace/appium/submodules/deviceconsole ~/Documents/Automation/workspace/appium
Making deviceconsole...
~/Documents/Automation/workspace/appium
* Copying deviceconsole to build
RESETTING ANDROID
* Configuring Android bootstrap
Running "configAndroidBootstrap" task
Fatal error: Could not find Android SDK, make sure to export ANDROID_HOME
---- FAILURE: reset.sh exited with status 1 ----
```
its error's on  
```Fatal error: Could not find Android SDK, make sure to export ANDROID_HOME```

do i have to set ANDROID_HOME even thought I'm not testing on Android?

**Comment by spatchamatla** [comment]
and also i see it safari launcher to use Release-iphoneos, if i want to open safari on Ipad will it be the same? Previously i used to install SafariLauncher for IPAD and launch appium to open safari using safari launcher.

**Comment by spatchamatla** [comment]
after installing the android studio, setting  ANDROID_HOME , and rerunning
```./reset.sh --real-safari --verbose``` i see the below error
```
* Configuring Android bootstrap
Running "configAndroidBootstrap" task
Error: Target id is not valid. Use 'android list targets' to get the target ids.
Warning: Setup cmd /Users/<uName>/Library/Android/sdk/tools/android failed with code 1 Use --force to continue.

Aborted due to warnings.
---- FAILURE: reset.sh exited with status 1 ----
```

**Comment by Jonahss** [comment]
If you run `reset.sh --ios` it will skip the android stuff.

**Comment by spatchamatla** [comment]
i ran with ```./reset.sh --ios --real-safari``` and it ran without errors.I started appium with 
```node lib/server/main.js``` and when i try to run the tests it errors out
```
info: [debug] Couldn't find ideviceinstaller, trying built-in at /Users/<path>/appium/build/libimobiledevice-macosx/ideviceinstaller
error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
info: [debug] Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
    at [object Object].IOS.getIDeviceObj (/Users/<path>/appium/lib/devices/ios/ios.js:909:13)
    at [object Object].Safari.installToRealDevice (/Users/<path>/appium/lib/devices/ios/safari.js:151:32)
    at /Users/<path>/appium/node_modules/async/lib/async.js:607:21
    at /Users/<path>/appium/node_modules/async/lib/async.js:246:17
    at iterate (/Users/<path>/appium/node_modules/async/lib/async.js:146:13)
    at /Users/<path>/appium/node_modules/async/lib/async.js:157:25
    at /Users/<path>/appium/node_modules/async/lib/async.js:248:21
    at /Users/<path>/appium/node_modules/async/lib/async.js:612:34
    at [object Object].<anonymous> (/Users/<path>/appium/lib/devices/ios/ios-crash-log.js:52:5)
    at [object Object].<anonymous> (/Users/<path>/appium/lib/devices/ios/ios-crash-log.js:27:5)
    at f (/Users/<path>/appium/node_modules/glob/node_modules/once/once.js:17:25)
    at Glob.<anonymous> (/Users/<path>/appium/node_modules/glob/glob.js:131:7)
    at Glob.emit (events.js:107:17)
    at Glob._finish (/Users/<path>/appium/node_modules/glob/glob.js:168:8)
    at done (/Users/<path>/appium/node_modules/glob/glob.js:157:12)
    at Glob._processReaddir2 (/Users/<path>/appium/node_modules/glob/glob.js:351:12)
    at /Users/<path>/appium/node_modules/glob/glob.js:288:17
    at RES (/Users/<path>/appium/node_modules/glob/node_modules/inflight/inflight.js:23:14)
    at f (/Users/s<path>/appium/node_modules/glob/node_modules/once/once.js:17:25)
    at Glob._readdirEntries (/Users/<path>/appium/node_modules/glob/glob.js:480:10)
    at /Users/<path>/appium/node_modules/glob/glob.js:457:12
    at FSReqWrap.oncomplete (fs.js:95:15)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not initialize ideviceinstaller; make sure it is installed and works on your system)","origValue":"Could not initialize ideviceinstaller; make sure it is installed and works on your system"},"sessionId":null}
info: <-- POST /wd/hub/session 500 382.470 ms - 300 
```

even thought i got the latest branch, it still shows the version as ```Appium v1.4.0```

**Comment by spatchamatla** [comment]
After looking at the post #4584, i installed ```ideviceinstaller``` using ```brew install ideviceinstaller``` and unlinked and installed ```ios_webkit_debug_proxy```. Now when i try to run the test i see the below error

```
error: Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using
info: [debug] Error: Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using
    at [object Object].<anonymous> (/Users/<path>/appium/lib/devices/ios/safari.js:70:17)
    at [object Object].<anonymous> (/Users/<path>/appium/lib/devices/common.js:77:12)
    at [object Object].iOSController.handleFindCb (/Users/<path>/appium/lib/devices/ios/ios-controller.js:313:5)
    at [object Object].<anonymous> (/Users/<path>/appium/lib/devices/ios/ios-controller.js:138:14)
    at next (/Users/<path>/appium/node_modules/async/lib/async.js:798:43)
    at /Users/<path>/appium/node_modules/async/lib/async.js:32:16
    at [object Object].exports.respond (/Users/<path>/appium/lib/devices/common.js:28:9)
    at [object Object].<anonymous> (/Users/<path>/appium/lib/devices/ios/ios.js:1473:18)
    at getResultAndSendNext (/Users/<path>/appium/node_modules/appium-uiauto/lib/command-proxy.js:146:20)
    at Socket.<anonymous> (/Users/<path>/appium/node_modules/appium-uiauto/lib/command-proxy.js:88:7)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using)","origValue":"Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using"},"sessionId":null}
info: <-- POST /wd/hub/session 500 11910.501 ms - 378 
```

So do i have to install the safari launcher on the iPad as well? i though safari Launcher is inbuilt now with latest appium.

**Comment by spatchamatla** [comment]
Im able to run the test after building latest safari launcher on iPad, but appium gets stuck while appium try to run second test. It successfully runs the first test Though.

i opened issue#5164 for the above issue.

**Comment by derek1106** [comment]
Does the fix go to Appium 1.4.1?
In Appium 1.4.1, I still cannot find SafariLauncher.zip, so how could I install SafariLauncher App for browser test?

**Comment by moizjv** [comment]
TRY 1.4.6

**Comment by derek1106** [comment]
I just installed Appium 1.4.6, but there is still no SafariLauncher.zip.

**Comment by Jonahss** [comment]
you have to run reset.sh --real-safari
​

**Comment by derek1106** [comment]
But I use avm to install different Appium versions, and then there is no "reset.sh" in the Appium.
What should I do to resolve the issue?

**Comment by derek1106** [comment]
Will you post the SafariLauncher.zip file in your official release in the future, just like Appium 1.3.x?

**Comment by derek1106** [comment]
When I executed the command "reset.sh --real-safari", I got the error as below.

* Building SafariLauncher for real devices
Running "buildSafariLauncherApp:iphoneos:/Users/shiwei/appium_source/appium-master/build/SafariLauncher/target.xcconfig" (buildSafariLauncherApp) task
Using sdk: iphoneos...
Cleaning build...
Building app...
Failed building app, maybe it doesn't exist?
Build settings from command line:
    SDKROOT = iphoneos8.1

Build settings from configuration file '/Users/shiwei/appium_source/appium-master/build/SafariLauncher/target.xcconfig':
    BUNDLE_ID = com.bytearc.SafariLauncher
    IDENTITY_CODE = 
    IDENTITY_NAME = iPhone Developer

=== BUILD TARGET SafariLauncher OF PROJECT SafariLauncher WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.1'

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

**Comment by spatchamatla** [comment]
@derek1106 
These are steps i followed to run tests on Safari on real devices::
1)Clone master branch from appium and run with ./reset.sh --ios --real-safari .
2)installed ideviceinstaller using brew install ideviceinstaller and unlinked and installed ios_webkit_debug_proxy
3)build latest safarilLauncher on the device
I started appium with
node lib/server/main.js
and then ./bin/ios-webkit-debug-proxy-launcher.js -c <UUID>:27753 -d

**Comment by spatchamatla** [comment]
Code Sign errors are due to either no provisioning profile or the developer certificate cannot be found by xcode, refresh your account and make sure your device is added to the profile you are using

**Comment by moizjv** [comment]
@Jonahss ping

**Comment by nikolmarku** [comment]
Error. Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using.

What is the version of SafariLaucher that appium is using?

**Comment by nikolmarku1** [comment]
Error. Could not find button to launch Safari is shown on appium version v1.4.8 (REV ca00c8b799957b8e69e513d981d98c6f507f269b)
and 1.4.0.   Thanks for your help

**Comment by Jonahss** [comment]
If you run `./reset.sh --real-safari

**Comment by Irislmh** [comment]
I got below errors:
* Determining platform
* Platform is mac
---- Resetting / Initializing Appium ----
RESETTING NPM
* Installing new or updated NPM modules (including devDeps)
---- FAILURE: reset.sh exited with status 1 ----
---- Retry with --verbose to see errors ----
LM-SHC-16501071:appium mengli$ ./reset.sh --real-safari --verbose
* Determining platform
* Platform is mac
---- Resetting / Initializing Appium ----
RESETTING NPM
* Installing new or updated NPM modules (including devDeps)
npm WARN package.json appium@1.4.8 No license field.
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "."
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path /Applications/Appium.app/Contents/Resources/node_modules/.bin/appium
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/Applications/Appium.app/Contents/Resources/node_modules/.bin/appium'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/Applications/Appium.app/Contents/Resources/node_modules/.bin/appium']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Applications/Appium.app/Contents/Resources/node_modules/.bin/appium' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/Appium.app/Contents/Resources/node_modules/appium/npm-debug.log
---- FAILURE: reset.sh exited with status 1 ----

Can you please take a look? Thanks!

**Comment by fayizkc** [comment]
I am also facing issue in the appium version 1.4.8 in Mac. It showing error as "(Original error: ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip')
While I am going to the path "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/" there is no folder SafariLauncher" available. Please help me to resolve it.

**Comment by Irislmh** [comment]
Hi Fayis.

I already fixed this issue. Please download the latest SafariLauncher
project from github(https://github.com/budhash/SafariLauncher), then build
it in Xcode, it will generate a file SafariLauncher.app in Products folder.
Compress the file to "SafariLauncher.zip", then navigate to
/Applications/Appium.app/Contents/Resources/node_modules/appium/build/,
create a folder "SafariLauncher", put "SafariLauncher.zip" file into the
folder, then it should be worked.
Hope it will help.

2015-09-15 22:06 GMT+08:00 Fayis K <notifications@github.com>:

**Comment by AppiumUserForMobile** [comment]
I am facing same issue on appium 1.4.16 . I tried steps mentioned by @Irislmh but that didnt work. Can someone please help?

**Comment by Jonahss** [comment]
@AppiumUserForMobile Which issue? This thread is way too long now.

**Comment by AppiumUserForMobile** [comment]
The issue of appium not finding SafariLauncher.

Here is what I tried
 git clone https://github.com/appium/appium.git
./reset.sh --ios --real-safari
But when trying to run appium from the local location where it got cloned to, it says "/usr/local/bin/appium:No such file or directory" .
I removed the 1.4.16 version which I had earlier.

Can you please help?

**Comment by AppiumUserForMobile** [comment]
Can someone please let me know what I am missing here? Thanks in advance.

**Comment by minimedj** [comment]
Appium 1.4.16

    WebDriverException: Message: A new session could not be created. (Original error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip')

**Comment by SrinivasanTarget** [comment]
reset.sh is moved out from current 1.5 architecture and it's more simple than before. Please try a recent version of appium i.e 1.5.1 now. Follow the instructions from https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/mobile-web.md. Incase of issues i request to raise a new issue with detailed logs as gist.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by rkn411** [comment]
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: ENOENT: no such file or directory, stat '/Applications/Appium 2.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip')","errno":-2,"code":"ENOENT","syscall":"stat","path":"/Applications/Appium 2.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip","origValue":"ENOENT: no such file or directory, stat '/Applications/Appium 2.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'"},"sessionId":null}

**Comment by rkn411** [comment]
error while launching safari browser on real device
iPhone 5s -9.3.3
xcode8.1
appium 1.14
safari launcher signed with developer certificates

**Comment by fayizkc** [comment]
Hi,
Please download the latest SafariLauncher
project from github(https://github.com/budhash/SafariLauncher), then build
it in Xcode, it will generate a file SafariLauncher.app in Products folder.
Compress the file to "SafariLauncher.zip", then navigate to
/Applications/Appium.app/Contents/Resources/node_modules/appium/build/,
create a folder "SafariLauncher", put "SafariLauncher.zip" file into the
folder, then it should be worked.
Hope it will help.

**Comment by rkn411** [comment]
i created folder i m running in mac machine so there won't be zip  format i think so
