### ISSUE TITLE
Appium v1.4.0 return invalid json data format

### ISSUE THREAD

**Issue by LimeDang** [appium/appium#5104]
Appium v1.4.0

When I execute: driver.executeScript("UIATarget.localTarget().frontMostApp().getTree()")
the data return is: {valid=true, enable=true, ..., name=Safari, type=UIAApplication} this is invalid json data format.

Previous versions of Appium, it return: {"valid":true, "enable":true, ..., "name":"Safari", "type":"UIAApplication"} this is valid json data format and it should be.

**Comment by sebv** [comment]
Possible bug.

**Comment by SrinivasanTarget** [comment]
@sebv It's working fine for me in Appium v1.4.16.Is it fixed?

**Comment by imurchie** [comment]
Works in 1.4.16 and 1.5. Closing.
