### ISSUE TITLE
Clear app data with Appium

### ISSUE THREAD

**Issue by Simon-Kaz** [appium/appium#5108]
First of all, I noticed that some devices don't play nice with the driver.appReset() method (java client). Main culprit being the Nexus 5 - Galaxy s4 is fine for example.

I tried the alternative (or is that what's being used by appReset?) 

````
adb shell pm clear my.app.package
````

But again, it did not work on Nexus 5, and worked fine with Galaxy s4.

Is there an alternative to the above?

**Comment by Jonahss** [comment]
Appium's `reset` function first uninstalls, then reinstalls the app.

Any idea why it doesn't work on the Nexus 5? What do you see in logcat when you try to run the adb commands?

**Comment by Simon-Kaz** [comment]
I'll do some more research later today! Will provide logs as well/

**Comment by Simon-Kaz** [comment]
I've tried to grep the logs but I'm not sure what to look for :( I can confirm though that nexus does not play nice with that adb command, the data is still there.

**Comment by Simon-Kaz** [comment]
Aaaaaand it started working.. I'll dig into this one more time, must've been the settings I changed.

**Comment by sebv** [comment]
Ok closing for now, open a new issue and post the log if needed.
