### ISSUE TITLE
[App] View and record in the inspector using the "WEBVIEW" context.

### ISSUE THREAD

**Issue by muclemente** [appium/appium#5110]
Hi everyone,

I am using the OSX GUI App for Appium and when trying to change the context to a webview, I'm getting an error called "invalid parameter: name". This is because the JSON in the post request is being sent as " { context: "WEBVIEW" } " and not { name: "WEBVIEW" }.

I was able to workaround this issue by manually sending a request to the hub via Postman with the correct body.

But when the context is changed and I hit "Refresh" in the Appium GUI, no elements are rendered. 
I'm guessing the current app is only parsing XML pages, not the Webview format (with CSS classes and whatnot)

Is this an already requested feature? Is this something already mapped down the road?

Thanks!

**Comment by Jonahss** [comment]
Hi, thanks for your issue, can you repost this to the github repository for Appium.app? This repo is only for the actual appium server :)
