### ISSUE TITLE
An element could not be located on the page using the given search parameters.

### ISSUE THREAD

**Issue by ashutoshcrestech** [appium/appium#5114]
Hi,
I tried with with class,id,link, then finally with xpath on both device and emulator but its giving me same error in Appium, am I doing something wrong, am trying to automate a simple phonegap application having html page, Please Help me to automate simple phonegap app.
//***My CODE is :*** 
public static AndroidDriver driver;
	public static void main(String[] args) throws IOException {
		DesiredCapabilities capabilites = new DesiredCapabilities();
		capabilites.setCapability("device name", "xxxxxxxxxxx");
		capabilites.setCapability("platform version", "4.4.2");
		capabilites.setCapability("platformName", "Android");
		capabilites.setCapability("appPackage", "com.example.hellophonegap");
		capabilites.setCapability("appActivity", "com.example.hellophonegap.MainActivity");
		
		driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilites);
		
		driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
		//driver.context("WEBVIEW_com.example.hellophonegap");
		/*WebElement linkButton = driver.findElement(By.className("Button"));
	    linkButton.click();*/
		driver.findElementByXPath("html/body/a/button").click();
		//driver.findElement(By.linkText("Visit Information Page!")).click();

	}
//***APPIUM o/p***
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"xpath","selector":"html/body/a/button","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"html/body/a/button","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding html/body/a/button using XPATH with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Could not find an element using supplied strategy. ","status":7}
> info: [debug] Waited for 26996ms so far

**Comment by sebv** [comment]
The best way to debug this kind of issues is to print the page source immediately before the find.

**Comment by ashutoshcrestech** [comment]
can you please elaborate as I am new to Appium.

**Comment by sebv** [comment]
It's easy, just call the source method on your driver. (They all have a source method, this is part of the JsonWire protocol).

**Comment by sebv** [comment]
Closing, does not look like a bug, please go here for further support: https://discuss.appium.io/
