### ISSUE TITLE
Depending on legacy on-demand authorization, which is not supported for new apps

### ISSUE THREAD

**Issue by valarmathivrv** [appium/appium#5115]
1. I am using appium version 1.3.7 for inspecting ios  app. I have given  the app path and device name and platform version.

2. When I launch the appium server, it doesn't recognize the physical device which I have connected via USB.

3. The appium log shows the simulators which are all available in the system.

4. I have tried to inspect the ios app in ios simulator itself, the app doesn't get installed in ios simulator. But the splash advertisement in the app alone get displayed as in the simulator. When I checked in the ios simulator, I don't find any app get installed in the ios simulator.I totally in chaos state, how can I able to get splash add without app get installed in the ios simulator.

5. I don't know what I am missing while setting the parameters for ios. Is there must to set bundled id, while connecting with physical device.

6. I just want to know whether the device version such as iphone 5s and platform version such as 7.1.1 are mandatory and that should be given as accurate while setting the parameters for ios.

Appium Log:

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"26c9dff4-b119-4144-88ef-efe3d84800a6"}
info: <-- GET /wd/hub/status 200 0.658 ms - 178 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"26c9dff4-b119-4144-88ef-efe3d84800a6"}

info: [IOS_SYSLOG_ROW ] May 13 18:23:23 alkaffs-Mac-mini.local locationd[5150]: ERROR: com.vr.iphone.lais depending on legacy on-demand authorization, which is not supported for new apps

info: [IOS_SYSLOG_ROW ] May 13 18:23:23 alkaffs-Mac-mini.local locationd[5150]: ERROR: com.vr.iphone.la is depending on legacy on-demand authorization, which is not supported for new apps

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"26c9dff4-b119-4144-88ef-efe3d84800a6"}
info: <-- GET /wd/hub/status 200 0.817 ms - 178 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"26c9dff4-b119-4144-88ef-efe3d84800a6"}

**Comment by sebv** [comment]
It's a ios issue, please google `"depending on legacy on-demand authorization, which is not supported for new apps"`

**Comment by sebv** [comment]
Closing, app issue, may be reopened if needed.
