### ISSUE TITLE
Cannot navigate back after calling setBackButtonBackgroundImage:

### ISSUE THREAD

**Issue by osgafarov** [appium/appium#5116]
Hey,

I am using appium 1.3.7. I am testing an iOS app on iOS 8.3 Simulator.
I have a navigation controller with multiple view controllers in its stack.
If I call 

```
[[UIBarButtonItem appearance] setBackButtonBackgroundImage:headerIconBack forState:UIControlStateHighlighted barMetrics:UIBarMetricsDefault];
```

then the back() method of Web Driver is not able to navigate back to previous view.

Looks like UIAutomation is not able to find a proper "Back" button in the nav bar.

Can you check it out guys?

Thanks,
Osman

**Comment by sebv** [comment]
Could you provide server log (in gist)? thx.

**Comment by osgafarov** [comment]
Here is the log: https://gist.github.com/osgafarov/2c31024bcfbd9b5428c5

If I don't call the method specified in my first comment, it works fine.
Thanks

**Comment by sebv** [comment]
Looks like there is no back button to tap. Could you print the page source before you call the `back` method?

**Comment by osgafarov** [comment]
What do you mean by page source? Should I print the views hierarchy tree in the Appium app?

**Comment by moizjv** [comment]
@osgafarov yes may be back button is not present in the screen?

**Comment by osgafarov** [comment]
@moizjv 
Here is the tree:
https://gist.github.com/osgafarov/9c8d1adf534aa1f39787

**Comment by moizjv** [comment]
@osgafarov `<UIAButton name="Back" label="Back" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/2" x="8" y="31.5" width="21" height="21">
                </UIAButton>` visible is false may be that is the reason?

**Comment by osgafarov** [comment]
@moizjv 
So looks like calling:
``` [[UIBarButtonItem appearance] setBackButtonBackgroundImage:headerIconBack forState:UIControlStateNormal barMetrics:UIBarMetricsDefault];```

Changes the visibility of the back button.
If I comment this line out, then everything is fine.
