### ISSUE TITLE
What is the correct way of generating .app file to make it run with Appium

### ISSUE THREAD

**Issue by hanzra** [appium/appium#5117]
I am struggling from the past few days to make appium work with the app developed by my team. I read on appium documents that debug version of .app file targeted for iphone simulator should work with Appium and I think we are doing the same. 

Is there anything else that should be taken care of while building app file? any suggestion for troubleshooting?

Dev Team is using xamarine to build the app.

**Comment by sebv** [comment]
Please go here for help: https://discuss.appium.io/
