### ISSUE TITLE
Unable to inspect the ios app using appium inspector

### ISSUE THREAD

**Issue by valarmathivrv** [appium/appium#5121]
1. I am using appium version 1.3.7 version.
2. After starting appium sever, the app get installed in ios simulator.
3. When I tried to inspect using appium inspector, the refresh button in the appium inspector keeps on loading, it doesn't load the home page of an app at all.

**Comment by sebv** [comment]
Please post issue here: https://github.com/appium/appium-dot-app

More details would also be helpful.

**Comment by sebv** [comment]
Closing, not a appium server issue (see previous ost), you may also get help here: https://discuss.appium.io/
