### ISSUE TITLE
Not able read value attribute of elements

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#5126]
I am using appium with python client to write automation for an application iOS (target devices are iPhone 5c and 6). 
Issue: Current implementation of get_text returns text from property of element obj (i.e. name or label attribute not very sure which one), i require to read the value attribute of element (value of text field etc) 
 
Do we have any api for this?

**Comment by imurchie** [comment]
For the value of a text field, `driver.text`.

This sort of query would be better asked on the [Appium Discuss](https://discuss.appium.io/) board.
