### ISSUE TITLE
[Android] Unable to get the text from a password field.

### ISSUE THREAD

**Issue by imurchie** [appium/appium#5127]
UI Automator is unable to get the text from an `android.widget.EditText` field which is used for a password (i.e., sets `inputType="textPassword"`). `getText()` always returns `""`. This also manifests itself as an inability to clear a password field, since clear checks if there is any text in the element, and UI Automator says there is not.

See appium/python-client#81.

**Comment by jlipps** [comment]
not being able to get the text may be intentional, but not being able to clear it is problematic :-/

maybe uiautomator2 will fix this

**Comment by HenningL** [comment]
to not get the text of a password-field is not something what makes sense to me. we are talking about testing not production environment. simple case: i want to check if the hint in the pw-field is correct. by now its impossible, or is it?

**Comment by jlipps** [comment]
@HenningL unfortunately the way that Google designed it, it's impossible. the way to detect that it is correct is to try logging in.
