### ISSUE TITLE
Appium-Selendroid not working with xpath to find the element in Native app

### ISSUE THREAD

**Issue by vijay0850** [appium/appium#5129]
My Environment: 

Windows 7, Appium 1.4.0, API 17, Automation: Selendroid, App:Hybrid

Selendroid is not clicking an element in Native app by using xpath.

Code:-

String s= driver.findElement(By.className("android.widget.Button")).getText();
		
System.out.println(s);  //Printing the Text "OK"
		 
 driver.findElement(By.xpath("//Button[@text='OK'']")).click(); // as suggested I used this xpath

but not clicking the button it showing "element not found" error message in java console.

When I using the find element by class name it working fine, but I want to click on a particular button in the screen.

driver.findElement(By.className("android.widget.Button")).click();

is this a issue in appium newer version? if its please resolve faster else tell me the solution :)

**Comment by vijay0850** [comment]
Any update for this issue

**Comment by EthanJiang** [comment]
Can you start the selendroid server. I just try 1.4.0 with selendroid. find the Selendroid server can't be started.

**Comment by vijay0850** [comment]
@EthanJiang I able to start selendroid server and able to find elements with classname but I cant use xpath to find the element.

**Comment by EthanJiang** [comment]
There is another Group, just for windows [Appium-dot-exe], I get quick response in that group. I think you can post the issue to that group.

**Comment by vijay0850** [comment]
Can you please tell me the group name

**Comment by EthanJiang** [comment]
appium/appium-dot-exe

**Comment by sebv** [comment]
Could you provide server log (In gist)? thx.

**Comment by vijay0850** [comment]
It showing element not found in Java console and here is the Appium log

https://gist.github.com/vijay0850/dee0f9af26e343b5ab66

**Comment by sebv** [comment]
Looks like, the element is not there, try to print a page source before the find to verify that the xpath is correct.

**Comment by vijay0850** [comment]
@sebv , Can you please tell me how to print the page source I will try that

**Comment by sebv** [comment]
Your driver must have a `page source` method check the driver doc.

**Comment by vijay0850** [comment]
Thanks @sebv now the xpath is working :)
