### ISSUE TITLE
Failed to start an Appium session, err was: [object Object]

### ISSUE THREAD

**Issue by cjtcwyk** [appium/appium#5130]
When Appium runs test on a Jenkins slaver, Appium will probability of occurrence the error.(Probably nine or ten test cases will occur once error)
error: Failed to start an Appium session, err was: [object Object]
info: [debug] undefined
info: [debug] Responding to client with error: {"status":33,"value":{"message":"Invalid response from device","name":"UnknownError","origValue":"Invalid response from device"},"sessionId":null}

the Jenkins slaver env: MacMini OSX 10.10.1, Appium 1.3.7, java client2.2, iOS8.1Simulator.

full log:
appium
info: Welcome to Appium v1.3.7 (REV 72fbfaa116d3d9f6a862600ee99cf02f6d0e2182)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
gradle clean test
:clean
:compileJava
:processResources UP-TO-DATE
:classes
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:test
Running test: test testOrder_ASAPOrderShouldSuccess(com.test.iweidao.uitest.core.order.iWeiDaoASAPOrderTest)
info: --> POST /wd/hub/session {"desiredCapabilities":{"waitForAppScript":true,"platformVersion":"8.1","autoAcceptAlerts":true,"app":"/Users/jenkins/Remote_FS_Root/workspace/iOS-APP-UITEST/./iWeidao.app","platformName":"iOS","deviceName":"iPhone 6"}}
info: Client User-Agent string: Apache-HttpClient/4.3.6 (java 1.5)
info: [debug] Using local app from desired caps: /Users/jenkins/Remote_FS_Root/workspace/iOS-APP-UITEST/iWeidao.app
info: [debug] Creating new appium session eeea2dbc-0480-40c0-ac3a-c510c6e5b87e
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder
info: [debug] Setting Xcode version
info: [debug] Setting iOS SDK Version
info: [debug] Getting sdk version from xcrun with a timeout
info: [debug] iOS SDK Version set to 8.1
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] iOS sim UDID is C27F518D-8D1F-4C54-979E-334CBAC26C44
info: [debug] Detecting automation tracetemplate
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/jenkins/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/0.10.28/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":true,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/jenkins/Library/Application Support/appium/bootstrap/bootstrap-89d18b1974eac5cb.js
info: [debug] Reusing dynamic bootstrap: /Users/jenkins/Library/Application Support/appium/bootstrap/bootstrap-89d18b1974eac5cb.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.1","iOSSDKVersion":"8.1","deviceName":"iPhone 6","platformVersion":"8.1"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (8.1 Simulator)'
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] Cleaning sim data files
info: Executing: xcrun simctl erase C27F518D-8D1F-4C54-979E-334CBAC26C44 with timeout 2000
info: [debug] Cleaning app data files
warn: Applications directory /Users/jenkins/Library/Developer/CoreSimulator/Devices/C27F518D-8D1F-4C54-979E-334CBAC26C44/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/jenkins/Library/Developer/CoreSimulator/Devices/C27F518D-8D1F-4C54-979E-334CBAC26C44/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Not setting locale
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS 8.* simulator log capture
info: [debug] Not pre-launching simulator
info: [debug] No device id or app, not installing to real device.
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on iPhone 6 (8.1 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 (8.1 Simulator)" /Users/jenkins/Remote_FS_Root/workspace/iOS-APP-UITEST/iWeidao.app -e UIASCRIPT "/Users/jenkins/Library/Application Support/appium/bootstrap/bootstrap-89d18b1974eac5cb.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST] Waiting for device to boot...
warn: Instruments socket client never checked in; timing out (global)
info: [debug] Killall instruments
info: [debug] [INSTSERVER] Instruments exited with code null
info: [debug] Killall instruments
info: [debug] Instruments never checked in
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator
info: Launching instruments
info: [debug] Attempting to run app on iPhone 6 (8.1 Simulator)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 (8.1 Simulator)" /Users/jenkins/Remote_FS_Root/workspace/iOS-APP-UITEST/iWeidao.app -e UIASCRIPT "/Users/jenkins/Library/Application Support/appium/bootstrap/bootstrap-89d18b1974eac5cb.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {"DYLD_INSERT_LIBRARIES":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6/InstrumentsShim.dylib","LIB_PATH":"/usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd6"}
info: [debug] And launch timeouts (in ms): {"global":90000}
info: Instruments is ready to receive commands
info: [debug] Instruments launched. Starting poll loop for new commands.
info: [debug] Setting bootstrap config keys/values
info: [debug] Pushing command to appium work queue: "target = $.target();\nau = $;\n$.isVerbose = true;\n"
info: [debug] Socket data received (2 bytes)
info: [debug] Socket data being routed.
info: [debug] Sending command to instruments: target = $.target();
au = $;
$.isVerbose = true;

info: [debug] [INST] Waiting for device to boot...
info: [debug] Socket data received (2 bytes)
info: [debug] Socket data being routed.
info: [debug] Instruments didn't send a result even though we were expecting one
info: [debug] Got null result from instruments
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: [object Object]
info: [debug] undefined
info: [debug] Responding to client with error: {"status":33,"value":{"message":"Invalid response from device","name":"UnknownError","origValue":"Invalid response from device"},"sessionId":null}
info: <-- POST /wd/hub/session 500 154576.245 ms - 146 
info: --> POST /wd/hub/session {"desiredCapabilities":{"waitForAppScript":true,"platformVersion":"8.1","autoAcceptAlerts":true,"app":"/Users/jenkins/Remote_FS_Root/workspace/iOS-APP-UITEST/./iWeidao.app","platformName":"iOS","deviceName":"iPhone 6"}}
info: Client User-Agent string: Apache-HttpClient/4.3.6 (java 1.5)
info: [debug] Using local app from desired caps: /Users/jenkins/Remote_FS_Root/workspace/iOS-APP-UITEST/iWeidao.app
info: [debug] Creating new appium session d877c16e-da26-4a31-84bf-7634deb1b4fb
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder

com.test.iweidao.uitest.core.order.iWeiDaoASAPOrderTest > testOrder_ASAPOrderShouldSuccess FAILED
    org.openqa.selenium.SessionNotCreatedException at iWeiDaoASAPOrderTest.java:34

**Comment by sebv** [comment]
Magic script here: https://github.com/appium/appium/blob/master/ci/as_current_user

**Comment by sebv** [comment]
Was this resolved?

**Comment by cjtcwyk** [comment]
thinks sebv! I had just seen the reply, will try to execute the script and let you know the results.

**Comment by cjtcwyk** [comment]
Something strange happened, I execute the script on my MBP, it works fine; but when I execute the script on my Mac mini, return appium: command not found. I have try to upgrade, and reinstall appium form npm, the script still can not found appium.

± which appium        
/usr/local/bin/appium

± ./as_current_user appium
Running:
sudo launchctl bsexec 65 sudo -u 'jenkins' appium
sudo: appium: command not found

**Comment by sebv** [comment]
Probably a PATH issue. 
Can try: 
sudo launchctl bsexec 65 sudo -u 'jenkins' $(which appium)

**Comment by cjtcwyk** [comment]
woooo! It works!! thanks sebv!
