### ISSUE TITLE
Starting appium server for both android and IOS on same machine through command line or through code?

### ISSUE THREAD

**Issue by tolgatanriverdi** [appium/appium#5131]
Hi
I would like to use appium in our project and I would like to start appium server for both android and IOS on the same machine.
I'm using Mac OsX , as far as I found there is only appium gui application for mac os x
If I want to start appium for IOS and android through command line(Or through changing source code)
What should I do?

Thanks
Tolga

**Comment by amedvedjev** [comment]
use command line :+1: 
 - to install on mac: npm -g install appium

**Comment by sebv** [comment]
Please refer to:
http://appium.io/
https://discuss.appium.io/
