### ISSUE TITLE
Shell command fails on retry logic

### ISSUE THREAD

**Issue by yaphatak** [appium/appium#5136]
This(https://github.com/appium/appium-adb/blob/master/lib/helpers.js#L157-L160) is adding escape characters on retry and causing failures 

2015-05-20 00:00:08:036 - info: [debug] Getting device API level
2015-05-20 00:00:08:039 - info: [debug] executing cmd: c:\Olympus\ADT\SDK\platform-tools\adb.exe -s deviceid shell "getprop ro.build.version.sdk"
2015-05-20 00:00:08:069 - info: error sending command, reconnecting device and retrying: shell "getprop ro.build.version.sdk"
2015-05-20 00:00:08:421 - info: --> GET /wd/hub/status {}
2015-05-20 00:00:08:422 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7"}},"sessionId":"a35e74ef-6544-42e7-9924-6a23d0a2d363"}
2015-05-20 00:00:08:423 - info: <-- GET /wd/hub/status 200 2.302 ms - 101 {"status":0,"value":{"build":{"version":"1.3.7"}},"sessionId":"a35e74ef-6544-42e7-9924-6a23d0a2d363"}
2015-05-20 00:00:09:081 - info: [debug] Trying to find a connected android device
2015-05-20 00:00:09:081 - info: [debug] Getting connected devices...
2015-05-20 00:00:09:082 - info: [debug] executing cmd: c:\Olympus\ADT\SDK\platform-tools\adb.exe -s deviceid devices
2015-05-20 00:00:09:158 - info: [debug] 4 device(s) connected
2015-05-20 00:00:09:159 - info: [debug] executing cmd: c:\Olympus\ADT\SDK\platform-tools\adb.exe -s deviceid "shell \"getprop ro.build.version.sdk\""
2015-05-20 00:00:09:202 - warn:  Error: Command failed: Android Debug Bridge version 1.0.31
 -a                            - directs adb to listen on all interfaces for a connection
 -d                            - directs command to the only connected USB device
                                 returns an error if more than one USB device is present.
 -e                            - directs command to the only running emulator.
                                 returns an error if more than one emulator is running.
 -s <specific device>          - directs command to the device or emulator with the given
                                 serial number or qualifier. Overrides ANDROID_SERIAL
                                 environment variable.
 -p <product name or path>     - simple product name like 'sooner', or
                                 a relative/absolute path to a product
                                 out directory like 'out/target/product/sooner'.
                                 If -p is not specified, the ANDROID_PRODUCT_OUT
                                 environment variable is used, which must
                                 be an absolute path.
 -H                            - Name of adb server host (default: localhost)
 -P                            - Port of adb server (default: 5037)
 devices [-l]                  - list all connected devices
                                 ('-l' will also list device qualifiers)
 connect <host>[:<port>]       - connect to a device via TCP/IP
                                 Port 5555 is used by default if no port number is specified.
 disconnect [<host>[:<port>]]  - disconnect from a TCP/IP device.
                                 Port 5555 is used by default if no port number is specified.
                                 Using this command with no additional arguments
                                 will disconnect from all connected TCP/IP devices.
device commands:
  adb push <local> <remote>    - copy file/dir to device
  adb pull <remote> [<local>]  - copy file/dir from device
  adb sync [ <directory> ]     - copy host->device only if changed
                                 (-l means list but don't copy)
                                 (see 'adb help all')
  adb shell                    - run remote shell interactively
  adb shell <command>          - run remote shell command
  adb emu <command>            - run emulator console command
  adb logcat [ <filter-spec> ] - View device log
  adb forward --list           - list all forward socket connections.
                                 the format is a list of lines with the following format:
                                    <serial> " " <local> " " <remote> "\n"
  adb forward <local> <remote> - forward socket connections
                                 forward specs are one of: 
                                   tcp:<port>
                                   localabstract:<unix domain socket name>
                                   localreserved:<unix domain socket name>
                                   localfilesystem:<unix domain socket name>
                                   dev:<character device name>
                                   jdwp:<process pid> (remote only)
  adb forward --no-rebind <local> <remote>
                               - same as 'adb forward <local> <remote>' but fails
                                 if <local> is already forwarded
  adb forward --remove <local> - remove a specific forward socket connection
  adb forward --remove-all     - remove all forward socket connections
  adb jdwp                     - list PIDs of processes hosting a JDWP transport
  adb install [-l] [-r] [-s] [--algo <algorithm name> --key <hex-encoded key> --iv <hex-encoded iv>] <file>
                               - push this package file to the device and install it
                                 ('-l' means forward-lock the app)
                                 ('-r' means reinstall the app, keeping its data)
                                 ('-s' means install on SD card instead of internal storage)
                                 ('--algo', '--key', and '--iv' mean the file is encrypted already)
  adb uninstall [-k] <package> - remove this app package from the device
                                 ('-k' means keep the data and cache directories)
  adb bugreport                - return all information from the device
                                 that should be included in a bug report.
  adb backup [-f <file>] [-apk|-noapk] [-obb|-noobb] [-shared|-noshared] [-all] [-system|-nosystem] [<packages...>]
                               - write an archive of the device's data to <file>.
                                 If no -f option is supplied then the data is written
                                 to "backup.ab" in the current directory.
                                 (-apk|-noapk enable/disable backup of the .apks themselves
                                    in the archive; the default is noapk.)
                                 (-obb|-noobb enable/disable backup of any installed apk expansion
                                    (aka .obb) files associated with each application; the default
                                    is noobb.)
                                 (-shared|-noshared enable/disable backup of the device's
                                    shared storage / SD card contents; the default is noshared.)
                                 (-all means to back up all installed applications)
                                 (-system|-nosystem toggles whether -all automatically includes
                                    system applications; the default is to include system apps)
                                 (<packages...> is the list of applications to be backed up.  If
                                    the -all or -shared flags are passed, then the package
                                    list is optional.  Applications explicitly given on the
                                    command line will be included even if -nosystem would
                                    ordinarily cause them to be omitted.)
  adb restore <file>           - restore device contents from the <file> backup archive
  adb help                     - show this help message
  adb version                  - show version num
scripting:
  adb wait-for-device          - block until device is online
  adb start-server             - ensure that there is a server running
  adb kill-server              - kill the server if it is running
  adb get-state                - prints: offline | bootloader | device
  adb get-serialno             - prints: <serial-number>
  adb get-devpath              - prints: <device-path>
  adb status-window            - continuously print device status for a specified device
  adb remount                  - remounts the /system partition on the device read-write
  adb reboot [bootloader|recovery] - reboots the device, optionally into the bootloader or recovery program
  adb reboot-bootloader        - reboots the device into the bootloader
  adb root                     - restarts the adbd daemon with root permissions
  adb usb                      - restarts the adbd daemon listening on USB
  adb tcpip <port>             - restarts the adbd daemon listening on TCP on the specified port
networking:
  adb ppp <tty> [parameters]   - Run PPP over USB.
 Note: you should not automatically start a PPP connection.
 <tty> refers to the tty for PPP stream. Eg. dev:/dev/omap_csmi_tty1
 [parameters] - Eg. defaultroute debug dump local notty usepeerdns
adb sync notes: adb sync [ <directory> ]
  <localdir> can be interpreted in several ways:
  - If <directory> is not specified, both /system and /data partitions will be updated.
  - If it is "system" or "data", only the corresponding partition
    is updated.
environmental variables:
  ADB_TRACE                    - Print debug information. A comma separated list of the following values
                                 1 or all, adb, sockets, packets, rwx, usb, sync, sysdeps, transport, jdwp
  ANDROID_SERIAL               - The serial number to connect to. -s takes priority over this if given.
  ANDROID_LOG_TAGS             - When used with the logcat option, only these debug tags are printed.
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)

**Comment by yaphatak** [comment]
@sebv can you have look at this?

**Comment by yaphatak** [comment]
adding escape character to adb command wont work except that escape character is part of "query" to certain adb command

**Comment by jlipps** [comment]
ah, so we're double-wrapping it. @moizjv fyi as you're porting appium-adb :-)

**Comment by rseek** [comment]
Hello, 
Fix would be great.

Seems like this problem is linked with https://github.com/appium/appium-adb/issues/70

**Comment by jlipps** [comment]
this should be fixed in the latest versions of appium
