### ISSUE TITLE
Safari "readyState was interactive" since Appium 1.3.5

### ISSUE THREAD

**Issue by ericzered** [appium/appium#5141]
Hello,
I was using Appium 1.3.4 and everything was ok with my Safari Browsing on iOS 8.1 Simulator.
I'm going to a website with JS.
But since I update to 1.4 (And I try too 1.3.5 and 1.3.7 with the same problem), I have "[REMOTE] readyState was interactive" for severals minutes...then a timeout.
Url is : http://sample.teads.net/demo/prod/qa.html

With 1.3.4 I have correct browsing : 

info: [debug] [REMOTE] {"__argument":{"WIRApplicationIdentifierKey":"PID:21670","WIRListingKey":{"1":{"WIRTitleKey":"Inread","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"http://sample.teads.net/demo/prod/qa.html","WIRPageIdentifierKey":1,"WIRConnectionIdentifierKey":"2a9981ee-e65c-4d54-9634-74f56248c560"}}},"__selector":"_rpc_applicationSentListing:"}
info: [debug] Remote debugger notified us of a new page listing
info: [debug] New page listing is same as old, doing nothing
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] {"__argument":{"WIRApplicationIdentifierKey":"PID:21655","WIRListingKey":{}},"__selector":"_rpc_applicationSentListing:"}
info: [debug] [REMOTE] New page listing did not match the app id we are currently using, ignoring
info: [debug] [REMOTE] Checking document readyState
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] readyState was complete
info: [debug] [REMOTE] Page is ready, calling onload cbs

But with > 1.4, I see the website display on the iOS 8.1 simulator, looks like loading is finish (reload button is here on Safari) but nothing happens, the second step of my script doesn't start and appium log are in a loop : 

info: [debug] [REMOTE] {"__argument":{"WIRApplicationIdentifierKey":"PID:22529","WIRListingKey":{"1":{"WIRTitleKey":"Inread","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"http://sample.teads.net/demo/prod/qa.html","WIRPageIdentifierKey":1,"WIRConnectionIdentifierKey":"0b2362a4-4095-4482-9337-213c56d983e4"}}},"__selector":"_rpc_applicationSentListing:"}
info: [debug] Remote debugger notified us of a new page listing
info: [debug] New page listing is same as old, doing nothing
info: [debug] [REMOTE] Checking document readyState
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] readyState was interactive
info: [debug] [REMOTE] Page was not ready, retrying
info: [debug] [REMOTE] Checking document readyState
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] readyState was interactive
info: [debug] [REMOTE] Page was not ready, retrying
info: [debug] [REMOTE] Checking document readyState
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] readyState was interactive
info: [debug] [REMOTE] Page was not ready, retrying
info: [debug] [REMOTE] Checking document readyState
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] readyState was interactive
info: [debug] [REMOTE] Page was not ready, retrying
info: [debug] [REMOTE] Checking document readyState
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] readyState was interactive
info: [debug] [REMOTE] Page was not ready, retrying
info: [debug] [REMOTE] Checking document readyState
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] readyState was interactive
info: [debug] [REMOTE] Page was not ready, retrying
info: [debug] [REMOTE] Checking document readyState
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] [REMOTE] readyState was interactive
info: [debug] [REMOTE] Page was not ready, retrying
info: [debug] [REMOTE] Checking document readyState
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
(and it's the same for a long time until timeout)

**Comment by imurchie** [comment]
Repeat. Closing.
