### ISSUE TITLE
I am not able to run iOS test without pre-launching an app. If I tried unchecking the pre-launch option , I get error that following desired capability is not provided :deviceName . But I have already provided them

### ISSUE THREAD

**Issue by ashwiniadke** [appium/appium#5143]
Creating this issue again as I didn't got any response for https://github.com/appium/appium/issues/5097

**Comment by sebv** [comment]
Please refer to doc here for new capabilities: http://appium.io/slate/en/master/?java#new-client-libraries

**Comment by sebv** [comment]
Closing, does not not look like  a bug, please go to https://discuss.appium.io/ for support.
