### ISSUE TITLE
Tap after fill an Textfield

### ISSUE THREAD

**Issue by norman784** [appium/appium#5144]
Hi

I've stuck trying to tap somewhere on the app after a Textfield is filled with a text

```
it("Tap", function () {
    var touch = new wd.TouchAction();

    touch.tap({x:115, y:269});

    driver
      .waitForElementById('com.test.app:id/autoCompleteTextView')
        .setText('726 Market Street, San Francisco, CA 94102, USA')
      .waitForElementById('com.test.app:id/autoCompleteTextView')
        .text().should.become('726 Market Street, San Francisco, CA 94102, USA')
      .perform(touch)
      .sleep(10000);
});
```

Seems that the tap sometimes not fired or fired before the text is filled, the reason I need to do this is b/c when the textfield is filled is shows a autocomplete where I need to select an item, but don't know why the list doesn't appear on the view xml on the inspector, so I don't know how to click/tap it, the only way I found was using TouchAction, but till now isn't working, another approach that try without luck was

```
it("Change Address", function () {
    driver
      .waitForElementById('com.test.app:id/autoCompleteTextView')
        .setText('726 Market Street, San Francisco, CA 94102, USA')
      .then(function () {

        var touch = new wd.TouchAction();

        touch
          .press({x:115, y:269})
          .release();

        return driver.perform(touch)
          .sleep(5000);
      })
      .waitForElementById('com.test.app:id/autoCompleteTextView')
        .text().should.become('726 Market Street, San Francisco, CA 94102, USA')
});
```

How can I accomplish it?

Using:
Android: 4.4.2
OS: OS X 10.10.3
Appium App (server): 1.3.7
Language: javascript

Regards

**Comment by imurchie** [comment]
This appears to be a bug in Android's UI Automator, which Appium uses under the hood. It does not seem to be able to find the `android.widget.AutoCompleteTextView` element that is created.

With a `TouchAction` you can click on the autocorrect dropdown, though the position of the elements may be dependent on screen size and whatnot. In your device you can turn on showing of touch coordinates, which might be of help.

**Comment by norman784** [comment]
Thanks for the reply, but I ended up hacking my app to work with the tests.

Regards

**Comment by imurchie** [comment]
Excellent! Care to share what you did? So we can expand our knowledge base?
