### ISSUE TITLE
Non-deterministic swipe behavior on Android

### ISSUE THREAD

**Issue by deadmoto** [appium/appium#5145]
I found an issue in either Appium or UIAutomator (more likely).
The problem is that when I use swipe action it scrolls different number of pixels every time.
It is frustrating when your tests use image comparison.
And it's more annoying because it cannot scroll exact number of pixels if its too little.
Thus when I try to scroll the screen by just 3 pixels down it scrolls  5, 9, 15 (it can be basically a random number within a certain range).
Could anyone confirm the problem?

**Comment by amedvedjev** [comment]
well we have similar issue when automating Google Map view inside application (both iOS and Android).
as workaround we use image comparison against several images. this increase result success dramatically :-)

example of our test steps:
1) open google view screen in application
2) do zoom in
3) capture needed image_1
4) steps 1,2 and compare against image_1 -> no match save image_2
5) steps 1,2 and compare against image_1 + image_2 -> no match save image_3
...

after 5-6 manual test tries we have 3-4 images that is match in 99% of times.
updating test with set of images and having high stability :-)

**Comment by Simon-Kaz** [comment]
@amedvedjev  do you use openCV? Tesseract? Sikuli? Your own wrapper for those?

**Comment by amedvedjev** [comment]
you got at first choice! opencv-2.4.10-0.9.1-20141109.113201-4-macosx-x86_64.jar

**Comment by Simon-Kaz** [comment]
I've been using sikuli as I only needed to create a quick prototype, but I'll definitely dig deeper and go for opencv directly!

**Comment by Fanch-** [comment]
Do you have also this issue with a high swipe duration ? Try with 5sec for example.

**Comment by deadmoto** [comment]
@Fanch- I tried to change swipe duration and swipe length.
When difference between startY and endY drops below certain value swipe action just stops working.
Example:
startY = 594, endY = 425 - woks (but element get shifted a few pixels)
startY = 417, endY = 425 - does not do anything

Also I tried to increase swipe path by swiping from the left edge to the right one.
It did not help either.

In logs Appium prints out proper coordinates when swipe action is called.

**Comment by amedvedjev** [comment]
@deadmoto why it is such a problem with different swipe?
BTW we have such problem ONLY with elements like google map. when we need precise scroll e.g. by 1/3 of page of some gallery or elements this working quite well.

**Comment by deadmoto** [comment]
@amedvedjev we need that to compare screenshots with baseline.
Even 1px shift fails the test.

**Comment by amedvedjev** [comment]
@deadmoto why not to use set of images? or let say 70% similarity?

**Comment by deadmoto** [comment]
@amedvedjev Because if we will set threshold higher than delta caused by swipe shift it may not detect small issues.
Moreover, precise scroll that gives deterministic results is not too much to ask :)

**Comment by sebv** [comment]
Moving this to bugs, let's revit this after the appium rewrite.

**Comment by deadmoto** [comment]
I have found a workaround that **does not** solve the problem completely but at least gives precise results.
Using arrow keys in Android causes screen to be scrolled to particular views.
Thus, I just use keyEvent KEYCODE_DPAD_DOWN and it scrolls the screen to the same position every time.

**Comment by SrinivasanTarget** [comment]
@triager please close
