### ISSUE TITLE
Unable to inspect in appium inspector and the appium get crashing , while launching the appium inspector

### ISSUE THREAD

**Issue by valarmathivrv** [appium/appium#5146]
1. I have installed appium 1.3.7 version in mac machine.
  2. I have started appium server for android app in android device.
  3.  In android device, the app get installed and opened successfully.
  4.  I have clicked the show inspector button and then I can able to see the inspector screen and then my appium inspector get crashed.
![063933c4-ef1b-11e4-9bb8-488bdae8d661](https://cloud.githubusercontent.com/assets/9842215/7746292/bb38634e-ffce-11e4-9566-b9f607476f58.png)
5. I have attached the screen shot below for reference.

**Comment by Jonahss** [comment]
Could you repost this issue on the github repository for the inspector? thanks.
