### ISSUE TITLE
Cannot read property 'x' of null on waiting

### ISSUE THREAD

**Issue by DmitryKa** [appium/appium#5147]
Updated appium: 1.3.6 to 1.4. And now when I do

    Appium::TouchAction.new.wait(3000).perform

(Ruby) I get error above.
Full log:

dmitry@dmitry-PC:~/Documents/appium/appium$ node .
info: Welcome to Appium v1.4.0 (REV dc30dae9e8fe8c85eeea707dbdbd60350fdff55b)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":999999,"platformName":"android","app":"/home/dmitry/Documents/appium/Secret-app.apk","deviceName":"Android","appWaitActivity":"com.secretapp.android.ui.activities.SignInActivity"}}                                                        
info: Client User-Agent string: appium/ruby_lib/6.0.0
info: [debug] No appActivity desired capability or server param. Parsing from apk.
info: [debug] No appPackage desired capability or server param. Parsing from apk.
info: [debug] Using local app from desired caps: /home/dmitry/Documents/appium/Secret-app.apk
info: [debug] Creating new appium session f36f2bf6-2dd7-4435-ac65-c747f1e5280c
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.8.0_31
info: [debug] Checking whether adb is present
info: [debug] Using adb from /home/dmitry/android-sdk-linux/platform-tools/adb
info: [debug] Parsing package and activity from app manifest
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /home/dmitry/android-sdk-linux/build-tools/22.0.1/aapt
info: [debug] Extracting package and launch activity from manifest.
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/build-tools/22.0.1/aapt dump badging /home/dmitry/Documents/appium/Secret-app.apk
info: [debug] badging package: com.secretapp.android.redesign
info: [debug] badging act: com.secretapp.android.ui.activities.MainActivity
info: [debug] Parsed package and activity are: com.secretapp.android.redesign/com.secretapp.android.ui.activities.MainActivity
info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb devices
info: [debug] 1 device(s) connected
info: Found device 192.168.56.101:5555
info: [debug] Setting device id to 192.168.56.101:5555
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 wait-for-device
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Getting device API level
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: Device API level is: 19
info: [debug] Extracting strings for language: default
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "getprop persist.sys.language"
info: [debug] Current device persist.sys.language: en
info: [debug] java -jar "/home/dmitry/Documents/appium/appium/node_modules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/home/dmitry/Documents/appium/Secret-app.apk" "/tmp/com.secretapp.android.redesign" en
info: [debug] No strings.xml for language 'en', getting default strings.xml
info: [debug] java -jar "/home/dmitry/Documents/appium/appium/node_modules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/home/dmitry/Documents/appium/Secret-app.apk" "/tmp/com.secretapp.android.redesign"
info: [debug] Reading strings from converted strings.json
info: [debug] Setting language to default
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 push "/tmp/com.secretapp.android.redesign/strings.json" /data/local/tmp
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /home/dmitry/android-sdk-linux/build-tools/22.0.1/aapt
info: [debug] Retrieving process from manifest.
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/build-tools/22.0.1/aapt dump xmltree /home/dmitry/Documents/appium/Secret-app.apk AndroidManifest.xml
info: [debug] Set app process to: com.secretapp.android.redesign
info: [debug] Not uninstalling app since server not started with --full-reset
info: [debug] Checking app cert for /home/dmitry/Documents/appium/Secret-app.apk.
info: [debug] executing cmd: java -jar /home/dmitry/Documents/appium/appium/node_modules/appium-adb/jars/verify.jar /home/dmitry/Documents/appium/Secret-app.apk
info: [debug] App already signed.
info: [debug] Zip-aligning /home/dmitry/Documents/appium/Secret-app.apk
info: [debug] Checking whether zipalign is present
info: [debug] Using zipalign from /home/dmitry/android-sdk-linux/build-tools/22.0.1/zipalign
info: [debug] Zip-aligning apk.
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/build-tools/22.0.1/zipalign -f 4 /home/dmitry/Documents/appium/Secret-app.apk /tmp/115421-6249-tka5b1/appium.tmp
info: [debug] MD5 for app is 427ff005e49305b45d2c56da4680f716
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "ls /data/local/tmp/427ff005e49305b45d2c56da4680f716.apk"
info: [debug] Getting install status for com.secretapp.android.redesign
info: [debug] Getting device API level
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "pm list packages -3 com.secretapp.android.redesign"
info: [debug] App is installed
info: App is already installed, resetting app
info: [debug] Running fast reset (stop and clear)
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "am force-stop com.secretapp.android.redesign"
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "pm clear com.secretapp.android.redesign"
info: [debug] Forwarding system:4724 to device:4724
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 forward tcp:4724 tcp:4724
info: [debug] Pushing appium bootstrap to device...
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 push "/home/dmitry/Documents/appium/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/
info: [debug] Pushing settings apk to device...
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 install "/home/dmitry/Documents/appium/appium/build/settings_apk/settings_apk-debug.apk"
info: [debug] Pushing unlock helper app to device...
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 install "/home/dmitry/Documents/appium/appium/build/unlock_apk/unlock_apk-debug.apk"
info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "ps 'uiautomator'"
info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.secretapp.android.redesign -e disableAndroidWatchers false
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] Waking up device if it's not alive
info: [debug] Pushing command to appium work queue: ["wake",{}]
info: [debug] [BOOTSTRAP] [debug] json loading complete.
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: wake
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "dumpsys window"
info: [debug] Screen already unlocked, continuing.
info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] dataDir set to: /data
info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data","status":0}
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
info: [debug] Getting device API level
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "getprop ro.build.version.sdk"
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.secretapp.android.redesign/com.secretapp.android.ui.activities.MainActivity"
info: [debug] Waiting for pkg "com.secretapp.android.redesign" and activity "com.secretapp.android.ui.activities.SignInActivity" to be focused
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "dumpsys window windows"
info: [debug] executing cmd: /home/dmitry/android-sdk-linux/platform-tools/adb -s 192.168.56.101:5555 shell "getprop ro.build.version.release"
info: [debug] Device is at release version 4.4.4
info: [debug] Device launched! Ready for commands
info: [debug] Setting command timeout to 999999 secs
info: [debug] Appium session started with sessionId f36f2bf6-2dd7-4435-ac65-c747f1e5280c
info: <-- POST /wd/hub/session 303 4885.479 ms - 74 
info: --> GET /wd/hub/session/f36f2bf6-2dd7-4435-ac65-c747f1e5280c {}
info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.4.4","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"newCommandTimeout":999999,"platformName":"android","app":"/home/dmitry/Documents/appium/Secret-app.apk","deviceName":"Android","appWaitActivity":"com.secretapp.android.ui.activities.SignInActivity"},"newCommandTimeout":999999,"platformName":"android","app":"/home/dmitry/Documents/appium/Secret-app.apk","deviceName":"192.168.56.101:5555","appWaitActivity":"com.secretapp.android.ui.activities.SignInActivity"},"sessionId":"f36f2bf6-2dd7-4435-ac65-c747f1e5280c"}
info: <-- GET /wd/hub/session/f36f2bf6-2dd7-4435-ac65-c747f1e5280c 200 4.644 ms - 769 {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.4.4","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"newCommandTimeout":999999,"platformName":"android","app":"/home/dmitry/Documents/appium/Secret-app.apk","deviceName":"Android","appWaitActivity":"com.secretapp.android.ui.activities.SignInActivity"},"newCommandTimeout":999999,"platformName":"android","app":"/home/dmitry/Documents/appium/Secret-app.apk","deviceName":"192.168.56.101:5555","appWaitActivity":"com.secretapp.android.ui.activities.SignInActivity"},"sessionId":"f36f2bf6-2dd7-4435-ac65-c747f1e5280c"}
info: --> POST /wd/hub/session/f36f2bf6-2dd7-4435-ac65-c747f1e5280c/timeouts/implicit_wait {"ms":30000}
info: [debug] Set Android implicit wait to 30000ms
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"f36f2bf6-2dd7-4435-ac65-c747f1e5280c"}
info: <-- POST /wd/hub/session/f36f2bf6-2dd7-4435-ac65-c747f1e5280c/timeouts/implicit_wait 200 2.001 ms - 76 {"status":0,"value":null,"sessionId":"f36f2bf6-2dd7-4435-ac65-c747f1e5280c"}

**error**
info: --> POST /wd/hub/session/f36f2bf6-2dd7-4435-ac65-c747f1e5280c/touch/perform {"actions":[{"action":"wait","options":{"ms":3000}}]}
info: <-- POST /wd/hub/session/f36f2bf6-2dd7-4435-ac65-c747f1e5280c/touch/perform 500 9.690 ms - 86 
TypeError: Cannot read property 'x' of null
    at /home/dmitry/Documents/appium/appium/lib/devices/android/android-controller.js:1108:34
    at Function._.each._.forEach (/home/dmitry/Documents/appium/appium/node_modules/underscore/underscore.js:153:9)
    at /home/dmitry/Documents/appium/appium/lib/devices/android/android-controller.js:1105:7
    at /home/dmitry/Documents/appium/appium/node_modules/async/lib/async.js:154:25
    at [object Object].<anonymous> (/home/dmitry/Documents/appium/appium/lib/devices/android/android-controller.js:1096:7)
    at iterate (/home/dmitry/Documents/appium/appium/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/home/dmitry/Documents/appium/appium/node_modules/async/lib/async.js:162:9)
    at [object Object].androidController.parseTouch (/home/dmitry/Documents/appium/appium/lib/devices/android/android-controller.js:1038:9)
    at [object Object].<anonymous> (/home/dmitry/Documents/appium/appium/lib/devices/android/android-controller.js:1020:12)
    at [object Object].<anonymous> (/home/dmitry/Documents/appium/appium/lib/devices/android/android-controller.js:960:5)
    at [object Object].androidController.performTouch (/home/dmitry/Documents/appium/appium/lib/devices/android/android-controller.js:1018:5)
    at exports.performTouch (/home/dmitry/Documents/appium/appium/lib/server/controller.js:337:14)
    at Layer.handle [as handle_request] (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/layer.js:82:5)
    at /home/dmitry/Documents/appium/appium/node_modules/express/lib/router/index.js:267:22
    at param (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/index.js:340:14)
    at param (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/index.js:356:14)
    at Function.proto.process_params (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/index.js:400:3)
    at next (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/index.js:261:10)
    at next (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/route.js:100:14)
    at next (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/home/dmitry/Documents/appium/appium/node_modules/express/lib/router/route.js:104:14)

seems other commands work fine, but this command produces error.

**Comment by imurchie** [comment]
Why are you trying to do a `wait` without any other commands? You need to `press` before you can `wait` (both logically, and, apparently, programmatically).

**Comment by DmitryKa** [comment]
@imurchie I use this command to just wait some seconds for my app reaction, not only after press. It worked, and worked fine earlier.

**Comment by imurchie** [comment]
Interesting. There has been some refactoring of that code, and that is a use case that we hadn't thought of. That said, it is not a good pattern, and my "fix" would be to throw an error earlier, saying that you can't do that!

Selenium has an api for waiting that should be used instead. I'm not sure of the exact usage in Ruby, but the official documentation is [here](http://docs.seleniumhq.org/docs/04_webdriver_advanced.jsp).

**Comment by DmitryKa** [comment]
Sorry, but https://www.dropbox.com/s/uqlyuhocn9diril/Screenshot-2015-05-22-22.05.14.png?dl=0

**Comment by imurchie** [comment]
Well... I guess google "Selenium wait"?

**Comment by DmitryKa** [comment]
Thx. Seems `Selenium::WebDriver::Wait.new(timeout: 5).until {}` solves this problem
