### ISSUE TITLE
Understanding the types of IOSElements

### ISSUE THREAD

**Issue by tolgatanriverdi** [appium/appium#5148]
Hi
I'm running appium server in my mac os x for IOS tests and everything seems ok while installing and running tests on real device
However when I try to get all the elements in the screen with the below method. It returns list of IOSElement objects , but from that point I dont know how to understand which element is TextField which element is a Button etc...

 List<WebElement> elements = driver.findElementsByIosUIAutomation(".elements()");

Aynone has any idea about it?

Thanks

**Comment by imurchie** [comment]
Perhaps `List elements = driver.findElementsByIosUIAutomation(".elements()");` is too broad. You can use one of the other selectors (find by class name, for instance, will allow you to find `UIATextField` elements), or UI Automation code that is more exact.

**Comment by tolgatanriverdi** [comment]
How can i find the all elements in a screen and find out which one is UIATextField and which one is UIAButton

**Comment by imurchie** [comment]
What is the use case for doing that?

You can get the page source, which will be an xml document, and parse that for the information you need. All the elements will be there, with their class and attributes.

**Comment by tolgatanriverdi** [comment]
Use case is getting all the elements in a screen of an application which I dont have access to source code
So I can run tests on ipa files(compiled in debug mode) which I dont have the source code

**Comment by imurchie** [comment]
Using `driver.source()` (or the similar command for your language) will give you access to the hierarchy for the view.

**Comment by tolgatanriverdi** [comment]
Thanks that solved my problem
and the answer for java is driver.getPageSource() method
