### ISSUE TITLE
Travis -> Appium Instruments crash exit code 250 

### ISSUE THREAD

**Issue by apallin** [appium/appium#5150]
While trying to execute Appium Code against Sauce Labs simulators for iOS I am having trouble with instruments crashing (go figure). However, this seems to be a pretty reproducible in one configuration where we are having Travis CI trigger a sauce labs test and execute the test code as part of a CI run.

Appium Logs:
134562015-05-13 01:06:26:249 - info: [debug] [INST STDERR] Instruments Trace Error : Failed to load document 'file:///tmp/appium-instruments/instrumentscli0.trace' : (Error Domain=com.apple.instruments Code=-6 "Document Missing Template Error: The operation couldnât be completed. (com.apple.instruments error -6.)")
134572015-05-13 01:06:26:290 - info: [debug] [INSTSERVER] Instruments exited with code 250
134582015-05-13 01:06:26:290 - info: [debug] Killall instruments
134592015-05-13 01:06:26:294 - info: [debug] Instruments crashed on startup
134602015-05-13 01:06:26:294 - info: [debug] Attempting to retry launching instruments, this is retry #2
134612015-05-13 01:06:26:294 - info: [debug] Killall iOS Simulator

I can include more Appium logs for sure but I am not aware of an easy way to get some of these logs in. Any help is appreciated.

**Comment by apallin** [comment]
More logs of the same crash.  This happens so frequently and it hoses all other test runs against the same VM's.

141562015-05-21 23:11:33:926 - info: [debug] [INST STDERR] Instruments Trace Error : Failed to load document 'file:///tmp/appium-instruments/instrumentscli0.trace' : (Error Domain=com.apple.instruments Code=-6 "Document Missing Template Error: The operation couldnât be completed. (com.apple.instruments error -6.)")
141572015-05-21 23:11:33:978 - info: [debug] [INSTSERVER] Instruments exited with code 250
141582015-05-21 23:11:33:978 - info: [debug] Killall instruments
141592015-05-21 23:11:33:990 - info: [debug] Instruments crashed on startup
141602015-05-21 23:11:33:990 - info: [debug] Attempting to retry launching instruments, this is retry #1
141612015-05-21 23:11:33:990 - info: [debug] Killall iOS Simulator
141622015-05-21 23:11:34:003 - info: [IOS_SYSLOG_ROW ] May 21 16:11:33 itako48019.prod.miso DTMobileIS[1868]: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
141632015-05-21 23:11:34:004 - info: [IOS_SYSLOG_ROW ] May 21 16:11:33 itako48019.prod.miso DTMobileIS[1868]: Could not create service named com.apple.instruments.server.services.launchdaemon
141642015-05-21 23:11:34:035 - info: [debug] [INSTSERVER] Instruments exited with code null
141652015-05-21 23:11:34:035 - info: [debug] Killall instruments
141662015-05-21 23:11:34:044 - info: [debug] Instruments crashed on startup
141672015-05-21 23:11:34:044 - info: [debug] Attempting to retry launching instruments, this is retry #2
141682015-05-21 23:11:34:044 - info: [debug] Killall iOS Simulator

**Comment by jlipps** [comment]
interesting. I'd like to take a look at the full logs. @apallin since this took place on Sauce, can you ping help@saucelabs.com and notify them that I sent you there? Include a link to your test. This way the Sauce support team can track it and they can direct it to me internally, so we'll take it from there. Apologies for the runaround, it looks like this may indeed be a Sauce-specific issue.
