### ISSUE TITLE
Is it possible to xpath to find webelenent on Android?

### ISSUE THREAD

**Issue by glebPrischepa** [appium/appium#5151]
Hey,

I am using Appium server 1.4.0 and io.appium java-client version 2.2.0 and developing tests for Android.

I cannot get xpath of WebElement using such construction
final String xpath = mobileElement.getAttribute("xpath");

In Appium Terminal I see

> info: [debug] Pushing command to appium work queue: ["element:getAttribute",{"elementId":"22","attribute":"xpath"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getAttribute","params":{"elementId":"22","attribute":"xpath"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getAttribute
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"This element does not have the 'xpath' attribute","status":7}
> info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":"This element does not have the 'xpath' attribute"},"sessionId":"855591e0-a1a8-4ef1-892a-b40b253e7527"}

Is it possible to use xpath for Android?

Thanks in advance

**Comment by vikaspune** [comment]
Hi Gleb,
I think you cant get xpath of element from WebElement. but If you already have WebElement object they you are are trying yo get it's locator?

If you wanted to access the parent element of current element you can use below code.

// .. refers to parent
WebElement parent = mobileElement.findElement(By.xpath("//.."))

**Comment by glebPrischepa** [comment]
Hi,

WebElement parent = mobileElement.findElement(By.xpath("//.."))
throws InvokationTargetException

in Console
> info: --> POST /wd/hub/session/c1ebab6e-cfb4-4f19-88c7-e96916f111b8/element/22/element {"id":"22","using":"xpath","value":"//.."}
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Cannot use xpath locator strategy from an element. It can only be used from the root element)","origValue":"Cannot use xpath locator strategy from an element. It can only be used from the root element"},"sessionId":"c1ebab6e-cfb4-4f19-88c7-e96916f111b8"}
> info: <-- POST /wd/hub/session/c1ebab6e-cfb4-4f19-88c7-e96916f111b8/element/22/element 500 2.204 ms - 372 


Any ideas?

**Comment by vikaspune** [comment]
Thanks for your above information.
I did research on this and realized you can not find element by calling element.findElement(By.xpath("")) You only have to use driver.findElementByXpath("") but in your case this is not useful.

I found a way to get parent element. It's using UIAutomator script with Appium.

Please go through below link 
http://stackoverflow.com/questions/17680352/how-can-i-get-the-parent-of-a-view-using-uiautomator/17740212#17740212

You will just need little knowledge about UIAutomator script. Sadly I am also new to UIAutomator script.

**Comment by glebPrischepa** [comment]
Cool, Thanks!
I will try.

Any ideas about
https://github.com/appium/appium/issues/5152
?

**Comment by sebv** [comment]
Please use appium discuss for this kind of issues.
https://discuss.appium.io/
