### ISSUE TITLE
Is it possible to send keys to input by one letter?

### ISSUE THREAD

**Issue by glebPrischepa** [appium/appium#5152]
Hi, all,

I am developing tests for Android.
When I use .sendKeys methods it replaces previous text.

My goal is to imitate typing in software keyboard like
A
An
And
Andr
Andro
Androi
Android

I checked log in Appium Terminal and found
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"12","text":"A","replace":false}}

It appears that .sendKeys method should not replace previous text and should append to existed but It replaces.

Any ideas?

Thanks in advance.

**Comment by imurchie** [comment]
Unfortunately that is not how Android UI Automator wants us to handle text. It does not entirely simulate typing on a keyboard.

To do that, you will need to use key events. This will trigger all the delegation in your app, as well.

The `KeyEvent` and key codes are available in [Android's Documentation](http://developer.android.com/reference/android/view/KeyEvent.html). In Appium, you just need to call `pressKeyCode` (the name will vary depending on the client being used) with each desired keycode. For JavaScript using `wd`, typing "Android" will look like

```javascript
element
    .pressDeviceKey(29, 193) // A
    .pressDeviceKey(42)         // n
    .pressDeviceKey(32)         // d
    .pressDeviceKey(46)         // r
    .pressDeviceKey(43)         // o
    .pressDeviceKey(37)         // i
    .pressDeviceKey(32);        // d
```

If you are using Java you can use the `KeyEvent` constants.

```java
driver..sendKeyEvent(KeyEvent.KEYCODE_A, KeyEvent.META_SHIFT_ON);
driver..sendKeyEvent(KeyEvent.KEYCODE_N);
driver..sendKeyEvent(KeyEvent.KEYCODE_D);
driver..sendKeyEvent(KeyEvent.KEYCODE_R);
driver..sendKeyEvent(KeyEvent.KEYCODE_O);
driver..sendKeyEvent(KeyEvent.KEYCODE_I);
driver..sendKeyEvent(KeyEvent.KEYCODE_D);
```

**Comment by sebv** [comment]
Closing, please try solution above. This kind of issue is better addressed in appium discuss: https://discuss.appium.io/
