### ISSUE TITLE
Appium pushed remote APK into temp and never clean it up, resulted /tmp filesystem full and killed appium process

### ISSUE THREAD

**Issue by KyleChihCheng** [appium/appium#5156]
Hi,

I am a newbie of Appium. Please tell me how does Appium clean up the temporary APK files, it seems keep generating new folders that contained APK file until it ran out of space (my /tmp filesystem is 3 GB)

Is the cleanup configurable or I am using appium switches wrong. Pardon my formatting since this is my first post.

Version: 1.3.4
Option: appium --session-override --strict-caps --selendroid-port 8081 --nodeconfig $config --log $log &
Capabilities:
android.json 
{
"capabilities":
[
{
"automationName": "Appium",
"maxInstances": 1,
"platformName": "Android",
"platformVersion": "4.4",
"version": ""
},
{
"automationName": "Selendroid",
"maxInstances": 1,
"platformName": "Android",
"platformVersion": "4.4",
"version": ""
}
],
"configuration":
{
"cleanUpCycle": 2000,
"timeout": 30000,
"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
"url": "http://testslave10.blah.com:4723/wd/hub",
"maxSession": 1,
"port": 4723,
"host": "testslave10.blah.com",
"role": "node",
"register": true,
"registerCycle": 5000,
"hubPort": 4444,
"hubHost": "sselenium02.blah.com"
}
}

115418-5676-19twpek/ 115418-5676-1ighx8i/ 115418-5676-1x3arys/ 115418-5676-c01omk/ 115418-5676-fd6ove/
115418-7031-1ksddt1/ 115418-7031-1nujis0/ 115418-7031-93a58d/ 1431128691242.tmp 
115418-5676-1etr8cr/ 115418-5676-1rss2sx/ 115418-5676-1ycrffy/ 115418-5676-fbzeha/ 115418-7031-14zi9o2/ 115418-7031-1nnikhw/ 115418-7031-8dp4z6/ 115418-7031-upx7re/
[jenkins@testslave10 tmp]$ ls -al /tmp/115418-*
/tmp/115418-5676-19twpek:
total 19424
drwxr-xr-x 2 jenkins jenkins 4096 May 18 11:17 .
drwxrwxrwt 23 root root 135168 May 18 14:11 ..
-rw-r--r-- 1 jenkins jenkins 19721910 May 18 11:17 appium-app.apk

   capabilities.setCapability(MobileCapabilityType.APP, ARTIFACTORY_URL);

Since there is no reply, I temporary made a jenkins post build shell that cleaned those temp folders
![screen shot 2015-05-22 at 1 09 37 pm](https://cloud.githubusercontent.com/assets/305111/7778811/de5d4fc8-0083-11e5-95bd-7d535ab580b8.png)

Please help, I posted this to https://discuss.appium.io but zero response.

**Comment by imurchie** [comment]
At the moment temp file management is not handled by Appium. It seems like something it _could_ do, though, so I'm adding this as a feature request.

**Comment by losttime** [comment]
We're running into this as an issue too. Any updates on priority for this feature?

**Comment by alewang** [comment]
I'm also running into this problem as well.

**Comment by alewang** [comment]
I made a workaround for Linux systems.

I first set up Appium and the Android libraries under a basic user that I named `appium`. For my Debian system, I had to add this user to the `audio` user group in order for adb to have access my Android devices (udev grants access to the audio user group to my devices).

I then added a cron job for the script below to run every 15 minutes. The script below recursively deletes any directories or files owned by the running user under /tmp that are older than 60 minutes.

`#!/usr/bin/env bash

# Beware that this script will delete everything that is owned by
# the user running this script

shopt -s nullglob

TMP_DIR=/tmp

exceptions=( webdriver )

cd $TMP_DIR
for tmp_file in *; do
    # Inefficient: Loop embedded in loop, but we hopefully have
    # only a few files to work with, right?
    exception_found="false"
    for except in $exceptions; do
        if [ "$except" == "$tmp_file" ]; then
            exception_found="true"
            break
        fi  
    done

    if [ "$exception_found" != "false" ]; then
        continue
    fi  

    if [ -O "$tmp_file" ] && [ "$(find $tmp_file -maxdepth 0 -mmin +60)" ]; then
        rm -rf $tmp_file
    fi  
done`

**Comment by jlipps** [comment]
the overall problem here (temp file management) is also described in #3179. work for both of these should be done at the same time, or these issues should consolidated into one.

**Comment by mykola-mokhnach** [comment]
Setting `clearSystemFiles` capability to `true` does the job
