### ISSUE TITLE
Is browsermob proxy supports MobileApp

### ISSUE THREAD

**Issue by karunakaranvrv** [appium/appium#5157]
@jlipps I am writing automation test for Mobileweb and Android/iOS app.

Using https://github.com/lightbody/browsermob-proxy to capture network responses for MobileWeb.
I want to do same for MobileApp. Is it possible?  or Where i need to post  this question to get answer for it?

Proxy code used in mobileweb:-

ProxyServer proxyServer = new ProxyServer(4444);
proxyServer.start();

Proxy proxy = proxyServer.seleniumProxy();
DesiredCapabilities capabillities = DesiredCapabilities.firefox();
capabillities.setCapability(CapabilityType.PROXY, proxy);
capabillities.setCapability("version", "5");
capabillities.setCapability("platform", Platform.XP);
this.driver = new RemoteWebDriver(
new URL("http://myname:xxxxxx@ondemand.saucelabs.com:80/wd/hub"),
capabillities);

I can able to setup proxy for mobileweb test. How can i do the same for mobile app testing.

Is above code supports mobile app?

Kindly respond me.

**Comment by sebv** [comment]
I guess so, the proxying is client side.

**Comment by sebv** [comment]
Closing, client side issue.

**Comment by jatinkapoor** [comment]
@jlipps  i am trying to accomplish the same - using appium to drive the native app on the android device and browsermob proxy to capture the network traffic .  But so far i haven't had too much success. I tried doing it manually using Charles proxy and it worked but with appium and browsermob proxy I am not able to make a connection between device and proxy server. 
I also made my device point to the proxy server before hand but i dont think it is able to make the connection.
Here's my code -

                BrowserMobProxy server = new BrowserMobProxyServer();
		server.start(5555);
		Proxy proxy = ClientUtil.createSeleniumProxy(server);
		DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
		desiredCapabilities.setCapability("automationName", "Appium");
		desiredCapabilities.setCapability("platformName", "Android");
		desiredCapabilities.setCapability(CapabilityType.PROXY, proxy);
		desiredCapabilities.setCapability("platformVersion", "5.1.1");
		desiredCapabilities.setCapability("deviceName", "JK");		
		desiredCapabilities.setCapability("app", "C:/testapp/com.xxxxx.android.apk");
		desiredCapabilities.setCapability("appPackage", "com.xxxxx.android");
		desiredCapabilities.setCapability("appActivity", "activities.home.HomeActivity");
		desiredCapabilities.setCapability("noReset",false);
		server.newHar("newHar");
		AndroidDriver driver;
		try {
			driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), desiredCapabilities);

			driver.manage().timeouts().implicitlyWait(180, TimeUnit.SECONDS);
			Har har = server.getHar();
			HarLog log = har.getLog();
			List<HarEntry> entries = new CopyOnWriteArrayList<HarEntry>(log.getEntries());
			System.out.println(entries);
			for (HarEntry entry : entries){
				System.out.println(entry.getRequest().getUrl());
			}

		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		server.stop();
	}


Any help would be appreciated.

**Comment by pm-ayush-kulshrestha** [comment]
i am also facing the same problem i am not able to capture http traffic using browserMob Proxy please help

**Comment by narulacool** [comment]
any success here? Kindly help I am also stuck.

**Comment by diwesh-anandpara** [comment]
any luck guys? still am looking for solution on this

**Comment by ShubamRade92** [comment]
i am also facing the same problem i am not able to capture http traffic using browserMob Proxy for android web app please help .
I am getting empty har file.

Here is my code for Android device
*************************************************************************
package Soaktesting;

import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Proxy;
import org.openqa.selenium.Proxy.ProxyType;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.FindBy;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import net.lightbody.bmp.BrowserMobProxy;
import net.lightbody.bmp.BrowserMobProxyServer;
import net.lightbody.bmp.client.ClientUtil;
import net.lightbody.bmp.core.har.Har;
import net.lightbody.bmp.proxy.CaptureType;

public class SoakTest_Mobile {
	
	@FindBy(xpath="//*[@id='position']") public WebElement CurrentTime;
	@FindBy(xpath="//span[@id=\"currentStreamName1\"]") public WebElement playback;
	@FindBy(xpath="//*[@id='pause']") public WebElement play;
	@FindBy(xpath="//*[@id='btnCloseStreamsPanel']/i") WebElement closePlayback;
	
		
	public Calendar calendar = Calendar.getInstance();
	public SimpleDateFormat formater = new SimpleDateFormat("dd_MM_yyyy_hh_mm_ss");
	String sFileName = "D:/Sliq Media/MemoryLeak data/SoakTestMobile" + formater.format(calendar.getTime()) + ".har";
	
	public WebDriver driver;
	public BrowserMobProxy proxy;
		
	@BeforeTest
	public void setUp() throws MalformedURLException {
		
	   // start the proxy
	    proxy = new BrowserMobProxyServer();
	    proxy.setTrustAllServers(true);
	    proxy.start(0);

	    Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);
	    System.out.println(seleniumProxy);
		seleniumProxy.setProxyType(ProxyType.MANUAL);

		seleniumProxy.setSslProxy("trustAllSSLCertificates");

	    // configure it as a desired capability
	    DesiredCapabilities capabilities = new DesiredCapabilities();
	    capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);
	    capabilities.setCapability("deviceName", "Samsung Tab S2");
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability("platformVersion", "7.0");
		capabilities.setCapability("noReset", "True");
		capabilities.setCapability("udid", "3300e73fe6538235");
		capabilities.setCapability("browserName", "Chrome");
		
	    
		driver = new RemoteWebDriver(new URL("http://127.0.0.1:4727/wd/hub"), capabilities);

		driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);

	    proxy.enableHarCaptureTypes(CaptureType.REQUEST_CONTENT, CaptureType.RESPONSE_CONTENT);


	    proxy.newHar("SliqSoakTest_SamsungTabS2.com");


	    driver.get("https://www.youtube.com/watch?v=FYzton89PWU");     
	
	}
	
	@Test
	public void testCaseOne() throws InterruptedException {
		Thread.sleep(15000);
		
		for(int j=0; j<5;j++ )
		{
		driver.navigate().refresh();
		Thread.sleep(15000);
		driver.findElement(By.xpath("//*[@id='play']")).click();
		Thread.sleep(10000);
		for(int i=0; i<50;i++)
			{
				String temp = driver.findElement(By.xpath("//*[@id='position']")).getText();	

				System.out.println("Time before increment is : "+temp);

				Thread.sleep(30000);
				String temp2 = driver.findElement(By.xpath("//*[@id='position']")).getText();
				System.out.println("Time after increment by 30sec is : "+temp2);

				if(temp.equalsIgnoreCase(temp2))
				{

					System.out.println("Video not incremented by 30sec");
					Assert.assertFalse(temp.equalsIgnoreCase(temp2));
				}
				else
				{

					System.out.println("Video incremented by 30sec");
				}
				
			}
		}
		
	}
	
	@AfterTest
	public void tearDown() {

		// get the HAR data
		Har har = proxy.getHar();

		// Write HAR Data in a File
		File harFile = new File(sFileName);
		try {
			har.writeTo(harFile);
			} 
		catch (IOException ex) {
			 System.out.println (ex.toString());
		     System.out.println("Could not find file " + sFileName);
		}
		
		if (driver != null) {
			proxy.stop();
			driver.quit();
		}
	}
}

Please help...
