### ISSUE TITLE
Could not pre-launch appium 

### ISSUE THREAD

**Issue by valarmathivrv** [appium/appium#5158]
1. I am using Xcode Version 6.3.2 and appium version 1.3.7.
2. I am getting below defined error message, When I start appium server

Error Log:

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --pre-launch --platform-version "7.1.2" --platform-name "iOS" --app "com.vr.iphone.sampleApp" --udid "1c71d40a38f94c9e6682f5409e6ea6c0ec081736" --show-ios-log --device-name "iPhone 5s" --isolate-sim-device

info: [debug] Starting Appium in pre-launch mode

info: Pre-launching app

info: [debug] App is an iOS bundle, will attempt to run as pre-existing
info: [debug] Creating new appium session a917afac-a070-4099-882d-5a3b0617a36c

info: [debug] Removing any remaining instruments sockets

info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode folder

info: [debug] Setting Xcode version

info: [debug] Setting iOS SDK Version

info: [debug] Getting sdk version from xcrun with a timeout

info: [debug] iOS SDK Version set to 8.3

info: [debug] Not checking whether simulator is available since we're on a real device
info: [debug] Detecting automation tracetemplate

info: [debug] Not auto-detecting udid, running on sim

info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vr.iphone.sampleApp/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.vr.iphone.sampleApp/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Creating instruments
info: On some xcode 6 platforms, instruments-without-delay does not work. If you experience this, you will need to re-run appium with the --native-instruments-lib flag
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/al/Library/Application Support/appium/bootstrap

info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/al/Library/Application Support/appium/bootstrap/bootstrap-d5a0fb924946d8d3.js
info: [debug] Reusing dynamic bootstrap: /Users/al/Library/Application Support/appium/bootstrap/bootstrap-d5a0fb924946d8d3.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.3.2","iOSSDKVersion":"8.3","deviceName":"iPhone 5s","platformVersion":"7.1.2"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 5s (7.1.2 Simulator)'
info: [debug] Not setting device type since we're on a real device
info: [debug] Checking whether we need to set app preferences
info: [debug] Not setting iOS and app preferences since we're on a real device
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator

info: [debug] Killing any other simulator daemons

info: [debug] On a real device; cannot clean device state

info: [debug] Not setting locale because we're using a real device
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS device log capture via deviceconsole

info: [debug] Not pre-launching simulator

info: [debug] Creating iDevice object with udid 1c71d40a38f94c9e6682f5409e6ea6c0ec081736
info: [debug] Checking app install status using: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/fruitstrap/fruitstrap isInstalled --id 1c71d40a38f94c9e6682f5409e6ea6c0ec081736 --bundle com.com.vr.iphone.sampleApp

info: [debug] App is not installed. Will try to install the app.

info: [debug] Installing app using cmd: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/fruitstrap/fruitstrap install --id 1c71d40a38f94c9e6682f5409e6ea6c0ec081736 --bundle "com.vr.iphone.sampleApp"

info: [IOS_SYSLOG_ROW ] May 23 16:45:23 P-v-iphone-5s lockdownd[25] <Notice>: 01bcc000 -[watchedServiceInfo logService:]: Freeing heartbeat <watchedServiceInfo: 0x13ce22890> [client=fruitstrap (F0FE931A-0099-4F10-932A-FAE4065DF358 fe80::6e40:8ff:fea6:b9a:457)] [fd=12] [pid=116 (mobile_installation_proxy fd=5)] [hb=59291375123]

info: [IOS_SYSLOG_ROW ] May 23 16:45:23 P-v-iphone-5s lockdownd[25] <Notice>: 01bcc000 -[watchedServiceInfo logService:]: last service <watchedServiceInfo: 0x13ce22890> [client=fruitstrap (F0FE931A-0099-4F10-932A-FAE4065DF358 fe80::6e40:8ff:fea6:b9a:457)] [fd=12] [pid=116 (mobile_installation_proxy fd=5)] [hb=59291375123]
info: [IOS_SYSLOG_ROW ] May 23 16:45:23 P-v-iphone-5s lockdownd[25] <Notice>: 01f84000 -[hostWatcher runWatcher]: ended loop for <hostWatcher: 0x13ce14de0> [F0FE931A-0099-4F10-932A-FAE4065DF358 fe80::6e40:8ff:fea6:b9a:60872] [fd=14]
info: [IOS_SYSLOG_ROW ] May 23 16:45:23 P-v-iphone-5s lockdownd[25] <Notice>: 01bcc000 -[watchedServiceInfo logService:]: dealloc <watchedServiceInfo: 0x13ce22890> [client=fruitstrap (F0FE931A-0099-4F10-932A-FAE4065DF358 fe80::6e40:8ff:fea6:b9a:457)] [fd=12] [pid=116 (mobile_installation_proxy fd=5)] [hb=59291375123]

info: [IOS_SYSLOG_ROW ] May 23 16:45:23 P-v-iphone-5s lockdownd[25] <Notice>: 01bcc000 -[watchedServiceInfo logService:]: first service <watchedServiceInfo: 0x13ce228c0> [client=fruitstrap (F0FE931A-0099-4F10-932A-FAE4065DF358 fe80::6e40:8ff:fea6:b9a:1225)] [fd=12] [pid=101 (afcd fd=8)] [hb=59308567985]
info: [IOS_SYSLOG_ROW ] May 23 16:45:23 P-v-iphone-5s lockdownd[25] <Notice>: 01bcc000 -[watchedServiceInfo logService:]: Watching <watchedServiceInfo: 0x13ce228c0> [client=fruitstrap (F0FE931A-0099-4F10-932A-FAE4065DF358 fe80::6e40:8ff:fea6:b9a:1225)] [fd=12] [pid=101 (afcd fd=8)] [hb=59308567985]
info: [IOS_SYSLOG_ROW ] May 23 16:45:23 P-v-iphone-5s lockdownd[25] <Notice>: 01efc000 -[hostWatcher runWatcher]: starting loop for <hostWatcher: 0x13ce14de0> [F0FE931A-0099-4F10-932A-FAE4065DF358 fe80::6e40:8ff:fea6:b9a:60872] [fd=14]
info: [IOS_SYSLOG_ROW ] May 23 16:45:23 P-v-iphone-5s lockdownd[25] <Notice>: 01bcc000 -[watchedServiceInfo logService:]: Freeing heartbeat <watchedServiceInfo: 0x13ce228c0> [client=fruitstrap (F0FE931A-0099-4F10-932A-FAE4065DF358 fe80::6e40:8ff:fea6:b9a:1225)] [fd=12] [pid=101 (afcd fd=8)] [hb=59308567985]
info: [IOS_SYSLOG_ROW ] May 23 16:45:23 P-v-iphone-5s lockdownd[25] <Notice>: 01bcc000 -[watchedServiceInfo logService:]: last service <watchedServiceInfo: 0x13ce228c0> [client=fruitstrap (F0FE931A-0099-4F10-932A-FAE4065DF358 fe80::6e40:8ff:fea6:b9a:1225)] [fd=12] [pid=101 (afcd fd=8)] [hb=59308567985]

info: [IOS_SYSLOG_ROW ] May 23 16:45:23 P-v-iphone-5s lockdownd[25] <Notice>: 01efc000 -[hostWatcher runWatcher]: ended loop for <hostWatcher: 0x13ce14de0> [F0FE931A-0099-4F10-932A-FAE4065DF358 fe80::6e40:8ff:fea6:b9a:60872] [fd=14]
info: [IOS_SYSLOG_ROW ] May 23 16:45:23 P-v-iphone-5s lockdownd[25] <Notice>: 01bcc000 -[watchedServiceInfo logService:]: dealloc <watchedServiceInfo: 0x13ce228c0> [client=fruitstrap (F0FE931A-0099-4F10-932A-FAE4065DF358 fe80::6e40:8ff:fea6:b9a:1225)] [fd=12] [pid=101 (afcd fd=8)] [hb=59308567985]

info: [debug] Cleaning up appium session

error: Could not pre-launch appium: Error: Unable to install [com.vr.iphone.sampleApp] to device with id [1c71d40a38f94c9e6682f5409e6ea6c0ec081736]. Error [Error: Command failed: /bin/sh -c /Applications/Appium.app/Contents/Resources/node_modules/appium/build/fruitstrap/fruitstrap install --id 1c71d40a38f94c9e6682f5409e6ea6c0ec081736 --bundle "com.vr.iphone.sampleApp"
Assertion failed: (access(app_path, F_OK) == 0), function main, file fruitstrap.c, line 718.
]

**Comment by sebv** [comment]
Looks like the app cannot be installed, try to automate the app with instruments first.

**Comment by valarmathivrv** [comment]
@sebv , I have  tried with instruments also,but I can't able to inspect the iOS app.

**Comment by sebv** [comment]
It's just your app is not compatible with instrument, you need a debug build.

**Comment by moizjv** [comment]
Closing this issue, as it does not seem to be an appium issue.
