### ISSUE TITLE
Appium identification methods

### ISSUE THREAD

**Issue by Tekin1** [appium/appium#5159]
Hi, i hope anyone here can help me. I am Writing my Final exam and evaluationg the three tool experitest, appium and monkeytalk.
And i am trying to find out which identification methdos appium can use.

Native ID
Web HTML5(DOM) commands
Image recognition
OCR (text recognition) <-- i know that appium can use OCR

**Comment by Tekin1** [comment]
Has no one a answer?

**Comment by moizjv** [comment]
@Tekin1 ideally you should be asking questions in [forum](http://discuss.appium.io) this space is for raising and tracking defects. Please go through our [documentation](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/finding-elements.md) . Thanks
