### ISSUE TITLE
Android - Webview cannot read property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by Henry-Gao** [appium/appium#5160]
I can successfully switch to the window handle and I also change the context to webview, however, when i do a document.getElementsByClassName('title')[0].innerHTML; I get the following error. 

[36minfo[39m: [debug] Responding to client with success: {"status":0,"value":"WEBVIEW_com.fivemobile.thescore.debug","sessionId":"e516cba4-2577-472f-86dd-8c5f7ca8179a"}
[36minfo[39m: [37m<-- GET /wd/hub/session/e516cba4-2577-472f-86dd-8c5f7ca8179a/context [39m[32m200[39m[90m 0.980 ms - 111[39m [90m{"status":0,"value":"WEBVIEW_com.fivemobile.thescore.debug","sessionId":"e516cba4-2577-472f-86dd-8c5f7ca8179a"}[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/e516cba4-2577-472f-86dd-8c5f7ca8179a/execute[39m [90m{"script":"return document.getElementsByClassName('story-digest-heading')[0].innerHTML;","args":[""]}[39m
[36minfo[39m: Proxying [POST /wd/hub/session/e516cba4-2577-472f-86dd-8c5f7ca8179a/execute] to [POST http://127.0.0.1:9515/wd/hub/session/c5491ed42767d386bfa37abfd3194b3d/execute] with body: {"script":"return document.getElementsByClassName('story-digest-heading')[0].innerHTML;","args":[""]}
[36minfo[39m: Got response with status 200: {"sessionId":"c5491ed42767d386bfa37abfd3194b3d","status":13,"value":{"message":"unknown error: Cannot read property 'innerHTML' of undefined\n  (Session info: webview=)\n  (Driver info: chromedriver=2...
[36minfo[39m: [37m<-- POST /wd/hub/session/e516cba4-2577-472f-86dd-8c5f7ca8179a/execute [39m[32m200[39m[90m 30.726 ms - 290[39m [90m[39m
[36minfo[39m: [37m-->[39m [37mGET[39m [37m/wd/hub/session/e516cba4-2577-472f-86dd-8c5f7ca8179a/screenshot[39m [90m{}[39m
[36minfo[39m: Proxying [GET /wd/hub/session/e516cba4-2577-472f-86dd-8c5f7ca8179a/screenshot] to [GET http://127.0.0.1:9515/wd/hub/session/c5491ed42767d386bfa37abfd3194b3d/screenshot] with body: {}
[36minfo[39m: Got response with status 200: {"sessionId":"c5491ed42767d386bfa37abfd3194b3d","status":13,"value":{"message":"unknown error: cannot activate web view\n  (Session info: webview=)\n  (Driver info: chromedriver=2.15.322455 (ae8db840d...

**Comment by imurchie** [comment]
Is this right at the beginning of your test? Could it be that the page hasn't loaded yet, so the DOM is not yet in place?

**Comment by Henry-Gao** [comment]
@imurchie, You are right. I didn't get the right page.
