### ISSUE TITLE
Opening a new window on safari real devices has a race condition

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#5167]
From a preliminary investigation it looks like clicking on a link which opens a new window in iOS mobile safari, the new tab _does_ open, but if we are currently spinning on a command (like checking the page title) the new window doesn't open that tab until the command ends.

Quarantining this test on real devices until this issue is resolved:
https://github.com/appium/appium/blob/d5abb9f48e4ad433b45c48a915aa1dd90eebe5ff/test/functional/ios/safari/windows-frame-specs.js#L53

**Comment by smccarthy** [comment]
Could this be the same issue I mention here ? https://discuss.appium.io/t/real-device-iphone-with-ios-9-3-and-appium-1-5-3-is-not-opening-a-new-tab/10835

**Comment by jlipps** [comment]
Startup logic for safari has changed and appears to function as expected now
