### ISSUE TITLE
Getting error "A new session could not be created as Could not initialize ideviceinstaller" even when ideviceinstaller is present

### ISSUE THREAD

**Issue by narulacool** [appium/appium#5170]
Hi, 

On running appium tests through commandline, I keep on getting the below message:

org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Could not initialize ideviceinstaller; make sure it is installed and works on your system) (WARNING: The server did not provide any stacktrace information)

I have ideviceinstaller installed in my system but still it is not working

i am using Mac OS 10.10.3, IOS 7/8.1, xcode 6.3.2, appium 1.4.1 command line

I am facing the same issue on another mac(OS 10.9.5, IOS 7/8.1, xcode 6.0.1, appium 1.2.0) that was running fine earlier.

**Comment by ubmobile** [comment]
Can u try after installing libimobiledevice library

**Comment by narulacool** [comment]
I did 
$ brew uninstall libimobiledevice
and then
$ brew install libimobiledevice

I also tried uninstalling & installing ideviceinstaller. 
$ brew install ideviceinstaller
It was installed but still appium is not running & gives the error in my original post.

Also, when I run :
$ ideviceinstaller

I see,
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libxml2/lib/libxml2.2.dylib
  Referenced from: /usr/local/lib/libplist.3.dylib
  Reason: Incompatible library version: libplist.3.dylib requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
Trace/BPT trap: 5

I think this might be the issue as ideviceinstaller is installed but not running properly. 
Any suggestions?

**Comment by ubmobile** [comment]
Please try once after updating Xcode command line tools, It worked for me once

To update Xcode command line tools from terminal:
xcode-select --install

**Comment by narulacool** [comment]
I am using xcode 6.3.2, so I have the latest command line tools.
$ brew config 
Command shows command line tool version as 6.3.2.0.1.1431401888

**Comment by imurchie** [comment]
Try installing the latest from `ideviceinstaller`. 

```shell
brew install --HEAD ideviceinstaller
```

**Comment by narulacool** [comment]
I am unable to install using --HEAD
It keeps on giving error: 
unable to find file makefile.in

**Comment by imurchie** [comment]
Strange. Something is out of whack on your system. Can you run `brew update` and `brew doctor`?

**Comment by narulacool** [comment]
I did try that but didnt help.
Brew doctor just says you are ready to brew...so that means everything is up to date..

**Comment by Simon-Kaz** [comment]
It only checks if requirements are met, it doesn't check if the required software works.

**Comment by ubmobile** [comment]
I am expecting with App, whether the app signed in debug mode with developer profile, Plz check once. Try with .app file too

**Comment by narulacool** [comment]
app is signed and automation was working fine before I upgraded to the latest configuration.

**Comment by sebv** [comment]
Could you provide full log in a gist?

**Comment by sebv** [comment]
ping

**Comment by narulacool** [comment]
This issue was resolved through this post:
http://technotesonthego.blogspot.in/2013/10/install-libimobiledevice-on-mac-os-x.html

Also I had to do:
$ brew uninstall libxml2
$ brew prune
$ brew install libxml2

Just in case this can be of help to anyone

**Comment by sebv** [comment]
Nice, thx!
