### ISSUE TITLE
Cannot use method TouchAction to process clicking the menu icon in Google page for real Android device

### ISSUE THREAD

**Issue by Lynn907** [appium/appium#5171]
Hi,

I use click, and tap method to click the left top corner menu icon in Google Home page for Android 5.0 device, but it's failed.

Here is the method I used. Please help me check the issue and advise the right method to process the action.

driver.navigate().to(https://www.google.com);
driver.context("WEBVIEW_1");
WebElement menu = driver.findElement(By.id("gbg"));
menu.click(); 
OR:
TouchAction touchAction = new TouchAction(driver);
touchAction.tap(menu).release().perform();

here is the screenshot for menu icon in google page and the screen after clicking the menu icon:
![menu](https://cloud.githubusercontent.com/assets/12625989/7835275/258635ac-04aa-11e5-9383-53f9dcb5bc0d.png)
![screenaftermenuclicked](https://cloud.githubusercontent.com/assets/12625989/7835322/7f36ac9e-04aa-11e5-8eec-3dce9d0a03ad.png)

**Comment by imurchie** [comment]
What does "failed" mean? Can you post the Appium server logs?

**Comment by jlipps** [comment]
I'm guessing it has to do with the javascript events that the app is listening for not matching those that the atoms are sending

**Comment by Anishohri** [comment]
I am facing the similar problem. Can't click on any webview object on chrome browser on any android device.

No error in appium logs.

**Comment by imurchie** [comment]
For some reason clicking the menu button does not work but clicking "Images" or "Web" does. Strange.

However, you _can_ exit to the `NATIVE_APP` and then use the `TouchAction#tap` method, which works.

My test:

```javascript
    it('should tap the hamburger menu on google.com', function (done) {
      var el;
      driver
        .get('http://google.com')
        .contexts().then(function (ctxs) {
          return driver.context(_.first(ctxs);
        })
        .elementByClassName('android.webkit.WebView')
        .then(function (_el) {
          el = _el;
          var action = new TouchAction(driver);
          return action.tap({x: 50, y: 300}).perform();
        })
        .then(function () {
          return el.elementByAccessibilityId('Maps');
        })
        .click()
        .sleep(3000) // google maps be slow
        .contexts().then(function (ctxs) {
          return driver.context(_.last(ctxs));
        })
        .url().should.eventually.include('https://www.google.com/maps')
        .waitForElementById('ml-searchboxinput').should.eventually.exist
        .nodeify(done);
    });
```

**Comment by Lynn907** [comment]
I have tried with your case. It works. Thanks a lot!:)

**Comment by Anishohri** [comment]
Yeah X and y works but it doesn't work with Element targets, i did some search and you have a bug already open #4075.

**Comment by SimiCode** [comment]
I had such an error once, I solved it by...
Make sure that you don't have both of these in your py:

from selenium import webdriver
from appium import webdriver

I had imported both while using selenium explicit waits to find my elements. Never, do so, Its a trap.

**Comment by sharma9890** [comment]
not able to click the top right icon
tried 
String ContextVaule = driver.getContext();
		ChromeDriver driver = new ChromeDriver();
		driver.findElement(By.id("menu_button")).click();

also tried via touch action.
@Lynn907 
@imurchie 
please help..
![Uploading Screen Shot 2018-01-31 at 6.21.04 PM.png…]()
