### ISSUE TITLE
I am new to Appium and getting issue while trying to run Appium mobile Web Test  in chrome/android.

### ISSUE THREAD

**Issue by faysalyare** [appium/appium#5173]
Here is the server side error 

=========================
 Starting Node Server
> info: Welcome to Appium v1.3.7 (REV 72fbfaa116d3d9f6a862600ee99cf02f6d0e2182)
> info: Appium REST http interface listener started on 127.0.0.1:4725
> info: [debug] Non-default server args: {"address":"127.0.0.1","port":4725,"logNoColors":true,"platformName":"Android","platformVersion":"19","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"Appium","platform":"ANDROID","browserName":"Chrome","autoLaunch":true,"version":"","autoAcceptAlerts":true,"platformVersion":"4.4.2","deviceName":"Nexus 5","platformName":"Android","deviceType":"phone","device":"android","enablePerformanceLogging":"true","device-orientation":"portrait"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
> warn: Converting cap enablePerformanceLogging from string to boolean. This might cause unexpected behavior.
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : platform, version, deviceType, device, device-orientation
> info: Set mode: Proxying straight through to Chromedriver
> info: [debug] Looks like we want chrome on android
> info: [debug] Creating new appium session 9db56e28-15c0-4860-a17d-cd6d93451e06
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\dev\Android-20140702\sdk\platform-tools\adb.exe
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\dev\Android-20140702\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device 069ae0dc00639a55
> info: [debug] Setting device id to 069ae0dc00639a55
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\dev\Android-20140702\sdk\platform-tools\adb.exe -s 069ae0dc00639a55 wait-for-device
> info: [debug] executing cmd: C:\dev\Android-20140702\sdk\platform-tools\adb.exe -s 069ae0dc00639a55 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\dev\Android-20140702\sdk\platform-tools\adb.exe -s 069ae0dc00639a55 install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: [debug] executing cmd: C:\dev\Android-20140702\sdk\platform-tools\adb.exe -s 069ae0dc00639a55 shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\dev\Android-20140702\sdk\platform-tools\adb.exe -s 069ae0dc00639a55 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\dev\Android-20140702\sdk\platform-tools\adb.exe -s 069ae0dc00639a55 push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\dev\Android-20140702\sdk\platform-tools\adb.exe -s 069ae0dc00639a55 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\dev\Android-20140702\sdk\platform-tools\adb.exe -s 069ae0dc00639a55 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Creating Chrome session
> info: [debug] Set chromedriver binary as: C:\Program Files (x86)\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data\/local\/tmp"}
> info: [debug] Ensuring Chromedriver exists
> info: [debug] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %b))
> info: [debug] No old chromedrivers seemed to exist
> info: [debug] Spawning chromedriver with: C:\Program Files (x86)\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] [CHROMEDRIVER] Starting ChromeDriver 2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf) on port 9515
> Only local connections are allowed.
> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session","method":"POST","json":{"sessionId":null,"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"069ae0dc00639a55"},"loggingPrefs":{"performance":"ALL"}}}}
> info: [debug] Successfully started chrome session ae1ab09907662dd8fc77477a41e22145
> info: [debug] Overriding session id with "ae1ab09907662dd8fc77477a41e22145"
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId ae1ab09907662dd8fc77477a41e22145
> info: <-- POST /wd/hub/session 303 6087.126 ms - 70 
> info: --> GET /wd/hub/session/ae1ab09907662dd8fc77477a41e22145 {}
> info: [debug] Proxying command to 127.0.0.1:9515
> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/ae1ab09907662dd8fc77477a41e22145","method":"GET"}
> info: [debug] Proxied response received with status 200: {"sessionId":"ae1ab09907662dd8fc77477a41e22145","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"platform":"ANDROID","rotatable":false,"takesHeapSnapshot":true,"takesScreenshot":true,"version":"42.0.2311.111","webStorageEnabled":true}}
> info: <-- GET /wd/hub/session/ae1ab09907662dd8fc77477a41e22145 200 10.824 ms - 507 
> info: --> POST /wd/hub/session/ae1ab09907662dd8fc77477a41e22145/url {"url":"https://exeter.cedardoc-dev.com/mindex.html"}
> info: [debug] Proxying command to 127.0.0.1:9515
> info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/ae1ab09907662dd8fc77477a41e22145/url","method":"POST","json":{"url":"https://exeter.cedardoc-dev.com/mindex.html"}}
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"unknown error: unhandled inspector error: {\"code\":-32000,\"message\":\"Timeline is deprecated. Please use Tracing instead\"}\n  (Session info: chrome=42.0.2311.111)\n  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Windows NT 6.3 x86_64)"},"sessionId":"ae1ab09907662dd8fc77477a41e22145"}
> info: <-- POST /wd/hub/session/ae1ab09907662dd8fc77477a41e22145/url 500 32.343 ms - 448 
> info: [debug] Didn't get a new command in 60 secs, shutting down...
> info: Shutting down appium session
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 64.555
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] UiAutomator shut down normally
> info: [debug] Killing chromedriver and waiting for close
> info: [debug] Chromedriver exited with code null
> info: [debug] (killed by signal SIGINT)
> info: [debug] executing cmd: C:\dev\Android-20140702\sdk\platform-tools\adb.exe -s 069ae0dc00639a55 shell "am force-stop com.android.chrome"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Cleaning up appium session
> info: [debug] We shut down because no new commands came in

==============================

and here is my capabilities

DesiredCapabilities capabilities = DesiredCapabilities.android();
			capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "chrome");
			capabilities.setCapability("automationName", "Appium");
			capabilities.setCapability("platformName","Android");
			capabilities.setCapability("autoLaunch", true);
			capabilities.setCapability("deviceType","phone");
			capabilities.setCapability("device", "android");
			capabilities.setCapability("autoAcceptAlerts", true);
			capabilities.setCapability("enablePerformanceLogging", "true");
			capabilities.setCapability("device-orientation", "portrait"); 
			capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
			capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "4.4.2");
			capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Nexus 5");
			
			  capabilities.setCapability(CapabilityType.BROWSER_NAME, "Chrome");
		

			try {
	driver = new RemoteWebDriver(new URL("http://127.0.0.1:4725/wd/hub"), capabilities);
	driver.get(url);
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}

	driver.manage().timeouts().implicitlyWait(40, TimeUnit.SECONDS);

Any help will be appreciated

Thanks,

**Comment by imurchie** [comment]
Are you using performance logging? If not, turn it off.

Otherwise, the latest version of Appium uses ChromeDriver 0.15, which has fixed this issue.

**Comment by imurchie** [comment]
Alternatively, with your current setup, you can add the capability:

```
chromeOptions: {perfLoggingPrefs: {enableTimeline: false}}
```

Which ought to turn off timeline and you won't get the error.

**Comment by faysalyare** [comment]
You right! I  turned off the performance logging and that worked for me .

Thanks,

**Comment by imurchie** [comment]
Excellent!
