### ISSUE TITLE
I cant see the expression on Emulator,but the appium debug log is OK

### ISSUE THREAD

**Issue by wushuai100** [appium/appium#5178]
List<WebElement> textFieldsList = driver.findElements(By.className("android.widget.EditText"));
        textFieldsList.get(0).click();
        driver.manage().timeouts().implicitlyWait(5,TimeUnit.SECONDS);
        System.out.println(1);
        textFieldsList.get(0).sendKeys("91442591@.com");
        System.out.println(2);t
        driver.manage().timeouts().implicitlyWait(5,TimeUnit.SECONDS);
        System.out.println(3);
        textFieldsList.get(1).click();
        textFieldsList.get(1).sendKeys("***************");
        System.out.println(4);

info: --> POST /wd/hub/session/6b82683b-fcd5-4fda-a9aa-a76a0a3d4a4c/element/2/value {"id":"2","value":["saohao4544312"]}
info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"2","text":"saohao4544312","replace":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"2","text":"saohao4544312","replace":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: setText
info: [debug] [BOOTSTRAP] [debug] Using element passed in.
info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: saohao4544312
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"6b82683b-fcd5-4fda-a9aa-a76a0a3d4a4c"}
info: <-- POST /wd/hub/session/6b82683b-fcd5-4fda-a9aa-a76a0a3d4a4c/element/2/value 200 4918.027 ms - 76 {"status":0,"value":true,"sessionId":"6b82683b-fcd5-4fda-a9aa-a76a0a3d4a4c"}
info: --> POST /wd/hub/session/6b82683b-fcd5-4fda-a9aa-a76a0a3d4a4c/element {"using":"class name","value":"android.widget.Button"}
info: [debug] Waiting up to 5000ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"class name","selector":"android.widget.Button","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"class name","selector":"android.widget.Button","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding android.widget.Button using CLASS_NAME with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CLASS=android.widget.Button, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"ELEMENT":"3"},"status":0}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"3"},"sessionId":"6b82683b-fcd5-4fda-a9aa-a76a0a3d4a4c"}
info: <-- POST /wd/hub/session/6b82683b-fcd5-4fda-a9aa-a76a0a3d4a4c/element 200 46.720 ms - 87 {"status":0,"value":{"ELEMENT":"3"},"sessionId":"6b82683b-fcd5-4fda-a9aa-a76a0a3d4a4c"}
info: --> POST /wd/hub/session/6b82683b-fcd5-4fda-a9aa-a76a0a3d4a4c/element/3/click {"id":"3"}
info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"3"}]

**Comment by imurchie** [comment]
I'm not sure what your issue is here. Is the provided log that of the second `sendKeys` call? And are you not seeing the text `"saohao4544312"` in the text field?

**Comment by wushuai100** [comment]
yeah ,i cant see the text "saohao4544312" in the screen ,but the logs show it succeed?,,,,,i use the other app with this code, it works nornal,but only with my test app ,it not work ,I think that some problem with my app?i not sure ,would you help me ,i have already stuck a week ,,........

**Comment by wushuai100** [comment]
help,help

**Comment by imurchie** [comment]
Are you sure that it is the correct EditText field? 

Can you print out the source at that point in the test? And post that here?

**Comment by wushuai100** [comment]
The source code:
List<WebElement> textFieldsList = driver.findElements(By.className("android.widget.EditText"));
        textFieldsList.get(0).click();
//        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        System.out.println(1);
        Thread.sleep(10);
        
        textFieldsList.get(0).sendKeys("18576625748");
        Thread.sleep(10);
        System.out.println(2);
//        driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS);
        System.out.println(3);
        textFieldsList.get(1).click();
        textFieldsList.get(1).sendKeys("111111");
        Thread.sleep(10);

The appium log :

info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[CLASS=android.widget.EditText, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
info: [debug] [BOOTSTRAP] [debug] Finding android.widget.EditText using CLASS_NAME with the contextId:  multiple: true
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CLASS=android.widget.EditText]
info: [debug] [BOOTSTRAP] [debug] getElements selector:UiSelector[CLASS=android.widget.EditText]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (0)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[CLASS=android.widget.EditText, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (1)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[CLASS=android.widget.EditText, INSTANCE=1]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (2)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[CLASS=android.widget.EditText, INSTANCE=2]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":[{"ELEMENT":"1"},{"ELEMENT":"2"}],"status":0}
info: [debug] Responding to client with success: {"status":0,"value":[{"ELEMENT":"1"},{"ELEMENT":"2"}],"sessionId":"3b758cd7-335e-4993-be18-d866185cfc73"}
info: <-- POST /wd/hub/session/3b758cd7-335e-4993-be18-d866185cfc73/elements 200 4609.259 ms - 105 {"status":0,"value":[{"ELEMENT":"1"},{"ELEMENT":"2"}],"sessionId":"3b758cd7-335e-4993-be18-d866185cfc73"}
info: --> POST /wd/hub/session/3b758cd7-335e-4993-be18-d866185cfc73/element/1/click {"id":"1"}
info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"1"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"1"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: click
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"3b758cd7-335e-4993-be18-d866185cfc73"}
info: <-- POST /wd/hub/session/3b758cd7-335e-4993-be18-d866185cfc73/element/1/click 200 3079.711 ms - 76 {"status":0,"value":true,"sessionId":"3b758cd7-335e-4993-be18-d866185cfc73"}
info: --> POST /wd/hub/session/3b758cd7-335e-4993-be18-d866185cfc73/element/1/value {"id":"1","value":["18576625748"]}
info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"1","text":"18576625748","replace":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"18576625748","replace":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: setText
info: [debug] [BOOTSTRAP] [debug] Using element passed in.
info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: 18576625748
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"3b758cd7-335e-4993-be18-d866185cfc73"}
info: <-- POST /wd/hub/session/3b758cd7-335e-4993-be18-d866185cfc73/element/1/value 200 5021.910 ms - 76 {"status":0,"value":true,"sessionId":"3b758cd7-335e-4993-be18-d866185cfc73"}
info: --> POST /wd/hub/session/3b758cd7-335e-4993-be18-d866185cfc73/element/2/click {"id":"2"}
info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"2"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"2"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: click
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"3b758cd7-335e-4993-be18-d866185cfc73"}
info: <-- POST /wd/hub/session/3b758cd7-335e-4993-be18-d866185cfc73/element/2/click 200 3054.369 ms - 76 {"status":0,"value":true,"sessionId":"3b758cd7-335e-4993-be18-d866185cfc73"}
info: --> POST /wd/hub/session/3b758cd7-335e-4993-be18-d866185cfc73/element/2/value {"id":"2","value":["111111"]}
info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"2","text":"111111","replace":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"2","text":"111111","replace":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: setText
info: [debug] [BOOTSTRAP] [debug] Using element passed in.
info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: 111111
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"3b758cd7-335e-4993-be18-d866185cfc73"}
info: <-- POST /wd/hub/session/3b758cd7-335e-4993-be18-d866185cfc73/element/2/value 200 2869.678 ms - 76 {"status":0,"value":true,"sessionId":"3b758cd7-335e-4993-be18-d866185cfc73"}
info: --> POST /wd/hub/session/3b758cd7-335e-4993-be18-d866185cfc73/element {"using":"class name","value":"android.widget.Button"}
info: [debug] Waiting up to 15000ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"class name","selector":"android.widget.Button","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","

I find that it work nornal  by accident,  
it cant put the cursor into the test field.....

**Comment by wushuai100** [comment]
the app is designed use Cordova,,,,i need set the context (WEBVIEW_me.ele.talaris
)or set it NATIVE_APP?

**Comment by imurchie** [comment]
If it is an actual `android.widget.EditText` element, then you should be in a `NATIVE_APP` context. You could try in the webview, but I don't think it should work.

What do you mean by "it can't put the cursor into the test field"?

**Comment by wushuai100** [comment]
i cant see the text （“18576625748”）in the textbox

**Comment by wushuai100** [comment]
sorry ,my english is so poor . I have this problem whit my test with appium 
1、i dont know  which  ContextHandlesstart  i must use ?  this code :
Set<String> contextNames = driver.getContextHandles();
   	         for (String contextName : contextNames) {
   	    System.out.println(contextName);


it print  on the console
NATIVE_APP
WEBVIEW_me.ele.talaris
WEBVIEW_com.android.browser"

2、I run my test flow ,but i cant see the text"1857662574" in the textbox   in my Android Emulator,but i can see it work nornal at times,,,,i m crazy

**Comment by imurchie** [comment]
You could try all three. I cannot tell you without knowing your app. But if it is a native view, use the `NATIVE_APP`; if it is in a webview, use `WEBVIEW_me.ele.talaris`; and if it is in a browser, use `WEBVIEW_com.android.browser`.

**Comment by wushuai100** [comment]
OK,thank for your help!
1,With this all three mode （NATIVE_APP，WEBVIEW_me.ele.talaris，WEBVIEW_com.android.browser）,i would Locating element with one way use selenium(import org.openqa.selenium.By;import org.openqa.selenium.WebElement;) ,ignore it is NATIVE_APP or H5, am i right?.
2,if you have the time,would you help me write the script with my app(just the Login text)。

**Comment by wushuai100** [comment]
and here is my app--->>>     http://pan.baidu.com/s/1mg89ZTm

**Comment by imurchie** [comment]
I couldn't install the apk:

```shell
➤ adb install ~/Downloads/fly.apk
4017 KB/s (389153 bytes in 0.094s)
        pkg: /data/local/tmp/fly.apk
Failure [INSTALL_FAILED_INVALID_APK]
```

**Comment by wushuai100** [comment]
oh,sorry, here is the latest version,try is again please...TKS:
http://pan.baidu.com/s/1bn32N3h

**Comment by imurchie** [comment]
On the first screen with two edit fields, things work entirely as expected, entering text into both.

```javascript
describe('Talaris-Cordova app', function () {
  var driver;
  setup(this, _.defaults({app: '/Users/isaac/Downloads/Talaris-Crodova.apk'}, desired)).then(function (d) { driver = d; });

  it('should do stuff', function (done) {
    var els;
    driver
      .waitForElementsByClassName('android.widget.EditText')
      .then(function (_els) {
        els = _els;
        return els[0];
      })
      .sendKeys('test number one')
      .then(function () {
        return els[1];
      })
      .sendKeys('test numero two')
      .sleep(5000)
      .nodeify(done)
  });
});
```

**Comment by wushuai100** [comment]
oh sorry ,i'm not familiar with js,would you write it with JAVA  Client,,,,Thanks.....

**Comment by sebv** [comment]
Closing, please go to https://discuss.appium.io/ for further help.
