### ISSUE TITLE
Appium not working for Multiple users on Mac 

### ISSUE THREAD

**Issue by jawlitkp** [appium/appium#5185]
Issue:
1. Installed Appium UI app and using brew as well without sudo command 
2. set up two users on mac with admin access 
3. Appium is working fine for one user who installed appium 
4. for 2nd user giving below error 

error: Appium will not work if used or installed with sudo. Please rerun/install as a non-root user. If you had to install Appium using `sudo npm install -g appium`, the solution is to reinstall Node using a method (Homebrew, for example) that doesn't require sudo to install global npm packages.

![screen shot 2015-05-31 at 11 21 05 am](https://cloud.githubusercontent.com/assets/9873362/7902413/288aadd4-0787-11e5-9434-5c46cbac0f69.png)

**Comment by njection** [comment]
Can you print your ~.bash_history file and trim it down to show what you
use to install Appium?

**Comment by jawlitkp** [comment]
Thanks for reply ,

For some reason i can see only one day history under .bash_history file ,so i am not able to see any command related Appium installation  but i have used bellow commands after installing home-brew 

> brew install node      # get node.js
> npm install -g appium  # get appium
> npm install wd         # get appium client

in adition to Appium UI application also giving me same error.

Any help would be appreciated and let me know if you need any other details

**Comment by njection** [comment]
Have you checked to see if you have any other instances of Node running?

**Comment by jawlitkp** [comment]
Yes ,i don't have any other instances running ,i did run killall node command as well.

I am able to run Appium from UI and terminal when i use account under which i have installed Appium but I am facing issue when i am login using different user account

**Comment by jlipps** [comment]
Right now Appium will only work for the user that owns its files. This will be remedied in a future version. For now, you could just `npm install -g appium` for the second user as well

**Comment by jlipps** [comment]
I guess if they share the same global npm space that won't work. I guess you'd have to install it in a local folder for the second user

**Comment by jawlitkp** [comment]
Thanks Jonathan!

I was able to install Appium using terminal and it's working fine for different users and for Apppim UI application I have installed different version of Appium for each users and it is working fine.

Appreciate your help

**Comment by jawlitkp** [comment]
Should I close issue or you want to keep it open for future enhancement ?

**Comment by jlipps** [comment]
No, that issue is already being tracked. Thanks.
