### ISSUE TITLE
[Android]  Review The Old Problem: Cannot locate elements in WebView

### ISSUE THREAD

**Issue by vietnq254** [appium/appium#5191]
Hi All,

This is the old problem that many users reported about.
UiAutomator helps us to locate elements in Webview if:
+ the device has API >= 19 and
+ enable WebView debugging:  ```WebView.setWebContentsDebuggingEnabled(true);```

I wonder about the second condition. A strong point of Appium is it doesnot require the source code of application to run test. In the other hand, tester will use the same version that is deployed to market.
But for the second condition that requires to enable Webview debugging, we need to talk to developer to change the code!!
It is impossible in many cases. Actually I am testing a commercial product that I cannot ask them to change any thing.
It means that Appium is not a good choice for testing hybrid app, right?
If I use the mode Selendroid for every hybrid apps then I don't need Appium.

I also see you will have the new architecture in the next version 1.5. Does it care about this problem?

Thank you,
NGUYEN Viet

**Comment by jlipps** [comment]
As this is a Chromedriver limitation, there's nothing we can do about it. So perhaps in your specific use case, an Instrumentation-based method like Selendroid is better.  Something like DroidDriver (on Appium's roadmap) might also provide that kind of support.
