### ISSUE TITLE
Automation of application with expansion file (obb file)

### ISSUE THREAD

**Issue by fayizkc** [appium/appium#5192]
I want to automate an application which is downloaded from Google play, which has expansion. Actual size of the application is 128 MB. So the base app size is only 23 MB, remaining app contends are saving to Android/obb folder. While I am trying to identify the object with UI Automator viewer, it is showing only android.view.View object, How can I identify inside object also with obb file. Please find the screenshot for the same.
![obb](https://cloud.githubusercontent.com/assets/9282160/7930879/c281e1fc-0929-11e5-9dc5-390abbb10c3e.jpg)

**Comment by sebv** [comment]
It's probably because those are not native Android UI control.

**Comment by fayizkc** [comment]
Hi Sebv,
Is it possible to automate games with Appium or any other free automation tools available for the same.

**Comment by sebv** [comment]
You could do it by coordinate, but it is not great.

**Comment by sebv** [comment]
Feature: better automation for game type app.
