### ISSUE TITLE
Testing multiple devices with single appium server?

### ISSUE THREAD

**Issue by tolgatanriverdi** [appium/appium#5193]
Hi 
We are going to use appium in our product as a test framework and we are going to build some wrappers on top of it
However when I searched the web , I saw some limitations about using multiple sessions on appium
Our planned infrastructure is like this:

We are planning to have 2 appium servers(with different ports) running on the same machine

1'st appium server is responsible for IOS devices
2'nd appium server is responsible for Android devices

1'st appium server will be connected to 2 IOS devices(1 Iphone and 1 Ipad)
2'nd appium server will be connected to 2 Android devices (1 Phone and 1 tablet)

And we are going to test 2 different applications for both android and IOS.

So my question here is :

When we want to test these applications.

On IOS Server:
We want to test 1'st application on Iphone
2'nd application on IPad
at the same time

On Android Server:
We want to test 1'st application on phone
2'nd application on Tablet
at the same time

Is something like that even possible? Or do we have to wait to finish 1'st applications test in order to start testing the 2'nd application

Thanks

**Comment by sebv** [comment]
With the current version, my advice is to to run VMs with one Appium per VMs. For the iOS server, you will need to run it on osx.

Please discuss this kind os setup here: https://discuss.appium.io/
