### ISSUE TITLE
Unable to locate "Record" button on Inspector window

### ISSUE THREAD

**Issue by dhiraj-infosys** [appium/appium#5201]
**Environment:**
- Version:1.4.0.0
- OS: Windows 7
- IDE: Eclipse
- Application: Android

**Steps:**
- Connect an android application with appium
- Click Launch to start the server.
- Now Open Inspector window.

**Observed:**
- I can take the screen shot and can locate the UI element. **But I cannot record the Script. How do I record the script?**

**Expected:**
- Recorder option is available.

**Comment by sebv** [comment]
Please report inspector issues here: https://github.com/appium/appium-dot-app
Or get support here: https://discuss.appium.io/

**Comment by dhiraj-infosys** [comment]
Issue has been logged to the https://github.com/appium/appium-dot-app . Track here  https://github.com/appium/appium-dot-app

**Comment by sebv** [comment]
Thx @dhiraj-infosys , could you fix the issue link above

**Comment by dhiraj-infosys** [comment]
@sebv , link has been fixed. But the linked issue has been closed already. And I have started my conversation on some other issue.

If you want, you can close this issue.

**Comment by mayurr87** [comment]
I am using AppiumForWindows_1_4_13_1. Installation done properly. 

But I cannot record the Script. How do I record the script?

Recording option is not available in Inspector. I am using windows machine. What to do.

**Comment by dhiraj-infosys** [comment]
@mayurr87, I think, AppiumForWindows does not support "Recorder" as of now. However it is available for Mac Appium version.

**Comment by mayurr87** [comment]
Thanks a lot.
