### ISSUE TITLE
Returning empty screenshot on Android 4.4.2

### ISSUE THREAD

**Issue by jhuska** [appium/appium#5202]
I am taking screenshot by well known way:

``` java
File screenshot = device.getScreenshotAs(OutputType.FILE);
String deviceName = device.getCapabilities().getCapability("deviceName").toString();
File destFile = new File(BUILD_DIR + File.separator
            + deviceName + "-" + screenshotName + ".png");
try {
   FileUtils.copyFile(screenshot, destFile);
} catch (IOException ex) {
   throw new RuntimeException(ex);
}
```

It works just fine on my devices, expect Samsung Galaxy S4, which is running Android 4.4.2.

In Appium server log I can find these lines:

```
/wd/hub/session/5a1b71ee-5b92-468d-8c54-eb1356f837dc/screenshot
[debug] executing cmd: path/to/sdk/platform-tools/adb -s [particularSerialNumber] shell "/system/bin/rm /data/local/tmp/screenshot.png; /system/bin/screencap -p /data/local/tmp/screenshot.png "
[debug] executing cmd: path/to/sdk/platform-tools/adb -s [particularSerialNumber] pull /data/local/tmp/screenshot.png "/tmp/appium11553-11542-1iswk7x.png"
[debug] Responding to client with success: {"status":0,"value":"","sessionId":"5a1b71ee-5b92-468d-8c54-eb1356f837dc"}
<-- GET /wd/hub/session/5a1b71ee-5b92-468d-8c54-eb1356f837dc/screenshot {"status":0,"value":"","sessionId":"5a1b71ee-5b92-468d-8c54-eb1356f837dc"}
```

Please see that `value` is empty. In result it creates an empty file.

When executing those `adb` commands manually, it works. I am running Appium from source, with pretty much fresh master (May 4) - all found issues related to screenshots were resolved sooner.

**Comment by sebv** [comment]
Try with the screenshotWaitTimeout cap.

**Comment by jhuska** [comment]
Thanks @sebv, I tried it. Unfortunately it does not help. 

Is not that cap. iOS only?

**Comment by sebv** [comment]
Ok put it in bug, I remember it is one of the thing we have in backlog, will tackle those after current Appium rewrite effort.

**Comment by imurchie** [comment]
This has all been changes. Closing.
