### ISSUE TITLE
How to switch to Dialog box in native App

### ISSUE THREAD

**Issue by kamaldeep1983** [appium/appium#5203]
Hi Team,

Could you please let me know how to switch to dialog box in native app.
Please find attached screenshot.
![issue](https://cloud.githubusercontent.com/assets/12550503/7961659/918e7e36-0a26-11e5-81e8-92a88a4a79d4.png)

Regards,
Kamaldeep

**Comment by sebv** [comment]
Sorry we don't provide this kind of support here, try appium discuss.
