### ISSUE TITLE
How to click on button when two button appears in one view

### ISSUE THREAD

**Issue by kamaldeep1983** [appium/appium#5204]
Hi Team,

I want to click on link "VIEW SAVED ITEMS" but when i am trying to identify this element it is coming under view class which has two buttons with label "VIEW SAVED ITEMS" and "CONTINUE SHIPPING".

Please find attached screenshot. 

Regards,
Kamaldeep
![issue_2](https://cloud.githubusercontent.com/assets/12550503/7961800/5b1a05cc-0a27-11e5-9f2e-ee107dd07780.png)

**Comment by sebv** [comment]
Please read the doc.
