### ISSUE TITLE
(iOS) Tapping on an element fails after launching an app

### ISSUE THREAD

**Issue by whoward** [appium/appium#5206]
After the previous work of being able to launch an app in the iOS simulator I've noticed a new issue - tapping on an element causes the instruments process to hang.

To reproduce:
1. Start with a safari session
2. Install/Launch your app
3. `setContext("NATIVE_APP")`
4. `executeScript("$.getElementByIndexPath('/0/0/7').tap()")`

The path `/0/0/7` should be whatever makes sense to you, this is all pseudocode.

I'm currently trying to dig down into this but with the codebase being as big as it is I'm hoping someone could give me an idea of where the problem might lie.

**Comment by sebv** [comment]
Please provide full log.

Not sure why you would open safari and then tap on a native element, should be a really side case.

**Comment by jlipps** [comment]
Also, why are you using executeScript/indexPath? indexPath is an appium-internal thing.

**Comment by whoward** [comment]
@sebv here is the log: https://gist.githubusercontent.com/whoward/097085ca8dcff753fad4/raw/4b3e28fa8adbc0c0ddbded6668995d5f73f564a0/out.log

The use case is not as contrived as it might appear, I'm testing deep links - launching the app from inside the browser.  Unfortunately it appears that something gets messed up on the transition from the web browser to the app.

@jlipps I'm just using it to provide a minimum failing test for you, in our code we actually use xpath to obtain the element.

**Comment by sebv** [comment]
Two things are coming to my mind when I see that
- Safari might use non native element
- paths like `/0/0/7` are not solid, the indexing easily breaks if the UI changes.

**Comment by whoward** [comment]
i'm not sure about the Safari point but regarding `/0/0/7` feel free to use whatever selection process you want for the element, it seems to happen regardless.

**Comment by sebv** [comment]
Well I suggest you try to do that in xCode instruments. 

Very likely it just hangs because Safari does not expect you to tap button this way. You're not really respecting the Safari usage contract.

**Comment by whoward** [comment]
Sorry @sebv I think there has been some communication failure here, at the point of this failure we have switched out of safari and are now inside our native app (com.codified.hipyard) - not Safari.

At this point Appium shouldn't be using the safari web remote, it should be using the app, and I can tell it works because I can inspect the current state of the app, its just once I start to interact with it it starts to fail.

**Comment by sebv** [comment]
Sorry i see now, didn't even realize we added this kind of functionality on ios. 

So I don't know why it hangs, looks like the whole Intruments process is hanging. There is not much in the log, maybe you could enable the sim log.

**Comment by jlipps** [comment]
Oh right. This is because instruments doesn't support automating multiple apps. In previous versions of Xcode, if you switched from Safari to your app, Instruments would actually crash and the session would end.

Nowadays (as I have learned from @Jonahss), Instruments won't die and you can introspect the new app in some measure, but certain actions cause Instruments to hang forever.

What this says to me is that something inadvertently changed on Apple's side that stopped Instruments from exiting when the app changes, but no one intentionally added support for multiple apps, hence the wonky behavior.

Unfortunately there's no 2-apps-in-one-session flow that works for iOS :-(

**Comment by whoward** [comment]
oh really? thats kind of odd - i know we can do the reverse where we start in the app then switch out to a web browser (facebook login) but I'm gonna guess that under the hood this isn't the same thing

**Comment by jlipps** [comment]
exactly, switching to a web browser is OK because a web browser doesn't need UIautomation-based automation; we use the remote debugger which is just available as part of the webview

**Comment by whoward** [comment]
ok well in that case it seems that nothing can be done unless apple improves instruments - thanks!
