### ISSUE TITLE
Element does not have location_in_view

### ISSUE THREAD

**Issue by curtissiemens** [appium/appium#5207]
When you find an element if you call:
loc_x = elem.location['x']
Then appium server complains:
warn: location will be removed in a future version of Appium, please use location_in_view

But I run a dir(elem) to see all of the accessors and there is no location_in_view member-variable to access.

I see how location to was switched to location_in_view and a warn was put in if you use the older 'location':
https://github.com/appium/appium/issues/1126
But I just can't switch my code to use the newer method.

Note: I'm using the Appium python-client to find elements.

**Comment by jlipps** [comment]
it's possible the python client doesn't implement location_in_view? or that it does so with a different method/accessor that looks superficially different? @imurchie might know

**Comment by curtissiemens** [comment]
The dir() of the element looks like:
 ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_execute', '_id', '_parent', '_upload', 'clear', 'click', 'find_element', 'find_element_by_accessibility_id', 'find_element_by_android_uiautomator', 'find_element_by_class_name', 'find_element_by_css_selector', 'find_element_by_id', 'find_element_by_ios_uiautomation', 'find_element_by_link_text', 'find_element_by_name', 'find_element_by_partial_link_text', 'find_element_by_tag_name', 'find_element_by_xpath', 'find_elements', 'find_elements_by_accessibility_id', 'find_elements_by_android_uiautomator', 'find_elements_by_class_name', 'find_elements_by_css_selector', 'find_elements_by_id', 'find_elements_by_ios_uiautomation', 'find_elements_by_link_text', 'find_elements_by_name', 'find_elements_by_partial_link_text', 'find_elements_by_tag_name', 'find_elements_by_xpath', 'get_attribute', 'id', 'is_displayed', 'is_enabled', 'is_selected', 'location', 'location_once_scrolled_into_view', 'parent', 'rect', 'send_keys', 'set_text', 'set_value', 'size', 'submit', 'tag_name', 'text', 'value_of_css_property']

So there isn't anything there that is the obvious successor to 'location'

**Comment by imurchie** [comment]
It is (cough cough) _entirely_ possible that the python client does not implement `location_in_view`. I'll fix that.

**Comment by sebv** [comment]
Coud someone open an issue in the python client project, link to it?

**Comment by curtissiemens** [comment]
I created https://github.com/appium/python-client/issues/86 to track this issue.
This ticket can be closed because the issue is in the appium/python-client codebase.
