### ISSUE TITLE
Do not close ios Simulator between test.

### ISSUE THREAD

**Issue by sebv** [appium/appium#5208]
Feature request, https://discuss.appium.io/t/not-close-ios-simulator-between-tests/4593
Is there a way already, I forgot? (ping @jlipps).

We should keep that in mind for 1.5.

**Comment by jlipps** [comment]
did they try the `noReset` capability set to true?

**Comment by igladun** [comment]
Hello,
Thanks for the suggestion, with noReset. It works. 
How can we reset app state before a test?

**Comment by jlipps** [comment]
By restarting the iOS simulator

**Comment by igladun** [comment]
@jlipps  what do you think about executing next commands between tests?
xcrun simctl uninstall booted com.myapp
xcrun simctl install booted myapp.app

**Comment by gilsheps** [comment]
is there an issue with Appium 1.5?
I tested after the version released and the iOS emulator closes after test end.
is there a way to run tests on ios without closing the emulator?

**Comment by jayantsarda** [comment]
Is there a way to just close safari once a test finishes and start another safari instance for another test and not closing the simulator

**Comment by alexisalvarez88** [comment]
Is there any chance to not close ios Simulator between test on appium 1.6.4?

**Comment by vikramvi** [comment]
@alexisalvarez88 https://github.com/appium/appium/issues/6385 & https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/reset-strategies.md.

I also call 2 methods closeApp & launchApp post each test case ( https://appium.github.io/java-client/io/appium/java_client/InteractsWithApps.html )

Let us know here if it helps ?

**Comment by saikrishna321** [comment]
@alexisalvarez88 pls set capability "noReset" to true  and this would stop closing the  open simulator
