### ISSUE TITLE
Deep linking with appium:

### ISSUE THREAD

**Issue by sebv** [appium/appium#5209]
Is this a new feature/bug/impossible?

ping @imurchie, @jlipps , @bootstraponline 

https://discuss.appium.io/t/deep-linking-with-appium/3365

**Comment by jlipps** [comment]
not sure why it would be doing this. does this repro with chromedriver by itself?

**Comment by Fanch-** [comment]
Example :  
Mobile apps with ads. When one expires, you send a deep link to the customer to reactivate it again. If the customer opens it AND has the app installed, you propose to him to finish action using the app (popup).

Would it work if I come for example from gmail app to my signed app? I mean I set capability to gmail app at first, click on my app in the popup (after click on deep link) so it launches it, and then is it possible to set new capabilities via client, manage serv params like keystore, etc.. ? I could launch my app first with no-reset I think, then gmail, then back to my app using deep link.

But the touchy part I think is that the customer might click on the link from web.

Is it possible to manage it with appium? Automatically detect the change from browser (chrome) to app (currently the popup offering possibility to launch other app, and after click; launch driver.launchApp(apk selected)).

I have just used appium to launch mobile App until now, so my questions might be stupid. (Well I tried with browser a few minutes ago but it seems the popup detection seems a bit touchy, I'm not sure we can easily switch context like that -from browser to app-).

**Comment by khallbec** [comment]
I'd like to second this suggestion.
Even if we could just feed in a URL that appium "opens". Since the deep links aren't usually "valid" URL's I can't make selenium do this. It complains that it isn't a valid URL.

**Comment by sebv** [comment]
Not sure how to act on this right now. Moving to new feature, we'll look at this again after appium rewrite.

**Comment by yunduankaifa** [comment]
hi , is this feature has been implemented?

**Comment by imurchie** [comment]
This has been implemented in iOS

**Comment by skovhus** [comment]
@imurchie I cannot find documentation for this... 

The only thing related I see is the changelog entry for 1.6.5:

> Allow setting url in native context, for opening deep links.

But searching in the commits I cannot seem to find the changes... Please advice. I'll happily contribute with some documentation.

Is it possible to deep link into an app using 1.6.3? Amazon Device Farm only supports this version currently.

**Comment by jlipps** [comment]
@skovhus this was implemented in the xcuitest driver. Are you sure you were looking at that one? the way to use is is to call `driver.url(scheme://etc)` where `scheme` is your deep-linking scheme.

**Comment by skovhus** [comment]
Ah, no. The different projects and how they are wired together is still a mystery to me. Any place where I can read about this (except for digging into the source)?

Do you know if this is supported for Android?

Thanks for taking your time. : )

**Comment by jlipps** [comment]
Yes, it works in Android. And to use the XCUITest driver, check out the new doc at https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest.md.
