### ISSUE TITLE
sendKeys doesn't work after switch to another app with Home button on iOS

### ISSUE THREAD

**Issue by polaris007** [appium/appium#5211]
My environment is iPhone 4, iOS 7.1.2,  Appium 1.3.7 on Mac OS 10.9 with XCode 6.2.
My scenario is:
1. Start AppA with Appium Inspector
2. Click Home button on iPhone
3. Click icon of another AppB
In AppB, I could locate the UI elements. But I can't send keys to TextField. And tapping Buttons doesn't work, either. Appium will hang if I perform such operations.
But if I tap at coordinate of a key on the soft keyboard, the key can be input to TextField. Also, tapping at coordinate of a Button can make the Button be clicked.

Firstly, I am not sure whether such scenario (switching between multiple apps) is supported. But seems it can work by tapping at coordinates. Is it possible to make sendKeys and all other APIs (click, etc) also work?

I also tried similar scenario with Java codes, The behavior is the same.

**Comment by jlipps** [comment]
Instruments doesn't support automating multiple apps on iOS (it never did). It no longer crashes, but commands hang indefinitely.

**Comment by polaris007** [comment]
Thanks Jonathan,
I have a further question about the issue. As you said, Instruments doesn't support automating multiple apps. But I could tap at a coordinate of a key on the soft keyboard to input keys on the second app. Does it mean, this way doesn't depend on Instruments, so it is expected to work? Or does it just happen to work and might not work in different environments?
