### ISSUE TITLE
Not able to select kendo drop down 

### ISSUE THREAD

**Issue by soujanyalaxmi** [appium/appium#5214]
Hi,

i am trying to select an item from kendo drop down , 

kendo renders the control in custom formatt(combination of mutple HTML controls

please let mw know if Appium suports Kendo UI controls
Thanks !!!

**Comment by sebv** [comment]
Better ask this kind of question on appium discuss: https://discuss.appium.io/

And provide more information about how it is failing.

**Comment by sebv** [comment]
Closing, please go to appium discuss for support.
