### ISSUE TITLE
Launch Safari on 7.1 using xCode 6.1 + 

### ISSUE THREAD

**Issue by patotskiy** [appium/appium#5215]
Env: 
1. Appium 1.4.1
2. xCode 6.3.2 6.2.0 6.1.0

Caps: 
        capabilities.setCapability("browserName", "Safari");
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("deviceName","iPad 2");
        capabilities.setCapability("platformVersion", "7.1");
        capabilities.setCapability("noReset", "true");
        capabilities.setCapability("newCommandTimeout","180");

Log: https://gist.github.com/patotskiy/edf1f18239c347ecc7de

Need to launch Safari on old SKD on new xCode, but after launching Simulator following error is appears:

The operation couldn't be completed (launchServicesError )

**Comment by patotskiy** [comment]
Any updates? :-)

**Comment by sebv** [comment]
Could you post the error log?

Make sure you run the authorize script.

**Comment by patotskiy** [comment]
Error log: https://gist.github.com/patotskiy/edf1f18239c347ecc7de

For 8.x SDK Safari work fine, using xCode 5.1.1 I can launch safari.But if  I use xCode 6.1+ and SDK 7.1, after launching Simulator I observe error message and appium restarts simulator

**Comment by sebv** [comment]
You could try to upgrade xCode to 6.3.2.

**Comment by sebv** [comment]
And manually go to the simulator and start Safari to see if it is sound.

**Comment by patotskiy** [comment]
manually I can launch Safari, but through appium i can not do that.

**Comment by sebv** [comment]
Start by upgrading xCode.

**Comment by patotskiy** [comment]
Appium version: 1.4.0
xCode 6.3.2

error: Could not prepare mobile safari: Error: We don't have write access to /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 7.1.simruntime/Contents/Resources/RuntimeRoot/Applications/MobileSafari.app, please re-run authorize as yauheni_patotski

**Comment by sebv** [comment]
You need to rerun the authorization script.

**Comment by patotskiy** [comment]
./authorize-ios.js 
Enabling DevToolsSecurity
Updating security db for developer access
Granting access to built-in simulator apps
Encountered an issue chmodding iOS sim app dirs. This may be because they don't exist on your system, which is not necessarily a problem. The error was: stderr maxBuffer exceeded.
Authorization successful

**Comment by patotskiy** [comment]
I fix this.
I execute chown manually

**Comment by sebv** [comment]
It's not the only thing the authorize script does.

**Comment by patotskiy** [comment]
autorize script does not work at all :-)

**Comment by sebv** [comment]
You need to run it with sudo.

**Comment by patotskiy** [comment]
Thank you Kind sir.

**Comment by sebv** [comment]
You're welcome...can this be closed?

**Comment by fionazj** [comment]
Hi patotskiy , 
I met same problems as yours, but i change the priority of the whole MobileSafari.app to 777, still got this error.. would you please send me some advise....

Thanks...
