### ISSUE TITLE
iOS Simulator is not honouring the flight mode or wifi off

### ISSUE THREAD

**Issue by diptirlenka** [appium/appium#5220]
Hi ,

I have successfully able to put the application in background .
2-->Then change the mode of wifi to off as well as flight mode to off but after relaunch, i am not able to take those effect in simulator.

i.e after flight mode is ON , still i am able to use the network.

**Comment by sebv** [comment]
I don't think flightMode work on iOS, in the code it is marked as not implemented:
https://github.com/appium/appium/blob/master/lib/devices/ios/ios-controller.js#L633

**Comment by jlipps** [comment]
that's correct, it's not supported in ios. you can emulate it by shelling out to various commands that turn the network interface of the machine off though.

**Comment by diptirlenka** [comment]
Can you tell me how can we do that ?

**Comment by jlipps** [comment]
Unfortunately, I don't remember offhand. Some judicious googling will help you in this case.
