### ISSUE TITLE
Unable to run ios-webkit-debug-proxy-launcher on multiple devices

### ISSUE THREAD

**Issue by spatchamatla** [appium/appium#5223]
Im able to run ios-webkit-debug-proxy on iPad 4 using
```
./bin/ios-webkit-debug-proxy-launcher.js -c <UDID>:27753 -d
```

But when i tried to run the same with iPad Air 2 it still says running and just shows that one single line
```
RUNNING: ios_webkit_debug_proxy -c <UDID>:27753 -d
```
i tried with the different ports but still the same issue.

updating with the appium and ios-webkit-debug-proxy logs::

Started Appium using
```
appium
```
and the logs for appium::
```
<User>-mac:appium <User>$ node lib/server/main.js
info: Welcome to Appium v1.4.0 (REV 4ce4d44e87729d7aa32c5a7b323d6429b24fddc0)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
```
and for ios-webkit-debug-proxy
```
./bin/ios-webkit-debug-proxy-launcher.js -c <UUID>:27753 -d
```
and logs
```
RUNNING: ios_webkit_debug_proxy -c <UUID>:27753 -d
```
But when i tried it on iPad4, it just runs fine.

**Comment by sebv** [comment]
i think internally appium use just just one port to talk to the proxy, so it doesn't work to run 2 at the same time.
@jlipps maybe you know more about that?

**Comment by spatchamatla** [comment]
I'm running tests on one device after another. I ran the test on iPad4 which ran smoothly but when i try to connect iPadAir2 and ran 
```
./bin/ios-webkit-debug-proxy-launcher.js -c <UUID>:27753 -d
```
im not seeing any logs in the ios-webkit-debug-proxy console other than
```
RUNNING: ios_webkit_debug_proxy -c <UUID>:27753 -d
```
but ultimately we want to run in parallel.

**Comment by spatchamatla** [comment]
appium runs fine using
```
node lib/server/main.js -p 4476 -U <UUID>
```
and its able to run fine
```
info: Welcome to Appium v1.4.0 (REV 4ce4d44e87729d7aa32c5a7b323d6429b24fddc0)
info: Appium REST http interface listener started on 0.0.0.0:4476
info: [debug] Non-default server args: {"udid":"<UUID>","port":4476}
info: Console LogLevel: debug
```

**Comment by sebv** [comment]
Not 100% sure but you I think need to terminate the first ios_webkit_debug_proxy process before starting the second one.

**Comment by spatchamatla** [comment]
i terminated both appium and ios_webkit_debug_proxy before running it on another iPad

**Comment by spatchamatla** [comment]
i think i found, since the ipad Air 2 is new, i for to turn on Web Inspector, in Safari Advance settings. Now its running fine. You can close this issue.

**Comment by siva2503** [comment]
There is a command provided by appium "--webkit-debug-proxy-port " , specifying this with the appium trigger will enable triggering appium server connecting to different iOS_webkit_debug_proxy ports.

Ex:

/Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/build/lib/main.js --address "127.0.0.1" --debug-log-spacing --device-name "iPhone 6S Plus" --webkit-debug-proxy-port 9227
