### ISSUE TITLE
Write XCUITestDriver as a new iOS backend (in Swift)

### ISSUE THREAD

**Issue by jdeff** [appium/appium#5225]
Oh man this is going to be fun.

**Comment by jdeff** [comment]
Sign me up for helping out with this.

**Comment by sebv** [comment]
We'll be happy to have new pp helping with the project. 

ping @jlipps

**Comment by jlipps** [comment]
@jdeff you will want to familiarize yourself with our appium rearchitecture which is currently in progress (https://github.com/appium/appium/issues/5169). I would recommend starting with the new architecture rather than hacking on the current codebase. it's nice because everything will be in its own self-contained repo (for example, check out a fake driver at https://github.com/appium/appium-fake-driver)

**Comment by jlipps** [comment]
cc @penguinho who has also done some research into this

**Comment by jlipps** [comment]
and my thought with this is not that it will be a replacement for the uiautomation-based ios driver, but that it will live side-by-side until we deprecate the old one, if in fact we choose to. in other words, this will belong in an appium-xcuitest-driver package, and export a XCUITestDriver, which will be triggered by a special automationName in caps like this (just as we do for Selendroid):

```js
{
  platformName: 'iOS',
  platformVersion: '9.0',
  deviceName: 'iPhone Simulator',
  app: 'xxx',
  automationName: 'XCUITest'
}
```

**Comment by ericwengelking** [comment]
@jlipps Are there plans for this new driver to support something simliar to MobileBy.IosUIAutomation(final String uiautomationText)?  Of course instead of passing in the javascript uiautomation string you would pass in the swift locator string.

**Comment by jlipps** [comment]
@ericwengelking there are currently no plans for that. Does swift even have 'eval'? I don't think so..?

**Comment by ericwengelking** [comment]
@jlipps @jdeff are there any updates on the progress of this enhancement?

**Comment by jlipps** [comment]
@Jonahss will be leading this charge very soon, it will be part of the effort to support facebook's new ios backend.

**Comment by Jonahss** [comment]
Work is being done together with facebook webdriveragent project.
see github.com/appium/appium-webdriveragent-driver     the XCUITest branch.

**Comment by ericwengelking** [comment]
:tada: :balloon:

**Comment by SrinivasanTarget** [comment]
@triager please close
