### ISSUE TITLE
EditText.clear() doesn't work due to triggerring a popup menu on Android device.

### ISSUE THREAD

**Issue by qwert321** [appium/appium#5226]
This is a blocker issue, I didn't find any workaround so far.
Any help and clues?!
Hope it is my wrong usage about the clear().
## The test code below with Android default Calculator (by appium python client):

```
    el = driver.find_elements_by_class_name('android.widget.EditText')
    assert el is not None
    el.clear()
```

---

It will trigger a popup context menu, with cut/copy/paste items.
Since no one to handle the popup meun, then .clear() failed finally.

Two things made it worse!
1. .send_keys() and set_text() will call .clear() automatically, so ,these two fundamental functions will fail too. Actually, I find the issue from .send_keys().
2. It's difficult to workaround it with inserting a clicking action on menu item to make clear() success, since the clear() action is one step. Any action follows the .clear() would be executed after the clear() failed.
## I tried latest versions:

Appium: 1.4.1
selenium (2.46.0) -- (with Appium 1.4.1, it's 2.45.0, same issue even I upgraded to 2.46.0)
Appium-Python-Client (0.14)

Mac OS: 10.10
device with Android : 4.4.2

Thanks.

**Comment by sebv** [comment]
ping @imurchie @moiz @jlipps you know a way to deal with that, seem to be a recurrent issue.

**Comment by imurchie** [comment]
I don't know any way to do it as the code stands now.

At the app level, you can try setting the `android.widget.EditText` to have `android:inputType="textNoSuggestions"`. I'm not sure if that will change anything, though.

**Comment by sebv** [comment]
Feature: enhance  the Android typing api.

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
