### ISSUE TITLE
Arguments to path.resolve must be strings (Selenium::WebDriver::Error::WebDriverError)

### ISSUE THREAD

**Issue by semyasem** [appium/appium#5235]
Hey guys, 

First time using Appium here. I went and tried to download some of the examples on the official site for a quick test but I was always getting
".rvm/gems/ruby-2.2.2/gems/selenium-webdriver-2.46.2/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok': Arguments to path.resolve must be strings (Selenium::WebDriver::Error::WebDriverError)"
each time I run a test. 

Anyone familiar with that error? I don't what info I should provide to help troubleshooting, please let me know what you need I'll post here. 

Much appreciated,

**Comment by sebv** [comment]
Could you post full server log (in gist)? thx.

**Comment by semyasem** [comment]
Hey Sebv, 

Sorry for the late replay, here you go: https://gist.github.com/semyasem/881813fe76fabc4326c4

Trying to figure out what went wrong, it looks like that error only happens when running Appium using command line. Test is running fine using Appium.app

**Comment by sebv** [comment]
Could you also post the beginning of the log, where appium and the session starts.

**Comment by semyasem** [comment]
Here're all logs I could find: 
https://gist.github.com/semyasem/19659d4524642436afff
and
https://gist.github.com/semyasem/56193acd94b84fa9e026

**Comment by sebv** [comment]
Could you retry with 1.4.3, 1.4.2 had a dependency bug.

**Comment by semyasem** [comment]
Error is gone on 1.4.3 :) 
Thanks for your help :+1:
