### ISSUE TITLE
How to put the running iOS application in iPhone simulator using appium or any other way?

### ISSUE THREAD

**Issue by diptirlenka** [appium/appium#5237]
How to put the running application in iPhone simulator using appium or any other method.

I am using 

 try {
                Thread.sleep(3000);
                Robot robot = new Robot();

                // Script for setting iPhone Simulator to foreground
                String[] cmd = {"osascript", "-e", "tell application \"iPhone Simulator\" to activate"};
                Process ls = Runtime.getRuntime().exec(cmd);
                ls.waitFor();

                robot.keyPress(KeyEvent.VK_META);
                robot.keyPress(KeyEvent.VK_SHIFT);
                robot.keyPress(KeyEvent.VK_H);

                robot.keyRelease(KeyEvent.VK_H);
                robot.keyRelease(KeyEvent.VK_SHIFT);
                robot.keyRelease(KeyEvent.VK_META);
                Thread.sleep(6000);
            } catch (Exception e) {
                Log.warn("Problem with closing using home button\n\n" + e.getMessage());
            }

**Comment by sebv** [comment]
Doc is here: appium.io/slate/en/master/
Please go to Appium discuss https://discuss.appium.io/ for support.
