### ISSUE TITLE
error: Unable to load node configuration file to register with grid

### ISSUE THREAD

**Issue by JamalMSaad** [appium/appium#5241]
Hi,
I have appium 1.4.0 version , and when i start appium and launch it , I am getting "error: Unable to load node configuration file to register with grid" issue , also the background of the appium screen is now in white , how can i reverted back to black (please see the attached screen shot)

Thx
Jamal
![screen shot 2015-06-11 at 9 51 56 am](https://cloud.githubusercontent.com/assets/12841220/8101408/a1dd4e62-101f-11e5-84d3-29fcd48c3b51.png)

**Comment by sebv** [comment]
This is a GUI issue, please try to reinstall and open an issue here if this does not solve your issue:
https://github.com/appium/appium-dot-app

**Comment by sebv** [comment]
Closing, this is being dealt with in appium-dot-app.

**Comment by dcbartlett** [comment]
I'm seeing this error from the console running 

```bash
appium --nodeconfig ./config.json
info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"nodeconfig":"./config.json"}
info: Console LogLevel: debug
error: Unable to load node configuration file to register with grid
```
