### ISSUE TITLE
Swipe on elements inside iOS 8.3 UIWebview is not working 

### ISSUE THREAD

**Issue by ChathuraP** [appium/appium#5244]
Appium server version : 1.3.7 (Ophiuchus)
Platform : MAC
Device : iPad
iOS : iOS 8.3
Orientation : Landscape

![screen shot 2015-06-11 at 12 17 21 pm](https://cloud.githubusercontent.com/assets/12408685/8105273/4afcec7a-1055-11e5-8c9f-97ff713a5971.png)

My app structure is open  a webview form the iPad and shows HTML content in it. We use iScroll JS library to create scrollable lists
and I need to scroll the list of elements using swipe or scroll. 

XML from the appium GUI shows this structure.
AppiumAUT > UIAApplication > UIAWindow > UIAScrollView > UIAWebView > UIAStaticText

currently “tap" event and "send keys text enter" is working fine. But I can’t scroll the view or preform swipe on table rows.

I tried these ways

1 .
        HashMap<String, Double> map = new HashMap<String, Double>();
        map.put("touchCount", 1.0);
        map.put("startX", 665.0);
        map.put("startY", 346.0);
        map.put("endX", 674.0);
        map.put("endY", 583.0);
        map.put("duration", 1.632265625);

        JavascriptExecutor executor =  (JavascriptExecutor)driver;
        executor.executeScript("mobile: swipe", map );

Error log : 

org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 6 milliseconds

2 .

WebElement element = wd.findElement(By.xpath("//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAWebView[1]/UIAStaticText[46]"));
        new Actions(wd).dragAndDropBy(element, 0, 200).perform();

Error log :

org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5 milliseconds

3.
Tried in Appium GUI Inspector swipe function with arguments( fingers 1, Duration 2, begin <418,315>, end <418,555>)

Error log :

info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","origValue":"connect ECONNREFUSED"},"sessionId":"32184d22-b4d0-440c-bb86-b0847835b38d"}
info: <-- GET /wd/hub/session/32184d22-b4d0-440c-bb86-b0847835b38d/contexts 500 2.584 ms - 293 

Since this Swipe function is critical for this automation I need a help.

**Comment by sebv** [comment]
You need to be in the native context.

**Comment by ChathuraP** [comment]
I check the context and its NATIVE_APP but gives the same error
org.openqa.selenium.WebDriverException: Not yet implemented. Please help us: http://appium.io/get-involved.html (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 8 milliseconds

**Comment by sebv** [comment]
Could you post full server log in a gist? thx.

**Comment by ChathuraP** [comment]
https://gist.githubusercontent.com/ChathuraP/5268df695656d2ad2fa6/raw/appium.log

**Comment by ChathuraP** [comment]
sorry I accidentally click on close. server basically return this error :
info: <-- POST /wd/hub/session/d97e98e3-9faf-446f-9c4f-3c18b7d71cf0/element/3/click 200 1224.559 ms - 74 {"status":0,"value":"","sessionId":"d97e98e3-9faf-446f-9c4f-3c18b7d71cf0"}

info: --> POST /wd/hub/session/d97e98e3-9faf-446f-9c4f-3c18b7d71cf0/log {"type":"appium_server"}

info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Unsupported log type 'appium_server' for this device, supported types : {\"syslog\":\"Logs for iOS applications on real devices and simulators\",\"crashlog\":\"Crash logs for iOS applications on real devices and simulators\",\"performance\":\"Performance Logs - Debug Timelines on real devices and simulators\"}"},"sessionId":"d97e98e3-9faf-446f-9c4f-3c18b7d71cf0"}

**Comment by sebv** [comment]
Those have nothing to do with this issue you missed this:
 
```
2015-06-11 10:18:13:423 - info: [debug] Tried to execute non-existent mobile command 'swipe'. Most mobile commands have been ported to official client library methods. Please check your Appium library for more information and documentation
```
You need to use the multitouch action api.

**Comment by ChathuraP** [comment]
Thanks a lot Seb Its working now. I use
TouchAction action = new TouchAction(driver);
        action.press(element).waitAction(300).moveTo(element1).release().perform();
