### ISSUE TITLE
Appium is using the wrong temporary directory, node is picking up the wrong temp directory 

### ISSUE THREAD

**Issue by ioanm** [appium/appium#5246]
Appium 1.4.3

Appium is using the wrong temporary directory 
node is picking up the wrong temp directory 

adding this 2 lines:
  console.log("user: " + process.env.USER)
  console.log("tmpDir: " + os.tmpDir() + " or " + process.env.TMPDIR)
to tempdir.js (lines 14 and 15 )
are returning a a different tempDir for the same user then when running this in terminal 

Terminal:
os.tmpDir()
'/var/folders/jc/ddhc1fp57q103ptrbft1892c0000wf/T/'

Appium logs:
info: [debug] Copying local zip to tmp dir
user: jenkins
tmpDir: /var/folders/x_/6g37tp0d0hs6nkzqdpm7dl5w0000wf/T/ or /var/folders/x_/6g37tp0d0hs6nkzqdpm7dl5w0000wf/T/
error: Unhandled error: TypeError: Cannot read property 'path' of undefined

**Comment by sebv** [comment]
Please provide full log.

**Comment by moizjv** [comment]
@ioanm ping!

**Comment by SrinivasanTarget** [comment]
@triager please close
