### ISSUE TITLE
Appium Launching Chrome Browser instead of Automation Native app

### ISSUE THREAD

**Issue by misskhushboo** [appium/appium#5250]
I am using the following desired capabilities to automate native android app on Samsung S5:
@Test
public void setUp(){
	
        File classpathRoot = new File(System.getProperty("user.dir"));
        File appDir 	= new File(classpathRoot, "\\lib");
        File app 		= new File(appDir, "demo.apk");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("platformVersion", "4.4");
        capabilities.setCapability("deviceName", "Samsung S5");
        //capabilities.setCapability("app", app.getAbsolutePath());
        capabilities.setCapability("autoLaunch", true);
        capabilities.setCapability("udid", "320821e688eb6123");    
        capabilities.setCapability("appPackage", "com.demo.test.demo"); 
        capabilities.setCapability("appActivity", ".RootActivity"); 
        try {
        	WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
			
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
	}

I am getting the following response on Appium:
> Killed Node Server.
> Node Server Process Ended
> Starting Node Server
> warn: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
> info: Welcome to Appium v1.4.0 (REV 8f63e2f91ef7907aed8bda763f4e5ca08e86970a)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"18","automationName":"Appium","browserName":"Chrome"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"appPackage":"com.demo.test.demo","appActivity":".RootActivity","autoLaunch":true,"platformVersion":"4.4","platformName":"Android","udid":"320821e688eb6123","deviceName":"Samsung S5"}}
> info: Client User-Agent string: Apache-HttpClient/4.4.1 (Java/1.8.0_45)
> info: Set mode: Proxying straight through to Chromedriver
> info: [debug] Looks like we want chrome on android
> info: [debug] Creating new appium session b1d9eff0-e961-4baa-b5e4-e42b435d4c10
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from D:\Android_SDK\sdk\platform-tools\adb.exe
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\Android_SDK\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device 320821e688eb6123
> info: [debug] Setting device id to 320821e688eb6123
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: D:\Android_SDK\sdk\platform-tools\adb.exe -s 320821e688eb6123 wait-for-device
> info: [debug] executing cmd: D:\Android_SDK\sdk\platform-tools\adb.exe -s 320821e688eb6123 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Set chromedriver binary as: C:\Program Files (x86)\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: Set chromedriver binary as: C:\Program Files (x86)\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: D:\Android_SDK\sdk\platform-tools\adb.exe -s 320821e688eb6123 install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: [debug] executing cmd: D:\Android_SDK\sdk\platform-tools\adb.exe -s 320821e688eb6123 shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: D:\Android_SDK\sdk\platform-tools\adb.exe -s 320821e688eb6123 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: D:\Android_SDK\sdk\platform-tools\adb.exe -s 320821e688eb6123 push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: D:\Android_SDK\sdk\platform-tools\adb.exe -s 320821e688eb6123 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: D:\Android_SDK\sdk\platform-tools\adb.exe -s 320821e688eb6123 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.chrome -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
> info: [debug] dataDir set to: /data/local/tmp
> info: Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
> info: No old chromedrivers seemed to exist
> info: Spawning chromedriver with: C:\Program Files (x86)\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe --url-base=wd/hub --port=9515
> info: [CHROMEDRIVER STDOUT] Starting ChromeDriver 2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3) on port 9515
> Only local connections are allowed.
> info: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
> info: Got response with status 200: {"sessionId":"","status":0,"value":{"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Windows NT","version":"6.1 SP1"}}}
> info: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"320821e688eb6123"}}}
> info: Got response with status 200: {"sessionId":"4184bcd8d216e60efc91764549469abf","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},"cssSelect...
> info: [debug] Overriding session id with "4184bcd8d216e60efc91764549469abf"
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId 4184bcd8d216e60efc91764549469abf
> info: <-- POST /wd/hub/session 303 9100.246 ms - 70 
> info: --> GET /wd/hub/session/4184bcd8d216e60efc91764549469abf {}
> info: Proxying [GET /wd/hub/session/4184bcd8d216e60efc91764549469abf] to [GET http://127.0.0.1:9515/wd/hub/session/4184bcd8d216e60efc91764549469abf] with body: {}
> info: Got response with status 200: {"sessionId":"4184bcd8d216e60efc91764549469abf","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},"cssSelect...
> info: <-- GET /wd/hub/session/4184bcd8d216e60efc91764549469abf 200 7.486 ms - 507 

Why chrome browser is getting launched when I have asked to automate Android Native app?

**Comment by sebv** [comment]
You've asked for it: "browserName":"Chrome"

**Comment by misskhushboo** [comment]
I did'nt see I mentioned browserName: chrome anywhere in the Desired Capabilities?

**Comment by sebv** [comment]
It was passed to the server as default argument, which is probably a bad idea.

**Comment by misskhushboo** [comment]
Its no where written that Chrome is the default server argument for "browserName" parameter. However I have added "app" which is incompatible with "browserName". Now even if I do this:
capabilities.setCapability("browserName","");
There is no change.

**Comment by sebv** [comment]
Can you try when starting appium without any arguments?

**Comment by sebv** [comment]
just pass logNoColor, the rest you don't need.

**Comment by misskhushboo** [comment]
I am not getting you. What is logNoColor. Where should I pass this and what arguments should be removed?

**Comment by sebv** [comment]
You have this in your log
```
info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"18","automationName":"Appium","browserName":"Chrome"}
```
That mean you started appium with tons of options.

**Comment by misskhushboo** [comment]
I have listed what options I have passed while starting the Appium. I have not passed browserName: Chrome. If this is printed in Appium then probably this is a bug. Also I think the parameters I passed are all required.
Now reduced to these parameters, still chrome is launching:
        File classpathRoot = new File(System.getProperty("user.dir"));
        File appDir 	= new File(classpathRoot, "\\lib");
	File app 		= new File(appDir, "MoneyDemoExample.apk");
	DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("platformVersion", "4.4");
        capabilities.setCapability("deviceName", "Samsung S5");
        capabilities.setCapability("app", app.getAbsolutePath());
try {
        	WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
			WebElement element= driver.findElement(By.name("username"));
			System.out.println("Got hold of web element="+element);
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}

**Comment by sebv** [comment]
```
I have listed what options I have passed while starting the Appium. 
```
I meant the appium server, not the session, and if you look above you didn't.

Go to the appium root dir, and start the server with `appium` or `node .` to be sure.

**Comment by misskhushboo** [comment]
Navigated to the directory where Appium is installed and started appium through command prompt cmd: "Appium". This launched Appium portal but did not started Appium. When I started it is the same with browsreName as chrome.
Secondly, tried launching Node directly through command prompt. It says node. is not recognized.

**Comment by misskhushboo** [comment]
Nevethless what Appium is doing, I have to automate native app, what modification should I do in capabilities that my app is automated? I am using appium 1.4.

**Comment by misskhushboo** [comment]
Found Chrome was selected by default by Appium. Deselected it and started Appium, It is now working.

**Comment by sebv** [comment]
Nice!

**Comment by misskhushboo** [comment]
Thanks for the advice.

**Comment by SanthoshGoud** [comment]
I am facing the same issue , where I can deselect the default chrome option?
