### ISSUE TITLE
can't run inspection on real device

### ISSUE THREAD

**Issue by BernieLiu** [appium/appium#5251]
i provide the bundleID, uuid, app path(.ipa), can't work

the alert says "Be sure the Appium server is running with an application opened by using the "App Path" parameter in Appium.app (along with package and activity for Android) or by connecting with selenium client and supplying this in the desired capabilities object."
and the log 
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: The following desired capabilities are required, but were not provided: deviceName)","origValue":"The following desired capabilities are required, but were not provided: deviceName"},"sessionId":null}

but in ios settings, there is no place i can input a device name, only  uuid.

**Comment by sebv** [comment]
You don't have `force-device` in ios settings?

**Comment by BernieLiu** [comment]
yes, after setting device to iphone5s, the error info become "counld not initialize ideviceinstaller"

**Comment by BernieLiu** [comment]
there are issues with the same error, i think now i can fix it, thank you @sebv
