### ISSUE TITLE
"Failed to Dump Window Hierarchy" when emojis are on screen.

### ISSUE THREAD

**Issue by pjayaram** [appium/appium#5252]
That's what I get from `arc` when I run the `page` command.  And automated tests fail too whenever there are emojis on screen.  **lorna** from the Appium community has observed this as well:
https://discuss.appium.io/t/unable-to-inspect-page-unknownerror-failed-to-dump-window-hierarchy/3815

There are a few emojis that don't cause problems, such as the church (with the cross and no heart), but most do (such as the "cool" sunglasses face).  It's also worth noting that there's no problems when the emoji are displayed on the keyboard.  I'm testing on a prototype LG G4, but I'm pretty sure this same issue happened on a prototype Galaxy Note 4 (or was it 5?) as well.  The issue doesn't seem to be confined to one app; try it on the URL bar of Chrome for example.  I'm on Android version 5.02, and Appium version 1.4.3.

**Comment by sebv** [comment]
Assuming this is a uiautomator bug,  @moizjv @bootstraponline @jlipps where do we report those?

**Comment by bootstraponline** [comment]
uiautomator bugs are [reported on the android issue tracker](https://code.google.com/p/android/issues). The uiautomator bugs I've reported/commented on have been closed as obsolete since Google has moved onto uiautomator v2 which is a different framework from what appium is using. uiautomator v1 bugs can only be resolved with a new release of the android OS which makes it not a great framework.

**Comment by pjayaram** [comment]
Yes, I think you are right that this is actually not an Appium bug, since I believe `uiautomatorviewer` was giving problems as well on screens with emoji.  I can confirm this on Monday when I'm back at work.

**Comment by bootstraponline** [comment]
This is the [exact uiautomator bug](https://code.google.com/p/android/issues/detail?id=62906). These kinds of issues will be addressed in appium when we move to the new android automation backend.

**Comment by pjayaram** [comment]
Sounds good.  Should I go ahead and close this issue then?

**Comment by Jonahss** [comment]
ahahahhaha such a funny bug. Well not much we can do since it's an android bug :(

**Comment by malheirosrafa** [comment]
Google corrected the problem, now uiautomatorviewer open views with emoji, how is possible to update the project and use the last version of uiautomator?

**Comment by Jonahss** [comment]
has it been fixed in Uiautomator? or the newer UIautomator 2 api?

If uiautomator 2, we are working on implementing that as a new driver for appium. https://github.com/appium/appium-uiautomator2-driver

**Comment by malheirosrafa** [comment]
UiAutomator2. Maybe using v1.5 branch already use this driver?

**Comment by Jonahss** [comment]
Nope. v1.5 is a rewrite of appium, but is still the same features and
backed. UiAutomator2 driver will be coming later.
Appium 1.5 makes it much easier for us to build these new drivers though :)

On Wed, Nov 25, 2015 at 12:55 PM, rafael malheiros <notifications@github.com
