### ISSUE TITLE
Drop down and date picker selection

### ISSUE THREAD

**Issue by Balajikl** [appium/appium#5253]
Hi All,

Pleae help me to find the city from the drop down list and change the date and time in date picker on mobile. I am working on appium and selenium

drop down - http://screencast.com/t/JFMW8Itz

Date and time picker - http://screencast.com/t/4m8vzEGWv

**Comment by sebv** [comment]
Try with `sendKey`.

**Comment by Balajikl** [comment]
Sendkeys will only enter the city in the text box. But as far as the design I need to send keys then city will be populated and later the city has to be selected after sending 'sendkeys'. So how to select from the list?

**Comment by sebv** [comment]
ping @jlipps @imurchie

**Comment by ramdas80** [comment]
scrollToExact("text") function usually works well inside a dropdown list. Try that.

For Date Picker, in my project I am relying on sendKeys for each individual edit box with index [ex: 0 index for Date, 1 index for month and 2 index for Year ...].. this is not reliable, but works for now :)

I will explore more and let you know, if I get any better solution.

**Comment by Jonahss** [comment]
@Balajikl did @ramdas80's advice help?

**Comment by ajayv1** [comment]
SendKeys was not working for me in either case. But i tried inject and its working. 
inject(driver, "var city = document.getElementById('id of the city');city.selectedIndex=1; var ev = document.createEvent('HTMLEvents'); ev.initEvent('change', true, true); month.dispatchEvent(ev);");

and similarly,
for datePicker, you can directly inject date and time by picking id of date field.
