### ISSUE TITLE
Driver session closes before mobile tap is performed

### ISSUE THREAD

**Issue by thivyae** [appium/appium#5254]
Im trying to perform long press action here.The command goes to appium queue but the elemnt is not clicked in the android screen 

 return this.driver.elementByName('My element', function(err, els) {
        console.log(els.text());
        var tapOpts = {
          duration: 3
          , x: 0.5
          , y: 0.5
          , element: els.value
        };
that.driver.execute("mobile: tap", [tapOpts], function(err) {
  console.log("done");
});
}) .then(function(){
      console.log("done longpress");
    });
};

Appium logs:
info: --> POST /wd/hub/session/3705cc01-68b2-418c-905f-351179c533e0/element {"using":"name","value":"My element"}
warn: [DEPRECATED] The name locator strategy has been deprecated and will be removed.  Please use the accessibility id locator strategy instead.
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"name","selector":"My element","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"name","selector":"My element","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding My element using NAME with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=My element, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[TEXT=My element, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"ELEMENT":"24"},"status":0}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"24"},"sessionId":"3705cc01-68b2-418c-905f-351179c533e0"}
info: <-- POST /wd/hub/session/3705cc01-68b2-418c-905f-351179c533e0/element 200 18.823 ms - 88 {"status":0,"value":{"ELEMENT":"24"},"sessionId":"3705cc01-68b2-418c-905f-351179c533e0"}
info: --> GET /wd/hub/session/3705cc01-68b2-418c-905f-351179c533e0/element/24/text {}

info: [debug] Pushing command to appium work queue: ["element:getText",{"elementId":"24"}]
info: --> POST /wd/hub/session/3705cc01-68b2-418c-905f-351179c533e0/execute {"script":"mobile: tap","args":[{"duration":3,"x":0.5,"y":0.5,"element":"24"}]}
info: [debug] Pushing command to appium work queue: ["click",{"x":0.5,"y":0.5}]
info: --> DELETE /wd/hub/session/3705cc01-68b2-418c-905f-351179c533e0 {}
info: Shutting down appium session
info: [debug] Pressing the HOME button
info: [debug] executing cmd: /users/thivya/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "input keyevent 3"
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"We're in the middle of shutting down the Android device, so your request won't be executed. Sorry!"},"sessionId":null}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"We're in the middle of shutting down the Android device, so your request won't be executed. Sorry!"},"sessionId":null}
info: <-- GET /wd/hub/session/3705cc01-68b2-418c-905f-351179c533e0/element/24/text 500 7.284 ms - 233 
info: <-- POST /wd/hub/session/3705cc01-68b2-418c-905f-351179c533e0/execute 500 6.224 ms - 233 

info: [debug] Stopping logcat capture

info: [debug] Logcat terminated with code null, signal SIGTERM

info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}

**Comment by sebv** [comment]
This api is depreated need to use the touch action api.

**Comment by thivyae** [comment]
I tried even touch action API,It is throwing the below error:

  var action = new wd.TouchAction();
       action
        .longclick({element: elm })
        .release();
       return that.driver.performTouchAction(action);

Appium logs:
info: --> POST /wd/hub/session/41d15856-f522-4623-b684-7da296babc07/touch/perform [{"action":"press","options":{"x":0.5,"y":0.5,"element":"24"}},{"action":"wait","options":{"ms":2}},{"action":"moveTo","options":{"x":0.55,"y":0.55,"element":"24"}},{"action":"release","options":{}}]
info: [debug] Pushing command to appium work queue: ["element:getLocation",{"elementId":"24"}]
info: --> DELETE /wd/hub/session/41d15856-f522-4623-b684-7da296babc07 {}
info: Shutting down appium session
info: [debug] Pressing the HOME button
info: [debug] executing cmd: /users/thivya/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "input keyevent 3"
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"24"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"y":436,"x":0},"status":0}
info: [debug] Pushing command to appium work queue: ["element:getSize",{"elementId":"24"}]
info: [debug] Pushing command to appium work queue: ["element:getLocation",{"elementId":"24"}]
info: [debug] Pushing command to appium work queue: ["element:swipe",{"startX":0.5,"startY":0.5,"endX":null,"endY":null,"steps":0,"elementId":"24"}]
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"We're in the middle of shutting down the Android device, so your request won't be executed. Sorry!"},"sessionId":null}
info: <-- POST /wd/hub/session/41d15856-f522-4623-b684-7da296babc07/touch/perform 500 26.190 ms - 233 

info: [debug] Stopping logcat capture

info: [debug] Logcat terminated with code null, signal SIGTERM

info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
info: [debug] [BOOTSTRAP] [debug] Closed client connection

**Comment by sebv** [comment]
It's the client code calling this, you need to wait for the command to complete.
```
info: --> DELETE /wd/hub/session/41d15856-f522-4623-b684-7da296babc07 {}
```

**Comment by thivyae** [comment]
I added wait statement but nothing works.The command itself is not getting executed

  var action = new wd.TouchAction();
  action
    .longclick({element: els })
    .wait(2)
    .release();
  return that.driver.performTouchAction(action).then(function(){

**Comment by sebv** [comment]
Could you link to a gist with the full server log? thx.

**Comment by thivyae** [comment]
below is the entire code related to the action::

return this.driver.elementByName('My Ristretto !23', function(err, els) {
  var action = new wd.TouchAction(that.driver);
  action
    .longclick({element: els })
    .wait(2)
    .release()
    .perform();
  return that.driver.performTouchAction(action).then(function(){
console.log("done");
});

Appium logs::
info: <-- POST /wd/hub/session/7dfe0ac6-679d-4f09-86ed-4fb11c6b4738/elements 200 2777.208 ms - 107 {"status":0,"value":[{"ELEMENT":"22"},{"ELEMENT":"23"}],"sessionId":"7dfe0ac6-679d-4f09-86ed-4fb11c6b4738"}
info: --> GET /wd/hub/session/7dfe0ac6-679d-4f09-86ed-4fb11c6b4738/element/22/text {}
info: [debug] Pushing command to appium work queue: ["element:getText",{"elementId":"22"}]
info: --> GET /wd/hub/session/7dfe0ac6-679d-4f09-86ed-4fb11c6b4738/element/23/text {}
info: [debug] Pushing command to appium work queue: ["element:getText",{"elementId":"23"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getText","params":{"elementId":"22"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getText

info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"My element","status":0}

info: [debug] Responding to client with success: {"status":0,"value":"My element","sessionId":"7dfe0ac6-679d-4f09-86ed-4fb11c6b4738"}

info: <-- GET /wd/hub/session/7dfe0ac6-679d-4f09-86ed-4fb11c6b4738/element/22/text 200 178.366 ms - 90 {"status":0,"value":"My Ristretto !23","sessionId":"7dfe0ac6-679d-4f09-86ed-4fb11c6b4738"}
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getText","params":{"elementId":"23"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getText
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Create new Recipe","status":0}
info: [debug] Responding to client with success: {"status":0,"value":"Create new Recipe","sessionId":"7dfe0ac6-679d-4f09-86ed-4fb11c6b4738"}
info: <-- GET /wd/hub/session/7dfe0ac6-679d-4f09-86ed-4fb11c6b4738/element/23/text 200 217.355 ms - 91 {"status":0,"value":"Create new Recipe","sessionId":"7dfe0ac6-679d-4f09-86ed-4fb11c6b4738"}

info: --> POST /wd/hub/session/7dfe0ac6-679d-4f09-86ed-4fb11c6b4738/element {"using":"name","value":"My element"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"name","selector":"My element","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"name","selector":"My element","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding My element using NAME with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=My Ristretto !23, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[TEXT=My element, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"ELEMENT":"24"},"status":0}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"24"},"sessionId":"7dfe0ac6-679d-4f09-86ed-4fb11c6b4738"}
info: <-- POST /wd/hub/session/7dfe0ac6-679d-4f09-86ed-4fb11c6b4738/element 200 19.932 ms - 88 {"status":0,"value":{"ELEMENT":"24"},"sessionId":"7dfe0ac6-679d-4f09-86ed-4fb11c6b4738"}
info: --> DELETE /wd/hub/session/7dfe0ac6-679d-4f09-86ed-4fb11c6b4738 {}
info: Shutting down appium session
info: [debug] Pressing the HOME button

info: [debug] executing cmd: /users/thivya/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "input keyevent 3"

info: [debug] Stopping logcat capture

info: [debug] Logcat terminated with code null, signal SIGTERM

info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] [BOOTSTRAP] [debug] Closed client connection

**Comment by sebv** [comment]
You are mixing promise syntax, not gonna work.

**Comment by sebv** [comment]
callback: `this.driver.elementByName('My Ristretto !23', function(err, els) {`
promise: `that.driver.performTouchAction(action).then(function(){`

**Comment by SrinivasanTarget** [comment]
@triager please close
