### ISSUE TITLE
Error: Screen did not unlock, java client 2.2.0, and Windows appium server 1.4.0.

### ISSUE THREAD

**Issue by ashishdd** [appium/appium#5255]
> info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":"180","platformVersion":"4.4.2","deviceName":"AndroidDevice","platformName":"Android","appActivity":"SecuritySettings","udid":"07c565f095488131","appPackage":"com.android.settings","noReset":true}}
> info: Client User-Agent string: Apache-HttpClient/4.3.2 (java 1.5)
> info: Found an existing session to clobber, shutting it down first...
> info: Shutting down appium session
> info: [debug] Pressing the HOME button
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "input keyevent 3"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 107.367
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] UiAutomator shut down normally
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: Old session shut down OK, proceeding to new session
> info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
> info: [debug] Creating new appium session b11ff8f7-cc25-4eab-b86c-7197e3fa0dbb
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_45
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe
> warn: No app capability, can't parse package/activity
> info: [debug] Set chromedriver binary as: C:\Program Files (x86)\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] Using fast reset? false
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device 07c565f095488131
> info: [debug] Setting device id to 07c565f095488131
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 wait-for-device
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: Device API level is: 19
> info: [debug] Extracting strings for language: default
> info: [debug] Apk doesn't exist locally
> info: [debug] Could not get strings, but it looks like we had an old strings file anyway, so ignoring
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "rm -rf /data/local/tmp/strings.json"
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Skipping install since we launched with a package instead of an app path
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.settings -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "dumpsys window"
> info: Unlocking screen
> info: [debug] Screen is locked, trying to unlock
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "dumpsys window"
> info: [debug] Screen is locked, trying to unlock
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "dumpsys window"
> info: [debug] Screen is locked, trying to unlock
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "dumpsys window"
> info: [debug] Screen is locked, trying to unlock
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "dumpsys window"
> info: [debug] Screen is locked, trying to unlock
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "dumpsys window"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 13.422
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] UiAutomator shut down normally
> error: Failed to start an Appium session, err was: Error: Screen did not unlock
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Error: Screen did not unlock
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-controller.js:399:25)
>     at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:1479:4
>     at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:180:9)
>     at ChildProcess.exithandler (child_process.js:635:7)
>     at ChildProcess.EventEmitter.emit (events.js:98:17)
>     at maybeClose (child_process.js:743:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Screen did not unlock)","origValue":"Screen did not unlock"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 24925.699 ms - 164

**Comment by sebv** [comment]
Try to do iit from command line to see if it work:
```
D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
....
info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "dumpsys window"
```

you can also check `adb logcat` , see if there is an error there.

**Comment by ashishdd** [comment]
From command line it is working file

D:\appium_workspace>D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s 07c565f095488131 shell "am start -S -a android.intent.action.MAIN -c android.intent.categor
y.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
Stopping: io.appium.unlock
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.appium.unlock/.Unlock }

Catlogs when trying with appium server:
06-15 12:13:21.403: I/ActivityManager(593): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.appium.unlock/.Unlock} from pid 28120
06-15 12:13:21.703: I/WindowManager(593): Screenshot max retries 4 of Token{423ee4b8 ActivityRecord{42647468 u0 com.android.settings/.SecuritySettings t134}} appWin=Window{42979710 u0 com.android.settings/com.android.settings.SecuritySettings} drawState=4
06-15 12:13:21.703: W/WindowManager(593): Screenshot failure taking screenshot for (768x1280) to layer 21025
06-15 12:13:21.713: D/AndroidRuntime(28120): Shutting down VM
06-15 12:13:21.713: D/jdwp(28120): Got wake-up signal, bailing out of select
06-15 12:13:21.713: D/dalvikvm(28120): Debugger has detached; object registry had 1 entries
06-15 12:13:21.803: D/dalvikvm(28153): Late-enabling CheckJNI
06-15 12:13:21.813: I/ActivityManager(593): Start proc io.appium.unlock for activity io.appium.unlock/.Unlock: pid=28153 uid=10185 gids={50185, 1028, 1015}
06-15 12:13:21.873: V/KeyguardDisableHandler(593): Not disabling keyguard since device policy is enforced
06-15 12:13:21.993: I/ActivityManager(593): Displayed io.appium.unlock/.Unlock: +227ms
06-15 12:13:22.284: D/PhoneStatusBar(684): disable: < EXPAND icons alerts TICKER system_info back* home* RECENT clock* search >
06-15 12:13:22.314: W/InputMethodManagerService(593): Got RemoteException sending setActive(false) notification to pid 28082 uid 10185
06-15 12:13:22.314: W/Binder(4679): Caught a RuntimeException from the binder stub implementation.
06-15 12:13:22.314: W/Binder(4679): java.lang.NullPointerException
06-15 12:13:22.314: W/Binder(4679): 	at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
06-15 12:13:22.314: W/Binder(4679): 	at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
06-15 12:13:22.314: W/Binder(4679): 	at android.os.Binder.execTransact(Binder.java:404)
06-15 12:13:22.314: W/Binder(4679): 	at dalvik.system.NativeStart.run(Native Method)
06-15 12:13:22.324: I/Keyboard.Facilitator(4679): onFinishInput()
06-15 12:13:22.334: V/PhoneStatusBar(684): setLightsOn(true)
06-15 12:13:23.475: D/AndroidRuntime(28177): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
06-15 12:13:23.475: D/AndroidRuntime(28177): CheckJNI is OFF
06-15 12:13:23.495: D/dalvikvm(28177): Trying to load lib libjavacore.so 0x0
06-15 12:13:23.495: D/dalvikvm(28177): Added shared lib libjavacore.so 0x0
06-15 12:13:23.495: D/dalvikvm(28177): Trying to load lib libnativehelper.so 0x0
06-15 12:13:23.495: D/dalvikvm(28177): Added shared lib libnativehelper.so 0x0
06-15 12:13:23.495: D/dalvikvm(28177): No JNI_OnLoad found in libnativehelper.so 0x0, skipping init
06-15 12:13:23.535: D/dalvikvm(28177): Note: class Landroid/app/ActivityManagerNative; has 179 unimplemented (abstract) methods
06-15 12:13:23.785: D/AndroidRuntime(28177): Calling main entry com.android.commands.am.Am
06-15 12:13:23.795: I/ActivityManager(593): Force stopping io.appium.unlock appid=10185 user=0: from pid 28177
06-15 12:13:23.795: I/ActivityManager(593): Killing 28153:io.appium.unlock/u0a185 (adj 0): stop io.appium.unlock
06-15 12:13:23.805: W/InputDispatcher(593): channel '426eaa60 io.appium.unlock/io.appium.unlock.Unlock (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-15 12:13:23.805: E/InputDispatcher(593): channel '426eaa60 io.appium.unlock/io.appium.unlock.Unlock (server)' ~ Channel is unrecoverably broken and will be disposed!
06-15 12:13:23.805: W/InputDispatcher(593): Attempted to unregister already unregistered input channel '426eaa60 io.appium.unlock/io.appium.unlock.Unlock (server)'
06-15 12:13:23.805: I/ActivityManager(593):   Force finishing activity ActivityRecord{4296d778 u0 io.appium.unlock/.Unlock t138}
06-15 12:13:23.805: I/WindowState(593): WIN DEATH: Window{426eaa60 u0 io.appium.unlock/io.appium.unlock.Unlock}
06-15 12:13:23.865: D/PhoneStatusBar(684): disable: < EXPAND icons alerts TICKER system_info BACK* HOME* RECENT CLOCK* search >
06-15 12:13:24.075: I/ActivityManager(593): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.appium.unlock/.Unlock} from pid 28177
06-15 12:13:24.386: I/WindowManager(593): Screenshot max retries 4 of Token{423ee4b8 ActivityRecord{42647468 u0 com.android.settings/.SecuritySettings t134}} appWin=Window{42979710 u0 com.android.settings/com.android.settings.SecuritySettings} drawState=4
06-15 12:13:24.386: W/WindowManager(593): Screenshot failure taking screenshot for (768x1280) to layer 21025
06-15 12:13:24.426: D/AndroidRuntime(28177): Shutting down VM
06-15 12:13:24.426: D/jdwp(28177): Got wake-up signal, bailing out of select
06-15 12:13:24.426: D/dalvikvm(28177): Debugger has detached; object registry had 1 entries
06-15 12:13:24.446: D/dalvikvm(28203): Late-enabling CheckJNI
06-15 12:13:24.446: I/ActivityManager(593): Start proc io.appium.unlock for activity io.appium.unlock/.Unlock: pid=28203 uid=10185 gids={50185, 1028, 1015}
06-15 12:13:24.506: V/KeyguardDisableHandler(593): Not disabling keyguard since device policy is enforced
06-15 12:13:24.616: I/ActivityManager(593): Displayed io.appium.unlock/.Unlock: +203ms
06-15 12:13:24.786: I/AndroidRuntime(27922): VM exiting with result code 0.
06-15 12:13:24.846: D/PhoneStatusBar(684): disable: < EXPAND icons alerts TICKER system_info back* home* RECENT clock* search >
06-15 12:13:24.856: V/PhoneStatusBar(684): setLightsOn(true)
06-15 12:13:24.876: W/InputMethodManagerService(593): Got RemoteException sending setActive(false) notification to pid 28153 uid 10185
06-15 12:13:24.876: W/Binder(4679): Caught a RuntimeException from the binder stub implementation.
06-15 12:13:24.876: W/Binder(4679): java.lang.NullPointerException
06-15 12:13:24.876: W/Binder(4679): 	at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
06-15 12:13:24.876: W/Binder(4679): 	at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
06-15 12:13:24.876: W/Binder(4679): 	at android.os.Binder.execTransact(Binder.java:404)
06-15 12:13:24.876: W/Binder(4679): 	at dalvik.system.NativeStart.run(Native Method)
06-15 12:13:24.886: I/Keyboard.Facilitator(4679): onFinishInput()
06-15 12:13:28.720: D/dalvikvm(817): GC_CONCURRENT freed 445K, 6% free 10598K/11196K, paused 7ms+3ms, total 75ms
06-15 12:13:33.876: I/PowerManagerService(593): Going to sleep due to screen timeout...
06-15 12:13:34.396: D/SurfaceFlinger(174): Screen released, type=0 flinger=0xb7293450
06-15 12:13:34.396: I/Keyboard.Facilitator(4679): onFinishInput()
06-15 12:13:34.406: V/KeyguardHostView(684): Initial transport state: 1, pbstate=0
06-15 12:13:34.487: V/KeyguardHostView(684): music state changed: 0
06-15 12:13:34.567: D/SurfaceControl(593): Excessive delay in blankDisplay() while turning screen off: 176ms
06-15 12:13:34.567: E/ANDR-PERF-LOCK(185): Failed to apply optimization for resource: 4 level: 0

**Comment by sebv** [comment]
Maybe stop taking screenshots when you are unlocking!

**Comment by sebv** [comment]
@jlipps cloud it be a  GUI issue, looks like the code is going crazy taking screenshout while unlocking. On system with limited resources, not a good idea.

**Comment by ashishdd** [comment]
But I am not taking any screenshot in my code, then how it is trying to take screenshot. 
For the Info I am using nexus 4 witn android 4.4.2.

**Comment by sebv** [comment]
Yeah I think it is the GUI which dos that.

**Comment by sebv** [comment]
Actually the GUI didn't ask for it, not too sure where this `screenshot` request is coming from.

**Comment by moizjv** [comment]
@ashishdd is it still an issue?

**Comment by ashishdd** [comment]
yes, it is still an issue.

**Comment by ashishdd** [comment]
I check with nexus 4(Android 4.4.2) and nexus 5(Android 5.0.1). It is working fine with nexus 7(Android 4.3)

**Comment by christian-bromann** [comment]
Have the same issues on the latest Appium running a Cordova app on a Nexus S (API level 22). I don't do any screenshots. It looks like this (boot process starts happening after ~11s):

![testrunner](https://cloud.githubusercontent.com/assets/731337/11968822/91f241da-a910-11e5-9cbb-214da184334d.gif)

Executing the unlock adb command doesn't help. At a certain point the whole device restarts and it throws an error:

```sh
/Users/<USER>/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"
Stopping: io.appium.unlock
android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:496)
        at android.app.ActivityManagerProxy.forceStopPackage(ActivityManagerNative.java:4243)
        at com.android.commands.am.Am.runStart(Am.java:733)
        at com.android.commands.am.Am.onRun(Am.java:305)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:97)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
```

Hope that helps to trace it down.

**Comment by SrinivasanTarget** [comment]
Fixed in https://github.com/appium/appium-android-driver/pull/149

**Comment by SrinivasanTarget** [comment]
@triager please close
