### ISSUE TITLE
AndroidDriver.setNetworkConnection(networkConnectionSetting) is not working on Android 5.0 and above

### ISSUE THREAD

**Issue by ashishdd** [appium/appium#5256]
Hi 
I am using Appium java client 2.2.0 and windows appium server 1.4.0.0.
I am try to switch the network using AndroidDriver.setNetworkConnection(networkConnectionSetting), it is working fine with 4.4.2 and it not working on 5.0 and above.

Let me know I have to do something else.

**Comment by sebv** [comment]
@moizjv @imurchie @jlipps any idea?

**Comment by sebv** [comment]
@ashishdd could you provide server log.

**Comment by ashishdd** [comment]
Appium server logs :+1: 

> info: --> POST /wd/hub/session {"desiredCapabilities":{"deviceName":"Oneplus one","platformName":"Android","appActivity":"com.android.settings.Settings","deviceType":"phone","device":"Android","appPackage":"com.android.settings"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.2 (java 1.5)
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : deviceType, device
> info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
> info: [debug] Creating new appium session dbc86960-acf9-4274-b2ec-658022389834
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_45
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe
> warn: No app capability, can't parse package/activity
> info: [debug] Set chromedriver binary as: C:\Program Files (x86)\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device de6f58e5
> info: [debug] Setting device id to de6f58e5
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 wait-for-device
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 21
> info: Device API level is: 21
> info: [debug] Extracting strings for language: default
> info: [debug] Apk doesn't exist locally
> info: [debug] Could not get strings, but it looks like we had an old strings file anyway, so ignoring
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "rm -rf /data/local/tmp/strings.json"
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Skipping install since we launched with a package instead of an app path
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.settings -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data\/local\/tmp"}
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":false}
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 21
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.android.settings/com.android.settings.Settings"
> info: [debug] Waiting for pkg "com.android.settings" and activity "com.android.settings.Settings" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "dumpsys window windows"
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "getprop ro.build.version.release"
> info: [debug] Device is at release version 5.0.2
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId dbc86960-acf9-4274-b2ec-658022389834
> info: <-- POST /wd/hub/session 303 4289.492 ms - 74 
> info: --> GET /wd/hub/session/dbc86960-acf9-4274-b2ec-658022389834 {}
> info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"5.0.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"deviceName":"Oneplus one","platformName":"Android","appActivity":"com.android.settings.Settings","deviceType":"phone","device":"Android","appPackage":"com.android.settings"},"deviceName":"de6f58e5","platformName":"Android","appActivity":"com.android.settings.Settings","deviceType":"phone","device":"Android","appPackage":"com.android.settings"},"sessionId":"dbc86960-acf9-4274-b2ec-658022389834"}
> info: <-- GET /wd/hub/session/dbc86960-acf9-4274-b2ec-658022389834 200 1.491 ms - 674 {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"5.0.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"deviceName":"Oneplus one","platformName":"Android","appActivity":"com.android.settings.Settings","deviceType":"phone","device":"Android","appPackage":"com.android.settings"},"deviceName":"de6f58e5","platformName":"Android","appActivity":"com.android.settings.Settings","deviceType":"phone","device":"Android","appPackage":"com.android.settings"},"sessionId":"dbc86960-acf9-4274-b2ec-658022389834"}
> info: --> POST /wd/hub/session/dbc86960-acf9-4274-b2ec-658022389834/network_connection {"name":"network_connection","parameters":{"type":4}}
> info: Setting network connection
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "settings put global airplane_mode_on 0"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 kill-server
> error: Unhandled error: Error: read ECONNRESET
>     at errnoException (net.js:904:11)
>     at TCP.onread (net.js:558:19) context: [POST /wd/hub/session {"desiredCapabilities":{"deviceName":"Oneplus one","platformName":"Android","appActivity":"com.android.settings.Settings","deviceType":"phone","device":"Android","appPackage":"com.android.settings"}}]
> info: [debug] UiAutomator exited
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 wait-for-device
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 forward tcp:4724 tcp:4724
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.settings -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":false}
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "am broadcast -a android.intent.action.AIRPLANE_MODE --ez state false"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 kill-server
> error: Unhandled error: Error: read ECONNRESET
>     at errnoException (net.js:904:11)
>     at TCP.onread (net.js:558:19) context: [POST /wd/hub/session {"desiredCapabilities":{"deviceName":"Oneplus one","platformName":"Android","appActivity":"com.android.settings.Settings","deviceType":"phone","device":"Android","appPackage":"com.android.settings"}}]
> info: [debug] UiAutomator exited
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 wait-for-device
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 forward tcp:4724 tcp:4724
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.settings -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":false}
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "am start -n io.appium.settings/.Settings -e wifi off -e data on"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 kill-server
> error: Unhandled error: Error: read ECONNRESET
>     at errnoException (net.js:904:11)
>     at TCP.onread (net.js:558:19) context: [POST /wd/hub/session {"desiredCapabilities":{"deviceName":"Oneplus one","platformName":"Android","appActivity":"com.android.settings.Settings","deviceType":"phone","device":"Android","appPackage":"com.android.settings"}}]
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 wait-for-device
> info: [debug] UiAutomator exited
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 forward tcp:4724 tcp:4724
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.android.settings -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":false}
> info: Getting network connection
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "settings get global airplane_mode_on"
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "settings get global wifi_on"
> info: [debug] executing cmd: D:\Installer\adt-bundle-windows-x86_64-20131030\sdk\platform-tools\adb.exe -s de6f58e5 shell "settings get global mobile_data"
> info: [debug] Responding to client with success: {"status":0,"value":4,"sessionId":"dbc86960-acf9-4274-b2ec-658022389834"}
> info: <-- POST /wd/hub/session/dbc86960-acf9-4274-b2ec-658022389834/network_connection 200 18644.415 ms - 73 {"status":0,"value":4,"sessionId":"dbc86960-acf9-4274-b2ec-658022389834"}
> info: [debug] [BOOTSTRAP] [debug] Emitting system alert message
> info: [debug] Emitting alert message...

**Comment by ashishdd** [comment]
it there any updates on this?

**Comment by moizjv** [comment]
@ashishdd what command are you using?

**Comment by ashishdd** [comment]
NetworkConnectionSetting ncs = new NetworkConnectionSetting(false, false, true);
driver.setNetworkConnection(ncs);

It is not working for "mobile data" only on android 5.0 and above

**Comment by moizjv** [comment]
@ashishdd looks like it works for me on emulator. Can you try switching to airplane mode first and then to mobile_data?
![screen shot 2015-06-18 at 9 59 27 am](https://cloud.githubusercontent.com/assets/1308607/8236951/e458ab52-15a0-11e5-8a8f-d3498cd408be.png)

**Comment by savishy** [comment]
I know this is an old bug but since it is still occurring I thought I would update it.

* Moto E XT1022 (Android 5.1, unrooted)
* Windows
* Appium 1.4.13.1

*In my case, the `ECONNRESET` errors are still seen but the network connection does get switched.*

**Code**

```
s.h.log.info("switch to airplane mode");
NetworkConnectionSetting n = new NetworkConnectionSetting(true,false,false);
s.h.androidDriver.setNetworkConnection(n);
s.h.log.info("switch to 3G mode");
n = new NetworkConnectionSetting(false,false,true);
s.h.androidDriver.setNetworkConnection(n);

```

**Console Logs**

```

 2016-03-10 11:23:24 INFO  AbstractHelper:50 - main switch to airplane mode
[31merror[39m: Unhandled error: Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26) context: [POST /wd/hub/session/f4ec345f-7e94-4465-b728-9d55b3abba47/appium/app/launch {}]
[31merror[39m: Unhandled error: Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26) context: [POST /wd/hub/session/f4ec345f-7e94-4465-b728-9d55b3abba47/appium/app/launch {}]
 2016-03-10 11:23:39 INFO  AbstractHelper:53 - main switch to 3G mode
[31merror[39m: Unhandled error: Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26) context: [POST /wd/hub/session/f4ec345f-7e94-4465-b728-9d55b3abba47/appium/app/launch {}]
[31merror[39m: Unhandled error: Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26) context: [POST /wd/hub/session/f4ec345f-7e94-4465-b728-9d55b3abba47/appium/app/launch {}]
[31merror[39m: Unhandled error: Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26) context: [POST /wd/hub/session/f4ec345f-7e94-4465-b728-9d55b3abba47/appium/app/launch {}]
```


[appium4723.log.txt](https://github.com/appium/appium/files/166598/appium4723.log.txt)
