### ISSUE TITLE
iOS cannot start Appium session

### ISSUE THREAD

**Issue by nabeel-ibrahim** [appium/appium#5260]
I am unable to start an appium session. below is the log:
[36minfo[39m: Welcome to Appium v1.4.3 (REV a357c7fa73222315dd85c3d2dd8334767cca1b0d)
[36minfo[39m: Appium REST http interface listener started on 127.0.0.1:4723
[36minfo[39m: Console LogLevel: info
[36minfo[39m: File LogLevel: info
Jun 15, 2015 11:40:43 AM com.score.app.GeneratorClasses.SetUp iOSSetUp
INFO: LAUNCHING APP!!!
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"app":"/Users/nibrahim/Documents/workspace/automation/iOS/myApp.ipa","showIOSLog":true,"nativeInstrumentsLib":false,"platformVersion":"8.3","bundleId":"com.thescore.ios.develop","waitForAppScript":true,"udid":"f219c51e1bdb972026c18ace54f4200a2c57ad4c\nf219c51e1bdb972026c18ace54f4200a2c57ad4c","platformName":"iOS","deviceName":"iPhone","autoAcceptAlerts":true}}[39m
[36minfo[39m: Client User-Agent string: Apache-HttpClient/4.4.1 (Java/1.8.0_45)
[36minfo[39m: Will try to parse the plist file as XML
[33mwarn[39m: Could not parse app Localizable.strings assuming it doesn't exist
[31merror[39m: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c ideviceinstaller -u f219c51e1bdb972026c18ace54f4200a2c57ad4c
f219c51e1bdb972026c18ace54f4200a2c57ad4c -l 
/bin/sh: line 1: f219c51e1bdb972026c18ace54f4200a2c57ad4c: command not found

I installed ideviceinstaller using brew install --HEAD ideviceinstaller. To fix this issue i usually restart my laptop but its not convenient to do this every time

**Comment by sebv** [comment]
ideviceinstaller is not installed correctly on your system.

You don't need to restart your laptop everytime you install something with brew.

**Comment by sebv** [comment]
See: https://github.com/appium/appium/issues/5258

**Comment by nabeel-ibrahim** [comment]
I tried reinstalling ideviceinstaller using the last comment on  #5258 but still having the same issue

**Comment by sebv** [comment]
Again , you need to fix brew and ideviceinstaller on your system.  ideviceinstaller is on github you may get better support for this specific issue there.

**Comment by Anishohri** [comment]
Can you also try with 1.4.0 or 1.3.7 appium.

**Comment by nabeel-ibrahim** [comment]
@sebv it is a problem with ideviceinstalle., i get the wrong UDID returned I will open a issue on their page. https://github.com/libimobiledevice/ideviceinstaller/issues/29

**Comment by sebv** [comment]
See: #5258 same udid issue.

**Comment by sebv** [comment]
Closing, should be sorted, may be reopened if needed.
