### ISSUE TITLE
Appium with ios on actual device

### ISSUE THREAD

**Issue by LokeshGangaiah** [appium/appium#5261]
Hello Friends,

Below error is seen, for the following below code:
What is the solution to resolve this Guys, looking forward to hear from you

=====
org.openqa.selenium.SessionNotCreatedException: A new session could not
be created. (Original error: Please provide the 'app' or 'browserName'
capability or start appium with the --app or --browser-name argument.
Alternatively, you may provide the 'bundleId' and 'udid' capabilities
for an app under test on a real device.) (WARNING: The server did not
provide any stacktrace information)
Command duration or timeout: 195 milliseconds

===
Code:
======
import io.appium.java_client.ios.IOSDriver;
import org.openqa.selenium.By;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
import io.appium.java_client.ios.*;

public class FB_ios {

public static IOSDriver driver;
//public static AndroidDriver driver;

public class FB_ios { public static IOSDriver driver;
//public static AndroidDriver driver; @BeforeClass
public void setUP() throws MalformedURLException { DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(CapabilityType.BROWSER_NAME, "firefox");
capabilities.setCapability("device", "iPhone 5");
capabilities.setCapability("u_did", "9e8bf6eeb08db0fff2113c39cc828b13e2d57da5");
capabilities.setCapability("bundle_id", "com.telstra.labs.treats");
capabilities.setCapability("deviceName", "VIV-064");
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("platformVersion", "8.0"); capabilities.setCapability("appPackage", "com.telstra.labs.treats");
capabilities.setCapability("appActivity", "au.com.vivant.telstratreats.activity.WelcomeActivity"); driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
}

@Test
public void Web_App_Test() throws InterruptedException

{
    System.out.println("Test started");

    System.out.println(" Start to identify a test");

    By.id("com.facebook.katana:id/login_username").findElement(driver).click();
    Thread.sleep(1000L);

    System.out.println("Test Completed");
}

@AfterClass
public void tearDown()
{
    driver.quit();
}

}

**Comment by sebv** [comment]
Please provide server log.

**Comment by LokeshGangaiah** [comment]
Sebv,
Made few changes to the capabilities in code, which resolved old issue and gave me new error.
Please see the server log and error below:



Server log:
==============
info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: <-- GET /wd/hub/status 200 7.509 ms - 104 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: <-- GET /wd/hub/status 200 2.342 ms - 104 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"8.0","deviceName":"VIV-064","platformName":"iOS","browserName":"iOS","bundleId":"com.telstra.labs.treats","udid":"9e8bf6eeb08db0fff2113c39cc828b13e2d57da5"}}

info: Client User-Agent string: Apache-HttpClient/4.4.1 (Java/1.7.0_79)

info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] App is an iOS bundle, will attempt to run as pre-existing
info: [debug] Creating new appium session ba9d75aa-5b23-4714-b42e-708ef9eebaf2
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Localizable.strings is not currently supported when using real devices.
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/lgangaia/Library/Application Support/appium/bootstrap

info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/lgangaia/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js
info: [debug] Reusing dynamic bootstrap: /Users/lgangaia/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js
info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog
warn: Could not capture device log using libimobiledevice idevicesyslog. Libimobiledevice probably isn't installed
info: [debug] Attempting iOS device log capture via deviceconsole

warn: Could not capture logs from device. Continuing without capturing logs.

error: Log capture did not start in a reasonable amount of time

info: [debug] Creating iDevice object with udid 9e8bf6eeb08db0fff2113c39cc828b13e2d57da5
info: [debug] Couldn't find ideviceinstaller, trying built-in at /Applications/Appium.app/Contents/Resources/node_modules/appium/build/libimobiledevice-macosx/ideviceinstaller
info: [debug] Cleaning up appium session

error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
error: Failed to start an Appium session, err was: Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system

info: [debug] Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
    at [object Object].IOS.getIDeviceObj (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:909:13)
    at [object Object].IOS.installToRealDevice (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:856:32)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:607:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:246:17
    at iterate (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:146:13)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:157:25
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:248:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:612:34
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1527:14)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js:890:21
    at [object Object]._onTimeout (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-log.js:166:7)
    at Timer.listOnTimeout (timers.js:110:15)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not initialize ideviceinstaller; make sure it is installed and works on your system)","origValue":"Could not initialize ideviceinstaller; make sure it is installed and works on your system"},"sessionId":null}
info: <-- POST /wd/hub/session 500 10045.773 ms - 300 
==
Error
===

org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Could not initialize ideviceinstaller; make sure it is installed and works on your system) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.23 seconds
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
====
Code:
=====
       DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("browserName", "iOS");
        capabilities.setCapability("udid", "9e8bf6eeb08db0fff2113c39cc828b13e2d57da5");
        capabilities.setCapability("bundleId", "com.telstra.labs.treats");
        capabilities.setCapability("deviceName", "VIV-064");//deviceName is the device returned by instruments with instruments -s devices
        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("platformVersion", "8.0");
        //capabilities.setCapability("appPackage", "com.telstra.labs.treats");
        //capabilities.setCapability("appActivity", "au.com.vivant.telstratreats.activity.WelcomeActivity");
      //  capabilities.setCapability("bundleId", "com.telstra.labs.treats");
        driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);




    }

**Comment by sebv** [comment]
See  #5258

**Comment by LokeshGangaiah** [comment]
yes thanks....It WORKED :)
So install brew on your mac , if not installed already
Once that is installed 
use the below command
brew install ideviceinstaller

this would solve the problem

thanks Sebv and All
