### ISSUE TITLE
Controls of Appium server GUI is in disable mode

### ISSUE THREAD

**Issue by Mayukh-saha** [appium/appium#5262]
Hello All,
Whenever I am opening the Appium server in the GUI mode (appium.exe ) , the controls ex: Android settings, General settings remains disabled. 
I am not able to change the values like 'No reset'. 
The versions I am using is :
Appium : 1.4.0.0
Node js : 0.12.4
I have also configured android properly to my system. 
I am attaching the relevant screenshots herewith for further reference. 

![server_gui_1jpg](https://cloud.githubusercontent.com/assets/12016179/8178034/535467fa-1428-11e5-90b4-1793bafd959a.jpg)

![server_gui_disabled_buttons](https://cloud.githubusercontent.com/assets/12016179/8178040/653c3394-1428-11e5-972c-f76ff9ebecd0.jpg)

![server_gui_disabled_buttons_2](https://cloud.githubusercontent.com/assets/12016179/8178045/74787002-1428-11e5-9c2d-1f9dd5e19bc1.jpg)

**Comment by sebv** [comment]
The front end project is here: https://github.com/appium/appium-dot-app, open an issue there and link to it.

**Comment by bpanda130** [comment]
What was the solution for this issue as i am facing the same..

**Comment by Mayukh-saha** [comment]
Stop the Appium server and then try.
