### ISSUE TITLE
Black GUI windows with OSX 10.9.5

### ISSUE THREAD

**Issue by sand3r** [appium/appium#5263]
Hello all,

When I open Appium and check any of the options windows, they are all black. I have updated Appium to the latest version (1.4.0). Is this a known issue or does someone know a way how to resolve this?

![screen shot 2015-06-16 at 11 00 07](https://cloud.githubusercontent.com/assets/564494/8179481/2d665118-1417-11e5-8202-5feaa3c49d8e.png)

**Comment by sebv** [comment]
ping @edgy360, We had a white GUI issue earlier today, now we have a black GUI issue.
Please open an issue here: https://github.com/appium/appium-dot-app

**Comment by edgy360** [comment]
Unfortunately, this is an ongoing issue.

Something at the OS level has broken. The only solution right now would be to upgrade to OS X 10.10 if possible, where the API’s are fixed.

https://github.com/appium/appium-dot-app/issues/456 <https://github.com/appium/appium-dot-app/issues/456>

**Comment by sebv** [comment]
Closing, please follow issue above.
