### ISSUE TITLE
Want to launch Safari without browsing to a default webpage

### ISSUE THREAD

**Issue by chris1248** [appium/appium#5267]
Given the ruby script:

```
require 'appium_lib'
desired_caps = {
  caps:       {
    platformName: 'iOS',
    platformVersion: '8.3',
    deviceName:    'iPad Air',
    browserName:   'Safari',
    safariInitialUrl: 'www.github.com'
  }
}

# Start the driver
driver = Appium::Driver.new(desired_caps)
driver = driver.start_driver <-- !!!!!! This loads a web-page at www.github.com !!!!!
driver.get("http://www.google.com")
```

When I call driver.start_driver, it starts up Safari on my IOS simulator, and then browses to a url. Without the 'safariInitialUrl' cap, it browses to '127.0.0.1/welcome'. 

**But I don't want safari to browse _anywhere_ at all (when it starts)**. It takes way too long when running hundreds of rspec tests. 

I found in the source code:
/appium/lib/devices/ios/ios.js (line 1596) the function 
`IOS.prototype.navToInitialWebview = function (cb)`
that calls 
`this.typeAndNavToUrl(cb);` 
which is responsible for the original navigation to the url when safari starts up. 

How can I modify it to just launch Safari and not browse to a page. I tried modifying the code in `typeAndNavToUrl` and indeed the loading of the URL was short circuited (i.e. the call to driver.get just hung). Hence my ruby script ground to a halt. I'm a newbie at javascript, so a lot of this is completely foreign to me.

**Comment by jlipps** [comment]
the problem is that if it doesn't navigate somewhere, there's no active webview to automate, and thus the whole point of a safari session is moot. going to some url is the only way we've found to get a webview open to the remote debugger so you can start sending commands.

the most efficient workaround for you will probably be to set safariInitialUrl on a per-session basis to what the first url you visit will be, that way you're not wasting any time.

**Comment by chris1248** [comment]
So would that explain why when I short-circuited the URL navigation, the rest of the script did nothing? Because I aborted the creation of the active webview?

**Comment by chris1248** [comment]
so is this a limitation in IOS then, or some other framework?

**Comment by moizjv** [comment]
@chris1248 yes it is a limitation currently.

**Comment by sebv** [comment]
@chris1248, why you don't set  safariInitialUrl="http://www.google.com" in your first example? I think you can do what you want on client side, just facade your driver and make it hot start on the first test, you can also use the logic to keep the driver hot between tests.

**Comment by moizjv** [comment]
@chris1248 does that help. Looks like a limitation we would need some url
