### ISSUE TITLE
Appium crashes for Airplane mode parallel testing

### ISSUE THREAD

**Issue by gauravgandhi15** [appium/appium#5272]
I have been trying to run some airplane mode test cases which includes turing it ON/OFF. It works fine on one device, but when i try to run it on multiple device then Appium crashes for some reason and unable to find the second connected device. Also, i am using NetworkConnectionSetting class for this functionality. Look at the logs:

{"compressLayout":false}]
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 shell "am broadcast -a android.intent.action.AIRPLANE_MODE --ez state false"
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 kill-server
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 wait-for-device
info: [debug] UiAutomator exited
info: error sending command, reconnecting device and retrying: wait-for-device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: [debug] 0 device(s) connected
info: [debug] Could not find devices, restarting adb server...
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 kill-server
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: [debug] Retrying restartAdb
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 kill-server
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: error sending command, reconnecting device and retrying: devices
info: [debug] Could not find devices, restarting adb server...
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 kill-server
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: error sending command, reconnecting device and retrying: devices
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: [debug] 1 device(s) connected
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: [debug] 1 device(s) connected
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 wait-for-device
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Forwarding system:5422 to device:4724
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 forward tcp:5422 tcp:4724
info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 shell "ps 'uiautomator'"
info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg packagename -e disableAndroidWatchers false
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 shell "am start -n io.appium.settings/.Settings -e wifi on -e data on"
info: [debug] 1 device(s) connected
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: [debug] 1 device(s) connected
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 wait-for-device
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 kill-server
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 wait-for-device
info: [debug] UiAutomator exited
info: error sending command, reconnecting device and retrying: wait-for-device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: [debug] Could not find devices, restarting adb server...
info: [debug] Retrying restartAdb
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 kill-server
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: error sending command, reconnecting device and retrying: devices
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 kill-server
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: [debug] 1 device(s) connected
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: [debug] 1 device(s) connected
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 wait-for-device
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Logcat terminated with code 0, signal null
info: [debug] 1 device(s) connected
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 wait-for-device
info: error sending command, reconnecting device and retrying: wait-for-device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 devices
info: [debug] 1 device(s) connected
info: [debug] Didn't get a new command in 60 secs, shutting down...
info: Shutting down appium session
info: [debug] Pressing the HOME button
info: [debug] executing cmd: /Users/kumarg/Downloads/android-sdk-macosx/platform-tools/adb -s T065000751 shell "input keyevent 3"
info: [debug] Stopping logcat capture
info: [debug] Logcat already stopped
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: <-- POST /wd/hub/session/5b9e0249-1ab5-4359-96dd-98fb547f04f7/network_connection - - ms - -
info: --> POST /wd/hub/session/5b9e0249-1ab5-4359-96dd-98fb547f04f7/network_connection {"name":"network_connection","parameters":{"type":6}}
info: <-- POST /wd/hub/session/5b9e0249-1ab5-4359-96dd-98fb547f04f7/network_connection 404 0.889 ms - 40
info: [debug] Didn't get a new command in 60 secs, shutting down...
info: [debug] Trying to stop appium but there's no session, doing nothing
info: [debug] We shut down because no new commands came in

**Comment by moizjv** [comment]
@gauravgandhi15 how are you running multiple devices? Currently one appium server can handle on only one device

**Comment by gauravgandhi15** [comment]
I have one server for each device.

**Comment by moizjv** [comment]
@gauravgandhi15 that is strange, so tests when they are ran in isolation works fine?

**Comment by gauravgandhi15** [comment]
Yes, they works fine. The issue i am having with only parallel test for 2 devices. Even it works fine on one device.

**Comment by moizjv** [comment]
@gauravgandhi15 so there are multiple appium servers on same machine connected to multiple devices? I am unable to understand setup

**Comment by gauravgandhi15** [comment]
yes right

**Comment by sebv** [comment]
@gauravgandhi15, looks like your 2 appium server are competing for ADB, in particular killing the server..

I don't think we support this use case well in the current version (but maybe @jlipps knows a way), I think it is better to do this kind of thing within run 2 separate VMs. 

We have plan to support this type of setup in the future (We are currently rewiting the appium server).

**Comment by gauravgandhi15** [comment]
@sebv But why it is not crashing for other tests? Why is it crashing only for airplane. When it works on one device, why does appium disconnect the other device only for airplane mode test case? I am sure when we are running two servers, they both run ADB to look for the devices, which runs fine for other tests. This is little confusing me.

**Comment by sebv** [comment]
`runs fine for other tests.` 
I think as long as you don't call killservers it runs fine. There are probably other calls which are problematic, but we don't know about them since there are no tests for this use case.

To avoid confusion: As far as my knowledge goes, your setup is not yet supported.

**Comment by gauravgandhi15** [comment]
@sebv ok so can you put this test in your backlog for next appium release?

**Comment by sebv** [comment]
Yes we'll keep it in mind, thx.

**Comment by priyankshah217** [comment]
@sebv even i also facing the same issue. for one device it successfully switched to airplane mode, while in other device it failed. it seems adb disconnected in the middle.

**Comment by moizjv** [comment]
@priyankshah217 do you have logs for it?

**Comment by priyankshah217** [comment]
Below is the sample code, I was trying to turn off wifi.
```                
  NetworkConnectionSetting networkConnectionSetting = null;
		networkConnectionSetting = driver.getNetworkConnection();
        	networkConnectionSetting.setWifi(false);
		driver.setNetworkConnection(networkConnectionSetting);
```
In one deive it successfully turned of WIFI while for second device it lost adb connections.

Please find attached logs on below link,
https://gist.github.com/priyankshah217/cf76d32fcd38ca62bf25

Thanks,
Priyank Shah

**Comment by moshimoshibye** [comment]
@moizjv  I also saw this when ran tests on saucelabs. It only happened when I change network status. 

And it cause me timeout on saucelabs ; (

Here is the log:
62102015-06-29 09:11:09:545 - info: --> GET /wd/hub/session/c0dacf61-0ab4-4d6c-811a-52ba6efdf7e6/network_connection {}
62112015-06-29 09:11:09:546 - info: Getting network connection
62122015-06-29 09:11:09:546 - info: [debug] executing cmd: /home/chef/android-sdk-linux/platform-tools/adb -s emulator-5554 shell "settings get global airplane_mode_on"
62132015-06-29 09:11:10:337 - info: [debug] executing cmd: /home/chef/android-sdk-linux/platform-tools/adb -s emulator-5554 shell "settings get global wifi_on"
62142015-06-29 09:11:10:946 - info: [debug] executing cmd: /home/chef/android-sdk-linux/platform-tools/adb -s emulator-5554 shell "settings get global mobile_data"
62152015-06-29 09:11:11:596 - info: [debug] Responding to client with success: {"status":0,"value":4,"sessionId":"c0dacf61-0ab4-4d6c-811a-52ba6efdf7e6"}
62162015-06-29 09:11:11:597 - info: <-- GET /wd/hub/session/c0dacf61-0ab4-4d6c-811a-52ba6efdf7e6/network_connection 200 2051.376 ms - 73 {"status":0,"value":4,"sessionId":"c0dacf61-0ab4-4d6c-811a-52ba6efdf7e6"}
62172015-06-29 09:11:11:632 - info: --> POST /wd/hub/session/c0dacf61-0ab4-4d6c-811a-52ba6efdf7e6/network_connection {"name":"network_connection","parameters":{"type":1}}
62182015-06-29 09:11:11:633 - info: Setting network connection
62192015-06-29 09:11:11:634 - info: [debug] executing cmd: /home/chef/android-sdk-linux/platform-tools/adb -s emulator-5554 shell "settings put global airplane_mode_on 1"
62202015-06-29 09:11:12:287 - info: [debug] Stopping logcat capture
62212015-06-29 09:11:12:290 - info: [debug] Logcat terminated with code null, signal SIGTERM
62222015-06-29 09:11:12:290 - info: [debug] executing cmd: /home/chef/android-sdk-linux/platform-tools/adb -s emulator-5554 kill-server
62232015-06-29 09:11:12:298 - info: [debug] UiAutomator exited
62242015-06-29 09:11:12:299 - info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
62252015-06-29 09:11:12:299 - info: [debug] executing cmd: /home/chef/android-sdk-linux/platform-tools/adb -s emulator-5554 wait-for-device
62262015-06-29 09:11:15:311 - info: [debug] executing cmd: /home/chef/android-sdk-linux/platform-tools/adb -s emulator-5554 shell "echo 'ready'"
62272015-06-29 09:11:15:362 - info: [debug] Starting logcat capture
62282015-06-29 09:11:15:444 - info: [debug] Forwarding system:4724 to device:4724
62292015-06-29 09:11:15:445 - info: [debug] executing cmd: /home/chef/android-sdk-linux/platform-tools/adb -s emulator-5554 forward tcp:4724 tcp:4724
62302015-06-29 09:11:15:453 - info: Starting App
62312015-06-29 09:11:15:453 - info: [debug] Attempting to kill all 'uiautomator' processes
62322015-06-29 09:11:15:453 - info: [debug] Getting all processes with 'uiautomator'
62332015-06-29 09:11:15:454 - info: [debug] executing cmd: /home/chef/android-sdk-linux/platform-tools/adb -s emulator-5554 shell "ps 'uiautomator'"
62342015-06-29 09:11:15:548 - info: [debug] No matching processes found
62352015-06-29 09:11:15:548 - info: [debug] Running bootstrap
62362015-06-29 09:11:15:549 - info: [debug] spawning: /home/chef/android-sdk-linux/platform-tools/adb -s emulator-5554 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap
62372015-06-29 09:11:15:648 - info: [debug] [UIAUTOMATOR STDOUT] WARNING: linker:
62382015-06-29 09:11:15:650 - info: [debug] [UIAUTOMATOR STDOUT] libdvm.so has text relocations. This is wasting memory and is a security risk. Please fix.
62392015-06-29 09:11:15:791 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
62402015-06-29 09:11:15:800 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
62412015-06-29 09:11:15:800 - info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
62422015-06-29 09:11:15:801 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
62432015-06-29 09:11:15:801 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
62442015-06-29 09:11:15:801 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
62452015-06-29 09:11:15:801 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
62462015-06-29 09:11:15:801 - info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
62472015-06-29 09:11:15:810 - info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
62482015-06-29 09:11:15:811 - info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
62492015-06-29 09:11:15:811 - info: [debug] [BOOTSTRAP] [debug] Loading json...
62502015-06-29 09:11:15:811 - info: [debug] [BOOTSTRAP] [debug] json loading complete.
62512015-06-29 09:11:15:811 - info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
62522015-06-29 09:11:15:811 - info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
62532015-06-29 09:11:15:824 - info: [debug] [BOOTSTRAP] [debug] Client connected
62542015-06-29 09:11:15:830 - info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
62552015-06-29 09:11:15:830 - info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
62562015-06-29 09:11:15:830 - info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
62572015-06-29 09:11:15:831 - info: [debug] executing cmd: /home/chef/android-sdk-linux/platform-tools/adb -s emulator-5554 shell "am broadcast -a android.intent.action.AIRPLANE_MODE --ez state true"
62582015-06-29 09:11:15:838 - info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
62592015-06-29 09:16:11:635 - info: <-- POST /wd/hub/session/c0dacf61-0ab4-4d6c-811a-52ba6efdf7e6/network_connection - - ms - -
62602015-06-29 09:16:11:636 - info: [debug] Didn't get a new command in 300 secs, shutting down...
62612015-06-29 09:16:11:637 - info: Shutting down appium session

**Comment by moizjv** [comment]
@moshimoshibye does this happen always or happens randomly?

**Comment by SrinivasanTarget** [comment]
Network connections been redesigned on both client and server now.Please raise a new issue incase if you hit the same on latest server and java client (will be released soon) along with logs in form of gist.We can take it up from there incase of any issues.Closing this now.

**Comment by SrinivasanTarget** [comment]
@triager please close
