### ISSUE TITLE
Can Appium support nativer browser for automation using wd.js

### ISSUE THREAD

**Issue by zhangmeng712** [appium/appium#5275]
Hi,
 I'm using appium for webapp testing,  in ios I set  appium  "node . --safari"  (appium version 1.4.5) to test my web page.
 I'm wondering is there any settings  can I set for appium to open native browser for web page testing in android? 
Any solutions?

**Comment by moizjv** [comment]
hi @zhangmeng712 can you please use [forum](http://discuss.appium.io) for asking questions. This space is for raising issues. For using wd.js you need to pass in capabilities as part of your script as 
`{"platformName":"Android", "platformVersion":"4.4", "browserName": "browser",
          "name" : "TestName",
          "deviceName":"Android"}`
