### ISSUE TITLE
Running a test 100 times: Failed to find elements.

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#5276]
have test in loop that opens one by one some application screen (iOS Simulator 8.1-8.3).
After X loop (about 20min running) Appium failed to find element and sees pageSource as:

<?xml version="1.0" encoding="UTF-8"?>

```
<AppiumAUT>
    <UIAApplication name="" label="" value="" dom="" enabled="false" valid="false" visible="false" hint="" path="/0" x="0.00003357034752143033" y="768.0000447604625" width="0" height="0">
    </UIAApplication>
</AppiumAUT>
```

we start appium as: [appium, --log-level, error, --port, 4724, --session-override]

any help or workaround?

Appium logs (with debug level):

[36minfo[39m: [debug] Sending command to instruments: au.getElementsByAccessibilityId('categoryCell')
[36minfo[39m: [37m<-- POST /wd/hub/session/0b11fee0-1f67-47a1-9674-21e2b5a227b4/elements [39m[32m200[39m[90m 5773.931 ms - 74[39m [90m{"status":0,"value":[],"sessionId":"0b11fee0-1f67-47a1-9674-21e2b5a227b4"}[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/0b11fee0-1f67-47a1-9674-21e2b5a227b4/timeouts/implicit_wait[39m [90m{"ms":20000}[39m
[36minfo[39m: [debug] Set iOS implicit wait to 20000ms
[36minfo[39m: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"0b11fee0-1f67-47a1-9674-21e2b5a227b4"}
[36minfo[39m: [37m<-- POST /wd/hub/session/0b11fee0-1f67-47a1-9674-21e2b5a227b4/timeouts/implicit_wait [39m[32m200[39m[90m 0.930 ms - 76[39m [90m{"status":0,"value":null,"sessionId":"0b11fee0-1f67-47a1-9674-21e2b5a227b4"}[39m
   failed tapUserProfileButton
[36minfo[39m: [37m-->[39m [37mGET[39m [37m/wd/hub/session/0b11fee0-1f67-47a1-9674-21e2b5a227b4/source[39m [90m{}[39m
[36minfo[39m: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
[36minfo[39m: [debug] [32m[INST] 2015-06-19 07:20:56 +0000 Debug: evaluation finished[39m
[36minfo[39m: [debug] [32m[INST] 2015-06-19 07:20:56 +0000 Debug: responding with:[39m
[36minfo[39m: [debug] [32m[INST] 2015-06-19 07:20:56 +0000 Debug: Running system command #1150: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"origin":{"x":614.0000042837157,"y":98.00000043711373},"size":{"width...[39m
[36minfo[39m: [debug] [32m[INST] 2015-06-19 07:20:56 +0000 Debug: Got new command 1150 from instruments: target.touch([{"touch":[{"x":814.0000055950572,"y":128.00000917939167}],"time":0.2},{"touch":[{"x":814.0000055950572,"y":128.00000917939167}],"time":0.4}])[39m
[36minfo[39m: [debug] [32m[INST] 2015-06-19 07:20:56 +0000 Debug: evaluating target.touch([{"touch":[{"x":814.0000055950572,"y":128.00000917939167}],"time":0.2},{"touch":[{"x":814.0000055950572,"y":128.00000917939167}],"time":0.4}])[39m

**Comment by amedvedjev** [comment]
more info when appium goes into this state:
    - simple tap like "driver.tap(1, x, y, 200)" does not work without error in logs
    - driver.getScreenshotAs(OutputType.FILE) working correctly
    - manually tap on iOS Simulator with client not working. need to reboot simulator or kill/restart appium driver (e.g. next test will start successfully)

if we have issue with iOS instruments can we made some feature programmatically restart/refresh iOS_Instruments to continue test execution form same point?

**Comment by moizjv** [comment]
I think some thing weird is happening with instruments. ping @jlipps @imurchie @Jonahss

**Comment by Jonahss** [comment]
Can you shorten your test suite? this is a valid bug, but I don't think we are currently optimizing for this use case.

**Comment by amedvedjev** [comment]
it is already shorten. one loop about 50sec. it does not reproduce 100% after 10 loops. it is starting to reproduce after about 12-14loops and never reached more then 19 loops.

**Comment by Jonahss** [comment]
Oh cool. Can you provide us with the exact code you use for that test? Then we could examine it while running and try to fix the memory leak.

**Comment by amedvedjev** [comment]
here is below some code (not all but only test itself. other code is quite large. based on PageFactory and TesnNG.

public class test_leaks extends BaseTest {

    private InitialScreenPage initialScreenPage;
    private MainScreenPage mainScreenPage;
    private HotelsListPage hotelsListPage;
    private NearMePage nearMePage;
    private CategoryGridViewPage categoryGridViewPage;
    private SubcategoryListViewPage subcategoryListViewPage;
    private UserProfilePage userProfilePage;
    private SearchPage searchPage;
    private HotelDetailsPage hotelDetailsPage;

    private org.openqa.selenium.Point userProfilePoint = null;

    @Test(groups = {"group_leaks"}, dataProvider="osVersion_deviceName")
    public void test_loop(String osVersion, String deviceName) throws Exception {

        //do loop
        int count = 1;
        System.out.println("---------- do test ----------");
        initialScreenPage = new InitialScreenPage(driver);
        assertTrue(initialScreenPage.isInitialScreenLoadedFast());
        System.err.println(getLeaks_iOS());

        mainScreenPage = initialScreenPage.tapSkipButton();

        do {
            System.out.println("  loop: "+count);

            System.out.println("  tap User Profile button");
            //mainScreenPage.tapUserProfileButton(); //here is PROBLEM happening after 10-12 loops


            //below is workaround tried to tap on previous stored location of userProfileButton
            for(int i=0; i<5; i++)
                try {
                    if(userProfilePoint==null) {
                        userProfilePoint = mainScreenPage.getUserProfileButtonCoordinates();
                    }
                    mainScreenPage.tapUserProfileButton();
                    break;
                } catch (Exception e) {
                    System.err.println("   failed tapUserProfileButton using previous coordinates x: " +
                            userProfilePoint.getX() +", y: " + userProfilePoint.getY());
                    mainScreenPage.tapElement(userProfilePoint.getX(), userProfilePoint.getY());
                    sleep(10);
                    mainScreenPage.tapElement(userProfilePoint.getX(), userProfilePoint.getY());
                    break;
                    //System.out.println(mainScreenPage.getPageSource());
                }
            userProfilePage = new UserProfilePage(driver);

            System.out.println("  return to Main Menu using Home button");
            userProfilePage.tapHomeButton();

            //check search button
            System.out.println("  tap Search button");
            mainScreenPage.tapSearchButton();
            searchPage = new SearchPage(driver,false);
            assertTrue(searchPage.isSearchPageLoadedFast());

            System.out.println("  return to Main Menu using Home button");
            searchPage.tapHomeButton();

            //check Primary Categories buttons: Regions
            System.out.println("  tap Regions button");
            mainScreenPage.tapMainMenuButton(0);
            categoryGridViewPage = new CategoryGridViewPage(driver,false);
            assertTrue(categoryGridViewPage.isCategoryGridViewLoadedFast());

            categoryGridViewPage.tapCategoryCell(0);
            subcategoryListViewPage = new SubcategoryListViewPage(driver,false);
            assertTrue(subcategoryListViewPage.isSubcategoryPageLoadedFast());
            subcategoryListViewPage.tapSubcategoryCell(0);
            hotelsListPage = new HotelsListPage(driver,false);
            assertTrue(hotelsListPage.isHotelsListPageLoaded());
            hotelsListPage.tapHotelCell(0);
            hotelDetailsPage = new HotelDetailsPage(driver,false);
            assertTrue(hotelDetailsPage.isHotelDetailsPageLoadedFast());
            hotelDetailsPage.tapThumbnailView(deviceName);
            assertTrue(hotelDetailsPage.isGalleryViewPageLoaded());

            System.out.println("  return to Main Menu using Home button");
            hotelDetailsPage.tapHomeButton();
            //assertTrue(mainScreenPage.isMainScreenLoadedFast());
            //System.err.println(getLeaks_iOS());

            //check Primary Categories buttons: Experience
            System.out.println("  tap Experience button");
            mainScreenPage.tapMainMenuButton(1);
            categoryGridViewPage = new CategoryGridViewPage(driver,false);
            assertTrue(categoryGridViewPage.isCategoryGridViewLoadedFast());

            System.out.println("  return to Main Menu using Home button");
            categoryGridViewPage.tapHomeButton();
            if(!mainScreenPage.isMainScreenLoadedFast()) {
                categoryGridViewPage.tapHomeButton();
                assertTrue(mainScreenPage.isMainScreenLoadedFast());
            }
            //System.err.println(getLeaks_iOS());

            //check Primary Categories buttons: Brands
            System.out.println("  tap Brands button");
            mainScreenPage.tapMainMenuButton(2);
            categoryGridViewPage = new CategoryGridViewPage(driver,false);
            assertTrue(categoryGridViewPage.isCategoryGridViewLoadedFast());

            System.out.println("  return to Main Menu using Home button");
            categoryGridViewPage.tapHomeButton();
            if(!mainScreenPage.isMainScreenLoadedFast()) {
                categoryGridViewPage.tapHomeButton();
                assertTrue(mainScreenPage.isMainScreenLoadedFast());
            }
            //System.err.println(getLeaks_iOS());

            //check near me button
            Location tallinn_airport_loc = new Location(59.416343, 24.802423, 0);
            driver.setLocation(tallinn_airport_loc);
            System.out.println("  tap Near Me button");
            mainScreenPage.tapMainMenuButton(3);
            nearMePage = new NearMePage(driver,false,false);

            System.out.println("  return to Main Menu using Home button");
            mainScreenPage.tapUserProfileButton();
            nearMePage.tapHomeButton();

            //check show all button
            System.out.println("  tap Show All button");
            mainScreenPage.tapMainMenuButton(4);
            hotelsListPage = new HotelsListPage(driver,false);
            assertTrue(hotelsListPage.isHotelsListPageLoadedFast());


            System.out.println("  return to Main Menu using Home button");
            hotelsListPage.tapHomeButton();
            if(!mainScreenPage.isMainScreenLoadedFast()) {
                hotelsListPage.tapHomeButton();
                assertTrue(mainScreenPage.isMainScreenLoadedFast());
            }
            System.err.println(getLeaks_iOS());
            count++;
        } while (count<100);
    }
}

**Comment by Jonahss** [comment]
Hm ok. So running the test 100 times, eventually it fails like you mention.
Thanks, this should be enough to reproduce it. We should write a test that just runs a simple test like 1000 times.

**Comment by amedvedjev** [comment]
i never was able to run more then 19 times. but failing can start from 10-12 loop. 10 loops run 100% successfully.

**Comment by Jonahss** [comment]
Ok. That will help us fix it. The goal should be 100 or 1000 :)

**Comment by amedvedjev** [comment]
more news with latest code.
Appium: 1.3.7, java-client: 3.1, iOS Simulator: 8.4

was able to reach 62 loop!. total time test execution now reaching up to 51min.

**Comment by amedvedjev** [comment]
after making tests more stubborn was able to complete 100 loops!
  Execution time: 5278sec = 88min
just nice stable appium work!

**Comment by Jonahss** [comment]
Ooh awesome!

What did you do to make your tests more stubborn and stable?

**Comment by amedvedjev** [comment]
well after about 60 loops app became not very reliable on tap. so i just added in many places like:

searchPage = mainScreenPage.tapSearchButton();
if(!searchPage.isSearchPageLoadedFast()) mainScreenPage.tapSearchButton(); //for sure
assertTrue(searchPage.isSearchPageLoadedFast());

**Comment by Jonahss** [comment]
Hmm. I see. So after 60 runs, memory leaks in Android and the App itself might start to manifest, and reliability goes downhill :(

**Comment by amedvedjev** [comment]
well with real device same test meets problem with instruments crashing after X loop where X never reached more then 12 loops.

appium driver starting slightly different (cause it is needed to get ios logs. and this is possible ONLY when set appium log to INFO or below).

appium driver starting as:
 [appium, --log-level, debug, --show-ios-log, --show-sim-log, --port, 4724, --session-override]


[36minfo[39m: [37m<-- POST /wd/hub/session/d3ffc7bb-0df4-4309-967f-73c2967da74b/touch/perform [39m[32m200[39m[90m 1246.128 ms - 74[39m [90m{"status":0,"value":"","sessionId":"d3ffc7bb-0df4-4309-967f-73c2967da74b"}[39m
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session/d3ffc7bb-0df4-4309-967f-73c2967da74b/touch/perform[39m [90m{"actions":[{"action":"press","options":{"x":383,"y":326}},{"action":"wait","options":{"ms":200}},{"action":"release","options":{}}]}[39m
[36minfo[39m: [debug] Pushing command to appium work queue: "target.touch([{\"touch\":[{\"x\":383,\"y\":326}],\"time\":0.2},{\"touch\":[{\"x\":383,\"y\":326}],\"time\":0.4}])"
[36minfo[39m: [debug] Sending command to instruments: target.touch([{"touch":[{"x":383,"y":326}],"time":0.2},{"touch":[{"x":383,"y":326}],"time":0.4}])
[36minfo[39m: [debug] [32m[INST] 2015-07-21 14:57:28 +0000 Debug: responding with:[39m
[36minfo[39m: [debug] [32m[INST] 2015-07-21 14:57:28 +0000 Debug: Running system command #833: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...[39m
[36minfo[39m: [debug] [32m[INST] 2015-07-21 14:57:28 +0000 Fail: The target application appears to have died[39m
[36minfo[39m: [IOS_SYSLOG_ROW ] Jul 21 17:57:29 Maxs-iPad SpringBoard[43] <Warning>: Received memory warning.
[36minfo[39m: [IOS_SYSLOG_ROW ] Jul 21 17:57:29 Maxs-iPad UserEventAgent[17] <Notice>: jetsam: kernel termination snapshot being created
[36minfo[39m: [IOS_SYSLOG_ROW ] Jul 21 17:57:29 Maxs-iPad discoveryd[66] <Notice>: Basic DeviceInformation Memory Pressure Warning sent: pressure
[36minfo[39m: [IOS_SYSLOG_ROW ] Jul 21 17:57:29 Maxs-iPad locationd[63] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
[36minfo[39m: [IOS_SYSLOG_ROW ] Jul 21 17:57:29 Maxs-iPad SpringBoard[43] <Warning>: Application 'UIKitApplication:*****senored***[0x9a3d]' was killed by jetsam.
[36minfo[39m: [debug] [33m[INST STDERR] 2015-07-21 17:57:28.413 instruments[11779:1724778] Attempting to set event horizon when core is not engaged, request ignored[39m
[36minfo[39m: [debug] [33m[INST STDERR] 2015-07-21 17:57:28.414 instruments[11779:1724778] Attempting to set event horizon when core is not engaged, request ignored[39m
[36minfo[39m: [IOS_SYSLOG_ROW ] Jul 21 17:57:29 Maxs-iPad ReportCrash[2957] <Error>: task_set_exception_ports(B07, 400, D03, 0, 0) failed with error (4: (os/kern) invalid argument)
[36minfo[39m: [IOS_SYSLOG_ROW ] Jul 21 17:57:29 Maxs-iPad ReportCrash[2957] <Notice>: Saved report to /Library/Logs/CrashReporter/JetsamEvent-2015-07-21-175729.ips
[36minfo[39m: [IOS_SYSLOG_ROW ] Jul 21 17:57:29 Maxs-iPad UserEventAgent[17] <Notice>: jetsam: kernel termination snapshot being created
[36minfo[39m: [IOS_SYSLOG_ROW ] Jul 21 17:57:30 Maxs-iPad backboardd[56] <Notice>: ALS: SetDisplayFactor: factor=1.0000
[36minfo[39m: [debug] [32m[INST] Instruments Trace Complete (Duration : 1167.213623s; Output : /tmp/appium-instruments/instrumentscli0.trace)[39m
[36minfo[39m: [debug] [90m[INSTSERVER] Instruments exited with code 0[39m
[36minfo[39m: [debug] Cleaning up after instruments exit
[36minfo[39m: [debug] Instruments exited unexpectedly
[36minfo[39m: [debug] Shutting down command proxy and ignoring any errors
[36minfo[39m: [debug] Closing socket server.
[36minfo[39m: [debug] Instruments socket server was closed
[36minfo[39m: [debug] Stopping iOS log capture
[36minfo[39m: [debug] Reset not set, not ending sim or cleaning up app state
[36minfo[39m: [debug] We were in the middle of processing a command when instruments died; responding with a generic error
[36minfo[39m: [debug] Cleaning up appium session
[36minfo[39m: [debug] Responding to client with error: {"status":13,"value":{"message":"Instruments died while responding to command, please check appium logs","name":"UnknownError","origValue":"Instruments died while responding to command, please check appium logs"},"sessionId":null}

**Comment by SrinivasanTarget** [comment]
@triager please close
