### ISSUE TITLE
xpath not evaluating correctly

### ISSUE THREAD

**Issue by braghome** [appium/appium#5281]
mobile only site phone browser
#4340 based on comment on Jan 21, 2015 all automation that runs on web view for mobile sites need to switch to native however can not look up elements using valid xpath

https://gist.github.com/braghome/6d8633c552897c6d6170

verified in chrome emulator
![screen shot 2015-06-19 at 8 44 51 am](https://cloud.githubusercontent.com/assets/1514698/8257270/491acc30-1661-11e5-946a-18a476b682c0.png)

**Comment by moizjv** [comment]
@braghome yes you would need to switch back to webview for interacting with elements in webview.

**Comment by braghome** [comment]
so what about #4340 based on comment on Jan 21, 2015

please clarify this we can have it both ways guys :-1:

**Comment by moizjv** [comment]
@sebv ping

**Comment by braghome** [comment]
so let rem the end goal: need to tap or click I don't care just make stuff work on iOS 8 and above

###### current Appium allergies 

https://gist.github.com/braghome/f978fe7480b1d2b95395
https://gist.github.com/braghome/fd01a03111a6d02c1148
https://gist.github.com/braghome/caca5dadf38a565fadcf
[click on nav bar and nothing happens](https://gist.github.com/braghome/8a2aeb8689005aecd154)

**Comment by sebv** [comment]
You cannot be in the native context and look for DIV, there are 2 contexts with different page sources, the element are not interchangeable. The best is to stay in the webview and use css selectors.

**Comment by braghome** [comment]
@sebv I will again referring to #4340 based on comment on Jan 21, 2015 for the original question

the thing is click does not work all the time [on our rendrJS mobilesite](http://m.trulia.com/) on webview so I was told need to tap in on iOS 8 and above

**Comment by sebv** [comment]
Sounds like a problem with your site, if you cannot click, can you click in pure javascript?

**Comment by braghome** [comment]
the same test works on Appium 1.2.0, :grey_question:

**Comment by moizjv** [comment]
@braghome yeah we removed support to find xpath elements in webview from native context as it was hampering performance

**Comment by moizjv** [comment]
@jlipps can we add it back as an optional flag, and consider it as a feature request?

**Comment by jlipps** [comment]
yeah, that's a good approach. I think we should add it as an optional capability.
