### ISSUE TITLE
hangs when launched from Appium 1.4.0 in iOS7.1.2

### ISSUE THREAD

**Issue by yizhixiaoxiaogou** [appium/appium#5283]
Mac OSX 10.9.5
 Xcode 6.2
iphone 5s 

App hangs when launched from Appium 1.4.0 in iOS7.1.2

Here is the last log

Creating iDevice object with udid 

so I using the follwing command 

 ideviceinstall -l command .it hangs up too .

replug the device to USB cable.  the command  works fine .

after that I restart appium . it works fine

How to ensure appium runs well without repluging the device to USB cable?

**Comment by moizjv** [comment]
There seems to be some flakiness with ideviceinstall and xcode 6.2, may be upgrading to 6.3 will solve this issue

**Comment by yizhixiaoxiaogou** [comment]
It runs very stable lately, thank you for reply.
