### ISSUE TITLE
"presskeyCode" method is not available on java-client

### ISSUE THREAD

**Issue by priyankshah217** [appium/appium#5285]
Hi All,

This could be enhancement or not major blocking task,
I observed a case during i need to press app_switch key(187) during automation. I did this using below command.
 driver.sendKeyEvent(187);

However, at appium server console, it printed warning message.

warn: [DEPRECATED] The keyevent function has been deprecated and will be removed.  Please use the pressKeyCode function instead.
info: [debug] Pushing command to appium work queue: ["pressKeyCode",{"keycode":187,"metastate":null}]

this is very misleading message since we do not have "pressKeyCode" method in java-client(2.2.0) library.

Thanks,
Priyank Shah

**Comment by moizjv** [comment]
ping @Jonahss

**Comment by Jonahss** [comment]
Oh thanks. I'll create an issue on the java-client.

**Comment by moizjv** [comment]
Closing issue here as it is tracked in java-client.
