### ISSUE TITLE
Clicking on an element does nothing with the appium driver 1.4.0

### ISSUE THREAD

**Issue by worker-9** [appium/appium#5286]
I switched from appium 1.2.2 (Cygnus) to 1.4.0 (Draco) yesterday. Clicking on an web element with the TouchAction or the selenium click function does nothing. 

* [appium_testcase.py](https://www.dropbox.com/s/4b9kee8n6jv6n9k/appium_testcase.py?dl=0)
* [appium.log](https://www.dropbox.com/s/ayumic8v5vh12s4/appium.log?dl=0)
* [demonstration of the expected result on chrome](https://www.youtube.com/watch?v=4JLXgr7kc5E)

### Versions
* Appium version: 1.4.0 (Draco)
* OS X version: Yosemite 10.10
* Xcode version: 6.3.2 (6D2105)
* Selenium version: 2.45.0
* Python version: 2.7.6

Any idea what could cause this issue?

Thanks

**Comment by moizjv** [comment]
@worker-9 Logs suggests that it performs click.
```
--> POST /wd/hub/session/5d414669-924e-42b8-82e0-277610267202/element/5000/click {"sessionId":"5d414669-924e-42b8-82e0-277610267202","id":"5000"}
2015-06-20 09:32:31:220 - info: [debug] [REMOTE] Executing 'click' atom in default context
2015-06-20 09:32:31:221 - info: [debug] [REMOTE] Sending javascript command
2015-06-20 09:32:31:222 - info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
2015-06-20 09:32:31:238 - info: [debug] [REMOTE] Receiving data from remote debugger
2015-06-20 09:32:31:238 - info: [debug] [REMOTE] got applicationSentData response
2015-06-20 09:32:31:238 - info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"5d414669-924e-42b8-82e0-277610267202"}```

Are you sure there is some event that is listening to the click. May be it is taking time to attach listeners. Can you see waiting little bit before clicking helps?

**Comment by worker-9** [comment]
Even when I wait before clicking nothing happen ( I used the ipython embed and perform the click multiple time without any response from the app). The same code work under appium 1.2.2, chromedriver, firefoxdriver, safaridriver, iedriver, android genymotion. The click does nothing on appium > 1.3. I postponed updating appium because of this issue but now I have another bug with appium 1.2.2 so I would like to clarify why the click function does nothing. I don't see any indication of a problem looking at the log though... Were you able to run my testcase and notice the problem? Thanks for your time!

**Comment by moizjv** [comment]
@worker-9 let me try, I thought it was a private url.

**Comment by moizjv** [comment]
@worker-9 use `tap` it works. 
![screen shot 2015-06-23 at 2 02 27 pm](https://cloud.githubusercontent.com/assets/1308607/8317188/97def2b8-19b0-11e5-8a3c-5e2790a766ab.png)
![screen shot 2015-06-23 at 2 02 40 pm](https://cloud.githubusercontent.com/assets/1308607/8317189/97e15e40-19b0-11e5-9b28-bf9c94f7b2eb.png)

**Comment by moizjv** [comment]
@worker-9 closing this issue. Please use `tap` instead of `click`. I was able to reproduce your issue and fix it using `tap` instead.

**Comment by worker-9** [comment]
@moizjv 

I did a video to show you my issue: http://www.youtube.com/watch?v=M6YLrK8h-Gg 

Here is the url of the site I used to test the tap function: http://tympanus.net/Tutorials/CircularProgressButton/

Basically even if I used the tap function it doesn't work on my side. What in your experience could cause such an issue? I don't see any kind of error in the appium log...

Thanks for your time again...

**Comment by moizjv** [comment]
@worker-9 sorry i tried it on android. Let me try on iOS

**Comment by moizjv** [comment]
@worker-9 so i got it working `"nativeWebTap":"true"` set this cap

**Comment by moizjv** [comment]
![screen shot 2015-06-24 at 2 43 10 pm](https://cloud.githubusercontent.com/assets/1308607/8342218/631bffba-1a7f-11e5-9220-f927c0075146.png)

**Comment by worker-9** [comment]
@moizjv

It work like a charm! Thanks you very much, I really appreciated your help!
