### ISSUE TITLE
Unable to start appium via programatically on ubuntu

### ISSUE THREAD

**Issue by mayurdharmadhikari** [appium/appium#5288]
Hi Friends,

I am trying to start appium server via java code and used below code

          final String APPIUM_HOME = System.getenv("APPIUM_HOME");
          String NODE=APPIUM_HOME + "/Cellar/node/0.12.4/bin/node";
          String APPIUM_JS=APPIUM_HOME + "/lib/node_modules/appium/bin/appium.js";
          Process process = Runtime.getRuntime().exec(NODE+" "+APPIUM_JS+" --address \"127.0.0.1\"");

	        // Just to confirm its working
         InputStream is = process.getInputStream();
         BufferedReader br = new BufferedReader(new InputStreamReader(is));
        String line = null;
              while ((line = br.readLine()) != null) {
                    System.out.println(line);
	            if(line.contains("Console LogLevel: debug"))
                       { break;}
}

APPIUM HOME value is:/home/username/.linuxbrew

However when I execute below command manually
Runtime.getRuntime().exec(NODE+" "+APPIUM_JS+" --address \"127.0.0.1\"");,server is getting started.But it is not working through code.

Output of Runtime.getRuntime().exec() is "/home/username/.linuxbrew/Cellar/node/0.12.4/bin/node /home/username/.linuxbrew/lib/node_modules/appium/bin/appium.js --address "127.0.0.1""

Please let me know if I am making any mistakes.

Thanks,

**Comment by moizjv** [comment]
@mayurdharmadhikari this does not look as an appium defect. What do you mean by `server is getting started.But it is not working through code.`  Closing the issue. Can you please ask question in the [forum](https://discuss.appium.io/)
