### ISSUE TITLE
npm install appium on win8 fails with linux command "uname"

### ISSUE THREAD

**Issue by mojjj** [appium/appium#5289]
running 

    npm install appium

or

    npm install -g appium@latest

fails.

npm -v  > 2.11.3                                 
node -v > v0.10.38                                       

appium on windows8.1, fails with calling "uname", a linux command (to my knowledge) not available at windows cmd

    > appium-chromedriver@2.1.3 install C:\myproject\node_modules\appium\node_modules\appium-chromedriver
    > node install-npm.js

    'uname' is not recognized as an internal or external command,
    operable program or batch file.

what further information do you need? any assistance is appreciated!

**Comment by moizjv** [comment]
@mojjj what is the complete output? Also you can try using [appium-exe](https://bitbucket.org/appium/appium.app/downloads/)

**Comment by mojjj** [comment]
http://pastebin.com/NSqk8zE2

**Comment by moizjv** [comment]
@mojjj yes looks like an issue, does [appium-exe](https://bitbucket.org/appium/appium.app/downloads/) work fine?

**Comment by mojjj** [comment]
the installer you pointed at, works. thank you for your time!

i would, however, feel more comfortable with the npm-installerd solution for easier management ;)

**Comment by mojjj** [comment]
@amitjaincoer191 @KenanY

**Comment by sebv** [comment]
It's here: https://github.com/appium/appium-support/blob/master/lib/system.js#L19
doesn't work on windows. cc @jlipps .

**Comment by sebv** [comment]
Workaround to detect windows 64.
```
function isOSWin64() {
  return process.arch === 'x64' || process.env.hasOwnProperty('PROCESSOR_ARCHITEW6432');
}
```

**Comment by aniket-21** [comment]
another workaround is if you have git installed, just add git's bin path in your %path% variable. git has utility uname under its bin...it would do the job for you till this issue is fixed

**Comment by Jonahss** [comment]
This is fixed! Appium version 1.4.8 just released.

**Comment by mojjj** [comment]
thank you! works with npm!

**Comment by Jonahss** [comment]
Great! Thanks for bearing with us :)
