### ISSUE TITLE
sendKeys on slider is not working as expected

### ISSUE THREAD

**Issue by sjrjanardhana** [appium/appium#5290]
I am trying to set the slider value to 0.2/0.5/0.9, but it always setting to "0%" i.e starting point of the slider

Please find the appium server logs below.

info: [debug] Socket data received (39 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"36"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"36"},"sessionId":"9a498be6-cec6-46e0-acb1-5e156ae6051e"}
info: <-- POST /wd/hub/session/9a498be6-cec6-46e0-acb1-5e156ae6051e/element 200 692.754 ms - 88 {"status":0,"value":{"ELEMENT":"36"},"sessionId":"9a498be6-cec6-46e0-acb1-5e156ae6051e"}

info: --> POST /wd/hub/session/9a498be6-cec6-46e0-acb1-5e156ae6051e/element/36/value {"id":"36","value":["0.9"]}

info: [debug] Pushing command to appium work queue: "au.getElement('36').setValueByType('0.9')"
info: [debug] Sending command to instruments: au.getElement('36').setValueByType('0.9')

info: [debug] [INST] 2015-06-22 15:26:59 +0000 Debug: Got new command 108 from instruments: au.getElement('36').setValueByType('0.9')

info: [debug] [INST] 2015-06-22 15:26:59 +0000 Debug: evaluating au.getElement('36').setValueByType('0.9')

info: [debug] [INST] 2015-06-22 15:26:59 +0000 Debug: target.frontMostApp().elements()[0].elements()[1].elements()[29].dragToValue("0.9")

info: [debug] [INST] 2015-06-22 15:27:01 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-06-22 15:27:01 +0000 Debug: responding with:

info: [debug] [INST] 2015-06-22 15:27:01 +0000 Debug: Running system command #109: /Applications/Appium_1.3.7.app/Contents/Resources/node/bin/node /Applications/Appium_1.3.7.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...

info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"9a498be6-cec6-46e0-acb1-5e156ae6051e"}
info: <-- POST /wd/hub/session/9a498be6-cec6-46e0-acb1-5e156ae6051e/element/36/value 200 2441.925 ms - 74 {"status":0,"value":"","sessionId":"9a498be6-cec6-46e0-acb1-5e156ae6051e"}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"9a498be6-cec6-46e0-acb1-5e156ae6051e"}
info: <-- GET /wd/hub/status 200 0.785 ms - 178 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"9a498be6-cec6-46e0-acb1-5e156ae6051e"}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"9a498be6-cec6-46e0-acb1-5e156ae6051e"}
info: <-- GET /wd/hub/status 200 0.990 ms - 178 {"status":0,"value":{"build":{"version":"1.3.7","revision":"72fbfaa116d3d9f6a862600ee99cf02f6d0e2182"},"isShuttingDown":false},"sessionId":"9a498be6-cec6-46e0-acb1-5e156ae6051e"}

info: --> POST /wd/hub/session/9a498be6-cec6-46e0-acb1-5e156ae6051e/element {"using":"class name","value":"UIASlider"}

info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByType('UIASlider')"
info: [debug] Sending command to instruments: au.getElementByType('UIASlider')

info: [debug] [INST] 2015-06-22 15:28:26 +0000 Debug: Got new command 109 from instruments: au.getElementByType('UIASlider')

info: [debug] [INST] 2015-06-22 15:28:26 +0000 Debug: evaluating au.getElementByType('UIASlider')

info: [debug] [INST] 2015-06-22 15:28:27 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-06-22 15:28:27 +0000 Debug: responding with:

info: [debug] [INST] 2015-06-22 15:28:27 +0000 Debug: Running system command #110: /Applications/Appium_1.3.7.app/Contents/Resources/node/bin/node /Applications/Appium_1.3.7.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"37"}}...

info: [debug] Socket data received (39 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"37"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"37"},"sessionId":"9a498be6-cec6-46e0-acb1-5e156ae6051e"}
info: <-- POST /wd/hub/session/9a498be6-cec6-46e0-acb1-5e156ae6051e/element 200 840.860 ms - 88 {"status":0,"value":{"ELEMENT":"37"},"sessionId":"9a498be6-cec6-46e0-acb1-5e156ae6051e"}
info: --> POST /wd/hub/session/9a498be6-cec6-46e0-acb1-5e156ae6051e/element/37/value {"id":"37","value":["0.51"]}
info: [debug] Pushing command to appium work queue: "au.getElement('37').setValueByType('0.51')"
info: [debug] Sending command to instruments: au.getElement('37').setValueByType('0.51')

info: [debug] [INST] 2015-06-22 15:28:28 +0000 Debug: Got new command 110 from instruments: au.getElement('37').setValueByType('0.51')

info: [debug] [INST] 2015-06-22 15:28:28 +0000 Debug: evaluating au.getElement('37').setValueByType('0.51')

info: [debug] [INST] 2015-06-22 15:28:28 +0000 Debug: target.frontMostApp().elements()[0].elements()[1].elements()[29].dragToValue("0.51")

info: [debug] [INST] 2015-06-22 15:28:29 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-06-22 15:28:29 +0000 Debug: responding with:

info: [debug] [INST] 2015-06-22 15:28:29 +0000 Debug: Running system command #111: /Applications/Appium_1.3.7.app/Contents/Resources/node/bin/node /Applications/Appium_1.3.7.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...

info: [debug] Socket data received (25 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"9a498be6-cec6-46e0-acb1-5e156ae6051e"}
info: <-- POST /wd/hub/session/9a498be6-cec6-46e0-acb1-5e156ae6051e/element/37/value 200 2442.940 ms - 74 {"status":0,"value":"","sessionId":"9a498be6-cec6-46e0-acb1-5e156ae6051e"}

**Comment by moizjv** [comment]
@sjrjanardhana can you use `setValue` instead? Also try using `50%`

**Comment by sjrjanardhana** [comment]
I have tried setting value suing 0.6 & 60% but still jumps back to old position.

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/ios/IOSElementTest.java#L38 works fine.Please reach us back if you hit the same.

**Comment by SrinivasanTarget** [comment]
@triager please close
