### ISSUE TITLE
iOS: App gets minimized on startup

### ISSUE THREAD

**Issue by nabeel-ibrahim** [appium/appium#5291]
If I have the app as the frontmost application before starting Appium, Appium will minimize the app right away and the session will continue. But if I start Appium without the app running or in the background (minimized), appium will start the app and it will be frontmost. I have the waitForAppScript capability set to true. Is there a way to make sure the app is not in a minimized state. I am running the appium 1.4.6 on iOS 8

**Comment by moizjv** [comment]
@nabeel-ibrahim it is not clear what do you mean. So when app is foremost and you start appium session app is minimized? Can you also provide logs?

**Comment by nabeel-ibrahim** [comment]
these are the logs:
[36minfo[39m: Welcome to Appium v1.4.6 (REV 1efd33330243765bae4e6216b62df3c9ec3cede5)
[36minfo[39m: Appium REST http interface listener started on 127.0.0.1:4723
[36minfo[39m: Console LogLevel: info
[36minfo[39m: File LogLevel: info
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"app":"/Users/nibrahim/Documents/workspace/myAppAutomation/iOS/myApp.ipa","showIOSLog":true,"nativeInstrumentsLib":false,"platformVersion":"8.3","bundleId":"com.myApp.ios.develop","waitForAppScript":true,"udid":"f219c51e1bdb972026c18ace54f4200a2c57ad4c","platformName":"iOS","deviceName":"iPhone","autoAcceptAlerts":true}}[39m
[36minfo[39m: Client User-Agent string: Apache-HttpClient/4.4.1 (Java/1.8.0_45)
[36minfo[39m: Will try to parse the plist file as XML
[33mwarn[39m: Could not parse app Localizable.strings assuming it doesn't exist
[36minfo[39m: Launching instruments
[36minfo[39m: [IOS_SYSLOG_ROW ] Jun 23 13:02:45 QA-iphone6 SpringBoard[54] <Warning>: Entitlement com.apple.multitasking.termination required to kill applications.
[36minfo[39m: [IOS_SYSLOG_ROW ] Jun 23 13:02:45 QA-iphone6 locationd[61] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
[36minfo[39m: [IOS_SYSLOG_ROW ] Jun 23 13:02:45 QA-iphone6 com.apple.xpc.launchd[1] (UIKitApplication:com.thescore.ios.develop[0xcb9b][605]) <Notice>: Service exited due to signal: Killed: 9
[36minfo[39m: [IOS_SYSLOG_ROW ] Jun 23 13:02:45 QA-iphone6 SpringBoard[54] <Warning>: Application 'UIKitApplication:com.thescore.ios.develop[0xcb9b]' exited abnormally via signal.
[36minfo[39m: [IOS_SYSLOG_ROW ] Jun 23 13:02:45 QA-iphone6 assertiond[64] <Warning>: pid_suspend failed for <BKNewProcess: 0x144e25b40; com.thescore.ios.develop; pid: 605; hostpid: -1>: Unknown error: -1, Unknown error: -1
[36minfo[39m: [IOS_SYSLOG_ROW ] Jun 23 13:02:45 QA-iphone6 assertiond[64] <Warning>: Could not set priority of <BKNewProcess: 0x144e25b40; com.thescore.ios.develop; pid: 605; hostpid: -1> to 2, priority: No such process
[36minfo[39m: [IOS_SYSLOG_ROW ] Jun 23 13:02:45 QA-iphone6 assertiond[64] <Warning>: Could not set priority of <BKNewProcess: 0x144e25b40; com.thescore.ios.develop; pid: 605; hostpid: -1> to 4096, priority: No such process

**Comment by nabeel-ibrahim** [comment]
@moizjv Basically what happens is 
I start Appium and if the app was frontmost before starting appium, Appium will close the current app, launch the app and minimize it right away.
But if the app was not running before starting appium, the app will be frontmost

**Comment by SrinivasanTarget** [comment]
@scottdixon We didn't experience this issue as part of Appium 1.5. Please close this.

@nabeel-ibrahim Try in Appium 1.5 and feel free to reopen the same with appium logs as gist incase of any issues.

**Comment by scottdixon** [comment]
@nabeel-ibrahim please reopen the issue if you experience issues with a more recent version of Appium.
