### ISSUE TITLE
wd.quit creates a selenium.common.exceptions.WebDriverException: Message: {"sessionId":null, "status":6, "value":""}

### ISSUE THREAD

**Issue by SportySeb** [appium/appium#5293]
* each time my programm executes the wd.quit command, an exception gets raised
* using appium v1.4.6
* starting appium with: "appium --address 127.0.0.1 --port 4725"

Thank you for your help in advanced.

*My python programm look like this:*
-------------------
from appium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
import time
import os

success = True
desired_caps = {}
desired_caps['appium-version'] = '1.0'
desired_caps['platformName'] = 'Android'
desired_caps['platformVersion'] = '4.4'
desired_caps['deviceName'] = '9255f077'
desired_caps['app'] = os.path.abspath('/home/ipoque/mobile_phone/com.netflix.mediaclient-1.apk')
desired_caps['appPackage'] = 'com.netflix.mediaclient'
desired_caps['appActivity'] = '.ui.launch.LaunchActivity'

wd = webdriver.Remote('http://127.0.0.1:4725/wd/hub', desired_caps)
wd.implicitly_wait(60)

def is_alert_present(wd):
    try:
        wd.switch_to_alert().text
        return True
    except:
        return False

try:
    print("clicking to 'sign in'")
    wd.find_element_by_xpath("//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.view.View[1]/android.support.v7.widget.LinearLayoutCompat[1]/android.widget.TextView[1]").click()

   ....

finally:
    wd.quit()
print("wd.quit")

-------------------

*The appium log says*
---------------------
info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"8"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"8"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: click
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"39cd7dac-fabd-47cb-871b-533e3960ce28"}
info: <-- POST /wd/hub/session/39cd7dac-fabd-47cb-871b-533e3960ce28/element/8/click 200 680.484 ms - 76 {"status":0,"value":true,"sessionId":"39cd7dac-fabd-47cb-871b-533e3960ce28"}
info: [debug] Didn't get a new command in 60 secs, shutting down...
info: Shutting down appium session
info: [debug] Pressing the HOME button
info: [debug] executing cmd: /home/ipoque/mobile_phone/android-sdk-linux/platform-tools/adb -s 9255f077 shell "input keyevent 3"
info: --> DELETE /wd/hub/session/39cd7dac-fabd-47cb-871b-533e3960ce28 {}
info: <-- DELETE /wd/hub/session/39cd7dac-fabd-47cb-871b-533e3960ce28 404 1.532 ms - 40 
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 108.294
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] UiAutomator shut down normally
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
info: [debug] We shut down because no new commands came in

---------------------

*and the log of my programm says*
---------------
closing netflix
Traceback (most recent call last):
  File "FastNetflixTest1.py", line 51, in <module>
    wd.quit()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 477, in quit
    self.execute(Command.QUIT)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 195, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
selenium.common.exceptions.WebDriverException: Message: {"sessionId":null,"status":6,"value":""}

**Comment by moizjv** [comment]
```info: [debug] Didn't get a new command in 60 secs, shutting down...
info: Shutting down appium session```

Looks like it is shutting down after 60 seconds and then you are calling `quit`. So you can try increasing timeout.

**Comment by SportySeb** [comment]
It solved the problem. Thank you very much.

For all others having the same problem : insert the following line in your code:

desired_caps['newCommandTimeout'] = '999'

to get a timeout of 999s instead of the default 90s
