### ISSUE TITLE
runAppInBackground() actually restarts the app

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#5295]
From @exstan

runAppInBackground() method actually restarts the app (after the specified timeout), because it brings the app to foreground using adb -S, which "force stop the target app before starting the activity".
Here is the log snippet:

info: [debug] executing cmd: /.../android-sdk_r24.0.2/platform-tools/adb -s emulator-5554 shell "input keyevent 3"
info: [debug] Getting device API level
info: [debug] executing cmd: /.../android-sdk_r24.0.2/platform-tools/adb -s emulator-5554 shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 19
info: [debug] executing cmd: /.../android-sdk_r24.0.2/platform-tools/adb -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.test.bla.bla/com.test.bla.bla.MyTestApp"
info: [debug] Waiting for pkg "com.test.bla.bla" and activity ".MyTestApp" to be focused

see https://github.com/appium/java-client/issues/209

**Comment by Jonahss** [comment]
@exstan if you want to submit a pull request to fix this bit of code. Shouldn't be too bad :)

**Comment by mayureshshirodkar** [comment]
@jlipps @imurchie I see this issue happening with the current build version 1.6.4-beta.
On Android, when i do a runAppInBackground, it actually restarts the app instead of just bringing the app to the foreground.
The issue exists in the current build.

**Comment by jlipps** [comment]
The API has been updated so that if a seconds value lower than 0 is passed, the app never returns. So this work has been done.
