### ISSUE TITLE
BundelID for iOS

### ISSUE THREAD

**Issue by LokeshGangaiah** [appium/appium#5296]
I have list of App's installed on my iphone device, I need to know how will i get the bundelid for them.
1. Facebook app  -- 
        How will i get the bundelid for this? 
       This is not listing in my xcode->devices list
        Why does it not list?
        The xcode->devices list only the apps which are installed using .ipa file or by installing
        from xcode is it?
2. There are other app's on the device i need to get there bundelid to run, which are not  listed in xcode
3. How will i get the bundelid from itunes?

**Comment by moizjv** [comment]
@LokeshGangaiah please ask questions in [forum](https://discuss.appium.io/), this space is for bugs in appium. You cannot test apps directly from itunes, as mentioned earlier from docs ```Devices: iPhone Simulator, iPad Simulator, and real iPhones and iPads
Native app support: Yes, with debug version of .app (simulator), or correctly-signed .ipa (real devices). Underlying support is provided by Apple’s UIAutomation framework.``` [here](http://appium.io/slate/en/1.4/?java#appium-platform-support).
