### ISSUE TITLE
touchAction use coordinate doesn't work

### ISSUE THREAD

**Issue by BernieLiu** [appium/appium#5298]
what i want to do is swipe the screen from right to left. 
using java-client 2.2.0&appium 1.4.0

first i use swipe method, but it says "Tried to execute non-existent mobile command 'swipe'."

then i try touchAction:

ta = new TouchAction(driver);
ta.press((int) (w*0.8), h/2).waitAction(1000).moveTo((int) (0.2*w), h/2).release().perform(); //w is the width and h is the height of screen.

the log:
info: <-- POST /wd/hub/session/fc770c14-df33-4fdb-887d-9bcab71b0605/touch/perform 200 1184.607 ms - 74 {"status":0,"value":"","sessionId":"fc770c14-df33-4fdb-887d-9bcab71b0605"}

info: --> POST /wd/hub/session/fc770c14-df33-4fdb-887d-9bcab71b0605/touch/perform {"actions":[{"action":"press","options":{"x":300,"y":333}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":75,"y":333}},{"action":"release","options":{}}]}
info: [debug] Pushing command to appium work queue: "au.dragApp(300,333,75,333,1)"
info: [debug] Sending command to instruments: au.dragApp(300,333,75,333,1)
info: [debug] Socket data received (25 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"fc770c14-df33-4fdb-887d-9bcab71b0605"}

it seems the command is successful but the nothing happens on UI. 

am i use it  mistakenly？

**Comment by moizjv** [comment]
try using `scroll`. [documentation](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md#bugs-and-workarounds)

**Comment by BernieLiu** [comment]
the app crash when scroll.
first i use scroll with out specifying an element, doesn't work.

i use instrument to record the operation i want, it shows below.
target.frontMostApp().mainWindow().scrollViews()[2].webViews()[0].images()[0].scrollToVisible();

then i find the element to scroll, the scroll with element id，
"au.getElement('0').scrollLeft()"

the app also crash. here is log
{"status":17,"value":"Unexpected error in -[UIAImage_0x7f826843b6e0 scrollLeft], /SourceCache/UIAutomation_Sim/UIAutomation-430.1.1/Framework/UIAElement.m line 1487, kAXErrorFailure"}
 

btw, i use iOS8.3 simulator, saw https://github.com/appium/appium/issues/4836 says, gesture methods can't work on 8.3?

**Comment by BernieLiu** [comment]
i tried an other app(main UI is not webview) with the same swipe/touchAction code，it works. 
so may be because of the app main UI is a webview so  the swipe/touchAction can't work. 

can anybody tell me how to solve it ?

**Comment by diana-zaharia** [comment]
I am experiencing the same issue when using `mobile: scroll`, please see logs below
```
info: --> POST /wd/hub/session/b1b2a6b8-cc52-45a9-8631-b3a6504483f5/execute {"script":"mobile: scroll","args":[{"direction":"down"}]}
info: [debug] Pushing command to appium work queue: "au.scrollFirstView('Down')"
info: [debug] Sending command to instruments: au.scrollFirstView('Down')
info: [debug] [INST] 2015-06-25 14:20:06 +0000 Debug: Got new command 9 from instruments: au.scrollFirstView('Down')
info: [debug] [INST] 2015-06-25 14:20:06 +0000 Debug: evaluating au.scrollFirstView('Down')
info: [debug] [INST] 2015-06-25 14:20:06 +0000 Debug: Looking for view of type scrollview
info: [debug] [INST] 2015-06-25 14:20:07 +0000 Debug: target.frontMostApp().elements()[1].elements()[2].scrollDown()
info: [debug] [INST] 2015-06-25 14:20:07 +0000 Debug: Unexpected error in -[UIAScrollView_0x7fd9d0c4d7b0 scrollDown], /SourceCache/UIAutomation_Sim/UIAutomation-430.1.1/Framework/UIAElement.m line 1480, kAXErrorFailure
```
Appium 1.4.0, iOS 8.3 simulator.

**Comment by moizjv** [comment]
@BernieLiu are you in native context?
@diana-zaharia try waiting little bit before executing scroll?

**Comment by diana-zaharia** [comment]
@moizjv I tried waiting, doesn't seem to help. Is this related to iOS 8.3, the issue mentioned earlier by @BernieLiu ?

**Comment by BernieLiu** [comment]
before the operation i use getContext, shows  "NATIVE_APP"
@moizjv do you mean that i should in WebView context?

**Comment by moizjv** [comment]
@diana-zaharia @BernieLiu so i tried to reproduce. For me it happens when i try to scroll down a view which is already scrolled down, example: `driver.execute("mobile: scroll", [{direction: 'down'}]);` works for first time and then when second time `driver.execute("mobile: scroll", [{direction: 'down'}]);` since view is already scrolled down it throws this error. It is issue with instruments. For now work around is to catch the exception since view is already scrolled down

**Comment by Jonahss** [comment]
@BernieLiu for your original issue:

Maybe you could use accessibility developer settings to have the device show where you are tapping/swiping. It's possible that the touch action is successful but for whatever reason, the device isn't swiping.
Try playing with the placement of your coordinates.

**Comment by nhanh2301** [comment]
Me too... In Web View, i can't swipe with touchAction
This error:

Error: [performTouchAction([{"action":"press","options":{"x":1050,"y":700}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":50,"y":700}},{"action":"release","options":{}}])] Error response status: 17, , JavaScriptError - An error occurred while executing user supplied JavaScript. Selenium error: An error occurred while executing user supplied JavaScript.

How to fix it?

**Comment by Jonahss** [comment]
@nhanh2301 could you please post the full appium server logs? They will probably contain more information as to what went wrong.

Your issue is different from the original error in this thread. In the original issue, no error is thrown. Could you open a new issue for your problem?

**Comment by vinceis1337** [comment]
Just wanted to add on I am actually coding TouchActions myself and they do NOT work on Simulator (Simulated iPhone 6 iOS 8.1 or 8.3 was the phone I used). They seem to do nothing at all. Whether I use driver.swipe or code the TouchAction manually. Both work on an Actual iPhone 6 iOS 8.1.2.

**Comment by Simon-Kaz** [comment]
^ thats a known issue @vinceis1337 and it's apple's instruments/simulator and not appium.

**Comment by SrinivasanTarget** [comment]
@triager please close
