### ISSUE TITLE
Error in uiautomatorviewer while scrolling (Error obtaining UI hierarchy)

### ISSUE THREAD

**Issue by tajmulhussainr** [appium/appium#5299]
Hi,

Sometimes uiautomatorviewer throws below mentioned error while obtaining screenshot in my application. Remedy is to restart the uiautomatorviewer.

Error obtaining UI hierarchy Reason:Error while obtaining UI hierarchy XML file.com.android.ddmlb.SynchException.Remote object doesn't exist.

How can I achieve this in appium, Is there any possibilities to restart uiautomatorviewer from code ?

**Comment by moizjv** [comment]
@tajmulhussainr I don't think this is appium issue. Is this related to appium gui clients?

**Comment by Jonahss** [comment]
Hm yeah. Using just appium, you should get the screenshot just fine.
Not sure about using uiautomatorviewer at the same time as appium.

**Comment by tajmulhussainr** [comment]
First of all sorry for the delayed response.

Tried with appium gui as well. Its not able to get the screenshot and it didn't throw any exception like uiautomator.

**Comment by Jonahss** [comment]
Instead of appium gui, could you use appium server from the command line, and then run a test script that just takes a screenshot? That would eliminate many variables.
