### ISSUE TITLE
provide a API for retrieving the information about which mode of orientation of a page is locked

### ISSUE THREAD

**Issue by prachi02** [appium/appium#5300]
As a tester, I want verify if for a page an orientation mode is locked.

**Comment by moizjv** [comment]
@prachi02 what do you mean? is this for iOS or Android?

**Comment by prachi02** [comment]
Its for both...Android and iOS

**Comment by jlipps** [comment]
there's already an api to get the current orientation...

**Comment by prachi02** [comment]
@jlipps.. there is no method in appium which returns all orientations that app Activity can perform...
One available method return activity current orientation, other method performs orientation this method throws exceptions if activity is not allowed to perform that orientation ....

**Comment by moizjv** [comment]
@prachi02 yes so if it throws exception then that would be enough to verify if orientation is locked?

**Comment by jlipps** [comment]
it's not appium's job to know what orientations your app supports. that's your app's job. but you can use moiz's strategy to verify it using appium.

**Comment by prachi02** [comment]
@Moizjv..Right now...I am catching the exception...
