### ISSUE TITLE
How to test Hybrid app build by Angular and OnsenUI

### ISSUE THREAD

**Issue by nhanh2301** [appium/appium#5303]
Hello Everybody!

I need test hybrid app build by AngularJS and OnsendUI.

Test on chrome, safari browser and app in android, ios.

**Comment by moizjv** [comment]
@nhanh2301 Please refer to [documentation](http://appium.io/slate/en/1.4/?java#automating-hybrid-apps). Please use [forum](http://discuss.appium.io) for questions. This space is for bugs in appium.
