### ISSUE TITLE
iOS: Could not use button_click after upgrade appium_lib from 5.0.1 to 7.0.0 

### ISSUE THREAD

**Issue by ravikumarachi** [appium/appium#5304]
I was using Appium_lib 5.0.1 and able to use below method:
1: exists { button(buttonText)}
2: button('show alert').click

But after appium_lib upgrade to version 7.0.0 I could not use the above methods.

Related to App: Nothing has been changed. If I switch back to previous version 5.0.1 then scripts are working as expected.

Can you please have a look into this.

**Comment by moizjv** [comment]
@ravikumarachi did you upgrade appium server? By apium_lib do you mean ruby client. If you think there is an issue with ruby client please raise a defect in [ruby_lib](https://github.com/appium/ruby_lib).

**Comment by ravikumarachi** [comment]
I dont think so it is problem with Ruby.
for android it is fine but for only ios.
applium_lib is changed to 7.0.0.

**Comment by moizjv** [comment]
@ravikumarachi can you raise an issue in  [ruby_lib](https://github.com/appium/ruby_lib) ?

**Comment by Jonahss** [comment]
Yes, you should post the issue to ruby_lib, instead of the main appium server.
