### ISSUE TITLE
Ruby code for hybrid apps uses non-defined methods

### ISSUE THREAD

**Issue by jmmerinero** [appium/appium#5307]
https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/hybrid.md & http://appium.io/slate/en/v1.0.0/?python#automating-hybrid-apps

The official documentation includes an example written in Ruby but it uses methods which are not defined for **Selenium::WebDriver** or **Selenium::WebDriver::Driver**.

It would be great if you could update the documentation with a working example.

**Comment by jlipps** [comment]
@jmmerinero the examples are meant to be run using https://github.com/appium/ruby_lib. appium supports methods that aren't included in the webdriver gem

**Comment by Jonahss** [comment]
If there are specific issues with the Ruby client, could you post in the github repo for that project? thanks
