### ISSUE TITLE
1.4.6 IOS safari browser multiple tests not running(Could not find web view.. there aren't any)

### ISSUE THREAD

**Issue by anmudgal** [appium/appium#5309]
Appium 1.4.6 did not solve a long due problem of (iOS webkit debug proxy issue) "IOS Safari browser multiple tests running sequentially on same device". Uptil 1.4.3 this scenario used to work after restarting appium and iOS_debug_webkit_proxy after every test.. 1.4.6 can not find any web views for second test even after restarting. 
And on 1.4.3 Android chrome is not working. Can you please help me here.. I am ok with patching 1.4.3 for android to work, which already works for IOS with restart solution.

**Comment by moizjv** [comment]
@anmudgal can you try using 1.4.6 for android chrome?

**Comment by anmudgal** [comment]
Yes Android tests are running in 1.4.6 even though I can see 
"error: Trying to proxy a session command without session id"
in the Appium logs


Now I will recheck the iOS tests even though when I tried earlier( on Appium 1.4.6) iOS Safari sequential tests do not work but they work with Appium 1.4.3 (with restarting appium and iOS webkit proxy after every test).

I will post my findings here.

Thanks@moizjv

**Comment by anmudgal** [comment]
Yes this is consistent with Appium 1.4.6, after first iOS Safari web test, I call driver.quit() and shut down appium and iOS_webkit_debug_proxy.. For second test,I restart appium and iOS_webkit_debug_proxy it launches SafariLauncher, opens Safari and can not type url.
Appium logs say: 
A new session could not be created. (Original error: Could not navigate to webview; there aren't any!)

IOS webkit logs say something like: "Connection close"

Retrying(restarting and rerunning script) 3 or 4 times might give a webview to appium.

In Appium 1.4.3, appium was getting webview most of the times with same steps. 

Please let me know if need any logs or information from my side.
Thanks

**Comment by vbhojaraja** [comment]
I am also facing the same issue with running tests on real device

**Comment by Jonahss** [comment]
@vbhojaraja Is your issue the same? Your first test runs fine on a real device, and then following tests fail?

**Comment by Jonahss** [comment]
@anmudgal I can see where the issue could arise. You are keeping the same app running, and multiple sessions try to connect to the same webview. You mentioned this being a long-standing issue. Can you link to an older ticket for this?

**Comment by vbhojaraja** [comment]
@Jonahss : I am facing this issue every time i am executing the test case.

**Comment by anmudgal** [comment]
@Jonahss I am not keeping the same App running, the sequence of events is as follow:

1) I start Selenium grid hub, appium and iOS debug webkit proxy(http://localhost:27753/json shows the available web view)
2) I run the test on iPhone Safari browser with a single session(SafariLauncher launches Safari web view gets refreshed and http://localhost:27753/json shows the available web view and test gets executed).
3) After completion of test, I call driver.quit() which closes and clears the current session and send 9 signal to Safari Browser tab and also Safari Launcher App, which eventually closes the current tab(where test was executed).
4) I shut down appium and iOS debug webkit proxy (If I don't shut down one or the other problem happens for the next test, most occurring is debug webkit proxy exits).

5) I restart appium and iOS debug webkit proxy(http://localhost:27753/json shows the available web view)
6) I run the next test - (SafariLauncher launches Safari web view gets refreshed but http://localhost:27753/json shows blank json).

7) After a few minutes appium throws error "Could not find web view there aren't any" as http://localhost:27753/json shows blank json.

I did not open any issue earlier for this, but facing multiple tests not running sequentially since Appium 1.3(without restarting anything). A lot of Appium code has changed since then and this scenario started working for me Appium 1.4.1 onwards with restarting solution and new SafariLauncher. In Appium 1.4.3 restart solution works fine but not in Appium 1.4.6. I did not try the versions between 1.4.3 and 1.4.6

**Comment by anmudgal** [comment]
So for second test after launching Safari Browser iOS debug webkit proxy can not get webviews and keeps the json array empty.

**Comment by Jonahss** [comment]
@anmudgal the issue might have something to do with the selenium grid setup, is that possible? Does the same issue occur if you just run sequential safari tests with a single appium server?

**Comment by Jonahss** [comment]
@vbhojaraja it sounds like your issue is not the same as @anmudgal's can you create a separate issue please?

**Comment by anmudgal** [comment]
@Jonahss No I don't think selenium grid has a role in it, It is either between interaction of appium and iOS_debug_webkit_proxy or the  iOS_debug_webkit_proxy alone.

If I keep same appium running(don't restart) then iOS_debug_webkit_proxy shows "child process exits with code 0" on second test. I will reconfirm this though.

**Comment by Jonahss** [comment]
@anmudgal how are you running ios_webkit_debug_proxy? Are you using the helper script found in `./bin/ios-webkit-debug-proxy-launcher.js`?

**Comment by anmudgal** [comment]
@Jonahss Yes.

**Comment by Jonahss** [comment]
What about when you leave the debug_proxy running in between tests. That is how our tests usually run. Hmmmm, ok I will try running tests like you. I will run a safari test, then restart appium and the debug proxy and run a second test.

**Comment by Jonahss** [comment]
Running on:
 iOS real device 8.3
Xcode 6.4
Appium 1.4.7

I started appium and debug_proxy. I ran a simple safari test three times. Then i restarted appium and the debug_proxy. ran test again and it passed.

I tried a bunch of combinations: leaving debug_proxy running and restarting appium. leaving appium running and restarting debug_proxy. Restarting both.

Test passed.

Maybe your doing the restarts programmatically, so some race condition exists? Try adding waits to your scripts to make sure things have fully started before testing?

How should I work to reproduce your issue?

**Comment by anmudgal** [comment]
I am using ios 7.1, Xcode 5.1, Appium 1.4.6

Here is the combination I am going to try later on:
ios 7.1, Xcode 6.1, Appium 1.4.7
ios 7.1, Xcode 5.1, Appium 1.4.7
ios 8.3, Xcode 6.1, Appium 1.4.7

I will post my findings here.. Also as mentioned earlier if I keep appium and debug proxy running.. debug proxy exits with message child process exits 0,

About your tests are you running selenium tests using java?? And are you calling driver.quit after every test??

**Comment by anmudgal** [comment]
@Jonahss 
I am using ios 7.1, Xcode 5.1, Appium 1.4.6

Here is the combination I am going to try later on:
 ios 7.1, Xcode 6.1, Appium 1.4.7
 ios 7.1, Xcode 5.1, Appium 1.4.7
 ios 8.3, Xcode 6.1, Appium 1.4.7

I will post my findings here.. Also as mentioned earlier if I keep appium and debug proxy running.. debug proxy exits with message child process exits 0,

About your tests are you running selenium tests using java?? And are you calling driver.quit after every test??

**Comment by Jonahss** [comment]
I'm running the tests using wd.js not java, but that shouldn't make a difference.

Yes I'm calling driver.quit after the tests.

If you upgrade to Xcode6.1 you should really really use 6.4, or 6.3.2 minimum. 6.3.2 fixed a couple bugs with Instruments.

**Comment by anmudgal** [comment]
I can't, as Xcode 6.3.2/6.4 need OSX 10.10 and my workplace allows upto OSX 10.9, that support will come later on.

**Comment by SrinivasanTarget** [comment]
@triager please close
