### ISSUE TITLE
Appium 1.4.6 iOS, not able to scroll in collectionview

### ISSUE THREAD

**Issue by qaDream77** [appium/appium#5310]
Swipe doesn't work and i read that scroll (start, end) was introduced. Nothing happens when i try to use scroll programmatically.

The appium func
    def scroll(self, start_locator, end_locator):
        el1 = self._element_find(start_locator, True, True)
        el2 = self._element_find(end_locator, True, True)
        driver = self._current_application()
        driver.scroll(el1, el2)

Doesn't do anything, doesn't throw an error.

Using Appium Inspector, i am able to use Scroll To, is that python code available anywhere? I am curious as to what the start position should be when i am doing it programmatically.

Similarly, is there any function for both iOS and Android that would scroll until an element comes into view? (This would be the ultimate addition, i tried making my own with little success).

EDIT: I used mobile:scroll and it works for up/down but not side-to-side. One app opens a side menu when i swipe right, is this a limitation of mobile:scroll or am i using the wrong functionality?

Thanks for the feedback on iOS scroll.

**Comment by Jonahss** [comment]
The appium inspector, and the python client are both open source right here :)
https://github.com/appium/appium-dot-app
https://github.com/appium/python-client

Scrolling is kind of in flux right now as we haven't decided on a single system which works well in both iOS and Android. Plus there are constant bugs related to this in Intruments itself.

The most reliable method of scrolling is to create TouchActions which swipe on the screen.

**Comment by rxiong** [comment]
Hi, we are having same issue and this is the result of using TouchActions is that we cannot cast to hasTouchScreen.

java.lang.ClassCastException: io.appium.java_client.ios.IOSDriver cannot be cast to org.openqa.selenium.interactions.HasTouchScreen

Is there a MobileTouchActions version or what am I missing?

**Comment by Jonahss** [comment]
Make sure you import io.appium.java_client.TouchAction and not the selenium one. Sorry about that.

**Comment by qaDream77** [comment]
Thanks for the reply Jonahss, in iOS mobile scroll to seems to work well enough but in android i noticed that using both scroll and swipe is very inconsistent and even the touch actions don't mitigate that inconsistency by much. Is there anything in the appium library for android that is equivalent to the ios mobile:scroll to?

I imagine that the limitation you are facing is that android doesn't load all of the elements into the xml like ios does?

**Comment by Jonahss** [comment]
Yup. You figured out the limitation exactly. We're still trying to decide on a really good way to do scrolling.

In android, you can use the findByAndroidUIAutomator and pass in something like "new UIScrollable(new UISelector().children()).scrollTo()" or something like that. My syntax is probably incorrect, but there are some UIScrollable commands that will work in appium this way.

Check out the code in the Ruby client for an example.
