### ISSUE TITLE
Browsable intent url not opening app

### ISSUE THREAD

**Issue by vrunoa** [appium/appium#5311]
I have a simple test on Android that clicks on an ```<a>``` element with an browsable intent url on an ```href``` and then waits for an application to launch. 
The test finds the element, clicks on it but the app is never launched. I tried using both ```.click``` and ```.tap``` over the element but the app is never launched. This only happens when using appium, if I open the same test url site and click it manually it does opens my application. 
Trying different things, I managed to make it work by adding a ```onclick="window.open('intent://...)"``` attribute on the ```<a>``` element by executing a script before clicking on the intent url;
```javascript
let script = 'document.querySelectorAll(\'[href="intent://..."]\')[0].setAttribute("onclick","window.open(\'intent://...\')")';
driver.executeScript(script);    
``` 
Or simply put the ```onclick="window.open('intent://...) ``` in the html code. But I didnt want to change my html source code. 

Has anyone ever had this problem ? What solution did you implement ? Is this an appium or a browser issue ?

**Comment by Jonahss** [comment]
Hm. I assume you're inside the WEB context when you're running the tap and click commands? What happens if you switch to the NATIVE context and use a TouchAction onto the coordinates of the <a> element?

Not sure why this isn't working for you....

**Comment by vrunoa** [comment]
I'm inside WEB context when I tap on the link. It never occur to me to switch to NATIVE and then touch on the link. I'll give it a try and let you know.

**Comment by Jonahss** [comment]
If you could provide us with an example app to reproduce this, we could experiment with it. Maybe the simplest possible app (or web page) with a single <a> element to launch an intent....

**Comment by vrunoa** [comment]
I play a little an manage to make it work by changing into ```NATIVE_APP``` contexts and perform a TouchAction. Much better solution that adding a ```onclick="window.open(intent://...)"```. Thanks for this advice @Jonahss.

I didn't look the element directly on ```NATIVE_APP``` contexts, 'cause in my case I don't know which is going to be. In my case this element could change from test to test. I just search for the ```<a>``` element with the custom ```intent://``` and then calculate the coords of this element inside the web view. 

Maybe for @kani19 issue [#5302](https://github.com/appium/appium/issues/5302) it would be better to directly look for clickable element in ```NATIVE_APP``` contexts. 

Here's my action for clicking on the intent:
```javascript

let webViewXPath = '//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.webkit.WebView[1]/android.view.View[1]';

let pressAction = (driver, coords) => {
  let action = new wd.TouchAction(driver);
  action.press({x:coords.x,y:coords.y}).wait(10).release()
  return action;
}
// i've already found the element to click as pass it as intentClick param
let intentClick = (driver, el) => {
  let elCoords;
  // get element location
  driver.getLocation(el, (err, coords) => {
    if(err) return error(err);
    elCoords = coords;
    driver.context('NATIVE_APP', (err) => {
      if(err) return error(err);
      driver.elementByXPath(webViewXPath, (err, el) => {
        if(err) return error(err);
        driver.getLocation(el, (err, coords) => {
          if(err) return error(err);
          let action = pressAction(driver, {x: elCoords.x, y: (coords.y + elCoords.y)});
          action.perform( (err) => {
            if(err) return error(err);
            isApplicationRunning(config);
          });
        });
      });
    });
  });
}
```
Full test [here](https://github.com/Urucas/zoster/blob/master/lib/android_test.js#L57).


P.S. As you ask me, I provide you the example I use to experiment .[https://gist.github.com/vrunoa/ca7683e35052f2cdeb1e](https://gist.github.com/vrunoa/ca7683e35052f2cdeb1e)

**Comment by Jonahss** [comment]
cool thanks for using appium-repl!

Your project looks cool. It almost makes sense that clicking on the element inside the web context doesn't work. When i click on your sample link on my desktop computer in chrome, nothing happens. So if we connect to chrome debugger tools in the webview and click, it makes sense that nothing happens there.

Good find, I'm sure other people will run into this sort of issue. Maybe write a post about it on discuss.appium.io ?

**Comment by vrunoa** [comment]
Just posted on discuss.appium.io, [https://discuss.appium.io/t/clicking-on-an-intent-url-not-http-link-inside-a-webview-solved/5022](https://discuss.appium.io/t/clicking-on-an-intent-url-not-http-link-inside-a-webview-solved/5022)
