### ISSUE TITLE
Appium can't recover a backgrounded selendroid app

### ISSUE THREAD

**Issue by vicwomg** [appium/appium#5316]
When using selendroid, the appium session doesn't recover from backgrounding (driver.runAppInBackground). The driver wont even process getPageSource(), even though the app appears on screen. 

Appium logs indicate it's sending adb commands but selendroid might have it's own bindings for backgrounding and recovering the app that allow it to recover: http://selendroid.io/advanced.html#backgroundApp

Error is:
Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Did not successfully proxy server command"}

Sample code (java/testng) to reproduce the issue, using the selendroid test app:

``` java
    @Test()
    public void testSelendroidTestApp() throws Exception{
        //Setup
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("automationName", "Selendroid");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("platformVersion", "4.4");
        capabilities.setCapability("deviceName", "Emulator");
        capabilities.setCapability("app", "http://central.maven.org/maven2/io/selendroid/selendroid-test-app/0.15.0/selendroid-test-app-0.15.0.apk");
        capabilities.setCapability("appPackage", "io.selendroid.testapp");
        capabilities.setCapability("appActivity", ".HomeScreenActivity");
        capabilities.setCapability("appWaitActivity", ".HomeScreenActivity");
        URL url = new URL("http://localhost:4723/wd/hub");
        AndroidDriver driver = new AndroidDriver(url, capabilities);

        //Test
        driver.getPageSource(); //OK
        driver.runAppInBackground(2);
        driver.getPageSource(); //Throws error
    }
```

When I switch automationName capability to default Appium, there is no issue. So definitely unique to the selendroid bindings

Full appium log here:
https://gist.github.com/vicwomg/35705da6cab74f50a23c

**Comment by Jonahss** [comment]
Thanks for the error report. Good reproduction code. We will have to look at the way selendroid handles backgrounding.

**Comment by vicwomg** [comment]
So far the only way I can get backgrounding to work on this version of selendroid is to send the HOME key, then recover the app using "adb shell am start -n <app_package/app_activity>

**Comment by jlipps** [comment]
support for selendroid has been discontinued, so closing this bug
