### ISSUE TITLE
Discussion: strategies for fixing dependencies in Appium

### ISSUE THREAD

**Issue by jlipps** [appium/appium#5317]
### The Problem

One of the downsides of breaking Appium apart into multiple independently-developed and -tested projects is dependency management becomes more complicated. NPM's package.json gives us various ways to specify dependencies. We can specify exact versions, or use symbols that denote version ranges. In most of the Appium packages, we use `^` for dependencies, which means "get me the latest patch version". If everyone is following semver, this should be OK, but sometimes 3rd parties (or, sadly, ourselves) might inadvertently release a broken package as a patch release. This would immediately break upstream packages for anyone who's doing a fresh `npm install`, and we would be none the wiser. We need a system for ensuring this kind of problem doesn't occur.

### Possible solutions

Here are some possible solutions (maybe there are others):

0. Stop using `^` in any project. Always specify exact dependency versions.
    * Pros: complete control
    * Cons: huge dependency management headache. We will probably more frequently release a patch change that _doesn't_ break than one that does. To have to explicitly update the entire dependency tree and re-publish to take advantage of this change would be onerous.
0. Use `^` only for projects we own (trusting that we will not release breaking changes as patch releases). Use exact versions for 3rd-party deps.
    * Pros: we can avoid 3rd-party breakages while taking advantages of auto-upgrading packages whose quality we can control. If something breaks, we can release a new patch version of the broken package quickly and the problem will be resolved.
    * Cons: this doesn't fix sub-deps of 3rd-party deps breaking. It also keeps us somewhat open to breakages that are our own fault.
0. Use `^` for all projects, but use `npm-shrinkwrap` when publishing the top-level project (appium/appium) so that `npm install appium` always returns the exact same subset of dependencies for a particular version of appium.
    * Pros: We are guaranteed that every Appium install will involve the same deps.
    * Cons: npm shrinkwrap is not entirely user friendly (or entirely unbroken, from what I can tell). There is confusion around when we would run shrinkwrap, whether we would keep it in source control, how it handles dev dependencies, and so forth.
0. Use `^` for all projects, and use `npm-shrinkwrap` when publishing all projects.
    * Pros: even more control than the previous solution. It also means we don't have runaway dependency problems in each project. This is useful if, say, another project was using appium-adb on its own, or appium-xcode on its own. We would be adding shrinkwrap protection to each one.
    * Cons: all the cons of the previous solution, plus we get back into the realm of having to make explicit updates and re-publishes to deps when sub-deps change.
0. Stop using `^` in any project. Always specify exact dependency versions. Only on this idea, write an automated tool (part of Turtledeps, perhaps) to update dependents, run tests, and re-publish automatically. (I.e., this is the same as the first option with some automation)
    * Pros: mixes complete control with lesser management headache
    * Cons: it's unclear whether an algorithm exists to safely run this logic. It'd probably require a setup involving a bunch of git clones and test environments ready to go. Might be more work than is worth it.

So let's discuss!

**Comment by sebv** [comment]
You have also the `~` option for dependency, it will only upgrade patch versions.

**Comment by imurchie** [comment]
Npm 3 [looks](https://github.com/npm/npm/releases/tag/v3.0.0) also like it might help with the issues we're experiencing.

**Comment by jlipps** [comment]
@sebv ah I was confused, I thought `^` only upgraded patch as well

**Comment by sebv** [comment]
@jlipps https://github.com/npm/node-semver#caret-ranges-123-025-004

**Comment by sebv** [comment]
Also I think 3 and 4 are the same, view from the main appium package. 

shrinkwrap is a good idea, just don't ever use it for dev dependencies. (So publish time is a good time). I don't think we need to  shrinkwrap dependency package, so I vote 3.

Fixing all the versions is a bad idea, if everybody was doing that, the Node.js ecosystem would be totally broken.

**Comment by Jonahss** [comment]
I'm for option 3. Thanks @imurchie for pointing out npm v3. Looks like it specifically fixes some of our issues. I still think that npm-shrinkwrap is broken if people are using different versions of node though :(

I'm for keeping `^` versioning for *most* dependencies. My ideal suggestion is as follows:

Use strict `=` versioning for all appium modules. Use `^` versioning for most dependencies. When it comes to super critical dependencies that have lost our trust (babel), we should lock those down to a strict `=`.

The way the node ecosystem works is modules are constantly updated and bug fixes come in. We already work hard to keep our dependencies up to date. It's fine if users who install at different times get different versions of lodash, because we trust lodash (also, patch updates usually FIX bugs more often than they introduce them). So by using `^` we keep our users with the most up to date code. If a 3rd party releases something in a patch version that breaks, they then go about fixing it right away and release a new version. (If they don't fix it right away, then we don't trust them and switch to `=` versioning).

We ourselves want to encourage this. If a bug comes up in appium, we can quickly release a patch version to fix and we hope that everybody is automatically updating to latest patch version.

**Comment by sebv** [comment]
@Jonahss I suspect it is related to old npm versions, when you install older node, you get older npm version, but you may upgrade it without having to upgrade node.

**Comment by moizjv** [comment]
So i was dealing with shrinkwrap in 1.4.7. I like the idea. 

It makes a lot of sense to add shrinkwrap when we release so we can lockdown dependencies. And in ideal world we will have shorter release cycles, implying our users using will be using updated versions with each new release. 

But when we are hacking we want to install dependencies which are latest. Also with time we would become more aware of issues that can come up when releasing a version. Like to use `npm intall --production` before releasing. Perhaps we can add all `shrinkwrap` related commands to our publish script. And ignoring shrinkwrap in `reset.sh` script. Option 3 is the best and with time we can completely overcome `cons` mentioned in that point.

**Comment by jlipps** [comment]
OK, I'm cool with option 3 as well (talked with Jonah IRL).
