### ISSUE TITLE
Unhandled exception EPIPE

### ISSUE THREAD

**Issue by chris1248** [appium/appium#5318]
So I was running some rspec tests again the IPad simulator using appium, when it crapped out on me with this cryptic message:

`error: uncaughtException: write EPIPE date=Tue Jun 30 2015 17:07:45 GMT-0600 (MDT), pid=2348, uid=1465707852, gid=1095186886, cwd=/Users/cjohnson/code/appium, execPath=/usr/local/Cellar/node/0.12.4/bin/node, version=v0.12.4, argv=[node, /Users/cjohnson/code/appium/lib/server/main.js, --session-override], rss=259129344, heapTotal=131841792, heapUsed=67632848, loadavg=[5.27294921875, 3.24609375, 2.546875], uptime=633176, trace=[column=11, file=util.js, function=exports._errnoException, line=746, method=_errnoException, native=false, column=14, file=net.js, function=WriteWrap.afterWrite, line=775, method=afterWrite, native=false], stack=[Error: write EPIPE,     at exports._errnoException (util.js:746:11),     at WriteWrap.afterWrite (net.js:775:14)]`

Hopefully you guys can decipher that stuff.

Here is the code I used to run it:

    Capybara.register_driver(:appium) do |app|
      # Set the ip address of the where the browser will navigate to
      Capybara.app_host = ENV["BRIDGE_HOST"]
      # By default Capybara starts this web server listening to localhost only
      # It is advised to force Capybara to listen to all interfaces
      Capybara.server_host = "0.0.0.0"
      # instead of using a random port, let's just use one we pick
      Capybara.server_port = 5567
      # To start the server, install the appium tools
      # and start the Appium server with this url
      url = "http://0.0.0.0:4723/wd/hub"
    
      # Setup the capabilities
      desired_caps_ios = {
        platform:        "Mac",
        platformName:    "iOS",
        platformVersion: "8.3",
        browserName: "Safari",
        noReset: false, # this
        # fullReset: true # and this are mutually exclusive
      }
    
      # For a list of devices we can assign for the :deviceName, See the documentation here:
      # http://appium.io/slate/en/master/?ruby#server-flags
      # specifically this command:
      # instruments -s devices
      desired_caps_ios[:deviceName] = case ENV["APPIUM_DEVICE"]
        when "IPad"
          "iPad Air"
        when "IPhone"
          "iPhone 6 Plus"
        else
          "iPad Air"
      end
    
      # See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md
      appium_lib_options = {
        server_url:           url,
        newCommandTimeout: 15, # How long (in seconds) Appium will wait for a new command from the client before assuming the client quit     and ending the session
        showIOSLog: true, # Whether to show any logs captured from a device in the appium logs. Default false
        webviewConnectRetries: 15, # Number of times to send connection message to remote debugger, to get webview. Default: 8
        launchTimeout: 15 * 1000, # Amount of time in ms to wait for instruments before assuming it hung and failing the session
        debug: false # uncomment to get a deluge of debugging messages
      }
      all_options = {
        appium_lib:  appium_lib_options,
        caps:        desired_caps_ios,
      }
    
      Appium::Capybara::Driver.new app, all_options
    end

**Comment by Jonahss** [comment]
Can you post any of the appium logs for this? It's an OS-level error. Perhaps something dies somewhere and closed one end of a pipe.

**Comment by jwallis** [comment]
I can reproduce this pretty consistently if not 100%.  My app has a very large XML tree and after au.mainApp().getTreeForXML() logs the tree it dies:


info: --> GET /wd/hub/session/8fe681a5-8428-4534-9822-108848f233c9/source {}
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()
info: [debug] [INST] 2015-09-17 20:01:54 +0000 Debug: Got new command 51 from instruments: au.mainApp().getTreeForXML()
info: [debug] [INST] 2015-09-17 20:01:54 +0000 Debug: evaluating au.mainApp().getTreeForXML()
info: [debug] [INST] 2015-09-17 20:02:06 +0000 Fail: The target application appears to have died
info: [debug] [INST STDERR] 2015-09-17 15:02:06.364 instruments[28048:996493] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST] 2015-09-17 20:02:06 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-09-17 20:02:06 +0000 Debug: responding with:alid":true,"visible":true,"hint":null,"path":"/0/0","x":0,"y":0,"width":375,"height":667},">":[]}},{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/1","x":0,"y":0.6875,"width":375,"height":665.625},">":[{"UIAButton":{"@":{"name":"Cancel","label":"Cancel","value":null,"dom":null,"enabled":true,"vali

...

info: [debug] [INST] 2015-09-17 20:02:06 +0000 Debug: Running system command #52: /usr/local/Cellar/node/0.12.7_1/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"my_app","label":"my_app","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":...
info: [debug] Socket data being routed.
info: [debug] Got null result from instruments
error: Couldn't parse result buffer: SyntaxError: Unexpected end of input
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"\"Error parsing socket data from instruments\""},"sessionId":"8fe681a5-8428-4534-9822-108848f233c9"}
info: <-- GET /wd/hub/session/8fe681a5-8428-4534-9822-108848f233c9/source 500 11979.853 ms - 215 
info: [debug] [INST] Instruments Trace Complete (Duration : 263.628479s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator
info: [debug] Cleaning sim data files
info: node-simctl: Executing: xcrun with args: simctl erase DB3378BA-5ACB-45C3-A61B-571223EC85C2 and timeout: 2000
info: [debug] Cleaning app data files
warn: Applications directory /Users/me/Library/Developer/CoreSimulator/Devices/DB3378BA-5ACB-45C3-A61B-571223EC85C2/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/me/Library/Developer/CoreSimulator/Devices/DB3378BA-5ACB-45C3-A61B-571223EC85C2/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Cleaning up appium session

**Comment by jwallis** [comment]
I just realized that I'm getting different errors on different attempts to repro.  With the same config as above I also get the trace below.  I have to believe they're related:


info: --> GET /wd/hub/session/8fe681a5-8428-4534-9822-108848f233c9/source {}
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()
info: [debug] [INST] 2015-09-17 20:01:54 +0000 Debug: Got new command 51 from instruments: au.mainApp().getTreeForXML()
info: [debug] [INST] 2015-09-17 20:01:54 +0000 Debug: evaluating au.mainApp().getTreeForXML()
info: [debug] [INST] 2015-09-17 20:02:06 +0000 Fail: The target application appears to have died
info: [debug] [INST STDERR] 2015-09-17 15:02:06.364 instruments[28048:996493] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST] 2015-09-17 20:02:06 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-09-17 20:02:06 +0000 Debug: responding with:alid":true,"visible":true,"hint":null,"path":"/0/0","x":0,"y":0,"width":375,"height":667},">":[]}},{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/1","x":0,"y":0.6875,"width":375,"height":665.625},">":[{"UIAButton":{"@":{"name":"Cancel","label":"Cancel","value":null,"dom":null,"enabled":true,"vali

...

info: [debug] [INST] 2015-09-17 20:02:06 +0000 Debug: Running system command #52: /usr/local/Cellar/node/0.12.7_1/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"my_app","label":"my_app","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":...
info: [debug] Socket data being routed.
info: [debug] Got null result from instruments
error: Couldn't parse result buffer: SyntaxError: Unexpected end of input
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"\"Error parsing socket data from instruments\""},"sessionId":"8fe681a5-8428-4534-9822-108848f233c9"}
info: <-- GET /wd/hub/session/8fe681a5-8428-4534-9822-108848f233c9/source 500 11979.853 ms - 215 
info: [debug] [INST] Instruments Trace Complete (Duration : 263.628479s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator
info: [debug] Cleaning sim data files
info: node-simctl: Executing: xcrun with args: simctl erase DB3378BA-5ACB-45C3-A61B-571223EC85C2 and timeout: 2000
info: [debug] Cleaning app data files
warn: Applications directory /Users/me/Library/Developer/CoreSimulator/Devices/DB3378BA-5ACB-45C3-A61B-571223EC85C2/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/me/Library/Developer/CoreSimulator/Devices/DB3378BA-5ACB-45C3-A61B-571223EC85C2/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Cleaning up appium session

**Comment by SrinivasanTarget** [comment]
@imurchie has handled this error recently.Please do reopen with latest logs incase if you hit the same.Thanks.

**Comment by SrinivasanTarget** [comment]
@triager please close
