### ISSUE TITLE
Can't create an instance of AppiumDriver/AndroidDriver

### ISSUE THREAD

**Issue by MiquelMittertreiner** [appium/appium#5320]
Hi,

My problem occures when creating an instance of the AndroidDriver/AppiumDriver.
At my work, we have an application where we use Selenium to automate our webbased tests.
By that I mean the product we have, which are multiple asp.net websites, we use selenium to automate all the testing. We are now trying to implement Appium also, so we can automate the testing on mobile devices. Is it even possible to use Appium outside of a TestClass? Since I did manage to get it to work inside testclasses. See my code below.

        Dim dsCapabilities As DesiredCapabilities = New DesiredCapabilities
        Dim objDriver As AndroidDriver(Of IWebElement)
        objDriver = New AndroidDriver(New Uri(""), dsCapabilities)

This code gives the following error:

![image](https://cloud.githubusercontent.com/assets/7239136/8448706/d5516f66-1fca-11e5-8941-1edbcb98277b.png)

It doesn't really matter which parameters I provide to the AndroidDriver, as it will always give an error.

![image](https://cloud.githubusercontent.com/assets/7239136/8448721/ef27366e-1fca-11e5-93d1-8cf48ae5b6ec.png)

The same pretty much goes when trying to create an instance of the AppiumDriver itself.

![image](https://cloud.githubusercontent.com/assets/7239136/8448748/20f1b1e2-1fcb-11e5-8c00-6db42e805b9a.png)

Help would be really appreciated.

**Comment by Jonahss** [comment]
Ah! You need to use the (java-client)[https://github.com/appium/java-client]
It has the classes that you need :)
