### ISSUE TITLE
How to quickly verify if a host is appium-setup?

### ISSUE THREAD

**Issue by binodpanta** [appium/appium#5325]
How do we scriptify the check that a host has Appium setup done, without actually trying to run appium and encountering/checking for the dialog or other situations?

**Comment by Jonahss** [comment]
run `node bin/appium-doctor.js` it checks the setup of dependencies and stuff :)

**Comment by binodpanta** [comment]
Thanks, does this script just check that appium can be used, or that appium setup has actually been completed (as per the doc instructions) ? I was looking for the latter if possible

**Comment by Jonahss** [comment]
The script actually looks for all the dependencies to make sure they are installed. And it checks your environment variables too. Try it out.

If you think it needs more, please open an issue on https://github.com/appium/appium-doctor
