### ISSUE TITLE
Can't find elements on iOS 8.3

### ISSUE THREAD

**Issue by raafe** [appium/appium#5334]
Hi,

There is a problem with finding elements on iOS 8.3.
if I use iOS 8.1.3 (iPhone 5), the following statement works fine:
"assert self._driver.find_element_by_name('Door test door was closed').is_displayed()"
I am able to find such an element.

But when I use another phone (iPhone 5S) with iOS 8.3, the problem with finding element occurs. It is visible in Appium inspector but the element could not be found.  It is also impossible to find it using in Appium Inspector the locator value "Door test door was closed" and the locator strategy "name". (Screenshot attached)

I use the same application and environment. Only the iOS paltform version is changed. I have not found any similar issue online. The problem concerns only few elements. Most of them I can find successfully.

Have you got any idea what could be the reason?

Environment:
Appium v1.4.7
node v0.12.5
Xcode 6.4

![zrzut ekranu 2015-07-02 o 10 47 07](https://cloud.githubusercontent.com/assets/6593318/8473363/584b6f50-20a9-11e5-83a7-5e00365420b5.png)

**Comment by Jonahss** [comment]
Hm. I'm not aware of what changed between those versions, but iOS is known for changing their underlying hierarchy between versions.
This is what to do: For each version, print out the results of `driver.source()` (or `getSource()` or whatever is used in the language you are using). You can then view those in an xml viewer and discover what's changing :)

report back here with your findings!

**Comment by lukemasterman** [comment]
I have this same issue, it appears to be with using the iPhone 5s in particular, whilst I initially thought it was an issue between OS versions, it would appear that some static text fields don't appear in the xml for the iPhone 5s. I initially noticed this when my tests were performing on an 8.1 iPhone 6 but getting a no element error on the iPhone 5s on 8.3, I attempted to do the same thing on an iPhone 5s on 8.1 and still had the same issue, whilst on the iPhone 6 on 8.3 the static text labels still appear which led me to presume this is an iPhone 5s issue rather than due to the OS.

**Comment by raafe** [comment]
I have checked it on iPhone 6 with 8.3 iOS and still the same problem occurs. Even after update iPhone 5s to 8.4 nothing has changed. I can not see some elements. I've checked the xml source and there is visible the problem with "q door was closed" static text:
- iPhone 5s, iOS 8.3:
```
                <UIATableCell name="q
door was closed" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/2" x="0" y="140" width="320" height="70">
                    <UIAStaticText name="q
door was closed" label="q
door was closed" value="q
door was closed" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/2/0" x="60" y="140" width="195" height="60">
                    </UIAStaticText>
                    <UIAStaticText name="06.07.15" label="06.07.15" value="06.07.15" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/2/1" x="257.5" y="172" width="42.5" height="11">
                    </UIAStaticText>
                    <UIAStaticText name="09:05" label="09:05" value="09:05" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/2/2" x="270" y="159" width="30" height="11">
                    </UIAStaticText>
                </UIATableCell>
```
- iPhone 5, iOS 8.1.3:
```
                <UIATableCell name="q door was closed" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/2" x="0" y="140" width="320" height="70">
                    <UIAStaticText name="q door was closed" label="q door was closed" value="q door was closed" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/2/0" x="60" y="140" width="195" height="60">
                    </UIAStaticText>
                    <UIAStaticText name="06.07.15" label="06.07.15" value="06.07.15" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/2/1" x="257.5" y="172" width="42.5" height="11">
                    </UIAStaticText>
                    <UIAStaticText name="09:05" label="09:05" value="09:05" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/2/2" x="270" y="159" width="30" height="11">
                    </UIAStaticText>
                </UIATableCell>
```
is any way to handle it?

**Comment by khallbec** [comment]
I noticed this and thought it was my selenium version. maybe I just changed my iPhone version. If I have time next week I'll try it. but till then I'm busy.

**Comment by Jonahss** [comment]
@raafe Wait so what's the difference in those two xml snippets? Is there a weird whitespace character in the string which creates a newline in one version of iOS and not the other? Is there some tricky unicode whitespace in the string?

**Comment by Jonahss** [comment]
That would explain why it can't be found. We match elements based on the string, and maybe one string has unicode whitespace and the other doesn't.

**Comment by raafe** [comment]
There is added additional 'enter', so it seems to be issue with architecture of iOS 8.3 and higher. I have found workaround by adding '\n' into search string.

Thanks for help

**Comment by Jonahss** [comment]
Yeah that's a nasty hidden bug. Thanks for finding it!
Maybe post to discuss.appium.io in case other people have the same issue?
