### ISSUE TITLE
1.4.6 Appium Unable to find webview 

### ISSUE THREAD

**Issue by vbhojaraja** [appium/appium#5336]
Latest version of appium throws an  error unable to find webview after launching the safarilauncher app eventhough   ios_webkit_debug_proxy  has been started.

**Comment by Jonahss** [comment]
By "latest version" you mean 1.4.7?
Can you post the logs please? You're on a real device, right?

**Comment by Jonahss** [comment]
I'm running the safari tests fine on my real device. Can you post a specific test that would break for me?

Are you using xcode 6.3.2?

**Comment by vbhojaraja** [comment]
i was trying this on appium version 1.4.6 though, today did install the latest version 1.4.7 but unable to find the Safarilauncher folder in the build. I did install appium through NPM. I will post the logs shortly,

I am using the xcode version 6.2

**Comment by vbhojaraja** [comment]
error: Failed to start an Appium session, err was: Error: ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'
info: [debug] Error: ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'
    at Error (native)

**Comment by Jonahss** [comment]
You need to run the `reset.sh` script with the `--real-safari` flag.
Can you clone this repo and build from source?

**Comment by Jonahss** [comment]
Can you upgrade to xcode 6.4?

**Comment by vbhojaraja** [comment]
There is an error when i try to run ./reset.sh  --real-safari --verbose

"fatal: Not a git repository (or any of the parent directories): .git"


above message is displayed.

**Comment by Jonahss** [comment]
did you clone this repository?

**Comment by vbhojaraja** [comment]
i downloaded the zip file and extracted it on my system.

**Comment by vbhojaraja** [comment]
Hi Jonah, 
Below are the list of steps i performed today.
1.) Opened the Safarilauncher.xcode project from /node_modules/Safarilauncher folder and installed the app on my device.
2.) Generated Safarilauncher.zip from /Users/Testing/Library/Developer/Xcode/DerivedData/SafariLauncher-dftbmktkgdjnjmbtnsgcbbifmohx/Build/Products/Debug-iphoneos/SafariLauncher.app
using the command zip -r SafariLauncher.zip SafariLauncher.app
3.) Copied the generated zip file to the build/Safarilauncher folder.
4.) Started the appium session from the bin folder using the command
node appium.js -U 8113fe2d04e6d16492eb41dd1ab54893bc1200f4 --app /Users/Testing/Library/Developer/Xcode/DerivedData/SafariLauncher-dftbmktkgdjnjmbtnsgcbbifmohx/Build/Products/Debug-iphoneos/SafariLauncher.app
5.) started the ios webkit debug proxy in bin folder using the command 
node ios-webkit-debug-proxy-launcher.js -c 8113fe2d04e6d16492eb41dd1ab54893bc1200f4:27753

below are the capabilities which i am passing

String my_SafariLauncher="/Users/Testing/Library/Developer/Xcode/DerivedData/SafariLauncher-dftbmktkgdjnjmbtnsgcbbifmohx/Build/Products/Debug-iphoneos/SafariLauncher.app";
                                                caps.setCapability(MobileCapabilityType.PLATFORM_VERSION, "8.2");
                                                caps.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");
                                                caps.setCapability(MobileCapabilityType.DEVICE_NAME,"iPod");
                                                caps.setCapability("automationName", "Appium");
                                                caps.setCapability("udid", "8113fe2d04e6d16492eb41dd1ab54893bc1200f4");
                                                   //caps.setCapability("app", "io.appium.SafariLauncher");
                                               caps.setCapability("app", my_SafariLauncher);
                                                //caps.setCapability("app", "safari");
                                    caps.setCapability("SafariAllowPopups", true);
                                    caps.setCapability("safariIgnoreFraudWarning", true);
                                    caps.setCapability("bundleId", "io.appium.SafariLauncher");
                                   //caps.setCapability("bundleId", "SafariLauncher");
                                    caps.setCapability("autoWebview", "true");
                                    caps.setCapability("autoAcceptAlerts", "true");

when i executed the test case it launched the safarilauncher app installed on the device but couldnt go any further after that and below error was displayed.

warn: Could not find any webviews yet, refreshing/retrying
info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not navigate to webview; there aren't any!
info: [debug] Error: Could not navigate to webview; there aren't any!
    at [object Object].<anonymous> (/Users/Testing/Downloads/appium-1.4.7/lib/devices/ios/ios.js:1685:14)
    at [object Object].<anonymous> (/Users/Testing/Downloads/appium-1.4.7/lib/devices/ios/ios.js:1574:5)
    at [object Object].<anonymous> (/Users/Testing/Downloads/appium-1.4.7/lib/devices/ios/ios.js:1551:5)
    at [object Object].<anonymous> (/Users/Testing/Downloads/appium-1.4.7/lib/devices/ios/ios-hybrid.js:69:5)
    at [object Object].<anonymous> (/Users/Testing/Downloads/appium-1.4.7/lib/devices/ios/webkit-remote-debugger.js:92:5)
    at /Users/Testing/Downloads/appium-1.4.7/node_modules/underscore/underscore.js:890:21
    at IncomingMessage.<anonymous> (/Users/Testing/Downloads/appium-1.4.7/lib/devices/ios/webkit-remote-debugger.js:105:7)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not navigate to webview; there aren't any!)","origValue":"Could not navigate to webview; there aren't any!"},"sessionId":null}
info: <-- POST /wd/hub/session 500 110423.008 ms - 218

**Comment by Jonahss** [comment]
And this is with appium version 1.4.7?

**Comment by vbhojaraja** [comment]
yes it is version 1.4.7

**Comment by vbhojaraja** [comment]
I even tried using the standalone ios_webkit_debug_proxy but no luck
Any suggestions?

**Comment by Jonahss** [comment]
Um. I think what you should do is:
1. clone the appium github repository
2. run `./reset.sh --ios`
3. run `./reset.sh --ios --real-safari`
4. start appium server and ios_webkit_debug_proxy
5. run your test with desired capability `browserName: safari` and no `app` capability.

**Comment by vbhojaraja** [comment]
ok let me give it a try.... how do you want the ios_webkit_debug_proxy to be started?

**Comment by Jonahss** [comment]
using the helper script provided: `./bin/ios-webkit-debug-proxy-launcher.js -c [your_device_UDID]:27753 -d`

**Comment by vbhojaraja** [comment]
@Jonah :  now i am able to run the automated test case successfully for IOS devices, but when i connect a android device it throws an error saying Chrome device not configured.

**Comment by Jonahss** [comment]
Can you make a separate issue for that? thanks.
