### ISSUE TITLE
iOS findByXpath doesn't support ids

### ISSUE THREAD

**Issue by aluedeke** [appium/appium#5337]
Hey,

as far as i can see it is not possible to select elements in ios by xpath which contains an id (an key from a translation file). 

Some time ago i wrote a small client side extension for the java client which replaced an xpath like that:

```
//UIAButton[@name='{{my.key}}']
```

to

```
//UIAButton[@name='{{My Translated text for my.key}}']
```

That worked in that particular project pretty well. Would like to get some feedback if a server side solution like that would be accepted?

@jlipps @bootstraponline what do you think?

**Comment by bootstraponline** [comment]
I have a similar fix in the Ruby bindings. A resolve_id method is used to
do the conversion client side. I agree it's useful.

**Comment by Jonahss** [comment]
Hm. So your proposal is that the id matching would happen inside appium or the app? That could be very useful.

What does @jlipps think?

**Comment by jlipps** [comment]
Appium has access to these strings through a Localization.plist or something?

**Comment by Jonahss** [comment]
Yeah.

**Comment by bootstraponline** [comment]
and strings.xml for android

**Comment by aluedeke** [comment]
For android i don't see the need yet. In android if i use the Selendroid or UIAutomator (>4.3) backend i can reference the id directly as attributes in the xml. for iOS this isn't possible.

**Comment by bootstraponline** [comment]
There are a few use cases on Android. appium supports uiautomator < API 18 (4.3) so that's one. Another is scrolling to text. You can't reference the id since the element isn't on screen yet, so you have to resolve the id first then scroll to that text.

**Comment by jlipps** [comment]
:+1:

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
