### ISSUE TITLE
Constant loading of TableView cells

### ISSUE THREAD

**Issue by sergejjkim** [appium/appium#5338]
Hi,

I'm using Appium 1.4, Java bindings 3.0, iOS 8.2 iPhone emulator. 
In my app I have a TableView that auto-uploads cells whenever the first cell or the last cell is visible. However when I run my appium test, each interaction of AppiumDriver with that TableView cells causes cell loadings. i.e. when I do driver.findElement() i can observe the app start to load new cells. Is there a way to avoid it? Thanks.

**Comment by Jonahss** [comment]
Ooh wow. Thanks for the detailed question.

Until now, we've never been aware that such a behavior happens. It sounds like this might be built right into how apple Instruments and UIAutomation functions.

The way to test this would be to write a small test script and run it through Instruments within Xcode. If the refreshing happens there (using the uiautomation api), then there's nothing we can do about it. But if you don't detect the reloading happening there, we could figure out which part of our code causes the reload to happen.

**Comment by sergejjkim** [comment]
hi Jonahss,

so i tried to do the similar test with apple ui automation. And it seems to be that loading happens there too.

**Comment by Jonahss** [comment]
Yeah, in that case it seems there's nothing we can do :(

You can log a bug with apple.
