### ISSUE TITLE
Appium not actually interact with password text field in Google login

### ISSUE THREAD

**Issue by NikitaMD** [appium/appium#5339]
I'm facing issue with Google+ login. Inside app we have Google+ as one of option to login. Appium able to enter text in email field, click enter. Than I see in appium log 200 return for password field and Sign in button, while appium doesnt actually click on them.

Here is code:

this is ok:
            self.driver.find_element(By.XPATH,\
                '//android.widget.EditText[1]').\
                    send_keys(config.Credential['googlelogin'])
            self.driver.find_element(By.XPATH,\
                '//android.widget.Button[@content-desc="Next"]').click()

            wait_for_element_visible(self.driver, By.XPATH,\
                '//android.widget.Button[@content-desc="Sign in"]')

here is appium should enter password, while nothing happens actually
            self.driver.find_element(By.XPATH,\
                '//android.widget.EditText[@password="true"]').\
                    send_keys(config.Credential['googlepasswd'])

            self.driver.find_element(By.XPATH,\
                '//android.widget.Button[@content-desc="Sign in"]').click()

After I have some more thing to wait and it fails, becouse script actually on the password enter page.

Here is appium log:
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element {"using":"xpath","sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","value":"//android.widget.Image[@content-desc=\"Google\"]"}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element 200 1797.052 ms - 87 {"status":0,"value":{"ELEMENT":"7"},"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19"}
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element {"using":"xpath","sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","value":"//android.widget.EditText[1]"}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element 200 522.381 ms - 87 {"status":0,"value":{"ELEMENT":"8"},"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19"}
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element/8/value {"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","id":"8","value":["s","e***"m"]}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element/8/value 200 9342.317 ms - 76 {"status":0,"value":true,"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19"}
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element {"using":"xpath","sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","value":"//android.widget.Button[@content-desc=\"Next\"]"}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element 200 1666.428 ms - 87 {"status":0,"value":{"ELEMENT":"9"},"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19"}
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element/9/click {"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","id":"9"}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element/9/click 200 279.185 ms - 76 {"status":0,"value":true,"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19"}
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element {"using":"xpath","sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","value":"//android.widget.Button[@content-desc=\"Sign in\"]"}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element 200 1990.915 ms - 88 {"status":0,"value":{"ELEMENT":"10"},"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19"}
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element {"using":"xpath","sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","value":"//android.widget.EditText[1]"}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element 200 1561.446 ms - 88 {"status":0,"value":{"ELEMENT":"11"},"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19"}
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element/11/value {"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","id":"11","value":["n","*****"1","$"]}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element/11/value 200 7194.310 ms - 76 {"status":0,"value":true,"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19"}
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element {"using":"xpath","sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","value":"//android.widget.EditText[@password=\"true\"]"}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element 200 82.388 ms - 88 {"status":0,"value":{"ELEMENT":"12"},"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19"}
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element/12/value {"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","id":"12","value":["n"*****"$"]}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element/12/value 200 6179.008 ms - 76 {"status":0,"value":true,"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19"}
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element {"using":"xpath","sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","value":"//android.widget.Button[@content-desc=\"Sign in\"]"}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element 200 60.355 ms - 88 {"status":0,"value":{"ELEMENT":"13"},"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19"}
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element/13/click {"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","id":"13"}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element/13/click 200 3202.113 ms - 76 {"status":0,"value":true,"sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19"}
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element {"using":"name","sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","value":"Accept"}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element 500 134.007 ms - 195 
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element {"using":"name","sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","value":"Accept"}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element 500 134.569 ms - 195 
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element {"using":"name","sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","value":"Accept"}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element 500 74.567 ms - 195 
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element {"using":"name","sessionId":"0224876d-f905-4be7-87cc-6279a3d5bc19","value":"Accept"}
info: <-- POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element 500 168.790 ms - 195 
info: --> POST /wd/hub/session/0224876d-f905-4be7-87cc-6279a3d5bc19/element

**Comment by Jonahss** [comment]
Hmm. Is this on a real device or an emulator? What version of android?
It could be that they have some sort of protection on @password fields. We've had trouble in the past getting the value of a password text field.

**Comment by NikitaMD** [comment]
@Jonahss This is real Nexus 6 with 5.1

**Comment by NikitaMD** [comment]
Seems like this issue not exist with Android 5.1

**Comment by Jonahss** [comment]
Yay!
Not sure there's really anything we can do then. Seems like an Android UIAutomator issue.
