### ISSUE TITLE
appium installation process

### ISSUE THREAD

**Issue by sushkad** [appium/appium#5343]
npm ERR! tar.unpack untar error /home/sushant/.npm/appium/1.4.7/package.tgz
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v0.10.25
npm ERR! npm  v2.12.1
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, mkdir '/usr/lib/node_modules'
npm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/lib/node_modules',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/lib/node_modules/appium',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v0.10.25
npm ERR! npm  v2.12.1
npm ERR! path npm-debug.log.41567c1185b4e0a8ff88f04279f1cea6
npm ERR! code EACCES
npm ERR! errno 3

npm ERR! Error: EACCES, open 'npm-debug.log.41567c1185b4e0a8ff88f04279f1cea6'
npm ERR!  { [Error: EACCES, open 'npm-debug.log.41567c1185b4e0a8ff88f04279f1cea6']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: 'npm-debug.log.41567c1185b4e0a8ff88f04279f1cea6' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

but still i got an error...mention above

i installled 
npm  v2.12.1
node v0.10.25
appium v1.4.7

how can i solve this issue?

**Comment by Jonahss** [comment]
First of all, please install node version 0.12 or above. Appium no longer supports version 0.10.

Secondly: you are trying to install appium globally for your user, but `/usr/lib/node_modules` does not have the correct permissions set. As stated in the log, you could install using `sudo`. Instead, I suggest install node using [nvm](https://github.com/creationix/nvm) which will install node in a place where a non-root user can access the necessary directories.

**Comment by sushkad** [comment]
i   Installed npm  -v       2.11.2
                  node -v       0.12.6
                  appium -v   1.4.7

 so how to i test Hybrid Cordova app using appium in Ubuntu ?
and  how appium show the Error like Performance testing related?

**Comment by Jonahss** [comment]
Could you ask question in the forum? discuss.appium.io
Also take a look at our documentation on appium.io
