### ISSUE TITLE
Xcode 6.4? Investigate

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#5347]
A user has reported that Instruments is crashing for them on Xcode 6.4

Has anyone else experienced this? I will install it and investigate today.

**Comment by Jonahss** [comment]
Hm. Tests are running fine for me...

**Comment by penguinho** [comment]
Might have to do with the OS he is using, maybe he is on El Capitan or Mavericks or something unusual

**Comment by rahuljawale** [comment]
I see the crashes with Xcode 6.4 with assetsd process (or daemon). I will get back with logs.

**Comment by Jonahss** [comment]
Can you post some of the logs from the crashes? Are these a special sort of test? Are you using Yosemite?

**Comment by SrinivasanTarget** [comment]
@triager please close
