### ISSUE TITLE
install appium error

### ISSUE THREAD

**Issue by lengyao88** [appium/appium#5349]
Last login: Tue Jul  7 23:11:49 on ttys001
zrydeMacBook-Pro:~ zry$ npm install appium
 
> udidetect@1.0.7 install /Users/zry/node_modules/appium/node_modules/udidetect
> make

gcc -o udidetect -framework CoreFoundation -framework MobileDevice -F/System/Library/PrivateFrameworks udidetect.c
 
> utf-8-validate@1.1.0 install /Users/zry/node_modules/appium/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.6","npm":"2.12.1"})
 
> bufferutil@1.1.0 install /Users/zry/node_modules/appium/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
 
> ws@0.5.0 install /Users/zry/node_modules/appium/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
 
> ws@0.4.31 install /Users/zry/node_modules/appium/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
 
> appium-chromedriver@2.1.3 install /Users/zry/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

info Chromedriver Install Opening temp file to write chromedriver_mac32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.15/chromedriver_mac32.zip 

...
RequestError: Error: connect ETIMEDOUT
    at new RequestError (/Users/zry/node_modules/appium/node_modules/appium-chromedriver/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/Users/zry/node_modules/appium/node_modules/appium-chromedriver/node_modules/request-promise/lib/rp.js:50:34)
    at self.callback (/Users/zry/node_modules/appium/node_modules/appium-chromedriver/node_modules/request/request.js:197:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/Users/zry/node_modules/appium/node_modules/appium-chromedriver/node_modules/request/request.js:854:8)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.12.1"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.12.1"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.12.1"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.12.1"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.12.1"})
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "appium"
npm ERR! node v0.12.6
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.1.3 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.1.3 install script 'node install-npm.js'.
npm ERR! This is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zry/npm-debug.log

**Comment by rahuljawale** [comment]
+1. Seeing same issue on Mac OS X 10.10.3 .

**Comment by juanpicado** [comment]
-1 I can build appium without issues, 10.9.5 and 10.10, maybe a temporary issue in the hosting of chromedriver (https://github.com/appium/appium-chromedriver/blob/master/lib/install.js#L15)
![screen shot 2015-07-11 at 11 58 20](https://cloud.githubusercontent.com/assets/558752/8633360/2b9f41d0-27c4-11e5-80c1-efc6469f131f.png)

**Comment by rahuljawale** [comment]
What version of iOS SDK are you using? I am on iOS 8.4

**Comment by juanpicado** [comment]
I think if you are trying to install appium, you don't need any sdk to do that. Just node.js. Anyway, I tried in Maverick (default xcode) and Yosemite (without xcode).

The issue is ```RequestError: Error: connect ETIMEDOUT``` as far I understood.

**Comment by rahuljawale** [comment]
It ended up being proxy issue. Our mac minis are behind corporate proxy.

The issue was that that npm was using http_proxy environment variable and for some reason it was trying to split the value by : (colon). So the reason why I was seeing error Invalid Protocol (when the proxy was set) and ELIFECYCLE (when the proxy was not set).

Incorrect value for http_proxy was `servername.domain.com:80 `
which had to be changed to `http://servername.domain.com:80`

**Comment by Jonahss** [comment]
Ah. Nice catch.
