### ISSUE TITLE
Cannot interact with second app via Appium (multi app scenario) 

### ISSUE THREAD

**Issue by kpanwar** [appium/appium#5350]
Hello,

I have the following setup where I have 2 appium servers running on my OS X and I create 2 drivers (one for each app). I start app B first and then I start app A and this results in app B getting backgrounded.
Code to set up the app is

	public void setup() throws MalformedURLException
    {
	DesiredCapabilities cap = this.initializeApplication("appB.app");
        this.authenticatorDriver = new IOSDriver(new URL("http://127.0.0.1:4724/wd/hub"), cap);
        this.authenticatorApp = new Authenticator(this.authenticatorDriver);
        cap = this.initializeApplication("appA.app");
        this.clientDriver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), cap);
        this.clientApp = new ClientApplication(this.clientDriver);
    }

    public DesiredCapabilities initializeApplication(String applicationPath) throws MalformedURLException
    {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "8.3");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone Simulator");
        capabilities.setCapability(MobileCapabilityType.APP, applicationPath);
        
        return capabilities;
    }

    public void testEndtoEnd() throws MalformedURLException
    {
    	clientApp.clickEndToEnd();
    	authenticatorApp.addUser();
    }

I am able to interact with app A controls that invokes app B, but when I try to interact with app B, appium times out with the error that the element was not found. Is there any workaround to this or any special method that sets the app to foreground or something?

additional logs from the problem app.

appium --port 4724 --no-reset --device-name "iPhone 6" --plaorm-name iOS --platform-version "8.3" --browser-name iOS
warn: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
info: Welcome to Appium v1.4.7 (REV 3b1a3b3ddffa1b74ce39015a7a6d46a55028e32c)
info: Appium REST http interface listener started on 0.0.0.0:4724
info: [debug] Non-default server args: {"port":4724,"noReset":true,"deviceName":"iPhone 6","platformName":"iOS","platformVersion":"8.3","browserName":"iOS"}
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/<username>/Library/Developer/Xcode/DerivedData/ADAB-bvcelnfdafckoahgsnmzojpxkneo/Build/Products/Debug-iphonesimulator/MyApp.app","platformVersion":"8.3","deviceName":"iPhone Simulator","platformName":"iOS","browserName":""}}
info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
info: [debug] Using local app from desired caps: /Users/<username>/Library/Developer/Xcode/DerivedData/ADAB-bvcelnfdafckoahgsnmzojpxkneo/Build/Products/Debug-iphonesimulator/MyApp.app
info: [debug] Creating new appium session 9b88836c-8e6b-4f5b-b450-705cb558d097
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version
info: [debug] Xcode version set to 6.3.2
info: [debug] Setting iOS SDK Version
info: [debug] iOS SDK Version set to 8.3
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"6.3.2","iOSSDKVersion":"8.3","deviceName":"iPhone Simulator","platformVersion":"8.3"}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone Simulator (8.3 Simulator)" to: "iPhone 6 (8.3 Simulator)"
info: [debug] Final device string is: 'iPhone 6 (8.3 Simulator)'
info: [debug] iOS sim UDID is 7689DE02-FD7C-4D3C-B89B-8792DF5B7AB8
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim

**Comment by Jonahss** [comment]
You're in unexplored territory here. Pretty sure what you are asking for is not possible, since Apple instruments only runs on the foreground app, and only one app at a time. But if you experiment, who knows what undocumented things you can do.

But from what I know, what you're asking for has never been done before, and I'm not sure if Instruments was build to run on more than one process at a time on the phone. Hm.......

Please tell us what results you get if you find a way to get this to work :)
