### ISSUE TITLE
error: Failed to start an Appium session, err was: Error: Instruments crashed on startup

### ISSUE THREAD

**Issue by sharat1000** [appium/appium#5351]
Getting this error : not able to resolve any help would be great, i am new to appium, i tried searching blogs but couldn't find a soution, my app is not getting launched by Appium

Steps followed:
1. Build my app code using Xcode by selecting my phone as target
2. My App got Installed and got launched on phone by Xcode after the build was successful
3. Went to settings of my iPhone and under Developer option - i enabled "Enable UI Automation"
4.  Now i launched Appium and gave the below settings and clicked on Launch
![screen shot 2015-07-08 at 4 05 37 pm](https://cloud.githubusercontent.com/assets/13235647/8568505/c5ac4de4-258b-11e5-889b-be1f2da16e57.png)
5. Clicked on Inspector and gives following popup error 
Could not start a new session

Be sure the Appium server is running with an application opened by using the "App Path" parameter in Appium.app (along with package and activity for Android) or by connecting with selenium client and supplying this in the desired capabilities object.

Tools Used -
Appium - 1.4.0 
Xcode - 6.3.2
OSX 10.9.5
Iphone 5

Logs of my appium run - 
info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: <-- GET /wd/hub/status 200 9.285 ms - 104 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: <-- GET /wd/hub/status 200 4.441 ms - 104 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: --> GET /wd/hub/sessions {}

info: [debug] Responding to client with success: {"status":0,"value":[]}

info: <-- GET /wd/hub/sessions 200 1.117 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.3","newCommandTimeout":"999999","automationName":"Appium","deviceName":"Sharat's iPhone"}}

info: Client User-Agent string: Appium (unknown version) CFNetwork/673.6 Darwin/13.4.0 (x86_64) (MacBookPro8%2C1)

info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***

info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] Using local app from command line: /Users/sutla/Library/Developer/Xcode/DerivedData/AppCenter-cojltwmfldjhdreqcbjnpkzhaqdy/Build/Products/Debug-iphoneos/AppCenter.app
info: [debug] Creating new appium session 67f0afee-1ec7-4f76-bcb5-a2151f0ec75e
info: [debug] Removing any remaining instruments sockets

info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Getting bundle ID from app

info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments

info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/sutla/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/sutla/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js
info: [debug] Reusing dynamic bootstrap: /Users/sutla/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js
info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog

info: [debug] Creating iDevice object with udid f0b7871ab20db2f7db32e3c65cdcb09942e6f47a

info: [debug] App is installed.

info: [debug] fullReset not requested. No need to install.
info: [debug] Starting command proxy.

info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: Launching instruments

info: [debug] Attempting to run app on real device with UDID f0b7871ab20db2f7db32e3c65cdcb09942e6f47a
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w f0b7871ab20db2f7db32e3c65cdcb09942e6f47a com.deloitteresources.appcentral -e UIASCRIPT "/Users/sutla/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2015-07-08 15:52:06.316 instruments[15388:5303] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [debug] [INST STDERR] 2015-07-08 15:52:06.476 instruments[15388:507] -[NSOperationQueue setQualityOfService:]: unrecognized selector sent to instance 0x7fc165533510

info: [debug] [INST STDERR] Instruments Trace Error : -[NSOperationQueue setQualityOfService:]: unrecognized selector sent to instance 0x7fc165533510

info: [debug] [INSTSERVER] Instruments exited with code 0

info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:04 Sharats-iPhone syslog_relay[167] <Notice>: syslog_relay found the ASL prompt. Starting...

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:06 Sharats-iPhone DTMobileIS[182] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:06 Sharats-iPhone DTMobileIS[182] <Warning>: Could not create service named com.apple.instruments.server.services.launchdaemon

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:06 Sharats-iPhone notification_proxy[166] <Error>: 0x503000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:06 Sharats-iPhone notification_proxy[166] <Error>: 0x585000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

info: Launching instruments

info: [debug] Attempting to run app on real device with UDID f0b7871ab20db2f7db32e3c65cdcb09942e6f47a

info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w f0b7871ab20db2f7db32e3c65cdcb09942e6f47a com.deloitteresources.appcentral -e UIASCRIPT "/Users/sutla/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2015-07-08 15:52:18.058 instruments[15395:2307] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [debug] [INST STDERR] 2015-07-08 15:52:18.216 instruments[15395:507] -[NSOperationQueue setQualityOfService:]: unrecognized selector sent to instance 0x7fc6d27427b0

info: [debug] [INST STDERR] Instruments Trace Error : -[NSOperationQueue setQualityOfService:]: unrecognized selector sent to instance 0x7fc6d27427b0

info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #3
info: [debug] Killall iOS Simulator
info: [IOS_SYSLOG_ROW ] Jul  8 15:52:18 Sharats-iPhone DTMobileIS[182] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
info: [IOS_SYSLOG_ROW ] Jul  8 15:52:18 Sharats-iPhone DTMobileIS[182] <Warning>: Could not create service named com.apple.instruments.server.services.launchdaemon

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:18 Sharats-iPhone notification_proxy[166] <Error>: 0x481000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:18 Sharats-iPhone notification_proxy[166] <Error>: 0x585000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:21 Sharats-iPhone backboardd[57] <Notice>: MultitouchHID: detection mode: 255->6 (deferring until bootloaded)

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:21 Sharats-iPhone SpringBoard[43] <Warning>: [MPUSystemMediaControls] Enabling lock screen media controls updates for screen turning on.
info: [IOS_SYSLOG_ROW ] Jul  8 15:52:21 Sharats-iPhone SpringBoard[43] <Warning>: [MPUSystemMediaControls] Updating supported commands for now playing application.

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:21 Sharats-iPhone sharingd[25] <Notice>: 15:52:21.074 : BTLE scanning started
info: [IOS_SYSLOG_ROW ] Jul  8 15:52:21 Sharats-iPhone sharingd[25] <Notice>: 15:52:21.075 : Scanning mode Contacts Only
info: [IOS_SYSLOG_ROW ] Jul  8 15:52:21 Sharats-iPhone sharingd[25] <Notice>: 15:52:21.084 : BTLE scanner Powered On

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:21 Sharats-iPhone backboardd[57] <Notice>: MultitouchHID: device bootloaded

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:21 Sharats-iPhone backboardd[57] <Notice>: MultitouchHID: detection mode: 6->6

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:22 Sharats-iPhone kernel[0] <Notice>: AppleAP3GDL::handleInterrupt2 FIFO is Empty

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:22 Sharats-iPhone backboardd[57] <Notice>: MultitouchHID: detection mode: 6->3

info: [IOS_SYSLOG_ROW ] Jul  8 15:52:22 Sharats-iPhone locationd[64] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0

info: Launching instruments

info: [debug] Attempting to run app on real device with UDID f0b7871ab20db2f7db32e3c65cdcb09942e6f47a

info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w f0b7871ab20db2f7db32e3c65cdcb09942e6f47a com.deloitteresources.appcentral -e UIASCRIPT "/Users/sutla/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2015-07-08 15:52:23.979 instruments[15398:1307] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [debug] [INST STDERR] 2015-07-08 15:52:24.130 instruments[15398:507] -[NSOperationQueue setQualityOfService:]: unrecognized selector sent to instance 0x7fe6cd4ab8d0

info: [debug] [INST STDERR] Instruments Trace Error : -[NSOperationQueue setQualityOfService:]: unrecognized selector sent to instance 0x7fe6cd4ab8d0

info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator

info: [debug] On a real device; cannot clean device state

info: [debug] Cleaning up appium session

info: [debug] Error: Instruments crashed on startup
    at [object Object].Instruments.onInstrumentsExit (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:440:31)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:353:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments crashed on startup)","origValue":"Instruments crashed on startup"},"sessionId":null}

error: Failed to start an Appium session, err was: Error: Instruments crashed on startup

info: <-- POST /wd/hub/session 500 20767.930 ms - 182

**Comment by Jonahss** [comment]
Hm, looks like instruments it crashing. This *might* be related to your operating system being 10.9 rather than 10.10 ??

Not much we can do if instruments is crashing. You can try to eliminate some possiblities by running an Automation test straight from xcode. Run your app in Xcode using the Automation trace template and see if it will work.

**Comment by TamirSagiGimso** [comment]
Hello ,
I Had exactly the same problem.
I solved it by enabling UI Automation under developer tools and it worked like magic.

Setting->Developer->Enable UI Automation

cheers

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by anand853** [comment]
can you please let me know which 'Setting->Developer->Enable UI Automation' you are talking about?
is it for Xcode ?

**Comment by juhlila** [comment]
@anand853 its on iphone config

**Comment by NasserMahmoud1** [comment]
@anand853 on Appium click on the wrench and the screwdriver logo(developer settings) , and click on enabled , and it will work like charm
