### ISSUE TITLE
CRITICAL - please fix ,its there since  appium lib5.0.1 

### ISSUE THREAD

**Issue by srikanthsadhu** [appium/appium#5352]
/.rvm/gems/ruby-2.1.2/gems/appium_lib-7.0.0/lib/appium_lib/device/device.rb:5:in `<module:Device>': uninitialized constant Appium::Device::Forwardable (NameError)

I go away with this by updating my local file to have the import, it would be nice if you could check in the fix in git.

**Comment by Jonahss** [comment]
Would you be willing/able to submit a pull request to the appium_lib repository?
https://github.com/appium/ruby_lib

**Comment by Jonahss** [comment]
Closing since this is unrelated to appium server itself, but thank you for bringing it to our attention.
