### ISSUE TITLE
Not able to locate element using XPath 

### ISSUE THREAD

**Issue by abatgit** [appium/appium#5354]
Hi,

We are working on iOS automation. But currently we are stuck with locating element and performing any action on that.

Element = driver.findElementByXPath("//UIAApplication[1]/UIAWindow[5]/UIAActionSheet[1]/UIACollectionView[1]/UIACollectionCell[1]");

We are trying to locate element using above xpath but it comes with following error:

info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
error: Error getting source, can't continue finding element by XPath
info: [debug] Condition unmet after 2ms. Timing out.
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Bad response from getTreeForXML. Err was undefined and res was undefined)","origValue":"Bad response from getTreeForXML. Err was undefined and res was undefined"},"sessionId":"7e2b1967-def2-4bad-b9d0-7b7f89e280f8"}

We have one class where we have defined all page elements based on xpath and accessing it in our test execution class.

**Comment by abatgit** [comment]
Got it fixed :)

Thanks,

**Comment by ShankarGargXebia** [comment]
I am able to reproduce this issue on 1.4.13. Earlier on 1.4.8, it used to work fine. any solution for this?
