### ISSUE TITLE
Interact with push notification toast when app is in background or device is locked

### ISSUE THREAD

**Issue by nish-i** [appium/appium#5355]
Hello,

I am trying to automate a scenario which involves interacting with a push notification in iOS devices- specifically the toast message which is displayed when the app is closed/in background or on the lock screen. 

After a bit of experimentation I found that both the lock and background call are blocking calls, so I cannot interact with the toast message. Also I am not able to do the same when the app is closed. 
Is there any way to automate this scenario for iOS devices.

**Comment by Jonahss** [comment]
We haven't found any way to test or automate push notification on iOS. Apple hasn't provided any way to interact with them :(

Perhaps in the future, with Apple devoting more to testing with XCUITest, they will add it. But for now, nothing we can do.

Only possible workaround is to take screenshots of the device and then use image-recognition to see the notification. You can *probably* use touch actions to hit particular screen coordinates over them. Can't interact with the lock screen at all though.

**Comment by sumitp-optimus** [comment]
Any update on testing push notifications on iOS ??
