### ISSUE TITLE
Android Webview sendkeys not working when input width not an integer

### ISSUE THREAD

**Issue by firemoon** [appium/appium#5356]
Hello,

I found a problem when i execute sendkeys in the webview context on Android device.
The input attribute width in my form is not an integer (but a float). When i set the width to 300px and the sendkeys works fine. (Version 1.4.0 (Draco))

![capture d ecran 2015-07-09 a 10 51 25](https://cloud.githubusercontent.com/assets/3878314/8591492/f2b87680-2628-11e5-89e3-1ac0a1a96996.png)

capabilities : 

```
    capabilities.setCapability("device", "Android");
    capabilities.setCapability("appium-version", "1.0");
    capabilities.setCapability("platformName", "Android");
    capabilities.setCapability("platformVersion", "5.1");
    capabilities.setCapability(CapabilityType.BROWSER_NAME, "");
    capabilities.setCapability(CapabilityType.PLATFORM, Platform.MAC);
    capabilities.setCapability("automationName", "Selendroid");
```

example :

```
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("username")));
    WebElement username = driver.findElement(By.id("username"));
    username.sendKeys("test@test.com"); // not working
```

I hope you can fix this problem.

Thank you

**Comment by Jonahss** [comment]
I will try to reproduce this in a test, and then we can work on fixing it :)

**Comment by imurchie** [comment]
Can you provide the Appium server log for a run of the test? 

And to be clear, in the HTML for the page loaded in the webview, you have an input tag like

```html
<input id="text_field" name="name" type="text" width="100.50px"/>
```

**Comment by imurchie** [comment]
Also, what happens when you use `automationName='Appium'` instead of `Selendroid`?

**Comment by firemoon** [comment]
Hello,

this is the log from Appium server : 

info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/15c02f7a-2284-77b0-3b88-4d413655a7f9/element","method":"POST","json":{"using":"id","value":"username"}}
info: [debug] Proxied response received with status 200: {"sessionId":"15c02f7a-2284-77b0-3b88-4d413655a7f9","status":0,"value":{"ELEMENT":":wdc:1437139194493"}}
info: <-- POST /wd/hub/session/15c02f7a-2284-77b0-3b88-4d413655a7f9/element 200 450.089 ms - 104 
info: --> POST /wd/hub/session/15c02f7a-2284-77b0-3b88-4d413655a7f9/element/%3Awdc%3A1437139194493/value {"id":":wdc:1437139194493","value":["test@test.com"]}
info: [debug] Setting text on element ':wdc:1437139194493': 'test@test.com'
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/15c02f7a-2284-77b0-3b88-4d413655a7f9/element/:wdc:1437139194493/value","method":"POST","json":{"value":["test@test.com"]}}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"15c02f7a-2284-77b0-3b88-4d413655a7f9"}
info: <-- POST /wd/hub/session/15c02f7a-2284-77b0-3b88-4d413655a7f9/element/%3Awdc%3A1437139194493/value 200 463.892 ms - 74 {"status":0,"value":"","sessionId":"15c02f7a-2284-77b0-3b88-4d413655a7f9"}
info: --> DELETE /wd/hub/session/15c02f7a-2284-77b0-3b88-4d413655a7f9 {}
info: Shutting down appium session
info: [debug] Stopping selendroid server

Yes the input tag is like you write

I try to use AppiumDriver but the webivew context is not available.

I hope this can help you.

**Comment by imurchie** [comment]
For Appium mode to work, the webview [needs to be in "debug" mode](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/hybrid.md#automating-hybrid-android-apps). This is a Android UI Automator necessity, unfortunately.

**Comment by imurchie** [comment]
I hope you are able to provide more information that will help reproduce this. I can't get it to happen locally.

I can't think of a reason this should be happening. Can you do anything else with the element in the case where you can't type? Get the size? Location? I'm just wondering if it is found and interactable at all.

Things that might be relevant: real device or emulator? Details of the device?

**Comment by firemoon** [comment]
I use a real device (Nexus6 : 5.1.1 / Nexus5 : 5.2).
