### ISSUE TITLE
how to check whether appium session is already in progress or not?

### ISSUE THREAD

**Issue by ayosuva** [appium/appium#5358]
how to check whether appium session is already in progress or not (Java)? if it is in progress how to reuse the same session once again?

**Comment by Jonahss** [comment]
Ok so.
Yes you can check to see if there already exists a session on the server. if you send a request to `/wd/hub/sessions` it will respond with a list of sessions running on the server, along with their desired capabilities.

You can then take the session ID from that list, and set that session ID on your client. Now your client is connected to that session and you can continue sending commands.

Here's the bad news: there's no command in the java client to send a request to the `/sessions` endpoint! :(   I talked to the selenium developers on IRC and they claim that the method only concerns selenium grid, so the java client shouldn't include it :(

I'm ok with adding the method to java-client though ^.^ If you want to look at that repository and submit a pull request to add it, it would be great. Or I can see if I have time to add it today.

(clients in other languages, like wd.js in javascript already have the `sessions` function).

**Comment by ayosuva** [comment]
How can i submit a pull request to add it?

**Comment by Jonahss** [comment]
@ayosuva check out the github repo for the java client: github.com/appium/java-client

If you explore that library, it imports the selenium java-client and extends it with appium methods. Find the list of commands, (search for similar commands, you will see how they are organized) and add the necessary call to `/wd/hub/sessions`.

You will need to create a java class to handle the information returned in that call. It should return an array of session objects. Take a look at https://github.com/SeleniumHQ/selenium/blob/01399fffecd5a20af6f31aed6cb0043c9c5cde65/java/server/src/org/openqa/selenium/remote/server/handler/GetAllSessions.java for inspiration.

**Comment by reach2jeyan** [comment]
I tried to hit the url while the appium session is in progress but I get a different result

This is my code
```def listentoappium

  uri = URI('http://0.0.0.0:4723/wd/hub/status')

  Net::HTTP.start(uri.host, uri.port,
                  :verify_mode => OpenSSL::SSL::VERIFY_NONE) do |http|
    request = Net::HTTP::Get.new uri.request_uri
    response = http.request request
    response.each do |respond|
      puts respond
    end

  end
end```

This is the result i get instead of the session details

```access-control-allow-origin
access-control-allow-methods
access-control-allow-headers
content-type
content-length
etag
date
connection```

**Comment by reach2jeyan** [comment]
Okay so when I use `curl http://0.0.0.0:4724/wd/hub/status` I get the result as `{"status":0,"value":{"build":{"version":"1.7.0","revision":null}},"sessionId":null`

**Comment by KazuCocoa** [comment]
The status spec is https://github.com/appium/appium/blob/master/docs/en/commands/status.md
You can get session id like https://github.com/appium/ruby_lib_core/blob/0ba7b1c726f02e11d6daa46481309b1e0e54b00e/lib/appium_lib_core/driver.rb#L168-L174 and probably it is your expected one.

**Comment by reach2jeyan** [comment]
```@driver.remote_status
remote_status```

This should have all the desired capabilities set for the `@driver` right? I am writing a standalone script where I just want to hit the running servers. Would this work without setting the desired capability

**Comment by KazuCocoa** [comment]
No, the command, `/wd/hub/status`, gets `build.version` and `build.revision` in server side as described in https://github.com/appium/appium/blob/master/docs/en/commands/status.md#response .

Do you expect https://github.com/appium/appium/blob/master/docs/en/commands/session/get.md ?
The command should get current session's capability.

**Comment by reach2jeyan** [comment]
Thanks! 

These aren't terminal command line ones I beleive? Do I need to define anything for @driver and session_capabilities?

**Comment by KazuCocoa** [comment]
I've checked more. The command isn't available in W3C.
The bridge command isn't accessible from OSS as well. (SeleniumDriver side)

If you'd like to get current session id, you can get `@driver.session_id`.
If you'd like to get current capability, you can get `@driver.capabilities`.

**Comment by reach2jeyan** [comment]
Thanks @KazuCocoa ! I'll try this and keep you posted
