### ISSUE TITLE
Getting Click On View Inside WindowManager Android

### ISSUE THREAD

**Issue by naumanafzaal** [appium/appium#5360]
I have a view added inside WindowManager and I want to get click on that view. Is there any way I can find that view?

I have used appium inspector to perform precise tap on that view and it works perfectly fine. But when I use same coordinates using AndroidDriver tap function it is not getting click.
This is what I am doing on AndroidDriver wd.tap(1, 969, 371, 500);  but it is not working.

Please help me in this regard. Thanks

**Comment by Jonahss** [comment]
Can you post the logs?
Have you tried the "NativeWebTap" desired capability?

**Comment by naumanafzaal** [comment]
Thanks Jonahss. 
I will paste logs shortly. Will "NativeWebTap" work on native android app? I didnt find this field in API reference?

**Comment by naumanafzaal** [comment]
This is the command generated from appium inspector 

wd.executeScript("mobile: tap", new HashMap<String, Double>() {{ put("tapCount", 1.0); put("touchCount", 1.0); put("duration", 0.5); put("x", 993.0); put("y", 360.0); }});

Here is my code, it runs successfully before wd.tap(1, 993, 360, 1); command 

wd.findElement(By.xpath("//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2]")).click();
		wd.findElement(By.xpath("//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.support.v4.view.ViewPager[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2]")).click();
		wd.tap(1, 993, 360, 1);
		wd.findElement(By.xpath("//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2]")).click();
		wd.findElement(By.xpath("//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]")).click();

Here are the logs 

After the tap command I am getting this error "Could not find an element using supplied strategy." because it was not able to find next element.


info: --> POST /wd/hub/session/64c1934d-f39f-4845-90ad-1a56b49d0210/touch/perform {"actions":[{"action":"press","options":{"x":1040,"y":330}},{"action":"wait","options":{"ms":1}},{"action":"release","options":{}}]}
info: [debug] Pushing command to appium work queue: ["element:touchDown",{"x":1040,"y":330}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchDown","params":{"x":1040,"y":330}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchDown
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1920]
info: [debug] [BOOTSTRAP] [debug] Performing TouchDown using element? false x: 1040, y: 330
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Pushing command to appium work queue: ["element:touchUp",{"x":1040,"y":330}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchUp","params":{"x":1040,"y":330}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchUp
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1920]
info: [debug] [BOOTSTRAP] [debug] Performing TouchUp using element? false x: 1040, y: 330
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"64c1934d-f39f-4845-90ad-1a56b49d0210"}
info: <-- POST /wd/hub/session/64c1934d-f39f-4845-90ad-1a56b49d0210/touch/perform 200 33.553 ms - 76 {"status":0,"value":true,"sessionId":"64c1934d-f39f-4845-90ad-1a56b49d0210"}
info: --> POST /wd/hub/session/64c1934d-f39f-4845-90ad-1a56b49d0210/element {"using":"xpath","value":"//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2]"}
info: [debug] Waiting up to 60000ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"xpath","selector":"//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2]","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2]","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding //android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2] using XPATH with the contextId:  multiple: false

info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Could not find an element using supplied strategy. ","status":7}

info: [debug] Waited for 137ms so far

info: [debug] Pushing command to appium work queue: ["find",{"strategy":"xpath","selector":"//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2]","context":"","multiple":false}]

info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2]","context":"","multiple":false}}

info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding //android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2] using XPATH with the contextId:  multiple: false

info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Could not find an element using supplied strategy. ","status":7}
info: [debug] Waited for 750ms so far

info: [debug] Pushing command to appium work queue: ["find",{"strategy":"xpath","selector":"//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2]","context":"","multiple":false}]

info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2]","context":"","multiple":false}}

info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding //android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[2] using XPATH with the contextId:  multiple: false

info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Could not find an element using supplied strategy. ","status":7}
info: [debug] Waited for 1420ms so far

**Comment by Jonahss** [comment]
In the log I see this
`[{"action":"press","options":{"x":1040,"y":330}}`
Those are not the same coordinates that your script has. Are you sure the right thing is happening?

**Comment by naumanafzaal** [comment]
Yes I changed them myself. Log were taken when x, y was 1040,330.  This is not the issue. 

Using appium inspector it is working perfectly with both values.

**Comment by Jonahss** [comment]
Hm. So in the logs, the tap seems to work fine. Do you have a way of checking to make sure if it got tapped in the right place? You can enable some debugging options that will show a little circle wherever the app gets tapped.

**Comment by naumanafzaal** [comment]
Yeah that would be quite helpful can you please let me know how to enable debugging?

**Comment by Jonahss** [comment]
I think it's a setting under Developer options.

**Comment by SrinivasanTarget** [comment]
@triager please close
