### ISSUE TITLE
Appium + Jenkins Integration.

### ISSUE THREAD

**Issue by qaDream77** [appium/appium#5363]
I have a windows 7 machine running jenkins to schedule python appium mobile test scripts.

The batch script is simple, starts appium as a background process.

Start /B appium
sleep 60
pybot test.robot

If i start appium locally then i just do pybot test.robot and have no issues but i need to start and stop the server with the job. Yet i get an error

Original error: 'java -version' failed. Error: spawn ENOENT)","origValue":"'java -version' failed. Error: spawn ENOENT

Console Output
-------------------------------------------------------------------
C:\Program Files (x86)\Jenkins\jobs\_ Android Smart Campus test\workspace>Start /B appium 

C:\Program Files (x86)\Jenkins\jobs\_ Android Smart Campus test\workspace>sleep 30 

[33mwarn[39m: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
[36minfo[39m: Welcome to Appium v1.4.0 (REV 8f63e2f91ef7907aed8bda763f4e5ca08e86970a)
[36minfo[39m: Appium REST http interface listener started on 0.0.0.0:4723
[36minfo[39m: Console LogLevel: debug

C:\Program Files (x86)\Jenkins\jobs\_ Android Smart Campus test\workspace>pybot -v usr:goran.sarenkapa -v pwd:Alpha123 -v local:1 "C:\Users\Goran\Documents\Robot Framework Mobile Test Scripts\Android\Android Smart Campus.robot" 

==============================================================================
Android Smart Campus :: Verify all apps are available                         
==============================================================================
Smart Campus Login                                                    [36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"deviceName":"192.168.56.101:5555","app":"C:\\Users\\Goran\\Documents\\Robot Framework Mobile Test Scripts\\Android/demoapp/Ryersonmobile.apk","appWaitPackage":"ca.ryerson.Ryersonmobile","platformVersion":"4.2.2","platformName":"Android","automationName":"appium"}}[39m
[36minfo[39m: Client User-Agent string: Python-urllib/2.7
[31merror[39m: Failed to start an Appium session, err was: Error: 'java -version' failed. Error: spawn ENOENT
[36minfo[39m: [debug] No appActivity desired capability or server param. Parsing from apk.
[36minfo[39m: [debug] No appPackage desired capability or server param. Parsing from apk.
[36minfo[39m: [debug] Using local app from desired caps: C:\Users\Goran\Documents\Robot Framework Mobile Test Scripts\Android\demoapp\Ryersonmobile.apk
[36minfo[39m: [debug] Creating new appium session ed2588b2-39ca-4696-b347-91626ec5e797
[36minfo[39m: Starting android appium
[36minfo[39m: [debug] Getting Java version
[36minfo[39m: [debug] Cleaning up android objects
[36minfo[39m: [debug] Cleaning up appium session
[36minfo[39m: [debug] Error: 'java -version' failed. Error: spawn ENOENT
    at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-common.js:1057:17)
    at exithandler (child_process.js:633:7)
    at ChildProcess.errorhandler (child_process.js:649:5)
    at ChildProcess.EventEmitter.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:795:12)
[36minfo[39m: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: 'java -version' failed. Error: spawn ENOENT)","origValue":"'java -version' failed. Error: spawn ENOENT"},"sessionId":null}
[36minfo[39m: [37m<-- POST /wd/hub/session [39m[31m500[39m[90m 17.746 ms - 208[39m [90m[39m
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No application is open
| FAIL |
Setup failed:
WebDriverException: Message: A new session could not be created. (Original error: 'java -version' failed. Error: spawn ENOENT)

Also teardown failed:
Several failures occurred:

1) No application is open

2) No application is open

3) No application is open
------------------------------------------------------------------------------
Android Smart Campus :: Verify all apps are available                 | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  C:\Program Files (x86)\Jenkins\jobs\_ Android Smart Campus test\workspace\output.xml
Log:     C:\Program Files (x86)\Jenkins\jobs\_ Android Smart Campus test\workspace\log.html
Report:  C:\Program Files (x86)\Jenkins\jobs\_ Android Smart Campus test\workspace\report.html

Process leaked file descriptors. See http://wiki.jenkins-ci.org/display/JENKINS/Spawning+processes+from+build for more information
Build step 'Execute Windows batch command' marked build as failure

**Comment by Simon-Kaz** [comment]
This isn't a problem with appium but with your jenkins machine. 

Original error: 'java -version' failed. Error: spawn ENOENT)","origValue":"'java -version' failed. Error: spawn ENOENT

**Comment by qaDream77** [comment]
1st test
C:\Program Files (x86)\Jenkins\jobs\_ Android Smart Campus test\workspace>appium-doctor
[36mRunning Android Checks[39m
[32mâœ” [39m[37mANDROID_HOME is set to "C:\Users\Goran\AppData\Local\Android\sdk"[39m
[32mâœ” [39m[37mJAVA_HOME is set to "C:\Program Files\Java\jdk1.8.0_45."[39m
[32mâœ” [39m[37mADB exists at C:\Users\Goran\AppData\Local\Android\sdk\platform-tools\adb.exe[39m
[32mâœ” [39m[37mAndroid exists at C:\Users\Goran\AppData\Local\Android\sdk\tools\android.bat[39m
[32mâœ” [39m[37mEmulator exists at C:\Users\Goran\AppData\Local\Android\sdk\tools\emulator.exe[39m
[32mâœ” [39m[37mAndroid Checks were successful.
[39m
[32mâœ” [39m[37mAll Checks were successful[39m
Finished: SUCCESS

2nd test
C:\Program Files (x86)\Jenkins\jobs\_ Android Smart Campus test\workspace>java -version 
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

C:\Program Files (x86)\Jenkins\jobs\_ Android Smart Campus test\workspace>exit 0 
Finished: SUCCESS

Sorry, i should have included these two tests as well, i had checked to make sure java was up and running beforehand. I have set this up on os x with no issues but on the windows machine with batch script starting appium and then running the test script it throws that java error.

**Comment by qaDream77** [comment]
Fixed, Jenkins doesn't like variables when specifying Path, can't use %SYSTEMROOT% as part of the environment variable setup even thought the batch console will return the proper result :(
