### ISSUE TITLE
deprecate newCommandTimeout in favor of idleTimeout

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#5364]
Sauce labs and selenium both use `idleTimeout` instead of `newCommandTimeout`. if you use `newCommandTimeout` on sauce, sauce still has it's own default `idleTimeout` of 90 sec.

To decrease confusion and increase consistency, let's add `idleTimeout` and slowly deprecate `newCommandTimeout`.

**Comment by SrinivasanTarget** [comment]
@scottdixon idleTimeout is deprecated and newCommandTimeout works fine as expected in new java client 3.4.0.Please close this.
