### ISSUE TITLE
No route for Se element `rect`

### ISSUE THREAD

**Issue by imurchie** [appium/appium#5369]
Selenium has an `element/rect` path for getting the size and position of an element (see the [spec draft](https://w3c.github.io/webdriver/webdriver-spec.html#get-element-rect)). Appium does not implement it at all. We need to either implement it fully, or at least respond that we don't implement it, since it is exposed by the standard clients.

``` shell
info: --> GET /wd/hub/session/0b66e6a6-ace9-4267-9fd4-235ff1f6428f/element/1/rect {}
info: [debug] Responding to client that we did not find a valid resource
info: <-- GET /wd/hub/session/0b66e6a6-ace9-4267-9fd4-235ff1f6428f/element/1/rect 404 16.370 ms - 47
```

Reported originally as appium/python-client#95

**Comment by HlebHalkouski** [comment]
@Jonahss any update? I found some documentation for [uiautomator](https://developer.android.com/reference/android/support/test/uiautomator/UiObject.html#getBounds()) and [UI Automation](https://developer.apple.com/library/ios/documentation/ToolsLanguages/Reference/UIAElementClassReference/index.html#//apple_ref/javascript/instm/UIAElement/rect)

**Comment by mykola-mokhnach** [comment]
this has been addressed recently.
