### ISSUE TITLE
Appium 1.4.6 iOS+Android, No application is open / session could not be created.

### ISSUE THREAD

**Issue by qaDream77** [appium/appium#5372]
After the application has been installed and launched, is there a function to test to see if the application is open/running/frozen?

A test result of session could not be created or no application is open is not useful when those imply infrastructure issues and not actual issues with the test script.

Thank you!

**Comment by Jonahss** [comment]
Hm. the best way to test if the application is running and the test is working is to call the `source()` command of your driver. It should return the hierarchy of elements currently on the device's UI. If the app crashed or the device froze, this command would fail.

Usually if the app crashes or the phone freezes, appium detects that something disconnected or went wrong and it ends the session.

I think the various clients could be improved, sending back more informative error messages, is that what your are asking for? It's something we'd like to do in the future and will be made much easier to implement in appium v1.5.

Does that answer your question?

P.S. You can hit the `/wd/hub/status` api endpoint of the appium server to see if a session is running, or if the server itself is healthy.

**Comment by qaDream77** [comment]
That helps a lot, thank you! I am currently writing a watch dog which goes through the log file for exactly that /wd/hub/status.

**Comment by Jonahss** [comment]
Cool
