### ISSUE TITLE
Request to add a method to check  the UI object exist or not exist

### ISSUE THREAD

**Issue by sas0807** [appium/appium#5373]

**Comment by Jonahss** [comment]
Hi,

To check if an element exists, you should just try to "find" it, using whatever method you use to find the element.

Are you asking for a method to check whether an element that you found earlier *still* exists? That's a method that *might* be possible, depending on the platform (android or ios).
For now, that's pretty complicated, but trying to "find" the element again is a good way to do this currently.

I'll add this as a feature request :)

**Comment by sas0807** [comment]
Hi,
Yes. When the script do a lot of operation,I want to know the operation whether success or failure as  a checkpoint;

Thank you!

**Comment by jlipps** [comment]
I think we should stick to simply finding the element to check whether it exists. If you try to interact with it and it doesn't exist, you'll get a specific exception explaining that the element is no longer able to be interacted with.
