### ISSUE TITLE
Appium inspector not working for MNCalendarView

### ISSUE THREAD

**Issue by nabeel-ibrahim** [appium/appium#5375]
I have a MNCalendarView that I am trying to inspect using the appium inspector. the inspector takes some time to load the page but after the loading is complete, i cannot inspect any of the elements. This only happens when I try to inspect a MNCalendarView. I am using appium 1.4.1 on Mac OS X

**Comment by Jonahss** [comment]
Could you please post this issue on the github repository for the inspector? This is the main appium command-line server repository.

Thank you :)
