### ISSUE TITLE
Pythonic way to start appium server 

### ISSUE THREAD

**Issue by Taitalus** [appium/appium#5378]
Hi, is there a pythonic way to start, kill and restart appium sever on different port in a machine??

**Comment by vinceis1337** [comment]
Depends on what OS. Do you mean like executing a command to start a server?

If you can get python to open an terminal you could execute a command to start an appium server.

More info: https://discuss.appium.io/t/starting-appium-server-programmatically-on-mac/1615

**Comment by imurchie** [comment]
Please query the discussion list.
