### ISSUE TITLE
AndroidDriver.currentActivity null pointer exception

### ISSUE THREAD

**Issue by nicolasavenza** [appium/appium#5379]
I'm getting some test failures due to a nullpointer exception inside the AndroidDriver when I call currentActivity(). This does not happen every time, most of the times the call works properly. I'm using the currentActivity call to verify whether the app crashed or is still running.

    java.lang.NullPointerException
	at io.appium.java_client.android.AndroidDriver.currentActivity(AndroidDriver.java:223)

Server log: 

    [36minfo[39m: [37m<-- GET /wd/hub/session/51f2fd4e-62c8-4fca-9ea3-56071b2b41ae/appium/device/current_activity [39m[32m200[39m[90m 159.526 ms - 76[39m [90m{"status":0,"value":null,"sessionId":"51f2fd4e-62c8-4fca-9ea3-56071b2b41ae"}[39m

**Comment by nicolasavenza** [comment]
This issue happens with Appium 1.4.7 on OSX 10.10.4

**Comment by sebv** [comment]
Looks like a java client bug, please report it there.

**Comment by nicolasavenza** [comment]
Submitted issue here: https://github.com/appium/java-client/issues/224

**Comment by nicolasavenza** [comment]
from https://github.com/appium/java-client/issues/224
> TikhomirovSergey commented on Aug 4
It is definitely the bug of the server, not client.

**Comment by TikhomirovSergey** [comment]
Here is the code which throws exception

https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidDriver.java#L288

>�[36minfo�[39m: �[37m<-- GET /wd/hub/session/51f2fd4e-62c8-4fca-9ea3-56071b2b41ae/appium/device/current_activity �[39m�[32m200�[39m�[90m 159.526 ms - 76�[39m �[90m{"status":0,"value":null,"sessionId":"51f2fd4e-62c8-4fca-9ea3-56071b2b41ae"}�[39m

The string above shows that NULL is returned with response from the server. 
I have two concerns:

- There is something wrong with Appium Android automation
- There is something wrong with Android SDK for MAC OS X

**Comment by SrinivasanTarget** [comment]
Works fine in latest version of client and server on API versions 19 to 23.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by gaffa** [comment]
I have:
- built server from current master
- used appium-java in 4.0.0
And still have the Problem that response.getValue() is null.

**Comment by SrinivasanTarget** [comment]
@gaffa Can you please open a new issue along with latest server logs as gist.Above info is not enough.
