### ISSUE TITLE
My Original error: AND Current:  is showing same activity still showing A new session could not be created.

### ISSUE THREAD

**Issue by shasaksingh** [appium/appium#5386]
A new session could not be created. (Original error: com.abc.iitglc/.ui.activity.MainActivity) never started. Current: com.abc.iitglc/.ui.activity.MainActivity) (WARNING: The server did not provide any stacktrace information)
capabilities.setCapability("appWaitPackage", "com.abc.iitglc");
capabilities.setCapability("appWaitActivity", ".ui.activity.MainActivity)");

Please help!!

**Comment by sebv** [comment]
Please provide full log in gist.
