### ISSUE TITLE
--log-timestamps is not giving correct time in the logs

### ISSUE THREAD

**Issue by naveenjammula** [appium/appium#5387]
I am using appium with python client to write automation for an application iOS (target devices are iPhone 5c and 6).

Issue: I am using "--log-timestamp" while starting the appium server. I can see logs now have date time concatenated in the beginning of each line. My issue is the date in datetime part of log is correct but i can see time is different.

I can see a time difference of about  5hr 32min. Do i need to set timezone somewhere ? is it a bug  or expected behaviour ?

My expectation is that the appium would be taking the system datetime as i am running appium server on a localhost.

From the time difference it looks like its taking GMT time by default I am in GMT +5:30 timeszone.

**Comment by beemi** [comment]
@naveenjammula  goodPoint did not realizes this

**Comment by sebv** [comment]
The GMT time is correct, I think there are some options to change that, please read the doc.

**Comment by beemi** [comment]
@sebv what is the option for BST??
