### ISSUE TITLE
Add a sendKeyStrategy Setting for Android

### ISSUE THREAD

**Issue by Simon-Kaz** [appium/appium#5393]
Right now, there are 2 options for sending keys:
- set capability sendKeyStrategy and be forced to use the same strategy across all tests
- don't set strategy and rely on one by one/grouped strategy ( https://github.com/appium/appium-uiauto/blob/master/uiauto/lib/element-patch/helper-patch.js#L24 )

I'd like to suggest an enhancement for the sendKeys method - being able to pass a parameter that would specify which strategy we want to use to enter the text, through a public interface maybe?

``` java
public interface SendKeyStrategy {
  String SET_VALUE = "setValue";
  String ONE_BY_ONE = "oneByOne";
  String GROUPED = "grouped"
}
```

And in java it'd look like this:

``` java
driver.sendKeys(SendKeyStrategy.SET_VALUE, "string to send");
```

We already follow similar approach with hideKeyboard - you can either not pass a parameter or select one of two strategies:

``` java
driver.hideKeyboard(HideKeyboardStrategy.PRESS_KEY, "Done");
public interface HideKeyboardStrategy {

  String TAP_OUTSIDE = "tapOutside";
  String PRESS_KEY = "pressKey";
}
```

Below is a real use case example (the ticket i logged in java-client repo):
https://github.com/appium/java-client/issues/217

**Comment by Jonahss** [comment]
:+1: 
If we don't want to violate the JSON Wire Protocol by adding an optional parameter, we could also add it as a Setting (like android hierarchy compression), which can be changed mid-test.

@jlipps what do you think?

**Comment by Simon-Kaz** [comment]
FYI, with help from @bootstraponline, i managed to switch the strategy in the middle of the test with: 

driver.executeScript("env.sendKeyStrategy = 'setValue'");

and

driver.executeScript("env.sendKeyStrategy = 'onebyone'");

It would definitely be better to do this via helper methods.

**Comment by Simon-Kaz** [comment]
As a temporary solution, i have created the following:

```java

   public enum sendKeyStrategy {
        SET_VALUE,
        ONE_BY_ONE,
        GROUPED
    }


public void setKeyboardStrategy(sendKeyStrategy strategy){
        switch(strategy) {
            case SET_VALUE: {
                driver.executeScript("env.sendKeyStrategy = 'setValue'");
            }
            case ONE_BY_ONE: {
                driver.executeScript("env.sendKeyStrategy = 'onebyone'");
            }
            case GROUPED: {
                driver.executeScript("env.sendKeyStrategy = 'grouped'");
            }
            default: {
                throw new IllegalArgumentException("Not a valid strategy: " + strategy);
            }
        }
    }

**Comment by jlipps** [comment]
i think it should be a setting too

**Comment by bootstraponline** [comment]
:+1: for a setting

**Comment by Jonahss** [comment]
@Simon-Kaz ok so a Setting it shall be. Want to have a chat some time and we can walk through the code for implementing this together?

**Comment by jervinjn** [comment]
Has this been implemented? If so, what is the Ruby equivalent? 
SendKeys is too slow. Please help.

**Comment by jlipps** [comment]
I'm going to close this since the sendKey strategy is only relevant for the old Instruments/UIAutomation driver which is no longer supported.

**Comment by chenry35** [comment]
Hello,

So there is no way to change the sendkey strategy for now?
