### ISSUE TITLE
Running Adb shell query

### ISSUE THREAD

**Issue by Taitalus** [appium/appium#5397]
Hi, is there anyway so that I can run adb shell command in appium server?

like this.. to know the state if a telephone rings then we can know it by running adb shell command

```
adb shell dumpsys telephony.registry|grep "mCallState"
```

```
adb shell dumpsys telephony.registry|findstr "mCallState"
```

I don't know how to catch the notification by webdriver when an incoming call comes.. any solutions?

**Comment by lomis2002** [comment]
To wait for incoming call on Android, following code should work in your test 

    public boolean isCallOngoing() {
        try {
            if (driver.currentActivity().equals("com.android.incallui.InCallActivity")) {
                return true;
            }
        } catch (Exception e) {
            return false;
        }
        return false;
    }

**Comment by Taitalus** [comment]
@lomis2002 thanks I will try this out. Though I figure it out by adb shell. I will try it out with appium next.
