### ISSUE TITLE
Use --no-window-animation flag when running Instrumentation (ex: selendroid)

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5400]
Google's Espresso project has documented how to disable window animations to improve stability. There's a separate appium issue [tracking that work](https://github.com/appium/appium/issues/3868).

Today I discovered that the `adb shell am instrument` accepts a `--no-window-animation` flag. This should be used by default where supported. I expect older devices to not support the flag.

**Comment by rompic** [comment]
any updates on this?

**Comment by bootstraponline** [comment]
appium's uiautomator v1 isn't using instrumentation so it'll only be applicable to the new uiautomator v2 driver (no ETA). In terms of getting this fixed for selendroid, someone just has to send a patch. I think it'd be a one line change.

**Comment by rompic** [comment]
does this mean it doesn't make sense to deactivate animations when using the default appium driver or is it still recommded? (couldn't find anything in the docs)

**Comment by bootstraponline** [comment]
It's still recommended. Animations cause flakiness.

**Comment by ukostas** [comment]
hi, ticket is closed and I did not get it, what is there any solution to disabling animation in place? thanks.

**Comment by bootstraponline** [comment]
https://github.com/linkedin/test-butler is what I've been using. Appium doesn't integrate with it though.

**Comment by ukostas** [comment]
Hi @bootstraponline , thanks for prompt response . I thought there is this an option "--no-window-animation" for " adb am instrument" and it was a plan to include this option when running uiautomator2 server apk. something like 
`am instrument --no-window-animation -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner`
But I could not follow what happen to this idea or may be I got it totally wrong. I will go check other related appium issues.

**Comment by bootstraponline** [comment]
I don't think it was ever implemented. The appium devs moved on to an espresso based driver.

**Comment by ukostas** [comment]
yeah, I found this project , but it is still "experimental". and uiautomator2 is currently most stable as per my knowledge.
@rkavalap , may be you can shed a light why this ticket was closed, is there any plan to implement this or we should wait for espresso driver ? 
thanks a lot

**Comment by jlipps** [comment]
I'll reopen. We don't support Selendroid any more but we do support the UiAutomator2 driver and it sounds like this could fruitfully be added there.

**Comment by imurchie** [comment]
Can you give https://github.com/appium/appium-uiautomator2-driver/pull/94 a try?

**Comment by ukostas** [comment]
cool, I can check it on my machine if needed, but I can't figure out how can I install appium-uiautomator2-driver locally from pull request.

**Comment by imurchie** [comment]
Yeah, that would be a pain.

If you upgrade the beta you will get `appium-uiautomator2-driver@0.6.0`, which has the change.

**Comment by ukostas** [comment]
Thanks! I will check and update here.

**Comment by ukostas** [comment]
hi, I have good news! I have updated to appium 1.7.0-beta, it includes `appium-uiautomator2-driver@0.6.0`. I see changes from appium log. But unfortunately this does not work, I still see animation. But then I found some old [source code](https://android.googlesource.com/platform/frameworks/base/+/android-4.4.2_r2/cmds/am/src/com/android/commands/am/Am.java), I edited appium-uiautomator2-driver code to run command like 
`cmd = 'am instrument -w --no-window-animation ' + INSTRUMENTATION_TARGET;` 
and it worked! to sum it up: looks like "<TEST_PACKAGE>/<RUNNER_CLASS>" should be last part of command line. @imurchie , could you please make changes ?

**Comment by imurchie** [comment]
0.6.1 ought to fix this. Sorry!

**Comment by ukostas** [comment]
hi! works OK now, no animation as expected and speeds up test execution a bit, tested on real device. I think this issue can be closed now. Thanks a lot !

**Comment by mykola-mokhnach** [comment]
Closing the issue as fixed. The new capability name is **disableWindowAnimation**
