### ISSUE TITLE
com.apple.instruments.server.services.wireless errors after one session

### ISSUE THREAD

**Issue by Triqqo** [appium/appium#5403]
I'm basically having two related issues with Appium and the com.apple.instruments.server.services.wireless service.

The first one being that whenever I run a single test in Safari on an iPhone 5S with iOS 7.1, the following error is thrown infinitely, or until Appium kills instruments:

```
2015-07-17 08:16:36:462 - info: [debug] [INST STDERR] 2015-07-17 10:16:36.461 instruments[3830:115176] Connection peer refused channel request for "com.apple.instruments.server.services.wireless"; channel canceled <DTXChannel: 0x7ff271ebdd80>
```

The error causes significant slowdown in test execution, or sometimes causes a session to not close properly. This brings be to the following related issue:
Whenever Selenium Grid terminates a session due to a timeout, if Appium is still hanging on this instruments error, the session never closes in Appium. The only way to close the session is to completely restart the Appium server for this device.

I've got the following setup:
- OS X 10.10.4
- Selenium Grid 2.46
- Appium 1.4.8 (tried 1.4.7 as well)
- Xcode 6.4
- iPhone 5S running iOS 7.1.2 

I haven't tried a newer iOS version on the same machine yet, but I want to use this machine exclusively for testing on iOS 7. I did try running an older version of XCode (5.1.1), but this didn't make a difference.

I'm using Protractor 2.1.0 to run the tests.

**Update:** Just tried an iPad with iOS 8.1.1, which doesn't encounter either issue. No instruments error and the session closes properly if something during the session hangs for whatever reason. It must be related to either iOS 7.1.2, or this specific iPhone. Any ideas?

**Comment by sebv** [comment]
Looks like it is spending time trying to connect to the wireless service, in one case it fails, on the other case it fails, sounds like device specific, but there is not enough information for us to investigate further.

**Comment by Triqqo** [comment]
Alright, what other information do you need?

**Comment by WendyWangbbg** [comment]
I fixed the problem after quitting the Instrument window...

**Comment by elango842003** [comment]
How do i close instrument window ? can you tell me elaborate ?
I am having this same issue .
