### ISSUE TITLE
[IOS] Errors when interacting with elements in WebView

### ISSUE THREAD

**Issue by ktronic80** [appium/appium#5404]
Appium 1.4.8/1.3.7
Appium Java Client 3.1.0
iOS 8.4 Simulator
Mac OS 10.10.4

Hi,

I'm trying to automate an App which has content in a webview. All works fine switching to webview context, finding the elements by id or css selector until I try to interact with an html element. The content in the webview is a form with some input fields a button. When I try to enter some text in an input field I get this error 
undefined is not an object (evaluating '(C(a)?xb(C(a)):window).getComputedStyle(a,null).MozTransform.match') (WARNING: The server did not provide any stacktrace information)

WebElement ele = driver.findElement(By.id("delivery-address-firstname"));
ele.sendKeys("Test");

Calling the click method on the button element throws a similar error but the submit method works.

I tried to set the capability nativeWebTap to true and false but it makes no difference.

Injecting JavaScript directly works:
js.executeScript("window.document.getElementById('delivery-address-firstname').value='Test");

I checked different methods of the WebElement class, most of them throw similar errors.
Here is a [log with some of the errors](https://gist.github.com/ktronic80/243fc0cc1feebeecc3b7)

[Here the Appium log with nativeWebTap=false.](https://gist.github.com/ktronic80/c92a2308ebd09e4d5b65)

[Here the Appium log with nativeWebTap=true.](https://gist.github.com/ktronic80/ea9b369e310bc8716431)

The HTML of the elements look like this
`<input id="delivery-address-firstname" maxlength="32" name="shippingAddress.firstName" required="required" type="text" value="" aria-required="true">`

`<button class="btn btn-std btn-next flr" data-elid="continue" name="send" type="submit" value="send" onclick="wt.sendinfo({linkId: 'checkout.next.address'});">
                                        Weiter
                                    </button>`

I also have an Android app which uses a webview with the same content there all works fine with Appium and Selendroid.

**Comment by sebv** [comment]
Try to use the `value` method instead of `text` for input fields.

**Comment by ktronic80** [comment]
Hi @sebv,

do you mean the type of the input element? I cannot change it the page is provided by another team and just displayed in the app.
I am just curious which kind webdriver is Appium using to interact with a webview?

**Comment by ktronic80** [comment]
Hi,
anything new on this issue?
I was not able to find a solution for this problem, yet. 
With iOS 9.0 one of the WebViews which has this problem in the app was replaced with SafariViewController and with it it works now. I can interact with web elements. Unfortunately for some technical reasons not all WebViews are replaced with SafariViewController.

**Comment by ktronic80** [comment]
I found a solution for this problem. I was using a debug build of the app when changed it to AddHoc build it worked.

**Comment by dmakhno** [comment]
@ktronic80, can you please explain how you've fixed this? I have the same issue now on aws device farm, using beta-channel for the app.
