### ISSUE TITLE
IOS Automation only : Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":""}

### ISSUE THREAD

**Issue by ankitbhatnagar4u** [appium/appium#5410]
I'm not able to click on the elements in my App when elements are identified By.name or ID or label. Appium is able to identify elements by xpath. It's not so that elements are not at all identified by appium. If I turn off my MAC machine (10.10.3) and run appium server and my project again, it identifies the elements example wd.findElements(By.name("Go")); for the first-second time but not after that. I'm attaching the logs as well as the logs that are coming while I'm recording and running the same.

Appium version used: 1.3.1(Ophiuchus)
Device(I Pad 2) and IOS version(7.1.1) 

@BeforeClass
    public static void init() throws Exception 
    {
        Date now = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("hh mm ss");
        String time = dateFormat.format(now);
        Screenshotpath = System.getProperty("user.dir").toString()+"/screenshot/test_"+time+"/";

```
     // set up appium
    File classpathRoot = new File(System.getProperty("user.dir"));
    File appDir = new File(classpathRoot.getAbsolutePath());
    File app = new File(appDir, IOSConfig.appName);

    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability("deviceName","iPad 2");
    capabilities.setCapability("platformName", "iOS");
    capabilities.setCapability("platformVersion", "7.1.1");
    capabilities.setCapability("app", app.getAbsolutePath());
    capabilities.setCapability("appPackage", "com.adobe.livecycle.ws");
    capabilities.setCapability("UDID", "ac5f348e57c8db28c5c0f4763ee32182bf9d0089");
    capabilities.setCapability("bundleId", "com.adobe.livecycle.Capture");
    capabilities.setCapability("device", "Stl-iPad");
    capabilities.setCapability(CapabilityType.PLATFORM, "MAC");
    driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
    settings = new SettingsScreen(driver);
    login = new IOSLoginScreen(driver);
    login.Login(IOSConfig.username, IOSConfig.password, IOSConfig.serverURL);

}
```

Also I'm giving the UDID if my device as well the the device(I Pad 2) and IOS version(7.1.1) while starting the appium server. There are no issues when I start Appium doctor. I'm not facing such issue with android automation.

info: --> POST /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/element {"using":"name","value":"Go"}

info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByName('Go')"
info: [debug] Sending command to instruments: au.getElementByName('Go')
info: [debug] [INST] 2015-07-21 13:18:36 +0000 Screenshot captured.
info: [debug] [INST] 2015-07-21 13:18:36 +0000 Debug: target.captureRectWithName("{origin:{x:0.00,y:0.00}, size:{height:0.00,width:0.00}}", "screenshote5b9f971-643b-4c8a-962b-819ff01e8b71")
info: [debug] [INST] 2015-07-21 13:18:36 +0000 Screenshot captured.
info: [debug] [INST] 2015-07-21 13:18:36 +0000 Debug: target.captureRectWithName("{origin:{x:0.00,y:0.00}, size:{height:0.00,width:0.00}}", "screenshote5b9f971-643b-4c8a-962b-819ff01e8b71")
info: [debug] [INST] 2015-07-21 13:18:36 +0000 Screenshot captured.
info: [debug] [INST] 2015-07-21 13:18:36 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-07-21 13:18:36 +0000 Debug: responding with:
info: [debug] [INST] 2015-07-21 13:18:36 +0000 Debug: Running system command #23: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] [INST] 2015-07-21 13:22:12 +0000 Debug: Got new command 23 from instruments: au.getElementByName('Go')
info: [debug] [INST] 2015-07-21 13:22:12 +0000 Debug: evaluating au.getElementByName('Go')
info: [debug] [INST] 2015-07-21 13:22:13 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-07-21 13:22:13 +0000 Debug: responding with:
info: [debug] [INST] 2015-07-21 13:22:13 +0000 Debug: Running system command #24: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Condition unmet after 587ms. Timing out.
info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":""},"sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}
info: <-- POST /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/element 500 587.493 ms - 179 

info: --> GET /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/source {}
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-07-21 13:22:14 +0000 Debug: Got new command 24 from instruments: au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-07-21 13:22:14 +0000 Debug: evaluating au.mainApp().getTreeForXML()

info: [IOS_SYSLOG_ROW ] Jul 21 18:52:14 Stl-iPad wifid[15] <Notice>: WiFi:[459177734.413038]:

info: [IOS_SYSLOG_ROW ] Jul 21 18:52:14 Stl-iPad wifid[15] <Notice>: Too frequent(4.538119 secs) rssi event from driver

info: [IOS_SYSLOG_ROW ] Jul 21 18:52:14 Stl-iPad wifid[15] <Notice>:

info: [debug] [INST] 2015-07-21 13:22:14 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-07-21 13:22:14 +0000 Debug: responding with::null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0","x":0,"y":0,"width":768,"height":1024},">":[{"UIAScrollView":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/0","x":0,"y":0,"width":768,"height":1024},">":[{"UIAWebView":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/0/0","x":0,"y":0,"width":768,"height":1024},">":[{"UIAStaticText":{"@":{"name":"User ID","label":"User ID","value":"","dom":{"id":""},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/0/0/0","x":20,"y":133,"width":45,"height":16},">":[]}},{"UIATextField":{"@":{"name":null,"label":null,"value":"user6","dom":{"id":"txtuser"},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/0/0/1","x":20,"y":154,"width":352,"height":39},">":[]}},{"UIAStaticText":{"@":{"name":"Password","label":"Password","value":"","dom":{"id":""},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/0/0/2","x":385,"y":133,"width":58,"height":16},">":[]}},{"UIASecureTextField":{"@":{"name":null,"label":null,"value":"••••••••","dom":{"id":"txtpwd"},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/0/0/3","x":385,"y":154,"width":356,"height":39},">":[]}},{"UIAStaticText":{"@":{"name":"Server URL","label":"Server URL","value":"","dom":{"id":""},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/0/0/4","x":20,"y":208,"width":68,"height":16},">":[]}},{"UIATextField":{"@":{"name":null,"label":null,"value":"http://10.42.86.243:8080","dom":{"id":"txtserver"},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/0/0/5","x":20,"y":229,"width":721,"height":39},">":[]}},{"UIAElement":{"@":{"name":null,"label":null,"value":"\n","dom":{"id":"serversDropDown"},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/0/0/6","x":720,"y":229,"width":25,"height":38},">":[]}},{"UIAButton":{"@":{"name":"Go","label":"Go","value":"","dom":{"id":"btnlogin"},"enabled":true,"valid":true,"visible":true,"hint":"","path":"/0/0/0/0/7","x":646,"y":288,"width":95,"height":40},">":[]}}]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/1","x":764.5,"y":0,"width":3.5,"height":1024},">":[]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/2","x":0,"y":1020.5,"width":768,"height":3.5},">":[]}}]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/1","x":0,"y":0,"width":768,"height":1024},">":[]}},{"UIAActivityIndicator":{"@":{"name":"In progress","label":"In progress","value":"1","dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/2","x":374,"y":502,"width":20,"height":20},">":[{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/2/0","x":374,"y":502,"width":20,"height":20},">":[]}}]}}]}},{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/1","x":0,"y":0,"width":768,"height":1024},">":[{"UIAStatusBar":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/1/0","x":0,"y":0,"width":768,"height":20},">":[{"UIAElement":{"@":{"name":"iPad","label":"iPad","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/0","x":6,"y":0,"width":25,"height":20},">":[]}},{"UIAElement":{"@":{"name":"3 of 3 Wi-Fi bars","label":"3 of 3 Wi-Fi bars","value":"AdobeCorp","dom":null,"enabled
":true,"valid":true,"visible":false,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/1","x":36,"y":0,"width":13,"height":20},">":[]}},{"UIAElement":{"@":{"name":"6:43 pm","label":"6:43 pm","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/2","x":361,"y":0,"width":46,"height":20},">":[]}},{"UIAElement":{"@":{"name":"100% battery power, Charging","label":"100% battery power, Charging","value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/3","x":696,"y":0,"width":67,"height":20},">":[]}}]}}]}}]}}}
info: [debug] [INST] 2015-07-21 13:22:14 +0000 Debug: Running system command #25: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"AEM Forms Workspace","label":"AEM Forms Workspa...

info: [debug] Socket data received (5307 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"AEM Forms Workspace","label":"AEM Forms Workspace","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":0,"width":768,"height":1024},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom"

info: [debug] Responding to client with success: {"status":0,"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n    <UIAApplication name=\"AEM Forms Workspace\" label=\"AEM Forms Workspace\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0\" x=\"0\" y=\"0\" width=\"768\" height=\"1024\">\n        <UIAWindow name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0\" x=\"0\" y=\"0\" width=\"768\" height=\"1024\">\n            <UIAScrollView name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0/0\" x=\"0\" y=\"0\" width=\"768\" height=\"1024\">\n                <UIAWebView name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0/0/0\" x=\"0\" y=\"0\" width=\"768\" height=\"1024\">\n                    <UIAStaticText name=\"User ID\" label=\"User ID\" value=\"\" dom=\"[object Object]\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0/0/0/0\" x=\"20\" y=\"133\" width=\"45\" height=\"16\">\n                    </UIAStaticText>\n                    <UIATextFie...","sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}
info: <-- GET /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/source 200 1468.572 ms - 6380 {"status":0,"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<AppiumAUT>\n    <UIAApplication name=\"AEM Forms Workspace\" label=\"AEM Forms Workspace\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0\" x=\"0\" y=\"0\" width=\"768\" height=\"1024\">\n        <UIAWindow name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0\" x=\"0\" y=\"0\" width=\"768\" height=\"1024\">\n            <UIAScrollView name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0/0\" x=\"0\" y=\"0\" width=\"768\" height=\"1024\">\n                <UIAWebView name=\"\" label=\"\" value=\"\" dom=\"\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0/0/0\" x=\"0\" y=\"0\" width=\"768\" height=\"1024\">\n                    <UIAStaticText name=\"User ID\" label=\"User ID\" value=\"\" dom=\"[object Object]\" enabled=\"true\" valid=\"true\" visible=\"true\" hint=\"\" path=\"/0/0/0/0/0\" x=\"20\" y=\"133\" width=\"45\" height=\"16\">\n                    </UIAStaticText>\n                    <UIATextFie...","sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}
info: --> GET /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/orientation {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: [debug] Sending command to instruments: au.getScreenOrientation()

info: [IOS_SYSLOG_ROW ] Jul 21 18:52:14 Stl-iPad wifid[15] <Notice>: WiFi:[459177734.879780]:

info: [IOS_SYSLOG_ROW ] Jul 21 18:52:14 Stl-iPad wifid[15] <Notice>: Too frequent(0.466743 secs) rssi event from driver, ignoring

info: [IOS_SYSLOG_ROW ] Jul 21 18:52:14 Stl-iPad wifid[15] <Notice>:

info: [debug] [INST] 2015-07-21 13:22:15 +0000 Debug: Got new command 25 from instruments: au.getScreenOrientation()

info: [debug] [INST] 2015-07-21 13:22:15 +0000 Debug: evaluating au.getScreenOrientation()

info: [debug] [INST] 2015-07-21 13:22:15 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-07-21 13:22:15 +0000 Debug: responding with:

info: [debug] [INST] 2015-07-21 13:22:15 +0000 Debug: Running system command #26: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"PORTRAIT"}...

info: [debug] Socket data received (33 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":"PORTRAIT"}
info: [debug] Setting internal orientation to PORTRAIT
info: [debug] Responding to client with success: {"status":0,"value":"PORTRAIT","sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}
info: <-- GET /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/orientation 200 922.716 ms - 82 {"status":0,"value":"PORTRAIT","sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}

info: --> GET /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/screenshot {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: [debug] Sending command to instruments: au.getScreenOrientation()

info: [debug] [INST] 2015-07-21 13:22:16 +0000 Debug: Got new command 26 from instruments: au.getScreenOrientation()

info: [debug] [INST] 2015-07-21 13:22:16 +0000 Debug: evaluating au.getScreenOrientation()

info: [debug] [INST] 2015-07-21 13:22:16 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-07-21 13:22:16 +0000 Debug: responding with:

info: [debug] [INST] 2015-07-21 13:22:16 +0000 Debug: Running system command #27: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"PORTRAIT"}...

info: [debug] Socket data received (33 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":"PORTRAIT"}
info: [debug] Setting internal orientation to PORTRAIT
info: [debug] Pushing command to appium work queue: "au.capture('screenshot5d27805d-ef15-4ffa-9c65-d336f35a0b83')"
info: [debug] Sending command to instruments: au.capture('screenshot5d27805d-ef15-4ffa-9c65-d336f35a0b83')

info: [debug] [INST] 2015-07-21 13:22:17 +0000 Debug: Got new command 27 from instruments: au.capture('screenshot5d27805d-ef15-4ffa-9c65-d336f35a0b83')

info: [debug] [INST] 2015-07-21 13:22:17 +0000 Debug: evaluating au.capture('screenshot5d27805d-ef15-4ffa-9c65-d336f35a0b83')

info: [debug] [INST] 2015-07-21 13:22:17 +0000 Debug: target.captureRectWithName("{origin:{x:0.00,y:0.00}, size:{height:1024.00,width:768.00}}", "screenshot5d27805d-ef15-4ffa-9c65-d336f35a0b83")

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}
info: <-- GET /wd/hub/status 200 0.466 ms - 178 {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}

info: [IOS_SYSLOG_ROW ] Jul 21 18:52:20 Stl-iPad wifid[15] <Notice>: WiFi:[459177740.234993]:

info: [IOS_SYSLOG_ROW ] Jul 21 18:52:20 Stl-iPad wifid[15] <Notice>: Too frequent(0.354015 secs) rssi event from driver, ignoring

info: [IOS_SYSLOG_ROW ] Jul 21 18:52:20 Stl-iPad wifid[15] <Notice>:

**Comment by ankitbhatnagar4u** [comment]
Please try to solve this asap since automation is completely stuck when appium is not able to identify elements based on name/id/ or lable

**Comment by ankitbhatnagar4u** [comment]
When I explicitly log into my app and try to click on any button then it shows error message as the element cannot be tapped. What am I doing wrong or Appium is not capable of handling this? Logs are attached below:

info: --> POST /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/element {"using":"name","value":"Go"}

info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByName('Go')"
info: [debug] Sending command to instruments: au.getElementByName('Go')
info: [debug] [INST] 2015-07-21 13:32:11 +0000 Debug: Got new command 89 from instruments: au.getElementByName('Go')
info: [debug] [INST] 2015-07-21 13:32:11 +0000 Debug: evaluating au.getElementByName('Go')
info: [debug] [INST] 2015-07-21 13:32:11 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-07-21 13:32:11 +0000 Debug: responding with:
info: [debug] [INST] 2015-07-21 13:32:11 +0000 Debug: Running system command #90: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Condition unmet after 871ms. Timing out.
info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":""},"sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}
info: <-- POST /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/element 500 871.378 ms - 179 
info: --> POST /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/execute {"script":"mobile: swipe","args":[{"endX":331,"duration":0.8400781,"endY":136,"touchCount":1,"startX":477,"startY":141}]}
info: [debug] Pushing command to appium work queue: "au.dragApp(477,141,331,136,0.8400781)"
info: [debug] Sending command to instruments: au.dragApp(477,141,331,136,0.8400781)
info: [debug] [INST] 2015-07-21 13:32:12 +0000 Debug: Got new command 90 from instruments: au.dragApp(477,141,331,136,0.8400781)
info: [debug] [INST] 2015-07-21 13:32:12 +0000 Debug: evaluating au.dragApp(477,141,331,136,0.8400781)
info: [debug] [INST] 2015-07-21 13:32:12 +0000 Debug: target.dragFromToForDuration({x:"477", y:"141"}, {x:"331", y:"136"}, "0.8400781")
info: [debug] [INST] 2015-07-21 13:32:13 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-07-21 13:32:13 +0000 Debug: responding with:
info: [debug] [INST] 2015-07-21 13:32:13 +0000 Debug: Running system command #91: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}
info: <-- POST /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/execute 200 2835.275 ms - 74 {"status":0,"value":"","sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}
info: --> POST /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/element {"using":"name","value":"Back"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByName('Back')"
info: [debug] Sending command to instruments: au.getElementByName('Back')
info: [debug] [INST] 2015-07-21 13:32:15 +0000 Debug: Got new command 91 from instruments: au.getElementByName('Back')
info: [
debug] [INST] 2015-07-21 13:32:15 +0000 Debug: evaluating au.getElementByName('Back')
info: [debug] [INST] 2015-07-21 13:32:15 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-07-21 13:32:15 +0000 Debug: Lookup returned [object UIAButton] with the name "UINavigationBarBackIndicatorDefault.png" (id: 6).
info: [debug] [INST] 2015-07-21 13:32:15 +0000 Debug: responding with:
info: [debug] [INST] 2015-07-21 13:32:15 +0000 Debug: Running system command #92: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"6"}}...
info: [debug] Socket data received (38 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"6"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"6"},"sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}
info: <-- POST /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/element 200 1283.196 ms - 87 {"status":0,"value":{"ELEMENT":"6"},"sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}
info: --> POST /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/element/6/click {}
info: [debug] Pushing command to appium work queue: "au.tapById('6')"
info: [debug] Sending command to instruments: au.tapById('6')
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}
info: <-- GET /wd/hub/status 200 0.383 ms - 178 {"status":0,"value":{"build":{"version":"1.3.1","revision":"1160ce02bb89c354cb99317985123acf39f0e7d3"},"isShuttingDown":false},"sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}
info: [IOS_SYSLOG_ROW ] Jul 21 19:02:16 Stl-iPad MobileGestaltHelper[72] <Error>: libMobileGestalt MobileGestalt.c:267: server_access_check denied access to question UniqueDeviceID for pid 5621
info: [IOS_SYSLOG_ROW ] Jul 21 19:02:16 Stl-iPad ScriptAgent[5621] <Error>: libMobileGestalt MobileGestaltSupport.m:167: pid 5621 (ScriptAgent) does not have sandbox access for re6Zb+zwFKJNlkQTUeT+/w and IS NOT appropriately entitled
info: [IOS_SYSLOG_ROW ] Jul 21 19:02:16 Stl-iPad ScriptAgent[5621] <Error>: libMobileGestalt MobileGestalt.c:528: no access to UniqueDeviceID (see <rdar://problem/11744455>)
info: [debug] [INST] 2015-07-21 13:32:16 +0000 Debug: Got new command 92 from instruments: au.tapById('6')
info: [debug] [INST] 2015-07-21 13:32:16 +0000 Debug: evaluating au.tapById('6')
info: [debug] [INST] 2015-07-21 13:32:16 +0000 Debug: UIAButton.tap()
info: [IOS_SYSLOG_ROW ] Jul 21 19:02:16 Stl-iPad MobileGestaltHelper[72] <Error>: libMobileGestalt MobileGestalt.c:267: server_access_check denied access to question UniqueDeviceID for pid 5621
info: [IOS_SYSLOG_ROW ] Jul 21 19:02:16 Stl-iPad ScriptAgent[5621] <Error>: libMobileGestalt MobileGestaltSupport.m:167: pid 5621 (ScriptAgent) does not have sandbox access for re6Zb+zwFKJNlkQTUeT+/w and IS NOT appropriately entitled
info: [IOS_SYSLOG_ROW ] Jul 21 19:02:16 Stl-iPad ScriptAgent[5621] <Error>: libMobileGestalt MobileGestalt.c:528: no access to UniqueDeviceID (see <rdar://problem/11744455>)
info: [debug] [INST] 2015-07-21 13:32:16 +0000 Debug: UIAButton could not be tapped
info: [debug] [INST] 2015-07-21 13:32:16 +0000 Error: VerboseError: elementId 6 could not be tapped
info: [debug] Sock
et data received (57 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":13,"value":"elementId 6 could not be tapped"}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"elementId 6 could not be tapped"},"sessionId":"6c8356c8-3e43-44aa-a977-c828787f03a0"}
info: <-- POST /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/element/6/click 500 3863.408 ms - 200 
info: --> GET /wd/hub/session/6c8356c8-3e43-44aa-a977-c828787f03a0/source {}
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-07-21 13:32:18 +0000 Error: Error during eval: tapById@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/6FDAFD71-EBF2-4D56-9D6B-DFE0717489E3/bootstrap-60f23230385b0cfa.js:1094:25
       eval code
eval@[native code]
startProcessing@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/6FDAFD71-EBF2-4D56-9D6B-DFE0717489E3/bootstrap-60f23230385b0cfa.js:2660:30
bootstrap@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/6FDAFD71-EBF2-4D56-9D6B-DFE0717489E3/bootstrap-60f23230385b0cfa.js:2726:31
global code@file:///Applications/Appium.app/Contents/Resources/node_modules/appium/6FDAFD71-EBF2-4D56-9D6B-DFE0717489E3/bootstrap-60f23230385b0cfa.js:2735:10

info: [debug] [INST] 2015-07-21 13:32:19 +0000 Debug: responding with:

info: [debug] [INST] 2015-07-21 13:32:19 +0000 Debug: Running system command #93: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":13,"value":"elementId 6 could not be tapped"}...

info: [debug] [INST] 2015-07-21 13:32:20 +0000 Debug: Got new command 93 from instruments: au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-07-21 13:32:20 +0000 Debug: evaluating au.mainApp().getTreeForXML()

**Comment by sebv** [comment]
Try to print the page source before the find to see what is there. 

Also try using Accessibility Ids and finders.
