### ISSUE TITLE
Appium 1.4.6 iOS, TAP Javascript bug?

### ISSUE THREAD

**Issue by qaDream77** [appium/appium#5418]
Most of the time when testing the app i get this as a warning.

info: [debug] [INST] 2015-07-19 13:30:51 +0000 Debug: Running system command #33: /usr/local/Cellar/node/0.12.4/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] [INST] 2015-07-19 13:30:51 +0000 Stopped: Script was stopped by the user
info: [debug] [INST] 2015-07-19 13:30:51 +0000 Error: Script threw an uncaught JavaScript error: JSON Parse error: Unexpected EOF on line 2606 of bootstrap-34512427e41832c2.js

Most of the time this goes ignored and doesn't break, sometimes however it breaks the automation because it can't find the object to tap on. I am wondering if this is an appium bug or? I checked the source and the button is there.

**Comment by sebv** [comment]
Please provide full log in gist.

**Comment by qaDream77** [comment]
Sorry for the delayed reply, i was on vacation. I'll post the full log tomorrow.

**Comment by SrinivasanTarget** [comment]
@triager please close
