### ISSUE TITLE
sendKeys doesn't work on Android

### ISSUE THREAD

**Issue by ivan-baranovski-intellectsoft** [appium/appium#5420]
I am using appium version 1.4.8 and i am running a tests on the different android devices. When I am printing text in the field i am getting the below error:

info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":"This element does not have the 'value' attribute"},"sessionId":"4d5c5d54-0500-4fa9-9c74-ccf27a18192d"}
info: <-- GET /wd/hub/session/4d5c5d54-0500-4fa9-9c74-ccf27a18192d/element/6/attribute/value 500 11.834 ms - 227 

The field element was found and click was performed. But the error is displayed after I am starting to print.
I used different locators but result is identical.
I tried to send keys in appium inspector. The keys was printed. 
I use this code:
WebElement loginBox = findElement(MobileBy.AndroidUIAutomator("resourceId(\"emailEditText\")"));
  loginBox.click();      
  loginBox.sendKeys("text");

**Comment by srk9ravi** [comment]
Have you verified your resourceId provided is able to identify the element on your app using appium Locator tab?

this happens usually when the appium unable to recognize the element using the provided locator.

**Comment by ivan-baranovski-intellectsoft** [comment]
I have found the problem. 
I use 		
`originalValue = element.getAttribute("value");`
insted of
`originalValue = element.getAttribute("text");`
when I try to get a log about current value in a field.
