### ISSUE TITLE
getLocationInView() please help calc to pixel

### ISSUE THREAD

**Issue by nhanh2301** [appium/appium#5423]
I get position with getLocationInView() and Appium return result
x: 109 and y: 225

but I using Sony Z3 (Android 5.1.1) for test App.

I debug point of element is: x: 435 and y: 835

i don't know, how to calc make result x 435 and y 835

getLocationInView return dpi and I need convert to pixel?

**Comment by sebv** [comment]
Please go to https://discuss.appium.io/ for support.
