### ISSUE TITLE
How to do swipe in appium

### ISSUE THREAD

**Issue by Pushpank** [appium/appium#5426]
Hello ,

I am using android device and want to test a swipe function on a contact pls help me how to do it .
I am using below code this is showing error..

driver.findElement(By.name("Tgroup"));
		JavascriptExecutor js=(JavascriptExecutor) driver; 
		HashMap<String, Double> swipeObject = new HashMap<String, Double>();
		swipeObject.put("startX",(double) 564); 
		swipeObject.put("startY",(double) 417); 
		swipeObject.put("endX",(double) 720); 
		swipeObject.put("endY",(double) 563); 
		 swipeObject.put("duration", 2.0);
		js.executeScript("mobile: swipe",swipeObject);

**Comment by Netoperek** [comment]
Hi. How about this:

appium_driver.within_context 'NATIVE_APP' do                                    
  ele = appium_driver.xpath(native_xpath)                                
  bounds = appium_element_bounds(native_xpath)                           
  start_x = bounds[:start_x] + 1                                                
  end_x = bounds[:end_x] - 1 
  start_y = bounds[:start_y]  + 1
  end_y= bounds[:end_y]  - 1
  appium_driver.swipe(                                                          
    start_x: start_x,                                                   
    start_y: start_y ,                                          
    end_x: end_x,                                                               
    end_y: end_y,                                                
    duration: 200)                                                              
end

**Comment by beemi** [comment]
driver.swipe(startx=75, starty=500, endx=75, endy=0, duration=800)

**Comment by Pushpank** [comment]
Hello,

Driver.swipe(222,460,90,460
,2000) is working fine for me for right to left swipe y axis make constant
for left or right swipe then it will work....

**Comment by sebv** [comment]
Please search this issue list or go to https://discuss.appium.io/
