### ISSUE TITLE
Appium 1.4.6 iOS, Bug report with appium.log

### ISSUE THREAD

**Issue by qaDream77** [appium/appium#5427]
Datestamp is correct, timestamp is not unless it is working on a different timezone other than my system clock.

appium.log returns success when it can't find an element.  Start your test script, which does tap your app and go back. I press the home button before the script has a chance to locate and press the go back button. So my python script will make a log of the error saying it cannot find element but the appium.log file itself won't.

**Comment by sebv** [comment]
Please read the doc regarding timezone and go to https://discuss.appium.io/ for support, this list is for specific bugs only.
