### ISSUE TITLE
Unable to install appium version 1.4.4 and after through npm

### ISSUE THREAD

**Issue by nabhinandan** [appium/appium#5432]
Hi,

  I am unable to install Appium version 1.4.4 and after through npm.
node version : v0.12.6
I have installed Git, maven/Ant/visual studio 2013/java/android sdk.

Context switching is failing on android device with appium version : 1.4.0,1.4.1, 1.4.2, and it was told the issue is fixed in 1.4.3. but when I installed 1.4.3  I faced the issue undefined is not a method. Hence I want to update to latest version and check if context switching works.

For few devices appium 1.3.7 list webview context for our android app. for few devices it wont.

Please help me how to resolve these issues.

**Comment by sebv** [comment]
try `npm update -g npm && npm cache clear`

**Comment by nabhinandan** [comment]
I am getting the below error after npm update and cache clear

C:\Windows\system32>npm update -g npm && npm cache clear
C:\Users\abhi\AppData\Roaming\npm\npm -> C:\Users\abhi\AppData\Roaming\npm\node_
modules\npm\bin\npm-cli.js
npm@2.13.3 C:\Users\abhi\AppData\Roaming\npm\node_modules\npm

C:\Windows\system32>npm install -g appium
npm ERR! tar.unpack untar error C:\Users\abhi\AppData\Local\Temp\npm-4484-ba81e3
0c\registry.npmjs.org\swig\-\swig-1.4.2.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2

npm ERR! unexpected eof
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log


Error While installing appium1.4.7:
          There is no context in which this conversion is possible
..\src\validation.cc(112): error C2039: 'NewSymbol' : is not a member of 'v8::S
tring' [C:\Users\abhi\AppData\Roaming\npm\node_modules\appium\node_modules\sock
et.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\
ws\build\validation.vcxproj]
          C:\Users\abhi\.node-gyp\0.12.6\deps\v8\include\v8.h(1599) : see decla
  ration of 'v8::String'
..\src\validation.cc(112): error C3861: 'NewSymbol': identifier not found [C:\U
sers\abhi\AppData\Roaming\npm\node_modules\appium\node_modules\socket.io\node_m
odules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\val
idation.vcxproj]
..\src\validation.cc(134): error C2660: 'v8::True' : function does not take 0 a
rguments [C:\Users\abhi\AppData\Roaming\npm\node_modules\appium\node_modules\so
cket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_module
s\ws\build\validation.vcxproj]
..\src\validation.cc(134): error C2660: 'v8::False' : function does not take 0
arguments [C:\Users\abhi\AppData\Roaming\npm\node_modules\appium\node_modules\s
ocket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modul
es\ws\build\validation.vcxproj]
/
> appium-chromedriver@2.1.3 install C:\Users\abhi\AppData\Roaming\npm\node_modul
es\appium\node_modules\appium-chromedriver
> node install-npm.js

Error: Command failed: C:\Windows\system32\cmd.exe /s /c "uname -m"
'uname' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6"
,"npm":"2.11.2"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.1
2.6","npm":"2.11.2"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6",
"npm":"2.11.2"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6",
"npm":"2.11.2"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6",
"npm":"2.11.2"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium@1.4.7"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.1.3 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@2.1.3 install script 'node install-np
m.js'.
npm ERR! This is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by sebv** [comment]
The npm upgrade did not work. You installed 2.13.3 and it is still using 2.11.2

**Comment by nabhinandan** [comment]
I updated to the latest npm using the steps in : https://github.com/npm/npm/wiki/Troubleshooting

But facing the error:
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.7","npm":"2.13.3"})
npm ERR! tar.unpack untar error C:\Users\abhi\AppData\Local\Temp\npm-3848-a74018
29\registry.npmjs.org\highlight.js\-\highlight.js-8.6.0.tgz
-
> appium-chromedriver@2.1.3 install C:\Program Files\nodejs\node_modules\appium\
node_modules\appium-chromedriver
> node install-npm.js

info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com
/2.15/chromedriver_win32.zip...
info Chromedriver Install Writing binary content to C:\Users\abhi\AppData\Local\
Temp\11573-3492-5mt8bu\chromedriver_win32.zip...
info Chromedriver Install Extracting C:\Users\abhi\AppData\Local\Temp\11573-3492
-5mt8bu\chromedriver_win32.zip to C:\Users\abhi\AppData\Local\Temp\11573-3492-5m
t8bu\chromedriver_win32
info Chromedriver Install Creating C:\Program Files\nodejs\node_modules\appium\n
ode_modules\appium-chromedriver\chromedriver\win...
info Chromedriver Install Copying unzipped binary, reading from C:\Users\abhi\Ap
pData\Local\Temp\11573-3492-5mt8bu\chromedriver_win32\chromedriver.exe...
info Chromedriver Install Writing to C:\Program Files\nodejs\node_modules\appium
\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe...
info Chromedriver Install C:\Program Files\nodejs\node_modules\appium\node_modul
es\appium-chromedriver\chromedriver\win\chromedriver.exe successfully put in pla
ce
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7"
,"npm":"2.13.3"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.1
2.7","npm":"2.13.3"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7",
"npm":"2.13.3"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7",
"npm":"2.13.3"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.7",
"npm":"2.13.3"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.3

npm ERR! unexpected eof
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by sebv** [comment]
you can try `npm install -gf appium` or reinstall the whole node.js, but I don't think this is an appium issue.

**Comment by nabhinandan** [comment]
After following below steps. I was able to installed latest appium version. Thank you.

npm config set registry http://registry.cnpmjs.org
npm cache clean appium
npm install -g appium@1.4.8

**Comment by mgmcdermott** [comment]
@sebv I realize that this is very outdated, but after a lot of head bashing, I've found that on my company's private registry, version 1.4.3 installs properly and 1.4.4 and up fail to install. No matter what, they make requests to the default npm registry (https://registry.npmjs.org/).

I realize this may seem like an issue on our end, but due to the fact that this is the only package that causes this issue and the solution above was to change registries (not a good solution for us), I think it may in fact be an issue with appium (or one of its dependencies). Any ideas?

**Comment by jlipps** [comment]
@mgmcdermott I'm not sure how private registries work, but I can't think of anything we're doing that would cause issues. What error do you get exactly? And you're on latest Node, latest NPM, and trying to install latest Appium?

**Comment by mgmcdermott** [comment]
Sorry for not responding, @jlipps (I hate when people do that). We are looking at it internally, I'll be sure to post the solution/real issue here if we figure it out.

**Comment by mgmcdermott** [comment]
So after some investigation, it appears that because appium is shipped with a npm-shrinkwrap.json that points to the default npm registry, it prevents us from using our internal registry. We can set up a proxy to hit the default registry as a workaround, but what is the reasoning behind publishing appium with a shrinkwrap?

**Comment by imurchie** [comment]
Appium is published with shrinkwrap because it allows us to lock in dependencies with know-working versions. Otherwise each install is subject to change, and we have no idea what is going on. It is possible to not use it by specifying `--no-shrinkwrap` when running `npm install`.

**Comment by imurchie** [comment]
You can add something like https://www.npmjs.com/package/rewrite-shrinkwrap-urls to your workflow as well, to get around it. Not sure what is the best practice.
