### ISSUE TITLE
How to locate elements relatively？

### ISSUE THREAD

**Issue by BernieLiu** [appium/appium#5434]
like get element's parent/child/sbling. base on that,  maybe we can construct relative path to locate element, it can be helpful to write robust code 

i found WebElement also has findElement(s) method, what's different from driver‘s？maybe it will find in the scope of element's children?

**Comment by srk9ravi** [comment]
findElements will return all the elements of the same class type on the screen/page, like buttons, statistexts..etc

where as findElement will return only one element of the given locator strategy.

**Comment by BernieLiu** [comment]
@srk9ravi  i mean what't difference between driver.findElement(s) and el.findElement(s)

the webElement class also have method findElement(s), is it same as driver‘s method?

**Comment by BernieLiu** [comment]
el.findElement(s) will search from el itself, the same as "search from selected element" in inspector.

so, it can be a way to locate child node

**Comment by sebv** [comment]
This is a client issue, please go to the driver project or https://discuss.appium.io/ for support.
