### ISSUE TITLE
Why i get a Error:  Invalid locator strategy: css selector

### ISSUE THREAD

**Issue by SimonMagg** [appium/appium#5435]
Env: 
Mac OSX version: 10.10.4 
Appium version: 1.4.8
Appium-Python-Client  v0.17 
 
My Question:
Whenever I try run a script for android. such as "driver.find_element_by_id("xxxx").click()
Appium returns: Invalid locator strategy: css selector

same of this Script (device)  on windows OS.  work is fine.

Thank for your help.
sorry my english able is too bad.

**Comment by srk9ravi** [comment]
what is the locator value you are providing in your script to fine the element.

appium accepts only name, xpath and resour-id for individual elements.

have you tried to locate the element with your locator strategy with appium locator tab?

**Comment by SimonMagg** [comment]
@srk9ravi  Yes. i had use xpath to run android  scripts on mac.  it's  work fine.
 
i used "resour-id". it's not work.   but, can run on Windows OS.

**Comment by SimonMagg** [comment]
Appium run logs:
info: --> POST /wd/hub/session/e5f59993-17e6-4184-8546-7a08153932af/element {"using":"css selector","sessionId":"e5f59993-17e6-4184-8546-7a08153932af","value":"[id=\"login_account\"]"}
info: [debug] Invalid locator strategy: css selector
info: [debug] Responding to client with error: {"status":9,"value":{"message":"Invalid locator strategy: css selector","origValue":"Invalid locator strategy: css selector"},"sessionId":"e5f59993-17e6-4184-8546-7a08153932af"}
info: <-- POST /wd/hub/session/e5f59993-17e6-4184-8546-7a08153932af/element 500 0.654 ms - 177

**Comment by srk9ravi** [comment]
driver.find_element_by_css_selector("\"login_account\").click()

if i am not worng, is the above statement you are using in your code to click on that element? i think, that's why it is returning like '"using":"css selector"' in the above log.

if not it should return '"using":"xpath" if you are using xpath to find the element.

i am not very sure, but please re-check your statement once it is written as by_css_selector or by_xpath?

**Comment by SimonMagg** [comment]
@srk9ravi  Thank of you replay.
Hmm.

**Comment by SimonMagg** [comment]
![myscript](https://cloud.githubusercontent.com/assets/13521580/8923440/6b0dedc8-3523-11e5-9c82-ae80e6959548.png)

**Comment by JMoravec** [comment]
This seems to be a bug in the Python Selenium package. I was able to work around this by downgrading to `Appium-Python-Client==0.14` and `Selenium==2.45.0`

I was able to recreate the issue when using `Appium-Python-Client==0.14` (or 0.17) and `Selenium==2.46.1`

**Comment by SimonMagg** [comment]
@JMoravec  Thanks for your help.
I will  try  again . downgrading to Appium-Python-Client==0.14 and Selenium==2.45.0

**Comment by SimonMagg** [comment]
Changed Appium-Python-Client==0.14 and Selenium==2.45.0
it was work fine.
Thanks all guys.

**Comment by nirvesh0103** [comment]
I had a same issue with appium. And after downgrading selenium to 2.45. Its working fine. Thanks to all.

**Comment by JMoravec** [comment]
Issue in SeleniumHQ for tracking: https://github.com/SeleniumHQ/selenium/issues/842
