### ISSUE TITLE
Target failed to run: Permission to debug com.igate.cloud was denied. The app must be signed with a development identity (e.g. iOS Developer).

### ISSUE THREAD

**Issue by atobulredy** [appium/appium#5437]
Hi,

When i was installing app with appium, I am getting the below error.
Target failed to run: Permission to debug com.igate.cloud was denied. The app must be signed with a development identity (e.g. iOS Developer).

Can you please check this ?

**Comment by sebv** [comment]
The error message is self-explainatory, please refer to the appium doc.

You may also first try to automate your app with Instruments, this is actually an Apple requirement.

**Comment by SrinivasanTarget** [comment]
@triager please close
