### ISSUE TITLE
Appium Tests abort with a 401 authentication error after running ~870 lines from google spreadsheet input file

### ISSUE THREAD

**Issue by tsumartin** [appium/appium#5439]
Coding in ruby,  I need to run ~1120 steps from Google spreadsheet input file to complete an acceptance suite, but tests abort after ~780 steps execute with a 401 error like:
------sparseData------																	
/Library/Ruby/Gems/2.0.0/gems/google_drive-1.0.1/lib/google_drive/session.rb:422:in `request': Response code 401 for get https://spreadsheets.google.com/feeds/worksheets/1cvvkTv9GADM8JhMffqhx5_ov9OFzHHzY49xnqBFs5Rw/private/full: <HTML> (GoogleDrive::AuthenticationError)																	
<HEAD>																	
<TITLE>Unauthorized</TITLE>																	
</HEAD>																	
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">																	
<H1>Unauthorized</H1>																	
<H2>Error 401</H2>																	
</BODY>																	
</HTML>																	
	from /Library/Ruby/Gems/2.0.0/gems/google_drive-1.0.1/lib/google_drive/spreadsheet.rb:59:in `worksheets'																
	from /Library/Ruby/Gems/2.0.0/gems/google_drive-1.0.1/lib/google_drive/spreadsheet.rb:73:in `worksheet_by_title'																
	from /Users/smartin/Developer/QA_Common/readFromGoogleSS_oath2.rb:101:in `executeTest'																
	from /Users/smartin/Developer/QA_GAi/Source/driver.rb:125:in `<main>'

**Comment by sebv** [comment]
Sorry I don't think this is an Appium issue.

**Comment by SrinivasanTarget** [comment]
@triager please close
