### ISSUE TITLE
[SOLVED] iOS: Real Device: Appium driver still asking "app" even if "bundleID" and "udid" are provided

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#5440]
Hi,

met with strange issue that Appium driver still need app file to test on real device when app is preinstalled on device + "bundleID" and "udid" are provided.

Appium 1.4.7, java-client 3.1.0, Mac OS X 10.10.4

Appium starting as:
```
start appium as: [appium, --log-level, error, --show-ios-log, --show-sim-log, --port, 4724, --session-override]
```

NOT WORKING CFG:
```
Capabilities [{automationName=Appium, newCommandTimeout=120, platform=MAC, platformVersion=8.4, fullReset=false, deviceName=iPad, browserName=iPad, bundleID=com.***sensored***, udid=***sensored***, noReset=true, version=}]
     open driver for iOS

org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Please provide the 'app' or 'browserName' capability or start appium with the --app or --browser-name argument. Alternatively, you may provide the 'bundleId' and 'udid' capabilities for an app under test on a real device.) (WARNING: The server did not provide any stacktrace information)
```

WORKING CFG:
```
Capabilities [{automationName=Appium, newCommandTimeout=120, platform=MAC, platformVersion=8.4, app=/Users/***sensored***/***sensored***.app, deviceName=iPad, fullReset=false, browserName=iPad, bundleID=com.***sensored***, udid=***sensored***, noReset=true, version=}]
```

**Comment by ellenmobify** [comment]
I'm able to test on a real device by specifying the bundle ID "com.blah.yourapp" *as the value* for `app`. Give that a try?

**Comment by rxiong** [comment]
Is it bundleID or bundleId? Not sure if its case sensitive, but we will start with real device soon and i would like to know as well.

**Comment by ellenmobify** [comment]
`bundleId`

**Comment by amedvedjev** [comment]
did i say something other?

ellenmobify - without server and driver config + component versions you can't confirm other. pls confirm it.

i am also using "bundleId". what i wrote is result what appium itself returns with:

System.out.println(capabilities) where capabilities = DesiredCapabilities.android(); and 'bundleId' value i just removed here in post for secure company purposes.

**Comment by amedvedjev** [comment]
yes it was misprint. thanks for catching.
