### ISSUE TITLE
Logcat capture failed: spawn "/Users/kingangeltot/Library/Android/sdk/platform-tools/adb"

### ISSUE THREAD

**Issue by kingangelTOT** [appium/appium#5441]
system: OS X Yosemite
appium version: 1.4.8

➜  tools  echo $ANDROID_HOME
/Users/kingangeltot/Library/Android/sdk

➜  tools  echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/jre/bin:/Users/kingangeltot/Library/Android/sdk/tools:/Users/kingangeltot/Library/Android/sdk/platform-tools

➜  tools  echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home

➜  tools  appium-doctor
Running iOS Checks
✔ Xcode is installed at /Applications/Xcode.app/Contents/Developer
✔ Xcode Command Line Tools are installed.
✔ DevToolsSecurity is enabled.
✔ The Authorization DB is set up properly.
✔ Node binary found at /usr/local/bin/node
✔ iOS Checks were successful.

Running Android Checks
✔ ANDROID_HOME is set to "/Users/kingangeltot/Library/Android/sdk"
✔ JAVA_HOME is set to "/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home."
✔ ADB exists at /Users/kingangeltot/Library/Android/sdk/platform-tools/adb
✔ Android exists at /Users/kingangeltot/Library/Android/sdk/tools/android
✔ Emulator exists at /Users/kingangeltot/Library/Android/sdk/tools/emulator
✔ Android Checks were successful.

✔ All Checks were successful

So what's wrong

**Comment by sebv** [comment]
Please provide server log in gist.

**Comment by SrinivasanTarget** [comment]
@triager please close
