### ISSUE TITLE
Install app does nothing on Sauce

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5442]
Install app takes a local path which makes it a no-op on sauce labs. Install app should be made sauce storage aware so people can migrate tests to Sauce Labs.

**Comment by Jonahss** [comment]
ooh :+1:

**Comment by jlipps** [comment]
This would not be a change on the Appium side. This would require Sauce trapping the call to install app, and replacing the "sauce-storage" url with a VM-local path. Anyone who's reading this and wants this feature should contact Sauce support and let them know you want it :-)

**Comment by imurchie** [comment]
We could add `"sauce-storage:"` as a valid scheme when we parse the app.
