### ISSUE TITLE
Appium refuses to install chrome apk

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5443]
```
caps['app']          = 'sauce-storage:my_chrome_fork.apk'
caps['appPackage']   = 'com.android.chrome'
caps['appActivity']  = 'com.google.android.apps.chrome.ChromeTabbedActivity' 
```

Appium will always use the on device chrome and won't even attempt to install the apk specified in app. I'd expect this behavior if browserName was set to `Chrome`, however since `app` is set I want appium to install the app.
- See this [Sauce job for an example](https://saucelabs.com/beta/tests/de58ad9f7721466e95dc053443e60c89/logs)

**Comment by jlipps** [comment]
I believe this should be fixed. Nowhere in Appium's code do we look at `appPackage` any more to determine whether to launch built-in Chrome or not. We look at `browserName`. If anyone is still experiencing this, please let us know.
