### ISSUE TITLE
Feature request: Toggle Wifi in background on an unrooted Android Device

### ISSUE THREAD

**Issue by auszone** [appium/appium#5447]
I'm using appium to do android automation. When I toggle wifi off, it switches apps to do that. Is it possible to toggle wifi in background on an unrooted Android Device?

**Comment by cades** [comment]
+1

**Comment by amedvedjev** [comment]
why not to do via adb command in code whatever you like :-) ?

**Comment by cades** [comment]
Because the machine that device connect to is the one running Appium, which maybe not the same as running testing code.

**Comment by sebv** [comment]
What would the adb command be like?

**Comment by VSergiyenko** [comment]
@sebv adb command is:
`adb -s `_`deviceUDID`_` shell am start -n io.appium.settings/.Settings -e wifi on`
for turning wifi on
and `adb -s `_`deviceUDID`_` shell am start -n io.appium.settings/.Settings -e wifi off`

im currently experiencing same problem:
running tests vs 2 physical devices, i cant figure out how to turn wifi on/off on the same device as my test is being currently ran for

any brilliant clues are appriated @jlipps :grin:

**Comment by jlipps** [comment]
@VSergiyenko you are saying that the adb command appium uses does not include the device id so it's not picking the correct device?

**Comment by VSergiyenko** [comment]
no @jlipps, it's just i was trying to find a way to retrieve udid from appium in order to use it as a part of adb cmd (that in my case is being ran fron runtime context not appium), but i wasn't able to
so the usage of https://github.com/appium/appium-adb would allows to execute adb commands to set wifi state through appium?

**Comment by jlipps** [comment]
@VSergiyenko what's wrong with just using the wifi commands within appium?

**Comment by VSergiyenko** [comment]
@jlipps are there any other options than the usage of https://www.npmjs.com/package/io.appium.settings or what is suggested at http://stackoverflow.com/questions/32010670/using-selenium-and-appium-is-it-possible-to-change-between-wifi-networks?
sorry if questions seem silly and thank you! :bow:

**Comment by jlipps** [comment]
if your goal is just to turn wifi off and then on again, yes, that should work

**Comment by SrinivasanTarget** [comment]
This is fixed in latest android-driver and java client.

**Comment by SrinivasanTarget** [comment]
@triager please close
