### ISSUE TITLE
location element is wrong 

### ISSUE THREAD

**Issue by kingangelTOT** [appium/appium#5448]
location element success by Appium Inspector 
info: --> POST /wd/hub/session/eaaa33dd-1eb2-440e-afa2-5f4bf9f58d2d/elements {"using":"id","value":"me.ele:id/userCenter_avatar_iv"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"id","selector":"me.ele:id/userCenter_avatar_iv","context":"","multiple":true}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"me.ele:id/userCenter_avatar_iv","context":"","multiple":true}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding me.ele:id/userCenter_avatar_iv using ID with the contextId:  multiple: true
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[RESOURCE_ID=me.ele:id/userCenter_avatar_iv]
info: [debug] [BOOTSTRAP] [debug] getElements selector:UiSelector[RESOURCE_ID=me.ele:id/userCenter_avatar_iv]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (0)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=me.ele:id/userCenter_avatar_iv]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (1)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[INSTANCE=1, RESOURCE_ID=me.ele:id/userCenter_avatar_iv]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":[{"ELEMENT":"8"}]}

but use script is wrong:
info: --> POST /wd/hub/session/77eaae4c-680d-4295-9305-51bc7b85aa48/elements {"using":"id","value":"me.ele:id/userCenter_avatar_iv"}
info: [debug] Waiting up to 10000ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"id","selector":"me.ele:id/userCenter_avatar_iv","context":"","multiple":true}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"me.ele:id/userCenter_avatar_iv","context":"","multiple":true}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding me.ele:id/userCenter_avatar_iv using ID with the contextId:  multiple: true
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[RESOURCE_ID=me.ele:id/userCenter_avatar_iv]
info: [debug] [BOOTSTRAP] [debug] getElements selector:UiSelector[RESOURCE_ID=me.ele:id/userCenter_avatar_iv]
info: [debug] [BOOTSTRAP] [debug] Element[] is null: (0)
info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[INSTANCE=0, RESOURCE_ID=me.ele:id/userCenter_avatar_iv]

info: [debug] [BOOTSTRAP] [debug] Failed to locate element. Clearing Accessibility cache and retrying.

what's wrong

**Comment by sebv** [comment]
Not sure, you may print a page source before the find to see if the element is really there.
