### ISSUE TITLE
fullReset capability does not delete the app if it already exists (installs on top of it)

### ISSUE THREAD

**Issue by Simon-Kaz** [appium/appium#5453]
With fullReset capability set to True, I was expecting the app to always be deleted and then installed.

Right now, when the app already exists on the ios device, it will not be deleted, it will be overwritten. 

What this means is that the data within the app will be retained, so e.g. user will be logged in.

**Comment by Jonahss** [comment]
Yup, `fullReset` should uninstall then install. Marking as a bug :)

**Comment by imurchie** [comment]
This has all been rewritten. Closing.
