### ISSUE TITLE
Automation Instrument ran into an exception while trying to run the script.  UIAScriptAgentSignaledException

### ISSUE THREAD

**Issue by gongxiujin** [appium/appium#5458]
info: Welcome to Appium v1.4.1 (REV ce6220829063679bcccf5724515c29569c4a16d9)

info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"app":"com.ooch.woqu","udid":"d8d2c6e304c64345b05753f86a283c37a99d5ff2","deviceName":"iPhone 5","platformName":"iOS","platformVersion":"8.1.1","showIOSLog":true,"defaultCommandTimeout":7200,"debugLogSpacing":true}

info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: <-- GET /wd/hub/status 200 8.795 ms - 104 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: <-- GET /wd/hub/status 200 3.214 ms - 104 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}
info: <-- GET /wd/hub/status 200 0.565 ms - 104 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}
info: <-- GET /wd/hub/status 200 0.705 ms - 104 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"}}}
info: --> GET /wd/hub/sessions {}
info: [debug] Responding to client with success: {"status":0,"value":[]}
info: <-- GET /wd/hub/sessions 200 0.789 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"8.1.1","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone 5"}}

info: Client User-Agent string: Appium (unknown version) CFNetwork/720.3.13 Darwin/14.3.0 (x86_64)
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] App is an iOS bundle, will attempt to run as pre-existing
info: [debug] Creating new appium session aece1080-93dc-43b1-9ff5-85b6dbfc4210
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.ooch.woqu/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.ooch.woqu/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/lonres/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/lonres/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js
info: [debug] Reusing dynamic bootstrap: /Users/lonres/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js
info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog

info: [debug] Creating iDevice object with udid d8d2c6e304c64345b05753f86a283c37a99d5ff2

info: [debug] App is installed.

info: [debug] fullReset not requested. No need to install.
info: [debug] Starting command proxy.

info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: Launching instruments

info: [debug] Attempting to run app on real device with UDID d8d2c6e304c64345b05753f86a283c37a99d5ff2
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w d8d2c6e304c64345b05753f86a283c37a99d5ff2 com.ooch.woqu -e UIASCRIPT "/Users/lonres/Library/Application Support/appium/bootstrap/bootstrap-6745615c424bb0c0.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2015-08-02 12:19:23.252 instruments[3895:360496] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [debug] [INST STDERR] 2015-08-02 12:19:24.435 instruments[3895:360551] Automation Instrument ran into an exception while trying to run the script.  UIAScriptAgentSignaledException

info: [debug] [INST] 2015-08-02 04:19:24 +0000 Fail: An error occurred while trying to run the script.

info: [debug] [INST] Instruments Trace Complete (Duration : 1.418549s; Output : /tmp/appium-instruments/instrumentscli0.trace)

info: [debug] [INSTSERVER] Instruments exited with code 0

info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator

info: [IOS_SYSLOG_ROW ] Aug  2 12:19:21 kebide-iPhone kernel[0] <Notice>: flow_divert_token_set (0): Failed to get the key unit from the token: 22

info: [IOS_SYSLOG_ROW ] Aug  2 12:19:21 kebide-iPhone lockdownd[26] <Error>: Could not set socket option SO_OPPORTUNISTIC: Invalid argument
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:21 kebide-iPhone syslog_relay[148] <Notice>: syslog_relay found the ASL prompt. Starting...

info: [IOS_SYSLOG_ROW ] Aug  2 12:19:25 kebide-iPhone kernel[0] <Notice>: flow_divert_token_set (0): Failed to get the key unit from the token: 22
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:23 kebide-iPhone lockdownd[26] <Error>: Could not set socket option SO_OPPORTUNISTIC: Invalid argument
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:25 kebide-iPhone kernel[0] <Notice>: flow_divert_token_set (0): Failed to get the key unit from the token: 22

info: [IOS_SYSLOG_ROW ] Aug  2 12:19:23 kebide-iPhone lockdownd[26] <Error>: Could not set socket option SO_OPPORTUNISTIC: Invalid argument
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:25 kebide-iPhone kernel[0] <Notice>: flow_divert_token_set (0): Failed to get the key unit from the token: 22
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:23 kebide-iPhone lockdownd[26] <Error>: Could not set socket option SO_OPPORTUNISTIC: Invalid argument
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:25 kebide-iPhone kernel[0] <Notice>: flow_divert_token_set (0): Failed to get the key unit from the token: 22
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:23 kebide-iPhone lockdownd[26] <Error>: Could not set socket option SO_OPPORTUNISTIC: Invalid argument
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:23 kebide-iPhone SpringBoard[43] <Warning>: Entitlement com.apple.multitasking.termination required to kill applications.
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:25 kebide-iPhone kernel[0] <Notice>: xpcproxy[3193] Container: /private/var/mobile/Containers/Data/Application/23B5CBCE-DF1A-4A0C-83BC-3A813E07D273 (sandbox)
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:25 kebide-iPhone kernel[0] <Notice>: flow_divert_token_set (0): Failed to get the key unit from the token: 22
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:23 kebide-iPhone lockdownd[26] <Error>: Could not set socket option SO_OPPORTUNISTIC: Invalid argument
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Error>: assertion failed: 12B435: libxpc.dylib + 51947 [E83F44AC-48AF-3662-929E-FB7538661BB3]: 0x7d
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone Unknown[3193] <Error>:
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:25 kebide-iPhone kernel[0] <Notice>: flow_divert_token_set (0): Failed to get the key unit from the token: 22
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone lockdownd[26] <Error>: Could not set socket option SO_OPPORTUNISTIC: Invalid argument
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone ScriptAgent[3194] <Warning>: UIAutomation is not enabled on this device. UIAutomation must be enabled in Settings.
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone notification_proxy[147] <Error>: 0x481000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone locationd[64] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: -[AppDelegate application:didFinishLaunchingWithOptions:] : 56
info: [IOS_SYSLOG_ROW ] app_version: 1.0.0
info: [IOS_SYSLOG_ROW ] app_client: iPhone_OS
info: [IOS_SYSLOG_ROW ] device_id: 633D08D9-9000-4A55-B54F-D848AC0D54CF
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone notification_proxy[147] <Error>: 0x585000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: seal_01
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: seal_02
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: seal_03
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: seal_04
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: seal_05
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: seal_06
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: seal_07
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: seal_08

info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: seal_09
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: seal_10
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: seal_11
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: seal_12
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: currentIndex = 0
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: currentIndex = 1
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: currentIndex = 2
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: currentIndex = 3
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: currentIndex = 4
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: currentIndex = 5
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: currentIndex = 6
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: currentIndex = 7
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: currentIndex = 8
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: currentIndex = 9
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: currentIndex = 10
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: currentIndex = 11
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: <WORKFLOW>: init sdk[1.2.8.22] with appid[900004427] in the bundle [com.ooch.woqu] on the device[iPhone5,2, 8.1.1 (12B435)]

info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: <WORKFLOW>: sdk install signal handler success, exception handler success
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: <WORKFLOW>: sdk open udid: 9E9EC207-7EC6-44C8-864F-98CD52D6BEC7, qimei: (null)
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: please set valid callback method 0
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: set callback method for test
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: sdk has set callback method: 1579289
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone ScriptAgent[3194] <Warning>: UIAutomation is not enabled on this device. UIAutomation must be enabled in Settings.
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone ScriptAgent[3194] <Error>: *** Terminating app due to uncaught exception 'kUIAExceptionUIAutomationNotEnabled', reason: 'UIAutomation is not enabled on this device. UIAutomation must be enabled in Settings.'
info: [IOS_SYSLOG_ROW ] *** First throw call stack:
info: [IOS_SYSLOG_ROW ] (0x2afb949f 0x3876fc8b 0x2afb93e5 0x1ed47d 0x1ed393 0x17b8e3 0x2bcc9d6f 0x2af7fd57 0x2af7f167 0x2af7d7cd 0x2aecb3c1 0x2aecb1d3 0x2bc04bfd 0x2bc530bd 0x6a7c1 0x38cefaaf)
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone ReportCrash[3195] <Error>: task_set_exception_ports(B07, 400, D03, 0, 0) failed with error (4: (os/kern) invalid argument)
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone ReportCrash[3195] <Notice>: ReportCrash acting against PID 3194
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone ReportCrash[3195] <Notice>: Formulating crash report for process ScriptAgent[3194]
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone 哎玛机器人[3193] <Warning>: 8.100000
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone ReportCrash[3195] <Notice>: Saved report to /var/mobile/Library/Logs/CrashReporter/ScriptAgent_2015-08-02-121924_kebide-iPhone.ips
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone SpringBoard[43] <Warning>: BSXPCMessage received error for message: Connection invalid
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone SpringBoard[43] <Warning>: Unable to get short BSD proc info for 3193: No such process
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone SpringBoard[43] <Warning>: Unable to get short BSD proc info for 3193: No such process

info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone SpringBoard[43] <Warning>: Unable to get short BSD proc info for 3193: No such process
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone com.apple.xpc.launchd[1] (UIKitApplication:com.ooch.woqu[0x44e2][3193]) <Notice>: Service exited due to signal: Killed: 9
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone SpringBoard[43] <Warning>: Application 'UIKitApplication:com.ooch.woqu[0x44e2]' exited abnormally via signal.
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone assertiond[58] <Warning>: Could not set priority of <BKNewProcess: 0x17d72730; com.ooch.woqu; pid: 3193; hostpid: -1> to 2, priority: No such process
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone assertiond[58] <Warning>: Could not set priority of <BKNewProcess: 0x17d72730; com.ooch.woqu; pid: 3193; hostpid: -1> to 4096, priority: No such process
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone SpringBoard[43] <Warning>: Unable to deliver -[UIRemoteApplication showTopMostMiniAlertWithSynchronizationPort:] message to port 0: (ipc/send) invalid destination port
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:24 kebide-iPhone UserEventAgent[17] <Warning>: id=com.ooch.woqu pid=3193, state=0
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:25 kebide-iPhone locationd[64] <Notice>: Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:25 kebide-iPhone DTMobileIS[165] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:25 kebide-iPhone DTMobileIS[165] <Warning>: Could not create service named com.apple.dt.Xcode.WatchProcessControl
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:25 kebide-iPhone DTMobileIS[165] <Warning>: Could not create service named com.apple.instruments.server.services.launchdaemon
info: [IOS_SYSLOG_ROW ] Aug  2 12:19:25 kebide-iPhone notification_proxy[147] <Error>: 0x585000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

info: [IOS_SYSLOG_ROW ] Aug  2 12:19:25 kebide-iPhone notification_proxy[147] <Error>: 0x585000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

**Comment by gongxiujin** [comment]
Always open the app, shut, open and close。I don't know how to fix。Pray god to guide

**Comment by gongxiujin** [comment]
ok  I konw how fix it

**Comment by omershatil** [comment]
hello! I get the same error. Can you please let me know how you resolved it? Otherwise, I'll have to pray to god also...
