### ISSUE TITLE
MobileElement.findElement() does not work for native iOS Apps with any locator strategy

### ISSUE THREAD

**Issue by abhivaikar** [appium/appium#5460]
I am trying to find an element inside a webelement and it's not working from automation code as well as from Appium Inspector

**Setup:**
1. Appium 1.4.8
2. XCode 6.3.2
3. iOS Simulator: iPhone with iOS 8.3
4. App: Native iOS App

**Locating strategies tried:** Xpath, name, class, ios uiautomation

Element hierarchy is as in the image:
<img width="721" alt="screen shot 2015-08-03 at 12 18 04 pm" src="https://cloud.githubusercontent.com/assets/1690028/9032196/af4aebde-39d9-11e5-8833-4381a5a3d496.png">

**My automation code is as below:**

``` Java
WebElement itemElement = driver.findElements(MobileBy.IosUIAutomation("UIATarget.localTarget().frontMostApp().mainWindow().collectionViews()[0].cells().withPredicate(\"name == 'id_itemSummaryView'\")").get(0);//This will return a single element out of 4 elements
itemElement.findElement(MobileBy.name("id_itemSummaryView")) //throws error
```

OR

``` Java
itemElement.findElement(MobileBy.IosUIAutomation("elements()[0]")); //throws error
```

Even from Appium Inspector, I set "Search from Selected Element" and try finding the element. Doesn't work.
Am I doing something wrong here? Or is this a bug in Appium?

**Comment by sebv** [comment]
Did you switch context? Please read the 'automate hybrid app doc'.

**Comment by abhivaikar** [comment]
Yes. Tried. Changed the context to NATIVE_APP didn't help.

**Comment by sebv** [comment]
If you have a WebElement it is an hybrid app, not a native app.

**Comment by abhivaikar** [comment]
Do you mean that I should use MobileElement instead of WebElement? Does that make a difference considering that MobileElement subclasses RemoteWebElement? I am sure that the view that I am automating is a native view and not a webview.

**Comment by sebv** [comment]
Switch context to "Webview"

**Comment by abhivaikar** [comment]
How is switching to Webview going to help me when the element is a native element? As you can see in the image attached that it's a UIAElement.

**Comment by sebv** [comment]
Sorry confused the driver class with Webview.

**Comment by sebv** [comment]
Hum maybe it is because it is not visible.

**Comment by abhivaikar** [comment]
Just for information sakes, I even tried this:
```Java
MobileElement itemElement = driver.findElements(MobileBy.IosUIAutomation("UIATarget.localTarget().frontMostApp().mainWindow().collectionViews()[0].cells().withPredicate(\"name == 'id_itemSummaryView'\")").get(0);//This will return a single element out of 4 elements. 
//Above driver is of type AppiumDriver<MobileElement>
itemElement.findElement(MobileBy.name("id_itemSummaryView")) // still throws error
```

Also, the element is visible on the inspector app view.

**Comment by sebv** [comment]
If you can it is best to use accessibility ids.

**Comment by abhivaikar** [comment]
The element that I want to find is a dynamically created element. It basically is a list of some items. I don't think I'll be able to find accessibility ids for them. Please check the below screenshot.
<img width="378" alt="screen shot 2015-08-04 at 5 58 32 pm" src="https://cloud.githubusercontent.com/assets/1690028/9060509/393fdff4-3ad2-11e5-9517-3852a3639903.png">

**Comment by abhivaikar** [comment]
@sebv Any updates on this issue?

**Comment by khallbec** [comment]
Looks like Im having the same problem. It was working fine on 1.4.10 I'll revert now. 

it looks like It found my named element "ProductName". see snippet below. but it never clicks on it.

info: [debug] Pushing command to appium work queue: "au.getElementsByName('ProductName')"
info: [debug] Sending command to instruments: au.getElementsByName('ProductName')
info: [debug] [INST] 2015-09-18 14:36:12 +0000 Debug: Got new command 44 from instruments: au.getElementsByName('ProductName')
info: [debug] [INST] 2015-09-18 14:36:12 +0000 Debug: evaluating au.getElementsByName('ProductName')
info: [debug] Socket data received (1027 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":[{"ELEMENT":"19"},{"ELEMENT":"20"},{"ELEMENT":"21"},{"ELEMENT":"22"},{"ELEMENT":"23"},{"ELEMENT":"24"},{"ELEMENT":"25"},{"ELEMENT":"26"},{"ELEMENT":"27"},{"ELEMENT":"28"},{"ELEMENT":"29"},{"ELEMENT":"30"},{"ELEMENT":"31"},{"ELEMENT":"32"},{"ELEMENT":"33"},{"ELEMENT":"34"},{"ELEME
info: [debug] Responding to client with success: {"status":0,"value":[{"ELEMENT":"19"},{"ELEMENT":"20"},{"ELEMENT":"21"},{"ELEMENT":"22"},{"ELEMENT":"23"},{"ELEMENT":"24"},{"ELEMENT":"25"},{"ELEMENT":"26"},{"ELEMENT":"27"},{"ELEMENT":"28"},{"ELEMENT":"29"},{"ELEMENT":"30"},{"ELEMENT":"31"},{"ELEMENT":"32"},{"ELEMENT":"33"},{"ELEMENT":"34"},{"ELEMENT":"35"},{"ELEMENT":"36"},{"ELEMENT":"37"},{"ELEMENT":"38"},{"ELEMENT":"39"},{"ELEMENT":"40"},{"ELEMENT":"41"},{"ELEMENT":"42"},{"ELEMENT":"43"},{"ELEMENT":"44"},{"ELEMENT":"45"},{"ELEMENT":"46"},{"ELEMENT":"47"},{"ELEMENT":"48"},{"ELEMENT":"49"},{"ELEMENT":"50"},{"ELEMENT":"51"},{"ELEMENT":"52"},{"ELEMENT":"53"},{"ELEMENT":"54"},{"ELEMENT":"55"},{"ELEMENT":"56"},{"ELEMENT":"57"},{"ELEMENT":"58"},{"ELEMENT":"59"},{"ELEMENT":"60"},{"ELEMENT":"61"},{"ELEMENT":"62"},{"ELEMENT":"63"},{"ELEMENT":"64"},{"ELEMENT":"65"},{"ELEMENT":"66"},{"ELEMENT":"67"},{"ELEMENT":"68"},{"ELEMENT":"69"},{"ELEMENT":"70"},{"ELEMENT":"71"},{"ELEMENT":"72"},{"ELEMENT":"73"},{"ELEMENT":"74"},{"ELEMENT":"75"},{"ELEMENT":"76"},{"ELEMENT":"77"}],"sessionId":"4e93a995-c978-4b46-8c6b-686d36a00588"}
info: <-- POST /wd/hub/session/4e93a995-c978-4b46-8c6b-686d36a00588/elements 200 630.241 ms - 1076 {"status":0,"value":[{"ELEMENT":"19"},{"ELEMENT":"20"},{"ELEMENT":"21"},{"ELEMENT":"22"},{"ELEMENT":"23"},{"ELEMENT":"24"},{"ELEMENT":"25"},{"ELEMENT":"26"},{"ELEMENT":"27"},{"ELEMENT":"28"},{"ELEMENT":"29"},{"ELEMENT":"30"},{"ELEMENT":"31"},{"ELEMENT":"32"},{"ELEMENT":"33"},{"ELEMENT":"34"},{"ELEMENT":"35"},{"ELEMENT":"36"},{"ELEMENT":"37"},{"ELEMENT":"38"},{"ELEMENT":"39"},{"ELEMENT":"40"},{"ELEMENT":"41"},{"ELEMENT":"42"},{"ELEMENT":"43"},{"ELEMENT":"44"},{"ELEMENT":"45"},{"ELEMENT":"46"},{"ELEMENT":"47"},{"ELEMENT":"48"},{"ELEMENT":"49"},{"ELEMENT":"50"},{"ELEMENT":"51"},{"ELEMENT":"52"},{"ELEMENT":"53"},{"ELEMENT":"54"},{"ELEMENT":"55"},{"ELEMENT":"56"},{"ELEMENT":"57"},{"ELEMENT":"58"},{"ELEMENT":"59"},{"ELEMENT":"60"},{"ELEMENT":"61"},{"ELEMENT":"62"},{"ELEMENT":"63"},{"ELEMENT":"64"},{"ELEMENT":"65"},{"ELEMENT":"66"},{"ELEMENT":"67"},{"ELEMENT":"68"},{"ELEMENT":"69"},{"ELEMENT":"70"},{"ELEMENT":"71"},{"ELEMENT":"72"},{"ELEMENT":"73"},{"ELEMENT":"74"},{"ELEMENT":"75"},{"ELEMENT":"76"},{"ELEMENT":"77"}],"sessionId":"4e93a995-c978-4b46-8c6b-686d36a00588"}
info: --> POST /wd/hub/session/4e93a995-c978-4b46-8c6b-686d36a00588/element/19/click {"id":"19"}
info: [debug] Pushing command to appium work queue: "au.tapById('19')"
info: [debug] Sending command to instruments: au.tapById('19')
info: [debug] [INST] 2015-09-18 14:36:12 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-09-18 14:36:12 +0000 Debug: Lookup returned [object UIACollectionCell] with the name "ProductName" (id: 19).

**Comment by khallbec** [comment]
FYI, downgrading to 1.4.10 makes it work again.

**Comment by khallbec** [comment]
try this.
I have a problem with it trying to get more results but it might work for you
public static void tapOnElementNumber(String element,int position) {
        List<WebElement> we  = driver.findElements(name(element));
        WebElement item = we.get(position);
        item. click();
    }

**Comment by SrinivasanTarget** [comment]
'Name' locator strategy is deprecated @khallbec @abhivaikar Please check this out https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/finding-elements.md

Also try the same in latest version of Appium 1.5, if you still face any issues please raise it with logs in form as gist.

@imurchie Can we please close this
