### ISSUE TITLE
`driver.switch_to.alert.accept()` dismisses alert in iOS 9

### ISSUE THREAD

**Issue by amake** [appium/appium#5463]
Using Appium v1.4.8 (REV 29b2c4d02dd4d41b91c08e0f4b25d24d32051d17) with Xcode 7b4 I find that calling `driver.switch_to.alert.accept()` (Python bindings) results in the dialog being _dismissed_ instead of accepted on the iOS 9 Simulator. This happens on iOS 9 only; the same setup but running the iOS 8.4 Simulator results in the expected behavior.

**Comment by sebv** [comment]
Sounds like a bug, do you have the logs.

**Comment by amake** [comment]
Here is a log in which I launch my app, then after a successful launch (`webdriver.Remote()` constructor returns and the app is visually confirmed to be running) I run `driver.switch_to.alert.accept()` twice:
https://gist.github.com/amake/2483fd68807d1c4ef1e5

Note that the first time it claims that "`Waited for a while and alert didn't close, moving on`" but this is false—the alert disappears in a timely fashion.

I see that `alert.accept()` ends up translating to `target.frontMostApp().alert().defaultButton().tap()`; perhaps the "default" button has changed in iOS 9? I tried to follow up on this but I wasn't sure on which layer this part takes place.

**Comment by SquareTheBase** [comment]
I see the same with apps built in XCode7 Beta 6.  Any one know of a workaround yet?

**Comment by philyates2000** [comment]
Getting this with Xcode 7 at the moment. Have auto accept alerts on and when accepting access to the camera roll it is cancelling the alert but not accepting it. This is causing tests to fail as photos are not available with they should be.

info: [debug] [INST] 2015-09-23 11:51:41 +0000 Debug: target.frontMostApp().alert().defaultButton().tap()
info: [debug] [INST] 2015-09-23 11:51:41 +0000 Debug: Waiting for alert to close...
info: [debug] [INST] 2015-09-23 11:51:42 +0000 Debug: Waiting for alert to close...
info: [debug] [INST] 2015-09-23 11:51:42 +0000 Debug: Waiting for alert to close...
info: [debug] [INST] 2015-09-23 11:51:42 +0000 Debug: Waiting for alert to close...
info: [debug] [INST] 2015-09-23 11:51:42 +0000 Debug: Waiting for alert to close...
info: [debug] [INST] 2015-09-23 11:51:43 +0000 Debug: Waiting for alert to close...
info: [debug] [INST] 2015-09-23 11:51:43 +0000 Debug: Waiting for alert to close...
info: [debug] [INST] 2015-09-23 11:51:43 +0000 Debug: Waiting for alert to close...
info: [debug] [INST] 2015-09-23 11:51:44 +0000 Debug: Waiting for alert to close...
info: [debug] [INST] 2015-09-23 11:51:44 +0000 Debug: Waiting for alert to close...
info: [debug] [INST] 2015-09-23 11:51:44 +0000 Debug: Waited for a while and alert didn't close, moving on

**Comment by SquareTheBase** [comment]
There's a similar issue with Apple's XCTest UI Testing framework in XC7.  A radar was opened for the framework failing on alert dismissals:

 http://openradar.appspot.com/radar?id=4979891669827584

**Comment by marciok** [comment]
An ugly workaround that I'm using: `execute_script 'target.frontMostApp().alert().buttons()[1].tap()'`. Note: this is ruby. 

I hope it helps.

**Comment by eugenluca** [comment]
Hi guys,

I think I found the problem with the alert.

In the node_modules/appium-uiauto/uiauto/lib/mechanic-ext/alert-ext.js file you will find:

// iOS9.1 returns 'cancel' as the default button.
if ((parseFloat($.systemVersion) >= 9.1 && buttonCount > 0) ||

The problem here is that cancel is also default on iOS 9.0v so the right code should be

// iOS9.0 returns 'cancel' as the default button.
if ((parseFloat($.systemVersion) >= 9.0 && buttonCount > 0) ||

This fixed the issue for me :D

**Comment by rams78** [comment]
https://github.com/eugenluca, kudos for spotting this. Looks like a typo, because 9.1 is not out yet.

Somehow, patching the alert-ext.js alone did not cut if for me, alert was not dismissed automatically.
I also had to specify 'waitForAppScript': '$.delay(5000); $.acceptAlert(); true;' - and then it started working as expected.

**Comment by appiumnovice** [comment]
In the release 1.4.13 of Appium.app for Mac, the previous correction was not enough for me.
The objet "acceptButton" is never null because initialize at the beginning of the function.

I finally replaced

        var acceptButton = alert.defaultButton();
        var buttonCount = alert.buttons().length;
        // iOS9.1 returns 'cancel' as the default button.
        if ((parseFloat($.systemVersion) >= 9.1 && buttonCount > 0) ||
            (acceptButton.isNil() && buttonCount > 0)) {
          // last button is accept
          acceptButton = alert.buttons()[buttonCount - 1];
        }
        acceptButton.tap();

by
        var acceptButton = null;
        var buttonCount = alert.buttons().length;
        // iOS9.1 returns 'cancel' as the default button.
        if ((parseFloat($.systemVersion) >= 9.0 && buttonCount > 0) ||
            (acceptButton.isNil() && buttonCount > 0)) {
          // last button is accept
          acceptButton = alert.buttons()[buttonCount - 1];
        } else{
          alert.defaultButton();
        }
        acceptButton.tap();

**Comment by savishy** [comment]
Is this issue still valid? 
I have two separate devices. I tried `driver.manage.alerts.accept()` first on iPhone 6+ / iOS 9.0.2 where the **alert was not accepted.**
Then I tried the same code (no changes) on an iPhone 5 / iOS 9.2. 
The alert **was accepted properly.**

**Comment by smccarthy** [comment]
Has anyone tried 9.3 ? My autoAcceptAlerts is not working on 9.3, and thinking maybe it acts similar to 9.0 ?

**Comment by poojatrivedi7** [comment]
Thanks @eugenluca - changing the alert-ext.js worked very well for us!

**Comment by LayMuiToh** [comment]
Hi, I add the "autoAcceptAlerts": "true" into the desired caps in the package.json file
it works but my app will disappear. I want my app to stay and allow me to continue the automation.
any idea?
