### ISSUE TITLE
swipe(SwipeElementDirection.UP, 1000) for Real Device is not working

### ISSUE THREAD

**Issue by VTINFOJames** [appium/appium#5465]
I am testing a Native iOS application on a real device and swiping DOWN on a UIAPicker within a UIAPickerWheel is working however, swiping UP on the same picker is not.  Any help would be appreciated. Here is my code:

        WebElement picker = driver.findElement(By.className("UIAPicker"));
       ((MobileElement) picker).swipe(SwipeElementDirection.DOWN, 1000); // THIS WORKS
       ((MobileElement) picker).swipe(SwipeElementDirection.UP, 1000); // THIS DOES NOT WORK

iOS 8.4, Appium Version 1.4.8

**Comment by sebv** [comment]
Does up by 100 woks?

Otherwise the standard method with picker wheels is to use sendKeys.

**Comment by VTINFOJames** [comment]
Using (SwipeElementDirection.Up, 100) fails with a WebDriver exception:
"info: [debug] [INST] 2015-08-06 11:28:16 +0000 Error: VerboseError: duration value must be greater than or equal to 0.5 or less than 60"
So I tried: 
((MobileElement) picker).swipe(SwipeElementDirection.UP, 500);
 and:
((MobileElement) picker).swipe(SwipeElementDirection.DOWN, 500);

The UP function did not fail but had the same result as using 1000 where the entire UIAPicker was being selected and swiped instead of the data wheel. The DOWN function works.

Using SendKeys just flat out failed even when using the xpath. 

It seems the problem is a known issue: https://github.com/appium/appium/issues/4106
I am seeing the same error with : "value":"- selectValue requires a valid value"

It is strange that DOWN works but UP does not... I really hope that this is eventually fixed for the className locator strategy.

**Comment by VTINFOJames** [comment]
Update: I just tried using sendKeys for a particular date String and it worked. So now my test is able to scroll DOWN to a value with (SwipeElementDirection.DOWN, 1000) and then move UP to a given date using SendKeys("dateString"). This is enough for me to verify that the picker wheel can be swiped, verify  that it contains multiple values and then position back to a desired date.
