### ISSUE TITLE
Appium server sending error when iOS keyboard is well hidden

### ISSUE THREAD

**Issue by popei69** [appium/appium#5468]
Hi guys,

Basically, I use `driver.hideKeyboard("Hide keyboard");` to hide keyboard and get access to uibutton under it.

On the UI, it works fine, the keyboard is hidden, but Appium sends back an error.

```
info: [debug] Pushing command to appium work queue: "au.hideKeyboard('pressKey','Hide keyboard')"
info: [debug] Sending command to instruments: au.hideKeyboard('pressKey','Hide keyboard')
info: [debug] [INST] 2015-08-05 11:19:26 +0000 Debug: Got new command 32 from instruments: au.hideKeyboard('pressKey','Hide keyboard')
info: [debug] [INST] 2015-08-05 11:19:26 +0000 Debug: evaluating au.hideKeyboard('pressKey','Hide keyboard')
info: [debug] [INST] 2015-08-05 11:19:26 +0000 Debug: Hiding keyboard with keyName Hide keyboard
info: [debug] [INST] 2015-08-05 11:19:26 +0000 Debug: target.frontMostApp().keyboard().buttons()["Hide keyboard"].tap()

info: [debug] Socket data received (50 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":17,"value":"Failed to hide keyboard."}
info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"Failed to hide keyboard."},"sessionId":"e8ea0130-3b17-405a-b329-70b61861d461"}
info: <-- POST /wd/hub/session/e8ea0130-3b17-405a-b329-70b61861d461/appium/device/hide_keyboard 500 17892.863 ms - 185 
info: --> DELETE /wd/hub/session/e8ea0130-3b17-405a-b329-70b61861d461 {}
info: Shutting down appium session
info: [debug] Stopping ios
```

I don't really understand how Appium server can send back an error when the keyboard was hidden. I'm currently using Appium 1.4.8.

Here is more info https://discuss.appium.io/t/hide-keyboard-ios-make-crash-the-app/5486

**Comment by sebv** [comment]
It's cause by this: https://github.com/appium/appium-uiauto/blob/634e52544d73d32d1c247ffbb5bc7642ef26096e/uiauto/lib/mechanic-ext/keyboard-ext.js#L89

Maybe it is just slowness.

**Comment by savishy** [comment]
Actually, it does not make sense why "Hide keyboard" works. In my situation, the keyboard has a "return" button. Pressing this manually hides the keyboard. But `driver.hideKeyboard("return")` is returning "Invalid key value".
