### ISSUE TITLE
Could not launch Safari on iOS Simulator (No SafariLauncher found)

### ISSUE THREAD

**Issue by DevilatorX** [appium/appium#5469]
I'm trying to start Safari on a simulator (iPhone 4S iOS 8.4). Appium is 1.4.8. Using Xcode 6.4. I get an error indicating that I'm missing SafariLauncher.zip.

Heres the log:
 users-MacBook-Pro:appium user$ appium
info: Welcome to Appium v1.4.8 (REV c8179bd8352d3c62d98fa58b324491230df9342a)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"udid":"624C18AC-F20A-4DDE-89CE-095D82EC338F","platformVersion":"8.4","browserName":"Safari","platformName":"iOS","deviceName":"'iPhone 4s'"}}
info: Client User-Agent string: Python-urllib/2.7
info: [debug] Configuring Safari session
info: [debug] Using local .zip from command line: /usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip
info: [debug] Copying local zip to tmp dir
info: [debug] Got configuration error, not starting session
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'
info: [debug] Error: ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'
    at Error (native)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip')","errno":-2,"code":"ENOENT","path":"/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip","origValue":"ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'"},"sessionId":null}
info: <-- POST /wd/hub/session 500 18.370 ms - 411

**Comment by sebv** [comment]
Is the file `/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'` there? How did you install appium?

**Comment by DevilatorX** [comment]
Nope. There wasnt even Safari launcher folder for me. I installed with "npm install -g appium"
