### ISSUE TITLE
Unsupported OS/browser/version/device combo: OS: 'unspecified', Browser: 'iphone', Version: '8.4.', Device: 'iPhone Simulator'

### ISSUE THREAD

**Issue by uscengineer** [appium/appium#5472]
My tests were running fine for a couple days. Went back to demo the tests and I started getting the error below. I have tried different devices and version combinations but keep getting the same error. 
Ruby: 2.1.3
ruby_lib: 7.0.0
ruby_console: 1.0.4
xcode: 6.4

This is my appium.txt file
[caps]
deviceName  = "iPhone Simulator"
platformVersion  = "8.4"
platformName  = "iOS"
app  = "/Users/automation/Desktop/UICatalog.app"

~/repos/test-app/iOS $ arc
appium.txt path: /Users/automation/repos/test-app/iOS/appium.txt
Exists? true
Loading /Users/automation/repos/test-app/iOS/appium.txt
{
    :caps => {
           :platformName => "ios",
                    :app => "~/Desktop/UICatalog.app",
             :deviceName => "iPhone Simulator",
        :platformVersion => "8.4",
             :showIOSLog => true
    }
}
{
    :caps => {
        :newCommandTimeout => 999999,
             :platformName => "ios",
                      :app => "/Users/automation/Desktop/UICatalog.app",
               :deviceName => "iPhone Simulator",
          :platformVersion => "8.4",
               :showIOSLog => true
    }
}
Debug is: true
Device is: ios
post /session
{
    :desiredCapabilities => {
        :newCommandTimeout => 999999,
             :platformName => "ios",
                      :app => "/Users/automation/Desktop/UICatalog.app",
               :deviceName => "iPhone Simulator",
          :platformVersion => "8.4",
               :showIOSLog => true
    }
}

Unsupported OS/browser/version/device combo: OS: 'unspecified', Browser: 'iphone', Version: '8.4.', Device: 'iPhone Simulator'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/appium_lib-7.0.0/lib/appium_lib/common/patch.rb:118:in `raw_execute'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:122:in `create_session'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/bridge.rb:87:in `initialize'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/driver.rb:52:in `new'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/common/driver.rb:52:in `for'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver.rb:86:in `for'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/appium_lib-7.0.0/lib/appium_lib/driver.rb:484:in `start_driver'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/appium_console-1.0.4/lib/start.rb:16:in `<top (required)>'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/pry-0.10.1/lib/pry/pry_class.rb:91:in `require'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/pry-0.10.1/lib/pry/pry_class.rb:91:in `block in load_requires'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/pry-0.10.1/lib/pry/pry_class.rb:90:in `each'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/pry-0.10.1/lib/pry/pry_class.rb:90:in `load_requires'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/pry-0.10.1/lib/pry/pry_class.rb:128:in `initial_session_setup'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/pry-0.10.1/lib/pry/cli.rb:206:in `block in <top (required)>'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/pry-0.10.1/lib/pry/cli.rb:83:in `call'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/pry-0.10.1/lib/pry/cli.rb:83:in `block in parse_options'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/pry-0.10.1/lib/pry/cli.rb:83:in `each'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/pry-0.10.1/lib/pry/cli.rb:83:in `parse_options'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/appium_console-1.0.4/lib/appium_console.rb:49:in `<module:Console>'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/appium_console-1.0.4/lib/appium_console.rb:31:in `<module:Appium>'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/appium_console-1.0.4/lib/appium_console.rb:30:in `<top (required)>'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/appium_console-1.0.4/bin/arc:66:in `require'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/gems/appium_console-1.0.4/bin/arc:66:in `<top (required)>'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/bin/arc:23:in `load'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/bin/arc:23:in `<main>'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/bin/ruby_executable_hooks:15:in `eval'
	from /Users/automation/.rvm/gems/ruby-2.1.3@test-app/bin/ruby_executable_hooks:15:in `<main>'

**Comment by sebv** [comment]
Could you provide server log?

**Comment by uscengineer** [comment]
It does not reach the appium_server. How can I generate a log from arc?

**Comment by uscengineer** [comment]
Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --debug-log-spacing --platform-version "8.1" --platform-name "iOS" --show-ios-log --default-device

info: Welcome to Appium v1.4.8 (REV c8179bd8352d3c62d98fa58b324491230df9342a)

info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"platformName":"iOS","platformVersion":"8.1","defaultDevice":true,"showIOSLog":true,"defaultCommandTimeout":7200,"debugLogSpacing":true}
info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}

info: <-- GET /wd/hub/status 200 7.203 ms - 104 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"}}}

This is what i see on the Appium Server when it starts up. platformVersion is 8.1 when it starts up. How can I change this in the app? I don't see anywhere to change this in General Settings or Developer Settings.

**Comment by sebv** [comment]
Looks like it is a arc issue.

**Comment by uscengineer** [comment]
@sebv It was an arc issue. Thanks!
