### ISSUE TITLE
Using Appium Inspector in Windows

### ISSUE THREAD

**Issue by purvesha** [appium/appium#5475]
I want to write the automation script for a web app using appium. I am a beginner and i am not aware of the same, can some one provide the detailed description on how to write the script.
My requirements are
open the chrome browser on my mobile
open the website say www.abc.com
login with my cresdetials
logout

If someone can help me, It will be of much help

Thanks

**Comment by sebv** [comment]
Here is the place for this kind of questions: https://discuss.appium.io/
