### ISSUE TITLE
Appium v1.4.8 cannot hide keyboard in iOS with driver.hideKeyboard(HideKeyboardStrategy.PRESS_KEY, "Go");

### ISSUE THREAD

**Issue by utkarsha1** [appium/appium#5476]
Code:
```
public void login() throws Exception {
        MobileElement signInBtn = waitAndFindUtil.findElement(MobileBy.name("Sign In"), driver);
        signInBtn.tap(2, 2);

        IOSElement emailTxt = (IOSElement) waitAndFindUtil.findElement(MobileBy.name("email"), driver);
        emailTxt.setValue("XXXXX");
        IOSElement pwdTxt = (IOSElement) waitAndFindUtil.findElement(MobileBy.name("pwd"), driver);
        pwdTxt.setValue("XXXXX");
        driver.hideKeyboard(HideKeyboardStrategy.PRESS_KEY, "Go");
        IOSElement loginBtn = (IOSElement) waitAndFindUtil.findElement(MobileBy.id("loginBtn"), driver);
        System.out.println(loginBtn.isEnabled());
        loginBtn.click();
        assertTrue(waitAndFindUtil.findElement(MobileBy.id("XYZ"), driver).isDisplayed());
}
```
Logs:

info: --> POST /wd/hub/session/2c67d6ad-7f4e-4eae-9cb2-87134f4ccfe8/appium/device/hide_keyboard {"strategy":"pressKey","key":"Go"} info: [debug] Pushing command to appium work queue: "au.hideKeyboard('pressKey','Go')" info: [debug] Sending command to instruments: au.hideKeyboard('pressKey','Go')
info: [debug] [INST] 2015-08-05 21:14:19 +0000 Debug: Got new command 11 from instruments: au.hideKeyboard('pressKey','Go')

info: [debug] [INST] 2015-08-05 21:14:19 +0000 Debug: evaluating au.hideKeyboard('pressKey','Go') info: [debug] [INST] 2015-08-05 21:14:19 +0000 Debug: Hiding keyboard with keyName Go

info: [debug] [INST] 2015-08-05 21:14:19 +0000 Debug: target.frontMostApp().keyboard().buttons()["Go"].tap()

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"2c67d6ad-7f4e-4eae-9cb2-87134f4ccfe8"} info: <-- GET /wd/hub/status 200 0.579 ms - 178 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"2c67d6ad-7f4e-4eae-9cb2-87134f4ccfe8"}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"2c67d6ad-7f4e-4eae-9cb2-87134f4ccfe8"} info: <-- GET /wd/hub/status 200 0.874 ms - 178 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"2c67d6ad-7f4e-4eae-9cb2-87134f4ccfe8"}

info: [IOS_SYSLOG_ROW ] Aug 5 17:14:27 XXXX-2.local lsd[77020]: LaunchServices: Currently 0 installed placeholders: (

info: [IOS_SYSLOG_ROW ] )

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"2c67d6ad-7f4e-4eae-9cb2-87134f4ccfe8"} info: <-- GET /wd/hub/status 200 0.763 ms - 178 {"status":0,"value":{"build":{"version":"1.4.8","revision":"c8179bd8352d3c62d98fa58b324491230df9342a"},"isShuttingDown":false},"sessionId":"2c67d6ad-7f4e-4eae-9cb2-87134f4ccfe8"}

info: [debug] [INST] 2015-08-05 21:14:36 +0000 Error: VerboseError: Failed to hide keyboard.

info: [debug] Socket data received (50 bytes)

info: [debug] Socket data being routed. info: [debug] Got result from instruments: {"status":17,"value":"Failed to hide keyboard."} info: [debug] Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"Failed to hide keyboard."},"sessionId":"2c67d6ad-7f4e-4eae-9cb2-87134f4ccfe8"} info: <-- POST /wd/hub/session/2c67d6ad-7f4e-4eae-9cb2-87134f4ccfe8/appium/device/hide_keyboard 500 18467.759 ms - 185 info: --> DELETE /wd/hub/session/2c67d6ad-7f4e-4eae-9cb2-87134f4ccfe8 {} info: Shutting down appium session info: [debug] Stopping ios

**Comment by sebv** [comment]
Could you give more context:
Does the go key exists?
Did the keyboard disappeared?

**Comment by utkarsha1** [comment]
Hi, yes the 'Go' key does exist. Also when the command got sent to
instruments it looked like it tapped as I watched on the simulator. But the
keyboard was still there (never hidden), the js failed and the app crashed.
I was testing against a native ios app.

**Comment by SrinivasanTarget** [comment]
@triager please close
