### ISSUE TITLE
Update chromedriver to latest version

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5477]
I'm seeing a bunch of `chrome not reachable` errors on Sauce. It'd be nice if we could update chromedriver to the latest version to increase stability.

https://github.com/appium/appium/issues/5450

```
"Selenium::WebDriver::Error::WebDriverError:
       timed out after 30 seconds (timeout: 30) (Error while waiting for Protractor to sync with the page: chrome not reachable
         (Session info: chrome=40.0.2214.109)
         (Driver info: chromedriver=2.15.322439 (8e31f8da05131cf34e45f79e9b22c7b4e149f8d9),platform=Linux 3.13.0-34-generic x86))"
https://saucelabs.com/beta/tests/62dc8b3bf7264a1d98ad763003eb89c2/commands
```

**Comment by bootstraponline** [comment]
chromedriver [2.17](http://chromedriver.storage.googleapis.com/index.html?path=2.17/) is out. appium appears to ship with chromedriver 2.15.

**Comment by sebv** [comment]
ping @moizjv should be automatic when new appium version is released on sauce.

**Comment by bayandin** [comment]
There was problem with updating chromedriver to 2.16: https://github.com/appium/appium/pull/5232

**Comment by bootstraponline** [comment]
The issues appear limited to emulators which sauce doesn't support for running chrome. Maybe appium needs two chromedrivers, one for emulators and one for physical devices?

**Comment by moizjv** [comment]
pinging @imurchie

**Comment by bootstraponline** [comment]
The out of date chromedriver issue is making it impossible for me to run Android automation on real devices with recent versions of the chrome browser.

I keep seeing errors like this:

```
Timed out receiving message from renderer: 54.028 (Selenium::WebDriver::Error::TimeOutError)
  (Session info: chrome=44.0.2403.133)
  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Linux 3.11.0-26-generic x86_64)
```

The website doesn't even load.

Chromedriver is up to [2.18](http://chromedriver.storage.googleapis.com/index.html?path=2.18/), appium is a full 3 versions behind.

**Comment by bootstraponline** [comment]
I'm reviewing the [release notes](https://sites.google.com/a/chromium.org/chromedriver/downloads) and Google has made changes to specifically address these kinds of reliability issues. The version shipped in appium is effectively abandonware.

> Latest Release: ChromeDriver 2.18
> 
> Changes include many bug fixes that allow ChromeDriver to work more reliably with Chrome 44+.
> 
> The latest version is recommended, and bugs will not be fixed in previous versions.
>
> https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium-chromedriver/commit/9ceea1b007b0ef3183d3a44d10c352f4e5235157

https://sites.google.com/a/chromium.org/chromedriver/downloads

Closing this since our recent latest version sync up with chrome driver latest version.Closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close
