### ISSUE TITLE
Unable to identify UI Elements in android

### ISSUE THREAD

**Issue by tarunHub** [appium/appium#5481]
Using Appium for automating Android Native app. 
I am identifying elements using android UIAutomator
Issue : I have eleven android textview fields which changes daily.
Issue is i am unable to read their values as all the eleven fields have same classname and same resource -id. 
Then i tried using Xpath but what i saw was when i navigate to the textView all the textviews have same index value resulting in all 11 textviews have same Xpath.
Now i am unable to identify elements. Kindly suggest.

**Comment by sebv** [comment]
Please go to https://discuss.appium.io/
