### ISSUE TITLE
scroll in android

### ISSUE THREAD

**Issue by tarunHub** [appium/appium#5482]
more issue : 
suppose i have 10 textviews. five are on the screen and five appears after scrolling down.
all 10 textviews have same classname and resourceid.
using class name or resource id and storing them in  List i am only able to get values of 5 elements which are visible on the screen and i am not able to get values of other five which needs scrolling to be visible on screen.

**Comment by sebv** [comment]
Please go to https://discuss.appium.io/ for general issues.
