### ISSUE TITLE
IOS has web context view present even when there is no webviews

### ISSUE THREAD

**Issue by glorylo** [appium/appium#5486]
When the current screen is in native mode, you can still see other contexts.  This 'causes some confusion in the test client code.  

We see WEBVIEW_33 and NATIVE_APP.  When actually in webview we see something like NATIVE_APP, WEBVIEW_154 and WEBVIEW_33

**Comment by sebv** [comment]
There must be some webviews somehow, could you provide the log.

**Comment by glorylo** [comment]
Just revisiting this now after upgrade to appium 1.4.8.  I don't see this issue.   I had seen in older 1.4 build  where I would see extra webview and on screens that do have an actual one, I see 3.
