### ISSUE TITLE
Cannot unlock screen in iOS device (Simulator)

### ISSUE THREAD

**Issue by igalep** [appium/appium#5487]
Hi ,
I'm trying to lock / unlock iOS simulator's device

driver.lockScreen(10);
Does the job , but the thing is , after the timeout (10s) the device hasn't been unlocked

It stays i locked state .
The appium log :

info: --> POST /wd/hub/session/0d80a422-aadb-47db-a1cd-2a269226756e/appium/device/lock {"seconds":10}

info: [debug] Pushing command to appium work queue: "au.lock(10)"

info: [debug] Sending command to instruments: au.lock(10)

info: [debug] [INST] 2015-08-06 14:50:16 +0000 Debug: Got new command 9 from instruments: au.lock(10)

info: [debug] [INST] 2015-08-06 14:50:16 +0000 Debug: evaluating au.lock(10)

info: [debug] [INST] 2015-08-06 14:50:16 +0000 Debug: target.lockForDuration("10")

info: [debug] [INST] 2015-08-06 14:50:27 +0000 Debug: target.springboard().mainWindow().scrollViews().firstWithPredicate("ANY elements.name == 'SlideToUnlock' OR ANY elements.name == 'SlideToSetup'").dragInsideWithOptions({endOffset:{x:0.90,y:0.90}}, duration:"0.5", startOffset:{x:0.10,y:0.90}}})

info: [debug] [INST] 2015-08-06 14:50:29 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-08-06 14:50:29 +0000 Debug: responding with:

info: [debug] [INST] 2015-08-06 14:50:29 +0000 Debug: Running system command #10: Applications/Appium.app/Contents/Resources/node/bin/node/Applications/Appium.app/Contents/Resurces/node_modules/appium/node_modules/appium uiauto/bin/command-proxy-client.js/tmp/instruments_sock 2,{"status":0,"value":false}...

Any idea how to unlock the screen ? or what I'm doing wrong ?

**Comment by sebv** [comment]
Cannot do much without reproing, but try to check if those elements exists: `SlideToUnlock` `SlideToSetup`.

**Comment by igalep** [comment]
The elements are exists , I was wonder , the "driver.lockScreen(10);" actually unlock the screen back to the application's state ? or it's just unlock it to the screen where I actually need to swipe the screen to the right ? 

The "SlideToUnlock" element does exist , but the problem is I'm not able to "move" it to the right...

**Comment by sebv** [comment]
If you cannot move it the automation cannot either.

**Comment by igalep** [comment]
I can move it manually on real device , simulator but by using appium it's just doesn't work no matter what I've tried ...
This is the screen I getting after the 'driver.lockScreen' being executed.

![screen shot 2015-08-10 at 2 24 36 pm](https://cloud.githubusercontent.com/assets/3533224/9170438/791eed66-3f6b-11e5-91a7-5129102d99e3.png)


I've also tried to swipe with :
driver.swipe
touchAction
...

nothing works for me

**Comment by igalep** [comment]
Anything new with the issue ?

**Comment by SrinivasanTarget** [comment]
@igalep Please try a latest version of appium and it should be working fine.Feel free to reopen the issue with latest logs incase you hit the same again.

**Comment by SrinivasanTarget** [comment]
@triager please close
