### ISSUE TITLE
cannot download appium

### ISSUE THREAD

**Issue by Radzhab** [appium/appium#5489]
https://bitbucket.org/appium/appium.app/downloads/

**Comment by sebv** [comment]
what the problem?

**Comment by victorhazbun87** [comment]
it is not working the appium-1.4.13.dmg link, when it "finishes" downloading it just says unconfirmed download as the file name.

**Comment by panindra1** [comment]
Yes it is not downloading.

**Comment by sfkaos** [comment]
Download using wget according to: 

```
wget https://bitbucket.org/appium/appium.app/downloads/appium-1.4.13.dmg
```

[https://github.com/appium/appium/issues/6038](https://github.com/appium/appium/issues/6038)

**Comment by SrinivasanTarget** [comment]
@triager please close
