### ISSUE TITLE
"mobile: scrollTo" to the last item isn't stable

### ISSUE THREAD

**Issue by IZaiarnyi** [appium/appium#5490]
In ~2% of cases I get such error "Could not scroll element into view: ..." 
Everything is OK, when I change scroll to another element (not the last).
Mac 10.10.4, Appium v1.4.8, Nexus Player Android 5.1.1

```java
        HashMap<String, String> scrollObject = new HashMap<String, String>();
        scrollObject.put("element", ((RemoteWebElement) driver.findElement(scrollableElement)).getId());
        scrollObject.put("text", item);
        driver.executeScript("mobile: scrollTo", scrollObject);
```

**Comment by sebv** [comment]
I think the mobile api has been deprecated.

**Comment by IZaiarnyi** [comment]
What is better to use instead of "mobile: scrollTop"?

**Comment by richardimms** [comment]
So the way I do it, which I'm not saying is the best, is to scroll using driver.sendKeyEvent() the KeyEvent to send being dpad down (driver.sendKeyEvent(20) or dpad up (driver.sendKeyEvent(19). I usually scroll until the element is visible, then select that element. Hopefully this will help.

**Comment by SrinivasanTarget** [comment]
@scottdixon Please close this as this API has been deprecated.

https://github.com/appium/appium/commit/79dad203e26721725a20ba971c231b9868506f5a

@IZaiarnyi Please use TouchActions API.Feel free to raise it again with appium logs as gist.

**Comment by scottdixon** [comment]
@IZaiarnyi - you can reference https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md

Reopen if you get stuck.
