### ISSUE TITLE
Method for getting current application package name

### ISSUE THREAD

**Issue by artkoshelev** [appium/appium#5493]
There is method to get current activity in AndroidDriver:

``` java
driver.currentActivity()
```

depending on application it may return string like `.MainActivity` without package name or full name. It would be nice to have a method to get the package name separately - appium get this information from apk anyway.

**Comment by amedvedjev** [comment]
we used: ((AppiumDriver) driver).getAppStrings() with "bundleIdentifier=" before Appium started itself to include package name into element IDs.

before we used: @FindBy(id = "com.XXXXXX.keyword:id/txt_badge")
now we using only: @FindBy(id = "txt_badge") and Appium adding package name itself.

**Comment by JamesMGreene** [comment]
This drives me crazy as well.

**Comment by selenUser** [comment]
Really need it !!!!

**Comment by imurchie** [comment]
This functionality is available in Appium 1.6.6 beta as of this morning. Unfortunately it will take some time to get a method into the clients, to make it accessible.

**Comment by dpgraham** [comment]
@imurchie Do you want me to do the client updates?

**Comment by raspu** [comment]
There's no equivalent for iOS? (Like getting the bundle id)?
