### ISSUE TITLE
Ubuntu14.04 failed install appium 

### ISSUE THREAD

**Issue by lzhang1** [appium/appium#5499]
xxxx@xxxx:~/appium$ ./reset.sh --android --verbose
* Determining platform
* Platform is linux
---- Resetting / Initializing Appium ----
RESETTING NPM
* Installing new or updated NPM modules (including devDeps)
npm WARN package.json appium@1.4.10 No license field.
npm WARN optional dep failed, continuing udidetect@1.0.7
RESETTING GENERAL
* Setting git revision data
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'core-js/library/fn/is-iterable'
Warning: Task "setGitRev" not found. Use --force to continue.

Aborted due to warnings.
---- FAILURE: reset.sh exited with status 1 ----

**Comment by sasikumarkannaiyan** [comment]
Try to install node using brew, which should solve this problem. Please see the following steps to install brew, node and appium

1. Install Brew 
git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew

# Until LinuxBrew is fixed, the following is required.
# See: https://github.com/Homebrew/linuxbrew/issues/47
nano ~/.bashrc
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH
## Setup linux brew
export LINUXBREWHOME=$HOME/.linuxbrew
export PATH=$LINUXBREWHOME/bin:$PATH
export MANPATH=$LINUXBREWHOME/man:$MANPATH
export PKG_CONFIG_PATH=$LINUXBREWHOME/lib64/pkgconfig:$LINUXBREWHOME/lib/pkgconfig:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=$LINUXBREWHOME/lib64:$LINUXBREWHOME/lib:$LD_LIBRARY_PATH

test the following after logout and login
$ which brew

2. Install Node
brew install node
brew link node

3. Install Appium
npm -g install appium

4. Run appium 
$ appium

Important: Uninstall the node / appium that you have installed previously.

Sasi

**Comment by scottdixon** [comment]
Appium 1.5 has done away with reset.sh

You can install via: `npm install -g appium`
