### ISSUE TITLE
`scroll()` doesn't work after change focus to another window by `window()`

### ISSUE THREAD

**Issue by timqian** [appium/appium#5500]
I am testing chrome44 on android4.2 using `wd.js`, 
After change focus to another window by `window()` commend, the window is focused but not showed up . I am able to do some actions like `title()`, but unable to scroll the page by `scroll()`, unless I open the window by hand.
Have anyone met this problem before?

code:
```
  it("should get the url", function () {
    return driver
    .get("http://admc.io/wd/test-pages/guinea-pig.html")
    //.windowHandle()
    .newWindow('https://www.baidu.com', 'baidu')
    //.windowHandle()
    .newWindow('https://www.timqian.com', 'tim')
    //.windowHandles()
    .window('baidu')
    .title()
    .get('http://afarkas.github.io/lazysizes/')
    .scroll(0, 2000)
});
```

**Comment by scottdixon** [comment]
@timqian - does the issue persist? Have you tried a more recent version of Appium?

**Comment by timqian** [comment]
@scottdixon No, I have not use appium for a long time. Maybe this issue shoud be closed

**Comment by scottdixon** [comment]
Thanks for the update. Reopen if this issue persists.
