### ISSUE TITLE
Appium v1.4.8 : sendKeys is not working on IOS simulators

### ISSUE THREAD

**Issue by utkarsha1** [appium/appium#5501]
Tried platform version 8.1, 8.3, 8.4 iPhone 5, 5s, 6, 6 Plus

When typing in text field with sendKeys("XYZ"), appium logs shows instruments error and app crashes due to kill signal being sent.

Similar problem reported here: https://discuss.appium.io/t/sendkeys-has-stopped-working-after-updating-to-1-4/4662

Appium logs:

    at process._tickDomainCallback (node.js:381:11)
    info: [debug] Socket data received (38 bytes)
    info: [debug] Socket data being routed.
    info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"1"}}
    info: [debug] Responding to client with success: {"status":0,"value":        {"ELEMENT":"1"},"sessionId":"414acb23-5e26-4489-9416-b0ec73a832be"}
info: <-- POST /wd/hub/session/414acb23-5e26-4489-9416-b0ec73a832be/element 200 1597.064 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"414acb23-5e26-4489-9416-b0ec73a832be"}
info: --> POST /wd/hub/session/414acb23-5e26-4489-9416-b0ec73a832be/element/1/value {"id":"1","value":["devtmaadmin@example.com"]}
info: <-- POST /sendKeys 500 1.890 ms - 66 
info: [debug] Responding to client with error: {"status":1,"value":{"message":"undefined status object"},"sessionId":"414acb23-5e26-4489-9416-b0ec73a832be"}
info: <-- POST /wd/hub/session/414acb23-5e26-4489-9416-b0ec73a832be/element/1/value 500 23.048 ms - 109 
info: --> DELETE /wd/hub/session/414acb23-5e26-4489-9416-b0ec73a832be {}
info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments
info: [debug] [INST] 2015-08-13 15:41:05 +0000 Stopped: Script was stopped by the user
info: [IOS_SYSLOG_ROW ] Aug 13 11:41:05  SpringBoard[16671]: Unable to get short BSD proc info for 16704: No such process
info: [IOS_SYSLOG_ROW ] Aug 13 11:41:05  com.apple.CoreSimulator.SimDevice.131ED809-544E-4AB6-8DF3-6C5362EA31C3.launchd_sim[16657] (UIKitApplication:com.xyz.ios[0x449f][16704]): Service exited due to signal: Killed: 9

info: [debug] [INST STDERR] 2015-08-13 11:41:05.620 instruments[16652:326729] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST STDERR] 2015-08-13 11:41:05.620 instruments[16652:327080] Attempting to set event horizon when core is not engaged, request ignored

**Comment by moizjv** [comment]
@utkarsha1 does it work on older versions?

**Comment by utkarsha1** [comment]
It worked on appium server 1.4.10, when I updated to the latest release...
I haven't tried older versions yet.

On 13 August 2015 at 16:49, Moiz Virani <notifications@github.com> wrote:

> @utkarsha1 <https://github.com/utkarsha1> does it work on older versions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/5501#issuecomment-130837508>.
>



-- 
Regards,
Utkarsha

**Comment by moizjv** [comment]
@utkarsha1 closing it then!

**Comment by KashishAggarwal** [comment]
I am using V1.4.13, in this it is not working.?

Can somebody help me here......
