### ISSUE TITLE
Examples on Android Not finding connected device with cucumber

### ISSUE THREAD

**Issue by justin808** [appium/appium#5505]
I'm trying to run the examples `cucumber_android` ruby examples.

I get this error:
```
info: [debug] executing cmd: /Users/justin/Library/Android/sdk/platform-tools/adb devices
info: [debug] 0 device(s) connected
info: [debug] executing cmd: /Users/justin/Library/Android/sdk/platform-tools/adb devices
info: [debug] 0 device(s) connected
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
```
I verified that I have the `name` of the device existing:
![cursor_and_android_virtual_device__avd__manager_and_3__default____android_avd__java_](https://cloud.githubusercontent.com/assets/1118459/9288269/e1899790-42d9-11e5-8a5c-6d42042220d9.jpg)

And in my config file (guessing that you have to add the name, or else you get an error)
```
[caps]
platformName = "android"
appActivity = ".Settings"
appPackage = "com.android.settings"
deviceName = "Nexus_5_API_22_x86"

[appium_lib]
sauce_username = false
sauce_access_key = false
```

What other steps do I need to follow?

**Comment by Simon-Kaz** [comment]
try adding 

platformVersion = "5.1.1"

**Comment by scottdixon** [comment]
Is the device actually running @justin808?

This ticket is from a while ago, I'm guessing you've made progress since then. Reopen if otherwise.
