### ISSUE TITLE
pull file need run-as

### ISSUE THREAD

**Issue by cades** [appium/appium#5507]
Hi appium developers,

First of all, thanks for your effort & time! Appium is really cool!

The [current implementation](https://github.com/appium/appium/blob/74c4ec1a20c1f20cd2ef0b821d314b02957c82bb/lib/devices/android/android-controller.js#L475) of pullFile using `adb.pull`, where `adb` is an instance of `appium-adb`.
And `appium-adb`'s [pull method implementation](https://github.com/appium/appium-adb/blob/master/lib/adb.js#L673) is simply `adb pull <path>`, which may not work on a non-rooted device because of permission.

After googling around, I found that I need `run-as <package>`. There are some discussion on [SO](http://stackoverflow.com/questions/18471780/android-adb-retrieve-database-using-run-as), though no one works for me :(

Does anyone encounter the same problem as me, and does anyone have idea on this issue?

**Comment by scottdixon** [comment]
Thanks for the thanks, @cades!

I've not seen anyone do this before - I'd suggest asking in discuss.appium.io
