### ISSUE TITLE
Dynamic Element - Not Found

### ISSUE THREAD

**Issue by sasikumarkannaiyan** [appium/appium#5508]
We have a scenario where the Dynamic elements are not traced by Appium. Please see the details below:

1. We perform a swipe (left) of an element which then shows 4 buttons.
2. These 4 buttons are visible in UI, but  Appium throws Element Not Found Exception.

Even in the Appium Inspector, the elements are traceable only when we click "Refresh" button. We tried refreshing the driver script using 

driver.executeScript("au.mainApp().getTreeForXML()", args); 

but even after refresh, the elements could not be found.

It looks like the XML page source is cached and is not getting refreshed.

Can anyone help on this?

Sasi

**Comment by scottdixon** [comment]
Same with this one - please try a more recent version of Appium. Reopen if the issue persists. Thanks!
