### ISSUE TITLE
Page Source cache - iOS issue

### ISSUE THREAD

**Issue by sasikumarkannaiyan** [appium/appium#5509]
I have a scenario where we need to repeat the same test methods for 4 different user logins. We achieve it using @Factory and @DataProvider with group-by-instances properties today. We use TestNG and Appium Java client. Assume we have the following

LandscapeTest.java -> contains 10 test methods
PortraitTest.java -> contains 10 test methods
RepeatTest.java 
@DataProvider(name = "basicData")
    public static Object[][]basicData(){ 
      return new Object[][] { { "Login1" }, { "Login2" }, { "Login3"},  { "Login4" }    };
   }

All the test methods are getting executed in some order, which is still manageable. But Appium throws Element Not Found exception for a button in some of these test methods. But when we run single view (Portrait only or Landscape only), it gets executed without any issue. 

It looks like a weird issue. We are running Appium v1.4.7.

Though we tried sending driver.executeScript("au.mainApp().getTreeForXML()", args); command to Appium, this does not help us. 

Do someone face similar issue or can we get a workaround for this?

**Comment by scottdixon** [comment]
Please try a more recent version of Appium. Reopen if the issue persists.
