### ISSUE TITLE
 A new session could not be created. (Original error: spawn OK) Command duration or timeout: 13.92 seconds

### ISSUE THREAD

**Issue by SnigdhaSuchismitaDash** [appium/appium#5510]
Appium version:1.4
platform:Android

Appium Log

> Killed Node Server.
> Node Server Process Ended
> Starting Node Server
> warn: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
> info: Welcome to Appium v1.4.0 (REV 8f63e2f91ef7907aed8bda763f4e5ca08e86970a)
> info: Appium REST http interface listener started on 0.0.0.0:4723
> info: [debug] Non-default server args: {"fullReset":true,"logNoColors":true,"androidDeviceReadyTimeout":"15","deviceName":"Galaxy Tab S","platformName":"Android","platformVersion":"19","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"Appium","platform":"Windows","platformName":"Android","deviceName":"Galaxy Tab S","appActivity":"com.experitest.ExperiBank.LoginActivity","appPackage":"com.experitest.ExperiBank"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : platform
> info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
> info: [debug] Creating new appium session 99d62f7c-14ab-484b-b2d1-e359ae485340
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.7.0_21
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe
> warn: No app capability, can't parse package/activity
> info: [debug] Set chromedriver binary as: C:\Program Files\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] Using fast reset? false
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe devices
> info: [debug] 2 device(s) connected
> info: Found device adb server is out of date.  killing...
> info: [debug] Setting device id to adb server is out of date.  killing...
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 15)
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe -s adb server is out of date.  killing...
>  wait-for-device
> error: Error running wait-for-device
> info: [debug] Retrying restartAdb
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe -s adb server is out of date.  killing...
>  kill-server
> error: Error killing ADB server, going to see if it's online anyway
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe -s adb server is out of date.  killing...
>  devices
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 15)
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe -s adb server is out of date.  killing...
>  wait-for-device
> error: Error running wait-for-device
> info: [debug] Retrying restartAdb
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe -s adb server is out of date.  killing...
>  kill-server
> error: Error killing ADB server, going to see if it's online anyway
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe -s adb server is out of date.  killing...
>  devices
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 15)
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe -s adb server is out of date.  killing...
>  wait-for-device
> error: Error running wait-for-device
> info: [debug] Retrying restartAdb
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe -s adb server is out of date.  killing...
>  kill-server
> error: Error killing ADB server, going to see if it's online anyway
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe -s adb server is out of date.  killing...
>  devices
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 15)
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe -s adb server is out of date.  killing...
>  wait-for-device
> error: Error running wait-for-device
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe -s adb server is out of date.  killing...
>  kill-server
> error: Error killing ADB server, going to see if it's online anyway
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe -s adb server is out of date.  killing...
>  devices
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 15)
> info: [debug] executing cmd: D:\adt-bundle-windows-x86-20140321\sdk\tools\adb.exe -s adb server is out of date.  killing...
>  wait-for-device
> error: Error running wait-for-device
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> error: Failed to start an Appium session, err was: Error: spawn OK
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Error: spawn OK
>     at errnoException (child_process.js:988:11)
>     at Process.ChildProcess._handle.onexit (child_process.js:779:34)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: spawn OK)","code":"OK","errno":"OK","syscall":"spawn","origValue":"spawn OK"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 13785.531 ms - 181

**Comment by scottdixon** [comment]
Closing old issue. Please try a more recent version of Appium. Reopen if the issue persists.

**Comment by SnigdhaSuchismitaDash** [comment]
Hi Scott,

I think it is issue with adb. The path to adb is wrong or contain space in
between. Or it is out of date.

Thanks and regards
Snigdha Dash

**Comment by scottdixon** [comment]
Thanks for the update!

**Comment by AlisaNi123** [comment]
I met the same question as you，Can you tell me how you solved it?
