### ISSUE TITLE
processedArguments not working

### ISSUE THREAD

**Issue by axelbarfod** [appium/appium#5512]
Hi guys,

I'm trying to send the process arguments to my AUT, using the processedArguments, 

capabilities = {
    :deviceName        => (!ENV['DEVICE_NAME'].nil?) ? ENV['DEVICE_NAME'] : 'iPhone 5',
    :platformName      => 'iOS', 
    :platformVersion   => '7.1', 
    :app               => ENV['APP_PATH'],
    :autoWebview       => true,
    :autoAcceptAlerts  => true, 
    :bundleId          => 'com.company.app.id', 
    :launchTimeout     => {
        :global         => 120000,
        :afterSimLaunch => 120000  
    }, 
    :newCommandTimeout => 120, 
    :processArguments  => "-mockScanner YES", 
    :keepKeyChains     => true

but after starting the app it says it's trying to boot the app, starts the app but when I go to the Setting > MyApp > it didn't change the parameter to the value I wanted, even after running the spawning instruments. I'm working with ruby. Is this a known issue?

Error shown on log is: 
"The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : processArguments"

**Comment by scottdixon** [comment]
Interesting. Can you give 1.5 a shot @axelbarfod ?

**Comment by axelbarfod** [comment]
Yes I can, will give feedback as soon as i try it

**Comment by MelissaHoweEmis** [comment]
I am also facing the issue where processArguments are being passed in with no error but aren't being used. Are there plans to resolve this please?

**Comment by imurchie** [comment]
@MelissaHoweEmis Can you provide more information? What version of Appium? A [gist](https://gist.github.com/) of the server logs?

**Comment by dandoveralba** [comment]
@imurchie looks like adding ", 'processArguments'" to line 42 of capabilities.js fixes this for 1.4.  Whaddya think?

**Comment by imurchie** [comment]
Does it? It would fix the warning that the capability is unrecognized, but not necessarily the problem that `processArguments` is not doing anything.

**Comment by dandoveralba** [comment]
Seems to... https://gist.github.com/dandoveralba/28e24e11e34b47530a52348b32c4df2f

**Comment by rkavalap** [comment]
Closing this as dup for https://github.com/appium/appium/issues/5909
