### ISSUE TITLE
sendKeys working incorrectly randomly

### ISSUE THREAD

**Issue by azucca** [appium/appium#5516]
I'm currently using Appium 1.4.0.0 with Java and we are developing an Android hybrid app using Cordova. We are experiencing random incorrect behaviour for sendKeys in some textfields. For example, I send my email address into the username field in order to log into the app, "azucca@itx.com", but it deletes the "m".

I tried to detect that behaviour, by capturing the value, hoping that I would get "azucca@itx.co" allowing me to recover from that error, but apparently Appium is not detecting the difference. It detects "azucca@itx.com".

This is a piece of the code where I'm able to reproduce the error:

                String username = "azucca@itx.com";
		String password = "12345";
				
		List<MobileElement> textfields = wd.findElementsByClassName("android.widget.EditText");
		textfields.get(0).sendKeys(username);
				
		System.out.println(findM(textfields,"azucca").getAttribute("name"));
		System.out.println(username);
		
		Thread.sleep(3000);
		
		if(findM(textfields,"azucca").getAttribute("name").compareTo(username)!=0){			
			wd.resetApp();
			logIn(wd);				
		}

I wrote the if clause hoping to detect the error and try to login again, but it never detects that the "m" is missing. Also, both System.out print the correct value.  The strange behaviour in sendKeys function is random, but it's causing our tests to fail most of the times.

I tried running it on emulators, real devices, Windows, MAC. Always get the same result.

**Comment by Fanch-** [comment]
Up, same problem and I can confirm it's a regression, sometimes it also writes the "space character" at the wrong position. Quite problematic.

**Comment by jrichardlai** [comment]
I have the same issue too, it stays on the begining of the text input strangely

**Comment by scottdixon** [comment]
This should be resolved in recent version of Appium. Reopen + provide logs if otherwise.
