### ISSUE TITLE
Question/Feature request: How to check equality of elements? Native apps.

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/appium#5517]
Hi guys! There is an interesting question.

Is there any command that allows to check equality of elements of a native app? If there is no command like that then does it makes sense to implement it.

What the problem:

``` java
WebElement e1 = driver.findElement(By. some constant locator);
WebElement e2 = driver.findElement(By. some constant locator);
e1.equals(e2);// is always "false"
```

for native apps. It happens because used automation tools always return different ID's each time when client tries to find (the same) an element.

@bootstraponline told me that it is impossible to compare elements on clients side correctly. There is not enough information for this action. So there should be something on server side that compares elements and returns **true** when elements are equals (it is the same element) and **false** otherwise. 

...And clients should be improved as well.

**Comment by bootstraponline** [comment]
The dedupe logic I implemented [for android](https://github.com/appium/appium/blob/a4b690cbe2ff2a091ecb05b71fa3595b5ec0da36/lib/devices/android/bootstrap/src/io/appium/android/bootstrap/utils/ElementHelpers.java#L35) demonstrates the use of equality for android using uiautomator v1. The [upstream issue](https://code.google.com/p/android/issues/detail?id=70233) in Android has been closed as uiautomator v2 makes it easier to determine equality without resorting to reflection.

**Comment by Marinell** [comment]
Sorry @bootstraponline . How can i use the dedupe function in practice? Could you please post an example?

**Comment by bootstraponline** [comment]
this is in reference to uiautomator v1 which doesn't exist anymore 

I ended up moving on to using Espresso for Android testing. uiautomator has a bunch of issues sadly.
