### ISSUE TITLE
Rename appium.txt to appium.yml

### ISSUE THREAD

**Issue by justin808** [appium/appium#5521]
I suggest that having parameters put in a `.txt` file is unexpected.

Have you considered using a YAML file?

**Comment by bootstraponline** [comment]
It's not yaml though. The format is called [toml](https://github.com/toml-lang/toml). Most editors don't know what to do with a file extension `.toml`. It's a plain text format so `.txt` makes sense to me.

**Comment by justin808** [comment]
I'd recommend changing it to `toml` and then specifying that people have editors handle the file as txt.

**Comment by bootstraponline** [comment]
I think having to explain to end users what a toml is and why they can't just double click the file to edit is going to cause more confusion than it's worth.

**Comment by justin808** [comment]
It looks like an old school windows ini file.

I think an unknown format is confusing to engineers.

**Comment by bootstraponline** [comment]
maybe we should just move it to appium.json then?

**Comment by justin808** [comment]
json doesn't allow simple comments (there's hacks), but it's the Node standard.

Why not yaml?

**Comment by bootstraponline** [comment]
I think yaml is too complex for this use case and has all kinds of fun [security issues](https://github.com/dtao/safe_yaml). toml is easier to read and write (similar to windows.ini files).

The only client with appium.txt support is ruby. It's trivial for end users to use yaml if they want and just parse it into a Hash which is then passed to the driver.

**Comment by bootstraponline** [comment]
Here's a posting about [yaml vs toml](http://npf.io/2014/08/intro-to-toml/) and the relevant trade offs.

**Comment by bootstraponline** [comment]
and [here's a summary](https://github.com/toml-lang/toml#comparison-with-other-formats) of json vs yaml vs toml from the official repo.

**Comment by justin808** [comment]
If the only client that uses the appium.txt file is ruby, and rubyist hardly even use windows, then making it like a windows.ini file...

I'd just go with YAML or JSON. Impossible to confuse. Easy to document.

**Comment by bootstraponline** [comment]
I filed an enhancement request about [supporting JSON](https://github.com/appium/ruby_lib/issues/349). It seems that's how google does it with [their protractor framework](https://github.com/angular/protractor/blob/master/config.json). appium is primarily a node project so I think that makes more sense than yaml.

I think with json it'd also be trivial for all the other appium bindings to easily read from the same config instead of keeping it ruby exclusive.

**Comment by sofaking** [comment]
I vote for YAML as well since it de-facto standard in Ruby community. JSON as configuration file will be probably even weirder than toml inside txt file.

**Comment by bootstraponline** [comment]
I'm thinking a proper plugin API is the solution so people can use their preferred format.
