### ISSUE TITLE
incessant hangs

### ISSUE THREAD

**Issue by adamf663** [appium/appium#5525]
I'm trying to automate testing of an android kitkat 4.4.2 phone.
I'm using eclipse, testng, log4j2, appium 1.4.10, java-client 3.1.0, and java 8.
I can't get through three runs of a trivial script, containing nothing other than navigation to home, notifications, quick settings and the main settings,  in a row without appium either hanging on installing an apk or trying to hit the home key with event 3.
Right now it is hung at: 
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s 631162636 install "/home/afelson/.linuxbrew/lib/node_modules/appium/build/settings_apk/settings_apk-debug.apk".
Subsequent runs will all fail with either being unable to start a new session or that one is already in progress;  the only recourse is to unplug/plug the phone's usb and to kill and restart the appium server.  

Rebooted, reinstalled the android sdk and appium to no avail.

**Comment by gregorywringle** [comment]
Where you able to make any headway with this issue? I'm experiencing the same thing.

**Comment by adamf663** [comment]
It seemed a little better with tracing reduced to the logfile.  
The hang is when appium is sending a debug version of the apk under test.  When I see it stuck there, I kill it and restart.
It's too bad the folks at appium haven't any time to troubleshoot this as it really makes appium look bad.

There's also an issue where appium is incapable of reusing a driver it thinks is still busy.  My initialization class kills and restarts the server when there are any issues with opening the driver.

----- Original Message -----

**Comment by adamf663** [comment]
no progress after 3 months.  why doesn't appium care that their software hangs and crashes?  (as I watch yet again hung installing appium/build/settings_apk/settings_apk-debug.apk )

**Comment by SrinivasanTarget** [comment]
@adamf663 please give a try in latest version of appium.Install the same by using: npm install -g appium.
Architecture is significantly improved alot. Looking forward to hear from you. Incase of issues, post the appium logs inform of gist.

**Comment by adamf663** [comment]
architecture is worse.   1.5.x  (including 1.5.1) is simply unuseable.
I still have to hack out the unlock code as it borks my phones every time.

I can no longer use two phones without appium crashing.  Screenshots in particular almost *always* cause appium to crash if there are two phones.
I run two phones through two appium servers, each with separate -p and -bp ports.
Tests that failed about 70% of the time due to appium bugs now fail 100% of the time.
I don't even know if the clear field bug carried over to 1.5.1.  I can't get that far in my tests to actually enter a field.

----- Original Message -----

**Comment by SrinivasanTarget** [comment]
@adamf663 To run on multiple devices, have a look at this, https://github.com/saikrishna321/AppiumTestDistribution.

Architecture is quite good in 1.5.1 and if you have any issues feel free to raise here.It will be addressed asap.And no hangs in appium latest version even you ran on multiple devices continuously.We have regressed the parallel testing on android and iOS quite alot of times and everything works fine for us.

**Comment by adamf663** [comment]
That much is true.  Appium doesn't hand when it tries to download the debug version of apks.
Still can't use it due to the incessant EOINT (or whatever) crashes.

----- Original Message -----

**Comment by SrinivasanTarget** [comment]
@adamf663 Can you please post the exact code snippet you have tried and the logs in form of gist here?

**Comment by SrinivasanTarget** [comment]
closing this in favor of https://github.com/appium/appium/issues/6384

**Comment by SrinivasanTarget** [comment]
@triager please close
