### ISSUE TITLE
Cannot switch to webview on Android

### ISSUE THREAD

**Issue by wilcollins** [appium/appium#5526]
I cannot switch contexts to WebView on v1.4.10. I have updated chromedriver ( #5477 ) but it still fails to switch contexts

```
[debug] Getting a list of available webviews
[debug] executing cmd: /usr/local/Cellar/android-sdk/24.3.3/platform-tools/adb -s emulator-5554 shell "cat /proc/net/unix"
[debug] WEBVIEW_3621 mapped to pid 3621
[debug] Getting process name for webview
[debug] executing cmd: /usr/local/Cellar/android-sdk/24.3.3/platform-tools/adb -s emulator-5554 shell "ps"
[debug] Parsed pid: 3621 pkg: com.WorkTaskManagement
[debug] from: u0_a66,3621,954,995984,137300,ffffffff,f7554355,S,com.WorkTaskManagement
[debug] returning process name: com.WorkTaskManagement
[debug] Available contexts: NATIVE_APP,WEBVIEW_com.WorkTaskManagement
[debug] ["WEBVIEW_com.WorkTaskManagement"]
[debug] Available contexts: NATIVE_APP,WEBVIEW_com.WorkTaskManagement
[debug] Connecting to chrome-backed webview
[debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Cannot read property 'stop' of null)","origValue":"Cannot read property 'stop' of null"},"sessionId":"bfa7d166-319f-41ba-85ec-11fc090ea6c0"}
```

Android 5.1, 5.0, & 4.4 have been tested

**Comment by wilcollins** [comment]
#5436 My app is also built using Cordova

**Comment by q-a** [comment]
What version of Chrome are you using?

**Comment by wilcollins** [comment]
I am trying to access a webview, not the chrome browser.. do you mean which
version of chromedriver?

**Comment by bootstraponline** [comment]
Reminds me of #2755. Same issue, different error message.

> (Original error: Cannot read property 'stop' of null)","origValue":"Cannot read property 'stop' of null"}

I recommend trying on a real device instead of an emulator to see if that helps. It doesn't look like the chrome driver related issues are going to be resolved until [appium 1.5](https://github.com/appium/appium/milestones).

**Comment by greedypinky** [comment]
I tried appium 1.4.12 but no luck to see the webview_xxx. however, when installed ver 1.3.4,
I could view the webview.

**Comment by a-padinha** [comment]
@greedypinky  hello, I'm having the same issue, are you working fine with 1.3.4?

**Comment by wilcollins** [comment]
I am still getting ``Did not get session redirect from Chromedriver`` on ``1.3.4`` with ``ChromeDriver 2.14.313457``

**Comment by wilcollins** [comment]
Working with ``1.3.4`` and ``ChromeDriver 2.18.343837``

**Comment by jvillacorta** [comment]
Thank you it works perfectly on Appium v1.3.4 and ChromeDriver 2.18.343837 for Android 5.1 and below.. I am having trouble with Android M, which was why I updated Appium.
