### ISSUE TITLE
How to add appium server in eclipse workspace

### ISSUE THREAD

**Issue by ssirekumar** [appium/appium#5527]
I have requirement like i don't want to install appium in my machine with the help of (npm install -g appium) So i want to run appium commands in command line mode with the help of node-modules. So in this consideration how can i add this into my eclipse project. I am looking exact like selendroid server jar configuration Does we have this kind of flexibility with appium.

This will help me lot in my project with giant client. As simple as i am looking every thing(Appium server should start from eclipse workspace) should be in my eclipse project only for all platforms(Linux, win, mac).

Thanks

**Comment by scottdixon** [comment]
@ssirekumar - please ask in http://discuss.appium.io

If you hit an Appium related bugs please file them here.
