### ISSUE TITLE
Provide the latest version of Selendroid in Appium

### ISSUE THREAD

**Issue by albedithdiaz** [appium/appium#5529]
Currently the latest version of Selendroid is 0.16.0 (http://selendroid.io/) but through Appium the latest version of Selendroid that I could get is 0.13.0. 

Please provide the latest version of Selendroid in Appium.

**Comment by vietnq254** [comment]
Hello,

Actually the newest version is 0.17.0-SNAPSHOT.
You can download these 2 files and copy them to folder '''appium\build\selendroid'''
[Selendroid 0.17.0-SNAPSHOT](https://www.dropbox.com/s/59943vc3coch3ze/selendroid.apk?dl=0)
[Selendroid Manifest](https://www.dropbox.com/s/mycyne845l816vo/AndroidManifest.xml?dl=0)

**Comment by imurchie** [comment]
In both 1.4 and 1.5. Closing.
