### ISSUE TITLE
Unable to select Login ID on App Splash Screen

### ISSUE THREAD

**Issue by karbon62** [appium/appium#5534]
Hi I'm trying to identify the ID for the Login on the splash screen but it doesn't identify it as a individual object and yet all that it does is display the whole splash screen as a whole object. 

This is for Android and I am using the Inspector tool to gain the ID too, not sure what is wrong, it could possibly be the app itself but Im wondering if there is a way of getting around this so that I can search and attain the ID for each individual object. 

Could someone please help? 

Thanks

**Comment by scottdixon** [comment]
Can you please provide your test script + server logs?

**Comment by karbon62** [comment]
Hi

I figured that this was an issue on the Client side and its no longer an issue. 

Thanks for helping and responding.

**Comment by scottdixon** [comment]
Thanks for the update!
