### ISSUE TITLE
AppiumDriver should not extends BaseDriver.

### ISSUE THREAD

**Issue by sebv** [appium/appium#5537]
- More or less BaseDriver manages one session at a time, Appium driver a list of sessions.
- There are some feature which are not relevant like command timeout, and unexpectedShutdown. 
- deleteSession does not even have the same signature.

It should probably be replaced by a session handler possibly extending MJSONWP. It's better to be really careful when extending classes and use it as little as possible, composition is the far better pattern.

**Comment by sebv** [comment]
ping @jlipps.

**Comment by jlipps** [comment]
I can see your point. However unexpected shutdown is still relevant, right? Appium needs to know when one of the sessions it's managing has ended so it can remove it from its list, right?

**Comment by sebv** [comment]
Yeah but  AppiumDriver is a client, not a producer.

**Comment by jlipps** [comment]
ok. I'm definitely open to this, I just don't have a good handle on whether we're going to be duplicating a lot of logic.

**Comment by sebv** [comment]
Now it is not perfect, but compared to before it is going to be very easy to reformat the code, so we should experiment a bit.

**Comment by jlipps** [comment]
yeah and it's easy to have an exhaustive set of functional tests using FakeDriver or something so it will be easy to see if we broke something

**Comment by jlipps** [comment]
closing for now, either we will not do this or something like it will be done automatically in our rearchitecture for Appium 2.0.
