### ISSUE TITLE
adb shell "pm list packages" should not only look at third party packages

### ISSUE THREAD

**Issue by whoward** [appium/appium#5538]
Appium version: `1.4.10`

So while working with an android device we want to be able to check to see which camera app comes installed on the device - pretty easy except Google in their infinite wisdom changed their camera app's package name between Android 4.x and Android 5.x

Android 4.x = `com.android.camera`
Android 5.x = `com.android.camera2`

we figured we could check this by hitting `/wd/hub/session/:session_id/appium/device/app_installed` with the package name of the camera but it returned false in both cases where it shouldn't have.

i looked into it a bit and it seems its because the command `adb shell "pm list packages -3 <package>"` and the `-3` excludes all non third-party packages.  I can't see why you wouldn't want system packages included...performance maybe but that can't be a big hit.

**Comment by rkavalap** [comment]
https://github.com/appium/appium-adb/blob/c57ab27852b047869e6b383813daca92216202bd/lib/tools/apk-utils.js

**Comment by tfcardoso** [comment]
I'm trying to automate an embedded app also and this is giving me problems. This is a simple fix and should be in next milestone.
