### ISSUE TITLE
noReset for iOS not working

### ISSUE THREAD

**Issue by threat70** [appium/appium#5540]
noReset = false not working for ios. In documentations says, that app must resets at session start, but on ios nothing happens. 

yea, reset means reset app data without reinstall, but for ios its best solution.

**Comment by amedvedjev** [comment]
we do not have any problem with resetting/not resetting app during Appium driver start.

both Android and iOS.

our versions: Appium 1.4.10 / 1.4.7 , Java client: 3.1.0

server starting like:
```[appium, --log-level, error, --port, 4724, --session-override]```

Example of driver start **without** reset for iOS:
```Capabilities [{automationName=Appium, newCommandTimeout=120, platform=MAC, platformVersion=8.1, app=/Users/SOMEAPP_PATH.app, deviceName=iPad Air, fullReset=false, browserName=iPad, noReset=true, version=}]``` 

Example of driver start **with** reset for iOS:
```Capabilities [{automationName=Appium, newCommandTimeout=120, platform=MAC, platformVersion=8.1, app=/Users/SOMEAPP_PATH.app, deviceName=iPad Air, fullReset=true, browserName=iPad, version=}]```

**Comment by threat70** [comment]
with fullReset app removed with session close. I need reinstall app only on start session. on android noReset = false, fullReset = false reinstall app only on start session and not remove after session

**Comment by galiaf95** [comment]
Any update on this issue. I have macmini with latest os and latest appium. And simulator gets killed every time I start my tests, but I specify noReset as true. I'm using python appium client.
