### ISSUE TITLE
Running tests on multiple simulators with setting '--instruments' param.

### ISSUE THREAD

**Issue by a-shynkevich** [appium/appium#5543]
Hello!

I am just trying check my version about running tests on several simulators at the same time.
I've reviewed a lot of topics about that and every of them told that 1 simulator uses per 1 instruments at the same time.

But what will happens if I will use 2 different instruments...?

So I've installed 2 xCodes it means I have 2 instruments.

I run appium server with argument '--instruments' where I set my path to instruments of second xCode:

 appium --instruments /Applications/Xcode_6.2.app/Contents/Developer/usr/bin/instruments 

But when I run my test I see that appium uses default instruments path: 

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

So in this case I ca't check my idea.
It seems that param '--instruments' does not work properly....

**Comment by rkavalap** [comment]
Closing as dup to #6385
