### ISSUE TITLE
What means "The app must be signed with a development identity" ?

### ISSUE THREAD

**Issue by Kolyall** [appium/appium#5547]
What means "The app must be signed with a development identity" ?
but ipa it 's already signed from xcode...

[INST STDERR] Instruments Trace Error : Target failed to run: Permission to debug com.***.*** was denied. The app must be signed with a development identity (e.g. iOS Developer).
What is wrong?

**Comment by Kolyall** [comment]
found 
 Product -> Scheme -> Edit Scheme, then select 'Profile' from the left menu and set the Build Configuration to Debug.

**Comment by sanatzzz** [comment]
Hi Kolyall, the app i am automating is provided by our client and they sign it with their profiles that they created. the device's udid that I have is added in that profile and I get the same error.
do i need anything else with me to get rid of the error.
I can automate an app that i created but not the one provided by our client.
if my developer does what you suggested and gives me the built .ipa file, will I be able to do it?
