### ISSUE TITLE
Can we change iPhone or iPad language during or before execution

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium#5550]
@jlipps , @Jonahss , @lukeis 
I have to take the screenshots of my App with all supported languages to put them into AppStore. To do this, do we have this possibility with Appium?

Approach: 
1. Launching the App with default Language(i.e.: English) 
2. Taking the screen shot
3. Change the language to Spanish
4. Take the screen shot and so on.

is this possible? I don't take about the Real device or simulator, My task needs to be done. Please help me.

**Comment by amedvedjev** [comment]
"--locale" attribute with server or "locale" with driver force to start iOS simulator with needed language.

**Comment by shivakrishnach31** [comment]
Thankyou @amedvedjev ,
I am facing some issue with installing my .app on Simulator. Is there any scope to do this on real device?

**Comment by scottdixon** [comment]
@shivakrishnach31 please open a new issue & provide server logs as a gist if you're still having trouble.
