### ISSUE TITLE
Unable to access web elements in a cross-origin (CROS) iframe on IOS mobile browser

### ISSUE THREAD

**Issue by jawlitkp** [appium/appium#5553]
Hello,
I am working on eCommerce application and it is cross origin iframe many ways, i saw this issue has been raised before and closed wihtout any solution,this is gating issue and need to be fixed,please provide solution anyone has it.

here is exception 

Exception : undefined is not an object (evaluating 'a.nodeType') (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.06 seconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:03:00'
System info: host: 'N/A', ip: 'N/A', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.7.0_75'
Session ID: 0fe07a6f-2b48-462b-a9e9-e98fd32ea3aa

**Comment by JasnoWa** [comment]
Does Appium use the Remote WebKit Debugger to execute scripts for iframes? I've seen this scenario work with other Selenium implementations.

**Comment by jawlitkp** [comment]
Yes Appium is using IOS Web debugger proxy , it is working fine for Android device and Browsers , so I am assuming issue is with proxy only.

**Comment by scottdixon** [comment]
@jawlitkp - please try a more recent version of Appium `npm install -g appium`.

CORS shouldn't effect Appium. If you're able to use it on a simulator, Appium should be able to interact with it.

Reopen if you get stuck.
