### ISSUE TITLE
Appium session started with sessionId null

### ISSUE THREAD

**Issue by deadmoto** [appium/appium#5555]
Configuration:
Appium v1.4.8 (3 instances)
Selenium Server Standalone 2.47.1

After random number of tests Appium instance fails to create new sessions.
It does not happen always but the more tests we run the higher is chance.

Can't attach logs, posted here: http://pastebin.com/HZ2HKyr7

**Comment by shaikatz** [comment]
Same here.. any advise?

**Comment by scottdixon** [comment]
Closing old issue. Please try a more recent version of Appium. Reopen if the issue persists.
