### ISSUE TITLE
Appium Android: unable to get elements under android.view.View

### ISSUE THREAD

**Issue by savishy** [appium/appium#5556]
I am working on automating testing for an app that has (among other things) an inbuilt gallery. 
I am on Appium v1.4.0 (REV 8f63e2f91ef7907aed8bda763f4e5ca08e86970a)
I am able to open the gallery-view fine (using the activity name). 

However, the main portion of the view is simply recognized as "android.view.View" with no subelements, although I can see previews of albums etc. 
Here's how it looks like in Appium Inspector. The "Selected" element is what I wish to interact with.
![appium-inspector](https://cloud.githubusercontent.com/assets/13379978/9628500/f6c7df82-5188-11e5-9fbb-565ada7b9453.png)
The screenshot is a simple case with only one album, but in a real scenario I would want to get a list of "album" subelements, open a specific "album" sub-element, and so-on.

Notes:

* Being able to interact with the photos is important as mine is a Gallery application.
* I have access to the source code but only done basic digging into the source.

How do I proceed? I have tried googling with various search strings and drawn a blank until now. Thanks for any help you can provide!

UPDATES:

* I just saw this discussion: https://groups.google.com/forum/#!topic/appium-discuss/WWSENPgolCg
I tooled around in the source. It appears the gallery view may be just an implementation of com.android.gallery3d (since src/ has two packages - my app's package and com.android.gallery3d).

**Comment by savishy** [comment]
Hello? Any responses?

**Comment by aniket-21** [comment]
Is it a custom view?

**Comment by savishy** [comment]
@aniket-21 Sorry - not acquainted with android development jargon - what is a custom view?

**Comment by aniket-21** [comment]
Below is the extract from developer.android.com

Generally, app developers get accessibility support for free, courtesy of the View and ViewGroup classes. However, some apps use custom view elements to provide a richer user experience. Such custom elements won't get the accessibility support that is provided by the standard Android UI elements. If this applies to your app, make sure that it exposes the custom-drawn UI element to Android accessibility services by implementing the AccessibilityNodeProvider class.

If the custom view element contains a single element, make it accessible by implementing accessibility API methods. If the custom view contains elements that are not views themselves (for example, a WebView, make sure it implements the AccessibilityNodeProvider class. For container views that extend an existing container implementation (for example, a ListView), implementing AccessibilityNodeProvider is not necessary.

**Comment by scottdixon** [comment]
Judging by your update it looks like you resolved this. Reopen if you require assistance.
