### ISSUE TITLE
IOS instruments still in use preventing subsequent tests to start

### ISSUE THREAD

**Issue by glorylo** [appium/appium#5557]
When running a test suite of many tests some tests will failed to start a new session due to the instruments hasn't been cleared.

In C# we get the exception when doing a launch:
System.InvalidOperationException : Unable to launch the app: Error: Trying to start a session but instruments is still around (IndexOutOfBounds)

The rest of the test suite fails to start from here on out.  Is there a way to force quit the instrument sessions and restart it without manually restarting the entire appium server?

**Comment by scottdixon** [comment]
@glorylo - please try Appium 1.5 - reopen this issue if you get stuck.
