### ISSUE TITLE
appium could not find the element in an iframe with mobile safari test

### ISSUE THREAD

**Issue by xlzdew** [appium/appium#5560]
Hi,
There is an iframe embedded in the tested page , it can switch to the iframe by using appium, but return "'undefined' is not an object error when it tries to find an element in the iframe. Following is my java test script. Is there any problem with my test case or is it an issue of appium? could you help me figure out? Thanks in advance.
(I tested it by using appium 1.4.0 /mobile safari)

	    DesiredCapabilities capabilities = new DesiredCapabilities();
	    capabilities.setCapability(CapabilityType.BROWSER_NAME, "safari");
	    capabilities.setCapability("platformVersion", "7.1");
	    capabilities.setCapability("platformName", "iOS");
	    capabilities.setCapability("deviceName", "iPhone Simulator");
	    driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);	    
     	driver.get("http://m.alibaba.com/ma"); 
     	WebElement iframeElement = driver.findElement(By.id("alibaba-login-box"));           
	driver.context("WEBVIEW_1");     
     	driver.switchTo().frame(iframeElement);  
     	WebElement loginElement = driver.findElement(By.id("fm-login-id"));// it returns error

it throw out following error logs:
info: [debug] Entering new web frame: :wdc:1441290966711
info: [debug] Responding to client with success: {"status":0,"value":{"WINDOW":":wdc:1441290966711"},"sessionId":"71b568b4-6109-4631-ad60-09ddeeb83477"}
info: <-- POST /wd/hub/session/71b568b4-6109-4631-ad60-09ddeeb83477/frame 200 13.793 ms - 103 {"status":0,"value":{"WINDOW":":wdc:1441290966711"},"sessionId":"71b568b4-6109-4631-ad60-09ddeeb83477"}
info: --> POST /wd/hub/session/71b568b4-6109-4631-ad60-09ddeeb83477/element {"using":"id","value":"fm-login-id"}
info: [debug] Waiting up to 0ms for condition
info: [debug] [REMOTE] Wrapping script for frame :wdc:1441290966711
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
info: [debug] [REMOTE] Receiving data from remote debugger
info: [debug] [REMOTE] got applicationSentData response
info: [debug] Condition unmet after 17ms. Timing out.
info: [debug] Responding to client with error: {"status":13,"value":{"message":"'undefined' is not an object (evaluating 'c.K.getElementById')","origValue":"'undefined' is not an object (evaluating 'c.K.getElementById')"},"sessionId":"71b568b4-6109-4631-ad60-09ddeeb83477"}
info: <-- POST /wd/hub/session/71b568b4-6109-4631-ad60-09ddeeb83477/element 500 18.572 ms - 226

**Comment by xlzdew** [comment]
it seems caused by the driver.switchTo().frame(iframeElement);  do not work under mobile safari.
I tried driver.getCurrentUrl() after switch to frame, it return the url of default page instead of the url of iframe window. 
The operation still hang on the current default page, and could not find any element in the iframe window Absolutely.

**Comment by krisdyZJU** [comment]
I met the same problem on safari in real devices. @xlzdew 
as you said, the return value of getCurrentUrl() is the same even I call driver.switchTo().frame(iframeElement).

we will have to stick to the source code of appium driver to investigate and fix this problem...

**Comment by krisdyZJU** [comment]
is there any update on this one?
i am reading the source code of selenium, but seems not easy to fix.
it is very awkward that appium can not support switchTo iframe but there is one iframe inside the web page which I need to automate..

**Comment by Nishant-Taksande** [comment]
I ran into the same issue.

Below is the application reference:
1. Launch browser and navigate to "http://m.ebay.com.au"
2. Click on Sign in  / Register link (Sign in page will be displayed with Register Tab).
3. Click on Register tab.
4. Try entering data in any field.

iFrame: id = regFrame

**Comment by jsalama2** [comment]
We had the same issue which we fixed by using the actual selenium driver instead of the appium driver which can be accessed in ruby with appium_driver.driver.switch_to.frame 0.

**Comment by crackwindows7** [comment]
i dont have find element
i just crack window 7 here<a href="http://crackwindows7.com/windows-loader-v2-2-4/" title="Windows Loader v2.2.4">Windows Loader v2.2.4</a> and <a href="http://crackwindows7.com/download-windows-7-activator/" title="Windows 7 Activator">Windows 7 Activator</a>
Please help me!Thanks

**Comment by lunchboxdc** [comment]
Any progress on this? I am recently blocked by this as well. We're going to have to resort to all manual testing until this is fixed.

**Comment by imurchie** [comment]
I'm closing this in preference to #5832, since there are logs for 1.5 there.

**Comment by srihariinnamuri** [comment]
I think Appium does not support Iframes, that mean you can not switch to Iframe in real devices.
We had a similar issue. here is the work around.
every Iframe will link to the url. get the Iframe url into a variable and access it by using driver.get("url").
fill the form and go to the next screen.

**Comment by lunchboxdc** [comment]
I disagree. The same code I have works just fine in an android emulator via a webview in an app. Granted that's probably using Chromedriver, it proves that Appium in general can do this.

Also, this issue is closed. Please put further comments on the issue @imurchie pointed out above.

**Comment by broven** [comment]
I face the same problem, my solution is switch to native context

**Comment by soul3510** [comment]
@broven hi, how did you manage to overcome this issue, can you please share? 
Thanks.

**Comment by broven** [comment]
@soul3510  my solution is to switch currentContext to native, use the native selector to access the element in iframe
