### ISSUE TITLE
Appium should provide a way to grant run-time permissions by default on Android M

### ISSUE THREAD

**Issue by willosser** [appium/appium#5561]
Android M no longer grants run-time permissions to apps even though they are listed in the manifest.  See https://developer.android.com/preview/features/runtime-permissions.html#

There should be a way to inform Appium that the application-under-test should get all requested run-time permissions.  This can be accomplished during installation by adding the -g flag.
  adb install -g <pkg_name>

There may be cases where we don't wish to have those permissions, so there this option should be configurable via capabilities.  It would also be nice to have an API to grant or revoke specific permissions.

**Comment by bootstraponline** [comment]
:+1:

**Comment by orrinLife360** [comment]
👍

**Comment by gowtham1984** [comment]
+1

**Comment by shivakrishnach31** [comment]
Any update on this guys?

**Comment by imurchie** [comment]
We tried the solution above and it broke almost everything. So until there is a better solution, no update.

**Comment by fabianaapateanu** [comment]
+1

**Comment by jlipps** [comment]
Looks like @mykola-mokhnach's solution in #6091 is probably the most straightforward way to implement this.

Acceptance criteria:
* [ ] appium reads the app's manifest and determines the permissions requested
* [ ] appium loops through the permission list, explicitly granting each one via ADB
* [ ] some way to test this

Presumably we should add some method `grantPermission` to appium-adb. Not sure where permission extraction from the manifest should be written.

**Comment by sravanmedarapu** [comment]
@jlipps, what should be the route to grant and revoke app permission ?

**Comment by sravanmedarapu** [comment]
With current approach of executing `adb shell pm grant pkg permission` for every requested permission is taking more time.

Following are the approaches tried locally as a alternative

1.  Tried with Android hidden API [`PackageManager`](https://github.com/android/platform_frameworks_base/blob/82834baa358f55acb542e17da828b2d497cf8332/core/java/android/content/pm/PackageManager.java#L3310) suggested by @bootstraponline [here](https://github.com/appium/appium/issues/6091#issuecomment-238238177)  and granting permissions much faster, but approach works only with Emulators but not with real devices. Code commit to [refer](https://github.com/appium/appium-uiautomator2-server/commit/b5398907ff4ec00ede689106a2874ecafff0008d)
   

     - Reason: To access the android hidden api, our application should also use same [sharedUserId](https://github.com/appium/appium-uiautomator2-server/blob/b5398907ff4ec00ede689106a2874ecafff0008d/app/src/main/AndroidManifest.xml#L4) and [sign](https://github.com/appium/appium-uiautomator2-server/blob/b5398907ff4ec00ede689106a2874ecafff0008d/app/build.gradle#L38) with same keystore of `android.uid.system`.  Application built with this configuration are not supported on real devices for security reasons.

1.  Instead executing shell command for every permission[`adb shell pm grant pkg permission`], we can try with single shell command by including all permissions[`adb shell pm grant pkg perm1;  pm grant pkg perm2; ...`]. Which will reduce considerable amount of time.

As granting permission with hidden API not working with real devices, we can proceed with single shell command for all permissions and as per the comment made by @jlipps [here](https://github.com/appium/appium/issues/7349#issuecomment-265903320) about having dark feature to enable this feature in capabilities would be a right approach.

**Comment by jlipps** [comment]
@sravanmedarapu let's proceed with single shell command. you've tested it and confirmed it does take less time?

**Comment by sravanmedarapu** [comment]
Sure @jlipps. Yeah comparatively it is considerable amount of time.

**Comment by jlipps** [comment]
https://github.com/appium/appium/issues/7493 is tracking the enhancement

**Comment by pvj** [comment]
Hi, sorry for the necro. I'm running an Android w/ API level 23 and just upgraded to Appium 1.6.4 beta, but I'm still not seeing the -g flag passed. Would you be able to help me pointing me to the right direction?

**Comment by imurchie** [comment]
Use the `autoGrantPermissions` desired capability (set to "true"). It is done by an alternative means, because the -g flag broke a lot of other things.

**Comment by pvj** [comment]
Hi @imurchie 

Thanks! I was just about to update my comment, as I ended up finding and using exactly just that. 

Thanks for the quick response, glad to know that I'm using the proper approach here.

**Comment by egorvas** [comment]
In my case Id like to reset my application after each test, like:

```
    @AfterMethod(alwaysRun = true)
    public void finishTest(ITestResult result) {
        if (driver!=null){
            driver.resetApp();
        }
    }
```

So, if I using autoGrantPermissions = true it works only for the first test, because after reset permissions resets also. May be any one knows way for to set permission after each start of application without additional driver init.(because it takes lots of time).
