### ISSUE TITLE
method app_installed? always returning true with specific server launch options

### ISSUE THREAD

**Issue by wili3** [appium/appium#5563]
It happens when:
- launching the appium server from source with the -U (udid) option. => node . -U
- launching the Appium.app with the udid checked inside iOS launch options.

When the server is initialized with this parameters and the test is executed in a iOS real device, the method app_installed? always returns true no matter the argument you pass to the method.

further information in this issue post from appium ruby repo. 
https://github.com/appium/ruby_lib/issues/350

**Comment by scottdixon** [comment]
hmm this isn't ideal! Can you please try a more recent version of Appium to see if the issue have been resolved?
