### ISSUE TITLE
 'java -version' failed. Error: spawn ENOENT

### ISSUE THREAD

**Issue by canb0** [appium/appium#5564]
I encounter a problem while executing my appium test.

at C:\Canberk\Appium\node_modules\appium\lib\devices\android\android-common.js:1033:17
at exithandler (child_process.js:633:7)
at ChildProcess.errorhandler (child_process.js:649:5)
at ChildProcess.EventEmitter.emit (events.js:95:17)
at Process.ChildProcess._handle.onexit (child_process.js:795:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: 'java -version' failed. Error: spawn ENOENT)","origValue":"'java -version' failed. Error: spawn ENOENT"},"sessionId":null}
info: <-- POST /wd/hub/session 500 210.506 ms - 208 
.
When I run "java -version" in command line there's no problem but when I execute cmd.exe /s /c "java -version" I got an error. I have JAVA_HOME in my PATH variable. How can I debug this problem.

"Specified path cannot be found" (sorry for mistranslation) is captured at the 1st line
I am using Windows 8.1 

![command](https://cloud.githubusercontent.com/assets/13525544/9679813/7d9266be-52fa-11e5-8cd3-e46804a91f8f.png)

**Comment by rets5s** [comment]
What path value did you set for JAVA_HOME?

**Comment by canb0** [comment]
I have

JAVA_HOME = C:\Program Files\Java\jdk1.7.0_79 I also tried C:\Progra~1\Java\jdk1.7.0_79 
and 
PATH variable has %JAVA_HOME%\bin

I also have a java.exe in my c:\windows\system32 folder , I renamed it in case it doesnt interfere with JAVA_HOME cause I have %SYSTEMRoot%\System32 variable in my Path
![command](https://cloud.githubusercontent.com/assets/13525544/9688677/5ef5df94-5339-11e5-90bc-5a4afd34c050.png)

**Comment by rets5s** [comment]
Someone before you had the same issue. Try following this https://github.com/appium/appium/issues/4229
I hope this helps.

**Comment by keytorc** [comment]
I resolved the problem. Those links saved my life: http://stackoverflow.com/questions/13316682/windows-cmd-exe-the-system-cannot-find-the-path-specified & http://carol-nichols.com/2011/03/17/the-system-cannot-find-the-path-specified/

**Comment by canb0** [comment]
I resolved the problem. Those links saved my life: http://stackoverflow.com/questions/13316682/windows-cmd-exe-the-system-cannot-find-the-path-specified & http://carol-nichols.com/2011/03/17/the-system-cannot-find-the-path-specified/

**Comment by reddyontp** [comment]
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: 'java -version' failed. Error: spawn ENOENT)","origValue":"'java -version' failed. Error: spawn ENOENT"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 28.621 ms - 208
