### ISSUE TITLE
Unable to sendkeys in Password field for iOS app in Simulator

### ISSUE THREAD

**Issue by JasjitKaur** [appium/appium#5565]
We are not able to sendkeys to password field in my app, when we run it on simulator(haven't tried in real device). Details: 

appium 1.4.8(GUI), 1.3.0(GUI), 1.4.3(command line)
OSX Yoshemite (10.10.3 beta)
Xcode - 6.3
Simulator - iPhone 5s, iPhone 6
iOS - 8.1, 8.2

Error Logs:  

DEBUG: Formatted failure output: 

 Failure/error: login.login("xyze@mail.com", "tester")

Exception: undefined method `send_keys' for nil:NilClass
# /Users/tester/Desktop/app/xxxx/Common/pages_helper.rb:56:in `send_keys'

 #/Users/tester/Desktop/app/xxxx/Pages/login_page.rb:49:in `login'

 #./test_spec.rb:9:in `block (2 levels) in <top (required)>'

**Comment by rets5s** [comment]
Can you provide some of your code? Also it seems like you missed spelled send keys method.
It should look something like that ```driver.findElement(By.id("email")).sendKeys(email);```

**Comment by JasjitKaur** [comment]
We are using 'Ruby' language for automating iOS app.

Here is the code:

def password_field
find_element(:textfield, "Password")
end

 - password_field.send_keys(password);

**Comment by rets5s** [comment]
it seems that you function not returning anything.Try adding return like this. 
```
def password_field
      return find_element(:textfield, "Password")
end
```

**Comment by scottdixon** [comment]
@JasjitKaur - does the issue persist?
