### ISSUE TITLE
Cannot use Appium with a Selenium Grid running in a Docker container

### ISSUE THREAD

**Issue by jderrien** [appium/appium#5566]
Hello everyone,

I'm trying to run Selenium tests on iOS with a Selenium hub hosted in a Docker container.

Useful reference about [how docker networks a container](https://docs.docker.com/articles/networking/#how-docker-networks-a-container).

By default Docker containers runs with the options `--net=bridge`. In this case, binding the Selenium Grid port on the Docker host involves a NAT. I'm getting these errors:
```
[Forwarding newSession on session null to remote] INFO org.apache.http.impl.execchain.RetryExec  - I/O exception (java.net.SocketException) caught when processing request to {}->http://192.168.200.240:4444: Network is unreachable
[Forwarding newSession on session null to remote] INFO org.apache.http.impl.execchain.RetryExec  - Retrying request to {}->http://192.168.200.240:4444
```

`192.168.200.240` is the private IP address of the Selenium hub. This one is NATed and so not accessible from the nodes.

Then I've tried the option `--net=host` of the `docker run` command. In this case the network is no more isolated (no more NAT), and the container uses the host network.

I was surprised to get a similar error:
```
[Forwarding newSession on session null to remote] INFO org.apache.http.impl.execchain.RetryExec  - I/O exception (java.net.SocketException) caught when processing request to {}->http://192.168.200.1:4444: Network is unreachable
[Forwarding newSession on session null to remote] INFO org.apache.http.impl.execchain.RetryExec  - Retrying request to {}->http://192.168.200.1:4444
```

Where `192.168.200.1` is the IP address of the `docker0` interface (the default Docker bridge).

Finally I had to bind the Selenium Hub to the right interface with the `-host` option to get the tests working.

Anyway, this is a strange behaviour, isn't it? I'm posting this issue here since it works well with classic Selenium nodes.

On the node, I can see the emulator starting, but it never receives the commands. I didn't see any reference to 192.168.200.x in the logs (with log level to debug).

The node configuration is:
```
{
  "capabilities": [
    {
      "browserName": "iPhone5s",
      "version":"8.2",
      "maxInstances": 1,
      "platform":"MAC"
    }
  ],
  "configuration": {
    "cleanUpCycle": 2000,
    "timeout": 30000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url": "http://osxm-ios-int01:5555/wd/hub",
    "host": "osxm-ios-int01",
    "port": 5555,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "selenium-int"
  }
}
```

`selenium-int` resolves to `10.100.4.13`. I've reproduced with Appium 1.3.7 and 1.4.8. I'm using iOS 8.2 and XCode 6.2.

Any idea? Thanks.

**Comment by jderrien** [comment]
Closing this issue for now. It could be related to code of the tests (I don't know why for now).

**Comment by jderrien** [comment]
Finally it's not related to Appium but to the Selenium Grid that responds a 303 See Other HTTP response with the bad ip address as the URI hostname.

The interesting part is I've tested with the Selenium Java Webdriver and the Ruby one. The first one follows the redirect as it with the bad host while the second does not. This was confusing. I should continue to investigate a bit and eventually report this issue to the Selenium team.

**Comment by jderrien** [comment]
To get it working with `--net=bridge`, I've finally used the `--hostname <hostname>` option in the `docker run` command. This adds the corresponding entry in `/etc/hosts`.

Then I've just used the `-host <hostname>` command when starting the Selenium Grid with the right hostname.

So `<hostname>` is resolved to the container's internal IP address in the container context and to the docker host's IP address externally (if you have setup the DNS correctly). And finally, it redirects to the right hostname when an HTTP redirection occurs.

**Comment by jderrien** [comment]
Finally found that the Ruby Selenium web driver drops the protocol/host/port part from the {{Location}} header but only keep the path ([ref](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/remote/http/default.rb#L95)).

What I've seen is now obvious.

**Comment by jderrien** [comment]
Last point, it seems that other nodes return a 200 OK response with JSON serialized data containing `sessionId` and other stuff.

Appium prefers to return a redirection 303 (See Other), ref [here](https://github.com/appium/appium/blob/v1.4.8/lib/server/controller.js#L181).

**Comment by Simon-Kaz** [comment]
This is interesting and totally related to what I'm working on - thanks for keeping us updated.
