### ISSUE TITLE
[Question] [IOS] Return application from background to foreground

### ISSUE THREAD

**Issue by noymn** [appium/appium#5567]
I don't know if this is a bug or a designed behaviour but I have a problem with returning a backgrounded app to foreground.

I have an application that has a way to redirect people to the store in order to download other applications. That action is bound to a button and opens the device marketplace. I also have coded the automation of those tasks, getting the user to the store and having the main application backgrounded, but I am unable to return to the application on iOS platform.

I use `runAppInBackground` method to return the application from background (in fact it sends it to background and recovers it) but that method only works properly on Android (1.3.7). When doing the same on iOS the application that is backgrounded is the AppStore (current foreground application) (1.4.8).

My first question is: Can I get my application back? How?
Then the other question arises: Why is Android returning the launched application to foreground and iOS is working on the foreground app to background and return? Is that intended?

Note: I can not use 1.3.7 on iOS since iOS 8.x broke support on `runAppInBackground`, nor can I use 1.4.8 on Android because 1.4.x version has a bug that restarts the application.

**Comment by scottdixon** [comment]
@noymn - please give Appium 1.5 a shot. Reopen this issue if you get stuck and I'll investigate further.
