### ISSUE TITLE
could appium support chrome browser test on ios 

### ISSUE THREAD

**Issue by xlzdew** [appium/appium#5569]
In the official doc, I saw it said Appium supports Safari on iOS and Chrome or the built-in 'Browser' app on Android.  Could appium support Chrome on iOS either？
I want to choose a suitable tools for mobile automating testing in my project, and the Chrome browser testing in iOS is important part of  compatibility auto testing. 
Thanks in advance.

**Comment by scottdixon** [comment]
Sorry for the delay! Appium doesn't support Chrome on iOS.
