### ISSUE TITLE
Swipe cant work well. iOS 8.4. Appium 1.4.0

### ISSUE THREAD

**Issue by jane-misfit** [appium/appium#5571]
My code:
exports.swipe = function (opts) {
  var action = new wd.TouchAction();
  action
    .press({x: opts.startX, y: opts.startY})
    .wait(opts.duration)
    .moveTo({x: opts.endX, y: opts.endY})
    .release();
  return this.performTouchAction(action);};

-----------------------------------------------------------------------------------
  it("should swipe to sync", function(){
      return driver.elementByXPath(" //UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIACollectionView[1]/UIACollectionCell[31]").
      then(function(){
          return driver.swipe({ startX: 30, startY: 200, endX: 250,  endY: 200, duration: 4000 });
      });});

-----------------------------------------------------------------------------------
Result:
 > CALL elementByXPath(" //UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIACollectionView[1]/UIACollectionCell[31]") 
 > POST /session/:sessionID/element {"using":"xpath","value":" //UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIACollectionView[1]/UIACollectionCell[31]"}
 > RESPONSE elementByXPath(" //UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIACollectionView[1]/UIACollectionCell[31]") {"ELEMENT":"7"}

 > CALL performTouchAction([{"action":"press","options":{"x":30,"y":200}},{"action":"wait","options":{"ms":4000}},{"action":"moveTo","options":{"x":250,"y":200}},{"action":"release","options":{}}]) 
 > POST /session/:sessionID/touch/perform [{"action":"press","options":{"x":30,"y":200}},{"action":"wait","options":{"ms":4000}},{"action":"moveTo","options":{"x":250,"y":200}},{"action":"release","options":{}}]
 > RESPONSE performTouchAction([{"action":"press","options":{"x":30,"y":200}},{"action":"wait","options":{"ms":4000}},{"action":"moveTo","options":{"x":250,"y":200}},{"action":"release","options":{}}]) ""
    ✓ should swipe to sync (15663ms)
 > CALL quit() 
 > DELETE /session/:sessionID 

Question:  I cant see the swipe in my screen. but there is no error log in the executing result. 
Can you help me ? 
![ba570a2a-7454-47c1-a4ec-92eaa81bc1d7](https://cloud.githubusercontent.com/assets/10269059/9703482/d5e5d79c-54b7-11e5-999c-ae869bfefb2c.png)

**Comment by valarmathivrv** [comment]
I am also facing same issue regarding swipe action in 8.4 simulator.

**Comment by jane-misfit** [comment]
I switched to real device. and the same code. it works.

**Comment by moizjv** [comment]
@jane-misfit and @valarmathivrv https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md#bugs-and-workarounds
