### ISSUE TITLE
Appium chromedriver halt when trying to switch to a "untitle" window

### ISSUE THREAD

**Issue by esoests** [appium/appium#5572]
I am using Appium on AndroidPhone 5.0 to automate a multiple webviews hybird app which interacts with third party app.
So setting -DautomationName as Appium should be the right strategy.

When switching to Webview context, I am trying to switch to each window to operate html elements, according to: appium/appium#3775 It works around well.
My problem is that sometimes, there are some untitled webview generated, when trying to switch to those untitled windows, appium server will halt and no response anymore.

Here is the appium-server log:
info: [debug] Proxying command to 127.0.0.1:9515
info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/55d219b675ddd645640fb78095906261/window","method":"POST","json":{"name":"CDwindow-34DC403F-AF6E-D996-4E3E-690BC2B06585"}}
info: [debug] Proxied response received with status 200: {"sessionId":"55d219b675ddd645640fb78095906261","status":0,"value":null}
info: <-- POST /wd/hub/session/bb1cc0b9-c33d-4194-b0d6-85affca3b67d/window 200 10.189 ms - 72
info: --> POST /wd/hub/session/bb1cc0b9-c33d-4194-b0d6-85affca3b67d/window {"name":"CDwindow-74C40368-43DF-7CCA-9646-EBA007FC82A5"}
info: [debug] Proxying command to 127.0.0.1:9515
info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/55d219b675ddd645640fb78095906261/window","method":"POST","json":{"name":"CDwindow-74C40368-43DF-7CCA-9646-EBA007FC82A5"}}
info: [debug] Proxied response received with status 200: {"sessionId":"55d219b675ddd645640fb78095906261","status":0,"value":null}
info: <-- POST /wd/hub/session/bb1cc0b9-c33d-4194-b0d6-85affca3b67d/window 200 9.791 ms - 72
info: --> GET /wd/hub/session/bb1cc0b9-c33d-4194-b0d6-85affca3b67d/window_handle {}
info: [debug] Proxying command to 127.0.0.1:9515
info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/55d219b675ddd645640fb78095906261/window_handle","method":"GET"}
info: [debug] Proxied response received with status 200: "{\"sessionId\":\"55d219b675ddd645640fb78095906261\",\"status\":0,\"value\":\"CDwindow-74C40368-43DF-7CCA-9646-EBA007FC82A5\"}"
info: <-- GET /wd/hub/session/bb1cc0b9-c33d-4194-b0d6-85affca3b67d/window_handle 200 2.731 ms - 115
info: --> GET /wd/hub/session/bb1cc0b9-c33d-4194-b0d6-85affca3b67d/title {}
info: [debug] Proxying command to 127.0.0.1:9515
info: [debug] Making http request with opts: {"url":"http://127.0.0.1:9515/wd/hub/session/55d219b675ddd645640fb78095906261/title","method":"GET"}

<img width="476" alt="webviews" src="https://cloud.githubusercontent.com/assets/8383787/9622530/ac8465e8-5166-11e5-87d2-9821a123fd0c.png">

**Comment by Jonahss** [comment]
Good bug, thank you for reporting. Shouldn't be hard for us to fix :)

**Comment by esoests** [comment]
Which release is this fix target for? is it possible in release 1.5?

**Comment by esoests** [comment]
@Jonahss Do you have time to look at it recently?

**Comment by scottdixon** [comment]
@esoests - does the issue persist?

**Comment by esoests** [comment]
Yes, @scottdixon  any idea how to fix it?

**Comment by jlipps** [comment]
Handling window changes is purely a Chromedriver-internal issue. If it's having problems with untitled views, I don't think that that's anything Appium can solve, unfortunately. Closing for now.
