### ISSUE TITLE
Appium failed to create session for device having API level 17 or higher if there is another device using API level lesser than 17 connected

### ISSUE THREAD

**Issue by swippy** [appium/appium#5573]
Below is the setup:
- 2 real devices connected to my Macbook (OS X 10.10.2)
  * One is using Android Jelly Bean 4.1.2 (API 16)  --> device ID = 0019ab1e4c4e2f
  * The other one is using Android 5.0 (API 21)  --> device ID = 526026517414
- Appium 1.4.10
- Java 1.8.0_05

In my test script, I include the device name that belongs to second device (device ID = 526026517414) in the DesiredCapabilities.
When I ran the script (I'm using IntelliJ), I noticed that the Appium server raised an error:

info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/xxx/Library/Android/sdk/platform-tools/adb devices
info: [debug] 2 device(s) connected
info: Found device 0019ab1e4c4e2f
info: [debug] Setting device id to 0019ab1e4c4e2f
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /Users/xxx/Library/Android/sdk/platform-tools/adb -s 0019ab1e4c4e2f wait-for-device
info: [debug] executing cmd: /Users/xxx/Library/Android/sdk/platform-tools/adb -s 0019ab1e4c4e2f shell "echo 'ready'"
info: [debug] Starting logcat capture
info: [debug] Getting device API level
info: [debug] executing cmd: /Users/xxx/Library/Android/sdk/platform-tools/adb -s 0019ab1e4c4e2f shell "getprop ro.build.version.sdk"
info: [debug] Device is at API Level 16
info: Device API level is: 16
error: Android devices must be of API level 17 or higher. Please change your device to Selendroid or upgrade Android on your device.
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
warn: UiAutomator did not shut down fast enough, calling it gone
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Android devices must be of API level 17 or higher. Please change your device to Selendroid or upgrade Android on your device.
info: [debug] Error: Android devices must be of API level 17 or higher. Please change your device to Selendroid or upgrade Android on your device.
    at /usr/local/lib/node_modules/appium/lib/devices/android/android.js:284:17
    at /usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:636:7
    at [object Object].<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-adb/lib/adb.js:180:9)
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Android devices must be of API level 17 or higher. Please change your device to Selendroid or upgrade Android on your device.)","origValue":"Android devices must be of API level 17 or higher. Please change your device to Selendroid or upgrade Android on your device."},"sessionId":null}

Error shown on IntelliJ:
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Android devices must be of API level 17 or higher. Please change your device to Selendroid or upgrade Android on your device.) (WARNING: The server did not provide any stacktrace information)

The appium detected 2 devices, which is correct.
The first detected device is the device using Jelly Bean on it.
And since the device using Jelly Bean (API 16), which is less than the supported API level of Appium (17), the Appium won't started to execute the test cases.

I was expecting that, since I use the device name (or device ID = 526026517414), the Appium should skipped the first detected device (because it has different device name/ID = 0019ab1e4c4e2f) and continued to the second device. I see that the Appium was starting to logcat capture on the first device first. It seems wrong to me, because I didn't put the first device name/ID but instead the second one in the DesiredCapabilities.

Conclusion:
Appium should have checked the device name in the DesiredCapabilities with the connected devices, skip or ignore to start the logcat capture on device that is not defined and should only started the logcat capture on the right device. If the desired device is not connected, then Appium should have aborted the logcat capture at all.

Anyway, before reproducing this issue, please be noticed that you should:
- attach the device running API level lesser than 17 as the first device
- attach the second device running API level 17 or above afterwards
Otherwise the issue will not be able to be reproduced.

**Comment by SrinivasanTarget** [comment]
Please try a latest version of appium and raise a new issue incase if you hit the same.

**Comment by SrinivasanTarget** [comment]
@triager please close
