### ISSUE TITLE
Can't find an element on a webview page of an andriod native app using Appium

### ISSUE THREAD

**Issue by thoratabhi** [appium/appium#5574]
I am not able to find the elements from android.webkit.webview package using java appium script.

How to get the userText field and password field locators.so that i can pass the value to UI using the Appium script.
![sample](https://cloud.githubusercontent.com/assets/14161758/9716002/622aa0ae-5583-11e5-9ecc-8eae02388c8a.jpg)

**Comment by SrinivasanTarget** [comment]
https://developer.chrome.com/devtools/docs/remote-debugging

**Comment by SrinivasanTarget** [comment]
@triager please close
