### ISSUE TITLE
unable to find the web elements 

### ISSUE THREAD

**Issue by RasoolShaik** [appium/appium#5578]
Hi Team,

One of the apk is developed by using web application. Here web application is developed by ionic framework.So the problem here is appium is unable to find the web elements on the corresponding apk.

Note : appium will support ionic frame work or not, just i want to confirm.please help me. it was great help.

Thanking you,
Rasool Shaik

**Comment by scottdixon** [comment]
@RasoolShaik you should be able to switch into the web context. Reopen if you get stuck.
