### ISSUE TITLE
Mobile Safari browser not getting closed in iPad Air 2 (iOS 8.1) on executing webdriver.quit() command

### ISSUE THREAD

**Issue by Kannadasan-Bose** [appium/appium#5581]
**Issue Description:** On executing the selenium scripts, after running both Appium server (UI Version) and ios_webkit_debug_proxy, the Safari browser is getting launched successfully in iPad Air 2, it does all testing as given in script, but once the script execution is done, when the webdriver.quit() command is executed to close the browser, it is not closing the browser.

When the next script is executed, it is opening one more new tab in the existing browser. In short, when it is executing the fourth script, there would be four tabs in the browser.

**Version Details:**
1. Mac: Yosemite OS X 10.10.2
2. XCode: 6.4
3. iOS: 8.1
4. Appium: 1.4.8
5. Appium Java Client: 3.1
6. Selenium Standalone jar: 2.47.0
7. Browser used: Safari
8. Device Used: iPad Air 2

Please let me know if any more detail is required.

Any help is highly appreciated.

**Comment by scottdixon** [comment]
Did you end up resolving this? Have your tried driver.close()?

**Comment by Kannadasan-Bose** [comment]
Hi Scott,

Actually the issue is with particular iOS version 8.0 to 8.2, when we run the same scripts against 8.3, 9.1 and 9.2 version, it ran fine and closed the tabs(as expected) that was opened through scripts.

**Note:** Both "driver.quit()" and "driver.close()" were used in the 8.0 to 8.2 versions as well, it even get executed, but it didn't close the browser tabs.

**Comment by khanhdodang** [comment]
Hi all,
I also got the same issue during run test on real device iPhone 6 iOS 9.2.1

**Comment by scottdixon** [comment]
Thanks @Kannadasan-Bose. I'll see if I can repro.
