### ISSUE TITLE
How to get the Image from apium webdriver

### ISSUE THREAD

**Issue by Dhanasekahar** [appium/appium#5582]
Hi,

I wanted get image from my android app, I am able to locate the element by id.
Can any one help me to get the image from web element.

**Comment by Fanch-** [comment]
I guess you can ask it here on the gitter chat : https://gitter.im/appium/appium.

**Comment by daluu** [comment]
Take screenshot of the screen then crop it to element's size using it's size (width, height) and x,y location? They have this technique for Selenium WebDriver for the web, you can probably adapt it for Appium for mobile app. Just search online for the tip.
