### ISSUE TITLE
Ubuntu: appium installation error

### ISSUE THREAD

**Issue by toralMevada** [appium/appium#5583]
npm ERR! tar.unpack untar error /tmp/npm-17089-d8dac47a/registry.npmjs.org/appium-uiauto/-/appium-uiauto-1.10.8.tgz
npm ERR! tar.unpack untar error /tmp/npm-17089-d8dac47a/registry.npmjs.org/date-utils/-/date-utils-1.2.17.tgz
npm ERR! tar.unpack untar error /tmp/npm-17089-d8dac47a/registry.npmjs.org/appium-instruments/-/appium-instruments-2.0.5.tgz
^Ctoral@toral:~$ npm install appium -g
npm ERR! Linux 3.5.0-23-generic
npm ERR! argv "node" "/home/toral/.linuxbrew/bin/npm" "install" "appium" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! path /home/toral/.linuxbrew/lib/node_modules/appium/node_modules/mocha/node_modules/.bin/jade
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/home/toral/.linuxbrew/lib/node_modules/appium/node_modules/mocha/node_modules/.bin/jade'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/home/toral/.linuxbrew/lib/node_modules/appium/node_modules/mocha/node_modules/.bin/jade']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/toral/.linuxbrew/lib/node_modules/appium/node_modules/mocha/node_modules/.bin/jade' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/home/toral/.linuxbrew/lib/node_modules/appium/node_modules/mocha/node_modules/.bin/jade'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/home/toral/.linuxbrew/lib/node_modules/appium/node_modules/mocha/node_modules/.bin/jade']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/toral/.linuxbrew/lib/node_modules/appium/node_modules/mocha/node_modules/.bin/jade' }

npm ERR! Please include the following file with any support request:
npm ERR!     /home/toral/npm-debug.log

**Comment by rets5s** [comment]
What did you use to install nodejs?

**Comment by sebv** [comment]
try;
`npm upgrade -g npm; npm -g cache clear; npm install appium`

But it is better to install locally:

```
mkdir appium_install && cd appium_install
npm init # return, return ......
npm cache clear
npm install appium
./node_modules/.bin/appium
```

**Comment by toralMevada** [comment]
Installed nodejs using brew: 
$ brew install node

**Comment by toralMevada** [comment]
Same error with "npm upgrade -g npm; npm -g cache clear; npm install -g appium" 

did not understand how to execute 'npm init' ?

**Comment by rets5s** [comment]
As sebv mentioned earlier: 
- Using command console navigate to the  folder where you want to install appium.
- In command console type npm init and follow instruction.
- Follow rest of the steps provided by sebv.

**Comment by rets5s** [comment]
When you execute `npm init` just keep hitting enter until its done.

**Comment by toralMevada** [comment]
Getting same error after following steps from "sebv".

npm-debug.logs: 

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/home/toral/.linuxbrew/bin/npm',
1 verbose cli   'install',
1 verbose cli   'appium',
1 verbose cli   './node_modules/.bin/appium' ]
2 info using npm@2.14.2
3 info using node@v0.12.7
4 verbose node symlink /home/toral/.linuxbrew/bin/node
5 verbose config Skipping project config: /home/toral/.npmrc. (matches userconfig)
6 verbose install initial load of /home/toral/package.json
7 verbose installManyTop reading scoped package data from /home/toral/node_modules/appium/package.json
8 verbose installManyTop reading scoped package data from /home/toral/node_modules/wd/package.json
9 info package.json appium@1.4.10 No license field.
10 verbose readDependencies loading dependencies from /home/toral/package.json
11 verbose install appium is installed as 1.4.10
12 silly cache add args [ 'appium', null ]
13 verbose cache add spec appium
14 silly cache add args [ './node_modules/.bin/appium', null ]
15 verbose cache add spec ./node_modules/.bin/appium
16 silly cache add parsed spec { raw: 'appium',
16 silly cache add   scope: null,
16 silly cache add   name: 'appium',
16 silly cache add   rawSpec: '',
16 silly cache add   spec: '*',
16 silly cache add   type: 'range' }
17 silly addNamed appium@*
18 verbose addNamed "*" is a valid semver range for appium
19 silly addNameRange { name: 'appium', range: '*', hasData: false }
20 silly mapToRegistry name appium
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/appium
24 verbose addNameRange registry:https://registry.npmjs.org/appium not in flight; fetching
25 silly cache add parsed spec { raw: './node_modules/.bin/appium',
25 silly cache add   scope: null,
25 silly cache add   name: null,
25 silly cache add   rawSpec: './node_modules/.bin/appium',
25 silly cache add   spec: '/home/toral/node_modules/.bin/appium',
25 silly cache add   type: 'local' }
26 error addLocal Could not install /home/toral/node_modules/.bin/appium
27 verbose get https://registry.npmjs.org/appium not expired, no request
28 silly addNameRange number 2 { name: 'appium', range: '*', hasData: true }
29 silly addNameRange versions [ 'appium',
29 silly addNameRange   [ '0.0.1',
29 silly addNameRange     '0.0.2',
29 silly addNameRange     '0.0.3',
29 silly addNameRange     '0.0.4',
29 silly addNameRange     '0.0.5',
29 silly addNameRange     '0.0.6',
29 silly addNameRange     '0.0.7',
29 silly addNameRange     '0.0.8',
29 silly addNameRange     '0.0.9',
29 silly addNameRange     '0.0.10',
29 silly addNameRange     '0.0.11',
29 silly addNameRange     '0.0.12',
29 silly addNameRange     '0.0.13',
29 silly addNameRange     '0.0.14',
29 silly addNameRange     '0.0.15',
29 silly addNameRange     '0.1.0',
29 silly addNameRange     '0.1.1',
29 silly addNameRange     '0.1.2',
29 silly addNameRange     '0.2.0',
29 silly addNameRange     '0.2.1',
29 silly addNameRange     '0.2.2',
29 silly addNameRange     '0.2.3',
29 silly addNameRange     '0.3.0',
29 silly addNameRange     '0.3.1',
29 silly addNameRange     '0.4.0',
29 silly addNameRange     '0.4.1',
29 silly addNameRange     '0.5.0',
29 silly addNameRange     '0.5.1',
29 silly addNameRange     '0.5.2',
29 silly addNameRange     '0.6.0',
29 silly addNameRange     '0.6.1',
29 silly addNameRange     '0.7.0',
29 silly addNameRange     '0.7.1',
29 silly addNameRange     '0.7.2',
29 silly addNameRange     '0.7.3',
29 silly addNameRange     '0.8.0',
29 silly addNameRange     '0.8.1',
29 silly addNameRange     '0.8.2',
29 silly addNameRange     '0.8.3',
29 silly addNameRange     '0.8.4',
29 silly addNameRange     '0.8.5',
29 silly addNameRange     '0.9.0',
29 silly addNameRange     '0.9.1',
29 silly addNameRange     '0.10.0',
29 silly addNameRange     '0.10.1',
29 silly addNameRange     '0.10.2',
29 silly addNameRange     '0.10.3',
29 silly addNameRange     '0.10.4',
29 silly addNameRange     '0.11.0',
29 silly addNameRange     '0.11.1',
29 silly addNameRange     '0.11.2',
29 silly addNameRange     '0.11.3',
29 silly addNameRange     '0.11.4',
29 silly addNameRange     '0.12.0',
29 silly addNameRange     '0.12.1-b',
29 silly addNameRange     '0.12.2',
29 silly addNameRange     '0.12.3',
29 silly addNameRange     '0.13.0',
29 silly addNameRange     '0.14.0',
29 silly addNameRange     '0.14.1',
29 silly addNameRange     '0.14.2',
29 silly addNameRange     '0.15.0',
29 silly addNameRange     '0.16.0',
29 silly addNameRange     '0.17.0',
29 silly addNameRange     '0.17.2',
29 silly addNameRange     '0.17.3',
29 silly addNameRange     '0.17.4',
29 silly addNameRange     '0.17.5',
29 silly addNameRange     '0.17.6',
29 silly addNameRange     '0.18.0',
29 silly addNameRange     '0.18.1',
29 silly addNameRange     '1.0.0-beta.1',
29 silly addNameRange     '0.18.2',
29 silly addNameRange     '1.0.0-beta.2',
29 silly addNameRange     '1.0.0',
29 silly addNameRange     '1.1.0',
29 silly addNameRange     '1.2.0',
29 silly addNameRange     '1.2.1',
29 silly addNameRange     '1.2.2',
29 silly addNameRange     '1.2.3',
29 silly addNameRange     '1.3.0-beta1',
29 silly addNameRange     '1.2.4',
29 silly addNameRange     '1.3.0',
29 silly addNameRange     '1.3.1',
29 silly addNameRange     '1.3.2-beta2',
29 silly addNameRange     '1.3.3',
29 silly addNameRange     '1.3.4-beta1',
29 silly addNameRange     '1.3.4',
29 silly addNameRange     '1.3.5-beta',
29 silly addNameRange     '1.3.5',
29 silly addNameRange     '1.3.6',
29 silly addNameRange     '1.3.7',
29 silly addNameRange     '1.4.0-beta',
29 silly addNameRange     '1.4.0',
29 silly addNameRange     '1.4.1',
29 silly addNameRange     '1.4.2',
29 silly addNameRange     '1.4.3-beta',
29 silly addNameRange     '1.4.3',
29 silly addNameRange     '1.4.4',
29 silly addNameRange     '1.4.5-beta',
29 silly addNameRange     '1.4.5',
29 silly addNameRange     '1.4.6-beta',
29 silly addNameRange     '1.4.6-beta2',
29 silly addNameRange     '1.4.6',
29 silly addNameRange     '1.4.7-beta',
29 silly addNameRange     '1.4.7-beta2',
29 silly addNameRange     '1.4.7-beta3',
29 silly addNameRange     '1.4.7',
29 silly addNameRange     '1.4.8-beta',
29 silly addNameRange     '1.4.8',
29 silly addNameRange     '1.4.9-beta',
29 silly addNameRange     '1.4.10',
29 silly addNameRange     '1.5.0-beta1' ] ]
30 silly addNamed appium@1.4.10
31 verbose addNamed "1.4.10" is a plain semver version for appium
32 silly cache afterAdd appium@1.4.10
33 verbose afterAdd /home/toral/.npm/appium/1.4.10/package/package.json not in flight; writing
34 verbose afterAdd /home/toral/.npm/appium/1.4.10/package/package.json written
35 verbose stack Error: ENOENT, open '/home/toral/node_modules/.bin/appium'
35 verbose stack     at Error (native)
36 verbose cwd /home/toral
37 error Linux 3.5.0-23-generic
38 error argv "node" "/home/toral/.linuxbrew/bin/npm" "install" "appium" "./node_modules/.bin/appium"
39 error node v0.12.7
40 error npm  v2.14.2
41 error path /home/toral/node_modules/.bin/appium
42 error code ENOENT
43 error errno -2
44 error enoent ENOENT, open '/home/toral/node_modules/.bin/appium'
44 error enoent This is most likely not a problem with npm itself
44 error enoent and is related to npm not being able to find a file.
45 verbose exit [ -2, true ]

**Comment by violet-day** [comment]
+1.I install node by nvm.
node version:4.0.0
npm version:2.14.2
npm ERR! tar.unpack untar error /var/folders/_k/hlxk2qq16mq4vpn1jtgb6rh00000gn/T/npm-18311-4d065bf3/registry.npmjs.org/xml2js/-/xml2js-0.4.9.tgz
npm ERR! tar.unpack error reading /var/folders/_k/hlxk2qq16mq4vpn1jtgb6rh00000gn/T/npm-18311-4d065bf3/registry.npmjs.org/appium-uiauto/-/appium-uiauto-1.10.8.tgz
npm ERR! tar.unpack untar error /var/folders/_k/hlxk2qq16mq4vpn1jtgb6rh00000gn/T/npm-18311-4d065bf3/registry.npmjs.org/appium-adb/-/appium-adb-1.7.5.tgz
npm ERR! tar.unpack untar error /var/folders/_k/hlxk2qq16mq4vpn1jtgb6rh00000gn/T/npm-18311-4d065bf3/registry.npmjs.org/appium-instruments/-/appium-instruments-2.0.4.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/Nemo/.nvm/versions/node/v4.0.0/bin/node" "/Users/Nemo/.nvm/versions/node/v4.0.0/bin/npm" "install" "-g" "appium@1.4.8"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! unexpected eof
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm info preuninstall appium@1.4.8
npm info uninstall appium@1.4.8
npm info postuninstall appium@1.4.8

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Nemo/npm-debug.log

**Comment by scottdixon** [comment]
We've recently release Appium 1.5, please see if this resolves your install woes. `npm install -g appium`.

Reopen if you get stuck.
