### ISSUE TITLE
Android Driver pullFile and pushFile functions are not recognized

### ISSUE THREAD

**Issue by mbukowski42** [appium/appium#5584]
## Scenario
I am running an appium (3.1.0) with java. I managed to connect to device and perform simple tests. 
As a next step I wanted to upload and download file from device. I used following piece of code:
```java
File file = new File("./resources/cloud-01.png");
Path path = Paths.get(file.getAbsolutePath());
byte[] b = Base64.encodeBase64(Files.readAllBytes(path));

driver.pushFile("/sdcard/download/cloud-01.png", b);
driver.pullFile("/sdcard/download/cloud-01.png");
```

I stole a session and tried to invoke the same request from soap ui with different path but I wasn't able to find correct url. When I executed an adb command it worked without any issues.
adb push /sdcard/download/cloud-01.png cloud-01.png
adb pull /sdcard/download/cloud-01.png

If I find some time I will try to pull from repository and check issue myself.

#### Pull
info: --> POST /wd/hub/session/bfe527d594f3e0b282c259cf764d85ff/appium/device/pull_file {"path":"/mnt/sdcard/download/cloud-01.png"}
info: Proxying [POST /wd/hub/session/bfe527d594f3e0b282c259cf764d85ff/appium/device/pull_file] to [POST http://127.0.0.1:9515/wd/hub/session/bfe527d594f3e0b282c259cf764d85ff/appium/device/pull_file] with body: {"path":"/mnt/sdcard/download/cloud-01.png"}
info: Got response with status 404: unknown command: session/bfe527d594f3e0b282c259cf764d85ff/appium/device/pull_file
info: <-- POST /wd/hub/session/bfe527d594f3e0b282c259cf764d85ff/appium/device/pull_file 404 8.000 ms - 83

#### Push 
info: --> POST /wd/hub/session/4741af06ef9cfdc1bd13a944ed3201c8/appium/device/push_file {"path":"/mnt/sdcard/download/cloud-01.png","data":[105,86, ...
info: Proxying [POST /wd/hub/session/4741af06ef9cfdc1bd13a944ed3201c8/appium/device/push_file] to [POST http://127.0.0.1:9515/wd/hub/session/4741af06ef9cfdc1bd13a944ed3201c8/appium/device/push_file] with body: {"path":"/mnt/sdcard/download/cloud-01.png","data":[105,86, ...
info: Got response with status 404: unknown command: session/4741af06ef9cfdc1bd13a944ed3201c8/appium/device/push_file
info: <-- POST /wd/hub/session/4741af06ef9cfdc1bd13a944ed3201c8/appium/device/push_file 404 13.307 ms - 83

**Comment by SrinivasanTarget** [comment]
please try a latest version of java client and appium server.We have this working now.

**Comment by SrinivasanTarget** [comment]
@triager please close
