### ISSUE TITLE
New iOS driver - WebDriverAgent

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5587]
https://github.com/facebook/webdriveragent looks awesome

edit: webdriveragent is currently limited to the iOS simulator and doesn't work on real iOS devices.

**Comment by triangletodd** [comment]
:+1:

**Comment by wimbledon** [comment]
:+1:

**Comment by Jonahss** [comment]
I've begun work on this ^.^
Timeline is about 3 weeks.

**Comment by arikon** [comment]
@Jonahss :+1:

**Comment by kaleposhobios** [comment]
@Jonahss thumbs up agree! Anything that can be done to help with this?

**Comment by Jonahss** [comment]
@kaleposhobios definitely!
Take a look at github.com/appium/appium-xcuitest-driver

It's a working driver right now! Things that need to be worked on:
 - Real Device support - see appium-ios-driver for examples of how to implement
 - More handling of desired capabilities (like sim locale, etc.) again see appium-ios-driver
 - More webdriver api commands suported: The basics are there but things like TouchAction are missing. This needs to be implemented in facebook/webDriverAgent

Looking for community help!

**Comment by kaleposhobios** [comment]
Hi Jonah,

That's great, thanks for that. I'm trying to get it set up.

I get this error. Any ideas?

info MJSONWP Calling WebDriverAgentDriver.createSession() with args:
[{"deviceName":"iPhone
6","udid":"BBE5DF23-BC41-4EB0-ADC1-71F6B6DA5C38","app":"/Users/mhorst/Source/skorupi/OneRx//build/Ad
Hoc Staging-iphonesimul...

WARN BaseDriver The following capabilities were provided, but are not
recognized by appium: app, bundleId.

info BaseDriver Session created with session id:
7e99f6f3-5a22-4297-a18c-b6587e68ba09

info WebDriverAgent-driver Determining device to run tests on

info simctl Executing: xcrun with args: simctl list devices and timeout: 0

ERR! WebDriverAgent-driver Error: Could not match line

ERR! WebDriverAgent-driver     at getDevices$ (lib/simctl.js:160:15)

ERR! WebDriverAgent-driver     at tryCatch
(/Users/mhorst/opensource/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)

ERR! WebDriverAgent-driver     at GeneratorFunctionPrototype.invoke [as
_invoke]
(/Users/mhorst/opensource/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:315:22)

ERR! WebDriverAgent-driver     at
GeneratorFunctionPrototype.prototype.(anonymous function) [as next]
(/Users/mhorst/opensource/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:100:21)

ERR! WebDriverAgent-driver     at GeneratorFunctionPrototype.invoke
(/Users/mhorst/opensource/appium-xcuitest-driver/node_modules/babel-runtime/regenerator/runtime.js:136:37)

ERR! WebDriverAgent-driver     at run
(/Users/mhorst/opensource/appium-xcuitest-driver/node_modules/core-js/library/modules/es6.promise.js:104:47)

ERR! WebDriverAgent-driver     at
/Users/mhorst/opensource/appium-xcuitest-driver/node_modules/core-js/library/modules/es6.promise.js:115:28

ERR! WebDriverAgent-driver     at flush
(/Users/mhorst/opensource/appium-xcuitest-driver/node_modules/core-js/library/modules/$.microtask.js:19:5)

ERR! WebDriverAgent-driver     at nextTickCallbackWith0Args (node.js:433:9)

ERR! WebDriverAgent-driver     at process._tickCallback (node.js:362:13)

ERR! WebDriverAgent-driver  [Error: Could not match line]

**Comment by Jonahss** [comment]
@kaleposhobios Thank you for bringing this up.
If this doesn't work for you, appium 1.5 might not either! We need to figure out why it didn't work.

The line of code throwing the error is here: https://github.com/appium/node-simctl/blob/8d399f4e4c6ffa7e4c8ad948e847d5a949d2e662/lib/simctl.js#L160

This is a small module we made to control iOS simulators. You could try debugging the `getDevices()` function in the `node-simctl` module.

To help me debug it, could you post the output of running the following in your terminal?
`xcrun simctl list devices`

**Comment by kaleposhobios** [comment]
Hi Jonah,

Actually I was doing the same steps to figure out the issue. Below is the
list. I'm not sure why the regex is failing.

But quickly, can I ask you, to get it to even run I finally figured out:

./node_modules/.bin/babel-node index.js


Is that right? And along with that, I tried to make code changes to simctl
to debug it, but my changes didn't seem to go into effect. Is there
something else I have to do?


== Device Types ==

iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)

iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)

iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)

iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)

iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)

iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)

iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)

iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)

iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)

iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)

iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)

iPad Pro (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)

Apple TV 1080p (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)

Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)

Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)

== Runtimes ==

iOS 7.1 (7.1 - 11D167) (com.apple.CoreSimulator.SimRuntime.iOS-7-1)
(unavailable, failed to open liblaunch_sim.dylib)

iOS 8.3 (8.3 - 12F70) (com.apple.CoreSimulator.SimRuntime.iOS-8-3)
(unavailable, failed to open liblaunch_sim.dylib)

iOS 8.4 (8.4 - 12H141) (com.apple.CoreSimulator.SimRuntime.iOS-8-4)

iOS 9.0 (9.0 - 13A344) (com.apple.CoreSimulator.SimRuntime.iOS-9-0)

iOS 9.1 (9.1 - 13B143) (com.apple.CoreSimulator.SimRuntime.iOS-9-1)

iOS 9.2 (9.2 - 13C75) (com.apple.CoreSimulator.SimRuntime.iOS-9-2)

tvOS 9.1 (9.1 - 13U78) (com.apple.CoreSimulator.SimRuntime.tvOS-9-1)

watchOS 2.0 (2.0 - 13S343) (com.apple.CoreSimulator.SimRuntime.watchOS-2-0)

watchOS 2.1 (2.1 - 13S660) (com.apple.CoreSimulator.SimRuntime.watchOS-2-1)

== Devices ==

-- iOS 7.1 --

-- iOS 8.3 --

-- iOS 8.4 --

    iPhone 4s (747604C3-C215-4706-9CF4-623F522A2EC7) (Shutdown)

    iPhone 5 (B55242E8-4F25-4808-A840-765409A48556) (Shutdown)

    iPhone 5s (FF39C826-018E-4C7B-B99A-6EAA7A4394B4) (Shutdown)

    iPhone 6 (528646C0-9BC1-4E9B-B49F-D4F5DBD27523) (Shutdown)

    iPhone 6 Plus (C04D6C40-E66B-428D-A47F-7F1E70790FC6) (Shutdown)

    iPad 2 (44FD7B6F-3239-43F3-9A18-BAD87CAF1CDC) (Shutdown)

    iPad Retina (AA6659C3-2473-43AC-A9F2-7CCE56508B26) (Shutdown)

    iPad Air (2B81FFDB-0FC2-44F4-9490-25D1CC68631D) (Shutdown)

-- iOS 9.0 --

-- iOS 9.1 --

-- iOS 9.2 --

    iPhone 4s (A7A3EF59-474F-45C4-9B3D-29990770D393) (Shutdown)

    iPhone 5 (AF3011AB-6292-4EE5-AB2E-9B73C0EF64F5) (Shutdown)

    iPhone 5s (BBE5DF23-BC41-4EB0-ADC1-71F6B6DA5C38) (Shutdown)

    iPhone 6 (8CA18A1B-2316-4044-BF07-6E3E189FCDFF) (Shutdown)

    iPhone 6 (Appium) {1} (F66E9C50-DF6E-4C08-B445-550A915CF6E2) (Shutdown)

    iPhone 6 Plus (AC876DF5-2659-44BC-B047-147E9831E82B) (Shutdown)

    iPhone 6s (4070BEDA-14A0-46C6-8B9E-C66B69D71791) (Shutdown)

    appiumTest-220aef61-9816-466d-9f37-30f82cb0e20e
(5FD4C029-BC51-40A2-96FE-A3D86E0A8E12) (Shutdown)

    appiumTest-2b97a80b-2db5-42dc-9369-ddf66cdeeeae
(CB24A907-23DF-4E34-890C-A5ED79A5CB91) (Shutdown)

    appiumTest-84e6f840-4055-4071-88ea-3a8a1839341c
(A2C48095-A185-4165-A43B-99AD0F8F5576) (Shutdown)

    appiumTest-acff9df1-3b3b-4c4f-b746-d05e2f0e9804
(9E4335E6-48B7-4879-916E-94520CC1BBC3) (Shutdown)

    appiumTest-c0d791c8-a7f6-4a4c-afe0-c77442a2f737
(55BA9807-2336-4455-916C-D2946BB0EBD9) (Shutdown)

    appiumTest-d4e2b511-66ea-46f1-b287-63ede78883de
(94C59577-276D-48A9-9FD6-D46F88974136) (Shutdown)

    bar (92D566F1-6A2B-4685-8688-2F76A47979E6) (Shutdown)

    foo (CD7129AD-4EF5-44C2-A414-87871861ED88) (Shutdown)

    iPhone 6s Plus (B01400EE-5AB0-4DFE-973F-E8F5EC9555E8) (Shutdown)

    iPad 2 (7F1730F4-1D54-4164-9A70-6DC8AF254D72) (Shutdown)

    iPad Retina (F26335B2-CDB2-4CCF-912A-C37BBDCAB145) (Shutdown)

    iPad Air (54959EAC-B7ED-4A37-B28C-F157DE3682EC) (Shutdown)

    iPad Air 2 (53C1826A-A7AD-4458-A091-54A7FE6D2787) (Shutdown)

    iPad Pro (BC838D2E-3E00-4C72-A662-A424364E0448) (Shutdown)

-- tvOS 9.1 --

    Apple TV 1080p (A7070B0B-39E1-480C-AF93-1D77288651CB) (Shutdown)

-- watchOS 2.0 --

    Apple Watch - 38mm (52B95E80-7331-4789-A9DA-30230754AA29) (Creating)

    Apple Watch - 38mm (46AFE310-AE88-4356-AE45-A03342F5D4F1) (Shutdown)

    Apple Watch - 38mm (6ECB5F76-1529-4F97-BD85-B303D1ECEF13) (Creating)

    Apple Watch - 42mm (2457AD5B-2506-4D52-979D-32AE881001E3) (Creating)

    Apple Watch - 42mm (CCBF00C5-00DA-42ED-99DF-26B39FD318A3) (Shutdown)

    Apple Watch - 42mm (405C540C-2A69-4696-8A7A-0BC5B50220E0) (Creating)

-- watchOS 2.1 --

    Apple Watch - 38mm (5AA70743-6F50-47A8-8D11-C0451026FD23) (Shutdown)

    Apple Watch - 42mm (317DE8D2-9350-424B-8A29-5BAF20F8FEAC) (Shutdown)

== Device Pairs ==

D10CFC2A-F604-461E-8CE9-FC03174E1566 (disconnected)

    Watch: Apple Watch - 38mm (46AFE310-AE88-4356-AE45-A03342F5D4F1)
(Shutdown)

    Phone: foo (CD7129AD-4EF5-44C2-A414-87871861ED88) (Shutdown)

21C52A3F-9B26-48A6-90B6-E08E73EB7D5B (disconnected)

    Watch: Apple Watch - 42mm (CCBF00C5-00DA-42ED-99DF-26B39FD318A3)
(Shutdown)

    Phone: bar (92D566F1-6A2B-4685-8688-2F76A47979E6) (Shutdown)

05084555-35D5-4478-8D94-57729B243241 (disconnected)

    Watch: Apple Watch - 38mm (5AA70743-6F50-47A8-8D11-C0451026FD23)
(Shutdown)

    Phone: iPhone 6s (4070BEDA-14A0-46C6-8B9E-C66B69D71791) (Shutdown)

43B0C4D4-A2B2-492D-B419-90DEAD18750D (disconnected)

    Watch: Apple Watch - 42mm (317DE8D2-9350-424B-8A29-5BAF20F8FEAC)
(Shutdown)

    Phone: iPhone 6s Plus (B01400EE-5AB0-4DFE-973F-E8F5EC9555E8) (Shutdown)

**Comment by Jonahss** [comment]
Yes, we use the same system for all appium modules now.

Run `gulp watch` to transpile your code into es5. It will run every time
you save a file. Linting and unit tests included.
Run `gulp once` to run this just once instead of watching and waiting for
changes.
Run `gulp test` to run tests including end-to-end tests

Once transpiled, running should just be `node .`

**Comment by kaleposhobios** [comment]
Hi Jonah,

Ok, great, I'll try that, thanks. Right now I'm redownloading Xcode since some of my simulators were stuck in "Creating" for whatever reason, and I couldn't even delete with with simctl.

Then, I will give it a shot again. If it still fails I wanted to try just making it more gracefully fail in getDevices(), instead of throwing an exception, just skip that one.

--Matt

**Comment by Jonahss** [comment]
Yeah I want to get to the bottom of this so we can help other people who
encounter the error.

**Comment by kaleposhobios** [comment]
Hi again,

After Xcode reinstall it's actually working fine. So, I'm not sure exactly which of the above simulators was causing the problem. I still wonder if we would want to just ignore a line it failed to parse?

Hopefully this is my other last question, just to clarify you note additional commands, which I think I'd like to work on. But so I can see the initial, is it possible for you to point me in the direction of how the current commands are taken in and passed to WebDriverAgent? For instance if I wanted to implement switch_to_alert()?

Thanks!

**Comment by Jonahss** [comment]
You will need to familiarize yourself with
https://github.com/facebook/webdriveragent

appium-xcuitest-driver runs `xcodebuild [...] test` which runs a single
XCUITest on a SampleApp in the facebook/webdriveragent project. That single
test starts an http server on the iOS device.

appium-xcuitest-server reads the iOS device logs until it sees that the
webdriveragent is started and it gets the port it is running on. From then
on, appium-xcuitestdriver just proxies the jsonwire protocol commands from
the appium server to the webdriveragent server running on the device.

Is that a good explanation? Feel free to ask any questions, or ask for
links to specific parts of code.

**Comment by kaleposhobios** [comment]
Hi Jonah,

Thanks for taking the time to write that up. I've been trying to piece
eveything together myself too, and what you wrote makes perfect sense. That
being said this is probably a stupid question but, in that case it sounds
like although there are some things to do in this code itself to make the
driver as functional as the current one (e.g. real device support), another
piece is that webdriveragent is missing support for some things we want to
have (like touch). And, the way to identify those missing pieces is just to
compare the selenium 3 spec (iOS parts especially). Is that accurate?

--matt

**Comment by Jonahss** [comment]
@kaleposhobios perfectly accurate :)

All the things that need to be implemented in webdriveragent are possible, just the facebook developers haven't gotten around to it yet because they use a slightly different protocol. But they are happy to include our pull requests that make them follow the Selenium 3 spec better.

**Comment by kaleposhobios** [comment]
Hi Jonah,

That's super helpful, thanks. Do we have a list of:
1. Appium commands that should be handled but are instead (by default)
proxied to Facebook (I think this is happening in some cases.
2. Features that are missing from Facebook (either against Selenium 3 spec
or ones we want for Appium)?

Or is it just, as we discover them? :)

**Comment by Jonahss** [comment]
We'll have to discover them as we go :)

Creating issues on the appium repos is good. and when the capability is missing from facebook, I can promote the issue to there.

**Comment by SrinivasanTarget** [comment]
@jlipps I'm closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close
