### ISSUE TITLE
Problems with TouchActions. Longpress

### ISSUE THREAD

**Issue by mgaticah** [appium/appium#5588]
in a C# automation project i'm using this code to longpress a nativeapp textview

 if (element != null)
                {
                    new TouchAction()
                      .LongPress(element)         //i've tried using coordinates as well
                      .Release().Perform();
                    Thread.Sleep(2000);
                    return;
                }

Where element is previous and properly captured.
But when i perform those actions i get this error:
   Error: Object reference not set to an instance of an object.
   Source: appium-dotnet-driver

I'm using this package configuration
  package id="Appium.WebDriver" version="1.4.0.3" targetFramework="net40" 
  package id="Castle.Core" version="3.3.3" targetFramework="net40" 
  package id="Newtonsoft.Json" version="7.0.1" targetFramework="net40" 
  package id="Selenium.Support" version="2.47.0" targetFramework="net40" 
  package id="Selenium.WebDriver" version="2.47.0" targetFramework="net40" 

ir's a picture of the element i'm trying to apply longpress. 
![image](https://cloud.githubusercontent.com/assets/5100855/9789046/f0d61dca-57a3-11e5-980c-6a807cd2cb88.png)

It's a file into downloads file list.

Could that be an appium issue? i guess my code is fine.

**Comment by SrinivasanTarget** [comment]
@triager please close
