### ISSUE TITLE
cannot start webkit proxy on ios simulator 8.4

### ISSUE THREAD

**Issue by nabeel-ibrahim** [appium/appium#5589]
I am trying to start the ios_webkit_debug_proxy on my ios 8.4 simulator on a specific port using the command below
`ios_webkit_debug_proxy -c 93356747-7F9A-4816-A382-15620A5FE9E7:9222` but I get the following error
`Unknown file: 93356747-7F9A-4816-A382-15620A5FE9E7:9222`. 
Is the UDID format correct for the simulator? Or is there a different way of starting the webkit proxy on a simulator in a specific port?

**Comment by scottdixon** [comment]
Your UDID looks off - you can confirm it my plugging in the device and running `system_profiler SPUSBDataType | sed -n -E -e '/(iPhone|iPad)/,/Serial/s/ *Serial Number: *(.+)/\1/p'`

Reopen if you get stuck.

**Comment by imurchie** [comment]
The ios webkit debug proxy is not needed for simulators. What are you trying to do that necessitates it?
