### ISSUE TITLE
Appium Returns multiple elements of an instance. Same UIATableView is Shown twice and all its elements refer same element in the screen

### ISSUE THREAD

**Issue by kbalakumar99** [appium/appium#5593]
I have an TableView with three tableCells, but appium detects Two table view.
In Case UIAStaticText it is four times repeated.

Pls refer these screenshots.
![screen shot 2015-09-10 at 7 12 07 pm](https://cloud.githubusercontent.com/assets/6997701/9814015/5347e222-58a8-11e5-8fe2-cae5db6c44bc.png)
and this one.
![screen shot 2015-09-10 at 7 07 34 pm](https://cloud.githubusercontent.com/assets/6997701/9814023/5c2b74bc-58a8-11e5-8211-4d4bdcfe1e05.png)

Is this a bug in appium???

I am getting the same while executing via Java code fieldCell.findElements(By.className("UIATableCell"))

The above code returns 6 UIATableCell.

**Comment by scottdixon** [comment]
Does the issue persist? Can you provide a sample app + test?

**Comment by kbalakumar99** [comment]
@scottdixon  It is working correctly now. I will provide u sample app + test, if it happens again

**Comment by scottdixon** [comment]
Good to know. Thanks for the update.

**Comment by javedansari** [comment]
Hi,

I am also facing the similar issue where I see the multiple instances of same object in the inspector. Also the querying the element name returns me that many number of object however there are less.

Please refer to the below screen shots for more details. And try to help me ASAP.
Thanks in advance!

![screen shot 2016-08-31 at 9 34 06 pm](https://cloud.githubusercontent.com/assets/21366286/18136826/b9a6baf6-6fc3-11e6-96cd-46a2bee38ce2.png)
