### ISSUE TITLE
Replace node-simctl with FBSimulatorControl

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5594]
[FBSimulatorControl](https://github.com/facebook/FBSimulatorControl) has a bunch more features. Related to #5587
- https://github.com/facebook/FBSimulatorControl/tree/master/fbsimctl

**Comment by wimbledon** [comment]
:+1:

**Comment by rompic** [comment]
+1

**Comment by dtopuzov** [comment]
+1

**Comment by vania-pooh** [comment]
+1

**Comment by alangithubtrader** [comment]
+1

**Comment by hideintheclouds** [comment]
+1

**Comment by zielinskikamil** [comment]
+1

**Comment by sudheertest** [comment]
+1

**Comment by sergeyzenchenko** [comment]
+1

**Comment by IvanStawski** [comment]
+1

**Comment by sergey-plevako-badoo** [comment]
+1

**Comment by alter-al** [comment]
+1

**Comment by dimagtf** [comment]
+1

**Comment by lanzelot1989** [comment]
+1

Am I correct in believing that this a prerequisite issue for allowing to run against multiple simulators on one macOS machine?

**Comment by dtopuzov** [comment]
Xcode9 support [multiple concurrent simulators](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/WhatsNewXcode/xcode_9/xcode_9.html) out of the box.

**Comment by lanzelot1989** [comment]
Does that make it easier for Appium to support this?

**Comment by crazyk2** [comment]
+1 
At present I boot and start WDA on several simulators on one mac by myself and use such 
 capabilities in Java client
```
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
        capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
        capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
        capabilities.setCapability(IOSMobileCapabilityType.USE_NEW_WDA, false);
        capabilities.setCapability(IOSMobileCapabilityType.WDA_LOCAL_PORT, 8100 + createdSize);
```
in order to run tests on several simulators simultaneously. It would be great if Appium do it out of the box.

**Comment by imurchie** [comment]
Closing in preference of #7281
