### ISSUE TITLE
Trying to `npm shrinkwrap` an appium project fails

### ISSUE THREAD

**Issue by iammerrick** [appium/appium#5595]
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: bplist-parser@0.1.0 /Users/Merrick/Developer/Domo/domoweb/DomoWeb/mobile-web/node_modules/appium/node_modules/bplist-parser
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Merrick/Developer/Domo/domoweb/DomoWeb/mobile-web/npm-debug.log

**Comment by jrichardlai** [comment]
yeah same for me

**Comment by akeelnazir** [comment]
change the version of bplist-parser to 0.1.0 in appium/package.json and run npm shrinkwrap again. This fixed the issue for me.

**Comment by SrinivasanTarget** [comment]
@scottdixon @imurchie As npm-shrinkwrap is removed in master. Hope this is resolved now. Can we close this?

**Comment by scottdixon** [comment]
@iammerrick - do you still have this issue with more recent versions of Appium?

**Comment by iammerrick** [comment]
@scottdixon We haven't bumped appium yet, we actually added something to our build script to go remove certain deps from package.json its not pretty.

**Comment by scottdixon** [comment]
eek! no worries. Reopen this issue if you hit any problems.
