### ISSUE TITLE
Rewrite in TypeScript

### ISSUE THREAD

**Issue by bootstraponline** [appium/appium#5601]
The issues [discussed last year](https://github.com/appium/appium/issues/3911) about async/await support and broad industry adoption have mostly been resolved.

I made a simple demo of [TypeScript async/await + Babel](https://github.com/bootstraponline/async_await_typescript) on node v4.0.0. As of the TypeScript [1.6 Beta](blogs.msdn.com/b/typescript/archive/2015/09/02/announcing-typescript-1-6-beta-react-jsx-better-error-checking-and-more.aspx) there's full support for async/await when targeting ES6. At some point after the 1.5 release, it'd be nice to find out if there are any other missing pieces that would block adopting TypeScript.

**Comment by jlipps** [comment]
Moving some code to TypeScript might make sense at some point, it seems to be gaining in the industry. But that can be a discussion for another time.

**Comment by julien-c** [comment]
Hi, I have a local fork of `appium-adb` written in Typescript that works mostly fine and passes the tests. 

I rewrote it to gain a better understanding of how `adb` is used in Appium (I'm a big Appium user and have contributed to the desktop app). Would you guys be interested in me pushing it somewhere so you can have a look and decide if it's a good direction for the project?

**Comment by yuchonghua** [comment]
Looking forward to index.d.ts declaration file with typescript
https://github.com/appium/appium-adb/issues/431

**Comment by imurchie** [comment]
@julien-c Sorry, this slipped past. I would still be interested in this, along with some explanation of what "works mostly fine" means ;).

**Comment by julien-c** [comment]
Hi @imurchie I haven't done anything new in appium over the last year but I remember discussing my fork (https://github.com/julien-c/appium-adb-ts) with someone on your Slack. You can probably find more info there.

**Comment by yuchonghua** [comment]
Thank you very much for the support of @imurchie and @julien-c. With ts, it is really convenient to use. It doesn't take too much time to understand the documentation and source code. Thank you very much.
