### ISSUE TITLE
Is there any scroll options available for appium other than scrollto and scrolltoExact? 

### ISSUE THREAD

**Issue by User423** [appium/appium#5604]
Is there any scroll options available for appium other than scrollto and scrolltoExact? For Example: like Scroll up, scroll down, Scroll to next, Scroll to next Screen/Page, Scroll to end, Scroll to Home. Please let me know if there are any other scroll options.

**Comment by Fanch-** [comment]
Nop, you have to implement them yourself, because appium provides the basics; compatible in every platforms.
I agree with you though, I guess on Android everybody implemented the 'scroll' taking also a direction and mobileElement.
You should look at the swipe() function.

**Comment by scottdixon** [comment]
More info: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md
