### ISSUE TITLE
use selenium alert method, and get UnknownError

### ISSUE THREAD

**Issue by kingangelTOT** [appium/appium#5607]
def alert_present?(driver)
    driver.switch_to.alert
    true
rescue Selenium::WebDriver::Error::NoAlertPresentError
    false
end

Not yet implemented. Please help us: http://appium.io/get-involved.html (Selenium::WebDriver::Error::UnknownError)

**Comment by scottdixon** [comment]
Try Appium 1.5 you should be good to go. Reopen if any issues.
