### ISSUE TITLE
Appium inspector running Android application in an infinite loop

### ISSUE THREAD

**Issue by visvaram** [appium/appium#5609]
I am facing some issue with appium inspector starting my Android application. It used to work before but after some recent changes its running continuously in a loop, on start it open the launcher, kills the process and close immediately and same goes again and again. 

Once I hit Stop button in launcher everything stops and the application works as expected. So not sure what is the issue with inspector on startup. Please let me know what needs to be done to fix this issue.

log:
09-14 17:17:43.887      892-929/? I/ActivityManager﹕ Displayed com.xxxx.debug/com.xxxx..xxActivity: +633ms (total +1s738ms)
09-14 17:17:43.891    1411-1411/? I/Keyboard.Facilitator﹕ onFinishInput()
09-14 17:17:43.909    7988-7988/com.xxxx.debug I/art﹕ System.exit called, status: 0
09-14 17:17:43.909    7988-7988/com.xxxx.debug I/AndroidRuntime﹕ VM exiting with result code 0, cleanup skipped.
09-14 17:17:43.934     892-1209/? I/WindowState﹕ WIN DEATH: Window{18e526e1 u0 com.xxxx.debug/com.xxxx.xxxActivity}
09-14 17:17:44.178     892-1379/? I/ActivityManager﹕ Process com.xxxx.debug (pid 7988) has died
09-14 17:17:44.181     892-1379/? W/ActivityManager﹕ Force removing ActivityRecord{3685407e u0 com.xxxx.debug/com.xxxx.xxxActivity t5062}: app died, no saved state
09-14 17:17:44.226     892-1747/? W/InputMethodManagerService﹕ Got RemoteException sending setActive(false) notification to pid 7988 uid 10253
09-14 17:17:44.229    1411-1411/? I/Keyboard.Facilitator﹕ onFinishInput()
09-14 17:17:44.302    1235-1235/? W/ResourceType﹕ No package identifier when getting value for resource number 0x00000000
09-14 17:17:44.302    1235-1235/? W/PackageManager﹕ Failure retrieving resources for com.xxxx.debug: Resource ID #0x0
09-14 17:17:44.754    1529-1847/? W/OpenGLRenderer﹕ Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
09-14 17:17:44.755    1529-1847/? W/OpenGLRenderer﹕ Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...

**Comment by scottdixon** [comment]
Closing old issue. Please try a more recent version of Appium. Reopen if the issue persists.
