### ISSUE TITLE
appium on ubuntu no gui

### ISSUE THREAD

**Issue by zhaochunyu** [appium/appium#5613]
Appium in the Ubuntu 15.04 system, the implementation of no graphics programs, I know in the iOS and windows have, if there is no graphics program, how to record ah?

Only the terminal output, no GUI
![2015-09-15 17 21 09](https://cloud.githubusercontent.com/assets/6846415/9872800/4bacd490-5bce-11e5-990b-810cef06aad3.png)

Please tell me what I should do？

**Comment by vietch2612** [comment]
use uiautomatorviewer on Android SDK Tools

**Comment by Jonahss** [comment]
Yeah, the appium server has no gui :)
I use a REPL to write test scripts.
