### ISSUE TITLE
Unable to removeapp - getting an exception

### ISSUE THREAD

**Issue by igalep** [appium/appium#5618]
Hi ,
I've tried 
      driver.removeApp("com.my.app");
but getting an exception :
Exception in thread "main" org.openqa.selenium.WebDriverException: undefined status object (WARNING: The server did not provide any stacktrace information)

and the appium log :

info: --> POST /wd/hub/session/71a4c5ca-92b5-4e94-99f5-f8a795671d82/appium/device/remove_app {"bundleId":"com.my.app"}

info: [debug] Responding to client with error: {"status":1,"value":{"message":"undefined status object"},"sessionId":"71a4c5ca-92b5-4e94-99f5-f8a795671d82"}

info: <-- POST /wd/hub/session/71a4c5ca-92b5-4e94-99f5-f8a795671d82/appium/device/remove_app 500 1.802 ms - 109

could you pls take a look in it ?

thanks

**Comment by igalep** [comment]
Any update on this one ?

**Comment by igalep** [comment]
Any update , does it work (supposed to be working ?)

**Comment by igalep** [comment]
Still no response ... the method doesnt work on iOS simulator running iOS 9.1

**Comment by scottdixon** [comment]
@igalep - please try Appium 1.5 - if you get stuck please post your full logs here as a gist.

**Comment by rokly** [comment]
@scottdixon driver.removeApp("BuildID") doesn't work for me on Appium 1.5. With 1.4.13 everything works fine but with 1.5 i get 
> org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)

Logfile:
[https://gist.github.com/rokly/f33210ac2f50f7bbc92d](url)

**Comment by imurchie** [comment]
If you are running from source, @rokly, can you update `appium-ios-driver` and try again?

**Comment by rokly** [comment]
@imurchie I tried it with io.appium:java-client:3.4.0 and got the same error message.

**Comment by imurchie** [comment]
I mean the server. I have added the method to the `appium-ios-driver` package that will be updated if you are running the Appium server from source. Otherwise it will have to wait for the next release.

**Comment by rokly** [comment]
@imurchie With your changes in the master branch it works for me. Thank you.

**Comment by nmeason** [comment]
I'm actually not seeing removeApp work with the latest updated appium-ios-driver (1.10.0).

Log can be found here:  https://gist.github.com/nmeason/e1d9267d6795db76359a
