### ISSUE TITLE
appium.app can not pre launch any ios simulator

### ISSUE THREAD

**Issue by fangmobile** [appium/appium#5620]
1.4.8

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --pre-launch --debug-log-spacing --platform-version "8.4" --platform-name "iOS" --app "/Users/jfang1/Desktop/appium/GenericPlayerDemo.app" --show-ios-log --device-name "iPhone 5"

info: [debug] Starting Appium in pre-launch mode

info: Pre-launching app
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] Using local app from command line: /Users/jfang1/Desktop/appium/GenericPlayerDemo.app
info: [debug] Creating new appium session bedacdab-d786-408f-a16d-c38fff9099b2
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version

info: [debug] Xcode version set to 7.0

info: [debug] Setting iOS SDK Version

info: [debug] iOS SDK Version set to 9.0

info: [debug] Checking whether instruments supports our device string

info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.0","iOSSDKVersion":"9.0","deviceName":"iPhone 5","platformVersion":"8.4"}

error: Could not find a device to launch. You requested 'iPhone (8.4 Simulator)', but the available devices were: ["iPad 2 (8.4) [909973AB-F3C6-4A0F-9C44-44C7002D41D3]","iPad 2 (9.0) [7DCA936A-D4DF-4CEE-8B80-34A6B24B1994]","iPad Air (8.4) [B825FCE9-626B-4342-A27F-C6A710494C3A]","iPad Air (9.0) [1ECE9A93-6F1B-408C-AA2A-F0E4226629DE]","iPad Air 2 (9.0) [D253662D-F391-4661-981E-DFCB9ADE4EA6]","iPad Retina (8.4) [A7FB4D00-28E1-465F-8E07-D3E0649943B5]","iPad Retina (9.0) [598F2732-2DDF-4B85-9D17-2BFE8CEDCABB]","iPhone 4s (8.4) [8B1EEA0D-79F9-48FB-BB28-1561AB2536BC]","iPhone 4s (9.0) [23E65E20-AC1A-4A80-B16D-928BCF17A6DE]","iPhone 5 (8.4) [6CEE45B2-541F-42A5-A9DB-015EC0921CC1]","iPhone 5 (9.0) [C6C21557-9E98-4083-B471-76F7BAEC3561]","iPhone 5s (8.4) [783962D0-687E-4505-90D5-D9A2EDECC664]","iPhone 5s (9.0) [C1C2FB8D-EDEB-41F2-86B1-BFB90F9D9CDB]","iPhone 6 (8.4) [BF2D1255-FAF5-4E86-9DC2-744EBF492609]","iPhone 6 (9.0) [CD341B19-1868-4A83-8451-01C7850BF953]","iPhone 6 (9.0) + Apple Watch - 38mm (2.0) [62D236C8-7740-414A-9D37-3D6750B86726]","iPhone 6 Plus (8.4) [51CF3824-1A74-4A38-9D93-9DE3D9AD99D1]","iPhone 6 Plus (9.0) [AD055395-A2F5-43F2-8BFB-58A22C282BB8]","iPhone 6 Plus (9.0) + Apple Watch - 42mm (2.0) [AD909908-A7C3-420E-ADE9-C72D31F02768]","iPhone 6s (9.0) [C0781FA6-4A68-4771-A3E1-546877B23964]","iPhone 6s Plus (9.0) [7DBAD341-DC1C-415D-8A75-16CB70F43EC1]"]

**Comment by fangmobile** [comment]
my work around is to launch app from command line and click inspector icon in appium app.
Closing issue.

**Comment by kiminoa** [comment]
Same problem. Thanks for including your workaround.
