### ISSUE TITLE
Swipe and scroll are not working

### ISSUE THREAD

**Issue by AspireInfotech** [appium/appium#5629]
Hi,

We could not do swipe in our application using appium on IOS from 7.1 to 8.4, i have tried all ways that suggested in internet but there is no way of make it work.
codes i have tried:
- currentDriver().swipe((int) (screenWidth * 0.5),(int) (screenHeight * 0.9), (int) (screenWidth* 0.5),0 ,1000); // where current driver will return a IOSDriver.

- HashMap<String, String> scrollObject = new HashMap<String, String>();
scrollObject.put("direction", "down");
js.executeScript("mobile: scroll", scrollObject);

- TouchAction().press(el0).moveTo(el1).release()

And also i tried to perform the swipe from the inspector it self but it does not work.

please note that we have the swipe working probably in other ios apps, but in this app it does not work.

Could you please advise if there are other workarounds to perform swipe?

Thanks.

**Comment by marloncruz** [comment]
There may be 2 culprits: 
1. Your width and height might be wrong. Could you try sending currentDriver().swipe(0.5,0.9,0.5,0,1000)?

2. Your swipe length is not enough to perform a swipe. Try swipe(0.9,0.9,0.9,0,1000) instead

**Comment by amedvedjev** [comment]
same issue. appium v1.4.15. but working e.g. with iOS 9.0

**Comment by scottdixon** [comment]
Try https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md - reopen + provide logs if the issue persists.
