### ISSUE TITLE
"driver.closeApp()" cannot really kill app on Android Devices.

### ISSUE THREAD

**Issue by TesterCC** [appium/appium#5630]
Appium version:1.4.0
Devices: Samung Note4(other android devices have same issue.)
Android 5.0.1

I can run my test script successfully. But after my script end, I check my Android devices,found the fact that app just run in background and not be killed. I also try use "driver.quit()"  but app still run in background.

Is there any ways can really kill the app?  
PS:Seemingly ios encounter the same problem.

**Comment by amedvedjev** [comment]
pls make more clear you want:
 - close app (it can start again if designed to run in background later itself)
 - remove app completely from device

**Comment by neemanegi** [comment]
I am facing the same problem. By using both command , app runs in background. Please let us know how to kill app(remove from memory)

**Comment by amedvedjev** [comment]
if your device on same machine where tests are running you can use "adb" to kill any app on phone.

**Comment by neemanegi** [comment]
For that device needs to be rooted. Is there any other way?

**Comment by omoskovko** [comment]
As workaround to close application you can send KeyEvent 187 to bring up the application switcher dialog and remove application from from the list.
```
driver.keyevent(187)
```
See http://developer.android.com/reference/android/view/KeyEvent.html for more information.

**Comment by scottdixon** [comment]
@neemanegi - please try a more recent version of Appium. Reopen if any issues.

**Comment by TesterCC** [comment]
omoskovko,Thanks a lot. It can real kill current app now.

**Comment by neha3110** [comment]
I am still looking for solution here ? 
how you able to kill the app?
