### ISSUE TITLE
Issue with tapping element inside UIACollectionView and UIACollectionView

### ISSUE THREAD

**Issue by bnimmagadda** [appium/appium#5632]
With using appium version 1.4.7 I am not able to tap element inside the UIACollectionView and cell.

I tried accessing element using classname,xpath.Nothing seems to be working. Screen shot shows the DOM structure.

Thanks
<img width="452" alt="screen shot 2015-09-21 at 2 00 55 pm" src="https://cloud.githubusercontent.com/assets/9437849/10005012/8e81cd58-6069-11e5-9b01-b0b2453366dd.png">

**Comment by bnimmagadda** [comment]
App is crashing when I try to tap any elements which resides inside UIACollectionView.

Any help is appreciated.

**Comment by scottdixon** [comment]
@bnimmagadda - did you resolve this? Please try with a more recent version of Appium. Reopen if the issue persists.
