### ISSUE TITLE
Appium 1.4.11 does not see some manually created iOS simulators

### ISSUE THREAD

**Issue by kchuykov** [appium/appium#5640]
I've created a few simulators and Appium  sees only the ones that start with iPhone or iPad.
Appium does not see the simulator with the name '253' for example.

Original error: Could not find a device to launch. You requested '253 (9.0)', but the available devices were:"([\"iPhone 245 (8.4) [A16B5A04-23CC-40D0-9910-B456759F55B3]\",\"iPhone 6s Plus (9.0) [33E80833-6810-44B2-8CCB-91A4C89122D9]\"])"

xcode 7
os x 10.10

**Comment by SrinivasanTarget** [comment]
@scottdixon This has been fixed in appium-instruments on Appium 1.5.Please close this.
https://github.com/appium/appium-instruments/commit/96f7a271e93dc3e63d4a67001f27f9efbdd558b4

**Comment by scottdixon** [comment]
Thanks @SrinivasanTarget 

@kchuykov - reopen if the issue persists.
