### ISSUE TITLE
[Xcode 7/iOS9/Appium-1.4.11] - Simulator closes on test failure and does not reopen for next test

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#5641]
Hi @jlipps @Jonahss @bootstraponline 

I'm running my tests on iPhone Simulator (6s) . I have multiple tests methods, when a single test method fails the simulator closes and does not open for the next test. Please find the server logs added to the gist

https://gist.github.com/saikrishna321/e65ccc0f3828b91cc9fd

Can someone pls help me on this.

**Comment by scottdixon** [comment]
@saikrishna321 - Judging by your other posts, I think you've resolved this. Reopen if otherwise.

**Comment by saikrishna321** [comment]
@scottdixon yup it works fine on 1.5
