### ISSUE TITLE
SafariLauncher not installed

### ISSUE THREAD

**Issue by nialltu** [appium/appium#5647]
I'm trying to get Appium working on an iPad iOS 8.4. I'm on a Mac (Yosemite) and using Xcode version 7.0 with the latest copy of Appium I git cloned on 23/09/15 (1.4.11).

I have followed the instructions to run reset.sh (which completes successfully), then when I start the server ("node /lib/server/main.js") it starts up fine without error. However, SafariLauncher is not installed on the device, and no errors have been displayed anywhere in the process?

At what point is SafariLauncher supposed to be installed on the device? During reset.sh or when Appium is run? 

The only warning I have seen during the process is the reset.sh reporting I don't have iOS7/8 active, but presumably xcode 7.0 use iOS 9 so is backwards compatible to 8?

**Comment by seleniumappiumnewbie** [comment]
You can install safari launcher with reset.sh by typing additional --real-safari.
-Type git clone https://github.com/appium/appium.git
-Type in terminal to find code-signing identity: security find-identity -v -p codesigning
-Type $ ./reset.sh --ios --real-safari --code-sign 'code signing identity' --profile 'retrieved profile identity code'

See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/mobile-web.md#mobile-safari-on-a-real-ios-device

**Comment by nialltu** [comment]
Hi @seleniumappiumnewbie, thank you for your help! I actually realised that SafariLauncher is not installed until your run a test that calls for it, I was expecting it to be installed onto the device during the reset.sh. But thank you for your assistance! :)
