### ISSUE TITLE
Appium clicking wrong Xpath in android chrome browser

### ISSUE THREAD

**Issue by manojtdm** [appium/appium#5657]
When I try to find the element using the xpath created by uiautomateviewer,it is clicking wrong xpath.
How to resolve the same?

driver.findElement(By.xpath("//*[@class='android.view.View' and @index='16']")).click();

scrren capture of element attached for reference.
![appium xpath issue](https://cloud.githubusercontent.com/assets/13692001/10098405/ba76cd9a-639e-11e5-9148-2c6d6015cabd.png)

**Comment by rets5s** [comment]
Try something like this
```
driver.findElement(By.xpath("//android.widget.View[@index='16']"));
```
