### ISSUE TITLE
Android 4.2 (API 17) crashes with the Appium Inspector

### ISSUE THREAD

**Issue by shermanericSF** [appium/appium#5659]
As discussed on this post,
https://discuss.appium.io/t/appium-1-3-4-1-did-not-work-for-me-with-android-os-4-2-2-device/1895

This still happens to me as of:
Appium dmg: 1.4.8
Appium Server Version 1.4.11

Specifically, I start ARC with the appium server, then use the DMG to inspect.
On all above platforms this is fine.  On this combination with 4.2.2 Android, it crashes - seemingly due to the same problem as what was provided on this post.

Thanks!

**Comment by bthuan** [comment]
Any plan to get this issue fixed? I think there are still a number of devices running Android 4.2 out there ( according to this: http://developer.android.com/about/dashboards/index.html). And some companies consider testing on Android 4.2 as a must as well

**Comment by SrinivasanTarget** [comment]
Hopefully this will be out for users soon with all issues related to dot.app: https://github.com/appium/appium-dot-app/pull/538

**Comment by SrinivasanTarget** [comment]
@triager please close
