### ISSUE TITLE
Unable to launch test url on ipad ios 8.4 with appium 1.4.11

### ISSUE THREAD

**Issue by amitsha** [appium/appium#5662]
------------------------------Unable to launch the test url on real ipad2 ios 8.4----------
------ Just after the apple.com site is launched, ios webkit debug proxy logs that it's disconnected from the ipad., and it connects again, and again just after apple.com is launched, it disconnects again.

Software Versions being used:
Mac Mini(Mac OSX 10.10.3) (Is the mac version an issue, earlier i had it working successfully on OSX 10.9.5)
Xcode 6.4
Safari Launcher https://github.com/budhash/SafariLauncher
Appium 1.4.11
ios webkit debug proxy (using .js file in appium tag v1.4.11 clone)
ipad2 (ios 8.4.1)

Enable UI automation option is enabled in Developer section in settings on the ipad
Web inspector is enabled on the ipad as well as on the mac

-----------------------------------------------------------------
Appium log:
INST] 2015-09-25 12:40:08 +0000 Fail: The target application appears to have died
info: [debug] [INST STDERR] 2015-09-25 13:40:08.563 instruments[5199:384675] Attempting to set event horizon when core is not engaged, request ignored
2015-09-25 13:40:08.564 instruments[5199:384675] Attempting to set event horizon when core is not engaged, request ignored
info: [debug] [INST] Instruments Trace Complete (Duration : 15.452854s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0

ios webkit debug proxy log:
Disconnected :27753 from Ipad 2 (e0982fdecee7b985a9a9d0fe37d9a91851f97edf)
ss.remove_server_fd(4)
ss.remove_fd(3)

child process exited with code 0
-------------------------------------------------------------------
Has anyone faced this issue?
With the same scenarios it was working fine for me on osx 10.9.5 and ipad 2 ios8.1(or 8.2, don't remember for sure)

**Comment by Swapnillll** [comment]
I had the issue with webkit getting disconnected but has been fixed in the latest release. 
Have you updated webkit proxy?
I'm able to test on below setup with no issues:
appium - 1.4.11
Yosemite OS X 10.10.4
XCode: 6.4 iOS: 8.4
Selenium Standalone jar: 2.47.1

**Comment by amitsha** [comment]
I’m using webkit js file inside appium 1.4.11 source code.
Probably I’m not using the same selenium version.I’ll try with this one.

**Comment by Swapnillll** [comment]
I'm not sure if it is related to selenium but you could give a try. 

I tried with standalone webkit  though, not the integrated.

**Comment by SrinivasanTarget** [comment]
Please try a latest version of appium and log a new issue with logs incase if you hit the same

**Comment by SrinivasanTarget** [comment]
@triager please close
