### ISSUE TITLE
How to upgrade appium.dmg to latest 1.4.11?

### ISSUE THREAD

**Issue by scastria** [appium/appium#5667]
I use the prebuilt appium.dmg mac app so I don't have to install node and other stuff.  However, I need xcode7/ios9 support.  How can I update appium.dmg to latest 1.4.11? OR How can I manually patch appium.dmg to latest?  I tried copying over the ios.js file from github to my appium.dmg contents but that didn't work.

**Comment by SouWilliams** [comment]
So far, the latest version of appium under MAC is not released. i strongly recommend to uninstall your current version and re-install by node. After that, you can update your appium by below command:

sudo npm install -g appium@1.4.11

**Comment by scastria** [comment]
Who is in charge of the dmg build and how can I get him/her to update it?  Why does appium.io website have a link to an old version?

**Comment by scastria** [comment]
I did try installing appium the hard way with brew and npm.  This gives me the server component, but what about inspector?  Is inspector only available with the dmg mac app distribution?  If so, then it is even more important that the mac dmg be upgraded to 1.4.11.

**Comment by moizjv** [comment]
1. Install latest appium using `npm install appium` (generally gets installed in node_modules directory from where you run it)
2. From setting set use external appium package as shown in picture below
 
![screen shot 2015-10-23 at 1 16 56 pm](https://github-cloud.s3.amazonaws.com/assets%2F1308607%2F10957193%2Fd6e698ba-8316-11e5-9821-ed62d63fac16.png)

**Comment by SrinivasanTarget** [comment]
@triager please close
