### ISSUE TITLE
MessyCode on Appium 1.4.0 with chinese

### ISSUE THREAD

**Issue by SouWilliams** [appium/appium#5669]
When try to test Android 4.4 with appium on windows, we found that when we try to click a button with chinese the log will be messy.  The project has already changed to UTF-8
please refer below screenshot.
![messycode](https://cloud.githubusercontent.com/assets/6127395/10157639/4573b8e6-66be-11e5-89fc-fa1f5d3c961a.jpg)
![messycode2](https://cloud.githubusercontent.com/assets/6127395/10157640/45c74420-66be-11e5-9aa6-2c72a904a611.png)

**Comment by SrinivasanTarget** [comment]
@SouWilliams please give a shot in appium 1.5.1 and raise a new issue incase of any issues been faced along with logs inform of gist.

**Comment by SrinivasanTarget** [comment]
@triager please close
