### ISSUE TITLE
Handle Heads Up messages that appear in Android Lollipop

### ISSUE THREAD

**Issue by nishantc-optimus** [appium/appium#5671]
Implement methods to detect and handle the heads up notifications that appear whenever a notification is received in an android device with OS > 5.1.0 i.e. Lollipop.
Currently the heads up notification appears and gets clicked if the user attempts to click on any application button that lies beneath the heads up message and the test fails.

**Comment by rkavalap** [comment]
Closing as External. This should be controlled from the OS level on the device. Unless you are expecting this to made from appium every time you run automation which seems every ugly.
