### ISSUE TITLE
Failed to locate key on iPhone 6 iOS 9.0 Appium 1.4.13

### ISSUE THREAD

**Issue by sergejjkim** [appium/appium#5677]
i'm using iPhone 6 iOS 9.0 Appium 1.4.13

and time after time i'm getting errors like failed to execute user supplied javascript when trying to type text. 
Server says:
info: [debug] Got result from instruments: {"status":17,"value":"target.frontMostApp().keyboard() failed to locate key 'M'"}

**Comment by SrinivasanTarget** [comment]
Please try a latest version of appium and raise a new issue along with logs incase if you hit the same.

**Comment by SrinivasanTarget** [comment]
@triager please close
