### ISSUE TITLE
Text view is considered as visible=false but it has visible=true in reality.

### ISSUE THREAD

**Issue by kos322** [appium/appium#5678]
Text view is considered as visible=false but it has visible=true in reality.
Seems apply only for some UIATextView.
See attachment. Via Appium Inspector and via API you receive that UIATextView is not visible but if you copy XML and check it will have visible=true.

Tested with xCode 7.0, Simulator iphone 5, iphone 6s, ios 9.0
Appium 1.4.13, taken from git, master
![capture](https://cloud.githubusercontent.com/assets/6050735/10194809/5c98e4a8-6793-11e5-9b2e-a0ccf14d2086.JPG)

**Comment by SrinivasanTarget** [comment]
Please raise here: https://github.com/appium/appium-dot-app/issues

**Comment by SrinivasanTarget** [comment]
@triager please close
