### ISSUE TITLE
driver.shake() no longer working

### ISSUE THREAD

**Issue by pjayaram** [appium/appium#5680]
Yet when I do "Shake Gesture" in iOS Simulator, the expected response occurs.  "Shake" in Appium Inspector isn't working either.

Since the last time shake was working, I updated Appium from 1.4.10 to 1.4.13, and updated XCode to 7.0 (which in turn updated the iOS Simulator to iOS 9.0).

**Comment by waltlreed** [comment]
I'm also seeing this issue.  Using Xcode 7.0, Appium 1.4.13, have tested in Simulator (iOS 9) and a Real Device (iPhone 6, iOS 9).  Tests written in Ruby, if that matters.

In addition, we have successfully shaken the simulator in a Simulator with iOS 8.4, so it seems to be an iOS 9 specific issue.

**Comment by SrinivasanTarget** [comment]
This hasn't been supported in iOS 9 by Apple. @scottdixon Can we close this please

**Comment by scottdixon** [comment]
Thanks @SrinivasanTarget 

"shake is broken/removed in UIAutomation for iOS 9+.." More info: #5966
