### ISSUE TITLE
 unknown server-side Exception, while performing touch operation on native app

### ISSUE THREAD

**Issue by gsaimadhu** [appium/appium#5681]
Env:
-------
Appium v1.4.0
Java SDK
Windows 7

Code:
-------
               try{
			if (element != null){
				AppiumDriver d = getDriver();
				TouchAction ta = new TouchAction(d);		
				TouchAction y = ta.moveTo(element).tap(element).perform();

			}

		} catch (Exception e){
			e.printStackTrace();
		}

Exception:
--------------
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 164 milliseconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'GANMA05-NB', ip: '192.168.42.5', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_45'
Session ID: 106ceca8-d63a-42d5-a8d1-dcb5872e0276
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{platform=LINUX, javascriptEnabled=true, appActivity=com.maa.ca.kitchensink.LauncherActivity, browserName=Android, networkConnectionEnabled=true, desired={newCommandTimeout=1000, platformName=Android, deviceName=gms, VERSION=4.4.2, appActivity=com.maa.ca.kitchensink.LauncherActivity, appPackage=com.maa.ca.kitchensink, BROWSER_NAME=Android}, locationContextEnabled=false, appPackage=com.maa.ca.kitchensink, BROWSER_NAME=Android, newCommandTimeout=1000, platformVersion=4.4.2, databaseEnabled=false, platformName=Android, deviceName=U4Q8EAFY8LTKEENF, VERSION=4.4.2, webStorageEnabled=false, warnings={}, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at io.appium.java_client.AppiumDriver.performTouchAction(AppiumDriver.java:304)
	at io.appium.java_client.TouchAction.perform(TouchAction.java:253)
	at com.ca.mcc.selenium.MobileOperation.click(MobileOperation.java:184)

Appium Log:
------------------
> Starting Node Server
> warn: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
> info: Welcome to Appium v1.4.0 (REV 8f63e2f91ef7907aed8bda763f4e5ca08e86970a)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"androidDeviceReadyTimeout":"226","deviceName":"gms","platformName":"Android","platformVersion":"18","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":"1000","VERSION":"4.4.2","deviceName":"gms","platformName":"Android","appActivity":"com.maa.ca.kitchensink.LauncherActivity","appPackage":"com.maa.ca.kitchensink","BROWSER_NAME":"Android"}}
> info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : VERSION, BROWSER_NAME
> info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
> info: [debug] Creating new appium session 7c0a9135-846a-422e-9bc5-6b81fb9061db
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.7.0_45
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe
> warn: No app capability, can't parse package/activity
> info: [debug] Set chromedriver binary as: D:\OpenTools\Appium\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device U4Q8EAFY8LTKEENF
> info: [debug] Setting device id to U4Q8EAFY8LTKEENF
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 226)
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF wait-for-device
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: Device API level is: 19
> info: [debug] Extracting strings for language: default
> info: [debug] Apk doesn't exist locally
> info: [debug] Could not get strings, but it looks like we had an old strings file anyway, so ignoring
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF shell "rm -rf /data/local/tmp/strings.json"
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Skipping install since we launched with a package instead of an app path
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF push "D:\\OpenTools\\Appium\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF install "D:\OpenTools\Appium\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF install "D:\OpenTools\Appium\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.maa.ca.kitchensink -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [UIAUTOMATOR STDOUT] tcp port:4724
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.maa.ca.kitchensink/com.maa.ca.kitchensink.LauncherActivity"
> info: [debug] Waiting for pkg "com.maa.ca.kitchensink" and activity "com.maa.ca.kitchensink.LauncherActivity" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF shell "dumpsys window windows"
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF shell "getprop ro.build.version.release"
> info: [debug] Device is at release version 4.4.2
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to 1000 secs
> info: [debug] Appium session started with sessionId 7c0a9135-846a-422e-9bc5-6b81fb9061db
> info: <-- POST /wd/hub/session 303 13953.585 ms - 74 
> info: --> GET /wd/hub/session/7c0a9135-846a-422e-9bc5-6b81fb9061db {}
> info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.4.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"newCommandTimeout":"1000","VERSION":"4.4.2","deviceName":"gms","platformName":"Android","appActivity":"com.maa.ca.kitchensink.LauncherActivity","appPackage":"com.maa.ca.kitchensink","BROWSER_NAME":"Android"},"newCommandTimeout":"1000","VERSION":"4.4.2","deviceName":"U4Q8EAFY8LTKEENF","platformName":"Android","appActivity":"com.maa.ca.kitchensink.LauncherActivity","appPackage":"com.maa.ca.kitchensink","BROWSER_NAME":"Android"},"sessionId":"7c0a9135-846a-422e-9bc5-6b81fb9061db"}
> info: <-- GET /wd/hub/session/7c0a9135-846a-422e-9bc5-6b81fb9061db 200 1.774 ms - 758 {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.4.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"newCommandTimeout":"1000","VERSION":"4.4.2","deviceName":"gms","platformName":"Android","appActivity":"com.maa.ca.kitchensink.LauncherActivity","appPackage":"com.maa.ca.kitchensink","BROWSER_NAME":"Android"},"newCommandTimeout":"1000","VERSION":"4.4.2","deviceName":"U4Q8EAFY8LTKEENF","platformName":"Android","appActivity":"com.maa.ca.kitchensink.LauncherActivity","appPackage":"com.maa.ca.kitchensink","BROWSER_NAME":"Android"},"sessionId":"7c0a9135-846a-422e-9bc5-6b81fb9061db"}
> info: --> GET /wd/hub/session/7c0a9135-846a-422e-9bc5-6b81fb9061db/screenshot {}
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF shell "/system/bin/rm /data/local/tmp/screenshot.png; /system/bin/screencap -p /data/local/tmp/screenshot.png "
> info: [debug] executing cmd: D:\Automation\adt-bundle-windows-x86_64-20140702\sdk\platform-tools\adb.exe -s U4Q8EAFY8LTKEENF pull /data/local/tmp/screenshot.png "C:\\Users\\ganma05\\AppData\\Local\\Temp\\appium11592-7780-r35esf.png"
> info: [debug] Responding to client with success: {"status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAtAAAAUACAYAAABuzmU9AAAABHNCSVQICAgIfAhkiAAAIABJREFUeJzsnXmYFNW5/z+nqnrvnqVnYWBAWRQwalTcAkgM4hbvjXtCEiHRq0Z/LnGLMS5RY0wwm8btutyQxxhNrks08cbgGhKJiILEuKABRJYZYJi9Z3qv5fdHTzc9M8BMT88Mg7yf55nnzLer6pxT+1tvvectBTgIgiAIgiAIgtAvtN3dAUEQBEEQBEHYkxADWhAEQRAEQRAKQAxoQRAEQRAEQSgAMaAFQRAEQRAEoQDEgBYEQRAEQRCEAhADWhAEQRAEQRAKQAxoQRAEQRAEQSgAMaAFQRAEQRAEoQDEgBYEQRAEQRCEAhADWhAEQRAEQRAKQAxoQRAEQRAEQSgAMaAFQRCEIcXtdnP11Vdz0kkn7e6uCIIgDArG7u6AIAiC8OkmEAjwta99DYApU6Zwzz337JZ+TJ48mc9//vMcdNBBjBkzhqqqKtxuN263m1QqRSqVorGxkfr6et5//32WLFnC6tWrd0tfBUEY2SjA2d2dEARBED69uN1uli5dmtOLFy/m+uuvxzTNIW+7srKSr3/965x44onU1NQA4DgOSqmdLuM422+LW7du5aWXXuLxxx+npaVlyPv7aWLy5MnU1tbiOA6bN2/+VD+MVFdXE4lESCQSu7srwjAhBrQgCIIw5CxfvjxntDqOwwcffMAVV1xBe3v7kLRXWlrKlVdeyUknnYTb7e5lNPdXZ43pZDLJSy+9xN133z1kfb755pv54he/yKJFi7jtttu6TXvrrbd45ZVXuOGGG4ak7aFg9uzZuf8dx+Fvf/vb7uvMEKKU4uKLL+aBBx4Y0PIul4svfOELzJ49m4MOOoiqqioMw9jh8Wjbdrd28x/2BlvH43EaGhpYvXo1ixcv5rXXXiOdTg9oHT+NiAEtCIIgDDkrVqwA4IknnmDu3LlAxrt72WWXsX79+kFt66yz...","sessionId":"7c0a9135-846a-422e-9bc5-6b81fb9061db"}
> info: <-- GET /wd/hub/session/7c0a9135-846a-422e-9bc5-6b81fb9061db/screenshot 200 1054.491 ms - 336954 {"status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAtAAAAUACAYAAABuzmU9AAAABHNCSVQICAgIfAhkiAAAIABJREFUeJzsnXmYFNW5/z+nqnrvnqVnYWBAWRQwalTcAkgM4hbvjXtCEiHRq0Z/LnGLMS5RY0wwm8btutyQxxhNrks08cbgGhKJiILEuKABRJYZYJi9Z3qv5fdHTzc9M8BMT88Mg7yf55nnzLer6pxT+1tvvectBTgIgiAIgiAIgtAvtN3dAUEQBEEQBEHYkxADWhAEQRAEQRAKQAxoQRAEQRAEQSgAMaAFQRAEQRAEoQDEgBYEQRAEQRCEAhADWhAEQRAEQRAKQAxoQRAEQRAEQSgAMaAFQRAEQRAEoQDEgBYEQRAEQRCEAhADWhAEQRAEQRAKQAxoQRAEQRAEQSgAMaAFQRCEIcXtdnP11Vdz0kkn7e6uCIIgDArG7u6AIAiC8OkmEAjwta99DYApU6Zwzz337JZ+TJ48mc9//vMcdNBBjBkzhqqqKtxuN263m1QqRSqVorGxkfr6et5//32WLFnC6tWrd0tfBUEY2SjA2d2dEARBED69uN1uli5dmtOLFy/m+uuvxzTNIW+7srKSr3/965x44onU1NQA4DgOSqmdLuM422+LW7du5aWXXuLxxx+npaVlyPv7aWLy5MnU1tbiOA6bN2/+VD+MVFdXE4lESCQSu7srwjAhBrQgCIIw5CxfvjxntDqOwwcffMAVV1xBe3v7kLRXWlrKlVdeyUknnYTb7e5lNPdXZ43pZDLJSy+9xN133z1kfb755pv54he/yKJFi7jtttu6TXvrrbd45ZVXuOGGG4ak7aFg9uzZuf8dx+Fvf/vb7uvMEKKU4uKLL+aBBx4Y0PIul4svfOELzJ49m4MOOoiqqioMw9jh8Wjbdrd28x/2BlvH43EaGhpYvXo1ixcv5rXXXiOdTg9oHT+NiAEtCIIgDDkrVqwA4IknnmDu3LlAxrt72WWXsX79+kFt66yz...","sessionId":"7c0a9135-846a-422e-9bc5-6b81fb9061db"}
> info: --> POST /wd/hub/session/7c0a9135-846a-422e-9bc5-6b81fb9061db/element {"using":"name","value":"Crash"}
> warn: [DEPRECATED] The name locator strategy has been deprecated and will be removed.  Please use the accessibility id locator strategy instead.
> info: [debug] Waiting up to 0ms for condition
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"name","selector":"Crash","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"name","selector":"Crash","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding Crash using NAME with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[DESCRIPTION=Crash, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[TEXT=Crash, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"ELEMENT":"1"},"status":0}
> info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"7c0a9135-846a-422e-9bc5-6b81fb9061db"}
> info: <-- POST /wd/hub/session/7c0a9135-846a-422e-9bc5-6b81fb9061db/element 200 2364.332 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"7c0a9135-846a-422e-9bc5-6b81fb9061db"}
> info: --> GET /wd/hub/session/7c0a9135-846a-422e-9bc5-6b81fb9061db/element/1/displayed {}
> info: [debug] Pushing command to appium work queue: ["element:getAttribute",{"elementId":"1","attribute":"displayed"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getAttribute","params":{"elementId":"1","attribute":"displayed"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getAttribute
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"true","status":0}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"7c0a9135-846a-422e-9bc5-6b81fb9061db"}
> info: <-- GET /wd/hub/session/7c0a9135-846a-422e-9bc5-6b81fb9061db/element/1/displayed 200 21.195 ms - 76 {"status":0,"value":true,"sessionId":"7c0a9135-846a-422e-9bc5-6b81fb9061db"}
> info: --> POST /wd/hub/session/7c0a9135-846a-422e-9bc5-6b81fb9061db/touch/perform {"actions":[{"action":"moveTo","options":{"element":"1"}},{"action":"tap","options":{"element":"1"}}]}
> info: [debug] Pushing command to appium work queue: ["element:getLocation",{"elementId":"1"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"1"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"y":1181,"x":8},"status":0}
> info: [debug] Pushing command to appium work queue: ["element:getSize",{"elementId":"1"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getSize","params":{"elementId":"1"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getSize
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"height":96,"width":140},"status":0}
> info: [debug] Pushing command to appium work queue: ["element:getLocation",{"elementId":"1"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"1"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"y":1181,"x":8},"status":0}
> info: [debug] Pushing command to appium work queue: ["element:getSize",{"elementId":"1"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getSize","params":{"elementId":"1"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getSize
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"height":96,"width":140},"status":0}
> info: [debug] Pushing command to appium work queue: ["element:touchMove",{"elementId":"1","x":78,"y":1229}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"elementId":"1","x":78,"y":1229}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
> info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? true x: 78, y: 1229
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Failed to execute touch event","status":13}
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Failed to execute touch event"},"sessionId":"7c0a9135-846a-422e-9bc5-6b81fb9061db"}
> info: <-- POST /wd/hub/session/7c0a9135-846a-422e-9bc5-6b81fb9061db/touch/perform 500 118.323 ms - 198

**Comment by SrinivasanTarget** [comment]
Please try a latest version of appium and raise a new issue along with logs incase if you hit the same.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by amiteshri92** [comment]
@SrinivasanTarget Can't this issue be resolved without upgrading the appium version?
