### ISSUE TITLE
How to switch to Main App

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium#5685]
Hi @jlipps , @Jonahss ,

In my IOS App, When i click on a button it opens and navigates AppStore App. But the actual app runs in background. Here I want to simply close the AppStore app and perform remaining automation on the Main App. How to do this?

**Comment by amedvedjev** [comment]
one of idea is try:
```
try { driver.runAppInBackground(1); }catch(Exception e){}
```

with Android it is restoring application to foreground

**Comment by shivakrishnach31** [comment]
@amedvedjev, I tried this. But not use.
We have driver.resetApp(); for iOS but it restoring the app from beginning. I don't want it from beginning i just want to take app to foreground only.

**Comment by Jonahss** [comment]
Can't exactly be done, due to apple testing constraints.
There *is* one potential option: if there is a button on the App Store UI
to transition back to your app, you could try sending a TouchAction to
those exact screen coordinates.

**Comment by SrinivasanTarget** [comment]
@triager please close
