### ISSUE TITLE
Appium fails to return backgrounded app to foreground (iOS, apostrophe escaping)

### ISSUE THREAD

**Issue by epiccoleman** [appium/appium#5690]
We have 2 versions the same iOS app.  Being built for different clients, the two applications have different app names.  When backgrounded with background_app (ruby_lib), one application behaves as expected - coming back to the foreground after the specified time. The other application fails to come back with the following error mesage: "Selenium::WebDriver::Error::JavascriptError: Unable to parse the format string "ANY elements.name == 'Foo's Bar". We have seen that there have been fixes in the past to resolve apostrophe escaping issues and wonder if this problem is related. The app that works has no apostrophe in the name.

**Comment by scottdixon** [comment]
Can you provider server logs as a gist?

**Comment by epiccoleman** [comment]
@scottdixon We ran the tests again to get the server log output. Unfortunately, these logs contain a lot of data that identifies our app and the company we're doing the work for. We're going to look into it here, but it's doubtful that we're going to be allowed to release these logs to you. Is there anything else we can do to help you guys track down the problem?

**Comment by scottdixon** [comment]
np @epiccoleman 

You could try to reproduce the issue in a sample app and provide the logs?

**Comment by epiccoleman** [comment]
@scottdixon ,

We finally got around to reproducing this issue in a sample app. I'm attaching the logs as requested.

[HelloWorldCommands](https://gist.github.com/epiccoleman/bc18f9384df0458d88d9) - This file contains the commands (in irb) we ran on a working sample app. There's no apostrophe in the name and `background_app` works fine.

[HelloWorldAppiumServer](https://gist.github.com/epiccoleman/65d2ea880b22956546c8) - This file is the server log for the working app (the commands run above).

[HelloWorld'sCommands](https://gist.github.com/epiccoleman/684557270fbca1737aa2) - This file contains the commands we ran to reproduce the bug. There is an apostrophe in the name of the app and `background_app` fails. I think this file probably has the error message that you're interested in. `Selenium::WebDriver::Error::JavascriptError: Unable to parse the format string "ANY elements.name == 'HelloWorld's'"`

[HelloWorld'sAppiumServer](https://gist.github.com/epiccoleman/2f1294bab3171b8ad498) - This file contains the Appium server for the failing attempt. 

Let us know if you need anything else, and thanks!

**Comment by scottdixon** [comment]
Thanks for all the logs.

I was able to reproduce the error in instruments:
![image](https://cloud.githubusercontent.com/assets/4726068/10617363/fbbe069a-771e-11e5-9fdd-2c347fc305e7.png)

Appium 1.4.13 also hits the error but it doesn't crash instruments, I'm able to continue sending commands. I see you're using Appium 1.4.8, can you try 1.4.13?

**Comment by epiccoleman** [comment]
@scottdixon - we have the same behavior after upgrading to 1.4.13. New server log is [here](https://gist.github.com/epiccoleman/62c41b4da6781a0b3549).

**Comment by dpgraham** [comment]
Closing. Instruments no longer supported.
