### ISSUE TITLE
App is crashing if user taps on hardware back when cursor is visible in the search field

### ISSUE THREAD

**Issue by dattatraymobiuso** [appium/appium#5694]
1. Open any resource screen
2. You are on Resource screen-> 1. Search field along with virtual keyboard
3. Minimize virtual keyboard but Still search field is visible and CURSOR is appearing in the field
4. Tap on hardware back
5. App crashed.

I have tries by changing the resource section where search field is not available then tries back operation. in this case app not crashed.

**Comment by scottdixon** [comment]
Can you please provide server logs as a gist.
