### ISSUE TITLE
How can i pick date time on android.view.View

### ISSUE THREAD

**Issue by vietch2612** [appium/appium#5696]
![Element](http://i.imgur.com/rKWhEJY.png)

I had an issue, cant pick some date from this. please help

**Comment by vietch2612** [comment]
anyone here

**Comment by scottdixon** [comment]
@vietch2612 what issue are you facing? Please provide server logs as a gist.

**Comment by vietch2612** [comment]
You can see on my picture, how i can pick some date on that element?
