### ISSUE TITLE
Element not visible exception.

### ISSUE THREAD

**Issue by murlismiles** [appium/appium#5698]
Am automating the app in the webview and input is of type tel and no default focus is set for it. driver.sendtext is not working but able to achieve it by sending it through javascript executor. now that value is sent to the text box, i need to clik on enter to proceed to the next screen but not able to achieve it.

**Comment by scottdixon** [comment]
What issue are you facing? Please provide server logs as a gist.

**Comment by SrinivasanTarget** [comment]
@triager please close
