### ISSUE TITLE
Getting error while executing program to swipe down the screen using Appium

### ISSUE THREAD

**Issue by srivatsava1987** [appium/appium#5699]
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.Test;

import io.appium.java_client.MobileDriver;
import io.appium.java_client.TouchAction;
import io.appium.java_client.android.AndroidDriver;

public class SwipeScreen {
	AndroidDriver dr;
	@Test
	public void testApp() throws MalformedURLException, InterruptedException{
	DesiredCapabilities capabilities = new DesiredCapabilities("appWaitActivity", null, null);
	File app =new File(System.getProperty("user.dir")+"\\app\\net.one97.paytm (1).apk");
	capabilities.setCapability(CapabilityType.BROWSER_NAME, "android"); 
	 capabilities.setCapability("deviceName","samsung-gt_i9060-42035bec4397 c000");
	  capabilities.setCapability("PlatformVersion","4.2.2");
	  capabilities.setCapability("PlatformName","Android");
	  capabilities.setCapability("app",app.getAbsolutePath());
	 // capabilities.setCapability("appPackage","com.android.settings");
	 // capabilities.setCapability("appActivity","com.android.settings.SettingsTabActivity");
	  dr = new AndroidDriver(new URL("http://192.168.10.165:4723/wd/hub"),capabilities);
	  dr.manage().timeouts().implicitlyWait(4, TimeUnit.SECONDS);
	Thread.sleep(30000);
	System.out.println(dr.manage().window().getSize().getWidth());
	System.out.println(dr.manage().window().getSize().getHeight());
	int screenWidth = dr.manage().window().getSize().getWidth();
	int screenHeight = dr.manage().window().getSize().getHeight();
	//Swipe Right
	int startx = screenWidth*8/9;
	int endx = screenWidth/9;
	int starty = screenHeight/2;
	int endy = screenHeight/2;
	dr.swipe(startx, starty, endx, endy, 5000);
	Thread.sleep(10000);
	 //Swipe Left
	startx = screenWidth/9;
	endx = screenWidth*8/9;
	starty = screenHeight/2;
	endy = screenHeight/2;
	dr.swipe(startx, starty, endx, endy, 5000);
	Thread.sleep(10000);
	//swipe down
	startx = screenWidth/2;
	endx = screenWidth/2;
	starty = screenHeight*6/7;
	endy = screenHeight/5;
	TouchAction action = new TouchAction((MobileDriver)dr);
	action.press(startx,starty).waitAction(10000).moveTo(endx,endy).release().perform();	
	//System.out.println(startx+" "+starty+" "+endx+" "+endy);
	//dr.swipe(startx, starty, endx, endy, 10000);
	Thread.sleep(50000);
	//swipe up
	startx = screenWidth/2;
	endx = screenWidth/2;
	starty = screenHeight/6;
	endy = screenHeight*5/6;
	dr.swipe(startx, starty, endx, endy, 5000);
	
	}
}

Error:
--------
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session.  
Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:58'
System info: host: 'Halcyon2-PC', ip: '192.168.140.172', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_67'
Driver info: driver.version: AndroidDriver

Appium Log:
-----------------
> Starting Node Server
> warn: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
> info: Welcome to Appium v1.4.0 (REV 8f63e2f91ef7907aed8bda763f4e5ca08e86970a)
> info: Appium REST http interface listener started on 192.168.10.165:4723
> info: [debug] Non-default server args: {"address":"192.168.10.165","logNoColors":true,"platformName":"Android","platformVersion":"18","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"D:\\AppleWorkspace\\Srikanth_test\\app\\net.one97.paytm (1).apk","platform":null,"deviceName":"samsung-gt_i9060-42035bec4397 c000","platformName":"Android","browserName":"android","PlatformVersion":"4.2.2","PlatformName":"Android","version":null}}
> info: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : platform, PlatformVersion, PlatformName, version
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from desired caps: D:\AppleWorkspace\Srikanth_test\app\net.one97.paytm (1).apk
> info: [debug] Creating new appium session 273ff4b1-88ae-49d0-957a-29457bb598c8
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.7.0_67
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe
> info: [debug] Parsing package and activity from app manifest
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\srivatsava\AppData\Local\Android\android-sdk\build-tools\22.0.1\aapt.exe
> info: [debug] Extracting package and launch activity from manifest.
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\build-tools\22.0.1\aapt.exe dump badging "D:\AppleWorkspace\Srikanth_test\app\net.one97.paytm (1).apk"
> info: [debug] badging package: net.one97.paytm
> info: [debug] badging act: net.one97.paytm.AJRJarvisSplash
> info: [debug] Parsed package and activity are: net.one97.paytm/net.one97.paytm.AJRJarvisSplash
> info: [debug] Set chromedriver binary as: C:\Program Files\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device 42035bec4397c000
> info: [debug] Setting device id to 42035bec4397c000
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 wait-for-device
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 17
> info: Device API level is: 17
> info: [debug] Extracting strings for language: default
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] java -jar "C:\Program Files\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "D:\AppleWorkspace\Srikanth_test\app\net.one97.paytm (1).apk" "C:\Users\SRIVAT~1\AppData\Local\Temp\net.one97.paytm" en
> info: [debug] No strings.xml for language 'en', getting default strings.xml
> info: [debug] java -jar "C:\Program Files\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "D:\AppleWorkspace\Srikanth_test\app\net.one97.paytm (1).apk" "C:\Users\SRIVAT~1\AppData\Local\Temp\net.one97.paytm"
> info: [debug] Reading strings from converted strings.json
> info: [debug] Setting language to default
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 push "C:\\Users\\SRIVAT~1\\AppData\\Local\\Temp\\net.one97.paytm\\strings.json" /data/local/tmp
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\srivatsava\AppData\Local\Android\android-sdk\build-tools\22.0.1\aapt.exe
> info: [debug] Retrieving process from manifest.
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\build-tools\22.0.1\aapt.exe dump xmltree "D:\AppleWorkspace\Srikanth_test\app\net.one97.paytm (1).apk" AndroidManifest.xml
> info: [debug] Set app process to: net.one97.paytm
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Checking app cert for D:\AppleWorkspace\Srikanth_test\app\net.one97.paytm (1).apk.
> info: [debug] executing cmd: java -jar "C:\Program Files\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar" "D:\AppleWorkspace\Srikanth_test\app\net.one97.paytm (1).apk"
> info: [debug] App already signed.
> info: [debug] Zip-aligning D:\AppleWorkspace\Srikanth_test\app\net.one97.paytm (1).apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\srivatsava\AppData\Local\Android\android-sdk\build-tools\22.0.1\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\build-tools\22.0.1\zipalign.exe -f 4 "D:\AppleWorkspace\Srikanth_test\app\net.one97.paytm (1).apk" C:\Users\SRIVAT~1\AppData\Local\Temp\11598-1644-1t9lyap\appium.tmp
> info: [debug] MD5 for app is 99b3b9d26b581b6e946cda3753a70cd0
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "ls /data/local/tmp/99b3b9d26b581b6e946cda3753a70cd0.apk"
> info: [debug] Getting install status for net.one97.paytm
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 17
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "pm list packages -3 net.one97.paytm"
> info: [debug] App is installed
> info: App is already installed, resetting app
> info: [debug] Running fast reset (stop and clear)
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "am force-stop net.one97.paytm"
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "pm clear net.one97.paytm"
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 push "C:\\Program Files\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 install "C:\Program Files\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 install "C:\Program Files\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg net.one97.paytm -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] json loading complete.
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 17
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n net.one97.paytm/net.one97.paytm.AJRJarvisSplash"
> info: [debug] Waiting for pkg "net.one97.paytm" and activity "net.one97.paytm.AJRJarvisSplash" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "dumpsys window windows"
> info: [debug] executing cmd: C:\Users\srivatsava\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42035bec4397c000 shell "getprop ro.build.version.release"
> info: [debug] Device is at release version 4.2.2
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId 273ff4b1-88ae-49d0-957a-29457bb598c8
> info: <-- POST /wd/hub/session 303 13698.623 ms - 74 
> info: --> GET /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8 {}
> info: [debug] Responding to client with success: {"status":0,"value":{"platform":null,"browserName":"android","platformVersion":"4.2.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"D:\\AppleWorkspace\\Srikanth_test\\app\\net.one97.paytm (1).apk","platform":null,"deviceName":"samsung-gt_i9060-42035bec4397 c000","platformName":"Android","browserName":"android","PlatformVersion":"4.2.2","PlatformName":"Android","version":null},"app":"D:\\AppleWorkspace\\Srikanth_test\\app\\net.one97.paytm (1).apk","deviceName":"42035bec4397c000","platformName":"Android","PlatformVersion":"4.2.2","PlatformName":"Android","version":null},"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: <-- GET /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8 200 3.458 ms - 774 {"status":0,"value":{"platform":null,"browserName":"android","platformVersion":"4.2.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"D:\\AppleWorkspace\\Srikanth_test\\app\\net.one97.paytm (1).apk","platform":null,"deviceName":"samsung-gt_i9060-42035bec4397 c000","platformName":"Android","browserName":"android","PlatformVersion":"4.2.2","PlatformName":"Android","version":null},"app":"D:\\AppleWorkspace\\Srikanth_test\\app\\net.one97.paytm (1).apk","deviceName":"42035bec4397c000","platformName":"Android","PlatformVersion":"4.2.2","PlatformName":"Android","version":null},"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: --> POST /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/timeouts/implicit_wait {"ms":4000}
> info: [debug] Set Android implicit wait to 4000ms
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: <-- POST /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/timeouts/implicit_wait 200 2.948 ms - 76 {"status":0,"value":null,"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: --> GET /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/window/current/size {}
> info: [debug] Pushing command to appium work queue: ["getDeviceSize"]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDeviceSize","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDeviceSize
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"width":480,"height":800},"status":0}
> info: [debug] Responding to client with success: {"status":0,"value":{"width":480,"height":800},"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: <-- GET /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/window/current/size 200 19.066 ms - 98 {"status":0,"value":{"width":480,"height":800},"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: --> GET /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/window/current/size {}
> info: [debug] Pushing command to appium work queue: ["getDeviceSize"]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDeviceSize","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDeviceSize
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"width":480,"height":800},"status":0}
> info: [debug] Responding to client with success: {"status":0,"value":{"width":480,"height":800},"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: <-- GET /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/window/current/size 200 9.635 ms - 98 {"status":0,"value":{"width":480,"height":800},"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: --> GET /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/window/current/size {}
> info: [debug] Pushing command to appium work queue: ["getDeviceSize"]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDeviceSize","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDeviceSize
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"width":480,"height":800},"status":0}
> info: [debug] Responding to client with success: {"status":0,"value":{"width":480,"height":800},"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: <-- GET /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/window/current/size 200 7.199 ms - 98 {"status":0,"value":{"width":480,"height":800},"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: --> GET /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/window/current/size {}
> info: [debug] Pushing command to appium work queue: ["getDeviceSize"]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDeviceSize","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDeviceSize
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":{"width":480,"height":800},"status":0}
> info: [debug] Responding to client with success: {"status":0,"value":{"width":480,"height":800},"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: <-- GET /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/window/current/size 200 7.250 ms - 98 {"status":0,"value":{"width":480,"height":800},"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: --> POST /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/touch/perform {"actions":[{"action":"press","options":{"y":400,"x":426}},{"action":"wait","options":{"ms":5000}},{"action":"moveTo","options":{"y":400,"x":53}},{"action":"release","options":{}}]}
> info: [debug] Pushing command to appium work queue: ["swipe",{"startX":426,"startY":400,"endX":53,"endY":400,"steps":140}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"swipe","params":{"startX":426,"startY":400,"endX":53,"endY":400,"steps":140}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: swipe
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][480,800]
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][480,800]
> info: [debug] [BOOTSTRAP] [debug] Swiping from [x=426.0, y=400.0] to [x=53.0, y=400.0] with steps: 140
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: <-- POST /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/touch/perform 200 3633.035 ms - 76 {"status":0,"value":true,"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: --> POST /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/touch/perform {"actions":[{"action":"press","options":{"y":400,"x":53}},{"action":"wait","options":{"ms":5000}},{"action":"moveTo","options":{"y":400,"x":426}},{"action":"release","options":{}}]}
> info: [debug] Pushing command to appium work queue: ["swipe",{"startX":53,"startY":400,"endX":426,"endY":400,"steps":140}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"swipe","params":{"startX":53,"startY":400,"endX":426,"endY":400,"steps":140}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: swipe
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][480,800]
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][480,800]
> info: [debug] [BOOTSTRAP] [debug] Swiping from [x=53.0, y=400.0] to [x=426.0, y=400.0] with steps: 140
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: <-- POST /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/touch/perform 200 5663.971 ms - 76 {"status":0,"value":true,"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: --> POST /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/touch/perform {"actions":[{"action":"press","options":{"y":685,"x":240}},{"action":"wait","options":{"ms":10000}},{"action":"moveTo","options":{"y":160,"x":240}},{"action":"release","options":{}}]}
> info: [debug] Pushing command to appium work queue: ["swipe",{"startX":240,"startY":685,"endX":240,"endY":160,"steps":280}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"swipe","params":{"startX":240,"startY":685,"endX":240,"endY":160,"steps":280}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: swipe
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][480,800]
> info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][480,800]
> info: [debug] [BOOTSTRAP] [debug] Swiping from [x=240.0, y=685.0] to [x=240.0, y=160.0] with steps: 280
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"The swipe did not complete successfully","status":13}
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"The swipe did not complete successfully"},"sessionId":"273ff4b1-88ae-49d0-957a-29457bb598c8"}
> info: <-- POST /wd/hub/session/273ff4b1-88ae-49d0-957a-29457bb598c8/touch/perform 500 9874.198 ms - 208

**Comment by scottdixon** [comment]
Closing old issue. Please try a more recent version of Appium. Reopen if the issue persists.
