### ISSUE TITLE
Failed to init iosdriver for  can not found ideviceinstaller, but i installed it 

### ISSUE THREAD

**Issue by ataraxia2013** [appium/appium#5702]
driver = new IOSDriver<MobileElement>(service.getUrl(), capabilities);
Failed to init IOSDriver 
error info ：
Failed to start an Appium session, err was: Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
[36minfo[39m: [debug] Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system

but~  i installed it already~

yixuantekiMacBook-Pro:libimobiledevice-macosx yixuan$ ideviceinstaller 
ERROR: No mode/operation was supplied.
Usage: ideviceinstaller OPTIONS
Manage apps on iOS devices.

  -u, --udid UDID	Target specific device by its 40-digit device UDID.
  -l, --list-apps	List apps, possible options:
       -o list_user	- list user apps only (this is the default)
       -o list_system	- list system apps only
       -o list_all	- list all types of apps
       -o xml		- print full output as xml plist

who can give me some help~ thx~

**Comment by scottdixon** [comment]
Have you tried any of these solutions: https://github.com/appium/appium/issues/4584

Let me know if you're still stuck and I'll reopen the issue.
