### ISSUE TITLE
get An unknown server-side error occurred while processing the command when try use move to method

### ISSUE THREAD

**Issue by tobecrazy** [appium/appium#5703]
## My code

```
driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    // swipe to right
    System.out.println(driver.getPageSource());
    // swipeToRight(driver, 2000);
    int width = driver.manage().window().getSize().width;
    int height = driver.manage().window().getSize().height;
    final TouchAction touchAction = new TouchAction(driver);
    // appium converts press-wait-move to-release to a swipe action
    touchAction.press(width / 4, height / 4).waitAction(2500).moveTo(width / 4, 2*height /3).release();
    touchAction.perform();
```
## Appium log

info: [debug] Pushing command to appium work queue: ["swipe",{"startX":270,"startY":480,"endX":270,"endY":1280,"steps":70}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"swipe","params":{"startX":270,"startY":480,"endX":270,"endY":1280,"steps":70}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: swipe
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1920]
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][1080,1920]
info: [debug] [BOOTSTRAP] [debug] Swiping from [x=270.0, y=480.0] to [x=270.0, y=1280.0] with steps: 70
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":13,"value":"The swipe did not complete successfully"}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"The swipe did not complete successfully"},"sessionId":"ad0168d7-ffd8-4091-90a4-b109c9f875a2"}
info: <-- POST /wd/hub/session/ad0168d7-ffd8-4091-90a4-b109c9f875a2/touch/perform 500 2624.817 ms - 208
info: --> DELETE /wd/hub/session/ad0168d7-ffd8-4091-90a4-b109c9f875a2 {}
info: Shutting down appium session
## Expected

should be works because the moveTo point is inside of my screen.
you see Swiping from [x=270.0, y=480.0] to [x=270.0, y=1280.0]  is in side Display bounds: [0,0][1080,1920]
## ENV ：

OS： window 10 
JDK: 1.7 
Java-client :3.2
Appium: V1.4.0

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.64 seconds
Build info: version: '2.48.0', revision: 'b7b081a', time: '2015-10-07 15:48:56'
System info: host: 'Young-PC', ip: '192.168.28.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.7.0_79'
Session ID: ad0168d7-ffd8-4091-90a4-b109c9f875a2
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{platform=LINUX, javascriptEnabled=true, appActivity=.ui.WelcomeActivity, browserName=, networkConnectionEnabled=true, noSign=true, desired={platformVersion=5.1, deviceName=Android Emulator, platformName=Android, appActivity=.ui.WelcomeActivity, browserName=, noSign=true, appPackage=mobi.w3studio.apps.android.shsmy.phone}, locationContextEnabled=false, appPackage=mobi.w3studio.apps.android.shsmy.phone, platformVersion=5.1, databaseEnabled=false, platformName=Android, deviceName=71UBBLF22G3W, webStorageEnabled=false, warnings={}, takesScreenshot=true}]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
    at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
    at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
    at io.appium.java_client.AppiumDriver.performTouchAction(AppiumDriver.java:297)
    at io.appium.java_client.TouchAction.perform(TouchAction.java:301)
    at com.dbyl.core.slideToUnlock.swipeTest(slideToUnlock.java:73)

**Comment by chenhengjie123** [comment]
I found that the implementation on Android controller would treat coordinate in `moveTo` as offset for current position.

> /lib/devices/android/android-controller.js
```
androidController.parseTouch = function (gestures, multi, cb) {
  if (multi && _.last(gestures).action === 'release') {
    gestures.pop();
  }

  var needsPoint = function (action) {
    return _.contains(['press', 'moveTo', 'tap', 'longPress'], action);
  };

  var touchStateObjects = [];
  async.eachSeries(gestures, function (gesture, done) {
    var options = gesture.options;
    if (needsPoint(gesture.action)) {
      options.offset = false;
      var elementId = gesture.options.element;
      if (elementId) {
        this.getLocation(elementId, function (err, res) {
          if (err) return done(err); // short circuit and quit

          var pos = { x: res.value.x, y: res.value.y };
          this.getSize(elementId, function (err, res) {
            if (err) return done(err);
            var size = {w: res.value.width, h: res.value.height};

            if (gesture.options.x || gesture.options.y) {
              options.x = pos.x + (gesture.options.x || 0);
              options.y = pos.y + (gesture.options.y || 0);
            } else {
              options.x =  pos.x + (size.w / 2);
              options.y = pos.y + (size.h / 2);
            }

            var touchStateObject = {
              action: gesture.action,
              options: options,
              timeOffset: 0.005,
            };
            touchStateObjects.push(touchStateObject);
            done();
          });
        }.bind(this));
      } else {
        // expects absolute coordinates, so we need to save these as offsets
        // and then translate when everything is done
        options.offset = true;
        options.x = (gesture.options.x || 0);
        options.y = (gesture.options.y || 0);

        touchStateObject = {
          action: gesture.action,
          options: options,
          timeOffset: 0.005,
        };
        touchStateObjects.push(touchStateObject);
        done();
      }
    } else {
      var offset = 0.005;
      if (gesture.action === 'wait') {
        options = gesture.options;
        offset = (parseInt(gesture.options.ms) / 1000);
      }
      var touchStateObject = {
        action: gesture.action,
        options: options,
        timeOffset: offset,
      };
      touchStateObjects.push(touchStateObject);
      done();
    }
  }.bind(this), function (err) {
    if (err) return cb(err);

    // we need to change the time (which is now an offset)
    // and the position (which may be an offset)
    var prevPos = null,
        time = 0;
    _.each(touchStateObjects, function (state) {
      if (typeof state.options.x === 'undefined' && typeof state.options.x === 'undefined') {
        // this happens with wait
        state.options.x = prevPos.x;
        state.options.y = prevPos.y;
      }
      if (state.options.offset && prevPos) {
        // the current position is an offset
        state.options.x += prevPos.x;
        state.options.y += prevPos.y;
      }
      delete state.options.offset;
      prevPos = state.options;

      if (multi) {
        var timeOffset = state.timeOffset;
        time += timeOffset;
        state.time = helpers.truncateDecimals(time, 3);

        // multi gestures require 'touch' rather than 'options'
        state.touch = state.options;
        delete state.options;
      }

      delete state.timeOffset;
    });

    cb(null, touchStateObjects);
  });
};
```

When met moveTo without elementId, it would call `options.offset = true;`. So the coordinate would be treated as offset.

I'm not sure whether it's a bug or by design. But it confused a lot of people since [documents for touching actions](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md) did not mention this. I just seem Java-client [mention this](https://github.com/appium/java-client/commit/d7874ca6b93f3e72f612402beea61964033ce9fe) in its JavaDoc.

Can we mention it in the touching actions document of appium or just fix it? @jlipps @imurchie

**Comment by imurchie** [comment]
We will update this in the documentation. It is by design.

**Comment by Steve-Liu** [comment]
i think it is not just document issue. 
prior to v1.4.0, like v1.3.7 or v1.3.6, the moveTo(int,int) works for absolute coordinates. 
After 1.4.0, then it does not work either absolute coordinates or relative coordinates to the current position on the screen, at least for android that i tested.

here is what i have seen, i have a knob on a wheel widget that i want to move around. 
the initial coordinates of the knob are, x=410, y=456. then i do some calculations and the destX and destY that i want to move it to on the wheel are 402 and 428 respectively. prior to 1.4.0, i just passed in the coordinates then it would work. then this time, i do additional calculation to calculate the offset coordinates which is x=-8 and y =-28. here are my codes 

 moveKnob.press(knob.firstElement())  // here i press the knob
           int xOnWheel = new Double(wheelCenterX + radius *
                            Math.cos(Math.toRadians(angle + sign * steps  - RIGHT_ANGLE))).intValue(); // calculate the x coordinates on the wheel 
            int yOnWheel = new Double(wheelCenterY + radius *
                            Math.sin(Math.toRadians(angle + sign * steps  - RIGHT_ANGLE))).intValue(); // calculate the y coordinates on the wheel 

            moveKnob.moveTo(xOnWheel-knobX, yOnWheel-knobY).release().perform();  // using the offset coordinates to move the knob

then it throws exception here

info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchDown","params":{"elementId":"25","x":410,"y":456}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchDown
info: [debug] [BOOTSTRAP] [debug] Performing TouchDown using element? true x: 410, y: 456
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] Pushing command to appium work queue: ["element:touchMove",{"x":402,"y":428}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":402,"y":428}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchMove
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][2048,1536]
info: [debug] [BOOTSTRAP] [debug] Performing TouchMove using element? false x: 402, y: 428
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
info: [debug] Pushing command to appium work queue: ["element:touchUp",{"x":-8,"y":-28}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:touchUp","params":{"x":-8,"y":-28}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: touchUp
info: [debug] [BOOTSTRAP] [debug] Display bounds: [0,0][2048,1536]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":29,"value":"Coordinate [x=-8.0, y=-28.0] is outside of element rect: [0,0][2048,1536]"}
info: [debug] Responding to client with error: {"status":29,"value":{"message":"The coordinates provided to an interactions operation are invalid.","origValue":"Coordinate [x=-8.0, y=-28.0] is outside of element rect: [0,0][2048,1536]"},"sessionId":"b847ac52-9486-4a42-8b9c-4f715e1bb000"}


 there is chance i missed something or im completely wrong.
please correct me if so. if not i think it is an issue.

**Comment by Steve-Liu** [comment]
some of my comments are gonna for weird reason. so here i add them.

in the exception, "Pushing command to appium work queue: ["element:touchUp",{"x":-8,"y":-28}]" the x= -8 and y=-28 should never been used per the java doc of moveTo(int,int) because it uses oldX+x and oldY+y. So "Pushing command to appium work queue: ["element:touchMove",{"x":402,"y":428}]" this is right one. the moveTo gets executed only once,  then why there are two pushing commands to appium work queue when it only executed once? and if you have some retry mechanism in appium, then why the second time is using the negative number?

**Comment by jonstoneman** [comment]
@imurchie: What is the reason for that design choice?  Shouldn't moveto's coordinates always be handled in the same way regardless of other actions within the sequence?  On Android, they are not treated as offsets within the press/wait/moveto/release and longpress/moveto/release sequences:

- https://github.com/appium/appium/blob/f5a04fdcc0707d1911b8263e06b7ea4bd816748e/lib/server/controller.js#L329
- https://github.com/appium/appium/blob/f5a04fdcc0707d1911b8263e06b7ea4bd816748e/lib/devices/android/android-controller.js#L1000

**Comment by jlipps** [comment]
going to track this in #7486.
