### ISSUE TITLE
Issues with Simulators on Appium 1.4.13

### ISSUE THREAD

**Issue by seleniumappiumnewbie** [appium/appium#5705]
Issue: Cannot run tests with Simulators on Appium 1.4.13 - Simulator cannot Load and Crashes and Restarts in a Loop

Running simulator tests on Appium 1.4.13 fails, but Running real iPhone device tests works if installed appium via git clone, but not via npm, because safari launcher is not set up with npm correctly. 

Environment: Mac El Capitan, Xcode 7.0.1, Appium 1.4.13

Note: My setup passes Appium-Doctor check

Steps to Reproduce:
1. Install Appium
1a. Install from source
-Type git clone https://github.com/appium/appium.git
-Type in terminal to find code-signing identity: security find-identity -v -p codesigning
-Type $ ./reset.sh --ios --real-safari --code-sign 'code signing identity' --profile 'retrieved profile identity code'
1b. Or Install from npm
-npm install -g appium
-npm install wd
2. Open Appium GUI App 1.4.8
Select "Developer settings" and enable it.
Select Use External NodeJS Binary to /usr/local/bin/node
Select Use External Appium Package and link to appium folder path
4. Set Force Device to iPhone 6 in Appium GUI App
5. Open Xcode
6. Start Appium Server via Appium GUI App if install from source
Start Appium Server via terminal appium & if install from npm
7. Launch iPhone 6 Simulator next or leave the script to launch it
8. Run simulator script from Eclipse

Actual Results;
1. Get this error "Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version"
2. It would keep opening and closing the simulator in a loop.

Error Details:
unknown20C9D0E03E3B:~ mac$ info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"Safari","platformName":"iOS","deviceName":"iPhone 6","platformVersion":"9.0"}}
info: Client User-Agent string: Apache-HttpClient/4.4.1 (Java/1.8.0_60)
info: [debug] Configuring Safari session
info: [debug] We're on iOS8+ so not copying mobile safari app
info: [debug] Creating new appium session dd9efbb0-e4ac-496f-ab7c-33e016ba4ab0
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version
info: [debug] Xcode version set to 7.0.1
info: [debug] Setting iOS SDK Version
error: Could not determine iOS SDK version
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version

info: [debug] Error: Command failed: /bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: /bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version\n)","cause":{"killed":true,"code":null,"signal":"SIGTERM","cmd":"/bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version"},"isOperational":true,"killed":true,"code":null,"signal":"SIGTERM","cmd":"/bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version","origValue":"Command failed: /bin/sh -c xcrun --sdk iphonesimulator --show-sdk-version\n"},"sessionId":null}
info: <-- POST /wd/hub/session 500 9977.276 ms - 525 

Simulator Script Used:
package com.example.appium;
import java.net.MalformedURLException;
import java.net.URL;
import org.openqa.selenium.By;
import io.appium.java_client.ios.IOSDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;

public class IOSSimulatorWithIOSDriver {

	@SuppressWarnings("rawtypes")
	public static void main(String... args) throws InterruptedException, MalformedURLException{
        DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
        desiredCapabilities.setCapability("platformName", "iOS");
        desiredCapabilities.setCapability("platformVersion", "9.0");
        desiredCapabilities.setCapability("deviceName", "iPhone 6");
        desiredCapabilities.setCapability("browserName", "Safari"); 

		IOSDriver<?> driver;
        driver= new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), desiredCapabilities);
        driver.get("http://www.google.com");
        WebElement ele =driver.findElement(By.name("q"));
        ele.click();
        ele.sendKeys("Packt Publishing");
        WebElement searchButton =
        driver.findElement(By.name("btnG"));
        System.out.println(searchButton.getSize());
        searchButton.click();
        Thread.sleep(5000);
        driver.quit();
    }
 }

Note: I'm new to appium and if this is an easy setup fix, let me know what I'm doing wrong and please help me to set it up correctly to run tests. Thank you for looking into this.

**Comment by scottdixon** [comment]
`cd` into `appium` and run `node bin/appium-doctor.js --dev`

What is the output?

**Comment by seleniumappiumnewbie** [comment]
I installed the new appium 1.4.13 dmg and got over the start error by copying the old 1.4.8 appium node_modules into the 1.4.13 folder.

Then I tried to rerun my simulator script, but now I get a new error that says appium can’t find my devices.

Appium-Doctor Returns:
Running iOS Checks
✔ Xcode is installed at /Applications/Xcode.app/Contents/Developer
✔ Xcode Command Line Tools are installed.
✔ DevToolsSecurity is enabled.
✔ The Authorization DB is set up properly.
✔ Node binary found at /usr/local/bin/node
✔ iOS Checks were successful.

Running Android Checks
✔ ANDROID_HOME is set to "/Users/vnvdm/Documents/android-sdk-macosx"
✔ JAVA_HOME is set to "/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home."
✔ ADB exists at /Users/vnvdm/Documents/android-sdk-macosx/platform-tools/adb
✔ Android exists at /Users/vnvdm/Documents/android-sdk-macosx/tools/android
✔ Emulator exists at /Users/vnvdm/Documents/android-sdk-macosx/tools/emulator
✔ Android Checks were successful.

Running Dev Checks
✔ mvn was found at /usr/local/apache-maven/apache-maven-3.3.3/bin/mvn
✔ adb was found at /Users/vnvdm/Documents/android-sdk-macosx/platform-tools/adb
✔ ant was found at /usr/local/bin/ant
✔ android-16 exists at /Users/vnvdm/Documents/android-sdk-macosx/platforms/android-16
✔ android-19 exists at /Users/vnvdm/Documents/android-sdk-macosx/platforms/android-19
✔ Dev Checks were successful.

✔ All Checks were successful

Appium Server Logs:
info: Client User-Agent string: Apache-HttpClient/4.4.1 (Java/1.8.0_60)
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***

info: ****        NEW SESSION           ***

info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************

info: *************************************
info: *************************************
info: *************************************
info: [debug] Configuring Safari session
info: [debug] We're on iOS8+ so not copying mobile safari app
info: [debug] Creating new appium session 778ddbef-9b86-4391-92dc-86338fc5c99c
info: [debug] Removing any remaining instruments sockets

info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version
info: [debug] Xcode version set to 7.0.1
info: [debug] Setting iOS SDK Version
info: [debug] iOS SDK Version set to 9.0
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

error: Failed getting devices. Err: Error: Command failed: /bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices
. Stdout: . Stderr: .

info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

error: Failed getting devices. Err: Error: Command failed: /bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices
. Stdout: . Stderr: .

info: [debug] Getting list of devices instruments supports

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"778ddbef-9b86-4391-92dc-86338fc5c99c"}

info: <-- GET /wd/hub/status 200 2.528 ms - 179 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"778ddbef-9b86-4391-92dc-86338fc5c99c"}

error: Failed getting devices. Err: Error: Command failed: /bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices
. Stdout: . Stderr: .

info: [debug] Cleaning up appium session

error: Failed to start an Appium session, err was: Error: Failed getting devices. Err: Error: Command failed: /bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices
. Stdout: . Stderr: .

info: [debug] Error: Failed getting devices. Err: Error: Command failed: /bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices
. Stdout: . Stderr: .
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:109:19
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Failed getting devices. Err: Error: Command failed: /bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices\n. Stdout: . Stderr: .)","origValue":"Failed getting devices. Err: Error: Command failed: /bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices\n. Stdout: . Stderr: ."},"sessionId":null}
info: <-- POST /wd/hub/session 500 37563.812 ms - 444

**Comment by seleniumappiumnewbie** [comment]
The original issue still exists. I still see the simulator crashing and restarting in a loop with the original steps if I set the Appium GUI app's developer settings' External Appium Package to link to the git clone folder of Appium instead of using the .app version.

**Comment by seleniumappiumnewbie** [comment]
Should I reclone from git to get more recent code?

**Comment by scottdixon** [comment]
What's the output when you run `/bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices` from the command line?

**Comment by seleniumappiumnewbie** [comment]
I don't have access to my mac now. I will run the command when I get home tonight. Will update you by tomorrow morning. Thanks for your help.

**Comment by seleniumappiumnewbie** [comment]
I see 
unknown20C9D0E03E3B:~ vnvdm$ /bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices

instruments, version 7.0.1 (58157)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]

**Comment by felixwcf** [comment]
Having all the problems mentioned on iOS 9.1 and Appium 1.4.13, tested and solved them in 1 solid day.

**Mac El Capitan (Ver 10.11.1), Xcode 7.0.1(7B91b), Appium 1.4.13**

**iPhone 5 (iOS 7.0.4) - OK**
i. In Xcode, make sure the Debug Code Signing Identity in Build Settings->Code Signing is set to **Developer** provisioning  profile.
ii. Build and run (⌘R) the app directly to the real device from Xcode. After that stop the running.
iii.  Build the app (⌘B) so it will generate the .app file.
iv. In Appium->iOS Settings, point the App Path to the app located in **Debug-iphonesimulator**. Set the **Force Device**, **Platform Version**  , and **UDID**.
v. In Appium, click Launch and then Inspector.

**For iPhone with iOS 8 and above - OK**
i. In your iPhone device, Go to **Settings -> Developer**, Enable the **UI Automation**.
ii. Same steps as iPhone 5 (iOS 7.0.4)  starting from i to v.

iPhone 6 (iOS 8.4.1) - OK
iPhone 6 Plus (iOS 9.0.2) - OK
iPhone 6 (iOS 9.1) - OK
iPad Mini 2 (iOS 7.1.2) -  OK
iPad Air (iOS 9.0.2) - OK

**For simulator - OK**
In **Appium-> Developer Settings**, check **Custom Server Flags** and insert **--native-instruments-lib**.

**Comment by KashishAggarwal** [comment]
Hi felixwcf,

Still getting confused, I need to Automate my application on ios simulator,

Configuration i am using:- Appium(1.4.13) and Mac(10.10.5), Need to simulate for iPhone6.

Can u please mention me the complete steps from making iosSimulator app from Xcode to Appium Settings. so as to launch Appium inspector and IOSsimulator using Appium...

**Comment by felixwcf** [comment]
What is the Xcode version are you using? 

I don't encountered the issue that you've mentioned in your screenshot above. Normally if you checked 'Custom Server Flags', the textbox below obviously having the purpose for users to fill in texts.

Maybe you need to go to Appium-> Reset Preferences.

or

https://github.com/appium/appium/issues/3887

**Comment by KashishAggarwal** [comment]
Hi felixwcf,

I am able to launch my ios simulator, but now when I am trying to click and perform sendkeys command from my eclipse script but its not working....


I raised issue yesterday,"Click and Sendkeys is not working with Appium v1.4.13, Xcode 7.0.1, on Ios simulator iPhone6 with platform version 8.1 #5779"

Can u guys please help me on this, what all mandatory things requires to perform click/sendkeys.... From importing jar file, sysntax of script to be used in eclipse for IOS simulator....

####### Please help me urgently, if anyone knows the answer.... It will be great help

**Comment by zcmgyu** [comment]
I have same issue

**Comment by felixwcf** [comment]
Hi, I'm sorry I can't help on this time, as I'm using IntelliJ IDE...

Remember to launch your Appium server before you run your test script in java IDE.
You can use Maven cmd to execute your script too.

**Comment by KashishAggarwal** [comment]
Felixwcf,

Another help if you can provide, can u please check my issue #517

**Comment by KashishAggarwal** [comment]
Hi,

Can you please help me in resolving this, i tried to recover Appium server
from last 4 hours...


Appium Server is not getting started after, performing Appium RESET
PREFERENCES option and filling desired capabilities for IOS simulator. #517

**Comment by felixwcf** [comment]
Could you please provide your appium output?

**Comment by KashishAggarwal** [comment]
I click on Set Preferences option in Appium and after that i am not able to
start Appium Server after providing all the IOS simulator details, I will
be thnkful if you help in resolving this...

Output on appium, after clicking launch button

Launching Appium with command: '/usr/local/bin/node' lib/server/main.js
--address "127.0.0.1" --command-timeout "7200" --debug-log-spacing --log
"/tmp/appium.log" --nodeconfig "/Users/me/nodeconfig.json" --robot-address
"127.0.0.1" --robot-port "4723" --platform-version "8.1" --platform-name
"iOS" --app "/Users/Pankaj/Desktop/kashish/Simulator/iPhone6 8.1/Beez.app"
--device-name "iPhone 6" --native-instruments-lib


Launching Appium with command: '/usr/local/bin/node' lib/server/main.js
--address "127.0.0.1" --command-timeout "7200" --debug-log-spacing --log
"/tmp/appium.log" --nodeconfig "/Users/me/nodeconfig.json" --robot-address
"127.0.0.1" --robot-port "4723" --platform-version "8.1" --platform-name
"iOS" --default-device --native-instruments-lib


Launching Appium with command: '/usr/local/bin/node' lib/server/main.js
--address "127.0.0.1" --command-timeout "7200" --debug-log-spacing --log
"/tmp/appium.log" --nodeconfig "/Users/me/nodeconfig.json" --robot-address
"127.0.0.1" --robot-port "4723" --platform-version "8.0" --platform-name
"iOS" --app "/Users/Pankaj/Desktop/kashish/Simulator/iPhone6 8.1/Beez.app"
--device-name "iPhone 6" --native-instruments-lib

**Comment by felixwcf** [comment]
I can still launch it after I select Reset Preference. 

```javascript
Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --debug-log-spacing --platform-version "8.1" --platform-name "iOS" --show-ios-log --default-device

info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
```

**Comment by KashishAggarwal** [comment]
Then please help me how will i start my appium server......

**Comment by KashishAggarwal** [comment]
I am using Appium v1.4.13, felicwcf, please help you if can provide any workaround...

Br
Kashish

**Comment by KashishAggarwal** [comment]
Hi All,

I am facing issue while starting appium using command line, because mentioned above I am not able to start server using Appium GUI....



Pankajs-MacBook-Pro:bin Pankaj$ node appium
info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: Console LogLevel: debug
info: --> GET / {}
info: [debug] Responding to client that we did not find a valid resource
info: <-- GET / 404 14.168 ms - 47 




Please help!!!!!!!!!!!!!

**Comment by seleniumappiumnewbie** [comment]
@felixwcf 
When you say insert "--native-instruments-lib" do you mean copy and paste this line into the custom server flags textbox In Appium-> Developer Settings?
Are there other settings you are suppose to check in the Developer Settings?
Then you can start Appium Server via the GUI app and it will run ios Simulator tests successfully?
Does adding this line affect running real iphone tests with the Appium Server? Does it still work with the real iphone tests?
Thanks for your help.

**Comment by seleniumappiumnewbie** [comment]
Now I'm also getting this error when I run iOS simulator tests with the GUI app or starting appium server via the terminal. A new session could not be created. (Original error: Command failed: /bin/sh -c ideviceinstaller -u xxlongnumberxxx -i /var/folders/18/05xmf2y509db8_8bjsxlnfd40000gn/T/115931-1299-fhxjnk/SafariLauncher.app No iOS device found, is it plugged in? The only difference is now I just did brew update and brew install ant.

**Comment by seleniumappiumnewbie** [comment]
Finally someone kindly shared a workaround for this issue with me. This worked for me. Finally after a month of headaches. 
Go to iOS advance settings in the GUI app and check Use Native Instruments Library and check Instruments Launch Timeout and set to 900,000 ms or a number of your choice so it has enough time to load before failing. Then I was able to open a browser in iOS Simulator 9.1. You have to manually type in 9.1 in the GUI app. Hopefully this issue will be fixed soon, so we don't need to do a workaround.

**Comment by randersen** [comment]
Thanks for the workaround! Saved me a lot of time.

**Comment by deadlyfingers** [comment]
I had the same error trying to run the sample-code node scripts. I got the Appium app to run by modifying iOS Settings to use Platform Version "9.2" and checking "Use Native Instruments Library" in iOS Advanced Settings.

**Comment by jotzebee** [comment]
**The workaround provided by seleniumappiumnewbie did work for me!** Thank you seleniumappiumnewbie! 
I will tell my story to generate keywords so hopefully other people will find this fix easier than me, I had to go through more than 10 suggestions before I found this one!

I installed Appium for mobile test automation of iOS apps and all its per-requisites on Mac. Then I couldn't run Java tests and realized my configuration was nok. Appium Doctor showed all green checkmarks. 
I launched Appium and then started Inspector. I got errors that "A session could not be started" with different original errors. The one that stuck around most, said: "instruments crash on startup"
So what I did based on the workaround provided above:

1. Start Appium GUI
2. Open Developer Settings of Appium GUI
2.1 Put a tick in Enabled
2.2 Put a tick in Custom Server Flags
2.3 in the text field of Custom Server Logs put 
--native-instruments-lib 
3. Open General Settings and make sure Server Address is 0.0.0.0 and Port is 4725
4. Open iOS Settings
5. In iOS Settings, Basic tab
5.1. Add App Path, mine is /Users/temp_user/Downloads/UICatalog.app (yes, this is the popular tutorial app)
5.2. Force Device, mine is iPhone 5, Platform 9.2, if you still get errors, in the appium log available devices are listed, find them and select to force device with data from the list or find device from xcode simulators list
**6. In iOS Settings, Advanced tab
6.1 Put a tick in Use Native Instruments Library
6.2 Put a tick in Instruments Launch Timeout, add 900,000 ms**
7. Press Launch btn in Appium GUI
8. Press Inspector btn in Appium GUI
Finally the Inspector loads the app in a simulator of the forced device

**Comment by leonardosebastian** [comment]
Hi, so, all that we have from Appium is this "workaround"?

**Comment by rish7** [comment]
@jotzebee thank you, it works for me too.

[https://github.com/appium/appium/issues/5705#issuecomment-197945266](https://github.com/appium/appium/issues/5705#issuecomment-197945266)

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by lohit81** [comment]
Hi,

Please advice how settings will work on Android environment.

Thanks,
LA
