### ISSUE TITLE
SafariLauncher is not correctly installed when installing Appium 1.4.13 via npm but is correctly installed via ./reset.sh --ios --real-safari

### ISSUE THREAD

**Issue by seleniumappiumnewbie** [appium/appium#5706]
Issue: SafariLauncher is not correctly installed when installing Appium 1.4.13 via npm but is correctly installed via ./reset.sh --ios --real-safari

Getting this error:
A new session could not be created. (Original error: ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip')

Environment: Mac El Capitan, Xcode 7.0.1, Appium 1.4.13
Note: My setup passes Appium-Doctor check

Steps to Reproduce:
1. Install Appium from nam
-npm install -g appium
-npm install wd
2. Open Appium GUI App 1.4.8
Select "Developer settings" and enable it.
Select Use External NodeJS Binary to /usr/local/bin/node
Select Use External Appium Package and link to appium folder path
4. Uncheck Force Device in Appium GUI App and Set IOS 9.0 and Paste in UUID but don't check it off
5. Start Appium Server via Appium GUI App 
6. Run in terminal ./bin/ios-webkit-debug-proxy-launcher.js -c xxxuuidxxx:27753 -d
7. Run real iPhone device script from Eclipse

Actual Results:
A new session could not be created. (Original error: ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip')

Error Details:
info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)

info: Appium REST http interface listener started on 0.0.0.0:4723

info: [debug] Non-default server args: {"safari":true,"platformName":"iOS","platformVersion":"9.0","browserName":"Safari","defaultDevice":true,"showIOSLog":true,"defaultCommandTimeout":7200,"debugLogSpacing":true}

info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: <-- GET /wd/hub/status 200 9.399 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: <-- GET /wd/hub/status 200 3.793 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"Safari","platformName":"iOS","udid":"8319807bbbc1d04c9bbc0634e14d28aca946b536","deviceName":"Real iPhone 5","platformVersion":"9.0"}}

error: Failed to start an Appium session, err was: Error: ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'

info: Client User-Agent string: Apache-HttpClient/4.4.1 (Java/1.8.0_60)
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] Configuring Safari session
info: [debug] Using local .zip from command line: /usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip
info: [debug] Copying local zip to tmp dir
info: [debug] Got configuration error, not starting session
info: [debug] Cleaning up appium session
info: [debug] Error: ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'
    at Error (native)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip')","errno":-2,"code":"ENOENT","path":"/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip","origValue":"ENOENT, stat '/usr/local/lib/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'"},"sessionId":null}
info: <-- POST /wd/hub/session 500 53.754 ms - 411 

NOTE:
However if you install Appium from git clone with ./reset.sh --ios --real-safari it correctly setups up SafariLauncher. I was able to run a real iPhone device test if I installed Appium via ./reset.sh --ios --real-safari. It just doesn't work if you install Appium via npm.
Install from source
-Type git clone https://github.com/appium/appium.git
-Type in terminal to find code-signing identity: security find-identity -v -p codesigning
-Type $ ./reset.sh --ios --real-safari --code-sign 'code signing identity' --profile 'retrieved profile identity code'

**Comment by scottdixon** [comment]
Please file this issue in the https://github.com/appium/appium-dot-app project.

**Comment by seleniumappiumnewbie** [comment]
See new bug https://github.com/appium/appium-dot-app/issues/513
