### ISSUE TITLE
Multiple Device execution - Android [Parallel execution of same script]

### ISSUE THREAD

**Issue by ejkdeveloper** [appium/appium#5707]
Hi,

I am new to Appium, my need is I have a small script developed in Junit to run native application. Its works on a single device which the connected. Please suggest a way to do it.

**Comment by scottdixon** [comment]
You might find the Junit sample code helpful: https://github.com/appium/sample-code/tree/master/sample-code/examples/java/junit

**Comment by ejkdeveloper** [comment]
Will this allow parallel execution of 2 Android devices.

**Comment by scottdixon** [comment]
For multiple devices you'll need to adjust some port related flags, more info: http://appium.io/slate/en/master/#parallel-android-tests

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/AppiumAndroidParallelExecution

**Comment by saikrishna321** [comment]
@ejkdeveloper  if your running on Mac/Linux the above parallel project work ...
