### ISSUE TITLE
Installing appium failed in go CI server

### ISSUE THREAD

**Issue by thivyae** [appium/appium#5712]
appium-chromedriver@2.3.2 installation failed in installing appium in GO CI/CD.
My node version-v0.10.35
npm version-1.4.28

Added appium in my package.json file:
"dependencies": {
    "appium": "^1.3.7",
    "grunt": "^0.4.5",
    "grunt-cucumberjs": "^0.5.2",
    "grunt-mkdir": "~0.1.2",
    "wd": "^0.3.11"
  },
  "devDependencies": {
    "grunt-cli": "~0.1.13",
    "ps-node": "0.0.4"
  }
}

Below is the stack trace:::

23:42:17.636 npm WARN optional dep failed, continuing bufferutil@1.2.1
23:42:17.637 npm WARN optional dep failed, continuing bufferutil@1.2.1
23:42:20.988 
23:42:20.988 > appium-chromedriver@2.3.2 install /Users/XXXX/Library/Application Support/Go Agent/pipelines/functionalTests/node_modules/appium/node_modules/appium-chromedriver
23:42:20.988 > node install-npm.js
23:42:20.988 
23:42:22.547 npm ERR! appium-chromedriver@2.3.2 install: `node install-npm.js`
23:42:22.547 npm ERR! spawn ENOENT
23:42:22.547 npm ERR! 
23:42:22.547 npm ERR! Failed at the appium-chromedriver@2.3.2 install script.
23:42:22.547 npm ERR! This is most likely a problem with the appium-chromedriver package,
23:42:22.547 npm ERR! not with npm itself.
23:42:22.547 npm ERR! Tell the author that this fails on your system:
23:42:22.547 npm ERR!     node install-npm.js
23:42:22.547 npm ERR! You can get their info via:
23:42:22.548 npm ERR!     npm owner ls appium-chromedriver
23:42:22.548 npm ERR! There is likely additional logging output above.
23:42:22.548 
23:42:22.548 npm ERR! System Darwin 14.3.0
23:42:22.548 npm ERR! command "node" "/usr/local/bin/npm" "install"
23:42:22.548 npm ERR! cwd /Users/XXXX/Library/Application Support/Go Agent/pipelines/functionalTests
23:42:22.548 npm ERR! node -v v0.10.35
23:42:22.548 npm ERR! npm -v 1.4.28
23:42:22.548 npm ERR! syscall spawn
23:42:22.548 npm ERR! code ELIFECYCLE
23:42:22.548 npm ERR! errno ENOENT
23:42:23.493 npm ERR! Error: ENOENT, lstat '/Users/XXXX/Library/Application Support/Go Agent/pipelines/functionalTests/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/TestApp.app/TestApp.app/Frameworks/libswiftCore.dylib'
23:42:23.493 npm ERR! If you need help, you may report this *entire* log,
23:42:23.493 npm ERR! including the npm and node versions, at:
23:42:23.494 npm ERR!     <http://github.com/npm/npm/issues>
23:42:23.494 
23:42:23.494 npm ERR! System Darwin 14.3.0
23:42:23.494 npm ERR! command "node" "/usr/local/bin/npm" "install"
23:42:23.494 npm ERR! cwd /Users/XXXX/Library/Application Support/Go Agent/pipelines/functionalTests
23:42:23.494 npm ERR! node -v v0.10.35
23:42:23.495 npm ERR! npm -v 1.4.28
23:42:23.495 npm ERR! path /Users/XXXX/Library/Application Support/Go Agent/pipelines/functionalTests/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/TestApp.app/TestApp.app/Frameworks/libswiftCore.dylib
23:42:23.495 npm ERR! fstream_path /Users/XXXX/Library/Application Support/Go Agent/pipelines/functionalTests/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/TestApp.app/TestApp.app/Frameworks/libswiftCore.dylib
23:42:23.495 npm ERR! fstream_type File
23:42:23.495 npm ERR! fstream_class FileWriter
23:42:23.495 npm ERR! code ENOENT
23:42:23.495 npm ERR! errno 34
23:42:23.495 npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:287:26
23:42:23.495 npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:108:15)
23:42:24.491 npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
23:42:24.867 npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
23:42:24.867 npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
23:42:24.867 npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
23:42:24.867 npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
23:42:24.986 npm ERR! 
23:42:24.986 npm ERR! Additional logging details can be found in:
23:42:24.986 npm ERR!     /Users/XXXX/Library/Application Support/Go Agent/pipelines/functionalTests/npm-debug.log
23:42:24.986 npm ERR! not ok code 0
23:42:25.119 [go] Current job status: failed.

**Comment by scottdixon** [comment]
Please update node to 0.12

**Comment by scottdixon** [comment]
Closing issue. Let me know if upgrading doesn't resolve the issue and I'll reopen.
