### ISSUE TITLE
TypeError: Object function parseUrl(req) has no method 'original'

### ISSUE THREAD

**Issue by Jukebox97** [appium/appium#5713]
using Appium 1.4.13.1, I'm attempting to connect to an android 4.4.2 device.  The following is the code:

            DesiredCapabilities caps = new DesiredCapabilities();
            caps.SetCapability(CapabilityType.BrowserName, "Chrome");
            caps.SetCapability("platformName", "Android");
            caps.SetCapability(CapabilityType.Version, version);
            caps.SetCapability("deviceName", "0123456789ABCDEF");
            caps.SetCapability(CapabilityType.Platform, "Android");
            driver = new AndroidDriver<AppiumWebElement>(new Uri("http://127.0.0.1:4723/wd/hub"), caps);

When the last line is executed, the device appears to show a browser, but then there's a failure in the Appium window:

> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId c8f6f8528c14a33d9e4377c58cbec56a
> info: <-- POST /wd/hub/session 303 27268.051 ms - 70 
> info: <-- GET /wd/hub/session/c8f6f8528c14a33d9e4377c58cbec56a 500 3.033 ms - 483 
> TypeError: Object function parseUrl(req){
>   var parsed = req._parsedUrl
> 
>   if (fresh(req, parsed)) {
>     return parsed
>   }
> 
>   parsed = fastparse(req.url)
> 
>   if (parsed.auth && !parsed.protocol && parsed.href.indexOf('//') !== -1) {
>     // This parses pathnames, and a strange pathname like //r@e should work
>     parsed = fastparse(req.url.replace(/@/g, '%40'))
>   }
> 
>   return req._parsedUrl = parsed
> } has no method 'original'
>     at serveStatic (D:\emulation\Appium\node_modules\appium\node_modules\express\node_modules\serve-static\index.js:63:32)
>     at Layer.handle [as handle_request] (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at trim_prefix (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:302:13)
>     at D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:270:7
>     at Function.proto.process_params (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
>     at next (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
>     at favicon (D:\emulation\Appium\node_modules\appium\node_modules\serve-favicon\index.js:63:7)
>     at Layer.handle [as handle_request] (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at trim_prefix (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:302:13)
>     at D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:270:7
>     at Function.proto.process_params (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
>     at next (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
>     at logger (D:\emulation\Appium\node_modules\appium\node_modules\morgan\index.js:136:5)
>     at Layer.handle [as handle_request] (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at trim_prefix (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:302:13)
>     at D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:270:7
>     at Function.proto.process_params (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
>     at next (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
>     at b (domain.js:183:18)
>     at Domain.run (domain.js:123:23)
>     at D:\emulation\Appium\node_modules\appium\lib\server\helpers.js:326:15
>     at Layer.handle [as handle_request] (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at trim_prefix (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:302:13)
>     at D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:270:7
>     at Function.proto.process_params (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
>     at next (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
>     at expressInit (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\middleware\init.js:23:5)
>     at Layer.handle [as handle_request] (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at trim_prefix (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:302:13)
>     at D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:270:7
>     at Function.proto.process_params (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
>     at next (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
>     at query (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\middleware\query.js:28:5)
>     at Layer.handle [as handle_request] (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\layer.js:82:5)
>     at trim_prefix (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:302:13)
>     at D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:270:7
>     at Function.proto.process_params (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:321:12)
>     at next (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:261:10)
>     at Function.proto.handle (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\router\index.js:166:3)
>     at EventEmitter.app.handle (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\application.js:141:10)
>     at Server.app (D:\emulation\Appium\node_modules\appium\node_modules\express\lib\express.js:28:9)
>     at Server.<anonymous> (D:\emulation\Appium\node_modules\appium\node_modules\socket.io\node_modules\engine.io\lib\server.js:369:22)
>     at Server.<anonymous> (D:\emulation\Appium\node_modules\appium\node_modules\socket.io\lib\index.js:258:16)
>     at Server.EventEmitter.emit (events.js:98:17)
>     at HTTPParser.parser.onIncoming (http.js:2108:12)
>     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
>     at Socket.socket.ondata (http.js:1966:22)
>     at TCP.onread (net.js:527:27)

I've tried using an emulator, thinking it might be the device, but I get the same "parsedUrl" error.  I had this working with a much older Android device that I no longer have access to.  Any suggestions would be appreciated.  

Thanks in advance.

**Comment by Jukebox97** [comment]
Update: I installed the latest node.exe, and Appium gives a similar error (TypeError: parseurl.original is not a function)

**Comment by naskog** [comment]
We are experience the same issue  using Appium 1.4.13.1, and android 5.1 device

            desired_caps['platformName'] = 'Android'
            desired_caps['platformVersion'] = '5.1'
            desired_caps['browserName'] = 'Chrome'

**Comment by naskog** [comment]
Well I installed the npm package and all works fine. Seems like a problem with the windows app.

**Comment by scottdixon** [comment]
Reopen if issue persists.
