### ISSUE TITLE
appium.dmg 1.4.13 crashes instruments

### ISSUE THREAD

**Issue by scastria** [appium/appium#5720]
This might be related to El Capitan and not ios9 or xcode 7.  I have manually corrected the symlinks in the other issue I posted and was able to start the server.  When I try to launch Inspector, instruments crashes with:

Shawns-MacBook-Pro:iwd7 shawn$ /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 (8.4)" /TFS/OERM/Main/Applications/Assessments/Assessments.iOS/bin/iPhoneSimulator/Debug/Assessments.iOS.app -e UIASCRIPT "/Users/shawn/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js" -e UIARESULTSPATH /tmp/appium-instruments
dyld: could not load inserted library '/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib' because no suitable image found.  Did find:
	/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib: mmap() error 1 at address=0x104497000, size=0x00001000 segment=__TEXT in Segment::map() mapping /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/thirdparty/iwd7/InstrumentsShim.dylib

Trace/BPT trap: 5

I was able to reproduce this in a terminal window.  Is the InstrumentsShim.dylib only good for Yosemite, perhaps??

**Comment by imurchie** [comment]
Currently `Instruments-Without-Delay` does not work with iOS 9+. We are working on a fix for this.

In order to run the server without this shim, in "Developer Settings" add a "Custom Server Flag" `--native-instruments-lib` before launching the server.

**Comment by scastria** [comment]
Works great!

**Comment by igalep** [comment]
Worked for me , Thanks !!

**Comment by chaithanya-dharmadhikari** [comment]
Didn't work for me.

**Comment by skypanther** [comment]
Does not work for me either.

**Comment by imurchie** [comment]
@chaithanya-dharmadhikari @skypanther What does "not work" mean? We need more information in order to diagnose.

**Comment by skypanther** [comment]
Ignore my comment. The issue I saw with 1.4.13 might have been setup related.

**Comment by alangithubtrader** [comment]
Thanks, works for me as well. Greatly appreciate it.

**Comment by chaithanya-dharmadhikari** [comment]
@imurchie Sorry for not adding the details. I got the same error after adding "Custom Server Flag" --native-instruments-lib. The log is -

error: uncaughtException: Cannot find module 'appium-instruments' date=Thu Oct 15 2015 08:13:01 GMT-0400 (EDT), pid=5066, uid=300, gid=1, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.12.7, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --address, 127.0.0.1, --platform-version, 9.0, --platform-name, iOS, --app, sample.ipa, --udid, **UDID**, --show-ios-log, --backend-retries, 2, --default-device, --no-reset, --launch-timeout, 9000000, --native-instruments-lib], rss=76472320, heapTotal=61778432, heapUsed=26645008, loadavg=[1.40478515625, 1.37353515625, 1.39111328125], uptime=3526, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=336, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Function.Module._load, line=278, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=14, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/instruments.js, function=, line=4, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=19, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js, function=, line=15, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false], stack=[Error: Cannot find module 'appium-instruments',     at Function.Module._resolveFilename (module.js:336:15),     at Function.Module._load (module.js:278:25),     at Module.require (module.js:365:17),     at require (module.js:384:17),     at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/instruments.js:4:14),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),     at Function.Module._load (module.js:310:12),     at Module.require (module.js:365:17),     at require (module.js:384:17),     at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:15:19),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),     at Function.Module._load (module.js:310:12)]

**Comment by scastria** [comment]
This is not a crash of instruments. Your error is that it can't find the module appium-instruments. That issue is covered in a different issue with a solution provided to fix symlinks. 

https://github.com/appium/appium-dot-app/issues/512

**Comment by seleniumbheema** [comment]
Still having the same issue

d (module.js:355:32),     at Function.Module._load (module.js:310:12)]

Launching Appium with command: export Custom Server Flag="--native-instruments-lib"; '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --debug-log-spacing --platform-version "8.1" --platform-name "iOS" --show-ios-log --default-device

error: uncaughtException: Cannot find module 'appium-instruments' date=Mon Oct 26 2015 14:03:27 GMT+0000 (GMT), pid=12316, uid=502, gid=20, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.12.7, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --command-timeout, 7200, --debug-log-spacing, --platform-version, 8.1, --platform-name, iOS, --show-ios-log, --default-device], rss=76918784, heapTotal=61778432, heapUsed=26622088, loadavg=[1.35791015625, 1.76904296875, 2.208984375], uptime=255222, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=336, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Function.Module._load, line=278, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=14, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/instruments.js, function=, line=4, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=19, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js, function=, line=15, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false], stack=[Error: Cannot find module 'appium-instruments',     at Function.Module._resolveFilename (module.js:336:15),     at Function.Module._load (module.js:278:25),     at Module.require (module.js:365:17),     at require (module.js:384:17),     at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/instruments.js:4:14),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),     at Function.Module._load (module.js:310:12),     at Module.require (module.js:365:17),     at require (module.js:384:17),     at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:15:19),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),     at Function.Module._load (module.js:310:12)]

**Comment by seleniumbheema** [comment]
it not working fine, Appium server starts fine, once i run the code, it pop up with window saying instruments cannot be opened because of a problem

**Comment by Screech1337** [comment]
me too!

**Comment by mariamjaved87** [comment]
Getting
main.js: error: Unrecognized arguments: native-instruments-lib

what do I do to make it work?

**Comment by nolanlawson** [comment]
This worked beautifully for me. For the record:

If you are using Appium from the command line, run:

```
appium --native-instruments-lib
```

In Appium.app, you'll need to go to Advanced, and then tick the box that says "Use Native Instruments Library."

**Comment by totbatotammo** [comment]
In Appium.app, you'll need to go to Advanced, and then tick the box that says "Use Native Instruments Library."

This worked fine for me :)

**Comment by sivakspt** [comment]
Worked for me Thanks.

**Comment by uaka** [comment]
> in "Developer Settings" add a "Custom Server Flag" --native-instruments-lib before launching the server.

This helped me too! It took me a day to find this solution!

**Comment by tocute** [comment]
Didn't work for me.
I add add a "Custom Server Flag" --native-instruments-lib
and tick the box that says "Use Native Instruments Library."
ENV : xCode 7
APP_PATH = '../../apps/TestApp/build/release-iphonesimulator/TestApp.app'
  caps:       {
    platformName:  'iOS',
    versionNumber: '8.1',
    deviceName:    'iPhone 6',
    app:           APP_PATH,
  }

but I received :

info: Launching instruments

info: [debug] Attempting to run app on iPhone 6 (8.1)
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 (8.1)" /Users/bill_beseye/Desktop/sample-code/sample-code/apps/TestApp/build/release-iphonesimulator/TestApp.app -e UIASCRIPT "/Users/bill_beseye/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [IOS_SYSLOG_ROW ] Dec 16 12:06:01 bills-MacBook-Pro.local DTMobileIS[26693]: Could not create service named com.apple.instruments.server.services.assets

info: [IOS_SYSLOG_ROW ] Dec 16 12:06:01 bills-MacBook-Pro.local SpringBoard[26684]: [FBSystemService] Error launching io.appium.TestApp: NotFound (4)

info: [debug] [INST STDERR] 2015-12-16 12:06:01.762 instruments[26734:92479] Attempting to change event horizon while disengage
info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 4.) : Failed to launch process with bundle identifier 'io.appium.TestApp'
info: [debug] [INST STDERR] 2015-12-16 12:06:01.764 instruments[26734:92419] Attempting to change event horizon while disengage
info: [debug] [INSTSERVER] Instruments exited with code 253
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator
info: [IOS_SYSLOG_ROW ] Dec 16 12:06:01 bills-MacBook-Pro.local DTMobileIS[26693]: Could not create service named com.apple.dt.Xcode.WatchProcessControl
info: [IOS_SYSLOG_ROW ] Dec 16 12:06:01 bills-MacBook-Pro.local DTMobileIS[26693]: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn

info: [debug] Cleaning sim data files
info: node-simctl: Executing: xcrun with args: simctl erase 98FE367C-9FFD-44E5-811B-2C8CB25EF07D and timeout: 2000

info: [debug] Cleaning app data files

warn: Applications directory /Users/bill_beseye/Library/Developer/CoreSimulator/Devices/98FE367C-9FFD-44E5-811B-2C8CB25EF07D/data/Containers/Data/Application doesn't exist. Have you run this simulator before?
warn: Applications directory /Users/bill_beseye/Library/Developer/CoreSimulator/Devices/98FE367C-9FFD-44E5-811B-2C8CB25EF07D/data/Containers/Bundle/Application doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Cleaning up appium session
info: [debug] Error: Instruments crashed on startup
    at [object Object].Instruments.onInstrumentsExit (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/lib/instruments.js:440:31)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-instruments/lib/instruments.js:353:12)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Instruments crashed on startup)","origValue":"Instruments crashed on startup"},"sessionId":null}

error: Failed to start an Appium session, err was: Error: Instruments crashed on startup

**Comment by yasmeentaj1** [comment]
In Appium.app, you'll need to go to Advanced, and then tick the box that says "Use Native Instruments Library."

This worked for me !!!! - Thanks

**Comment by JESii** [comment]
None of this works for me on Appium 1.4.16. I start appium server (either CLI or GUI), run my cucumber tests, the simulator starts but never connects and eventually Instruments crashes with "Timed out waiting for device to boot"
