### ISSUE TITLE
Scroll an native view in Android

### ISSUE THREAD

**Issue by esoests** [appium/appium#5723]
I am suffering issues on flick method in TouchAction, I use it like this:
       TouchActions flick = new TouchActions(this.getDriver()).flick(onElement, 10, -1000, 10);
        flick.perform();

But the server get halt and log output is:
info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/fadce987-1584-887d-a964-2e21375e4d81/touch/flick","method":"POST","json":{"yoffset":-1000,"xoffset":10,"speed":10,"element":"26b9da29-e372-b4f4-0473-c1d76fd3d2c8"}}
info: [debug] [SELENDROID] SystemJvm 10 reports
info: [debug] [SELENDROID] SystemAnr 10 reports
info: [debug] [SELENDROID] SystemTombstone 10 reports
info: [debug] [SELENDROID] IntentService[FeatureConfigRefreshService](ApacheHTTPLog):getSBService() is false
info: [debug] [SELENDROID] IntentService[FeatureConfigRefreshService](ApacheHTTPLog):SMARTBONDING_ENABLED is false
info: [debug] [SELENDROID] IntentService[FeatureConfigRefreshService](ApacheHTTPLog):Resquest instance of HttpUriRequesttrue
info: [debug] [SELENDROID] null
info: [debug] [SELENDROID] IntentService[FeatureConfigRefreshService](ApacheHTTPLog):Inside DefaultClientConnectionOperator.openConnection()
info: [debug] [SELENDROID] IntentService[FeatureConfigRefreshService](ApacheHTTPLog):start to get IP for host mas-ext.amazon.com at time 1444799543639
info: [debug] [SELENDROID] IntentService[SelfUpdateService](ApacheHTTPLog):getSBService() is false
info: [debug] [SELENDROID] IntentService[SelfUpdateService](ApacheHTTPLog):SMARTBONDING_ENABLED is false
info: [debug] [SELENDROID] IntentService[SelfUpdateService](ApacheHTTPLog):Resquest instance of HttpUriRequesttrue
info: [debug] [SELENDROID] null
info: [debug] [SELENDROID] IntentService[SelfUpdateService](ApacheHTTPLog):Inside DefaultClientConnectionOperator.openConnection()
info: [debug] [SELENDROID] IntentService[SelfUpdateService](ApacheHTTPLog):start to get IP for host mas-ext.amazon.com at time 1444799543655
info: [debug] [SELENDROID] IntentService[BlockedAppsService](ApacheHTTPLog):getSBService() is false
info: [debug] [SELENDROID] IntentService[BlockedAppsService](ApacheHTTPLog):SMARTBONDING_ENABLED is false
info: [debug] [SELENDROID] IntentService[BlockedAppsService](ApacheHTTPLog):Resquest instance of HttpUriRequesttrue
info: [debug] [SELENDROID] null
info: [debug] [SELENDROID] IntentService[BlockedAppsService](ApacheHTTPLog):Inside DefaultClientConnectionOperator.openConnection()
info: [debug] [SELENDROID] IntentService[BlockedAppsService](ApacheHTTPLog):start to get IP for host mas-ext.amazon.com at time 1444799543670
info: [debug] [SELENDROID] IntentService[FeatureConfigRefreshService](ApacheHTTPLog):finish to get IP for host mas-ext.amazon.com at time 1444799543690, result number 1
info: [debug] [SELENDROID] IntentService[SelfUpdateService](ApacheHTTPLog):finish to get IP for host mas-ext.amazon.com at time 1444799543690, result number 1
info: [debug] [SELENDROID] IntentService[SelfUpdateService](ApacheHTTPLog):DefaultClientConnectionOperator.openConnection()InetAddress.getAllByName length:1
info: [debug] [SELENDROID] IntentService[FeatureConfigRefreshService](ApacheHTTPLog):DefaultClientConnectionOperator.openConnection()InetAddress.getAllByName length:1
info: [debug] [SELENDROID] IntentService[BlockedAppsService](ApacheHTTPLog):finish to get IP for host mas-ext.amazon.com at time 1444799543693, result number 1
info: [debug] [SELENDROID] IntentService[BlockedAppsService](ApacheHTTPLog):DefaultClientConnectionOperator.openConnection()InetAddress.getAllByName length:1
info: [debug] [SELENDROID] IntentService[FeatureConfigRefreshService](ApacheHTTPLog):DefaultClientConnectionOperator.openConnection() connsock Socket[address=/54.239.18.232,port=443,localPort=53851]
info: [debug] [SELENDROID] IntentService[BlockedAppsService](ApacheHTTPLog):DefaultClientConnectionOperator.openConnection() connsock Socket[address=/54.239.18.232,port=443,localPort=35256]
info: [debug] [SELENDROID] IntentService[SelfUpdateService](ApacheHTTPLog):DefaultClientConnectionOperator.openConnection() connsock Socket[address=/54.239.18.232,port=443,localPort=42143]

But the same method works on other elements. Any clue on why this happens?

**Comment by qaDream77** [comment]
In android, you can't click on an element that isn't visible on the screen. You have to scroll it into view first.

**Comment by SrinivasanTarget** [comment]
Its fixed in latest version.Please try a latest version of appium.

**Comment by SrinivasanTarget** [comment]
@triager please close
