### ISSUE TITLE
SafariLauncher is not installed with the Appium 1.4.13 GUI App dmg

### ISSUE THREAD

**Issue by seleniumappiumnewbie** [appium/appium#5727]
Issue: SafariLauncher is not installed with the Appium 1.4.13 GUI App dmg

A new session could not be created. (Original error: ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip')

Steps:
1. Install Appium 1.4.13 dmg 
2. Connect iPhone device
3. Run script from Eclipse to load Safari browser

Expected Results:
Appium GUI App dmg should install SafariLauncher during installation.

Actual Results:
info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)

info: Appium REST http interface listener started on 0.0.0.0:4723

info: [debug] Non-default server args: {"safari":true,"platformName":"iOS","platformVersion":"9.0","browserName":"Safari","defaultDevice":true,"showIOSLog":true,"defaultCommandTimeout":7200,"debugLogSpacing":true}
info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: <-- GET /wd/hub/status 200 12.989 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"Safari","platformName":"iOS","udid":"8319807bbbc1d04c9bbc0634e14d28aca946b536","deviceName":"Real iPhone 5","platformVersion":"9.0"}}

info: Client User-Agent string: Apache-HttpClient/4.4.1 (Java/1.8.0_60)
info: *************************************

info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************

info: [debug] Configuring Safari session

info: [debug] Using local .zip from command line: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip

info: [debug] Copying local zip to tmp dir

info: [debug] Got configuration error, not starting session

error: Failed to start an Appium session, err was: Error: ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'

info: [debug] Cleaning up appium session

info: [debug] Error: ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'
    at Error (native)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip')","errno":-2,"code":"ENOENT","path":"/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip","origValue":"ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'"},"sessionId":null}
info: <-- POST /wd/hub/session 500 42.022 ms - 498 

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: <-- GET /wd/hub/status 200 2.123 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

**Comment by scottdixon** [comment]
Duplicate https://github.com/appium/appium/issues/5706

**Comment by seleniumappiumnewbie** [comment]
See new bug https://github.com/appium/appium-dot-app/issues/513

**Comment by rkn411** [comment]
2017-01-10 15:28:30:674 - info: [debug] Error: ENOENT: no such file or directory, stat '/Applications/Appium 2.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'
    at Error (native)
2017-01-10 15:28:30:674 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: ENOENT: no such file or directory, stat '/Applications/Appium 2.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip')","errno":-2,"code":"ENOENT","syscall":"stat","path":"/Applications/Appium 2.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip","origValue":"ENOENT: no such file or directory, stat '/Applications/Appium 2.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'"},"sessionId":null}

**Comment by rkn411** [comment]
xcode 7.3
iOS-9.3.5
appium 1.4.13
