### ISSUE TITLE
Warning for update Appium 1.4.13 on Mac 

### ISSUE THREAD

**Issue by pisces202** [appium/appium#5730]
Hi!
I've just updated Appium to 1.4.13 on my Mac but always getting this warning message about the latest version is 1.4.8 not 1.4.13. What's wrong with it?

![screen shot 2015-10-16 at 1 55 46 pm](https://cloud.githubusercontent.com/assets/14870426/10535537/dae74652-740d-11e5-92fc-122a735bfb04.png)

**Comment by scottdixon** [comment]
Please raise dot-app related issues in https://github.com/appium/appium-dot-app

Others are experiencing the same: https://github.com/appium/appium-dot-app/issues/511
