### ISSUE TITLE
Appium v1.4.13 Server showing error and Conflict between latest and 1.4.8 version

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium#5732]
Hello @jlipps / @Jonahss  

Today I have downloaded Appium v1.4.13 dmg and installed on the Mac which was running with v1.4.8. After launching the latest version of App, I got a alert message as ' Your current version 1.4.13(Draco) and latest version 1.4.8(Draco). I am shocked. Actually which one is latest.

And if I launch the Appium server, it is not launched properly. Got the below error.

Launching Appium with command: '/Applications/Appium 2.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --debug-log-spacing --platform-version "8.1" --platform-name "iOS" --show-ios-log --default-device

error: uncaughtException: Cannot find module 'appium-instruments' date=Fri Oct 16 2015 16:44:17 GMT+0530 (IST), pid=49733, uid=502, gid=20, cwd=/Applications/Appium 2.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium 2.app/Contents/Resources/node/bin/node, version=v0.12.7, argv=[/Applications/Appium 2.app/Contents/Resources/node/bin/node, /Applications/Appium 2.app/Contents/Resources/node_modules/appium/lib/server/main.js, --command-timeout, 7200, --debug-log-spacing, --platform-version, 8.1, --platform-name, iOS, --show-ios-log, --default-device], rss=76382208, heapTotal=61778432, heapUsed=26825184, loadavg=[1.73779296875, 2.06982421875, 1.84326171875], uptime=886650, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=336, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Function.Module._load, line=278, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=14, file=2.app/Contents/Resources/node_modules/appium/lib/devices/ios/instruments.js, function=Object.<anonymous> (/Applications/Appium, line=4, method=<anonymous> (/Applications/Appium, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=19, file=2.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js, function=Object.<anonymous> (/Applications/Appium, line=15, method=<anonymous> (/Applications/Appium, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false], stack=[Error: Cannot find module 'appium-instruments',     at Function.Module._resolveFilename (module.js:336:15),     at Function.Module._load (module.js:278:25),     at Module.require (module.js:365:17),     at require (module.js:384:17),     at Object.<anonymous> (/Applications/Appium 2.app/Contents/Resources/node_modules/appium/lib/devices/ios/instruments.js:4:14),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),     at Function.Module._load (module.js:310:12),     at Module.require (module.js:365:17),     at require (module.js:384:17),     at Object.<anonymous> (/Applications/Appium 2.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:15:19),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),     at Function.Module._load (module.js:310:12)]

What was the problem with latest version. Actually I have to work on iOS 9 so I need to update Appium. Please help me ASAP.

**Comment by scottdixon** [comment]
Please raise dot-app related issues in https://github.com/appium/appium-dot-app

Others are experiencing the same:
https://github.com/appium/appium-dot-app/issues/511
https://github.com/appium/appium-dot-app/issues/512
