### ISSUE TITLE
Urgent Error, unable to install appium on ubuntu 64bit

### ISSUE THREAD

**Issue by qaDream77** [appium/appium#5736]
I just did a clean install of Ubuntu 14.04.3 LTS 64bit,

Step 1)
sudo apt-get install build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev

Step 2) Get Brew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"

Step 3) Add the paths
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"

Step 4)
brew update
brew install node
brew link node (if it doesn't link already)

Step 5)
npm install -g appium

Result: Full error log at: http://pastebin.com/6EzSv22E

What is going on? I never had this issue in the past. GCC, G++, MAKE are all installed. Python is 2.7.10

Any advice would be greatly appreciated!

Cheers.

**Comment by scottdixon** [comment]
I also hit this error on node 4. Try switching to node 0.12 and then `npm install -g appium`.

You might find https://github.com/creationix/nvm useful.

**Comment by qaDream77** [comment]
Thank you good sir! You have just saved me hours of looking for that needle =D

Worked like a charm, still some warnings, but the errors are gone at least.

Just to finish this up in case someone else has a similar issue.

After you install brew in step 2)

Step 2.5) this will install version control for homebrew
brew tap homebrew/versions

Step 2.5b) this will display all available versions of node
brew search node

Updated Step 4)
Step 4)
brew update
brew install node012
brew link node (if it doesn't link already)

NOTE: Might need node010, not sure yet.
