### ISSUE TITLE
Swipe or ScrollTo or TouchAction not working in iOS Simulator 8.x/9.0 with Appium 1.4.13, Xcode 7.0.1 and Java-Client 3.2.0

### ISSUE THREAD

**Issue by hnallani** [appium/appium#5738]
Tried various ways and no luck
Page view is "Scrollview"

ScrollTo is working in "TableView" (At least not throwing an error) for the same configuration of Appium 1.4.13, Xcode 7.0.1, iOS 8.x/9.0 and Java-Client 3.2.0.

I saw other threads that Apple is not fixing scroll issues in iOS simulator but someone posted some solutions which are not working for the page is having Scrollview.

Please suggest if someone got a fix for this.

**Comment by scottdixon** [comment]
Have you tried https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md#bugs-and-workarounds

**Comment by hnallani** [comment]
Thanks Scottdixon. I tried all the solutions earlier but I missed something. It is working now with following solution which is specified in the docs.

JavascriptExecutor js = (JavascriptExecutor) iosDriver; 
HashMap scrollObject = new HashMap(); 
scrollObject.put("element", ((RemoteWebElement) iosDriver.findElement(By.name("elementName"))).getId());
js.executeScript("mobile: scroll", scrollObject);
