### ISSUE TITLE
Extremely slow appium tests since recent updates

### ISSUE THREAD

**Issue by keaneal** [appium/appium#5740]
Appium.app 1.4.13
Mac OSX 10.10.5 Yosemite
Xcode 7.0
iOS Simulator 9.1

We've had this problem for a couple of months now and it is getting to the point where we might have to stop using appium. I'm not sure if it was the update to yosemite, ios 9 or appium 1.4 but somewhere along the line performance just fell off a cliff. Before tests that took 10 minutes are now taking up to an hour. There doesn't seem to be any one reason, just a general slowness in all appium actions. 

I've seen a few other issues describing slowness but they don't seem directly related to ours. https://github.com/appium/appium/issues/4397 The user in this issue claims it was resolved by turning off log debugging but we don't have that enabled? 

We run our tests using Cucumber if thats relevant? I am happy to provide any more details. We really need to get this resolved as our entire regression test suite for our mobile app is now creeping up to 24 hours!

**Comment by scottdixon** [comment]
`instruments-without-delay` doesn't support Xcode 7. This could be the issue you're seeing. @moizjv is working on a solution.

**Comment by keaneal** [comment]
Yes our update to Xcode 7 would certainly coincide with the performance drop off. Is there any workarounds available and/or an open issue so I can monitor progress on a solution?

**Comment by vinceis1337** [comment]
Is everyone aware that Facebook has replied and basically said the repo is orphaned?

https://github.com/facebook/instruments-without-delay/pull/18

Someone already has a fix for instruments-without-delay but the repo needs to be forked and maintained by someone else.

**Comment by moizjv** [comment]
https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/iwd_xcode7.md

**Comment by moizjv** [comment]
let us know if that fixes the issue

**Comment by djwgit** [comment]
hi, @moizjv 
I have xcode 711, ios simulator 9.1, appium 1.4.15
executed the script,  the keys/dict injected into com.apple.instruments.deviceservice.plist
but iwd not working for instruments...

info: [debug] Attempting to run app on iPhone 6 (9.1) [
info: On xcode 7.0, instruments-without-delay does not work, skippinginstruments-without-delay

DTMobileISShim.dylib under appium iwd7 is dated Sep25, should I switch back to xcode 7 ?
thanks

**Comment by ywang24** [comment]
Hi Moizjv, thank you for helping on this issue,I saw the same issue as djwgit:

info: [debug] Instruments is at: /Applications/Xcode7.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on iPhone 6 (9.1) [
info: [debug] Attempting to run app with process arguments: 1278
info: On xcode 7.0, instruments-without-delay does not work, skippinginstruments-without-delay

**Comment by ywang24** [comment]
my problem is gone... need to add sudo when execute the command.

**Comment by djwgit** [comment]
@ywang24 could you share more how what you did, 
 I have appium 1.4.16, xcode7.2, simulator 9.0,  updated node modules, 
 tried start server using appium, or node.
I don't think sudo does the trick, on my machine, I could see the script inserted into the plist file.  but in appium server console, it still says  instruments-without-delay does not work, skippinginstruments-without-delay ... :-(

**Comment by djwgit** [comment]
need to make sure using 9.2 simulator, not clear in the doc.

**Comment by keaneal** [comment]
I'm only getting around to trying this out now, is there any way to confirm it is definitely working? Also does the simulator have to be 9.2, is 9.0 okay?

**Comment by moizjv** [comment]
@keaneal it should work for iOS > 9 and xcode > 7

**Comment by KBhatti** [comment]
is this supposed to work now? I am not sure if my instruments-without-delay is working by default or if I need to put in extra commands to make it work. I am using xcode 7.3, Appium 1.5.0. When I launch appium from the command line and attempt to run my maven test Project (whether on Simulator or real device) here is what I see
[debug] [Instruments] Attempting to launch instruments, this is try #1
[Instruments] Launching instruments
[debug] [Instruments] Attempting to run app on iPhone 6s Plus (9.3) [
[Instruments] On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7

Does this mean that my IWD is getting launched automatically every time I run a test (on Simulator or real device). Or is it not running ?

Thanks.

**Comment by imurchie** [comment]
You'll need to run the command linked to above for each xcode, I think. The logs, unfortunately, will still say that it doesn't work.

**Comment by KBhatti** [comment]
well the thing is that if you look at the logs this line doesn't it mean that the IWD is working?
[Instruments] On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7


I am assuming that for me its working by defaul? Or is it no ?
