### ISSUE TITLE
How to validate the alert messages that are displayed for a short period and then disappear.

### ISSUE THREAD

**Issue by User423** [appium/appium#5744]
I was unable to get the alert messages like "Profile data updated successfully" like messages that will appear for short period. Even I was unable to detect those messages using UI automator. Can anyone please help me on this.

**Comment by scottdixon** [comment]
Are you referring to http://developer.android.com/guide/topics/ui/notifiers/toasts.html ?

**Comment by User423** [comment]
Yes, Could you please tell me how to identify and validate these messages using Appium.

**Comment by saikrishna321** [comment]
@User423 #4824

**Comment by igalep** [comment]
try to use : 
WebDriverWait wait.until(ExpectedConditions.visibilityOfElementLocated(By.....);
