### ISSUE TITLE
Appium fails to launch from Mac app and command line using 1.4.13

### ISSUE THREAD

**Issue by jamescaldwell** [appium/appium#5753]
Everytime I click the Launch button I get the following error.  Running it from the command line does the same thing.

error: uncaughtException: Cannot find module 'appium-instruments' date=Wed Oct 21 2015 19:57:01 GMT-0500 (CDT), pid=19891, uid=501, gid=20, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.12.7, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --address, 127.0.0.1, --command-timeout, 7200, --debug-log-spacing, --platform-version, 8.4, --platform-name, iOS, --show-ios-log, --show-ios-log, --default-device], rss=77332480, heapTotal=61778432, heapUsed=26192072, loadavg=[1.734375, 1.92529296875, 2.0458984375], uptime=172761, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=336, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Function.Module._load, line=278, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=14, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/instruments.js, function=, line=4, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=19, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js, function=, line=15, method=null, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false], stack=[Error: Cannot find module 'appium-instruments',     at Function.Module._resolveFilename (module.js:336:15),     at Function.Module._load (module.js:278:25),     at Module.require (module.js:365:17),     at require (module.js:384:17),     at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/instruments.js:4:14),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),     at Function.Module._load (module.js:310:12),     at Module.require (module.js:365:17),     at require (module.js:384:17),     at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:15:19),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),     at Function.Module._load (module.js:310:12)]

**Comment by scottdixon** [comment]
A number of GUI users are hitting this error - some solutions are discussed here: appium/appium-dot-app#510

**Comment by SrinivasanTarget** [comment]
@triager please close
