### ISSUE TITLE
Could it be possible to make unlock.apk manages unlocking with also password ?

### ISSUE THREAD

**Issue by Fanch-** [appium/appium#5755]
Related to https://discuss.appium.io/t/appium-1-2-2-unable-to-unlock-the-screen-in-htc-one/198/8

> But got it in the box of unlock.apk will be much better
> - maxski

When manually installing an ssl certificate (self-signed certificate for **preprod purpose**, a pattern is needed -PIN, password, ...- asked when unlocking screen)  https://support.google.com/nexus/answer/2844832 And Disable Keyguard, use the flags to dismiss it doesn't allow us to pilot app with credential.

It could be great to have a capability to automatically manage the unlocking of screen with password (android). Server arg maybe?

That way we could use : 

``` java
capabilities.setCapability("unlockScreenPassword", "*****");
```

``` shell
adb -s $udid shell input text "password" && adb -s $udid shell input keyevent 66
```
- `adb -s $udid shell input keyevent 26` before if needed

What do you think ?

**Edit :** It seems harder than I thought, for HTC a gesture is necessary to display password window, but we can bypass this overlay by desactivating "locking screen" (go directly to security screen), I don't know if it is possible to do that using adb (I guess yes or directly starting the intent and ignore what I have written next) and if it is adequate for the owner of the phone -to modify his parameter options- .... though it looks like enable/disable wifi/airplane mode, etc ...

``` shell
#!/bin/bash
tmp="$(adb -s $udid shell dumpsys power | grep 'mScreenOn=\|state' | grep -oE '(true|false|ON|OFF)')"
if [ "$tmp" == 'false' ] || [ "$tmp" == 'OFF' ]; then
    echo "Screen is off. Turning on."
    adb -s $udid shell input keyevent 26 && adb -s $udid shell input text Certif && adb -s $udid shell input keyevent 66
    echo "OK, should be on now."
else
    echo "Screen is already on."
fi
```

A touchscreen swipe is also possible.

**Comment by scottdixon** [comment]
CC @imurchie
