### ISSUE TITLE
Appium inspector has stopped loading

### ISSUE THREAD

**Issue by SameenJavid** [appium/appium#5757]
Hi, 
I created a login script for my application using Appium 1.4.13 in java. I was able to launch appium inspector in very first run and recored steps successfully. After a playback i tried editing my script and appium inspector has stopped launching, Sometimes it does launch but no scree\controls show up for the application. 

Below are the detailed logs from appium 
2m[INST] 2015-10-22 11:23:03 +0000 Debug: Running system command #11: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"SpringBoard","label":" ","value":null,"dom":nul...
info: [debug] Socket data received (8144 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"SpringBoard","label":" ","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":0,"width":1024.0000335703464,"height":768.0000447604625},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"do
info: [debug] Condition unmet after 10598ms. Timing out.
info: [debug] Cleaning up appium session
info: [debug] Error: App did not have elements
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:483:30
    at Object.cb [as callback] (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-controller.js:261:7)
    at next (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:798:43)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:32:16
    at [object Object].exports.respond (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/common.js:28:9)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1498:18)
    at getResultAndSendNext (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/lib/command-proxy.js:146:20)
    at Socket.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/lib/command-proxy.js:88:7)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: App did not have elements)","origValue":"App did not have elements"},"sessionId":null}
info: <-- POST /wd/hub/session 500 44593.396 ms - 172 
info: [IOS_SYSLOG_ROW ] Oct 22 16:23:04 nerldap lsd[1154]: LaunchServices: Currently 0 installed placeholders: (
info: [IOS_SYSLOG_ROW ] )

info: [IOS_SYSLOG_ROW ] Oct 22 16:23:22 nerldap mstreamd[1100]: (Note ) PS: Media stream daemon stopping.

info: [IOS_SYSLOG_ROW ] Oct 22 16:23:22 nerldap mstreamd[1100]: (Note ) AS: <MSIOSAlbumSharingDaemon: 0x7fefc2514910>: Shared Streams daemon has shut down.
info: [IOS_SYSLOG_ROW ] Oct 22 16:23:22 nerldap mstreamd[1100]: (Warn ) mstreamd: mstreamd shutting down.

info: [IOS_SYSLOG_ROW ] Oct 22 16:23:26 nerldap ids_simd[1102]: (Error) IDSSimulatorSupport: <IDSSimSupportLocalServer.m __68-[IDSSimSupportLocalServer setNetworkSimulation:enabled:completion:]_block_invoke:544> message send of data {
info: [IOS_SYSLOG_ROW ] ControlCmd = SetNetSimulationEnabledCmd;

info: [IOS_SYSLOG_ROW ] Enabled = 0;
info: [IOS_SYSLOG_ROW ] ServiceName = "com.apple.private.alloy.sockpuppet.classd";
info: [IOS_SYSLOG_ROW ] } failed with error Error Domain=com.apple.idssimualtorsupport.errors Code=2 "(null)" UserInfo={NSUnderlyingError=0x7f9fa2d07470 {Error Domain=NSMachErrorDomain Code=268435459 "(ipc/send) invalid destination port"}}
info: [IOS_SYSLOG_ROW ] Oct 22 16:23:26 nerldap companionappd[1108]: (Error) WatchKit: <SPTransport.m __67-[SPTransport service:account:identifier:didSendWithSuccess:error:]_block_invoke:415> __67-[SPTransport service:account:identifier:didSendWithSuccess:error:]_block_invoke identifier (FD920ABE-211B-475F-87B2-5CD6BE737627), serviceName ((null)), success: 0 error, domain: com.apple.identityservices.error, code: 23
info: [IOS_SYSLOG_ROW ] Oct 22 16:23:26 nerldap companionappd[1108]: (Error) WatchKit: <SPCompanionAppServer.m __75-[SPCompanionAppServer sendProtobuf:sender:timeOut:allowInsecureTransport:]_block_invoke:894> sendProtobuf failed, error : Error Domain=com.apple.identityservices.error Code=23 "Timed out" UserInfo={NSLocalizedDescription=Timed out, NSUnderlyingError=0x7fe561e02550 {Error Domain=com.apple.ids.idssenderrordomain Code=12 "(null)"}}
info: [IOS_SYSLOG_ROW ] Oct 22 16:23:26 nerldap companionappd[1108]: (Error) WatchKit: <SPTransport.m __67-[SPTransport service:account:identifier:didSendWithSuccess:error:]_block_invoke:415> __67-[SPTransport service:account:identifier:didSendWithSuccess:error:]_block_invoke identifier (BE6E7BA1-3E0A-49FD-9D36-AE4C1751C1B2), serviceName ((null)), success: 0 error, domain: com.apple.identityservices.error, code: 23
info: [IOS_SYSLOG_ROW ] Oct 22 16:23:26 nerldap companionappd[1108]: (Error) WatchKit: <SPCompanionAppServer.m __75-[SPCompanionAppServer sendProtobuf:sender:timeOut:allowInsecureTransport:]_block_invoke:894> sendProtobuf failed, error : Error Domain=com.apple.identityservices.error Code=23 "Timed out" UserInfo={NSLocalizedDescription=Timed out, NSUnderlyingError=0x7fe561d20b60 {Error Domain=com.apple.ids.idssenderrordomain Code=12 "(null)"}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: <-- GET /wd/hub/status 200 1.546 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: [IOS_SYSLOG_ROW ] Oct 22 16:23:36 nerldap sharingd[1158]: 16:23:36.013 : Failed to send SDURLSessionProxy startup message, error Error Domain=com.apple.identityservices.error Code=23 "Timed out" UserInfo={NSLocalizedDescription=Timed out, NSUnderlyingError=0x7ffd83716330 {Error Domain=com.apple.ids.idssenderrordomain Code=12 "(null)"}}

Following is the exception from eclipse
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: App did not have elements) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 44.81 seconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'nerldap.lahore.techlogix.com', ip: '172.20.3.218', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:247)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:156)
	at tesssss.LoginxiQ.main(LoginxiQ.java:29)

Please help.

**Comment by scottdixon** [comment]
Please post dot-app related issues here: https://github.com/appium/appium-dot-app

**Comment by SrinivasanTarget** [comment]
I see many issues related to this already in https://github.com/appium/appium-dot-app/issues.Hence closing this here.

**Comment by SrinivasanTarget** [comment]
@triager please close
