### ISSUE TITLE
Set chromedriver version into reset.sh

### ISSUE THREAD

**Issue by shadeimi** [appium/appium#5758]

**Comment by shadeimi** [comment]
Hi All, 
./reset.sh --android --chromedriver-version 2.20 --verbose on appium v1.4.8 doesn't download the version requested.

**Comment by scottdixon** [comment]
You can now set the version like so:
```npm install appium-chromedriver --chromedriver_version="2.20"```

More info: https://github.com/appium/appium-chromedriver

Setting the ChromeDriver version via reset.sh was removed here: https://github.com/appium/appium/commit/42afa652e14b3e79d25e92e642c45b03f7479506
