### ISSUE TITLE
I Cannot start server in 1.4.13 Appium app in mac OS X (10.11)

### ISSUE THREAD

**Issue by kbalakumar99** [appium/appium#5759]
This is the error I got.

error: uncaughtException: Cannot find module 'appium-instruments' date=Thu Oct 22 2015 20:01:24 GMT+0530 (IST), pid=3594, uid=1884161367, gid=884470207, cwd=/Applications/Appium 2.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium 2.app/Contents/Resources/node/bin/node, version=v0.12.7, argv=[/Applications/Appium 2.app/Contents/Resources/node/bin/node, /Applications/Appium 2.app/Contents/Resources/node_modules/appium/lib/server/main.js, --address, 127.0.0.1, --command-timeout, 7200, --debug-log-spacing, --platform-version, 9.0.2, --platform-name, iOS, --app, /Users/bala-2082/Test/files to test/ios/Debug-iphonesimulator/Zoho Creator.app, --udid, 24b76c93fb78749b145b71e32f65fcda9206b180, --device-name, iPhone 6 Plus], rss=76455936, heapTotal=61778432, heapUsed=26760992, loadavg=[1.53173828125, 1.92919921875, 1.79345703125], uptime=11830, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=336, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Function.Module._load, line=278, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=14, file=2.app/Contents/Resources/node_modules/appium/lib/devices/ios/instruments.js, function=Object.<anonymous> (/Applications/Appium, line=4, method=<anonymous> (/Applications/Appium, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=365, method=require, native=false, column=17, file=module.js, function=require, line=384, method=null, native=false, column=19, file=2.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js, function=Object.<anonymous> (/Applications/Appium, line=15, method=<anonymous> (/Applications/Appium, native=false, column=26, file=module.js, function=Module._compile, line=460, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=478, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=355, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=310, method=Module._load, native=false], stack=[Error: Cannot find module 'appium-instruments',     at Function.Module._resolveFilename (module.js:336:15),     at Function.Module._load (module.js:278:25),     at Module.require (module.js:365:17),     at require (module.js:384:17),     at Object.<anonymous> (/Applications/Appium 2.app/Contents/Resources/node_modules/appium/lib/devices/ios/instruments.js:4:14),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),     at Function.Module._load (module.js:310:12),     at Module.require (module.js:365:17),     at require (module.js:384:17),     at Object.<anonymous> (/Applications/Appium 2.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:15:19),     at Module._compile (module.js:460:26),     at Object.Module._extensions..js (module.js:478:10),     at Module.load (module.js:355:32),     at Function.Module._load (module.js:310:12)]

**Comment by scottdixon** [comment]
A number of GUI users are hitting this error - some solutions are discussed here: https://github.com/appium/appium-dot-app/issues/510
