### ISSUE TITLE
Unable to locate element on iOS 9.0.2

### ISSUE THREAD

**Issue by shivani26** [appium/appium#5760]
![screen shot 2015-10-22 at 10 50 31 pm](https://cloud.githubusercontent.com/assets/9482801/10672781/bebb6eb6-790f-11e5-86d1-485d4fa8bd0f.png)

Environment:
Appium v1.4.11
Xcode 7.0

**Comment by scottdixon** [comment]
Please provide Appium server logs.

**Comment by shivani26** [comment]
Tried locating this partucular element
MobileElement me = (MobileElement) driver.findElement(By.xpath("//UIAStaticText[text()='Verify your mobile number']"));	

info: [debug] [INST] 2015-10-22 17:56:24 +0000 Debug: Running system command #35: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"SpringBoard","label":" ","value":null,"dom":nul...
info: [debug] Socket data received (8035 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"SpringBoard","label":" ","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":0,"width":320,"height":480},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid
info: [debug] Condition unmet after 61301ms. Timing out.
info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters."},"sessionId":"ae6c6adc-210f-4e05-9fac-7eea17fd4f2f"}
info: <-- POST /wd/hub/session/ae6c6adc-210f-4e05-9fac-7eea17fd4f2f/element 500 61302.024 ms - 164 
info: --> DELETE /wd/hub/session/ae6c6adc-210f-4e05-9fac-7eea17fd4f2f {}
info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments
info: [debug] [INST] 2015-10-22 17:57:55 +0000 Stopped: Script was stopped by the user
info: [debug] [INST STDERR] 2015-10-22 23:27:55.523 instruments[9473:1734230] Attempting to change event horizon while disengage
info: [debug] [INST] Instruments Trace Complete (Duration : 76.026451s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator
info: [debug] Killing any other simulator daemons
info: [debug] On a real device; cannot clean device state
info: [debug] Cleaning up appium session
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"ae6c6adc-210f-4e05-9fac-7eea17fd4f2f"}
info: <-- DELETE /wd/hub/session/ae6c6adc-210f-4e05-9fac-7eea17fd4f2f 200 2106.551 ms - 76 {"status":0,"value":null,"sessionId":"ae6c6adc-210f-4e05-9fac-7eea17fd4f2f"}
