### ISSUE TITLE
Deleting Android session shutsdown VM, but doesn't kill emulator

### ISSUE THREAD

**Issue by LesterTheTester** [appium/appium#5762]
I'm using quit_driver in appium_lib to quit the session.  Appium receives the command:

```
info: --> DELETE /wd/hub/session/cd7e58fd-c8a6-4d3d-99ee-c2d1ce24dcbb {}
info: Shutting down appium session
info: [debug] Pressing the HOME button
info: [debug] executing cmd: /opt/android-sdk-linux/platform-tools/adb -s emulator-5554 shell "input keyevent 3"
info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 98.538
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] UiAutomator shut down normally
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"cd7e58fd-c8a6-4d3d-99ee-c2d1ce24dcbb"}
info: <-- DELETE /wd/hub/session/cd7e58fd-c8a6-4d3d-99ee-c2d1ce24dcbb 200 665.849 ms - 76 {"status":0,"value":null,"sessionId":"cd7e58fd-c8a6-4d3d-99ee-c2d1ce24dcbb"}
```

This is a problem because the next test in the sequential suite gets handed the already-shutdown emulator.  Appium only launches a new emulator if I kill the emulator session for it. The only way I've found to work around this in automation is to issue "adb emu kill" manually after quitting the driver, which seems hacky.  Shouldn't appium be handling this as part of quitting the session?

I've also noticed that the other closing functions close_app, etc. cause the emulator to shut down.  This also doesn't make sense, shouldn't it close the app without shutting down the OS?

**Comment by LesterTheTester** [comment]
Bump. Needs Triage Anyone having similar issues on Linux?

**Comment by vmarinel** [comment]
Did you ever get a resolution to this?

**Comment by imurchie** [comment]
I'm not sure I understand what is going on. The shutdown command ought only be affecting the bootstrap code, which is running the UI Automator instance. It should not do anything adverse to the device itself.

Is this not the case? If so, we need more information in order to diagnose and fix. Full logs, info of the running environment.

**Comment by dpgraham** [comment]
I'm closing this for now. If this issue comes up again for anyone please leave a comment with logs and environment info and we'll re-open.
