### ISSUE TITLE
unzip threw error :stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by nogae** [appium/appium#5765]
Hi,

I get "unzip threw error :stdout maxBuffer exceeded", I am using Appium .v1.4.8 .
maxBuffer is indeed 524288, as it should be (commit d9c8522 took care of that) . How can I fix it?

Here are my logs:

2015-10-26 13:20:52:883 - info: *************************************
2015-10-26 13:20:52:884 - info: *************************************
2015-10-26 13:20:52:884 - info: *************************************
2015-10-26 13:20:52:884 - info: *************************************
2015-10-26 13:20:52:884 - info: *************************************
2015-10-26 13:20:52:884 - info: *************************************
2015-10-26 13:20:52:885 - info: *************************************
2015-10-26 13:20:52:885 - info: *************************************
2015-10-26 13:20:52:886 - info: **** NEW SESSION ***
2015-10-26 13:20:52:886 - info: **** NEW SESSION ***
2015-10-26 13:20:52:886 - info: **** NEW SESSION ***
2015-10-26 13:20:52:887 - info: **** NEW SESSION ***
2015-10-26 13:20:52:887 - info: **** NEW SESSION ***
2015-10-26 13:20:52:887 - info: **** NEW SESSION ***
2015-10-26 13:20:52:887 - info: **** NEW SESSION ***
2015-10-26 13:20:52:887 - info: **** NEW SESSION ***
2015-10-26 13:20:52:887 - info: *************************************
2015-10-26 13:20:52:888 - info: *************************************
2015-10-26 13:20:52:888 - info: *************************************
2015-10-26 13:20:52:888 - info: *************************************
2015-10-26 13:20:52:888 - info: *************************************
2015-10-26 13:20:52:889 - info: *************************************
2015-10-26 13:20:52:889 - info: *************************************
2015-10-26 13:20:52:889 - info: *************************************
2015-10-26 13:20:52:900 - info: [debug] Using local .ipa from command line: /Users/admin/Documents/new ipa/CPiPhoneSSLVPN (Debug).ipa
2015-10-26 13:20:52:901 - info: [debug] Copying local zip to tmp dir
2015-10-26 13:20:53:861 - info: [debug] /Users/admin/Documents/new ipa/CPiPhoneSSLVPN (Debug).ipa copied to /var/folders/6f/tkpm4tq96pgdvl5_1bp72btr0000gn/T/115926-3207-sjzgv3/appium-app.zip
2015-10-26 13:20:54:095 - info: [debug] Unzipping /var/folders/6f/tkpm4tq96pgdvl5_1bp72btr0000gn/T/115926-3207-sjzgv3/appium-app.zip
2015-10-26 13:20:54:096 - info: [debug] Testing zip archive: /var/folders/6f/tkpm4tq96pgdvl5_1bp72btr0000gn/T/115926-3207-sjzgv3/appium-app.zip
2015-10-26 13:20:54:999 - info: [debug] Zip archive tested clean
2015-10-26 13:20:57:148 - error: Unzip threw error Error: stdout maxBuffer exceeded.
2015-10-26 13:21:23:705 - error: Stderr: Archive: /var/folders/6f/tkpm4tq96pgdvl5_1bp72btr0000gn/T/115926-3207-sjzgv3/appium-app.zip
creating: Payload/
creating: Payload/CPiPhoneSSLVPN.app/
inflating: Payload/CPiPhoneSSLVPN.app/_BMCalendarMonthMeetingCell.nib

inflating: Payload/CPiPhoneSSLVPN.app/_BMCalendarPadMonthTitleView.nib

creating: Payload/CPiPhoneSSLVPN.app/_CodeSignature/
inflating: Payload/CPiPhoneSSLVPN.app/_CodeSignature/CodeResources

inflating: Payload/CPiPhoneSSLVPN.app/About-iPad.nib

inflating: Payload/CPiPhoneSSLVPN.app/about.html

inflating: Payload/CPiPhoneSSLVPN.app/About.nib

inflating: Payload/CPiPhoneSSLVPN.app/ActiveSyncErrorPage-iPad.nib

inflating: Payload/CPiPhoneSSLVPN.app/ActiveSyncErrorPage.nib

creating: Payload/CPiPhoneSSLVPN.app/AddReasonForMeetingViewController~ipad.nib/
inflating: Payload/CPiPhoneSSLVPN.app/AddReasonForMeetingViewController~ipad.nib/objects-8.0+.nib

inflating: Payload/CPiPhoneSSLVPN.app/AddReasonForMeetingViewController~ipad.nib/runtime.nib

creating: Payload/CPiPhoneSSLVPN.app/AddReasonForMeetingViewController~iphone.nib/
inflating: Payload/CPiPhoneSSLVPN.app/AddReasonForMeetingViewController~iphone.nib/objects-8.0+.nib

inflating: Payload/CPiPhoneSSLVPN.app/AddReasonForMeetingViewController~iphone.nib/runtime.nib

inflating: Payload/CPiPhoneSSLVPN.app/alarm.caf

inflating: Payload/CPiPhoneSSLVPN.app/all-detail.xml

inflating: Payload/CPiPhoneSSLVPN.app/all-sub.xml

inflating: Payload/CPiPhoneSSLVPN.app/all.xml

inflating: Payload/CPiPhoneSSLVPN.app/AnimatedProgressBar.gif

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon29x29.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon29x29@2x.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon29x29@2x~ipad.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon29x29@3x.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon29x29~ipad.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon40x40@2x.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon40x40@2x~ipad.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon40x40@3x.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon40x40~ipad.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon50x50@2x~ipad.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon50x50~ipad.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon57x57.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon57x57@2x.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon60x60@2x.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon60x60@3x.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon72x72@2x~ipad.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon72x72~ipad.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon76x76@2x~ipad.png

inflating: Payload/CPiPhoneSSLVPN.app/AppIcon76x76~ipad.png

inflating: Payload/CPiPhoneSSLVPN.app/archived-expanded-entitlements.xcent

inflating: Payload/CPiPhoneSSLVPN.app/Assets.car

inflating: Payload/CPiPhoneSSLVPN.app/aurora.caf

inflating: Payload/CPiPhoneSSLVPN.app/AuthMethodsController-iPad.nib

inflating: Payload/CPiPhoneSSLVPN.app/AuthMethodsController.nib

inflating: Payload/CPiPhoneSSLVPN.app/bamboo.caf

inflating: Payload/CPiPhoneSSLVPN.app/BannerAlertView.nib

creating: Payload/CPiPhoneSSLVPN.app/Base.lproj/
creating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMCalendarViewStoryboard.storyboardc/
inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMCalendarViewStoryboard.storyboardc/__BMCalendarView0.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMCalendarViewStoryboard.storyboardc/__BMCalendarView1.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMCalendarViewStoryboard.storyboardc/_calendarDayViewController.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMCalendarViewStoryboard.storyboardc/gue-dd-0Hr-view-7cl-vA-MJV.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMCalendarViewStoryboard.storyboardc/Info.plist

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMCalendarViewStoryboard.storyboardc/QTB-Gf-dhq-view-cUy-tW-SRU.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMCalendarViewStoryboard.storyboardc/UIViewController-QTB-Gf-dhq.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMCalendarViewStoryboard.storyboardc/ujx-bB-71k-view-kxU-UV-3X6.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMCalendarViewStoryboard.storyboardc/Z8l-A4-Hkj-view-mHo-Rr-RSD.nib

creating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMailBackgroundSync.storyboardc/
inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMailBackgroundSync.storyboardc/Info.plist

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMailBackgroundSync.storyboardc/PcO-Ik-qNj-view-tuZ-ia-S9D.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMailBackgroundSync.storyboardc/UIViewController-PcO-Ik-qNj.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMailHeaderCell.nib

creating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMailSharingViewController.storyboardc/
inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMailSharingViewController.storyboardc/Info.plist

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMailSharingViewController.storyboardc/owW-2F-GMm-view-gnw-m6-BS4.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMailSharingViewController.storyboardc/UIViewController-owW-2F-GMm.nib

creating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMeetingEditStoryboard.storyboardc/
inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMeetingEditStoryboard.storyboardc/BMMeetingEditStoryboardIdentifier.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMeetingEditStoryboard.storyboardc/c9C-lN-PQC-view-xp2-qs-lDL.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMeetingEditStoryboard.storyboardc/e77-Xe-Sdg-view-iUv-gx-ggu.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMeetingEditStoryboard.storyboardc/hcp-Pr-cOi-view-CQn-bf-hiL.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMeetingEditStoryboard.storyboardc/Info.plist

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMeetingEditStoryboard.storyboardc/t1K-J4-Rrx-view-Zkh-KL-Sqi.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMeetingEditStoryboard.storyboardc/tvM-c5-s9k-view-Zra-qP-M8Q.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMeetingEditStoryboard.storyboardc/UIViewController-aBg-91-SDp.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMeetingEditStoryboard.storyboardc/UIViewController-c9C-lN-PQC.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMeetingEditStoryboard.storyboardc/UIViewController-hcp-Pr-cOi.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMeetingEditStoryboard.storyboardc/UIViewController-tvM-c5-s9k.nib

inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMMeetingViewController.nib

creating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMNotesViewStoryboard.storyboardc/
inflating: Payload/CPiPhoneSSLVPN.app/Base.lproj/BMNotesViewStoryboard.storyboardc/Czd-aa-IG1-view-S3r-FO-Mod.nib

**Comment by scottdixon** [comment]
Have you tried increasing the buffer in linked commit as well as https://github.com/appium/appium/blob/88e67ce987d78ce44de252219e07dc176a3511c2/lib/helpers.js#L98 ?

**Comment by nogae** [comment]
Hi, first thanks for your help ;)   No, I haven't changed the helpers.js file.  Do I change it and run Appium again? Is it enough?

**Comment by scottdixon** [comment]
I'd be interested to know if this resolves your issue. Try increasing by 50%.

**Comment by nogae** [comment]
Hi,

Still not working. increased the maxBuffer by 50% and  100% both files...

any ideas?

thanks :)

**Comment by scottdixon** [comment]
Any progress on this @nogae? Try Appium 1.5 `npm install -g appium` 

Reopen if the issue persists.
