### ISSUE TITLE
Which appium version supports IOS simulator 9.0 and IOS realDevice 8.1

### ISSUE THREAD

**Issue by seleniumbheema** [appium/appium#5767]
for me Appium.app Version 1.3.4 working fine for IOS 8.1.1 realdevice and getting issues with IOS simulator 9.0

Appium Version 1.4.13 in terminal is working fine with iOS 9.0 simulator but not for iOS 8.1.1

**Comment by scottdixon** [comment]
iOS 9.0 support was introduced in 1.4.10.

What issue are you facing with iOS 8.1.1?

**Comment by seleniumbheema** [comment]
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Could not find a device to launch. You requested 'iPhone6 Test (8.1.1)', but the available devices were: ["iPad 2 (9.0) [C09E4483-8058-4E09-9169-217F399E09D6]","iPad Air (9.0) [4CC8789B-1C19-4D72-AD05-D2A7F829FDFE]","iPad Air 2 (9.0) [5E408179-4721-453D-ACC2-CEB7407FCEEE]","iPad Retina (9.0) [CC2641E7-736F-4FCE-91A4-DF4C0A7DED2C]","iPhone 4s (9.0) [148EFC50-C717-4976-A843-0010AF0B1CAF]","iPhone 5 (9.0) [446099DC-223E-4608-914A-DBC0380042E8]","iPhone 5s (9.0) [6B92D76F-37B3-4F0C-B8D6-4EF05DB81548]","iPhone 6 (9.0) [AF6762C8-F35E-431A-AA6B-47AD68F311D2]","iPhone 6 (9.0) + Apple Watch - 38mm (2.0) [3AFA34DA-C8C7-4CF3-947E-821BC3889D77]","iPhone 6 Plus (9.0) [9F14DACC-99AD-4874-B8D8-F6869E04DCDA]","iPhone 6 Plus (9.0) + Apple Watch - 42mm (2.0) [81F5A7F9-6D88-4EEE-9389-58BDB86090DB]","iPhone 6s (9.0) [5E2F9DE9-50EC-409F-908D-CC8AD842E05B]","iPhone 6s Plus (9.0) [675C2032-FA50-46DD-A48E-97B015BBC4F9]"]) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 1.38 seconds
      Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
      System info: host: 'Anils-MacBook-Pro.local', ip: '169.254.51.5', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_7

**Comment by seleniumbheema** [comment]
@ scottdixon - can I've dmg for 1.4.10 please

**Comment by scottdixon** [comment]
1.4.13 is the closest .app: https://bitbucket.org/appium/appium.app/downloads/. You'll need to build from source if you're after 1.4.10 specifically.

However, in regards to your error: It can't find any iPhone 6 8.1.1 simulators. Changing Appium versions won't resolve this. What's the output when you run this command: `xcrun simctl list`?

**Comment by seleniumbheema** [comment]
Actually, I've installed Appium v.1.4.13 version in two different ways in Same machine. 

APpium through Console using Ruby - where My scripts are running fine for IOS Simulator 9.1 and Getting below errors for IOS 8.1.1 real device

org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Could not find a device to launch. You requested 'Bheema iPhone6 Test (8.1.1)', but the available devices were: ["iPad 2 (8.1) [107DC5F0-F95F-45D4-86A2-83320302FE92]","iPad 2 (9.1) [406CFCEB-5316-4D75-B904-5CD7E689378E]","iPad Air (8.1) [215658CF-75ED-4794-B09A-4FDA84DE9FD7]","iPad Air (9.1) [C6E19053-DAE6-421F-A0F9-B1536EA0445A]","iPad Air 2 (9.1) [590A2CB1-E148-4226-A845-0C9E8CC4F4F7]","iPad Pro (9.1) [4A418D52-F46E-4FBE-B63A-E41F5843F23C]","iPad Retina (8.1) [9BBBDA22-D57B-4CD2-BAAA-D91B7A606BF0]","iPad Retina (9.1) [7A8B25A7-E68F-4A8D-A393-9126366C575E]","iPhone 4s (8.1) [1546262E-61DC-447B-AA9C-293E5660DDB6]","iPhone 4s (9.1) [403B791B-B8DB-46B9-A1E6-199303FC6902]","iPhone 5 (8.1) [F4F2F181-FB63-4962-9046-4949C86A74CF]","iPhone 5 (9.1) [E98F0F6E-D0C9-4F80-A89D-D878F9693874]","iPhone 5s (8.1) [572666FF-3551-4E69-8259-994DD0C9E775]","iPhone 5s (9.1) [61C50C0D-BD7F-48B0-97D0-C936199726BF]","iPhone 6 (9.1) [1B57FB01-42D4-4DEA-A544-38BEC6166212]","iPhone 6 Plus (8.1) [4D8CF7C3-EFD1-4136-A0C1-CD8237B01C90]","iPhone 6 Plus (9.1) [3A301409-6977-43CA-A433-EB5D89C0AC0F]","iPhone 6-V8 (8.1) [E7EB6F7D-F0EE-40DB-BC9B-57B75074F1DE]","iPhone 6s (9.1) [E57644DC-7297-40F7-B142-6D354EA0D688]","iPhone 6s (9.1) + Apple Watch - 38mm (2.0) [066E0DDB-CB8C-4F30-BBB1-F4758CDAC489]","iPhone 6s Plus (9.1) [139D86FD-468C-40D9-BD94-E9A87B6F6283]","iPhone 6s Plus (9.1) + Apple Watch - 42mm (2.0) [3FFBF9A0-AEAC-4512-9FCF-2442004BDADD]"]) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 1.12 seconds
      Build info: version: '2.43.1', revision: '5163bceef1bc36d43f3dc0b83c88998168a363a0', time: '2014-09-10 09:43:55'
      System info: host: 'Anils-MacBook-Pro.local', ip: '169.254.62.107', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_79'
      Driver info: io.appium.java_client.ios.IOSDriver
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
      	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
      	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
      	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
      	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
      	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:240)
      	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:126)
      	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
      	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:109)
      	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:23)
      	at com.prevox.appium.util.webConnector.openApplication(webConnector.java:129)
      	at com.prevox.appium.login_Step.I_go_to_Yubl(login_Step.java:43)

APpium through GUI  - for IOS simulator 9.1-getting below errors

info: [debug] [INSTSERVER] Instruments exited with code null

info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator

**Comment by scottdixon** [comment]
You'll need to specify a UDID for the real device.

**Comment by seleniumbheema** [comment]
@scottdixon 

instruments cannot be opened because of a problem, for real device - Appium GUI.. 


How to configure UDID in console

**Comment by scottdixon** [comment]
From the docs: 
...you can run tests on that device by passing the `-U` or `--udid` flag.

More info: http://appium.io/slate/en/master/?ruby#appium-on-real-ios-devices

**Comment by seleniumbheema** [comment]
why Appium GUI is not working for me in any version,

**Comment by scottdixon** [comment]
What issue are you facing?

**Comment by seleniumbheema** [comment]
Failed to start an Appium session, err was: Error: Could not find a device to launch. You requested 'iPhone (8.2 Simulator)', but the available devices were: ["iPad 2 (8.1) [107DC5F0-F95F-45D4-86A2-83320302FE92]","iPad 2 (8.2) [78DED3BA-943E-4617-900E-DF1B2F741518]","iPad 2 (9.1) [406CFCEB-5316-4D75-B904-5CD7E689378E]","iPad Air (8.1) [215658CF-75ED-4794-B09A-4FDA84DE9FD7]","iPad Air (8.2) [E3199CDF-4B87-45BD-8C78-46A0CE9B61EB]","iPad Air (9.1) [C6E19053-DAE6-421F-A0F9-B1536EA0445A]","iPad Air 2 (9.1) [590A2CB1-E148-4226-A845-0C9E8CC4F4F7]","iPad Pro (9.1) [4A418D52-F46E-4FBE-B63A-E41F5843F23C]","iPad Retina (8.1) [9BBBDA22-D57B-4CD2-BAAA-D91B7A606BF0]","iPad Retina (8.2) [1DB7E218-F9B4-43C4-880D-FA18BCC242BD]","iPad Retina (9.1) [7A8B25A7-E68F-4A8D-A393-9126366C575E]","iPhone 4s (8.1) [1546262E-61DC-447B-AA9C-293E5660DDB6]","iPhone 4s (8.2) [39140424-CEC8-4EB5-90B3-98523349C301]","iPhone 4s (9.1) [403B791B-B8DB-46B9-A1E6-199303FC6902]","iPhone 5 (8.1) [F4F2F181-FB63-4962-9046-4949C86A74CF]","iPhone 5 (8.2) [EE9B652F-6672-47AE-9829-28B0F453C550]","iPhone 5 (9.1) [E98F0F6E-D0C9-4F80-A89D-D878F9693874]","iPhone 5s (8.1) [572666FF-3551-4E69-8259-994DD0C9E775]","iPhone 5s (8.2) [2B273DC2-00FE-4626-B327-C29AE3E2DE21]","iPhone 5s (9.1) [61C50C0D-BD7F-48B0-97D0-C936199726BF]","iPhone 6 (8.2) [2C879CD0-4265-42A0-BFE6-91CED4968B35]","iPhone 6 (9.1) [1B57FB01-42D4-4DEA-A544-38BEC6166212]","iPhone 6 Plus (8.1) [4D8CF7C3-EFD1-4136-A0C1-CD8237B01C90]","iPhone 6 Plus (8.2) [B0B0223A-32C7-4946-9BD1-F6759F9620A2]","iPhone 6 Plus (9.1) [3A301409-6977-43CA-A433-EB5D89C0AC0F]","iPhone 6-V8 (8.1) [E7EB6F7D-F0EE-40DB-BC9B-57B75074F1DE]","iPhone 6s (9.1) [E57644DC-7297-40F7-B142-6D354EA0D688]","iPhone 6s (9.1) + Apple Watch - 38mm (2.0) [066E0DDB-CB8C-4F30-BBB1-F4758CDAC489]","iPhone 6s Plus (9.1) [139D86FD-468C-40D9-BD94-E9A87B6F6283]","iPhone 6s Plus (9.1) + Apple Watch - 42mm (2.0) [3FFBF9A0-AEAC-4512-9FCF-2442004BDADD]"]

**Comment by seleniumbheema** [comment]
I'm using iPhone 6 Simulator 8.2 version, When I give Devicename as "=iPhone 6" then it will detect and throws same error

**Comment by scottdixon** [comment]
Grab the latest Appium: `npm install appium`
and then tell the GUI to use that external Appium package:
![image](https://cloud.githubusercontent.com/assets/4726068/10774506/cdeab376-7cbe-11e5-9951-91dd2a1b634e.png)

**Comment by seleniumbheema** [comment]
so, you want me uninstall my Current appium.app (GUI) reinstall it with above settings?

**Comment by seleniumbheema** [comment]
by installing that stuff I got npm-debug.log

**Comment by scottdixon** [comment]
If you'd like to use the GUI, leave it installed. You just need to adjust the GUI's settings to point to the latest version of Appium.

You can do this by installing the latest version: `npm install appium` and then telling the GUI to use that version (change `/path/to/appium` to the actual path of the newly installed appium).

**Comment by seleniumbheema** [comment]
while installing

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "appium"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! path ../appium/bin/appium.js
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall symlink

npm ERR! Error: EACCES: permission denied, symlink '../appium/bin/appium.js' -> '/Users/BheemaA/node_modules/.bin/appium'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, symlink '../appium/bin/appium.js' -> '/Users/BheemaA/node_modules/.bin/appium']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../appium/bin/appium.js',
npm ERR!   dest: '/Users/BheemaA/node_modules/.bin/appium' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/BheemaA/Documents/git_appium/appiumGUI/npm-debug.log

**Comment by scottdixon** [comment]
You'll need to downgrade to node 0.12 and then run it again.

**Comment by seleniumbheema** [comment]
Thanks @scottdixon , now Simulators are working fine GUI,

I've started running in real device by giving UDID, it didn't throw me error. it still running from 10mins.. will let you know for update

**Comment by seleniumbheema** [comment]
Brilliant, Thanks @scottdixon , 

Need to Run in CI, I planning to run the Appium server through programatically. Now we are changing the devices and versions forcefully in GUI. how can we run the different versions and devices while running appium server programmatically???

**Comment by scottdixon** [comment]
Glad to hear it. You can use Appium from the command line instead of the GUI. More info: http://appium.io/slate/en/master/

Alternatively, you can use a service like saucelabs.com to run your CI tests.
