### ISSUE TITLE
Appium is killing all the opened IOS simulator when starting, Which is creating issue when trying to run appium script on multiple IOS simulators

### ISSUE THREAD

**Issue by appiummaster-1** [appium/appium#5768]
<h2>Pre - Conditions</h2>
1. Xcode 7
2. Appium 1.4.13
3. Created two new simulator with different names and I'm able to successfully launched using command line.

<h2>Executed steps</h2>
1. Launched Selenium Grid
2. Started appium server with below commands

node appium.js -bp 5557 --chromedriver-port 5745 --port "4726" --nodeconfig /Software/iPhone6IOSSimulator.json --command-timeout "7200" --session-override --debug-log-spacing --log "/tmp/appium.log" --platform-version "9.0" --platform-name "iOS" --show-ios-log --device-name "iPhone 6 Srikanth" --launch-timeout "9999999" --native-instruments-lib

node appium.js -bp 5558 --chromedriver-port 5746 --port "4727" --nodeconfig /Software/iPhone5IOSSimulator.json --command-timeout "7200" --session-override --debug-log-spacing --log "/tmp1/appium.log" --platform-version "9.0" --platform-name "iOS" --show-ios-log --device-name "iPhone 5 Srikanth" --launch-timeout "9999999" --native-instruments-lib

<h1>ISSUE</h1>

Actual Result
When I run my script that time it is launching on first simulator and after that my script is trying to start on second simulator, that time my first simulator is automatically killed because appium is killing all the opened simulator instances. So its not possible to launch app on multiple simulators.

Expected Result
Appium should not kill all opened simulators.

**Comment by appiummaster-1** [comment]
https://discuss.appium.io/t/running-appium-script-on-multiple-ios-simulators/6739

**Comment by bootstraponline** [comment]
If there's no way to disable this then I think it's a bug in appium.

**Comment by dhuanggithub** [comment]
I am having the issue.  I would also like to start multiple instances of iOS simulator on the same machine.  This bug/issue makes it impossible.  Thank you.

**Comment by artgo** [comment]
+1 Same issue.

**Comment by sergeyzenchenko** [comment]
+1

**Comment by subash-canapathy** [comment]
+1

**Comment by dancyzheng** [comment]
I met the same issue when trying to start multiple instances of real devices.

**Comment by dhuanggithub** [comment]
See my latest update regarding real devices here [](https://github.com/appium/appium/issues/273)

**Comment by CoHuK** [comment]
Still no updates?

**Comment by CoHuK** [comment]
As I understand it's happening here: https://github.com/appium/appium-ios-simulator/blob/master/lib/utils.js
But why? Why don't we kill only one simulator?

**Comment by appiummaster-1** [comment]
I think now its time to fix this issue, lot of people facing the same issue. 
Please fix this issue asap.

**Comment by saikrishna321** [comment]
@appiummaster-1 i don't think this will be fixed, as i believe there a stream of work which is going on on WebDriverAgent which helps running tests on simulators without killing the sims

https://github.com/appium/WebDriverAgent

**Comment by hemano** [comment]
capabilities.setCapability(MobileCapabilityType.NO_RESET, true);

**Comment by hsoehalim** [comment]
in python:
self.caps['noReset'] = True

**Comment by iamchetan** [comment]
Has this been resolved for anybody?
Does anyone have a workaround for this issue?

**Comment by rkavalap** [comment]
Closing this as dup for #6385
