### ISSUE TITLE
Not able to set new command timeout value for Windows GUI.The option is disabled

### ISSUE THREAD

**Issue by thivyae** [appium/appium#5773]
Not able to set new command timeout value for Windows GUI.The option is disabled.Due to this,the appium server is always closing after leaving it idle for 60 secs.Very annoying.Any way to override this value alone during server startup?

**Comment by scottdixon** [comment]
Have you tried using the `Custom Server Flags` field?

In future, please post windows GUI queries in: https://github.com/appium/appium-dot-exe
