### ISSUE TITLE
Simulator iOS 9.1 crashes when appium try to build tree (screen contains alert)

### ISSUE THREAD

**Issue by VitaliLiavitski** [appium/appium#5774]
I use appium 1.14.13, and try to run my tests on iOS 9.1, for start appium I use this command 
 " node . --app path_to_my_app --device-name "iPhone 6" --platform-name iOS --native-instruments-lib ",
in application I should handle native iOS alert, but I can't do it because appium tries to build tree and crashes when this alert is displayed on screen.

appium lpgs:
info: [debug] Condition unmet after 10349ms. Timing out.
info: [debug] Cleaning up appium session
error: Could not pre-launch appium: Error: App did not have elements

**Comment by scottdixon** [comment]
Please provide a gist of the entire log.

**Comment by VitaliLiavitski** [comment]
info: [debug] Starting Appium in pre-launch mode
info: Pre-launching app
info: [debug] Using local app from command line: path_to_app
info: [debug] Creating new appium session 278902d5-9ecc-40e8-a6fd-b15fdb1e2df6
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version
info: [debug] Xcode version set to 7.1
info: [debug] Setting iOS SDK Version
info: [debug] iOS SDK Version set to 9.1
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.1","iOSSDKVersion":"9.1","deviceName":"iPhone 6","platformVersion":null}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone 6 (9.1)" to: "iPhone 6 (9.1) ["
info: [debug] Final device string is: 'iPhone 6 (9.1) ['
info: [debug] iOS sim UDID is GENERATED_GUID
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Getting bundle ID from app
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/admin/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/Volumes/Macintosh2/appium/src/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
...o: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
info: [debug] Dynamic bootstrap path: /Users/admin/Library/Application Support/appium/bootstrap/bootstrap-dabb1f9450e466dd.js
info: [debug] Reusing dynamic bootstrap: /Users/admin/Library/Application Support/appium/bootstrap/bootstrap-dabb1f9450e466dd.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.1","iOSSDKVersion":"9.1","deviceName":"iPhone 6","platformVersion":null}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone 6 (9.1)" to: "iPhone 6 (9.1) ["
info: [debug] Final device string is: 'iPhone 6 (9.1) ['
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.1","iOSSDKVersion":"9.1","deviceName":"iPhone 6","platformVersion":null}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone 6 (9.1)" to: "iPhone 6 (9.1) ["
info: [debug] Final device string is: 'iPhone 6 (9.1) ['
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall Simulator
info: [debug] Cleaning sim data files
info: node-simctl: Executing: xcrun with args: simctl erase GENERATED_GUID and timeout: 2000
info: [debug] Cleaning app data files
warn: Applications directory /Users/admin/Library/Developer/CoreSimulator/Devices/GENERATED_GUID/data/Applications doesn't exist. Have you run this simulator before?
info: Couldn't find app directories to delete. Probably it's not installed
info: [debug] Not setting locale
info: [debug] No iOS / app preferences to set
info: [debug] Starting iOS 8.* simulator log capture
info: [debug] Not pre-launching simulator
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on iPhone 6 (9.1) [
info: On xcode 7.0, instruments-without-delay does not work, skippinginstruments-without-delay
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6 (9.1) [" path_to_app -e UIASCRIPT "/Users/admin/Library/Application Support/appium/bootstrap/bootstrap-dabb1f9450e466dd.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And launch timeouts (in ms): {"global":90000}
info: [debug] [INST] Waiting for device to boot...
info: Instruments is ready to receive commands
info: [debug] Instruments launched. Starting poll loop for new commands.
info: [debug] Setting bootstrap config keys/values
info: [debug] Pushing command to appium work queue: "target = $.target();\nau = $;\n$.isVerbose = true;\n"
info: [debug] Socket data received (2 bytes)
info: [debug] Socket data being routed.
info: [debug] Sending command to instruments: target = $.target();
au = $;
$.isVerbose = true;
info: [debug] [INST] 2015-10-31 16:02:43 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-10-31 16:02:43 +0000 Debug: responding with:
info: [debug] [INST] 2015-10-31 16:02:43 +0000 Debug: Running system command #1: /usr/local/bin/node /Volumes/Macintosh2/appium/src/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":true}...
info: [debug] Socket data received (27 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":true}
info: [debug] Setting initial orientation to PORTRAIT
info: [debug] Pushing command to appium work queue: "au.setScreenOrientation('PORTRAIT')"
info: [debug] Sending command to instruments: au.setScreenOrientation('PORTRAIT')
info: [debug] [INST] 2015-10-31 16:02:44 +0000 Debug: Got new command 1 from instruments: au.setScreenOrientation('PORTRAIT')
info: [debug] [INST] 2015-10-31 16:02:44 +0000 Debug: evaluating au.setScreenOrientation('PORTRAIT')
info: [debug] [INST] 2015-10-31 16:02:44 +0000 Debug: target.setDeviceOrientation("1")
info: [debug] [INST] 2015-10-31 16:02:45 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-10-31 16:02:45 +0000 Debug: responding with:
info: [debug] [INST] 2015-10-31 16:02:45 +0000 Debug: Running system command #2: /usr/local/bin/node /Volumes/Macintosh2/appium/src/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"PORTRAIT"}...
info: [debug] Socket data received (33 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":"PORTRAIT"}
info: [debug] Waiting for app source to contain elements
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()
info: [debug] [INST] 2015-10-31 16:02:46 +0000 Debug: Got new command 2 from instruments: au.mainApp().getTreeForXML()
info: [debug] [INST] 2015-10-31 16:02:46 +0000 Debug: evaluating au.mainApp().getTreeForXML()
info: [debug] [INST] 2015-10-31 16:02:46 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-10-31 16:02:46 +0000 Debug: responding with: application_tree
. . .
appium tries to build tree several times (count of attempts = 11)
 . . .

info: [debug] [INST] 2015-10-31 16:02:56 +0000 Debug: Running system command #11: /usr/local/bin/node /Volumes/Macintosh2/appium/src/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"SpringBoard","label":" ","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":...
info: [debug] Socket data received (7086 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"SpringBoard","label":" ","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":0,"width":375,"height":667},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid
info: [debug] Condition unmet after 10340ms. Timing out.
info: [debug] Cleaning up appium session
error: Could not pre-launch appium: Error: App did not have elements

**Comment by scottdixon** [comment]
It looks like you're literally sending in 'path_to_my_app' - this should be replaced with the path to your .app file.

**Comment by VitaliLiavitski** [comment]
As for my first comment I replace my real path to  fake variable path_to_my_app only for comment, sorry if it mislead you
I used path to my .app file, 
node . --app /Volumes/Macintosh2/Test/myTest.app --device-name "iPhone 6" --platform-name iOS --native-instruments-lib
but I have faced with this issue, logs are attached above

**Comment by scottdixon** [comment]
@VitaliLiavitski - any luck with this? Have you tried Appium 1.5?

**Comment by SrinivasanTarget** [comment]
@VitaliLiavitski please reopen if you hit the same in latest server

**Comment by SrinivasanTarget** [comment]
@triager please close
