### ISSUE TITLE
appium crashes app on ios 9.1

### ISSUE THREAD

**Issue by nabeel-ibrahim** [appium/appium#5775]
I'm on appium 1.4.13 and using xcode 7.1 running ios 9.1. The appium server starts off fine but after a certain number of testcases the server will crash.
The logs are below
`[IOS_SYSLOG_ROW ] Oct 28 18:19:42 nibrahim-mbp theScore[51993]: *** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3512.29.5/UICollectionViewData.m:399
info: [IOS_SYSLOG_ROW ] Oct 28 18:19:42 nibrahim-mbp theScore[51993]: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}'
info: [IOS_SYSLOG_ROW ] *** First throw call stack:
info: [IOS_SYSLOG_ROW ] (
info: [IOS_SYSLOG_ROW ] 0   CoreFoundation                      0x0000000103970f45 __exceptionPreprocess + 165
info: [IOS_SYSLOG_ROW ] 1   libobjc.A.dylib                     0x0000000107db1deb objc_exception_throw + 48
info: [IOS_SYSLOG_ROW ] 2   CoreFoundation                      0x0000000103970daa +[NSException raise:format:arguments:] + 106
info: [IOS_SYSLOG_ROW ] 3   Foundation                          0x00000001079fe5ee -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
info: [IOS_SYSLOG_ROW ] 4   UIKit                               0x0000000105987dc5 __45-[UICollectionViewData validateLayoutInRect:]_block_invoke + 1285
info: [IOS_SYSLOG_ROW ] 5   UIKit                               0x000000010598739c -[UICollectionViewData validateLayoutInRect:] + 3067
info: [IOS_SYSLOG_ROW ] 6   UIKit                               0x000000010593654c -[UICollectionView layoutSubviews] + 194
info: [IOS_SYSLOG_ROW ] 7   UIKit                               0x000000010519ae40 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 710
info: [IOS_SYSLOG_ROW ] 8   QuartzCore                          0x0000000104b7859a -[CALayer layoutSublayers] + 146
info: [IOS_SYSLOG_ROW ] 9   QuartzCore                          0x0000000104b6ce70 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
info: [IOS_SYSLOG_ROW ] 10  QuartzCore                          0x0000000104b6ccee _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
info: [IOS_SYSLOG_ROW ] 11  QuartzCore                          0x0000000104b61475 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
info: [IOS_SYSLOG_ROW ] 12  QuartzCore                          0x0000000104b8ec0a _ZN2CA11Transaction6commitEv + 486
info: [IOS_SYSLOG_ROW ] 13  QuartzCore                          0x0000000104b8f37c _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
info: [IOS_SYSLOG_ROW ] 14  CoreFoundation                      0x000000010389c947 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
info: [IOS_SYSLOG_ROW ] 15  CoreFoundation                      0x000000010389c8b7 __CFRunLoopDoObservers + 391
info: [IOS_SYSLOG_ROW ] 16  CoreFoundation                      0x000000010389250b __CFRunLoopRun + 1147
info: [IOS_SYSLOG_ROW ] 17  CoreFoundation                      0x0000000103891e08 CFRunLoopRunSpecific + 488
info: [IOS_SYSLOG_ROW ] 18  GraphicsServices                    0x000000010b17bad2 GSEventRunModal + 161
info: [IOS_SYSLOG_ROW ] 19  UIKit                               0x00000001050e630d UIApplicationMain + 171
info: [IOS_SYSLOG_ROW ] 20  theScore                            0x0000000101742ed1 main + 65
info: [IOS_SYSLOG_ROW ] 21  libdyld.dylib                       0x000000010928192d start + 1
info: [IOS_SYSLOG_ROW ] )
info: [IOS_SYSLOG_ROW ] Oct 28 18:19:42 nibrahim-mbp SpringBoard[51463]: HW kbd: Failed to set (null) as keyboard focus
info: [IOS_SYSLOG_ROW ] Oct 28 18:19:42 nibrahim-mbp SpringBoard[51463]: UNNotificationRegistrarConnectionListener connection invalidated
info: [IOS_SYSLOG_ROW ] Oct 28 18:19:42 nibrahim-mbp com.apple.CoreSimulator.SimDevice.164A2665-6386-4C37-9BF3-71DC35988470.launchd_sim[51446] (UIKitApplication:com.thescore.ios.develop[0xf699][51993]): Service exited due to signal: Abort trap: 6
info: [IOS_SYSLOG_ROW ] Oct 28 18:19:42 nibrahim-mbp SpringBoard[51463]: Unable to get short BSD proc info for 51993: No such process
info: <-- GET /wd/hub/session/4af5dbc2-43e9-4f8b-a82c-609b49179dee/element/63/displayed 200 123.330 ms - 76 {"status":0,"value":true,"sessionId":"4af5dbc2-43e9-4f8b-a82c-609b49179dee"}
info: --> POST /wd/hub/session/4af5dbc2-43e9-4f8b-a82c-609b49179dee/element {"using":"name","value":"activity-indicator-icon.png"}
info: [IOS_SYSLOG_ROW ] Oct 28 18:19:42 nibrahim-mbp ScriptAgent[51994]: AX Lookup problem! 1102 com.apple.iphone.axserver:51993 (
info: [IOS_SYSLOG_ROW ] 0   AXRuntime                           0x000000010a0ddca5 _AXGetPortFromCache + 303
info: [IOS_SYSLOG_ROW ] 1   AXRuntime                           0x000000010a0dd894 AXUIElementCopyAttributeValue + 498
info: [IOS_SYSLOG_ROW ] 2   UIAutomation                        0x0000000108a45a5f -[UIAXElement valueForAttribute:] + 66
info: [IOS_SYSLOG_ROW ] 3   UIAutomation                        0x0000000108a48304 -[UIAXElement children] + 32
info: [IOS_SYSLOG_ROW ] 4   UIAutomation                        0x0000000108a541b6 -[UIAElement elements] + 164
info: [IOS_SYSLOG_ROW ] 5   CoreFoundation                      0x00000001067717ac __invoking___ + 140
info: [IOS_SYSLOG_ROW ] 6   CoreFoundation                      0x00000001067715fe -[NSInvocation invoke] + 286
info: [IOS_SYSLOG_ROW ] 7   ScriptProcessor                     0x00000001064aabc7 ObjCBridgeFunctionCallback + 3226
info: [IOS_SYSLOG_ROW ] 8   JavaScriptCore                      0x00000001085d4b8b _ZN3JSC19APICallbackFunction4callINS_18JSCallbackFunctionEEExPNS_9ExecStateE + 571
info: [IOS_SYSLOG_ROW ] 9   JavaScriptCore                      0x00000001085b10e0 _ZN3JSC14handleHostCallEPNS_9ExecStateENS_7JSValueENS_22CodeSpecializationKindE + 368
info: [IOS_SYSLOG_ROW ] 10  ???                                 0x000002d76a57cae4 0x0 + 3124225362660
info: [IOS_SYSLOG_ROW ] 11  ???                                 0x000002d76a583110 0x0 + 3124225388816
info: [IOS_SYSLOG_ROW ] 12  ???                                 0x000002d76a59a4f7 0x0 + 3124225484023
info: [IOS_SYSLOG_ROW ] 13  ???                                 0x000002d76a5995e5 0x0 + 3124225480165
info: [IOS_SYSLOG_ROW ] 14  ???                                 0x000002d76a596819 0x0 + 3124225468441
info: [IOS_SYSLOG_ROW ] 15  ???                                 0x000002d76a57cb7a 0x0 + 3124225362810
info: [IOS_SYSLOG_ROW ] 16  JavaScriptCore                      0x00000001086ba829 vmEntryToJavaScript + 326
info: [IOS_SYSLOG_ROW ] 17  JavaScriptCore                      0x000000010858dd79 _ZN3JSC7JITCode7executeEPNS_2VMEPNS_14ProtoCallFrameE + 169
info: [IOS_SYSLOG_ROW ] 18  JavaScriptCore                      0x000000010857099b _ZN3JSC11Interpreter7executeEPNS_14EvalExecutableEPNS_9ExecStateENS_7JSValueEPNS_7JSScopeE + 1291
info: [IOS_SYSLOG_ROW ] 19  JavaScriptCore                      0x0000000108570433 _ZN3JSC4evalEPNS_9ExecStateE + 1715
info: [IOS_SYSLOG_ROW ] 20  JavaScriptCore                      0x00000001086b6811 llint_slow_path_call_eval + 273
info: [IOS_SYSLOG_ROW ] 21  JavaScriptCore                      0x00000001086c06aa llint_entry + 23665
info: [IOS_SYSLOG_ROW ] 22  JavaScriptCore                      0x00000001086c03c6 llint_entry + 22925
info: [IOS_SYSLOG_ROW ] 23  JavaScriptCore                      0x00000001086c03c6 llint_entry + 22925
info: [IOS_SYSLOG_ROW ] 24  JavaScriptCore                      0x00000001086ba829 vmEntryToJavaScript + 326
info: [IOS_SYSLOG_ROW ] 25  JavaScriptCore                      0x000000010858dd79 _ZN3JSC7JITCode7executeEPNS_2VMEPNS_14ProtoCallFrameE + 169
info: [IOS_SYSLOG_ROW ] 26  JavaScriptCore                      0x0000000108574674 _ZN3JSC11Interpreter7executeEPNS_17ProgramExecutableEPNS_9ExecStateEPNS_8JSObjectE + 10404
info: [IOS_SYSLOG_ROW ] 27  JavaScriptCore                      0x000000010837e356 _ZN3JSC8evaluateEPNS_9ExecStateERKNS_10SourceCodeENS_7JSValueERN3WTF8NakedPtrINS_9ExceptionEEE + 470
info: [IOS_SYSLOG_ROW ] 28  JavaScriptCore                      0x00000001085d3528 JSEvaluateScript + 424
info: [IOS_SYSLOG_ROW ] 29  ScriptProcessor                     0x00000001064a0443 -[ScriptAgent startScript:] + 1451
info: [IOS_SYSLOG_ROW ] 30  Foundation                          0x000000010603c117 __NSThreadPerformPerform + 283
info: [IOS_SYSLOG_ROW ] 31  CoreFoundation                      0x00000001067af011 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
info: [IOS_SYSLOG_ROW ] 32  CoreFoundation                      0x00000001067a4f3c __CFRunLoopDoSources0 + 556
info: [IOS_SYSLOG_ROW ] 33  CoreFoundation                      0x00000001067a43f3 __CFRunLoopRun + 867
info: [IOS_SYSLOG_ROW ] 34  CoreFoundation                      0x00000001067a3e08 CFRunLoopRunSpecific + 488
info: [IOS_SYSLOG_ROW ] 35  Foundation                          0x00000001060403a1 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 267
info: [IOS_SYSLOG_ROW ] 36  Foundation                          0x00000001060d2d61 -[NSRunLoop(NSRunLoop) run] + 74
info: [IOS_SYSLOG_ROW ] 37  ScriptAgent                         0x0000000105f6b3b2 ScriptAgent + 5042
info: [IOS_SYSLOG_ROW ] 38  libdyld.dylib                       0x0000000107e6692d start + 1
info: [IOS_SYSLOG_ROW ] 39  ???                                 0x0000000000000001 0x0 + 1
info: [IOS_SYSLOG_ROW ] )
info: [IOS_SYSLOG_ROW ] Oct 28 18:19:42 nibrahim-mbp SpringBoard[51463]: Application 'UIKitApplication:com.thescore.ios.develop[0xf699]' crashed.
info: [IOS_SYSLOG_ROW ] Oct 28 18:19:42 nibrahim-mbp assertiond[51467]: assertion failed: 15B42 13B137: assertiond + 12188 [93FFE0B6-5C27-387F-B32A-6EE378BBB22A]: 0x1
info: [IOS_SYSLOG_ROW ] Oct 28 18:19:42 nibrahim-mbp assertiond[51467]: notify_suspend_pid() failed with error 7
info: [IOS_SYSLOG_ROW ] Oct 28 18:19:42 nibrahim-mbp assertiond[51467]: assertion failed: 15B42 13B137: assertiond + 12188 [93FFE0B6-5C27-387F-B32A-6EE378BBB22A]: 0x1
info: [IOS_SYSLOG_ROW ] Oct 28 18:19:42 nibrahim-mbp SpringBoard[51463]: [MPUSystemMediaControls] Updating supported commands for now playing application.
info: <-- POST /wd/hub/session/4af5dbc2-43e9-4f8b-a82c-609b49179dee/element 500 116.594 ms - 179 
info: --> POST /wd/hub/session/4af5dbc2-43e9-4f8b-a82c-609b49179dee/element {"using":"name","value":"activity-indicator-icon.png"}
error: Unexpected error: Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:350:11)
    at ServerResponse.header (/Users/nibrahim/node_modules/appium/node_modules/express/lib/response.js:695:10)
    at ServerResponse.send (/Users/nibrahim/node_modules/appium/node_modules/express/lib/response.js:146:12)
    at ServerResponse.json (/Users/nibrahim/node_modules/appium/node_modules/express/lib/response.js:235:15)
    at ServerResponse.send (/Users/nibrahim/node_modules/appium/node_modules/express/lib/response.js:134:21)
    at /Users/nibrahim/node_modules/appium/lib/server/responses.js:69:21
    at safely (/Users/nibrahim/node_modules/appium/lib/server/helpers.js:306:5)
    at exports.respondError (/Users/nibrahim/node_modules/appium/lib/server/responses.js:68:3)
    at onErr (/Users/nibrahim/node_modules/appium/lib/server/controller.js:153:5)
    at [object Object].onInstrumentsDie (/Users/nibrahim/node_modules/appium/lib/server/controller.js:159:5)
    at [object Object].<anonymous> (/Users/nibrahim/node_modules/appium/lib/devices/ios/ios.js:516:12)
    at [object Object].<anonymous> (/Users/nibrahim/node_modules/appium/lib/devices/ios/ios.js:1397:5)
    at [object Object].IOS.runSimReset (/Users/nibrahim/node_modules/appium/lib/devices/ios/ios.js:1368:5)
    at [object Object].IOS.postCleanup (/Users/nibrahim/node_modules/appium/lib/devices/ios/ios.js:1394:8)
    at [object Object].IOS.shutdown (/Users/nibrahim/node_modules/appium/lib/devices/ios/ios.js:1443:8)
    at [object Object].<anonymous> (/Users/nibrahim/node_modules/appium/lib/devices/ios/ios.js:523:12)
    at Server.<anonymous> (/Users/nibrahim/node_modules/appium/node_modules/appium-uiauto/lib/command-proxy.js:198:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1521:8)
    at doNTCallback1 (node.js:428:9)
    at process._tickDomainCallback (node.js:391:17) context: [POST /wd/hub/session/4af5dbc2-info: [IOS_SYSLOG_ROW ] Oct 28 18:19:4343e9-4f8b-a82c-609b49179dee/appium/app/launch {}]
 nibrahim-mbp DTServiceHub[51472]: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
info: Shutting down appium session`

**Comment by scottdixon** [comment]
Please provide a gist of the Appium server log.

**Comment by nabeel-ibrahim** [comment]
https://gist.github.com/nabeel-ibrahim/4846d45fc76d46d65981

**Comment by nabeel-ibrahim** [comment]
as additional info, I restart the app everytime a test fails i.e driver.closeApp() and driver.launchApp() and that after a time causes a crash of the app and the appium session. If I re run my tests again, the app would crash as soon as I initialize the iosDriver, but if I add the Full Reset flag and if I don't restart the app, this issue doesn't occur

**Comment by nabeel-ibrahim** [comment]
@scottdixon any update on this? I still cant run my testsuite on ios 9.1. After a certain time appium will crash

**Comment by scottdixon** [comment]
@nabeel-ibrahim - any progress on this? please try Appium 1.5

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by SrinivasanTarget** [comment]
Closed this because of inactivity.
