### ISSUE TITLE
iOS 9.1 is duplicating windows on apps

### ISSUE THREAD

**Issue by mathias21** [appium/appium#5777]
Hi

After installing iOS 9.1 in some iPhone 6, all my tests started to fail when using XPATH locator. This is caused by a new view hierarchy that iOS 9 is using. Each Window you have in the app is being duplicated with an invisible window behind, with the screen size. So the app window is being duplicated and also the Status bar is duplicated as well. This is killing any test with XPATH locator. This combined with the bug related with Accessibility values (https://github.com/appium/appium/issues/537) is really affecting the speed on Automation.

I'm attaching a screenshot of an empty project that I created just to check if the problem came from my app or Appium. Xcode is also reflecting these windows. I hope this could help you. If you have more information on why this is happening and if we can avoid it, I would be glad to hear your answers.

Thank you!
![multiplewindows](https://cloud.githubusercontent.com/assets/7766710/10815108/2f812450-7e2a-11e5-8360-cd48e7535398.png)

**Comment by dpgraham** [comment]
Closing this. If this is still an issue with new versions of Appium, please comment with a Gist of the appium logs where this is failing.
