### ISSUE TITLE
Need help on sendkeys for Android 6 (Marshmallow)

### ISSUE THREAD

**Issue by shivakatakam** [appium/appium#5780]
Hi,

I started working on Android 6 (Marshmallow ), i'm using Appium version 1.14.13.1 . Problem i'm facing here is i'm unable to use sendkeys as soon i call sendkeys method keyboard layout is popping due to this generated Xpaths are getting replaced with new keyboard xpath layout, 

Please assist me on this, i could not able to attach the files and images as i do not have write permissions.

**Comment by pamepros** [comment]
This was solved here: https://discuss.appium.io/t/need-help-on-sendkeys-for-android-6-marshmallow/6815/4
