### ISSUE TITLE
Web view in iOS not working

### ISSUE THREAD

**Issue by frankbolviken** [appium/appium#5784]
Hi,

I successfully used appium creating tests for a native app we have in our organisation. But when trying to create tests for our hybrid app, I am having difficulties. The app is created with Sencha Touch and compiled using cordova. The problem I have is that I cannot see the webview as an available context.

```
info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP"],"sessionId":"1d12aa5c-3109-41b8-8570-3723474bdd0d"}
info: <-- GET /wd/hub/session/1d12aa5c-3109-41b8-8570-3723474bdd0d/contexts 200 208.964 ms - 86 {"status":0,"value":["NATIVE_APP"],"sessionId":"1d12aa5c-3109-41b8-8570-3723474bdd0d"}
info: [debug] [REMOTE] Debugger socket disconnected
info: --> POST /wd/hub/session/1d12aa5c-3109-41b8-8570-3723474bdd0d/window {"name":"WEBVIEW"}
info: [debug] Responding to client that a method is not implemented in this context
```

```
Set<String> contextNames = driver.getContextHandles();
        for (String contextName : contextNames) {
            System.out.println(contextNames); //prints out something like NATIVE_APP \n WEBVIEW_1
        }
```

ContextNames only contains NATIVE_APP

**Comment by scottdixon** [comment]
Sounds like an issue with Sencha Touch - did you ever find a work around?

**Comment by frankbolviken** [comment]
Never found a solution and we just stopped trying basically. 
It was a rather old version of sencha touch also, so might be that things have changed though.

**Comment by scottdixon** [comment]
Thanks for the update. Reopen if you hit a similar issue.
