### ISSUE TITLE
Fails to install unlock_apk-debug.apk

### ISSUE THREAD

**Issue by gregorywringle** [appium/appium#5785]
Appiums dies on:

    adb install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"

After which capabilities get sent again and cause everything to be clobbered.

Log Snipit

    22:46:22 [36minfo[39m: [debug] App is installed
    22:46:22 [36minfo[39m: App is already installed, resetting app
    22:46:22 [36minfo[39m: [debug] Running fast reset (stop and clear)
    22:46:22 [36minfo[39m: [debug] executing cmd: adb shell "am force-stop com.test.test"
    22:46:23 [36minfo[39m: [debug] executing cmd: adb shell "pm clear com.test.test"
    22:46:24 [36minfo[39m: [debug] Forwarding system:2252 to device:4724
    22:46:24 [36minfo[39m: [debug] executing cmd: adb  forward tcp:2252 tcp:4724
    22:46:24 [36minfo[39m: [debug] Pushing appium bootstrap to device...
    22:46:24 [36minfo[39m: [debug] executing cmd: adb  push "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/
    22:46:24 [36minfo[39m: [debug] Pushing settings apk to device...
    22:46:24 [36minfo[39m: [debug] executing cmd: adb  install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/settings_apk/settings_apk-debug.apk"
    22:46:24 [36minfo[39m: [debug] Pushing unlock helper app to device...
    22:46:24 [36minfo[39m: [debug] executing cmd: adb  install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"
    22:56:15 [36minfo[39m: [37m<-- POST /wd/hub/session [39m[32m-[39m[90m - ms - -[39m [90m[39m
    22:56:17 [36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"app":"test.apk","platformVersion":"5.1.0","udid":"WQJ321JI","platformName":"Android","deviceName":"Nexus 5"}}[39m
    22:56:17 [36minfo[39m: Client User-Agent string: Apache-HttpClient/4.3.4 (java 1.5)
    22:56:17 [36minfo[39m: Found an existing session to clobber, shutting it down first...
    22:56:17 [36minfo[39m: Shutting down appium session
    22:56:17 [36minfo[39m: [debug] Pressing the HOME button
    22:56:17 [36minfo[39m: [debug] executing cmd: adb  shell "input keyevent 3"
    22:56:18 [36minfo[39m: [debug] Stopping logcat capture
    22:56:18 [36minfo[39m: [debug] Logcat terminated with code null, signal SIGTERM
    22:56:18 [36minfo[39m: [debug] Sent shutdown command, waiting for UiAutomator to stop...
    22:56:20 undefined
    23:06:17 [36minfo[39m: [37m<-- POST /wd/hub/session [39m[32m-[39m[90m - ms - -[39m [90m[39m

Appium Command 

    /Applications/Appium.app/Contents/Resources/node/bin/node lib/server/main.js --command-timeout 7200 --session-override

Note: Every time I've seen this occur there are about 10 minutes between unlocking and the capabilities being resent.

It appears that this line always appears before the capabilities get sent again:

    08:36:00 [36minfo[39m: [37m<-- POST /wd/hub/session [39m[36m303[39m[90m 20970.942 ms - 74[39m [90m[39m

Could it be the session timed out and the server is notifying the client?

**Comment by gregorywringle** [comment]
[Similar issue](https://github.com/appium/appium/issues/5525)

**Comment by adamf663** [comment]
no progress after 3 months.  why doesn't appium care that their software hangs and crashes?  (as I watch yet again hung installing appium/build/settings_apk/settings_apk-debug.apk )

**Comment by scottdixon** [comment]
@gregorywringle - does the issue persist?

@adamf663 - are you hitting the same issue on Appium 1.5?

**Comment by adamf663** [comment]
1.5 is too buggy.  had to revert. 

On March 8, 2016 4:33:27 PM MST, Scott Dixon <notifications@github.com> wrote:
>@gregorywringle - does the issue persist?
>
>@adamf663 - are you hitting the same issue on Appium 1.5?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/appium/appium/issues/5785#issuecomment-194023735

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by scottdixon** [comment]
@adamf663 - have you tried the 1.5 release? (outside of beta). There have been significant improvements since the beta release.

If you're hitting any problems with it please file an issue.

**Comment by adamf663** [comment]
it constantly crashes with no useful logging. . 0 releases are universally terrible. 

On March 8, 2016 5:21:57 PM MST, Scott Dixon <notifications@github.com> wrote:
>@adamf663 - have you tried the 1.5 release? (outside of beta). There
>have been significant improvements since the beta release.
>
>If you're hitting any problems with it please file an issue.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/appium/appium/issues/5785#issuecomment-194034329

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by scottdixon** [comment]
Would love some more info - Appium crashes when you run it? How are you running it?

**Comment by adamf663** [comment]
I was running it by spawning a process from java, specifying port and bport.  I need to run multiple applications and since appium insists on app and activity, I gave it the settings app.  Appium 1.4 has it's own problems.  70% of the time when I connect to the driver, it gives a session error so I pro-grammatically would kill and restart it.  Otherwise the worst part was that if you try to find_elements of a child and there isn't at least one, it would return an unrelated child of a different element.

With 1.5, it would simply crash with something like IEOP  (look at my ticket for wifi for example).  Just turning the access point on/off would often be enough to crash 1.5.  I had to get on with my automation development and reverted to 1.4.


----- Original Message -----

**Comment by scottdixon** [comment]
There are known issues around ADB network activity, specifically airplane mode. Please give the updated 1.5 a shot and post an issue with logs if you hit a problem.

**Comment by scottdixon** [comment]
Closing. @adamf663 has created a number of separate issues. @gregorywringle reopen if this specific issue persists in 1.5

**Comment by mukesh-kumar06** [comment]
Getting below error "INSTALL_FAILED_UPDATE_INCOMPATIBLE"
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D\:\\Android\\android-sdk\\platform-tools\\adb.exe -P 5037 -s 5bc2478f install C\:\\Users\\resi\\AppData\\Local\\Programs\\appium-desktop\\resources\\app\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk' exited with code 1'; Stderr: 'Failed to install C:\Users\resi\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-unlock\bin\unlock_apk-debug.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package io.appium.unlock signatures do not match the previously installed version; ignoring!]'; Code: '1' (WARNING: The server did not provide any stacktrace information)

Using Code:
DesiredCapabilities capabilities = new DesiredCapabilities();
		 capabilities.setCapability("browserName", "");   //Leave blank if automating an App
		 capabilities.setCapability("platformVersion", "7.1.1");
		 capabilities.setCapability("deviceName","Nexus 6");
		 capabilities.setCapability("platformName","Android");
		 capabilities.setCapability("newCommandTimeout","1200");
		 capabilities.setCapability("appPackage", "-------");
		 capabilities.setCapability("appActivity","----------");
		AndroidDriver<AndroidElement> drive = new AndroidDriver<AndroidElement>(new URL("http://---------/wd/hub"),capabilities);

**Comment by mukesh-kumar06** [comment]
Can anyone Pls help me with this issue?

**Comment by mahesh-kumbhar** [comment]
Simple uninstall 'Unlock' from Your Device and try again
