### ISSUE TITLE
NewCommandTimeout Appium Capability Doesn't Work in 1.4.13 (Running on Mac)

### ISSUE THREAD

**Issue by seleniumappiumnewbie** [appium/appium#5788]
caps.setCapability("newCommandTimeout", 600);
or 
caps.setCapability("newCommandTimeout", "600");

doesn't work in Appium 1.4.13

It keeps showing
info: [debug] Didn't get a new command in 60 secs, shutting down...
info: Shutting down appium session

NOTE: Running on Mac

**Comment by scottdixon** [comment]
Please use a more recent version of appium. Reopen + provide entire server log as a gist if the issue persists.
