### ISSUE TITLE
Adb flaky with lollipop + some manufacturer (like some asus tablets) [INFO] : java.lang.UnsatisfiedLinkError{...}

### ISSUE THREAD

**Issue by Fanch-** [appium/appium#5791]
It seems there is a bug making appium unable to work for specific devices, du to some adb commands working randomly (like adb shell uiautomator) : see https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars&groupby=&sort=&id=181995

Just for info if someone faced similar issue, and found a solution.

**Comment by vietnq254** [comment]
```
Reproduce : 
Compile project on Android Studio while your device is on the activity of the previous version of the project. You will get this error every time. This means that if you forget to close the activity, it will "relaunch" the activity and make it seem that the new project has been successfully loaded, but it's the old version that is launched.
```

```fullReset``` flag is your solution
```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("fullReset", true);
```

**Comment by Fanch-** [comment]
In fact for me it was the case regardless of the adb command, activity opened or not. (I also tried input keyevent/input text).

A recent upgrade from the tablet fixed the problem though !
