### ISSUE TITLE
Reset, reset flags and reinstall behaviour bugs

### ISSUE THREAD

**Issue by Ross-Code** [appium/appium#5793]
We having issues controlling reset/launch behaviour with Appium (1.14.13) from Python. The way the reset flags affect uninstall/reinstall behaviour is not obvious from the documentation and even though we feel we now have the correct flags, we keep hitting issues that may possibly be bugs (please see below).

**Expected behaviour:**
1. For the Reset command to just reset the application (depending on flags).

**Observed behaviour:**
1. The Reset command also always launches the application.
2. An error occurs when attempting to find elements from this "reset()" application launch:

**Expanded description of what we were attempting to do:**

The application auto-launches. But we want to time launches.
_So we set autoLaunch to false_

After writing several tests we realised the application is being completely uninstalled and reinstalled each test/run, which is not what we want, just the data to be reset.
_So we set fullReset to false_

We then wrote a test where we need to close and re-open the application and realised that application data is reset between the close_app() and launch_app().
_So we set noReset to false_

So now we can close/open the app during a test without resetting the data. However we then realise the data is never being reset for us between tests (which most of the time we do want).
_So we then start calling reset() before launch_app() at test start_

However now the app is being double launched every test because reset() launches the application by activity (it seems from reading code/logs) and then launch_app() launches the app again.
_So we remove the call to launch_app(), since the app is being launched by reset anyway_

However now the Appium server hits an error when we attempt to find UI elements because (it seems) the launch from reset() doesn't set something up that the launch from launch_app() does:

> error: Unhandled error: TypeError: Cannot read property 'sendAction' of null

So for now we reinserted the launch_app() and have the "bug" of the application double launches every test, which slows it down and is not ideal.

**Questions:**
1. Are we using Appium correctly for the behaviour we want? 
2. Are these issues bugs or do we misunderstand how reset is supposed to work?

**Opinion:**
There could be another (or several more) flag(s) that allow more fine-grained control install/uninstall behaviour that take precedence over the reset flags (if present) while leaving the reset flags to control actual _resetting_ behaviour. 

Thank you for reading

**Comment by dpgraham** [comment]
This document explains the reset features in detail

https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/reset-strategies.md
