### ISSUE TITLE
iOS-web-kit-debug-proxy : Could not connect to WebKitRemoteDebugger server

### ISSUE THREAD

**Issue by priyatech** [appium/appium#5794]
Hi,

iOS-web-kit-debug-proxy connects and disconnects with rpc server immediately.
On running the Appium code on hybrid app, works well on native pages, but fails while switching to the web context.
Error Message on Appium log: Could not connect to WebKitRemoteDebugger server
Responding to client with error: {"status":clock13:

1. This issue occurs both with iOS-web-kit-debug-proxy through appium/bin launcher and home-brew
2. Safari Web Inspector is enabled

Appium : 1.3.4
iOS device : 7.1
Xcode Version: 7.1
OSx Version: 10.10

**Comment by imurchie** [comment]
Does this work if you use an earlier version of Xcode, keeping iOS at 7.1?

**Comment by priyatech** [comment]
Initially, it was working . later i updated the OSx to 10.10.5 and Xcode to 7. After the updates, iOS-web-kit-debug-proxy connects and disconnects with rpc server immediately. Tried with the older version of Xcodev6.5, the issue is still the same. 
sudo xcode-select --switch /Applications/Xcode6.app/Contents/Developer

**Comment by imurchie** [comment]
Can you provide, in a gist, the Appium server log, `ios-webkit-debug-proxy` log, and any client-side logging that is available?

**Comment by priyatech** [comment]
[ios_web_kit_debug_proxy.txt](https://github.com/appium/appium/files/32583/ios_web_kit_debug_proxy.txt)
[appium_log.txt](https://github.com/appium/appium/files/32584/appium_log.txt)

Have uploaded the logs.

**Comment by scottdixon** [comment]
Please try with Appium 1.5 - post your entire logs if you have a problem.
