### ISSUE TITLE
"Open this page in" alert couldn't be automated

### ISSUE THREAD

**Issue by mcanovas** [appium/appium#5795]
Hello everyone,

I have an application with a Facebook connection created for iOS and I'd automated the Facebook connection using ios-webkit and Safari.

When I updated to iOS 9, I got a surprise. When the permissions to the app in Facebook are given and return to the application now appears the "Open this page in" alert.

When a try to accept this popup Appium remains stuck. I can't accept this popup.

After read some literature about the problem, I arrived to the fact that the alert is opened by Safari and I can't manage it because Safari is not signed as a Developer application.

The problem is that I NEED to close this popup, auto accept or something like that.

Is someone in the same problem? Is there some workaround? Facebook app signed for Dev? :-)

Thank for all

**Comment by scottdixon** [comment]
@mcanovas - please try the autoacceptalerts capability. Reopen if your issue persists.
