### ISSUE TITLE
Instruments Trace Error : Target failed to run: Permission to debug com.esct.PIt was denied. The app must be signed with a development identity (e.g. iOS Developer).

### ISSUE THREAD

**Issue by ashwin-pajankar** [appium/appium#5796]
I am using following desired capabilities with Appium and iPad 2

    DesiredCapabilities capabilities = new DesiredCapabilities();
    capabilities.setCapability("udid", "ea56e8ae8e5f5235c16d5315f4cb34d81be55917");
    capabilities.setCapability("platformName", "iOS");
    capabilities.setCapability("deviceName", "iPad 2");
    capabilities.setCapability("platformVersion", "8.3");
    capabilities.setCapability("app", "/Users/Aress-QA/Desktop/PSt-forQA.ipa");
    capabilities.setCapability("platformName", "iOS");
    wd = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"),capabilities);
    wd.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);

The application is launched and it crashes moments later, Appium console shows following error,

    info: [debug] [INST STDERR] 2015-11-04 14:51:55.082 instruments[9690:170378] WebKit Threading Violation - initial use of WebKit from a secondary thread.
    info: [debug] [INST STDERR] 2015-11-04 14:51:55.984 instruments[9690:170400] Attempting to change event horizon while disengage
    info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: Permission to debug com.esct.PIt was denied. The app must be signed with a development identity (e.g. iOS Developer).

Can anyone please help? Please do provide exact steps.

**Comment by scottdixon** [comment]
Which version of Appium are you running? Please provide the entire log as a gist.

**Comment by imurchie** [comment]
You will not be able to automate a production `ipa`. It needs to be built for development, and signed as such. This is a hard rule imposed by Apple.
