### ISSUE TITLE
ideviceinstaller is unable to install Safarilauncher.app file on real iOS device.

### ISSUE THREAD

**Issue by anjandevara** [appium/appium#5805]
ideviceinstaller is unable to install Safarilauncher.app file on real iOS device even thouhg the following points were properly set:
1. Bundle Identifier set - com.SafariLauncher.SafariLauncher
2. Code Signed with correct provisioning profiles
3. Provisioning profile added to the real device through iTunes
4. SafariLauncher.app zipped and pushed to SafariLauncherDirectory.
5. ideviceinstaller - Installed
6. ios-webkit-proxy - Installed & Configured
7. Appium server running on http://localhost:4723/wd/hub
8. ios-webkit-proxy running through terminal - ios_webkit_debug_proxy -d -c e49e850db4c4d7496cb8c50445c7e5edc1479a57:27753

Please help me in resolving this problem. 

I am getting only one Error as below:

error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c ideviceinstaller -u e49e850db4c4d7496cb8c50445c7e5edc1479a57 -i /var/folders/3d/78005x010_l3k1w65m7wlrxw0000gn/T/115106-88978-1rsbqes/SafariLauncher.app

info: [debug] Error: Command failed: /bin/sh -c ideviceinstaller -u e49e850db4c4d7496cb8c50445c7e5edc1479a57 -i /var/folders/3d/78005x010_l3k1w65m7wlrxw0000gn/T/115106-88978-1rsbqes/SafariLauncher.app

```
at ChildProcess.exithandler (child_process.js:203:12)
at emitTwo (events.js:87:13)
at ChildProcess.emit (events.js:172:7)
at maybeClose (internal/child_process.js:818:16)
at Socket.<anonymous> (internal/child_process.js:319:11)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at Pipe._onclose (net.js:469:12)
```

info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: /bin/sh -c ideviceinstaller -u e49e850db4c4d7496cb8c50445c7e5edc1479a57 -i /var/folders/3d/78005x010_l3k1w65m7wlrxw0000gn/T/115106-88978-1rsbqes/SafariLauncher.app\n)","killed":false,"code":128,"signal":null,"cmd":"/bin/sh -c ideviceinstaller -u e49e850db4c4d7496cb8c50445c7e5edc1479a57 -i /var/folders/3d/78005x010_l3k1w65m7wlrxw0000gn/T/115106-88978-1rsbqes/SafariLauncher.app","origValue":"Command failed: /bin/sh -c ideviceinstaller -u e49e850db4c4d7496cb8c50445c7e5edc1479a57 -i /var/folders/3d/78005x010_l3k1w65m7wlrxw0000gn/T/115106-88978-1rsbqes/SafariLauncher.app\n"},"sessionId":null}
info: <-- POST /wd/hub/session 500 8332.973 ms - 696

**Comment by addepalliamareswar** [comment]
It seems to be issue with command lines tools. Install command tools for
fixing this issue.

On 6 Nov 2015 20:46, "anjandevara" <notifications@github.com> wrote:
>
> ideviceinstaller is unable to install Safarilauncher.app file on real iOS
device even thouhg the following points were properly set:
>
> Bundle Identifier set - com.SafariLauncher.SafariLauncher
> Code Signed with correct provisioning profiles
> Provisioning profile added to the real device through iTunes
> SafariLauncher.app zipped and pushed to SafariLauncherDirectory.
> ideviceinstaller - Installed
> ios-webkit-proxy - Installed & Configured
> Appium server running on http://localhost:4723/wd/hub
> ios-webkit-proxy running through terminal - ios_webkit_debug_proxy -d -c
e49e850db4c4d7496cb8c50445c7e5edc1479a57:27753
>
> Please help me in resolving this problem.
>
> I am getting only one Error as below:
>
> error: Failed to start an Appium session, err was: Error: Command failed:
/bin/sh -c ideviceinstaller -u e49e850db4c4d7496cb8c50445c7e5edc1479a57 -i
/var/folders/3d/78005x010_l3k1w65m7wlrxw0000gn/T/115106-88978-1rsbqes/SafariLauncher.app
>
> info: [debug] Error: Command failed: /bin/sh -c ideviceinstaller -u
e49e850db4c4d7496cb8c50445c7e5edc1479a57 -i
/var/folders/3d/78005x010_l3k1w65m7wlrxw0000gn/T/115106-88978-1rsbqes/SafariLauncher.app
>
> at ChildProcess.exithandler (child_process.js:203:12)
> at emitTwo (events.js:87:13)
> at ChildProcess.emit (events.js:172:7)
> at maybeClose (internal/child_process.js:818:16)
> at Socket.<anonymous> (internal/child_process.js:319:11)
> at emitOne (events.js:77:13)
> at Socket.emit (events.js:169:7)
> at Pipe._onclose (net.js:469:12)
>
> info: [debug] Responding to client with error:
{"status":33,"value":{"message":"A new session could not be created.
(Original error: Command failed: /bin/sh -c ideviceinstaller -u
e49e850db4c4d7496cb8c50445c7e5edc1479a57 -i
/var/folders/3d/78005x010_l3k1w65m7wlrxw0000gn/T/115106-88978-1rsbqes/SafariLauncher.app\n)","killed":false,"code":128,"signal":null,"cmd":"/bin/sh
-c ideviceinstaller -u e49e850db4c4d7496cb8c50445c7e5edc1479a57 -i
/var/folders/3d/78005x010_l3k1w65m7wlrxw0000gn/T/115106-88978-1rsbqes/SafariLauncher.app","origValue":"Command
failed: /bin/sh -c ideviceinstaller -u
e49e850db4c4d7496cb8c50445c7e5edc1479a57 -i
/var/folders/3d/78005x010_l3k1w65m7wlrxw0000gn/T/115106-88978-1rsbqes/SafariLauncher.app\n"},"sessionId":null}

**Comment by anjandevara** [comment]
My Current Xcode Version - 6.3.2
Installed Commandline tool related to xcode version.
![commanvlinetoolsinstalled](https://cloud.githubusercontent.com/assets/8520504/11005186/719ba694-84e2-11e5-969b-647504873c22.jpg)

**Comment by ReinhardXu2007** [comment]
I've the similar problem.
Where did you put the privisioning profile?
Did you build the SafariLauncher yourself, or used the bundled SafariLauncher.
