### ISSUE TITLE
newCommandTimeout been ignored with selenium grid

### ISSUE THREAD

**Issue by shaikatz** [appium/appium#5809]
Hi,

I'm trying to set newCommandTimeout capability to 1000 seconds for my test.
I can see in the Appium log this line on the test initialization:
Setting command timeout to 1000 secs.
Despite that, after 5 minutes which is the default timeout, my session will be deleted due to timeout.
(I'm using autoLaunch=true, so it isn't related to issue #5568
I'm working with grid in version 2.46 and appium on version 1.4.0 running android tests.

**Comment by cthorell** [comment]
Having the same issue, would be great to get a fix for this one.

**Comment by scottdixon** [comment]
@shaikatz - 1.5 should resolve this - please reopen if the issue persists.

`npm install -g appium`
