### ISSUE TITLE
sendkeys seems to swipe when trying to delete hint text on android

### ISSUE THREAD

**Issue by rompic** [appium/appium#5816]
When appium tries to delete hint text in an edit box it seems to swipe and almost opens the android sidebar menu:
OS X 10.11.1
java-client 3.2.0
appium.dmg (1.4.13)

![halt](https://cloud.githubusercontent.com/assets/6322123/11060640/c68ca4e8-87a1-11e5-9d9a-b572cc758db9.png)

**Comment by rompic** [comment]
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: setText
info: [debug] [BOOTSTRAP] [debug] Using element passed in.
info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
info: [debug] [BOOTSTRAP] [debug] Text remains after clearing, but it appears to be hint text.
info: [debug] [BOOTSTRAP] [debug] Text not cleared. Assuming remainder is hint text.
info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: ...

**Comment by SrinivasanTarget** [comment]
Please try a latest version of appium and raise a new issue along with logs incase if you hit the same.

**Comment by SrinivasanTarget** [comment]
@triager please close
