### ISSUE TITLE
appium installation doesn't work because of cached files 

### ISSUE THREAD

**Issue by RoyGeagea** [appium/appium#5819]
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/lodash/-/lodash-3.10.1.tgz
npm ERR! tar.unpack untar error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/lodash/-/lodash-3.10.1.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/date-utils/-/date-utils-1.2.17.tgz
npm ERR! tar.unpack untar error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/date-utils/-/date-utils-1.2.17.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/binary-cookies/-/binary-cookies-0.1.1.tgz
npm ERR! tar.unpack untar error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/binary-cookies/-/binary-cookies-0.1.1.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/highlight.js/-/highlight.js-8.8.0.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/socket.io-parser/-/socket.io-parser-2.2.4.tgz
npm ERR! tar.unpack untar error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/socket.io-parser/-/socket.io-parser-2.2.4.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/core-js/-/core-js-0.9.18.tgz
npm ERR! tar.unpack untar error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/core-js/-/core-js-0.9.18.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/source-map-support/-/source-map-support-0.2.10.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/appium-instruments/-/appium-instruments-2.0.6.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/benchmark/-/benchmark-1.0.0.tgz
npm ERR! tar.unpack untar error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/benchmark/-/benchmark-1.0.0.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/bluebird/-/bluebird-2.10.1.tgz
npm ERR! tar.unpack untar error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/bluebird/-/bluebird-2.10.1.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/traceur/-/traceur-0.0.91.tgz
npm ERR! tar.unpack untar error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/traceur/-/traceur-0.0.91.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/appium-atoms/-/appium-atoms-0.0.5.tgz
npm ERR! tar.unpack untar error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/appium-atoms/-/appium-atoms-0.0.5.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/json3/-/json3-3.2.6.tgz
npm ERR! tar.unpack untar error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/json3/-/json3-3.2.6.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/swig/-/swig-1.4.2.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/difflib/-/difflib-0.2.4.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/appium-uiauto/-/appium-uiauto-1.10.10.tgz
npm ERR! tar.unpack untar error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/appium-uiauto/-/appium-uiauto-1.10.10.tgz
npm ERR! tar.unpack unzip error /var/folders/mt/65v75dg548q85x1dbw67hhwr0000gn/T/npm-82880-24b928f4/registry.npmjs.org/plist/-/plist-1.1.0.tgz

**Comment by scottdixon** [comment]
Please clear your NPM cache and try again. Reopen if the issue persists.

**Comment by RoyGeagea** [comment]
i clear the npm cache, the issue still appearing

**Comment by scottdixon** [comment]
@RoyGeagea see if any of these solutions help you out: https://github.com/npm/npm/issues/5133
