### ISSUE TITLE
Instruments often crashes

### ISSUE THREAD

**Issue by KentHan** [appium/appium#5824]
__info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)__
info: Appium REST http interface listener started on 0.0.0.0:4725
info: [debug] Non-default server args: {"port":4725}
info: Console LogLevel: debug
info: [37m--> [37mPOST [37m/wd/hub/session [90m{"desiredCapabilities":{"deviceName":"any device name is fine but udid should be correct one","udid":"6c110317767993119290afd07c5b693d54674467","platformName":"iOS","app":"/Users/Shared/Jenkins/Home/workspace/iOS_RunTest/ios/../apps/test.app","noReset":"true","newCommandTimeout":"300","fullReset":"false","autoAcceptAlerts":"true","bundleId":"com.testcorp.test.dev"}}
info: Client User-Agent string: Python-urllib/2.7
warn: Converting cap noReset from string to boolean. This might cause unexpected behavior.
warn: Converting cap fullReset from string to boolean. This might cause unexpected behavior.
warn: Converting cap autoAcceptAlerts from string to boolean. This might cause unexpected behavior.
info: [debug] Using local app from desired caps: /Users/Shared/Jenkins/Home/workspace/iOS_RunTest/apps/test.app
info: [debug] Creating new appium session 3c75ef5d-233b-455f-b822-936c8fe7a6a8
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Parsed app Localizable.strings
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/Shared/Jenkins/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/usr/local/Cellar/node/4.2.1/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":true,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/Shared/Jenkins/Library/Application Support/appium/bootstrap/bootstrap-022a0bdd244a23a7.js
info: [debug] Reusing dynamic bootstrap: /Users/Shared/Jenkins/Library/Application Support/appium/bootstrap/bootstrap-022a0bdd244a23a7.js
info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog
info: [debug] Creating iDevice object with udid 6c110317767993119290afd07c5b693d54674467
info: [debug] App is installed.
info: [debug] fullReset not requested. No need to install.
info: [debug] Starting command proxy.
info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 6c110317767993119290afd07c5b693d54674467
info: On xcode 7.0, instruments-without-delay does not work, skippinginstruments-without-delay
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 6c110317767993119290afd07c5b693d54674467 com.testcorp.test.dev -e UIASCRIPT "/Users/Shared/Jenkins/Library/Application Support/appium/bootstrap/bootstrap-022a0bdd244a23a7.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And launch timeouts (in ms): {"global":90000}
__info: [debug] [INST STDERR] Failed to find matching kernel in /System/Library/Kernels__
__info: [debug] [INST STDERR] _RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.__
info: [debug] [INST STDERR] 2015-11-12 18:31:16.358 instruments[39207:4721077] WebKit Threading Violation - initial use of WebKit from a secondary thread.
info: [debug] [INST STDERR] 2015-11-12 18:31:47.348 instruments[39207:4721081] Automation Instrument ran into an exception while trying to run the script.  UIAScriptAgentSignaledException
info: [debug] [32m[INST] 2015-11-12 09:31:47 +0000 Fail: An error occurred while trying to run the script.
info: [debug] [32m[INST] Instruments Trace Complete (Duration : 31.397085s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [90m[INSTSERVER] Instruments exited with code 0
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall Simulator

**Comment by KentHan** [comment]
Does anyone encounter this issue?

**Comment by KentHan** [comment]
Recovered after switching off and on **Enable UI Automation**.

**Comment by zetendra** [comment]
@KentHan how did you resolve this issue.. Facing same issue .....

**Comment by KentHan** [comment]
Hi @zetendra,
since it's a remote device in other country, I'm not sure what the real solution is.
I asked my colleage to re-enable **Enable UI Automation**, and restart the device.
After that, even the error message **Failed to find matching kernel in /System/Library/Kernels...** still occurs, Appium works.

(the error message occurs when I executes **instruments -s**, so I think's it's Apple issue)
