### ISSUE TITLE
ideviceinstaller error using Xcode7.1 and  appium 1.4 

### ISSUE THREAD

**Issue by jimramberg** [appium/appium#5826]
Apology in advance: I did some searching for newbie docs; and couldn't find anything helpful.
I am trying to get the ipHonesimulator working with Xcode 7.1 with OS El Captain 10.11

error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c ideviceinstaller -u XXXXXXXXXXXXXXXXXXX -l 

info: [debug] Cleaning up appium session
info: [debug] Error: Command failed: /bin/sh -c ideviceinstaller -u XXXXXXXXXXXXXXXXXXXXX -l 

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

Running the command in terminal gives:
Jims-MacBook-Pro:~ ramberg$ /bin/sh -c ideviceinstaller -u XXXXXXXXXXXXXXXXX -l

ERROR: No mode/command was supplied.
Usage: ideviceinstaller OPTIONS
Manage apps on iOS devices.

If this is a newbie error; I would appreciate being pointed to the correct resource/doc

thanks
jim

Note that I tried using both the UDID from the simulator as well as my hardware one for my mac

**Comment by marloncruz** [comment]
just use ideviceinstaller...
remove /bin/sh -c

**Comment by scottdixon** [comment]
Please try with Appium 1.5 - post your entire logs if you have a problem.

**Comment by ChristopherStephan** [comment]
Same issue with Appium 1.5.3.

**Comment by XPCD** [comment]
Using " /bin/sh -c ideviceinstaller" says "ERROR: No mode/command was supplied." but the direct "ideviceinstaller" command works fine. ideviceinstaller version is "HEAD-442f670_2" and Appium is 1.5.3.
