### ISSUE TITLE
Find the elements of Facebook App inside the Native app

### ISSUE THREAD

**Issue by arjaysalvadora** [appium/appium#5827]
I have a Native app run in Appium Selendroid mode. The Facebook app launch inside the native app when user click on the "Facebook Login" button. I'm having a problem getting the element inside the Facebook app. When i get the available context, appium always returns only one context. When i try to enter my login credential in the Email and Password field appium returns Selenium::WebDriver::Error::NoSuchElementError: Element was not found.

How can i solve this problem? please help.

The Appium server run in Selendroid mode. Here is the desired capabilities: --address "127.0.0.1" --callback-address "127.0.0.1" --callback-port "4723" --command-timeout "7200" --debug-log-spacing --automation-name "Selendroid" --platform-name "Android" --platform-version "4.3" --app "path/to/local/apk" --dont-stop-app-on-reset --device-name "Automation" --selendroid-port "8080"

![screen shot 2015-11-13 at 5 56 14 pm](https://cloud.githubusercontent.com/assets/11629336/11143606/5d607d2c-8a31-11e5-89be-e14985eeb1c2.png)

**Comment by asnaith** [comment]
If you can't find a work around maybe try uninstalling the facebook app from the device and see if you can automate the facebook webview login (which should appear if facebook app is not installed) instead.

**Comment by scottdixon** [comment]
Any luck with this @arjaysalvadora ?

**Comment by imurchie** [comment]
Are you sure that debugging is turned on for the webview?

https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/hybrid.md#automating-hybrid-android-apps
