### ISSUE TITLE
Appium 1.4.13 Inspector Partial Page Display

### ISSUE THREAD

**Issue by chemanth** [appium/appium#5841]
Using Appium 1.4.13 GUI Inspector, we are not able to see some portions of  pages in our App . In the below screenshot, the left hand pane is completely greyed out, whereas it actually exists in the Application.

![screenclip000100](https://cloud.githubusercontent.com/assets/4380406/11207892/f659b85e-8d3d-11e5-9c11-8c90dad70108.jpg)

**Comment by chemanth** [comment]
Got to see this thread, where the solution was scaling the simulator to 100%.
it worked. Now i am able to see the full page. But in previous versions of Appium, it was not needed.

**Comment by scottdixon** [comment]
Interesting. Thanks for the update.
