### ISSUE TITLE
TouchAction.moveTo() assumes relative coordinates on iOS and absolute coordinates on Android

### ISSUE THREAD

**Issue by rshanley** [appium/appium#5847]
Using Appium Java Client 3.2.0

TouchAction.moveTo(int x, int y) assumes absolute coordinates on Android.

On iOS however it assumes relative coordinates.

This breaks the platform independence.

We recreated this with the following Java test:

new TouchAction(driver).longPress(start.getX(), start.getY()).moveTo(end.getX(), end.getY()).release().perform()

**Comment by scottdixon** [comment]
@rshanley - please try Appium 1.5 `npm install -g appium`

Let me know if the issue persists.

**Comment by rshanley-micro-focus** [comment]
@scottdixon this issue still persists. we have been using a workaround.

**Comment by denniskpw** [comment]
Can confirm this is reproducible with the python client on Appium 1.5.3.

**Comment by dpgraham** [comment]
Closing. If this problem still occurs on Appium 1.6.x please post the error logs and I'll re-open it.

**Comment by pabitra-itobuz** [comment]
At the time of giving "(new TouchAction(driver)).tap(341, 44).perform();" this below mention error is showing. 
The method tap(TapOptions) in the type TouchAction is not applicable for the arguments (int, int)
If I want to use coordinates then how can I use?
Appium version:- 1.10.1
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
Selenium:- 3.141.59
Platform:- iOS
