### ISSUE TITLE
Replaying test with Appium from locked device causes android buttons to disappear

### ISSUE THREAD

**Issue by rshanley** [appium/appium#5848]
![appium_buttons_disappear](https://cloud.githubusercontent.com/assets/4246438/11240534/f3f8c530-8df3-11e5-903b-c59ed186c86d.png)

**Comment by amedvedjev** [comment]
+1 we got same. try restart device.

**Comment by rshanley** [comment]
'restart device' is ok as a manual workaround when testing locally but is not an acceptable solution in the long-term when running complex remote automated tests.

**Comment by scottdixon** [comment]
Which API level is this? Are you running the tests locally? How are you replaying?
