### ISSUE TITLE
Appium 1.5 issue with identifying elements

### ISSUE THREAD

**Issue by chemanth** [appium/appium#5849]
Have been setting up our automation infrastructure to be compatible with Appium 1.5.

Followed this thread
https://discuss.appium.io/t/appium-1-5-beta-release/6058
and have done the set up. 

But We are gtting the below error while trying to type text in a textfiled.

``` There was an org.openqa.selenium.UnsupportedCommandException: Parameters were incorrect. We wanted {"required":["value"]} and you sent ["id","value"]```

Could someone kindly look into this ? I would love to help you guys by providing the logs.

**Comment by pr4bh4sh** [comment]
Facing same issue any updates...

**Comment by hectorv** [comment]
I'm getting a similar error on iOS while trying to use `set_value`:

```
WebDriverException: Message: Parameters were incorrect. We wanted {"required":["value"]} and you sent ["elementId","value","id"]
```

I remember we replaced `send_keys` with `set_value` because it was [much faster on iOS](https://discuss.appium.io/t/how-to-make-appium-tests-run-faster-on-ios/445). Is that no longer supported on Appium 1.5?

**Comment by scottdixon** [comment]
I think this was addressed in a later release - @chemanth please try with the latest Appium 1.5

**Comment by chemanth** [comment]
@scottdixon I have got this error during beta testing. Now this error is no more occurring.

**Comment by scottdixon** [comment]
Thanks for the update!
