### ISSUE TITLE
iOS Simulators re-booting for every test

### ISSUE THREAD

**Issue by dantapadmi** [appium/appium#5850]
Having upgraded Appium so I can use iOS 9 simulators I am now experiencing an issue whereby the simulator will perform a full restart for every test (in a similar way as to when you select reset content and settings). I do not have this problem if I run the app through xcode, close the simulator and run again (it immediately starts). This is very irritating as it's increasing the length of my tests, has anyone experience and/or solved a similar issue?

Attached is a screenshot.
![screen shot 2015-11-18 at 16 43 02](https://cloud.githubusercontent.com/assets/13796074/11268393/65da462e-8ea8-11e5-86db-71850182740b.png)

EDIT: I will added that I never had this issue on the older version of Appium/Xcode.

**Comment by chemanth** [comment]
Are you sure, the "Full Reset" option is not checked under iOS Settings in your Appium GUI ?

**Comment by dantapadmi** [comment]
I am using the non-GUI version of Appium and have not set any capabilities with regards to reset, this all worked fine previously. I should note I did try setting both the fullReset and noReset capabilities and was able to avoid the reboot but the app data was not reset which is a problem.

**Comment by dantapadmi** [comment]
Here is the output when Appium initially sets up the simulator...

info: [debug] Dynamic bootstrap path: /Users/dant/Library/Application Support/appium/bootstrap/bootstrap-d64fb2c6ae4302bd.js
info: [debug] Reusing dynamic bootstrap: /Users/dant/Library/Application Support/appium/bootstrap/bootstrap-d64fb2c6ae4302bd.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.1","iOSSDKVersion":"9.1","deviceName":"iPhone 6","platformVersion":"9.1"}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone 6 (9.1)" to: "iPhone 6 (9.1) ["
info: [debug] Final device string is: 'iPhone 6 (9.1) ['
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.1","iOSSDKVersion":"9.1","deviceName":"iPhone 6","platformVersion":"9.1"}
info: [debug] fixDevice is on
info: [debug] Fixing device. Changed from: "iPhone 6 (9.1)" to: "iPhone 6 (9.1) ["
info: [debug] Final device string is: 'iPhone 6 (9.1) ['
info: [debug] Parsed app Info.plist (as binary)
info: [debug] Wrote new app Info.plist with device type
info: [debug] Checking whether we need to set app preferences
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall Simulator
info: [debug] Resetting Content and Settings for Simulator
info: node-simctl: Executing: xcrun with args: simctl erase 7B25504A-C3ED-4EB2-A6CD-E1F6BADFFE3D and timeout: 2000
info: node-simctl: Executing: xcrun with args: simctl erase 7B25504A-C3ED-4EB2-A6CD-E1F6BADFFE3D and timeout: 2000
info: node-simctl: Executing: xcrun with args: simctl erase 7B25504A-C3ED-4EB2-A6CD-E1F6BADFFE3D and timeout: 2000
info: node-simctl: Executing: xcrun with args: simctl erase 7B25504A-C3ED-4EB2-A6CD-E1F6BADFFE3D and timeout: 2000
info: [debug] Not setting locale

As you can see Resetting Content and Settings for Simulator is being called, either this isn't the case for <ios 9.0 simulators or it doesn't work. Either way the end result is that the iOS 9 simulators always have to do a full startup. No permutation of the fullreset and noReset flags results in what I want which is for the app to be freshly installed (remove app data) without resetting the simulator completely.

**Comment by scottdixon** [comment]
Can you please give 1.5 a shot: `npm install -g appium` - let me know if the issue persists.
