### ISSUE TITLE
reset.sh failed at while building appium from master branch

### ISSUE THREAD

**Issue by priyankshah217** [appium/appium#5856]
Hi,

I was trying to build appium from source. I was not able to build while running reset.sh file.

Please find below link.

https://gist.github.com/priyankshah217/ed0bd0a254fe3f38d177

Thanks,
Priyank Shah

**Comment by pr4bh4sh** [comment]
https://github.com/appium/appium/issues/5869

**Comment by scottdixon** [comment]
Please try with Appium 1.5 - we've removed `reset.sh`
