### ISSUE TITLE
Inspector displaying invisible objects parameters

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium#5860]
In a scenario, Appium inspector displaying invisible objects parameters also. This is causing my scripts to  fail. 

Scenario is:

1. In Screen 1, Tap on a button(You will navigate to Screen 2)
2. In Screen 2, I have 5 buttons objects(I stored all 5 objects into a list)
3. From Screen2, I tapped on a button and navigated to Screen1
4. From screen1, Again tapped on a button(again navigated to Screen 2)
5. Now in Screen 2, Inspector showing only 5 buttons. But when run the loop to tap on 2nd button from available 5 button, Appium failed to tap on it.
So, i printed all the available button text using .getText() method and I found that inspector having information of background screen(Screen 1) and foreground screen(Screen 2) objects.
I don't need screen 1 objects information as I am in screen 2 now. here screen 1 is not at all visible. Why Appium inspector collecting objects from screen 1 when I am in screen 2.

How to get rid of invisible objects identification. Don't say uncheck 'Show Invisible' in Appium Inspector, I already did that.

**Comment by scottdixon** [comment]
Please file GUI issues in the [appium-dot-app project](https://github.com/appium/appium-dot-app). Thank you
