### ISSUE TITLE
Tapping on already selected option is not working in hamburger menu 

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium#5861]
I have selected a option by tapping on it from hamburger menu. If I try to tap again on them same option by opening hamburger menu, Tap is not happening. 

But when I did re-tapping manually that's working fine. So, no issue with App.

How to tap on it???

**Comment by marloncruz** [comment]
try click instead of tap.

**Comment by shivakrishnach31** [comment]
I tried both @marloncruz , but no success.

**Comment by scottdixon** [comment]
@shivakrishnach31 - are you still experiencing issues? Can you provide a log / sample app?

Also, give Appium 1.5 a shot `npm install -g appium`
