### ISSUE TITLE
Windows installer contains deprecated version of node

### ISSUE THREAD

**Issue by yahman72** [appium/appium#5862]
Appium installer (the windows one) comes with a deprecated version of node.

<pre>
Checking if an update is available
Update not available
Launching Appium server with command: C:\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --platform-name Android --platform-version 23 --automation-name Appium --log-no-color
<b>warn: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!`</b>
</pre>

**Comment by scottdixon** [comment]
Please file this issue in the [Windows GUI project](https://github.com/appium/appium-dot-exe).
