### ISSUE TITLE
Appium will not work if used or installed with sudo. Please rerun/install as a non-root user.

### ISSUE THREAD

**Issue by vickykm2000** [appium/appium#5863]
Getting below error while executing appium on jenkins... please help..
Appium will not work if used or installed with sudo. Please rerun/install as a non-root user. If you had to install Appium using `sudo npm install -g appium`, the solution is to reinstall Node using a method (Homebrew, for example) that doesn't require sudo to install global npm packages

**Comment by SrinivasanTarget** [comment]
Closing this in favour of https://github.com/appium/appium/issues/1902.

**Comment by SrinivasanTarget** [comment]
@triager please close
