### ISSUE TITLE
Failed to start an Appium session (google a lot but coudn't find wordkaround )

### ISSUE THREAD

**Issue by aasan** [appium/appium#5865]
Hi All,
I am new to Appium, below is issue i am facing while trying to run safari browser. 
Log of Appium is below:

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --debug-log-spacing --platform-version "8.4" --platform-name "iOS" --udid "c366c13f7712717f33903969375cea17b19b262" --show-ios-log --device-name "iPhone 5"

info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)

info: Appium REST http interface listener started on 0.0.0.0:4723

info: [debug] Non-default server args: {"udid":"c366c13f7712717f33903969375cea17b19b262","deviceName":"iPhone 5","platformName":"iOS","platformVersion":"8.4","showIOSLog":true,"defaultCommandTimeout":7200,"debugLogSpacing":true}
info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: <-- GET /wd/hub/status 200 11.799 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: <-- GET /wd/hub/status 200 2.993 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: <-- GET /wd/hub/status 200 0.737 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: <-- GET /wd/hub/status 200 1.161 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> POST /wd/hub/session {"desiredCapabilities":{"browserName":"safari","platformName":"iOS","udid":"c366c13f7712717f33903969375cea17b19b262b","deviceName":"iPhone 5","platformVersion":"8.4"}}

info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.8.0_65)
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***

error: Failed to start an Appium session, err was: Error: ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'

info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] Configuring Safari session
info: [debug] Using local .zip from command line: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip
info: [debug] Copying local zip to tmp dir
info: [debug] Got configuration error, not starting session
info: [debug] Cleaning up appium session
info: [debug] Error: ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'
    at Error (native)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip')","errno":-2,"code":"ENOENT","path":"/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip","origValue":"ENOENT, stat '/Applications/Appium.app/Contents/Resources/node_modules/appium/build/SafariLauncher/SafariLauncher.zip'"},"sessionId":null}
info: <-- POST /wd/hub/session 500 20.079 ms - 498 

While Java Code is Below

package com.learn.mobile.browser;
import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.WebDriver;
import org.testng.annotations.Test;

import io.appium.java_client.ios.IOSDriver;

import org.testng.annotations.BeforeTest;
import org.testng.annotations.AfterTest;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

public class TestGoogle {
  WebDriver wd;

  @BeforeTest
  public void beforeTest() throws MalformedURLException 
  {
      DesiredCapabilities capabilities = new DesiredCapabilities();

```
  capabilities.setCapability("deviceName", "iPhone 5");
  capabilities.setCapability("platformName", "iOS");
  capabilities.setCapability("platformVersion", "8.4");
  capabilities.setCapability("udid", "c366c13f7712717f33903969375cea17b19b262b");
  capabilities.setCapability(CapabilityType.BROWSER_NAME, "safari");
  wd = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
```

  }

  @Test
  public void testSearchPage() 
  {
 // wd.get("www.google.co.uk");
  }

  @AfterTest
  public void afterTest() {
  }

}

Appium Apple Setting Screenshot is:
![screen1](https://cloud.githubusercontent.com/assets/16004536/11376827/a294a8f8-92da-11e5-83c5-89e45bbf21a6.png)

**Comment by marloncruz** [comment]
Could you try the steps in this page?
https://discuss.appium.io/t/mobile-web-automation-on-ios-real-device-safari/4900

**Comment by scottdixon** [comment]
It looks like it can't find SafariLauncher. Can you please try with Appium 1.5? `npm install -g appium`
