### ISSUE TITLE
After a problem Appium takes 100% of CPU and is not able to run tests anymore

### ISSUE THREAD

**Issue by jderrien** [appium/appium#5867]
Hello,

When an error occurs for some reasons, it appears the session is cleaned up but then the iOS simulator cannot be launched anymore and the CPU usage is 100% for the node process.

Here is the log: [appium-100-cpu.txt](https://github.com/appium/appium/files/43077/appium-100-cpu.txt)

In this log, during the first session, the iOS simulator starts to boot but it takes too long.

I've set `--launch-timeout 180000` but I think it only waits around 135 seconds according to:
- the number (27) of lines `info: --> GET /wd/hub/status {}` between `info: [debug] [INST] Waiting for device to boot...` and `info: Found an existing session to clobber, shutting it down first...`
- and the register cycle (5 sec)

Then the session is overridden since I've launched Appium with {{--session-override}}. Which is expected.

But during the next session the iOS simulator is not launched (or doesn't show up), and the CPU usage goes to 100%. I don't know exactly when the CPU usage problems occurs, but I would be happy to try to reproduce this issue and provide more information.

My thought is that it starts when the `undefined` line is logged (but again it's something I have to confirm):
```
info: [debug] Killall Simulator
undefined
```

About the context, I run iOS simulators in multiple VM (only one simulator per VM). The disk I/O can be really slow specially during the first start of the iOS simulator. And a lot of problems can happen during this time.

Even if the system is a bit overloaded during this time, there is something wrong with Appium that takes 100% of CPU and is not able to continue.

I'm using:
- OS X ElCapitan
- Node 5.1.0
- Appium 1.4.15
- Xcode 7.1
- iOS 9.1
- Selenium 2.48.2 (grid)

I launch Appium with:
```
appium --nodeconfig $config --safari --port $port --launch-timeout 180000 --command-timeout 120 --native-instruments-lib --session-override --log-level debug >> $logfile 2>&1
```

The node configuration is:
```
{
  "capabilities": [
    {
      "browserName": "iPhone5s",
      "version":"9.1",
      "maxInstances": 1,
      "platform":"MAC"
    }
  ],
  "configuration": {
    "cleanUpCycle": 2000,
    "timeout": 120000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url": "http://osxe-ios-0501:5555/wd/hub",
    "host": "osxe-ios-0501",
    "port": 5555,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubHost": "hub-02.xxxxxxx.xxx",
    "hubPort": 4444
  }
}
```

Let me know if you need more details.

Thanks!

**Comment by scottdixon** [comment]
Can you please try Appium 1.5? Let me know if you see the same issue.

**Comment by jderrien** [comment]
@scottdixon My work context has changed and I'm no more in charge of this project. I cannot help anymore on this issue. Sorry.

I've resolved the issue by adding more RAM to the OS X VM. Closing the issue.

**Comment by scottdixon** [comment]
Thanks for the update.
