### ISSUE TITLE
[iOS] can’t capture screenshot correctly on Xcode7.1

### ISSUE THREAD

**Issue by jormungand2006** [appium/appium#5868]
Related: https://discuss.appium.io/t/ios-cant-capture-screenshot-correctly-on-xcode7-1/6872

Hello,
after I updated Xcode7.1, I noticed that I can't capture screenshot correctly on Xcode7.1 simulator by "screenshot" method.
When I test UICatalog.app on Xcode6.4 / Xcode7.0.1 simulator, screenshot is correct as I expected.
But when I test UICatalog.app on Xcode7.1 simulator, screenshot is not correct.
The result is that image lacks half of screen.

![2015-11-02_14-05-12_ios_lastscreen](https://cloud.githubusercontent.com/assets/6168526/11391566/a5c5a81c-9396-11e5-928f-d65adad9f253.png)

So my question is that it's a latest Instruments bug or Appium's bug?

[Condition]
・Mac OS X Yosemite (10.10.5)
・Xcode7.1.1 / Xcdoe7.0.1 / Xcode6.4
・Appium 1.4.16, 1.4.13 (GUI)
・appium_lib 7.0.0

Thanks!

**Comment by scottdixon** [comment]
Interesting. Does the same issue occur on Appium 1.5? Also, have you tried iOS 9.2 or 9.3?

**Comment by toejough** [comment]
I'm also having this problem - I'm using the 9.1 simulator.  I'm planning on trying out appium 1.5 as soon as I can actually get it installed (npm is having a hard time installing it, for whatever reason).  @jormungand2006 - if you get this figured out can you post an update?  I'll do the same.

**Comment by brtu** [comment]
I was getting the same issue.  It was because I had the iOS simulator set to 50% scaling.  When I set the scaling back to 100%, it got the whole picture.
