### ISSUE TITLE
reset.sh fails to install the "android-driver-app" and fails to build for selendroid from source.

### ISSUE THREAD

**Issue by pr4bh4sh** [appium/appium#5869]
@Jonahss @jlipps @sebv @moizjv 
I'm trying to build and run Appium from source. If i execute 
```./reset.sh --ios --android --verbose```

 it works however my requirement include selendroid too, so i did
```./reset.sh --selendroid --verbose```

it fails to build with this log - https://gist.github.com/pr4bh4sh/e495f55351592d8765af

So i tried to install the android-driver-app from npm
```npm install android-driver-app --verbose```

It also fails to install with log- https://gist.github.com/pr4bh4sh/60e30b6204dd83db32f8

From the log it seems that the ```android-driver-app``` is not at https://registry.npmjs.org/android-driver-app anymore.
This seems to be the issue behind this (at least at this step).

P.S. I have all the check passed when i run ```appium-doctor```

**Comment by moizjv** [comment]
@pr4bh4sh can you pull latest code from master and then update submodules `"git submodule sync && git submodule update --init`

**Comment by pr4bh4sh** [comment]
@moizjv I did below steps
1. git clone https://github.com/appium/appium.git --branch master
2. git submodule sync && git submodule update --init
3. npm cache clean
4 ./reset.sh --selendroid --verbose

I'm still getting this log https://gist.github.com/pr4bh4sh/e495f55351592d8765af

**Comment by SrinivasanTarget** [comment]
@pr4bh4sh Appium 1.5 doesn't have reset.sh now so please try and update us with appium logs incase if you face any issues.

@scottdixon We can close this for now as we don't have reset.sh in new arch.
