### ISSUE TITLE
appium can not connect to the device 

### ISSUE THREAD

**Issue by yisake** [appium/appium#5883]
I've met a problem. I start second appium for different TCP port(4723,4725) and there is 2 devices on my computer. From my script I want to connect to the 192.168.56.102:5555, but appium connect to the first device. Please check the appium log below.The post request and the appium log.

######attention
> info: --> POST /wd/hub/session {"desiredCapabilities":{"deviceName":"192.168.56.102:5555","unicodeKeyboard":true,"resetKeyboard":true,"platformVersion":"4.3","appPackage":"com.android.calculator2","platformName":"Android","appActivity":".Calculator"}}

> info: [debug] executing cmd: E:\360浜戠洏\Fangdd\android-sdk-windows\platform-tools\adb.exe devices
> info: [debug] 2 device(s) connected
> info: Found device 192.168.56.101:5555
> info: [debug] Setting device id to 192.168.56.101:5555

#####command log
C:\Users\Administrator>adb devices
List of devices attached
192.168.56.101:5555     device
192.168.56.102:5555     device

C:\Users\Administrator>

#####appium log
> info: --> POST /wd/hub/session {"desiredCapabilities":{"deviceName":"192.168.56.102:5555","unicodeKeyboard":true,"resetKeyboard":true,"platformVersion":"4.3","appPackage":"com.android.calculator2","platformName":"Android","appActivity":".Calculator"}}
> info: Client User-Agent string: Python-urllib/2.7
> info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
> info: [debug] Creating new appium session 2aa50261-04f4-43f1-8ab3-7cb1982b6aa9
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.6.0_45
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from E:\360浜戠洏\Fangdd\android-sdk-windows\platform-tools\adb.exe
> warn: No app capability, can't parse package/activity
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Not checking whether app is present since we are assuming it's already on the device
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: E:\360浜戠洏\Fangdd\android-sdk-windows\platform-tools\adb.exe devices
> info: [debug] 2 device(s) connected
> info: Found device 192.168.56.101:5555
> info: [debug] Setting device id to 192.168.56.101:5555
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: E:\360浜戠洏\Fangdd\android-sdk-windows\platform-tools\adb.exe -s 192.168.56.101:5555 wait-for-device
> info: [debug] executing cmd: E:\360浜戠洏\Fangdd\android-sdk-windows\platform-tools\adb.exe -s 192.168.56.101:5555 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level

**Comment by yisake** [comment]
the bug if from GUI of version of AppiumForWindows_1_4_13_1

**Comment by kcinman11358** [comment]
Can you post your capabilities list? You should be able to get around this by specifying which server you want to connect during driver construction

**Comment by scottdixon** [comment]
Please try with Appium 1.5 - post your entire logs if you have a problem.
