### ISSUE TITLE
Appium on Android: Keyboard.sendKeys(text) does not work for special characters such as backspace and enter

### ISSUE THREAD

**Issue by FrankBorland** [appium/appium#5886]
The Selenium keycodes for special characters such as backspace and enter do not work on Appium on Android. (Note: They work on Appium on iOS).

It looks like the an internal mapping from Selenium keycode to Android keycode is missing from the Appium implementation.

**Comment by scottdixon** [comment]
Please try with Appium 1.5 - post your entire logs if you have a problem.
