### ISSUE TITLE
Appium and cucumber 2.0.1

### ISSUE THREAD

**Issue by ericzered** [appium/appium#5887]
Hello,
SInce I've updated cucumber to 2.0.1 (https://github.com/cucumber/cucumber-ruby/blob/master/History.md) I have an error for all my appium scenarios at the end. Same for cucumber 2.0.2.
Now, after finishing my scenario, I've got in the console : 
(Selenium::WebDriver::Error::NoSuchDriverError)
/Users/mycomputer/.rvm/gems/ruby-2.2.1/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
/Users/mycomputer/.rvm/gems/ruby-2.2.1/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/Users/mycomputer/.rvm/gems/ruby-2.2.1/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
/Users/mycomputer/.rvm/gems/ruby-2.2.1/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
/Users/mycomputer/.rvm/gems/ruby-2.2.1/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
/Users/mycomputer/.rvm/gems/ruby-2.2.1/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/Users/mycomputer/.rvm/gems/ruby-2.2.1/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:664:in `raw_execute'
/Users/mycomputer/.rvm/gems/ruby-2.2.1/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:642:in `execute'
/Users/mycomputer/.rvm/gems/ruby-2.2.1/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:201:in `getPageSource'
/Users/mycomputer/.rvm/gems/ruby-2.2.1/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/driver.rb:163:in `page_source'

And I see in Appium logs 2 lines at the end I've never add with cucumber 2.0.0

info: --> GET /wd/hub/session/2ac2334b-112e-4505-9b94-4163b311e0d0/source {}
info: <-- GET /wd/hub/session/2ac2334b-112e-4505-9b94-4163b311e0d0/source 404 0.576 ms - 40

You can see the difference for the exact same script, this is the end of the appium logs, where the error appear with cucumber 2.0.1 : 
http://img11.hostingpics.net/pics/790568appiumcucumber.jpg

**Comment by SrinivasanTarget** [comment]
Please try a latest version of appium and raise a new issue along with logs incase if you hit the same. Also following our issue template will help us understood more further.

**Comment by SrinivasanTarget** [comment]
@triager please close
