### ISSUE TITLE
session timeout breaks appium clients

### ISSUE THREAD

**Issue by yahman72** [appium/appium#5888]
The client (python in my case) fails with KeyError, there's no "error" key in the response dictionary.
I.e. the client tries to look for an error element in the response although appium responds with "404" HTTP error code (according to appium logs)
I guess this is applicable for all clients (not only python) since the exception comes from selenium package (see below).

To throw an error is this scenario is expected, but it should be managed somehow e.g. so that the client side shows an human-readable error message (e.g. "Unknown Session Id")

<pre>
  File "C:\Python27\lib\site-packages\appium\webdriver\webdriver.py", line 382, in press_keycode
    self.execute(Command.PRESS_KEYCODE, data)
  File "C:\Python27\lib\site-packages\selenium-2.48.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  File "C:\Python27\lib\site-packages\selenium-2.48.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 103, in check_response
    status = value['error']
</pre>

appium logs
<pre>
info: <-- POST /wd/hub/session/1c948c97-4984-42d2-b4bc-3a4be1d99a4a/appium/device/press_keycode 200 34.335 ms - 76 {"status":0,"value":true,"sessionId":"1c948c97-4984-42d2-b4bc-3a4be1d99a4a"}
info: [debug] Didn't get a new command in 90 secs, shutting down...
info: Shutting down appium session
...
info: [debug] We shut down because no new commands came in
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: --> POST /wd/hub/session/1c948c97-4984-42d2-b4bc-3a4be1d99a4a/appium/device/press_keycode {"sessionId":"1c948c97-4984-42d2-b4bc-3a4be1d99a4a","keycode":"6"}
info: <-- POST /wd/hub/session/1c948c97-4984-42d2-b4bc-3a4be1d99a4a/appium/device/press_keycode 404 1.827 ms - 40 
</pre>

**Comment by SrinivasanTarget** [comment]
Please try a latest version of appium and raise a new issue along with logs incase if you hit the same.

**Comment by SrinivasanTarget** [comment]
@triager please close
