### ISSUE TITLE
Can't interact with custom widgets on android

### ISSUE THREAD

**Issue by itamar6587** [appium/appium#5895]
Hi,

I’m trying to interact through appium with a custom made widget, that is built as a LinerLayout that wraps an EditText. The LinearLayout adds the EditText progromaticlly. Appium inspector shows the LinearLayout as an editText and for that i am not able to interact with the editText inside the LinearLayout. 

In the photo you can see the custom widget selected, and that appium recognizes it as an EditText. 

Any Idea how to interact with custom made widgets?

![screen shot 2015-12-02 at 3 31 08 pm](https://cloud.githubusercontent.com/assets/15959580/11532194/ef9caa20-990a-11e5-8a81-c03e7bb34e03.png)

**Comment by Jonahss** [comment]
Hrm. Not sure :(
Maybe somebody else has experience with this? @bootstraponline @simonk

**Comment by bootstraponline** [comment]
I remember something about uiautomator v1 not allowing custom widgets. selendroid should work.

**Comment by itamar6587** [comment]
Thanks, eventually i switched to an google widget..
