### ISSUE TITLE
1.5-beta not registering with Selenium Grid v2.45.0

### ISSUE THREAD

**Issue by whopiecat** [appium/appium#5902]
Hello:

I am not able to register a node to the Grid with Appium v1.5.0-beta7.
I can run tests (very slowly), by connecting to the port, but do not see the node register with the Grid.

I do not see the log message of "starting auto register thread for grid."

Are the Selenium Grid features implemented in this1.5 beta?

Appium v1.5.0-beta7
Selenium v.2.45.0

Thanks

**Comment by Jonahss** [comment]
We designed it to work, so you may have helped us find a bug.
Could you retry with the latest 1.5 beta?

**Comment by whopiecat** [comment]
Thanks for the info.

I installed the 1.5 Beta 8 version.
When the Selenium Grid is running and a mobile device is registered.

Appium node log displays 
[Appium] Request to register with grid was unsuccessful: Request failed

Selenium Grid log displays
Registered a node [address]

Selenium Grid Console displays
mobile device icon  (as expected for a mobile device registered with Grid)

I am using:
Appium 1.5 Beta 8
Selenium 2.48.2

Thanks

**Comment by Lightmoor** [comment]
I have the same problem with Selenium 2.47.1

**Comment by Lightmoor** [comment]
I have some logs for you


java -jar selenium-server-standalone-2.48.2.jar -role hub -hubConfig hubconfigMini.json -port 4445
13:27:53.185 INFO - Launching Selenium Grid hub
2015-12-21 13:27:53.823:INFO::main: Logging initialized @795ms
13:27:53.835 INFO - Will listen on 4445
13:27:53.894 INFO - Will listen on 4445
2015-12-21 13:27:53.897:INFO:osjs.Server:main: jetty-9.2.z-SNAPSHOT
2015-12-21 13:27:53.927:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@76f2b07d{/,null,AVAILABLE}
2015-12-21 13:27:53.955:INFO:osjs.ServerConnector:main: Started ServerConnector@4b553d26{HTTP/1.1}{0.0.0.0:4445}
2015-12-21 13:27:53.956:INFO:osjs.Server:main: Started @928ms
13:27:53.957 INFO - Nodes should register to http://10.90.167.137:4445/grid/register/
13:27:53.957 INFO - Selenium Grid hub is up and running
13:28:07.547 INFO - Registered a node http://0.0.0.0:4723
13:28:12.481 INFO - Registered a node http://0.0.0.0:4723
13:28:12.482 WARN - Cleaning up stale test sessions on the unregistered node http://0.0.0.0:4723
13:28:17.454 INFO - Registered a node http://0.0.0.0:4723
13:28:17.455 WARN - Cleaning up stale test sessions on the unregistered node http://0.0.0.0:4723
13:28:22.462 INFO - Registered a node http://0.0.0.0:4723
13:28:22.463 WARN - Cleaning up stale test sessions on the unregistered node http://0.0.0.0:4723
13:28:27.468 INFO - Registered a node http://0.0.0.0:4723
13:28:27.469 WARN - Cleaning up stale test sessions on the unregistered node http://0.0.0.0:4723
13:28:32.485 INFO - Registered a node http://0.0.0.0:4723
13:28:32.485 WARN - Cleaning up stale test sessions on the unregistered node http://0.0.0.0:4723
13:28:37.493 INFO - Registered a node http://0.0.0.0:4723
13:28:37.493 WARN - Cleaning up stale test sessions on the unregistered node http://0.0.0.0:4723





node . --nodeconfig /Users/ottoqs/mobiletest/nodeconfigs/IOS8mini.json --session-override --log-level debug
[debug] [Appium] Starting auto register thread for grid. Will try to register every 5000 ms.
[Appium] Welcome to Appium v1.5.0-beta9 (REV e7f89e43705060a0bfb122765ea141844861dfd3)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Non-default server args:
[Appium]     sessionOverride: true
[Appium]     nodeconfig: /Users/ottoqs/mobiletest/nodeconfigs/IOS8mini.json
[Appium] Request to register with grid was unsuccessful: Request failed
[debug] [Appium] Hub down or not responding: ${err.message}
[Appium] Request to register with grid was unsuccessful: Request failed
[debug] [Appium] Hub down or not responding: ${err.message}
[Appium] Request to register with grid was unsuccessful: Request failed
[debug] [Appium] Hub down or not responding: ${err.message}
[Appium] Request to register with grid was unsuccessful: Request failed
[HTTP] --> GET /wd/hub/status 
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: null
[HTTP] <-- GET /wd/hub/status 200 13.008 ms - 42 
[debug] [Appium] Hub down or not responding: ${err.message}
[HTTP] --> GET /wd/hub/status 
[Appium] Request to register with grid was unsuccessful: Request failed
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: null
[HTTP] <-- GET /wd/hub/status 200 5.973 ms - 42 
[debug] [Appium] Hub down or not responding: ${err.message}
[HTTP] --> GET /wd/hub/status 
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: null
[HTTP] <-- GET /wd/hub/status 200 5.168 ms - 42 
[Appium] Request to register with grid was unsuccessful: Request failed
[debug] [Appium] Hub down or not responding: ${err.message}
[HTTP] --> GET /wd/hub/status 

nodeconfig (IOS8mini.json)
{
  "capabilities":
      [
        {
          "browserName": "Safari",
          "version":"8.4",
          "maxInstances": 1,
          "platform":"MAC"
        }
      ],
  "configuration":
  {
    "cleanUpCycle":2000,
    "timeout":30000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "host": "127.0.0.1",
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4445,
    "hubHost": "127.0.0.1",
    "deviceNameOtto": "IPhone51"
  }
}


The Selenium Console shows the device see screenshot

![bildschirmfoto 2015-12-21 um 13 34 21](https://cloud.githubusercontent.com/assets/4245019/11933254/18e02c00-a7fb-11e5-8da3-10449d7c06f9.png)

I use the same configurations as in Appium 1.4.16. In Appium 1.4.16 it works fine.

**Comment by Jonahss** [comment]
@jlipps this is a bug with appium 1.5. We should have it support selenium grid same as 1.4.16.

**Comment by jlipps** [comment]
yes, I agree

**Comment by whopiecat** [comment]
Is there an update on appium 1.5 registering with the Selenium Grid?

**Comment by jlipps** [comment]
I believe one of @imurchie, @Jonahss, or @scottdixon was going to work on this

**Comment by whopiecat** [comment]
Thanks for the update.

**Comment by scottdixon** [comment]
@whopiecat: this should now be resolved - please confirm (you'll need to pull a fresh copy of appium from source or wait for the next beta release).

**Comment by whopiecat** [comment]
Installed 1.5.0-beta11.
Does register with the Selenium Grid and displays in Selenium Grid Console as expected.
Thanks
