### ISSUE TITLE
SendKeys not working with UIAPickerWheel

### ISSUE THREAD

**Issue by ankit154** [appium/appium#5905]
```
Driver.FindElementByClassName("UIAPickerWheel").SendKeys(value)
```

I'm using the above code to change the picker's value. However instead of changing to the given value, the picker gets scrolled by one element and then the instruments crashes with the following error

<i><b>Responding to client with error: {"status":17,"value":{"message":"An error occurred while executing user supplied JavaScript.","origValue":"Unexpected error in -[UIAPickerWheel_0x124e5e3f0 _spinWheel:], /SourceCache/UIAutomation/UIAutomation-430/Framework/UIAItemElements.m line 358, kAXErrorInvalidUIElement"},"sessionId":"780043e0-85b9-41b8-be69-76340ddc62b6"}</i></b>  

Env: 
Appium: 1.4.13 + XCode: 7.0 + iOS: 9.0

I've attached the error log. Any help regarding this.

log.txt](https://github.com/appium/appium/files/55450/log.txt)

<i>PS:  I'm using  Appium DotNet Driver </i>

**Comment by kcinman11358** [comment]
I am able interact with our UIAPickerWheel just fine with APpium 1.4.13, XCode 7, and iOS 9.2

Couple of suggestions, just for satiety
1) Debug the test and make sure that Driver.FindElementByClassName("UIAPickerWheel").Count is greater than 0
2) If there are multiple UIAPickerWheels, make sure you are specifying it with by Driver.FindElementByClassName("UIAPickerWheel").ElementAt(x).SendKeys, where x is the UIAPickerWheel you want
3) Make sure the element is enabled. You can do this by inspecting the element with Appium.

Let me know if this helps

**Comment by ankit154** [comment]
@kcinman11358 : Still stuck with the problem. 

>1) Debug the test and make sure that Driver.FindElementByClassName("UIAPickerWheel").Count is greater than 0

 Yes its greater than 0.

>2) If there are multiple UIAPickerWheels, make sure you are specifying it with by Driver.FindElementByClassName("UIAPickerWheel").ElementAt(x).SendKeys, where x is the UIAPickerWheel you want

There's a single pickerwheel
>3) Make sure the element is enabled. You can do this by inspecting the element with Appium.

Yes, its enabled. I'm getting the same problem using sendKeys on the wheel via inspector GUI too.

**Comment by ankit154** [comment]
Ok I found a hack of making it work. Though I really don't like this approach and would like sendKeys to work straightaway, it seems to be the only way for me right now:

    string temp = string.Empty;
    while (temp != value){
    try {
      Driver.FindElementByClassName ("UIAPickerWheel").SendKeys (value);
    }
    catch{
      //Do Nothing
    }
    finally {
      temp = Driver.FindElementByClassName ("UIAPickerWheel").GetAttribute ("value");
    }}

**Comment by kcinman11358** [comment]
Interesting. I am still able to get mine to work. Another suggestion: upgrade to xcode 7.2. Maybe something fixed it in there. Here is my code:
 protected IWebElement GetElement(By by)
        {
            WebDriverWait wait = new WebDriverWait(_driver, new TimeSpan(0, 0, 90));
            wait.Until(ExpectedConditions.ElementExists(by));
            return _driver.FindElement(by);
        }
 public void Select(string account)
           {
                GetElement(By.ClassName("UIAPickerWheel")).SendKeys(account);
            }

**Comment by kcinman11358** [comment]
How many times does your loop go through before it sends the keys?

**Comment by ankit154** [comment]
Even I'm thinking its  got to do something with the xcode and iOS versions being used. Will be doing that upgrade over the weekend.

>How many times does your loop go through before it sends the keys?

(n-1) times for sending keys for the nth item in the wheel.
