### ISSUE TITLE
appium 1.4.16 > current github master > ./reset.sh yields  Error: Cannot find module 'appium-instruments'

### ISSUE THREAD

**Issue by shermanericSF** [appium/appium#5907]
**Environment**
* Appium 1.4.16
* checked out code from https://github.com/appium/appium/ master branch as of 2015-12-09 @9:16 AM PST

**Steps to Reproduce**

1.  Go to the appium checked out repository on your local machine
2.  ./reset.sh --dev --ios --verbose

Expected:  The reset works as expected.
Actual:  The reset fails.  Reason
```
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'appium-instruments'
```

**Note**
* Full gist is here: https://gist.github.com/shermanericSF/008635ebf7b42b086bf1
*Other problems around this error center around Appium.dmg. I am not using that.  My symlinks in node_modules seem correct.

Let me know if you need any other information.
Thanks!

**Comment by Jonahss** [comment]
We hope to solve your issue by publishing appium version 1.5 ;)
Is that ok?
You can check it out now on the `1.5` branch.

**Comment by shermanericSF** [comment]
Hi @Jonahss - totally fine.  :)
I'll check out the 1.5 branch here shortly.
Thanks!
