### ISSUE TITLE
Methods for rotation to reverse portrait and reverse landscape are missing

### ISSUE THREAD

**Issue by yasmin09** [appium/appium#5911]
There is no way to rotate native app into reverse portrait or reverse landscape view.

Currently, I am using Selenium method to rotate to portrait and landscape (always right landscape).

I am using ->
((Rotatable)driver).rotate(ScreenOrientation.PORTRAIT);
((Rotatable)driver).rotate(ScreenOrientation.LANDSCAPE);

I want to rotate native app to REVERSE_PORTRAIT and REVERSE_LANDSCAPE but as I can see that is not supported.

**Comment by Jonahss** [comment]
Ah yes. We should implement those. Adding as a feature request.

**Comment by SrinivasanTarget** [comment]
@Jonahss Does this be implemented in appium or in selenium?

**Comment by mykola-mokhnach** [comment]
WDA supports the endpoint for rotation settings. Supported rotation values:

```
          @(UIDeviceOrientationUnknown) : @{@"x" : @(-1), @"y" : @(-1), @"z" : @(-1)},
          @(UIDeviceOrientationPortrait) : @{@"x" : @(0), @"y" : @(0), @"z" : @(0)},
          @(UIDeviceOrientationPortraitUpsideDown) : @{@"x" : @(0), @"y" : @(0), @"z" : @(180)},
          @(UIDeviceOrientationLandscapeLeft) : @{@"x" : @(0), @"y" : @(0), @"z" : @(270)},
          @(UIDeviceOrientationLandscapeRight) : @{@"x" : @(0), @"y" : @(0), @"z" : @(90)},
          @(UIDeviceOrientationFaceUp) : @{@"x" : @(90), @"y" : @(0), @"z" : @(0)},
          @(UIDeviceOrientationFaceDown) : @{@"x" : @(270), @"y" : @(0), @"z" : @(0)},
```
