### ISSUE TITLE
Appium 1.4.16 throwing error"Could not find a device to launch...." for iphone

### ISSUE THREAD

**Issue by AppiumUserForMobile** [appium/appium#5912]
I am getting this exception on 1.4.13, 1.4.15 and 1.4.16 . The same code and phone works on appium 1.3.7 dmg . Is this a bug in appium? If so, what is the workaround ?

info: Client User-Agent string: Apache-HttpClient/4.4.1 (Java/1.8.0_60)
info: [debug] Configuring Safari session
info: [debug] Creating new appium session 65f69586-5329-40da-ae1c-9170705028c9
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version
info: [debug] Xcode version set to 7.2
info: [debug] Setting iOS SDK Version
info: [debug] iOS SDK Version set to 9.2
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
error: Failed getting devices. Err: Error: Command failed: /bin/sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments' -s devices
2015-12-10 15:54:28.667 instruments[27863:703111] WebKit Threading Violation - initial use of WebKit from a secondary thread.
. Stdout: Known Devices:
. Stderr: 2015-12-10 15:54:28.667 instruments[27863:703111] WebKit Threading Violation - initial use of WebKit from a secondary thread.
.
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.2","iOSSDKVersion":"9.2","deviceName":"iPhone","platformVersion":null}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone (9.2)'
error: Could not find a device to launch. You requested 'iPhone (9.2)', but the available devices were: ["iPad 2 (9.2) [87C99C1B-00BD-4B9D-BD4D-46E04E44AF8D]","iPad Air (9.2) [59A77AE1-97F9-4F5C-9F7B-18342CDA59EE]","iPad Air 2 (9.2) [BBD6907C-A5BF-4D80-AA81-D42B83C7BB80]","iPad Pro (9.2) [DF4A5DDB-2991-4FDE-8A2C-7FFBF78A8F7F]","iPad Retina (9.2) [AD5E7593-A794-464B-B843-BA0458EBC18A]","iPhone 4s (9.2) [4BDDD7EF-9F34-4DD2-814F-C67B793623E5]","iPhone 5 (9.2) [CBAF481D-4E07-4DC2-946C-1D421A7B0F14]","iPhone 5s (9.2) [AA1F9EF7-32D4-427A-B06D-64475D550380]","iPhone 6 (9.2) [9880AA55-0A0C-4D8D-BF47-3EA4C9ED1DD8]","iPhone 6 Plus (9.2) [D6A067C9-929A-48C7-8F3D-9E9A8E0551B6]","iPhone 6s (9.2) [9AD26211-6BDD-447F-AD61-DE4C9247EE47]","iPhone 6s (9.2) + Apple Watch - 38mm (2.1) [0422BCA6-0DFC-4661-84C4-4483A805D9E2]","iPhone 6s Plus (9.2) [4E026632-C71F-423C-958F-8825C60BBF29]","iPhone 6s Plus (9.2) + Apple Watch - 42mm (2.1) [F58DCD5D-ABE2-4141-B4D9-655338CD7FD2]"]
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not find a device to launch. You requested 'iPhone (9.2)', but the available devices were: ["iPad 2 (9.2) [87C99C1B-00BD-4B9D-BD4D-46E04E44AF8D]","iPad Air (9.2) [59A77AE1-97F9-4F5C-9F7B-18342CDA59EE]","iPad Air 2 (9.2) [BBD6907C-A5BF-4D80-AA81-D42B83C7BB80]","iPad Pro (9.2) [DF4A5DDB-2991-4FDE-8A2C-7FFBF78A8F7F]","iPad Retina (9.2) [AD5E7593-A794-464B-B843-BA0458EBC18A]","iPhone 4s (9.2) [4BDDD7EF-9F34-4DD2-814F-C67B793623E5]","iPhone 5 (9.2) [CBAF481D-4E07-4DC2-946C-1D421A7B0F14]","iPhone 5s (9.2) [AA1F9EF7-32D4-427A-B06D-64475D550380]","iPhone 6 (9.2) [9880AA55-0A0C-4D8D-BF47-3EA4C9ED1DD8]","iPhone 6 Plus (9.2) [D6A067C9-929A-48C7-8F3D-9E9A8E0551B6]","iPhone 6s (9.2) [9AD26211-6BDD-447F-AD61-DE4C9247EE47]","iPhone 6s (9.2) + Apple Watch - 38mm (2.1) [0422BCA6-0DFC-4661-84C4-4483A805D9E2]","iPhone 6s Plus (9.2) [4E026632-C71F-423C-958F-8825C60BBF29]","iPhone 6s Plus (9.2) + Apple Watch - 42mm (2.1) [F58DCD5D-ABE2-4141-B4D9-655338CD7FD2]"]
info: [debug] Error: Could not find a device to launch. You requested 'iPhone (9.2)', but the available devices were: ["iPad 2 (9.2) [87C99C1B-00BD-4B9D-BD4D-46E04E44AF8D]","iPad Air (9.2) [59A77AE1-97F9-4F5C-9F7B-18342CDA59EE]","iPad Air 2 (9.2) [BBD6907C-A5BF-4D80-AA81-D42B83C7BB80]","iPad Pro (9.2) [DF4A5DDB-2991-4FDE-8A2C-7FFBF78A8F7F]","iPad Retina (9.2) [AD5E7593-A794-464B-B843-BA0458EBC18A]","iPhone 4s (9.2) [4BDDD7EF-9F34-4DD2-814F-C67B793623E5]","iPhone 5 (9.2) [CBAF481D-4E07-4DC2-946C-1D421A7B0F14]","iPhone 5s (9.2) [AA1F9EF7-32D4-427A-B06D-64475D550380]","iPhone 6 (9.2) [9880AA55-0A0C-4D8D-BF47-3EA4C9ED1DD8]","iPhone 6 Plus (9.2) [D6A067C9-929A-48C7-8F3D-9E9A8E0551B6]","iPhone 6s (9.2) [9AD26211-6BDD-447F-AD61-DE4C9247EE47]","iPhone 6s (9.2) + Apple Watch - 38mm (2.1) [0422BCA6-0DFC-4661-84C4-4483A805D9E2]","iPhone 6s Plus (9.2) [4E026632-C71F-423C-958F-8825C60BBF29]","iPhone 6s Plus (9.2) + Apple Watch - 42mm (2.1) [F58DCD5D-ABE2-4141-B4D9-655338CD7FD2]"]
    at noDevicesError (/usr/local/avm/versions/1.4.16/node_modules/appium/lib/devices/ios/ios.js:1143:10)
    at [object Object].<anonymous> (/usr/local/avm/versions/1.4.16/node_modules/appium/lib/devices/ios/ios.js:1149:16)
    at /usr/local/avm/versions/1.4.16/node_modules/appium/node_modules/async/lib/async.js:522:46
    at /usr/local/avm/versions/1.4.16/node_modules/appium/node_modules/async/lib/async.js:251:17
    at /usr/local/avm/versions/1.4.16/node_modules/appium/node_modules/async/lib/async.js:148:21
    at /usr/local/avm/versions/1.4.16/node_modules/appium/node_modules/async/lib/async.js:248:21
    at /usr/local/avm/versions/1.4.16/node_modules/appium/node_modules/async/lib/async.js:612:34
    at /usr/local/avm/versions/1.4.16/node_modules/appium/node_modules/async/lib/async.js:513:25
    at /usr/local/avm/versions/1.4.16/node_modules/appium/node_modules/appium-instruments/lib/instruments.js:119:7
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by kcinman11358** [comment]
Can you provide your capabilities list please?

**Comment by AppiumUserForMobile** [comment]
I am able to get over this error. Providing the DeviceName as 'iPhone 6 Plus' helped.

**Comment by kcinman11358** [comment]
Awesome. I was just going to suggest this :)

Make sure a deviceName is also specified when doing Android testing.

Please close the issue, thanks
