### ISSUE TITLE
Eventually, Safari tab crashes in iOS web test

### ISSUE THREAD

**Issue by crummy** [appium/appium#5913]
I have quite a long test (an hour or so) on iOS, and eventually the Safari tab crashes with this message appearing at the top of my tab: "A problem occurred with this web page, so it was reloaded." I understand this isn't really an Appium bug, but I'm looking for ideas of how to handle it - perhaps Appium could detect this state and reconnect?

I'm using Appium 1.4.16 with the included ios-webkit-debug-proxy. My test cases visits hundreds of websites, taking a screenshot of each. I can a few hundred successfully until I experience this failure, not always on the same site.

I've reproduced this on an iPhone 6S Plus and iPad Pro, with a test that just visits many websites, and with a test that just takes many screenshots. It seems that after a long enough time in a test, the Safari tab crashes.

The tail of my Appium log is here:
https://gist.github.com/crummy/f546f89fd0ec25c6ca14
I don't see any crash logs in Xcode's device inspector.

**Comment by Jonahss** [comment]
Hm interesting.
I know you probably have a reason why you can't do this, but one option is to end the test after n tests (for some positive number n), and start a new test.
Sure it will add ~30-60 seconds for each reset, but won't crash.

You can also try to use appium version 1.5 (check out `1.5` branch). Performance might be better there, plus you can help us beta test ^.^

**Comment by crummy** [comment]
Yes, that's what I've been reduced to doing but for various reasons I'd prefer not to.

After Christmas I should get a chance to try Appium 1.5 and will report back if this helps.

Safari sometimes gets into a state where it appears every web page load crashes Safari, not just during a web test. Closing Safari or rebooting the phone seems to resolve it. I'm wondering if I need to reboot the device between tests too, just to guarantee stability...

**Comment by dpgraham** [comment]
Closing this because it's related to an old version of Appium. If this issue returns please leave a comment.
