### ISSUE TITLE
Appium Inspector Issue.

### ISSUE THREAD

**Issue by petesanchez3** [appium/appium#5914]
![20151211_213522](https://cloud.githubusercontent.com/assets/16264242/11760480/4b2d8500-a052-11e5-8f3e-d70035757ecb.jpg)

Having an issue setting up my appium correctly. I launch it which works well. Than I click on inspector and get the error in screenshot. 

Please help. 

Pete

**Comment by kcinman11358** [comment]
Just to help troubleshoot this a little better, can you take a screenshot of the configuration settings as well as the advanced settings?

Also, are you using simulators or real devices?

**Comment by petesanchez3** [comment]
![screen shot 2015-12-12 at 11 48 36 am](https://cloud.githubusercontent.com/assets/16264242/11763611/c978281a-a0c6-11e5-9103-2a64a65cca18.png)
![screenshot 2015-12-12 11 50 41](https://cloud.githubusercontent.com/assets/16264242/11763612/c979431c-a0c6-11e5-8b20-70bc73c9bce0.png)

Using REAL DEVICE

**Comment by petesanchez3** [comment]
![screen shot 2015-12-12 at 11 48 36 am](https://cloud.githubusercontent.com/assets/16264242/11763616/f3af0c8e-a0c6-11e5-9fd3-af98684a17c3.png)
![screenshot 2015-12-12 11 50 41](https://cloud.githubusercontent.com/assets/16264242/11763617/f3b2bfaa-a0c6-11e5-8025-b32de94d5d2a.png)

**Comment by petesanchez3** [comment]
![screenshot 2015-12-12 11 52 53](https://cloud.githubusercontent.com/assets/16264242/11763618/02b16862-a0c7-11e5-85ed-c147b07a7eda.png)
![screenshot 2015-12-12 11 53 07](https://cloud.githubusercontent.com/assets/16264242/11763619/02b15e58-a0c7-11e5-85ff-3c8f3200b009.png)

**Comment by kcinman11358** [comment]
Hmm, everything is looking good so far. Are you specifying a .app or a .ipa?

**Comment by petesanchez3** [comment]
I am taking a class on appium on udemy.  The instructor said to use sample UIcatalogapp for this test.

**Comment by kcinman11358** [comment]
Is it pointing to the .app or .zip?
