### ISSUE TITLE
Jenkins: appium will not work if used or installed with sudo. 

### ISSUE THREAD

**Issue by Anishohri** [appium/appium#5921]
Hi

I uninstalled it and reinstalled node it couple of time using brew and then appium but still i am getting this error from jenkins "[31merror[39m: Appium will not work if used or installed with sudo. Please rerun/install as a non-root user. If you had to install Appium using `sudo npm install -g appium`, the solution is to reinstall Node using a method (Homebrew, for example) that doesn't require sudo to install global npm packages.
Build step 'Execute shell' marked build as failure"

It works fine from terminal though.

Any help would be appreciated.

**Comment by SrinivasanTarget** [comment]
@Anishohri  Uninstall node and install node without sudo command. i.e npm install appium -g

@Jonahss please close this ticket

**Comment by Anishohri** [comment]
@SrinivasanTarget 

That is very clear in the message that that appium displays, and not sure why would you think that i never tried it ?

If you may please read that i have already tried the steps you mentioned 3-4 times but its not working.

**Comment by SrinivasanTarget** [comment]
@Anishohri Hope this will help u. https://github.com/appium/appium/issues/2294

Is CI tries to install appium using sudo command?? or just trying to execute the appium server i.e command "appium" from CI??

**Comment by Anishohri** [comment]
@SrinivasanTarget 
People are still looking for answers on this thread #2294.

CI is trying to execute it as sudo because the same setup works fine from the terminal 
cmd for CI shell is -

cd /usr/local/lib/node_modules/appium/lib/server/
node main.js

**Comment by dpgraham** [comment]
Re-open if this is still error
