### ISSUE TITLE
Android bootstrap - Find by uiautomator strategy with classNameMatches returns partial results

### ISSUE THREAD

**Issue by romangoldstain** [appium/appium#5924]
Hello,

Let say I'm calling find() method with the following uiautomator strategy selector:
new UiSelector().classNameMatches("android.widget.ListView")

now, in my app, I have a layout with two ListViews. Both are positioned under different parents in the layout, so their both indexes (parent relative) are 0.

Now, I would expect that findElements() with the selector above, will result BOTH ListViews.
But, what happens actually, is that I get ONLY the first one.
(I know I can use the plain className() and it will work, but I really need the classNameMatches() here)

The code in AndroidElementsHash.getElement() keeps the search loop as long as UiObject with the given selector + counter was found.
in case of CLASS_REGEX, this method uses the UiObject.index, instead of the UiObject.instance.
And this is the problem, it's ok the expect the instance to keep increasing as long as the rest of the selector remains the same so the code will collect all the matching views, BUT this is not the case for index. As the index is parent relative, and not necessarily increasing.
Btw, if I move the second ListView under the same parent (so it's index is now 1), I'll get both ListViews.

Issue 2:
Now, If I use the following selector:

new UiSelector().classNameMatches("android.widget.ListView").instance(0)

I would expect to get both list upon the right instance param - 0/1.
BUT, this line in AndroidElementsHash.getElement() :
final boolean endsWithInstance = endsWithInstancePattern.matcher(selectorString).matches();

keeps settings endWithInstance var to false, since the INSTANCE field is the FIRST (not the last) in the selector's string (as created by the UiAutomatorParser).

Thanks,
Roman

**Comment by scottdixon** [comment]
Can you post some example failing test code?

**Comment by romangoldstain** [comment]
Sorry for the delay,

So - 
this is my layout:
LinearLayout (index = whatever)
   EditText  (index = 0)
   Button (index = 1)

EditText and a Button under linear layout.

If I run the following 'find' command with uiautomator strategy:

{"action":"find","cmd":"action","params":{"context":"","selector":"new UiSelector().**classNameMatches**(\"android.widget.Button\")","multiple":true,"strategy":"-android uiautomator"}}

I will get NO results. although I have 3 buttons in the layout.
If I'll change the 'classNameMatches' into 'className' I'll get all the buttons, as expected.


Now, the source for this unwanted behavior can be found inside AndroidElementHash.java:

this line:
_final boolean useIndex = selectorString.contains("CLASS_REGEX=");_
causes the search loop to use index (and not instance).
for this example, there is no button with index 0 (button's index is 1), so the loop will break right after the very first lookup failure.

My question is why using 'index' for loop's selector if CLASS_REGEX was detected?
Using 'instance' (by making useIndex false), just like for every other case worked fine here. But, I guess there is a reason for this, right?


Thanks,
Roman.

**Comment by jlipps** [comment]
@romangoldstain to be honest I am not sure why we have this option of setting `useIndex` when we are doing a class regex match. Unfortunately the project moved so git history doesn't tell us anything interesting. Have you tried making the change to remove `useIndex`? Are there any side effects? If our tests pass with this change, we'd accept a PR to this effect.

**Comment by jlipps** [comment]
going to close this for now, particularly because we're putting continued effort into the uiauto2 driver, not the uiauto1 driver.
