### ISSUE TITLE
Parallel run of appium scripts on two iOS devices on single MAC using appium

### ISSUE THREAD

**Issue by rgupta95** [appium/appium#5925]
Hi All,

I am new to appium grid and trying to create appium grid with two iOS devices on single MAC.Is it possible ?

1.Started the selenium hub on MAC .but when it comes to create a node , i created one nodeconfig.json file and put it on eclipse and added to the appium.exe .

2.When i am pasting the below command from cmd on MAC :
appium -a 172.22.1.124 -p 4723  --bp 4726 -U 103724f39571a32711908eb180b8cde8307b6e19 --nodeconfig /Users/ranjangupta/Documents/workspace/MCKINSEY_IPAD/MCK_nodeconfig.json

getting error message like appium command not found.

I have appium installed on my system and i run script on it .

Please suggest if can we run parallel script on single MAC with above configuration .

Waiting for positive response soon .

Thanks,
Ranjan Gupta

**Comment by SrinivasanTarget** [comment]
@rgupta95 Only one instrument session can be active at a time and it's not an appium limitation. Thats how apple have designed it. Parallel execution is possible only in android devices.

@jlipps please close this ticket.

**Comment by kcinman11358** [comment]
While what @SrinivasanTarget is true, you could look into Selenium Grid. I haven't played with it myself, but it is worth a shot

**Comment by priyankshah217** [comment]
@rgupta95 @SrinivasanTarget you can run two IOS devices parallel. to do this you need to provide additional parameter of tmp directory while launching appium server.

.node -p 6001 -U <Device1> --tmp /temp/dir1 &
.node -p 6002 -U <Device2> --tmp /temp/dir2 &

so you can try with grid also.

Thanks,
Priyank Shah

**Comment by SrinivasanTarget** [comment]
yup @priyankshah217 Able to execute across two real ios devices parallely now. Thanks @priyankshah217

**Comment by priyankshah217** [comment]
@rgupta95 , can you please close this issue?

**Comment by saikrishna321** [comment]
@SrinivasanTarget havent you notice that appium kills instruments when starting a new session ? kill Instruments ..

**Comment by saikrishna321** [comment]
@priyankshah217 @SrinivasanTarget https://github.com/appium/appium-instruments/blob/f0a125ddb5a1c42cc82b8ae9621df6b98f778e14/lib/instruments.js#L94

**Comment by rompic** [comment]
would be interesting how uber does it : https://www.youtube.com/watch?v=p6gsssppeT0&feature=youtu.be&list=PLSIUOFhnxEiCWGsN9t5A-XOhRbmz54IS1&t=730

**Comment by scottdixon** [comment]
Looks like this is resolved. Let me know if otherwise.

**Comment by rgupta7888** [comment]
I would like to make the issue open as i am trying to run script on two ioS real devices on single mac with appium 1.6 . When i am trying to run the below command to connect node to the hub i am getting issue "java.lang.IllegalStateException: Not a JSON Object: null" server error on "http://192.168.0.101:4444/grid/register/" . Please suggest .

node appium.js -bp 5557 –port 5555 –udid 437593bb0b56b28071b0b8287b2c6844f680178c –nodeconfig /Users/cex/Downloads/iOSGrid/iPhone6.json –command-timeout “7200” –session-override –debug-log-spacing –log “/Users/cex/Downloads/iOSGrid/iPhone6.log” –native-instruments-lib –tmp “/Users/cex/Downloads/iOSGrid/Device_iPhone6”
