### ISSUE TITLE
When an GUI application is support for 9.0.2 ?

### ISSUE THREAD

**Issue by axenovV** [appium/appium#5926]
Hello, When will support for 9.0.2 for os x?  Thanks.
<img width="266" alt="2015-12-16 15 55 00" src="https://cloud.githubusercontent.com/assets/9257530/11841328/9ebf03b0-a40d-11e5-8d79-d9117e889bb4.png">

**Comment by SrinivasanTarget** [comment]
@axenovV It does supports iOS 9 or 9+ real devices whereas the listing has issues in UI. We will get issues when we attempt to execute on iOS 9 simulators

**Comment by kcinman11358** [comment]
In the meantime, you can manually type in the Platform version you want for the simulator and it will work

**Comment by scottdixon** [comment]
Appium 1.4.11+ supports iOS9 - you can request additional iOS versions in the GUI by creating an issue in https://github.com/appium/appium-dot-app
