### ISSUE TITLE
Appium GUI doesn't list iOS 9 or 9+ simulators 

### ISSUE THREAD

**Issue by SrinivasanTarget** [appium/appium#5927]
Appium GUI doesnt list my iOS 9 or 9+ devices whereas isntruments -s devices list down iOS 9 simulators as well.
Appium GUI version: 1.4.13
<img width="1415" alt="screen shot 2015-12-16 at 8 55 15 pm" src="https://cloud.githubusercontent.com/assets/8896549/11844975/81e4d2ea-a437-11e5-8853-e7950afd56f8.png">

**Comment by kcinman11358** [comment]
While it doesn't list them, you can manually type in the Platform version you want and it will work

**Comment by scottdixon** [comment]
You can request newer versions be creating an issue in https://github.com/appium/appium-dot-app
