### ISSUE TITLE
Cannot access elements in NATIVE_APP view when running appium in selendroid mode

### ISSUE THREAD

**Issue by hardik-d** [appium/appium#5928]
code that fails:

set_context "NATIVE_APP"
within_context('NATIVE_APP') do
      @driver.find_element(:xpath, '//*[@name="SIGN UP ."]').click
end

capabilities:

caps: {
        platformName: 'Android',
        platformVersion: '5.0',
        deviceName: 'Android',
        automationName: 'Selendroid',
        app: '/Users/hardik/android-pnminc-dev-debug.apk',
    }

started appium using:

appium --automation-name Selendroid
info: Welcome to Appium v1.4.16 (REV d11c15a516f16d20c77ccc8e1d501957fb65d9eb)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"automationName":"Selendroid"}
info: Console LogLevel: debug

Emulator: Nexus_5_API_21_x86 API Level 21

Appium logs:

info: [debug] executing cmd: /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "am instrument -e main_activity 'com.paynearme.android.pnmc.MobileConsumer' com.paynearme.consumer.dev.selendroid/io.selendroid.server.ServerInstrumentation"
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/status","method":"GET"}
info: [debug] Selendroid server is alive!
info: [debug] Listening for Selendroid logs
info: [debug] Creating Selendroid session
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session","method":"POST","json":{"desiredCapabilities":{"warnings":{},"desired":{"platformName":"Android","platformVersion":"5.0","deviceName":"Android","automationName":"Selendroid","app":"/Users/hardik/android-pnminc-dev-debug.apk"},"platformName":"Android","platformVersion":"5.0","deviceName":"Android","automationName":"Selendroid","app":"/Users/hardik/android-pnminc-dev-debug.apk"}}}
info: [debug] Successfully started selendroid session
info: [debug] Waiting for pkg "com.paynearme.consumer.dev" and activity "com.paynearme.android.pnmc.MobileConsumer" to be focused
info: [debug] Getting focused package and activity
info: [debug] executing cmd: /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "dumpsys window windows"
info: [debug] Overriding session id with "d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7"
info: [debug] Device launched! Ready for commands
info: [debug] Setting command timeout to the default of 60 secs
info: [debug] Appium session started with sessionId d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7
info: <-- POST /wd/hub/session 303 6377.418 ms - 74 
info: --> GET /wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7 {}
info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7","method":"GET"}
info: [debug] Proxied response received with status 200: {"sessionId":"d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7","status":0,"value":{"warnings":{},"desired":{"platformName":"Android","platformVersion":"5.0","deviceName":"Android","automationName":"Selendroid","app":"/Users/hardik/android-pnminc-dev-debug.apk"},"platformName":"android","platformVersion":"21","deviceName":"Android","automationName":"selendroid","app":"/Users/hardik/android-pnminc-dev-debug.apk","takesScreenshot":true,"browserName":"selendroid","rotatable":true,"platform":"android","handlesAlerts":true,"javascriptEnabled":true,"networkConnectionEnabled":true,"version":"0.17.0","acceptSslCerts":true}}
info: <-- GET /wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7 200 13.836 ms - 611 
info: --> POST /wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7/timeouts/implicit_wait {"ms":0}
info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7/timeouts/implicit_wait","method":"POST","json":{"ms":0}}
info: [debug] Proxied response received with status 200: {"sessionId":"d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7","status":0,"value":""}
info: <-- POST /wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7/timeouts/implicit_wait 200 12.068 ms - 74 
info: --> POST /wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7/context {"name":"NATIVE_APP"}
info: [debug] Getting a list of available webviews
info: [debug] executing cmd: /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "cat /proc/net/unix"
info: [debug] WEBVIEW_3735 mapped to pid 3735
info: [debug] Getting process name for webview
info: [debug] executing cmd: /Users/hardik/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell "ps"
info: [debug] Parsed pid: 3735 pkg: com.paynearme.consumer.dev
info: [debug] from: u0_a58,3735,946,694320,96568,ffffffff,71fb860f,R,com.paynearme.consumer.dev
info: [debug] returning process name: com.paynearme.consumer.dev
info: [debug] Available contexts: undefined
info: [debug] ["WEBVIEW_com.paynearme.consumer.dev"]
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7/window_handles","method":"GET"}
info: [debug] Available contexts: ["WEBVIEW_0","NATIVE_APP"]
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7"}
info: <-- POST /wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7/context 200 92.858 ms - 76 {"status":0,"value":null,"sessionId":"d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7"}
info: --> POST /wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7/element {"using":"xpath","value":"//*[@name=\"SIGN UP .\"]"}
info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7/element","method":"POST","json":{"using":"xpath","value":"//*[@name=\"SIGN UP .\"]"}}
info: [debug] [SELENDROID] -1
info: [debug] [SELENDROID] -1
info: [debug] [SELENDROID] -1
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Did not successfully proxy server command"},"sessionId":"d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7"}
info: <-- POST /wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7/element 500 151.699 ms - 210 
info: --> GET /wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7/screenshot {}
info: [debug] Proxying command to localhost:8080
info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7/screenshot","method":"GET"}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Did not successfully proxy server command"},"sessionId":"d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7"}
info: <-- GET /wd/hub/session/d5bbcbcc-34a1-611a-b729-ab15c6a3aaf7/screenshot 500 3.659 ms - 210 

AppCrash log:

java.lang.ClassCastException: io.selendroid.server.model.AndroidNativeElement$WebViewSourceClient cannot be cast to org.apache.cordova.CordovaChromeClient
	at org.apache.cordova.CordovaWebView.setWebChromeClient(CordovaWebView.java:332)
	at io.selendroid.server.model.AndroidNativeElement$4.run(AndroidNativeElement.java:383)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5001)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by priyankshah217** [comment]
@hardik-d , can you please provide snippet of code for better understaning.

**Comment by hardik-d** [comment]
i did:

code that fails:

set_context "NATIVE_APP"
within_context('NATIVE_APP') do
@driver.find_element(:xpath, '//*[@name="SIGN UP ."]').click
end

**Comment by scottdixon** [comment]
@hardik-d - do you his the same issue with 1.5? `npm install -g appium`

**Comment by hardik-d** [comment]
this was prior to 1.5, and i am just using appium android now instead of selendroid. i think the issue was related to cordova apps support not sure if anything happened there. can close this
