### ISSUE TITLE
pipe --show-ios-log to separate file?

### ISSUE THREAD

**Issue by joshrlesch** [appium/appium#5930]
Is there a way to pipe just the ios device logs to a separate file when running tests with appium? The developers are asking for that info and its a little clustered when starting appium with `--show-ios-log` and piping all the appium logs to a file.

**Comment by scottdixon** [comment]
Not to my knowledge.

It would be reasonably straight forward to add, particularly in 1.5 - you might like to fork https://github.com/appium/appium-ios-log
