### ISSUE TITLE
Failed to start an Appium session, err was: Error: ENOENT on Windows 7

### ISSUE THREAD

**Issue by chanisasuw** [appium/appium#5934]
I have issue when appium connect with emulator 

Enviroments Setup:
1. Use Appium on Windows 7 
2. Appium latest version 1.4.16.1
3. Nodejs latest version
4. Android sdk and set up environment variables PATH: C:\Program Files (x86)\Android\android-sdk
5. Java set up JAVA_HOME: C:\Program Files (x86)\Java\jre1.8.0_51

So now i can connect emulator and when i clicked inspector to "Attempting to connect Appium"  and display "Failed to connect to the server. Please check that is it running"

and I see my log display below

> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"app":"C:\Users\Chanis4\Downloads\com.facebook.katana-v57.0.0.18.136-18629582-Android-4.0.3.apk","address":"127.0.0.1","fullReset":true,"logNoColors":true,"avd":"Addroid42","deviceName":"Addroid42","platformName":"Android","platformVersion":"17","automationName":"Appium","locale":"US"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"deviceName":"Addroid42","app":"C:\Users\Chanis4\Downloads\com.facebook.katana-v57.0.0.18.136-18629582-Android-4.0.3.apk","deviceReadyTimeout":"5","platformName":"Android"}}
> info: Client User-Agent string: undefined
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from desired caps: C:\Users\Chanis4\Downloads\com.facebook.katana-v57.0.0.18.136-18629582-Android-4.0.3.apk
> info: [debug] Creating new appium session 51e66bae-0f53-4ea4-82a5-82c35fd7bfe8
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_65
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe
> info: [debug] Parsing package and activity from app manifest
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Program Files (x86)\Android\android-sdk\build-tools\android-4.4W\aapt.exe
> info: [debug] Extracting package and launch activity from manifest.
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\build-tools\android-4.4W\aapt.exe" dump badging C:\Users\Chanis4\Downloads\com.facebook.katana-v57.0.0.18.136-18629582-Android-4.0.3.apk
> info: [debug] badging package: com.facebook.katana
> info: [debug] badging act: null
> info: [debug] Parsed package and activity are: com.facebook.katana/com.facebook.katana.LoginActivity
> 
> info: [debug] Using fast reset? false
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: [debug] Trying to find Addroid42 emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" devices
> info: [debug] 1 device(s) connected
> info: [debug] 1 emulator(s) connected
> info: [debug] Sending telnet command to device: avd name
> info: [debug] Getting running emulator port
> info: [debug] Socket connection to device created
> info: [debug] Socket connection to device ready
> info: [debug] Telnet command got response: Addroid42
> info: [debug] Found emulator Addroid42 in port 5554
> info: [debug] Setting device id to emulator-5554
> info: [debug] Did not launch AVD because it was already running.
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" -s emulator-5554 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" -s emulator-5554 shell "getprop persist.sys.country"
> info: [debug] Current device persist.sys.country: US
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" -s emulator-5554 wait-for-device
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" -s emulator-5554 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 17
> info: Device API level is: 17
> info: [debug] Extracting strings for language: default
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" -s emulator-5554 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\Chanis4\Downloads\com.facebook.katana-v57.0.0.18.136-18629582-Android-4.0.3.apk" "C:\Users\Chanis4\AppData\Local\Temp\com.facebook.katana" en
> info: [debug] No strings.xml for language 'en', getting default strings.xml
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\Chanis4\Downloads\com.facebook.katana-v57.0.0.18.136-18629582-Android-4.0.3.apk" "C:\Users\Chanis4\AppData\Local\Temp\com.facebook.katana"
> info: [debug] Reading strings from converted strings.json
> info: [debug] Setting language to default
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" -s emulator-5554 push "C:\Users\Chanis4\AppData\Local\Temp\com.facebook.katana\strings.json" /data/local/tmp
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Program Files (x86)\Android\android-sdk\build-tools\android-4.4W\aapt.exe
> info: [debug] Retrieving process from manifest.
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\build-tools\android-4.4W\aapt.exe" dump xmltree C:\Users\Chanis4\Downloads\com.facebook.katana-v57.0.0.18.136-18629582-Android-4.0.3.apk AndroidManifest.xml
> info: [debug] Set app process to: com.facebook.katana
> info: [debug] Uninstalling com.facebook.katana
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" -s emulator-5554 shell "am force-stop com.facebook.katana"
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe" -s emulator-5554 uninstall com.facebook.katana
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] Checking app cert for C:\Users\Chanis4\Downloads\com.facebook.katana-v57.0.0.18.136-18629582-Android-4.0.3.apk.
> info: [debug] executing cmd: java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar" C:\Users\Chanis4\Downloads\com.facebook.katana-v57.0.0.18.136-18629582-Android-4.0.3.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Users\Chanis4\Downloads\com.facebook.katana-v57.0.0.18.136-18629582-Android-4.0.3.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Program Files (x86)\Android\android-sdk\build-tools\android-4.4W\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: "C:\Program Files (x86)\Android\android-sdk\build-tools\android-4.4W\zipalign.exe" -f 4 C:\Users\Chanis4\Downloads\com.facebook.katana-v57.0.0.18.136-18629582-Android-4.0.3.apk C:\Users\Chanis4\AppData\Local\Temp\1151118-4404-1iht2ug\appium.tmp
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Error: ENOENT, rename 'C:\Users\Chanis4\AppData\Local\Temp\1151118-4404-1iht2ug\appium.tmp'
>     at Error (native)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: ENOENT, rename 'C:\Users\Chanis4\AppData\Local\Temp\1151118-4404-1iht2ug\appium.tmp')","errno":-4058,"code":"ENOENT","path":"C:\Users\Chanis4\AppData\Local\Temp\1151118-4404-1iht2ug\appium.tmp","origValue":"ENOENT, rename 'C:\Users\Chanis4\AppData\Local\Temp\1151118-4404-1iht2ug\appium.tmp'"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 27066.397 ms - 418 
> error: Failed to start an Appium session, err was: Error: ENOENT, rename 'C:\Users\Chanis4\AppData\Local\Temp\1151118-4404-1iht2ug\appium.tmp'

**Comment by scottdixon** [comment]
Looks like it's having a hard time renaming a nonexistent file. Please reinstall appium (or try 1.5 `npm install-g appium`) and try again.

**Comment by emna24** [comment]
I have the same issue, do you resolve it?

**Comment by chanisasuw** [comment]
yep, I remove appium .exe and use 

npm install -g appium 

it work for me

**Comment by vikramvi** [comment]
@triager please close this issue
