### ISSUE TITLE
All elements that are visible on a screen have visible == false

### ISSUE THREAD

**Issue by artgo** [appium/appium#5941]
XCode 7.2, appium 1.4.13 all elements have visible == false
![image](https://cloud.githubusercontent.com/assets/1357101/11910907/70c41254-a5b9-11e5-9d88-7261d5f229d6.png)

Similar to https://github.com/appium/appium/issues/4131

log: https://gist.github.com/artgo/3a1e2f9b8e2ac402e929

**Comment by dante2121** [comment]
I'm experiencing this issue as well.  In my case it's with a search bar found inside of a supplementary view.  Neither the appium inspector nor appium server can see the element.

Appium 1.4.13
Xcode 7.1
iOS 9.1

**Comment by scottdixon** [comment]
@artgo - is is just the GUI reporting visible false, or Appium too?

Can you please try with Appium 1.5 `npm install -g appium`

**Comment by artgo** [comment]
I believe just GUI.

**Comment by scottdixon** [comment]
Thanks.

@rompic has the same issue and has filed a bug in the GUI project: https://github.com/appium/appium-dot-app/issues/526

**Comment by KateOgar** [comment]
I faced the same issue in 1.5.2 appium. Could you help me: how can i check that element is present in the app in my tests with this issue? May be there is some other way?
