### ISSUE TITLE
Stop Karma from Appium after executing the tests.

### ISSUE THREAD

**Issue by nuthankumarns** [appium/appium#5945]
Hello All,

I am on the verge of automating Jasmine tests via karma runner within a Webview. Launched the iOS device with Hybrid App from Appium Webdriver using karma-webdriver-launcher plugin, the webpage in the hybrid app is hard-coded with Karma server's URL. Karma is able to run the test and aggregate the results, however, Karma is not stopped after all the tests, instead tries and gives up after 3 tries. SingleRun is set to true. I am testing WebRTC capabilities on iOS, I cannot test the same on Safari or any other browsers but for hybrid app.
One of the documents for Appium configuration points to https://github.com/appium/sample-code/tree/master/sample-code/examples/node
But, My concern is only API testing and little to do with UIAutomation. Do I need to run the mocha test script and start the appium, If so how do I do that and let Karma know when the tests are complete - perhaps send a driver.quit() from the any of the tests.

Any suggestions? I am not sure if this has anything to do with Karma.

Thanks,
Nuthan.

**Comment by scottdixon** [comment]
HI @nuthankumarns, please ask general question in the Appium discuss page: https://discuss.appium.io/

Good luck!
