### ISSUE TITLE
Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: UiAutomator quit before it successfully launched)","origValue":"UiAutomator quit before it successfully launched"},"sessionId":null}

### ISSUE THREAD

**Issue by sachin2788** [appium/appium#5947]
I paste my code here please review and let me know how to resolve this.
package Appiumsample;

import static org.junit.Assert.*;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;

import org.junit.Test;
import org.openqa.selenium.remote.DesiredCapabilities;

public class desiredcap {

	@Test
	public void test() throws MalformedURLException {
	
		File appDir = new File("src");
		
//	File app = new File(appDir, "WhatsApp.apk");
		File app = new File(appDir, "BookMyShow.apk");
		
		
//		File classpathRoot = new File(System.getProperty("user.dir"));
//        File appDir = new File(classpathRoot, "E:/Selenium/WorkSpace/AppiumSample/src/");
//        File app = new File(appDir, "BookMyShow.apk");
//		
		
		
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.PLATFORM_NAME,MobilePlatform.ANDROID);
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "ANDROID EMULATOR");
	//	cap.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
		cap.setCapability(MobileCapabilityType.APP, "BookMyShow.apk");
	//	cap.setCapability(MobileCapabilityType.APP, "WhatsApp.apk");
		//Android Driver
		AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), cap);
		
		
	}

}

**Comment by sachin2788** [comment]
![ui_emu](https://cloud.githubusercontent.com/assets/3167447/11972160/183df24a-a96e-11e5-832d-8b68c06ef1a6.png)

**Comment by scottdixon** [comment]
Do you hit the same issue with Appium 1.5?

**Comment by SrinivasanTarget** [comment]
As per above screenshot and code i see deviceName is wrong and App should also specify the path of apk.I don't see any session issue in latest arch. @sachin2788 Give a shot in Appium 1.5.1 and if incase if you still face any issues,raise a new issue with logs inform of gist.Closing this.

**Comment by SrinivasanTarget** [comment]
@triager please close
