### ISSUE TITLE
the tap command get stuck when duration is set to 0

### ISSUE THREAD

**Issue by reekic** [appium/appium#5948]
mac os : 10.11.1
appium : 1.4.16
iphone6s: 9.1
[appium_log.txt](https://github.com/appium/appium/files/70582/appium_log.txt)

**test procedure**

1. open the safari and access a web using the safari launcher
2. tap the video embeded in the page to play it

**issue**

1. the tap wont retrun if the duration is set to 0
2. while if the code is changed to driver.tap([(188,284)], 200), it works

**key python code**

c = driver.current_context
driver.switch_to.context("NATIVE_APP")
sleep(1)
driver.tap([(188,284)],200)
sleep(2)
driver.tap([(188,284)])
sleep(2)
driver.switch_to.context(c)

**gist log for the "driver.tap([(188,284)])", abnormal**

info: --> POST /wd/hub/session/7a7ba361-443c-4db7-afed-b0f624efae1d/touch/perform {"sessionId":"7a7ba361-443c-4db7-afed-b0f624efae1d","actions":[{"options":{"y":284,"x":188,"count":1},"action":"tap"}]}
info: [debug] Pushing command to appium work queue: "UIATarget.localTarget().frontMostApp().rect()"
info: [debug] Sending command to instruments: UIATarget.localTarget().frontMostApp().rect()
info: [debug] [INST] 2015-12-23 03:53:14 +0000 Debug: Got new command 4 from instruments: UIATarget.localTarget().frontMostApp().rect()
info: [debug] [INST] 2015-12-23 03:53:14 +0000 Debug: evaluating UIATarget.localTarget().frontMostApp().rect()
info: [debug] [INST] 2015-12-23 03:53:14 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-12-23 03:53:14 +0000 Debug: responding with:
info: [debug] [INST] 2015-12-23 03:53:14 +0000 Debug: Running system command #5: /usr/local/bin/node /Users/ninja/Documents/AppiumProject/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"origin":{"x":0,"y":0},"size":{"width":375,"height":667}}}...
info: [debug] Socket data received (81 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"origin":{"x":0,"y":0},"size":{"width":375,"height":667}}}
info: [debug] Pushing command to appium work queue: "UIATarget.localTarget().frontMostApp().tapWithOptions({\"tapOffset\":{\"x\":0.5013333333333333,\"y\":0.4257871064467766},\"tapCount\":1,\"touchCount\":1})"
info: [debug] Sending command to instruments: UIATarget.localTarget().frontMostApp().tapWithOptions({"tapOffset":{"x":0.5013333333333333,"y":0.4257871064467766},"tapCount":1,"touchCount":1})
info: [debug] [INST] 2015-12-23 03:53:15 +0000 Debug: Got new command 5 from instruments: UIATarget.localTarget().frontMostApp().tapWithOptions({"tapOffset":{"x":0.5013333333333333,"y":0.4257871064467766},"tapCount":1,"touchCount":1})
info: [debug] [INST] 2015-12-23 03:53:15 +0000 Debug: evaluating UIATarget.localTarget().frontMostApp().tapWithOptions({"tapOffset":{"x":0.5013333333333333,"y":0.4257871064467766},"tapCount":1,"touchCount":1})
info: [debug] [INST] 2015-12-23 03:53:15 +0000 Debug: target.frontMostApp().tapWithOptions({touchCount:"1", tapCount:"1", tapOffset:{x:"0.5013333333333333", y:"0.4257871064467766"}})
info: [debug] Didn't get a new command in 60 secs, shutting down...
info: Shutting down appium session
info: [debug] Stopping safariLauncher
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall Simulator
info: [debug] On a real device; cannot clean device state
info: [debug] Cleaning up appium session
info: [debug] We shut down because no new commands came in

**gist log for the "driver.tap([(188,284)],200)", normal**

info: --> POST /wd/hub/session/5022fedf-e834-4146-8554-62110dd58596/touch/perform {"actions":[{"action":"longPress","options":{"x":188,"y":284,"duration":10}},{"action":"release","options":{}}],"sessionId":"5022fedf-e834-4146-8554-62110dd58596"}
info: [debug] Pushing command to appium work queue: "target.touch([{\"touch\":[{\"x\":188,\"y\":284}],\"time\":0.2}])"
info: [debug] Sending command to instruments: target.touch([{"touch":[{"x":188,"y":284}],"time":0.2}])
info: [debug] [INST] 2015-12-23 03:59:04 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-12-23 03:59:04 +0000 Debug: responding with:
info: [debug] [INST] 2015-12-23 03:59:04 +0000 Debug: Running system command #4: /usr/local/bin/node /Users/ninja/Documents/AppiumProject/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] [INST] 2015-12-23 03:59:21 +0000 Debug: Got new command 4 from instruments: target.touch([{"touch":[{"x":188,"y":284}],"time":0.2}])
info: [debug] [INST] 2015-12-23 03:59:21 +0000 Debug: evaluating target.touch([{"touch":[{"x":188,"y":284}],"time":0.2}])
info: [debug] [INST] 2015-12-23 03:59:21 +0000 Debug: target.touch(__NSCFArray)
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"5022fedf-e834-4146-8554-62110dd58596"}
info: <-- POST /wd/hub/session/5022fedf-e834-4146-8554-62110dd58596/touch/perform 200 1865.849 ms - 74 {"status":0,"value":"","sessionId":"5022fedf-e834-4146-8554-62110dd58596"}

**Comment by scottdixon** [comment]
Please try with the latest Appium 1.5 `npm install -g appium`

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by SrinivasanTarget** [comment]
Closed this because of inactivity
