### ISSUE TITLE
Unable to install apk if it name contains "(" character

### ISSUE THREAD

**Issue by IZaiarnyi** [appium/appium#5951]
Str:
1. capabilities.setCapability(MobileCapabilityType.APP, "/Users/yupa/jenkins/workspace/HEDclient-release-0.3.10(31).apk")
2. Set other necessary  capabilities
3. Create new AndroidDriver

Actual result: 
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Command failed: /bin/sh -c java -jar /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/jars/sign.jar /Users/yupa/jenkins/workspace/HEDclient-release-0.3.10(31).apk --override
/bin/sh: -c: line 0: syntax error near unexpected token `('

Expected result:
Driver was create successfully 

Additional information:
appium --version = 1.4.16
appium.java-client = 3.3.0

**Comment by kcinman11358** [comment]
can you install it via adb install?

**Comment by IZaiarnyi** [comment]
Only if I type  ```adb install 'HEDclient-release-0.3.10(31).apk'```  
 ```adb install 'HEDclient-release-0.3.10(31).apk``` - return the same syntax error near unexpected token `('
The Problem is that if I provide path to my apk with quotes in my  capabilities I will get   error that apk path isn't correct.

**Comment by kcinman11358** [comment]
hmm, well can you trim the name off before you install it?

**Comment by scottdixon** [comment]
I'm unable to reproduce this - can you please provide full logs as a gist

**Comment by scottdixon** [comment]
Assuming this is resolved. Please reopen if you need to file a bug.
