### ISSUE TITLE
npm install -g appium error!!!

### ISSUE THREAD

**Issue by RoyGeagea** [appium/appium#5952]
npm ERR! tar.unpack unzip error /var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-6863-033232ce/registry.npmjs.org/core-js/-/core-js-0.9.18.tgz
npm ERR! tar.unpack untar error /var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-6863-033232ce/registry.npmjs.org/core-js/-/core-js-0.9.18.tgz
npm ERR! tar.unpack unzip error /var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-6863-033232ce/registry.npmjs.org/appium-instruments/-/appium-instruments-2.0.6.tgz
npm ERR! tar.unpack unzip error /var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-6863-033232ce/registry.npmjs.org/bluebird/-/bluebird-2.10.2.tgz
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.2.0/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/admin/npm-debug.log

**Comment by scottdixon** [comment]
@RoyGeagea - are you able to reproduce this error if you try again?

**Comment by RoyGeagea** [comment]
the error this time is :

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/underscore.string/-/underscore.string-2.2.1.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/underscore.string/-/underscore.string-2.2.1.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/iconv-lite/-/iconv-lite-0.2.11.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/iconv-lite/-/iconv-lite-0.2.11.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/lodash/-/lodash-2.4.2.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/lodash/-/lodash-2.4.2.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/appium-instruments/-/appium-instruments-2.0.6.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/appium-instruments/-/appium-instruments-2.0.6.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/date-utils/-/date-utils-1.2.17.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/date-utils/-/date-utils-1.2.17.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/appium-atoms/-/appium-atoms-0.0.5.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/appium-atoms/-/appium-atoms-0.0.5.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/teen_process/-/teen_process-1.5.1.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/colors/-/colors-1.0.3.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/colors/-/colors-1.0.3.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/appium-uiauto/-/appium-uiauto-1.10.10.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/appium-uiauto/-/appium-uiauto-1.10.10.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/chai/-/chai-3.4.0.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/chai/-/chai-3.4.0.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/coffee-script/-/coffee-script-1.3.3.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-4889-2e583016/
registry.npmjs.org/coffee-script/-/coffee-script-1.3.3.tgz

**Comment by scottdixon** [comment]
hmm what happens if you `npm cache clean` and run it again?

**Comment by scottdixon** [comment]
also, are you running through a VPN?

**Comment by RoyGeagea** [comment]
no i'm not running through a VPN, and after npm cache clean this is the
error:

JJJ:~ admin$ npm cache clean

JJJ:~ admin$ npm install -g appium

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/namp/-/namp-0.2.25.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/appium-atoms/-/appium-atoms-0.0.5.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/appium-atoms/-/appium-atoms-0.0.5.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/teen_process/-/teen_process-1.5.1.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/lodash/-/lodash-3.10.1.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/lodash/-/lodash-3.10.1.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/socket.io-parser/-/socket.io-parser-2.2.4.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/socket.io-parser/-/socket.io-parser-2.2.4.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/es6-promise/-/es6-promise-2.3.0.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/appium-adb/-/appium-adb-1.7.5.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/request/-/request-2.53.0.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/request/-/request-2.53.0.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/traceur/-/traceur-0.0.92.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/traceur/-/traceur-0.0.92.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.8.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.8.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/swig/-/swig-1.4.2.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-5018-7c8bdf8e/
registry.npmjs.org/swig/-/swig-1.4.2.tgz

**Comment by scottdixon** [comment]
Looks unrelated to Appium - @imurchie have you ever seen this?

**Comment by imurchie** [comment]
No. I can install it with the same configuration.

Does it work if you try to install locally (i.e., `npm install appium`)? Does it work to install something else (e.g., `npm install -g gulp`)?

Is there more information that can be given? What is the os and version?

**Comment by RoyGeagea** [comment]
I can install other packages
OS: osx el capitan version 10.11.1

**Comment by imurchie** [comment]
And locally?

I would also delete the temporary files that are in `/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-*`. I'm not sure if `npm cache clean` gets rid of these. 

Finally, can you post, as a [gist](https://gist.github.com/), the full install log (`/Users/admin/npm-debug.log`)?

**Comment by RoyGeagea** [comment]
i delete the temporary file in: /var/folders/rh/
c1nghqvn7610gbml5gvyskbw0000gp/T/npm-*, and the errors still
this is the gist file:
https://gist.github.com/RoyGeagea/dee081644d38129ecb2b

On Mon, Dec 28, 2015 at 10:56 PM, Isaac A. Murchie <notifications@github.com

**Comment by imurchie** [comment]
The log seems to indicate that this is a network connection issue. 

One last idea: can you try installing an older version, e.g., `npm install -g appium@1.4.16`

**Comment by RoyGeagea** [comment]
errors still appear

**Comment by scottdixon** [comment]
@RoyGeagea what happens if you install it locally?

i.e. `npm install appium@1.4.16` (without -g flag)

**Comment by RoyGeagea** [comment]
result:

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-23585-878847a7/
registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.8.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-23585-878847a7/
registry.npmjs.org/appium-instruments/-/appium-instruments-2.0.6.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-23585-878847a7/
registry.npmjs.org/traceur/-/traceur-0.0.92.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-23585-878847a7/
registry.npmjs.org/swig/-/swig-1.4.2.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-23585-878847a7/
registry.npmjs.org/swig/-/swig-1.4.2.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-23585-878847a7/
registry.npmjs.org/appium-atoms/-/appium-atoms-0.0.5.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-23585-878847a7/
registry.npmjs.org/appium-uiauto/-/appium-uiauto-1.10.10.tgz

npm ERR! tar.unpack unzip error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-23585-878847a7/
registry.npmjs.org/es6-promise/-/es6-promise-2.3.0.tgz

npm ERR! tar.unpack untar error
/var/folders/rh/c1nghqvn7610gbml5gvyskbw0000gp/T/npm-23585-878847a7/
registry.npmjs.org/es6-promise/-/es6-promise-2.3.0.tgz

npm ERR! Darwin 15.0.0

npm ERR! argv "/usr/local/Cellar/node/5.2.0/bin/node" "/usr/local/bin/npm"
"install" "appium@1.4.16"

npm ERR! node v5.2.0

npm ERR! npm  v3.3.12

npm ERR! code ECONNRESET

npm ERR! errno ECONNRESET

npm ERR! syscall read


npm ERR! network read ECONNRESET

npm ERR! network This is most likely not a problem with npm itself

npm ERR! network and is related to network connectivity.

npm ERR! network In most cases you are behind a proxy or have bad network
settings.

npm ERR! network

npm ERR! network If you are behind a proxy, please make sure that the

npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by Jonahss** [comment]
Has anyone besides @RoyGeagea  been able to reproduce this?
@RoyGeagea  could you try from a different network, or a different computer?

**Comment by RoyGeagea** [comment]
I try on different connections but not computers

**Comment by RoyGeagea** [comment]
Issue not solved

**Comment by scottdixon** [comment]
@RoyGeagea are you hitting this with any other NPM packages? Have you tried with different NPM versions? Have you researched `network read ECONNRESET` or tried any of these: http://stackoverflow.com/questions/18419144/npm-not-working-read-econnreset

**Comment by RoyGeagea** [comment]
I can install other packages.
And i try all the solution

**Comment by scottdixon** [comment]
Hmm I think we've exhausted all avenues. At this point I would suggest following the error's suggestion and posting the issue in: https://github.com/npm/npm/issues

If you have any more information, especially in regards to Appium, I'd be happy to reopen the issue and try to assist you further.
