### ISSUE TITLE
Unable to find xpath "//UIATextField[1]" with the new build of app using

### ISSUE THREAD

**Issue by devicodev** [appium/appium#5953]
Env.: appium 1.4.16
appium-client 1.4.13

One month ago I built an iOS application and used inspector for finding elements on the Login screen but today I got a problem with the new build of my app. The problem is that I can't find elements on the Login screen all I see is parent element and no child elements can be found.  
Login View
type: UIAElement
value: 
label: Login View
enabled: true
visible: false
valid: true
location: {0, 0}
size: {320, 568}
xpath: //UIAApplication[1]/UIAWindow[1]/UIAElement[1]

It's very critical for me, I have this problem only on Login screen.

Additional info: difference between old and new builds is unsupporting iOS7 target version.
![2015-12-24_0510](https://cloud.githubusercontent.com/assets/8375926/11993248/c8ef88cc-a9fc-11e5-97a5-d4bd46584f8a.png)

**Comment by kcinman11358** [comment]
Is the login page a webview or native?

**Comment by devicodev** [comment]
native, also please note that in "Context" dropdown I tried with "Native App" option and the same result for me. Tested with appium 1.5.0 beta9 too.

Actually I got the same result using this option
https://developer.apple.com/library/ios/technotes/TestingAccessibilityOfiOSApps/TestAccessibilityiniOSSimulatorwithAccessibilityInspector/TestAccessibilityiniOSSimulatorwithAccessibilityInspector.html

only "Login View" element was accessible ...

**Comment by kcinman11358** [comment]
Another question: Are you the developer of this app? Because it just seems odd it can't pick it up
