### ISSUE TITLE
Unable to launch application on iOS simulator with appium 1.4.13

### ISSUE THREAD

**Issue by swati711** [appium/appium#5954]
Hi All,

I am trying to launch ionic  app on iOS simulator using appium..it tries for three times and crashes with following error:

xcode : 7.2
Appium:1.4.13
Ios Simulator :9.2

info: [IOS_SYSLOG_ROW ] Dec 24 05:05:57 mac-atadikam-D1 SpringBoard[14149]: Unable to get pid for 'UIKitApplication:com.ionicframework.jany633449[0xcb94]': No such process (err 3)
info: [IOS_SYSLOG_ROW ] Dec 24 05:05:57 mac-atadikam-D1 SpringBoard[14149]: Bootstrapping failed for <FBApplicationProcess: 0x7d68d570; com.ionicframework.jany633449; pid: -1>
info: [IOS_SYSLOG_ROW ] Dec 24 05:05:57 mac-atadikam-D1 SpringBoard[14149]: Application 'UIKitApplication:com.ionicframework.jany633449[0xcb94]' exited voluntarily.

info: [IOS_SYSLOG_ROW ] Dec 24 05:05:57 mac-atadikam-D1 com.apple.CoreSimulator.SimDevice.B964EB97-D0FF-4751-A17D-732B96C86AF1.launchd_sim[14132] (UIKitApplication:com.ionicframework.jany633449[0x60c6][14278]): Program specified by service does not contain one of the requested architectures: U
info: [IOS_SYSLOG_ROW ] Dec 24 05:05:57 mac-atadikam-D1 SpringBoard[14149]: Unable to get pid for 'UIKitApplication:com.ionicframework.jany633449[0x60c6]': No such process (err 3)
info: [IOS_SYSLOG_ROW ] Dec 24 05:05:57 mac-atadikam-D1 SpringBoard[14149]: Bootstrapping failed for <FBApplicationProcess: 0x7bfbdc10; com.ionicframework.jany633449; pid: -1>
info: [IOS_SYSLOG_ROW ] Dec 24 05:05:57 mac-atadikam-D1 SpringBoard[14149]: [FBSystemService] Error launching com.ionicframework.jany633449: Unspecified (1)
info: [IOS_SYSLOG_ROW ] Dec 24 05:05:57 --- last message repeated 1 time ---
info: [IOS_SYSLOG_ROW ] Dec 24 05:05:57 mac-atadikam-D1 SpringBoard[14149]: Unable to delete job with label UIKitApplication:com.ionicframework.jany633449[0x60c6]. Error: Operation now in progress
info: [IOS_SYSLOG_ROW ] Dec 24 05:05:57 mac-atadikam-D1 SpringBoard[14149]: Application 'UIKitApplication:com.ionicframework.jany633449[0x60c6]' exited for an unknown reason.
info: [IOS_SYSLOG_ROW ] Dec 24 05:05:57 mac-atadikam-D1 com.apple.CoreSimulator.SimDevice.B964EB97-D0FF-4751-A17D-732B96C86AF1.launchd_sim[14132] (UIKitApplication:com.ionicframework.jany633449[0x60c6][14278]): Trampoline was terminated before jumping to service: Killed: 9

info: [debug] [INST STDERR] 2015-12-24 05:05:58.493 instruments[14262:138463] Attempting to change event horizon while disengage

info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.) : Failed to launch process with bundle identifier 'com.ionicframework.jany633449'
2015-12-24 05:05:58.494 instruments[14262:138502] Attempting to change event horizon while disengage
info: [debug] [INSTSERVER] Instruments exited with code 253
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] We exceeded the number of retries allowed for instruments to successfully start; failing launch
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killing any other simulator daemons
info: [debug] Killall iOS Simulator
info: [IOS_SYSLOG_ROW ] Dec 24 05:05:58 mac-atadikam-D1 DTServiceHub[14158]: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn
info: [debug] Cleaning sim data files
info: node-simctl: Executing: xcrun with args: simctl erase B964EB97-D0FF-4751-A17D-732B96C86AF1 and timeout: 2000

**Comment by kcinman11358** [comment]
can install the app without growing through appium?

**Comment by Simon-Kaz** [comment]
Appium 1.4.13 doesn't support 9.2. You need to update to latest appium version to use iOS 9.2 or use an older simulator that is supposed by 1.4.13

**Comment by kcinman11358** [comment]
@Simon-Kaz, that is not true. I am using Appium 1.4.13 and iOS 9.2 just fine

**Comment by Simon-Kaz** [comment]
Full support was added in https://discuss.appium.io/t/appium-1-4-14-released/6978 
YMMV with previous version.

**Comment by scottdixon** [comment]
@swati711 - did updating Appium resolve the issue?

@kcinman11358 - 1.4.13 is the latest .app, you'll need to install through NPM or from source to update.

**Comment by swati711** [comment]
Rebuilding the app in xcode resolved this issue.

**Comment by Krunaltthakkar13** [comment]
Hi geeks 

iOS :10.3
appium :1.6.3
xcode : 8.3

XCTRunner[7366]: Enqueue Failure: Failed to launch isteer.Demoappium: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.) /usr/local/lib/node_modules/appium/node_modules/appi

Let me know if anyone knows
