### ISSUE TITLE
Is appium conflict with mitmproxy?

### ISSUE THREAD

**Issue by cryingDream94** [appium/appium#5956]
When I used appium to write test cases，and set the mobile phone connection mitmproxy agent。
I found a very strange problem。
In test case，click button send url request，request cost time (response time - request time) very big.

**Comment by cryingDream94** [comment]
Such as this url request，run appium test case。mitmproxy intercept information：
 {"requestSize": 0.423828125, "startTime": 1451011779.794478, "realTime": 6.059123992919922, "url": "http://ms0.meituan.net/touch/css/i/fonts/base14.woff", "contentType": "[]", "endTime": 1451011785.853602, "responseSize": 8.720703125}
"realTime": 6.059123992919922
-----------------
manual click。mitmproxy intercept information:
"realTime": 0.89
.....
"run appium test case"  and "manual click" real time very difference。

**Comment by Jonahss** [comment]
Hm. Well.
Any ideas of what we can do to minize this issue?

**Comment by rkavalap** [comment]
@cryingDream94 Can you post details on how to repro this and more details based on the current appium issue template.
