### ISSUE TITLE
scrollTo doesn't work on iOS 9.1

### ISSUE THREAD

**Issue by RoyGeagea** [appium/appium#5957]
scrollTo doesn't work on iOS 8.4, 9.0, 9.1

**Comment by scottdixon** [comment]
Which version of Appium are you using? All of the mobile commands other than mobile: scroll were deprecated in 1.4 and removed in 1.5. The touch action API is better for these actions.

**Comment by RoyGeagea** [comment]
can you give me an example in touch action ?

**Comment by scottdixon** [comment]
@RoyGeagea: some great information here: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md

**Comment by scottdixon** [comment]
@RoyGeagea: some great information here: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md
