### ISSUE TITLE
Cordova 4.1.1 Hybrid WebView switching gives the error in Appium latest version 1.4.16 on selendroid mode

### ISSUE THREAD

**Issue by kannan554** [appium/appium#5959]
We switched the version of Cordova from 3.6.4 to 4.1.1 in our latest build. Switching of webview was working fine earlier, however after the cordova version change it gives the below error. 

I know this issue prevailed earlier and was fixed along with selendroid fix in 0.15. But would like to know whether it would work fine for cordova 4.x also. 

Any suggestion to trouble shoot the issue further would really help.

[debug] [SELENDROID] io.selendroid.server.model.SelendroidWebDriver$SelendroidWebChromeClient cannot be cast to org.apache.cordova.engine.SystemWebChromeClient
[36minfo[39m: [debug] [SELENDROID]    at org.apache.cordova.engine.SystemWebView.setWebChromeClient(SystemWebView.java:76)

**Comment by kannan554** [comment]
I think the culprit here is selendroid 0.17. I ran the test on selendroid 0.16 and it ran without any issue.  Also found out that there is an existing issue in selendroid project for the same
https://github.com/selendroid/selendroid/issues/993
Hence the fix for appium may depend on selendroid fix

**Comment by Jonahss** [comment]
Sounds like it. Thanks @kannan554. Can you respond here when the selendroid bug gets fixed and we can update the version.

**Comment by kannan554** [comment]
Sure, I will follow up on that.
