### ISSUE TITLE
MultiAction: org.json.JSONException: Index -1 out of range [0..0)

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/appium#5961]
Appium Server: v1.4.16 and lower

The sample of a client code:

```java
    List<MobileElement> els = driver.findElementsByClassName("android.widget.TextView");
    Point loc1 = els.get(7).getLocation();
    MobileElement target = els.get(1);
    Point loc2 = target.getLocation();

    TouchAction press = new TouchAction(driver);
    press.press(loc1.x, loc1.y).waitAction(1000);

    //TouchAction move = new TouchAction(driver);
    //move.moveTo(loc2.x, loc2.y);

    TouchAction release = new TouchAction(driver);
    release.release();

    MultiTouchAction multiAction = new MultiTouchAction(driver);
    multiAction.add(press)./*add(move).*/add(release).perform();
```
The fragment of server output: https://gist.github.com/TikhomirovSergey/9fa52c25fca6214a4d71

This code crashes. However the code below works: 

```java
    TouchAction touchAction = new TouchAction(driver);
    touchAction.press(loc1.x, loc1.y).waitAction(1000).release();

    MultiTouchAction multiAction = new MultiTouchAction(driver);
    multiAction.add(touchAction).perform();
```

The fragment of server output
https://gist.github.com/TikhomirovSergey/5ad8a8a985154496a277

It looks like the "release" action is transformed somehow to the empty object "[]". 
>--> POST /wd/hub/session/f4aa01f2-db36-44da-a9f0-1e724eb331f2/touch/multi/perform {"actions":[[{"action":"press","options":{"x":0,"y":734}},{"action":"wait","options":{"ms":1000}}],[{"action":"release","options":{}}]]}
>Pushing command to appium work queue: ["performMultiPointerGesture",{"actions":[[{"action":"press","time":0.005,"touch":{"x":0,"y":734}},{"action":"wait","time":1.004,"touch":{"ms":1000,"x":0,"y":734}}],[]]}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"performMultiPointerGesture","params":{"actions":[[{"action":"press","time":0.005,"touch":{"x":0,"y":734}},{"action":"wait","time":1.004,"touch":{"ms":1000,"x":0,"y":734}}],[]]}}

And then this JSON cannot be parsed by server.

**Comment by Jonahss** [comment]
MultiTouchAction is for multiple TouchActions. A single TouchAction object is a series of movements (press, wait, release), and a MultiTouchAction is a collection of TouchAction objects, one for each "finger" touching the screen.

So you created two TouchActions, one presses and waits, the other just releases (without ever pressing).

So MultiTouch is trying to do both, one finger pressing, other finger releasing without ever touching.

Proper code would be:

```
TouchAction press = new TouchAction(driver);
press.press(loc1.x, loc1.y).waitAction(1000).release();

press.perform();
```
