### ISSUE TITLE
shake function doesn't work

### ISSUE THREAD

**Issue by RoyGeagea** [appium/appium#5966]
Hello,
shake function doesn't work on ios9 simulator

**Comment by scottdixon** [comment]
@RoyGeagea can you please provide logs as a gist.

**Comment by Jonahss** [comment]
Looks like "shake" is broken/removed in UIAutomation for iOS 9+

See here: https://github.com/calabash/calabash-ios/issues/873

Appium's strategy to fixing this should be development on https://github.com/appium/appium-xcuitest-driver  it should be working using that driver. (currently under development, look forward to it after appium 1.5 is published)

**Comment by brandontineo** [comment]
Has these been fixed on any released version of appium???
