### ISSUE TITLE
Appium (ios) how to send keys to UIAPickerWheel

### ISSUE THREAD

**Issue by liu3821** [appium/appium#5970]
Mac + appium(1.4.8/1.4.13) + iOS9.1(iPhone5s)
1. xx.sendKeys("2017") this is working
2. (note: there are two spaces in param, web site remove one space) xxx.sendKey("1  ($0.49)") , the wheel move to the target value, then crash.
3.  (note: there are two spaces in param, web site remove one space)xxx.sendKey("0  "), not woking, may be appium trim the space.

is this a bug of appium?

**Comment by liu3821** [comment]
^_^  i find a way to resolve this question:https://github.com/appium/appium/issues/5905
and this is code of java version, just catch the exception to avoid crash:
                            String value0 = "0  ";
				String temp0 = "";
				while (!temp0.equals(value0)){
					try {
                                           ad.findElementByClassName("UIAPickerWheel").sendKeys(value0);
					} catch (Exception e){
					  //Do Nothing
					} finally {
					  temp0 = ad.findElementByClassName ("UIAPickerWheel").getText();
					  System.out.println("temp0" + temp0);
					}
				}

**Comment by Jonahss** [comment]
Good workaround. We should fix this though :)

**Comment by kcinman11358** [comment]
This should have an iOS label.

**Comment by kornfan** [comment]
Appium 1.5.3 GUI on OS X 10.11.3
When I try to sendKeys to UIAPickerWheel it gives me following error:
`(org.openqa.selenium.WebDriverException: Unexpected error in -[UIAPickerWheel_0x1613fbd60 selectValue:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIAutomation/UIAutomation-449.2/Framework/UIAItemElements.m line 452 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.51 seconds`

Here's the log from the server 

`[debug] [UIAuto] Socket data received (8156 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"bFixing Dev","label":"bFixing Dev","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":0,"width":1024.0000335703464,"height":768.0000447604625},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value
[debug] [UIAuto] Sending command to instruments: au.getElementByIndexPath('/0/0/44/3/0')

[debug] [Instruments] [INST] 2016-08-19 13:48:00 +0000 Debug: Got new command 125 from instruments: au.getElementByIndexPath('/0/0/44/3/0')
[debug] [Instruments] [INST] 2016-08-19 13:48:00 +0000 Debug: evaluating au.getElementByIndexPath('/0/0/44/3/0')
[debug] [Instruments] [INST] 2016-08-19 13:48:00 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-08-19 13:48:00 +0000 Debug: responding with:

[debug] [Instruments] [INST] 2016-08-19 13:48:00 +0000 Debug: Running system command #126: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/fy/jr6h5svn7fz3bph_pky_x45c0000gq/T/instruments_sock 2,{"status":0,"v...
[debug] [UIAuto] Socket data received (39 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"ELEMENT":"34"}}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"34"}
[HTTP] <-- POST /wd/hub/session/8af1effb-addf-4d60-8a9e-a2e9948ed655/element 200 3514 ms - 88 
[HTTP] --> POST /wd/hub/session/8af1effb-addf-4d60-8a9e-a2e9948ed655/element/34/value {"id":"34","value":["11"]}
[MJSONWP] Calling AppiumDriver.setValue() with args: [["11"],"34","8af1effb-addf...
[debug] [iOS] Executing iOS command 'setValue'
[debug] [UIAuto] Sending command to instruments: au.getElement('34').setValueByType('11')

[debug] [Instruments] [INST] 2016-08-19 13:48:01 +0000 Debug: Got new command 126 from instruments: au.getElement('34').setValueByType('11')

[debug] [Instruments] [INST] 2016-08-19 13:48:01 +0000 Debug: evaluating au.getElement('34').setValueByType('11')

[debug] [Instruments] [INST] 2016-08-19 13:48:01 +0000 Debug: Unexpected error in -[UIAPickerWheel_0x1613fbd60 selectValue:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIAutomation/UIAutomation-449.2/Framework/UIAItemElements.m line 452

[debug] [UIAuto] Socket data received (206 bytes)

[debug] [UIAuto] Got result from instruments: {"status":17,"value":"Unexpected error in -[UIAPickerWheel_0x1613fbd60 selectValue:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIAutomation/UIAutomation-449.2/Framework/UIAItemElements.m line 452"}
[HTTP] <-- POST /wd/hub/session/8af1effb-addf-4d60-8a9e-a2e9948ed655/element/34/value 500 1509 ms - 267 
[HTTP] --> DELETE /wd/hub/session/8af1effb-addf-4d60-8a9e-a2e9948ed655 {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["8af1effb-addf-4d60-8a9e-a...
[debug] [iOS] Deleting ios session
[debug] [UIAuto] Destroying instruments client socket.
[debug] [UIAuto] Closing socket server.
[debug] [UIAuto] Instruments socket server was closed
[debug] [Instruments] Starting shutdown.
[debug] [Instruments] Sending sigterm to instruments

[debug] [Instruments] [INST] 2016-08-19 13:48:01 +0000 Error: VerboseError: Unexpected error in -[UIAPickerWheel_0x1613fbd60 selectValue:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIAutomation/UIAutomation-449.2/Framework/UIAItemElements.m line 452
[debug] [Instruments] [INST] 2016-08-19 13:48:02 +0000 Stopped: Script was stopped by the user

[debug] [Instruments] [INST] 2016-08-19 13:48:01 +0000 Error: Error during eval: selectValue@[native code]
       setValueByType@file:///Applications/Appium.app/Contents/Resources/node_modules/18C463C9-DA8A-45E7-96D6-939C70008035/bootstrap-0105f28840825aaf.js:2084:23
eval code
eval@[native code]
startProcessing@file:///Applications/Appium.app/Contents/Resources/node_modules/18C463C9-DA8A-45E7-96D6-939C70008035/bootstrap-0105f28840825aaf.js:2793:30
bootstrap@file:///Applications/Appium.app/Contents/Resources/node_modules/18C463C9-DA8A-45E7-96D6-939C70008035/bootstrap-0105f28840825aaf.js:2861:31
global code@file:///Applications/Appium.app/Contents/Resources/node_modules/18C463C9-DA8A-45E7-96D6-939C70008035/bootstrap-0105f28840825aaf.js:2870:10
[debug] [Instruments] [INST] 2016-08-19 13:48:02 +0000 Debug: responding with:
       2016-08-19 13:48:02 +0000 Debug: Running system command #127: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/fy/jr6h5svn7fz3bph_pky_x45c0000gq/T/instruments_sock 2,{"status":17,"...
[debug] [Instruments] [INST STDERR] 2016-08-19 15:48:02.413 instruments[14465:510078] Attempting to change event horizon while disengage

[debug] [Instruments] [INST] Instruments Trace Complete (Duration : 213.836975s; Output : /var/folders/fy/jr6h5svn7fz3bph_pky_x45c0000gq/T/appium-instruments/instrumentscli0.trace)

[debug] [Instruments] Instruments exited with code 0

[debug] [iOSLog] Stopping iOS log capture
[debug] [iOS] Running ios real device reset flow
[Appium] Removing session 8af1effb-addf-4d60-8a9e-a2e9948ed655 from our master session list
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null`

**Comment by mykola-mokhnach** [comment]
closed as outdated.

**Comment by someoneEsle** [comment]
I have the same problem with "XCUIElementTypePickerWheel". Using setValue("   something") does not work as Appium is probably trimming the spaces.

**Comment by Jasper11** [comment]
I have the same problem with "XCUIElementTypePickerWheel". 
PickerWheelElement.sendKeys(value) doesn't work when value contains whitespace. Please reopen the issue.
