### ISSUE TITLE
Appium not running to test without Xcode process.

### ISSUE THREAD

**Issue by mehmetboraezer** [appium/appium#5972]
Hello, I run Appium and connect Selenium Grid with these parameters : 
```
appium --nodeconfig /Users/bla/nodeconfig.json --udid "DEVICE_UDID" -bp 59564 --native-instruments-lib
```
But i have a problem. Sometimes Appium does not run to test without Xcode. When i see this situation, i open Xcode (just click Xcode icon, nothing else). After that Appium continues to test. This problem is not always visible. 

* [ My Appium Log ](https://github.com/appium/appium/files/77728/log.txt)

What am i doing wrong? How can i run continuously without any problem? How do i fix it?

---
* Appium v1.4.16
* Xcode 7.2 (7C68)
* Devices : iPhone 6 (iOS 8.4.1) [ I have tried different iOS version and different real devices (iPhone6(iOS 9.2), iPhone5(iOS 8.4.1), iPhone4S) ]

**Comment by Jonahss** [comment]
I have an idea.

When you reboot your iPhone, it loses the Developer settings in the settings app, so UIAutomation isn't enabled. Starting XCode on the host causes XCode to contact the iPhone and it sets up the phone for development.

This should last, until the iPhone reboots.

You can automate this process on your host machine by installing the developer image on the iPhone prior to running tests. Using `ideviceimagemounter` from the libimobiledevice project.

**Comment by mehmetboraezer** [comment]
I installed the developer image and after that the issue was fixed completely. You are right @Jonahss . Thank you.
