### ISSUE TITLE
Detect busy device

### ISSUE THREAD

**Issue by minimedj** [appium/appium#5976]
Hi guys, I have multiple appium instances running. Each instance has only one real device connected.

Is there a way to know that certain appium instance/device is busy (has active session)?

p.s. Would be great if I can request appium instance for number of active sessions and if it has any (I expect only 1 in my case) - it is clear sign for me that appium instance/device is busy.

**Comment by amedvedjev** [comment]
appium running on some port. maybe check what is listening needed ports?

this is OS dependant on Windows it is one way, on Mac another one.

**Comment by minimedj** [comment]
@amedvedjev This is one of possibilities, but I would prefer something more robust.

**Comment by crashbell** [comment]
You can start Appium instances as a child processes and catch its output `stdout` or `stderr` to find out what it's doing.

**Comment by minimedj** [comment]
@crashbell it works just fine

**Comment by saikrishna321** [comment]
@minimedj how did u get this done ? can you pls post your code snippet or more info pls

**Comment by minimedj** [comment]
@saikrishna321 Sorry, cannot post any code because of NDA, but it is very simple:

1. Run appium as a subprocess and capture all its output from `stdout` and `strerr`
2. Develop pattern matching code that will detect events from appium's output you are interested in.
3. When you detect event - do something with it.

Another hint: You would need multiprocess or multithread application (depends on your env), but is is very easy.

This is it. Good luck.
