### ISSUE TITLE
App freezes on iOS when data logging is ebaled

### ISSUE THREAD

**Issue by rajpalc** [appium/appium#5980]
When I am running the automation on iOS, app is freezing when a large json data is logged. This issue is not there on android for the same app. Also, this issue is not happening while running the automation by disabling the data logging. 

I need the to have the data logging while running the iOS automation tests, since I want to analyze all the logs later.

Appium:1.4.13
Ios Simulator : 8.1

**Comment by scottdixon** [comment]
Interesting. Is it all version of iOS or just 8.1? What are the test machine specs?

Can you also try on Appium 1.5?

**Comment by rajpalc** [comment]
Its happening with all versions of iOS. 

These are machine specs
MacBook Pro (Retina, 15-inch, Mid 2015)
Processor 2.5 GHz Intel Core i7
Memory 16 GB 1600 MHz DDR3

I have not tried on Appium 1.5 yet. Will try that and let you know.

**Comment by umaralikhan** [comment]
@scottdixon this is happening on following as well.


MAC Version - OS X EI Capitan 10.11.5
Appium - 1.5.3
iphone - 6 Plus (Simulator)
IOS version - 9.3, 9.0, 8.4

I am having the same issue. My problem is that once my application is signed in and lands over main page the appium inspector can't show any element hierarchy in it. And if I take the application in background and open up some other application like settings and bring back my application in foreground then the appium inspector shows all elements in it.

This is causing a lot of trouble to me

@tekisrinivas20 please check it on priority

**Comment by jlipps** [comment]
closing for now since it seems machine-dependent. also we have updated our logging strategies so maybe the data isn't as problematic.
