### ISSUE TITLE
python get_log('crashlog') return empty list on iOS device

### ISSUE THREAD

**Issue by camillake** [appium/appium#5983]
I could not get device crash by calling get_log('crashlog')

**My environment:**
appium 1.4.16
Appium-Python-Client 0.17
target device ios 8.4.1
development platform 
xcode 7.2

**Comment by scottdixon** [comment]
@camillake - can you please try with Appium 1.5

If you don't have any luck please provide server logs as a gist.

**Comment by z00sts** [comment]
Hi there!
Got same issue today. Both ios-driver 'crashlog' and 'performance' logs are empty everytime.

```
Appium v1.5.3 (REV 52691cd0de6c18906e5fe7f290c0b4deda64973a)
Appium-Python-Client 0.24
Xcode 7.3.1 (Build version 7D1014)
iPhone 6, iOS version 9.3

Non-default server args:
backendRetries: 1
log: 'appium_logs/appium.log'
logTimestamp: true
localTimezone: true
debugLogSpacing: true
nativeInstrumentsLib: true
showIOSLog: true
Deprecated server args:
--native-instruments-lib => --default-capabilities '{"nativeInstrumentsLib":true}'
--show-ios-log => --default-capabilities '{"showIOSLog":true}'

Capabilities:
app: <app_path>
fullReset: true
waitForAppScript: 'target.elements().length > 0;'
sendKeyStrategy: 'setValue'
platformName: 'iOS'
platformVersion: '9.3'
deviceName: 'iPhone 6'
udid: '<udid>'
autoDismissAlert: 'true'
nativeInstrumentsLib: true
showIOSLog: true
```

**Comment by jlipps** [comment]
Hi @z00sts we don't support Appium 1.5.3 anymore. Can you download 1.6.3 and try? (And note that the automation engine for iOS has changed in 1.6, so it might be different in some respects).

**Comment by z00sts** [comment]
@jlipps Thank you for your response. I'll try it soon :)
