### ISSUE TITLE
Not able to click any element while audio id playing

### ISSUE THREAD

**Issue by karanahuja007** [appium/appium#5984]
Hi,

I need to click on pre-sets for audio, but the problem is that appium waits till the audio play gets over.
And once the audio play has been completed that pre-set button gets disabled.

Please provide any valid solution to access that element during the time of audio play.

Thanks & Regards,
Karan Ahuja

**Comment by scottdixon** [comment]
Which platform? How are you currently triggering the audio play?

**Comment by karanahuja007** [comment]
I am using AndroidDriver(Appium) for Android Automation and my current app is related to Music composer and beat mixer. I am stuck at a place where I need to click on an element(beat mixer button).

Functionality of application is Beat mixer button only gets enabled during the time audio is playing. Before & After of audio play button remains disabled

Problem is Android Appium waits till the audio play gets completed. Is there any way to click on the beat mixer button during the time audio is playing?

I have tried with the following ways but didn't get any result.

performMultiTouchAction()
runAppInBackground(2)

As I need to test on multiple android devices any valuable solution other than coordinates click will be appreciated.

**Comment by scottdixon** [comment]
`Beat mixer button only gets enabled during the time audio is playing.`

- how are you triggering the audio play with Appium? Can I see your test script?

**Comment by karanahuja007** [comment]
// Clicking play button of embedded media player.
 WebDriverWait wait = new WebDriverWait(webDriver, 20);
        WebElement element = wait.until(ExpectedConditions.elementToBeClickable(By.id("playButton")));
element.click();

//Clicking Beat mixer button.
 WebDriverWait wait = new WebDriverWait(webDriver, 20);
        WebElement element = wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[text()='Hi_Pass']")));
element.click();

Please find the attached Screenshot:-
![click7](https://cloud.githubusercontent.com/assets/3114521/12385256/fe67a24a-bddf-11e5-88b9-201bbe4a3578.png)

**Comment by zcmgyu** [comment]
Same problem here

**Comment by zcmgyu** [comment]
I have same problem.
And I've used adb to work around this problem

adb shell input keyevent KEYCODE_MEDIA_PLAY_PAUSE

**Comment by karan-trantor** [comment]
Problem is resolved for me.
I was using xpath method 'text()' for finding text which works well with (Selenium + web) but for android @text works instead of text().

**Comment by vikramvi** [comment]
@triager please close per above comment
