### ISSUE TITLE
Running Appium Test on Real Device with Safari Launcher

### ISSUE THREAD

**Issue by aasan** [appium/appium#5991]
Hi All,

Safari Launcher is installed on my mobile. 
Phone is Connected as can be seen in below code

ACAC0B14:~ atariq$ ios_webkit_debug_proxy
Listing devices on :9221
Connected :9222 to Asjad's iPhone (0838095b054---------------------------)

When i run below testcase 
Java Code

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("deviceName","Asjad's iPhone");
capabilities.setCapability("platformName","iOS");
capabilities.setCapability("platformVersion","9.2");
capabilities.setCapability(CapabilityType.BROWSER_NAME, "safari");
capabilities.setCapability("udid", "0838095b0547b64d-------------177c");
driver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
Thread.sleep(6000);
driver.get("http://www.google.com");

No Error. phone asked to Enter Passcode once Passcode is Enter nothing happen on the phone it didn't open safari

If possible please rely with suggestions.

Appium Log : show only below warning rest all OK. If you want i can attached complete log as well

info: [debug] [INST STDERR] 2016-01-08 11:29:29.088 instruments[1409:695155] Failed to start Instruments daemon on 'Asjad's iPhone (9.2)' (The service is invalid.)

info: [debug] [INST STDERR] Instruments Usage Error : Specified target process is invalid: com.softwaretestingappium.

info: [debug] [INST STDERR] instruments, version 7.2 (59503)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]

**Comment by scottdixon** [comment]
Sounds like an issue with the device - try this: https://github.com/appium/appium/issues/2124#issuecomment-42650685

**Comment by Akulavenkatesh** [comment]
Seems like there is some issue with the 'BundleID':
info: [debug] [INST STDERR] Instruments Usage Error : Specified target process is invalid: com.softwaretestingappium.
