### ISSUE TITLE
Unable to take screenshot on Safari browser on Real iOS device

### ISSUE THREAD

**Issue by uparejiya** [appium/appium#5995]
Hi,

I am unable to take screenshot on iOS real device safari browser. Driver stuck at Takescreenshot command. I am using java for automation on iOS. Please give any suggestion or solution for this.

**Comment by scottdixon** [comment]
Please provide your server logs as a [gist](https://gist.github.com/).

**Comment by uparejiya** [comment]
This issue is resolved by using latest appium version
