### ISSUE TITLE
Appium exits with `Killed: 9` before ever returning valid session

### ISSUE THREAD

**Issue by apallin** [appium/appium#5997]
I am at an impasse here and have tried everything to get this working.  All I have changed in my code is moved my test runner from relative imports to a new python package.  Since then, the test dies just after posting the session to Appium.  There is no visible difference in desiredCapabilities, the App or the Appium logs EXCEPT one line:

```
info: <-- POST /wd/hub/session - - ms - -
```

This seems to be what is killing this.

I have posted comparisons of both Appium logs, working and not working.
Not working:
https://gist.github.com/apallin/a977ee4272b07de72a3b
Working:
https://gist.github.com/apallin/e6b56bdd36079c077073

Here is the two desired capabilities:
Working:
2016-01-08 15:08:30,841 |DEBUG  | selenium.webdriver.remote.remote_connection :: POST http://127.0.0.1:4723/wd/hub/session {"desiredCapabilities": {"deviceName": "iPhone Simulator", "name": "ios-test_golden_path_registration-None", "app": "/Users/adampallin/src/Lyft-iOS/ui-tests/Lyft.app", "build": "ios", "platformVersion": "9.0", "platformName": "iOS", "appiumVersion": "1.4.16"}}

Not Working:
2016-01-08 14:57:36,207 |DEBUG  | selenium.webdriver.remote.remote_connection :: POST http://127.0.0.1:4723/wd/hub/session {"desiredCapabilities": {"deviceName": "iPhone Simulator", "name": "ios-test_golden_path_registration-None", "app": "/Users/adampallin/src/Lyft-iOS/ui-tests/Lyft.app", "build": "ios", "platformVersion": "9.1", "platformName": "iOS", "appiumVersion": "1.4.16"}}
Killed: 9

**Comment by scottdixon** [comment]
Hmm strange that the post to create session is returning so quickly.

Can you rule out the different platformVersions (9.0 vs 9.1)?

**Comment by apallin** [comment]
Already have, it hasn't affected that at all.
On Fri, Jan 8, 2016 at 4:08 PM Scott Dixon <notifications@github.com> wrote:

> Hmm strange that the post to create session is returning so quickly.
>
> Can you rule out the different platformVersions (9.0 vs 9.1)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/5997#issuecomment-170161773>.
>
-- 
*Adam Pallin*
QA Automation Engineer
650.245.7060
[image: Lyft]

**Comment by scottdixon** [comment]
@imurchie might have an idea

**Comment by imurchie** [comment]
That log output usually means that the client has disconnected.

**Comment by apallin** [comment]
@imurchie So what could be causing this to disconnect?  It is in the middle of opening the webdriver connection while initializing a new instance.  Any action is directly happening in the appium.webdriver.Remote() object.

**Comment by imurchie** [comment]
That I don't know. Are you comfortable providing your test script?

**Comment by apallin** [comment]
I should be able to pair it down and provide you a sanitized script. Ill follow up ASAP.

**Comment by apallin** [comment]
[test_failures.zip](https://github.com/appium/appium/files/86184/test_failures.zip)

Paired this down significantly to illustrate our test setup, I cant figure out what the issue is with this model.  

To execute, use any app for a demo and run:
`py.test --platformName='iOS' --deviceName='iPhone Simulator' --platformVersion='9.1' --app=/path/to/app new_test_model.py`

**Comment by apallin** [comment]
@imurchie any update?  FYI this is only happening on iOS, not Android with the same code

**Comment by khallbec** [comment]
I'm not sure if this is the same problem. But I found that I now need to rebuild the simulator for the device I want to test on if I switch devices.
For instance... If I have been running tests on iPhone its fine. But if I switch to iPad I need to rebuild the iPad simulator in Xcode then my tests will run. If I try to switch back to iPhone, I have to rebuild for iPhone in Xcode.
This is not 8.4 only 9.0
I'm on Xcode 7.0 and Appium 1.4 15

I hope this helps. I need to figure out how to not build the sim every time we switch.

**Comment by apallin** [comment]
@khallbec Were you having the same error occur in the same spot?  I don't think this is because of what you are describing because as soon as I switch back to the other test code (my old model) it works.

**Comment by imurchie** [comment]
I can reproduce the problem with Appium 1.4, but everything works fine with 1.5. I also can run tests using the same python client, but not in the project above. Not sure what the problem is.

**Comment by khallbec** [comment]
I'll check first thing in the morning. I rolled back from 1.4.16 because it wasn't working for me. I'm running tests right now so I can't start a session up to see exactly where it is failing.

**Comment by apallin** [comment]
Confirmed that this is fixed in 1.5... What do you mean by "the same python client"?  Additionally, I am interested to know when 1.5 goes out and when Saucelabs will provide that version of Appium.  This is blocking us moving forward with a significant overhaul of our test infrastructure.

**Comment by imurchie** [comment]
I mean that the failure seems to be somewhere in the Selenium client installed through `pip`. But using the exact same client I can run other tests.

We are working hard on fixing up a few last issues with 1.5, including some that happen on Sauce Labs. When we release 1.5 it will also be supported on Sauce.

**Comment by apallin** [comment]
Thanks, this

**Comment by apallin** [comment]
Whoops!  I leave this to you all to decide if this is fixed and ready to be closed as of 1.5.  Seems to be working there and I wouldn't expect you to patch 1.4 at all.

**Comment by imurchie** [comment]
This does not clear anything up, but your test suite works if I pass in a `deviceName` of `"iPhone 6"` rather than `"iPhone Simulator"`. But the latter works for other tests.

I've tracked down the error to within the urllib package. Not sure what is going on.

**Comment by Xalior** [comment]
`Instruments.killAllSim = function () {
  xcode.getVersion(function (err, version) {
    // this is contrary to our usual pattern, but if getting the xcode version
    // fails, we couldn't have started simulators anyways/
    if (err) return;
    if (version >= "7") {
      logger.debug("Killall Simulator");
      exec('pkill -9 -f "Simulator"');
    } else if (version >= "6") {
      logger.debug("Killall iOS Simulator");
      exec('pkill -9 -f "iOS Simulator"');
    } else {
      logger.debug("Killall iPhoneSimulator");
      exec('pkill -9 -f iPhoneSimulator');
    }
  });
};
` from appium/node_modules/appium-instruments/lib/instruments.js

execs a pkill on all processes with "Simulator" in the parameters or commandname. I bet that's your cause!

-Dx
