### ISSUE TITLE
Double clicking on home button is iOS

### ISSUE THREAD

**Issue by gilsheps** [appium/appium#5998]
is there a way to double clicking on home button?
i need to test when double clicking on home button and return to the my app. 
runAppInBackground will not work in my case.

**Comment by SrinivasanTarget** [comment]
@gilsheps Don't think so, its possible in current appium version. Can you pls tell me why does runAppInBackground doesn't work in your case?

**Comment by scottdixon** [comment]
@gilsheps the latest Appium 1.5 beta contains a fix for backgrounding apps on iOS9+
https://github.com/appium/appium-ios-driver/pull/61

There's also an update to this fix (sans apple script) about to merge:
https://github.com/appium/appium-ios-driver/pull/63
