### ISSUE TITLE
Interacting with app level alert view fails on iOS when 'autoAcceptAlerts=true' capability is set

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#6001]
Interacting with app level alert views fails with unknown server-side error on iOS when `autoAcceptAlerts = true` capability is set. App level alert view is accepted through Ruby bindings using `alert_accept` method which calls `acceptAlert` method. App level alert view is actually dismissed correctly but error is still raised by `instruments`. Without `autoAcceptAlerts` capability everything is working fine. I just need to use `autoAcceptAlerts` because I need to dismiss system level push notification alert view before interacting with app level alert views.

Steps for more info about the use case
```
1. App is launched
2. System level push notification alert view is shown and dismissed correctly by Appium
3. User selects log out in the app
4. App level alert view is displayed
5. Accept app level alert view with acceptAlert method
6. App level alert view is dismissed but instruments raises an error "An unknown server-side error occurred while processing the command"
```

Environment
```
OS X 10.11.2
iOS 9.2
Xcode 7.2
Appium server v1.4.16
iOS simulator iPhone 6 (9.2)
Ruby 2.1.5p273
ruby_lib 7.0.0
```

Appium server log snippet
```
info: --> POST /wd/hub/session/dce5cd98-b7b5-4aa8-9f2c-7b10eace9028/accept_alert {}
info: [debug] Pushing command to appium work queue: "au.acceptAlert()"
info: [debug] Sending command to instruments: au.acceptAlert()
info: [debug] [INST] 2016-01-11 13:22:57 +0000 Debug: target.frontMostApp().alert().buttons()[1].tap()
info: [debug] [INST] 2016-01-11 13:22:57 +0000 Debug: Waiting for alert to close...
info: [debug] [INST] 2016-01-11 13:22:57 +0000 Debug: Waiting for alert to close...
info: [debug] [INST] 2016-01-11 13:22:58 +0000 Debug: Got new command 18 from instruments: au.acceptAlert()
info: [debug] [INST] 2016-01-11 13:22:58 +0000 Debug: evaluating au.acceptAlert()
info: [debug] Socket data received (93 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":13,"value":"An unknown server-side error occurred while processing the command."}
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"An unknown server-side error occurred while processing the command."},"sessionId":"dce5cd98-b7b5-4aa8-9f2c-7b10eace9028"}
info: <-- POST /wd/hub/session/dce5cd98-b7b5-4aa8-9f2c-7b10eace9028/accept_alert 500 2594.734 ms - 236
info: [debug] [INST] 2016-01-11 13:22:58 +0000 Error: VerboseError: An unknown server-side error occurred while processing the command.
```

**Comment by scottdixon** [comment]
@JaniJegoroff: do you hit the same issue running

i) iOS 8.4 or below w/ Appium 1.4.16
ii) iOS 9.2 w/ Appium 1.5 beta

**Comment by JaniJegoroff** [comment]
@scottdixon Yes, I'm able to reproduce issue with both cases:

i) iOS 8.4 w/ Appium 1.4.16
ii) iOS 9.2 w/ Appium 1.5 beta (v1.5.0-beta8 (REV d19c85fa5aa8359ea81f5fbe8c3fe977b45ea526))

**Comment by scottdixon** [comment]
Thanks. I wonder if it's the double up of `acceptAlert` and `autoAcceptAlert` - given you're using `autoAcceptAlerts`, can you omit `acceptAlert`?

Can you please share the test code?

**Comment by JaniJegoroff** [comment]
There are two alerts in this use case; APN alert (Apple Push Notification) which is system level and Logout alert which is app level. APN alert is dismissed correctly with `autoAcceptAlerts`. After that I use `acceptAlert` to dismiss Logout alert. Logout alert is dismissed but in spite of that `instruments` raises an error. So I can't omit `acceptAlert` because it is used for app level alert handling.

Unfortunately I can't share this test code. I will try to create separate example project where this can be reproduced.

**Comment by JaniJegoroff** [comment]
@scottdixon Here is one simple example project: https://github.com/JaniJegoroff/JLPermissions

Could you try it out?

**Comment by JaniJegoroff** [comment]
Grrr, I see. Looks like `autoAcceptAlerts` is handling **ALL** the alert views, system level and app level. Is that really correct behaviour? I was expecting it to handle only system level alerts.

**Comment by scottdixon** [comment]
@JaniJegoroff thanks for the sample code.

@imurchie - can you confirm: is this the expected behavior or a bug?

**Comment by imurchie** [comment]
This is the correct behavior. `autoAcceptAlerts` accepts _all_ alerts.

**Comment by scottdixon** [comment]
Thanks. In that case, I'll update the docs.
