### ISSUE TITLE
Problem with instruments (Xcode 7.2)

### ISSUE THREAD

**Issue by RamonBoza** [appium/appium#6010]
Hi all,

I've updated to appium 1.4.13 and Xcode to last version, with instruments being version 7.2.

When I try to execute an automation test I get in return:

Instruments Usage Error : Specified target process is invalid: com.apple.iTunes
instruments, version 7.2 (59503)

Doing some tests, if I execute the following

instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate  com.apple.iTunes

it works well.

but if I execute:

/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate  -w b5861ac2464be20d1b7a225b2c9c2b5573fdf02d com.apple.iTunes

it fails with the above message.

Has anyone got to that problem and found a solution? Thanks

**Comment by dpgraham** [comment]
This looks like an Xcode issue. Apple support or StackOverflow would be the best place to go for help on this type of issue.
