### ISSUE TITLE
appium console log - info: <-- POST /wd/hub/session is always shown each second

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#6011]
Hi,
Even after starting appium server with option  appium --log-level debug:error , I still see below log each second

info: <-- POST /wd/hub/session/be5eb704-921b-45df-a7a0-95c89f0df20c/timeouts/implicit_wait 404 0.640 ms - 40 
info: --> POST /wd/hub/session/6ec23037-b191-410c-a25c-b64de5280d30/timeouts/implicit_wait {"ms":0}

Is this a bug ?

Please review

**Comment by whopiecat** [comment]
Hey vikramvi,

There are several settings for --log-level.
Try other settings which reduce the display to just what you want to see displayed.

**Comment by SrinivasanTarget** [comment]
@triager please close
