### ISSUE TITLE
Document Missing Template Error: The operation couldn’t be completed

### ISSUE THREAD

**Issue by v0l0d** [appium/appium#6013]
Hello,
I see this issue appears from time to time, but that's what I have with git version, branch master (I did pull today)
The app is build for the simulator
```
/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 5s (9.0)" "/<fullpath>/RP Staging.app" -e UIASCRIPT "/Users/Shared/Jenkins/Library/Application Support/appium/bootstrap/bootstrap-e348cd8a155eb5e9.js" -e UIARESULTSPATH /tmp/appium-instruments
```

Error:
Instruments Trace Error : Failed to load document 'file:///tmp/appium-instruments/instrumentscli0.trace/' : (Error Domain=com.apple.instruments Code=-6 "Document Missing Template Error: The operation couldn’t be completed. (com.apple.instruments error -6.)")

Can you help me please?
I cleaned /tmp folder, did ```git clone --recursive appium``` and then ```./reset.sh```
But it doesn't help

P.S. I did a lot of testing, now I see that Appium has failed couple tests ('cause of error above), but suddenly it went forward and started testing (I guess ```--no-reset``` change the situation a bit)

**Comment by scottdixon** [comment]
@v0l0d can you git it a shot with Appium 1.5 beta? `npm install -g appium@beta`

**Comment by v0l0d** [comment]
@scottdixon 
thank you for reply

I did a long road installing it with npm and stuck with error:
> error: Could not find config file:  /Users/user/local/lib/node_modules/appium/.appiumconfig.json; looks like config hasn't been run. Please run reset.sh or appium configure.

p.s. just for the reference, I used this answer to install on OS X with NPM http://stackoverflow.com/questions/24813589/how-to-setup-appium-on-mac-os-to-run-automated-tests-from-java-classes-on-androi

**Comment by scottdixon** [comment]
@v0l0d - 1.5 eliminates much of the existing setup.

If you run `npm install -g appium@beta` and then `appium` from your terminal you should be good to go.

**Comment by v0l0d** [comment]
@scottdixon unfortunately the error is raised while running ```appium``` after installation with ```npm install -g appium@beta```

Here's the output

```appium```
> error: Could not find config file: /Users/user/local/lib/node_modules/appium/.appiumconfig.json; looks like config hasn't been run. Please run reset.sh or appium configure.
> error: uncaughtException: Could not find config file: /Users/user/local/lib/node_modules/appium/.appiumconfig.json; looks like config hasn't been run. Please run reset.sh or appium configure. date=Thu Jan 14 2016 03:23:13 GMT+0700 (ICT), pid=29861, uid=247, gid=247, cwd=/Users/user/local/lib/node_modules/appium, execPath=/Users/user/local/bin/node, version=v5.4.1, argv=[/Users/user/local/bin/node, /Users/user/local/bin/appium], rss=115793920, heapTotal=93066984, heapUsed=74327704, loadavg=[2.28466796875, 2.90283203125, 2.75048828125], uptime=3858339, trace=[column=13, file=/Users/user/local/lib/node_modules/appium/lib/helpers.js, function=exports.getAppiumConfig, line=326, method=getAppiumConfig, native=false, column=23, file=/Users/user/local/lib/node_modules/appium/lib/server/main.js, function=null, line=146, method=null, native=false, column=21, file=/Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=null, line=607, method=null, native=false, column=17, file=/Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=null, line=246, method=null, native=false, column=13, file=/Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=iterate, line=146, method=null, native=false, column=9, file=/Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=async.eachSeries, line=162, method=eachSeries, native=false, column=13, file=/Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=_asyncMap, line=245, method=null, native=false, column=23, file=/Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=Object.mapSeries, line=228, method=mapSeries, native=false, column=19, file=/Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js, function=Object.async.series, line=605, method=async.series, native=false, column=9, file=/Users/user/local/lib/node_modules/appium/lib/server/main.js, function=Object.main [as run], line=144, method=main [as run], native=false, column=10, file=/Users/user/local/lib/node_modules/appium/bin/appium.js, function=, line=57, method=null, native=false, column=26, file=module.js, function=Module._compile, line=397, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=404, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=343, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=300, method=Module._load, native=false, column=10, file=module.js, function=Function.Module.runMain, line=429, method=Module.runMain, native=false, column=18, file=node.js, function=startup, line=139, method=null, native=false, column=3, file=node.js, function=null, line=999, method=null, native=false], stack=[Error: Could not find config file: /Users/user/local/lib/node_modules/appium/.appiumconfig.json; looks like config hasn't been run. Please run reset.sh or appium configure.,     at exports.getAppiumConfig (/Users/user/local/lib/node_modules/appium/lib/helpers.js:326:13),     at /Users/user/local/lib/node_modules/appium/lib/server/main.js:146:23,     at /Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js:607:21,     at /Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js:246:17,     at iterate (/Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js:146:13),     at async.eachSeries (/Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js:162:9),     at _asyncMap (/Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js:245:13),     at Object.mapSeries (/Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js:228:23),     at Object.async.series (/Users/user/local/lib/node_modules/appium/node_modules/async/lib/async.js:605:19),     at Object.main [as run] (/Users/user/local/lib/node_modules/appium/lib/server/main.js:144:9),     at Object.<anonymous> (/Users/user/local/lib/node_modules/appium/bin/appium.js:57:10),     at Module._compile (module.js:397:26),     at Object.Module._extensions..js (module.js:404:10),     at Module.load (module.js:343:32),     at Function.Module._load (module.js:300:12),     at Function.Module.runMain (module.js:429:10),     at startup (node.js:139:18),     at node.js:999:3]

**Comment by scottdixon** [comment]
Hmm there shouldn't be any reference to appiumconfig.json in 1.5

Can you try:
```npm uninstall -g appium
npm install -g appium@beta
appium```

**Comment by v0l0d** [comment]
@scottdixon 
I have it also installed with DMG at /Applications
can it effect? 

I've started uninstall/install process (exactly as provided by you), though: are you sure about ```appium``` at the end of command in your last message?

**Comment by scottdixon** [comment]
It shouldn't conflict - please confirm it's closed when you're doing the uninstall / install.

My command got butchered, please refresh + see my updated previous comment.

**Comment by v0l0d** [comment]
@scottdixon 
yep, uninstall helped to launch it
And this particular issue is over

Though I'm still facing 'Launching instruments' issue. please see below. Can you please advice?
1. 
[Error: Failed getting devices, err: Error: Command '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -s devices' timed out after 12000ms.]
[iOSSim] Retrieving device name string for Xcode version 7.2

if I run this command in CLI it executes immediately 

2. 
[Instruments] Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Instruments.launch$ (lib/instruments.js:210:15)
    at tryCatch (/Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:355:11)
 [Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch]
[MJSONWP] Encountered internal error running command: Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Instruments.launch$ (lib/instruments.js:210:15)
    at tryCatch (/Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/Shared/Jenkins/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:355:11)

**Comment by scottdixon** [comment]
Can you please add a [gist](http://gist.github.com) of the full log?

**Comment by v0l0d** [comment]
https://gist.github.com/v0l0d/120de6f662e15fc2d64f

I see simulator screen is black while starting. Looks strange. Like something is holding it from starting. Though it is fine if I launch instruments command

**Comment by scottdixon** [comment]
Can you try going to iOS Simulator menu, and pressing "Reset Content and Settings", then run it again.

**Comment by v0l0d** [comment]
I already did it

how do I increase this timeout:
> [iOSSim] We will time out after 60000ms
> [iOSSim] Simulator booted in 71360ms
I have ```launchTimeout=600000```, but it didn't effect

btw it didn't finish booting, but was still in the middle of it

**Comment by v0l0d** [comment]
@scottdixon 
Can you please help with simulator boot timeout? I need to increase it, but ```launchTimeout``` has no effect. 
I did code search, but didn't find code

thank you!

**Comment by scottdixon** [comment]
Take a look at these docs: http://appium.io/slate/en/1.5/
