### ISSUE TITLE
Waiting for multiple elements at same time

### ISSUE THREAD

**Issue by subratkumarmandal** [appium/appium#6016]
Can Appium try to find more than one element at same time ?

**Comment by namannigam** [comment]
does that mean combining findElements(<element1 details>) && findElements(<element2 details) into one statement?

**Comment by dpgraham** [comment]
```java
public List<T> findElements(org.openqa.selenium.By by)
```

This method returns a list of elements that match the 'By' criteria. Other than that there aren't any methods that get more than one element simultaneously. You have to do them one after the other
