### ISSUE TITLE
highlighter going out of the text boxes

### ISSUE THREAD

**Issue by vatsas** [appium/appium#6017]
This is my second page , wherein i'm facing the issue .

<img width="377" alt="screen shot 2016-01-13 at 11 18 15 am" src="https://cloud.githubusercontent.com/assets/13148520/12286130/67ebc162-b9e7-11e5-89f6-4d8a023b8dd6.png">

**Comment by vatsas** [comment]
I have used xpath to capture , but the code having it does not work . It just stops.

**Comment by pr4bh4sh** [comment]
Can you describe your issue a bit more and post the logs as well.

**Comment by vatsas** [comment]
I am using Android 4.4.4 device , installing an hybrid app built using the ionic framework.  The above snapshot is the second page of the application. Observe the highlighter control (red box) is out of the frame . This is seen only in the second page , whereas this was working fine in first page (used xpath) .

I'm suspecting , when the page is traversed from first to second page , there may be an issue .

However, kindly look at the issue .


[appium_logs.txt](https://github.com/appium/appium/files/88875/appium_logs.txt)
 logs attached.

**Comment by pr4bh4sh** [comment]
Can you post the full image of the uiautomator/inspector as well, the one you posted seems cropped.

**Comment by vatsas** [comment]
<img width="1405" alt="screen shot 2016-01-14 at 12 06 37 pm" src="https://cloud.githubusercontent.com/assets/13148520/12317523/07ac6a46-bab8-11e5-9e9d-ae7f7bf7fae3.png">

I have uploaded the screenshot , Thanks Prabhash for taking a look ...

**Comment by pr4bh4sh** [comment]
You should log the issue here https://github.com/appium/appium-dot-app/issues
Anyway I never use Appium inspector for Android element inspections, use uiautomatorviewer. There is only one difference between them that is Appium inspector provides XPath.

**Comment by SrinivasanTarget** [comment]
You can log it here: https://github.com/appium/appium-dot-app/issues

**Comment by SrinivasanTarget** [comment]
@triager please close
