### ISSUE TITLE
Appium iOS: crash when try to install app to real device by "appium"

### ISSUE THREAD

**Issue by liu3821** [appium/appium#6018]
Appium Server 1.4.13 + Mac 10.10.5 + jdk1.8 + iPod touch 8.4.1( & iphone5s 9.1)
0. i need reset status of ios app, like login status, so i checked "Full Reset" on appium server.
1. uninstall app from real device, then run a simple test case
2. crash

I have follow the appium doc to prepared my environment.

PS: if there was a stable method to reset status of ios app pls tell me that.

Error message from appium server:"
info: [debug] App is not installed. Will try to install the app.

info: [debug] Cleaning up appium session

error: Failed to start an Appium session, err was: Error: Installing com.planetart.fpuk failed

info: [debug] Error: Installing com.planetart.fpuk failed
    at /Users/FrankL/Desktop/Appium1.4.13/Appium.app/Contents/Resources/node_modules/appium/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Installing com.planetart.fpuk failed)","origValue":"Installing com.planetart.fpuk failed"},"sessionId":null}
info: <-- POST /wd/hub/session 500 3219.753 ms - 194 

info: [IOS_SYSLOG_ROW ] Jan 13 15:17:30 Adams-iPod-touch syslog_relay[306] <Notice>: syslog_relay read 51 total bytes:

info: [IOS_SYSLOG_ROW ] ========================
info: [IOS_SYSLOG_ROW ] ASL is here to serve you
info: [IOS_SYSLOG_ROW ] Jan 13 15:17:30 Adams-iPod-touch syslog_relay[306] <Notice>: syslog_relay found the ASL prompt. Starting...

info: [IOS_SYSLOG_ROW ] Jan 13 15:17:32 Adams-iPod-touch mobile_installation_proxy[295] <Error>

"

**Comment by SrinivasanTarget** [comment]
@liu3821 you can give a try in appium latest version i.e 1.5.2.If you still find any issues please raise a new issues with appium logs in form of gist

**Comment by SrinivasanTarget** [comment]
@triager please close
