### ISSUE TITLE
appium-instrument link to previous version with commit f0a125ddb5a1c42cc82b8ae9621df6b98f778e14

### ISSUE THREAD

**Issue by camillake** [appium/appium#6019]
I just fork appium and want to make some changes on apium-instruments. The head is point to f0a125ddb5a1c42cc82b8ae9621df6b98f778e14.

**Comment by scottdixon** [comment]
This is because appium-instruments is getting ready for the Appium 1.5 release. 

Please consider making changes on the 1.5 beta branch and then you can hack on the https://github.com/appium/appium-instruments package

**Comment by camillake** [comment]
@scottdixon 
I got it. Thanks a lot.

**Comment by scottdixon** [comment]
Yep, thats it.
