### ISSUE TITLE
Appium iOS: Ability to capture and parse custom log. 

### ISSUE THREAD

**Issue by xiaofengC** [appium/appium#6021]
we are developing an library with little ui, the only outputs are logs. I think is a necessary feature!

**Comment by scottdixon** [comment]
Are you referring to outputting iOS logs? You can do so with the `showIOSLog` default capability.

`{ showIOSLog: true }`

**Comment by xiaofengC** [comment]
oh ok ,let me try this , but can I look for certain symbols in my log as the result of a test case?
