### ISSUE TITLE
Record issues

### ISSUE THREAD

**Issue by huangxionging** [appium/appium#6022]
# Record issues 
* Forgive my poor english
* Appium 1.4.13 Mac
* iOS(Objective-C)
* I use function of Appium Inspector Record 
* swipe

```Objective-C
[webDriver executeScript: @"mobile: swipe" arguments:@[@{@"touchCount" : @(1), 
@"duration" : @(3)  ,@"startX" : @(13), @"startY" : @(45), @"endX" : @(13), 
@"endY" : @(100)}] error: &error];
```
### Print Info
* info: [debug] Tried to execute non-existent mobile command 'swipe'. Most mobile commands have been ported to official client library methods. Please check your Appium library for more information and documentation
* info: [debug] Responding to client that a method is not implemented

* {"status":13,"sessionId":"140fed32-cf15-44f8-8cb2-8c91b076166c","value":{"message":"Not yet implemented. Please help us: http://appium.io/get-involved.html"}}

**Comment by SrinivasanTarget** [comment]
@huangxionging Refer: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md

try using a latest version of appium i.e 1.5.2 now.

mobile:swipe is deprecated in latest versions of appium.

Feel free to log an issue if there is any along with logs inform as gist.

**Comment by SrinivasanTarget** [comment]
@triager please close
