### ISSUE TITLE
Unable to scroll the page in an android application

### ISSUE THREAD

**Issue by sanatzzz** [appium/appium#6023]
In the application in which I am testing I need to scroll the page to a particular element. So,we tried using the following
D8.scrollTo("XXXX");
D8.findElement(By.name("XXXXXX"));
but this works only when we use AndroidDriver. The problem is that in the app on which I'm performing my testing I need to switch from mobile to portal and portal to mobile in the same test case. So, for performing portal operations I should use RemoteWebDriver. So, please provide a solution to use scroll functionality in my testing without using AndroidDriver.

**Comment by kcinman11358** [comment]
What type of element is it?

**Comment by SrinivasanTarget** [comment]
It's an issue with java-client.Fix is in progress. Issue is here: https://github.com/appium/java-client/issues/342

**Comment by SrinivasanTarget** [comment]
@triager please close
