### ISSUE TITLE
Appium iOS: crash when try to open a app that not closed from backend

### ISSUE THREAD

**Issue by liu3821** [appium/appium#6024]
Appium Server 1.4.13 + Mac 10.10.5 + jdk1.8 + iPod touch 8.4.1
0. run case,  success
1. open app manually
2. run case, try to open app
3. appium try several times to open app, every time was just only see splash page then back to desktop
, sometimes it can open success after a while
4. may crash

**Comment by SrinivasanTarget** [comment]
@liu3821 you can give a try in appium latest version i.e 1.5.2.If you still find any issues please raise a new issues with appium logs in form of gist

**Comment by SrinivasanTarget** [comment]
@triager please close
