### ISSUE TITLE
ios-webkit-debug-proxy.md seems out-of-date

### ISSUE THREAD

**Issue by CMTaylor** [appium/appium#6027]
The ios-webkit-debug-proxy.md document says:

"NOTE: As of April 2, 2015, the primary ios-webkit-debug-proxy repository has not been updated for some time. We currently recommend using James Chuong's fork. To do so, you'll need to build from source. If you're unfamiliar with building with GMake, try following the steps below."

but https://github.com/google/ios-webkit-debug-proxy was last updated on 7-Oct-15 for iOS 9 support.

Please update this documentation file with the latest information.

**Comment by imurchie** [comment]
Updated in 1.5 docs.
