### ISSUE TITLE
Remember Android emulator state for use with rebooting

### ISSUE THREAD

**Issue by filmaj** [appium/appium#6028]
Certain Appium functionality requires rebooting an Android target (such as setting device locale).

This can be problematic with certain configurations of the Android emulator. In particular, the Android emulator supports snapshots (at least on Android 4.3 and older - [newer Android emulator versions have an Android SDK bug that makes this feature unusable](https://code.google.com/p/android/issues/detail?id=65080)), which allows for much-faster boot-up times.

However, since snapshots essentially boot the emulator off a particular RAM state, rebooting with them can lead to interesting side effects. In particular, certain emulator states get "wiped" back to the snapshot state when you reboot a snapshot-powered emulator. One such property is date and time.

Feature request: before Appium goes to reboot an Android emulator, have it collect certain emulator states (so far, the only thing I can think of being affected is date and time), and, upon successful completion of emulator reboot, reset these states to the pre-boot values.

Let me know what y'all think!

**Comment by dpgraham** [comment]
We're currently looking into Android 7 (Nougat) support for a future sprint, so this is something that we may revisit in said sprint.

**Comment by mykola-mokhnach** [comment]
In appium@beta UIA2 driver got a [feature](https://github.com/appium/appium-android-driver/pull/630), which allows to directly control the emulator using its console commands.
