### ISSUE TITLE
1.5.0-beta11: Appium return "SessionNotCreatedError" error

### ISSUE THREAD

**Issue by mehmetboraezer** [appium/appium#6032]
Hello, I'm trying to do the test in beta version for Appium but did not succeed.

Xcode Version : 7.2 (7C68)
Appium Version : 1.5.0-beta11
iOS Version : 9.2 (13C75)(This is real device.)

Appium started with this parameters : 
```
appium --udid a1ef66f78b8357bdaa4d849e89c107okeo2124rw --command-timeout 20000
```

At the end Appium return the following error message: 
"A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): platformName IOS is not included in the list."

But i don't know why. Because "platformName: IOS" is valid desired capabilities.

[Appium session log file](https://github.com/appium/appium/files/91968/test.txt)

**Comment by moizjv** [comment]
@mehmetboraezer thanks for bringing this up. We have [fixed](https://github.com/appium/appium-base-driver/pull/43) this in latest version of 1.5 but it is in process of releasing. You can try using `iOS` in cap till then.

**Comment by scottdixon** [comment]
Please reopen if any issues.
