### ISSUE TITLE
Installing on Raspberry Pi

### ISSUE THREAD

**Issue by Mattwhooo** [appium/appium#6033]
I'm trying to install Appium from NPM on a Raspberry Pi.  I'm using Node 5.4 installed from LinuxBrew.  I've copied the install log here: https://gist.github.com/Mattwhooo/d20ce5b898dad2644e77

Help me Appium team you're my only hope :-)

**Comment by markdb314** [comment]
I have the same problem, it looks like issue #5700 was meant to fix this, but I don't get why I don't see that change when I install v1.4.16.  In the appium package.json I see version 1.4.16, but the "ws" package version is still listed as ~0.7.1.  Confused...

**Comment by Mattwhooo** [comment]
It turns out my problem was the Android SDK as there is not an ARM version of it.  I was able to follow the instructions here: http://www.timelesssky.com/blog/develop-app-on-android-with-android-sdk to get the SDK going and am now working through a few more issues.  I can now install from NPM but am getting an 'Device Android is not configured' Error when I try to run test.  I read in another issue that compiling from source may resolve this so I'm working through that now.

**Comment by markdb314** [comment]
It appears that the npm shrinkwrap file is still referencing ws 0.7.2.  I'll admit I'm not totally familiar with how npm shrinkwrap works, but maybe something went wrong in the process of building the npm package?

**Comment by imurchie** [comment]
Interesting. I'd be into hearing how the installation and running on the Raspberry Pi works out. I tried a year ago but it was a no-go.

**Comment by Mattwhooo** [comment]
I've been able to get a little further in the install process now.   I found in another thread that API 19 is required for the Android sdk and I only had 20, 21, 22 installed.  I'm not getting further in to the build process, but it is giving the following error:

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [aapt] /home/pi/android/android-sdk-linux/build-tools/23.0.2/aapt: 2: /home/pi/android/android-sdk-linux/build-tools/23.0.2/aapt: Syntax error: newline unexpected (expecting ")")

BUILD FAILED
/home/pi/android/android-sdk-linux/tools/ant/build.xml:649: The following error occurred while executing this line:
/home/pi/android/android-sdk-linux/tools/ant/build.xml:694: null returned: 2

Total time: 5 seconds
---- FAILURE: reset.sh exited with status 1 ----

**Comment by imurchie** [comment]
Which step is this in? It may be possible to skip building some of the stuff, if necessary.

**Comment by Mattwhooo** [comment]
It looks like its trying to build unlock.apk.  I've put the full build verbose build section of the logs here.  https://gist.github.com/Mattwhooo/578570793406c4cb730b  

I don't know a lot about the android build process so I'm some what at a loss for where to go next.   I'm currently trying a different version of the android build tools so see if that resolves.

**Comment by Mattwhooo** [comment]
when using an older version of the build tools i get the same failure point but a different message;

build tools 19.1.0;
  [aapt] /home/pi/android/android-sdk-linux/build-tools/19.1.0/aapt: 1: /home/pi/android/android-sdk-linux/build-tools/19.1.0/aapt: Syntax error: "(" unexpected

build tools 23.0.2

[aapt] /home/pi/android/android-sdk-linux/build-tools/23.0.2/aapt: 2: /home/pi/android/android-sdk-linux/build-tools/23.0.2/aapt: Syntax error: newline unexpected (expecting ")")

**Comment by imurchie** [comment]
I'm not sure, either, how to proceed.

But I guess the next step is to investigate what is happening in the `build.xml`:

```shell
/home/pi/android/android-sdk-linux/tools/ant/build.xml:649: The following error occurred while executing this line:
/home/pi/android/android-sdk-linux/tools/ant/build.xml:693: null returned: 2
```

**Comment by Mattwhooo** [comment]
Those lines are point back at aapt.  I'm starting to think that it's a compilation problem with aapt and working through some instructions found http://www.timelesssky.com/blog/building-android-sdk-build-tools-aapt-for-debian-arm to compile.

**Comment by Mattwhooo** [comment]
relevant lines from build file:

<aapt executable="${aapt}"
                    command="package"
                    verbose="${verbose}"
                    manifest="${out.manifest.abs.file}"
                    originalManifestPackage="${project.app.package}"
                    androidjar="${project.target.android.jar}"
                    rfolder="${gen.absolute.dir}"
                    nonConstantId="${android.library}"
                    libraryResFolderPathRefid="project.library.res.folder.path"
                    libraryPackagesRefid="project.library.packages"
                    libraryRFileRefid="project.library.bin.r.file.path"
                    ignoreAssets="${aapt.ignore.assets}"
                    binFolder="${out.absolute.dir}">

**Comment by imurchie** [comment]
Alright.

I also wonder if it is possible to get ant to print out the whole `aapt` command it is running, in order to just run that.

**Comment by Mattwhooo** [comment]
Good thought, save a lot of time in debug cycles of looking at this.  I will look into it.

**Comment by Mattwhooo** [comment]
@imurchie  You mentioned earlier about potentially skipping this step. If I can get this build process working on another machine would it be viable to just put the apk where it needs to go?

**Comment by imurchie** [comment]
I am not actually sure. I think that is reasonable on most architectures (it's what the Mac app does, for instance), but who knows with a Raspberry Pi.

**Comment by Mattwhooo** [comment]
I was able to get it working by replacing the android build tools aapt, zipalign, and aidl with arm compiled counterparts from this repo:

https://github.com/skyleecm/android-build-tools-for-arm/tree/master/out/host/linux-arm/bincd 

It still failed a little further on trying to build selendroid, but i didn't need that for what i wanted to test.  I am now able to run automation against a native app (though it takes 3-4 minutes for each test to start because the pi takes so long to resign the app).  I'm not able to run web automation yet because I haven't found an arm compiled chromedriver yet.  Thanks for your help @imurchie

**Comment by imurchie** [comment]
That is pretty awesome! Slow run times aside, it's cool that it works on a Raspberry Pi.

**Comment by prateekchawla** [comment]
@Mattwhooo  How to install npm and node on Raspberry PI. I am currently landing into some errors
and what version shall i install to successfully run appium

**Comment by Mattwhooo** [comment]
@prateekchawla I got his running a couple of years ago, but it was unusable.  Mostly this was just playing around to see if it works.  I wouldn't recommend going down this path for anything but fun.

Having said that I would have just followed instructions I found on google for getting Node installed.  There should be several as thats a very common thing to be installing on a Pi

**Comment by Mattwhooo** [comment]
Also, I have no idea what version I installed at this point, it would have been whatever Appium recommended at the time and it could have easily changed since then

**Comment by prateekchawla** [comment]
That makes sense. I would like to know why it was unusable. I am trying to run Appium tests on device connected to raspberry pi and then run them locally. Will that be a slow process or something?

**Comment by prateekchawla** [comment]
@Mattwhooo  Also, were you running some appium tests on your pi for playing around ?

**Comment by Mattwhooo** [comment]
@prateekchawla  Yes, speed was the primary problem, though it may have also been unstable and the device would disconnect all the time (if I remember correctly thats why I abandoned this).  The biggest time suck was re-signing the APK  and that step was adding several minutes to each test.  I don't think I ever got mobile web working so your results may vary.  I was probably also doing this on a Pi 2 as I don't think the Pi 3 were available at the time.  

For your information I was playing around with a way to have a 'Dock' for always connected appium devices.  I tried with the Raspberry Pi, but also with the Kangaroo https://www.amazon.com/Kangaroo-MD2B-Mobile-Desktop-Computer/dp/B017J20D8U

I was registering the appium server as a node on selenium grid and then running the test from my laptop.

**Comment by Mattwhooo** [comment]
More recent mention of the challenges faced with mobile web (though for totally different reasons) https://github.com/timgrossmann/InstaPy/issues/126

**Comment by prateekchawla** [comment]
Thankyou @Mattwhooo  for sharing your experience.

**Comment by MummanaSubramanya** [comment]
thanks for the info. Was finally able to run tests from raspberrypi  :)

**Comment by Mattwhooo** [comment]
@MummanaSubramanya Can you share what you were able to accomplish here?  I'm curious of what people are using Pi for in testing and how it goes!

**Comment by MummanaSubramanya** [comment]
Sure..!! my task was to run the appium c# tests for a hybrid application on RPI 3 B+. The main challenge was to get the android-sdk and appium for arm processor. Not only that even I needed chrome and chromedriver arm version. Google helped to get all the things working. :)
