### ISSUE TITLE
How do I turn off the SIM card warning before the test?

### ISSUE THREAD

**Issue by mehmetboraezer** [appium/appium#6034]
Hello, i use the real iOS devices. If this is required, my provision script reboot the device. But after restart, iOS show alerts (SIM card, update or etc..).

Trying to restart the device and run the test I get the following errors.

```
Could not start script, target application is not frontmost.
or
Automation Instrument ran into an exception while trying to run the script. UIAScriptAgentSignaledException
```

I can't use "autoAcceptAlerts" because these alerts are displayed without opening the application.

**Comment by williamjablonski** [comment]
Any solution for this?

**Comment by mehmetboraezer** [comment]
I haven't found the solution yet to using software methods. @williamjablonski maybe you can plug inactive sim card.

**Comment by dpgraham** [comment]
Unfortunately there's no way to make Appium dismiss alerts that are already on the device before tests start.
