### ISSUE TITLE
Cannot download appium mac osx version

### ISSUE THREAD

**Issue by erolyapici** [appium/appium#6038]
https://bitbucket.org/appium/appium.app/downloads/appium-1.4.13.dmg
This file not finish download file. 178MB downloaded but not finish

**Comment by mehmetboraezer** [comment]
You can download the file with wget command.

```
wget https://bitbucket.org/appium/appium.app/downloads/appium-1.4.13.dmg
```

**Comment by namannigam** [comment]
related : https://discuss.appium.io/t/downloads-not-completing-28-10-2015/6781/8

**Comment by moizjv** [comment]
Thanks @mehmetboraezer and @namannigam. @erolyapici hope suggestions fixed your issues.
