### ISSUE TITLE
Appium can not recognize element in different xml declaration(java) in Android.

### ISSUE THREAD

**Issue by yisake** [appium/appium#6040]
It seems appium can not recognize element in different xml files defined in java code. My Android develop tell me that some page is not is the same declaration. The page_source method also can not dump the screenshot.

*It seems after I click the sort button, the new page is displayed in the front of main page.  What method can i do for change the xml files.

**Comment by scottdixon** [comment]
Can you please elaborate + provide an example test?

**Comment by yisake** [comment]
The issue is same as ##6050
https://github.com/appium/appium/issues/6050

I met the problem with my uiautomatorviewer , It can not locate the control front,It only locate the control, So appium can not locate the control also(because appium depends on uiautomator)

I can offer the application(.apk), please tell me if you can access the address or not.
http://pan.baidu.com/s/1i42X3Lz

If you can access the address, please download the apk and test. After install, please click 二手房，位置，and use uiautomatorviewer to check the controls.

**Comment by dpgraham** [comment]
If this is still an issue, let me know and I'll re-open as long as you provide Appium logs.
