### ISSUE TITLE
Instruments died while responding to command, please check appium logs

### ISSUE THREAD

**Issue by bindubudha** [appium/appium#6041]
This is my setting:
appium server version: 1.4.16
Mac OS: 10.11.1
Xcode version: 7.1
iOS simulator: iPhone 5 (8.4)

Instruments is crashed while executing a command. 
It used to work perfectly fine, but, not sure why I am getting this error now. 

Appium log is attached here. 
[Appium_instruments_log.txt](https://github.com/appium/appium/files/94209/Appium_instruments_log.txt)

**Comment by nuggit32** [comment]
I'm seeing same type of problem as well, appears the application is 
Appium server 1.4.16
IPhone 6 Plus Real Device 
IOS Version 8.4.1

When clicking some buttons the app crashes.  This cannot be simulated manually only through automation.  "info: [debug] [INST] 2016-01-21 20:33:09 +0000 Fail: The target application appears to have died"


info: --> POST /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/timeouts {"type":"implicit","ms":0}
info: [debug] Set iOS implicit wait to 0ms
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"fb793db5-654b-44d6-8501-56d30ad78244"}
info: <-- POST /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/timeouts 200 0.869 ms - 76 {"status":0,"value":null,"sessionId":"fb793db5-654b-44d6-8501-56d30ad78244"}
info: --> GET /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/context {}
info: [debug] Responding to client with success: {"status":0,"value":"NATIVE_APP","sessionId":"fb793db5-654b-44d6-8501-56d30ad78244"}
info: <-- GET /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/context 200 1.202 ms - 84 {"status":0,"value":"NATIVE_APP","sessionId":"fb793db5-654b-44d6-8501-56d30ad78244"}
info: --> POST /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/elements {"using":"id","value":"Hide Account"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementsByAccessibilityId('Hide Account')"
info: [debug] Sending command to instruments: au.getElementsByAccessibilityId('Hide Account')
info: [debug] [INST] 2016-01-21 20:33:08 +0000 Debug: evaluation finished
info: [debug] [INST] 2016-01-21 20:33:08 +0000 Debug: responding with:
info: [debug] [INST] 2016-01-21 20:33:08 +0000 Debug: Running system command #50: /usr/local/Cellar/node/5.1.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] [INST] 2016-01-21 20:33:09 +0000 Debug: Got new command 50 from instruments: au.getElementsByAccessibilityId('Hide Account')
info: [debug] [INST] 2016-01-21 20:33:09 +0000 Debug: evaluating au.getElementsByAccessibilityId('Hide Account')
info: [debug] [INST] 2016-01-21 20:33:09 +0000 Fail: The target application appears to have died
info: [debug] [INST] 2016-01-21 20:33:09 +0000 Debug: evaluation finished
info: [debug] [INST] 2016-01-21 20:33:09 +0000 Debug: responding with:
info: [debug] [INST STDERR] 2016-01-21 14:33:10.015 instruments[50291:8747423] Attempting to change event horizon while disengage
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":[]}
info: [debug] Id selector, 'Hide Account', not found in Localizable.strings.
info: [debug] Pushing command to appium work queue: "au.getElementsById('Hide Account')"
info: [debug] Sending command to instruments: au.getElementsById('Hide Account')
info: [debug] [INST] 2016-01-21 20:33:09 +0000 Debug: Running system command #51: /usr/local/Cellar/node/5.1.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":[]}...
info: [debug] [INST] Instruments Trace Complete (Duration : 68.301582s; Output : /tmp/appium-instruments/instrumentscli0.trace)
info: [debug] [INSTSERVER] Instruments exited with code 0
info: [debug] Cleaning up after instruments exit
info: [debug] Instruments exited unexpectedly
info: [debug] Shutting down command proxy and ignoring any errors
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Stopping iOS log capture
info: [debug] Reset not set, not ending sim or cleaning up app state
info: [debug] We were in the middle of processing a command when instruments died; responding with a generic error
info: [debug] Cleaning up appium session
info: [debug] Condition unmet after 2097ms. Timing out.
info: [debug] Responding to client with error: {"status":13,"value":{"message":"Instruments died while responding to command, please check appium logs","name":"UnknownError","origValue":"Instruments died while responding to command, please check appium logs"},"sessionId":null}
info: <-- POST /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/elements 500 2098.882 ms - 230 
info: --> POST /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/timeouts {"type":"implicit","ms":1000}
info: <-- POST /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/timeouts 404 0.660 ms - 40 
info: --> GET /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/screenshot {}
info: <-- GET /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/screenshot 404 1.004 ms - 40 
info: --> POST /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/timeouts {"type":"implicit","ms":0}
info: <-- POST /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/timeouts 404 1.098 ms - 40 
info: --> POST /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/timeouts {"type":"implicit","ms":1000}
info: <-- POST /wd/hub/session/fb793db5-654b-44d6-8501-56d30ad78244/timeouts 404 0.642 ms - 40 
Tests run: 5, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 76.025 sec <<< FAILURE! - in TestSuite
hideAccounts(com.cri.fnbo.ios.accounts.HideAllAccountsExceptOne)  Time elapsed: 34.289 sec  <<< FAILURE!
org.openqa.selenium.remote.SessionNotFoundException: 
Command duration or timeout: 4 milliseconds
Build info: version: '2.49.0', revision: '365eeb44deba2067b1761c8862ef21d55250e063', time: '2016-01-13 11:57:39'
System info: host: 'herberts-MacBook-Pro.local', ip: '10.40.112.81', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.2', java.version: '1.8.0_65'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{networkConnectionEnabled=false, warnings={}, bundleId=FNB.QA-FNB-Kansas, databaseEnabled=false, deviceName=CRi iPhone 6, platform=MAC, desired={bundleId=FNB.QA-FNB-Kansas, platformName=iOS, udid=auto, deviceName=CRi iPhone 6}, webStorageEnabled=false, locationContextEnabled=false, browserName=iOS, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=auto}]
Session ID: fb793db5-654b-44d6-8501-56d30ad78244
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:164)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:863)
	at io.appium.java_client.pagefactory.AppiumElementLocator.changeImplicitlyWaitTimeOut(AppiumElementLocator.java:115)
	at io.appium.java_client.pagefactory.AppiumElementLocator.waitFor(AppiumElementLocator.java:133)
	at io.appium.java_client.pagefactory.AppiumElementLocator.findElements(AppiumElementLocator.java:167)
	at io.appium.java_client.pagefactory.interceptors.InterceptorOfAListOfElements.intercept(InterceptorOfAListOfElements.java:44)
	at $java.util.ArrayList$$EnhancerByCGLIB$$17343041.get(<generated>)
	at com.cri.fnbo.ios.accounts.HideAllAccountsExceptOne.hideAccounts(HideAllAccountsExceptOne.java:116)

**Comment by scottdixon** [comment]
@bindubudha - did you make progress? It looks like the app is crashing:
` Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'`
