### ISSUE TITLE
Failing to launch SafariLauncher app on device

### ISSUE THREAD

**Issue by Chetan-A-G** [appium/appium#6049]
I have successfully deployed the SafariLauncher.app on the device through Xcode. When i am trying to launch the safari browser getting below error.
INST STDERR] 2016-01-18 02:45:28.641 instruments[677:9597] Attempting to change event horizon while disengage

info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: Permission to debug com.internal.ent2.determinations.mobile was denied. The app must be signed with a development identity (e.g. iOS Developer).
info: [debug] [INST STDERR] 2016-01-18 02:45:28.643 instruments[677:9597] Attempting to change event horizon while disengage

error: Could not pre-launch appium: Error: Instruments crashed on startup

Pls help to solve this.

**Comment by scottdixon** [comment]
Which code sign identity are you using?
