### ISSUE TITLE
Landscape orientation is not working for iPhone 6

### ISSUE THREAD

**Issue by yadavgabhi** [appium/appium#6054]
I am facing issue with change orientation for iPhone 6. Below are the versions of iOS and appium I already tried with different combinations:

iOS: 9.0, 9.2
appium: 1.4.13, 1.4.14

I tried below codes to change the orientation of iPhone 6 but no luck and same code is working fine for iPad Air:
1. capabilities.setCapability("orientation", "LANDSCAPE");
2. ((AppiumDriver) driver).rotate(ScreenOrientation.LANDSCAPE);
3. ((IOSDriver) driver).rotate(ScreenOrientation.LANDSCAPE);

If anybody have solution, please suggest

**Comment by moizjv** [comment]
@yadavgabhi i tested iPhone 6 9.2 using https://github.com/appium/appium-ios-driver/blob/master/test/e2e/safari/screenshot-specs.js#L18 it works fine.

**Comment by moizjv** [comment]
Can you paste appium logs. Also i used appium 1.5 beta

**Comment by moizjv** [comment]
Also [forum](http://discuss.appium.io) is a good place to ask questions

**Comment by yadavgabhi** [comment]
I logged this one first in discussion forum, but did not got any response thats why I put same here.
https://discuss.appium.io/t/landscape-orientation-is-not-working-for-iphone-6/8004

I tried with below versions, as already mentioned in details:
iOS: 9.0, 9.2
appium: 1.4.13, 1.4.14

Let me try with 1.5 beta then I will let you know the status

**Comment by yadavgabhi** [comment]
@moizjv Can you please suggest from where I can download the appium 1.5 beta?

**Comment by HemaSundarPenugonda** [comment]
Even i am facing the same issue.
@moizjv I tried with the below env and still Orientation is not changing:

Device : iPhone 6
iOS version : 9.2
Appium Version : Appium v1.5.0-beta11 (REV 2134d379bd4884960aded95a522d62ba58d9c55d)

Please find the logs attached.
[https://gist.github.com/HemaSundarPenugonda/e9a2a749685bc2feb142](url)

**Comment by ShankarGargXebia** [comment]
Appium and Landscape is working fine. That was a bug in Application under Test. Please close the issue.

**Comment by scottdixon** [comment]
@yadavgabhi: best way to get 1.5 beta: `npm install -g appium@beta`

@ShankarGargXebia: Thanks. Reopen if any issues.
