### ISSUE TITLE
Changing device language before launching tests

### ISSUE THREAD

**Issue by andrepm06** [appium/appium#6056]
have the following scren scenario:

1 - I have to check if my (pyhsicial)device is in english. If not, i have to switch to english;

2 - Open my application and run my tests.

I wrote two functions, one to check the language and the other one to switch the language. Then, in setUp() i check if is english.

Here's me code:

def setUp(self):
    desired_caps = {}
    desired_caps['platformName'] = 'Android'
    desired_caps['platformVersion'] = '4.4'
    desired_caps['deviceName'] = '0429058934'
    desired_caps['app'] = os.path.abspath(os.path.join(os.path.dirname(__file__),'C:/Users/andre.mendes/Desktop/workspace/powerpro/apps/powerpro.apk'))
    desired_caps['appPackage'] = 'com.psafe.powerpro'
    desired_caps['appActivity'] = '.MainActivity'
    desired_caps['autoLaunch'] = False
    self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
    self.driver.implicitly_wait(15) 
    getLang = "adb -s 0429058934 shell getprop persist.sys.language"        
    ret = subprocess.check_output(getLang)
    lang = ret.strip()
    if lang != 'en':
        os.system("adb -s 0429058934 shell am start -a android.settings.LOCALE_SETTINGS")
        eng = self.driver.find_element_by_name('English (United Kingdom)')
        action = TouchAction(self.driver)
        action.press(eng).perform()
        action.move_to(x=0, y=50).perform()
        self.driver.find_element_by_name('English (United States)').click()
    self.driver.launch_app()    

But how i do it without lanching my application? I tried desired_caps['autoLaunch'] = False, but it keep getting TypeError: Cannot read property 'sendAction' of null

**Comment by moizjv** [comment]
You can use `language` [desired capability](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md)

**Comment by moizjv** [comment]
this does not look like a bug. Can you use [forum](https://discuss.appium.io/)
