### ISSUE TITLE
Android emulator doesn't get launched automatically like iOS simulator

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#6057]
Please refer to https://github.com/appium/java-client/issues/300 comment from Jonahss

starting server externally with appium command without any flags , do launch iOS simulator mentioned in capabilities but this doesn't happen for android emulator even though it's mentioned in capabilities.

**Comment by moizjv** [comment]
@vikramvi yes it is nice to have feature; but it requires some set up on user end like user should have pre created android emulator with particular name. I am going to mark this as feature request.

**Comment by prolificcoder** [comment]
Also I may always want to run this on a device because my main machine may have little screen or low memory to run a good emulator.

**Comment by imurchie** [comment]
Setting the `avd` capability will get you this.
