### ISSUE TITLE
ANDROID - Pressing ENTER - is it possible to send android IME_ACTIONS via appium

### ISSUE THREAD

**Issue by darragk** [appium/appium#6062]
We have an Android APP where we need to press the ENTER key after entering a code. I have researched this all over and tried all kinds of key events (66, 86, etc), have tried to get the APP developer to listen for the ENTER key but nothing works. I have had to go down the route of using a hardcoded location tap to click the keyboard - which is clearly not ideal and only works on one device.

On speaking further to the developer, he says that the only thing that is triggered on pressing enter is an IME_ACTION in this case IME_ACTION_SEND. I am wondering is there a way to get appium to trigger such an action such as IME_ACTION_SEND?

I am using Ruby with appium_lib.
Android API 19 (Genymotion emulator but also tried strandard Android emulator.)

•Platform : Android
•Appium version 1.4.0.0
•Genymotion Emulator
•Language Ruby
•My OS Windows 7

**Comment by scottdixon** [comment]
Any luck with this?

Seems like they had the same requirement: https://qxf2.com/blog/android-appium-press-enter-soft-keyboard/

Solution was to manually tap the enter key.

**Comment by darragk** [comment]
Hi,

We have ended up with hardcoded location pressing of the enter key too -  which is not ideal. That is why I was wondering if appium could receive IME_ACTIONs.

Thanks,
Kirsty
