### ISSUE TITLE
iOS:  element.displayed? returning true for Non-visible items in Inspector

### ISSUE THREAD

**Issue by shermanericSF** [appium/appium#6063]
Hey there:
This is very similar to https://github.com/appium/appium/issues/4404 - except this is on iOS.

Environment:
Xcode 7.2
iOS Simulator 9.2 - iPhone 5S
Appium Version: 1.4.16

Steps to Reproduce:
1.  Start up an Arc session.
2.  Navigate to the page to inspect.
3.  Interrogate the app looking for visible and non-visible elements.

Expected Behavior:
Elements that are not visible should yield _false_ when running find_element(@element).displayed? commands.

Actual Result:
Elements that are not visibile are yielding true in this situation.  See forthcoming screen shot.

Note:
This window that is false reporting actually exists, it is underneath our help screen in this case.

Let me know if you need more information.  I can attach a full gist if you'd like.
Thanks!
Eric
![screen shot 2016-01-25 at 9 00 07 am](https://cloud.githubusercontent.com/assets/10579118/12557986/4325f4f6-c342-11e5-9aeb-e6c405b572ef.png)

**Comment by mehmetboraezer** [comment]
Hi @shermanericSF , you are using "id" attribute. I think this is wrong. Maybe you should use "name" attribute?

```
find_element(:name,"Main Menu").displayed?
```

**Comment by rompic** [comment]
i have a similar problem: https://discuss.appium.io/t/isdisplayed-on-ios/7917

**Comment by shermanericSF** [comment]
Hi @mehmetboraezer 
First of all, thanks for the speed reply!
Alas, finding the element by name yields the same error. 
In addition, looking at the inspector, ID should work IMHO as there is a label filled out.

Let me know if you need any more information.

Thanks in advance!
Eric

**Comment by pappy-o** [comment]
FWIW: I'm also running into certain iOS elements that always return true for .isDisplayed(). These are just UIAButton elements (happens regardless of locator strategy).

Same env as the OP.

**Comment by gselsidi** [comment]
I have the complete opposite issue, .isvisible .isdisplayed .isenabled are all returning false, even though the element and it's attributes are true, and visible.

**Comment by rompic** [comment]
the interesting thing is.. if i copy the xml from the inspector (via the copy button) it is correctly defined in the xml.

can you check that as well?

**Comment by rompic** [comment]
see https://github.com/appium/appium-dot-app/blob/ef1d051ddeab736cad9bc10268a5c8e7bf766a47/Appium/Inspector/WebDriverElementNode.m#L210
 @"visible:", [NSString stringWithFormat:@" %@\n", (self.clickable ? @"true" : @"false")],

should this be changed to visible? ther doesn't seem to be a clickable element in the json response

**Comment by williamrussell-grindr** [comment]
+1 for a fix.

**Comment by jtheodore-rent** [comment]
I am running into this issue as well. We are working on a React.js app, and elements that are clearly not visible on the page are returning as visible. Specifically, when I assert that the element is not visible before it should be, that check fails saying that the element returned as visible/displayed. This is only happening on iOS devices, not on Android.

**Comment by vikramvi** [comment]
@jtheodore-rent can you please try with https://github.com/appium/appium-desktop, in case issue is still reproducible; create new issue under that repo

**Comment by jtheodore-rent** [comment]
@vikramvi I can try with Appium Desktop, but I doubt I will see different results - I should have been more specific in my first post.

I am not running these tests locally but connecting through SauceLabs. We are also doing an evaluation of TestObject. We have observed this issue on both platforms (SauceLabs with an iPhone 6 Simulator, TestObject with an iPhone SE Real Device). On both, I believe the Appium version being run is 1.6.3

**Comment by jlipps** [comment]
@mykola-mokhnach what's the status with visibility accuracy in most recent WDA? I think 1.6.4 had some fixes for this, no?

**Comment by jlipps** [comment]
nevermind, this issue is not for XCUITest-based tests but for UIAutomation-based tests.

**Comment by swathi-b** [comment]
I too have this issue

![appium_visibility_issue](https://cloud.githubusercontent.com/assets/2126991/26568176/8ff0491e-4544-11e7-9cbc-9a06ade3cd5e.png)

Though element is invisible/not enabled appium treats it as enabled element

boolean availability = driver.findElementByAccessibilityId("Today").isEnabled(); ==> true
boolean availability = driver.findElementByAccessibilityId("Today").isDisplayed(); ==> true

**Comment by imurchie** [comment]
Closing as the inspector is not longer supported.
