### ISSUE TITLE
Instruments crashes when clicking buttons - IOS Only

### ISSUE THREAD

**Issue by go2guy** [appium/appium#6064]
On IOS I'm having issues when clicking buttons sometimes, the app crashes.  I cannot get it happen manually for the developer, so we do not think it related to the APP code.

I'm simply trying to click a Save button after I have clicked 2 buttons to hide some events.  You can see it around line 1150 in the log file.  This is happening all the time.

info: [debug] [INST] 2016-01-25 21:30:57 +0000 Fail: The target application appears to have died

The appium debug log is located here for investgation.
https://gist.github.com/nuggit32/c4a018b19d753aa34701

**Comment by mehmetboraezer** [comment]
Hi @nuggit32, you clicked the wrong xpath, perhaps? Can you try click xpath using of Appium Inspector. Please check this.
I think if you can click a button, you can click all of them.

**Comment by nuggit32** [comment]
The mapping of the button is correct.  Sometimes it works, sometimes it does not.    The problem is "the  target application appears to have died" thus the button element not available anymore.

org.openqa.selenium.WebDriverException: Instruments died while responding to command

**Comment by huminzhi** [comment]
I am hitting the same issue that "Instruments died while responding to command", It's more likely an Apple's bug...

**Comment by cuhavp** [comment]
+1
