### ISSUE TITLE
How to locate <img lazy-load-src> element in webview context

### ISSUE THREAD

**Issue by lucyking** [appium/appium#6067]
We can use **xpath=//img[@src=...]**  to locate normal image:
```
<img src="..."  />
```
But some big web use lazy loading images methon，lead to the img element tag abnormal:
```
<img data-lazyload-src="..."  />
```
Has anyone ever had this problem ? What solution did you implement ?

**Comment by scottdixon** [comment]
What happens when you try //img[@data-lazyload-src=...] ?

Also, which lazyload plugin are you using? The `data-lazy-load` attribute might be removed from the element once the image is loaded. Can you share the URL?

**Comment by lucyking** [comment]
@scottdixon 
1.[can't locate the image element.](https://gist.github.com/lucyking/2e6c84b8b01964535b6f?l=9395#file-img-data-lazyload-src-L9395)
2.may in javascript at the server.Here is the [Example](https://git.hz.netease.com/yxplusQA/YX_RFUI_Framework_demo/issues/7).In this webview,when the image's "src=..." at the <img.../img> body's head,then we can locate in uiautomatorviwer,if "src=..."  in the rear,image can't be locate. 
3.Above <img .../img> detial is view by chrome://inspect/#devices on PC, so wiyhout **lazyload** tag;
but when load img on mobile, we can see  *<img data-lazyload-src=*  tag in the [uidump](https://gist.github.com/lucyking/2e6c84b8b01964535b6f?l=9395#file-img-data-lazyload-src-L1547).

**Comment by lucyking** [comment]
According to the 2rd interesting performance, I've tried modify and rebuild uiautomator.jar source code in AOSP，but do not get any significant progress yet.
ps: large websites such as ebay may use lazy-load methon to improve user experience.The  significant feature of lazy-load is that when slide down the apk UI, it will take a little while to load the **data-lazyload-src** such as images.

**Comment by scottdixon** [comment]
Thanks. I just ran your code - `data-lazyload-src` is removed when the image loads. Perhaps it's cleaner to target the elements using a class, for example: `.game-icon`

As a side note,  I see you're searching for `http://yixinpublic.nos-yx.netease.com/pr_librsktskhoasg-at9m7-w==_1449214377_89338393?imageView&thumbnail=200x0` - but this image doesn't appear to be anywhere in the source (unless you're dynamically loading it?)

**Comment by lucyking** [comment]
The element seaching for is another game pic,that is __totally equivalent__ to the pic3 in the source.
Just because there was some time interval between writing the gist and the source's illustration. :joy: 
Respect to your detailed inspection. :+1:

**Comment by scottdixon** [comment]
Nice. Can I consider this issue resolved? Or do you still face problems?

**Comment by lucyking** [comment]
Yes,it resolved.Many thanks to your gorgeous replay.
