### ISSUE TITLE
startup appium error by shell in mac os

### ISSUE THREAD

**Issue by xujianjie** [appium/appium#6070]
i am use python client lib to startup appium server by shell, like this:

node = os.path.join('/Applications/Appium.app/Contents', 'Resources/node/bin/node')
        js = os.path.join('/Applications/Appium.app/Contents', 'Resources/node_modules/appium/lib/server/main.js')
        subprocess.Popen([node, js, '--session-override', '--log-level', 'info', '--port', '%s' % port, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

then error:

WebDriverException: Message: A new session could not be created. (Original error: Command failed: /bin/sh -c ideviceinstaller -u e28b1d41bc6be9f89af5a3019c3ced91379e6b03 -l 
dyld: Library not loaded: @executable_path/../lib/libimobiledevice.3.dylib
  Referenced from: /Applications/Appium.app/Contents/Resources/node_modules/appium/build/libimobiledevice-macosx/ideviceinstaller
  Reason: image not found

when i use 1.3.7, it was works!

**Comment by xujianjie** [comment]
my appium version is 1.4.13

**Comment by scottdixon** [comment]
Can you please try with the latest Appium beta?

`npm install -g appium@beta`

**Comment by SrinivasanTarget** [comment]
@xujianjie Feel free to log a new issue if you hit the same issue again with latest version of appium.

**Comment by SrinivasanTarget** [comment]
@triager please close
