### ISSUE TITLE
iOS - Appium detects wrong simulator folder due to paired devices (iPhone 6s / iPhone 6s Plus / xcode 7.2)

### ISSUE THREAD

**Issue by NikolayStanoev** [appium/appium#6071]
Hello,

I have faced one strange problem with xcode 7.2 and iPhone 6s / iPhone 6s Plus simulators. When you install xcode 7.2 it comes with iOS 9.2 simulators and we have a paired devices (iPhone 6s + Apple Watch / iPhone 6s Plus + Apple Watch). As a result when I start a test (mobile Safari) using iPhone 6s or iPhone 6s Plus appium detects the folder for the paired device instead of the simulator.  

Information about the environment:
* MAC OS X - El Capitan (10.11.1)
* xCode 7.2 ( iOS 9.2 / 9.1 Simulators)
* appium 1.4.16 installed from npm 
* Capabilities (DEVICE_NAME in the second example is changed to iPhone 6s Plus Custom):
```
sharedIOS.setCapability(MobileCapabilityType.PLATFORM_VERSION, "9.2");
sharedIOS.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
sharedIOS.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
sharedIOS.setCapability("safariIgnoreFraudWarning", "true");
sharedIOS.setCapability("autoAcceptAlerts", "true");
sharedIOS.setCapability("safariAllowPopups", "true");
sharedIOS.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6s Plus")
sharedIOS.setCapability("name", "iPhone Simulator");
```

You can see the example below:
In this file you can see all devices which are on the machine. 
[All simulators](https://gist.github.com/NikolayStanoev/4d8854a77ca395aabc96)
You can focus on the following lines:
iPhone 6s Plus (9.2) [758AE73E-ACE3-4655-9BA2-9EAA7E83D007]
iPhone 6s Plus (9.2) + Apple Watch - 42mm (2.1) [911E2404-CBB0-4DBC-8CE4-E1376E13E6F5]

In the file below is an example of the output from appium. 
[iPhone 6s Plus log](https://gist.github.com/NikolayStanoev/bbaf4cc35b36aa77c5d0)
As you can see from the log it gets the paired simulator [911E2404-CBB0-4DBC-8CE4-E1376E13E6F5] instead of the iPhone 6s Plus simulator [758AE73E-ACE3-4655-9BA2-9EAA7E83D007].

The root cause of this problem is that when appium searches for iPhone 6s Plus it detects two values. The first one is iPhone 6s Plus and the second one is iPhone 6s Plus + Apple Watch. So as a final value will be set the second result ( iPhone 6s Plus + Apple Watch). Same issue is reproducible with iPhone 6s.

In order to workaround that problem I have create a new simulator (iPhone 6s Plus Custom) from Xcode -> Window -> Devices -> Add Simulator:
* Simulator Name : iPhone 6s Plus Custom
* Device Type: iPhone 6s Plus
* iOS Version: iOS 9.2
Paired Apple Watch: None

You can see this simulator in the xcrun file 
iPhone 6s Plus Custom (9.2) [BF5A1969-903A-4D37-86CC-C9E2507898A8]

When I try to run the test against that simulator. Appium works fine till Let\`s browse page. After that when I try to open www.google.com it does nothing. The page is refreshed several times (still on Let\`s browse) but nothing else happens. Unfortunately, I still haven`t found where exactly is the problem. Do you have any idea how we can resolve that problem?
[iPhone 6s Plus Custom log](https://gist.github.com/NikolayStanoev/38dd638535d0e8677e0b)

**Comment by scottdixon** [comment]
Interesting. What happens when you run ```/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w "iPhone 6s Plus (9.2)" com.apple.mobilesafari -e UIASCRIPT "/Users/ecmadmin/Library/Application Support/appium/bootstrap/bootstrap-8f6a9c4213adae81.js" -e UIARESULTSPATH /tmp/appium-instruments```

It looks like Appium is trying to launch the correct device. I wonder where the wires are getting crossed.

Can you give it a shot with the latest Appium beta? Let me know if either issue persists.

`npm install -g appium@beta`

**Comment by NikolayStanoev** [comment]
Hello Scot,

Sorry for the late reply.

I have installed appium 1.5.0 and updated xcode to 7.2.1 version. Everything runs fine. I think that the problem might be in the xcode but will double check that later today. 

Feel free to close that problem.

**Comment by scottdixon** [comment]
Good to hear. Thanks for the update.
