### ISSUE TITLE
My app is getting launched and closing by itself: Below are the logs

### ISSUE THREAD

**Issue by abhishekhardi** [appium/appium#6072]
> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --app C:\Users\Abhishek\Downloads\ErosNow_V72_VN3.1.9_RC_REV2.apk --device-ready-timeout 10 --platform-name Android --platform-version 19 --automation-name Appium --log-no-color
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"app":"C:\Users\Abhishek\Downloads\ErosNow_V72_VN3.1.9_RC_REV2.apk","address":"127.0.0.1","logNoColors":true,"androidDeviceReadyTimeout":"10","platformName":"Android","platformVersion":"19","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\Users\Abhishek\Desktop\erostest\erostest\app\Erosnow.apk","appPackage":"com.erosnow","appActivity":"com.erosnow.SplashScreenActivity","platformVersion":"4.4.2","appWaitActivity":"com.erosnow.OnBoardingActivity","udid":"6PVCA6EE9TJ7FU5S","platformName":"Android","deviceName":"ANDROID"}}
> info: Client User-Agent string: Apache-HttpClient/4.5 (Java/1.8.0_65)
> info: [debug] Using local app from desired caps: C:\Users\Abhishek\Desktop\erostest\erostest\app\Erosnow.apk
> info: [debug] Creating new appium session b0fd4442-5b22-4273-9424-93c70ec3c678
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_65
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device 6PVCA6EE9TJ7FU5S
> info: [debug] Setting device id to 6PVCA6EE9TJ7FU5S
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 10)
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S wait-for-device
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: Device API level is: 19
> info: [debug] Extracting strings for language: default
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\Abhishek\Desktop\erostest\erostest\app\Erosnow.apk" "C:\Users\Abhishek\AppData\Local\Temp\com.erosnow" en
> info: [debug] No strings.xml for language 'en', getting default strings.xml
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\Abhishek\Desktop\erostest\erostest\app\Erosnow.apk" "C:\Users\Abhishek\AppData\Local\Temp\com.erosnow"
> info: [debug] Reading strings from converted strings.json
> info: [debug] Setting language to default
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S push "C:\Users\Abhishek\AppData\Local\Temp\com.erosnow\strings.json" /data/local/tmp
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\Abhishek\Desktop\androidsdk\sdk\build-tools\23.0.2\aapt.exe
> info: [debug] Retrieving process from manifest.
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\build-tools\23.0.2\aapt.exe dump xmltree C:\Users\Abhishek\Desktop\erostest\erostest\app\Erosnow.apk AndroidManifest.xml
> info: [debug] Set app process to: com.erosnow
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Checking app cert for C:\Users\Abhishek\Desktop\erostest\erostest\app\Erosnow.apk.
> info: [debug] executing cmd: java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar" C:\Users\Abhishek\Desktop\erostest\erostest\app\Erosnow.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Users\Abhishek\Desktop\erostest\erostest\app\Erosnow.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\Abhishek\Desktop\androidsdk\sdk\build-tools\23.0.2\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\build-tools\23.0.2\zipalign.exe -f 4 C:\Users\Abhishek\Desktop\erostest\erostest\app\Erosnow.apk C:\Users\Abhishek\AppData\Local\Temp\116027-8956-hpzmqv\appium.tmp
> info: [debug] MD5 for app is 39b34c305cecda03b6b4282820b0a797
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "ls /data/local/tmp/39b34c305cecda03b6b4282820b0a797.apk"
> info: [debug] Getting install status for com.erosnow
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "pm list packages -3 com.erosnow"
> info: [debug] App is not installed
> info: Installing App
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "mkdir -p /data/local/tmp/"
> info: [debug] Removing any old apks
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "ls /data/local/tmp/*.apk"
> info: [debug] Found an apk we want to keep at /data/local/tmp/39b34c305cecda03b6b4282820b0a797.apk
> info: [debug] Couldn't find any apks to remove
> info: [debug] Uninstalling com.erosnow
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "am force-stop com.erosnow"
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S uninstall com.erosnow
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "pm install -r /data/local/tmp/39b34c305cecda03b6b4282820b0a797.apk"
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S push "C:\Program Files (x86)\Appium\node_modules\appium\build\android_bootstrap\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.erosnow -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] WARNING: linker: libvc1dec_sa.ca7.so has text relocations. This is wasting memory and is a security risk. Please fix.
> info: [debug] [UIAUTOMATOR STDOUT] WARNING: linker: libvc1dec_sa.ca7.so
> info: [debug] [UIAUTOMATOR STDOUT] has text relocations. This is wasting memory and is a security risk. Please fix.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [UIAUTOMATOR STDOUT] tcp port:4724
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] json loading complete.
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.erosnow/com.erosnow.SplashScreenActivity"
> info: [debug] Waiting for pkg "com.erosnow" and activity "com.erosnow.OnBoardingActivity" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "dumpsys window windows"
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "dumpsys window windows"
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "getprop ro.build.version.release"
> info: [debug] Device is at release version 4.4.2
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId b0fd4442-5b22-4273-9424-93c70ec3c678
> info: <-- POST /wd/hub/session 303 36468.993 ms - 74 
> info: --> GET /wd/hub/session/b0fd4442-5b22-4273-9424-93c70ec3c678 {}
> info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.4.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"C:\Users\Abhishek\Desktop\erostest\erostest\app\Erosnow.apk","appPackage":"com.erosnow","appActivity":"com.erosnow.SplashScreenActivity","platformVersion":"4.4.2","appWaitActivity":"com.erosnow.OnBoardingActivity","udid":"6PVCA6EE9TJ7FU5S","platformName":"Android","deviceName":"ANDROID"},"app":"C:\Users\Abhishek\Desktop\erostest\erostest\app\Erosnow.apk","appPackage":"com.erosnow","appActivity":"com.erosnow.SplashScreenActivity","appWaitActivity":"com.erosnow.OnBoardingActivity","udid":"6PVCA6EE9TJ7FU5S","platformName":"Android","deviceName":"6PVCA6EE9TJ7FU5S"},"sessionId":"b0fd4442-5b22-4273-9424-93c70ec3c678"}
> info: <-- GET /wd/hub/session/b0fd4442-5b22-4273-9424-93c70ec3c678 200 13.860 ms - 916 {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.4.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"C:\Users\Abhishek\Desktop\erostest\erostest\app\Erosnow.apk","appPackage":"com.erosnow","appActivity":"com.erosnow.SplashScreenActivity","platformVersion":"4.4.2","appWaitActivity":"com.erosnow.OnBoardingActivity","udid":"6PVCA6EE9TJ7FU5S","platformName":"Android","deviceName":"ANDROID"},"app":"C:\Users\Abhishek\Desktop\erostest\erostest\app\Erosnow.apk","appPackage":"com.erosnow","appActivity":"com.erosnow.SplashScreenActivity","appWaitActivity":"com.erosnow.OnBoardingActivity","udid":"6PVCA6EE9TJ7FU5S","platformName":"Android","deviceName":"6PVCA6EE9TJ7FU5S"},"sessionId":"b0fd4442-5b22-4273-9424-93c70ec3c678"}
> info: --> POST /wd/hub/session/b0fd4442-5b22-4273-9424-93c70ec3c678/timeouts {"type":"implicit","ms":50000}
> info: [debug] Set Android implicit wait to 50000ms
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"b0fd4442-5b22-4273-9424-93c70ec3c678"}
> info: <-- POST /wd/hub/session/b0fd4442-5b22-4273-9424-93c70ec3c678/timeouts 200 14.977 ms - 76 {"status":0,"value":null,"sessionId":"b0fd4442-5b22-4273-9424-93c70ec3c678"}
> info: --> DELETE /wd/hub/session/b0fd4442-5b22-4273-9424-93c70ec3c678 {}
> info: Shutting down appium session
> info: [debug] Pressing the HOME button
> info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell "input keyevent 3"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
> info: [debug] [UIAUTOMATOR STDOUT] [CDS]close[4724]
> info: [debug] [UIAUTOMATOR STDOUT] close [socket][/0.0.0.0:4724]
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 15.403
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] UiAutomator shut down normally
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"b0fd4442-5b22-4273-9424-93c70ec3c678"}
> info: <-- DELETE /wd/hub/session/b0fd4442-5b22-4273-9424-93c70ec3c678 200 1442.373 ms - 76 {"status":0,"value":null,"sessionId":"b0fd4442-5b22-4273-9424-93c70ec3c678"}

**Comment by karthick2313** [comment]
you are pressing the home button in your code,

> info: [debug] Pressing the HOME button

info: [debug] executing cmd: C:\Users\Abhishek\Desktop\androidsdk\sdk\platform-tools\adb.exe -s 6PVCA6EE9TJ7FU5S shell `"input keyevent 3"`

**Comment by scottdixon** [comment]
It looks like the session is created successfully and then, having no commands, the session is deleted. 

Can you please provide your test code?

**Comment by soniacepedano** [comment]
Hi guys
to me is happened the same. i use appium for windows

this is my test cde


public class LoginOK {
  
	RemoteWebDriver driver;
	LoginPage logpag;
	
 
  @Test
  public void Login() {
	System.out.println("test case started");
	
	logpag = new LoginPage(driver);
	
	System.out.println("test case started2");
	String username= "user";
	String pass = "profesoruno";
	
	System.out.println("test case started3");
	
	logpag.loginOK(username, pass);
	System.out.println("test case started4");	
  }
  @BeforeTest
  public void setUp() throws MalformedURLException{
	  /**
	   * creación de la capability, para poder pasar android activity u paquete para appium
	   */
	  DesiredCapabilities capability = new DesiredCapabilities();
	  //capability.setCapability("BROWSER_NAME", "");
	  
	 /**
	  * Reemplazar con nuestra version de andorid 
	  */
	  capability.setCapability("automationName","appium");
	  capability.setCapability("platformVersion", "4.4.2");
	  capability.setCapability("deviceName","Android Emulator");
	  capability.setCapability("platformName","Android");
	  
	  capability.setCapability("appPackage","com.sm.savia");
	  capability.setCapability("appActivity",".MainActivity");
	  capability.setCapability("language","es");
	  capability.setCapability("app", "C:\\users\\sonia.cepedano\\Downloads\\SaviaDigitalAndroidPRE.apk");
	 
	  
	  /**
	   * 
	   */
	  
	  driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capability);
	  
  }

  @AfterTest
  public void teardown() {
	  
	  driver.quit();
  }

}

**Comment by abhishekhardi** [comment]
Comment out after test. Should work

On May 20, 2016 5:56 PM, "soniacepedano" <notifications@github.com> wrote:
>
> Hi guys
> to me is happened the same. i use appium for windows
>
> this is my test cde
>
> public class LoginOK {
>
> RemoteWebDriver driver;
> LoginPage logpag;
>
> @Test
> public void Login() {
> System.out.println("test case started");
>
> logpag = new LoginPage(driver);
>
> System.out.println("test case started2");
> String username= "user";
> String pass = "profesoruno";
>
> System.out.println("test case started3");
>
> logpag.loginOK(username, pass);
> System.out.println("test case started4");
>
> }
> @BeforeTest
> public void setUp() throws MalformedURLException{
> /**
> * creación de la capability, para poder pasar android activity u paquete
para appium
> */
> DesiredCapabilities capability = new DesiredCapabilities();
> //capability.setCapability("BROWSER_NAME", "");
>
>  /**
>   * Reemplazar con nuestra version de andorid
>   */
>   capability.setCapability("automationName","appium");
>   capability.setCapability("platformVersion", "4.4.2");
>   capability.setCapability("deviceName","Android Emulator");
>   capability.setCapability("platformName","Android");
>
>   capability.setCapability("appPackage","com.sm.savia");
>   capability.setCapability("appActivity",".MainActivity");
>   capability.setCapability("language","es");
>   capability.setCapability("app",
"C:\\users\\sonia.cepedano\\Downloads\\SaviaDigitalAndroidPRE.apk");
>
>
>   /**
>    *
>    */
>
>   driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"),
capability);
