### ISSUE TITLE
Cannot Install Appium 1.4.16 via npm

### ISSUE THREAD

**Issue by sehandane** [appium/appium#6075]
Hi all,

I have problem when try to install the latest Appium. Can someone help me with this...

I'm using MACOX 10.10.5

Here is the log

[Log.txt](https://github.com/appium/appium/files/107670/Log.txt)

**Comment by mehmetboraezer** [comment]
Please try this commands:
```
npm uninstall -g appium
npm cache clean -f
npm install -g n
n stable
npm install npm -g
npm install -g appium 
```

**Comment by sehandane** [comment]
@mehmetboraezer thanks for replying, I tried your suggested commands but still not work :(

This is the log
[Log.txt](https://github.com/appium/appium/files/109177/Log.txt)

**Comment by pr4bh4sh** [comment]
@sehandane Downgrade your node to version 0.12, you can look into NVM if you want have multiple versions of node installed.

**Comment by sehandane** [comment]
@pr4bh4sh thanks, but it does not work.
Maybe I should try to reinstall MACOS...:(

**Comment by mehmetboraezer** [comment]
@sehandane i think that is bad idea. So perhaps you can reinstall Node.js. 

Try this:

```
sudo rm -rf  /usr/local/lib/node_modules/npm/
brew uninstall node
brew doctor
brew install node
```

**Comment by sehandane** [comment]
@mehmetboraezer It's still not work. I have also tried with another fresh machine and try the below 
`> brew install node      # get node.js
> npm install -g appium  # get appium
> npm install wd         # get appium client
> appium &               # start appium
> node your-appium-test.js`

I have errors while installing Appium - 
[AppiumErrorLog.txt](https://github.com/appium/appium/files/115075/AppiumErrorLog.txt)
Then I tried to get Appium client - 
[AppiumClientError.txt](https://github.com/appium/appium/files/115078/AppiumClientError.txt)
After all, I tried to start the Appium - 
[StartnTest.txt](https://github.com/appium/appium/files/115080/StartnTest.txt)

**Comment by sehandane** [comment]
Hi, I have started the Appium. Is it installed and started successfully?
![screen shot 2016-02-03 at 11 54 14 am](https://cloud.githubusercontent.com/assets/16129840/12773328/26fad3e6-ca6d-11e5-9b8d-64df3eda10ef.png)

If I wanna open the Appium GUI, Inspector. Is there any way to do ?

**Comment by mehmetboraezer** [comment]
I think working properly (if you do not receive an error). And yes you can. But first download and install Appium GUI application.

You can download this way:
```
 wget https://bitbucket.org/appium/appium.app/downloads/appium.dmg
```

**Comment by sehandane** [comment]
@mehmetboraezer Thanks,
Could you show me how to start iOS Simulator by the installed Appium via npm :)

**Comment by mehmetboraezer** [comment]
@sehandane You can watch this video :) 

[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/d1u58t-ko6s/0.jpg)]
(https://www.youtube.com/watch?v=d1u58t-ko6s)

**Comment by sehandane** [comment]
@mehmetboraezer Thanks a lot
