### ISSUE TITLE
Android : Some UI Elements in the IMDB App are not  recognized

### ISSUE THREAD

**Issue by FrankBorland** [appium/appium#6076]
I am cannot click on the search results in the IMDB app using Appium 1.4.16. They are also not contained in the hierarchy that I get when calling driver.getPageSource(); 

![imdbelementsnotinhierarchy](https://cloud.githubusercontent.com/assets/8554028/12647786/437d6294-c5d7-11e5-8459-d0efa68323aa.PNG)

[Hierarchy_without_search_results.txt](https://github.com/appium/appium/files/108329/Hierarchy_without_search_results.txt)
(txt file with the dumped hierarchy)

The hierarchy only contains the elements behind the search result, such as the image marked in the screenshot)

**Comment by kcinman11358** [comment]
Could be a webview, in which case you should change the context to support this hybrid app

**Comment by scottdixon** [comment]
@FrankBorland - any luck with @kcinman11358 webview suggestion?
