### ISSUE TITLE
android screen stay lock when using lockScreen function

### ISSUE THREAD

**Issue by gilsheps** [appium/appium#6077]
HI,
i'm testing my app and i using driver.lockScreen(), on iOS this function is blocking the driver and Appium unlock the screen after the timer ended.
on Android, i need to add sleep timer and the screen stay locked.
is there a way that Android driver will act as IOS driver?

**Comment by mehmetboraezer** [comment]
Hello @gilsheps. What is your Android version? I got the same error and my Android version is 6.0. And i think this is bug. 
Finally my solution is screen constantly leave open.

**Comment by gilsheps** [comment]
my question is not the same, the screen lock and goes to sleep.
the question about that android driver does not act as ios driver.

**Comment by imurchie** [comment]
This is the desired behavior. The locking-waiting-unlocking is necessary for iOS, where it is the only way to do any locking. For Android it should just lock. If you want it to unlock, you can call unlock.

I am making the seconds parameter optional, and documenting this difference.
