### ISSUE TITLE
ADB Failed to Uninstall

### ISSUE THREAD

**Issue by mirkara** [appium/appium#6079]
The following happens a few times when running Appium over a long period of time.

[36minfo[39m: [debug] Set app process to: com.test.test
[36minfo[39m: [debug] Uninstalling com.test.teset
[36minfo[39m: [debug] executing cmd: /android/android-sdk/platform-tools/adb -s code shell "am force-stop com.test.test"
[36minfo[39m: [debug] executing cmd: /android/android-sdk/platform-tools/adb -s code uninstall com.test.test
[36minfo[39m: [debug] Stopping logcat capture
[36minfo[39m: [debug] Logcat terminated with code null, signal SIGTERM
[36minfo[39m: [debug] Sent shutdown command, waiting for UiAutomator to stop...
[33mwarn[39m: UiAutomator did not shut down fast enough, calling it gone
[36minfo[39m: [debug] Cleaning up android objects
[36minfo[39m: [debug] Cleaning up appium session
[36minfo[39m: [debug] Error: Command failed: /bin/sh -c /android/android-sdk/platform-tools/adb -s code uninstall com.test.test
 at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by mehmetboraezer** [comment]
Hello @mirkara. Can you try adb commands with manually? It works? And bundle id is correct? Please check them.

**Comment by scottdixon** [comment]
Any update, @mirkara ?

**Comment by mirkara** [comment]
Hey sorry for the late response. Manually it works. However we're dropped this.

**Comment by BikramDhall** [comment]
Hi
adb command works amnually,
Still error as below even if uninstalling both AppiumSettings apk as well as unlock apk.

[36minfo[39m: [debug] executing cmd: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE forward tcp:4724 tcp:4724
[36minfo[39m: [debug] Pushing appium bootstrap to device...
[36minfo[39m: [debug] executing cmd: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
[36minfo[39m: [debug] Pushing settings apk to device...
[36minfo[39m: [debug] executing cmd: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
[36minfo[39m: [debug] Stopping logcat capture
[36minfo[39m: [debug] Logcat terminated with code null, signal SIGTERM
[36minfo[39m: [debug] Sent shutdown command, waiting for UiAutomator to stop...
[33mwarn[39m: UiAutomator did not shut down fast enough, calling it gone
[36minfo[39m: [debug] Cleaning up android objects
[36minfo[39m: [debug] Cleaning up appium session
[31merror[39m: Failed to start an Appium session, err was: Error: Command failed: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
adb: failed to install C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]

[36minfo[39m: [debug] Error: Command failed: C:\Users\dhall\AppData\Local\Android\sdk\platform-tools\adb.exe -s G070VM0985051PJE install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
adb: failed to install C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by BikramDhall** [comment]
This issue is comming only on amazon Fire TV 3rd gen and 4th gen however script works fine on gen 1 and 2.  Both one two are lower configuration and storage.
