### ISSUE TITLE
Not able to locate the element (But i am element on the inspector)

### ISSUE THREAD

**Issue by asos-ShanmugaMahalingam** [appium/appium#6080]
I am able to see the element on the appium inspector and also seeing it as visible on the XML. But i am not abel to locate that element. 
Any one able to help me on it ?

**Comment by asos-ShanmugaMahalingam** [comment]
![screen shot 2016-01-29 at 14 02 21](https://cloud.githubusercontent.com/assets/16081307/12677488/4b5defaa-c691-11e5-9c09-ed78ac36babb.png)

![screen shot 2016-01-29 at 14 05 49](https://cloud.githubusercontent.com/assets/16081307/12677507/700f3c50-c691-11e5-8af5-6d32b09d99bf.png)

**Comment by imurchie** [comment]
Is this still an issue? Or why is this closed?

Can you post the logs, as a [gist](https://gist.github.com/)?

Getting elements by name is not the preferred way to do things, since name is brittle. Use accessibility id.

**Comment by asos-ShanmugaMahalingam** [comment]
Thanks for your reply.  Yes i am still seeing the issue. 

PS: I assumed appium.io is the best place to log a defect.

**Comment by imurchie** [comment]
Yes, if it is just a query about how to do something, the forums would be a better bet. Thanks!
