### ISSUE TITLE
TouchAction can not use function 'move_to' multi-times at a time

### ISSUE THREAD

**Issue by zippies** [appium/appium#6085]
I am using python 3.3.5   Android 4.4
This work fine:
`
TouchAction(self).long_press(x=816,y=649).move_to(x=264,y=649).release().perform()
`
but this will cause an error(Message: The coordinates provided to an interactions operation are invalid.):
`TouchAction(self).long_press(x=816,y=649).move_to(x=264,y=649).move_to(x=264,y=1000).release().perform()
`
……Is there anything i can do to solve this problem?

**Comment by imurchie** [comment]
Can you provide the server logs in a [gist](https://gist.github.com/) so that we can more accurately pinpoint the problem?

**Comment by imurchie** [comment]
Can you try using a `press` action rather than a `long_press` action as your first action?

**Comment by mounamukhar** [comment]
I am having this issue. I have tried changing the long-press to just press. But still happening. Any suggestion?
