### ISSUE TITLE
Not able to locate the element which is visible in the appium inspector

### ISSUE THREAD

**Issue by asos-ShanmugaMahalingam** [appium/appium#6086]
I am able to see the element on the appium inspector and also seeing it as visible on the XML. But i am not abel to locate that element.

I am seeing a element called "Sub-total" but i couldn't locate it using 
driver.find_element_by_name("Sub-total")

**Comment by asos-ShanmugaMahalingam** [comment]
![screen shot 2016-01-29 at 14 02 21](https://cloud.githubusercontent.com/assets/16081307/12697794/ddd488e2-c783-11e5-8188-03be08d8103b.png)
![screen shot 2016-01-29 at 14 05 49](https://cloud.githubusercontent.com/assets/16081307/12697795/ddd5fa2e-c783-11e5-9532-9d550aee2d2d.png)

**Comment by kcinman11358** [comment]
What language are you using? Using C#, it would be driver.findElementByName("Sub-total");

What are you trying to do with this element? Also, for debugging purposes, I would do var x = driver.findElementsByName("Sub-total").Count; and see if there are multiple on the screen

**Comment by asos-ShanmugaMahalingam** [comment]
I am using python and i couldn't find the element using driver.find_element_by_name("Sub-total"). 

I think appium inspector is not loading the elements in <UIACollectionView> (few cases). Please find the attache the screenshot. 
![screen shot 2016-02-01 at 09 35 12](https://cloud.githubusercontent.com/assets/16081307/12713627/acb5c97a-c8c7-11e5-9574-f429a789f367.png)

**Comment by Sumanjit13** [comment]
Hi
I am facing the same issue. I am not able to click on element with attribute visible: false but other elements with same attributes I am able to interact.
With that element isDisplayed returns False and isEnabled returns True.
I have tried to tap on element with x,y co-ordinates but appium throws exception that element is not visible to tap.

**Comment by scottdixon** [comment]
Can you please try Appium 1.5

Also, are you able to provide a sample app so we can reproduce?
