### ISSUE TITLE
Can not attach to Device

### ISSUE THREAD

**Issue by Scriptkiddi** [appium/appium#6090]
Im running appium as a supervisor process. If I then try to connect to the devices it responds with this error

`: Client User-Agent string: Python-urllib/3.5
info: [debug] No appActivity desired capability or server param. Parsing from apk.
info: [debug] No appPackage desired capability or server param. Parsing from apk.
info: [debug] Using local app from desired caps: /home/testing/app-fat-release.apk
info: [debug] Creating new appium session a021e323-f509-4ebe-b975-f6d926d8d74c
info: Starting android appium
info: [debug] Getting Java version
info: Java version is: 1.8.0_66-internal
info: [debug] Checking whether adb is present
info: [debug] Using adb from /home/testing/android_sdk/android-sdk-linux/platform-tools/adb
info: [debug] Parsing package and activity from app manifest
info: [debug] Checking whether aapt is present
info: [debug] Using aapt from /home/testing/android_sdk/android-sdk-linux/build-tools/23.0.2/aapt
info: [debug] Extracting package and launch activity from manifest.
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/build-tools/23.0.2/aapt dump badging /home/testing/app-fat-release.apk
info: [debug] badging package: com.quappi.scriptkiddi.krypton
info: [debug] badging act: com.quappi.scriptkiddi.krypton.MainActivity
info: [debug] Parsed package and activity are: com.quappi.scriptkiddi.krypton/com.quappi.scriptkiddi.krypton.MainActivity
info: [debug] Using fast reset? true
info: [debug] Preparing device for session
info: [debug] Checking whether app is actually present
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb devices
info: [debug] 2 device(s) connected
info: Found device 03157df360338a11
info: [debug] Setting device id to 03157df360338a11
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb -s 03157df360338a11 wait-for-device
info: [debug] Retrying restartAdb
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb -s 03157df360338a11 kill-server
info: [debug] Getting connected devices...
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb -s 03157df360338a11 devices
info: [debug] 2 device(s) connected
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb -s 03157df360338a11 wait-for-device
info: [debug] Retrying restartAdb
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb -s 03157df360338a11 kill-server
info: [debug] Getting connected devices...
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb -s 03157df360338a11 devices
info: [debug] 1 device(s) connected
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb -s 03157df360338a11 wait-for-device
info: [debug] Retrying restartAdb
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb -s 03157df360338a11 kill-server
info: [debug] Getting connected devices...
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb -s 03157df360338a11 devices
info: [debug] 1 device(s) connected
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb -s 03157df360338a11 wait-for-device
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb -s 03157df360338a11 kill-server
info: [debug] Getting connected devices...
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb -s 03157df360338a11 devices
info: [debug] 1 device(s) connected
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: /home/testing/android_sdk/android-sdk-linux/platform-tools/adb -s 03157df360338a11 wait-for-device
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
warn: UiAutomator did not shut down fast enough, calling it gone
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
info: [debug] undefined
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created.","origValue":"Device did not become ready in 5 secs; are you sure it's powered on?"},"sessionId":null}
`
the wired thing about it is if i run my normal appium command directly from my command line I get a working appium server. I guess its something about an enviorment variable but since I dont really get an error Im opening an issue guessing somewhere there is a silent error in there. Does anybody have an idea what it could be?

**Comment by dpgraham** [comment]
I'm going to close this issue for now. If this is still happening, let me know and re-open the ticket
