### ISSUE TITLE
Reboot scenario fails due to session not available

### ISSUE THREAD

**Issue by email2vimalraj** [appium/appium#6095]
**Appium server**: 1.4.16, **java-client**: 3.3.0, **OS**: Mac 10.10.5 

This is my capability for the real android device:

```
platformName: Android
deviceName:   Android
app:          debug-app.apk
newCommandTimeout: 120
noReset: true
```

Steps to reproduce the issue:

Create the capabilities
Create android driver object with the capabilities
Trigger reboot
Watch appium session cleans up.
Code Example (**watch line # 36 and 37 are commented out**) : https://gist.github.com/email2vimalraj/9ac0df30fb89d7f924be

The following steps are working fine:

Create the capabilities
Create android driver object with the capabilities
Close the app and launch the app again
Trigger reboot
Now everything will go smooth
Code Example (**watch line # 36 and 37 are un-commented**) : https://gist.github.com/email2vimalraj/518ec9e1e998f838923a

_P.S_: Re-creating the issue since no one is replying to the issue which I have opened earlier - #5992 and closed the earlier

**Comment by email2vimalraj** [comment]
Any updates?

**Comment by scottdixon** [comment]
@email2vimalraj - do you hit the same issue with 1.5?
Also, can you please provide Appium server logs as a gist?

**Comment by email2vimalraj** [comment]
@scottdixon: I'll give a try and let you know.

**Comment by email2vimalraj** [comment]
@scottdixon : Sorry for the delay. Got a chance to upgrade to latest v1.5.3 and tried this. Facing error while rebooting without closing app or rebooting after driver.closeApp() or rebooting after driver.forceCloseApp():

```
[Logcat] Logcat terminated with code 0, signal null
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'UiAUtomator shut down unexpectedly'
[Appium] Removing session 23cd9289-f1ed-4884-9bd6-9cb83572e744 from our master session list
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
Unhandled rejection Error: No device connected, cannot run adb shell command "am force-stop com.myapp.mypackage"
    at ADB.callee$0$0$ (lib/tools/system-calls.js:198:11)
    at tryCatch (/Users/myname/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/myname/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/myname/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/myname/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by ngavrish** [comment]
@email2vimalraj this is still an issue for me
Android 6.0.1
Appium 164

**Comment by jlipps** [comment]
@ngavrish how are you rebooting the device?

**Comment by imurchie** [comment]
Rebooting has been fixed, as far as I know.
