### ISSUE TITLE
React Native test apps

### ISSUE THREAD

**Issue by scottdixon** [appium/appium#6098]
I propose we use [React Native](https://facebook.github.io/react-native/) to generate future test apps.

Some of the benefits:
- Create both iOS & Android applications using JS.
- Appium developers will be familiar with the ES6 syntax.

**Comment by webzepter** [comment]
:+1:

**Comment by scottdixon** [comment]
hmm this might not work.

`...a button is not implemented as a native UIButton, and a ListView doesn't use UITableView. Instead they are composed of native UIViews with a lot of JavaScript glue..`

**Comment by GeoffreyPlitt** [comment]
Does Appium work for React-Native Android yet?

**Comment by saikrishna321** [comment]
yah it does work . I run my test against react-native Android and iOS

**Comment by zachrnolan** [comment]
@saikrishna321 are you on xcode 8? It looks like Appium doesn't support it yet.

**Comment by saikrishna321** [comment]
yah I'm using xcode 8and test run on iOS 10

Do you have difficulty with locating the elements ?

**Comment by stereodenis** [comment]
@saikrishna321 could you get link to your tests?

**Comment by saikrishna321** [comment]
@stereodenis https://github.com/saikrishna321/VodQaAdvancedAppium

**Comment by KazuCocoa** [comment]
https://github.com/appium/sample-code/blob/master/sample-code/apps/VodQAReactNative.zip have been added by @saikrishna321

**Comment by saikrishna321** [comment]
Closing as we have React Native app in place 
github.com/appium/VodQAReactNative
