### ISSUE TITLE
Having more than one device plugged in test run on first device listed by adb.

### ISSUE THREAD

**Issue by xavilage** [appium/appium#6103]
Hi all,
Which one is the approach to have multiple devices always connected to an Appium server? 

On my experience the test will run on the device listed on the top when you run "adb-devices" completely missing the point of the capabilities defined.

Thanks, 
Javier Lage

**Comment by kcinman11358** [comment]
Hi @xavilage ,

See my response here: https://github.com/appium/appium-dot-app/issues/519

Basically, you need to set the udid of the device.

 capabilities.SetCapability("udid", udid);

**Comment by xavilage** [comment]
Pretty cool. Thanks @kcinman11358
