### ISSUE TITLE
Appium retrieves only the first element from a list where the child element has a static index and the parents index varries

### ISSUE THREAD

**Issue by CsabaF** [appium/appium#6104]
Hello,

I was attempting to get a full list of elements in a case where the parent of the child in xpath was dynamic and the child had a fix index and appium retrieves only the first element although almost all xpath validators will retrieve the full list.

My initial xpath that worked in validators but not in Appium : 
```java
FindsByIOSUIAutomation(XPath = "//UIAApplication[1]/UIAWindow[1]/UIATableView[1]/UIATableCell/UIAStaticText[1]", Priority = 1)
```

UIATableCell has no index, meaning it should verify all UIATableCells with a UIAStaticText[1] child and not stop at the first one.

To work around this temporarily i got full results retrieved from appium after i changed the xpath to :  ```java
FindsByIOSUIAutomation(XPath = "//UIAApplication[1]/UIAWindow[1]/UIATableView[1]/UIATableCell[position()>=1]/UIAStaticText[position()>=1][position() mod 2=0]", Priority = 1)
```

**Comment by dpgraham** [comment]
Since you have a workaround I'm going to close this. If you want this ticket reopened, and if you provide us with the source XML we can see if this is a bug or not.
