### ISSUE TITLE
iOS - Connection peer refused channel request for "com.apple.instruments.server.services.wireless"

### ISSUE THREAD

**Issue by elango842003** [appium/appium#6105]
info: [debug] [INST STDERR] 2016-02-04 11:22:19.507 instruments[800:29975] Connection peer refused channel request for "com.apple.instruments.server.services.wireless"; channel canceled <DTXChannel: 0x7fe75e674510>

I am using latest Appium : 1.4.13.

My requirement to record UI Automation, so I am using xrecord binary to record iPhone6.
(xrecord - Comment line tool to operate quick time)

when i use xrecord with Appium UI Automation, i am getting this error. if i don't use xrecord then my automation working fine. 

sad part is xrecord + Appium UI Automation worked 10 times in last 4 days. now its stopped working.

Any clue and let me know if you need more log.

**Comment by scottdixon** [comment]
Sounds like an xrecord/appium conflict. Can you provide more info/links to xrecord?

**Comment by elango842003** [comment]
https://github.com/WPO-Foundation/xrecord

Command Line Tool to record iOS device using QuickTime.
