### ISSUE TITLE
Can start application without specifying the appActivity

### ISSUE THREAD

**Issue by nijakanthan** [appium/appium#6107]
DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "5.0");
desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "<device serial no>");
desiredCapabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 9999);
desiredCapabilities.setCapability("appPackage", "com.facebook.katana");

URL url = new URL("http://localhost:4070/wd/hub");
AppiumDriver driver = new AndroidDriver(url, desiredCapabilities);

Error Message
error: Failed to start an Appium session, err was: Error: Parameter 'appActivity' is required for launching application

But we can start the application without specifying the application activity using adb monkey

Command
adb shell monkey -p com.facebook.katana -c android.intent.category.LAUNCHER 1

Can't use this command to launch application

**Comment by priyankshah217** [comment]
@nijakanthan , In adb monkey you are proving intent category, which launch intent hence activity will be launched eventually. In appium app is opened using its Launch activity, so you need to mentioned it into capability. 

Please try to raise this in appium forum: https://discuss.appium.io/ before raising up here.

**Comment by nijakanthan** [comment]
Thank you very much @priyankshah217
