### ISSUE TITLE
Appium Inspector - Refresh is extremely slow

### ISSUE THREAD

**Issue by Timawg** [appium/appium#6108]
###### Action Performed:
1. While the application and Appium is running, change the view in the app and hit refresh in the appium Inspector
2. A new screenshot will be captured and displayed in the inspector, however no new elements are loaded and the refresh button keeps spinning for a very long time (1-5 minutes)

This was not an issue until just recently, but I've not made any changes in Settings and it occurs with any .app

Appium version is 1.4.13

<img width="671" alt="screen shot 2016-02-05 at 12 16 11" src="https://cloud.githubusercontent.com/assets/14542962/12845068/9dc14fd6-cc03-11e5-91df-7c57d63367a4.png">

**Comment by Timawg** [comment]
Could this be the culprit?

error: [REMOTE] Could not create binary plist from data

info: [debug] Responding to client with success: {"status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAAQABJREFUeAHsXQegLDd1nff5pvcOptj03iEUGwgQ03uA0EwAmwA2ppMAgdAh1FAMBAwxIfQeeugu9N47mN6x6WDjHx1pzswdjabtbJndPfr/raSr23Sk3b2j0Wh3jj/++D1Zr7QTcbHuxH2R9VAtlZJeUiJF9SpYd/xLtW2Po1EdWNwfuZCnkmFPNU+etrOz2h6s2v7kB0gOtiKg+dMKT2fjHnzmKQmBBgQWPjvWfP6Nxme0goaBy8nd6rs52i2MbO0Y/8HeQcCGNIUCV0Cs4+sFscP5nSL+s4yQtibQZmm2jJZQh649hRx5kCNRH+uBGuhdNMiSpyyH0o7THNsttdJqTnFjAT34Tt1NB+Icje1fGk4FvaBXuZI9pT1HiRsdKW+n09a2V+nbK0o8i/fJ6YMcku9EnqMW6JE9z1l9oVyV2lSr+2E5A5SW0l1u19gtv0yO9jnQ7YkCt26MxCEEmhAY+/4Z+/5t8kv05SDQ/W3W4UdH4NUhvfbNY79rx+I/Vn70AHQ60Mkw2gWroIjNSSwGyBXgiq8XRHKlc8cfOKv81RpEGRtSje0zo0nqAg80BB7qokRcJ91rxnsNcbOv5C8IttFpVlnIO8ugHTLgwl+QT0SzrtGvZzueZOAe3usV84U6V3Apd4QsvuoqrLvIvTZAQbAQRTUV9FIF2W0e2ggMaqGbJfTgDjQrF5dz7wtyqSmQoI++0VrBHBViXVGzqkJgqxFQ4LjVw6/OC4GVItAWT6zUscL41D1sj3DaW4tO5oUQVVkZ2/vGmBHSljFWm2y0VkIUFyjlqnpNDWJHMDlbVhp8TfWKW64DuXip2gTt1EEZz4tVbheNh7by1cfgaMo1hZg8j6udgt1hZd0xOA58yYYVnpCXdbQlvPc0Ousqxkk0LSahk6E7wUYZWoPKK5ghtgkOc2gpy0M0JXgN...","sessionId":"64b6004f-c1f6-4d44-8b44-f5196bdf07dd"}
info: <-- GET /wd/hub/session/64b6004f-c1f6-4d44-8b44-f5196bdf07dd/screenshot 200 2269.884 ms - 230454 {"status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAAAXNSR0IArs4c6QAAQABJREFUeAHsXQegLDd1nff5pvcOptj03iEUGwgQ03uA0EwAmwA2ppMAgdAh1FAMBAwxIfQeeugu9N47mN6x6WDjHx1pzswdjabtbJndPfr/raSr23Sk3b2j0Wh3jj/++D1Zr7QTcbHuxH2R9VAtlZJeUiJF9SpYd/xLtW2Po1EdWNwfuZCnkmFPNU+etrOz2h6s2v7kB0gOtiKg+dMKT2fjHnzmKQmBBgQWPjvWfP6Nxme0goaBy8nd6rs52i2MbO0Y/8HeQcCGNIUCV0Cs4+sFscP5nSL+s4yQtibQZmm2jJZQh649hRx5kCNRH+uBGuhdNMiSpyyH0o7THNsttdJqTnFjAT34Tt1NB+Icje1fGk4FvaBXuZI9pT1HiRsdKW+n09a2V+nbK0o8i/fJ6YMcku9EnqMW6JE9z1l9oVyV2lSr+2E5A5SW0l1u19gtv0yO9jnQ7YkCt26MxCEEmhAY+/4Z+/5t8kv05SDQ/W3W4UdH4NUhvfbNY79rx+I/Vn70AHQ60Mkw2gWroIjNSSwGyBXgiq8XRHKlc8cfOKv81RpEGRtSje0zo0nqAg80BB7qokRcJ91rxnsNcbOv5C8IttFpVlnIO8ugHTLgwl+QT0SzrtGvZzueZOAe3usV84U6V3Apd4QsvuoqrLvIvTZAQbAQRTUV9FIF2W0e2ggMaqGbJfTgDjQrF5dz7wtyqSmQoI++0VrBHBViXVGzqkJgqxFQ4LjVw6/OC4GVItAWT6zUscL41D1sj3DaW4tO5oUQVVkZ2/vGmBHSljFWm2y0VkIUFyjlqnpNDWJHMDlbVhp8TfWKW64DuXip2gTt1EEZz4tVbheNh7by1cfgaMo1hZg8j6udgt1hZd0xOA58yYYVnpCXdbQlvPc0Ousqxkk0LSahk6E7wUYZWoPKK5ghtgkOc2gpy0M0JXgN...","sessionId":"64b6004f-c1f6-4d44-8b44-f5196bdf07dd"}
info: --> GET /wd/hub/session/64b6004f-c1f6-4d44-8b44-f5196bdf07dd/contexts {}
info: [debug] [REMOTE] Selecting app undefined (try #1 of 8)
info: [debug] [REMOTE] Sending _rpc_forwardGetListing: message to remote debugger
info: [debug] [REMOTE] {"__argument":{"WIRConnectionIdentifierKey":"cfb7bc1e-9b2c-43ed-83e3-9420a4ff68a6"},"__selector":"_rpc_forwardGetListing:"}
info: [debug] [REMOTE] TypeError: Cannot read property 'bplistOverride' of undefined

**Comment by saikrishna321** [comment]
@Timawg +1 even i have faced this with the WordPress application

**Comment by Timawg** [comment]
@saikrishna321 The app is partially built in Swift but for the most part in the "old" language.

**Comment by scottdixon** [comment]
@Timawg does the issue persist? can you please post this issue in the [appium-dot-app](https://github.com/appium/appium-dot-app/) project?

**Comment by SrinivasanTarget** [comment]
I see many similar issues related to this already exists in https://github.com/appium/appium-dot-app/issues

**Comment by SrinivasanTarget** [comment]
@triager please close
