### ISSUE TITLE
Cannot get source of obfuscated application

### ISSUE THREAD

**Issue by sofaking** [appium/appium#6109]
Some class names and other strings are obfuscated during the building of our app. When I ask for page_source for a screen with obfuscated element I'm getting:
```
2016-02-05 16:40:57:456 - info: --> GET /wd/hub/session/2d565f3f-2a01-43e0-bb77-3c1baf9b0f07/source {}
2016-02-05 16:40:57:457 - info: [debug] Pushing command to appium work queue: ["source",{}]
2016-02-05 16:40:57:462 - info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
2016-02-05 16:40:57:464 - info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
2016-02-05 16:40:57:467 - info: [debug] [BOOTSTRAP] [debug] Got command action: source
2016-02-05 16:40:57:611 - info: [debug] [BOOTSTRAP] [debug] Command returned error:org.w3c.dom.DOMException: o.沉
2016-02-05 16:40:57:612 - info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":13,"value":"o.沉"}
2016-02-05 16:40:57:612 - info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processi
ng the command.","origValue":"o.沉"},"sessionId":"2d565f3f-2a01-43e0-bb77-3c1baf9b0f07"}
2016-02-05 16:40:57:614 - info: <-- GET /wd/hub/session/2d565f3f-2a01-43e0-bb77-3c1baf9b0f07/source 500 158.398 ms - 174 
```

However, find_element and everything else works fine. And BTW, UI Automation Viewer is able to show hierarchy of such screen. It looks like so:
![screen shot 2016-02-05 at 17 20 42](https://cloud.githubusercontent.com/assets/690515/12848838/4720013e-cc2d-11e5-87ce-dcb9efeceb64.png)

And since the logic of getting source is hidden deep into AppiumBootstrap.jar I don't know how to debug it.

**Comment by imurchie** [comment]
Is it possible to get a copy of your app? 

My attempts to put those characters into an app don't fail.

**Comment by sofaking** [comment]
Hello, Isaac! Thanks for looking into it.
Yes, you can get it directly from playstore: https://play.google.com/store/apps/details?id=com.kms.free
Just skip the first run wizard and try to get page_source from main screen or from settings.

**Comment by imurchie** [comment]
Thanks!

Is there an activity that will get me to the right place?

**Comment by sofaking** [comment]
AFAIK, there's not. You just need to skip through the wizard and get to the screen with a shield at the center.

**Comment by imurchie** [comment]
Ok. Reproduced.

For reference, the steps:

```js
  it('should get the source', function (done) {
    driver
      .setImplicitWaitTimeout(10000)
      .elementByAccessibilityId('WELCOME_NEXT_STEP')
        .click()
      .elementByClassName('android.widget.Button')
        .click()
      .elementById('com.kms.free:id/skip_link')
        .click()
      .elementByAccessibilityId('WIZARD_FINISH_BUTTON')
        .click()
      .source().print()
      .nodeify(done);
  });
```

**Comment by imurchie** [comment]
It looks to me  that your obfuscation is going too far in certain cases, and the XML parser is unable to handle it.

Here is the output from a run where I replace the offending characters with `this.is.broken`: https://gist.github.com/imurchie/8c7914facfc818b38ae4

Android Dalvik uses the retired Apache Harmony project to do XML parsing, and that parser does not allow anything outside of the Latin alphabet and Arabic numerals in it's identifiers (see [here](http://grepcode.com/file/repo1.maven.org/maven2/org.robovm/robovm-rt/0.0.8/org/apache/harmony/xml/dom/DocumentImpl.java#DocumentImpl.isXMLIdentifier%28java.lang.String%29)).

**Comment by sofaking** [comment]
What do you think, why uiautomatorviewer doesn't crash under the same conditions?

**Comment by imurchie** [comment]
Because it's not getting the source. If it doesn't have to convert to XML, then there should be no problem.

**Comment by sofaking** [comment]
If I understood correctly the solution could be to parse XML on the side of Appium Server.
Anyway, as a workaround we now test only debug builds. So for me issue is kind of closed.
