### ISSUE TITLE
Appium command to wake up the Android Device

### ISSUE THREAD

**Issue by muralidhar1620** [appium/appium#6115]
I am working on lock screen android native app automation with appium 

I am able to lock the device with command driver.lockScreen(X sec);

 Before unlock, phone is going to sleep mode and not able to wake up the device, Is there any appium command to wake up the device ? (Tapping Power button manually will wake up the device, I need this to do it from Script)

If i can wake up the device then i am able to unlock.

App play store link : https://play.google.com/store/apps/details?id=com.perk.screen

**Comment by bikshamar** [comment]
adb shell input keyevent 26
