### ISSUE TITLE
Launch app with different wait activity

### ISSUE THREAD

**Issue by email2vimalraj** [appium/appium#6117]
We should have the capability to set the app activity and the app wait activity while launching the app. For instance:

- Create the android driver object with the following capabilities:
```
    platformName: Android
    deviceName:   Android
    appPackage:   com.demos.myapp
    appActivity:  com.demos.myapp.activities.HomePageActivity
    appWaitActivity:  com.demos.myapp.activities.MainActivity
    app:          myapp.apk
    noReset:      true
    newCommandTimeout: 120
```

- I perform some actions and navigations and at the end I'll be at the `com.demos.myapp.activities.ReportActivity`

- I force close the app

- I want to launch the app now and verify I am in `com.demos.myapp.activities.ReportActivity`.

Now the problem is:
```
Responding to client with error: {"status":1,"value":{"message":"Unable to launch the app: Error: com.demos.myapp/.activities.MainActivity never started. Current: com.demos.myapp/.activities.ReportActivity"},"sessionId":"5586f2c3-93de-454e-b991-e9958478ff03"}
```

I tried using the startActivity like this as well:
`startActivity("com.demos.myapp", "com.demos.myapp.activities.HomePageActivity", "com.demos.myapp", "com.demos.myapp.activities.ReportActivity")`

This gave me an error stack trace like this:
```
info: <-- POST /wd/hub/session/afa6f9c2-f277-4e97-9290-2b9c7aa7b78d/appium/device/start_activity 500 1.372 ms - 93 
TypeError: Cannot read property 'startApp' of null
    at [object Object].Android.startApp (/Users/vselvam/.node/lib/node_modules/appium/lib/devices/android/android.js:397:13)
    at exports.startActivity (/Users/vselvam/.node/lib/node_modules/appium/lib/server/controller.js:144:16)
    at Layer.handle [as handle_request] (/Users/vselvam/.node/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/vselvam/.node/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/vselvam/.node/lib/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
...
```

I use Node v5.0.0 and appium v1.4.16.

**Comment by email2vimalraj** [comment]
@imurchie - Anyhelp?

**Comment by priyankshah217** [comment]
@email2vimalraj , can u just remove appActivity and just run with appWaitActivity only. In my case i just provided wait activity in capability and worked perfectly.

**Comment by email2vimalraj** [comment]
@priyankshah217, still getting the same error:

```
info: <-- POST /wd/hub/session/6cb553ec-5674-4fbc-b14c-843e67df2e0b/appium/device/start_activity 500 2.138 ms - 93 
TypeError: Cannot read property 'startApp' of null
    at [object Object].Android.startApp (/Users/vselvam/.node/lib/node_modules/appium/lib/devices/android/android.js:397:13)
    at exports.startActivity (/Users/vselvam/.node/lib/node_modules/appium/lib/server/controller.js:144:16)
    at Layer.handle [as handle_request] (/Users/vselvam/.node/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
```

**Comment by priyankshah217** [comment]
@email2vimalraj "I force close the app" what it means are you stopping app or putting current app in background?

**Comment by email2vimalraj** [comment]
Forget the force close app... Even it is not working if I send `driver.closeApp()`, and then call `driver.launchApp()`

**Comment by priyankshah217** [comment]
can u provide steps whats are you doing and also post your appium server logs on gist. Also can u check driver==null after closing your app.

**Comment by imurchie** [comment]
Yes, please provide the server logs in a [gist](https://gist.github.com/). 

What version of the server are you using?

**Comment by email2vimalraj** [comment]
@priyankshah217 and @imurchie : Thanks for replying me. I found out that there is a bug in `appium-adb` which does not parse the multiple wait activity capability. Raised the bug issue there: https://github.com/appium/appium-adb/issues/138
