### ISSUE TITLE
How to verify Custom icons using appium?

### ISSUE THREAD

**Issue by mohitgupta1176** [appium/appium#6119]
<img width="1224" alt="screen shot 2016-02-09 at 5 48 23 pm" src="https://cloud.githubusercontent.com/assets/6658790/12916006/17ea19ba-cf55-11e5-91dc-fdc66ebc459e.png">

How to verify Custom icons which is not visible through appium inspector for Ios
Trying to automate an IOS native application,
I want to click on + icon,but same is not visible through appium inspector and instruments recording 
Also tried out x-y cordinate ((AppiumDriver) driver).tap(77, 185, 54, 23);
Attach Screen shot of icons for reference..

**Comment by shivakrishnach31** [comment]
@mohitgupta1176 , Pls refer https://github.com/appium/appium/issues/5020

**Comment by mohitgupta1176** [comment]
Thanks Shiva..

On Wed, Feb 10, 2016 at 10:01 AM, Shiva Krishna <notifications@github.com>
wrote:

> @mohitgupta1176 <https://github.com/mohitgupta1176> , Pls refer #5020
> <https://github.com/appium/appium/issues/5020>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/appium/appium/issues/6119#issuecomment-182193173>.
>



-- 
Regards
MOHIT GUPTA
+919717912816
