### ISSUE TITLE
info: [debug] [BOOTSTRAP] [debug] Command returned error:java.lang.IllegalStateException: UiAutomation not connected!

### ISSUE THREAD

**Issue by rajivpaliath** [appium/appium#6120]
Hi, I am trying to automate an android tablet app. There is a pin on the tablet, which I am able to enter. I can see the app has been started on my device. 

But, then I start getting this message on the appium log: java.lang.IllegalStateException: UiAutomation not connected and the script fails.

I am attaching the logfile. Please let me know what needs to be done if any of you has experienced this.
[appium.txt](https://github.com/appium/appium/files/124116/appium.txt)

Here is the desired capabilities that I am passing:
'appium-version' => '1.0',
'platformName' => 'Android',
'platformVersion' => '4.4',
'deviceName' => 'Android',
'appPackage' => 'com.telmate.TelmateGettingout',
'appActivity' => 'com.telmate.TelmateGettingout.ui.IntroActivity'

Appium version that I am using is: 1.4.13

**Comment by scottdixon** [comment]
Can you please try again using Appium 1.5 beta
