### ISSUE TITLE
Bug : error: uncaughtException: Cannot read property 'forwardPort' of null date

### ISSUE THREAD

**Issue by namannigam** [appium/appium#6123]
Well I faced this issue while executing our tests with `--full-reset : True`. Following are the logs from the Appium Server : 

> Launching Appium with command: export ANDROID_HOME="/Applications/adt-bundle-mac-x86_64-20140702/sdk"; '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --session-override --debug-log-spacing --log-timestamp --automation-name "Appium" --platform-name "Android" --platform-version "5.1" --app "/Users/macUser/GitHub/AutomationProjects/auto-mobile/app/com.myapp.android_ecom_app.apk" --full-reset --dont-stop-app-on-reset --app-pkg "com.myapp.android" --device-name "test"
> 
> 2016-02-09 12:10:32:776 - info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
> 
> 2016-02-09 12:10:32:786 - info: Appium REST http interface listener started on 0.0.0.0:4723
> 
> 2016-02-09 12:10:32:798 - info: [debug] Non-default server args: {"app":"/Users/macUser/GitHub/AutomationProjects/auto-mobile/app/com.myapp.android_ecom_app.apk","sessionOverride":true,"fullReset":true,"logTimestamp":true,"androidPackage":"com.myapp.android","deviceName":"test","platformName":"Android","platformVersion":"5.1","automationName":"Appium","defaultCommandTimeout":7200,"dontStopAppOnReset":true,"debugLogSpacing":true}
> 
> 2016-02-09 12:10:32:801 - info: Console LogLevel: debug
> 
> 2016-02-09 12:10:33:271 - info: --> GET /wd/hub/status {}
> 2016-02-09 12:10:33:274 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
> 
> 2016-02-09 12:10:33:285 - info: <-- GET /wd/hub/status 200 14.237 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
> 
> 2016-02-09 12:10:35:426 - info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk","appPackage":"com.myapp.android","appActivity":"com.myapp.android.SplashActivity","automationName":"Appium","takesScreenshot":"true","platformName":"Android","deviceName":"Mi 4i"}}
> 2016-02-09 12:10:35:427 - info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.8.0_65)
> 2016-02-09 12:10:35:428 - info: *************************************
> 2016-02-09 12:10:35:428 - info: *************************************
> 2016-02-09 12:10:35:428 - info: *************************************
> 2016-02-09 12:10:35:428 - info: *************************************
> 2016-02-09 12:10:35:428 - info: *************************************
> 2016-02-09 12:10:35:429 - info: *************************************
> 2016-02-09 12:10:35:429 - info: *************************************
> 2016-02-09 12:10:35:429 - info: *************************************
> 2016-02-09 12:10:35:429 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:35:429 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:35:430 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:35:431 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:35:431 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:35:431 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:35:431 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:35:432 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:35:432 - info: *************************************
> 2016-02-09 12:10:35:432 - info: *************************************
> 2016-02-09 12:10:35:432 - info: *************************************
> 2016-02-09 12:10:35:432 - info: *************************************
> 2016-02-09 12:10:35:433 - info: *************************************
> 2016-02-09 12:10:35:433 - info: *************************************
> 2016-02-09 12:10:35:433 - info: *************************************
> 2016-02-09 12:10:35:433 - info: *************************************
> 2016-02-09 12:10:35:434 - warn: Converting cap takesScreenshot from string to boolean. This might cause unexpected behavior.
> 2016-02-09 12:10:35:436 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : takesScreenshot
> 2016-02-09 12:10:35:439 - info: [debug] Using local app from desired caps: /Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk
> 2016-02-09 12:10:35:441 - info: [debug] Creating new appium session 8443d1a2-c37f-470f-b013-0820fdd517b0
> 2016-02-09 12:10:35:442 - info: Starting android appium
> 2016-02-09 12:10:35:443 - info: [debug] Getting Java version
> 
> 2016-02-09 12:10:35:590 - info: Java version is: 1.8.0_65
> 
> 2016-02-09 12:10:35:591 - info: [debug] Checking whether adb is present
> 
> 2016-02-09 12:10:35:593 - info: [debug] Using adb from /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb
> 2016-02-09 12:10:35:594 - info: [debug] Using fast reset? false
> 2016-02-09 12:10:35:594 - info: [debug] Preparing device for session
> 2016-02-09 12:10:35:595 - info: [debug] Checking whether app is actually present
> 2016-02-09 12:10:35:595 - info: Retrieving device
> 2016-02-09 12:10:35:596 - info: [debug] Trying to find a connected android device
> 2016-02-09 12:10:35:596 - info: [debug] Getting connected devices...
> 2016-02-09 12:10:35:599 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb devices
> 
> 2016-02-09 12:10:38:183 - info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk","appPackage":"com.myapp.android","appActivity":"com.myapp.android.SplashActivity","automationName":"Appium","takesScreenshot":"true","platformName":"Android","deviceName":"Mi 4i"}}
> 
> 2016-02-09 12:10:38:183 - info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.8.0_65)
> 2016-02-09 12:10:38:183 - info: *************************************
> 2016-02-09 12:10:38:183 - info: *************************************
> 2016-02-09 12:10:38:184 - info: *************************************
> 2016-02-09 12:10:38:184 - info: *************************************
> 2016-02-09 12:10:38:184 - info: *************************************
> 
> 2016-02-09 12:10:38:184 - info: *************************************
> 2016-02-09 12:10:38:184 - info: *************************************
> 2016-02-09 12:10:38:185 - info: *************************************
> 2016-02-09 12:10:38:185 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:38:185 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:38:185 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:38:185 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:38:185 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:38:185 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:38:185 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:38:186 - info: ***\*        NEW SESSION           ***
> 2016-02-09 12:10:38:186 - info: *************************************
> 2016-02-09 12:10:38:186 - info: *************************************
> 2016-02-09 12:10:38:186 - info: *************************************
> 2016-02-09 12:10:38:186 - info: *************************************
> 2016-02-09 12:10:38:186 - info: *************************************
> 2016-02-09 12:10:38:186 - info: *************************************
> 2016-02-09 12:10:38:187 - info: *************************************
> 2016-02-09 12:10:38:187 - info: *************************************
> 2016-02-09 12:10:38:187 - info: Found an existing session to clobber, shutting it down first...
> 2016-02-09 12:10:38:187 - info: Shutting down appium session
> 2016-02-09 12:10:38:187 - info: [debug] Removing app from device
> 2016-02-09 12:10:38:188 - info: [debug] Uninstalling com.myapp.android
> 2016-02-09 12:10:38:189 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb shell "am force-stop com.myapp.android"
> 
> 2016-02-09 12:10:38:661 - info: [debug] 1 device(s) connected
> 
> 2016-02-09 12:10:38:661 - info: Found device 0e65ec12
> 2016-02-09 12:10:38:661 - info: [debug] Setting device id to 0e65ec12
> 2016-02-09 12:10:38:662 - info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> 
> 2016-02-09 12:10:38:663 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 wait-for-device
> 2016-02-09 12:10:38:677 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "echo 'ready'"
> 
> 2016-02-09 12:10:38:699 - info: [debug] Starting logcat capture
> 
> 2016-02-09 12:10:38:722 - info: [debug] Getting device API level
> 
> 2016-02-09 12:10:38:722 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "getprop ro.build.version.sdk"
> 
> 2016-02-09 12:10:38:762 - info: [debug] Device is at API Level 21
> 
> 2016-02-09 12:10:38:762 - info: Device API level is: 21
> 2016-02-09 12:10:38:763 - info: [debug] Extracting strings for language: default
> 2016-02-09 12:10:38:766 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "getprop persist.sys.language"
> 
> 2016-02-09 12:10:38:810 - info: [debug] Current device persist.sys.language: en
> 
> 2016-02-09 12:10:38:810 - info: [debug] java -jar "/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk" "/tmp/com.myapp.android" en
> 
> 2016-02-09 12:10:39:459 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 uninstall com.myapp.android
> 
> 2016-02-09 12:10:39:847 - info: [debug] No strings.xml for language 'en', getting default strings.xml
> 
> 2016-02-09 12:10:39:848 - info: [debug] java -jar "/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk" "/tmp/com.myapp.android"
> 
> 2016-02-09 12:10:40:705 - info: [debug] Reading strings from converted strings.json
> 
> 2016-02-09 12:10:40:707 - info: [debug] Setting language to default
> 
> 2016-02-09 12:10:40:708 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 push "/tmp/com.myapp.android/strings.json" /data/local/tmp
> 
> 2016-02-09 12:10:40:797 - info: [debug] Checking whether aapt is present
> 
> 2016-02-09 12:10:40:800 - info: [debug] Using aapt from /Applications/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/aapt
> 
> 2016-02-09 12:10:40:801 - info: [debug] Retrieving process from manifest.
> 2016-02-09 12:10:40:801 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/aapt dump xmltree /Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk AndroidManifest.xml
> 
> 2016-02-09 12:10:40:819 - info: [debug] Set app process to: com.myapp.android
> 2016-02-09 12:10:40:819 - info: [debug] Uninstalling com.myapp.android
> 2016-02-09 12:10:40:820 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "am force-stop com.myapp.android"
> 
> 2016-02-09 12:10:41:520 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 uninstall com.myapp.android
> 
> 2016-02-09 12:10:41:963 - info: [debug] App was uninstalled
> 
> 2016-02-09 12:10:41:963 - info: [debug] Pressing the HOME button
> 2016-02-09 12:10:41:964 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "input keyevent 3"
> 
> 2016-02-09 12:10:42:499 - info: [debug] App was not uninstalled, maybe it wasn't on device?
> 
> 2016-02-09 12:10:42:499 - info: [debug] Checking app cert for /Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk.
> 2016-02-09 12:10:42:500 - info: [debug] executing cmd: java -jar /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/jars/verify.jar /Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk
> 
> 2016-02-09 12:10:43:304 - info: [debug] App already signed.
> 
> 2016-02-09 12:10:43:304 - info: [debug] Zip-aligning /Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk
> 
> 2016-02-09 12:10:43:304 - info: [debug] Checking whether zipalign is present
> 2016-02-09 12:10:43:307 - info: [debug] Using zipalign from /Applications/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/zipalign
> 2016-02-09 12:10:43:308 - info: [debug] Zip-aligning apk.
> 2016-02-09 12:10:43:309 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/zipalign -f 4 /Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk /var/folders/9_/zhwc774n3kx8k1g7s_n3q9n15by3jh/T/11619-6667-fu8b2f/appium.tmp
> 2016-02-09 12:10:43:313 - info: [debug] Stopping logcat capture
> 2016-02-09 12:10:43:317 - info: [debug] Logcat terminated with code null, signal SIGTERM
> 2016-02-09 12:10:43:318 - info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> 
> 2016-02-09 12:10:43:459 - info: [debug] MD5 for app is f379074e9ac9dc0854f1f8103e09ff96
> 
> 2016-02-09 12:10:43:460 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "ls /data/local/tmp/f379074e9ac9dc0854f1f8103e09ff96.apk"
> 
> 2016-02-09 12:10:43:550 - info: [debug] Getting install status for com.myapp.android
> 
> 2016-02-09 12:10:43:550 - info: [debug] Getting device API level
> 2016-02-09 12:10:43:551 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "getprop ro.build.version.sdk"
> 
> 2016-02-09 12:10:43:576 - info: [debug] Device is at API Level 21
> 
> 2016-02-09 12:10:43:578 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "pm list packages -3 com.myapp.android"
> 
> 2016-02-09 12:10:44:231 - info: [debug] App is not installed
> 
> 2016-02-09 12:10:44:232 - info: Installing App
> 2016-02-09 12:10:44:233 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "mkdir -p /data/local/tmp/"
> 
> 2016-02-09 12:10:44:361 - info: [debug] Removing any old apks
> 
> 2016-02-09 12:10:44:364 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "ls /data/local/tmp/*.apk"
> 
> 2016-02-09 12:10:44:389 - info: [debug] No apks to examine
> 
> 2016-02-09 12:10:44:390 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 push "/Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk" /data/local/tmp/f379074e9ac9dc0854f1f8103e09ff96.apk
> 
> 2016-02-09 12:10:44:437 - info: --> GET /wd/hub/status {}
> 
> 2016-02-09 12:10:44:438 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
> 
> 2016-02-09 12:10:44:442 - info: <-- GET /wd/hub/status 200 4.969 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
> 
> 2016-02-09 12:10:47:112 - info: [debug] Uninstalling com.myapp.android
> 
> 2016-02-09 12:10:47:113 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "am force-stop com.myapp.android"
> 
> 2016-02-09 12:10:48:219 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 uninstall com.myapp.android
> 
> 2016-02-09 12:10:49:080 - info: [debug] App was not uninstalled, maybe it wasn't on device?
> 
> 2016-02-09 12:10:49:080 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "pm install -r /data/local/tmp/f379074e9ac9dc0854f1f8103e09ff96.apk"
> 
> 2016-02-09 12:10:50:066 - info: <-- POST /wd/hub/session - - ms - - 
> 
> 2016-02-09 12:10:50:323 - warn: UiAutomator did not shut down fast enough, calling it gone
> 
> 2016-02-09 12:10:50:323 - info: [debug] Cleaning up android objects
> 2016-02-09 12:10:50:323 - info: [debug] Cleaning up appium session
> 2016-02-09 12:10:50:324 - info: Old session shut down OK, proceeding to new session
> 2016-02-09 12:10:50:324 - warn: Converting cap takesScreenshot from string to boolean. This might cause unexpected behavior.
> 
> 2016-02-09 12:10:50:325 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : takesScreenshot
> 2016-02-09 12:10:50:327 - info: [debug] Using local app from desired caps: /Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk
> 2016-02-09 12:10:50:327 - info: [debug] Creating new appium session bd9ae91c-9d44-4a7a-958d-61d6f1cb8a5b
> 2016-02-09 12:10:50:328 - info: Starting android appium
> 2016-02-09 12:10:50:328 - info: [debug] Getting Java version
> 
> 2016-02-09 12:10:50:447 - info: Java version is: 1.8.0_65
> 
> 2016-02-09 12:10:50:448 - info: [debug] Checking whether adb is present
> 
> 2016-02-09 12:10:50:449 - info: [debug] Using adb from /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb
> 2016-02-09 12:10:50:450 - info: [debug] Using fast reset? false
> 2016-02-09 12:10:50:450 - info: [debug] Preparing device for session
> 2016-02-09 12:10:50:450 - info: [debug] Checking whether app is actually present
> 2016-02-09 12:10:50:451 - info: Retrieving device
> 2016-02-09 12:10:50:451 - info: [debug] Trying to find a connected android device
> 2016-02-09 12:10:50:451 - info: [debug] Getting connected devices...
> 2016-02-09 12:10:50:451 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb devices
> 
> 2016-02-09 12:10:50:465 - info: [debug] 1 device(s) connected
> 2016-02-09 12:10:50:465 - info: Found device 0e65ec12
> 2016-02-09 12:10:50:466 - info: [debug] Setting device id to 0e65ec12
> 2016-02-09 12:10:50:466 - info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> 2016-02-09 12:10:50:466 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 wait-for-device
> 2016-02-09 12:10:50:479 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "echo 'ready'"
> 
> 2016-02-09 12:10:50:571 - info: [debug] Starting logcat capture
> 
> 2016-02-09 12:10:50:594 - info: [debug] Getting device API level
> 
> 2016-02-09 12:10:50:594 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "getprop ro.build.version.sdk"
> 
> 2016-02-09 12:10:50:635 - info: [debug] Device is at API Level 21
> 
> 2016-02-09 12:10:50:635 - info: Device API level is: 21
> 2016-02-09 12:10:50:635 - info: [debug] Extracting strings for language: default
> 2016-02-09 12:10:50:636 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "getprop persist.sys.language"
> 
> 2016-02-09 12:10:50:676 - info: [debug] Current device persist.sys.language: en
> 
> 2016-02-09 12:10:50:676 - info: [debug] java -jar "/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk" "/tmp/com.myapp.android" en
> 
> 2016-02-09 12:10:51:948 - info: [debug] No strings.xml for language 'en', getting default strings.xml
> 
> 2016-02-09 12:10:51:948 - info: [debug] java -jar "/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/jars/appium_apk_tools.jar" "stringsFromApk" "/Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk" "/tmp/com.myapp.android"
> 
> 2016-02-09 12:10:52:827 - info: [debug] Reading strings from converted strings.json
> 
> 2016-02-09 12:10:52:829 - info: [debug] Setting language to default
> 
> 2016-02-09 12:10:52:830 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 push "/tmp/com.myapp.android/strings.json" /data/local/tmp
> 
> 2016-02-09 12:10:52:856 - info: [debug] Checking whether aapt is present
> 2016-02-09 12:10:52:858 - info: [debug] Using aapt from /Applications/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/aapt
> 2016-02-09 12:10:52:858 - info: [debug] Retrieving process from manifest.
> 2016-02-09 12:10:52:858 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/aapt dump xmltree /Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk AndroidManifest.xml
> 2016-02-09 12:10:52:868 - info: [debug] Set app process to: com.myapp.android
> 2016-02-09 12:10:52:868 - info: [debug] Uninstalling com.myapp.android
> 2016-02-09 12:10:52:869 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "am force-stop com.myapp.android"
> 
> 2016-02-09 12:10:53:949 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 uninstall com.myapp.android
> 
> undefined
> 
> 2016-02-09 12:11:19:969 - info: [debug] App was uninstalled
> 
> 2016-02-09 12:11:19:969 - info: [debug] Checking app cert for /Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk.
> 2016-02-09 12:11:19:970 - info: [debug] executing cmd: java -jar /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/jars/verify.jar /Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk
> 
> 2016-02-09 12:11:20:803 - info: [debug] App already signed.
> 
> 2016-02-09 12:11:20:803 - info: [debug] Zip-aligning /Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk
> 2016-02-09 12:11:20:803 - info: [debug] Checking whether zipalign is present
> 2016-02-09 12:11:20:804 - info: [debug] Using zipalign from /Applications/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/zipalign
> 2016-02-09 12:11:20:804 - info: [debug] Zip-aligning apk.
> 2016-02-09 12:11:20:805 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/build-tools/android-4.4W/zipalign -f 4 /Users/macUser/GitHub/auto-mobile/app/com.myapp.android_ecom_app.apk /var/folders/9_/zhwc774n3kx8k1g7s_n3q9n15by3jh/T/11619-6667-19ed91y/appium.tmp
> 
> 2016-02-09 12:11:20:932 - info: [debug] MD5 for app is f379074e9ac9dc0854f1f8103e09ff96
> 
> 2016-02-09 12:11:20:932 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "ls /data/local/tmp/f379074e9ac9dc0854f1f8103e09ff96.apk"
> 
> 2016-02-09 12:11:20:996 - info: [debug] Getting install status for com.myapp.android
> 
> 2016-02-09 12:11:20:997 - info: [debug] Getting device API level
> 2016-02-09 12:11:20:997 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "getprop ro.build.version.sdk"
> 
> 2016-02-09 12:11:21:031 - info: [debug] Device is at API Level 21
> 
> 2016-02-09 12:11:21:032 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "pm list packages -3 com.myapp.android"
> 
> 2016-02-09 12:11:22:473 - info: [debug] App is not installed
> 
> 2016-02-09 12:11:22:473 - info: Installing App
> 2016-02-09 12:11:22:474 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "mkdir -p /data/local/tmp/"
> 
> 2016-02-09 12:11:22:513 - info: [debug] Removing any old apks
> 2016-02-09 12:11:22:514 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "ls /data/local/tmp/*.apk"
> 
> 2016-02-09 12:11:22:555 - info: [debug] Found an apk we want to keep at /data/local/tmp/f379074e9ac9dc0854f1f8103e09ff96.apk
> 
> 2016-02-09 12:11:22:555 - info: [debug] Couldn't find any apks to remove
> 2016-02-09 12:11:22:555 - info: [debug] Uninstalling com.myapp.android
> 2016-02-09 12:11:22:556 - info: [debug] executing cmd: /Applications/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb -s 0e65ec12 shell "am force-stop com.myapp.android"
> 
> 2016-02-09 12:11:22:629 - error: uncaughtException: Cannot read property 'forwardPort' of null date=Tue Feb 09 2016 17:41:22 GMT+0530 (IST), pid=6667, uid=1254034992, gid=1493847943, cwd=/Applications/Appium.app/Contents/Resources/node_modules/appium, execPath=/Applications/Appium.app/Contents/Resources/node/bin/node, version=v0.12.7, argv=[/Applications/Appium.app/Contents/Resources/node/bin/node, /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/server/main.js, --command-timeout, 7200, --session-override, --debug-log-spacing, --log-timestamp, --automation-name, Appium, --platform-name, Android, --platform-version, 5.1, --app, /Users/macUser/GitHub/AutomationProjects/auto-mobile/app/com.myapp.android_ecom_app.apk, --full-reset, --dont-stop-app-on-reset, --app-pkg, com.myapp.android, --device-name, test], rss=166219776, heapTotal=122578432, heapUsed=94962576, loadavg=[3.40234375, 3.08349609375, 3.07421875], uptime=84377, trace=[column=11, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/android-common.js, function=[object Object].androidCommon.forwardPort, line=635, method=androidCommon.forwardPort, native=false, column=21, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=607, method=null, native=false, column=17, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=246, method=null, native=false, column=13, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=iterate, line=146, method=null, native=false, column=25, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=157, method=null, native=false, column=21, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=248, method=null, native=false, column=34, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js, function=null, line=612, method=null, native=false, column=9, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/android-common.js, function=, line=548, method=null, native=false, column=5, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js, function=null, line=1360, method=null, native=false, column=9, file=/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js, function=, line=180, method=null, native=false, column=7, file=child_process.js, function=ChildProcess.exithandler, line=742, method=exithandler, native=false, column=17, file=events.js, function=ChildProcess.emit, line=110, method=emit, native=false, column=16, file=child_process.js, function=maybeClose, line=1015, method=null, native=false, column=11, file=child_process.js, function=, line=1183, method=null, native=false, column=17, file=events.js, function=Socket.emit, line=107, method=emit, native=false, column=12, file=net.js, function=Pipe.close, line=485, method=close, native=false], stack=[TypeError: Cannot read property 'forwardPort' of null,     at [object Object].androidCommon.forwardPort (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/android-common.js:635:11),     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:607:21,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:246:17,     at iterate (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:146:13),     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:157:25,     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:248:21,     at /Applications/Appium.app/Contents/Resources/node_modules
> /appium/node_modules/async/lib/async.js:612:34,     at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/android/android-common.js:548:9),     at /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:1360:5,     at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:180:9),     at ChildProcess.exithandler (child_process.js:742:7),     at ChildProcess.emit (events.js:110:17),     at maybeClose (child_process.js:1015:16),     at Socket.<anonymous> (child_process.js:1183:11),     at Socket.emit (events.js:107:17),     at Pipe.close (net.js:485:12)]

**Comment by scottdixon** [comment]
Can you please try with the latest Appium (v1.5) `npm install -g appium`?
