### ISSUE TITLE
Not able to Launch android app and always getting error while installing settings_apk-debug.apk

### ISSUE THREAD

**Issue by rishabhjain2893** [appium/appium#6126]
Error :

> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --app D:\Appium\Amazon\Amazon.apk --pre-launch --platform-name Android --platform-version 23 --automation-name Appium --log-no-color
> Killed Node Server.
> Appium server process ended
> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --app D:\Appium\Amazon\Amazon.apk --platform-name Android --platform-version 23 --automation-name Appium --log-no-color
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"app":"D:\Appium\Amazon\Amazon.apk","address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"23","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"D:\Appium\Amazon\Amazon.apk","appPackage":"com.amazon.mShop.android.shopping","appActivity":"com.amazon.mShop.splashscreen.StartupActivity","platformVersion":"6.0","platformName":"Android","deviceName":"SP7731C11005A190178"}}
> info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.8.0_66)
> info: [debug] Using local app from desired caps: D:\Appium\Amazon\Amazon.apk
> info: [debug] Creating new appium session 841f87e6-d52a-48fc-bc55-412330f476f8
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_66
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from D:\Cherrey\sdk\platform-tools\adb.exe
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device 7731G11044C040177
> info: [debug] Setting device id to 7731G11044C040177
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 wait-for-device
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 23
> info: Device API level is: 23
> info: [debug] Extracting strings for language: default
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: 
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "D:\Appium\Amazon\Amazon.apk" "C:\Users\RISHAB~1.JAI\AppData\Local\Temp\com.amazon.mShop.android.shopping" 
> info: [debug] Reading strings from converted strings.json
> info: [debug] Setting language to default
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 push "C:\Users\RISHAB~1.JAI\AppData\Local\Temp\com.amazon.mShop.android.shopping\strings.json" /data/local/tmp
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from D:\Cherrey\sdk\build-tools\android-4.4W\aapt.exe
> info: [debug] Retrieving process from manifest.
> info: [debug] executing cmd: D:\Cherrey\sdk\build-tools\android-4.4W\aapt.exe dump xmltree D:\Appium\Amazon\Amazon.apk AndroidManifest.xml
> info: [debug] Set app process to: com.amazon.mShop.android.shopping
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Checking app cert for D:\Appium\Amazon\Amazon.apk.
> info: [debug] executing cmd: java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar" D:\Appium\Amazon\Amazon.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning D:\Appium\Amazon\Amazon.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from D:\Cherrey\sdk\build-tools\android-4.4W\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: D:\Cherrey\sdk\build-tools\android-4.4W\zipalign.exe -f 4 D:\Appium\Amazon\Amazon.apk C:\Users\RISHAB~1.JAI\AppData\Local\Temp\116111-10628-16ov19q\appium.tmp
> info: [debug] MD5 for app is fec25b078a3939b77a0c5ad909d5cf6a
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 shell "ls /data/local/tmp/fec25b078a3939b77a0c5ad909d5cf6a.apk"
> info: [debug] Getting install status for com.amazon.mShop.android.shopping
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 23
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 shell "pm list packages -3 com.amazon.mShop.android.shopping"
> info: [debug] App is installed
> info: App is already installed, resetting app
> info: [debug] Running fast reset (stop and clear)
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 shell "am force-stop com.amazon.mShop.android.shopping"
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 shell "pm clear com.amazon.mShop.android.shopping"
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 push "C:\Program Files (x86)\Appium\node_modules\appium\build\android_bootstrap\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: Command failed: C:\Windows\system32\cmd.exe /s /c "D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk""
> 
> info: [debug] Error: Command failed: C:\Windows\system32\cmd.exe /s /c "D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk""
> 
> ```
> at ChildProcess.exithandler (child_process.js:751:12)
> at ChildProcess.emit (events.js:110:17)
> at maybeClose (child_process.js:1016:16)
> at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
> ```
> 
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: C:\Windows\system32\cmd.exe /s /c \"D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 install \"C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk\"\"\n)","killed":false,"code":3221226356,"signal":null,"cmd":"C:\Windows\system32\cmd.exe /s /c \"D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 install \"C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk\"\"","origValue":"Command failed: C:\Windows\system32\cmd.exe /s /c \"D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 install \"C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk\"\"\n"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 17009.065 ms - 856 

Ecllipse Error 
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: Command failed: C:\Windows\system32\cmd.exe /s /c "D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk""
) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 17.19 seconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'IN50063NBW', ip: '192.168.91.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_66'
Driver info: io.appium.java_client.android.AndroidDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
    at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
    at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
    at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:247)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:129)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
    at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
    at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:161)
    at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:170)
    at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:82)
    at Appauto.main(Appauto.java:29)

Please help to give solution.

**Comment by rishabhjain2893** [comment]
Program :
import io.appium.java_client.MobileElement;
import io.appium.java_client.android.AndroidDriver;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.remote.DesiredCapabilities;
//import org.testng.annotations.AfterTest;
//import org.testng.annotations.Test;


public class Appauto {
	
	private static AndroidDriver driver;
	
	
	public static void main(String g[]) throws MalformedURLException,InterruptedException
	{
		File app = new File("D:\\Appium\\Amazon\\Amazon.apk");
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability("deviceName", "SP7731C11005A190178");
		cap.setCapability("platformVersion", "6.0");
		cap.setCapability("platformName", "Android");
		cap.setCapability("app", app.getAbsolutePath());
		cap.setCapability("appPackage", "com.amazon.mShop.android.shopping");
		cap.setCapability("appActivity", "com.amazon.mShop.splashscreen.StartupActivity");
		
		driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),cap);
		driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS);
		driver.quit();
	}
	

}

**Comment by imurchie** [comment]
Can you try installing manually? Using the command

```
D:\Cherrey\sdk\platform-tools\adb.exe -s 7731G11044C040177 install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
```
