### ISSUE TITLE
Can we automate fire tv stick using appium

### ISSUE THREAD

**Issue by Jitu1888** [appium/appium#6127]
We are trying to automate application which is downloaded in fire tv stick.

I dont know how to proceed. Need a help from you guys.

**Comment by imurchie** [comment]
I don't know that it has been tried. Have you checked in the discussion list? https://discuss.appium.io/

**Comment by scottdixon** [comment]
Reopen if you have any queries.

**Comment by Jitu1888** [comment]
We didnt get any feed back on it.

**Comment by Jitu1888** [comment]
Please need a solution on it

**Comment by SrinivasanTarget** [comment]
@Jitu1888 Please discuss this on our forum, https://discuss.appium.io/

**Comment by jay58** [comment]
Yes we can do that. Check https://discuss.appium.io/ for the same.
