### ISSUE TITLE
vulnerabilities on "uglify-js" node module used

### ISSUE THREAD

**Issue by SrinivasanTarget** [appium/appium#6131]
Issue: https://gist.github.com/SrinivasanTarget/d47222af770264f1efc6

https://nodesecurity.io/advisories/48

Soln: Updating uglify-js to >=2.6.0  in our appium modules.

@imurchie @moizjv @jlipps fyi

**Comment by SrinivasanTarget** [comment]
On Looking further path leads to swig (currently not maintained) node module we use on appium-express.

@imurchie Any thoughts?

**Comment by SrinivasanTarget** [comment]
https://github.com/wycats/handlebars.js/ Looks more promising instead of swig

**Comment by imurchie** [comment]
Handlebars/mustache are much too heavyweight for what we use templating for. I would much rather get rid of `swig` in favor of something like `lodash` templates (https://lodash.com/docs#template).

**Comment by imurchie** [comment]
HOw it would work: https://github.com/appium/appium-express/pull/10
