### ISSUE TITLE
mobile: tap is not working 

### ISSUE THREAD

**Issue by s-sridevi15** [appium/appium#6132]
Hi, 
  I am using 
appium version 1.5.0-beta11 
java-client 3.1.0

When I run the following code 
JavascriptExecutor js = (JavascriptExecutor) driver;
		HashMap<String, Double> tapObject = new HashMap<String, Double>();
		tapObject.put("x", (double) element.getLocation().getX());
		tapObject.put("y", (double) element.getLocation().getY());
		tapObject.put("duration", (double) 0);
		tapObject.put("touchCount", (double) 4);
		js.executeScript("mobile: tap", tapObject);

I got an error " org.openqa.selenium.UnsupportedCommandException: Unknown command, all the mobile commands except scroll have been removed. (WARNING: The server did not provide any stacktrace information) "

I need to tap one of the element 4 times with duration 0 . It seems like appium does not support "mobile: tap" using javascript . Is there any alternative for mobile gestures? I stucked with appium automation as it is not supported. 
Appreciate if you somebody can suggest alternative way

**Comment by scottdixon** [comment]
`mobile: tap` has been deprecated for some time and was removed in 1.5

You can use the [touch action api](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md) instead.
