### ISSUE TITLE
1.5.0-beta14. Windows 7/8/10. Can't launch appium node via command line.  

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/appium#6133]
The command line sample:
> node C:\The_Path_To_NPM_Root_Directory\node_modules\appium\build\lib\main.js --default-capabilities '{"platformName": "Android"}'

Error: 
>usage: main.js [-h] [-v] [--shell] [--ipa IPA] [-a ADDRESS] [-p PORT]
               [-ca CALLBACKADDRESS] [-cp CALLBACKPORT] [-bp BOOTSTRAPPORT]
               [-r BACKENDRETRIES] [--session-override] [-l] [-g LOG]
               [--log-level {info,info:debug,info:info,info:warn,info:error,warn
,warn:debug,warn:info,warn:warn,warn:error,error,error:debug,error:info,error:wa
rn,error:error,debug,debug:debug,debug:info,debug:warn,debug:error}]
               [--log-timestamp] [--local-timezone] [--log-no-colors]
               [-G WEBHOOK] [--safari] [--default-device] [--force-iphone]
               [--force-ipad] [--tracetemplate AUTOMATIONTRACETEMPLATEPATH]
               [--instruments INSTRUMENTSPATH] [--nodeconfig NODECONFIG]
               [-ra ROBOTADDRESS] [-rp ROBOTPORT]
               [--selendroid-port SELENDROIDPORT]
               [--chromedriver-port CHROMEDRIVERPORT]
               [--chromedriver-executable CHROMEDRIVEREXECUTABLE]
               [--show-config] [--no-perms-check]
               [--command-timeout DEFAULTCOMMANDTIMEOUT] [--strict-caps]
               [--isolate-sim-device] [--tmp TMPDIR] [--trace-dir TRACEDIR]
               [--debug-log-spacing] [--suppress-adb-kill-server]
               [--async-trace]
               [--webkit-debug-proxy-port WEBKITDEBUGPROXYPORT]
               [--default-capabilities DEFAULTCAPABILITIES] [-k]
               [--platform-name PLATFORMNAME]
               [--platform-version PLATFORMVERSION]
               [--automation-name AUTOMATIONNAME] [--device-name DEVICENAME]
               [--browser-name BROWSERNAME] [--app APP] [-lt LAUNCHTIMEOUT]
               [--language LANGUAGE] [--locale LOCALE] [-U UDID]
               [--orientation ORIENTATION] [--no-reset] [--full-reset]
               [--app-pkg APPPACKAGE] [--app-activity APPACTIVITY]
               [--app-wait-package APPWAITPACKAGE]
               [--app-wait-activity APPWAITACTIVITY]
               [--device-ready-timeout DEVICEREADYTIMEOUT]
               [--android-coverage ANDROIDCOVERAGE] [--avd AVD]
               [--avd-args AVDARGS] [--use-keystore]
               [--keystore-path KEYSTOREPATH]
               [--keystore-password KEYSTOREPASSWORD] [--key-alias KEYALIAS]
               [--key-password KEYPASSWORD] [--intent-action INTENTACTION]
               [--intent-category INTENTCATEGORY] [--intent-flags INTENTFLAGS]
               [--intent-args OPTIONALINTENTARGUMENTS]
               [--dont-stop-app-on-reset] [--calendar-format CALENDARFORMAT]
               [--native-instruments-lib] [--keep-keychains]
               [--localizable-strings-dir LOCALIZABLESTRINGSDIR]
               [--show-ios-log]

>main.js: error: argument "--default-capabilities": Invalid parse value: '{platfo
rmName:

The similar command works on Mac OS X. 

>/usr/local/lib/node_modules/appium/build/lib/main.js --default-capabilities '{"platformName": "iOS"}'

>[Appium] Welcome to Appium v1.5.0-beta14 (REV f7b4c9e0e7ab8f0bde765a47f24d11aa11a3d038)
[Appium] Non-default server args:
[Appium]   defaultCapabilities: { platformName: 'iOS' }
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   platformName: 'iOS'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

So. How to form the command string correctly on Windows? 
or
Is it the bug?

**Comment by TikhomirovSergey** [comment]
appium/java-client#302
appium/appium-dotnet-driver#136

https://github.com/appium/java-client/issues/319
https://github.com/appium/appium-dotnet-driver/issues/138

**Comment by imurchie** [comment]
@scottdixon Can you take a look at this Windows issue?

**Comment by scottdixon** [comment]
@imurchie sure.

@TikhomirovSergey keep you posted on these windows issues.

**Comment by TikhomirovSergey** [comment]
ok.

**Comment by imurchie** [comment]
The quotes appear to need to be escaped. `--default-capabilities '{\"platformName\": \"Android\"}'` works.

I guess this needs to be documented. Blech.

**Comment by TikhomirovSergey** [comment]
@scottdixon @imurchie 
Guys 
It is ok if I try to start node programmatically.
![](https://cloud.githubusercontent.com/assets/4927589/13221318/e3d3ed9a-d98b-11e5-916c-b0084bf292a9.png)

![](https://cloud.githubusercontent.com/assets/4927589/13221180/164b1dda-d98b-11e5-8553-540a857c7b1a.png)

:+1: 

But how to start a node via command promt. Not any command works.
![](https://cloud.githubusercontent.com/assets/4927589/13221503/dc8b30f6-d98c-11e5-8f39-f490b5f0a982.png)

**Comment by imurchie** [comment]
What is the command you're using in the second case above? I see in the programmatic example that the quotes are being escaped.

**Comment by TikhomirovSergey** [comment]
@imurchie 

![](https://cloud.githubusercontent.com/assets/4927589/13227471/e1e55480-d9a7-11e5-962f-7f96b6dd64a6.png)
Also I've tried: 
> node C:\Users\STikhomirov\AppData\Roaming\npm\node_modules\appium\build\lib\main.js { \"platformName\": \"Android\" }

> node C:\Users\STikhomirov\AppData\Roaming\npm\node_modules\appium\build\lib\main.js { "platformName": "Android" }

and some other variants.

**Comment by imurchie** [comment]
What happens with 

```
node C:\path_to\npm\node_modules\appium\build\lib\main.js '{ \"platformName\": \"Android\" }'
```

**Comment by scottdixon** [comment]
@TikhomirovSergey - I think you're missing the leading `--default-capabilities` flag

As in: ```node C:\path_to\npm\node_modules\appium\build\lib\main.js --default-capabilities "{ \"platformName\": \"Android\" }"```

**Comment by TikhomirovSergey** [comment]
@scottdixon 
Yeah. That works.

**Comment by abhirep** [comment]
I have tried installing  appium 1.5 released version on windows 7 , 8 and 10 , I am getting the following error

`
> appium-chromedriver@2.8.0 install C:\Users\achauhan\AppData\Roaming\npm\no
odules\appium\node_modules\appium-chromedriver
> node install-npm.js

Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
info Chromedriver Install Installing Chromedriver version '2.21' for platfor
in' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to..
info Chromedriver Install Downloading http://chromedriver.storage.googleapis
/2.21/chromedriver_win32.zip...
info Chromedriver Install Writing binary content to C:\Users\achauhan\AppDat
cal\Temp\201621-7524-1cn5kzj\chromedriver_win32.zip...
info Chromedriver Install Extracting C:\Users\achauhan\AppData\Local\Temp\20
-7524-1cn5kzj\chromedriver_win32.zip to C:\Users\achauhan\AppData\Local\Temp
621-7524-1cn5kzj\chromedriver_win32
info Chromedriver Install Creating C:\Users\achauhan\AppData\Roaming\npm\nod
dules\appium\node_modules\appium-chromedriver\chromedriver\win...
info Chromedriver Install Copying unzipped binary, reading from C:\Users\ach
n\AppData\Local\Temp\201621-7524-1cn5kzj\chromedriver_win32\chromedriver.exe
info Chromedriver Install Writing to C:\Users\achauhan\AppData\Roaming\npm\n
modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedrive
e...
info Chromedriver Install C:\Users\achauhan\AppData\Roaming\npm\node_modules
ium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe succe
lly put in place

> appium-selendroid-driver@1.2.2 install C:\Users\achauhan\AppData\Roaming\n
ode_modules\appium\node_modules\appium-selendroid-driver
> node ./bin/install.js

info SelendroidInstaller Ensuring C:\Users\achauhan\AppData\Roaming\npm\node
ules\appium\node_modules\appium-selendroid-installer\selendroid\download exi
info SelendroidInstaller Downloading Selendroid standalone server version 0.
 from https://github.com/selendroid/selendroid/releases/download/0.17.0/sele
id-standalone-0.17.0-with-dependencies.jar --> C:\Users\achauhan\AppData\Roa
\npm\node_modules\appium\node_modules\appium-selendroid-installer\selendroid
nload\selendroid-server.jar
info SelendroidInstaller Writing binary content to C:\Users\achauhan\AppData
ming\npm\node_modules\appium\node_modules\appium-selendroid-installer\selend
\download\selendroid-server.jar
info SelendroidInstaller Selendroid standalone server downloaded
info SelendroidInstaller Determining AndroidManifest location
Error: Command 'jar tf C:\\Users\\achauhan\\AppData\\Roaming\\npm\\node_modu
\appium\\node_modules\\appium-selendroid-installer\\selendroid\\download\\se
roid-server.jar' errored out: Error: spawn jar ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at ChildProcess.<anonymous> (lib/teen_process.js:31:14)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
npm ERR! Windows_NT 6.3.9600
**npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\node
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE**

npm ERR! appium-selendroid-driver@1.2.2 install: `node ./bin/install.js`
npm ERR! Exit status 1
npm ERR!
**npm ERR! Failed at the appium-selendroid-driver@1.2.2 install script 'node .
/install.js'.
npm ERR! This is most likely a problem with the appium-selendroid-driver pac
,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls appium-selendroid-driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:**
npm ERR!     C:\Users\achauhan\npm-debug.log`

I have attached the debug file also, Can someone help me out on this
[npm-debug.txt](https://github.com/appium/appium/files/152577/npm-debug.txt)

**Comment by abhirep** [comment]
I fixed this . Here is what I did

    I cleared the npm cache
    Used npm install appium -f to force install appium in my AppData/Node_modules directory
    Set an environment variable pointing to ADB to PATH C:\Users\achauhan\node_modules.bin

**Comment by HopeCao** [comment]
@abhirep 

I hav encountered the same problem, How do you solve this problem？
