### ISSUE TITLE
Appium how to achieve precise rolling, have what good method to judge reaches the page end

### ISSUE THREAD

**Issue by smartest-water** [appium/appium#6136]
Appium how to achieve precise rolling, have what good method to judge reaches the page end,

I want to take the data on the mobile phone App use Appium climb, swipe the method like with different devices...Now it is very trouble. Judgment reaches the footer.

I now use the android emulator running (scroll to get the data), run in the long run, will throw an exception

D/dalvikvm( 7544): JIT code cache reset in 98 ms (1535968 bytes 1/0)
D/dalvikvm( 7544): GC_CONCURRENT freed 1946K, 10% free 20248K/22288K, paused 23ms+123ms, total 308ms
F/libc    ( 7544): Fatal signal 4 (SIGILL) at 0xaa4a01f8 (code=1), thread 7544 (ngdong.app.mall)

**Comment by scottdixon** [comment]
Can you please rephrase what you're trying to achieve and where you're getting stuck?
