### ISSUE TITLE
Unable to perform Drag and Drop action in Android using Appium - throws Did not drag successfully

### ISSUE THREAD

**Issue by vinothannamalai** [appium/appium#6137]
I am unable to perform drag and drop action using below code in Android Hybrid App using Appium.

Option 1 new TouchAction(driver).longPress(ele1).moveTo(ele2).release.perform();

option 2 new TouchAction(driver).longPress(ele1).moveTo(ele2, 252, 180).release.perform();

Option 3 new TouchAction(driver).longPress(ele1, 252, 152).moveTo(ele2, 252, 180).release.perform();

Appium version: 1.4.13 Android OS: 4.4.2 Error: Appium throws an error like it did not perform drag action successfully.

--- log appium server ---- info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"Did not drag successfully","status":13}

Note: I tried in both Horizontal and Vertical perspective but no luck.

Thanks,

vinoth

**Comment by imurchie** [comment]
Can you provide more of the Appium server log, as a [gist](https://gist.github.com/). Preferably the whole thing. If not, then at least the entire `perform` command, along with any system information (Appium version, operating system, node version, etc).
