### ISSUE TITLE
There is no way to test android 4.2 or lower version of multiple devices?

### ISSUE THREAD

**Issue by kgp700** [appium/appium#6139]
Hi.
I want to test native application on android 4.2 or lower of multiple devices
but all methods occurred error

Working normally when use appium mode but have problem on selendroid mode
Using on Windows7, I tested on appium version 1.4.16, 1.4.13, 1.3.7.2
Using java client

**Method1.** Without specify apk path(capabilities.setCapability("app") but specified "deviceName", "platformName" , osVersion, MobileCapabilityType.AUTOMATION_NAME,"Selendroid" , "appPackage", "appActivity", "udid"
=> If not specify app path, occurred this error - org.openqa.selenium.SessionNotCreatedException: A new session could not be created. (Original error: hasInternetPermissionFromManifest failed. Error: Command failed: ERROR: no dump file specified
) (WARNING: The server did not provide any stacktrace information)

My target app have Internet Permission

**Method2.** With specify apk path(capabilities.setCapability("app") , and specified "deviceName", "platformName" , osVersion, MobileCapabilityType.AUTOMATION_NAME,"Selendroid" , "appPackage", "appActivity", "udid", "appWaitActivity"

=> If specify apk path, **ONLY One device start test normally but another devices occured following error **

> info: [debug] executing cmd: C:\Users\username\AppData\Local\Android\sdk\build-tools\23.0.2\zipalign.exe -f 4 C:\Users\username\workspace\appium_multi_devices\src\example\applicationapk.apk C:\Users\username\AppData\Local\Temp\116115-7808-9h2i9y\appium.tmp
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: EPERM, rename 'C:\Users\username\workspace\appium_multi_devices\src\example\applicationapk.apk'
> info: [debug] Error: EPERM, rename 'C:\Users\username\workspace\appium_multi_devices\src\example\applicationapk.apk'

There is no way to test android 4.2 or lower version of multiple devices?
or it just bug?

**Comment by SrinivasanTarget** [comment]
Please check this out: https://github.com/saikrishna321/AppiumTestDistribution

**Comment by SrinivasanTarget** [comment]
@triager please close
