### ISSUE TITLE
no such element occurs mostly while running from Jenkins :: Very inconsistent behaviour

### ISSUE THREAD

**Issue by anilkishore9** [appium/appium#6143]
Hi,
Environment of testing
iOS 9.2
Iphone 5S
Iphone 6s.
Appium  1.4.13 
TestNG

Whenever I run some some test cases from development environment eclipse, the test case which ran successfully in first run may thrown No Such element found error in some of the runs.

So, If I execute same test cases for 10 times 
5 out of 10 times will be successful
3 out of 10  times with no such element found exception
1 out of 10 times time a instruments crash

When run the same test cases from Jenkins for 10 times  

2 out of 10 times will be successful
5 out of 10  times with no such element found exception
2 out of 10 times time a instruments crash

I was doubting on Jenkins. So it tired twice with multiple Jenkins machine and did a fresh install etc.  

Looks like it is problem with Appium now. Is it same with others?

I am trying to 130 Test cases in a row and planning to increase number exponential.

Suggest me if there are guidelines in terms of number of test cases or number of runs we need to limit to?

**Comment by imurchie** [comment]
Can you provide the log output from (a) a passing case and (b) a failing case? Both as [gists](https://gist.github.com/).

**Comment by anilkishore9** [comment]
Loggs are too big ... i have to collate and send it. Did any others reported similar issue? Or is there any best practices to follow while running from jenkins?

**Comment by SrinivasanTarget** [comment]
@anilkishore9 You can only post the logs where you notice the failure instead of entire logs.

**Comment by dpgraham** [comment]
I'm going to close this for now. If you provide Appium logs detailing the problems I'll re-open.
