### ISSUE TITLE
Appium test on iOS devices over wifi

### ISSUE THREAD

**Issue by pracs23** [appium/appium#6144]
Is there a way to connect iOS device through wifi to run Appium tests. Please provide the how to do it if someone has worked it out. I hear that this has been recently supported by Xcode and Appium.

**Comment by imurchie** [comment]
There is no official way. Please ask on the [discussion list](https://discuss.appium.io/) to see if anyone else has any ideas.

**Comment by Aswini-kumarPradhan** [comment]
. Have xcode 9.2 and latest iOS in your phone
. Open WebDriverAgent.xcodeproj 
. Connect your device using usb cable
. Goto devices and find your device
. Check on the checkbox : "Connect via network"
. Once done (*You'll see a globe icon in front of device), remove the usb
. Goto xcode and run the project on your device
. Once it runs successfully, start appium server and your tests can be run on real device on wifi
![screen shot 2018-01-02 at 12 45 19 pm](https://user-images.githubusercontent.com/15100999/34477001-e0128b38-efbb-11e7-8145-ba269f72b2a3.png)

**Comment by frank7023** [comment]
无效，提示Unknown device or simulator UDID:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
