### ISSUE TITLE
Screenshot PNG is invalid

### ISSUE THREAD

**Issue by peterept** [appium/appium#6145]
When I call save_screenshot (from ruby) I get the saved PNG.

I actually can view it in any Mac preview tool and finder.

And imagemagick can read its properties:

```
$ identify screenshot.png
PNG 1440x2560 1440x2560+0+0 8-bit sRGB 2.318MB 0.000u 0:00.000
```

But if you try and convert it with imagemagick it fails:

```
$ convert screenshot.png NULL:
convert: Extra compressed data `screenshot.png' à warning/png.c/MagickPNGWarningHandler/1777.
convert: Extra compression data `screenshot.png' à warning/png.c/MagickPNGWarningHandler/1777.
```

I initially found this trying to load the images with chunky_png to process diffs:

require 'chunky_png'
image = ChunkyPNG::Image.from_file("screenshot.png")

```
Zlib::DataError: incorrect data check
    from /Users/EE/.rvm/gems/ruby-2.1.5/gems/chunky_png-1.3.5/lib/chunky_png/chunk.rb:249:in `<<'
    from /Users/EE/.rvm/gems/ruby-2.1.5/gems/chunky_png-1.3.5/lib/chunky_png/chunk.rb:249:in `block in combine_chunks'
    from /Users/EE/.rvm/gems/ruby-2.1.5/gems/chunky_png-1.3.5/lib/chunky_png/chunk.rb:249:in `each'
    from /Users/EE/.rvm/gems/ruby-2.1.5/gems/chunky_png-1.3.5/lib/chunky_png/chunk.rb:249:in `combine_chunks'
    from /Users/EE/.rvm/gems/ruby-2.1.5/gems/chunky_png-1.3.5/lib/chunky_png/datastream.rb:148:in `imagedata'
    from /Users/EE/.rvm/gems/ruby-2.1.5/gems/chunky_png-1.3.5/lib/chunky_png/canvas/png_decoding.rb:88:in `from_datastream'
    from /Users/EE/.rvm/gems/ruby-2.1.5/gems/chunky_png-1.3.5/lib/chunky_png/image.rb:74:in `from_datastream'
    from /Users/EE/.rvm/gems/ruby-2.1.5/gems/chunky_png-1.3.5/lib/chunky_png/canvas/png_decoding.rb:53:in `from_file'
    from (irb):2
    from /Users/EE/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```

Is this a known issue? Is it with the Android UIAutomation library?

Any work-around to fix the screenshot images so they can be processed?

This is on Samsung Note 4 Android OS 4.4.4

**Comment by peterept** [comment]
Could it be related to extra fields:

https://commons.apache.org/proper/commons-compress/zip.html

> Prior to version 1.1 of this library trying to read an archive with extra fields that didn't follow the recommended structure for those fields would cause Compress to throw an exception. Starting with version 1.1 these extra fields will now be read as UnparseableExtraFieldData.

**Comment by peterept** [comment]
From some posts on StackOverflow it seems that Android since 4.4.4 is producing invalid PNG files:

http://stackoverflow.com/questions/27235305/android-png-bitmap-compression-not-working-properly-between-note-4-and-nexus-5

Hmm!! Very frustrating.

One work-around I found is to convert each screenshot with imagemagick (which reports the error but still converts it and saves it correctly). Then I can load it.

However, it's pretty clunky requiring imagemagick to be installed and to add that to the automation testing. 

Is there a better solution?

**Comment by scottdixon** [comment]
Interesting. I just tested ImageMagick 6.9.2-10 / Android 6.0 & 4.4.2 with success.

Have you experimented with other Android or IM versions? Which IM version are you currently using?

**Comment by peterept** [comment]
So imagemagick will fix the images (it should display the warnings). It's only other programs that can't load them. The bug is when the image data is all saved in one IDAT chunk (which it is on Android 4 and 5).

In my tests I now call imagemagick after each screenshot to repair the png using 

`system("convert \"#{path}\" \"#{path}\"")
`
