### ISSUE TITLE
Appium Opera Browser support for running tests on android mobile device

### ISSUE THREAD

**Issue by amitjaincoer191** [appium/appium#6147]
Did appium support opera browser if I try to launch it on similar grounds like I do for firefox,Chrome etc

AndroidDriver <WebElement> driver;
DesiredCapabilities cap = new DesiredCapabilities(); 
cap.setCapability(MobileCapabilityType.PLATFORM_VERSION,"5.1");
cap.setCapability(MobileCapabilityType.PLATFORM_NAME,"Android");
cap.setCapability(MobileCapabilityType.DEVICE_NAME,"AMXEN223");         cap.setCapability("androidDeviceSocket","com.opera.mini.native" + ".devtools");
cap.setCapability("chromedriverExecutable","C:/nodeModules/appium/build/operadriver/windows");
cap.setCapability(MobileCapabilityType.BROWSER_NAME,MobileBrowserType.CHROMIUM);
cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT,"-1");
driver =  new AndroidDriver <WebElement>(new URL("http://127.0.0.1:4725/wd/hub"),cap);

**Comment by amitjaincoer191** [comment]
Currently it gives method not implemented error if I try to use

driver.get(url);

I mean if I can pass in browser name something like this then it will help

cap.setCapability(MobileCapabilityType.BROWSER_NAME,MobileBrowserType.OPERA);

**Comment by amitjaincoer191** [comment]
Currently appium supports
MobileBrowserType.SAFARI
MobileBrowserType.Chrome
MobileBrowserType.Chromium

**Comment by imurchie** [comment]
Appium does not currently support Opera. Adding to feature requests.

**Comment by sriram-rangarajan** [comment]
Any update on this?

**Comment by jlipps** [comment]
At this point, the Appium core team is probably not going to prioritize Opera support. We're more than happy for anyone in the community to make a pull request, however, and we'll help walk someone through the process of getting it submitted.

**Comment by daveabes** [comment]
Good day, then what about this?

Does this not integrate into Appium?

https://github.com/operasoftware/operachromiumdriver

**Comment by daveabes** [comment]
I was able to make us of the [OperaChromiumDriver](https://github.com/operasoftware/operachromiumdriver) to automate tests on opera browser, however, opera mini did not work.

**Comment by neerajlad** [comment]
Hi All,

Does appium support Chromium and firefox?
This is my code: 

                          if (params.get("browserName_") == "safari") {
				cap = DesiredCapabilities.safari();
			} else if (params.get("browserName_") == "firefox") {
				cap = DesiredCapabilities.firefox();
			} else if (params.get("browserName_") == "chrome") {
				cap = DesiredCapabilities.chrome();

				ChromeOptions options = new ChromeOptions();
				// options.setExperimentalOption("prefs", prefs);
				options.addArguments("disable-notifications");
				cap.setCapability(ChromeOptions.CAPABILITY, options);
			} else {
				cap = DesiredCapabilities.safari();
			}
			if (!params.get("screenshotPath_").equalsIgnoreCase("")) {
				GlobalVariables.SCREENSHOT_PATH = params.get("screenshotPath_");
			}

			cap.setCapability(MobileCapabilityType.DEVICE_NAME, params.get("deviceName_"));
			cap.setCapability(MobileCapabilityType.PLATFORM_NAME, GlobalVariables.amPLATFORM);
			cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, params.get("platformVersion_"));
			cap.setCapability(MobileCapabilityType.BROWSER_NAME, params.get("browserName_"));
			cap.setCapability(CapabilityType.UNEXPECTED_ALERT_BEHAVIOUR, "UnexpectedAlertBehaviour.ACCEPT");

**Comment by mykola-mokhnach** [comment]
Closed as obsolete. Opera uses the same engine as chromium
