### ISSUE TITLE
Android: Unable to interact with element because of element location changes[element X and Y coordinates changing to -ve values]

### ISSUE THREAD

**Issue by sravanmedarapu** [appium/appium#6149]
As per the execution flow below are the actions performed(simplified for better understanding)
- Click on Sign In button[Native View]
- Click on Back Button in Sign In Page [Web View] which will navigate to previous page
- Click on Sign In button[Native View]

I am able to switch the contexts with out any issues. from native to web view and from web view to native view

**Issue:**
After navigating back to native view from web view. driver object unable to perform click actions on native view page.[initially able to interact before switching to web view]

**Observations and findings:**
**Initially** elements X and Y coordinates are having +ve values
**After navigating back** to same page from web view, elements X and Y coordinates are showing -ve values

Also tried to get the page source before and after navigating back found that bounds attribute value(coordinates) got updated to -ve values. 

googled results for the route cause:
http://stackoverflow.com/questions/25715522/negative-value-from-android-getlocationonscreen

**Comment by imurchie** [comment]
Can you provide the server logs as a [gist](https://gist.github.com/)?

**Comment by sravanmedarapu** [comment]
please refer https://gist.github.com/sravanmedarapu/47c7d9b7217e0261d72d

observation about bounds values for same element before and after navigating back :

bounds=**"[243,1278][837,1416]" **

bounds=**"[-837,1278][-243,1416]"**

**Comment by imurchie** [comment]
There is nothing in the logs to indicate that there is an error in automation. It feels to me like a timing issue, where you go back and find the element but the UI hasn't refreshed or something. Can you try waiting for a bit before finding the element and interacting with it?

**Comment by sravanmedarapu** [comment]
Hi Isaac,
Tried by giving ample amount of wait to time for page to load, for sure it is not a sync issue. Even when I tried by capturing the page properties with **UIAutomatorViewer** it is showing the **bound** values as **[0 , 0]** for all the elements in that page.

any work around or Appium/UIAutomator API for page refresh to solve issue?

**Comment by sravanmedarapu** [comment]
Any thoughts on this issue ?

**Comment by gamesguru** [comment]
could be a uiautomator bug.  is this android 6.0 by any chance? are the elements near the bottom of the screen?
