### ISSUE TITLE
Getting error as  Required platform doesn't exist (API level >= 17)

### ISSUE THREAD

**Issue by suneel020287** [appium/appium#6151]
In Appium , android settings selected automation name as "Selendroid":

When i try to run my script giving error as :

info: [debug] Error: Required platform doesn't exist (API level >= 17)

> ```
> at [object Object].ADB.compileManifest (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:306:15)
> at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\selendroid.js:444:16)
> at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:607:21
> at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:246:17
> at iterate (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:146:13)
> at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:157:25
> at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:248:21
> at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:612:34
> at [object Object].ADB.checkSdkBinaryPresent (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\lib\adb.js:116:5)
> at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\selendroid.js:442:30)
> at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:607:21
> at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:246:17
> at iterate (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:146:13)
> at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:157:25
> at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:248:21
> at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\async\lib\async.js:612:34
> at C:\Program Files (x86)\Appium\node_modules\appium\node_modules\mkdirp\index.js:48:26
> at FSReqWrap.oncomplete (fs.js:95:15)
> ```

I have api:22. Please help how to solve this error.

**Comment by imurchie** [comment]
Appium 1.4 does not look for API level 22. Download 21 in addition, and it ought to work.

The only directories it looks for are: 

```js
var locs = ['android-4.2', 'android-17', 'android-4.3', 'android-18',
      'android-4.4', 'android-19', 'android-L', 'android-20', 'android-5.0',
      'android-21'];
```
