### ISSUE TITLE
longPress, moveTo, release to drag respect longPress duration

### ISSUE THREAD

**Issue by ahansen1** [appium/appium#6154]
When submitting a longPress, moveTo, release action the android-controller.js converts it to a drag action.  In doing so, it sends a default duration of 1 or 2 seconds depending on the apiLevel.  Was having issues with the default duration not being long enough to pick up our item.  Would be nice to have the duration be set based on the duration of the longPress action if it is provided.

**Comment by ahansen1** [comment]
https://github.com/appium/appium/pull/6153

**Comment by imurchie** [comment]
Fixed by #6153
