### ISSUE TITLE
Unable to execute Isdisplayed() method

### ISSUE THREAD

**Issue by areebashuja** [appium/appium#6157]
Hi,
I am stuck at a very important part of my automation which i am unable to resolve.

I wanted to execute below code which indicates that:

//if modal is displayed
if(driver.findElement(By.xpath("//android.widget.FrameLayout[1]//android.widget.FrameLayout[1]//android.widget.FrameLayout[1]//android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]")).isDisplayed())
{
//click yes
driver.findElement(By.xpath("//android.widget.FrameLayout[1]//android.widget.FrameLayout[1]//android.widget.FrameLayout[1]//android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[1]")).click();
}
else
{
//else click back
driver.findElement(By.xpath("//android.view.View[1]/android.widget.LinearLayout[1]/android.view.View[1]/android.widget.ImageButton[1]")).click();	
}

The problem is that, Appium is not identifying/considering isDisplayed() method, stucks on "if" clause and starts searching for the modal and the time out occurs and it doesn't go to next step at all.

I have also tried to use below "size" method instead of "isDisplayed", but eclipse not accepting "size" method.
if(driver.findElement(By.xpath("//android.widget.FrameLayout[1]//android.widget.FrameLayout[1]//android.widget.FrameLayout[1]//android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]")).size()>0)

**Environment:**
* Appium version: 1.4.16 
* Eclipse version: eclipse_Kelper64 

Please suggest.
Thanks in advance

**Comment by rompic** [comment]
In case the Element does not exist (which is different than not being displayed), you could catch the Elementnotfound exception.

Like this pseudocode

public boolean iselementdisplayed(){
try{
return element.isdisplayed();}
Catch(Elementnotfound... E){
return false;}
}

---- areebashuja schrieb ----

**Comment by rompic** [comment]
For the size think you have to use findelements...

I strongly suggest you look into the annotations Feature of the java client

**Comment by areebashuja** [comment]
@rompic  both above mentioned suggestions of try catch and size is still not working

**Comment by rompic** [comment]
please post your code and the error you get

**Comment by areebashuja** [comment]
I have found the below solution with the help of my senior developer and now my whole scenario is working perfect. I thought i must have to share this here, so that anyone can take benefit from the following solution of above mentioned problem.

WebDriverWait driverWait = new WebDriverWait(driver, 3);
try {            
     if(driverWait.until(ExpectedConditions.visibilityOfElementLocated(By.id("btnOk"))) != null){
              driver.findElement(By.id("btnOk")).click();
     }
} 
catch(Exception e) {        	
     driver.findElement(By.id("btnCancel")).click();
} 

Thanks

**Comment by kcinman11358** [comment]
Looks like your dev beat me to it, but yes waiting is your bet. Sometimes, it can just be that half a second that could cause your test to fail. Something that we have implemented is having a wait.until for each time we are looking for an element. This is in c#, but it should translate

public IWebElement GetElement(By by)
        {
            WebDriverWait wait = new WebDriverWait(_driver, new TimeSpan(0, 0, 90));
            wait.Until(ExpectedConditions.ElementToBeClickable(by));
            return _driver.FindElement(by);
        }

**Comment by areebashuja** [comment]
Thank you @kcinman11358 for your reply, very thankful to you
