### ISSUE TITLE
Appium Win Log field issues

### ISSUE THREAD

**Issue by jbruchanov** [appium/appium#6160]
## The problem

Log window is not bottom scrolled as log grows
App  gets extremely slow when you reach some log length limit

## Environment

* Appium.exe version 1.4.16.1
* Win10

## Details

* Seems that every log TextField update calls something like scrollToBottom, but then something resets that scroll position so it's crazily jumping at then end is always topScrolled
* Fill the log textbox with a lot of text, the app is extremely slow

**Comment by scottdixon** [comment]
Please file this in the Appium [Windows GUI repo](https://github.com/appium/appium-dot-exe)
