### ISSUE TITLE
Can you update the documentation for appium installation? 

### ISSUE THREAD

**Issue by lakshmypriya** [appium/appium#6161]
## The problem

Can you update the documentation for appium installation?  I had multiple issues while trying to install the .dmg file .On googlingand talking to people I did find the solution to have it installed 

I do feel that saying "Download the Appium app.  Run it! " doesnt help anybody. Could you make elaborate a bit? 

Now the issues I had 

1/ the dmg file wouldnt show up .I would keep having unconfirmed.crdownload file

Solution:
Rename it to appium.dmg ->Double click on it .It would do the install and  move the .app to applications folder

or 
go to https://github.com/appium/appium.git -> git clone  https://github.com/appium/appium.git
-> go to bin folder ->run appium.js

I would think this much amount of required for anyone starting off .

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

**Comment by scottdixon** [comment]
Thanks for the report!

The .crdownload file sounds like a Chrome issue that occurs when downloads don't complete. This doesn't seem to be related to Appium and I'm not sure it makes sense to include it in the docs.

The `npm install -g appium` step could be much more prominent. I'll update the docs!

**Comment by scottdixon** [comment]
Closing. Let me know if you have any other suggestions.
