### ISSUE TITLE
An unknown server-side error occurred while processing the command.

### ISSUE THREAD

**Issue by samChen0** [appium/appium#6168]
## The problem
Hello, everyone, I was just learning appium, my question is: I execute the script after the preparation, pycharm prompted me to the following error:
Error Traceback (recent call last most):
File "/Users/mac/Downloads/Test_1.py", line 31, test_login in
Button=self.driver.find_element_by_class_name ("personal Center 1")
File "/Library/Python/2.7/site-packages/selenium-2.52.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 378, find_element_by_class_name in
Self.find_element return (by=By.CLASS_NAME, value=name)
File "/Library/Python/2.7/site-packages/selenium-2.52.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 712, find_element in
{'using': by,'value': value}) ['value']
File "/Library/Python/2.7/site-packages/selenium-2.52.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 201, execute in
Self.error_handler.check_response (response)
File "build/bdist.macosx-10.11-intel/egg/appium/webdriver/errorhandler.py", line 29, check_response in
Wde raise
WebDriverException: message: an unknown server-side error occurred while processing the. (Original: the class name selector must use full UIA class names. Try'UIA\u4e2a\u4eba\u4e2d\u5fc31'with instead.)

## Environment
Appium version : 1.4.13
OS X EI Capitan version : 10.11.3
using Appium
Mobile platform
Real device
Appium CLI

## Details
This is my code, hope to be able to get help! Thank you very much ~~~
#-*- coding:UTF-8 -*-
import os
import unittest
from appium import webdriver

class ComplexIOSTests(unittest.TestCase):

    def setUp(self):
        # set up appium
        # ** Important Note **
        # Make sure you have build the UICatalog applcation in your local repository
        app = os.path.join(os.path.dirname(__file__),
                           '../../Users/mac/Downloads',
                           'Playload.ipa')
        app = os.path.abspath(app)
        self.driver = webdriver.Remote(
            command_executor='http://127.0.0.1:4723/wd/hub',
            desired_capabilities={
                'app': app,
                'platformName': 'iOS',
                'platformVersion': '7.1.2',
                'deviceName': 'iPhone 4s',
                'bundleId': 'com.telecom',
                'udid': 'cd。。。。。。。。。。。。。。'
            })
        self._values = []

    def test_login(self):
        #点击个人中心
        print "click person center"
        button=self.driver.find_element_by_class_name("个人中心1")
        button.click()

        #点击输入框,输入电话号码
        print "import phone number"
        text1=self.driver.find_element_by_xpath("//UIAApplication[1]/UIAWindow[1]/UIATextField[1]")
        text1.click()
        text1.send_keys("123456789")

**Comment by imurchie** [comment]
Can you provide, in a [gist](https://gist.github.com/), the full Appium server logs?

**Comment by samChen0** [comment]
@imurchie Thank you for your attention, this problem has not appeared, because I modified the code without error, estimation is grammar problems.

**Comment by imurchie** [comment]
Ok! Thanks!
