### ISSUE TITLE
Reopening the application without clearing cache

### ISSUE THREAD

**Issue by KalveeduVijay** [appium/appium#6169]
Hello Everyone,

I am eager to understand if there is any solution to reopen application without clear cache after reaching home screen ?

**Scenario: **App getting crashed. With this done, it goes to home screen.

**Actual:
**It uninstall app from my mobile automatically.

**Expected:**
Reopen once when it is called.

Appium : 1.4.13
Xcode : 7.2
Java version : 8.0

**Comment by KalveeduVijay** [comment]
Any update on this ?

**Comment by scottdixon** [comment]
@KalveeduVijay - can you please clarify your goal? Are you saying you don't want the app reinstalled if it crashes?

**Comment by SrinivasanTarget** [comment]
@triager please close
