### ISSUE TITLE
UiObject.clearText() strange behavior for a specific field on Android Tablet

### ISSUE THREAD

**Issue by Fanch-** [appium/appium#6171]
## Environment 
- appium v1.4.16
- java-client 3.3.0
- real device : Android tablet (tried on Samsung Galaxy Note10 & Tab4 -10P-) -> 4.4.2 & 5.1.1 

## Issue 

I am experiencing a strange issue, I have a field (EditText) with a value already set and I want to read this value and send another one (sendKey).

It works fine when reading the value but it doesn't work on Tablet when I try to send another value.

To be more specific (on tablet where the bug is present), it deletes the first word using UiObject.clearText() but after appium can't get back the element the second time using -it seems- its own generated selector to check if the field is empty and if there is still an action to perform.
Though the layout is still the same (EditText, instance=2 or 3 for tablet).

So the steps for clearText() are : 
"Depot bien Immo part prolong" -> " bien Immo part prolong" -> blocked

Here the logs : 
**Tablet logs where it doesn't work : **
https://gist.github.com/Fanch-/a7055676c205c1b78095

**Smartphone logs where it works : **
https://gist.github.com/Fanch-/b9eb9bb7711ecce40dd0

From what I have read; on these Tablets the selector generated by appium is not able to locate the element after the first time (UiSelector[CLASS=android.widget.EditText, INSTANCE=3]).
In the scenario it works for previous similar fields (tablet too) though ...

Any ideas?

**Comment by scottdixon** [comment]
@Fanch- please try with the latest version of Appium `npm install -g appium`

Let me know if you're still experiencing an issue and I'll investigate further.

**Comment by Fanch-** [comment]
@scottdixon : I still have the problem with appium 1.5.1

```bash```
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding //*[@resource-id="fr.leboncoin.delivery:id/ad_validation_body"]/android.widget.EditText using XPATH with the contextId:  multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.EditText, INSTANCE=3]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"78"}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"78"}
[HTTP] <-- POST /wd/hub/session/01eac16b-d579-4d08-ba90-b76ee7411a73/element 200 160 ms - 88 
[HTTP] --> POST /wd/hub/session/01eac16b-d579-4d08-ba90-b76ee7411a73/element/78/value {"id":"78","value":["Modif prolong Ventes Immo"]}
[MJSONWP] Calling AppiumDriver.setValue() with args: [["Modif prolong Ventes Immo"],"78","01eac16b-d579-4d08-ba90-b76ee7411a73"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"78","text":"Modif prolong Ventes Immo","replace":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"78","text":"Modif prolong Ventes Immo","replace":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Attempting to clear using UiObject.clearText().
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":7,"value":"UiSelector[CLASS=android.widget.EditText, INSTANCE=3]"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[HTTP] <-- POST /wd/hub/session/01eac16b-d579-4d08-ba90-b76ee7411a73/element/78/value 500 26928 ms - 164 

```

Also, another comment :  we can't modify a previous full field using sendKeys with text selector -EditText-. Because it removes the first letter (to check if it's the placeholder maybe) then try to access to it again, and ofc it doesn't find the element because the text value has been changed. 

And in my case using the text value is needed because it's the only available information. I agree a content-desc value should be added in the app here.

With the java-client I tried clear() -on MobileElement- to do the **clear() + sendKeys('placeHolder')** but it didn't work so the workaround is to send the **delete keycode X.length() times then sendKeys('placeHolder')**

For example if I want to pass a field value (EditText) from 'badNumIdentif' to 'correctNumIdentif' : 
_Using: UiSelector[TEXT=badNumIdentif]_

_Attempting to clear using UiObject.clearText()_. -> first letter deleted

_[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result_ _{"status":7,"value":"UiSelector[TEXT=badNumIdentif]"}_
_[HTTP] <-- POST /wd/hub/session/de6a9ba0-92c1-4121-89a0-4d63c6262ae1/element/185/value_ _500 25218 ms - 164_

**Comment by Fanch-** [comment]
Ok it must come from the XPath selector, relating to https://github.com/appium/appium/issues/6359

Modyfing the selector, it worked.
