### ISSUE TITLE
When start driver many times, sometimes an unknown server-side error occurred with Appium 1.5.0-beta14

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#6174]
## The problem

`An unknown server-side error occurred while processing the command. Original error: Command 'osascript -e 'quit app "iOS Simulator"'' exited with code 1` happened many times when I run my test nightly.

This error is not happen with Appium 1.4.16. So, I share it.

(I only past logs with error log level. I will update logs with debug log level in the next running test time.)

```
[iOSSim] {"stdout":"","stderr":"0:24: execution error: osascript got an error: Application isn’t running. (-600)\n","code":1}
[iOSSim] {"stdout":"","stderr":"0:24: execution error: iOS Simulator got an error: Application isn’t running. (-600)\n","code":1}
[MJSONWP] Encountered internal error running command: Error: Command 'osascript -e 'quit app "iOS Simulator"'' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:56:19)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
[iOSSim] {"stdout":"","stderr":"0:24: execution error: iOS Simulator got an error: Application isn’t running. (-600)\n","code":1}
[MJSONWP] Encountered internal error running command: Error: Command 'osascript -e 'quit app "iOS Simulator"'' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:56:19)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
[Instruments] Error launching instruments: Instruments crashed on startup
```

## Environment

* Appium version (or git revision) that exhibits the issue:
    - 1.5.0-beta14
* Last Appium version that did not exhibit the issue (if applicable):
    - 1.4.16
* Desktop OS/version used to run Appium:
    - Mac OS X 10.10
* Node.js version (unless using Appium.app|exe):
    - v4.2.4
* Mobile platform/version under test:
    - iOS8.4 x iPhone 6s plus simulator
    - Xcode6.4
* Real device or emulator/simulator:
    - simulator
* Appium CLI or Appium.app|exe:
    - CLI
* Library (I add this section. How about to add item *what library do you use ?* on here ?)
    - ruby_lib 8.0.2

## Details

1. start driver with `Appium::Driver.new(caps).start_driver` which is provided by ruby_lib.
2. do some scenarios and finish them
3. start other scenarios again with `Appium::Driver.new(caps).start_driver`
4. do some scenarios and finish them ...

And loop step starting driver many times. Then, sometimes the error occurred.

My environment is same as previous issue. https://github.com/appium/appium/issues/5920#issuecomment-172215699
(the above issue is solved. Thanks so much !)

## Link to Appium logs

- Error log
    - https://gist.github.com/KazuCocoa/22a1a18d3f46b8c1486d

I will add additional logs with debug log level soon ...

**Comment by scottdixon** [comment]
Can you provide an example failing test script? Or the entire logs?

**Comment by imurchie** [comment]
Can you try this against the latest beta?

**Comment by KazuCocoa** [comment]
I will try with latest one by today.

**Comment by KazuCocoa** [comment]
I checked with Appium1.5.0-beta16. But this issue reproduced.

I get a debug log. https://gist.github.com/KazuCocoa/310765e53a2546f612e2
Especially, the error is around https://gist.github.com/KazuCocoa/310765e53a2546f612e2#file-logs_for_6174-log-L412 .

It looks `setLocale` error.

----

## env

my environment is similar to https://github.com/appium/appium/issues/5920#issuecomment-172215699 . So, if you try [the scenario](https://github.com/KazuCocoa/scenarioForAppiumIssue5920/blob/master/spec/test_spec.rb#L22) many time, then this error will occur.

- caps files are similar to https://github.com/KazuCocoa/scenarioForAppiumIssue5920/blob/master/spec/test_spec.rb.
    - But I use 
 ```
    language: "jp",
    locale: "ja_JP",
```

**Comment by imurchie** [comment]
I'm no longer certain what the issue is. 

Can you make sure that you have the ability to run AppleScripts? If you, for instance, `osascript -e 'quit app "iOS Simulator"'`, what happens? Is there any security dialog?

**Comment by KazuCocoa** [comment]
No, there are no security dialog. > Is there any security dialog?

I'm investigating several cases. don't use AppleScript, `set_location` and so on...
`set_location` failed on Android. So, I will try without set_location on iOS simulator, too.

I will update this issue if my investigation proceed.

- `set_location` is method which is provided by `ruby_lib`.

```
    def set_location(opts = {})
      latitude = opts.fetch(:latitude)
      longitude = opts.fetch(:longitude)
      altitude = opts.fetch(:altitude, 75)
      @driver.set_location(latitude, longitude, altitude)
    end
```

**Comment by KazuCocoa** [comment]
memos

- Appium 1.5.0 don't support setting language and locale on client side ? even described in https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md ?

```
> [BaseDriver] The following capabilities were provided, but are not recognized by appium: language, locale.
```

**Comment by imurchie** [comment]
No, this is a weird logging artifact that is slated to be fixed.

**Comment by KazuCocoa** [comment]
I checked my full scenarios with Appium 1.5.1.

But suddenly Appium failed to launch instruments.
The following are logs of warning level. `driver_start_with` is my own log which means try to call `Appium::Driver.new(caps).start_driver`via ruby_lib.

According to the log, Appium failed to re-launch instruments. So, I will update my scenario a bit and try again with debug or info of log level again. I will close this issue if don't happen unknown server side error which is this issue's main topic.

```
[iOS] Could not file localizable strings file 'Localizable.strings'!
[Instruments] Error launching instruments: Instruments crashed on startup
[driver_start_with]
[iOS] Could not file localizable strings file 'Localizable.strings'!
[driver_start_with]
[iOS] Could not file localizable strings file 'Localizable.strings'!
[driver_start_with]
[iOS] Could not file localizable strings file 'Localizable.strings'!
[driver_start_with]
[iOS] Could not file localizable strings file 'Localizable.strings'!
[driver_start_with]
[iOS] Could not file localizable strings file 'Localizable.strings'!
[driver_start_with]
[iOS] Could not file localizable strings file 'Localizable.strings'!
[driver_start_with]
[iOS] Could not file localizable strings file 'Localizable.strings'!
[driver_start_with]
[iOS] Could not file localizable strings file 'Localizable.strings'!
[Instruments] Instruments socket client never checked in; timing out (global)
[driver_start_with]
[driver_start_with]
[driver_start_with]
[driver_start_with]
```

**Comment by KazuCocoa** [comment]
I checked with Appium 1.5.2 again. I close this issue because my main topic of this issue was not happened. So, i close this issue in this time.

---

BTW, Appium 1.5.2 has...

- slow running test wit Xcode6.4 x (iOS8.x or iOS7.x) than Appium 1.4.x
    -  without-delay option doesn't work on Appium 1.5.2 ?
- missing Xcode command many times

```
[MJSONWP] Encountered internal error running command: Error: Condition unmet after 60081 ms. Timing out.
    at spin$ (lib/asyncbox.js:118:13)
    at tryCatch (/Users/xxx/Documents/github/my_test/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/xxx/Documents/github/my_test/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/xxx/Documents/github/my_test/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/xxx/Documents/github/my_test/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/xxx/Documents/github/my_test/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /Usersxxx/Documents/github/my_test/node_modules/appium/node_modules/asyncbox/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

**Comment by KazuCocoa** [comment]
I attached https://github.com/appium/appium/issues/6452 for `[MJSONWP] Encountered internal error running command: Error: Condition unmet after 60081 ms. Timing out.`
