### ISSUE TITLE
How to run Appium testcases in Redwood HQ

### ISSUE THREAD

**Issue by areebashuja** [appium/appium#6175]
I want to use Redwood HQ with Appium environment. I am unable to find out any simple and easy guide to setup run Appium test in Redwood HQ. Please help me out.
Thanks, in advance

**Comment by sunnytambi** [comment]
Hi @areebashuja , could you find a simple guide for integrating Appium with Redwood HQ?

**Comment by sunnytambi** [comment]
Finally, my team member has just submitted a complete working code of RedwoodHQ integration with Appium for mobile functional test automation.
We call it Wheat.

Here is the link .. https://github.com/Talentica/Wheat

**Comment by jlipps** [comment]
Thanks @sunnytambi! looks interesting
