### ISSUE TITLE
Appium 1.5 Beta 16 A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): browserName iOS is not included in the list.

### ISSUE THREAD

**Issue by SrinivasanTarget** [appium/appium#6177]
## The problem
Session Not created error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5 beta src
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: NA
* Node.js version (unless using Appium.app|exe): 5
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real devices (Two real devices)
* Appium CLI or Appium.app|exe: Beta src

## Details

When we try to run our test suite parallely on two devices on 1.5 beta src we are getting this error whereas same works fine on appium 1.4.16

## Link to Appium logs
https://gist.github.com/SrinivasanTarget/b67a1b9f5504fdb477bf

@imurchie  Please help on this.

**Comment by imurchie** [comment]
Looking into this. Strange.

**Comment by SrinivasanTarget** [comment]
Same testcases works fine on 1.4.16 on multiple iOS devices parallely

**Comment by imurchie** [comment]
The quick fix is to add `browserName: ''` to your desired capabilities.

**Comment by SrinivasanTarget** [comment]
ok let me check now

**Comment by imurchie** [comment]
Yes. We weren't catching this because our test harness always gives a blank (rather than non-existent) `browserName`. I'll look into how to fix this.

**Comment by SrinivasanTarget** [comment]
Yup it works with that quick fix.Now Appium parallel on Multiple iOS devices works with 1.5 as well.

**Comment by scottdixon** [comment]
This should have been resolved in https://github.com/appium/appium-ios-driver/pull/100

Please reopen if any issues.
