### ISSUE TITLE
Need a sample hybrid app for iOS to demo my client

### ISSUE THREAD

**Issue by know2script** [appium/appium#6178]
## The problem

Hi - Team could someone help me with a sample hybrid iOS app to show how appium automated to my customer. Like native we have UICatalog & For web we have SafariLauncher do we have any sample app for hybrid along with Xcode project so that I can deploy into my device and can automate it. Please help

**Comment by scottdixon** [comment]
Here's a basic UIWebView you could automate: http://www.makemegeek.com/uiwebview-example-ios/

(Scroll down for link to Xcode project files)

**Comment by email2vimalraj** [comment]
@know2script: I understand that you wanted to show the demo. Perhaps this forum is to discuss issues with appium. Going forward kindly use this forum: https://discuss.appium.io or use the appium chat: https://gitter.im/appium/appium# for requests like this.

I hope you understand.

**Comment by know2script** [comment]
@email2vimalraj  Thanks for your advise. People will ask for help only when they are helpless and couldn't find the proper direction. I got two valuable responses and Im currently exploring on them which I can help others in this regards.

Well, @email2vimalraj  It would be great if you would have provide a sample app details before posting your advise.
