### ISSUE TITLE
Swipe not working for particular selecting item from List in mobile app

### ISSUE THREAD

**Issue by Sruthi-M** [appium/appium#6181]
## The problem

swipe from right to left is not working in mobile app.
## Environment

* Appium version -1.4.16
* Desktop OS/version -ubuntu 14.04 LTS
* Node.js version v4.2.6
* Mobile platform: Android 5.1
* Real device 

## Details

I have list of items.In the list items selecting one item and swipe right to left.But the problem is swipe didn't worked.
Html code 
```
<img ng-class="getRightImage(item)" src="img/Power-Button-icon.png" class="offIcon">

<h2><strong class="ng-binding">aws8 - aws sdk test</strong> <ion-spinner ng-hide="!( item.state == 'stopping' || item.state == 'pending') " style="display:inline" class="spinner spinner-ios ng-hide"> </ion-spinner>  </h2>
</div>

<div class="item-options invisible"><ion-option-button class="button-royal icon ion-play button" ng-hide="!( item.state == 'stopped') " ng-click="startInstance(item)"></ion-option-button></div>
```

test case

```
List<WebElement> instances = driver.findElements(By.className("item-content"))

String instanceName=instances.get(3).getText();

 for (WebElement singleInstance : instances) {

String instanceh2Text = singleInstance.getText();

if(instanceh2Text.equals(instanceName)){

Point point = singleInstance.getLocation(); 

int xcord = point.getX(); 

int ycord = point.getY(); 

WebElement startButton=driver.findElement(By.className("button-royal"));

startButton.click();

}

}
```

I tried these ways
1.Dimension size = driver.manage().window().getSize(); 
            	int startx = (int) (size.width * 0.8); 
            	int endx = (int) (size.width * 0.20); 
            	int starty = size.height / 2; 
            	driver.swipe(startx, starty, endx, starty, 1000);
getting org.openqa.selenium.WebDriverException: unknown error: operation is unsupported on Android
2.JavascriptExecutor executor = (JavascriptExecutor)driver;
executor.executeScript("arguments[0].click();", startButton);
3. TouchAction action = new TouchAction(driver);
action.press(element).waitAction(300).moveTo(element1).release().perform();
int leftX = el.getLocation().getX();
int rightX = leftX + el.getSize().getWidth();
int upperY = el.getLocation().getY();
int lowerY = upperY - el.getSize().getHeight();
int middleY = (upperY - lowerY) / 2;
if (orientation.equals("portrait"))
{ driver.swipe(leftX + 5, middleY, rightX - 5, middleY, 500); }
else if (orientation.equals("landscape"))
{ driver.swipe(rightX - 5, middleY, leftX + 5, middleY, 500); }

but didn't work

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

**Comment by subhashreddyG** [comment]
int lowerY = upperY - el.getSize().getHeight();
middleY = (upperY - lowerY) / 2           will mislead to wrong location.
 
change it to:
int upperY = el.getLocation().getY();
int lowerY = upperY + el.getSize().getHeight();
int middleY = (upperY + lowerY) / 2;

it will work..

**Comment by fernandesbinu** [comment]
void swipe() {
			TouchAction action = new TouchAction(_driver);
			WebElement el = GetElementByXpath(_driver, xpath);
			WebElement el2 = GetElementByXpath(_driver, xpath);

	        int startY = el.getLocation().getY() + (el.getSize().getHeight() / 2);
	        int startX = el.getLocation().getX() + (el.getSize().getWidth() / 2);

	        int endX = el2.getLocation().getX() + (el2.getSize().getWidth() / 2);
	        int endY = el2.getLocation().getY() + (el2.getSize().getHeight() / 2);

	        action.press(startX, startY).waitAction(2000).moveTo(endX, endY).release().perform();
	        }

It should work, as it works for me to swipe from right to left just select 2 web elements from right and left give the xpath it should work.

**Comment by subhashreddyG** [comment]
use method      swipe(SwipeElementDirection direction,
         int duration) with help of mobileElement class

**Comment by scottdixon** [comment]
@Sruthi-M did any of the suggestions resolve the issue? If not, please provide server logs as a gist.

**Comment by SrinivasanTarget** [comment]
Fixed in https://github.com/appium/java-client/commit/5da85f818d9bfd04b8be7aa7e38ecbcccd72e16c

**Comment by SrinivasanTarget** [comment]
@triager please close
