### ISSUE TITLE
1.4.16 --no-reset seems to still be resetting for both Android and iOS.

### ISSUE THREAD

**Issue by shermanericSF** [appium/appium#6182]
Hey There,
I'm most likely doing something wrong, but just in case I'm not :).

Background:
Appium 1.4.16
Platforms: iOS 9.2 and Android Genymotion Simulators.
Mac OS X El Capitan
Not sure when this problem started happening.

Problem Descripttion
- I seem to have stumbled on the problem of not being able to run scenarios/tests back to back and stay signed in after my test.  It seems like my app is being reset according to my gist below.
- I'm double checking to make sure my settings are correct.
- Here's what I have (I script this out so variables are passed in):

```
Starting Appium Server:
 appium -a localhost -p $android_appium_port -bp $android_appium_bootstrap_port --no-reset


Desired Capabilities:
[caps]
platformName = "Android"
platformVersion = "4.4"
deviceName = "Galaxy S4"
appPackage = "com.x.y.z"
appActivity = "com.x.y.z.activity"
appWaitActivity = "com.x.y.z.activity1,com.x.y.z.activity2"
noReset = true
fullReset = false
app = "myapk.apk"

[appium_lib]
port = 4900
```

- I'm not doing any resets in any after hooks that I am aware of.
- I've also taken out of Desired Caps the noReset and fullReset leaving only the --no-reset in appium server startup. Also, the same result occurs.
- Here is my appium logs full gist of the test run. I tried this on 1.4.15 also with the same result: 
- https://gist.github.com/shermanericSF/0c89269d752f78ba1f94

Any help is most welcome.
Thanks in advance!

**Comment by SrinivasanTarget** [comment]
@shermanericSF  Have you tried in Appium 1.5 version?

**Comment by shermanericSF** [comment]
I haven't yet.  I can try shortly.  I'm also using appium_lib v8.0 and the latest Xcode 7

**Comment by scottdixon** [comment]
Any luck with 1.5 @shermanericSF ?

**Comment by shermanericSF** [comment]
no, sadly.  I've tried running 1.5 from appium source (master) and getting
the same result.
My appium.txt activities are like this.  Not sure if this needs to be
changed?  Possibly appium is restarting if it can't find the right activity?


appActivity = "com.blackboard.android.bbinstructorshared.activity.LaunchActivityInstructor"
appWaitActivity =
"com.blackboard.android.bbinstructorshared.login.activity.LoginActivityInstructor,
com.blackboard.android.bbinstructorshared.navigation.activity.NavigationActivityInstructor"



Appium is starting with the no-reset flag confirmed here:

info: Welcome to Appium v1.4.16 (REV
ae6877eff263066b26328d457bd285c0cc62430d)

info: Appium REST http interface listener started on localhost:4900

info: [debug] Non-default server args:
{"address":"localhost","port":4900,"bootstrapPort":4902,"noReset":true}

info: Console LogLevel: debug


Let me know what other information you may need.

Thanks!

**Comment by shermanericSF** [comment]
I was able to resolve this by removing any invalid activities in appWaitActivity

**Comment by scottdixon** [comment]
Thanks for the update, @shermanericSF
