### ISSUE TITLE
send keys to Datepicker not working in samsung galaxy tab

### ISSUE THREAD

**Issue by subhashreddyG** [appium/appium#6184]
send keys to Datepicker not working in samsung galaxy tab.
two keyboards(datepicker dialog keyboard & default keyboard) opening while executing sendkeys method.
it working fine mobile devices.opening only one keyboard
i tried with all possible ways
same code working fine with mobile devices

**Comment by subhashreddyG** [comment]
its working with help of  androidkeycode in that datepicker elements
elem.cliclk();
driver.pressKeyCode(AndroidKeyCode.KEYCODE_1);
driver.navigate().back();

**Comment by scottdixon** [comment]
Looks like you've resolved this. Please reopen if otherwise.
