### ISSUE TITLE
[v1.5.0-beta16] org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#6186]
## The problem

Not able to interact with element with name locator

## Environment

* Appium version (or git revision) that exhibits the issue:   v1.5.0-beta16
* Last Appium version that did not exhibit the issue (if applicable):   1.4.16
* Desktop OS/version used to run Appium:  Mac
* Node.js version (unless using Appium.app|exe):  v5.7.0
* Mobile platform/version under test: Android 5.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

To reproduce this issue try to run AndroidTest.java -> apiDemo()

## Link to Appium logs

[debug] [ADB] Running /Users/vikram-anna/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","000007CF003ACABB","shell","am","start","-n","io.appium.android.apis/.ApiDemos","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[Appium] New AndroidDriver session created successfully, session 8d727191-2c78-4127-960d-cff26a82be6c added to master session list
[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":tr...
[HTTP] <-- POST /wd/hub/session 200 22996 ms - 871 
[HTTP] --> POST /wd/hub/session/8d727191-2c78-4127-960d-cff26a82be6c/element 
[MJSONWP] Calling AppiumDriver.findElement() with args: ["name","Animation","8d727191-2c78-4127-960d-cff26a82be6c"]
[HTTP] <-- POST /wd/hub/session/8d727191-2c78-4127-960d-cff26a82be6c/element 500 6 ms - 144 
[HTTP] --> DELETE /wd/hub/session/8d727191-2c78-4127-960d-cff26a82be6c 
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["8d727191-2c78-4127-960d-cff26a82be6c"]
[debug] [AndroidDriver] Shutting down Android driver

**Comment by SrinivasanTarget** [comment]
Name locator strategy is deprecated instead use //*[@name="Animation"]

**Comment by vikramvi** [comment]
@SrinivasanTarget can you please link me to document stating which all locators are applicable with 1.5 , I can write some more test cases to check all of them and submit PR.

**Comment by vikramvi** [comment]
https://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/By.html , aren't we supporting all the locator strategies and why some of them are deprecated ?

**Comment by SrinivasanTarget** [comment]
Nope we are not supporting all the locator strategies still use can use name locator strategy within xpath. Not sure about the exact reason why it is deprecated.

**Comment by imurchie** [comment]
The `name` locator strategy was deprecated long ago, and removed in Appium 1.5. The reason is largely because it was not clear what it was querying, and was necessarily handled differently in Android and iOS. 

The recommended way to search for the same information is by accessibility id.

**Comment by vikramvi** [comment]
@imurchie thanks for clarification. I've filed new issue for improvement in error message https://github.com/appium/appium/issues/6192

**Comment by SrinivasanTarget** [comment]
@vikramvi Error messages are improved and is available in java_client 3.4.0(yet to be released).Please hold for few days for that release if you are using java_client.

**Comment by vikramvi** [comment]
Nice thanks for info @SrinivasanTarget

**Comment by qa-bob-csaa** [comment]
Thanks All this is helpful.  Any idea if the id locator is better to use in place of name.  I am not a fan of css Selecor and xpath.

**Comment by ruchikar** [comment]
am not using 'name' locator still am getting, Locator Strategy 'name' is not supported for this session... error message, any clue wats wrong?

**Comment by mgmanikandan87** [comment]
@rubarb yes recent appium update from 1.5 "name" locator got deprecated "Remove long-deprecated name locator strategy"
This link will help you : https://www.youtube.com/watch?v=bT3tqaLNn-Y

**Comment by ohadschn** [comment]
For anyone encountering this using the `wd` node.js webdriver client, here's a simple workaround based on SrinivasanTarget's suggestion:

```js
var elementByNameUsingXPath = function (name) {
    return self.driver.elementByXPath(util.format('//*[@name="%s"]', name));
}
wd.addPromiseChainMethod('elementByName', elementByNameUsingXPath);
```

Note that in Android 7, it seems like `text=` should sometimes be used instead of `name=` (just check the source XML).

**Comment by prat3ik** [comment]
You can use `//*[@text="Animation"]` as XPath locator

**Comment by vicky18782** [comment]
@SrinivasanTarget  you mentioned of using this "//*[@name="Animation"]" can you give an example like which method to use instead of find element by name

also I have lot of my code referring to find element by name as we have a localized app .

help would be appriciated

**Comment by benoyjose** [comment]
I am trying to scrap out all mobile elements available in a session to my java application. Is it possible without passing any search parameters to fetch.

**Comment by imurchie** [comment]
@benoyjose No, but you can get the source and parse it for all the elements.

**Comment by benoyjose** [comment]
@imurchie thanks I was able to fetch all elements that way. @SrinivasanTaarget it would be far more easier and helpful if we can fetch all elements as list or map by wildcard rather than search and fetch.
