### ISSUE TITLE
startCapture can not find the adb path with this.adb.path.

### ISSUE THREAD

**Issue by nitibu** [appium/appium#6189]
## The problem

When i open application, appium server run into Logcat.prototype.startCapture, like below:
```
Logcat.prototype.startCapture = function (cb) {
  this.onLogcatStart = cb;
  logger.debug("Starting logcat capture");
  logger.debug(this.adb.path);
  logger.debug(this.adb.defaultArgs[0]);
  logger.debug(this.adb.defaultArgs[1]);
  this.proc = spawn('adb', ['devices']);
  this.proc.stdout.on('data', function(data){
    console.log('standard output:\n' + data);
  });
  // this.proc = spawn(this.adb.path, this.adb.defaultArgs.concat(['logcat']));
  this.proc = spawn('/home/dqa/local/android-sdk-linux/platform-tools/adb', [this.adb.defaultArgs[0], this.adb.defaultArgs[1], 'logcat']);
  this.proc.stdout.setEncoding('utf8');
  this.proc.stderr.setEncoding('utf8');
```

1.this.proc = spawn(this.adb.path, this.adb.defaultArgs.concat(['logcat']));
Run this command, it would tell me :+1: 
[31merror[39m: Logcat capture failed: spawn "/home/dqa/local/android-sdk-linux/platform-tools/adb" ENOENT
23.88  [36minfo[39m: [debug] Stopping logcat capture
23.89  standard output:

2.this.proc = spawn('/home/dqa/local/android-sdk-linux/platform-tools/adb', [this.adb.defaultArgs[0], this.adb.defaultArgs[1], 'logcat']);

I do not know why? Is there any differeces between the two conmands? 
## Environment
- Appium version (or git revision) that exhibits the issue: 1.4.16
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: ubuntu 15.10
- Node.js version (unless using Appium.app|exe): v5.2.0
- Mobile platform/version under test:
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe:

**Comment by scottdixon** [comment]
Can you please include a gist of your entire log?

Is ADB actually available here `/home/dqa/local/android-sdk-linux/platform-tools/adb` ?
