### ISSUE TITLE
Unfortunately app has stopped - Error is seen when trying to launch app with Appium on android

### ISSUE THREAD

**Issue by LokeshGangaiah** [appium/appium#6190]
## The problem

Trying to Launch the App(selendroid-test-app) on my android device, using eclipse and appium server.
When i run my .java file, it installes an .apk file and try's launch but getting an crash kind of an message "unfortunately app has stopped".
## Environment
- Appium version 1.4.16.1 (Ophiuchus)
- Windows 7 64 bit
- Eclipse 5.1 Mars.1 Release
- *Android SDK Installed / Samsung S5 5.0OS
- Real device
- Appium CLI or Appium.app|exe:
## Details

Below is my .java code also the AndroidManifest.xml and the Console output in my eclipse
Along with the appium log(noting much is seen in this log)
I feel someting wrong in the AndroidManifest.xml

Also i am doubting is my Run Configuration correct for Android Application

Also everytime i create a project it rather creates an file in my device with android icon,i doubt why its creating those rather than actually launching my app?
And also when i tap on that icon,it gives the same Unfortunately app has stopped 
# Looking forward to your help

package ello;

import io.appium.java_client.android.AndroidDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class apptest {
    public static AndroidDriver driver;
    @BeforeClass
    public void setUP() throws MalformedURLException {
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("browserName", "");
        capabilities.setCapability("device", "Android");
        capabilities.setCapability("deviceName", "Lokesh Gangaiah");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("platformVersion", "5.0");
        capabilities.setCapability("app_name", "selendroid-test-app");
        capabilities.setCapability("appPackage", "io.selendroid.testapp");
        capabilities.setCapability("appActivity", "io.selendroid.testapp.HomeScreenActivity");
        driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    }

```
@Test
public void Sel_Button_Test() throws InterruptedException {
```

  System.out.println("Test Started");
  WebElement ButtonElement =   driver.findElementById("io.selendroid.testapp:id/buttonStartWebview");
        ButtonElement.click();
 Thread.sleep(3000L);
  System.out.println("Test has been completed");
  }

 @AfterClass
    public void tearDown()
    {
        driver.quit();
    }
# }
# AndroidManifext.xml

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.ello"
    android:versionCode="1"
    android:versionName="1.0" >

```
<uses-sdk
    android:minSdkVersion="8"
    android:targetSdkVersion="21" />

<application
    android:allowBackup="true"
    android:icon="@drawable/ic_launcher"
    android:label="@string/app_name"
    android:theme="@style/AppTheme" >


 <activity
        android:name=".apptest"
        android:label="@string/app_name" >

     <intent-filter>
        <action android:name="android.intent.action.MAIN" />

            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        </activity>
 </application>
```

</manifest>
# 

Android Console output:
[2016-02-25 16:27:27 - ello] Android Launch!
[2016-02-25 16:27:27 - ello] adb is running normally.
[2016-02-25 16:27:27 - ello] Performing com.example.ello.apptest activity launch
[2016-02-25 16:27:29 - ello] Uploading ello.apk onto device '00bd9781'
[2016-02-25 16:27:29 - ello] Installing ello.apk...
[2016-02-25 16:27:37 - ello] Success!
[2016-02-25 16:27:37 - ello] Starting activity com.example.ello.apptest on device 00bd9781
[2016-02-25 16:27:38 - ello] ActivityManager: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.example.ello/.apptest }
# 

Appium logs:

> Checking if an update is available
> Update not available
> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --platform-name Android --platform-version 21 --automation-name Selendroid --log-no-color
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"21","automationName":"Selendroid"}
> # info: Console LogLevel: debug
> ## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

**Comment by scottdixon** [comment]
Can you please try with the latest Appium 1.5 `npm install -g appium`

**Comment by LokeshGangaiah** [comment]
Thanks for the reply.

Got this error below when used npm install -g appium:
installed few things then got the below error: was unable to install appium 1.5
===
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! appium-selendroid-driver@1.2.2 install: `node ./bin/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-selendroid-driver@1.2.2 install script 'node ./bin
/install.js'.
npm ERR! This is most likely a problem with the appium-selendroid-driver package
,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls appium-selendroid-driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\GangaiahL\npm-debug.log

**Comment by LokeshGangaiah** [comment]
Hi, can any one help me on this pls, i am still stuck up with the above problem.

**Comment by dekelev** [comment]
@LokeshGangaiah  Yes. I had this issue too when tried to install Appium 1.5.2 on Windows 8.1.

Just add the JDK 'bin' directory to the PATH environment variable.

My issue was that NPM tries to run an installation script that uses the 'jar' command and fails.
