### ISSUE TITLE
[improvement - v1.5.0-beta16]  Better error message for name locator strategy missing support

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#6192]
## The problem

Refer to https://github.com/appium/appium/issues/6186

## Environment

Appium version (or git revision) that exhibits the issue: v1.5.0-beta16
Last Appium version that did not exhibit the issue (if applicable): 1.4.16
Desktop OS/version used to run Appium: Mac
Node.js version (unless using Appium.app|exe): v5.7.0
Mobile platform/version under test: Android 5.0
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: CLI

## Details

Current error message is 

"Locator Strategy 'name' is not supported for this session" 

'name' locator strategy no more valid , please use some other strategy.

This will avoid users creating invalid tickets here

## Link to Appium logs

NA

**Comment by scottdixon** [comment]
Locator strategy 'name' was deprecated in earlier versions of Appium and has been removed in 1.5.

More info: http://appium.io/slate/en/1.5/?ruby#new-locator-strategies

**Comment by imurchie** [comment]
I'm open to an improvement along these lines. The correct place for it would be [here](https://github.com/appium/appium-base-driver/blob/01f6a54a36c7e18055627cd1c449e98fc192c0ab/lib/driver.js#L192-L202).

**Comment by scottdixon** [comment]
Closing this issue. Feel free to submit improvements via a PR.

**Comment by mgmanikandan87** [comment]
@vikramvi, appium 1.5 "name" locator got deprecated "Remove long-deprecated name locator strategy"
This link will help you : https://www.youtube.com/watch?v=bT3tqaLNn-Y
