### ISSUE TITLE
The script keeps waiting before taking a screenshot.

### ISSUE THREAD

**Issue by Mitalig** [appium/appium#6193]
I am running my script on sauce labs for following configuration:
PlatformName: Android
PlatformVersion:5.1
DeviceName: Android 5.1 Emulator
BrowserName: Chrome
AppiumVersion: 1.4.7

Follwing is the code for screenshot:
    File scrFile = ((TakesScreenshot) ActionKeywords.driver).getScreenshotAs(OutputType.FILE);
                    int stepno=(MobileApplicationTest.iTestStep)+1;  
FileUtils.copyFile(scrFile, new File(VerifyingExcel.screenShotsPath+"//"+MobileApplicationTest.sTestCaseID+"//"+stepno+".jpg"));

Following are the appium logs:
[Appiumlog.txt](https://github.com/appium/appium/files/147720/Appiumlog.txt)

Following are logcat logs:
[logcat logs.txt](https://github.com/appium/appium/files/147721/logcat.logs.txt)

Could you please give a brief of what's wrong?

**Comment by Mitalig** [comment]
Any update on the above issue?

**Comment by SrinivasanTarget** [comment]
Can you try in Appium 1.5 and update us back?

**Comment by scottdixon** [comment]
@Mitalig any luck with 1.5?

**Comment by Mitalig** [comment]
@scottdixon @SrinivasanTarget I tried running my script with appium version 1.5.0 on sauce labs but still facing same issue.

Any other way to resolve this issue?

**Comment by scottdixon** [comment]
I see you're targeting #search1 - could you be looking for #search? (looking jabong.com source): `<input type="text" id="search" class="form-control"...`

If you script attempting to take a screenshot on failure? Are you able to share your test script?
