### ISSUE TITLE
Appium cannot handle Quantity strings (plurals) in Android 

### ISSUE THREAD

**Issue by lnnp1910** [appium/appium#6201]
How does appium handle Quantity strings in Android?

http://developer.android.com/guide/topics/resources/string-resource.html#Plurals

Is there a way to get a specific value of this string?

```
<resources>
    <plurals name="numberOfSongsAvailable">
        <item quantity="one">Znaleziono %d piosenkę.</item>
        <item quantity="few">Znaleziono %d piosenki.</item>
        <item quantity="other">Znaleziono %d piosenek.</item>
    </plurals>
</resources>
```

I assume we would need 2 parameters in this case, one is for the string id and another one for the quantity value = one, few or other...

Has this feature been supported yet? I'm using appium python client at this moment and receives NoneType any time calling this type of strings. 

Please help!!

**Comment by imurchie** [comment]
This has not been supported yet. Adding to feature requests to be implemented.

**Comment by mykola-mokhnach** [comment]
This issue is addressed by https://github.com/appium/appium-adb/pull/304. If any string id with multiple plural forms found then all these forms are packed into the value of type array (while "regular" values are simple strings) in the resulting dictionary.
