### ISSUE TITLE
Unable to run cucumber against Android device

### ISSUE THREAD

**Issue by JESii** [appium/appium#6203]
## Problem

I'm trying to run a test against an Android device that I have connected to my system. I have appium-server running (tried both from CLI and GUI); adb reports that my device is connected and authorized. The failure mode is different, depending on whether I am running against the GUI server or the CLI server.

## Environment

* Appium 1.4.16
* (No previous version)
* Mac OSX 10.11.13
* Node v5.7.0
* Android v4.4 on Samsun Galaxy S5
* Real device

## Running against the GUI server
When I am running the job against the GUI server, cucumber reports this error:

`spawn "/usr/local/bin/adb" ENOENT (Selenium::WebDriver::Error::WebDriverError)`

The last few lines from the GUI log are:

```
info: [debug] executing cmd: "/usr/local/bin/adb" devices

info: [debug] 1 device(s) connected
info: Found device 67a66618
info: [debug] Setting device id to 67a66618
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
info: [debug] executing cmd: "/usr/local/bin/adb" -s 67a66618 wait-for-device

info: [debug] executing cmd: "/usr/local/bin/adb" -s 67a66618 shell "echo 'ready'"

error: Logcat capture failed: spawn "/usr/local/bin/adb" ENOENT

info: [debug] Starting logcat capture
info: [debug] Cleaning up appium session
info: [debug] Error: spawn "/usr/local/bin/adb" ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickDomainCallback (node.js:381:11)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: spawn \"/usr/local/bin/adb\" ENOENT)","code":"ENOENT","errno":"ENOENT","syscall":"spawn \"/usr/local/bin/adb\"","path":"\"/usr/local/bin/adb\"","origValue":"spawn \"/usr/local/bin/adb\" ENOENT"},"sessionId":null}
info: <-- POST /wd/hub/session 500 124.396 ms - 298 

error: Failed to start an Appium session, err was: Error: spawn "/usr/local/bin/adb" ENOENT
```

Complete GUI server log is at https://gist.github.com/JESii/dbae594a050953eb96a7#file-appium_gui_log

Notice that the first adb command (for devices) worked just fine; it was the adb ... shell command that failed. That command `"/usr/local/bin/adb" -s 67a66618 shell` works just fine from the command line.

## Running against the CLI server
When I am running the job against the CLI server, I get this error:

`Could not proxy command to remote server. Original error: 404 - unknown command: wd/hub/status (Selenium::WebDriver::Error::WebDriverError)`

The last few lines from the CLI log are:

```
error: Failed to start an Appium session, err was: Error: Could not proxy command to remote server. Original error: 404 - unknown command: wd/hub/status
info: [debug] Error: Could not proxy command to remote server. Original error: 404 - unknown command: wd/hub/status
    at JWProxy.proxy$ (lib/proxy.js:109:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at bound (domain.js:287:14)
    at GeneratorFunctionPrototype.runBound (domain.js:300:12)
    at run (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/appium-chromedriver/node_modules/appium-jsonwp-proxy/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:17:13)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickDomainCallback (node.js:423:13)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not proxy command to remote server. Original error: 404 - unknown command: wd/hub/status)","origValue":"Could not proxy command to remote server. Original error: 404 - unknown command: wd/hub/status"},"sessionId":null}

```

Complete CLI log is at https://gist.github.com/JESii/6de3bb6989889eeb73cf#file-appium_cli_log.

Here are some environment details; I installed the Android SDK via homebrew - MacOSx El Capitan.

```
QAA$ adb devices -l
List of devices attached
67a66618               device usb:337641472X product:kltevzw model:SM_G900V device:kltevzw

QAA$ $ANDROID_HOME
-bash: /usr/local/opt/android-sdk: is a directory

QAA$ whence adb
/usr/local/bin/adb

QAA$ appium --udid 67a66618
info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
info: Appium REST http interface listener started on 0.0.0.0:4723
info: [debug] Non-default server args: {"udid":"67a66618"}
info: Console LogLevel: debug

QAA$ ls $ANDROID_HOME
/usr/local/opt/android-sdk@

QAA$ ls $ANDROID_HOME/
INSTALL_RECEIPT.json  add-ons@              build-tools@          extras@               platforms@            sources@              temp@
README                bin/                  etc/                  platform-tools/       samples@              system-images@        tools/
```

**Comment by SrinivasanTarget** [comment]
@JESii Can you try this in our Appium 1.5 v and update us?

**Comment by JESii** [comment]
OK; will do.

**Comment by JESii** [comment]
Where can I find the latest build -- I only found source on the Releases page? The downloads page doesn't have the 1.5 app.

**Comment by JESii** [comment]
OK; Appium 1.5.0; running on the CLI server get error:
`An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: 404 - unknown command: wd/hub/status (Selenium::WebDriver::Error::UnknownError)`. Log is attached.
[appium_cli.log.txt](https://github.com/appium/appium/files/151403/appium_cli.log.txt)

**Comment by imurchie** [comment]
Can you make sure that nothing is running on port `9515`? ChromeDriver is crashing.

I will look into the error messages when this happens.

**Comment by JESii** [comment]
I rebooted my machine and I see that chromedriver/port 9515 is running - loaded with launchctl.
I'll stop that and retry my test...

**Comment by JESii** [comment]
Reran the test with chromedriver stopped; got same result. I saw that the Android phone opened the browser 3 times with a "data" URL but never went beyond that. When I run this straight on Chrome, it runs fine.

**Comment by imurchie** [comment]
Are the logs the same? That is, getting a `[SEVERE]: bind() returned an error, errno=48: Address already in use` error from Chromedriver?

**Comment by JESii** [comment]
No; different error message:
```
2016-02-29 19:05:59:188 - info: [JSONWP Proxy] Got response with status 200: {"sessionId":"0ff8edd91298ca6d02e5828e115ec02b","status":13,"value":{"message":"unknown error: Chrome version must be >= 46.0.2490.0\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28...
2016-02-29 19:05:59:395 - error: [Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
2016-02-29 19:05:59:396 - info: [debug] [Chromedriver] Changed state to 'stopped'
```
[appium_cli.log2.txt](https://github.com/appium/appium/files/151587/appium_cli.log2.txt)

**Comment by imurchie** [comment]
Ok. This is a ChromeDriver error:

```
2016-02-29 19:05:59:188 - info: [JSONWP Proxy] Got response with status 200: {"sessionId":"0ff8edd91298ca6d02e5828e115ec02b","status":13,"value":{"message":"unknown error: Chrome version must be >= 46.0.2490.0\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28...
```

Essentially, ChromeDriver doesn't support the version of Chrome you are running.

Again, I'll look into how we log this to make it more expressive.

**Comment by JESii** [comment]
OK; thanks... I'll look into resolving that separately. 
I do wonder why I am able to use chromedriver in all my other tests... it only fails when I trying to use appium with an android device.

**Comment by imurchie** [comment]
Does ChromeDriver alone work with your Android device?

**Comment by JESii** [comment]
FYI: I'm on the latest versions: chromedriver 2.21.371459 and chrome 48.0.2564.116 (64-bit)

**Comment by JESii** [comment]
Not sure what you mean by "...ChromeDriver along with your Android device?"

**Comment by imurchie** [comment]
I'm just trying to clarify what you mean by it only failing when you try to use Appium with an Android device. Does this mean that if you just run ChromeDriver, without Appium, it can automate the same device? Or that it you can use ChromeDriver to automate a desktop Chrome instance?

**Comment by JESii** [comment]
I automate a desktop run with chrome & chromedriver

**Comment by imurchie** [comment]
What version of Chrome is on your Android device?

**Comment by JESii** [comment]
Ah... 3.0.1916. I'll see about upgrading that. I am able to run this device on a different machine.
Thanks.

**Comment by JESii** [comment]
I've been digging a little deeper and I see from the the ChromeDriver site []((https://sites.google.com/a/chromium.org/chromedriver/getting-started/getting-started---android)) that it looks like my version of Chrome (V38.0.2125.509) should be supported:

> "ChromeDriver supports running tests on Chrome browser (version 30+) "

Is there something else going on that I'm not aware of?

**Comment by JESii** [comment]
OK; I got it working.
1. I had exported ANDROID_HOME /usr/local/opt/android-sdk -- as defined in the  brew install.
2. The tests started working only after I updated the Appium GUI Android settings to explicitly set "Android | Advanced | Android SDK Path" to the same value.
This looks like an Appium bug to me?

**Comment by SrinivasanTarget** [comment]
@JESii It doesn't look like an appium bug to me. This always works fine if you have all the PATH variable is set properly and updated version of chrome and chromedriver. @imurchie Is there anything do we need to improve w.r.t logging?

**Comment by imurchie** [comment]
I'm no longer sure what the problem is. But it could be something in the GUI.

**Comment by SrinivasanTarget** [comment]
@triager please close
