### ISSUE TITLE
Mac run ./reset.sh error

### ISSUE THREAD

**Issue by kaku21** [appium/appium#6204]
## The problem

I use mac os setup appium environment,when I run ./reset.sh it give an error message

9 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/spiike21/appium/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
npm WARN install:utf-8-validate@1.1.0 utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.1.0 Exit status 1
npm WARN appium@1.4.0 No license field.
RESETTING GENERAL
* Setting git revision data
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'path-is-absolute'
Warning: Task "setGitRev" not found. Use --force to continue.

## Environment

* Appium version (or git revision) that exhibits the issue:
  git clone https://github.com/testerhome/appium.git
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
  OS X EI Capitan 10.11.1
* Node.js version (unless using Appium.app|exe):
  node -v: v5.7.0
  npm -v: 3.7.5
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

when i use $ node .   run appium it give error message:
$ node .
error: uncaughtException: Cannot find module 'path-is-absolute' date=Sun Feb 28 2016 14:32:27 GMT+0800 (CST), pid=4514, uid=501, gid=20, cwd=/Users/username/appium, execPath=/usr/local/bin/node, version=v5.7.0,....

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

**Comment by SrinivasanTarget** [comment]
@kaku21 Your repo is way behind our latest repo. Appium 1.5 is released couple of days back.Can you clone latest repo and follow the instructions on how to run appium from source in below link,

https://github.com/appium/appium/blob/master/docs/en/contributing-to-appium/appium-from-source.md

reset.sh is removed in latest repo. Try this one and update us.

**Comment by kaku21** [comment]
ok,i'll try it but i counter another question on windows environment.then i will submit a new issue

**Comment by SrinivasanTarget** [comment]
@kaku21 Can you please close this if it works for you?

**Comment by scottdixon** [comment]
@kaku21 please reopen if you have any issues with 1.5 install.
