### ISSUE TITLE
Default-capabilities flag 'fullReset' not working on iOS real devices on 1.5.0

### ISSUE THREAD

**Issue by HlebHalkouski** [appium/appium#6206]
## The problem
Default-capabilities flag 'fullReset' not working on iOS real devices. On Android devices works fine.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.5.0
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: OS X El Capitan ( 10.11.3)
* Node.js version (unless using Appium.app|exe): 5.7.0
* Mobile platform/version under test: iOS 9.2
* Real device or emulator/simulator: real device

## Details
Start appium server with command: 
`appium --port "4748" --session-override --default-capabilities '{"fullReset":true, "udid":"%deviceUdid%"}'`
Application wasn't reinstall, just restart.

## Link to Appium logs
https://gist.github.com/HlebHalkouski/8d5f592154c952b452ca

**Comment by SrinivasanTarget** [comment]
@HlebHalkouski fullReset is only for simulators please check this out,
https://github.com/appium/appium/blob/1.5/docs/en/writing-running-appium/caps.md

**Comment by HlebHalkouski** [comment]
@SrinivasanTarget ok, but it's works on 1.4.16 version.

**Comment by MEZISH** [comment]
It seems that I am getting the same problem:
Java implementation of AppiumDriver does not clean native application cache when the app is being fully reset by method "driver().resetApp()", implemented as "execute(MobileCommand.RESET);".
In previous 1.4.16 Appium version this worked as expected. Right now after re-install the user is still logged in the application.

Environment:
    Appium version 1.5.0
    Last Appium version that did not exhibit the issue (if applicable): 1.4.16
    Desktop OS/version used to run Appium: OSX
    Node.js version (unless using Appium.app|exe): 4.1.2
    Mobile platform/version under test: iOS 8.4
    Real device or emulator/simulator: real device iPhone 5
    Appium CLI or Appium.app|exe: Appium CLI

**Comment by rokly** [comment]
As well driver.removeApp("BundleID") doesn't work on appium 1.5. So there is no chance for me to bring my app into default state with appium 1.5.

**Comment by imurchie** [comment]
@HlebHalkouski I see the problem. It is with our logic around handling `ipa` files.

**Comment by HlebHalkouski** [comment]
Still not working on appium@1.15.1

**Comment by imurchie** [comment]
Can you provide the logs for 1.5.1?

**Comment by HlebHalkouski** [comment]
@imurchie Sure: [appium@1.15.1 logs](https://gist.github.com/HlebHalkouski/63bb619f29f8f4757f3718098499f633)

I think problem in [driver.js](https://github.com/appium/appium-ios-driver/blob/master/lib/driver.js#L341-L342). `this.installIpa()` wasn't perform.

**Comment by HlebHalkouski** [comment]
@imurchie In [driver.js](https://github.com/appium/appium-ios-driver/blob/master/lib/driver.js#L208-L213)
change `let ext = this.opts.app.substring(this.opts.app.length - 4).toLowerCase();` to `let ext = this.opts.app.substring(this.opts.app.length - 3).toLowerCase();`

**Comment by HlebHalkouski** [comment]
appium@1.5.2 - work correct. Thanks you!
