### ISSUE TITLE
Android native Browser failed with 'chrome not reachable' error message (Appium 1.5)

### ISSUE THREAD

**Issue by ivasylchenko** [appium/appium#6207]
## Environment
- Appium version 1.5 (source code d1d1c56d7fd1d66a3de8822393258f3bf2658bd4):
- Desktop OS/version used to run Appium: Linux x64 (Ubuntu)
- Node.js version: v0.12.10
- Mobile platform/version under test: Android 4.4.2
- Real device: LG G2
## Details

`DesiredCapabilities capabilities = new DesiredCapabilities();
  capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
  capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "4.4.2");
  capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "G2");
  capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Browser");`

Browser is opened and Google page is loaded then stuck with no actions, closed and opened again couple times.
## Link to Appium logs

[Detailed log](https://gist.github.com/ivasylchenko/5953affc03099c485827)

**Comment by scottdixon** [comment]
Interesting. I was unable to repo on a 4.4.2 emulator or a 5.0.1 real device.

Do you hit the same issue if you specify 'Chrome' as the browserName?

**Comment by ivasylchenko** [comment]
If "Chrome" is specified, it works successfully, but fails with native browser - "Browser" value in browserName.

I've tried on other real devices and results were the same:
* LG G3 (5.0.1)
* HTC One X (4.3)

**Comment by khanhdodang** [comment]
I also got the same issue, please see my detail log below:
>[Appium] Welcome to Appium v1.5.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"browserName":"Browser","platformName":"Android","deviceName":"Galaxy GRAND Prime"},null,null,null]
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   browserName: 'Browser'
[Appium]   platformName: 'Android'
[Appium]   deviceName: 'Galaxy GRAND Prime'
[BaseDriver] Session created with session id: f8a88a04-0a77-44d8-95ad-8b00cba17aee
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_76-ea
[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.browser and com.android.browser.BrowserActivity
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/khanhdo/Softwares/android-sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 2 device(s) connected
[AndroidDriver] Using device: 7b70e0b7
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/khanhdo/Softwares/android-sdk/platform-tools/adb
[debug] [ADB] Setting device id to 7b70e0b7
[AndroidDriver] App file was not listed, instead we're going to run com.android.browser directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 2 device(s) connected
[debug] [ADB] Running /Users/khanhdo/Softwares/android-sdk/platform-tools/adb with args: ["-P",5037,"-s","7b70e0b7","shell","pm","list","packages","com.android.browser"]
[AndroidDriver] Starting Android session
[debug] [ADB] Running /Users/khanhdo/Softwares/android-sdk/platform-tools/adb with args: ["-P",5037,"-s","7b70e0b7","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 2 device(s) connected
[debug] [ADB] Running /Users/khanhdo/Softwares/android-sdk/platform-tools/adb with args: ["-P",5037,"-s","7b70e0b7","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Running /Users/khanhdo/Softwares/android-sdk/platform-tools/adb with args: ["-P",5037,"-s","7b70e0b7","install","/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/io.appium.settings/bin/settings_apk-debug.apk"]
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Running /Users/khanhdo/Softwares/android-sdk/platform-tools/adb with args: ["-P",5037,"-s","7b70e0b7","install","/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 2 device(s) connected
[debug] [ADB] Running /Users/khanhdo/Softwares/android-sdk/platform-tools/adb with args: ["-P",5037,"-s","7b70e0b7","shell","getprop","ro.build.version.release"]
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running /Users/khanhdo/Softwares/android-sdk/platform-tools/adb with args: ["-P",5037,"-s","7b70e0b7","forward","tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running /Users/khanhdo/Softwares/android-sdk/platform-tools/adb with args: ["-P",5037,"-s","7b70e0b7","push","/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar","/data/local/tmp/"]
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 2 device(s) connected
[debug] [ADB] Running /Users/khanhdo/Softwares/android-sdk/platform-tools/adb with args: ["-P",5037,"-s","7b70e0b7","shell","ps","uiautomator"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: -P, 5037, -s, 7b70e0b7, shell, uiautomator, runtest, AppiumBootstrap.jar, -c, io.appium.android.bootstrap.Bootstrap, -e, pkg, com.android.browser, -e, disableAndroidWatchers, false, -e, acceptSslCerts, false
[debug] [UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[AndroidDriver] Starting a chrome-based browser session
[debug] [Chromedriver] Changed state to 'starting'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[Chromedriver] Set chromedriver binary as: /Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
[Chromedriver] Killing any old chromedrivers, running: ps -ef | grep /Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15
[Chromedriver] Successfully cleaned up old chromedrivers
[Chromedriver] Spawning chromedriver with: /Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515 --adb-port=5037
[Chromedriver] [STDOUT] Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 9515
Only local connections are allowed.
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Mac OS X\",\"version\":\"10.11.2\"}}}"
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"7b70e0b7"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"a2e01cdc383789d61d99a154d9b179fe","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=M...
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"7b70e0b7"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"33d3f251eb782c69e9973ef933df388d","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=M...
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"7b70e0b7"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"83d38d8820e0e91ff0b57b6adc2df418","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=M...
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.browser","androidActivity":"com.android.browser.BrowserActivity","androidDeviceSerial":"7b70e0b7"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"39626d75b2067053bc96f13065039003","status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=M...
[Chromedriver] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver] Changed state to 'stopped'
[Chromedriver] Error: An error occurred (Original error: chrome not reachable
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.2 x86_64))
    at JWProxy.command$ (lib/proxy.js:139:15)
    at tryCatch (/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
 { [Error: An error occurred (Original error: chrome not reachable
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.2 x86_64))]
  status: 100,
  value: { message: 'chrome not reachable\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.2 x86_64)' },
  httpCode: 200 }
[debug] [AndroidDriver] Shutting down Android driver
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/khanhdo/Softwares/android-sdk/platform-tools/adb with args: ["-P",5037,"-s","7b70e0b7","shell","input","keyevent",3]
[debug] [Logcat] Stopping logcat capture
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":"OK, shutting down","status":0}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Time: 296.047
[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/khanhdo/Softwares/android-sdk/platform-tools/adb with args: ["-P",5037,"-s","7b70e0b7","shell","ps","uiautomator"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Moving to state 'stopped'
[MJSONWP] Encountered internal error running command: Error: An error occurred (Original error: chrome not reachable
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.2 x86_64))
    at JWProxy.command$ (lib/proxy.js:139:15)
    at tryCatch (/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Users/khanhdo/Desktop/appium15/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
[HTTP] <-- POST /wd/hub/session 500 302412 ms - 312
[HTTP] --> DELETE /wd/hub/session
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- DELETE /wd/hub/session 404 8 ms - 57

**Comment by khanhdodang** [comment]
I also got the same issue, please see my log for more details
https://gist.github.com/khanhdodang/4b38c5fff221d7e62ccb#file-details-log

**Comment by profforg7** [comment]
I have the same problem on appium 1.5.3 (source code 068c4e5d0a7683956fb03c8ba81026106f016da7)
testing device is lg g3.
Who have launched tests on Android Native browser? Any ideas how to resolve this issue?

**Comment by SrinivasanTarget** [comment]
@imurchie Is this still valid? Shall we close this.
