### ISSUE TITLE
iOS getGeoLocation not implemented

### ISSUE THREAD

**Issue by Jonahss** [appium/appium#6208]
## The problem

using wd.js `driver.getGeoLocation()` is unimplemented.

## Environment

* Appium version 1.5.0
* Desktop OS/version used to run Appium: OSX 10.11
* Node.js version (unless using Appium.app|exe): 5.7.0
* Mobile platform/version under test: iOS 9.2 using Xcode 7.2.1
* Real device or emulator/simulator: sim
* Appium CLI

## Details

Maybe we don't support this on purpose? In that case, this issue can be closed, and the omission is thusly documented.

## Link to Appium logs

https://gist.github.com/Jonahss/bb36ce8f3fe4c78c5662

**Comment by imurchie** [comment]
I don't think this is an issue. Appium has no way of getting the geolocation from the device at the moment.
