### ISSUE TITLE
npm install appium on windows not support driver.findElement(By.name("Add Contact")); 

### ISSUE THREAD

**Issue by kaku21** [appium/appium#6209]
## The problem

the same code driver.findElement(By.name("Add Contact")); can run on the Appium.exe which setup through AppiumForWindows_1_4_13_1 include appium-installer.exe and update.bat,
but can not run with the appium setup through npm install -g appium 
is there some different on version or there are some wrong with my config?? I confuse with it
when I use cmd startup appium only support driver.findElementbyid to locate element,why???

## Environment

* Appium version (or git revision) that exhibits the issue:1.5.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:windows 7 64bit
* Node.js version (unless using Appium.app|exe):v5.0.7
* Mobile platform/version under test:android 4.4.4 - API 19
* Real device or emulator/simulator:use genemotion simulator
* Appium CLI or Appium.app|exe:cmd startup appium ( c:\Users\user>appium )
[Appium] Welcome to Appium v1.5.0 
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

**Comment by CYsuncheng** [comment]
I had the same problem

**Comment by HlebHalkouski** [comment]
@CYsuncheng @kaku21 Check [this](https://github.com/appium/appium/issues/6192)

**Comment by scottdixon** [comment]
This has been removed in 1.5. More info: https://github.com/appium/appium/issues/6192

Reopen in you have any further queries.

**Comment by CYsuncheng** [comment]
@HlebHalkouski  @scottdixon thanks

**Comment by kaku21** [comment]
@scottdixon thx,now I understand why I encounter the question.

**Comment by kaku21** [comment]
@HlebHalkouski thx lot
