### ISSUE TITLE
[Windows - Appium 1.5.0] Initializing test session takes too long

### ISSUE THREAD

**Issue by nghiadhd** [appium/appium#6210]
## Environment
- Appium version (or git revision) that exhibits the issue: appium 1.5.0
- Last Appium version that did not exhibit the issue (if applicable): 1.4.16
- Desktop OS/version used to run Appium: Windows 8.1 64 bit
- Node.js version (unless using Appium.app|exe): 4.3.1
- Mobile platform/version under test: Android/5.0
- Real device or emulator/simulator: Samsung S5
## Details

Below is my test script to re-produce

``` javascript
var wd = require('wd')

describe('Test', function() {
  it('wait for very long', function(cb) {
    // The device plugged-in to computer
    var desiredCaps = {
      browserName: 'chrome',
      platformName: 'Android',
      platformVersion: '5.0',
      deviceName: 'Galaxy S5'
    }
    // Running Appium service
    var serverInfo = {
      host: '192.168.20.95',
      port: 4723
    }

    var driver = wd.promiseChainRemote(serverInfo)
    driver.on('http', function(meth, path) {
      console.log('>>> %s %s %s', (new Date()).toString(), meth, path)
    })
    driver.on('status', function(info) {
      console.log('>>> %s GOT RESPONSE', (new Date()).toString(), info)
    })

    driver.init(desiredCaps).then(function() {
      driver.quit().then(cb, cb)
    }, cb)
  })
})
```

My `package.json`

``` json
{
  "name": "TestScript",
  "version": "0.0.1",
  "scripts": {
    "test": "mocha --timeout 3600000 test.js"
  },
  "dependencies": {
    "wd": "^0.3.11",
    "mocha": "^2.4.4",
    "mochawesome": "^1.3.1"
  }
}
```

And this is output from the above test script

```
$ npm test

> TestScript@0.0.1 test /Users/user//test
> mocha --timeout 3600000 test.js

  Test
>>> Tue Mar 01 2016 16:31:50 GMT+0700 (ICT) POST /session
>>> Tue Mar 01 2016 16:33:11 GMT+0700 (ICT) GOT RESPONSE 
Driving the web on session: ff295e52-f9c3-4e9f-ad55-052270a89c64

>>> Tue Mar 01 2016 16:33:11 GMT+0700 (ICT) DELETE /session/:sessionID
>>> Tue Mar 01 2016 16:33:13 GMT+0700 (ICT) GOT RESPONSE
Ending your web drivage..

    ✓ wait for very long (83037ms)


  1 passing (19s)
```

From the above log messages, Appium takes 1 min 20 secs to proceed the `POST /session` request. However, this long processing time doesn't happen if
- Runs Appium 1.5.0 on MAC OS
- Runs Appium 1.4.16 on both Windows / MAC OS

Is the long processing time for `POST /session` is expected behaviour or known issue ? Because it causes my test scripts to be timeout

**Comment by scottdixon** [comment]
Interesting. Can you please provide the windows logs (1.4.16 & 1.5) as a [gist](http://gist.github.com).

**Comment by nghiadhd** [comment]
Windows logs

Appium 1.4.16: https://gist.github.com/nghiadhd/85e82c8e3973b78a7006
Appium 1.5.0: https://gist.github.com/nghiadhd/379e2eb7d74a5198c80e

**Comment by abhirep** [comment]
@nghiadhd  I am trying to install appium 1.5 but I am getting an error on windows 8. How did you install it?

**Comment by nghiadhd** [comment]
@abhirep Could you give me the log? I guess you have error with jar
My steps are:

- Download appium 1.5 from https://github.com/appium/appium/releases
- Set PATH =%PATH%;%JAVA_HOME%\bin;%ANDROID_HOME%\platform-tools
- Install Node: 4.3.1
- Install NPM: 3.7.2
- Go to appium and "npm install"

**Comment by abhirep** [comment]
@nghiadhd 

These are the logs



    appium-chromedriver@2.8.0 install C:\Users\achauhan\AppData\Roaming\npm\no
    odules\appium\node_modules\appium-chromedriver
    node install-npm.js

Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
info Chromedriver Install Installing Chromedriver version '2.21' for platfor
in' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to..
info Chromedriver Install Downloading http://chromedriver.storage.googleapis
/2.21/chromedriver_win32.zip...
info Chromedriver Install Writing binary content to C:\Users\achauhan\AppDat
cal\Temp\201621-7524-1cn5kzj\chromedriver_win32.zip...
info Chromedriver Install Extracting C:\Users\achauhan\AppData\Local\Temp\20
-7524-1cn5kzj\chromedriver_win32.zip to C:\Users\achauhan\AppData\Local\Temp
621-7524-1cn5kzj\chromedriver_win32
info Chromedriver Install Creating C:\Users\achauhan\AppData\Roaming\npm\nod
dules\appium\node_modules\appium-chromedriver\chromedriver\win...
info Chromedriver Install Copying unzipped binary, reading from C:\Users\ach
n\AppData\Local\Temp\201621-7524-1cn5kzj\chromedriver_win32\chromedriver.exe
info Chromedriver Install Writing to C:\Users\achauhan\AppData\Roaming\npm\n
modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedrive
e...
info Chromedriver Install C:\Users\achauhan\AppData\Roaming\npm\node_modules
ium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe succe
lly put in place

    appium-selendroid-driver@1.2.2 install C:\Users\achauhan\AppData\Roaming\n
    ode_modules\appium\node_modules\appium-selendroid-driver
    node ./bin/install.js

info SelendroidInstaller Ensuring C:\Users\achauhan\AppData\Roaming\npm\node
ules\appium\node_modules\appium-selendroid-installer\selendroid\download exi
info SelendroidInstaller Downloading Selendroid standalone server version 0.
from https://github.com/selendroid/selendroid/releases/download/0.17.0/sele
id-standalone-0.17.0-with-dependencies.jar --> C:\Users\achauhan\AppData\Roa
\npm\node_modules\appium\node_modules\appium-selendroid-installer\selendroid
nload\selendroid-server.jar
info SelendroidInstaller Writing binary content to C:\Users\achauhan\AppData
ming\npm\node_modules\appium\node_modules\appium-selendroid-installer\selend
\download\selendroid-server.jar
info SelendroidInstaller Selendroid standalone server downloaded
info SelendroidInstaller Determining AndroidManifest location
Error: Command 'jar tf C:\Users\achauhan\AppData\Roaming\npm\node_modu
\appium\node_modules\appium-selendroid-installer\selendroid\download\se
roid-server.jar' errored out: Error: spawn jar ENOENT
at exports._errnoException (util.js:870:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32
at onErrorNT (internal/child_process.js:344:16)
at nextTickCallbackWith2Args (node.js:441:9)
at process._tickCallback (node.js:355:17)
at ChildProcess. (lib/teen_process.js:31:14)
at emitOne (events.js:77:13)
at ChildProcess.emit (events.js:169:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12
at onErrorNT (internal/child_process.js:344:16)
at nextTickCallbackWith2Args (node.js:441:9)
at process._tickCallback (node.js:355:17)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\node
node_modules\npm\bin\npm-cli.js" "install" "-g" "appium"
npm ERR! node v4.2.6
npm ERR! npm v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! appium-selendroid-driver@1.2.2 install: node ./bin/install.js
npm ERR! Exit status 1
npm ERR!
**npm ERR! Failed at the appium-selendroid-driver@1.2.2 install script 'node .
/install.js'.
npm ERR! This is most likely a problem with the appium-selendroid-driver pac
,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node ./bin/install.js
npm ERR! You can get their info via:
npm ERR! npm owner ls appium-selendroid-driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:**
npm ERR! C:\Users\achauhan\npm-debug.log`

**Comment by nghiadhd** [comment]
@abhirep 

Root cause is 

Error: Command 'jar tf C:\Users\achauhan\AppData\Roaming\npm\node_modu
\appium\node_modules\appium-selendroid-installer\selendroid\download\se
roid-server.jar' errored out: Error: spawn jar ENOENT

Please check the file seleroid-server.jar is exist or not
If it's exist, please make sure the PATH (environemnt variable) is point to %JAVA_HOME%\bin
Then exit "cmd" and make sure "jar" command is ready

Good luck

**Comment by abhirep** [comment]
@nghiadhd  I fixed this . Here is what I did

1. I cleared the npm cache
2. Used npm install appium -f  to force install appium in my AppData/Node_modules directory
3. Set  an environment variable  pointing to ADB to PATH
C:\Users\achauhan\node_modules\.bin

Thanks for your feedback

**Comment by nghiadhd** [comment]
@scottdixon

Have you any idea about this issue? It makes my test script run failed (timeout)

**Comment by nghiadhd** [comment]
@scottdixon 

When I investigate the logs file, I see some hints.
The appium 1.5.0 takes so much time because it got "chrome not reachable" and need to retry

Appium 1.4.16

info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/h
	ub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage"
	:"com.android.chrome","androidDeviceSerial":"fcc59b88"}}}
	info: JSONWP Proxy: Got response with status 200: {"sessionId":"b49737492b3483a6
	67b1eabc14b867e6","status":0,"value":{"acceptSslCerts":true,"applicationCacheEna
	bled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},
	"cssSel...
	info: Chromedriver: Changed state to 'online'
	info: [debug] Overriding session id with "b49737492b3483a667b1eabc14b867e6"
	info: [debug] Device launched! Ready for commands
	info: [debug] Setting command timeout to the default of 60 secs
	info: [debug] Appium session started with sessionId b49737492b3483a667b1eabc14b8
	67e6
	info: <-- POST /wd/hub/session 303 65797.324 ms - 70

Appium 1.5.0

       [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/se
	ssion] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com
	.android.chrome","androidDeviceSerial":"fcc59b88"}}}
	[JSONWP Proxy] Got response with status 200: {"sessionId":"80a6141fc2bc1f08b0a65
	889e3ed0570","status":100,"value":{"message":"chrome not reachable\n  (Driver in
	fo: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform
	=W...
	[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/se
	ssion] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com
	.android.chrome","androidDeviceSerial":"fcc59b88"}}}
	[JSONWP Proxy] Got response with status 200: {"sessionId":"b11b707c84a77225c1f26
	e289800da04","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled"
	:false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chrome
	dr...
	[debug] [Chromedriver] Changed state to 'online'
	[Appium] New AndroidDriver session created successfully, session 6503b852-7008-4
	6f3-b10a-004752a7743a added to master session list
	[MJSONWP] Responding to client with driver.createSession() result: {"platform":"
	LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true
	,"databaseEnabled":false,"networkConnectionEnabled":tr...
	[HTTP] <-- POST /wd/hub/session 200 154067 ms - 472

**Comment by nghiadhd** [comment]
@scottdixon 

I tried to replace chromedriver 2.21 on Appium 1.5.0 by chromedriver 2.18
and the performance is increase so much

[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/se
ssion] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com
.android.chrome","androidDeviceSerial":"62c0dc7c"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"52c9c155bde2a16bd557b
38b34cd9fe9","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled"
:false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},"cssS
el...
[debug] [Chromedriver] Changed state to 'online'
[Appium] New AndroidDriver session created successfully, session 93a0ba4f-6b7e-4
ccc-b7d3-f9a800d3bea4 added to master session list
[MJSONWP] Responding to client with driver.createSession() result: {"platform":"
LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true
,"databaseEnabled":false,"networkConnectionEnabled":tr...
[HTTP] <-- POST /wd/hub/session 200 15181 ms - 476

**Comment by scottdixon** [comment]
thanks @nghiadhd - I'll take a look on a Windows machine

**Comment by rkavalap** [comment]
@nghiadhd  is this still an issue ?

**Comment by nghiadhd** [comment]
@rkavalap 
I didn't test on Windows machine long time, so I'll close this issue
