### ISSUE TITLE
appium respond with empty list for iOS syslog

### ISSUE THREAD

**Issue by segalr3** [appium/appium#6211]
## The problem

Trying to read logs (java-client):
LogEntries logEntries = driver.manage().logs().get("syslog");

logEntries are always empty.
I've tried to loop over driver.manage().logs().getAvailableLogTypes(), all of the types return empty list, some of them return an error, where only "syslog", "crashlog", "performance" are valid for iOS.

On the Android platform it seems to work fine (tested 5.1.1).

## Environment

* Appium version: 1.4.8
* Desktop OS/version used to run Appium: OSX
* Node.js version: v0.10.26
* Mobile platform/version under test: iOS (tested on 7,8,9 versions)
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

**Comment by scottdixon** [comment]
Can you please try with Appium 1.5 `npm install -g appium`

Let me know if you hit the same issue and I'll investigate further.

**Comment by segalr3** [comment]
i had to install libimobiledevice, so actually not a problem in appium

**Comment by patotskiy** [comment]
I have same issue for appium 1.5.3.
Issue reproduce not for all devices. I have about 20 devices, but half of them returns empty syslog.
