### ISSUE TITLE
Server flag --orientation not supported in Appium 1.5

### ISSUE THREAD

**Issue by chemanth** [appium/appium#6213]
## The problem

In the Appium 1.5 which is installed through `npm install -g appium` the server flag `--orientation` is not recognized. 

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.5
* Last Appium version that did not exhibit the issue (if applicable): Appium 1.4.16
* Desktop OS/version used to run Appium: MAC OS ELCAPITAN
* Node.js version (unless using Appium.app|exe): 5.4.1
* Mobile platform/version under test: iOS 9.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium installed through Node.

## Details

The Appium server flag `--orientation` is not supported in Appium 1.5

## Link to Appium logs

`The desiredCapabilities object was not valid for the following reason(s): orie                                                            ntation Landscape is not included in the list.`

**Comment by scottdixon** [comment]
Many Appium 1.5 server arguments have been deprecated in favor of the `–default-capabilities` flag.

Try this:
`--default-capabilities '{"orientation": "..."}'`

More info: http://appium.io/slate/en/master/?ruby#the---default-capabilities-flag

**Comment by chemanth** [comment]
Thanks Scott ! The `--default-capabilities "{\"--orientation\": \"Landscape\"}"` is working perfect.

**Comment by scottdixon** [comment]
Excellent!
