### ISSUE TITLE
Unable to start html5 video playback with tap action on a Real iOS Device

### ISSUE THREAD

**Issue by dannyfinks** [appium/appium#6217]
## Environment
- Appium version - 1.4.13
- Desktop OS/version - Mac OS X 10.11
- Mobile platform/version under test -Mobile Safari - iOS 9.2 - iPad
- Real device Issue
- Appium.app UI Environment
## Details

I am attempting to start playback on an html5 video player in iOS 9.2 with a Real iPad Device by using the tap action on the video tag. The actual tap action occurs so a log may not be very helpful. The problem is that the tap is not treated as a real gesture and this is likely due to the preventative measures that Apple has set to prevent video autostart on an iOS device. Is their any way to potentially bypass this with Appium for iOS? With Android Chrome we were able to avoid this particular issue with the "disable-gesture-requirement-for-media-playback" flag. 

I also do not face this issue on an iOS simulator. With the simulator I was able to set the nativeWebTap capability to true in order to get the tap action to work properly, but I was hoping we could potentially run tests on a real device as well as the simulator. Thanks in advance for any feedback.

**Comment by scottdixon** [comment]
Interesting. Have you experimented with other gestures like longpress or tried tapping a few times?

**Comment by dannyfinks** [comment]
sorry for getting back so late @scottdixon I have tried multiple such experiments. Here is the apple documentation where this is mentioned - https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html

I am assuming they have done a ton to ensure that gestures via javascript could not hack through their autoplay business rules. Unfortunately it does not seem that they provide any workaround the way the Chrome team has done that I mentioned above. From my research I have found that with a solution like Phonegap you can provide configuration options such as "MediaPlaybackRequiresUserAction = NO"

**Comment by dannyfinks** [comment]
@scottdixon I think this may be being worked on by @lukeis with https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/7763

**Comment by lukeis** [comment]
I'm most certainly not working on that :)

**Comment by dannyfinks** [comment]
apologies...I got a bit excited when I saw you label it :)

**Comment by jwang-net** [comment]
Experiencing a similar issue with an HTML5 video player on an iOS real device. I've tried tap, press, longpress, and all of my attempts either yield a video player error, or nothing at all. Similar to @dannyfinks, the TouchActions all register however. Was there ever a solution found for this?

**Comment by dannyfinks** [comment]
@jwang-net I have not tried with a real device in quite some time. I have been just running with a simulator. It is possible though now that Safari 10 allows autoplay on media when volume is muted that this may work.

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
