### ISSUE TITLE
Return correct element coordinates when changing device rotation

### ISSUE THREAD

**Issue by artkoshelev** [appium/appium#6219]
## The problem

When changing device orientation to landscape, appium returns coordinates in "old" coordinates system, so we need to convert them manually. It seems this should be handled in appium.

## Environment

* Appium version 1.4.13
* Tests run on real android devices and emulators

**Comment by SrinivasanTarget** [comment]
@artkoshelev Can you please try this in Appium 1.5 and update us?

**Comment by SrinivasanTarget** [comment]
@triager please close
