### ISSUE TITLE
iOS Simulator set_location sometimes does not propagate to App

### ISSUE THREAD

**Issue by apallin** [appium/appium#6222]
## The problem

I am seeing behavior with `set_location` for Appium's driver, specifically iOS, where the location is not getting propagated to our app.  This is mostly occurring on our runs in Saucelabs, but I have seen this happen locally as well.  The behavior is such that `set_location` goes off without a hitch, i.e. no error codes in the Appium logs, but when our app starts, the core location read is at 0,0.

## Environment

* Appium python-client version 0.20
* Appium version 1.4.16
* Node.js version v0.12.2
* Testing on iOS 9.1
* Simulator
* Appium CLI

## Details

This is mostly occurring on our Saucelabs runs but is leveraging the same commands that would happen locally.  The main issue at hand is we are entering a location in `set_location` for Appium and expecting that location to be set properly.  However, once the App starts, we are at 0,0 and the tests fail.

## Link to Appium logs

Link to gist:
https://gist.github.com/apallin/3eba6ce8a5410d82def3

**Comment by scottdixon** [comment]
Interesting. What happens if you wait a few seconds and try again?

**Comment by apallin** [comment]
I can try adding that logic in, but it looks like no matter how many times its set it seems to get wedged at 0,0.  Do you know if there is an easy way to return the location that it thinks its set at?  I haven't been able to find any information on that. 

I am concerned this is a race condition between when our app is reading CoreLocation and when Appium sets it.  Since we cant set the location until the app boots because of how AppiumDriver works, I am concerned that we aren't getting an updated location or something along those lines.

**Comment by apallin** [comment]
No change in behavior with another set_location.

**Comment by scottdixon** [comment]
Good to know. Let me investigate.

**Comment by amedvedjev** [comment]
it is valid even without appium according to our experience. setting in simulator location via Menu does not help sometimes.

what we did to workaround is write osascript first to disable location and then enter location again.

maybe this help to workaround appium problem. why not to introduce "disable location" ?

**Comment by scottdixon** [comment]
@apallin could I trouble you for a test + demo app exhibiting the issue?

**Comment by rompic** [comment]
+1

**Comment by apallin** [comment]
@scottdixon Sorry, I don't think I can release our app that is exhibiting this behavior but I am happy to do some kind of call/walkthrough with you all.  I have been working with Saucelabs extensively on this already.
Let me see if I can find a way to release something to you, but its not something I can easily do.

**Comment by scottdixon** [comment]
Understandable @apallin - Alternatively, are you able to produce a failing test scenario with https://github.com/mehmetg/WhereAmI?

@rompic - are you hitting the same issue / do you have a sample application you can provide?

**Comment by rompic** [comment]
I have the problem that Geolocation seems to be never propagated to the simulator :(
