### ISSUE TITLE
Unable to install appium 1.5 version on windows 7/ windows 8-Appium Chromedriver Installation issue

### ISSUE THREAD

**Issue by RashmiMurthy** [appium/appium#6225]
## Unable to install appium 1.5 version on windows 7/ windows 8

Unable to install appium higher versions( 1.4.1-1.5), facing Appium chromedriver installation issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.1 to 1.5
* Last Appium version that did not exhibit the issue (if applicable): 1.3.5
* Desktop OS/version used to run Appium: windows 7 , windows 8
* Node.js version (unless using Appium.app|exe): 3.6.0

## Link to Appium logs

Please find the below log,
C:\Users\JenkinServer\AppData\Roaming\npm\authorize-ios -> C:\Users\JenkinServer
\AppData\Roaming\npm\node_modules\appium\node_modules\.bin\authorize-ios
C:\Users\JenkinServer\AppData\Roaming\npm\appium -> C:\Users\JenkinServer\AppDat
a\Roaming\npm\node_modules\appium\build\lib\main.js

> appium-chromedriver@2.8.0 install C:\Users\JenkinServer\AppData\Roaming\npm\no
de_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.21' for platform 'w
in' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com
/2.21/chromedriver_win32.zip...
info Chromedriver Install Writing binary content to C:\Users\JENKIN~1\AppData\Lo
cal\Temp\201623-3824-1nfcyed\chromedriver_win32.zip...
info Chromedriver Install Extracting C:\Users\JENKIN~1\AppData\Local\Temp\201623
-3824-1nfcyed\chromedriver_win32.zip to C:\Users\JENKIN~1\AppData\Local\Temp\201
623-3824-1nfcyed\chromedriver_win32
Invalid or unsupported zip format. No END header found
C:\Users\JenkinServer\AppData\Roaming\npm
`-- (empty)

npm WARN optional Skipping failed optional dependency /appium/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.8
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.8.0 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-chromedriver@2.8.0 install script 'node install-np
m.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-chromedriver p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\JenkinServer\npm-debug.log
npm ERR! code 1

**Comment by scottdixon** [comment]
Looks like the ChromeDriver download isn't successful. Can you try again:
```
npm cache clean
npm install -g appium
```

**Comment by RashmiMurthy** [comment]
hi...

Tied suggested commands but same issue Appium-chromedriver download is not happening.
But i could install latest Appium version on windows 10 machine.Only On windows 7 -windows 8 installation is not happening.

Please help out.

Thanks..

**Comment by RashmiMurthy** [comment]
hi..

Had some download permission issue. Able to install now. So closing the issue

**Comment by HopeCao** [comment]
@RashmiMurthy 

Hi RashmiMurthy,

I hav encountered the same problem, How do you solve this problem？
