### ISSUE TITLE
Some elements are invisible on screenshot of iOS 9.2

### ISSUE THREAD

**Issue by joeySNV** [appium/appium#6229]
## The problem

When I take screenshot of simulator with Appium, some elements are missing.
[what I was expecting to get](https://cloud.githubusercontent.com/assets/4482813/13492982/73f1a122-e13b-11e5-8873-a96bd6b7169c.png)
[what I got](https://cloud.githubusercontent.com/assets/4482813/13492995/8d9dbfde-e13b-11e5-9043-a93d300b3aa7.jpg)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.0
* Last Appium version that did not exhibit the issue (if applicable): Not found. 1.4.16 has the same problem.
* Desktop OS/version used to run Appium: OS X Yosemite 10.10.5
* Node.js version (unless using Appium.app|exe): v5.0.0
* Mobile platform/version under test: iOS 9.2
* Real device or emulator/simulator: Simulator Version 9.2 (SimulatorApp-643 CoreSimulator-201.3), Xcode 7.2.1
* Appium CLI or Appium.app|exe: CLI

## Details

In app, I'm missing buttons, text fields etc. They are reachable by Appium, I can acces their properties, I can tap on them, but screenshot does not capture them.
It happens only on iOS 9.2, on iOS 8.4 it works fine.

[logs](https://gist.github.com/joeySNV/def689ac326865a5ef8e)

**Comment by HlebHalkouski** [comment]
@joeySNV its xcode bug. Check [this](https://github.com/lionheart/openradar-mirror/issues/6568)

**Comment by joeySNV** [comment]
Thank you for the info. I did not notice/find that. 
This is invalid issue then.
