### ISSUE TITLE
how to convert selendroidPort to systemPort for appium-selendroid-driver

### ISSUE THREAD

**Issue by xuanzhaopeng** [appium/appium#6231]
## The problem

The Selendroid session cannot be launched by defined port through argument --selendroid-port 6666

## Environment

Appium 1.5.0 (installed by npm)
Appium-selendroid-driver 1.2.2 

## Details

Appium-Selendroid-Driver driver.cs wait for the argument called 'systemPort',

but Appium pass selendroidPort as argument

Then Appium-Selendroid-Driver will use the first port from range [8200, 8299] , thus it will start from 8200 rather than the defined 6666

**Comment by imurchie** [comment]
Thanks! Looking into this.

**Comment by imurchie** [comment]
This should be fixed in `appium-selendroid-driver` 1.2.3
