### ISSUE TITLE
1.5.0. Android. Selendroid mode: The getContext() returns null

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/appium#6234]
## The problem

The _getContext()_ method returns the **null** value. 

## Environment

* Appium version 1.5.0
* Last Appium version that did not exhibit the issue 1.4.16:
* Desktop OS/version used to run Appium: I've checked it on Windows 8/10
* Node.js version: v4.2.6
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: no

## Link to Appium logs

[Get context](https://gist.github.com/TikhomirovSergey/3ae4a500dd4fe179bdf1)
[Get contexts](https://gist.github.com/TikhomirovSergey/5a5c10a850a3f688d902)

## Code To Reproduce Issue [ Good To Have ]

```java
        private static int SELENDROID_PORT = 9999;
        ....

        AppiumServiceBuilder builder = new AppiumServiceBuilder();
        service = builder.build();
        service.start();

        File appDir = new File("src/test/java/io/appium/java_client");
        File app = new File(appDir, "ApiDemos-debug.apk");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
        capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
        capabilities.setCapability(AndroidMobileCapabilityType.SELENDROID_PORT, SELENDROID_PORT);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.SELENDROID);
        WebDriver driver = new AndroidDriver<WebElement>(service.getUrl(), capabilities);

        ...
        driver.getContext(); //returns null value
        driver.getContextHandles(); //returns set which contains "NATIVE_APP"
        driver.getContext(); //returns null value  again !!!!
```

**Comment by imurchie** [comment]
I'm not sure why it did not do this before. But it's to spec to return null when it is in the default context.

https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md#webviews-and-other-contexts

**Comment by TikhomirovSergey** [comment]
@imurchie Is old server output needed?

**Comment by imurchie** [comment]
Will that change anything?

**Comment by TikhomirovSergey** [comment]
it was just a question. Don't worry

**Comment by imurchie** [comment]
Appium is in error, then. Selendroid is doing it correctly. Alas.

**Comment by adholaria** [comment]
Is this issue been fixed? I'm also having this problem. getContext() returns null instead NATIVE_APP .

**Comment by scottdixon** [comment]
@adholaria - please see https://github.com/appium/appium/issues/6234#issuecomment-191958769

**Comment by adholaria** [comment]
@scottdixon - are you saying it's by spec? 

https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md#webviews-and-other-contexts

**Comment by scottdixon** [comment]
Can you confirm/dismiss this @imurchie ? If I'm reading the spec correctly it says it should return `null` for no session. Are you saying Appium 1.5 _is_ in error, or 1.4 _was_ in error?

**Comment by TikhomirovSergey** [comment]
@scottdixon 
it in 1.4.x was working. Now (1.5.x) it returns **null  ** till user switches to NATIVE_APP forcefully.

```java
        private static int SELENDROID_PORT = 9999;
        ....

        AppiumServiceBuilder builder = new AppiumServiceBuilder();
        service = builder.build();
        service.start();

        File appDir = new File("src/test/java/io/appium/java_client");
        File app = new File(appDir, "ApiDemos-debug.apk");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
        capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
        capabilities.setCapability(AndroidMobileCapabilityType.SELENDROID_PORT, SELENDROID_PORT);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.SELENDROID);
        WebDriver driver = new AndroidDriver<WebElement>(service.getUrl(), capabilities);

        ...
        driver.getContext(); //returns null value
        driver.getContextHandles(); //returns set which contains "NATIVE_APP"
        driver.getContext(); //returns null value  again !!!!
```

Then 

```java
driver.context("NATIVE_APP");
 driver.getContext(); // returns "NATIVE_APP"
```

It always returns "NATIVE_APP" in Appium (automator) mode.

**Comment by scottdixon** [comment]
My apologies, I misinterpreted - looks like we need to fix this. Reopening.
