### ISSUE TITLE
[Appium 1.5] The device screen is turn-off (blank) while the test is running

### ISSUE THREAD

**Issue by nghiadhd** [appium/appium#6235]
## The problem

On the Appium 1.5.0, the screen is turn off while the test is running.
But in Appium 1.4.16, the screen is turn on when the test runs and turn off when the test finishes 

Is this a bug or a new feature of Appium 1.5.0. I didn't see it on changelog

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.0
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: MAC OS 10.11 & Windows 8.1
* Node.js version (unless using Appium.app|exe): 5.4.0
* Mobile platform/version under test: All real Android devices (I tested with Nexus 5, Galaxy S5, Galaxy Note 4)
* Real device or emulator/simulator: Real device

## Details

Plug device and run the test script with Appium
- On Appium 1.4.16: The device screen will be awaked and keep it turn on while the test running
- On Appium 1.5.0: The device screen is still off all time while the test is running

**Comment by scottdixon** [comment]
@nghiadhd - can you please provide a sample test script + appium server log?

Which API version are you testing?

**Comment by buunguyen** [comment]
I have the same issue. While the tests run fine, using `adb shell screencap -p` to take screenshot fails (did work with 1.4). Would love to know if this is an intended change or bug.

**Comment by scottdixon** [comment]
@buunguyen - I'll take a look, which API level?

**Comment by buunguyen** [comment]
@scottdixon I'm using a Galaxy S5 API level 21.

**Comment by nghiadhd** [comment]
@scottdixon 

- Test script: https://gist.github.com/nghiadhd/97c9635cc76eb79659ea
log:
- Appium 1.4.16: https://gist.github.com/nghiadhd/5963595ed0a1344f3c7f
- Appium 1.5.0: https://gist.github.com/nghiadhd/f85a138ad09c9c23871c

Device: Nexus 5 (6.0.1) API lel 23.

I see that Appium 1.4.16 has invoked unlock activity to awake the device but Appium 1.5.0 not yet

Please help me identify it is new feature on Appium 1.5.0 or just a bug

**Comment by nghiadhd** [comment]
@scottdixon 

- On Appium 1.4.16, It installs "unlock_apk-debug.apk" to device 

info: [debug] executing cmd: /Volumes/Data/Softwares/android-sdk-macosx/platform-tools/adb -s 034288fa308a4a62 install "/Volumes/Data/Projects/Appium/1.4.16/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"

and then launch it

info: [debug] executing cmd: /Volumes/Data/Softwares/android-sdk-macosx/platform-tools/adb -s 034288fa308a4a62 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.appium.unlock/.Unlock"

- On Appium 1.5.0, it just pushing debug_unlock.apk to device and do nothing

[debug] [ADB] Running /Volumes/Data/Softwares/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","034288fa308a4a62","install","/Volumes/Data/Projects/Appium/1.5/node_modules/appium/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]

I also write a snip code to manual launch the unlock.apk on Appium 1.5.0 and it works like charm

Does Appium 1.5.0 have the option to launch "unlock_apk-debug.apk" or not? or just a bug?

**Comment by buunguyen** [comment]
@nghiadhd +1 for the finding. The fact that unlock.apk is installed but not used does sound like a bug to me. Hope it will be fixed soon.

**Comment by scottdixon** [comment]
Thanks. Looking into it.

**Comment by buunguyen** [comment]
@scottdixon awesome, thank you!  Can you let us know when we can expect this fix to be released?

**Comment by scottdixon** [comment]
@buunguyen - You can build appium-android-driver from source to use it right away, alternatively a fresh Appium should be published this week.

**Comment by buunguyen** [comment]
Great, thanks for letting me know.
