### ISSUE TITLE
About launch activity

### ISSUE THREAD

**Issue by winkar** [appium/appium#6236]
## The problem

I've got an android app, whose launch activity start another activity immediately , thus appium cannot found the launch activity and report error. 

Normal app can be started by appium . 

## Environment

* Appium version: 1.5
* OSX 10.11:
* Node.js version:5.7.1
* Mobile platform/version under test: 4.4
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Cli

## Link to Appium logs

[gist](https://gist.github.com/winkar/88929e8536da17ecb9d5#file-gistfile1-txt)

## Code To Reproduce Issue [ Good To Have ]
```ruby
#!/usr/bin/env ruby
require 'appium_lib'

APP_PATH = './apk/wandoujia.apk'

desired_caps = {
    caps:  {
        platformName: 'Android',
        deviceName: 'Motorola Moto X',
        app: APP_PATH
    },
    appium_lib: {
        sauce_username: nil,
        sauce_access_key: nil
    }
}



driver = Appium::Driver.new(desired_caps).start_driver
```

**Comment by imurchie** [comment]
Have you tried the `appWaitPackage` and `appWaitActivity` desired capabilities?

https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md#android-only

**Comment by kasirga32** [comment]
You must set **com.wandoujia.jupiter.onboard.OnboardActivity** as app wait activity. In your manifest file, you have a activity which named HomeActivity is in launcher mode. So appium waits this activity to begin test.

**Comment by winkar** [comment]
Thanks you all.
