### ISSUE TITLE
unable to install appium 1.5.0. npm install fails

### ISSUE THREAD

**Issue by tabishjaved03** [appium/appium#6237]
## The problem

Tried
npm install -g appium

i am using Mac OS X
I already had appium version 1.4.13 installed.
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.4

npm logs are as below. 
https://gist.github.com/tabishjaved03/14d38c578b8a6b1f623f
<script src="https://gist.github.com/tabishjaved03/14d38c578b8a6b1f623f.js"></script>

**Comment by scottdixon** [comment]
Looks like connectivity issues. Can you try again?

```
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
```

**Comment by SrinivasanTarget** [comment]
@tabishjaved03 Any luck after that?

**Comment by tabishjaved03** [comment]
Yes. Worked on a better connection. Thnx

**Comment by SrinivasanTarget** [comment]
Thanks @tabishjaved03
