### ISSUE TITLE
[Appium 1.5] Instruments did not terminate after 5 seconds!

### ISSUE THREAD

**Issue by chemanth** [appium/appium#6238]
## The problem

In the cleanup section of our tests we are restarting the driver. It was working fine till Appium 1.4.16.
Also, in Appium 1.5, it is working as expected for some tests. But some tests are randomly failing with the below error in Cleanup.
`[Appium] Had trouble ending session 0f23effd-5281-4bd9-87a5-07a8d399e51c: Instruments did not terminate after 5 seconds!`
`[MJSONWP] Encountered internal error running command: Error: Instruments did not terminate after 5 seconds!`

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.5
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: Mac ELCAPITAN
* Node.js version (unless using Appium.app|exe): 5.4.1
* Mobile platform/version under test: iOS 9.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Randomly tests are failing with below error when we are restarting the simulator by quitting the driver and re-instantiating it.

## Link to Appium logs

`[Appium] Had trouble ending session 5afecaee-aa3b-4606-9960-89dcd3e0500e: Instruments did not terminate after 5 seconds!`
`[MJSONWP] Encountered internal error running command: Error: Instruments did not terminate after 5 seconds!`
   ` at Instruments.callee$2$0$ (lib/instruments.js:338:15)`
    `at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)`
    `at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)`
    `at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)`
    `at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)`
    `at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:104:47)`
    `at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:115:28`
   `at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)`
    `at doNTCallback0 (node.js:419:9)`
    `at process._tickCallback (node.js:348:13)`

**Comment by scottdixon** [comment]
Can you please provide a link to the entire log as a gist?

Any similarities with the tests that _do_ fail?

**Comment by michaelmendoza42** [comment]
i've been getting this recently, also. I think it was caused by 1.5, but i'm not sure how.

**Comment by chemanth** [comment]
I am also analyzing to find out the similarities between failing tests.
Please find below the gist. The file is pretty huge. The exact error is at this time stamp.
2016-03-05 07:05:11:419

https://gist.github.com/chemanth/796c2a539b119c0b90f6

**Comment by scottdixon** [comment]
Thanks. Looking into it.

**Comment by scottdixon** [comment]
Take care of in https://github.com/appium/appium-ios-driver/pull/110 - available in appium-ios-driver 1.8.10 - reopen if any issues.
