### ISSUE TITLE
[Appium 1.5] Appium requires Chrome browser v46+ on Android device

### ISSUE THREAD

**Issue by duylam** [appium/appium#6239]
## The problem

Our team was using Appium 1.4.6 (on both Windows and Mac machines) for testing web apps (using Selenium SDK) on real Android devices (mostly 4.4 and 5.x)

When Appium 1.5 is released, we upgraded Appium in one Windows and Mac machine to try out new features. After v1.5 is installed, we have seen an issue (on both Mac and Windows): when Appium is processing the request `POST /session`, it prints below error in console and stops (I means it doesn't send response back to test script and the http request `POST /session` is ignored)

```org.openqa.selenium.WebDriverException: unknown error: Chrome version must be >= 46.0.2490.0
(Driver info: chromedriver=2.21.371459 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Windows NT 6.1 SP1 x86) (WARNING: The server did not provide any stacktrace information)```

The error disappears if we upgrade the Chrome browser on Android devices to latest (v48 at the time we're doing)

I researched a bit and found that the Chrome v46+ is required due to [this change](https://github.com/appium/appium-chromedriver/commit/9ceea1b007b0ef3183d3a44d10c352f4e5235157) where it uses native chromedriver *2.21*. And chromedriver 2.21 needs Chrome v46+

**My question**

For Android devices, Appium 1.5 requires a Chrome browser released just [6 months ago](http://googlechromereleases.blogspot.com/2015/10/chrome-for-android-update.html). Is this expected requirement (e.g. Appium 1.5 does need to have Chrome v46+) or a misconfiguration (e.g. actually Appium 1.5 can work on Chrome v44+ as 1.4.6)

**Comment by JamesPere** [comment]
I'm also having the same issue as this using Android Emulator, the browser crashes and the same error is listed in the Appium console

**Comment by imurchie** [comment]
This is an expected change. In order to keep up with bug fixes in ChromeDriver (the 3rd party system we use to automate Chrome), we need to upgrade. But ChromeDriver, in upgrades, stops supporting lower versions of Chrome.

You can specify a version while installing appium by using `--chromedriver_version="2.16"` (2.16 can be whatever version you want). See [here](https://github.com/appium/appium-chromedriver#custom-chromedriver-version).

**Comment by duylam** [comment]
@imurchie Thanks for your confirmation. To clarify: you mean we could use Appium 1.5 with old version of chromedriver (by option `--chromedriver_version`) ?

**Comment by imurchie** [comment]
Yes, that is the case. You should see it downloading the version you want
while the install happens.
