### ISSUE TITLE
[Appium 1.5] language capability not recognized by appium

### ISSUE THREAD

**Issue by rompic** [appium/appium#6240]
## The problem

After updating to Appium 1.5 (Server) and appium-java (3.4) I cannot start a server using the language capability (which according to the documentation still exists).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: OSX 10.11.3
* Node.js version (unless using Appium.app|exe): v0.12.9
* Mobile platform/version under test: IOS/Android
* Real device or emulator/simulator: Simulator / Emulator
* Appium CLI or Appium.app|exe: CLI

## Details

-

## Link to Appium logs
"The following capabilities were provided, but are not recognized by appium: language."

## Code To Reproduce Issue [ Good To Have ]
capabilities.setCapability("language", "de");

**Comment by imurchie** [comment]
Fixed by https://github.com/appium/appium-base-driver/commit/8d2b9ff4fef7d1a84dec3373daa4b49861c0e95d

**Comment by rompic** [comment]
Any hint on when this will be released?

**Comment by SrinivasanTarget** [comment]
@rompic Please follow this, https://github.com/appium/appium/blob/master/docs/en/contributing-to-appium/appium-from-source.md and you can use the feature rightaway.

**Comment by Abinmathews** [comment]
I got the following capability issue:
"The following capabilities were provided, but are not recognized by appium: appiumVersion".
I am using appium version 1.6.5,any idea?

**Comment by imurchie** [comment]
@Abinmathews Because that is not an Appium desired capability.
