### ISSUE TITLE
[Appium 1.5] iOS app restart does not clear app cache

### ISSUE THREAD

**Issue by MEZISH** [appium/appium#6241]
## The problem

Java implementation of AppiumDriver does not clean native application cache when the app is being fully reset by method "driver().resetApp()", implemented as "execute(MobileCommand.RESET);".
In previous 1.4.16 Appium version this worked as expected. Right now after re-install the user is still logged in the application.

## Environment

* Appium version 1.5.0
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: OSX
* Node.js version (unless using Appium.app|exe): 4.1.2
* Mobile platform/version under test:  iOS 8.4
* Real device or emulator/simulator: real device iPhone 5
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by HlebHalkouski** [comment]
Maybe [same issue ](https://github.com/appium/appium/issues/6206)

**Comment by MEZISH** [comment]
@HlebHalkouski yes, indeed it seems the same issue. Thank you for the reference. Was not able to find it through search.
