### ISSUE TITLE
[Appium 1.5] 'mobile: scrollTo' method has not yet been implemented

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#6242]
## The problem

I'm using `execute_script('mobile: scrollTo'` command successfully with Appium server `1.4.16`. This is however not working anymore with Appium server `1.5`. Is this something that has been deprecated (I could not find this information from release notes) or is it a bug?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.0
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: Mac OS X El Capitan 10.11.3
* Node.js version (unless using Appium.app|exe): v5.1.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI
* Other: ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]

## Details

```
Appium 1.4.16
Janis-MacBook-Air:android_tests janijegoroff$ arc
[1] pry(main)> execute_script('mobile: scrollTo', element: find_element(id: 'list').ref, text: 'Views')
true
[2] pry(main)>
```
```
Appium 1.5
Janis-MacBook-Air:android_tests janijegoroff$ arc
[1] pry(main)> execute_script('mobile: scrollTo', element: find_element(id: 'list').ref, text: 'Views')
Selenium::WebDriver::Error::UnknownError: Method has not yet been implemented
from /Users/janijegoroff/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/selenium-webdriver-2.50.0/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
[2] pry(main)>
```

## Link to Appium logs

https://gist.github.com/JaniJegoroff/a0fbdb0ab66d82f0e2bb

## Code To Reproduce Issue [ Good To Have ]

1. Fork https://github.com/appium/ruby_lib
2. Connect Android device
3. Start Appium server
4. Navigate to `ruby_lib/android_tests` directory
5. Execute `bundle`
6. Execute `arc`
7. Execute `execute_script('mobile: scrollTo', element: find_element(id: 'list').ref, text: 'Views')`

**Comment by chenchaoyi** [comment]
I believe it has been removed in 1.5, http://appium.io/slate/en/1.5/?ruby#no-more-execute_script%28%22mobile:-xxx%22%29

It would be nice to add it into CHANGELOG.md though.

**Comment by scottdixon** [comment]
All the deprecated `mobile:` commands except scroll have been removed in 1.5.

You can use the [touch action api](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md) instead.

Updating docs + changelog.
