### ISSUE TITLE
Document - update JSON Wire Protocol link

### ISSUE THREAD

**Issue by chenchaoyi** [appium/appium#6243]
## The problem

Mobile JSON Wire Protocol links are still pointing to the decommissioned code.google.com URL.

## Details

The current document like https://github.com/appium/appium/blob/master/docs/en/about-appium/intro.md or https://github.com/appium/appium/blob/master/docs/en/about-appium/appium-clients.md are still pointing to `code.google.com` for JSON Wire Protocol reference, which is resolved to a deprecated link https://github.com/seleniumhq/selenium-google-code-issue-archive now.

When people want to add their own binding libraries, it will become very confusing. It would be much better to update all these links to the official link of JSON Wire Protocol, which I couldn't find at the moment.

**Comment by SrinivasanTarget** [comment]
Please find the same here: https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol

**Comment by chenchaoyi** [comment]
Thanks, the JSON Wire Protocol links are fixed. 

`Mobile JSON Wire Protocol` link still points to `https://code.google.com/p/selenium/source/browse/spec-draft.md?repo=mobile`. Open #6252 to track it.
