### ISSUE TITLE
npm appium fails to install on Travis

### ISSUE THREAD

**Issue by leighdice** [appium/appium#6244]
## The problem

` npm install apppium -g `

trying to install appium with the ` language: android `  in a Travis CI environment keeps failing to install

## Environment

* Appium Version: 1.5.0
* Desktop OS/version used to run Appium: Ubuntu 12.04 LTS
* Node.js version: v0.10.36

## Details

So I am currently writing test suites for an app on both iOS and Android. We've recently set up a general smoke test for iOS which is run using Travis CI. It installs perfectly fine on there.

## Link to Appium logs

https://gist.github.com/leighdice/f42069ef0be389a74915

## Code To Reproduce Issue 

Simple Travis CI android environment.

**Comment by scottdixon** [comment]
Looks like a network issue - are you consistently getting the failure on rerun?

**Comment by leighdice** [comment]
Yeah tried 4 or 5 times, same thing each time.

**Comment by scottdixon** [comment]
I just noticed the node version - can you please try with 0.12 or greater?

**Comment by leighdice** [comment]
Yes we've forced node 0.12 version and worked perfectly.

Sorry to bother! :smile: 

Feel free to close if you don't feed this is an issue

**Comment by scottdixon** [comment]
Thanks for the update! For anyone else who comes across this issue - Appium 1.5 requires Node 0.12 as a minimum Node version.
