### ISSUE TITLE
MobileElement.sendKeys method clashes Appium with iOS UIPickerWheel

### ISSUE THREAD

**Issue by paroliav** [appium/appium#6246]
## The problem

Selecting items in the lists displayed in UIPickerWheel is really slow and crashed Appium if it's a long list of items.
If I have a list like 4.0 4.1 4.2 .. 20.0, and I want to select something at the bottom of the list, Appium tries to select the item in the list, fails to reach at the bottom of the list and throws exception.

## Environment

Appium 1.4.13 (Draco)
El Capitan OSX
iOS 8.1 above
Real devices
Appium CLI node v5.6.0

## Details

Appium crashes when selecting items in big lists in UIPickerWheel. 

## Code To Reproduce Issue [ Good To Have ]

	public static void setpicker(String strObjectRecStr,String spare1, String strInputVal, WebDriver driver)
		  {
			  try {
				  MobileElement ele;
				  ele = (MobileElement)getElement(strObjectRecStr,"",driver);
				  ele.sendKeys(strInputVal);

			} catch (Exception e) {
				e.printStackTrace();
			}

		  }

**Comment by SrinivasanTarget** [comment]
Please try a latest version of appium and raise a new issue along with logs incase if you hit the same. Incase of java-client issues, please raise here: https://github.com/appium/java-client/issues/

**Comment by SrinivasanTarget** [comment]
@triager please close
