### ISSUE TITLE
Appium - Emulator not running error 

### ISSUE THREAD

**Issue by JamesPere** [appium/appium#6247]
## The problem

Unable to run tests against android emulator

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): Appium.exe
* Mobile platform/version under test: Android 6.0 Marshmellow
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium.exe

## Details

The tests start to run, appium recognises this and then launches the android emulator.  When the emulator has loaded up, the tests end up timing out and the message "info: [debug] Emulator Default2 not running" is repeated (Default2 is the name of my avd).

## Link to Appium logs

Appium Log: https://gist.github.com/JamesPere/11101b008e715914d5a4

## Code To Reproduce Issue [ Good To Have ]

I am using the Appium dot net bindings, here is the code I am using:

using System;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Appium;
using OpenQA.Selenium.Appium.Android;

namespace AppiumDriverDemo
{
    [TestFixture()]
    public class ProgramTest
    {
        private AppiumDriver<AppiumWebElement> driver;

        [TestFixtureSetUp]
        public void beforeAll()
        {
            DesiredCapabilities capabilities = new DesiredCapabilities();

            capabilities.SetCapability("deviceName", "Default2");
           capabilities.SetCapability("platformName", "Android");
           capabilities.SetCapability("appPackage", "com.android.calculator2");
           capabilities.SetCapability("appActivity", "com.android.calculator2.Calculator");
            driver = new AndroidDriver<AppiumWebElement>(
                           new Uri("http://127.0.0.1:4723/wd/hub"),
                               capabilities);
        }

        [TestFixtureTearDown]
        public void afterAll()
        {
            // shutdown
            driver.Quit();
        }

        public void TestCalculator()
        {

            var two = driver.FindElement(By.Name("2"));
            two.Click();
            var plus = driver.FindElement(By.Name("+"));
            plus.Click();
            var four = driver.FindElement(By.Name("4"));
            four.Click();
            var equalTo = driver.FindElement(By.Name("="));
            equalTo.Click();

            var results = driver.FindElement(By.ClassName("android.widget.EditText"));

            Assert.AreEqual("6", results.Text);
        }

        [Test()]
        public void AppiumDriverMethodsTestCase()
        {
            // Using appium extension methods
            AppiumWebElement el = driver.FindElementByAccessibilityId("1");
            el.SendKeys("abc");
            Assert.AreEqual(el.Text, "abc");
        }
    }

}

Here are my appium settings
![image](https://cloud.githubusercontent.com/assets/6763784/13598079/df6eee9c-e513-11e5-8c85-0ede002e2a31.png)

**Comment by scottdixon** [comment]
What's the output of `adb devices`? Is Default2 listed?

**Comment by JamesPere** [comment]
Adb devices gives me this 

![image](https://cloud.githubusercontent.com/assets/6763784/13615611/31378e50-e56e-11e5-85d0-a65ee793196e.png)

Not sure where it gets its name from.  I noticed that the test will get further than this if the emulator is already running without the "launch avd" ticked, but whenever it launches it itself, it never sees it.

**Comment by scottdixon** [comment]
Try changing device name to 'emulator-5554'

**Comment by JamesPere** [comment]
In appium, there is no option for 'emulator-5554' only 'Default2' and if I change the device name in my test it still gives me the same error.

**Comment by JamesPere** [comment]
Tried setting the Device Name in Appium which was previously disabled but no different

**Comment by scottdixon** [comment]
I suspect you'll have more luck without using the GUI - are you able to `npm install -g appium` ?

**Comment by JamesPere** [comment]
I've installed using npm and I've run with the following command line params:

appium --address 127.0.0.1 --port 4723 --platform-name Android --platform-version 23 --automation-name Appium --device-name Default2 --log-no-color --pre-launch

But this does not load up the emulator from scratch so I have been unable to replicate the same state via command line

**Comment by scottdixon** [comment]
Once the server is running you'll need to send requests to it to initiate a session.

I suggest posting your issue in the [Appium.exe](https://github.com/appium/appium-dot-exe) project - someone familiar with the Windows GUI may be able to assist.

If you have any problems with the Appium server itself, feel free to reopen this issue.

**Comment by lvconley** [comment]
I'm having precisely the same issue. But I'm running on OSX 10.11.3, with Appium 1.4.13, and Android Studio 2.1 Preview 1 (March 08, 2016). I don't think that this is an Appium problem, however. I think it's an issue with the Android Studio 2.1 Preview. Specifically, at the commandline, when I type: 

`android list avd` 

I get the following:

```
The following Android Virtual Devices could not be loaded:
    Name: Nexus_6_API_23x86
    Path: /Users/dude/.android/avd/Nexus_6_API_23.avd
   Error: Uknown error
```

Each and every AVD created by Android Studio has this same issue. So, once Appium launches the AVD, it then cannot start a session with it to install my app to test and displays the following:

```
info: [debug] executing cmd: /Applications/Android_SDKs/adt-bundle-mac-x86_64-20140702/sdk/platform-tools/adb devices

info: [debug] 1 device(s) connected
info: [debug] 1 emulator(s) connected
info: [debug] Sending telnet command to device: avd name
info: [debug] Getting running emulator port
info: [debug] Socket connection to device created
info: [debug] Socket connection to device ready
info: [debug] Telnet command got response: a[K[Dav[K[D[Davd[K[D[D[Davd [K[D[D[D[Davd n[K[D[D[D[D[Davd na[K[D[D[D[D[D[Davd nam[K[D[D[D[D[D[D[Davd name[K
Nexus_6_API_23
info: [debug] Emulator Nexus_6_API_23 not running
```
So, I think this issue is a problem with the Android Studio beta release. When time permits I will uninstall Android Studio 2.1 Preview 1 and re-install the older current release and then see what happens.

**Comment by lvconley** [comment]
As a work-around I'll try installing an older version of Android Studio and see if things start working again: http://tools.android.com/tips/using-multiple-android-studio-versions

**Comment by scottdixon** [comment]
Interesting @lvconley - please keep us posted.

**Comment by LoveleenSaini** [comment]
I am having same issue on Windows.
Appium version  - 1.4.16.1

**Comment by saranguruprasath** [comment]
same issue here with appium-1.4.16.1 & android studio 2.1.2 Build #AI-143.2915827

info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: [debug] Trying to find appiumtestdevice emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: G:\Androidstudio\Android\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: [debug] 1 emulator(s) connected
> info: [debug] Sending telnet command to device: avd name
> info: [debug] Getting running emulator port
> info: [debug] Socket connection to device created
> info: [debug] Socket connection to device ready
> info: [debug] Telnet command got response: a[K[Dav[K[D[Davd[K[D[D[Davd [K[D[D[D[Davd n[K[D[D[D[D[Davd na[K[D[D[D[D[D[Davd nam[K[D[D[D[D[D[D[Davd name[K
> appiumtestdevice
> info: [debug] Emulator appiumtestdevice not running
> info: [debug] Launching Emulator with AVD appiumtestdevice, launchTimeout 120000ms and readyTimeout 120000ms
> info: [debug] Checking whether emulator is present
> info: [debug] Using emulator from G:\Androidstudio\Android\sdk\tools\emulator.exe
> info: [debug] Trying to find appiumtestdevice emulator
> info: [debug] Getting connected emulators
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: G:\Androidstudio\Android\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: [debug] 1 emulator(s) connected
> info: [debug] Sending telnet command to device: avd name
> info: [debug] Getting running emulator port
> info: [debug] Socket connection to device created
> info: [debug] Socket connection to device ready
> info: [debug] Telnet command got response: a[K[Dav[K[D[Davd[K[D[D[Davd [K[D[D[D[Davd n[K[D[D[D[D[Davd na[K[D[D[D[D[D[Davd nam[K[D[D[D[D[D[D[Davd name[K

**Comment by jayeshust** [comment]
restart & uncheck the launch AVD option worked for me

**Comment by khansanar20** [comment]
Did anyone find a solution to this? I am facing the same issue on MAC with appium 1.4.16. The test launches the emulator however I continuosly get the error : Emulator not running. Would really appreciate your help.

**Comment by trigoesrodrigo** [comment]
It is a problem with the latest versions of the android emulators. They report the name of the emulator with special characters that can't be parsed by that version of Appium. Either revert to older versions of those emulators, or update Appium to >=1.5.2.

**Comment by vpkhachane** [comment]
I am facing same issues , Unable to launch app on emulator ..Anyone know how to integrate genymotion emulator in appium

**Comment by jithin768** [comment]
Did anyone find a solution to this? I am facing the same issue on MAC with appium 1.4.13. Please help me to solve this issue . 

info: [debug] 1 device(s) connected
info: [debug] 1 emulator(s) connected
info: [debug] Sending telnet command to device: avd name
info: [debug] Getting running emulator port
info: [debug] Socket connection to device created
info: [debug] Socket connection to device ready
info: [debug] Telnet command got response: a[K[Dav[K[D[Davd[K[D[D[Davd [K[D[D[D[Davd n[K[D[D[D[D[Davd na[K[D[D[D[D[D[Davd nam[K[D[D[D[D[D[D[Davd name[K
Nexus_5X_API_22
info: [debug] Emulator  not running
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...

warn: UiAutomator did not shut down fast enough, calling it gone

error: Failed to start an Appium session, err was: Error: Could not find  emulator.

info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session

info: [debug] Error: Could not find  emulator.
    at [object Object].ADB.getRunningAVDWithRetry (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:715:15)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:794:10)
    at [object Object].ADB.checkSdkBinaryPresent (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:116:5)
    at [object Object].ADB.launchAVD (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:760:8)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:800:23)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:720:11)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:707:9
    at done (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/node_modules/async/lib/async.js:132:19)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/node_modules/async/lib/async.js:32:16
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:703:11)
    at Socket.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:1538:9)
    at Socket.emit (events.js:107:17)
    at TCP.close (net.js:485:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not find  emulator.)","origValue":"Could not find  emulator."},"sessionId":null}
info: <-- POST /wd/hub/session 500 249521.374 ms - 172 

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: <-- GET /wd/hub/status 200 0.697 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: <-- GET /wd/hub/status 200 0.847 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: <-- GET /wd/hub/status 200 0.707 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: <-- GET /wd/hub/status 200 0.785 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: <-- GET /wd/hub/status 200 1.107 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: <-- GET /wd/hub/status 200 1.135 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

**Comment by Mushtaq-QA** [comment]
restart Appium & uncheck the launch AVD option under Android settings,
because you are already calling the device in your code so no need to launch it again.
