### ISSUE TITLE
[1.5 Android. Selendroid] Can't open a session on Windows 7 

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/appium#6249]
## The problem

A Selendroid session is not being opened on Windows7.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.0
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 5.7.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator

## Details
This is reproduced with Windows 7. I can't reproduce it with Win 8/10

## Link to Appium logs

https://gist.github.com/TikhomirovSergey/fb6ba8aeb468be012c69

## Code To Reproduce Issue [ Good To Have ]

```java
AppiumServiceBuilder builder = new AppiumServiceBuilder();
AppiumDriverLocalService  service = builder.build();
 service.start();

File appDir = new File("src/test/java/io/appium/java_client");
File app = new File(appDir, "ApiDemos-debug.apk");
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
//capabilities.setCapability(AndroidMobileCapabilityType.SELENDROID_PORT, SELENDROID_PORT);
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.SELENDROID);
AppiumDriver<WebElement>  driver = new AndroidDriver<>(service.getUrl(), capabilities);
```

**Comment by scottdixon** [comment]
Thanks. Investigating.

**Comment by scottdixon** [comment]
@TikhomirovSergey - I was able to run a successful selendroid session on Windows 7. Here's the last part of my log: https://gist.github.com/scottdixon/f4b56455663d440e099f

Your error looks similar to the existing Windows issue which was resolved in https://github.com/appium/appium-adb/pull/141. Please grab a fresh copy of Appium + make sure you're using appium-adb 2.4.2 or greater.

Let me know if the issue persists.

**Comment by TikhomirovSergey** [comment]
@scottdixon 
ok. I'll try again soon...
