### ISSUE TITLE
processArguments option do not handle the arguments correctly

### ISSUE THREAD

**Issue by xuanzhaopeng** [appium/appium#6250]
## The problem

Appium and Appium-IOS-driver could not handle the processArguments correctly if there is several space in it.

## Environment

Appium 1.5.0 (installed from nom)
Appium-IOS-Driver 1.8.7

## Details

From Appium, it provides an option variable called processArguments could be used for generation of InstrumentsExecArgs, but however, it only could consider it correctly when the argument without space.

However if I want to pass some argument such as : -e ABCDEFG TESTNAME -e DFASDFSDF TESTER

so it will make them become a string, rather than the arguments.
check source code here :

https://github.com/appium/appium-instruments/blob/master/lib/instruments.js#L279

**Comment by imurchie** [comment]
This is fixed in `appium-ios-driver` and will be in the next release.
