### ISSUE TITLE
Document - update Mobile JSON Wire Protocol link

### ISSUE THREAD

**Issue by chenchaoyi** [appium/appium#6252]
## The problem
#6248 fixes the JSON Wire Protocol link, but the `Mobile JSON Wire Protocol` links are still pointing to the decommissioned code.google.com URL.

## Details

The current documents like
* https://github.com/appium/appium/blob/master/docs/en/about-appium/intro.md 
* https://github.com/appium/appium/blob/master/docs/en/about-appium/appium-clients.md 

are still pointing to `https://code.google.com/p/selenium/source/browse/spec-draft.md?repo=mobile` for Mobile JSON Wire Protocol reference, which is resolved to a deprecated link now.

**Comment by imurchie** [comment]
The correct link is `https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md` (see [Appium's implementation](https://github.com/appium/node-mobile-json-wire-protocol#mobile-json-wire-protocol).
