### ISSUE TITLE
[Appium 1.5] Appium is not honoring noReset=true capability when executing against android device

### ISSUE THREAD

**Issue by nmeason** [appium/appium#6254]
## The problem

Appium is not honoring the noReset=true capability passed in for the session. Every time I start a session for Android, with this capability, my app is uninstalled and then re-installed. 
## Environment
- Appium version: 1.5.0
- Last Appium version that did not exhibit the issue: 1.4.16
- Desktop OS/version used to run Appium: Mac OS X Yosemite 10.10.5
- Node.js version: 5.7.1
- Mobile platform/version under test: Android 5.0
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: Appium CLI
## Details

1) Install app on android mobile device.
2) Create AndroidDriver and pass in noReset=true as a capability.
2) Run test code.

App is uninstalled from the device and re-installed. Expect the the app to not be uninstalled since noReset=true was set.
## Link to Appium logs

https://gist.github.com/nmeason/1027320bf0bd2cda15d3
## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Samsung Galaxy S5");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "Android");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "5.1");
capabilities.setCapability(MobileCapabilityType.UDID, "012345abc");
capabilities.setCapability(MobileCapabilityType.APP, "my.apk");
capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
driver = new AndroidDriver(new URL("http://localhost:4733/wd/hub"), capabilities);

**Comment by asnaith** [comment]
I was just about to log this issue too. I have exactly the same problem coming from 1.4.16.

Sharing my environment too as it's slightly different and maybe that helps rule out some of the possible causes of the problem. 

**Environment**

Appium version: 1.5.0
Last Appium version that did not exhibit the issue: 1.4.16
Desktop OS/version used to run Appium: Windows 10
Node.js version: 5.1.0
Mobile platform/version under test: Android 5.1.1
Real device or emulator/simulator: Real device
Appium CLI or Appium.app|exe: Appium CLI

**Comment by nmeason** [comment]
I see this hasn't been triaged yet. Any update? This issue is increasing our runtime by quite a bit since the app is installing fresh every time we run a test.

**Comment by imurchie** [comment]
If you update to the latest version of `appium-android-driver` this ought to be fixed.

**Comment by nmeason** [comment]
Thank you. I've updated to the latest version and the noReset flag seems to be honored now.

**Comment by Kignuf** [comment]
Hello, I'm having this issue but I'm unsure how to update appium-android-driver package.
Could someone give me a hint please ?

Thanks !
