### ISSUE TITLE
Android WebView Tests Fail with "no such element: Unable to locate element" only on certain devices

### ISSUE THREAD

**Issue by gbsendhil** [appium/appium#6258]
I have a test case that uses the android webview context/driver.

The tests are successful on certain devices but fails on some devices (mostly Samsung) with the below error

info: JSONWP Proxy: Got response with status 200: {"sessionId":"890fcd6351f05365da5eb39da327e302","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//*[@id='welcomeSection']/div[1]/div[3]/h...

The android application is compiled with SDK 23. And    WebView.setWebContentsDebuggingEnabled(true);

**Comment by scottdixon** [comment]
Which version of Appium are you using? Are all the devices using the same API level? Can you please provide the entire log as a [gist](http://gist.github.com)?

**Comment by ramdas80** [comment]
Appium version 1.4.8
Appium Java client - 3.3.0

**Comment by scottdixon** [comment]
Thanks @ramdas80 - do you hit the same issue with a more recent version of Appium?

**Comment by gbsendhil** [comment]
Yes , 

We even tried with the latest version of appium and it still fails to find the element.

The interesting point here is the test's run smoothly when on run on certain set of devices  and fails on another set of them.  

When we debugged till the org.openqa.selenium.By.xpath(findByValue); we didn't see any difference in the flows .

Our problem is occuring only on certain  devices mostly samsung it gives the element not found . 

We are experiencing the problem after the APK was compiled with targetSDK 23.

**Comment by scottdixon** [comment]
`The interesting point here is the test's run smoothly when on run on certain set of devices and fails on another set of them.` - can you elaborate as to which devices work/don't work?

**Comment by gbsendhil** [comment]
It worked on HTC M8 (4.4.4)  and failed on Samsung S6 (5.0.1)

**Comment by ronnelpinto** [comment]
Could you please help us on this? We are still encountering this issue on most of the devices. Has it got to do something with the API version or device manufacturer?

**Comment by scottdixon** [comment]
Thanks. This is on the radar to investigate.

**Comment by jlipps** [comment]
@gbsendhil can you print out the source of the app on a working device and a non-working device immediately before the find Element and confirm that the source is the same?

**Comment by ronnelpinto** [comment]
@jlipps 
Element not found in web view (Actual issue)
This issue is still coming on devices above 5.0. Tests work fine on Webviews for 4.4 devices.
Nature of this issue is Random as on same device it run sometime successfully and sometime does not.

Has this issue got something to do with Android System Webview update for 5.0 and above?

**Comment by SrinivasanTarget** [comment]
@gbsendhil Bro i'm closing this. Will help out in office if you need any lead on this. Could be a external driver issue or with system webviews.
