### ISSUE TITLE
Unlocker borks phone

### ISSUE THREAD

**Issue by adamf663** [appium/appium#6262]
## The problem
The appium unlocker, if permitted to run, will cause our launcher to lock up and require the phone to be rebooted.  I am only able to use appium on a locked phone if I hack the appium javascript to comment out the unlock code.
This problem existed in 1.4.16 and exists in 1.5.

Fix for appium-1.5:  edit 
{linuxbrew}/lib/node_modules/appium/node_modules/appium-android-driver/build/lib/android-helpers.js
```
helpers.unlock = function callee$0$0(adb) {
  return _regeneratorRuntime.async(function callee$0$0$(context$1$0) {
    var _this2 = this;

    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
        context$1$0.next = 2;
        return _regeneratorRuntime.awrap(adb.isScreenLocked());

      case 2:
        if (context$1$0.sent) {
          context$1$0.next = 5;
          break;
        }

        _logger2['default'].info("Screen already unlocked, doing nothing");
        return context$1$0.abrupt('return');

      case 5:
        _logger2['default'].info("Unlocking screen");

        context$1$0.next = 8;
        return _regeneratorRuntime.awrap((0, _asyncbox.retryInterval)(10, 1000, function callee$1$0() {
          return _regeneratorRuntime.async(function callee$1$0$(context$2$0) {
            while (1) switch (context$2$0.prev = context$2$0.next) {
              case 0:
 **             return context$2$0.stop();
                //_logger2['default'].debug("Screen is locked, trying to unlock");
                //context$2$0.next = 3;
                //return _regeneratorRuntime.awrap(adb.startApp({
                  //pkg: "io.appium.unlock",
                  //activity: ".Unlock",
                  //action: "android.intent.action.MAIN",
                  //category: "android.intent.category.LAUNCHER",
                  //flags: "0x10200000"
                //}));
**
              case 3:
                context$2$0.next = 5;
                return _regeneratorRuntime.awrap(adb.isScreenLocked());

              case 5:
                if (context$2$0.sent) {
                  context$2$0.next = 9;
                  break;
                }

                _logger2['default'].debug("Screen unlocked successfully");
                context$2$0.next = 10;
                break;

              case 9:
                throw new Error("Screen did not unlock successfully, retrying");

              case 10:
              case 'end':
                return context$2$0.stop();
            }
          }, null, _this2);
        }));

      case 8:
      case 'end':
        return context$1$0.stop();
    }
  }, null, this);
};
```

**Comment by scottdixon** [comment]
Thank for taking the time to report @adamf663. Can you please provide logs as a gist so I can investigate further?

**Comment by adamf663** [comment]
Attached are logcat, bugreport, and the appium log
[unlock.zip](https://github.com/appium/appium/files/167391/unlock.zip)

**Comment by scottdixon** [comment]
Thanks. Looking into this.

**Comment by scottdixon** [comment]
@adamf663 - please clarify: `I am only able to use appium on a locked phone if I hack the appium javascript to comment out the unlock code.` - if you comment out the unlock code, the device unlocks anyway?

**Comment by adamf663** [comment]
No.  I unlock the phone through my scripts.
If I leave the appium code as is, I'm left with an phone that is unusable until rebooted.

----- Original Message -----

**Comment by scottdixon** [comment]
Related to https://github.com/appium/appium/issues/5080

**Comment by scottdixon** [comment]
A [recent update to unlocker](https://github.com/appium/unlock_apk/commit/020456f9d9e8ca58d3a395b1009af8d88bf1ae78) might resolve this - Appium 1.5.1 should be released today or tomorrow which will include this update. Let me know if this resolves the hang.

**Comment by adamf663** [comment]
Any chance the clear field bug might get someday fixed?  It is maddening not being even able to reliably enter a text field!
Also what about that nasty bug where findelements on an element will return children of another parent if nothing is found? That bug makes
reading notification messages nearly impossible.
Or the bug where losing wifi (or it reconnecting) will crash appium?

----- Original Message -----

**Comment by scottdixon** [comment]
#6269 & #6261 are on the radar.

Clear field bug issue, is this the same as #4694?

**Comment by adamf663** [comment]
no.  The problem is that when calling clearField, appium fails about 15% of the time to clear the field despite taking an amazingly long time to (not) do it.

----- Original Message -----

**Comment by imurchie** [comment]
Yes, we've reviewed and reviewed that code. If you give logs of how it is failing we can revisit and see if there is something else that can be done.

**Comment by adamf663** [comment]
I did.

----- Original Message -----

**Comment by adamf663** [comment]
oh, I thought you were talking about the unlock/borker code.
I'll get you logs next time clearField fails.  I can barely go a day without that bug occuring.

How about the wifi connect/reconnect bug where all that is needed to crash appium is for the wifi network to come and go?
or the bug where findelements returns an element off a different parent if none exist?


----- Original Message -----

**Comment by imurchie** [comment]
Those are on our radar and are being put into the queue.

**Comment by adamf663** [comment]
thank you.

----- Original Message -----

**Comment by jlipps** [comment]
@adamf663 as another note: it sounds like those other bugs already have issues created; in the future can you please +1 your frustration about them on those issue pages so we can use that to help us prioritize a fix? talking about it here doesn't give us that record, and with the hundreds of issues being discussed in this tracker it would be easy for them to get lost. sounds like in this case that @imurchie and @scottdixon are aware now anyway.

**Comment by adamf663** [comment]
Seems reasonable.  I'm just frustrated right now.  I do appreciate all the hard work you're doing.

----- Original Message -----

**Comment by jlipps** [comment]
We understand your frustration. Believe us! Working with the idiosyncrasies of the underlying tools Appium is forced to integrate with can be as infuriating as using Appium, and the former is often the root cause of the latter :-) Thanks for your patience.

**Comment by adamf663** [comment]
and whose brilliant idea at google was it that scrollable menus do not have an internal structure with the entire list?  I've never had such problems with any other automation in my 20 years experience.  Can't do the page object model in android if the entire menu isn't visible!  

----- Original Message -----

**Comment by imurchie** [comment]
@adamf663 Would you mind sharing how you are unlocking apps in your scripts? The more options we have to think about fixing, the better.

**Comment by adamf663** [comment]
Right now the automation simply looks for a screen object only seen on the unlock page and does a swipe from bottom to top to unlock.
Later it'll be enhanced to enter a pin "1234" for pin unlock.

----- Original Message -----

**Comment by adamf663** [comment]
Has 1.5.1 been released?

----- Original Message -----

**Comment by SrinivasanTarget** [comment]
@triager please close
