### ISSUE TITLE
are you sure it's powered on? - Issue Appium

### ISSUE THREAD

**Issue by edward22mc** [appium/appium#6263]
## The problem

I was able to open the app on my device once I clicked on the "Play" button. Now I can't.
## Environment

Device: Samsung Note 4 (Android 5.1.1)
Appium version: 1.4.16.1
## Link to Appium logs

> info: [debug] Starting Appium in pre-launch mode
> info: Pre-launching app
> info: [debug] Using local app from command line: C:\AndroidSDK\sdk\APKS\Core_2_4_1_1_Beta.apk
> info: [debug] Creating new appium session eedce219-925a-4acb-8f31-78ab7255e447
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_73
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\AndroidSDK\sdk\platform-tools\adb.exe
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device 410014fddca722db
> info: [debug] Setting device id to 410014fddca722db
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db wait-for-device
> info: [debug] Retrying restartAdb
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db kill-server
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db devices
> info: [debug] 1 device(s) connected
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db wait-for-device
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db shell "echo 'ready'"
> info: [debug] Retrying restartAdb
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db kill-server
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db devices
> info: [debug] 1 device(s) connected
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db wait-for-device
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db shell "echo 'ready'"
> info: [debug] Retrying restartAdb
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db kill-server
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db devices
> info: [debug] 1 device(s) connected
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db wait-for-device
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db shell "echo 'ready'"
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db kill-server
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db devices
> info: [debug] 1 device(s) connected
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db wait-for-device
> info: [debug] executing cmd: C:\AndroidSDK\sdk\platform-tools\adb.exe -s 410014fddca722db shell "echo 'ready'"
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> error: Could not pre-launch appium: Device did not become ready in 5 secs; are you sure it's powered on?

**Comment by jprakash1** [comment]
i am also got the same issue.

**Comment by MohiniR** [comment]
i am also getting the same issue. @jprakash1 are you running appium in server machine?

**Comment by jprakash1** [comment]
@MohiniR  No, I just using my Lap.

**Comment by dpgraham** [comment]
If one of you can provide me with steps to reproduce this we can investigate this issue.

**Comment by dpgraham** [comment]
Closing for now. I'll re-open it if more info is provided.
