### ISSUE TITLE
Unable to install app on iOS device 

### ISSUE THREAD

**Issue by lakshmypriya** [appium/appium#6264]
## The problem

I am trying to install app on my device using appium command line tool .

## Environment

* Appium v1.5.0 (REV 470e5356f559481a5529df8d4e929aa62254cee8)
*Previous Version of Appium  1.4.15:
* Mac OS El capitan:
* Node.js version (v5.7.0):
* iOS:
* Real device :iOS 9.2
* Appium CLI 
* Xcode 7.2.1

## Details

I am trying to install app on my device using appium command line tool . It was working fine with the previous version I had  but wouldn't install the app with the current version .I didn't change anything in the code 

## Link to Appium logs
https://gist.github.com/lakshmypriya/01f333cdb76c2e7e8c6b

## Code To Reproduce Issue [ Good To Have ]

=

**Comment by saikrishna321** [comment]
@lakshmypriya your trying to install simulator build on real device, which will not work. You need to have .ipa file

**Comment by hajarbabour** [comment]
@lakshmypriya http://stackoverflow.com/questions/517463/how-can-i-install-a-ipa-file-to-my-iphone-simulator

**Comment by SrinivasanTarget** [comment]
@triager please close
