### ISSUE TITLE
webview setWebViewClient didn‘t have an effect when test by appium selendroid

### ISSUE THREAD

**Issue by easyforgood** [appium/appium#6266]
## The problem

webview.setWebViewClient() didn't work when I want to override a shouldOverrideUrlLoading().

some operator in shouldOverrideUrlLoading() but it didn't work when using appium and selendroid
## Environment
- Appium version (or git revision) that exhibits the issue: 1.4.16.1
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Windows7 32bit
- Node.js version (unless using Appium.app|exe): v4.2.2
- Mobile platform/version under test: android 4.3 
- Real device or emulator/simulator: emulator
- Appium CLI or Appium.app|exe: Appium.exe
## Details

It's hybrid  type and under android 4.4 so I have to use the **selendroid**

I test  run with the Appium auto-operator and without appium by manual.

Setting log.i() to print log  in the  @Override  shouldOverrideUrlLoading().

On the manual hand, every log print could be found.
But On the other appium test hand, It hasn’t been find and just like shouldOverrideUrlLoading() didn't exsit.
## Link to Appium logs

 [gist](https://gist.github.com/easyforgood/700e33ac69828d42c0e2)  

> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/window_handles","method":"GET"}
> info: [debug] Available contexts: ["NATIVE_APP","WEBVIEW_0"]
> info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP","WEBVIEW_0"],"sessionId":"860b4876-c367-f05c-d73a-6e97d8c17b86"}
> info: <-- GET /wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/contexts 200 281.003 ms - 98 {"status":0,"value":["NATIVE_APP","WEBVIEW_0"],"sessionId":"860b4876-c367-f05c-d73a-6e97d8c17b86"}
> info: --> POST /wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/context {"name":"WEBVIEW_0"}
> info: [debug] Getting a list of available webviews
> info: [debug] executing cmd: D:\android-sdk\platform-tools\adb.exe -s emulator-5554 shell "cat /proc/net/unix"
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_0
> info: [debug] []
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/window_handles","method":"GET"}
> 
> info: [debug] Available contexts: ["NATIVE_APP","WEBVIEW_0"]
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/context","method":"POST","json":{"name":"WEBVIEW_0"}}
> info: [debug] [SELENDROID] Unable to resolve superclass of Lio/selendroid/server/model/SelendroidWebDriver$ExtendedSystemWebChromeClient; (1841)
> info: [debug] [SELENDROID] Link of class 'Lio/selendroid/server/model/SelendroidWebDriver$ExtendedSystemWebChromeClient;' failed
> info: [debug] [SELENDROID] Could not find class 'io.selendroid.server.model.SelendroidWebDriver$ExtendedSystemWebChromeClient', referenced from method io.selendroid.server.model.SelendroidWebDriver.encapulateWebChromeClientForView
> info: [debug] [SELENDROID] unable to resolve new-instance 1456 (Lio/selendroid/server/model/SelendroidWebDriver$ExtendedSystemWebChromeClient;) in Lio/selendroid/server/model/SelendroidWebDriver;
> info: [debug] [SELENDROID] Unable to resolve superclass of Lio/selendroid/server/model/SelendroidWebDriver$SelendroidSystemWebViewClient; (1843)
> info: [debug] [SELENDROID] Link of class 'Lio/selendroid/server/model/SelendroidWebDriver$SelendroidSystemWebViewClient;' failed
> info: [debug] [SELENDROID] Could not find class 'io.selendroid.server.model.SelendroidWebDriver$SelendroidSystemWebViewClient', referenced from method io.selendroid.server.model.SelendroidWebDriver.encapulateWebViewClientForView
> info: [debug] [SELENDROID] unable to resolve new-instance 1458 (Lio/selendroid/server/model/SelendroidWebDriver$SelendroidSystemWebViewClient;) in Lio/selendroid/server/model/SelendroidWebDriver;
> info: [debug] [SELENDROID] Unable to resolve superclass of Lio/selendroid/server/model/SelendroidWebDriver$ExtendedSystemWebChromeClient; (1841)
> info: [debug] [SELENDROID] Link of class 'Lio/selendroid/server/model/SelendroidWebDriver$ExtendedSystemWebChromeClient;' failed
> info: [debug] [SELENDROID] Unable to resolve superclass of Lio/selendroid/server/model/SelendroidWebDriver$SelendroidSystemWebViewClient; (1843)
> info: [debug] [SELENDROID] Link of class 'Lio/selendroid/server/model/SelendroidWebDriver$SelendroidSystemWebViewClient;' failed
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"860b4876-c367-f05c-d73a-6e97d8c17b86"}
> info: <-- POST /wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/context 200 904.860 ms - 76 {"status":0,"value":null,"sessionId":"860b4876-c367-f05c-d73a-6e97d8c17b86"}
> info: --> POST /wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/context {"name":"WEBVIEW_0"}
> info: [debug] Getting a list of available webviews
> info: [debug] executing cmd: D:\android-sdk\platform-tools\adb.exe -s emulator-5554 shell "cat /proc/net/unix"
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_0
> info: [debug] []
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/window_handles","method":"GET"}
> info: [debug] Available contexts: ["NATIVE_APP","WEBVIEW_0"]
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"860b4876-c367-f05c-d73a-6e97d8c17b86"}
> info: <-- POST /wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/context 200 269.353 ms - 76 {"status":0,"value":null,"sessionId":"860b4876-c367-f05c-d73a-6e97d8c17b86"}
> info: --> POST /wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/element {"using":"link text","value":"click app me"}
> info: [debug] Proxying command to localhost:8080
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/element","method":"POST","json":{"using":"link text","value":"click app me"}}
> info: [debug] Proxied response received with status 200: {"value":{"ELEMENT":":wdc:1457598532243"},"status":0,"sessionId":"860b4876-c367-f05c-d73a-6e97d8c17b86"}
> info: <-- POST /wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/element 200 1251.147 ms - 104 
> info: --> POST /wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/element/%3Awdc%3A1457598532243/click {"id":":wdc:1457598532243"}
> info: [debug] Proxying command to localhost:8080
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/element/%3Awdc%3A1457598532243/click","method":"POST","json":{"id":":wdc:1457598532243"}}
> info: [debug] Proxied response received with status 200: {"value":"","status":0,"sessionId":"860b4876-c367-f05c-d73a-6e97d8c17b86"}
> info: <-- POST /wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/element/%3Awdc%3A1457598532243/click 200 1598.258 ms - 74 
> info: --> POST /wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/timeouts {"type":"script","ms":20000}
> info: [debug] Proxying command to localhost:8080
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/timeouts","method":"POST","json":{"type":"script","ms":20000}}
> info: [debug] Proxied response received with status 200: {"status":0,"sessionId":"860b4876-c367-f05c-d73a-6e97d8c17b86"}
> info: <-- POST /wd/hub/session/860b4876-c367-f05c-d73a-6e97d8c17b86/timeouts 200 101.053 ms - 63 
## Code To Reproduce Issue [ Good To Have ]

appium.java

```
DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "emulator-5554");
        capabilities.setCapability("platformVersion", "4.3.1");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability(MobileCapabilityType.APP,
                "D:\\JAVAWORKSPACE\\TestforAppium\\bin\\TestforAppium.apk");
        capabilities.setCapability("automationName", "Selendroid");
        capabilities.setCapability("appPackage", "com.example.testforappium");
        capabilities.setCapability("appActivity", ".MainActivity");
        AndroidDriver driver = null;
        try {
            URL url = new URL("http://127.0.0.1:4723/wd/hub");
            driver = new AndroidDriver(url, capabilities);
            driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
            driver.manage().timeouts().pageLoadTimeout(10, TimeUnit.SECONDS);
            Set<String> contextNames =  ((AppiumDriver) driver).getContextHandles();
            driver.context("WEBVIEW_0");
            driver.findElementByLinkText("click app me").click();
        } catch (Exception e) {
            e.printStackTrace();
        }
```

---

MainActivity.java

```
    setContentView(R.layout.activity_main);
        webview= (WebView) this.findViewById(R.id.webView1);
        Log.i("finish", "1");
        webview.setWebViewClient(new WebViewClient(){
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url){
                Log.i("finish", "2");
                if(url.startsWith("http://baidu")){
                    Log.i("finish", "3");
                    testOperation();
                }
                view.loadUrl(url);
                return true;
            }
        });
        webview.loadUrl("http://172.27.146.62/");

    }
```

**Comment by dpgraham** [comment]
This looks like a problem with Selendroid.
