### ISSUE TITLE
TypeError: null is not an object (evaluating 'au.getElement('5001').rect')

### ISSUE THREAD

**Issue by ciekawy** [appium/appium#6267]
## The problem

when invoking tap in `NATIVE_MODE` like this 

```
var action = new TouchAction(driver)
          .tap({e: element})
          .release()
          .perform();
```

I'm getting an error

```
[debug] [Instruments] [INST] 2016-03-10 09:12:50 +0000 Debug: Got new command 6 from instruments: au.getElement('5001').rect()
[debug] [Instruments] [INST] 2016-03-10 09:12:50 +0000 Debug: evaluating au.getElement('5001').rect()
[debug] [Instruments] [INST] 2016-03-10 09:12:50 +0000 Error: TypeError: null is not an object (evaluating 'au.getElement('5001').rect')

```
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.0
- Desktop OS/version used to run Appium: OS X 10.11.2
- Node.js version (unless using Appium.app|exe): 4.2.1
- Mobile platform/version under test: iOS 9.2
- Real device or emulator/simulator: simulator iPhone 6s
- Appium CLI or Appium.app|exe: appium
## Details

I think this is eaxectly the same problem as described here
https://gist.github.com/sarfmomin/b50d34a33138a6906be0
## Link to Appium logs

https://gist.github.com/ciekawy/f1bbe70f10ef9b0aa52d

**Comment by dpgraham** [comment]
It's probably not finding the element. If you post the source XML (driver.source()) then we can check if it's a bug or not.
