### ISSUE TITLE
Appium can't detect available objects

### ISSUE THREAD

**Issue by rockyav** [appium/appium#6273]
## The problem

There are 3 topics in the screen:
. Top-up with a credit/Mada card : have 1 textfield
. Top-up with SADAD : have 2 textfield
. Top-up with a voucher : have 1 textfield

These topic are collapse format, touch on this, the textfield will displays.

And each object have edit textfield, but appium only can detect the textfield of 1st topic. While I can see, touch, input text on other textfield.

I use the "outsource" function to show, and see only 1 textfield is available, these other are not show.
## Environment
- Appium version 1.4.15
- Desktop OS/version used to run Appium: OS X Yosemite v10.10.5
- Node.js version (unless using Appium.app|exe): 4.2.2
- Mobile platform/version under test: iPhone 6S
- Real device or emulator/simulator: Real device
## Logs:

[Logs.docx](https://github.com/appium/appium/files/171339/Logs.docx)

---

**In the logs, you can see, there is only one "UIATextField" displayed.**

**Comment by scottdixon** [comment]
Can you please provide your logs as a [gist](gist.github.com)?

**Comment by rockyav** [comment]
@scottdixon I have just updated the log. Please check :)
Thanks.

**Comment by scottdixon** [comment]
@rockyav - thanks for the app xml, can you please share your test code and appium logs as a gist?
