### ISSUE TITLE
driver().launchApp() uninstalls application in Android

### ISSUE THREAD

**Issue by SergeVKom** [appium/appium#6274]
## The problem
Application is deleted after call method driver().launchApp()

## Environment

* Appium version: 1.5
* Last Appium version that did not exhibit the issue: 1.4.16
* Desktop OS/version used to run Appium: MacOS 10.11.3
* Node.js version: 5.7.1
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe:  Appium CLI

## Details

1. Install app
2. call driver().closeApp()
3. call driver().launchApp()

## Link to Appium logs

https://gist.github.com/SergeVKom/67b2054e475beafb1e6b

## Code To Reproduce Issue

2016-03-11 13:09:27:542 - [Appium] Creating new AndroidDriver session
2016-03-11 13:09:27:542 - [Appium] Capabilities:
2016-03-11 13:09:27:548 - [Appium]   appActivity: 'com.oxagile.animationsample.LoginActivity'
2016-03-11 13:09:27:549 - [Appium]   appPackage: 'com.conax.golive.development'
2016-03-11 13:09:27:550 - [Appium]   newCommandTimeout: 300
2016-03-11 13:09:27:550 - [Appium]   platformVersion: '6.0'
2016-03-11 13:09:27:551 - [Appium]   automationName: 'Appium'
2016-03-11 13:09:27:551 - [Appium]   platformName: 'Android'
2016-03-11 13:09:27:552 - [Appium]   deviceName: 'Nexus 6'
2016-03-11 13:09:27:552 - [Appium]   noReset: true

**Comment by nuggit32** [comment]
I'm seeing the same thing occur as well after calling launchApp().
Here is a gist of the appium log.
https://gist.github.com/nuggit32/02f1bdf67fa2d015b7ad

**Comment by nuggit32** [comment]
This seems like a high priority issue for anyone wanting to move to 1.5.  Currently my code base cannot goto 1.5 if the app is getting uninstalled?  Is there a workaround or projected fix?

**Comment by nuggit32** [comment]
@SergeVKom this seems like a high priority issue for someone wanting to use Appium 1.5 on Android.  I currently cannot upgrade to 1.5 unless there is a workaround for this.

**Comment by SergeVKom** [comment]
@nuggit32 I'm using 
driver.quit() / new AppiumDriver()
in before class methods, instead of 
driver.closeApp() / driver.launchApp()
it helps, but not a good way. Looking forward the fix. Hope it happens soon.

**Comment by imurchie** [comment]
1.5 is not handling `noReset` correctly. Working on a fix.

**Comment by imurchie** [comment]
If you are running from source, could you update `appium-android-driver` and make sure it is version `appium-android-driver@1.7.4`, then try again?

**Comment by nuggit32** [comment]
I've never ran from source, but willing to give it a try until the new fix comes out.

**Comment by imurchie** [comment]
That would be excellent. Thanks!

**Comment by nuggit32** [comment]
Okay I got the source installed and verified appium-android-driver is 1.7.4 during the npm install.

Started the node up with node .

My sample code:
        cap.setCapability(MobileCapabilityType.DEVICE_NAME,
            context.getCurrentXmlTest().getParameter("realDevice"));
        cap.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, context.getCurrentXmlTest().getParameter("appPackage"));
        cap.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY,
            context.getCurrentXmlTest().getParameter("appActivity"));
        cap.setCapability(AndroidMobileCapabilityType.APP_WAIT_ACTIVITY,
            context.getCurrentXmlTest().getParameter("appWaitActivity"));
        cap.setCapability(MobileCapabilityType.UDID, context.getCurrentXmlTest().getParameter("udid"));
        cap.setCapability(MobileCapabilityType.PLATFORM_NAME, context.getCurrentXmlTest().getParameter("platformName"));
        cap.setCapability(MobileCapabilityType.PLATFORM_VERSION,
            context.getCurrentXmlTest().getParameter("platformVersion"));
        //cap.setCapability(MobileCapabilityType.NO_RESET, true);

        try {
            driver = new AndroidDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), cap);
        } catch (MalformedURLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        ((AppiumDriver<MobileElement>) driver).launchApp();

It is failing on [MJSONWP] Encountered internal error running command: TypeError: path must be a string
Here is a gist of the appium log
https://gist.github.com/nuggit32/e8f89437adc49bb37b75

**Comment by nuggit32** [comment]
So.....I removed driver.lanuchApp() as that appears to be the problem.  I was looking at the driver.js code and   autoLaunch: true.

So launchApp() is not needed? 
When I removed this the app launched and no errors.

**Comment by imurchie** [comment]
Once more, with feeling. All local launch tests work. Can you get `appium-android-driver` 1.7.6 and try?

**Comment by nuggit32** [comment]
@imurchie confirmed 1.7.6 is working properly now.  Thanks alot...Good work!
Will this be released as part of appium 1.5.1?

**Comment by imurchie** [comment]
Yes it will. There are lots of bug fixes in there.

**Comment by SrinivasanTarget** [comment]
@triager please close
