### ISSUE TITLE
not able to install .ipa or .app file on ios simulator 7.1

### ISSUE THREAD

**Issue by automationtesting123** [appium/appium#6275]
## The problem

Hi Can any one help me...!

I am working on automation testing for IOS and i am not able to install .app or .ipa on my ios simulator.
i want to automate the application(ex : watsapp.ipa or watsapp.app)
## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.13(Draco)
* Desktop OS/version used to run Appium: Maveric OS X 10.9.3
* Node.js version (unless using Appium.app|exe):3.6.0
* Mobile platform/version under test: Xcode 5.1.1
* Real device or emulator/simulator: IOS simulator 7.1

## Details

I need to automate the an ios application(ex : watsapp) and i am unable to launch the application on xcode 5.1.1 simulator 7.1.

please help me how to launch the app.

## Code To Reproduce Issue [ Good To Have ]

 DesiredCapabilities cap = new DesiredCapabilities();
                  cap.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);
cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, "7.1");
                  cap.setCapability("appium-version", "1.4");
appDriver  = new IOSDriver(new URL(hostUrl), cap);
                   appDriver.installApp("/Users/automationuser/Desktop/LMS1.0.app");

**Comment by imurchie** [comment]
Is this your app? For a simulator it needs to be a simulator build of the application. For a real device it needs to be built with a development identity and provisioning profile.

**Comment by automationtesting123** [comment]
@imurchie 
Can't we install .ipa file on ios simulator?

**Comment by imurchie** [comment]
No. Apple won't allow it.

**Comment by automationtesting123** [comment]
@imurchie 
Ok, can we install .ipa file into iphone through appium?
I am using iphone 5s 8.3 and i am able to install my .ipa file but not able to launch it through appium?

**Comment by imurchie** [comment]
Is it an `ipa` that you built? As I said above, it needs to be built with a developer identity and provisioning profile. It **cannot** be a production app.

**Comment by automationtesting123** [comment]
@imurchie 
no i have not built the ipa.
can you help me how to automate the ios testing?

**Comment by imurchie** [comment]
You can begin by reading http://appium.io/getting-started.html?lang=en

That should get you started.

**Comment by automationtesting123** [comment]
i am able to install ipa file into my real device(iphone 5s) but not able to launch it.

**Comment by imurchie** [comment]
Again, it needs to be signed by a developer identity. It **cannot** be a downloaded app that you don't own. Apple will not allow it.

**Comment by automationtesting123** [comment]
Thank you, but I have downloaded .ipa file and i am able to install from command line tools into my real device.

**Comment by imurchie** [comment]
Yes. But you **cannot** automate it. Appium won't be able to because Apple will not do it.

**Comment by automationtesting123** [comment]
ok but is there any other way to automate my application?

**Comment by imurchie** [comment]
If it is _your_ application (i.e., one that you have access to in order to build) then it will work.

**Comment by automationtesting123** [comment]
Hi i do not have .app file or source code
how to check   app is signed with valid developer provisioning profile

**Comment by saikrishna321** [comment]
@automationtesting123 hope this thread helps 

http://stackoverflow.com/questions/14881126/how-to-tell-what-profile-signing-certificate-was-used-to-sign-ipa

**Comment by automationtesting123** [comment]
@saikrishna321 

Thanks saikrishna.

do i need to pass .ipa path in  (path_to_your_provisioning_profile)
security cms -D -i (path_to_your_provisioning_profile)

**Comment by saikrishna321** [comment]
@automationtesting123 i guess i haven't used this ..  an easy way check this https://github.com/nomad/shenzhen

**Comment by automationtesting123** [comment]
can any one help me on the below question.
Can we install .ipa file directly into either IOS simulator or IPhone by using Appium.app?

**Comment by imurchie** [comment]
Not if it is a production app. If you downloaded it from a vendor, it is most likely a production app, and Appium cannot be used for it.

**Comment by automationtesting123** [comment]
So can't we re-sign the developer identity?if so suggest me a solution?

**Comment by imurchie** [comment]
No. You need the source code.

**Comment by saikrishna321** [comment]
@automationtesting123  

1. You cannot resign a .ipa if the build is release build ( which is production app)
2. You can resign a .ipa if the build is debug build(which is a test app)

@imurchie thoughts ?

**Comment by imurchie** [comment]
I think that is correct, yes.

**Comment by automationtesting123** [comment]
then in this case i cannot automate the app

**Comment by saikrishna321** [comment]
@automationtesting123 ask them to provide you a debug build with provision profile holding your device UDID.

**Comment by automationtesting123** [comment]
@saikrishna321 Thank you.

**Comment by automationtesting123** [comment]
@imurchie  @saikrishna321 Thank you guys.

**Comment by SJ2020** [comment]
Hi Guys , I am new to iOS Automation testing , I am also stuck with same problem where I am receiving .ipa file from developer, As suggested in this thread I need to ask for debug build with my provisioning id(that is xcodeOrgId = 10 digit number, correct?) , Once i received debug build(Assuming it is .ipa file), how to do i open the same with Appium.app to inspect elements . I would appreciate your reply.
