### ISSUE TITLE
【Solved】grid node register to hub server in infinite loop

### ISSUE THREAD

**Issue by lucyking** [appium/appium#6278]
### ---> I've found the key to this question
 - that's just due to I forget modify the host address in JSON.
modify ```"host":"127.0.0.1"``` to```"host":"10.240.128.210"```,then everything goes well.

- but it's not easy for we newbee to find the failure msg.
( I used WebStorm to debug Appium.js step by step :joy: )

- may we can print debug info when register fail #6283 

![crime scene](https://raw.githubusercontent.com/lucyking/pic/master/IMG_20160314_195050.jpg)

==================================
## The problem
We try to set up a appium grid server because we have lots of devices. 
- In Windows,everything goes well.
- But in Linux && Mac, when the node has registered to hub already,the callback value is still **false**,
that lead to the node register to server **again and again**.
That is very dreadful,because a running session always be override by the new register. 

## Environment

* Appium version (or git revision) that exhibits the issue:   1.5.0  && 1.4.16 
* Last Appium version that did not exhibit the issue (if applicable):   NONE
* Desktop OS/version used to run Appium:   Ubuntu LTS 14.10.3  /   Mac 10.10.5 
* Node.js version (unless using Appium.app|exe): win7 (4.2.2) / Ubuntu(node 5.7.0)  /  Mac (node 0.12.7)  
* Real device or emulator/simulator: Real devices

### log
- hub:
    - java -jar selenium-server-standalone-2.47.1.jar -port 4444 -role hub

- node:
    - appium --nodeconfig   [samsung5.json](https://gist.github.com/lucyking/497160305319c7392e1d) -p 4725 -U 3xxxaec -bp 8888

### on Linux
![while1](https://raw.githubusercontent.com/lucyking/pic/master/reg-while1.png)

### modify the grid-register.js to print above debug info 
![1](https://raw.githubusercontent.com/lucyking/pic/master/grid-register3.png)
![2](https://raw.githubusercontent.com/lucyking/pic/master/grid-register4.png)

### ps
- if using **return cb(true)** the register will work seems well,but it‘s a temporary expedient && not safe.

**Comment by SrinivasanTarget** [comment]
@triager please close
