### ISSUE TITLE
Send Application to background and bring back to foreground not working on Appium 1.4.16 and IOS 9.2

### ISSUE THREAD

**Issue by Prasant-Sutaria** [appium/appium#6280]
## The problem

We have an IOS native app, we have certain scenario in which we send the application on background for say 20 secs and then bring it back to foreground.

We are using appium's inbuilt method driver.runAppInBackground(durationInSeconds)

The application goes to background as expected but while bringing the application back to foreground appium fails.
## Environment

We are using:
Appium 1.4.16 on SauceLabs
IOS version 9.2
iPhone 5s Simulator
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Appium Log : https://gist.github.com/Prasant-Sutaria/764831a9921c59211f4e
## Code To Reproduce Issue [ Good To Have ]

try{
     driver.runAppInBackground(durationInSeconds);
}catch(Exception e){
}

**Comment by scottdixon** [comment]
This is a known issue as of iOS9 - I think @imurchie implemented a solution in Appium 1.5

**Comment by imurchie** [comment]
The background logic is indeed significantly changed in 1.5. I would try it there, and if it is still a problem we can figure out the solution.

**Comment by igalep** [comment]
Hi , 

I've same issue as well , any update on this one ?

**Comment by imurchie** [comment]
Is the issue in Appium 1.5? If so, could you post the server logs?
