### ISSUE TITLE
Unable to obtain password attribute

### ISSUE THREAD

**Issue by mbknieri** [appium/appium#6281]
## The problem

When I attempt to obtain the password attribute, Appium responds with an error that the element can not be located.

When viewing the element using the Appium inspector, it is clear that the element does have the password attribute:

<img width="285" alt="screen shot 2016-03-14 at 2 55 53 pm" src="https://cloud.githubusercontent.com/assets/3682651/13756215/3cc373d4-e9f5-11e5-9667-9d4028a361f7.png">
## Environment

Appium version: v1.4.13, v1.4.16
Desktop OS: Yosemite v10.10.5
Node.js Version: v4.2.3
Mobile Platform: Android
Emulator: Genymotion, Samsung Galaxy S6 - 6.0.0 - API 23
Noticed error on both Appium CLI and Appium.app
## Link to Appium logs

Can not post full log on gist. Here is the log output from where the error occurred:

```
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"xpath","selector":"//android.view.View[2]/android.widget.EditText[1]","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.view.View[2]/android.widget.EditText[1]","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding //android.view.View[2]/android.widget.EditText[1] using XPATH with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CLASS=android.widget.EditText, INSTANCE=1]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"18"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"18"},"sessionId":"6aeafb9b-f259-495a-8e58-c03eec0cf737"}
info: <-- POST /wd/hub/session/6aeafb9b-f259-495a-8e58-c03eec0cf737/element 200 1471.686 ms - 88 {"status":0,"value":{"ELEMENT":"18"},"sessionId":"6aeafb9b-f259-495a-8e58-c03eec0cf737"}
info: --> GET /wd/hub/session/6aeafb9b-f259-495a-8e58-c03eec0cf737/element/18/attribute/password {}
info: [debug] Pushing command to appium work queue: ["element:getAttribute",{"elementId":"18","attribute":"password"}]
info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":"This element does not have the 'password' attribute"},"sessionId":"6aeafb9b-f259-495a-8e58-c03eec0cf737"}
info: <-- GET /wd/hub/session/6aeafb9b-f259-495a-8e58-c03eec0cf737/element/18/attribute/password 500 2.976 ms - 230 
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getAttribute","params":{"elementId":"18","attribute":"password"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getAttribute
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":7,"value":"This element does not have the 'password' attribute"}
info: --> DELETE /wd/hub/session/6aeafb9b-f259-495a-8e58-c03eec0cf737 {}
info: Shutting down appium session
```

## Code To Reproduce Issue [ Good To Have ]

used java-client's .getAttribute("password") on a WebElement.

**Comment by imurchie** [comment]
There is currently no way to pull this information. I'm not sure where the .app is getting this from.

If it is a WebElement you might be able to change contexts and get the information.

**Comment by mbknieri** [comment]
I looked at the implementation for Appium.app. It looks like the attribute is obtained from the last page source's xml response. I hit the Refresh button in the Appium inspector and saw that the server response did provide the password attribute:

<android.widget.EditText index=\"1\" text=\"\" class=\"android.widget.EditText\" package=\"\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"true\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"true\" selected=\"false\" bounds=\"[52,788][1388,944]\" resource-id=\"\" instance=\"1\"\/>

If I understand your response correctly, there is currently not a way to obtain this attribute from the server even though it is provided in the xml response after getting the page source? I am able to get other attributes for the element (ex. getAttribute("resource-id") works).

**Comment by imurchie** [comment]
Ah. Ok, it is just parsing the XML, then. The `getAttribute` method queries the device for the information, and the device does allow us to check for password. It seems like you'll have to get the source and find your element in there.

The attributes that can be retrieved directly can be found here:

booleans: https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/io/appium/android/bootstrap/AndroidElement.java#L94-L121

strings: https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/io/appium/android/bootstrap/AndroidElement.java#L182-L202

**Comment by gluxhappy** [comment]
Does this issue solved?  
I have the same issue now, and i am trying to find a solution.

**Comment by darya1844** [comment]
I have the same problem and would be glad to get any solution.

**Comment by Yelisey** [comment]
Please, fix this bug/issue-bug..

**Comment by Carlgege** [comment]
@sravanmedarapu @mykola-mokhnach @imurchie 
I have solved this issue after update the UiObject2Element from the source code of uiautomator2 server
(appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\app\src).

```java

public boolean getBoolAttribute(final String attr) throws UiObjectNotFoundException, NoAttributeFoundException, UiAutomator2Exception {
        boolean res;
        if ("enabled".equals(attr)) {
            res = element.isEnabled();
        } else if ("checkable".equals(attr)) {
            res = element.isCheckable();
        } else if ("checked".equals(attr)) {
            res = element.isChecked();
        } else if ("clickable".equals(attr)) {
            res = element.isClickable();
        } else if ("focusable".equals(attr)) {
            res = element.isFocusable();
        } else if ("focused".equals(attr)) {
            res = element.isFocused();
        } else if ("longClickable".equals(attr)) {
            res = element.isLongClickable();
        } else if ("scrollable".equals(attr)) {
            res = element.isScrollable();
        } else if ("selected".equals(attr)) {
            res = element.isSelected();
        } else if ("displayed".equals(attr)) {
            res = invoke(method(UiObject2.class, "getAccessibilityNodeInfo"), element) != null ? true : false;
        } else if ("password".equals(attr)) {
            res = AccessibilityNodeInfoGetter.fromUiObject(element).isPassword();
        }  else {
            throw new NoAttributeFoundException(attr);
        }
        return res;
    } 

```

**Comment by mykola-mokhnach** [comment]
You are welcome to create a PR containing your fix ;)

Here you can find server source: https://github.com/appium/appium-uiautomator2-server

**Comment by jlipps** [comment]
@Carlgege yes, please do submit a PR!

**Comment by mykola-mokhnach** [comment]
Closed as fixed
