### ISSUE TITLE
Scroll down not working in android

### ISSUE THREAD

**Issue by prolificcoder** [appium/appium#6282]
## The problem

As per @scottdixon creating a issue
Client code
`driver.execute("mobile: scroll", [{direction: 'down'}])` 
is giving error

``` shell
[[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[HTTP] --> POST /wd/hub/session/47d2280f-4948-440b-a39e-d6ffc0cb67fd/execute
[MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: scroll",[{"direction":"down"}],"47d2280f-4948-440b-a39e-d6ffc0cb67fd"]
[HTTP] <-- POST /wd/hub/session/47d2280f-4948-440b-a39e-d6ffc0cb67fd/execute 501 2 ms - 122
[HTTP] --> DELETE /wd/hub/session/47d2280f-4948-440b-a39e-d6ffc0cb67fd
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["47d2280f-4948-440b-a39e-d6ffc0cb67fd"]
[debug] [AndroidDriver] Shutting down Android driver
[debug] [ADB] Getting connected devices...]
```
## Environment
- 1.5 latest e8d41945f1035e9fa4a560b914e9bb51b2569faa
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: Android
- Real device or emulator/simulator: Genymotion Android 5 emulator
- Appium CLI or Appium.app|exe:
## Details

Tried other methods of scrolling too and they are flaky at best - eg: https://discuss.appium.io/t/unable-to-perform-drag-on-genymotion-android-5-1-emulator/9057
## Link to Appium logs

gist of appium log https://gist.github.com/prolificcoder/88df05be9ad9c28e51e3

**Comment by prolificcoder** [comment]
This test though passed locally seems out of date - https://github.com/appium/sample-code/blob/master/sample-code/examples/node/android-complex.js#L75
also it failed on saucelabs - https://saucelabs.com/beta/tests/c4a7be3705c04eb99e5e1a7f9ac3b56b/watch

**Comment by prolificcoder** [comment]
I also ran this in appium 1.4.16 and got an error (though a different one)

`nfo: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"e63c4d7d-7da7-4e71-91a1-755687a957b6"}
info: <-- POST /wd/hub/session/e63c4d7d-7da7-4e71-91a1-755687a957b6/element/2/click 200 159.055 ms - 76 {"status":0,"value":true,"sessionId":"e63c4d7d-7da7-4e71-91a1-755687a957b6"}
info: --> POST /wd/hub/session/e63c4d7d-7da7-4e71-91a1-755687a957b6/execute {"script":"mobile: scroll","args":[{"direction":"down"}]}
info: <-- POST /wd/hub/session/e63c4d7d-7da7-4e71-91a1-755687a957b6/execute 500 2.798 ms - 74
TypeError: cb is not a function
    at [object Object].androidController.scroll (/Users/smalugu/code/exp/appium/lib/devices/android/android-controller.js:690:3)
    at Object.exports.mobileScroll [as scroll] (/Users/smalugu/code/exp/appium/lib/server/controller.js:645:14)
    at Object.exports.executeMobileMethod (/Users/smalugu/code/exp/appium/lib/server/controller.js:984:22)
    at exports.execute (/Users/smalugu/code/exp/appium/lib/server/controller.js:940:15)`

full log - https://gist.github.com/prolificcoder/13cdd2b648127f58b12b

**Comment by prolificcoder** [comment]
After the issue is fixed an wd based e2e test in sample code will be much appreciated

**Comment by prolificcoder** [comment]
Created a PR with a workaround -https://github.com/appium/sample-code/pull/75

**Comment by dmydry** [comment]
is there any update on this issue guys?

**Comment by SrinivasanTarget** [comment]
https://github.com/mykola-mokhnach/appium/blob/75df4b9856c01b98a7073712303a6fa60ff6f791/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md
