### ISSUE TITLE
check_response return keyerror KeyError: '\'message\'\n

### ISSUE THREAD

**Issue by camillake** [appium/appium#6284]
## The problem

After finding element, I got KeyError exception.

## Environment

* Appium version (or git revision) that exhibits the issue:1.4.16
* Desktop OS/version used to run Appium: Mac 10.11.2
* Node.js version (unless using Appium.app|exe): 5.7.0
* Mobile platform/version under test: iPad/ iOS 8.4.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: python 3.4

## Details
This doesn't not happen every time. 

##  Appium logs
 
   lambda driver: driver.find_element(self.how_to, locator_key))
   lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 712, in find_element
    {'using': by, 'value': value})['value']
  lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  lib/python3.4/site-packages/appium/webdriver/errorhandler.py", line 24, in check_response
    super(MobileErrorHandler, self).check_response(response)
  lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 104, in check_response
    message = value['message']
KeyError: '\'message\'\n

## Appium server logs

2016-03-16 02:36:33:565 - info: [debug] [INST] 2016-03-16 02:36:33 +0000 Fail: The target application appears to have died

https://gist.github.com/camillake/7cc65caa06de760c6d8a

**Comment by imurchie** [comment]
Can you provide the Appium server logs (as a [gist](https://gist.github.com/)) so we can see what the server is responding with, that the client doesn't like.

Trying to reproduce with Appium 1.5 would be excellent, too.

**Comment by camillake** [comment]
@imurchie 
I upload the server log.

I couldn't upgrade to Appium 1.5 now because I have to test the new environment before I upgrade it.

**Comment by imurchie** [comment]
Sorry, I missed this.

Is this error consistent? The app seems to have crashed. The next step I guess would be to look at the iOS system logs and crash logs to see what the problem is.

**Comment by camillake** [comment]
HI @imurchie ,
Thanks for your reply.
I think Appium server should handle it if no response is sent from instruments instead of throw KeyError exception.
What do you think?

**Comment by imurchie** [comment]
The `KeyError` is not being thrown by the server. The server is returning a 404 response, because the session has crashed and is no longer available, and the client is not handling that correctly.

**Comment by camillake** [comment]
Hi @imurchie 
I got it.
Thanks a lot.
