### ISSUE TITLE
[Appium 1.5] --full-reset on iOS devices is only a modify.

### ISSUE THREAD

**Issue by rokly** [appium/appium#6287]
Hi,
If i start an appium ios test with --full-reset , the appium servers performs only an modifiy. The app will not be removed and new installed.
This is a problem for me because login data from the last user will not be resetted and so i can't test with another user.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.0
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: OS X El Capitan
* Node.js version (unless using Appium.app|exe): v4.2.0
* Mobile platform/version under test: iOS 9.2.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

I found in the appium logs this:
> [iOSLog] [IOS_SYSLOG_ROW] Mar 15 15:39:30 iPhone-5-92-3053 SpringBoard[235] <Warning>: Installed apps did change.
[iOSLog] [IOS_SYSLOG_ROW] Added: {(
[iOSLog] [IOS_SYSLOG_ROW] )}
[iOSLog] [IOS_SYSLOG_ROW] Removed: {(
[iOSLog] [IOS_SYSLOG_ROW] )}
[iOSLog] [IOS_SYSLOG_ROW] Modified: {(
[iOSLog] [IOS_SYSLOG_ROW] "Bundle.ID"
[iOSLog] [IOS_SYSLOG_ROW] )}

but i think it should be something likr that:

> [iOSLog] [IOS_SYSLOG_ROW] Mar 15 15:39:30 iPhone-5-92-3053 SpringBoard[235] <Warning>: Installed apps did change.
[iOSLog] [IOS_SYSLOG_ROW] Added: {(
[iOSLog] [IOS_SYSLOG_ROW] )}
[iOSLog] [IOS_SYSLOG_ROW] Removed: {(
[iOSLog] [IOS_SYSLOG_ROW] "Bundle.ID"
[iOSLog] [IOS_SYSLOG_ROW] )}
[iOSLog] [IOS_SYSLOG_ROW] Modified: {(
[iOSLog] [IOS_SYSLOG_ROW] )}

## Link to Appium logs
[https://gist.github.com/rokly/4e1feb759757c66a95aa](url)

Thanks for helping

**Comment by HlebHalkouski** [comment]
[Linked](https://github.com/appium/appium/issues/6206)

**Comment by rokly** [comment]
Thanks for linking.
