### ISSUE TITLE
Problem with flick when trying to perform it using ADMC wd.io implementation on Node.js

### ISSUE THREAD

**Issue by SwinX** [appium/appium#6289]
## The problem

Working on flick implementation in [Gemini UI automation framework](https://github.com/gemini-testing/gemini). As JSON Wire client library gemini uses [wd.io](https://github.com/admc/wd).
When trying to perform general flick on web page (without specifying element to flick on) getting error `Selenium error: unknown error: element identifier must be a string`
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5
- Last Appium version that did not exhibit the issue (if applicable): None
- Desktop OS/version used to run Appium: Mac OS X 10.11.2
- Node.js version (unless using Appium.app|exe): 5.5.0
- Mobile platform/version under test: Android 4.4
- Real device or emulator/simulator: Simulator 
- Appium CLI or Appium.app|exe: `./node_modules/.bin/appium -p 4721 -U emulator-5554 --nodeconfig ~/Documents/appium-test/appium.json`
## Details

After brief source code search I got that my flick requests are not coming to `appium-android-driver`, but being proxied to somewhere (???) (btw it would be nice if you will point how this actually works and where requests are being actually proxied). 
If I do appium code modifications and force all flick requests to be dispatched to `appium-android-driver` everything starts working fine.
## Link to Appium logs

https://gist.github.com/SwinX/5ecb7ec1f3e37231ac5f

**Comment by imurchie** [comment]
For a Chrome session, Appium proxies most requests to a ChromeDriver instance that it manages.

If you have made changes that fix the problem, would you consider opening a pull request on `appium-android-driver`?

**Comment by SwinX** [comment]
Unfortunately my fix may not be considered as a solution cause it's just just tweak of logic which determines should HTTP request be proxied or not: all URLs containing `flick` are considered as not proxied and I did this for previous appium version (1.4.x). Also I'm not sure is this really appium problem or not.

May you please take a closer look at this log:
```
[HTTP] --> POST /wd/hub/session/9109c2e5-0d85-4550-8702-23d51127326a/touch/flick 
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/9109c2e5-0d85-4550-8702-23d51127326a/touch/flick] to [POST http://127.0.0.1:9515/wd/hub/session/cc75ee5396ea70af8d622882a64326ec/touch/flick] with body: {"xspeed":500,"yspeed":500}
[JSONWP Proxy] Got response with status 200: {"sessionId":"cc75ee5396ea70af8d622882a64326ec","status":13,"value":{"message":"unknown error: element identifier must be a string\n  (Session info: chrome=48.0.2564.95)\n  (Driver info: chromedriv...
[JSONWP Proxy] Replacing sessionId cc75ee5396ea70af8d622882a64326ec with 9109c2e5-0d85-4550-8702-23d51127326a
[HTTP] <-- POST /wd/hub/session/9109c2e5-0d85-4550-8702-23d51127326a/touch/flick 200 202 ms - 295 
```
This is what actually being sent by wdio to appium and appium's response. I have few questions about this:
Is wdio build URL correctly?
Are params being sent correctly? 
Is this enough params for appium to do a flick in browser?

You told that most requests are being proxied to ChromeDriver. But why any flick request should be proxied to ChromeDriver in general? I know that this method is being declared in [spec](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidtouchflick) so ChromeDriver has to implement it, but shouldn't appium take care about flicks?

P.S. about proxying requests - am I understood right that for a Chrome session requests are being proxied to ChromeDriver if needed and this is all? So in general scheme looks something like this:
`Express server -> Request router -> Chrome driver or Appium` ?

**Comment by SwinX** [comment]
After further research I came to following results:
ChromeDriver shipped with appium fails requests for flicking on screen without elements. Result - it returns error `unknown error: element identifier must be a string`. Example: 
```
[HTTP] --> POST /wd/hub/session/b7904b67-7295-42c8-b999-46a31b40442d/touch/flick 
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/b7904b67-7295-42c8-b999-46a31b40442d/touch/flick] to [POST http://127.0.0.1:9515/wd/hub/session/490715bd12129a9f2aa52d0726fb2bb3/touch/flick] with body: {"xspeed":500,"yspeed":500}
[JSONWP Proxy] Got response with status 200: {"sessionId":"490715bd12129a9f2aa52d0726fb2bb3","status":13,"value":{"message":"unknown error: element identifier must be a string\n  (Session info: chrome=48.0.2564.95)\n  (Driver info: chromedriv...
[JSONWP Proxy] Replacing sessionId 490715bd12129a9f2aa52d0726fb2bb3 with b7904b67-7295-42c8-b999-46a31b40442d
[HTTP] <-- POST /wd/hub/session/b7904b67-7295-42c8-b999-46a31b40442d/touch/flick 200 176 ms - 295 
```
Attempt to do workaround using touch actions got no success too always returning `Selenium error: Method has not yet been implemented`. Example: 
```
[HTTP] --> POST /wd/hub/session/fb527605-a7f5-46e6-a6d1-138bdb975680/touch/perform 
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"speed":500,"offsets":{"x":0,"y":0}}}],"fb527605-a7f5-46e6-a6d1-138bdb975680"]
[HTTP] <-- POST /wd/hub/session/fb527605-a7f5-46e6-a6d1-138bdb975680/touch/perform 501 3 ms - 122
```
3. Attempt to do flick on some element on a page led to error `[flick(".button-round .button_state_radio",0,0,500)] Error response status: 10, StaleElementReference - An element command failed because the referenced element is no longer attached to the DOM. Selenium error: stale element reference: element is not attached to the page document`

So it seems that either flicks are completely broken in web context or I do something wrong. Seems second much more probable than first so any advice here will be really nice to have.

**Comment by SwinX** [comment]
:up: guys any suggestions ?

**Comment by jlipps** [comment]
@SwinX sorry for the long delay here. If you get latest Appium (1.6.3) does it still exhibit this issue?
