### ISSUE TITLE
Java client swipe() methods not working with 1.5

### ISSUE THREAD

**Issue by marcallenbetts** [appium/appium#6292]
## The problem

Java client swipe() methods are not working after upgrade to 1.5. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5
* Last Appium version that did not exhibit the issue (if applicable): 14.13
* Desktop OS/version used to run Appium: 
* Node.js version (unless using Appium.app|exe): 1.5
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs
[Link to Appium log](https://gist.github.com/marcallenbetts/a9646be204c1db0c243b)

## Code To Reproduce Issue [ Good To Have ]
`AppiumDriver<?> driver = new IOSDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), dc);
MobileElement me = (MobileElement) driver.findElement(By.id("myElement"));
me.swipe(SwipeElementDirection.LEFT, 1000);`

**Comment by imurchie** [comment]
Can you provide the server logs for the call, so we can see what it is trying to do on the server side? Thanks.

**Comment by scottdixon** [comment]
Depending on how the java client handles swipe, this _might_ be related to #6257

**Comment by marcallenbetts** [comment]
@imurchie Updated with log. Sorry about that; I thought I added them the first time.

**Comment by imurchie** [comment]
@scottdixon it looks like it is related. :(

**Comment by SrinivasanTarget** [comment]
This has been fixed in https://github.com/appium/java-client/commit/5da85f818d9bfd04b8be7aa7e38ecbcccd72e16c

Please wait for an 4.0 java client to be released or you can use a snapshot attached here https://github.com/appium/java-client/issues/350.

**Comment by SrinivasanTarget** [comment]
@triager please close
