### ISSUE TITLE
[Appium 1.5] UIATextField elements Disappearing from DOM (native app; iOS 9.2)

### ISSUE THREAD

**Issue by pappy-o** [appium/appium#6293]
## The problem

There is a view in this target app that has 15+ input fields (it's creating a user record with complete address information, etc.). There are 2-3 UIATextFields that no longer appear in the DOM after entering data into a few fields above, which means a NoSuchElement is thrown when I try to .setValue() in those fields.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5
- Node.js version: 5.8.0
- Mobile platform/version under test: iOS 9.2
- Real device or emulator/simulator: Sim (iPhone 6)
- Appium CLI or Appium.app|exe: CLI (all default server caps)
## Details

The parent UIATableCell elements that house the text fields are still there (along with the UIAStaticText element that is the label), but the text fields themselves are gone. If I add a sleep to the code being run, I'm still able to interact with those text fields as usual manually (clicking in them with the mouse and entering values); they just don't appear in the xml tree.

I tried to trick it into working by changing the order around, but inevitably, the last fields that are to be entered get dropped (regardless of which fields they are).

I've read in other issues about the xml tree being automatically compressed (usually in reference to android issues); I'm wondering if this might be what is going on here. Does Appium remove elements from the tree if they don't have any assigned attributes after a certain period of time?
## Link to Appium logs

These currently have sensitive/personal info in them; I can try to clean them up if they are necessary. I can also try to repro if someone has a sample app with a bunch (more than 15) of input fields in a single view. 
## Additional References

Check these out. That Address Line 2 field is one of the two that is prone to disappearing. The first image is an excerpt from the page source when I first navigate to the screen. The second is the same section from the page source after entering data into 3 fields, including the Address Line 1 line (blue blacked out) (notice that the UIATableCell and UIAStaticText are still there; just not the input field).

![now you see me](https://cloud.githubusercontent.com/assets/11673106/13821516/6026e84a-eb78-11e5-8c30-7d963c71933e.png)

<img width="1052" alt="now you don t" src="https://cloud.githubusercontent.com/assets/11673106/13823343/8e2b675a-eb7f-11e5-9a51-bf653443765d.png">

**Comment by dpgraham** [comment]
Closing issue. Please re-open if this is still a problem.
