### ISSUE TITLE
appium crashed after test 3~4hours

### ISSUE THREAD

**Issue by yisake** [appium/appium#6298]
Appium crashed after works 3~4 hours, what log should I collect to upload?

below is the logs:

---

<--- Last few GCs --->

38244392 ms: Mark-sweep 1398.7 (1456.9) -> 1398.5 (1456.9) MB, 51.4 / 0 ms (+ 19
5.0 ms in 20 steps since start of marking, biggest step 111.0 ms) [allocation fa
ilure] [GC in old space requested].
38244653 ms: Mark-sweep 1398.5 (1456.9) -> 1398.5 (1456.9) MB, 257.5 / 0 ms [las
t resort gc].
38244945 ms: Mark-sweep 1398.5 (1456.9) -> 1398.0 (1456.9) MB, 291.7 / 0 ms [las
t resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

```
2: arguments adaptor frame: 3->2
```

==== Details ================================================

[2]: arguments adaptor frame: 3->2 {
  // actual arguments
  [00] : 20509
  [01] : 00000381304B0EE9 <an Uint8Array with map 000002F2F2C72A49>
  [02] : 0000038130404131 <undefined>  // not passed to callee
}
# 

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!
## Environment
- Appium version (or git revision) that exhibits the issue:
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by scottdixon** [comment]
Please provide your Appium server logs as a [gist](http://gist.github.com).

**Comment by yisake** [comment]
Where can I fount the log mentioned by you? I've attach the log in cmd.exe.

**Comment by SrinivasanTarget** [comment]
Yes @yisake Also give us more description for the issue in above template.

**Comment by yisake** [comment]
I just have the log from console(cmd.exe) in windows.
So I need to know where is the appium log and I can upload.

**Comment by SrinivasanTarget** [comment]
Please share the full logs from your terminal in form of gist as the above logs are not enough to replicate your issue.

**Comment by omoskovko** [comment]
Hi @scottdixon and @SrinivasanTarget 

I have the same issue.

Appium log you can find by following link:
https://gist.github.com/omoskovko/4b8f145aff23a9a0c6461eaa40a2f8ea

**Comment by rkavalap** [comment]
webdriver call before failure: /wd/hub/session/3d8f3290-ff26-4488-9be6-1b01b22c1fc5/source {}

instance=\"10\"><android.widget.RelativeLayout index=\"0\" text=\"\" class
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
./run-Android.sh: line 8: 24140 Abort trap: 6           '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --address $ZM_IP --command-timeout "17200" --debug-log-spacing --automation-name "Appium" --platform-name "Android" --platform-version "4.4" --app $ZM_APP --full-reset --app-pkg "com.zultys.mobiledroid" --app-activity ".view.activities.StartActivity" --device-name "Nexus 4"

**Comment by tccyp001** [comment]
saw the same issue  in appium 1.6.5 yesterday,  will try to run it today and get the log.
