### ISSUE TITLE
driver.swipe doesn't work on appium 1.5.0

### ISSUE THREAD

**Issue by royanghami** [appium/appium#6299]
## The problem

swiping is not working  

## Environment

* Appium 1.5.0
* Appium 1.4.16
* SauceLabs 
* SauceLabs
* iOS 9.1
* Simulator

## Details

i'm trying to swipe between 2 points (2 points are in the bounds of the screen)

## Link to Appium logs

https://gist.github.com/royanghami/2cd793ac76b2b71bd63b

## Code To Reproduce Issue [ Good To Have ]

Java-Client
driver.swipe(100, 300, 100, 100, 1000);

**Comment by SrinivasanTarget** [comment]
#6292

**Comment by danqa** [comment]
I am having the same issue using appium_lib with ruby. Possibly related?

**Comment by SrinivasanTarget** [comment]
please log the same in https://github.com/appium/ruby_lib/issues with latest log.

**Comment by SrinivasanTarget** [comment]
@triager please close
