### ISSUE TITLE
appium crashed again

### ISSUE THREAD

**Issue by yisake** [appium/appium#6303]
appium crashed with ver1.14.6

**attach crash logs
<--- Last few GCs --->

23967227 ms: Mark-sweep 1391.4 (1456.9) -> 1391.1 (1456.9) MB, 273.5 / 0 ms [las
t resort gc].
23967229 ms: Scavenge 1391.1 (1456.9) -> 1391.1 (1456.9) MB, 0.7 / 0 ms [allocat
ion failure].
23967229 ms: Scavenge 1391.1 (1456.9) -> 1391.1 (1456.9) MB, 0.6 / 0 ms [allocat
ion failure].
23967512 ms: Mark-sweep 1391.1 (1456.9) -> 1391.1 (1456.9) MB, 282.1 / 0 ms [las
t resort gc].
23967783 ms: Mark-sweep 1391.1 (1456.9) -> 1391.1 (1456.9) MB, 270.5 / 0 ms [las
t resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000038A2C7373A9 <JS Object>
    1: slowToString [buffer.js:348] [pc=000003FF0C1BF6D5] (this=0000017A7B8FE831
 <an Uint8Array with map 000002D8FAE3C0D1>,encoding=0000038A2C7AA2D1 <String[4]:
 utf8>,start=0,end=65632)
    2: toString [buffer.js:~375] [pc=000003FF0E26AA05] (this=0000017A7B8FE831 <a
n Uint8Array with map 000002D8FAE3C0D1>)
    3: arguments adaptor frame: 3->0
    4: write [string_decoder.js:129] [pc=000003FF0E...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

**Comment by yisake** [comment]
I run the test on Genymotion android simulator.

**Comment by SrinivasanTarget** [comment]
@yisake try a latest version of appium through 'npm install -g appium'.  And still if you face any issues raise it with logs in form of gist.

**Comment by SrinivasanTarget** [comment]
@triager please close
