### ISSUE TITLE
Logcat Terminate issue on Android, Appium 1.4.13

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#6308]
## The problem

Logcat Terminate error while running tests on Android
## Environment

Android 5.02
Appium 1.4.13
## Details

Appium console shows logcat terminate error randomly.
## Link to Appium logs

nfo: [debug] Logcat terminated with code 0, signal null
info: [debug] UiAutomator exited
info: [debug] executing cmd: /Users/venkateshsingh/android/platform-tools/adb -s ZX1D63MDJ7 shell "echo 'ping'"
info: error sending command, reconnecting device and retrying: shell "echo 'ping'"
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/venkateshsingh/android/platform-tools/adb -s ZX1D63MDJ7 devices
info: [debug] 0 device(s) connected
info: [debug] Could not find devices, restarting adb server...
info: [debug] executing cmd: /Users/venkateshsingh/android/platform-tools/adb -s ZX1D63MDJ7 kill-server
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Users/venkateshsingh/android/platform-tools/adb -s ZX1D63MDJ7 devices
info: [debug] 1 device(s) connected
info: [debug] executing cmd: /Users/venkateshsingh/android/platform-tools/adb -s ZX1D63MDJ7 "shell \"echo 'ping'\""
info: [debug] Error: Command failed: /bin/sh -c /Users/venkateshsingh/android/platform-tools/adb -s ZX1D63MDJ7 "shell \"echo 'ping'\”"

**Comment by imurchie** [comment]
Can you provide _more_ of the server logs? 

It would also be good to upgrade to a newer version of Appium.
