### ISSUE TITLE
Appium 1.5.0 cannot start on IOS

### ISSUE THREAD

**Issue by sehandane** [appium/appium#6309]
Hi all,

While starting I got some error below:
1.Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
2. Error: Command 'xcrun simctl erase DA38E3FF-F1FF-48E1-9530-21739B7A7A9F' timed out after 2000ms
3.  On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
4. Error launching instruments: Instruments never checked in

I'm using
* Appium version: 1.5.0
* MAC OS 10.10.5

## Log Detail

[Appium] Welcome to Appium v1.5.0 (REV 4251efa88cc6cc3e937dd2d97cbf745a348d09e8)
[Appium] Non-default server args:
[Appium]   log: '/Users/abcv034/Desktop/Automation/AppiumLog/log.txt'
[Appium]   loglevel: 'info'
[Appium]   defaultCapabilities: { app: '/Users/abcv034/Library/Developer/Xcode/DerivedData/rls-aygsoqskrsylchcnikbkozzzrvav/Build/Products/Debug-iphonesimulator/rls.app',
  newCommandTimeout: 300,
  platformVersion: '9.2',
  browserName: '',
  platformName: 'iOS',
  deviceName: 'iPhone 6s' }
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   app: '/Users/abcv034/Library/Developer/Xcode/DerivedData/rls-aygsoqskrsylchcnikbkozzzrvav/Build/Products/Debug-iphonesimulator/rls.app'
[Appium]   newCommandTimeout: 300
[Appium]   platformVersion: '9.2'
[Appium]   browserName: ''
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6s'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status 
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.0","revision":"4251efa88cc6cc3e937dd2d97cbf745a348d09e8"}}
[HTTP] <-- GET /wd/hub/status 200 24 ms - 121 
Mobile Driver is starting...
[HTTP] --> GET /wd/hub/status 
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.0","revision":"4251efa88cc6cc3e937dd2d97cbf745a348d09e8"}}
[HTTP] <-- GET /wd/hub/status 200 13 ms - 121 
[HTTP] --> GET /wd/hub/status 
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.0","revision":"4251efa88cc6cc3e937dd2d97cbf745a348d09e8"}}
[HTTP] <-- GET /wd/hub/status 200 18 ms - 121 
[HTTP] --> POST /wd/hub/session 
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/abcv034/Library/Developer/Xcode/DerivedData/rls-aygsoqskrsylchcnikbkozzzrvav/Build/Products/Debug-iphonesimulator/rls.app","platfor...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/abcv034/Library/Developer/Xcode/DerivedData/rls-aygsoqskrsylchcnikbkozzzrvav/Build/Products/Debug-iphonesimulator/rls.app'
[Appium]   platformName: 'iOS'
[Appium]   newCommandTimeout: 300
[Appium]   platformVersion: '9.2'
[Appium]   browserName: ''
[Appium]   deviceName: 'iPhone 6s'
[BaseDriver] Session created with session id: d1a256e2-98ef-44a5-b40d-fc1b96b270c7
[BaseDriver] Using local app '/Users/abcv034/Library/Developer/Xcode/DerivedData/rls-aygsoqskrsylchcnikbkozzzrvav/Build/Products/Debug-iphonesimulator/rls.app'
[Appium] Welcome to Appium v1.5.0 (REV 4251efa88cc6cc3e937dd2d97cbf745a348d09e8)
[Appium] Non-default server args:
[Appium]   log: '/Users/abcv034/Desktop/Automation/AppiumLog/log.txt'
[Appium]   loglevel: 'info'
[Appium]   defaultCapabilities: { app: '/Users/abcv034/Library/Developer/Xcode/DerivedData/rls-aygsoqskrsylchcnikbkozzzrvav/Build/Products/Debug-iphonesimulator/rls.app',
  newCommandTimeout: 300,
  platformVersion: '9.2',
  browserName: '',
  platformName: 'iOS',
  deviceName: 'iPhone 6s' }
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   app: '/Users/abcv034/Library/Developer/Xcode/DerivedData/rls-aygsoqskrsylchcnikbkozzzrvav/Build/Products/Debug-iphonesimulator/rls.app'
[Appium]   newCommandTimeout: 300
[Appium]   platformVersion: '9.2'
[Appium]   browserName: ''
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6s'
[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
Error: listen EADDRINUSE 0.0.0.0:4723
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:401:11)
[iOSSim] Retrieving device name string for Xcode version 7.2.1
[iOSSim] Constructing iOS simulator for Xcode version 7.2.1
[iOS] Extracted bundleID: com.abcv.RLS from app: /Users/abcv034/Library/Developer/Xcode/DerivedData/rls-aygsoqskrsylchcnikbkozzzrvav/Build/Products/Debug-iphonesimulator/rls.app
[iOSSim] Cleaning simulator DA38E3FF-F1FF-48E1-9530-21739B7A7A9F
[simctl] Error: Command 'xcrun simctl erase DA38E3FF-F1FF-48E1-9530-21739B7A7A9F' timed out after 2000ms
    at [object Object]._onTimeout (lib/teen_process.js:69:19)
    at Timer.listOnTimeout (timers.js:92:15)
 { [Error: Command 'xcrun simctl erase DA38E3FF-F1FF-48E1-9530-21739B7A7A9F' timed out after 2000ms] stdout: '', stderr: '', code: null }
[Instruments] Launching instruments
[Instruments] On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
[Instruments] Instruments socket client never checked in; timing out (global)
[Instruments] Error launching instruments: Instruments never checked in
[Instruments] Launching instruments
[Instruments] On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
[UIAuto] Instruments is ready to receive commands
[Appium] New IosDriver session created successfully, session d1a256e2-98ef-44a5-b40d-fc1b96b270c7 added to master session list
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takes...
[HTTP] <-- POST /wd/hub/session 200 170001 ms - 760 
[HTTP] --> POST /wd/hub/session/d1a256e2-98ef-44a5-b40d-fc1b96b270c7/timeouts 
[MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",5000,"d1a256e2-98ef-44a5-b40d-fc1b96b270c7"]
[MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/d1a256e2-98ef-44a5-b40d-fc1b96b270c7/timeouts 200 10 ms - 76 
[HTTP] --> POST /wd/hub/session/d1a256e2-98ef-44a5-b40d-fc1b96b270c7/timeouts 
[MJSONWP] Calling AppiumDriver.timeouts() with args: ["page load",500000,"d1a256e2-98ef-44a5-b40d-fc1b96b270c7"]
[MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/d1a256e2-98ef-44a5-b40d-fc1b96b270c7/timeouts 200 5 ms - 76

**Comment by williamrussellajb** [comment]
Exact same error. It's after pulling the latest from git.

**Comment by SrinivasanTarget** [comment]
@williamrussellajb Are the logs same as above or different.Can you paste the logs in form of gist?

**Comment by SrinivasanTarget** [comment]
@williamrussellajb Take a pull and run again.It works fine.

**Comment by makhov** [comment]
I have the same issue, but `appium --no-reset` works fine. Something broken in appium-ios-simulator.

**Comment by makhov** [comment]
```
➜  ~ tail /var/log/system.log
Mar 27 21:05:05 MacBook-Pro-makhov com.apple.CoreSimulator.CoreSimulatorService[775]: Requested phone is is not available for pairing.  Assuming it has the capability.
Mar 27 21:05:05 MacBook-Pro-makhov com.apple.CoreSimulator.CoreSimulatorService[775]: Requested watch is is not available for pairing.  Assuming it has the capability.
```

**Comment by makhov** [comment]
Solved! I had two xcode versions on my Mac. Removing old version and all old simulators solve the problem.

**Comment by sehandane** [comment]
@makhov I have only one Xcode version

**Comment by KBhatti** [comment]
@makhov is this supposed to work now? I am not sure if my instruments-without-delay is working by default or if I need to put in extra commands to make it work. I am using xcode 7.3, Appium 1.5.0. When I launch appium from the command line and attempt to run my maven test Project (whether on Simulator or real device) here is what I see
[debug] [Instruments] Attempting to launch instruments, this is try #1
[Instruments] Launching instruments
[debug] [Instruments] Attempting to run app on iPhone 6s Plus (9.3) [
[Instruments] On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7


Does this mean that my IWD is getting launched automatically every time I run a test (on Simulator or real device). Or is it not running ?


Thanks.

**Comment by SrinivasanTarget** [comment]
@KBhatti https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/iwd_xcode7.md
Check this out
