### ISSUE TITLE
error: Could not set the device type in Info.plist when try to launch for iOS app

### ISSUE THREAD

**Issue by Manasaanand** [appium/appium#6310]
## The problem

Set up everything properly but Appium UI is not launching properly display errror as above. everything seems working good. but unable to run appium UI
## Environment
- Appium version (or git revision) that exhibits the issue: Version 1.4.13 (Draco)
- Last Appium version that did not exhibit the issue (if applicable): Version 1.4.13 (Draco)
- Desktop OS/version used to run Appium: iOSYosemite 10.10.5
- Node.js version (unless using Appium.app|exe): 5.7.0
- Mobile platform/version under test: Simulator 6 9.2 version
- Real device or emulator/simulator:: Simulator an dmobile device both with latest iOS iPhone 5
- Appium CLI or Appium.app|exe::
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --pre-launch --debug-log-spacing --platform-version "9.2" --platform-name "iOS" --app "com.example.apple-samplecode.UICatalog" --full-reset --show-ios-log --device-name "iPhone 6" --native-instruments-lib --native-instruments-lib

info: [debug] Starting Appium in pre-launch mode

info: Pre-launching app
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: ***\*        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] App is an iOS bundle, will attempt to run as pre-existing

info: [debug] Creating new appium session 94950ffa-bcf7-4440-85e8-f7fa66fedb6a
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version

info: [debug] Xcode version set to 7.2.1

info: [debug] Setting iOS SDK Version

info: [debug] iOS SDK Version set to 9.2
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.2.1","iOSSDKVersion":"9.2","deviceName":"iPhone 6","platformVersion":"9.2"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (9.2)'
info: [debug] iOS sim UDID is 70C971E6-3EA7-42DB-8211-145AA2D5C77C
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim

error: Could not set the device type in Info.plist

info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.example.apple-samplecode.UICatalog/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.example.apple-samplecode.UICatalog/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/AnandJois/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/AnandJois/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js
info: [debug] Reusing dynamic bootstrap: /Users/AnandJois/Library/Application Support/appium/bootstrap/bootstrap-f062718992d59810.js
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.2.1","iOSSDKVersion":"9.2","deviceName":"iPhone 6","platformVersion":"9.2"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (9.2)'
info: [debug] We're on iOS7.1+ so forcing defaultDevice on
info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"7.2.1","iOSSDKVersion":"9.2","deviceName":"iPhone 6","platformVersion":"9.2"}
info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone 6 (9.2)'
info: [debug] Could not parse plist file (as binary) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.example.apple-samplecode.UICatalog/Info.plist
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Applications/Appium.app/Contents/Resources/node_modules/appium/com.example.apple-samplecode.UICatalog/Info.plist
info: [debug] Cleaning up appium session
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Try using the path to a `.app` as you app, rather than a bundle id.
