### ISSUE TITLE
Can iOS Command Center be opened with Appium?

### ISSUE THREAD

**Issue by joshuarh** [appium/appium#6312]
## The problem

I am trying to simulate the internet connection going down on the device. Since Appium does not support the iOS Network Connection API, I am trying to do it manually by opening the Command Center (by swiping up from the bottom of the screen).

Unfortunately swiping up from the lowest pixel of the screen doesn't open it. The closest I can get on an iPhone 6 sim is `start_y: 657` and anything above that throws `point is not within the bounds of the screen`.

If there's a better way to simulate the network connection going down on iOS, please advise. Thank you!

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: OS X 10.11.3
* Node.js version (unless using Appium.app|exe): 5.5.0
* Mobile platform/version under test: iPhone 6
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

**Comment by imurchie** [comment]
This would be better asked on the [Appium Discuss list](https://discuss.appium.io/). Users might have figured out ways.

There is no particular way that is reliable, as far as I know. You _can_ automate the Settings app, but that is slow and laborious.
