### ISSUE TITLE
Setting the AVD Capability is not auto-starting the avd

### ISSUE THREAD

**Issue by stevejensen22** [appium/appium#6313]
## The problem

I have passed in `avd` into my `DesiredCapabilities()` and I have the right name. I was under the impression that this would auto start that avd at test runtime. This isn't happening for me.
## Environment
- Appium version (or git revision) that exhibits the issue: `1.5.0`
- Last Appium version that did not exhibit the issue (if applicable): `I'm new to Appium`
- Desktop OS/version used to run Appium: `Windows 10`
- Node.js version (unless using Appium.app|exe): `node -v gives me v5.0.0`
- Mobile platform/version under test: `Android 4.2.2`
- Real device or emulator/simulator: `Emulator`
- Appium CLI or Appium.app|exe: `I installed it with npm install -g appium`
## Details

My code looks likes this:

```
    public void setUpMobile() throws Exception{
        // SessionId seleniumRemoteSessionId;
        DesiredCapabilities caps = new DesiredCapabilities();
        caps.setCapability("avd", "Test");
        caps.setCapability("deviceName", "emulator-5556");
        caps.setCapability("app", "C:\\Users\\steve\\Workspace\\apps\\com.plexapp.android.apk");
        if (!initialized) {
            // initialize the driver
            driver = new AndroidDriver(new URL("http://192.168.1.2:4723/wd/hub"), caps);
        }
    }
```

If this is not the way to get an `avd` to auto start and there is another way, please let me know.
## Link to Appium logs

https://gist.github.com/lilshrumpmerp/95508630c960f7ef1c10
## Code To Reproduce Issue [ Good To Have ]

https://github.com/appium/tutorial/blob/master/projects/java_android/src/test/java/appium/tutorial/android/AutomatingASimpleActionTest.java#L13-L17

**Comment by dpgraham** [comment]
Can you repost the gist? It's giving me a 404
