### ISSUE TITLE
[Appium-Instruments]Hard code for Install Timeout when get devices list

### ISSUE THREAD

**Issue by xuanzhaopeng** [appium/appium#6314]
## The problem

Hard code in https://github.com/appium/appium-instruments/blob/master/lib/utils.js#L32 , use const variable INST_STALL_TIMEOUT as the timeout for get available devices, which is not enough for some low performance test devices.(const value is 12000ms)

## Environment

Appium 1.5.0 (installed from NPM)
Appium-ios-driver 1.8.7
Appium-Instruments 3.6.0

## Details

Need to find a way or an additional option parameters passed from IOS Driver, to set this INSTALL_TIME OUT , rather than always use 12000ms as the timeout.

Please have a look about the source code correspondent :  https://github.com/appium/appium-instruments/blob/master/lib/utils.js#L32

**Comment by imurchie** [comment]
`launchTimeout` now gets through.

**Comment by xuanzhaopeng** [comment]
Cool
