### ISSUE TITLE
[appium 1.5] waitForAppScript needs a semicolon or colon

### ISSUE THREAD

**Issue by edcamposaw** [appium/appium#6318]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

I will copy and paste my thread from discuss.appium.io

https://discuss.appium.io/t/waitforappscript-passed-as-string-but-appium-doesnt-create-new-session/8822

Hello, I keep getting the following error using appium 1.5 released last week:

[debug] [Appium] Capability 'waitForAppScript' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] SessionNotCreatedError: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): waitForAppScript must be of type string.

My dcaps in appium logs:

[Appium] Capabilities:
[Appium] udid: '---'
[Appium] platformName: 'iOS'
[Appium] platformVersion: '8.3'
[Appium] deviceName: '---'
[Appium] sendKeyStrategy: 'grouped'
[Appium] autoAcceptAlerts: false
[Appium] waitForAppScript: 'true'
[Appium] app: '---'
[Appium] newCommandTimeout: 180
my dcaps in code:

    caps: {
        udid: $udid,
        platformName: 'iOS',
        platformVersion: @version,
        deviceName: @name,
        sendKeyStrategy: 'grouped',
        autoAcceptAlerts: $property['autoAcceptAlerts'],
        waitForAppScript: 'true',
        app: @app,
        newCommandTimeout: 180
    }
I've tried a couple of different combinations of true True 'true' 'True' "true" "True"

all with same results.

The info on the error seems strange also it says "Capability 'waitForAppScript' changed from string to boolean." but then the error message itself says the opposite. "Details: The desiredCapabilities object was not valid for the following reason(s): waitForAppScript must be of type string."

The fix for it:

waitForAppScript: "true,",

Is this expected behavior?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5
* Last Appium version that did not exhibit the issue (if applicable): 1.4.*
* Desktop OS/version used to run Appium: el capitan
* Node.js version (unless using Appium.app|exe): 0.12.7
* Mobile platform/version under test: ios
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: cli

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
This is not the expected behaviour and has already been fixed. It will be in the next release, which is in the works (once we ratify full iOs 9.3 support).

Use `"true;"` is a good work around for now.

Thanks for reporting this!
