### ISSUE TITLE
appium remove data from UIView

### ISSUE THREAD

**Issue by gilsheps** [appium/appium#6319]
## The problem

I have UIView in feed, when Appium reading the feed, the data from the  UIView disappears.
the issue happened also with the inspector when I clicked on inspector button.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.4.16 + 1.5.0
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: OSX 10.11.4 (15E65)
- Node.js version (unless using Appium.app|exe): 
- Mobile platform/version under test: 9.3
- Real device or emulator/simulator: simulator
- Appium CLI or Appium.app|exe: 
## Details

I have app with feed with table, this feed will display some asset. one of the asset is UIView, this view can display video or image. 
when Appium read the elements that in the screen the data of the UIView disappears. it means that the video or the image disappears
## Link to Appium logs

https://gist.github.com/gilsheps/27204f17d8d3ec200dab
## Link to video that exam the issue:

https://dl.dropboxusercontent.com/u/6694769/appium.mov

**Comment by jlipps** [comment]
Sorry, the old inspector is no longer supported. We'll be releasing a new one soon!
