### ISSUE TITLE
can't install appium1.5.0

### ISSUE THREAD

**Issue by jackiezero** [appium/appium#6320]
#### Hi Dears 
         I used npm install -g appium  update appium to 1.5.0 in commond ,there is a problem appear in install SelendroidInstaller . 
>yan@yan-Inspiron-7548:~$ sudo npm install -g appium
[sudo] password for yan: 
 
> appium-chromedriver@2.8.0 install /usr/local/lib/node_modules/appium/node_modules/appium-chromedriver
> node install-npm.js

> Error trying to install Chromedriver binary. Waiting and trying again.
   Error trying to install Chromedriver binary. Waiting and trying again.
   Error trying to install Chromedriver binary. Waiting and trying again.
>  info Chromedriver Install Installing Chromedriver version '2.21' for platform 'linux' and     architecture   '64'
>  info Chromedriver Install Opening temp file to write chromedriver_linux64 to...
>  info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip...
>  RequestError: Error: connect ETIMEDOUT 74.125.203.128:80
    at new RequestError (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/usr/local/lib/node_modules/appium/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/appium/node_modules/request/request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

> appium-selendroid-driver@1.2.2 install /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver
> node ./bin/install.js

>info SelendroidInstaller Ensuring /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-installer/selendroid/download exists
>info SelendroidInstaller Downloading Selendroid standalone server version 0.17.0 from https://github.com/selendroid/selendroid/releases/download/0.17.0/selendroid-standalone-0.17.0-with-dependencies.jar --> /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-installer/selendroid/download/selendroid-server.jar

**Comment by SrinivasanTarget** [comment]
Try installing appium without sudo

**Comment by jackiezero** [comment]
#### hi  i had try installing appium without sudo in user and root ,it also can't successful. 
### In user ,remind me not have permission 
>yan@yan-Inspiron-7548:~$ npm install -g appium
npm ERR! tar.unpack untar error /home/yan/.npm/appium/1.5.0/package.tgz
npm ERR! Linux 4.2.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! path /usr/local/lib/node_modules/appium
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

>npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/appium',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/appium',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

>npm ERR! Please include the following file with any support request:
npm ERR!     /home/yan/npm-debug.log

#### In root 
> yan@yan-Inspiron-7548:~$ sudo su
[sudo] password for yan: 
root@yan-Inspiron-7548:/home/yan# npm install -g appium
npm ERR! tar.unpack untar error /tmp/npm-2956-3cc2c276/registry.npmjs.org/appium-android-driver/-/appium-android-driver-1.6.12.tgz
npm ERR! tar.unpack untar error /tmp/npm-2956-3cc2c276/registry.npmjs.org/appium-instruments/-/appium-instruments-3.6.0.tgz
npm ERR! Linux 4.2.0-34-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20

> npm ERR! unexpected eof
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

> npm ERR! Please include the following file with any support request:
npm ERR!     /home/yan/npm-debug.log
root@yan-Inspiron-7548:/home/yan#

**Comment by JordanGS** [comment]
I have the exact same issue as the original post, except mine is in Windows 7.

I have tried Node v4.4.1 LTS and Node v5.9.0 Stable.

My process was to install python 2.7, install pip, java jdk, set environment variables for both.
Installed node as admin from the .exe
ran cmd as admin and tried to execute 'npm install -g appium'

resulted in the same error as above. I am trying to install appium to be able to run it from the command line and not from the GUI.

**Comment by qaDream77** [comment]
I have the same issue as JordanGS, i did the exact same steps as he/she. Can anyone comment on this issue?

**Comment by kapilsaxena** [comment]
I am also facing the same issue on OSX 10.11.3

**Comment by SrinivasanTarget** [comment]
@kapilsaxena Is the logs same? Are you running appium from source?

**Comment by kapilsaxena** [comment]
I tried running the command npm install -g appium and it throws errors.

Please see the complete logs at http://pastebin.com/1qCiifE6

**Comment by SrinivasanTarget** [comment]
Based on your logs i see node version is 0.10, for appium 1.5 to work fine we need min 0.12. Upgrade your node version and give a try it should work.

**Comment by kapilsaxena** [comment]
Yes. I upgraded the node version and it worked fine for me.
Thanks!

**Comment by SrinivasanTarget** [comment]
:+1:

**Comment by MithuraJ** [comment]
https://drive.google.com/file/d/0B1JOMwQk8qIcb1B6cDNkRTlpcWc/view?usp=sharing
I have this issue too. I'm trying to install this off of Windows 7.

I have tried Node v4.4.1 LTS and Node v5.9.0 Stable.

My process was to install python 2.7, install pip, java jdk, set environment variables for both.
Installed node as admin from the .exe
ran cmd as admin and tried to execute 'npm install -g appium'

resulted in the same error as above. I am trying to install appium to be able to run it from the command line and not from the GUI.

**Comment by gbhatnag** [comment]
I was encountering the same problem. Upgrading `node` from `v0.10.40` to `v0.12.7` worked, though the beginning of the installation (via `npm install -g appium`) still reported the same error for a few seconds: `Error trying to install Chromedriver binary. Waiting and trying again.` -- repeated twice before the installation successfully continued.

**Comment by qaDream77** [comment]
@gbhatnag I have node v4.4.1 installed. Does it have to be v0.12.7 specifically?

**Comment by gbhatnag** [comment]
Maybe it's not compatible that far ahead?  I use `nvm` to manage node versions so I can switch around versions depending on what's needed.

**Comment by qaDream77** [comment]
@gbhatnag works fine on ubuntu with v4.4.1, the only reason is that i work more on windows so i need it on my windows boot without having to switch os for mobile testing.

**Comment by gbhatnag** [comment]
Looks like there a [couple](https://github.com/coreybutler/nvm-windows) [modules](https://github.com/hakobera/nvmw) that do version management for node on Windows.  Hopefully switching to a different version will allow you install.  Other apps that require different versions of node can be started in different environments and you can use the version manager to change the version of node in those environments.

**Comment by qaDream77** [comment]
Node version doesn't matter, it doesn't work with v0.12 either. Breaks on same thing.

**Comment by gbhatnag** [comment]
Ah, bummer.  Maybe there's some issue specific to Windows.

**Comment by qaDream77** [comment]
@gbhatnag i'm not sure, i'm hoping someone from the appium team can comment, it seems to be related to the selendroid driver.

**Comment by imurchie** [comment]
The android driver, on install, downloads both Chromedriver and Selendroid. Unfortunately there are some issues with the order in which things get done by npm.

What version of npm are you using? While Appium officially supports 2+, npm 2 is _much_ more problematic in this regard. I would recommend moving to npm 3.x.

**Comment by jackiezero** [comment]
@imurchie     Thanks  I will try npm 3+  . I am confirmed the issues  is only appear in install appium 1.5.0 ,if install other versions  is ok

**Comment by jackiezero** [comment]
@imurchie   Hi  I had tried installing appium with npm 3+ succeed. But in the last nom
remind , is there have something affect??
> npm WARN optional Skipping failed optional dependency /appium/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.9

**Comment by imurchie** [comment]
That is fine. It's an optional dependency that only works on Mac. Appium functions fine without it.
