### ISSUE TITLE
iOS real device Bluetooth Pairing Request: How to handle popup

### ISSUE THREAD

**Issue by JK-90** [appium/appium#6323]
## The problem

Hi,
i want to handle the Bluetooth Pairing Request popup on iOS real device.
I navigate in the Settings app from the iPhone 6s and enable the Bluetooth via Appium. Just after i start a bluetooth request from an other device to my iPhone the iPhone shows the Pair-Popup. How can i control the popup and tap the "Pair" Button. It appears to me that Appium freeze and have no access to the popup. Can someone help me?

Thanks 
## Environment
- Mobile platform/version under test: iOS 9.2.1
- Real device or emulator/simulator: Real device

**Comment by radnotiz** [comment]
Normally I go for calls generic for any alerts

For Ruby:
- [Appium API](http://www.rubydoc.info/github/appium/ruby_lib/Appium/Ios#alert_accept-instance_method) 
- [Webdriver API](https://selenium.googlecode.com/git/docs/api/rb/Selenium/WebDriver/Alert.html) 

[Example for Webdriver](https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings#javascript-dialogs)

**Comment by JK-90** [comment]
Hi Radnotiz, 
it dont work with this. The Appium driver have no access to the popup. Have you an other solution?

**Comment by dpgraham** [comment]
Unfortunately there's no way for Appium to dismiss alerts
