### ISSUE TITLE
Not able to read data from modal/popup in android 

### ISSUE THREAD

**Issue by tadesushilgithub** [appium/appium#6324]
## The problem

Not able to access popup, a kind of modal in android application. Here I am suing Heads-up notifications app for notification but not able to read and access popup. It's not showing inside uiautomator.
![heads-up notification popup](https://cloud.githubusercontent.com/assets/17309586/13986261/de73f30a-f0d7-11e5-909a-16d8c2649593.JPG)

So inside attached Image i want to read data from popup which is there on top of screen. Why it's not showing inside uiautomator? OR is this kind of custom control? What can I do to see inside uiautomator ? as this is 3rd party app I can't change apk code. Please find attached .apk file.
[Heads-up%20Notifications_1.12.zip](https://github.com/appium/appium/files/186037/Heads-up.20Notifications_1.12.zip)

**Comment by saikrishna321** [comment]
@tadesushilgithub if UIAutomator cant see it then appium can't either do anything .. 

@imurchie thoughts ?

**Comment by tadesushilgithub** [comment]
@saikrishna321 ya you right but how to show inside uiautomator? if they enabled the accessibility then can we see inside uiautomator? but problem is 3rd party application we can't edit code base.

**Comment by jlipps** [comment]
Unfortunately custom controls are often not automatable. I would run uiautomatorviewer and if you don't see the element there either, there's not much you can do. You could ask the 3rd party to add accessibility info to their control, perhaps!
