### ISSUE TITLE
Make sure packages are not including extra stuff

### ISSUE THREAD

**Issue by imurchie** [appium/appium#6325]
## The problem

All of the appium packages currently include a lot of unnecessary stuff when publishing. We ought to add a lot of stuff to the `.npmignore` file:
- tests
- test assets
- un-transpiled source code
- documentation of all sorts (e.g., all `.md` files)
- supporting files (config, gulpfiles, Makefiles, etc)

This needs to be done on a package-by-package basis.
- [ ] https://github.com/appium/appium-instruments
- [ ] https://github.com/appium/appium-android-driver
- [ ] https://github.com/appium/appium-ios-driver
- [ ] https://github.com/appium/appium-adb
- [ ] https://github.com/appium/appium-selendroid-driver
- [ ] https://github.com/appium/appium-base-driver
- [ ] https://github.com/appium/node-mobile-json-wire-protocol
- [ ] https://github.com/appium/appium-chromedriver
- [ ] https://github.com/appium/appium-express
- [ ] https://github.com/appium/appium-android-bootstrap
- [ ] https://github.com/appium/appium-doctor
- [ ] https://github.com/appium/node-teen_process
- [ ] https://github.com/appium/appium-ios-simulator
- [ ] https://github.com/appium/appium-support
- [ ] https://github.com/appium/appium-xcode
- [ ] https://github.com/appium/appium-uiauto
- [ ] https://github.com/appium/appium-remote-debugger
- [ ] https://github.com/appium/node-simctl
- [ ] https://github.com/appium/appium-selendroid-installer
- [ ] https://github.com/appium/appium-ios-log
- [ ] https://github.com/appium/ios-app-utils
- [ ] https://github.com/appium/appium-cookies
- [ ] https://github.com/appium/jsonwp-proxy
- [ ] https://github.com/appium/appium-uiautomator
- [ ] https://github.com/appium/logger
- [ ] https://github.com/appium/appium-atoms
- [ ] https://github.com/appium/appium-fake-driver
- [ ] https://github.com/appium/authorize-ios

Maybe others?

**Comment by SrinivasanTarget** [comment]
Are we gonna include wiki for documentation to eliminate doc's?

**Comment by imurchie** [comment]
No. This is not eliminating docs, just eliminating them from the tarball that gets downloaded from npm. So the size is smaller and download faster.

**Comment by SrinivasanTarget** [comment]
#6327

**Comment by SrinivasanTarget** [comment]
Yup Got it @imurchie

**Comment by dpgraham** [comment]
So far, this is what we're ignoring in the .npmignore file

```
assets/
submodules/
test/
_vimrc_local.vim
*.swp
*.swo
*~
.*~
.DS_Store
.travis.yml
*.log
*.trace
*.sublime-
*.prefs
.jshintrc
./.npmignore
```

We still need exclude untranspiled code and docs. I think this ticket is worth revisiting to see if we can slim down the Appium build further. The node_modules/ directory is 200+ MB.

**Comment by imurchie** [comment]
Yes. But it's probably best to do after we've pared down the packages to at least a reasonable number (the "dearchitecting" project).

**Comment by mykola-mokhnach** [comment]
@imurchie Is this issue still relevant?

**Comment by dpgraham** [comment]
@mykola-mokhnach I could take this one. The Java projects (uiautomator2-server, adb, espresso) could have globs added to .npmignore ... specifically they all include the Java src, which is unneeded.

**Comment by imurchie** [comment]
@dpgraham Seems good to go through those ones. But they should all be moved to using `package.json` instead of `.npmignore`.

On a practical note, `npm pack --dry-run` is useful for seeing what npm will put into the tarball, without having to publish or even actually create the archive.

**Comment by dpgraham** [comment]
I just had a look through all of the contents of Appium and it looks like we got all the important stuff.
