### ISSUE TITLE
Appium NPM install failure on Windows 7

### ISSUE THREAD

**Issue by qaDream77** [appium/appium#6329]
## The problem

A few of us seem to be having this issue, but i went ahead to create a new ticket because the one i posted in previously got hijacked by and didn't get resolved.

The issue is that we can't install appium via the npm command, do not wish to install it via the .exe

## Environment

I'm trying to install this off of Windows 7.

I have tried Node v4.4.1 LTS and Node v5.9.0 Stable.

My process was to install python 2.7.5, install pip, java jdk, set environment variables for both.
Installed node as admin from the .exe
ran cmd as admin and tried to execute 'npm install -g appium'

## Details

Resulted in the same error as above. I am trying to install appium to be able to run it from the command line and not from the GUI.

## Link to Appium logs

https://drive.google.com/file/d/0B1JOMwQk8qIcb1B6cDNkRTlpcWc/view?usp=sharing

**Comment by jackiezero** [comment]
@qaDream77    you should ensure the issue is  updated version to appium1.5.0   .   Installed other appium version is OK

**Comment by scottdixon** [comment]
What happens when you `npm install appium-selendroid-driver` ?

**Comment by qaDream77** [comment]
@scottdixon 

`Java -version`

OUTPUT: java version "1.8.071-b15

`for %i in (javac.exe) do @echo. %~$PATH:i`

OUTPUT: nothing

`npm install appium-selendroid-driver`

Tried Node v0.12 and v5.9.1. Both produce the same error. Verified node version with `node -v`

v0.12 error is attached in the google drive log.
https://drive.google.com/open?id=0B9wNqMrAeGFNWk5obTNwbUYydjg

v5.9.1 does not generate an npm log but gives the following:
http://prnt.sc/ajhs4o

**Comment by scottdixon** [comment]
Another thought - Appium on windows has a hard time with multiple spaces. Can you move your java to dir that doesn't have a space? e.g. C:\Java, updated your JAVA_HOME path and see if this changes anything?

**Comment by qaDream77** [comment]
@scottdixon doing that now, gimme a minute. Thanks!

**Comment by qaDream77** [comment]
@scottdixon I moved it to `C:\Java`, same error still persists.

**Comment by qaDream77** [comment]
**SOLUTION**

The issues is 3 fold.

1) Spaces in path are **NOT** allowed! Therefore, create a folder in C drive called Development such as `C:\Development`

Install NodeJS into this folder, Install JAVA JDK into this folder.

`C:\Development`

- Java

- NodeJS

Now you have to set your environment variables.

`JAVA_HOME` **HAS** to be set to `C:\Java\jdk1.7.0_79`, `jdk1.7.0_79` is just installed version, yours might be different.

Add to `PATH` the following: `C:\Development\nodejs\` and `%JAVA_HOME%\bin`

Do **NOT** use `C:\ProgramData\Oracle\Java\javapath` for anything.

You may however still have to update your symbolic links to point to the jdk and not the jre for other applications if they use javapath folder and not your environment variable.

**Comment by scottdixon** [comment]
Good to hear @qaDream77, thanks for following up.

For WD usage, take a look at our sample code: https://github.com/appium/sample-code/tree/master/sample-code/examples/node
