### ISSUE TITLE
Session terminated when opening https://addons-dev.allizom.org using Android 5.1

### ISSUE THREAD

**Issue by davehunt** [appium/appium#6330]
Note that this issue was initially reported to Sauce Labs, however they have been able to reproduce locally using Appium and advised opening an issue here.
## The problem

When attempting to open https://addons-dev.allizom.org using Android 5.1 the session is terminated and subsequent commands fail. From Sauce Labs: "when using Android 5.1 the application takes longer than 60 seconds to respond to the Appium driver and this causes the session to shutdown".
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.0
- Last Appium version that did not exhibit the issue (if applicable): n/a
- Desktop OS/version used to run Appium: Linux
- Node.js version (unless using Appium.app|exe): unknown
- Mobile platform/version under test: Android 5.1
- Real device or emulator/simulator: Emulator
- Appium CLI or Appium.app|exe: unknown
## Details

This is working in Android 5.0.
## Link to Appium logs

https://saucelabs.com/jobs/cc79a2ebffbf48b7bfa275ebad93aac3

Also, from Sauce Labs reproducing the issue locally:

```
info: —> POST /wd/hub/session/f5c40b5db128ad26df4bee337bc20b72/url {"url":“https://addons-dev.allizom.org”,“sessionId”:"f5c40b5db128ad26df4bee337bc20b72"}
info: JSONWP Proxy: Proxying [POST /wd/hub/session/f5c40b5db128ad26df4bee337bc20b72/url] to [POST http://127.0.0.1:9515/wd/hub/session/f5c40b5db128ad26df4bee337bc20b72/url] with body: {"url":“https://addons-dev.allizom.org”,“sessionId”:"f5c40b5db128ad26df4bee337bc20b72"}
info: [debug] Didn’t get a new command in 60 secs, shutting down…
info: Shutting down appium session
info: Chromedriver: Changed state to ‘stopping’
info: JSONWP Proxy: Proxying [DELETE /] to [DELETE http://127.0.0.1:9515/wd/hub/session/f5c40b5db128ad26df4bee337bc20b72] with no body
info: Chromedriver: [STDERR] [92.016][SEVERE]: Unable to receive message from renderer
```
## Code To Reproduce Issue

Clone and run tests from https://github.com/mozilla/Addon-Tests/tree/master/tests/mobile making sure you have the required Python packages. A suitable command line to reproduce the error would be something like:

``` bash
$ py.test --base-url https://addons-dev.allizom.org --capability browserName Browser --capability platformName Android --capability platformVersion 5.1 --capability deviceName 'Android Emulator' tests/mobile
```

You can run this via Sauce Labs by providing `SAUCELABS_USERNAME`, `SAUCELABS_API_KEY` environment variables and `--driver SauceLabs` command line option, and `--capability appiumVersion 1.5.0`. Alternatively you can use `--driver Remote` and specify a `--host` and `--port` for the Appium server.

**Comment by scottdixon** [comment]
I'm able to reproduce this locally w/ Android 5.1 (both Appium 1.4 & 1.5). The browser crashes when it's mid-render. Logcat: https://gist.github.com/scottdixon/ee4dc71a55b2d4484f23

Doesn't crash on other versions of Android. Doesn't crash on 5.1 when I manually navigate to https://addons-dev.allizom.org

![image](https://cloud.githubusercontent.com/assets/4726068/14026486/4943d992-f1b0-11e5-8fe0-c6ac9da6fe0e.png)

I'll dig deeper in an upcoming sprint.

**Comment by dpgraham** [comment]
Is this still an issue?

**Comment by davehunt** [comment]
It doesn't appear to be an issue any more. Either a later Appium version or changes to the website have likely resolved it.
