### ISSUE TITLE
Appium 1.5.0, hybrid app, iOS real device: executeAsync always returns 'undefined is not a function'

### ISSUE THREAD

**Issue by alsorokin** [appium/appium#6335]
## The problem

When running Appium tests for a hybrid app on a real iOS device, the executeAsync method always returns 'undefined is not a function' error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.0
* Desktop OS/version used to run Appium: OSX Yosemite 10.10.5
* Node.js version (unless using Appium.app|exe): 0.12.7
* Mobile platform/version under test: iOS 8.1
* Real device or emulator/simulator: Real iPad 2
* Appium CLI or Appium.app|exe: Appium CLI

## Details

The tested webview app is just a helloWorld app built with latest [cordova](https://github.com/apache/cordova-cli):
`cordova create foo`
`cd foo`
`cordova platform add ios`
`cordova build --device`

Or you can take built .ipa from my [sample-code](https://github.com/alsorokin/sample-code/blob/master/sample-code/apps/HelloCordova.ipa) fork.
## Link to Appium logs

https://gist.github.com/alsorokin/3f989ee2de9565e8f368

## Code To Reproduce Issue

```javascript
  it("should execute async script", function () {
    return driver
      .sleep(5000) // give it some time to load
      .contexts()
      .then(function(contexts) {
        return driver.context(contexts[contexts.length - 1]);
      })
      .executeAsync(function (cb) {
        setTimeout(function () {
          cb();
        })
      }, []);
  });
```

**Comment by alsorokin** [comment]
I forgot to add: this code works on the simulator and fails only on real iOS device.
It also fails on previous Appium versions, though without the error message (just no response from Appium).

Also, synchronous execute works just fine:
```javascript
  it("should execute async script", function () {
    return driver
      .sleep(5000) // give it some time to load
      .contexts()
      .then(function(contexts) {
        return driver.context(contexts[contexts.length - 1]);
      })
      .execute(function () {
        return 15; 
      }, []).should.eventually.equal(15); //it works!
  });
```

**Comment by imurchie** [comment]
Yes. I see the problem. My apologies.

**Comment by imurchie** [comment]
@alsorokin If you are running from source, can re-run `rm -rf node_modules && npm install` to get the latest?

**Comment by alsorokin** [comment]
I wasn't running from source but I'll try it today and tell you the results.

**Comment by alsorokin** [comment]
Tried it, I'm not getting this error anymore but now there's just no response from the device after execute_async is sent. I guess that's another issue. It is also present on older Appium versions.

https://github.com/appium/appium/issues/6343
