### ISSUE TITLE
getScreenshotAs saving 0 byte screenshots on Android

### ISSUE THREAD

**Issue by VinceBarresi** [appium/appium#6336]
## The problem

I'm using the appium java bindings for both iOS and Android automation. A few of my tests contain methods for capturing and comparing screenshots. For some reason, all of my android screenshots are saving as 0 byte files. I have not seen this happen on iOS and am not sure whats happening exactly. I've pasted my method below.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.4.16
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Mac OSX 10.11.2
- Node.js version (unless using Appium.app|exe): 5.5.0
- Mobile platform/version under test: Android
- Real device or emulator/simulator: Nexus 6P - Android 6.0 (real device)
- Appium CLI or Appium.app|exe: Appium CLI
## Code To Reproduce Issue [ Good To Have ]

```
public void saveScreenshotToDirectory(String pathToScreenshots) {
        try {
            File sourceFile = DriverManager.getAppiumDriver().getScreenshotAs(OutputType.FILE);
            SimpleDateFormat dateTimeFormat = new SimpleDateFormat("MMddyyhhmmssa");
            String filename = dateTimeFormat.format(new Date());
            File targetFile = new File(pathToScreenshots + filename + ".png");
            FileUtils.copyFile(sourceFile, targetFile);
        } catch (Exception e) {
            e.printStackTrace();
            Logger.logMessage("Failed to save screenshot.");

        }
    }
```

**Comment by scottdixon** [comment]
@VinceBarresi - can you please try with Appium 1.5 - if the issue persists please provide a [gist](http://gist.github.com) of the logs.

**Comment by wuweicoco** [comment]
In Appium 1.5.3, have the same issue~
