### ISSUE TITLE
Downloading the Appium .dmg for mac osx always errors at 100% for me

### ISSUE THREAD

**Issue by tomtom87** [appium/appium#6341]
I am trying to download the Appium DMG app for Mac OSX from the appium bitbucket but everytime my download reaches 100% it doesn't complete and I cannot use the dmg, my mac says it is corrupted.

Please can someone help me download it from an alternative URL?

**Comment by scottdixon** [comment]
Please post this in the appium-dot-app project. It looks like there's another issue open along the same lines: https://github.com/appium/appium-dot-app/issues/534
