### ISSUE TITLE
Appium 1.5.0, hybrid app, iOS real device, executeAsync callback is not called.

### ISSUE THREAD

**Issue by alsorokin** [appium/appium#6343]
## The problem

When running Appium tests for a hybrid app on a real iOS device, the executeAsync callback is not called.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.3, 1.4, 1.5, edge
* Last Appium version that did not exhibit the issue (if applicable): none
* Desktop OS/version used to run Appium: OSX Yosemite 10.10.5
* Node.js version (unless using Appium.app|exe): 0.12.9
* Mobile platform/version under test: iOS 8.1
* Real device or emulator/simulator: real iPad 2
* Appium CLI or Appium.app|exe: Appium CLI

## Details

The tested webview app is just a helloWorld app built with [cordova](https://github.com/apache/cordova-cli):
`cordova create foo`
`cd foo`
`cordova platform add ios`
`cordova build --device`

Or you can take built .ipa from my [sample-code](https://github.com/alsorokin/sample-code/blob/master/sample-code/apps/HelloCordova.ipa) fork.

## Link to Appium logs

https://gist.github.com/alsorokin/f1679fe090b0c6c053e8

## Code To Reproduce Issue

```javascript
  it("should execute async script", function () {
    return driver
      .sleep(5000) // give it some time to load
      .contexts()
      .then(function(contexts) {
        return driver.context(contexts[contexts.length - 1]);
      })
      .executeAsync(function (cb) {
        setTimeout(function () {
          cb();
        })
      }, []);
  });
```

**Comment by imurchie** [comment]
Well... That is something different, at least :(

**Comment by imurchie** [comment]
Your script works fine locally. Can you open a a local resource from you real device (i.e., something that appium can server, like `http://YOUR-IP/test/guinea-pig`). This feels like an addressing issue.

**Comment by alsorokin** [comment]
Yeah, it was a connectivity problem. Turns out that the CSP tag in my index.html did not allow the connection to appium server.
Problem solved. Thanks for the help, @imurchie

**Comment by imurchie** [comment]
You're welcome! I'm so glad that you got it working!
