### ISSUE TITLE
Appium 1.5 error prompt on iOS

### ISSUE THREAD

**Issue by gymg** [appium/appium#6345]
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "."
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.8.3 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.8.3 install script 'node install-npm.js'.
npm ERR! This is most likely a problem with the appium-chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install-npm.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls appium-chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tanlinzhen/Applications/appium/npm-debug.log
---- FAILURE: reset.sh exited with status 1 ----

**Comment by imurchie** [comment]
Can you try upgrading to npm 3? This is a problem that is sometimes seen in 2.

**Comment by gymg** [comment]
Thanks!
Yes. I upgraded the node version and it worked fine for me.

**Comment by Saranyanataraj** [comment]
@gymg Can u pls tell me to which version you upgraded node to?

**Comment by gymg** [comment]
OK， upgraded the version，npm install -g appium@1.5.0-beta4

**Comment by gymg** [comment]
@Saranyanataraj

**Comment by Saranyanataraj** [comment]
@gymg , I need to know the node and npm versions.

**Comment by gymg** [comment]
node versions 
![15d3f34b-db05-4312-9276-8bfa091a45a3](https://cloud.githubusercontent.com/assets/10443323/14848108/b875db5e-0c9e-11e6-9c55-69ff8c803e4e.png)

**Comment by Saranyanataraj** [comment]
Thanks @gymg.
