### ISSUE TITLE
Appium 1.5.0, Trying to start iOS log capture but it's already started exception in driver

### ISSUE THREAD

**Issue by JasonDobo** [appium/appium#6346]
## The problem
I'm in the process of upgrading our test project to use Appium 1.5.0 and every time I try and create a driver I get a "Trying to start iOS log capture but it's already started" exception. This only happens on IOS, on Android Appium 1.5.0 appears to be working fine.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.5.0
* Selenium Java version: 2.52.0
* Appium Java client: 3.4.0
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Last Selenium Java version version that did not exhibit the issue : 2.52.0
* Last Appium Java client version that did not exhibit the issue: 3.4.0
* Desktop OS/version used to run Appium: Mac OS X 10.11.3
* Node.js version (unless using Appium.app|exe): v5.7.0
* Mobile platform/version under test: iOS 9.3, iPhone 6s
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: 

## Details
In the test project first I start the Appium service, AppiumDriverLocalService.buildService
            localService = AppiumDriverLocalService.buildService(new AppiumServiceBuilder()
                    .withIPAddress(serverHost)
                    .usingAnyFreePort()
                    .withArgument(GeneralServerFlag.LOG_LEVEL, "error")
                    .withStartUpTimeOut(30, TimeUnit.SECONDS));
I then try and create the Appium, with the following capabilities:
[Appium] Capabilities:
[Appium]   app: '/Users/jason.dobo/MYApp.app'
[Appium]   noReset: true
[Appium]   newCommandTimeout: 150
[Appium]   platformVersion: '9.3'
[Appium]   hardwareType: 'simulator'
[Appium]   bundleId: 'com.commonagency.moonpigdevint'
[Appium]   name: ' - jason.dobo'
[Appium]   waitForAppScript: '$.delay(3000);$.acceptAlert()'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6s'
[Appium]   launchTimeout: 90000
[Appium]   nativeInstrumentsLib: true

AppiumDriver driver = new IOSDriver<>(driverServer.getLocalServiceURL(), capabilities.getDesiredCapabilities());

The driver appears to be created, the simulator launches with my application and then I get the "Trying to start iOS log capture but it's already started!" Exception

## Link to Appium logs
https://gist.github.com/JasonDobo/3fbe80817e0bb889925a

**Comment by imurchie** [comment]
So this happens when you start a session, and then call `launchApp`? Is this the process you want to go through? The application is already launched so it should not need to be done.

**Comment by JasonDobo** [comment]
Thank you @imurchie removing "launchApp" resolved the problem. I'm not sure why the original automation code did both or why it worked on pre-1.5.0 Appium.

**Comment by imurchie** [comment]
Excellent. I've changed the code to be able to handle it anyway. Just getting it through our CI system. But I'm glad that it works without the launch.
