### ISSUE TITLE
Appium inspector detects previous page elements when tapped

### ISSUE THREAD

**Issue by Sujina** [appium/appium#6347]
When navigates from 1 page to other page on apps, and  if an element is tapped using appium inspector, previous page element is getting detected through inspector.

## Environment

* Android and iOS app (both apps of a single company)
* MAC OS Capitan
* Xcode( 6 and 7 versions)
* Appium(1.4.13)

Please help.

**Comment by SrinivasanTarget** [comment]
Please raise an issue in https://github.com/appium/appium-dot-app/issues. Closing this here.

**Comment by SrinivasanTarget** [comment]
@triager please close
