### ISSUE TITLE
Rotation is inverted on Android

### ISSUE THREAD

**Issue by vicusbass** [appium/appium#6348]
I noticed a problem with screen orientation. The tablet is in Portrait position, but Appium thinks it's Landscape. When I rotate the screen using the rotate(ScreenOrientation.PORTRAIT) method, the screen rotates to landscape.
## Environment
- Appium version: 1.4.16.1
- Desktop OS: Windows 7 64bits
- Mobile platform: Android 5.1.1, 5.0.2
- Real device: Nexus 10, Samsung Note 10
- Appium Java Client: 3.4.0
## Link to Appium logs

Here's a snippet of Appium logs showing what happens when I try to rotate to Lanscape, being in Portrait mode:
https://gist.github.com/vicusbass/482a1dbd7aa2dfb5763c

**Comment by SrinivasanTarget** [comment]
@vicusbass Can you give a try on Appium latest version 1.5  and update us back?

**Comment by vicusbass** [comment]
Sure, as soon as available to install it. However, I did not notice any changes related to this issue, so not very high expectations

**Comment by artkoshelev** [comment]
Same issue here - orientation is inverted for all devices with 10" screen. Such devices "natural orientation" (in terms of uiautomator) is LANDSCAPE, so it returns "ROTATION_0", which appium parses as PORTRAIT.

**Comment by SrinivasanTarget** [comment]
@artkoshelev Have you tried in Appium 1.5.1?

**Comment by irenadavidov** [comment]
Create a pull request with the fix for this issue: https://github.com/appium/appium-android-bootstrap/pull/21
