### ISSUE TITLE
iOS Simulator Test -  Error: Appium was unable to set locale info

### ISSUE THREAD

**Issue by vkyt** [appium/appium#6350]
## The problem

Appium starts an iOS simulator instance and crashes when passing in the language and locale information.
## Environment
- Appium version: 1.5
- Last Appium version that did not exhibit the issue: 1.4.16
- Desktop OS/version used to run Appium: Mac Yosemite 10.10.5 (14F1605)
- Node.js version: v.5.5.0, npm 3.5.3 
- Mobile platform/version under test: iOS simulator iPhone 6 (8.4)
- Real device or emulator/simulator: Simulator
- Appium CLI or Appium.app|exe: 
## Link to Appium logs

https://gist.github.com/vkyt/cce4c4a2314b7708f7c64cf41af568c6
## Code To Reproduce Issue [ Good To Have ]

Language: ruby
I'm using FigNewton gem to pass in Appium server capabilities - FigNewton yml file is attached at the bottom.

  Appium::Driver.new(caps: {platformName: FigNewton.platformName, app: load_app_path.app_path, platformVersion: FigNewton.platformVersion, deviceName: FigNewton.deviceName, language: FigNewton.language, locale: FigNewton.locale, newCommandTimeout: FigNewton.newCommandTimeout}, appium_lib: {sauce_username: false, sauce_access_key: false})
# FigNewton Env File:

platformName: "iOS"
platformVersion: "8.4"
language: en
locale: en_CA
deviceName: "iPhone Simulator"
build_tool: xcode
build_config: automation-test-sim
log_level: debug
test_log_level: 0
newCommandTimeout: 350

**Comment by jlipps** [comment]
@vkyt we've changed the way that the sim gets its locale info, can you try in Appium 1.6.3 to see if this problem persists?

**Comment by SrinivasanTarget** [comment]
@triager please close
