### ISSUE TITLE
[Appium 1.5] Can't update from source - path is too long.

### ISSUE THREAD

**Issue by mittt** [appium/appium#6354]
## The problem

I followed [this](https://github.com/appium/appium/blob/master/docs/en/contributing-to-appium/appium-from-source.md) guide to install appium from source. The problem is that i can't update my copy on Windows, because some files can't be deleted - path is too long. The files can't be deleted even if i move the node_modules folder to the root of the partition.

I used rmdir to delete node_modules folder, but the delete also fails if i try with Explorer.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5 (the HEAD up to 30-03-2016)
* Desktop OS/version used to run Appium: Windows 10 
* Node.js version (unless using Appium.app|exe): v5.0.0

## Link to Appium logs

[rmdir error, files paths that are too long](https://gist.github.com/mittt/7fe969aae88f41e1d7e0b525921a544f)

**Comment by imurchie** [comment]
What version of npm do you have? Npm 3 installs everything flatly.

In the meantime, http://www.nikola-breznjak.com/blog/nodejs/how-to-delete-node_modules-folder-on-windows-machine/

**Comment by mittt** [comment]
{ npm: '3.3.6',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '56.1',
  modules: '47',
  node: '5.0.0',
  openssl: '1.0.2d',
  uv: '1.7.5',
  v8: '4.6.85.28',
  zlib: '1.2.8' }

**Comment by mittt** [comment]
The issue is still there even with the latest node/npm:

{ npm: '3.7.3',
  ares: '1.10.1-DEV',
  http_parser: '2.6.2',
  icu: '56.1',
  modules: '47',
  node: '5.9.1',
  openssl: '1.0.2g',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }

**Comment by imurchie** [comment]
At this point what is the problem? You can google how to delete the files. Does it not subsequently install?

**Comment by mittt** [comment]
The article above works great for me. 10x 

You can close the issue, I guess it's not even related to appium.

**Comment by imurchie** [comment]
Glad things worked out!
