### ISSUE TITLE
[Appium 1.5.1] Failing to reset simulator on xcode 7.3

### ISSUE THREAD

**Issue by leighdice** [appium/appium#6355]
## The problem

Updated Xcode to 7.3, now failing to reset the simulator each time a test is run
Tried updating to 1.5.1 but that didn't seem to fix it

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.1
* Desktop OS/version used to run Appium: Mac OSX 10.11.1
* Node.js version (unless using Appium.app|exe): 0.12.7
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator

## Details

Worked fine, with Xcode 7.2 and appium 1.5.0. 9.3 simulator seems to be causing it issues

## Link to Appium logs

https://gist.github.com/leighdice/5da8053b67cc6f3b7ab4626c3c86ad15#file-gistfile1-txt

**Comment by imurchie** [comment]
Yes, this has been seen and fixed, though after 1.5.1 was released unfortunately. 

If you are running from source, could you run `rm -rf node-modules && npm install`? If you are running from npm, please reinstall without the shrinkwrap file: `npm install -g appium --no-shrinkwrap`. Both ways ought to get you the latest `appium-ios-simulator`, which fixes this issue.

**Comment by leighdice** [comment]
Ah I see. `--no-shrinkwrap` worked beautifully thank you :+1: 

I found another workaround is to use the `fullReset` flag on the server arguments (if you want a fresh installed app each time).

**Comment by imurchie** [comment]
Excellent!
