### ISSUE TITLE
Error trying to install Chromedriver binary on Mac OS X El Capitan

### ISSUE THREAD

**Issue by schanami** [appium/appium#6358]
I followed the setup process 

> brew install node      # get node.js
> npm install -g appium  # get appium
> npm install wd         # get appium client
> appium &               # start appium
> node your-appium-test.js

stuck on this appium install step:
Error trying to install Chromedriver binary. Waiting and trying again. fn must be a function

```
See http://goo.gl/916lJJ
```

**Comment by imurchie** [comment]
What version of Node and Npm are you using? This error to me means that you are on a Node below 0.12, which is required.

**Comment by schanami** [comment]
was on node v0.10.25.  and making progress.
downloaded Appium.app but having problem running tests

**Comment by schanami** [comment]
rstormsf helped a lot.  how come the docs say to run node tests when it should be mocha?
https://github.com/appium/sample-code/issues/23
