### ISSUE TITLE
Sometimes element returned is wrong (from Xpath Selector)

### ISSUE THREAD

**Issue by Fanch-** [appium/appium#6359]
## The problem

Executing the same test, I can see sometimes appium get back the wrong element, using an Xpath selector.

## Environment

* Appium 1.5.1
* Java-client 3.3.0
* Google Nexus 6 real device
* Node v4.1.1

## Details
Selector : **//*[contains(@resource-id, "ad_validation_spinner_category")]/android.widget.Spinner/android.widget.TextView**

I want to have the text of this element, which is "Ventes Immobilieres" (Instance=4), though when it doesn't work I get "Catégorie" -> INSTANCE=3

**Works :**

```bash```
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[contains(@resource-id, \"ad_validation_spinner_category\")]/android.widget.Spinner/android.widget.TextView","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[contains(@resource-id, \"ad_validation_spinner_category\")]/android.widget.Spinner/android.widget.TextView","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding //*[contains(@resource-id, "ad_validation_spinner_category")]/android.widget.Spinner/android.widget.TextView using XPATH with the contextId:  multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.TextView, INSTANCE=4]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"7"}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"7"}
```

DOM : https://gist.github.com/Fanch-/9c581b0e4391f66ac29f56fa0389d92a

```bash```
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getText","params":{"elementId":"7"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getText","params":{"elementId":"7"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getText
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"Ventes immobilières"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getText() result: "Ventes immobilières"
```

**And when it doesn't :**

```bash```
[HTTP] --> POST /wd/hub/session/4a9b1558-88c6-4fd9-8ee3-6b5925af1683/element {"using":"xpath","value":"//*[contains(@resource-id, \"ad_validation_spinner_category\")]/android.widget.Spinner/android.widget.TextView"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//*[contains(@resource-id, \"ad_validation_spinner_category\")]/android.widget.Spinner/android.widget.TextView","4a9b1558-88c6-4fd9-8ee3-...
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[contains(@resource-id, \"ad_validation_spinner_category\")]/android.widget.Spinner/android.widget.TextView","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[contains(@resource-id, \"ad_validation_spinner_category\")]/android.widget.Spinner/android.widget.TextView","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding //*[contains(@resource-id, "ad_validation_spinner_category")]/android.widget.Spinner/android.widget.TextView using XPATH with the contextId:  multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CLASS=android.widget.TextView, INSTANCE=3]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"7"}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"7"}
```

DOM : https://gist.github.com/Fanch-/622b649c3f9ca36d4dfae3439d0f23ea

```bash```
[HTTP] <-- GET /wd/hub/session/4a9b1558-88c6-4fd9-8ee3-6b5925af1683/source 200 167 ms - 29324 
[HTTP] --> GET /wd/hub/session/4a9b1558-88c6-4fd9-8ee3-6b5925af1683/element/7/text {}
[MJSONWP] Calling AppiumDriver.getText() with args: ["7","4a9b1558-88c6-4fd9-8ee3-6b5925af1683"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getText","params":{"elementId":"7"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getText","params":{"elementId":"7"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getText
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"Catégorie"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getText() result: "Catégorie"
[HTTP] <-- GET /wd/hub/session/4a9b1558-88c6-4fd9-8ee3-6b5925af1683/element/7/text 200 19 ms - 84
```

Then I tried with : 

```java```
        MobileElement el = findById(getBaseIdSelector() + "ad_validation_spinner_category")
                  .findElementByClassName("android.widget.Spinner");
                  .findElementByClassName("android.widget.TextView");
        text = el.getText();
```

No problem, it seems to get the correct element each time.

So using Xpath selectors, we can see sometimes it get back the third instance of TextView though looking at the DOM it should be the fourth one. Can you confirm me that Xpath selectors are flaky with appium ? Should I stop using them? 

> find by “xpath” (i.e., an abstract representation of a path to an element, with certain constraints)

Is it an example of constraint ?

**Comment by imurchie** [comment]
XPath selection does have issues, mostly because it is something that is built on the fly for a view, rather than using the vendor-provided tools. If you can avoid it, I would.

**Comment by Fanch-** [comment]
Well, it might be interesting to point it in the documentation. Just saw that most of my appium workarounds were linked to XPath selectors. 

I guess we should use Xpath just to get parent element then, using **x/../../{....}.**, because from what I saw we can't do it using the the vendor-provided tools' way.
