### ISSUE TITLE
Grid Hub and Nodes stops after a node is turned off or cable unplugged

### ISSUE THREAD

**Issue by eliasnogueira** [appium/appium#6360]
Hello guys!

I facing a problem that I presume could be a bug.
I have a lot of devices in a grid (12), but it occurs with two or more devices.

**Configs (for testing propouse)**
- Selenium/Appium grid with a hub and node in same machine
- Nodes correctly configured (udid, appium post and bp port always unique)

**Scenario**
- Same app executing in parallel through separated threads

**Action**
- After the test execution in the devices I can do two things to throw the error:
- *\* Power off the device
- *\* Unplug the USB cable
- *\* [For emulator] Close the window of emulator

**Versions**
- Selenium Server 2.53.0
- Appium 1.5.1

*_Error *_
_on console (Eclipse)_
`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: UiAUtomator shut down unexpectedly (WARNING: The server did not provide any stacktrace information)`

_on node closed_
`Unhandled rejection Error: No device connected, cannot run adb shell command "am force-stop com.eliasnogueira.buttontest"`

_on the other nodes_
`Unhandled rejection Error: Error executing adbExec. Original error: Command '/Users/eliasnogueira/android-sdk/platform-tools/adb -P 5037 -s 192.168.56.102:5555 shell am force-stop com.eliasnogueira.buttontest' exited with code 255{"stdout":"","stderr":"error: device '192.168.56.102:5555' not found\n","code":255}`

**What I expect**
Not stop the Grid after the node stop (shutdown or unplug cable)

Full logs attached.

[console_eclipse.txt](https://github.com/appium/appium/files/198105/console_eclipse.txt)
[node_closed.txt](https://github.com/appium/appium/files/198106/node_closed.txt)
[other_nodes.txt](https://github.com/appium/appium/files/198107/other_nodes.txt)

Any help would be much appreciated! :slight_smile:

**Comment by dpgraham** [comment]
I don't think this is something that can be resolved on the Appium side. If I understand, the issue has to do with one of the nodes shutting down and then all of the tests halt. This would have to be fixed on Selenium Grid.

**Comment by vikramvi** [comment]
@eliasnogueira did you manage to get this issue fixed ? It will be helpful to community in case you can give more details here.

**Comment by eliasnogueira** [comment]
Hello guys!
As my main problem is about power off the device (the battery goes down) I put a usb hub with a good power charge. But if I manually disconnect the device, or the device or emulator goes off the error persist.

Just to mention it occurs in Windows and Linux environment .

**Comment by vikramvi** [comment]
@eliasnogueira can you re-open the bug please, as currently it's in closed state

**Comment by eliasnogueira** [comment]
I cannot reopen the issue :(
I gonna put this issue on Selenium Grid and ask for help to analyze this issue and try to solve it.

**Comment by eliasnogueira** [comment]
Issue on SeleniumHQ/Selenium
https://github.com/SeleniumHQ/selenium/issues/3300

**Comment by dpgraham** [comment]
@imurchie @jlipps can you guys confirm if this is an Appium issue or a Selenium grid issue.

**Comment by jlipps** [comment]
Hmm, it sounds like it's an adb issue, or a uiautomator issue. @eliasnogueira what did you observe on the device attached to the closed node? Did the device itself crash or go offline?
