### ISSUE TITLE
Appium install － npm install -g appium  prompt error information

### ISSUE THREAD

**Issue by gymg** [appium/appium#6369]
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! path /Users/tanlinzhen/.npm-packages/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/Users/tanlinzhen/.npm-packages/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/Users/tanlinzhen/.npm-packages/lib/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/tanlinzhen/.npm-packages/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tanlinzhen/npm-debug.log

**Comment by imurchie** [comment]
You don't have write access to ` /Users/tanlinzhen/.npm-packages/lib/node_modules`. Did you install something with sudo?

**Comment by gymg** [comment]
sudo npm install，I should uninstall and reinstall it?

**Comment by priyankshah217** [comment]
Do not use sudo to install appium

**Comment by imurchie** [comment]
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by gymg** [comment]
install appium , i user npm install -g appium is result of  above error prompt

**Comment by imurchie** [comment]
But npm was installed with sudo, so the directories that were created then are not writeable by the normal user. This is not an Appium issue (try something like `npm install -g glob` to see that any package will fail).

**Comment by gymg** [comment]
thanks , all partner

**Comment by gymg** [comment]
@imurchie  thanks   ,  appoint appium version " npm install -g appium@1.5.0-beta4" ,solution to the problem

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by SrinivasanTarget** [comment]
@triager please close
