### ISSUE TITLE
Feature request: Return an error when an Android ListView child view is scrolled off screen

### ISSUE THREAD

**Issue by alewang** [appium/appium#6370]
## The problem

When an AndroidElement is retrieved for the first child view under a ListView, the AndroidElement's getText, getLocation, and getSize methods will return unexpected values when the the child view is scrolled out of view. When the child view is scrolled out of view, the AndroidElement's getText, getLocation, and getSize methods will return values for the ListView's new and current first child, which is different from the original first child.
## Environment
- Appium version that exhibits the issue: 1.5.1
- Last Appium version that did not exhibit the issue (if applicable): N/A
- Desktop OS/version used to run Appium: OS X 10.10.5
- Node.js version (unless using Appium.app|exe): v5.8.0
- Mobile platform/version under test: Android
- Real device or emulator/simulator: Real device, Android 4.4.4
- Appium CLI or Appium.app|exe: CLI
## Details

The sample code project includes a sample app, whose UI is just a list view with list items numbered sequentially from 0 to 99. The Appium sample code will retrieve the first child element of the list view and print out the element's position, size, and text. The test will then swipe the list view upward so the "0" list item is out of view. The test will then use the same reference to the first child and try to print the child's position, size, and text again. The test's second attempt to print these values out will actually print out the position, size, and text for the list view's **current** and **new** first child.

For example, on my device, after the scrolling step, the first child element in the list view becomes the element containing the text "9". Using getText on the original first child element's reference returns "9", indicating the first child's AndroidElement has resolved the request using properties of the 9th data item in the list.
## Link to Appium logs

https://gist.github.com/alewang/126e7e0bdb296d06c1658d6980fb5bda
## Code To Reproduce Issue

This project contains the Appium code that demonstrates the issue: https://github.com/alewang/Appium-List-View-Child-Bug. The sample APK that's included in that project can be built from the source code in the following project: https://github.com/alewang/Appium-List-View-Demo.

---

I'm not sure if this is the intended behavior, but it's definitely not something I expect. I was expecting some exception to be thrown indicating that the UI element is no longer on the screen. Instead, the first child's AndroidElement reference ends up resolving against a different child of the ListView.

Consider the following one-line excerpt from the Appium log:

```
[HTTP] --> GET /wd/hub/session/27dca1a8-59f2-4dcf-9e17-5ed8a1382269/element/2/text {}
```

This call occurs right before the driver session is closed, meaning that this call is made from the getText method, called after the flinging operation is performed. The endpoint shown still uses the element ID for the original, first child element of the list view, but it ends up returning the text for the current and new first child of the list.

I'm posting this as a feature request, because I do not recall previous versions of Appium ever throwing exceptions on list view elements that are no longer valid. This would be an excellent feature to have because it would allow the community to write tests that can detect when certain elements have been scrolled off screen.

**Comment by jlipps** [comment]
@alewang thanks for the request. I'll add this to our backlog. In the meantime, have you tried the new uiautomator2 automation backend? Does it exhibit the same behavior?

**Comment by dpgraham** [comment]
Closing this issue. If this problem still persists on UIAutomator2, will re-open.
