### ISSUE TITLE
scroll to element only scrolls one screen

### ISSUE THREAD

**Issue by adigrinvald** [appium/appium#6371]
when using            js.executeScript("mobile: scroll", scrollObject) instead of scrolling to element only one scroll is performed. If object is in the bottom and you need to scroll more than once to see it than scroll doesn't get to the object.
## Environment

* Appium version1.5.0
* Last Appium version that did not exhibit the issue 1.4.16
* Desktop OS/version used to run Appium:10.11.13
* Node.js version (unless using Appium.app|exe):v5.8.0
* Mobile platform/version under test:iOS
* Real device or emulator/simulator:Real devices iOS8/9
* Appium

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
 public void scrollToListItemElement(MobileElement scrollToElement, MobileElement optionalOverlappingElement) {

            int initialHeight = scrollToElement.getCenter().getY();
            JavascriptExecutor js = driver;
            String webElementId = scrollToElement.getId();

            HashMap<String, String> scrollObject = new HashMap<>();
            scrollObject.put("element", webElementId);
            scrollObject.put("direction", "down");
            js.executeScript("mobile: scroll", scrollObject);
        
        }

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.
[Archive.zip](https://github.com/appium/appium/files/204246/Archive.zip)

**Comment by imurchie** [comment]
Scrolling to an element is no longer supported in Appium 1.5. `mobile: scroll` with an element scrolls _on that element_. That is why it does nothing when called again. Try using `mobile: scroll` without the element, checking if the element is visible and re-scrolling if not.

```
element = find_element()
while (element.is_not_visible) {
    scroll down
}
```

**Comment by chrigrahcisco** [comment]
Is there a particular reason this is no longer supported?  `mobile: scrollTo` was always successful (on iOS at least) and required no complicated logic. Just a one-liner and viola! your element was scrolled into physical view without issue.

**Comment by imurchie** [comment]
I think the reasoning was that (a) it is non-standard API, which we are trying to reduce, (b) it works differently in iOS and Android, and (c) it should be implemented in the clients, not the server.

**Comment by SrinivasanTarget** [comment]
@adigrinvald please reopen if you have any issues.

**Comment by SrinivasanTarget** [comment]
@triager please close
