### ISSUE TITLE
Appium 1.5.1 error: Trying to start iOS log capture but it's already started!

### ISSUE THREAD

**Issue by wkoszek** [appium/appium#6373]
## The problem

I'm getting:

```
======================================================================
ERROR: test_accelerate_accOff (__main__.AccelerateTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wkoszek/r/autotest/AccelerateTests.py", line 49, in setUp
    testutils.setupTest(self, libcb)
  File "/Users/wkoszek/r/autotest/testutils.py", line 164, in setupTest
    adb.launch_activity(app.mainactivity())
  File "/Users/wkoszek/r/autotest/kitchen/kitchen.py", line 56, in launch_activity
    self.d.launch_app()
  File "/usr/local/lib/python2.7/site-packages/appium/webdriver/webdriver.py", line 529, in launch_app
    self.execute(Command.LAUNCH_APP)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 233, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/appium/webdriver/errorhandler.py", line 29, in check_response
    raise wde
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Trying to start iOS log capture but it's already started!
```
## Environment
- 1.5.1
- 1.4.13 from DMG from Appium.app works fine,.
- 10.11.4
- node v5.9.1
- iPhone 5s
- iOS 9.2.1
## Details

Getting `Trying to start iOS log capture but it's already started!`. I tried searching around issues, and people did have similar problems, but with older Appium versions. I tried playing with capabilities (removing `fullReset`, `noReset`, `autoLaunch`). No avail. Same with `--native-instruments-lib`. Problem didn't go away.

With `Appium.app` from Appium website which comes with appium 1.4.13 I'm **not** hitting this problem.
## Link to Appium logs

https://gist.github.com/wkoszek/7782c1e7e334fab71b306a3e3211941d
## Code To Reproduce Issue [ Good To Have ]

From the trace above you can see Appium seems to die on app launch. I'm running from the framework we've made at work, so I'm not pasting everything, but these are the capabilities I'm sending in a request:

```
           caps = {
                    'app': app_path,
                    'appName':'kitchensink',
                    'platformName': 'iOS',
                    'platformVersion': KitchenApp.configuration["sim_version"],
                    'deviceName': iphone_model,
                    'udid' : KitchenApp.configuration["serial_number"],
                    'fullReset': False,
                    'noReset' : False,
                    'autoLaunch': False,
                    'newCommandTimeout': 0, # disable the new command timeout.
                    'nativeInstrumentsLib': True,
                    'showIOSLog': True
                    }
            command_executor='http://127.0.0.1:4723/wd/hub'
            start = time.time()
```

**Comment by imurchie** [comment]
I have a solution for this that I am trying to get through our build. I'll note here when it is done.

**Comment by imurchie** [comment]
The fix for this is in `appium-ios-driver@1.11.1`. If you are running from source you can update the package. If you are running from npm, reinstall with the `--no-shrinkwrap` flag to get the latest version.

**Comment by wkoszek** [comment]
@imurchie So I tried the following command:

```
npm install -g --no-shrinkwrap appium-ios-driver@1.11.1
```

The outcome of the command is here:  https://gist.github.com/wkoszek/d52486a6b1cf8eeb021603aa9e4c031e

Afterwards I tried running same 1.5.1 `appium`:

https://gist.github.com/wkoszek/6fb7177e2ec77a535022ff56236e1fa8

Am I doing something incorrectly?

**Comment by imurchie** [comment]
Sorry. You will need to install all of Appium using the flag. `npm install -g appium --no-shrinkwrap` ought to get you the latest published code from sub-packages.

**Comment by wkoszek** [comment]
@imurchie Thanks. I had no luck with it on the 1st try. I then wiped the whole `npm` registry and I re-created it once again. So looks like it helped with this particular problem. I've hit something else, but will open a separate problem.
