### ISSUE TITLE
[Appium 1.5.1]  "A session is either terminated or not started" running for 10min on 5  Android devices

### ISSUE THREAD

**Issue by mittt** [appium/appium#6374]
## The problem

I have a test that waits for 100min for an element to disappear - It check every 30s if it's displayed. I have cut it down, so you can test with it(source code below).

I think I'm reporting 2 different issues, here.

**The first one is an error if the test is run on 1 Android device:**
"A connection that was expected to be kept alive was closed by the server." error.  ([Stack Trace](https://gist.github.com/mittt/59f7a724b9d21c1b99ca9dd43833f3d4))
The appium log just says": "[HTTP] --> DELETE /wd/hub/session..." out of nowhere. ([Log, here](https://gist.github.com/mittt/3ef4ebb38c3b73e94e2c3399e3c0b5ba))

**If the test is running in parallel on 5 Android devices:**
The first 4 fail with  "A session is either terminated or not started" 10-20 min into execution ([Stack trace](https://gist.github.com/mittt/ddbdd50200c30b0af9c39e3c529a79e8)). 
The appium log looks the same to me, as in the first case. ([Log, here](https://gist.github.com/mittt/61e9227f3be1e76f8c8e5f97e8e68e86))

The 5th device fails like the first case, as if started alone. ([Log, here](https://gist.github.com/mittt/3ef4ebb38c3b73e94e2c3399e3c0b5ba))
## Environment
- Appium version (or git revision) that exhibits the issue: Appium v1.5.1 (REV 566147c20d5342b02f92e579a4a152701ed45b09) (Update on 06-04-2016)
- Desktop OS/version used to run Appium: Windows 10 64x
- Node.js version (unless using Appium.app|exe): node: '5.9.1'
- Mobile platform/version under test: Android 
- Real device or emulator/simulator: case 1: 1 real; case 2: 5 real in parallel
- Appium CLI or Appium.app|exe: cli
## Link to Appium logs

Appium Logs- parallel run:
[log_0.txt](https://github.com/appium/appium/files/206610/log_0.txt)
[log_1.txt](https://github.com/appium/appium/files/206606/log_1.txt)
[log_2.txt](https://github.com/appium/appium/files/206609/log_2.txt)
[log_3.txt](https://github.com/appium/appium/files/206607/log_3.txt)
[log_4.txt](https://github.com/appium/appium/files/206608/log_4.txt)
## Code To Reproduce Issue

[The test](https://gist.github.com/mittt/ad4f2f5e7dd1c5ee3ac25f85fb3d6f37)

**Comment by imurchie** [comment]
The Appium server is getting an HTTP request to delete the session. This seems like an issue with the client timing itself out. 

Can you look at the network traffic from the client?

**Comment by mittt** [comment]
Yes, I'll try to record it tomorrow.

Also, while I was writing the issue i noticed that in the "first case" i get a screenshot at the end. That's part my TearDown, so It looks like it's not a problem with the Appium node - that leaves the Client lib, the Hub or NUnit3. I would rule out NUnit, because I use the same setup for many other tests and only this one fails. I'll try to give more info tomorrow.

**Comment by mittt** [comment]
https://drive.google.com/file/d/0B1LbMaNqM7sDOU1hR2FxeDVRM28/view?usp=sharing
This is recorded with [Fiddler](http://www.telerik.com/fiddler), it's free. I couldn't make WireShark record Outgoing traffic. I ran it on 2 devices in parallel.
[log_0.txt](https://github.com/appium/appium/files/208009/log_0.txt)
[log_1.txt](https://github.com/appium/appium/files/208010/log_1.txt)

It looks like it's not the client lib. I got the "A session is either terminated or not started"  error on both.

**Comment by mittt** [comment]
Is my code enough to replicate it?

**Comment by mittt** [comment]
It still crashes the same way - everything was updated Friday. I'm updating again, now, I'll tell you the results tomorrow.

**Comment by imurchie** [comment]
The server is still getting a DELETE request to remove the session. There is nothing wrong in the logs.

I can't use Fiddler. It only seems to work on Windows and I don't have access to a Windows machine.

**Comment by mittt** [comment]
There is no DELETE coming from the client. This is from the recording:
![untitled](https://cloud.githubusercontent.com/assets/8478583/14616558/99308bd2-05b3-11e6-942c-bc5b8cf52731.png)

Also you can check it by unzipping it, It's readable even without Fiddler.

Have you tried running the sample code I've attached. It fails consistently if run in parallel, through a hub. I'll try to narrow it down tomorrow - i'll test without the hub and also on a single device, again.

**Comment by imurchie** [comment]
I can't run the code you sent. I don't even know what language it is.

The server logs are definitely seeing a DELETE request _prior_ to getting the request for the element highlighted above. It's coming through HTTP so it's not something the server itself is doing.

**Comment by mittt** [comment]
Soo, it's something the hub is popping up out of nowhere.

The code is a simple C# class. Earlier I asked if it usable. OK, i'll send you a complete project you can run.

**Comment by mittt** [comment]
I found that I have  a timeout set to 30000 in my nodeconfig JSON that is used to start appium.

The problem occurs only when the client is sleeping for exactly 30s. If the timeout is less then the sleep - for example if we sleep for 35s - the client gets a proper exception about inactivity.

If you are not interested in fixing this, close the issue. I'll manage my timeouts and sleeps better.

**Comment by mittt** [comment]
I think i found the source of the other error - the KeepAliveFailure. 
![wireshark](https://cloud.githubusercontent.com/assets/8478583/14818274/ef041d14-0bc4-11e6-8b64-f2b014a644da.png)


This time out is set on the Jetty server on the hub:
  <session-config>
    <session-timeout>30</session-timeout>
  </session-config>

I'll keep it in mind when writing my tests.

**Comment by ajit-jadhav** [comment]
Facing same issue while executing multi configuration job in jenkins for appium-android.

**Comment by jlipps** [comment]
This is not an appium problem per se, closing.
