### ISSUE TITLE
The problem described in https://github.com/appium/appium/issues/5392 and https://github.com/appium/appium/issues/5766 is back again on 1.5.1

### ISSUE THREAD

**Issue by senevit4** [appium/appium#6378]
The problem described in https://github.com/appium/appium/issues/5392 and https://github.com/appium/appium/issues/5766 is back again on 1.5.1

But now it looks like:
[HTTP] <-- POST /wd/hub/session 200 9881 ms - 715 
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.1","revision":"ee51200036dac07568da29b8aa88c0335ea6a514"}}
[HTTP] <-- GET /wd/hub/status 200 7523 ms - 121 
[HTTP] --> POST /wd/hub/session/61069cd4-a2f3-43e2-a527-1646ba48efb9/appium/device/app_installed {"bundleId":"com.myapp"}
[MJSONWP] Calling AppiumDriver.isAppInstalled() with args: ["com.myapp","61069cd4-a2f3-43e2-a527-1646ba48efb9"]
[debug] [iOS] Executing iOS command 'isAppInstalled'
[HTTP] <-- POST /wd/hub/session/61069cd4-a2f3-43e2-a527-1646ba48efb9/appium/device/app_installed 501 5 ms - 122 
[HTTP] --> DELETE /wd/hub/session/61069cd4-a2f3-43e2-a527-1646ba48efb9 {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["61069cd4-a2f3-43e2-a527-1646ba48efb9"]
[debug] [iOS] Deleting ios session
[debug] [UIAuto] Destroying instruments client socket.
[debug] [UIAuto] Closing socket server.
[debug] [UIAuto] Instruments socket server was closed
[debug] [Instruments] Starting shutdown.
[debug] [Instruments] Sending sigterm to instruments

This problem was fixed here https://github.com/appium/appium/pull/5405 but this fix disappeared from appium(downloaded from brew). Now, after appium source code refactoring, it's hard to find where to apply this changes.

**Comment by SrinivasanTarget** [comment]
@senevit4 Can you please follow our issue template and reopen a new issue with proper description if you face any issues in Appium 1.5.2.Closing this for now.

**Comment by SrinivasanTarget** [comment]
@triager please close
