### ISSUE TITLE
Not logging adb logcat in the console/file/webhook

### ISSUE THREAD

**Issue by anshumanchatterji** [appium/appium#6379]
## The problem

Appium is starting adb logcat process, but not writing the logs in its console or file or webhook. This seems to be an issue with the ConsoleLogLevel which is always coming to be debug. There is no option to set this with UI, and setting it with command line is not working.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.4.16.1 (Windows)
* Last Appium version that did not exhibit the issue (if applicable): dont know
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): using appium.exe
* Mobile platform/version under test: Android Marshmallow
* Real device or emulator/simulator: RealDevice
* Appium CLI or Appium.app|exe: Appium.exe

## Link to Appium logs

[AppiumLogs.txt](https://github.com/appium/appium/files/208384/AppiumLogs.txt)

**Comment by SrinivasanTarget** [comment]
@anshumanchatterji please try in appium 1.5.2.Install the same via. npm install -g appium.Please reopen the issue with latest logs incase if you hit the same.

**Comment by SrinivasanTarget** [comment]
@triager please close
