### ISSUE TITLE
iOS could not reset emulator when noReset flag is false in capabilities

### ISSUE THREAD

**Issue by trigoesrodrigo** [appium/appium#6380]
## The problem

Passing `noReset:false` in the device capabilities is not working. The iOS simulator doesn't reset the app data. 
The appium logs show that appium is not being able to reset the simulator:

```
[debug] [iOSSim] Simulator files not fully created. Waiting a bit
[debug][iOS] Could not reset simulator. Leaving as is
```
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.1
- Last Appium version that did not exhibit the issue (if applicable): 1.4.16
- Desktop OS/version used to run Appium: OSX 10.11.4
- Node.js version (unless using Appium.app|exe): v0.12.9
- Mobile platform/version under test: iOS 9.1 and iOS 9.2
- Real device or emulator/simulator: simulator
- Appium CLI or Appium.app|exe: CLI
## Link to Appium logs

[Appium log](https://gist.github.com/trigoesrodrigo/8756709897c309dad05eeb5e92a8e41c)
## Code to reproduce the issue

[HelloWorld Cordova project](https://github.com/trigoesrodrigo/cordova-helloworld)

```
npm install
mocha tests/sample.spec.js
```

**Comment by alexcosmin** [comment]
I have exactly the same issue. Passing `"fullReset": "true"`  in the device capabilities works, but would be nice to get `"noReset": "false"` working as well.

**Comment by jlipps** [comment]
@alexcosmin are you still experiencing this issue with the latest version of Appium? We've updated the reset logic a fair amount.

**Comment by SrinivasanTarget** [comment]
@triager please close
