### ISSUE TITLE
Instruments fail to launch on iOS 9.1 Simulator

### ISSUE THREAD

**Issue by alsorokin** [appium/appium#6383]
## The problem

The instruments fail to launch on iOS 9.1 simulator. Please see the logs below.
What caught my attention is the device string which seems malformed: 'iPhone 6s (9.1) ['

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.0
* Node.js version (unless using Appium.app|exe): 0.12.2
* Mobile platform/version under test: iOS 9.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/alsorokin/d34eb052ed58a7d8e0b43ab27bf42c3c

**Comment by imurchie** [comment]
The device being `iPhone 6s (9.1) [` is expected. Instruments doesn't care, but this allows us to distinguish from iPhones that are paired to Apple watch devices. Without the `[` Instruments would fail with an ambiguous device name.

**Comment by imurchie** [comment]
Things are timing out. Can you run `xcrun simctl list` and give the output here?

**Comment by alsorokin** [comment]
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad Pro (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
Apple TV 1080p (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
== Runtimes ==
iOS 8.4 (8.4 - 12H141) (com.apple.CoreSimulator.SimRuntime.iOS-8-4)
iOS 9.1 (9.1 - 13B137) (com.apple.CoreSimulator.SimRuntime.iOS-9-1)
tvOS 9.0 (9.0 - 13T393) (com.apple.CoreSimulator.SimRuntime.tvOS-9-0)
watchOS 2.0 (2.0 - 13S343) (com.apple.CoreSimulator.SimRuntime.watchOS-2-0)
== Devices ==
-- iOS 8.4 --
-- iOS 9.1 --
    iPhone 5s (F649CE8F-F03E-4810-AD10-CB04A5530619) (Shutdown)
    iPhone 6s (D49E1A17-16DF-4872-BB5E-E93D670DC3DC) (Shutdown)
    iPhone 6s Plus (DA6D3C8F-39BE-486B-A6DB-362B7BA75FD3) (Booted)
-- tvOS 9.0 --
-- watchOS 2.0 --
    Apple Watch - 38mm (867BF7EA-8F26-413D-9357-0B69CA641D5D) (Shutdown)
    Apple Watch - 42mm (64965031-7B91-422C-8676-92E52307406B) (Shutdown)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-8-3 --
    iPhone 4s (291BFE36-8AE6-4A96-AD80-89CB51164DB7) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (B3745DFA-7C6E-4830-BBD9-BDA89F355F78) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (B922A6B8-20B8-46CC-8E28-C97CD214630D) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (90CE44DB-04EA-4741-B592-6D3D5FFE0C42) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-9-0 --
    iPhone 5s (85338552-2275-4696-B1FE-2F4027EA8DBC) (Shutdown) (unavailable, runtime profile not found)
== Device Pairs ==
07F3F091-62AC-4BF4-BBF8-0604DB444771 (disconnected)
    Watch: Apple Watch - 38mm (867BF7EA-8F26-413D-9357-0B69CA641D5D) (Shutdown)
    Phone: iPhone 6s (D49E1A17-16DF-4872-BB5E-E93D670DC3DC) (Shutdown)
42070555-E8BE-4A2B-BEE5-84298E345CC6 (disconnected)
    Watch: Apple Watch - 42mm (64965031-7B91-422C-8676-92E52307406B) (Shutdown)
    Phone: iPhone 6s Plus (DA6D3C8F-39BE-486B-A6DB-362B7BA75FD3) (Booted)

**Comment by imurchie** [comment]
Thanks!

Can you try running `xcrun simctl shutdown DA6D3C8F-39BE-486B-A6DB-362B7BA75FD3`, and then try running your test?

**Comment by alsorokin** [comment]
No changes :(
Here's the server log:
https://gist.github.com/alsorokin/13b4aff104631d36f65cfe84b858307b

**Comment by SrinivasanTarget** [comment]
@imurchie Its similar to #6380
