### ISSUE TITLE
appium unuseable with more than one phone

### ISSUE THREAD

**Issue by adamf663** [appium/appium#6384]
Problem started with appium 1.5.0 and carried onto 1.5.1.
I run a separate appium server for each phone, with separate -p and -bp ports.

When there is a second phone, appium will crash almost immediately.
It seems mostly when doing a screenshot, although the utter lack of any debugging log messages regarding the crash makes such a determination impossible.

It looks like the two instances are vying for the same adb.

Attached are logfiles, and the log messages of the running script including logcat messages.
[appium-crash.zip](https://github.com/appium/appium/files/210379/appium-crash.zip)

**Comment by SrinivasanTarget** [comment]
@adamf663 Can you please post logs here and also more details in your description like, client version, node version,code snippet of desired capabilitiesetc

**Comment by SrinivasanTarget** [comment]
Post your logs inform of gist would be very helpful

**Comment by adamf663** [comment]
I was delayed with the logfiles as your editor doesn't permitting attaching them directly!

**Comment by SrinivasanTarget** [comment]
Attach logs in form of gist. https://gist.github.com/

**Comment by adamf663** [comment]
Logfiles are in this issue in zip file appium-crash.zip
appium 1.5.1 with appium unlocker hacked out;  java-client 3.4.0
        capabilities = new DesiredCapabilities();
        // timeouts are in milliseconds
        capabilities.setCapability("deviceName", "Android phone");
        capabilities.setCapability("platformName", "ANDROID");
        capabilities.setCapability("noSign", true);
        capabilities.setCapability("appPackage", "com.android.settings");
        capabilities.setCapability("appActivity", ".Settings");
        capabilities.setCapability("newCommandTimeout", 30000); // how long before next command.. make it longer so appium won't kill itself
        capabilities.setCapability("udid", adbDevice);

adbDevice is variable for device id returned by 'adb devices'

**Comment by adamf663** [comment]
node 5.9.0

**Comment by SrinivasanTarget** [comment]
Need logs files in form of gist to act on. Attachments are not available on your comments.

**Comment by adamf663** [comment]
code snippet for screenshot.  At least this is where I think appium crashes.  It's hard to tell because it crashes without a message.   Why can't you see the 'appium-crash.zip' attached to the main issue?  I'm looking right at it, have no problem extracting it.  Why make extra hoops to jump through?

**Comment by SrinivasanTarget** [comment]
I don't see any attachments here, only text of "Logfiles are in this issue in zip file appium-crash.zip" is available. Where is the attachments here? Whats the android API level you are using?

**Comment by adamf663** [comment]
see the first part of this issue. It's right there.  Click on appium-crash.zip.  It works for me.  Why not for you?

I'm not using the android API.  The phone is lollipop 5.1.1.

**Comment by adamf663** [comment]
Your gist page doesn't work well.  It took four tries before I got it to accept three files.  I save it as a public gist and it only shows the third file under the first filename.  This is a serious pain in the ass.

**Comment by adamf663** [comment]
<script src="https://gist.github.com/adamf663/0b661bdef3f1dba46bb79f97e2d9e8e7.js"></script>

**Comment by adamf663** [comment]
https://gist.github.com/adamf663/0b661bdef3f1dba46bb79f97e2d9e8e7#file-appium-641227378-log

**Comment by SrinivasanTarget** [comment]
Looks like similar to https://github.com/appium/appium/issues/5318

**Comment by adamf663** [comment]
1) EPIPE error pretty much says nothing other than "something died".
2) 5318 is ios, mine is android.
3) preceding line indicates it was trying to take a screenshot which is one of the last things my script was trying to do.l  5318 was trying to getTreeForXML.  I see adb log statements indicating two devices using the same adb, over port 5037.    Last statements have *two* attempts to rm /data/local/tmp/screenshot.png.  I think it is a pretty safe bet that the IOS script isn't using adb. :-)

**Comment by SrinivasanTarget** [comment]
Not able to reproduce this from my end. Everything seems fine for me on iOS and Android parallel testing.

please refer that something you can able to improve on your framework based on,https://github.com/saikrishna321/AppiumTestDistribution

Ways to capture screenshots are still in a discussion from appium end.

**Comment by adamf663** [comment]
Did you perform screenshots, do an adb pull for the UIX  and use the settings app as the app under test?
IOS is irrelevant.

----- Original Message -----

**Comment by SrinivasanTarget** [comment]
I didn't check on settings app? Appium works fine for me on all below combinations of parallel testing,

1)Android and iOS devices 
2)Multiple Android devices
3)Multiple iOS devices

Will check the settings app

**Comment by adamf663** [comment]
did you try screen shots?  
did you try pulling a file?

I don't care about IOS.  

----- Original Message -----

**Comment by SrinivasanTarget** [comment]
Yes, Screenshot is pulled out.It works fine but haven't tried in settings app.

**Comment by adamf663** [comment]
It would be helpful if there was more debugging information available other than one word: EPIPE.

----- Original Message -----

**Comment by adamf663** [comment]
There are the exception line numbers:  Line 890, column 11 of util.js and line 771 column 14 of net.js.

----- Original Message -----

**Comment by SrinivasanTarget** [comment]
Ok @imurchie Any thoughts on this?

**Comment by adamf663** [comment]
perhaps related:
https://github.com/appium/appium/issues/6202
https://github.com/appium/appium/issues/5982


----- Original Message -----

**Comment by saikrishna321** [comment]
@adamf663 yeah i'm able to capture screenshot when running tests in parallel.

```
 File scrFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
 FileUtils.copyFile(scrFile, new File("Screenshot.png"));
```

**Comment by adamf663** [comment]
and pull files,  simultaneously on multiple devices?  what about increasing debugging to there is more information than "appium crashed"? 

On April 13, 2016 11:06:20 PM MDT, Sai Krishna <notifications@github.com> wrote:
>@adamf663 yeah i'm able to capture screenshot when running tests in
>parallel.
>
>```
>File scrFile = ((TakesScreenshot)
>driver).getScreenshotAs(OutputType.FILE);
> FileUtils.copyFile(scrFile, new File("Screenshot.png"));
>```
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/appium/appium/issues/6384#issuecomment-209763395

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by saikrishna321** [comment]
@adamf663 yah on multiple devices simultaneously

**Comment by adamf663** [comment]
What about getting some debugging output? You success doesn't help me and I don't even know if screenshots are the problem! 

On April 14, 2016 11:12:19 AM MDT, Sai Krishna <notifications@github.com> wrote:
>@adamf663 yah on multiple devices simultaneously 
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/appium/appium/issues/6384#issuecomment-210054576

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by imurchie** [comment]
I have added error handling to the stdio streams in our process manager (`teen_process@1.6.0`). I'm hoping this gives some visibility into the issue, and also stops Appium from crashing when this sort of error happens. But given that I can't reproduce it, I'm not entirely sure.

**Comment by adamf663** [comment]
I need error reporting *now*. Regardless of your inability to reproduce my problems, I can't use appium 1.5 with two phones and appium 1.4's bugs keep it from performing the simplest tasks like setting a field (clear field on a password field is unreliable even when performed three times for redundancy) I'm ready to abandon appium altogether. Its bugs far outweigh any added benefit. 

On April 15, 2016 10:13:57 AM MDT, "Isaac A. Murchie" <notifications@github.com> wrote: 



I have added error handling to the stdio streams in our process manager ( teen_process@1.6.0 ). I'm hoping this gives some visibility into the issue, and also stops Appium from crashing when this sort of error happens. But given that I can't reproduce it, I'm not entirely sure.

**Comment by adamf663** [comment]
No response.  Appium is still unuseable for me sincel 1.5.  Must I completely abandon using appium and move to using uiautomator directly?

----- Original Message -----

**Comment by adamf663** [comment]
Wiped appium and rebuilt 1.5.1, with the only "hack" being the removal of the unlock (phone borking) code.

I removed the UIXfile upload in the screen shot method as it crashed appium every time when there were multiple phones.

Now it crashes at pressKeyCode(AndroidKeyCode.KEYCODE_POWER), again with the meaningless EPIPE error.

I'm asuming I will continue to get abject silence on my REPEATED requests for some error reporting other than CRASH!  (EPIPE).
Assuming the silence continue this week, I'll be ripping appium out of my automation framework and it will be good riddance!


----- Original Message -----

**Comment by adamf663** [comment]
It's looking like anytime an adb command is issued, appium crashes.

----- Original Message -----

**Comment by imurchie** [comment]
Getting no response surprises you? Your comment was designed to alienate everyone working on the project.

This is an open source project. We try to get to issues as soon as we can, but there is a lot of work to be done and not a lot of people working on it. In your case you've **demanded** we fix problems that we cannot reproduce.

If you'd like to _help_, the source is available and we can give some direction in how to go about debugging and fixing the issues. Otherwise, I'm not sure what can be done.

**Comment by adamf663** [comment]
fix it would be nice.  provide ANY error reporting.   But I'm  out of patience.  It is clear I have to get rid if appium. 

On April 20, 2016 4:49:04 PM MDT, "Isaac A. Murchie" <notifications@github.com> wrote:
>Getting no response surprises you? Your comment was designed to
>alienate everyone working on the project.
>
>This is an open source project. We try to get to issues as soon as we
>can, but there is a lot of work to be done and not a lot of people
>working on it. In your case you've **demanded** we fix problems that we
>cannot reproduce.
>
>If you'd like to _help_, the source is available and we can give some
>direction in how to go about debugging and fixing the issues.
>Otherwise, I'm not sure what can be done.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/appium/appium/issues/6384#issuecomment-212642573

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by adamf663** [comment]
THIS HAS NOT BEEN FIXED AND IS AN INCREDIBLY SERIOUS DEFECT.  The root cause is that issuing an adb command crashes appium!!
