### ISSUE TITLE
Not able to download Appium for mac

### ISSUE THREAD

**Issue by hpalusa** [appium/appium#6389]
Hi , 

Its is pleasure to take help , I was not able to download appium from 2days , I am getting network errors and some time it is showing as 178/178 MB 0 secs left  and it is not dowloading at all :( 
In dowload folder it is showing as "Unconfirmed 729930.crdownload" Please help me out in this issue.

**Comment by scottdixon** [comment]
@hpalusa - do you hit the same issue in another browser?

**Comment by SrinivasanTarget** [comment]
Refer https://github.com/appium/appium/issues/6038 It should work

**Comment by SrinivasanTarget** [comment]
@triager please close
