### ISSUE TITLE
Searching within context of element - Accessibility ID - IOS

### ISSUE THREAD

**Issue by mbknieri** [appium/appium#6391]
## The problem

When attempting to search for an element with the context of another element using the accessibility id search strategy, Appium is returning that the element is a child of this element when it is, in fact, not a child of that element. I am finding this issue both on the Appium client(v1.4.13) and on the Appium server.

## Environment

* Appium v1.4.16
* El Capitan (10.11.4)
* Node v4.2.3
* IOS v9.2 Simulator 

## Details

Example:

Parent Element has name "Parent Element"
Child Element has name: "Child Element"
When search for this element using name strategy under Parent Element, Appium returns with an error that there are no elements under Parent Element with the name Child Element. 
When searching for this element using the id strategy under Parent Element, Appium returns that there are elements under Parent Element with the id Child Element.

## Link to Appium logs

I cannot provide a link to gist, but below are the Appium logs demonstrating the results of the above example:

Searching using the name strategy:

info: --> POST /wd/hub/session/11f681e0-29d9-4562-bbb9-fc19e58fe65c/element {"using":"name","value":"Parent Element"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByName('Parent Element')"
info: [debug] Sending command to instruments: au.getElementByName('Parent Element')
info: [debug] [INST] 2016-04-11 16:41:41 +0000 Debug: Got new command 38 from instruments: au.getElementByName('Parent Element')
info: [debug] [INST] 2016-04-11 16:41:41 +0000 Debug: evaluating au.getElementByName('Parent Element')
info: [debug] [INST] 2016-04-11 16:41:41 +0000 Debug: evaluation finished
info: [debug] [INST] 2016-04-11 16:41:41 +0000 Debug: Lookup returned [object UIATableCell] with the name "Parent Element" (id: 22).
info: [debug] [INST] 2016-04-11 16:41:41 +0000 Debug: responding with:
info: [debug] [INST] 2016-04-11 16:41:41 +0000 Debug: Running system command #39: /usr/local/bin/node /Users/a533971/Desktop/Appium/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"22"}}...
info: [debug] Socket data received (39 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"22"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"22"},"sessionId":"11f681e0-29d9-4562-bbb9-fc19e58fe65c"}
info: <-- POST /wd/hub/session/11f681e0-29d9-4562-bbb9-fc19e58fe65c/element 200 298.012 ms - 88 {"status":0,"value":{"ELEMENT":"22"},"sessionId":"11f681e0-29d9-4562-bbb9-fc19e58fe65c"}
info: --> POST /wd/hub/session/11f681e0-29d9-4562-bbb9-fc19e58fe65c/element/22/elements {"using":"name","value":"Child Element"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementsByName('Child Element', '22')"
info: [debug] Sending command to instruments: au.getElementsByName('Child Element', '22')
info: [debug] [INST] 2016-04-11 16:41:42 +0000 Debug: Got new command 39 from instruments: au.getElementsByName('Child Element', '22')
info: [debug] [INST] 2016-04-11 16:41:42 +0000 Debug: evaluating au.getElementsByName('Child Element', '22')
info: [debug] [INST] 2016-04-11 16:41:42 +0000 Debug: evaluation finished
info: [debug] [INST] 2016-04-11 16:41:42 +0000 Debug: responding with:
info: [debug] [INST] 2016-04-11 16:41:42 +0000 Debug: Running system command #40: /usr/local/bin/node /Users/a533971/Desktop/Appium/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":[]}...
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":[]}
info: [debug] Condition unmet after 1051ms. Timing out.
info: [debug] Responding to client with success: {"status":0,"value":[],"sessionId":"11f681e0-29d9-4562-bbb9-fc19e58fe65c"}

Searching using the accessibility id strategy:

info: <-- POST /wd/hub/session/11f681e0-29d9-4562-bbb9-fc19e58fe65c/element/22/elements 200 1052.141 ms - 74 {"status":0,"value":[],"sessionId":"11f681e0-29d9-4562-bbb9-fc19e58fe65c"}
info: --> POST /wd/hub/session/11f681e0-29d9-4562-bbb9-fc19e58fe65c/element {"using":"name","value":"Parent Element"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementByName('Parent Element')"
info: [debug] Sending command to instruments: au.getElementByName('Parent Element')
info: [debug] [INST] 2016-04-11 16:41:57 +0000 Debug: Got new command 40 from instruments: au.getElementByName('Parent Element')
info: [debug] [INST] 2016-04-11 16:41:57 +0000 Debug: evaluating au.getElementByName('Parent Element')
info: [debug] [INST] 2016-04-11 16:41:57 +0000 Debug: evaluation finished
info: [debug] [INST] 2016-04-11 16:41:57 +0000 Debug: Lookup returned [object UIATableCell] with the name "Parent Element" (id: 23).
info: [debug] [INST] 2016-04-11 16:41:57 +0000 Debug: responding with:
info: [debug] [INST] 2016-04-11 16:41:57 +0000 Debug: Running system command #41: /usr/local/bin/node /Users/a533971/Desktop/Appium/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"23"}}...
info: [debug] Socket data received (39 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"ELEMENT":"23"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"23"},"sessionId":"11f681e0-29d9-4562-bbb9-fc19e58fe65c"}
info: <-- POST /wd/hub/session/11f681e0-29d9-4562-bbb9-fc19e58fe65c/element 200 478.987 ms - 88 {"status":0,"value":{"ELEMENT":"23"},"sessionId":"11f681e0-29d9-4562-bbb9-fc19e58fe65c"}
info: --> POST /wd/hub/session/11f681e0-29d9-4562-bbb9-fc19e58fe65c/element/23/elements {"using":"id","value":"Child Element"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.getElementsByAccessibilityId('Child Element', '23')"
info: [debug] Sending command to instruments: au.getElementsByAccessibilityId('Child Element', '23')
info: [debug] [INST] 2016-04-11 16:41:58 +0000 Debug: Got new command 41 from instruments: au.getElementsByAccessibilityId('Child Element', '23')
info: [debug] [INST] 2016-04-11 16:41:58 +0000 Debug: evaluating au.getElementsByAccessibilityId('Child Element', '23')
info: [debug] [INST] 2016-04-11 16:41:58 +0000 Debug: evaluation finished
info: [debug] [INST] 2016-04-11 16:41:58 +0000 Debug: responding with:
info: [debug] [INST] 2016-04-11 16:41:58 +0000 Debug: Running system command #42: /usr/local/bin/node /Users/a533971/Desktop/Appium/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":[]}...
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":[]}
info: [debug] Id selector, 'Child Element', not found in Localizable.strings.
info: [debug] Pushing command to appium work queue: "au.getElementsById('Child Element')"
info: [debug] Sending command to instruments: au.getElementsById('Child Element')
info: [debug] [INST] 2016-04-11 16:41:59 +0000 Debug: Got new command 42 from instruments: au.getElementsById('Child Element')
info: [debug] [INST] 2016-04-11 16:41:59 +0000 Debug: evaluating au.getElementsById('Child Element')
info: [debug] [INST] 2016-04-11 16:41:59 +0000 Debug: evaluation finished
info: [debug] [INST] 2016-04-11 16:41:59 +0000 Debug: Lookup returned [object UIATableCell] with the name "Child Element" (id: 24).
info: [debug] [INST] 2016-04-11 16:41:59 +0000 Debug: Lookup returned [object UIAStaticText] with the name "Child Element" (id: 25).
info: [debug] [INST] 2016-04-11 16:41:59 +0000 Debug: responding with:
info: [debug] [INST] 2016-04-11 16:41:59 +0000 Debug: Running system command #43: /usr/local/bin/node /Users/a533971/Desktop/Appium/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":[{"ELEMENT":"24"},{"ELEMENT":"25"}]}...
info: [debug] Socket data received (58 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":[{"ELEMENT":"24"},{"ELEMENT":"25"}]}
info: [debug] Responding to client with success: {"status":0,"value":[{"ELEMENT":"24"},{"ELEMENT":"25"}],"sessionId":"11f681e0-29d9-4562-bbb9-fc19e58fe65c"}
info: <-- POST /wd/hub/session/11f681e0-29d9-4562-bbb9-fc19e58fe65c/element/23/elements 200 2022.421 ms - 107 {"status":0,"value":[{"ELEMENT":"24"},{"ELEMENT":"25"}],"sessionId":"11f681e0-29d9-4562-bbb9-fc19e58fe65c"}

## Code To Reproduce Issue [ Good To Have ]

Original Element is obtained using WebElement originalElement = driver.findElement(By.id(<id>))
Child Element is obtained using WebElement childElement = originalElement.findElement(By.id(<id>))
childElement.isDisplayed() is returning true, even though there is no element under originalElement with the id. Also calling originalElement.findElement(By.id<id>)) is not throwing a NoSuchElementException.

**Comment by scottdixon** [comment]
@mbknieri - can you confirm the issue persists with Appium 1.5.1?

**Comment by mbknieri** [comment]
Hi @scottdixon 
Yes this is still happening with Appium v1.5.1. Since the name strategy has been removed in v1.5.1, I could only test searching within the context of another element using accessibility id.

These are the logs from Appium v1.5.1 (attempting to find Child Element within Parent Element, returning true, even though an element with name Child Element is not a child of Parent Element):

[HTTP] <-- GET /wd/hub/session/7105102a-ef7b-4a7f-94cc-d4c8769ff0e9/element/39/name 200 958 ms - 84 
[HTTP] --> POST /wd/hub/session/7105102a-ef7b-4a7f-94cc-d4c8769ff0e9/element {"using":"id","value":"Parent Element"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","Parent Element","7105102a-ef7b-4a7f-94cc-d4c8769ff0e9"]
[debug] [iOS] Executing iOS command 'findElement'
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [UIAuto] Sending command to instruments: au.getElementByAccessibilityId('Parent Element')
[debug] [Instruments] [INST] 2016-04-12 14:30:21 +0000 Debug: Got new command 117 from instruments: au.getElementByAccessibilityId('Parent Element')
[debug] [Instruments] [INST] 2016-04-12 14:30:21 +0000 Debug: evaluating au.getElementByAccessibilityId('Parent Element')
[debug] [Instruments] [INST] 2016-04-12 14:30:21 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-04-12 14:30:21 +0000 Debug: Lookup returned [object UIATableCell] with the name "Parent Element" (id: 40).
[debug] [Instruments] [INST] 2016-04-12 14:30:21 +0000 Debug: responding with:
[debug] [UIAuto] Socket data received (39 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"ELEMENT":"40"}}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"40"}
[HTTP] <-- POST /wd/hub/session/7105102a-ef7b-4a7f-94cc-d4c8769ff0e9/element 200 465 ms - 88 
[HTTP] --> POST /wd/hub/session/7105102a-ef7b-4a7f-94cc-d4c8769ff0e9/element/40/element {"id":"40","using":"id","value":"Child Element"}
[MJSONWP] Calling AppiumDriver.findElementFromElement() with args: ["id","Child Element","40","7105102a-ef7b-4a7f-94cc-d4c8769ff0e9"]
[debug] [iOS] Executing iOS command 'findElementFromElement'
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [UIAuto] Sending command to instruments: au.getElementByAccessibilityId('Child Element', '40')
[debug] [Instruments] [INST] 2016-04-12 14:30:21 +0000 Debug: Running system command #118: /usr/local/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/jk/d1_5sx3d2dg6lpwhp65j590801ft0l/T/instruments_sock 2,{"status":0,"value":{"ELEMENT":"40"}}...
[debug] [Instruments] [INST] 2016-04-12 14:30:22 +0000 Debug: Got new command 118 from instruments: au.getElementByAccessibilityId('Child Element', '40')
[debug] [Instruments] [INST] 2016-04-12 14:30:22 +0000 Debug: evaluating au.getElementByAccessibilityId('Child Element', '40')
[debug] [Instruments] [INST] 2016-04-12 14:30:22 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-04-12 14:30:22 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-04-12 14:30:22 +0000 Debug: Running system command #119: /usr/local/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/jk/d1_5sx3d2dg6lpwhp65j590801ft0l/T/instruments_sock 2,{"status":0,"value":""}...
[debug] [UIAuto] Socket data received (25 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
[debug] [UIAuto] Sending command to instruments: au.getElementById('Child Element')
[debug] [Instruments] [INST] 2016-04-12 14:30:23 +0000 Debug: Got new command 119 from instruments: au.getElementById('Child Element')
[debug] [Instruments] [INST] 2016-04-12 14:30:23 +0000 Debug: evaluating au.getElementById('Child Element')
[debug] [Instruments] [INST] 2016-04-12 14:30:23 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-04-12 14:30:23 +0000 Debug: Lookup returned [object UIATableCell] with the name "Child Element" (id: 41).
[debug] [Instruments] [INST] 2016-04-12 14:30:23 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-04-12 14:30:23 +0000 Debug: Running system command #120: /usr/local/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/jk/d1_5sx3d2dg6lpwhp65j590801ft0l/T/instruments_sock 2,{"status":0,"value":{"ELEMENT":"41"}}...
[debug] [UIAuto] Socket data received (39 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"ELEMENT":"41"}}
[MJSONWP] Responding to client with driver.findElementFromElement() result: {"ELEMENT":"41"}
[HTTP] <-- POST /wd/hub/session/7105102a-ef7b-4a7f-94cc-d4c8769ff0e9/element/40/element 200 2079 ms - 88

**Comment by mbknieri** [comment]
I was wondering if I can get an estimated time of when this issue will be resolved? I'm unfortunately stuck on v1.4.16 until this is fixed, since the name locator strategy is removed in v1.5. If this issue is not a priority to be resolved, is there a suggested workaround for v1.5?

**Comment by scottdixon** [comment]
Interesting. I see it first searches within the context of Parent Element and it can't find anything.
```
[UIAuto] Sending command to instruments: au.getElementByAccessibilityId('Child Element', '40')
...
[UIAuto] Got result from instruments: {"status":0,"value":""}
```

But then it immediately follows up with another search sans context argument:
```
[UIAuto] Sending command to instruments: au.getElementById('Child Element')
...
[UIAuto] Got result from instruments: {"status":0,"value":{"ELEMENT":"41"}}
```

I'm unable to repo this with the latest version of `appium-ios-driver`. Can you try your test on the latest version and let me know if the issue persists?

**Comment by mbknieri** [comment]
What do you mean by latest version of appium-ios-driver? Should I test against the latest version of appium(v1.5.2)? Latest java client?

**Comment by scottdixon** [comment]
@mbknieri test against https://github.com/appium/appium-ios-driver

Let me know if you need a hand setting it up.

**Comment by mbknieri** [comment]
I'm not sure how to run tests against appium-ios-driver so I am unable to verify that this issue is reproducible on the latest version. However, I did update the java-client to v4.0.0 and tested against Appium v1.5.3 and I am no longer seeing the issue!

**Comment by imurchie** [comment]
You're welcome! Glad things were resolved.
