### ISSUE TITLE
Add 'org.chromium.chrome' as a browser target

### ISSUE THREAD

**Issue by nmeason** [appium/appium#6393]
## The problem

Attempting to automate org.chromium.chrome/.com.google.android.apps.chrome.Main as a chrome browser. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.1
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OSX El Capitan
* Node.js version (unless using Appium.app|exe): 5.9.0
* Mobile platform/version under test: 4.4
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Passing in "browserName=chromium" in my AndroidDriver capabilities does not launch my version of Chromium. Would like an option to be passed in that allows launching the package/activity stated above.
This issue is exactly what https://github.com/appium/appium/pull/5807 describes, but has since been closed.

**Comment by imurchie** [comment]
That PR was on the old Appium, and seems to have languished as the new version was released. I am porting it over to the latest.

**Comment by nmeason** [comment]
Great thank you!

**Comment by imurchie** [comment]
I have published `appium-android-driver@1.9.1` with support for Chromium.

Since I don't have a Chromium development environment, can you update to this version of `appium-android-driver` and try it out? Thanks!

**Comment by nmeason** [comment]
Thanks for the fix. From testing so far this is working as expected.

**Comment by imurchie** [comment]
👍

**Comment by SrinivasanTarget** [comment]
@triager please close
