### ISSUE TITLE
avm cannot install Appium 1.5 and 1.5.1

### ISSUE THREAD

**Issue by derek1106** [appium/appium#6395]
Use the command to install Appium 1.5.1.
avm 1.5.1

I get the error as below and Appium 1.5.1 is not installed.
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/avm/versions/1.5.1/package.json'
npm WARN 1.5.1 No description
npm WARN 1.5.1 No repository field.
npm WARN 1.5.1 No README data
npm WARN 1.5.1 No license field.
/usr/local/bin/avm: line 286: appium: command not found
   installed :

**Comment by imurchie** [comment]
What is avm?

**Comment by SrinivasanTarget** [comment]
Appium version manager. This needs to be raised in a avm repo not here as
we don't maintain that repo.

**Comment by SrinivasanTarget** [comment]
Please raise your concern in https://github.com/abhinavsingh/avm.

Any issues related to avm cannot be answered here as we don't maintain.

**Comment by SrinivasanTarget** [comment]
You can install appium latest through "npm install appium"

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by derek1106** [comment]
Because some file path is changed in Appium 1.5, so avm cannot install it.
I make the change for avm file, then it can install all Appium versions.

1. in 'activate' function, link "node_modules/appium/build/lib/main.js" to "bin/appium".
2. in 'execute_with_version' function, use "node_modules/appium/build/lib/main.js" to start Appium.

**Comment by gvillafuerte2** [comment]
Hello Derek I would like to attempt your solution but i cant find the avm file. Could you please let me know where to edit it?
