### ISSUE TITLE
Return values for iOS window_handles are not protocol compliant (Appium 1.5+)

### ISSUE THREAD

**Issue by DylanLacey** [appium/appium#6396]
## The problem

Using Appium 1.5+ to get `window_handles` for iOS Safari sessions will return non-String results.  Numeric values are being returned which, depending on the language, might be cast as `Long`, `Fixnum` or others.

This is problematic for strongly typed clients (such as Java) as they expect `String`.  At runtime, receiving a `Long` causes an exception.

[The Webdriver 3 Standard](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-window-handle) explicitly specifies that Window Handles are `String`, as does [the WebDriver 2 JSON WP Standard](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#get-sessionsessionidwindow_handles).

## Environment

* Appium version 1.5 and up
* 1.4.something
* OS X 10.9
* Node.js version v5.10.0
* Mobile platform/version under test: iOS 9.0, iOS 8.2
* Real device or emulator/simulator: Simulator
* Appium CLI on above, also Sauce Labs

## Link to Appium logs

Probably not relevant?  I was able to repro this on multiple sites under test and different Appium deploys.

## Code To Reproduce Issue [ Good To Have ]

```ruby
require "selenium/webdriver"
require 'selenium/webdriver/remote/http/persistent'

def caps
  {
    'deviceName' => "iPhone Simulator",
    'browserName' => "safari",
    'platformVersion' => '8.2',
    'platformName' => 'iOS'
  }
end

def endpoint
  "http://localhost:4732/wd/hub"
end

http_client = ::Selenium::WebDriver::Remote::Http::Persistent.new
http_client.timeout = 200 # Browser launch can take a while   

begin
    driver = Selenium::WebDriver.for :remote, :url => endpoint, :desired_capabilities => caps, :http_client => http_client

    driver.navigate.to "http://www.google.com"
    driver.window_handles.each do |handle|
        STDERR.puts "Class of Window Handlers: #{handle.class}"
    end
ensure
   driver.quit
end 
```

**Comment by imurchie** [comment]
Logs are _always_ relevant. ;)
