### ISSUE TITLE
Very slow execution protractor tests on iOS Safari

### ISSUE THREAD

**Issue by LionasELV** [appium/appium#6397]
Hello All,

My protractor tests work very well in Chrome browser on mobile devices.
But these tests work very slow on iOS emulators, tests executed at 10 and more time slowly, I don't talk about addition problems related with launch protractor tests on iOS.

Please, can anybody get me responce about speed of execution tests on iOS.

Maby all have the such problems with speed on iOS?

If not, then can you describe step-by-step instruction regarding speed up of execution protractor tests on iOS.

I launch my tests on the following test environment:

```
Mac OS - Yosemite 10.10.5;
xCode - 6.4;
Appium - 1.5.0.
```

**Comment by jlipps** [comment]
This would be a better forum question. If you think there's an issue in the latest version of Appium, please send in your Appium logs with timestamps enabled!
