### ISSUE TITLE
Cannot install appium 1.5.1 via npm

### ISSUE THREAD

**Issue by sehandane** [appium/appium#6398]
## The problem

I am using Appium 1.4.16 and I wanna upgrade to 1.5.1 to work on iOS 9.3. I have tried to uninstall/overwrite but it still in 1.4.16.

## Environment

OS: MAC OS 10.11.4
Xcode: 7.3
Node.js version v5.10.1
Current Appium: 1.4.16

## Install Log

make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/appium/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:utf-8-validate@1.1.0 utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.1.0 Exit status 1
/usr/local/lib
└── appium@1.4.16

**Comment by celestinecypoon** [comment]
I had a similar problem as well, but I also manually deleted the files from my computer and then reinstalled. That seemed to have done the trick.

**Comment by sehandane** [comment]
@celestinecypoon I tried to remove all file/folder which are related to Appium but no use...
