### ISSUE TITLE
Fail to install iOS app on real device after switching to appium-ios-driver@1.11.2

### ISSUE THREAD

**Issue by wojciwojci** [appium/appium#6399]
## The problem

I am not able to install iOS app on real device after switching to appium-ios-driver@1.11.2. The problem did not occur in appium-ios-driver@1.9.0 (this version had this problem https://github.com/appium/appium/issues/6367 ).
## Environment
- Appium version (or git revision) that exhibits the issue:  1.5.1
- Last Appium version that did not exhibit the issue (if applicable) 1.5.0
- Desktop OS/version used to run Appium:OS X El Capitan 10.11.4
- node version v0.12.7
- Mobile platform iphone 8.4
- Real device 
## Details

Different exceptions are thrown in appium server log if app is already installed on phone (log2.log) and if app is to be installed by the test (log1.log).

Problem did not exist in appium-ios-driver@1.9.0.
## Link to Appium logs

[link](https://gist.github.com/wojciwojci/6002d0deb052b9f319e7cf6db56a0b77)

**Comment by SrinivasanTarget** [comment]
Are you able to remove the app manually from the device using ideviceinstaller - ideviceinstaller -u 561319f0269cf4d0e52a25af8deef3f7faa45295 -U com.seamless.SEQR ?

**Comment by wojciwojci** [comment]
Yes, I can remove app using this command. I used to remove app like this after switching to Appium 1.5.0. 
Currently the biggest problem in installing app on the device before tests.
If I install the app before the test by "ideviceinstaller - ideviceinstaller -i /path/to/app" and start appium server without "--full-reset" flag then test continues without exceptions. However such workaround is not easy to automate in my set up.

**Comment by SrinivasanTarget** [comment]
@imurchie Can you please look into this.

**Comment by mikejackowski** [comment]
There's one more thing to add - the app can't be installed when it is remote (via http) but it works if the app is local. It used to work via http in older appium versions.
