### ISSUE TITLE
clear adb logs from device using appium

### ISSUE THREAD

**Issue by sivakreddyc** [appium/appium#6403]
Hi 

I want to clear the device logs using appium

from command line we can clear adb logs from device using adb logcat -c but this is not possible when appium is running. So is there any way to clear adb logs from device using the appium

**Comment by imurchie** [comment]
No, there is no way to do this at the present time.

**Comment by brtu** [comment]
have you tried:

`List<LogEntry> logEntries = driver.manage().logs().get("logcat").getAll();`

Each time you call that command, I've found it will clear the log entries that you receive.... I am not sure whether it clears the logcat logs from the device.  But I think this may serve your purpose.

**Comment by sivakreddyc** [comment]
List<LogEntry> logEntries = driver.manage().logs().get("logcat").getAll();

This is not working

**Comment by imurchie** [comment]
What does "This is not working" mean?

**Comment by sivakreddyc** [comment]
List logEntries = driver.manage().logs().get("logcat").getAll(); using this command it's clearing the logs

**Comment by imurchie** [comment]
Ok. What is the problem, then?

**Comment by sivakreddyc** [comment]
sorry please check the above comment . i updated it.

**Comment by imurchie** [comment]
You mean _actually_ clearing the logs. @brtu's suggestion is not enough.

My original answer stands. This is not a feature that Appium currently supports. I've added it to our bucket of enhancement requests.

**Comment by sivakreddyc** [comment]
Ok. also we have one more problem in our automation - That is switching between webview and native view for multiple times. 

Also can you provide more enhancements which adb provides

**Comment by imurchie** [comment]
You'll have to be more specific. I don't know what you are talking about.

**Comment by alewang** [comment]
Cool, glad to see 'adb logcat -c' is on the feature list. Will there be a way to control whether Appium clears logcat or keep its current behavior? Maybe a desired capability to determine when the logcat buffers are cleared would be neat. 😛

**Comment by JoseCanavire** [comment]
I have some trouble clearing the logcat log programmatically somehow like this.
```java 
Process process = Runtime.getRuntime().exec(String.format("adb -s %s logcat -c", deviceId);
```
it does not work always as planned, sometimes it takes too long and you can't be sure the log is empty or not. Did someone got a better result?

**Comment by monsam** [comment]
is there any update on this? "clear adb logs from device using appium"

**Comment by bennid** [comment]
I'm running my emulators and phones in a selenium grid, and are therefore always running, so this is now very much needed... is there any progress on this front?  Even if it's "clear at connection time".  Thanks!

**Comment by imurchie** [comment]
There is now a capability, `clearDeviceLogsOnStart`, which when set to `true` will clear the adb logcat logs at the beginning of the session.

**Comment by ExcessWarriors** [comment]
@imurchie : clearDeviceLogsOnStart capability is not working and it is not clearing the device log.

**Comment by kashyapDaibala** [comment]
@imurchie : Same "clearDeviceLogsOnStart" not clearing any device logs. i'm checking for IOS device

**Comment by chenlujjj** [comment]
@imurchie  Which appium version supports the  `clearDeviceLogsOnStart` capability ? I didn't find it in the documentation: http://appium.io/docs/en/writing-running-appium/caps/index.html
