### ISSUE TITLE
How to force language in Desired Capabilities - Appium - Java 

### ISSUE THREAD

**Issue by kimoan** [appium/appium#6405]
## The problem

Does anybody know how i can made my App to run in specific language e.g. : English, German,,,,via 
a line of code in Desired Capabilities.
I know in appium Gui you can set the flag to force it, that app run in a specific language, but i have some test that i want to be run in different language ...see part of my code : 
	
## Environment

* Appium version 1.4.13(Draco)

## Details

// Config and Setup a AppiumDriverInstance
	public AppiumDriver<MobileElement> driver;
	public WebDriverWait wait;

	@BeforeClass
	public void setUp() throws Exception {
		// set up appium for ios instance
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 5s");
		capabilities.setCapability(MobileCapabilityType.APP, "/Users/Shared/my/ Test1.app");
		// capabilities.setCapability(cap, "Mac");
		driver = new IOSDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
		wait = new WebDriverWait(driver, 30);
	}

**Comment by imurchie** [comment]
Please ask such queries in the Appium Discuss board.

The short answer: there is a `language` capability (https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md)
