### ISSUE TITLE
Appium-doctor on Windows

### ISSUE THREAD

**Issue by imurchie** [appium/appium#6408]
## The problem

We have received a report that `appium-doctor` does not install correctly for Windows users.

    Also while looking at the documentation you might want to include that Window
    users need to have a path variable setup for appium-doctor pointing to the directory 
    of appium-doctor.cmd. I had an issue trying to run the appium-doctor command 
    until I added a variable which directly points to the directory location of this command 
    file. I would also update the documentation for the above problem as I don't see it in 
    the documentation very clearly.

While documenting this would be useful, it would be better to figure out how to get it to automatically be runnable when a user has run `npm install -g appium-doctor`.

**Comment by SrinivasanTarget** [comment]
Fixed in https://github.com/appium/appium/commit/6eb48cf2e3c4dd59697cbe3a9ed2119b3423d878

**Comment by SrinivasanTarget** [comment]
@triager please close
