### ISSUE TITLE
Issue on "Setting command timeout to the default of 60 secs" 

### ISSUE THREAD

**Issue by Tanmoyray** [appium/appium#6409]
## The problem

I am not able to run app through appium due to "Didn't get a new command in 60 secs, shutting down"

How to fix it?
## Details

During run through appium, appium could not install app within my emulator, then i externaly install app through cmd.

app is running . home page open.

during input within home page , I have received  error like this...

Device launched! Ready for commands

> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId null
> info: [debug] Didn't get a new command in 60 secs, shutting down...
> info: [debug] Trying to stop appium but there's no session, doing nothing
> info: [debug] We shut down because no new commands came in
## Environment
- Appium version (or git revision) that exhibits the issue:1.4.16.1
- Desktop OS/version used to run Appium: Window 7
- Mobile platform/version under test: android 1.5.1
- Real device or emulator/simulator: Simulator
## Link to Appium logs

> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --app C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk --full-reset --platform-name Android --platform-version 22 --automation-name Appium --device-name "New_Device_API_22" --log-no-color
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"app":"C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk","address":"127.0.0.1","fullReset":true,"logNoColors":true,"deviceName":"New_Device_API_22","platformName":"Android","platformVersion":"22","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"deviceName":"New_Device_API_22","app":"C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk","platformName":"Android"}}
> info: Client User-Agent string: undefined
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from desired caps: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk
> info: [debug] Creating new appium session 9dccd348-686f-4870-8a8d-df486f4bd130
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_73
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe
> info: [debug] Parsing package and activity from app manifest
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\tray\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe
> info: [debug] Extracting package and launch activity from manifest.
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe dump badging C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk
> info: [debug] badging package: com.knwedu.comschoolapp
> info: [debug] badging act: com.knwedu.ourschool.SplashActivity
> info: [debug] Parsed package and activity are: com.knwedu.comschoolapp/com.knwedu.ourschool.SplashActivity
> info: [debug] Using fast reset? false
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device emulator-5554
> info: [debug] Setting device id to emulator-5554
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 wait-for-device
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: Device API level is: 22
> info: [debug] Extracting strings for language: default
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk" "C:\Users\tray\AppData\Local\Temp\com.knwedu.comschoolapp" en
> info: [debug] No strings.xml for language 'en', getting default strings.xml
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk" "C:\Users\tray\AppData\Local\Temp\com.knwedu.comschoolapp"
> info: [debug] Reading strings from converted strings.json
> info: [debug] Setting language to default
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 push "C:\Users\tray\AppData\Local\Temp\com.knwedu.comschoolapp\strings.json" /data/local/tmp
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\tray\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe
> info: [debug] Retrieving process from manifest.
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe dump xmltree C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk AndroidManifest.xml
> info: [debug] Set app process to: com.knwedu.comschoolapp
> info: [debug] Uninstalling com.knwedu.comschoolapp
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "am force-stop com.knwedu.comschoolapp"
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 uninstall com.knwedu.comschoolapp
> info: [debug] App was uninstalled
> info: [debug] Checking app cert for C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk.
> info: [debug] executing cmd: java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar" C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\tray\AppData\Local\Android\sdk\build-tools\23.0.1\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\build-tools\23.0.1\zipalign.exe -f 4 C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk C:\Users\tray\AppData\Local\Temp\116315-6104-1j81nt4\appium.tmp
> info: [debug] MD5 for app is 6ea2fb5f8b957d951e91462f51cca7c9
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ls /data/local/tmp/6ea2fb5f8b957d951e91462f51cca7c9.apk"
> info: [debug] Getting install status for com.knwedu.comschoolapp
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "pm list packages -3 com.knwedu.comschoolapp"
> info: [debug] App is not installed
> info: Installing App
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "mkdir -p /data/local/tmp/"
> info: [debug] Removing any old apks
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ls /data/local/tmp/*.apk"
> info: [debug] Found an apk we want to keep at /data/local/tmp/6ea2fb5f8b957d951e91462f51cca7c9.apk
> info: [debug] Couldn't find any apks to remove
> info: [debug] Uninstalling com.knwedu.comschoolapp
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "am force-stop com.knwedu.comschoolapp"
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 uninstall com.knwedu.comschoolapp
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "pm install -r /data/local/tmp/6ea2fb5f8b957d951e91462f51cca7c9.apk"
> info: <-- POST /wd/hub/session - - ms - - 
> undefined
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 push "C:\Program Files (x86)\Appium\node_modules\appium\build\android_bootstrap\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.knwedu.comschoolapp -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] json loading complete.
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] dataDir set to: /data
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data"}
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":false}
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.knwedu.comschoolapp/com.knwedu.ourschool.SplashActivity"
> info: [debug] Waiting for pkg "com.knwedu.comschoolapp" and activity "com.knwedu.ourschool.SplashActivity" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "dumpsys window windows"
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.release"
> info: [debug] Device is at release version 5.1
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId 9dccd348-686f-4870-8a8d-df486f4bd130
> info: [debug] Didn't get a new command in 60 secs, shutting down...
> info: Shutting down appium session
> info: [debug] Removing app from device
> info: [debug] Uninstalling com.knwedu.comschoolapp
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "am force-stop com.knwedu.comschoolapp"
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 uninstall com.knwedu.comschoolapp
> error:  Error: Command failed: C:\Windows\system32\cmd.exe /s /c "C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 uninstall com.knwedu.comschoolapp"
> 
> ```
> at ChildProcess.exithandler (child_process.js:751:12)
> at ChildProcess.emit (events.js:110:17)
> at maybeClose (child_process.js:1016:16)
> at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
> ```
> 
> warn:  Error: Command failed: C:\Windows\system32\cmd.exe /s /c "C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 uninstall com.knwedu.comschoolapp"
> 
> ```
> at ChildProcess.exithandler (child_process.js:751:12)
> at ChildProcess.emit (events.js:110:17)
> at maybeClose (child_process.js:1016:16)
> at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
> ```
> 
> info: [debug] Pressing the HOME button
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "input keyevent 3"
> info: --> POST /wd/hub/session {"desiredCapabilities":{"deviceName":"New_Device_API_22","app":"C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk","platformName":"Android"}}
> info: Client User-Agent string: undefined
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from desired caps: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk
> info: [debug] Creating new appium session 98e840b7-7f66-4ba4-ac0c-b1ada0f25af6
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_73
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe
> info: [debug] Parsing package and activity from app manifest
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\tray\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe
> info: [debug] Extracting package and launch activity from manifest.
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe dump badging C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk
> info: [debug] badging package: com.knwedu.comschoolapp
> info: [debug] badging act: com.knwedu.ourschool.SplashActivity
> info: [debug] Parsed package and activity are: com.knwedu.comschoolapp/com.knwedu.ourschool.SplashActivity
> info: [debug] Using fast reset? false
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device emulator-5554
> info: [debug] Setting device id to emulator-5554
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 wait-for-device
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: Device API level is: 22
> info: [debug] Extracting strings for language: default
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk" "C:\Users\tray\AppData\Local\Temp\com.knwedu.comschoolapp" en
> info: [debug] No strings.xml for language 'en', getting default strings.xml
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk" "C:\Users\tray\AppData\Local\Temp\com.knwedu.comschoolapp"
> info: [debug] Reading strings from converted strings.json
> info: [debug] Setting language to default
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 push "C:\Users\tray\AppData\Local\Temp\com.knwedu.comschoolapp\strings.json" /data/local/tmp
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\tray\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe
> info: [debug] Retrieving process from manifest.
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\build-tools\23.0.1\aapt.exe dump xmltree C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk AndroidManifest.xml
> info: [debug] Set app process to: com.knwedu.comschoolapp
> info: [debug] Uninstalling com.knwedu.comschoolapp
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "am force-stop com.knwedu.comschoolapp"
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 uninstall com.knwedu.comschoolapp
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 138.776
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] UiAutomator shut down normally
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] We shut down because no new commands came in
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] Checking app cert for C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk.
> info: [debug] executing cmd: java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar" C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\tray\AppData\Local\Android\sdk\build-tools\23.0.1\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\build-tools\23.0.1\zipalign.exe -f 4 C:\Users\tray\AppData\Local\Android\sdk\platform-tools\KNWEDU.apk C:\Users\tray\AppData\Local\Temp\116315-6104-vpo4oo\appium.tmp
> info: [debug] MD5 for app is 6ea2fb5f8b957d951e91462f51cca7c9
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ls /data/local/tmp/6ea2fb5f8b957d951e91462f51cca7c9.apk"
> info: [debug] Getting install status for com.knwedu.comschoolapp
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "pm list packages -3 com.knwedu.comschoolapp"
> info: [debug] App is not installed
> info: Installing App
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "mkdir -p /data/local/tmp/"
> info: [debug] Removing any old apks
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ls /data/local/tmp/*.apk"
> info: [debug] Found an apk we want to keep at /data/local/tmp/6ea2fb5f8b957d951e91462f51cca7c9.apk
> info: [debug] Couldn't find any apks to remove
> info: [debug] Uninstalling com.knwedu.comschoolapp
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "am force-stop com.knwedu.comschoolapp"
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 uninstall com.knwedu.comschoolapp
> info: [debug] App was not uninstalled, maybe it wasn't on device?
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "pm install -r /data/local/tmp/6ea2fb5f8b957d951e91462f51cca7c9.apk"
> info: <-- POST /wd/hub/session - - ms - - 
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 push "C:\Program Files (x86)\Appium\node_modules\appium\build\android_bootstrap\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.knwedu.comschoolapp -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] json loading complete.
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] dataDir set to: /data
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data"}
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":false}
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.knwedu.comschoolapp/com.knwedu.ourschool.SplashActivity"
> info: [debug] Waiting for pkg "com.knwedu.comschoolapp" and activity "com.knwedu.ourschool.SplashActivity" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "dumpsys window windows"
> info: [debug] executing cmd: C:\Users\tray\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.release"
> info: [debug] Device is at release version 5.1
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId null
> info: [debug] Didn't get a new command in 60 secs, shutting down...
> info: [debug] Trying to stop appium but there's no session, doing nothing
> info: [debug] We shut down because no new commands came in

**Comment by Tanmoyray** [comment]
Any guidance ??

**Comment by jlipps** [comment]
Your client script broke connection with the Appium server in the middle of requesting a new session, so the session timed out. That means it's a client-side issue of some kind.
