### ISSUE TITLE
Appium installation

### ISSUE THREAD

**Issue by c-hendo** [appium/appium#6410]
## The problem

Hi, when I run  
npm install -g appium
I receive:
114150 error code ELIFECYCLE
114151 error appium-selendroid-driver@1.3.1 install: node ./bin/install.js
114151 error Exit status 1

## Environment

node v5.8.0
npm v3.8.1

## Details

114140 silly install printInstalled
114141 warn optional Skipping failed optional dependency /appium/fsevents:
114142 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.11
114143 verbose stack Error: appium-selendroid-driver@1.3.1 install: node ./bin/install.js
114143 verbose stack Exit status 1
114143 verbose stack at EventEmitter. (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:239:16)
114143 verbose stack at emitTwo (events.js:100:13)
114143 verbose stack at EventEmitter.emit (events.js:185:7)
114143 verbose stack at ChildProcess. (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
114143 verbose stack at emitTwo (events.js:100:13)
114143 verbose stack at ChildProcess.emit (events.js:185:7)
114143 verbose stack at maybeClose (internal/child_process.js:850:16)
114143 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
114144 verbose pkgid appium-selendroid-driver@1.3.1
114145 verbose cwd D:\
114146 error Windows_NT 6.1.7601
114147 error argv "D:\dev\nodejs\node.exe" "C:\Users\user\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "appium"
114148 error node v5.8.0
114149 error npm v3.8.1
114150 error code ELIFECYCLE
114151 error appium-selendroid-driver@1.3.1 install: node ./bin/install.js
114151 error Exit status 1
114152 error Failed at the appium-selendroid-driver@1.3.1 install script 'node ./bin/install.js'.
114152 error Make sure you have the latest version of node.js and npm installed.
114152 error If you do, this is most likely a problem with the appium-selendroid-driver package,
114152 error not with npm itself.
114152 error Tell the author that this fails on your system:
114152 error node ./bin/install.js
114152 error You can get information on how to open an issue for this project with:
114152 error npm bugs appium-selendroid-driver
114152 error Or if that isn't available, you can get their info via:
114152 error npm owner ls appium-selendroid-driver
114152 error There is likely additional logging output above.
114153 verbose exit [ 1, true ]

**Comment by kasirga32** [comment]
Looks like a path problem. Can you provide npm version and what terminal you are using?

**Comment by c-hendo** [comment]
npm v3.8.1
windows 7

**Comment by SrinivasanTarget** [comment]
@c-hendo Have you tried again?Any luck?

**Comment by SrinivasanTarget** [comment]
@c-hendo Please raise this with more recent logs incase if you hit the same in latest version of appium and after path is configured properly.Closing this for now.

**Comment by SrinivasanTarget** [comment]
@triager please close
