### ISSUE TITLE
Finding element with XPath on iOS bypasses implicit wait timeout

### ISSUE THREAD

**Issue by agauthiez** [appium/appium#6411]
## The problem

I set the the implicit wait timeout to 5 seconds but when I wanted to locate an element (i.e. with `POST /wd/hub/session/<session_id>/element`)
using XPath strategy on an iOS application, it failed on the first try, ignoring the 5s timeout.

## Environment

* Appium version (or git revision) that exhibits the issue: **1.5.1**
* Last Appium version that did not exhibit the issue (if applicable): **working on 1.4.13**
* Desktop OS/version used to run Appium: **OSX 10.10.5**
* Node.js version (unless using Appium.app|exe): **5.7.1**
* Mobile platform/version under test: **iPhone6 / iOS 8.4**
* Real device or emulator/simulator: **Simulator**
* Appium CLI or Appium.app|exe: **Appium CLI**

## Details

Appium "implicitly waits" successfully with other strategies on iOS. Moreover this issue report does not apply to `POST /wd/hub/session/<session_id>/elements` command and when using the Android driver.

## Link to Appium logs

[See here](https://gist.github.com/agauthiez/ef8d02322cfd4758fdfd0fdfb24bd806).

**Comment by imurchie** [comment]
This looks like there is an error getting the XML in order to do the XPath search, not that it is not using the implicit wait.

I'll look into this.

**Comment by imurchie** [comment]
Are you able to get the source for the page right before you try the Xpath search?

**Comment by agauthiez** [comment]
Thanks for the answers. Yes, I get the source successfully. As I mentioned `/elements` behaves correctly, but `/element` does not. I guess it can help you.

**Comment by imurchie** [comment]
Can you post the entire logs? I'm not sure of the problem, so the more information the better.

**Comment by agauthiez** [comment]
I just updated [my Gist](https://gist.github.com/agauthiez/ef8d02322cfd4758fdfd0fdfb24bd806):
- [set the implicit wait timeout](https://gist.github.com/agauthiez/ef8d02322cfd4758fdfd0fdfb24bd806#file-appium-logs-L2)
- [looked for a non exiting element](https://gist.github.com/agauthiez/ef8d02322cfd4758fdfd0fdfb24bd806#file-appium-logs-L49)
- [looked for an existing one](https://gist.github.com/agauthiez/ef8d02322cfd4758fdfd0fdfb24bd806#file-appium-logs-L64)

**Comment by imurchie** [comment]
Figured it out. Thanks for the patience, and the detailed report!
