### ISSUE TITLE
1.5.3 - iOS - Switching to WebView context takes way too long (10+ seconds)

### ISSUE THREAD

**Issue by brtu** [appium/appium#6414]
## The problem

I think this is a new issue that popped up in 1.5.1.  I don't think it happened in 1.4.16.

I have a WebView that opens up when I hit a button, and when I switch to the WebView context in iOS, it takes around 10 seconds.  This is way too long for my test, and the events that I'm searching for already happen before the context gets done switching from native to webview.  Any insight on how to fix it?

Thanks!
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.1
- Last Appium version that did not exhibit the issue (if applicable): 1.4.16
- Desktop OS/version used to run Appium: Mac 10.11.4
- Node.js version (unless using Appium.app|exe):  5.9.0
- Mobile platform/version under test: iOS 9.3 (happens for 9.2 also)
- Real device or emulator/simulator: simulator
- Appium CLI or Appium.app|exe: CLI
## Details

The context switching works fine in Android and happens very fast.  Just takes a very long time in iOS.
## Link to Appium logs

https://gist.github.com/brtu/bcd85f559a07604bf1c21065497fcb7b
## Code To Reproduce Issue [ Good To Have ]

Java client 3.4.1:

```
    Set<String> contextNames = driver.getContextHandles();
    driver.context((String) contextNames.toArray()[1]);
```

**Comment by mahmoud-cliqz** [comment]
I have the same problem it takes too long time, even with 10 seconds some times it works and some times it does not work

**Comment by IvanStawski** [comment]
same to me

**Comment by brtu** [comment]
Just tested this on 1.5.3, still takes 15 seconds to switch from native to webview context.

**Comment by jlipps** [comment]
@brtu I don't have a good answer as to why it would take so long to find the list of webviews. Does this repro in the new xcuitest-based driver? For example Appium 1.6.4 with iOS 10+

**Comment by brtu** [comment]
@jlipps i don't believe this is a problem anymore in 1.6+.  Closing this ticket
