### ISSUE TITLE
Cannot switch to Webview in Facebook application

### ISSUE THREAD

**Issue by alexr1978** [appium/appium#6415]
## The problem

Hi,
I'm using Appium to check web articles that are shared in Facebook.my step are:
1. open Facebook application in real device (Android) 
2. find the article that I need and click to enter it. 
3. try to switch to Webview to check some elements inside the article,

But when I debug I see only NATIVE APP context.

However , When I check this page using UI Automator Viewer, I see the article appears in the class "android.webkit.WebView".

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android (5.0, 6.0)
* Real device or emulator/simulator: Nexus 5, HUAWEI GRA-L09

**Comment by amedvedjev** [comment]
a you Facebook app developer? NOT = forget about switching with NOT debug app to webview

**Comment by imurchie** [comment]
That is correct. If the webview is not in debug mode it cannot be automated, unfortunately. See https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/hybrid.md#automating-hybrid-android-apps

**Comment by Tanmoyray** [comment]
Use : driver.context("NATIVE_APP") 
or 
You can use CromeDriver for inspect web elements .

**Comment by SrinivasanTarget** [comment]
@triager please close
