### ISSUE TITLE
Error on android swipe without 'wait' before 'move': "Cannot read property 'element' of undefined"

### ISSUE THREAD

**Issue by norekinc** [appium/appium#6416]
## The problem

Using ruby client (appium_lib v.8.0.2) I've encountered an issue with `swipe` on Android device. Its `TouchAction::swipe` does not require `duration` param, therefore with Appium server v1.5.1 it throws an error on server side, when duration is not provided.

## Environment

* Appium version (or git revision) that exhibits the issue: master, rev d4c7e55
* Last Appium version that did not exhibit the issue (if applicable): unknown
* Desktop OS/version used to run Appium: OSX 10.11.4
* Node.js version (unless using Appium.app|exe): 5.5.0
* Mobile platform/version under test: Motorola Moto G 3, android 5.1.1; Nexus 7, android 5.1.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

Issue does not apply to iOS - tested on real device.

## Link to Appium logs

gist includes android swipe with wait, without wait and ios swipe without wait:
https://gist.github.com/norekinc/18311ebb0959d0c9048398a2fc6dce6c

## Code To Reproduce Issue [ Good To Have ]

With ruby's arc:
`swipe start_x: 10, end_x: 10, start_y: 20, end_y: 20`

Unable to reproduce with java client, as that one requires duration parameter, so it's impossible to do swipe without `wait`:
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/TouchShortcuts.java#L77

While ruby client has `duration` optional:
https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/device/touch_actions.rb#L103

**Comment by imurchie** [comment]
Thanks for the detailed report! I will look into this.

**Comment by imurchie** [comment]
First thing: if you do a swipe without a wait it will _not_ be translated into an actual swipe on the device. It will simulate a swipe, but it may not function the same. The Android automation library has a method for swiping that we map to press-wait-moveTo-release. The Ruby client ought to put in a wait for 0 if it wants to indicate a swipe.

Making an issue on the ruby client would be good to get that fixed there.

**Comment by imurchie** [comment]
I've fixed the underlying bug in the android driver. The issue still stands as described above.

**Comment by norekinc** [comment]
@imurchie Actually I was about to create a PR in ruby client to set default duration. Then I decided to create this issue as the bug lies on server side, not client

Yeh, I know it is rather a simulating swipe - as server logs show us the sequence that has been built

**Comment by imurchie** [comment]
A PR to the ruby client would be awesome!

**Comment by norekinc** [comment]
Here it go https://github.com/appium/ruby_lib/pull/368
