### ISSUE TITLE
Clicking on inspector, Appium crashes

### ISSUE THREAD

**Issue by Prateek032** [appium/appium#6418]
Steps to replicate:
1. Launch the appium server and Run it
2. Run the java code (code which is written to test the app) on phone 
3. Now when the app opens on device, click on **Inspector**  icon
Bingo.. ! appium crashes
## Environment

* Appium version: 1.4.13.dmg
* Desktop OS/version used to run Appium: OSX EI Capitan version 10.11.4
* Mobile platform/version under test: SAMSUNG GALAXY GRAND (jelly beans)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: 1.5.1

**Comment by Prateek032** [comment]
Here you can see the [logs](https://gist.github.com/Prateek032/b63c524c86cd5d70cfc60feb13cb6032)

**Comment by imurchie** [comment]
Can you open this issue on the app? https://github.com/appium/appium-dot-app/issues
