### ISSUE TITLE
Unable to identify issue... Plz see log 

### ISSUE THREAD

**Issue by Tanmoyray** [appium/appium#6419]
Application has open through real device and then closed , i think it crashed  ...
I am not identify the issue..
Plc help.

## Code To Reproduce Issue [ Good To Have ]

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --command-timeout "7200" --debug-log-spacing --platform-version "9.3" --platform-name "iOS" --app "/Users/user/Documents/MyApp/KNWAllCollegeApp.ipa" --udid "6c19722f4be4855b359288fe037c7a7a958d92a7" --show-ios-log --device-name "iPad 2"

info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)

info: Appium REST http interface listener started on 0.0.0.0:4723

info: [debug] Non-default server args: {"app":"/Users/user/Documents/MyApp/KNWAllCollegeApp.ipa","udid":"6c19722f4be4855b359288fe037c7a7a958d92a7","deviceName":"iPad 2","platformName":"iOS","platformVersion":"9.3","showIOSLog":true,"defaultCommandTimeout":7200,"debugLogSpacing":true}

info: Console LogLevel: debug

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: <-- GET /wd/hub/status 200 16.524 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: <-- GET /wd/hub/status 200 9.723 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/sessions {}
info: [debug] Responding to client with success: {"status":0,"value":[]}

info: <-- GET /wd/hub/sessions 200 1.897 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"9.3","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPad 2"}}
info: Client User-Agent string: Appium (unknown version) CFNetwork/760.4.2 Darwin/15.4.0 (x86_64)
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************

info: [debug] Using local .ipa from command line: /Users/user/Documents/MyApp/KNWAllCollegeApp.ipa
info: [debug] Copying local zip to tmp dir

info: [debug] /Users/user/Documents/MyApp/KNWAllCollegeApp.ipa copied to /var/folders/k5/4vvbrjq52b3dkncqtz6vn_gw0000gn/T/116319-1010-18tsvm7/appium-app.zip

info: [debug] Unzipping /var/folders/k5/4vvbrjq52b3dkncqtz6vn_gw0000gn/T/116319-1010-18tsvm7/appium-app.zip

info: [debug] Testing zip archive: /var/folders/k5/4vvbrjq52b3dkncqtz6vn_gw0000gn/T/116319-1010-18tsvm7/appium-app.zip

info: [debug] Zip archive tested clean

info: [debug] Unzip successful

info: [debug] Using locally extracted app: /var/folders/k5/4vvbrjq52b3dkncqtz6vn_gw0000gn/T/116319-1010-18tsvm7/Payload/KNWAllCollegeApp.app
info: [debug] Creating new appium session 15cc4d0e-0358-4b26-a329-503c60755f0d
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /var/folders/k5/4vvbrjq52b3dkncqtz6vn_gw0000gn/T/116319-1010-18tsvm7/Payload/KNWAllCollegeApp.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /var/folders/k5/4vvbrjq52b3dkncqtz6vn_gw0000gn/T/116319-1010-18tsvm7/Payload/KNWAllCollegeApp.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Getting bundle ID from app

info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/user/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
info: [debug] Dynamic bootstrap path: /Users/user/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js
info: [debug] Reusing dynamic bootstrap: /Users/user/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js

info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog

info: [debug] Creating iDevice object with udid 6c19722f4be4855b359288fe037c7a7a958d92a7

info: [debug] App is installed.

info: [debug] fullReset not requested. No need to install.
info: [debug] Starting command proxy.

info: [debug] Instruments socket server started at /tmp/instruments_sock
info: [debug] Starting instruments

info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 6c19722f4be4855b359288fe037c7a7a958d92a7
info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 6c19722f4be4855b359288fe037c7a7a958d92a7 com.knwedu.knwedu -e UIASCRIPT "/Users/user/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:02 Tanmoy-Ray syslog_relay[3043] <Notice>: syslog_relay read 51 total bytes:
info: [IOS_SYSLOG_ROW ] ========================
info: [IOS_SYSLOG_ROW ] ASL is here to serve you

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:02 Tanmoy-Ray syslog_relay[3043] <Notice>: syslog_relay found the ASL prompt. Starting...

info: [debug] [INST STDERR] 2016-04-19 17:11:04.447 instruments[1021:48550] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray SpringBoard[54] <Warning>: BSXPCMessage received error for message: Connection interrupted
info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray SpringBoard[54] <Warning>: HW kbd: Failed to set (null) as keyboard focus

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray SpringBoard[54] <Warning>: UNNotificationRegistrarConnectionListener connection invalidated
info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray SpringBoard[54] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray SpringBoard[54] <Warning>: Unable to get short BSD proc info for 3280: No such process
info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray SpringBoard[54] <Warning>: Unable to get short BSD proc info for 3280: No such process

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray com.apple.xpc.launchd[1] (UIKitApplication:com.knwedu.knwedu[0x904a][3280]) <Notice>: Service exited due to signal: Killed: 9

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray SpringBoard[54] <Warning>: Application 'UIKitApplication:com.knwedu.knwedu[0x904a]' quit via signal.

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray kernel[0] <Notice>: xpcproxy[3288] Container: /private/var/mobile/Containers/Data/Application/8180DB58-EC9F-4536-9C5E-8FA6A1F981F0 (sandbox)

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray UserEventAgent[23] <Warning>: 2655426603906: id=com.knwedu.knwedu pid=3280, state=0

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray DTServiceHub[3174] <Warning>: Unable to acquire task port after launch of pid 3288 (com.knwedu.knwedu)
info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray com.apple.xpc.launchd[1] (UIKitApplication:com.knwedu.knwedu[0x1e30][3288]) <Notice>: Service exited due to signal: Killed: 9

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray SpringBoard[54] <Warning>: Application 'UIKitApplication:com.knwedu.knwedu[0x1e30]' exited abnormally via signal.

info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: Permission to debug com.knwedu.knwedu was denied. The app must be signed with a development identity (e.g. iOS Developer).

info: [debug] [INSTSERVER] Instruments exited with code 253
info: [debug] Killall instruments
info: [debug] Instruments crashed on startup
info: [debug] Attempting to retry launching instruments, this is retry #1
info: [debug] Killall iOS Simulator

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray searchd[2849] <Warning>: ====^^^^ DuetExpert missing data, count -> people:0 applicationDeepLinks:0 applications:8 requests:19 missingAllDataRequests:0
info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray DTServiceHub[3174] <Warning>: Could not create service named com.apple.instruments.server.services.processcontrol.posixspawn

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray gputoolsd[3287] <Notice>: schedule invalidation <DYTransport 0x12d608470, error: lost transport connection (31)>

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray gputoolsd[3287] <Notice>: terminating daemon 0x12d507460

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray notification_proxy[2987] <Error>: 0x16e1bb000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!
info: [IOS_SYSLOG_ROW ] Apr 19 17:11:05 Tanmoy-Ray notification_proxy[2987] <Error>: 0x16e1bb000 -[MNPLockdownConnection receiveMessage]: lockdown_receive_message error!

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"15cc4d0e-0358-4b26-a329-503c60755f0d"}

info: <-- GET /wd/hub/status 200 7.265 ms - 179 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"15cc4d0e-0358-4b26-a329-503c60755f0d"}

info: Launching instruments
info: [debug] Attempting to run app on real device with UDID 6c19722f4be4855b359288fe037c7a7a958d92a7

info: [debug] Spawning instruments with command: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /tmp/appium-instruments/instrumentscli0.trace -w 6c19722f4be4855b359288fe037c7a7a958d92a7 com.knwedu.knwedu -e UIASCRIPT "/Users/user/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js" -e UIARESULTSPATH /tmp/appium-instruments
info: [debug] And extra without-delay env: {}
info: [debug] And launch timeouts (in ms): {"global":90000}

info: [debug] [INST STDERR] 2016-04-19 17:11:11.998 instruments[1027:48633] WebKit Threading Violation - initial use of WebKit from a secondary thread.

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:12 Tanmoy-Ray SpringBoard[54] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:12 Tanmoy-Ray SpringBoard[54] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:12 Tanmoy-Ray kernel[0] <Notice>: xpcproxy[3290] Container: /private/var/mobile/Containers/Data/Application/8180DB58-EC9F-4536-9C5E-8FA6A1F981F0 (sandbox)

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:12 Tanmoy-Ray DTServiceHub[3174] <Warning>: Unable to acquire task port after launch of pid 3290 (com.knwedu.knwedu)
info: [IOS_SYSLOG_ROW ] Apr 19 17:11:12 Tanmoy-Ray com.apple.xpc.launchd[1] (UIKitApplication:com.knwedu.knwedu[0x939b][3290]) <Notice>: Service exited due to signal: Killed: 9
info: [IOS_SYSLOG_ROW ] Apr 19 17:11:12 Tanmoy-Ray SpringBoard[54] <Warning>: [com.knwedu.knwedu (3290)] Kill failed. Error: No such process (3)

info: [IOS_SYSLOG_ROW ] Apr 19 17:11:13 Tanmoy-Ray SpringBoard[54] <Warning>: Application 'UIKitApplication:com.knwedu.knwedu[0x939b]' exited abnormally via signal.

info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: Permission to debug com.knwedu.knwedu was denied. The app must be signed with a development identity (e.g. iOS Developer).

**Comment by imurchie** [comment]
You don't have permission to automate the application.

```
info: [debug] [INST STDERR] Instruments Trace Error : Target failed to run: Permission to debug com.knwedu.knwedu was denied. The app must be signed with a development identity (e.g. iOS Developer).
```

See: https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices.md#appium-on-real-ios-devices

**Comment by Tanmoyray** [comment]
Thank you @imurchie , then i will try it through simulator, 
then it will be working ...
