### ISSUE TITLE
autoWebviewTimeout not working for Appium 1.5.1

### ISSUE THREAD

**Issue by dvotion** [appium/appium#6420]
I have a setup which runs Protractor tests on an Android device. The app starts with a Native view and then switches to a webview. When running Appium 1.4.16 everything goes fine and Appium uses the autoWebviewTimeout to wait for the webview to become available and then continues executing.

When using Appium 1.5.1 (with & without install shrinkwrap) it doesn't wait for the webview to become available and shuts down. It looks like it ignores the autoWebviewTimeout setting.

The specific part of the debug log where this is happening:

[AndroidDriver] Setting auto webview
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/denniswiemer/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","02157df223553638","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] Found webviews: []
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"]
[debug] [AndroidDriver] Shutting down Android driver

Hopefully somebody can help! Thank you!

**Comment by wswebcreation** [comment]
Do you see difference in the code of 1.4.16 and 1.5.1 regarding the autoWebviewTimeout?

**Comment by dvotion** [comment]
@wswebcreation When looking at the difference between the both I see the autoWebviewTimeout is implemented in 1.4.16 but didn't see it in the 1.5.1 appium-android-driver. But it is implemented and working in 1.5.1 selendroid driver.

**Comment by imurchie** [comment]
Yes, it does not seem to be implemented there. Looking into it.

**Comment by dvotion** [comment]
Thank you! Life saver :)

**Comment by imurchie** [comment]
Fixed. Getting through the build then I will publish so it will get into Appium 1.5.2.

**Comment by wswebcreation** [comment]
Tnx!!

**Comment by dvotion** [comment]
Wow, thanks!
When will 1.5.2 be released? Is it possible to already use the fix, in example: checkout 1.5.1 with --no-shrinkwrap?

**Comment by imurchie** [comment]
It should be possible. If you are running from source, just npm install again.

I am set to release 1.5.2 today.

**Comment by dvotion** [comment]
Cool!

**Comment by dvotion** [comment]
Super, just checked out the source and Android is running smooth. Thank you!
Do you know when 1.5.2 will be in NPM?

**Comment by imurchie** [comment]
Sorry, didn't happen yesterday because of issues in our build process. I'm hoping for this morning. :|
