### ISSUE TITLE
iOS Simulator bundle path map discrepancy

### ISSUE THREAD

**Issue by adjavaherian** [appium/appium#6422]
## The problem

Appears that when iOSSimulator is building bundle path map, there's a problem creating the path...

I think this is the correct path.  Notice the Containers/Containers difference in the description below.

/Users/4m1r/Library/Developer/CoreSimulator/Devices/87A53418-4DB5-43FF-8EF7-170CA6640AFB/data/**Containers**/Data/Application/

Not sure that this really causes any problems, it looks like a simulator clean / reset?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: OS X 10.11.4 (15E65)
* Node.js version (unless using Appium.app|exe): v4.2.4
* Mobile platform/version under test: NA
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: NA

## Details

See Above

## Link to Appium logs

[https://gist.github.com/adjavaherian/f0c2eb381416e3b5311c018d42c66c2e](https://gist.github.com/adjavaherian/f0c2eb381416e3b5311c018d42c66c2e)

## Code To Reproduce Issue [ Good To Have ]

No code, just build an app and run it with with the iso-simple.js example in the examples.

**Comment by imurchie** [comment]
https://github.com/appium/appium-ios-simulator/issues/54

**Comment by adjavaherian** [comment]
Nice.  Thanks!
