### ISSUE TITLE
ADB crashes appium.

### ISSUE THREAD

**Issue by adamf663** [appium/appium#6423]
I continue to be unable to use appium 1.5 on multiple phones.  Latest discovery is that *any* adb command will crash appium.  ALL I HAVE TO DO TO CRASH APPIUM IS RUN "watch adb devices" in another terminal window!!

In version 1.4, appium respected the bp parameter and each server had it's own adb instance.

In 1.5, the bp parameter is ignored and appium servers use a common adb.  
If the user's program also issues an adb command, appium crashes.

Time to abandon appium.  I need to get work done and appium has been unusable for too long.

**Comment by scottdixon** [comment]
Duplicate https://github.com/appium/appium/issues/6384
