### ISSUE TITLE
Cannot click the delete button after swiping to left in ios

### ISSUE THREAD

**Issue by dancyzheng** [appium/appium#6424]
## The problem

I want to delete contact by clicking on the delete button after swiping to left. The contacts are listed in a table as cells. 
The contact in every cell can be swiped to left and then a delete button appears. The delete button can be found by appium, but error occurs when trying to click on it. I'm sure the button is visible on the screen after swiping. I don't know why deleteBtnE.isDisplayed() is false even after waiting for some time. 
## Environment
- Appium 1.4.13
- Desktop OS/version used to run Appium: MacBook Pro (13-inch, Mid 2012)
- Node.js version (unless using Appium.app|exe): v4.4.2
- Mobile platform/version under test: ios 8.1
- Real device or emulator/simulator: iphone 6
## Details

Code
WebElement tableCellE = driver.findElements(By.className("UIATableCell")).get(5);
int y = tableCellE.getLocation().getY();
int width = driver.manage().window().getSize().width;
driver.swipe(width \* 3 / 4, y, width / 2, y, 1000);
try {
Thread.sleep(1000);
} catch (InterruptedException e) {
// TODO Auto-generated catch block
e.printStackTrace();
}
WebEelement deleteBtnE = driver.findElement(By.xpath(//UIAApplication[1]/UIAWindow[1]/UIATableView[1]/UIATableCell[6]/UIAButton[1]));
System.out.println("is displayed? " + deleteBtnE.isDisplayed() + ===X==="+deleteBtnE.getLocation().getX()+"===Y==="+deleteBtnE.getLocation().getY());
deleteBtnE.click()
## Link to Appium logs

https://gist.github.com/dancyzheng/c184072e3fa9abc541d03717bde331ff

**Comment by scottdixon** [comment]
@dancyzheng - does the issue persist in Appium 1.5.2?

**Comment by dancyzheng** [comment]
I installed latest appium 1.5.2. But cannot start the server server. Blocked here. https://discuss.appium.io/t/cannot-start-appium-server-and-launch-inspector-after-upgrading-to-1-5-2/10098/8
