### ISSUE TITLE
can't send arabic characters using scrollTo command

### ISSUE THREAD

**Issue by mostafaawd** [appium/appium#6430]
## The problem
I have a problem in sending Arabic characters to Appium server using scrollTo command like the below using the below code:

```
    String v= "القاهرة";
    String vs= new String(v.getBytes("UTF-8"));
    System.out.println(vs);
     
    driver.scrollTo(vs).click();
```

Appium server dose not recognise this code and logging the below 
info: [debug] [BOOTSTRAP] [debug] Invoke complete.
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CONTAINS_DESCRIPTION=Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CONTAINS_TEXT=Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":7,"value":"No element found"}

## Environment

* Appium version (1.4.16.1) that exhibits the issue:1.4.16.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: tablet S II, Android 5.0.2
* Real device or emulator/simulator: Real device and emulator
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Can you provide the _entire_ Appium server log? At the very least, the full command (from the `HTTP` command for the `scrollTo`, to the return from the `HTTP` command) is necessary to go on.

**Comment by mostafaawd** [comment]
sure the below is the full log starting from the step before the scrollTo:
======
name","selector":"android.widget.Spinner","context":"","multiple":true}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding android.widget.Spinner using CLASS_NAME with the contextId:  multiple: true
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CLASS=android.widget.Spinner]
> info: [debug] [BOOTSTRAP] [debug] getElements selector:UiSelector[CLASS=android.widget.Spinner]
> info: [debug] [BOOTSTRAP] [debug] Element[] is null: (0)
> info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[CLASS=android.widget.Spinner, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Element[] is null: (1)
> info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[CLASS=android.widget.Spinner, INSTANCE=1]
> info: [debug] [BOOTSTRAP] [debug] Element[] is null: (2)
> info: [debug] [BOOTSTRAP] [debug] getElements tmp selector:UiSelector[CLASS=android.widget.Spinner, INSTANCE=2]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":[{"ELEMENT":"23"},{"ELEMENT":"24"}]}
> info: [debug] Responding to client with success: {"status":0,"value":[{"ELEMENT":"23"},{"ELEMENT":"24"}],"sessionId":"f0bc0989-7362-4294-b2fc-08b9100266c6"}
> info: <-- POST /wd/hub/session/f0bc0989-7362-4294-b2fc-08b9100266c6/elements 200 130.570 ms - 107 {"status":0,"value":[{"ELEMENT":"23"},{"ELEMENT":"24"}],"sessionId":"f0bc0989-7362-4294-b2fc-08b9100266c6"}
> info: --> POST /wd/hub/session/f0bc0989-7362-4294-b2fc-08b9100266c6/element/1/value {"id":"1","value":["ef_admin"]}
> info: [debug] Pushing command to appium work queue: ["element:setText",{"elementId":"1","text":"ef_admin","replace":false,"unicodeKeyboard":true}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"1","text":"ef_admin","replace":false,"unicodeKeyboard":true}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: setText
> info: [debug] [BOOTSTRAP] [debug] Using element passed in.
> info: [debug] [BOOTSTRAP] [debug] Attempting to clear using UiObject.clearText().
> info: [debug] [BOOTSTRAP] [debug] Sending plain text to element: ef_admin
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"f0bc0989-7362-4294-b2fc-08b9100266c6"}
> info: <-- POST /wd/hub/session/f0bc0989-7362-4294-b2fc-08b9100266c6/element/1/value 200 4243.662 ms - 76 {"status":0,"value":true,"sessionId":"f0bc0989-7362-4294-b2fc-08b9100266c6"}
> info: --> POST /wd/hub/session/f0bc0989-7362-4294-b2fc-08b9100266c6/touch/perform {"actions":[{"action":"tap","options":{"element":"3"}}]}
> info: [debug] Pushing command to appium work queue: ["element:getLocation",{"elementId":"3"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"3"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getLocation
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"x":1120,"y":446}}
> info: [debug] Pushing command to appium work queue: ["element:getSize",{"elementId":"3"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getSize","params":{"elementId":"3"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getSize
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"width":112,"height":92}}
> info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"3","x":1176,"y":492}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"3","x":1176,"y":492}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: click
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"f0bc0989-7362-4294-b2fc-08b9100266c6"}
> info: <-- POST /wd/hub/session/f0bc0989-7362-4294-b2fc-08b9100266c6/touch/perform 200 305.852 ms - 76 {"status":0,"value":true,"sessionId":"f0bc0989-7362-4294-b2fc-08b9100266c6"}
> info: --> POST /wd/hub/session/f0bc0989-7362-4294-b2fc-08b9100266c6/element/23/click {"id":"23"}
> info: [debug] Pushing command to appium work queue: ["element:click",{"elementId":"23"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"elementId":"23"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: click
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] Responding to client with success: {"status":0,"value":true,"sessionId":"f0bc0989-7362-4294-b2fc-08b9100266c6"}
> info: <-- POST /wd/hub/session/f0bc0989-7362-4294-b2fc-08b9100266c6/element/23/click 200 196.213 ms - 76 {"status":0,"value":true,"sessionId":"f0bc0989-7362-4294-b2fc-08b9100266c6"}
> info: --> POST /wd/hub/session/f0bc0989-7362-4294-b2fc-08b9100266c6/element {"using":"-android uiautomator","value":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().descriptionContains(\"Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\"Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©\").instance(0));"}
> info: [debug] Waiting up to 0ms for condition
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().descriptionContains(\"Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\"Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©\").instance(0));","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().descriptionContains(\"Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©\").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\"Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©\").instance(0));","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().descriptionContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0)); using ANDROID_UIAUTOMATOR with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().descriptionContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0))
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().descriptionContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0), 
> info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().descriptionContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0)
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©"
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@11faaf58
> info: [debug] [BOOTSTRAP] [debug] Invoke complete.
> info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0))
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().textContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0), 
> info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().textContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0)
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©"
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@3f39a8b1
> info: [debug] [BOOTSTRAP] [debug] Invoke complete.
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CONTAINS_DESCRIPTION=Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CONTAINS_TEXT=Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
> info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().descriptionContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0));new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0)); using ANDROID_UIAUTOMATOR with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().descriptionContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0))
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().descriptionContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0), 
> info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().descriptionContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0)
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©"
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@26d8f196
> info: [debug] [BOOTSTRAP] [debug] Invoke complete.
> info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0))
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().textContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0), 
> info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().textContains("Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©").instance(0)
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©"
> info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
> info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
> info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@13fec117
> info: [debug] [BOOTSTRAP] [debug] Invoke complete.
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CONTAINS_DESCRIPTION=Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[CONTAINS_TEXT=Ø§Ù„Ù‚Ø§Ù‡Ø±Ø©, INSTANCE=0]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":7,"value":"No element found"}
> info: [debug] Condition unmet after 10384ms. Timing out.
> info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":"No element found"},"sessionId":"f0bc0989-7362-4294-b2fc-08b9100266c6"}
> info: <-- POST /wd/hub/session/f0bc0989-7362-4294-b2fc-08b9100266c6/element 500 10388.032 ms - 195

**Comment by imurchie** [comment]
This is an issue with your client not encoding the text correctly. Please open an issue with whatever client you are using.

Pertinent output from a run on Appium 1.4.16:

```
info: Welcome to Appium v1.4.16 (REV c4004afc396d4670cf43efe4674a43199ea6c755)
info: Appium REST http interface listener started on 0.0.0.0:4723

...

info: --> POST /wd/hub/session/7e36a8de-024a-4873-a651-4322557a5bcb/element {"using":"-android uiautomator","value":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"القاهرة\").instance(0));"}
info: [debug] Waiting up to 5000ms for condition
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"القاهرة\").instance(0));","context":"","multiple":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text(\"القاهرة\").instance(0));","context":"","multiple":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: find
info: [debug] [BOOTSTRAP] [debug] Finding new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text("القاهرة").instance(0)); using ANDROID_UIAUTOMATOR with the contextId:  multiple: false
info: [debug] [BOOTSTRAP] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().text("القاهرة").instance(0))
info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: boolean arg: true
info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
info: [debug] [BOOTSTRAP] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().text("القاهرة").instance(0),
info: [debug] [BOOTSTRAP] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().text("القاهرة").instance(0)
info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: class java.lang.String arg: "القاهرة"
info: [debug] [BOOTSTRAP] [debug] UiSelector coerce type: int arg: 0
info: [debug] [BOOTSTRAP] [debug] Method name: scrollIntoView
info: [debug] [BOOTSTRAP] [debug] Setting uiObject for scrollIntoView
info: [debug] [BOOTSTRAP] [debug] Invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException with: com.android.uiautomator.core.UiObject@11fcd4cd
info: [debug] [BOOTSTRAP] [debug] Invoke complete.
info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[TEXT=القاهرة, INSTANCE=0]
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":{"ELEMENT":"1"}}
info: [debug] Responding to client with success: {"status":0,"value":{"ELEMENT":"1"},"sessionId":"7e36a8de-024a-4873-a651-4322557a5bcb"}
info: <-- POST /wd/hub/session/7e36a8de-024a-4873-a651-4322557a5bcb/element 200 4578.166 ms - 87 {"status":0,"value":{"ELEMENT":"1"},"sessionId":"7e36a8de-024a-4873-a651-4322557a5bcb"}
info: --> GET /wd/hub/session/7e36a8de-024a-4873-a651-4322557a5bcb/element/1/text {}
info: [debug] Pushing command to appium work queue: ["element:getText",{"elementId":"1"}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getText","params":{"elementId":"1"}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getText
info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"القاهرة"}
info: [debug] Responding to client with success: {"status":0,"value":"القاهرة","sessionId":"7e36a8de-024a-4873-a651-4322557a5bcb"}
info: <-- GET /wd/hub/session/7e36a8de-024a-4873-a651-4322557a5bcb/element/1/text 200 227.365 ms - 88 {"status":0,"value":"القاهرة","sessionId":"7e36a8de-024a-4873-a651-4322557a5bcb"}
```
