### ISSUE TITLE
Inconsistent --help text & behavior wrt Device Name

### ISSUE THREAD

**Issue by midopa** [appium/appium#6431]
## The problem

Appium console help says `device-name` is deprecated. But if I launch an Android session without it in the desired capabilities it fails.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.2
* Last Appium version that did not exhibit the issue (if applicable): Unknown
* Desktop OS/version used to run Appium: Ubuntu 14.04
* Node.js version (unless using Appium.app|exe): 5.10.1
* Mobile platform/version under test: Android 5.1
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: CLI

## Details

Looks like it's because of this: https://github.com/appium/appium-base-driver/blob/master/lib/desired-caps.js#L17

## Link to Appium logs

Crash log: https://gist.github.com/midopa/89e925a290fa5e1378e8e61f4f4ff246
Appium --help text: https://gist.github.com/midopa/068c4c965f0facb7691930bb27b46e1b

## Code To Reproduce Issue [ Good To Have ]

```
DesiredCapabilities caps = new DesiredCapabilities();
caps.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, "com.android.browser");
caps.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, ".BrowserActivity");
AndroidDriver<MobileElement> driver = AndroidDriver(caps);
```

**Comment by imurchie** [comment]
The server flag `--device-name` _is_ deprecated. That said, the desired capability `deviceName` is still required.

The help text is for the server argument.
