### ISSUE TITLE
Was the clear issue resolved in Appium 

### ISSUE THREAD

**Issue by mostafaawd** [appium/appium#6433]
## The problem

during using the clear method  in the edit text it deletes only one character instead of  clearing all the text.
after reading about the issue I know that it is known issue, so if some one has a workaround can help us.
specially there is no text I can get it in order to go for FOR loop to clear the issue it seems it is a hidden one.   
## Environment
- Appium version (or git revision) that exhibits the issue:
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Windows10
- Node.js version (unless using Appium.app|exe): 1.4.16.1
- Mobile platform/version under test: 
- Real device or emulator/simulator:Real device
- Appium CLI or Appium.app|exe:
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by scottdixon** [comment]
No this hasn't been resolved yet.

**Comment by TFry** [comment]
This looks to still be an issue (in some regard) on 1.5.3 

I have tested on two different devices where the text will eventually get deleted entirely, but it does so one character at a time. 

Each character deletion is followed by a long delay.

Gist: [https://gist.github.com/TFry/01071924dfe1cc8e836098283156fc99](url)

Using Ruby doing a simple:
` @overlayNameBtn = TextField.new(':id => "com.company.android.GAAPP:id/editable_text_field"')

def self.EventName(name)
    @overlayNameBtn.send_keys(name)
  end`

**Comment by dpgraham** [comment]
Does this still happen for anyone? If it does, I'll re-open the ticket.
