### ISSUE TITLE
Android screenshot currently forces use of device diskspace

### ISSUE THREAD

**Issue by imurchie** [appium/appium#6436]
## The problem

It should be possible to specify the location of the screenshot vis-a-vis the device. This should not be the name of the file, but the directory into which we put the screenshot. So devices with no drive space can use an SD card or other storage. This should be behind an Android-only desired capability.

**Comment by dpgraham** [comment]
@imurchie Was this implemented on UIAutomator2?

**Comment by imurchie** [comment]
I have no idea.

**Comment by mykola-mokhnach** [comment]
For never (5.0+) we catch screenshots using `adb exec-out`, which does not create any temporary files and writes the data directly into memory buffer. We only fallback to the old screenshoting method if the new approach fails (which should never happen if adb is up to date and works properly). So, I assume the issue can be closed.
