### ISSUE TITLE
Does appium support any other browser apart from Chrome for Android and Safari for iOS?

### ISSUE THREAD

**Issue by anbog** [appium/appium#6438]
Does appium support any other browser apart from Chrome for Android and Safari for iOS? We are looking for firefox in iOS and Android or opera as well.

**Comment by anbog** [comment]
Does appium support any other browser apart from Chrome for Android and Safari for iOS? We are looking for firefox in iOS and Android or opera as well.

**Comment by imurchie** [comment]
It also supports the default browser (`browserName: Browser`) on Android.

We have no support for Firefox or Opera anywhere, though we would totally be into someone looking into how to automate them and get them into Appium!

**Comment by anbog** [comment]
Okay.. Thanks for response..

**Comment by vipin-kumar-tomar** [comment]
It's been 2 years so wondering if Appium added support for any other browser like chrome in iOS for mobile web.

**Comment by kbalakumar99** [comment]
Hi there, Any updates on this? Can we automate Chrome in ios?

**Comment by naelabdeljawad** [comment]
Hey,
Any updates regarding **firefox** ?

**Comment by imurchie** [comment]
Neither Chrome for iOS nor Firefox for any platform are supported.
