### ISSUE TITLE
Appium 1.5.2, iOS: Strings with embedded \n break sendKeys

### ISSUE THREAD

**Issue by amaharana** [appium/appium#6441]
## The problem

In earlier versions of Appium (I checked 1.4.10), if I called sendKeys with a string such as "mystring\n", Appium passed this string to instruments as-is. However, in Appium 1.5.2, \n causes the string to be split into two lines and causes Instruments to barf with `Unexpected EOF` as the first line's quote remains unclosed.

Appium 1.4.10 (works as expected):
```
info: [debug] [INST] 2016-04-27 20:51:46 +0000 Debug: Got new command 78 from instruments: au.sendKeysToActiveElement('mystring\n')
info: [debug] [INST] 2016-04-27 20:51:46 +0000 Debug: evaluating au.sendKeysToActiveElement('mystring\n')
info: [debug] [INST] 2016-04-27 20:51:46 +0000 Debug: target.frontMostApp().keyboard().typeString("mystring\n")
```

Appium 1.5.2:
```
[HTTP] --> POST /wd/hub/session/fd716bef-e63e-4285-81a6-175944f1ffac/keys {"value":["mystring\n"]}
[MJSONWP] Calling AppiumDriver.keys() with args: [["mystring\n"],"fd716bef-e63e-4285-81a6-175944f1ffac"]
[debug] [iOS] Executing iOS command 'keys'
[debug] [UIAuto] Sending command to instruments: au.sendKeysToActiveElement('mystring
')
[debug] [Instruments] [INST] 2016-04-27 20:18:45 +0000 Debug: Got new command 75 from instruments: au.sendKeysToActiveElement('mystring
       ')
[debug] [Instruments] [INST] 2016-04-27 20:18:45 +0000 Debug: evaluating au.sendKeysToActiveElement('mystring
       ')
[debug] [UIAuto] Socket data received (40 bytes)
[debug] [UIAuto] Got result from instruments: {"status":17,"value":"Unexpected EOF"}
[HTTP] <-- POST /wd/hub/session/fd716bef-e63e-4285-81a6-175944f1ffac/keys 500 443 ms - 101
[debug] [Instruments] [INST] 2016-04-27 20:18:45 +0000 Error: SyntaxError: Unexpected EOF
```

## Environment
* Appium version (or git revision) that exhibits the issue: 1.5.2
* Last Appium version that did not exhibit the issue (if applicable): 1.4.10
* Desktop OS/version used to run Appium: Mac OSX Yosemite 10.10.5
* Node.js version (unless using Appium.app|exe): 5.7.0
* Real device or emulator/simulator: iOS 9.2 simulator
* Appium CLI or Appium.app|exe: Appium 1.5.2 CLI built from source

**Comment by imurchie** [comment]
Thank you for the detailed report. I will look into this.

**Comment by amaharana** [comment]
Works fine with this. Thanks for the quick fix!
