### ISSUE TITLE
session-override stopped working for v1.5.0+

### ISSUE THREAD

**Issue by norekinc** [appium/appium#6442]
## The problem

On concurrent tests running on the same server with flag `--session-override`, latest running test session should override older tests session. Issue exists in v1.5.0, v1.5.1, master, though it was working on v1.4.6

## Environment

* Appium version (or git revision) that exhibits the issue:
 * v1.5.0 rev 93004e134878b75c03ff78a6b7041a1f846d0429
 * master, rev 216264ff169023d7517d7d1d48186dd971908730
* Last Appium version that did not exhibit the issue (if applicable):
 * 1.4.6
* Desktop OS/version used to run Appium: OSX 10.11.4
* Node.js version (unless using Appium.app|exe): v5.5.0
* Mobile platform/version under test: Android 5.1.1
* Real device or emulator/simulator: nexus 7
* Appium CLI or Appium.app|exe: CLI, ruby_lib

## Details

-

## Link to Appium logs

https://gist.github.com/norekinc/648d44a77390e051c327fd0da1818976#file-appium-server-part-log-on-2nd-android-session

Included full server log + part where second session enters

## Code To Reproduce Issue [ Good To Have ]

No code to be added, rather steps to reproduce:

**Given** run appium server with `--session-override` param, eg from the source: `node . --session-override --log-level debug`
**And** run client code/test that will start new session on the server
**And** run another test with caps pointing to the **same** `server_url`, **after** 1st session has been created
**When** second test requests sever for new session
**Then (expected)** server overrides session, second test continues running, first test fails
**Then (actual)** second test fails, showing error message:
`A new session could not be created. Details: Problem getting session data for driver type AndroidDriver; does it implement 'get driverData'? (Selenium::WebDriver::Error::SessionNotCreatedError)` (ruby client)

**Comment by SrinivasanTarget** [comment]
@triager please label: Bug

**Comment by imurchie** [comment]
This [was fixed](https://github.com/appium/appium/commit/406a06a7decccf04994568de1e86f8b338d0819d) and will be in 1.5.3.

**Comment by anand853** [comment]
still i see the issue with 1.6.4. 

logs:
/usr/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pycharm/_jb_pytest_runner.py" --path /Users/cigniti_apasunoori/Documents/iRobot/sourceCode/cloudCode/sitecorepy/appAutomation/TestStringMethods.py
Testing started at 10:38 PM ...
Launching py.test with arguments /Users/cigniti_apasunoori/Documents/iRobot/sourceCode/cloudCode/sitecorepy/appAutomation/TestStringMethods.py in /Users/cigniti_apasunoori/Documents/iRobot/sourceCode/cloudCode/sitecorepy/appAutomation
============================= test session starts ==============================
platform darwin -- Python 2.7.10, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /Users/cigniti_apasunoori/Documents/iRobot/sourceCode/cloudCode/sitecorepy/appAutomation, inifile:
collected 1 items
TestStringMethods.py F
TestStringMethods.py:23 (TestStringMethods.test_lauchApp)
self = <appAutomation.TestStringMethods.TestStringMethods testMethod=test_lauchApp>

    def test_lauchApp(self):
            # print iRobotCore.func_name ()
            desired_caps = {}
            desired_caps['platformName'] = 'Android'
            desired_caps['platformVersion'] = '6.0.1'
            desired_caps['deviceName'] = 'SAMSUNG-SM-G920V'
            # desired_caps['platformVersion'] = '5.1'
            # desired_caps['deviceName'] = 'XT1053'
            desired_caps['appPackage'] = 'com.irobot.home'
            desired_caps['appActivity'] = 'com.irobot.home.SplashActivity_'
            desired_caps['noReset'] = True
            desired_caps['newCommandTimeout'] = 3000
            desired_caps['session-override'] = True
    
>           driver = webdriver.Remote ( 'http://localhost:4723/wd/hub', desired_caps )

TestStringMethods.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Library/Python/2.7/site-packages/appium/webdriver/webdriver.py:36: in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py:92: in __init__
    self.start_session(desired_capabilities, browser_profile)
/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py:179: in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py:238: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x10889c810>
response = {'status': 500, 'value': '{"status":33,"value":{"message":"A new session could not be created. Details: Problem getting session data for driver type AndroidDriver; does it implement \'get driverData\'?"},"sessionId":null}'}

    def check_response(self, response):
        """
            Checks that a JSON response from the WebDriver does not have an error.
    
            :Args:
             - response - The JSON response from the WebDriver server as a dictionary
               object.
    
            :Raises: If the response contains an error message.
            """
        status = response.get('status', None)
        if status is None or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, basestring):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if status is None:
                        status = value["status"]
                        message = value["value"]
                        if not isinstance(message, basestring):
                            value = message
                            try:
                                message = message['message']
                            except TypeError:
                                message = None
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class = ErrorInResponseException
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = WebDriverException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = WebDriverException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        else:
            exception_class = WebDriverException
        if value == '' or value is None:
            value = response['value']
        if isinstance(value, basestring):
            if exception_class == ErrorInResponseException:
                raise exception_class(response, value)
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '<anonymous>')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = "    at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException and 'alert' in value:
            raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
>       raise exception_class(message, screen, stacktrace)
E       WebDriverException: Message: A new session could not be created. Details: Problem getting session data for driver type AndroidDriver; does it implement 'get driverData'?

/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py:193: WebDriverException


=================================== FAILURES ===================================
_______________________ TestStringMethods.test_lauchApp ________________________

self = <appAutomation.TestStringMethods.TestStringMethods testMethod=test_lauchApp>

    def test_lauchApp(self):
            # print iRobotCore.func_name ()
            desired_caps = {}
            desired_caps['platformName'] = 'Android'
            desired_caps['platformVersion'] = '6.0.1'
            desired_caps['deviceName'] = 'SAMSUNG-SM-G920V'
            # desired_caps['platformVersion'] = '5.1'
            # desired_caps['deviceName'] = 'XT1053'
            desired_caps['appPackage'] = 'com.irobot.home'
            desired_caps['appActivity'] = 'com.irobot.home.SplashActivity_'
            desired_caps['noReset'] = True
            desired_caps['newCommandTimeout'] = 3000
            desired_caps['session-override'] = True
    
>           driver = webdriver.Remote ( 'http://localhost:4723/wd/hub', desired_caps )

TestStringMethods.py:38: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Library/Python/2.7/site-packages/appium/webdriver/webdriver.py:36: in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py:92: in __init__
    self.start_session(desired_capabilities, browser_profile)
/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py:179: in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py:238: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x10889c810>
response = {'status': 500, 'value': '{"status":33,"value":{"message":"A new session could not be created. Details: Problem getting session data for driver type AndroidDriver; does it implement \'get driverData\'?"},"sessionId":null}'}

    def check_response(self, response):
        """
            Checks that a JSON response from the WebDriver does not have an error.
    
            :Args:
             - response - The JSON response from the WebDriver server as a dictionary
               object.
    
            :Raises: If the response contains an error message.
            """
        status = response.get('status', None)
        if status is None or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, basestring):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if status is None:
                        status = value["status"]
                        message = value["value"]
                        if not isinstance(message, basestring):
                            value = message
                            try:
                                message = message['message']
                            except TypeError:
                                message = None
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass
    
        exception_class = ErrorInResponseException
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = WebDriverException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = WebDriverException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        else:
            exception_class = WebDriverException
        if value == '' or value is None:
            value = response['value']
        if isinstance(value, basestring):
            if exception_class == ErrorInResponseException:
                raise exception_class(response, value)
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']
    
        screen = None
        if 'screen' in value:
            screen = value['screen']
    
        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '<anonymous>')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = "    at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException and 'alert' in value:
            raise exception_class(message, screen, stacktrace, value['alert'].get('text'))
>       raise exception_class(message, screen, stacktrace)
E       WebDriverException: Message: A new session could not be created. Details: Problem getting session data for driver type AndroidDriver; does it implement 'get driverData'?

/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py:193: WebDriverException
========================== 1 failed in 16.63 seconds ===========================
Process finished with exit code 0

**Comment by imurchie** [comment]
Session override is a server flag, not a desired capability, so `desired_caps['session-override'] = True` does nothing.

**Comment by anand853** [comment]
i do not see any server flags with 1.1. - beta 2 (mac version) pls let me know where to set it?
