### ISSUE TITLE
driver.Manage().Window.Size trying this appium for android giving unknown error: operation is unsupported on Android

### ISSUE THREAD

**Issue by naveenkumarks** [appium/appium#6444]
## The problem

We are using test script which runs on both IOS and android but when we are trying to get device screen size using driver.Manage().Window.Size in android giving operation is unsupported on Android.same working in appium ios.
## Environment
- Appium version (or git revision) that exhibits the issue:
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
I need the Appium server logs, to see what command is actually being sent. 

Also, what language are you writing in?

**Comment by naveenkumarks** [comment]
Hi
I am using C# client .

driver.Manage().Window.Size is working in native view.but when i am trying to get in webview context its failing below is the appium log.

appium server:1.4.16.1
Appium Dotnet Driver:1.4.1.1


appium log:

> info: <-- GET /wd/hub/session/a00d68f5-4936-4e41-a6da-6b49a8ef16a6/context 200 0.855 ms - 106 {"status":0,"value":"WEBVIEW_com.leicabiosystems.warg","sessionId":"a00d68f5-4936-4e41-a6da-6b49a8ef16a6"}
> info: --> GET /wd/hub/session/a00d68f5-4936-4e41-a6da-6b49a8ef16a6/window/current/size {}
> info: JSONWP Proxy: Proxying [GET /wd/hub/session/a00d68f5-4936-4e41-a6da-6b49a8ef16a6/window/current/size] to [GET http://127.0.0.1:9515/wd/hub/session/2ce18af1424fb58ddcd289acf24c7c4c/window/current/size] with body: {}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"2ce18af1424fb58ddcd289acf24c7c4c","status":13,"value":{"message":"unknown error: operation is unsupported on Android\n  (Session info: chrome=49.0.2623.105)\n  (Driver info: chromedri...
> info: JSONWP Proxy: Replacing sessionId 2ce18af1424fb58ddcd289acf24c7c4c with a00d68f5-4936-4e41-a6da-6b49a8ef16a6
> info: <-- GET /wd/hub/session/a00d68f5-4936-4e41-a6da-6b49a8ef16a6/window/current/size 200 4.326 ms - 298

**Comment by chethangowda** [comment]
Am also getting same error on webview.

Error log

org.openqa.selenium.WebDriverException: unknown error: operation is unsupported on Android
  (Session info: webview=33.0.0.0)
  (Driver info: chromedriver=2.21.371461 (633e689b520b25f3e264a2ede6b74ccc23cb636a),platform=Linux 3.13.0-85-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 20 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'SAMDK11050175', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-85-generic', java.version: '1.8.0_91'
Driver info: io.appium.java_client.android.AndroidDriver

**Comment by imurchie** [comment]
That command is not supported on Android webviews. You cannot do it.

**Comment by chethangowda** [comment]
Thanks...

How to acchive scroll down ro left in WEBVIEW(hybrid) application...

**Comment by abhagupta** [comment]
did anyone find a work around for this issue. I run the same tests for both Web and Android and it would be nice if I do not have to change the code explicitly for Android's browser.

**Comment by SrinivasanTarget** [comment]
ScrollDown should happen by default in webviews when we try finding the element. Feel free to raise a voice in our discuss forum.

**Comment by sumeetp4** [comment]
Scroll down is not happening by default in webviews when finding the element. Seems to work in iOS (Safari browser), but not in Chrome (Android)

**Comment by vcherakam** [comment]
@imurchie  Hi Could you please tell me the command which supported on Android webview.

Please help me on this.

**Comment by Infernion** [comment]
@imurchie @vcherakam have you figured out which command is supported on Android?

**Comment by sandhya448** [comment]
me too facing the same problem. have tried using window.size().. which gives me unsupported error..
tried using sequence of press, moveto,release..operations...which gives methods not yet been implemented
tried using swipe.. whioch is removed from the latest jar..
curently i am using 5.0.4 appium client.. please suggest any change in the jar version or pls provide a working way for android or ios
