### ISSUE TITLE
Even after setting pageLoadTimeout, webview request `title did not wait

### ISSUE THREAD

**Issue by truebit** [appium/appium#6447]
## The problem

Test in a hybrid iOS app on real device using Java. after setting pageLoadTimeout, webview request did not wait
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.2
- Last Appium version that did not exhibit the issue (if applicable): n/a
- Desktop OS/version used to run Appium: n/a
- Node.js version (unless using Appium.app|exe): 5.9.1
- Mobile platform/version under test: iOS hybrid
- Real device or emulator/simulator:  iPhone 6s plus 9.3
- Appium CLI or Appium.app|exe: 
## Details
1. set pageLoadTimeout in Page Objects class

``` java
driver.manage().timeouts().pageLoadTimeout(timeOutDuration.getTime(), timeOutDuration.getTimeUnit());
```
1. switch to webcontext before webpage loading (`context` retrieved from `driver.getContextHandles()`):

`driver.context(context);`
1. get web title:
   `driver.getTitle()`

According to the debug logs below, it did not wait with pageLoadTimeout
## Link to Appium logs

> [MJSONWP] Calling AppiumDriver.getContexts() with args: ["59ee33e3-ee6d-4599-bc98-6799248f39a9"]
> [debug] [iOS] Executing iOS command 'getContexts'
> [debug] [iOS] Getting list of available contexts
> [debug] [iOS] Retrieving contexts and views
> [debug] [iOS] Selecting by url: false 
> [debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
> [debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
> [debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"chrome-devtools://devtools/bundled/inspector.html?ws=localhost:27753/devtools/page/7","faviconUrl":"","thumbnailUrl":"/thumb/applewebdata://1A27EA09-517D-4D9B-B194-3B752C741EF6","title":"","url":"applewebdata://1A27EA09-517D-4D9B-B194-3B752C741EF6","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/7","appId":"PID:3514"}]
> [MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_7"]
> [HTTP] <-- GET /wd/hub/session/59ee33e3-ee6d-4599-bc98-6799248f39a9/contexts 200 30 ms - 98 
> [MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_7","59ee33e3-ee6d-4599-bc98-6799248f39a9"]
> [debug] [iOS] Executing iOS command 'setContext'
> [debug] [iOS] Attempting to set context to 'WEBVIEW_7'
> [debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/7
> [MJSONWP] Responding to client with driver.setContext() result: null
> [HTTP] <-- POST /wd/hub/session/59ee33e3-ee6d-4599-bc98-6799248f39a9/context 200 19 ms - 76 
> [HTTP] --> GET /wd/hub/session/59ee33e3-ee6d-4599-bc98-6799248f39a9/title {}
> [MJSONWP] Calling AppiumDriver.title() with args: ["59ee33e3-ee6d-4599-bc98-6799248f39a9"]
> [debug] [iOS] Executing iOS command 'title'
> [debug] [RemoteDebugger] Executing 'title' atom in default context
> [debug] [RemoteDebugger] Sending javascript command (function(){return function...
> [debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
> [debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type"...
> [debug] [RemoteDebugger] Found handler for message '1'
> [debug] [RemoteDebugger] Received result for atom 'title' execution: ""
> [MJSONWP] Responding to client with driver.title() result: ""
> [HTTP] <-- GET /wd/hub/session/59ee33e3-ee6d-4599-bc98-6799248f39a9/title 200 511 ms - 74

**Comment by truebit** [comment]
A workaround:
```java
String title = new WebDriverWait(driver, 30).until(new ExpectedCondition<String>() {

            @Override
            public String apply(WebDriver driver) {
                String currentTitle = driver.getTitle();
                if (StringUtils.isNoneEmpty(currentTitle)){
                    return currentTitle;
                }else{
                    return null;
                }
            }
            @Override
            public String toString() {
                return "title to be not null or empty";
            }
        });
```
but could not work

**Comment by imurchie** [comment]
Can you provide the full logs? I need to see how the page load timeout is (or is not) being set on the server side.

**Comment by truebit** [comment]
I used PageFactory in java-client:
```
PageFactory.initElements(new AppiumFieldDecorator(driver, 30, TimeUnit.SECONDS), pageObjects);
```
for that hybrid page, but it seems that the this PageFactory did not follow the timeout

**Comment by truebit** [comment]
It's a little complicated:
#### I set driver implicitlyTimeOut in test class, 
```java
driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
driver.manage().timeouts().pageLoadTimeout(5, TimeUnit.SECONDS);
```
with output log below:

> [HTTP] --> POST /wd/hub/session/634bfa94-1fab-4753-b429-b4951aca25d7/timeouts {"type":"implicit","ms":5000}
> [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",5000,"634bfa94-1fab-4753-b429-b4951aca25d7"]
> [debug] [iOS] Executing iOS command 'timeouts'
> [debug] [BaseDriver] Set implicit wait to 5000ms
> [MJSONWP] Responding to client with driver.timeouts() result: null
> [HTTP] <-- POST /wd/hub/session/634bfa94-1fab-4753-b429-b4951aca25d7/timeouts 200 4 ms - 76 
> [HTTP] --> POST /wd/hub/session/634bfa94-1fab-4753-b429-b4951aca25d7/timeouts {"type":"page load","ms":5000}
> [MJSONWP] Calling AppiumDriver.timeouts() with args: ["page load",5000,"634bfa94-1fab-4753-b429-b4951aca25d7"]
> [debug] [iOS] Executing iOS command 'timeouts'
> [debug] [iOS] Set page load timeout to 5000ms
> [MJSONWP] Responding to client with driver.timeouts() result: null
> [HTTP] <-- POST /wd/hub/session/634bfa94-1fab-4753-b429-b4951aca25d7/timeouts 200 2 ms - 76 

#### I used PageFactory to init PageObjects with timeout, but it seems `getTitle()` did not affected by PageFactory timeout:
```java
PageFactory.initElements(new AppiumFieldDecorator(driver, 5, TimeUnit.SECONDS), pageObjects);
```
#### finally I called like `hybridPage.title()` in the page class. the log output is like what I described in this issue

**Comment by imurchie** [comment]
The `pageLoadTimeout` is only in effect during the loading of a page. Once the page is loaded, commands are executed and returned. Your workaround is the only way to wait for the title to change.

**Comment by truebit** [comment]
But `getTitle()` should return not null if the page load finished. My html page is a Jquery mobile page with `<title>` set. I think `getTitle()` should be return not null after page loaded successfully?

**Comment by truebit** [comment]
And even with the workaround I posted, it would not get the title even when the page loaded successfully and the title was already there.
I found that if the title could not retrieved the first time, no matter how many times it tried, it would not get the title. log like below:

> [HTTP] --> POST /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/context {"name":"WEBVIEW_245"}
> [MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_245","3ec622b7-2234-4fb9-85f0-ac1c95cce9ce"]
> [debug] [iOS] Executing iOS command 'setContext'
> [debug] [iOS] Attempting to set context to 'WEBVIEW_245'
> [debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/245
> [MJSONWP] Responding to client with driver.setContext() result: null
> [HTTP] <-- POST /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/context 200 11 ms - 76 
> [HTTP] --> GET /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/title {}
> [MJSONWP] Calling AppiumDriver.title() with args: ["3ec622b7-2234-4fb9-85f0-ac1c95cce9ce"]
> [debug] [iOS] Executing iOS command 'title'
> [debug] [RemoteDebugger] Executing 'title' atom in default context
> [debug] [RemoteDebugger] Sending javascript command (function(){return function...
> [debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
> [debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type"...
> [debug] [RemoteDebugger] Found handler for message '1'
> [debug] [RemoteDebugger] Received result for atom 'title' execution: ""
> [MJSONWP] Responding to client with driver.title() result: ""
> [HTTP] <-- GET /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/title 200 511 ms - 74 
> [HTTP] --> GET /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/title {}
> [MJSONWP] Calling AppiumDriver.title() with args: ["3ec622b7-2234-4fb9-85f0-ac1c95cce9ce"]
> [debug] [iOS] Executing iOS command 'title'
> [debug] [RemoteDebugger] Executing 'title' atom in default context
> [debug] [RemoteDebugger] Sending javascript command (function(){return function...
> [debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
> [debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type"...
> [debug] [RemoteDebugger] Found handler for message '2'
> [debug] [RemoteDebugger] Received result for atom 'title' execution: ""
> [MJSONWP] Responding to client with driver.title() result: ""
> [HTTP] <-- GET /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/title 200 509 ms - 74 
> [HTTP] --> GET /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/title {}
> [MJSONWP] Calling AppiumDriver.title() with args: ["3ec622b7-2234-4fb9-85f0-ac1c95cce9ce"]
> [debug] [iOS] Executing iOS command 'title'
> [debug] [RemoteDebugger] Executing 'title' atom in default context
> [debug] [RemoteDebugger] Sending javascript command (function(){return function...
> [debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
> [debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type"...
> [debug] [RemoteDebugger] Found handler for message '3'
> [debug] [RemoteDebugger] Received result for atom 'title' execution: ""
> [MJSONWP] Responding to client with driver.title() result: ""
> [HTTP] <-- GET /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/title 200 509 ms - 74 
> [HTTP] --> GET /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/title {}
> [MJSONWP] Calling AppiumDriver.title() with args: ["3ec622b7-2234-4fb9-85f0-ac1c95cce9ce"]
> [debug] [iOS] Executing iOS command 'title'
> [debug] [RemoteDebugger] Executing 'title' atom in default context
> [debug] [RemoteDebugger] Sending javascript command (function(){return function...
> [debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
> [debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type"...
> [debug] [RemoteDebugger] Found handler for message '4'
> [debug] [RemoteDebugger] Received result for atom 'title' execution: ""
> [MJSONWP] Responding to client with driver.title() result: ""
> [HTTP] <-- GET /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/title 200 510 ms - 74 
> [HTTP] --> GET /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/title {}
> [MJSONWP] Calling AppiumDriver.title() with args: ["3ec622b7-2234-4fb9-85f0-ac1c95cce9ce"]
> [debug] [iOS] Executing iOS command 'title'
> [debug] [RemoteDebugger] Executing 'title' atom in default context
> [debug] [RemoteDebugger] Sending javascript command (function(){return function...
> [debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
> [debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type"...
> [debug] [RemoteDebugger] Found handler for message '5'
> [debug] [RemoteDebugger] Received result for atom 'title' execution: ""
> [MJSONWP] Responding to client with driver.title() result: ""
> [HTTP] <-- GET /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/title 200 510 ms - 74 
> [HTTP] --> GET /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/title {}
> [MJSONWP] Calling AppiumDriver.title() with args: ["3ec622b7-2234-4fb9-85f0-ac1c95cce9ce"]
> [debug] [iOS] Executing iOS command 'title'
> [debug] [RemoteDebugger] Executing 'title' atom in default context
> [debug] [RemoteDebugger] Sending javascript command (function(){return function...
> [debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
> [debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type"...
> [debug] [RemoteDebugger] Found handler for message '6'
> [debug] [RemoteDebugger] Received result for atom 'title' execution: ""
> [MJSONWP] Responding to client with driver.title() result: ""
> [HTTP] <-- GET /wd/hub/session/3ec622b7-2234-4fb9-85f0-ac1c95cce9ce/title 200 509 ms - 74

**Comment by jlipps** [comment]
Appium is doing the right thing here. If you want to ensure that a page is loaded and the timeout is in effect, you need to set the URL after switching contexts.
