### ISSUE TITLE
Get app package name with Appium AndroidDriver

### ISSUE THREAD

**Issue by louis57** [appium/appium#6448]
I am using Appium to automatically test some Android apps. I usually find elements with IDs, like this:

`appiumDriver.findElement(By.id("com.XXX.keyword:id/nextButton"));`

But sometimes package name is "com.XXX.keyword.debug", therefore the tests are failed. Currently, I have a parameter:

`String packageName = "com.XXX.keyword`

and then in my code, I write:
`appiumDriver.findElement(By.id(packageName + ":id/nextButton"));`

so I modify this parameter according to which version I am testing.

Is there any way I can get packageName with appiumDriver, something like appiumDriver.getPackageName() ?!, so the tests are independent on this matter.

**Comment by imurchie** [comment]
There is not, currently. It makes sense to add to the return value from creating a session, though. So I've opened a PR to do so.

**Comment by imurchie** [comment]
`appium-android-driver@1.10.3` contains this change. You can get it by installing Appium from npm with the `--no-shrinkwrap` option (see [npm install docs](https://docs.npmjs.com/cli/install)), otherwise it will be in Appium 1.5.3, whenever that comes out.

The return value from creating a session ought to be something like:

```
[ 'd4d6f6b4-1be3-4c15-a2dd-46acd751ef42',
  { platform: 'LINUX',
    webStorageEnabled: false,
    takesScreenshot: true,
    javascriptEnabled: true,
    databaseEnabled: false,
    networkConnectionEnabled: true,
    locationContextEnabled: false,
    warnings: {},
    desired:
     { app: '/Users/isaac/code/appium-android-driver/node_modules/sample-apps/node_modules/android-apidemos/bin/ApiDemos-debug.apk',
       deviceName: 'Android',
       platformName: 'Android' },
    app: '/Users/isaac/code/appium-android-driver/node_modules/sample-apps/node_modules/android-apidemos/bin/ApiDemos-debug.apk',
    deviceName: 'emulator-5554',
    platformName: 'Android',
    platformVersion: '5.1.1',
    appPackage: 'io.appium.android.apis',
    appWaitPackage: 'io.appium.android.apis',
    appActivity: 'io.appium.android.apis.ApiDemos',
    appWaitActivity: 'io.appium.android.apis.ApiDemos' } ]
```
