### ISSUE TITLE
Appium 1.5.2, Android (mobile Chrome): tap throws "method has not yet been implemented" exception in webview context

### ISSUE THREAD

**Issue by amaharana** [appium/appium#6450]
## The problem

In Appium 1.4.10, I was using "mobile: tap" to perform tap options on mobile Chrome. Since this has been removed in Appium 1.5.2, I switched to driver.tap(). This works in native context, but in webview context ("CHROMIUM"), it throws an exception.

```
driver.getContextHandles()
// 0 = "NATIVE_APP"
// 1 = "CHROMIUM"
```

This works fine. The coordinates are very close to the top, so I see a quick flash of the notification center being pulled down.

```
driver.context("NATIVE_APP");
driver.tap(1, 10, 49, 1);
```

This throws an exception:

```
driver.context("CHROMIUM");
driver.tap(1, 10, 49, 1);
```

Client log:

```
Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 8 milliseconds
```

Server log (replaced webview url):

```
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","CHROMIUM"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'CHROMIUM'
[debug] [AndroidDriver] Found existing Chromedriver for context 'CHROMIUM'. Using it.
[JSONWP Proxy] Proxying [GET /url] to [GET http://127.0.0.1:9515/wd/hub/session/bf79e635e6902a8117b3e915edc0930d/url] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"bf79e635e6902a8117b3e915edc0930d\",\"status\":0,\"value\":\"http://www.someurl.com/\"}"
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/99aee2b9-acef-4d2f-bb86-715c42b96cc9/context 200 33 ms - 76
[HTTP] --> POST /wd/hub/session/99aee2b9-acef-4d2f-bb86-715c42b96cc9/touch/perform {"actions":[{"action":"press","options":{"x":10,"y":49}},{"action":"wait","options":{"ms":1}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":10,"y":49}},{"action":"wait","options":{"ms":1}},{"action":"release","options":{}}],"99aee2b9-acef-4d2f-bb86-715...
[HTTP] <-- POST /wd/hub/session/99aee2b9-acef-4d2f-bb86-715c42b96cc9/touch/perform 501 4 ms - 122
```
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.2
- Last Appium version that did not exhibit the issue (if applicable): 1.4.10 (with mobile: tap)
- Desktop OS/version used to run Appium: Mac OSX Yosemite 10.10.5
- Node.js version (unless using Appium.app|exe): 5.7.0
- Real device or emulator/simulator: Android Nexus 6 6.0.1 (real device) with Chrome 50.0.2661.89
- Appium CLI or Appium.app|exe: Appium 1.5.2 CLI built from source

**Comment by scottdixon** [comment]
@amaharana 1.4 defers web context `tap` to `click`.

In 1.5, you can call `click` or:

```
browser
.init(desiredCaps)
.get('https://www.google.com')
.waitForElementByName('q', 5000)
  .tap() // or .click()
```

**Comment by amaharana** [comment]
Thanks Scott. I'll update my code to call click. Shouldn't 1.5 defer the web context tap to click as well?

**Comment by scottdixon** [comment]
I suspect it was a leftover from deprecating `mobile: tap`, with 1.5 removing `mobile: tap` completely, I think it's done the right thing here. Thoughts, @imurchie?

**Comment by amaharana** [comment]
I am getting the same exception for press() and longPress().

**Comment by scottdixon** [comment]
Thanks expected, you can only use commands supported by ChromeDriver, non of which are touch actions.

**Comment by imurchie** [comment]
Yes. None of the touch actions are available in the web context.

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/issues/4075

**Comment by amaharana** [comment]
Ah ok thanks for the pointers. How about retaining tap's functionality (redirect to click), in 1.5.2 as well?

**Comment by SrinivasanTarget** [comment]
@triager please label: Bug, Hybrid Apps

**Comment by dpgraham** [comment]
Assigning this level 3 priority. I doubt the core team will get around to this, considering that there's workarounds for this, but if somebody in the community wants to jump on this we'd be happy to take pull requests.

**Comment by anjanabendre** [comment]
I am using Appium 1.6.1, Android Tab 6.0.1, ChromeDriver 28,  Robot framework Appium Library version=1.4.5, 
Our application is hybrid app developed on ionic platform supports both android and iOS. It has Native and Webview. Most of the controls works on webview. But tap, press, TouchAction.Perform etc..not working on it.  It I try to perform these actions on the same controls in NATIVE view, as per appium server log, it performs the action but nothing happens on mobile app.

Please help!!  Our automation is stuck up as we have 80% cases where drag and drop, slider and tap functionality is required.

**Comment by anjanabendre** [comment]
Hi,
Any update on click(), tap() , swipe etc.. not working on hybrid mobile app doesn't work.
I would really appreciate if we get some updates on this issue.

Thanks,
Anjana Bendre

**Comment by anjanabendre** [comment]
please refer the log for exception:

[HTTP] --> POST /wd/hub/session/f67bdcb7-0b55-4591-a43f-e1c1ef79c1f9/touch/perform {"sessionId":"f67bdcb7-0b55-4591-a43f-e1c1ef79c1f9","actions":[{"action":"tap","options":{"y":null,"x":null,"count":1,"element":"0.05397038778391594-10"}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"y":null,"x":null,"count":1,"element":"0.05397038778391594-10"}}],"f67bdcb7-0b55-4591-a43f-e1c1ef79c1f9"]
[HTTP] <-- POST /wd/hub/session/f67bdcb7-0b55-4591-a43f-e1c1ef79c1f9/touch/perform 501 2 ms - 122 
[HTTP] --> GET /wd/hub/session/f67bdcb7-0b55-4591-a43f-e1c1ef79c1f9/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [GET /wd/hub/session/f67bdcb7-0b55-4591-a43f-e1c1ef79c1f9/screenshot] to [GET http://127.0.0.1:8000/wd/hub/session/660cdda262b5acd33ec488a80f55b22c/screenshot] with body: {}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
    at doJwpProxy$ (C:\Users\E0441161\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\mjsonwp\mjsonwp.js:354:13)
    at tryCatch (C:\Users\E0441161\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\E0441161\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\Users\E0441161\AppData\Local\Programs\appium-desktop\resources\app\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\E0441161\AppData\Local\Programs\appium-deskto

**Comment by mykola-mokhnach** [comment]
Touch actions support is not going to be implemented for webview context. Perhaps, W3C actions will work there.
