### ISSUE TITLE
Failed to launch simulator with [MJSONWP] Encountered internal error running command: Error: Condition unmet after xxxx ms. Timing out.

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium#6452]
## The problem

Failed to launch simulator in ios sim reset flow.

## Environment

* Appium version (or git revision) that exhibits the issue:
    - Appium 1.5.2
* Last Appium version that did not exhibit the issue (if applicable):
    - Appium 1.4.16
* Desktop OS/version used to run Appium:
    - Mac OS X 10.11.4
* Node.js version (unless using Appium.app|exe):
    - v4.2.4
* Mobile platform/version under test:
    - iOS SDK 9.2
    - Xcode 7.2
* Real device or emulator/simulator:
    - simulator
* Appium CLI or Appium.app|exe:
    - Appium CLI

And

- use ruby_lib 8.0.2

## Details

- When I tried to start and launch test, then ios simulator never launch and repeated timeout error.
    - `[MJSONWP] Encountered internal error running command: Error: Condition unmet after 60239 ms. Timing out.`
- Once restart Machine(Mac OS X 10.11), then some times fixed it and could run test. But after some running tests, this issue happened again.
- According to stackoverflow [here](http://stackoverflow.com/questions/36581271/not-able-to-run-ios-appium-tests-when-using-node), this issue is fixed sometimes if I re-install Xcode and its commandline tools. But this issue reproduced again.
- According to the following error log, I attached as Appium log, this problem may start to reproduce after failed to set locale with 500 error.
    - https://gist.github.com/KazuCocoa/ea10e43f452043f3eabe3585775c662f#file-20160430_appium_failed_to_launch_simulator-log-L76-L20160430

## Link to Appium logs

- Debug log
    - https://gist.github.com/KazuCocoa/ea10e43f452043f3eabe3585775c662f
- log of `[driver_start_with]` is https://github.com/KazuCocoa/scenarioForAppiumIssue5920/blob/master/lib/c_appium/driver.rb#L19, which is my log.

## Code To Reproduce Issue [ Good To Have ]

- You may be able to reproduce any apps such as https://github.com/KazuCocoa/scenarioForAppiumIssue5920/
- Once reproduce this issue, I never launch ios simulator until reboot machine.

**Comment by SrinivasanTarget** [comment]
@triager please label: iOS

**Comment by imurchie** [comment]
Can you run `xcrun simctl list` and post the output here?

**Comment by KazuCocoa** [comment]
yup.
Here you go. https://gist.github.com/KazuCocoa/640f310026c5d77993ae4c5cbf841787

**Comment by Julienblc** [comment]
I have the same issue.. Here's my test : 
- I create a first driver, with basics parameters.
- I kill this driver
- I had two capabilities : 
```
capabilities.setCapability("language", language);
capabilities.setCapability("locale", locale);
```

- Then I create a new driver (new IOSDriver).

FAIL : I got this error log : `Error: Appium was unable to set locale info: Error: Condition unmet after x ms`
Then, no one test can be run, even the simple one.. Seems like changing locale break something.

I have since I upgrade Appium from 1.4.13 to 1.5.2.

**Comment by imurchie** [comment]
@KazuCocoa Sorry, this slipped through my notice.

The issue is with the devices that are `disconnected` or `unavailable`. The system is waiting for everything to be `shutdown`. I am going to look at whether it is possible to expand this a little.

**Comment by imurchie** [comment]
@Julienblc I imagine the problem is the same. You can look in the output of the above command.

**Comment by KazuCocoa** [comment]
Thanks !

**Comment by Julienblc** [comment]
Sure, here you are : https://gist.github.com/Julienblc/76c043f678e7d997362b92bbc263368f

**Comment by imurchie** [comment]
For some reason the iPhone 6 Plus with Watch attached is `Booted`. This is what stops things from working.

You shouldn't need to restart your computer. With the output from the above command, find whatever is `Booted` and run `xcrun simctl shutdown XXX` where `XXX` is the udid of the device (in the logs above, `86717F63-C5D4-4AC6-A5F0-4E29532C87A1`).

Can you provide a gist of the Appium logs so I can see if I can see why that device is booted?

**Comment by Julienblc** [comment]
Sorry for the delay, but I can't believe it : it's working.. I haven't change anything.. I continue testing, and if I get the error again, i'll back to you. Thank you @imurchie !

**Comment by Julienblc** [comment]
When I run `xcrun simctl shutdown 86717F63-C5D4-4AC6-A5F0-4E29532C87A1` , nothing happened -> seems like he'n not able to shutdown it.

Here are my logs : https://gist.github.com/Julienblc/e9e7bbd49c79a9ae0fea2755e943b3f3


In the beginning of the day, everything worked. And after moment, a test failed, and after no test worked.. Seems like the problem comes from the booted simulator no ?

**Comment by imurchie** [comment]
Yes, the booted simulator is the cause. I have no idea why it is not able to be shutdown.

The only variable I see is that it is paired to a Watch. Do you use that functionality? If not, could you try running your tests against a iPhone 6s Plus sim without the pairing? I'm not able to make that make a difference, locally, but who knows.

**Comment by Julienblc** [comment]
No, I'm not using the watch at all :/
But it's not only the device linked with the watch. It's also in the list == Devices == -> -- iOS 9.3 --

**Comment by p00j4** [comment]
I too ran into this:
```
"appium": 1.5.3
"macOs": 10.10.5
"xcode":7.2
"iosSdk":9.2
```
**Stacktrace:**
```
[debug] [iOSSim] Killing all iOS Simulators
[iOSSim] The following devices are not in the correct state:
[iOSSim]     Simulator not shut down: iPhone (undefined, udid: 6s Simulator) is still in state '383365b5-8416-4970-8eb7-ff2c2aa8c68a'
[MJSONWP] Encountered internal error running command: Error: Condition unmet after 60089 ms. Timing out.
    at spin$ (lib/asyncbox.js:118:13)
    at tryCatch (/Users/pooja/Documents/Automation/Appium/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/pooja/Documents/Automation/Appium/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/pooja/Documents/Automation/Appium/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/pooja/Documents/Automation/Appium/appium/node_modules/asyncbox/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Users/pooja/Documents/Automation/Appium/appium/node_modules/asyncbox/node_modules/core-js/library/modules/es6.promise.js:89:39)
    at /Users/pooja/Documents/Automation/Appium/appium/node_modules/asyncbox/node_modules/core-js/library/modules/es6.promise.js:100:28
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Tried, shutting down** but fails
xcrun simctl shutdown 383365b5-8416-4970-8eb7-ff2c2aa8c68a
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Unable to shutdown device in current state: Shutdown

**Comment by imurchie** [comment]
Ah. Yes, Appium is using a regular expression to parse out the devices from the above list. It, however, fails when there are extra parentheses. So `iPhone (6s Simulator) (383365B5-8416-4970-8EB7-FF2C2AA8C68A) (Shutdown)` gets parsed incorrectly, unfortunately. 

The easiest way around this would be to rename the simulator to something of the same sort as the rest.

**Comment by Julienblc** [comment]
But the thing weird is the "state" of the device : `is still in state '383365b5-8416-4970-8eb7-ff2c2aa8c68a'`
As you said, the parser seems to consider the second part of the string (in this case the ID) as the state.

Is there any link that, for myself, I have to put an equal in front of my device in Appium ?
`=iPhone 6s Plus (9.3) [86717F63-C5D4-4AC6-A5F0-4E29532C87A1] (Simulator)`

**Comment by KazuCocoa** [comment]
In my environment, Appium 1.5.3 works fine. Thanks!

**Comment by p00j4** [comment]
@imurchie : thanks for the clue, got the sim up :+1:  (though same tests' findElement fails which works on 1.4.8, will find root cause & update)
well, I want to fix the regEx issue, can you please tell me file name or enclosing package, would be quick for me to solve (if its not on top of your head, no issues, will anyway debug back tracing the logs)

@Julienblc : for my case, what it meant was : observe here (the no of braces in 2nd line vs in 1st line)
```
iPhone 6 Plus (CE53D46C-11B7-4D92-A0BE-6BCD38DE66AD) (Shutdown)
iPhone (6s Simulator) (383365B5-8416-4970-8EB7-FF2C2AA8C68A) (Shutdown)
```

**Comment by KazuCocoa** [comment]
I close this issue because the original issue was solved.
thanks

**Comment by huig1149** [comment]
@KazuCocoa 
I solve the similar problew by reinstalling ideviceinstaller and libimobiledevice. You need the latest libimobiledevice, in the Appium 1.5.3 version.
Open the Terminal, type the commands below:

brew uninstall ideviceinstaller
brew uninstall libimobiledevice
brew install --HEAD libimobiledevice
brew link --overwrite libimobiledevice
brew install ideviceinstaller
brew link --overwrite ideviceinstaller
It may work for you.
Refer to Michael Gallacher：
[(http://stackoverflow.com/questions/38609898/ideviceinstaller-l-wont-show-the-app-list-on-the-iphone)]
