### ISSUE TITLE
[Question] Optional param always requires value.

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#6454]
@imurchie 

W.R.T to startActivity 
https://github.com/appium/node-mobile-json-wire-protocol/blob/master/lib/routes.js#L359

i started to work on implementing startActivity with intent and category on the java_client, it always looks for value when its mentioned optional on the server-side.

 And other question: What exactly does these values help -intentAction,intentCategory and  Flags?

@SrinivasanTarget you want add anything

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/java-client/issues/356

**Comment by saikrishna321** [comment]
https://github.com/appium/java-client/pull/381
