### ISSUE TITLE
Appium doesn't install my iOS app

### ISSUE THREAD

**Issue by romainlouvet** [appium/appium#6456]
## The problem

Since 1.5.2, When appium try to install my app -> Instruments Usage Error: Specified target process is invalid: fr.leboncoin.Leboncoin

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.2 (1.5.1 it's work!)
* Desktop OS/version used to run Appium: Mac os 10.11.4
* Real device or emulator/simulator: Real Device

## Link to Appium logs

https://gist.github.com/romainlouvet/7f7c80214bb66d394458c587231625c1

**Comment by wojciwojci** [comment]
I had problems with app installation after switching to appium 1.5.2 too. Try to install app that is stored on the same drive as appium server. Just try with path to app already downloaded instead of app path with http:// .... .

**Comment by fengkingcheng** [comment]
I had the same problem,app installation is ok on appium1.4.16,but it fail to install app when switching to appium 1.5.2

**Comment by nicolasavenza** [comment]
I ran into this issue as well after updating to 1.5.2 from 1.4.16.

Downgrading to 1.5.1 was my workaround until this fix gets in. ( @romainlouvet thanks for mentioning that it was working on 1.5.1!)

**Comment by romainlouvet** [comment]
it's good with Appium 1.5.3 :+1:
