### ISSUE TITLE
Run 2 Appium servers with on two different ports for 2 different devices

### ISSUE THREAD

**Issue by sabzwari1** [appium/appium#6460]
## The problem

I am trying to run 2 Appium servers with on two different ports e.g. 127.0.0.1:4723, 127.0.0.1:4777
I am able to pass in desired capabilities for 2 different devices

But for some reason appium sever automatically selects the first device appearing in adb devices  list and starts running my test steps on the same device for both appium server instances although different capabilities were passed when start servers.

## Environment
https://bitbucket.org/appium/appium.app/downloads/AppiumForWindows_1_4_16_1.zip
* Appium version 1.4.16.1
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): Appium.app|exe
* Mobile platform/version under test: Android 4.4.4, 4.2 
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app|exe

## Details

I am using AppiumLibrary (RobotFramewokr) for passing the desired capabilities

## Link to Appium logs

Screen shot have logs

**Comment by scottdixon** [comment]
Sounds like others were having this issue with the GUI https://github.com/appium/appium-dot-app/issues/519

If no luck, please reopen this issue in https://github.com/appium/appium-dot-app/
