### ISSUE TITLE
iOS swipe control center works in Appium 1.4 but not appium 1.5+

### ISSUE THREAD

**Issue by williamrussell-grindr** [appium/appium#6461]
## The problem
Appium does not currently support network connectivity for iOS. 
The workaround has been to swipe up the control center and then tap the wifi icon.  This works great in appium 1.4.

The test cases need to swipe up the bottom control center menu on iOS devices.

## Environment

* Appium 1.5+ is broken
* 1.4.13
* Mac osx el capitan
* IOS 9.3 iPhone 6
* Real
* Appium CLI & Appium.add 1.4.13

## Details

The code below works 100% on appium 1.4.13, but not on 1.5+

## Link to Appium logs
```
[HTTP] --> POST /wd/hub/session/3e8a914e-090a-4443-bc2e-077eaed07f46/touch/perform {"actions":[{"action":"press","options":{"x":275,"y":667}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":275,"y":467}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":275,"y":667}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":275,"y":467}},{"action":"...
[debug] [iOS] Executing iOS command 'performTouch'
[debug] [UIAuto] Sending command to instruments: target.touch([{"touch":[{"x":275,"y":667}],"time":0.2},{"touch":[{"x":275,"y":667}],"time":0.7},{"touch":[{"x":550,"y":1134}],"time":0.8999999999999999}])
[debug] [Instruments] [INST] 2016-05-02 23:12:29 +0000 Debug: Got new command 7 from instruments: target.touch([{"touch":[{"x":275,"y":667}],"time":0.2},{"touch":[{"x":275,"y":667}],"time":0.7},{"touch":[{"x":550,"y":1134}],"time":0.8999999999999999}])
[debug] [Instruments] [INST] 2016-05-02 23:12:29 +0000 Debug: evaluating target.touch([{"touch":[{"x":275,"y":667}],"time":0.2},{"touch":[{"x":275,"y":667}],"time":0.7},{"touch":[{"x":550,"y":1134}],"time":0.8999999999999999}])
[debug] [Instruments] [INST] 2016-05-02 23:12:29 +0000 Debug: target.touch(__NSCFArray)
[debug] [Instruments] [INST] 2016-05-02 23:12:30 +0000 Debug: point is not within the bounds of the screen
[debug] [UIAuto] Socket data received (70 bytes)
[debug] [UIAuto] Got result from instruments: {"status":17,"value":"point is not within the bounds of the screen"}
[HTTP] <-- POST /wd/hub/session/3e8a914e-090a-4443-bc2e-077eaed07f46/touch/perform 500 1083 ms - 131
[debug] [Instruments] [INST] 2016-05-02 23:12:30 +0000 Error: VerboseError: point is not within the bounds of the screen
[debug] [Instruments] [INST] 2016-05-02 23:12:30 +0000 Error: Error during eval: touch@[native code]
       eval code
eval@[native code]
startProcessing@file:///Users/williamrussell/5071A0F3-2DE7-4CAB-95D2-99316E730A1A/bootstrap-ba10a5de2043f93e.js:2793:30
bootstrap@file:///Users/williamrussell/5071A0F3-2DE7-4CAB-95D2-99316E730A1A/bootstrap-ba10a5de2043f93e.js:2861:31
global code@file:///Users/williamrussell/5071A0F3-2DE7-4CAB-95D2-99316E730A1A/bootstrap-ba10a5de2043f93e.js:2870:10
[debug] [Instruments] [INST] 2016-05-02 23:12:30 +0000 Debug: responding with:
```

## Code To Reproduce Issue [ Good To Have ]
```
        int height = driver.findElementByClassName("UIAWindow").getSize().getHeight();
        int width = driver.findElementByClassName("UIAWindow").getSize().getWidth();
        driver.swipe(width-100, height, width-100, height-200, 500);
        driver.findElementByAccessibilityId("Wi-Fi").click();
```

**Comment by williamrussell-grindr** [comment]
in the logs:
``` target.touch([{"touch":[{"x":275,"y":667}],"time":0.2},{"touch":[{"x":275,"y":667}],"time":0.7},{"touch":[{"x":550,"y":1134}],"time":0.8999999999999999}])
```
It looks as if my move to on the swipe area has been increased to fall off the screen. 
height(667)-200 is 467. NOT 1134 as the logs say. 

Any advice?

**Comment by scottdixon** [comment]
In 1.5, iOS touch behaves a little differently, see: https://medium.com/@scottdixon/appium-touch-examples-w-nodejs-ios-wd-ee2b9956aab1

**Comment by SrinivasanTarget** [comment]
It's fixed on java client.Please take a look at this: https://github.com/appium/java-client/issues/350. Incase of any issues please raise here: https://github.com/appium/java-client/issues

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by RatkoD** [comment]
I'm still unable to get the Control Centre on screen using the code from @williamrussell-grindr. Is it just me, or it's still not working.

**Comment by imurchie** [comment]
Can you define "Not working"? Can you provide a [gist](https://gist.github.com) of the logs?

**Comment by RatkoD** [comment]
I use the above code:
        int height = driver.findElementByClassName("UIAWindow").getSize().getHeight();
        int width = driver.findElementByClassName("UIAWindow").getSize().getWidth();
        driver.swipe(width-100, height, width-100, height-200, 500);
        driver.findElementByAccessibilityId("Wi-Fi").click();

This should pull up the control center and locate the Wi-Fi button and disable/enable wifi right? Well I get could not locate element (WiFi), but the reason is because the control center is not pulled up as expected. I'm using appium 1.5.3 and java-client 4.0.0.

**Comment by saoasuna** [comment]
I'm also having this problem; anyone know a solution?

**Comment by gitsaquib** [comment]
Any update on this?

**Comment by jlipps** [comment]
@imurchie did the coordinate system change from absolute to relative somewhere along the way here?
