### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by 03623170** [appium/appium#6466]
## The problem
After the update today i recevied this error message, when I try to check appium:
Error: Cannot find module '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
can you help?

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Update from what, to what?

Generally, do:

```
npm install -g appium-doctor
appium-doctor
```

**Comment by SrinivasanTarget** [comment]
@triager please label: ReproNeeded

**Comment by gendelbendel** [comment]
Not OP, but I had been using 1.4.13 and upgraded to 1.5.2.

When clicking the doctor button in the app, then issuing appium-doctor in that same terminal, this is the output:

Last login: Wed May  4 14:29:34 on ttys003
gs-mbp15-dward:~ dward$ '/Applications/Appium.app/Contents/Resources/node/bin/node' '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
module.js:341
    throw err;
    ^

Error: Cannot find module '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
gs-mbp15-dward:~ dward$ appium-doctor
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed.
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ HOME is set to: /Users/dward
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/dward/Library/Android/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/dward/Library/Android/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/dward/Library/Android/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/dward/Library/Android/sdk/tools/emulator
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor 
gs-mbp15-dward:~ dward$

------

Upon looking in the app itself, it looks as if appium-doctor wasn't packaged with the newest app and the old one it was.

The only file in /Applications/Appium.app/Contents/Resources/node_modules/appium/bin/ is ios-webkit-debug-proxy-launcher.js.

**Comment by imurchie** [comment]
Apparently it was not. You should open an issue with the [app](https://github.com/appium/appium-dot-app/issues/new). Thanks!
