### ISSUE TITLE
iOS App Reset and fresh app install with appium 1.5.2

### ISSUE THREAD

**Issue by PavithraNavaneeth** [appium/appium#6472]
**_## The problem_**
I have a requirement to ensure the clean state between tests (if test fails in between it should come back to main screen). 
Before all the Tests - I start the driver and after all the test completes - I quit the driver.
For new driver instance - I would like to start the app in full reset mode. And when I do driver.quit - I want the app to be uninstalled and simulator to be killed and cleared.
In between tests - I want to use driver.resetapp() - To restart the app (kill and start the app again)

Against grid run - How can I always ensure the clean state of simulator and new app install during first driver launch and restart app (without uninstalling app/kill simulator) inbetween and kill simulator, reset settings in the end ?

**_## Environment_**
Appium Version: 1.5.2
OS Version: MAC 
iOS Version: all iOS versions
Device type: ios Simulator

**_## Details_**
I run my tests against selenium grid either from local or CI (Team city job)

Selenium grid: Appium server and nodes run with --full-reset flag (To ensure the clean state of simulators) - I do not want to disturb it.

My framework code with appium 1.5.2 when I have capabilties with fullReset - false and noReset - true, driver.resetapp() works as expected.
However new driver launch or driver.quit - doesn't uninstall the app and doesn't kill the simulator.
I tried using Runtime.getRuntime().exec("killall Simulator"); and Runtime.getRuntime().exec("xcrun simctl erase all") --> to kill and erase the contents of simulator as part of Teardown();

Killing simulator and resetting via runtime command only works when I run the script in local. When I try running against grid - it doesnt work (it doesnt kill the simulator in grid node) - which is expected.

How can I overcome the above issue?

**_## Code To Reproduce Issue [ Good To Have ]_**

Rough java pseudo code with high-level flow:

@BeforeTest()
public IOSDriver<MobileElement> launchiOSApp() throws Exception {
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities .setCapability("deviceName","iPhone 6 Plus");
capabilities .setCapability("platformName","MAC");
capabilities .setCapability("platformVersion","9.1");
capabilities.setCapability("bundleID","value");
capabilities .setCapability("app",testapp);
capabilities .setCapability("waitForAppScript","5000");
capabilities .setCapability("fullReset","false");
capabilities .setCapability("noReset","true");
driver = new IOSDriver<MobileElement>(new                   URL("http://"+serverIP+":"+serverport+"/wd/hub"),capabilities);
return driver;
}

@Test()
public void actualTest() throws Exception {
my actual test
}

@AfterMethod()
public void restartApp() throws Exception {
driver.restApp()
}

@AfterTest()
public void tearDown() throws exception {
driver.quit();
//Applicable only for local run and not on grid
Runtime.getRuntime().exec("killall Simulator"); 
Runtime.getRuntime().exec("xcrun simctl erase all");
}

**Comment by jlipps** [comment]
You should run your test cases in different sessions, rather than relying on `resetApp`. Also, using both `fullReset` and `noReset` at the same time does not do anything different than just using `fullReset`.
