### ISSUE TITLE
Appium should try to match the desired capabilities for Android tests

### ISSUE THREAD

**Issue by midopa** [appium/appium#6473]
## The problem

When running iOS tests on Appium, Appium obeys the desired capabilities given when launching the driver. For example, if you specify a 8.4 iPhone, it will launch the appropriate simulator if it can. However, this isn't the case on Android. Appium just grabs/launches the first device/simulator it sees, unless it's given an explicit UDID or emulator name. I propose:
- If a UDID or an emulator name is given, then Appium should attempt to use that and fail if it can't. [Existing functionality]
- If given OS version in the device capabilities, it should do its best to find a matching device/emulator and fail if it can't.
- If it finds multiple matches, it will take the first. [Inline with existing functionality]
- If no OS version is given, then Appium can fall back to its default behavior of just grabbing the first thing it sees. [Existing functionality]

This sounds like the problem that Selenium Grid solves and I would've agreed a while back, but now with Appium Local Service in the mix, I see a lot of value for this kind of behavior natively in Appium. Local Service gives me the ability to spin up Appium on-demand and programmatically. It really simplifies the configuration and maintenance of test machines.

This should be just grabbing all the device/emulator info and looking for a match. I'm more than happy to implement this or help out, but I'd like to spitball this with you guys so I don't end up working on a PR that gets rejected.

Thoughts?
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.2
- Last Appium version that did not exhibit the issue (if applicable): N/A
- Desktop OS/version used to run Appium: OS X, El Capitan
- Node.js version (unless using Appium.app|exe): 1.5.2
- Mobile platform/version under test: Android
- Real device or emulator/simulator: Both
- Appium CLI or Appium.app|exe: CLI

**Comment by imurchie** [comment]
This seems like a good idea. Adding it to our features backlog.

What is "Appium Local Service"?

**Comment by SrinivasanTarget** [comment]
@imurchie Appium Local Service is to start appium server programatically in java-client

**Comment by midopa** [comment]
Cool. I'm already working on it!

**Comment by imurchie** [comment]
Nice! Let us know when you have something!

**Comment by midopa** [comment]
appium/appium-android-driver#141 is an implementation. Let me know what you think. If we're good, I'll add tests.
