### ISSUE TITLE
Appium kills and restarts iphone simulator on running tests with nodejs

### ISSUE THREAD

**Issue by yamelkaya** [appium/appium#6475]
## The problem

When I run tests with `npm run` command  on iphone simulator I faced with the same problem again and again:

1. Appium starts iphone simulator
2. Simulator loaded correctly and I see main page
3. After that simulator killed and restarted again
4. Simulator loaded and application too

I use configuration from [appium/sample-code](https://github.com/appium/sample-code/tree/master/sample-code/examples/node) repository but I changed appium version to 1.5.2 and platform version to 9.3.
 
## Environment

* Appium version (or git revision) that exhibits the issue: **1.5.2**
* Desktop OS/version used to run Appium: **OS X 10.11**
* Node.js version (unless using Appium.app|exe): **5.11**
* Mobile platform/version under test: **9.3**
* Real device or emulator/simulator: **iphone 5s simulator**
* Appium CLI or Appium.app|exe: **both**

## Link to Appium logs

[gist](https://gist.github.com/yamelkaya/95a5ca5b628358128ede24f6b541e685)

**Comment by alexprice91** [comment]
I am having the same issue.

**Comment by imurchie** [comment]
In the current logic, you will need to specify the capability `noReset` as `true`.

**Comment by alexprice91** [comment]
@imurchie thank you soo much. Cannot emphasize enough my appreciation!

**Comment by yamelkaya** [comment]
@imurchie thanks a lot for your reply. I've already noticed that `noReset` solves this problem but I still have one more question. 
Which test configuration should I use to be able to reset simulator before or after running all tests in project? I've tried to search over all issues on github but without any luck. For now I come up with following solution: at the end of all tests run empty test suit that init driver with `noReset = false`. But it looks like workaround. Do you have any other solutions for this problem?

**Comment by imurchie** [comment]
There is not really any way to do that. Appium does not provide any such management, as it is outside of its scope. Whatever is running the suite ought to handle such things (Appium does not know if a project is done. It just knows about sessions).
