### ISSUE TITLE
When remote debugger element is not in cache, should return StaleElementException, not JSError

### ISSUE THREAD

**Issue by gprasad84** [appium/appium#6476]
## The problem

In my test I am trying to click on a link and then use WebDriverWait for the link element to go stale using expected_conditions.staleness_of() to verify that the navigation has proceeded to the next page. This approach seems to work fine when I run my tests on browsers running on mac laptop. But I am getting errors when I am attempting to run the same test on an iPhone simulator using Appium server which looks like a bug to me.
## Environment
- Appium version: 1.5.1
- Desktop OS/version used to run Appium: OS X El Capitan 10.11.4
- Node.js version : v0.12.7
- Mobile platform/version under test: iOS 9.3
- Real device or emulator/simulator: simulator

Appium logs https://gist.github.com/gprasad84/41ad257c76b62a5632990f667cc8c23c
Console output https://gist.github.com/gprasad84/188cf70794fb189c26d9207990e7d791
Test code https://gist.github.com/gprasad84/a1cf3bc19625b0326fc95dc18bc7a9a2

Looking at the implementation of staleness_of(), the method immediately should return when there is a StaleElementReferenceException confirming that the element is no longer present in the DOM. But in my case I see a WebDriverException with a status of 17. Status explanation of code 17 per this error handler is ‘Javascript error’.

**Comment by jlipps** [comment]
I think you're right, @gprasad84. I'll add this to our backlog to take a look at this.

**Comment by imurchie** [comment]
This should be fixed in the latest beta.
