### ISSUE TITLE
Appium 1.5.2 "Android bootstrap socket crashed" when executing android_sample.js

### ISSUE THREAD

**Issue by zumwald** [appium/appium#6478]
## The problem

When executing 'mocha android-simple.js' from [the sample code](https://github.com/appium/sample-code/tree/master/sample-code/examples/node), Appium successfully installs the app, then the bootstrap crashes.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.2 (latest from 'npm install -g appium')
- Last Appium version that did not exhibit the issue (if applicable): N/A
- Desktop OS/version used to run Appium: OS X 10.11.4
- Node.js version (unless using Appium.app|exe): 0.12.13
- Mobile platform/version under test: Android
- Real device or emulator/simulator: Real device, 6.0.1
- Appium CLI or Appium.app|exe: issue reproduces on both
## Details

I've attempted passing in -p & -bp ports explicitly, as well as checked for processes hanging on to these ports on my machine to no avail.
## Link to Appium logs

[Gist here](https://gist.github.com/zumwald/d74343bd8fc17ebde22aa1bb0c9be0d7)
## Code To Reproduce Issue

It reproduces with the Node appium samples out-of-the-box: https://github.com/appium/sample-code/tree/master/sample-code/examples/node

**Comment by zumwald** [comment]
FWIW, this doesn't repro on an API19 emulator, perhaps something to do with the fact that I was running against an S7?

**Comment by jlipps** [comment]
If you're still experiencing this, @zumwald, can you try to reproduce with Appium 1.6.3? And what does logcat say at the moment of the crash? Any stacktraces from the bootstrap?
