### ISSUE TITLE
No screenshots when using serenity-core version 1.1.29-rc.3 and up

### ISSUE THREAD

**Issue by cdamian** [appium/appium#6479]
## The problem

serenity.take.screenshots is not working with appium when using serenity-core version 1.1.29-rc.3 and up.

Taking a guess here but it might be due to the following commit, please correct me if I am wrong:

https://github.com/serenity-bdd/serenity-core/commit/240b93be5bd79a80bf13778033753a0fd62b3f7f

## Environment

* Tested on the last 3 versions of appium
* Mobile platform/version under test - Android - real devices and emulators (Android versions 4.3 and up);
* Appium CLI and Appium.app|exe

## Details

I assume that the changes in the serenity commit that I linked above are causing the below behavior:

...
[HTTP] --> GET /wd/hub/session/7367c1d3-f5a0-46a7-b0cb-0db7cc161e88/title {}
[MJSONWP] Calling AppiumDriver.title() with args: ["7367c1d3-f5a0-46a7-b0cb-0db7cc161e88"]
[HTTP] <-- GET /wd/hub/session/7367c1d3-f5a0-46a7-b0cb-0db7cc161e88/title 501 1 ms - 122
[HTTP] --> GET /wd/hub/session/7367c1d3-f5a0-46a7-b0cb-0db7cc161e88/title {}
[MJSONWP] Calling AppiumDriver.title() with args: ["7367c1d3-f5a0-46a7-b0cb-0db7cc161e88"]
[HTTP] <-- GET /wd/hub/session/7367c1d3-f5a0-46a7-b0cb-0db7cc161e88/title 501 1 ms - 122
...

## Link to Appium logs

https://gist.github.com/cdamian/93941de6f8ea0bf613e7185432065ce9

## Code To Reproduce Issue [ Good To Have ]

https://github.com/serenity-bdd/serenity-core/commit/240b93be5bd79a80bf13778033753a0fd62b3f7f

## Dependencies versions from my .pom file:

       <maven.compiler.source>1.8</maven.compiler.source>
       <maven.compiler.target>1.8</maven.compiler.target>
       <maven-compiler-plugin.version>3.2</maven-compiler-plugin.version>
       <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
       <serenity.version>1.1.29-rc.3</serenity.version>
       <serenity.maven.version>1.1.29-rc.3</serenity.maven.version>
       <serenity.cucumber.version>1.1.6</serenity.cucumber.version>
       <serenity.jira.plugin.version>1.1.2-rc.1</serenity.jira.plugin.version>
       <serenity.jira.version>1.1.1</serenity.jira.version>
       <mysql.connector.version>5.1.31</mysql.connector.version>
       <json.simple.version>1.1.1</json.simple.version>
       <com.google.inject.version>4.0</com.google.inject.version>
       <slf4j.version>1.7.7</slf4j.version>
       <kafka.version>0.8.0</kafka.version>
       <junit.version>4.12</junit.version>
       <assertj.version>1.7.0</assertj.version>
       <lambdaj.version>2.3.3</lambdaj.version>
       <cucumber.version>1.2.4</cucumber.version>
       <appium.version>3.4.1</appium.version>
       <selenium.version>2.52.0</selenium.version>
       <surefire.plugin.version>2.18.1</surefire.plugin.version>

**Comment by scottdixon** [comment]
Sounds like an issue with `serenity-core` - please post this in https://github.com/serenity-bdd/serenity-core

Please reopen if you believe this is an Appium bug.

**Comment by imurchie** [comment]
The 501 errors from `title` are because you are in a native context, and title only works in webviews.

**Comment by cdamian** [comment]
Thank you all for replying.

I will report this issue to the link provided by @scottdixon

Initially, I reported this as an appium issue because at some point the logs were also specifying that the feature ( AppiumDriver.title() I assume) is not yet implemented.
