### ISSUE TITLE
Android - Not able to identify popup dialog/window

### ISSUE THREAD

**Issue by ushashegde** [appium/appium#6480]
## The problem

Android : Appium (UIautomatorviewer) is not identifying the element

I am trying to identify popup window in one of the android app, but appium is not able to identify that element.
It is android native element(mFilterPopupDialog) which is used in app
## Environment
- Appium version (or git revision) that exhibits the issue: 1.4.16.1
- Last Appium version that did not exhibit the issue (if applicable):NA
- Desktop OS/version used to run Appium: Windows 7
- Node.js version (unless using Appium.app|exe):NA
- Mobile platform/version under test: Android 5.0
- Real device or emulator/simulator: Real device(HTC 1+)
- Appium CLI or Appium.app|exe:

**Comment by imurchie** [comment]
`UIautomatorviewer` is unable to identify it? Appium will not, then, since both rely on UiAutomator. There is little that can be done except to look at how the popup is created. Is it non-standard?

**Comment by SrinivasanTarget** [comment]
@triager please label: Android

**Comment by ushashegde** [comment]
It is common popup which is widely used in android app (mFilterPopupDialog). 
But UIautomatorviewe is not able to identify it.

**Comment by imurchie** [comment]
There must be something with the way it is invoked, but I have no idea what that would be. Try posting on https://discuss.appium.io/ to see if anyone else has run into such an issue.

**Comment by Nuoxxx** [comment]
I have the same problem.It confused me a couple of days.Hope someone can help~

**Comment by SrinivasanTarget** [comment]
Try UIAutomator2 and incase if you hit the same feel free to log a new issue with logs inform of gist.
