### ISSUE TITLE
Original error: Bad response from getTreeForXML. Err was undefined and res was undefined)

### ISSUE THREAD

**Issue by tcvenkat** [appium/appium#6482]
info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.8.0_91)
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************

info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : appiumVersion, deviceOrientation, version, platform
info: [debug] Using local app from desired caps: /Users/vvarikuppala/dist/LottoNZ.app

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"},"isShuttingDown":false}}

info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"},"isShuttingDown":false}}
info: --> GET /wd/hub/status {}
info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"},"isShuttingDown":false}}
info: <-- GET /wd/hub/status 200 2.006 ms - 127 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"},"isShuttingDown":false}}

undefined

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: [debug] Creating new appium session ee2382dc-2faf-4dcb-b892-32ceb5df17ca

info: [debug] Removing any remaining instruments sockets

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"},"isShuttingDown":false},"sessionId":"ee2382dc-2faf-4dcb-b892-32ceb5df17ca"}

info: <-- GET /wd/hub/status 200 11.001 ms - 178 {"status":0,"value":{"build":{"version":"1.4.1","revision":"ce6220829063679bcccf5724515c29569c4a16d9"},"isShuttingDown":false},"sessionId":"ee2382dc-2faf-4dcb-b892-32ceb5df17ca"}

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: [debug] Cleaned up instruments socket /tmp/instruments_sock

info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim

info: [debug] No strings file 'Localizable.strings' for language 'en', getting default strings

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: --> GET /wd/hub/sessions {}

info: [debug] Responding to client with success: {"status":0,"value":[{"id":"ee2382dc-2faf-4dcb-b892-32ceb5df17ca","capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"app":"/Users/vvarikuppala/dist/LottoNZ.app","appiumVersion":"1.4.16","platformVersion":"8.4.1","browserName":"","deviceOrientation":"portrait","platformName":"iOS","version":"","deviceName":"IPhone 4S","platform":"MAC"},"app":"/Users/vvarikuppala/dist/LottoNZ.app","appiumVersion":"1.4.16","platformVersion":"8.4.1","deviceOrientation":"portrait","platformName":"iOS","version":"","deviceName":"IPhone 4S"}}],"sessionId":"ee2382dc-2faf-4dcb-b892-32ceb5df17ca"}

info: <-- GET /wd/hub/sessions 200 2.852 ms - 764 {"status":0,"value":[{"id":"ee2382dc-2faf-4dcb-b892-32ceb5df17ca","capabilities":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"app":"/Users/vvarikuppala/dist/LottoNZ.app","appiumVersion":"1.4.16","platformVersion":"8.4.1","browserName":"","deviceOrientation":"portrait","platformName":"iOS","version":"","deviceName":"IPhone 4S","platform":"MAC"},"app":"/Users/vvarikuppala/dist/LottoNZ.app","appiumVersion":"1.4.16","platformVersion":"8.4.1","deviceOrientation":"portrait","platformName":"iOS","version":"","deviceName":"IPhone 4S"}}],"sessionId":"ee2382dc-2faf-4dcb-b892-32ceb5df17ca"}

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: [debug] Could not parse plist file (as binary) at /Users/vvarikuppala/dist/LottoNZ.app/en.lproj/Localizable.strings

info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Users/vvarikuppala/dist/LottoNZ.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist

info: [debug] Getting bundle ID from app

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - - 

info: --> GET /wd/hub/session/ee2382dc-2faf-4dcb-b892-32ceb5df17ca/source {}

info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Bad response from getTreeForXML. Err was undefined and res was undefined)","origValue":"Bad response from getTreeForXML. Err was undefined and res was undefined"},"sessionId":"ee2382dc-2faf-4dcb-b892-32ceb5df17ca"}
info: <-- GET /wd/hub/session/ee2382dc-2faf-4dcb-b892-32ceb5df17ca/source 500 7.829 ms - 332 

info: <-- GET /wd/hub/status - - ms - - 

info: <-- GET /wd/hub/status - - ms - -

**Comment by tcvenkat** [comment]
Appium inspector is not opening IOS app in inspector

**Comment by SrinivasanTarget** [comment]
@tcvenkat Please raise appium-dot-app issues here:https://github.com/appium/appium-dot-app/issues/

**Comment by SrinivasanTarget** [comment]
@triager please close
