### ISSUE TITLE
**URGENT [iphone - internjs] Unable to switch to iFrame

### ISSUE THREAD

**Issue by skbeacon** [appium/appium#6485]
Hi All,

We have a site where there are iframes. As per our test requirement we need to switch to the iframes (we are using switchToFrame()) and search for a particular element. The problem arises when we are switching, the test hangs. Its working properly for Android but can not make it work in iphone (both sim and real device). 

We also tried by switching context but got no result. It would be great help if anyone can show us the light.

Thanks All

**Comment by imurchie** [comment]
Can you provide more information? Full Appium server logs are useful. Information about the iframes (are they hosted on the same domain? Is there complex nesting? Etc.).

**Comment by skbeacon** [comment]
@imurchie 
**Appium server log:**
File Attached
[appiumLogNew.txt](https://github.com/appium/appium/files/256377/appiumLogNew.txt)


**Some information about iframes:**
- Iframes contains ad from an ad provider.
- In some cases there are nested iframes.
We need to detects whether the ad is loaded in our ad space or not. And that's when it hangs when we try to switch to iframes. Iframes locate at the top, middle and lower part of the page.

**Comment by jlipps** [comment]
In the log, it showed your client making requests out of order; that could account for a hang. Can you try again with Appium 1.6.3 and see if the issue persists?
