### ISSUE TITLE
findElementByName() is not supported in new Version 1.5.2 (Ara) ?!

### ISSUE THREAD

**Issue by louis57** [appium/appium#6486]
I was using Appium 1.4.13 (Draco) and everything worked fine. Today I get notification to update to new version Appium 1.5.2 (Ara), and I get the error with mothod findElementByName()

`AppiumDriver<MobileElement> appiumDriver;`
`appiumDriver.findElementByName("metric").click();`

and I always get this error:

> org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.5.2 (Ara)
* Last Appium version that did not exhibit the issue (if applicable): Appium 1.4.13 (Draco)
* Desktop OS/version used to run Appium: Mac Capitan 10.11.4
* Mobile platform/version under test: Android 5.1.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

**Comment by imurchie** [comment]
Searching by name was deprecated over a year ago and removed from 1.5. In general, searching by accessibility id is better for a variety of reasons.

**Comment by louis57** [comment]
ah, thanks. it's good to know :)

**Comment by slipy12** [comment]
I know is not the best way to search, but not all apps or not all elements has an id for memory performance. Some times I needed it, there's no way to rescue this method?

**Comment by louis57** [comment]
In my case, I am testing an app and there is a few buttons which don't have any ID or content-desc, only button's text. So findElementByName was a good answer for me. Of course I can have some workaround to make it work, but findElementByName would be nice to have

**Comment by akasun1** [comment]
The same idea with louis

**Comment by akasun1** [comment]
I have changed my code to the methods below:

WebElement el=(WebElement) driver.findElementByAndroidUIAutomator("new UiSelector().text(\"" + something + "\")");

WebElement el=(WebElement) driver.findElementByAndroidUIAutomator("new UiSelector().text(\"something\") ");

**Comment by mgmanikandan87** [comment]
@louis57 I think this link will help you : https://www.youtube.com/watch?v=bT3tqaLNn-Y

**Comment by GdHadi** [comment]
@mgmanikandan87 use element locator from AndroidUIAutomator is worked for me,
