### ISSUE TITLE
Full-reset uses deprecated ideviceinstaller command

### ISSUE THREAD

**Issue by mirkara** [appium/appium#6487]
## The problem

Using the --full-reset flag uses an deprecated ideviceinstaller command

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.2
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: Mac 10.10.5
* Node.js version (unless using Appium.app|exe): 5.0.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: Unknown

## Details

N/A

## Link to Appium logs

[iOS] Could not remove 'com.test.test' from device
[MJSONWP] Encountered internal error running command: Error: Command failed: /bin/sh -c ideviceinstaller -u <UDID> -u com.test.test
WARNING: Using "-u" for "--uninstall" is deprecated. Please use "-U" instead.
ERROR: Uninstall failed. Got error "APIInternalError".

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

## Code To Reproduce Issue [ Good To Have ]

```
**Abridged somewhere
public class iOSTest
{
    private AppiumDriver ad = null;
        
    @BeforeTest
    public void setUp() {
        DesiredCapabilities capabilities = new DesiredCapabilities();

        File app = new File("/Path/To/Ipa.ipa");

        capabilities.setCapability("platformName", "iOS");
        capabilities.setCapability("platformVersion", "8.0.0");
        capabilities.setCapability("app", app.getAbsolutePath());
        capabilities.setCapability("deviceName", "device name");
        capabilities.setCapability("udid", "UDID");
    
        try{
            ad = new IOSDriver(new URL("http://127.0.0.1:4721/wd/hub"), capabilities);        
        }
        catch(Exception e){
            e.printStackTrace();
            System.exit(-1);
        }
    }

    @AfterClass
    public void tearDown()
    {
        ad.quit();
    }

    @org.testng.annotations.Test
    public void mainPageTest() {
        System.out.println("Test");
    }
}

```

**Comment by imurchie** [comment]
Fix submitted to project used to manage real devices.

**Comment by ksylvan** [comment]
What is the fix? Is it on appium-ios-driver?

**Comment by ksylvan** [comment]
Any update on when the fix will be integrated?

**Comment by imurchie** [comment]
Can you run the uninstall command manually and see what the output is? In my experience lately, the message only gets printed when there is an actual failure elsewhere.

In terms of getting the fix in, I cannot say. If it doesn't happen soon I may have to start using a forked version.

**Comment by zafrani** [comment]
I'm experiencing this bug as well.

**Comment by brianmrock** [comment]
Will this be included in 1.5.3?

**Comment by imurchie** [comment]
I will repeat...

Can you run the uninstall command manually and see what the output is? In my experience lately, the message only gets printed when there is an actual failure elsewhere.

**Comment by appiumnovice** [comment]
I'm encountering the same problem.
I installed appium 1.5.3 on Mac.

I tried to uninstall iOS app from the simulator :
`ideviceinstaller -u 192.168.64.101:5555 -U com.vsct.appun`

```
WARNING: Using "-u" for "--uninstall" is deprecated. Please use "-U" instead.
No iOS device found, is it plugged in?
```

**Comment by imurchie** [comment]
@appiumnovice Dealing with the simulator should not use `ideviceinstaller` at all. Can you attach a link to a [gist](https://gist.gitbub.com) of the server logs?

**Comment by appiumnovice** [comment]
Sorry,
The problem was server side. I customized a server for an Android simulator instead of iOS simulator (head in the clouds)!

**Comment by SrinivasanTarget** [comment]
@triager please close
