### ISSUE TITLE
Appium 1.5.0+ can't unlock LG L90 (D405)

### ISSUE THREAD

**Issue by mittt** [appium/appium#6489]
## The problem

 error: [MJSONWP] Encountered internal error running command: Error: Screen did not unlock successfully, retrying

Appium can't unlock a LG L90 (D405) with Android 5.0.2. Other devices work fine. It's set to Swipe Unlock, I also tried with No Lock Screen. I also Factory Reset the phone and tested again - still the same.
## Environment
- Appium version (or git revision) that exhibits the issue: Appium v1.5.2 (REV ad054100d63e2f8fbf33d6b4af50bfb22b514110) - lastest from source up to 2016-05-10
- Last Appium version that did not exhibit the issue (if applicable): I think it was the same with all 1.5 versions and it was working with 1.4.*.
- Desktop OS/version used to run Appium: .Net Client lib from NuGet
- Node.js version (unless using Appium.app|exe): node: '5.9.1',
- Mobile platform/version under test: Android
- Real device or emulator/simulator: LG L90 (D405) with Android 5.0.2 (latest for the device) 
- Appium CLI or Appium.app|exe: cli
## Link to Appium logs

[Appium Log](https://gist.github.com/mittt/318db63578161040e3b8db6dfea07954)
[Logcat](https://gist.github.com/mittt/a9da71d73bb9e49bd9db671ea82251b9)

**Comment by imurchie** [comment]
You got the same error when there was no lock screen? That seems odd.

But yes, there are problems with the unlocker for Android 5+. We are trying to fix it but not getting very far.

**Comment by mittt** [comment]
Yes, the screen just stays black in both cases.

**Comment by dpgraham** [comment]
Closing this because we don't support Android Driver. If this still happens on UIAutomator, will re-open.
