### ISSUE TITLE
Appium 1.5.2 cannot perform SWIPE, always gives the error "point is not within the bounds of the screen", but works very well with Appium 1.4.13

### ISSUE THREAD

**Issue by wenxiaoy** [appium/appium#6490]
## The problem
Appium 1.5.2 cannot perform SWIPE, always gives the error "point is not within the bounds of the screen", but the same command works very well with Appium 1.4.13

## Environment

* APPIUM 1.5.2
* iOS 9.3
* MAC OS
* RobotFramework

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
The iOS touch actions were made specification compliant, in the same way as the Android ones always were. This means, unfortunately, that the coordinates of move need to be relative, rather than absolute.

You didn't give any logs as the template asked, so I'm assuming that is the problem.

**Comment by wenxiaoy** [comment]
@imurchie Thank you:)
But even I tried with relative parameters, no swipe effect neither. 
Here is the log, so sorry to bother you again:


> [debug] [UIAuto] Socket data received (83 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"origin":{"x":194,"y":520},"size":{"width":60,"height":48}}}
[debug] [UIAuto] Sending command to instruments: au.getElement('0').tapWithOptions({"tapOffset":{"x":0.5,"y":0.5},"tapCount":1,"touchCount":1})
[debug] [Instruments] [INST] 2016-05-12 12:38:57 +0000 Debug: Got new command 6 from instruments: au.getElement('0').tapWithOptions({"tapOffset":{"x":0.5,"y":0.5},"tapCount":1,"touchCount":1})
[debug] [Instruments] [INST] 2016-05-12 12:38:57 +0000 Debug: evaluating au.getElement('0').tapWithOptions({"tapOffset":{"x":0.5,"y":0.5},"tapCount":1,"touchCount":1})
[debug] [Instruments] [INST] 2016-05-12 12:38:57 +0000 Debug: target.frontMostApp().elements()[0].elements()[6].elements()[5].tapWithOptions({tapOffset:{x:"0.5", y:"0.5"}, touchCount:"1", tapCount:"1"})
[debug] [UIAuto] Socket data received (25 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
[MJSONWP] Responding to client with driver.performTouch() result: ""
[HTTP] <-- POST /wd/hub/session/5ca64dfa-35c6-4589-b0c3-4dc1db519ba9/touch/perform 200 2216 ms - 74 
[HTTP] --> POST /wd/hub/session/5ca64dfa-35c6-4589-b0c3-4dc1db519ba9/touch/perform {"sessionId":"5ca64dfa-35c6-4589-b0c3-4dc1db519ba9","actions":[{"action":"press","options":{"y":"0.8","x":"0.8"}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"y":"0.3","x":"0.6"}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"y":"0.8","x":"0.8"}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"y":"0.3","x":"0.6"}},{"...
[debug] [iOS] Executing iOS command 'performTouch'
[debug] [UIAuto] Sending command to instruments: target.touch([{"touch":[{"x":"0.8","y":"0.8"}],"time":0.2},{"touch":[{"x":"0.8","y":"0.8"}],"time":1.2},{"touch":[{"x":"0.60.8","y":"0.30.8"}],"time":1.4}])
[debug] [Instruments] [INST] 2016-05-12 12:38:57 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-05-12 12:38:57 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-05-12 12:38:57 +0000 Debug: Running system command #7: /usr/local/Cellar/node/5.8.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/wr/cxnb3nmx3gd16pc5415tb57c0000gn/T/instruments_sock 2,{"status":0,"value":""}...
[debug] [Instruments] [INST] 2016-05-12 12:38:58 +0000 Debug: Got new command 7 from instruments: target.touch([{"touch":[{"x":"0.8","y":"0.8"}],"time":0.2},{"touch":[{"x":"0.8","y":"0.8"}],"time":1.2},{"touch":[{"x":"0.60.8","y":"0.30.8"}],"time":1.4}])
[debug] [Instruments] [INST] 2016-05-12 12:38:58 +0000 Debug: evaluating target.touch([{"touch":[{"x":"0.8","y":"0.8"}],"time":0.2},{"touch":[{"x":"0.8","y":"0.8"}],"time":1.2},{"touch":[{"x":"0.60.8","y":"0.30.8"}],"time":1.4}])
[debug] [Instruments] [INST] 2016-05-12 12:38:58 +0000 Debug: target.touch(__NSCFArray)
[debug] [UIAuto] Socket data received (25 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
[MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/5ca64dfa-35c6-4589-b0c3-4dc1db519ba9/touch/perform 200 2451 ms - 76 
[HTTP] --> DELETE /wd/hub/session/5ca64dfa-35c6-4589-b0c3-4dc1db519ba9 {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["5ca64dfa-35c6-4589-b0c3-4dc1db519ba9"]
[debug] [iOS] Deleting ios session
[debug] [UIAuto] Destroying instruments client socket.
[debug] [UIAuto] Closing socket server.
[debug] [UIAuto] Instruments socket server was closed
[debug] [Instruments] Starting shutdown.
[debug] [Instruments] Sending sigterm to instruments
[debug] [Instruments] [INST] 2016-05-12 12:39:04 +0000 Stopped: Script was stopped by the user
[debug] [Instruments] [INST] 2016-05-12 12:39:00 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-05-12 12:39:00 +0000 Debug: responding with:
       2016-05-12 12:39:00 +0000 Debug: Running system command #8: /usr/local/Cellar/node/5.8.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/wr/cxnb3nmx3gd16pc5415tb57c0000gn/T/instruments_sock 2,{"status":0,"value":""}...

**Comment by SrinivasanTarget** [comment]
@wenxiaoy Which appium client are you using?

**Comment by wenxiaoy** [comment]
Python.
Normally I use Robotframework+Appium Sever to test .

**Comment by shay777** [comment]
i have the same issue
after i upgraded the appium to 1.5.2 i get the error of:
 point is not within the bounds of the screen
any idea how to solve this?

**Comment by imurchie** [comment]
In the logs I see barely tiny numbers of the change in x/y position. What happens if you use larger values?

**Comment by wenxiaoy** [comment]
@shay777 I use "scroll" instead.

**Comment by wenxiaoy** [comment]
@imurchie if I put larger number, I will get the same error as @shay777 said "point is not within the bounds of the screen".

**Comment by shay777** [comment]
"scroll" is deprecated. I guess it depends on the version that you have.
I updated the java client to 4.0.0

**Comment by tony-pear** [comment]
My python code calls driver.swipe() with params well within bounds of the screen, but still getting following error

```
Got new command 71 from instruments: au.getWindowSize()
evaluating au.getWindowSize()
evaluation finished
responding with:
Running system command #72: /usr/bin/nodejs /usr/local/avm/versions/1.4.16/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/scratch_y8K1t.scratch/appium-uot3j7/instruments_sock 2,{"status":0,"value":{"width":414,"height":736}}...

Got new command 72 from instruments: au.dragApp(207,552,0,-515.1999999999999,0.8)
evaluating au.dragApp(207,552,0,-515.1999999999999,0.8)
target.dragFromToForDuration({x:"207", y:"552"}, {x:"0", y:"-515.1999999999999"}, "0.8")
end point is not within the bounds of the screen
VerboseError: end point is not within the bounds of the screen
Error during eval: dragFromToForDuration@[native code]
```
