### ISSUE TITLE
Not pushing command to appium work queue for SendKeys()

### ISSUE THREAD

**Issue by Abhilipsa12** [appium/appium#6491]
## The problem

In the below logs, i cannot see appium to push the command to appium work queue. I am trying to perform SendKeys() over a UIPickerWheel to select a value on it.

I believe that there is a version installation mismatch. Coz it is working on one machine, but not on others. Can anyone point-out on which specific components i need to check here for version compatibility. I have matched the node, appium, device versions.

2016-05-10 12:32:46:469 - info: --> POST /wd/hub/session/550f46c3-925a-481d-932c-7d9e421fc76d/element/0/value {"id":"0","value":["August"]}
2016-05-10 12:32:46:480 - info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","origValue":"connect ECONNREFUSED"},"sessionId":"550f46c3-925a-481d-932c-7d9e421fc76d"}
## Environment
- Appium version (or git revision) that exhibits the issue: 1.4.13
- Last Appium version that did not exhibit the issue (if applicable):
- Node.js version (unless using Appium.app|exe): v0.12.7
- Mobile platform/version under test: 9.3.1
- Real device or emulator/simulator: Real Device
- Appium CLI or Appium.app|exe: CLI
## Details

In one machine where the thing is working, i can see as soon as a POST request is received, it gets added into the appium work queue then it is forwarded to Instruments. But in my case, It is giving a generic error(13) by which i am unable to find out the actual problem.

**Comment by imurchie** [comment]
Can you provide more of the logs? Preferably _all_ of the logs? It is not possible to diagnose the situation with the snippet provided.

**Comment by anshumanchatterji** [comment]
@imurchie Please find the detailed logs attached here.

The error is at **_2016-05-10 06:32:13:558_**


[pCloudy appium log.txt](https://github.com/appium/appium/files/258571/pCloudy.appium.log.txt)

**Comment by anshumanchatterji** [comment]
I believe that the problem was due to RobotPort capability being set by mistake. Setting it to -1 solves the issue.
