### ISSUE TITLE
Unable to load url, device is not online when moving from Windows 7 to WIndows 10 Appium 1.4.16.1

### ISSUE THREAD

**Issue by aaronmagi** [appium/appium#6493]
## The problem

Problem on HTC M9: (Device FA541YJ05065 is not online)

> info: JSONWP Proxy: Got response with status 200: {"sessionId":"8f850c7adf1832bbf32101c4fdd8d25b","status":13,"value":{"message":"unknown error: Device FA541YJ05065 is not online\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62...

Samsung S6 (last line of output)

> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"FA541YJ05065"}}}

Both screens seem to load and then hang on a grey screen.

I have 2 environments setup, one on windows 7 and one on windows 10.  The windows 10 is my new development machine.  Currently this test will run correctly on the W7 Appium Server but not on my W10 box.

The test is to open a chrome browser and go to facebook.   I can get this to work for both a HTC M9 and Samsung S6 device on the Windows 7 machine but not the windows 10.
## Environment
- Appium version (or git revision) 1.4.16.1
- Last Appium version that did not exhibit the issue (if applicable):1.4.16.1
- Desktop OS/version used to run Appium: Windows 10
- Node.js version (unless using Appium.app|exe):Appium installed
- Mobile platform/version under test: Android 5.1  with Android SDK 23
- Real device or emulator/simulator: Real device HTC M9
- Mobile platform/version under test: Android 5.1.1  with Android SDK 23
- Real device or emulator/simulator: Real device Samsung S6 Edge
- Appium CLI or Appium.app|exe: Appium CLI and Appium exe
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

I have included the working and non working logs

[appium working.txt](https://github.com/appium/appium/files/258270/appium.working.txt)
[appium not working.txt](https://github.com/appium/appium/files/258271/appium.not.working.txt)

[appium not working S6.txt](https://github.com/appium/appium/files/258279/appium.not.working.S6.txt)
[appium working S6.txt](https://github.com/appium/appium/files/258280/appium.working.S6.txt)
## Code To Reproduce Issue [ Good To Have ]

[JavaTestClass.txt](https://github.com/appium/appium/files/258278/JavaTestClass.txt)

**Comment by aaronmagi** [comment]
I should note that when going back to Appium 1.14.13 the chrome driver does not load correctly but the Appium creates error messages and then fails.  It hangs in 1.14.16




[Appium 1413 fail.txt](https://github.com/appium/appium/files/259574/Appium.1413.fail.txt)

**Comment by jlipps** [comment]
If you're still experiencing this problem, please upgrade to Appium 1.6.3 and upload new logs if the problem persists.
