### ISSUE TITLE
Can't get object is password field or not

### ISSUE THREAD

**Issue by yunusmete** [appium/appium#6494]
## The problem

I'm trying to get selected object is a password field or not. Also same problem for long-clickable objects. For that, used below code:

```
  List<MobileElement> elementsByAndroidUIAutomator = driver.findElementsByAndroidUIAutomator("new UiSelector()");
  for (MobileElement mobileElement : elementsByAndroidUIAutomator) {
        System.out.println("password " + mobileElement.getAttribute("password"));
  }
```

According to [this class](https://github.com/appium/appium/blob/88e67ce987d78ce44de252219e07dc176a3511c2/lib/devices/android/bootstrap/src/io/appium/uiautomator/core/AccessibilityNodeInfoDumper.java), there is field named password. I used some of field like checked and checkable attributes and they are working correctly.
## Link to Appium logs

Exception log https://gist.github.com/kasirga32/8491bfc8813bc3686c99980134905a17
Appium log https://gist.github.com/kasirga32/976ccf36bc1608fe756de1c426e900bf

Thanks,
Yunus

**Comment by jlipps** [comment]
Unfortunately, there is no way in the Android automation API to detect whether a field is a password field.
