### ISSUE TITLE
iOS Native App Switch - Switching between App and Safari Browser is not working in Appium 1.5.0

### ISSUE THREAD

**Issue by seleniumbheema** [appium/appium#6498]
## The problem

Trying use below xpath, to switch back to app.

 driver.findElement(By.xpath("//UIAButton[@label = 'Back to app']")).click();

which is doing nothing to be...anybody have any solution for this, pleas post here, that would be greatly helpful

**Comment by scottdixon** [comment]
Are you in the app context when you try clicking the 'Back to app' button? Please provide your logs as a gist.
