### ISSUE TITLE
Appium server causing elements to become inaccessible

### ISSUE THREAD

**Issue by GreenJeans** [appium/appium#6500]
## The problem

When attempting iOS automation against a collectionView inside a headerView inside another collectionView, Appium itself is causing the elements to become inaccessible.

When Appium automation is running against an iOS simulator (or the Appium inspector has been launched), previously accessible elements (via iOS Accessibility Inspector) are no longer inspectable and cannot be automated against.

Killing the Appium server immediately restores accessibility of the elements (iOS Accessibility Inspector can inspect the elements).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.13, 1.5.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OSX 10.11.4
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 8.1, 8.3, 9.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app

**Comment by SrinivasanTarget** [comment]
@GreenJeans Please raise it here: https://github.com/appium/appium-dot-app/issues

**Comment by SrinivasanTarget** [comment]
@triager please close
