### ISSUE TITLE
1.5.2 - Android MainActivity is never detected by Appium

### ISSUE THREAD

**Issue by apallin** [appium/appium#6501]
## The problem

I already filed this against the beta1.5 version here and it got closed as a duplicate... but it is still failing on 1.5.2.  For reference https://github.com/appium/appium/issues/6020

Our main App activity never manages to be detected as launched even though it is and I can visually confirm this.

The error message is as such:
```
[MJSONWP] Encountered internal error running command: Error: Error occured while starting App. Original error: me.app.android.dev/me.app.android.ui.MainActivity never started
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/apk-utils.js:80:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:355:11)
```
Here is a gist to the full logs:
https://gist.github.com/apallin/5d76b0297d8c0d9b111817d724536eaf 

## Environment

* Appium 1.5.2
* Last Appium to work 1.4.16
* Mac OSX 10.11.4 (15E65)
* Node version v0.12.2
* Mobile version Android 4.4.2
* Real Device
* Appium CLI

**Comment by kasirga32** [comment]
Looks like your app is starting another activity. It can be a tutorial or a splash screen?

**Comment by imurchie** [comment]
What is `com.teslacoilsw.launcher/.NovaLauncher`? That is the package and activity that Appium is finding has focus.

```
Found package: 'com.teslacoilsw.launcher' and activity: '.NovaLauncher'
```

**Comment by apallin** [comment]
No idea, this was totally working on 1.4.16 and it detects our main activity as launched.  No app code is changing, only the version of Appium. Any idea how I can debug this further?

**Comment by imurchie** [comment]
With your app running can you run `adb shell dumpsys window windows` from the terminal? And then provide a gist of the output?

**Comment by apallin** [comment]
During Launch: https://gist.github.com/apallin/a7970c63efb31d1593880f72b18735ca
Post Launch: https://gist.github.com/apallin/915f336136fd54e6eea603d7c68983a1

When speaking with an Android dev, he mentioned that this sounds like a broken intent or no package/component, and asked what Appium is sending for launch.  Any thoughts?

**Comment by imurchie** [comment]
Appium is launching the app with the activity and package "me.app.android.dev/me.app.android.ui.MainActivity" the action intent "android.intent.action.MAIN" with the intent category of "android.intent.category.LAUNCHER"

**Comment by apallin** [comment]
Is that an issue on my end that is fixable or something that can be modified?  This seems strange that somehow the behavior is altered in 1.5+ and somehow I am the only one reporting this.

**Comment by apallin** [comment]
@imurchie any update or advice.  This is a big blocker

**Comment by imurchie** [comment]
I don't really have an update or advice. Are you able to share your app, so I can reproduce locally? Otherwise, are you comfortable modifying packages and trying things out?

**Comment by apallin** [comment]
@imurchie Sorry for taking so long to get back.  I am comfortable modifying the package but I can't share the application.  If you can advise me on what to alter, please let me know.

**Comment by apallin** [comment]
This is still blocking us as of now in upgrading, which we need to absolutely do with `1.6`

**Comment by apallin** [comment]
@imurchie after digging into this further, pretty sure I realized what is happening.  We are setting a lot of boot arguments with `-e` that seem to get seriously truncated.  Do you all put a limit on what you are sending to `adb` with a character limit?

**Comment by apallin** [comment]
So I have to obscure these credentials, but you can see that this is truncated compared to what we are actually sending this.  I have confirmed the entire ADB command works to launch the app outside of Appium, but failed when truncated like this.

```
[debug] [ADB] Running /Users/adampallin/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","65d4298f","shell","am","start","-n","me.lyft.android.dev/me.lyft.android.ui.MainActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000","-e","settings","'{xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}'","-e","environment","'{xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
```

You can clearly see that the `json` data being passed to `-e environment` is truncated and does not include the closing bracket or the rest of the data.  Compared to Appium 1.4.16, the whole thing is passed in.

**Comment by apallin** [comment]
@imurchie pinging again on this, mind taking a look?

**Comment by imurchie** [comment]
Sorry for the delay.

Can you give an example (in structure is enough) of the arguments you are passing in. Something is going wrong in our parsing. This is through `optionalIntentArguments`, correct?

**Comment by apallin** [comment]
@imurchie yeah this is through `optionalIntentArguments`, here is an example:

```
intent_variables = {
    "url": "https://www.foo.com",
    "url2": "https://www.foo2.com",
    "url3": "https://www.foo3.com",
    "url4": "https://www.foo4.com",
    "key1": "abc1234",
    "key2": "abcd1234",
    "key3": "abc12345",
    "string1": "test"
}
settings_variable = {
    "flagOn": False,
    "flag2On": True,
    "flag3On": True,
    "httpLoggingLevel": 1,
}
environment_quoted = quote(json.dumps(intent_variables), safe='}{\'')
settings_quoted = quote(json.dumps(settings_variable), safe='}{\'')
intent_args = {"optionalIntentArguments": "-e settings '{}'".format(settings_quoted) +
                                          " -e environment '{}'".format(environment_quoted)}
return intent_args
```

This gets added to capabilities.

**Comment by imurchie** [comment]
Is there anything else special about the intent arguments? I seem to be able to have arbitrarily long arguments and it still works.

**Comment by imurchie** [comment]
Can you try out the parsing test, with your particular configuration (since I don't have access to it). Something like https://github.com/appium/appium-adb/blob/master/test/unit/helper-specs.js#L105-L113 ? The following has the intent args from above, and just prints out the parsed version...

```js
  it.only('should parse lyft optionalIntentArguments', async () => {
      let v = {optionalIntentArguments: "-e settings '{%22httpLoggingLevel%22%3A%201%2C%20%22flag2On%22%3A%20true%2C%20%22flag3On%22%3A%20true%2C%20%22flagOn%22%3A%20false}' -e environment '{%22url4%22%3A%20%22https%3A%2F%2Fwww.foo4.com%22%2C%20%22key3%22%3A%20%22abc12345%22%2C%20%22url3%22%3A%20%22https%3A%2F%2Fwww.foo3.com%22%2C%20%22url2%22%3A%20%22https%3A%2F%2Fwww.foo2.com%22%2C%20%22url%22%3A%20%22https%3A%2F%2Fwww.foo.com%22%2C%20%22key2%22%3A%20%22abcd1234%22%2C%20%22key1%22%3A%20%22abc1234%22%2C%20%22string1%22%3A%20%22test%22}'"};
      let cmd = buildStartCmd(_.defaults(v, startOptions), 20);
      console.log(cmd);
    });
```

**Comment by apallin** [comment]
This seems to be fixed on 1.6 now.

**Comment by aquintiliano** [comment]
I am having this issue, version 1.6.2 and 1.6.3

**Comment by 103683** [comment]
i have the same issue.

**Comment by bgpros** [comment]
I just installed 1.6.5 and I have the same problem, does somebody have the solution for this. Thanks for the help!

**Comment by nobuhiroharada** [comment]
I just installed 1.7.0 and I have the same problem, does somebody have the solution for this. Thanks for the help!

**Comment by imurchie** [comment]
@nobuhiroharada Please provide the Appium server logs as a link to a [gist](https://gist.github.com). Without them we can do nothing.

**Comment by nobuhiroharada** [comment]
@imurchie Thanks for your comment.
Appium log
https://gist.github.com/nobuhiroharada/738735910ef75f27750939f747d731d5

Our app build by Cordova@6.5.0(android@5.2.2). Appium say there is no "MainActivity".(Actually there is "MainActivity" because app is launching in our testing device) Anyway when testing iOS app, it's working.
If you have any question or suggestion, feel free to ask.

Appium info
├─┬ appium@1.7.0
├─┬ appium-adb@3.0.0
├─┬ appium-chromedriver@3.0.1

appium_test.js config
```
var wd = require("wd");
var chai = require("chai");
var chaiAsPromised = require("chai-as-promised");
var fs = require("fs");

chai.use(chaiAsPromised);
chai.should();
chaiAsPromised.transferPromiseness = wd.transferPromiseness;

var desired = {
    "appium-version": "1.0",
    name: "jp.tjkapp.moteko3",
    platformName: "android",
    deviceName: "Samsung S5",
    app: "/hogehoge/android-armv7-release.apk",
    appActivity: "MainActivity"
};
```
