### ISSUE TITLE
Hi appium team, my script for ios stops at first findelement script itself. please resolve

### ISSUE THREAD

**Issue by Aswini-kumarPradhan** [appium/appium#6502]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by Aswini-kumarPradhan** [comment]
So i installed 1.4.13 again. scripts working.

**Comment by imurchie** [comment]
Is this not an issue, then?

**Comment by Aswini-kumarPradhan** [comment]
Oh! it is. We are meant to use the latest versions. I am having problem with latest version only.

**Comment by imurchie** [comment]
Then we need more information. Everything asked for in the first post is needed. A detailed description of the problem, server logs, any information about the context of the failing tests (operating system, clienet library, commands, etc.).

**Comment by Aswini-kumarPradhan** [comment]
FAILED CONFIGURATION: @BeforeClass launch
org.openqa.selenium.InvalidSelectorException: Locator Strategy 'name' is not supported for this session (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 19 milliseconds
    	        
IOSDriver<MobileElement> driver;

 		DesiredCapabilities capabilities = new DesiredCapabilities();
 		capabilities.setCapability("deviceName", "iPhone 6");
 		capabilities.setCapability("platformName", "iOS");
 		capabilities.setCapability("app", "/Users/ashwin/Desktop/EdCast.app");
 		capabilities.setCapability("fullReset", "true");
 		capabilities.setCapability("platformVersion", "9.3"); 
 		driver = new IOSDriver<>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);//change port
 		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
                driver.findElement(By.name("sign in btn 1")).click();

**Comment by Aswini-kumarPradhan** [comment]
above error after updating appium to 1.5.2 (ara).....this code worked using appium draco 1.4.13...

**Comment by imurchie** [comment]
Yes. There is no more `name` strategy. It was deprecated years ago and removed in 1.5.

Try using `accessibility id`.
