### ISSUE TITLE
Appium sporadically fails to click on a present element

### ISSUE THREAD

**Issue by Timawg** [appium/appium#6505]
## The problem

As title, Appium fails to click on a present element during automation. Sometimes it works, sometimes not. I'd say for the most part, it does not.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.13
* Desktop OS/version used to run Appium: El Capitan
* Mobile platform/version under test: iPhone 6, iOS 9.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: .app

## Link to Appium logs

https://gist.github.com/Timawg/f9e235a0e2a8ee7def8d9ea878f095cd (The error can be found on line 1072)

**Comment by yahman72** [comment]
I had similar problems, and the issue was that the UI was not completely rendered when trying to click on an element. For workarounds see #5830

**Comment by SrinivasanTarget** [comment]
@triager please close
