### ISSUE TITLE
TinyMCE iOS

### ISSUE THREAD

**Issue by xaircore** [appium/appium#6506]
## The problem

When trying to enter the text in the element, the completion of the test there is an error:
Exception: Cannot set the selection end (status: 13)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS X El Capitan
* Node.js version (unless using Appium.app|exe): 4.3.1
* Mobile platform/version under test: iPad 2 iOS 9.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI 

## Details

```
<div class="ws-editor-frame ws-basic-style mce-content-body mce-edit-focus" contenteditable="true">
<p><br data-mce-bogus="1"></p>
</div>
```

**Comment by imurchie** [comment]
This is not enough to go on. Could you provide the full appium server logs, at least?

**Comment by xaircore** [comment]
@imurchie [logs](https://gist.github.com/xaircore/1495c12de787e5da4a2c12c653d566ca)
