### ISSUE TITLE
Click/Tap works in Android 5.0 but not 5.1

### ISSUE THREAD

**Issue by KevinMarkVI** [appium/appium#6508]
## The problem

I was trying to write a basic login test for an Android app using the Appium Java bindings and I was having trouble clicking on an element. I tried clicking, tapping, offset tapping, TouchAction chain with no success. 

UPDATE: I ran into the same problem on a different element when using Android 5.0. I am still able to manually click on the element when I take control of the session.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.2
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: OSX 10.10 launching tests Via Sauce Labs
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: Android 5.1
- Real device or emulator/simulator: Emulator
- Appium CLI or Appium.app|exe: Appium via Sauce Labs
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

https://saucelabs.com/beta/tests/bd545d57f5114134bd2d15cadc19bae0/logs
## Code To Reproduce Issue [ Good To Have ]

[devryJavaTestNGLogin.zip](https://github.com/appium/appium/files/266544/devryJavaTestNGLogin.zip)

Changing the platform version to 5.1 will re-create the issue. 

Run framework with "mvn test". 

I can provide the app to an Appium team member within Sauce Labs. Slack Kevin Berg.

**Comment by dpgraham** [comment]
If this issue is still happening with a later version of Appium, please re-open this issue. Sorry for the non-reply.
