### ISSUE TITLE
iOS: Contents of a Safari Web View the second time around are now all labeled as not visible

### ISSUE THREAD

**Issue by lutzj82** [appium/appium#6513]
## The Problem

I have a native iOS app that uses OpenID for authentication.  The app launches a Safari WebView for login and logout. Testing against the simulator, I can log in, navigate around the app, and logout (using the Inspector as well as through automation). After logging out I am returned to the login page. When I try to re-log in, my tests fail as all the contents of the web view are now not visible. The last visible element is the UIAWebView. I've attach screen shots using the inspector both the first time around and the second time.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.2
- Last Appium version that did not exhibit the issue (if applicable): N/A
- Desktop OS/version used to run Appium: Mac El Capitan
- Node.js version (unless using Appium.app|exe): 5.10
- Mobile platform/version under test: iOS 9.3 with XCode 7.3
- Real device or emulator/simulator: simulator
## Details

<img width="1231" alt="screen shot 2016-05-18 at 8 32 07 am" src="https://cloud.githubusercontent.com/assets/1851537/15358807/4f223e22-1cd4-11e6-8434-cfe6bb0b0f66.png">

<img width="1229" alt="screen shot 2016-05-18 at 8 34 49 am" src="https://cloud.githubusercontent.com/assets/1851537/15358808/50ceda50-1cd4-11e6-9dfd-73614400ef77.png">
## Link to Appium logs

https://gist.github.com/lutzj82/925d49c05290d52884279b3b2125bb52

**Comment by imurchie** [comment]
It seems to be unable to connect to the webview at this point. 

Do you have the logs for when it _does_ connect to the webview? The first case above?

**Comment by lutzj82** [comment]
I've included a log where I start launch the appium inspector and the app is loaded with the webview I can access

## Link to Appium log

https://gist.github.com/lutzj82/3d33b5e5069731f6fd42757e4c95ee5b

**Comment by jlipps** [comment]
The webview connection logic has changed completely and this issue should be resolved in the latest version of Appium
