### ISSUE TITLE
Appium inspector Launches session with New Command Timeout 60 seconds

### ISSUE THREAD

**Issue by randersen** [appium/appium#6514]
## The problem

When launching an appium session using the inspector the New Command Timeout is set to 60 seconds. The problem with this is since most of the time commands aren't being sent the session will end while I'm trying to find elements on a page.

## Environment

* Appium 1.5.2
* Version 1.4.13 did not have this issue
* Mac OSX
* Android Inspector

## Appium logs

`[debug] [AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session c050b4e6-98af-4aa1-9786-a38bc20fae42 from our master session list`

**Comment by imurchie** [comment]
https://github.com/appium/appium-dot-app/issues/541

**Comment by randersen** [comment]
ahh searched the wrong repo, sorry about that.
