### ISSUE TITLE
Android native - Text encoding issue in webElement.sendKeys() with German umlauts

### ISSUE THREAD

**Issue by FrankBorland** [appium/appium#6515]
## The problem

Appium seems to have encoding issues in some situations like when German umlauts are entered into a text field on Android. For example, when executing webElement.sendKeys("blöööööööööööööööä"), the text "bl&APYA9gD2APYA9gD2APYA9gD2APYA9gD2APYA9gD2AO-" is inserted into the text field and not "blöööööööööööööööä". However, it is correctly inserted if I use one "ö" less in the string, which is really strange.

## Environment

* Appium 1.5.1
* Windows 7x64
* Node.js v4.4.3
* Android 5.1.1 (also happens on Android 6)
* Real device
* Appium CLI

## Details

When using as input text "blööööööööööööööä" (i.e. one "ö" less), the encoding works as expected:
...
[HTTP] <-- GET /wd/hub/session/9d07fc79-a6b3-4be1-b36b-282df8c50c0c/element/5/text 200 45 ms - 74 
[HTTP] --> POST /wd/hub/session/9d07fc79-a6b3-4be1-b36b-282df8c50c0c/element/5/value {"id":"5","value":["blÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¤"]}
[MJSONWP] Calling AppiumDriver.setValue() with args: [["blÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¤"],"5","9d07fc79-a6b3-4be1-b36b-282df8c50c0c"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"5","text":"blÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¤","replace":false,"unicodeKeyboard":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"5","text":"blÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¤","replace":false,"unicodeKeyboard":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending Unicode text to element: blÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¤
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Encoded text: bl&APYA9gD2APYA9gD2APYA9gD2APYA9gD2APYA9gD2APYA5A-
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
...

When using as input text "blöööööööööööööööä", the encoding does not work:
...
[HTTP] <-- GET /wd/hub/session/9d07fc79-a6b3-4be1-b36b-282df8c50c0c/element/6/text 200 36 ms - 74 
[HTTP] --> POST /wd/hub/session/9d07fc79-a6b3-4be1-b36b-282df8c50c0c/element/6/value {"id":"6","value":["blÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¤"]}
[MJSONWP] Calling AppiumDriver.setValue() with args: [["blÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¤"],"6","9d07fc79-a6b3-4be1-b36b-282df8c50c0c"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:setText","params":{"elementId":"6","text":"blÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¤","replace":false,"unicodeKeyboard":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:setText","params":{"elementId":"6","text":"blÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¤","replace":false,"unicodeKeyboard":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: setText
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using element passed in.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Sending Unicode text to element: blÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¶ÃƒÂ¤
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closing tag missing. Adding.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Encoded text: bl&APYA9gD2APYA9gD2APYA9gD2APYA9gD2APYA9gD2AO-
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
...

The line "Closing tag missing. Adding." already indicates that there is an encoding issue.

**Comment by imurchie** [comment]
Interesting. Reproducible. Looking into the cause.
