### ISSUE TITLE
driver.swipe() using Java is throwing "point is not within the bounds of the screen" warning even with coordinates in the middle of the screen

### ISSUE THREAD

**Issue by lmlindy** [appium/appium#6519]
## The problem
I updated from Appium 1.4 and the swipe feature stopped working. Appium is returning with "point is not within the bounds of the screen (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 3.93 seconds"
This happens even if the points are all in the middle of the screen.

## Environment

* Appium 1.5.2
* Last Appium version that did not exhibit the issue: 1.4.3
* OSX El Capitan
* iOS 9.3.2
* Real device: iPad 
* Appium.app

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs
https://gist.github.com/anonymous/e5715d1954e00433b673ce82bde56911

## Code To Reproduce Issue 

mDriver.swipe(500, 747, 500, 400, 1000);

**Comment by imurchie** [comment]
What language are you using? The iOS coordinates were changed to relative (as they should be, according to the specification).

**Comment by truebit** [comment]
this refers to https://github.com/appium/java-client/issues/350
it's already fixed and will be released in java-client v4.0

**Comment by yuqizhaoyq** [comment]
@truebit @scottdixon 
Python client also exists the problem.

**Comment by aquintiliano** [comment]
I'm using java-client v4.0, and the issue still occurs, the command was:
element.swipe(SwipeElementDirection.LEFT, 1000);
