### ISSUE TITLE
Unknown server error while clicking on the element in Android L device

### ISSUE THREAD

**Issue by rajagondap** [appium/appium#6520]
## Appium is throwing Unknown server error while executing click operation on mobile application.

I am using Appium to Automate Hybrid android application. I want to click on link element for that i have used driver.findElement(By.xpath("xpath of the element which is clickable")).click(); method to click on the element.
## Environment
- Appium version 1.4.16.1
- Last Appium version that did not exhibit the issue (if applicable): Not documented 
- Desktop OS/version used to run Appium: Windows
- Node.js version (unless using Appium.app|exe): 0.12.7
- Mobile platform/version under test: 5.1 Lolipop
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: Appum App
## Details

But the appium error i found is as follows
info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"CATCH_ALL: java.lang.NumberFormatException: Invalid int: \"74.96875\"\n\tat java.lang.Integer.invalidInt(Integer.java:138)\n\tat java.lang.Integer.parse(Integer.java:410)\n\tat java.lang.Integer.parseInt(Integer.java:367)\n\tat java.lang.Integer.parseInt(Integer.java:334)\n\tat io.selendroid.server.model.AndroidWebElement.getCenterCoordinates(AndroidWebElement.java:233)\n\tat io.selendroid.server.model.AndroidWebElement.click(AndroidWebElement.java:249)\n\tat io.selendroid.server.handler.ClickElement.safeHandle(ClickElement.java:36)\n\tat io.selendroid.server.handler.SafeRequestHandler.handle(SafeRequestHandler.java:87)\n\tat io.selendroid.server.AndroidServlet.handleRequest(AndroidServlet.java:264)\n\tat io.selendroid.server.common.BaseServlet.handleHttpRequest(BaseServlet.java:67)\n\tat io.selendroid.server.common.http.ServerHandler.channelRead(ServerHandler.java:53)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)\n\tat io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:223)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)\n\tat io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)\n\tat java.lang.Thread.run(Thread.java:818)\n"},"sessionId":"9d414cad-c55a-b412-45dc-136549572601"}

> info: <-- POST /wd/hub/session/9d414cad-c55a-b412-45dc-136549572601/element/%3Awdc%3A1463743598485/click 500 278.282 ms - 3112 
> info: --> DELETE /wd/hub/session/9d414cad-c55a-b412-45dc-136549572601 {}
> info: Shutting down appium session

I found that java.lang.NumberFormatException: Invalid int: \"74.96875\"\n\tat  this exception is causing the error(the back slash in above number causing the issue is my guess). 

This issue is only observer in Android L device. on KK devices its working fine. 

Please let me know what will be the reason.

**Comment by rajagondap** [comment]
Please resolve this ASAP as i need it for automating 500 Test cases by next week.

**Comment by imurchie** [comment]
Can you provide the Appium server logs as a gist? We cannot tell anything from the client exception.

**Comment by rajagondap** [comment]
Hi Isaac,
I am not sure how to take server logs. Could you please guide me where to
take it.?

Regards,
Rj

**Comment by imurchie** [comment]
Wherever you are running the Appium server. If on the command line, it is just the output from the command. In the app, it is the stuff in the main window.
