### ISSUE TITLE
Ubuntu 16 + "Killing any old chromedrivers" -> crash

### ISSUE THREAD

**Issue by ntishko** [appium/appium#6526]
## The problem

When switching to webview context, I'm seeing this as the last command in the logs.  When I run it by hand, my ssh connection is dropped and the appium is closed.  Here is the command -> "ps -ef | grep /home/testing/.linuxbrew/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/linux/chromedriver_64 | grep -v grep |grep -e '--port=9515\(\s.*\)\?$' | awk '{ print $2 }' | xargs kill -15".  

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Ubuntu 16.04
* Node.js version (unless using Appium.app|exe): 6.2
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Android 6.0.1 device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

This crash occurs regardless of whether appium is loaded or not.  This is an Ubuntu 16.04 box I'm remoting into.  This was a non-issue when I was running Ubunutu 15, but after upgrading to 16.04, this is a persistent problem.  For comparison, I issued the same command to an Ubuntu 14.04.4 LTS box (via ssh) and nothing happened.  

## Link to Appium logs

(Logs to come)

**Comment by thyraxion** [comment]
I just experience the exact same issue on my Ubuntu 16.04.
It seems to be a bug with 16.04. 

https://bugs.launchpad.net/ubuntu/+source/procps/+bug/1577297
http://ubuntuforums.org/showthread.php?t=2322677&goto=newpost/

Because there are currently no chromedriver processes running, grep won't return anything and the command will be the same as :

`echo | xargs kill -15`

Here are my appium logs :
[test.txt](https://github.com/appium/appium/files/281594/test.txt)

**Comment by ntishko** [comment]
I manually rolled back the procps package to 1:3.3.9-1ubuntu8 via the following commands:

sudo dpkg -i /var/cache/apt/archives/libprocps3_3.3.9-1ubuntu8_amd64.deb
sudo dpkg -i /var/cache/apt/archives/libprocps3-dev_3.3.9-1ubuntu8_amd64.deb
sudo dpkg -i /var/cache/apt/archives/procps_3.3.9-1ubuntu8_amd64.deb

after downloading them from a repo (e.g. - https://launchpad.net/ubuntu/+source/procps)

Tests run fine now.  Thanks!

**Comment by imurchie** [comment]
This has been fixed and will be in the next release. See https://github.com/appium/appium-chromedriver/pull/38
