### ISSUE TITLE
iOS - Appium - unable to scrollTo a particular element and click on it with an real device

### ISSUE THREAD

**Issue by LokeshGangaiah** [appium/appium#6527]
## The problem

Unable to scroll to a particular element and click on that element.
When used scrollTo or scrollToExact function, the page does to top scroll more rather than the bottom scroll and finally unable to find the element it intended for.
And gets an error "elementId 3 could not be tapped"

## Environment

* Appium version: 1.5.2
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version Mac OS 10.10.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:iphone 6 9.2 os actual device
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

So there is a list when user clicks get bigger and among that list we need to scroll down to select a particular element which is not in the first page/ first screen seen.

When try to do that via script the page goes down / up ,but not till the element and will be unable to see it or select it,finally the script ends.

## Link to Appium logs

https://gist.github.com/LokeshGangaiah/d01caf20c65e44a5523a14a9d6270b17 - appium logs

https://gist.github.com/LokeshGangaiah/c23dee0573af36b5b13da4288afcc2c4 - eclipse logs

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code
[code appium ios.txt](https://github.com/appium/appium/files/280853/code.appium.ios.txt)
 and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by SrinivasanTarget** [comment]
Please look at this: https://github.com/appium/java-client/issues/350

**Comment by SrinivasanTarget** [comment]
@triager please close
