### ISSUE TITLE
in caps.md,bundleId Description "but you must provide 'udid'." udid is OK ?

### ISSUE THREAD

**Issue by gucj** [appium/appium#6528]
I read caps.md [https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md](url),when I see bundleId Description
Bundle ID of the app under test. Useful for starting an app on a real device or for using other caps which require the bundle ID during test startup. To run a test on a real device using the bundle ID, you may omit the 'app' capability, **but you must provide _'udid'_.** 
I think udid should be  Bundle ID,is it right?

**Comment by SrinivasanTarget** [comment]
Please raise your doubts here: https://discuss.appium.io/

**Comment by SrinivasanTarget** [comment]
@triager please close
