### ISSUE TITLE
switch to WEBVIEW_1 after resetApp

### ISSUE THREAD

**Issue by IvanStawski** [appium/appium#6529]
## The problem

switch to context "WEBVIEW_1" when testing ios app after resetApp() will produce 500 error
!
## Environment
- Appium version1.5.2:
- Last Appium version that did not exhibit the issue (if applicable): 1.4.16
- Desktop OS/version used to run Appium: MAC OS El Capitan
- IOS 9.3, Xcode 7.3.1, iphone 6:
- Simulator
- Appium.app
## Link to Appium logs

https://gist.github.com/IvanStawski/8afd94b28490acc4876f8594d0ad4185
## Code To Reproduce Issue [ Good To Have ]

nodejs:
driver
   .context("WEBVIEW_1")
   .resetApp()
   .context("WEBVIEW_1")

**Comment by jlipps** [comment]
Sorry to have delayed so long in responding to this report. Please try with the latest version of Appium and if the problem persists, upload a new _full_ version of your Appium logs (including the startup logs etc)
