### ISSUE TITLE
Selendroid-Like Inspector For iOS

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#6530]
Hi there,

in our company we use both Appium automation features - for iOS and for Android. The thing is, that we suffer a lot while using iOS inspector (which is a part of desktop client), since it is not very convenient for use and it is quite slow. In contrary to it Selendroid's built-in inspector, which works in web browser, is much more convenient and universal. So we tried to modify its source code a bit to make it compatible with iOS and it did the trick:
![inspector_screenshot](https://cloud.githubusercontent.com/assets/7767781/15544889/a41fe444-229a-11e6-9e56-22dc62b54d2a.png)

I would be happy to share this implementation with Appium community, so it could be possible to create web inspector implementation for iOS.
My first question is about licensing issues, because the code is based on the original implementation from eBay (Apache license) and I've just changed small part of it. 
And the second question: currently this inspector acts as an offline web page. Probably, it would be more useful to integrate it with iOS driver and make it available on a custom port, like it is done for Selendroid. 

Thanks for your cooperation.

**Comment by vpathania1** [comment]
I would say create a github project for it and have wider community access it, there will be tons of people waiting to pounce on it to make it better and beautiful. Personally I am more than happy to look at it and contribute.

**Comment by SrinivasanTarget** [comment]
@imurchie @jlipps @bootstraponline FYI

**Comment by bootstraponline** [comment]
This is fine for the legacy iOS driver but XCUITest will be using [Facebook's inspector](https://github.com/facebook/WebDriverAgent/tree/master/Inspector).

**Comment by jlipps** [comment]
@mykola-mokhnach thanks for your work! That's really awesome. What I would say is to simply create a repo detailing how to use this, and then popularize it within the community as an alternative choice. If it receives good adoption, we can mention it in the docs and so forth.

At this point the core team does not officially support any inspector project so unfortunately we can't take this under our wing to help maintain it ourselves.

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach If you have created any repo please tag it here.It may benefit many of our users.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by saikrishna321** [comment]
@mykola-mokhnach this is really awesome.. would be great if you could share your work on repo

**Comment by mykola-mokhnach** [comment]
@saikrishna321  @SrinivasanTarget  @jlipps I've published my Inspector implementation here: https://github.com/mykola-mokhnach/Appium-iOS-Inspector
Feel free to add your comments and suggestions :)

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach Awesome Buddy:) Will take a look at it soon 👍

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach It looks cool buddy Nice 👍

**Comment by saikrishna321** [comment]
@mykola-mokhnach Thanks buddy :) This is gonna help a lot of them
