### ISSUE TITLE
IOS 9.3.1 Iphone SE instruments crashing on startup

### ISSUE THREAD

**Issue by vpathania1** [appium/appium#6531]
## The problem

I am just installing the App through Appium UI. Iphone SE 9.3.1 instruments crashing on the startup. It installs the App but crashes on the launch of the app. I have other phone with lower OS versions and they work fine looks its only a problem with with 9.3.1.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.2
* Last Appium version that did not exhibit the issue (if applicable): did not downgrade
* Desktop OS/version used to run Appium: Mac OS X El Capitan
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Iphone 9.3.1 Iphone SE
* Real device or emulator/simulator: Real Devices
* Appium CLI or Appium.app|exe: Appium exe

## Details

Appium pushes the App on the phone I can see the app installing but it fails to launch it.

## Link to Appium logs

> [Instruments] Launching instruments
> 
> [debug] [Instruments] Attempting to run app on real device with UDID '49c0d3a221589569d6853e11098b272476ba8343'
> [debug] [Instruments] Found Insruments-Without-Delay: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7
> [debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/q4/5r56k4yx4k7039q_mznks3mrwhq0mt/T/appium-instruments/instrumentscli0.trace -w 49c0d3a221589569d6853e11098b272476ba8343 com.weather.TWC -e UIASCRIPT "/Users/vishal.pathania/Library/Application Support/appium/bootstrap/bootstrap-32a8f430cae4a579.js" -e UIARESULTSPATH /var/folders/q4/5r56k4yx4k7039q_mznks3mrwhq0mt/T/appium-instruments'
> [debug] [Instruments] And extra without-delay env: {}
> [debug] [Instruments] And launch timeouts (in ms): {"global":90000}
> 
> [HTTP] --> GET /wd/hub/status {}
> [MJSONWP] Calling AppiumDriver.getStatus() with args: []
> 
> [HTTP] <-- GET /wd/hub/status - - ms - - 
> 
> [debug] [Instruments] [INST STDERR] 2016-05-25 15:27:28.352 instruments[50728:5184570] WebKit Threading Violation - initial use of WebKit from a secondary thread.
> 
> [debug] [Instruments] Instruments exited with code 253
> 
> [Instruments] Error launching instruments: Instruments crashed on startup

## Code To Reproduce Issue [ Good To Have ]

Using Appium exe to install and launch the app.

**Comment by imurchie** [comment]
This usually means that the app is not built correctly. It needs to be a debug build for a real device.

See https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices.md#appium-on-real-ios-devices

**Comment by SrinivasanTarget** [comment]
@triager please close
