### ISSUE TITLE
How to select multiple contacts 

### ISSUE THREAD

**Issue by Pushpank** [appium/appium#6533]
## The problem

I am trying to select multiple contacts, Able to select by name one by one but have not another option if dont know thw name, can any one guide me in this
## Environment

* Appium version (or git revision) that exhibits the issue:1.5.02
* Desktop OS/version used to run Appium: mac 10
* Mobile platform/version under test: Android
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:

![screen shot 2016-05-26 at 12 38 57 pm 2](https://cloud.githubusercontent.com/assets/13232112/15566609/9511058c-233f-11e6-853f-cc3e22688e8c.png)

**Comment by saikrishna321** [comment]
@Pushpank you should ask this on discuss.appium.io, this place is meant only for issues.

**Comment by saikrishna321** [comment]
@triager please close

**Comment by SrinivasanTarget** [comment]
@triager please close
