### ISSUE TITLE
Error converting element ID for using in WD atoms: undefined (WebDriver\Exception\UnknownEr ror)

### ISSUE THREAD

**Issue by dsgdevfront** [appium/appium#6534]
Getting this error when running automation tests on real iOS devices

An unknown server-side error occurred while processing the command. Original error: Error converting element ID for using in WD atoms: undefined (WebDriver\Exception\UnknownEr
ror)

Running Appium on mac os machine with the devices connected to it
got the selinum tests on remote desktop

Tests should run on Safari browser

Run fine on Adroid devices so the issue is iOS specific

any help will be appreciated

Using last version of node.js
appium 
xCode
etc

thanks

**Comment by DavidFrahm** [comment]
Same here as best I can tell.

I got to this point because browser.click() fails silently (selector seems to find an element, but click does nothing and also not not throw an error).  So I was trying browser.touch(selector) and got this:

Failed: An unknown server-side error occurred while processing the command. Original error: Error converting element ID for using in WD atoms: 5342

I'm using appium 1.5.3 and webdriverio 4.0.9.

**Comment by imurchie** [comment]
Can you provide more of the logs?

**Comment by DavidFrahm** [comment]
Here are the appium and webdriverio logs. If you need anything else let me know.

[appium-console-20160616-0910.txt](https://github.com/appium/appium/files/318576/appium-console-20160616-0910.txt)
[wdio-console-20160616-0910.txt](https://github.com/appium/appium/files/318577/wdio-console-20160616-0910.txt)

**Comment by christian-bromann** [comment]
@DavidFrahm your issue doesn't look Appium related. It looks like an Jasmine issue:
```
TypeError: Cannot read property 'addExpectationResult' of undefined
    at Env.fail (/Users/david/Projects/es-mono/app/es-admin/node_modules/wdio-jasmine-framework/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:894:24)
```
Can you file an issue in the WebdriverIO project with more details information? Thanks!

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by SrinivasanTarget** [comment]
Not related to Appium as per above comments. hence closing this.
