### ISSUE TITLE
Instruments Crashed on startup error, While I try to launch ipa on iOS Device

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#6535]
## The problem

Instruments Crashed on startup error, While I try to launch iPA on iOS Device
## Environment
- 1.4.13
- Last Appium version that did not exhibit the issue (if applicable):
- EL Captain
- using Appium.app
- iOS 9.3
- Real device iphone 6
-  Appium.app
## Details

Instruments Crashed on startup error, While I try to launch iPA on iOS Device. Appium tries multiple times and then fails.
**Works fine though If I install the App using iTunes first and then try launching using Automation.**

**Comment by imurchie** [comment]
Is the app downloaded from iTunes? For Appium to work the app needs to be signed with a developer identity, so it won't work downloaded from iTunes. This is an Apple requirement.

See https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices.md#appium-on-real-ios-devices

**Comment by VenkateshPS** [comment]
No the App is not downloaded from iTunes, and yes it is signed with developer identity.

**Comment by imurchie** [comment]
Can you provide the full Appium server logs (as a [gist](https://gist.github.com/)), then? There is no way to have any ideas otherwise.

**Comment by VenkateshPS** [comment]
https://gist.github.com/VenkateshPS/0e76d07724c9c64778436c59085b0888

**Comment by mykola-mokhnach** [comment]
Try the most recent Appium version. If this does not work as well then try to manually extract .app package from ipa and install it using libimobiledevice, to make sure the package is properly signed (see 
```bash
ideviceinstaller --help
```)
for more details.

**Comment by VenkateshPS** [comment]
I tried on Appium 1.5.2, and getting the same error.

**Comment by VenkateshPS** [comment]
also installation was successful when i tried ideviceinstaller -i XXXX.ipa

**Comment by mykola-mokhnach** [comment]
try to unpack .app from .ipa and provide the path to .app instead of .ipa. Probably, this might change something
