### ISSUE TITLE
sendKeys passing wrong value to EditText

### ISSUE THREAD

**Issue by esh0** [appium/appium#6536]
## The problem

Hello, we're facing some issues with Appium. There is a simple script to test activity which contains:
- 4 edittext's
- 1 check button
- 1 label
## Environment
- Appium version 1.4.16.1
- Windows 7
- Android 6.0.1 on Nexus 5 real device, Android 5.0 on Nexus 5 emualtor (Genymotion)
## Details

At first we pass four numbers (1, 2, 3, 4), one to each edittext. Then we click on check button and check if label is visible. Then we pass another four numbers (4, 4, 8, 8), click check button and check label visibility. The problem is on the second pass - the first number is entered as (1), not (4). This reproduces both on real device and emulator. Also tested using MAC and there issue still reproduces. What can be important - editText has feature that after a text is entered it's switching focus to next edit text (unless it's the last one).

What we tried:
- adding element.click before sendKeys - didn't help
- looping sendKeys until first edit text will have value (4) - never, always wrong value (1)

In the appium log we can see that it's searching for correct view id (code1) and passing correct value (4), but on device it's entering (1).
## Link to Appium logs

https://gist.github.com/esh0/f1caae20158aafa9e7789f6c8c3a6e5e
## Code To Reproduce Issue

https://gist.github.com/esh0/5ab51f9ac2780bc9bb001adb76653c39
https://gist.github.com/esh0/10492e357fc2d145788654b0e388d27f
https://drive.google.com/file/d/0B58HwcKVCJnEekZ1bDZBVGlfWW8/view

Thanks for looking into that issue.

**Comment by jlipps** [comment]
Sorry for the delay here, @esh0. Can you try again with the latest version of Appium (and you might also consider trying with the UiAutomator2 automation backend)
