### ISSUE TITLE
Failed to start an Appium session, err was: Error: Installing com.google.duet.Duet failed

### ISSUE THREAD

**Issue by aravindkirish** [appium/appium#6543]
Hi,
      I was facing this issue. I am trying to automate ios application using appium.

I have written the following code.
DesiredCapabilities capabilities = new DesiredCapabilities(); 
	        capabilities.setCapability("platformName", "ios");
	        capabilities.setCapability("deviceName","iOS");
	        capabilities.setCapability("udid", "54047d45e26daf87xxxxx0d689fdff31610cc0");
	        capabilities.setCapability("app","com.google.duet.Duet");

	        driver = new RemoteWebDriver( new URL( "http://192.168.13.93:4723/wd/hub" ), capabilities );

## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Capabilities seems to be assigned incorrectly. Please read
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md

**Comment by imurchie** [comment]
The `app` desired capability should not be the bundle id. If the app is already installed on the device, leave `app` blank and use `bundleId` with `com.krimston.duet.Duet`.

See `bundleId` under https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md#ios-only

**Comment by aravindkirish** [comment]
Thanks a lot for your reply. Its now working.

On Tue, May 31, 2016 at 8:34 PM, Isaac A. Murchie <notifications@github.com>
wrote:

> The app desired capability should not be the bundle id. If the app is
> already installed on the device, leave app blank and use bundleId with
> com.krimston.duet.Duet.
>
> See bundleId under
> https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md#ios-only
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/appium/appium/issues/6543#issuecomment-222717049>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ASwD8B1vAdSisQUVBK7uIeXLTL8qmkZjks5qHE3lgaJpZM4IqS2U>
> .
>



-- 
*With regards *
*ARAVINDKUMAR*

**Comment by imurchie** [comment]
Excellent!
