### ISSUE TITLE
Appium mobile: scroll not working on Java client 4.0.0  and appium 1.5.2

### ISSUE THREAD

**Issue by zaidkazi** [appium/appium#6545]
Hey guys after updating to java client 4.0.0 and Appium version 1.5.2 this no longer works.

`JavascriptExecutor js = (JavascriptExecutor) this.getIOSDriver();
                HashMap<String, String> scrollObject = new HashMap<String, String>();
                scrollObject.put("direction", "up");
                scrollObject.put("element", ((RemoteWebElement) element).getId());
                js.executeScript("mobile: scroll", scrollObject);`

I get a error as the following on the execute step.

> org.openqa.selenium.WebDriverException: Unexpected error in -[UIATableCell_0x7fa0d2b4ec10 scrollUp], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIAutomation_Sim/UIAutomation-449.2/Framework/UIAElement.m line 1473, kAXErrorSuccess (WARNING: The server did not provide any stacktrace information)
> Command duration or timeout: 941 milliseconds
> Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
> System info: host: 'MacBook-Pro-3.local', ip: '10.93.90.89', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_60'
> Driver info: io.appium.java_client.ios.IOSDriver
> Capabilities [{app=/Users/tempautomation/Desktop/emulatedappfile/sapporo.ipa, networkConnectionEnabled=false, noReset=true, bundleId=com.temp.sapporo3, keepKeyChains=false, databaseEnabled=false, deviceName=iPhone 6, launchTimeout=150000, fullReset=false, platform=MAC, desired={app=/Users/tempautomation/Desktop/emulatedappfile/sapporo.ipa, noReset=true, newCommandTimeout=120, platformVersion=9.3, bundleId=com.zaid.com, browserName=, waitForAppScript=true;, keepKeyChains=false, platformName=iOS, deviceName=iPhone 6, launchTimeout=150000, fullReset=false}, newCommandTimeout=120, platformVersion=9.3, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, waitForAppScript=true;, javascriptEnabled=true, platformName=iOS}]
> Session ID: f8e3e73b-5fc4-4063-ab03-302df16d007c

**Comment by imurchie** [comment]
The `kAXErrorSuccess` usually means that the scroll has moved past the end of the view. Is there any scrolling happening?

**Comment by zaidkazi** [comment]
No scrolling at all

**Comment by imurchie** [comment]
IS there room for it to scroll?

**Comment by zaidkazi** [comment]
What do u mean by that umm the screen is pretty much a table view and the element that I am finding is a table cell located at around position or index 40 of the table View and the screen starts off at the top and there is about 7 to 8 table cells at any given time so it needs to scroll by a couple times to reach to the end of the page but there is no movement

**Comment by imurchie** [comment]
Ok.

Can you provide the server logs so we can look into the problem?

**Comment by zaidkazi** [comment]
sure 

Server log of last few steps prior to scroll and the final stack trace

> [debug] [iOS] Executing iOS command 'elementDisplayed'
[debug] [UIAuto] Sending command to instruments: au.getElement('35').isDisplayed()
[debug] [Instruments] [INST] 2016-06-01 00:46:16 +0000 Debug: Got new command 114 from instruments: au.getElement('35').isDisplayed()
[debug] [Instruments] [INST] 2016-06-01 00:46:16 +0000 Debug: evaluating au.getElement('35').isDisplayed()
[debug] [Instruments] [INST] 2016-06-01 00:46:16 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-06-01 00:46:16 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-06-01 00:46:16 +0000 Debug: Running system command #115: /usr/local/Cellar/node/6.0.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/3l/yrzdgw8d7z90ng4m0xq74ldw0000gn/T/instruments_sock 2,{"status":0,"value":false}...
[debug] [UIAuto] Socket data received (28 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":false}
[MJSONWP] Responding to client with driver.elementDisplayed() result: false
[HTTP] <-- GET /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element/35/displayed 200 1040 ms - 77 
31/05/2016 20:46:16 [INFO ] AccountsOverview - Waiting to appear using locator - By.id: accounts_list
[HTTP] --> POST /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element {"using":"id","value":"accounts_list"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","accounts_list","1514149d-91ad-44b3-847f-75e003fdf147"]
[debug] [iOS] Executing iOS command 'findElement'
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [UIAuto] Sending command to instruments: au.getElementByAccessibilityId('accounts_list')
[debug] [Instruments] [INST] 2016-06-01 00:46:17 +0000 Debug: Got new command 115 from instruments: au.getElementByAccessibilityId('accounts_list')
[debug] [Instruments] [INST] 2016-06-01 00:46:17 +0000 Debug: evaluating au.getElementByAccessibilityId('accounts_list')
[debug] [Instruments] [INST] 2016-06-01 00:46:17 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-06-01 00:46:17 +0000 Debug: Lookup returned [object UIATableView] with the name "accounts_list" (id: 36).
[debug] [Instruments] [INST] 2016-06-01 00:46:17 +0000 Debug: responding with:
[debug] [UIAuto] Socket data received (39 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"ELEMENT":"36"}}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"36"}
[HTTP] <-- POST /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element 200 1060 ms - 88 
[debug] [Instruments] [INST] 2016-06-01 00:46:17 +0000 Debug: Running system command #116: /usr/local/Cellar/node/6.0.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/3l/yrzdgw8d7z90ng4m0xq74ldw0000gn/T/instruments_sock 2,{"status":0,"value":{"ELEMENT":"36"}}...
[HTTP] --> GET /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element/36/displayed {}
[MJSONWP] Calling AppiumDriver.elementDisplayed() with args: ["36","1514149d-91ad-44b3-847f-75e003fdf147"]
[debug] [iOS] Executing iOS command 'elementDisplayed'
[debug] [UIAuto] Sending command to instruments: au.getElement('36').isDisplayed()
[debug] [Instruments] [INST] 2016-06-01 00:46:18 +0000 Debug: Got new command 116 from instruments: au.getElement('36').isDisplayed()
[debug] [Instruments] [INST] 2016-06-01 00:46:18 +0000 Debug: evaluating au.getElement('36').isDisplayed()
[debug] [Instruments] [INST] 2016-06-01 00:46:18 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-06-01 00:46:18 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-06-01 00:46:18 +0000 Debug: Running system command #117: /usr/local/Cellar/node/6.0.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/3l/yrzdgw8d7z90ng4m0xq74ldw0000gn/T/instruments_sock 2,{"status":0,"value":true}...
[debug] [UIAuto] Socket data received (27 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":true}
[MJSONWP] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element/36/displayed 200 938 ms - 76 
31/05/2016 20:46:18 [INFO ] AccountsOverview - The page has appeared.
[HTTP] --> POST /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element {"using":"id","value":"loading"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","loading","1514149d-91ad-44b3-847f-75e003fdf147"]
[debug] [iOS] Executing iOS command 'findElement'
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [UIAuto] Sending command to instruments: au.getElementByAccessibilityId('loading')
[debug] [Instruments] [INST] 2016-06-01 00:46:19 +0000 Debug: Got new command 117 from instruments: au.getElementByAccessibilityId('loading')
[debug] [Instruments] [INST] 2016-06-01 00:46:19 +0000 Debug: evaluating au.getElementByAccessibilityId('loading')
[debug] [Instruments] [INST] 2016-06-01 00:46:20 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-06-01 00:46:20 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-06-01 00:46:20 +0000 Debug: Running system command #118: /usr/local/Cellar/node/6.0.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/3l/yrzdgw8d7z90ng4m0xq74ldw0000gn/T/instruments_sock 2,{"status":0,"value":""}...
[debug] [UIAuto] Socket data received (25 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
[debug] [UIAuto] Sending command to instruments: au.getElementById('loading')
[debug] [Instruments] [INST] 2016-06-01 00:46:21 +0000 Debug: Got new command 118 from instruments: au.getElementById('loading')
[debug] [Instruments] [INST] 2016-06-01 00:46:21 +0000 Debug: evaluating au.getElementById('loading')
[debug] [Instruments] [INST] 2016-06-01 00:46:24 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-06-01 00:46:24 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-06-01 00:46:24 +0000 Debug: Running system command #119: /usr/local/Cellar/node/6.0.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/3l/yrzdgw8d7z90ng4m0xq74ldw0000gn/T/instruments_sock 2,{"status":0,"value":""}...
[debug] [UIAuto] Socket data received (25 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
31/05/2016 20:46:24 [INFO ] AccountsOverview - Waiting to appear using locator - By.id: accounts_list
[HTTP] <-- POST /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element 500 5560 ms - 164 
[HTTP] --> POST /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element {"using":"id","value":"accounts_list"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","accounts_list","1514149d-91ad-44b3-847f-75e003fdf147"]
[debug] [iOS] Executing iOS command 'findElement'
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [UIAuto] Sending command to instruments: au.getElementByAccessibilityId('accounts_list')
[debug] [Instruments] [INST] 2016-06-01 00:46:25 +0000 Debug: Got new command 119 from instruments: au.getElementByAccessibilityId('accounts_list')
[debug] [Instruments] [INST] 2016-06-01 00:46:25 +0000 Debug: evaluating au.getElementByAccessibilityId('accounts_list')
[debug] [Instruments] [INST] 2016-06-01 00:46:25 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-06-01 00:46:25 +0000 Debug: Lookup returned [object UIATableView] with the name "accounts_list" (id: 37).
[debug] [Instruments] [INST] 2016-06-01 00:46:25 +0000 Debug: responding with:
[debug] [UIAuto] Socket data received (39 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"ELEMENT":"37"}}
[debug] [Instruments] [INST] 2016-06-01 00:46:25 +0000 Debug: Running system command #120: /usr/local/Cellar/node/6.0.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/3l/yrzdgw8d7z90ng4m0xq74ldw0000gn/T/instruments_sock 2,{"status":0,"value":{"ELEMENT":"37"}}...
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"37"}
[HTTP] <-- POST /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element 200 1068 ms - 88 
[HTTP] --> GET /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element/37/displayed {}
[MJSONWP] Calling AppiumDriver.elementDisplayed() with args: ["37","1514149d-91ad-44b3-847f-75e003fdf147"]
[debug] [iOS] Executing iOS command 'elementDisplayed'
[debug] [UIAuto] Sending command to instruments: au.getElement('37').isDisplayed()
[debug] [Instruments] [INST] 2016-06-01 00:46:26 +0000 Debug: Got new command 120 from instruments: au.getElement('37').isDisplayed()
[debug] [Instruments] [INST] 2016-06-01 00:46:26 +0000 Debug: evaluating au.getElement('37').isDisplayed()
[debug] [Instruments] [INST] 2016-06-01 00:46:26 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-06-01 00:46:26 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-06-01 00:46:26 +0000 Debug: Running system command #121: /usr/local/Cellar/node/6.0.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/3l/yrzdgw8d7z90ng4m0xq74ldw0000gn/T/instruments_sock 2,{"status":0,"value":true}...
[debug] [UIAuto] Socket data received (27 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":true}
[MJSONWP] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element/37/displayed 200 921 ms - 76 
31/05/2016 20:46:26 [INFO ] AccountsOverview - The page has appeared.
[HTTP] --> POST /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element {"using":"-ios uiautomation","value":".tableViews()[0].cells().firstWithPredicate(\"ANY staticTexts.label == 'Account Number: (00002-10404797-001)' \")"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["-ios uiautomation",".tableViews()[0].cells().firstWithPredicate(\"ANY staticTexts.label == 'Account Number: (00002-10404797-001)' \")","1514149d-...
[debug] [iOS] Executing iOS command 'findElement'
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [UIAuto] Sending command to instruments: au.getElementByUIAutomation('.tableViews()[0].cells().firstWithPredicate(\"ANY staticTexts.label == \'Account Number: (00002-10404797-001)\' \")')
[debug] [Instruments] [INST] 2016-06-01 00:46:27 +0000 Debug: Got new command 121 from instruments: au.getElementByUIAutomation('.tableViews()[0].cells().firstWithPredicate(\"ANY staticTexts.label == \'Account Number: (00002-10404797-001)\' \")')
[debug] [Instruments] [INST] 2016-06-01 00:46:27 +0000 Debug: evaluating au.getElementByUIAutomation('.tableViews()[0].cells().firstWithPredicate(\"ANY staticTexts.label == \'Account Number: (00002-10404797-001)\' \")')
[debug] [Instruments] [INST] 2016-06-01 00:46:27 +0000 Debug: byUIAutomation: evaluating code: $.mainWindow().tableViews()[0].cells().firstWithPredicate("ANY staticTexts.label == 'Account Number: (00002-10404797-001)' ")
[debug] [Instruments] [INST] 2016-06-01 00:46:27 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-06-01 00:46:27 +0000 Debug: Lookup returned [object UIATableCell] with the name "account_row" (id: 38).
[debug] [UIAuto] Socket data received (39 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"ELEMENT":"38"}}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"38"}
[HTTP] <-- POST /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element 200 1077 ms - 88 
[debug] [Instruments] [INST] 2016-06-01 00:46:27 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-06-01 00:46:27 +0000 Debug: Running system command #122: /usr/local/Cellar/node/6.0.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/3l/yrzdgw8d7z90ng4m0xq74ldw0000gn/T/instruments_sock 2,{"status":0,"value":{"ELEMENT":"38"}}...
[HTTP] --> POST /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/execute {"script":"function getElement() {return target.frontMostApp().mainWindow().contentArea();};getElement();","args":[""]}
[MJSONWP] Calling AppiumDriver.execute() with args: ["function getElement() {return target.frontMostApp().mainWindow().contentArea();};getElement();",[""],"1514149d-91ad-44b3-847f-75e003fdf147"]
[debug] [iOS] Executing iOS command 'execute'
[debug] [UIAuto] Sending command to instruments: function getElement() {return target.frontMostApp().mainWindow().contentArea();};getElement();
[debug] [Instruments] [INST] 2016-06-01 00:46:45 +0000 Debug: Got new command 122 from instruments: function getElement() {return target.frontMostApp().mainWindow().contentArea();};getElement();
[debug] [Instruments] [INST] 2016-06-01 00:46:45 +0000 Debug: evaluating function getElement() {return target.frontMostApp().mainWindow().contentArea();};getElement();
[debug] [Instruments] [INST] 2016-06-01 00:46:45 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-06-01 00:46:45 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-06-01 00:46:45 +0000 Debug: Running system command #123: /usr/local/Cellar/node/6.0.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/3l/yrzdgw8d7z90ng4m0xq74ldw0000gn/T/instruments_sock 2,{"status":0,"value":{"origin":{"x":0,"y":64},"size":{"width":37...
[debug] [UIAuto] Socket data received (82 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"origin":{"x":0,"y":64},"size":{"width":375,"height":603}}}
[MJSONWP] Responding to client with driver.execute() result: {"origin":{"x":0,"y":64},"size":{"width":375,"height":603}}
[HTTP] <-- POST /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/execute 200 684 ms - 131 
[HTTP] --> GET /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element/38/location {}
[MJSONWP] Calling AppiumDriver.getLocation() with args: ["38","1514149d-91ad-44b3-847f-75e003fdf147"]
[debug] [iOS] Executing iOS command 'getLocation'
[debug] [UIAuto] Sending command to instruments: au.getElement('38').getElementLocation()
[debug] [Instruments] [INST] 2016-06-01 00:46:46 +0000 Debug: Got new command 123 from instruments: au.getElement('38').getElementLocation()
[debug] [Instruments] [INST] 2016-06-01 00:46:46 +0000 Debug: evaluating au.getElement('38').getElementLocation()
[debug] [Instruments] [INST] 2016-06-01 00:46:46 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-06-01 00:46:46 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-06-01 00:46:46 +0000 Debug: Running system command #124: /usr/local/Cellar/node/6.0.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/3l/yrzdgw8d7z90ng4m0xq74ldw0000gn/T/instruments_sock 2,{"status":0,"value":{"x":0,"y":7877}}...
[debug] [UIAuto] Socket data received (39 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"x":0,"y":7877}}
[MJSONWP] Responding to client with driver.getLocation() result: {"x":0,"y":7877}
[HTTP] <-- GET /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element/38/location 200 971 ms - 88 
[HTTP] --> GET /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element/38/displayed {}
[MJSONWP] Calling AppiumDriver.elementDisplayed() with args: ["38","1514149d-91ad-44b3-847f-75e003fdf147"]
[debug] [iOS] Executing iOS command 'elementDisplayed'
[debug] [UIAuto] Sending command to instruments: au.getElement('38').isDisplayed()
[debug] [Instruments] [INST] 2016-06-01 00:46:47 +0000 Debug: Got new command 124 from instruments: au.getElement('38').isDisplayed()
[debug] [Instruments] [INST] 2016-06-01 00:46:47 +0000 Debug: evaluating au.getElement('38').isDisplayed()
[debug] [Instruments] [INST] 2016-06-01 00:46:47 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-06-01 00:46:47 +0000 Debug: responding with:
[debug] [UIAuto] Socket data received (28 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":false}
[MJSONWP] Responding to client with driver.elementDisplayed() result: false
[HTTP] <-- GET /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/element/38/displayed 200 1053 ms - 77 
[debug] [Instruments] [INST] 2016-06-01 00:46:47 +0000 Debug: Running system command #125: /usr/local/Cellar/node/6.0.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/3l/yrzdgw8d7z90ng4m0xq74ldw0000gn/T/instruments_sock 2,{"status":0,"value":false}...
[HTTP] --> POST /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/execute {"script":"mobile: scroll","args":[{"direction":"up","element":"38"}]}
[MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: scroll",[{"direction":"up","element":"38"}],"1514149d-91ad-44b3-847f-75e003fdf147"]
[debug] [iOS] Executing iOS command 'execute'
[debug] [UIAuto] Sending command to instruments: au.getElement('38').scrollUp()
[debug] [Instruments] [INST] 2016-06-01 00:46:52 +0000 Debug: Got new command 125 from instruments: au.getElement('38').scrollUp()
[debug] [Instruments] [INST] 2016-06-01 00:46:52 +0000 Debug: evaluating au.getElement('38').scrollUp()
[debug] [Instruments] [INST] 2016-06-01 00:46:52 +0000 Debug: target.frontMostApp().mainWindow().tableViews()[0].cells().firstWithPredicate("ANY staticTexts.label == 'Account Number: (00002-10404797-001)' ").scrollUp()
[debug] [Instruments] [INST] 2016-06-01 00:46:52 +0000 Debug: Unexpected error in -[UIATableCell_0x7f90932bf020 scrollUp], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIAutomation_Sim/UIAutomation-449.2/Framework/UIAElement.m line 1473, kAXErrorFailure
[debug] [UIAuto] Socket data received (220 bytes)
[debug] [UIAuto] Got result from instruments: {"status":17,"value":"Unexpected error in -[UIATableCell_0x7f90932bf020 scrollUp], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIAutomation_Sim/UIAutomation-449.2/Framework/UIAElement.m line 1473, kAXErrorFailure"}
[HTTP] <-- POST /wd/hub/session/1514149d-91ad-44b3-847f-75e003fdf147/execute 500 513 ms - 281 
[debug] [Instruments] [INST] 2016-06-01 00:46:52 +0000 Error: VerboseError: Unexpected error in -[UIATableCell_0x7f90932bf020 scrollUp], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIAutomation_Sim/UIAutomation-449.2/Framework/UIAElement.m line 1473, kAXErrorFailure
[debug] [Instruments] [INST] 2016-06-01 00:46:52 +0000 Error: Error during eval: scrollUp@[native code]
       eval code
eval@[native code]
startProcessing@file:///Users/tempautomation/appium-tests/16BDE77C-46D6-463A-AF56-5759E0EDA0FA/bootstrap-c1ef4636f82d359b.js:2793:30
bootstrap@file:///Users/tempautomation/appium-tests/16BDE77C-46D6-463A-AF56-5759E0EDA0FA/bootstrap-c1ef4636f82d359b.js:2861:31
global code@file:///Users/tempautomation/appium-tests/16BDE77C-46D6-463A-AF56-5759E0EDA0FA/bootstrap-c1ef4636f82d359b.js:2870:10
[debug] [Instruments] [INST] 2016-06-01 00:46:52 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-06-01 00:46:52 +0000 Debug: Running system command #126: /usr/local/Cellar/node/6.0.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/3l/yrzdgw8d7z90ng4m0xq74ldw0000gn/T/instruments_sock 2,{"status":17,"value":"Unexpected error in -[UIATableCell_0x7f90...

org.openqa.selenium.WebDriverException: Unexpected error in -[UIATableCell_0x7f90932bf020 scrollUp], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIAutomation_Sim/UIAutomation-449.2/Framework/UIAElement.m line 1473, kAXErrorFailure (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 525 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'MacBook-Pro-3.local', ip: '192.168.1.47', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_60'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/tempautomation/Desktop/emulatedappfile/temp.ipa, networkConnectionEnabled=false, noReset=true, bundleId=com.temp.temp3, keepKeyChains=false, databaseEnabled=false, deviceName=iPhone 6, launchTimeout=150000, fullReset=false, platform=MAC, desired={app=/Users/tempautomation/Desktop/emulatedappfile/temp.ipa, noReset=true, newCommandTimeout=120, platformVersion=9.3, bundleId=com.temp.temp3, browserName=, waitForAppScript=true;, keepKeyChains=false, platformName=iOS, deviceName=iPhone 6, launchTimeout=150000, fullReset=false}, newCommandTimeout=120, platformVersion=9.3, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, waitForAppScript=true;, javascriptEnabled=true, platformName=iOS}]
Session ID: 1514149d-91ad-44b3-847f-75e003fdf147

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:51)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
	at com.temp.bu.mobile.temp.pageobject.BasetempPage.scrollByElementAndClick(BasetempPage.java:287)
	at com.temp.bu.mobile.temp.pageobject.accounts.AccountsOverview.selectAccountByNumber(AccountsOverview.java:217)
	at com.temp.bu.mobile.temp.functional.CreditLineFunctionalTest.creditLineInterestOnlyDisplayDetails_229161(CreditLineFunctionalTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:122)

**Comment by imurchie** [comment]
If the screen is at the top and your element is below, why are you trying to up?

Also, I don't think you want to scroll with the element, if I'm reading the commands right. Element `38` the element you want to find, but you are trying to scroll within it.

```
{"script":"mobile: scroll","args":[{"direction":"up","element":"38"}]}
```

I think you want to scroll `"down"` with no element.

**Comment by shay777** [comment]
i have the same issue using java
after i updated the java client to 1.5.2 the swipe is not working only on ios
it ignored
any idea what is going on?

**Comment by SrinivasanTarget** [comment]
@shay777 Don't mix it up.Your issue is irrelevant here.Have a look at https://github.com/appium/java-client/issues/350 to succeed in swipe. If you still find issues in swipe, raise it seperately with appium logs inform of gist to look further.

**Comment by SrinivasanTarget** [comment]
@triager please close. Closing this as i dont see any updates post that. Assuming everything looks fine.
