### ISSUE TITLE
Retrieving the device id or UDID

### ISSUE THREAD

**Issue by email2vimalraj** [appium/appium#6550]
## The problem

During my test execution, I wanted to execute few **adb** commands which appium doesn't provide out of the box. For example, I would like to retrieve the model name of the device, filter the logcat by tag names and so on. So I use **System** command to execute the required adb commands and get the required output. This works well enough if I have single device connected, since adb doesn't expect the **-s** parameter with the device id.

However, if I have multiple devices connected to my machine, appium takes any one of the device if I don't pass UDID and executes on it. The **deviceName** capability in my test is set to **Android**. I would like to retrieve the device id on which appium is running.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOSX El Captain
* Node.js version (unless using Appium.app|exe): v6.0.0
* Mobile platform/version under test: Android M / Android L
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

I believe my problem statement itself in very detail. Let me know in case more details required.

## Code To Reproduce Issue [ Good To Have ]

adb command with device id argument.

**Comment by mykola-mokhnach** [comment]
As far as I know there will be Appium interface for ADB, but only since Appium 2.0
As a workaround you can parse the log generated by Appium server to extract the device id. The corresponding log record looks like 
```
Using device: ${udid}
```
Make sure your minimum logging level is set to 'info' or less

**Comment by imurchie** [comment]
I like this idea. I've made a PR to add it to the session information.

**Comment by imurchie** [comment]
Just realized this is unnecessary. Can you look at the return value from starting a session? Is there no indication in there of the device you are actually running against?

**Comment by email2vimalraj** [comment]
As a workaround, this is what I've done. 

- I get the session id using driver.getSessionId()
- Then I frame a url: http://appium host:appium port/wd/hub/session/sessionId
- Hit the above url using any rest client libraries as a GET method. I use Apache HttpClient library.
- Then I retrieve the key called "value.deviceName" form the response body which contains the actual device id irrespective of my capability or UDID.

This now solved my problem. However I feel there should be a way by which appium can expose the device id to the user. For example, using java-client library, I should be able to use driver.getDeviceId().

Thanks
Vimalraj

**Comment by saikrishna321** [comment]
@email2vimalraj i'm able to get the deviceUDID by the below command 
```
((AndroidDriver)getDriver()).capabilities.asMap().get("deviceName")

```
@imurchie thoughts?

**Comment by email2vimalraj** [comment]
@saikrishna321 : For me it returns **Android**, since in my capability I've set the **deviceName** capability to **Android**.

**Comment by saikrishna321** [comment]
@email2vimalraj i do it this way, java_client 4.0.0

```
 DesiredCapabilities androidCapabilities = new DesiredCapabilities();
        androidCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android");
        androidCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "5.X");
        androidCapabilities.setCapability("browserName", "");     
        androidCapabilities
            .setCapability(MobileCapabilityType.APP, prop.getProperty("ANDROID_APP_PATH"));
        androidCapabilities.setCapability(MobileCapabilityType.UDID, device_udid);
```

**Comment by email2vimalraj** [comment]
Okay I see you are setting the capability called UDID which actually sets the deviceName also. In my case I don't set the UDID cap. 

Thanks
Vimalraj

**Comment by saikrishna321** [comment]
@email2vimalraj ah i get what ur saying .... @imurchie no return values from the session start does not hold anything, only we hit the session/sessionID we get the details 

```
{"status":0,"value":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"/Users/saikrisv/git/sample-code/sample-code/examples/java/junit/../../../apps/ApiDemos/bin/ApiDemos-debug.apk","appPackage":"io.appium.android.apis","appActivity":".ApiDemos","platformName":"Android","deviceName":"Android Emulator","platformVersion":"4.4"},"app":"/Users/saikrisv/git/sample-code/sample-code/examples/java/junit/../../../apps/ApiDemos/bin/ApiDemos-debug.apk","appPackage":"io.appium.android.apis","appActivity":".ApiDemos","platformName":"Android","deviceName":"192.168.65.101:5555","platformVersion":"5.0"},"sessionId":"5790524a-2f42-4727-ab31-874f9c37edcc"}
```

**Comment by imurchie** [comment]
I've updated the `appium-android-driver` to include `deviceUDID` in the returned capabilities.

**Comment by saikrishna321** [comment]
@imurchie /sessions/ gives the details as follows which holds the deviceName 

***[{capabilities={app=/Users/saikrisv/git/java-client/java-client/src/test/java/io/appium/java_client/IntentExample.apk, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=192.168.65.101:5555, platform=LINUX, desired={app=/Users/saikrisv/git/java-client/java-client/src/test/java/io/appium/java_client/IntentExample.apk, platformName=Android, deviceName=Android Emulator}, platformVersion=5.0, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, javascriptEnabled=true, platformName=Android}, id=5ac5c0ee-e748-429e-ac62-c2916bd3a349}]

So which means we need to get this written on the client side ... Do we still need to have this on appium-android-driver?

**Comment by imurchie** [comment]
This is retrieved from `appium-android-driver`. I'm not sure what you mean.

**Comment by saikrishna321** [comment]
https://github.com/appium/node-mobile-json-wire-protocol/blob/master/lib/routes.js#L15 

Implementing this end point on the client side returns the above response as i posted .. Am i making sense now ?

**Comment by imurchie** [comment]
Is that method not implemented in all the client libraries? 

For a particular session, https://github.com/appium/node-mobile-json-wire-protocol/blob/master/lib/routes.js#L17 will also return the same information, but for a single session.

My change to the android driver simply adds the udid to the information, as `deviceUDID`.

**Comment by SrinivasanTarget** [comment]
No @imurchie We have this as feature request in java-client here: https://github.com/appium/java-client/issues/215

**Comment by saikrishna321** [comment]
@SrinivasanTarget thanks for pointing out...

**Comment by SrinivasanTarget** [comment]
@imurchie Do we have deviceUDID info in iOSDriver session already?

**Comment by imurchie** [comment]
Does the Java client support getting a single session?

**Comment by SrinivasanTarget** [comment]
No @imurchie We will add that to feature request.

**Comment by imurchie** [comment]
Alright. Whatever the case, the information is returned from starting a session.

**Comment by SrinivasanTarget** [comment]
Thanks! @imurchie I will add the endpoints in java-client soon :)

**Comment by SrinivasanTarget** [comment]
@triager please label: Enhancement

**Comment by SrinivasanTarget** [comment]
@triager please close
