### ISSUE TITLE
Appium installation error

### ISSUE THREAD

**Issue by rajabhaskar** [appium/appium#6555]
## The problem

I'm getting the below error when tried to install the appium using npm. I have set my java path as "JAVA_HOME: C:\Program Files\Java\jre1.8.0_77", path: %JAVA_HOME%\bin". even though I am getting the same error as specified below. 

## Environment

* npm -version -3.9.3
* java version "1.8.0_77"
  Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
  Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
* node --version: v6.2.1

##Error log:
C:\Users\xxxx>npm install -g appium

appium-chromedriver@2.8.0 install C:\Users\xxxx\AppData\Roaming\npm\node_mo
dules\appium\node_modules\appium-chromedriver
node install-npm.js
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
Error trying to install Chromedriver binary. Waiting and trying again.
info Chromedriver Install Installing Chromedriver version '2.21' for platform 'w
in' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com
/2.21/chromedriver_win32.zip...
info Chromedriver Install Writing binary content to C:\Users\xxxx\AppData\Loc
al\Temp\201653-18828-12btz6u\chromedriver_win32.zip...
info Chromedriver Install Extracting C:\Users\xxxx\AppData\Local\Temp\201653-
18828-12btz6u\chromedriver_win32.zip to C:\Users\xxxx\AppData\Local\Temp\2016
53-18828-12btz6u\chromedriver_win32
info Chromedriver Install Creating C:\Users\xxxx\AppData\Roaming\npm\node_mod
ules\appium\node_modules\appium-chromedriver\chromedriver\win...
info Chromedriver Install Copying unzipped binary, reading from C:\Users\xxxx
\AppData\Local\Temp\201653-18828-12btz6u\chromedriver_win32\chromedriver.exe...
info Chromedriver Install Writing to C:\Users\xxxx\AppData\Roaming\npm\node_m
odules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
...
info Chromedriver Install C:\Users\xxxx\AppData\Roaming\npm\node_modules\appi
um\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe successful
ly put in place

appium-selendroid-driver@1.2.2 install C:\Users\xxxx\AppData\Roaming\npm\no
de_modules\appium\node_modules\appium-selendroid-driver
node ./bin/install.js
info SelendroidInstaller Ensuring C:\Users\xxxx\AppData\Roaming\npm\node_modu
les\appium\node_modules\appium-selendroid-installer\selendroid\download exists
info SelendroidInstaller Downloading Selendroid standalone server version 0.17.0
from https://github.com/selendroid/selendroid/releases/download/0.17.0/selendro
id-standalone-0.17.0-with-dependencies.jar --> C:\Users\xxxx\AppData\Roaming\
npm\node_modules\appium\node_modules\appium-selendroid-installer\selendroid\down
load\selendroid-server.jar
info SelendroidInstaller Writing binary content to C:\Users\xxxx\AppData\Roam
ing\npm\node_modules\appium\node_modules\appium-selendroid-installer\selendroid\
download\selendroid-server.jar
info SelendroidInstaller Selendroid standalone server downloaded
info SelendroidInstaller Determining AndroidManifest location
**Error: Command 'jar tf C:\Users\xxxx\AppData\Roaming\npm\node_modules\
appium\node_modules\appium-selendroid-installer\selendroid\download\selendr
oid-server.jar' errored out: Error: spawn jar ENOENT**
at exports._errnoException (util.js:870:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
at onErrorNT (internal/child_process.js:344:16)
at nextTickCallbackWith2Args (node.js:442:9)
at process._tickCallback (node.js:356:17)
at ChildProcess. (lib/teen_process.js:31:14)
at emitOne (events.js:77:13)
at ChildProcess.emit (events.js:169:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
at onErrorNT (internal/child_process.js:344:16)
at nextTickCallbackWith2Args (node.js:442:9)
at process._tickCallback (node.js:356:17)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "-g" "appium@beta"
npm ERR! node v4.4.5
npm ERR! npm v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! appium-selendroid-driver@1.2.2 install: node ./bin/install.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-selendroid-driver@1.2.2 install script 'node ./bin
/install.js'.
npm ERR! This is most likely a problem with the appium-selendroid-driver package
,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node ./bin/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs appium-selendroid-driver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR! npm owner ls appium-selendroid-driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\xxxx\npm-debug.log

**Comment by mykola-mokhnach** [comment]
ENOENT error means there is no such file or directory. Make sure the parent folder where jar utility is located is included to PATH environment variable and that selendroid-server.jar exists by the given path. Btw, what is the output after manual execution of that command?

**Comment by rajabhaskar** [comment]
@mykola-mokhnach I have placed the file path "C:\Users\xxxx\AppData\Roaming\
npm\node_modules\appium\node_modules\appium-selendroid-installer\selendroid\down
load" where the jar file is being I even tried to install the appium-selendroid-driver package by it self, but it error out with below message. My nodejs version is V6.2.1

C:\Users\xxxxx>npm install appium-selendroid-driver

> appium-chromedriver@2.9.2 install C:\Users\xxxxx\node_modules\appium-chromed
river
> node install-npm.js

info Chromedriver Install Installing Chromedriver version '2.21' for platform 'w
in' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com
/2.21/chromedriver_win32.zip...
info Chromedriver Install Writing binary content to C:\Users\xxxxx\AppData\Loc
al\Temp\201658-23084-ezbz23.jypcy833di\chromedriver_win32.zip...
info Chromedriver Install Extracting C:\Users\xxxxx\AppData\Local\Temp\201658-
23084-ezbz23.jypcy833di\chromedriver_win32.zip to C:\Users\xxxxx\AppData\Local
\Temp\201658-23084-ezbz23.jypcy833di\chromedriver_win32
info Chromedriver Install Creating C:\Users\xxxxx\node_modules\appium-chromedr
iver\chromedriver\win...
info Chromedriver Install Copying unzipped binary, reading from C:\Users\xxxxx
\AppData\Local\Temp\201658-23084-ezbz23.jypcy833di\chromedriver_win32\chromedriv
er.exe...
info Chromedriver Install Writing to C:\Users\xxxxx\node_modules\appium-chrome
driver\chromedriver\win\chromedriver.exe...
info Chromedriver Install C:\Users\xxxxx\node_modules\appium-chromedriver\chro
medriver\win\chromedriver.exe successfully put in place

> appium-selendroid-driver@1.3.4 install C:\Users\xxxxx\node_modules\appium-se
lendroid-driver
> node ./bin/install.js

dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_77
info SelendroidInstaller Standalone jar exists and has correct hash, skipping do
wnload
info SelendroidInstaller Determining AndroidManifest location
Error: Command 'jar tf C:\\Users\\xxxxx\\node_modules\\appium-selendroid-insta
ller\\selendroid\\download\\selendroid-server.jar' errored out: Error: spawn jar
 ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at ChildProcess.<anonymous> (lib/teen_process.js:31:14)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:202:12)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
C:\Users\xxxxx
+-- check-node-version@1.1.1
`-- lodash@4.13.1

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\xxxxx\packag
e.json'
npm WARN xxxxx No description
npm WARN xxxxx No repository field.
npm WARN xxxxx No README data
npm WARN xxxxx No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "appium-selendroid-driver"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE

npm ERR! appium-selendroid-driver@1.3.4 install: `node ./bin/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the appium-selendroid-driver@1.3.4 install script 'node ./bin
/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium-selendroid-dri
ver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium-selendroid-driver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium-selendroid-driver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xxxxx\npm-debug.log

**Comment by imurchie** [comment]
What is missing is not the jar file so much as the `jar` program. If you run `where jar` what happens? What if you run `jar`?

**Comment by rajabhaskar** [comment]
@imurchie I am able to solve the issue by updating my Java to Java 1.8.0_91 and also by downloading    and installing selandroid driver separately. Here is the output when I run where jar "C:\Program Files\Java\jdk1.8.0_77\bin\jar.exe" before I solved the issue, And after updating my jdk it became - "C:\Program Files\Java\jdk1.8.0_92\bin\jar.exe".... Thanks a lot for your help on this.
BUT
After installation of Appium I tried to run "adb devices" from platform-tools folder - then I got an error saying "adb stopped working". I tried to download Android SDK tools separately and replaced the tools folder with newly downloaded one but results the same error. 
Here are my other findings:
1. When I double click on "emulator-crash-service" it error out with message "Qt5Core.dll" is missing
2. When I run a sample program from IntelliJ with all necessary configurations, the program errorout with "Error:(42, 23) java: cannot access org.openqa.selenium.remote.http.HttpClient  class file for org.openqa.selenium.remote.http.HttpClient not found"
3. The AVD's that I have created in Android studio are not being displayed in Appium client(Appium.app) -->Android settings -->Launch AVD dropdown. 

These may not be related to a single issue, but just thought like this might give you some clue on what is happening. Thank you so much

**Comment by imurchie** [comment]
The adb and class not found issues seem separate. Not sure about Java and setting up a dev environment. Can you post on https://discuss.appium.io/ to see if someone there can help?

**Comment by vpkhachane** [comment]
How to fix following error . it is getting while installing Appium 1.6

Selendroid Could not find Java's 'jar' executable on your PATH.

![appium error](https://cloud.githubusercontent.com/assets/15686482/21516726/d6c340e8-ccff-11e6-9da7-12e541f3123e.jpg)

**Comment by vikramvi** [comment]
@vpkhachane please open a new ticket instead of mentioning on closed ticket. 

Also provide details as per issue format only, your screenshot is not very useful

**Comment by tpavan** [comment]
I am facing same issue while installing Appium 1.5.3 or 1.6.0 on windows 10

**Comment by Sanmejie** [comment]
![Uploading image.png…]()
C:\Users\mi>cnpm install appium@1.10 -g
Downloading appium to C:\Users\mi\AppData\Roaming\npm\node_modules\appium_tmp
Copying C:\Users\mi\AppData\Roaming\npm\node_modules\appium_tmp\_appium@1.10.1@appium to C:\Users\mi\AppData\Roaming\npm\node_modules\appium
Installing appium's dependencies to C:\Users\mi\AppData\Roaming\npm\node_modules\appium/node_modules
[1/32] @babel/runtime@^7.0.0 installed at node_modules\_@babel_runtime@7.3.1@@babel\runtime

WARN node unsupported "node@v6.11.4" is incompatible with appium-selendroid-driver@1.13.3 › request-promise@4.2.2 › tough-cookie@3.0.0 › ip-regex@^3.0.0, expected node@>=8
[2/32] appium-fake-driver@^0.x installed at node_modules\_appium-fake-driver@0.6.2@appium-fake-driver
[3/32] appium-windows-driver@1.x installed at node_modules\_appium-windows-driver@1.5.1@appium-windows-driver
[4/32] appium-mac-driver@1.x installed at node_modules\_appium-mac-driver@1.4.1@appium-mac-driver
[5/32] appium-base-driver@3.x installed at node_modules\_appium-base-driver@3.13.2@appium-base-driver
[6/32] appium-support@2.x installed at node_modules\_appium-support@2.25.0@appium-support
[7/32] async-lock@^1.0.0 existed at node_modules\_async-lock@1.1.3@async-lock
[8/32] asyncbox@2.x existed at node_modules\_asyncbox@2.5.2@asyncbox
[9/32] bluebird@3.x existed at node_modules\_bluebird@3.5.3@bluebird
[10/32] argparse@^1.0.10 installed at node_modules\_argparse@1.0.10@argparse
[11/32] dateformat@^3.0.3 installed at node_modules\_dateformat@3.0.3@dateformat
[12/32] find-root@^1.1.0 installed at node_modules\_find-root@1.1.0@find-root
[13/32] lodash@^4.17.9 existed at node_modules\_lodash@4.17.11@lodash
[14/32] continuation-local-storage@3.x installed at node_modules\_continuation-local-storage@3.2.1@continuation-local-storage
[15/32] npmlog@4.x existed at node_modules\_npmlog@4.1.2@npmlog
[16/32] request@^2.81.0 existed at node_modules\_request@2.88.0@request
[17/32] request-promise@4.x existed at node_modules\_request-promise@4.2.2@request-promise
[18/32] longjohn@^0.2.12 installed at node_modules\_longjohn@0.2.12@longjohn
[19/32] semver@^5.5.0 existed at node_modules\_semver@5.6.0@semver
[20/32] source-map-support@0.x existed at node_modules\_source-map-support@0.5.10@source-map-support
[21/32] teen_process@1.x existed at node_modules\_teen_process@1.14.1@teen_process
[22/32] appium-ios-driver@2.x installed at node_modules\_appium-ios-driver@2.13.2@appium-ios-driver
fsevents@2.0.1 download from binary mirror: {"host":"https://cdn.npm.taobao.org/dist/fsevents"}
platform unsupported fsevents@2.x Package require os(darwin) not compatible with your platform(win32)
[fsevents@2.x] optional install error: Package require os(darwin) not compatible with your platform(win32)
[npminstall:runscript] heapdump@0.x found binding.gyp file, auto run "node-gyp rebuild", root: "C:\\Users\\mi\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\_heapdump@0.3.12@heapdump"

C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\_heapdump@0.3.12@heapdump>node "C:\Users\mi\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
[24/32] winston@3.x installed at node_modules\_winston@3.1.0@winston
[25/32] appium-xcuitest-driver@^2.104.0 installed at node_modules\_appium-xcuitest-driver@2.107.0@appium-xcuitest-driver
[26/32] appium-tizen-driver@1.1.1-beta.2 installed at node_modules\_appium-tizen-driver@1.1.1-beta.2@appium-tizen-driver
[27/32] appium-youiengine-driver@^1.1.1 installed at node_modules\_appium-youiengine-driver@1.1.1@appium-youiengine-driver
[28/32] appium-android-driver@^4.0.0 installed at node_modules\_appium-android-driver@4.8.0@appium-android-driver
[29/32] appium-uiautomator2-driver@1.x installed at node_modules\_appium-uiautomator2-driver@1.28.1@appium-uiautomator2-driver
[30/32] appium-espresso-driver@^1.3.0 installed at node_modules\_appium-espresso-driver@1.7.1@appium-espresso-driver
[31/32] appium-selendroid-driver@1.x installed at node_modules\_appium-selendroid-driver@1.13.3@appium-selendroid-driver
Warning: Missing input files:
C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\_heapdump@0.3.12@heapdump\build\..\src\compat-inl.h
C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\_heapdump@0.3.12@heapdump\build\..\src\compat.h
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK ve
rsion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\_heapdump@0.3.12@heapdump\build\addon.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mi\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mi\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mi\AppData\Roaming\npm\node_modules\appium\node_modules\_heapdump@0.3.12@heapdump
gyp ERR! node -v v6.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
[npminstall:runscript:error] heapdump@0.x has binding.gyp file, run "node-gyp rebuild" error: Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
[heapdump@0.x] optional install error: Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\mi\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:74:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
execute post install 3 scripts...
[1/3] scripts.install appium-android-driver@4.8.0 › appium-chromedriver@^4.8.0 run "node install-npm.js", root: "C:\\Users\\mi\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\_appium-chromedriver@4.10.1@appium-chromedriver"
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function
Error trying to install Chromedriver binary. Waiting and trying again. Unexpected token function

**Comment by imurchie** [comment]
@Sanmejie What version of node and npm are you running?
