### ISSUE TITLE
Lost connection to selenium grid

### ISSUE THREAD

**Issue by michalakm** [appium/appium#6556]
## The problem

I run tests with Appium on real iOS device with selenium grid each hour. Sometimes test fails because of missing Appium session. 
In selenium grid log I see message:
"org.openqa.grid.internal.ActiveTestSessions - Session [7d44e3f9-591b-4632-b0fe-e7039d78cbec] not available and is not among the last 1000 terminated sessions.". 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OS 10.11.4
* Node.js version (unless using Appium.app|exe): v0.12.7
* Mobile platform/version under test: iOS 9.1.2
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium client
* Selenium Grid version: v.2.48.0

## Link to Appium logs

[appium log](https://gist.github.com/michalakm/81e39c4bfddfbd18edc28548283fd99f)
[part of selenium grid log](https://gist.github.com/michalakm/e10faacab7e256c8c0035cc446609fef)

If this log is not enough please let me know.

**Comment by mykola-mokhnach** [comment]
I'm not 100% sure, but you can try to play with timeouts for the grid. According to the attached log Appium session with id 7d44e3f9-591b-4632-b0fe-e7039d78cbec was registered as successfully created at 14:07:01:460 and the grid failed to get it at 16:07:01.499, which is a very short time period.

**Comment by SrinivasanTarget** [comment]
@triager please close
