### ISSUE TITLE
"Element does not exist in cache" after element changes state

### ISSUE THREAD

**Issue by bverkron** [appium/appium#6558]
## The problem

I am attempting to determine if an element is visible in mobile Safari. _When executing the code in debug mode in Eclipse everything works fine but when I do a full run it fails with the error_ "Element does not exist in cache" on the .isDisplayed call.
## Environment
- Appium app version: 1.5.2
- Last Appium version that did not exhibit the issue: Tried 1.4.13 but stuck in a "We launched the simulator but the required dirs don't yet exist"/ "Checking condition to see if we should kill instruments" loop
- Desktop OS/version: OS X 10.11.5
- Mobile platform/version under test: iPhone 6 / iOS 9.3 (simulator)
## Details

Can't determine why it's failing or why it works fine in debug mode. I have attempted other methods of detecting the presence of the element (even though this one works as proven by the line that's commented out) and I've also attempted to put arbitrary waits in various places with no success (not that it should matter because the first line should wait until the element exists before proceeding anyway).

HTML for the element and some of it's parents.

```
<div id="login-message" class="modal fade in">
    <div id="loginmessage">        
        <div class="modal-header">
            <button class="close" data-dismiss="modal"><a href="javascript:" onclick="loginBox();">x</a></button>
            <h3>Success!</h3>
        </div>
        <div class="modal-body scroll-area-modal">
            <div class="scroller2">                       
               <b>Welcome <span class="firstName">fname501</span></b>
               <p class="showLastVisit"><span class="lastVisit" id="lastdate">Your last visit was at 15:42 on Monday, June 06, 2016 </span></p>
            </div>
        </div>
        <div class="modal-footer">
            <a class="btn btn-large btn-primary" href="javascript:" onclick="loginBox();">OK</a>
        </div>
    </div>
</div>
```

I just tried another element on another page (a standard text box) and the same code works without issue.  Perhaps this issue has to do with the css or other properties of the element?
## Link to Appium logs

https://gist.github.com/bverkron/d72794d006195d772929e293dc9d05bf
## Code To Reproduce Issue

```
//xpath passed to this block of code is //*[@id='loginmessage']/div[1]/h3
WebElement element = (new WebDriverWait(wd, timeout))
    .until(ExpectedConditions.presenceOfElementLocated(By.xpath(xpath)));

//element.getAttribute("innerHTML") returns the expected text so I know the element has been found and is present.

boolean elementVisible;

elementVisible = element.isDisplayed();
```

**Comment by bverkron** [comment]
Hmmmm, it seems adding an even longer arbitrary wait (30 sec) before calling that code makes it work.  So there is some kind of timing issue, even when the element is detected as being present ahead of time by the wait code.

**Comment by bverkron** [comment]
Seems like a race condition or something.  If I wait 30 seconds before calling that code it seems to work. If, however, I surround it (just the .isDisplayed call) with a try / catch and keep trying it for upwards of 60 seconds it will continue to fail. Even if the element is clearly visible on the page and the previous wait for presence has succeeded.

**Comment by mykola-mokhnach** [comment]
We use this universal wrapper to make sure an element is visible
```java

 public static boolean isElementPresentAndDisplayed(RemoteWebDriver driver, final WebElement element) {
        try {
            return element.isDisplayed();
        } catch (NoSuchElementException e) {
            return false;
        }
    }

....

  Wait<WebDriver> wait = new FluentWait<WebDriver>(driver)
                    .withTimeout(timeoutSeconds, TimeUnit.SECONDS)
                    .pollingEvery(1, TimeUnit.SECONDS)
                    .ignoring(NoSuchElementException.class)
                    .ignoring(StaleElementReferenceException.class)
                    .ignoring(InvalidElementStateException.class);
            try {
                return wait.until(drv -> {
                    final List<WebElement> foundElements = drv.findElements(by);
                    if (foundElements.size() > 0) {
                        for (WebElement element : foundElements) {
                            if (isElementPresentAndDisplayed(driver, element)) {
                                return true;
                            }
                        }
                    }
                    return false;
                });
            } catch (TimeoutException e) {
                return false;
            }
```

**Comment by mykola-mokhnach** [comment]
Also, you can try to use visibilityOfElementLocated condition instead of presenceOfElementLocated, which, actually, only verifies that the corresponding element is present in DOM. But it will fail anyway with something like StaleElementReferenceException or InvalidElementStateException if the page under test is being dynamically changed by javascript at the same time when element verification happens.

**Comment by bverkron** [comment]
I will give those a try, but ultimately should isDisplayed be throwing the "Element does not exist in cache" exception?  The element is detected, it's clearly visible on the screen (and has been for some time with the earlier arbitrary waits I tried) so in my mind it should simply thrown false.  I could see the other exceptions being thrown, perhaps, but the cache exception perplexes me.  Having to wait 30+ seconds before I can call .isDisplayed for it to work (to avoid being stuck with that exception) seems odd.

**Comment by bverkron** [comment]
Hmmm, looking at the log entries I can see that it does return boolean false for the first few iterations of the loop..

```
Checking //*[@id='loginmessage']/div[1]/h3 for visiblity (waiting up to 60 seconds)... 
Checking for visibility... result = false
Checking for visibility... result = false
Checking for visibility... result = false
Checking for visibility... result = false
Checking for visibility... result = false
Error attempting to detect visibilty of element: org.openqa.selenium.WebDriverException: Element does not exist in cache (status: 10) (WARNING: The server did not provide any stacktrace information)
```

...but once the cache exception is thrown it never comes back to life.  If, however I wait long enough before starting that loop it will return true right away and succeed.  There must be some kind of flux going on in the page or the server that throws it into that cache exception state and then it just stays there.

**Comment by bverkron** [comment]
Yup, looks like it something along those lines.  If I re-identify the object after the cache exception is thrown I can call isDisplayed again successfully.

```
			} catch (Exception e){
				Log("Error attempting to detect visibilty of element: " + e.toString() + " ");
				
				//Re-identify the element and repopulate the object
				element = wait.until(new Function<WebDriver,WebElement>(){
					public WebElement apply(WebDriver arg0) {
						return wd.findElement(By.xpath(xpath));}
					});
			}
```

Log...
```
Checking //*[@id='loginmessage']/div[1]/h3 for visiblity (waiting up to 60 seconds)... Checking for visibility... result = false
Checking for visibility... result = false
Checking for visibility... result = false
Checking for visibility... result = false
Checking for visibility... result = false
***** Element disappears from cache *****
Error attempting to detect visibilty of element: org.openqa.selenium.WebDriverException: Element does not exist in cache (status: 10) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 514 milliseconds
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 16:57:40'
System info: host: 'Automation-Mac-Mini.local', ip: '10.150.1.29', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_91'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{networkConnectionEnabled=false, databaseEnabled=false, deviceName=iPhone 6, platform=MAC, showIOSLog=true, nativeInstrumentsLib=true, desired={showIOSLog=true, nativeInstrumentsLib=true, safariIgnoreFraudWarning=true, newCommandTimeout=1200, platformVersion=9.3, browserName=safari, platformName=iOS, deviceName=iPhone 6, autoAcceptAlerts=true}, safariIgnoreFraudWarning=true, newCommandTimeout=1200, platformVersion=9.3, webStorageEnabled=false, locationContextEnabled=false, browserName=safari, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, autoAcceptAlerts=true}]
Session ID: 9d65bc91-6aac-4093-a469-be5b4fd48a67 
***** Element re-identified / repopulated *****
Checking for visibility... result = true
Element visible
```

What could cause the element to be removed form the cache like that?

**Comment by mykola-mokhnach** [comment]
So, we got a solution now. The fact that the element changes its state is something, which has nothing to do with Appium itself. This would be rather some special behaviour of the page under test.

**Comment by bverkron** [comment]
Well, I wouldn't call it a solution (at least not a great one) but yes I think we found the cause.

It would be nice to know what kind of attributes of the element have to change in order for it to trigger that cache exception.  Also, what are the differences between this cache exception and other 'stale' exceptions? 

I believe only the 'style' property changes, the ID and everything else about the element remains the same so to lose the reference and have to rebuild it is a little awkward.  Maybe any attribute changes cause it to be tossed from the cache?

**Comment by littleclay** [comment]
We've started running into the same issue occasionally. I thought that any change that invalidates the element should throw a StaleElementReferenceException?

**Comment by carsonreinke** [comment]
This may or may not be related, but I was receiving this error also.  I found the problem was sending an array of `WebElement` objects to `executeScript` would produce this same error.  It was fixed by simply flattening the array to actual arguments worked.  Thanks @sgorman

**Comment by littleclay** [comment]
Bump on this: https://github.com/appium/appium/issues/6558#issuecomment-252040526

**Comment by dpgraham** [comment]
@littleclay Have you tested this in 1.6.4?

**Comment by aoby** [comment]
We are seeing this bug in `1.6.5`. We were able to [work around](https://github.com/code-dot-org/code-dot-org/pull/18462) it though by catching the exception in a wrapper.
