### ISSUE TITLE
Auto accept alert fails if App alert comes before app is launched

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#6559]
## The problem

Auto accept alert fails if App alert comes before app is launched. The Alert actually belongs to App but Appium fails to Accept that.

setting capability as below:
capabilities.setCapability("autoAcceptAlerts", true);
## Environment

Noticed this on 1.4.13 

## Details
Before App launches an Alert appears saying App wants to Access microphone..etc

**Comment by mykola-mokhnach** [comment]
I'd say the application under test violates iOS Human Interface guidelines. It is stated there, that security alerts should be triggered before the corresponding function call rather than on app startup:

>  Ask permission at app startup only if your app can’t perform its primary function without the user’s data. People won’t be bothered by this if it’s obvious that the main function of your app depends on knowing their personal information.
> 
> Avoid making programmatic calls that trigger the alert before the user actually selects the feature that needs the data. This way, you avoid causing people to wonder why your app wants their personal information when they’re doing something that doesn’t appear to need it. (Note that checking the user’s Location Services preference does not trigger the alert.) 


https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/LocationServices.html#//apple_ref/doc/uid/TP40006556-CH42-SW1

**Comment by imurchie** [comment]
Workarounds are found here: https://github.com/appium/appium/issues/4178

**Comment by priyankshah217** [comment]
@VenkateshPS , i faced this issue, but problem lies here is appium identifies alert once your app launch. if alert pops up before app launch then appium is not able to recognize it. So the workaround which i followed is to ask developer to put some delay between app launch and alert. so in my case app's startup screen display first soon it alert pops up. So spending so much amount of time and energy for this, you can simply ask developer to introduce some delay. I believe it does not affect your core functionality.

**Comment by VenkateshPS** [comment]
@priyankshah217 , I too asked the developer to add delay.

**Comment by SrinivasanTarget** [comment]
@triager please close
