### ISSUE TITLE
Does WebElement and MobileElement click differently for mobile apps?

### ISSUE THREAD

**Issue by nirajsingh1486** [appium/appium#6560]
**Does WebElement and MobileElement click differently for mobile apps?**

**Right now i am trying to click Element in mobile app using WebElement element .**

Code for click:

 public static void click (AppiumDriver driver, WebElement webElement, String webElementName, String activityName){

        ActionModule.isDisplayed(driver, webElement, webElementName, activityName);

        try{
            if (! Utils.waitForElementToBeClickable(driver, webElement)){
                Log.error(webElement + " is not clickable");
                Reporter.log(webElement + " is not clickable");
                Assert.fail(webElement + " is not clickable");
            }
            webElement.click();
            Log.info(webElementName + " is successfully clicked on " + activityName + " activity");
        } 
        /*catch (AppiumDriverException e1){
            Log.error(webElementName + " is not clickable at this point. Pls check logs");
            Log.debug(e1.getMessage());
            Reporter.log(webElementName + " is not clickable at this point. Pls check logs");
            Assert.fail(webElementName + " is not clickable at this point. Pls check logs");
        }*/
        catch (Exception e){
            Log.error(e.getLocalizedMessage());
            Reporter.log(e.getLocalizedMessage());
            Assert.fail(e.getLocalizedMessage());
        }
    }

**Comment by imurchie** [comment]
This would be better asked directly to whatever client binding you are using. The appium server does not have anything to do with that.
