### ISSUE TITLE
Appium hangs after clicking a button that closes an Android webview

### ISSUE THREAD

**Issue by dekelev** [appium/appium#6562]
## The problem

Appium hangs after clicking a button that closes an Android WebView that was opened by another WebView.

It always used to work, but the issue had started after upgrading to Appium 1.5.2 (same on 1.5.3).
I reverted back to Appium 1.4.16 and then it worked again.
## Environment
- Appium version (or git revision) that exhibits the issue: Appium 1.5.2, 1.5.3
- Last Appium version that did not exhibit the issue (if applicable): Appium 1.4.16
- Desktop OS/version used to run Appium: Windows 8.1
- Node.js version (unless using Appium.app|exe): 4.4.5
- Mobile platform/version under test: Samsung Galaxy S4 with Android 5.0.1
- Real device or emulator/simulator: real device
- Appium CLI or Appium.app|exe: Appium CLI
## Details

My test opens an Android webview from a native app, then it clicks on a button that opens a new webview above the first one.
Then it clicks on a button that closes the webview and gets back to the first webview.
At this point, Appium just hangs without responding to the click action.
## Link to Appium logs

https://gist.github.com/dekelev/281cbe931ffb0177e56f2f99b1a28765

**Comment by dekelev** [comment]
I've found a workaround.

Works:
```
.execute("setTimeout(function () { document.getElementById('ButtonSubmit').click(); }, 5000)").context('NATIVE_APP')
```

Does NOT work:
```
.elementById('ButtonSubmit').click().context('NATIVE_APP')
```
Does NOT work:
```
.execute("document.getElementById('ButtonSubmit').click()").context('NATIVE_APP')
```

**Comment by jlipps** [comment]
Thanks, good to know that users might need to wait a bit of time before looking for contexts.

**Comment by abisekkachroo** [comment]
@dekelev 
Can you please provide a code example on how to solve this 
I have found the issue a pop-up appears 
Its a popup with the list of language fields  
After selecting anyone language I click on done button .
Again its works without using switching to alert or frames
But when the popup closes exection gets hanged till appium session is closed

**Comment by dekelev** [comment]
@abisekkachroo
I've shared my workaround in Node.JS, and there's no Java equivalent implementation that I'm aware of and in anyway, I'm no longer working on Appium related projects and I don't even have access to my original Appium project.
