### ISSUE TITLE
An unknown server-side error occurred while processing the command

### ISSUE THREAD

**Issue by hajarbabour** [appium/appium#6563]
I m trying to run multiples tests cases  with testNg, Selenium webdriver , and appium
but after running  a few testCases , the appium server is blocked and i get this error in the console 

An unknown server-side error occurred while processing the command. (Original error: Timed out waiting for screenshot file. Error: ENOENT, open '/tmp/appium-instruments/Run 1/screenshotb4024ccd-f974-4e32-94fa-6e043c840c48.png') (WARNING: The server did not provide any stacktrace information)

Command duration or timeout: 73.35 seconds

Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:03:33'

System info: host: 'users-iMac.local', ip: '192.168.1.27', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_80'

Session ID: b495c112-eb63-4d7d-8376-8e0c9698b637

Driver info: io.appium.java_client.ios.IOSDriver

Capabilities [{platform=MAC, javascriptEnabled=true, browserName=iOS, networkConnectionEnabled=false, desired={newCommandTimeout=40000, platformVersion=9.2, deviceName=iPad 2, platformName=iOS, bundleId=com.InovaSquad.Artinove}, locationContextEnabled=false, newCommandTimeout=40000, platformVersion=9.2, databaseEnabled=false, deviceName=iPad 2, platformName=iOS, webStorageEnabled=false, bundleId=com.InovaSquad.Artinove, warnings={}, takesScreenshot=true}]

An unknown server-side error occurred while processing the command. (Original error: Timed out waiting for screenshot file. Error: ENOENT, open '/tmp/appium-instruments/Run 1/screenshotb4024ccd-f974-4e32-94fa-6e043c840c48.png') (WARNING: The server did not provide any stacktrace information)

Command duration or timeout: 73.35 seconds

Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:03:33'

System info: host: 'users-iMac.local', ip: '192.168.1.27', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_80'

Session ID: b495c112-eb63-4d7d-8376-8e0c9698b637

Driver info: io.appium.java_client.ios.IOSDriver

Capabilities [{platform=MAC, javascriptEnabled=true, browserName=iOS, networkConnectionEnabled=false, desired={newCommandTimeout=40000, platformVersion=9.2, deviceName=iPad 2, platformName=iOS, bundleId=com.InovaSquad.Artinove}, locationContextEnabled=false, newCommandTimeout=40000, platformVersion=9.2, databaseEnabled=false, deviceName=iPad 2, platformName=iOS, webStorageEnabled=false, bundleId=com.InovaSquad.Artinove, warnings={}, takesScreenshot=true}]

the console log :

{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/3/0/5","x":146,"y":391,"width":383,"height":45},">":[]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/3/0/6","x":146,"y":391,"width":383,"height":45},">":[]}}]}}]}}]}}}

info: [debug] Socket data received (33 bytes)

info: [debug] Socket data being routed.

info: [debug] Got result from instruments: {"status":0,"value":"PORTRAIT"}

info: [debug] Setting internal orientation to PORTRAIT

info: [debug] Pushing command to appium work queue: "au.capture('screenshot0f02fa4c-5c6f-4d33-957f-d373a46db2b2')"

info: [debug] Sending command to instruments: au.capture('screenshot0f02fa4c-5c6f-4d33-957f-d373a46db2b2')

info: [debug] [INST] 2016-06-08 10:40:40 AM +0000 Debug: Running system command #727: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"Artinove","label":"Artinove","value":null,"dom":n...

info: [debug] [INST] 2016-06-08 10:40:41 AM +0000 Debug: Got new command 727 from instruments: au.getElementByIndexPath('/0/0/1/0/100')

info: [debug] Socket data received (25 bytes)

info: [debug] Socket data being routed.

info: [debug] Got result from instruments: {"status":0,"value":""}

info: [debug] Waiting 10000 ms for screenshot to ge generated.

info: [debug] [INST] 2016-06-08 10:40:41 AM +0000 Debug: evaluating au.getElementByIndexPath('/0/0/1/0/100')

info: [debug] [INST] 2016-06-08 10:40:41 AM +0000 Debug: evaluation finished

info: [debug] [INST] 2016-06-08 10:40:41 AM +0000 Debug: Lookup returned [object UIAButton] with the name "Ok" (id: 230).

info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Timed out waiting for screenshot file. Error: ENOENT, open '/tmp/appium-instruments/Run 1/screenshot0f02fa4c-5c6f-4d33-957f-d373a46db2b2.png')","origValue":"Timed out waiting for screenshot file. Error: ENOENT, open '/tmp/appium-instruments/Run 1/screenshot0f02fa4c-5c6f-4d33-957f-d373a46db2b2.png'"},"sessionId":"b495c112-eb63-4d7d-8376-8e0c9698b637"}

info: <-- GET /wd/hub/session/b495c112-eb63-4d7d-8376-8e0c9698b637/screenshot 500 64941.953 ms - 470 

info: [debug] [INST] 2016-06-08 10:40:41 AM +0000 Debug: responding with:

info: [debug] [INST] 2016-06-08 10:40:41 AM +0000 Debug: Running system command #728: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"ELEMENT":"230"}}...

info: [debug] [INST] 2016-06-08 10:40:42 AM +0000 Debug: Got new command 728 from instruments: au.tapById('230')

info: [debug] [INST] 2016-06-08 10:40:42 AM +0000 Debug: evaluating au.tapById('230')

info: [debug] [INST] 2016-06-08 10:40:42 AM +0000 Debug: target.frontMostApp().elements()[0].elements()[1].elements()[0].elements()[100].tap()

info: --> POST /wd/hub/session/b495c112-eb63-4d7d-8376-8e0c9698b637/element {"using":"xpath","value":"//UIAApplication[1]/UIAWindow[1]/UIAScrollView[2]/UIAWebView[1]/UIAButton[3]"}

info: [debug] Waiting up to 0ms for condition

info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"

info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()

info: [debug] [INST] 

2016-06-08 10:40:43 AM +0000 Debug: evaluation finished

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"b495c112-eb63-4d7d-8376-8e0c9698b637"}

info: <-- GET /wd/hub/status 200 1.752 ms - 179 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"b495c112-eb63-4d7d-8376-8e0c9698b637"}

info: [debug] [INST] 2016-06-08 10:40:43 AM +0000 Debug: responding with:

info: [debug] [INST] 2016-06-08 10:40:43 AM +0000 Debug: Running system command #729: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...

info: [debug] [INST] 2016-06-08 10:40:45 AM +0000 Debug: Got new command 729 from instruments: au.mainApp().getTreeForXML()

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"b495c112-eb63-4d7d-8376-8e0c9698b637"}

info: <-- GET /wd/hub/status 200 1.197 ms - 179 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"},"isShuttingDown":false},"sessionId":"b495c112-eb63-4d7d-8376-8e0c9698b637"}

info: [debug] [INST] 2016-06-08 10:40:45 AM +0000 Debug: evaluating au.mainApp().getTreeForXML()

info: [debug] [INST] 2016-06-08 10:40:46 AM +0000 Debug: evaluation finished

info: [debug] Socket data received (208 bytes)

**Comment by mykola-mokhnach** [comment]
Try to increase the _screenshotWaitTimeout_ value in driver capabilities.
Also check this thread https://discuss.appium.io/t/screenshotwaittimeout-not-accepted-as-a-capability/2119 - might be helpful.

Btw, in our company we don't use built-in Appium screenshoting feature for Simulator, since it's slow. I've created custom ObjectiveC application, which does the job and saves taken screenshot into a file. It's, probably, not ideal, but suits our needs pretty well:
```objc
#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>

int getSimWindowPid() {
    @autoreleasepool {
        NSArray *windowInfos = (__bridge_transfer NSArray*)CGWindowListCopyWindowInfo(kCGWindowListOptionAll, kCGNullWindowID);
        int result = 0;
        for(NSDictionary *windowInfo in windowInfos) {
            NSString* windowName = windowInfo[(__bridge NSString*)kCGWindowName];
            NSString* windowOwnerName = windowInfo[(__bridge NSString*)kCGWindowOwnerName];
            if ([windowName containsString:@"iOS"] && [[windowOwnerName lowercaseString] containsString:@"simulator"]) {
                return [windowInfo[(__bridge NSString*)kCGWindowNumber] intValue];
            }
        }
        return result;
    }
}

#define TOP_BAR_HEIGHT 22

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        if (argc < 2) {
            NSLog(@"Usage: simshot <path_to_result_png_screenshot> <real_window_height>");
            return -1;
        }
        int simWindowPid = getSimWindowPid();
        if (simWindowPid <= 0 ) {
            return -1;
        }
        CGImageRef img = CGWindowListCreateImage(CGRectNull, kCGWindowListOptionIncludingWindow, simWindowPid, kCGWindowImageBoundsIgnoreFraming);
        size_t currentWidth = CGImageGetWidth(img);
        size_t currentHeight = CGImageGetHeight(img);
        // Remove the top window bar from the screenshot
        img = CGImageCreateWithImageInRect(img, CGRectMake(0, TOP_BAR_HEIGHT, currentWidth, currentHeight - TOP_BAR_HEIGHT));
        NSMutableData *imgData = [[NSMutableData alloc] init];
        CGImageDestinationRef imgDest = CGImageDestinationCreateWithData((__bridge CFMutableDataRef)imgData, kUTTypePNG, 1, NULL);
        CGImageDestinationAddImage(imgDest, img, NULL);
        BOOL finalizeRes = CGImageDestinationFinalize(imgDest);
        if(!finalizeRes) return -1;
        
        NSString *dstPath = [NSString stringWithUTF8String:argv[1]];
        if (![imgData writeToFile:dstPath atomically:YES]) {
            return -1;
        }
    }
    return 0;
}

```

**Comment by imurchie** [comment]
Without the full logs it's hard to know. But can you check if there are multiple Instruments processes running? There is an issue where that happens, and can come up after multiple tests have been running, in a variety of ways.

**Comment by SrinivasanTarget** [comment]
@triager please close
