### ISSUE TITLE
using the ignoreUnimportantViews capability leads to an internal server error

### ISSUE THREAD

**Issue by rompic** [appium/appium#6568]
## The problem
An internal error occurs if the ignoreUnimportantViews capability is set.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.2
* Last Appium version that did not exhibit the issue (if applicable): I'm not to sure but I think this worked on 1.4.x
* Desktop OS/version used to run Appium: Mac OSX 10.11.5
* Node.js version (unless using Appium.app|exe): v6.2.1
* Mobile platform/version under test: android
* Real device or emulator/simulator: both (real device & emulator)
* Appium CLI or Appium.app|exe: CLI

## Details
see logs
Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs
https://gist.github.com/rompic/ade73ebd45f3bd3d249c3d5204d68368

## Code To Reproduce Issue [ Good To Have ]
capabilities.setCapability(AndroidMobileCapabilityType.IGNORE_UNIMPORTANT_VIEWS,true);

**Comment by rompic** [comment]
same issue on Appium v1.5.3

**Comment by imurchie** [comment]
Can you post the logs for the error in 1.5.3? I cannot reproduce this locally. :(

**Comment by rompic** [comment]
seems as if I cannot reproduce it either :(
