### ISSUE TITLE
An element could not be located on the page 

### ISSUE THREAD

**Issue by hajarbabour** [appium/appium#6570]
The appium server is blocked and the test is failed   when running a large suite of tests  cases in java and TestNG. When running individual test  it works fine . Any idea what might have caused this issue?

I m getting this error 

An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2.12 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:03:33'
System info: host: 'users-iMac.local', ip: '192.168.1.27', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_80'
**\* Element info: {Using=xpath, value=//UIAApplication[1]/UIAWindow[1]/UIAScrollView[2]/UIAWebView[1]/UIAButton[11]}
Session ID: 3555a2fb-e5d5-4379-8406-8e4bc5daebc5
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{platform=MAC, javascriptEnabled=true, browserName=iOS, networkConnectionEnabled=false, desired={newCommandTimeout=40000, platformVersion=9.2, deviceName=iPad 2, platformName=iOS, bundleId=com.InovaSquad.Artinove}, locationContextEnabled=false, newCommandTimeout=40000, platformVersion=9.2, databaseEnabled=false, deviceName=iPad 2, platformName=iOS, webStorageEnabled=false, bundleId=com.InovaSquad.Artinove, warnings={}, takesScreenshot=true}]

**Comment by imurchie** [comment]
Does this happen randomly? Or always in one place? Is the element there?

Can you provide the server logs for the failing run? With the information provided it is impossible to say anything.
