### ISSUE TITLE
AppiumDriver.findElementFromElement() not work stable for android

### ISSUE THREAD

**Issue by HlebHalkouski** [appium/appium#6571]
## The problem

Calling AppiumDriver.findElementFromElement() is not work stable. 
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable): 1.4.16
- Desktop OS/version used to run Appium: Mac OS
- Node.js version (unless using Appium.app|exe): v5.7.0
- Mobile platform/version under test: Android 
- Real device or emulator/simulator: real device
- Appium CLI or Appium.app|exe: cli
## Details

I have a native application with video player. Controls on player displayed only for 5 seconds after taping on the player. On appium@1.4.16 I don't have any issue's with locate control elements and do some actions(getText(), getSize(), click(), etc) with this elements. But after update appium server to 1.5+ versions I have a troubles with finding the elements on video player. It's not works stable. I was retrying to find this elements after NoSuchElementExceptions, for sometimes it's works, but almost retrying also cannot find this element. 

In logs you can find a different behavior the appium server with a same test scrips.  

This is big blocker for my work. I will be grateful for a solution to this problem
## Link to Appium logs

[appium@1.5.3](https://gist.github.com/HlebHalkouski/7ae7d749b4b1916b5068a80452423d75)
[appium@1.4.16](https://gist.github.com/HlebHalkouski/b475d8f41045bbf5c5f4ee8255c75a85)

**Comment by mykola-mokhnach** [comment]
You can use xpath locators as a workaround

**Comment by imurchie** [comment]
Is there any possibility of getting a copy of your application to test this. It works for our test apps, unfortunately.

**Comment by HlebHalkouski** [comment]
@imurchie product owner will be not happy. I will try to reproduce on your sample-applications. Thank you.

**Comment by imurchie** [comment]
Understood. The layout of the nested elements might be enough for me to reproduce.

**Comment by aquintiliano** [comment]
I even can't find this method... is it java?

**Comment by ajeeshvl** [comment]
@HlebHalkouski  were you able to resolve this?. I'm facing same issue.
appium version: 1.6.4
Mobile Platform: 6.0.1

I even tried with xpath, it doesn't work. It works perfect, only when the playback is paused.

**Comment by HlebHalkouski** [comment]
@ajeeshvl did you tried with ID? Also we use driver as search contex and this works better.

**Comment by ajeeshvl** [comment]
@HlebHalkouski yes, I tried with ID.  can you explain a bit more about using driver as search context?. Did you mean to say, like bellow code? but it does't return anything.
 driver.findElements(By.xpath("//android.widget.ImageButton"))
 driver.findElements(By.id("btn_play_pause"))

**Comment by igalep** [comment]
Same issue here as well , 

The `findElementFromElement()` is not stable at all for Android , fails 60% of the time...

Any ideas ?

**Comment by zeeshanahmed91** [comment]
@imurchie @mykola-mokhnach 
I am facing the same issue, when i tried to findElementFromElement(). I am using the uiautomator2 Capability.

**Java client Version is** : 5.0.4
**Appium : v** 1.7.1

**Server Logs are :**  https://gist.github.com/zeeshanahmed91/51872ff0483dc12a45410da8de7b519c

Any Update on this Issue ? Please clarify either its Bug of Appium Server /UIAutomator2  or Java_Client Library.
Thanks

**Comment by zeeshanahmed91** [comment]
@HlebHalkouski 
Any Update on Above Issue *findElementFromElement()* ? 
Thanks
