### ISSUE TITLE
Impossibe to read hint text from the android.widget.EditText field.

### ISSUE THREAD

**Issue by acidroed** [appium/appium#6572]
## The problem

It's impossibe to read hint text from the android.widget.EditText element. I know that it could be possible to use element.getAttribute("name") earlier, but now it doesn't work.
## Environment
- Appium version: 1.4.16.1
- Desktop OS/version used to run Appium: Windows 7
- Mobile platform/version under test: Nexus4, Android 4.4.2, API19
- Real device or emulator/simulator: emulator
- Appium CLI or Appium.app|exe: exe
## Details

I have EditText Element in my app. It's username field. So, when it's empty, I need to check that "Username" hint text is present, but I can't read it.
There is screenshot from UI Automator Viewer:
![appiumissue](https://cloud.githubusercontent.com/assets/13766722/15931754/b1ad2266-2e61-11e6-91fa-fba474e05a99.PNG)

element.getAttribute("name") returns "". Also I've tried element.getAttribute("hint"), but there was exception.

**Comment by imurchie** [comment]
What happens when you get the text of the element when the hint text is there? In my experience it returns the hint text.

**Comment by acidroed** [comment]
> What happens when you get the text of the element when the hint text is there?
It returns empty String.

> In my experience it returns the hint text.
Yes, it worked earlier. That's why we could easily get hint text using element.getAttribute("name") or element.getText(). But now it doesn't work. As you can see in the screenshot, fields text and content-desc are empty. Maybe because of new SDK version, or new Appium.

**Comment by imurchie** [comment]
If the UI Automator Viewer is unable to find it, then Appium will not be able to find it (since Appium uses Ui Automator to automate the app). What version of the Android SDK are you using? It worked for my test app using the latest (25.1.7).

**Comment by acidroed** [comment]
25.1.7

**Comment by imurchie** [comment]
Hmm. Any possibility that I can get a copy of the app so I can reproduce and fix, if possible?

**Comment by acidroed** [comment]
Sorry, unfortunately I can't, because of trade secret.

**Comment by imurchie** [comment]
Understood.

**Comment by Slaiter** [comment]
@acidroed Hello, tell me please, you found a solution how to get the text of a hint if him is not visible?
