### ISSUE TITLE
Appium could not find hooks by name

### ISSUE THREAD

**Issue by enguyen1967** [appium/appium#6573]
## The problem

I download and using Appium 1.5.3 and my tests start falling because can't find the hooks. I change the hook to XPath and it start working.

## Environment

* Appium version 1.5.3
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: OS X El Capitan
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 9.3
* Real device or emulator/simulator: iPhone 6
* Appium CLI or Appium.app|exe: using Appium.App

**Comment by imurchie** [comment]
What do you mean "can't find the hooks"? 

Can you provide a [gist](https://gist.github.com) with the server logs for the error?

**Comment by enguyen1967** [comment]
This is the hooks I am looking for (Email, Password, LoginButton). You will see I changed them from by name to by xpath:
// Hook to Email text field
			//public static SeleniumHook Email = By.Name("signup_v5_login_email_text_field");
			public static SeleniumHook Email = By.XPath("//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIATextField[1]");
			// Hook to button clear text 
			public static SeleniumHook ClearText = By.Name("Clear text");
			//public static SeleniumHook ClearText = By.XPath("//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIATextField[1]/UIAButton[1]");
			// Hook to Password text field
			//public static SeleniumHook Password = By.Name("signup_v5_login_password_text_field");
			public static SeleniumHook Password = By.XPath("//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIASecureTextField[1]");
			// Hook to Login button
			//public static SeleniumHook LoginButton = By.Name("signup_v5_login_button"); 
			public static SeleniumHook LoginButton = By.XPath("//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAElement[2]");

The log I will attach show the hook cannot found since I haven't change them to xpath (ROADBLOCK_TOS_agree_button)

[automation_log.txt](https://github.com/appium/appium/files/307534/automation_log.txt)

**Comment by imurchie** [comment]
Ah. Yes, the `name` locator strategy no longer exists in Appium 1.5.x. It was long deprecated and now removed. `XPath` works, or you could try `accessibility id`, which is generally better.

**Comment by enguyen1967** [comment]
Cool. Let me try that. Thanks

**Comment by enguyen1967** [comment]
Yeah, that works. Thanks

**Comment by imurchie** [comment]
Excellent! Glad it worked out.
