### ISSUE TITLE
Error from "npm install -g appium"

### ISSUE THREAD

**Issue by mkataokaelementum** [appium/appium#6574]
I am trying to upgrade Appium today and am unable to do so via "npm install -g appium" due to the following error.  Could someone please help ? 

$ npm install -g appium

/usr/local/bin/authorize-ios -> /usr/local/lib/node_modules/appium/node_modules/.bin/authorize-ios
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v4.4.4
npm ERR! npm  v3.9.0
npm ERR! path /usr/local/bin/appium
npm ERR! code EEXIST

npm ERR! Refusing to delete /usr/local/bin/appium: ../lib/node_modules/appium/bin/appium.js symlink target is not controlled by npm /usr/local
npm ERR! File exists: /usr/local/bin/appium
npm ERR! Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mayukataoka/npm-debug.log
npm ERR! code 1

**Comment by imurchie** [comment]
```
npm ERR! File exists: /usr/local/bin/appium
npm ERR! Move it away, and try again.
```

You will need to manually delete (or move, if you prefer) `/usr/local/bin/appium`.

**Comment by mkataokaelementum** [comment]
Fixed by removing /usr/local/bin/appium and reinstalling it.
Thank you.

**Comment by imurchie** [comment]
You're welcome. Glad it worked out.
