### ISSUE TITLE
Inability to retrieve a checkbox state for UWP application

### ISSUE THREAD

**Issue by quitefire** [appium/appium#6576]
Hi guys, could you suggest on how to get a checkbox state of AppiumWebElement for UWP application?

isChecked = false and can't be changed when a checkbox is checked/unchecked

Regards,
Bogdan

**Comment by imurchie** [comment]
What is a UWP application?

Can you provide some information about what happens when you try? Preferably the full logs as a [gist](https://gist.github.com).

**Comment by quitefire** [comment]
follow the link to see : [https://msdn.microsoft.com/en-us/windows/uwp/get-started/whats-a-uwp](url)
there is nothing to share on gist ...it's not possible to get a real checkbox state using isChecked() method ( java bindings).
The method always returns "false" value no matter whether a checkbox is checked or not.

**Comment by imurchie** [comment]
I don't understand where this app would be running. Is it on an iOS or Android device?

**Comment by quitefire** [comment]
In our case , it's a desktop windows 10 (uwp) application.  Also, it could be run on a phablet or a windows phone .

**Comment by pr4bh4sh** [comment]
@quitefire You should look into https://github.com/2gis/Winium, Appium is for android and iOS.

**Comment by quitefire** [comment]
@pr4bh4sh I'm in need of an open source instrument .
For winium to support an automated testing of UWP desktop application I should have Microsoft Visual Studio Enterprise with the license for 6k $ since it uses Coded UI internally.

**Comment by jlipps** [comment]
You should now be using WinAppDriver, it supports UWP apps.
