### ISSUE TITLE
Can not install Appnium in Mac and uninstall/install several time ,still do not work 

### ISSUE THREAD

**Issue by baot20** [appium/appium#6577]
## The problem

I install node and npm this morning and failed in installing appnium . I do not remember using sudo or not . As I have execute many commands today.   I have tried to uninstall/install several time ,still do not work .
## Environment
- Appium version (or git revision) that exhibits the issue: appium@1.5.3
- Desktop OS/version used to run Appium: OS X 10.11.15
- Node.js version (unless using Appium.app|exe):v6.2.1
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:
## Details

Here is the details of my terminate :
Last login: Sun Jun 12 16:42:05 on ttys003
tinas-mbp:~ baot$ npm uninstall appium -g
tinas-mbp:~ baot$ npm install -g appium

> appium@1.5.3 prepublish /Users/baot/appium
> gulp prepublish

sh: gulp: command not found

npm ERR! addLocal Could not install /Users/baot/appium
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! appium@1.5.3 prepublish: `gulp prepublish`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the appium@1.5.3 prepublish script 'gulp prepublish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp prepublish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/baot/npm-debug.log
tinas-mbp:~ baot$ npm -g --registry http://registry.cnpmjs.org  install appium

> appium@1.5.3 prepublish /Users/baot/appium
> gulp prepublish

sh: gulp: command not found

npm ERR! addLocal Could not install /Users/baot/appium
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "-g" "--registry" "http://registry.cnpmjs.org" "install" "appium"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! appium@1.5.3 prepublish: `gulp prepublish`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the appium@1.5.3 prepublish script 'gulp prepublish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp prepublish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/baot/npm-debug.log

**Comment by mykola-mokhnach** [comment]
Try to install gulp first:
```bash
npm -g install gulp
```

**Comment by baot20** [comment]
Hi mykola-mokhnach，

I have tried

**Comment by ChaitanyaQA** [comment]
Seems that you are using node v6.2.1, which is not a stable version. Please use v4.4.5 which is stable version

**Comment by Srilatha7** [comment]
I have a similar problem. I have tried to upgrade to Appium 1.6.0, but was not successful. So, I tried to uninstall and reinstall Appium again. Now Appium does not install through npm command. I want to downgrade to Appium 1.5.3 as 1.6 dmg file is not yet released.

Command used : npm install -g appium
Error log: 

> appium@1.6.0-beta3 prepublish /Users/srilathakondapalli/appium
> gulp prepublish

sh: gulp: command not found

npm ERR! addLocal Could not install /Users/srilathakondapalli/appium
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! appium@1.6.0-beta3 prepublish: `gulp prepublish`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the appium@1.6.0-beta3 prepublish script 'gulp prepublish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp prepublish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/srilathakondapalli/npm-debug.log

**Comment by imurchie** [comment]
That command should not be invoked when doing a global npm install. Neither should `appium@1.6.0-beta3` be what is installed. Are you sure that is the command you are using?

**Comment by Srilatha7** [comment]
I'm new to Appium. So tried to install with the help of posts here and something went wrong. Appium tool is installed correctly and the version is v1.5.3(Ara). But when I check the same in terminal with appium -v (or) appium version then it says "-bash: appium: command not found"

**Comment by imurchie** [comment]
The Appium GUI will not affect what is installed outside of it. So it will not be available through the terminal.

**Comment by SrinivasanTarget** [comment]
@triager please close
