### ISSUE TITLE
 Appium Selendroid could not do element.swipe

### ISSUE THREAD

**Issue by truebit** [appium/appium#6578]
## The problem

Appium Selendroid translated swipe action to unknown action for Selendroid
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable): n/a
- Desktop OS/version used to run Appium: mac osx 10.11
- Node.js version (unless using Appium.app|exe): 6.0.0
## Details

element swipe cannot be performed, proxy returned 404
error log below:

> 2016-06-13 17:22:58:684 - [MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: 404 - undefined
>     at doJwpProxy$ (lib/mjsonwp/mjsonwp.js:329:11)
>     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke](/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw](/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
> 2016-06-13 17:22:58:686 - [HTTP] <-- POST /wd/hub/session/151dd00f-f5f2-4fc4-97ff-491babc8bcc6/touch/perform 500 34 ms - 274 
## Link to Appium logs

https://gist.github.com/truebit/7b09a17b4d0c6cf4fa2abeaf95586ea9
## Code To Reproduce Issue [ Good To Have ]

No need

**Comment by mykola-mokhnach** [comment]
We have a workaround for it. This code is present in inherited AndroidDriver class:
```java
  private static int getNextCoord(double startC, double endC, double current,
                                    double duration) {
        return (int) Math.round(startC + (endC - startC) / duration * current);
    }

    public final static int SWIPE_STEP_DURATION_MILLISECONDS = 40;

    private void swipeViaTouchActions(int startx, int starty, int endx,
                                      int endy, int durationMilliseconds) {
        int duration = 1;
        if (durationMilliseconds > SWIPE_STEP_DURATION_MILLISECONDS) {
            duration = (durationMilliseconds % SWIPE_STEP_DURATION_MILLISECONDS == 0)
                    ? (durationMilliseconds / SWIPE_STEP_DURATION_MILLISECONDS)
                    : (durationMilliseconds / SWIPE_STEP_DURATION_MILLISECONDS + 1);
        }
        int current = 1;
        final TouchActions ta = new TouchActions(this);
        ta.down(startx, starty).perform();
        do {
            try {
                Thread.sleep(SWIPE_STEP_DURATION_MILLISECONDS);
            } catch (InterruptedException e) {
                Throwables.propagate(e);
            }
            ta.move(getNextCoord(startx, endx, current, duration),
                    getNextCoord(starty, endy, current, duration)).perform();
            current++;
        } while (current <= duration);
        ta.up(endx, endy).perform();
    }

    @Override
    public void swipe(int startx, int starty, int endx, int endy, int durationMilliseconds) {
        if (new DefaultArtifactVersion(androidOSVersion).compareTo(new DefaultArtifactVersion("4.3")) < 0) {
            // adb swipe command under 4.2 does not support duration parameter
            swipeViaTouchActions(startx, starty, endx, endy, durationMilliseconds);
            return;
        }

        final String adbCommand = String.format(ADB_PREFIX
                        + "adb shell input touchscreen swipe %d %d %d %d %d", startx,
                starty, endx, endy, durationMilliseconds);
        log.debug("ADB swipe: " + adbCommand);
        try {
            Runtime.getRuntime()
                    .exec(new String[]{"/bin/bash", "-c", adbCommand})
                    .waitFor();
        } catch (Exception e) {
            throw new WebDriverException(e.getMessage(), e);
        }
    }
```

**Comment by truebit** [comment]
@mykola-mokhnach Thanks! I will try it

**Comment by truebit** [comment]
Actually I found Selendroid contains [flick gesture](http://selendroid.io/gestures.html), the appium proxy should do that by translating actions to Selenddroid flick gesture.
