### ISSUE TITLE
Tests begin to fail in random place with "An unknown server-side error occurred while processing the command. Original error: Abnormal Instruments termination!" error

### ISSUE THREAD

**Issue by dmitrysolnikov** [appium/appium#6579]
## The problem

I am trying to execute full iOS test suite using Appium 1.5.2 on my real device. After some time all tests begin to fail with "An unknown server-side error occurred while processing the command. Original error: Abnormal Instruments termination!" error. Each time it's happening in different places at the begin of scenario(sometimes it could be 1 hour before fails and sometimes 15 minutes)
## Environment
- Appium 1.5.2
- OS X El Capitan v 10.11.5
- Node v0.12.14
- iOS 9.3.1
- iPad Air 2(real device)
- Appium CLI
## Link to Appium logs

https://gist.github.com/dmitrysolnikov/a5b6fdd45553c76df81caac34721caa0

**Comment by mykola-mokhnach** [comment]
> [debug] [Instruments] [INST] 2016-06-13 07:39:06 +0000 Fail: The target application appears to have died

I see this line before the abnormal instruments termination happens, which means that the application under test might just crashed there or became unresponsive. If true then it looks like normal behaviour.

**Comment by qamonstir** [comment]
It is not crashing manually and it is happening in different places. What could be the reason of that crash? Is there any way to avoid this crash? For example if it's crashed on one scenario it goes fine on following scenarios?

**Comment by dmitrysolnikov** [comment]
It is not crashing manually and it is happening in different places. What could be the reason of that crash? Is there any way to avoid this crash? For example if it's crashed on one scenario it goes fine on following scenarios?

**Comment by mykola-mokhnach** [comment]
You may restart driver session (or even restart Appium server itself) if such crash happens. We do it, for example, for each scenario. 
Although, this heavily depends on you scenario architecture. If the following test case depends on application state, created by previous one, then it would be hardly possible to implement this idea.
Also, carefully check the device logs - it is possible, that your application experiences memory leaks or race condition issues.  That is why it is not possible to detect these crashes manually.

**Comment by dmitrysolnikov** [comment]
Many thanks Mykola. How can I restart driver session before each scenario automatically? There is some parameter?

**Comment by mykola-mokhnach** [comment]
Call driver.quit() after each test and then driver = new IOSDriver() when a test starts. appium_java package also includes AppiumDriverLocalService wrapper class, which allows you to control Appium service state directly from your Java code.

**Comment by dmitrysolnikov** [comment]
Thank you one more time

**Comment by abhilashcae** [comment]
Hi,

I'm facing the exact same problem. I ran into this issue on almost all of the iOS devices (iPhone, iPad). Below are the scenarios where the tests fail:
Scenario 1:
When I close and relaunch the app using driver.close_app() and driver.launch_app(). driver.launch_app() throws this error in Appium.

Scenario 2:
When the app is backgrounded using driver.background_app(1)

@dmitrysolnikov - Is this resolved for you? If so, can you please share how you resolved it?

@jlipps @sebv - it would be great if you could throw some light on this.

**Comment by mykola-mokhnach** [comment]
> When I close and relaunch the app using driver.close_app() and driver.launch_app(). driver.launch_app() throws this error in Appium.

Unfortunately, this stuff is still buggy. I haven't heard anything so far about any updates on it.

> When the app is backgrounded using driver.background_app(1)

It is necessary to set **appName** capability properly to make this API call working as expected.

**Comment by abhilashcae** [comment]
It is necessary to set appName capability properly to make this API call working as expected.

appName capability is set properly. When I stop the Appium server and start again, it works for 1 or 2 times. Again it fails.

**Comment by knreddy036** [comment]
I am facing the same .Any work around for this issue .If we do quit and launch driver each time ,the execution increases more

**Comment by vikas-thange-twc** [comment]
I am also facing same issue while executing below code
,,,
		HashMap<String, Object> map = new HashMap<>();
		map.put("direction", "down");
		map.put("duration", 1);
		executor.executeScript("mobile: scroll", map);
,,,

The app is getting crashed on executor.executeScript()

I am using below environment 
iOS 9.3.1
Appium 1.5.3 (UI)
Java-Client 4.1.2

**Comment by anton-unity** [comment]
Confirm that happens quite a lot in random place
I'm using iOS 9.x, Appium (python binding) 1.5.3, iOS simulator

**Comment by imurchie** [comment]
Yes. Instruments likes to break.

**Comment by zhuchuji** [comment]
When I try with one real device, it works fine. But with two devices, I counter the same problem: one of the devices always terminate after execute a few tests. I use testng and my environment is:
Appium 1.5.3
Mac os x 10.12.1
real devices: iphone6(ios 9.3), iphone6s(ios 9.2)
I still have no idea of why it terminate and crash

**Comment by jlipps** [comment]
The message you saw means that either your app suffered a crash, or that instruments itself crashed. Unfortunately there's nothing Appium can do about that.

**Comment by qamonstir** [comment]
@jlipps is there any way to restart appium server after my application crashes? Because if it crashed all next scenarios will fail with next error - "A session is either terminated or not started (Selenium::WebDriver::Error::NoSuchDriverError)". How can I avoid this?

**Comment by zhuchuji** [comment]
You could create a new appium service or restart it with AppiumDriverLocalService or AppiumServiceBuilder class

**Comment by qamonstir** [comment]
@zhuchuji is there any examples on Ruby for this? I would like to implement it in my env.rb file(http://pastebin.com/PchaqFqw)

**Comment by zhuchuji** [comment]
@qamonstir Sorry. I work on Java...Never work with Ruby before

**Comment by vikramvi** [comment]
@dmitrysolnikov can you please share if you could get any workaround for this problem ?
