### ISSUE TITLE
Couldn't launch Appium session due to Error: 'java -version' failed

### ISSUE THREAD

**Issue by rajabhaskar** [appium/appium#6582]
## The problem

This is almost identical to the problem in #4229. However, in my case the solution provided there is already in place in my setup, yet I still have the problem.

I am on Windows 8.1 Pro
Have both %SystemRoot%\system32 and %SystemRoot% on my PATH variable
java location on my path variable and JAVA_HOME defined.

Yet when I try to start appium in the GUI with "Pre-Launch" application checked, I get 
error: Failed to start an Appium session, err was: Error: 'java -version' failed. Error: Command failed: C:\Windows\system32\cmd.exe /s /c "java -version"
## Environment
- Appium version: v1.4.16
- Desktop OS/version used to run Appium: Windows 8.1 Pro
- Node.js version (unless using Appium.app|exe): v6.2.1
- Mobile platform/version under test: Android 6.0
- Real device or emulator/simulator: Emulator
- Appium CLI or Appium.app|exe: I have installed Appium through npm and also downloaded appium.app from appium.io website.
## Details

java -version works fine in cmd.exe:

$ java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

@sebv I ran the command mentioned in #4229:

$ node -e "require('child_process').exec('java -version', function (err, stdout, stderr) { console.log(arguments); });"

which returns:
C:\Users\msi1370>node -e "require('child_process').exec('java -version', functio
n (err, stdout, stderr) { console.log(arguments); });"
{ '0': null,
  '1': '',
  '2': 'java version "1.8.0_92"\r\nJava(TM) SE Runtime Environment (build 1.8.0_
92-b14)\r\nJava HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)\r\n'
}

Also @sebv As per your suggestion in #4229, I have included "console.log("Env-->", process.env);" in C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-common.js at "androidCommon.getJavaVersion = function (cb)" function and inside the if(err){}  and got below log up on running my script. 
Can you please help me to get rid of this error. 
## Link to Appium logs

> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --app C:\Users\msi1370\Desktop\Envoy_02_06_2016.apk --app-activity com.envoy.world.MyWorldActivity --app-pkg com.envoy.world --platform-name Android --platform-version 23 --automation-name Appium --log-no-color
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"app":"C:\Users\msi1370\Desktop\Envoy_02_06_2016.apk","address":"127.0.0.1","logNoColors":true,"androidPackage":"com.envoy.world","androidActivity":"com.envoy.world.MyWorldActivity","platformName":"Android","platformVersion":"23","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\Users\msi1370\Desktop\Envoy_02_06_2016.apk","appPackage":"com.envoy.world","appActivity":"com.envoy.world.MyWorldActivity","platformVersion":"6.0","browserName":"android","platformName":"Android","version":"","deviceName":"Nexus 6","platform":"ANDROID","avd":"Android"}}
> info: Client User-Agent string: Apache-HttpClient/4.5.2 (Java/1.8.0_92)
> info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : version, platform
> info: [debug] Using local app from desired caps: C:\Users\msi1370\Desktop\Envoy_02_06_2016.apk
> info: [debug] Creating new appium session 526e5017-fd02-482b-8ea6-73cedd66896b
> info: Starting android appium
> info: [debug] Getting Java version
> Env--> { ALLUSERSPROFILE: 'C:\ProgramData',
>   ANDROID_SDK_HOME: 'C:\Users\msi1370\AppData\Local\Android',
>   APPDATA: 'C:\Users\msi1370\AppData\Roaming',
>   'asl.log': 'Destination=file',
>   CommonProgramFiles: 'C:\Program Files (x86)\Common Files',
>   'CommonProgramFiles(x86)': 'C:\Program Files (x86)\Common Files',
>   CommonProgramW6432: 'C:\Program Files\Common Files',
>   COMPUTERNAME: 'MSI-VIZ-DHP-046',
>   ComSpec: 'C:\Windows\system32\cmd.exe',
>   FP_NO_HOST_CHECK: 'NO',
>   HOMEDRIVE: 'C:',
>   HOMEPATH: '\Users\msi1370',
>   JAVA_HOME: 'C:\Program Files\Java\jdk1.8.0_92',
>   JRE_HOME: 'C:\Program Files\Java\jre1.8.0_92',
>   LOCALAPPDATA: 'C:\Users\msi1370\AppData\Local',
>   LOGONSERVER: '\\MSI-VIZAG-BDC01',
>   NUMBER_OF_PROCESSORS: '4',
>   OnlineServices: 'Online Services',
>   OS: 'Windows_NT',
>   Path: 'C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Windows\System32;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Java\jdk1.8.0_92\bin;\Users\msi1370\Local Settings\Application Data\Google\Chrome\Application\chrome.exe;E:\Rajabhaskar Workspace\maven\apache-maven-3.3.9\apache-maven\src\bin;C:\Users\msi1370\AppData\Local\Android\sdk\platform-tools;C:\Users\msi1370\AppData\Local\Android\sdk\platforms;C:\Users\msi1370\AppData\Local\Android\sdk\tools;C:\Program Files\nodejs;C:\php;C:\Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_modules\appium-selendroid-installer\selendroid\download;C:\Users\msi1370\AppData\Local\Android;C:\Ruby23-x64\bin;C:\ProgramData\Oracle\Java\javapath;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\iojs\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Java\jre1.8.0_73\bin;C:\Users\msi1370\AppData\Roaming\npm',
>   PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW',
>   Platform: 'BPC',
>   PROCESSOR_ARCHITECTURE: 'x86',
>   PROCESSOR_ARCHITEW6432: 'AMD64',
>   PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel',
>   PROCESSOR_LEVEL: '6',
>   PROCESSOR_REVISION: '3c03',
>   ProgramData: 'C:\ProgramData',
>   ProgramFiles: 'C:\Program Files (x86)',
>   'ProgramFiles(x86)': 'C:\Program Files (x86)',
>   ProgramW6432: 'C:\Program Files',
>   PSModulePath: 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\',
>   PTSMINSTALLPATH_X86: 'c:\Program Files (x86)\Hewlett-Packard\HP ProtectTools Security Manager\',
>   PUBLIC: 'C:\Users\Public',
>   SESSIONNAME: 'Console',
>   SystemDrive: 'C:',
>   SystemRoot: 'C:\Windows',
>   TEMP: 'C:\Users\msi1370\AppData\Local\Temp',
>   TMP: 'C:\Users\msi1370\AppData\Local\Temp',
>   USERDNSDOMAIN: 'VIZAG.MSI.LOCAL',
>   USERDOMAIN: 'VIZAG',
>   USERDOMAIN_ROAMINGPROFILE: 'VIZAG',
>   USERNAME: 'MSI1370',
>   USERPROFILE: 'C:\Users\msi1370',
>   windir: 'C:\Windows' }
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: 'java -version' failed. Error: Command failed: C:\Windows\system32\cmd.exe /s /c "java -version"
> 
> info: [debug] Error: 'java -version' failed. Error: Command failed: C:\Windows\system32\cmd.exe /s /c "java -version"
> 
> ```
> at [object Object].<anonymous> (C:\Program Files (x86)\Appium\node_modules\appium\lib\devices\android\android-common.js:1059:17)
> at ChildProcess.exithandler (child_process.js:758:5)
> at ChildProcess.emit (events.js:110:17)
> at maybeClose (child_process.js:1016:16)
> at Socket.<anonymous> (child_process.js:1184:11)
> at Socket.emit (events.js:107:17)
> at Pipe.close (net.js:484:11)
> ```
> 
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: 'java -version' failed. Error: Command failed: C:\Windows\system32\cmd.exe /s /c \"java -version\"\n)","origValue":"'java -version' failed. Error: Command failed: C:\Windows\system32\cmd.exe /s /c \"java -version\"\n"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 115.806 ms - 328 
## Code To Reproduce Issue [ Good To Have ]

AndroidDriver driver =  new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

**Comment by mykola-mokhnach** [comment]
It might be, that you execute Appium before PATH environment variable is initialised properly, because by default exec command inherits the environment from the parent process, which is node.exe in our case. Open new cmd console, make sure that the current path to java.exe is present in PATH (by typing _SET | more_) and execute Appium from there. Then try to create the driver.

**Comment by rajabhaskar** [comment]
@mykola-mokhnach Thanks for the quick turnaround. I have closed the cmd console and opened a new one. --> verified PATH and confirmed that it represents correct path to java.exe i.e. "C:\Program Files\Java\jdk1.8.0_92\bin"
Then I started Appium from cmd using command "Appium" and once I see the response "**C:\Users\msi1370>appium
[Appium] Welcome to Appium v1.5.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723**" then I created AndroidDriver .. Below is the error log I have got

##Error Log:_________________________________________________
C:\Users\msi1370>appium
[Appium] Welcome to Appium v1.5.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Users\\msi137
0\\Desktop\\Envoy_02_06_2016.apk","appPackage":"com.envoy.world","appActivity":"
com.envoy.world.MyWorldActivity","platformVersion":"6.0","browserName":"android"
,"platformName":"Android","version":"","deviceName":"Nexus 6","platform":"ANDROI
D","avd":"Android"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"C:\\Users\\ms
i1370...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   app: 'C:\\Users\\msi1370\\Desktop\\Envoy_02_06_2016.apk'
[Appium]   appPackage: 'com.envoy.world'
[Appium]   appActivity: 'com.envoy.world.MyWorldActivity'
[Appium]   platformVersion: '6.0'
[Appium]   browserName: 'android'
[Appium]   platformName: 'Android'
[Appium]   version: ''
[Appium]   deviceName: 'Nexus 6'
[Appium]   platform: 'ANDROID'
[Appium]   avd: 'Android'
[BaseDriver] The following capabilities were provided, but are not recognized by
 appium: version, platform.
[AndroidDriver] The desired capabilities should generally not include both an ap
p and a browser
[BaseDriver] Session created with session id: 6129c38d-1aaa-4f12-8ed0-d80db78372
66
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_92
[ADB] Checking whether adb is present
[ADB] The ANDROID_HOME environment variable is not set to the Android SDK root d
irectory path. ANDROID_HOME is required for compatibility with SDK 23+. Checking
 along PATH for adb.
[ADB] Using adb from C:\Users\msi1370\AppData\Local\Android\sdk\platform-tools\a
db.exe

[debug] [ADB] Trying to find Android emulator
[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[ADB] Error: Error while getting connected devices. Original error: Command 'C:\
\Users\\msi1370\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe devices'
exited with code 3221225477
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:118:9)
    at tryCatch (C:\Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_m
odules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\msi1370\AppData\
Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.j
s:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\
Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime
\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\msi1370\AppData\Roaming\npm\n
ode_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Error while getting connected devices. Original error: Command 'C:\\User
s\\msi1370\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe devices' exite
d with code 3221225477
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:118:9)
    at tryCatch (C:\Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_m
odules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\msi1370\AppData\
Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.j
s:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\
Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime
\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\msi1370\AppData\Roaming\npm\n
ode_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[ADB] Error: Error getting emulators. Original error: Error while getting connec
ted devices. Original error: Command 'C:\\Users\\msi1370\\AppData\\Local\\Androi
d\\sdk\\platform-tools\\adb.exe devices' exited with code 3221225477
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:263:9)
    at tryCatch (C:\Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_m
odules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\msi1370\AppData\
Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.j
s:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\
Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime
\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\msi1370\AppData\Roaming\npm\n
ode_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Error getting emulators. Original error: Error while getting connected d
evices. Original error: Command 'C:\\Users\\msi1370\\AppData\\Local\\Android\\sd
k\\platform-tools\\adb.exe devices' exited with code 3221225477
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:263:9)
    at tryCatch (C:\Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_m
odules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\msi1370\AppData\
Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.j
s:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\
Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime
\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\msi1370\AppData\Roaming\npm\n
ode_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[ADB] Error: Error getting AVD. Original error: Error getting emulators. Origina
l error: Error while getting connected devices. Original error: Command 'C:\\Use
rs\\msi1370\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe devices' exit
ed with code 3221225477
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:305:9)
    at tryCatch (C:\Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_m
odules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\msi1370\AppData\
Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.j
s:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\
Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime
\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\msi1370\AppData\Roaming\npm\n
ode_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Error getting AVD. Original error: Error getting emulators. Original err
or: Error while getting connected devices. Original error: Command 'C:\\Users\\m
si1370\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe devices' exited wi
th code 3221225477
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:305:9)
    at tryCatch (C:\Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_m
odules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\msi1370\AppData\
Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.j
s:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\
Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime
\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\msi1370\AppData\Roaming\npm\n
ode_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [AndroidDriver] Shutting down Android driver
[AndroidDriver] Cannot shut down Android driver; it has already shut down
[MJSONWP] Encountered internal error running command: Error: Error getting AVD.
Original error: Error getting emulators. Original error: Error while getting con
nected devices. Original error: Command 'C:\\Users\\msi1370\\AppData\\Local\\And
roid\\sdk\\platform-tools\\adb.exe devices' exited with code 3221225477
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:305:9)
    at tryCatch (C:\Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_m
odules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\msi1370\AppData\
Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.j
s:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (C:\
Users\msi1370\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime
\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\msi1370\AppData\Roaming\npm\n
ode_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 385 ms - 403
__________________________________________________________________________

**Comment by mykola-mokhnach** [comment]
There is some problem with adb tool, which cannot get a list of connected devices. Try googling the error:
adb exited with code 3221225477
For me it seems that the tool itself is somehow corrupted and I'd try reinstalling it, or installing different SDKs.

**Comment by rajabhaskar** [comment]
I have already tried to reinstall the Android SDK and also I have tried downloading plateform-tools separately and replaced it in SDK folder. nothing solved this error with adb.exe. 
I have googled this but got no proper solution and that's the reason I have posted it as a new issue here.

**Comment by mykola-mokhnach** [comment]
The error you get from ADB means ACCESS_VIOLATION (SEGFAULT analogue in *nix systems). This means adb crashes while trying to get the information about connected devices. I'd try to remove all connected devices/emulators first and see whether it shows empty list properly. Then try to test with real device first or Genymotion simulator. If this works then try to create different types of devices (not all of them at the same time, but rather one after another) using avd and check if adb can list them.

**Comment by rajabhaskar** [comment]
I was unable to run "adb devices" from command line as it's throwing me error popup "adb.exe Stopped working". I have deleted all my AVDs and disconnected all my real devices then I ran adb devices which resulted this pop up. 
Also I have installed "qt-opensource-windows-x86-msvc2015_64-5.6.1.exe" and when I double click on it, it's not installing anything in my machine and being idle. I have 64bit system and I have downloaded the corresponding version only. Please advise. 




![image](https://cloud.githubusercontent.com/assets/18653701/16039036/564f92ea-3245-11e6-977c-f5e9676a43d5.png)

**Comment by jlipps** [comment]
Closing since this is an issue with the adb install on your system, not with appium.
