### ISSUE TITLE
Appium - adb devices not working

### ISSUE THREAD

**Issue by rajabhaskar** [appium/appium#6583]
## The problem

After installation of Appium I tried to run "adb devices" from platform-tools folder - then I got an error saying "adb stopped working". I tried to download Android SDK tools separately and replaced the tools folder with newly downloaded one but results the same error. 
Here are my other findings:
1. When I double click on "emulator-crash-service" it error out with message "Qt5Core.dll" is missing
2. When I run a sample program from IntelliJ with all necessary configurations, the program errorout with "Error:(42, 23) java: cannot access org.openqa.selenium.remote.http.HttpClient class file for org.openqa.selenium.remote.http.HttpClient not found"
3. The AVD's that I have created in Android studio are not being displayed in Appium client(Appium.app) -->Android settings -->Launch AVD dropdown.

These may not be related to a single issue, but just thought like this might give you some clue on what is happening. Thank you so much

## Environment

Appium version: v1.4.16
Desktop OS/version used to run Appium: Windows 8.1 Pro
Node.js version (unless using Appium.app|exe): v6.2.1
Mobile platform/version under test: Android 6.0
Real device or emulator/simulator: Emulator
Appium CLI or Appium.app|exe: I have installed Appium through npm and also downloaded appium.app from appium.io website.

![image](https://cloud.githubusercontent.com/assets/18653701/16032495/dd2cb4fe-3223-11e6-98ac-2c7f0a789c77.png)

**Comment by mykola-mokhnach** [comment]
> 1. When I double click on "emulator-crash-service" it error out with message "Qt5Core.dll" is missing
This file is a part of QT SDK v5. Try to download and install it from https://www.qt.io/download/

> 2. When I run a sample program from IntelliJ with all necessary configurations, the program errorout with "Error:(42, 23) java: cannot access org.openqa.selenium.remote.http.HttpClient class file for org.openqa.selenium.remote.http.HttpClient not found"

Make sure you have all the necessary modules included into your maven/gradle config. There should be at least (in case of Maven):
```xml
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
```
and 
```xml
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
```

**Comment by rajabhaskar** [comment]
@mykola-mokhnach I have the maven dependencies already. below is my pom.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.envoyworld</groupId>
    <artifactId>cucumber</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>2.47.0</version>
        </dependency>
        <dependency>
            <groupId>io.appium</groupId>
            <artifactId>java-client</artifactId>
            <version>3.4.1</version>
        </dependency>
        
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>1.2.4</version>
        </dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>1.2.4</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.2</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20080701</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.skyscreamer</groupId>
            <artifactId>jsonassert</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.fge</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>
        <dependency>
         <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.2.4</version>
        </dependency>
        <dependency>
            <groupId>com.codesnippets4all</groupId>
            <artifactId>quick-json</artifactId>
            <version>1.0.4</version>
        </dependency>
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>1.8.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-htmlunit-driver</artifactId>
            <version>2.47.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>

**Comment by mykola-mokhnach** [comment]
It should be enough to just install the SDK and reboot the PC. If the error still exists then try to add the folder, where this dll persists, to your system PATH.
Regarding Java error - try to clean and build you project with maven command line tool. Probably, something is broken in IDE configuration.

**Comment by SrinivasanTarget** [comment]
@triager please close
