### ISSUE TITLE
Appium routing request "touch/perform" to Selendroid makes all TouchAction implemented actions not work

### ISSUE THREAD

**Issue by truebit** [appium/appium#6585]
## The problem

Appium routing request "touch/perform" to Selendroid makes all TouchAction implemented actions not work, such like swipe, longpress and dragAndDrop
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable): n/a
- Desktop OS/version used to run Appium: mac osx 10.11
- Node.js version (unless using Appium.app|exe): 6.0.0
## Details

using appium java-client: 4.0.0
element swipe cannot be performed, it uses `AndroidDriver.doSwipe` which uses `TouchAction` to perform. refer to #6578 
this also happens in longpress with code `new TouchAction(driver).longPress(element).release().perform();`
- this two actions are performed by `TouchAction`, the underlying request is `/wd/hub/session/:sessionId/touch/perform`, this request could not be recognized by Selendroid.
- in [appium-selendroid-driver  `NO_PROXY`](https://github.com/appium/appium-selendroid-driver/blob/master/lib/driver.js#L27), this request is not excluded.
- but in [selendroid server](https://github.com/selendroid/selendroid/blob/master/selendroid-server/src/main/java/io/selendroid/server/AndroidServlet.java#L55), `touch/perform` request is not implemented
## Link to Appium logs

https://gist.github.com/truebit/7b09a17b4d0c6cf4fa2abeaf95586ea9
## Code To Reproduce Issue [ Good To Have ]

`new TouchAction(driver).longPress(element).release().perform();`
`((MobileElement) element).swipe(SwipeElementDirection.UP, durationMs);`

**Comment by mykola-mokhnach** [comment]
Try to use org.openqa.selenium.interactions.touch.TouchActions instead

**Comment by mykola-mokhnach** [comment]
But I prefer doing log tap with adb - IMHO it's more stable. Just provide equal start and end coordinates:
```bash
adb shell input touchscreen swipe <x> <y> <x> <y> <durationMs>
```

**Comment by truebit** [comment]
@mykola-mokhnach Yep, now I reimplemented swipe and longpress using adb in my wrapper driver. But I think this is just a workaround. This issue itself is a design missing point

**Comment by truebit** [comment]
@mykola-mokhnach `TouchActions` does not work for `longpress` action, it would throw exception:
> java.lang.ClassCastException: io.appium.java_client.android.AndroidDriver cannot be cast to org.openqa.selenium.interactions.HasTouchScreen
> 
> 	at org.openqa.selenium.interactions.touch.TouchActions.<init>(TouchActions.java:38)
> 	at com.changba.cabbie.impl.AppiumCabbie.longPressOnElement(AppiumCabbie.java:173)
> 	at com.changba.mobile.uitest.pages.MyChangbaPage.cancelFavWork(MyChangbaPage.java:97)
> 	at com.changba.mobile.uitest.tests.MyChangbaPageTest.afterMethod(MyChangbaPageTest.java:116)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
> 	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
> 	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
> 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
> 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
> 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
> 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
> 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:782)
> 	at org.testng.TestRunner.run(TestRunner.java:632)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
> 	at org.testng.TestNG.run(TestNG.java:1064)
> 	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
> 	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)

**Comment by mykola-mokhnach** [comment]
@truebit sorry, forgot to mention one important thing:
```java
public class MyAndroidDriver extends AndroidDriver<WebElement> implements ZetaDriver, HasTouchScreen {
    private RemoteTouchScreen touch;

    public MyAndroidDriver(URL remoteAddress, Capabilities desiredCapabilities) {
        super(remoteAddress, desiredCapabilities);
        this.touch = new RemoteTouchScreen(getExecuteMethod());
    }

    private void swipeViaTouchActions(int startx, int starty, int endx,
                                      int endy, int durationMilliseconds) {
        int duration = 1;
        if (durationMilliseconds > SWIPE_STEP_DURATION_MILLISECONDS) {
            duration = (durationMilliseconds % SWIPE_STEP_DURATION_MILLISECONDS == 0)
                    ? (durationMilliseconds / SWIPE_STEP_DURATION_MILLISECONDS)
                    : (durationMilliseconds / SWIPE_STEP_DURATION_MILLISECONDS + 1);
        }
        int current = 1;
        final TouchActions ta = new TouchActions(this);
        ta.down(startx, starty).perform();
        ....
    }
}
```

**Comment by SrinivasanTarget** [comment]
@triager please label: Bug, Selendroid
