### ISSUE TITLE
Real device is not find by instrument

### ISSUE THREAD

**Issue by CapDam** [appium/appium#6586]
Hi, 

Appium does not recognize my real device (iPhone 6S Plus):

> node . --default-capabilities '{"platformName":"IOS"}' --default-capabilities '{"platformVersion":"9.3.2"}' --default-capabilities '{"browserName":"Safari"}' --default-capabilities '{"launchTimeout":20000}' --default-capabilities '{"udid":"b08d743e4c8acc04d2ba4adf16b460916d54ae0e"}' --default-capabilities '{"noReset":true}' --default-capabilities '{"nativeInstrumentsLib":true}'
[Appium] Welcome to Appium v1.5.3 (REV 1b86d0cba9b645d4a2fb1e9c083d492388d4f147)
[Appium] Non-default server args:
[Appium]   defaultCapabilities: { nativeInstrumentsLib: true }
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   nativeInstrumentsLib: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"9.3","deviceName":"b08d743e4c8acc04d2ba4adf16b460916d54ae0e","browserName":"Safari","platformName":"IOS"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformVersion":"9.3","...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   platformVersion: '9.3'
[Appium]   deviceName: 'b08d743e4c8acc04d2ba4adf16b460916d54ae0e'
[Appium]   browserName: 'Safari'
[Appium]   platformName: 'IOS'
[Appium]   nativeInstrumentsLib: true
[BaseDriver] Session created with session id: f00e6e65-0a6b-4149-9ed1-8caf478101f9
[debug] [iOS] Not auto-detecting udid.
[debug] [iOS] We are on iOS8+ so not copying Safari app
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /var/folders/dr/547_pknn7wg422cb7yzt7k740000gn/T/instruments_sock
[debug] [iOS] Setting Xcode version
[debug] [iOS] Xcode version set to 7.3.1
[debug] [iOS] Setting iOS SDK Version
[debug] [iOS] iOS SDK Version set to 9.3
[debug] [iOS] Checking whether instruments supports our device string
[debug] [Instruments] Getting list of devices instruments supports
[debug] [Instruments] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
[debug] [Instruments] Available devices: Apple TV 1080p (9.2) [A4560DCA-9F32-4ED7-9BF1-A24EE277B66B] (Simulator),iPad 2 (9.3) [68D54A28-AE03-46A9-88DA-08C42ED3FD80] (Simulator),iPad Air (9.3) [53AABC5F-316C-40AC-B7D4-EEC3B17692C4] (Simulator),iPad Air 2 (9.3) [43D3C265-E5FF-4DCA-930E-38D3343A13FD] (Simulator),iPad Pro (9.3) [980C59B7-DE39-4AA8-8005-85F79D781417] (Simulator),iPad Retina (9.3) [709A8FE8-7741-4D7B-B10C-8CE34545E1E4] (Simulator),iPhone 4s (9.3) [318F5CB8-C11A-4637-9005-C137DCA8FDE0] (Simulator),iPhone 5 (9.3) [7AC2457B-4716-4642-94D6-09694C45CFAE] (Simulator),iPhone 5s (9.3) [00272D14-1A38-4482-ABEF-FA7E241EB4F8] (Simulator),iPhone 6 (9.3) [43F0C14F-AB7C-428B-839D-5AE7C181758E] (Simulator),iPhone 6 Plus (9.3) [F0C394DF-C50F-4C1F-9ED5-92BE69933BE7] (Simulator),iPhone 6s (9.3) [01FEB9F3-F870-470E-B9FE-EA3D577A0A4E] (Simulator),iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [AF9FCBF1-8B19-41F0-88B4-78AE330B3B17] (Simulator),iPhone 6s Plus (9.3) [D72CC7E6-F0E7-4875-B884-6D1B3D65094B] (Simulator),iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [BA7ECE98-06AE-41CC-91E5-E75CAF73160A] (Simulator)
[iOSSim] Retrieving device name string for Xcode version 7.3.1
[debug] [iOSSim] Getting device string from options: {"deviceName":"b08d743e4c8acc04d2ba4adf16b460916d54ae0e","platformVersion":"9.3","forceIphone":false,"forceIpad":false}
[debug] [iOSSim] Final device string is 'b08d743e4c8acc04d2ba4adf16b460916d54ae0e (9.3)'
[iOS] Error: Could not find a device to launch. You requested 'b08d743e4c8acc04d2ba4adf16b460916d54ae0e (9.3)', but the available devices were: ["Apple TV 1080p (9.2) [A4560DCA-9F32-4ED7-9BF1-A24EE277B66B] (Simulator)","iPad 2 (9.3) [68D54A28-AE03-46A9-88DA-08C42ED3FD80] (Simulator)","iPad Air (9.3) [53AABC5F-316C-40AC-B7D4-EEC3B17692C4] (Simulator)","iPad Air 2 (9.3) [43D3C265-E5FF-4DCA-930E-38D3343A13FD] (Simulator)","iPad Pro (9.3) [980C59B7-DE39-4AA8-8005-85F79D781417] (Simulator)","iPad Retina (9.3) [709A8FE8-7741-4D7B-B10C-8CE34545E1E4] (Simulator)","iPhone 4s (9.3) [318F5CB8-C11A-4637-9005-C137DCA8FDE0] (Simulator)","iPhone 5 (9.3) [7AC2457B-4716-4642-94D6-09694C45CFAE] (Simulator)","iPhone 5s (9.3) [00272D14-1A38-4482-ABEF-FA7E241EB4F8] (Simulator)","iPhone 6 (9.3) [43F0C14F-AB7C-428B-839D-5AE7C181758E] (Simulator)","iPhone 6 Plus (9.3) [F0C394DF-C50F-4C1F-9ED5-92BE69933BE7] (Simulator)","iPhone 6s (9.3) [01FEB9F3-F870-470E-B9FE-EA3D577A0A4E] (Simulator)","iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [AF9FCBF1-8B19-41F0-88B4-78AE330B3B17] (Simulator)","iPhone 6s Plus (9.3) [D72CC7E6-F0E7-4875-B884-6D1B3D65094B] (Simulator)","iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [BA7ECE98-06AE-41CC-91E5-E75CAF73160A] (Simulator)"]
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at noDevicesError (lib/driver.js:912:14)
    at IosDriver.checkSimAvailable$ (lib/driver.js:917:9)
    at tryCatch (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not find a device to launch. You requested 'b08d743e4c8acc04d2ba4adf16b460916d54ae0e (9.3)', but the available devices were: ["Apple TV 1080p (9.2) [A4560DCA-9F32-4ED7-9BF1-A24EE277B66B] (Simulator)","iPad 2 (9.3) [68D54A28-AE03-46A9-88DA-08C42ED3FD80] (Simulator)","iPad Air (9.3) [53AABC5F-316C-40AC-B7D4-EEC3B17692C4] (Simulator)","iPad Air 2 (9.3) [43D3C265-E5FF-4DCA-930E-38D3343A13FD] (Simulator)","iPad Pro (9.3) [980C59B7-DE39-4AA8-8005-85F79D781417] (Simulator)","iPad Retina (9.3) [709A8FE8-7741-4D7B-B10C-8CE34545E1E4] (Simulator)","iPhone 4s (9.3) [318F5CB8-C11A-4637-9005-C137DCA8FDE0] (Simulator)","iPhone 5 (9.3) [7AC2457B-4716-4642-94D6-09694C45CFAE] (Simulator)","iPhone 5s (9.3) [00272D14-1A38-4482-ABEF-FA7E241EB4F8] (Simulator)","iPhone 6 (9.3) [43F0C14F-AB7C-428B-839D-5AE7C181758E] (Simulator)","iPhone 6 Plus (9.3) [F0C394DF-C50F-4C1F-9ED5-92BE69933BE7] (Simulator)","iPhone 6s (9.3) [01FEB9F3-F870-470E-B9FE-EA3D577A0A4E] (Simulator)","iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [AF9FCBF1-8B19-41F0-88B4-78AE330B3B17] (Simulator)","iPhone 6s Plus (9.3) [D72CC7E6-F0E7-4875-B884-6D1B3D65094B] (Simulator)","iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [BA7ECE98-06AE-41CC-91E5-E75CAF73160A] (Simulator)"]
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at noDevicesError (lib/driver.js:912:14)
    at IosDriver.checkSimAvailable$ (lib/driver.js:917:9)
    at tryCatch (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: Could not find a device to launch. You requested 'b08d743e4c8acc04d2ba4adf16b460916d54ae0e (9.3)', but the available devices were: ["Apple TV 1080p (9.2) [A4560DCA-9F32-4ED7-9BF1-A24EE277B66B] (Simulator)","iPad 2 (9.3) [68D54A28-AE03-46A9-88DA-08C42ED3FD80] (Simulator)","iPad Air (9.3) [53AABC5F-316C-40AC-B7D4-EEC3B17692C4] (Simulator)","iPad Air 2 (9.3) [43D3C265-E5FF-4DCA-930E-38D3343A13FD] (Simulator)","iPad Pro (9.3) [980C59B7-DE39-4AA8-8005-85F79D781417] (Simulator)","iPad Retina (9.3) [709A8FE8-7741-4D7B-B10C-8CE34545E1E4] (Simulator)","iPhone 4s (9.3) [318F5CB8-C11A-4637-9005-C137DCA8FDE0] (Simulator)","iPhone 5 (9.3) [7AC2457B-4716-4642-94D6-09694C45CFAE] (Simulator)","iPhone 5s (9.3) [00272D14-1A38-4482-ABEF-FA7E241EB4F8] (Simulator)","iPhone 6 (9.3) [43F0C14F-AB7C-428B-839D-5AE7C181758E] (Simulator)","iPhone 6 Plus (9.3) [F0C394DF-C50F-4C1F-9ED5-92BE69933BE7] (Simulator)","iPhone 6s (9.3) [01FEB9F3-F870-470E-B9FE-EA3D577A0A4E] (Simulator)","iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [AF9FCBF1-8B19-41F0-88B4-78AE330B3B17] (Simulator)","iPhone 6s Plus (9.3) [D72CC7E6-F0E7-4875-B884-6D1B3D65094B] (Simulator)","iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [BA7ECE98-06AE-41CC-91E5-E75CAF73160A] (Simulator)"]
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at noDevicesError (lib/driver.js:912:14)
    at IosDriver.checkSimAvailable$ (lib/driver.js:917:9)
    at tryCatch (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/Damien/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 1646 ms - 1403 

But when I do "instruments -s devices", I get:

> Last login: Tue Jun 14 12:33:17 on console
$ instruments -s devices
Known Devices:
2016-06-14 12:33:42.823 instruments[420:4340] WebKit Threading Violation - initial use of WebKit from a secondary thread.
MacBook  [8B3FCF1E-A5DA-5AB0-8782-3A0FA7C8EC3E]
iPhone Test (9.3.2) [b08d743e4c8acc04d2ba4adf16b460916d54ae0e]
Apple TV 1080p (9.2) [A4560DCA-9F32-4ED7-9BF1-A24EE277B66B] (Simulator)
iPad 2 (9.3) [68D54A28-AE03-46A9-88DA-08C42ED3FD80] (Simulator)
iPad Air (9.3) [53AABC5F-316C-40AC-B7D4-EEC3B17692C4] (Simulator)
iPad Air 2 (9.3) [43D3C265-E5FF-4DCA-930E-38D3343A13FD] (Simulator)
iPad Pro (9.3) [980C59B7-DE39-4AA8-8005-85F79D781417] (Simulator)
iPad Retina (9.3) [709A8FE8-7741-4D7B-B10C-8CE34545E1E4] (Simulator)
iPhone 4s (9.3) [318F5CB8-C11A-4637-9005-C137DCA8FDE0] (Simulator)
iPhone 5 (9.3) [7AC2457B-4716-4642-94D6-09694C45CFAE] (Simulator)
iPhone 5s (9.3) [00272D14-1A38-4482-ABEF-FA7E241EB4F8] (Simulator)
iPhone 6 (9.3) [43F0C14F-AB7C-428B-839D-5AE7C181758E] (Simulator)
iPhone 6 Plus (9.3) [F0C394DF-C50F-4C1F-9ED5-92BE69933BE7] (Simulator)
iPhone 6s (9.3) [01FEB9F3-F870-470E-B9FE-EA3D577A0A4E] (Simulator)
iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [AF9FCBF1-8B19-41F0-88B4-78AE330B3B17] (Simulator)
iPhone 6s Plus (9.3) [D72CC7E6-F0E7-4875-B884-6D1B3D65094B] (Simulator)
iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [BA7ECE98-06AE-41CC-91E5-E75CAF73160A] (Simulator)

**Comment by imurchie** [comment]
Do _not_ specify `deviceName` as `b08d743e4c8acc04d2ba4adf16b460916d54ae0e`.

**Comment by CapDam** [comment]
How I do to a real device??
 thank you

**Comment by imurchie** [comment]
specify the `udid` in your desired capabilities and it should use the real device.

**Comment by sayali0710** [comment]
Same issue any one resolved this?

**Comment by smccarthy** [comment]
@sayali0710 If it is the same issue, specify the UDID in your desired capabilities.

**Comment by SrinivasanTarget** [comment]
@triager please close
