### ISSUE TITLE
Names for images not appearing in Appium inspector

### ISSUE THREAD

**Issue by s-sridevi15** [appium/appium#6590]
## The problem

   I am working on automating IONIC/Hydbrid apps using Appium. Some of the images does not have names, so I have added names for for html tags
<ion-option-button class="share" name="share" on-tap="browse.shareLink($event, file)" id="secondary"> 

and I have build app for ios using xcode and when I run app through automation , Appium inspector does not show name . I tried adding id and it did not worked.

Having names for images are useful as xpaths are keep changing and having hard time to automate tests without having names for images. 
## Environment
- Appium version - 1.5.2
- Mobile platform/version under test: IOS
- Real device or emulator/simulator: Real Device

I appreciate if somebody can help

**Comment by SrinivasanTarget** [comment]
@triager please close
