### ISSUE TITLE
Unable to select Date Picker in android using Appium

### ISSUE THREAD

**Issue by testingmobileautomation** [appium/appium#6591]
## The problem

I'm unable to select the date-picker in an android device using appium.
I have tried three ways but still am unable to change.
Kindly suggest me how do I proceed in this.
## Details

I have tried using the Xpath, the inspector is inspecting the element but it is not altering the values I provided through .sendkeys.
So, kindly if there's any suggestions please pass it, so that it helps me to move forward.
## Code To Reproduce Issue

![datepicker](https://cloud.githubusercontent.com/assets/19967595/16106526/c213c442-33b2-11e6-93f9-a5900c226d66.jpg)

**Try #1**
((AndroidElement)(driver.findElementByXPath("//android.widget.NumberPicker[@index='0']//android.widget.Button[@index=0]"))).tap(1, 2);
        ((AndroidElement)(driver.findElementByXPath("//android.widget.NumberPicker[@index='1']//android.widget.Button[@index=0]"))).tap(1, 2);
        ((AndroidElement)(driver.findElementByXPath("//android.widget.NumberPicker[@index='2']//android.widget.Button[@index=0]"))).tap(1, 2);

**Try #2**
List<WebElement> pick = driver.findElements(By.className("android.widget.EditText"));
             pick.get(0).sendKeys("24");;
             pick.get(1).sendKeys("5");
             pick.get(2).sendKeys("1991");

**Try #3** 
driver.findElement(By.xpath("//android.widget.NumberPicker[@index='0']")).sendKeys("5");
             driver.findElement(By.xpath("//android.widget.NumberPicker[@index='1']")).sendKeys("5");
             driver.findElement(By.xpath("//android.widget.NumberPicker[@index='2']")).sendKeys("1990")

**Comment by kasirga32** [comment]
Are you sure date picker fields are editable? Because app developer can disable it.

**Comment by testingmobileautomation** [comment]
@kasirga32 yes it is editable. So any suggestions ??

![capture](https://cloud.githubusercontent.com/assets/19967595/16110291/b30e2a1a-33ca-11e6-92e8-154b8be45511.JPG)

**Comment by kasirga32** [comment]
You can try first click to EditText then send keys to it.

**Comment by testingmobileautomation** [comment]
@kasirga32  i tried it, check Try #3 but it not working.

**Comment by amedvedjev** [comment]
same problem. we solved it by doing scroll and check value. when value is needed -> stop scroll of needed wheel.

**Comment by sankritraj** [comment]
doesn't using @Index work for xpath?. Try it once by auto generated path.

**Comment by testingmobileautomation** [comment]
@sankritraj
Sorry, I'm unable to get send keys using @index also. Any other suggestions ?

**Comment by sankritraj** [comment]
@testingmobileautomation What i am trying to say here, The xpath 'driver.findElement(By.xpath("//android.widget.NumberPicker[@index='0']")).sendKeys("5");' you using is correct?

Try the xpath automatically generated by inspector or uiautomator

**Comment by VictorAPI** [comment]
@here 
The following solution works for me:

Try #4
driver.findElement(By.xpath("//android.widget.NumberPicker[@index='0']")).setValue("May");
driver.findElement(By.xpath("//android.widget.NumberPicker[@index='1']")).sendKeys("5");
driver.findElement(By.xpath("//android.widget.NumberPicker[@index='2']")).sendKeys("1990");
