### ISSUE TITLE
Thanks for the update, but I really need the name strategy, what else can I do if there is no ID?

### ISSUE THREAD

**Issue by zsinghua** [appium/appium#6593]
Thanks for the update, but I really need the name strategy, what else can I do if there is no ID?
I noticed the change in Android from last release, now it comes to iOS even.
Should I really go with class names + index? And even ID + index? That is really painful.

**Comment by mykola-mokhnach** [comment]
Just replace all the By.name locators with MobileBy.AccessibilityId
The strategy has not been removed completely - it was just renamed.

**Comment by SrinivasanTarget** [comment]
@triager please close
