### ISSUE TITLE
Sendkey sends extra character in password field

### ISSUE THREAD

**Issue by rmittal01** [appium/appium#6594]
## The problem

I created a simple Appium script for successful Login scenario. 
following is the code for the Test
List<WebElement> textFieldsList = driver.findElements(By.className("android.widget.EditText"));
	 textFieldsList.get(0).sendKeys("racv_rm1");
	 textFieldsList.get(1).sendKeys("test1234");
 WebElement login=driver.findElement(By.id("racv_login"));
	 login.click();
when I run this test, it enters correct value in username field, but in password field it enters "test12346".
No matter what I change the password value in the sendKey command, it appends a "6" to it.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Windows 7 Pro
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Samsung Galaxy S6 (Lollipop 5.0)
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Can you provide Appium log? 
Is it possible, that login button is covered by on-screen keyboard and it taps a keyboard key instead of the button itself (hiding the keyboard might help to solve the problem if this is true)?

**Comment by rmittal01** [comment]
Thanks,

Keyboard overlap was the problem.

Thanks again,
Ruchika


*Regards*
Ruchika Mittal
Mob-0407661017

**Comment by saviommoreira** [comment]
Hi Ruchika,
I got the same problem here.
Could you share your solution?

Regards
Moreira
