### ISSUE TITLE
Record feature of inspector is no longer working.

### ISSUE THREAD

**Issue by codiophile** [appium/appium#6598]
## The problem

I cannot get the inspector to interact with UI elements. Maybe because it is still using the name strategy to locate the elements, which is no longer supported. Not sure if that is the only issue, but it is for sure one of the issues.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.2 and 1.5.3
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: Mac OS X 10.11.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 9.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium.app is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by geek154** [comment]
Facing Similar Problem. (url:https://github.com/appium/appium/issues/6595)

Were you able to launch simulator and get the app installed successfully?

**Comment by codiophile** [comment]
On 1.5.2 no, but on 1.5.3 yes.

**Comment by geek154** [comment]
It isn't working for me on 1.5.3 either.

**Comment by SrinivasanTarget** [comment]
@codiophile Please log it here: https://github.com/appium/appium-dot-app/issues Thanks

**Comment by SrinivasanTarget** [comment]
@triager please close
