### ISSUE TITLE
Appium inspector - "precise tap" to advance to next screen doesn't work

### ISSUE THREAD

**Issue by rafaelcs** [appium/appium#6600]
## The problem

I'm using appium inspector to locate elements on IOS 9. The first screen of the my app open normally, but when I used the "precise tap" to click on the button to advance to next screen, it's doesn't work 
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: OS X EL CAPITAN - Version 10.11
- Node.js version (unless using Appium.app|exe): v 6.2.0
- Mobile platform/version under test: iphone 6 - 9.3
- Real device or emulator/simulator: simulator
- Appium CLI or Appium.app|exe: .exe
## Details

How can I click on this button to advance to the next screen?

![image](https://cloud.githubusercontent.com/assets/8113555/16169042/9a916296-34f5-11e6-960c-bd5696d6101b.png)

Cheers,
Rafael

**Comment by StipeKolovrat** [comment]
HI Rafael, 

it should be straight forward, 

please try this: 

1. Tap `Record`
2. Tap `Precise Tap`
3. Choose `Duration` 
4. Tap on desired element in Appium inspector
5. Tap `Perform`

Hope it helps

**Comment by imurchie** [comment]
"Doesn't work" is diagnostically not too useful. Can you provide the logs so we can possibly figure out what is going wrong?

**Comment by rafaelcs** [comment]
@imurchie - What type of log for this situation? Where I can get this log?

**Comment by imurchie** [comment]
It should be in the main window of the app, I think. Whatever text is produced in there.

**Comment by rafaelcs** [comment]
@StipeKolovrat Even with this steps, I'm not able to see the next screen of the app. More idea?

**Comment by StipeKolovrat** [comment]
I as well, have from time to time issues on appium 1.5.3. 

Did you try with 1.4.13 version? That one seemed reliable. 
You can find archive of previois versions in here: https://bitbucket.org/appium/appium.app/downloads/

**Comment by jlipps** [comment]
Appium.app is not supported anymore. Use [appium-desktop](https://github.com/appium/appium-desktop) instead
