### ISSUE TITLE
TouchUp fails after negative TouchMove

### ISSUE THREAD

**Issue by tiagoshibata** [appium/appium#6602]
## The problem

Performing a touchMove with negative coordinates followed by a touchUp fails, returning that the relative (negative) coordinates are outside the screen. If the touchMove preceding the touchUp has positive coordinates the error is not thrown.
#5243 related.

## Environment

* Appium version (or git revision) that exhibits the issue: c92d23d4bef00642c623a5004942801f993c8b3f
* Desktop OS/version used to run Appium: Linux
* Node.js version: v6.2.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Using Appium CLI and Python client

## Details

Relevant log lines of minimal example:
```
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":99,"y":99}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchMove
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][720,1184]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchMove using element? false x: 99, y: 99
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchUp","params":{"x":-1,"y":-1}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchUp","params":{"x":-1,"y":-1}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchUp
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][720,1184]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":29,"value":"Coordinate [x=-1.0, y=-1.0] is outside of element rect: [0,0][720,1184]"}
```

## Link to Appium logs

[Log of example shown below](https://gist.github.com/tiagoshibata/3bda9d9aa09109f0e59fd2f34ada0772) (package and activity names removed from log).
[Log of sample-code/examples/python/android_complex.py](https://gist.github.com/tiagoshibata/21176e09f92cbcb11334cb1246de0f54).

## Code To Reproduce Issue

Minimal example:
```
from appium.webdriver.common.touch_action import TouchAction
import appium

capabilities = {
	'appActivity': "<ACTIVITY_NAME>",
	'appPackage': "<PACKAGE_NAME>",
	'deviceName': "Android",
	'platformName': "Android",
}

webdriver = appium.webdriver.Remote("http://localhost:4723/wd/hub", capabilities)
try:
	touch_action = TouchAction(webdriver)
	touch_action.press(x=100, y=100).move_to(x=-1, y=-1).release().perform()
finally:
	webdriver.quit()
```

[sample-code/examples/python/android_complex.py](https://github.com/appium/sample-code/blob/master/sample-code/examples/python/android_complex.py) also fails with `{"status":13,"value":"Unable to perform multi pointer gesture"}` on my device.

**Comment by imurchie** [comment]
Yes. This seems like a bug. Thanks for bringing it to our attention!

**Comment by Metalliguitare** [comment]
Hello there.

I'm sorry if it's not the right place to write this, i'm beginning with Appium and even GitHub.

I'm still having the issue in Appium 1.6.3 on Android real device so i can't achieve to do a proper swipe...
I'm using JAVA, and since the swipe method is deprecated, i don't want to use it.

With the hope to solve, i updated all soft this morning, so I'm using :
- Mac OS 10.11 
- Appium 1.6.3
- NodeJS 6.9.4
- npm 3.10.10

When i use the same sample code tiagoshibata posted, i have the same result "is outside of element rect" as my -1 had been passed as absolute coordinates.

I'm stuck.
Thanks a lot for your help.

**Comment by jlipps** [comment]
What happens if you do the coordinate math yourself and use absolute coordinates?

**Comment by Metalliguitare** [comment]
Oh... after reviewing my code a 5th time, seems I've finally fixed my problem

I wanted to use my statement in a "for" loop (with i as the number of swipes i want).

It seems that if I don't instantiate a new TouchAction(myDriver) object inside my loop after each swipe, i have issues.
Now it seems to work much better.

Maybe your answer just switched a light in my poor brain :)
Sorry for the inconvenience.
