### ISSUE TITLE
I'm facing issue in appium server

### ISSUE THREAD

**Issue by nagarjunay** [appium/appium#6604]
In Appium server i have been set ios settings and i click on launch button & when i click  on inspector then iphone simulator will start and the app opens and close. what is the problem, can any one help out me.

thank you.

**Comment by imurchie** [comment]
Can you provide the Appium server logs as a [gist](https://gist.github.com)? Otherwise there is nothing we can say.

**Comment by nagarjunay** [comment]
[debug] [Instruments] [INST STDERR] Instruments Trace Error : Target failed to run: The operation couldn’t be completed. (FBSOpenApplicationErrorDomain error 1.) : Failed to launch process with bundle identifier 'in.fybr'

[debug] [Instruments] Instruments exited with code 253

[Instruments] Error launching instruments: Instruments never checked in

[debug] [iOSSim] Killing all iOS Simulators

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - -

**Comment by SrinivasanTarget** [comment]
@nagarjunay Your app doesn't seem to be debug signed to run against appium.It's not appium error.Please raise this in appium discuss forum and there are already many answers there. for e.g https://discuss.appium.io/t/instruments-crashed-on-startup-ios-real-device/3285/10

**Comment by SrinivasanTarget** [comment]
@triager please close
