### ISSUE TITLE
Appium doesn't install when using an enterprise mirror of NPM

### ISSUE THREAD

**Issue by JamieEdge** [appium/appium#6605]
## The problem

Within a standard corporate environment, there are can be issues with npm and proxies. In fact, so many that I spent almost an entire day messing with proxy settings and getting not very far.

The way that Appium package.json file defines dependencies causes some issues. There is a hardcoded URL to the `https://repository.npmjs.org/...` path of each module, leading to two issues:
- Some proxies will not allow HTTPS traffic or will break the SSL chain, inject extra headers, etc.
- Some enterprise environments will use an internal mirror of the NPM repository to save thousands of machines downloading the same packages from the Internet again and again.

You might think just to not use a proxy, which isn't possible for me as firewalls require all web traffic to go via proxies. You might also think to just switch to some home wifi, but this also isn't possible on many corporate machines due to network access control requiring only company networks to be used.
## Environment
- Appium version (or git revision) that exhibits the issue: HEAD
- Last Appium version that did not exhibit the issue (if applicable): Cannot see that far back in Git history.
- Desktop OS/version used to run Appium: Mac OS X (but would affect Windows too)
- Node.js version (unless using Appium.app|exe): 4.4.5
- Mobile platform/version under test: N/A
- Real device or emulator/simulator: N/A
- Appium CLI or Appium.app|exe: CLI (NPM)
### Case 1 - Using an internal NPM mirror

```
npm config set repository http://internal-npm-mirror.example.intranet/
```

Then install Appium using `npm install appium` and notice how a handful of errors appear about not being able to connect to `https://repository.npmjs.org` (because you are in a proxy environment).
### Case 2 - Using proxy settings and HTTP (not HTTPS)

```
npm config set proxy http://user:pass@internal-proxy-server.example.intranet:8080/
npm config set https-proxy https://user:pass@internal-proxy-server.example.intranet:8080/
npm config set repository http://repository.npmjs.org/
```

Then install Appium using `npm install appium` and notice how the first level of dependencies download ok, but the following ones try to download from the HTTPS version of the NPM repository and fail because of internal issues with proxies/NPM/SSL.

To be sure that it's not just specific proxies, I tried 4 different servers and none would work.

I'm sure that I'm not the only one who has ever tried to install Appium via NPM inside of a restrictive network environment before, and hopefully this is something that could be resolved simply.

**Comment by jlipps** [comment]
@JamieEdge is this issue still persisting? I think it may have been an issue with npm-shrinkwrap rather than Appium itself.

**Comment by JamieEdge** [comment]
I’m afraid that I haven’t been using Appium for a few months so cannot tell if this issue still exists. Essentially, it was the part when the install process starting trying to fetch stuff using non-npm distribution that things got stuck and then eventually failed. If that bit is gone then I think that it is sorted.
