### ISSUE TITLE
ideviceinstaller is not installed with Appium

### ISSUE THREAD

**Issue by JamieEdge** [appium/appium#6606]
## The problem

It is expected that Appium will include a compiled version of ideviceinstaller so that testing on real iOS devices will work 'out of the box' but this is not the case.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable): Unknown
- Desktop OS/version used to run Appium: Mac OS 10.11
- Node.js version (unless using Appium.app|exe): 4.4.5 or 6.2.2
- Mobile platform/version under test: iOS
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: CLI or Appium.app
## Details

The ideviceinstaller utility is expected to be installed by Appium within it's own directory, but is not.

This is an issue, as in an enterprise environment tools like Homebrew are blocked.
## Link to Appium logs

```
[debug] [iOS] Couldn't find ideviceinstaller, trying built-in at /Users/jamie/Desktop/appium-via-npm/node_modules/appium/node_modules/build/libimobiledevice-macosx/ideviceinstaller
```
## Code To Reproduce Issue

Run the following command on a machine which does not have ideviceinstaller already.

`npm install appium`

**Comment by moinuddin14** [comment]
You are correct that one ideviceinstaller comes along with the Appium. But that is specific to one platform and if your platform meets the same, then the inbuilt that comes with Appium will work, else you have to install it seperately.

**Comment by edgy360** [comment]
The issue is that there isn't any version included, not even one for the wrong arch (below).

And even if it were just for one arch, surely OS X 64 bit is a standard architecture for at least the past few years on OS X, and I couldn't imagine a different arch that it would be compiled for. I could only think of PPC but I doubt that Xcode or Appium could even run on that.

```
ls: /Users/jamie/Desktop/appium-via-npm/node_modules/appium/node_modules/build/libimobiledevice-macosx/: No such file or directory

ls: /Users/jamie/Desktop/appium-via-npm/node_modules/appium/node_modules/build/: No such file or directory
```

**Comment by jlipps** [comment]
@JamieEdge ideviceinstaller needs to be installed on its own, not as part of the Appium install. Apologies for the lengthy delay on reply here.
