### ISSUE TITLE
[Feature Request] `recreateChromeDriverTimeout` capability

### ISSUE THREAD

**Issue by ssynix** [appium/appium#6607]
## The problem

I'm automating a hybrid cordova app on android. I experience intermittent chromedriver failures when dealing with webviews.
#### 1. Chrome not reachable upon initiating a chromedriver session

The first failure happens when _sometimes_ starting a chromedriver session fails with "chrome not reachable". Tailing the chromedriver log shows a stream of 

```
...
[13.158][DEBUG]: DevTools request: http://127.0.0.1:12056/json/version
[13.158][DEBUG]: DevTools request failed
[13.213][DEBUG]: DevTools request: http://127.0.0.1:12056/json/version
[13.214][DEBUG]: DevTools request failed
[13.268][DEBUG]: DevTools request: http://127.0.0.1:12056/json/version
[13.269][DEBUG]: DevTools request failed
[13.323][DEBUG]: DevTools request: http://127.0.0.1:12056/json/version
...
```

Enabling `recreateChromeDriverSessions` allows appium to retry starting the chromedriver and sometimes this attempt is successful, however there is a chance at times where this fails 4 times in a row and I believe this is the limit on how many times appium retries the operation.

The issue with this approach is that `recreateChromeDriverSessions=true` gives the chromedriver failure a chance to happen every time the context is switched to a webview. While `recreateChromeDriverSessions=false` will continue to work if the first attempt on starting a chromedriver works successfully.

So they both have their pros and cons, but nothing that works around the issue completely. I'm not sure if the issue is within chromedriver, cordova, our app, or somehow related to the overall interaction between all this, but I believe it's not seated within Appium based on my looking through its source code.
#### 2. Chromedriver stuck on capturing a screenshot

The second failure happens sometimes when I want to grab a screenshot in a webview context. Appium is waiting on chromedriver to return, but chromedriver log is stuck on this step:

```
[364.749][DEBUG]: DEVTOOLS COMMAND Page.captureScreenshot (id=20) {

}
```

No log shows up on appium or chromedriver after this.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable): used selendroid before appium 1.5.x
- Desktop OS/version used to run Appium: MacOS El Capitan
- Node.js version (unless using Appium.app|exe): 6.1.0
- Mobile platform/version under test: Android 6, Android N
- Real device or emulator/simulator: Nexus 6P
## Suggestion

Add a `recreateChromeDriverTimeout` parameter which recreates the chromedriver session if it fails to respond within the specified timeout. I'm open to adding this myself, but I find the code a bit hard to read and navigate through with all the async await usages. I'm also not familiar with all the places in the code that need to be touched as a result of this.

**Comment by ssynix** [comment]
If you could give me pointers on different places in the project that I need to change for a successful implementation, I can look into contributing.

Also what do you recommend for debugging Appium? I've had trouble with most IDEs and debugging tools when it comes to setting up ES6 source maps and stepping through the code.

Thank you!

**Comment by jlipps** [comment]
@ssynix are you still noticing this issue with the latest version of Appium? it has new chromedrivers which might have resolved this issue

**Comment by ssynix** [comment]
The specific issue mentioned here has been fixed in ChromeDriver. Although I still think there's value in timing out requests sent to proxies in general. We faced a similar issue in the past where ios-webkit-debug-proxy wouldn't send back a response and Appium would wait forever.
