### ISSUE TITLE
macOS Sierra Beta support

### ISSUE THREAD

**Issue by dnphung** [appium/appium#6609]
## The problem

macOS Sierra beta cannot be detected by the appium server 

## Environment

* latest Appium version
* Desktop OS/version used to run Appium: El Capitan
* Real device: iPhone 6 iOS 10 beta
* Appium CLI or Appium.app|exe:

**Comment by imurchie** [comment]
What do you mean by "detected"?

**Comment by 03623170** [comment]
I receive following error:
'/Applications/Appium.app/Contents/Resources/node/bin/node' '/Applications/Appium.app/Contents/Resources/node_modules/appium-doctor/appium-doctor.js'
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ Xcode is installed at: /Library/Developer/CommandLineTools
[Error: Could not detect Mac OS X Version from sw_vers output: '10.12
']

**Comment by imurchie** [comment]
Ah. Yes, this is a bug. Thank you for letting us know!

**Comment by imurchie** [comment]
Can you try to reinstall `appium-doctor` and retry?

```
cd /Applications/Appium.app/Contents/Resources/
npm install appium-doctor
```

**Comment by 03623170** [comment]
Unfortunately, the error is still there

**Comment by imurchie** [comment]
Ok. Can you make an issue in the [app's repository](https://github.com/appium/appium-dot-app/issues). I don't know how it is doing things.

**Comment by carlos-navas-globant** [comment]
were you able to solve this? How can you add MacOSX Sierra exception?

**Comment by spc4** [comment]
I am facing the same issue. @dnphung  were you able to solve it ?

**Comment by carlos-navas-globant** [comment]
@spc4 I fixed by installing Appium. version 1.4.13 (you can download it from older builds).

Then:

1) Navigate  to /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/doctor/ and edit the ios.js file.

2) Edit the following function by adding 10.12 as part of the supported operating systems “IOSChecker.prototype.getMacOSXVersion = function (cb)”

**Comment by ladzaj** [comment]
@carlos-navas-globant: did not help, i installed older Appium 1.14.3 (Draco), edited ios.js file:

IOSChecker.prototype.getMacOSXVersion = function (cb) {
  exec("sw_vers -productVersion", function (err, stdout) {
    if (err === null) {
      if (_s.startsWith(stdout, '10.8')) {
        this.osVersion = '10.8';
        cb(null, "Mac OS X 10.8 is installed.");
      } else if (_s.startsWith(stdout, '10.9')) {
        this.osVersion = '10.9';
        cb(null, "Mac OS X 10.9 is installed.");
      } else if (_s.startsWith(stdout, '10.10')) {
        this.osVersion = '10.10';
        cb(null, "Mac OS X 10.10 is installed.");
      } else if (_s.startsWith(stdout, '10.11')) {
        this.osVersion = '10.11';
        cb(null, "Mac OS X 10.11 is installed.");
      } else if (_s.startsWith(stdout, '10.12’)) {
        this.osVersion = '10.12’;
        cb(null, "Mac OS X 10.12 is installed.");
      } else {
        this.log.fail("Could not detect Mac OS X Version", cb);
      }
    } else {
      this.log.fail("Unknown SW Version Command: " + err, cb);
    }
  }.bind(this));
};

i saved changes, and i am facing this after starting Appium Doctor:

'/Applications/Appium.app/Contents/Resources/node/bin/node' '/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js'
/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/doctor/ios.js:43
      } else if (_s.startsWith(stdout, '10.12’)) {
                                       ^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium-doctor.js:4:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

Any idea to solve this please? Thanks

**Comment by imurchie** [comment]
This will not solve the overall problem, but the syntax error in the code you wrote is the find '’', which should be a regular single quote.

**Comment by dnphung** [comment]
@spc4 I am currently switched to appium@beta version

**Comment by Prateek412** [comment]
Facing the same issue:-
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ Xcode is installed at: /Library/Developer/CommandLineTools
[Error: Could not detect Mac OS X Version from sw_vers output: '10.12
']

**Comment by imurchie** [comment]
I've made some updates. Can you reinstall `appium-doctor` and try again?

```
npm uninstall -g appium-doctor
npm install -g appium-doctor
```

**Comment by brianbautista** [comment]
Thank you imurchie.  Uninstall and reinstall worked on macOS Sierra.

**Comment by imurchie** [comment]
Awesome! 

Soon I should have a machine that I can run macOS tests on. So we can certify Appium with it.

Thanks for the feedback!

**Comment by saicharan005** [comment]
Guys , 
This is Sai . I am also facing the same issue . Using the Appium version 1.5.3 . I have tried Uninstall and reinstall of appium doctor . But  of no avail . Under Resources folder i have 2 sub folders i.e appium && appium-doctor .. The ios.js file syntax also completely different to above mentioned . Please help me .

**Comment by imurchie** [comment]
Can you provide the output, @saicharan005 ? There is no way to tell what is going on.

**Comment by Tanmoyray** [comment]
I am also getting this issue.
Environment : macOX siri, appium: 1.5.3
I am not able run appium. Please help, How to fixed this issue?

`appium doctor has not worked. 
Error :
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
[Error: Could not detect Mac OS X Version from sw_vers output: '10.12`

Appium Logs:
` `Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --debug-log-spacing --automation-name "Appium" --platform-name "Android" --platform-version "7.0" --app "/Users/tanmoyray/Desktop/veiculu.apk" --avd "test_7.0" --app-pkg "com.senrysa.parkingplace" --app-activity "com.facebook.LoginActivity" --device-name "Moto"

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:
[Appium]   debugLogSpacing: true
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '7.0'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'Moto'
[Appium]   app: '/Users/tanmoyray/Desktop/veiculu.apk'
[Appium]   appPackage: 'com.senrysa.parkingplace'
[Appium]   appActivity: 'com.facebook.LoginActivity'
[Appium]   avd: 'test_7.0'
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"Android"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"7.0"}'
[Appium]   --automation-name => --default-capabilities '{"automationName":"Appium"}'
[Appium]   --device-name => --default-capabilities '{"deviceName":"Moto"}'
[Appium]   --app => --default-capabilities '{"app":"/Users/tanmoyray/Desktop/veiculu.apk"}'
[Appium]   --app-pkg => --default-capabilities '{"appPackage":"com.senrysa.parkingplace"}'
[Appium]   --app-activity => --default-capabilities '{"appActivity":"com.facebook.LoginActivity"}'
[Appium]   --avd => --default-capabilities '{"avd":"test_7.0"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '7.0'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'Moto'
[Appium]   app: '/Users/tanmoyray/Desktop/veiculu.apk'
[Appium]   appPackage: 'com.senrysa.parkingplace'
[Appium]   appActivity: 'com.facebook.LoginActivity'
[Appium]   avd: 'test_7.0'

[Appium] Appium REST http interface listener started on 0.0.0.0:4723

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 41 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 25 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 22 ms - 83 

[HTTP] --> GET /wd/hub/sessions {}

[MJSONWP] Calling AppiumDriver.getSessions() with args: []

[MJSONWP] Responding to client with driver.getSessions() result: []

[HTTP] <-- GET /wd/hub/sessions 200 4 ms - 40 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","appPackage":"com.senrysa.parkingplace","newCommandTimeout":"7200","app":"/Users/tanmoyray/Desktop/veiculu.apk","platformVersion":"7.0","deviceName":"Moto","automationName":"Appium"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android",...

[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   platformName: 'Android'
[Appium]   appPackage: 'com.senrysa.parkingplace'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/tanmoyray/Desktop/veiculu.apk'
[Appium]   platformVersion: '7.0'
[Appium]   deviceName: 'Moto'
[Appium]   automationName: 'Appium'
[Appium]   appActivity: 'com.facebook.LoginActivity'
[Appium]   avd: 'test_7.0'

[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior

[BaseDriver] Session created with session id: 135df2ce-cc52-43c8-95aa-9a1a35d6fb19
[debug] [AndroidDriver] Getting Java version

[AndroidDriver] Java version is: 1.8.0_91

[ADB] Checking whether adb is present

[ADB] Using adb from /Users/tanmoyray/library/android/sdk/platform-tools/adb

[debug] [ADB] Trying to find test_7.0 emulator

[debug] [ADB] Getting connected emulators

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[debug] [ADB] 1 emulator(s) connected

[debug] [ADB] Sending telnet command to device: avd name
[debug] [ADB] Getting running emulator port

[debug] [ADB] Socket connection to device created

[debug] [ADB] Socket connection to device ready

[debug] [ADB] Telnet command got response: Nexus_S_API_24

[debug] [ADB] Emulator test_7.0 not running
[debug] [ADB] Launching Emulator with AVD test_7.0, launchTimeout60000 ms and readyTimeout 60000 ms
[ADB] Checking whether emulator is present

.
.
.

[debug] [ADB] Trying to find test_7.0 emulator

[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] 1 emulator(s) connected
[debug] [ADB] Sending telnet command to device: avd name
[debug] [ADB] Getting running emulator port
[debug] [ADB] Socket connection to device created
[debug] [ADB] Socket connection to device ready
[debug] [ADB] Telnet command got response: Nexus_S_API_24
[debug] [ADB] Emulator test_7.0 not running

[debug] [ADB] Trying to find test_7.0 emulator

[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] 1 emulator(s) connected
[debug] [ADB] Sending telnet command to device: avd name
[debug] [ADB] Getting running emulator port
[debug] [ADB] Socket connection to device created
[debug] [ADB] Socket connection to device ready
[debug] [ADB] Telnet command got response: Nexus_S_API_24
[debug] [ADB] Emulator test_7.0 not running

[debug] [ADB] Trying to find test_7.0 emulator

[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[ADB] Error: Could not find test_7.0 emulator.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:325:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 [Error: Could not find test_7.0 emulator.]

[debug] [ADB] 1 emulator(s) connected
[debug] [ADB] Sending telnet command to device: avd name
[debug] [ADB] Getting running emulator port
[debug] [ADB] Socket connection to device created
[debug] [ADB] Socket connection to device ready
[debug] [ADB] Telnet command got response: Nexus_S_API_24
[debug] [ADB] Emulator test_7.0 not running
[debug] [AndroidDriver] Shutting down Android driver
[AndroidDriver] Cannot shut down Android driver; it has already shut down
[HTTP] <-- POST /wd/hub/session 500 64352 ms - 216 

[ADB] Error: Error getting AVD with retry. Original error: Could not find test_7.0 emulator.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:327:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 [Error: Error getting AVD with retry. Original error: Could not find test_7.0 emulator.]
[MJSONWP] Encountered internal error running command: Error: Error getting AVD with retry. Original error: Could not find test_7.0 emulator.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:327:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 95 ms - 83 `

**Comment by imurchie** [comment]
@Tanmoyray this is _not_ the same problem. Appium 1.5.3 does not support Android N. You will have to upgrade to get support.

**Comment by michaelgorlik** [comment]
hi @imurchie , i have made all the instructions you talled us to do but i still get the "Could not detect Mac OS X Version from sw_vers output: '10.12
']" error
please advice.

**Comment by sourcebits-siddesh** [comment]
@michaelgorlik  I come across same issue with same sieera OS version

Tried uninstalling the appium doctor and installing ..Unable to resolve the issue.

waiting here please revert back

**Comment by chattip-playbasis** [comment]
It' worked for me.

Answer for resolve this problem.

http://stackoverflow.com/questions/40129794/how-to-fix-error-could-not-detect-mac-os-x-version-from-sw-vers-output-10-12/40168992#40168992

**Comment by michaelgorlik** [comment]
@chattip-playbasis  thanks this resolved my problem!

**Comment by zhuzhutest** [comment]
@chattip-playbasis it worked for me ,thk

**Comment by Elmeri** [comment]
Could this be officially fixed? It seems weird that the official solution is for everyone using Sierra to manually modify config file.

**Comment by imurchie** [comment]
This _is_ officially fixed. If you use `appium-doctor` 2.3.3 or above the error is not there.

**Comment by Elmeri** [comment]
Ah, thank you. Sorry about that then.

**Comment by sjenasears** [comment]
i am still getting the issue Error: Could not detect Mac OS X Version from sw_vers output: '10.12.3

**Comment by imurchie** [comment]
You will need to upgrade. This is an issue with an old and outdated version of Appium.

**Comment by prashant-testhandy** [comment]
Where to get latest and new version of Appium?
I downloaded from Appium.io there I found 1.5.3 is the latest one and I am still getting error however by changing .js files I can work but thats not the correct way of doing it I feel, please tell where can I get .dmg file for Mac because of some limitations I cannot install it using npm.

**Comment by mykola-mokhnach** [comment]
@prashant-testhandy https://github.com/appium/appium-desktop/releases

**Comment by prashant-testhandy** [comment]
I think it is not the one I am looking for it is 1.0.2 beta, is there any renumbering for version is done I am not aware of because I already have 1.5.3 which is throwing error.

**Comment by carolcruzc** [comment]
Hi I'm having a similar problem:
Appium: 1.7.1

**appium-doctor --android**
OK

**appium-doctor --ios**
info AppiumDoctor Appium Doctor v.1.4.3
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 6.11.4
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
Error: Could not detect Mac OS X Version from sw_vers output: '10.13'
    at Object.macOsxVersion$ (/usr/local/lib/node_modules/appium-doctor/node_modules/appium-support/build/lib/system.js:114:15)
    at tryCatch (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium-doctor/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:109:7)
MAC6056:~ ccruz$ appium --version
