### ISSUE TITLE
Android hybrid mobile app: Getting Unhandled error: Error: getaddrinfo ENOENT in appium, wherein a session could not be created

### ISSUE THREAD

**Issue by vsa110810** [appium/appium#6610]
## The problem

While trying to run appium for scripts of android hybrid mobile apps, I get this error message in appium console:
 info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready

> info: [debug] [BOOTSTRAP] [debug] Loading json...
> error: Unhandled error: Error: getaddrinfo ENOENT
>     at Object.exports._errnoException (util.js:746:11)
>     at errnoException (dns.js:49:15)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:94:26) context: [POST /wd/hub/session {"desiredCapabilities":{"appPackage":"app","appActivity":"<app>.MainActivity","BROWSER_NAME":"Android","VERSION":"6.0.1","platformName":"Android","deviceName":"Moto G (3rd Generation)","]
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.

**At the same time in eclipse, SessionNotCreatedException is seen.**  
## Environment
- Appium versions (or git revision) that exhibits the issue: 1.4.13 and 1.4.16.1
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Windows 8.1
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: android 6.0.1
- Real device or emulator/simulator: Real device: Moto G 3rd generation
- Appium CLI or Appium.app|exe: base.apk
## Details

I am trying to automate android hybrid mobile application with simple complexity. The issue I initially faced was that the context of app or switch of context was not detected by appium with error, "WEBVIEW_undefined". To resolve that issue, used the code snippet of bchand1748 in [Link1](https://discuss.appium.io/t/hybrid-android-app-testing-cant-switch-to-webview/5182/4). 
Executed the script and the first run was successful, though the elements located by xpath was not detected. But in the next successive runs, it kept showing error,"NoSuchContextFound" and "device not online" error though the device is listed by adb. 
To correct this issue, followed the instructions in [Link 2](https://github.com/appium/appium/issues/5704). 
As before, again it executed the first time and in the next successive runs, it showed another error, "Unhandled error: Error: getaddrinfo ENOENT". Thus, a new session could not be created. 

As can be observed the appium shows different kind of errors each time and I have not been able to automate the app successfully. Well, I have used this tool (1.4.13) before, and it worked for the very same mobile hybrid app. Would like to get information on how to proceed. I have attached screenshots of errors displayed in appium at each instance.

![ap_er](https://cloud.githubusercontent.com/assets/20083762/16259381/ffeedbcc-387f-11e6-93f3-249f9d7cfeef.png)
![appium_atmn](https://cloud.githubusercontent.com/assets/20083762/16259382/fff0cd06-387f-11e6-8fa3-6dd0afcc5854.png)
![webview_ntdetectd](https://cloud.githubusercontent.com/assets/20083762/16259383/fff52504-387f-11e6-8b51-191b8b9761b5.png)
## Link to Appium logs : Unhandled error: Error: getaddrinfo ENOENT

https://gist.github.com/vsa110810/45a0087b9284e127f5b4aba59b0b7e94
## Code To Reproduce Issue [ Good To Have ]

https://github.com/appium/sample-code/compare/master...vsa110810:patch-1

**Comment by jlipps** [comment]
Does this reproduce in Appium 1.6.4? Sorry to take so long to respond.

**Comment by imurchie** [comment]
Closing as only a problem on very old Appium versions.
