### ISSUE TITLE
OpenJDK not supported by any release?

### ISSUE THREAD

**Issue by amosshapira** [appium/appium#6613]
## The problem

I'm encountering the problem which is supposedly already address by #5551 but couldn't find the solution (of adding "openjdk" to the regular expression) in any released version. I tried 1.4.10, 1.4.16, 1.5.0 and 1.5.3. The changed file has disappeared from the 1.5.x source altogether.

Where can I get a released version which includes the fix?

Thanks.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.10, 1.4.16, 1.5.0, 1.5.3
* Last Appium version that did not exhibit the issue (if applicable): NA. The change was introduced by our switch to OpenJDK
* Desktop OS/version used to run Appium: Ubuntu 12.04
* Node.js version (unless using Appium.app|exe): 0.12.14
* Mobile platform/version under test: Android
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

**Comment by imurchie** [comment]
The fix is in the code: https://github.com/appium/appium-android-driver/blob/master/lib/android-helpers.js#L24

What is the problem that is happening?

**Comment by amosshapira** [comment]
Thanks for getting back to me. I am trying to stick with Appium 1.4.x line because Appium 1.5 brings a whole new pile of errors (`import` causing a syntax error).

Steps to reproduce:

1. On Ubuntu 12.04
1. Install nvm (following instructions from http://www.liquidweb.com/kb/how-to-install-nvm-node-version-manager-for-node-js-on-ubuntu-12-04-lts/ with a later version of nvm: `curl https://raw.githubusercontent.com/creationix/nvm/v0.31.1/install.sh | bash`)
1. install Appium 1.4.16 (latest Appium 1.4): `npm install appium@1.4.16`
1. Start Appium server: `/node_modules/appium/bin/appium.js --app ./SafeShare/app/build/outputs/apk/app-debug.apk --session-override --log-level debug --device-ready-timeout 180 &`
1. Execute a cucumber test which talks to Appium. The step definition is very specific to our environment but here is the error message:
```
info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","deviceName":"Android SDK built for x86","app":"/home/jenkins-slave/workspace/master.test.android/android-app/SafeShare/app/build/outputs/apk/app-debug.apk"}}
info: Client User-Agent string: appium/ruby_lib/5.0.1
info: [debug] No appActivity desired capability or server param. Parsing from apk.
info: [debug] No appPackage desired capability or server param. Parsing from apk.
info: [debug] Using local app from desired caps: /home/jenkins-slave/workspace/master.test.android/android-app/SafeShare/app/build/outputs/apk/app-debug.apk
info: [debug] Creating new appium session f4107c10-2df4-4598-af10-18a02a725ecd
info: Starting android appium
info: [debug] Getting Java version
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
error: Failed to start an Appium session, err was: Error: Could not get the Java version. Is Java installed?
info: [debug] Error: Could not get the Java version. Is Java installed?
    at [object Object].<anonymous> (/home/jenkins-slave/workspace/master.test.android/android-app/node_modules/appium/lib/devices/android/android-common.js:1062:17)
    at ChildProcess.exithandler (child_process.js:745:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1019:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1091:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not get the Java version. Is Java installed?)","origValue":"Could not get the Java version. Is Java installed?"},"sessionId":null}
```
Looking at the source of 1.4.16 on my disk as well as in https://github.com/appium/appium/blob/v1.4.16/lib/devices/android/android-common.js#L1046, I see that the fix is still not there.

Just for testing, I edited `node_modules/appium/lib/devices/android/android-common.js` to make the change locally on my test server and the error is gone.

Is there a way for me to get a working 1.4.x branch which includes this change?

Thanks.

**Comment by amosshapira** [comment]
Another test - I cloned the https://github.com/appium/appium repo locally and after creating a tag 'v1.4' for branch '1.4' I could diff it against the v1.4.16 tag and see that the change is in the branch head, but trying to install appium with `npm install appium@1.4` still comes up with the 1.4.16 version.

**Comment by amosshapira** [comment]
For now I created an updated branch 1.4 in a fork of Appium at https://github.com/amosshapira/appium and install that with `npm install git://github.com/amosshapira/appium.git#1.4`

**Comment by imurchie** [comment]
For the `import` errors in 1.5.x, that sounds like you are not transpiling the code. From source, the code needs to be run through `gulp transpile`, otherwise it will not work.

**Comment by imurchie** [comment]
This is an odd problem. The code was fixed but didn't make it into the release, for unknown reasons. The solution you've come up with seems like the only way to go. There is no active work on 1.4.x, though, so any problems that are fixed will not make there way into there.

**Comment by amosshapira** [comment]
Thanks. Using my version of 1.4 overcomes this issue but gets stuck on another common issue of not finding .appiumconfig.json and suggesting to run reset.sh, which isn't there anymore.

Should I expect to be able to switch to 1.5 smoothly? I'm just trying to get our Android tests back to work without knowing Appium so looking for the path of least work.

**Comment by amosshapira** [comment]
@imurchie do you have a pointer to documentation about this?

**Comment by amosshapira** [comment]
I ended up installing Appium 1.5 globally on the system.
Thanks.
