### ISSUE TITLE
Wifi connection can't be enable/disable on Appium 1.5.3 using custom wrapper

### ISSUE THREAD

**Issue by Mikulasi** [appium/appium#6615]
## The problem

Hi all! I updated Appium to the new one 1.5.3 recently and faced with issue that on Android wifi connection doesn't enable or disable using new implementation **driver.setConnection(Connection.NONE);** and **driver.setConnection(Connection.WIFI);**  on single and multithreaded tests.
## Environment
- Appium 1.5.3
- I checked this implementation on Appium 1.4 version and it works fine
- OS/version used to run Appium: EL Capitan
- Node.js version (unless using Appium.app|exe): Node v6.2.2
- Mobile platform/version under test: Android
- Real device or emulator/simulator: Real devices Samsung S4(5.0.1) and Nexus 5 (5.1.1)
- Appium CLI or Appium.app|exe: Appium CLI and Appium application
- Device API level: 21
## Link to Appium logs

https://gist.github.com/Mikulasi/455e76cf169819c3f642f0c92dcfb554
## Code

```
public void setWifiOff() {
        ((AndroidDriver<?>) appiumcontroller().getMobileDriver()).setConnection(Connection.NONE);
   }
```

**Comment by SrinivasanTarget** [comment]
@Mikulasi Is it not working on Grid env(multiple devices) or it doesn't work even for single device in API 23? Also please confirm on the Android API's it doesn't work?

**Comment by SrinivasanTarget** [comment]
@triager please label: bug,Android

**Comment by Mikulasi** [comment]
@SrinivasanTarget updated issue, it doesnt work even on single device and API level is 21

**Comment by TikhomirovSergey** [comment]
@Mikulasi 
I have read your gist

Here you are trying to set the NONE connection (bitmask is zero)
https://gist.github.com/Mikulasi/455e76cf169819c3f642f0c92dcfb554#file-gistfile1-txt-L1

...and here you are trying to get the connection
https://gist.github.com/Mikulasi/455e76cf169819c3f642f0c92dcfb554#file-gistfile1-txt-L135
This gist doesn't show which result is returned. Can you clarify that?

For instance, at that gist the returned result is 0 (NONE)
https://gist.github.com/TikhomirovSergey/da9af5fa326083ab0ec7483d326ee2bd#file-gistfile1-txt-L136

@SrinivasanTarget I have an idea. Is it possible that something is wrong wnen someboby tryes to do that on MAC OS? I do it on Windows and it seems it is fine.

**Comment by Mikulasi** [comment]
@TikhomirovSergey sure, i'll do that

**Comment by TikhomirovSergey** [comment]
@Mikulasi 
Also I've noticed...
Despite of connection setting sets/get 0 (NONE) an emulator looks like it is not offline. It it the real problem which you are facing?

**Comment by Mikulasi** [comment]
@TikhomirovSergey yes, when you set NONE, wifi is still enable

**Comment by SrinivasanTarget** [comment]
@Mikulasi @TikhomirovSergey Yes NONE is not working for me now in my personal device. Looking into it.

**Comment by SrinivasanTarget** [comment]
@imurchie FYI It came back again:( Looking into it.

**Comment by Mikulasi** [comment]
As a workaround to switch wifi off set Airplane and to switch wifi on set WIFI or ALL

**Comment by LoveleenSaini** [comment]
Hi @SrinivasanTarget 
Is there any update on this issue?

**Comment by SrinivasanTarget** [comment]
Unfortunately no updates @LoveleenSaini

**Comment by JaniJegoroff** [comment]
Still seeing this on Appium 1.6.1 release.

**Comment by SrinivasanTarget** [comment]
@sravanmedarapu Ping. Do you have any solution in mind through UIAutomator2?

**Comment by sravanmedarapu** [comment]
@SrinivasanTarget  Yeah, it is possible to handle WIFI state. Will make the necessary changes and share the details here once changes are published.

**Comment by SrinivasanTarget** [comment]
Thanks @sravanmedarapu

**Comment by sravanmedarapu** [comment]
@tfcardoso yes, current work around using WifiManager implemented in UIAutomator2 driver. but unfortunately work around will not work in all higher version real devices because of Android Security constraints and using adb commands also not working, we should investigate other possible means.

**Comment by jlipps** [comment]
@sravanmedarapu this can be closed, correct, now that NetworkConnection has been added to uiautomator2?

**Comment by sravanmedarapu** [comment]
@jlipps, current implementation is working flawlessly in all emulators(API 20 and above) but failing in some devices. So I think we can't close the issue  as it is still replicating.

Tested in Moto G(API 23) and One Plus One(API 23), it's working in Moto G but not in One Plus.

**Comment by jlipps** [comment]
Ok sounds good @sravanmedarapu. Is there a path to seeing what is going on with those devices?

**Comment by sravanmedarapu** [comment]
Issue is because of the security restrictions.

Exception:
`java.lang.SecurityException: io.appium.uiautomator2.server.test from uid 10240 not allowed to perform WIFI_CHANGE\n\tat android.app.AppOpsManager.noteOp(AppOpsManager.java:1888)\n\tat android.app.AppOpsManager.noteOp(AppOpsManager.java:1954)\n\tat android.net.wifi.WifiManager.setWifiEnabled(WifiManager.java:1471)
`

**Comment by jlipps** [comment]
Hmm. In that case I'm fine just keeping a list of phones which have a security model that doesn't support this feature, calling this feature done, and keeping our eyes open for a potential solution.

**Comment by sravanmedarapu** [comment]
Sure.

**Comment by Channareddy** [comment]
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
