### ISSUE TITLE
Session was terminated due to BROWSER_TIMEOUT exception after running tests in parallel

### ISSUE THREAD

**Issue by Mikulasi** [appium/appium#6619]
## The problem

There is a `org.openqa.selenium.WebDriverException: Session [95243da5-73bc-40db-b9fe-34b65f340e08] was terminated due to BROWSER_TIMEOUT` exception after update Appium to 1.5.3 and running tests in parallel, single threaded test works fine

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: El Capitan
* Node.js version (unless using Appium.app|exe): 6.2.2
* Mobile platform/version under test: Android API 21
* Real device or emulator/simulator: real devices Nexus 5(5.1.1), Samsung S4(5.0.1)
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/Mikulasi/b0edaa9d0326c86b5d0107c16947e8e7

https://gist.github.com/Mikulasi/7dbb6ba2e31a86f463159944b3f91534

**Comment by mykola-mokhnach** [comment]
Do you use Grid for parallel test execution? Also, this is a bit suspicious, that you don't explicitly provide device udid in capabilities when more than one device is connected, which may (and will) cause threading conflict since two different tests try to lock the same device at the same time.

**Comment by Mikulasi** [comment]
@mykola-mokhnach thanks, since new default capabilitites appears i forgot to pass udid, my mistake. it works after passing udid on each node.

**Comment by kolasvyshch** [comment]
@Mikulasi did you add udid to node.json file?

**Comment by Mikulasi** [comment]
yes and it works

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by jawlitkp** [comment]
How did you provide UDID in json file ? i am getting same issue,i am trying to treat all android device as same and let grid decide to pick any android device which is free and in order to achieve this i am not passing UDID so it run in most cases but i am getting the same error at randomly

**Comment by Mikulasi** [comment]
@jawlitkp, starting grid node set **--udid** parameter
