### ISSUE TITLE
RESOLVED - iOS processArguments doesn't send arguments to the application

### ISSUE THREAD

**Issue by JakeSc** [appium/appium#6620]
## The problem

According to http://appium.io/slate/en/master , the `processArguments` capability is used for "Arguments to pass to the AUT using instruments". However, setting the capability `processArguments` actually causes _environment_ variables to be set in the subsequent `instruments` command, not process arguments.

Testing with this (Java):
```
capabilities.setCapability("processArguments", "-arg -arg2 -arg3");
```

incorrectly causes the instruments command to look like this:
```
[debug] [Instruments] Spawning instruments with command: 'instruments -t Automation.tracetemplate -w "iPhone 6s (9.3) [" /path/to/App.app.app -e -arg "-arg2 -arg3" ...
```
(Note the `-e -arg "-arg2 -arg3"`.)

According to `man instruments`, -e is used to set environment variables. Process arguments should simply be passed in as additional arguments to the `instruments` command, like:
```
[debug] [Instruments] Spawning instruments with command: 'instruments -t Automation.tracetemplate -w "iPhone 6s (9.3) [" /path/to/App.app.app -arg -arg2 -arg3 ...
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OS X 10.11.5
* Node.js version (unless using Appium.app|exe): v4.1.1
* Mobile platform/version under test: iOS 9.3
* Real device or emulator/simulator: Simulator, iPhone 6
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

[See logs here](https://gist.github.com/JakeSc/5c70eb5fa43f5fba01a9a2487e614a0f)
Search for "Spawning instruments with command" and you'll see the bug.

## Code To Reproduce Issue [ Good To Have ]

```
		DesiredCapabilities capabilities = new DesiredCapabilities();

			capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6s");
			capabilities.setCapability(MobileCapabilityType.APP, "/DerivedData/MyApp-asdffxpdxxuyuvbwslojebjfqxcf/Build/Products/Debug-iphonesimulator/MyApp.app");
			capabilities.setCapability("processArguments", "-asdf -asdf2 -asdf3");
			UiTestcase.driver = new IOSDriver<MobileElement>(new URL("http://localhost:4723/wd/hub"), capabilities);
```

**Comment by JakeSc** [comment]
Never mind, this was resolved by this commit:
```
50f0c822ccf589996145c7e3473c44e01b78145c
Allow plain text process arguments
```

Closing.

**Comment by JakeSc** [comment]
This should be closed. Thanks!

**Comment by SrinivasanTarget** [comment]
@triager please close
