### ISSUE TITLE
Instruments socket client never checked in...

### ISSUE THREAD

**Issue by thiesdiggity** [appium/appium#6621]
Hello,

I have been racking my brain on this for a couple of days and cannot seem to fix the issue. It doesn't appear that Appium is able to launch instruments. I keep getting the following error:

[debug] [Instruments] And launch timeouts (in ms): {"global":0}
[Instruments] Instruments socket client never checked in; timing out (global)

## Environment

* Appium version 1.5.3
* OSX 10.11.6
* Node Version: 4.2.4
* iPhone 6 (9.3)
* Emulator
* Appium CLI

## Details

The command that the logs says its running is the following:

[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/k0/fn22bv350rngqjcl1qgv9k1h0000gn/T/appium-instruments/instrumentscli0.trace -w "iPhone 6 (9.3) [" com.apple.mobilesafari -e UIASCRIPT "/Users/john/Library/Application Support/appium/bootstrap/bootstrap-8bc9fdc4744eeb9d.js" -e UIARESULTSPATH /var/folders/k0/fn22bv350rngqjcl1qgv9k1h0000gn/T/appium-instruments'

However, when I run this via CLI it loads the simulator without any issue.

I've ran all the Appium setup scripts as well.

Please help!

Thanks,
John

**Comment by mykola-mokhnach** [comment]
Which capabilities do you pass to initialise the driver? Try to set _launchTimeout_ to, say, 60000 milliseconds and check what the execution result is (http://appium.io/slate/en/master/?ruby#ios-only).

**Comment by thiesdiggity** [comment]
DUH!
That worked.

Thank you very much @mykola-mokhnach!
