### ISSUE TITLE
XPath 2.0 support ?

### ISSUE THREAD

**Issue by oscheller87** [appium/appium#6623]
## The problem

I want to use the xpath function `matches` to work with custom RegExes. 
i.e.: `self.driver.find_elements_by_xpath("//*[matches(@label, 'Login')]")`
I'm aware that I don't need a regex for this certain example.

The `matches` function is part of XPath 2.0 and doesn't work with XPath versions lower than that. Is there a custom way to update the XPath version that appium uses to a higher one?

**Comment by ajit-jadhav** [comment]
You can use 'contains'  function against @text().

**Comment by oscheller87** [comment]
Thank you for the work-around suggestion. My question still stands though. I'd like to use more advanced regular expressions than what's possible with `contains`.

**Comment by jtappi** [comment]
Any updates in regards to Appium using Xpath 2.0?

**Comment by mykola-mokhnach** [comment]
I think, the main reason for this is libxml2, which still does not support XPath 2.0 and which is the base for almost all existing XML parsers. Check http://www.stars-blog.com/why-doesnt-libxml2-support-xpath-2-0-closed/ for more details. For iOS/MacOS there is native _NSXMLParser_, which supports XPath 2.0, but people complain it has other important problems, like encoding and data retrieving.

**Comment by jtappi** [comment]
thanks for the followup!

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by mhvora** [comment]
We have run into an issue where we need XPATH to be case insensitive. 
The text for TEXTVIEW comes up as camel case in Android 6 and ALL CAPS in Android 7,8.
eg: On the Android UI we have text "AIRPORT". On Android 6, the text attribute for this TextView comes up as "Airport" on uiautomater and on Android 7 and 8, the text attribute for this TextView comes up as "AIRPORT".
Is there a solution for this?

Note: XPATH 2.0 has functions that can help with case-insensitive matching but appium doesn't support it currently

**Comment by mykola-mokhnach** [comment]
@mhvora 

```java
    protected static String xpath1toLowerCase(String string) {
        return String.format("translate(%s,'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')", string);
    }

    private static Function<String, By> byAlertButtonByCaption = caption ->
            By.xpath(String.format("//*[starts-with(@resource-id, '%s') and %s='%s']",
                    "android:id/button", xpath1toLowerCase("@text"), caption.toLowerCase()));
```
