### ISSUE TITLE
Appium 1.5.2/1.5.3 running scripts very slow on iPhone real safari browser

### ISSUE THREAD

**Issue by knreddy036** [appium/appium#6626]
# The problem

Scripts are running very slow with appium 1.5.2 version , but with appium 1.4.3 version ,it is very fast .Suppose for each testscript in appium 1.4.3 ,it takes 80 sec ,but with appium 1.5.2 ,it is taking 400 sec .Any Idea how to fix this one ?
## Environment
- Appium version (or git revision) that exhibits the issue: Appium 1.5.3/1.5.2
- Last Appium version that did not exhibit the issue (if applicable): Appium 1.4.13
- Desktop OS/version used to run Appium: OS X EI Captain 10.11.5
- Node.js version (unless using Appium.app|exe): 1.6.2
- Mobile platform/version under test: iOS 9.3.2
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: Appium CLI and Appium.app
## Details

Scripts are running very slow with appium 1.5.2 version , but with appium 1.4.3 version ,it is very fast .Suppose for each testscript in appium 1.4.3 ,it takes 80 sec ,but with appium 1.5.2 ,it is taking 400 sec .Any Idea how to fix this one ?
## Link to Appium logs

[iPhone6splus.txt](https://github.com/appium/appium/files/342019/iPhone6splus.txt)
## Code To Reproduce Issue [ Good To Have ]

Please refer the logs for the capabilities i used for appium and browser

**Comment by jawlitkp** [comment]
I am facing same issue ,is there any update ?

**Comment by jawlitkp** [comment]
Are you able to resolve this issue ? if yes please share solution

**Comment by rkavalap** [comment]
Closing as dup for https://github.com/appium/appium/issues/6644
