### ISSUE TITLE
Android native browser (Chrome) - attach and test on running chrome instance

### ISSUE THREAD

**Issue by romangoldstain** [appium/appium#6628]
## The problem

Hello,

I'm trying to run an appium test on android chrome over already running chrome instance. In order to do so, I've changed the chrome option **androidUseRunningApp** to **true**. for some reason, this caused a very unexpected behavior:
the running chrome instance freezes, once chromedriver tries to attach, and after few seconds it's process is shut down. I do see the following lines in logcat:

_I/ActivityManager( 1136): Force stopping com.android.chrome appid=10073 user=-1: set debug app
I/ActivityManager( 1136): Killing 17704:com.android.chrome:privileged_process0/u0a73 (adj 0): stop com.android.chrome
W/ActivityManager( 1136): Scheduling restart of crashed service com.android.chrome/org.chromium.content.app.PrivilegedProcessService0 in 1000ms
I/ActivityManager( 1136): Killing 17631:com.android.chrome/u0a73 (adj 0): stop com.android.chrome_

At this point, if I launch chrome manually quick enough, from device's launcher, the new chromedriver session will be created against the newly start chrome and I get back a valid WebDriver. But if I wont launch it, no session will be created and the test fails to get valid WebDriver.

I tried to bypass appium by directly sending REST-ing the chromedriver directly, same result.
these are the capabilities I'm sending:
_{"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidUseRunningApp":**true**,"androidDeviceSerial":"xxx"}}}_

Any idea?

tried chromedriver 2.18 and 2.22, no diff. 
nothing useful (or at all) in chromedriver's logs (--log-path opt).

Thanks!
## Environment
- Appium version (or git revision) that exhibits the issue: 1.4.16.1
- Desktop OS/version used to run Appium: windows
- Mobile platform/version under test: Nexus 5 4.4, Samsung S5 5.1
- chromedriver version: 2.18 and 2.22
- android chrome app version: 49
- Real device or emulator/simulator: real device

**Comment by jlipps** [comment]
Sorry to not have replied to this before; I don't think we support that capability. If Appium doesn't start chrome and initialize chromedriver on its own, I imagine weird things would happen. Does it work in the normal case? (Just setting browserName to "Chrome" and letting Appium launch Chrome and automate it? You shouldn't need to send in any of the chromeOptions you are currently sending).
