### ISSUE TITLE
Unexpected error. Parameters were incorrect. 

### ISSUE THREAD

**Issue by Can-too** [appium/appium#6630]
## The problem
I am using the Appium server on a Mac Mini and connecting my tests to it using the remoteWebDriver to from a Windows machine.  Two devices are connected to the mac mini. An iPhone 5C and a Nexus 6. I have written the C# code to connect to the Nexus and view a web page on the browser. That is working fine however the test using the iphone is failing only when the code attempts to find the element using the same code used successfully for the Nexus Test. 

I am attempted to find the element using the following variations but had the same issue:
1.  var idElement = driver.FindElement(By.Id("i_am_an_id")); or 
2. idElement = new WebDriverWait(driver, new TimeSpan(30)).Until(ExpectedConditions.ElementIsVisible(By.Id("i_am_an_id")));

Error:
OpenQA.Selenium.WebDriverException : Unexpected error. Parameters were incorrect. We wanted {"required":["using","value"]} and you sent ["using","value","locator"]
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementById(String id)
   at OpenQA.Selenium.By.<>c__DisplayClass2.<Id>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at RWWA.TestAutomation.Core.Tests.Appium.Samples.RemoteTests.Apple() in 

## Environment

* Appium version: 1.5.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: iOS 10.11.15
* Node.js version (unless using Appium.app|exe): v6.2.2
* Mobile platform/version under test: iPhone 5c v9.3.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium Command line (BASH)

## Details

```
 [Test]
        public void Apple()
        {
            var usercapabilities = new DesiredCapabilities();
            usercapabilities.SetCapability("deviceName", " iPhone");
            usercapabilities.SetCapability("platformName", "ios");
            usercapabilities.SetCapability("platformVersion", "9.3.2");
            usercapabilities.SetCapability(CapabilityType.BrowserName, "Safari");
            usercapabilities.SetCapability("udid", "437b...");

            RemoteWebDriver driver = new RemoteWebDriver(new Uri("http://10.67.14.98:4723/wd/hub"), usercapabilities);

            driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(30.0));
            driver.Navigate().GoToUrl("http://saucelabs.com/test/guinea-pig");

            Console.WriteLine("You are waiting 5 seconds...");
            Thread.Sleep(5000);

            Console.WriteLine("All systems are go again...");
            Console.WriteLine("You are at: " + driver.Url);

            var idElement = driver.FindElement(By.Id("i_am_an_id"));
            //idElement = new WebDriverWait(driver, new TimeSpan(30)).Until(ExpectedConditions.ElementIsVisible(By.Id("i_am_an_id")));
```

## Link to Appium logs
see:
[HTTP] --> POST /wd/hub/session/ffb7cfb5-81ee-49a7-a2ea-1dd153f7d0ce/element {"using":"id","value":"i_am_an_id","locator":"id"}
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["using","value"]} and you sent ["using","value","locator"]

[The Portion of the Appium Log produced when running only the Nunit Apple() Test below](https://gist.github.com/Can-too/bb8d354911020f7869e89961e64d362e)

## Code To Reproduce Issue [ Good To Have ]
```
using NUnit.Framework;
using OpenQA.Selenium.Remote;
using System;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;

namespace RWWA.TestAutomation.Core.Tests.Appium.Samples
{
    public class RemoteTests
    {
        [Test]
        public void Android()
        {
            var usercapabilities = new DesiredCapabilities();
            usercapabilities.SetCapability("deviceName", "Nexus 6");
            usercapabilities.SetCapability("platformName", "Android");
            usercapabilities.SetCapability("platformVersion", "6.0.1");
            usercapabilities.SetCapability(CapabilityType.BrowserName, "Chrome");

            RemoteWebDriver driver = new RemoteWebDriver(new Uri("http://10.67.14.98:4723/wd/hub"), usercapabilities);

            driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(15));
            driver.Navigate().GoToUrl("http://saucelabs.com/test/guinea-pig");

            Console.WriteLine("You are waiting 5 seconds...");
            Thread.Sleep(5000);

            Console.WriteLine("All systems are go again...");
            Console.WriteLine("You are at: " + driver.Url);

            var idElement = new WebDriverWait(driver, new TimeSpan(15)).Until(ExpectedConditions.ElementIsVisible(By.Id("i_am_an_id")));
            Console.WriteLine("Using the Id 'i_am_an_id' find the WebElement: " + idElement.Text);

            Assert.AreEqual("I am a div", idElement.Text);

            Assert.IsNotNull(idElement);
            Console.WriteLine("The Element with the id: 'i_am_an_id' contains the text: " + idElement.Text);

            var commentElement = driver.FindElement(By.Id("comments"));
            Assert.IsNotNull(commentElement);
            commentElement.SendKeys("This is an awesome comment");
            Console.WriteLine("The Element with the id: 'comments' has been sent the text: " + commentElement.Text);

            Console.WriteLine("Click on the Submit: ");
            var submitElement = driver.FindElement(By.Id("submit"));
            Assert.IsNotNull(submitElement);
            submitElement.Click();
            Thread.Sleep(7000);
            Console.WriteLine("Looking at page: ");

            var yourCommentsElement = driver.FindElement(By.Id("your_comments"));
            Assert.IsNotNull(yourCommentsElement);
            Console.WriteLine("The Element with the id: 'your_comments' has been found with the text: " + yourCommentsElement.Text);
            Assert.True(driver.FindElement(By.Id("your_comments")).Text.Contains("This is an awesome comment"));

            driver.Close();
            driver.Quit();

        }

        [Test]
        public void Apple()
        {
            var usercapabilities = new DesiredCapabilities();
            usercapabilities.SetCapability("deviceName", " iPhone");
            usercapabilities.SetCapability("platformName", "ios");
            usercapabilities.SetCapability("platformVersion", "9.3.2");
            usercapabilities.SetCapability(CapabilityType.BrowserName, "Safari");
            usercapabilities.SetCapability("udid", "437b7...");

            RemoteWebDriver driver = new RemoteWebDriver(new Uri("http://10.67.14.98:4723/wd/hub"), usercapabilities);

            driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(30.0));
            driver.Navigate().GoToUrl("http://saucelabs.com/test/guinea-pig");

            Console.WriteLine("You are waiting 5 seconds...");
            Thread.Sleep(5000);

            Console.WriteLine("All systems are go again...");
            Console.WriteLine("You are at: " + driver.Url);

            var idElement = driver.FindElement(By.Id("i_am_an_id"));
            //idElement = new WebDriverWait(driver, new TimeSpan(30)).Until(ExpectedConditions.ElementIsVisible(By.Id("i_am_an_id")));
            Console.WriteLine("Using the Id 'i_am_an_id' find the WebElement: " + idElement.Text);

            Assert.AreEqual("I am a div", idElement.Text);

            Assert.IsNotNull(idElement);
            Console.WriteLine("The Element with the id: 'i_am_an_id' contains the text: " + idElement.Text);

            var commentElement = driver.FindElement(By.Id("comments"));
            Assert.IsNotNull(commentElement);
            commentElement.SendKeys("This is an awesome comment");
            Console.WriteLine("The Element with the id: 'comments' has been sent the text: " + commentElement.Text);

            Console.WriteLine("Click on the Submit: ");
            var submitElement = driver.FindElement(By.Id("submit"));
            Assert.IsNotNull(submitElement);
            submitElement.Click();
            Thread.Sleep(7000);
            Console.WriteLine("Looking at page: ");

            var yourCommentsElement = driver.FindElement(By.Id("your_comments"));
            Assert.IsNotNull(yourCommentsElement);
            Console.WriteLine("The Element with the id: 'your_comments' has been found with the text: " + yourCommentsElement.Text);
            Assert.True(driver.FindElement(By.Id("your_comments")).Text.Contains("This is an awesome comment"));

            driver.Close();
            driver.Quit();
        }
    }
}
```
`

**Comment by mykola-mokhnach** [comment]
Location by id is done on iOS by using MobileBy.AccessibilityId locator type instead of the standard Selenium's By.Id. That is why it does not work. Try to use this special locator class for iOS instead (though, I'm not sure how it works in C# and where it is declared since I only use Java).

**Comment by Can-too** [comment]
Many thanks, however the code that I included in the issue is the same code, that I rewrote in c#. Previously I used Java and didn't require the locator to find the elements on the browser web page? Why does Java test case code that work fine without locators and this c# code not?

**Comment by Can-too** [comment]
Many thanks for your advice previously. What I did was upgrade my selenium web driver. And the previous erroneous code worked without any locators. I didn't upgrade from a very low version either it was a minor version change but the result was a previous code that wasn't working is now working fine.

I just wanted to pass this on to you so if you have issues that come along with this type of problem, perhaps an upgrade to the latest version of the web driver will resolve things.
Kind regards,

Can-too

**Comment by SrinivasanTarget** [comment]
@triager please close
