### ISSUE TITLE
Appium inspector showing elements as invisible which are actually visible

### ISSUE THREAD

**Issue by shanthi2016** [appium/appium#6635]
Hi All,

I am trying to automate iOS app using Appium.

It has UIViews (UILabel, UIButton, UIImageView) in a UICollectionViewCell in a UICollectionView.

When I am looking for elements in the Appium inspector,all the UICollectionView elements are showing as invisible in the appium inspector( Checking the show invisible checkbox is displaying the elements).

It is returning Nosuchelementfoundexception when i am using isDispayed().

I want to access those elements and perform the action.

Please suggest how can I resolve the issue.
## Environment

Appium Version 1.4.13 (Draco)
iOS version 9.3
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by Cazzpurr** [comment]
You are going to need to either use xpath to find the element or write a function to scroll to the element beforehand. This support ticket might also help you: https://discuss.appium.io/t/ios-accessing-control-not-in-view/97

**Comment by JALsnipe** [comment]
Hey @Cazzpurr, thanks for your reply.  I am one of @shanthi2016's colleagues.  In this case even the elements on the UICollectionViewCell subclass that is currently visible is coming up as "invisible" in the Appium inspector.  The UICollectionView also automatically scrolls between tiles.  Could that be what is causing the views to come up as invisible?  I would assume that if the cell was visible, the elements on that specific cell would appear as visible.

**Comment by jmolliver** [comment]
See my comment in this thread.
https://github.com/appium/appium/issues/4131#issuecomment-231026493

**Comment by LukasLewandowski** [comment]
Any solution for this? Clicking/tapping into "invisible" element is not working :(

(MobileBy.XPATH, '//UIAStaticText[2][@visible="false"]')

Appium throws: Original error: elementId 16 could not be tapped
