### ISSUE TITLE
Unable to launch SafariLauncher using appium 1.5.3

### ISSUE THREAD

**Issue by aluzardo** [appium/appium#6637]
## The problem

Unable to run SafariLauncher on a real ios device (iPad 4).
## Environment
- Appium version: 1.5.3
- Desktop OS/version used to run Appium: OSx Capitan
- Node.js version: v5.11.1
- Mobile platform/version under test: IOS 9.3
- Real device : Ipad 4
- Appium CLI
## Details

First problem was that appium is not able to install automatically SafariLauncher in my real device (iPad 4). The problem is:

```
WebDriverError: An unknown server-side error occurred while processing the command. Original error: Bad app: /Users/adolfocabrera/.nvm/versions/node/v5.11.1/lib/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.
```

I fixed the problem installing SafariLauncher in my iPad using Xcode. Using the project stored in `/Users/adolfocabrera/.nvm/versions/node/v5.11.1/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/safari-launcher/`

SafariLauncher is successful installed in the iPad but It is not possible to run test using appium.

The problem is that instruments is not able to found SafariLauncher

```
[debug] [Instruments] [INST STDERR] 2016-07-06 15:01:37.449 instruments[749:16722] WebKit Threading Violation - initial use of WebKit from a secondary thread.
[debug] [Instruments] [INST STDERR] Instruments Usage Error: Specified target process is invalid: com.bytearc.SafariLauncher
instruments, version 7.3 (60134)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]
```
## Link to Appium logs

https://gist.github.com/aluzardo/2bfd7975d143004ebada6946ffddc0fa
## Code To Reproduce Issue [ Good To Have ]

Using this conf.js

```
exports.config = {
    // set to "custom" instead of cucumber.
    framework: 'custom',

    // path relative to the current config file
    frameworkPath: require.resolve('protractor-cucumber-framework'),

    // relevant cucumber command line options
    cucumberOpts: {
        require: 'features/step_definitions/*.step.js',
        format: "pretty"
    },

    seleniumAddress: 'http://localhost:4723/wd/hub',
    specs: ['features/*.feature'],
    capabilities: {
        browserName: 'safari',
        'appium-version': '1.5.3',
        platformName: 'iOS',
        platformVersion: '9.3',
        deviceName: 'iPad 4',
        'udid': '39d39a8bf0d6635268e5997dae574c04246f5e2b'
    }
};
```

In this project:

https://github.com/aluzardo/protractor-cucumber-tests

PD. Maybe this issue is duplicated #6477 but here different version of appium.

**Comment by imurchie** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/safari-launcher.md
