### ISSUE TITLE
I am facing a problem when I start the appium start programmatically through my java code.

### ISSUE THREAD

**Issue by vinyasjain77** [appium/appium#6638]
When I run the code to start the appium server, I get a ideviceinstaller error. I have tried all possible things to get rid of this error.

Here are the things that I have done:
1. Uninstall ideviceinstaller
2. Install ideviceinstaller again using --HEAD

Also viewed a lot of threads for this problem, but I found nothing substantial. What is the way to get rid of this error.  
## Environment
- Appium version 1.4.13
- Desktop OS/version used to run Appium: MAC
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: iOS
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe:

Below is the error log for the same:
[36minfo[39m: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
[36minfo[39m: Appium REST http interface listener started on 127.0.0.1:4723
[36minfo[39m: [debug] Non-default server args: {"address":"127.0.0.1","fullReset":true}
[36minfo[39m: Console LogLevel: debug
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[36minfo[39m: [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m [90m{"desiredCapabilities":{"app":"/Users/vinyasjain/Documents/WishboneiOS/src/inputData/Wishbone-4.12-Dev.ipa","appiumVersion":"1.4.13","platformVersion":"9.3.2","browserName":"","platformName":"iOS","udid":"d1b1886a98485433d9fd2761011801663bc67454","deviceName":"iPhone5C"}}[39m
[36minfo[39m: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.8.0_65)
[36minfo[39m: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : appiumVersion
[36minfo[39m: [debug] Using local .ipa from desired caps: /Users/vinyasjain/Documents/WishboneiOS/src/inputData/Wishbone-4.12-Dev.ipa
[36minfo[39m: [debug] Copying local zip to tmp dir
[36minfo[39m: [debug] /Users/vinyasjain/Documents/WishboneiOS/src/inputData/Wishbone-4.12-Dev.ipa copied to /var/folders/m0/tt70y77s3jv44xfhmd50006w0000gn/T/11666-66716-139nzy4/appium-app.zip
[36minfo[39m: [debug] Unzipping /var/folders/m0/tt70y77s3jv44xfhmd50006w0000gn/T/11666-66716-139nzy4/appium-app.zip
[36minfo[39m: [debug] Testing zip archive: /var/folders/m0/tt70y77s3jv44xfhmd50006w0000gn/T/11666-66716-139nzy4/appium-app.zip
[36minfo[39m: [debug] Zip archive tested clean
[36minfo[39m: [debug] Unzip successful
[36minfo[39m: [debug] Using locally extracted app: /var/folders/m0/tt70y77s3jv44xfhmd50006w0000gn/T/11666-66716-139nzy4/Payload/Wishbone.app
[36minfo[39m: [debug] Creating new appium session fc48f1ac-b6bd-4eef-9ac3-2cf7e42aadcc
[36minfo[39m: [debug] Removing any remaining instruments sockets
[36minfo[39m: [debug] Cleaned up instruments socket /tmp/instruments_sock
[36minfo[39m: [debug] Auto-detecting iOS udid...
[36minfo[39m: [debug] Not auto-detecting udid, running on sim
[36minfo[39m: [debug] Could not parse plist file (as binary) at /var/folders/m0/tt70y77s3jv44xfhmd50006w0000gn/T/11666-66716-139nzy4/Payload/Wishbone.app/en.lproj/Localizable.strings
[36minfo[39m: Will try to parse the plist file as XML
[36minfo[39m: [debug] Could not parse plist file (as XML) at /var/folders/m0/tt70y77s3jv44xfhmd50006w0000gn/T/11666-66716-139nzy4/Payload/Wishbone.app/en.lproj/Localizable.strings
[33mwarn[39m: Could not parse app Localizable.strings assuming it doesn't exist
[36minfo[39m: [debug] Getting bundle ID from app
[36minfo[39m: [debug] Parsed app Info.plist (as binary)
[36minfo[39m: [debug] Creating instruments
[36minfo[39m: [debug] Preparing uiauto bootstrap
[36minfo[39m: [debug] Dynamic bootstrap dir: /Users/vinyasjain/Library/Application Support/appium/bootstrap
[36minfo[39m: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
[36minfo[39m: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
[36minfo[39m: [debug] Dynamic bootstrap path: /Users/vinyasjain/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js
[36minfo[39m: [debug] Reusing dynamic bootstrap: /Users/vinyasjain/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js
[36minfo[39m: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog
[33mwarn[39m: Could not capture device log using libimobiledevice idevicesyslog. Libimobiledevice probably isn't installed
[36minfo[39m: [debug] Attempting iOS device log capture via deviceconsole
[36minfo[39m: [debug] Creating iDevice object with udid d1b1886a98485433d9fd2761011801663bc67454
[36minfo[39m: [debug] Couldn't find ideviceinstaller, trying built-in at /Applications/Appium.app/Contents/Resources/node_modules/appium/build/libimobiledevice-macosx/ideviceinstaller
[31merror[39m: Could not initialize ideviceinstaller; make sure it is installed and works on your system
[36minfo[39m: [debug] Cleaning up appium session
[31merror[39m: Failed to start an Appium session, err was: Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
[36minfo[39m: [debug] Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
    at [object Object].IOS.getIDeviceObj (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:909:13)
    at [object Object].IOS.installToRealDevice (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:856:32)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:607:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:246:17
    at iterate (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:146:13)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:157:25
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:248:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:612:34
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-crash-log.js:52:5)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-crash-log.js:27:5)
    at f (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/glob/node_modules/once/once.js:17:25)
    at Glob.<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/glob/glob.js:131:7)
    at Glob.emit (events.js:107:17)
    at Glob._finish (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/glob/glob.js:168:8)
    at done (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/glob/glob.js:157:12)
    at Glob._processReaddir2 (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/glob/glob.js:351:12)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/glob/glob.js:288:17
    at RES (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/glob/node_modules/inflight/inflight.js:23:14)
    at f (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/glob/node_modules/once/once.js:17:25)
    at Glob._readdirEntries (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/glob/glob.js:480:10)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/glob/glob.js:457:12
    at FSReqWrap.oncomplete (fs.js:95:15)
[36minfo[39m: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not initialize ideviceinstaller; make sure it is installed and works on your system)","origValue":"Could not initialize ideviceinstaller; make sure it is installed and works on your system"},"sessionId":null}
[36minfo[39m: [37m<-- POST /wd/hub/session [39m[31m500[39m[90m 6379.262 ms - 300[39m [90m[39m

Immediate help is much appreciated.

Thanks in advance.

**Comment by SrinivasanTarget** [comment]
@vinyasjain77 Are you able to install the app using ideviceinstaller manually? Can you please install ideviceinstaller through brew and give a try?

**Comment by vinyasjain77** [comment]
I have done that. Still no success. @SrinivasanTarget

**Comment by mykola-mokhnach** [comment]
Make sure the the path to ideviceinstaller's parent folder is present in PATH environment variable and this environment is visible to Appium service. 
How did you install ideviceinstaller itself?
```bash
brew install -g ideviceinstaller
```
Right?

Try Appium 1.5 if nothing helps.

**Comment by vinyasjain77** [comment]
How do I set the environment variable for ideviceinstaller? Can you share that here? 

I used brew install --HEAD ideviceinstaller to install ideviceinstaller. @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
Not for the ideviceinstaller, but rather for Appium service. By default a process inherits the environment from its parent process. Which means, if you execute Appium from Terminal, for example, then you have to make sure first, that this Terminal has correct env set:
```bash
env | grep PATH
```
and that you can execute ideviceinstaller without providing full path to it:
```bash
ideviceinstaller --help
```

**Comment by knreddy036** [comment]
Before executing the script Set this  PATh=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin in Run configuration under environment section. You will not face any issue

**Comment by SrinivasanTarget** [comment]
@triager please close
