### ISSUE TITLE
driver.swipe() stopped working for iOS - Appium 1.5.X

### ISSUE THREAD

**Issue by vikaspune** [appium/appium#6639]
## The problem

Appium swipe [ driver.swipe() method ] stopped working for iOS after upgrading Appium to 1.5.X

## Environment

* Appium version that exhibits the issue: 1.5.X
* Last Appium version that did not exhibit the issue (if applicable):1.4.13
* Desktop OS/version used to run Appium: OS X El Capitan (10.11.5)
* Node.js version (unless using Appium.app|exe): Using appium App
* Mobile platform/version under test: iPhone 6 with iOS 8.4.1 & 8.4.2 (also did not work on iOS 9.X)
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe: Appium App

## Details

I have been using Appium V1.3, V1.4. Recently I upgraded Appium to 1.5.2 and my scripts stopped working after upgrade. The issue is with - driver.swipe(), It was neither performing swipe not throwing exception.
I tried upgrading to 1.5.3 but no luck. I reverted back to V1.4.13 and script started working. I have tried on 1.4.8 also works.

## Link to Appium logs
Including log for driver.swipe() ->

[HTTP] --> POST /wd/hub/session/d8914eec-edc3-4b75-afaa-f742eacd1c7e/touch/perform {"actions":[{"action":"press","options":{"x":187,"y":610}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":187,"y":56}},{"action":"release","options":{}}]}
 [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
[debug] [iOS] Executing iOS command 'performTouch'
 [debug] [UIAuto] Sending command to instruments: target.touch([{"touch":[{"x":187,"y":610}],"time":0.2},{"touch":[{"x":187,"y":610}],"time":1.2},{"touch":[{"x":374,"y":666}],"time":1.4}])
 [debug] [Instruments] [INST] 2016-07-07 07:19:35 +0000 Debug: Got new command 8 from instruments: target.touch([{"touch":[{"x":187,"y":610}],"time":0.2},{"touch":[{"x":187,"y":610}],"time":1.2},{"touch":[{"x":374,"y":666}],"time":1.4}])
 [debug] [Instruments] [INST] 2016-07-07 07:19:35 +0000 Debug: evaluating target.touch([{"touch":[{"x":187,"y":610}],"time":0.2},{"touch":[{"x":187,"y":610}],"time":1.2},{"touch":[{"x":374,"y":666}],"time":1.4}])
 [debug] [Instruments] [INST] 2016-07-07 07:19:35 +0000 Debug: target.touch(__NSCFArray)
 [debug] [UIAuto] Socket data received (25 bytes)
 [debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
[MJSONWP] Responding to client with driver.performTouch() result: null
 [HTTP] <-- POST /wd/hub/session/d8914eec-edc3-4b75-afaa-f742eacd1c7e/touch/perform 200 1912 ms - 76 

## Code To Reproduce Issue 
//driver   is already initialized with IOSDriver<>
driver.swipe(187, 610, 187, 56, 1000);

**Comment by VTINFOJames** [comment]
I am having a similar problem with Swipe in Appium 1.5.3 and iOS 9.3 testing a native iOS app on a real device with Java.

My Code:

`element = (IOSElement) driver.findElementById(elementName).findElement(By.className("UIAStaticText"));
element.swipe(SwipeElementDirection.DOWN,1000);`

Appium Console Output for this command:

`2016-07-08 10:00:51:490 - [debug] [Instruments] [INST] 2016-07-08 14:00:51 +0000 Debug: Got new command 19 from instruments: target.touch([{"touch":[{"x":383,"y":709}],"time":0.2},{"touch":[{"x":383,"y":709}],"time":1.2},{"touch":[{"x":766,"y":1438}],"time":1.4}])

2016-07-08 10:00:51:496 - [debug] [Instruments] [INST] 2016-07-08 14:00:51 +0000 Debug: evaluating target.touch([{"touch":[{"x":383,"y":709}],"time":0.2},{"touch":[{"x":383,"y":709}],"time":1.2},{"touch":[{"x":766,"y":1438}],"time":1.4}])

2016-07-08 10:00:51:501 - [debug] [Instruments] [INST] 2016-07-08 14:00:51 +0000 Debug: target.touch(__NSCFArray)

2016-07-08 10:00:52:731 - [debug] [Instruments] [INST] 2016-07-08 14:00:52 +0000 Debug: point is not within the bounds of the screen

2016-07-08 10:00:53:081 - [debug] [UIAuto] Socket data received (70 bytes)

2016-07-08 10:00:53:082 - [debug] [UIAuto] Got result from instruments: {"status":17,"value":"point is not within the bounds of the screen"}

2016-07-08 10:00:53:087 - [HTTP] <-- POST /wd/hub/session/7069d81e-4956-425e-b88a-e0f80840b0da/touch/perform 500 2462 ms - 131 

2016-07-08 10:00:53:344 - [debug] [Instruments] [INST] 2016-07-08 14:00:52 +0000 Error: VerboseError: point is not within the bounds of the screen

2016-07-08 10:00:53:746 - [debug] [Instruments] [INST] 2016-07-08 14:00:52 +0000 Error: Error during eval: touch@[native code]
       eval code
eval@[native code]
startProcessing@file:///Applications/Appium%202.app/Contents/Resources/node_modules/EE92186E-1685-4C47-97B1-5E3C503A5589/bootstrap-67786b2caff875f6.js:2793:30
bootstrap@file:///Applications/Appium%202.app/Contents/Resources/node_modules/EE92186E-1685-4C47-97B1-5E3C503A5589/bootstrap-67786b2caff875f6.js:2861:31
global code@file:///Applications/Appium%202.app/Contents/Resources/node_modules/EE92186E-1685-4C47-97B1-5E3C503A5589/bootstrap-67786b2caff875f6.js:2870:10

`

**Comment by mhernandez8888** [comment]
I think this is the issue you guys are running into. https://github.com/appium/appium/issues/6257#issuecomment-196949576

**Comment by boney246** [comment]
VTINFOJames can you plea explain how are you finding xpaths for a native elements since the Native elements are only on ipad/tablet. And we cannot get page source for Apps unlike desktop we can use firebug 
I am trying to get page source by driver.getpagesource() gives xml 
And working with these xml locators taking lot time when running scripts 
Sample XPATH is //UIAButton[@name='SOMENAME']

**Comment by adrianmatean** [comment]
Hi all,
Same issue here after updating to Appium 1.5.3, iPhone 5S with 9.3.1. Performing swipe with points within the screen leads to "point is not within the bounds of the screen". In 1.4.8 worked correctly.

The code is simple (Java):
`drive.swipe(startx, starty, endx, endy, duration);`

Some logs from my app, we can see that the points are within the bounds:
`Swiping from point 2/142 to 2/562. Screen size is 320/568. Duration: 1000 ms`

Appium logs show a point 704 (not sure I read the logs right):
`[debug] [Instruments] [INST] 2016-07-20 07:27:09 +0000 Debug: Got new command 53 from instruments: target.touch([{"touch":[{"x":2,"y":142}],"time":0.2},{"touch":[{"x":2,"y":142}],"time":1.2},{"touch":[{"x":4,"y":704}],"time":1.4}])

[debug] [Instruments] [INST] 2016-07-20 07:27:09 +0000 Debug: evaluating target.touch([{"touch":[{"x":2,"y":142}],"time":0.2},{"touch":[{"x":2,"y":142}],"time":1.2},{"touch":[{"x":4,"y":704}],"time":1.4}])

[debug] [Instruments] [INST] 2016-07-20 07:27:09 +0000 Debug: target.touch(__NSCFArray)

[iOSLog] [IOS_SYSLOG_ROW] Jul 20 10:27:10 ngtvs-iPhone MobileGestaltHelper[86] <Error>: libMobileGestalt MobileGestalt.c:281: server_access_check denied access to question UniqueDeviceID for pid 4286

[iOSLog] [IOS_SYSLOG_ROW] Jul 20 10:27:10 ngtvs-iPhone ScriptAgent[4286] <Error>: libMobileGestalt MobileGestaltSupport.m:151: pid 4286 (ScriptAgent) does not have sandbox access for re6Zb+zwFKJNlkQTUeT+/w and IS NOT appropriately entitled
[iOSLog] [IOS_SYSLOG_ROW] Jul 20 10:27:10 ngtvs-iPhone ScriptAgent[4286] <Error>: libMobileGestalt MobileGestalt.c:542: no access to UniqueDeviceID (see <rdar://problem/11744455>)

[debug] [Instruments] [INST] 2016-07-20 07:27:10 +0000 Debug: point is not within the bounds of the screen

[debug] [Instruments] [INST] 2016-07-20 07:27:10 +0000 Error: VerboseError: point is not within the bounds of the screen

[debug] [UIAuto] Socket data received (70 bytes)

[debug] [UIAuto] Got result from instruments: {"status":17,"value":"point is not within the bounds of the screen"}`

**Comment by adrianmatean** [comment]
Workaround in Java for swipe. 
Original line of code:
`drive.swipe(startx, starty, endx, endy, duration);`

Workaround:
`TouchAction ta1 = new TouchAction(AppiumDriverInstance.getInstance());`
`MultiTouchAction ma = new MultiTouchAction(AppiumDriverInstance.getInstance());`
`ta1.press(startx, starty).waitAction(duration).moveTo(endx - startx, endy - starty).release();`
`ma.add(ta1).perform();`

**Comment by boney246** [comment]
Do we need to update java client to 4.0 for this work around

**Comment by VTINFOJames** [comment]
I just found this: 
@SergeyTichomirov
> But it seems many other users had used absolute coordinates before 1.5.0 was released. I was forced to buid and share a temporary snapshot there: https://github.com/appium/java-client/issues/350#issuecomment-2120707668 in order to keep their code working

[https://github.com/appium/java-client/issues/350#issuecomment-212070766](url)

**Comment by boney246** [comment]
This worked perfectly

**Comment by mbknieri** [comment]
I am seeing an issue with Appium's swipe that was mentioned originally in the issue being opened, where calling driver.swipe() neither performs the swipe or throws an exception. I'm getting similar logs where instrument's response is: Responding to client with driver.performTouch() result: null.

I previously had the other issue mentioned in the comments where the point is not within bounds of the screen and that was resolved by upgrading java client to 4.0. I am wondering, however, if anyone can help with the original issue opened by @vikaspune.

**Comment by SrinivasanTarget** [comment]
@triager please label: Bug

**Comment by vikaspune** [comment]
Just to inform , I upgraded my maven dependency to use java client to 4.1.2 and the same existing code worked.

**Comment by vikas-thange-twc** [comment]
Reopening this issues as this still exists.
