### ISSUE TITLE
Appium 1.5.3 ScrollTo does not work for iOS

### ISSUE THREAD

**Issue by JordanGS** [appium/appium#6640]
## The problem

The 1.5.3 patch broke the Scroll To function that was part of the library.

## Environment

Appium 1.5.3
OSX
iOS 9.3
All iPhone simulators
iPhone 6s (real)
Node 6.2.2 (I tried downgrading to 0.12 and made no difference)

## Details

```
def scroll_to(self, locator):
        """Scrolls to element"""
        driver = self._current_application()
        element = self._element_find(locator, True, True)
        driver.execute_script("mobile: scrollTo", {"element": element.id})
```

is the python function to scroll to the element

## Link to Appium logs

WebDriverException: Message: Unknown command, all the mobile commands except scroll have been removed.
```

[MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath",".//*[@name='Smart...
[debug] [iOS] Executing iOS command 'findElements'
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [UIAuto] Sending command to instruments: au.mainApp().getTreeForXML()
[debug] [Instruments] [INST] 2016-07-07 17:50:49 +0000 Debug: Got new command 20 from instruments: au.mainApp().getTreeForXML()

[debug] [UIAuto] Socket data received (8192 bytes)
[debug] [UIAuto] Socket data received (6049 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"my mobile","label":"my mobile","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":0,"width":320,"height":480},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enab
[debug] [UIAuto] Sending command to instruments: au.getElementsByIndexPaths(["/0/0/1/2","/0/0/1/2/0"])

[debug] [UIAuto] Socket data received (56 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":[{"ELEMENT":"1"},{"ELEMENT":"2"}]}
[MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"1"},{"ELEMENT"...
[HTTP] <-- POST /wd/hub/session/d6b0b303-8fcc-4397-9372-30945f5b9c9c/elements 200 2260 ms - 105 
[HTTP] --> POST /wd/hub/session/d6b0b303-8fcc-4397-9372-30945f5b9c9c/execute {"sessionId":"d6b0b303-8fcc-4397-9372-30945f5b9c9c","args":[{"element":"1"}],"script":"mobile: scrollTo"}
[MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: scrollTo",[{"elem...
[debug] [iOS] Executing iOS command 'execute'
[HTTP] <-- POST /wd/hub/session/d6b0b303-8fcc-4397-9372-30945f5b9c9c/execute 500 1 ms - 159 
[HTTP] --> GET /wd/hub/session/d6b0b303-8fcc-4397-9372-30945f5b9c9c/screenshot {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["d6b0b303-8fcc-4397-9372-3...
[debug] [iOS] Executing iOS command 'getScreenshot'

```

## Workaround

`driver.execute_script("mobile: scroll", {"direction": 'down', 'element': element})`

This was my simple workaround to the problem but it doesn't solve it. I want to scroll to the element! It NEEDS to be in view or it will click the wrong element since it works on an x and y location basis. This will only do ONE single swipe down however, so if multiple swipes are required then will workaround will FAIL!

## Question

Can anyone share some thoughts on why ScrollTo is no longer supported? Is this a bug? If it's intended functionality, can we add in the old functionality back please.

Thank you!

**Comment by JaniJegoroff** [comment]
I asked same question few months back: https://github.com/appium/appium/issues/6242

**Comment by JordanGS** [comment]
@JaniJegoroff Well that is highly inconvenient since touch doesn't work nearly as well. Thanks a lot for the answer mate, i really appreciate it since i couldn't find an answer myself :)
