### ISSUE TITLE
Appium WD How To?

### ISSUE THREAD

**Issue by JordanGS** [appium/appium#6643]
## The problem

appium.io says to install the client via `npm install wd`, does this refer to the GUI client? If so, how do i run the GUI client after it's installed because on the terminal `appium` doesn't start the gui client but the text based one.

**Comment by mykola-mokhnach** [comment]
What do you want to achieve? Appium itself is just a NodeJS module, which acts as a service. There is nothing to show in UI. In case you just want some simple visual interface for service execution, then you can try https://github.com/appium/appium-dot-app (Mac OS X only).
Also, you may use this inspector if you just want to debug the UI tree generated by Appium (iOS only):
https://github.com/mykola-mokhnach/Appium-iOS-Inspector (WebBrowser-based)

**Comment by JordanGS** [comment]
@mykola-mokhnach appium has a gui interface of the server available for download, i thought `npm install wd` was the command line version to install it instead of from their website, maybe i'm wrong?

**Comment by imurchie** [comment]
`wd` is a JavaScript Selenium webdriver client. In tests written in JavaScript it gives commands to interact with the Selenium server (or Appium).

https://github.com/admc/wd

**Comment by SrinivasanTarget** [comment]
@triager please close
