### ISSUE TITLE
Critical : Appium 1.5.* running scripts very slow on iPhone real safari browser

### ISSUE THREAD

**Issue by jawlitkp** [appium/appium#6644]
## The problem

Scripts are running very slow with appium 1.5.2 version , but with appium 1.4.3 version ,it is very fast .Suppose for each testscript in appium 1.4.3 ,it takes 80 sec ,but with appium 1.5.2 ,it is taking 400 sec 
## Environment

Appium version (or git revision) that exhibits the issue: Appium 1.5.3/1.5.2
Last Appium version that did not exhibit the issue (if applicable): Appium 1.4.13
Desktop OS/version used to run Appium: OS X EI Captain 10.11.5
Node.js version (unless using Appium.app|exe): 1.6.2
Mobile platform/version under test: iOS 9.3.2
Real device or emulator/simulator: Real device
Appium CLI or Appium.app|exe: Appium CLI and Appium.app
## Details

Scripts are running very slow with appium 1.5.2 version , but with appium 1.4.3 version ,it is very fast .Suppose for each testscript in appium 1.4.3 ,it takes 80 sec ,but with appium 1.5.2 ,it is taking 400 sec

**Comment by imurchie** [comment]
Can you provide more information? Logs (with timestamps on) for two runs? 

For iOS 9 you need to take extra steps with instruments-without-delay (see https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/iwd_xcode7.md) so that might be a problem.

**Comment by JordanGS** [comment]
@jawlitkp 1.5.X has been running scripts that used to take 4 minutes on 1.4.X, now take 10 minutes for me. These are native applications, the delay between actions seems to have gotten a lot longer.

**Comment by jawlitkp** [comment]
Tried above solution but did not work out.even it broke my working code with older version of appium

**Comment by johnmorrisQADeveloper** [comment]
I am facing the same issue, where test on Appium 1.6 takes another 30 seconds more than Appium 1.4.

**Comment by qakapil** [comment]
@imurchie with Appium1.6 my tests are running pretty fast on iPhone (real devices) but on iPad they are extremely slow. Should I create a separate issue for it or we can track it here ?

**Comment by imurchie** [comment]
I guess start a new issue, @qakapil . Make sure the logs have timestamps on so that we can see where things are going slow.

**Comment by qakapil** [comment]
@imurchie - https://github.com/appium/appium/issues/7046

**Comment by jawlitkp** [comment]
Are you running using safari launcher? My test is still slow and I am using safari launcher. So at this point I got stuck using appium 1.4.13. May be for you it's running faster because you might be testing app but I my case I am testing mobile website

**Comment by qakapil** [comment]
No, I am testing the native app.

**Comment by jawlitkp** [comment]
Ok so that's the reason, I have been trying on all 1.5* and 1.6* and so far I haven't got any luck

**Comment by qakapil** [comment]
@imurchie  Any update on this issue ?

**Comment by jawlitkp** [comment]
Any update on this issue ?
