### ISSUE TITLE
Critical : Appium 1.5.* Chrome browser crashes right after launching

### ISSUE THREAD

**Issue by jawlitkp** [appium/appium#6645]
## The problem

Appium 1.5.* Chrome browser crashes right after launching

org.openqa.selenium.remote.SessionNotFoundException: no such session (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) 

## Environment

Appium version (or git revision) that exhibits the issue: 1.5.3
Desktop OS/version used to run Appium: MacOS El Capitan
Node.js version (unless using Appium.app|exe): 6.1.0
Mobile platform/version under test: Android 6.0
Real device or emulator/simulator: Galaxy Nexus
Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Please check https://github.com/appium/appium/issues/6634
