### ISSUE TITLE
Appium script does not run on iOS simulators

### ISSUE THREAD

**Issue by rgupta95** [appium/appium#6646]
Project code is on xamarin and when i try to run appium script on iOS simulators .I could not ,getting error message that "the device that you requested is not available  " or sometimes i get "Could not extract Info.plist from application: Plist file doesn't exist:" .Earlier to this , i used to get the build from xcode and it was working fine but i am getting these two issues while running the appium script .

Please help.

**Comment by mykola-mokhnach** [comment]
Please properly fill out the initial bug reporting template. Logs, versions, code examples - everything might be useful. The current information is not enough to make any assumptions.

**Comment by fangmobile** [comment]
same here

**Comment by fangmobile** [comment]
check app location.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by SrinivasanTarget** [comment]
@rgupta95 Please reopen with proper defect template.

**Comment by angeliaw** [comment]
I met this same problem.  while run tests, it pops up Error message
An unknown server-side error occurred while processing the command. Original error: Could not extract Info.plist from application: Plist file doesn't exist:
