### ISSUE TITLE
Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c ideviceinstaller -u

### ISSUE THREAD

**Issue by gp1n3d4** [appium/appium#6648]
## The problem

I can't run appium, i've been having this error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.13 (Draco)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OS X El Capitan 10.11.5 
* Node.js version (unless using Appium.app|exe): v4.4.7 and npm v2.15.8
* Mobile platform/version under test: iphone 6s
* Real device or emulator/simulator: 
* Appium CLI or Appium.app|exe: 

## Link to Appium logs

error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c ideviceinstaller -u B6A0A86D-7927-4D3D-B827-704C62A47587 -l 

info: [debug] Installing ipa found at /Users/gp1n3d4/Music/iTunes/iTunes Media/Mobile Applications/myapp.ipa
info: [debug] Cleaning up appium session
info: [debug] Error: Command failed: /bin/sh -c ideviceinstaller -u B6A0A86D-7927-4D3D-B827-704C62A47587 -l 

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: /bin/sh -c ideviceinstaller -u B6A0A86D-7927-4D3D-B827-704C62A47587 -l \n)","killed":false,"code":2,"signal":null,"cmd":"/bin/sh -c ideviceinstaller -u B6A0A86D-7927-4D3D-B827-704C62A47587 -l ","origValue":"Command failed: /bin/sh -c ideviceinstaller -u B6A0A86D-7927-4D3D-B827-704C62A47587 -l \n"},"sessionId":null}
info: <-- POST /wd/hub/session 500 1196.128 ms - 418

**Comment by imurchie** [comment]
Where is the `ipa` file from? It looks like it is from iTunes, in which case it will not be automatable. You need to build a debug version.

**Comment by gp1n3d4** [comment]
Thank you @imurchie I will do that and try it again...

**Comment by gp1n3d4** [comment]
can I build a debug version if i just have the ipa app. @imurchie ?

**Comment by imurchie** [comment]
No. You need the source code.

**Comment by gp1n3d4** [comment]
thanks @imurchie

**Comment by gp1n3d4** [comment]
hi @imurchie i already have my debug version but it does do the same error.

**Comment by imurchie** [comment]
What happens if you run the ideviceinstaller command by itself.

**Comment by gp1n3d4** [comment]
hi @imurchie i run this in dhe command line: and if you see i have an X in ==> Dependencies

Gersons:~ gersonpineda$ which ideviceinstaller
/usr/local/bin/ideviceinstaller
Gersons:~ gersonpineda$ brew info ideviceinstaller
ideviceinstaller: stable 1.1.0 (bottled), HEAD
Cross-platform library and tools for communicating with iOS devices
http://www.libimobiledevice.org/
/usr/local/Cellar/ideviceinstaller/1.1.0_2 (7 files, 63K) *
  Poured from bottle on 2016-07-08 at 09:49:56
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ideviceinstaller.rb
==> Dependencies
Build: pkg-config ✘
Required: libimobiledevice ✔, libzip ✔
Gersons:~ gersonpineda$

**Comment by gp1n3d4** [comment]
@imurchie  this is the log: 

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: <-- GET /wd/hub/status 200 5.365 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
info: <-- GET /wd/hub/status 200 1.456 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

info: --> GET /wd/hub/sessions {}
info: [debug] Responding to client with success: {"status":0,"value":[]}

info: <-- GET /wd/hub/sessions 200 1.710 ms - 23 {"status":0,"value":[]}

info: --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","platformVersion":"9.3","newCommandTimeout":"999999","automationName":"Appium","deviceName":"iPhone 6s"}}

info: Client User-Agent string: Appium (unknown version) CFNetwork/760.5.1 Darwin/15.5.0 (x86_64)

info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************

info: [debug] Using local app from command line: /Users/gersonpineda/Desktop/demo.app

info: [debug] Creating new appium session c5c3dae3-2f6f-4f93-a72c-af461f171d0d
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Auto-detecting iOS udid...
info: [debug] Not auto-detecting udid, running on sim
info: [debug] Could not parse plist file (as binary) at /Users/gersonpineda/Desktop/demo.app/en.lproj/Localizable.strings
info: Will try to parse the plist file as XML
info: [debug] Could not parse plist file (as XML) at /Users/gersonpineda/Desktop/demo.app/en.lproj/Localizable.strings
warn: Could not parse app Localizable.strings assuming it doesn't exist
info: [debug] Getting bundle ID from app

info: [debug] Parsed app Info.plist (as binary)
info: [debug] Creating instruments
info: [debug] Preparing uiauto bootstrap
info: [debug] Dynamic bootstrap dir: /Users/gersonpineda/Library/Application Support/appium/bootstrap
info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

info: [debug] Dynamic bootstrap path: /Users/gersonpineda/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js
info: [debug] Reusing dynamic bootstrap: /Users/gersonpineda/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js

info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog

info: [debug] Creating iDevice object with udid B6A0A86D-7927-4D3D-B827-704C62A47587

info: [debug] App is not installed. Will try to install the app.

info: [debug] Cleaning up appium session

error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c ideviceinstaller -u B6A0A86D-7927-4D3D-B827-704C62A47587 -i /Users/gersonpineda/Desktop/demo.app


info: [debug] Error: Command failed: /bin/sh -c ideviceinstaller -u B6A0A86D-7927-4D3D-B827-704C62A47587 -i /Users/gersonpineda/Desktop/demo.app

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: /bin/sh -c ideviceinstaller -u B6A0A86D-7927-4D3D-B827-704C62A47587 -i /Users/gersonpineda/Desktop/demo.app\n)","killed":false,"code":2,"signal":null,"cmd":"/bin/sh -c ideviceinstaller -u B6A0A86D-7927-4D3D-B827-704C62A47587 -i /Users/gersonpineda/Desktop/demo.app","origValue":"Command failed: /bin/sh -c ideviceinstaller -u B6A0A86D-7927-4D3D-B827-704C62A47587 -i /Users/gersonpineda/Desktop/demo.app\n"},"sessionId":null}
info: <-- POST /wd/hub/session 500 168.021 ms - 526

**Comment by imurchie** [comment]
I guess I should have been more specific. What happens when you actually _run_ `ideviceinstaller`? 

```
ideviceinstaller -u B6A0A86D-7927-4D3D-B827-704C62A47587 -i /Users/gersonpineda/Desktop/demo.app
```

**Comment by gp1n3d4** [comment]
@imurchie this is the result. 

Gersons:~ gersonpineda$ ideviceinstaller -u B6A0A86D-7927-4D3D-B827-704C62A47587 -i /Users/gersonpineda/Desktop/demo.app
ERROR: Invalid UDID specified
Usage: ideviceinstaller OPTIONS
Manage apps on iOS devices.

  -u, --udid UDID	Target specific device by its 40-digit device UDID.
  -l, --list-apps	List apps, possible options:
       -o list_user	- list user apps only (this is the default)
       -o list_system	- list system apps only
       -o list_all	- list all types of apps
       -o xml		- print full output as xml plist
  -i, --install ARCHIVE	Install app from package file specified by ARCHIVE.
                       	ARCHIVE can also be a .ipcc file for carrier bundles.
  -U, --uninstall APPID	Uninstall app specified by APPID.
  -g, --upgrade ARCHIVE	Upgrade app from package file specified by ARCHIVE.
  -L, --list-archives	List archived applications, possible options:
       -o xml		- print full output as xml plist
  -a, --archive APPID	Archive app specified by APPID, possible options:
       -o uninstall	- uninstall the package after making an archive
       -o app_only	- archive application data only
       -o docs_only	- archive documents (user data) only
       -o copy=PATH	- copy the app archive to directory PATH when done
       -o remove	- only valid when copy=PATH is used: remove after copy
  -r, --restore APPID	Restore archived app specified by APPID
  -R, --remove-archive APPID  Remove app archive specified by APPID
  -o, --options		Pass additional options to the specified command.
  -h, --help		prints usage information
  -d, --debug		enable communication debugging

**Comment by imurchie** [comment]
Is that the UDID of your device?

**Comment by gp1n3d4** [comment]
the UDID of my device is the one from xcode I'am trying to use the simulator one.

**Comment by gp1n3d4** [comment]
@imurchie the UDID of my device is the one from xcode I'am trying to use the simulator one.

**Comment by imurchie** [comment]
I don't understand. You are trying to run a test on a simulator?

**Comment by gp1n3d4** [comment]
@imurchie  correct.

**Comment by imurchie** [comment]
Oh. Then you do not specify a UDID at all. Appium is assuming you are running on a real device. `ideviceinstaller` works for real devices only.

Remove the UDID from your desired capabilities.

**Comment by gp1n3d4** [comment]
thank you so much.. is working now... I've been reading every where and no one explain that. lol.. thank you again.

**Comment by imurchie** [comment]
No problem! I'm glad things worked out!

**Comment by psphanireddy** [comment]
@imurchie  ideviceinstaller -u dac7004f8b63aa7a6de8754c110c0798ef41c409 -i /Users/Downloads/Users-2/Shared/demo.app
Uploading demo.app package contents... DONE.
Installing '(null)'
 - CreatingStagingDirectory (5%)
 - ExtractingPackage (15%)
 - InspectingPackage (20%)
 - TakingInstallLock (20%)
 - PreflightingApplication (30%)
 - VerifyingApplication (40%)
 - Error occurred: ApplicationVerificationFailed

I am getting this error. Can you please help me on it

**Comment by imurchie** [comment]
This usually means that the app is not built for the real device, or is not signed correctly.

**Comment by gp1n3d4** [comment]
Hi @imurchie any idea why is not working again. :( 

<img width="1097" alt="screenshot 2017-01-22 22 14 55" src="https://cloud.githubusercontent.com/assets/20362327/22193475/71553f9a-e0f0-11e6-9797-eb83e8d6230c.png">
<img width="1184" alt="screenshot 2017-01-22 22 14 29" src="https://cloud.githubusercontent.com/assets/20362327/22193484/777c5430-e0f0-11e6-85f8-ae61bbd9e2c9.png">

**Comment by imurchie** [comment]
Not without logs, no. This looks like an Xcode version mismatch but I have no way of telling.

**Comment by gersonpineda** [comment]
@imurchie this is the log, and the xcode version is the 8.2.1

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' lib/server/main.js --address "127.0.0.1" --command-timeout "7200" --pre-launch --debug-log-spacing --platform-version "8.4" --platform-name "iOS" --app "/Users/gersonpineda/Desktop/demo.app" --full-reset --show-ios-log --device-name "iPhone 6"

info: [debug] Starting Appium in pre-launch mode

info: Pre-launching app
info: *************************************
info: *************************************
info: *************************************
info: *************************************

info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: ****        NEW SESSION           ***
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: *************************************
info: [debug] Using local app from command line: /Users/gersonpineda/Desktop/demo.app
info: [debug] Creating new appium session 50a69d1d-bc98-4b41-bf1c-dc30f71372b3
info: [debug] Removing any remaining instruments sockets
info: [debug] Cleaned up instruments socket /tmp/instruments_sock
info: [debug] Setting Xcode version

info: [debug] Xcode version set to 8.2.1

info: [debug] Setting iOS SDK Version
info: [debug] iOS SDK Version set to 10.2
info: [debug] Checking whether instruments supports our device string
info: [debug] Getting list of devices instruments supports
info: [debug] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

info: [debug] Getting device string from opts: {"forceIphone":false,"forceIpad":false,"xcodeVersion":"8.2.1","iOSSDKVersion":"10.2","deviceName":"iPhone 6","platformVersion":"8.4"}

info: [debug] fixDevice is on
info: [debug] Final device string is: 'iPhone (8.4 Simulator)'

error: Could not find a device to launch. You requested 'iPhone (8.4 Simulator)', but the available devices were: ["iPad Air (10.2) [38C83A8E-69EC-47EC-89AC-7DE0BFD2CC24] (Simulator)","iPad Air 2 (10.2) [BC0F1B9D-1E4A-4FFC-A4E6-FFBC80C651FB] (Simulator)","iPad Pro (12.9 inch) (10.2) [BE6440CA-5B7F-4907-9588-7803EA2A4E9A] (Simulator)","iPad Pro (9.7 inch) (10.2) [0491A5B4-EEF9-4ED6-864B-A519139991ED] (Simulator)","iPad Retina (10.2) [85DF6291-D623-4048-9254-C495E8634306] (Simulator)","iPhone 5 (10.2) [3256FC90-3486-412B-9FCD-B04B67940296] (Simulator)","iPhone 5s (10.2) [AF8DAA0B-5306-4557-A049-E497BCD8EE09] (Simulator)","iPhone 6 (10.2) [BDBD4E16-8ADA-428B-8D2D-5405605892BD] (Simulator)","iPhone 6 Plus (10.2) [D211272C-0908-485F-B0C0-1082DED5CBE7] (Simulator)","iPhone 6s (10.2) [6A7466AB-ACE4-4B7D-8C51-F9739424E618] (Simulator)","iPhone 6s Plus (10.2) [FAD4B02F-1887-4B3A-A619-AEAE61E0DF8C] (Simulator)","iPhone 7 (10.2) [F2B1F78F-876B-4C40-91CF-3F6DD56F53EE] (Simulator)","iPhone 7 (10.2) + Apple Watch Series 2 - 38mm (3.1) [0A17D43C-3101-4D1E-B377-9ACFCB56FC44] (Simulator)","iPhone 7 Plus (10.2) [ADEE7C5F-40D3-47FE-AEC2-BADCA4B0167F] (Simulator)","iPhone 7 Plus (10.2) + Apple Watch Series 2 - 42mm (3.1) [3DB7C6B0-FAFE-44C8-B72D-DF0DE50A74D0] (Simulator)","iPhone SE (10.2) [21C55139-C3DC-4525-9A29-60EE4CBBB708] (Simulator)"]

**Comment by imurchie** [comment]
What version of Appium are you using? This problem is that the system is trying to use an `Instruments`-based system but Xcode 8+ does not have `Instruments`. To test iOS 8.4 you will need to use at most Xcode 7.3.

**Comment by gersonpineda** [comment]
what about testing iOS 10.2 that is the one that I really want to test. also the appium version is 1.4.13

**Comment by imurchie** [comment]
You cannot test iOS 10+ on Appium below version 1.6. The way in which Apple allows automating the device changed and earlier versions of Appium do not support the new way.

**Comment by gersonpineda** [comment]
thanks @imurchie I will download Appium 1.6 then.
