### ISSUE TITLE
Error forwarding session from selenium grid to appium node

### ISSUE THREAD

**Issue by monika07** [appium/appium#6654]
## The problem

Error forwarding the new session cannot find : Capabilities [{appPackage=com.android.browser, appActivity=com.android.browser.BrowserActivity, browserName=android, platformName=Android, version=6.0, deviceName=192.168.57.101:5555, platform=ANDROID}]
## Environment
- Appium version : 1.53.0
- Desktop OS/version used to run Appium: MAC v10.11.5
- Node.js version (unless using Appium.app|exe): v6.2.2
- Mobile platform/version under test: Android / Samsung S6 / 6.0
- Real device or emulator/simulator: Geny Motion Emulator
- Appium CLI or Appium.app|exe: from GUI
## Details

Hi, I am new to Appium and i am trying to configure appium node to selenium grid. When i use selenium grid url after configuration to start native browser on android, i am getting "Error forwarding session" issue. i am not getting any error in appium logs as the request is not being forwarded to appium. I dont know what else can i check. Please help.  I have provided Node.json, Desired capabilites.
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue

Node.json: 
`
        "capabilities": [{
                "deviceName": "192.168.57.101:5555",
                "version": "6.0",
                "maxInstances": 1,
                "platformName": "ANDROID"
        }],
        "configuration": {
                "cleanUpCycle": 2000,
                "timeout": 30000,
                "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
                "url": "http://127.0.0.1:4723/wd/hub",
                "host": "127.0.0.1",
                "port": 4723,
                "maxSession": 6,
                "register": true,
                "registerCycle": 5000,
                "hubPort": 4444,
                "hubHost": "127.0.0.1"
        }
`

Desired capability:

`DesiredCapabilities capabilities = DesiredCapabilities.android();
//capabilities for Samsung Galaxy S6        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"192.168.57.101:5555");
capabilities.setCapability(MobileCapabilityType.VERSION, "6.0");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,MobilePlatform.ANDROID);
capabilities.setCapability("appPackage","com.android.browser");
capabilities.setCapability("appActivity", "com.android.browser.BrowserActivity")`

Grid Console:

<img width="1416" alt="screen shot 2016-07-12 at 16 16 38" src="https://cloud.githubusercontent.com/assets/19171610/16770194/0a7c8950-484c-11e6-864e-c6b0d5200c20.png">

**Comment by mykola-mokhnach** [comment]
Please, make sure you provided correct capabilities to Appium. The current capabilities seem to be set incorrectly. First, you have to prepare grid configuration file and pass the path to it as command line parameter (_--nodeconfig_). Each node should provide its own configuration. Then Appium should automatically select matching node based on capabilities values. 

Read http://appium.io/slate/en/master/?java#selenium-grid for more details.
