### ISSUE TITLE
elementByName() being removed 1.5.x

### ISSUE THREAD

**Issue by blueice349** [appium/appium#6655]
## The problem

Ever sense elementByName has been removed I lost function of my automation.. I can not use XPath sense XPath would change in my list of items anytime more items are added or removed from the list. So on android I use to be able to use elementByName( 'textNameOfElement' ); sense removing this feature I can not update appium to the latest with out ALL test breaking on Android, I tried to use elementById( 'textNameOfElement' ); and that just breaks, I have set accessibility labels on everything I can in the app, but there are things I am unable to set id's for like the photo attached, they have the same ID but different text
![screen shot 2016-07-12 at 8 07 25 am](https://cloud.githubusercontent.com/assets/16051640/16770305/ab509134-4809-11e6-84c7-243bb402cfad.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.x
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: Mac OSK
* Node.js version (unless using Appium.app|exe): latest 
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by JordanGS** [comment]
@blueice349 I have the same issue, i didn't update mine to 1.5.X because it runs slower but you can just use xpath and search for the name attribute. `xpath=.//*[@name='textNameOfElement']`

**Comment by jmolliver** [comment]
You can xpath to the name attribute, but it will be slower. It looks like you can use elementById in its place. You can see they updated the sample file with it here.
https://github.com/appium/sample-code/commit/a820e4906dd239b1ade0e10de07a851b57628e26#diff-9bd16273653a34774dbf75d755146c30

**Comment by blueice349** [comment]
@jmolliver  does not work on android, but works on iOS....

**Comment by blueice349** [comment]
@JordanGS is this the same for JavaScript? so it would be .elementByXPath( './/*[ @name= 'nameOfElement' ] )?

**Comment by blueice349** [comment]
What a pain! wish I could just get elementByName put back in so the only thing I can find is doing it this way:

`it( 'should get alert for incorrect clientAccount'.green, function () {

			config.loginTest = true;
			if ( commons.isIOS() || commons.isAndroid() ) {
				return driver
				.waitForElementByXPath( '//*[ @name=\'OK\' ]', 120000 )
				.then( function ( el ) {

					commons.alertText( alerts.loginLogoutAlerts.wrongClientAccount )
					return el
					.click()
					.sleep( 1000 )
				} );

			} else {
				return driver
				.waitForElementByXPath( '//*[ @text=\'OK\' ]', 120000 )
				.then( function ( el ) {

					commons.alertText( alerts.loginLogoutAlerts.wrongClientAccount )
					return el
					.click()
					.sleep( 1000 )
				} );
			}
		} );`

**Comment by jmolliver** [comment]
With more research I found that .elementByAccessibilityId is the right way to go. Does that work for you on both iOS and Android? 

.elementByAccessibilityId('ok')

**Comment by blueice349** [comment]
Nope to both @name only works on iOS unless the element has a accessibilitylabel set. Android only works if I do @text and that don't work for iOS and accessibilityId does not work either

**Comment by blueice349** [comment]
No way to set accessibility on a optionDialog use to just use elementByName for both and it would work

**Comment by blueice349** [comment]
my work around now more a hack but it works! 

`
Commons.prototype.textToXPath = function ( text ) {
 
        var driver = config.driver;
 
        if ( this.isAndroid() ) {
                return '//*[ @text=\'' + text + ' \']';
 
        } else {
                return '//*[ @name=\'' + text + ' \']';
        }
};
 
 
//How to run function from a test
 
var commons = require( './helpers/commons.js' );
 var driver      = config.driver;
 
driver.elementByXPath( commons.textToXPath( 'elementText' ).click();
`

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by JordanGS** [comment]
@blueice349 Sorry, i didn't get a notification. Yes you found the same workaround that i found haha. In the end my i downgraded appium for iOS to 1.4.16 because scroll got removed and upgraded appium for android to 1.5.3 because without the new capabilities, my apk no longer runs. Feels like more issues were caused by the 1.5.X version than were solved.
