### ISSUE TITLE
Can appium support automating native apps which running on BES 12 tray or MDM tray

### ISSUE THREAD

**Issue by gurram1986** [appium/appium#6657]
Question: Hi, I am looking for an mobile automation using selenium. Will Appium support automation for native apps which are accessable from BES 12 tray or MDM. 
 - Looking it for iPad
 - User to login with BES 12 credentials and open BES 12 tray
 - Then click on native browser based app from BES 12 to launch continue functional testing like by keying few data and click on button/selection etc..

Could you please let me know if appium can support my requirement. Also, pls share if any alternatives. Thanks in advance.

**Comment by SrinivasanTarget** [comment]
Its a good candidate for discussion forum.Please try there.

**Comment by SrinivasanTarget** [comment]
@triager please close
