### ISSUE TITLE
Unable to switch between windows in devices using appium.

### ISSUE THREAD

**Issue by navin578** [appium/appium#6660]
I am facing issues when we try to switch between the windows in either android or IOS devices.

```
String target = "https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/";
String value = "testEnrollWindow";

String args1 = String.format("window.open('%s', '%s'); null;", target, value);
((JavascriptExecutor) driver).executeScript(args1);
```

The Above code is to open the new window this action is not performed in either I Phone or android devices.

when I try to switch it is showing this exception,

Switching code:

```
for (String winHandle : driver.getWindowHandles()) {
                if (!(parentHandle == winHandle)) {
                    driver.switchTo().window(winHandle);
                }            }
```

```
Exception:java.lang.Long cannot be cast to java.lang.String
```

I am unable to replicate this issue and haven't found much resources regarding this issue.

Is this a bug in Appium or is there any other way to switch between the windows.

Note:I am using sauce-labs to execute my tests.

**Comment by satyasrikanth** [comment]
For android 
String currentWindow=driver.getWindowHandle();
//Action that gets new window
			 int ctime=1;
			//waiting till the windows size is 2 for some time
			 while(driver.getWindowHandles().size()<3)
			 {
				Thread.sleep(5000);
				ctime++;
				if(ctime==5)
					break;
			 }
			 //Switchingn to window
			 Set<String> windows2=driver.getWindowHandles();
			 for(String window:windows2)
			 {
				 if(!window.equalsIgnoreCase(currentWindow))
				 {
					 driver.switchTo().window(window);
					 break;
				 }
				
			 }


For iOS


 
 String WebViewContext="";
 contextNames = ((AppiumDriver) driver).getContextHandles();
 for (String contextName : contextNames) {
 
 	WebViewContext=contextName;

 
 }
 ((AppiumDriver) driver).context(WebViewContext);

**Comment by navin578** [comment]
I am unable to open the window at all,the reply you have given is for swicthing between them.
Please provide code which opens window.

**Comment by satyasrikanth** [comment]
I confused with the question you started with.
For android or iOS, you need to disable popup blocker,
For android chrome driver,  you can add --disable-popup-blocking in capabilities
Similarly for iOS, you need to add safari capability "safariAllowPopups" to  true as those are simulators.

**Comment by navin578** [comment]
Yes I used these capability's but the problem is both urls (window1 url and window 2 url ) are opening in same window which makes it a single window so am facing error  "NoSuchWindowException: A request to switch to a different window could not be satisfied because the window could not be found."

**Comment by satyasrikanth** [comment]
This is not a issue, you can post question in forums.

Try this
		Set<String> windows = driver.getWindowHandles();
		String currentHandle = driver.getWindowHandle();
		((JavascriptExecutor)driver).executeScript("window.open();");
		Set<String> newWindow = driver.getWindowHandles();
		newWindow.removeAll(windows);
		String newHandle = ((String)newWindow.toArray()[0]);
		driver.switchTo().window(newHandle);

**Comment by navin578** [comment]
Thanks for you reply I will try this code

**Comment by navin578** [comment]
I have tried the above piece of code its not working.

**Comment by navin578** [comment]
It is behaving same like the mentioned above code.
