### ISSUE TITLE
Landscape - iOS : tap is not working , Probably due to the cordinates.

### ISSUE THREAD

**Issue by satyasrikanth** [appium/appium#6661]
## The problem

I can able to tap on the element using tap(int,webElement,int) or tap(int,int,int,int) in portrait mode on iOS simulator while I am unable to do that in Landscape mode
## Environment
- Appium v 2.5.3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: 10.10.5
- Node.js version (unless using Appium.app|exe): 4.4.7
- Mobile platform/version under test: iOS simulator (iPhone 5s 9.2) - Safari
- Real device or emulator/simulator: Simulator
- Appium CLI or Appium.app|exe: app
## Details

Portrait Mode : ((AppiumDriver) driver).tap(1, moElement, 200);  and tap(1, xcordinate of center of element, y cordinate of center of element, 200) is working fine.
Landscape mode :  Not tapping at all. 
Only working when nativeWebTap:true and clicking moElement.click(). But this is not useful for me as I need to click another element using offset based on this element.

**Comment by dpgraham** [comment]
Closing. Re-open if still a problem.
