### ISSUE TITLE
Android bootstrap socket crashed when PC offline

### ISSUE THREAD

**Issue by klyndon** [appium/appium#6666]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!
## Environment
- Appium version (or git revision) that exhibits the issue:
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by klyndon** [comment]
I would like to run tests on a PC that is not connected to any network.

envt:
Ubuntu 14.04
latest appium server and  python-client, all on same PC
android handset connected over usb

can reproduce using sample python test scripts, e.g. python-client-master/test/functional/android/appium_tests.py

When I'm connected to the network (over wifi), everything runs fine.

When I disable wifi, get an appium server crash:

[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: -P, 5037, -s, e2c9ba3c, shell, uiautomator, runtest, AppiumBootstrap.jar, -c, io.appium.android.bootstrap.Bootstrap, -e, pkg, com.example.android.apis, -e, disableAndroidWatchers, false, -e, acceptSslCerts, false
[debug] [UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Loading json...
Error: Android bootstrap socket crashed: Error: getaddrinfo EAI_AGAIN undefined:4724
    at Socket.<anonymous> (lib/bootstrap.js:87:21)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1015:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

test script command in progress is:
self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

any suggestions?

**Comment by mykola-mokhnach** [comment]
This error happens in NodeJS _net.connect_ method call (https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener). Maybe, there's some implementation issue when _localhost_ is parsed as _undefined_ if there's no network connection (also, it depends on how you disable it - there are many ways of doing it in Linux). Anyway, try to replace _localhost_ with _127.0.0.1_ and see whether this helps.

**Comment by klyndon** [comment]
Thanks for the idea, but it didn't work. It appears that my Python script can talk to the local a appium server just fine, it's when trying to set up a socket with the device that it fails on port 4724.





On Mon, Jul 18, 2016 at 8:02 AM -0700, "mykola-mokhnach" <notifications@github.com> wrote:












This error happens in NodeJS net.connect method call (https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener). Maybe, there's some implementation issue when localhost is parsed as undefined if there's no network connection (also, it depends on how you disable it - there are many ways of doing it in Linux). Anyway, try to replace localhost with 127.0.0.1 and see whether this helps.

**Comment by Dharmendrapawar** [comment]
Hi klyndon,

Even i am facing the same issue, when Appium is run offline i am getting java.net.socketexception. I am using Java and Appium. If you have got the solution please help me.

**Comment by klyndon** [comment]
I never found a solution, good luck!
