### ISSUE TITLE
Access elements of iOS application using accessibility labels

### ISSUE THREAD

**Issue by darshb** [appium/appium#6667]
Hello,

I am not able to access elements of the application by its accessibility labels.

I am working on iPhone application, that uses Appium for automation testing. In iOS, we have 
accessibility labels like we have "Resource id" in android using which we can identify elements in automation. However, our automation team is not able to access elements using accessibility label. Is there any other way to do it.

* Latest Appium version with selenium
* Mac with EL Capitan OS used to run Appium:
* iOS
* Real device 
* Robot Framework

**Comment by mykola-mokhnach** [comment]
Any appium logs, code snippets, screenshots? There's not enough information to solve the problem.

**Comment by blueice349** [comment]
Try just doing elementById that worked for me

**Comment by SrinivasanTarget** [comment]
@triager please close
