### ISSUE TITLE
FullReset isn't working properly on real device iOS

### ISSUE THREAD

**Issue by AliakseiLogvinenko** [appium/appium#6668]
## The problem

I am trying to launch appium inspector. When app isn't present on device, it is still trying to install it to device and crashes with when an error, log further below. When app is present, it successfully deletes it, but fails to run it after install.
## Environment
- Appium version: 1.5.3
- Last Appium version that did not exhibit the issue: 1.4.18
- Desktop OS/version used to run Appium: OS X El Capitan 10.11.4
- Mobile platform/version under test: iOS 8.4
- Real device or emulator/simulator: real device iPhone 4s
- Appium CLI or Appium.app|exe: Appium.app
- Xcode version: 7.3
## Details

The app is running OK without full reset. For the first error it seems that ideviceinstaller throws an error that isn't gracefully handled. for the second - The app appears and can be launched manually after appium crashes. I`m not sure, but might be timeout issue.
## Link to Appium logs

https://gist.github.com/AliakseiLogvinenko/afae5b324ac6294cc889b1322ca61ec8 -logs When app isn't present on device
https://gist.github.com/AliakseiLogvinenko/0bb2844f88bfcbd3d918759b32653c3d - logs When app is present

**Comment by StingrayFE** [comment]
I had the same problem. Almost same same setup, the problem went away when i updated my ipod to ios 9.

It was not working on my ipod with ios 8.4.

**Comment by AliakseiLogvinenko** [comment]
i tried changing my device (iphone 6(9.3), iphone 6+(8.4)) and now i`m using iPod 9.3. Its still occuring from time-to time, and i have no idea how to fix that. the only work-around i tried using - is to not use full reset, and remove app before i create new exemplar of IOSDriver.

**Comment by imurchie** [comment]
Reset has been fixed in more recent versions of appium
