### ISSUE TITLE
IOS removeApp call issues target application appears to have died

### ISSUE THREAD

**Issue by go2guy** [appium/appium#6669]
## The problem

Sometimes when calling removeApp() I get an error that it appears the target application has died. Sometimes the code works fine then other times it does not.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: OSX 10
- Node.js version (unless using Appium.app|exe): 5.5.0
- Mobile platform/version under test:
- Real device or emulator/simulator:  iPhone 6 Version 9.3.2
- Appium CLI or Appium.app|exe: 

Java_client 4.0.0
## Details

I'm trying to uninstall the latest app and install the latest app everynight from a nightly build. I do this by creating a driver instance and calling removeApp() then close the driver. Then I start another driver instance. Since the app is not installed that driver instance will install the app.

What I see is that this only works about 50% of the time. It is hit and miss. The app gets uninstalled but it never makes it to the new driver to reinstall the new app as it issues an Abnormal Instruments termination.

Maybe I'm doing this wrong as well and there is a better way to uninstall and reinstall the latest app.
## Link to Appium logs

https://gist.github.com/nuggit32/78faf895149949954d50299ddddd82a1
## Code To Reproduce Issue [ Good To Have ]

```
app = new File(context.getCurrentXmlTest().getParameter("ipafile"));
        cap.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
        cap.setCapability(MobileCapabilityType.DEVICE_NAME,
            context.getCurrentXmlTest().getParameter("virtualDevice"));
        cap.setCapability(MobileCapabilityType.UDID, context.getCurrentXmlTest().getParameter("udid"));
        cap.setCapability(MobileCapabilityType.PLATFORM_NAME, context.getCurrentXmlTest().getParameter("platformName"));
        cap.setCapability(IOSMobileCapabilityType.BUNDLE_ID, context.getCurrentXmlTest().getParameter("bundleID"));

        driver = new IOSDriver<MobileElement>(AppiumService.getUrl(), cap);

       //Remove the App
        ((AppiumDriver<MobileElement>) driver).removeApp(context.getCurrentXmlTest().getParameter("bundleID"));
        ((AppiumDriver<MobileElement>) driver).quit();

        driver = null;
       //Let the new driver install the new app
        driver = new IOSDriver<MobileElement>(AppiumService.getUrl(), cap);
```

**Comment by mykola-mokhnach** [comment]
How about settings the _fullReset_ capability to true instead?

**Comment by SrinivasanTarget** [comment]
@triager please label: Bug

**Comment by nuggit32** [comment]
@mykola-mokhnach fullReset will also remove the app after the test correct?  I don't won't the app removed after the tests have ran.

**Comment by mykola-mokhnach** [comment]
I'm not sure what you want to achieve in your code by calling 
```java
        ((AppiumDriver<MobileElement>) driver).removeApp(context.getCurrentXmlTest().getParameter("bundleID"));
```

but it seemed to me, that _context.getCurrentXmlTest().getParameter("bundleID")_ is the identifier of the current application under test. Anyway, if this is a real device then you can try to workaround this method call by executing _ideviceinstaller_ tool manually to uninstall your app. See the man page to this command for more details.

**Comment by nuggit32** [comment]
@mykola-mokhnach I'm trying to do the following steps.

1.  My CI server creates a new app nightly.
2.  After that creation, remove the old app, hence calling removeApp.
3.  Install the new app from the CI server, hence 
driver = new IOSDriver<MobileElement>(AppiumService.getUrl(), cap);
4.  Run the tests.

I want to leave the app in place, so when I come in to look at any failed tests I can just open the app the tests where ran against.

I did not use fullReset as this removes the app after the tests ran.

So I want to uninstall latest app, before the tests run, install the latest app, run the tests, then leave the app in place for debugging any issues.

**Comment by mykola-mokhnach** [comment]
Got it. Then yes, you can try to uninstall the app directly from Jenkins instead using 
```
ideviceinstaller --uninstall <app_id
```
call.

**Comment by nuggit32** [comment]
I can give this a try.  I think it would be a nice feature to have to be able to uninstall and reinstall a new IOS app via Appium services and leave the app in place after tests have completed.  I will look at programmatically using ideviceinstaller in my scripts to try to accomplish my intent.
