### ISSUE TITLE
UIASegmentedControl methods

### ISSUE THREAD

**Issue by paarrivanan** [appium/appium#6670]
How to identify the selected UIAButton under the UIASegmentedControl object which has 2 or more similar buttons.?

**Comment by mykola-mokhnach** [comment]
Extract the XML UI tree and check attributes of child UIAButton nodes. There should be some difference there. In case, there is no difference, then you still have two possible ways. The first way is to assign special accessibility identifier to the selected button in the app code (more stable) or take a screenshot of a button(s) and compare it with an example (less stable, but closer to the principles of "black box" testing).

**Comment by paarrivanan** [comment]
There is no difference in attributes of the button. Can you please give me some examples of the first work around you have mentioned.? I am using selenium java for my purpose.

**Comment by mykola-mokhnach** [comment]
@paarrivanan it should be done by application developers in the source code, not by you.

**Comment by paarrivanan** [comment]
Okay. Got it. Thank you!

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach On a different note, do you have access to appium triager and appium slack?

**Comment by mykola-mokhnach** [comment]
@SrinivasanTarget No I don't. Shall I?

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach I will ask our team to add you in both.Please share your details to me. i.e your email id

**Comment by mykola-mokhnach** [comment]
@SrinivasanTarget My main email is _mokhnach_ 'at' _GMail.com_

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach cool. Will ask team to invite you.

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach Can you check your mail? Hope you got invite for appium.slack.com

**Comment by SrinivasanTarget** [comment]
@triager please close
