### ISSUE TITLE
currentactivity Function is not accurate

### ISSUE THREAD

**Issue by lizhaode** [appium/appium#6672]
## The problem

When current activity has been changed,the function returend the previous activity.Even I thake script sleep 3s.

I am so sorry that my English is poor, if you can't understand, please leave a message and I will change.
## Environment
- Appium version 1.4.16  in Windows 8.1 X64
- I use Appium.exe 
- Android 5.1
- Real device 
## Details

The app is a market like Google Play Store. 

The python script:

``` python
from appium import webdriver as wd
#ingore the same code

wbdriver = wd.Remote('http://127.0.0.1:4723/wd/hub',dc)
#The next script is click a download button,then click a button to download managment activity

downnumbutton = wbdriver.find_element_by_id('downPointsText')
 #show pause or continue or retry button

loading_text = wbdriver.find_element_by_id('loading_text') #the download progress text

while wbdriver.current_activity == '.mdcontent.usermanager.down.UserDownActivity':
    if downnumbutton.text == '暂停':
        print('正在下载，进度： ',loading_text.text,'\r',end='')
    if downnumbutton.text == '继续' or downnumbutton.text == '重试':
        print('下载出错')
        wbdriver.quit()
```

The error is 

> File "d:\haimamarket\downandinstall.py", line 37, in <module>
> print('正在下载，进度： ',loading_text.text,'\r',end='')
> File "C:\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 69, in text
> return self.execute(Command.GET_ELEMENT_TEXT)['value']
> File "C:\Python35\lib\site-packages\selenium\webdriver\remote\webelement.py", line 456, in execute
> return self.parent.execute(command, params)
> File "C:\Python35\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 236, in execute
> self.errorhandler.check_response(response)
> File "C:\Python35\lib\site-packages\appium\webdriver\errorhandler.py", line 29, in checkresponse
> raise wde
> File "C:\Python35\lib\site-packages\appium\webdriver\errorhandler.py", line 24, in checkresponse
> super(MobileErrorHandler, self).check_response(response)
> File "C:\Python35\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.

I found that  , when activity has changed , the currentactivity function returned the previous activity.
So,python script get errors

Even if I changed the script like this:

``` python
while wbdriver.current_activity == '.mdcontent.usermanager.down.UserDownActivity':
    if downnumbutton.text == '暂停':
        print('正在下载，进度： ',loading_text.text,'\r',end='')
        time.sleep(3)
    if downnumbutton.text == '继续' or downnumbutton.text == '重试':
        print('下载出错')
        wbdriver.quit()
```

Also got the same error.
## Link to Appium logs

Appium log is 

> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: D:\Android\sdk\platform-tools\adb.exe -s 3DN4C16411024563 shell "dumpsys window windows"
> info: [debug] Responding to client with success: {"status":0,"value":".mdcontent.usermanager.down.UserDownActivity","sessionId":"5827ad6c-6f80-4d81-a2ec-f46e6c6c8b7f"}
> info: <-- GET /wd/hub/session/5827ad6c-6f80-4d81-a2ec-f46e6c6c8b7f/appium/device/current_activity 200 75.297 ms - 118 {"status":0,"value":".mdcontent.usermanager.down.UserDownActivity","sessionId":"5827ad6c-6f80-4d81-a2ec-f46e6c6c8b7f"}
> info: --> GET /wd/hub/session/5827ad6c-6f80-4d81-a2ec-f46e6c6c8b7f/element/4/text {}
> info: [debug] Pushing command to appium work queue: ["element:getText",{"elementId":"4"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getText","params":{"elementId":"4"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getText
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"鏆傚仠"}
> info: [debug] Responding to client with success: {"status":0,"value":"鏆傚仠","sessionId":"5827ad6c-6f80-4d81-a2ec-f46e6c6c8b7f"}
> info: <-- GET /wd/hub/session/5827ad6c-6f80-4d81-a2ec-f46e6c6c8b7f/element/4/text 200 49.005 ms - 80 {"status":0,"value":"鏆傚仠","sessionId":"5827ad6c-6f80-4d81-a2ec-f46e6c6c8b7f"}
> info: --> GET /wd/hub/session/5827ad6c-6f80-4d81-a2ec-f46e6c6c8b7f/element/5/text {}
> info: [debug] Pushing command to appium work queue: ["element:getText",{"elementId":"5"}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"element:getText","params":{"elementId":"5"}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getText
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":7,"value":"UiSelector[INSTANCE=0, RESOURCE_ID=me.haima.androidassist:id\/loading_text]"}
> info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":"UiSelector[INSTANCE=0, RESOURCE_ID=me.haima.androidassist:id/loading_text]"},"sessionId":"5827ad6c-6f80-4d81-a2ec-f46e6c6c8b7f"}

**Comment by mykola-mokhnach** [comment]
Try not to use activity name detection. Instead, just setup a timer and wait until the text of download button is changed:
```python
TIMEOUT_SECONDS = 60
CHECK_DELAY_SECONDS = 1
time_started = time.time()
while time.time() - time_started <= TIMEOUT_SECONDS:
    try:
        if wbdriver.find_element_by_id('downPointsText').text in ('继续', '重试'):
            wbdriver.quit()
            return
    except WebDriverException:
        pass
    print('Still loading...')
    time.sleep(CHECK_DELAY_SECONDS)
raise RuntimeError('Download progress has not been completed after {} seconds'.format(TIMEOUT_SECONDS))
```

**Comment by lizhaode** [comment]
@mykola-mokhnach 
Thanks a lot.
But ,I also want to know why not to use activity name detection?

**Comment by mykola-mokhnach** [comment]
Probably, there's a bug there. Try to get the output of 
```
adb shell dumpsys window windows | grep -E 'mCurrentFocus|mFocusedApp'
```
command to make sure that the expected activity is in foreground (and it is different from what _wbdriver.current_activity_ returns) while your verification is being done.

**Comment by lizhaode** [comment]
Thanks.
I open a cmd,then open python,write this:
```python
import subprocess
while 1:
    subprocess.check_output('adb shell dumpsys window windows | findstr "mFocusedApp"'
```
It can show activity immediately.
I found that when cmd show activity has changed.
```python
wbdriver.current_activity == '.mdcontent.usermanager.down.UserDownActivity'
```
It also returnd true!

when added sleeptime,like this
```python
while wbdriver.current_activity == '.mdcontent.usermanager.down.UserDownActivity':
    if downnumbutton.text == '暂停':
        print('正在下载，进度： ',loading_text.text,'\r',end='')
        time.sleep(5)
    if downnumbutton.text == '继续' or downnumbutton.text == '重试':
        print('下载出错')
        wbdriver.quit()
```

It works wright.
But time.sleep(3),it works wrong.

Thats , I think currentactivity funcation has bug.
