### ISSUE TITLE
Permission to start activity denied

### ISSUE THREAD

**Issue by mbirthariya** [appium/appium#6673]
Getting following error while starting app....
My code
`public void call() throws MalformedURLException {
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("deviceName", "SM-T53");
		capabilities.setCapability("platformVersion", "4.4.2");
		capabilities.setCapability("platfromName", "Android");
		capabilities.setCapability("appPackage", "com.test.waitlist");
		capabilities.setCapability("appActivity", "com.clavo.restaurant.waitlist.activities.WaitlistActivity");
		dr = new AndroidDriver(new URL("http://127.0.0.1:4725/wd/hub/"), capabilities);`

Appium Error Log.

info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : platfromName
info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device
info: [debug] Creating new appium session 900273d4-517a-4dd6-b732-bbde767838f9
info: Starting android appium
info: [debug] Getting Java version

info: Java version is: 1.7.0_79

info: [debug] Checking whether adb is present

info: [debug] Using adb from /Applications/ADT/sdk/platform-tools/adb

warn: No app capability, can't parse package/activity
info: [debug] Using fast reset? false
info: [debug] Preparing device for session
info: [debug] Not checking whether app is present since we are assuming it's already on the device
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb devices

info: [debug] 1 device(s) connected

info: Found device 0e9a6ce10299061f
info: [debug] Setting device id to 0e9a6ce10299061f
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 10)
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f wait-for-device

info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "echo 'ready'"

info: [debug] Starting logcat capture

info: [debug] Getting device API level

info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "getprop ro.build.version.sdk"

info: [debug] Device is at API Level 19

info: Device API level is: 19
info: [debug] Extracting strings for language: default
info: [debug] Apk doesn't exist locally
info: [debug] Could not get strings, but it looks like we had an old strings file anyway, so ignoring
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "rm -rf /data/local/tmp/strings.json"

info: [debug] Not uninstalling app since server not started with --full-reset

info: [debug] Skipping install since we launched with a package instead of an app path
info: [debug] Forwarding system:4724 to device:4724
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f forward tcp:4724 tcp:4724

info: [debug] Pushing appium bootstrap to device...

info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f push "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/

info: [debug] Pushing settings apk to device...

info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/settings_apk/settings_apk-debug.apk"

info: [debug] Pushing unlock helper app to device...

info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"

info: Starting App

info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "ps 'uiautomator'"

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}},"sessionId":"900273d4-517a-4dd6-b732-bbde767838f9"}

info: <-- GET /wd/hub/status 200 9.777 ms - 156 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}},"sessionId":"900273d4-517a-4dd6-b732-bbde767838f9"}

info: [debug] No matching processes found
info: [debug] Running bootstrap
info: [debug] spawning: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.test.waitlist -e disableAndroidWatchers false

info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1

info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] Waking up device if it's not alive
info: [debug] Pushing command to appium work queue: ["wake",{}]

info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: wake

info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "dumpsys window"
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}

info: [debug] Screen already unlocked, continuing.

info: [debug] Pushing command to appium work queue: ["getDataDir",{}]

info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
info: [debug] dataDir set to: /data/local/tmp
info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
info: [debug] Getting device API level
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "getprop ro.build.version.sdk"
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}

info: [debug] Device is at API Level 19

info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.test.waitlist/com.clavo.restaurant.waitlist.activities.WaitlistActivity"

error: Permission to start activity denied.

info: [debug] Stopping logcat capture

error: Failed to start an Appium session, err was: Error: Permission to start activity denied.

info: [debug] Logcat terminated with code null, signal SIGTERM
info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 1.614
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] UiAutomator shut down normally
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
info: [debug] Error: Permission to start activity denied.
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:1151:19)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:180:9)
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Permission to start activity denied.)","origValue":"Permission to start activity denied."},"sessionId":null}
info: <-- POST /wd/hub/session 500 7782.015 ms - 194

**Comment by saikrishna321** [comment]
@mbirthariya you have miss spelled platfromName it should be platformName

**Comment by mbirthariya** [comment]
@saikrishna321 Thanks, I already rectified that and tried, even getting same error.

info: [debug] Didn't get app but did get Android package, will attempt to launch it on the device

info: [debug] Creating new appium session 38e655e4-70d9-4011-a88a-301e4b078457
info: Starting android appium
info: [debug] Getting Java version

info: Java version is: 1.7.0_79

info: [debug] Checking whether adb is present

info: [debug] Using adb from /Applications/ADT/sdk/platform-tools/adb
warn: No app capability, can't parse package/activity
info: [debug] Using fast reset? false
info: [debug] Preparing device for session
info: [debug] Not checking whether app is present since we are assuming it's already on the device
info: Retrieving device
info: [debug] Trying to find a connected android device
info: [debug] Getting connected devices...
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb devices

info: [debug] 1 device(s) connected

info: Found device 0e9a6ce10299061f
info: [debug] Setting device id to 0e9a6ce10299061f
info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 10)
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f wait-for-device

info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "echo 'ready'"

info: [debug] Starting logcat capture

info: [debug] Getting device API level

info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "getprop ro.build.version.sdk"

info: [debug] Device is at API Level 19

info: Device API level is: 19
info: [debug] Extracting strings for language: default
info: [debug] Apk doesn't exist locally
info: [debug] Could not get strings, but it looks like we had an old strings file anyway, so ignoring
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "rm -rf /data/local/tmp/strings.json"

info: [debug] Not uninstalling app since server not started with --full-reset

info: [debug] Skipping install since we launched with a package instead of an app path
info: [debug] Forwarding system:4724 to device:4724
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f forward tcp:4724 tcp:4724

info: [debug] Pushing appium bootstrap to device...

info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f push "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/android_bootstrap/AppiumBootstrap.jar" /data/local/tmp/

info: [debug] Pushing settings apk to device...

info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/settings_apk/settings_apk-debug.apk"

info: [debug] Pushing unlock helper app to device...

info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f install "/Applications/Appium.app/Contents/Resources/node_modules/appium/build/unlock_apk/unlock_apk-debug.apk"

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}},"sessionId":"38e655e4-70d9-4011-a88a-301e4b078457"}

info: <-- GET /wd/hub/status 200 9.133 ms - 156 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}},"sessionId":"38e655e4-70d9-4011-a88a-301e4b078457"}

info: Starting App
info: [debug] Attempting to kill all 'uiautomator' processes
info: [debug] Getting all processes with 'uiautomator'
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "ps 'uiautomator'"

info: [debug] No matching processes found

info: [debug] Running bootstrap
info: [debug] spawning: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.test.waitlist -e disableAndroidWatchers false

info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1

info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1

info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
info: [debug] [BOOTSTRAP] [debug] Loading json...
info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
info: [debug] Waking up device if it's not alive
info: [debug] Pushing command to appium work queue: ["wake",{}]
info: [debug] [BOOTSTRAP] [debug] Client connected
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: wake

info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "dumpsys window"

info: [debug] Screen already unlocked, continuing.

info: [debug] Pushing command to appium work queue: ["getDataDir",{}]

info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
info: [debug] dataDir set to: /data/local/tmp
info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
info: [debug] Getting device API level
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "getprop ro.build.version.sdk"

info: [debug] Device is at API Level 19
info: [debug] executing cmd: /Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.test.waitlist/com.clavo.restaurant.waitlist.activities.WaitlistActivity"

info: [debug] Stopping logcat capture
info: [debug] Logcat terminated with code null, signal SIGTERM

error: Permission to start activity denied.

info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
info: [debug] [BOOTSTRAP] [debug] Closed client connection
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
info: [debug] [UIAUTOMATOR STDOUT] Time: 1.475
info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
info: [debug] UiAutomator shut down normally
info: [debug] Cleaning up android objects
info: [debug] Cleaning up appium session
info: [debug] Error: Permission to start activity denied.
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:1151:19)
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-adb/lib/adb.js:180:9)
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Permission to start activity denied.)","origValue":"Permission to start activity denied."},"sessionId":null}
info: <-- POST /wd/hub/session 500 8314.585 ms - 194 

error: Failed to start an Appium session, err was: Error: Permission to start activity denied.

**Comment by saikrishna321** [comment]
from coomandline run this command and see if the app comes up 

/Applications/ADT/sdk/platform-tools/adb -s 0e9a6ce10299061f shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.test.waitlist/com.clavo.restaurant.waitlist.activities.WaitlistActivity"

**Comment by mbirthariya** [comment]
@saikrishna321 , I tried the same its not launching the app.

Stopping: com.test.waitlist
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.test.waitlist/com.clavo.restaurant.waitlist.activities.WaitlistActivity }
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.test.waitlist/com.clavo.restaurant.waitlist.activities.WaitlistActivity } from null (pid=24724, uid=2000) not exported from uid 10388
	at android.os.Parcel.readException(Parcel.java:1472)
	at android.os.Parcel.readException(Parcel.java:1426)
	at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:2367)
	at com.android.commands.am.Am.runStart(Am.java:680)
	at com.android.commands.am.Am.onRun(Am.java:270)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
	at com.android.commands.am.Am.main(Am.java:76)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:301)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by imurchie** [comment]
Your app needs to be able to be launched with the activity and package you pass in. If not, there is nothing that can be done.

**Comment by SrinivasanTarget** [comment]
@mbirthariya Reach out to your developer to make it accessible.You can raise this in discuss.appium.io.Closing this as we cannot do further on this.

**Comment by SrinivasanTarget** [comment]
@triager please close
