### ISSUE TITLE
I have a doubt in ios automation.Not able to tap Choose button.can anyone help me in Appium inspector not able to find its id/xpath.

### ISSUE THREAD

**Issue by deepakchoudhury** [appium/appium#6674]
I have a doubt in ios automation.Not able to tap Choose button.In Appium inspector not able to find its id/xpath.

Appium Version-V1.5.3

**Comment by mykola-mokhnach** [comment]
@deepakchoudhury please carefully fill out the default bug reporting form, so that we can help having enough information about the problem.

**Comment by SrinivasanTarget** [comment]
@triager please close
