### ISSUE TITLE
Appium 1.5.3 no close button for settings window

### ISSUE THREAD

**Issue by blueice349** [appium/appium#6677]
## The problem

If you open appium.app and do not move the .app at all and open any settings window it opens and there is no way to close the windows with out closing appium.app all together this has been a issue from the first version of appium I used 1.4.3... and now 1.5.3.. see the screen shot below!

## Environment

* Appium version (or git revision) that exhibits the issue:1.5.3
* Last Appium version that did not exhibit the issue (if applicable): NONE
* Desktop OS/version used to run Appium: OSK
* Node.js version (unless using Appium.app|exe): not related 
* Mobile platform/version under test: not related
* Real device or emulator/simulator: No related
* Appium CLI or Appium.app|exe: Appium.app 1.5.3

## Details

Photos: 
<img width="822" alt="screen shot 2016-07-19 at 8 28 26 am" src="https://cloud.githubusercontent.com/assets/16051640/16953736/6e7164b4-4d8b-11e6-832d-925859dc68e8.png">

**Comment by SGDSmith** [comment]
CMD + W    will close that window

**Comment by blueice349** [comment]
perfect thanks! still think a small X at the top would be helpful....
