### ISSUE TITLE
Getting error - Tap point is not within the bounds of the screen for IOS on trying to tap on x,y coordinate of an element

### ISSUE THREAD

**Issue by IntelloScooby** [appium/appium#6678]
## The problem

Tap point is not within the bounds of the screen - error message is displayed for IOS when trying to tap at an x, y coordinate of a slider element

## Environment

* Appium version that exhibits the issue: 1.5.1
* Mobile platform: IOS

## Details

I am getting error when I try to tap on an x,y coordinate on a slider object. The object is visible and the coordinates are correct but I still get the error - 

> tap point is not within the bounds of the screen

 for IOS. The same code works fine on Android for the same application.

## Code To Reproduce Issue

Below is how my code looks like:

```
float playTimeOffset = 0.5;
WebElement slider = Actions.findElementByDevice(PLAYBACK_SCRUBBER); 

Dimension sliderSize = slider.getSize();
int sliderWidth = sliderSize.getWidth();
int sliderHeight = sliderSize.getHeight();

Point sliderLocation = slider.getLocation();
int sliderX = sliderLocation.getX();
int sliderY = sliderLocation.getY();

int offsetX = (int) (sliderWidth * playTimeOffset);
int tapX = sliderX + offsetX;
int tapY = sliderY + (int) (sliderHeight * 0.50);

touchAction.tap(slider, tapX, tapY).perform();
```

## Appium Log and error trace: 
[https://gist.github.com/IntelloScooby/decf3d3127af0b43f1cd860ab3d517f1]

**Comment by mykola-mokhnach** [comment]
```java
touchAction.tap(slider, tapX, tapY).perform();
```

the problem must be here. You calculate absolute element coordinates on the screen (_sliderX_ and _sliderY_) and then try to tap the element using these coordinates, which causes the mentioned problem, since it expects relative coordinates in such case. It is necessary to either do generic screen tap having this (tapX, tapY) point or replace method call with
```java
touchAction.tap(slider, (int) (sliderWidth * playTimeOffset), (int) (sliderHeight * 0.50)).perform();
```

**Comment by SrinivasanTarget** [comment]
@triager please close
