### ISSUE TITLE
Appium does not detect the pre-existing app on iOS device

### ISSUE THREAD

**Issue by wildwolfeng** [appium/appium#6679]
## The problem

When I attempt to run appium with iOS bundle id, it says app was not installed

## Environment

* Appium version (or git revision) that exhibits the issue:
Appium 1.5.3
* Desktop OS/version used to run Appium:
MAC OSX 10.11.6
* Node.js version (unless using Appium.app|exe):
5.12.0
* Mobile platform/version under test:
iPhone 6 with iOS 10
* Real device or emulator/simulator:
Real device
* Appium CLI or Appium.app|exe:
CLI

## Details

**My script :**

```
class SimpleIOSTests(unittest.TestCase):
    def setUp(self):
        # set up appium
        self.driver = webdriver.Remote(
            command_executor='http://localhost:4723/wd/hub',
            desired_capabilities={
                'app': 'com.XXXX.XXX',
                'udid':'MY UDID',
                'platformVersion': '10.0',
                'platformName': 'iOS',
                'deviceName': 'xPhone'
            })
......

```
**Appium logs:**

[debug] [iOS] App is an iOS bundle, will attempt to run as pre-existing
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /var/folders/58/9bpqjjfj2kq6thd7_knk0t5c0000gq/T/instruments_sock
[debug] [iOS] No language specified. Using default strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/fyu/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/usr/local/Cellar/node5/5.12.0/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/58/9bpqjjfj2kq6thd7_knk0t5c0000gq/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...bug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
[debug] [UIAuto] Dynamic bootstrap path: /Users/fyu/Library/Application Support/appium/bootstrap/bootstrap-c22bb713e711df3f.js
[debug] [UIAuto] Reusing dynamic bootstrap: /Users/fyu/Library/Application Support/appium/bootstrap/bootstrap-c22bb713e711df3f.js
[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [iOS] Creating iDevice object with did MY UDID
[debug] [iOS] App is not installed. Will try to install.
[MJSONWP] Encountered internal error running command: Error: Installing com.XXXX.XXXX failed
    at /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:484:12)

**Then I modify the main.js:**

```
IDevice.prototype.install = function (app, cb) {
    exec(this._build_cmd(['-i', wrapForExec(app)]), function (err, stdout, stderr) {
	if (err) {
	    cb(err, stdout);
	} else {
	    if (stdout.indexOf('Complete') != -1) {
		cb(null);
	    } else {
**Here use cb(null) to instead of threw new error**
  		//cb(new Error('Installing ' + app + ' failed'));
		cb(null);
	    }
	}
    });
};
```

**Then I relaunch appium server and run my script, it works fine.** 

BTW, when I run ideviceinstaller -l  manually, it prompts "Could not connect to lockdownd. Exiting.", but I don't know why this happened. Maybe it's the root cause.

**Comment by mykola-mokhnach** [comment]
Have you tried another iOS device? Google says that sometimes resettings All Content and Settings on the target device does help to resolve the problem (Settings > General > Reset > Reset All Content and Settings).

**Comment by wildwolfeng** [comment]
@mykola-mokhnach Yes, I have tried on another iPhone 6 with iOS 9.1, and I also erase all settings and content of my device, it does not help.

**Comment by mykola-mokhnach** [comment]
hm... I would also try to remove idevicelibrary completely with all its files and install the most recent version available.

**Comment by michaelgallacher** [comment]
This issue began for me when I updated to El Capitan 10.11.6 yesterday.  Running ideviceinstaller as sudo works, so I'd bet it is due to a security fix in a dependency of ideviceinstaller.

**Comment by imurchie** [comment]
Specify the bundle id as `bundleId` not as `app` in your desired caps.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by VasilijSviridov** [comment]
Same issue here, even with phone reset and with bundleId instruments crashing on startup

**Comment by VasilijSviridov** [comment]
it seems that problem with ideviceinstaller which from 11.6 El Capitan requires sudo command

**Comment by mayureshshirodkar** [comment]
Facing similar issue as @VasilijSviridov  and @michaelgallacher on updating to ElCapitan 10.11.6

**Comment by mayureshshirodkar** [comment]
Meanwhile,  After a lot of googling and research, came across this post. Helped me fix the issue. May be a temporary fix, but it works.

http://stackoverflow.com/questions/39035415/ideviceinstaller-fails-with-could-not-connect-to-lockdownd-exiting

Use:
sudo chmod -R 777 /var/db/lockdown/

**Comment by huig1149** [comment]
I solve the similar problew by reinstalling ideviceinstaller and libimobiledevice. You need the latest libimobiledevice, in the Appium 1.5.3 version.
Open the Terminal, type the commands below:

1. brew uninstall ideviceinstaller
2. brew uninstall libimobiledevice
3. brew install --HEAD libimobiledevice
4. brew link --overwrite libimobiledevice
5. brew install ideviceinstaller
6. brew link --overwrite ideviceinstaller

It may work for you.

Refer to Michael Gallacher：
[(http://stackoverflow.com/questions/38609898/ideviceinstaller-l-wont-show-the-app-list-on-the-iphone)]

**Comment by stellasu168** [comment]
Hi, I'm having the same issue with Appium 1.5.3. I did the above commands, still can't launch inspector (with different error message though). I upgraded my iPhone to iOS 10.0, but I'm still using 9.3.4 in the capabilities. Could that be the problem?

**Comment by VasilijSviridov** [comment]
To run automation on iOS10 you need to use appium 1.6 with xcuit driver :) appium 1.5.3 won't work on iOS10.
