### ISSUE TITLE
Error launching instruments: Instruments crashed on startup

### ISSUE THREAD

**Issue by nikhilnadagouda** [appium/appium#6684]
## The problem
I am trying to run appium for iOS simulator automation testing through command line. Appium launches the iOS simulator and simulator crashes before completing boot up.

[debug] [Instruments] [INST STDERR] Instruments Trace Error : Target failed to run: Unable to install app with path: com.xyz.ios.liteclient: "(null)"
[debug] [Instruments] Instruments exited with code 253
[Instruments] Error launching instruments: Instruments crashed on startup

## Environment
* Appium version : 1.5.3 
* Desktop OS/version used to run Appium: OS X 10.11.5
* Node.js version : 6.2.2 
* Mobile platform/version under test: Xcode 7.3.1
* Real device or emulator/simulator: iOS simulator  iPhone 6

## Logs

Welcome to Appium v1.5.3 (REV ed9bb449d1bfc837d46b2572e9ffc2a70b32f9de)
[Appium] Non-default server args:
[Appium]   port: 7010
[Appium]   sessionOverride: true
[Appium]   app: '/Users/abc/Library/Developer/Xcode/DerivedData/xyz/Build/Products/Debug-iphonesimulator/AppLiteClient.app'
[Appium] Deprecated server args:
[Appium]   --app => --default-capabilities '{"app":"/Users/abc/Library/Developer/Xcode/DerivedData/xyz/Build/Products/Debug-iphonesimulator/AppLiteClient.app"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   app: '/Users/abc/Library/Developer/Xcode/DerivedData/xyz/Build/Products/Debug-iphonesimulator/AppLiteClient.app'
[Appium] Appium REST http interface listener started on 0.0.0.0:7010
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"com.xyz.ios","appPackage":"com.xyz.ios","appActivity":"none","newCommandTimeout":"130","platformVersion":"9.3","platformName":"iOS","deviceName":"iPhone 6"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"com.xyz.ios
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   app: 'com.xyz.ios'
[Appium]   appPackage: 'com.xyz.ios'
[Appium]   appActivity: 'none'
[Appium]   newCommandTimeout: '130'
[Appium]   platformVersion: '9.3'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6'
[debug] [iOSSim] Getting device string from options: {"deviceName":"iPhone 6","platformVersion":"9.3","forceIphone":false,"forceIpad":false}
[debug] [iOSSim] Fixing device. Changed from 'iPhone 6' to 'iPhone 6 (9.3) ['
[debug] [iOSSim] Final device string is 'iPhone 6 (9.3) ['
[debug] [iOS] iOS sim UDID is 32CB5
[debug] [UIAuto] Dynamic bootstrap dir: /Users/abc/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/usr/local/Cellar/node/6.2.2/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually mod...!
[debug] [UIAuto] Dynamic bootstrap path: /Users/abc/Library/Application Support/appium/bootstrap/bootstrap-38d28181787d2ebc.js
[debug] [UIAuto] Reusing dynamic bootstrap: /Users/abc/Library/Application Support/appium/bootstrap/bootstrap-38d28181787d2ebc.js
[debug] [iOS] User specified default device, letting instruments launch it
=
[debug] [Instruments] Attempting to run app on iPhone 6 (9.3) [
[Instruments] On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/appium-instruments/instrumentscli0.trace -w "iPhone 6 (9.3) [" com.xyz.ios.liteclient -e UIASCRIPT "/Users/abc/Library/Application Support/appium/bootstrap/bootstrap-38d28181787d2ebc.js" -e UIARESULTSPATH /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/appium-instruments'
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}
[debug] [Instruments] [INST] Waiting for device to boot...
[debug] [Instruments] [INST STDERR] Instruments Trace Error : Target failed to run: Unable to install app with path: com.xyz.ios.liteclient: "(null)"
[debug] [Instruments] Instruments exited with code 253
[Instruments] Error launching instruments: Instruments crashed on startup
[debug] [iOSSim] Killing all iOS Simulators
[debug] [Instruments] Attempting to launch instruments, this is try #2

**Comment by nikhilnadagouda** [comment]
@imurchie  Can you help me on this one?

**Comment by imurchie** [comment]
Why are you sending `"app":"com.xyz.ios"` in your desired capabilities? You seem to be setting an actual app on the command line when starting the app.

```
[Appium] Non-default server args:
[Appium]   port: 7010
[Appium]   sessionOverride: true
[Appium]   app: '/Users/abc/Library/Developer/Xcode/DerivedData/xyz/Build/Products/Debug-iphonesimulator/AppLiteClient.app'
```

**Comment by nikhilnadagouda** [comment]
@imurchie  Yes I was using --app option and sending the abs path of com.xyz.ios.app. Even without it i faced same error

**Comment by imurchie** [comment]
Can you post the logs for when you do _not_ specify `app` as the bundle id for the app?

**Comment by nikhilnadagouda** [comment]
command : appium -dd --no-reset -p 7010 --session-override




[Appium] Welcome to Appium v1.5.3 (REV ed9bb449d1bfc837d46b2572e9ffc2a70b32f9de)
[Appium] Non-default server args:
[Appium]   port: 7010
[Appium]   sessionOverride: true
[Appium]   defaultDevice: true
[Appium]   noReset: true
[Appium] Deprecated server args:
[Appium]   --no-reset => --default-capabilities '{"noReset":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   noReset: true
[Appium] Appium REST http interface listener started on 0.0.0.0:7010
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"com.xyz.ios.liteclient","appPackage":"com.xyz.ios.liteclient","appActivity":"none","newCommandTimeout":"130","platformVersion":"9.3","platformName":"iOS","deviceName":"iPhone 6"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"com.xyz.ios.l...
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   app: 'com.xyz.ios.liteclient'
[Appium]   appPackage: 'com.xyz.ios.liteclient'
[Appium]   appActivity: 'none'
[Appium]   newCommandTimeout: '130'
[Appium]   platformVersion: '9.3'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6'
[Appium]   noReset: true
[BaseDriver] Capability 'newCommandTimeout' changed from string ('130') to integer (130). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appPackage, appActivity.
[BaseDriver] Session created with session id: c7568199-f831-47a8-b86a-84648d08be28
[debug] [iOS] Not auto-detecting udid.
[debug] [iOS] App is an iOS bundle, will attempt to run as pre-existing
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/instruments_sock
[debug] [iOS] Setting Xcode version
[debug] [iOS] Xcode version set to 7.3.1
[debug] [iOS] Setting iOS SDK Version
[debug] [iOS] iOS SDK Version set to 9.3
[debug] [iOS] Checking whether instruments supports our device string
[debug] [Instruments] Getting list of devices instruments supports
[debug] [Instruments] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
[debug] [Instruments] Available devices: Apple TV 1080p (9.2) [88AE4758-90BB-45FE-90D5-1D274EC3692B] (Simulator),iPad 2 (9.3) [047E4B17-3046-41C1-B1DA-B45B9949C35E] (Simulator),iPad Air (9.3) [0DE4B03E-B192-495D-9DAB-C03A3CB7882B] (Simulator),iPad Air 2 (9.3) [BCD26AB0-7164-4784-A3D0-42F50F250D81] (Simulator),iPad Pro (9.3) [47557DE4-D056-4DBF-B331-B35034D6FE49] (Simulator),iPad Retina (9.3) [03BC89D3-8DAC-44B4-BB20-F2E7C35103CC] (Simulator),iPhone 4s (9.3) [D8B51781-9CCC-479A-ABC7-05D0451C5D5C] (Simulator),iPhone 5 (9.3) [9BE532C0-5EDA-4914-9628-9541E265DFA6] (Simulator),iPhone 5s (9.3) [68766F52-192B-403E-81CA-D709DEB756CF] (Simulator),iPhone 6 (9.3) [32CB5DF0-4BA8-4C0A-B10D-D7C71EA1213A] (Simulator),iPhone 6 Plus (9.3) [84A7DB65-9892-446C-8BB6-B8CA00640671] (Simulator),iPhone 6s (9.3) [4EE0C4CE-1CDB-4122-A1A2-33155F6234AC] (Simulator),iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [51AA8357-92E5-4384-BB0E-83E2F26657F8] (Simulator),iPhone 6s Plus (9.3) [E774793C-C7CF-4AC8-9CD7-D2DBF6AA027B] (Simulator),iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [9C522182-0320-4530-B460-C7578FC1F374] (Simulator)
[iOSSim] Retrieving device name string for Xcode version 7.3.1
[debug] [iOSSim] Getting device string from options: {"deviceName":"iPhone 6","platformVersion":"9.3","forceIphone":false,"forceIpad":false}
[debug] [iOSSim] Fixing device. Changed from 'iPhone 6' to 'iPhone 6 (9.3) ['
[debug] [iOSSim] Final device string is 'iPhone 6 (9.3) ['
[debug] [iOS] iOS sim UDID is 32CB5DF0-4BA8-4C0A-B10D-D7C71EA1213A
[iOSSim] Constructing iOS simulator for Xcode version 7.3.1
[debug] [iOS] No language specified. Using default strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/abc/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/usr/local/Cellar/node/6.2.2/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"oneByOne"}
[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually mod...!
[debug] [UIAuto] Dynamic bootstrap path: /Users/abc/Library/Application Support/appium/bootstrap/bootstrap-38d28181787d2ebc.js
[debug] [UIAuto] Reusing dynamic bootstrap: /Users/abc/Library/Application Support/appium/bootstrap/bootstrap-38d28181787d2ebc.js
[debug] [iOS] User specified default device, letting instruments launch it
[debug] [iOS] Reset not set, not ending sim
[debug] [iOS] Not setting locale
[debug] [iOS] No iOS / app preferences to set
[debug] [iOSLog] Starting iOS 9.3 simulator log capture
[debug] [iOSLog] System log path: /Users/abc/Library/Logs/CoreSimulator/32CB5DF0-4BA8-4C0A-B10D-D7C71EA1213A/system.log
[debug] [iOS] Not pre-launching simulator
[debug] [iOS] Starting UIAutoClient, and launching Instruments.
[debug] [UIAuto] Instruments socket server started at /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/instruments_sock
[debug] [Instruments] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
[debug] [Instruments] Attempting to launch instruments, this is try #1
[Instruments] Launching instruments
[debug] [Instruments] Attempting to run app on iPhone 6 (9.3) [
[Instruments] On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/appium-instruments/instrumentscli0.trace -w "iPhone 6 (9.3) [" com.xyz.ios.liteclient -e UIASCRIPT "/Users/abc/Library/Application Support/appium/bootstrap/bootstrap-38d28181787d2ebc.js" -e UIARESULTSPATH /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/appium-instruments'
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}
[debug] [Instruments] [INST STDERR] Instruments Trace Error : Target failed to run: Unable to install app with path: com.xyz.ios.liteclient: "(null)"
[debug] [Instruments] Instruments exited with code 253
[Instruments] Error launching instruments: Instruments crashed on startup
[debug] [iOSSim] Killing all iOS Simulators
[debug] [Instruments] Attempting to launch instruments, this is try #2
[Instruments] Launching instruments
[debug] [Instruments] Attempting to run app on iPhone 6 (9.3) [
[Instruments] On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/appium-instruments/instrumentscli0.trace -w "iPhone 6 (9.3) [" com.xyz.ios.liteclient -e UIASCRIPT "/Users/abc/Library/Application Support/appium/bootstrap/bootstrap-38d28181787d2ebc.js" -e UIARESULTSPATH /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/appium-instruments'
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}
[debug] [Instruments] [INST] Waiting for device to boot...
[debug] [Instruments] [INST STDERR] Instruments Trace Error : Target failed to run: Unable to install app with path: com.xyz.ios.liteclient: "(null)"
[debug] [Instruments] Instruments exited with code 253
[Instruments] Error launching instruments: Instruments crashed on startup
[debug] [iOSSim] Killing all iOS Simulators
[debug] [Instruments] Attempting to launch instruments, this is try #3
[Instruments] Launching instruments
[debug] [Instruments] Attempting to run app on iPhone 6 (9.3) [
[Instruments] On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/appium-instruments/instrumentscli0.trace -w "iPhone 6 (9.3) [" com.xyz.ios.liteclient -e UIASCRIPT "/Users/abc/Library/Application Support/appium/bootstrap/bootstrap-38d28181787d2ebc.js" -e UIARESULTSPATH /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/appium-instruments'
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}
[debug] [Instruments] [INST] Waiting for device to boot...
[debug] [Instruments] [INST STDERR] Instruments Trace Error : Target failed to run: Unable to install app with path: com.xyz.ios.liteclient: "(null)"
[debug] [Instruments] Instruments exited with code 253
[Instruments] Error launching instruments: Instruments crashed on startup
[debug] [iOSSim] Killing all iOS Simulators
[debug] [Instruments] Attempting to launch instruments, this is try #4
[Instruments] Launching instruments
[debug] [Instruments] Attempting to run app on iPhone 6 (9.3) [
[Instruments] On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/appium-instruments/instrumentscli0.trace -w "iPhone 6 (9.3) [" com.xyz.ios.liteclient -e UIASCRIPT "/Users/abc/Library/Application Support/appium/bootstrap/bootstrap-38d28181787d2ebc.js" -e UIARESULTSPATH /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/appium-instruments'
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}
[debug] [Instruments] [INST] Waiting for device to boot...
[debug] [Instruments] [INST STDERR] Instruments Trace Error : Target failed to run: Unable to install app with path: com.xyz.ios.liteclient: "(null)"
[debug] [Instruments] Instruments exited with code 253
[Instruments] Error launching instruments: Instruments crashed on startup
[debug] [iOSSim] Killing all iOS Simulators
[debug] [Instruments] Attempting to launch instruments, this is try #5
[Instruments] Launching instruments
[debug] [Instruments] Attempting to run app on iPhone 6 (9.3) [
[Instruments] On xcode 7.0+, instruments-without-delay does not work, skipping instruments-without-delay
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-instruments/thirdparty/iwd7
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/appium-instruments/instrumentscli0.trace -w "iPhone 6 (9.3) [" com.xyz.ios.liteclient -e UIASCRIPT "/Users/abc/Library/Application Support/appium/bootstrap/bootstrap-38d28181787d2ebc.js" -e UIARESULTSPATH /var/folders/_s/bsq_3xld1m10x4ll1hh98rl80000gn/T/appium-instruments'
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}
[debug] [Instruments] [INST] Waiting for device to boot...
[debug] [Instruments] [INST STDERR] Instruments Trace Error : Target failed to run: Unable to install app with path: com.xyz.ios.liteclient: "(null)"
[debug] [Instruments] Instruments exited with code 253
[Instruments] Error launching instruments: Instruments crashed on startup
[Instruments] Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Instruments.launch$ (lib/instruments.js:220:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Instruments.launch$ (lib/instruments.js:220:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at Instruments.launch$ (lib/instruments.js:220:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by nikhilnadagouda** [comment]
This log is what I just produced without --app option. 

command used : appium -dd --no-reset -p 7010 --session-override

**Comment by nikhilnadagouda** [comment]
in test scripts I have <parameter name="first_app_package" value="com.xyz.ios.liteclient"/> which specifies app package.

**Comment by imurchie** [comment]
That is not what you want. You want what you were putting in the `--app` server flag, either as _just_ that flag, or the same value in the `app` desired capability. You _do not_ want `com.xyz.ios.liteclient` as your `app` desired cap.

**Comment by imurchie** [comment]
`appPackage` does not have any affect on iOS. It is an Android-only capability.

**Comment by nikhilnadagouda** [comment]
Initially I had specified appium -dd --no-reset --app /Users/abc/Library/Developer/Xcode/DerivedData/xyz/Build/Products/Debug-iphonesimulator/AppLiteClient.app -p 7010 --session-override as the command.

I didn't specify bundle id as --app. I think It is taking from test script which has something like 
"parameter name="first_app_package" value="com.xyz.ios.liteclient""

**Comment by imurchie** [comment]
Your initial logs have the following request to start a session:

```
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"com.xyz.ios","appPackage":"com.xyz.ios","appActivity":"none","newCommandTimeout":"130","platformVersion":"9.3","platformName":"iOS","deviceName":"iPhone 6"}}
```

You either need to get rid of the `app` here, as it is invalid, or use the same value as you set with the `---app` flag.

**Comment by nikhilnadagouda** [comment]
I made the changes. Replacing the bundle ID to the actual .app path helped it. I thought the command line option --app would be overriding  the default values. 

@imurchie  thank you

**Comment by imurchie** [comment]
The command line options _is_ the default. The one specified in the session start request overrides it.
