### ISSUE TITLE
safari on simulator keep refreshing

### ISSUE THREAD

**Issue by freezer-glp** [appium/appium#6685]
## The problem

I use Selenium Grid 2.53.1 and Appium(1.5.3) to build automation testing on iPhone simulator and its safari. But the safari on iPhone simulator struck at the initialUrl and keep refreshing
## Environment
- Appium version : 1.5.3( using Appium.app)
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS: OS X EI 10.11.5  xCode: 7.1
- Node.js version (unless using Appium.app|exe):
- Mobile platform: iPhone simulator iOS 9.1
- Real device or emulator/simulator:
- Appium.app
## Details

I start selenium grid hub on my Win10 PC(10.172.112.73) by:  
`java -jar selenium-server-standalone-2.53.1.jar -role hub -hubConfig hub-json-cfg.json`

the `hub-json-cfg.json` writes:

```
{
  "host": "localhost",
  "port": 4444,
  "newSessionWaitTimeout": -1,
  "servlets" : [],
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 5000,

  "cleanUpCycle": 5000,
  "timeout": 300000,
  "browserTimeout": 0,
  "maxSession": 5,
  "jettyMaxThreads":-1
}
```

And I start appium using [appium.app][1] on my macbook(10.172.113.147)

and the ios-node-cfg.json writes:

```
{

    "capabilities": [

         {                     
         "browserName": "Safari",                     
         "maxInstances": 1,                     
         "platform": "MAC",
         "deviceName": "iPhone Simulator"                     
         }

    ],

    "configuration": {
        "timeout":30000,
        "hub": "http://10.172.112.73:4444/grid/register",
        "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
        "maxSession": 1,
        "hubPort": 4444,
        "hubHost": "10.172.112.73",
        "remoteHost": "http://10.172.113.147:4723",
        "register": true,        
        "registerCycle": 5000,        
        "role": "node"        
    }

}
```

Then I run test a very Simple case( c# ):  

```
 DesiredCapabilities cap = DesiredCapabilities.IPhone();
 cap.SetCapability("deviceName", "iPhone Simulator");
 cap.SetCapability("simulator",true);
 cap.SetCapability("browserName", "Safari");
 cap.SetCapability("platformVersion", "8.2");
 cap.SetCapability("safariInitialUrl", "www.github.com");
 IWebDriver driver = new RemoteWebDriver(new Uri("http://10.172.113.147:4723/wd/hub/"), cap);
 driver.Navigate().GoToUrl("https://www.google.com.hk/");
```

It can launch the iPhone and open safari, and then go to the initialUrl. 

But Then the process will stuck. The safari will keep refreshing again and again. And I find a log writes:

> [debug] [RemoteDebugger] Received app, but expected url
> ('forms.office.com') was not found. **Trying again**.

which seems lead to the problem.
## Link to Appium logs

> [debug] [RemoteDebugger] Received response from socket send: '["PID:44428",{"1":{"WIRTitl...'
> [debug] [RemoteDebugger] Page changed: {"1":{"WIRTitleKey":"","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"about:blank","WIRPageIdentifierKey":1}}
> [debug] [RemoteDebugger] Received app, but expected url ('forms.office.com') was not found. Trying again.
> [debug] [RemoteDebugger] Found app id key 'PID:44420' for bundle 'com.apple.mobilesafari'
> [debug] [RemoteDebugger] Found separate bundleId 'com.apple.WebKit.WebContent' acting as proxy for 'com.apple.mobilesafari', with app id 'PID:44428'
> [debug] [RemoteDebugger] Trying out the possible app ids: PID:44428
> [debug] [RemoteDebugger] Selecting app PID:44428 (try #15 of 20)
> [debug] [RemoteDebugger] Sending '_rpc_forwardGetListing:' message to remote debugger
> [debug] [RemoteDebugger] Receiving data from remote debugger: '{"__argument":{"WIRApplicationIdentifierKey":"PID:44428","WIRListingKey":{"1":{"WIRTitleKey":"","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"about:blank","WIRPageIdentifierKey":1}}},"__selector":"_rpc_applicationSentListing:"}'

 [Appium logs](https://gist.github.com/freezer-glp/35949a4007ebf67269423836b5ccf7b3)

**Comment by mykola-mokhnach** [comment]
Try to add https:// prefix to the _safariInitialUrl_ parameter.

**Comment by freezer-glp** [comment]
@mykola-mokhnach 
Hi, I tried what you suggested. This time(also iOS 8.2 on iPhone Simulator) the error log is:  
> [simctl] Error: simctl error running 'openurl': An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
> The operation couldn’t be completed. Invalid argument
> Invalid argument
>     at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
>     at simCommand$ (lib/simctl.js:22:11)
>     at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
>     at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
>     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
>     at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)


And I tried on iOS 9.1, The same problem shows again:

> [debug] [RemoteDebugger] Received response from socket send: '["PID:9445",{"1":{"WIRTitle...'
> [debug] [RemoteDebugger] Received page change notice for app PID:9445 but listening for PID:9461. Ignoring.
> [debug] [RemoteDebugger] Received app, but expected url **('https://www.github.com')** was not found. Trying again.
> [debug] [RemoteDebugger] Selecting app PID:9461 (try #12 of 20)
> [debug] [RemoteDebugger] Sending '_rpc_forwardGetListing:' message to remote debugger
> [debug] [RemoteDebugger] Receiving data from remote debugger: '{"__argument":{"WIRApplicationIdentifierKey":"PID:9461","WIRListingKey":{"1":{"WIRTitleKey":"","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"about:blank","WIRPageIdentifierKey":1}}},"__selector":"_rpc_appl
> [RemoteDebugger] Error: Could not connect to a valid app after 20 tries.
>     at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
>     at RemoteDebugger.selectApp$ (lib/remote-debugger.js:216:11)
>     at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
>     at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
>     at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
>     at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>  [Error: Could not connect to a valid app after 20 tries.]

**Comment by mykola-mokhnach** [comment]
This looks more like a bug in Appium. Probably, @imurchie can confirm it.

**Comment by garyeaston** [comment]
Did you find a work around for this? I am having the same issue and allowing the simulator to boot to the default page and then navigating to my chosen url after is very time consuming.

**Comment by rburgos240** [comment]
I'm experiencing this same issue using appium. Does anyone have a solution for fixing this problem? a different version of appium?

**Comment by freezer-glp** [comment]
@garyeaston @rburgos240 I still **not** find a solution about this issue. Please kindly connect me if any solution found.

**Comment by mykola-mokhnach** [comment]
Is this problem still relevant in the recent Appium releases (1.6.5)

**Comment by mykola-mokhnach** [comment]
Closed as inactive
