### ISSUE TITLE
context 'WEBVIEW' not found in Selenium error

### ISSUE THREAD

**Issue by firekyrin** [appium/appium#6686]
## The problem

I run appium's example code,like this:
$ npm run ios-webview
and give me the follow fails:

```
1) ios webview should get the url:
     Error: [context("WEBVIEW")] Error response status: 35 Selenium error: No such context found.
at exports.newError (node_modules/wd/lib/utils.js:139:13)
      at node_modules/wd/lib/callbacks.js:33:23
      at node_modules/wd/lib/webdriver.js:174:5
      at Request._callback (node_modules/wd/lib/http-utils.js:87:7)
      at Request.self.callback (node_modules/request/request.js:368:22)
      at Request.<anonymous> (node_modules/request/request.js:1219:14)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1167:12)
      at endReadableNT (_stream_readable.js:926:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

this is my code that i fixed in ios-webview.js:

```
it("should get the url", function () {
    return driver
      .elementByXPath('//UIATextField[@value=\'Enter URL\']')
        .sendKeys('www.google.com')
    //   .elementByName('Go').click()
      .elementByXPath('//UIAButton').click()
      .elementByClassName('UIAWebView').click() // dismissing keyboard
      .context('WEBVIEW')
      .sleep(1000)
      .waitForElementByName('q', 5000)
        .sendKeys('sauce labs')
        .sendKeys(wd.SPECIAL_KEYS.Return)
      .sleep(1000)
      .title().should.eventually.include('sauce labs');
  });
```
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Darwin kaideMacBook-Pro.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
- Node.js version (unless using Appium.app|exe): v6.2.0
- Mobile platform/version under test: iPhone 6
- Real device or emulator/simulator: Simulator
- Appium CLI or Appium.app|exe:  Appium.app

**Comment by jrgoulet** [comment]
Having a similar issue in Android. Here's another discussion about it:

https://github.com/appium/appium/issues/5089

**Comment by rknell** [comment]
Hey,

I've read through the link provided which is Android specific and also followed to the subsequent iOS branch in which the solution is simply to upgrade to v 1.4 (I'm on 1.5.3 right now)

As @firekyrin mentioned, I also needed to fix the sample code just to run the demo because .elementByName is depreciated... this is the official sample code from this repo:

https://github.com/appium/sample-code/blob/master/sample-code/examples/node/ios-webview.js

It would be great if someone else could test the official code against 1.5.3 and see if they can get it working, i'm happy to put in a pull request once this is solved so at least the official docs are working.

PS. I used 

```
.elementByXPath('//*[@name="Go"]').click()
```
instead of 
```
.elementByXPath('//UIAButton').click()
```

To fix step 1 of the sample code. Not sure what the preferred method would be.

**Comment by rknell** [comment]
Righto this works:

```
it("should get the url", function () {
    return driver
      .elementByXPath('//UIATextField[@value=\'Enter URL\']')
        .sendKeys('www.google.com')
      .elementByXPath('//*[@name="Go"]').click()
      .elementByClassName('UIAWebView').click() // dismissing keyboard
      .contexts()
      .then(function (contexts) {
        var webViewContext = _.find(contexts, function (context) {
          return context.indexOf('WEBVIEW') !== -1;
        });
        return driver.context(webViewContext);
      })
      .sleep(1000)
      .waitForElementByXPath('//*[@name="q"]', 5000)
        .sendKeys('sauce labs')
        .sendKeys(wd.SPECIAL_KEYS.Return)
      .sleep(1000)
      .title().should.eventually.include('sauce labs');
  });
```

I got some inspiration from this article:
http://ezosaleh.com/verifying-a-cordovaphonegap-build-with-smoke-tests-appium

Which helped solved the context issues. Also needed to fix a second reference of get by name to xpath.

**Comment by firekyrin** [comment]
tks @rknell ! it is perfect! running this works successfully!
