### ISSUE TITLE
installApp expects app path to be local to appium server and not the client

### ISSUE THREAD

**Issue by emipra** [appium/appium#6688]
When executing installApp command Appium expects app path to exist on the same host as the server process. This make it impossible for a remote client to use installApp with apk local to it.
Would you be open to installApp acting in similar fashion to pushFile that takes base64 encoded data object?

Using pushFile as a workaround does not seem to be possible as installApp will not deal with files on remote devices as well.

Code in question: https://github.com/appium/appium-android-driver/blob/master/lib/commands/general.js#L95

**Comment by emipra** [comment]
Other options:
1. Introduce installLocalApp call that would take path relative to device, so we could do pushFile first and then installLocalApp. It's nice because we have to push apk onto device anyway in order to do install using "adb shell pm install /path/on/device" 

2. Make installApk accepts URLs same as app capability when starting a new appium session

**Comment by imurchie** [comment]
This is available on the newest version of appium.
