### ISSUE TITLE
Appium Inspector don't see debug-banner info

### ISSUE THREAD

**Issue by mokena1990** [appium/appium#6689]
## The problem

In testing enviroment of app developers make banner with code, which need for registration.
So when it displayed, I click on "Refresh" button in Appium Inspector. It's displayed in Inspector, but when I click on it, it's shows as UIAImage or UIAElement and text with displayed code doesdn't contains in any of element in Element Tree.

![app-banner-problem](https://cloud.githubusercontent.com/assets/17159265/17056766/ac9d3a5e-5026-11e6-920f-52968a9b5e6c.jpg)

![app-banner-problem-2](https://cloud.githubusercontent.com/assets/17159265/17057030/93265428-5028-11e6-9932-66408fc445c6.jpg)

Application developed in outsource company and I don't have access to source code.
## Environment
- Appium version (or git revision) that exhibits the issue: Version 1.5.3 (Ara)
- Last Appium version that did not exhibit the issue (if applicable): -
- Desktop OS/version used to run Appium: OS X El Capitan 10.11.5
- Node.js version (unless using Appium.app|exe): -
- Mobile platform/version under test: iOS 9.3.3
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: Appium.app

**Comment by mykola-mokhnach** [comment]
Try it with my inspector implementation. Probably, it's gonna work better.

https://github.com/mykola-mokhnach/Appium-iOS-Inspector

**Comment by mokena1990** [comment]
@mykola-mokhnach Nope, this solution not working.
In my case It's shows every element like in Appium Inspector.

**Comment by mykola-mokhnach** [comment]
As a workaround, you may try to tap the edit field by absolute screen coordinates and then input the code just by clicking the corresponding buttons on the on-screen keyboard + Send key after input is finished ("blind simulation"). This is not the most stable and elegant solution, but it may serve its purpose in this situation, where access to the source code is limited.

**Comment by mokena1990** [comment]
I think need add some info - in code, where i use method getSource(). Result don't contains needed text. So, maybe it's problem of Appium, not Appium Inspector.

**Comment by SrinivasanTarget** [comment]
Please try appium desktop incase if you still face this issue
