### ISSUE TITLE
Could not find Element - Android

### ISSUE THREAD

**Issue by elyanivson31** [appium/appium#6691]
## The problem

I'm trying to send some data to a EditText Element by Xpath.
`[FindsBy(How = How.XPath, Using = "//android.widget.LinearLayout[14]/android.widget.RelativeLayout[0]/android.widget.EditText[0]")]
public IWebElement JobTest { get; set; }`

this screeen has many textboxs and to get this specific one I have to scroll down , and I thought when using the Xpath element, the screen will be scrolled down automatically....?
## Environment

Appium 1.5.4
C# - VS2013
Android SDK
Selennium

**Comment by mykola-mokhnach** [comment]
Nope, I don't think that scroll is going to be performed automatically. It is necessary to scroll the view manually until the necessary element is reached.
The pseudocode for it will look like this:
```
while not <element exists> do
     <scroll down>;
end while
```
Also, locating elements by their indices in the UI tree might be unstable. It would be better to search by id instead.

**Comment by elyanivson31** [comment]
I also prefer to use ID, unfortunately I'm not the developer of this specific app.
does Appium has default Scroll  down? I'm familiar with scrollTo and ScrollToExact.

**Comment by mykola-mokhnach** [comment]
Yep, these two method will scroll to the exact text label. In case there is no such label, you may use _swipe_ method to just scroll "blindly" thru the whole view until the necessary element is found.

**Comment by elyanivson** [comment]
I'll give it a try thanks

**Comment by qaDream77** [comment]
1. Check that the element is in view.
2. Yes? Click on it
3. No? Swipe down then go back to step 1.
