### ISSUE TITLE
push file to application data folder

### ISSUE THREAD

**Issue by talarari** [appium/appium#6692]
pushing a file to the applications data folder fails.(that is where the app saves files since it can only be accessed by the app and not any other app) like this (webdriver.io syntax)

```
browser.pushFile('/data/com.mypackage/someFile.txt',data)
```

getting permission denied, since normal adb cannot push to that directory.
we could support writing to the application folder like this:
http://stackoverflow.com/questions/22703254/copying-files-in-adb-shell-with-run-as

by pushing the file to a temp location, then using adb shell run-as packageName to move it to the application folder.

this would enable us to mock files used by the app without forcing the app to change code and save the files in a public location (very bad for security reasons).

any chance this is available in another way the is currently supported in appium that i don't know of?

**Comment by imurchie** [comment]
This seems like a good thing to implement. I will put it in the features pile. To be honest, though, we won't have many cycles to spend on it.

Is there any chance you want to take a stab at implementing this? I'd be happy to help point you in the right direction.

**Comment by mykola-mokhnach** [comment]
It is possible now to access files in application containers, but this only works for apps built with `debuggable` flag set to `true`. Other build types throw Access Denied error while trying to access container content via `run-as`.
