### ISSUE TITLE
driver.swipe(SwipeElementDirection direction, int duration) does not works on Appium 1.4.13 with Java client 4.0.0

### ISSUE THREAD

**Issue by VenkateshPS** [appium/appium#6693]
## The problem

driver.swipe(SwipeElementDirection direction, int duration) does not works on Appium 1.4.13 with Java client 4.0.0
## Environment

* Appium version 1.4.13
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium :OS X yosemite 10.10.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:iOS 8.4
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:Appium .app

**Comment by SrinivasanTarget** [comment]
@VenkateshPS use latest version of appium server.Java-client syncs with latest server only.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by VenkateshPS** [comment]
I just checked on java client 3.4.1 and swipe works fine. 
@SrinivasanTarget  I cannot move to latest Appium as my tests use name locator.

**Comment by SrinivasanTarget** [comment]
Swipe implementation on java-client (3.4.1) and appium server (1.4.x) is not as per spec. So this has been changed in latest version of client and server. please see the details here: https://github.com/appium/appium/issues/6257#issuecomment-196949576 & https://github.com/appium/java-client/issues/350.

Instead i would suggest you to move to accessibilityID label from name locator strategy.
