### ISSUE TITLE
Appium issue while running in console with parallel execution

### ISSUE THREAD

**Issue by ArunVeer** [appium/appium#6698]
Dear Team,

Context of the issue: 
With Appium running in console, we are doing a parallel execution of 4 real devices connected to a iMac and 2 real devices connected to Mac Minis. We are using different ports for Appium. The issue seems to be totally inconsistent and below are the scenarios in which it happens,

1) Changing Native view from Web view - ERROR running Appium command: cb is not a function
This issue doesn't occurs when we try with Appium GUI, but when we run it through console, it occurs. The scenario go in native view but sometimes it still remains in web view so the it gives error as the element not found. It doesn't switch to native view then. So this causes the rest of the test cases also to fail.

2) WebDriver Exception - 
[java] WARNING: WebDriverException thrown by findElement(By.name: Close)
     [java] org.openqa.selenium.remote.SessionNotFoundException: 

This error is again is linked with switch to native / webview.
This error is very consistent and it occurs during parallel execution.

3) One scenario in a device execution completion (Pass/Fail):
Not sure about this but as observed, If 2 parallel execution is going on and if the scenario is failed/passed in one console then on the other device the scenario fails the execution of the other device

Also we have tried with reinstalling the Node JS but of no use

Appuie Version - Tried with 1.5.2, 1.4.13 and 1.4.16 - Issue is same

PS: I cannot share you the log files as it may contain the confidential information of the client

**Comment by bipin-k** [comment]
Dear @ArunVeer, Could you please share the source code you have written for parallel execution for analysis of multiple instance creation?

**Comment by saikrishna321** [comment]
@bipin-k see this https://github.com/saikrishna321/AppiumTestDistribution

**Comment by SrinivasanTarget** [comment]
@triager please close
