### ISSUE TITLE
Running Appium tests in parallel and using driver.quit() from one test kills/causes the other test(s) to fail.

### ISSUE THREAD

**Issue by aaronmagi** [appium/appium#6699]
## The problem

I am using `Java` to run `JUnit` test's in parallel to `Appium` servers configured with different ports and UUID's for each device.  I am running the same test on both phones.  It looks like when the test ends on the first phone it somehow interferes with the other phone which is still processing the same test.  This results in the error message and stack trace shown below. 

**This does NOT** happen every time.  It seems like most of the time the problem occurs but sometimes it will run a test on both without an issue.

**driver.quit()/close()**
As part of the tests we close out the driver at the end using `driver.quit()`.  Doing this causes the behaviour described above.  If I **REMOVE** `driver.quit()` all the tests will finish successfully.  The problem with this is that if I want to run other tests the driver session is still open in `Appium` and there is no way to close it unless I restart `Appium`.

Each JUnit test is run on its on Appium port and using the UUID of the device.

    processBuilder.command("appium", "--log-timestamp", "--log",
                    new File(logs, "appiumMCBLogger.txt").getAbsolutePath(), "-p", port, "-U", deviceSerial);

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.5.3 / Appium Java Client 4.0.0 / Appium 3.4.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: CentOS (Linux localhost.localdomain 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: Android 6.0.1 (LG / Samsung)
* Real device or emulator/simulator: Real Devices
* Appium CLI or Appium.app|exe: Appium linux application (Appium v1.5.3) with Appium Java Client 4.0.0 or 3.4.1

## Details

2 Different errors:
1:  
     org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Android bootstrap socket crashed: Error: This socket has been ended by the other party (WARNING: The server did not provide any stacktrace information)

2: 
     org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up (WARNING: The server did not provide any stacktrace information)

## Link to Appium logs

**Stack Trace**
[appium stacktrace.txt](https://github.com/appium/appium/files/386858/appium.stacktrace.txt)

**Appium Logs**
[appium.txt](https://github.com/appium/appium/files/386870/appium.txt)
[appiumError.txt](https://github.com/appium/appium/files/386871/appiumError.txt)
[appiumOutput.txt](https://github.com/appium/appium/files/386872/appiumOutput.txt)

**Comment by SrinivasanTarget** [comment]
Refer this: https://github.com/saikrishna321/AppiumTestDistribution

**Comment by SrinivasanTarget** [comment]
@triager please close
