### ISSUE TITLE
Xpath searching from the context of another element is not working as expected

### ISSUE THREAD

**Issue by LoveleenSaini** [appium/appium#6700]
## The problem

Background:
I have a scenario where I need to determine on run time if an element has a child element of a certain type (android.widget.TextView) and then get its text.
In my test I have used xpath searching from context of parent element to achieve this.

Problem:
When the test runs, Appium successfully detects if the child element exists BUT when I try to get its text (when it exists), it returns the text of first android.widget.TextView element from TOP of the page.
## Environment
- Appium version: 1.5.3
- OS: Windows 7 professional
- Node.js version: 4.4.7
- Mobile platform/version under test: Android/5.1.1
- Real device
- Appium CLI
## Link to Appium logs

https://gist.github.com/LoveleenSaini/0753b3507feb11c05a471d916d394b76
## Code To Reproduce Issue

```
    WebElement container = driver.findElementByXPath("//android.support.v7.widget.LinearLayoutCompat");
    List<WebElement> allTextViewsInContainer = container.findElements(By.xpath(".//android.widget.TextView"));
    if(allTextViewsInContainer.size() > 0)
    {
        for (WebElement textView : allTextViewsInContainer)
        {
            String text = textView.getText();
        }
    }
```

**And it works fine when I use following code therefore there is certainly a problem with Xpath searching from the context of another element.**

```
 List<WebElement> allTextViewsInContainer = driver.findElementsByXPath("//android.support.v7.widget.LinearLayoutCompat//android.widget.TextView");
 if(allTextViewsInContainer.size() > 0)
 {
     for (WebElement textView : allTextViewsInContainer)
     {
         String text = textView.getText();
      }
 }
```

**Comment by dpgraham** [comment]
Labelling this as Priority 2. A bug that has a known workaround.

**Comment by mykola-mokhnach** [comment]
this is not going to be revisited as UIA1 is considered obsolete and there is no such problem in UIA2
