### ISSUE TITLE
How to enable http://localhost in Safari?

### ISSUE THREAD

**Issue by z-vr** [appium/appium#6701]
Is it possible to be able to access [http://localhost](http://localhost) from a real iPad? I'm running a proxy on my computer and have added it to the iPad's wi-fi config, but I'm not able to open locahost in safari browser. I think the problem is not in proxy, because I can see images on a webpage, e.g., `http://localhost:8080/squid-internal-static/icons/SN.png`, however I cannot access localhost from Chrome or Safari. For example, browserstack have implemented it somehow.

**Comment by SrinivasanTarget** [comment]
Please raise your question in discussion forum of appium

**Comment by SrinivasanTarget** [comment]
@triager please close
