### ISSUE TITLE
Alert window from browser not accessible to driver for iOS

### ISSUE THREAD

**Issue by sandykaka** [appium/appium#6702]
- Appium version (or git revision) that exhibits the issue: 1.4.13 (tried with latest version but it has issues launching app through GUI so reverted to 1.4.13)
- Desktop OS/version used to run Appium: OS X 10.11.6 (15G31)
- Real device: iphone 9.3.1

I am having exactly similar issue as https://github.com/appium/python-client/issues/121

I tried to find answer and I found suggestion to use `desired_caps['autoAcceptAlerts'] = True`
But this only works if user is in same app as it was launched. If user clicks on deeplink or any link which opens through browser and pops-up alert window it just hangs until timeout.

```
info: <-- POST /wd/hub/session/9b097c07-9527-4e5f-95a8-a99dba12d9af/element/3/click 200 1204.922 ms - 74 {"status":0,"value":"","sessionId":"9b097c07-9527-4e5f-95a8-a99dba12d9af"}
info: --> POST /wd/hub/session/9b097c07-9527-4e5f-95a8-a99dba12d9af/element {"using":"xpath","sessionId":"9b097c07-9527-4e5f-95a8-a99dba12d9af","value":"//UIAbutton[@name='Open']"}
info: [debug] Waiting up to 0ms for condition
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()
info: [debug] [INST] 2016-07-28 21:42:23 +0000 Debug: evaluation finished
info: [debug] [INST] 2016-07-28 21:42:23 +0000 Debug: responding with:
info: [debug] [INST] 2016-07-28 21:42:23 +0000 Debug: Running system command #15: /usr/local/Cellar/node/6.3.1/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
```

Appium comes out of stuck situation if I manually go back to app.

As mentioned in above logs I tried to click on Alert window Open button using xpath as `//UIAbutton[@name='Open']"` but it just gets stuck and once I come back to app manually it fails with error [debug] Responding to client with error: `{"status":7,"value":{"message":"An element could not be located on the page using the given search parameters."},"sessionId":"9b097c07-9527-4e5f-95a8-a99dba12d9af"}`
I can communicate with alert windows in app but not when app goes in background as browser and browser alert window pops-up.

![img_0002](https://cloud.githubusercontent.com/assets/8442050/17231203/575e534e-54d5-11e6-88a8-19797721ecea.jpg)

**Comment by liangway** [comment]
Same issue

**Comment by mykola-mokhnach** [comment]
I don't think there is a workaround for such issue if the alert is also not visible in the native context. We are pretty limited with what XCTest provides to us.
