### ISSUE TITLE
Enhancement: Accelerometer and Gyroscope Simulation

### ISSUE THREAD

**Issue by gsccheng** [appium/appium#6704]
Hi, as an enhancement, I'd like to request the features of being able to simulate mobile device orientation (physically, not portrait/landscape) and acceleration. Thanks.

**Comment by dpgraham** [comment]
We can only simulate what UIAutomator2 can simulate.

Looking at the docs (https://developer.android.com/reference/android/support/test/uiautomator/UiDevice.html) we've already simulated everything orientation related. As for acceleration, I know of no such automation tools. 

If anyone is aware of any, feel free to post a link on this issue thread.
