### ISSUE TITLE
Appium error - A new session could not be created

### ISSUE THREAD

**Issue by Abhresh** [appium/appium#6705]
## The problem
I am trying to run my first program into Appium and it worked before but not working now.
the program is to install and run an app (bookmyshow app) on android emulator.

##
The configuration is intact as it was when the same code run successfully but now its not working and showing this error,
Server Running,
ADV Running,
code showing no errors.

## Code To Reproduce Issue [ Good To Have ]

package Android;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import org.junit.Test;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;

public class desiredcapb {

	@Test
	public void test() throws MalformedURLException {
	File appDir = new File("src");
	File app = new File(appDir,"Battery Saver Pro.apk");
	DesiredCapabilities capabilities = new DesiredCapabilities();
	capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
	capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Android Emulator");
	capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
	AndroidDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);		
	}
}

## Appium Server Logs:
> info: --> POST /wd/hub/session {"desiredCapabilities":{"app":"C:\\Users\\Abhresh\\Documents\\APPIUM\\Appiuminto\\src\\Battery Saver Pro.apk","platformName":"Android","deviceName":"Android Emulator"}}
> info: Client User-Agent string: Apache-HttpClient/4.5.1 (Java/1.8.0_91)
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from desired caps: C:\Users\Abhresh\Documents\APPIUM\Appiuminto\src\Battery Saver Pro.apk
> info: [debug] Creating new appium session bee81b96-b555-47d6-a072-6ba71238a151
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_91
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from D:\Training\APPIUM\sdk\platform-tools\adb.exe
> info: [debug] Parsing package and activity from app manifest
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from D:\Training\APPIUM\sdk\build-tools\23.0.3\aapt.exe
> info: [debug] Extracting package and launch activity from manifest.
> info: [debug] executing cmd: D:\Training\APPIUM\sdk\build-tools\23.0.3\aapt.exe dump badging "C:\Users\Abhresh\Documents\APPIUM\Appiuminto\src\Battery Saver Pro.apk"
> info: [debug] badging package: apps.ignisamerica.batterysaver.pro
> info: [debug] badging act: apps.ignisamerica.batterysaver.controller.activity.SplashActivity
> info: [debug] Parsed package and activity are: apps.ignisamerica.batterysaver.pro/apps.ignisamerica.batterysaver.controller.activity.SplashActivity
> info: [debug] Using fast reset? false
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: D:\Training\APPIUM\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device emulator-5554
> info: [debug] Setting device id to emulator-5554
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: D:\Training\APPIUM\sdk\platform-tools\adb.exe -s emulator-5554 wait-for-device
> info: [debug] executing cmd: D:\Training\APPIUM\sdk\platform-tools\adb.exe -s emulator-5554 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: D:\Training\APPIUM\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: Device API level is: 19
> info: [debug] Extracting strings for language: default
> info: [debug] executing cmd: D:\Training\APPIUM\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] java -jar "D:\Training\APPIUM\Appium\Appium Server\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\Abhresh\Documents\APPIUM\Appiuminto\src\Battery Saver Pro.apk" "C:\Users\Abhresh\AppData\Local\Temp\apps.ignisamerica.batterysaver.pro" en
> info: [debug] Reading strings from converted strings.json
> info: [debug] Setting language to default
> info: [debug] executing cmd: D:\Training\APPIUM\sdk\platform-tools\adb.exe -s emulator-5554 push "C:\\Users\\Abhresh\\AppData\\Local\\Temp\\apps.ignisamerica.batterysaver.pro\\strings.json" /data/local/tmp
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: Could not push strings.json
> info: [debug] Error: Could not push strings.json
>     at D:\Training\APPIUM\Appium\Appium Server\node_modules\appium\lib\devices\android\android.js:347:26
>     at [object Object].<anonymous> (D:\Training\APPIUM\Appium\Appium Server\node_modules\appium\node_modules\appium-adb\lib\adb.js:178:16)
>     at ChildProcess.exithandler (child_process.js:758:5)
>     at ChildProcess.emit (events.js:110:17)
>     at maybeClose (child_process.js:1016:16)
>     at Process.ChildProcess._handle.onexit (child_process.js:1088:5)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not push strings.json)","origValue":"Could not push strings.json"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 12230.414 ms - 176

**Comment by imurchie** [comment]
What did you change?

What happens if you run the following command manually (i.e., from the command line):

```
D:\Training\APPIUM\sdk\platform-tools\adb.exe -s emulator-5554 push "C:\Users\Abhresh\AppData\Local\Temp\apps.ignisamerica.batterysaver.pro\strings.json" /data/local/tmp
```

**Comment by Abhresh** [comment]
@imurchie 

This is what i got when i run in command line...

C:\Users\Abhresh>D:\Training\APPIUM\sdk\platform-tools\adb.exe -s emulator-5554 push "C:\Users\Abhresh\AppData\Local\Temp\apps.ignisamerica.batterysaver.pro\strings.json" /data/local/tmp
adb: error: connect failed: device 'emulator-5554' not found

**Comment by Abhresh** [comment]
@imurchie 

I just added one ready project to check how the code runs... and made some changes in the code only... no changes in the configuration... sand just after that i am facing this issue...

**Comment by imurchie** [comment]
Is your emulator running? Run the emulator and try the command again.

**Comment by Abhresh** [comment]
Emulator is running, even the AVD is running but Same situation...

C:\Users\Abhresh>D:\Training\APPIUM\sdk\platform-tools\adb.exe -s emulator-5554 push "C:\Users\Abhresh\AppData\Local\Temp\apps.ignisamerica.batterysaver.pro\strings.json" /data/local/tmp
adb: error: connect failed: device 'emulator-5554' not found

**Comment by imurchie** [comment]
Ok. Can you change that part to whatever the emulator is? (to find the emulator, you can run `adb devices`).

**Comment by Abhresh** [comment]
this is the result:

C:\Users\Abhresh>adb devices
adb server is out of date.  killing...
* daemon started successfully *
List of devices attached
emulator-5554   device

**Comment by imurchie** [comment]
And the push command fails with the same error? Not finding the device?

**Comment by Abhresh** [comment]
Yes

**Comment by imurchie** [comment]
I have no idea, then.

**Comment by Abhresh** [comment]
Finally got the hurdle passed... Error is now skipped by going with Fresh Start.... But yes the issue is not resolved as we have not sure ans how to solve that error. Thanks alot

**Comment by imurchie** [comment]
No problem. If it comes up again we can see if we can get to the bottom of it somehow.
