### ISSUE TITLE
Appium crashes after starting adroind session when executing command wait-for-device

### ISSUE THREAD

**Issue by mn8** [appium/appium#6711]
## The problem

When running Android tests on a jenkins server, appium will crash when it tries to wait-for-device. 
Strangely appium will be able to see the simulator, and start the android session normally. Than it will very quickly wait-for-device before restarting adb all together. After which it will see that no devices are connected.  

## Environment

*Appium: 1.5.3
* OSX on Jenkins server
* Node.js version (unless using Appium.app|exe):
* Android API-19
* Simulator
* Appium CLI

## Link to Appium logs
https://gist.github.com/anonymous/7c796e5bf123e0ab32909fb280a57088

## Code To Reproduce Issue [ Good To Have ]
//Emulator is started using the android emulator plugin:

#start appium
node /Applications/Appium.app/Contents/Resources/node_modules/appium/build/lib/main.js --no-reset &
sleep 15s
#remove spec timeout
sed -i -e "s/.*this.timeout.*//g" ./test/**/$TEST_SUITE
rm ./test/**/$TEST_SUITE-e

#run spec
node_modules/.bin/mocha --reporter mochawesome --timeout 300000 test/**/$TEST_SUITE

**Comment by mykola-mokhnach** [comment]
It looks like the simulator is slow and _adb wait-for-device_ commands take more that default 10 seconds timeout. Look for system-calls.js file inside Appium sources and change the default timeout in this line
```javascript
systemCallMethods.waitForDevice = async function (appDeviceReadyTimeout = 30) {
```
to 
```javascript
systemCallMethods.waitForDevice = async function (appDeviceReadyTimeout = 90) {
```

then restart appium service and try again.

**Comment by email2vimalraj** [comment]
I believe this is exactly the same problem I face which I have reported here: #6584.

@mn8 : Did you try on Appium 1.4.16? Kindly see whether it works fine on Appium 1.4.16, because I don't have this problem when I run my tests on 1.4.16.

**Comment by imurchie** [comment]
You can stop the killing of the adb instance by starting Appium with the server flag `--suppress-adb-kill-server`

**Comment by email2vimalraj** [comment]
The `--suppress-adb-kill-server` also didn't help.

**Comment by imurchie** [comment]
Can you say a little more about that? Because if it produces the exact same result, then it is not the restarting of adb. Logs are always good. The less information, the less anyone can do.

**Comment by mn8** [comment]
Setting the device timeout work for me

**Comment by lclmq** [comment]
Why I did't find the system-calls.js file inside Appium sources..
