### ISSUE TITLE
MobileElement.isSelected() method does not work for android.widget.CheckBox on Android

### ISSUE THREAD

**Issue by qual** [appium/appium#6712]
## The problem

Irrespective of whether the Checkbox is checked or not, MobileElement.isSelected() method **always returns false**. It should return true if checkbox is checked and false if checkbox is unchecked. 
## Environment
- Appium version (or git revision) that exhibits the issue: Appium 1.5.3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Windows 7
- Node.js version (unless using Appium.app|exe): 4.4.5
- Mobile platform/version under test: Android  6.0 (Marshmallow)
- Real device or emulator/simulator: Android emulator
- Appium CLI or Appium.app|exe: Appium CLI
## Details

Note: This method works correctly on iOS 9.3 simulator
## Link to Appium logs

https://gist.github.com/qual/6dd2015de7336c09fa67dc75b1b4bd04
## Code To Reproduce Issue [ Good To Have ]

MobileElement checkbox = driver.findElementByAccessibilityId("mycheckbox");
System.out.println("selected:" + checkbox.isSelected());
## Output

False 
(Although, checkbox is checked)

**Comment by mykola-mokhnach** [comment]
Which standard Android UI class your checkbox inherits? This one https://developer.android.com/reference/android/widget/CheckBox.html or it is some custom one?

**Comment by qual** [comment]
I don't have custom checkbox. I am using Android's standard checkbox (https://developer.android.com/reference/android/widget/CheckBox.html)

**Comment by aniket-21** [comment]
Ideally you should  be  checking for attribute checked rather than selected

**Comment by qual** [comment]
I am aware of that alternative. But since Appium claims to provide transparency over Android and iOS native automation libraries, all the methods are supposed to work in a same way over both the platforms. So isSelected() is supposed to work correctly in both Android and iOS (Nothing mentioned in documentation about whether it works on only iOS)
Also, in my case, I am not supposed to write platform specific code using Appium.

**Comment by aniket-21** [comment]
If selected has a different meaning altogether in android context it doesn't make sense to use it in place of checked attribute, if you are expecting to use 100% same code for Android and iOS by now you should be well aware that you have chosen a wrong tool. I would have handled this scenario in my own wrapper function

**Comment by qual** [comment]
why the selected attribute would have a different meaning in Android context?

**Comment by qual** [comment]
@aniket-21 
Why the isSelected() would have a different meaning in Android context? Its clearly an implementation of remote web element. So Appium is supposed to handle it internally for Android and iOS. 
I believe, contrary to you mentioned, instead of me abstracting the behavior, Do you not think that Appium should abstract behavior being a Platform agnostic framework ?

Also, I understand there would be platform specific behaviors in some of the methods but shouldn't those behaviors be organized into Android or iOS specific separate methods ? Since the AndroidElement extends MobileElement which extends RemoteWebElement. Since the isSelected() is part of RemoteWebElement the behavior should be overridden appropriately for Android and iOS element.

I just wanted to have clarification from Appium devs whether this is a known issue or something that has never been seen before.

**Comment by qual** [comment]
Any updates on this issue ?

**Comment by mykola-mokhnach** [comment]
One must use `checked` attribute of an element if it is a checkbox to verify whether it is selected not: https://stackoverflow.com/questions/31717440/checkbox-setselected-not-working-when-using-androiddrawableright-property/31717669
