### ISSUE TITLE
pass data to android app before it launches

### ISSUE THREAD

**Issue by talarari** [appium/appium#6714]
i need to be able to pass some data (a string is enough) from the appium test to the app.
the data needs to be available for the app from the start, so it can use it in a very early part of the code happening in android's Application.OnCreate method.

i cant find a way to pass that data early enough, i've tried:
1.  optionalIntentArguments capability :
i get the data in main activity, after application onCreate, too late.  
2. pushFile - write the data to the device storage before launching the app:
i cant write to the private application storage (see this [issue](https://github.com/appium/appium/issues/6692))
writing to a public storage folder requires me to add a permission to my app , which i'm not going to do.  
3. is it possible to change share preferences somehow? that would solve this for me.

any other way you can think of to solve this?

i really dont want to resort to running adb commands... would really prefer some clean appium way of doing this.

**Comment by mykola-mokhnach** [comment]
For our app we pass data from tests via messages broadcasting. Check https://github.com/majido/clipper implementation as an example. Just execute the corresponding _adb broadcast_ command as soon as driver initialization is finished in the test code and you should be good to go.

**Comment by talarari** [comment]
Is adb broadcast supported in appium? I'm running against a testdroid device farm, so running adb commands is much harder.
