### ISSUE TITLE
Support delete File

### ISSUE THREAD

**Issue by talarari** [appium/appium#6718]
Appium currently supports push file and pull file, couldn't find documentation about deleting a file.
This is required to perform clenup when pushing files for a test

**Comment by Jiurong-Yang** [comment]
Is there any updates for this feature?

**Comment by KazuCocoa** [comment]
As a temporary solution, you can call `adb shell rm xxxxxx` via https://appiumpro.com/editions/3

**Comment by mykola-mokhnach** [comment]
the feature has been added to iOS using mobile: deleteFile endpoint

**Comment by mykola-mokhnach** [comment]
The endpoint has been added for both iOS and Android
