### ISSUE TITLE
Unable to select a value for month and year in date picker

### ISSUE THREAD

**Issue by asinghdminc** [appium/appium#6719]
Hi i am trying to automate a feature in which i have to select a date using date picker in android 6.0. I am able to select the year which is visible on the screen, but i am unable to scroll to a year and select it. 

Also i am facing problem in selecting a month.

**Comment by bipin-k** [comment]
Could you please send Screenshot and UiX files?

**Comment by asinghdminc** [comment]
Hi @bipin-k 

Please find attached screenshot. I don't know what do you mean by UiX files.

![image](https://cloud.githubusercontent.com/assets/12182643/17801614/c68ca024-6608-11e6-9029-ca6d407d263e.png)

**Comment by bipin-k** [comment]
@asinghdminc Could you please let me know the app name?
If possible, please try with UIAutomatorViewer Tool and check id/xpath of the year you want to tap.

**Comment by asinghdminc** [comment]
@bipin-k this is a normal date picker you can use any app for this. And xpath thing doesn't work because it stays same for all elements visible on the screen.

**Comment by dpgraham** [comment]
Closing this. If this is still an issue I'll re-open.
