### ISSUE TITLE
WebKit Threading Violation - initial use of WebKit from a secondary thread / UI Automation Enabled

### ISSUE THREAD

**Issue by Sivanur** [appium/appium#6724]
## The problem

I can't seem to get rid of the WebKit Threading Violation I get: 
[debug] [Instruments] [INST STDERR] 2016-08-09 11:32:29.167 instruments[20737:2462620] WebKit Threading Violation - initial use of WebKit from a secondary thread.

As I read the most common suggestion is to enable the UI Automation which is already enabled.
This issue started occurring after updating the Appium app from version 1.4.8 to 1.5.3 
## Environment
- Appium version: 1.5.3
- Last Appium version that did not exhibit the issue: 1.4.8 
- Desktop OS/version used to run Appium: OS X EL Capitan version 10.11.6
- Node.js version (unless using Appium.app|exe): Using Appium.app
- Mobile platform/version under test: iOS 9.3.2
- Real device or emulator/simulator: iPhone 6 Real Device
- Appium CLI or Appium.app|exe: Appium.app
## Link to Appium logs

https://gist.github.com/Sivanur/77c74a0d439b56eff8b2601c738f1601
[Client logs for Appium issue.txt](https://github.com/appium/appium/files/408551/Client.logs.for.Appium.issue.txt)

**Comment by jawlitkp** [comment]
I am facing issue ,ended up downgrading to 1.4.8

**Comment by raja22ganesan** [comment]
Am facing the same issue. Is it resolved in 1.4.8?
