### ISSUE TITLE
Android Radial Time Picker can not be accessed

### ISSUE THREAD

**Issue by Pansch** [appium/appium#6727]
## The problem

The radial time picker in Android cannot be accessed. If the xpath of an hour(1-12) is provided, the element is not found.

## Environment

Appium 5.3
Windows 7
Real Device: Nexus 5, 
Android 6.0.1
Nodejs: 4.4.7

**Comment by SrinivasanTarget** [comment]
Please raise your question with proper details in discuss.appium.io

**Comment by SrinivasanTarget** [comment]
@triager please close
