### ISSUE TITLE
Can't connect Appium to the Selenium Grid

### ISSUE THREAD

**Issue by srigney** [appium/appium#6729]
## The problem

I am attempting to connect Appium to the Selenium grid. I get the Selenium Grid up fine but when I execute the command to register a node through Appium I get an error stating 'Request to register with the grid was unsuccessful...hub down or not responding. Both Appium and the Selenium grid are on my localhost.

## Environment

* Appium version: 1.4.11 (can't upgrade to 1.5 because swipe is broken)
* Desktop OS/version: OSX El Capitan
* Node.js version (unless using Appium.app|exe): 6.3.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details
I am able to manually register a node using Postman and the config.json as the body, but when I do the Selenium grid says it can't communicate with the Appium server.

## Link to Appium logs
https://gist.github.com/srigney/f18eff02b9a48c4e6fcc79ea44d2643c

**Comment by mykola-mokhnach** [comment]
Have you noticed this tutorial http://appium.io/slate/en/master/?java#grid-node-configuration-example-json-file?

What I can see in the given node config file - the 'url' property with full hub address is missing

**Comment by srigney** [comment]
Yes I have seen that tutorial along with every other one out there. I did also try it with the url property and received the same results. In looking at the Appium code it appears that the Selenium grid cares more about the id property (which I proved with a manual post) and the Appium code actually constructs this based on the host and port if it's not present. 

When I did the manual post without the id but with the url I received an error message saying the id property was missing. So I removed the url and put in the id property and received a 200 response and the node was registered and showing in Grid Console. 

If I use the Selenium jar to register a node it works
java -jar /Users/sounduser/Selenium/selenium-sver-standalone-3.0.0-beta2.jar -role node  -hub http://localhost:4441/grid/register

**Comment by mykola-mokhnach** [comment]
Maybe, it does not like the fact that host name is localhost? Try to replace it with real host IP address .

**Comment by srigney** [comment]
I replaced all instances of localhost with the ip address and got the same results.

**Comment by tommywo** [comment]
@srigney if you need to set custom id for node please build appium from source, as fix was merged after 1.5.3 release. If not then get rid of id in nodeconfig

From logs it looks like a problem with connectivity, maybe try to run appium with `-a` parameter - i had some problem with it running on wrong network (somehow network from VirtualBox was default).
`appium -a 127.0.0.1 -p 4729 --nodeconfig /Users/sounduser/Automation/Appium_Iphone_Sim.json`

**Comment by srigney** [comment]
@tommywo The id was in the config file in order to test registering a grid manually through Postman. The id is a requirement of Selenium grid. I don't need it in the config file when trying to run through Appium.

I'm not sure why you are telling me to use the -a parameter instead of -i, since I'm not using -i parameter in the first place, not even sure what it is used for.

And why do you have the ip address of 127.0.0.1, are you just using that ip as an example?

This is the command and config I am using currently:
appium -a 192.168.1.3 -p 4723 --nodeconfig /Users/sounduser/Automation/Simulator.json

**Simulator.json**
{
    "capabilities": [
        {
            "browserName": "Safari",
            "platformVersion": "9.3",
            "maxInstances": 1,
            "platformName": "iOS",
            "deviceName": "iPhone 6"
        }
    ],
    "configuration": {
        "cleanUpCycle": 2000,
        "timeout": 300000,
        "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
        "maxSession": 1,
        "host": "192.168.1.3",
        "port": 4723,
        "hubPort": 4441,
        "hubHost": "192.168.1.3",
        "register": true,
        "registerCycle": 5000,
        "role": "node"
    }
}

**Comment by srigney** [comment]
Thanks to everyone for tyring to help, I was able to get it working. Somehow my when my config saved at one point the directory was changed to a temp directory. So the config file I was using in my node command was the wrong version.

I was able to find this out by upgrading to Appium 1.5 which has more verbose error reporting. Now I will try to go back to 1.4.3 since swipe is broken in 1.5.
