### ISSUE TITLE
Appium not working with iOS 9.3.4

### ISSUE THREAD

**Issue by waynema** [appium/appium#6730]
## The problem

Appium not working on iOS 9.3.4
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Desktop OS/version used to run Appium: Mac OS 10.11.6
- Node.js version (unless using Appium.app|exe): 5.7.0
- Mobile platform/version under test: iOS 9.3.4
- Real device or emulator/simulator: real device
- Appium CLI or Appium.app|exe:  CLI
## Details

After upgrade to iOS 9.3.4 on devices,  all my appium tests are not working and give instruments crashed on startup errors.  I have to downgrade to 9.3.3 immediately.
## Code To Reproduce Issue [ Good To Have ]

Just update to iOS 9.3.4 and see for yourself

**Comment by imurchie** [comment]
Yes, there was a change in the secure connection between the computer and the phone in 9.3.4, unfortunately (you probably also notice that you need to trust the computer on each connection). 

There has been some success with rebuilding libimobiledevice from source. They are working on a full fix, which Appium will make use of.

**Comment by siva2503** [comment]
Meanwhile.!! the below link can be followed to downgrade the version, just as a workaround!

http://www.redmondpie.com/how-to-downgrade-ios-9.3-on-iphone-or-ipad-tutorial/

ipsw download link - http://www.redmondpie.com/download-ios-9.3.3-ipsw-for-iphone-and-ipad-final-version/

**Comment by skumar1122** [comment]
@imurchie 
Is new Appium 1.6.0-beta1 version supports 9.3.4 versions ?

**Comment by imurchie** [comment]
It will once one PR is merged. Right now it still depends on libimobiledevice.

**Comment by imurchie** [comment]
libimobiledevice seems to work with 9.3.5.

**Comment by skumar1122** [comment]
9.3.5 is working.

**Comment by pmeyyapp** [comment]
@skumar1122 , how did you get it to work ?

**Comment by skumar1122** [comment]
upgraded from 9.3.4 to 9.3.5 but I had Xcode beta in my laptop so I have to uninstall it and install Xcode 7 again and restarted laptop and worked fine with my tests used iPhone5s like before with appium 1.5.3
