### ISSUE TITLE
Is it possible to prevent Appium from restarting between specs?

### ISSUE THREAD

**Issue by azaslavsky** [appium/appium#6734]
## The problem

Not sure how to prevent appium from resetting between specs.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.4.16
- Desktop OS/version used to run Appium: OSX 10.11.3 El Capitan
- Node.js version (unless using Appium.app|exe): 4.4.4
- Mobile platform/version under test: iPhone 6
- Real device or emulator/simulator: Simulator
- Appium CLI or Appium.app|exe: CLI
## Details

Suppose that in my specs capability, I submit the following: 

``` javascript
capabilities: {
  noReset: true,
  specs: ['a.test.js', 'b.test.js']
  //Other capabilities
}
```

Then , when I run appium with the CLI command of `appium -lt 180000 --session-override --no-reset`, I expect both specs to be run without reseting the emulator in between.  However, what actually happens is that the emulator is reset after each spec completes (but not between individual tests within the specs).  Is there any way to circumvent this, and run all specs consecutively on one instance on the emulator?

**Comment by mykola-mokhnach** [comment]
Have you tried to use suites instead of specs? https://github.com/angular/protractor/blob/master/docs/referenceConf.js

It would be nice to see the log output (both protractor and appium after spec file is switched).

**Comment by azaslavsky** [comment]
So I'm using webdriver.io (rather than protractor), and via a CLI call that specifies which files to test, so I can't set suites that way.  I'll get the test output in a bit.

**Comment by mykola-mokhnach** [comment]
I don't know how webdriver.io does the job, but based on this [tutorial](http://webdriver.io/guide/testrunner/organizesuite.html) it executes every separate suite in a separate process, which might cause your issue. So, by organizing tests into suites and passing multiple suite names to the CLI runner once rather than executing separate specs multiple times might help to solve the issue.

**Comment by butlersrepos** [comment]
This is relevant to my interests. I'm doing the same setup (webdriver.io, appium) and the specs each teardown the emulator and restart it for each one which is a massive timesink.

**Comment by dpgraham** [comment]
Closing this. This is more of a discussion topic then it is an issue.

As for not setting-up/tearing-down on every test, that's not an Appium issue so much as it is a test framework issue. You'll have to find out on the test framework how to start a session globally before any tests run and tear it down after all tests are run

I know that for Mocha (and possibly Protractor/Jasmine, but don't hold me to it) you can have a global before and after

```javascript
before(function () {
  // Setup appium session
});
after(function () {
  // Tear down appium session
});
```
