### ISSUE TITLE
Appium, Ruby & Android optionalIntentArguments issue

### ISSUE THREAD

**Issue by THEMrFill** [appium/appium#6735]
## The problem

We are trying to pass extra arguments to an app to automate certain bits of functionality, some of the keys & values contain hyphens which is causing us a bit of a problem as when the command is run via Appium it adds a space in at odd points
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable): 
- Desktop OS/version used to run Appium: OS X 10.11.6 (15G31) 
- Node.js version (unless using Appium.app|exe): 6.2.1
- Mobile platform/version under test: Android 5.1.1 / 6.0.1
- Real device or emulator/simulator: Sony Xperia Z /  LG Nexus 5X
- Appium CLI or Appium.app|exe: CLI
## Details

In the Capabilities we are adding several entities in :optionalIntentArguments, each pre-pended with --es (Extra String), with the Key & Value sent through, but whenever the key or value gets to a certain length, and includes a hyphen, the key or value breaks, e.g.
`quick-register.device-identifier ABCD123-EFGH456-IJKL7890`
turns into
`quick-register.device -identifier`
and if we put apostrophes/quotes around the key
`'quick-register.device -identifier' ABCD123`

As we're using this information to speed up processing, it breaking causes our scripts to give false negatives as the passed values are incorrectly received.
## Link to Appium logs

Will upload if required, but don't appear to show much related to the values
## Code To Reproduce Issue [ Good To Have ]

`caps[:optionalIntentArguments] = " --es quick-register.device-identifier ABCD123-EFGH456-IJKL7890"`

`$driver.caps = caps`
`$driver.start_driver`

**Comment by mykola-mokhnach** [comment]
It looks like a bug in Appium to me.
As a temporary workaround you can do the following:
1. Locate the file _appium-adb/lib/helpers.js_
2. Find the function _buildStartCmd_
3. Replace the following code:

```javascript
if (startAppOptions.optionalIntentArguments) {
    // expect optionalIntentArguments to be something like '-x options',
    // '-y option argument' or a combination of the two
    let argRe = /(-[^\s]+) ([^-]+)/g;
    while (true) {
      let optionalIntentArguments = argRe.exec(startAppOptions.optionalIntentArguments);
      if (!optionalIntentArguments) {
        break;
      }
      let flag = optionalIntentArguments[1];
      let space = optionalIntentArguments[2].indexOf(' ');
      let arg, value;
      if (space === -1) {
        arg = optionalIntentArguments[2];
      } else {
        arg = optionalIntentArguments[2].substring(0, space).trim();
        value = optionalIntentArguments[2].substring(space + 1).trim();
      }
      cmd.push(flag, arg);
      if (value) {
        cmd.push(value);
      }
    }
  }
```

with 

```javascript
  if (startAppOptions.optionalIntentArguments) {
       let argRe = /('.*?'|".*?"|\S+)/g;
       cmd.push.apply(cmd, startAppOptions.optionalIntentArguments.match(argRe));
  }
```

4. Restart Appium service

**Comment by THEMrFill** [comment]
Hi,

I've found & updated several versions of `helpers.js` to no avail, and added `log.debug()` messages to check if the code is being executed, but I never get the message I've added.

We've even tested using the appium.app GUI, but have the same results.

Appium was installed along with NodeJS, using npm, so I don't know if the location is masked or already compiled into something that I'm not able to see/update.

Thank you for the assistance,
Phil

**Comment by mykola-mokhnach** [comment]
On my Mac OS 10.11.6 npm installs all libraries into _/usr/local/lib/node_modules_ folder.
The location of _helpers.js_ file is

/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-adb/build/lib/helpers.js
/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-adb/lib/helpers.js

You need to change the first one (in _build_ folder) - it is preprocessed and optimized version of the second one.

**Comment by mykola-mokhnach** [comment]
In case you execute Appium from GUI application then it is necessary to change the path to your local Appium binary in /usr/local/lib/ folder under developer settings otherwise change the helpers file, which is located inside Resources folder of Appium.app package (that binary is used by default if you don't provide any custom paths in developer settings).

**Comment by THEMrFill** [comment]
Hi,

I had to make a minor tweak to your code as it was returning an error on starting the Appium server:
`/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-adb/build/lib/helpers.js:424`
`        return e.replace(/^"|"$|^'|'$/g, '');`
`        ^^^^^^`
`SyntaxError: Unexpected token return`

To "hack" it slightly I got rid of the map method call - it works now, but I have to presume that our parameters will be _clean_ when we send them into the app, so the RegEx shouldn't be needed...

As we're supplying all information, we should know that it's clean, especially since all parameters are in a known format.

Again, thank you for the help, this got us over using a nasty "hack" to get it working.

Thanks,
Phil

**Comment by mykola-mokhnach** [comment]
There should be an opening curly bracket after _function(e)_ declaration 
```javascript
if (startAppOptions.optionalIntentArguments) {
    let argRe = /('.*?'|".*?"|\S+)/g;
    let matches = startAppOptions.optionalIntentArguments.match(argRe).map(function (e) {
        return e.replace(/^"|"$|^'|'$/g, '');
    });
    cmd.push.apply(cmd, matches);
  }
````

**Comment by mykola-mokhnach** [comment]
I wouldn't say this is 'hack', but rather bugfix. Thought I don't consider myself experienced enough to commit directly into Appium codebase. I'm just happy, that even with my shallow javascript knowledge it is possible to help one to solve the problem he faces :)

@jlipps  Please mark the issue as a bug

**Comment by THEMrFill** [comment]
That missing open curly brace fixed the error - I wasn't even thinking about that when I tried it, my JS is a little rusty and I'm used to the Java compiler giving me more information 😊

I hope this gets fixed soon - we're not spreading this fix around the office, rather waiting for the next update from the product.

Thanks,
Phil

**Comment by jgreen210** [comment]
This commit:

https://github.com/appium/appium-adb/commit/5db0b1acafe6f522b00419df6373353d1e2c2f6a

...was made before this bug was created, but post-dates the code mentioned above:

https://github.com/appium/appium/issues/6735#issuecomment-239920044

Does it fix this issue too? Its test cases suggest it should. github tells me it is in appium-adb release  v2.6.4. N.B. an appium-adb release version is not the same as an appium release version.

**Comment by jlipps** [comment]
I think the fix should indeed be in force. Closing this for now. If evidence of this or a new bug surfaces, we can deal with that as necessary. Thanks for your follow-up @jgreen210.
