### ISSUE TITLE
Update of Appium Documentation

### ISSUE THREAD

**Issue by BhaskarVj** [appium/appium#6737]
Hi Team,

While going through Appium official URL: **http://appium.io/**, found that appium can support only up to 9.2v. We're testing on 9.3.2 versions. Please update the same and please correct me if I'm wrong.

Versions: 7.1, 8.0, 8.1, 8.2, 8.3, 8.4, 9.0, 9.1 and 9.2

## Environment
Xcode 7.3.1,
iOS 9.3.2,
Appium 1.5.3.
Mac OSX 10.10

Regards,
Vijay Bhaskar.

**Comment by TuHuynhVan** [comment]
@BhaskarVj 
From the update on #6730. I don't think the document is outdated!

I think you got a best luck when running the test successfully with the current Env setting but not sure for other Env with same setting like that.

**Comment by saikrishna321** [comment]
@SrinivasanTarget can we close this
