### ISSUE TITLE
Cannot run tests on actual devices since OS X 10.11.6

### ISSUE THREAD

**Issue by rz-robsn** [appium/appium#6739]
## The problem

I am trying to run tests on real ios devices. 
## Environment
- git revision that exhibits the issue: tag 1.5.3
- Desktop OS/version used to run Appium: OS X 10.11.6
- Node.js version: 6.3.0
- Real devices :
  - Ipad Air 2 on iOS 9.2.1
  - Ipad mini 3 on iOS 8.11
  - Ipod touch (5th or 6th gen, I'm not sure) on ios 8.0
## Details

I first had the same problem as in issue #6679, which I fixed by starting the appium server as a superuser (which in turn runs ideviceinstaller as a super user as well). However when I do that, while the application does get installed on my target device, instruments systematically fails to start the app.

I've tried running only the instrument command as a regular user and as a super user. The command manages to launch the app only when I run it as a regular user.

I've also managed to make appium run the tests by modifying the appium source code so that it starts ideviceinstaller as a superuser (by just prepending "sudo" to the command invoked) and then running appium as a regular user.
## Link to Appium logs

This [gist](https://gist.github.com/rz-robsn/dcc008d4f649072e9bbaebce3a7087bd) describes what happened when : 
- I run appium as a super user and try to run test on an actual devices
- I run the instruments command as a super user
- I run the instruments command as a regular user
## Code To Reproduce Issue [ Good To Have ]

You can use the TestApp project from https://github.com/appium/sample-code to reproduce the issue.

**Comment by TuHuynhVan** [comment]
@rz-robsn 
Did you turn on [Enable UI] AutomationSettings > Developer ?

**Comment by rz-robsn** [comment]
@TuHuynhVan 

Yes, "Enable UI Automation" is enabled for all the devices I've specified. I forgot to mention it.

**Comment by TuHuynhVan** [comment]
@rz-robsn 
Make sure you have not installed Node or Appium with sudo?

**Comment by rz-robsn** [comment]
Both Node and Appium were installed without sudo.

I also could reproduce the problem launching the appium server shipped with Appium.app version 1.5.3.

**Comment by TuHuynhVan** [comment]
`[debug] [Instruments] Instruments exited with code 253`
--> There is many possible problems with this error. I faced this before and I have to installed all of thing from scratch (included rebuild the app). So just try some steps below first:

Can you try to do:
0. Make sure all tested iDevice are registered on AppleDeveloper
1. Start ios_webkit_proxy
2. Start appium server  Add flag [--native-instruments-lib] and try, if not OK -> Step 03
3. 
- Make sure ideviceinstaller is installed
-  brew update.

As I mentioned, I face this error before and I have to re-installed all of thing from a scratch!
Just my thought to help you check again all configurations.

**Comment by rz-robsn** [comment]
How do I start ios_webkit_proxy ? Should I install it view brew as defined [here](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/ios-webkit-debug-proxy.md) ?

**Comment by TuHuynhVan** [comment]
@rz-robsn 
Yes. Below is the summary and you can follow:
` # The first command is only required if you don't have brew installed.
 > ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
 > brew update
 > brew install ios-webkit-debug-proxy`

**Start it by using:**
`ios_webkit_debug_proxy -c **yourDeviceUDIDHere**:27753 -d`

**Comment by rz-robsn** [comment]
- All my devices are registered on Apple Developer.
- ideviceinstaller is installed.

This is what I did :

- I ran `brew update`
- Then I installed the `ios-webkit-debug-proxy` program, running the command gave me this :

```
± |automation/TA-196 {29} ✓| → ios_webkit_debug_proxy -c b7c2526f31bcd14d9bdaa1f3e0c35f7bf81c239a:27753 -d
ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=684
ss.add_server_fd(4)
Could not connect to lockdownd. Exiting.: Permission denied
ss.remove_server_fd(4)
Unable to attach b7c2526f31bcd14d9bdaa1f3e0c35f7bf81c239a inspector
Css.remove_fd(3)
```

- Then I run the same command as sudo, I don't have the `Could not connect to lockdownd.` message anymore.

```
→ sudo ios_webkit_debug_proxy -c b7c2526f31bcd14d9bdaa1f3e0c35f7bf81c239a:27753 -d
Password:
ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=684
ss.add_server_fd(4)
ss.add_fd(6)
wi.send_packet[245]:
 00 00 00 F1 62 70 6C 69 73 74 30 30 D1 01 02 5F 10 12 57  ....bplist00..._..W
 49 52 46 69 6E 61 6C 4D 65 73 73 61 67 65 4B 65 79 4F 10  IRFinalMessageKeyO.
 AA 62 70 6C 69 73 74 30 30 D2 01 03 02 04 5A 5F 5F 73 65  .bplist00.....Z__se
 ...more hexadecimal codes...
```

So without quitting the `sudo ios_webkit_debug_proxy` program, I started appium both with and without sudo then ran the test, and Appium still throws me an error.

This [gist](https://gist.github.com/rz-robsn/6c389978c540c9aa85e76f050f55b8b4) contains the appium logs, it's not much different from one from my first comment.

**Comment by TuHuynhVan** [comment]
@rz-robsn 
I don't know why you are always required [sudo] for every single command like that. So strange!

I have never faced that error before.

May this help you:
https://github.com/libimobiledevice/libimobiledevice/issues/243

**Comment by rz-robsn** [comment]
@TuHuynhVan The issue that you referred to mentioned that uninstalling the libraries fixed the problem. So I uninstalled and reinstalled `ios_webkit_debug_proxy` via Homebrew. I also uninstalled `ideviceinstaller` and all its dependencies and re-installed them again.

The problem is still not fixed. I have the same issues I reported in my initial post, regardless of if run `ios_webkit_debug_proxy` or not.

I don't know what I can do at this point. Any help would be appreciated. 

Thanks !

**Comment by saikrishna321** [comment]
@rz-robsn can you please try launching the application from instruments and see if that works

**Comment by saikrishna321** [comment]
@rz-robsn can you please try launching the application from instruments and see if that works

**Comment by rz-robsn** [comment]
@saikrishna321 : Running tests using the Instruments GUI works. Once I build and install the application on the device, I can record and run javascript UIAutomation code using the Automation template from the Instruments application.

**Comment by mayureshshirodkar** [comment]
@rz-robsn Even i am facing the same issue, Since i updated to El captain 10.11.6. Did you find any workaround for this?

**Comment by rz-robsn** [comment]
@mayureshshirodkar,

There are different workarounds for this problem. None of which I like :
* Don't run your test on a real device but on the simulator
* change the appium source code so that the `ideviceinstaller` command is launched as a super user and make sure you run node as a regular user.
* install the application on the device manually beforehand and just specify your app bundle id in your test capabilities (instead of specifying the path/url to your ipa file). 
* Do the same as the previous point, but instead of installing the application manually, you call the `ideviceinstaller` command yourself before you run your test.

Right now I'm just running my tests using the simulator only.

**Comment by mayureshshirodkar** [comment]
Meanwhile,  After a lot of googling and research, came across this post. Helped me fix the issue. May be a temporary fix, but it works.

http://stackoverflow.com/questions/39035415/ideviceinstaller-fails-with-could-not-connect-to-lockdownd-exiting

Use:
sudo chmod -R 777 /var/db/lockdown/

**Comment by shusso** [comment]
For me xcode8GM in osx 10.11.5 required to recompile the libimobiledevice to get pass the lockdown issue. See [this](https://github.com/libimobiledevice/libimobiledevice/issues/346#issuecomment-246592802)
