### ISSUE TITLE
Unable to launch app to iOS Simulator

### ISSUE THREAD

**Issue by mn8** [appium/appium#6741]
## The problem

 I am unable to run my test in an iOS simulator. I have tried running via code, and running via the inspector, neither one seems to install the app correctly on the simulator device. I have been able to manually install app so I know it's not that.  And when appium runs it will reset the simulator so it's connected to it. I have tried pointed it to both .ipa files and .app files. 

What happens: 
## Environment
- 1.5.3/1.5.2/1.4.7
- El Capitan
- iPhone /9.3:
- Simulator:
- Appium App:
## Details

Caps Im using:
`exports.iPhone = {
        browserName: '',
        //udid:'87D75FAB-5DD2-4E7E-82A9-A0E4BD783D62',
        platformName: 'iOS',
        platformVersion:'9.3',
        noReset:true,
        app:"/Users/patrick.coady/kronos/automation/apps/KronosMobile.app",
        newCommandTimeout:300,
        deviceName: 'iPhone 6',
        deviceReadyTimeout: 1800000,

};`
## Link to Appium logs

https://gist.github.com/mn8/b01381fbbcca5072a1b0892a4b72ffa3

**Comment by imurchie** [comment]
Is the app downloaded, as it looks from the location? Or did you compile it locally?

**Comment by mn8** [comment]
I have complied it locally, as well as gotten it from a jenkins build that compiles the code. I take the ipa file extract it, than grab the .app inside of it.

**Comment by mykola-mokhnach** [comment]
Have you tried to run this command manually?

```bash
/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D ~/Desktop/instrumentscli0.trace -w "iPhone 6 (9.3) [" /Users/patrick.coady/Downloads/Payload/KronosMobile.app -e UIASCRIPT "/Users/patrick.coady/Library/Application Support/appium/bootstrap/bootstrap-ee0aa0f77dbbdc27.js" -e UIARESULTSPATH /var/folders/79/vy2h0tcx521gv901byk994mcx7gr_0/T/appium-instruments
```

What is the output?

Also, I'd like to see the output of 

```bash
instruments -s
```

**Comment by mn8** [comment]
instruments -s 

US-C02MV0FMFRG2 [56FFE1B6-AA37-5093-8A59-20BDF3A66243]
Apple TV 1080p (9.2) [DCECBCC5-4692-4AB5-9EF2-66128307A5CD] (Simulator)
Apple Watch - 38mm (2.2) [FBC7C724-C1CC-49D1-9784-AC2DABD2CA75] (Simulator)
Apple Watch - 42mm (2.2) [C2CB6412-438B-4695-9496-227C402F2197] (Simulator)
iPad 2 (9.2) [68B6698C-61FD-414F-B4BB-71B39B7C0DA7] (Simulator)
iPad Air (9.2) [B48463F8-BFA3-4A94-89D9-E8F042305477] (Simulator)
iPad Air (9.3) [B43E2B1D-AFEF-40C1-8E48-71259F9DC793] (Simulator)
iPad Air 2 (9.2) [D00B1C34-DBC2-4B86-B868-D8D09C7F8004] (Simulator)
iPad Pro (9.2) [5A870018-463D-4ABF-B599-BCDE0310E692] (Simulator)
iPad Retina (9.2) [4CF26A73-4A1C-425C-9AFE-399FDACC2871] (Simulator)
iPhone 4s (9.2) [CDD562A6-2E52-4A02-A426-E1C157D1692E] (Simulator)
iPhone 5 (9.2) [E3E4C217-7551-46CF-8AFC-B003F75EABCC] (Simulator)
iPhone 5s (9.2) [3398F219-7D1B-4869-90C7-94441C98DFAA] (Simulator)
iPhone 6 (9.2) [2D994748-3696-40E2-ADB9-842DB9413EF6] (Simulator)
iPhone 6 (9.3) [87D75FAB-5DD2-4E7E-82A9-A0E4BD783D62] (Simulator)
iPhone 6 Plus (9.2) [55C5B572-5753-4C4B-B4A9-42B9E26BB45F] (Simulator)
iPhone 6s (9.2) [41E54680-4146-4F14-B64F-58C4195E09EA] (Simulator)
iPhone 6s Plus (9.2) [3945EF0C-11BB-4BBD-A2F4-B75F3A9AB433] (Simulator)
iPhone5 (9.3) [00CA870B-D89F-4927-9E3A-346B472CDD3C] (Simulator)
Known Templates:
"Activity Monitor"
"Allocations"
"Automation"
"Blank"
"Cocoa Layout"
"Core Animation"
"Core Data"
"Counters"
"Energy Log"
"File Activity"
"GPU Driver"
"Leaks"
"Metal System Trace"
"Network"
"OpenGL ES Analysis"
"System Trace"
"System Usage"
"Time Profiler"
"Zombies"


The other commands just hangs there indefinitely.

**Comment by mykola-mokhnach** [comment]
Most likely, there is a problem with your system setup if instruments freezes after execution.
Did you try to test the same app, but on the other Mac?

**Comment by imurchie** [comment]
When building don't create an ipa. Just create a simulator build in debug mode, which should produce a .app file, which will be runnable.

**Comment by mn8** [comment]
Still not working. I built debut iPhone 6s simulator, and the .app works fine on the simulator manually but appium is still not launching it. I'm getting the same logs.
