### ISSUE TITLE
Not able to identify the XPATH for the elements: Checkbox/RadioButton as those are hidden from Appium Inspector

### ISSUE THREAD

**Issue by rameshshriram** [appium/appium#6744]
## Not able to identify the XPATH for the elements: Checkbox/RadioButton as those are hidden from Appium Inspector

We are automating the iPad hybrid application, but not able to identify the XPATH for the elements: Checkbox/RadioButton as those are hidden from Appium Inspector. And without XPATH fo those elements, we can't able to perform the operations on those elements: Checkbox/Radiobuttons. 
Please help me on this.
## Environment

* Appium version (or git revision) that exhibits the issue: Appium version is 1.4.13
* Last Appium version that did not exhibit the issue (if applicable): We tried with latest version # 1.5.3 also. But the issue still persist.
* Desktop OS/version used to run Appium: MAC 10.11.5
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPad 9.1(13B143)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

**Comment by shreyaskd** [comment]
I face similar issue too

**Comment by saikrishna321** [comment]
@rameshshriram this issue is something to do with appium inspector not appium as server, can you raise the issue here (https://github.com/appium/appium-dot-app)

@SrinivasanTarget can we close this

**Comment by SrinivasanTarget** [comment]
yup @saikrishna321

**Comment by SrinivasanTarget** [comment]
@triager please close
