### ISSUE TITLE
xcuitest driver doesn't support downloading apps via a url

### ISSUE THREAD

**Issue by jlipps** [appium/appium#6748]
It barfs on e.g. `https://appium.s3.amazonaws.com/TestApp7.1.app.zip`

**Comment by yaphatak** [comment]
@jlipps That is true and also if someone passes undefined/ null to app it doesn't work either.
I can send PR soon to do installation app part. I already have it working locally. I just need to put together PR. I think we should keep it outside WDA

**Comment by jlipps** [comment]
@yaphatak great, glad you told me. I was about to work on it, but I'll let you do it :-) definitely should be outside of WDA, we can just import and use the code from basedriver.

undefined/null should not work right? Are you saying we don't throw a decent error?

**Comment by yaphatak** [comment]
> undefined/null should not work right? Are you saying we don't throw a decent error?
I think I was not clear. Lets say user sends only bundleid and dont send `app` and `fullReset` is `false`. Then we should not throw exception as `bundleid` is more than enough to run test. But today if we just pass `null` value for `app` and valid `bundleid` then it still throws exception from WDA and test fails.

**Comment by imurchie** [comment]
Related issue: https://github.com/appium/appium-xcuitest-driver/issues/37
