### ISSUE TITLE
simplify windows documentation

### ISSUE THREAD

**Issue by jlipps** [appium/appium#6751]
Now that java is not a pre-requisite for installing appium on windows (for winappdriver), we can update the docs to not mention java/jar/etc for the WinAppDriver portion

**Comment by yodurr** [comment]
is the JDK requirement now gone completely or still required for Android app testing?

**Comment by jlipps** [comment]
Still required for Android!

**Comment by yodurr** [comment]
:)

**Comment by yodurr** [comment]
Thank you!
