### ISSUE TITLE
Unable to run first appium test

### ISSUE THREAD

**Issue by vpkhachane** [appium/appium#6754]
## The problem

I am trying to run basic appium test that launch apk into device. but i am getting errors. And i am confused how to run appium test into Android studio.
Here I have attached screenshots.
Please help me 

## Environment

* Appium version (or git revision) that exhibits the issue:Appium v1.4.16
* Last Appium version that did not exhibit the issue (if applicable):NA
* Desktop OS/version used to run Appium: Windows 10 64 bit
* Node.js version (unless using Appium.app|exe):v4.4.7
* Mobile platform/version under test: Android 5.1 
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.exe
![screenshot_1](https://cloud.githubusercontent.com/assets/15686482/17844326/0ae27ae2-6856-11e6-9771-5942082a4ecf.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/15686482/17844324/0ae09394-6856-11e6-9745-7bda0e195b0b.jpg)
![screenshot_3](https://cloud.githubusercontent.com/assets/15686482/17844325/0ae1ec30-6856-11e6-8355-1406a1a8112e.jpg)

**Comment by saikrishna321** [comment]
@vpkhachane did u start the appium server ?

**Comment by vpkhachane** [comment]
Thank you for quick response.
How can i start appium server
I have followed following step:
1)Starting appium.exe , In that i have given application path and I have set server address is my ip address ex 192.168.0.114 and port is 4723.
2)Start eclipse and run program with TestNG and getting following erros
Error Log
[TestNG] Running:
C:\Users\prabu\AppData\Local\Temp\testng-eclipse--1847523077\testng-customsuite.xml

[Utils] Attempting to create C:\AndroidDemoworkspace\StartAppium\test-output\Default suite\Default test.xml
[Utils] Directory C:\AndroidDemoworkspace\StartAppium\test-output\Default suite exists: true
FAILED: start
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: 'unknown', revision: '2aa21c1', time: '2016-08-02 14:59:43 -0700'
System info: host: 'Vaibhav-PC', ip: '192.168.0.114', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:670)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:247)
at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:130)
at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:157)
at demo.StartAppium.start(StartAppium.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:646).....

**Comment by saikrishna321** [comment]
@vpkhachane can u pls post the server logs ?

**Comment by vpkhachane** [comment]
Hello,

My Source code is:-

package demo;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Driver;

import org.openqa.selenium.Capabilities;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.Test;

public class StartAppium {
/**
* @param args
*/

static WebDriver driver;
@Test
public static void start() throws Exception{

// DesiredCapabilities capability=new DesiredCapabilities();
// capability.setCapability("device","Android");
// capability.setCapability(CapabilityType.VERSION,"5.1");
// capability.setCapability(CapabilityType.PLATFORM,"WINDOWS");
// capability.setCapability("deviceName","Moto E(2nd Generation)");
// capability.setCapability("PlatformName","Android");
// capability.setCapability("PlatformName","Android");
// capability.setCapability("app", "C:\AndroidDemoworkspace\MyAppiumProject\apk\WhatsApp.apk");
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("automationName", "Appium");
capabilities.setCapability("appium-version", "1.0");
capabilities.setCapability("platformName", "Android");
capabilities.setCapability("platformVersion", 5.1);
capabilities.setCapability("deviceName","Moto E(2nd Generation)");
capabilities.setCapability("app","C:\AndroidDemoworkspace\MyAppiumProject\apk\WhatsApp.apk");

    //driver = new RemoteWebDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
    driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);

}

}

I have getting following error messages.

[TestNG] Running:
C:\Users\prabu\AppData\Local\Temp\testng-eclipse-736829451\testng-customsuite.xml

[Utils] Attempting to create C:\AndroidDemoworkspace\StartAppium\test-output\Default suite\Default test.xml
[Utils] Directory C:\AndroidDemoworkspace\StartAppium\test-output\Default suite exists: true
PASSED: start

===============================================
Default test
Tests run: 1, Failures: 0, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.jq.Main@1b0375b3: 46 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 0 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@48140564: 6 ms
[Utils] Attempting to create C:\AndroidDemoworkspace\StartAppium\test-output\junitreports\TEST-demo.StartAppium.xml
[Utils] Directory C:\AndroidDemoworkspace\StartAppium\test-output\junitreports exists: true
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@3b6eb2ec: 3 ms
[Utils] Attempting to create C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite\toc.html
[Utils] Directory C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite\Default test.properties
[Utils] Directory C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite\index.html
[Utils] Directory C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite\main.html
[Utils] Directory C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite\groups.html
[Utils] Directory C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite\classes.html
[Utils] Directory C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite\reporter-output.html
[Utils] Directory C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite\methods-not-run.html
[Utils] Directory C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite\testng.xml.html
[Utils] Directory C:\AndroidDemoworkspace\StartAppium\test-output\old\Default suite exists: true
[Utils] Attempting to create C:\AndroidDemoworkspace\StartAppium\test-output\old\index.html
[Utils] Directory C:\AndroidDemoworkspace\StartAppium\test-output\old exists: true
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@1134affc: 17 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@3ac3fd8b: 2 ms

**Comment by mykola-mokhnach** [comment]
> driver = new AndroidDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
Why 0.0.0.0? Use the address of a machine, where Appium server is started or just _localhost_ if it is running on the same machine, where you run your tests. 
You can use _telnet_ Windows cmdline utility to make sure that Appium server is running and listening on the particular port:

```
telnet 192.168.0.114 4723
```

**Comment by saikrishna321** [comment]
@vpkhachane this is client side error. can u post the server side logs( when u run run from appium.exe). Can you raise this over discuss.appium.io

@SrinivasanTarget this can be closed, looks more like a discuss not issue.

**Comment by vpkhachane** [comment]
@mykola-mokhnach :- I have Added System IP address still it gives same error

@saikrishna321 :- Following are log of appium.exe
Launching Appium server with command: C:\Appium\node.exe lib\server\main.js --address 192.168.0.114 --port 4723 --app C:\Users\prabu\Desktop\WhatsApp.apk --avd Custom Tablet - 6.0.0 - API 23 - 2560x1600 --platform-name Android --platform-version 21 --automation-name Appium --log-no-color
> usage: main.js [-h] [-v] [--shell]
> main.js: error: Unrecognized arguments: Tablet - 6.0.0 - API 23 - 2560x1600.
> 
>                [--localizable-strings-dir LOCALIZABLESTRINGSDIR] [--app APP]
>                [--ipa IPA] [-U UDID] [-a ADDRESS] [-p PORT]
>                [-ca CALLBACKADDRESS] [-cp CALLBACKPORT] [-bp BOOTSTRAPPORT]
>                [-k] [-r BACKENDRETRIES] [--session-override] [--full-reset]
>                [--no-reset] [-l] [-lt LAUNCHTIMEOUT] [-g LOG]
>                [--log-level {info,info:debug,info:info,info:warn,info:error,warn,warn:debug,warn:info,warn:warn,warn:error,error,error:debug,error:info,error:warn,error:error,debug,debug:debug,debug:info,debug:warn,debug:error}]
>                [--log-timestamp] [--local-timezone] [--log-no-colors]
>                [-G WEBHOOK] [--native-instruments-lib]
>                [--app-pkg ANDROIDPACKAGE] [--app-activity ANDROIDACTIVITY]
>                [--app-wait-package ANDROIDWAITPACKAGE]
>                [--app-wait-activity ANDROIDWAITACTIVITY]
>                [--android-coverage ANDROIDCOVERAGE] [--avd AVD]
>                [--avd-args AVDARGS]
>                [--device-ready-timeout ANDROIDDEVICEREADYTIMEOUT] [--safari]
>                [--device-name DEVICENAME] [--platform-name PLATFORMNAME]
>                [--platform-version PLATFORMVERSION]
>                [--automation-name AUTOMATIONNAME] [--browser-name BROWSERNAME]
>                [--default-device] [--force-iphone] [--force-ipad]
>                [--language LANGUAGE] [--locale LOCALE]
>                [--calendar-format CALENDARFORMAT] [--orientation ORIENTATION]
>                [--tracetemplate AUTOMATIONTRACETEMPLATEPATH]
>                [--instruments INSTRUMENTSPATH] [--show-sim-log]
>                [--show-ios-log] [--nodeconfig NODECONFIG] [-ra ROBOTADDRESS]
>                [-rp ROBOTPORT] [--selendroid-port SELENDROIDPORT]
>                [--chromedriver-port CHROMEDRIVERPORT]
>                [--chromedriver-executable CHROMEDRIVEREXECUTABLE]
>                [--use-keystore] [--keystore-path KEYSTOREPATH]
>                [--keystore-password KEYSTOREPASSWORD] [--key-alias KEYALIAS]
>                [--key-password KEYPASSWORD] [--show-config] [--no-perms-check]
>                [--command-timeout DEFAULTCOMMANDTIMEOUT] [--keep-keychains]
>                [--strict-caps] [--isolate-sim-device] [--tmp TMPDIR]
>                [--trace-dir TRACEDIR] [--intent-action INTENTACTION]
>                [--intent-category INTENTCATEGORY] [--intent-flags INTENTFLAGS]
>                [--intent-args OPTIONALINTENTARGUMENTS]
>                [--dont-stop-app-on-reset] [--debug-log-spacing]
>                [--suppress-adb-kill-server] [--async-trace]
>                
> 
> Appium server process ended

**Comment by mykola-mokhnach** [comment]
@vpkhachane Make sure the emulator named "Custom Tablet - 6.0.0 - API 23 - 2560x1600" really exists in your system. 
In case you want to execute the test on a real device then do not provide _--avd_ parameter at all. Also, you can just pass _null_ as _deviceName_ capability value to pick up the first available real Android device connected to your PC or its serial number, which is visible in 

```
adb devices -l
```

output.

**Comment by SrinivasanTarget** [comment]
@vpkhachane I suggest you to check these projects for sample tests: https://github.com/appium/sample-code & https://github.com/appium/java-client/tree/master/src/test/java/io/appium/java_client. Also we have a good Wiki here: https://github.com/appium/java-client/wiki. Raise this in discuss.appium.io.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by vpkhachane** [comment]
@mykola-mokhnach : I am using real device. let me know to where change required
DesiredCapabilities capabilities = new DesiredCapabilities();
	    capabilities.setCapability("automationName", "Appium");
	    capabilities.setCapability("appium-version", "1.0");
	    capabilities.setCapability("platformName", "Android");
	    capabilities.setCapability("platformVersion", 5.1);
	    capabilities.setCapability("deviceName","Moto E(2nd Generation)");
	    capabilities.setCapability("app","C:\\AndroidDemoworkspace\\MyAppiumProject\\apk\\WhatsApp.apk");
	    
	    //driver = new RemoteWebDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
		driver = new AndroidDriver(new URL("http://192.168.0.114:4723/wd/hub"), capabilities);

**Comment by vpkhachane** [comment]
Appium working fine now... Actually i have made few mistakes like adding wrong jar files, environment variables wrong.. Thanks everyone to reply me. But i want to explore it more . suggest me demo examples
