### ISSUE TITLE
[iOS] Application crashes on device when VoiceOver is off and Appium tries to get Tree for XML

### ISSUE THREAD

**Issue by zxcq99** [appium/appium#6756]
## The problem

Application crashes on device when VoiceOver is off and Appium tries to get Tree for XML. If VoiceOver is on it works just fine. Works fine on simulator as well.
## Environment
- Appium version (or git revision) that exhibits the issue: Appium 1.5.3 (git 2.7.4)
- Last Appium version that did not exhibit the issue (if applicable): -
- Desktop OS/version used to run Appium: OS X El Capitan 10.11.6
- Node.js version (unless using Appium.app|exe): -
- Mobile platform/version under test: iOS 9.2
- Real device or emulator/simulator: All real devices
- Appium CLI or Appium.app|exe: -
## 
## Link to Appium logs

[gist](https://gist.github.com/zxcq99/fde063a1b67b3250bb737ffaecdc61c5)
##

**Comment by dpgraham** [comment]
Closing this. Instruments no longer supported.
