### ISSUE TITLE
Error While launching appium browser:- org.openqa.selenium.WebDriverException: ERROR running Appium command: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by Naren-Neal** [appium/appium#6761]
hello all i am new to appium while launching a chrome browser in real device , i found following issue ,please help ............................Console and appium logs attached 

![test1](https://cloud.githubusercontent.com/assets/21190425/17892111/896a8082-68f4-11e6-8749-88379852c410.png)
![appium logs](https://cloud.githubusercontent.com/assets/21190425/17892139/a130f110-68f4-11e6-9764-9904841e91ee.png)
Please help stuck with this issue from last 3 weeks

**Comment by mykola-mokhnach** [comment]
Please check the tutorial carefully, your capabilities seems to have wrong values:
http://appium.io/slate/en/master/?java#mobile-chrome-on-emulator-or-real-device

Also, this is not a bug report - please forward the question to Appium discussions.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by Naren-Neal** [comment]
Any update ???
