### ISSUE TITLE
Investigate adding touch action support to `appium-xcuitest-driver`.

### ISSUE THREAD

**Issue by imurchie** [appium/appium#6762]
Add touch action support to `appium-xcuitest-driver`.

Might just be importing the right things from ios-driver, and tweaking to not use UI Automation.

Acceptance criteria:
* [ ] Document of what currently _does_ work
* [ ] List of what we can expect to _make_ work given the current state of WDA + XCUITest
* [ ] List of what we currently think is impossible
* [ ] Radars filed (Radar + OpenRadar + Worms) for things Apple should fix

**Comment by cesarca** [comment]
Is it possible to make a long press currently in Appium 1.6?

**Comment by hardik-d** [comment]
this would be the most desired feature, most of my tests rely on touchaction

**Comment by VivekParolia** [comment]
Is it possible to support 2 finger touch?

**Comment by Prasant-Sutaria** [comment]
We are using Appium 1.6.3 on SauceLabs and other providers. We are not able to do long press on an element. Its very important for our testing.

**Comment by Prasant-Sutaria** [comment]
@imurchie , Sorry I was not able to create gist. I have attach the log file. 

Code used:

TouchAction action = new TouchAction(driver);
action.longPress(elem).release().perform();

Exception:

org.openqa.selenium.WebDriverException: Support for this gesture is not yet implemented. Please contact an Appium dev (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 548 milliseconds

[TestObject_Appium_iPhone_SE_16GB_POC27_31-03-2017_10-40-50.txt](https://github.com/appium/appium/files/886291/TestObject_Appium_iPhone_SE_16GB_POC27_31-03-2017_10-40-50.txt)

**Comment by hardik-d** [comment]
@imurchie it works in android and not in ios. This has been broken since 1.6. I had to change my test code to press instead of long_press. @Prasant-Sutaria have you tried regular press?

**Comment by mykola-mokhnach** [comment]
@hardik-d long press action in iOS can be achieved by providing either single _longpress_ or _press-wait-release_ action chains. Appium 1.6.4-beta is expected to be installed.

**Comment by hardik-d** [comment]
i know how long_press works, maybe i missed it on 1.6.4beta release page that it is now supported! will try it out. Thanks!

**Comment by mykola-mokhnach** [comment]
This is the list of action chains supported by XCTest:

```javascript
const supportedGesturesMapping = {
    doubleTap: {
      handler: async (x) => {await this.handleDoubleTap(x);},
      matches: [
        [{action: 'doubletap'}],
        [{action: 'tap', options: {count: 2}}]
      ]
    },
    tap: {
      handler: async (x) => {await this.handleTap(x[0]);},
      matches: [
        [{action: 'tap'}],
        [{action: 'tap'}, {action: 'release'}],
        [{action: 'press'}, {action: 'release'}]
      ]
    },
    longPress: {
      handler: async (x) => {await this.handleLongPress(x);},
      matches: [
        [{action: 'longpress'}],
        [{action: 'press'}, {action: 'wait'}, {action: 'release'}]
      ]
    },
    drag: {
      handler: async (x) => {await this.handleDrag(x);},
      matches: [
        [{action: 'press'}, {action: 'wait'}, {action: 'moveTo'}, {action: 'release'}]
      ]
    },
    scroll: {
      handler: async (x) => {await this.handleScroll(x);},
      matches: [
        [{action: 'press'}, {action: 'moveTo'}, {action: 'release'}]
      ]
    }
  };
```

Also these mobile gestures are available:
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md

**Comment by mykola-mokhnach** [comment]
and multitouch only supports pinch/zoom, which contains of two _press-moveTo-release_ chains

**Comment by hardik-d** [comment]
@mykola-mokhnach i get below error:

     Selenium::WebDriver::Error::UnknownError:
       Support for this gesture is not yet implemented. Please contact an Appium dev

for this code:

Appium::TouchAction.new.long_press(x: 100, y: 200).move_to(x: 100, y: -200).release.perform

**Comment by mykola-mokhnach** [comment]
Only action chains mentioned above are supported.

**Comment by hardik-d** [comment]
not following @mykola-mokhnach how is press.move_to.release working then? does it mean it matches scroll? can i do press.move_to.press.move_to? (guess not)

**Comment by mykola-mokhnach** [comment]
yep, you are right.

**Comment by hardik-d** [comment]
thanks

**Comment by jlipps** [comment]
I'm going to close this since the implementation of the various "mobile:" commands are now (sadly) the preferred way of performing actions for ios.

**Comment by oscheller1** [comment]
Is there a comprehensive overview about which parameters are possible using "mobile" commands? E.g. 1) I'd like to know if it's possible to use `"mobile:scroll", {"element": el, "direction":"down"}` in conjunction with some other parameters, for example how far to scroll, instead of the standard range. 2) Which other "mobile" commands beside `scroll` are possible?

Besides that, for anyone reading, I found the `driver.swipe` function to offer reliable customized scrolling, which is translated to a TouchAction:
```
        action = TouchAction(self)
        action \
            .press(x=start_x, y=start_y) \
            .wait(ms=duration) \
            .move_to(x=offset_x, y=offset_y) \
            .release()
        action.perform()
```

**Comment by mykola-mokhnach** [comment]
We only have https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md

You are welcome to extend it if you want
