### ISSUE TITLE
fullReset option does not work

### ISSUE THREAD

**Issue by puzlpix** [appium/appium#6766]
Testing with fullReset=True and noReset=True is not working as expected.
I've got two test methods in a test where:
 test_01 signs-in a user
 test_02 runs with user signed in
Any time the test is rerun, a user is already signed-in before test_01 runs, but should not be.
It only seems to work by manually resetting simulator content and settings and running the test the first time.

Appium server: Version 1.5.3 (Ara)
Appium client: Version 0.22 Appium-Python-Client for Appium 1.5
Xcode: Version 7.3.1
Simulator: iPhone 5 iOS 9.2

https://gist.github.com/puzlpix/684692991278669168569b1629378af9

**Comment by imurchie** [comment]
Why are you setting _both_ `noReset` and `fullReset`? If memory serves, `noReset` takes precedence and no reset will be done, no matter what else is on.

**Comment by puzlpix** [comment]
I'd like to test sign-up/sign-in with test_01 and continue to test_02 from the signed-up/signed-in app state. I tried with fullReset=true and not setting noReset and both tests reinstall the app.

**Comment by mykola-mokhnach** [comment]
_fullReset_ option won't help in such case. Execute this command before you run you the first test to reset the device if you are on simulator:

```bash
xcrun simctl erase <simulator_id>
```

Make sure the simulator is not running while starting the command.
Or use the following command  to uninstall leftovers of your app from a real device

```bash
/usr/local/bin/ideviceinstaller -u  <device_udid> -U <application_bundle_id>
```

**Comment by chenchaoyi** [comment]
I think you want a fullReset before running all tests, and between each test, you want noReset.

**Comment by puzlpix** [comment]
I tried conditionally configuring a WebDriver between tests in setUp:
`      if fullReset:
        print("doing full reset")
        capabilities['fullReset'] = True
        capabilities['noReset'] = False
        fullReset = False
      else:
        print("not doing full reset")
        capabilities['fullReset'] = False
        capabilities['noReset'] = True`

But simulator still resets for each test.

**Comment by imurchie** [comment]
Reset has been rewritten. Closing.
