### ISSUE TITLE
Visible element is not tappable

### ISSUE THREAD

**Issue by puzlpix** [appium/appium#6767]
Attempting to tap a button that is visible onscreen throws exception:
WebDriverException: Message: UIAButton could not be tapped because the element is not visible

The button and another 9 visible elements on screen are also visible=false in the Inspector.

Appium server: Version 1.5.3 (Ara)
Appium client: Version 0.22 Appium-Python-Client for Appium 1.5
Xcode: Version 7.3.1
Simulator: iPhone 5 iOS 9.2

https://gist.github.com/puzlpix/e32aa758054a6413ee2f6e22fcf6cdd7

Sample code:
`
    def test_0002_tapProgramDetailsButton(self):
      tap_action = TouchAction(self.driver)
      try:
        button = self.driver.find_element_by_accessibility_id('Program Details')
        self.assertIsNotNone(button, "Program Details button not found")
        tap_action.tap(button).perform()
      except Exception:
        print("error tapping Program Details")
`

**Comment by mykola-mokhnach** [comment]
It might be possible if these buttons are covered by some invisible transparent layer. As a workaround, you may just find out button coordinates from the xml tree (check __get_page_source()__ call) and then perform generic click by coordinates.

**Comment by dpgraham** [comment]
Closing this. Instruments no longer supported.
