### ISSUE TITLE
appium cannot be installed via Ansible, Salt or Shell script

### ISSUE THREAD

**Issue by shane51** [appium/appium#6768]
## The problem

Recently, I'm trying to use Ansible, SaltStack + Vagrant to setup appium dev env.  When using ansible or Salt to do  `npm install`, appium always return error, however, appium was successfully installed already. 
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3  with npm install
- Last Appium version that did not exhibit the issue (if applicable): null
- Desktop OS/version used to run Appium: unbuntu 14.04 ( vagrant box: ubuntu/trusty64)
- Node.js version (unless using Appium.app|exe):  v6.4.0
- Mobile platform/version under test: null
- Real device or emulator/simulator: null
- Appium CLI or Appium.app|exe: null
#### error with ansible npm install:

```
fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/npm install --global appium", "failed": true, "msg": "", "rc": 1, "stderr": "\n\n", "stdout": "/usr/bin/appium -> /usr/lib/node_modules/appium/build/lib/main.js\n/usr/bin/authorize-ios -> /usr/lib/node_modules/appium/node_modules/.bin/authorize-ios\n\n> appium-chromedriver@2.9.2 install /usr/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver\n> node install-npm.js\n\n", "stdout_lines": ["/usr/bin/appium -> /usr/lib/node_modules/appium/build/lib/main.js", "/usr/bin/authorize-ios -> /usr/lib/node_modules/appium/node_modules/.bin/authorize-ios", "", "> appium-chromedriver@2.9.2 install /usr/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver", "> node install-npm.js", ""]}
```
#### error with Salt npm install:

```
[INFO    ] Running state [oracle-java8-installer] at time 08:54:41.575894
[INFO    ] Executing state pkg.installed for oracle-java8-installer
[INFO    ] Package oracle-java8-installer is already installed
[INFO    ] Completed state [oracle-java8-installer] at time 08:54:41.579994 duration_in_ms=4.1
[INFO    ] Running state [appium] at time 08:54:41.582858
[INFO    ] Executing state npm.installed for appium
[INFO    ] Executing command 'npm list --silent --json --global' in directory '/root'
[INFO    ] Executing command 'npm install --silent --json  --global appium' in directory '/root'
[ERROR   ] Command 'npm install --silent --json  --global appium' failed with return code: 1
[ERROR   ] stdout: /usr/bin/appium -> /usr/lib/node_modules/appium/build/lib/main.js
/usr/bin/authorize-ios -> /usr/lib/node_modules/appium/node_modules/.bin/authorize-ios
[ERROR   ] retcode: 1
[ERROR   ] Error installing 'appium': 
[INFO    ] Completed state [appium] at time 08:57:01.074710 duration_in_ms=139491.852
```

**We debugged ansible and found appium returns code 1 after installed successfully**
## Code To Reproduce Issue [ Good To Have ]

We found another simple way to reproduce:
#### pre-requisite:

Ensure appium is **NOT** installed or uninstalled 
OS: ubuntu
#### Steps to reproduce

1 Create a shell script:

``` shell
# test_appium_exit_code_1.sh
sudo npm install -g appium
```

2 Change mode to +x to run shell

``` shell
chmod +x test_appium_exit_code_1.sh
```

3 run:

``` shell
./test_appium_exit_code_1.sh
```

4 Will see stdout as below:

```
/usr/bin/authorize-ios -> /usr/lib/node_modules/appium/node_modules/.bin/authorize-ios
/usr/bin/appium -> /usr/lib/node_modules/appium/build/lib/main.js

> appium-chromedriver@2.9.2 install /usr/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver
> node install-npm.js
```

and installation process exit.
#### Actual result:

**When check the return code as below, we will get `1`**

```
echo $?
```

Since Ansible or Salt use script to run appium, so they will get code `1` from appium, which breaks Ansible or Salt process
#### Expected result:

Run Appium install with script should return code `0`

**Comment by mykola-mokhnach** [comment]
Are you trying to install Appium on a clean machine or it is already present there?

**Comment by shane51** [comment]
Clean machine, I used Vagrant to create a clean ubuntu, and I got this issue. 

if I cannot reproduce with the steps, I can provide my Vagrantfile and Ansible script, then you can debug it

**Comment by mykola-mokhnach** [comment]
You could change the command to
```bash 
npm install -g appium || true
```

if you want to workaround the issue. But I cannot understand why do you need sudo to execute npm installer? In theory it should work without root privileges and should create executable symlinks in __/usr/local/bin__ folder, which does not require elevated permissions for writing.

**Comment by shane51** [comment]
Yes, I should not use sudo for npm install.

The workaround works! thank you :)

 Still confused why install appium via script will give exit code 1?
It's weird that when I try to trace the npm process during the installation, the installation will succeed with exit code 0.
