### ISSUE TITLE
Document and test the '-ios predicate string' locator strategy in xcuitest-driver

### ISSUE THREAD

**Issue by imurchie** [appium/appium#6777]
The locator strategy exists. Need to test it, and document how it works (and how things that were done with 'ios uiautomation' strategy can be done).

**Comment by dpgraham** [comment]
Sample WebDriverAgent source https://gist.github.com/dpgraham/63a97e960dc3e16b68084428b877be9e

For some reason, the predicate 'isVisible=1' will return nothing but 'isWDVisible=1' will return all visible elements. Need to understand where the 'WD' comes from.

**Comment by mykola-mokhnach** [comment]
@dpgraham I suppose it comes from https://github.com/facebook/WebDriverAgent/blob/b2e1c07d1028b696708b64b130292770b72e8052/WebDriverAgentLib/Routing/FBElement.h

**Comment by dpgraham** [comment]
Thanks @mykola-mokhnach. That FBElement.h file clears things up quite a bit. I do think we'll need to document this further though.

**Comment by mykola-mokhnach** [comment]
@dpgraham I've recently created a PR for WDA, that should clean up things a bit, but dunno when (or 'if') it is going to be merged: https://github.com/facebook/WebDriverAgent/pull/379
