### ISSUE TITLE
Make sure that 'appium' endpoints work in xcuitest-driver

### ISSUE THREAD

**Issue by imurchie** [appium/appium#6778]
At least all that are reasonable. This is an umbrella for probably a number of problems that will come up.

**Comment by jlipps** [comment]
@imurchie can we add a list to this issue to track? I think you've actually done a number of these already, right?

**Comment by yaphatak** [comment]
I opened this with `FB/WDA` [here](https://github.com/facebook/WebDriverAgent/issues/284). 
So `FB` is open to add `appium` endpoint as extension. I think most of things we are missing are `gesture` like endpoints? @imurchie do we have such list somewhere? I can try to take few. I am swamped with internal work now (but it never ends :)). I will see what I can do

**Comment by imurchie** [comment]
This was the original catchall. There are individual tickets, most complete, for the actual endpoint. I'm closing this one.
