### ISSUE TITLE
Android Nougat Support

### ISSUE THREAD

**Issue by imurchie** [appium/appium#6779]
We need to investigate Android Nougat support. There have been reports of failures.

https://github.com/appium/appium/issues/6776
https://github.com/appium/appium/issues/6665

**Comment by jlipps** [comment]
If #6665 is fixed, will this resolve the issue entirely?

**Comment by Pitel** [comment]
Also #6850

**Comment by jlipps** [comment]
I haven't heard about new problems for Nougat, so calling this done.
