### ISSUE TITLE
Error: Command failed: /bin/sh -c ideviceinstaller 

### ISSUE THREAD

**Issue by ruchikar** [appium/appium#6781]
## The problem
Appium inspector fail to run on iOS (simulator + real device). Works fine for Android.
Throws error: Error: Command failed: /bin/sh -c ideviceinstaller 

I have already installed ideviceinstaller

## Environment

* Appium version 1.4.13
* Desktop OS/version used to run Appium: OSX 10.11.5 
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: Appium.app

## Details

Am trying to launch inspector for iOS, whenevr I do that am facing issues

## Link to Appium logs

error: Failed to start an Appium session, err was: Error: Command failed: /bin/sh -c ideviceinstaller -u 9603A2D4-DEC0-4E28-AD29-0FCB894D54F7 -i /Users/Ruchika/Downloads/Staging.app

info: [debug] Creating iDevice object with udid 9603A2D4-DEC0-4E28-AD29-0FCB894D54F7
info: [debug] App is not installed. Will try to install the app.
info: [debug] Cleaning up appium session
info: [debug] Error: Command failed: /bin/sh -c ideviceinstaller -u 9603A2D4-DEC0-4E28-AD29-0FCB894D54F7 -i /Users/Ruchika/Downloads/Staging.app

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: /bin/sh -c ideviceinstaller -u 9603A2D4-DEC0-4E28-AD29-0FCB894D54F7 -i /Users/Ruchika/Downloads/Staging.app\n)","killed":false,"code":2,"signal":null,"cmd":"/bin/sh -c ideviceinstaller -u 9603A2D4-DEC0-4E28-AD29-0FCB894D54F7 -i /Users/Ruchika/Downloads/Staging.app","origValue":"Command failed: /bin/sh -c ideviceinstaller -u 9603A2D4-DEC0-4E28-AD29-0FCB894D54F7 -i /Users/Ruchika/Downloads/Staging.app\n"},"sessionId":null}
info: <-- POST /wd/hub/session 500 61.606 ms - 526 

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Which output do you see if you execute the same command from terminal?

```bash
/bin/sh -c ideviceinstaller
```

Check which interpreter is set as the default one:

```bash
/bin/sh -version
```

In case this is Bash make sure the path to the folder where ideviceinstaller is installed is present in PATH environment variable.

**Comment by ruchikar** [comment]
It got resolved, Was trying to run on simulator and was passing UDID as well.
So, solution is when you want to run on simulator, disable or remove UDID check

**Comment by SrinivasanTarget** [comment]
@triager please close
