### ISSUE TITLE
Requires fingerprint supporting

### ISSUE THREAD

**Issue by ken-jiang** [appium/appium#6782]
## The problem

We have automation test case that requires fingerprint operations, but appium and its java_client are not supporting this feature.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS X EI Capitan (Version 10.11.6)
* Node.js version (unless using Appium.app|exe): v5.10.1
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Android emulator 25.1.7
* Appium CLI or Appium.app|exe: Appium 1.5.3

## Details

Now Android emulator supports inputting the fingerprint via command as below:
adb -s <emulator-ID> emu finger touch <fingerprint ID>
This command can be used by Appium to input <fingerprint ID> for Android testing.

**Comment by SrinivasanTarget** [comment]
@triager please close
