### ISSUE TITLE
Unable to work with appium inspector on mac machine with real device

### ISSUE THREAD

**Issue by 007nilesh007** [appium/appium#6784]
I am trying to invoke appium inspector with ream iPhone device , but getting an exception as "Failed to start instrument daemon on iphone123" in appium logs

**Comment by mykola-mokhnach** [comment]
Not enough info to assume anything. Please fill out carefully the initial template for bug reporting.

Usually, with real device it is necessary to make sure the device has UI Automation mode enabled in Settings, the device UUID is added to the development profile, the application under test is signed with this development profile (not enterprise) and is built in debug mode.

**Comment by SrinivasanTarget** [comment]
@triager please close
