### ISSUE TITLE
iOS 10 Simulator not running using appium 1.6.0 beta 1 XCode 8 beta 6

### ISSUE THREAD

**Issue by codehunterridoy** [appium/appium#6786]
## The problem

I am trying to run my ios app (.app) in iOS 10 simulator. but after running appium via command line appium loads the iOS simulator and suddenly crashed without installing my app into the simulator. After reviewing the log i found that "Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled." is failed first.

The Appium server error is :--

```
 [Appium] Creating new XCUITestDriver session
 [Appium] Capabilities:
 [Appium]   app: '/Users/User/Documents/workspace/myApp/resource/myApp.app'
 [Appium]   sendKeyStrategy: 'setValue'
 [Appium]   newCommandTimeout: '9000'
 [Appium]   --no-reset: false
 [Appium]   platformVersion: '10.0'
 [Appium]   browserName: 'iOS'
 [Appium]   platformName: 'iOS'
 [Appium]   deviceName: 'iPad Air 2'
 [Appium]   version: '8.0'
 [Appium]   platform: 'MAC'
 [BaseDriver] Capability 'newCommandTimeout' changed from string ('9000') to integer        (9000). This may cause unexpected behavior
 [BaseDriver] The following capabilities were provided, but are not recognized by appium: --no-reset, version, platform.
 [BaseDriver] Session created with session id: 7854203a-5203-4f6f-9fe9-1df10fe20673
 [debug] [XCUITest] Xcode version set to '8.0'
 [debug] [XCUITest] iOS SDK Version set to '10.0'
 [iOSSim] Constructing iOS simulator for Xcode version 8.0 with udid '14768B9B-0F3A-4081-      9941-6F00D6DA5DCE'
 [XCUITest] Determining device to run tests on: udid: '14768B9B-0F3A-4081-9941-6F00D6DA5DCE', real device: false
 [XCUITest] Safari test requested
 [debug] [iOSLog] Starting iOS 10.0 simulator log capture
 [debug] [iOSLog] System log path: /Users/User/Library/Logs/CoreSimulator/14768B9B-0F3A-4081-9941-6F00D6DA5DCE/system.log
 [XCUITest] Setting up simulator
 [debug] [iOS] No reason to set locale
 [debug] [iOS] No iOS / app preferences to set
 [XCUITest] Simulator with udid '14768B9B-0F3A-4081-9941-6F00D6DA5DCE' not booted.   Booting up now
 [debug] [iOSSim] Killing all iOS Simulators
 [iOSSim] Starting simulator with command: open /Applications/Xcode-     beta.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 14768B9B-0F3A-4081-9941-6F00D6DA5DCE
 [iOSSim] Tailing simulator logs until we encounter the string "SMS Plugin initialized"
 [iOSSim] We will time out after 60000ms
 [debug] [iOSSim] Simulator startup timed out. Continuing anyway.
 [debug] [iOSSim] Waiting an extra 10000ms for the simulator to really finish booting
 [debug] [iOSSim] Done waiting extra time for simulator
 [iOSSim] Simulator booted in 70137ms
 [XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-  xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
 [XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
 [XCUITest] Launching WebDriverAgent on the device
 [debug] [XCUITest] Beginning test with command 'xcodebuild -project  /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=14768B9B-0F3A-4081-9941-6F00D6DA5DCE test' in directory   '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
 [XCUITest] Waiting for WebDriverAgent to start on device
 [debug] [XCUITest] Log file for xcodebuild test: /Users/User/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/9164AEBC-4BC6-4D11-B6B8-88DBA398280A/Session-WebDriverAgentRunner-2016-08-30_181422-1hZd5G.log
 [XCUITest] 2016-08-30 18:14:27.872 xcodebuild[3817:96886] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/User/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/9164AEBC-4BC6-4D11-B6B8-88DBA398280A/Session-WebDriverAgentRunner-2016-08-30_181422-1hZd5G.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/User/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/9164AEBC-4BC6-4D11-B6B8-88DBA398280A/Session-WebDriverAgentRunner-2016-08-30_181422-1hZd5G.log}

 [XCUITest] 2016-08-30 18:14:27.873 xcodebuild[3817:97213] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7f872afdfc10>

 [XCUITest] 
```

Testing failed:

```
 [XCUITest]     ./Scripts/generate_modules.sh: line 15: Modules/module.modulemap:   Permission denied
  ** TEST FAILED **


   The following build commands failed:
PhaseScriptExecution Generate\ modules   /Users/User/Library/Developer/Xcode/DerivedData/WebDriverAgent-     brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-     iphonesimulator/WebDriverAgentLib.build/Script-AD35D0281CF1B37A00870A75.sh
 (1 failure)

 [XCUITest] xcodebuild exited with code '65' and signal 'null'
 [debug] [XCUITest] xcodebuild failure warrants retry. Retrying...
 [XCUITest] Shutting down WebDriverAgent
 [XCUITest] Simulator log exited with code 'null'
 [XCUITest] Launching WebDriverAgent on the device
 [debug] [XCUITest] Beginning test with command 'xcodebuild -project   /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-     driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination  id=14768B9B-0F3A-4081-9941-6F00D6DA5DCE test' in directory  '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
 [XCUITest] Waiting for WebDriverAgent to start on device
 [debug] [XCUITest] Log file for xcodebuild test:   /Users/User/Library/Developer/Xcode/DerivedData/WebDriverAgent- brdadhpuduowllgivnnvuygpwhzy/Logs/Test/007D8FF8-7759-4ABC-A28D-631228541A6B/Session-WebDriverAgentRunner-2016-08-30_181519-GI0cpR.log
 [XCUITest] 2016-08-30 18:15:25.648 xcodebuild[3843:97232] Error   Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/User/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/007D8FF8-7759-4ABC-A28D-631228541A6B/Session-WebDriverAgentRunner-2016-08-30_181519-GI0cpR.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/User/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/007D8FF8-7759-4ABC-A28D-631228541A6B/Session-WebDriverAgentRunner-2016-08-30_181519-GI0cpR.log}

 [XCUITest] 2016-08-30 18:15:25.649 xcodebuild[3843:97723] Connection peer refused  channel request for   "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel    canceled <DTXChannel: 0x7fe1ecab6770>

 [XCUITest] 
 Testing failed:
```

[XCUITest]  ./Scripts/generate_modules.sh: line 15: Modules/module.modulemap: Permission    denied
     *\* TEST FAILED **

```
   The following build commands failed:
PhaseScriptExecution Generate\ modules  /Users/User/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug- iphonesimulator/WebDriverAgentLib.build/Script-AD35D0281CF1B37A00870A75.sh
```

(1 failure)

```
 [XCUITest] xcodebuild exited with code '65' and signal 'null'
 [XCUITest] Error: xcodebuild failed with code 65
at SubProcess.<anonymous> (lib/webdriveragent.js:214:25)
at emitTwo (events.js:106:13)
at SubProcess.emit (events.js:191:7)
at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
Error: xcodebuild failed with code 65
at SubProcess.<anonymous> (lib/webdriveragent.js:214:25)
at emitTwo (events.js:106:13)
at SubProcess.emit (events.js:191:7)
at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
 [XCUITest] Shutting down WebDriverAgent
 [XCUITest] Simulator log exited with code 'null'
 [debug] [XCUITest] Resetting simulator
 [debug] [XCUITest] Shutting down simulator
 [debug] [iOSSim] Killing all iOS Simulators
 [debug] [iOSSim] Killing simulator timed out. Using killall signal
 [debug] [iOSLog] Stopping iOS log capture
 [MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code   65
at SubProcess.<anonymous> (lib/webdriveragent.js:214:25)
at emitTwo (events.js:106:13)
at SubProcess.emit (events.js:191:7)
at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
[HTTP] <-- POST /wd/hub/session 500 205042 ms - 167 
```
## Environment
- Appium 1.6.0 beta 1
- OS X El Capitan 10.11.5
- Node.js v6.4.0
- iOS 10 simulator
  *XCode 8 beta 6
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Code To Reproduce Issue [  ]

i run the appium server by calling  "appium" in terminal and i am using java_client 4.1.2 my code is like below 

```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "iOS");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.0");
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("newCommandTimeout", "9000");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPad Air");
capabilities.setCapability(MobileCapabilityType.VERSION, "8.0");
capabilities.setCapability(MobileCapabilityType.PLATFORM,"Mac");
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("sendKeyStrategy","setValue");
capabilities.setCapability("--no-reset", false);
capabilities.setCapability("app", app.getAbsolutePath());
try {
    AppiumDriver<WebElement> driver = new IOSDriver<WebElement>(new URL(this.getAppiumUrl()), capabilities);
} catch (MalformedURLException e) {
    e.printStackTrace();
} catch (Exception e) {
    e.printStackTrace();
}
```

**Comment by shay777** [comment]
any progress regarding this?

**Comment by imurchie** [comment]
What is in `/Users/User/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/9164AEBC-4BC6-4D11-B6B8-88DBA398280A/Session-WebDriverAgentRunner-2016-08-30_181422-1hZd5G.log`?

**Comment by dumplincat** [comment]
09:39:33.332 xcodebuild[68620:1630266] Beginning test session 317AFE22-3538-426D-A8CC-0BA1A3323DAC with Xcode 7D1012 on target <DVTiOSDevice: 0x7f91a5d47da0> {
		deviceSerialNumber:         FK5PQ2MCG5QT
		identifier:                 0e62ec54a39da6861bba017228ac36977f1e5ecf
		deviceClass:                iPhone
		deviceName:                 TA iPhone 6 Plus
		deviceIdentifier:           0e62ec54a39da6861bba017228ac36977f1e5ecf
		productVersion:             9.3.4
		buildVersion:               13G35
		deviceSoftwareVersion:      9.3.4 (13G35)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        12524122112
		deviceAvailableCapacity:    8587808768
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7f91a5c76ff0 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:             
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (9.3.4 (13G35))
09:39:33.332 xcodebuild[68620:1630266] 	/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
build
test
-project
/Users/shawn.zhang/dev/tools/appium_1.6.0-release/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
-scheme
WebDriverAgentRunner
-destination
id=0e62ec54a39da6861bba017228ac36977f1e5ecf
-configuration
Debug
09:39:33.332 xcodebuild[68620:1630266] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
09:39:33.334 xcodebuild[68620:1630266] Initializing test infrastructure.
09:39:33.841 xcodebuild[68620:1630402] Creating the connection.
09:39:33.842 xcodebuild[68620:1630402] Listening for proxy connection request from the test bundle (all platforms)
09:39:33.842 xcodebuild[68620:1630402] Resuming the connection.
09:39:33.842 xcodebuild[68620:1630402] Test connection requires daemon assistance.
09:39:33.842 xcodebuild[68620:1630266] Checking test manager availability..., will wait up to 120s
09:39:33.843 xcodebuild[68620:1630266] Starting test session with ID <__NSConcreteUUID 0x7f91a5d04a60> 317AFE22-3538-426D-A8CC-0BA1A3323DAC
09:39:33.882 xcodebuild[68620:1630710] testmanagerd handled session request.
09:39:33.883 xcodebuild[68620:1630266] Waiting for test process to launch.
09:39:36.665 xcodebuild[68620:1630266] Test operation failure: Test operation was canceled.
09:39:36.665 xcodebuild[68620:1630266] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled." UserInfo={NSLocalizedDescription=Test operation was canceled.} didCancel: 1

**Comment by dumplincat** [comment]
<script src="https://gist.github.com/dumplincat/2f08e3063d2a071551af7c42c9125e63.js"></script>

**Comment by dumplincat** [comment]
[https://gist.github.com/dumplincat/2f08e3063d2a071551af7c42c9125e63](url)

**Comment by dumplincat** [comment]
[XCUITest] xcodebuild exited with code '127' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 127
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
 Error: xcodebuild failed with code 127
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

**Comment by dumplincat** [comment]
@imurchie do I have the similar error above? thanks

**Comment by imurchie** [comment]
@dumplincat It doesn't look like the same error, no.

Can you provide a gist to the full appium logs? It is impossible to tell from the isolated snippet.

**Comment by dumplincat** [comment]
@imurchie thanks man. pls look at this
https://gist.github.com/dumplincat/24aeb139f238b585190cee417aaab8d8

I'm trying out the new version 1.6.0 release of Appium and counting on it to solve legacy problems like cross-app testing which mean to test something out of the app e.g. notifications. Really appreciate it!

**Comment by parasuramankumarasami** [comment]
when i run the /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/2E0D2143-8A2D-43F8-AA73-42A349197CA1/Session-WebDriverAgentRunner-2016-10-24_142101-cvVcMh.log
**# -bash: /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/2E0D2143-8A2D-43F8-AA73-42A349197CA1/Session-WebDriverAgentRunner-2016-10-24_142101-cvVcMh.log: Permission denied**

I am getting permission denied. how to fix this issue?

**Comment by imurchie** [comment]
@dumplincat Sorry, this slipped passed me in all the reports. I'm not sure what error code 127 is. Can you run the following and see what comes out?

```
cd /Users/hello.world/dev/tools/appium_1.6.0-release/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
/Users/hello.world/dev/tools/appium_1.6.0-release/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /Users/hello.world/dev/tools/appium_1.6.0-release/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=0e62ec54a39da6861bba017228ac36977f1e5ecf
```

**Comment by imurchie** [comment]
@parasuramankumarasami I'm confused. What are you trying to run?

**Comment by parasuramankumarasami** [comment]
Hi @imurchie ,

Xcode : Xcode-beta 8
iOS version in MAC mini: 10.12 (macOS Sierra)
Appium: installed using npm install -g appium@beta
automationName: 'XCUITest'
iPhone has: 10.0.2

I have installed the developer signed build in the iPhone.
i have started the node in the command prompt with necessary parameter like app package, app, app activity and etc.

here is the appium node log:
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=117cbc1f3fa0fe07cd1888b4753811ada8bb9460' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability.
[debug] [XCUITest] Log file for xcodebuild test: /Users/pjayaram/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/01A05D1C-9D88-40AD-83AC-12D07A3E04C5/Session-WebDriverAgentRunner-2016-10-24_163832-3QZoFe.log

when i run the below command in the another terminal:
/Users/pjayaram/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/01A05D1C-9D88-40AD-83AC-12D07A3E04C5/Session-WebDriverAgentRunner-2016-10-24_163832-3QZoFe.log

I am getting permission denied
-bash: /Users/pjayaram/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/01A05D1C-9D88-40AD-83AC-12D07A3E04C5/Session-WebDriverAgentRunner-2016-10-24_163832-3QZoFe.log: Permission denied

When i run the below command in the another terminal

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=117cbc1f3fa0fe07cd1888b4753811ada8bb9460' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

i am getting struck after

▸ Copying /Users/pjayaram/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework
▸ Signing /Users/pjayaram/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework
▸ Touching WebDriverAgentRunner.xctest
▸ Signing /Users/pjayaram/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
▸ Signing /Users/pjayaram/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/yf/qljb2n79607d5blzrq72d0500000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/47dfd274fd1bad87943da309515f1290/117cbc1f3fa0fe07cd1888b4753811ada8bb9460/ManifestCache.plist

i could see web driver is installed in the device.

Please let me proceed.

**Comment by imurchie** [comment]
`/Users/pjayaram/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/01A05D1C-9D88-40AD-83AC-12D07A3E04C5/Session-WebDriverAgentRunner-2016-10-24_163832-3QZoFe.log` is a text file, not a runnable program.

The preceding line is what you need to worry about:

```
[XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability.
```

Can you install, as it says, `deviceconsole`, and pass it in with the `realDeviceLogger` capability? See the note [here](https://github.com/appium/appium-xcuitest-driver/#external-dependencies) for details.

**Comment by parasuramankumarasami** [comment]
hi @imurchie 

I have installed deviceconsolve.

Ps-Mac-mini:bin pjayaram$ npm install -g deviceconsole

> deviceconsole@1.0.1 install /usr/local/lib/node_modules/deviceconsole
> make

Making deviceconsole...
/usr/local/lib
└── deviceconsole@1.0.1 

Ps-Mac-mini:bin pjayaram$ 

where to set the realDeviceLogger capability?

**Comment by jlipps** [comment]
@parasuramankumarasami in your desired capabilities in your client script, like:

```js
capabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
```

**Comment by MadebyBala** [comment]
hi can u help me  with this 

[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:66:19)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
 { [Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1]
  stdout: '\u001b[1mFetching dependencies\n*** Downloading KissXML.framework binary at "5.0.5"\n',
  stderr: 'Failed to write to /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS: Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “iOS” in the folder “Build”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS, NSUnderlyingError=0x7fad08c06630 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}\n',
  code: 1 }
[XCUITest] Shutting down WebDriverAgent
[debug] [XCUITest] Running iOS simulator reset flow
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [XCUITest] Cleaning simulator state.
[debug] [iOSSim] Cleaning app data files for 'IntegrationApp.app', 'com.facebook.IntegrationApprun'
[debug] [iOSSim] Checking whether simulator has been run before
[debug] [iOSSim] Simulator has been run before
[debug] [iOSSim] Building bundle path map
[debug] [iOSSim] Checking whether simulator has been run before
[debug] [iOSSim] Simulator has been run before
[debug] [iOSSim] Building bundle path map
[debug] [iOSSim] Deleting directory: '/Users/user/Library/Developer/CoreSimulator/Devices/A798799D-4D0E-4919-814E-04ABE2438D32/data/Containers/Data/Application/C7838F5F-CDEB-44C4-BAE9-7048039FDCE1'
[debug] [iOSSim] Deleting directory: '/Users/user/Library/Developer/CoreSimulator/Devices/A798799D-4D0E-4919-814E-04ABE2438D32/data/Containers/Bundle/Application/EDEF46F3-9EBC-44A5-8A07-93F8BE59444E'
[debug] [iOSSim] Deleting file: '/Users/user/Library/Developer/CoreSimulator/Devices/Library/Preferences/com.facebook.IntegrationApprun.plist'
[debug] [iOSSim] Killing any simulator daemons for A798799D-4D0E-4919-814E-04ABE2438D32
[iOSSim] Cleaning simulator A798799D-4D0E-4919-814E-04ABE2438D32
[debug] [XCUITest] Resetting simulator
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:66:19)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[HTTP] <-- POST /wd/hub/session 500 167163 ms - 199

**Comment by MadebyBala** [comment]
i am getting error but i installed them correctly please help me in fixing this

**Comment by imurchie** [comment]
@MadebyBala  You don't have permission to write to `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS`. You need to change that (probably best to change the permissions on `/usr/local/lib/node_modules/appium` altogether.
