### ISSUE TITLE
Safari - iOS .getCoordinates().onPage() is acting like .getCoordinates().inViewport()

### ISSUE THREAD

**Issue by hazmeister** [appium/appium#6787]
## The problem

I have a test that clicks a button which scrolls the page down to a particular section.  I then assert that the heading is within the browser's viewport.  On iOS .getCoordinates().onPage() is acting like .getCoordinates().inViewport().
## Environment
- Appium version: 1.53
- Desktop OS/version used to run Appium: OS X 10.11.6
- Mobile platform/version under test: iOS 9.3.5
- Real device or emulator/simulator: iPhone 4S
- Appium.app
## Details

My problem is when the following line executes on Appium with iOS:
`long headingHeight = element(By.cssSelector("h3#objective")).getCoordinates().onPage().getY();`

On iOS the figure returned is 0 (which would be correct if I was asking for `.getCoordinates().inViewport().getY();`)  Executing the same test on Android returns the correct result.

This is a web test for the mobile web, not a web view or native app.
## Code To Reproduce Issue

```
driver.get("http://appium.io/slate/en/master/?java#");
wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Appium GUI"))).click();
Locatable heading = (Locatable) driver.findElement(By.cssSelector("#section-appium-gui>h1"));
System.out.println(heading.getCoordinates().onPage().getY());
```

[Clone here](https://github.com/hazmeister/appium-bugs/blob/master/src/test/java/Coordinates.java)

For this example, on Android, the position is returned in the hundreds of thousands (which is correct , as you have to scroll pretty far to get here).  On iOS, the response is -2 (which would be reasonable accurate if I was asking for onScreen or inViewPort.
## Appium Logs

[Gist](https://gist.github.com/hazmeister/a912efe872d700457f3c23b54231d437)

**Comment by hazmeister** [comment]
Updated with repro

**Comment by hazmeister** [comment]
No worries, log added to main description.  Thanks for looking!

**Comment by dpgraham** [comment]
Closing this. Instruments no longer supported.
