### ISSUE TITLE
Appium can't see UIControl elements.

### ISSUE THREAD

**Issue by KharanKnight** [appium/appium#6788]
I have an app that has sliders in it that are completely 100% invisible to Appium. They are UIControl elements. I have seen other sliders in the app that are UIASliders according to Appium and are 100% interactable, but the UIControl elements don't appear in the Appium Inspector, nor do they appear in the parsed XML document. Any ideas for why this might be, or intended upcoming fixes for this?

**Comment by mykola-mokhnach** [comment]
Make sure you've set the _isAccessibilityElement_ property of the particular control, which is not visible in the tree, to YES. Check https://developer.yahoo.com/blogs/ydn/defining-isaccessibilityelement-ios-application-53755.html for more details

**Comment by SrinivasanTarget** [comment]
@triager please close
