### ISSUE TITLE
Appium pulls stale DOM after an AJAX call is made & the new elements added after the AJAX call are not identified.

### ISSUE THREAD

**Issue by vishwathma** [appium/appium#6792]
Summary:
Appium does not pull the right DOM after an AJAX call is made & it still pulls the stale DOM.
## Environment

In all the scenarios, I have used Simulator and not real devices.
Appium : 1.5.3
xcode : 7.3.1
Plaform : I tested this only on IOS.
## Details

Scenario 1:
I run the automated test case
I navigate to a view
I  do some action which is actually a AJAX call.
The new elements which are loaded after the AJAX Call is made are not identified & the test case fails with a WaitException.

Scenario 2:
I run the test case manually using Appium
Navigate to a view
I do some action which makes AJAX call
Go to Appium Inspector, I see that the elements are identified in the inspector.

Scenario 3:
I run the test case manually using Appium
Navigate to the view
Go to Appium Inspector, I refresh, I see the correct UI elements(before AJAX Call)
Again I go back to the APP, pull activate to refresh(the page gets reloaded)
I do a action which makes a AJAX call & I see the new elements in the view
Again I go back to Appium Inspector, I refresh, I do not see the UI elements which were added to the view after the AJAX call was made.

I have few queries:
1. Is this the issue with Appium or UIAutomation?
2. Is it the same behavior on Android?
3. What is the apt solution to tackle this issue?

**Comment by dpgraham** [comment]
Closing this. If this is still an issue let me know and I can re-open.
