### ISSUE TITLE
add capability for ensuring app hasn't crashed post launch

### ISSUE THREAD

**Issue by jlipps** [appium/appium#6793]
Something like `ensureAppDidntCrashMs`.

The reason is that sometimes an app will crash due to an instruments memory error or something similar very early on in the session, but after we have determined that it launched. If we want to wait a bit longer, we could catch the crash and it would be subject to Appium's retry logic, thereby adding more stability to Appium overall.

It would be optional of course, hidden behind this capability.

**Comment by imurchie** [comment]
Sounds good to me!

**Comment by jlipps** [comment]
This was really only relevant for instruments, which we're no longer supporting
