### ISSUE TITLE
Optional Intent Arguments being stripped away

### ISSUE THREAD

**Issue by hariskhaliq** [appium/appium#6794]
## The problem

Optional Intent Arguments being stripped away when adb gets executed.
## Environment
- Appium version **v1.5.3**
- Last Appium version that did not exhibit the issue: **Didn't try an older version**
- Desktop OS/version used to run Appium: **Mac OS v10.11**
- Node.js version (unless using Appium.app|exe): Using **Appium.exe**
- Mobile platform/version under test: **Android 6.0**
- Real device or emulator/simulator: **Emulator**
- Appium CLI or Appium.app|exe: **appium.exe**
## Details

Detail inside gist.
## Link to Appium logs

https://gist.github.com/hariskhaliq/559fb8998a1bcad849ce43d28eba7b05

**Comment by hariskhaliq** [comment]
Should have been created inside `appium-adb` and just moved it there https://github.com/appium/appium-adb/issues/170

**Comment by jlipps** [comment]
It's ok @hariskhaliq it's useful to track issues here on the main repo. Reopening.

**Comment by jlipps** [comment]
@hariskhaliq can you put the whole thing in additional `"`? It looks like our shell parser is splitting into separate arguments based on spaces, which is reasonable IMO.
