### ISSUE TITLE
Finding a MobileElement inside a MobileElement 

### ISSUE THREAD

**Issue by ruchikar** [appium/appium#6796]
## The problem

So here's the situation:
I have a list of products displayed on a page, and each product has details.
Now am using page factory so I could easily define the product level elements as 

@AndroidFindBy("")
@iOSFindBy("")
MobileElement product;

@AndroidFindBy("")
@iOSFindBy("")
MobileElement product_title;

Now situation is that I want to iterate through each product and verify the details, which would require something like

for (MobileElement product: getAllProduct()) {
Assert.assertTrue(product.findElement(**product_title**).getText());
}

is this currently supported?
## Environment
- Appium version (or git revision) that exhibits the issue:
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
It is possible and should work properly, but I saw some bug reports before, that it sometimes fails, especially on Android. I would suggest to user location by xpath instead, which should work in any case. For example:

```java
final String strXpathParent1Root = "//parent1";
final String strXpathParent2Root = "//parent2";

final Function<By,. String> childrenByParent = parentXPathStr->
    By.xpath(String.format("%s//child", parentXPathStr));

for(String parentXPathStr: new String[] {strXpathParent1Root, strXpathParent2Root}) {
  if (driver.findElements(childrenByParent.apply(parentXPathStr)).size() > 0) {
      System.out.print(String.format("There are children inside %s parent", parentXPathStr));
  }
}
```

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by SrinivasanTarget** [comment]
Go through tests here: https://github.com/appium/java-client/tree/master/src/test/java/io/appium/java_client/pagefactory_tests
