### ISSUE TITLE
Privileges problem during Appium installation on Mac OS

### ISSUE THREAD

**Issue by PaulinkaS** [appium/appium#6798]
After successful Appium installation on Mac with a use of npm:
`sudo npm install -g appium`
followed by installation of "authorize-ios"
`sudo npm install -g authorize-ios`
I tried to run the later. Unfortunately, this ended up with a following exception

> "Encountered an issue changing priveledges...
and "Error was: Command 'chown -R _myusername_" 

After some investigation on my site, I noticed that the username printed in the error message does not correspond to the username I have after checking it in the terminal with the following line:
`id-un`

In order to solve my issue, I change the "Account Name" in my user settings to the same one as displayed in the error. However, I believe it should not be a long term solution due to the fact that not everyone is willing and allowed to change their personal settings. Could you, please, take a look at this and maybe use the `id-un` users credentials instead during the ios authorization process? 

PS. Love your work. Appium is really a great and powerful tool!

**Comment by mykola-mokhnach** [comment]
Any chance NOT to install appium with sudo?

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by SrinivasanTarget** [comment]
Please try to install without sudo command and raise a issue with proper issue description and logs

**Comment by TerryArtlink** [comment]
same.

**Comment by imurchie** [comment]
Same what?
