### ISSUE TITLE
How do I interact with a Safari Web View instead of WebView on iOS?

### ISSUE THREAD

**Issue by vorgaszeldrahar** [appium/appium#6800]
## The problem

I'm testing an app which provides functionality to log in through Google. When you click the button to log in with Google, the application opens a Safari Web View so that the user can provide his or her credentials. I've tried to interact with this by switching from native view to web view, but encountered an error. I have also encountered errors when trying to retrieve the list of contexts.

The code that I used to attempt to switch to a different context is pretty simplistic:
`self.driver.switch_to.context("WEBVIEW_1")`

I tried using "WEBVIEW" and "WEBVIEW_1" as inputs, but neither seemed to work.

Here is the output in the Appium log:
https://gist.github.com/vorgaszeldrahar/e3af135caf8424c517ba24aded7c149d

Is there a recommended way to interact with a Safari Web View with Appium?

## Environment

* Appium version (or git revision) that exhibits the issue: Version 1.5.3 running on OS X.
* Last Appium version that did not exhibit the issue (if applicable): Unknown
* Desktop OS/version used to run Appium: OS X 10.11.6 (El Capitan)
* Node.js version (unless using Appium.app|exe): N/A
* Mobile platform/version under test: iPhone 6s Plus
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium.app

## Details

See above.

## Link to Appium logs

https://gist.github.com/vorgaszeldrahar/e3af135caf8424c517ba24aded7c149d

**Comment by jlipps** [comment]
@vorgaszeldrahar did you first run the command to get a list of contexts before trying to set one?

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by SrinivasanTarget** [comment]
Closed this because of inactivity
