### ISSUE TITLE
can't test app in real device by ios

### ISSUE THREAD

**Issue by wenshi11019** [appium/appium#6803]
## Description

when i test app with real device, it failed to start the appium server correctly. I found someone say that the reason is ios device update to 9.3.4? but I run success in version 1.5.3 with the same code.
## Environment

java client build version: 4.1.2
Appium server version: 1.6.0-beta1
Desktop OS: OSX El Capitan 10.11.6
Node.js version 6.5.0
Mobile platform/version under test: iOS
Real device or emulator/simulator: real device
## Details

the real device haven't test app,but i see appium log stop in "Creating iDevice object with udid 26378cb9bca6165915278f7afb38aa0b432c5381",and then appium server doesn't work.
## Code To Reproduce Issue [ Good To Have ]

`       DesiredCapabilities capabilities = new DesiredCapabilities();

```
    capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone5s");
    capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);
    capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "9.3.4");

    capabilities.setCapability(MobileCapabilityType.APP, "/Users/gaojiewen/Library/Developer/Xcode/DerivedData/语音信箱-efrgkaqmpsyueggibdtnqonlpuun/Build/Products/Debug-iphoneos/Voicemail.app");

    capabilities.setCapability(IOSMobileCapabilityType.BUNDLE_ID, "com.voicemail.iflyzunhong");

    capabilities.setCapability(MobileCapabilityType.UDID, "26378cb9bca6165915278f7afb38aa0b432c5381");

    capabilities.setCapability(MobileCapabilityType.FULL_RESET, Boolean.TRUE);
    capabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, 60000);

    IOSDriver<MobileElement> driver = null;
    service.startAppiumServer();//start the appium server in /bin/bash

    try {
        logger.info("starting create the IOSDriver.");
        driver = new IOSDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);

        logger.info("the IOSDriver create Successfully.");
    } catch (WebDriverException e) {

        logger.error("the AppiumService haven't started.\n", e);
    } catch (MalformedURLException e) {

        logger.error("the IOSDriver create failed.", e);
    }`
```
## Ecxeption stacktraces

https://gist.github.com/wenshi11019/6bdd8ceb02da3e656ebb7a28b539ca27
## Link to Appium logs

https://gist.github.com/wenshi11019/e8f693a36a02e3225bdf6f30b540eb33

**Comment by wenshi11019** [comment]
I reported this question in appium/java_client. See at https://github.com/appium/java-client/issues/463

**Comment by mykola-mokhnach** [comment]
Have you tried this solution: https://github.com/appium/appium/issues/6730 ?

**Comment by wenshi11019** [comment]
@mykola-mokhnach I can run success with 9.3.4 in version 1.5.3.  I think it only opper in 1.6.0-beta-1

**Comment by imurchie** [comment]
This is no longer an issue.
