### ISSUE TITLE
Can't interact with NumberPicker

### ISSUE THREAD

**Issue by arctouch-thiagomachado** [appium/appium#6805]
## The problem

I want to interact with an android.widget.NumberPicker to change the selected value. I've tried to use `send_keys("Mon")` and I've tried to tap on previous/next value, but nothing happens.

## Environment

* Appium version that exhibits the issue: 1.5.3
* Desktop OS/version used to run Appium: OS X El Capitan 10.11.4
* Mobile platform/version under test: Android 5.0
* Real device or emulator/simulator: Galaxy S5 (real device)

## Details

Properties of the "NumberPicker":
```
content-desc: 
type: android.widget.NumberPicker
text: 
index: 0
enabled: true
location: {96, 737}
size: {192, 540}
checkable: false
checked: false
focusable: false
clickable: false
long-clickable: false
package: *********
password: false
resource-id: 
scrollable: true
selected: false
xpath: //android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.NumberPicker[1]
```

## Link to Appium logs

Appium log when I use `send_keys` on NumberPicker:
https://gist.github.com/arctouch-thiagomachado/6ffbf89c4ccc0c00a9b8e9043e0b282a

Appium log when I use `send_keys` on EditText inside NumberPicker:
https://gist.github.com/arctouch-thiagomachado/ad57b0038ac490c5233e79fcb314add2

Appium log when I tap on Button inside NumberPicker:
https://gist.github.com/arctouch-thiagomachado/ed8bf71284b7401dd3bfec1e9257135e

## Code To Reproduce Issue

- send_keys on NumberPicker: 

`$driver.find_element(:xpath, "//android.widget.NumberPicker[1]").send_keys("Mon")`

- send_keys on EditText inside NumberPicker:

`$driver.find_element(:xpath, "//android.widget.NumberPicker[2]/android.widget.EditText").send_keys("10")`

- tap on Button inside NumberPicker:

`$driver.find_element(:xpath, "//android.widget.NumberPicker[1]/android.widget.Button[2]").click`

**Comment by jlipps** [comment]
I believe this method of setting the value of a picker wheel is only supported on iOS. For Android I am not sure if UiAutomator gives us any good way to set the value of a NumberPicker. Notice how in this UiAutomator demo file they actually click an incrementing button to make the value the right value: https://android.googlesource.com/platform/development/+/master/samples/UiAutomator/src/com/android/test/uiautomator/demos/SetTwoMinuteAlarm.java#104

**Comment by arctouch-thiagomachado** [comment]
@jlipps We've tried to click the incrementing button. This works on Android 4.4.2, but it's not working on Android 5.

On the logs above I've showed the result of trying to tap on the incrementing button.

Thanks!

**Comment by jlipps** [comment]
Unfortunately Appium is sending the command to UiAutomator successfully, and UiAutomator is actually running the tap. If it's not triggering the behavior correctly in your app, that's either a UiAutomator bug, or maybe you don't have the same element you think you have?
