### ISSUE TITLE
Not able to find elements inside a webview on Android Emulator.

### ISSUE THREAD

**Issue by asharm9** [appium/appium#6806]
## The problem

Started running the test cases on Android Emulator but the same test case which works fine on real Android device the same test case is failing after switching the context to webview and could not find elements inside webview.
Also if two apps are present in Emulator which has debuggable webview then while running he test case on one app, the list of webview gives the webview of the other app too which is not on foreground but just installed in the emulator. 
## Environment
- Appium version 1.5.3
- Node version 5.1.0
- Using Emulator
- Tried with running appium server through appium GUI as well as through creating shell file.

**Comment by jlipps** [comment]
> the same test case is failing after switching the context to webview and could not find elements inside webview.

Please provide a link to a gist of your full appium logs which show the webview context switch and the element finding failure

> Also if two apps are present in Emulator which has debuggable webview then while running he test case on one app, the list of webview gives the webview of the other app too which is not on foreground but just installed in the emulator.

This is not totally unexpected. The real question is, is the webview you're interested in also in the list?

**Comment by asharm9** [comment]
@jlipps Thanks for the response.

I have accumulated more information on this. The issue is only happening on the Nexus device with Android 6 both on real device and emulator. Appium is able to switch the context to webview but i guess could not able to maintain the chromedriver session somehow. Thats what i suspect.

Below is the logs i am getting.

[MJSONWP] Calling AppiumDriver.getContexts() with args: ["d9984d9f-29c1-4f2c-b89
4-6...
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 3 device(s) connected
[debug] [ADB] Running C:\Android\AndroidSDK\platform-tools\adb.exe with args: ["
-P",5037,"-s","ENU7N15C15000588","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_11191 mapped to pid 11191
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 3 device(s) connected
[debug] [ADB] Running C:\Android\AndroidSDK\platform-tools\adb.exe with args: ["
-P",5037,"-s","ENU7N15C15000588","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 11191 pkg: com.***.android.debug!
[debug] [AndroidDriver] from: u0_a88,11191,3900,2659340,436548,0000000000,R,com.
kmart.android.debug
[debug] [AndroidDriver] returning process name: com.kmart.android.debug
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.******.android.debug"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.****.and
roid.debug"]
[MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP","
WEBVIEW_com....
[HTTP] <-- GET /wd/hub/session/d9984d9f-29c1-4f2c-b894-61f57f591ffe/contexts 200
 722 ms - 120
[HTTP] --> POST /wd/hub/session/d9984d9f-29c1-4f2c-b894-61f57f591ffe/context {"n
ame":"WEBVIEW_com.kmart.android.debug"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_com.*****.andro
id...
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"versio
n":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 9 ms - 83
[debug] [ADB] 3 device(s) connected
[debug] [ADB] Running C:\Android\AndroidSDK\platform-tools\adb.exe with args: ["
-P",5037,"-s","ENU7N15C15000588","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_11191 mapped to pid 11191
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 3 device(s) connected
[debug] [ADB] Running C:\Android\AndroidSDK\platform-tools\adb.exe with args: ["
-P",5037,"-s","ENU7N15C15000588","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 11191 pkg: com.****.android.debug!
[debug] [AndroidDriver] from: u0_a88,11191,3900,2659340,437340,SyS_epoll_,000000
0000,S,com.****.android.debug
[debug] [AndroidDriver] returning process name: com.*****.android.debug
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.******.android.debug"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.*****.and
roid.debug"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'WEBVIEW_com
.****.android.debug'
[debug] [AndroidDriver] Found existing Chromedriver for context 'WEBVIEW_com.****.android.debug'. Using it.
[JSONWP Proxy] Proxying [GET /url] to [GET http://127.0.0.1:9521/wd/hub/session/
750e87cc6ac517e1c2964bff885b1393/url] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"750e87cc6...
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/d9984d9f-29c1-4f2c-b894-61f57f591ffe/context 200
 717 ms - 76
[HTTP] --> GET /wd/hub/session/d9984d9f-29c1-4f2c-b894-61f57f591ffe/context {}
[MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["d9984d9f-29c1-4f
2c-b894-6...
[MJSONWP] Responding to client with driver.getCurrentContext() result: "WEBVIEW_
com.******.android....
[HTTP] <-- GET /wd/hub/session/d9984d9f-29c1-4f2c-b894-61f57f591ffe/context 200
4 ms - 105
[HTTP] --> GET /wd/hub/session/d9984d9f-29c1-4f2c-b894-61f57f591ffe/cookie {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [GET /wd/hub/session/d9984d9f-29c1-4f2c-b894-61f57f591ff
e/cookie] to [GET http://127.0.0.1:9521/wd/hub/session/750e87cc6ac517e1c2964bff8
85b1393/cookie] with body: {}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"750e87cc6...
[JSONWP Proxy] Replacing sessionId 750e87cc6ac517e1c2964bff885b1393 with d9984d9
f-29c1-4f2c-b894-61f57f591ffe
[HTTP] <-- GET /wd/hub/session/d9984d9f-29c1-4f2c-b894-61f57f591ffe/cookie 200 1
1 ms - 222
[HTTP] --> DELETE /wd/hub/session/d9984d9f-29c1-4f2c-b894-61f57f591ffe {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["d9984d9f-29c1-4f2c-b
894-6...
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Stopping chromedriver for context WEBVIEW_com.****.andr
oid.debug
[debug] [Chromedriver] Changed state to 'stopping'
[JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:9521/wd/hub/sessi
on/750e87cc6ac517e1c2964bff885b1393] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"750e87cc6...
[debug] [Chromedriver] Changed state to 'stopped'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 3 device(s) connected
[debug] [ADB] Running C:\Android\AndroidSDK\platform-tools\adb.exe with args: ["
-P",5037,"-s","ENU7N15C15000588","shell","am","force-stop","com.*****.android.de
bug"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 3 device(s) connected
[debug] [ADB] Running C:\Android\AndroidSDK\platform-tools\adb.exe with args: ["
-P",5037,"-s","ENU7N15C15000588","shell","am","force-stop","io.appium.unlock"]
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
[debug] [ADB] 3 device(s) connected
[debug] [ADB] Running C:\Android\AndroidSDK\platform-tools\adb.exe with args: ["
-P",5037,"-s","ENU7N15C15000588","shell","input","keyevent",3]
[debug] [Logcat] Stopping logcat capture
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdow
n"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value"
:"OK, shutting down"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomato
rTestRunner
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunS
erver
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appi
um.android.bootstrap.Bootstrap
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter
=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Time: 385.838
[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 3 device(s) connected
[debug] [ADB] Running C:\Android\AndroidSDK\platform-tools\adb.exe with args: ["
-P",5037,"-s","ENU7N15C15000588","shell","ps","uiautomator"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Moving to state 'stopped'
[Appium] Removing session d9984d9f-29c1-4f2c-b894-61f57f591ffe from our master s
ession list
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/d9984d9f-29c1-4f2c-b894-61f57f591ffe 200 3517
ms - 76
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"Appium
","platform":"ANDROID","deviceName":"GalaxyS5","platformName":"Android","appActi
vity":"com.sears.android.activity.SearsMainActivity","appPackage":"com.sears.and
roid.debug"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"Ap
pium"...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   automationName: 'Appium'
[Appium]   platform: 'ANDROID'
[Appium]   deviceName: 'GalaxyS5'
[Appium]   platformName: 'Android'
[Appium]   appActivity: '<App activity>'
[Appium]   appPackage: '<App package>'
[Appium]   platformVersion: '4.4'
[Appium]   udid: 'ENU7N15C15000588'
[Appium]   appWaitActivity: '<wait activity>'
[BaseDriver] The following capabilities were provided, but are not recognized by
 appium: platform.
[BaseDriver] Session created with session id: 1b3bcc26-ee62-4419-9169-f3bf90f4d2
52
[debug] [AndroidDriver] Getting Java version
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[AndroidDriver] Java version is: 1.7.0_45
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Android\AndroidSDK\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 3 device(s) connected
[AndroidDriver] Using device: ENU7N15C15000588
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Android\AndroidSDK\platform-tools\adb.exe
[debug] [ADB] Setting device id to ENU7N15C15000588
[AndroidDriver] App file was not listed, instead we're going to run com.sears.an
droid.debug directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 3 device(s) connected

**Comment by dpgraham** [comment]
Closing this. If this is still a problem, I'll re-open and we can revisit this.
