### ISSUE TITLE
understanding DeviceName capability for android for a emulator farm on single machine

### ISSUE THREAD

**Issue by jayantsarda** [appium/appium#6807]
Am able to test on individual emulators but have issues with the whole emulator farm. My setup is as below:
I have 8 emulators running on different ports in same machine(one with high ram and cpu). The device names start from emulator-5556 to emulator-5580 ( i don't have emulator-5554). Test do run on most of these emulators but looks like by the time each emulator runs one test , all other test fails for below error (like out of 400 test only few are executed and others fail)

I need help on what should be my deviceName capability value from my test. If omit it it fails for DeviceName not provided. (note that i have common capability creation method for all my test)

I have these emulator registered with a grid which distributes the test among these nodes

Error: 

> An unknown server-side error occurred while processing the command. Original error: Device emulator-5554 was not in the list of connected devices (WARNING: The server did not provide any stacktrace information)
> Command duration or timeout: 9.05 seconds

I am using appium 1.5.3 .As far as i remember with older version of appium this capability was ignored ... so my setup was working fine.

Can some guide me on how to make this setup working again.
Is having "emulator-5554" mandatory?
Thanks in advance for help on this.

**Comment by mykola-mokhnach** [comment]
Have you already tried this solution described in the documentation?

> Sometimes, for various reasons, adb gets stuck. If it’s not showing any connected devices or otherwise failing, you can restart it by running:
> adb kill-server && adb devices

Which devices are shown in

```
adb devices -l
```

command output?

**Comment by mykola-mokhnach** [comment]
Have you already tried this solution described in the documentation?

> Sometimes, for various reasons, adb gets stuck. If it’s not showing any connected devices or otherwise failing, you can restart it by running:
> adb kill-server && adb devices

Which devices are shown in

```
adb devices -l
```

command output?

**Comment by mykola-mokhnach** [comment]
Have you already tried this solution described in the documentation?

> Sometimes, for various reasons, adb gets stuck. If it’s not showing any connected devices or otherwise failing, you can restart it by running:
> adb kill-server && adb devices

Which devices are shown in

```
adb devices -l
```

command output?

**Comment by mykola-mokhnach** [comment]
Have you already tried this solution described in the documentation?

> Sometimes, for various reasons, adb gets stuck. If it’s not showing any connected devices or otherwise failing, you can restart it by running:
> adb kill-server && adb devices

Which devices are shown in

```
adb devices -l
```

command output?

**Comment by mykola-mokhnach** [comment]
Have you already tried this solution described in the documentation?

> Sometimes, for various reasons, adb gets stuck. If it’s not showing any connected devices or otherwise failing, you can restart it by running:
> adb kill-server && adb devices

Which devices are shown in

```
adb devices -l
```

command output?

**Comment by jayantsarda** [comment]
thanks for response @mykola-mokhnach . In My case I am not even spinning up "emulator-5554" so devices list also does not have it. Do does its mandatory to have this device name running ?

**Comment by mykola-mokhnach** [comment]
I think so. I haven't tried to run it with simulator, but Appium requires real devices to be constantly connected

**Comment by imurchie** [comment]
You can have Appium spin up the specified emulator by specifying it in the `avd` capability.

**Comment by jayantsarda** [comment]
@mykola-mokhnach I do have other devices emulators running..I just don't have "emulator-5554" which the default first device name assigned to emulators  My list looks like this:

> emulator-5524          device product:sdk_x86 model:Android_SDK_built_for_x86 device:generic_x86
emulator-5534          device product:sdk_x86 model:Android_SDK_built_for_x86 device:generic_x86
emulator-5544          device product:sdk_x86 model:Android_SDK_built_for_x86 device:generic_x86
emulator-5564          device product:sdk_x86 model:Android_SDK_built_for_x86 device:generic_x86

>
