### ISSUE TITLE
Appium fails to install the app after an attempt to install Xcode 8 Beta

### ISSUE THREAD

**Issue by nchinenk** [appium/appium#6808]
## The problem

I attempted to install Xcode 8 Beta today and my automated tests failed to run. I have since uninstalled Xcode 8 from my machine and reinstalled Xcode 7.3.1 and am still having the same issue. The log in Appium is stating it fails to uninstall or install the app. I rechecked all the settings are they are still the same as when the test were running smoothly. Please help.

## Environment

* Appium version 1.5.3 (ara)
* Desktop OS/version used to run Appium: Mac OS El Capitan
* Mobile platform/version under test: 9.3.4
* Real device: iPad Air 2

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

https://gist.github.com/nchinenk/41850ef80f9e2e7dcee60b84829d4bf9

##Code

import unittest
from selenium.webdriver.common.action_chains import ActionChains
import time
import os
import sys
from appium import webdriver
import re

success = True
desired_caps = {}
desired_caps['appium-version'] = '1.0'
desired_caps['platformName'] = 'iOS'
desired_caps['platformVersion'] = '9.3'
desired_caps['deviceName'] = 'iPad Air 2'
desired_caps['app'] = os.path.abspath('/Users/Nikita/Library/Developer/Xcode/DerivedData/POSLavu-fcxgdffvtlhkbvgusqtrawkbwafu/Build/Products/Debug-iphoneos/POSLavu.app')
#Enable the following line to prevent app from reinstalling next time you run the test. At the initial run you can get it to the point where you would like your next test to run from
desired_caps['noReset'] = True

wd = webdriver.Remote('http://0.0.0.0:4723/wd/hub', desired_caps)
#wd.implicitly_wait(60)

**Comment by nchinenk** [comment]
Forgot to mention I am getting same error when both running a script written in Python and when trying to use Appium Inspector. Here are the screenshots with the error and my settings,
![screen shot 2016-09-06 at 5 22 55 pm](https://cloud.githubusercontent.com/assets/15165971/18294476/b7ebeb5e-7456-11e6-8d4a-2b21f740d1a0.png)
![screen shot 2016-09-06 at 5 24 24 pm](https://cloud.githubusercontent.com/assets/15165971/18294482/c8138adc-7456-11e6-8491-128279141e1f.png)
![screen shot 2016-09-06 at 5 24 42 pm](https://cloud.githubusercontent.com/assets/15165971/18294491/d20d978a-7456-11e6-9754-343e9eb03032.png)
![screen shot 2016-09-06 at 5 24 59 pm](https://cloud.githubusercontent.com/assets/15165971/18294495/dcec392c-7456-11e6-8a4d-b504fca0f9a4.png)
![screen shot 2016-09-06 at 5 25 18 pm](https://cloud.githubusercontent.com/assets/15165971/18294505/e8955574-7456-11e6-857f-93867a6fdd0b.png)

**Comment by imurchie** [comment]
Appium 1.5.3 **will not** be able to automate using Xcode 8, as Xcode 8 removed all support for Instruments automation, which is how Appium 1.5.3 does things.

We are working on a replacement driver for iOS going forward. It is in beta right now. You can install it using `npm install -g appium@beta`. You will also need to have `Carthage` installed (`brew install carthage`) and use the `automationName` of `XCUITest`.

**Comment by nchinenk** [comment]
Thanks for the quick response. That explains a lot! However, my current concern is if I can revert everything to the way it was. I uninstalled Xcode 8, reinstalled Xcode 7, but the app fails to start by Appium. Is there a way to manually install instruments automation or diagnose it? Thanks!

**Comment by imurchie** [comment]
Not sure what you mean by manually install Instruments.

If you give the logs for the failure when using xcode 7, perhaps we could help diagnose the problem. In my experience switching xcodes is pretty simply (I have, for instance, 6 different versions installed, that I switch between to do/test different things).

**Comment by nchinenk** [comment]
The appium log I attached to the original report above is from after Xcode 8 was removed and Xcode 7 reinstalled. Is there another log i can retrieve and post here to help with this issue?

**Comment by imurchie** [comment]
Sorry. I didn't realize that.

What version of iOS is the iPad running. There was a problem with iOS 9.3.4 where the secure connection was changed and the installer no longer worked. 9.3.5 fixed it, I think.

**Comment by nchinenk** [comment]
It's 9.3.4. I'm upgrading now to see if there is any difference. But again, something got wrong/broken during installation of Xcode 8 i believe, which I removed since then. Could it be that the instruments module in Xcode 7 got corrupted/removed by Xcode 8 installation? In which case is there a way to diagnose and fix that?

**Comment by nchinenk** [comment]
All tests created with Appium ran fine on the same iPad on 9.3.4 before the ill attempt to upgrade to Xcode 8.

**Comment by imurchie** [comment]
Hmm. I don't know. I've never run across anything like that, but it is possible, I guess.

**Comment by nchinenk** [comment]
Does the log shed any light onto why might be wrong?

**Comment by imurchie** [comment]
Not really.

Can you try manually installing the app? You can try through xcode, just to see. And then as Appium does, using `ideviceinstaller`:

```
ideviceinstaller \
-u 87a79ee694273bd27f16a30771429c301a5cb327 \
-i /Users/Nikita/Library/Developer/Xcode/DerivedData/POSLavu-fcxgdffvtlhkbvgusqtrawkbwafu/Build/Products/Debug-iphoneos/POSLavu.app
```

**Comment by nchinenk** [comment]
I can install using Xcode just fine. When i try running the device installer command it gives me an error: "Could not connect to lockdown. Exiting"

**Comment by imurchie** [comment]
Yes. That is the issue with 9.3.4. I'm not sure why it ever worked (unless you already had the app on the iPad and it didn't need to re-install it).

**Comment by nchinenk** [comment]
I just updated to 9.3.5 and I'm still getting that error when running ideviceinstaller command

**Comment by nchinenk** [comment]
I fixed the issue with ideviceinstaller not working by running this command: sudo chmod -R 777 /var/db/lockdown/. After that everything is back to normal again. thanks for your help!

**Comment by imurchie** [comment]
Awesome!
