### ISSUE TITLE
arc fails with exception in 1.6.0-beta1 if automationName set to XCUITest

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/appium#6809]
## The problem

arc is failing with an exception on OS X 10.11.6 and Xcode 7.1.3 if automationName is set to XCUITest. 
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0-beta1
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3
- Desktop OS/version used to run Appium: 10.11.6
- Node.js version (unless using Appium.app|exe): 6.5.0
- Mobile platform/version under test: iOS 9.3
- Real device or emulator/simulator: Simulator
- Appium CLI or Appium.app|exe: CLI
## Details

I uninstalled 1.5.3, installed 1.6.0-beta1, and now I can no longer launch arc. The only other change made was adding the automationName field to caps and setting it to XCUITest.

If this field is removed, arc launches as expected.
## Link to Appium logs

Appium log: https://gist.github.com/VivaLosDoyers/81c67283c2f132a28af500a27de9bb59
arc output: https://gist.github.com/VivaLosDoyers/1dcaeccf88deadbbb3a5db7ca6c321ac
## Code To Reproduce Issue [ Good To Have ]

The appium.txt contents:

| => cat appium.txt 
[caps]
automationName = "XCUITest"
platformName = "iOS"
app = "~/appium/myApp.app"
platformVersion = "9.3"
deviceName = "iPad Retina"
fullReset = "true"

**Comment by imurchie** [comment]
What is `arc`?

**Comment by mykola-mokhnach** [comment]
Make sure you have write permissions to the whole /usr/local folder:
```
sudo chown -R $USER /usr/local
```

**Comment by VivaLosDoyers** [comment]
@mykola-mokhnach unfortunately that didn't fix my issue

@imurchie arc is the appium ruby console. I didn't realize that was a separate project from the main appium. Maybe I should create an issue on that project...

**Comment by imurchie** [comment]
This _looks_ like a server issue.

What are your permissions on `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS`?

**Comment by rkavalap** [comment]
@VivaLosDoyers Is this still an issue with latest version of appium server and appium ruby console ?

**Comment by VivaLosDoyers** [comment]
No, it isn't. I've been using arc with Appium 1.6.0 and 1.6.1 beta without issue.
