### ISSUE TITLE
adb shell ping is getting escaped too many times

### ISSUE THREAD

**Issue by imurchie** [appium/appium#6810]
## The problem

At certain points the adb shell ping command gets escaped too many times, and adb cannot run it.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Linux
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs

https://gist.github.com/imurchie/86c06ac25a12cf5b330b19c429639c98

**Comment by jlipps** [comment]
For some reason I thought this was fixed already @imurchie?

**Comment by imurchie** [comment]
I think it is. This was a support issue that I wanted to check out. But it was in 1.4.16.
