### ISSUE TITLE
Appium won't install for me on Windows 7

### ISSUE THREAD

**Issue by JAffleck** [appium/appium#6812]
## The problem

I thought appium was supposed to work on Windows 7.
Please let me know if there's anything I'm doing wrong, or if Windows 7 x64 is Unsupported.
I ran the following command from an Command Prompt with Admin privileges (see screenshot):
npm install -g appium

It looks like it's dying when it gets to an fsevents module because it says it can't rename some files.
The suggestion says run it in a command prompt as an administrator, and I did, and that didn't fix anything.  Does anyone have any ideas?

## Environment

![appium_install](https://cloud.githubusercontent.com/assets/5248068/18355978/3ca44bbe-75a8-11e6-9ecc-4d19d4d27099.png)
Windows 7 x64
node 6.5.0
nom 3.10.3
Error Number -4048
syscall rename

## LogFile
[npm-debug.log.txt](https://github.com/appium/appium/files/462032/npm-debug.log.txt)

**Comment by imurchie** [comment]
It should.

The first highlighted portion of the log is normal: `fsevents` is a library necessary on Mac systems, and is skipped in all other environments.

The second is a permissions problem. I don't know what the permissions is on your install directory, so it's hard to say what the problem is. Do you have permission to write to there? 

There is documentation on setting up for Windows here: https://github.com/appium/appium/blob/master/docs/en/appium-setup/running-on-windows.md

**Comment by mykola-mokhnach** [comment]
probably you have some leftovers  from an old unfinished installation? Try  to remove appium first by executing 

```
npm remove -g appium
```

or delete appium folder inside node_modules root manually and run install.

**Comment by mykola-mokhnach** [comment]
What you can also try is to temporarily disable your Antivirus software while installing the stuff and run

```
npm cache clean
```

before the operation

**Comment by JAffleck** [comment]
@imurchie I should have rights to those folders.  
I checked to make sure my user account was in the Administrators group, and even removed it from the Users group, but still ran into the same issue.

**Comment by JAffleck** [comment]
![image](https://cloud.githubusercontent.com/assets/5248068/18357783/77c1e9fc-75af-11e6-95c8-d2a844d78227.png)

[npm-debug.log.txt](https://github.com/appium/appium/files/462139/npm-debug.log.txt)

**Comment by JAffleck** [comment]
Wow it worked.  Thanks for the help guys!
