### ISSUE TITLE
/wd/hub/session/:sessionId/appium/device/rotate not implemented

### ISSUE THREAD

**Issue by imurchie** [appium/appium#6815]
`/wd/hub/session/:sessionId/appium/device/rotate` not implemented in xcuitest driver, because it's not implemented in XCUITest itself.

Acceptance criteria:
* [ ] radar filed requesting rotation support
* [ ] linked to worms
* [ ] docs updated mentioning lack of support for this feature

**Comment by imurchie** [comment]
Seems like there is support for this now. Not sure if/how it works.

https://github.com/facebook/WebDriverAgent/blob/61323c31289e76f2618347c385f78a0b5b7ea838/WebDriverAgentLib/Commands/FBOrientationCommands.m#L42-L43

**Comment by jlipps** [comment]
interesting. maybe we should change the acceptance criteria here and reload this for a future sprint since it looks like it will involve actual investigation / work?

**Comment by imurchie** [comment]
Yes, seems like. Turn it into an investigation ticket. I'm happy to keep it in the sprint and do it tomorrow, since it will be timeboxed.

**Comment by jlipps** [comment]
👍

**Comment by imurchie** [comment]
I've done some investigation. The WDA implementation _looks_ right. `wd` does not currently support the [device rotation spec](https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md#device-rotation) so I cannot say that it actually works. But Appium will proxy requests for both getting and setting to WDA, which can handle both.

Closing this as no longer an issue.
