### ISSUE TITLE
/wd/hub/session/:sessionId/appium/app/end_test_coverage not implemented

### ISSUE THREAD

**Issue by imurchie** [appium/appium#6819]
`/wd/hub/session/:sessionId/appium/app/end_test_coverage` not implemented in xcuitest driver

**Comment by jlipps** [comment]
this is not implemented in the old iOS driver, do we even care about this?

**Comment by SrinivasanTarget** [comment]
Yes @jlipps We don't have this on legacy iOS driver as well.

**Comment by jlipps** [comment]
Going to close then
