### ISSUE TITLE
Search by XPath always returns an empty result with Appium 1.6.0beta1 @ XCUITest

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#6823]
## The problem

XPath locators stopped working in Appium 1.6.0beta @ with XCUITest set as automationName
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0beta1
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3
- Desktop OS/version used to run Appium: OSX 10.11.6
- Node.js version (unless using Appium.app|exe): 5.4.1
- Mobile platform/version under test: iOS 9.3
- Real device or emulator/simulator: Simulator
- Appium CLI or Appium.app|exe: CLI
## Details

Locating elements by XPath always returns empty result. Location by accessibility id and className works as expected. Element location by the same XPath expression in the XML document returned by driver.getPageSource() method succeeds if I use any 3-rd party XML editor tool.
The same code triggers no issues if "classic" Appium iOS driver is used.
## Appium logs

https://gist.github.com/mykola-mokhnach/f2ce48e7a7c206574a13f7986debf914
## Code To Reproduce Issue [ Good To Have ]

``` java
driver.findElements(MobileBy.xpath("(//Window[@name='ZClientMainWindow']//CollectionView)[1]/Cell/StaticText[@value='49f6cef7']/parent::*"))
```

Other XPath expressions fail as well, for example "//Window"

**Comment by imurchie** [comment]
Can you try `//XCUIElementTypeWindow`?

**Comment by mykola-mokhnach** [comment]
@imurchie Yep, this one is found (through it took several seconds to locate it). Strange, I don't see any nodes with such names in the generated page tree.

**Comment by imurchie** [comment]
No, the generated page tree gives the name minus `XCUIElementType`, for reasons that I don't fully understand. And mostly it returns "Other", which is apparently some Apple attempt at making things difficult.

**Comment by mykola-mokhnach** [comment]
This is what I currently see:
![screen](https://cloud.githubusercontent.com/assets/7767781/18388861/9512fec0-76a3-11e6-9d7c-12cc41446e01.png)

So. how to workaround this? Change all node names to something like 

```
//XCUIElementTypeWindow
```?

**Comment by mykola-mokhnach** [comment]
The second weird thing is, that 

```
findElement(By.className("Window")) == findElement(By.className("XCUIElementTypeWindow")) 
```

but 

```
findElement(By.xpath("//Window")) != findElement(By.xpath("..XCUIElementTypeWindow")) 
```

**Comment by ssynix** [comment]
@mykola-mokhnach the reason is that WDA replaces occurrences of `XCUIElementType` in the page source to make it more readable and reduce its size.

Their className locator strategy is able to handle this simplification logic.

There are bound to be backwards-incompatible changes in the page source due to the switch to a different automation framework. In our app, there seem to be extra `Other` elements here and there that I didn't used to see in UIAutomation. So, many of our locators that used XPath to locate elements by their path are completely broken.

**Comment by mykola-mokhnach** [comment]
@imurchie Can you please provide some hint on attributes location? Let say, if I want to find the first visible image in the tree, then I use this expression:

```java
driver.findElements("//XCUIElementTypeImage[@visible='true']")
```

But this does not find anything as a result, though the original XML contains this attribute for sure. Shall I also add some magic prefix to attribute names?

**Comment by ssynix** [comment]
@mykola-mokhnach  If you use the WDA inspector (`serverURL/inspector`), it shows that the visibility attribute is called `isVisible`. I haven't tested it but it's probably going to work with that.

**Comment by mykola-mokhnach** [comment]
@ssynix Thanks for your answer. Unfortunately, inspector is not available for me. The following exception is shown if I try to navigate http://localhost:8100/inspector URL:
```javascript
{
  "value" : "Invalid parameter not satisfying: path\n\n(\n\t0   CoreFoundation                      0x0000000106575d85 __exceptionPreprocess + 165\n\t1   libobjc.A.dylib                     0x0000000105fe9deb objc_exception_throw + 48\n\t2   CoreFoundation                      0x0000000106575bea +[NSException raise:format:arguments:] + 106\n\t3   Foundation                          0x0000000105c33d5a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198\n\t4   WebDriverAgentLib                   0x0000000113a2185b -[FBResponseFilePayload initWithFilePath:] + 283\n\t5   WebDriverAgentLib                   0x0000000113a1db67 FBResponseFileWithPath + 87\n\t6   WebDriverAgentLib                   0x0000000113a2de8c __29+[FBInspectorCommands routes]_block_invoke + 108\n\t7   WebDriverAgentLib                   0x0000000113a1de2c -[FBRoute_Sync mountRequest:intoResponse:] + 140\n\t8   WebDriverAgentLib                   0x0000000113a16304 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 548\n\t9   RoutingHTTPServer                   0x0000000113adac18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136\n\t10  RoutingHTTPServer                   0x0000000113adb4fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47\n\t11  libdispatch.dylib                   0x0000000108e233d7 _dispatch_client_callout + 8\n\t12  libdispatch.dylib                   0x0000000108e0ee2f _dispatch_barrier_sync_f_slow_invoke + 65\n\t13  libdispatch.dylib                   0x0000000108e233d7 _dispatch_client_callout + 8\n\t14  libdispatch.dylib                   0x0000000108e0de5d _dispatch_main_queue_callback_4CF + 714\n\t15  CoreFoundation                      0x00000001064cf0f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9\n\t16  CoreFoundation                      0x0000000106490b99 __CFRunLoopRun + 2073\n\t17  CoreFoundation                      0x00000001064900f8 CFRunLoopRunSpecific + 488\n\t18  Foundation                          0x0000000105bd3a31 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 267\n\t19  Foundation                          0x0000000105c66fe1 -[NSRunLoop(NSRunLoop) run] + 74\n\t20  WebDriverAgentLib                   0x0000000113a15246 -[FBWebServer startServing] + 230\n\t21  WebDriverAgentRunner                0x000000011053afc4 -[UITestingUITests testRunner] + 100\n\t22  CoreFoundation                      0x000000010645e5cc __invoking___ + 140\n\t23  CoreFoundation                      0x000000010645e41e -[NSInvocation invoke] + 286\n\t24  XCTest                              0x0000000105a82ef3 __24-[XCTestCase invokeTest]_block_invoke_2 + 362\n\t25  XCTest                              0x0000000105ab7613 -[XCTestContext performInScope:] + 190\n\t26  XCTest                              0x0000000105a82d78 -[XCTestCase invokeTest] + 169\n\t27  XCTest                              0x0000000105a833a2 -[XCTestCase performTest:] + 459\n\t28  XCTest                              0x0000000105a80cf7 -[XCTestSuite performTest:] + 396\n\t29  XCTest                              0x0000000105a80cf7 -[XCTestSuite performTest:] + 396\n\t30  XCTest                              0x0000000105a80cf7 -[XCTestSuite performTest:] + 396\n\t31  XCTest                              0x0000000105a6db10 __25-[XCTestDriver _runSuite]_block_invoke + 51\n\t32  XCTest                              0x0000000105a8eb4c -[XCTestObservationCenter _observeTestExecutionForBlock:] + 640\n\t33  XCTest                              0x0000000105a6da55 -[XCTestDriver _runSuite] + 453\n\t34  XCTest                              0x0000000105a6e7d1 -[XCTestDriver _checkForTestManager] + 259\n\t35  XCTest                              0x0000000105ab8a9a _XCTestMain + 628\n\t36  CoreFoundation                      0x000000010649b2ec __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12\n\t37  CoreFoundation                      0x0000000106490f75 __CFRunLoopDoBlocks + 341\n\t38  CoreFoundation                      0x00000001064906d2 __CFRunLoopRun + 850\n\t39  CoreFoundation                      0x00000001064900f8 CFRunLoopRunSpecific + 488\n\t40  GraphicsServices                    0x0000000108630ad2 GSEventRunModal + 161\n\t41  UIKit                               0x000000010692bf09 UIApplicationMain + 171\n\t42  XCTRunner                           0x00000001059f28ad XCTRunner + 6317\n\t43  libdyld.dylib                       0x0000000108e5292d start + 1\n\t44  ???                                 0x0000000000000005 0x0 + 5\n)",
  "sessionId" : "A6AEB186-5D4F-428B-8913-5ED273F55D81",
  "status" : 13
}
```

I have tried to put different possible attribute names and see whether it works, but neither of them can be found:
```
FAILED:
//XCUIElementTypeImage[@visible]
//XCUIElementTypeImage[@isVisible]
//XCUIElementTypeImage[@displayed]
//XCUIElementTypeImage[@isDisplayed]
//XCUIElementTypeImage[@enabled]
//XCUIElementTypeImage[@isEnabled]

PASSED:
//XCUIElementTypeImage[@name]
//XCUIElementTypeImage[@label]
//XCUIElementTypeImage[@value]
//XCUIElementTypeImage[@rect]
//XCUIElementTypeImage[@type]
```

**Comment by amirwaisman** [comment]
What about absolute xPaths? 

What should I change in something like: 

//UIAApplication[1]/UIAWindow[4]/UIAAlert[1]/UIAScrollView[1]/UIAStaticText[1]

?

Thanks.

**Comment by mykola-mokhnach** [comment]
XCUIDriver also advertises possibility to find elements by predicate string:
https://github.com/facebook/WebDriverAgent/wiki/Queries (using predicate string):

```bash
curl -X POST $JSON_HEADER \
-d "{\"using\":\"predicate string\",\"value\":\"isWDVisible=1\"}" \
$DEVICE_URL/session/$SESSION_ID/elements
```

but I don't see any possibility in Appium Java client (v4.1.2) to use this feature.

**Comment by ptsiakos77** [comment]
@mykola-mokhnach 
I have the same problem regarding the time required to locate the elements by xpath. In my case takes approximately 4 seconds which is kind of unacceptable so I have switched back from XCuiTest to UI Automation.

 Any ideas why is this delay present and when will be fixed?

**Comment by ssynix** [comment]
@mykola-mokhnach 
* Maybe the inspector bundle is not built for you. Try going into the WDA folder and run `./Scripts/bootstrap.sh -i`, you can also go to [http://localhost:8100/source](http://localhost:8100/source) for seeing the page source.

* java-client 5.0 will include searching by `IosNSPredicate`.

* I debugged the xpath issue you brought up and noticed that WDA [does not include visibility as an attribute](https://github.com/facebook/WebDriverAgent/blob/14820677342fc035bb1df29a206d613542dc5c13/WebDriverAgentLib/Categories/XCElementSnapshot%2BFBHelpers.m#L57) in the XML page source that it passes to its XPath parser (KissXML).

@amirwaisman Ideally you'd find and replace these element types with their [equivalents in XC testing](https://github.com/facebook/WebDriverAgent/blob/6816e09583c46655e7b7650df84641c64b2b5fdf/WebDriverAgentLib/Utilities/FBElementTypeTransformer.m#L23). However as I mentioned, there were extra `Other` container elements in my page source which completely invalidated all these absolute paths. So you'd have to test this out yourself...

**Comment by dpgraham** [comment]
I don't believe this is an issue anymore. Predicate strings are now supported and you can find elements by XPath in XCUITest now. Will re-open if issues found.
