### ISSUE TITLE
support a way to run shell script on host machine

### ISSUE THREAD

**Issue by huminzhi** [appium/appium#6824]
A feature request:
## The problem

Using iOS UIAutomation, we can run script on host machine by sending command to appium: "UIATarget().Host().execute(path, [])"... 
However this feature is no longer available in XCUITest.
## Details

We still hope to have this feature so that we can run sqlite3, plistBuddy to setup the simulation as we need... Some examples are:
1. install cert file onto simulation (modify file TrustStore.sqlite3)
2. allow the application to access calendar (modify file TCC.db)
3. allow launch schema so that you won't stuck at an alert when app launched from URL (com.apple.launchservice.schemaapproval.plist)
....

It's true most cases we can use PullFile() PushFil() to achieve what we want, but it will be very handy if appium can allow and support running script on the host.

**Comment by jlipps** [comment]
Thanks @huminzhi. I could see us adding an endpoint that allows you to upload a cert that will be part of the trust store for the session. What do you do to the calendar db to allow access?

If you can share the specific ways you achieve these things, it will make it easier to add them in as Appium features.

**Comment by huminzhi** [comment]
@jlipps sorry to reply late, for calendar db, what we do is:
sqlite3 <path to TCC.db> "insert into 'access' VALUES ('kTCCServiceCalendar', '<app bundler id>', 0,1,1,0,0)";

It's a bit "hacky" way, but didn't find a better way, if you know some other approach, would love to learn :)

**Comment by jlipps** [comment]
that's great, thanks

**Comment by huminzhi** [comment]
Hi, @jlipps Is it something can be quickly added in 1.6.0beta? It turns out we have quite some places using this feature...

**Comment by dpgraham** [comment]
This feature is available: https://github.com/appium/appium-xcuitest-driver/pull/385
