### ISSUE TITLE
driver.getContexts() fails with "Error: Could not connect to a valid app after 20 tries"

### ISSUE THREAD

**Issue by robin-lott** [appium/appium#6825]
## The problem

I am testing an app flow that involves clicking a button in the app which opens a webpage in Safari.
I then use `available_contexts` to confirm that Safari has opened, before trying to switch contexts to Safari.
The problem is that the `available_contexts` command is failing.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3 (& 1.6.0-beta1)
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: OS X 10.11.6
* Node.js version (unless using Appium.app|exe): 6.3.1
* Mobile platform/version under test: iOS 9.3 (& 8.4)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

The simulator is launched and the app installed via Appium Ruby Console (https://github.com/appium/ruby_console).
The desired capabilities used are:
```
driver.capabilities['desired']
{
             "newCommandTimeout" => 999999,
                      "bundleId" => "<bundle id of app>",
                    "deviceName" => "iPhone 6",
                  "platformName" => "iOS",
               "platformVersion" => "9.3",
                           "app" => '<path to app>',
                 "keepKeyChains" => true,
       "locationServicesEnabled" => true,
    "locationServicesAuthorized" => true
}
```

1. The app is launched and `available_contexts` works as expected.
2. Then a button is clicked in the app which opens a page in Safari.
3. At this point I use `available_contexts` to check that Safari is present.
That fails, like this:
```
pry(main)> available_contexts
Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not connect to a valid app after 20 tries.
from /Users/login/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
```
Full details in logs linked to below.

## Link to Appium logs

[Appium logs gist](https://gist.github.com/robin-lott/3e4819b346914645628874fed03e6093)

## Code To Reproduce Issue [ Good To Have ]

**Comment by jlipps** [comment]
Unfortunately, Appium does not currently support automating multiple apps within the same session. The reason is (as you can see in your logs) that Instruments will exit as soon as the app under test exits. With Appium 1.6 however this should be possible as we're moving away from Instruments as the automation engine for iOS.

**Comment by robin-lott** [comment]
Thanks for the information. We will stick with Appium 1.4.16 for now then, since that version does support the flow described above.

**Comment by midopa** [comment]
I'm seeing this sometimes in my mobile Safari tests. They do not leave the app. They only open and close new tabs. My test environment is nearly identical to the original issue, except I'm using Node 6.7.0

Error message:
```
2016-10-11 22:23:40:899 - [MJSONWP] Encountered internal error running command: Error: Could not connect to a valid app after 20 tries.
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at RemoteDebugger.selectApp$ (lib/remote-debugger.js:216:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

Can this be reopened? If not, I can file another issue,.

**Comment by derunewige** [comment]
I have quite the same problem. 
I am clicking on a button that opens a website. Now i want to change the context and the same error occurs. But then i found out, it does not matter when I am calling getContextHandels(). At every point in my code that error occurs.

Appium version (or git revision) that exhibits the issue: 1.6.1-beta
Desktop OS/version used to run Appium: OS X 10.12.2
Node.js version (unless using Appium.app|exe): 6.9.1
Mobile platform/version under test: iOS 9.3
Real device or emulator/simulator: simulator
Appium CLI or Appium.app|exe: Appium CLI

```		
private AppiumDriver<IOSElement> driver;

DesiredCapabilities caps = new DesiredCapabilities();
caps.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
caps.setCapability(MobileCapabilityType.PLATFORM_VERSION, "9.3"); 
caps.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6s"); 
caps.setCapability(MobileCapabilityType.APP, "/Users/username/Desktop/appname.app"); 

caps.setCapability(IOSMobileCapabilityType.BUNDLE_ID, "at.xxx.xxx");
caps.setCapability(IOSMobileCapabilityType.AUTO_ACCEPT_ALERTS, Boolean.TRUE);
caps.setCapability(IOSMobileCapabilityType.SEND_KEY_STRATEGY, "setValue");
caps.setCapability(MobileCapabilityType.NO_RESET, Boolean.TRUE);
caps.setCapability(MobileCapabilityType.FULL_RESET, Boolean.FALSE);
driver = new IOSDriver<>(new URL("http://127.0.0.1:4723/wd/hub"), caps);
```

```
	    Set<String> contextNames = driver.getContextHandles();
	    for (String contextName : contextNames) {
	        System.out.println(contextName);
	        if (contextName.contains("WEBVIEW")){
	            driver.context(contextName);
	        }
	    }
```

=>
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not connect to a valid app after 20 tries.

Link to appium log:
https://gist.github.com/derunewige/ba854d5068f86d332ac3e746c7ef78d2

**Comment by derunewige** [comment]
Found a solution for my problem. I just added a Thread.sleep() before I am calling .getContextHandles()

**Comment by midopa** [comment]
I'm glad you have it working for your scenario, but hard coding waits is more of a band-aid solution.

**Comment by derunewige** [comment]
I know =(
But do you know a wait condition I can use for an implicit wait? Can I increase the amount of tries from 20 to something like 100 and hope it won't kill the server?

**Comment by jlipps** [comment]
@derunewige you could wrap the context setting logic itself in a retry with a short timeout. Something like this (pseudocode):

```
while getContexts() does not include "WEBVIEW":
  sleep 500ms
setContext("WEBVIEW")
```

(of course you'd want some kind of global timeout in case it never finds one). But this should at least keep your wait more elastic.

**Comment by derunewige** [comment]
Thanks for your response jlipps! But the problem is, that getContexts() throws an error. 
If I would make such a while loop, I somehow have to ignore the error till It works.
As soon as the call of getContexts() is working, the webview is instantly found.

**Comment by jlipps** [comment]
@derunewige you could achieve this by using exception handling in your programming language. and @imurchie's recent changes should prevent the getContext call from throwing an error immediately.

**Comment by SergheiRidico** [comment]
I also faced this issue. 
Appium server: v1.8.1-beta1
iOS: 11.3
Simulator: iPhone 8

```[MJSONWP] Encountered internal error running command: Error: Could not connect to a valid app after 20 tries.
[MJSONWP]     at Object.wrappedLogger.errorAndThrow (/usr/local/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:78:13)
[MJSONWP]     at RemoteDebugger.selectApp$ (/usr/local/lib/node_modules/appium/node_modules/appium-remote-debugger/lib/remote-debugger.js:277:6)
[MJSONWP]     at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
[MJSONWP]     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
[MJSONWP]     at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
[MJSONWP]     at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)```

I got this error after had tried to getContextHandles.
