### ISSUE TITLE
UnreachableBrowserException and SessionNotCreatedException on iOS Appium Automation

### ISSUE THREAD

**Issue by LokeshGangaiah** [appium/appium#6826]
## The problem

Getting the error UnreachableBrowserException and SessionNotCreatedException when trying to Launch the App on iOS actual device using Appium Server.

Also not even able to just launch the App from the appium tool(inspector), when try to do that gives the same error as mentioned below for appium logs. The settings in the Appium is fine, it is the same settings which i used earlier to run the automation,but now its not working. 

I am using latest xCode ver8.0-beta,is it causing this issue? does the appium not support with latest xcode

UIAutomation option is also enabled

Did go through few of the blogs and comments such as,non of them worked: 1. Updating the chormedriver 2. changing the browser name in capabilities 3. Including the jar files

## Environment

* Appium version (or git revision) that exhibits the issue:1.5.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac 10.11
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:iPhone 5
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

https://gist.github.com/LokeshGangaiah/48554cac7fafcdc5bf47dd8a36465cf8

## Code To Reproduce Issue [ Good To Have ]

https://github.com/appium/sample-code/compare/master...LokeshGangaiah:patch-1#diff-6cbcfcd2e671db128b348863f424c961

**Comment by jlipps** [comment]
You can't install a .app onto a real device. You need a signed .ipa file.

**Comment by LokeshGangaiah** [comment]
Thanks @jlipps it worked. I was loading .app file in Appium settings as well in my script  i was passing .app file. But i used to use .app file earlier and it used to work am surprised to see its not working now.
But after seeing your comment and changing it back to .ipa file in both appium and my script -worked
