### ISSUE TITLE
getContexts() retrieves webviews of background application

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#6828]
Steps to reproduce:
1. Launch application with webview and place the application in background( App-1)
2. Launch the second application from Appium and getContexts() fetch's webview from the App-1 which is in the background.

[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/XXXX/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.68.102:5555","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] WEBVIEW_6613 mapped to pid 6613
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/XXXX/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.68.102:5555","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 6613 pkg: com.prajaatvkannada.XXXX.prajaatvkannada!
[debug] [AndroidDriver] from: u0_a67,6613,465,1476500,180496,ffffffff,b7730f75,S,com.prajaatvkannada.XXXX.prajaatvkannada
[debug] [AndroidDriver] returning process name: com.prajaatvkannada.XXXX.prajaatvkannada
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.prajaatvkannada.XXXX.prajaatvkannada"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.prajaatvkannada.XXXX.prajaatvkannada"]

[MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_com.prajaatvkannada.XXXX.prajaatvkannada"]
[HTTP] <-- GET /wd/hub/session/9933fbaa-0b00-4e42-9bb3-60b9b6308d7e/contexts 200 88 ms - 141

**Comment by SrinivasanTarget** [comment]
@triager please label: Bug

**Comment by juhlila** [comment]
any news about this? im having the same problem

**Comment by dpgraham** [comment]
I doubt the core Appium team will be able to get to this in the near future, but if anyone in the community would like to jump on this, we'd be happy to take pull requests.

**Comment by mykola-mokhnach** [comment]
Closing it as fixed. We now verify isActive attribute for each web view
