### ISSUE TITLE
Appium@1.6.0beta1 throws "Cannot read property 'sendCommand' of undefined" exception in XCUITest  automation mode if setValue method of IOSElement is invoked

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#6829]
## The problem

Appium throws an exception if _setValue_ method of IOSelement instance is invoked.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0beta1
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: OS X 10.11.6
* Node.js version (unless using Appium.app|exe): 5.4.1
* Mobile platform/version under test: 9.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Please find below

## Link to Appium logs

https://gist.github.com/mykola-mokhnach/cb1b23b17744079cecf2e6f023c12fec

## Code To Reproduce Issue [ Good To Have ]

```java
final WebElement convoInput = driver.findElement(nameConversationInput);
((IOSElement) convoInput).setValue(message);
```

**Comment by imurchie** [comment]
Thanks for this! A fix is in the works.

**Comment by SrinivasanTarget** [comment]
@triager please close
