### ISSUE TITLE
Foreground screen elements not detected by Appium

### ISSUE THREAD

**Issue by Abur73** [appium/appium#6830]
## The problem

While trying to get element's information, it was found that elements were not detected by the Appium inspector (from the screen on the foreground), elements detected were the ones from the screen on the background.
Checked the same screen using UIAutomationViewer and elements are displayed correctly. Tried to use the xpath & resourceID from UIAutomatorViewer on my actual scripts on Appium, but I have got "Element not found" error exception. So the element on the foreground is not even detected on Execution time either.
Also tried UiSelector calls to Server, but that would not work also, got "Element not found".
## Environment
- Appium GUI 1.4.13, 1.5.3, headless 1.4.16
- Ran Appium on Mac OS X "El Capitan"
- Used Genymotion with AVD Google Nexus 6P API23 6.0.0
## Details

No Elements are being detected on neither Appium GUI server at execution time nor using Inspector.

<img width="1392" alt="screen shot 2016-09-12 at 11 42 04 am" src="https://cloud.githubusercontent.com/assets/22153748/18444556/4a0f00d4-78df-11e6-89c2-0939490b8887.png">

<img width="1278" alt="screen shot 2016-09-12 at 11 42 57 am" src="https://cloud.githubusercontent.com/assets/22153748/18444560/4c521200-78df-11e6-9a62-3828ddae2f37.png">
## Link to Appium logs

https://gist.github.com/Abur73/d700b6982b7b16090b3a3b478acc6e2b
## Code To Reproduce Issue [ Good To Have ]

https://play.google.com/store/apps/details?id=com.disney.mdx.wdw.google&hl=en

**Comment by lvconley** [comment]
I've encountered this issue on Android as well, most recently with Appium 1.5.3 on the Mac. Most frustrating since UIAutomatorViewer can see the elements just fine.

**Comment by SrinivasanTarget** [comment]
Please try appium-desktop incase if you hit the same reopen the issue again.

**Comment by benjamintanner** [comment]
What was the solution to this, I am seeing the exact same issue with Appium 1.2.7

**Comment by renjujv** [comment]
What was the solution for this issue?
I am still facing the same issue on 1.6.1 with my Appium Desktop Linux AppImage release.

![selection_172](https://user-images.githubusercontent.com/3957722/41234705-8b97d1a4-6daa-11e8-8c9e-f68720855b22.png)

In the above one, the voice search button from main page is getting selected.

![selection_173](https://user-images.githubusercontent.com/3957722/41235010-6c402120-6dab-11e8-8a0f-38913447178b.png)

Any workaround?
