### ISSUE TITLE
iOS driver does not return usable webview elements resulting from arbitrary executeScript calls

### ISSUE THREAD

**Issue by jlipps** [appium/appium#6831]
This is https://github.com/appium/appium-ios-driver/issues/173

**Comment by dpgraham** [comment]
@jlipps The linked issue was deleted. Do you remember the details of this?

**Comment by jlipps** [comment]
Yeah: basically when you would return an element from an executeScript call, it wouldn't be wrapped up in the appropriate element object. or it would only be wrapped up if it was not in an array. i think this is pretty low priority though.

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
