### ISSUE TITLE
Two sessions initialized in Appium 1.5.3 and iOS 9.3

### ISSUE THREAD

**Issue by mpetrak** [appium/appium#6832]
## The problem

Initializing two new sessions with one webdriver init (webdriverio v4.2.11) in Appium 1.5.3 & iOS 9.3.
Init phase endup with

>  A new session could not be created. Details: Problem getting session data for driver type IosDriver; does it implement 'get driverData'?
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable): 1.4.16
- Desktop OS/version used to run Appium: OS X El Capitan
- Node.js version (unless using Appium.app|exe): LTS 4.4.7
- Mobile platform/version under test: iOS 9.3
- Real device or emulator/simulator: iPhone Simulator
- Appium CLI or Appium.app|exe: node app
## Details

From log (https://gist.github.com/mpetrak/fb095ffbcca5c3d0fede51febf92b0c9) there is 'waiting for device boot' and empty response from server to client. Then, client immediately sending same 'createSession' request. During this waiting, mobile simulator is going through reset phase. After that it seems like next 'createSession' is executed and server ends up. I've tried --session-override server arguments, but it leads to never ending simulator reboots - up to test timeout.

When i start same test with 'noReset' capability. It seems like device is booted quicker, there is no empty response from server to client -> no second 'createSession' call and no error during initialization. But it's not a way for me. I need to have my simulator clean before each test.

Don't know if it is really appium server issue or client library issue. But it is working with same client and appium 1.4.16 with iOS 8.4. But in this configuration I can see a different process of simulator reset / cleanup, which seems to be quicker. From my point of view the empty response is the reason.

No another appium session running in background.
## Link to Appium logs

https://gist.github.com/mpetrak/fb095ffbcca5c3d0fede51febf92b0c9

**Comment by mpetrak** [comment]
Client issue. Solved by webdriverIO connectionRetryTimeout configuration option

**Comment by RohitJ158** [comment]
sometime There is problem to locate the element on the web view. As the element is actually present but not able to make any activity with that.
