### ISSUE TITLE
Can't click a TouchableHighlight view when the view is inside a ListView

### ISSUE THREAD

**Issue by xianlinbox** [appium/appium#6833]
## The problem
I try to perform a click action on an element which is inside a ListView, But there is no corresponding response for this action.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3
* Desktop OS/version used to run Appium: OS X EL Captain 10.11.6
* Node.js version (unless using Appium.app|exe):  4.2.1
* Mobile platform/version under test: iOS 9
* Real device or emulator/simulator: simulator 
* Appium CLI or Appium.app|exe:  Appium.app

## Details
In my App, There is a simple user flow:

**Input some words -> click search -> show list of results -> `click` first item -> show first item details.**

When I try to perform this flow in Appium,  click search works fine, I can see the list of results, but when i perform click first item, it doesn't work. I can't see the first item details.

## Code [ Good To Have ]
SearchButton:
```
<TouchableHighlight style={styles.button}
                              underlayColor='#99d9f4'
                              testID="SearchButton"
                              onPress={this.onSearchPressed.bind(this)}>
            <Text style={styles.buttonText}>Go</Text>
          </TouchableHighlight>
```
List of Results:
```
renderRow(rowData, sectionID, rowID) {
    const price = rowData.price_formatted.split(' ')[0];

    return (
      <TouchableHighlight onPress={() => this.rowPressed(rowData.guid)}
                          testID={'property' + rowID}
                          underlayColor='#dddddd'>
        <View>
          <View style={styles.rowContainer}>
            <Image style={styles.thumb} source={{ uri: rowData.img_url }} />
            <View  style={styles.textContainer}>
              <Text style={styles.price}>£{price}</Text>
              <Text style={styles.title}
                    numberOfLines={1}>{rowData.title}</Text>
            </View>
          </View>
          <View style={styles.separator}/>
        </View>
      </TouchableHighlight>
    );
  }

  render() {
    return (
      <ListView
        dataSource={this.state.dataSource}
        renderRow={this.renderRow.bind(this)}/>
    );
  }
```
The method  i tried to perform the action:
```
appiumDriver.elementById('property0').click();
appiumDriver.elementById('property0').tap();

appiumDriver.elementById('property0')
.then((el) =>{
var action = new wd.TouchAction(driver);
        action
          .press({el: el, x: 10, y: 10})
          .release();
        return action.perform();
}))
```

**Comment by mykola-mokhnach** [comment]
What do you see in Appium log?
As a workaround, you may calculate absolute coordinates of the element on the screen and perform a generic tap:

```
driver.tap(1, x, y, 125)
```

**Comment by xianlinbox** [comment]
The Appium log as follow:

```
[HTTP] --> POST /wd/hub/session/76921463-ed88-4610-b20e-09c02e812125/element/3/click {}
[MJSONWP] Calling AppiumDriver.click() with args: ["3","76921463-ed88-4610-b2...
[debug] [iOS] Executing iOS command 'click'
[debug] [UIAuto] Sending command to instruments: au.tapById('3')

[debug] [Instruments] [INST] 2016-09-14 06:15:45 +0000 Debug: Got new command 19 from instruments: au.tapById('3')

[debug] [Instruments] [INST] 2016-09-14 06:15:45 +0000 Debug: evaluating au.tapById('3')
[debug] [Instruments] [INST] 2016-09-14 06:15:45 +0000 Debug: UIAElement.tap()

[debug] [Instruments] [INST] 2016-09-14 06:15:45 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-09-14 06:15:45 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-09-14 06:15:45 +0000 Debug: Running system command #20: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/b9/0dgr2bjx1fbdvq3n1wtrwfy80000gn/T/instruments_sock 2,{"status":0,"v...

```

**Comment by jlipps** [comment]
Appium did its job correctly. Unfortunately you're not seeing the correct response in your app. This could be for a few reasons:

1) Your app is broken (but presumably that is ruled out when you have used it manually)
2) Instruments/UIAutomation has a bug (which is not unlikely)--unfortunately we can't do anything about that
3) The element you've found is not actually the element you think it is
4) There's a race condition and the element is not yet tappable when your code is trying to tap it

Ideas:
1) add a temporary sleep before the click just to see if it's a race condition
2) try clicking twice
3) inspect the xml to make sure the element is visible and the one you want.
