### ISSUE TITLE
Feature: Make special XCUIElement and XCUICoordinate methods available from Appium

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#6834]
Current Appium iOS implementation does not allow to perform double tap, pinch or hover actions properly. And these methods are already implemented for instances of **XCUIElement** and **XCUICoordinate** classes. It would be nice to have wrappers for these methods in Appium@XCUITest as well.

**Comment by jlipps** [comment]
Closing this out and creating new issues to track the requests here:
* #7140 
* https://github.com/appium/appium/issues/7141

`doubleTap` should already work according to @imurchie
