### ISSUE TITLE
[Appium@1.6.0beta1] Calling driver.tap in XCUITest mode throws "Support for gestures other than Tap is not yet implemented" exception

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#6836]
## The problem

calling driver.tap method immediately fails the test
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0beta1
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3
- Desktop OS/version used to run Appium: 10.11.6
- Node.js version (unless using Appium.app|exe):5.4.1
- Mobile platform/version under test: 9.3
- Real device or emulator/simulator: Simulator
- Appium CLI or Appium.app|exe: CLI
## Details

See below
## Link to Appium logs

```
2016-09-13 13:45:51:872 - info: [HTTP] --> POST /wd/hub/session/fc90e4e8-0ba6-4aad-92d6-5303931af43a/touch/perform {"actions":[{"action":"press","options":{"x":343,"y":639}},{"action":"wait","options":{"ms":125}},{"action":"release","options":{}}]}
2016-09-13 13:45:51:877 - info: [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
2016-09-13 13:45:51:879 - info: [debug] [XCUITest] Executing command 'performTouch'
2016-09-13 13:45:51:916 - info: [HTTP] <-- POST /wd/hub/session/fc90e4e8-0ba6-4aad-92d6-5303931af43a/touch/perform 501 10 ms - 175 
2016-09-13 13:45:57:328 - info: [HTTP] --> DELETE /wd/hub/session/fc90e4e8-0ba6-4aad-92d6-5303931af43a {}
2016-09-13 13:45:57:329 - info: [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["fc90e4e8-0ba6-4aad-92d6-5...
2016-09-13 13:45:57:331 - info: [XCUITest] Shutting down WebDriverAgent
2016-09-13 13:45:57:336 - info: [XCUITest] Simulator log exited with code 'null'
2016-09-13 13:45:57:350 - info: [XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
2016-09-13 13:45:57:352 - info: [debug] [XCUITest] Resetting simulator
2016-09-13 13:45:57:354 - info: [debug] [XCUITest] Shutting down simulator
```
## Code To Reproduce Issue [ Good To Have ]

``` java
driver.tap(1, x, y, 125);
```

```
org.openqa.selenium.WebDriverException: Support for gestures other than Tap is not yet implemented. Please contact an Appium dev (WARNING: The server did not provide any stacktrace information)
```

**Comment by yaphatak** [comment]
@imurchie : Looking at request (POST /wd/hub/session/fc90e4e8-0ba6-4aad-92d6-5303931af43a/touch/perform {"actions":[{"action":"press","options":{"x":343,"y":639}},{"action":"wait","options":{"ms":125}},{"action":"release","options":{}}]}) this is different way of calling tap. We do support one way here 
https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/gesture.js#L26

Should we support both?

**Comment by imurchie** [comment]
Yes, it should be translated in `performTouch` and sent to the tap method. Alas.

**Comment by amirwaisman** [comment]
So what is the conclusion here?

**Comment by PS-Matt** [comment]
I'm running into a similar behavior on 1.6.0beta1—it seems related to me, but I've never declared myself an expert on the matter. The scenario occurs when attempting to perform a scrolling gesture.  The log reports the following:

**Comment by yaphatak** [comment]
We really cant pass `wait` to WDA as it is not used to do tap

**Comment by igalep** [comment]
Same issue as well , but I'm using beta2 of appium 1.6

the action I trying to perform **(worked on appium 1.5.3)**

`touchAction.press(element, elementWidth, elementHeight).waitAction(550).moveTo(-150, 0).release().perform();` - swipe left

and the exception I'm getting is the same :

> (org.openqa.selenium.WebDriverException: Support for gestures other than Tap is not yet implemented. Please contact an Appium dev ...


pls try to look into as well !

Thanks

**Comment by mgeilich** [comment]
Are gestures other than Tap supported yet?  I am getting this same error and wonder if it is just a misleading error message and my problem is really something different?

**Comment by mykola-mokhnach** [comment]
@mgeilich you can temporarily workaround the problem by triggering direct calls to WDA. All you need to implement are elements location and _dragfromtoforduration_ API call. [Here](https://github.com/facebook/WebDriverAgent/tree/master/WebDriverAgentLib/Commands) is the full list of supported WDA commands and [here](https://github.com/facebook/WebDriverAgent/wiki/Queries) you can find queries examples.

**Comment by mgeilich** [comment]
@mykola-mokhnach direct calls to WDA look promising though it is not clear to me how to get the SESSION_ID needed for those API calls.  I am starting my session (python) with:

        self.driver = webdriver.Remote(
            command_executor='http://127.0.0.1:4723/wd/hub',
            desired_capabilities={
                'bundleId': app,
                'autoWebview': False,
                'platformName': 'iOS',
                'platformVersion': '10.0',
                'deviceName': 'iPhone',
                'browserName': '',
                'udid': '1c723fabed8e8f743e40e6f918da25f8416724d4',
                'realDeviceLogger': '/usr/local/bin/idevicesyslog',
                'locationServicesEnabled': True,
                'locationServicesAuthorized': True,
                'automationName': 'XCUITest'
            })

I do not see a WDA API call to retrieve the SESSION_ID.  Is there a way to do that?



On Oct 12, 2016, at 3:25 AM, mykola-mokhnach <notifications@github.com<mailto:notifications@github.com>> wrote:


@mgeilich<https://github.com/mgeilich> you can temporarily workaround the problem by triggering direct calls to WDA. All you need to implement are elements location and dragfromtoforduration API call. Here<https://github.com/facebook/WebDriverAgent/tree/master/WebDriverAgentLib/Commands> is the full list of supported WDA commands and here<https://github.com/facebook/WebDriverAgent/wiki/Queries> you can find queries examples.

**Comment by mykola-mokhnach** [comment]
You can extract session id by just sending simple GET request to the WDA's / endpoint:

```bash
curl http://localhost:8100/
```

Current session id will be returned as a value of _sessionId_ key in response JSON.

**Comment by mgeilich** [comment]
Sadly, all I get back is this:
self = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x108a77310>
response = {'sessionId': '89343673-43c7-4af4-89f5-9f4e4012a8f5', 'status': 13, 'value': {'message': 'Method has not yet been implemented’}}

The call I am making from Python is:
        stuff = self.driver.execute("touchLongPress", params={"elements":map.get_attribute("id")})

Should I be making the call differently?



On Oct 12, 2016, at 3:25 AM, mykola-mokhnach <notifications@github.com<mailto:notifications@github.com>> wrote:


@mgeilich<https://github.com/mgeilich> you can temporarily workaround the problem by triggering direct calls to WDA. All you need to implement are elements location and dragfromtoforduration API call. Here<https://github.com/facebook/WebDriverAgent/tree/master/WebDriverAgentLib/Commands> is the full list of supported WDA commands and here<https://github.com/facebook/WebDriverAgent/wiki/Queries> you can find queries examples.

**Comment by dmydry** [comment]
Guys, same issue.

_Appium v1.6.0
appium-xcuitest-driver@2.0.29_

**Appium log:**
`[HTTP] --> POST /wd/hub/session/8fd36521-9ff3-4c13-a7d2-4fd3b9c2845b/touch/perform {"actions":[{"action":"press","options":{"x":20,"y":200}},{"action":"moveTo","options":{"x":20,"y":-200}},{"action":"release"}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
[debug] [XCUITest] Executing command 'performTouch'
[HTTP] <-- POST /wd/hub/session/8fd36521-9ff3-4c13-a7d2-4fd3b9c2845b/touch/perform 501 5 ms - 175`

**Error:**
`Error: Support for gestures other than Tap is not yet implemented. Please contact an Appium dev`

**Comment by mgeilich** [comment]
@dmydry, I found a way around the error message, though I haven’t seen the behavior actually work yet.  Try this:
                action.press(m).wait(3000).release().perform()

I found the answer here:
https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/gesture.js#L26

Read the commands.performTouch() function.  Only a few specific combinations of actions are allowed.

On Oct 20, 2016, at 8:08 AM, dmydry <notifications@github.com<mailto:notifications@github.com>> wrote:


Guys, same issue.

Appium v1.6.0
appium-xcuitest-driver@2.0.29

Appium log:
[HTTP] --> POST /wd/hub/session/8fd36521-9ff3-4c13-a7d2-4fd3b9c2845b/touch/perform {"actions":[{"action":"press","options":{"x":20,"y":200}},{"action":"moveTo","options":{"x":20,"y":-200}},{"action":"release"}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
[debug] [XCUITest] Executing command 'performTouch'
[HTTP] <-- POST /wd/hub/session/8fd36521-9ff3-4c13-a7d2-4fd3b9c2845b/touch/perform 501 5 ms - 175

Error:
Error: Support for gestures other than Tap is not yet implemented. Please contact an Appium dev

**Comment by dmydry** [comment]
@mgeilich not sure I've got your suggestion. I need a scroll, I'm using webdriver.io js framework for my testing workflow and my command looks like:
`client.touchPerform([{
          action: 'press',
          options: {
            x: x1,
            y: y1,
          },
        }, {
          action: 'moveTo',
          options: {
            x: x2,
            y: y2,
          },
        }, {
          action: 'release',
        }])`

I worked well before appium 1.6 and ios 10. Now it throws me this error. 
You recommended me to just press, wait and release. It makes no sense for me. Or I really didn't get the idea.

**Comment by mgeilich** [comment]
@dmydry, referring to the link to the source I sent previously:
https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/gesture.js#L26

it looks to me like perform() will accept the command if it is press/wait/moveTo/release.  Only a few combinations are accepted, and this is one of them.  For your specific case, look at helpers.isDrag().




On Oct 20, 2016, at 9:15 AM, dmydry <notifications@github.com<mailto:notifications@github.com>> wrote:


@mgeilich<https://github.com/mgeilich> not sure I've got your suggestion. I need a scroll, I'm using webdriver.io<http://webdriver.io> js framework for my testing workflow and my command looks like:
client.touchPerform([{
action: 'press',
options: {
x: x1,
y: y1,
},
}, {
action: 'moveTo',
options: {
x: x2,
y: y2,
},
}, {
action: 'release',
}])

I worked well before appium 1.6 and ios 10. Now it throws me this error.
You recommended me to just press, wait and release. It makes no sense for me. Or I really didn't get the idea.

**Comment by dmydry** [comment]
@mgeilich YES, thanks, already got it from source code here - https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/gesture.js

## FOR ALL WHO WANTS TO USE SCROLL IN APPIUM 1.6 AND IOS 10:
Please use the next example of actions sequence:
`[{
          action: 'press',
          options: {
            x: x1,
            y: y1,
          },
        }, {
          action: 'wait',
          options: {
            ms: 50,
          },
        }, {
          action: 'moveTo',
          options: {
            x: x2,
            y: y2,
          },
        }, {
          action: 'release',
        }]` 

Hope it will help you. I spent few hours to get this.

**Comment by mykola-mokhnach** [comment]
We just make direct calls to WDA API leaving Appium stuff (java lib and NodeJS backend) behind the scene to achieve full compatibility:

```java

    private static String parseResponseWithStatus(JSONObject response) throws StatusNotZeroError {
        if (response.getInt("status") == 0) {
            return response.get("value").toString();
        } else {
            throw new StatusNotZeroError(response.get("value").toString());
        }
    }

 public void dragFromToForDuration(String uuid, FBDragArguments FBDragArguments) throws RESTError, StatusNotZeroError {
        parseResponseWithStatus(client.dragFromToForDuration(getSessionId(), uuid, FBDragArguments));
    }

....

public class FBDragArguments {
    private double fromX;
    private double fromY;
    private double toX;
    private double toY;
    private double durationSeconds;

    public FBDragArguments(double fromX, double fromY, double toX, double toY, double durationSeconds) {
        this.fromX = fromX;
        this.fromY = fromY;
        this.toX = toX;
        this.toY = toY;
        DurationValidator.validate(durationSeconds);
        this.durationSeconds = durationSeconds;
    }

    public double getFromX() {
        return fromX;
    }

    public double getFromY() {
        return fromY;
    }

    public double getToX() {
        return toX;
    }

    public double getToY() {
        return toY;
    }

    public double getDurationSeconds() {
        return durationSeconds;
    }
}

....

    public JSONObject dragFromToForDuration(String sessionId, String uuid, FBDragArguments FBDragArguments)
            throws RESTError {
        final Builder webResource = buildDefaultRequest(
                String.format("uiaTarget/%s/dragfromtoforduration", uuid), sessionId);
        final JSONObject body = new JSONObject();
        body.put("fromX", FBDragArguments.getFromX());
        body.put("fromY", FBDragArguments.getFromY());
        body.put("toX", FBDragArguments.getToX());
        body.put("toY", FBDragArguments.getToY());
        body.put("duration", FBDragArguments.getDurationSeconds());
        return waitForResponse(() -> restHandlers.httpPost(webResource, body.toString(), new int[]{HttpStatus.SC_OK}));
    }


....

class DurationValidator {
    private static final double MAX_DURATION_VALUE = 60;
    private static final double MIN_DURATION_VALUE = 0.5;

    public static void validate(double actualValue) {
        if (actualValue < MIN_DURATION_VALUE || actualValue > MAX_DURATION_VALUE) {
            throw new IllegalArgumentException(String.format(
                    "Duration value is expected to be in range [%.2f seconds, %.2f seconds]. " +
                            "The actual duration value %.2f does not fit into this range.",
                    MIN_DURATION_VALUE, MAX_DURATION_VALUE, actualValue));
        }
    }
}

```

**Comment by shay777** [comment]
I having the same issue.
action.press(audio).waitAction(3000).release().perform();
I still getting this error message.
Any idea how to solve it?

**Comment by mgeilich** [comment]
@shay777 try this:
                action = TouchAction(self.driver)
                action.press(el,x,y).wait(delay).release().perform()

Notice that I’m using wait() instead of waitAction() and specifying x/y for the press.  This works for me.


On Oct 25, 2016, at 11:05 AM, shay777 <notifications@github.com<mailto:notifications@github.com>> wrote:


I having the same issue.
action.press(audio).waitAction(3000).release().perform();
I still getting this error message.
Any idea how to solve it?

**Comment by shay777** [comment]
@mgeilich Thanks for your comment.
If I use wait() then I cannot use release() or even perform() after it. I get a message that the methods cannot be resolve.
Anything I am missing there?

**Comment by mgeilich** [comment]
@shay777, I realize that you didn’t specify what language you are using for your tests.  My comments (and issues) were/are related to using the Python library for webdriver, if you are not using Python or have a different version of the library, your results may be different.  For my case, here is what webdriver is doing:

helpers.isTap = function (gestures) {

return (
        (gestures.length === 3 &&
        gestures[0].action === 'press' &&
        gestures[1].action === 'wait' &&
        gestures[2].action === 'release') ||
        (gestures.length === 1 && gestures[0].action === 'tap')
        );
        };



So from Python, you can either do press().wait().release().perform() or tap().perform().  Read the code here:
https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/gesture.js#L26



On Oct 26, 2016, at 2:34 AM, shay777 <notifications@github.com<mailto:notifications@github.com>> wrote:


@mgeilich<https://github.com/mgeilich> Thanks for your comment.
If I use wait() then I cannot use release() or even perform() after it. I get a message that the methods cannot be resolve.
Anything I am missing there?

**Comment by Nesaganesh** [comment]
Anyone over these issues  I have the similar problem not able to use driver.Tap(x,y);

Earlier version of Appium1.6beta was able to use driver.tap, but in beta 3, I am not able to do driver.tap

I tried Press, Moveto and Release this is just scrolling not click/tap

c# code
ITouchAction touchAction = new TouchAction(iosDriver);
            touchAction.Press(elementCenterX, elementCenterY).Wait(50).MoveTo(elementCenterX, elementCenterY).Release();
            iosDriver.PerformTouchAction(touchAction);

Also tried 

touchAction.Tap(elementCenterX, elementCenterY);
            iosDriver.PerformTouchAction(touchAction);


These are not working please can someone help ASAP.

**Comment by Nesaganesh** [comment]
I am now able to tap using the below command 

ITouchAction touchAction = new TouchAction(iosDriver);
touchAction.Tap(element, elementCenterX, elementCenterY);
iosDriver.PerformTouchAction(touchAction);

**Comment by dodigital** [comment]
Was able to slide on a UISlider. The important thing is to note that if your points are incorrect and especially if the starting X point is off that the knob of a UISlider, it won't work. I using the action below:

`WebElement slider = (new WebDriverWait(driver, 5).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//XCUIElementTypeSlider"))));
		
		int startingX = slider.getLocation().x + 14;
		int startingY = 347;		
		
		int endX = slider.getSize().width/2 + startingX;
		int endY = startingY;
		
		TouchAction move = new TouchAction(driver);
		move.press(startingX, startingY).waitAction(5000).moveTo(endX, endY).release().perform();`

**Comment by gitsaquib** [comment]
I am trying to tap assistive touch after launching app. 

driver = AppiumDriverFactory.get();
driver.rotate(ScreenOrientation.LANDSCAPE);
TouchAction touchAction = new TouchAction(driver);
touchAction.tap(40, 400);
driver.performTouchAction(touchAction);

Nothing is happening

**Comment by mykola-mokhnach** [comment]
@gitsaquib It's known XCTest issue. Landscape mode is not supported properly there: https://github.com/facebook/WebDriverAgent/issues/362
Although in since Appium 1.6.2 element clicks in landscape work as expected, since WDA itself has a workaround.

**Comment by gitsaquib** [comment]
Unfortunately, my app works only in LS mode

**Comment by anshushireen01** [comment]
Hi

I am trying to swipe/scroll on a ios on a app( not safari) using WebDriverAgent /appium ... but it says org.openqa.selenium.WebDriverException: Unhandled endpoint: /session/AE8B58EB-A899-4383-BFE4-32DB299BFEE2/touch/perform ...please help  appium1.6.4beta👍

**Comment by mgeilich** [comment]
How are you trying to swipe/scroll and what kind of element are you trying to hit?  If you’ve got the right element ID, something like this should work:

                action = TouchAction(self.driver)
                action.press(w,0,0).wait(1000).move_to(w,0,100).release().perform()


On Mar 13, 2017, at 2:27 AM, anshushireen01 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi

I am trying to swipe/scroll on a ios on a app( not safari) using WebDriverAgent /appium ... but it says org.openqa.selenium.WebDriverException: Unhandled endpoint: /session/AE8B58EB-A899-4383-BFE4-32DB299BFEE2/touch/perform ...please help appium1.6.4beta👍

**Comment by anshushireen01** [comment]
Ok, this is wat i tried: 
    	  TouchAction action = new TouchAction(driver); 
    	  WebElement w = driver.findElementByName("my text"); --- this returns a valid webelement , then 
action.press(w,0,0).waitAction(1000).moveTo(w,0,100).release().perform();

here i get error :
![image](https://cloud.githubusercontent.com/assets/26374405/23879347/8b6f88d6-08a0-11e7-892d-fc5134bf81f6.png)- please help

**Comment by vikramvi** [comment]
@anshushireen01 please open new issue with all the details per template.  sometimes comment on closed issue gets ignored / missed out
