### ISSUE TITLE
Not able to sendKeys to a email field in Appium Beta iOS 10

### ISSUE THREAD

**Issue by KranthiReddyK** [appium/appium#6837]
## The problem

Not able to send keys to a email field using sendKeys `driver.findElementById(EMAIL_FIELD_ID).sendKeys("1234");` 

## Environment

* Appium version `1.6.0-beta1`
* Mobile platform/version under test: iOS 10 
* Real device or emulator/simulator: *Simulator* iPhone 6S iOS 10

## Details

Tapping on the email field works but cannot input the data.

## Link to Appium logs

https://gist.github.com/KranthiReddyK/e0aa5671bb904ddf9ee6cadc72ad14a3

## Link to system logs

https://gist.github.com/KranthiReddyK/1ba512f2aa8284617f94b538633f6d7a

**Comment by skumar1122** [comment]
Hi , how did you managed to work with iOS 10 real devices ? does Appium version 1.6.0-beta1 supports it ?

**Comment by KranthiReddyK** [comment]
Im not using real device , just simulator.

**Comment by yaphatak** [comment]
@KranthiReddyK : I think you should give system log to facebook/WebDriverAgent. ITs failing on WDA side and appium wont be able to fix it.

**Comment by skumar1122** [comment]
@yaphatak 
Just to confirm above , will Appium version 1.6.0-beta works with iOS 10 devices for Automation now ?

**Comment by yaphatak** [comment]
@skumar1122 : Yes

**Comment by imurchie** [comment]
This will be fixed on our side. It's an argument mis-match thing. I have a fix in the works, just trying to get Travis to cooperate.

**Comment by KranthiReddyK** [comment]
Thx for the fix, @imurchie Will it be part of `npm install -g appium@beta` command or need to get it from master.

**Comment by KranthiReddyK** [comment]
@imurchie I still have the same issue.

## Not fixed Appium Logs

https://gist.github.com/KranthiReddyK/f33aba372d0f2cf240b623dcedf44db1

I have used the below commands to use master.

`git clone https://github.com/appium/appium.git`
`cd appium`
`npm install`
`node .`

I'm on latest master.

**Comment by imurchie** [comment]
Yes, it will be a little while before we can release it, because of slow CI. You can clone `appium-xcuitest-driver` and then link it. Or wait a little bit.

**Comment by KranthiReddyK** [comment]
Sorry, Just to confirm `appium-xcuitest-driver` should be a part `appium` master right. As mentioned above I still have the issue.

**Comment by imurchie** [comment]
There is a new release of `appium-xcuitest-driver` that fixes this issue.

**Comment by KranthiReddyK** [comment]
cool thanks

**Comment by imurchie** [comment]
You will need to update the dependencies if running from master. You can do `npm install appium-xcuitest-driver` to update just that one, or `rm -rf node_modules && npm install` in order to get all of them.
