### ISSUE TITLE
Appium touchAction bug

### ISSUE THREAD

**Issue by juhlila** [appium/appium#6838]
## The problem

Im using ruby client. (the latest)
I didnt update any gem, but lately I am getting this error a lot, and it was working fine for the last 3 months. Here is what Im doing

`Appium::TouchAction.new.tap(x: 386, y: 107, count: 9).perform`

the element is inside the bounds and its a clickable item
and the error is
`Selenium::WebDriver::Error::JavascriptError: tap point is not within the bounds of the screen
from /Users/julia/.rvm/gems/ruby-2.3.1/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/response.rb:70:in assert_ok'`

Yesterday this was working fine, today its not working at all, nothing was changed, only me has access to the code. 
its driving me crazy cause now my stable tests are not stable anymore because of fake fails

appium logs: https://gist.github.com/juhlila/fa0bc4f2420ffcfb0afe737e9d08a254
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3
- Desktop OS/version used to run Appium: ios 8
- Node.js version (unless using Appium.app|exe): 3.10.3
- Mobile platform/version under test: iphone 5s
- Real device or emulator/simulator: real device
- Appium CLI or Appium.app|exe: cli
## Description

When i click using javascript, it works

`execute_script 'UIATarget.localTarget().tap({x:386, y:107});'`

logs https://gist.github.com/juhlila/2ea6b10fca14abe6be1d48c88dc3aad4

**Comment by imurchie** [comment]
Can you provide the **full** server logs? It's difficult without context to tell anything.

**Comment by juhlila** [comment]
Here its the full log
https://gist.github.com/juhlila/8923af1dde5ba503b87fba67bb117cef

**Comment by imurchie** [comment]
Very strange. Apple is reporting that the bounds are negative:

```
[debug] [UIAuto] Sending command to instruments: UIATarget.localTarget().frontMostApp().rect()
[debug] [Instruments] [INST] 2016-09-15 19:00:09 +0000 Debug: Got new command 5 from instruments: UIATarget.localTarget().frontMostApp().rect()
[debug] [Instruments] [INST] 2016-09-15 19:00:09 +0000 Debug: evaluating UIATarget.localTarget().frontMostApp().rect()
[debug] [Instruments] [INST] 2016-09-15 19:00:09 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-09-15 19:00:09 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-09-15 19:00:09 +0000 Debug: Running system command #6: /usr/local/Cellar/node/6.5.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/k0/s803_jl52hvggnvg9sbdbbf00000gn/T/instruments_sock 2,{"status":0,"value":{"origin":{"x":-0.000010840424720461877,"y"...
[debug] [UIAuto] Socket data received (150 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":{"origin":{"x":-0.000010840424720461877,"y":-247.99998915957508},"size":{"width":320.0000248280692,"height":568.0000139876443}}}
```

So 

```
"origin": {
    "x" :-0.000010840424720461877,
    "y": -247.99998915957508
},
"size": {
    "width": 320.0000248280692,
    "height": 568.0000139876443
}
```

And then Appium does some math and comes out with something that is outside the bounds of the screen.

**Comment by imurchie** [comment]
Does this happen if you do the element retrieval through the normal means, instead of using `execute`?

**Comment by juhlila** [comment]
If you mean, click on the element, using `buttons[4].click`, it also works.
This is occurring on an iphone 5s, I was using touchAction on an iphone 6 and it was working

**Comment by saikrishna321** [comment]
@KazuCocoa ping

**Comment by KazuCocoa** [comment]
👍 

https://github.com/appium/ruby_lib_core/blob/9dc38d65a1c0d8975fc67a8274c1d2ebd43e7e5d/lib/appium_lib_core/device/touch_actions.rb#L92

Current `TouchAction#tap` doesn't change `x` and `y`. So, the client should pass `x` and `y` to the server and close this.
