### ISSUE TITLE
How to verify toast text

### ISSUE THREAD

**Issue by vpkhachane** [appium/appium#6840]
## The problem

I want automate android application , I have some test cases depends on toast . but i am not getting any proper way to handle them.  Prove me solution on it
## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v4.4.7
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/issues/4824

**Comment by SrinivasanTarget** [comment]
@triager please close
