### ISSUE TITLE
XPath locators working very slowly in Appium 1.6.0beta @ with XCUITest set as automationName

### ISSUE THREAD

**Issue by ptsiakos77** [appium/appium#6842]
## The problem

I switched to appium 1.6.0 beta and changed my xpath locators according to this link: http://masilotti.com/xctest-documentation/Constants/XCUIElementType.html.
 The elements are found by xpath strategy but the time required is very big (approximately 4 seconds to find and interact with an element) 
## Environment

Appium version (or git revision) that exhibits the issue: 1.6.0beta1
Last Appium version that did not exhibit the issue (if applicable): 1.5.3
Desktop OS/version used to run Appium: OSX El Capitan 10.11.6
Mobile platform/version under test: iOS 9.3
Real device or emulator/simulator: Simulator

**Comment by dilsreccse** [comment]
@ptsiakos77  / @imurchie : Hi, can you help me to understand how to use xpath with XCUIElement & grab elements with it ? i used to grap elements via Appium Inspector, now i have installed appium via terminal, one way is to get the page source & find the elements , but it is difficult to do grab, Any alternate methods ?

**Comment by mykola-mokhnach** [comment]
@dilsreccse You can try this Inspector implementation: https://github.com/mykola-mokhnach/Appium-iOS-Inspector

**Comment by mykola-mokhnach** [comment]
Regarding XPath queries performance - I think this is because of non-optimal XML library selection. One should try to replace it with something faster: https://github.com/facebook/WebDriverAgent/issues/306

**Comment by dilsreccse** [comment]
@mykola-mokhnach : i'm using appium 1.6 beta , how to use this   https://github.com/mykola-mokhnach/Appium-iOS-Inspector ?

**Comment by KrazySush** [comment]
@mykola-mokhnach 
Is it possible to automate hybrid apps on iOS 10- locating webview elements and performing normal actions like click, sendKeys, getText, etc?

**Comment by mykola-mokhnach** [comment]
@dilsreccse It does not matter which Appium version you use. Just start your test, put a breakpoint and open main inspector's HTML page in a browser.

**Comment by mykola-mokhnach** [comment]
@KrazySush Unfortunately, I cannot answer, since I only have experience automating native apps. But in theory this should work - it worth trying.

**Comment by KrazySush** [comment]
@mykola-mokhnach 
I have tried on iOS 10 simulator.
But after finding element in Webview (say **wd.findElementByXpath("something")**) whenever I try to use click() method, I am getting exception as "**Method not implemented yet**". 
Not getting any reference link for this. So still confused about support for hybrid apps with Xcode 8, iOS 10.
It will be great if anyone can help on this.

**Comment by mykola-mokhnach** [comment]
@KrazySush  Rather try something like this:

```java
By locator = By.xpath("//someting");
driver.findElement(locator).click();
```

**Comment by dilsreccse** [comment]
@mykola-mokhnach : how to install this  https://github.com/mykola-mokhnach/Appium-iOS-Inspector ?

**Comment by mykola-mokhnach** [comment]
@dilsreccse No, just clone the repository.

**Comment by dilsreccse** [comment]
@mykola-mokhnach  - i cloned the repository by running the command in terminal git clone git@github.com:mykola-mokhnach/Appium-iOS-Inspector.git then how can i access it , my AppiumIpPort=http://0.0.0.0:4723 , how to proceed further ?

**Comment by mykola-mokhnach** [comment]
There is a readme file there. Just start your test, put a breakpoint there ,and open inspector's html page when the breakpoint is reached in any browser.

**Comment by dilsreccse** [comment]
@mykola-mokhnach : Got it :) its working 👍

**Comment by pri1012** [comment]
@mykola-mokhnach  is there a soultion for the xpath locator being slow? I am currently using Appium 1.6.1 Beta Version[c# Client Library]

**Comment by mykola-mokhnach** [comment]
@pri1012 my fix is still being tested by FB team and has not been merged to master yet. You can apply the patch yourself if you need it right now or you can wait until it is fully tested by FB and merged to the mainstream,

**Comment by pri1012** [comment]
@mykola-mokhnach thanks for the update.How to use your code?could you please provide the steps

**Comment by qamonstir** [comment]
I have the same question as @pri1012. How can we use your code @mykola-mokhnach ? And when it planned to be merged in master?

**Comment by mykola-mokhnach** [comment]
@qamonstir wait for Appium release 1.6.2

**Comment by qamonstir** [comment]
@mykola-mokhnach thanks

**Comment by RashmiMurthy** [comment]
@mykola-mokhnach : XPath locators working very slowly even in Appium 1.6.3

**Comment by mykola-mokhnach** [comment]
@RashmiMurthy it might be because of https://github.com/facebook/WebDriverAgent/issues/372

You may try to apply the workaround I proposed there and see whether it makes your xpath search faster. Nothing else we can do there.

**Comment by fedorc** [comment]
I have the same issue with locating element with Native: xpath, className and WebView: css

my metrics(in milliseconds):
```    WebView findByCss
Find regular element by css = 48246
Find element in element time = 105861
Send keys time = 135278
Is enabled time = 135642
Click time = 146527
```
```    Native findByXpath
Find regular element by css = 51252
Find element in element time = 59121
Send keys time = 101749
Is enabled time = 103388
Click time = 119801
```
```    Native findByClassName
Find regular element by css = 54908
Find element in element time = 70380
Send keys time = 94436
Is enabled time = 95807
Click time = 107137
```

**Comment by mykola-mokhnach** [comment]
Closing this for now. WDA has changed visibility detection strategy and xpath location cannot be technically much faster than it is now (unless Apple change something for it in XCTest). Also ClassChain location has been introduced recently in order to minimise xpath usage.

**Comment by findmanish** [comment]
@mykola-mokhnach @dilsreccse @KrazySush @pri1012 
Guys facing issue to launch the iOS app where running code from windows machine
 with Appium 1.6.5
iOS 10.3.3
Xcode 8.3.3
Please help me out with any document related to so that i can follow.I am a new learner in #appium-ios-driver
