### ISSUE TITLE
continue with security warning on android browser

### ISSUE THREAD

**Issue by jayantsarda** [appium/appium#6843]
Appium Version: 1.5.3
Android :4.4.2
Browser: Android Browser (Browser)

I have the same issue as posted in thread : https://discuss.appium.io/t/bypass-security-warning-popups-in-mobile-web-browser-testing-mobile-web-app/11551

When i try to access https site, i get security warning. These warning can be suppressed manually if i go to 
browser -> Settings -> privacy and Security -> show Security warning and un check it.
But when i run my automation this check box is checked again.

I have tried adding below capabilities: 
cap.setCapability(MobileCapabilityType.ACCEPT_SSL_CERTS, true); or
cap.setCapability("autoAcceptAlerts", true);
 but did not help.

There could be 2 possible solution acceptable in may case:
1. I do this setting in my emulator and My automation browser takes that in to account (this was working when i was on appium 1.4.13)
2. If i can have some capabilities which helps me getting rid of these warning.

Although preferable solution could be some thing with capabilities

Note: cap.setCapability(MobileCapabilityType.ACCEPT_SSL_CERTS, true); did work in case of chrome browser

Thanks in advance for the help

**Comment by jayantsarda** [comment]
any update on above query?

**Comment by dpgraham** [comment]
I don't think we have the ability to do this with programmatically. If the certificate isn't accepted on the device you have to set the SSL Cert to be accepted in the device settings.
