### ISSUE TITLE
[MJSONWP] Encountered internal error running command: Error: Removing com.example.apple-samplecode.UICatalog failed.

### ISSUE THREAD

**Issue by Moidul** [appium/appium#6844]
## The problem
Appium server is not able to install or uninstall to\from the ios divice

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: Apple Mac Pro - OS X EI Captain Version 10.11.6 (15G31)
* Node.js version (unless using Appium.app|exe): 6.5.0
* Mobile platform/version under test: iOS 9.3.5
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Details

I am trying to run the Appium inspector for the sample app UICatalog. It was working yesterday and suddenly not working from today. following things are already checked
- Enable UI Automation flag is set to true,
- The ipa is checked by manually installed to the test device through iTune and working correctly.
- Appium server restarted 
- Desktop machine restrted.

## Link to Appium logs

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --address "127.0.0.1" --debug-log-spacing --platform-version "8.1" --platform-name "iOS" --app "/Users/hasanm/Developments/appium/uicatalog/build/UICatalog/UICatalog/UICatalog.ipa" --udid "2906c87b1e914dc54f3e451ff832a170c3c1159a" --full-reset --device-name "iPhone 6 Plus"

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:

[Appium]   address: '127.0.0.1'
[Appium]   debugLogSpacing: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '8.1'
[Appium]   deviceName: 'iPhone 6 Plus'
[Appium]   app: '/Users/hasanm/Developments/appium/uicatalog/build/UICatalog/UICatalog/UICatalog.ipa'
[Appium]   udid: '2906c87b1e914dc54f3e451ff832a170c3c1159a'
[Appium]   fullReset: true
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"8.1"}'
[Appium]   --device-name => --default-capabilities '{"deviceName":"iPhone 6 Plus"}'
[Appium]   --app => --default-capabilities '{"app":"/Users/hasanm/Developments/appium/uicatalog/build/UICatalog/UICatalog/UICatalog.ipa"}'
[Appium]   -U,--udid => --default-capabilities '{"udid":"2906c87b1e914dc54f3e451ff832a170c3c1159a"}'
[Appium]   --full-reset => --default-capabilities '{"fullReset":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '8.1'
[Appium]   deviceName: 'iPhone 6 Plus'
[Appium]   app: '/Users/hasanm/Developments/appium/uicatalog/build/UICatalog/UICatalog/UICatalog.ipa'
[Appium]   udid: '2906c87b1e914dc54f3e451ff832a170c3c1159a'
[Appium]   fullReset: true

[Appium] Appium REST http interface listener started on 127.0.0.1:4723

[HTTP] --> GET /wd/hub/status {}

## Code To Reproduce Issue [ Good To Have ]

N/a

**Comment by Moidul** [comment]
It is working now after executing the following command. 

_sudo chmod -R 777 /var/db/lockdown/_

But not to sure is it a correct way to resolve this issue or not. Thanks.

**Comment by HItesh007** [comment]
I was facing the same issue since yesterday and after a lot of research, it was a dead end.

But @Moidul , **That fix you have mentioned solved the issue.**

Thank You Man. It saved my day.

**Comment by jlipps** [comment]
I'm guessing it's a result of downloading the new itunes or xcode?

**Comment by HasaanAli** [comment]
Didn't work for me. :(

**Comment by aqell22** [comment]
I'm still having trouble with this particular issue. 
ERROR: 
**MJSONWP] Encountered internal error running command: Error: Command failed: ideviceinstaller -u 3BE0413A-B950-493B-9FFA-A48C8C995B3B -U alix.julian.isItPrime2

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)**

I ran the command **"sudo chmod -R 777 /var/db/lockdown/**
I even managed to uninstall homebrew and reinstalling then unlinking/linking the ideviceinstaller 
brew unlink ideviceinstaller
brew link ideviceinstaller

Still no luck any suggestions ?

**Comment by imurchie** [comment]
@aqell22 What if you run the command on its own, on the command line: ` ideviceinstaller -u 3BE0413A-B950-493B-9FFA-A48C8C995B3B -U alix.julian.isItPrime2`.

**Comment by aqell22** [comment]
When i run the command on its own i get this

Alixs-MacBook-Air:~ alixedwards$ ideviceinstaller -u 3BE0413A-B950-493B-9FFA-A48C8C995B3B -U alix.julian.isItPrime2
ERROR: Invalid UDID specified
Usage: ideviceinstaller OPTIONS
Manage apps on iOS devices.

**Comment by imurchie** [comment]
And is the udid you supplied the udid of the device? Is the device plugged in?

**Comment by aqell22** [comment]
It's a device from the simulator on Xcode I actually copied it from the list of devices they gave when I was first getting an error for locating a particular device. Does the situation change seeing as I'm using the simulator instead of an actual device?  I'll try and go into the Device Manager and copy it and try it again.

**Comment by imurchie** [comment]
What version of Appium are you using? `ideviceinstaller` _only_ works on real devices. For some reason Appium thinks that you are running against one.

**Comment by aqell22** [comment]
Ah okay and I'm using Version 1.5.3 (Ara)

**Comment by aqell22** [comment]
I have run apps from Xcode to my iPhone before, could that also be it ?

**Comment by imurchie** [comment]
Hm. I'm pretty certain that Appium 1.5.3 does not allow you to specify the exact iOS simulator you want to run against, just the type.

**Comment by aqell22** [comment]
Are there any versions that allow this or do I have to use a real device?

**Comment by imurchie** [comment]
1.6 does this, for 10.x tests. But specifying the `platformName`, `platformVersion`, and `deviceName` correctly will get you the right simulator on any version of appium.

**Comment by aqell22** [comment]
Okay, I'll give it a try now and get back to you !

**Comment by imurchie** [comment]
If it remains a problem, please start a new issue. This is unrelated to the current issue.

**Comment by aqell22** [comment]
You are a lifesaver, I kept the version at 8.3 because I saw that in most of the tutorials I was watching to try and fix it. Could have saved me a couple hours if I just tried but thank you so much!
