### ISSUE TITLE
xCode 8 issue

### ISSUE THREAD

**Issue by 03623170** [appium/appium#6845]
## The problem
Since the update on Xcode 8 I am neither able to run the inspector nor can start any test scripts. 

## Environment

* Appium version (or git revision) that exhibits the issue: v.1.5.3
* Last Appium version that did not exhibit the issue (if applicable):v.1.5.3
* Desktop OS/version used to run Appium: El Capitan 
* Mobile platform/version under test: iOS 9.3.5
* Real device or emulator/simulator: iPhone 6 Plus (real)

## Details

I guess this is the missing ui-instruments in xcode8 how will appium handle this? 

## Link to Appium logs

[Xcode] Could not find Automation.tracetemplate in any of the followinglocations /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate,/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate
[Xcode] Could not find Automation.tracetemplate in any of the followinglocations /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate,/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate
[MJSONWP] Encountered internal error running command: Error: Could not find Automation.tracetemplate in any of the followinglocations /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate,/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate
    at getAutomationTraceTemplatePathWithoutRetry$ (lib/xcode.js:172:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by jlipps** [comment]
The only version of Appium that will work with xcode 8 is 1.6.0. You can download the beta now. Instruments/UIAutomation have been removed and only Appium's XCUITest support will work moving forward.

**Comment by jlipps** [comment]
See https://github.com/appium/appium/blob/master/CHANGELOG.md#changes-in-version-160-beta-1-from-153 for more info

**Comment by pavanbachu0604** [comment]
@jlipps When is appium expected to release complete version of appium 1.6 with full support to real devices ?

**Comment by jlipps** [comment]
@pavanbachu0604 Appium 1.6 beta already supports real devices. cc @yaphatak, I think there are some additional instructions for using them, maybe.

**Comment by 03623170** [comment]
That means, that we have to refractor all our test scripts written in java to Swift for XCUITest, don't we?

**Comment by jlipps** [comment]
No. Appium supports XCUITest as an automation backend, the same way it supported Instruments/UIAutomation before. You shouldn't need to update your tests (unless you use XPath, because those locators will all be different on the new scheme).

**Comment by skumar1122** [comment]
Appium 1.6 beta doesn't support real devices ...
refer for more details -----  #6597

**Comment by pavanbachu0604** [comment]
@jlipps Can you please mention what are the special instructions that needs to be followed for using appium 1.6 beta on real devices. The added the following capabilities : 
capabilities.setCapability("platformVersion", "10.0");
capabilities.setCapability("deviceName", "iPad");
capabilities.setCapability("platform", "iOS");
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("app", "com.vzw.pos.native");
driver.set(new IOSDriver(new URL("http://localhost:4723/wd/hub"),capabilities));

I am getting the error : simctl error , unable to 'create'

**Comment by jlipps** [comment]
@skumar1122 well I believe it is working for some people, so I suggest continuing to follow up on that thread to get help. My understanding could be off on that though.

@pavanbachu0604 this thread is not a good place to get help for that. I would suggest beginning by reading the docs about real devices. Automating a real device always requires the `udid` capability.

**Comment by pavanbachu0604** [comment]
@jlipps : here is appium log https://gist.github.com/pavanbachu0604/6eddaf82771794f0087e7dcf04a15d46; it is throwing an error about the web driver agent. Please have a look into logs

**Comment by jlipps** [comment]
@pavanbachu0604 i'm not sure how to advise on signing WDA correctly. it is also not related to this issue, so please ask for help in a related issue or create a new one of your own

**Comment by 03623170** [comment]
@pavanbachu0604 the docu says that the WebDriver should have the same signed provisioning profile as the .ipa. I am not sure if that might helped you.

**Comment by pavanbachu0604** [comment]
@03623170 I understand that , but I am curious how i get both of them under same provisioning profile

**Comment by yaphatak** [comment]
can u try this 
https://github.com/appium/appium-xcuitest-driver/issues/106. You don't need to have same provisioning profile as your app. You just need to have dev provision profile and has to be installed on device

**Comment by pavanbachu0604** [comment]
@yaphatak : I have the provisioning profile still I am facing the isssue Signing the WebDriver Agent #6846

**Comment by srkannan** [comment]
Can someone point me to the location from where I can download Appium 1.6?

**Comment by imurchie** [comment]
Use ' npm install -g appium@beta'

**Comment by zhaodazhou** [comment]
The Xcode8's Instruments not contain UIAutomation, I guess Apple not support UIAutomation any more. The XCUITest will replace it.

**Comment by nareshkc** [comment]
Hi I downloaded Appium 1.6 beta, how can i run, can anybody explain next steps...what i need to do

**Comment by skumar1122** [comment]
follow these steps - #6854

**Comment by nareshkc** [comment]
@skumar1122 Thank you....let me try and update

**Comment by j0hnsa** [comment]
Hello,

Im facing the same issue with an app that was provisioned for iOS9 that used to work for UIAutomation but since the update on iOS that forced me to install Xcode8 returns this error:
[Xcode] 
Testing failed:
	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.

[Xcode] 	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'

This app must be re-built to run on a real iOS10 device?

I'm using appium 1.6.1beta with Xcode 8.

Thanks in advance for the attention

**Comment by rmont881** [comment]
@j0hnsa https://github.com/appium/appium-xcuitest-driver <-- Go down to `Real Devices`. You need to set a development team and code signing identity for `appium-xcuitest-driver`. Make sure you set it for both `WebDriverAgentLib` and `WebDriverAgentRunner` if you go the manual route.

**Comment by rkn411** [comment]
016-12-09 16:24:28:625 - [MJSONWP] Encountered internal error running command: Error: Could not find Automation.tracetemplate in any of the followinglocations /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate,/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate
    at getAutomationTraceTemplatePathWithoutRetry$ (lib/xcode.js:172:9)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by rkn411** [comment]
getting issue with iOS10.11,xcode 8.1,appium 1.6beta

**Comment by vikramvi** [comment]
@rkn411 please open new issue with all the necessary details per issue template. Updating closed issue won't be of much use

**Comment by imurchie** [comment]
Also search the old issues for pertinent ones. This one is well-known.
