### ISSUE TITLE
Unable to install iOS app on real device after updating to Xcode 8.0 and ITunes 12.5.1

### ISSUE THREAD

**Issue by nan2806** [appium/appium#6848]
Appium 1.5.3
iPhone OS 8.1

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --session-override --debug-log-spacing --platform-version "8.1" --platform-name "iOS" --default-device --launch-timeout "90000" --native-instruments-lib

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:

[Appium] sessionOverride: true

[Appium] defaultDevice: true
[Appium] debugLogSpacing: true
[Appium] platformName: 'iOS'
[Appium] platformVersion: '8.1'
[Appium] nativeInstrumentsLib: true

[Appium] Deprecated server args:
[Appium] --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium] --platform-version => --default-capabilities '{"platformVersion":"8.1"}'
[Appium] --native-instruments-lib => --default-capabilities '{"nativeInstrumentsLib":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

[Appium] platformName: 'iOS'

[Appium] platformVersion: '8.1'
[Appium] nativeInstrumentsLib: true

[Appium] Appium REST http interface listener started on 0.0.0.0:4723

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 17 ms - 83

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 21 ms - 83

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"deviceName":"MO004","udid":"de9a026a526de3b6a8f5b3f91fa7f9ad4dc0804f","app":"/Users/qateam/Desktop/GTS/GTS 12.app","waitForAppScript":"‘$.delay(3000); true’","platformVersion":"8.1","platformName":"iOS"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"MO004","udi...

[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium] deviceName: 'MO004'
[Appium] udid: 'de9a026a526de3b6a8f5b3f91fa7f9ad4dc0804f'
[Appium] app: '/Users/qateam/Desktop/GTS/GTS 12.app'
[Appium] waitForAppScript: '‘$.delay(3000); true’'
[Appium] platformVersion: '8.1'
[Appium] platformName: 'iOS'
[Appium] nativeInstrumentsLib: true

[BaseDriver] Session created with session id: b7765de1-4979-4da7-9f27-e46b51422080
[debug] [iOS] Not auto-detecting udid.
[BaseDriver] Using local app '/Users/qateam/Desktop/GTS/GTS 12.app'
[debug] [iOS] Removing any remaining instruments sockets

[debug] [iOS] Cleaned up instruments socket /var/folders/7y/x200fww90hv1p63j03mldd_r0000gn/T/instruments_sock
[debug] [iOS] No language specified. Using default strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!
[debug] [ios-app-utils] Getting bundle ID from app

[iOS] Extracted bundleID: com.amosenterprise.gtsfr from app: /Users/qateam/Desktop/GTS/GTS 12.app
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/qateam/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/7y/x200fww90hv1p63j03mldd_r0000gn/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

[debug] [UIAuto] Dynamic bootstrap path: /Users/qateam/Library/Application Support/appium/bootstrap/bootstrap-19f3a156f474ff38.js
[debug] [UIAuto] Reusing dynamic bootstrap: /Users/qateam/Library/Application Support/appium/bootstrap/bootstrap-19f3a156f474ff38.js

[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'

[debug] [iOS] Creating iDevice object with udid de9a026a526de3b6a8f5b3f91fa7f9ad4dc0804f

[debug] [iOS] App is not installed. Will try to install.

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Encountered internal error running command: Error: Command failed: ideviceinstaller -u de9a026a526de3b6a8f5b3f91fa7f9ad4dc0804f -i "/Users/qateam/Desktop/GTS/GTS 12.app"

at ChildProcess.exithandler (child_process.js:202:12)
at emitTwo (events.js:100:13)
at ChildProcess.emit (events.js:185:7)
at maybeClose (internal/child_process.js:850:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:90:13)
at Socket.emit (events.js:182:7)
at Pipe._onclose (net.js:475:12)

https://discuss.appium.io/t/unable-to-install-ios-app-on-real-device-after-updating-to-xcode-8-0-and-itunes-12-5-1/12192?u=nan2806

**Comment by 03623170** [comment]
might be related: https://github.com/appium/appium/issues/6845#

**Comment by imurchie** [comment]
Appium 1.5.3 will **not** work with Xcode 8. The automation system has changed.

You can try 1.6.0-beta1 (`npm i -g appium@beta`). See https://github.com/appium/appium-xcuitest-driver#external-dependencies for the dependencies, and use `automationName` capability set to `XCUITest`.
