### ISSUE TITLE
adb shell ps uiautomator: bad pid uiautomator

### ISSUE THREAD

**Issue by Pitel** [appium/appium#6850]
## The problem

I'm just trying to learn Appium with Android native device
## Environment
- Appium version (or git revision) that exhibits the issue: v1.5.3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Ubuntu 16.04
- Node.js version (unless using Appium.app|exe): 6.6.0
- Mobile platform/version under test: Android 7
- Real device or emulator/simulator: Real Nexus 5X
- Appium CLI or Appium.app|exe: CLI
## Details

I'm just starting to learn Appium, so I'm writing some JS code from examples, but can't connect to my device.
## Link to Appium logs

https://gist.github.com/Pitel/2970b0d7aef7f6441208495979c7f17f
## Code To Reproduce Issue [ Good To Have ]

``` javascript
"use strict";

let server = {
    host: 'localhost',
    port: 4723
};

let android = {
    platformName: 'Android',
    deviceName: 'Android',
    appPackage: 'cz.master.lois'
};

let driver = require("wd").promiseChainRemote(server);

driver.init(android).setImplicitWaitTimeout(3000);

driver.quit();
```

**Comment by Pitel** [comment]
It works on Android 6.0 (Nexus 4 with CyanogenMod 13)

**Comment by imurchie** [comment]
This has been fixed.
