### ISSUE TITLE
Parameters were incorrect. We wanted {"required":["using","value"]} and you sent ["using","value",":id"]

### ISSUE THREAD

**Issue by Propeller-SV** [appium/appium#6851]
## The problem

I'm using Codeception and Appium.app on MacOS. When I try to select option with:
`$I->selectOption('//*[@id="select-id"]', array('text' => 'Sample'));`

in results I see this error:

```
[Facebook\WebDriver\Exception\WebDriverException] JSON decoding of remote response failed.
Error code: 4
The response: 'Parameters were incorrect. We wanted {"required":["using","value"]} and you sent ["using","value",":id"]'
```
## Environment
- Appium version that exhibits the issue: 1.5.3
- Desktop OS/version used to run Appium: MacOS 10.11.6
- Mobile platform/version under test: iOS 9.3
- Real device or emulator/simulator: simulator
- Codeception: 2.2.4
## Link to Appium logs

https://gist.github.com/Propeller-SV/8f2ab41b507d03c70ee6dd963c2a975d

**Comment by imurchie** [comment]
For some reason your test runner is sending `:id` as a parameter. It should not.

**Comment by Propeller-SV** [comment]
Ok, first issue can be solved like this:
```
$I->click('default'); // default selected value
$I->click(['xpath' => '//*[@id="select-id"]//option[contains(.,"Sample")]']);
```
But I have another one
```
$I->fillField('#selector', 'Tester');
```
result
```
[Facebook\WebDriver\Exception\WebDriverException] JSON decoding of remote response failed.
Error code: 4
The response: 'Parameters were incorrect. We wanted {"required":["value"]} and you sent ["value",":id"]'
```

**Comment by imurchie** [comment]
This remains the same problem. The test runner is adding an `:id` parameter that should not be there.
