### ISSUE TITLE
Switch Off Wifi and relaunch app using same session

### ISSUE THREAD

**Issue by gitsaquib** [appium/appium#6852]
## The problem

We have a requirement for sending app in background and switching off wifi and calls app back in foreground 
1. We are unable to send app in background and resume the same afterwards
2. Unable to switch off wifi

**Comment by dpgraham** [comment]
Doubtful that we'll be able to implement this (I don't think it's possible), but we can keep tracking this in the event that a future testing framework supports this feature.

**Comment by mykola-mokhnach** [comment]
Session restore implementation is a complicated topic, because we never know the final flow state in this scenario. I don't think it is ever going to be implemented. It would be easier and more practical just to restart the session on the client side with noReset capability set to true.
