### ISSUE TITLE
iOS 10 Real devices fix 

### ISSUE THREAD

**Issue by skumar1122** [appium/appium#6854]
## The problem

Failed to run on real device Safari testing.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0-beta1
- Desktop OS/version used to run Appium: 10.11.6 
- Mobile platform/version under test: iOS 10.0
- Real device or emulator/simulator: Real Device (iPhone6Plus)
- Xcode 8
## Details

Steps followed:

[sudo ]npm install -g appium@beta (honestly might be better off pulling from source for latest...)
sudo chmod 777 /var/db/lockdown (from libimobiledevice/libimobiledevice#356)
brew uninstall ios-webkit-debug-proxy (follow the instructions here https://github.com/google/ios-webkit-debug-proxy for building from source)
brew install --HEAD && brew install ios-webkit-debug-proxy 
brew uninstall libimobiledevice && brew install --HEAD libimobiledevice
brew install usbmuxd
brew install carthage (WDA project uses this)
https://github.com/appium/appium-xcuitest-driver#usage -- ensure deviceconsole is pulled down, compiled, and realDeviceLogger referenced in your appium capabilities
Clone WebDriverAgent from source and replace the one provided in the npm appium dependency
https://github.com/facebook/WebDriverAgent/wiki/Common-Issues -- ensure the provisioning profile or team is set on the WDA project to match your project
Make sure you can run (without errors):

idevicepair pair (Hit 'Trust' on device)
idevicepair validate
ios_webkit_debug_proxy --debug (just make sure this runs without error then you can ctrl+c)
Modify appium capabilities to include:

platformVersion: '10.0'
automationName: 'XCUITest'
realDeviceLogger: <path/to/deviceconsole> (requires you to run make after pulling down deviceconsole repo)
## Appium logs

WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: real device safari support not yet implemented. Contact an appium dev

**Comment by yaphatak** [comment]
@skumar1122 : Do you have `SafariLauncher` installed on ios 10 real device? If Yes can you give a try with this change https://github.com/appium/appium-xcuitest-driver/pull/158?

**Comment by Can-too** [comment]
Using the same installation is causing the message as above "real device safari support not yet implemented. Contact an appium dev"

What may or may not be interesting, is that the pervious devices running under iOS 9.3.5 are also not working and have the same error produced.

A portion of the log is below - hopefully this is helpful? : 

`2016-09-19 02:10:09:208 - error: [XCUITest] Error: real device safari support not yet implemented. Contact an appium dev
 at XCUITestDriver.start$ (lib/driver.js:178:15)
 at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
 at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
 at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
 at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: real device safari support not yet implemented. Contact an appium dev
 at XCUITestDriver.start$ (lib/driver.js:178:15)
 at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
 at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
 at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
 at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
2016-09-19 02:10:09:208 - info: [debug] [XCUITest] Resetting simulator
2016-09-19 02:10:09:210 - error: [MJSONWP] Encountered internal error running command: Error: real device safari support not yet implemented. Contact an appium dev
 at XCUITestDriver.start$ (lib/driver.js:178:15)
 at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
 at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
 at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
 at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)`

**Comment by skumar1122** [comment]
@yaphatak 
I couldn't do : brew install --HEAD ios-webkit-debug-proxy , so i have to try to uninstall and installed master ios-webkit-debug-proxy again and still the same error.

**Comment by ThilakBP** [comment]
HI Guys,

I am working on appium 1.6.3,xcode 8.1 and simulator 10.1.
There is an scenario in my application.
when click on forgot password link and pop window is displayed with email address field.
I am able to get the id for email id using accessibility inspector.
But when i run my java code its throwing an error as 

org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.22 seconds

Thanks in advance
Thilak BP

**Comment by pavanbachu0604** [comment]
Did you try using the driver.getPageSource() and checking if the particular Xpath is present ?

**Comment by ThilakBP** [comment]
Thankd for the response pawan ,i have tried using page source,in page source its showing the value as 
**<XCUIElementTypeTextField name="" label="" value="Email or Phone" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/2/0/0/1/0/0/2/0/0/0/0" x="73" y="345" width="229" height="17">
</XCUIElementTypeTextField>**

and ios inspector xpath:
<img width="777" alt="screen shot 2017-01-17 at 11 43 10 am" src="https://cloud.githubusercontent.com/assets/24888980/22009587/3860b542-dcaa-11e6-8f43-8c5238958ed1.png">

**Comment by ThilakBP** [comment]
<XCUIElementTypeTextField name="" label="" value="Email or Phone" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/2/0/0/1/0/0/2/0/0/0/0" x="73" y="345" width="229" height="17">
                                                        </XCUIElementTypeTextField>

**Comment by jlipps** [comment]
@ThilakBP what you're bringing up is unrelated to this issue. Please create a new issue with your details if you want us to look into it. Thanks for hopping in @pavanbachu0604.

**Comment by aroramayank2002** [comment]
I got following error with this command:
brew install --HEAD && brew install ios-webkit-debug-proxy

Error: Invalid usage: This command requires a formula argument

**Comment by imurchie** [comment]
@aroramayank2002  Just use `brew install ios-webkit-debug-proxy --HEAD`

**Comment by aroramayank2002** [comment]
Now another: I could start webkit proxy, appium server and launch the test but got following exception in appium server which pointed to the log file:
Session-WebDriverAgentRunner-2017-03-13_162347-OYcXyh.log

Error in log file:
Test operation failure: Launch session expired before checking in.

Error in appium server console logs:
[Xcode] 2017-03-13 16:23:47.777 xcodebuild[77383:14221282] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/mayank.arora/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fbe43992990 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2017-03-13 16:23:47.777 xcodebuild[77383:14221282] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **

**Comment by imurchie** [comment]
That is a code signing issue. Please see https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

**Comment by swachhab** [comment]
Please validate if your setup is fully installed, Check this link for whole setup:
https://mobileautotools.wordpress.com/appium-setup-for-ios-10/
