### ISSUE TITLE
Real Device Safari support in xcuitest-driver

### ISSUE THREAD

**Issue by imurchie** [appium/appium#6855]
We have not yet implemented support for real device web testing...

**Comment by dilsreccse** [comment]
@imurchie  is that possible to use Safarilauncher in appium v1.6 beta2 to automate the safari web application?

**Comment by imurchie** [comment]
There is no longer any need to SafariLauncher. Safari testing on real device ought to work now.

**Comment by dilsreccse** [comment]
@imurchie is that can be possible with appium v1.6 beta ? if yes how to proceed with it ?

**Comment by imurchie** [comment]
I don'd understand the question. To automate Safari with 1.6.0 beta, just use `Safari` as `browerName`.

**Comment by dilsreccse** [comment]
@imurchie thnx it worked :)

**Comment by hungnguyen201087** [comment]
Sorry, I used dotnet to make up the below DesiredCapabilities:
DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.SetCapability("platformName", "ios");
            capabilities.SetCapability("platformVersion", "10.2");
            capabilities.SetCapability("platform", "Mac");
            capabilities.SetCapability("deviceName", "iPhone 7 Plus");
            capabilities.SetCapability("automationName", "XCUITest");
            capabilities.SetCapability("browerName", "Safari");
            //Connecting to Appium Server
            Uri serverUri = new Uri("http://127.0.0.1:4723/wd/hub");
            driver = new IOSDriver<IOSElement>(serverUri, capabilities, TimeSpan.FromSeconds(120));
            //driver = new RemoteWebDriver(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities);
            driver.Manage().Timeouts().ImplicitlyWait(TimeSpan.FromSeconds(120));

Then I get error: System.InvalidOperationException : An unknown server-side error occurred while processing the command. Original error: The desired capabilities must include either an app or a bundleId for iOS

Could you help to correct my DesiredCapabilities to make open Safari browser in IOS simulator or real device?
Thanks

**Comment by hungnguyen201087** [comment]
Oh sorry, I resolved this issue. Just fix 'browerName' to 'browserName', typo issue, my bad.
It works now.

**Comment by amiteshri92** [comment]
@imurchie
Is it not implemented yet for safari with xcuitest-driver?

**Comment by imurchie** [comment]
@amiteshri92 What is "it" in your question? Safari works perfectly fine with `appium-xcuitest-driver`.
