### ISSUE TITLE
Document lack of 'location' endpoint in xcuitest, submit feature request to apple

### ISSUE THREAD

**Issue by imurchie** [appium/appium#6856]
Currently it gets proxied to WDA, which doesn't handle it at all.

See https://github.com/appium/appium/issues/6853#issuecomment-247618099

**Comment by danqa** [comment]
Hi @imurchie Hope all is well. Any eta on this issue. I'm blocked until this is fixed. I know you got tons of stuff going on. Just hoping to get a ball park figure. Thanks in advance.

**Comment by steve-gray** [comment]
@imurchie, is the intention to try and get WDA to support this? They closed down discussions pretty quickly when someone asked about this capability before:

- https://github.com/facebook/WebDriverAgent/issues/218

Is there some command-line based way to work around this temporarily? Keen to avoid a full-on XCode rollback.

-Steve

**Comment by jlipps** [comment]
This is just not supported in XCUITest. New acceptance criteria for closing this:

* [ ] `/location` endpoint returns 501 NYI instead of attempting to proxy
* [ ] radar/openradar filed requesting this feature, crosslinked to worms repo
* [ ] appium docs updated to mention lack of this feature

**Comment by imurchie** [comment]
https://github.com/appium/worms/issues/5
