### ISSUE TITLE
Appium.app not launching IOS App 

### ISSUE THREAD

**Issue by nuggit32** [appium/appium#6857]
## The problem

Unable to start IOS app with Appium.app.    This just started to occur, and I think it might have started when the IOS upgrade from 9.3.4 to 9.3.5.  This is the only thing I can recall has changed.  Other people have seen this issue lately as well. 
https://discuss.appium.io/t/why-the-app-failed-to-install-on-device-from-appium/12172

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.5.3
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: OS X El Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): 5.5.0
* Mobile platform/version under test: IOS 9.3.5
* Real device or emulator/simulator: iPhone6s
* Appium CLI or Appium.app|exe:  Appium.app Version 1.5.3 (Ara)
* XCode 7.3.1

## Details

When trying to start the IOS application in Appium.app an error occurs.  See end of Gist file below for error and stack trace.

## Link to Appium logs
https://gist.github.com/nuggit32/be4308cd39298fb96cc5432a3c05cd06 

## Code To Reproduce Issue [ Good To Have ]

Not available.

**Comment by oscheller87** [comment]
Same problem for me. After updating iOS to 9.3.5 Appium can no longer launch apps on the device.

**Comment by oscheller87** [comment]
Same problem occurs on other iOS devices as well. Tested on two 9.3.5 devices and a 8.3 device. 

All throw the same error now
`[debug] [iOS] Creating iDevice object with udid 1802a42ea90fd58d1ac43c2cb3915ee6227fe239

[debug] [iOS] App is not installed. Will try to install.

[MJSONWP] Encountered internal error running command: Error: Installing <bundle_id> failed
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)`

I don't really know what changed. It seems to be Mac OS X related, since the problem is occuring on different versions of iOS. Maybe a OSX system update that broke something?

**Comment by oscheller87** [comment]
i should add that the app is installed on all those devices with correct bundle_id

**Comment by oscheller87** [comment]
I've noticed there was an Itunes update around the time the tests stopped working on both the CI server and also my local Mac. Could this have caused things to not work any longer?

**Comment by jlipps** [comment]
Yes, iTunes upgrade broke UIAutomation. See https://github.com/appium/appium/issues/6844 for fix involving chmodding the lockdown db
