### ISSUE TITLE
android-simple.js sample test doesn't work

### ISSUE THREAD

**Issue by Pitel** [appium/appium#6859]
## The problem
- Test scenario doesn't run all steps
- Test passes, even if it shouldn't
## Environment
- Appium version (or git revision) that exhibits the issue: v1.5.3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Ubuntu 16.04
- Node.js version (unless using Appium.app|exe): v6.6.0
- Mobile platform/version under test: Android 6.0
- Real device or emulator/simulator: Real Nexus 4 with CyanogenMod 13
- Appium CLI or Appium.app|exe: CLI
## Details

If you look at the code (link at bottom), it should click on multiple items and check some stuff. But if you look at the log, it just (barely) clicks on first item and marks the test as ok and doesn't even bother with the rest.

I suppose the problem is with `should`, and JS promises...
## Link to Appium logs

```
  android simple
 > CALL init({"platformName":"Android","deviceName":"Android","app":"http://appium.github.io/appium/assets/ApiDemos-debug.apk"}) 
 > POST /session {"desiredCapabilities":{"platformName":"Android","deviceName":"Android","app":"http://appium.github.io/appium/assets/ApiDemos-debug.apk"}}

Driving the web on session: 39692c6b-7f96-469c-af91-3c31006a8a0b

 > RESPONSE init({"platformName":"Android","deviceName":"Android","app":"http://appium.github.io/appium/assets/ApiDemos-debug.apk"}) "39692c6b-7f96-469c-af91-3c31006a8a0b",{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformName":"Android","deviceName":"Android","app":"http://appium.github.io/appium/assets/ApiDemos-debug.apk"},"platformName":"Android","deviceName":"04c2eca396885879","app":"http://appium.github.io/appium/assets/ApiDemos-debug.apk","deviceUDID":"04c2eca396885879","platformVersion":"6.0.1","appPackage":"io.appium.android.apis","appWaitPackage":"io.appium.android.apis","appActivity":"io.appium.android.apis.ApiDemos","appWaitActivity":"io.appium.android.apis.ApiDemos"}
 > CALL setImplicitWaitTimeout(3000) 
 > POST /session/:sessionID/timeouts/implicit_wait {"ms":3000}
 > RESPONSE setImplicitWaitTimeout(3000) 
 > CALL elementByAccessibilityId("Graphics") 
 > POST /session/:sessionID/element {"using":"accessibility id","value":"Graphics"}
    ✓ should find an element (62ms)
 > CALL quit() 
 > DELETE /session/:sessionID 
 > RESPONSE elementByAccessibilityId("Graphics") {"ELEMENT":"1"}
 > CALL element.click() 
 > POST /session/:sessionID/element/1/click 

Ending your web drivage..

 > RESPONSE quit() 


  1 passing (17s)
```
## Code To Reproduce Issue [ Good To Have ]

https://github.com/appium/sample-code/blob/master/sample-code/examples/node/android-simple.js

**Comment by jlipps** [comment]
I took a look, and the code does look incorrect. Thanks for reporting.

**Comment by mykola-mokhnach** [comment]
Sample code repository is now obsolete
