### ISSUE TITLE
After updating the mac mini to OS 10.11.6 appium is not able to launch the app

### ISSUE THREAD

**Issue by jainabhishek111** [appium/appium#6861]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!
## Environment
- Appium version (or git revision) that exhibits the issue:
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by jainabhishek111** [comment]
[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

[debug] [UIAuto] Dynamic bootstrap path: /Users/crmtest/Library/Application Support/appium/bootstrap/bootstrap-b3d9467fe086a9e6.js

[debug] [UIAuto] Reusing dynamic bootstrap: /Users/crmtest/Library/Application Support/appium/bootstrap/bootstrap-b3d9467fe086a9e6.js
[debug] [iOS] Running ios real device reset flow
[debug] [iOS] Full reset requested. Will try to uninstall the app 'io.cordova.myappa5b0c9'.
[debug] [iOS] Creating iDevice object with udid 33d65b8659362ffd3386990aac522dae61227fbe

[iOS] Could not remove 'io.cordova.myappa5b0c9' from device

[MJSONWP] Encountered internal error running command: Error: Removing io.cordova.myappa5b0c9 failed
    at /Volumes/Appium/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:145:6
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)

[HTTP] <-- POST /wd/hub/session 500 568 ms - 175

**Comment by oscheller87** [comment]
Getting the very same error message:

[MJSONWP] Encountered internal error running command: Error: Installing *bundle_id* failed
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)

Though I have this problem on OS X 10.11.4 as well as 10.11.6 on multiple different iOS 9.5.3 and 8.3 devices. I don't get any iOS UI tests to run for the last few days (starting Sept 15th). I already wrote in another post, that itunes updated around the time that the tests stopped working. I downgraded the itunes installation manually but the problem persists.

**Comment by lambourn** [comment]
Try to update your libimobiledevice installation, see https://github.com/libimobiledevice/ideviceinstaller/issues/54
