### ISSUE TITLE
error: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED appium error

### ISSUE THREAD

**Issue by debasisj** [appium/appium#6862]
## The problem

Hello

I have a very simple code snippet in VS C# which will lunch the chrome on AVD, go the URL, find the element and perform a login action.
here is the part of the problematic part, full code is below 
  driver.Navigate().GoToUrl("MyURL");
                driver.FindElement(By.XPath("//button[@class = 'gcbtn']")).Click();
All goes well until it hit the URL in chrome and open the page, now it should go for the find element action 
In Visual Studio, I see my code stops after opening the URL - not sure what's the update it's waiting from appium server 

In the appium log, appium srevr stops here (what's it waiting for, as URL ia laready opened and ready to take actions) - full log attached
[test.txt](https://github.com/appium/appium/files/481597/test.txt)

2016-09-20 02:38:41:833 - info: JSONWP Proxy: Proxying [POST /wd/hub/session/64e06ffd1f4ddfeb718e54184eec85fc/url] to [POST http://127.0.0.1:9515/wd/hub/session/64e06ffd1f4ddfeb718e54184eec85fc/url] with body: {"url":"MyURL"}
2016-09-20 02:39:41:834 - info: [debug] Didn't get a new command in 60 secs, shutting down...
## Environment
- Appium version (or git revision) that exhibits the issue: 1.4.16.1
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Win 7
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: android 6.0, 23
- Real device or emulator/simulator:emulator
- Appium CLI or Appium.app|exe:
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using OpenQA.Selenium;
using Appium.Interfaces;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Appium.Enums;
using OpenQA.Selenium.Appium.Android;
using OpenQA.Selenium.Appium.Interfaces;
using OpenQA.Selenium.Interactions;
using CropConnect.PageObjects;
using GrainTransact.ComponentHelper;
using GrainTransact.Settings;

namespace CropConnect.TestScripts
{
    [TestClass]
    public class DemoDevice
    {
        [TestMethod]
        public void AndriodTest()
        {

```
        try
        {
            DesiredCapabilities cap = new DesiredCapabilities();

           cap.SetCapability(MobileCapabilityType.BrowserName, "Chrome");
            //cap.SetCapability("device", "Android");
            cap.SetCapability(MobileCapabilityType.PlatformName, "Android");
            cap.SetCapability(MobileCapabilityType.DeviceName, "deb");
           // cap.SetCapability(MobileCapabilityType.AutomationName, "Appium");
            cap.SetCapability(MobileCapabilityType.PlatformVersion, "6.0");

            IWebDriver driver = new AndroidDriver<IWebElement>(new Uri("http://127.0.0.1:4723/wd/hub"), cap, TimeSpan.FromSeconds(180));


            driver.Navigate().GoToUrl("MyURL");
            driver.FindElement(By.XPath("//button[@class = 'gcbtn']")).Click();
            driver.FindElement(By.Id("userNameInput")).SendKeys(ObjectRepository.Config.GetUserName());
            driver.FindElement(By.Id("passwordInput")).SendKeys(ObjectRepository.Config.GetUserName());
            driver.FindElement(By.Id("submitButton")).Click();
        }
        catch (Exception e)
        {

            Console.WriteLine(e.ToString());
        }
    }
}
```

}

**Comment by dpgraham** [comment]
Closing.

If this still happens in 1.6 I'll re-open.
