### ISSUE TITLE
launching http://127.0.0.1:4273/welcome url on iPhone5 simulator 9.2 safari browser 

### ISSUE THREAD

**Issue by automationtesting123** [appium/appium#6865]
## The problem

Hi,
http://127.0.0.1:4723/welcom url is getting launched instead of https://www.google.com for every time when i run the below code

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3 Ara
* Last Appium version that did not exhibit the issue (if applicable): my requirement is to use Appium 1.5.3 Ara
* Desktop OS/version used to run Appium: Mac OS EI Captain
* Node.js version (unless using Appium.app|exe): 1.5.3
* Mobile platform/version under test: IOS 9.1
* Real device or emulator/simulator: iPhone5(9.1) and also all other versions of simulators
* Appium CLI or Appium.app|exe: Appium.app

## Details

http://127.0.0.1:4723/welcom url is getting launched instead of https://www.google.com for every time when i run the below code.
## Link to Appium logs

I dont see any kind of error messages in appium console

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities cap = new DesiredCapabilities();
cap.setCapability("deviceName", device);
cap.setCapability("platformName", "iOS");
cap.setCapability("platformVersion", "9.1");					cap.setCapability(MobileCapabilityType.BROWSER_NAME, BrowserType.SAFARI);

AppiumDriver appDriver  = new IOSDriver(new URL(hostUrl), cap);

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by automationtesting123** [comment]
![simulator screen shot sep 20 2016 7 46 56 pm](https://cloud.githubusercontent.com/assets/17786510/18673828/d5d04290-7f6a-11e6-82f8-005e98ade325.png)
![simulator screen shot sep 20 2016 7 46 59 pm](https://cloud.githubusercontent.com/assets/17786510/18673829/d6032f20-7f6a-11e6-8a29-7a0e9920a64f.png)
![simulator screen shot sep 20 2016 7 47 04 pm](https://cloud.githubusercontent.com/assets/17786510/18673830/d603cc00-7f6a-11e6-9065-41bb80487741.png)

**Comment by imurchie** [comment]
Try setting the `safariInitialUrl` capability to `"https://www.google.com"`.

**Comment by automationtesting123** [comment]
@imurchie: i have set "safariInitialUrl" in desired capabilities after i have run the code but google site is keep on loading and refresing on safari

**Comment by automationtesting123** [comment]
is any another way to avoid this Applim/welcom url?

**Comment by imurchie** [comment]
Without the logs there is no way to tell what is going on.

Using the `safariInitialUrl` ought to avoid the welcome screen. Otherwise, no.

**Comment by automationtesting123** [comment]
@imurchie: Thanks... it's resolved my issue
