### ISSUE TITLE
Appium 1.6.0-beta1: Failed to tap on some elements

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#6866]
## The problem

After migrating from 1.5.3 -> 1.6.0-beta1 have problem with tap action with some page elements. In Appium logs we see that tap happened but in Simulator we see no action done.
## Environment
- Appium version: 1.6.0-beta1
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3
- Desktop OS/version used to run Appium: OS X 10.11.6
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: 
- Real device or emulator/simulator: Simulator 10.0
- Appium CLI or Appium.app|exe:
## Details

After digging little more find out that with following tap actions **it does not work** with problem element:
- new TouchAction((MobileDriver) driver).tap(element).perform();
- ((AppiumDriver) driver).tap(1, element, 200);

**but it works with** same element:
- element.click();
## Link to Appium logs

https://gist.github.com/amedvedjev/ae8926ed678bd9b25f7da1cde378ba2e

**Comment by yaphatak** [comment]
is this element in view when you see try to tap it?

**Comment by amedvedjev** [comment]
@yaphatak yes. element is clearly visible and i can tap on it multiple times without success with TouchAction or tap.

In all cases tap happens with same X,Y coordinates.

**Comment by yaphatak** [comment]
so if tap is working which action is failing and when?

**Comment by amedvedjev** [comment]
@yaphatak 
with TouchAction and tap - tap happened BUT on client it does not happen. with click - tap happens on client.
I mentioned that it mostly affect dynamic elements. Static elements like static button or icon any way is working.
