### ISSUE TITLE
create class name shortcuts to map to XCUIElement*

### ISSUE THREAD

**Issue by jlipps** [appium/appium#6871]
Currently, if you want to find an element by class name in XCUITest, you need to do something like:

```
driver.find_element_by_class_name("XCUIElementTypeStaticText")
```

We could easily and deterministically map `StaticText` to `XCUIElementTypeStaticText`. Seems like it would be a convenience, and in many cases keep people from having to rewrite tests.

**Comment by imurchie** [comment]
This seems reasonable. Not sure about the not rewriting tests part, since in UI Automation they would be looking for `UIAStaticText`. But still useful.

**Comment by imurchie** [comment]
The available types are here: https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Utilities/FBElementTypeTransformer.m
