### ISSUE TITLE
Appium 1.6.0-beta1: iOS: Failed to set PickerWheel value

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#6873]
## The problem

Set wheel value does not work any more with latest Appium.

## Environment

* Appium version: 1.6.0-beta1
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: OS X 10.11.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 
* Real device or emulator/simulator: Simulator 10.0
* Appium CLI or Appium.app|exe:

## Details

Tried:
`((IOSElement)driver.findElements(MobileBy.className("XCUIElementTypePickerWheel")).get(0)).setValue(countryName);
            ((IOSElement)driver.findElements(MobileBy.className("XCUIElementTypePickerWheel")).get(0)).sendKeys(countryName);`

## Link to Appium logs

debug] [XCUITest] Executing command 'setValueImmediate'
[XCUITest] There is currently no way to bypass typing using XCUITest. Setting value through keyboard
[JSONWP Proxy] Proxying [POST /element/F725FBF8-4D89-45EF-A7EC-1EBA2D61E9F4/value] to [POST http://localhost:8100/session/05D96C05-81F1-4089-B914-BD6A7F8259C0/element/F725FBF8-4D89-45EF-A7EC-1EBA2D61E9F4/value] with body: {"value":["N","e","t","h","...
[debug] [WebDriverAgent] Sim: Sep 21 11:51:31 aleks XCTRunner[28375]: Enqueue Failure: UI Testing Failure - Requested adjust to value '(
[debug] [WebDriverAgent] Sim: 	    N,
[debug] [WebDriverAgent] Sim: 	    e,
[debug] [WebDriverAgent] Sim: 	    t,
[debug] [WebDriverAgent] Sim: 	    h,
[debug] [WebDriverAgent] Sim: 	    e,
[debug] [WebDriverAgent] Sim: 	    r,
[debug] [WebDriverAgent] Sim: 	    l,
[debug] [WebDriverAgent] Sim: 	    a,
[debug] [WebDriverAgent] Sim: 	    n,
[debug] [WebDriverAgent] Sim: 	    d,
[debug] [WebDriverAgent] Sim: 	    s
[debug] [WebDriverAgent] Sim: 	)' which is not one of the possible values Austria, Belgium, Bulgaria, Croatia, Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Iceland, Ireland, Italy, Latvia, Liechtenstein, Lithuania, Luxembourg, Malta, Netherlands, Norway, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden, Switzerland, United Kingdom for the picker wheel "Austria" PickerWheel /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1

**Comment by urimagisto** [comment]
same issue here, with same setup

**Comment by imurchie** [comment]
This isa repeatable failure. Working on the upstream project to get a fix.

Thanks!

**Comment by jlipps** [comment]
@imurchie seems like WDA doesn't know how to handle array of values according to the spec?

**Comment by imurchie** [comment]
It does, except for picker wheels. I've just submitted a PR to fix this issue.

**Comment by amedvedjev** [comment]
how to grab changes? reinstall with
`npm i -g webpack`

**Comment by imurchie** [comment]
If you update Appium you should get these changes. 

Updated in `appium-xcuitest-driver@2.0.16`.

**Comment by amedvedjev** [comment]
damn! working just great! speed if fantastic comparing with older UIAutomation.

**Comment by appiumnovice** [comment]
Hi, I still have this problem with appium beta1.6.0-beta1 witch contains appium-xcuitest-driver@2.0.23.
I tried to set "ven., 7 oct." (or "7 oct.") in wheel containing "mar., 4 oct.".
The error is : "Enqueue Failure: UI Testing Failure - Internal error: unable to find current value '(null)' in possible values 15 août, 16 août, ... 7 oct., ... for the picker wheel "mar., 4 oct." PickerWheel /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1"

**Comment by imurchie** [comment]
Can you provide more of the log? We need to know what is being sent in.

**Comment by appiumnovice** [comment]
I added Appium logs, but seems poor in a debug mode

Le 5 oct. 2016 18:31, "Isaac A. Murchie" <notifications@github.com> a
écrit :

**Comment by imurchie** [comment]
I don't see any logs.

**Comment by appiumnovice** [comment]
I put a Gist link to Appium log

Le 7 oct. 2016 15:46, "Isaac A. Murchie" <notifications@github.com> a
écrit :

**Comment by imurchie** [comment]
Where? You need to post a link here.

**Comment by appiumnovice** [comment]
Sorry, I added it to the post.

Here is the poor log from Appium for the moment the script tries to get
items by xpath:
https://gist.github.com/appiumnovice/b067a93e4471f2c84013d8b6845868c4



2016-10-07 15:58 GMT+02:00 Isaac A. Murchie <notifications@github.com>:

**Comment by imurchie** [comment]
I don't understand what this has to do with the original problem. What is this log? Why am I looking at it?

**Comment by appiumnovice** [comment]
Well, I'll try to be more clear

I do a findElementsByXpath() and I retrieve a number of items.
But when I try to retrieve values from these items, I didn't retrieve the
values from the good property for all items.

I look for retrieve the value of the property "trainNameLabel" for all
items.

In many cases, it returns the value of the property "trainNameLabel" (it's
what I asked. ex: TER N°843508),
but sometimes I have the value of the property "destinationLabel" (ex:
Valenciennes) or the hour (ex : 11 Heure 46 Minute).
Why I got theses values?

I select only XCUIElementTypeStaticText items with @name=trainNameLabel and
when I get values, some come from XCUIElementTypeStaticText with
@name="destinationLabel" or "11 Heure 46 Minute " !

Here is an example of tree of items for which I want just to get the value
of the last "XCUIElementTypeStaticText" (with name="trainNameLabel"):

    <XCUIElementTypeCell name="SUTrainBoardDefaultCell" label="" value=""
dom="" enabled="true" valid="true" visible="true" hint=""
path="/0/0/0/0/0/0/1/0/0/0/1/0/2" x="0" y="139" width="414" height="75">
        <XCUIElementTypeStaticText name="platformNumberLabel" label="Voie
4" value="Voie 4" dom="" enabled="true" valid="true" visible="true" hint=""
path="/0/0/0/0/0/0/1/0/0/0/1/0/2/0" x="294" y="164" width="35" height="25">
        </XCUIElementTypeStaticText>
        <XCUIElementTypeStaticText name="11 Heure 46 Minute " label="11
Heure 46 Minute " value="11 Heure 46 Minute " dom="" enabled="true"
valid="true" visible="true" hint="" path="/0/0/0/0/0/0/1/0/0/0/1/0/2/1"
x="20" y="166" width="50" height="21">
        </XCUIElementTypeStaticText>
        <XCUIElementTypeStaticText name="destinationLabel"
label="Valenciennes" value="Valenciennes" dom="" enabled="true"
valid="true" visible="true" hint="" path="/0/0/0/0/0/0/1/0/0/0/1/0/2/2"
x="76" y="148" width="213" height="34">
        </XCUIElementTypeStaticText>
        <XCUIElementTypeStaticText name="trainNameLabel" label="TER
N°843508" value="TER N°843508" dom="" enabled="true" valid="true"
visible="true" hint="" path="/0/0/0/0/0/0/1/0/0/0/1/0/2/3" x="76" y="183"
width="213" height="15">
        </XCUIElementTypeStaticText>
    </XCUIElementTypeCell>

The Appium log I sent only shows the moment when findElementsByXpath()
instruction is run. But I haven't seen an error in log.

I really don't know how to proceed to find the root cause of this problem.

Thank you in advance for your help.

2016-10-07 16:03 GMT+02:00 Isaac A. Murchie <notifications@github.com>:

**Comment by ngreeney** [comment]
@appiumnovice This is not an error. You are asking how to do something not reporting an error as far as I can tell. Try asking here: https://discuss.appium.io/

If it really is an error, you need to post what commands you are explicitly sending to appium (like what python/java/etc command) and what you are receiving back from appium.

Also this does not have to do with the picker wheel issue so please start another post with all the correct logs if you think it is still an error.

**Comment by appiumnovice** [comment]
Issac, i'm really really really sorry!!!

I just understood than I send you elements for another problem !!! Post
#6945 that I opened 2 days ago!

For this problem of Picker, I'm run the test again and send you Appium logs.

2016-10-07 16:03 GMT+02:00 Isaac A. Murchie <notifications@github.com>:

**Comment by appiumnovice** [comment]
I posted a new issue : #6962

PS: is it possible to remove previous posts that finally have nothing to do with the problem described in this post to avoid visitors to be disturbed ?

**Comment by suganeby** [comment]
@appiumnovice,  Did you solve the picker issue? I do have issue in setting value to the picker wheel. Let me know if you have any solution.
I am using appium 1.6.3 on a real device ios 10.

**Comment by kcinman11358** [comment]
I'm running Appium 1.6.3 via command line and using iphone6 9.3 sim. 

I am unable to use send keys, where as old version of appium i could

**Comment by Joekannan** [comment]
Hi All,

Please let me know the solution for this issue.

SendKeys were working in old version. What is the logic to deal with PickerWheel.

It is very urgent for me to complete the assignment. stuck into this.

**Comment by amedvedjev** [comment]
@Joekannan 
```
driver.findElement(MobileBy.className("XCUIElementTypePickerWheel")).setValue("your_value");
```

**Comment by Joekannan** [comment]
@amedvedjev 

Thanks for the prompt update.

Unfortunately, this is also not working for me 👎 .

And I am getting the below error in Terminal - Appium logs
[debug] [iProxy] recv failed: Resource temporarily unavailable
[debug] [iProxy] recv failed: Operation not permitted

**Comment by Joekannan** [comment]
@amedvedjev 

I am very new to iOS Automation. i have installed Appium 1.6.4-beta from terminal. After the installation if i launch the appium from Terminal Appium 1.6.3 is launching.

**Logs are below:**
Last login: Wed Mar  1 16:29:24 on ttys000
DTS-Mini:~ automation$ npm install appium@1.6.4-beta
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
automation@1.0.0 /Users/automation
└── appium@1.6.4-beta 

npm WARN automation@1.0.0 No description
npm WARN automation@1.0.0 No repository field.
DTS-Mini:~ automation$ sudo npm install appium@1.6.4-beta
Password:
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
automation@1.0.0 /Users/automation
└── appium@1.6.4-beta 

npm WARN automation@1.0.0 No description
npm WARN automation@1.0.0 No repository field.
DTS-Mini:~ automation$ appium --default-capabilities '{"newCommandTimeout": 3000}'
[Appium] Welcome to Appium v1.6.3 (REV d9b43638333b47dd8ed8bcbbb97ef9f8c0ad5756)
[Appium] Non-default server args:
[Appium]   defaultCapabilities: { newCommandTimeout: 3000 }
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   newCommandTimeout: 3000
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

Your timely help would be appreciated. Thanks

**Comment by appiumnovice** [comment]
Try "npm install *-g* appium@1.6.4-beta" <appium@1.6.4-beta>

2017-03-01 17:40 GMT+01:00 Joekannan <notifications@github.com>:

**Comment by Joekannan** [comment]
@appiumnovice 

I am getting the below terminal error 

Last login: Wed Mar  1 17:28:51 on ttys001
DTS-Mini:~ automation$ npm install *-g* appium@1.6.4-beta
npm ERR! addLocal Could not install /Users/automation/*-g*
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "*-g*" "appium@1.6.4-beta"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! path /Users/automation/*-g*
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/automation/*-g*'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/automation/*-g*'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/automation/.npm/_logs/2017-03-01T17_29_49_831Z-debug.log
DTS-Mini:~ automation$

**Comment by Joekannan** [comment]
I have seen a separate thread for this issue, where they have mentioned it is a non-appium issue and  developer needs to change the Wheel picker implementation to identify the elements.

Below is the URL where i found this information:-
https://github.com/appium/appium/issues/6962

Can anyone please confirm this, is there any other alternate or reliable workaround to deal with XCUIElementTypePickerWheel Element..

Please it is very urgent. Your help is much appreciated.

**Comment by suganeby** [comment]
I had the same issue. My developer couldn't change the implementation for some reasons. 
I tried below work around with points and dimensions. It works. 

 List<IOSElement> wheels = driver.findElements(MobileBy.className("XCUIElementTypePickerWheel"))

Point p1=wheels.get(0).getLocation()
Dimension d1 = wheels.get(0).getSize()

//-100 scrolls up (taps the value below the currently selected value)
driver.tap(1, p1.getX(), p1.getY() + d1.getHeight() -100, 500)

//+100 scrolls down (taps the value above the currently selected value)
driver.tap(1, p1.getX(), p1.getY() +100, 500)

**Comment by Joekannan** [comment]
@suganeby 
Thanks a lot for your help. Its absolutely working fine.

**Comment by kamikrazeguy** [comment]
@suganeby Thanks for the implementation. I've been scouring for a workaround for a viewForRow implementation and this was the only solution that worked for me. I really appreciate your contribution!

**Comment by suganeby** [comment]
@Joekannan and @kamikrazeguy 
I just installed appium 1.6.4. Now I am able to set values to the picker directly.

List wheels = driver.findElements(MobileBy.className("XCUIElementTypePickerWheel"))
wheels.get(0).setValue("12")

**Comment by kamikrazeguy** [comment]
Per @suganeby 

I just installed appium 1.6.4. Now I am able to set values to the picker directly.

List wheels = driver.findElements(MobileBy.className("XCUIElementTypePickerWheel"))
wheels.get(0).setValue("12")

**Comment by SamyQAZ** [comment]
Was anyone able to get solution for this issue?
I am facing the same issue with Appium.app version 1.6.1.
Not sure how to select date from wheel picker.

Tried to use,
xpath=//*[@XCUIElementTypePickerWheel='XCUIElementTypeAny',1,"2020"]
But seem something wring in this. 
Does anyone know whats wrong with the xpath?

**Comment by suganeby** [comment]
@SamyQAZ ,
can you try my solution above? It uses class name instead of xpath.
