### ISSUE TITLE
Failed to start an appuim session

### ISSUE THREAD

**Issue by sami7g** [appium/appium#6874]
While running my automation script throwing error like 'SessionNotCreatedExcption'. When launching appium getting the following error.

error: Failed to start an Appium session, err was: Error: Installing /Users/OatMac/Library/Developer/Xcode/DerivedData/OATmobile-dqasddtzvemznsefcbkcwpxtfvkr/Build/Products/Debug-iphoneos/OATmobile.app failed

info: [debug] Error: Installing /Users/OatMac/Library/Developer/Xcode/DerivedData/OATmobile-dqasddtzvemznsefcbkcwpxtfvkr/Build/Products/Debug-iphoneos/OATmobile.app failed
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Installing /Users/OatMac/Library/Developer/Xcode/DerivedData/OATmobile-dqasddtzvemznsefcbkcwpxtfvkr/Build/Products/Debug-iphoneos/OATmobile.app failed)","origValue":"Installing /Users/OatMac/Library/Developer/Xcode/DerivedData/OATmobile-dqasddtzvemznsefcbkcwpxtfvkr/Build/Products/Debug-iphoneos/OATmobile.app failed"},"sessionId":null}
info: <-- POST /wd/hub/session 500 1260.939 ms - 422

And my code is like below.
String device_version = rb.getString("device_version");
  String device_appPath = rb.getString("device_appPath");
  String device_name = rb.getString("device_name");
  //String device_platform = rb.getString("device_platform");
  File app=new File("/Users/OatMac/Library/Developer/Xcode/DerivedData/OATmobile-dqasddtzvemznsefcbkcwpxtfvkr/Build/Products/Debug-iphoneos/OATmobile.app");
  DesiredCapabilities capabilities = new DesiredCapabilities();
  capabilities.setCapability(CapabilityType.VERSION, device_version);
  capabilities.setCapability("deviceName", device_name);
  capabilities.setCapability("app", app.getAbsolutePath());
  driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);

Environment:
Appium: 1.4.8
Xcode: 7.3.1
MAC: 10.11.1

**Comment by jlipps** [comment]
For real devices you have to set your app to be a signed ipa. It can't be a `.app` build.
