### ISSUE TITLE
findElement hangs when current windowHandle disaappears

### ISSUE THREAD

**Issue by michalakm** [appium/appium#6875]
## The problem

I test an Android hybrid app. I want to switch from one window to other and to select the right one needed to further test I iterate each window and look for a specified element. Usually this approach works fine but in this case when I open new window for a moment spinner appears. When Appium switches to window with spinner and it disappears it hangs without any exception or anything.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.2 and 1.5.3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: iOS 10.11.6
- Node.js version (unless using Appium.app|exe): Appium.app
- Mobile platform/version under test: Android 5.0.1
- Real device or emulator/simulator: real
- Appium CLI or Appium.app|exe: both CLI and app
## Details

Step by step description:
1. I am in webview context, one window handle is present - let's call it [1]
2. Button to open new webview is clicked 
3. Two new window handles appear - spinner and new window so there are three - let's call them [2] and [3] respectively
4. I iterate between each of them and look for a specified element (in this case css locator #product-page) to choose one of them so I switch to first of three [1].
5. I search for the element and the element is not found so I switch to second window [2] - with spinner.
6. I start searching for the element, in the meantime spinner disappears so I expect NoSuchWindow exception or something but application hangs.
## Link to Appium logs

[log_apppium](https://gist.github.com/michalakm/ddbb92232e8ce86235b3bac3bdb95ab8)

**Comment by dpgraham** [comment]
Unable to reproduce. If this is still a problem, please re-open with new logs.
