### ISSUE TITLE
appium issue with xcode 8

### ISSUE THREAD

**Issue by shay777** [appium/appium#6876]
## The problem

Appium inspector cannot launch ipa file with iOS 10 and xcode 8

## Environment

Appium v.1.6.0 -beta1
xcode 8
On real iOS device 10

## Details

I cannot start the appium inspector with ipa file due to the following error:
[Xcode] Could not find Automation.tracetemplate in any of the followinglocations /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate,/Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate

## Link to Appium logs

https://gist.github.com/shay777/a5b0a84da512b5438b38bbe0174e7043

**Comment by imurchie** [comment]
What version of Appium is it running against? iOS 10 will not work with anything below 1.6.0-beta.

Even then you will need to specify an `automationName` of `XCUITest` to get the new driver that can handle Xcode 8/iOS 10.

**Comment by shay777** [comment]
I am using 1.6.0-beta from the command line but the appium desktop app (the one that can launch the appium inspector) is 1.5.3. Is there any other way to inspect the elements besides the desktop app? or maybe there is also a beta version for the desktop app?

**Comment by imurchie** [comment]
There is not yet a version of the desktop app for 1.6.0.

**Comment by shay777** [comment]
is there any other way I can inspect the elements?

**Comment by jlipps** [comment]
@shay777 not visually, no. you can always use the page source command to inspect the hierarchy though.

**Comment by shay777** [comment]
what do you mean by use the page source code?
basically an element like: //UIATableCell[5]/UIAStaticText[2] should not work on xcode 8 and ios 10, right?

**Comment by imurchie** [comment]
No, it won't. There is no more UI Automation, so no more `UIA...`.

You can retrieve the page source for the view you are on and figure out what is there that way. Your client will have its particular way of doing so.

**Comment by urimagisto** [comment]
use xcode accessibility inspector meanwile

**Comment by mgmanikandan87** [comment]
Hi all,

Currently, appium 1.6 is not available in GUI to inspect the elements, but there is workaround you can get the elements. 

Try this :

https://www.youtube.com/watch?v=4BgkVp0v3BM

This video might help you guys
