### ISSUE TITLE
cannot launch app on iphone using appium

### ISSUE THREAD

**Issue by shay777** [appium/appium#6877]
## The problem

I have an ios app installed on a real phone but I cannot launch it.
## Environment

Appium v.1.6.0 -beta1
xcode 8
On real iOS device 10
## Details

I cannot run my script after I upgraded to xcode 8 and ios 10
## Link to Appium logs

https://gist.github.com/shay777/8d4e684be740c5c742caaa1ee53e53bc

**Comment by imurchie** [comment]
Try specifying the bundle id as `bundleId` instead of `app`.

**Comment by shay777** [comment]
thanks
it worked
but is there a reason why I see this line on the command line:
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...

it's keep appearing and not stoping

**Comment by srkannan** [comment]
MobileCapabilityType does not have bundleId as property.

**Comment by wjl025** [comment]
[Appium] Welcome to Appium v1.6.0-beta2
[Appium] Non-default server args:
[Appium]   address: '127.0.0.1'
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","platformName":"ios","appPackage":"m
e.andpay.Expended-Business","appActivity":"","deviceName":"5eb40ffb1c125cf65acdf3ac52a7963ca65dcd0a","udid":"5eb40ffb1c1
25cf65acdf3ac52a7963ca65dcd0a","bundleId":"me.andpay.Expended-Business","unicodeKeyboard":true,"resetKeyboard":true,"ign
oreUnimportantViews":true,"sendKeyStrategy":"setValue","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITes...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   automationName: 'XCUITest'
[Appium]   platformName: 'ios'
[Appium]   appPackage: 'me.andpay.Expended-Business'
[Appium]   appActivity: ''
[Appium]   deviceName: '5eb40ffb1c125cf65acdf3ac52a7963ca65dcd0a'
[Appium]   udid: '5eb40ffb1c125cf65acdf3ac52a7963ca65dcd0a'
[Appium]   bundleId: 'me.andpay.Expended-Business'
[Appium]   unicodeKeyboard: true
[Appium]   resetKeyboard: true
[Appium]   ignoreUnimportantViews: true
[Appium]   sendKeyStrategy: 'setValue'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appPackage, appActivity, unicodeKeyboard, resetKeyboard, ignoreUnimportantViews, realDeviceLogger.
[BaseDriver] Session created with session id: 8eb38c0f-21f9-4743-b6fb-f208caf3357e
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: 5eb40ffb1c125cf65acdf3ac52a7963ca65dcd0a
[debug] [XCUITest] Creating iDevice object with udid 5eb40ffb1c125cf65acdf3ac52a7963ca65dcd0a
[XCUITest] Determining device to run tests on: udid: '5eb40ffb1c125cf65acdf3ac52a7963ca65dcd0a', real device: true
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] Stdout from app isInstalled check: [....] Waiting for iOS device to be connected
[....] Using iPhone 6 (GSM) 'iPhone' (5eb40ffb1c125cf65acdf3ac52a7963ca65dcd0a).
true

[debug] [XCUITest] App is installed.
[debug] [XCUITest] fullReset not requested. No need to install.
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Beginning test with command 'xcodebuild -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=5eb40ffb1c125cf65acdf3ac52a7963ca65dcd0a build test' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
(node:13708) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: spawn EACCES
[debug] [XCUITest] Log file for xcodebuild test: /Users/jialinwang/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/3CBA6F36-C84F-4FA2-A315-002A09931BE5/Session-WebDriverAgentRunner-2016-09-23_143209-xlvax4.log
[HTTP] <-- POST /wd/hub/session - - ms - - 
(END)

my app not launch,help me,thanks

**Comment by wjl025** [comment]
[XCUITest] Log file for xcodebuild test
https://gist.github.com/wjl025/849694e533394c0fa7b9bf7db9dc833a

**Comment by yaphatak** [comment]
Internally it also expects `deviceconsole` to be installed. (You can install npm install `deviceconsole`. A compiled binary named deviceconsole will be added to ./node_modules/deviceconsole/.) 

You need to either have `deviceconsole` in your `PATH`, or specify its location using the `realDeviceLogger` capability.

**Comment by wjl025** [comment]
@yaphatak
i have install deviceconsole and capability is specify
 caps: {
          automationName: 'XCUITest',
          platformName: PLATFORM,
          appPackage: BUNDLE_ID,
          appActivity: APP_ACTIVITY,
          deviceName: UDID,
          udid: UDID,
          bundleId: BUNDLE_ID,
          unicodeKeyboard: true,
          resetKeyboard: true,
          ignoreUnimportantViews: true,
          sendKeyStrategy: 'setValue',
          realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole'
      },
