### ISSUE TITLE
setValue("/") in appium1.6beta actually set the text to "\/"

### ISSUE THREAD

**Issue by huminzhi** [appium/appium#6878]
## The problem

With UIA, we can setValue() to a text field element
This is no longer working after upgrade to appium1.6beta

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6beta
* Last Appium version that did not exhibit the issue (if applicable): 1.5
* Desktop OS/version used to run Appium: Mac OS10.11
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by jlipps** [comment]
@huminzhi can you provide more context for this please?

**Comment by huminzhi** [comment]
sorry to reply late @jlipps on this.. 
At beginning, I saw some error message saying 'setValue' in not supported, but seems it's fixed now(https://github.com/appium/appium-xcuitest-driver/issues/133);  now I can see it does 'setValue', however, in some case, it's not setting a correct value..

my code is simply 
driver.setTextValue(element, "http://xxxxx/")
It worked before, but now I saw the element is set to "http:\/\/xxxxxx\/" (an escaped string?)

I am not sure if it's related to this change https://github.com/appium/appium-xcuitest-driver/pull/141, will you please help check?

**Comment by imurchie** [comment]
This is fixed by https://github.com/appium/appium-xcuitest-driver/pull/182

**Comment by huminzhi** [comment]
cool!
