### ISSUE TITLE
Software keyboard on Android Emulators can block actions on elements

### ISSUE THREAD

**Issue by chiarnglin** [appium/appium#6879]
## The problem

Demo: https://www.youtube.com/watch?v=hp1HJjrW0CQ&feature=youtu.be
Software keyboard comes up when a text field is highlighted. A button that is covered by the keyboard is acquired by ID, but when it is clicked, the keyboard is clicked instead of the button. 
## Environment

node 6.4.0, appium 1.5.3, osx 10.11, android 19 emulator
running appium from cli
## Code To Reproduce Issue [ Good To Have ]

Please reference emulator-softkeyboard-tests repo.

**Comment by amedvedjev** [comment]
hide keyboard before tap on button. What are you expecting?

**Comment by chiarnglin** [comment]
Well, Appium tests replicate user workflows. As a user, if I tried to find a button covered by a keyboard, I'd say, "I can't find this button", rather than tapping the space bar in an attempt to click on the button. That's the bug. 

Hiding the keyboard is a workaround. The best solution would be to have the app push the screen up when the keyboard comes up. The former requires a change to the test, and the latter requires a change to the app. If I change neither, this is not a behavior I expect to happen in an Appium test.

**Comment by pumano** [comment]
but if you have EditText element at bottom of screen, you can't enter any data to that element, because: 
`org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 25.24 seconds`

## Environment
node 6.4.0, appium 1.5.3, osx 10.11.6, android 21 emulator, java-client 
running appium from cli

**Comment by chiarnglin** [comment]
The case that we observed was where there was a button element at the bottom of the screen. Appium still tries to interact with it by tapping the keyboard where it covers the location of the button.

**Comment by dpgraham** [comment]
Logging this as a bug but I'm not certain if we'll be able to fix it. If UIAutomator2 is reporting the presence of the element despite being behind the keyboard, not sure we can workaround that. Will look into it though.

**Comment by jlipps** [comment]
Moving to P2 since there's a nice workaround.

**Comment by SamyQAZ** [comment]
Appium fails to click search button on keyboard for capability unicode keyboard. 

Input some text and choose search.

does anyone have idea how to click search, tried using press keycode 66 but no luck

**Comment by mykola-mokhnach** [comment]
I don't think there is more to do here as we have now. One can always hide a keyboard on Android if necessary by calling hideKeyboard API
