### ISSUE TITLE
[ios] "reset" doesn't really reset the simulator

### ISSUE THREAD

**Issue by huminzhi** [appium/appium#6883]
## The problem

execute "reset" to reset the simulation (suppose also uninstall the existing apps),  simulation just shutdown then reopen, it doesn't really 'reset' 
## Environment
- Appium version (or git revision) that exhibits the issue: appium1.6beta1
- Last Appium version that did not exhibit the issue (if applicable): appium1.5
- Desktop OS/version used to run Appium: mac os10.11
- Node.js version (unless using Appium.app|exe):5.5.0
- Mobile platform/version under test: ios 10.0
- Real device or emulator/simulator: simulator
- Appium CLI or Appium.app|exe:CLI
## Details

From the logs below, it seems working, however, the simulator doesn't really reset as expected:

[debug] [XCUITest] Resetting simulator
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [iOSLog] Stopping iOS log capture
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
How do you execute "reset"? Can you provide an example of your source code? In general, you cannot execute this command while Simulator is still running.

**Comment by huminzhi** [comment]
Just by sending command "reset" to the webDriver..
So probably I should talk to webDriver team..?

**Comment by imurchie** [comment]
Reset has been rewritten. Closing.
