### ISSUE TITLE
Document for using the appium 1.6.0 beta for real devices

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#6885]
I am using the appium 1.6 beta 1 for iOS 10 device.

Can anyone mention the steps and prerequisites that are required for running appium 1.6 on real devices ? Screenshots are really encouraged.

**Comment by yaphatak** [comment]
@pavanbachu0604 let us know if [this](https://github.com/yaphatak/appium-xcuitest-driver/blob/cdac8d2c24f3595b09e17efe95275e0874cda556/README.md#real-devices) doc make sense to you and works for you.

**Comment by pavanbachu0604** [comment]
_WNJ0034ALDVSBCF:WebDriverAgent XXXX $ sh ./Script/build.sh
sh: ./Script/build.sh: No such file or directory_

I am getting error

**Comment by yaphatak** [comment]
Sorry There is mistake and I will update that doc.
It should be `./Scripts/build.sh`

**Comment by ngreeney** [comment]
running `./Scripts/build.sh` fails with this for me:

```
** ARCHIVE FAILED **


The following build commands failed:
	CompileC /Users/Nathan/Library/Developer/Xcode/DerivedData/WebDriverAgent-cztbxbrgjvgebmdxjvobdqpmtkpj/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/IntermediateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/Objects-normal/armv7/XCTestPrivateSymbols.o WebDriverAgentLib/Utilities/XCTestPrivateSymbols.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

```

**Comment by pavanbachu0604** [comment]
CompileC /Users/bachupa/Library/Developer/Xcode/DerivedData/WebDriverAgent-ebjlqhzcytpvtscannpqdvjrwdui/Build/Intermediates/ArchiveIntermediates/WebDriverAgentRunner/IntermediateBuildFilesPath/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/Objects-normal/armv7/XCTestPrivateSymbols.o WebDriverAgentLib/Utilities/XCTestPrivateSymbols.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

I get the above error

**Comment by yaphatak** [comment]
its fine follow rest of instructions

**Comment by ngreeney** [comment]
Ok, if it's not an issue the next step I'm guessing is the problem then:
```
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<UDID>' test
```

```
Signing Identity:     "iPhone Developer: Nathan Greeney (####)"
Provisioning Profile: "WebDriverAgent"
                      (######)

    /usr/bin/codesign --force --sign C449ADBAD2E68A55E87FDE8FA8C9A035E78827C4 --deep --entitlements /Users/Nathan/Library/Developer/Xcode/DerivedData/WebDriverAgent-cztbxbrgjvgebmdxjvobdqpmtkpj/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentRunner.build/WebDriverAgentRunner.xctest.xcent --timestamp=none /Users/Nathan/Library/Developer/Xcode/DerivedData/WebDriverAgent-cztbxbrgjvgebmdxjvobdqpmtkpj/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
/Users/Nathan/Library/Developer/Xcode/DerivedData/WebDriverAgent-cztbxbrgjvgebmdxjvobdqpmtkpj/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app: replacing existing signature

writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/x6/qcscbnts2vv28f167055q3p80000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/4c752fe92cf4ea46bacd6da81c6b53c5/f8550726639b5c7dbf596cc598f5ad74d45f94f1/ManifestCache.plist
2016-09-23 13:05:38.828 xcodebuild[24064:2895330] Error Domain=com.apple.dtdevicekit Code=-402652994 "App installation failed" UserInfo={NSLocalizedFailureReason=This application's application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x0000000111a1f3cb DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x0000000111a1fb09 DTDK_AMDErrorToNSError + 791
	2   DTDeviceKitBase                     0x0000000111a5fa02 __90-[DTDKRemoteDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 158
	3   DVTFoundation                       0x0000000108f352e5 DVTInvokeWithStrongOwnership + 75
	4   DTDeviceKitBase                     0x0000000111a5f748 -[DTDKRemoteDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1181
	5   IDEiOSSupportCore                   0x000000011195836a __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.336 + 4597
	6   DVTFoundation                       0x0000000109058f4b __DVTDispatchAsync_block_invoke + 827
	7   libdispatch.dylib                   0x00007fff8733093d _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff8732540b _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff8732a03b _dispatch_queue_drain + 754
	10  libdispatch.dylib                   0x00007fff87330707 _dispatch_queue_invoke + 549
	11  libdispatch.dylib                   0x00007fff87328d53 _dispatch_root_queue_drain + 538
	12  libdispatch.dylib                   0x00007fff87328b00 _dispatch_worker_thread3 + 91
	13  libsystem_pthread.dylib             0x00007fff961594de _pthread_wqthread + 1129
	14  libsystem_pthread.dylib             0x00007fff96157341 start_wqthread + 13
), NSLocalizedRecoverySuggestion=This application's application-identifier entitlement does not match that of the installed application. These values must match for an upgrade to be allowed., NSLocalizedDescription=App installation failed}
2016-09-23 13:05:38.828 xcodebuild[24064:2895330] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **
```

**Comment by yaphatak** [comment]
I dont think we can do anything at this point , just search for this error message. As this is generic messages for either something wrong with cert/ provision profile or device

**Comment by ngreeney** [comment]
Thanks for the help yaphatak.

I did figure it out in case anyone else runs into this. Key was that it said an upgrade is not allowed since I had changed to cert at some point after it had installed a broken version on the phone.

By deleting the WebDriverAgent on the phone it fixed all the issues and got me to the `Listening on USB` line

**Comment by shreyasdraut** [comment]
i am getting Testing failed:
	'OSAtomicOr32Barrier' is deprecated: first deprecated in iOS 10.0 - Use atomic_fetch_or() from <stdatomic.h> instead

**Comment by yaphatak** [comment]
@shreyasdraut : My best guess is you are using old version of `appium-xcuitest-driver`

**Comment by pavanbachu0604** [comment]
_writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/d9/nbk40gxs49g8n6k71zg08gdsn6nf8h/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/26c7f03105e60d9077113bb2c41efd56/a2e0b888c9c53dfc03d3b27d4ef7b2c7b5abd9d8/ManifestCache.plist
2016-09-23 21:21:56.172177 XCTRunner[1417:427670] Running tests...
2016-09-23 21:21:56.261666 XCTRunner[1417:427670] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2016-09-23 21:21:56.262263 XCTRunner[1417:427670] (dlopen_preflight(/var/containers/Bundle/Application/4EC74A13-0960-4B5F-BFEE-7150BAB6C36E/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/KissXML.framework/KissXML
  Referenced from: /private/var/containers/Bundle/Application/4EC74A13-0960-4B5F-BFEE-7150BAB6C36E/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/WebDriverAgentLib
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/4EC74A13-0960-4B5F-BFEE-7150BAB6C36E/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/KissXML.framework/KissXML: code signature invalid for '/private/var/containers/Bundle/Application/4EC74A13-0960-4B5F-BFEE-7150BAB6C36E/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/Frameworks/WebDriverAgentLib.framework/Frameworks/KissXML.framework/KissXML'
)
2016-09-23 21:21:55.982 xcodebuild[2534:29563] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)_



I am getting the above error; I am not having any issues in Xcode

**Comment by pavanbachu0604** [comment]
I am getting this error
<img width="683" alt="screen shot 2016-09-26 at 6 23 44 pm" src="https://cloud.githubusercontent.com/assets/21222084/18854020/88110b7e-8416-11e6-9ad2-9439dea3174e.png">

**Comment by ngreeney** [comment]
You need to select a Team that has a provisioning profile that has a wild card for the app ID so it will allow com.facebook

**Comment by pavanbachu0604** [comment]
<img width="716" alt="screen shot 2016-09-27 at 9 58 18 am" src="https://cloud.githubusercontent.com/assets/21222084/18876840/2ba0c360-8499-11e6-8f9d-a615aa81bc10.png">

**Comment by ngreeney** [comment]
The build settings are saying one type of cert is needed and the General tab is saying another. Hence the conflict.

I would reinstall the package as I am guessing something in the Build Settings got changed along the way or you are on an older version of it.

**Comment by shreyasdraut** [comment]
@yaphatak can you tell me what is the latest code because i tried to solve this :
i am getting Testing failed:
'OSAtomicOr32Barrier' is deprecated: first deprecated in iOS 10.0 - Use atomic_fetch_or() from instead

however i still am not able to resolve the issue

**Comment by ngreeney** [comment]
@shreyasdraut this has nothing to do with the issue being discussed. Please make a new issue.
