### ISSUE TITLE
scroll and click not working for Appium

### ISSUE THREAD

**Issue by LokeshGangaiah** [appium/appium#6886]
## The problem

I am trying to scroll and its not working for both Android and iOS
Did try with ScrollTO and ScrollToExact as both of them are deprecated now, so did try with this:

        String str = "CADILLAC";
        driver.findElementByAndroidUIAutomator("new UiScrollable(new  UiSelector().scrollable(true).instance(0)).scrollIntoView(new  UiSelector().textContains(\""+str+"\").instance(0))").click();
Still not working

## Environment

* Appium version (or git revision) that exhibits the issue:1.4.16
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Window 8
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 5.0OS
* Real device or emulator/simulator: Real device - samsung s4
* Appium CLI or Appium.app|exe:

## Details

Did go through many blogs , videos , course content and material no one has explained or there a specific solution on how to handle this

Did try with below,still gets the error "org.openqa.selenium.WebDriverException:"

## Link to Appium logs

https://gist.github.com/LokeshGangaiah/e645ccebb3a12557953fe1c45c0ad231

Eclipse log https://gist.github.com/LokeshGangaiah/2dc32a516b545e402a0191dd44db571a

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by SrinivasanTarget** [comment]
There has been lot of changes in server post 1.4.x. Please try a latest version of appium which is 1.6 now and raise a new issue incase if you hit the same.

**Comment by SrinivasanTarget** [comment]
@triager please close
