### ISSUE TITLE
Error: Unable to find real device logging program 'deviceconsole'

### ISSUE THREAD

**Issue by Hellengo** [appium/appium#6887]
## The problem

xCode 8, iOS 10 not working with the beta version of appium 1.6.0

Error: Unable to find real device logging program 'deviceconsole'

## Details
log:
https://gist.github.com/Hellengo/621462fa20671bc7406f5f94b544cd0d

**Comment by imurchie** [comment]
You need to install `deviceconsole`. `npm install -g deviceconsole`. If it installs in a place not on the PATH, use `realDeviceLogger` capability to specify the exact location.

**Comment by Hellengo** [comment]
➜  ~ npm install -g deviceconsole

> deviceconsole@1.0.1 install /Users/Hellengo/.npm-packages/lib/node_modules/deviceconsole
> make

Making deviceconsole...
/Users/Hellengo/.npm-packages/lib
└── deviceconsole@1.0.1


>ln -fs /Users/Hellengo/.npm-packages/lib/node_modules/deviceconsole/deviceconsole /usr/local/bin/deviceconsole

**Comment by Hellengo** [comment]
thanks, npm install -g deviceconsole fixed the issue, but now I am getting 'xcodebuild failed with code 65' error, any thought?

Logs:
https://gist.github.com/Hellengo/8bc4d027d9dd9adada6813b245ba0b2f

**Comment by imurchie** [comment]
That problem is discussed in other issues. Mostly it's a signing issue. Use the `showXcodeLog` cap to get the output from xcodebuild.
