### ISSUE TITLE
[XCUITest] Make the delay between application install and startup configurable

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#6889]
## The problem

Sometimes application under test fails to start properly because of race condition if the size of application under test is big enough.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0-beta2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.11.6
* Node.js version (unless using Appium.app|exe): 5.4.1
* Mobile platform/version under test: 9.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

The problem is described here in more details: https://forums.developer.apple.com/thread/25221
If the app is big enough and we try to launch it right after the installation then the system might send SIGKILL to it preventing the app from starting. Here is how it looks like in Simulator log:

```
ep 23 10:27:38 Nick CoreSimulatorBridge[33314]: Requesting launch of com.wearezeta.zclient-alpha with options: {
        arguments =     (
           ...
        );
        environment =     {
            NSUnbufferedIO = YES;
        };
        stderr = "/dev/ttys005";
        stdout = "/dev/ttys005";
        "wait_for_debugger" = 0;
    }
Sep 23 10:27:38 Nick assertiond[33310]: assertion failed: 15G1004 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
Sep 23 10:27:40 Nick searchd[33366]: tcp_connection_tls_session_error_callback_imp 5 __tcp_connection_tls_session_callback_write_block_invoke.434 error 22
Sep 23 10:27:41 Nick searchd[33366]: tcp_connection_tls_session_error_callback_imp 6 __tcp_connection_tls_session_callback_write_block_invoke.434 error 22
Sep 23 10:27:41 Nick mstreamd[33296]: (Note ) PS: Media stream daemon stopping.
Sep 23 10:27:41 Nick mstreamd[33296]: (Note ) AS: <MSIOSAlbumSharingDaemon: 0x7fa84050e1f0>: Shared Streams daemon has shut down.
Sep 23 10:27:41 Nick mstreamd[33296]: (Warn ) mstreamd: mstreamd shutting down.
Sep 23 10:27:58 Nick com.apple.CoreSimulator.SimDevice.949BAA5F-9949-453C-920D-DFD7522662F5.launchd_sim[33290] (UIKitApplication:com.wearezeta.zclient-alpha[0xd139][33524]): Service exited due to signal: Killed: 9
Sep 23 10:27:58 Nick SpringBoard[33306]: Application 'UIKitApplication:com.wearezeta.zclient-alpha[0xd139]' exited abnormally via signal.
Sep 23 10:28:06 Nick searchd[33366]: tcp_connection_destination_handle_tls_close_notify 3 closing socket due to TLS CLOSE_NOTIFY alert
Sep 23 10:28:06 Nick searchd[33366]: tcp_connection_tls_session_error_callback_imp 7 __tcp_connection_tls_session_callback_write_block_invoke.434 error 22
Sep 23 10:28:58 Nick coresymbolicationd[33543]: /Users/elf/Library/Developer/CoreSimulator/Devices/949BAA5F-9949-453C-920D-DFD7522662F5/data/Library/Caches/com.apple.coresymbolicationd/data does not exist, resetting cache
Sep 23 10:28:59 Nick XCTRunner[33508]: Enqueue Failure: UI Testing Failure - '<XCUIApplicationImpl: 0x7fbba8ea04d0 com.wearezeta.zclient-alpha at /var/folders/4s/4pd60d1j5cj2bkg1lr_s5c100000gn/T/2016823-4417-izg3qz/Payload/Wire.app>' App state is still not running active, state = XCApplicationStateNotRunning /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
```

As a workaround we might add a capability to make the delay between application install and startup configurable to avoid the race condition and thus fix the problem.

**Comment by mykola-mokhnach** [comment]
I've also created an issue in WebDriver project and got the same recommendation from the author: https://github.com/facebook/WebDriverAgent/issues/298

**Comment by imurchie** [comment]
The driver already installs the application before launching WDA and starting the test. Does the application not get installed fully?

**Comment by mykola-mokhnach** [comment]
Yeah, looks like there is some kind of race condition when we try to start the app before it was fully installed. It's easier to reproduce if application package is big enough (26 MB .ipa file in my case).

**Comment by imurchie** [comment]
Ok! I'll have a look at how to get this working.

**Comment by mykola-mokhnach** [comment]
Thanks @imurchie. I'd appreciate it.

**Comment by imurchie** [comment]
Hmm. I can't reproduce this. I just ran tests against a 350 mb app with no problems.

Can you give more info? Full logs? Anything might help.

**Comment by mykola-mokhnach** [comment]
Unfortunately there is not so much info. We randomly experience this problem while running tests in our local automation lab while IO and CPU load are high, since there are multiple virtual machines on this node.

**Comment by yaphatak** [comment]
@mykola-mokhnach : `appium` install app itself. It doesn't use `WDA` to install app.

**Comment by mykola-mokhnach** [comment]
@yaphatak I've checked this in source code:

_appium-xcuitest-driver/build/lib/driver.js_

```javascript
async start () {
...
    await this.installApp();

    await this.startWda(this.opts.sessionId, realDevice);

    await this.setInitialOrientation(this.opts.orientation);
....
```

and _installApp_ method is exported from 

_node-simctl/build/lib/simctl.js_

which simply executes _simctl_ command line tool with corresponding parameters and waits until it returns an exit code. The problem here is, that simctl might, and, actually, does, return a result before the app is fully installed on Simulator. I've tried to just put a hardcoded delay in _installApp_ method after _simctl install_ command is executed and this trick solved the issue:

``` javascript
async function installApp (udid:string, appPath:string):void {
  await simExec('install', 0, [udid, appPath]);
  await exec('sleep 5');
}
```

**Comment by imurchie** [comment]
Alright. Seems reasonable, if it is configurable. Alternatively we could wait for the logs to tell us that the application has been installed, though that comes with its own gang of problems.

**Comment by imurchie** [comment]
This is available now. Use the `iosInstallPause` cap, which takes a time in milliseconds.

**Comment by mykola-mokhnach** [comment]
@imurchie Already did. Many thanks!
