### ISSUE TITLE
adb: stop: must be root; can't launch tests on Android 7.0

### ISSUE THREAD

**Issue by oscheller1** [appium/appium#6894]
## The problem

Can not launch tests on Android 7.0. When launching the test, I run into the following error:  

selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: Command '/Users//Library/Android/sdk/platform-tools/adb -P 5037 -s shell stop' exited with code 1{"stdout":"","stderr":"stop: must be root\n","code":1}
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3.
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3.
- Desktop OS/version used to run Appium: Mac OS X 10.11.4
- Node.js version (unless using Appium.app|exe): -
- Mobile platform/version under test: Android 7.0
- Real device or emulator/simulator: Nexus 9 real device
- Appium CLI or Appium.app|exe: Appium.app
## Details

Running the test with exact same parameters on an Android 6.0 device works without problems.
Probably an ADB problem, not Appium related. Still asking here for a way to fix if possible.

**Comment by imurchie** [comment]
Can you provide a link to a [gist](https://gist.github.com/) of the entire server log? `adb stop` is the last thing that we have not yet figured out how to handle in order to fully automate Android 7, but it is unclear what is sending the command here, so I can't help you at all at the moment.

**Comment by oscheller87** [comment]
Gist: https://gist.github.com/oscheller87/754fbed951ef4069213c2df496a98773

**Comment by imurchie** [comment]
Ah, yes. Setting the language is causing a reboot of the device, and Appium cannot currently stop the app. We are looking into how to do this.
