### ISSUE TITLE
Is this the Appium CLA?

### ISSUE THREAD

**Issue by hyandell** [appium/appium#6897]
Is the Appium CLA simply this text:

"By submitting your Contribution to the Appium Project, You hereby agree to license your Contribution under the Apache License, Version 2.0, and to include the appropriate copyright notice required by the license.  "

Or is there another document somewhere?

Apologies for asking, but it's unusual (but nice) to have it so small :)

[ https://docs.google.com/forms/d/e/1FAIpQLSfmNZYamjlCfug73CZyosCgairZnlmK9IP6FtTMj01C_cSkIQ/viewform ]

**Comment by imurchie** [comment]
That form is it.
