### ISSUE TITLE
#Xcode 8 iOS10.0 : Unable to launch appium

### ISSUE THREAD

**Issue by nlnarasimhamurthy** [appium/appium#6899]
## The problem

Unable to launch appium and simulator after upgrading the xcode to 8.0. None of the versions of simulator working, either 9.3 or 10.0.

## Environment

* Appium.app version (1.4.13) # verified in Appium 1.5 version as well
* EI Captain latest update
* Node.js version (v6.3.0):
* iOS platform/version (10.0)

## Appium logs

error: Failed to start an Appium session, err was: Error: Bad app: /Users/cdtasvc-jnk/Downloads/360ONE.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name. cause: Error: Error locating the app: ENOENT, stat '/Users/cdtasvc-jnk/Downloads/360ONE.app'

info: [debug] Using local app from command line: /Users/cdtasvc-jnk/Downloads/360ONE.app
info: [debug] Got configuration error, not starting session
info: [debug] Cleaning up appium session
info: [debug] Error: Bad app: /Users/cdtasvc-jnk/Downloads/360ONE.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name. cause: Error: Error locating the app: ENOENT, stat '/Users/cdtasvc-jnk/Downloads/360ONE.app'
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:188:13)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/device.js:82:16
    at FSReqWrap.oncomplete (fs.js:95:15)
info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Bad app: /Users/cdtasvc-jnk/Downloads/360ONE.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name. cause: Error: Error locating the app: ENOENT, stat '/Users/cdtasvc-jnk/Downloads/360ONE.app')","origValue":"Bad app: /Users/cdtasvc-jnk/Downloads/360ONE.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name. cause: Error: Error locating the app: ENOENT, stat '/Users/cdtasvc-jnk/Downloads/360ONE.app'"},"sessionId":null}

**Comment by imurchie** [comment]
Are you running Appium 1.4.13 (and/or 1.5)? These will **never** be able to automate iOS 10, or anything using Xcode 8. The technology they use to automate ios devices is gone in Xcode 8. You will need to use an Appium 1.6.0 beta.

**Comment by nlnarasimhamurthy** [comment]
Hi Isaac,

I tried with both 1.4.13 and 1.5.3 versions of Appium, but the result is
same.

So, where can i find *Appium 1.6.0* dmg file.? Kindly let me know.

*Thanks and Regards,*

*-Narasimhamurthy*

**Comment by imurchie** [comment]
There is no 1.6.0 dmg yet, as the server is in beta. You can install the server using `npm install -g appium@beta`.

**Comment by nlnarasimhamurthy** [comment]
Thanks for the information.

*Thanks and Regards,*

*-Narasimhamurthy*
