### ISSUE TITLE
Appium 1.6Beta2 - Reset App fails

### ISSUE THREAD

**Issue by Reedyuk** [appium/appium#6905]
## The problem

When performing the driver command "reset", appium server throws an exception(find attached log).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0-beta2
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: Mac 10.12
* Node.js version (unless using Appium.app|exe): 6.2.2
* Mobile platform/version under test: iOS 10 Xcode 8
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

[gist](https://gist.github.com/Reedyuk/068f9459463fa23d40ce2a752a878f59)

## Code To Reproduce Issue [ Good To Have ]

In java, simply using the driver.resetApp(); method causes the failure.
[log from java](https://gist.github.com/Reedyuk/079cb059d3d8e919cefce32aa2307804)

**Comment by imurchie** [comment]
Can you provide more of the logs in order to get to the bottom of this? The more the better. The _full_ logs are best. As a gist.

**Comment by Reedyuk** [comment]
Are those two gists, i embedded not enough? 
It looks to me like, whencalling the resetApp, it has lost the path to the app or the namespace of the app.
`[iOS] Something went wrong while launching the [undefined] app.`
`org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Path must be a string. Received undefined (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.50 seconds`
If i get time, i might try and create a sample project for you.

**Comment by imurchie** [comment]
No. At the very least the entire command (from the incoming http request to the outgoing response) are needed. But things also depend on configuration, etc.

**Comment by amedvedjev** [comment]
tried with latest version which contains updated components and now it is working.

the current behaviour is: emulator closing -> emulator opening -> client reinstalling. Not nice way (takes long time)

**Comment by imurchie** [comment]
Can you try with the latest code? I have pulled in the old ios driver reset logic.

**Comment by amedvedjev** [comment]
look like working 👍  added into test and left for night. let see how stable it working...

**Comment by jlipps** [comment]
We'll reopen if there are further problems, thanks @amedvedjev!

**Comment by Reedyuk** [comment]
Hi, yes, i can confirm that its working for me too.

Thanks

**Comment by adasGit** [comment]
Need help with,
IosDriver().resetApp();

I get the following error! :/ It was working in older version - 1.4.13

org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

**Comment by imurchie** [comment]
Can you post a [gist](https://gist.github.com) of the full server logs?

**Comment by adasGit** [comment]
Hope this would help to analyze.

[idevicesyslog.docx](https://github.com/appium/appium/files/578477/idevicesyslog.docx)

**Comment by imurchie** [comment]
I cannot open a Word document. Please post a [gist](https://gist.github.com) of the Appium server logs.

**Comment by adasGit** [comment]
Added the following gist to take a look please,
https://gist.github.com/adasGit/9c93ef8c7b814282e5f7c5baf332c557

**Comment by imurchie** [comment]
Can you provide the Appium logs? The should start with something like

```
[Appium] Welcome to Appium v1.6.1-beta (REV 5817d3125a8cf50f4074190dda4dbfdd60f229bd)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

**Comment by adasGit** [comment]
Could you please help me find the log.
I did npm install appium-ios-log and set capability showIOSLog as true.
Where should i look for the log?
Am i supposed to use APIs startCapture(), stopCapture()? but how?

**Comment by imurchie** [comment]
Wherever you have run the server, it is the standard output. If you run Appium using the command `appium`, it is whatever comes next.

**Comment by adasGit** [comment]
Here it is, thank you.
https://gist.github.com/adasGit/6c190a7166f63873c70abe3cc7396c43

**Comment by imurchie** [comment]
This should be fixed in the latest version. Can you try that?

```
npm uninstall -g appium
npm install -g appium@beta
```

**Comment by adasGit** [comment]
It works!! :)
Using appium@beta
Thank you very much.
