### ISSUE TITLE
Appium 1.6beta2 Real device - After starting iproxy to forward traffic from local port 8100   

### ISSUE THREAD

**Issue by Nesaganesh** [appium/appium#6907]
Hello,

I am stuck with the below line, can someone please help me out.

[Xcode] /Users/nesag/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app: replacing existing signature

[Xcode]

[Xcode] MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/mh/0qzhsjy9449ccxw8xl75vzshk02zy3/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/59099c12cc4a6b152cfa48c8f1dc0326/82f38c6f825a4644d0e4e259ce12d31030057e4e/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/nesag/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/mh/0qzhsjy9449ccxw8xl75vzshk02zy3/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.qQejpN/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
dst_ipa: /var/folders/mh/0qzhsjy9449ccxw8xl75vzshk02zy3/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.qQejpN/WebDriverAgentRunner-Runner.app_sparse.ipa

[Xcode] __MDMDirectoryDiff_block_invoke.37:1473 calling writeDictToFile with: /var/folders/mh/0qzhsjy9449ccxw8xl75vzshk02zy3/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.qQejpN/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

[Xcode] writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/mh/0qzhsjy9449ccxw8xl75vzshk02zy3/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.qQejpN/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [WebDriverAgent] Device: Sep 28 17:45:31 DarrenGs-iPhone XCTRunner[1071] : Running tests...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [WebDriverAgent] Device: Sep 28 17:45:32 DarrenGs-iPhone XCTRunner[1071] : Continuing to run tests in the background with task ID 1
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[XCUITest] Detected that WebDriverAgent is running at url 'http://192.168.59.97:8100'
[XCUITest] WebDriverAgent started at url 'http://192.168.59.97:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bu...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[HTTP] <-- POST /wd/hub/session - - ms - - 
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
Terminal1:
cd /usr/local/Cellar/ios-webkit-debug-proxy/1.7 && ios_webkit_debug_proxy -c 82f38c6f825a4644d0e4e259ce12d31030057e4e:27753 -d

Terminal2:
appium -U 82f38c6f825a4644d0e4e259ce12d31030057e4e -p 4723 --full-reset --webkit-debug-proxy-port 27753 --tmp /tmp/ios/

From C# code:
var remoteAddress = new Uri(Constants.SeleniumGrid);
var capabilities = new DesiredCapabilities();
capabilities.SetCapability(CapabilityType.BrowserName, "IOSNATIVE");
capabilities.SetCapability(MobileCapabilityType.PlatformVersion, "10.0");
capabilities.SetCapability("automationName", "XCUITest");
capabilities.SetCapability("newCommandTimeout", "9000");
capabilities.SetCapability(MobileCapabilityType.DeviceName, "iPad Air");
capabilities.SetCapability("platformName", "iOS");
capabilities.SetCapability("sendKeyStrategy", "setValue");
capabilities.SetCapability("--no-reset", false);
capabilities.SetCapability(MobileCapabilityType.PlatformName, "iOS");
capabilities.SetCapability(MobileCapabilityType.AppPackage, "uk.co.derivco.betway.sports");
capabilities.SetCapability(MobileCapabilityType.DeviceName, "IOSDevice");
capabilities.SetCapability(MobileCapabilityType.App, Constants.NativeAppPath);

```
    capabilities.SetCapability("showXcodeLog", "true");
    Driver = new IOSDriver<IWebElement>(remoteAddress, capabilities);
```

time curl -X GET '-H "Content-Type: application/json"' http://192.168.59.97:8100/status
{
"sessionId" : "BA72F22B-BE7C-4BE4-910A-E7273628CAEF",
"value" : {
"state" : "success",
"os" : {
"name" : "iOS",
"version" : "10.0.1"
},
"ios" : {
"simulatorVersion" : "10.0.1"
},
"build" : {
"time" : "Sep 28 2016 17:45:36"
}
},
"status" : 0
}
real 0m0.104s
user 0m0.005s
sys 0m0.010s

**Comment by Nesaganesh** [comment]
[iOSLog] [IOS_SYSLOG_ROW] Sep 29 00:09:09 DarrenGs-iPhone SpringBoard(SpringBoard)[759] <Info>: Set device motion sensor status <private>
[iOSLog] [IOS_SYSLOG_ROW] Sep 29 00:09:09 DarrenGs-iPhone XCTRunner(WebDriverAgentLib)[1131] <Notice>: ServerURLHere->http://192.168.0.21:8100<-ServerURLHere
[XCUITest] Detected that WebDriverAgent is running at url 'http://192.168.0.21:8100'
[XCUITest] WebDriverAgent started at url 'http://192.168.0.21:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8200 to device port 8100 over USB
[iOSLog] [IOS_SYSLOG_ROW] Sep 29 00:09:09 DarrenGs-iPhone XCTRunner(WebDriverAgentLib)[1131] <Notice>: Listening on USB
[iOSLog] [IOS_SYSLOG_ROW] Sep 29 00:09:09 DarrenGs-iPhone backboardd[62] <Info>: client com.apple.test.WebDriverAgentRunner-Runner - (1131) updated deferrals to {(
[iOSLog] [IOS_SYSLOG_ROW] )}
[iOSLog] [IOS_SYSLOG_ROW] Sep 29 00:09:09 DarrenGs-iPhone SpringBoard(KeyboardArbiter)[759] <Info>: HW kbd: currently com.apple.test.WebDriverAgentRunner-Runner ((null) < (null))
[iOSLog] [IOS_SYSLOG_ROW] Sep 29 00:09:09 DarrenGs-iPhone SpringBoard(KeyboardArbiter)[759] <Error>: HW kbd: Failed to set (null) as keyboard focus
[XCUITest] Error: iproxy  exited with code '208'
    at SubProcess.<anonymous> (lib/webdriveragent.js:344:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: iproxy  exited with code '208'
    at SubProcess.<anonymous> (lib/webdriveragent.js:344:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[XCUITest] Shutting down WebDriverAgent
[Xcode] ** BUILD INTERRUPTED **

**Comment by Jitu1888** [comment]
Please help me out 
In my case it is getting stuck on
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...

Even i added realDeviceLogger capability.

Environment
1. iPad: 10.1
2. Appium 1.6.2
3. Xcode: 8.1

Please help me out of this

**Comment by kenmcc** [comment]
is the device stuck on a black screen, showing the battery symbol?

**Comment by r-ni** [comment]
I have the same issue as you, Jitu1888.
All works fine on appium-1.6.1, after updating to 1.6.2 have 
Waiting for WebDriverAgent server to finish loading...
And nothing happened.

**Comment by Jitu1888** [comment]
Use 1.6.1 only, WDA package was not upgraded with appium version 1.6.2 and
1.6.3. So the proxy connection is failing

**Comment by r-ni** [comment]
So, 1.6.2 and 1.6.3 doesn't work with ios10? Can't believe.

**Comment by Jitu1888** [comment]
It will work if you take latest WDA from git.

**Comment by r-ni** [comment]
Works with appium@1.6.3 but super slow. Downgraded to 1.6.1 again.
