### ISSUE TITLE
How can we install appium beta to run IOS tests with XCUITEST

### ISSUE THREAD

**Issue by tolgatanriverdi** [appium/appium#6912]
Hi

I'm trying to install appium beta 1.6 in order to run ios 10 apps with xcuitest
But I couldnt find any documentation about that.
We have an application in production and now we cannot run tests on IOS 10
Could you please help me about the issue?
Thanks

**Comment by imurchie** [comment]
Install with `npm install -g appium@beta`.

**Comment by tolgatanriverdi** [comment]
Thanks I've installed it but this time it gave the below error, do I have to change anything from java-client side also

```
[debug] [iOS] Xcode version set to 8.0
[iOS] SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.
    at IosDriver.createSession$ (lib/driver.js:120:28)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
 { [SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.] jsonwpCode: 33 }
```

**Comment by imurchie** [comment]
Have you tried using `XCUITest` as `automationName`, as the error suggests?

**Comment by tolgatanriverdi** [comment]
Ok and now it gives this error,
Sorry for bothering but it constantly gives errors

```
[MJSONWP] Encountered internal error running command: Error: Platform version must be 9.3 or above. '9.1' is not supported.
    at Error (native)
    at XCUITestDriver.start$ (lib/driver.js:158:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```

**Comment by tolgatanriverdi** [comment]
Now its giving this error


```
[XCUITest] Shutting down WebDriverAgent
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:66:19)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by tolgatanriverdi** [comment]
Sorry to bother again. I've fixed all the previous erros but now it shows a different kind of error, which I didnt understand anything. Before IOS 10 I was using ipa files to start tests with appium, but now  when I try to use the same ipa file(Only difference is, its compiled with ios 10)
it gave the below error. What should I do?

Thanks

```

[Xcode] 
Testing failed:
	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'
** TEST FAILED **
```

**Comment by imurchie** [comment]
https://github.com/appium/appium-xcuitest-driver#real-devices

**Comment by tolgatanriverdi** [comment]
I've followed the guide that you showed, however I still got the same error
And also when I run the appium webdriver agent quits suddenly with following error:

```
Test Suite 'All tests' started at 2016-09-29 21:10:17.218
Test Suite 'WebDriverAgentRunner.xctest' started at 2016-09-29 21:10:17.221
Test Suite 'UITestingUITests' started at 2016-09-29 21:10:17.222
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2016-09-29 21:10:17.226
    t =     0.01s     Set Up
2016-09-29 21:10:17.236089 XCTRunner[554:54840] Built at Sep 29 2016 21:08:14
2016-09-29 21:10:17.272499 XCTRunner[554:54840] ServerURLHere->http://192.168.2.245:8100<-ServerURLHere
2016-09-29 21:10:17.273985 XCTRunner[554:54840] Listening on USB
** BUILD INTERRUPTED **
Terminated: 15
```


And this is the appium's log:

```
[Xcode] 
Testing failed:
	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'

[Xcode] ** TEST FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:260:25)
    at emitTwo (events.js:87:13)
    at SubProcess.emit (events.js:172:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
 [Error: xcodebuild failed with code 65]
[XCUITest] Shutting down WebDriverAgent
[XCUITest] System log exited with code '0'
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:260:25)
    at emitTwo (events.js:87:13)
    at SubProcess.emit (events.js:172:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by imurchie** [comment]
You need to use a developer team in the project.

**Comment by tolgatanriverdi** [comment]
I'm using the same team in both WebDriverAgentRunner and also in the ipa project that I'm going to test

**Comment by imurchie** [comment]
Again, please see other threads about this issue.

**Comment by tolgatanriverdi** [comment]
I've looked to the other threads  but couldnt find a solution.
I dont know why webdriveragents stops with below message:

** BUILD INTERRUPTED **

**Comment by tolgatanriverdi** [comment]
About the documentations there is only one step that I've failed and cannot find a solution about it is in below. Can it be the source of the problem

```
WebDriverAgent nts$ ./Scripts/bootstrap.sh
Fetching dependencies
Building Inspector
Creating bundle directory...
Building inspector.js...

> web-driver-inspector@1.0.0 build /usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector
> webpack --progress --colors

sh: webpack: command not found

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! web-driver-inspector@1.0.0 build: `webpack --progress --colors`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the web-driver-inspector@1.0.0 build script 'webpack --progress --colors'.
npm ERR! This is most likely a problem with the web-driver-inspector package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --colors
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-driver-inspector
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/npm-debug.log
Error occured during 'npm run build', please check npm build log
```

**Comment by imurchie** [comment]
There is `-d` in the command. `./Scripts/bootstrap.sh -d`

**Comment by tolgatanriverdi** [comment]
When I run with the -d parameter it only gives this output to console:

```
MacBook-Pro:WebDriverAgent nts$ ./Scripts/bootstrap.sh -d
**Fetching dependencies**
MacBook-Pro:WebDriverAgent nts$ 
```

**Comment by mykola-mokhnach** [comment]
Try

```bash
npm install -g webpack
```

**Comment by mykola-mokhnach** [comment]
@tolgatanriverdi Also, to test webdriver installation on a real device you need to open it with Xcode (usually it is installed to _/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent_ folder). Select WebDriverAgentRunner target and press Cmd+U (Product->Test). If this succeeds then there's very high probability, that it works with Appium as well.
The second step would be to make sure, that your app can be installed into the same device. Make sure you have ios-deploy package installed on your system 

```
npm install -g ios-deploy
```

Then get your application as .app package (it should be already signed with development signature - the same one, which was used to sign WebDriver) and execute the following command:

```
ios-deploy --id <device_udid> --uninstall --bundle <app_path> --verbose
```

The application should be successfully installed as a result and there should be no errors in verbose log.

**Comment by tolgatanriverdi** [comment]
Thanks mykola

I've followed the steps that you suggested. And installed everything succesfully.
But the result is same
WebDriverAgent quits with the below console output:

```
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2016-10-02 20:28:43.465
    t =     0.01s     Set Up
2016-10-02 20:28:43.475219 XCTRunner[735:143813] Built at Oct  2 2016 20:28:32
2016-10-02 20:28:43.514845 XCTRunner[735:143813] ServerURLHere->http://192.168.2.245:8100<-ServerURLHere
2016-10-02 20:28:43.516414 XCTRunner[735:143813] Listening on USB
** BUILD INTERRUPTED **
Terminated: 15

```


And also , the appium console output can be found below: (Same as previous errors)

```
[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'


[Xcode] 
Testing failed:
	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'

[Xcode] ** TEST FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:260:25)
    at emitTwo (events.js:87:13)
    at SubProcess.emit (events.js:172:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
 [Error: xcodebuild failed with code 65]
[XCUITest] Shutting down WebDriverAgent
[XCUITest] System log exited with code 'null'
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:260:25)
    at emitTwo (events.js:87:13)
    at SubProcess.emit (events.js:172:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
[HTTP] <-- POST /wd/hub/session 500 7291 ms - 167 

```

**Comment by mykola-mokhnach** [comment]
I think the log output is pretty clear here - you should use developer signature for signing (both components: WebDriverAgentRunner and WebDriverAgentLib should be signed with it). Enterprise signature won't work.

**Comment by tolgatanriverdi** [comment]
I've already opened WebDriverAgent.xcodeproj file with xcode and selected the development team as code signing profile
When I run the WebDriverAgentRunner it succesfully install the webdriver to phone and execute the application and take it to background succesfully.
But the appium result still the same

**Comment by tolgatanriverdi** [comment]
And also, when I run the ./Scripts/bootstrap.h , I get the following error:


```
./Scripts/bootstrap.sh
Fetching dependencies
Building Inspector
Creating bundle directory...
Building inspector.js...

> web-driver-inspector@1.0.0 build /usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector
> webpack --progress --colors

Hash: 9ed7d0b85cc08341fd0f  
Version: webpack 1.13.2
Time: 66ms
   [0] multi main 28 bytes {0} [built] [1 error]
    + 1 hidden modules

ERROR in ./js/app.js
Module parse failed: /usr/local/lib/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/js/app.js Unexpected token (59:4)
You may need an appropriate loader to handle this file type.
```

**Comment by imurchie** [comment]
There should be no reason to run that shell script. And if you do for some reason want to, the command needs a `-d`.

**Comment by tolgatanriverdi** [comment]
So , that I couldnt find a way to solve this problem and run the app tests on IOS 10 device.
I always get build interrupted message from WebDriverAgent (Even though I'm using development profile to sign it)

and get the below error from appium:

```
[Xcode] 
Testing failed:
    Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
    Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'

[Xcode] ** TEST FAILED **
```

What should be the problem?

**Comment by imurchie** [comment]
Can you try using an xcconfig file instead? Make sure you have the latest version of the beta (with `appium-xcuitest-driver` version 2.0.21. And follow the initial directions here: https://github.com/appium/appium-xcuitest-driver#real-devices

**Comment by tolgatanriverdi** [comment]
How can I use xcconfig file?

**Comment by imurchie** [comment]
https://github.com/appium/appium-xcuitest-driver#real-devices

**Comment by tolgatanriverdi** [comment]
I'm using a wildcard development profile, does it make any difference?

**Comment by imurchie** [comment]
No. That works.

**Comment by tolgatanriverdi** [comment]
But the result is same.
I couldnt find any solution to this problem

**Comment by mikhailpractice** [comment]
@tolgatanriverdi Need your help, How did you fix "bootstrap.sh -d" issue??? Thanks

**Comment by AllocAndInit** [comment]
@imurchie  i have go to the ./WebDriverAgent When I run ./Scripts/bootstrap.sh -d it only gives this output to console:
Fetching dependencies and nothing else
and I have try npm install -g webpack
what happend? Could you help me  ?

**Comment by AllocAndInit** [comment]
@imurchie 
![snip20161101_5](https://cloud.githubusercontent.com/assets/19301846/19883173/b23dcb32-a04d-11e6-8311-a58aa8eed5ae.png)

what should I do ?

**Comment by AllocAndInit** [comment]
@imurchie 
hi
I ran Scripts/bootstrap.sh -d from node_modules/appium-xcuitest-driver/WebDriverAgent and this was the result:
$ Scripts/bootstrap.sh -d
Fetching dependencies

And nothing happens. Is there anything I should do?
thanks

**Comment by imurchie** [comment]
@AllocAndInit That means they are downloaded already.

**Comment by AllocAndInit** [comment]
@imurchie thanks a lot 
but when I launch Appium   I get a problem here is the log 
the version of appium is 1.6.0-beta3
Xcode : 8.0
![snip20161101_7](https://cloud.githubusercontent.com/assets/19301846/19887884/29ee413a-a066-11e6-9b42-23ade719ca81.png)

**Comment by AllocAndInit** [comment]
@imurchie  how can I solve this problem
thanks for your help

**Comment by imurchie** [comment]
@AllocAndInit Can you provide the full logs as a [gist](https://gist.github.com)? This does not looks like Appium 1.6.0, but I cannot tell from what you've given.

**Comment by AllocAndInit** [comment]
@imurchie  OK Thank you very much

this is the gist 
https://gist.github.com/AllocAndInit/c5a8dcefc6d4960f86245183ec8983e5

I would appreciate your help 
thanks a lot

**Comment by AllocAndInit** [comment]
@imurchie  when I excute the command line appium -v 
it shows the   1.6.0-beta3
anything is wrong?

**Comment by imurchie** [comment]
@AllocAndInit  You are running `[Appium] Welcome to Appium v1.5.3`. So the global version and the version you are running are not the same.

**Comment by AllocAndInit** [comment]
@imurchie  when I expect to launch a app in real device , I excute appium -U <UDID> --app <bundle id> command line 
it shows zsh: parse error near `\n'
what is happening? Could you tell me what should I do?

**Comment by AllocAndInit** [comment]
@imurchie yes , you are right , thanks a lot ,Is my problem, I confuse the global version and the version I am running

**Comment by mushtaque87** [comment]
Guys make sure you are signing the project for WebDriverAgent.xcodeproj  in /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/ .   Dont just download the project to desktop or download folder and try to sign the project . 


After installing appium-xcuitest-driver in your system . go to this location /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/ and sign .. this is where appium terminal command pics the WebDriverAgentRunner and build it .
