### ISSUE TITLE
Appium 1.6Beta2: New sessions are being created when old session has yet to be deleted

### ISSUE THREAD

**Issue by JaysonPidgeon** [appium/appium#6913]
## The problem

I am running a XCUITest driver, with the capabilities shown below. The scripts run properly up until a screen change at which point a new appium session is being created (No HTTP call in appium log telling the current session to close). At this point my test cases realize that a driver no longer exists and attempts to create a new driver. I then get the error below labeled `Error 1`. After all of my tests are failed due to Drivers not being created I get the appium line:
```
[HTTP] --> DELETE /wd/hub/session/7b96b7d4-5c45-4a5a-aa4b-3792b882c26e {}
```
This session id is that of my initial session, all other appium sessions created between the creation of the session described above and the deletion of the session described above are only created, not deleted. 

Additionally I have noticed that the automation only ever works when I delete the WebDriverAgent and run the tests again. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6Beta2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: 10.11.6 (El Capitan)
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS 9.3.5
* Real device or emulator/simulator: Real Device

## Details

Capabilities:
```
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/jaysonpidge...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/<Path>/application.ipa'
[Appium]   proxy: null
[Appium]   noReset: true
[Appium]   newCommandTimeout: 420000
[Appium]   realDeviceLogger: 'idevicesyslog'
[Appium]   platformVersion: '9.3.5'
[Appium]   automationName: 'XCUITest'
[Appium]   takesScreenshot: true
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone'
[Appium]   autoAcceptAlerts: true
[Appium]   udid: '<udid>'
[BaseDriver] The following capabilities were provided, but are not recognized by appium: proxy, realDeviceLogger, takesScreenshot.
[BaseDriver] Session created with session id: 7b96b7d4-5c45-4a5a-aa4b-3792b882c26e
```

Error 1:
```
[debug] [XCUITest] Log file for xcodebuild test: /Users/jaysonpidgeon/Library/Developer/Xcode/DerivedData/WebDriverAgent-dnjjhmlvurrbabcucpujrrlqqnen/Logs/Test/9B336995-4871-4219-925C-39B7A4F2B100/Session-WebDriverAgentRunner-2016-09-29_094919-se1Joh.log
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [WebDriverAgent] Device: Sep 29 09:49:28 iPhone XCTRunner[350] <Warning>: Running tests...
[debug] [WebDriverAgent] Device: Sep 29 09:49:28 iPhone XCTRunner[350] <Warning>: Running tests...
[debug] [WebDriverAgent] Device: Sep 29 09:49:28 iPhone XCTRunner[350] <Warning>: Continuing to run tests in the background with task ID 1
[debug] [WebDriverAgent] Device: Sep 29 09:49:28 iPhone XCTRunner[350] <Warning>: Continuing to run tests in the background with task ID 1
[debug] [WebDriverAgent] Device: Sep 29 09:49:29 iPhone XCTRunner[350] <Warning>: Built at Sep 29 2016 09:49:21
[debug] [WebDriverAgent] Device: Sep 29 09:49:29 iPhone XCTRunner[350] <Warning>: Built at Sep 29 2016 09:49:21
[XCUITest] Detected that WebDriverAgent is running at url 'http://172.16.0.158:8100'
[debug] [WebDriverAgent] Device: Sep 29 09:49:29 iPhone XCTRunner[350] <Warning>: ServerURLHere->http://172.16.0.158:8100<-ServerURLHere
[XCUITest] Detected that WebDriverAgent is running at url 'http://172.16.0.158:8100'
[debug] [WebDriverAgent] Device: Sep 29 09:49:29 iPhone XCTRunner[350] <Warning>: ServerURLHere->http://172.16.0.158:8100<-ServerURLHere
[XCUITest] WebDriverAgent started at url 'http://172.16.0.158:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [WebDriverAgent] Device: Sep 29 09:49:29 iPhone XCTRunner[350] <Warning>: Listening on USB
[debug] [WebDriverAgent] Device: Sep 29 09:49:29 iPhone XCTRunner[350] <Warning>: Listening on USB
[XCUITest] Error: iproxy  exited with code '208'
    at SubProcess.<anonymous> (lib/webdriveragent.js:344:25)
    at emitTwo (events.js:87:13)
    at SubProcess.emit (events.js:172:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
 [Error: iproxy  exited with code '208']
[XCUITest] Shutting down WebDriverAgent
[XCUITest] System log exited with code '0'
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: iproxy  exited with code '208'
    at SubProcess.<anonymous> (lib/webdriveragent.js:344:25)
    at emitTwo (events.js:87:13)
    at SubProcess.emit (events.js:172:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by JaysonPidgeon** [comment]
Through debugging my code I found the issue occurs when trying to reset the app i.e.
`driver.resetApp();`

**Comment by imurchie** [comment]
Is there any way to give the full logs (as a gist)? It's hard to see the big picture with a tiny snippet.

**Comment by JaysonPidgeon** [comment]
Unfortunately I cannot give the full log for the issue due to confidentiality. From what I noticed it occurs when `driver.resetApp()` and then when a new driver object is created (due to the loss of the previous one). Sorry that this is not very helpful. I'll try and recreate the issue on a different project.

**Comment by JaysonPidgeon** [comment]
I reproduced using a test on an iOS native settings app. here is the link to the list.
https://gist.github.com/JaysonPidgeon/445b4965255f429f51c1b1034738f2c2

**Comment by imurchie** [comment]
I've updated how we proxy, which ought to fix part of this problem.

However, the new session being created is on the client side. For some reason your client is getting a 500 error and, without killing the old session, tries to start a new session.

https://gist.github.com/JaysonPidgeon/445b4965255f429f51c1b1034738f2c2#file-appiumlogiproxy208error-L498-L499

**Comment by JaysonPidgeon** [comment]
Okay, is this new fix updated into master? I will do more research into what is occurring on the client side to see why a new session is being created.

**Comment by imurchie** [comment]
It is in a dependency of the main appium. If you re-install it should be included.

**Comment by JaysonPidgeon** [comment]
I believe the client side issue stems from my logic for obtaining a Driver. The way I have it setup is to have a thread pool where each thread calls a `getDriver()` method which checks if a driver exists on the current thread. If a driver does exist then that driver is returned. If there is no driver the thread attempts to make a new driver. At this point on appium v 1.5.3 if a session is already in place and another driver tried to get assigned to the already running session a `SessionNotCreatedException` was thrown. I would catch this exception and view that last known instantiated driver object. 

Hopefully my description of my program makes sense. Which brings me to my question. Is the `SessionNotCreatedException` suppose to occur when another session is created while a previous session is already running?

**Comment by imurchie** [comment]
Yes. Currently Appium only handles a single session at a time.

**Comment by JaysonPidgeon** [comment]
Perfect, is there another card which links to supporting the `SessionNotCreatedException` in 1.6.x?

**Comment by imurchie** [comment]
I don't understand what you're asking.

**Comment by JaysonPidgeon** [comment]
Sorry, I mean to say is the behaviour that was present in version 1.5.3 where if a new driver is attempted to be created when there is already a running session that a `SessionNotCreatedException` is thrown.

**Comment by imurchie** [comment]
Yes. That has always been the behavior.

**Comment by JaysonPidgeon** [comment]
Okay thanks, let me know if there is any information I can send to you to help fix this issue :)

**Comment by imurchie** [comment]
It's not really an issue. Changing it is in the plan but requires significant rewrite of the system to allow for non-clobbering of resources.

If you want the old session to get killed and the new to take over, you can start the server with the `--session-override` flag.

**Comment by JaysonPidgeon** [comment]
Okay thanks for the advice. I must have just been confused as to how the future of appium is to function. Thanks for the help!

**Comment by SrinivasanTarget** [comment]
@triager please close
