### ISSUE TITLE
[Android > Kitkat][Hybrid] Alternate mechanism to find webviews other than adb command

### ISSUE THREAD

**Issue by coding-yogi** [appium/appium#6916]
## The problem

Need to find a way to detect webview even if debugging for webview is not enabled in application targeted above Kitkat versions
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: Windows 8
- Node.js version (unless using Appium.app|exe): 5.7.1
- Mobile platform/version under test: Android 6.0
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: Appium CLI
## Details

It seems to find webviews in version above kitkat via below ADB command, webview debugging needs to be enabled explictly in app. But UIAutomator viewer is still able to detect webview in the app. Is it possible to use same mechanism to find webviews

adb shell cat /proc/net/unix

https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/webviews?hl=en#configure-webviews-for-debugging

**Comment by mykola-mokhnach** [comment]
UiAutomator does not have access to the internal application structure and thus cannot detect anything from inside of it. It can only "see" what is passed to the accessibility.
