### ISSUE TITLE
In Appium 1.5.3, unable to launch Safari on real iOS device

### ISSUE THREAD

**Issue by ReinhardXu2007** [appium/appium#6917]
## The problem
Could not start up safari on real iOS device.

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: 10.11.5
* Node.js version (unless using Appium.app|exe): 4.5.0
* Mobile platform/version under test: ios 9.3.2
* Real device or emulator/simulator: iphone5s
* Appium CLI or Appium.app|exe: appium.app with node

## Details
When I tried to start a new session, I got the log:
logs:
```
[debug] [iOS] App is not installed. Will try to install.
[MJSONWP] Encountered internal error running command: Error: Installing /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app failed
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:160:6
```

And after I modified appium-ios-driver/node_modules/node_idevice/main.js to print the install cmd, I got:
`ideviceinstaller -u 81efb4eadca74ab261864f3e4252cb10fe4bc8df -i /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app
`
Then I tried to execute the ideviceinstaller cmd, it shows: 
`Could not connect to lockdownd. Exiting.
`

I tried to execute with sudo, it works, the SafariLauncher could be installed to device.
But how to fix the issue in Appium?

## Code To Reproduce Issue [ Good To Have ]
```
    @Test
    public void test() throws MalformedURLException, InterruptedException {
        DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
        desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone");
        desiredCapabilities.setCapability("udid", "81efb4eadca74ab261864f3e4252cb10fe4bc8df");

        desiredCapabilities.setCapability(MobileCapabilityType.BROWSER_NAME, MobileBrowserType.SAFARI);
        URL url = new URL("http://127.0.0.1:4723/wd/hub");
        this.driver = new IOSDriver<IOSElement>(url, desiredCapabilities);

        driver.get("https://www.baidu.com");
        Thread.sleep(5000L);
        System.out.println(driver.getPageSource());
    }

```

**Comment by imurchie** [comment]
https://github.com/appium/appium/issues/6739

**Comment by ReinhardXu2007** [comment]
@imurchie  thanks, It helps.
As was metioned in https://github.com/libimobiledevice/ideviceinstaller/issues/47
The issue is that /var/db/lockdown is now mode 700.
Solution is:  
chmod -R 777 /var/db/lockdown/
