### ISSUE TITLE
Random issue while replacing sessionId in clicking the <ion-list> hybrid application in iOS devices/android devices

### ISSUE THREAD

**Issue by surajgupta7175** [appium/appium#6921]
## The problem

Hello all, 
I am working on automation of an hybrid application built in ionic2/angular2.

I am trying to click on list i.e ion-list element.

Developers have made the "ion-item" to "button ion-item" to improve the click/tap response at both the places as mentioned in [link](https://ionicframework.com/docs/v2/api/components/item/Item/)

While clicking some times I get an error with replacing sessionID when I use Action/Java script

> Note: I am not able to click using driver
## Environment

Appium 1.5.2 
Chromedriver 2.21

```
Pasting HTML code

<ion-list radio-group *ngIf="showSubGroup && !subgroup.isMultipleSelection">
        <button id="{{subgroup.applicationcode[i].codeys.display}}" ion-item *ngFor="let code of subgroup.applicationcode let i=index">
            <ion-label>{{subgroup.applicationcode[i].codeys.display}}</ion-label>
            <ion-checkbox *ngIf="code.userInput == null" [checked]="code.codeys.selected" (click)="codeysSelected(code.codeys)"></ion-checkbox>

            <ion-textarea id="comment" #textarea [attr.maxLength]="commentAreaMaxLength" (keyup)="textKeyup($event,code.userInput)"
                *ngIf="code.userInput != null" [(ngModel)]="code.userInput.value">
            </ion-textarea>
        </button>
    </ion-list>

```
## Details

I am  using AppiumDriver<IWebElement>, using below code 

```
AppiumDriver<IWebElement> driver = new AndroidDriver<IWebElement>(new Uri(serverUri), capabilities, TimeSpan.FromSeconds(Constants.DriverWaitTime));

driver.FindElement(By.Id("xyz")).Click();
```

**//This gives an error saying. Element is not clickable since other element would receive a click.** (In my view this is due to overlapping ion-list. When I see the HTML I see extra span tag which is overlapping)

Due to this I tried using 
1. Action class (not successful everytime)

```
private static Actions actions = new Actions(Client.AppiumDriver);
private static IWebElement element = null;

element = Client.AppiumDriver.FindElement(By.Id(locator));
actions.MoveToElement(element, 10, 10).Click().Perform();
```
1. Javascript

```
public static IJavaScriptExecutor js = Client.AppiumDriver as IJavaScriptExecutor;

js.ExecuteScript("arguments[0].click()", Client.AppiumDriver.FindElement(By.XPath(locator)));

```

Most of the time randomly
Action breaks throwing error **"The URL '/wd/hub/session//moveto'"** did not map to a valid resource"

Javascript breaks throwing error **"The URL '/wd/hub/session//execute'"** did not map to a valid resource"

I tried putting waits, letting elements load completely but still I get above error

Has any one faced the similar problem??
## Link to Appium logs

> [HTTP] <-- GET /wd/hub/session/9aaf70d4-8384-4c54-8386-62e40a3edea7/element/5017/enabled 200 515 ms - 76 
>     [HTTP] --> POST /wd/hub/session/9aaf70d4-8384-4c54-8386-62e40a3edea7/element {"using":"id","value":"hp_takePhoto"}
>     [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","hp_takePhoto","9aaf70d4-8384-4c54-8386-62e40a3edea7"]
>     [debug] [iOS] Executing iOS command 'findElement'
>     [debug] [BaseDriver] Waiting up to 5000 ms for condition
>     [debug] [RemoteDebugger] Executing 'find_element' atom in default context
>     [debug] [RemoteDebugger] Sending javascript command (function(){return function...
>     [debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
>     [debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type"...
>     [debug] [RemoteDebugger] Found handler for message '42'
>     [debug] [RemoteDebugger] Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1474455901436"}
>     [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"5018"}
>     [HTTP] <-- POST /wd/hub/session/9aaf70d4-8384-4c54-8386-62e40a3edea7/element 200 514 ms - 90 
>     [HTTP] --> POST /wd/hub/session//moveto {"element":"5018","xoffset":10,"yoffset":10}
>     [debug] [HTTP] No route found. Setting content type to 'text/plain'
>     [HTTP] <-- POST /wd/hub/session//moveto 404 1 ms - 65

When the step gets successfully executed logs are like   

```
[HTTP] --> POST /wd/hub/session/c3924633-053a-450b-a3fb-2600c00655c5/element {"using":"id","value":"hp_takePhoto"}
    [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","hp_takePhoto","c3924633-053a-450b-a3fb-2600c00655c5"]
    [debug] [iOS] Executing iOS command 'findElement'
    [debug] [BaseDriver] Waiting up to 5000 ms for condition
    [debug] [RemoteDebugger] Executing 'find_element' atom in default context
    [debug] [RemoteDebugger] Sending javascript command (function(){return function...
    [debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...

    [debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type"...
    [debug] [RemoteDebugger] Found handler for message '30'
    [debug] [RemoteDebugger] Received result for atom 'find_element' execution: {"ELEMENT":":wdc:1474457829048"}

    [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"5012"}

    [HTTP] <-- POST /wd/hub/session/c3924633-053a-450b-a3fb-2600c00655c5/element 200 511 ms - 90 

    [HTTP] --> POST /wd/hub/session/c3924633-053a-450b-a3fb-2600c00655c5/execute {"script":"arguments[0].click()","args":[{"ELEMENT":"5012","element-6066-11e4-a52e-4f735466cecf":"5012"}]}

    [MJSONWP] Calling AppiumDriver.execute() with args: ["arguments[0].click()",[{"ELEMENT":"5012","element-6066-11e4-a52e-4f735466cecf":"5012"}],"c3924633-053a-450b-a3fb-2600c00655c5"]
    [debug] [iOS] Executing iOS command 'execute'
    [debug] [RemoteDebugger] Executing 'execute_script' atom in default context
    [debug] [RemoteDebugger] Sending javascript command (function(){return function...
    [debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...

    [debug] [RemoteDebugger] Receiving WebKit data: {"result":{"result":{"type"...

    [debug] [RemoteDebugger] Found handler for message '31'
    [debug] [RemoteDebugger] Received result for atom 'execute_script' execution: null

    [MJSONWP] Responding to client with driver.execute() result: null

    [HTTP] <-- POST /wd/hub/session/c3924633-053a-450b-a3fb-2600c00655c5/execute 200 513 ms - 76 
```

As looking into failed logs I can make out there is some issue with

> [HTTP] <-- POST /wd/hub/session/9aaf70d4-8384-4c54-8386-62e40a3edea7/element 200 514 ms - 90 
> [HTTP] --> POST /wd/hub/session//moveto {"element":"5018","xoffset":10,"yoffset":10}

instead of element , "9aaf70d4-8384-4c54-8386-62e40a3edea7" this should be used. Don't know why it takes the correct session sometimes and throws the error randomly....
## Code To Reproduce Issue [ Good To Have ]

Cannot share the application. Ionic2/angular2 app having list with above two structure will do the job in my view.

**Comment by imurchie** [comment]
Your client is sometimes not sending the session id. It might be more useful to ask it at the repository for whichever client it is.

**Comment by surajgupta7175** [comment]
@imurchie  Could you explain your comment a bit. I got confused how should I proceed further.. Thankyou

**Comment by imurchie** [comment]
My comment is that your client library, how you communicate with the Appium server, seems to send malformed requests periodically. See, for instance,

```
[HTTP] --> POST /wd/hub/session//moveto {"element":"5018","xoffset":10,"yoffset":10}
```

You can see that the session id, which should be before `moveto`, is missing.

I don't know what client you are using so I can't point you to their issue tracker to get some eyes on that.

**Comment by surajgupta7175** [comment]
AppiumDriver<IWebElement> driver = new IOSDriver<IWebElement>(new Uri(serverUri), capabilities, TimeSpan.FromSeconds(30)); //For IOS
AppiumDriver<IWebElement> driver = new AndroidDriver<IWebElement>(new Uri(serverUri), capabilities, TimeSpan.FromSeconds(30)); //For Android

Setting up capabilities as required

@imurchie  My codebase is in .net and using 
appium-dotnet-driver 1.5.1.1
Webdriver 2.53.1.0
System 4.0.0.0

**Comment by imurchie** [comment]
You should contact the appium-dotnet-driver folks (create an issue there). It is not a server problem.
