### ISSUE TITLE
[Appium Beta 1.6 - XCode 8 - iOS 10] XPath Locator Mechanism Changed?

### ISSUE THREAD

**Issue by raymondlapak** [appium/appium#6923]
## The problem

XPath locator using UI as prefix (e.g. UIButton, UITextField, etc) does not seem to be working after an upgrade to XCode 8 and Appium Beta 1.6. I am now using XCUITest as automationName. Element with prefix XC seems to be working though. Any idea on how to tackle this change? Any element inspector for XC-prefix elements available ? 

Thanks. Appreciate your hard work. 

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6
* Last Appium version that did not exhibit the issue (if applicable): Appium 1.5.3
* Desktop OS/version used to run Appium: Mac OSX
* Node.js version (unless using Appium.app|exe): Latest
* Mobile platform/version under test: iOS 10
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
Yes, the UI tree looks differently now. All elements have XCUIElementType prefix. Check out driver.getPageSource() method output for more details. You can try this Inspector https://github.com/mykola-mokhnach/Appium-iOS-Inspector to play with XPaths locators

**Comment by SrinivasanTarget** [comment]
@triager please close
