### ISSUE TITLE
Android M Grant permissions #6091

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#6928]
can we made some workaround here PLS? this is really stopping issue with any CI for android

[https://github.com/appium/appium/issues/6091](https://github.com/appium/appium/issues/6091)

i am also fine if we implement either:
- "appWaitPackage" to accept multiple values

or
- "waitForAppScript" to skip any "appWaitPackage" and "appWaitActivity" (this was working in Appium 1.5.3)

**Comment by imurchie** [comment]
This has been fixed in recent versions.
