### ISSUE TITLE
Not able to run safari launcher.app on mobile device

### ISSUE THREAD

**Issue by deepsinghkalsi** [appium/appium#6931]
## The problem

I'm new to appium, eclipse automation testing. I'm trying to run the demo application on mobile device. But everytime i run i'm getting this error.

/Applications/Appium.app/Contents/Resources/nodeorg.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Bad app: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name. (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 224 milliseconds_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name. (WARNING: The server did not provide any stacktrace information)
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Desktop OS/version used to run Appium: 10.10.5
- Node.js version (unless using Appium.app|exe): 6.7.0
- Mobile platform/version under test: IOS
- Real device or emulator/simulator: IOS version 8.0 to 9.3
- Appium CLI or Appium.app|exe:
## Code To Reproduce Issue

Using the below listed capabilities

capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");  
testStepMessage("Platform Name: iOS");  
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "9.2");  
testStepMessage("Platform Version: 9.3.1");  
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone");  
testStepMessage("Device Name: iPhone 6s");  
capabilities.setCapability(MobileCapabilityType.UDID, "Device UDID");

**Comment by automationtesting123** [comment]
@deepsinghkalsi I am also facing same kind of issue. Have you build safari launcher.app through xcode??

**Comment by deepsinghkalsi** [comment]
Yes automationtesting123, What version of appium are you using?

**Comment by automationtesting123** [comment]
appium 1.5.3 (Ara)

**Comment by deepsinghkalsi** [comment]
I got it solved with appium 1.4.13

**Comment by automationtesting123** [comment]
I am using iPod touch (9.3) real device. but 1.4.13 does not support the ios version 9.3.

**Comment by automationtesting123** [comment]
can you help me in solving this issue?

**Comment by deepsinghkalsi** [comment]
Yes appium 1.4.13 does instead of selecting from a dropdown, manually add 9.3 there. I added 9.2 and was able to run the iPhone 6

**Comment by deepsinghkalsi** [comment]
Any success @automationtesting123

**Comment by vikramvi** [comment]
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/mobile-web.md#mobile-safari-on-a-real-ios-device
