### ISSUE TITLE
org.openqa.selenium.UnsupportedCommandException error on appium scroll

### ISSUE THREAD

**Issue by LokeshGangaiah** [appium/appium#6932]
## The problem

I am trying to scroll to a particular element in the screen, getting the below error:
## Environment
- Appium version (or git revision) that exhibits the issue:1.4.16.1
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:Windows 8
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:Android 6.0.1
- Real device or emulator/simulator:Real device
- Appium CLI or Appium.app|exe:
## Details

I clikc on a link which takes me to a new page, and in the new page i need to scroll down to click on a particular element, this is what i need to achieve.
## Link to Appium logs

https://gist.github.com/LokeshGangaiah/016cb4ac0085bcbc1ecd0722a99c2904
## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/LokeshGangaiah/2b14a587b0d6dcb338618edd5c0d102a

**Comment by imurchie** [comment]
Do you have a particular need to be using Selendroid as a backend?

**Comment by LokeshGangaiah** [comment]
@imurchie Yes its an mobile App for Android to automate and the tool i am using is Appium

**Comment by imurchie** [comment]
But why are you using `automationName = 'Selendroid'`?

**Comment by mykola-mokhnach** [comment]
@LokeshGangaiah you can try this solution for Selendroid: https://github.com/appium/appium/issues/6585
