### ISSUE TITLE
Babel 5, minimatch and line-numbers are deprecated

### ISSUE THREAD

**Issue by srkannan** [appium/appium#6935]
## The problem

 npm install appium@1.6.0-beta3
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.

## Environment

* Appium version (or git revision) that exhibits the issue:appium@1.6.0-beta3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.11.16
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:iOS
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:

**Comment by imurchie** [comment]
Yes. Porting to Babel 6 would be nice but it necessitates a rewrite of how transpilation works. It would mean a relatively long period of _no_ work getting done on Appium's functionality.

The others are sub-dependencies. None of them matter.

**Comment by srkannan** [comment]
But you see I'm not able to install appium@1.6.0-beta3 because of this issue.

**Comment by imurchie** [comment]
Those warnings should not stop an install. Is there no other logging?

What version of node are you on? What version of npm?

**Comment by srkannan** [comment]
node -v : v6.7.0
npm -v : 3.10.7

I do get this error:
(node:21166) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by srkannan** [comment]
I just updated to npm -v 3.10.8 and then if I try to install I get:

npm install appium@1.6.0-beta3
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/Users/Kannan
└── appium@1.6.0-beta3 

npm WARN enoent ENOENT: no such file or directory, open '/Users/Kannan/package.json'
npm WARN Kannan No description
npm WARN Kannan No repository field.
npm WARN Kannan No README data
npm WARN Kannan No license field.

**Comment by imurchie** [comment]
There is no error there.

Can you go into `/Users/Kannan/node_modules/appium`

**Comment by srkannan** [comment]
Yes I'm able to go in to that folder
but appium -v
-bash: /usr/local/bin/appium: No such file or directory
and which appium does not return anything

**Comment by imurchie** [comment]
If you want it to be global, you need to install with the `-g` option: `npm install -g appium@beta`.

**Comment by srkannan** [comment]
ok that solves the problem thanks!
