### ISSUE TITLE
Unable to find element using "name" locator strategy in 1.6.0-beta3 version

### ISSUE THREAD

**Issue by anshulsachan** [appium/appium#6938]
After switching to 1.6.0-beta3  in order to support xcode 8, all the test cases are failing wherever i am using name as the locator strategy to identify elements.
up till now i was using appium 1.4.8 app to execute and all the test cases were working fine.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0-beta3  
* Last Appium version that did not exhibit the issue (if applicable): 1.4.8
* Desktop OS/version used to run Appium: 10.11.6
* Node.js version (unless using Appium.app|exe): v6.2.2
* Mobile platform/version under test: iOS 9.3.5
* Real device or emulator/simulator: Device

## Details

Appium is able to identify absolute path like //UIAApplication[1]/UIAWindow[1]/UIAButton[1] but is failing to identify path like "name=Sale"

##Appium logs
[HTTP] --> POST /wd/hub/session/56ed2eef-d821-4f35-84df-29d097e7050a/element {"using":"name","value":"Sale"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["name","Sale","56...
[debug] [iOS] Executing iOS command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, -ios uiautomation, accessibility id
[HTTP] <-- POST /wd/hub/session/56ed2eef-d821-4f35-84df-29d097e7050a/element 500 1 ms - 144

**Comment by jlipps** [comment]
Name was removed in 1.5. Use accessibility id instead.

**Comment by uzmasyed00** [comment]
hi jlipps

if we dont have accessibility_id, what else can we use?

**Comment by imurchie** [comment]
Have you _tried_ using accessibility id, even if you don't have any set?

**Comment by uzmasyed00** [comment]
I did, but it didnt do anything as there was nothing set.
Another question I have is for appium 1.6, how do I use the inspector to find values of element properties?

**Comment by shrikant007** [comment]
findElement(By.name("some text"));  this is working fine in my case

**Comment by asifurrouf** [comment]
@shrikant007 ,as you said appium 1.6.0 working fine in your  case,but Name was removed in 1.5,
would you please say what is your OS & Exact Appium Version after rechecking.

**Comment by sanjaychaudhari1821** [comment]
May I know the reason for elements not working on specific screen.For me ID, Name is not working only on 1 screen
