### ISSUE TITLE
add capability to enable calendar access for iOS apps

### ISSUE THREAD

**Issue by jlipps** [appium/appium#6939]
It would be nice to enable calendar access for apps the same way we do for location services. I propose we add a `calendarAuthorized` or `calendarAccessAuthorized` capability to mediate this. The way we can achieve the access if by modifying the `TCC.db` file in the simulator, as follows:

Prerequisites:
1. Knowledge of the iPhone shared resources directory
1. Knowledge of the app bundleId

Then we can execute a sqlite command:

```
sqlite3 \
"$IPHONE_RESOURCE_DIR/Library/TCC/TCC.db" \
"INSERT INTO 'access' VALUES('kTCCServiceCalendar', '$BUNDLE_ID', 0, 1, 1, 0, 0);"
```

cc @imurchie

**Comment by imurchie** [comment]
Looks like it should not be too hard to do.

**Comment by huminzhi** [comment]
Can we have it in 1.6.1? @imurchie

**Comment by jlipps** [comment]
@huminzhi I don't think so, we're trying to get out 1.6.1 as soon as possible with some urgent bugfixes. But we can prioritize it as an enhancement for sure.

**Comment by huminzhi** [comment]
@jlipps  any update for this?

**Comment by jlipps** [comment]
It is still prioritized, but we haven't gotten to it yet. Thanks to @dpgraham's work getting sqlite updates working for your other request, this should be pretty straightforward.

**Comment by huminzhi** [comment]
Thank you @jlipps ! We are waiting for this to unblock some of our tests.. Thanks to keep me updated!

**Comment by dpgraham** [comment]
Acceptance criteria:

* [ ] Add API to appium-ios-simulator that adds calendar access to TCC.db
* [ ] Update https://github.com/appium/ios-test-app to include a use case where authorization status for calendar access is displayed
* [ ] Update https://github.com/appium/appium-xcuitest-driver to include a new dcap for enabling calendar and a functional test that proves that it has authority to access calendar
