### ISSUE TITLE
Could Not Launch Appium Inspector

### ISSUE THREAD

**Issue by stellasu168** [appium/appium#6940]
## The problem

"Could Not Launch Appium Inspector: 
Could not get list of sessions from Appium Server

Be sure the Appium server is running with an application opened by using the "App Path" parameter in Appium.app"

I can't open the inspector. I was able to open it a few days ago. In the meantime, nothing changed in my environment. Also, instrument can open my .ipa file. 

## Environment

* Appium version: 1.53 (GUI)
* Desktop OS/version used to run Appium: OS X El Capitan
* Node.js version (unless using Appium.app|exe): v6.3.1
* Mobile platform/version under test: iOS 9.3.4
* Real device or emulator/simulator: real iOS device

## Details

I launched Appium, please see logs below. It doesn't have any error in the log. I clicked on the Inspector but getting the error message above. I was able to open it a few days ago. Also, instrument can open my .ipa file. I can run my automation test but can't open the inspector. Although there is something flaky in my test. The send key is sending infinite arguments to the username text filed. I will do a separate post for that. 

## Link to Appium logs

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --debug-log-spacing --platform-version "9.3.4" --platform-name "iOS" --app "/Users/sus01/Desktop/BOTW/BOTW_MOB_5.1_20160923_ForAutomationTestingOnly/BOTW-iPhone-5.1.0-D7.ipa" --udid "b2202fdabdc9077d7c2e3ded27202bdac545axxx" --show-ios-log --device-name "Stella iPhone6" --launch-timeout "90000"

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:
[Appium]   debugLogSpacing: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.3.4'
[Appium]   deviceName: 'Stella iPhone6'

[Appium]   app: '/Users/sus01/Desktop/BOTW/BOTW_MOB_5.1_20160923_ForAutomationTestingOnly/BOTW-iPhone-5.1.0-D7.ipa'
[Appium]   udid: 'b2202fdabdc9077d7c2e3ded27202bdac545axxx'
[Appium]   showIOSLog: true
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"9.3.4"}'
[Appium]   --device-name => --default-capabilities '{"deviceName":"Stella iPhone6"}'
[Appium]   --app => --default-capabilities '{"app":"/Users/sus01/Desktop/BOTW/BOTW_MOB_5.1_20160923_ForAutomationTestingOnly/BOTW-iPhone-5.1.0-D7.ipa"}'
[Appium]   -U,--udid => --default-capabilities '{"udid":"b2202fdabdc9077d7c2e3ded27202bdac545axxx"}'
[Appium]   --show-ios-log => --default-capabilities '{"showIOSLog":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.3.4'

[Appium]   deviceName: 'Stella iPhone6'
[Appium]   app: '/Users/sus01/Desktop/BOTW/BOTW_MOB_5.1_20160923_ForAutomationTestingOnly/BOTW-iPhone-5.1.0-D7.ipa'
[Appium]   udid: 'b2202fdabdc9077d7c2e3ded27202bdac545axxx'
[Appium]   showIOSLog: true

[Appium] Appium REST http interface listener started on 0.0.0.0:4723

<img width="1440" alt="screen shot 2016-10-04 at 5 10 04 pm" src="https://cloud.githubusercontent.com/assets/4042543/19096933/7c5d0e64-8a55-11e6-9a8c-2d86f2fc1aea.png">

**Comment by mykola-mokhnach** [comment]
You can try this inspector implementation as a workaround: https://github.com/mykola-mokhnach/Appium-iOS-Inspector

**Comment by hansjoergkeser** [comment]
another alternative:
https://macacajs.github.io/app-inspector/

here you don't have to set a breakpoint like in the tool mentioned above. It is more like the appium.app inspector. Unfortunately both tools do not offer any selector validation. Hope there is another cool tool that offers that functionality.

**Comment by stellasu168** [comment]
Thank you @hansjoergkeser! All I have access to is an .ipa file, can I still use this tool? I don't have access to the app's code.

**Comment by stellasu168** [comment]
Thank you for your comments friends. I think this might be a firewall issue. Once I logged out of my vpn, the inspector works. Quick note, it does work with vpn on a few days ago. Still kinda weird. But it's working now. Thanks again!!
