### ISSUE TITLE
Unable to run test against emulator

### ISSUE THREAD

**Issue by kiran-meda** [appium/appium#6942]
## The problem
 
I am running C# appium tests on emulator. Unable to create session as it is giving error Chrome version must be >= 46.0.2490.0\n  (Driver info: chromedriver=2.21.371459
## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 6.0
* Real device or emulator/simulator: Emulator Nexus 6
* Appium CLI or Appium.app|exe: Appium.exe

## Details

I am new to appium, I am unable to run tests on appium emulator. I have created a AVD named "Sample" for Nexus 6.0,  Android Version 6.0. I am getting while running the test.

I checked device name using adb devices -l, it is giving following emulator information

emulator-5554          device product:sdk_phone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64

## Link to Appium logs

https://gist.github.com/kiran-meda/a7dcdae886913270dbb2b26240f40208

## Code To Reproduce Issue [ Good To Have ]
```
using OpenQA.Selenium;
using OpenQA.Selenium.Appium.Android;
using OpenQA.Selenium.Appium.Enums;
using OpenQA.Selenium.Remote;
using System;
 namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
 AndroidDriver<AndroidElement> driver = null;
            DesiredCapabilities capabilities = DesiredCapabilities.Android();
            capabilities.SetCapability(MobileCapabilityType.BrowserName, "Browser");
            capabilities.SetCapability(MobileCapabilityType.DeviceName, "generic_x86_64");
            capabilities.SetCapability(MobileCapabilityType.PlatformVersion, "6.0.1");
            capabilities.SetCapability(AndroidMobileCapabilityType.AppPackage, "com.android.browser");
            capabilities.SetCapability(AndroidMobileCapabilityType.AppActivity, "com.android.browser.BrowserActivity");
            
            capabilities.SetCapability("udid", "emulator-5554");
                driver = new AndroidDriver<AndroidElement>(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities, TimeSpan.FromSeconds(180));
                driver.Navigate().GoToUrl("https://google.com");
        }
    }
```

Kindly let me know if I miss any capabilities or any further information required.

**Comment by imurchie** [comment]
What version of the browser are you running on the device?

**Comment by kiran-meda** [comment]
Browser version: 6.0-2780065(#23)
Process: com.android.browser
Source: /system/app/Browser/Browser.apk

**Comment by imurchie** [comment]
ChromeDriver is not able to automate the version of the browser you are using. I'm not sure what the minimum is, since it only reports for Chrome.

You can install a previous version of ChromeDriver, and then pass in the path with the `--chromedriver-executable` server flag when starting the appium server.

http://chromedriver.storage.googleapis.com/index.html

**Comment by SrinivasanTarget** [comment]
@triager please close
