### ISSUE TITLE
[v1.6.0-beta3] 'Activity used to start app doesn't exist or cannot be launched!' when trying to run Android tests

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#6943]
## The problem

I'm unable to run Android tests since I can't even launch the app: `An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity (Selenium::WebDriver::Error::UnknownError)`

I think this is a similar issue that I experienced with 1.5-beta8 version in the past: https://github.com/appium/appium/issues/5936

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0-beta3
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16/1.5.3
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe): v5.1.1
* Mobile platform/version under test: Android 5.0.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

```
@launch @reset
Feature: launch to default login or registration

  Background:                   # features/launch.feature:4
  An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity (Selenium::WebDriver::Error::UnknownError)
  ./features/support/hooks.rb:10:in `Before'
    Given I am on launch screen # features/step_definitions/common_steps.rb:1

  @sanity @analytics
  Scenario: already registered and have a card            # features/launch.feature:8
    When I have a card                                    # features/step_definitions/launch_steps.rb:1
    Then I should be taken to the login screen            # features/step_definitions/launch_steps.rb:9
      undefined method `save_screenshot' for nil:NilClass (NoMethodError)
      ./features/support/utils/screenshot_utils.rb:16:in `capture'
      ./features/support/hooks.rb:19:in `After'

Failing Scenarios:
cucumber -p android -p launch -p default_flags -p default_tags -p skip_ios features/launch.feature:8 # Scenario: already registered and have a card

1 scenario (1 failed)
7 steps (7 skipped)
0m15.763s
Exited with status: 1
Janis-MacBook-Air:bdd janijegoroff$
```

## Link to Appium logs

https://gist.github.com/JaniJegoroff/690765390a02707e54d6b0406bca8aa0

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
This doesn't look like the same issue at all.

Can you check if the app is getting installed? We changed the install command and it might have messed things up.

**Comment by JaniJegoroff** [comment]
I see, app is not getting installed.

**Comment by imurchie** [comment]
Ok. I'm in the process of reverting the change. I'll let you know when the change is published.

**Comment by imurchie** [comment]
Can you try with `appium-adb@2.6.16`?

**Comment by JaniJegoroff** [comment]
I quickly try it out and app is now installed to the device. However, I see some other errors:
```
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: -P, 5037, -s, HT35DW918545, shell, uiautomator, runtest, AppiumBootstrap.jar, -c, io.appium.android.bootstrap.Bootstrap, -e, pkg, com.ga.loyalty.android.nectar.activities.local, -e, disableAndroidWatchers, false, -e, acceptSslCerts, false
[Logcat] Logcat terminated with code 0, signal null
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[debug] [UiAutomator] Moving to state 'stopped'
```
I will have a closer look after I get back to home.

**Comment by imurchie** [comment]
Alright. Create a new issue if it persists.

**Comment by JaniJegoroff** [comment]
Thanks @imurchie, this is working great now.

**Comment by shaynl** [comment]
Hi, I'm having the same issue. when trying to run appium -adb@2.6.16 i'm getting this error:

> [Appium] Welcome to Appium v1.6.0-beta3
[Appium] Non-default server args:
[Appium]   address: 'db@2.6.16'
[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
Error: getaddrinfo ENOTFOUND db@2.6.16
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

**Comment by imurchie** [comment]
What are you trying to do when running ` appium -adb@2.6.16`? That is not a thing.

To get the latest code, reinstall the beta (`npm uninstall -g appium@beta && npm install -g appium@beta`).
