### ISSUE TITLE
XCode 8 - findElementsByXpath() returns some bad objects

### ISSUE THREAD

**Issue by appiumnovice** [appium/appium#6945]
## The problem

Hi,
I'm trying to retrieve values from items with findElementsByXpath() and I obtain correct and bad values.

The tree of items retrieved with getPageSource seems correct (see attachment).

This script worked with Appium 1.5.3, Xcode 7, iOS 9.3
## Environment
- Appium version 1.6.0-beta1
- MacOS El Capitan 10.11.6
- Node.js version : 0.12
- Mobile platform/version under test: iOS 9.3
- Real device or emulator/simulator: simulator
- Appium CLI or Appium.app|exe: CLI
- Client : Java
## Link to Appium logs

https://gist.github.com/appiumnovice/b067a93e4471f2c84013d8b6845868c4
## Link to tree of items

https://gist.github.com/appiumnovice/a664c4e63d266d5aaef47482908f94dd
## Code To Reproduce Issue

// Get items with property name = trainNameLabel
String xpath = "//XCUIElementTypeStaticText[@name=\"**trainNameLabel**\"]";
List<WebElement> items = driver.findElementsByXPath(xpath);
System.out.println("Nb items : " + items.size());

// Displays names (property "value" of each trainNameLabel item)
String transportType;
for(WebElement item : items) {
    transportType = item.getAttribute("value");
    System.out.println("transport type : + transportType);
}

**Comment by mykola-mokhnach** [comment]
You XPath expression looks a bit suspicious. What if you change it to
```
"(//XCUIElementTypeTable[starts-with(@name,\"Départs trains et cars SNCF\")])[1]//XCUIElementTypeStaticText[@name=\"trainNameLabel\"]"
```

?

**Comment by appiumnovice** [comment]
Hi, thanks for your help.
I simplified the xpath.

**Comment by appiumnovice** [comment]
I simplified the xpath to get items.

Nb items : 20
transport type : TER N°843508
transport type : CAR 46415
transport type : TER N°844817
transport type : TER N°841813
transport type : TER N°842415
transport type : Amiens
transport type : TER N°844107
transport type : 12 Heure 05 Minute 
transport type : TER N°843812
transport type : TER N°19927
transport type : TER N°841243
transport type : TER N°842417
transport type : TER N°844911
transport type : TER N°843210
transport type : TER N°844819
transport type : TER N°842219
transport type : Tourcoing
transport type : TER N°842419
transport type : TER N°841817
transport type : TER N°844821

3 values are not corrects:  Amiens, 12 Heure 05 Minute, Tourcoing 

Logs seems poor : 
https://gist.github.com/appiumnovice/b067a93e4471f2c84013d8b6845868c4

And it takes 120 seconds to have a response.

**Comment by dpgraham** [comment]
This may be an issue with WebDriverAgent

**Comment by mykola-mokhnach** [comment]
Please try the most recent Appium release 1.6.5
If it still does not work then please report an issue directly to https://github.com/facebook/WebDriverAgent/issues
