### ISSUE TITLE
[Feature Request] - Make autoAcceptAlerts a run-time configurable setting

### ISSUE THREAD

**Issue by ansumd** [appium/appium#6946]
## The problem

Would like to request "autoAcceptAlerts" desired capability to be a run-time configurable setting. Currently in our app there are some alerts that pop up that we want to ignore and there are some alerts we want to actually handle the inputting text, selecting buttons etc.

Currently autoAcceptAlerts is not a run-time configurable setting according to docs:
https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/settings.md

Tried disabling autoAcceptAlerts by issuing following but it did not work:
self.driver.update_settings({"autoAcceptAlerts": "false"})
## Environment
- Appium version 1.4.13:
- Mac OSX El Capitan 10.11.6
- NPM version 2.15.1
- iphone 5S iOS 8.0.2

**Comment by imurchie** [comment]
Going forward there is no way to implement auto accept alerts. Closing.
