### ISSUE TITLE
iOS/Appium 1.6 beta3 - sendKeys()/setValue() methods clicks or taps on random elements in the page but does not enter text in the EditTextField element.

### ISSUE THREAD

**Issue by mmuntakim15** [appium/appium#6948]
## The problem

When calling either sendKey() or setValue() methods to enter text into editTextField, appium just randomly click on any button it finds on that page. 
## Environment
- Appium version (or git revision) that exhibits the issue: v1.6.0-beta3
- Last Appium version that did not exhibit the issue (if applicable): v1.6.0-beta2
- Desktop OS/version used to run Appium: Mac version 10.11.6
- Node.js version (unless using Appium.app|exe): v4.4.3
- Mobile platform/version under test: Xcode 8.0 / iOS 10.0
- Real device or emulator/simulator: Simulator
- Appium CLI or Appium.app|exe: Appium CLI
## Link to Appium logs

https://gist.github.com/mmuntakim15/14019d4afc958b80df68893c821d5e6d

**Comment by imurchie** [comment]
I have a feeling this is related to a bug in the WebDriverAgent. Can you try the following:

```
// somewhere temporary
git clone https://github.com/imurchie/WebDriverAgent.git
```

And then add the capabilities `agentPath` and `bootstrapPath`. `bootstrapPath` should have as its value the directory that is created by the above `git clone` (e.g., `/Users/isaac/temp/WebDriverAgent`) and `agentPath` should have the same, but with `/WebDriverAgent.xcodeproj` appended (e.g., `/Users/isaac/temp/WebDriverAgent/WebDriverAgent.xcodeproj`).

Then run your test and see what happens.

Thanks!

**Comment by mmuntakim15** [comment]
Thanks @imurchie but it didn't work, here is the appium logs https://gist.github.com/mmuntakim15/46194ef9bc9cbb49ba0720a9a6ea26e6

And this is the capabilities value link as per your instruction:
https://gist.github.com/mmuntakim15/2757b0269d062d6d261ebb89848b7752

Thanks

**Comment by srkannan** [comment]
When using agentPath and bootstrapPath I get:
The following capabilities were provided, but are not recognized by appium: agentPath, bootstrapPath

**Comment by imurchie** [comment]
@srkannan That should not matter. Things will continue on.

**Comment by mmuntakim15** [comment]
@imurchie thanks it worked now, that was dumb error from my side.

**Comment by imurchie** [comment]
Hmm. Ok. I will add this to the report on the upstream project.
