### ISSUE TITLE
iOS webkit Proxy Support for iOS 10.11

### ISSUE THREAD

**Issue by anshu1987** [appium/appium#6949]
## The problem

I just upgraded my mac machine OS to 10.11.6 and iOS webkit debug proxy command stop working.
Error I am getting is : Could not connect to lockdownd. Exiting.: Permission denied.

I tried brew install ios-webkit-debug-proxy as well, but got message as: 
Warning: ios-webkit-debug-proxy-1.5 already installed
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.

So the Question should I downgrade OS version or there is some workaround.

**Comment by pavanbachu0604** [comment]
Temporary fix is : sudo chmod -R 777 /var/db/lockdown 

Permanent fix would to reinstall the ios webkit from master. 

1. For that you need to uninstall the existing webkit
2. Use this command : brew install --HEAD ios-webkit-debug-proxy

**Comment by SrinivasanTarget** [comment]
@triager please close
