### ISSUE TITLE
[1.6.0-beta3] 'noReset: true' capability not handled correctly on Android?

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#6950]
## The problem

I run two scenarios with `noReset = true` capability. First scenario will start from scratch:
```
uninstall app > install app > go to launch screen > go to login screen > go to main screen
```
Second scenario should restart the app and go straight to the main screen. App is restarted and main screen opened but I see an error: `An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: com.ga.foo.android.app.activities.local/com.ga.foo.android.app.activity.FirstLaunchActivity or .com.ga.foo.android.app.activity.FirstLaunchActivity never started (Selenium::WebDriver::Error::UnknownError)`

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0-beta3
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16, 1.5.3
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe): v5.1.1
* Mobile platform/version under test: Android 5.0.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

```
@offers
Feature: offers

  @sanity
  Scenario: show offers              # features/offers.feature:5
    Given I am on offers screen      # features/step_definitions/common_steps.rb:1
    Then I should see list of offers # features/step_definitions/offers_steps.rb:27

  Scenario: show offers with content                 # features/offers.feature:9
  An unknown server-side error occurred while processing the command. Original error: Error occured while starting App. Original error: com.ga.foo.android.app.activities.local/com.ga.foo.android.app.activity.FirstLaunchActivity or .com.ga.foo.android.app.activity.FirstLaunchActivity never started (Selenium::WebDriver::Error::UnknownError)
  ./features/support/hooks.rb:10:in `Before'
    Given server returns offers with lifestyle image # features/step_definitions/offers_steps.rb:6
    And I am on offers screen                        # features/step_definitions/common_steps.rb:1
    Then I should see offer data                     # features/step_definitions/offers_steps.rb:31
      A session is either terminated or not started (Selenium::WebDriver::Error::NoSuchDriverError)
      ./features/support/utils/screenshot_utils.rb:16:in `capture'
      ./features/support/hooks.rb:19:in `After'

Failing Scenarios:
cucumber -p android -p offers -p default_flags -p default_tags -p skip_ios features/offers.feature:9 # Scenario: show offers with content

2 scenarios (1 failed, 1 passed)
5 steps (3 skipped, 2 passed)
1m40.261s
Exited with status: 1
```

## Link to Appium logs

https://gist.github.com/JaniJegoroff/b0735a7ace0c8cc0aee6a0776ed58696

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Can you try updating to the most recent `appium-xcuitest-driver`? I have added the (until then missing) reset logic from the ios driver.

**Comment by JaniJegoroff** [comment]
Still the same issue. Appium is expecting to find launch screen (activity.FirstLaunchActivity) even though after restart without reset it should be interested of main screen (activity.LandingActivity).

**Comment by imurchie** [comment]
Sorry, I've been heads down on iOS so much that I missed the Android part of this.

Did this work previously? Literally nothing has changed in that part of the Android system.

**Comment by JaniJegoroff** [comment]
I can only say this is working with 1.4.16 because I'm using it daily basis. This is first time trying out 1.6.0-beta3 release on Android. Which version I should try out, 1.5.3 maybe?

**Comment by JaniJegoroff** [comment]
Actually after reading 1.5.3 release notes:
> It also adds functionality to support for iOS WKWebViews and for automating the iOS Calendar app, as well as adding a capability to use abd for screenshots in Android web/hybrid sessions, selecting the correct version of Android emulator, and **providing a list of Android activities to wait for on session startup**.

Sounds like I need to provide list of activities for Appium? Going to try that...

**Comment by JaniJegoroff** [comment]
Okay, got it fixed by providing list of activities in `appWaitActivity` capability. In my case activity name has to be full name otherwise it didn't work.

`[Appium]   appWaitActivity: 'com.ga.foo.android.app.activity.FirstLaunchActivity, com.ga.foo.android.app.activity.LandingActivity'`
