### ISSUE TITLE
Not able find the elements in Native App (Similar issue #4621)

### ISSUE THREAD

**Issue by ravikirankandula** [appium/appium#6951]
## The problem

Hi,

Anyone help me to find the elements from android.webkit.webview package to the java appium script

How to click on the links in 1st page and how get the userText field and password field elements and need to pass some input and after that how to identify the elements for Sign-in button

when i Try to place, UI Automator cursor on respected UI, it's not taking

Thanks,
Ravi
## Environment

1) Appium Version 1.4.16
2) windows machine
3) Google Nexus 5 device->Version(5.1.0) -> API level 22 Reolution: 1080X1920
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by ravikirankandula** [comment]
![samplepage](https://cloud.githubusercontent.com/assets/18656713/19146982/9892f0e2-8bd3-11e6-909f-ea8845f87181.png)

**Comment by ravikirankandula** [comment]
![samplepage1](https://cloud.githubusercontent.com/assets/18656713/19147348/591160fa-8bd5-11e6-9ccb-757b1b515e7f.png)

**Comment by dpgraham** [comment]
Inspector and Appium-Desktop both don't get the contents of WebViews.
