### ISSUE TITLE
Hard driver usage in iOS tests

### ISSUE THREAD

**Issue by keshavjoshi49** [appium/appium#6952]
## The problem

If I am running around 50 IOS (real device) based test cases using mac 10.10, Appium 1.5.3 and Java as coding language. Mac system starts displaying Low swap memory.

I have tried both GUI  mode of appium and running appium through command line.
## Environment
- Appium version - 1.5.3
- Desktop OS/version used to run Appium: MAC OS 10.10
- Mobile platform/version under test: 9.3.2
- Real device or emulator/simulator: Real Device
- Appium CLI or Appium.app|exe: Tried with both
## Details

I have tried to run appium using both command line and GUI mode. After lots of R&D, I found that in processes, size of instruments keeps on increasing from MBs to GBs and slowing down my system.

Is this a memory leak in Appium? is there any workaround for this?

**Comment by JaniJegoroff** [comment]
Check Apple instruments folder size because it will consume massive amount of disk space:
`du -sh /Library/Caches/com.apple.dt.instruments`

My Mac was running out of disk space until I cleaned up that folder. We also clean up that folder in our CI machine once a week automatically.

**Comment by keshavjoshi49** [comment]
@JaniJegoroff - yes , i had also cleared this cache, but every we execute the test cases(50-80). machine gets stuck in between and size of these caches grow to a huge amount. so do i need to clear it while my tests are running?
what can we do to stop my machine from getting stuck while my tests are running.

**Comment by JaniJegoroff** [comment]
I have around 50 scenarios and cleaning the cache once in a while is enough for me. But I'm still using Appium server 1.4.16.

**Comment by JaniJegoroff** [comment]
I have been testing my projects with `1.6.0-beta` versions recently and haven't see any memory issues (not in my iMac nor MacBook Air).

**Comment by tapisky** [comment]
I have experienced the same issue with Appium 1.5.3. When running a test with a lot of scenarios, the execution slows down and eventually my mac freezes as well. I even see a system message saying that I'm running low in hard disk space. It only happens when running this particular test, not with other (shorter ones).

By the way, the exact same test on Android does not lead to this issue, only the iOS test.

**Comment by keshavjoshi49** [comment]
@JaniJegoroff - As i have not worked with 1.6.0-beta so can't say much about it. but with @tapisky comment and my research we are sure this is related to IOS/instruments which results in failed execution of test cases and low hard disk/swap space.

**Comment by NareshSamala** [comment]
Hi, 

Am facing the same issue with appium 1.6.3 with xcode 8.2 ios 10.1.1 real device, mac 10.6 above

On every launch of driver instance my storage space is reduced to around 300mb... clearly observed in more then 3 systems sqme issue

**Comment by imurchie** [comment]
Update to 1.6.4 and use the `clearSystemFiles` capability (set to `true`).
