### ISSUE TITLE
How to run Xctest on ios 10 apps from appium

### ISSUE THREAD

**Issue by pixyish** [appium/appium#6953]
## The problem
we are not able to automate ios 10 using appium.
we were using instrument before so please is there any support of appium for xctest.

**Comment by imurchie** [comment]
Search through these issues, or look in the docs. 

https://github.com/appium/appium/blob/master/docs/en/appium-setup/running-on-osx.md#testing-using-xcode-8-including-ios-10-with-xcuitest
