### ISSUE TITLE
Cannot install appium1.6.0-beta if authoize-ios and appium-doctor are already installed

### ISSUE THREAD

**Issue by flashquartermaster** [appium/appium#6954]
## The problem

I have to uninstall authorize-ios and appium-doctor if I want to install appium1.6.0-beta's locally to my project and then reinstall them afterwards.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0-beta3
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: macOS Sierra
* Node.js version (unless using Appium.app|exe): 4.4.5
* Mobile platform/version under test: Any
* Real device or emulator/simulator: Any
* Appium CLI or Appium.app|exe: CLI

## npm debug

```
12080 error Darwin 16.0.0
12081 error argv "/Users/tom/.nvm/versions/node/v4.4.5/bin/node" "/Users/tom/.nvm/versions/node/v4.4.5/bin/npm" "install" "appium@1.6.0-beta3"
12082 error node v4.4.5
12083 error npm  v3.10.5
12084 error path /Users/tom/pathToApp/node_modules/appium/node_modules/.bin/authorize-ios
12085 error code ENOENT
12086 error errno -2
12087 error syscall chmod
12088 error enoent ENOENT: no such file or directory, chmod '/Users/tom/pathToApp/node_modules/appium/node_modules/.bin/authorize-ios'
12089 error enoent ENOENT: no such file or directory, chmod '/Users/tom/pathToApp/node_modules/appium/node_modules/.bin/authorize-ios'
12089 error enoent This is most likely not a problem with npm itself
12089 error enoent and is related to npm not being able to find a file.
12090 verbose exit [ -2, true ]
```

## Code To Reproduce Issue [ Good To Have ]

`npm install autorize-ios appium-doctor`
`npm install appium@1.6.0-beta3`

**Comment by imurchie** [comment]
We have just released 1.6.0, and this issue is fixed. Thanks for reporting!

**Comment by flashquartermaster** [comment]
Hi, can't seem to get 1.6.0 it is not a valid version with npm. @latest is 1.5.3. Do I have to build it from source?

**Comment by imurchie** [comment]
Yeah, I'm seeing that. I am looking into what went wrong.
