### ISSUE TITLE
Conflict between ionic serve and appium

### ISSUE THREAD

**Issue by flashquartermaster** [appium/appium#6956]
**I am not 100% sure this is a bug but it is a pain when developing and running tests if you forget that it happens.**
## The problem

Selenium Webdriver fails at createSession  if `ionic serve` is running. I think because of a clash on localhost:8100.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0-beta3
- Last Appium version that did not exhibit the issue (if applicable): N/a
- Desktop OS/version used to run Appium: macOS Sierrra
- Node.js version (unless using Appium.app|exe): 4.4.5
- Mobile platform/version under test: iOS (Have not checked Android)
- Real device or emulator/simulator: Simulaor
- Appium CLI or Appium.app|exe: CLI
## Link to Appium logs

[https://gist.github.com/flashquartermaster/5f89cee5ec38e07c605b060c12bd1c0b](https://gist.github.com/flashquartermaster/5f89cee5ec38e07c605b060c12bd1c0b)
## Link to Protractor output

[https://gist.github.com/flashquartermaster/da8ca0bcf2d871ac96e5c2685856cc3f](https://gist.github.com/flashquartermaster/da8ca0bcf2d871ac96e5c2685856cc3f)

Ionic:
`√ Running dev server: http://localhost:8100`

Appium:
`[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session]`
## Code To Reproduce Issue

Outlined here at the original issue: [https://github.com/angular/protractor/issues/3616](https://github.com/angular/protractor/issues/3616)

`ionic serve`
`node_modules/.bin/appium`
`node_modules/.bin/protractor tests/ios-conf.js`

**Comment by mykola-mokhnach** [comment]
WebDriver itself uses USE_PORT environment variable to change the default port number. Not sure whether Appium supports this setting

**Comment by mykola-mokhnach** [comment]
Looks like Appium already has separate setting for it: _wdaLocalPort_

https://github.com/appium/appium-xcuitest-driver#usage

**Comment by flashquartermaster** [comment]
Thanks for such a quick reply. It seems as though _wdaLocalPort_ is only for a real ios device over USB, it did not help me with the simulator.

**Comment by flashquartermaster** [comment]
Sorry, I completely missed the first comment. Unfortunately, USE_PORT does not work either.

**Comment by rkavalap** [comment]
@flashquartermaster  
have you used --webdriveragent-port server side argument for appium other than wdaLocalPort ?
Can you try changing the default value from this file, try gulp transpile and post your findings if that works for you ?
https://github.com/appium/appium/blob/master/lib/parser.js

**Comment by imurchie** [comment]
There should be no need to change any code for changing the port. Just use the `--webdriveragent-port` server argument, or the `wdaLocalPort` desired capability.
