### ISSUE TITLE
Unable to start a WebDriver session

### ISSUE THREAD

**Issue by flashquartermaster** [appium/appium#6957]
## The problem

The session is being created and then deleted almost immediately.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.0 & 1.6.0-beta3
- Last Appium version that did not exhibit the issue (if applicable): 1.5.0
- Desktop OS/version used to run Appium: MacOS Sierra 10.12
- Node.js version (unless using Appium.app|exe): 4.4.5
- Mobile platform/version under test: Android
- Real device or emulator/simulator: Emulator (AVD and Genymotion)
- Appium CLI or Appium.app|exe: CLI
## Details

I have been using this setup for a while now and suddenly it is failing. I have re-built the projects from scratch and re-installed all the node modules ensuring that the same versions are being used. The only difference is that I am on MacOS Sierra now and was on El Capitan when it last worked. The only major difference I have noticed is that I have to specify the platform as 'MAC' in the capabilities or appium reports the platform to be 'LINUX'.

`[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webSto...`
## Link to Appium logs

[https://gist.github.com/flashquartermaster/82d7937dbda2372e3ef466727808d303](https://gist.github.com/flashquartermaster/82d7937dbda2372e3ef466727808d303)
## Link to Protractor output

[https://gist.github.com/flashquartermaster/bbd43dc3aa4851a5e966d692385ea326](https://gist.github.com/flashquartermaster/bbd43dc3aa4851a5e966d692385ea326)
## Code To Reproduce Issue

The sample code I am running can be found at [https://github.com/flashquartermaster/myappname](https://github.com/flashquartermaster/myappname)

You should only need to `npm install` and update the android-conf.js with a deviceName.

**Comment by imurchie** [comment]
The LINUX platform refers to the Android platform.

The client here is sending a DELETE command to end the session. The server is doing all that is should.

**Comment by flashquartermaster** [comment]
Thanks @imurchie, I misunderstood the the way platform was working there.

So, can help me to figure out where I go from here, I've spent a long time debugging to try to find out why this has stopped working and got nowhere. Could this be an issue with any of the other modules I am using?

**Comment by JaniJegoroff** [comment]
Have you tried to update Android SDK Manager packages from Preview channel? I had some random `adb` issues after moving to Mac OS Sierra but got rid off those by doing so. Everything is now working fine with 1.6.0-beta3.

**Comment by flashquartermaster** [comment]
Thanks for the advice @JaniJegoroff I have given it a go but the problem persists
