### ISSUE TITLE
SendKeys on iOS DatePicker -> Unable to find current value 'null' (Xcode 8)

### ISSUE THREAD

**Issue by appiumnovice** [appium/appium#6962]
## The problem

The script performs a sendKeys on an iOS Data Picker Wheel.
Date is not modified with Appium 1.6.0-beta1
It was modified with the previous version of Appium (1.5.3).
## Environment
- Appium version: 1.6.0-beta1
- Last Appium version that did not exhibit the issue : 1.5.3
- Desktop OS/version: MacOSX 10.11.6
- Node.js version : 
- Mobile platform/version under test: iPhone 6s Plus / iOS 9.3 (XCode 8)
- Real device or emulator/simulator: Simulator
- Appium : CLI
## Link to Appium logs

https://gist.github.com/appiumnovice/c0e27eaba5713debf5521c029bcd053f
## Link to tree of items is needed

https://gist.github.com/appiumnovice/79e760f3af3b6a7cf7d83ee2a5c9152b
## Code To Reproduce Issue [ Good To Have ]

WebElement dateWheel = findElementByXpath("//XCUIElementTypePickerWheel[1]");
dateWheel.sendKeys("ven., 14 oct.");

I tried too this solution without success:
dateWheel.sendKeys("14 oct.");

**Comment by imurchie** [comment]
What version of `appium-xcuitest-driver` are you using? It should be printed near the beginning of the session (and is part of the reason we want the _entire_ log, not just what appears to be pertinent)

```
[debug] [XCUITest] XCUITestDriver version: 2.0.24
```

**Comment by appiumnovice** [comment]
OK. I have the same version:
[debug] [XCUITest] XCUITestDriver version: 2.0.24

Here is the full run till the problem of value setting on DatePicker:
https://gist.github.com/appiumnovice/3685f5fb0e3ac38748fc88a9c5373ac4

**Comment by rakeshmick** [comment]
Any  update on this , issue?. I am also facing the same problem. send keys is not working for XCUIElementTypePickerWheel.

Getting error like:

8-447A-99D1-AC1C7B8ADB3A/attribute/type] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypePickerWheel\",\n  \"sessionId\" : \"7A3073EE-04FB-450A-B1EE-1AB45753DC00\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Proxying [POST /element/AFC4C815-C1B8-447A-99D1-AC1C7B8ADB3A/value] to [POST http://localhost:8100/session/7A3073EE-04FB-450A-B1EE-1AB45753DC00/element/AFC4C815-C1B8-447A-99D1-AC1C7B8ADB3A/value] with body: {"value":["T","5"]}
[debug] [WebDriverAgent] Sim: Nov 11 13:26:55 C02P61Q6G3QT XCTRunner[56580]: Enqueue Failure: UI Testing Failure - Internal error: unable to find current value 'BADev (Dev 0), 3 of 11' in possible values Mock, Local, BADev (Dev 0), Dev 1, T0, T2, T3, T4, T5, Staging, Prod for the picker wheel "BADev (Dev 0), 3 of 11" PickerWheel /Users/nitink/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
[debug] [WebDriverAgent] Sim: Nov 11 13:26:56 C02P61Q6G3QT XCTRunner[56580]: Enqueue Failure: UI Testing Failure - Failed to receive event delivery confirmation within 0.0s of the original dispatch. /Users/nitink/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
[JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"7A3073EE-04FB-450A-B1EE-1AB45753DC00","status":0}
[MJSONWP] Responding to client with driver.setValue() result: null
[HTTP]

**Comment by mykola-mokhnach** [comment]
Use _setValue_ method instead of _sendKeys_ to change picker value.

**Comment by rakeshmick** [comment]
Both gives the same response.No difference.

**Comment by mykola-mokhnach** [comment]
try with Appium 1.6.1beta or 1.6.0 stable

**Comment by mykola-mokhnach** [comment]
Also, the log shows that you are trying to set the wheel to non-existing value. Try to set one of the available values it shows in the output:  

```
Mock, Local, BADev (Dev 0), Dev 1, T0, T2, T3, T4, T5, Staging, Prod
```

**Comment by rakeshmick** [comment]
That is not correct. This is how I am setting it, I am using the xpath to identify the element and using the correct label in the send keys. I also tried sendKeys instead of set value.

IOSElement picker= (IOSElement) new WebDriverWait(wd,60).until(ExpectedConditions.elementToBeClickable(By.xpath("//XCUIElementTypePickerWheel"))); 
        picker.setValue("T5");

**Comment by mykola-mokhnach** [comment]
Seems like it's some known issue with XCTest framework and it has nothing to do with Appium itself
Check these threads for more details:
https://forums.developer.apple.com/thread/16104
https://github.com/skywinder/ActionSheetPicker-3.0/issues/255
http://www.openradar.me/22918650

Probably, you need to check the way you declare you PW in the code to workaround the problem.

**Comment by pisarenco92** [comment]
@rakeshmick Did you solve the problem?

**Comment by rakeshmick** [comment]
I had to get my developer change the Wheel picker implementation to identify the element.
As mykola mentioned above, there is a known issue with xcode which is still open. The fix did help me identify the element but it is has bring up a problem in controlling the font size of the options in the picker. Hope the issue gets fixed soon in xcode.

**Comment by rakeshmick** [comment]
For information on what change needs to be done to change the implementation of the picker, please see the links mykola posted,it speaks about a few work around,I tired the same and it helped. 
This is from the first post :
 workaround for me is use
 
func pickerView(pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {  
}  
instead of
func pickerView(pickerView: UIPickerView, viewForRow row: Int, forComponent component: Int, reusingView view: UIView?) {  
}

**Comment by pisarenco92** [comment]
@rakeshmick Thanks. I will try that solution

**Comment by Siddh010** [comment]
Could anyone please let us know when can be picker issue be fixed.
Thank you in advance.

**Comment by mykola-mokhnach** [comment]
Closing as non  Appium-related issue

**Comment by lvconley** [comment]
Hi All, I'm using Appium Desktop for iOS version 1.0.2-beta 2 against an iOS mobile app built with Xcode 8.3.3 and am unable to interact with pickerWheels in the app. Based on what I've read and after reviewing my code in depth, I believe this issue has to do with the way the pickerWheel views have been built. But I'm unable to get much help from the iOS devs where I work, so I'm going to post the relevant pickerWheel source code here in the hope that someone can tell me whether they any issues with it or not. For you iOS mobile devs reading this, any feedback you can offer on the code below and whether it will hinder automation or not would be GREATLY appreciated!

`#pragma mark - UIPickerViewDelegate

- (NSString *)pickerView:(UIPickerView *)pickerView
             titleForRow:(NSInteger)row forComponent:(NSInteger)component
{
    id options = [self itemAtIndexPath:self.focusedIndexPath][WDPRCellOptions];
    
    if ([options isKindOfClass:NSDictionary.class])
    {
        NSAssert(WDPRDatePickerModeMonthYear ==
                 [options[WDPRDatePickerMode] intValue], @"");
        
        if (component == 0) // months
        {
            row++;
        }
        else if (component == 1) // year
        {
            row = ([NSDate baseYear] % 100) + row;
        }
        
        return [NSString stringWithFormat:@"%0.2ld", (long)row];
    }
    else if ([options isKindOfClass:NSArray.class])
    {
        if ((component >= [options count]) ||
            ![options[component] isKindOfClass:NSArray.class])
        {
            // one-dimensional options (ignore component)
            return ([options[row] formattedDescription] ?: @"");
        }
        else
        {   // two-dimensional options ([component][row])
            NSArray* nestedArray = options[component];
            
            return ([nestedArray[row] formattedDescription] ?: @"");
        }
    }
    
    return @"";
}

- (void)pickerView:(UIPickerView *)pickerView
      didSelectRow:(NSInteger)row inComponent:(NSInteger)component
{
    id newValue;
    id item = [self itemAtIndexPath:self.focusedIndexPath];
    
    id options = item[WDPRCellOptions];
    if (![options isKindOfClass:NSDictionary.class])
    {
        // TODO: flush out multi-column support
        if ( [options isKindOfClass:[NSArray class]])
        {
            // if we are using model objects as options, we want the actual object to be returned. otherwise this will be NSString
            newValue = options[row];
        }
    }
    else
    {
        NSAssert(WDPRDatePickerModeMonthYear ==
                 [options[WDPRDatePickerMode] intValue], @"");
        
        NSDateComponents* dateComponents = [NSDateComponents new];
        
        if (pickerView.numberOfComponents > 0)
        {
            dateComponents.month = ([pickerView selectedRowInComponent:0] + 1);
        }
        
        if (pickerView.numberOfComponents > 1)
        {
            dateComponents.year = ([NSDate baseYear] + [pickerView selectedRowInComponent:1]);
        }
        
        NSDate *selectedDate = [NSCalendar.currentCalendar dateFromComponents:dateComponents];
        
        unsigned unitFlags = NSCalendarUnitYear | NSCalendarUnitMonth;
        NSDateComponents* minDateComponents = [NSCalendar.currentCalendar components:unitFlags
                                                                            fromDate:options[WDPRCellMinimumDate]];
        
        if (options[WDPRCellMinimumDate] &&
            ((dateComponents.year < minDateComponents.year) ||
             ((dateComponents.month < minDateComponents.month) &&
              (dateComponents.year <= minDateComponents.year))))
        {
            minDateComponents.month = dateComponents.month;
            minDateComponents.year = minDateComponents.year + 1;
            
            //Let's select the minimum expiration date
            newValue = [NSCalendar.currentCalendar dateFromComponents:minDateComponents];
            
            //Select this month in next year
            [pickerView selectRow:minDateComponents.month - 1 inComponent:0 animated:YES];
            [pickerView selectRow:1  inComponent:1 animated:YES];
        }
        else
        {
            newValue = selectedDate;
        }
    }
    
    //Some placeholder items don't have this value set, no need to update
    if (item[WDPRCellDetail])
    {
        [self changeDetailValueForItemAtIndexPath:self.focusedIndexPath to:newValue];
    }
}

- (UIView *)pickerView:(UIPickerView *)pickerView viewForRow:(NSInteger)row
          forComponent:(NSInteger)component reusingView:(UILabel *)label
{
    label = label ?: [[UILabel alloc] initWithFrame:CGRectZero];
    
    label.font = [label.font fontWithSize:WDPRPickerViewOptionLabelFontSize];
    label.textAlignment = NSTextAlignmentCenter;
    
    label.text = [self pickerView:pickerView
                      titleForRow:row forComponent:component];
    //label.text = [label.text stringByAppendingString:@"      "];
    
    id optionLabels = [self itemAtIndexPath:self.focusedIndexPath][WDPRCellOptionAccessibilityLabels];
    NSString *accessibilityLabel = nil;
    if ([optionLabels isKindOfClass:NSArray.class])
    {
        if ((component >= [optionLabels count]) ||
            ![optionLabels[component] isKindOfClass:NSArray.class])
        {
            // one-dimensional options (ignore component)
            accessibilityLabel = ([optionLabels[row] formattedDescription] ?: @"");
        }
        else
        {   // two-dimensional options ([component][row])
            NSArray* nestedArray = optionLabels[component];
            
            accessibilityLabel = ([nestedArray[row] formattedDescription] ?: @"");
        }
    }
    if (accessibilityLabel)
    {
        label.accessibilityLabel = accessibilityLabel;
    }
    
    return label;
}



@end`

**Comment by hmil** [comment]
Thanks @rakeshmick for the hint. I fixed my objective-c code according to your suggestion:

```objective-c
- (NSString *)pickerView:(UIPickerView *)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component {
 ```
Instead of:
```objective-c
- (UIView *)pickerView:(UIPickerView *)pickerView viewForRow:(NSInteger)row forComponent:(NSInteger)component reusingView:(UIView *)view {
```

The font is ugly now but at least I can automate it!
