### ISSUE TITLE
Android: Error: New app path browser did not have extension .apk when running over a browser

### ISSUE THREAD

**Issue by brinkins** [appium/appium#6963]
## Unable to run Appium on android for chrome or android browser

On android, when I try to run Appium on a browser, this is the error I get:
[MJSONWP] Encountered internal error running command: Error: New app path browser did not have extension .apk
## Environment
- Appium version (or git revision) that exhibits the issue: Version 1.5.3 (Ara), 1.5.2 has a different error but there is still an issue.
- Last Appium version that did not exhibit the issue (if applicable): 1.4.13
- Desktop OS/version used to run Appium: Mac OS El Capitan 10.11.6
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: checked on android browser and chrome browser with android 4.2.2 real device and 5.1.0 Genymotion simulator (with GP services and chrome installed and working)
- Real device or emulator/simulator: both described above
- Appium CLI or Appium.app|exe: 1.5.3, 1.5.2 app
## Link to Appium logs

https://gist.github.com/brinkins/fa15591631fb0440b041b203bf03c64b
## Code To Reproduce Issue [ Good To Have ]

Just launch Appium with the capabilities mentioned: "browserName": "Browser" or "Chrome"
![image](https://cloud.githubusercontent.com/assets/5406782/19201721/5ba8e10a-8ca5-11e6-8b52-36291a55c74f.png)

**Comment by dpgraham** [comment]
Looks like the error is probably due to: 

```The desired capabilities should generally not include both an app and a browser```

We have a new desktop client in development:

https://github.com/appium/appium-desktop

**Comment by brinkins** [comment]
Hi Dan, I don't have both capabilities enabled, just the browser, so I am not sure the error is because of what you say (If you check the screenshot there is no apk enabled). It also happens when I run my scripts, and I do not have an application in my capabilities. Just:
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, BROWSER);
or 
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, Constants.CHROME);

along with these other ones:
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, ReadProperties.getProperty(Properties.AUTOMATOR_NAME));
        capabilities.setCapability(CustomCapabilities.WAIT_FOR_APP_SCRIPT,true);
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT,Constants.APPIUM_COMMAND_TIMEOUT);
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, deviceData.getDeviceName());
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, Parameters.ANDROID);

Does it work for you?

The new Appium Desktop looks awesome, I will def try it out

**Comment by dpgraham** [comment]
As a workaround can you try setting the 'app' to null explicitly and let me know what happens.

 (there's a similar issue like this https://github.com/appium/appium/issues/6790 where setting app to null fixed it).

**Comment by brinkins** [comment]
Dan, as you said, setting the app as null does fix the issue. Thanks!

**Comment by dpgraham** [comment]
No problem. Glad I could help!
