### ISSUE TITLE
need  efficiency  way to  restart/close  application    appium1.6-beta3/ iOS10

### ISSUE THREAD

**Issue by bearxc** [appium/appium#6964]
we need  close/restart app   for each test  make sure in clean state .

So far , when  appium launches  app ,  agent is  always  redeployed  ,  it is slow . 

Based on  following link,  "With WDA you can simply stat new session without need for re-deploying"

https://github.com/facebook/WebDriverAgent/issues/322

**Comment by imurchie** [comment]
Currently Appium has no way of knowing that the WDA app is on the device and up-to-date. Once things stabilize we can implement something like that. But given that both this project and WDA are in development, rebuilding and reinstalling is the only way to keep things in sync.

**Comment by yaphatak** [comment]
This is easy to do but issue that we experienced with this is `WDA` becomes unusable after few tests and need to restart it anyways. But we can still have this implemented with `capability` to turn on or off feature

**Comment by bearxc** [comment]
capability  is a good ideal  , please keep me in loop .

**Comment by SrinivasanTarget** [comment]
@saikrishna321 FYI

**Comment by saikrishna321** [comment]
@yaphatak when u say WDA gets unstable after few test runs, do you remove the WebDriverAgent and let appium install it again ?
