### ISSUE TITLE
add capability to install cert

### ISSUE THREAD

**Issue by huminzhi** [appium/appium#6966]
Similar to this enhancement:
https://github.com/appium/appium/issues/6939
We want to install cert into the simulator so that it works with https

We previously use UIA host().performTask to do it as below, it will be nice if we can add a capability to achieve the same thing..  I thought about pull/push file, however, not sure how to get "$IPHONE_SHARED_RESOURCES_DIRECTORY",  so alternatively,  option2: appium adds an API to getIPHONESharedResourceDir (simulator path), option3: pull/push file can understand environment variables like "$IPHONE_SHARED_RESOURCES_DIRECTORY"... 

Thank you!

String cmd = "SHA1='xxxxxxxx'; SUBJ='xxxxx';TSET='xxxx';DATA='xxx'; SQLITEDBPATH=\\"$IPHONE_SHARED_RESOURCES_DIRECTORY/Library/Keychains/TrustStore.sqlite3\\"; " + 
                "if [ -e \\"$SQLITEDBPATH\\" ]; then " +
                "   sqlite3 \\"$SQLITEDBPATH\\" \\"INSERT INTO 'tsettings' VALUES(X'$SHA1',X'$SUBJ',X'$TSET',X'$DATA');\\"; " +
                "fi;";    executeRawInstrumentsJS("UIATarget.localTarget().host().performTaskWithPathArgumentsTimeout(\"/bin/sh\",[\"-c\",\"" + cmd + "\"],5)");

**Comment by jlipps** [comment]
Acceptance criteria:

* [ ] method `installSSLCert` added to instances of the sim object in appium-ios-simulator
* [ ] appium-ios-driver and appium-xcuitest-driver startup flows updated to look for a `customSSLCert` capability
* [ ] the value for this capability should either be ASCII or b64-encoded binary, depending on what we decide needs to be done
* [ ] tested by navigating to some site in safari with the custom cert
