### ISSUE TITLE
add capability for launch services

### ISSUE THREAD

**Issue by huminzhi** [appium/appium#6967]
We need to enable launch services for the app so that it can be launched from a URL in simulator without popping up an alert.
We previously achieve this by using UIA host().performTask as below and now we hope appium can add a capability for it, or alternatively, expose $xcodePath and $IPHONE_SHARED_RESOURCES_DIRECTORY through API, or allow push/pull file understand environment variables.

String cmd = "xcodePath=$(xcode-select -p);" +
"/usr/libexec/PlistBuddy -c \\"Add $xcodePath/Platforms/iPhoneSimulator.platform/Developer/Library/CoreSimulator/RuntimeOverlay/usr/libexec/CoreSimulatorBridge-->[appname]  string  " +
appBundleId + "\\" $IPHONE_SHARED_RESOURCES_DIRECTORY/Library/Preferences/com.apple.launchservices.schemeapproval.plist";
       executeRawInstrumentsJS("UIATarget.localTarget().host().performTaskWithPathArgumentsTimeout(\"/bin/sh\",[\"-c\",\"" + cmd + "\"],5)");

**Comment by dpgraham** [comment]
@jlipps I don't think I understand this issue, but it's in the backlog. What priority do you think we should give it?

**Comment by jlipps** [comment]
@dpgraham this is basically to allow people to click on specialized URLs to deep-link to an app, without having to first accept the dialog that pops up asking whether it's ok to be redirected to that app. basically we just have to add this bit to the appropriate plist on the appium side, maybe hidden behind a capability. shouldn't be too much work.

**Comment by mykola-mokhnach** [comment]
The current scenario could be achieved by using pullFile/pushFile helpers. E.g. the original plist could be pulled locally, modified and then pushed back to the Simulator file system
