### ISSUE TITLE
Cannot run test on real iOS device by error: Could not navigate to webview.

### ISSUE THREAD

**Issue by ReinhardXu2007** [appium/appium#6970]
## The problem

When initializing the driver, there is an error occured:

```
[MJSONWP] Encountered internal error running command: Error: Could not navigate to webview! Err: Cannot read property 'split' of undefined
  at IosDriver.spinHandles$ (lib/commands/context.js:463:15)
  at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/babel-runtime/regenerator/runtime.js:67:40)

```
## Environment
- Appium version (or git revision) that exhibits the issue:
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3
- Desktop OS/version used to run Appium: 10.11.5
- Node.js version (unless using Appium.app|exe): 4.5.0
- Mobile platform/version under test: ios 9.3.2
- Real device or emulator/simulator: iphone5s
- Appium CLI or Appium.app|exe: start by cmd: node appium/build/lib/main.js --debug-log-spacing --default-device
- ios_webkit_debug_proxy: latest version downloaded from github
## Diagnosis

I've debugged the js code, and found the cause, but don't know how to resolve it.
In module appium-ios-driver/node_modules/appium-remote-debugger, webkit-remote-debugger.js , it would ask devices info from ios_webkit_debug_proxy.
The proxy returned json like: 

> [{"deviceId":"81efb4eadca74ab261864f3e4252cb10fe4bc8df","deviceName":"徐文灏的 iPhone","url":"localhost:9223"}]

But in js code it expects property 'webSocketDebuggerUrl' what is not returned from proxy.

> var urlArray = pageObject.webSocketDebuggerUrl.split('/').reverse();

How to resolve it?
## Code To Reproduce Issue [ Good To Have ]

```
    @Test
    public void test() throws MalformedURLException, InterruptedException {
        DesiredCapabilities desiredCapabilities = new DesiredCapabilities();
        desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone");
        desiredCapabilities.setCapability("udid", "81efb4eadca74ab261864f3e4252cb10fe4bc8df");

        desiredCapabilities.setCapability(MobileCapabilityType.BROWSER_NAME, MobileBrowserType.SAFARI);
        URL url = new URL("http://127.0.0.1:4723/wd/hub");
        this.driver = new IOSDriver<IOSElement>(url, desiredCapabilities);

        driver.get("https://www.baidu.com");
        Thread.sleep(5000L);
        System.out.println(driver.getPageSource());
    }

```

**Comment by imurchie** [comment]
This does seem like a bug. We'll look into it.

**Comment by rkavalap** [comment]
Unable to repro this on a simulator. https://youtu.be/fPsOrCRVyB4
Need to test this out on a real device. Will post my findings soon, once i get that setup. 
@ReinhardXu2007  Can you post a link of the appium server log as a gist, so we can get an entire stack trace that way i can dig further based on the dependencies

**Comment by Siddh010** [comment]
Hi 
I am using Appium 1.6.1 , with same desiredCapabilities as mention above  in Real device (iphone6) I am getting below error message while executing  in safari browser:-
It will lunch the browser and open "http://appium.io'"  and below error message  will be display ... 

Also execute ios_webkit_debug_proxy -c UUID:27753

I have also start 


[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
//[iOS] Could not find any webviews yet, refreshing/retrying
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753

**Comment by ericomurtez** [comment]
Hi, 

I Am seeing same as above in almost identical conditions. Looking forward to fix.

If there is a workaround please let me know in meantime.

Thanks,
Eric

**Comment by jlipps** [comment]
@ericomurtez can you attach a full set of Appium logs run on the latest version of Appium? We're having trouble reproducing this.

**Comment by ericomurtez** [comment]
https://gist.github.com/ericomurtez/0608b5424a49e682de4767f4f4d92bee

Let me know if would like more info.

**Comment by jlipps** [comment]
Thanks @ericomurtez that is an instance of the same problem. Do you know precisely which version of i-w-d-p you're using?

**Comment by ericomurtez** [comment]
Just updated to latest (1.7) and got the same error.

**Comment by ericomurtez** [comment]
Hey guys, did you have any update on this?

**Comment by jlipps** [comment]
No update yet but @ericomurtez thanks for confirming the version, hopefully that will help us to repro

**Comment by imurchie** [comment]
The problem is starting `ios-webkit-debug-proxy` in the way that Google [recommends](https://github.com/google/ios-webkit-debug-proxy#start-the-proxy). This leads to the proxy listening on port 9221, but each individual device being on subsequent (open) ports. So with a single iPhone attached I get it actually listening on port 9222.

If you start the proxy with `ios_webkit_debug_proxy -c <uuid>:<port> -d`you get the device correctly on the port specified, and Appium can connect and get the correct information (rather than a notice of the correct destination).

**Comment by ericomurtez** [comment]
That worked for me, thank you very much.

**Comment by imurchie** [comment]
Awesome!

**Comment by JESii** [comment]
Just in case someone else is reading this issue to solve a problem: the "standard" port when running i-w-d-p for Appium is 27753, 9222; see issue #7847.  What worked for me was to start i-w-d-p likc so:
`ios_webkit_debug_proxy -c <uuid>:27753 -d`
As pointed out by @imurchie in that issue: "If you want to run `ios-webkit-debug-proxy` on a port other than `27753`, you need to specify that port through the `--webkit-debug-proxy-port` server argument. Otherwise it has no way of knowing where the proxy is running."

**Comment by skansar** [comment]
👍 @JESii

**Comment by MathuMarques** [comment]
Hey I'm having the same issue, but this message appears when I try to set appium proxy port.


MacBook-Pro-de-Sala:~ sala5a$ ios_webkit_debug_proxy -c <auto>:<27343> -d
-bash: syntax error near unexpected token `27343'

**Comment by gauravgandhi15** [comment]
> The problem is starting `ios-webkit-debug-proxy` in the way that Google [recommends](https://github.com/google/ios-webkit-debug-proxy#start-the-proxy). This leads to the proxy listening on port 9221, but each individual device being on subsequent (open) ports. So with a single iPhone attached I get it actually listening on port 9222.
> 
> If you start the proxy with `ios_webkit_debug_proxy -c <uuid>:<port> -d`you get the device correctly on the port specified, and Appium can connect and get the correct information (rather than a notice of the correct destination).


How do i change the port to 9222? Please provide any command to do it or if i can change in the appium GUI

**Comment by imurchie** [comment]
You can change the port that `ios-webkit-debug-proxy` listens to by using the command
```
ios_webkit_debug_proxy -c <device-uuid>:<port-you-want> -d
```

You can change the port that Appium will listen on using the `--webkit-debug-proxy-port` server flag when starting Appium
```
appium --webkit-debug-proxy-port <port-you-want>
```

**Comment by gauravgandhi15** [comment]
Thanks. For some reason my appium through terminal not working. Getting
some stack maximum size exceed.  Can I change this in appium GUI somewhere?

**Comment by imurchie** [comment]
If you create an issue we could perhaps figure out what is wrong with Appium in your terminal.

I do not think there is a way to change it from the GUI. Is there a reason the port Appium defaults to (`27753`) is not usable?

**Comment by gauravgandhi15** [comment]
Actually I’m not sure, I have worked on android but iOS working for the
first time. I just my setup but getting this  error webview not found. When
I googled it, I found this post. Is there any way to point my scripts to
27753 which is already running?

**Comment by imurchie** [comment]
That is what happens by default. Appium expected the debug proxy to be running on that port, somewhere. 

Information can be found here: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/web/ios-webkit-debug-proxy.md

**Comment by gauravgandhi15** [comment]
with this

$ sudo apt-get install autoconf automake libusb-dev libusb-1.0-0-dev
libplist-dev libplist++-dev usbmuxd libtool libimobiledevice-dev


I am getting error apt-get command not found but i do have homebrew
installed( i verify it by brew -v)

What should i do?

**Comment by imurchie** [comment]
If you have Homebrew, just install using `brew install ios-webkit-debug-proxy`. There is no need to install from source.

**Comment by gauravgandhi15** [comment]
Thank you so much. It works now
