### ISSUE TITLE
Appium could not shows WEBVIEW but actually exists on an Android Native App

### ISSUE THREAD

**Issue by kentzhu1020** [appium/appium#6973]
## The problem

I'm running Appium on Mac to test an Android Native App directly on an Android device. However, when I try to fetch the contexts and switch to the one containing WEBVIEW (When I use UIAutomator Viewer or Chrome DevelopTool Inspector, It does exist named as android.webkit.WebView), But when I try to catch it via driver.switch_to.context('WEBVIEW') it gives me No Such Context...I debug the code on the contexts lists only returns one context, NATIVE_APP.

When I use the inspector, I'm able to see a WebView and a lot of View children appended to it, which relate to each one of the elements inside the app. So, despite it doesn't show the element tree in Web view mode, I'm able to see it's using a WebView, but somehow isn't able to connect to that specific context.

I find some guy provide that change the desire_capability['automationName']='Selendroid' it does not work for me due to my other native elements could not be found any longer if it changes
## Environment
- Appium version: 1.5.3
- Desktop OS/version used to run Appium: Mac 
- Node.js version (unless using Appium.app|exe): v6.5.0
- Mobile platform/version under test: Android
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: *.apk
## Details

Please see the problem
## Link to Appium logs

[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.performTouch() result: true
[HTTP] <-- POST /wd/hub/session/d1ad0f3b-e7a2-4fd4-a561-8539b354b37d/touch/perform 200 224 ms - 76 
[HTTP] --> POST /wd/hub/session/d1ad0f3b-e7a2-4fd4-a561-8539b354b37d/context {"sessionId":"d1ad0f3b-e7a2-4fd4-a561-8539b354b37d","name":"WEBVIEW"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW","d1ad0f3b-e7a2-4...
[debug] [AndroidDriver] **_Getting a list of available webviews_**
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /PATH/TO/Andriod/android-sdk-macosx/platform-tools/adb with args: ["-P",5037,"-s","**UDID**","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] Found webviews: []
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"]
[HTTP] <-- POST /wd/hub/session/d1ad0f3b-e7a2-4fd4-a561-8539b354b37d/context 500 49 ms - 109 
{}
[HTTP] --> POST /wd/hub/session/d1ad0f3b-e7a2-4fd4-a561-8539b354b37d/element {"using":"id","sessionId":"d1ad0f3b-e7a2-4fd4-a561-8539b354b37d","value":"com.xxx.mobile:id/button_home"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.xxx.mobile:i...
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.xxx.mobile:id/button_home","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.xxx.mobile:id/button_home","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.xxx.mobile:id/button_home' using 'ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.xxx.mobile:id/button_home]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"77"}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"77"}
[HTTP] <-- POST /wd/hub/session/d1ad0f3b-e7a2-4fd4-a561-8539b354b37d/element 200 47 ms - 88 
[HTTP] --> POST /wd/hub/session/d1ad0f3b-e7a2-4fd4-a561-8539b354b37d/element {"using":"id","sessionId":"d1ad0f3b-e7a2-4fd4-a561-8539b354b37d","value":"com.xxx.mobile:id/button_home"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["id","com.xxx.mobile:i...
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.xxx.mobile:id/button_home","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.xxx.mobile:id/button_home","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding 'com.xxx.mobile:id/button_home' using 'ID' with the contextId: '' multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.xxx.mobile:id/button_home]
## Code To Reproduce Issue [ Good To Have ]

driver.switch_to.context("WEBVIEW")
driver.find_element_by_id("content").get_attribute("product-id")
driver.switch_to.context("NATIVE_APP")
<img width="612" alt="pic" src="https://cloud.githubusercontent.com/assets/7146371/19219191/3f2acac0-8e3f-11e6-9601-223bd9e6a7f6.png">

**Comment by ravikirankandula** [comment]
me also facing similar issue.. but didn't find any solution

**Comment by Eta92** [comment]
Same problem here.
I tried to run test on Windows, it failed because context issue. So I destroyed my OS to go for Ubuntu.
And magic ! I face exactly the same problem. Auto web-view on or not, no wait to start testing whereas the app is installed and ready.

**Comment by mwager** [comment]
Same problem here, but cannot find a solution..


```
appium output: (this gets logged several times, the app already started)

[debug] [AndroidDriver] Found webviews: []
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /path/to/android-sdk/platform-tools/adb with args: ["-P",5037,"-s","db87d3f2","shell","cat","/proc/net/unix"]
```

Then protractor fails:

```
[14:54:54] E/launcher - No such context found.
[14:54:54] E/launcher - WebDriverError: No such context found.
    at WebDriverError (/Users/work/Projects/foo/lbo-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/Users/work/Projects/foo/lbo-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/Users/work/Projects/foo/lbo-e2e/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/Users/work/Projects/foo/lbo-e2e/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/Users/work/Projects/foo/lbo-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/Users/work/Projects/foo/lbo-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/Users/work/Projects/foo/lbo-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/Users/work/Projects/foo/lbo-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /Users/work/Projects/foo/lbo-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by pcortez** [comment]
Same problem, but I tried with OS X and an android APK with crosswalk.
```
[debug] [ADB] Running '/Users/pcortez/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGD855aaca49c8","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] Found webviews: []
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"]
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/pcortez/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGD855aaca49c8","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] Found webviews: []
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"]
[debug] [AndroidDriver] Shutting down Android driver
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/pcortez/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGD855aaca49c8","shell","am","force-stop","cl.xxxx.xxxx"]
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/pcortez/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGD855aaca49c8","shell","input","keyevent",3]
```

**Comment by jlipps** [comment]
If the OP is also using crosswalk webviews, I think that's probably the issue. IIRC, as of this moment Chromedriver does not support automating crosswalk webviews. I would raise an issue at Google's tracker for Chromedriver asking for Crosswalk support.

**Comment by LukasLewandowski** [comment]
Any solution for this? (I am testing app build by Cordova and on iOS I can switch to webview using ios-webkit-debug-proxy but unfortunately Android have only NATIVE_APP context).

**Comment by obstar** [comment]
same issue for android 7.0, appium 1.6.4
webview is visible in inspector but during test run the only available contexts to switch is native_app

**Comment by pantherqin** [comment]
Similar issue here. Android 7.1, appium 1.6. 

In instpector I can see the webview, I can see the resource-id field.

When using driver.elementByClassName("android.webkit.WebView"), I get the webview element. However when I use driver.elementById("com.xxx.my-app-name:id/webView"), I got UNDEFINED.

**Comment by jcmorfin** [comment]
Similar issue for me. Testing on Android 7.0 using Appium 1.6.4.

I can see the WebView in the app but when I call _driver.getContextHandles()_ I get only NATIVE_APP.

**Comment by LukasLewandowski** [comment]
You can use modified version of chromedriver to work with Web View on Android.

I am using chromedriver from:

https://github.com/piotrekkmt/chromedriver-appium

with added desired_capabilities:
           "chromedriverExecutable": os.path.join(PROJECT_ROOT, "chromedriver"),
            "androidDeviceSocket": "<appPackage>_devtools_remote",
            "chromeOptions": {
                "androidDeviceSocket": "<appPackage>_devtools_remote"
            },

**Comment by ahermle93** [comment]
Facing the same issues on Windows/MacOS with Appium 1.6.5 and Android 7.0. Is there a working solution?

@LukasLewandowski Your solution didn't work for me.

**Comment by LukasLewandowski** [comment]
@ahermle93 Did You use uiautomator2?

**Comment by keshavwy** [comment]
@ahermle93 @LukasLewandowski @kentzhu1020 I am also still facing this issue. Does anyone find a solution for this problem?

**Comment by Anand093** [comment]
Can anybody help me on this 
[debug] [AndroidDriver] Found webviews: []
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"]


My appium next line of code doesn't execute when Found webviews: [] happens

**Comment by imurchie** [comment]
@Anand093 Please provide the full logs as a link to a [gist](https://gist.github.com).

**Comment by vutukuriswathi** [comment]
Even i am also facing the same issue.
Even though webview is available ,appium is showing only the native app context
Here I am attaching the logs for your reference
[appium-server-logs.txt](https://github.com/appium/appium/files/1662094/appium-server-logs.txt)

Here I am mentioning the code which i used

for( String contextName : contextNames){
                System.out.println(contextName);
  
            if (contextName.contains("WEBVIEW")) {
                TestBase.driver.context(contextName);
            }
}

**Comment by Anand093** [comment]
I have a temporary solution 
If you stuck with webview and your further code is not executing
 
**driver.openNotifications();
driver.findElement(By.id("com.android.systemui:id/notification_stack_scroller")).click();**

Basically i just open notification & clicking on any mobile element(inspect and get any mobile element from notification panel), so that driver will again come back to default screen. 
remember this is for android.
If you do so control will again come back to normal screen & code flow wont stop.

**Comment by Anand093** [comment]
@imurchie some how i manage to get my code working. Anyways thanks for the help :) :)

**Comment by ajeet0808** [comment]
@Anand093 
Could you help me out , i am also facing same Error-
[debug] [AndroidDriver] Found webviews: []
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"].

**Comment by Anand093** [comment]
@ajeet0808 
driver.openNotifications();
driver.findElement(By.id("com.android.systemui:id/notification_stack_scroller")).click();

Basically i just open notification & clicking on any mobile element(inspect and get any mobile element from notification panel), so that driver will again come back to default screen.
remember this is for android.
If you do so control will again come back to normal screen & code flow wont stop.

**Comment by Anand093** [comment]
@ajeet0808  
Let me know whether the above solution solves your problem ?

**Comment by kaesaecracker** [comment]
Same problem here. @Anand093 your solution did not work for me.

**Comment by Anand093** [comment]
Hi @

i just added two line before finding element or elements using android driver reference.

driver.openNotifications();
driver.navigate().back();
Thread.sleep(2000);

above 2 lines will move driver to the mobile notification panel, actually doing that will bring driver to the current focus.
that solved my problem
I am not sure whether same solution will solve your problem, but can be checked.
