### ISSUE TITLE
Xpath changes in Appium 1.6

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#6976]
I have updated my devices to iOS 10 and appium to 1.6 beta 3, I am observing that there is noticeable changes to xpaths in Appium 1.6. In my application I am nearly using 500-600 xpaths. Is there any to match the xpath changes ?

**Comment by appiumnovice** [comment]
In my case, Idid a find/replace to replace all "UAI" by "XCUIElementType"
Example : UIAButton -> XCUIElementTypeButton

I had 2 exceptions:
UIATableCell -> XCUIElementTypeTableCell
UIATableView -> XCUIElementTypeTable

**Comment by tapisky** [comment]
How about executing scripts? For example, in appium <= 1.5.3 I was able to run this script:
`$driver.execute_script("UIATarget.localTarget().frontMostApp().version()")`

But now with XCUI I can't. Any ideas?

**Comment by imurchie** [comment]
Executing scripts will not work. UI Automation is no longer there, so the entire scripting language is gone. We are working on another way to do the same sort of thing, but don't have one yet.
