### ISSUE TITLE
Travis post-build hook to release on npm (missing)

### ISSUE THREAD

**Issue by F2X** [appium/appium#6977]
## The problem

The latest available version of appium is available on GitHub releases but not in npm

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: Debian stretch
* Node.js version (unless using Appium.app|exe): 6.7.0
* Mobile platform/version under test: N/A
* Real device or emulator/simulator:N/A
* Appium CLI or Appium.app|exe:N/A

## Details

There is no Travis publishing hook to release on npm: [https://docs.travis-ci.com/user/deployment/npm/](https://docs.travis-ci.com/user/deployment/npm/)

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

npm install -g appium -> 1.5.3 version

**Comment by imurchie** [comment]
We don't want any sort of Travis integration into this. But we are looking into why the manual release failed.
