### ISSUE TITLE
[1.6.0-beta3][Android] "Error: Unable to get pids for uiautomator"

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#6978]
## The problem

Just installed the latest 1.6.0-beta3 release and seeing this error in console:
`[ADB] Error: Unable to get pids for uiautomator. Orginial error: this.shell(...).trim is not a function`

Test is still passing in spite of console error.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0-beta3
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe): v5.1.1
* Mobile platform/version under test: Android 5.0.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

https://gist.github.com/JaniJegoroff/32f8f3237cd53244d213ac6280df5fde

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
Ugh. Yes, the trim is on the wrong thing.

**Comment by crashbell** [comment]
@imurchie Could you please let me know when this fix will be available on NPM?

**Comment by imurchie** [comment]
My apologies. It is released as `appium-adb@2.6.18`. To get it from npm within a release, you can use `--no-shrinkwrap`

```
npm install -g appium --no-shrinkwrap
```

**Comment by crashbell** [comment]
Thanks a lot @imurchie!
It's not relevant to this PR but it seems like we don't need `--no-shrinkwrap` to get the latest `adb` version. (I'm still using Appium 1.5.3). I got `appium-adb@2.6.17` yesterday even when running `npm install` without `--no-shrinkwrap`.

I suspect `appium-android-bootstrap` since it put `appium-adb` in  `devDependencies` (ref: [package.json](https://github.com/appium/appium-android-bootstrap/blob/master/package.json#L44) and somehow that bypassed NPM installation.

**Comment by Vishnu1067** [comment]
I still have a problem

Appium - v1.6.0
adb - 2.6.18
node - v6.8.1

When i install with npm install -g appium --no-shrinkwrap, there is an error like  

`ERROR in ./Scripts/Performance.ts
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)`

[https://github.com/webpack/webpack/issues/2463](url)

Reference: https://github.com/webpack/webpack/issues/2463

Is there new release happening for adb again? Please help me to resolve this problem.

**Comment by rops** [comment]
Is a new release planned to ship with appium-adb@2.6.18?

**Comment by jlipps** [comment]
@rops shouldn't be too long, no

**Comment by haifengrundadi** [comment]
Do you fix the problem? @jlipps

**Comment by jlipps** [comment]
Yes, Appium has released several versions since the fix was pushed.
