### ISSUE TITLE
[Appium 1.6.0-beta3/iOS] click functionality is not working properly with List<iOSELement>  

### ISSUE THREAD

**Issue by mmuntakim15** [appium/appium#6981]
## The problem

Unable to perform click on element from List in consistent basis, The test step fails about 70% of the time, even though element is enabled and visible, it just randomly clicks on another button on the screen.  However test step passes about 30 percent of the time. 

Note: This scenario passed 100% of the time in appium 1.5.3, we have not changed any code from our end. 
## Environment
- Appium version (or git revision) that exhibits the issue: Appium 1.6.0-beta3
- Last Appium version that did not exhibit the issue (if applicable): Appium 1.5.3
- Desktop OS/version used to run Appium: Mac 10.11.6
- Node.js version (unless using Appium.app|exe): v4.4.3
- Mobile platform/version under test: ipadAir/iOS 10.0
- Real device or emulator/simulator:simulator
- Appium CLI or Appium.app|exe:CLI
## Link to Appium logs

I dont know if the log is going help much since app click on some other button instead actual specified element so there are no actual error, it just starts looking for subsequent steps elements and throws an NoSuchElementFoundException. Please let me know if you need the logs. 
## Code To Reproduce Issue [ Good To Have ]

```
  @iOSFindBy(xpath = "//XCUIElementTypeCell[starts-with(@name, 'reservation_cell_id_')]")
    private List<IOSElement> reservationRowList;

   @Step
    public void clickOnReservationRowByIndex() {
       reservationRowList.get(0).click();
    }
```

**Comment by mykola-mokhnach** [comment]
Most likely there is some animation between clicks, which means it might be, that the previous element does not have enough time to disappear after the next one is clicked. Try to add some delay between clicks or wait explicitly until current element disappears after it is clicked.
Also, try to use className/AccessibilityId/predicate locators - xpath is pretty slow for now :-(

**Comment by mmuntakim15** [comment]
@mykola-mokhnach I tried using delays but no luck :( thanks for your reply, I'll continue to debug and see what happens.

**Comment by dpgraham** [comment]
Closing this issue. If this is still a problem with the latest Appium, let me know and I'll re-open.
