### ISSUE TITLE
Tests timeout looking for elements in iOS9

### ISSUE THREAD

**Issue by chrisie** [appium/appium#6982]
## The problem

I recently upgraded from Appium 1.4.14 to Appium 1.6.0-beta3 in order to be able to run my tests with XCode 8. My tests run fine on an iOS 10 emulator, but fail on the iOS 9 emulator, where any attempt to locate an element in a page times out.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0-beta3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: OSX El Capitan
- Node.js version (unless using Appium.app|exe): 4.6.0
- Mobile platform/version under test: iOS 9 / 10 
- Real device or emulator/simulator: iPhone 6 emulator
- Appium CLI or Appium.app|exe: CLI
## Details

The automated tests pass on an iOS 10 emulator but fail on an iOS 9 emulator where any interaction with the page elements times out. I am certain that it is not a configuration issue since the exact same configuration works fine with a different app. Both apps are hybrid cordova apps with Angular and I can't for the life of me imagine what the difference between the two is and why one works and the other doesn't.
## Link to Appium logs

The [iOS 9 logs](https://gist.github.com/chrisie/ba466beb5844675130b0bb054653648b) for the tests that fail.
The [iOS 10 logs](https://gist.github.com/chrisie/58a5c0b371a5f7c115aca29e67e8d763) for the tests that pass.
## Code To Reproduce Issue [ Good To Have ]

The test step that fails (from which the logs above are produced) is the following:

```
var selector = '.banner';
element.all(by.css(selector)).then(function(elements) {
    console.log('Found elements');
    console.log(elements);
});
```

**Comment by jlipps** [comment]
@chrisie for iOS 9 if you want tests to work the same way, simply don't include `automationName: XCUITest`. this only works in 9.3 and up.

**Comment by chrisie** [comment]
@jlipps It is actually iOS 9.3 that I'm trying to use so it should work, shouldn't it?

**Comment by jlipps** [comment]
@chrisie in the iOS 9 logfile I see that your client is calling `driver.quit` without waiting for a response from the async execute script calls. I'm unsure why your client would be doing that. Is it timing out or something?

**Comment by chrisie** [comment]
I'm not sure why it''s happening either. The behaviour I see is that the test step times out and it happens regardless of what I do inside the test step. It also seems to happen with protractor bit not when calling methods directly from wd.js through the wd-bridge, which makes me believe that it could be something related to the script that protractor uses to wait for Angular. Any idea what else I could test / try to get a better view of the root cause of the issue?

**Comment by jlipps** [comment]
Unfortunately I don't have any ideas. I know protractor does odd things and we often have problems with it. It appears to be a client-side issue in any case. I'd dig into why protractor is quitting the session on you.
