### ISSUE TITLE
[1.5.3] Can't use inspector on iOS real device

### ISSUE THREAD

**Issue by vincentlabatut** [appium/appium#6983]
## The problem

I can't use the inspector when running appium with an iOS physical device.
## Environment
- Appium version : 1.5.3
- Mac OS 10.11.6
- testing iOS 9.3
- iPhone 6
## Details

I start appium, it works, it installs the IPA on the physical device, the session looks ok. But when I click the inspector button, I get the "Could not Launch Appium Inspector".
BTW, I have --pre-launch in my options, but it never did anything, nothing happens at startup until I connect with an appium client.
## Link to Appium logs

See attached log with
[appium-log.txt](https://github.com/appium/appium/files/519872/appium-log.txt)
## Command line

(see logs for details)

'/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --pre-launch --debug-log-spacing --platform-version "9.3.5" --platform-name "iOS" --app "/Users/myself/Documents/MyCompanyReact-Recette.ipa" --udid "1d4826814a97d90167684918d9e29a5baf6358a9" --device-name "iPhone 6" --session-override

**Comment by imurchie** [comment]
Please try `appium-desktop`.
