### ISSUE TITLE
Appium 1.6 beta3 crashes

### ISSUE THREAD

**Issue by tolgatanriverdi** [appium/appium#6985]
Appium 1.6 beta crashes with following error. Does anyone know the reason?

```
[Xcode] 2016-10-10 20:53:14.407 xcodebuild[18966:150367] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

[Xcode] 
Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

[Xcode] ** TEST FAILED **

Unable to start WebDriverAgent: Error: spawn EACCES
```

**Comment by mykola-mokhnach** [comment]
It would be more useful to get the whole Xcode log packed as gist.

**Comment by tolgatanriverdi** [comment]
How can I do that?

**Comment by imurchie** [comment]
Does this happen if you run the `xcodebuild` command on its own?

**Comment by tolgatanriverdi** [comment]
No If I run the xcodebuild bymyself this error doesnt occur but, when I run xcodebuild manualy appium still triest to execute webdriveragent and this terminates the already running webdriveragent

**Comment by imurchie** [comment]
Not sure what the last part means, but that you can run the xcodebuild command manually is something.

What are your desired capabilities?

**Comment by tolgatanriverdi** [comment]
DesiredCapabilities capabilities = new DesiredCapabilities();
         capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
         capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.0");
         capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,   this.deviceSettings.getDeviceName());
         capabilities.setCapability(MobileCapabilityType.UDID, this.deviceSettings.getDeviceID());
         capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
         capabilities.setCapability("showIOSLog", true);
         capabilities.setCapability("autoAcceptAlerts",true);
         capabilities.setCapability("fullReset", false);
         capabilities.setCapability("noReset", true);
         capabilities.setCapability("automationName", "XCUITest");   
         capabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/");

**Comment by imurchie** [comment]
Alright. Change the last line from 

```
capabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/");
```

to 

```
capabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
```

**Comment by tolgatanriverdi** [comment]
That Worked 

Thanks

**Comment by imurchie** [comment]
No problem! I'm glad it works. The next version will make that error more clear.
