### ISSUE TITLE
App is not launching

### ISSUE THREAD

**Issue by qakapil** [appium/appium#6986]
## The problem

Even though I have xcpretty installed but still I see this message in Appium logs while trying to start my test - 
debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...

## Environment
Xcode 8
Mac OS 10.11.6
Devices - Tested with iPhone iOS10 and iPad iOS9
Appium-Python-Client

## Details
I set a break point after create_driver command and noticed that the test gets stuck at create_driver for a couple of minutes with following lines being printed on Appium logs - 
[XCUITest] WebDriverAgent started at url 'http://192.168.8.218:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bu...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...

After a few minutes the test proceeds. Looking at the logs it seems everything was fine, however, on real device the App never gets launched. Element not found message in the logs gives a false impression. Probably it is an issue with iproxy ?

## Link to Appium logs
https://gist.github.com/qakapil/c83a828b091518d9a3cd2a63cf4b1988

**Comment by qakapil** [comment]
Update - I realized that if I manually install the app first and then run my Appium tests, it works fine, WDA does not get stuck.
However, when I install the app at runtime (by passing *.app path to app desired capability) then I face the above mentioned problem. Looks like there is a problem with App signing using Xcode 8.

**Comment by qakapil** [comment]
Issue was with my Xcode code signing. Closing this bug.

**Comment by skuttyihr** [comment]
How did we resolve this and set up XCode signing?
