### ISSUE TITLE
java.lang.NullPointerException on waiting an element to be displayed

### ISSUE THREAD

**Issue by jeangb** [appium/appium#6987]
## The problem

Hello,
When I try to wait until an element is displayed on my native application, I got a java.lang.NullPointerException.
It's strange because it happens after I sucessfully handled elements before.

## Environment

* Appium v1.4.16
* Windows 7 64bits
* I use appium.exe
* Android 4.4.2
* Samsung Galaxy S4
* API java client is 4.1.2

## Details

I'm testing the log-in function of an android open-source application.
The application is successfully launched, and appium is able to hit and edit the login and password texfield, then the login button.
Then I want to wait that my main activity is displayed. And that's where I have my NullPointerException error.
Appium doesn't wait a second and failed at this point :
`MobileElement mainMenuBis = (MobileElement) (new WebDriverWait(driver, 10)).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//android.widget.ImageButton")));`
My failure exeception : https://gist.github.com/jeangb/1c523708f0c91dac026a4616c07772b0
The appium server logs : 
https://gist.github.com/jeangb/7d628731c752facc1c829eca55d9ff55

Note that if I use a thread.sleep(5000) or I wait that the element is displayed with the eclipse debugger, it will not fail. I don't want to use a thread.sleep.

My driver:
`public static AppiumDriver driver;`

It's instanciate in my setUp function like this:
```
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("deviceName","<redacted>");
		capabilities.setCapability("platformName","Android");
		capabilities.setCapability("platformVersion", "4.4.2");

		capabilities.setCapability("appPackage", "im.vector.alpha");
		capabilities.setCapability("appActivity", "im.vector.activity.LoginActivity");

		setDriver(new AndroidDriver<WebElement>(new URL(Constant.Server_Adress),capabilities));
```
Does anyone knows why it doesn't wait ?

**Comment by imurchie** [comment]
This seems like a Java client problem. You can check the [discussion board](https://discuss.appium.io/) or create an issue on the [Java client](https://github.com/appium/java-client/issues)
