### ISSUE TITLE
appium 1.6 server cannot find pids

### ISSUE THREAD

**Issue by lsecond** [appium/appium#6988]
## The problem

I try to upgrade from appium 1.53 to 1.6 by use "npm install -g appium", which was succeeded. 
however when we run test against android, test failed with Error: Unable to get pids for tomator2.server. Orginial error: this.shell(...).trim is not a function

## Environment

* Appium version 1.6.
* Last Appium version that did not exhibit the issue (if applicable): 1.53
* Desktop OS/version used to run Appium: mac OS X EI Capitan
* Node.js version (unless using Appium.app|exe):v6.7.0
* Mobile platform/version under test:android 5.0/4.4/6.0
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:CLI

## Details

test log:

## Link to Appium logs

https://gist.github.com/lsecond/fee3b23204d47292c6f78b1b886182ab

## Code To Reproduce Issue [ Good To Have ]

capabilities setup:

	DesiredCapabilities capabilities = new DesiredCapabilities();
			capabilities.setCapability("deviceName", "Android");
			capabilities.setCapability("platformVersion", "4.4");
			capabilities.setCapability("app", app.getAbsolutePath());
			capabilities.setCapability("automationName", "UIAutomator2");

			driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),
					capabilities);

**Comment by JaniJegoroff** [comment]
This issue is duplicate to https://github.com/appium/appium/issues/6978
