### ISSUE TITLE
Github username needed when running bootstrap script

### ISSUE THREAD

**Issue by momojah** [appium/appium#6993]
When running the bootstrap script as shown below I am asked for my github username. Nothing happens when I enter my github username. I have installed Appium 1.6.0 and Xcode 8.

XXX:WebDriverAgent YYY$ ./Scripts/bootstrap.sh
Fetching dependencies
Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com':

I also tried with:

./Scripts/bootstrap.sh -d
./Scripts/bootstrap.sh -D

**Comment by mykola-mokhnach** [comment]
Try to execute it with -x option to see debug log:

```bash
bash -x Scripts/bootstrap.sh -d
```

I suppose there might be some issues with carthage setup in your system

**Comment by momojah** [comment]
I am once again asked for my github username (already set globally).
How do I check if my carthage (0.7.1) setup is correct?

Log
+ set -e
+ export PATH=/Users/jhansen/.rvm/gems/ruby-2.2.1/bin:/Users/jhansen/.rvm/gems/ruby-2.2.1@global/bin:/Users/jhansen/.rvm/rubies/ruby-2.2.1/bin:/usr/local/Cellar/android-sdk/24.2/.android/avd:/usr/local/Cellar/android-sdk/24.2/platform-tools:/usr/local/Cellar/android-sdk/24.2/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/apache-ant-1.8.4/bin:/usr/local/share/npm/bin/:/Users/jhansen/.rvm/bin:/usr/local/bin
+ PATH=/Users/jhansen/.rvm/gems/ruby-2.2.1/bin:/Users/jhansen/.rvm/gems/ruby-2.2.1@global/bin:/Users/jhansen/.rvm/rubies/ruby-2.2.1/bin:/usr/local/Cellar/android-sdk/24.2/.android/avd:/usr/local/Cellar/android-sdk/24.2/platform-tools:/usr/local/Cellar/android-sdk/24.2/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/apache-ant-1.8.4/bin:/usr/local/share/npm/bin/:/Users/jhansen/.rvm/bin:/usr/local/bin
+ BOLD='\033[1m'
+ [[ ! -f Scripts/bootstrap.sh ]]
+ getopts ' i d D h ' option
+ case "$option" in
+ FETCH_DEPS=1
+ getopts ' i d D h ' option
+ [[ -n x ]]
+ fetch_and_build_dependencies
+ echo -e '\033[1mFetching dependencies'
Fetching dependencies
+ assert_has_carthage
+ command -v carthage
+ cmp -s Cartfile.resolved Carthage/Cartfile.resolved
+ carthage bootstrap
Username for 'https://github.com': Username for 'https://github.com': Username for 'https://github.com':

**Comment by mykola-mokhnach** [comment]
Probably it's outdated. Mine is v. 0.16.2
Try 

```
brew update
brew upgrade carthage
```

**Comment by momojah** [comment]
Thanks a lot. Seems like more things were broken after updating OSX.

1. $ cd /usr/local  
2. $ git reset --hard  
3. $ git clean -df
4. $ brew update
5. $ brew upgrade carthage
