### ISSUE TITLE
Brosermob proxy tests are broken from appium upgrade to 1.5.3 

### ISSUE THREAD

**Issue by jayantsarda** [appium/appium#6997]
I am adding browsermob proxy as selenium proxy capability. The appium test for android were working fine till i was using 1.4.13 version of appium. After upgrade to 1.5.3 my har file is empty.
## Selenium 2.53.0

Do i need to make any changes to capabilities to fix this?

**Comment by jlipps** [comment]
It's possible. 1.5 was a complete rewrite of Appium so you should expect things to work differently from 1.4. We'll need more details about what's not working specifically though.

**Comment by jayantsarda** [comment]
oops my bad ... it was not working in 1.4 as well  and found couple of posts saying appium ignores proxy capability ... is that still true with 1.5 ?
Thanks
