### ISSUE TITLE
[appium1.6-beta3/java-client 4.1.2/iOS10]        findElementByXpath   on visible attribute 

### ISSUE THREAD

**Issue by bearxc** [appium/appium#6999]
I can not  find a way to  look for   element on  visible attribute with findElementByXpath  .     appium page source shows as   visible="true"  while  WDA shows as "isVisible :1"  , I tried following ways , no luck .

findElementByXpath("//XCUIElementTypeStaticText[@lable='123' and visible='true' ]")

findElementByXpath("//XCUIElementTypeStaticText[@lable='123' and visible= '1' ]")
 
findElementByXpath("//XCUIElementTypeStaticText[@lable='123' and isVisible= '1' ]")

findElementByXpath("//XCUIElementTypeStaticText[@lable='123' and isVisible= 'true' ]")

**Comment by jlipps** [comment]
Isn't `visible` an attribute? Doesn't that mean you'd need to write it as `@visible`?

**Comment by bearxc** [comment]
typo on my comments  , I tried following commands , none works .


findElementByXpath("//XCUIElementTypeStaticText[@lable='123' and @visible='true' ]")

findElementByXpath("//XCUIElementTypeStaticText[@lable='123' and @visible= '1' ]")

findElementByXpath("//XCUIElementTypeStaticText[@lable='123' and @isVisible= '1' ]")

findElementByXpath("//XCUIElementTypeStaticText[@lable='123' and @isVisible= 'true' ]")

**Comment by jlipps** [comment]
What is the xml output of page source?

**Comment by bearxc** [comment]
<XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/0/1/0/0/1/3" x="0" y="251" width="375" height="44">
                                        <XCUIElementTypeStaticText name="123" label="123" value="123" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/0/1/0/0/1/3/0" x="15" y="263" width="40" height="21">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeStaticText name="12:00 AM" label="12:00 AM" value="12:00 AM" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/0/1/0/0/1/3/1" x="287" y="263" width="73" height="21">
                                        </XCUIElementTypeStaticText>
                                    </XCUIElementTypeCell>

**Comment by bearxc** [comment]
<XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/0/1/0/0/1/3" x="0" y="251" width="375" height="44">
                                        <XCUIElementTypeStaticText name="123" label="123" value="123" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/0/1/0/0/1/3/0" x="15" y="263" width="40" height="21">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeStaticText name="12:00 AM" label="12:00 AM" value="12:00 AM" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/0/1/0/0/1/3/1" x="287" y="263" width="73" height="21">
                                        </XCUIElementTypeStaticText>
                                    </XCUIElementTypeCell>
