### ISSUE TITLE
Hint Attribute text missing in XCUITest driver with appium 1.6 release.

### ISSUE THREAD

**Issue by kyle-silk** [appium/appium#7000]
## The problem

Some of the attributes particularly hints do not show up in the XML file when using driver.pagesource() in java. This was not an issue in previous releases.  

## Environment

* Appium version : 1.6
* Last Appium version that did not exhibit the issue : >1.5.X
* Desktop OS/version used to run Appium: MAC OS
* Node.js version (unless using Appium.app|exe):  6.7.0
* Mobile platform/version under test: IOS Xcode8
* Real device or emulator/simulator: Simulator 
* Appium CLI or Appium.app|exe: CLI
* Driver: XCUITest driver, java bindings.

## Details

All hint Attributes are missing in the pagesource, including ones from apple elements.

## Link to Appium logs
Here is the Gist log.
<script src="https://gist.github.com/anonymous/f9eb4ae949cab669f0e011e90eada028.js"></script>

## Code To Reproduce Issue [ Good To Have ]

No need to post code, just do pagesource with an app that has hints...pretty sure ios alone has some on the nav bar... but regardless you will see the hint attribute being empty for all elements.

**Comment by imurchie** [comment]
Apple no longer gives access to those. See https://github.com/appium/appium-xcuitest-driver/issues/216

**Comment by kyle-silk** [comment]
thanks for the quick reply, that is very unfortunate
