### ISSUE TITLE
[appium1.6-beta3/java-client 4.1.2/iOS10]        findElementByXpath   on visible attribute 

### ISSUE THREAD

**Issue by bearxc** [appium/appium#7001]
I can not find element  based on  visible attribute  through  findElementByXpath .     appium page source shows as "visible='true'"   while WDA shows as "isVisible:1"  . I tried following ways , none works.

//XCUIElementTypeStaticText[@visible='1' and @label='123']"

//XCUIElementTypeStaticText[@visible='true' and @label='123']"

//XCUIElementTypeStaticText[@isVisible=1 and @label='123']"

//XCUIElementTypeStaticText[@isVisible='true' and @label='123']"

It only works when remove visible checking , such as 
//XCUIElementTypeStaticText[@label='123']"

Here is example of page source .

<XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/0/1/0/0/1/3" x="0" y="251" width="375" height="44">
                                        <XCUIElementTypeStaticText name="123" label="123" value="123" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/0/1/0/0/1/3/0" x="15" y="263" width="40" height="21">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeStaticText name="12:00 AM" label="12:00 AM" value="12:00 AM" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/0/1/0/0/1/3/1" x="287" y="263" width="73" height="21">
                                        </XCUIElementTypeStaticText>
                                    </XCUIElementTypeCell>

**Comment by bearxc** [comment]
` <XCUIElementTypeStaticText name="123" label="123" `value="123"` dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/0/1/0/0/1/3/0" x="15" y="263" width="40" height="21"> </XCUIElementTypeStaticText>`

**Comment by jlipps** [comment]
Odd, I wonder if this is a bug in WDA. @imurchie have you seen this before?

**Comment by mykola-mokhnach** [comment]
This not gonna work until this PR is merged to WDA: https://github.com/facebook/WebDriverAgent/pull/308
For now the tree, which is generated by WDA for xpath lookup, does not include visibility and accessibility attributes.

**Comment by SrinivasanTarget** [comment]
@triager please close
