### ISSUE TITLE
Scripts/bootstrap.sh -d is not fetching any dependencies

### ISSUE THREAD

**Issue by vutukuriswathi** [appium/appium#7003]
When I ran the below command it is not fetching any dependencies and I am not getting any error.Can some one help me what I did wrong.
Scripts/bootstrap.sh -d
## Environment

appium 1.6 beta3
ios real device : 10.0.2

**Comment by zarkonan** [comment]
I think you are asking for help on wrong place as this is for issues not user help board.

**Comment by vishwathma** [comment]
@vutukuriswathi, even I had the same experience. But I just wanted to check with you, what is the reason you are running bootstrap.sh -d ?

**Comment by imurchie** [comment]
I agree that there should be no reason to run this script manually. Appium does it if necessary.

That being said, the script will only fetch the dependencies if it is necessary. The first time run it should do something like:

```
$ ./Scripts/bootstrap.sh -d
Fetching dependencies
*** Downloading KissXML.framework binary at "5.0.5"
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
*** Downloading peertalk.framework binary at "v1.0"
*** xcodebuild output can be found in /var/folders/1l/3rb7r9kd00x7wsf72472ylnc0000gn/T/carthage-xcodebuild.cz0I4z.log
$
```

If run again it will just do:

```
$ ./Scripts/bootstrap.sh -d
Fetching dependencies
$
```

**Comment by SrinivasanTarget** [comment]
@triager please close
