### ISSUE TITLE
How to launch appium web inspector with appium 1.6 beta as there is no appium.app dmg file

### ISSUE THREAD

**Issue by vutukuriswathi** [appium/appium#7004]
How to launch appium web inspector with appium 1.6 beta as there is no appium.app dmg file

**Comment by SubinLee** [comment]
I wonder.

**Comment by zarkonan** [comment]
lunch it using web browser

**Comment by vutukuriswathi** [comment]
can you please redirect me to the doucmentation link.

**Comment by momojah** [comment]
https://github.com/facebook/webdriveragent

**Comment by wjl025** [comment]
I get http://172.19.31.236:8100/inspector
but result is 
![image](https://cloud.githubusercontent.com/assets/22388210/19591183/48202c98-97a8-11e6-91b3-3d7acfa73a5e.png)

**Comment by mgmanikandan87** [comment]
Hi all,

Currently, appium 1.6 is not available in GUI to inspect the elements, but there is workaround you can get the elements. 

Try this :

https://www.youtube.com/watch?v=4BgkVp0v3BM

This video might help you guys

**Comment by mykola-mokhnach** [comment]
@vutukuriswathi You can also try this inspector implementation: https://github.com/mykola-mokhnach/Appium-iOS-Inspector

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by kcinman11358** [comment]
you can follow this persons guide
https://medium.com/@chenchaoyi/the-options-of-inspecting-ios-10-app-with-appium-1-6-534ba166b958#.1kq3lhnc2
