### ISSUE TITLE
Error: Removing app

### ISSUE THREAD

**Issue by FrancoLiuDev** [appium/appium#7005]
[MJSONWP] Encountered internal error running command: Error: Removing com.leediancn.AppiumTestProjectX failed
## Environment
- Appium version: 1.5.3
- Desktop OS/version used to run Appium: macOS Sierra 10.12
  - Mobile platform/version under test:  iPod 10.0
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe:Appium.app

Details :

My ipa is generated by itunes

 Link to Appium logs:

https://gist.github.com/FrancoLiuDev/04e8f1839f796265b576f3be36061487
## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by mykola-mokhnach** [comment]
Probably, you need to update the idevicelibrary package.
But first try to uninstall the app from the device manually using idevceinstaller:

```
ideviceinstaller --U <bundle_id> -u <device_uuid> --debug
```

and check the output.
