### ISSUE TITLE
android UiAutomator2 error

### ISSUE THREAD

**Issue by wjl025** [appium/appium#7006]
## The problem

see log
## Environment
- Appium version (or git revision) that exhibits the issue:1.6.0
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: 10.11.6
- Node.js version (unless using Appium.app|exe):6.6.0
- Mobile platform/version under test:android 6.0
- Real device or emulator/simulator:Real device
- Appium CLI or Appium.app|exe:CLI
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

https://gist.github.com/wjl025/a7c4c3538e06d3f4ed53120b6198578a
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by sravanmedarapu** [comment]
Can you provide adb logs ?

**Comment by wjl025** [comment]
where is adb logs?
android 6.0 is work,this is android 5.02,yet not support 
I see https://github.com/appium/appium-uiautomator2-server/wiki,Prerequisites: This module should support for Android 5.0 to run on API Level 20.

**Comment by sravanmedarapu** [comment]
use `adb logcat` command to capture the logcat, and always preferable to clear the existing logs using `adb logcat -c` before starting the server.


for storing logs in to a file use `adb logcat > ui2_logcat.txt`

**Comment by SrinivasanTarget** [comment]
@triager please close
