### ISSUE TITLE
Warring : Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version.

### ISSUE THREAD

**Issue by subaKumaran3** [appium/appium#7008]
When i start the Appium server i got this message and my test case got fail, is there any pbm with my Appium server?

My code is :
           DesiredCapabilities capabilities = new DesiredCapabilities(); 
        capabilities.setCapability("BROWSER_NAME", "Android"); 
        capabilities.setCapability("VERSION", "7.0"); System.out.println("2");
        capabilities.setCapability("deviceName","emulator-5554"); 
        capabilities.setCapability("platformName","Android");  
        capabilities.setCapability("appPackage", "com.android.calculator2"); 
        capabilities.setCapability("appActivity","com.android.calculator2.Calculator"); 
            driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities); 

Appium

> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --platform-name Android --platform-version 17 --automation-name Appium --device-name "emulator-5554" --log-no-color
> warn: Appium support for versions of node < 0.12 has been deprecated and will be removed in a future version. Please upgrade!
> info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"address":"127.0.0.1","logNoColors":true,"deviceName":"emulator-5554","platformName":"Android","platformVersion":"17","automationName":"Appium"}
> info: Console LogLevel: debug

error message is :
A new session could not be created. (Original error: Command failed: Failed to install C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk: Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install io.appium.settings without first uninstalling.]
) (WARNING: The server did not provide any stacktrace information)

How can i solve this problem?

**Comment by imurchie** [comment]
The node warning should not be a problem. 

The other is odd. Can you manually delete the appium settings app from the device and see if the error persists?
