### ISSUE TITLE
XCUITest Element could not be found error

### ISSUE THREAD

**Issue by tolgatanriverdi** [appium/appium#7009]
Hi

Before XCUITest (Before IOS 10)
I was using below method to find a UI Element in IOS application:

```
   private void executeIOSAction(IOSObjects mtosElement, ActionType actionType) throws CrashException, ActionNotPossibleException 
  {
      WebElement webElement = null;
      try {
         if (actionType == ActionType.CLICK) { // For finding clickable objects
            if (mtosElement instanceof XCUIElementTypeButton) { 
               // this.turnWifiStatus(true);
               logger.info("Clicking Button:" + mtosElement.getName() + " WithXPath:" + mtosElement.getPathStr());
               XCUIElementTypeButton buttonElement = (XCUIElementTypeButton) mtosElement;
               webElement = driver.findElement(By.xpath(buttonElement.getPathStr()));
               if (webElement != null) {
                  webElement.click();
                  buttonElement.setIsClicked();
             }
    }
```

But after changing implementation to XCUITest it gives the below error. Does anyone know how can I fix that?

```
2016-10-13 13:46:55,318 ERROR:  Web Driver Exception:An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 546 milliseconds

Path That I'm Searching: //XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeButton[1]
```

And this is the driver.getPageSource() output of the current Screen:

https://drive.google.com/file/d/0B3eSt3_PT8YXakQwRC1ZOHFDT2c/view?usp=sharing

Thanks

**Comment by dmydry** [comment]
Hello! I just started to test a chain appium 1.6 with ios 10 test (I had working tests with appium 1.5 and ios 9.3). I've got an issue that appium can't interact with elements in a tree with XCUIElementTypeOther. It can't find an element using xpath or accessibility id or click on it.

**Comment by srkannan** [comment]
I'm getting the same issue:
[XCUITest] Rewrote incoming selector from '//UIAApplication[1]/UIAWindow[1]/UIATextField[1]' to '//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeTextField[1]' to match XCUI type. You should consider updating your tests to use the new selectors directly

How does one find the new elements with out the Inspector tool which is not available in 1.6.0-beta3 ?

**Comment by jlipps** [comment]
@srkannan for the time being, use the page source command

**Comment by SonaliBurghate** [comment]
@jlipps  I am unable to locate element appears on a video , though it has Accessibility ID , Label and Type provided. Please help.

**Comment by mayukataoka** [comment]
Noticed the same problem myself, also.

**Comment by mykola-mokhnach** [comment]
The UI tree generated by XCTest is different from the one generated by instruments. So don't expect same paths or class names to work for both frameworks. Most of the times it is necessary to update locators according to the actual tree. 
Regarding inspector - the "native" one is currently being developed. Although you can try some [alternatives](https://medium.com/@chenchaoyi/the-options-of-inspecting-ios-10-app-with-appium-1-6-534ba166b958).
