### ISSUE TITLE
Add new touch ID endpoint to clients for iOS

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7013]
With XCUITest's new touchID endpoints, we need to release new versions of Appium clients that support them. This is an issue to track that progress:
- [x] Python (https://github.com/appium/python-client)
- [x] Ruby (appium_lib) (https://github.com/appium/ruby_lib) (Done already)
- [ ] Java (https://github.com/appium/java-client)
- [x] .NET  (https://github.com/appium/appium-dotnet-driver)
- [x] PHP(https://github.com/appium/php-client)
- [x] WD (https://github.com/admc/wd)
- [x] webdriver.io (@christian-bromann maybe you can take this one?)

**Comment by christian-bromann** [comment]
> webdriver.io (@christian-bromann maybe you can take this one?)

on it

**Comment by wenshi11019** [comment]
I choose java
