### ISSUE TITLE
update appium-1.5.3 to 1.6.0

### ISSUE THREAD

**Issue by johnChnia** [appium/appium#7016]
## The problem

i had install appium-1.5.3，today i update it to 1.6.0，then hava  a  wrong.
## Environment
- Appium version (or git revision) that exhibits the issue: from 1.5.3 to 1.6.0
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3
- Desktop OS: mac os 10.11.5 
## Details

```
 john@ios  ~/Desktop  cnpm install -g appium
[babel-core@5.8.24](/usr/local/lib/node_modules/.appium_npminstall/node_modules/.0.1.10@appium-fake-driver/node_modules/babel-core) deprecate: Babel 5 is no longer being maintained. Upgrade to Babel 6.
[minimatch@2.0.10](/usr/local/lib/node_modules/.appium_npminstall/node_modules/.5.8.24@babel-core/node_modules/minimatch) deprecate: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[line-numbers@0.2.0](/usr/local/lib/node_modules/.appium_npminstall/node_modules/.5.8.24@babel-core/node_modules/line-numbers) deprecate: Copy its ~20 LOC directly into your code instead.
[fsevents@1.0.14] download from binary mirror: {"module_name":"fse","module_path":"./lib/binding/{configuration}/{node_abi}-{platform}-{arch}/","remote_path":"./v{version}/","package_name":"{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz","host":"https://npm.taobao.org/mirrors/fsevents"}
[appium@1.6.0] link /usr/local/bin/appium@ -> ../lib/node_modules/.appium_npminstall/node_modules/.1.6.0@appium/build/lib/main.js
[appium@*] installed at node_modules/.appium_npminstall/node_modules/.1.6.0@appium (422 packages, use 13s, speed 283.52kB/s, json 3.68MB, tarball 0B)
execute post install scripts...
[appium-chromedriver@2.9.2] scripts.install: "node install-npm.js" at /usr/local/lib/node_modules/.appium_npminstall/node_modules/.2.9.2@appium-chromedriver
info Chromedriver Install Installing Chromedriver version '2.21' for platform 'mac' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_mac32 to...
info Chromedriver Install Downloading http://tnpm-hz.oss-cn-hangzhou.aliyuncs.com/dist/chromedriver/2.21/chromedriver_mac32.zip...
info Chromedriver Install Writing binary content to /var/folders/jt/k2c4bmp13sz8yfks0rj6_h4r0000gn/T/2016914-10536-1spt0xs.bj3151xlxr/chromedriver_mac32.zip...
info Chromedriver Install Extracting /var/folders/jt/k2c4bmp13sz8yfks0rj6_h4r0000gn/T/2016914-10536-1spt0xs.bj3151xlxr/chromedriver_mac32.zip to /var/folders/jt/k2c4bmp13sz8yfks0rj6_h4r0000gn/T/2016914-10536-1spt0xs.bj3151xlxr/chromedriver_mac32
info Chromedriver Install Creating /usr/local/lib/node_modules/.appium_npminstall/node_modules/.2.9.2@appium-chromedriver/chromedriver/mac...
info Chromedriver Install Copying unzipped binary, reading from /var/folders/jt/k2c4bmp13sz8yfks0rj6_h4r0000gn/T/2016914-10536-1spt0xs.bj3151xlxr/chromedriver_mac32/chromedriver...
info Chromedriver Install Writing to /usr/local/lib/node_modules/.appium_npminstall/node_modules/.2.9.2@appium-chromedriver/chromedriver/mac/chromedriver...
info Chromedriver Install /usr/local/lib/node_modules/.appium_npminstall/node_modules/.2.9.2@appium-chromedriver/chromedriver/mac/chromedriver successfully put in place
[appium-chromedriver@2.9.2] scripts.install success, use 8s
[appium-uiautomator2-driver@0.0.4] scripts.install: "node ./bin/install.js" at /usr/local/lib/node_modules/.appium_npminstall/node_modules/.0.0.4@appium-uiautomator2-driver
dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_60
info UiAutomator2 downloading UiAutomator2 Server APKs
UiAutomator2 setup files did not yet exist, waiting...
dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_60
info UiAutomator2 downloading UiAutomator2 Server APKs
UiAutomator2 setup files did not yet exist, waiting...
dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_60
info UiAutomator2 downloading UiAutomator2 Server APKs
UiAutomator2 setup files did not yet exist, waiting...
dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_60
info UiAutomator2 downloading UiAutomator2 Server APKs
UiAutomator2 setup files did not yet exist, waiting...
```
## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
What version of node and npm are you using?

**Comment by johnChnia** [comment]
i am in China

node version: v6.8.1
npm version: 3.10.8

**Comment by imurchie** [comment]
@sravanmedarapu Any ideas about this issue? It seems to be hung on downloading UiAutomator2...

**Comment by ezuluagas** [comment]
@johnChnia , I have the same problem, do you know how can I solve it??

**Comment by sravanmedarapu** [comment]
@ezuluagas, Can you share the log ?

**Comment by ezuluagas** [comment]
@sravanmedarapu it's the same message  info UiAutomator2 downloading UiAutomator2 Server APKs
UiAutomator2 setup files did not yet exist, waiting...

**Comment by sravanmedarapu** [comment]
Can you try with --no-shrinkwrap  and share your findings

npm install -g appium --no-shrinkwrap

**Comment by johnChnia** [comment]
@sravanmedarapu  i will try soon, thank you

**Comment by johnChnia** [comment]
@sravanmedarapu  use this command what you comment above ,  i  install appium1.6.0 success.
Thank you!

logs like:

nfo UiAutomator2 downloading UiAutomator2 Server APK v0.0.4 : https://github.com/appium/appium-uiautomator2-server/releases/download/v0.0.4/appium-uiautomator2-server-v0.0.4.apk
info UiAutomator2 downloading UiAutomator2 Server test APK v0.0.4 : https://github.com/appium/appium-uiautomator2-server/releases/download/v0.0.4/appium-uiautomator2-server-debug-androidTest.apk

scripts.install appium > appium-uiautomator2-driver@0.0.7 finished in 1m
deprecate appium > appium-fake-driver > babel-core@5.8.24 Babel 5 is no longer being maintained. Upgrade to Babel 6.
deprecate appium > appium-fake-driver > babel-core > minimatch@2.0.10 Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
deprecate appium > appium-fake-driver > babel-core > line-numbers@0.2.0 Copy its ~20 LOC directly into your code instead.
All packages installed (417 packages installed from npm registry, use 21m, speed 12.08kB/s, json 889(6.03MB), tarball 8.5MB)
Recently updated since (2016-10-28): 16 packages (detail see file node_modules/.recently_updates.txt)
 today
  - appium > appium-youiengine-driver > appium-android-driver > appium-android-bootstrap@2.7.7 (05:58:49)

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by tangtingting** [comment]
I have the same question, what's the reason for this problem 
install log ：
UiAutomator2 setup files did not yet exist, waiting...
dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.7.0_121
info UiAutomator2 downloading UiAutomator2 Server APK v0.0.8 : https://github.com/appium/appium-uiautomator2-server/releases/download/v0.0.8/appium-uiautomator2-server-v0.0.8.apk
info UiAutomator2 downloading UiAutomator2 Server test APK v0.0.8 : https://github.com/appium/appium-uiautomator2-server/releases/download/v0.0.8/appium-uiautomator2-server-debug-androidTest.apk
