### ISSUE TITLE
[MacOS Sierra and Xcode 7.3.1] Can we run iOS tests on this configuration? 

### ISSUE THREAD

**Issue by HlebHalkouski** [appium/appium#7017]
## Cannot create driver

Have error: `Original error: Installing /var/folders/47/p02m27d56xq92rc8mz9lfxth0009rh/T/2016914-8199-dcvgu7.7o91ejnhfr/Payload/App.app failed`.

And when I'm trying to launch application using Intruments->Automation, error appear: 

![image](https://cloud.githubusercontent.com/assets/11422447/19383804/e72697e0-920e-11e6-92a8-803b14eace50.png)
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0 
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3
- Desktop OS/version used to run Appium: MacOS Sierra (10.12)
- Mobile platform/version under test: iOS
- Real device or emulator/simulator: real device

**Comment by imurchie** [comment]
I have not gotten access to a machine running macOS, so I have not been able to verify that anything works on it. Your guess, at this point, is as good as mine.

**Comment by saikrishna321** [comment]
@HlebHalkouski @imurchie i tested appium 1.6 on macOS Sierra and works fine on both iOS 10 and iOS 9.3

**Comment by imurchie** [comment]
Awesome! Any idea about the above error?

**Comment by HlebHalkouski** [comment]
@saikrishna321 did you use xcode 7 with uiautomation(automationName=Appium)?

**Comment by saikrishna321** [comment]
@imurchie error does not say anything that i could understand ... @HlebHalkouski i used xcode 8 and iPhone 6 running iOS10, appium-1.6v picks automationName as XCUITest if it's xcode 8.

Can you please provide some steps when u encountered this error ?

**Comment by HlebHalkouski** [comment]
@saikrishna321 I'm used MacOS Sierra, xcode 7.3.1, ipad 4 ios 9.3.2 and automationName was Appium(default).

**Comment by saikrishna321** [comment]
> And main question, I think, is: can we use xcode 7 with uiautomation on MacOs Sierra

i think it should not be a problem, not sure though ... @SrinivasanTarget any thoughts ?

**Comment by SrinivasanTarget** [comment]
I think ```ideviceinstaller``` will be the only problem.

**Comment by HlebHalkouski** [comment]
@saikrishna321 @SrinivasanTarget I found [solution](https://github.com/libimobiledevice/ideviceinstaller/issues/47) for issue with `ideviceinstaller` and  MacOs Sierra: 

- update the permissions in /var/db/lockdown folder. 
`sudo chmod -R 777 /var/db/lockdown`
And then ideviceinstaller will work with MacOs Sierra and xCode 7.3.1. 

=> Appium@1.5.3 support iOS 9.3 and lower on MacOs Sierra.
