### ISSUE TITLE
Performance degradation between Appium 1.4.13 and 1.6.0

### ISSUE THREAD

**Issue by chrisie** [appium/appium#7020]
## The problem

We recently upgraded from Appium 1.4.13 to Appium 1.6.0. Following this upgrade we saw a huge performance hit in our tests to the point where individual actions (ex. element click) now take approximately 1500ms instead of 50msec which was the case with the previous version.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0
- Last Appium version that did not exhibit the issue (if applicable): 1.4.13 (although we have not tested with the versions in-between 1.4.13 and 1.6.0)
- Desktop OS/version used to run Appium: OSX El Capitan
- Node.js version (unless using Appium.app|exe): 4.6.0
- Mobile platform/version under test: iOS 8.4
- Real device or emulator/simulator: Emulator
- Appium CLI or Appium.app|exe: CLI
## Details

Our automated testing stack consists of Appium, Protractor and Cucumber. We recently upgraded from Appium 1.4.13 to 1.6.0 and found our tests becoming extremely slow. We have tested with a single Cucumber directive, which looks for an element, scrolls to it and clicks it, in order to try and identify the source of the problem, and it seems that every single action is taking around 1500msec instead of around 50msec which was the case with the earlier Appium version.
More specifically, our Cucumber directive does the following (code included at the end of the issue):
- Wait for an element to appear in the DOM
- Check if the element is visible
- Scroll to the element
- Click the element

We are logging the time needed for each action to be performed and we are seeing the following times between Appium 1.4.13 and 1.6.0
- Wait for element 78 msec with 1.4.13 vs 1542 msec with 1.6.0
- Check if visible 40 msec with 1.4.13 vs 1552 msec with 1.6.0
- Scroll 11 msec with 1.4.13 vs 515 msec with 1.6.0
- Click 57 msec with 1.4.13 vs 1551 msec with 1.6.0

We have repeated our tests several times, and each time the results are similar. Unfortunately due to this delay we practically cannot run our tests, since they now need several hours to run instead of a few minutes, and since we need Appium 1.6.0 to support XCode 8 we are pretty much blocked. 
Please note that these results are with XCode 7 (since we needed to be able to compare the two Appium versions) but we are seeing a similar delay with XCode 8 (using iOS 10.0 and the XCUITest automation) as well. 
## Link to Appium logs
- [Appium 1.4.13 log](https://gist.github.com/chrisie/8a74b1b575412ad4b784d8b641254ee0)
- [Appium 1.6.0 log](https://gist.github.com/chrisie/8e5880a6968388b3953a85beb20e91e9)
## Code To Reproduce Issue [ Good To Have ]

The test Cucumber directive we are using:

```
this.When(/^I click "(.*)"$/, function(field, next) {
      var startTime = new Date().getTime();
       console.log(new Date());
      var scrollToScript = 'document.querySelector("' + selector.css(field)+ '").scrollIntoView();';
      this.helpers.waitUntilElementIsInDom(field, function (theElement) {
          var time1 = new Date().getTime() - startTime;
          console.log(time1);
          theElement.isDisplayed().then(function (isDisplayed) {
              var time2 = new Date().getTime() - startTime - time1;
              console.log(time2);
              browser.driver.executeScript(scrollToScript).then(function() {
                  var time3 = new Date().getTime() - startTime - time1 - time2;
                  console.log(time3);
                  theElement.click().then(function () {
                       var time4 = new Date().getTime() - startTime - time1 - time2 - time3;
                       console.log(time4);
                       next(); 
                  });
              });
          });
      });
  });
```

**Comment by amedvedjev** [comment]
have the same. our test suite time got increased from 1h to 1,5h.
the only really nice fast is wheel "setValue" .

**Comment by iquicktest** [comment]
same.

**Comment by jlipps** [comment]
Which iOS version were you testing on 1.4.13? And which on 1.6?

**Comment by chrisie** [comment]
iOS 8.4 in both (in order to get comparable results) but we've also tried Appium 1.6 with iOS 10 and the results are similar.

**Comment by kkhaidukov** [comment]
@jlipps I'm having the same issue (appium 1.6.0 + iOS 10), and instruments without delay that you mentioned doesn't seem to help here

**Comment by VasilijSviridov** [comment]
Xcode 8.1, iOS 10.1(real device)+ appium 1.6 - instead of 50sec we now have 5mins.

**Comment by chrisie** [comment]
@jlipps We also saw no difference with instruments without delay either. Anything else we can try? This is becoming a real blocker for us.

**Comment by jlipps** [comment]
@chrisie if you're running both appium versions with the same xcode/ios version (note it needs to be the same xcode version, not just the same ios version; xcode version is more significant for how appium runs than ios version), the next step would be to add the `--log-timestamp` server flag and compare the appium log output from the two appium versions and see if there is any obvious place where one is taking longer than the other.

**Comment by chrisie** [comment]
@jlipps Yes, I'm testing with the same XCode version I tried the --log-timestamp option (with XCode 7) and it seems (to me at least) that for some reason there is a big delay after the click and before the response is sent back to the client. The relevant fragments are

For Appium 1.4.13:
```
2016-11-08 09:43:47:715 - info: --> POST /wd/hub/session/3e427cd6-09cc-40ec-9414-ea72ff1a2510/element/5001/click {}
2016-11-08 09:43:47:717 - info: [debug] [REMOTE] Executing 'click' atom in default context
2016-11-08 09:43:47:717 - info: [debug] [REMOTE] Sending javascript command
2016-11-08 09:43:47:718 - info: [debug] [REMOTE] Sending _rpc_forwardSocketData: message to remote debugger
2016-11-08 09:43:47:750 - info: [debug] [REMOTE] Receiving data from remote debugger
2016-11-08 09:43:47:751 - info: [debug] [REMOTE] Receiving data from remote debugger
2016-11-08 09:43:47:751 - info: [debug] [REMOTE] got applicationSentData response
2016-11-08 09:43:47:751 - info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"3e427cd6-09cc-40ec-9414-ea72ff1a2510"}
2016-11-08 09:43:47:752 - info: <-- POST /wd/hub/session/3e427cd6-09cc-40ec-9414-ea72ff1a2510/element/5001/click 200 36.692 ms - 76 {"status":0,"value":null,"sessionId":"3e427cd6-09cc-40ec-9414-ea72ff1a2510"}
```

And for Appium 1.6.0
```
2016-11-08 09:39:19:817 - [HTTP] --> POST /wd/hub/session/636a927b-dc81-420c-afeb-f5d006cb3e57/element/5002/click {}
2016-11-08 09:39:19:817 - [MJSONWP] Calling AppiumDriver.click() with args: ["5002","636a927b-dc81-420c...
2016-11-08 09:39:19:817 - [debug] [iOS] Executing iOS command 'click'
2016-11-08 09:39:19:819 - [debug] [RemoteDebugger] Executing 'click' atom in default context
2016-11-08 09:39:19:819 - [debug] [RemoteDebugger] Sending javascript command (function(){return function...
2016-11-08 09:39:19:820 - [debug] [RemoteDebugger] Sending '_rpc_forwardSocketData:' message to remote debugger
2016-11-08 09:39:19:852 - [debug] [RemoteDebugger] Received applicationSentData response
2016-11-08 09:39:19:852 - [debug] [RemoteDebugger] Found data handler for response
2016-11-08 09:39:19:852 - [debug] [RemoteDebugger] Received data response from socket send: '{"status":0,"value":null}'
2016-11-08 09:39:19:852 - [debug] [RemoteDebugger] Original command: sendJSCommand
2016-11-08 09:39:19:853 - [debug] [RemoteDebugger] Received result for atom 'click' execution: null
2016-11-08 09:39:19:967 - [debug] [RemoteDebugger] Received applicationSentData response
2016-11-08 09:39:20:326 - [MJSONWP] Responding to client with driver.click() result: null
2016-11-08 09:39:20:326 - [HTTP] <-- POST /wd/hub/session/636a927b-dc81-420c-afeb-f5d006cb3e57/element/5002/click 200 510 ms - 76
```

Although the actual click seems to be happening in pretty much the same time in both cases (around 40msec) I see a big delay in Appium 1.6.0 to receive the applicationSentData response and respond to the client (around 500msec). Not sure what this means and how it could be fixed but I'm hoping you have some more insight on this :)

The full logs are available here:

- [Appium 1.4.13](https://gist.github.com/chrisie/08f0b5a770596cfc8d79e38ae3fa7274)
- [Appium 1.6.0](https://gist.github.com/chrisie/d544aae4e14d39563cc82e8ae5cd54fc)

**Comment by jlipps** [comment]
@imurchie this is interesting. If it is indeed the exact same version of iOS and the exact same version of Xcode, it could be a sign of a performance degradation in our remote debugger code.

**Comment by VasilijSviridov** [comment]
any update on this ?

**Comment by pmegremis** [comment]
Does Appium 1.6.2 contain fix for performance issue that is described in this ticket?

**Comment by jlipps** [comment]
@imurchie any more thoughts about whether remote debugger changes could be contributing to this?

**Comment by jlipps** [comment]
Acceptance criteria:
* [ ] investigate remote debugger and determine cause of increased latency
* [ ] fix for increased latency

**Comment by pmegremis** [comment]
Any update on this issue?

**Comment by chrisie** [comment]
@jlipps @imurchie Any news on this?

**Comment by VasilijSviridov** [comment]
it seem that performance issue is seen only on hybrid apps( using webview), might be helpful for fixing issue with performance.

**Comment by chrisie** [comment]
@jlipps @imurchie Since this is a very important issue for us we are also doing investigation on our end to see if we can figure out what the problem is and contribute back a solution. Are there any pointers you could give us on what we might be looking for and where?

**Comment by VasilijSviridov** [comment]
@chrisie  I started using WDA(facebook) without appium and it seems fixes problems.

**Comment by chrisie** [comment]
@VasilijSviridov This sounds very interesting, could you tell me a few more details when you get a chance? I guess you have completely replaced Appium with WDA? Have you seen any issues so far (unsupported commands, etc.)? What does the rest of your test stack look like?

**Comment by yaphatak** [comment]
This is fixed in https://github.com/appium/appium-xcuitest-driver/commit/a0488d34d9f4743c41284c3504e209a3065b118f

**Comment by chrisie** [comment]
@yaphatak Thanks a lot! I upgraded to appium-xcuitest-driver 2.15.0 and the performance problem went away :) For some reason I couldn't upgrade to 2.16.0 (the WebDriverAgent was not found) but 2.15.0 does the job.
I'm therefore closing this since a solution exists.

**Comment by edoardoo** [comment]
@chrisie  May I ask you if there's a standard procedure to upgrade?

**Comment by chrisie** [comment]
@edoardoo I guess it depends on how you define "standard". In my case I was using a npm-shrinkwrap.json to avoid loading new versions of node module dependencies before we get a chance to test them so what I did was go into node_modules/appium, `npm install` the version of appium-xcuitest-driver I wanted and regenerate npm-shrinkwrap. I assume if you're not using shrinkwrap you should get the latest version of appium-xcuitest-driverif you uninstall and re-install appium, with the caveat of course the the latest version (2.16.0) wasn't working for me.
