### ISSUE TITLE
Appium 

### ISSUE THREAD

**Issue by GebakerJH** [appium/appium#7021]
## The problem

Appium doesn't find Carthage even though is is installed.  Here are the applicable lines from the log.

[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage not found. Install using `brew install carthage`
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[debug] [XCUITest] Creating WebDriverAgent resources directory
[debug] [XCUITest] Creating WebDriverAgent resource bundle directory

The output of the which statement from the command line produces:
/usr/local/bin/carthage

Due to restrictions on the system Carthage was installed using the package from the Carthage website rather than brew.
https://github.com/Carthage/Carthage/releases

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.11
* Last Appium version that did not exhibit the issue (if applicable): N/A first version I tested with carthage dependency.
* Desktop OS/version used to run Appium: Max OS X 10.11.16
* Node.js version (unless using Appium.app|exe): 6.8.0
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Simualtor
* Appium CLI or Appium.app|exe: Appium as service.  Started with LaunchAgent Plist used through Jenkins.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
        <dict>
        <key>KeepAlive</key>
        <dict>
                <key>SuccessfulExit</key>
                <false />
        </dict>
        <key>Label</key>
        <string>com.jha.appium</string>
        <key>EnvironmentVariables</key>
                 <dict>
                        <key>ANDROID_HOME</key>
                        <string>/Users/Jenkins/android-sdk-macosx</string>
                        <key>JAVA_HOME</key>
                        <string>/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home</string>
                </dict>
        <key>ProgramArguments</key>
        <array>
                <string>/Users/jenkins/opt/bin/node</string>
                <string>/Users/jenkins/appium/</string>
                <string>--default-device</string>
        </array>
        <key>debug</key>
                <true />
        <key>RunAtLoad</key>
                <true />
        <key>WorkingDirectory</key>
                <string>/Users/jenkins/appium</string>
        <key>StandardOutPath</key>
                <string>/Users/jenkins/appium/appium.log</string>
        <key>StandardErrorPath</key>
                <string>/Users/jenkins/appium/error.log</string>
        </dict>
</plist>

## Details

Does attempt to run a script on the device but unsure if successful because have not ported scripts from instruments to XCUITest yet.  

## Link to Appium logs

Additional logging can be provided if necessary.  Unable to post at this time due to possible company restrictions.

**Comment by imurchie** [comment]
That should be fine. Even if the logs say that Carthage cannot be found.

As long as the dependencies can be downloaded, the system works. You can verify by going into `<appium-root>/node_modules/appium-xcuitest-driver/WebDriverAgent` and running `./Scripts/bootstrap.sh -d`. If it does not fail (it may just say "Fetching dependencies", and exit, which means that it has already done so) then all is well.

**Comment by GebakerJH** [comment]
imurchie - Tried that and was successful.  Got the "Fetching dependencies" message.  Thanks for the quick response.

**Comment by longnguyen2508** [comment]
In my case, cause writeable permission I cannot link to carthage. 

> sudo chown -R $(whoami) /usr/local/share/
then 
> brew link carthage
