### ISSUE TITLE
./js/app.js Error

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#7023]
I am getting the above error when I am trying to install WebDriver Agent Project. I have followed the steps from the this link https://github.com/appium/appium-xcuitest-driver#real-devices 

Appium 1.6
Xcode 8.1 beta
iOS 10.1 Beta 3 

https://gist.github.com/pavanbachu0604/94ad14af5eea350685c0e3f1208841d6

**Comment by imurchie** [comment]
If you look at the instructions, it says to run `./Scripts/bootstrap.sh -d` (note the `-d`).

But this should not be necessary to do at all.
