### ISSUE TITLE
GetPageSource method runs too slow with XCUITest

### ISSUE THREAD

**Issue by tolgatanriverdi** [appium/appium#7029]
Hi

I was using driver.getPageSource() method with UIAutomation and I'm trying to use same method with XCUITest. However appium responds too slow so my java client gets timeout error.And it always shows the below log:

```
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
```

Do you know any other way to get xml output of the current screen's view hierarchy

Thanks

**Comment by mykola-mokhnach** [comment]
This is rather [WDA](https://github.com/facebook/WebDriverAgent/issues/320) issue, since Appium builds XML representation based on information received from /source API call.  For apps containing many UI elements on a single screen it works very slowly.

**Comment by imurchie** [comment]
Those log lines were a bug that should be fixed in the latest version. But the page source issue is a problem with WebDriverAgent.

Can you provide, at the bare minimum, the full logs for the page source call? From when the command comes in to when it is responded to?

**Comment by tolgatanriverdi** [comment]
You can find the logs about getPageSource in below:

```
[debug] [XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [POST /source] to [POST http://localhost:8100/session/140BBBC6-0C88-4662-82D1-29E7F0D196A3/source] with no body
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"...
[MJSONWP] Responding to client with driver.getPageSource() result: "<?xml version=\"1.0\" enco...
[HTTP] <-- GET /wd/hub/session/32c884d8-a47b-45cd-9e10-32222071d3ae/source 200 275 ms - 11674 
```

**Comment by imurchie** [comment]
Ok. That is just the speed of the upstream system, and ultimately the tools that Apple provides. Unfortunately.
