### ISSUE TITLE
Documentation on tap method

### ISSUE THREAD

**Issue by jkoorts** [appium/appium#7030]
## The problem

The doc says this about tap "@param duration how long between pressing down, and lifting fingers/appendages". The problem is it does not state the measure of duration. Is it seconds, minutes, etc?
## Environment

Any
## Details

Documentation is vague
## Link to Appium logs

None needed
## Code To Reproduce Issue [ Good To Have ]

None needed

**Comment by imurchie** [comment]
Can you point us to the documentation of which you speak?

**Comment by jkoorts** [comment]
http://appium.github.io/java-client/io/appium/java_client/TouchShortcuts.html#tap(int, int, int, int)

**Comment by SrinivasanTarget** [comment]
@jkoorts Will fix it. Thanks.

**Comment by SrinivasanTarget** [comment]
@triager please label: Bug

**Comment by SrinivasanTarget** [comment]
Fixed already in client
