### ISSUE TITLE
Not possible to inspect the app

### ISSUE THREAD

**Issue by momojah** [appium/appium#7033]
## The problem

I'm writing scripts in Ruby and cannot inspect the app.
1. ARC is no longer maintained
2. Inspector is no longer available without Instruments

## Environment

* Appium version 1.6.0
* XCUITest
* Simulator, Iphone 7, iOS 10

**Comment by imurchie** [comment]
Try getting the page source to see what is available.

**Comment by momojah** [comment]
@imurchie : I used to do that with ARC. How is it otherwise done?

**Comment by imurchie** [comment]
I dont know what ARC is. But whatever client you choose to use will have a method to get the page source.

**Comment by momojah** [comment]
@imurchie : ARC is Appium Ruby Console. For the ruby bindings it is the ARC approach which is mentioned everywhere. I don't know how to proceed. Can you help in any way?

**Comment by imurchie** [comment]
I don't know Ruby, but it looks like there is a method `get_source`.

**Comment by tapisky** [comment]
@momojah try just with 'source', it works for me (I'm on Ruby). Also, you can get some info with method 'page_class'.

**Comment by momojah** [comment]
@imurchie : thanks.
@tapisky : thanks. both are working for me. How do I specify the page_class? I tried with page_class :XCUIElementTypeButton in Appium Ruby Console but it failed with "ArgumentError: wrong number of arguments (1 for 0)".

**Comment by tapisky** [comment]
@momojah 

The way I find elements is like below:
* with class => find_elements(class: 'XCUIElementTypeButton) (you will get an array with all Buttons)
* with xpath => find_element(xpath: '//XCUIElementTypeButton[@name="My button"]') (you will get the element with the specified attributes)

**Comment by mykola-mokhnach** [comment]
@momojah You can try to use this inspector implementation: https://github.com/mykola-mokhnach/Appium-iOS-Inspector

**Comment by momojah** [comment]
@tapisky & @mykola-mokhnach : WOW! Thanks a lot to both of you. Everything works now. I'm grateful.
