### ISSUE TITLE
java driver pushFile corrputs transfered file

### ISSUE THREAD

**Issue by isbjorn** [appium/appium#7036]
## The problem

```driver.pushFile``` corrputs file when called with instance of ```java.io.File```

### Not works
```
File file = ...
driver.pushFile(devicePath, file); // corrupts file, looks like it base64 encoded twice
```

### Works
```
import org.apache.commons.io.FileUtils;
...
byte[] content = FileUtils.readFileToByteArray(file); // file -> stream -> byte array
driver.pushFile(devicePath, content); // works
```

## Environment

* Appium 1.5.3
* Node.js  v6.3.1
* Android emulator with 5.1.1
* Appium java-client 4.1.2

## Details

Push one file into virtual device, the first time with ```java.io.File```, the second time with ```byte[]```
Grab both files from deviced with ```adb pull ...```
The first file will be broken

**Comment by imurchie** [comment]
This seems like an issue with the Java client. You will get more help by posting the issue there.

https://github.com/appium/java-client/issues

**Comment by isbjorn** [comment]
Thanks, i opened issue https://github.com/appium/java-client/issues/493
