### ISSUE TITLE
Appium crashes when I'm trying to set device to default network settings

### ISSUE THREAD

**Issue by yunusmete** [appium/appium#7037]
## The problem

Hi,

I want to make set device networks settings before to start test. So I'm doing set wifi, data on and airplane mode off and starting of test. This code works on single test but fails when running on parallel test.

If a comment out network settings method, works fine.

Any suggest?
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test: Android 5.1
- Real device or emulator/simulator: Real
- Appium CLI or Appium.app|exe: CLI
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

https://gist.github.com/yunusmete/e368232f3f817b9d704224c6b7c3e99b
## Code To Reproduce Issue [ Good To Have ]

   private void revertToDefaultNetworkSettings() {
      NetworkConnectionSetting networkConnection = driver.getNetworkConnection();
      networkConnection.setAirplaneMode(false);
      networkConnection.setData(true);
      networkConnection.setWifi(true);

```
  driver.setNetworkConnection(networkConnection);
```

   }

**Comment by imurchie** [comment]
Can you provide the _server_ logs? The client logs are of limited use.

**Comment by yunusmete** [comment]
Sure. https://gist.github.com/yunusmete/34d63271ae98355df4db8523003dc937

**Comment by dpgraham** [comment]
Closing this. Will re-open if error is still occurring.
