### ISSUE TITLE
Setting text value on a text_field object in PageObject pattern does not remove initial contents completely (iOS)

### ISSUE THREAD

**Issue by tapisky** [appium/appium#7038]
## The problem

When setting the value of a text field (ie. 'description = "Synergistic Granite Car"', where description is an object of type 'text_field" in PageObject pattern), the previous content of the text field is not totally cleared, in fact, only the text on the first line gets cleared (if the text is long enough to fit in more than one line). I see that the framework tries to remove the actual value of the text edit, and it does it successfully when the text is short and only fits in one line, but when the text fits in more than one line, the text in the other lines is not cleared.

100% reproducible on my environment
## Environment
- Appium version (or git revision) that exhibits the issue: Appium 1.6.0
- Last Appium version that did not exhibit the issue (if applicable): Appium 1.5.3
- Desktop OS/version used to run Appium: MacOS OSX El Capitan
- Node.js version v6.2.0
- Mobile platform/version under test: iOS, OS version 10
- Real device or emulator/simulator: simulator
- Appium CLI or Appium.app|exe: Appium CLI
- iOS Native app
## Details

No more details.
## Link to Appium logs

`[MJSONWP] Calling AppiumDriver.setValue() with args: [["hola que tal"],"4E064617...
[debug] [XCUITest] Executing command 'setValue'
[JSONWP Proxy] Proxying [POST /element/4E064617-21A2-4945-B604-4B9FC720C75C/value] to [POST http://localhost:8100/session/5DDCDCDA-4C99-47C8-A266-4B3DE0E06003/element/4E064617-21A2-4945-B604-4B9FC720C75C/value] with body: {"value":["h","o","l","a","...
[JSONWP Proxy] Got response with status 200: {"status":0,"id":"4E064617-...
[MJSONWP] Responding to client with driver.setValue() result: null
[HTTP] <-- POST /wd/hub/session/f9bd0a7c-2ff4-4710-99f7-538a16462486/element/4E064617-21A2-4945-B604-4B9FC720C75C/value 200 2427 ms - 76`

Looks like the issue is in 'AppiumDriver.setValue()' function, that it only clears the content before the cursor, and not after.

**Comment by mykola-mokhnach** [comment]
Yep, seems like it, but it would be more useful to report this bug directly to [WDA](https://github.com/facebook/WebDriverAgent/issues) issues. As a workaround, you can try to click at the end of the input field first to put the cursor into proper place before setting a new value.

**Comment by dpgraham** [comment]
Closing this as likely WDA bug.
