### ISSUE TITLE
IOS 10.12 not supporting by Appium

### ISSUE THREAD

**Issue by D40156965** [appium/appium#7039]
## The problem

i just updated the IOS version and in Appium when i run the doctor it gives me "[Error: Could not detect Mac OS X Version from sw_vers output: '10.12
']" error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:10.12
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
You need to upgrade your version of `appium-doctor`. This issue has been fixed.

**Comment by D40156965** [comment]
how can I upgrade that? please send me an instruction.

**Comment by imurchie** [comment]
`npm install -g appium-doctor`. The output ought to indicate version 1.2.4.

**Comment by D40156965** [comment]
Last login: Mon Oct 17 13:10:22 on ttys000
cmclt5cg4454qtl:~ nitesh$ npm install -g appium-doctor
npm http GET https://registry.npmjs.org/appium-doctor
npm http 304 https://registry.npmjs.org/appium-doctor
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/appium-doctor'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/appium-doctor']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/appium-doctor',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/appium-doctor',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 16.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "appium-doctor"
npm ERR! cwd /Users/nitesh
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! path /usr/local/lib/node_modules/appium-doctor
npm ERR! fstream_path /usr/local/lib/node_modules/appium-doctor
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/appium-doctor'
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/nitesh/npm-debug.log
npm ERR! not ok code 0
cmclt5cg4454qtl:~ nitesh$

**Comment by D40156965** [comment]
what can I do on this case?

**Comment by imurchie** [comment]
You need to have access to `/usr/local/lib/node_modules` and contained directories. Change the permissions or owner on there. I presume you installed node/npm with sudo.

**Comment by D40156965** [comment]
it is not working for me>>>>?????

**Comment by imurchie** [comment]
What is "it"? And what is the output of not working?

**Comment by chattip-playbasis** [comment]
It' worked for me.

Answer for resolve this problem.

http://stackoverflow.com/questions/40129794/how-to-fix-error-could-not-detect-mac-os-x-version-from-sw-vers-output-10-12/40168992#40168992
