### ISSUE TITLE
Cannot set context to WebView on iOS 10 real device

### ISSUE THREAD

**Issue by rexors** [appium/appium#7041]
## The problem

~~I want to switch to Webview but this results in an 500 server error. I'm located within a Cordova app. In addition Appium is also able to find the correct Webview:
`POST /wd/hub/session/543437c8-355f-4664-9864-52b759c6b64a/context {"name":"WEBVIEW_de.secret.com"}`~~

~~The problem will be most likely this part of the logs:~~

~~[Appium] New XCUITestDriver session created successfully, session 543437c8-355f-4664-9864-52b759c6b64a added to master session list
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,...
[HTTP] <-- POST /wd/hub/session 200 46582 ms - 610 
[HTTP] --> POST /wd/hub/session/543437c8-355f-4664-9864-52b759c6b64a/context {"name":"WEBVIEW_de.secret.com"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_de.secret.co...
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'WEBVIEW_de.secret.com'
[HTTP] <-- POST /wd/hub/session/543437c8-355f-4664-9864-52b759c6b64a/context 500 8 ms - 109 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":20,"realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","automationName":"XCUITest","bundleId":"de.secret.com","xcodeConfigFile":"/Users/tester/Desktop/Repos/secret/src/app/test/gui/xcconfig","platformName":"iOS","udid":"<my-device-id>","deviceName":"Device"}}~~

~~In addition I started the ios-webkit-debug-proxy but nothing changed. Is the ios-webkit-debug-proxy still required in order to test on hybrid apps in webview contexts?~~

~~I also noticed that one `[XCUITest] xcodebuild exited with code '65' and signal 'null'` which is giving me some exit code but I can't find anything useful on the internet about that exit code.~~
### Edit

I found my mistake: I was switching to a Webview that was not existing. I fixed my problem by dynamically switching to the existing Webview. After switching to an existing Webview everything looks better for a second but then I got a different error:

```
[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:27753/devtools/page/1","faviconUrl":"","thumbnailUrl":"/thumb/file:///var/containers/Bundle/Application/7490DEFD-5CEE-459B-8CCB-E55FA92E9869/stepfolio.app/www/index.html","title":"stepfolio","url":"file:///var/containers/Bundle/Application/7490DEFD-5CEE-459B-8CCB-E55FA92E9869/stepfolio.app/www/index.html","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/1","appId":"PID:673"}]
[MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_1"]
[HTTP] <-- GET /wd/hub/session/a1e076f5-66bc-4bce-80af-6b031e4a036a/contexts 200 98 ms - 98 
[HTTP] --> POST /wd/hub/session/a1e076f5-66bc-4bce-80af-6b031e4a036a/context {"name":"WEBVIEW_1"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_1","a1e076f5-66bc...
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'WEBVIEW_1'
[debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/1
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/a1e076f5-66bc-4bce-80af-6b031e4a036a/context 200 15 ms - 76 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"newCommandTimeout":20,"realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","automationName":"XCUITest","bundleId":"de.ergovia.stepfolio.test","xcodeConfigFile":"/Users/buekera/Desktop/Repos/stepfolio/src/app/test/gui/xcconfig","platformName":"iOS","udid":"fa07957fe9b8519fa6c61f280391e85f730539cb","deviceName":"Device"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"newCommandTimeout":20,"r...
[Appium] Creating new XCUITestDriver session
```

Every seems fine here until Appium tries to create a new session? Why is that? Appium was able to fine the Webview and was able to switch to it. This line seems interesing too: 
`[MJSONWP] Responding to client with driver.setContext() result: null`
The result of the context switch seems to be null.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0
- Last Appium version that did not exhibit the issue (if applicable): not available
- Desktop OS/version used to run Appium: Mac OSX 10.11.6
- Node.js version (unless using Appium.app|exe): 6.8.0
- Mobile platform/version under test: iOS 10.0.2
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: Appium command line
#### Updated Appium logs

https://gist.github.com/rexors/157ce3e15f39bef91a05f2efaac3c949
## Capabilities

I got the following capabilities:

```
desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest")
desiredCapabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 20)
desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Device")
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS")
desiredCapabilities.setCapability(IOSMobileCapabilityType.BUNDLE_ID, "de.secret.com")
desiredCapabilities.setCapability('realDeviceLogger', "/usr/local/lib/node_modules/deviceconsole/deviceconsole")
desiredCapabilities.setCapability('xcodeConfigFile', "/Users/tester/Desktop/Repos/secret/src/app/test/gui/xcconfig")
desiredCapabilities.setCapability(MobileCapabilityType.UDID, "<my-device-id>")
```

...and the following driver:

`IOSDriver<WebElement> driver = new IOSDriver<WebElement>(new URL(PropertyManager.appiumUrl),
                    new CapabilityManager().createIOSCapabilities())`

Thanks in advance!

**Comment by rexors** [comment]
Nobody can help me here?

**Comment by imurchie** [comment]
The `[HTTP] --> POST /wd/hub/session` indicates that the new session is being started at the request of the client. It's not the Appium server that is initiating it.

There is no return value from setting the context.

**Comment by rexors** [comment]
@imurchie Ok, I will have a look, thanks a lot!

**Comment by rexors** [comment]
@imurchie I found out why my client is trying to open a new session:

When my client is receiving this `[MJSONWP] Responding to client with driver.setContext() result: null`, the returned WebDriver is `null` and in this regard the client is trying to open a new session.

So from what I see, the `MJSONWP` is returning `null` after switching to given webview context. From my point of view this is a bug from the `MJSONWP` and has nothing to do with my client.

**Comment by dpgraham** [comment]
Thanks @rexors. Based on the logs you've provided, this does indeed appear to be a bug:

```
[debug] [XCUITest] Executing command 'getContexts'
[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: [{"devtoolsFrontendUrl":"/devtools/devtools.html?ws=localhost:27753/devtools/page/2","faviconUrl":"","thumbnailUrl":"/thumb/file:///var/containers/Bundle/Application/98E0F574-483E-4DEC-ADA8-17FD9E265C6D/secret.app/www/index.html","title":"secret","url":"file:///var/containers/Bundle/Application/98E0F574-483E-4DEC-ADA8-17FD9E265C6D/secret.app/www/index.html","webSocketDebuggerUrl":"ws://localhost:27753/devtools/page/2","appId":"PID:717"}]
[MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP","WEBVIEW_2"]
[HTTP] <-- GET /wd/hub/session/72345735-3491-40e3-b491-c2e4a3636a2a/contexts 200 22 ms - 98 
[HTTP] --> POST /wd/hub/session/72345735-3491-40e3-b491-c2e4a3636a2a/context {"name":"WEBVIEW_2"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_2","72345735-3491...
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'WEBVIEW_2'
[debug] [RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/2
[MJSONWP] Responding to client with driver.setContext() result: null
```

...the call to getContexts proves that WEBVIEW_2 exists so the subsequent call to 'setContext' should not be returning 'null'.

I'll add this to our backlog of issues.

**Comment by imurchie** [comment]
The [spec](https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md#webviews-and-other-contexts) does not specify any return value from this functionality.

**Comment by dpgraham** [comment]
My bad. The call to setContext is successful.

@rexors After your call to setContext, what errors are you experiencing?

**Comment by jlipps** [comment]
@rexors it looks like what is happening is that your client code is attempting to start a new session immediately after the `setContext` call, which results in errors. I would debug your client code to determine why that is happening. Happy to reopen this discussion with more info.

**Comment by Aru1** [comment]
I am not able to switch context in IOS 10.1.1 real device with Appium 1.6.5. I installed ios_webkit_debug_proxy, still not working. Please let me know other version if it works there.

**Comment by maxklimav** [comment]
Here is the open issue: https://github.com/appium/appium/issues/9014

**Comment by maxklimav** [comment]
Here is the open issue about it:  https://github.com/appium/appium/issues/9014
