### ISSUE TITLE
Video player controls not working on iOS10

### ISSUE THREAD

**Issue by qakapil** [appium/appium#7042]
## The problem

My tests with Appium1.6-Xcode8 were more or less working fine until I encountered this issue on iOS10 App yesterday. For our app we have some tests which perform actions on a video player like play, pause, fwd, rewind etc (think of youtube player). Somehow Appium1.6 is not able to perform any action on the elements on this video player. The elements are being recognized properly. 

So self.driver.find_element(By.ID, “PLAY_BUTTON”) does return the element. However, self.driver.find_element(By.ID, “PlayerControls_Close_Button”).click() does nothing. 

When I look at the appium  page_source, everything looks fine with the element. -

 <XCUIElementTypeButton name="PlayerControls_Close_Button" label="Close" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/2" x="-1" y="14" width="44" height="44">

This is happening for all the other elements on the player.

Note - Same tests with Xcode8-Appium1.6 work fine on iOS9, I see this issue on iOS10 device only. Any suggestions ? 
## Environment

Appium1.6
Xcode8
iOS10
MAC OS

**Comment by mykola-mokhnach** [comment]
If this is landscape mode then it's known issue. Otherwise try to tap by coordinates instead of invoking _click_ method.

**Comment by qakapil** [comment]
@mykola-mokhnach thanks for replying. Yes, by our player always launches in landscape view. So does it mean I am blocked here ? Same tests do work on iOS9 though with Appium1.6. Could you please share the issue/bug number with me ?

**Comment by mykola-mokhnach** [comment]
yw: https://github.com/appium/appium/issues/6994

**Comment by qakapil** [comment]
@mykola-mokhnach Thanks. Though in my case I am using iPhone iOS10.0(real device) and not iPad or simulator.
