### ISSUE TITLE
WDA throws error, and tries to open the app several times before crashing with error code 65

### ISSUE THREAD

**Issue by NagyRobertt** [appium/appium#7044]
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.11.6 
* Node.js version (unless using Appium.app|exe): 4.4.7
* Mobile platform/version under test: iOS 10.0.2
* Real device or emulator/simulator: Real Device, iPad Mini 4
* Xcode: 8.0

Desired Capabilities

  desiredCapabilities.setCapability("automationName", "XCUITest");
  desiredCapabilities.setCapability("xcodeConfigFile", "/Users/i318338/Desktop/Config.xcconfig");
 desiredCapabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
 desiredCapabilities.setCapability("deviceName", "iDevice");
 desiredCapabilities.setCapability("platformName", Platform.getPlatform());
 desiredCapabilities.setCapability("udid", getUdid(capabilityProperties));

## Details

I upgraded my appium in hope of running my tests on iOS 10 real devices. I did the necessary steps to be able to run XCUITests (https://github.com/appium/appium-xcuitest-driver#configuration).

However when i try to run my tests appium logs the following: https://gist.github.com/NagyRobertt/7900b48872c8fc02652019fd7a7a4469

From the WDA i was able to log the following: 
https://gist.github.com/NagyRobertt/1d6bfe1d2b56238ff502a8c021d596cd

Hope i gave enough details.
Regards,
Robert

**Comment by imurchie** [comment]
Can you provide the _full_ server logs? It is very difficult to tell anything from a snippet.

**Comment by NagyRobertt** [comment]
Here is the full log: https://gist.github.com/NagyRobertt/5abe64c7a8be55e1267cb6886c100ef5

**Comment by NagyRobertt** [comment]
Actually i just saw in the log for some reason the xconfig didn't provide the provisioning profile properly i tried by adding to WDA project manually but it showed still error: 
https://gist.github.com/NagyRobertt/e1cee63ff48717908c8ee2d9b27a434d

**Comment by imurchie** [comment]
Can you try manually running the command:

```
cd /Users/i318338/.jenkins_ios/workspace/AppiumServerDeployer/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
/Users/i318338/.jenkins_ios/workspace/AppiumServerDeployer/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /Users/i318338/.jenkins_ios/workspace/AppiumServerDeployer/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=46257a5f12f1c9b51c4fe79c60908c20cfe224f9 --xcode-config-file "/Users/i318338/Desktop/Config.xcconfig"
```

**Comment by NagyRobertt** [comment]
Here are the results:
https://gist.github.com/NagyRobertt/65d484e2b08876ee0f1759da04e8af8a

**Comment by NagyRobertt** [comment]
Actually in the WDA project the automatically manage signing option was not ticked. After that the build succeeded but the test still failed:
https://gist.github.com/NagyRobertt/5d730c4fe313d718eb3690ac5b8808c5

**Comment by pavanbachu0604** [comment]
As I see from the logs that the Config file path is not correct. 

"Check dependencies, The file “ProjectSettings.xcconfig” couldn’t be opened because there is no such file. (/Users/i318338/.jenkins_ios/workspace/AppiumServerDeployer/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig)"

**Comment by NagyRobertt** [comment]
I saw that message as well, not sure why it comes up if i declare to use my xcconfig from somewhere else. I tried what happens if i put it there instead but the results were the same.

**Comment by pavanbachu0604** [comment]
Try to access the same path using terminal

**Comment by NagyRobertt** [comment]
Originally there is no such folder there as Configurations. If i created the path and renamed my xcconfig to ProjectSettings this is the result:
https://gist.github.com/NagyRobertt/0d906a0f07f3f16cb3baf23d0dcd0910

Test failed the same way, the only difference is that i didn't get the warning this time.

**Comment by fabianaapateanu** [comment]
I have the same error as in https://gist.github.com/NagyRobertt/0d906a0f07f3f16cb3baf23d0dcd0910
Please see my gist here:
https://gist.github.com/fabianaapateanu/ffc96f6e910645425f33d2bef41c1c81


Appium version (or git revision) that exhibits the issue: 1.6.0
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: 10.12.1
Node.js version (unless using Appium.app|exe): 5.10.1
Mobile platform/version under test: iOS 10.0.2 &  iOS 10.1
Real device or emulator/simulator: Real Device, iPad Air, iPhone 6
Xcode: 8.1 (beta)

**Comment by imurchie** [comment]
@fabianaapateanu Can you reboot your machine? Changing xcodes screws things up a lot.

**Comment by fabianaapateanu** [comment]
@imurchie @NagyRobertt  apparently the  XCTest: code signing blocked mmap() error was indeed a code sign issue. 
I regenerated my Apple development certificate and provisioning profile, and after using the new certificate for signing everything worked fine :D  Just took me 1 and a half day :)))

**Comment by NagyRobertt** [comment]
This seem to have solved my issue as well. Closing the incident.

**Comment by ChiWhiteSox56** [comment]
I've been stuck on this issue for a long time (dyld XCTest / code signing blocked mmap() error) and have not found any solution. I can no longer run Appium tests on real iOD devices. I see that @fabianaapateanu regenerated their development certificate and dev provisioning profile. I do not have a development account (and therefore no development certificate) so the developer has been providing me with the certificate, private key and provisioning profile and I'm accessing them via Keychain Access. Does anyone know if this could be the reason that I'm having this problem? Do I need to generate these from my machine in order for this to work? 

Also, I'm using node 7.3.0. Is downgrading recommended?

**Comment by imurchie** [comment]
@ChiWhiteSox56 Can you create a new issue, with details of how you are doing this and the specific logs? A perfunctory test of moving a certificate from one machine to another seemed to work for me. But I would like to figure out the problem and provide for it.

**Comment by ChiWhiteSox56** [comment]
@imurchie - Will do. Thanks!
