### ISSUE TITLE
Element selector gets rewritten even if it matches XCUI type

### ISSUE THREAD

**Issue by tapisky** [appium/appium#7045]
## The problem

Element selector gets rewritten even if it matches XCUI type when using 'find_element' methods.
## Environment
- Appium version (or git revision) that exhibits the issue: Appium 1.6.0
- Last Appium version that did not exhibit the issue (if applicable): N/A
- Desktop OS/version used to run Appium: Mac OS El Capitan
- Node.js version (unless using Appium.app|exe): 6.2.0
- Mobile platform/version under test: iOS with OSX10
- Real device or emulator/simulator: simulator
- Appium CLI or Appium.app|exe: Appium CLI
## Details

N/A
## Link to Appium logs

`[MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementType...
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[XCUITest] Rewrote incoming selector from '//XCUIElementTypeButton[@name='Convert']' to '//XCUIElementTypeButton[@name='Convert']' to match XCUI type. You should consider updating your tests to use the new selectors directly`
## Code To Reproduce Issue [ Good To Have ]

Ruby:
find_element(xpath: "//XCUIElementTypeButton[@name='Convert']")

**Comment by imurchie** [comment]
Yes, the log is wrong.

**Comment by dpgraham** [comment]
@imurchie Can I close this?

**Comment by imurchie** [comment]
Yes.
