### ISSUE TITLE
Appium1.6 test execution on iPads is very slow

### ISSUE THREAD

**Issue by qakapil** [appium/appium#7046]
## The problem

As far as execution speed is concerned Appium1.6 works really well on  iPhones. However on iPads (iOS9 and iOS10) test execution speed is very slow. 
## Environment

Mac OS 10.11.6
Appium - build from latest master branch
Device - iPad2 iOS10
## Details

Slow test execution. Actions performed on every element are considerably slow compared to iPhones.
## Link to Appium logs

https://gist.github.com/qakapil/c682af707046cb35440438d0c7373a18

**Comment by qakapil** [comment]
Also, please note that I am not using Xpath as a locator strategy for any of my elements.

**Comment by qakapil** [comment]
@imurchie - Hi, any update on this issue ?

**Comment by Timoxa84** [comment]
Faced the same issue. Test execution time on iPad in two times slower than iPhone.

**Comment by qakapil** [comment]
Hi, any update on this one please ? With Appium1.6.3 also test execution on iPad is very slow compared to iPhone

**Comment by ohadschn** [comment]
I am seeing this as well, but it's much worse than 2X slower. Locating a single element can take 4 minutes!

**Comment by ohadschn** [comment]
Could be this: https://github.com/appium/appium/issues/7630

**Comment by dpgraham** [comment]
Closing this due to XCUI and XPath performance being an ongoing issue that's tracked elsewhere
