### ISSUE TITLE
Incorrect error message if user attempts swipe with XCUITestDriver without supplying duration

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/appium#7048]
If a user sends a swipe command without a duration, the following error appears.

```
[1] pry(main)> Appium::TouchAction.new.swipe(start_x: 200, start_y: 200, end_x: 300, end_y:300).perform
Selenium::WebDriver::Error::UnknownError: Support for gestures other than Tap is not yet implemented. Please contact an Appium dev
```

That's not really the correct message since swiping works when duration is provided.

**Comment by jlipps** [comment]
@VivaLosDoyers can you paste the section of your appium server log where it is receiving the parameters from the ruby client? I'd like to see what exactly it's sending the server.

**Comment by VivaLosDoyers** [comment]
Sure thing. Here ya go:

`[HTTP] --> POST /wd/hub/session/8bec241d-63bc-4c07-a542-4778a2f9df6e/touch/perform {"actions":[{"action":"press","options":{"x":100,"y":100}},{"action":"moveTo","options":{"x":100,"y":100}},{"action":"release"}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
[debug] [XCUITest] Executing command 'performTouch'
[HTTP] <-- POST /wd/hub/session/8bec241d-63bc-4c07-a542-4778a2f9df6e/touch/perform 501 5 ms - 175 
`

**Comment by dpgraham** [comment]
Closing this. This error shouldn't happen any more, it should be covered by

```javascript
scroll: {
	      handler: async (x) => {await this.handleScroll(x);},
	      matches: [
	        [{action: 'press'}, {action: 'moveTo'}, {action: 'release'}]
	      ]
	    }
```
