### ISSUE TITLE
XCUITest clicks and taps last too long

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/appium#7051]
## The problem

My iOS app has image assets that behave differently depending on how long a user taps and holds. When quickly tapped (as someone would tap a button for example), a popup menu should appear. 

When I try a normal tap like so:
`find_elements(id: 'MainView.ImageAsset')[1].tap`
or with a click:
`find_elements(id: 'MainView.ImageAsset')[1].click`

The element is animating as if the user pressed the object for longer. I'm unscientifically going to guess that a click lasts 200ms. Is there any way to change this to be shorter?

It's worth noting that with UIAutomation, this issue didn't occur, so it seems like clicks now have a longer duration under XCUITest.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3
- Desktop OS/version used to run Appium: 10.12
- Node.js version (unless using Appium.app|exe): 6.7.0
- Mobile platform/version under test: iOS 9.3
- Real device or emulator/simulator: sim
- Appium CLI or Appium.app|exe: CLI

**Comment by imurchie** [comment]
Can you try clicking? I don't know what client you are using so I cannot tell what it might look like there. But something like `click`.

**Comment by VivaLosDoyers** [comment]
Click unfortunately has the same behavior. This is using ruby_lib

**Comment by VivaLosDoyers** [comment]
Is there any alternative I can try instead of just a .click or .tap? This is basically a showstopper for updating to Appium 1.6.0 and Xcode 8, which is something we really need to do.

**Comment by VivaLosDoyers** [comment]
I was able to work around this by using the press touchaction:

`Appium::TouchAction.new.long_press(element: element, duration: 0.1).perform`

**Comment by imurchie** [comment]
That should work. There is also now a capability `tapWithShortPressDuration` which will do the same. You specify a short period (say `0.1`) in the cap, and the system will use a long press of that duration instead of a tap.
