### ISSUE TITLE
XCUITest driver --browserName capability does not work

### ISSUE THREAD

**Issue by Timoxa84** [appium/appium#7053]
## The problem

Hi, folks! 
I test a native app on iOS. For my testing purposes I use Selenium Grid and it's set up as described in  [Appium's Selenium Grid docs](http://appium.io/slate/en/master/?ruby#selenium-grid)
The Selenium Grid server matches capabilities to nodes using `browserName`, `version`, and `platform`. The session is then passed to the matching node and Appium looks for `deviceName`, `platformName`, and `app`. `browserName` capability being used as a way to specify the device or simulator for the Grid to match the node on (e.g. iPhone 6 Plus)
This approach perfectly worked for Appium 1.5.3 and below.

However for Appium 1.6.0 `browserName` capability allows to select an appropriate device, but runs safari browser instead of the native app.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0 (builded from source)
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: 10.11.6 (El Capitan)
* Node.js version (unless using Appium.app|exe): 6.6.0
* Mobile platform/version under test: 10.0
* Real device or emulator/simulator: real device iPad Air 2
* Appium CLI or Appium.app|exe: Appium CLI

## Details
**Start Appium with cmd:**

`node /appium/ --address 10.6.240.81 --port 4723 --command-timeout 600000 --session-override --nodeconfig /iPad/nodeAppiumiPad.json --debug-log-spacing --app com.test.app --udid <my iPad UDID goes here>`

**nodeAppiumiPad.json configuration:**
```
{
  "capabilities":
      [
        {
			"browserName": "iPad",
			"version":"10.0",
			"selenimProtocol": "WebDriver",
			"platformName":"iOS",
			"maxInstances": 1,
			"deviceName":"iPad",
			"platform":"MAC"
        }
      ],
  "configuration":
  {
    "cleanUpCycle":2000,
    "timeout":600000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "host": "10.6.240.96",
    "port": 4725,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
     "hubPort": 4444,
    "hubHost": "10.6.87.96"
  }
}
```

## Link to Appium logs
https://gist.github.com/Timoxa84/b801a48a2885fddc4c15824e4375dd2f

## Code To Reproduce Issue [ Good To Have ]
https://gist.github.com/Timoxa84/c702046b5bbbd7805324a3f12ac4d7a7

**Comment by senevit4** [comment]
Hello , i am using the same approach of testing my native ios application and i have similar problem.

**Comment by imurchie** [comment]
An oversite. PR in the works.
