### ISSUE TITLE
unable to recognize buttons under MGSwipeTableCell with appium 1.6.0

### ISSUE THREAD

**Issue by srk9ravi** [appium/appium#7058]
## The problem

Unable to recognize the buttons under MGSwipeTableCell element with appium 1.6.0

actually, i have to swipe the cell after that at the end of that cell, i will be displayed with two buttons, which i am unable to click or unable to fetch them in the page source as well, as when i use the page source command, the swipe is going off and the screen coming to normal position which is not showing the buttons.. 

and even after that, i created a multiple xpath's for those buttons to try to click and failed to do that.. please suggest how can i proceed?

{however, as an alternative, i am able to click on them using coordinates as of now..}

{I am attaching the screenshot of the buttons for reference.}
## Environment

appium 1.6.0
ios 9.3 Simulator
[as of now, i am unable to run my app on real device due to code sign issue from our side.]

<img width="371" alt="scrollview_buttons" src="https://cloud.githubusercontent.com/assets/8058405/19537232/359e4c3a-961d-11e6-8a2f-805fc12328e1.png">

**Comment by mykola-mokhnach** [comment]
Probably, it's the issue with accessibility settings in your code. Check my recent comment on https://github.com/appium/appium/issues/6517

**Comment by srk9ravi** [comment]
I am unable to recognize these buttons with appium version 1.5.3 with UI inspector using id property..
i am facing this issue only with 1.6.0 may be as i don't have proper inspector or it is issue with this version..?

**Comment by mykola-mokhnach** [comment]
XCUITest mode uses absolutely different backend to interact with the application under test. Try to use the default Xcode 8 Accessibility Inspector tool to make your buttons are accessible and visible there.
I cannot say more, because the information you provided is definitely not enough to make any assumptions.
