### ISSUE TITLE
[XCUITest] Error: Could not find app at WorkSpaces.ipa

### ISSUE THREAD

**Issue by Dheepthi** [appium/appium#7059]
My test automation scripts were working in Xcode 7.3 and with appium 1.5.*

My iPad device got updated to iOS10 and then my app is not getting launched.

I did all the following steps;
iOS10 + appium 1.6beta

1. download appium 1.6 beta
2. open .xcodeproj in cod
3. download brew install carthage
4. https://github.com/appium/appium-xcuitest-driver#real-devices
5. sudo chmod -R 777 /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/
6. /usr/local/bin/node /usr/local/lib/node_modules/appium/build/lib/main.js -a 0.0.0.0 -p 4723 --app WorkSpaces.ipa --automation-name XCUITest --platform-name iOS
7. install iso-deploy (sudo npm install --global --unsafe-perm ios-deploy)
8. install device console npm install -g deviceconsole
9. brew install ideviceinstaller

Appium logs:
```
685b35999016:~ wsqa$ 
685b35999016:~ wsqa$ /usr/local/bin/node /usr/local/lib/node_modules/appium/build/lib/main.js -a 0.0.0.0 -p 4723 --automation-name XCUITest --platform-name iOS 
[Appium] Welcome to Appium v1.6.0-beta3
[Appium] Non-default server args:
[Appium]   platformName: 'iOS'
[Appium]   automationName: 'XCUITest'
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --automation-name => --default-capabilities '{"automationName":"XCUITest"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   platformName: 'iOS'
[Appium]   automationName: 'XCUITest'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"WorkSpaces.ipa","bundleId":"com.amazon.workspaces","udid":"1180bb0b4c3b10df8ad3781426801e6abee13f41","platformName":"iOS","deviceName":"iPad","realDeviceLogger":"idevicesyslog"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"WorkSpaces.ipa","b...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: 'WorkSpaces.ipa'
[Appium]   bundleId: 'com.amazon.workspaces'
[Appium]   udid: '1180bb0b4c3b10df8ad3781426801e6abee13f41'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPad'
[Appium]   realDeviceLogger: 'idevicesyslog'
[Appium]   automationName: 'XCUITest'
[debug] [XCUITest] XCUITestDriver version: 2.0.29
[BaseDriver] Session created with session id: b7055491-9eec-4fff-a751-a08109e66498
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: 1180bb0b4c3b10df8ad3781426801e6abee13f41
[debug] [XCUITest] Creating iDevice object with udid 1180bb0b4c3b10df8ad3781426801e6abee13f41
[XCUITest] Determining device to run tests on: udid: '1180bb0b4c3b10df8ad3781426801e6abee13f41', real device: true
[debug] [XCUITest] App is an iOS bundle, will attempt to run as pre-existing
[debug] [XCUITest] Checking whether app is actually present
[XCUITest] Error: Could not find app at WorkSpaces.ipa
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at XCUITestDriver.checkAppPresent$ (lib/driver.js:317:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not find app at WorkSpaces.ipa
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at XCUITestDriver.checkAppPresent$ (lib/driver.js:317:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[XCUITest] Error: Could not find app at WorkSpaces.ipa
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at XCUITestDriver.checkAppPresent$ (lib/driver.js:317:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not find app at WorkSpaces.ipa
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at XCUITestDriver.checkAppPresent$ (lib/driver.js:317:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[MJSONWP] Encountered internal error running command: Error: Could not find app at WorkSpaces.ipa
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at XCUITestDriver.checkAppPresent$ (lib/driver.js:317:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 226 ms - 173 
```

Highly appreciate your support

Note: before raising this issue i google'd fully for a solution, but ended in vain.

**Comment by imurchie** [comment]
Try specifying the full path to the app.

**Comment by Dheepthi** [comment]
i have already given full path 
/usr/local/bin/node /usr/local/lib/node_modules/appium/build/lib/main.js -a 0.0.0.0 -p 4723 **--app /Users/wsqa/Desktop/WorkSpaces.ipa** --automation-name XCUITest --platform-name iOS

**Comment by imurchie** [comment]
That's not what you posted the logs for.

But if you are _also_ sending in an `app` desired capability (as you are in the logs) then the command line app is overwritten. The desired capability one (again, in the logs) is not a full path.

**Comment by Dheepthi** [comment]
oh okay got it. will try it and get back. 
Thank u

**Comment by Dheepthi** [comment]
app is not getting launched
i cant see anything happening after last log statement

LOGS:

685b35999016:~ wsqa$ 
685b35999016:~ wsqa$ /usr/local/bin/node /usr/local/lib/node_modules/appium/build/lib/main.js -a 0.0.0.0 -p 4723 --app /Users/wsqa/Desktop/WorkSpaces.ipa --automation-name XCUITest --platform-name iOS 
[Appium] Welcome to Appium v1.6.0-beta3
[Appium] Non-default server args:
[Appium]   platformName: 'iOS'
[Appium]   automationName: 'XCUITest'
[Appium]   app: '/Users/wsqa/Desktop/WorkSpaces.ipa'
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --automation-name => --default-capabilities '{"automationName":"XCUITest"}'
[Appium]   --app => --default-capabilities '{"app":"/Users/wsqa/Desktop/WorkSpaces.ipa"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   platformName: 'iOS'
[Appium]   automationName: 'XCUITest'
[Appium]   app: '/Users/wsqa/Desktop/WorkSpaces.ipa'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"bundleId":"com.amazon.workspaces","udid":"1180bb0b4c3b10df8ad3781426801e6abee13f41","platformName":"iOS","deviceName":"iPad","realDeviceLogger":"idevicesyslog"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"bundleId":"com.amazon.wo...
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   bundleId: 'com.amazon.workspaces'
[Appium]   udid: '1180bb0b4c3b10df8ad3781426801e6abee13f41'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPad'
[Appium]   realDeviceLogger: 'idevicesyslog'
[Appium]   automationName: 'XCUITest'
[Appium]   app: '/Users/wsqa/Desktop/WorkSpaces.ipa'
[debug] [XCUITest] XCUITestDriver version: 2.0.29
[BaseDriver] Session created with session id: 2f68c46b-3e6d-4186-90ac-e2fcdaeff50c
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: 1180bb0b4c3b10df8ad3781426801e6abee13f41
[debug] [XCUITest] Creating iDevice object with udid 1180bb0b4c3b10df8ad3781426801e6abee13f41
[XCUITest] Determining device to run tests on: udid: '1180bb0b4c3b10df8ad3781426801e6abee13f41', real device: true
[BaseDriver] Using local app '/Users/wsqa/Desktop/WorkSpaces.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/jw/xqfsb38d7ylg2gl81_971xnh0000gn/T/2016920-24256-1kmjtfj.p5p32z9f6r/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/jw/xqfsb38d7ylg2gl81_971xnh0000gn/T/2016920-24256-1kmjtfj.p5p32z9f6r/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/jw/xqfsb38d7ylg2gl81_971xnh0000gn/T/2016920-24256-1kmjtfj.p5p32z9f6r/Payload/Skylight.app'
[debug] [XCUITest] Checking whether app is actually present
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=1180bb0b4c3b10df8ad3781426801e6abee13f41' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability.
[debug] [XCUITest] Log file for xcodebuild test: /Users/wsqa/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/F665D99E-1B7D-4E19-968E-AABD004E0096/Session-WebDriverAgentRunner-2016-10-20_094802-H6F8WP.log
[HTTP] <-- POST /wd/hub/session - - ms - - 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"bundleId":"com.amazon.workspaces","udid":"1180bb0b4c3b10df8ad3781426801e6abee13f41","platformName":"iOS","deviceName":"iPad","realDeviceLogger":"idevicesyslog"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"bundleId":"com.amazon.wo...

**Comment by imurchie** [comment]
You need to change your `realDeviceLogger` to `deviceconsole`.

```
[XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability.
```

See https://github.com/appium/appium-xcuitest-driver#external-dependencies

**Comment by imurchie** [comment]
Alternatively you can install the latest `ideviceinstaller`, which works.

**Comment by Dheepthi** [comment]
thank much it worked.

Regarding XPath
static String showAdvanceSettings_XPath = "//**UIAButton**[contains(@name,'Show Advanced Settings')]";

all UIA has to be replaced with XCUIElementType is it?
//**XCUIElementTypeButton**[contains(@name,'Show Advanced Settings')]

Is the above change temporary for appium1.6 beta  or  a permanent change?

**Comment by imurchie** [comment]
That is a permanent change. `UIA` stands for `UI Automation`, which is no longer around.

**Comment by Dheepthi** [comment]
cool. Thanks much. 
Highly appreciate your support
Keep Up.
