### ISSUE TITLE
Getting error while trying to take Screenshot for real ios device

### ISSUE THREAD

**Issue by shanbavi** [appium/appium#7061]
unable to take screenshot on real ios device using the java client has given below 

WebDriver driver2 = new Augmenter().augment(driver);
 File file  = ((TakesScreenshot)driver2).getScreenshotAs(OutputType.FILE);
 FileUtils.copyFile(file, new File("//Users/axion/Documents/workspace/axion"));
getting this error

"Oct 19, 2016 12:19:43 PM org.openqa.selenium.remote.Augmenter extractRemoteWebDriver
WARNING: Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only"

**Comment by imurchie** [comment]
This seems like a Java Client issue. Please ask there.
