### ISSUE TITLE
Appium : Unable to start a Webdriver Session 

### ISSUE THREAD

**Issue by blademaestro** [appium/appium#7062]
## The problem

When i try to run to run my Protractor Test in my app. It would briefly run then once the app opens it would suddenly close and report an error.

this is the error below:
https://gist.github.com/blademaestro/c4c87800aa19fcb4130cfd6b80e9f1b1
## Environment
- Appium version (or git revision) that exhibits the issue: 1.4.61.1
  exhibits the issue:
- Desktop OS/version used to run Appium: Windows 8.1 
- Mobile platform/version under test: Android 4.2.2
- Real device or emulator/simulator: Real Device 
- Appium CLI or Appium.app|exe: Appium.exe 
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

https://gist.github.com/blademaestro/69d70367523f0e70b3b5e4ff0073e0e9
## Code To Reproduce Issue [ Good To Have ]

i'm very new to the community, please tell me if i missed anything else. i've attached the sample project i'm working with in the url below 
https://drive.google.com/open?id=0B5ubsHBoQJqrNzJVdnM4YTlUVEE

**Comment by mykola-mokhnach** [comment]
It looks like _setScriptTimeout_ command is not supported by Appium. Can you execute execute your tests without it?

**Comment by imurchie** [comment]
Yes, it only works for iOS.

**Comment by blademaestro** [comment]
1. I've dug around to find _setScriptTimeout_ , I tried removing it out but the test won't run

2. I'm also using Protractor i'm sorry i missed that part. 

Note: I was able to execute another Ionic project with the same setup and it worked. Is it possibly an issue with Protractor / Appium?

**Comment by blademaestro** [comment]
#1915 timeouts/async_script method not implemented error

*Update:
I've tried searching about the problem. my case is similar to what they were experiencing. I'll try replicating the fix they suggested. hopefully it would resolve my issue.

**Comment by gustavomick** [comment]
same problem fixed with  capabilities.autoWebview= true

**Comment by gustavomick** [comment]
same problem fixed with capabilities.autoWebview= true

**Comment by gkohen** [comment]
@gustavomick, where you able to run your Protractor test on a hybrid app?
After added the line above I get the following error: 

> debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.jda.SLAssociateApp","androidUseRunningApp":true,"androidDeviceSerial":"emulator-5554"}}}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"668625e60b2b7466600963e59ef3093f","status":13,"value":{**"message":"unknown error: unable to discover open pages\n**  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)"}}

**Comment by gustavomick** [comment]
@gkohen yes. using  npm install appium-adb@2.7.0 and appium --chromedriver-executable libs/chromedriver-2.24.exe

**Comment by gkohen** [comment]
@gustavomick , ran in with the version above on my Mac with the same results. Any ideas on where to troubleshoot?
Thanks

**Comment by gustavomick** [comment]
@gkohen no.

**Comment by jlipps** [comment]
yes, `autoWebview` is the correct way to solve this protractor issue. With protractor it does a lot of things assuming you already are in a web context.
