### ISSUE TITLE
Elements missing from the screen on a native android app

### ISSUE THREAD

**Issue by SergioLeone** [appium/appium#7068]
## The problem

I will describe the problem in steps, so it would be easier to understand. I've seen people having similar problem but no one seems to have a solution.
1. I launch the app and navigate somewhere from the Home Screen via one of the buttons that I've successfully located.
2. From the current screen I open a Navigation Drawer Menu and navigate back to Home Screen 
3. Now I try to locate elements on the home screen but the PageSource is empty and I get an error that element could not be located.

What I've tried:
1. all sorts of waits
2. driver.getPageSource(); //Someone suggested this might help, but it didn't

Some additional notes:
- The issue is reproducing when I'm reproducing through same steps in Appium Inspector. In last step, when I'm back on Home Page I try to locate an element in Inspector by id/xpath/..., but it finds nothing. 
- AND, the DOM seems like from previous screen (when the Navigation Drawer was opened), although visibly I see the Home Screen.
- If I Refresh in Inspector, then the DOM is correct again. 
- But if I click on some elements from Home Screen when the DOM is improper, then there is a crash in appium (see below).
- If I try to extract PageSource in 1st Step (with just System.out.print(driver.getPageSource()), then appium gives me the PageSource of the Home Screen in the logs, but if I do the same in 3rd Step, then it's empty.

Appium crash:

```
Exception Name: NSInvalidArgumentException
Description: (
    "<NSIndexPath: 0x6080002373c0> {length = 15, path = 0 - 0 - 0 - 0 - 0 - 1 - 0 - 0 - 0 - 0 - 4 - 1 - 0 - 0 - 0}"
) is not a valid set of index paths; expecting a maximum 0 rows but requested 0
User Info: (null)

0   CoreFoundation                      0x00007fffb49f47bb __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fffc9161a2a objc_exception_throw + 48
2   AppKit                              0x00007fffb2a51c46 -[NSBrowser setSelectionIndexPaths:] + 2283
3   Appium                              0x0000000101bac4f0 -[AppiumInspector setSelectedNode:] + 1760
4   Appium                              0x0000000101baceb7 -[AppiumInspector selectNodeNearestPoint:] + 119
5   Appium                              0x0000000101bafdcd -[AppiumInspector handleClickAt:seleniumPoint:] + 685
6   Appium                              0x0000000101bb26c8 -[AppiumInspectorScreenshotImageView mouseUp:] + 264
7   AppKit                              0x00007fffb2e70dfe -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 1544
8   AppKit                              0x00007fffb2e7042a -[NSWindow(NSEventRouting) sendEvent:] + 541
9   AppKit                              0x00007fffb2d10bf5 -[NSApplication(NSEvent) sendEvent:] + 1145
10  AppKit                              0x00007fffb25f7009 -[NSApplication run] + 1002
11  AppKit                              0x00007fffb25c1a8a NSApplicationMain + 1237
12  Appium                              0x0000000101b7c4e2 main + 34
13  libdyld.dylib                       0x00007fffc9a3d255 start + 1
```
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable): NA
- Desktop OS/version used to run Appium: MacOS 10.12
- Node.js version (unless using Appium.app|exe): NA
- Mobile platform/version under test: 4.4.2
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: app
## Details

NA
## Link to Appium logs

https://gist.github.com/Ser-Gius/ba468a1cd15fa78d0735248394407d17
## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by Ser-Gius** [comment]
It's not iOS, but Android and I'm testing native elements, not hybrid app

**Comment by jlipps** [comment]
closing in favor of #7119
