### ISSUE TITLE
element (visible=\"false\" ) can be find 

### ISSUE THREAD

**Issue by wjl025** [appium/appium#7070]
## The problem

element is visible=\"false\,but find
## Environment
- Appium version (or git revision) that exhibits the issue:1.6.0
- Last Appium version that did not exhibit the issue (if applicable):1.5.3
- Desktop OS/version used to run Appium:10.11.6
- Node.js version (unless using Appium.app|exe):6.6.0
- Mobile platform/version under test:ios 9.3.5
- Real device or emulator/simulator:real device
- Appium CLI or Appium.app|exe:CLI
## Details

<XCUIElementTypeButton name="cancel" label="cancel" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/0/0/0/1" x="8" y="31" width="21" height="22"></XCUIElementTypeButton>

<XCUIElementTypeButton name="cancel" label="cancel" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/2/0" x="15" y="176" width="345" height="45"></XCUIElementTypeButton>

two button ,one visible = false,one true
find_element (:accessibility_id,'cancel' ) and click
i want to click button(visible=true),but click first button(visible=false)

**Comment by wjl025** [comment]
<XCUIElementTypeButton name="cancel" label="cancel" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/0/0/0/1" x="8" y="31" width="21" height="22"></XCUIElementTypeButton>

<XCUIElementTypeButton name="cancel" label="cancel" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/2/0" x="15" y="176" width="345" height="45"></XCUIElementTypeButton>

**Comment by wjl025** [comment]
![image](https://cloud.githubusercontent.com/assets/22388210/19593844/0d5ca58e-97b5-11e6-832e-dd6124c5f37c.png)

**Comment by mykola-mokhnach** [comment]
Known issue. Will be fixed by https://github.com/facebook/WebDriverAgent/pull/308
