### ISSUE TITLE
Appium startup crashes if there is an alert opens

### ISSUE THREAD

**Issue by chandrasekharmelam** [appium/appium#7074]
Hi Team,

There is an alert already presented in the ios device. I started appium without closing the alert. that time it is showing instrument crushed on startup. 

Im using:
Appium 1.6.0 beta3
xcode:7.3.1

Thanks in advance.

**Comment by imurchie** [comment]
Yes. Appium has no way of controlling the device until Instruments has launched. You need to dismiss random alerts that are going on before the session.

**Comment by SrinivasanTarget** [comment]
@triager please close
