### ISSUE TITLE
iOS web support on real device hangs if native dialog opens

### ISSUE THREAD

**Issue by cschabetsberger-micro-focus** [appium/appium#7075]
## The problem

It is easily possible to open native dialogs in Safari, for example, by executing a long tap on the device when the Apple website is open (see attached screenshot). As soon as the dialog is open, the next call of the Appium iOS driver does not return.
## Environment
- 1.5.3
- OS X El Capitan
- Node.js v4.4.3
- iOS 9.3.5
- Real device
## Details

When looking at the log output, it seems that the call that is executed after the native dialog opened does not return in appium-uiauto::UIAutoClient (so the callback of the sendCommand function is never called or at least not for a long time). However, the log does not indicate an error in the UIAutoClient or in the command-proxy-client.js

Steps to reproduce:
1. Start iOS web testing on a real iOS device
2. Navigate to http://www.apple.com/
3. Execute a longTap action so that a native dialog opens up (see the screenshot)
-> The next call of the Appium iOS driver does not return.

![ios_device_screen](https://cloud.githubusercontent.com/assets/20298501/19601962/9575c036-97ab-11e6-8ef6-dc271c84edf3.PNG)

Log output (only lines of interest):
[HTTP] --> GET /wd/hub/session/0e94c9b9-bce0-46c4-b1e5-30eded6eba74/window/current/size {}
[MJSONWP] Calling AppiumDriver.getWindowSize() with args: ["current","0e94c9b9-bce0-4...]
[debug] [iOS] Executing iOS command 'getWindowSize'
[debug] [UIAuto] Sending command to instruments: au.getWindowSize()
[debug] [Instruments] [INST] 2016-10-21 13:59:40 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-10-21 13:59:40 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-10-21 13:59:40 +0000 Debug: Running system command #10: /Applications/Silk/Mobile/osx/Node/node /Applications/Silk/Mobile/common/Appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/gr/l4x_wssn1yj2mvyz9p557f380000gn/T/instruments_sock 2,{"status":0,"value":""}...

**Comment by imurchie** [comment]
Can you provide the full logs (as a [gist](https://gist.github.com)). They are also of interest.

**Comment by henrymclay** [comment]
I'm getting a similar thing automating a Spotify sign-in in an app with mobile and (limited) Webviews on a real device, same setup except I have:

- node 6.7.0

I click login and get a popup asking me if I'd like to open the page in the hybrid app I'm automating, and then Appium hangs - following the click to log in that opens the dialog, I no longer get a response to commands I send, and my tests or console will hang til I quit the server or it times out. 

I've noticed that I am able to get and change web and native view contexts after this, and those seem to respond correctly, but no other commands get a response from Appium. 

Apologies for not posting the full logs - I'm limited in what I can share, but if there's a particular part that would be of interest (or something to look for) I can work on a sanitized version. 

In both cases when it hangs I'm getting a similar pattern to: 

"[debug] [iOS] Executing iOS command 'postAcceptAlert'
[debug] [UIAuto] Sending command to instruments: au.acceptAlert()
[debug] [Instruments] [INST] 2016-10-27 23:20:15 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-10-27 23:20:15 +0000 Debug: responding with:" 

after I try a command following the window popping up (again, Native and Webview context getting and setting seems to be the exception, but it will hang after changing that). 

I get the same behavior with autoAcceptAlerts set to true (with the postAcceptAlert firing and everything).

**Comment by dpgraham** [comment]
Closing this. Will re-open if logs provided.
