### ISSUE TITLE
Unable to capture screenshot in webview in Android Hybrid application

### ISSUE THREAD

**Issue by tekisrinivas20** [appium/appium#7076]
Hi team,

I am automating Android Hybrid Application using Appium, while working i am switching to both webview and native view. If any exception occurred I am trying to capture screenshot, but i am unable to capture screenshot in webview, Appium server sending screenshot command to server but Appium server getting shutdown after 40 sec and i am not able to get the screenshot. I have tried the possible ways but no luck could any one please help on this issue and I am attaching server logs, Working environment.
## Environment
- Appium version1_4_16_1
- Windows 7 64 bit
- Android - 5.1.1
- Real device (Samsung 10 inch tablet)
- Latest Chrome driver - 2.24
## Appium server logs :

https://gist.github.com/tekisrinivas20/26913b2879d63859c1e6787281a2c5b8
## Code To Reproduce Issue:

To switch webview : driver.context("WEBVIEW_");
DateFormat df = new SimpleDateFormat("dd-MM-yyyy HH-mm-ss");
Date date = new Date();
File file = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
FileUtils.copyFile(file, new File("D:\Appium_Reports\"+df.format(date)+".png"));

Thank you,

**Comment by tekisrinivas20** [comment]
As same, server getting shutdown after shudown and below are the server logs
> info: --> GET /wd/hub/session/6f376cb9-7ee5-4b6c-a56b-dc2bebb06b5c/screenshot {}
> info: JSONWP Proxy: Proxying [GET /wd/hub/session/6f376cb9-7ee5-4b6c-a56b-dc2bebb06b5c/screenshot] to [GET http://127.0.0.1:9515/wd/hub/session/2f0ccffbf552ea9697ed8f08ab7e734c/screenshot] with body: {}
> info: [debug] Didn't get a new command in 60 secs, shutting down...

**Comment by imurchie** [comment]
Oh. I didn't notice you were using an old version of Appium. 

There's not much that can be done. In 1.5.3 and above you can specify to use adb rather than ChromeDriver to get screenshots, which are flakey in CD. Before that you cannot.

**Comment by tekisrinivas20** [comment]
I have downloaded Appium 1.5.3 source but, how can I update Appium version to 1.5.3.
