### ISSUE TITLE
ios 10 facing issue while switching to webview

### ISSUE THREAD

**Issue by acdurai** [appium/appium#7077]
@imurchie 

Xcode 8.0
Appium 1.6.0
iOS 10
ios-webkit-debug-proxy

Am able to run the test in native screens, but facing issue only while switching to hybrid pages.

**Comment by SrinivasanTarget** [comment]
@acdurai Please log a new issue with detailed description following the issue template and attach your logs in form of gist to look further.

**Comment by SrinivasanTarget** [comment]
@triager please close
