### ISSUE TITLE
Appium server freezes

### ISSUE THREAD

**Issue by Mygod** [appium/appium#7078]
## The problem

Appium server freezes.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu x64 16.04 (Linux Mint 18)
* Node.js version (unless using Appium.app|exe): 6.8.1
* Mobile platform/version under test: Android emulator 7.1.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

The app being tested: https://github.com/Mygod/nju-portal-login-android

I can't seem to reproduce this bug continuously.

## Link to Appium logs

https://gist.github.com/Mygod/5b19174c2b448efea0c1cffccfef1e3d

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
This has been fixed but not yet in a full appium release. Can you re-install Appium with the latest?

```
npm uninstall -g appium
npm install -g appium --no-shrinkwrap
```

**Comment by Mygod** [comment]
Haven't experienced another freeze like this for a while now. I'd suppose this has been fixed.
