### ISSUE TITLE
ios debug webkit proxy disconnects while connecting to webview on Appium 1.6.0

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#7080]
## The problem

ios debug webkit proxy disconnects, as soon as the gets app deployed on the the phone.

I run a shell script to runs this command before creating the ios driver:
ios_webkit_debug_proxy -c 9f18f3f8f092bce333b63fd1e50a36332109654f:27753

Have added the desired capabilities below.
This works fine on Appium 1.5.3, noticed this happening since moving to XcuiTest i.e Appium 1.6.0
I have to manually run the command, to get connected  and get Webviews after the first attempt to connect to debug proxy fails.

Already added comments about ios debug webkit proxy here:
https://github.com/google/ios-webkit-debug-proxy/issues/143
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3
- Desktop OS/version used to run Appium: OSX 10.11.6
- Node.js version (unless using Appium.app|exe): v5.5.0
- Mobile platform/version under test:  iOS 9.3.5 
- Real device or emulator/simulator: iPhone 5s
- Appium CLI 
## Link to Appium logs

Appium Log:
https://gist.github.com/mayureshshirodkar/21190b801c0555fde504158da59cd629

ios_webkit_debug error:
^CMacBook-Pro:~ shirodkm$ ios_webkit_debug_proxy -c 9f18f3f8f092bce333b63fd1e50a36332109654f:27753
Connected :27753 to iPhone (9f18f3f8f092bce333b63fd1e50a36332109654f)
Unknown app_id PID:1973
Invalid message _rpc_applicationSentListing: <dict>
    <key>WIRApplicationIdentifierKey</key>
    <string>PID:1973</string>
    <key>WIRListingKey</key>
    <dict>
        <key>8</key>
        <dict>
            <key>WIRPageIdentifierKey</key>
            <integer>8</integer>
            <key>WIRTitleKey</key>
            <string>JSContext</string>
            <key>WIRTypeKey</key>
            <string>WIRTypeJavaScript</string>
        </dict>
    </dict>
</dict>
Disconnected :27753 from iPhone (9f18f3f8f092bce333b63fd1e50a36332109654f)
## Code To Reproduce Issue [ Good To Have ]

```
    DesiredCapabilities iOSCapabilities = new DesiredCapabilities();
    iOSCapabilities.setCapability("deviceName", Base.readInternalHash("ios_device"));
    iOSCapabilities.setCapability("platformVersion", Base.readInternalHash("ios_version"));
    iOSCapabilities.setCapability("automationName", "XCUITest");
    iOSCapabilities.setCapability("showXcodeLog", true);
    iOSCapabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
    iOSCapabilities.setCapability("app", System.getProperty("user.dir") + Base.readInternalHash("ios_app"));
    iOSCapabilities.setCapability("bundleId", Base.readInternalHash("bundle_id"));
    iOSCapabilities.setCapability("newCommandTimeout", 500);
    iOSCapabilities.setCapability("autoWebview", true);
    iOSCapabilities.setCapability("autoWebviewTimeout", 12000);
    //iOSCapabilities.setCapability("fullReset", true);
    iOSCapabilities.setCapability("autoAcceptAlerts", true);
    iOSCapabilities.setCapability("udid", Base.readInternalHash("udid"));

    driver = new IOSDriver(new URL(Base.readInternalHash("url_ios")), iosNative());
```

**Comment by testingIOS** [comment]
Encountered same issue on iOS 9.3.5 iPad device while setting the webview context using XcuiTest i.e Appium 1.6.0. We need this fix soon, it is blocking to continue the tests unless manual intervension

**Comment by Thirumalaivigneshm** [comment]
Hi, 

Is there any update on this. 

**Observation**:
1. The **ios_webkit_debug_proxy** connects for the 1st time from the terminal.
2. The appium server v1.6.0 is started with the **--webkit-debug-proxy-port 27753** flag.
3. During the automation when the hybrid application navigates to the Webview page/content the "ios_webkit_debug_proxy" disconnects providingthe following error. 

Unknown app_id PID:857
Invalid message _rpc_applicationSentListing: <dict>
	<key>WIRApplicationIdentifierKey</key>
	<string>PID:857</string>
	<key>WIRListingKey</key>
	<dict>
		<key>1</key>
		<dict>
			<key>WIRPageIdentifierKey</key>
			<integer>1</integer>
			<key>WIRTitleKey</key>
			<string>JSContext</string>
			<key>WIRTypeKey</key>
			<string>WIRTypeJavaScript</string>
		</dict>
	</dict>
</dict>
ss.remove_fd(6)
Disconnected :27753 from iPhone6+ eText3 (007afd54fa9194e46aa8eb2d749c91f58a8c91d7)


4. If, I reconnect the ios_webkit_debug_proxy manually while debugging the automation script and try to get the list of Contexts, it works. But why it disconnects during the automation while moving to the Webview content. 



Kindly help.


Thanks,
Thiru

**Comment by VeronikaGusarova** [comment]
Hi,

is there any progress regarding this issue or just a workaround?

Facing the same problem for my hybrid app

Kindly help,

Thanks, Veronika

**Comment by mayureshshirodkar** [comment]
@jlipps  is there any workaround that we could use for this? Or should we be updating ios debug proxy?
Right now, my tests fail during the run as the iPhone gets disconnected on encountering this error.

**Comment by jlipps** [comment]
Have you tried with the latest IWDP? I have not been able to reproduce this. And how are you starting IWDP?

**Comment by VeronikaGusarova** [comment]
Works fine for me with updated IWDP, thanks a lot!

**Comment by jlipps** [comment]
Excellent!
