### ISSUE TITLE
cant switch the context to web view in android using java.

### ISSUE THREAD

**Issue by vutukuriswathi** [appium/appium#7081]
## The problem

When I tried to switch to webview ,I am getting the context as undefined.Some times it is printing webview context as "WEBVIEW_undefined "and some times "WEBVIEW_XXXXX".Can any one please help me how to resolve it.I believe some thing is broken on appium java side.
## Environment

Appium: 1.4.13
Android real device: 6.0.1

I used the below code to switch to web view.
Set<String> availableContexts = driver.getContextHandles();
            for (String contexts : availableContexts) {
                System.out.println("Context Name is " + contexts);
                if (contexts.contains("WEBVIEW")) {
                    System.out.println("Context Name is " + contexts);
                    ((AndroidDriver) driver).context(contexts);
                    break;
                }
            }

**Comment by SrinivasanTarget** [comment]
@vutukuriswathi Please try a latest version of appium server 1.6.1 beta, java client latest version and it should be working properly. Incase if you hit the same issue. Raise a new issue with detailed log in form of gist and also follow the issue template to look further.

**Comment by SrinivasanTarget** [comment]
@triager please close
