### ISSUE TITLE
Xcode 8 iOS10.0 : Unable to launch appium

### ISSUE THREAD

**Issue by GopalakrishnaNagam** [appium/appium#7082]
## The problem

Xcode 8 with iOS 10 Simulator
1)  Installed Xcode8 and iOS 10 Simulator.
2)  Tried to launch IOS simulator through Appium(Version 1.4.13) manually.
3)  Upgraded the Appium Version to 1.5 and checked with the Xcode8 – Still the same issue exists.
4)   I tried installing beta version as per the blog comments (npm install -g appium@beta),still the same issue exists.

**Comment by Akulavenkatesh** [comment]
What error message are you seeing? How are you trying to launch Appium - GUI or Terminal?
There is Appium 1.6.0 stable version, please install it.

**Comment by imurchie** [comment]
Neither 1.4.13 nor 1.5.x will work with Xcode 8. You need Appium 1.6.0.

**Comment by videmort** [comment]
There is no version 1.6 DMG yet :(

**Comment by GopalakrishnaNagam** [comment]
Through terminal i have the installed the latest version (npm install -g appium) (v1.6.0)
Xcode8 and iOS 10 Simulator

Launched the app through terminal and ran the script
App is not launching and in error logs message is displaying as 
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead. (WARNING: The server did not provide any stacktrace information)

**Comment by imurchie** [comment]
You need to specify `automationName` of XCUITest.
