### ISSUE TITLE
Swipe method in appium

### ISSUE THREAD

**Issue by GopalakrishnaNagam** [appium/appium#7083]
## The problem

We have an functionality in our project where we have to swipe and delete the record.Kindly let me know how to work on this.
If we try to do the swipe action using javascript executor of selenium, error thrown as Swipe method is not yet implemented.
Is there any other way to handle this scenario.

**Comment by VivaLosDoyers** [comment]
Did you include a duration? You'll get that error message if you don't include the duration. 

See https://github.com/appium/appium/issues/7048
