### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by rafalf** [appium/appium#7084]
## The problem

I am pretty much facing this issue: https://github.com/appium/appium/issues/6978 after upgrading appium.
So I tried the solution from #6978  
`npm install -g appium --no-shrinkwrap`
and I got the following error when starting appium:
_TypeError: Path must be a string. Received undefined_

How am I supposed to get it working?

## Environment
*  appium@1.6.0
* Windows 10
* Real device or emulator/simulator: Emulator

## Appium logs

C:\WINDOWS\system32>npm install -g appium --no-shrinkwrap
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
C:\Users\rafal\AppData\Roaming\npm\appium -> C:\Users\rafal\AppData\Roaming\npm\node_modules\appium\build\lib\main.js
C:\Users\rafal\AppData\Roaming\npm
`-- appium@1.6.0

npm WARN optional Skipping failed optional dependency /appium/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

C:\WINDOWS\system32>appium
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:184:7)
    at Object.<anonymous> (lib/driver.js:45:8)
    at Module._compile (module.js:541:32)

## Code To Reproduce Issue [ Good To Have ]

start `appium` from command line

**Comment by mykola-mokhnach** [comment]
Seems like you've provided some invalid value in capabilities.

**Comment by imurchie** [comment]
No. This is a problem with Appium. I'm looking into what it is.

**Comment by imurchie** [comment]
I've tracked down the problem. I broke it in the ios driver, but it is fixed in `appium-ios-driver@1.12.30`.

Can you re-install without shrinkwrap? Sorry about that.

**Comment by rafalf** [comment]
When I re-install it  I get the other error

`[UiAutomator] Error while killing uiAutomator: Error: Unable to kill uiautomator processes. Original error: Unable to get pids for uiautomator. Orginial error: this.shell(...).trim is not a function` #6978 

I re-install it via:  `npm install -g appium`

How do I check versions of the specific components ?

I am running on: appium@1.6.0

**Comment by imurchie** [comment]
Sorry, you need to turn off shrinkwrap

```
npm uninstall -g appium
npm install -g appium --no-shrinkwrap
```

**Comment by rafalf** [comment]
thanks!! seems to not throwing any errors now and it's 1.12.30 after re-install 

It's shutting down for me now itself tho. but thats probably some other issue I guess 


[Chromedriver] [STDOUT] Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 8000
Only local connections are allowed.
[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"10.0\"}}}"
[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"emulator-5554"}}}
[JSONWP Proxy] Got response with status 200: {"sessionId":"37d95834048f41e54710bb1a58932a9e","status":13,"value":{"message":"unknown error: Chrome version must be >= 46.0.2490.0\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 10.0 x86_64)"}}
[debug] [Chromedriver] Changed state to 'online'
[Appium] New AndroidDriver session created successfully, session d925fc1a-e754-4206-a01a-f7127de0d67f added to master session list
[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"platformVersion":"5.1.1","deviceName":"A...
[HTTP] <-- POST /wd/hub/session 200 8639 ms - 517
[HTTP] --> POST /wd/hub/session/d925fc1a-e754-4206-a01a-f7127de0d67f/url {"url":"www.google.com","sessionId":"d925fc1a-e754-4206-a01a-f7127de0d67f"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/d925fc1a-e754-4206-a01a-f7127de0d67f/url] to [POST http://127.0.0.1:8000/wd/hub/session/37d95834048f41e54710bb1a58932a9e/url] with body: {"url":"www.google.com","sessionId":"d925fc1a-e754-4206-a01a-f7127de0d67f"}
[JSONWP Proxy] Got response with status 200: {"sessionId":"37d95834048f41e54710bb1a58932a9e","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 10.0 x86_64)"}}
[JSONWP Proxy] Replacing sessionId 37d95834048f41e54710bb1a58932a9e with d925fc1a-e754-4206-a01a-f7127de0d67f
[HTTP] <-- POST /wd/hub/session/d925fc1a-e754-4206-a01a-f7127de0d67f/url 200 21 ms - 219
[HTTP] --> DELETE /wd/hub/session/d925fc1a-e754-4206-a01a-f7127de0d67f {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["d925fc1a-e754-4206-a01a-f7127de0d67f"]
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Stopping chromedriver for context CHROMIUM
[debug] [Chromedriver] Changed state to 'stopping'
[JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8000/wd/hub/session/37d95834048f41e54710bb1a58932a9e] with no body
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"37d95834048f41e54710bb1a58932a9e\",\"status\":0,\"value\":null}"
[debug] [Chromedriver] Changed state to 'stopped'
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","input","keyevent",3]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Time: 6.533
[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[debug] [AndroidBootstrap] Received command result from bootstrap

**Comment by imurchie** [comment]
The server is getting a delete request, to end the session. Something is going on with your test, not Appium, at this point.

**Comment by rafalf** [comment]
thanks, I'll try to figure that out.. however .. the test is pretty straight forward 
https://gist.github.com/rafalf/22653ea09d83f3ea2674259371863665

**Comment by imurchie** [comment]
I don't know. The command on line 16 is not getting to the server, for whatever reason.

**Comment by rafalf** [comment]
Its failing while starting the session  it doesnt get to even open the url 
I think i have track it down tho :) 
Thanks @imurchie for the quick response 

[JSONWP Proxy] Got response with status 200: {"sessionId":"a41571cf0b4faff0c610b5458b683120","status":13,"value":{"message":"unknown error: Chrome version must be >= 46.0.2490.0\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 10.0 x86_64)"}}

**Comment by rafalf** [comment]
Closing it
