### ISSUE TITLE
Can't run tests on real devices with xCode 8, iOS 9.3 and appium 1.6.0-beta3

### ISSUE THREAD

**Issue by PeterGolf** [appium/appium#7086]
## The problem

Trying to run tests on real iOS device. The develop team give me .ipa file. I also have a developer apple id. Have an error while starting WebDriverAgentRunner

[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'

[Xcode] 
Testing failed:
	No profiles for 'com.facebook.WebDriverAgentRunner' were found:  Xcode couldn't find a provisioning profile matching 'com.facebook.WebDriverAgentRunner'.

[Xcode] 	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'
** TEST FAILED **

## Environment

* Appium version 1.6.0-beta3
* Desktop OS/version used to run Appium: macOS 10.12 (16A323)
* Node.js version (unless using Appium.app|exe): 3.10.8
* Mobile platform/version under test: iOS 9.3
* Real device
* Appium CLI

**Comment by mykola-mokhnach** [comment]
WebDriverAgent project has to be signed as well by the same developer signature as the main application under test. you can either set signing profile manually for WebDriverAgent project by opening it in Xcode or use _xcodeConfigFile_ capability (and, probably, _keychainPath_ + _keychainPassword_) like it is described in https://github.com/appium/appium-xcuitest-driver#usage

**Comment by PeterGolf** [comment]
I have already tried to make it via xCode and have an error:

Failed to create provisioning profile.
The app ID "com.facebook.WebDriverAgentRunner" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.

com.facebook.WebDriverAgentRunner' were found
Xcode couldn't find a provisioning profile matching 'com.facebook.WebDriverAgentRunner'.

**Comment by mykola-mokhnach** [comment]
You maybe try to sign it with an enterprise profile, which is not gonna work. You need a development one and the device under test should be explicitly included into the list of provisioned devices. Also, the application itself should be built in debug mode (this also means you will not be able to test a build, which is ready for AppStore deployment). Ping your developers if you are unsure about the stuff.

**Comment by PeterGolf** [comment]
@mykola-mokhnach Thanks! I will try to make it with not enterprise profile. Don't close this issue plz

**Comment by PeterGolf** [comment]
@mykola-mokhnach I changed my profile and build WebDriverAgentRunner, but still have the same problem. Wont to try change this: Real device security settings fix for real devices. How can i exportthe private development key from my system keychain?

**Comment by PeterGolf** [comment]
But i just tried to run command: "node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project ~/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=*****" and at the end i have 
2016-10-25 11:22:04.264 XCTRunner[475:178773] Built at Oct 25 2016 11:21:50
2016-10-25 11:22:04.292 XCTRunner[475:178773] ServerURLHere->http://(null):8100<-ServerURLHere
2016-10-25 11:22:04.293 XCTRunner[475:178773] Listening on USB

**Comment by PeterGolf** [comment]
I resolved this problem by reinstalling appium via downloading and using npm in appium derectory. After this i run command with "node ." command

**Comment by rajeshantony74** [comment]
I have followed this link and it worked for me. Basically you need to create a xcodConfig and apply it to the to project ( under Configuration ).

**Comment by ohadschn** [comment]
@mykola-mokhnach I'm pretty sure the app under test doesn't have to be signed using the same developer as WDA. I run tests with no issue using a different signer, albeit in the same development team.

**Comment by arifmasood** [comment]
@ohadschn if i understand correctly you are saying that signing can be done using any account that is part of same development team ?

Can we also do the signing with an account that is by no way associated to development team?

**Comment by ohadschn** [comment]
@arifmasood I don't know (all my accounts were under the same dev team), but if you get a chance to test it, it would be interesting to know...
