### ISSUE TITLE
Xcodebuild connection refused with Simulated device, module.modulemap: Permission denied

### ISSUE THREAD

**Issue by EricBlueSav** [appium/appium#7090]
## The problem

I am trying to run a suite of automated tests built with protractor and NodeJS on an iPhone simulator using Appium.

## Environment

* Appium 1.6.0
* Desktop OS/version used to run Appium: macOS 10.12
* Node.js version (unless using Appium.app|exe): 6.7.0
* Mobile platform/version under test: iPhone SE, 5s, iPad 10.0... etc tried a few
* Simulator
* Appium CLI

## Details

When I run my tests I get a few interesting errors:

2016-10-24 16:48:29.031 xcodebuild[2607:55915] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7f9c6b47a4d0>

Testing failed: ./Scripts/generate_modules.sh: line 15: Modules/module.modulemap: Permission denied

** TEST FAILED **

The following build commands failed:
	PhaseScriptExecution Generate\ modules /Users/ericsavoie/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/Script-AD35D0281CF1B37A00870A75.sh
(1 failure)

xcodebuild exited with code '65' and signal 'null'

## Link to Appium logs

Appium logs in [gist](https://gist.github.com/EricBlueSav/6aadbbde2e0f9f5902b7f1102d70c422) 

WebDriverAgent logs in [gist](https://gist.github.com/EricBlueSav/83b7456144395bba387e10a4f196c00f)

WebDriverAgent retry logs in [gist](https://gist.github.com/EricBlueSav/54cc991397f055955d13e5f073472934)

## Code To Reproduce Issue [ Good To Have ]

Running Appium using: "appium"

protractor capabilities set up as
    {
      browserName: 'safari',
      'appium-version': '1.6',
      platformName: 'iOS',
      platformVersion: '10.0',
      deviceName: 'iPad Pro (9.7 inch)',
    },

running using: protractor

Potentially useful to know, with this exact set up I have Android tests working flawlessly. There is something going wrong with the env used to test Apple devices nothing wrong with my general set up. It is certain that there is something wrong with an apple device specific setting.

**Comment by mykola-mokhnach** [comment]
Make sure your current user has write permissions to the folder where Appium is currently installed

**Comment by EricBlueSav** [comment]
Thanks that got me started! It is loading the webpage :)
