### ISSUE TITLE
fullReset capability does not work on Appium 1.6.0

### ISSUE THREAD

**Issue by pengboZheng** [appium/appium#7092]
## Environment
- Appium version: 1.6.0
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3
- Desktop OS/version used to run Appium: OSX 10.11.6
- Node.js version (unless using Appium.app|exe): v.6.9.1
- Mobile platform/version under test: iOS9.3.5
- Real device or emulator/simulator: Real device iPhone 6
- Appium CLI or Appium.app|exe: Appium CLI
## Details
1. Put fullReset capabilities in setup() won't work
2. Put fullReset when run Appium server CLI `appium --full-reset`, wont' work
3. Remove fullReset capabilities from setup will work
4. Remove fullReset from CLI will work
5. use both fullReset in setup() and CLI under appium version 1.5.3 will work perfectly.
## Link to Appium logs

https://gist.github.com/pengboZheng/b79b5d43cccc43469cb8c30c7c9bd618
## Code To Reproduce Issue [ Good To Have ]

From Java:
`capabilities.setCapability(MobileCapabilityType.FULL_RESET, true);`
From Appium CLI:
`appium --full-reset`

**Comment by mykola-mokhnach** [comment]
I don't think this is a bug - "fullReset" option has never been advertised in docs: https://github.com/appium/appium-xcuitest-driver#usage

**Comment by mayureshshirodkar** [comment]
I see fullReset under Appium server capabilities.
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md

**Comment by mayureshshirodkar** [comment]
This seems to be an issue.No work around yet.
@jlipps @imurchie Any Work arounds you could suggest?

**Comment by jlipps** [comment]
> TypeError: Cannot read property 'opts' of null

^ is definitely a bug. Whether `fullReset` is supposed to work or not on real devices in 1.6 is another question. But let's resolve this bug first.

**Comment by imurchie** [comment]
This is indeed an error. 

Fix: https://github.com/appium/appium-ios-driver/pull/190

**Comment by mayureshshirodkar** [comment]
Just tried the fix on my local Appium. 
fullReset worked for me.
@imurchie @jlipps Thanks for looking into the issue.

**Comment by pengboZheng** [comment]
@imsardine Awesome! thanks man
