### ISSUE TITLE
Appium does not auto accept system pop ups on iOS 9 and above

### ISSUE THREAD

**Issue by shahmharsh** [appium/appium#7093]
## The problem

Appium does not auto accept system pop ups on iOS 9 and above

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.13 and above (including 1.6.0-beta3)
* Last Appium version that did not exhibit the issue (if applicable): Have been seeing this issue since 1.4.13. Haven't verified if it works in earlier versions.
* Desktop OS/version used to run Appium: Mac OS 10.11.6
* Node.js version (unless using Appium.app|exe): Tried both Appium.app and node v4.4.3
* Mobile platform/version under test: iOS 9 and 10
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium.app

## Details

It dismisses the pop up on iOS 8 devices
The capabilities that I have for my latest run:
[Appium] Capabilities:
[Appium]   deviceName: 'iPhone 6'
[Appium]   autoAcceptAlerts: true
[Appium]   automationName: 'XCUITest'
[Appium]   browserName: ''
[Appium]   device: 'iphone'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.0'
[Appium]   bundleId: ‘\<BUNDLE_ID>’
[Appium]   udid: ‘\<UDID>’

**Comment by hariskhaliq** [comment]
+1

**Comment by mykola-mokhnach** [comment]
_autoAcceptAlerts_ capability is not implemented for XCUITest. Check https://github.com/appium/appium-xcuitest-driver#usage for the list of currently supported capabilities.

**Comment by mykola-mokhnach** [comment]
@triager please close
