### ISSUE TITLE
Unable to launch app on real device

### ISSUE THREAD

**Issue by mikhailpractice** [appium/appium#7095]
## The problem

Unable to launch app on real device. WebdriverAgent is launching but after that nothing happening.
 In the appium logs get this message "The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability."

BUT after I installed and specified path start getting this message: "ERROR: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent: Error: spawn EACCES"
## Environment
- Appium 1.6
- iOS 10.0

**Comment by mykola-mokhnach** [comment]
It is not possible to advice anything here without capabilities list. Also, having detailed log may help to locate the error source in Appium code.
