### ISSUE TITLE
Unable to get the same Id's in some devices of Android Hybrid Application

### ISSUE THREAD

**Issue by tekisrinivas20** [appium/appium#7098]
Hi team,

I am automating Android Hybrid Application using Appium, while working I am getting the Id's from UIA Automator viewer But I am not getting some of the Id's in one device and some of the Id's not getting in another device, what is the reason both the devices are having same android version and also I have installed all android versions like Android 5.0.1, 5.1.1 and 6.0. And also I have verified in Emulator. Is there any version dependency to get the Id's from UIA automator viewer. Could any one please help on this issue. I am attaching both the device screenshots and Working environment.

Environment

Appium version1_4_16_1
Windows 7 64 bit
Android - 5.1.1
Real device (Samsung 10 inch tablet)
Latest Chrome driver - 2.24
![android_hybridapp_device-1](https://cloud.githubusercontent.com/assets/22059441/19684192/82fb4964-9ad3-11e6-9f7d-68358a1c6503.jpg)
![android_hybridapp_device-2](https://cloud.githubusercontent.com/assets/22059441/19684191/82d8d7b2-9ad3-11e6-9f13-fb3e0d421a2c.jpg)

Thank you.

**Comment by mykola-mokhnach** [comment]
Have you tried newer Appium version?

**Comment by JaniJegoroff** [comment]
Are you talking about `uiautomatorviewer` tool which is part of Android SDK and therefore nothing to do with Appium??

**Comment by tekisrinivas20** [comment]
Thanks for your quick reply. yes, actually in order to Automate android application with Appium, we need to find the elements locators by using uiautomatorviewer tool, or is there any other tool available with appium to locate elements. Could you please explain possible solution for this.

**Comment by jlipps** [comment]
uiautomatorviewer is a good tool. I'm not sure why there would be a discrepancy in what it returns. Unfortunately, we can't provide any assistance on that score :-(
