### ISSUE TITLE
Elements missing from the screen on a native ios10 app with xcode8 and appium1.6

### ISSUE THREAD

**Issue by johnmorrisQADeveloper** [appium/appium#7099]
## The problem

Element is visible on the screen, but not on the page source on DOM, so unable to interact with it.
1. If I run the app on ios9 with xcode7.3 on appium 1.6, i can see the element on the dom and interact with it
2. If I run the app on ios10 with xcode8 on appium 1.6,  I can't see the element on the dom nor interact with the dom

## Environment
* Appium 1.6
* Last Appium version that did not exhibit the issue (if applicable):
* MAC OSX 10.12 Sierra:
* Node.js version v6.8.0
* Iphone 6s with ios10.0.1 
* Appium CLI 

## Details
the app is a web hybrid app, parts of the app are native and parts are in the web view. The element I am trying to interact is a web view element

## Code To Reproduce Issue [ Good To Have ]
It might be similiar to the issue https://github.com/appium/appium/issues/7068 but on ios10 and on  later version.

**Comment by jlipps** [comment]
For a webview element, use the Context API to scope into the Webview, as it says in our [hybrid docs](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/hybrid.md).

The reason there is a change between iOS9 and iOS10 is that the automation system is completely different underneath the hood (see our [XCUITest migration doc](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md)). With iOS9, some (not all) webview elements were included in the native hierarchy. In iOS10, this is no longer the case. But on either platform, the supported way to interact with webview elements is and always has been via the Context API.

**Comment by VasilijSviridov** [comment]
@jlipps , what if contextNames returns only NATIVE_APP? 
getPageSource returns empty XCUIElement:
<XCUIElementTypeWebView></XCUIElementTypeWebView>  which is empty, but app really have more data in webview ?

//get contexts
Set<String> contextNames = driver.getContextHandles();
for (String contextName : contextNames) {
    System.out.println(contextNames); //prints out something like NATIVE_APP \n WEBVIEW_1
}
