### ISSUE TITLE
Timeout when trying to inspect the app

### ISSUE THREAD

**Issue by momojah** [appium/appium#7101]
## The problem

Timeout error when trying to inspect the app.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0
- Last Appium version that did not exhibit the issue (if applicable): 1.5.x
- Desktop OS/version used to run Appium: OSX 10.12
- Node.js version (unless using Appium.app|exe): v6.7.0
- Mobile platform/version under test: 10
- Real device or emulator/simulator: Simulator
- Appium CLI or Appium.app|exe:
## Details

The elements available in my app on a page with a results list can be extreme. In Appium 1.5.x it could take up to several minutes to get the complete list of elements available. In Appium 1.6.0 I am getting a timeout. Can this be changed somehow?
## Link to Appium logs

[1] pry(main)> source
Selenium::WebDriver::Error::UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ETIMEDOUT
from /Users/jhansen/.rvm/gems/ruby-2.2.1/gems/selenium-webdriver-2.47.1/lib/selenium/webdriver/remote/response.rb:71:in `assert_ok'
## Code To Reproduce Issue [ Good To Have ]

Open Appium Ruby Console and type 'source'.
This is working on the other pages in my app I have inspected.

**Comment by mykola-mokhnach** [comment]
This might be caused by known Apple issue. Here's the possible fix: https://github.com/facebook/WebDriverAgent/pull/332

**Comment by momojah** [comment]
@mykola-mokhnach : Great. This seems to have fixed my issue. Thanks a lot.
