### ISSUE TITLE
DRIVER.getKeyboard().sendKeys(Keys.RETURN) enters an emoticon in the text field instead of hitting enter for iOS Simulator with appium 1.6

### ISSUE THREAD

**Issue by IntelloScooby** [appium/appium#7103]
## The problem

The below lines of code enter the "data" in the text field and an emoticon at the end:

`DRIVER.findElementByAccessibilityId(elementID).sendKeys(data);
  DRIVER.getKeyboard().sendKeys(Keys.RETURN);`

This code was working find with appium 1.5.1 and I started getting this issue when moved to appium 1.6

Attaching a screenshot for reference.

![screen shot 2016-10-25 at 10 20 14 am](https://cloud.githubusercontent.com/assets/11371576/19694806/55f39584-9aa6-11e6-8990-76261310f02d.png)
## Environment
- Appium version (or git revision) that exhibits the issue: appium 1.6
- Last Appium version that did not exhibit the issue (if applicable): appium 1.5.1
- Desktop OS/version used to run Appium: macOS Sierra
- Node.js version (unless using Appium.app|exe): Node 6.9.1
- Mobile platform/version under test: iOS Simulator for iPhone 6/ iOS 9.3
- Real device or emulator/simulator: Simulator
- XCode version: XCode 8.0
## Link to Appium logs

https://gist.github.com/IntelloScooby/a026ec4eb040d1745d17b22843d85385
## Code To Reproduce Issue

`DRIVER.findElementByAccessibilityId(elementID).sendKeys(data);
  DRIVER.getKeyboard().sendKeys(Keys.RETURN);`

**Comment by mykola-mokhnach** [comment]
Workaround: You may try to locate the Return button as a normal UI element and click it.

**Comment by imurchie** [comment]
Fixed in latest version of the driver.

**Comment by IntelloScooby** [comment]
Thank you!
