### ISSUE TITLE
iOS 10.1 support

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7105]
Apple just released this. Let's ensure Appium XCUITest works with it.

**Comment by imurchie** [comment]
The beta worked a couple of weeks ago. I'll install and go through with the latest.

**Comment by imurchie** [comment]
Hmph. GA doesn't want to run on my machine.

**Comment by imurchie** [comment]
Got it running. Testing.

**Comment by imurchie** [comment]
iOS 10.1 simulator tests all work. Native app tests work. Currently I am unable to get `ios-webkit-debug-proxy` to connect.

**Comment by pavanbachu0604** [comment]
@imurchie are elements getting clicked in landscape mode ?

**Comment by imurchie** [comment]
@pavanbachu0604 It does not look like it.

**Comment by pavanbachu0604** [comment]
@imurchie in my case it is not able to click the element, but it shows in log that it has clicked on element.

Log file : https://gist.github.com/pavanbachu0604/d2f819070dad7327020caf82c68b5b18

Capabilities:
if(driver==null){
      		   driver = new ThreadLocal<RemoteWebDriver>();
//    	            DesiredCapabilities cap = DesiredCapabilities.internetExplorer();
    	            DesiredCapabilities capabilities = new DesiredCapabilities();
    				capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPad");
    				capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITEST");
    				capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.1");
    				capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS"); //newly added
    				capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 10000);
    				capabilities.setCapability("xcodeConfigFile", "/Users/bachupa/Desktop/Configfile.xcconfig");
    				capabilities.setCapability(MobileCapabilityType.APP, "/Users/bachupa/Desktop/App/UAT_Apps/Retail/16.9.6/POSMobile_NOEMP.app");
//    				capabilities.setCapability(MobileCapabilityType.APP, "com.vzw.pos.posmobile");
//    				capabilities.setCapability("autoDismissAlerts", true);
    				driver.set(new IOSDriver(new URL("http://localhost:4723/wd/hub"),
    						capabilities));






Device: iPad Mini 4
iOS Version: 10.1
Appium: V1.6
Xcode : 8.1 Beta

**Comment by pavanbachu0604** [comment]
@imurchie @jlipps Any update on above issue ? I am not able to proceed any further because of this , I had similar issue in iOS 10 also and it is unsolved

**Comment by imurchie** [comment]
Unfortunately it remains an issue. Apple is aware of it (at least, a bug has been filed with them) but it has not been resolved.

**Comment by mykola-mokhnach** [comment]
I think WDA developers are going to create a workaround for it: https://github.com/facebook/WebDriverAgent/issues/262

This should be transparent to Appium then once it's released.

**Comment by pavanbachu0604** [comment]
@mykola-mokhnach : any idea when can we except this issue to be fixed because my complete application works only in landscape mode and its a big road blocker

**Comment by mykola-mokhnach** [comment]
We do execute our landscape tests on iOS 9.3

**Comment by pavanbachu0604** [comment]
@mykola-mokhnach I am working iOS 10.1 right now so I must make sure things are working on iOS 10.1

**Comment by jlipps** [comment]
This is all working as well as 10.0, except for real device web testing, which we are tracking in another issue: https://github.com/appium/appium/issues/7142

**Comment by testingIOS** [comment]
I would like to know the fix is for landscape mode issue on iOS 10.x or i-w-d-p fix on iOS 10.x simulator?

**Comment by pavanbachu0604** [comment]
@jlipps When is fix planned to be released?

**Comment by pavanbachu0604** [comment]
@jlipps @imurchie  Even in Appium 1.6.1beta, we are not able to click on elements ....

**Comment by jlipps** [comment]
@pavanbachu0604 there is no fix for the landscape + fix issue yet. it's an apple bug.

**Comment by KrishnB** [comment]
@jlipps Does this release support running tests on more than one simulator parallelly?
