### ISSUE TITLE
Unable to install appium on ubuntu 14.0.4

### ISSUE THREAD

**Issue by prateekc71191** [appium/appium#7106]
Hi All,

Facing problem in appium installtion due to npm and nodejs
npm and nodejs package is already installed 
Command: npm install -g appium

Error: 
"> node install-npm.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/babel-core'
npm ERR! error rolling back  appium@1.6.0 { [Error: ENOTEMPTY, rmdir '/home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/babel-core']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/babel-core' }
npm ERR! weird error 127
npm ERR! Error: ENOENT, lstat '/home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/SimShim.dylib'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/pratecha
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/SimShim.dylib
npm ERR! fstream_path /home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7/SimShim.dylib
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, open '/home/pratecha/tmp/npm-4478-J0htEkPO/1477063107259-0.44992291228845716/package/internal/MapCache.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/pratecha
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/pratecha/tmp/npm-4478-J0htEkPO/1477063107259-0.44992291228845716/package/internal/MapCache.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! EEXIST, mkdir '/home/pratecha/tmp/npm-4478-J0htEkPO/1477063113642-0.5848549860529602/package/modules'
File exists: /home/pratecha/tmp/npm-4478-J0htEkPO/1477063113642-0.5848549860529602/package/modules
Move it away, and try again. 

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/pratecha
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/pratecha/tmp/npm-4478-J0htEkPO/1477063113642-0.5848549860529602/package/modules
npm ERR! fstream_path /home/pratecha/tmp/npm-4478-J0htEkPO/1477063113642-0.5848549860529602/package/modules/es7.string.rpad.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/jpeg-js/test/fixtures/tree-cmyk.jpg'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/pratecha
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/jpeg-js/test/fixtures/tree-cmyk.jpg
npm ERR! fstream_path /home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/jpeg-js/test/fixtures/tree-cmyk.jpg
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/appium-uiautomator2-server/app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/pratecha
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/appium-uiautomator2-server/app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
npm ERR! fstream_path /home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/appium-uiautomator2-server/app/src/main/java/io/appium/uiautomator2/model/UiObjectElement.java
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/core-js/client/core.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/pratecha
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/core-js/client/core.js
npm ERR! fstream_path /home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/core-js/client/core.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/request-promise/node_modules/bluebird/js/browser/bluebird.core.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "appium"
npm ERR! cwd /home/pratecha
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/request-promise/node_modules/bluebird/js/browser/bluebird.core.js
npm ERR! fstream_path /home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/appium-base-driver/node_modules/request-promise/node_modules/bluebird/js/browser/bluebird.core.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/home/pratecha/.npm-packages/lib/node_modules/appium/node_modules/appium-android-driver/ApiDemos-debug.apk'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
"'
can someone please provide any solution to fix this or easy way to install appium instead sperately installing all this dependencies. 

Thanks.

**Comment by mykola-mokhnach** [comment]
Is Mr banned from google search: http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu ?

**Comment by imurchie** [comment]
Appium will not work with Node 0.10. Please upgrade to _at least_ Node 4 and Npm 3.

**Comment by mykola-mokhnach** [comment]
@triager please close

**Comment by prateekc71191** [comment]
Thanks @mykola-mokhnach  and @imurchie 
I will try with npm 3 and update this thread.
