### ISSUE TITLE
Running Appium + Protractor + iPhone simulator on macOSX ends with safari opening and navigating to the page but nothing happens after

### ISSUE THREAD

**Issue by EricBlueSav** [appium/appium#7107]
## The problem

After navigating to the page that is requested in the protractor code the iPhone simulator stops executing actions. Protractor and Appium both stall - I'm not sure if they get stuck in a loop of some kind or are just waiting for an action that can't complete.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6.0
- Desktop OS/version used to run Appium: macOS 10.12
- Node.js version (unless using Appium.app|exe): 6.7
- Mobile platform/version under test: iPhone 10.0
- Real device or emulator/simulator: Simulator
- Appium CLI 
## Link to Appium logs

Appium logs [gist](https://gist.github.com/EricBlueSav/bc86df64d56f784f2124dd284950a61c) 
Wedriver logs [gist](https://gist.github.com/EricBlueSav/9f62716204c28773d0c83588f22367cc)
Core Simulator system.log [gist](https://gist.github.com/EricBlueSav/cb1983e5d726283234f3963004935b3e)
## Code To Reproduce Issue [ Good To Have ]

```
  capabilities:
  {
    browserName: 'Safari',
    'appium-version': '1.6',
    platformName: 'iOS',
    platformVersion: '10.0',
    deviceName: 'iPhone 6s',
    realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
  },
```

note: I do not know if I need the realDeviceLogger but it seemed to make no difference with or without it. I tried with and without hardware keyboard checked off as well.

**Comment by jlipps** [comment]
@EricBlueSav thanks for the report. You definitely don't need realDeviceLogger set because you're not running with a real device.

The problem here is that Appium via the remote debugger cannot connect to Safari. Do you have some other app connected to mobile Safari via a remote debugger connection? In the simulator settings, under Safari > Advanced, is "Web Inspector" enabled?

**Comment by EricBlueSav** [comment]
Thanks for the answer. As far as I know nothing else is connected to the remote debugger. I'm not doing any development on the iPhone emulator just spinning it up for automation. Web Inspector is enabled. Whether it was foolish or not I updated to 10.1 a couple days ago. I also updated my web driver from 2.22 to 2.24. I had to reinstall protractor to get webdriver-manager update to properly update to the latest.

I'm still having the same issue though.

**Comment by imurchie** [comment]
Yes, the remote debugger is not finding any working views. Out of curiosity, can you try using the `safariInitialUrl` desired capability, set to some page (e.g., `'http://google.com'`)?

**Comment by EricBlueSav** [comment]
Looks like the same issue.

[debug] [RemoteDebugger] Received app, but expected url ('http://google.com') was not found. Trying again.
[RemoteDebugger] Error: Could not connect to a valid app after 20 tries.

**Comment by mykola-mokhnach** [comment]
Closed as inactive. Please try it with appium@beta and provide the updated log if the issue still happens
