### ISSUE TITLE
Unavailable to click the button in Landscape mode

### ISSUE THREAD

**Issue by baliand** [appium/appium#7109]
## The problem

Can't click on ui button in Landscape mode

## Environment

* Appium 1.6.0 - appium@1.6.0
* Desktop OS/version used to run Appium: OS X 10.11.6
* Node.js version (unless using Appium.app|exe): v 6.2.0
* Mobile platform/version under test: iOS 10.0.2
* Real device : iPhone 6S

## Details
When iPhone in Landscape mode I can't click on button. For portrait mode all buttons are clickable and I can click on button.

## Code To Reproduce Issue
driver.rotate(ScreenOrientation.LANDSCAPE);
driver.findElement(By.id("Close")).click();

**Comment by mykola-mokhnach** [comment]
This is known issue, which cannot be fixed because of a bug in Apple's XCTest framework. Check https://github.com/appium/appium/issues/6994 for references.

**Comment by mykola-mokhnach** [comment]
@triager please close

**Comment by baliand** [comment]
@mykola-mokhnach Ok. 
So How Can I click button in landscape mode? Do you have some temporary solution?

**Comment by mykola-mokhnach** [comment]
Calculate coordinates manually and click by coordinates

**Comment by baliand** [comment]
@ I made that 
WebElement uiElement = iosAPI.getWebElement(webDriver, null, moreOptButtonLocator);
*int x = uiElement.getLocation().getX() + 10;
int y = uiElement.getLocation().getY() + 10;
driver.tap(1, x, y, 1000);*
but it doesn't work.

**Comment by mykola-mokhnach** [comment]
Try to exchange x and y

**Comment by baliand** [comment]
I tried. No change.

**Comment by baliand** [comment]
@mykola-mokhnach  I found solution. Thanks

**Comment by mykola-mokhnach** [comment]
@baliand you can share your solution here as well. Probably, it could be useful for other readers.

**Comment by maesiva** [comment]
Adding an offset of 10 or exchanging x,y values didn't work. 
Locking the device Orientation to Portrait in the Side Switch didn't work either.
@baliand please share your workaround.

**Comment by dsavchenkov** [comment]
Hello, i have another problem in Landscape orientation - i can't click on alert, but i can do it in Portrait mode. Better to have a separate problem?

**Comment by mykola-mokhnach** [comment]
@dsavchenkov Known XCTest [issue](https://github.com/facebook/WebDriverAgent/issues/300). Unfortunately it does not respect landscape orientation

**Comment by dsavchenkov** [comment]
@mykola-mokhnach Thanks for the reply

**Comment by devqa-investing** [comment]
Did anyone find a solution for this issue?

**Comment by Ip2507** [comment]
Hi,

In Ipad, I'm able to click back arrow of our application in portrait orientation, And when we rotate in a landscape , and clicking the same back button doesn't work properly

Can anyone suggest the answer?
