### ISSUE TITLE
Where can I get a link for download Appium Client 1.6 ?

### ISSUE THREAD

**Issue by albka1986** [appium/appium#7111]
Where can I get a link for download Appium Client 1.6 ?

Can I use the environment for testing: 
- Iphone 5  (iOS 10.0.2 )
- Xcode 8

**Comment by mykola-mokhnach** [comment]
Appium 1.6 can be installed either from npm repository or built from sources. No other packages are available for now. BTW, this is a place for issue reports. Please ask your question on Appium forum.

@triager please close
