### ISSUE TITLE
findElements ByXpath returns empty list when using atribute comparisons

### ISSUE THREAD

**Issue by levibalint** [appium/appium#7112]
## The problem

I am trying to find a list of elements that are currently within a certain portion of the device's screen. For this I am using an xpath that checks whether the **y** attribute of the tag is between certain limits (for ex. [@y > 0][@y < 500])

When I use such an xpath, appium doesnt return any elements in spite of how the xml looks when getting the page source.

Similarly, there is a problem when using contains (for ex. [@label[contains(.,'part-of-label')]] ) 
but there is no problem with detecting elements where the attribute is exactly something ([@label="some-label"]) 
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6
- Last Appium version that did not exhibit the issue (if applicable): 1.5.3
- Desktop OS/version used to run Appium: OS X El Capitan 10.11.6
- Node.js version (unless using Appium.app|exe): v6.8.1
- Mobile platform/version under test: ios10
- Real device or emulator/simulator: real device
## Details

When using any 3rd party xpath validator or the [ios inspector](https://github.com/mykola-mokhnach/Appium-iOS-Inspector/blob/master/README.md), I do find the elements without a problem.
## Appium logs (relevant lines at least)

`[HTTP] --> POST /wd/hub/session/50e7a29d-c65a-49f0-a06f-55d2f1742713/elements {"using":"xpath","value":"//XCUIElementTypeCell[@y < 500]"}`
`[MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementType...`
`[debug] [XCUITest] Executing command 'findElements'`
`[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id`
`[XCUITest] Rewrote incoming selector from '//XCUIElementTypeCell[@y < 500]' to '//XCUIElementTypeCell[@y < 500]' to match XCUI type. You should consider updating your tests to use the new selectors directly`
`[debug] [BaseDriver] Waiting up to 0 ms for condition`
`[JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/B0B1E4B2-7EA8-4887-B882-0482112FA81C/elements] with body: {"using":"xpath","value":"/...`
`[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"B0...`
`[MJSONWP] Responding to client with driver.findElements() result: []`
## Code To Reproduce Issue (java)

@iOSFindBy(xpath = "//XCUIElementTypeCell[@y < 500]")
 public List<MobileElement> elements;

//or try finding elements directly with:
//elements = appiumDriver.findElementsByXPath("//XCUIElementTypeCell[@y < 500]");

// then use it like:
elements.get(0).click();
## XML i am trying to find the element(s) in (you should find 2 using the xpath above)

https://gist.github.com/levibalint/4a9484e46bdc74d4e4a6422a61681671
## Note

I've also looked through the appium issue list to find a similar problem but found nothing concrete.

**Comment by mykola-mokhnach** [comment]
WebDriverAgent framework does not include element size into the xml tree, so you cannot rely on this. They are only visible in the tree, which is generated by Appium for your convenience. What you can try - get all elements with corresponding tag names (XCUIElementTypeCell) and then extract their locations using _getLocation_ method of WebElement/IOSElement object.

**Comment by levibalint** [comment]
@mykola-mokhnach I see, i did not know that :), thanks. We could try using getLocation(), sure.

Now that I think about it, the source of the problem seems to be different for size/location than when I try to get "//XCUIElementTypeCell[@label[contains(.,'part-of-label')]]" 
(which also doesnt return any elements)

Any idea why that doesn't work? 
(also, should I open a separate issue for that?)

**Comment by mykola-mokhnach** [comment]
Check https://github.com/facebook/WebDriverAgent/blob/6813e2549b684379e1b6a6ee96deb2b42f4e1a85/WebDriverAgentLib/Categories/XCElementSnapshot%2BFBHelpers.m method _XMLElementFromElement_ to know for sure which xml attributes are available for lookup. 

Regarding your xpath: try to change it to 

```
//XCUIElementTypeCell[contains(@label, 'part-of-label')]"
```

**Comment by baliand** [comment]
@mykola-mokhnach Hi. I have the same problem but with XCUIElementTypeCollectionView
I tried to get child elements. 
driver.findElements(MobileBy.xpath("//XCUIElementTypeCollectionView/*"));
second variant:
WebElement collection = driver.findElements(MobileBy.className("XCUIElementTypeCollectionView"));
collection..findElements(MobileBy.xpath("./*"))

but I all time get timeout 240.
and list is empty

```
<XCUIElementTypeCollectionView enabled="true" valid="true" visible="true">
  <XCUIElementTypeStaticText enabled="true" valid="true" visible="true">
          <XCUIElementTypeButton enabled="true" valid="true" visible="true"></XCUIElementTypeButton>
          <XCUIElementTypeStaticText enabled="true" valid="true" visible="true"></XCUIElementTypeStaticText>
          <XCUIElementTypeStaticText enabled="true" valid="true" visible="true"></XCUIElementTypeStaticText>
          <XCUIElementTypeStaticText enabled="true" valid="true" visible="true"></XCUIElementTypeStaticText>
          <XCUIElementTypeStaticText enabled="true" valid="true" visible="true">   </XCUIElementTypeStaticText>
  </XCUIElementTypeStaticText>
<!-- XCUIElementTypeStaticText more than 250 -->
</XCUIElementTypeCollectionView>
```

**Comment by mykola-mokhnach** [comment]
@baliand Try not to use xpath locators at all with the current WDA implementation, especially if your UI tree is big enough. Redesign your location strategy. Is it really necessary to get all these 100 text fields?

**Comment by baliand** [comment]
@mykola-mokhnach I would like to not use xPath but I have not so much ID or I can't to use ID because it's name of photography(is can be any name).
Before iOS 10 and XCUITest I used UIAutomator. I was expecting to be able to modify UIAutomation on xPath

**Comment by mykola-mokhnach** [comment]
@baliand you can still assign ids to these elements since they are not supposed to be visible anywhere in UI. You can even assign the same id to all photos and put the actual text in _label_ or _value_ property.

**Comment by baliand** [comment]
@mykola-mokhnach Ok. 
I have question. 
When I used  this 
WebElement element =driver.findElements(MobileBy.className("XCUIElementTypeCollectionView"));
List<WebElement> list = element.findElements(MobileBy.className("XCUIElementTypeStaticText"));
 I expect list witch contain child elements from XCUIElementTypeCollectionView. Why element.findElements returns child from child. 
For example:
XCUIElementTypeCollectionView contains 50 elements of XCUIElementTypeStaticText, I want to get 50 elements. But I get more than 50 elements of XCUIElementTypeStaticText because XCUIElementTypeStaticText contains a few XCUIElementTypeStaticText.

**Comment by mykola-mokhnach** [comment]
@baliand Because this is the way it works. _findElements_ is always looking for descendants of the current element (the root element itself is also included), but not only for children.

Regarding lazy developers - you can add these accessibility ids yourself. It's easy like assigning a variable.

**Comment by baliand** [comment]
@mykola-mokhnach How? I don't have access to code.

**Comment by levibalint** [comment]
I think this can be closed, since I rewrote the part where I used xpath and now we find elements based on weight/height and position using getLocation() >> thanks for the tip!

the more elaborate xpath (contains[]) still doesn't work though.
