### ISSUE TITLE
ios-webkit-debug-proxy-launcher.js requires an iOS 10 device to manually open Safari before connecting to it

### ISSUE THREAD

**Issue by codedgeass** [appium/appium#7115]
## The problem

iOS Webkit Debug Proxy will not connect to my iOS 10 device when launching the proxy through Appium's supplied _ios-webkit-debug-proxy-launcher.js_. Executing 
`node ios-webkit-debug-proxy-launcher.js -c <UDID>:27753 -d` 
outputs 
`RUNNING: ios_webkit_debug_proxy -c <UDID>:27753 -d` 
and there is no more output after that. Once I manually open Safari on my device, then the usual output that shows a device is connected will be appended to stdout. If I run the proxy directly without this Javascript file, e.g. 
`ios_webkit_debug_proxy -c <UDID>:27753 -d`, 
it works fine. If I connect an iOS 9 device and run the proxy the same way as before using the Javascript file, it works fine.
## Environment
- Appium version (or git revision) that exhibits the issue: **1.6.0**
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: **Mac 10.11.6**
- Node.js version (unless using Appium.app|exe): **6.9.1**
- Mobile platform/version under test: **iOS 10.0.2**
- Real device or emulator/simulator: **Real device**
- Appium CLI or Appium.app|exe: **Appium CLI**
## Details

I am on a work computer and am locked out of `/usr/bin/env`. Therefore, I need to explicitly specify the `node` command when running the Javascript file. I am not certain what effect this has, if any. I've tried removing the shebang line specifying to use node at the top of _ios-webkit-debug-proxy-launcher.js_ but that did not help.
## Link to Appium logs

Part of the problem is I'm not receiving any logs.
## Code To Reproduce Issue [ Good To Have ]

`node ios-webkit-debug-proxy-launcher.js -c <UDID>:27753 -d`

**Comment by jlipps** [comment]
@codedgeass it was as little hard to know whether this actually works, or doesn't, based on your report. What's wrong exactly? the iwdp launcher doesn't do what it's supposed to? Or it's not showing the logs you might expect from running iwdp directly?

**Comment by codedgeass** [comment]
@jlipps Thanks for looking at this. As far as I can tell, the proxy is not connecting to the phone. I am having a similar issue with _main.js_. When I run `node main.js` I get the error 

```
import { init as logsinkInit } from './logsink';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

But when running it through the `appium` command in `/usr/local/bin` it runs fine. Could this  have something to do with my `/usr/bin/env` restricted access?

**Comment by imurchie** [comment]
The issue with running `node main.js` is that the file you want to run is the _transpiled_ version, which is `build/lib/main.js`.

**Comment by codedgeass** [comment]
Upon starting IWDP, output to logs pauses after the first line:

> RUNNING: ios_webkit_debug_proxy -c <UDID>:27753 -d

Note, Appium is able to open Safari on the device during this period. Output will continue upon pointing a browser to _localhost:27753_ or when Safari is opened on the physical device (manually or through Appium). The iwdp does perform as expected despited the output being "delayed". I'll close this out since it's a minor quality of life change at best and I'm uncertain what the expectations are for the debugger.
