### ISSUE TITLE
Unable to run Windows app automation with Appium

### ISSUE THREAD

**Issue by kirankumar4vr** [appium/appium#7116]
## The problem

I'm trying to run windows app automation with latest appium that is running successfully with winappdriver. Appium is looking for xcode on windows device even after providing proper platformName and deviceName in the desired capabilities. Also, showing "iOS" as platformName in the logs
## Environment
- Appium version (or git revision) that exhibits the issue: V1.6.0
- Last Appium version that did not exhibit the issue (if applicable): NA
- Desktop OS/version used to run Appium: windows 10
- Node.js version (unless using Appium.app|exe): V6.9.1
- Mobile platform/version under test: windows 10
- Real device or emulator/simulator: Real
- Appium CLI or Appium.app|exe: CLI
## Link to Appium logs

https://gist.github.com/kirankumarb4u/14ba7ab8faf9185f21a37d879786af01
## Code To Reproduce Issue

protected static IOSDriver<IOSElement> AppSession;
appCapabilities.SetCapability("app", "Pearson.PSC_tk9qhwb5jzw48!App");
appCapabilities.SetCapability("platformName", "Windows");
appCapabilities.SetCapability("deviceName", "WindowsPC");
AppSession = new IOSDriver<IOSElement>(new Uri(WindowsApplicationDriverUrl), appCapabilities);

**Comment by SrinivasanTarget** [comment]
@kirankumarb4u https://gist.github.com/kirankumarb4u/14ba7ab8faf9185f21a37d879786af01#file-windowsappautomation-appium-L12
Give appropriate platform name and try.

**Comment by kirankumarb4u** [comment]
@SrinivasanTarget MobileCapabilityType  is also giving the same result as with the strings "platformName", "Windows"
