### ISSUE TITLE
Implement 'back' function for XCUITestDriver

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#7118]

**Comment by imurchie** [comment]
Does https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/navigation.js#L6-L11 not work?

**Comment by dpgraham** [comment]
It only works in a web context

**Comment by imurchie** [comment]
Ah. True. We used to use the UI Automation method `back` but there is nothing like that in XCTest. Alas.

**Comment by jlipps** [comment]
@imurchie I looked into it and the "UI Automation method `back`" is actually a hacky little script that we own in appium-uiauto. So it should be possible to reimplement in appium-xcuitest-driver or webdriveragent.

**Comment by imurchie** [comment]
Yeah. I've implemented it. Waiting for CI.
