### ISSUE TITLE
Abndroid Native App Testing - Fragments - Unable to locate elements

### ISSUE THREAD

**Issue by SergioLeone** [appium/appium#7119]
## The problem

Not able to locate elements of Fragments.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.5.3
- Last Appium version that did not exhibit the issue (if applicable): NA
- Desktop OS/version used to run Appium: MacOS 10.12
- Node.js version (unless using Appium.app|exe): 6.9.1
- Mobile platform/version under test: Android 4.4.2 | Android 5.0
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: App
## Details

I have opened an issue here: https://github.com/appium/appium/issues/7068
Now, talking with our developers I have more info and I realized it's because of their new implementation - they are using Fragments to develop the apps now.

So the issue is that appium can not locate elements on the screen and/or locates incorrect elements when you change screens(views).

I tried to look for a way to refresh the view, but I don't think there is anything like this. 
## Link to Appium logs

NA
## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by JaniJegoroff** [comment]
How does element tree looks like in `uiautomatorviewer`? How you are trying to find elements, what locator strategy you are using?

**Comment by Ser-Gius** [comment]
I've tried id's and xpath's - both give the same results.

PFA screenshot of uiautomatorviewer element tree.

![screen shot 2016-10-27 at 15 14 59](https://cloud.githubusercontent.com/assets/22973227/19762600/42f31a78-9c58-11e6-9554-7fa11703a36f.png)


Also, as I described in the previous issue, what happens is this:
1. After the initial launch of the app - the elements are located fine on the Home Screen of the app, I can get xml with .getPageSource() and so on.
2. After I navigate to any other page, the xml with .getPageSource() returns blank, I can not locate elements with id or xpath locators

**Comment by Ser-Gius** [comment]
And, for example I navigate somewhere from Home Screen (using Appium Inspector)
Then I open Navigation Drawer and navigate back to Home Screen
Then I see again what elements I have on Home Screen navigating through the layouts of the Inspector (the Inspector refreshes automatically all the time I'm doing some actions). So now the elements tree will be incorrect - I can see that when I select some layout it highlights incorrect elements and if I tap on something in Inspector screen, then Inspector crashes.
But if I refresh the inspector manually, then it will show the correct tree

**Comment by Ser-Gius** [comment]
others have also reported same issue: https://discuss.appium.io/t/dealing-with-fragments/4906

It's strange that Appium would not support this implementation. Anyone knows a workaround? Struggling for a week now trying to make it work...

**Comment by ibizaman** [comment]
Sorry for simply "bumping", but I'm struggling with this myself.

**Comment by jlipps** [comment]
I'm having trouble understanding this issue. Are you saying that you can see elements in uiautomatorviewer that Appium isn't able to find?

**Comment by SergioLeone** [comment]
For me this was exactly the case.
However, switching to appium 1.6 and using uiautomator2 solved the issue.

**Comment by jlipps** [comment]
Excellent. Closing this issue then as that is what we currently support. @ibizaman feel free to open a new issue if you're experiencing bad behavior on Appium 1.6 + the uiautomator2 automation backend.

**Comment by GustavoPS10** [comment]
Why has the fragments not been addressed ? It's April 2018 and still appium isn't able to tap/click elements inside fragments.

**Comment by nimeshbhatt** [comment]
I was facing the same issue but works fine now.
Just add one another capability that is "**caps.setCapability("automationName", "UiAutomator2");**" and make sure you have appium version greater than or equal to 1.6.0

**Comment by Jeeveshk** [comment]
@nimeshbhatt I tried using the capabilities you mentioned but then I ended up facing a different error which seems to be related to proxy. Did you as well face any similar sort of problem, if so can you please let me know how to fix it?
I update the UiAutomator 2 as well but the issue pertained
Can you please tell me how did you locate the element, did you have to switch to frames even after adding the capabilities
