### ISSUE TITLE
Unable to create session in emulator

### ISSUE THREAD

**Issue by kiran-meda** [appium/appium#7120]
## The problem
Unable to create session as it is unable to find emulator
A new session could not be created. (Original error: Could not find Sample emulator.) (33)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 6.0
* Real device or emulator/simulator: Emulator Nexus 6
* Appium CLI or Appium.app|exe:

## Details

I am trying to run appium test against emulator. I am getting an error that unable to create session.

## Link to Appium logs

https://gist.github.com/kiran-meda/07dda5f930fadb4b5a332a070b23d05b

## Code To Reproduce Issue [ Good To Have ]

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            DesiredCapabilities capabilities = DesiredCapabilities.Android();
            capabilities.SetCapability(MobileCapabilityType.BrowserName, "Chrome");
            capabilities.SetCapability(MobileCapabilityType.DeviceName, "generic_x86_64");
            capabilities.SetCapability(MobileCapabilityType.PlatformVersion, "6.0");
            capabilities.SetCapability(AndroidMobileCapability.Avd, "Sample");
            capabilities.SetCapability(AndroidMobileCapability.AppPackage, "com.android.chrome");

            capabilities.SetCapability("udid", "emulator-5554");
            AndroidDriver<AndroidElement> driver = null;

            try
            {
                driver = new AndroidDriver<AndroidElement>(new Uri("http://127.0.0.1:4723/wd/hub"), capabilities, TimeSpan.FromSeconds(180));
                driver.Navigate().GoToUrl("https://10.41.71.242");

                IWebElement ele = driver.FindElement(By.Id("UserName"));
                ele.SendKeys("retailuser");

                driver.Quit();

            }
            catch (Exception Exception){ }
        }
    }
}

**Comment by imurchie** [comment]
Appium 1.4.16 does not support Android 6, unfortunately.

**Comment by mykola-mokhnach** [comment]
@triager please close
