### ISSUE TITLE
Implement performTouch for XCUITestDriver

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#7121]
https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/gesture.js

'performTouch' isn't supported yet. It hits the 'NotYetImplementedError'.

**Comment by imurchie** [comment]
Can you be more specific about the error you're getting? `performTouch` is implemented, though not every part of what was before. https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/gesture.js#L24

**Comment by ReaLau** [comment]
Hi @imsardine I met the same problem too, in my side it shows no error message, but looks like it keeps doing something with no specify effects on UI:
MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"y":600,"x":300}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"y":-300,"x":0}},{"action":"release","options":{}}],"2eb01894-4dc0-4f55-a499-ef14b2443009"]
[debug] [XCUITest] Executing command 'performTouch'
[JSONWP Proxy] Proxying [POST /uiaTarget/0/dragfromtoforduration] to [POST http://localhost:8100/session/BF5BA444-A5E5-4863-AF25-8998E006012A/uiaTarget/0/dragfromtoforduration] with body: {"fromX":300,"fromY":600,"toX":300,"toY":300,"duration":1}
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
.......................


my appium version is 1.6.0(beta3), xcode 8.0, hybird app(most of the app pages inside are webview), appium-python-client.
I just tried this script: driver.swipe(300, 600, 0, -300), which means swipe from down(300, 600) to up(300, 300 ) if I do not make any misunderstanding.

Please have a check on this, much appreciated. :)

**Comment by ReaLau** [comment]
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...

it keeps showing this log and seems no end.

**Comment by ReaLau** [comment]
![image](https://cloud.githubusercontent.com/assets/19317322/19801253/0c089e14-9d31-11e6-8570-cfa471953aad.png)
this is the screenshot at that time.
I have successfully sign in app and access this screenshot page with some other script, but every time I gets this situation above:  no error shows out and no changes on app UI even it seems like the swipe action has been done via log. Please help.

**Comment by dpgraham** [comment]
The error is 'Selenium error: Support for gestures other than Tap is not yet implemented. Please contact an Appium dev'. It's not meeting any of the conditions defined in 'performTouch' https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/gesture.js#L24

**Comment by dpgraham** [comment]
The error I encountered was in my test script. It was sending a tap action and then a release action and it wasn't registering as a touch event because the release action is redundant (a tap is a 'press' and 'release' performed quickly).

@ReaLau it looks like performTouch is working correctly for you and the issue you're having is with the server locking up. Could you create a new issue?

**Comment by ReaLau** [comment]
@dpgraham  OK, I'll create a new issue. my bad:)

**Comment by dpgraham** [comment]
No problem. Thanks @ReaLau!
