### ISSUE TITLE
Error: simctl error running 'create': Invalid device type: iPhone Simulator (8.1 Xcode and 1.6 Appium)

### ISSUE THREAD

**Issue by rafalf** [appium/appium#7126]
## The problem

I am seeing this error, unsure what's causing it. I upgraded to 8.1 yesterday but cannot tell if that's the problem as i have never before tried out running apps only Safari.

Safari boots up good with Simulator tho.
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6
- Last Appium version that did not exhibit the issue (if applicable): don't know
- Mobile platform/version under test: IPhone 6
- Real device or emulator/simulator: iOS Simulator 
- Appium CLI or Appium.app|exe: cli  

## Details

While running this piece of code:

`
class SafariTests(unittest.TestCase):

```
def setUp(self):
    desired_caps = {
        'deviceName': 'iPhone Simulator',
        'platformName': 'iOS',
        'automationName':'XCUITest',
        'app':'/Users/rafalfusik/Desktop/UICatalog.app',
        'nativeWebTap': True,
        'newCommandTimeout':'120' # timeout for a new command
        # 'fullReset':True,          # to avoid double launch
    }

    self.driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

def tearDown(self):
    self.driver.quit()

def test_home(self):

    windows_size = self.driver.get_window_size()
```

`
## Link to Appium logs

[Logs on gist](https://gist.github.com/rafalf/2c66636e16dcf03e72172e1cca1c1c5a)
## Code To Reproduce Issue [ Good To Have ]

Run the python script 
## the following runs w/t any issue.

`desired_caps = {
            'browserName': 'safari',
            'platformName': 'iOS',
            'platformVersion': '10.1',
            'deviceName': 'iPhone Simulator',
            'nativeWebTap': True,
            'automationName':'XCUITest',
            'newCommandTimeout':'120', # timeout for a new command
            'fullReset':True,          # to avoid double launch
            #'safariIgnoreFraudWarning': True
        }`

 **also this works fine:**
xcrun simctl install booted /Users/rafalfusik/Desktop/UICatalog.app

**Comment by mykola-mokhnach** [comment]
Try to set more specific deviceName in capabilites. Use the

```
xcrun simctl list
``` 

command to get the list of available simulated device names.

**Comment by rafalf** [comment]
Now, i am getting this error:
[Iphone 6 - gist](https://gist.github.com/rafalf/9f0cebe0e19a57918c59881c178686b1)

        desired_caps = {
            # 'deviceName': 'iPhone Simulator',
            # 'deviceName': 'iPhone 6',
            'platformName': 'iOS',
            'automationName':'XCUITest',
            'app':'/Users/rafalfusik/Desktop/UICatalog.app',
            'newCommandTimeout':'120',
            'showXcodeLog':True
          }


appium started as `appium --device-name 'iPhone 7'`

**Comment by mykola-mokhnach** [comment]
I think the error message there is clear - set the _platformVersion_ capability

**Comment by rafalf** [comment]
It did the trick, many thanks for that. So both needs to be set:
__deviceName__ as a specific device and __platformVersion__
btw whats clear for your not necessarily clear to me, log could be more descriptive  ;)
-- XCUI was logging 'Using latest version 10.1'

`[XCUITest] No platformVersion specified. Using latest version '10.1'
[simctl] Error: simctl error running 'create': Invalid runtime: undefined
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at simCommand$ (lib/simctl.js:22:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)`

**Comment by rafalf** [comment]
this can be closed now

**Comment by imurchie** [comment]
Thanks for bringing to our attention that the error is confusing. I've added a line to the logs to indicate that it might cause problems. https://github.com/appium/appium-xcuitest-driver/pull/274

**Comment by Thirudhas** [comment]
Hi,
Anyone help me on the below issue:
I am trying to launch safari browser in iOS real device. but while executing I am getting the below mentioned error.

**simctl error running 'create': Invalid device type: iPhone**

**Comment by avrahamShutterFly** [comment]
I got  the same problem "Error: simctl error running ‘io’: Invalid device:***"
its happen only when I used SWIPE function, #imurchie can you help me?
