### ISSUE TITLE
different behavior between 1.4 and 1.6 - touch doesn't save

### ISSUE THREAD

**Issue by rafalf** [appium/appium#7127]
## The problem

This is working fine with appium 1.4 ( UI ) . Basically the test selects time and then touches on OK that saves the time
However it doesnt get saved with 1.6 Appium ( CLI) 
## Environment
- Appium version (or git revision) that exhibits the issue: 1.6
- Last Appium version that did not exhibit the issue (if applicable): 1.4
- Mobile platform/version under test: Android 5.1.1
- Real device or emulator/simulator: Emulator 
- Appium CLI or Appium.app|exe: CLI
## Details

Describe in more detail the problem you have been experiencing, if necessary.
## Link to Appium logs

[pass gist](https://gist.github.com/rafalf/27a6f4fcb1d04c0a3993c2dd45aa086c)
[fail gist](https://gist.github.com/rafalf/67a37d4d25c51e9b20b6116e9eaa7f2f)
[android-the clock](http://testprojects.co/static/img/postimg/androidIssue.png)

the following seems different:
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.performTouch() result: null
## Code To Reproduce Issue [ Good To Have ]

Touch, long press on time and then touch on OK

**Comment by tomliuxin** [comment]
which Android version you used? 7.0 or 6.0 or?

**Comment by rafalf** [comment]
5.1.1 (API 22)

**Comment by imurchie** [comment]
Which of the commands is the one that is not doing what you want? There are too many touch actions in the logs to tell which is which at the moment.

**Comment by rafalf** [comment]
@imurchie 
i believe it's failing on the last touch ( click ) 
[appium log](https://gist.github.com/rafalf/a039a032c3d2f58171a23dccf71e846f)
[adv logcat](https://gist.github.com/rafalf/23c02967b1e3dafcc428f27d0375d63d)

**Comment by rafalf** [comment]
and this is in 1.4 ( pass )
[adb logcat](https://gist.github.com/rafalf/e48ffbf619fd246d4b05f775ffbeeb8a)

**Comment by rafalf** [comment]
I tried out 2 different locators:
by id - `el = WebDriverWait(self.driver, 2).until(EC.presence_of_element_located((By.ID, 'com.nineteenthmile:id/ok')))`
by xpath - el =`self.driver.find_element_by_xpath("//android.widget.Button[@text='OK']")`
`action.tap(el).perform()`

Both are failing with appium 1.6.

**Comment by dpgraham** [comment]
I don't think we can fix this. It doesn't seem to be producing any errors.
