### ISSUE TITLE
Unable to find GeneralServerFlag.UIID in java-client-4.1.2.jar

### ISSUE THREAD

**Issue by surikiran** [appium/appium#7130]
## The problem
Unable to find GeneralServerFlag.UIID in java-client-4.1.2.jar when trying to start appium server programmatically using AppiumServiceBuilder class 
## Environment

* Appium version --- 1.4.16.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): v0.12.7
* Mobile platform/version under test: Android 4.4.2,5.0.2,4.3,5.0
* Real device or emulator/simulator: GalaxyNote III, Tab A, Tab3, NoteIII
* Appium CLI or Appium.app|exe: java-client-4.1.2.jar,gson-2.7.jar

## Details

I am planning to start appium server programmatically using AppiumServiceBuilder class by following the instructions from the link https://github.com/saikrishna321/TestNGParallelThreads/blob/master/src/test/java/com/test/classes/AppiumServer.java#L43. Surprisingly when I try to give the value of device ID I am not able to get the value of GeneralServerFlag.UIID when I try to check for existing values in GeneralServerFlag class I unable to find UIID. I need this value to start the service of my appium server. If I don't supply this value parallel execution will not happen but the script will execute in only one device which is recognized by adb(information from lots of forums) hence I desperately need the value of UIID. I found an alternative of starting appium server through commands but I am not interested as AppiumServiceBuilder/AppiumDriverLocalService seems to work excellent in all environments for the concept of starting appium server programatically. I tried to find the content of  java-client-4.1.2.jar but unable to find alternative for UIID hence someone please provide a solution as I have been completely stuck here

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

service = AppiumDriverLocalService.buildService ( new AppiumServiceBuilder ( ).usingDriverExecutable ( new File (
			                         appiumInstalledDirectory +
			                              File.separator + "node.exe" ) )
			     .withAppiumJS ( new File (
			                              appiumInstalledDirectory +
			                                   File.separator + File.separator + "node_modules" + File.separator + "appium" + File.separator + "bin" + File.separator + "appium.js" ) )
			     .withIPAddress ( AppiumServiceBuilder.DEFAULT_LOCAL_IP_ADDRESS )
			     .usingPort ( Integer.valueOf ( port ) )
			     .withArgument ( GeneralServerFlag.SESSION_OVERRIDE )
			     .withArgument ( AndroidServerFlag.BOOTSTRAP_PORT_NUMBER ,
			          AppiumServerStartStop.nextFreePort ( )
			               .toString ( ) )
			     .withArgument ( GeneralServerFlag.LOG_LEVEL ,
			          "debug" )
			     .withLogFile ( new File (
			                              new File (
			                                                       classpathRoot , File.separator +
			                                                            "log" ) , "androidLog.txt" ) ) ) ;

**Comment by mykola-mokhnach** [comment]
Is it possible to try it with the most recent node and Appium versions?

**Comment by jlipps** [comment]
This sounds like a java-client issue rather than a server issue. If so, please report it at that project's issue tracker instead.

**Comment by saikrishna321** [comment]
@surikiran its moved to MobileCapabilityType, you can set it as 

```
capabilities.setCapability(MobileCapabilityType.UDID, "232434jhjkhjk4343");
```

**Comment by saikrishna321** [comment]
@jlipps @SrinivasanTarget this can be closed

**Comment by mykola-mokhnach** [comment]
@triager please close

**Comment by surikiran** [comment]
Due to some internet problem I not able to view your replies. saikrishna321 I agree that this has been moved to mobilecapability but when I am trying to design a logic from your post I have been araising with an exception due to which I am not able to pass the value of UDID to appium server hence unable to execute parallel using appium service as I am completely new to automation and java programming can someone help me how this issue can be solved i.e I want to send the value of UDID to the method .withArgument() of AppiumServiceBuilder class so which location of my code I can pass the value of UIID as when I call the method .withArgument(Capabilities.getCapability(MobileCapability.UDID,"UDIDParameter")) I am getting exception where the execution is stopping but no exception message is displayed in the console hence somebody please help me to solve this issue.

**Comment by saikrishna321** [comment]
@surikiran the repo your trying is just a sample test to reproduce a deadlock issue on parallel run. So don't try to run that ..

**Comment by surikiran** [comment]
this is fine @surikiran then how can I send the value of UDID to AppiumBuildService class so as to create Appium service programatically..........can someone including SaiKrishna in this forum help me to solve this issue.
