### ISSUE TITLE
/wd/hub/session/:sessionId/rotation implementation

### ISSUE THREAD

**Issue by SrinivasanTarget** [appium/appium#7131]
Implement endpoint ```/wd/hub/session/:sessionId/rotation``` in below drivers,

- [x] XCUITest/WDA
- [x] UIAutomator2 
- [ ] Legacy iOS Driver
- [ ] Legacy android Driver

@sravanmedarapu @imurchie FYI

https://github.com/appium/appium-base-driver/blob/master/lib/mjsonwp/routes.js#L178

**Comment by TikhomirovSergey** [comment]
Yes. I think we need it for new modes (XCUITest/WDA, UIAutomator2) at least. It would be cool if old automation modes coulsd support it.

**Comment by sravanmedarapu** [comment]
Sure @SrinivasanTarget .

From [WDA ](https://github.com/rafael-chavez/WebDriverAgent/blob/5382290c269edcc1a46d7d59fa90d15dad10d9df/WebDriverAgentLib/Categories/XCUIDevice%2BRotation.m#L37) implementation could see end point supports `UIDeviceOrientationFaceUp` and `UIDeviceOrientationFaceDown`,  seems setting these orientations are not possible in android.

**Comment by SrinivasanTarget** [comment]
I personally didn't test those on iOS yet. Will test and update soon. Does
rest can be implemented for Android?

**Comment by bootstraponline** [comment]
It looks like Android supports [quite a few different orientation modes](https://developer.android.com/guide/topics/manifest/activity-element.html).
```
android:screenOrientation=["unspecified" | "behind" |
                                     "landscape" | "portrait" |
                                     "reverseLandscape" | "reversePortrait" |
                                     "sensorLandscape" | "sensorPortrait" |
                                     "userLandscape" | "userPortrait" |
                                     "sensor" | "fullSensor" | "nosensor" |
                                     "user" | "fullUser" | "locked"]
```

and [for getting:](https://developer.android.com/reference/android/view/Surface.html).

```
ROTATION_0
ROTATION_180
ROTATION_270
ROTATION_90
```

Appium is suppose to follow [the mobile spec](https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md#device-rotation) which is different from just exposing the native rotation primitives.

**Comment by sravanmedarapu** [comment]
As Android supporting limited Orientations, possible combinations would be

Portrait : `{"x" : 0, "y" : 0, "z" : 0}`
PortraitUpsideDown : `{"x" : 0, "y" : 0, "z" : 180}`
LandscapeLeft : `{"x" : 0, "y" : 0, "z" : 270}`
LandscapeRight :` {"x" : 0, "y" : 0, "z" : 90}`

**Comment by SrinivasanTarget** [comment]
@sravanmedarapu We are getting ```method not implemented error```. Logs here: https://gist.github.com/SrinivasanTarget/6e1e029a4f82e2055531923809282403. Can you check this?

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey FYI

**Comment by jlipps** [comment]
Going to close this since we're not really putting energy into supporting the legacy drivers right now.
