### ISSUE TITLE
Appium can't access buttons inside uitableview header

### ISSUE THREAD

**Issue by shaynl** [appium/appium#7132]
## The problem
Appium can't access buttons inside uitableview header. Those buttons set to be visible with accessibility labels on Xcode 8 but appium not see them (see attached screenshot).
Please advice on how I can click those buttons with Appium.
Thanks.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: IOS 10.0.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

![screenshot 2016-10-31 14 56 56](https://cloud.githubusercontent.com/assets/11661865/19855444/4877b1f2-9f7d-11e6-962f-e3271fbf1935.png)

**Comment by mykola-mokhnach** [comment]
Can you see these elements using the standard Xcode accessibility inspector from developer tools?

**Comment by shaynl** [comment]
I tried it now and all I can see is the header... this is strange. In the code the buttons have accessibility labels. Is it an Xcode bug?

![screenshot 2016-10-31 16 48 29](https://cloud.githubusercontent.com/assets/11661865/19858718/462210c4-9f8b-11e6-9aab-0d2d75851572.png)

**Comment by mykola-mokhnach** [comment]
Try the solution described in https://github.com/appium/appium/issues/6517

**Comment by mykola-mokhnach** [comment]
I close the issue, since it's not an Appium problem.

**Comment by mykola-mokhnach** [comment]
@triager please close

**Comment by Sureshkumar5694** [comment]
@shaynl Did you find solution to this issue.. I am also facing the same issue

**Comment by Young-Je** [comment]
I encountered the same problem. now

**Comment by krishnagniyes** [comment]
I encountered the same problem. :( :(
