### ISSUE TITLE
Original error: Xcode version [object Object] is not yet supported

### ISSUE THREAD

**Issue by jeevan1524** [appium/appium#7133]
Problem :  I am getting the above error "Original error: Xcode version [object Object] is not yet supported" while I run my automation on the real ipad device on xcode using appium.

Configurations:
---------------
Appium version : 1.5.3
OS version : 10.12
Xcode version : 8.0
Device : ipad(real device)

Appium log:
------------
Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' --debug=5858 appium/build/lib/main.js --address "127.0.0.1" --session-override --debug-log-spacing --platform-version "9.2" --platform-name "iOS" --safari --browser-name "Safari" --full-reset --show-ios-log --device-name "ipad_v9" --isolate-sim-device

Debugger listening on port 5858

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:

[Appium]   address: '127.0.0.1'

[Appium]   sessionOverride: true
[Appium]   safari: true
[Appium]   isolateSimDevice: true
[Appium]   debugLogSpacing: true
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.2'
[Appium]   deviceName: 'ipad_v9'
[Appium]   browserName: 'Safari'

[Appium]   fullReset: true
[Appium]   showIOSLog: true
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"9.2"}'
[Appium]   --device-name => --default-capabilities '{"deviceName":"ipad_v9"}'
[Appium]   --browser-name => --default-capabilities '{"browserName":"Safari"}'

[Appium]   --full-reset => --default-capabilities '{"fullReset":true}'
[Appium]   --show-ios-log => --default-capabilities '{"showIOSLog":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

[Appium]   platformName: 'iOS'

[Appium]   platformVersion: '9.2'
[Appium]   deviceName: 'ipad_v9'
[Appium]   browserName: 'Safari'
[Appium]   fullReset: true

[Appium]   showIOSLog: true

[Appium] Appium REST http interface listener started on 127.0.0.1:4723

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 28 ms - 83 

[HTTP] --> POST /wd/hub/session {"sessionId":null,"desiredCapabilities":{"platformVersion":"10.1","deviceName":"iPad Air","browserName":"Safari","platformName":"iOS","appiumVersion":"1.5.3"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformVersion":"10.1",...

[Appium] Creating new IosDriver session

[Appium] Capabilities:
[Appium]   platformVersion: '10.1'
[Appium]   deviceName: 'iPad Air'

[Appium]   browserName: 'Safari'
[Appium]   platformName: 'iOS'
[Appium]   appiumVersion: '1.5.3'
[Appium]   fullReset: true
[Appium]   showIOSLog: true

[BaseDriver] The following capabilities were provided, but are not recognized by appium: appiumVersion.

[BaseDriver] Session created with session id: 2530e88e-1efa-4b5a-b03a-0496fdf027f8
[debug] [iOS] Not auto-detecting udid.
[debug] [iOS] We are on iOS8+ so not copying Safari app

[debug] [iOS] Removing any remaining instruments sockets

[debug] [iOS] Cleaned up instruments socket /var/folders/py/qsds3k_s1tx03rgm_mcq8_y80000gn/T/instruments_sock
[debug] [iOS] Setting Xcode version

[debug] [iOS] Xcode version set to 8.1

[debug] [iOS] Setting iOS SDK Version

[debug] [iOS] iOS SDK Version set to 10.1
[debug] [iOS] Checking whether instruments supports our device string
[debug] [Instruments] Getting list of devices instruments supports

[debug] [Instruments] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[debug] [Instruments] Available devices: Apple Watch - 38mm (3.1) [D6D9FE0F-D4C8-4E2D-9F1D-6AB600F73C9C] (Simulator),Apple Watch - 42mm (3.1) [D076E0DB-47E1-480C-8C93-0B1D1A4B2FAD] (Simulator),iPhone 7 (10.1) + Apple Watch Series 2 - 38mm (3.1) [0019BDBB-80A5-4E21-A477-AD6EE8AFD8EE] (Simulator),iPhone 7 Plus (10.1) + Apple Watch Series 2 - 42mm (3.1) [A3BC03BD-3AF6-4895-AE91-324C32606D08] (Simulator)

[MJSONWP] Encountered internal error running command: Error: Xcode version [object Object] is not yet supported
    at handleUnsupportedXcode (lib/simulator.js:15:11)
    at getDeviceString$ (lib/simulator.js:44:3)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[HTTP] <-- POST /wd/hub/session 500 2535 ms - 187 

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 14 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 15 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 19 ms - 83 

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 23 ms - 83 

Note: This is the first time I am making an attempt to run it on the real device, have enrolled to Apple Developer Program & have all the necessary certificates & provisioning profiles setup done.

Please help.!!

**Comment by mykola-mokhnach** [comment]
Xcode 8 and above are not supported by Appium 1.5 and older versions. You must use 1.6.0+

**Comment by mykola-mokhnach** [comment]
@triager please close
