### ISSUE TITLE
iOS10.1/java client  4.1.2 /Appium1.6 -beta3  swipe does not work 

### ISSUE THREAD

**Issue by bearxc** [appium/appium#7135]
Try to swipe element from right to left , and it turns out  as click instead of swipe . 

int leftX = element.getLocation().getX();
 int centerX = element.getLocation().getX() + (element.getSize().getWidth() / 2);
 int centerY = element.getLocation().getY() + (element.getSize().getHeight() / 2);
 Context.driver.swipe(centerX, centerY, leftX, centerY, 100);

HTTP] --> GET /wd/hub/session/c1c41ed9-0958-4491-b910-9ea879b4ae96/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/location {}
[MJSONWP] Calling AppiumDriver.getLocation() with args: ["59EAFAE9-6C52-4589-B3AF-36076C64221A","c1c41ed9-0958-4491-b910-9ea879b4ae96"]
[debug] [XCUITest] Executing command 'getLocation'
[JSONWP Proxy] Proxying [GET /element/59EAFAE9-6C52-4589-B3AF-36076C64221A/rect] to [GET http://localhost:8100/session/62F9630F-9C47-4A62-AF32-AADE40F86049/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/rect] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 119,\n    \"x\" : 0,\n    \"width\" : 375,\n    \"height\" : 83\n  },\n  \"sessionId\" : \"62F9630F-9C47-4A62-AF32-AADE40F86049\",\n  \"status\" : 0\n}"
[MJSONWP] Responding to client with driver.getLocation() result: {"x":0,"y":119}
[HTTP] <-- GET /wd/hub/session/c1c41ed9-0958-4491-b910-9ea879b4ae96/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/location 200 160 ms - 87 
[HTTP] --> GET /wd/hub/session/c1c41ed9-0958-4491-b910-9ea879b4ae96/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/location {}
[MJSONWP] Calling AppiumDriver.getLocation() with args: ["59EAFAE9-6C52-4589-B3AF-36076C64221A","c1c41ed9-0958-4491-b910-9ea879b4ae96"]
[debug] [XCUITest] Executing command 'getLocation'
[JSONWP Proxy] Proxying [GET /element/59EAFAE9-6C52-4589-B3AF-36076C64221A/rect] to [GET http://localhost:8100/session/62F9630F-9C47-4A62-AF32-AADE40F86049/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/rect] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 119,\n    \"x\" : 0,\n    \"width\" : 375,\n    \"height\" : 83\n  },\n  \"sessionId\" : \"62F9630F-9C47-4A62-AF32-AADE40F86049\",\n  \"status\" : 0\n}"
[MJSONWP] Responding to client with driver.getLocation() result: {"x":0,"y":119}
[HTTP] <-- GET /wd/hub/session/c1c41ed9-0958-4491-b910-9ea879b4ae96/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/location 200 154 ms - 87 
[HTTP] --> GET /wd/hub/session/c1c41ed9-0958-4491-b910-9ea879b4ae96/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/size {}
[MJSONWP] Calling AppiumDriver.getSize() with args: ["59EAFAE9-6C52-4589-B3AF-36076C64221A","c1c41ed9-0958-4491-b910-9ea879b4ae96"]
[debug] [XCUITest] Executing command 'getSize'
[JSONWP Proxy] Proxying [GET /element/59EAFAE9-6C52-4589-B3AF-36076C64221A/rect] to [GET http://localhost:8100/session/62F9630F-9C47-4A62-AF32-AADE40F86049/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/rect] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 119,\n    \"x\" : 0,\n    \"width\" : 375,\n    \"height\" : 83\n  },\n  \"sessionId\" : \"62F9630F-9C47-4A62-AF32-AADE40F86049\",\n  \"status\" : 0\n}"
[MJSONWP] Responding to client with driver.getSize() result: {"width":375,"height":83}
[HTTP] <-- GET /wd/hub/session/c1c41ed9-0958-4491-b910-9ea879b4ae96/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/size 200 156 ms - 97 
[HTTP] --> GET /wd/hub/session/c1c41ed9-0958-4491-b910-9ea879b4ae96/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/location {}
[MJSONWP] Calling AppiumDriver.getLocation() with args: ["59EAFAE9-6C52-4589-B3AF-36076C64221A","c1c41ed9-0958-4491-b910-9ea879b4ae96"]
[debug] [XCUITest] Executing command 'getLocation'
[JSONWP Proxy] Proxying [GET /element/59EAFAE9-6C52-4589-B3AF-36076C64221A/rect] to [GET http://localhost:8100/session/62F9630F-9C47-4A62-AF32-AADE40F86049/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/rect] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 119,\n    \"x\" : 0,\n    \"width\" : 375,\n    \"height\" : 83\n  },\n  \"sessionId\" : \"62F9630F-9C47-4A62-AF32-AADE40F86049\",\n  \"status\" : 0\n}"
[MJSONWP] Responding to client with driver.getLocation() result: {"x":0,"y":119}
[HTTP] <-- GET /wd/hub/session/c1c41ed9-0958-4491-b910-9ea879b4ae96/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/location 200 147 ms - 87 
[HTTP] --> GET /wd/hub/session/c1c41ed9-0958-4491-b910-9ea879b4ae96/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/size {}
[MJSONWP] Calling AppiumDriver.getSize() with args: ["59EAFAE9-6C52-4589-B3AF-36076C64221A","c1c41ed9-0958-4491-b910-9ea879b4ae96"]
[debug] [XCUITest] Executing command 'getSize'
[JSONWP Proxy] Proxying [GET /element/59EAFAE9-6C52-4589-B3AF-36076C64221A/rect] to [GET http://localhost:8100/session/62F9630F-9C47-4A62-AF32-AADE40F86049/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/rect] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"y\" : 119,\n    \"x\" : 0,\n    \"width\" : 375,\n    \"height\" : 83\n  },\n  \"sessionId\" : \"62F9630F-9C47-4A62-AF32-AADE40F86049\",\n  \"status\" : 0\n}"
[MJSONWP] Responding to client with driver.getSize() result: {"width":375,"height":83}
[HTTP] <-- GET /wd/hub/session/c1c41ed9-0958-4491-b910-9ea879b4ae96/element/59EAFAE9-6C52-4589-B3AF-36076C64221A/size 200 150 ms - 97 

[HTTP] --> POST /wd/hub/session/c1c41ed9-0958-4491-b910-9ea879b4ae96/touch/perform {"actions":[{"action":"press","options":{"x":187,"y":160}},{"action":"wait","options":{"ms":100}},{"action":"moveTo","options":{"x":-187,"y":0}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":187,"y":160}},{"action":"wait","options":{"ms":100}},{"action":"moveTo","options":{"x":-187,"y":0}},{"action":"release","options":{}}],"c1c41ed9-0958-4491-b910-9ea879b4ae96"]
[debug] [XCUITest] Executing command 'performTouch'
[JSONWP Proxy] Proxying [POST /uiaTarget/0/dragfromtoforduration] to [POST http://localhost:8100/session/62F9630F-9C47-4A62-AF32-AADE40F86049/uiaTarget/0/dragfromtoforduration] with body: {"fromX":187,"fromY":160,"toX":0,"toY":160,"duration":0.1}
[JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"62F9630F-9C47-4A62-AF32-AADE40F86049","status":0}
[MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/c1c41ed9-0958-4491-b910-9ea879b4ae96/touch/perform 200 1738 ms - 74

**Comment by saikrishna321** [comment]
@SrinivasanTarget @jlipps this can be closed. @bearxc can you please this on java-client repo

**Comment by bearxc** [comment]
open on java-client  and closed this one
