### ISSUE TITLE
ADB cannot find some Emulators after upgrading to appium 1.6.0 on Mac

### ISSUE THREAD

**Issue by tateexon** [appium/appium#7136]
Originally posted in: https://discuss.appium.io/t/adb-cannot-find-some-emulators-after-upgrading-to-appium-1-6-0-on-mac/13017

After upgrading to appium 1.6.0 my custom emulators as well as some of the more standard ones like Nexus 6P are no longer able to be launched when running a test with Appium. If I switch back to appium 1.5.3 I am able to both see and launch my whole list. Here is the current message it is sending me:

```
[Appium] Welcome to Appium v1.6.0
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0"...
[HTTP] <-- GET /wd/hub/status 200 11 ms - 83 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/tate/git/qaautomation/target/classes/tatetest.apk","appPackage":"com.tate.android","intentAction":"android.intent.action.VIEW","recordVideo":true,"deviceName":"Galaxy_S7_API_23","avd":"Galaxy_S7_API_23","appActivity":"com.tate.main.ui.activity.MainActivity","newCommandTimeout":900,"platformVersion":"4.4","recordScreenshots":true,"platformName":"Android","optionalIntentArguments":"-e uri 'tate://com.tate.mobile/home/'"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/tate/git...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/tate/git/qaautomation/target/classes/tatetest.apk'
[Appium]   appPackage: 'com.tate.android'
[Appium]   intentAction: 'android.intent.action.VIEW'
[Appium]   recordVideo: true
[Appium]   deviceName: 'Galaxy_S7_API_23'
[Appium]   avd: 'Galaxy_S7_API_23'
[Appium]   appActivity: 'com.tate.main.ui.activity.MainActivity'
[Appium]   newCommandTimeout: 900
[Appium]   platformVersion: '6.0'
[Appium]   recordScreenshots: true
[Appium]   platformName: 'Android'
[Appium]   optionalIntentArguments: '-e uri \'tate://com.tate.mobile/home/\''
[BaseDriver] The following capabilities were provided, but are not recognized by appium: recordVideo, recordScreenshots.
[BaseDriver] Session created with session id: b9525d5c-8372-46b7-bd88-f011b1c665f7
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_112
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/tate/Library/Android/sdk/platform-tools/adb
[debug] [ADB] Trying to find Galaxy_S7_API_23 emulator
[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[debug] [ADB] 0 device(s) connected
[debug] [ADB] 0 emulator(s) connected
[debug] [ADB] Emulator Galaxy_S7_API_23 not running
[debug] [ADB] Launching Emulator with AVD Galaxy_S7_API_23, launchTimeout60000 ms and readyTimeout 60000 ms
[ADB] Checking whether emulator is present
[ADB] Using emulator from /Users/tate/Library/Android/sdk/tools/emulator
[ADB] Checking whether android is present
[ADB] Using android from /Users/tate/Library/Android/sdk/tools/android
[ADB] Error: Avd 'Galaxy_S7_API_23' is not available. please select your avd name from one of these: '(Galaxy_Nexus_API_25), (Nexus_4_API_25), (Nexus_5_API_25), (Nexus_6_API_25), (Nexus_One_API_25), (Nexus_S_API_25)'
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (lib/tools/system-calls.js:416:9)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

You can see in the error that it is only showing this list of emulators: '(Galaxy_Nexus_API_25), (Nexus_4_API_25), (Nexus_5_API_25), (Nexus_6_API_25), (Nexus_One_API_25), (Nexus_S_API_25)'

If I look in Android Studio I have 9 emulators. Here is a picture of my current emulators in Android Studio:
[Image](https://cdn-standard.discourse.org/uploads/appium/original/2X/4/41d8e33cf9e55306d1a0ddc49affa10c7dbda362.png)

If I manually launch the emulators not in the ADB list and run a test then everything works fine but if I let appium launch the emulator itself it cannot find some of the emulators on the list. Is this a known issue or is there any known fix for this?

Other info that may be needed:
Android Studio 2.2.2
Appium 1.6.0
appium java-client 4.1.2
node v6.9.1
java version 1.8.0_112
Android Debug Bridge version 1.0.36
Mac OS 10.11.6

Any help is appreciated!
Thanks,

Tate

**Comment by mykola-mokhnach** [comment]
What is the output of 

```
android list avd -c
```

command on your system?

**Comment by mykola-mokhnach** [comment]
Looks like I know where the problem is: 

```javascript
const androidPlatforms = ['android-4.2', 'android-17', 'android-4.3', 'android-18',
                          'android-4.4', 'android-19', 'android-L', 'android-20',
                          'android-5.0', 'android-21', 'android-22', 'android-MNC',
                          'android-23', 'android-6.0'];

async function getDirectories (rootPath) {
  let files = await fs.readdir(rootPath);
  let dirs = [];
  for (let file of files) {
    let pathString = path.resolve(rootPath, file);
    if ((await fs.lstat(pathString)).isDirectory()) {
      dirs.push(file);
    }
  }
  // It is not a clean way to sort it, but in this case would work fine because
  // we have numerics and alphanumeric
  // will return some thing like this
  // ["17.0.0", "18.0.1", "19.0.0", "19.0.1", "19.1.0", "20.0.0",
  //  "android-4.2.2", "android-4.3", "android-4.4"]
  return dirs.sort();
}
```

android 7.0 SDK root is missing here. This is the file named _helpers.js_ inside _appium-adb_ module.

**Comment by mykola-mokhnach** [comment]
@jlipps please take a look

**Comment by mykola-mokhnach** [comment]
@tateexon Can you please provide the output of 

```
/Users/tate/Library/Android/sdk/tools/android list avd -c
```

command on your system?

**Comment by jlipps** [comment]
thanks @mykola-mokhnach added it to the 1.6.1 milestone. Want to take a crack at adding that string yourself?

**Comment by tateexon** [comment]
@mykola-mokhnach here is the command results you asked for:
android list avd -c
Galaxy_Nexus_API_25
Nexus_4_API_25
Nexus_5_API_25
Nexus_6_API_25
Nexus_One_API_25
Nexus_S_API_25

**Comment by mykola-mokhnach** [comment]
@tateexon This means that your "Galaxy_S7_API_23" emulator has been created by some other tool. Can you try to recreate it there/set the path to it in Android studio?

**Comment by tateexon** [comment]
@mykola-mokhnach Ok I recreated it and it now shows up in the list:
android list avd -c
Galaxy_Nexus_API_25
Galaxy_S7_API_23
Nexus_4_API_25
Nexus_5_API_25
Nexus_6_API_25
Nexus_One_API_25
Nexus_S_API_25

I am really confused now as to why it quit working in the first place. I have only ever created these in android studio, don't know how else to create them lol. That is a mystery for another day I guess.

Thank you very much for clearing up the confusion and helping me through this issue!

**Comment by mykola-mokhnach** [comment]
@tateexon np, I'm happy to help

@jlipps I think it would be enough here to just improve the error message in such case and make it more helpful, so people can understand and handle the problem themselves (e. g. ask one to check "android list avd -c" output). No problems with directory names though, sorry for the confusion.

**Comment by tateexon** [comment]
@mykola-mokhnach I did just notice that recreating the Nexus 6P did not fix the issue for it and if I run that command without -c "android list avd" then it shows the 6P with an error like this:
    Name: Nexus_6P_API_25
    Path: /Users/m662149/.android/avd/Nexus_6P_API_25.avd
   Error: Google Nexus 6P no longer exists as a device

Not sure what that means and it is not blocking me at the moment but it may be an issue for someone else.

**Comment by vikramvi** [comment]
@tateexon @mykola-mokhnach @jlipps 

Even I'm facing same issue with Appium v1.6.1-beta

1)
android list avd -c
doesn't show anything

2)
android list avd

Available Android Virtual Devices:

The following Android Virtual Devices could not be loaded:
    Name: Nexus_5_API_23
    Path: /Users/vikram-anna/.android/avd/Nexus_5_API_23.avd
   Error: Unknown target 'android-23' in /Users/vikram-anna/.android/avd/Nexus_5_API_23.ini
---------
    Name: Nexus_5_API_25
    Path: /Users/vikram-anna/.android/avd/Nexus_5_API_25.avd
   Error: Uknown error

I've created both the avd through Android Studio itself, please clarify if there is something wrong from my end or this is appium bug ?

**Comment by mykola-mokhnach** [comment]
Try to recreate the device or create it via command line

**Comment by dduphorn** [comment]
I'm getting the same error in

{"status":0,"value":{"build":{"version":"1.6.3","revision":"2176894a5be5da17a362bf3f20678641a78f4b69"}},"sessionId":null}

What is the fix?

**Comment by dduphorn** [comment]
I was successfully able to get the android emulator to open correctly.  

When your creating a device, don't select a System Image that included (with Google API).  The issue must have something to do with Google API.

**Comment by luisromanwp** [comment]
Yes, I have the same problem and only is working automatically with Emulator without Google API

**Comment by jlipps** [comment]
Sounds like ADB or the emulator is broken. I'd report it to Google.

**Comment by dduphorn** [comment]
How do I report it to Google :)

**Comment by jlipps** [comment]
https://code.google.com/p/android/issues/list
