### ISSUE TITLE
Appium 1.6.1

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7139]
Release Appium 1.6.1

**Comment by pavanbachu0604** [comment]
@jlipps Is the elements not being clicked in landscape mode solved?

**Comment by imurchie** [comment]
No, it is not.

**Comment by enzoliao** [comment]
Will the Desktop App be upgraded to 1.6.x ?

**Comment by kommuswamy** [comment]
Is there an appium inspector in this version for IOS? can you run it through the GUI?
