### ISSUE TITLE
map XCUIElement.pinch to appium's current touch action pinch/zoom api

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7140]
Apparently XCUIElement and XCUICoordinate classes have a pinch method. We should map Appium's TouchAction handling to determine how to call XCUITest pinch under the hood.

Acceptance criteria:
* [ ] Give access to zoom via WDA (either through an endpoint or through their version of TouchActions)
* [ ] map Appium's touchaction representing zoom to the appropriate corresponding method/touchaction in WDA
* [x] file a radar to the effect that pinch doesn't work, add to worms repo
* [ ] document pinch not working yet in migration doc

**Comment by imurchie** [comment]
XCTest method: https://developer.apple.com/reference/xctest/xcuielement/1618669-pinchwithscale?language=objc

**Comment by imurchie** [comment]
WDA PR: https://github.com/facebook/WebDriverAgent/pull/366

**Comment by imurchie** [comment]
Documentation of pinch problem: https://github.com/appium/appium/pull/7282

**Comment by imurchie** [comment]
XCUITest driver PR: https://github.com/appium/appium-xcuitest-driver/pull/302

**Comment by imurchie** [comment]
Radar/worm: https://github.com/appium/worms/issues/6

**Comment by IvanStawski** [comment]
Should pinch and zoom work in 1.6.3 with help of MultiAction?
