### ISSUE TITLE
add support for XCUIElement hover capability

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7141]
XCUIElements have a hover method, which we should expose via WDA to appium.

Acceptance criteria:
* [ ] new MJSONWP endpoint (`/session/:id/appium/element/:elementId/hover`) added in base-driver, mapping to `hover` command
* [ ] same endpoint added in WDA (or if they disagree, use whatever endpoint they want)
* [ ] `hover` command added in xcuitest-driver
* [ ] client libraries updated with access to this command
* [ ] test app or uicatalog app or some app with hover behavior used to write tests

**Comment by mykola-mokhnach** [comment]
The _hover_ method is only available in MacOS, but not for iOS. See https://developer.apple.com/documentation/xctest/xcuielement for more details.

**Comment by jlipps** [comment]
Oh. Going to close then since we don't support XCUITest for MacOS. If the appium-for-mac team wants to implement this, they certainly can though!
