### ISSUE TITLE
investigate web testing on ios 10.1

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7142]
It seems that i-w-d-p is not yet working with 10.1. Anything we can do to fix it up?

**Comment by testingIOS** [comment]
This is a blocker for web testing on iOS 10.x untill the iwdp is supported in iOS 10.x. We are looking for the  fix soon.

**Comment by yaphatak** [comment]
@jlipps : `i-w-d-p` means `ios-webkit-debug-proxy`? So does that means its not working for real devices? I don't see this issue

**Comment by imurchie** [comment]
Initial tests did not work for web testing on real devices in iOS 10.1. This might have changed, so this is an investigation into it.

**Comment by imurchie** [comment]
This all seems to work now, with the latest `iwdp` and iOS 10.1.1/Xcode 8.1.
