### ISSUE TITLE
XCTRunner Error for iOS 10, Appium 1.6.0, Xcode 8

### ISSUE THREAD

**Issue by philipsTanoto** [appium/appium#7143]
## The problem
When trying to get the page source for a specific page of the App I get this error:
The page contains user profile info, which includes email, name, sex, gender, birthdate, height, weight.
It is working on any other pages, so I'm not quite sure what is causing this error. 

XCTRunner[453:180715] Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x17405b120> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1

## Environment

* Appium v1.6.0
* This issue was not observed in Appium 1.4.0, before moving to iOS 10 and Xcode 8 (i.e. iOS 9.3, Xcode 7.3)
* Mac OS El Capitan
* Node.js version (unless using Appium.app|exe): 7.0.0
* Mobile platform/version under test: iOS 10
* Real device or emulator/simulator: real device iPhone 5S
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/philipsTanoto/5e2ebe49e3a3e3ddd4cdca81a22d8574
note: the actual bundle_id is replaced with "bundle_id"

Any help would be appreciated, thanks!

**Comment by mykola-mokhnach** [comment]
You can temporarily apply this patch https://github.com/facebook/WebDriverAgent/pull/332 to solve the issue locally. Or wait until Appium picks up new WDA release. 
Closing as non-Appium issue (also has duplicates).

**Comment by mykola-mokhnach** [comment]
@triager please close

**Comment by philipsTanoto** [comment]
@mykola-mokhnach, I tried applying the fix you referred [facebook/WebDriverAgent#332](here), but it doesn't seem to fix my issue, when calling getPageSource(), I never got any respond back from the webdriveragent, even after waiting until the process timeouts. I just copy pasted the changes you made into my local machine, which is the file "XCUIElement+FBIsVisible.m"
I'm using the iOS Appium Inspector you referred [here](https://github.com/appium/appium/issues/6923)

**Comment by jeangb** [comment]
@philipsTanoto I have the same problem, applying the fix didn't change a thing. Have you been able to resolve this ?
