### ISSUE TITLE
Webview context - CSS Selector is not working

### ISSUE THREAD

**Issue by rexors** [appium/appium#7145]
## The problem

After switching to Webview context I'm not able to use the css selector to interact with elements  (`driver.findElement(By.cssSelector('.myElement'))`)

The following line is printed after I try to interact with an element via css selector:

`[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id`

Do I miss something here completely and css selection is not even supported with iOS?

I followed these instructions:

https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/hybrid.md

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: 10.11.6
* Node.js version (unless using Appium.app|exe): 6.8.0
* Mobile platform/version under test: iOS 10.0.2
* Real device or emulator/simulator: Real device - iPad Air
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

[Appium server logs](https://gist.github.com/rexors/47fa60342094fb8b9503010d60b74cc5)

## Code To Reproduce Issue

```
class TestRunner {

    public static void main(String[] args) {
        IOSDriver<WebElement> driver = new IOSDriver<WebElement>(new URL("http://127.0.0.1:4723/wd/hub"), createIOSCapabilities())

        Thread.sleep(5000)
        toWebviewContext(driver)
        println driver.getContext()

        WebElement myElement = driver.findElement(By.cssSelector('.myElement'))
        println myElement.getLocation()
        myElement.click()
    }

    public static DesiredCapabilities createIOSCapabilities() {
        DesiredCapabilities desiredCapabilities = new DesiredCapabilities()

        desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, 'XCUITest')
        desiredCapabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 20)
        desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, 'iPad Air')
        desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, 'iOS')
        desiredCapabilities.setCapability(IOSMobileCapabilityType.BUNDLE_ID, 'de.secret.secret')
        desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, '10.0.2')
        desiredCapabilities.setCapability('realDeviceLogger', '/usr/local/lib/node_modules/deviceconsole/deviceconsole')
        desiredCapabilities.setCapability('xcodeConfigFile', '/Users/user/Desktop/Repos/secret/src/app/test/gui/xcconfig')
        desiredCapabilities.setCapability('autoWebView', false)
        desiredCapabilities.setCapability('fulLReset', false)
        desiredCapabilities.setCapability(MobileCapabilityType.UDID, 'device-id')

        return desiredCapabilities;
    }

    public static toWebviewContext(AppiumDriver driver) {
        Set<String> contextHandles = driver.getContextHandles()
        for (String handle : contextHandles) {
            if (handle.startsWith('WEBVIEW_')) {
                driver.context(handle)
                break
            }
        }
    }
}
```

**Comment by rexors** [comment]
CSS Selectors are working but now I'm facing another issue:

I'm not able to click() on any elements...

**Comment by dpgraham** [comment]
Hi Rexor. Since you got the CBS selectors working, can you show me updated appium logs that you're getting when you try to click the element.

**Comment by rexors** [comment]
Hi @dpgraham , thanks for answering.

I noticed that the problem may be within our App. We use some JavaScript so handle click and touch events and may have broken clicks performed by selenium. We are investigating right now. I will let you know when we know more!

**Comment by rexors** [comment]
This issue can be closed. I had a bug in my application. Working now!
