### ISSUE TITLE
Implement 'clickCurrent' in appium-xcuitest-driver

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#7146]
## The problem
In my scripts, I move to Webview mode and try to click on an element using Action Builder click method provided by Selenium.
The issue occurs on using XCUITest (Xcode 8.0), works absolutely fine with Instruments (Xcode 7.3)

## Environment

* Appium version (or git revision) that exhibits the issue: v 1.6.0 (Xcuitest)
* Last Appium version that did not exhibit the issue (if applicable): v1.6.0 (Instruments)
* Node.js version (unless using Appium.app|exe): v5.5.0
* Mobile platform/version under test: iOS 9.3.5
* Real device iPhone 5S
* Appium CLI

## Details

Error on selenium:
org.openqa.selenium.WebDriverException: Method has not yet been implemented (WARNING: The server did not provide any stacktrace information)

## Link to Appium logs

https://gist.github.com/mayureshshirodkar/e17a934c36822cda68a1ea90bb7aebd1
[HTTP] <-- POST /wd/hub/session/791fbd5e-a1c6-4c86-8b81-95c7ec98ac3d/moveto 200 1018 ms - 76 
**## [HTTP] --> POST /wd/hub/session/791fbd5e-a1c6-4c86-8b81-95c7ec98ac3d/click {"button":0}
[MJSONWP] Calling AppiumDriver.clickCurrent() with args: [0,"791fbd5e-a1c6-4c86-8b81...
 [debug] [XCUITest] Executing command 'clickCurrent'
[HTTP] <-- POST /wd/hub/session/791fbd5e-a1c6-4c86-8b81-95c7ec98ac3d/click 501 2 ms - 122** 

## Code To Reproduce Issue [ Good To Have ]
 Actions builder = new Actions(driver.getWebDriver());
WebElement el=findElementByXpath("xpath");
builder.moveToElement(el).click().perform();

**Comment by dpgraham** [comment]
Thanks @mayureshshirodkar 

The 'clickCurrent' method was available in Instruments driver (https://github.com/appium/appium-ios-driver/blob/00638de9c62e961a0278a47db98cc16480dd2bee/lib/commands/gesture.js) and is no longer available in XCUITest driver (https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/gesture.js)

@imurchie Is there a reason 'clickCurrent', 'clickCoords' and 'clickWebCoords' weren't ported over to appium-xcuitest-driver?

**Comment by imurchie** [comment]
No particular reason, no.

**Comment by dpgraham** [comment]
Okay, in that case we'll put it on the backlog as an enhancement.

**Comment by mayureshshirodkar** [comment]
@dpgraham any update on this issue?

**Comment by dpgraham** [comment]
This is still on our backlog.

**Comment by Aroxx** [comment]
I see that "flick" is not implemented in appium-xcuitest-driver either. Are there plans to implement flick?

**Comment by imurchie** [comment]
Unfortunately Apple hasn't given a way to do it, so at the moment, no plans.

**Comment by mykola-mokhnach** [comment]
clickCurrent won't be implemented with XCTest
