### ISSUE TITLE
Getting an internal error when tried to launch appium

### ISSUE THREAD

**Issue by shrikant007** [appium/appium#7147]
## The problem

I updated an Appium from version **1.4.13** to **1.5.2** and since then i started facing an issue. Showing an error "Encountered internal error running command" while launching an app on my real device

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.5.2
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: macOS Sierra version 10.12
* Xcode version: 8.1
* Node.js version (unless using Appium.app|exe):3.10.8
* Mobile platform/version under test: 10.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

## Details
I updated an Appium from version **1.4.13** to **1.5.2** and since then i started facing an issue. Showing an error "Encountered internal error running command" while launching an app on my real device

## Link to Appium logs

https://gist.github.com/shrikant007/f38a157499d63544771ffba2b52fcea7

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("appium-version", "1.0");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.1");
capabilities.setCapability("newCommandTimeout", "9000");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "Soban's iPhone");
capabilities.setCapability(MobileCapabilityType.VERSION, "8.0");
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("sendKeyStrategy","setValue");
capabilities.setCapability("--no-reset", false);

**Comment by jlipps** [comment]
Your `app` needs to be a signed ipa file ready for deployment on your device

**Comment by imurchie** [comment]
Appium 1.5.2 _will not_ work with Xcode 8+. Apple has changed their automation system entirely, and it is only supported in 1.6.x.

**Comment by shrikant007** [comment]
Thanks @jlipps and @imurchie for reply.

I have installed Appium v1.6.1-beta using npm install -g appium@beta after that i am able to install an app on real device but app is not being launched on device but Getting an error "Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1' "

**Comment by shrikant007** [comment]
i am using below capabilities-

	public static void beforeMethod()

	{
	
			DesiredCapabilities capabilities = new DesiredCapabilities();
			
			capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.6.0");
			capabilities.setCapability("automationName", "XCUITest");
			capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
			capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.1");
			capabilities.setCapability("deviceName", "Soban's iPhone");
			capabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
			capabilities.setCapability("--no-reset", false);
			capabilities.setCapability("autoWebview", false);
			capabilities.setCapability("xcodeConfigfile", "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/xcodeConfigfile.xcconfig");

			//Read property file
			String propFile = "config.properties";
			Properties propertyFile = functionLibrary.getPropertyFile(propFile);
			
			capabilities.setCapability("app", propertyFile.get("app_path"));

		try {
			
			wd = new IOSDriver<IOSElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);

		} catch (MalformedURLException e) {

			e.printStackTrace();
		}

		wd.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);

	}

**Comment by imurchie** [comment]
Please search the issues. This has been dealt with many times

**Comment by shrikant007** [comment]
Thanks @imurchie issues got fixed after following below links. Now i am able to launch an app. Closing this thread.

https://discuss.appium.io/t/xcodebuild-failed-with-code-65-warning-the-server-did-not-provide-any-stacktrace-information-command-duration-or-timeout-32-63-seconds/12756/3

https://libraries.io/npm/appium-xcuitest-driver
