### ISSUE TITLE
driver.elementById('text on display') behaviour in Appium 1.6

### ISSUE THREAD

**Issue by philipshurpik** [appium/appium#7148]
## The problem

Hi Guys!

I experience problem when upgrading to Appium 1.6 from Appium 1.5.3.
My app is on React Native (currently 0.33) for iOS (10.0 version).

Previously in many cases I used:
`driver.elementById('some text that is displaying on display')`

For example it suitable for ActionSheets and in some other places, when you can't add testID to element.

But now it can't find it with error:

```
> CALL elementById("Create new client") 
> POST /session/:sessionID/element {"using":"id","value":"Create new client"}

Error: [elementById("Create new client")] Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters. Selenium error: An element could not be located on the page using the given search parameters.
```

Possibly something in handling elements by id (like text on the screen) changed.

Would be happy if you suggest how to change my tests to make it work.

In this particular case I need to press on ActionSheet element, but also would be happy to know more general solution.

## Environment

* Appium version: 1.6
* Last Appium version that did not exhibit the issue: 1.5.3
* Mobile platform/version under test: iOS 10, React Native 0.33

**Comment by mykola-mokhnach** [comment]
Where this text is located in _driver.getPageSource()_ method output?

**Comment by philipshurpik** [comment]
I tried to find getPageSource() method, but as I understand wd client (https://github.com/admc/wd) not support this command.

Maybe you can suggest other solution?

**Comment by dpgraham** [comment]
The 'wd' client has a command called driver.source()

If you call 'driver.source().then(console.log)' it will output the XML.
