### ISSUE TITLE
Appium Inspector and UIAutomatorViewer return different tree hierarchy 

### ISSUE THREAD

**Issue by Ser-Gius** [appium/appium#7149]
## The problem

I'm inspecting the same screens with Appium Inspector and UIAutomatorViewer on native android app and the results are as follows:

In Appium Inspector for every screen the tree starts like this:
`//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]`

UIAutomatorViewer shows something different for each screen (see attached screenshot)
![screen shot 2016-11-02 at 18 13 43](https://cloud.githubusercontent.com/assets/22973227/19929203/3237f800-a128-11e6-946f-e55a1405cf4c.png)

Which one is correct and why is this happening?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MacOS 10.12
* Node.js version (unless using Appium.app|exe): NA
* Mobile platform/version under test: Android, 4.4.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: App

## Details

NA

## Link to Appium logs

NA

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by jlipps** [comment]
Do you have 'ignore unimportant views' checked in uiautomatorviewer? The android source xml looks different based on whether this setting is on.

**Comment by Ser-Gius** [comment]
Yes, I already figured it out, it was because I was exporting XML with --compressed flag in uiautomatorviewer. Was using only appium inspector before and was unaware of this feature of uiautomatorviewer.
Thanks and close please.

**Comment by mykola-mokhnach** [comment]
@triager please close
