### ISSUE TITLE
platformVersion can imply automationName XCUITest when targeting Safari.

### ISSUE THREAD

**Issue by jlennox** [appium/appium#7150]
## The problem

Appium attempts to use the XCUITest backend when `browserName` is set to `Safari` and `platformVersion` is set to 10.0 or above. This issue does not happen if `platformVersion` is not set.

This causes Appium to attempt to compile WebDriverAgent, etc, without need.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* ~~Last Appium version that did not exhibit the issue (if applicable):~~
* ~~Desktop OS/version used to run Appium:~~
* Node.js version (unless using Appium.app|exe): v6.8.0
* Mobile platform/version under test: iOS 10.0.2
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

This code is causing the automation to be considered as "XCUITest"

From `appium.js`
```javascript
    if (caps.platformName.toLowerCase() === 'ios') {
      if (caps.platformVersion) {
        let majorVer = caps.platformVersion.toString().split(".")[0];
        if (parseInt(majorVer, 10) >= 10) {
          log.info("Requested iOS support with version >= 10, using XCUITest " +
                   "driver instead of UIAutomation-based driver, since the " +
                   "latter is unsupported on iOS 10 and up.");
          return XCUITestDriver;
        }
      }

      return IosDriver;
    }
```

## Link to Appium logs

(Sorry, I can not share the logs)

**Comment by imurchie** [comment]
Why is this a problem?

**Comment by jlennox** [comment]
It requires Xcode to be setup with a signing profile and so forth when it's not needed.

The behavior is different if platformVersion is specified or not. That's exceptional. It should consistently fall one way or the other.

**Comment by imurchie** [comment]
Without it, if the device is 10 or above it will just fail anyway once it gets to the iOS driver.

**Comment by jlennox** [comment]
If I do not specify `platformVersion` but set `browserName` to Safari, it runs fine. If I set `platformVersion` to `10.0.2` and browserName` to Safari it attempts to compile WebDriverAgent.

**Comment by imurchie** [comment]
Can you provide the logs for a test run with this setup? It _should_ not work!
