### ISSUE TITLE
appium/appium `gulp once` pauses for an obscene amount of time before finishing

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7153]
This is a burden for running unit tests before committing, etc...

**Comment by imurchie** [comment]
Appium's problem is solved. There is still a problem with `appium-ios-driver`, which I have tracked down to https://github.com/appium/appium-ios-driver/blob/master/test/unit/ios-log-specs.js but can't seem to fix. It appears to be something in the `tail` child process.
