### ISSUE TITLE
(node:6200) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by jackiezero** [appium/appium#7157]
## The problem

when is run appium in the cmd

![994 tmp](https://cloud.githubusercontent.com/assets/15335697/19953877/d76a4b86-a1ad-11e6-8bbc-16d14251ff63.jpg)

I want to konw it's node's issue or appium V1.6.0 have this issue

## Environment

* Appium V1.6.0
* node V7.0.0
* npm V3.10.8
* WIN7

**Comment by imurchie** [comment]
This is an issue in 1.6.0 (which came out before Node 7). It is fixed and
will not be there in the next release.

**Comment by jackiezero** [comment]
Thx

**Comment by simlw** [comment]
how to solve this problem? my environments:   
- node V6.9.1
- appium V1.6.0
- OSX 
- npm V4.6.1

**Comment by imurchie** [comment]
Upgrade Appium. Though it is just a warning, not an error. Everything still functions.
