### ISSUE TITLE
Can't click randomly on IOS device by Appium 1.6

### ISSUE THREAD

**Issue by bily621** [appium/appium#7158]
## The problem

I want to randomly click on ios device, using the methode  "driver.tap(1,x,y,50)", i found the actioning don't work 

## Environment

* Appium version : v1.6.0 
* Mac os: 10.11.6
* Node.js version :v4.4.3
* ios version: 9.3.4
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium cli
* XCUITestDriver version: 2.0.34
* java-client version: 3.4.1

## Link to Appium logs

[HTTP] <-- GET /wd/hub/session/36eb04e8-ff77-45e3-9cc0-42ed53337728/source 200 2439 ms - 58757
[HTTP] --> POST /wd/hub/session/36eb04e8-ff77-45e3-9cc0-42ed53337728/touch/perform {"actions":[{"action":"press","options":{"x":225,"y":251}},{"action":"wait","options":{"ms":50}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":225,"y":251}},{"action":"wait","options":{"ms":50}},{"action":"release","options":{}}],"36eb04e8-ff77-45e3-9cc0-42ed53337728"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted "WDA long press needs an element" and you sent undefined
[HTTP] <-- POST /wd/hub/session/36eb04e8-ff77-45e3-9cc0-42ed53337728/touch/perform 400 6 ms - 93
[HTTP] --> GET /wd/hub/session/36eb04e8-ff77-45e3-9cc0-42ed53337728/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["36eb04e8-ff77-45e3-9cc0-42ed53337728"]
[debug] [XCUITest] Executing command 'getPageSource'

## Code To Reproduce Issue [ Good To Have ]

x =new Random().nextInt(w);
x =x <10 || x > (w-10) ? w/2 : x;
y =new Random().nextInt(h);
y =y <75 || y > (h-10) ? h/2 :y;
driver.tap(1,x,y,500);

**Comment by imurchie** [comment]
As of right now the upstream project does not allow arbitrary coordinates to be interacted with. We will look into how to support this.

**Comment by mykola-mokhnach** [comment]
@bily621 you can workaround it by calling the corresponding WDA API directly (it's running on the same server by default, port 8100). This is the wrapper we use for the call in our framework.

```java
    public JSONObject tap(String sessionId, String uuid, double x, double y) throws RESTError {
        final Builder webResource = buildDefaultRequest(String.format("tap/%s", uuid), sessionId);
        final JSONObject body = new JSONObject();
        body.put("x", x);
        body.put("y", y);
        return waitForResponse(() -> restHandlers.httpPost(webResource, body.toString(), new int[]{HttpStatus.SC_OK}));
    }
```

You need to pass "0" as _uuid_ value to tap at (x, y) position on the screen surface. _sessionId_ is returned by default if one does any request to the WDA server root (usually http://localhost:8100/)

**Comment by imurchie** [comment]
Oh! Thanks @mykola-mokhnach! That gave me the pointer to get the right way to do this (hadn't thought to look at `tap`). I can get it working now. I'll open a PR in WDA.

**Comment by imurchie** [comment]
https://github.com/facebook/WebDriverAgent/pull/351

**Comment by bily621** [comment]
@mykola-mokhnach Thanks,but I can't understand quite clearly
@imurchie I saw that you submitted something，can i use it ?

**Comment by mykola-mokhnach** [comment]
It is an advanced topic. I can try to explain it if you need an urgent workaround. Or you can just wait until the next Appium version is released with this issue fixed.

**Comment by imurchie** [comment]
@bily621 I am in the process of getting that fix into Appium. Should be by the end of the day.

**Comment by bily621** [comment]
@mykola-mokhnach Thanks，I understand what you mean, but I don't know how to do it.
@imurchie  I am looking forward to using the new API，ths!!!!

**Comment by imurchie** [comment]
This has been fixed. Closing.
