### ISSUE TITLE
[Error: iproxy exited with code '234']

### ISSUE THREAD

**Issue by shay777** [appium/appium#7161]
## The problem

Hi,

I am not able to launch my ios app due to this error. I can see the WebDriverAgent starting but then my test fails.

Any idea what this error means?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac sierra
* Node.js version (unless using Appium.app|exe):4.2.1
* Mobile platform/version under test: ios 10
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

https://gist.github.com/shay777/2f8246aab99ba7cc9048d97c15106abf

**Comment by mykola-mokhnach** [comment]
Something seems to be broken in the node config, because WDA is not supposed to start on port number zero:
> [XCUITest] Detected that WebDriverAgent is running at url 'http://192.168.0.58:0'

Also, as far as I know there was some bug about selenium grid and Appium 1.6 compatibility, which has been recently fixed. @imurchie correct me if I'm wrong.

**Comment by imurchie** [comment]
No, that is weird. Can you run the `xcodebuild` command from the terminal

```
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=c286617073f726af8d465d5cfe4de491136db5b1
```

**Comment by shay777** [comment]
@mykola-mokhnach How can I change the port of the WebDriverAgent or even check it? Not sure if it's related but my selenium grid server is on port 4444.

@imurchie  I ran the command and basically nothing happens. It stays with: 
2016-11-06 10:00:24.543537 XCTRunner[296:11823] Running tests...
2016-11-06 10:00:25.508588 XCTRunner[296:11823] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2016-11-06 10:00:26.196
Test Suite 'WebDriverAgentRunner.xctest' started at 2016-11-06 10:00:26.199
Test Suite 'UITestingUITests' started at 2016-11-06 10:00:26.202
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2016-11-06 10:00:26.206
    t =     0.01s     Set Up
2016-11-06 10:00:26.220873 XCTRunner[296:11823] Built at Nov  6 2016 10:00:14
2016-11-06 10:00:26.253765 XCTRunner[296:11823] ServerURLHere->http://192.168.0.58:0<-ServerURLHere
2016-11-06 10:00:26.255100 XCTRunner[296:11823] Listening on USB

Anything I should do? How to run the test? Should I start appium?

Thanks to you both

**Comment by shay777** [comment]
I installed appium again and now it's working. Not sure what was the issue but i had also webdriveragent and appium-xcuitest-driver folders installed so i deleted it and installed appium from the beginning so I will only have WebDriverAgent installed on /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

**Comment by shay777** [comment]
not sure if it's related. thanks for the help anyway.

**Comment by imurchie** [comment]
Glad it worked out.
