### ISSUE TITLE
When is the Expected Time of Arrival for Appium 1.6 dmg version ?

### ISSUE THREAD

**Issue by dilsreccse** [appium/appium#7162]
We understand that currently Appium 1.6 Terminal version is available. Can it be considered as stabilised Version to proceed with our iOS 10 Automation? Also, Please confirm that are there any plan to release .dmg version of Appium 1.6 anytime soon? If Yes, when it will be released? Any major feature changes planned?

**Comment by SrinivasanTarget** [comment]
Please raise your question in appium discuss forum. Any updates related to this will be communicated via same channel.

**Comment by SrinivasanTarget** [comment]
@triager please close

**Comment by SrinivasanTarget** [comment]
Till we get a new release on this you can use other inspectors mentioned here, https://github.com/SrinivasanTarget/awesome-appium#inspectors
