### ISSUE TITLE
New Appium GUIs + Inspectors

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7167]
The current Appium GUIs (Appium.app and Appium.exe) have a number of issues. They aren't maintained by the core Appium team. They're written in Objective-C and C# respectively: two languages, and specifically, two languages other than Appium's core language. Because of this they lag behind the Appium server and are often broken. However, users love them primarily because of the Inspector feature (the thing that lets them graphically navigate their app), so we have to field a ton of complaints about these projects. There's an opportunity to start over. With [Electron](http://electron.atom.io/), we'd be able to take the new version of Appium we're working on and embed it directly inside a Node-based GUI app written using the languages and technologies the core team is experienced with. We'd have one codebase and could distribute the app on Mac, Windows, and Linux. The GUIs would become an official part of Appium's release cycle so they wouldn't be broken.

**Comment by mykola-mokhnach** [comment]
IMHO some users use these graphical wrappers, because they don't know how to/don't want to use the stuff installed with npm and available from Terminal. Shortly speaking, they need a simple UI wrapper to start/stop Appium server, set some additional options and to monitor logs.

**Comment by enzoliao** [comment]
Really nice decision!

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium-desktop
