### ISSUE TITLE
Onboarding Overhaul

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7169]
The current Appium docs leave a lot to be desired. The format is confusing (it would be better for API docs), the content is outdated, and many things are still undocumented. This project would go back to the drawing board in all of these areas and put together something genuinely helpful for the community, which hopefully reduces the kind of support issues we're currently flooded by.

**Comment by dpgraham** [comment]
@jlipps @imurchie Can we call this 'done'? I think we've accomplished our goal.

**Comment by imurchie** [comment]
I would have said the sample code was part of onboarding. But given that we have an epic for that, closing this is fine.
