### ISSUE TITLE
iOS Startup Time Improvement

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7173]
iOS startup times have gotten progressively longer with each iOS release. In part this is Apple's fault and there's not anything we can do about it. But we should investigate and see if we can be more efficient in how we start sessions / webdriveragent, especially given that we can now focus on XCUITest and leave Instruments behind

**Comment by mykola-mokhnach** [comment]
Some points which can be improved already:
1. "simctl install" works even while simulator is booting. How we do it - just start the simulator and then retry and wait until there are no errors from this command.

2. We detect simulator startup by scanning through process list ether than by scanning log output. In our case the presence of "nsurlstoraged" daemon executed from Simulator utilities root (there is a Mac OS daemon with the same name) means that Simulator has been already successfully booted. 

3. We do add **-Fn** options to open utility before starting the simulator to ensure there is no extra stuff in cache, that can prevent it from booting properly. 

4. We do not try to restart the simulator by default if it is already running (only in case the selected device model is different). simctl uninstall/simctl install sequence is pretty enough in most of the cases to reset the app without resetting the Simulator.

**Comment by imurchie** [comment]
Interesting. These are certainly worth giving a shot.

**Comment by jlipps** [comment]
Yeah, great suggestions @mykola-mokhnach!

**Comment by jzzj** [comment]
Certainly needs. Mark it for future news.

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach I think your suggestions are implemented now. Can we close this out there anything left. I personally feel we have improved from where we were on this after above suggestions.

**Comment by mykola-mokhnach** [comment]
@SrinivasanTarget yes, everything from the list above has been already implemented.
