### ISSUE TITLE
Appium Dearchitecture

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7174]
OK, we went a bit overboard in Appium 1.5 by exploding Appium into 40+ repos and NPM packages. Let's think a little more critically about it and consolidate into the minimal number of repos/packages that make sense for our code and community patterns.

**Comment by rkavalap** [comment]
Current
![appium-current](https://cloud.githubusercontent.com/assets/80310/24785739/1d672910-1b11-11e7-9e2e-3be1516065b2.png)

Planned:
![appium-planned](https://cloud.githubusercontent.com/assets/80310/24785742/20825fc0-1b11-11e7-85b0-2682186d062c.png)

**Comment by dpgraham** [comment]
Is there anything left to do on this @jlipps or @imurchie?

**Comment by imurchie** [comment]
Most of this is not necessary. There are still some bits of dearchitecture that need to be done.
1. Integrate `appium-android-bootstrap` and `appium-uiautomator`
1. Integrate the result of above into `appium-android-driver`
1. Integrate, as much as possible, the Android helpers (unlocker, settings, ime) and streamline install of that.

**Comment by mykola-mokhnach** [comment]
Closed as completed
