### ISSUE TITLE
Stuck when trying to click an element

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/appium#7178]
## The problem

Appium seems to get stuck into a bad state when trying to click a particular button in my UI. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: OS X 10.12.1
* Node.js version (unless using Appium.app|exe): 7.0.0
* Mobile platform/version under test: iOS 9.3
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

When attempting to click this object using the Appium ruby console, the call never returns. The Appium log shows repeatedly: 

```
[JSONWP Proxy] Proxying [POST /uiaElement/B363CC4B-8343-422C-BD94-14C9E9156E95/scroll] to [POST http://localhost:8100/session/E776DBB7-BED5-4BC5-B6B2-6999C1F9934C/uiaElement/B363CC4B-8343-422C-BD94-14C9E9156E95/scroll] with body: {"toVisible":true}
[JSONWP Proxy] Got response with status 200: {"sessionId":"E776DBB7-BED5...
```

It never gets out of this state, and I'm required to force quit Appium and relaunch. This issue does not occur with the UIA driver.

Appium log: https://gist.github.com/VivaLosDoyers/45a2852d3a113ef472b97e037a6863cc

## Code To Reproduce Issue [ Good To Have ]
```
find_element(id: 'Delete').click
```

**Comment by imurchie** [comment]
Can you update Appium to get the latest driver? There has been a bunch of work done, which gets rid of the need for scrolling here, which seems like the problem.

```
npm uninstall -g appium
npm install -g appium --no-shrinkwrap
```

**Comment by VivaLosDoyers** [comment]
I'll give that a try. Is there a way to easily find out when drivers get updated?

**Comment by imurchie** [comment]
Not particularly. You can watch here: https://github.com/appium/appium-xcuitest-driver/releases

**Comment by VivaLosDoyers** [comment]
Unfortunately that didn't solve this problem for me.

The good thing is that I have a workaround for this case. I was attempting to target the XCUIElementTypeStaticText part of the button, which is when this occurs. Targeting the button itself (one level above in the DOM) works.

**Comment by imurchie** [comment]
Hmm. Ok. We'll keep looking. I'm glad you have a workaround.

**Comment by nicolasavenza** [comment]
I've seen this when trying to setText on a textfield that is the last element of a list. The weird thing is I'm not trying to do any scrolling but the error message is the same as VivaLosDoyers sees:

`Failed to perform scroll with visible cell due to max scroll count reached`

I'm working around it by using setValue on the cell element that contains the textfield for now.

**Comment by VivaLosDoyers** [comment]
There was a fix made for that error in the latest XCUITest driver. It gets installed if you uninstall and reinstall appium.

**Comment by rkavalap** [comment]
Closing this issue since it was fixed in the latest XCUOTest driver.
