### ISSUE TITLE
How to upgrade the chrome browser at Android 7.0 emulator 

### ISSUE THREAD

**Issue by tomliuxin** [appium/appium#7179]
after created android 7.0 emulator, the chrome browser auto installed, the version is 51.*.*, 
but I want to upgrade this browser to the latest version 54.*.*
due to this installed when emulator created, I can't uninstall it. how to upgrade it to the latest version?

**Comment by tomliuxin** [comment]
Issue solved. 
used the CMD to uninstall it. 

adb root
adb remount
adb shell
cd system
cd app
rm Chrome -f -rR

open CMD again
adb root
adb remount
adb shell
cd data
cd data
rm -r com.android.chrome

**Comment by tomliuxin** [comment]
chrome apk:
http://www.apkmirror.com/apk/google-inc/chrome/

**Comment by arsen91** [comment]
> rm Chrome -f -rR

this one gives me `rm: Chrome.apk: Read-only file system` :/

**Comment by appiumnovice** [comment]
Same problem.

**Comment by veenadevi** [comment]
getting same issue with Android 7+chrome 51, any solution?

**Comment by jackjoy** [comment]
Use`$ANDROID_HOME/emulator/emulator -avd Nexus7 -writable-system` to start emulator and then do above instructions. (Nexus7 is example avd identifier)

**Comment by saxenasurbhi92** [comment]
I tried above steps but getting error as 
"generic_x86:/data/data # rm -r com.android.chrome
rm: com.android.chrome: No such file or directory"

**Comment by Akulavenkatesh** [comment]
This link for me, download the apk and drag & drop it to simulator:
 
https://www.apkmirror.com/apk/google-inc/chrome/chrome-61-0-3163-98-release/chrome-browser-61-0-3163-98-6-android-apk-download/
