### ISSUE TITLE
how to use instrument's template in appium

### ISSUE THREAD

**Issue by wangtao169447** [appium/appium#7180]
## The problem
I wonder how to combine appium with instrument's template(such as Acitivity Monitor,Time profile).especially automationName is XCUITest

before i use appium ,i use command below 
`instruments -w #{device} -t #{automation_template_path} #{app_path} -e UIASCRIPT #{ui_custom_path} -e UIARESULTSPATH #{result_base_dir}` 
to collect different performance date during the autotest

## Environment
mac os 10.11.6
iphone simulator 10.0
appium 1.6
automationName XCUITest

**Comment by jlipps** [comment]
You can't. The UIAutomation Instrument and XCUITest are incompatible.
