### ISSUE TITLE
switch the context from NATIVE_APP to WebView issue

### ISSUE THREAD

**Issue by tomliuxin** [appium/appium#7182]
## The problem

C# code, after initialize the driver, switch the context from NATIVE_APP to WebView issue

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Desktop OS/version used to run Appium:  window
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: emulator
* Chrome browser version: 54.0.2840.85

## Link to Appium logs
https://gist.github.com/tomliuxin/48fd33436bcddd191fe14543b806e232

## Code To Reproduce Issue [ Good To Have ]
  DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.SetCapability("device", "Android");
            capabilities.SetCapability(CapabilityType.Platform, "Windows");
            capabilities.SetCapability("deviceName", deviceName);
            capabilities.SetCapability("platformName", "Android");
            capabilities.SetCapability("platformVersion", "7.0");
            capabilities.SetCapability("automationName", "uiautomator2");
            //capabilities.SetCapability("automationName", "Appium");
            capabilities.SetCapability("unicodeKeyboard", "True");
            capabilities.SetCapability("resetKeyboard", "True");
            capabilities.SetCapability("appPackage", appPackage);
            capabilities.SetCapability("appActivity", appActivity);
            capabilities.SetCapability("newCommandTimeout", "30000");

            Uri uri = new Uri(uriString);
            TimeSpan timeSpan = TimeSpan.FromMinutes(20);
            myDriver = new AndroidDriver<AppiumWebElement>(uri, capabilities, timeSpan);
           
            ReadOnlyCollection<string> contexts = myDriver.Contexts;

            for (int i = 0; i < contexts.Count; i++)
            {
                if (contexts[i].Contains("WEBVIEW"))
                {
                    myDriver.Context = contexts[i];
                    break;
                }
            }

**Comment by imurchie** [comment]
I don't know what happened to the logs in the gist, but they are unreadable.

**Comment by dpgraham** [comment]
```cs
myDriver.Context = contexts[i];
```

^ This doesn't invoke the REST call to ```/session/{sessionId}/context```

In order to set the context you need to call the 'setContext' method.

Try

```cs
myDriver.setContext(contexts[i]);
```
