### ISSUE TITLE
Could not find any web view. / Unable to identify ui elements after launching IOS 10.0 app

### ISSUE THREAD

**Issue by erarunsharma** [appium/appium#7183]
## The problem

We are able to launch IOS 10.0 app on iPhone 6s but now it says Could not find any web view

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac 
* Node.js version (unless using Appium.app|exe): v4.6.1
* Mobile platform/version under test: IOS10.0
* Real device or emulator/simulator: Real device iPhone 6s
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Appium able to launch IOS 10.0 native app but then its trying to find web views. We are not able to identify the UI elements

desired_capabilities={
            'app': '/Users/nagarro/Desktop/Melody_app/home-owner-app.app',
            'platformName': 'iOS',
            'platformVersion': '10.0',
            'deviceName': 'iPhone 6s',
            'automationName': 'XCUITest',
            'newCommandTimeout': 9000,
            'sendKeyStrategy': 'setValue',
            'autoWebview': True,
            'udid': udid,
            'realDeviceLogger': '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
        })

## Link to Appium logs

https://gist.github.com/erarunsharma/51ea3f179a721901acc241ef4ecb5525

## Code To Reproduce Issue [ Good To Have ]

1. Install appium 1.6.0 and all dependancies 
2. Add provisioning profile in WebDriverAgent
3. Run appium server
4. Observe logs

**Comment by VasilijSviridov** [comment]
also I noticed that there is some security issues on iOS10.0.* version, so automation works properly with real device on iOS 10.1 only.

**Comment by erarunsharma** [comment]
hi @imurchie I have tried to run ios-webkit-debug-proxy. I have successfully configured ios-webkit-debug-proxy and it says connected: 9222 to iPhone 6s

But after launching the app on iPhone 6s, it still says Could not find any webviews.

One more question i need to ask, is it possible to automate ios10.0 native app or it works with only webviews with mobilesafari browser?

**Comment by erarunsharma** [comment]
hi @imurchie, we have resolved the above issue by removing 'autoWebview': True property from desired capabilities. Now we are able to find UI elements in the ios10.0 native app.

**Comment by surajgupta7175** [comment]
Can you please paste the Appium logs...

**Comment by erarunsharma** [comment]
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"2EAA...
[Appium] New XCUITestDriver session created successfully, session adf0553c-73e1-4808-a2b8-4b6871067e1e added to master session list
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,...
[HTTP] <-- POST /wd/hub/session 200 24732 ms - 533 
[HTTP] --> POST /wd/hub/session/adf0553c-73e1-4808-a2b8-4b6871067e1e/timeouts/implicit_wait {"sessionId":"adf0553c-73e1-4808-a2b8-4b6871067e1e","ms":60000}
[MJSONWP] Calling AppiumDriver.implicitWait() with args: [60000,"adf0553c-73e1-4808-...
[debug] [XCUITest] Executing command 'implicitWait'
[debug] [BaseDriver] Set implicit wait to 60000ms
[MJSONWP] Responding to client with driver.implicitWait() result: null
[HTTP] <-- POST /wd/hub/session/adf0553c-73e1-4808-a2b8-4b6871067e1e/timeouts/implicit_wait 200 8 ms - 76 
[HTTP] --> POST /wd/hub/session/adf0553c-73e1-4808-a2b8-4b6871067e1e/element {"using":"accessibility id","sessionId":"adf0553c-73e1-4808-a2b8-4b6871067e1e","value":"CreateAccountSceen_BackToLoginButton"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["accessibility id","Create...
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 60000 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/2EAA9321-EE2E-4EF2-9F19-680FEA94B010/element] with body: {"using":"accessibility id"...
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"4DFEDA...
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"4DFEDAFF-162A-4...
[HTTP] <-- POST /wd/hub/session/adf0553c-73e1-4808-a2b8-4b6871067e1e/element 200 309 ms - 171 
[HTTP] --> POST /wd/hub/session/adf0553c-73e1-4808-a2b8-4b6871067e1e/element/4DFEDAFF-162A-4546-A264-427C9956EC0D/click {"sessionId":"adf0553c-73e1-4808-a2b8-4b6871067e1e","id":"4DFEDAFF-162A-4546-A264-427C9956EC0D"}
[MJSONWP] Calling AppiumDriver.click() with args: ["4DFEDAFF-162A-4546-A264-4...
[debug] [XCUITest] Executing command 'click'
[JSONWP Proxy] Proxying [POST /uiaElement/4DFEDAFF-162A-4546-A264-427C9956EC0D/scroll] to [POST http://localhost:8100/session/2EAA9321-EE2E-4EF2-9F19-680FEA94B010/uiaElement/4DFEDAFF-162A-4546-A264-427C9956EC0D/scroll] with body: {"toVisible":true}
[JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"2E...
[JSONWP Proxy] Proxying [POST /element/4DFEDAFF-162A-4546-A264-427C9956EC0D/click] to [POST http://localhost:8100/session/2EAA9321-EE2E-4EF2-9F19-680FEA94B010/element/4DFEDAFF-162A-4546-A264-427C9956EC0D/click] with body: {}
[JSONWP Proxy] Got response with status 200: {"status":0,"id":"4DFEDAFF-...
[MJSONWP] Responding to client with driver.click() result: ""
[HTTP] <-- POST /wd/hub/session/adf0553c-73e1-4808-a2b8-4b6871067e1e/element/4DFEDAFF-162A-4546-A264-427C9956EC0D/click 200 1018 ms - 74

**Comment by dpgraham** [comment]
Closing this. If this is still an issue, please re-open.
