### ISSUE TITLE
press touch action with multiple move_to fails

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/appium#7184]
## The problem

Given the following complex touch action:

```
Appium::TouchAction.new.press(element: item, x: 20, y: 20).wait(200).move_to(element: myElement, x: 5, y: 5).wait(200).move_to(element: myOtherElement, x: 100, y: 20).release.perform
```

This action will fail with the error:
```
Selenium::WebDriver::Error::UnknownError: Support for gestures other than Tap is not yet implemented. Please contact an Appium dev
```

Removing the second move_to and wait from the touch action causes the action to occur, with no error message.

This worked in Appium 1.5.3

Appium log: https://gist.github.com/VivaLosDoyers/156fecb2acd3732898241e198f91036c

Caps:
```
platformName = "iOS"
app = "~/appium/myApp.app"
platformVersion = "9.3"
deviceName = "iPad Retina"
fullReset = "true"
automationName = "XCUITest"
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: OS X 10.12.1
* Node.js version (unless using Appium.app|exe): 7.0.0
* Mobile platform/version under test: iOS 9.3
* Real device or emulator/simulator: sim
* Appium CLI or Appium.app|exe: CLI

**Comment by imurchie** [comment]
Yes. As of now Apple has not provided any way to do such _ad hoc_ gestures.

**Comment by VivaLosDoyers** [comment]
Just curious if this situation as improved at all? I've seen improvements to swiping in the XCUITest driver, but it seems multitouch actions are still not possible?

**Comment by jlipps** [comment]
We are still blocked on this because we have no way to implement ad hoc gestures in XCUITest still. I'm going to close this as it doesn't look like there will be anything we can do for some time.
