### ISSUE TITLE
Appium closes upon tapping 'Launch' button

### ISSUE THREAD

**Issue by 907howard** [appium/appium#7186]
## The problem

 I am facing a weird bug with appium 1.5.3 ara version, Hitting on launch button closes appium.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3(Ara)
* Last Appium version that did not exhibit the issue (if applicable):1.4
* Desktop OS/version used to run Appium:Macbook Pro (Retina)
* Node.js version (unless using Appium.app|exe):Appium.exe
* Mobile platform/version under test:Android 5.1.1
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:Appium.exe

## Details
This happens if I do the following:
1.launch appium 
2.Hit on the 'Launch' button and then when it shows the appium server is running then hit on the 'Stop' button again.
3.Now again tap on the 'Launch' button and note that the appium will close on its own.

## Link to Appium logs

NA

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by mykola-mokhnach** [comment]
It's hardly possible to say anything here without logs and screenshots. Also, the issue description is unclear.

**Comment by surajgupta7175** [comment]
Uncheck the Radio button "Kill Processes Using Server Port Before Launch"  present in General Settings
