### ISSUE TITLE
Could not proxy command to remote server

### ISSUE THREAD

**Issue by echonox** [appium/appium#7187]
## The problem

Can't do backend calls

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: N/A
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: Android 5.1.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

I am using WDIO with CucumberJS and Appium when running the test case it runs fine (filing inputs, clicking buttons, getting text and etc) until it reaches to the point where it does http request to backend (login call) and the test crashes with this error:

An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up

## Link to Appium logs

wdio.conf.js:

https://gist.github.com/echonox/bc20b72207c21805e9f5010f6d7c357e

appium.log:

https://gist.github.com/echonox/0189281689819a1c2b669cf39e97fa89

package.json:

https://gist.github.com/echonox/a0e2d5e74f4e30281cc4fa52f8f8b5d6

**Comment by imurchie** [comment]
Can you look in the device logs for any indication of Selendroid crashing?

**Comment by mykola-mokhnach** [comment]
@echonox please provide adb log as well. Probably, Selendroid crashed at this point.

**Comment by CYsuncheng** [comment]
the reason is selendroid ?  I met the error too, and how to handle it ?
