### ISSUE TITLE
Android webview contains empty html source, can't find elements

### ISSUE THREAD

**Issue by tomliuxin** [appium/appium#7188]
## The problem

unknown error: operation is unsupported on Android
  (Session info: chrome=51.0.2704.91)
  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 10.0 x86_64)

## Environment
* Appium version (or git revision) that exhibits the issue: 1.6.0
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe):6.9.1
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: emulator
* Chrome driver version: 2.20.0
* Chrome browser version: 54.*.**

## Details

After changed the driver context from NATIVE_APP to WEBVIEW_****(app package), and then want to use the below code to get the screen size:
int Screen_Y = myDriver.Manage().Window.Size.Height;    (C# code)

## Link to Appium logs
[debug] [Chromedriver] Changed state to 'online'
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/2bd9612e-5f5c-42d9-907e-8ed7dd3ca284/context 200 8285 ms - 76
[HTTP] --> GET /wd/hub/session/2bd9612e-5f5c-42d9-907e-8ed7dd3ca284/window/current/size {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [GET /wd/hub/session/2bd9612e-5f5c-42d9-907e-8ed7dd3ca284/window/current/size] to [GET http://127.0.0.1:8000/wd/hub/session/f0e1c69aeddffb14d868f9c8ba205037/window/current/size] with body: {}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"f0e1c69aeddffb14d868f9c8ba205037\",\"status\":13,\"value\":{\"message\":\"unknown error: operation is unsupported on Android\\n  (Session info: chrome=51.0.2704.91)\\n  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 10.0 x86_64)\"}}"
[JSONWP Proxy] Replacing sessionId f0e1c69aeddffb14d868f9c8ba205037 with 2bd9612e-5f5c-42d9-907e-8ed7dd3ca284
[HTTP] <-- GET /wd/hub/session/2bd9612e-5f5c-42d9-907e-8ed7dd3ca284/window/current/size 200 24 ms - 294
[HTTP] --> DELETE /wd/hub/session/2bd9612e-5f5c-42d9-907e-8ed7dd3ca284 {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["2bd9612e-5f5c-42d9-907e-8ed7dd3ca284"]
[debug] [UiAutomator2] Deleting UiAutomator2 session
[debug] [AndroidDriver] Stopping chromedriver for context WEBVIEW_com.microsoft.flow.nightly
[debug] [Chromedriver] Changed state to 'stopping'
[JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8000/wd/hub/session/f0e1c69aeddffb14d868f9c8ba205037] with no body

.

**Comment by mykola-mokhnach** [comment]
It might be the issue similar to https://github.com/appium/appium/issues/7128
Shortly saying, modern chrome driver, which is included into Appium 1.6, does not support older browser versions anymore (<54)

**Comment by tomliuxin** [comment]
@mykola-mokhnach,Thanks. 

Yes, I was using the chrome browser version is 54.0.2840.85, but still met this issue.

unknown error: operation is unsupported on Android
  (Session info: chrome=51.0.2704.91)
  (Driver info: chromedriver=2.20.353145 (343b531d31eeb933ec778dbcf7081628a1396067),platform=Windows NT 10.0 x86_64)

**Comment by sravanmedarapu** [comment]
You need to switch back the context to NATIVE_APP to get the window size.

**Comment by tomliuxin** [comment]
@sravanmedarapu , you mean, when get the window size, or PressKeycode, need to switch back to NATIVE_APP, and when findElement, need to switch to WEBVIEW_, right?

**Comment by sravanmedarapu** [comment]
Yeah, to interact elements with in WEBVIEW, you need to switch to WEBVIEW. For rest of all general actions, you need to switch back to default context i.e NATIVE_APP.

**Comment by tomliuxin** [comment]
@sravanmedarapu, yes, context is NATIVE_APP, can general actions (pressKeycode, get window size)
but after I switch back to WEBVIEW to get the element, met the issue too

[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.microsoft.flow.nightly"]
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/feb8910d-f95a-4043-a592-5dcffb21411a/context 200 118 ms - 76
[HTTP] --> GET /wd/hub/session/feb8910d-f95a-4043-a592-5dcffb21411a/context {}
[MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["feb8910d-f95a-4043-a592-5dcffb21411a"]
[MJSONWP] Responding to client with driver.getCurrentContext() result: "WEBVIEW_com.microsoft.flow.nightly"
[HTTP] <-- GET /wd/hub/session/feb8910d-f95a-4043-a592-5dcffb21411a/context 200 5 ms - 108
[HTTP] --> POST /wd/hub/session/feb8910d-f95a-4043-a592-5dcffb21411a/element {"using":"class name","value":"android.webkit.WebView"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/feb8910d-f95a-4043-a592-5dcffb21411a/element] to [POST http://127.0.0.1:8000/wd/hub/session/d8e6ea2b9c68c52ba677c985eb43b846/element] with body: {"using":"class name","value":"android.webkit.WebView"}
[JSONWP Proxy] Got response with status 200: **{"sessionId":"d8e6ea2b9c68c52ba677c985eb43b846","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"class name\",\"selector\":\"android.webkit.WebView\"}\n  (Session info: chrome=51.0.2704.91)\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 10.0 x86_64)"}}**

**Comment by sravanmedarapu** [comment]
Typically elements under(child elements) `android.webkit.WebView` will be considered as WEBVIEW, here you are referring  `android.webkit.WebView` in webview context which is not valid.
Refer for finding element properties in webview. https://developers.google.com/web/tools/chrome-devtools/remote-debugging

**Comment by tomliuxin** [comment]
@sravanmedarapu , Thanks. 

after used the remote-debugging, got my app is: WebView in com.microsoft.flow.nightly (51.0.2704.91)
and then inspect it, got the app one element is:
 <input class = "text-input ng-pristine ng-valid ng-touched" ******>
if I can use the code: 
Driver.FindElement(By.CssSelector("input.text-input ng-pristine ng-valid ng-touched"))
to get this element? 

{"sessionId":"e0d9c4da7314f70b0567a2788e4d014f","status":7,"value":{"message":"no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"input.text-input ng-pristine ng-valid ng-touched\"}\n  (Session info: chrome=51.0.2704.91)\n  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 10.0 x86_64)"}}

**Comment by sravanmedarapu** [comment]
Please make sure CssSelector you are using is valid.

**Comment by tomliuxin** [comment]
I think CssSelector value is correct, could you help to double check it? Thanks.

I try to use the below code to find button:
 myDriver.FindElementByCssSelector("button.skip-button").Click();
 myDriver.FindElementByCssSelector("button[class*='skip-button']").Click();
 myDriver.FindElementByCssSelector("div.app-root button").Click();

The UI like:
![capture](https://cloud.githubusercontent.com/assets/23069744/20088505/6141aa3c-a5bb-11e6-954f-273a0af18b71.PNG)

**Comment by sravanmedarapu** [comment]
Aren't you able to find element with `myDriver.FindElementByCssSelector("button.skip-button")` ?

**Comment by tomliuxin** [comment]
@sravanmedarapu , Yesh, I can't able to find element with that.
maybe due to I can't enable WEBVIEW?
C# how to enable that?

**Comment by ledinhphuong** [comment]
Maybe, It belongs to chromedriver not support your Chrome. Please take a look the [docs](https://www.npmjs.com/package/appium-chromedriver) to know how to update/change chromedriver version to support your Chrome.

**Comment by sravanmedarapu** [comment]
@tomliuxin, Can you share result of getPageSource() after switching WEBVIEW context in a separate gist.

**Comment by tomliuxin** [comment]
@sravanmedarapu, Thanks. 

the appium log:
https://gist.github.com/tomliuxin/43f89edebdb0064c90c4b704e9c303dc#file-after-switch-context

**Comment by sravanmedarapu** [comment]
@tomliuxin, I have requested page source. 
 you can get the page source by executing `driver.getPageSource()`

**Comment by tomliuxin** [comment]
@sravanmedarapu, Thanks. 
sorry, my mistaked. 

Maybe I got the reason, why can't find element.
after switch context, got the page source is:
<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body></body></html>
 NO any element.

**Comment by tomliuxin** [comment]
@sravanmedarapu 
switch to NATIVE_APP context, the page source is:
https://gist.github.com/tomliuxin/f8a2a4bf4d62d63d1bc16c73e23fe406#file-native_app
(but only have webview element, NO button, textboxt element)

but switch to WEBVIEW_ context, the page source is:
![capture](https://cloud.githubusercontent.com/assets/23069744/20090389/d2e425f0-a5c7-11e6-9a04-22763f603c1f.PNG)
(no any element)

do you know why? build apk issue? Thanks.

**Comment by mykola-mokhnach** [comment]
WEBVIEW element inside application uses Chrome renderer as well. This renderer is usually integrated with the corresponding library (for example Cordova) and can be different from the system browser. You can either try to update this component in your application to the most recent available version and hope it contains supported chrome libraries. Or downgrade Appium driver, which supports older browser versions, which I don't recommend it.

**Comment by tomliuxin** [comment]
@sravanmedarapu 
the page source is: 
https://gist.github.com/tomliuxin/43f89edebdb0064c90c4b704e9c303dc#file-after-switch-context

is not same as the below UI

![capture](https://cloud.githubusercontent.com/assets/23069744/20093455/c622cea6-a5d7-11e6-8224-ab056f4b42a3.PNG)

**Comment by jlipps** [comment]
@tomliuxin are you sure you're in the right webview? sometimes there are multiple

**Comment by tomliuxin** [comment]
@sravanmedarapu, the source as below.
https://gist.github.com/tomliuxin/43f89edebdb0064c90c4b704e9c303dc

sometimes, the page source is hiddenform, there is NO any element, so can't find the element.

**Comment by rkavalap** [comment]
@tomliuxin  Can you install appium@beta So you get the latest chromedriver and post the appium server logs as a gist. appium beta installs chromedriver v2.25 which supports the latest chrome browser as well.

**Comment by tomliuxin** [comment]
@sravanmedarapu , @rkavalap Thanks for help. 
I have solved the chrome driver/browser issue, and I can find the element for my app at some page when use the ChromeDeveloperTool
but for my app, some of page source is 'hiddenform', see 
https://gist.github.com/tomliuxin/43f89edebdb0064c90c4b704e9c303dc

for this page, how can I get the UI element?

**Comment by rkavalap** [comment]
@tomliuxin If you can see the page source from chrome devtools, you should be able to get the same source via chromedriver. the only scenario i see this might be failing would be you are connecting to the incorrect web view as jlipps mentioned. 

Can you post the output of adb for the below 2 commands  
adb devices
adb -s <device> shell “cat /proc/net/unix | grep devtools_remote”

If the webviews listed in the above commands are showing up in the appium log, then you may not be setting the correct context. If you still believe that you are connecting to right webview context and get a hidden form, this is more of a chrome / chromedriver issue. You may want to post this question on chrome-discuss google group for some info.

**Comment by tomliuxin** [comment]
@rkavalap 

C:\Users\v-tomliu>adb shell "cat /proc/net/unix | grep devtools_remote"
00000000: 00000002 00000000 00010000 0001 01 13173 @webview_devtools_remote_2357
00000000: 00000003 00000000 00000000 0001 03 13675 @webview_devtools_remote_2357

**Comment by tomliuxin** [comment]
@rkavalap 
Type more information for it. 
there are 2 context I got using the code: Driver.Contexts:
NATIVE_APP
WEBVIEW_com.microsoft.flow.nightly    (com.microsoft.flow.nightly is my app package name)

and firstly, the context is NATIVE_APP, I executed the code PressKeycode to press Enter key to go to the app signin page, 
then I switch the context to : WEBVIEW_com.microsoft.flow.nightly, I can get the element for 'Username', 'Password' textbox, after type the value and click SignIn button, go to the next page, 
using the Driver.pagesource to get the page source, the source is hidden form.

**Comment by tomliuxin** [comment]
and I found in some page, I got the webview from adb:
C:\Users\v-tomliu>adb shell "cat /proc/net/unix | grep devtools_remote"
00000000: 00000002 00000000 00010000 0001 01 134408 @webview_devtools_remote_14151

in appium log:
[debug] [AndroidDriver] WEBVIEW_14151 mapped to pid 14151
[debug] [AndroidDriver] Getting process name for webview

both are 14151, you mean I set the incorrect to WebView at that page? so got the hidden form?

**Comment by tomliuxin** [comment]
@rkavalap  
debug again:
C:\Users\v-tomliu>adb shell "cat /proc/net/unix | grep devtools_remote"
00000000: 00000002 00000000 00010000 0001 01 28983 @webview_devtools_remote_3997
00000000: 00000003 00000000 00000000 0001 03 36847 @webview_devtools_remote_3997
00000000: 00000003 00000000 00000000 0001 03 36849 @webview_devtools_remote_3997

appium log:
[debug] [AndroidDriver] WEBVIEW_3997 mapped to pid 3997
[debug] [AndroidDriver] Getting process name for webview
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'E:\Android\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[debug] [AndroidDriver] Parsed pid: 3997 pkg: com.microsoft.flow.nightly!
[debug] [AndroidDriver] from: u0_a78,3997,1234,1850804,245516,SyS_epoll_,00000000,S,com.microsoft.flow.nightly
[debug] [AndroidDriver] returning process name: com.microsoft.flow.nightly
[debug] [AndroidDriver] Found webviews: ["WEBVIEW_com.microsoft.flow.nightly"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","WEBVIEW_com.microsoft.flow.nightly"]

Set the context to: WEBVIEW_com.microsoft.flow.nightly
I think I set the correct context.

**Comment by rkavalap** [comment]
@tomliuxin From what you describe, 
I am assuming you are trying to launch the app using (PressKeyCode).
You have liveid signin page on your device. 
You switched to webview at this stage you should see the signin page. 

I don't see any issue so far. After you entered the credentials do you have something shown on the screen ? or are you having trouble logging into using live id ?

**Comment by tomliuxin** [comment]
@rkavalap 
Yes, after entered credentials (signed in), the next page shown at the screen, NO any issue into logging. 

not sure, why in sign in page, I can get the page source, I can get the element,
but in next page, it is hidden form.

**Comment by rkavalap** [comment]
These are few things I would try. 
After you are signed in. open chrome browser
chrome://inspect/#devices
Select the device and click sources. If you see the sources different from what you received in chromedriver vs chrome then it's chrome related bug. (I am very doubtful of this).

If they match, you should go talk to your server side developers / client developers to figure out how your views are rendered. I am sorry, At this point i don't think the issue itself is related to appium.

**Comment by tomliuxin** [comment]
@rkavalap  Thanks for help. 

after singed in, I got the below page, and chrome://inspect/#devices, got the below sources:
![untitled](https://cloud.githubusercontent.com/assets/23069744/20164596/9c2b5b6c-a740-11e6-9357-248ddd133bac.png)

but in my C# code, I got the sources is: hidden form:
....form method="POST" name="hiddenform" action="....

**Comment by tomliuxin** [comment]
@rkavalap, Yes, I don't think it is appium issue. 

another question, manually control my app, after signed in, if you open the app again, it is signed in. 
but using the Uiautomator2 to run the cases, after initialize the driver, the app is not sign in even the last time the app signed in. 
how can i keep the cookie/Catch for my app? 

I try to add the below code, 
 capabilities.SetCapability(CapabilityType.SupportsApplicationCache, "True");
it is not work

**Comment by tomliuxin** [comment]
Thanks @rkavalap , @sravanmedarapu, All help, the issue solved. Thanks again.

**Comment by SakethPullagura** [comment]
@tomliuxin : Could you help with the solution for this problem. I am facing exactly the same issue and tried all the options suggested here. Still i am not able to see any element after login page. checked with pagesource. It shows empty body, but the chrome inspect is showing all the webview elements.
