### ISSUE TITLE
Cannot long press on an element in ios

### ISSUE THREAD

**Issue by shay777** [appium/appium#7189]
## The problem

Hello,
I am facing an issue regarding long press in ios 10. 
I am using java client 3.4.1
Seems that it is not supported. I tried some workarounds like:
action.press(audio).waitAction(2000).release().perform(); 
but didn't manage to solve the issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: mac sierra
* Node.js version (unless using Appium.app|exe):4.2.1
* Mobile platform/version under test: ios 10
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

I need to perform a long press on a certain element but i get an error of:

org.openqa.selenium.WebDriverException: Support for gestures other than Tap is not yet implemented. Please contact an Appium dev (WARNING: The server did not provide any stacktrace information)

## Link to Appium logs

https://gist.github.com/shay777/b0d5acbdee4be5fdb868e92b5baf45f4

Is it possible to long press an element?

thanks

**Comment by mykola-mokhnach** [comment]
Try to update java_client module

**Comment by shay777** [comment]
@mykola-mokhnach  thanks for your reply.
I already tried it. I upgraded to java-client 4.1.2 but the error still appears.
Anything I miss here?

**Comment by mykola-mokhnach** [comment]
We use direct WDA API call to perform long tap and workaround Appium stuff for now:

```java
   public JSONObject touchAndHold(String sessionId, String uuid, double durationSeconds) throws RESTError {
        final Builder webResource = buildDefaultRequest(String.format("uiaElement/%s/touchAndHold", uuid), sessionId);
        final JSONObject body = new JSONObject();
        body.put("duration", durationSeconds);
        return waitForResponse(() -> restHandlers.httpPost(webResource, body.toString(), new int[]{HttpStatus.SC_OK}));
    }
```

Probably, there is a better solution for this (or it could be already fixed in 1.6.1beta)

**Comment by imurchie** [comment]
This ought to work in 1.6.1.

**Comment by shay777** [comment]
thank you for clarifying it

**Comment by dodigital** [comment]
@imurchie can confirm this works now on 1.6.1
