### ISSUE TITLE
Cannot scroll on iOS in WebView using javascript for UIA automator

### ISSUE THREAD

**Issue by MSI15** [appium/appium#7190]
## The problem
Cannot scroll to an element on webView in an iOS app.

## Environment

Appium Version 1.6
Appium java client version 1.4.2
Real iOS device: iPhone 6 plus, OS version 9.3.2
Tested on iOS app that contains a webView

## Details

I was trying to scroll to an element on web view that is embedded in the mobile app. Therefore I used the script below that worked before:

JavascriptExecutor executor = driver;
 executor.executeScript ("target.frontMostApp().mainWindow().scrollViews()[0].webViews()[0].staticTexts()[\"These Terms and Conditions were last updated in June 2015.\"].scrollToVisible();");

This no longer works throwing an error as below:

org.openqa.selenium.WebDriverException: Cannot perform action on invalid element: UIAElementNil from target.frontMostApp().mainWindow().scrollViews()[0].webViews()[0].staticTexts()["These Terms and Conditions were last updated in June 2015."] (WARNING: The server did not provide any stacktrace information)

## Link to Appium logs

Full appium log is as below:

[HTTP] --> POST /wd/hub/session/8551fdd1-9b1f-416b-ac5a-fb207e04467a/execute {"script":"target.frontMostApp().mainWindow().webViews()[0].staticTexts()[\"These Terms and Conditions were last updated in June 2015.\"].scrollToVisible();","args":[]}
[MJSONWP] Calling AppiumDriver.execute() with args: ["target.frontMostApp().mai...
[debug] [iOS] Executing iOS command 'execute'
[debug] [UIAuto] Sending command to instruments: target.frontMostApp().mainWindow().webViews()[0].staticTexts()["These Terms and Conditions were last updated in June 2015."].scrollToVisible();
[debug] [Instruments] [INST] 2016-11-15 20:04:11 +0000 Debug: Running system command #13: /usr/local/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/gy/6d1zry216qsb0zh_bjjfr6j40000gn/T/instruments_sock 2,{"status":0,"value":true}...
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Debug: Got new command 13 from instruments: target.frontMostApp().mainWindow().webViews()[0].staticTexts()["These Terms and Conditions were last updated in June 2015."].scrollToVisible();
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Debug: evaluating target.frontMostApp().mainWindow().webViews()[0].staticTexts()["These Terms and Conditions were last updated in June 2015."].scrollToVisible();
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Debug: Cannot perform action on invalid element: UIAElementNil from target.frontMostApp().mainWindow().webViews()[0].staticTexts()["These Terms and Conditions were last updated in June 2015."]
[debug] [UIAuto] Socket data received (213 bytes)
[debug] [UIAuto] Got result from instruments: {"status":17,"value":"Cannot perform action on invalid element: UIAElementNil from target.frontMostApp().mainWindow().webViews()[0].staticTexts()[\"These Terms and Conditions were last updated in June 2015.\"]"}
[HTTP] <-- POST /wd/hub/session/8551fdd1-9b1f-416b-ac5a-fb207e04467a/execute 500 1082 ms - 274
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Error: VerboseError: Cannot perform action on invalid element: UIAElementNil from target.frontMostApp().mainWindow().webViews()[0].staticTexts()["These Terms and Conditions were last updated in June 2015."]
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Error: Error during eval: scrollToVisible@[native code]
       eval code
eval@[native code]
startProcessing@file:///Users/amayah/65F435AD-D6CA-4A52-8DB3-5C0CEF742915/bootstrap-9cbf3ea225b36a29.js:2794:30
bootstrap@file:///Users/amayah/65F435AD-D6CA-4A52-8DB3-5C0CEF742915/bootstrap-9cbf3ea225b36a29.js:2862:31
global code@file:///Users/amayah/65F435AD-D6CA-4A52-8DB3-5C0CEF742915/bootstrap-9cbf3ea225b36a29.js:2875:10
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Debug: Running system command #14: /usr/local/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/gy/6d1zry216qsb0zh_bjjfr6j40000gn/T/instruments_sock 2,{"status":17,"value":"Cannot perform action on invalid element: UIAElementNil from target.frontMostApp().mainWin...

## Code To Reproduce Issue [ Good To Have ]

JavascriptExecutor executor = driver;
 executor.executeScript ("target.frontMostApp().mainWindow().scrollViews()[0].webViews()[0].staticTexts()[\"These Terms and Conditions were last updated in June 2015.\"].scrollToVisible();");

**Comment by rkavalap** [comment]
Can we have gist of appium server logs to investigate the issue.

**Comment by imurchie** [comment]
Yes, UI Automation no longer exists in Xcode 8+/iOS 10+, so scripting based on it will not work.

**Comment by MSI15** [comment]
I have added the appium logs, please also find the logs as below. The script used still works on iOS apps developed using Xcode 8 and only doesn't work in the case of webViews:

[HTTP] --> POST /wd/hub/session/8551fdd1-9b1f-416b-ac5a-fb207e04467a/execute {"script":"target.frontMostApp().mainWindow().webViews()[0].staticTexts()[\"These Terms and Conditions were last updated in June 2015.\"].scrollToVisible();","args":[]}
[MJSONWP] Calling AppiumDriver.execute() with args: ["target.frontMostApp().mai...
[debug] [iOS] Executing iOS command 'execute'
[debug] [UIAuto] Sending command to instruments: target.frontMostApp().mainWindow().webViews()[0].staticTexts()["These Terms and Conditions were last updated in June 2015."].scrollToVisible();
[debug] [Instruments] [INST] 2016-11-15 20:04:11 +0000 Debug: Running system command #13: /usr/local/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/gy/6d1zry216qsb0zh_bjjfr6j40000gn/T/instruments_sock 2,{"status":0,"value":true}...
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Debug: Got new command 13 from instruments: target.frontMostApp().mainWindow().webViews()[0].staticTexts()["These Terms and Conditions were last updated in June 2015."].scrollToVisible();
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Debug: evaluating target.frontMostApp().mainWindow().webViews()[0].staticTexts()["These Terms and Conditions were last updated in June 2015."].scrollToVisible();
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Debug: Cannot perform action on invalid element: UIAElementNil from target.frontMostApp().mainWindow().webViews()[0].staticTexts()["These Terms and Conditions were last updated in June 2015."]
[debug] [UIAuto] Socket data received (213 bytes)
[debug] [UIAuto] Got result from instruments: {"status":17,"value":"Cannot perform action on invalid element: UIAElementNil from target.frontMostApp().mainWindow().webViews()[0].staticTexts()[\"These Terms and Conditions were last updated in June 2015.\"]"}
[HTTP] <-- POST /wd/hub/session/8551fdd1-9b1f-416b-ac5a-fb207e04467a/execute 500 1082 ms - 274
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Error: VerboseError: Cannot perform action on invalid element: UIAElementNil from target.frontMostApp().mainWindow().webViews()[0].staticTexts()["These Terms and Conditions were last updated in June 2015."]
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Error: Error during eval: scrollToVisible@[native code]
       eval code
eval@[native code]
startProcessing@file:///Users/amayah/65F435AD-D6CA-4A52-8DB3-5C0CEF742915/bootstrap-9cbf3ea225b36a29.js:2794:30
bootstrap@file:///Users/amayah/65F435AD-D6CA-4A52-8DB3-5C0CEF742915/bootstrap-9cbf3ea225b36a29.js:2862:31
global code@file:///Users/amayah/65F435AD-D6CA-4A52-8DB3-5C0CEF742915/bootstrap-9cbf3ea225b36a29.js:2875:10
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-11-15 20:04:12 +0000 Debug: Running system command #14: /usr/local/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/gy/6d1zry216qsb0zh_bjjfr6j40000gn/T/instruments_sock 2,{"status":17,"value":"Cannot perform action on invalid element: UIAElementNil from target.frontMostApp().mainWin...
