### ISSUE TITLE
Unable to install appium without specifying version

### ISSUE THREAD

**Issue by amirwaisman** [appium/appium#7191]
## The problem

unable to run the command:

_npm install -g appium_

It gives the following errors:

> appium@1.6.0-beta1 prepublish /Users/amirwaisman/appium
> gulp prepublish

module.js:474
    throw err;
    ^

Error: Cannot find module 'appium-gulp-plugins'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/amirwaisman/appium/gulpfile.js:9:19)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

npm ERR! addLocal Could not install /Users/amirwaisman/appium
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! appium@1.6.0-beta1 prepublish: `gulp prepublish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium@1.6.0-beta1 prepublish script 'gulp prepublish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the appium package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp prepublish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs appium
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls appium
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/amirwaisman/npm-debug.log

## Environment

`node -v
v7.0.0`

`npm -v
3.10.8
`

## Details

Only when using "npm install -g appium@<version>" the installation works.

**Comment by rkavalap** [comment]
Closing as Unable to repro this issue. appium 1.6.0 installs fine for me with npm install appium
