### ISSUE TITLE
Encountered internal error running command: Error: Xcode version [object Object] is not yet supported

### ISSUE THREAD

**Issue by gaponte1985** [appium/appium#7193]
Xcode version 8.1 
Appium Version 1.5.3 (Ara)

2016-11-07 11:19:23:542 - [MJSONWP] Encountered internal error running command: Error: Xcode version [object Object] is not yet supported
    at handleUnsupportedXcode (lib/simulator.js:15:11)
    at getDeviceString$ (lib/simulator.js:44:3)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**Comment by imurchie** [comment]
Appium 1.5.3 will not work with Xcode 8+. You will need 1.6 and you will
need to use the xcuitest automationName.

**Comment by gaponte1985** [comment]
use the xcuitest automationName. what you meant with this.

**Comment by imurchie** [comment]
I mean use the 'automationName' capability, and set it to "xcuitest". Xcode
8 removed the system Appium used to automate iOS, so an entirely different
mechanism is used now.

**Comment by gaponte1985** [comment]
how can i install 1.6 appiun?

**Comment by imurchie** [comment]
`npm install -g appium` (for 1.6.0) or `npm install -g appium@beta` (for 1.6.1 beta).

**Comment by gaponte1985** [comment]
npm WARN engine appium@1.6.1-beta: wanted: {"node":">=4","npm":">=3"} (current: {"node":"4.4.5","npm":"2.15.5"})
npm ERR! tar.unpack untar error /Users/aponte/.npm/appium/1.6.1-beta/package.tgz
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@beta"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path /usr/local/lib/node_modules/appium
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/appium']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/appium',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/appium',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:

**Comment by imurchie** [comment]
You must have installed node/npm (or perhaps a version of Appium) with sudo. You need to change the permissions on `/usr/local/lib/node_modules/appium`, though you probably want to do it for `/usr/local/lib/node_modules` entirely, or installing anything with npm might be a problem.

**Comment by rkavalap** [comment]
Closing issue as xcode 8 support is from appium v1.6 and above.

**Comment by gaponte1985** [comment]
I mean use the 'automationName' capability, and set it to "xcuitest". Xcode
8 removed the system Appium used to automate iOS, so an entirely different
mechanism is used now.

I dont get it

**Comment by imurchie** [comment]
There is a desired capability `automationName`. In order to automate with Xcode 8.1 you need to set it to `"XCUITest"`. This is because Apple has completely changed how they automate, starting with Xcode 8. The old mechanism, which Appium made use of, no longer exists.

**Comment by mkhb654** [comment]
So just to be clear you guys are recommending in the below code base add xcuitest method desiredCapabilities and run the script.  This will kick off AppiumTest.  



public class AppiumTest {

        String receipeName = "Recipe Name";
        String saveRecipe = "//UIAApplication[1]/UIAWindow[2]/UIANavigationBar[1]/UIAButton[3]";
        public AppiumDriver<MobileElement> driver;
        public WebDriverWait wait;
        @Before
        public void setUp() throws Exception {
            // set up appium for android instance
            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
            capabilities.setCapability(MobileCapabilityType.APP, "/Users//Desktop/ApiDemos-App.app");
            driver = new IOSDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
            wait = new WebDriverWait(driver, 30);
        }
        @After
        public void tearDown() throws Exception {
            driver.quit();
        }


    }

**Comment by imurchie** [comment]
@mkhb654 XCUITest is iOS. I'm unclear at all what your snippet has to do with this issue.

**Comment by sglebs** [comment]
Those who use the appium binaries from https://bitbucket.org/appium/appium.app/downloads/
 beware: it is 1.5.3, at the time of this writing. It won't work if you have Xcode 8 you will have to wait for newer binaries or launch from the console (no GUI/app).

**Comment by imurchie** [comment]
There is a beta of a new GUI. See https://github.com/appium/appium-desktop#appium-desktop-

**Comment by sglebs** [comment]
Another tip is to use the GUI 1.5.3 binary from https://bitbucket.org/appium/appium.app/downloads/ and configure it to use a newer/external Appium. In the GUI: Developer Settings / Enable. Use External Appium Package. It worked for me.
