### ISSUE TITLE
Appium client has  Crashed 

### ISSUE THREAD

**Issue by Tanmoyray** [appium/appium#7196]
## The problem

When i click appium inspector , app has launched and then Applium client has crashed.

## Link to Appium logs

Tanmoys-Mac-mini:~ tanmoyray$ appium
[Appium] Welcome to Appium v1.5.3 (REV 47d57ca99526d47897a0bbe98a1f6a5ba466167f)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 38 ms - 121 
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 3 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","appPackage":"com.senrysa.veiculu","newCommandTimeout":"7200","app":"/Users/tanmoyray/Documents/AndroidApk/Veikulu/veiculu.apk","platformVersion":"4.2.2","deviceName":"Andy4.2.2","automationName":"Appium"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android",...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   platformName: 'Android'
[Appium]   appPackage: 'com.senrysa.veiculu'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/tanmoyray/Documents/AndroidApk/Veikulu/veiculu.apk'
[Appium]   platformVersion: '4.2.2'
[Appium]   deviceName: 'Andy4.2.2'
[Appium]   automationName: 'Appium'
[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
[BaseDriver] Session created with session id: f3fb9f1b-a4dd-421c-a802-017047b2d727
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_91
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/tanmoyray/library/android/sdk/platform-tools/adb
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Looking for a device with Android 4.2.2
[debug] [ADB] Setting device id to 192.168.56.100:5555
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","getprop","ro.build.version.release"]
[AndroidDriver] Using device: 192.168.56.100:5555
[ADB] Checking whether adb is present
[ADB] Using adb from /Users/tanmoyray/library/android/sdk/platform-tools/adb
[debug] [ADB] Setting device id to 192.168.56.100:5555
[BaseDriver] Using local app '/Users/tanmoyray/Documents/AndroidApk/Veikulu/veiculu.apk'
[debug] [AndroidDriver] Checking whether app is actually present
[AndroidDriver] Starting Android session
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","install","/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/io.appium.settings/bin/settings_apk-debug.apk"]
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","install","/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","getprop","ro.build.version.release"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","dumpsys","window"]
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [AndroidDriver] Parsing package and activity from app manifest
[ADB] Checking whether aapt is present
[ADB] Using aapt from /Users/tanmoyray/library/android/sdk/build-tools/24.0.1/aapt
[ADB] Extracting package and launch activity from manifest
[debug] [ADB] badging package: com.senrysa.veiculu
[debug] [ADB] badging act: com.senrysa.veiculu.SplashScreen
[debug] [AndroidDriver] Parsed package and activity are: com.senrysa.veiculu/com.senrysa.veiculu.SplashScreen
[AndroidDriver] Remote apk path is /data/local/tmp/929089c84f54b3758209ce83db622944.apk
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","ls","/data/local/tmp/929089c84f54b3758209ce83db622944.apk"]
[debug] [AndroidDriver] Checking if app is installed
[debug] [ADB] Getting install status for com.senrysa.veiculu
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","getprop","ro.build.version.sdk"]
[debug] [ADB] Device API level: 17
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","pm","list","packages","-3","com.senrysa.veiculu"]
[debug] [ADB] App is  installed
[AndroidDriver] Apk is already on remote and installed, resetting
[debug] [AndroidDriver] Running fast reset (stop and clear)
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","am","force-stop","com.senrysa.veiculu"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","pm","clear","com.senrysa.veiculu"]
[debug] [AndroidDriver] Extracting strings from apk /Users/tanmoyray/Documents/AndroidApk/Veikulu/veiculu.apk null /var/folders/d6/zgrs6hbx0f3c5qy2hq6z0ln40000gn/T/com.senrysa.veiculu
[debug] [ADB] Extracting strings for language: default
[debug] [ADB] Device API level: 17
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","getprop","persist.sys.language"]
[debug] [ADB] Current device property 'persist.sys.language': 
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","getprop","ro.product.locale.language"]
[debug] [ADB] Current device property 'ro.product.locale.language': en
[debug] [ADB] No strings.xml for language 'en', getting default strings.xml
[debug] [ADB] Reading strings from converted strings.json
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","push","/var/folders/d6/zgrs6hbx0f3c5qy2hq6z0ln40000gn/T/com.senrysa.veiculu/strings.json","/data/local/tmp"]
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","forward","tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","push","/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar","/data/local/tmp/"]
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","ps","uiautomator"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: -P, 5037, -s, 192.168.56.100:5555, shell, uiautomator, runtest, AppiumBootstrap.jar, -c, io.appium.android.bootstrap.Bootstrap, -e, pkg, com.senrysa.veiculu, -e, disableAndroidWatchers, false, -e, acceptSslCerts, false
[debug] [UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] json loading complete.
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[AndroidBootstrap] Android bootstrap socket is now connected
[debug] [ADB] Device API level: 17
[debug] [ADB] Getting connected devices...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","am","start","-n","com.senrysa.veiculu/com.senrysa.veiculu.SplashScreen","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Waiting for pkg: 'com.senrysa.veiculu' and activity: 'com.senrysa.veiculu.SplashScreen' to be focused
[debug] [ADB] Possible activities, to be checked: com.senrysa.veiculu.SplashScreen, .SplashScreen, .com.senrysa.veiculu.SplashScreen
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","dumpsys","window","windows"]
[debug] [ADB] Found package: 'com.senrysa.veiculu' and activity: '.SplashScreen'
[Appium] New AndroidDriver session created successfully, session f3fb9f1b-a4dd-421c-a802-017047b2d727 added to master session list
[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webSto...
[HTTP] <-- POST /wd/hub/session 200 7731 ms - 921 
[HTTP] --> GET /wd/hub/session/f3fb9f1b-a4dd-421c-a802-017047b2d727/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["f3fb9f1b-a4dd-421c-a802-0...
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source
[debug] [AndroidBootstrap] [UIAUTO STDOUT] [APPIUM-UIAUTO] [debug] Returning result: {"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><hierarchy><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"0\"><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"1\"><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"2\"><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"3\"><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"4\"><android.view.View index=\"0\" text=\"\" class=\"android.view.View\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"true\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"0\"><android.view.View index=\"2\" text=\"\" class=\"android.view.View\" package=\"com.andyroid.launcher\" content-desc=\"Home screen 3\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"true\" password=\"false\" selected=\"false\" instance=\"1\"><android.view.View index=\"0\" text=\"\" class=\"android.view.View\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"2\"\/><\/android.view.View><\/android.view.View><android.widget.FrameLayout index=\"1\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"5\"><android.widget.RelativeLayout index=\"1\" text=\"\" class=\"android.widget.RelativeLayout\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"0\"><android.widget.LinearLayout index=\"0\" text=\"\" class=\"android.widget.LinearLayout\" package=\"com.andyroid.launcher\" content-desc=\"Search\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"0\"><android.widget.ImageView index=\"0\" text=\"\" class=\"android.widget.ImageView\" package=\"com.andyroid.launcher\" c
[debug] [AndroidBootstrap] [UIAUTO STDOUT] ontent-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"0\"\/><\/android.widget.LinearLayout><\/android.widget.RelativeLayout><\/android.widget.FrameLayout><android.widget.ImageView index=\"2\" text=\"\" class=\"android.widget.ImageView\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"1\"\/><android.view.View index=\"3\" text=\"\" class=\"android.view.View\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"3\"><android.view.View index=\"0\" text=\"\" class=\"android.view.View\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"4\"><android.view.View index=\"0\" text=\"\" class=\"android.view.View\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" instance=\"5\"><android.widget.TextView NAF=\"true\" index=\"0\" text=\"\" class=\"android.widget.TextView\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" scrollable=\"false\" long-clickable=\"true\" password=\"false\" selected=\"false\" instance=\"0\"\/><android.widget.TextView NAF=\"true\" index=\"1\" text=\"\" class=\"android.widget.TextView\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" scrollable=\"false\" long-clickable=\"true\" password=\"false\" selected=\"false\" instance=\"1\"\/><android.widget.TextView NAF=\"true\" index=\"2\" text=\"\" class=\"android.widget.TextView\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" scrollable=\"false\" long-clickable=\"true\" password=\"false\" selected=\"false\" instance=\"2\"\/><android.widget.TextView NAF=\"true\" index=\"3\" text=\"\" class=\"android.widget.TextView\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" scrollable=\"false\" long-clickable=\"true\" password=\"false\" selected=\"false\" instance=\"3\"\/><android.widget.TextView NAF=\"true\" index=\"4\" text=\"\" class=\"android.widget.TextView\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" scrollable=\"false\" long-clickable=\"true\" password=\"false\" selected=\"false\" instance=\"4\"\/><android.widget.TextView NAF=\"true\" index=\"5\" text=\"\" class=\"android.widget.TextView\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" scrollable=\"false\" long-clickable=\"true\" password=\"false\" selected=\"false\" instance=\"5\"\/><android.widget.TextView NAF=\"true\" index=\"6\" text=\"\" class=\"android.widget.TextView\" package=\"com.andyroid.launcher\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" scrollable=\"false\" lon
[debug] [AndroidBootstrap] [UIAUTO STDOUT] g-clickable=\"true\" password=\"false\" selected=\"false\" instance=\"6\"\/><\/android.view.View><\/android.view.View><\/android.view.View><\/android.widget.FrameLayout><\/android.widget.FrameLayout><\/android.widget.FrameLayout><\/android.widget.FrameLayout><\/android.widget.FrameLayout><\/hierarchy>","status":0}[/APPIUM-UIAUTO]
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] Stream still not complete, waiting
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [AndroidBootstrap] Stream still not complete, waiting
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getPageSource() result: "<?xml version=\"1.0\" enco...
[HTTP] <-- GET /wd/hub/session/f3fb9f1b-a4dd-421c-a802-017047b2d727/source 200 201 ms - 8492 
[HTTP] --> GET /wd/hub/session/f3fb9f1b-a4dd-421c-a802-017047b2d727/orientation {}
[MJSONWP] Calling AppiumDriver.getOrientation() with args: ["f3fb9f1b-a4dd-421c-a802-0...
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"orientation","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"orientation","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: orientation
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Current rotation: ROTATION_270
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"value":"LANDSCAPE","status":0}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getOrientation() result: "LANDSCAPE"
[HTTP] <-- GET /wd/hub/session/f3fb9f1b-a4dd-421c-a802-017047b2d727/orientation 200 13 ms - 83 
[HTTP] --> GET /wd/hub/session/f3fb9f1b-a4dd-421c-a802-017047b2d727/screenshot {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["f3fb9f1b-a4dd-421c-a802-0...
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","/system/bin/rm","/data/local/tmp/screenshot.png;","/system/bin/screencap","-p","/data/local/tmp/screenshot.png"]
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","pull","/data/local/tmp/screenshot.png","/var/folders/d6/zgrs6hbx0f3c5qy2hq6z0ln40000gn/T/appium116108-3530-14fsa8z.d79qpsnhfr.png"]
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABQ...
[HTTP] <-- GET /wd/hub/session/f3fb9f1b-a4dd-421c-a802-017047b2d727/screenshot 200 1165 ms - 476930 
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[HTTP] --> GET /wd/hub/session/f3fb9f1b-a4dd-421c-a802-017047b2d727/contexts {}
[MJSONWP] Calling AppiumDriver.getContexts() with args: ["f3fb9f1b-a4dd-421c-a802-0...
[debug] [AndroidDriver] Getting a list of available webviews
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/tanmoyray/library/android/sdk/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.100:5555","shell","cat","/proc/net/unix"]
[debug] [AndroidDriver] Found webviews: []
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP"]
[MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/f3fb9f1b-a4dd-421c-a802-017047b2d727/contexts 200 99 ms - 86 
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 406 ms - 121

**Comment by mykola-mokhnach** [comment]
please do not open duplicated issues. Also, the issue description is impossible to read

@triager please close

**Comment by Tanmoyray** [comment]
@mykola-mokhnach  It is not duplicated issue.. please see log cheerfully

**Comment by mykola-mokhnach** [comment]
Sorry. it's not gonna work this way. Describe your issue properly, according to the default template, so then one can figure out what is happening there.

**Comment by Tanmoyray** [comment]
@mykola-mokhnach Ok... I will try to do it.

**Comment by Tanmoyray** [comment]
@mykola-mokhnach is it ok ?

**Comment by Tanmoyray** [comment]
@triager Open it please... Appium client has crashed .

**Comment by imurchie** [comment]
What do you mean by "Appium client has crashed". The logs do not indicate anything untoward.  Does the server crash? Does the application go away?

**Comment by Tanmoyray** [comment]
Yes .... Appium application go away. 
`package MainPage;

import java.io.Console;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import Login.ValidLogin;
import Search.Search;
import io.appium.java_client.android.AndroidDriver;

public class main {

	public AndroidDriver<WebElement> driver;
	
@BeforeTest
	public void Setup() throws MalformedURLException{
	DesiredCapabilities capability = new DesiredCapabilities();
	capability.setCapability("AppPackageName", "com.senrysa.veiculu");
	capability.setCapability("AppActivityName", "com.senrysa.veiculu.SplashScreen");
	capability.setCapability("DeviceName", "Andy4.2.2");
	capability.setCapability("AppPath", "/Users/tanmoyray/Documents/AndroidApk/Veikulu/veiculu.apk");
		
	driver=new AndroidDriver<WebElement>(new URL("http://127.0.0.1:4723/wd/hub"), capability);
	driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);	
	
	}

@Test(priority=1)
public void SignIn() throws InterruptedException{
	
	ValidLogin signin =new ValidLogin(driver); 
	
	signin.txtUserName.sendKeys("9836067653");
	//Thread.sleep(2500);
	Assert.assertEquals("9836067653", "9836067653");
	
	signin.txtPassword.sendKeys("1234");
	//Thread.sleep(2500);
	Assert.assertEquals("1234", "1234");
	
	signin.btnLogin.click();
	//Thread.sleep(25000);
/*	WebDriverWait wait = new WebDriverWait(driver, 15);
	wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.support.v4.widget.DrawerLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]"
))); */
	Assert.assertEquals(true, true);
	
}
 
@Test(priority=2)
public void FindPujo() throws InterruptedException{
	
	Search findpujo =new Search(driver); 
	Thread.sleep(500);
	

	
	findpujo.ClkSearchicon.click();
	Thread.sleep(1500);
	Assert.assertEquals(true, true);
	
	/*
	findpujo.TxtSearchbox.sendKeys("park street");
	Thread.sleep(500);
	
	
	findpujo.SelectText.click();
	Thread.sleep(25000);
	
	findpujo.Click5.clear();
	Thread.sleep(500);
	Assert.assertEquals(true, true);
	
	//Assert.assertEquals("Park Street area, Kolkata, West Bengal, India", findpujo.SelectText.getText());
	*/
}

@AfterTest
public void Exit() {
	driver.quit();
}
	
}
`
`package Search;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.pagefactory.AndroidFindBy;
import io.appium.java_client.pagefactory.AppiumFieldDecorator;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.PageFactory;
public class Search {
	public Search(AndroidDriver<WebElement> driver){
		PageFactory.initElements(new AppiumFieldDecorator(driver), this);

}


	@AndroidFindBy(xpath="//android.widget.ImageView[@resource-id='com.senrysa.veiculu:id/toolbar_search_place']")
	public WebElement ClkSearchicon;
	
	
	
	@AndroidFindBy(id="autoCompleteTextView")
	public WebElement TxtSearchbox;
	
	@AndroidFindBy(xpath="//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.ListView[1]/android.widget.TextView[1]"
)
	public WebElement SelectText;
	
	@AndroidFindBy(id="rd_marker_five")
	public WebElement Click5;
	


}`

**Comment by SrinivasanTarget** [comment]
Hey @Tanmoyray Don't use Appium GUI for your execution. Try to run the appium server from command prompt latest is 1.6 through ``` npm install -g appium```.Start the server from terminal manually or through programatically and then run your program.

**Comment by Tanmoyray** [comment]
@SrinivasanTarget This is the other way, I have used it but When I click on Inspector ,application run and then 'Appium application go away'.

**Comment by SrinivasanTarget** [comment]
@Tanmoyray As Appium GUI is not maintained for sometime now, i would not recommend you to do that. You can use ```uiautomatorviewer``` for  Android and Facebook's ```WDA Inspector``` for iOS for sometime.

**Comment by Tanmoyray** [comment]
@SrinivasanTarget Ok... @triager So please change the issue status as 'Open'.

**Comment by SrinivasanTarget** [comment]
We cannot sorry. please open a issue here: https://github.com/appium/appium-dot-app/issues

**Comment by Tanmoyray** [comment]
@SrinivasanTarget @mykola-mokhnach @imurchie @sah @triager  I am not getting you, What does it mean "We can't sorry". Whatever, If you say that I need to log this issue within your sub repo. I am asking why? here, I am not telling, app has crashed, I am telling 'applium has crashed' . I believe , whatever the app is  but applium should not crashed or closed automatically . 


I other way, Why I log this issue twice, You can easily assign this issue to the right person where as "appium-dot-app" is a sub repo off "appium".

Please let me know, If I'm wrong .

**Comment by SrinivasanTarget** [comment]
```Appium GUI ``` is not actively maintained and we do have an epic #7167 to provide solution for our users.

Appium GUI is crashed is what you are keep on telling here which is irrelevant on server repo and this should be logged as specified above. Please log with proper issue description atleast there.

If you face any issues related to server, you can log here with all the details required along with logs following the issue template. We are happy to look further.
