### ISSUE TITLE
Appium Server is not displaying logs in GUI Console

### ISSUE THREAD

**Issue by muralidhar1620** [appium/appium#7199]
Hi,
when run appium server v1.5.3, it won't display logs in GUI console and Response of localhost:4723/wd/hub/status is 
 {"status":0,"value":{"build":{"version":"1.5.3","revision":null}},"sessionId":null.And some times {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. Original error: ENOENT: no such file or directory, stat '/usr/local/lib/node_modules/appium/build'"},"sessionId":null}.This is for appium GUI for Android in **Mac**.

Please find attachment for configuration settings in Mac

I had reverted back to v1.4.13 and same issue exists.Any thoughts to make it work ?

Thanks,
Murali

![screen shot 2016-11-08 at 12 43 21 pm](https://cloud.githubusercontent.com/assets/14792866/20097012/642fc398-a5d2-11e6-80a5-04c769d3b2ec.png)
![screen shot 2016-11-08 at 12 43 24 pm](https://cloud.githubusercontent.com/assets/14792866/20097016/649975c2-a5d2-11e6-9a30-8944e4b2b9ff.png)
![screen shot 2016-11-08 at 12 43 28 pm](https://cloud.githubusercontent.com/assets/14792866/20097015/6495c490-a5d2-11e6-9e89-ce5489d0df6a.png)
![screen shot 2016-11-08 at 12 43 32 pm](https://cloud.githubusercontent.com/assets/14792866/20097014/64924004-a5d2-11e6-8db2-cd196344cf10.png)

**Comment by jlipps** [comment]
Sorry @muralidhar1620 we don't provide support for Appium GUI issues here. I'm not sure why the logs wouldn't be showing up, unless you've modified the log level.

**Comment by Tanmoyray** [comment]
@muralidhar1620  Try check with  'Full Reset' and 'Stop with Reset' .

**Comment by muralidhar1620** [comment]
Thanks for Reply @Tanmoyray .Tried with 'Full Reset' and 'Stop with Reset' and its not working(Not displaying logs in the GUI console).

Is there any possible ways to fix this.Should i perform uninstall appium and Reinstall again ? If Yes can you please let me know the uninstallation steps (Online Doc) ?.Thanks!

**Comment by Tanmoyray** [comment]
@muralidhar1620 
I dont have any ready document  on it.
Try:
1. No need to set sdk path , I have worked without it.
2. Recheck your env variable

**Comment by sgurusharan** [comment]
Hi @muralidhar1620,

I had similar problem and resolved it - it looks like there may be more than one appium server running on the machine that are trying to access the log.

1. Stop the Appium Server and Quit the Application.
2. Execute the following in terminal: `ps x | grep [A]ppium | grep [n]ode` - this should display the list of commands that invoke appium server. You should have NO node process corresponding to appium.
3. If there are any, kill all the processes displayed, starting from the latest process (highest process id) using `kill -KILL <process_id>` - the process id is the number that appears when executing the ps x command.

Once all appium processes are killed - relaunch the Appium Server - Voila!!

Hope this helps.

Regards,
Gurusharan S.
