### ISSUE TITLE
Impossible to get src attribute from imageview

### ISSUE THREAD

**Issue by jeangb** [appium/appium#7201]
## The problem

My problem is that I would like to check if an imageview was touched.
This is not a button so I can't use checked, or enabled.
The image inside the imageview changed when we press it (grey to red).
So I would like to check that the image resource was changed.

## Environment

* Appium version: 1.5.3
* Desktop OS/version used to run Appium: Win 7 64bits
* Mobile platform/version under test: 4.4.2
* Real device or emulator/simulator: Real device

## Details
The object in the android xml:
```
<ImageView
                android:id="@+id/mute_audio"
                android:layout_width="0dp"
                android:layout_weight="14"
                android:layout_height="24dp"
                android:src="@drawable/ic_material_mic_off_grey"/>
```

I tried using getAttribute("**src**") but didn't work.
I tried an other strategy which was getting the object by xpath : `android.widget.ImageView[contains(@src,'ic_material_mic_off_grey')]`
but it didn't work neither.
Do you have a solution for this ? It's important for my tests to check if this kind of "buttons" are pressed.

**Comment by mykola-mokhnach** [comment]
We use screenshot comparison for such cases

**Comment by jeangb** [comment]
Is it really reliable ? Because I guess this won't work with different screen sizes, dimensions should change.

**Comment by mykola-mokhnach** [comment]
Probably yes if you compare it with examples. But it should be OK if you just compare two screenshots taken in scope of the same testing session.

**Comment by jeangb** [comment]
Ok then. I didn't think about that ...
What tool/api would you advise ?

**Comment by mykola-mokhnach** [comment]
We use OpenCV library for this purpose

**Comment by jeangb** [comment]
Thank you I'm going to check this out !
It's too bad we can't get the src attribute though

**Comment by imurchie** [comment]
Unfortunately we are constrained by what we can get from the `UIObject` object that Android provides. :(

**Comment by jeangb** [comment]
Thank your for your answers. Maybe what Android provides will be more consistent in the future !

**Comment by imurchie** [comment]
Hopefully!
