### ISSUE TITLE
Give more helpful error when using an invalid app download URI scheme

### ISSUE THREAD

**Issue by JMVM** [appium/appium#7203]
## The problem

If trying to automate an Android app into real device from **local machine using file URI scheme** (for example, file:///C:/Users/josem/Downloads/AndroBluetooth.apk), getting an exception about 'Bad app'. 

Having a look, it's being looked for into **Appium server install dir** (C:\Program Files (x86)\Appium\node_modules\appium\file:\C:\Users\josem\Downloads\AndroBluetooth.apk)

However, using directly absolute path (C:\Users\josem\Downloads\AndroBluetooth.apk), it's properly found and loaded into real device.

## Environment

* Appium version (or git revision) that exhibits the issue: 4.1.2
* Mobile platform/version under test: Android 5.1.1
* Real device or emulator/simulator: Samsung Galaxy Note 4
* Appium CLI or Appium.app|exe: 1.4.16.1

## Details

Lack of support for **file URI scheme**

## Link to Appium logs

https://gist.github.com/JMVM/11ab17c59faa283dac422570f166a18a

**Comment by imurchie** [comment]
That is something that could be done. But what is wrong with just specifying the file, without the `file` scheme?

**Comment by JMVM** [comment]
I was more thinking about URI scheme to have for example the same format for file:// and http(s)://, and in function of that processing in one way or not. And obviously to avoid uncontrolled situation, throwing an exception in that case.

**Comment by jlipps** [comment]
We can at least make the error message more clear. Probably it should be something like:

> App download scheme `file://` not supported. Use `http(s)` instead.

**Comment by mykola-mokhnach** [comment]
Fixed
