### ISSUE TITLE
location based tap implementation not working in Appium 1.6 & 1.6.1

### ISSUE THREAD

**Issue by dilsreccse** [appium/appium#7204]
We need to tap based on location. Before Appium 1.6 version, we used the following code,

### ((JavascriptExecutor) ElementsAction.driver).executeScript(
				"mobile: tap", new HashMap<String, Double>() {
					{
						put("tapCount", (double) 1);
						put("touchCount", (double) 1);
						put("duration", 1.0);                            
						put("x", (double) x_co);
						put("y", (double) y_co);
					}
				});

The above code is not working in Appium 1.6. So we tried the below actions and still its not working:
### TouchAction action = new TouchAction((MobileDriver) ElementsAction.driver);
action.longPress(x, y).perform();
action.tap(x, y).perform();

## Environment

* Appium version that exhibits the issue: 1.6.1
* Mobile platform/version under test: iOS 10 iPad Air
* Real device or emulator/simulator: Real device

Kindly provide a solution to tap based on location as it is impacting our scripts on a large scale.

**Comment by imurchie** [comment]
`mobile: tap` will not work, no. All `mobile:` methods are gone except `scroll`.

Can you provide the logs for `longPress` and `tap`, so we can see what is invoked on on the server side, and suggest alternatives (different clients implement those in different ways)?

**Comment by dilsreccse** [comment]
@imurchie , gist for longpress based on location [here]((https://gist.github.com/dilsreccse/cb58c7b372b7327fe51cdbc9ebedb43a))
& gist for tap based on location [here](https://gist.github.com/dilsreccse/4f6975c2c69ffc0d3e2cc9dbce4ca880)

**Comment by dilsreccse** [comment]
@imurchie any workaround can be done to tab based on location based tap implementation.

**Comment by mykola-mokhnach** [comment]
You may call update WDA from master (these functions are already available there) and call its API directly from your framework.

There is also one method based on Apple scripting, but it's only suitable for Simulator tests.

**Comment by imurchie** [comment]
It is available in `appium-xcuitest-driver@2.0.35`. You can update by re-installing 1.6.1-beta

```
npm uninstall -g appium
npm install -g appium@beta
```

**Comment by dodigital** [comment]
@imurchie Location based tap does work, however what can you tell us about long press ? Has that been implemented on 1.6.1 ? I'm having 'Support for gestures other than Tap is not yet implemented.' Please help.

**Comment by imurchie** [comment]
Did you try it on the 1.6.1 beta? It should work.

**Comment by dilsreccse** [comment]
Hi @imurchie , have tried it in 1.6.1 beta , its not working

**Comment by imurchie** [comment]
Which did not work? And what does "not working" mean? Logs would be good.
