### ISSUE TITLE
Appium 1.4.16 (Windows) + android emulator : unable to find elements

### ISSUE THREAD

**Issue by Harmo80** [appium/appium#7205]
## The problem

I tried to findElement on a android hybrid application (ionic), but it doesn't work. I want to launch an android app and doing action with Appium. The app start very well, but I'm unable to find any element. 
I tried some elements, like : 

```
WebElement elem = driver.findElement(By.xpath("//android.view.View/android.view.View/android.widget.CheckBox[1]")); 
WebElement elem = driver.findElement(By.xpath("//android.view.View[0]"));
WebElement elem = driver.findElement(By.xpath("//android.view.View/*[@resource-id='usernameId']"));
or
WebElement elem = driver.findElement(By.xpath("//*[@resource-id='usernameId']"));
```

Nothing works. :( 
I think my xpath is correct... 
Here's a screenshot of one of the element i wanna to find : (usernameId) 
https://i.gyazo.com/ca3508201eed91fbb83f57871af0134c.png
As you see, the element's resource-id is "usernameId" without package. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16 but same with 1.6 on Ubuntu. 
* Desktop OS/version used to run Appium: Windows / Linux
* Real device or emulator/simulator: Emulator / AVD
* Appium CLI or Appium.app|exe: exe in windows, CLI on Ubuntu. 

## Details

Java Error : 
```
Exception in thread "main" org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 21.97 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Maxime-PC', ip: '192.168.10.72', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_25'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{app=C:\weaselselenium\app.apk, appPackage=com.ionicframework.feessolutions151197, networkConnectionEnabled=true, recreateChromeDriverSessions=true, warnings={}, databaseEnabled=false, deviceName=emulator-5554, version=4.1.2, platform=ANDROID, appActivity=com.ionicframework.feessolutions151197.MainActivity, desired={app=C:\weaselselenium\app.apk, appPackage=com.ionicframework.feessolutions151197, appActivity=com.ionicframework.feessolutions151197.MainActivity, recreateChromeDriverSessions=true, browserName=Android, takesScreenshot=true, platformName=Android, deviceName=DeviceTest, version=4.1.2, platform=ANDROID}, platformVersion=5.0.1, webStorageEnabled=false, locationContextEnabled=false, browserName=Android, takesScreenshot=true, javascriptEnabled=true, platformName=Android}]
Session ID: 252f7e0a-4d1f-4dc1-a13e-96a1c3c0d2cc
*** Element info: {Using=xpath, value=//android.view.View[0]}
```

## Appium logs

```
> info: --> POST /wd/hub/session/252f7e0a-4d1f-4dc1-a13e-96a1c3c0d2cc/element {"using":"xpath","value":"//android.view.View[0]"}
> info: [debug] Waiting up to 0ms for condition
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"xpath","selector":"//android.view.View[0]","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.view.View[0]","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding //android.view.View[0] using XPATH with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":7,"value":"Could not find an element using supplied strategy. "}
> info: [debug] Condition unmet after 21957ms. Timing out.
> info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":"Could not find an element using supplied strategy. "},"sessionId":"252f7e0a-4d1f-4dc1-a13e-96a1c3c0d2cc"}
```

Any ideas ?

**Comment by imurchie** [comment]
Two things:

1. Can you check the source at that point to see that in fact things are there?

2. It might be a timing issue. You can set an implicit wait so that the find will be repeated for a bit, in case they are not there when you are searching.

**Comment by mykola-mokhnach** [comment]
Elements indexing in XPath queries starts from 1.
Use _getPageSource()_ call to see the actual xml tree visible to Appium and get attribute names there.

**Comment by Harmo80** [comment]
@imurchie I've already put 15s or 30s of waiting time, no difference. 

@mykola-mokhnach Oh, yes, index starts at one, so it works now for View elements. But I want to find the goddamn EditText element. 
Thanks for the tip of getPageSource() ! Very useful. 
So, I see that my EditText have no "resource-id" visible in that XML... But when I use uiautomatorviewer.bat (android sdk), I could see the resource-id. :( ( https://i.gyazo.com/ca3508201eed91fbb83f57871af0134c.png )

You can search on the attached file for "EditText", there is only two input fields, and both have no resource-id, but the should. :/

[pageSource.txt](https://github.com/appium/appium/files/581245/pageSource.txt)

**Comment by mykola-mokhnach** [comment]
How do you set id field in application resources? Something like this http://stackoverflow.com/questions/8460680/how-can-i-assign-an-id-to-a-view-programmatically ?

**Comment by mykola-mokhnach** [comment]
There is one id visible in the page source ( resource-id="android:id/content" ) just make sure all tyhe other ids are set the same way.

**Comment by Harmo80** [comment]
I do the test on a real device, my phone, and the resource-id is visible on the page source... And the findElement works well. Same app, same apk, same program. :( 
My phone is on Android 5.1.1 (Moto G3), and my emulators was Nexus S, Nexus 6 on API 21... I can't believe this is due to a difference between Android 5.0 and 5.1.1. 

Should be a known behavior of the emulator ?

**Comment by Harmo80** [comment]
Here's similar issue : 
http://stackoverflow.com/questions/21399503/real-device-vs-emulator-uiautomator-does-not-show-resource-id-for-the-app
http://stackoverflow.com/questions/19801746/uiautomatorviewer-no-longer-shows-resource-id

They talked about level API < 18, but I tried with Android 5 and another Emulator on Android 7. 

I'm such a newbie on Android, perhaps I fucked up somewhere on the installation of the android SDK : I have installed the SDK on two different computers : 
Android SDK tools v 24.0.2 + platform tools v21 + SDK platform API 23 + SDK platform API 21 (Android 5 and 6) 
Android SDK tools v 25.2.2 + platform tools v25 + SDK platform API 25 + SDK platform API 24 (Android 7)

**Comment by Harmo80** [comment]
Just test with appium 1.6.0, same problem.

**Comment by dpgraham** [comment]
Closing this. If this is still an issue, I can re-open it.
