### ISSUE TITLE
Getting Bad app error when using a URL to an ipa file for real iOS device testing

### ISSUE THREAD

**Issue by nicolasavenza** [appium/appium#7207]
## The problem

Using a url to an ipa file causes a bad app error when testing with real iOS devices on 1.6.1-beta.

## Environment

* Appium version: 1.6.1-beta
* Last Appium version that did not exhibit the issue: 1.6.0
* Desktop OS/version used to run Appium: macOS 10.12.1
* Node.js version (unless using Appium.app|exe): v6.9.1
* Mobile platform/version under test: iOS 10.1.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
```
info: [BaseDriver] Using downloadable app 'http://jenkinsurl/job/ios_app_build/lastSuccessfulBuild/artifact/app_adhoc.ipa'
info: [BaseDriver] Downloaded app to '/var/folders/s7/bzp6wwy522x66279g2lyvkth0000gq/T/2016109-62030-bqym2j.0m6d7snhfr/appium-app'
error: [XCUITest] Error: New app path /var/folders/s7/bzp6wwy522x66279g2lyvkth0000gq/T/2016109-62030-bqym2j.0m6d7snhfr/appium-app did not have extension .app
```

## Link to Appium logs

`Error: Bad app: http://jenkinsurl/job/ios_app_build/lastSuccessfulBuild/artifact/app_adhoc.ipa. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name.`

## Code To Reproduce Issue [ Good To Have ]

Using java client:

`capabilities.setCapability(MobileCapabilityType.APP, "http://jenkinsurl/job/ios_app_build/lastSuccessfulBuild/artifact/app_adhoc.ipa");`

**Comment by jlipps** [comment]
At the moment I think we only support downloading`.zip` files. Can you try zipping it and see if that works?

**Comment by nicolasavenza** [comment]
I've worked around it by downloading the file first and using a local path.

**Comment by rkavalap** [comment]
Closing this as we have a work around.
