### ISSUE TITLE
Cannot start Appim with custom bootstrap port and error log level

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#7209]
## The problem

appium -p 4726 -bp 5726 --log-level error - FAILES to start
appium -p 4726 -bp 5726 --log-level info - no problem

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1-beta
* Desktop OS/version used to run Appium: El Captain
* Node.js version (unless using Appium.app|exe): v5.6.0

**Comment by jlipps** [comment]
@amedvedjev starts fine for me with that command. What error are you experiencing specifically?

**Comment by amedvedjev** [comment]
no error. just waiting waiting waiting....

**Comment by jlipps** [comment]
Waiting is what a server is supposed to do...

You set the log level to `error`, which is why you are not seeing any startup messages (those are log-level `info`)

**Comment by amedvedjev** [comment]
wow.... indeed! sorry
