### ISSUE TITLE
Appium 1.6.0 UIAutomator2 save the cookie

### ISSUE THREAD

**Issue by tomliuxin** [appium/appium#7210]
## The problem

How to set the uiautomator2 save the cookie when initialize the driver

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.0
* Desktop OS/version used to run Appium: window 10
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: emulator
* uiautomator2: version 0.0.7
* Chrome driver: 2.21.0

## Details
There is one android app, if you have signed in, next time open this app, it will be signed in too.
but when I use the appium+uiautomator2 to run cases, after initialize the driver, the app is not signed in even last time has been signed in.

do we have any way to save the cookie/catch for app?

## Code To Reproduce Issue [ Good To Have ]
C# initialize the driver code:
  DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.SetCapability("device", "Android");
            capabilities.SetCapability(CapabilityType.Platform, "Windows");
            capabilities.SetCapability("deviceName", deviceName);
            capabilities.SetCapability("platformName", "Android");
            capabilities.SetCapability("platformVersion", "7.0");
            capabilities.SetCapability("automationName", "uiautomator2");
            //capabilities.SetCapability("automationName", "Appium");
            capabilities.SetCapability("unicodeKeyboard", "True");
            capabilities.SetCapability("resetKeyboard", "True");
            capabilities.SetCapability("appPackage", appPackage);
            capabilities.SetCapability("appActivity", appActivity);
            capabilities.SetCapability("newCommandTimeout", "30000");
            capabilities.SetCapability(CapabilityType.SupportsApplicationCache, "True");
            capabilities.SetCapability(CapabilityType.IsJavaScriptEnabled, "True");
            capabilities.SetCapability(CapabilityType.AcceptSslCertificates, "True");

            Uri uri = new Uri(uriString);
            TimeSpan timeSpan = TimeSpan.FromMinutes(20);
            myDriver = new AndroidDriver<AppiumWebElement>(uri, capabilities, timeSpan);

**Comment by sravanmedarapu** [comment]
Can you try by setting `noReset` capability to `true`.

If it still not working please share appium server logs in a separate [gist](http://gist.github.com/).

**Comment by tomliuxin** [comment]
@sravanmedarapu , Thanks so much, that worked.
