### ISSUE TITLE
Unable to build appium from source (Failed at the appium-windows-driver@0.2.0 install script 'node install-npm.js')

### ISSUE THREAD

**Issue by ivasylchenko** [appium/appium#7211]
## Environment
- Appium version: v1.6.0-beta3 (source code 7131abb9f58c2854e5d447af32d1e6b0e6f632b3):
- Last Appium version that did not exhibit the issue: v.1.5.2 (8102f84ea8701f7a15d37bc0d3d6cc27535d7327)
- Desktop OS/version used to run Appium: Linux x64 (Ubuntu 15.10)
- Node.js version: v4.4.7
- Java version: 1.8.0_66

## Details
Followed by [instructions](https://github.com/appium/appium/blob/master/docs/en/contributing-to-appium/appium-from-source.md).

Failed on first step after cloning - npm install.

## Link to Appium logs

[Detailed log](https://gist.github.com/ivasylchenko/14d1ee4da3e9a9b10a55a7fde0a04b44)

**Comment by imurchie** [comment]
Can you upgrade npm? Version 3 handles dependencies better, and this should be solved.

**Comment by ivasylchenko** [comment]
Current npm version is 2.15.8
Updated to 3.10.9

Issue resolved.

@imurchie Thanks
