### ISSUE TITLE
chrome web driver is opened and closed with the text "data;" in the url 

### ISSUE THREAD

**Issue by dekel11** [appium/appium#7212]
i am using python 2.7 with Appium (1.5.3) on MAC with Android Chrome web driver,
i am opened the emulator (device:Nexus 5X API 22) via android studio.
then i run the code.

Currently, chrome webdriver is opened and closed with the text "data;" in the url and i get an error-
```
/Users/automator/.virtualenvs/Automation2.7/bin/python "/Users/automator/Library/Application Support/IdeaIC2016.2/python/helpers/pycharm/utrunner.py" /Users/automator/Automation/ginseng/ginseng_android.py::AndroidWebViewTests true
Testing started at 3:56 PM ...
/Users/automator/Automation/ginseng/ginseng_android.py:5: RuntimeWarning: Parent module 'ginseng' not found while handling absolute import
  import unittest
/Users/automator/Automation/ginseng/ginseng_android.py:6: RuntimeWarning: Parent module 'ginseng' not found while handling absolute import
  from time import sleep
/Users/automator/Automation/ginseng/ginseng_android.py:17: RuntimeWarning: Parent module 'ginseng' not found while handling absolute import
  from selenium import webdriver

Error
Traceback (most recent call last):
  File "/Users/automator/Automation/ginseng/ginseng_android.py", line 41, in test_get_url
    self.driver.get('http://ginseng.life')
  File "/Users/automator/.virtualenvs/Automation2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 248, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/automator/.virtualenvs/Automation2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Users/automator/.virtualenvs/Automation2.7/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: no such session
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.6 x86_64)
```

also this is my code:
```python
# import os
# import glob
# from time import sleep
# import gspread
import unittest
from time import sleep
# from datetime import datetime, date
# from oauth2client.service_account import ServiceAccountCredentials
# from random import randint
# import logging
# from selenium.webdriver.support.ui import Select
# import requests
# import boto.ses
# from helper_functions import write_to_log_file
# from selenium.webdriver.common.action_chains import ActionChains
# from appium import webdriver
from selenium import webdriver


PLATFORM_VERSION = '5.1.1'

class AndroidWebViewTests(unittest.TestCase):

    def setUp(self):

        desired_caps = {
            'browserName': 'Chrome',
            'platformName': 'Android',
            'platformVersion': PLATFORM_VERSION,
            'deviceName': 'Nexus 5X API 22'
            'recreateChromeDriverSessions", true'
        }

        if (PLATFORM_VERSION != '5.1.1'):
            desired_caps['automationName'] = 'selendroid'

        self.driver = webdriver.Remote('http://localhost:4723/wd/hub',
                                       desired_caps)

    def test_get_url(self):
        self.driver.get('http://ginseng.life')
        sleep(20)

    def tearDown(self):
        self.driver.quit()


if __name__ == '__main__':
    suite = unittest.TestLoader().loadTestsFromTestCase(AndroidWebViewTests)
    unittest.TextTestRunner(verbosity=2).run(suite)
```

please help !!!!

**Comment by imurchie** [comment]
Can you provide the Appium server logs as a [gist](https://gist.github.com)?

**Comment by dekel11** [comment]
this is the link for the code,
https://gist.github.com/dekel11/21b43d30886e782334a297435dcbba42
Thanks

**Comment by imurchie** [comment]
We need the Appium server logs. They should begin something like

```
[Appium] Welcome to Appium v1.6.1-beta (REV 5817d3125a8cf50f4074190dda4dbfdd60f229bd)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

**Comment by dekel11** [comment]
Hi,
this is the logs i get from Appium:

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 14 ms - 83 

[HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"platformVersion":"5.1.1","deviceName":"Nexus 5X API 22","browserName":"Chrome","platformName":"Android"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformVersion":"5.1.1"...

[Appium] Creating new AndroidDriver session

[Appium] Capabilities:
[Appium]   platformVersion: '5.1.1'
[Appium]   deviceName: 'Nexus 5X API 22'
[Appium]   browserName: 'Chrome'

[Appium]   platformName: 'Android'
[Appium]   automationName: 'Appium'

[BaseDriver] Session created with session id: a6cddc24-ca6e-43d2-8ae4-21bef2d5852d

[debug] [AndroidDriver] Getting Java version

[AndroidDriver] Java version is: 1.8.0_111

[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main

[ADB] Checking whether adb is present

[ADB] Using adb from /Users/automator/Library/Android/sdk/platform-tools/adb
[AndroidDriver] Retrieving device list

[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[AndroidDriver] Looking for a device with Android 5.1.1
[debug] [ADB] Setting device id to emulator-5554
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]

[AndroidDriver] Using device: emulator-5554

[ADB] Checking whether adb is present

[ADB] Using adb from /Users/automator/Library/Android/sdk/platform-tools/adb

[debug] [ADB] Setting device id to emulator-5554
[AndroidDriver] App file was not listed, instead we're going to run com.android.chrome directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","com.android.chrome"]

[AndroidDriver] Starting Android session

[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","wait-for-device"]

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","echo","ping"]

[debug] [Logcat] Starting logcat capture

[debug] [AndroidDriver] Pushing settings apk to device...

[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","install","/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/io.appium.settings/bin/settings_apk-debug.apk"]

[debug] [AndroidDriver] Pushing unlock helper app to device...

[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","install","/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-unlock/bin/unlock_apk-debug.apk"]

[ADB] Getting device platform version

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected

[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window"]

[AndroidDriver] Screen already unlocked, doing nothing

[debug] [AndroidBootstrap] Watching for bootstrap disconnect

[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","forward","tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","push","/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar","/data/local/tmp/"]

[debug] [ADB] Attempting to kill all uiautomator processes

[debug] [ADB] Getting all processes with uiautomator

[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","ps","uiautomator"]

[ADB] No uiautomator process found to kill, continuing...

[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: -P, 5037, -s, emulator-5554, shell, uiautomator, runtest, AppiumBootstrap.jar, -c, io.appium.android.bootstrap.Bootstrap, -e, pkg, com.android.chrome, -e, disableAndroidWatchers, false, -e, acceptSslCerts, false

[debug] [UiAutomator] Moving to state 'online'

[AndroidBootstrap] Android bootstrap socket is now connected

[AndroidDriver] Starting a chrome-based browser session
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver
[Chromedriver] Killing any old chromedrivers, running: pkill -15 -f "/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver.*--port=9515"

[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.

[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected

[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver --url-base=wd/hub --port=9515 --adb-port=5037

[Chromedriver] [STDOUT] Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 9515
Only local connections are allowed.

[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body

[JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body

[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"stat...

[JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"ch...

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[JSONWP Proxy] Got response with status 200: {"sessionId":"21daa48098426...

[debug] [Chromedriver] Changed state to 'online'

[Appium] New AndroidDriver session created successfully, session a6cddc24-ca6e-43d2-8ae4-21bef2d5852d added to master session list
[MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webSto...
[HTTP] <-- POST /wd/hub/session 200 94764 ms - 568 

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] --> POST /wd/hub/session/a6cddc24-ca6e-43d2-8ae4-21bef2d5852d/url {"url":"http://ginseng.life","sessionId":"a6cddc24-ca6e-43d2-8ae4-21bef2d5852d"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[JSONWP Proxy] Proxying [POST /wd/hub/session/a6cddc24-ca6e-43d2-8ae4-21bef2d5852d/url] to [POST http://127.0.0.1:9515/wd/hub/session/21daa48098426dcc60bba10ed9dfb4ce/url] with body: {"url":"http://ginseng.life...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[JSONWP Proxy] Got response with status 200: {"sessionId":"21daa48098426...
[JSONWP Proxy] Replacing sessionId 21daa48098426dcc60bba10ed9dfb4ce with a6cddc24-ca6e-43d2-8ae4-21bef2d5852d
[HTTP] <-- POST /wd/hub/session/a6cddc24-ca6e-43d2-8ae4-21bef2d5852d/url 200 46 ms - 220 

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] --> DELETE /wd/hub/session/a6cddc24-ca6e-43d2-8ae4-21bef2d5852d {}
[MJSONWP] Calling AppiumDriver.deleteSession() with args: ["a6cddc24-ca6e-43d2-8ae4-2...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Stopping chromedriver for context CHROMIUM
[debug] [Chromedriver] Changed state to 'stopping'
[JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:9515/wd/hub/session/21daa48098426dcc60bba10ed9dfb4ce] with no body
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"21daa4809...
[debug] [Chromedriver] Changed state to 'stopped'
[debug] [ADB] Getting connected devices...
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.unlock"]

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[debug] [ADB] Pressing the HOME button

[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","input","keyevent",3]

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [Logcat] Stopping logcat capture

[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}

[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}

[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN

[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}

[debug] [AndroidBootstrap] Received command result from bootstrap

[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/automator/Library/Android/sdk/platform-tools/adb with args: ["-P",5037,"-s","emulator-5554","shell","ps","uiautomator"]

[HTTP] <-- GET /wd/hub/status - - ms - - 

[ADB] No uiautomator process found to kill, continuing...

[debug] [UiAutomator] Moving to state 'stopped'
[Appium] Removing session a6cddc24-ca6e-43d2-8ae4-21bef2d5852d from our master session list

[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/a6cddc24-ca6e-43d2-8ae4-21bef2d5852d 200 18067 ms - 76 

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 12 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 57 ms - 83

**Comment by mykola-mokhnach** [comment]
Try to provide updated chromedriver binary to the driver and see how it performs.
