### ISSUE TITLE
fullReset couldn't remove app from real device with iOS 8.4

### ISSUE THREAD

**Issue by pengboZheng** [appium/appium#7213]
## Environment

* Appium version (or git revision) that exhibits the issue: v1.5.2 v1.5.3 and v1.6.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: osx 10.11.6
* Node.js version (unless using Appium.app|exe): v7.1.0
* Mobile platform/version under test: iOS 8.4.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Both

## Details
**Update details:**
iTune version: 12.5.1.21: 
This version of iTune will constantly popup "Trust This Computer" alert when run appium test, and will not even install the app, the error message will be (https://gist.github.com/pengboZheng/54d48cf3f03b31e22f3ef0887e12fd55)

> [Instruments] Error launching instruments: Instruments crashed on startup

 Then I followed instruction [https://discuss.appium.io/t/unable-to-install-ios-app-after-updating-to-xcode-8-0-and-itunes-12-5-1/12146](url) use `brew uninstall libimobiledevice && brew install --HEAD libimobiledevice` then install app is normal if there is no `fullReset` flag.

1. Start any appium server that list on above
2. Try to run the test with `capabilities.setCapability(MobileCapabilityType.FULL_RESET, true);` OR add `--full-reset` in appium CLI
3. If the app installation target is Real device, the output from Appium v1.5.3 and v1.6.0 will be
> Encountered internal error running command: Error: Command failed: ideviceinstaller -u 4616022ec26add0fc653c1cb544289feed2028ce -U com.printeron.printeron

The Appium v1.5.2 error output will be
> Encountered internal error running command: Error: Command failed: ideviceinstaller -u 4616022ec26add0fc653c1cb544289feed2028ce -u com.printeron.printeron
WARNING: Using "-u" for "--uninstall" is deprecated. Please use "-U" instead.

4. After remove the flag or capability `fullReset` with both Real device and simulator, the tests will work.
5. set `fullReset` flag or capability to True and run with simulator will work.
6. For iOS 9.3 on Real device works fine with `fullReset` set to True.

## Link to Appium logs

Appium v1.5.2: https://gist.github.com/pengboZheng/94f0f88acd9e654b86791e1c7f37bb66
Appium v1.6.0: https://gist.github.com/pengboZheng/dfe7acd5143626bc0a247965641bae99

**Comment by imurchie** [comment]
Can you make sure you have the latest libimobiledevice?

```
brew upgrade libimobiledevice --HEAD
```

**Comment by pengboZheng** [comment]
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
consul-backinator                                                                   typesafe-activator

Error: libimobiledevice HEAD-23069d1 already installed

**Comment by pengboZheng** [comment]
@imurchie please check [https://github.com/appium/appium/issues/7215](url)
