### ISSUE TITLE
IOS slider cannot be moved

### ISSUE THREAD

**Issue by vstefanescu83** [appium/appium#7214]
## The problem
Cannot move slider in IOS Simulator

## Environment

* Appium version 1.6
* IOS Simulator 10.1 Xcode8

## Details
I have tried using element.setValue("0.8") (and also sendKeys and many other ways) to modify IOS slider to a different position however it doesnt work, following error is displayed:
Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}
There should be no keyboard as its a slider not an input field.

In Xcode i have succesfully automated the slider movement using "adjustToNormalizedSliderPosition" method however i cant seem to find any similar method implemented in appium. Maybe the correspondent of this XCUITEST method should be implemented in appium?

**Comment by dpgraham** [comment]
This is due to an issue with WebDriverAgent (which is used by appium-xcuitest-driver). This issue has since been resolved and will make it's way into a future Appium release.

https://github.com/facebook/WebDriverAgent/issues/339
