### ISSUE TITLE
Unable to launch app on real devices with iOS 10 using appium 1.6.

### ISSUE THREAD

**Issue by vutukuriswathi** [appium/appium#7218]
I am unable to launch the iOS application using appium 1.6 on real devices.

My webdriveragent project is started on device after that it is unable to run any tests and I am not getting any error message.

can some one help me on this.

Below are my configuration details
appium:1.6.0
ios Device : iphone6s with 10.1 iOS

My capabilities:
DesiredCapabilities capabilities = new DesiredCapabilities();
				capabilities.setCapability("automationName", "XCUITest");
				
				capabilities.setCapability("udid", iosConfig.getProperty("udid"));
				capabilities.setCapability("bundleId", iosConfig.getProperty("appBundleId"));
				capabilities.setCapability("platformName", platformConfig.getProperty("platform"));
				capabilities.setCapability("platformVersion", iosConfig.getProperty("iosDeviceVersion"));
				capabilities.setCapability("deviceName", iosConfig.getProperty("iosDeviceName"));
				File appdir = new File(System.getProperty("user.dir") + "/src/test/resources/com/iview/mobileApps/"
						+ iosConfig.getProperty("iosAppName") + ".app");
				capabilities.setCapability("app", appdir.getAbsolutePath());
				capabilities.setCapability("autoAcceptAlerts", true);
				driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

My appium logs:
appium &
[1] 8920

WS103309:~ srivastava4f0z$ (node:8920) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

[Appium] Welcome to Appium v1.6.0 (REV 1d66cdd3ade841c6b7cd8a71d4b71d5426d00a58)

[Appium] Appium REST http interface listener started on 0.0.0.0:4723

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/srivastava4f0z/Documents/swathi/ABCMeTabletsAutomation/src/test/resources/com/abc/mobileApps/abcme.ipa","platformVersion":"10.1","automationName":"XCUITest","bundleId":"au.net.abc.abcme","udid":"15eb7de5c880d3c6062eb2a43bfb53af06472d28","platformName":"iOS","deviceName":"ABC's iPhone","autoAcceptAlerts":true}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/srivastava4...

[Appium] Creating new XCUITestDriver session

[Appium] Capabilities:

[Appium] app: '/Users/srivastava4f0z/Documents/swathi/ABCMeTabletsAutomation/src/test/resources/com/abc/mobileApps/abcme.ipa'

[Appium] platformVersion: '10.1'

[Appium] automationName: 'XCUITest'

[Appium] bundleId: 'au.net.abc.abcme'

[Appium] udid: '15eb7de5c880d3c6062eb2a43bfb53af06472d28'

[Appium] platformName: 'iOS'

[Appium] deviceName: 'ABC\'s iPhone'

[Appium] autoAcceptAlerts: true

[debug] [XCUITest] XCUITestDriver version: 2.0.26

[BaseDriver] Session created with session id: 2d5588ee-9833-498f-8826-5784b439f256

[debug] [XCUITest] Xcode version set to '8.1'

[debug] [XCUITest] iOS SDK Version set to '10.1'

[debug] [XCUITest] Available devices: 15eb7de5c880d3c6062eb2a43bfb53af06472d28

[debug] [XCUITest] Creating iDevice object with udid 15eb7de5c880d3c6062eb2a43bfb53af06472d28

[XCUITest] Determining device to run tests on: udid: '15eb7de5c880d3c6062eb2a43bfb53af06472d28', real device: true

[BaseDriver] Using local app '/Users/srivastava4f0z/Documents/swathi/ABCMeTabletsAutomation/src/test/resources/com/abc/mobileApps/abcme.ipa'

[debug] [BaseDriver] Copying local zip to tmp dir

[debug] [BaseDriver] Unzipping /var/folders/yg/9m75_q9j4d7dzqrjgcjfjfw9sx6hwn/T/20161011-8920-1hc8gmz.qrp1glow29/appium-app.zip

[debug] [BaseDriver] Testing zip archive: /var/folders/yg/9m75_q9j4d7dzqrjgcjfjfw9sx6hwn/T/20161011-8920-1hc8gmz.qrp1glow29/appium-app.zip

[BaseDriver] Unzipped local app to '/var/folders/yg/9m75_q9j4d7dzqrjgcjfjfw9sx6hwn/T/20161011-8920-1hc8gmz.qrp1glow29/Payload/abcme.app'

[debug] [XCUITest] Checking whether app is actually present

[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog

[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'

[XCUITest] Setting up real device

[debug] [XCUITest] Stdout from app isInstalled check: [....] Waiting for iOS device to be connected

[....] Using iPhone 6s 'ABC's iPhone' (15eb7de5c880d3c6062eb2a43bfb53af06472d28).

true

[debug] [XCUITest] App is installed.

[debug] [XCUITest] Full reset not requested. No need to install.

[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj

[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

[XCUITest] Launching WebDriverAgent on the device

[debug] [XCUITest] Carthage found: /usr/local/bin/carthage

[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=15eb7de5c880d3c6062eb2a43bfb53af06472d28' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'

[XCUITest] Waiting for WebDriverAgent to start on device

[XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability.

[debug] [XCUITest] Log file for xcodebuild test: /Users/srivastava4f0z/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/5A8917B4-C6E7-4897-A443-CF1EF60F8FB4/Session-WebDriverAgentRunner-2016-11-11_135451-ngo2zR.log

**Comment by mykola-mokhnach** [comment]
Just read the log
> [XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability.

This issue has been discussed many times already. Please look for similar existing threads.

**Comment by rkavalap** [comment]
Closing as dup
