### ISSUE TITLE
driver.lockDevice(5) is not working

### ISSUE THREAD

**Issue by shivakrishnach31** [appium/appium#7219]
## The problem
lockDevice method is not working.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable):1.4.13
* Desktop OS/version used to run Appium:Mac/Elcapitan
* Node.js version (unless using Appium.app|exe):6.8.1
* Mobile platform/version under test:iOS/9.3.2
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

driver.lockDevice(5) not working and got 'Method not implemented' exception

## Link to Appium logs

> [HTTP] <-- POST /wd/hub/session/f3139f7b-ecd9-4b1a-bf03-cb4f30bd80a3/element/AF35F06B-97C5-41CF-9846-E93FE93A1453/click 200 4003 ms - 74
> [HTTP] --> POST /wd/hub/session/f3139f7b-ecd9-4b1a-bf03-cb4f30bd80a3/appium/device/lock {"seconds":5}
> [MJSONWP] Calling AppiumDriver.lock() with args: [5,"f3139f7b-ecd9-4b1a-bf03...
> [debug] [XCUITest] Executing command 'lock'
> [HTTP] <-- POST /wd/hub/session/f3139f7b-ecd9-4b1a-bf03-cb4f30bd80a3/appium/device/lock 501 3 ms - 122
> [debug] [iProxy] recv failed: Resource temporarily unavailable
> [debug] [iProxy] recv failed: Operation not permitted

## Code To Reproduce Issue [ Good To Have ]

```
IOSDriver<MobileElement> driver = new iOSDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
driver.lockDevice(5);
```

**Comment by imurchie** [comment]
Yes. As of now Apple has provided no way to lock and unlock the device, going forward.

**Comment by rkavalap** [comment]
Closing the issue as it is external currently.
