### ISSUE TITLE
Getting error The file doesn’t exist while running appium from eclipse

### ISSUE THREAD

**Issue by rameshkvv6231** [appium/appium#7221]
I am getting an error while launching multiple devices through eclipse only. from command prompt its working fine. Please reply me ASAP

I think the error is due to --tmp argument but I don't no how to resolve that one. Can anyone suggest me. 

Error I got was

[INST STDERR] 2016-11-10 22:51:26.948 instruments[18757:344032] WebKit Threading Violation - initial use of WebKit from a secondary thread.

[debug] [Instruments] [INST STDERR] Instruments Error: Could not create output document '/Software/Eclipse/Firetest_StressTest_ABCD/tmp/dir2 &/appium-instruments/instrumentscli0.trace': The file doesn’t exist.

[debug] [Instruments] Instruments exited with code 254

[Instruments] Error launching instruments: Instruments crashed on startup

This is my code.

CommandLine command = new CommandLine("/Applications/Appium.app/Contents/Resources/node/bin/node");
command.addArgument("/Applications/Appium.app/Contents/Resources/node_modules/appium/build/lib/main.js", false);
command.addArgument("--address", false);
command.addArgument("127.0.0.1");
command.addArgument("--port", false);
command.addArgument(port);
command.addArgument("-U", false);
command.addArgument(udid);
command.addArgument("--tmp");
command.addArgument(tmp/dir2  "&");
command.addArgument("--full-reset", false);
DefaultExecuteResultHandler resultHandler = new DefaultExecuteResultHandler();
DefaultExecutor executor = new DefaultExecutor();
executor.setExitValue(1);
try {
executor.execute(command, resultHandler);
Thread.sleep(5000);
System.out.println("Appium server started.");
} catch (IOException e) {
e.printStackTrace();
} catch (InterruptedException e) {
e.printStackTrace();
}

**Comment by imurchie** [comment]
You haven't provided the information required to answer this.

What version of Appium are you using? What version of Xcode are you running?

If you could post, as a [gist](https://gist.github.com), the _full_ Appium server logs we could make a better assessment.
