### ISSUE TITLE
[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1

### ISSUE THREAD

**Issue by diego-ferrand** [appium/appium#7223]
## The problem

Executing a java test on iOS 10 in an emulator doesn't wait for the emulator to load all the way, throwing the error provided in the gist. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0.
* Desktop OS/version used to run Appium: OS X El Capitan, 10.11.6.
* Node.js version (unless using Appium.app|exe): v6.8.1.
* Mobile platform/version under test: iOS 10.0.
* Real device or emulator/simulator: emulator.
* Appium CLI or Appium.app|exe: Appium CLI.

## Details

Executing a java test on iOS 10 in an emulator doesn't wait for the emulator to load all the way, throwing the error provided in the gist. 

## Link to Appium logs
[Appium logs](https://gist.github.com/diego-ferrand/151844e7a29673829bc0ead68ddc176c)

**Comment by mykola-mokhnach** [comment]
do you have carthage installed and working on your system?

**Comment by diego-ferrand** [comment]
Carthage wasn't installed.
