### ISSUE TITLE
UNABLE TO TEST APP ON ANDROID ,GETTING ERROR AFTER LAUNCH.

### ISSUE THREAD

**Issue by sahurabi92** [appium/appium#7225]
## The problem
At first while trying to test site on android device ,on google Chrome or browser after launching ,
two three times chrome restarting and then throwing error :> info: Chromedriver: Changed state to 'stopped'
> error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM
> info: Chromedriver stopped unexpectedly on us, shutting down then calling back up with the on-die callback
 same as also on third party apps like whatsapp and other apps ,after lunching whatsapp getting error

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16.1
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: ANDROID 6.0.1
* Real device or emulator/simulator: REAL
* Appium CLI or Appium.app|exe:APPIUM.EXE

##Here is my log for chrome 
https://gist.github.com/sahurabi92/6dbf519f236c7d82ff2480de6943ad20.js
and code for chrome:
package appium;

import java.net.URL;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.android.AndroidDriver;

public class Test1 {

	public static void main(String[] args) throws Exception
	{ 
		DesiredCapabilities c=new DesiredCapabilities();
		c.setCapability(CapabilityType.BROWSER_NAME,"Chrome");
		c.setCapability("deviceName","my device");
       c.setCapability("platformName","Android");
       c.setCapability("platformVersion","6.0.1");
       URL u=new URL("http://127.0.0.1:4723/wd/hub");
       WebDriver driver=new AndroidDriver(u,c);
       Thread.sleep(5000);
       driver.get("http://www.gmail.com");
       Thread.sleep(5000);
       driver.findElement(By.name("Email")).sendKeys("xxxxx");
       Thread.sleep(3000);
       driver.findElement(By.name("passwd")).sendKeys("xxxxx");
       driver.findElement(By.id("signin")).click();
       driver.close();
                }
      }

and log for whatsapp : 
https://gist.github.com/sahurabi92/aacd798e2599c441f7bfd11ebed741f5

n code for whatsapp:
package mindq;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.By;
import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;

import io.appium.java_client.android.AndroidDriver;

public class Test9 {

	public static void main(String[] args) throws MalformedURLException, InterruptedException {
		DesiredCapabilities c=new DesiredCapabilities();
		c.setCapability(CapabilityType.BROWSER_NAME,"");
		c.setCapability("deviceName","My android");
       c.setCapability("platformName","Android");
       c.setCapability("platformVersion","6.0.1");
       c.setCapability("appPackage", "com.whatsapp");
       c.setCapability("appActivity", "com.whatsapp.Main");
       URL u=new URL("http://127.0.0.1:4723/wd/hub");
       AndroidDriver driver=new AndroidDriver(u,c);
       //Thread.sleep(5000);
      driver.findElement(By.xpath("//*[@content-desc='Search']")).click();
      Thread.sleep(5000);
      driver.findElement(By.xpath("//*[@text='Search…']")).sendKeys("Aman");
      driver.quit();
     
	     }
	}

app is launching  and after sometime getting those error ,tried all possibilities but not able to solve error ,please help me someone..

**Comment by mykola-mokhnach** [comment]
Appium 1.4 is incompatible with newer Android versions. Try to update to 1.6.0

**Comment by sahurabi92** [comment]
Is 1.6.0 is available for windows ??? plz give me the link ..

**Comment by mykola-mokhnach** [comment]
It is available in npm repository:

```
npm install -g appium@1.6.0
```

**Comment by sahurabi92** [comment]
i am new to appium can you tell me the full procedure plz..

**Comment by sahurabi92** [comment]
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>npm install -g appium@1.6.0
npm ERR! tar.unpack unzip error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-youiengine-driver\-\appium-youiengine-driver-1.0.6.tgz
npm ERR! tar.unpack unzip error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-selendroid-driver\-\appium-selendroid-driver-1.4.3.tgz
npm ERR! tar.unpack unzip error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-android-driver\-\appium-android-driver-1.10.27.tgz
npm ERR! tar.unpack untar error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-youiengine-driver\-\appium-youiengine-driver-1.0.6.tgz
npm ERR! tar.unpack untar error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-selendroid-driver\-\appium-selendroid-driver-1.4.3.tgz
npm ERR! tar.unpack unzip error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-base-driver\-\appium-base-driver-2.0.19.tgz
npm ERR! tar.unpack unzip error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-ios-driver\-\appium-ios-driver-1.12.27.tgz
npm ERR! tar.unpack unzip error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-atoms\-\appium-atoms-0.1.0.tgz
npm ERR! tar.unpack untar error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-ios-driver\-\appium-ios-driver-1.12.27.tgz
npm ERR! tar.unpack unzip error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-uiautomator2-server\-\appium-uiautomator2-server-0.0.1.tgz
npm ERR! tar.unpack untar error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-uiautomator2-server\-\appium-uiautomator2-server-0.0.1.tgz
npm ERR! tar.unpack unzip error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-android-bootstrap\-\appium-android-bootstrap-2.7.5.tgz
npm ERR! tar.unpack unzip error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\babel-core\-\babel-core-5.8.24.tgz
npm ERR! tar.unpack unzip error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-adb\-\appium-adb-2.6.17.tgz
npm ERR! tar.unpack untar error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-adb\-\appium-adb-2.6.17.tgz
npm ERR! tar.unpack unzip error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-instruments\-\appium-instruments-3.8.5.tgz
npm ERR! tar.unpack untar error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\babel-core\-\babel-core-5.8.24.tgz
npm ERR! tar.unpack untar error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-instruments\-\appium-instruments-3.8.5.tgz
npm ERR! tar.unpack unzip error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-xcuitest-driver\-\appium-xcuitest-driver-2.0.26.tgz
npm ERR! tar.unpack untar error C:\Users\rabi\AppData\Local\Temp\npm-34332-c3ac6df7\registry.npmjs.org\appium-xcuitest-driver\-\appium-xcuitest-driver-2.0.26.tgz
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium@1.6.0"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5

npm ERR! unexpected end of file
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log


get this error while trying to install appium from npm

**Comment by mykola-mokhnach** [comment]
Try 

```
npm cache clean
npm install -g appium@1.6.0 --no-shrinkwrap
npm install -g appium@1.6.0
```

This might be similar issue https://github.com/npm/npm/issues/11993

**Comment by sahurabi92** [comment]
Thanks 1.6.0 installed successfully but getting same error ,chrome restating unexceptionally. n throwing exception : "no such session"  on IDE

**Comment by amedvedjev** [comment]
your npm version is?

**Comment by sahurabi92** [comment]
latest one 3.10.3

**Comment by mykola-mokhnach** [comment]
you need to provide _appActivity_ capability, which should be equal to activity id, which is the first to start (seems like it's com.whatsapp/.HomeActivity in your case)

**Comment by sahurabi92** [comment]
Thanks i will try but what about browser error ??  launching browser "data;" like this then closing automatically..whats the issue??

**Comment by mykola-mokhnach** [comment]
Try to download the most recent chromedriver binary and provide path to it using _ chromedriverExecutable_ capability. Check http://stackoverflow.com/questions/40235380/protractor-selenium-webdriver-runtime-executioncontextcreated-has-invalid-c for more details.

**Comment by rkavalap** [comment]
@sahurabi92  IMO:
You may want to look at the version of your chrome on your android device, and then download the appropriate version of chromedriver. You can check the chromedriver's support version for chrome based on the download url and look at the notes.txt

If you want a specific version of chromedriver to be installed with appium,
set the env variable for (CHROMEDRIVER_VERSION) to the version you want. which could be 2.25 or 2.24 etc.

**Comment by sahurabi92** [comment]
thanks to all :   my prob is solved but facing a issue while launching 3rd party app for testing ,the app is lunching with cleared data .like while i am tried to automate whatsapp,app is lunching but previous data is clearing Thats why unable to automate

**Comment by mykola-mokhnach** [comment]
set _noReset_ capability to _true_

**Comment by sahurabi92** [comment]
Thanks a lot mykola-mokhnach 
and last one how to know the correct app activity name ??

**Comment by amedvedjev** [comment]
easiest: add any activity name, enable log level in appium to debug and start. In logs it will be written what activity appeared with tested app after start.
