### ISSUE TITLE
inspector error help me ~~~ appium 1.5.3 

### ISSUE THREAD

**Issue by SubinLee** [appium/appium#7226]
Obviously the inspector function is not working right now.
The cause of the error is not found.
Help. Please.
I do not speak English very well and I have used a translator.

Appium 1.5.3
Mac OS: Sierra
Xcode: 7.3.1
Device: iphone 5 (9.1)

[iOSLog] [IOS_SYSLOG_ROW] Nov 14 10:24:16 dev installd[43] <Error>: 0x40081000 +[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]: 142: Failed to verify code signature of /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.g1jA5o/extracted/Qpost.app : 0xe8008018 (The identity used to sign the executable is no longer valid.)

[iOSLog] [IOS_SYSLOG_ROW] Nov 14 10:24:16 dev installd[43] <Error>: 0x40081000 -[MIInstaller performInstallationWithError:]: Verification stage failed
[iOSLog] [IOS_SYSLOG_ROW] Nov 14 10:24:16 dev profiled[149] <Notice>: (Note ) MC: Provisioning profiles changed

[iOSLog] [IOS_SYSLOG_ROW] Nov 14 10:24:16 dev profiled[149] <Notice>: (Note ) MC: Updating MIS trust...

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[iOSLog] [IOS_SYSLOG_ROW] Nov 14 10:24:17 dev routined[37] <Error>: CoreLocation: Error occurred while trying to retrieve motion state update: CMErrorDomain Code:104

[HTTP] <-- GET /wd/hub/status - - ms - - 

[iOSLog] [IOS_SYSLOG_ROW] Nov 14 10:24:18 dev mobile_installation_proxy[193] <Error>: 0x4029b000 __MobileInstallationInstallForLaunchServices_block_invoke222: Returned error Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.g1jA5o/extracted/Qpost.app : 0xe8008018 (The identity used to sign the executable is no longer valid.)" UserInfo={LibMISErrorNumber=-402620392, LegacyErrorString=ApplicationVerificationFailed, FunctionName=+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:], NSLocalizedDescription=Failed to verify code signature of /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.g1jA5o/extracted/Qpost.app : 0xe8008018 (The identity used to sign the executable is no longer valid.), SourceFileLine=142}

[iOSLog] [IOS_SYSLOG_ROW] Nov 14 10:24:18 dev mobile_installation_proxy[193] <Warning>: ERROR: MobileInstallationInstallForLaunchServices returned nil

[iOSLog] [IOS_SYSLOG_ROW] Nov 14 10:24:18 dev mobile_installation_proxy[193] <Error>: 0x40081000 handle_install: Installation failed: Error Domain=LaunchServicesError Code=0 "(null)" UserInfo={Error=ApplicationVerificationFailed, ErrorDetail=-402620392, ErrorDescription=Failed to verify code signature of /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.g1jA5o/extracted/Qpost.app : 0xe8008018 (The identity used to sign the executable is no longer valid.)}

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Encountered internal error running command: Error: Command failed: ideviceinstaller -u 73e931ec4a6c380dedadee6cc67af590ee93adc8 -i /var/folders/bm/mn11kb9j3y16yq7g39hgy89r0000gn/T/20161014-13626-zn6m2e/Payload/Qpost.app

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)

[HTTP] <-- POST /wd/hub/session 500 48169 ms - 307 

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 747 ms - 83

**Comment by imurchie** [comment]
It looks to me like your application has been signed by an identity that no longer exists or no longer has the rights to sign. This issue appears to be relatively common (see, for instance, http://stackoverflow.com/questions/31484742/0xe8008018-the-identity-used-to-sign-the-executable-is-no-longer-valid).
