### ISSUE TITLE
Long press element issue

### ISSUE THREAD

**Issue by tomliuxin** [appium/appium#7229]
## The problem

need to long press one element, met the issue:
ProxyRequestError: Could not proxy command to remote server. Original error: 500 

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.0
* Desktop OS/version used to run Appium: window 10
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: emulator

## Code To Reproduce Issue [ Good To Have ]
TouchAction action = new TouchAction(driver);
action.LongPress(oneelement).Perform();

anyting I missed?

**Comment by sravanmedarapu** [comment]
Can you share appium server logs in a separate [gist ](https://gist.github.com/)?

**Comment by tomliuxin** [comment]
@sravanmedarapu  Thanks help. 
log: https://gist.github.com/tomliuxin/07247381f5b1fb584b883d0abed2b6ab 
run at appium 1.4.16

**Comment by tomliuxin** [comment]
code:
  TouchAction action = new TouchAction(PowerAppUtility.myDriver);
                action.LongPress(Manage.ThreePoint, Manage.ThreePoint.Location.X, Manage.ThreePoint.Location.Y).Perform();

**Comment by dodigital** [comment]
Were you able to resolve the issue and long press on the element in the end ?

**Comment by tomliuxin** [comment]
Nope, i did not solve it, do you have any comments about it? Thanks

**Comment by sravanmedarapu** [comment]
@tomliuxin, In the issue description you mentioned that you are getting `ProxyRequestError: Could not proxy command to remote server. Original error: 500 `. but in the logs you provided I don't see such stuff.

Can you give a try in v1.6.0 with out UiAutomator2 capability.

**Comment by tomliuxin** [comment]
@sravanmedarapu  Thanks. 

not sure why I can't open the gist website. 

copy the log:

Appium 1.6.0, with out UIAutomatior2: error: Failed to execute touch event
Log:
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"82"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getLocation
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"x":1272,"y":98}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getLocation() result: {"x":1272,"y":98}
[HTTP] <-- GET /wd/hub/session/30739a8d-863f-4660-832e-14df961ebd98/element/82/location 200 26 ms - 89
[HTTP] --> GET /wd/hub/session/30739a8d-863f-4660-832e-14df961ebd98/element/82/location {}
[MJSONWP] Calling AppiumDriver.getLocation() with args: ["82","30739a8d-863f-4660-832e-14df961ebd98"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getLocation","params":{"elementId":"82"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"82"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getLocation
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"x":1272,"y":98}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getLocation() result: {"x":1272,"y":98}
[HTTP] <-- GET /wd/hub/session/30739a8d-863f-4660-832e-14df961ebd98/element/82/location 200 8 ms - 89
[HTTP] --> GET /wd/hub/session/30739a8d-863f-4660-832e-14df961ebd98/element/82/location {}
[MJSONWP] Calling AppiumDriver.getLocation() with args: ["82","30739a8d-863f-4660-832e-14df961ebd98"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getLocation","params":{"elementId":"82"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"82"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getLocation
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"x":1272,"y":98}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getLocation() result: {"x":1272,"y":98}
[HTTP] <-- GET /wd/hub/session/30739a8d-863f-4660-832e-14df961ebd98/element/82/location 200 8 ms - 89
[HTTP] --> GET /wd/hub/session/30739a8d-863f-4660-832e-14df961ebd98/element/82/location {}
[MJSONWP] Calling AppiumDriver.getLocation() with args: ["82","30739a8d-863f-4660-832e-14df961ebd98"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:getLocation","params":{"elementId":"82"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:getLocation","params":{"elementId":"82"}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: getLocation
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"x":1272,"y":98}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getLocation() result: {"x":1272,"y":98}
[HTTP] <-- GET /wd/hub/session/30739a8d-863f-4660-832e-14df961ebd98/element/82/location 200 8 ms - 89
[HTTP] --> POST /wd/hub/session/30739a8d-863f-4660-832e-14df961ebd98/touch/perform {"actions":[{"action":"moveTo","options":{"x":1272,"y":98}},{"action":"longpress","options":{"element":"82","x":1272,"y":98}},{"action":"wait","options":{"ms":2000}},{"action":"release"}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"moveTo","options":{"x":1272,"y":98}},{"action":"longpress","options":{"element":"82","x":1272,"y":98}},{"action":"wait","options":{"ms":2000}},{"action":"release"}],"30739a8d-863f-4660-832e-14df961ebd98"]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:touchMove","params":{"x":1272,"y":98}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:touchMove","params":{"x":1272,"y":98}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: touchMove
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Display bounds: [0,0][1440,2392]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Performing TouchMove using element? false x: 1272, y: 98
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":13,"value":"**Failed to execute touch event"}**
[debug] [AndroidBootstrap] Received command result from bootstrap
[HTTP] <-- POST /wd/hub/session/30739a8d-863f-4660-832e-14df961ebd98/touch/perform 500 17 ms - 154

**Comment by tomliuxin** [comment]
@sravanmedarapu Thanks.

not sure why I can't open the gist website.

copy the log:

Appium 1.6.0, with UIAutomatior2: error: ProxyRequestError: Could not proxy command to remote server. Original error: 500
 Log:
[MJSONWP] Responding to client with driver.getLocation() result: {"x":1272,"y":98}
[HTTP] <-- GET /wd/hub/session/e82a0a7b-968e-4bfd-b9e3-0d375ddd09c2/element/f3227b58-2090-40b9-b891-208f2cbad6dd/location 200 14 ms - 89
[HTTP] --> GET /wd/hub/session/e82a0a7b-968e-4bfd-b9e3-0d375ddd09c2/element/f3227b58-2090-40b9-b891-208f2cbad6dd/location {}
[MJSONWP] Calling AppiumDriver.getLocation() with args: ["f3227b58-2090-40b9-b891-208f2cbad6dd","e82a0a7b-968e-4bfd-b9e3-0d375ddd09c2"]
[UiAutomator2] calling get location: f3227b58-2090-40b9-b891-208f2cbad6dd
[JSONWP Proxy] Proxying [GET /element/f3227b58-2090-40b9-b891-208f2cbad6dd/location] to [GET http://localhost:8200/wd/hub/session/e66e1912-08c3-438a-87b6-910c6c69a744/element/f3227b58-2090-40b9-b891-208f2cbad6dd/location] with body: {}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"e66e1912-08c3-438a-87b6-910c6c69a744\",\"status\":0,\"value\":{\"x\":1272,\"y\":98}}"
[MJSONWP] Responding to client with driver.getLocation() result: {"x":1272,"y":98}
[HTTP] <-- GET /wd/hub/session/e82a0a7b-968e-4bfd-b9e3-0d375ddd09c2/element/f3227b58-2090-40b9-b891-208f2cbad6dd/location 200 16 ms - 89
[HTTP] --> GET /wd/hub/session/e82a0a7b-968e-4bfd-b9e3-0d375ddd09c2/element/f3227b58-2090-40b9-b891-208f2cbad6dd/location {}
[MJSONWP] Calling AppiumDriver.getLocation() with args: ["f3227b58-2090-40b9-b891-208f2cbad6dd","e82a0a7b-968e-4bfd-b9e3-0d375ddd09c2"]
[UiAutomator2] calling get location: f3227b58-2090-40b9-b891-208f2cbad6dd
[JSONWP Proxy] Proxying [GET /element/f3227b58-2090-40b9-b891-208f2cbad6dd/location] to [GET http://localhost:8200/wd/hub/session/e66e1912-08c3-438a-87b6-910c6c69a744/element/f3227b58-2090-40b9-b891-208f2cbad6dd/location] with body: {}
[JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"e66e1912-08c3-438a-87b6-910c6c69a744\",\"status\":0,\"value\":{\"x\":1272,\"y\":98}}"
[MJSONWP] Responding to client with driver.getLocation() result: {"x":1272,"y":98}
[HTTP] <-- GET /wd/hub/session/e82a0a7b-968e-4bfd-b9e3-0d375ddd09c2/element/f3227b58-2090-40b9-b891-208f2cbad6dd/location 200 14 ms - 89
[HTTP] --> POST /wd/hub/session/e82a0a7b-968e-4bfd-b9e3-0d375ddd09c2/touch/perform {"actions":[{"action":"moveTo","options":{"x":1272,"y":98}},{"action":"longpress","options":{"element":"f3227b58-2090-40b9-b891-208f2cbad6dd","x":1272,"y":98}},{"action":"wait","options":{"ms":2000}},{"action":"release"}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"moveTo","options":{"x":1272,"y":98}},{"action":"longpress","options":{"element":"f3227b58-2090-40b9-b891-208f2cbad6dd","x":1272,"y":98}},{"action":"wait","options":{"ms":2000}},{"action":"release"}],"e82a0a7b-968e-4bfd-b9e3-0d375ddd09...
[JSONWP Proxy] Proxying [POST /touch/move] to [POST http://localhost:8200/wd/hub/session/e66e1912-08c3-438a-87b6-910c6c69a744/touch/move] with body: {"params":{"x":1272,"y":98}}
[MJSONWP] Encountered internal error running command:  {"jsonwp":{"sessionId":"e66e1912-08c3-438a-87b6-910c6c69a744","status":13,"value":false}} ProxyRequestError**: Could not proxy command to remote server. Original error: 500** - {"sessionId":"e66e1912-08c3-438a-87b6-910c6c69a744","status":13,"value":false}

**Comment by Dymon01** [comment]
Hi tomliuxin.
if you need to long press one element. 
try to use swipe which duration as you need and set bouth points on your element 
its worked for me

**Comment by tomliuxin** [comment]
@Dymon01 , thanks. 

you mean use the Driver.Swipe(element.x, element.y, emelemt.x, element.y, duration)?

could you give me one sample code which worked for you? Thanks.

**Comment by sravanmedarapu** [comment]
@tomliuxin, Can you try by updating uiautomator2 driver to 0.0.9

 npm install appium-uiautomator2-driver@0.0.9

**Comment by tomliuxin** [comment]
Thanks all, issue resolved
