### ISSUE TITLE
Appium 1.6.1-beta, xcode 8.1- ios not working 

### ISSUE THREAD

**Issue by kineret321** [appium/appium#7230]
Hi,
Im trying to to use appium1.6.1-beta, xcode version 8.1 with ios device- no matter the ios device version (tried with ios 8.1 and ios 10.0.0.1)
and i got error message:
Appium's IosDriver does not support xcode version 8.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.

desired capabilities:
desired_caps = {}
desired_caps['appium-version'] = '1.6.1'
desired_caps['platformName'] = 'ios'
desired_caps['platformVersion'] = '10.0.1'
desired_caps['deviceName'] = 's5'
desired_caps['app'] = os.path.abspath(desktop+"/ios_1.7.2_TE3487.ipa")
desired_caps['udid']= 'db965483453320c02bb5907be3b02248b2f99576'

I tried to add 
desired_caps['automationName']='XCUITest'
but still not working

another issue: how can i inspect ios element with appium client 1.6.1-beta? could not find solution.

Thanks

Please help

**Comment by zmorris** [comment]
For anyone new to Appium, the pull request mentioned in https://github.com/appium/sample-code/issues/101 helped me get https://github.com/appium/sample-code running, then you can examine its tests to see what's changed.

See https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md for more specifics.
