### ISSUE TITLE
"You don’t have permission to save the file “KissXML” in the folder “Checkouts”.

### ISSUE THREAD

**Issue by kirangowdawestwing** [appium/appium#7232]
## The problem

I ran into a couple of issues setting up the 1.6.0-beta1 driver for iOS 10 simulator testing with the XCUITestDriver.

  stdout: '\u001b[1mFetching dependencies\n*** Skipped downloading KissXML.framework binary due to the error:\n\t"API rate limit exceeded for 217.111.53.37. (But here\'s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"\n*** Checking out KissXML at "5.0.5"\n',
  stderr: 'Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/KissXML: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “KissXML” in the folder “Checkouts”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/KissXML, NSUnderlyingError=0x7ffcb0c6f250 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})\n',

## Environment

* Appium version (or git revision) that exhibits the issue:  1.6.1
* iOS 10.1

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
 { Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  stdout: '\u001b[1mFetching dependencies\n*** Skipped downloading KissXML.framework binary due to the error:\n\t"API rate limit exceeded for 217.111.53.37. (But here\'s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"\n*** Checking out KissXML at "5.0.5"\n',
  stderr: 'Failed to check out repository into /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/KissXML: Could not create working directory (Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “KissXML” in the folder “Checkouts”." UserInfo={NSFilePath=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Checkouts/KissXML, NSUnderlyingError=0x7ffcb0c6f250 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}})\n',
  code: 1 }
[XCUITest] Shutting down WebDriverAgent
[debug] [XCUITest] Running iOS simulator reset flow
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [XCUITest] Full reset is on. Cleaning simulator
[debug] [iOSSim] Killing any simulator daemons for B0B93535-FB60-4E23-80B6-2F71B547B3FF
[iOSSim] Cleaning simulator B0B93535-FB60-4E23-80B6-2F71B547B3FF
[debug] [XCUITest] Resetting simulator
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
[HTTP] <-- POST /wd/hub/session 500 46299 ms - 199 

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
```bash
sudo chown -R $USER /usr/local 
```
