### ISSUE TITLE
Failed to find scrollable visible parent

### ISSUE THREAD

**Issue by simondh** [appium/appium#7233]
## The problem

I have written a very simple IOS App to test the testing. Got Appium 1.1.6-beta to run the app on a live iPhone. The app runs up, but the last python line here:

```
    def test_taper_length_entry(self):
        # print (self.driver.debugDescription)
        lenField = self.driver.find_element_by_accessibility_id('taperLengthField')
        lenField.clear()
        # lenField.set_value('100') tried this as well, same error
        lenField.send_keys("100") # crashes here with odd message "Failed to find scrollable visible parent with 2 visible children"
```
 repeatedly causes a failure
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Failed to find scrollable visible parent with 2 visible children\" UserInfo={NSLocalizedDescription=Failed to find scrollable visible parent with 2 visible children}","sessionId":"4586337D-3C64-4432-A4C5-12ACDD109CFD","status":13}

## Environment

* Appium version 1.6.1-beta
* (only got app working on iphone with 1.6.1!)
* Desktop macOS 10.12.1, Xcode Version 8.1 (8B62)
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: iPhone 6, IOS 10.1.1
* Real device or emulator/simulator:Real, iPhone 6
* Appium CLI or Appium.app|exe: CLI
testing from Python 2.7

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

Gist
<script src="https://gist.github.com/simondh/c801a98e328fc791842d5dd902e12e66.js"></script>

**Comment by simondh** [comment]
Full Git of Swift app and Python test here
https://bitbucket.org/simon_hewitt/appiumtest/admin

**Comment by mbaglay** [comment]
Have the same problem on attempt to tap a facebook login field.

**Comment by raymondlapak** [comment]
Any update on this one? I face this issue when running the test on my apps, trying to tap on a textview..

**Comment by artemenko-a-a** [comment]
@raymondlapak I had the same problem. Updating Appium to version 1.6.3 helped me.

**Comment by raymondlapak** [comment]
Thanks. Was using the old version of appium-xcuitest-driver. Updating to the 2.5.3 resolve this.
