### ISSUE TITLE
Double tap doesn't work after switching to xcuitest framework

### ISSUE THREAD

**Issue by NagyRobertt** [appium/appium#7234]
## The problem

Had an implementation of double tap. After the switch it doesn't work and the app crashes.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS
* Mobile platform/version under test: iOS 10.0.2
* Real device or emulator/simulator: real device

## Details

I'm not sure if this is an issue or simply the we did it is not supported anymore. If the way we are doing is not applicable anymore would like to know how we could implement double tap method differently

## Link to Appium logs

https://gist.github.com/NagyRobertt/b62360465c6c2457d129701b0a09ca35 - log with iOS syslog (very noisy)
https://gist.github.com/NagyRobertt/cf648d69ca3aa6b6f3b4f0537f75171b (without syslog)

## Code used 
```
public void openApplicationAdditionalSettings(WebElement elementToDblTap) {
        this.getLogger().logDebug("Performing double tap on the given element.");
        String elementId = ((RemoteWebElement) elementToDblTap).getId();
        ((RemoteWebDriver) this).executeScript("au.getElement('" + elementId + "').tapWithOptions({tapCount:2});");
    }
```

**Comment by imurchie** [comment]
Yes. There is no longer any UI Automation, so any UI Automation code you were sending in will not work.

**Comment by NagyRobertt** [comment]
Cool. Thanks. So in order to try this out i just need to checkout the master codeline?

**Comment by imurchie** [comment]
It is available in `appium-xcuitest-driver@2.0.35`. You can update by re-installing 1.6.1-beta

```
npm uninstall -g appium
npm install -g appium@beta
```

**Comment by NagyRobertt** [comment]
Ok. Did that but now i'm not sure how i can call the new function. Should it be something like
TouchAction touch = new TouchAction(driver);
touch.DoubleTap(element); ?

Because it is not showing anything.

**Comment by NagyRobertt** [comment]
@imurchie can you give any comment on this? Also i'm using java, for the automation.

**Comment by LukasLewandowski** [comment]
Any progress on this? 

Old (form Appium 1.5.3) method to double tap is not working:

            action.tap(element=None, x=position_x, y=position_y, count=2).perform()

**Comment by NagyRobertt** [comment]
For me this is actually already working. In the xcuitest-driver this is already implemented. For java-client a feature was missing because i was using an old client version. However i don't about python.

**Comment by vikramvi** [comment]
@NagyRobertt can you please open this issue under appium java client project ?

**Comment by saikrishna321** [comment]
Try this with the latest java-client,

https://github.com/saikrishna321/VodQaAdvancedAppium/blob/master/src/test/java/com/appium/gesture/GestureTest.java
