### ISSUE TITLE
unable to switch to webview in Appium Selendroid mode

### ISSUE THREAD

**Issue by 5rajesh** [appium/appium#7236]
## The problem
I am unable to switch to Webview in appium selendroid mode. Getting error An unknown server-side error occurred while processing the command. (Original error: read ECONNRESET)

## Environment

I am facing this problem in Appium 1.4.00/ 1.4.13/1.4.16
* Appium version (or git revision) that exhibits the issue: Appium 1.4.00/ 1.4.13/1.4.16
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): V 6.3.0
* Mobile platform/version under test: 4.2.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.exe

## Details

After attching the context 'webview_0' in the next step when trying to close the pop up (driver.findElement(By.xpath("//*[@id='popupClose']")).click();) getting below error. It'll be great if somebody help me on the same. Thanks in advance.

> info: [debug] Available contexts: ["NATIVE_APP","WEBVIEW_0"]
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228/context","method":"POST","json":{"name":"WEBVIEW_0"}}
> info: [debug] [SELENDROID] [CDS]close[8080]
> info: [debug] [SELENDROID] close [socket][/0.0.0.0:8080]
> info: [debug] [SELENDROID] close [socket][/0.0.0.0:-1]
> info: [debug] [SELENDROID] io.selendroid.server.model.SelendroidWebDriver$SelendroidWebChromeClient cannot be cast to org.apache.cordova.engine.SystemWebChromeClient
> info: [debug] [SELENDROID] 	at org.apache.cordova.engine.SystemWebView.setWebChromeClient(SystemWebView.java:76)
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"0431d6c8-82c4-36ed-3473-95584c27e228"}
> info: <-- POST /wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228/context 200 626.480 ms - 76 {"status":0,"value":null,"sessionId":"0431d6c8-82c4-36ed-3473-95584c27e228"}
> info: [debug] [SELENDROID] [CDS]close[8080]
> info: [debug] [SELENDROID] close [socket][/0.0.0.0:8080]
> info: --> POST /wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228/elements {"using":"id","value":"popupClose"}
> info: [debug] Proxying command to localhost:8080
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228/elements","method":"POST","json":{"using":"id","value":"popupClose"}}
> info: [debug] [SELENDROID] close [socket][/0.0.0.0:-1]
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Did not successfully proxy server command"},"sessionId":"0431d6c8-82c4-36ed-3473-95584c27e228"}
> info: <-- POST /wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228/elements 500 278.162 ms - 210 
> info: --> DELETE /wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228 {}
> info: Shutting down appium session
> info: [debug] Stopping selendroid server
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228","method":"DELETE"}
> info: [debug] Cleaning up appium session
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: read ECONNRESET)","code":"ECONNRESET","errno":"ECONNRESET","syscall":"read","origValue":"read ECONNRESET"},"sessionId":null}

## Link to Appium logs

> info: [debug] Available contexts: ["NATIVE_APP","WEBVIEW_0"]
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228/context","method":"POST","json":{"name":"WEBVIEW_0"}}
> info: [debug] [SELENDROID] [CDS]close[8080]
> info: [debug] [SELENDROID] close [socket][/0.0.0.0:8080]
> info: [debug] [SELENDROID] close [socket][/0.0.0.0:-1]
> info: [debug] [SELENDROID] io.selendroid.server.model.SelendroidWebDriver$SelendroidWebChromeClient cannot be cast to org.apache.cordova.engine.SystemWebChromeClient
> info: [debug] [SELENDROID] 	at org.apache.cordova.engine.SystemWebView.setWebChromeClient(SystemWebView.java:76)
> info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"0431d6c8-82c4-36ed-3473-95584c27e228"}
> info: <-- POST /wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228/context 200 626.480 ms - 76 {"status":0,"value":null,"sessionId":"0431d6c8-82c4-36ed-3473-95584c27e228"}
> info: [debug] [SELENDROID] [CDS]close[8080]
> info: [debug] [SELENDROID] close [socket][/0.0.0.0:8080]
> info: --> POST /wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228/elements {"using":"id","value":"popupClose"}
> info: [debug] Proxying command to localhost:8080
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228/elements","method":"POST","json":{"using":"id","value":"popupClose"}}
> info: [debug] [SELENDROID] close [socket][/0.0.0.0:-1]
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Did not successfully proxy server command"},"sessionId":"0431d6c8-82c4-36ed-3473-95584c27e228"}
> info: <-- POST /wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228/elements 500 278.162 ms - 210 
> info: --> DELETE /wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228 {}
> info: Shutting down appium session
> info: [debug] Stopping selendroid server
> info: [debug] Making http request with opts: {"url":"http://localhost:8080/wd/hub/session/0431d6c8-82c4-36ed-3473-95584c27e228","method":"DELETE"}
> info: [debug] Cleaning up appium session
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: read ECONNRESET)","code":"ECONNRESET","errno":"ECONNRESET","syscall":"read","origValue":"read ECONNRESET"},"sessionId":null}

## Code To Reproduce Issue [ Good To Have ]

AndroidDriver<MobileElement> driver;

			DesiredCapabilities capabilities = new DesiredCapabilities();
			capabilities.setCapability("browserName", "");
			capabilities.setCapability("platformName", "Android");
			capabilities.setCapability("automationName", "Selendroid");
			capabilities.setCapability("version", "4.2.2");
			capabilities.setCapability("locationContextEnabled", true);
			capabilities.setCapability("deviceName", "444434GGFLKL");
			capabilities.setCapability("app", app.getAbsolutePath());
			capabilities.setCapability("appPackage", "xyz.xyz.com");
			capabilities.setCapability("appActivity", ".XYZActivity");
			driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

						Set<String> contextNames1 =  driver.getContextHandles();
						for (String contextName : contextNames1) 
						  {
						      if (contextName.contains("NATIVE_APP"))
						      {
						           driver.context(contextName);
						      }
						  }
						
						Set<String> contextNames =  driver.getContextHandles();
						for (String contextName : contextNames) 
						{
						    if (contextName.contains("WEBVIEW"))
						    {
						         driver.context(contextName);
						    }
						}

driver.findElement(By.xpath("//*[@id='popupClose']")).click();

**Comment by dpgraham** [comment]
Closing this. If this is still an issue I'll re-open.
