### ISSUE TITLE
App cache deleted when starting already installed app

### ISSUE THREAD

**Issue by rexors** [appium/appium#7238]
## The problem

The App cache seems to be deleted everytime appium starts the already installed app. I don't want the cache to be deleted because this leads to very long loading operations on app startup (some content has to be downloaded).

Right now I need to downgrade to Appium 1.5.3 but this is no option anymore, because I am testing on iOS and Android at the same time and testing with iOS 10+ needs Appium to be 1.6.0+.

When you need more information, let me know.

Thanks in advance!

## Environment

* Appium version (or git revision) that exhibits the issue: 1-6-0 - 1.6.1-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3 and earlier
* Desktop OS/version used to run Appium: OSX  10.11.6
* Node.js version (unless using Appium.app|exe): 6.8.0
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Appium Logs

[Logs](https://gist.github.com/rexors/15ab4b628338380804011f9ff67706b8)

## Code To Reproduce Issue [ Good To Have ]

```
desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, 'Appium')
desiredCapabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 20)
desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, 'Android Device')
desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, 'Android')
desiredCapabilities.setCapability(AndroidMobileCapabilityType.APP_PACKAGE, 'secret.app.test')
desiredCapabilities.setCapability(AndroidMobileCapabilityType.APP_ACTIVITY, '.MainActivity')
desiredCapabilities.setCapability(MobileCapabilityType.TAKES_SCREENSHOT, true)
desiredCapabilities.setCapability('fullReset', false)
desiredCapabilities.setCapability('clearSystemFiles', false)
```

**Comment by mykola-mokhnach** [comment]
Have you tried to set _noReset_ capability to _true_?

**Comment by rexors** [comment]
@mykola-mokhnach I will try!

**Comment by rexors** [comment]
@mykola-mokhnach Haha, yeah, it's working. Didn't know about this capability because I didn't need it before. Thank you very much for the super fast answer! :+1:

**Comment by dpgraham** [comment]
Thanks @mykola-mokhnach!
