### ISSUE TITLE
Unable to click on elements which are visible

### ISSUE THREAD

**Issue by sami7g** [appium/appium#7241]
Element properties as:
enabled:true
visible:false
valid: true

Not able to click on few elements which has same properties as above. tried in different ways
- Using JS code as below
```javascript
JavascriptExecutor js = (JavascriptExecutor) driver;
    HashMap<String, Double> tapObject = new HashMap<String, Double>();
    tapObject.put("x", x);
    tapObject.put("y", y);
    tapObject.put("duration", 1.0);
    tapObject.put("touchCount", 1.0);
    tapObject.put("tapCount", 1.0);
    js.executeScript("mobile: tap", tapObject);
```

- Usind xpath:
```javascript
driver.findElementByXPath("//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAWebView[1]/UIAStaticText[6]").click();
```
## Environment

* Appium version:1.4.8
* Desktop OS/version used to run Appium:OS X EI Captain(10.11.6)
* Mobile platform/version under test: 8.3
* Real device or emulator/simulator: Real device ipod
* Xcode: 7.3

**Comment by imurchie** [comment]
Can you define "unable" a bit more? Does it fail? Not click? 

Generally, the _full_ Appium server logs (as a [gist](https://gist.github.com) make it easier to make any diagnose and help. Thanks!

**Comment by sami7g** [comment]
UI implementation is on Angularjs, check the appium server log as attached.
i'm trying to click on element with label 'Cycle Count'. even i tried using wait method.

**Comment by sami7g** [comment]
[CC_Appiumlog.txt](https://github.com/appium/appium/files/599196/CC_Appiumlog.txt)
Kindly check it.

**Comment by imurchie** [comment]
Can you post it as a [gist](https://gist.github.com)? I cannot open random files.
