### ISSUE TITLE
Repository Tag Doesn't mention windows support

### ISSUE THREAD

**Issue by milkshakeuk** [appium/appium#7244]
## The problem

The Repository tagline currently reads "Automation for iOS and Android Apps. http://appium.io/" 

## Environment

NA

## Details

With the newly added support for windows apps the tagline should probably updated to include this.

perhaps one of the below will suffice:

"Automation for iOS, Android and Windows Apps. http://appium.io/"
"Automation for iOS, Windows and Android Apps. http://appium.io/"
"Automation for Windows, iOS and Android Apps. http://appium.io/"

**Comment by imurchie** [comment]
Good idea!. Thanks.
