### ISSUE TITLE
Can't send keys to a UIAlertController with textField

### ISSUE THREAD

**Issue by dodigital** [appium/appium#7245]
## The problem

Simply as the title states. I'm unable to use the sendKeys(String) method to enter texts into a UITextField during testing. I also previously used to be able to tap on certain keys on a keyboard when it's in view. 

Since updated to the Appium Beta 1.6.1 version the problem above arose. I had to use this version due to being able to slide on a UISlider.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1 beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.0
* Desktop OS/version used to run Appium: Mac
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device

## Details

I created a simple demo project to simulate the interaction with a alertcontroller textfield. The user long presses on a point on the screen and an alertcontroller with a textfield pops up and the user is supposed to be able to enter a text into the textfield.

## Link to Appium logs: 
Via command line:
[]https://gist.github.com/dodigital/5f9b89f42f549bda00aa8b3c79c54754
Via eclipse console:
[]https://gist.github.com/dodigital/849587c7bc76f3f089b5a9aae5dd82d6

## Code To Reproduce Issue
```java
        @Test (priority = 1)
	public void scenarioOne() throws InterruptedException {
		Thread.sleep(3000);
		// Highlight A, X position
		int posX = driver.manage().window().getSize().getWidth() / 2;
		int posY = driver.manage().window().getSize().getHeight() / 2;
		
		TouchAction longPress = new TouchAction(driver);
		longPress.press(posY, posX).waitAction(2000).release().perform();
		
		Thread.sleep(2000);
		System.out.println(driver.getPageSource());
		
		WebElement field = (new WebDriverWait(driver, 5).until(ExpectedConditions.presenceOfElementLocated(By.xpath("//XCUIElementTypeTextField"))));
		field.click();
		field.sendKeys("TEST");
		
		//typeTextIntoAlert("TEST");
	
	}
	
	
	public void typeTextIntoAlert(String test){
		
		char[] charArray = test.toCharArray();
		
		for(int i = 0; i < charArray.length; i++){
			driver.findElement(By.xpath(String.format("//XCUIElementTypeKey[@name='%s']", Character.toString(charArray[i]).toLowerCase()))).click();
		}
	}
```

**Comment by imurchie** [comment]
Can you provide the _full_ log? There is contextual information that is necessary to do anything.

**Comment by dodigital** [comment]
@imurchie Updated to public gists* both Eclipse and Command line recorded logs

**Comment by dodigital** [comment]
@imurchie I've updated the gist as requested earlier. I haven't been able to resolve the issue as of yet. Please do have a look. Thanks.

**Comment by jlipps** [comment]
@dodigital did you try using the alert methods which are designed for entering text into an alert? something like this:

```java
Alert alert=driver.switchTo().alert();
alert.sendKeys("foo");
```

**Comment by dodigital** [comment]
@jlipps Thanks for the tip. That doesn't work either. Although accepting an alert via driver.accept(); does work. I get the error message below when trying 'driver.sendKeys("foo")'

```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/901B155B-DCC3-4123-B2E3-CB45C0790623/alert/text -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/901B155B-DCC3-4123-B2E3-CB45C0790623/alert/text"
    );
} (WARNING: The server did not provide any stacktrace information)
```

**Comment by babusurendra** [comment]
Hi @jlipps , I have the same issue ,both sendkeys and setvalue are not working , as it already reported as bug, is there any update on this? 

I have my scripts in ruby .
xcode 8.1 
appuium 1.6.1

**Comment by babusurendra** [comment]
@jlipps ,when i tried that driver.switchTo.alert() it throws error saying undefined method **undefined method `switchTo' for #<Selenium::WebDriver::Driver:0x2b94e88**

**Comment by babusurendra** [comment]
@jlipps , any expected date for appium 1.6 dmg ?
