### ISSUE TITLE
Convert WDA to a .ipa file & use it in the iPad/ iPhone devices

### ISSUE THREAD

**Issue by dilsreccse** [appium/appium#7250]
Right now i'm using Appium 1.6 & WDA to support iOS 10 iPad devices. As WDA needs developer ID verification, i did the same & working for me. But now my concern is, i need to verify my developer profile in the iPad devices intermittently, is that possible for me to convert  WDA to a .ipa file & use it. if yes could anyone help me doing it ?

**Comment by pavanbachu0604** [comment]
You need not convert the WDA to .ipa or an .app file. Just make you pass as Desired Capabilities through your code

**Comment by dilsreccse** [comment]
@pavanbachu0604 , previously when we used safari launcher to launch safari browser, we were able to convert the safari launcher xcode project to .ipa file & use it. i tried the same for WDA, unable to install the app on to the device. it just shows "installing" in itunes. @imurchie can we able to convert WDA to ipa file ?

**Comment by pavanbachu0604** [comment]
@dilsreccse You dont need to create a .ipa out of WDA when you run appium and  give xcodexonfig file as one of the capability then the WDA would be installed automatically into ur ipads

**Comment by dilsreccse** [comment]
@pavanbachu0604 : what is the capability that we need use can u give a sample ?

**Comment by pavanbachu0604** [comment]
@dilsreccse You need not give any spl capability for WDA specific , just use capabilities that you would use appium1.6

**Comment by jlipps** [comment]
There is no reason to convert WDA to an ipa file. Appium manages WDA for you.
