### ISSUE TITLE
[appium 1.6.0] Can't pull file from iOS simulator. Original error: Cannot read property 'getDir' of undefined

### ISSUE THREAD

**Issue by dsavchenkov** [appium/appium#7253]
## The problem
Can't pull file from iOS simulator. Original error: Cannot read property 'getDir' of undefined

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.1
* Node.js version (unless using Appium.app|exe): v7.1.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

Error on call driver.pull_file

## Link to Appium logs

https://gist.github.com/dsavchenkov/6d2694100b52f370ec95035efb4f0a79

## Code To Reproduce Issue [ Good To Have ]
self.driver.pull_file(path)

**Comment by dsavchenkov** [comment]
Any updates, guys? or maybe there is a workaround?

**Comment by jlipps** [comment]
Sorry for the delay @dsavchenkov. Can you add the _full_ appium logs to that gist? We need to see everything from the beginning of starting the appium server up to that error.

**Comment by dsavchenkov** [comment]
@jlipps , I updated an existing log file
https://gist.github.com/dsavchenkov/6d2694100b52f370ec95035efb4f0a79

**Comment by jlipps** [comment]
@dsavchenkov I mean everything starting from the moment you run the appium server. Everything starting with these lines:

```
[Appium] Welcome to Appium v1.6.3 (REV eb5cecc97014e4303648f57f84a1a4c7b27d8462)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

**Comment by imurchie** [comment]
This is a reproducible error. Pulling into the sprint.

**Comment by imurchie** [comment]
@dsavchenkov Yes, you can. Though the easiest way is to upgrade without shrinkwrap (`npm uninstall -g appium && npm install -g appium --no-shrinkwrap`), you can also just update the XCUITest module.

(1) Find out where Appium is installed.
(2) Go to where Appium is installed.
(3) run `npm install appium-xcuitest-driver`
(4) run `npm ls appium-xcuitest-driver`. It should now be version 2.5.1 (this will also be printed in the logs when you start a session in Appium.

**Comment by dsavchenkov** [comment]
@imurchie thank you
