### ISSUE TITLE
Building WebDriverAgent on to device errors out with No signing certificate when Crontab is used. XcodeBuild works fine when appium scripts are directly ran.

### ISSUE THREAD

**Issue by SatishKumarKV** [appium/appium#7254]
## The problem

Building WebDriverAgent on to device errors out with No signing certificate when Crontab is used. XcodeBuild works fine when appium scripts are directly ran.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Sierra
* Node.js version (unless using Appium.app|exe): Latest
* Mobile platform/version under test: 10
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

I am trying to schedule running of my Automation suite which has around 200 test scripts using TestNG.

Below is the command being used and is placed inside a PERL script which is being tried run from crontab 
java -cp /Users/Test/Automation/iOSAgent/LetsAutomate.jar:bin:ios:jars/*:/Users/Test/Automation/jars/testng-6.9.4.jar -DSuiteDisplayName=Upgrade3.01 -Dplatform=ios -DdeviceProfile=AutomationiOS6 -DconnectionHost=127.0.0.1 -DtoolName=appium -Dcustomer=M4_MDM -DrecipientList=\"xxx@xxx.com"  org.testng.TestNG  /Users/Test/Automation/iOSAgent/ios/Suites/Upgrade3.01.xml"

Above command ran from Terminal directly works fine without any issues. But when i use crontab i am getting below error while trying to build WebDriverAgent on to the device..

`[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=77e99161a0a6a65592ba0858e4b0c64a736027f0' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/Satish/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/181E00E5-DDC7-4A27-8ED4-24A2BFA26BAD/Session-WebDriverAgentRunner-2016-11-19_220613-SKPva9.log
[Xcode] 2016-11-19 22:06:14.705 xcodebuild[82004:663916] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/Satish/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/181E00E5-DDC7-4A27-8ED4-24A2BFA26BAD/Session-WebDriverAgentRunner-2016-11-19_220613-SKPva9.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/Satish/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/181E00E5-DDC7-4A27-8ED4-24A2BFA26BAD/Session-WebDriverAgentRunner-2016-11-19_220613-SKPva9.log}

[Xcode] 
Testing failed:
	No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "KNT489GST5" with a private key was found.
** TEST FAILED **

[Xcode] 
The following build commands failed:
	Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] xcodebuild failure warrants retry. Retrying...
[XCUITest] Shutting down WebDriverAgent
[XCUITest] System log exited with code 'null'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=77e99161a0a6a65592ba0858e4b0c64a736027f0' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/Satish/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/FA4E4EE1-499F-4DA5-8B4E-36F640847DE8/Session-WebDriverAgentRunner-2016-11-19_220616-8IzGhV.log
[Xcode] 2016-11-19 22:06:16.895 xcodebuild[82054:664130] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/Satish/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/FA4E4EE1-499F-4DA5-8B4E-36F640847DE8/Session-WebDriverAgentRunner-2016-11-19_220616-8IzGhV.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/Satish/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/FA4E4EE1-499F-4DA5-8B4E-36F640847DE8/Session-WebDriverAgentRunner-2016-11-19_220616-8IzGhV.log}

[Xcode] 

[Xcode] 
Testing failed:
	No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "KNT489GST5" with a private key was found.

[Xcode] ** TEST FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[XCUITest] Shutting down WebDriverAgent
[XCUITest] System log exited with code '0'
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
(node:81970) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Can't stop process; it's not currently running
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[HTTP] <-- POST /wd/hub/session 500 5998 ms - 167 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: xcodebuild failed with code 65 (WARNING: The server did not provide any stacktrace information)
`

Tried with sudo privileges too , but same error..
sudo crontab -u xxxx -e

**Comment by mykola-mokhnach** [comment]
Try to use _keychainPath_ and _keychainPassword_ capabilities.

**Comment by SatishKumarKV** [comment]
Thanks @mykola-mokhnach..
Moving the certs to the System keychain, and referencing it specifically fixed the issue
http://stackoverflow.com/questions/16550594/jenkins-xcode-build-works-codesign-fails

**Comment by SatishKumarKV** [comment]
Thanks , Closing issue.
