### ISSUE TITLE
Could not initialize ideviceinstaller

### ISSUE THREAD

**Issue by albka1986** [appium/appium#7256]
**## The problem**

Could Not Launch Appium Inspector.
I receive the error: 
_"Could not start a new session
Be sure the Appium server is running with an application opened by using the "App Path" parameter in Appium.app (along with package and activity for Android) or by connecting with selenium client and supplying this in the desired capabilities object."_

**## Environment**

* Appium version: 1.6;
* Appium client: 1.5.3 (Ara);
* OS version: MAC OS X El Capitan;
* Simulator -  iPhone 5s, iOS 9.3;

## Link to Appium logs

[Appium logs](https://gist.github.com/albka1986/85b66086228dadbf4b7258c59ec1e14c)

## Settings in Appium
[Screenshot](http://prntscr.com/dab7x0)

**Comment by jlipps** [comment]
Is ideviceinstaller installed and working on your system?

**Comment by albka1986** [comment]
@jlipps  
Ideviceinstaller is installed, but i don't know it is work or no?! How can I check it? 
I ran my app file on emulator - it is all ok. But inspector doesn't want to run.

`iMac-admin-3:~ oleh$ ideviceinstaller
ERROR: No mode/operation was supplied.
Usage: ideviceinstaller OPTIONS
Manage apps on iOS devices.

  -u, --udid UDID	Target specific device by its 40-digit device UDID.
  -l, --list-apps	List apps, possible options:
       -o list_user	- list user apps only (this is the default)
       -o list_system	- list system apps only
       -o list_all	- list all types of apps
       -o xml		- print full output as xml plist
  -i, --install ARCHIVE	Install app from package file specified by ARCHIVE.
                       	ARCHIVE can also be a .ipcc file for carrier bundles.
  -U, --uninstall APPID	Uninstall app specified by APPID.
  -g, --upgrade ARCHIVE	Upgrade app from package file specified by ARCHIVE.
  -L, --list-archives	List archived applications, possible options:
       -o xml		- print full output as xml plist
  -a, --archive APPID	Archive app specified by APPID, possible options:
       -o uninstall	- uninstall the package after making an archive
       -o app_only	- archive application data only
       -o docs_only	- archive documents (user data) only
       -o copy=PATH	- copy the app archive to directory PATH when done
       -o remove	- only valid when copy=PATH is used: remove after copy
  -r, --restore APPID	Restore archived app specified by APPID
  -R, --remove-archive APPID  Remove app archive specified by APPID
  -o, --options		Pass additional options to the specified command.
  -h, --help		prints usage information
  -d, --debug		enable communication debugging`

**Comment by cgoldberg** [comment]
@albka1986 ,
plug in a device and run `$ ideviceinstaller -l`.

Note: it looks like the stable branch (1.1.0) from homebrew is currently borked for devices running iOS 10:

```
$ brew list --versions ideviceinstaller
ideviceinstaller 1.1.0_2
$ ideviceinstaller -l
Could not connect to lockdownd. Exiting.
```

**Comment by imurchie** [comment]
You can install the latest with `brew install -v --HEAD ideviceinstaller`.

**Comment by albka1986** [comment]
@imurchie 

I've the version of ideviceinstaller 1.1.0_2.

```
iMac-admin-3:~ oleh$ brew list --versions ideviceinstaller
ideviceinstaller 1.1.0_2
iMac-admin-3:~ oleh$ ideviceinstaller -l
No iOS device found, is it plugged in?

```

**Comment by albka1986** [comment]
@cgoldberg 
I plugged a device. And this is what system says:

```
iMac-admin-3:~ oleh$ ideviceinstaller -l
No iOS device found, is it plugged in?

```

**Comment by imurchie** [comment]
Latest `ideviceinstaller` ought to fix this.

**Comment by XPCD** [comment]
Using " /bin/sh -c ideviceinstaller" says "ERROR: No mode/command was supplied." but the direct "ideviceinstaller" command works fine. ideviceinstaller version is "HEAD-442f670_2"
