### ISSUE TITLE
XCUITest stuck with message : Waiting for WebDriverAgent server to finish loading

### ISSUE THREAD

**Issue by SatishKumarKV** [appium/appium#7257]
## The problem

XCUITest stuck with message : Waiting for WebDriverAgent server to finish loading

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6
* Last Appium version that did not exhibit the issue (if applicable):  #1.5.3
* Desktop OS/version used to run Appium: EL Capita
* Node.js version (unless using Appium.app|exe): Latest
* Mobile platform/version under test: 10.0
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

WebDriverAgent seems to be running fine on the device ( Have checked Xcode build logs ) but after that i am seeing msg **Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB** and stuck.
Nothing happening on the device.

## Link to Appium logs
`[debug] [WebDriverAgent] Device: Nov 21 17:36:40 shabreens-iPhone XCTRunner[782] <Notice>: Running tests...
[debug] [WebDriverAgent] Device: Nov 21 17:36:41 shabreens-iPhone XCTRunner[782] <Notice>: Continuing to run tests in the background with task ID 1
[XCUITest] Detected that WebDriverAgent is running at url 'http://10.104.150.75:8100'
[XCUITest] WebDriverAgent started at url 'http://10.104.150.75:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.`

**Comment by Krops** [comment]
Same issue
[debug] [XCUITest] App installed.
[XCUITest] Using default agent: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
[XCUITest] Using default bootstrap: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=018d516781c346aae155a85861be00cef4eacada' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[XCUITest] xcodebuild exited with code '70' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Full reset requested. Will try to uninstall the app 'com.comcast.labs.PersonalMedia'.
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] app uninstall stdout : [....] Waiting for iOS device to be connected
[....] Using iPhone 6 (GSM) 'User’s iPhone' (018d516781c346aae155a85861be00cef4eacada).
------ Uninstall phase ------
[ OK ] Uninstalled package with bundle id com.comcast.labs.PersonalMedia

[debug] [XCUITest] Removed 'com.comcast.labs.PersonalMedia'
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (lib/webdriveragent.js:294:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (lib/teen_process.js:191:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[HTTP] <-- POST /wd/hub/session 500 161219 ms - 167 
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...

**Comment by Rdexmah** [comment]
Hey you got any resolution
 , I am also facing same issue.

**Comment by jlipps** [comment]
Appium 1.6.3 was just released with several fixes, please give it a try

**Comment by mysteryit** [comment]
I am using appium 1.6.3, the issue still happen:

[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/qa-apple/Library/Developer/Xcode/DerivedData/UICatalog-fimnbmfovdxmibgbjsbrmyhqmshf/Build/Products/Debug-iphoneos/UICatalog.app'
[Appium]   noReset: true
[Appium]   newCommandTimeout: 900
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   platformVersion: '10.1'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'com.example.apple-samplecode.UICatalog'
[Appium]   platformName: 'iOS'
[Appium]   udid: '769650378b3bad03061677c30bc900e6b146ad8b'
[Appium]   deviceName: 'Mon'
[Appium]   autoAcceptAlerts: true
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] Session created with session id: b43fb95a-0a15-47f0-b0ab-0bd2ee1a5e59
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [XCUITest] Available devices: 769650378b3bad03061677c30bc900e6b146ad8b
[debug] [XCUITest] Creating iDevice object with udid 769650378b3bad03061677c30bc900e6b146ad8b
[XCUITest] Determining device to run tests on: udid: '769650378b3bad03061677c30bc900e6b146ad8b', real device: true
[BaseDriver] Using local app '/Users/qa-apple/Library/Developer/Xcode/DerivedData/UICatalog-fimnbmfovdxmibgbjsbrmyhqmshf/Build/Products/Debug-iphoneos/UICatalog.app'
[debug] [XCUITest] Checking whether app '/Users/qa-apple/Library/Developer/Xcode/DerivedData/UICatalog-fimnbmfovdxmibgbjsbrmyhqmshf/Build/Products/Debug-iphoneos/UICatalog.app' is actually present
[debug] [XCUITest] App is present
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] Error checking install status: Command 'ios-deploy --exists --id 769650378b3bad03061677c30bc900e6b146ad8b --bundle_id com.example.apple-samplecode.UICatalog' exited with code 255
[debug] [XCUITest] App is not installed. Will try to install.
[debug] [XCUITest] App installed successfully.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=769650378b3bad03061677c30bc900e6b146ad8b -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/qa-apple/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/A18D06D1-E494-4C7D-8B69-E5AB14951472/Session-WebDriverAgentRunner-2016-12-15_104807-m0vkZh.log
[Xcode] 2016-12-15 10:48:11.526 xcodebuild[3019:96834]  DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.WebDriverAgentRunner-Runner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x000000010f70537b DTDKCreateNSError + 113
	1   DTDeviceKitBase                     0x000000010f705ab9 DTDK_AMDErrorToNSError + 791
	2   DTDeviceKitBase                     0x000000010f7172a5 __70-[DTDKRemoteDeviceConnection startHouseArrestServiceForAppIdentifier:]_block_invoke + 100
	3   DTDeviceKitBase                     0x000000010f716181 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_4 + 22
	4   DTDeviceKitBase                     0x000000010f7082c7 __DTDKExecuteInSession_block_invoke + 38
	5   DTDeviceKitBase                     0x000000010f7078f0 __DTDKExecuteWithConnection_block_invoke_2 + 477
	6   DTDeviceKitBase                     0x000000010f7076ec __DTDKExecuteWithConnection_block_invoke + 107
	7   libdispatch.dylib                   0x00007fff9996940b _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x00007fff9996a9f2 _dispatch_barrier_sync_f_invoke + 74
	9   DVTFoundation                       0x0000000106b1998b DVTDispatchBarrierSync + 206
	10  DVTFoundation                       0x0000000106af6337 -[DVTDispatchLock performLockedBlock:] + 116
	11  DTDeviceKitBase                     0x000000010f7075f6 DTDKExecuteWithConnection + 223
	12  DTDeviceKitBase                     0x000000010f708251 DTDKExecuteInSession + 121
	13  DTDeviceKitBase                     0x000000010f7160b8 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 117
	14  DVTFoundation                       0x0000000106b18ce7 __DVTDispatchAsync_block_invoke + 827
	15  libdispatch.dylib                   0x00007fff9997493d _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x00007fff9996940b _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x00007fff9997bbd7 _dispatch_async_redirect_invoke + 1733
	18  libdispatch.dylib                   0x00007fff9996940b _dispatch_client_callout + 8
	19  libdispatch.dylib                   0x00007fff9996d29b _dispatch_root_queue_drain + 1890
	20  libdispatch.dylib                   0x00007fff9996cb00 _dispatch_worker_thread3 + 91
	21  libsystem_pthread.dylib             0x00007fff94b2b4de _pthread_wqthread + 1129
	22  libsystem_pthread.dylib             0x00007fff94b29341 start_wqthread + 13
), NSLocalizedRecoverySuggestion=Too many instances of this service are already running., NSLocalizedDescription=Too many instances of this service are already running.}]

[debug] [WebDriverAgent] Device: Dec 15 10:48:37 Mon XCTRunner[317] <Notice>: Running tests...
[debug] [WebDriverAgent] Device: Dec 15 10:48:37 Mon XCTRunner[317] <Notice>: Unable to load configuration data from specified path /var/folders/_q/p70gtp790877x727mndzq_q00000gn/T/com.apple.dt.XCTest/E8198AD9-4EE8-4E28-A55E-E05608CC93FD/remote-container/tmp/WebDriverAgentRunner-E8198AD9-4EE8-4E28-A55E-E05608CC93FD.xctestconfiguration; error: The file doesn\M-b\M^@\M^Yt exist.
[debug] [WebDriverAgent] Device: Dec 15 10:48:37 Mon XCTRunner[317] <Notice>: Looking for test bundles in /var/containers/Bundle/Application/051595DF-9049-4C01-9EE3-E4B1370D069C/WebDriverAgentRunner-Runner.app/PlugIns
[debug] [WebDriverAgent] Device: Dec 15 10:48:37 Mon XCTRunner[317] <Notice>: Found test bundle at /var/containers/Bundle/Application/051595DF-9049-4C01-9EE3-E4B1370D069C/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
[debug] [WebDriverAgent] Device: Dec 15 10:48:37 Mon XCTRunner[317] <Notice>: Looking for configurations in /var/containers/Bundle/Application/051595DF-9049-4C01-9EE3-E4B1370D069C/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
[debug] [WebDriverAgent] Device: Dec 15 10:48:37 Mon XCTRunner[317] <Notice>: No configurations found, creating a default configuration that will run all tests.
[HTTP] <-- POST /wd/hub/session - - ms - - 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/qa-apple/Library/Developer/Xcode/DerivedData/UICatalog-fimnbmfovdxmibgbjsbrmyhqmshf/Build/Products/Debug-iphoneos/UICatalog.app","noReset":true,"newCommandTimeout":900,"realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"10.1","automationName":"XCUITest","bundleId":"com.example.apple-samplecode.UICatalog","platformName":"iOS","udid":"769650378b3bad03061677c30bc900e6b146ad8b","deviceName":"Mon","autoAcceptAlerts":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/qa-apple/Library/Developer/Xcode/DerivedData/UICatalog-fimnbmfovdxmibgbjsbrmyhqmshf/Build/Products/Debug-iphoneos/UICatalog.app","noReset":true,"newCommandTimeout":900,"realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"10.1","automationName":"XCUITest","bundleId":"com.example.apple-samplecode.UICatalog","platformName":"iOS","udid":"769650378b3bad03061677c30bc900e6b146ad8b","deviceName":"Mon","autoAcceptAlerts":true},null,null,null,null,null,null]
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...

**Comment by geasscode** [comment]
I'm face this issue too.

**Comment by rockyav** [comment]
I'm faced this issue with appium v1.6.2.
But it's working when I downgrade appium to version: 1.6.0-beta3

**Comment by dr12782** [comment]
I am seeing this issue too on v1.6.3, iOS 10.2.

**Comment by wangtao169447** [comment]
I am seeing this issue too on v1.6.3, iOS 9.3.5 iOS 10.1.1 and so on

**Comment by RamanaK** [comment]
i see the same issue with appium 1.6.3, xcode 8.2 and iOS 10.2

**Comment by wangtao169447** [comment]
@RamanaK @dr12782 @rockyav @geasscode 
you can try it with updated appium-xcuitest-driver component. Set its version to 2.5.1/2.5.0

good luck!

**Comment by jlipps** [comment]
@imurchie when did our server discovery logic get updated? Was it post-1.6.3?

**Comment by SrinivasanTarget** [comment]
No more an issue now.

**Comment by sherknil** [comment]
@imurchie I have started facing this issue with my old set up Appium v1.6.0beta3.
Below is link for log details.

https://gist.github.com/anonymous/434d7793a6bdf0d89827b5135a9e870f
can you please help me here?

**Comment by imurchie** [comment]
My main help would be to suggest you upgrade. Appium 1.6.0-beta3 was released more than a year ago (on Oct 4, 2016).

**Comment by sherknil** [comment]
@imurchie Yes. I can upgrade to latest version. But same setup was up and and running previously and why we are getting this issue now. Is it only because we are using older version of Appium?

**Comment by imurchie** [comment]
I have no idea why it is not working at the moment. But a lot of work has gone into making it more stable and reliable, and upgrading would get access to that.
