### ISSUE TITLE
Running appium and webkit programmatically using java 

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#7258]
As a part of job requirement I need to run the Appium server and Webkit for multiple devices using java instead of running it from Terminal. I had created a shell script for running them and tried to invoke through Java , even that is failing.

Any suggestions are welcomed.

**Comment by jlipps** [comment]
Hi @pavanbachu0604, we'll need more information to help. What exactly are you trying to do? What's not working?

**Comment by pavanbachu0604** [comment]
I wanted to invoke Appium Server and ios webkit debug proxy from Java Code

**Comment by RandyPfohlL11** [comment]
This does not sound like an issue. What is the issue exactly?

**Comment by jlipps** [comment]
This issue tracker is not for how-tos, but for tracking defects with the appium server. A few seconds of searching got me this, which looks relevant: https://discuss.appium.io/t/launching-and-stopping-appium-server-programmtically/700. Hope it helps! The discussion forum is a better place to get help with pattern questions like this. thanks!
