### ISSUE TITLE
Appium Fail: The target application appears to have died

### ISSUE THREAD

**Issue by QASpruha** [appium/appium#7259]
## Problem

Hi,
I am testing iOS app on real device (iPad mini) and i am getting this same issue after clicking an element application gets crashed/closed. Even if i try launching the app through appium and clicking the element manually then also Application gets closed
Appium logs showing error : Fail: The target application appears to have died

Tried on different iPad devices including ipad 2 and ipad mini but same issue occurs.
Please help me to resolve the issue ASAP

TIA
Spruha

## Environment

*Appium Version: 1.5.3
*iSO version : 9.3.2 
* Node.js version: 3.3.12
* Real device: iPad 2 and iPad mini 

Appium Logs:

MJSONWP] Calling AppiumDriver.click() with args: ["0","0ea38673-e186-48f9-83...
[debug] [iOS] Executing iOS command 'click'
[debug] [UIAuto] Sending command to instruments: au.tapById('0')
[debug] [Instruments] [INST] 2016-11-21 17:04:32 +0000 Debug: Got new command 6 from instruments: au.tapById('0')
[debug] [Instruments] [INST] 2016-11-21 17:04:32 +0000 Debug: evaluating au.tapById('0')
[debug] [Instruments] [INST] 2016-11-21 17:04:32 +0000 Debug: target.frontMostApp().elements()[3].elements()[3].tap()
[debug] [Instruments] [INST] 2016-11-21 17:04:32 +0000 Debug: evaluation finished
[debug] [Instruments] [INST] 2016-11-21 17:04:32 +0000 Debug: responding with:
[debug] [Instruments] [INST] 2016-11-21 17:04:32 +0000 Debug: Running system command #7: /usr/local/Cellar/node/5.3.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/y8/6q9509dj4333sr4wh2dfmpzxs0tx4m/T/instruments_sock 2,{"status":0,"value":""}...
[debug] [UIAuto] Socket data received (25 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
[MJSONWP] Responding to client with driver.click() result: null
[HTTP] <-- POST /wd/hub/session/0ea38673-e186-48f9-834d-32e740586dec/element/0/click 200 523 ms - 76 
[debug] [Instruments] [INST] 2016-11-21 17:04:31 +0000 Fail: The target application appears to have died
[debug] [Instruments] [INST STDERR] 2016-11-21 12:04:31.870 instruments[63357:603999] Attempting to change event horizon while disengage
[debug] [Instruments] [INST] Instruments Trace Complete (Duration : 198.846130s; Output : /var/folders/y8/6q9509dj4333sr4wh2dfmpzxs0tx4m/T/appium-instruments/instrumentscli0.trace)
[debug] [Instruments] Instruments exited with code 0
[debug] [iOS] Deleting ios session
[debug] [UIAuto] Destroying instruments client socket.
[debug] [UIAuto] Closing socket server.
[Appium] Closing session, cause was 'An unknown server-side error occurred while processing the command. Original error: Abnormal Instruments termination!'
[Appium] Removing session 0ea38673-e186-48f9-834d-32e740586dec from our master session list
[debug] [UIAuto] Instruments socket server was closed
[debug] [iOSLog] Stopping iOS log capture

**Comment by jlipps** [comment]
This means your app crashed. Appium is not causing the crash. I would check the simulator logs to see what error could have occurred.

**Comment by QASpruha** [comment]
@jlipps Thank you for quick response.
 I am using real device. And application is working good if I operate it manually. But if I launch it using Appium, at only one particular page it gets crashed. Even if I launch application through Appium and Click that element Manually then also the same issue persist.
I will try executing the same app with simulator and give my feedback

**Comment by jlipps** [comment]
@QASpruha to prove whether it is related to Appium or not, you'd need to launch the app using instruments and the UIAutomation instrument. If it exhibits the crashing behavior there, we've proved that Appium is not the issue.

Also, as I mentioned, viewing the device log would also be a good place to look for any errors which might have crashed the app.
