### ISSUE TITLE
No multi-touch API?

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/appium#7261]
## The problem

I'm trying to perform a pinch in Appium 1.6.1 beta, and am being told that's not possible.

```
left = Appium::TouchAction.new.press(x: center_x - 50, y: center_y).wait(1500).move_to(x: percentage / 2, y: -1).wait(1500).release
right = Appium::TouchAction.new.press(x: center_x + 50, y: center_y).wait(1500).move_to(x: -percentage / 2, y: 1).wait(1500).release
pinch = Appium::MultiTouch.new
pinch.add left
pinch.add right
pinch.perform
```

Output is
`
Selenium::WebDriver::Error::UnknownError: Support for multi-action API is not yet implemented. Please contact an Appium dev.
`

Appium output: https://gist.github.com/VivaLosDoyers/5cd534e9b382e6a73047b306b329ebfc

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1 beta 1 with XCUITest 2.0.37
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3 with UIAutomation
* Desktop OS/version used to run Appium: OS X 10.12.1
* Node.js version (unless using Appium.app|exe): 7.0.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: sim
* Appium CLI or Appium.app|exe: CLI

**Comment by jlipps** [comment]
That's right, Apple decided not to include, as far as we can tell, any kind of generalized gesture automation in XCUITest. Follow https://github.com/appium/appium/issues/6762 for our investigations.

**Comment by imurchie** [comment]
This is also relevant: https://github.com/appium/appium-xcuitest-driver/pull/302
