### ISSUE TITLE
When the page source is huge, appium’s element finding strategy is too slow.

### ISSUE THREAD

**Issue by Prakash-Saravanan** [appium/appium#7264]
## The problem

When the page source goes on increasing, the time taken by appium to find the elements gets increased

## Environment

* Appium version 1.5.3
* Desktop OS/version used to run Appium: MacOS 10.12.1 
* Mobile platform/version under test: iOS 9.3.5
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: both

**Comment by mykola-mokhnach** [comment]
It's rather underlying technology problem (which is Apple In your case), than Appium issue.

**Comment by vikramvi** [comment]
@Prakash-Saravanan can you please try same scenario with latest appium version which has support for XCUITest ?

**Comment by amedvedjev** [comment]
confirming same slowness with large iOS pages. but this was always. with XCTest the same...

**Comment by jlipps** [comment]
@mykola-mokhnach doesn't seem like there's any way for us to improve this right? other than adding a feature request for apple to give us a hierarchy dump more quickly?

**Comment by mykola-mokhnach** [comment]
@jlipps Probably, there is something, that we don't know about. But I neither work for Apple, nor is an expert in reverse engineering. So, yeah, let's hope that sometimes a miracle happens and The Corporation will pay attention to other things except of making money :)

**Comment by Prakash-Saravanan** [comment]
So far able to use driver.getPageSource() to get the page source as XML tree. Using the page source string with org.w3c.dom API, able to read the element's attribute values such as name, location and size. But cannot perform any actions on those elements as it takes more time (~5 minutes).

Hence I thought this would be an issue from Appium side.

**Comment by Prakash-Saravanan** [comment]
@vikramvi Have not tried it with XCUITest as the migration process needs an ample amount of time :-(
