### ISSUE TITLE
Encountered internal error running command: Error: iproxy exited with code '208'

### ISSUE THREAD

**Issue by shay777** [appium/appium#7265]
## The problem

I would like to run a test in a loop (that it continue to run all the time). I am using    @Test(invocationCount = 3) in intellij in order to achieve it.
The issue is that in ios the test runs only one time and after it finished, the test suppose to run again but the app not started. I can see the web driver agent starting and then the app trying to start but fails.
Is this a process issue?
thanks

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac os sierra
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: ios 10
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe:

## Link to Appium logs

https://gist.github.com/shay777/1042e6b85f68f5e2c93b5dd7b1ff6942

**Comment by imurchie** [comment]
Can you update Appium (`npm uninstall -g appium && npm install -g appium@beta`)? There has been some progress in this I think.

**Comment by shay777** [comment]
@imurchie  updating Appium indeed solved the issue.
Thanks
