### ISSUE TITLE
Appium starts up app on one device, tries to finish test on another

### ISSUE THREAD

**Issue by jfrazier-apteligent** [appium/appium#7268]
## The problem

Hello,
I am running a small device farm and have run into a few issues while using Appium. The most vexing of which is as follows:
Context: There are two Samsung phones on this device farm, a Galaxy S6 and a Galaxy S5. While their adb IDs are very different, their model numbers are virtually identical (SM-G920V and SM-G900V, respectively)and they are on the same OS (6.0.1). 

The result:
Appium server starts up, and my test logic picks a device at random from test config. When the Galaxy S6 is selected, the test app boots up on the S6 AND the S5. The tests then try to run on the Galaxy S5, instead of the actual target, which is the S6. The tests then fail on the S6 because button presses and app navigation are occurring on the S5 for some reason, and the S6 cannot locate elements because it never navigated past the main launch screen for the app. My suspicion is that the appium server is targeting devices based on more than just adb ID and is somehow sending commands to the wrong device, but I am not certain.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OSX 10.11.6
* Node.js version (unless using Appium.app|exe): 6.3.1
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium server started programmatically using CLI args.

## Link to Appium logs

There are no logs to speak of. At least, not any relevant to the issue at hand. Everything in the logs simply looks normal. Let me know if there is anything I can do on my end to help debug.

**Comment by mykola-mokhnach** [comment]
do you use selenium grid to run your tests? If yes then try 1.6.1beta, where some bugs have been fixed.

**Comment by jfrazier-apteligent** [comment]
hello @mykola-mokhnach -
I am not using Selenium Grid. I will try updating to the beta when I am back in the office from the holiday.

Out of curiosity: How is appium targeting the devices, and how could it cause an issue like this one? If I know where the code is, I can take a look and see about resolving the issue myself.

Thanks for your time,
-Josh

**Comment by mykola-mokhnach** [comment]
It's hard to guess anything without logs and code listings. In general, Appium creates a session with unique ID when you create AndroidDriver instance in your code and proxies all the commands to the selected listener on the corresponding device (UIAutomation by default, there are also other supported backends, like Selendroid or UIA2). You can debug the stuff by adding more logs into the corresponding node module (on OSX these are normally stored under /usr/local/lib/node_modules/appium/node_modules/). Just locate the _lib_ subfolder of the corresponding module, add the necessary changes to the corresponding source file and execute 

```
gulp transpile
```

to invoke transpilation and update cached binaries (you'll need to install several other additional modules, like _gulp_ itself and _appium-gulp-plugins_ to make it).

**Comment by jfrazier-apteligent** [comment]
Thanks. I'll try adding additional logs to suss out the problem.

How are those IDs created? Are they based on the device's information?  Just trying to figure out how one device could receive commands intended for another if there is a unique ID involved.

**Comment by vikramvi** [comment]
@jfrazier-apteligent can you share sample project so it'll be easier to reproduce issue ?
