### ISSUE TITLE
Lost ID when using XCUITest with appium 1.6 beta3 in IOS

### ISSUE THREAD

**Issue by xinhuadian** [appium/appium#7272]
## The problem

Lost ID when using XCUITest with appium 1.6 beta3 in IOS.
My app is a hybrid app running on iOS device.  The input filed WITH ID can’t be find after running in the appium. Then I use getPageSource, find the matched XCUIElementTypeTextField lost name or ID. So findElementByID doesn’t work.

## Environment

* Appium version (or git revision) that exhibits the issue:
1.6.0 beta 3
* Last Appium version that did not exhibit the issue (if applicable):
This issue happen on IOS XCUITest with IOS 10.1  .   Not happen on Instrument with IOS 9.3
* Desktop OS/version used to run Appium:
Mac 10.11.6
* Mobile platform/version under test:
Ipad air simulator,  IOS 10.1
* Real device or emulator/simulator:
simulator
* Appium CLI or Appium.app|exe:
Appium CLI

## Details

The source code of html is 
`<div class="editbox">
          <label class="left" for="username">username</label>
            <input class="right" type="text" id="username" sup_html_type="text"  sup_max_length="32767" sup_num_of_decimals="0" credential="username"/><span style="display:block" id="activation_username_help" class="help"></span>
          </div>`

The code I see from getPageSouce is 

` <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0/0/0/0/0/0/0/0/1/0" x="15" y="88" width="738" height="40">
           <XCUIElementTypeOther name="username" label="username" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0/0/0/0/0/0/0/0/1/0/0" x="15" y="88" width="244" height="22">
              <XCUIElementTypeStaticText name="username" label="username" value="username" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0/0/0/0/0/0/0/0/1/0/0/0" x="15" y="89" width="72" height="20">
               </XCUIElementTypeStaticText>
                </XCUIElementTypeOther>
         <XCUIElementTypeTextField name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0/0/0/0/0/0/0/0/1/0/1" x="262" y="90" width="459" height="37”>
          </XCUIElementTypeTextField>`
 </XCUIElementTypeOther>

**Comment by dpgraham** [comment]
The call to 'getPageSource' is being called from the native IOS app context. What you need to do is to switch contexts to the WebView and then calling 'getPageSource' will show you the HTML. 

(see https://github.com/appium/appium-base-driver/blob/master/docs/mjsonwp/protocol-methods.md for information about contexts)

If that doesn't work then let me know and I can re-open the ticket.
