### ISSUE TITLE
XCUITest/WebDriverAgentRunner - getaddrinfo ENOTFOUND localhost localhost:8100

### ISSUE THREAD

**Issue by TusharRastogi** [appium/appium#7273]
## The problem

I am facing some proxyRequest Error:

> ProxyRequestError: Could not proxy command to remote server. Original error: Error: getaddrinfo ENOTFOUND localhost localhost:8100

I got this issue while automating my app on iOS 10. I have setup all the dependencies and WebDriverAgent successfully.

It just happens that WebDriverAgentRunner launches on my device (iPhone 6) and after that this error appears.

## Environment

* Appium version - 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: MAC OS X 10.11 El Capitan
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS 10.0.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

**Versions:**
Node - v6.9.1
npm - 3.10.8
appium - 1.6.0

**Starting appium server**
appium -p 4725 --session-override

**Server Caps:**
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("platformVersion", "10.0.2");
capabilities.setCapability("deviceName", "iPhone");
capabilities.setCapability("newCommandTimeout", 100000);
capabilities.setCapability("unicodeKeyboard", true);
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("sendKeyStrategy", "setValue");
capabilities.setCapability("showXcodeLog", true);
capabilities.setCapability("udid", pro.getProperty("udid"));
capabilities.setCapability("app", "/Users/magic/Desktop/Appium/myApp.ipa");
wd = new IOSDriver<MobileElement>(new URL("http://0.0.0.0:4725/wd/hub"), capabilities);
 
## Link to Appium logs

[Appium Logs](https://gist.github.com/TusharRastogi/59d2cc9dff3f6d9bc0dcdbb36cca0cc9)

## Code To Reproduce Issue [ Good To Have ]
NA

**Comment by mykola-mokhnach** [comment]
getaddrinfo ENOTFOUND means the client was not able to connect to given address. Why do you set 0.0.0.0 as server address?

**Comment by TusharRastogi** [comment]
Because Appium server is running at that address!!! See [gists](https://gist.github.com/TusharRastogi/59d2cc9dff3f6d9bc0dcdbb36cca0cc9) for more info.

**Comment by TusharRastogi** [comment]
I'm facing this issue in v1.6.1 as well.
See [gist](https://gist.github.com/TusharRastogi/346acd71c38c3688cd2398fee0c10305)
I know the logs are quiet long but what I can see other than ENOTFOUND is `[Xcode] The file “ProjectSettings.xcconfig” couldn’t be opened because there is no such file. (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig)`
Please help!! Am I missing some configuration?
@imurchie @SrinivasanTarget @priyankshah217

**Comment by jlipps** [comment]
> [XCUITest] Detected that WebDriverAgent is running at url 'http://10.11.8.17:8100'

I'm confused why WDA would be running on that host. That doesn't seem like `localhost` now does it?

**Comment by TusharRastogi** [comment]
@jlipps 
`10.11.8.17` is the real device(iPhone's) IP address and `8100 `here is the default port for WDA. I think WDA is running on the real device but not sure why is it redirecting to `localhost`.
Is this expected?
`[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB`

**Comment by mykola-mokhnach** [comment]
@TusharRastogi yes, this is how WDA works. In case the connected real device is in the same WiFi network as the host machine then real phone's IP address is going to be used otherwise _localhost_ is used, since all the commands will be proxied via local USB connection.

**Comment by MuhammadAziz** [comment]
Hi I'm facing the same issue in v1.6.1
device: ios simulator
xcode: 8.0
target sdk: 10.0
172.19.16.119 is my Mac IP
See [gist](https://gist.github.com/MuhammadAziz/65f55f624bbb9d9fd09af0cd9b8803ed)
After my test is failed, I'm able to access http://localhost:8100/ through my browser. Here the response
`{
  "sessionId" : "9735E50B-F277-460C-8222-C6950F13ED2C",
  "value" : "Unhandled endpoint: \/ -- http:\/\/localhost:8100\/ with parameters {\n    wildcards =     (\n        \"\"\n    );\n}",
  "status" : 1
}`
Please advise!

**Comment by TusharRastogi** [comment]
@jlipps, @mykola-mokhnach 

I have update appium to v1.6.3 and I am still facing this issue.

Also while I run:

`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test`

I get something I like this

> 2017-01-10 13:55:39.821694 XCTRunner[282:34627] Running tests...
2017-01-10 13:55:41.362400 XCTRunner[282:34627] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2017-01-10 13:55:42.578
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-01-10 13:55:42.584
Test Suite 'UITestingUITests' started at 2017-01-10 13:55:42.589
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.01s     Start Test at 2017-01-10 13:55:42.596
    t =     0.02s     Set Up
2017-01-10 13:55:42.619678 XCTRunner[282:34627] Built at Jan 10 2017 13:49:52
2017-01-10 13:55:42.730716 XCTRunner[282:34627] ServerURLHere->http://10.11.8.17:8100<-ServerURLHere
2017-01-10 13:55:42.733805 XCTRunner[282:34627] Listening on USB

??

**Comment by mykola-mokhnach** [comment]
@TusharRastogi Try Appium with most recent components:

```
npm uninstall -g appium && npm install -g appium --no-shrinkwrap
```

**Comment by TusharRastogi** [comment]
Thanks @mykola-mokhnach for replying, I tried running again and I get [this](https://gist.github.com/TusharRastogi/03e2123ed1345901c540af32cf8835f8).


I really don't understand what/why is this:

> [debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB

**Comment by mykola-mokhnach** [comment]
Try to restart your device

**Comment by TusharRastogi** [comment]
@mykola-mokhnach @jlipps 

Still same **ENOTFOUND** issue see [gist](https://gist.github.com/TusharRastogi/170f8a8a7f207776c2ba6affa0ada1d1l).


Here is my script :
```
public class Tester 
{
	static IOSDriver<MobileElement> wd;
	public static void main(String[] args) throws FileNotFoundException, IOException, InterruptedException 
	{
		Properties pro = new Properties();
		pro.load(new FileInputStream("./Inputs/App.properties"));
		DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.0.2");
		capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.6.3");
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPad 48");
		capabilities.setCapability(MobileCapabilityType.UDID, pro.getProperty("udid"));		
		capabilities.setCapability(MobileCapabilityType.APP, "/Users/magic/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app");
		wd = new IOSDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
		wd.manage().timeouts().implicitlyWait(90, TimeUnit.SECONDS);
		wd.findElementByName("Attributes").click();
	}
}
```

Both Integration and WebDriverAgent Runner apps **_are installing_** on my device but only WDA Runner launches than closes...

Also is it possible that this issue is due to my host machine and real device being in same network?

I have checked some other logs in some other threads but I never found this:

> [debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB

**Comment by TusharRastogi** [comment]
I found similar issue (#4642) for appium v1.3 related to ios-webkit-debug(i guess) but it has no resolution to it.

Could it be related to Mac OSX version, mine is 10.11.6.

**Comment by mykola-mokhnach** [comment]
do you see any errors in real device log when you try to start WDA?

**Comment by TusharRastogi** [comment]
I don't this so!
This is complete log(incl. device logs) for one session.

**Comment by imurchie** [comment]
That log line about proxying ports has been on _every_ real device test for months.

The issue is here:
```
[Xcode] 2017-01-10 17:41:44.469 xcodebuild[1858:18285]  DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.WebDriverAgentRunner-Runner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., com.apple.dtdevicekit.stacktrace=(
```

Can you try adding the capability `useNewWDA` set to `true`.

**Comment by TusharRastogi** [comment]
@imurchie 
Tried with `capabilities.setCapability("useNewWDA", true)` but still same issue ENOTFOUND.

Here are session logs [with](https://gist.githubusercontent.com/TusharRastogi/b3033aa92198023c440a31e45f7e0877/raw/51f4092d90aa35b5c5c3e14860e79cea6b7e830f/Device_Logs_1) device-logs & [without](https://gist.github.com/TusharRastogi/b99aa0b75de2288f8641a510194f744d) device-logs.

**Comment by xaph** [comment]
any update on this issue? 

I'm facing the same issue with osx 10.11.6

What if I upgrade my osx to sierra? Anybody got a clue about this issue related to osx version or not?

**Comment by thanksdanny** [comment]
i faceing the same issue ,too.

`[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
 [debug] [XCUITest] Log file for xcodebuild test: /Users/thanksdanny/Library/Developer/Xcode/DerivedData/WebDriverAgent-aglwdgpknbtvkxddxdjubmhlahqx/Logs/Test/63A1F57E-605E-48B0-BA5E-587560048CEC/Session-WebDriverAgentRunner-2017-01-24_212914-1cnJXf.log
 [debug] [XCUITest] Unable to connect to running WebDriverAgent: Error: getaddrinfo ENOTFOUND localhost localhost:8100
 [XCUITest] Getting status of WebDriverAgent on device timed out. Continuing
 [debug] [XCUITest] Sending createSession command to WDA
 [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://0.0.0.0:4723/welcome"],"shouldWaitForQuiescence":true}}
 [debug] [XCUITest] Failed to create session. Retrying...
 [debug] [XCUITest] Sending createSession command to WDA
 [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.apple.mobilesafari","arguments":["-u","http://0.0.0.0:4723/welcome"],"shouldWaitForQuiescence":true}}
 [debug] [XCUITest] Failed to create session. Retrying...`

**Comment by imurchie** [comment]
@thanksdanny or @xaph Can you provide the _full_ Appium server logs as a [gist](https://gist.github.com)?

**Comment by thanksdanny** [comment]
@imurchie thank you very much to reply me,here is my [gits](https://gist.github.com/thanksdanny/e4a7ba7dec577ad73e5aff8ee00abc24)

**Comment by imurchie** [comment]
Are you able to `ping` localhost?

```
ping localhost
```

**Comment by mykola-mokhnach** [comment]
@thanksdanny 

If you have localhost as your host and it still doesn't work, check your /etc/hosts file if it has this row: 

```
127.0.0.1 localhost
```

**Comment by thanksdanny** [comment]
@mykola-mokhnach i found the problem! as you said i check the /etc/hosts file , i found that my hosts file has been changed , when i use "Gas Mask" to change my host a month ago. now i can run the test!

@imurchie and thank u !!!very very much !!

**Comment by imurchie** [comment]
Awesome!

**Comment by lvconley** [comment]
This for the tip on the hosts file, guys! That's exactly what was blocking me with the useless "ENOTFOUND" error as well. Something had wiped my hosts file--and I have no idea what did it. Anyway, I restored it thusly and all started working perfectly:

##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost

**Comment by kamaldeepsinghbhatia** [comment]
@mykola-mokhnach I faced same issue and almost tried all things like restart even re-installation. But adding host worked. Thank you so much!!!!! (Y)

**Comment by KranthiRekhaKadari** [comment]
how can we know about the host file

**Comment by coolvasanth** [comment]
> Thanks for the tip on the hosts file, guys! That's exactly what was blocking me with the useless "ENOTFOUND" error as well. Something had wiped my hosts file--and I have no idea what did it. Anyway, I restored it thusly and all started working perfectly:
> 
> `127.0.0.1 localhost 255.255.255.255 broadcasthost ::1 localhost`

I have exact same thing as you mentioned in the etc/hosts file. Still I'm getting error, "ENOTFOUND". Can you please help me what could be the issue.
