### ISSUE TITLE
Support for path based xpath(identified using iOS 9.x) in iOS 10 

### ISSUE THREAD

**Issue by giripalanivel** [appium/appium#7275]
## The problem
We have xpath locators identified in iOS 9.x version such as  //UIAWebView/UIATextField.
Since there is no alternative ids, we are forced to use above xpath only.

When we tried to run the tests in iOS10 using appium 1.6, the UIA string in xpath is not getting replaced by XCUITestElementType.

I know currently single xpath locators were automatically gets updated to XCUITestElementType, but is there a support planed for path based xpath strings? If so what is the timeline for it?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: MAC 10.11
* Node.js version (unless using Appium.app|exe): 4.5.0
* Mobile platform/version under test: iOS10
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
There is no way to automatically update UIAtomation locators to XCTest, since the second one generates different hierarchy and class names are different there or are just presented as "XCUITestElementTypeOther". You must update all xpaths manually if you want to use WDA.
