### ISSUE TITLE
Cannot launch Appium tests on iOS 10 simulator or device

### ISSUE THREAD

**Issue by MSI15** [appium/appium#7276]
## The problem

When attempting run Appium tests on iOS 10 real device or simulator the simulator starts to load and crashes. In the case of real device the app never loads.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6.1-beta
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS X EI Capitan 10.11.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.1
* Real device or emulator/simulator: iPhone 6s Plus
* Appium CLI or Appium.app|exe:

## Details

I have some tests written in intelli J IDE that run on Appium for iOS devices. When attempting to run the tests with the following Appium capabilities, in the case of a simulator the simulator crashes and i the case of a real device the device crashes.

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("platformName", "ios");
capabilities.setCapability("command-timeout", 100000);
capabilities.setCapability("app", applicationPath);
capabilities.setCapability("bundleId", bundleId);
capabilities.setCapability("autoDismissAlerts", true);
capabilities.setCapability("fullReset", true);
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability(CapabilityType.VERSION, iOSVersion);
capabilities.setCapability("deviceName", deviceName);
 capabilities.setCapability("udid", UDID);
capabilities.setCapability("noReset", true);

## Link to Appium logs

Please refer to the link below.

https://gist.github.com/MSI15/6f84510f7be8adc94ba56d28ea3f477a

## Code To Reproduce Issue [ Good To Have ]

   public IOSDriver<WebElement> startIOSDriver() throws Exception {
        URL serverAddress = new URL("http://127.0.0.1:"+port+"/wd/hub");
        DesiredCapabilities capabilities = getIosDesiredCapabilities();
        iOS_DRIVER = new IOSDriver<WebElement>(serverAddress, capabilities);
        return iOS_DRIVER;
    }

**Comment by mykola-mokhnach** [comment]
Make sure _carthage_ is installed on the machine where the test is running

**Comment by MSI15** [comment]
I have installed carthage, now it runs on simulator. But the tests don't run on a real device. When attempting to run the tests on real device I get the error below:

**Comment by ohadschn** [comment]
Easiest way to install *cathage* on OSX: `brew install carthage`.
