### ISSUE TITLE
Problems with finding BundleID configured apps on IOS 10.1 using Appium 1.6

### ISSUE THREAD

**Issue by SteveKSB** [appium/appium#7278]
## The problem
Appium 1.6 fails to find BundleID specified apps on Iphone 6 Plus on IOS 10
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3 using Iphone 5/IOS 9.3
* Desktop OS/version used to run Appium: mac OS Sierra (10.12.1)
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Iphone 6 Plus/IOS 10.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium.exe

## Details

Configured Appium 1.6 with latest XCUITest driver (2.0.37) and specified a BundleID for a preinstalled app on an Iphone 6 plus/IOS 10.1. Using ideviceinstaller to the connected device, a listing of the BundleIDs for the apps are displayed. Using this BundleID, configured Appium to use it (I don't have the .app or .ipa). Appium can connect to the Iphone but when it checks for the bundleID app, it says it cannot be found. Another post pointed to using newer version of XCUITest driver to fix which I did by installing 2.0.37. When I try Appium 1.5.3 to Iphone 5/IOS 9.3, it successfully finds the Bundle ID.

## Link to Appium logs

https://gist.github.com/SteveKSB/ea1f583d02928c1c876c01af709bc984

## Code To Reproduce Issue [ Good To Have ]

Any use of BundleID with Appium 1.6 appears to cause this problem.

**Comment by imurchie** [comment]
Do not specify an `app` desired capability at all.

**Comment by SteveKSB** [comment]
@imurchie Can you elaborate on what you mean by Do not specify an app desired capability at all? The same type of BundleID app finding does work on older Appium to IOS 9.3 phone. Is this not supported in IOS 10.1 yet? Thank you.

**Comment by imurchie** [comment]
I think there is a small error in Appium's handling of having both a `bundleId` and `app` set to be the bundle id. If you _only specify `bundleId` and leave off the capability `app` it ought to work.

**Comment by SteveKSB** [comment]
@imurchie Thank you. Makes sense. I'm running Appium from the GUI on Mac OS X. Which file would contain these params so can be removed? Thank you.
