### ISSUE TITLE
Appium can not retrieve elements tree (page source)

### ISSUE THREAD

**Issue by Oreneo** [appium/appium#7279]
## The problem
Appium inspector screenshot is displayed correctly, but the elements are not being identified.
Getting the message:
"Error getting source page: An unknown server-side error occurred while processing the command."
Error in log: "Command returned error:java.lang.RuntimeException: Failed to Dump Window Hierarchy"

## Environment
* Appium version: 1.6.0
* Desktop OS/version: Windows 10
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: Android 4.4.2
* Real device or emulator/simulator: Samsung GT-I9505

## Link to Appium logs
https://gist.github.com/Oreneo/719e308e8da1e54cb8984a85035f674f

**Comment by jlipps** [comment]
Is this a problem when not using Appium.exe? Appium.exe is no longer supported.
