### ISSUE TITLE
XCUITest - XCode 8 - iOS 10 Tests Are Running Very Slow

### ISSUE THREAD

**Issue by raymondlapak** [appium/appium#7284]
## The problem

A simple test like logging in, assertion, and logging out takes 5-6 minutes whereas in Android test (also Appium) only takes like 2 or 3 minutes. It seems like the test just stuck for couple of seconds on finding element before proceeding to execute any task. I heavily use XPATH though.

I already done the iwd injection from https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/iwd_xcode7.md but with no good result, tests are still very slow to execute.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0-beta3
* Desktop OS/version used to run Appium: OS X
* Mobile platform/version under test: iOS 10 - iPhone 6
* Real device or emulator/simulator: Simulator

**Comment by mykola-mokhnach** [comment]
Known limitation of XCTest. Wait for the next release of Appium with this WDA fix included: https://github.com/facebook/WebDriverAgent/pull/308

You may also do some optimizations in your code right know. Read https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md for more details

**Comment by raymondlapak** [comment]
Thanks @mykola-mokhnach , any idea on when will the next version of Appium be available with that WDA fix? Great work on https://github.com/facebook/WebDriverAgent/pull/308 by the way. Can't wait for the release.

**Comment by mykola-mokhnach** [comment]
@raymondlapak This fix has been already released with Appium 1.6.2

**Comment by arsen-adzhiametov** [comment]
@mykola-mokhnach I'm using version appium 1.6.3 and face the same issue but with Web UI testing on real device. 

Could you look at description of my [#7950](https://github.com/appium/appium/issues/7950). Maybe you have some new information about this behaviour. I have read tens of posts where found descriptions that XCUITest are slow, but I can't believe that it is still unresolved. Thank you

**Comment by arsen-adzhiametov** [comment]
SOLVED for me: 
I’ve installed appium 1.6.4-beta and was surprised. My test become faster in ~4 times!
Execution time on real device comparable with chrome emulator (for one 7-step scenario: 23 sec on chrome emulator and 50 sec on real  iOS device!)
Previously I’ve mentioned that execution time of this scenario took about 3 minutes (for appium 1.6.3).
