### ISSUE TITLE
ios, element not loading with appium in runtime, but loading manually

### ISSUE THREAD

**Issue by veeramanikandanvv** [appium/appium#7286]
I am able to see the Table that loads dynamically in the Screen Manually but when i fetching the page source with getPageSource() method its provding me the incorrect source in which table data is not seen. I am Using appium 1.5.3. someone help me on this.

**Comment by veeramanikandanvv** [comment]
In a Screen i have Show Details link. If i Click the show details Link, it populates Table. I am able to see the Table Manually. But in getPageSource() i am not able to see the table data. I use XPATH for Inspecting the Table Data and get the Exception as "Unable to Locate the Element." 

In Appium Inspector also i am able to see the table only after the Refresh. 

Any Solution is highly Appreciated

**Comment by TusharRastogi** [comment]
**This is not an issue of Appium. Use [discuss ](https://discuss.appium.io/)forum to ask something like this**

Just to give you gist,
First check whether the table is visible or not (eg. isDisplayed()). Then try to interact with it.
And I suggest using `accessibility ID` or `uiautomation `locator strats. over xpath.

Also after selecting the Show Details link if the table is not visible on screen scroll to view the table.

**Comment by veeramanikandanvv** [comment]
Thanks Tushar. Initially when i Land in the Page the Table is Hidden. After Clicking the Show Details the Table becomes visible. But Even after Table is Visible we are unable to get the Source of the Table. 

Please help us on this.

**Comment by veeramanikandanvv** [comment]
i feel the issue is from appium, Posting the Similar kind of Issue FYI,

https://github.com/appium/appium/issues/4606

**Comment by dpgraham** [comment]
Hey @veeramanikandanvv. Can you provide me with a gist of the server logs and the code snippet you are trying to call? Also can you provide me the source XML?

**Comment by srk9ravi** [comment]
@veeramanikandanvv 
Hi I am the one who posted the original issue and still facing the same. 
please let me know once you are able to fix that.
Thanks

**Comment by veeramanikandanvv** [comment]
Issue is been fixed...  We have to set set accessibility elementhidden as
no in the xcode.. this resolved my issue...

On 29-Nov-2016 12:04 am, "Ravikumar Seedarla" <notifications@github.com>
wrote:

@veeramanikandanvv <https://github.com/veeramanikandanvv>
Hi I am the one who posted the original issue and still facing the same.
please let me know once you are able to fix that.
Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/appium/appium/issues/7286#issuecomment-263353638>, or mute
the thread
