### ISSUE TITLE
 Pop up system not recognized

### ISSUE THREAD

**Issue by royncls** [appium/appium#7287]
Hello,
I am currently developing robot framework and appium tests on a native application that embeds swift1.5.3.
I'm on an IOS environment "elcapitain", xcode 8 and an appium version 1.6.1.
The problem I encounter is that the pop up systems are not recognized by appium. None is possible.
I say that I start on Mac so maybe I forget something.
If you had a solution to offer me, I would be very happy.

Thank you very much.

## Environment
* Appium version 1.6.1
* Last Appium version that did not exhibit the issue (if applicable):<1.6
* Desktop OS/version used to run Appium: Mac Elcapitain

**Comment by mykola-mokhnach** [comment]
We use Apple scripting to click buttons on systemy alerts:

```applescript
set defaultTimeout to 1.0
set foundNotif to false
tell application "System Events"
	repeat with i from 1 to 10
		if process "UserNotificationCenter" exists then
			set foundNotif to true
			exit repeat
		end if
		delay defaultTimeout
	end repeat
	delay defaultTimeout
	if foundNotif is false then
		error "No permission window found"
	end if
	tell process "UserNotificationCenter"
		click button "%s" of window 1
	end tell
end tell
```

and then in the code 

```java
      String script = String.format(new String(Files.readAllBytes(Paths.get(getClass().getResource(PERMISSION_SCRIPT).toURI()))), "OK");
      getDriver().executeScript(script);
```

**Comment by royncls** [comment]
Hello, 

Thanks for the Answer but could you be more precise where we have to put this kind of code?

Thanks in advance
