### ISSUE TITLE
Opening native app ios 10 with grid

### ISSUE THREAD

**Issue by jonasvandevelde** [appium/appium#7288]
Hi, 
I want to run my scripts on IOS 10 with appium. Previously, I've ran my scripts on 7, 8, 9 which worked good.
Now I'm making the switch to IOS 10 and I'm having a very hard time starting my scripts and opening the native app.
I've updated to xcode 8 and Appium 1.6, 
uninstalled and installed libimobiledevice and ideviceinstaller again, 
did a sudo chmod on /var/db/lockdown, 
downloaded the latest node.js, 
installed carthage, 
ran the ./Scripts/bootstrap.sh in the WebDriverAgent folder, 
ran the npm i -g webpack command
followed [this](https://discuss.appium.io/t/xcodebuild-failed-with-code-65-warning-the-server-did-not-provide-any-stacktrace-information-command-duration-or-timeout-32-63-seconds/12756/4) page for the WebDriverError, 
set the automationName to 'XCUITest'

this are my capabilities in the code:
`capabilities.setCapability("deviceName",device);
  capabilities.setCapability("browserName","IOSiPhone"+device);
  capabilities.setCapability("app", PhoneIPA);
  capabilities.setCapability("noReset", true);
  capabilities.setCapability("newCommandTimeout",200);
  capabilities.setCapability("UDID",device);
  capabilities.setCapability("Dev","IOSiPhone");
  capabilities.setCapability(MobileCapabilityType.TAKES_SCREENSHOT,"true");
  capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"IOS");
capabilities.setCapability("xcodeConfigFile","/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig");
                `
this is my json file:
`{
"capabilities":
[
{
"browserName": "IOSiPhonec7814fda77dc2ee263dbe7addfa9331b38fd604a",
"version":"",
"maxInstances": 1,
"platform":"MAC"
}
],
"configuration":
{
"nodeTimeout":120, 
"port":4727, 
"hubPort":4040,
"proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
"url":"http://127.0.0.1:4727/wd/hub",
"hub": "127.0.0.1:4040/grid/register",
"hubHost":"127.0.0.1",
"nodePolling":2000,
"registerCycle":1000,
"register":true,
"cleanUpCycle":6000, 
"timeout":120000, 
"maxSession":1,
"newCommandTimeout":60000,
"takesScreenshot":true
}
}
`

this is my cmd line how I start my appium node:
`node /usr/local/lib/node_modules/appium/build/lib/main.js --nodeconfig /Users/jonasvandevelde/INGIT/CleanStartScript/json/json2251.json -p 4727 -U c7814fda77dc2ee263dbe7addfa9331b38fd604a -bp 2251 --automation-name XCUITest
`

But when I run my test, some WebDriver opens on appium.io and not my native application.
I'm using a selenium grid to connect to which is connected to the node.

**Comment by mykola-mokhnach** [comment]
Appium 1.6.1, which has been released just recently has several fixes for Grid. Try it.
