### ISSUE TITLE
appium is not able to update from 1.6.1-beta to 1.6.1

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#7290]
## The problem

I've 1.6.1-beta installed and today morning tried updating to latest version with command npm update -g. But it didn't update to 1.6.1 

## Environment

* Appium version (or git revision) that exhibits the issue:    1.6.1-beta
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium:  Mac  10.11.6
* Node.js version (unless using Appium.app|exe): v7.1.0
* Mobile platform/version under test: NA 
* Real device or emulator/simulator: NA
* Appium CLI or Appium.app|exe: NA

## Details

NA

## Link to Appium logs

NA

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by amedvedjev** [comment]
```
npm uninstall -g appium
npm install -g appium
```

**Comment by vikramvi** [comment]
thanks it worked @amedvedjev
