### ISSUE TITLE
npm install -g appium is failing

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#7292]
## The problem

npm install -g appium is failing with error as below

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'deep-extend' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "install" "-g" "appium"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.2

npm ERR! Cannot read property 'extsprintf' of undefined
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vikram-anna/npm-debug.log

## Environment

* Appium version (or git revision) that exhibits the issue:  1.6.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Mac  10.11.6
* Node.js version (unless using Appium.app|exe):  v7.1.0
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Uninstalled existing Beta version of appium and tried installing latest one, it is failing consistently

## Link to Appium logs

NA

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by TusharRastogi** [comment]
Check the compatible node version for the appium version you are installing. Try changing(upgrading node):
`brew upgrade node`
`npm install -g appium@1.6.1` # If you are looking for latest Appium version

**Comment by mykola-mokhnach** [comment]
Looks like this [known](https://github.com/npm/npm/issues/14660#issuecomment-261597360) bug in npm. Downgrading npm to 3.10.10 has resolved the problem for me:

```
npm install -g npm@3.10.10
```

**Comment by vikramvi** [comment]
@mykola-mokhnach @TusharRastogi  Thanks for quick help.

It will be nice if appium team mentions compatible versions of npm and node when new version of appium is released  cc: @jlipps

**Comment by trusk89** [comment]
Can confirm @vikramvi 's fix works. Thanks!

**Comment by jlipps** [comment]
@vikramvi didn't notice the issue until you mentioned it, but it sounds like NPM has found a fix so it should be resolved for everyone soon in any case.
