### ISSUE TITLE
Appium 1.6. Unable to sendKeys on TextField. "Keyboard is not present" error occurs

### ISSUE THREAD

**Issue by VeronikaGusarova** [appium/appium#7293]
## The problem

Getting following error when trying Clear or SendKeys into TextField

OneTimeSetUp: OpenQA.Selenium.WebDriverException : Unexpected error. Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}

## Environment

* reproducible only with Appium 1.6.0
* Last Appium version that did not exhibit the issue - Appium 1.5.3 (with another locator)
* Desktop OS/version used to run Appium - iOS 10.11.5
* Node.js version (unless using Appium.app|exe): npm v. 3.10.3
* Mobile platform/version under test: iOS 10.0.2
* Real device 
* Hybrid app (reproducible on native screen)

## Details

The error occurs when running following code:
var userNameField = _webDriver.FindElement(By.XPath("//XCUIElementTypeTextField[1]"));
userNameField.Click();
userNameField.Clear();
userNameField.SendKeys(userName);

The element is successfully found by locator (seeing in debug mode), no problems with waiters.

Looks like textfield cannot receive focus

Tried Tap and setimmediatevalue - got the same result

## Link to Appium logs

See appium logs [here](https://gist.github.com/VeronikaGusarova/4e9a8382d803f7c1b7cb434ce855d394)

**Comment by mykola-mokhnach** [comment]
Is the keyboard shown if you tap the text field manually? Might it be there are several text fields in the UI tree and you are looking for a wrong one?

**Comment by VeronikaGusarova** [comment]
No, there is the only textField. Please see [source code](https://gist.github.com/VeronikaGusarova/1039d87600b48eba5244ea91ed307eef)

Reproducible even with full path

May be the issue is similar with https://github.com/appium/appium/issues/7109

**Comment by mykola-mokhnach** [comment]
You didn't say anything about landscape mode before. Yes - there's a known bug. Try to manually replace WDA in /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent with the most recent [version](https://github.com/facebook/WebDriverAgent) and restart Appium - this should do the trick.

**Comment by VeronikaGusarova** [comment]
works now, thanks!

**Comment by mykola-mokhnach** [comment]
@triager please close
