### ISSUE TITLE
ERROR: Test target WebDriverAgentRunner encountered an error (Failed to background test runner

### ISSUE THREAD

**Issue by vinodgs7** [appium/appium#7295]
## Summary

Unable to dismiss system level alert on iOS device(Low battery alert)

## Environment

* Appium version: 1.6.0
* Desktop OS/version used to run Appium: OS X El Capitan version 10.11.6
* Node.js version (unless using Appium.app|exe): v4.6.2
* Mobile platform/version under test: iOS 9.3.5
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
https://gist.github.com/vinodgs7/ddd11f5620cb9bbf175de2b866d20a96

## Steps To Reproduce Issue

Scenario: 
1. Add capability capabilities.setCapability("autoDismissAlerts", true);
2. Start execution when device battery percentage is at 6% 
3. Run test in debug mode and put debug point after application launch
4. Wait till low battery alert appears
5. Resume execution

**Comment by mykola-mokhnach** [comment]
Unfortunately, there is [no workaround](https://github.com/facebook/WebDriverAgent/issues/367) for it.

**Comment by mykola-mokhnach** [comment]
@triager please close
