### ISSUE TITLE
Code signing is required for product type 'UI Testing Bundle' in SdK 10.2 appium 1.6

### ISSUE THREAD

**Issue by shanky231** [appium/appium#7300]
I have installed appium 1.6 through command line and wants to test with my real device but not working, but with simulator its working.
Following error is coming
Signing for 'WebDriverAgentRunner' requires a development team.
Code signing is required for product type 'UI Testing Bundle' in SdK 10.2

I have already signed WebdriverAgentLib and Runner with my Id and  i m able to build it successfully with my device through xcode.
My app is also signed with same Id

Please Help.    Its urgent I have a release.

One thing which i suspect is In webdriverAgentLib Provisioning profile is showing 'not required'.I have already signed it but it still not changing

**Comment by mykola-mokhnach** [comment]
Try to use _keychainPath_ and _keychainPassword_ [capabilities](https://github.com/appium/appium-xcuitest-driver).

**Comment by shanky231** [comment]
I tried but didn't get how to do that.Can you please explain the process.(where keychain file will be created, to give the path and which .p12 file to be used

**Comment by mykola-mokhnach** [comment]
If you carefully read though the provided link then you might notice the link to [this](http://stackoverflow.com/questions/16550594/jenkins-xcode-build-works-codesign-fails) Stackoverflow issue, which describes the stuff in much more detailed way.

**Comment by shanky231** [comment]
hey thanks for the reply, but adding keychain is not helping.Can you provide any other solution.
And one more query the devices udid needs to be registered even for running the Integration app.
