### ISSUE TITLE
Appium with Cordova compatibility

### ISSUE THREAD

**Issue by Smita001** [appium/appium#7301]
## The problem

I am unable to switch to Webview in appium selendroid mode. Getting error An unknown server-side error occurred while processing the command. (Original error: read ECONNRESET)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.00/ 1.4.13/1.4.16
* Last Appium version that did not exhibit the issue (if applicable):1.4.16
* Desktop OS/version used to run Appium:Windows 10/Windows 7
* Node.js version (unless using Appium.app|exe):6.3.0
* Mobile platform/version under test:4.2.2
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe: Appium.exe

## Details

After attching the context 'webview_0' in the next step when trying to close the pop up (driver.findElement(By.xpath("//*[@id='popupClose']")).click();) getting below error. 
Please help me on the same to unblock the issue

## Link to Appium logs

https://gist.github.com/Smita001/2f5eed22e6bb885758f0995e64d6e0bc

## Code To Reproduce Issue [ Good To Have ]
DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("browserName", "");
		capabilities.setCapability("platformName", "Android");
		capabilities.setCapability("automationName", "Selendroid");
		capabilities.setCapability("version", "4.2.2");
		capabilities.setCapability("locationContextEnabled", true);
		capabilities.setCapability("deviceName", "444434GGFLKL");
		capabilities.setCapability("app", app.getAbsolutePath());
		capabilities.setCapability("appPackage", "xyz.xyz.com");
		capabilities.setCapability("appActivity", ".XYZActivity");
		driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

					Set<String> contextNames1 =  driver.getContextHandles();
					for (String contextName : contextNames1) 
					  {
					      if (contextName.contains("NATIVE_APP"))
					      {
					           driver.context(contextName);
					      }
					  }
					
					Set<String> contextNames =  driver.getContextHandles();
					for (String contextName : contextNames) 
					{
					    if (contextName.contains("WEBVIEW"))
					    {
					         driver.context(contextName);
					    }
					}
driver.findElement(By.xpath("//*[@id='popupClose']")).click();

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Try to invoke

```java
getDriver().switchTo().alert().accept()
```

instead to accept the alert.

**Comment by jlipps** [comment]
@Smita001 the log shows that Selendroid is having some internal trouble interacting with your webview. I'd suggest you ask the Selendroid project for help with that error message.
