### ISSUE TITLE
I try to found the appium 1.6.1 dmg file, but I can not found it. can you help me to found, thanks.

### ISSUE THREAD

**Issue by qkjs** [appium/appium#7302]
## The problem

I am a beginner at Appium, I have a Mac. so I try to found a Appium dmg file to install. I think it's sample then using commend line.  Bug I can't found the the dmg file for Appium 1.6.1. the old version can't be using, because Xcode 8.1 problem.  how can help me fix this issue. thanks a lot.

**Comment by mykola-mokhnach** [comment]
Appium is only available from npm repository. Closing the issue as irrelevant, Appium forum is better place for such kind of request.

@triager please close
