### ISSUE TITLE
Error while using driver.tap with coordinates after update to 1.6.1

### ISSUE THREAD

**Issue by PeterGolf** [appium/appium#7304]
## The problem

I'm using command driver.tap(1, x, y, 2) for tapping on element. With 1.6.0 it works fine, but with 1.6.1 it stopped working. I have this error:

An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/0492FE5C-49B7-43E4-8BDB-58F0DD66627E/touchAndHold -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/0492FE5C-49B7-43E4-8BDB-58F0DD66627E/touchAndHold"
    );
} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 11 milliseconds

**Comment by PeterGolf** [comment]
this is from node:

[HTTP] --> POST /wd/hub/session/6dade04f-16e9-410f-a5d1-3e05fd3b21e3/touch/perform {"actions":[{"action":"press","options":{"x":300,"y":500}},{"action":"wait","options":{"ms":2}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":300,"y":500}},{"action":"wait","options":{"ms":2}},{"action":"release","options":{}}],"6dade04f-16e9-410f-a5d1-3e05fd3b21e3"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-wait-release
[debug] [JSONWP Proxy] Proxying [POST /touchAndHold] to [POST http://localhost:8100/session/0492FE5C-49B7-43E4-8BDB-58F0DD66627E/touchAndHold] with body: {"duration":0.002,"x":300,"y":500}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/0492FE5C-49B7-43E4-8BDB-58F0DD66627E/touchAndHold -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/0492FE5C-49B7-43E4-8BDB-58F0DD66627E/touchAndHold\"\n    );\n}","sessionId":"0492FE5C-49B7-43E4-8BDB-58F0DD66627E","status":1}
[HTTP] <-- POST /wd/hub/session/6dade04f-16e9-410f-a5d1-3e05fd3b21e3/touch/perform 500 7 ms - 398 
[HTTP] --> POST /wd/hub/session/6dade04f-16e9-410f-a5d1-3e05fd3b21e3/element {"using":"xpath","value":""}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","","6dade04f-16e9-410f-a5d1-3e05fd3b21e3"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/0492FE5C-49B7-43E4-8BDB-58F0DD66627E/element] with body: {"using":"xpath","value":""}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"xpath","value":"","description":"unable to find an element"},"sessionId":"0492FE5C-49B7-43E4-8BDB-58F0DD66627E","status":7}
[HTTP] <-- POST /wd/hub/session/6dade04f-16e9-410f-a5d1-3e05fd3b21e3/element 500 360 ms - 164

**Comment by PeterGolf** [comment]
@imurchie as i see, it was fixed in appium/appium-xcuitest-driver project (issue 281), but after installing 1.6.1 release version, the problem is actual.

**Comment by jlipps** [comment]
@PeterGolf it seems to me that this is either a WebDriverAgent issue (perhaps they removed the `touchAndHold` endpoint), or a client issue (maybe it's trying to connect to the `touchAndHold` endpoint, which doesn't exist). @mykola-mokhnach or @marekcirkos do you know anything about this?

**Comment by mykola-mokhnach** [comment]
@jlipps I suppose this happens, because the recent WDA release has not been merged to 1.6.1 release, where @imurchie's PR for _touchAndHold_ by coordinates is merged (it has been added as separate API call).

**Comment by marekcirkos** [comment]
@jlipps It is still there https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L59

**Comment by jlipps** [comment]
Ugh. I didn't realize @imurchie's PR had a WDA dependency. I guess we need to pull in WDA and get out 1.6.2 ASAP.

**Comment by SonaliBurghate** [comment]
I also facing same error for xy co-ordinates on iOS with Appium1.6.1. Please let us know the release date for Appium1.6.2

**Comment by swachhab** [comment]
Does Appium 1.6.1 supports TouchAction functions like Pinch(x,y).Perform(), I am facing Unhandled endpoint exception while working in IOS 10.1..?
