### ISSUE TITLE
Xcode 8 iOS10.0 : Unable to launch appium

### ISSUE THREAD

**Issue by GopalakrishnaNagam** [appium/appium#7308]
## The problem

Through terminal i have the installed the latest version (npm install -g appium) (v1.6.0)
Xcode8 and iOS 10 Simulator

Launched the app through terminal and ran the script
App is not launching and in error logs message is displaying as
org.openqa.selenium.SessionNotCreatedException: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.0. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead. (WARNING: The server did not provide any stacktrace information)

**Comment by jlipps** [comment]
Did you try doing what the message said (using the `automationName` capability with the value `XCUITest`? At any rate, I'm not sure you're actually targeting iOS 10 because that message only appears for iOS 9 and below.

**Comment by GopalakrishnaNagam** [comment]
Previous Xcode version is 7, Appium(1.4.13)  and iOS 9.1 , then it worked fine .After upgrading to Xcode 8.1 , appium v1.6.2 (through Terminal) ,iOS 10.1 , I am facing the below issue in the error logs
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

**Comment by jlipps** [comment]
You should read https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md. The automation system for iOS 10 is completely different and even has different system dependencies.
