### ISSUE TITLE
autoAcceptAlerts does't work

### ISSUE THREAD

**Issue by wangtao169447** [appium/appium#7309]
## The problem
autoAcceptAlerts does't work

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.1
* Last Appium version that did not exhibit the issue (if applicable):1.6.0
* Desktop OS/version used to run Appium:OSX 10.11.6
* Node.js version (unless using Appium.app|exe):v6.3.0
* Mobile platform/version under test:iOS/10.1
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:Appium CLI and python-client

## Details
i have set "autoAcceptAlerts": True, however it does not work

## Code To Reproduce Issue [ Good To Have ]
        self.driver = webdriver.Remote(
            command_executor='http://127.0.0.1:4723/wd/hub',
            desired_capabilities={
                'app': app,
                'platformName': 'iOS',
                'platformVersion': '10.1',
                'automationName': 'XCUITest',
                'deviceName': 'iPhone 6',
                'autoAcceptAlerts': True,
            })

**Comment by dpgraham** [comment]
Duplicate of: https://github.com/appium/appium/issues/6864
