### ISSUE TITLE
Error : copying attributes (Appium 1.6.1 - Inspector)

### ISSUE THREAD

**Issue by muratme** [appium/appium#7310]
## The problem

I could not inspect elements with 1.6.1. After a while, especially if there are lots of listing elements (collectionView  > cells) on view. Inspector stoped suddenly!

## Environment

    Appium version (or git revision) that exhibits the issue: Appium 1.6.1
    Desktop OS/version used to run Appium: MACOS 10.11.6 El Capitan
    Node version (unless using Appium.app|exe): v6.8.0
    Npm Version : 3.10.8
    Mobile platform/version under test: IOS 10.1
    Real device or emulator/simulator: Iphone5s Simulator (10.1)
    java version "1.8.0_40"

## Link to Appium logs

[debug] [WebDriverAgent] Sim: Nov 29 14:20:47 murat-mercans-MacBook-Pro XCTRunner[18397]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x6100000576d0> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1

**Comment by mykola-mokhnach** [comment]
Known [WDA](https://github.com/facebook/WebDriverAgent/issues/372) issue. There is nothing Appium can do about it.

**Comment by mykola-mokhnach** [comment]
@triager please close
