### ISSUE TITLE
Appium v1.6.0 - Landscape mode - Unable to tap on the button of type XCUIElementTypeButton .

### ISSUE THREAD

**Issue by vishwathma** [appium/appium#7311]
Unable to tap on the button of type XCUIElementTypeButton in the Landscape mode. The same test case works fine in the Portrait mode.

The button shows up properly in the view & also in the dom tree.xml. But tapping action on the button fails on using both xpath & className.

## Environment

* Appium version (or git revision) that exhibits the issue: V1.6.0
* Last Appium version that did not exhibit the issue (if applicable): V1.5.3
* Desktop OS/version used to run Appium: MAC 10.11.6
* Node.js version (unless using Appium.app|exe): v6.8.1
* Mobile platform/version under test: IOS/10.1
* Real device or emulator/simulator: Simulator

**Comment by jlipps** [comment]
This issue has already been reported and resolved. Please use Appium 1.6.1

**Comment by pavanbachu0604** [comment]
@jlipps With Appium 1.6.1 the we are not able to click the element in landscape mode

**Comment by vikramvi** [comment]
https://github.com/appium/appium/issues/6994  @pavanbachu0604 @vishwathma
