### ISSUE TITLE
Xcode 8 iOS 10.0.2 : Appium unable to launch app

### ISSUE THREAD

**Issue by kumawatbharat** [appium/appium#7312]
**Problem**

Appium not able to launch application. I have started appium from source code and running from command line. Able to start appium but not able to execute test cases.

**Environment**

iOS - 10.0.2
Xcode - 8.0

**Details**

**Appium log :** 

Desired capabilities
apabilities:
[Appium]   browser_name: ''
[Appium]   setWebContentsDebuggingEnabled: 'true'
[Appium]   autoWebView: 'true'
[Appium]   takesScreenshot: true
[Appium]   javascriptEnabled: true
[Appium]   driver.class: 'io.appium.java_client.ios.IOSDriver'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone'
[Appium]   cssSelectorsEnabled: true
[Appium]   app: '/Users/mitulrathod/Desktop/app/Reservation.ipa'
[Appium]   udid: 'b016629ba87d807d7d0eec3c5c0b0c08bdda45c1'
[Appium]   automationName: 'XCUITest'
[Appium]   platformVersion: '10.0.2'

xcodeConfigFile: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] XCUITestDriver version: 2.2.0
[BaseDriver] The following capabilities were provided, but are not recognized by appium: browser_name, setWebContentsDebuggingEnabled, autoWebView, takesScreenshot, javascriptEnabled, driver.class, cssSelectorsEnabled.
[BaseDriver] Session created with session id: 1d6ce291-8a71-4c26-92f6-85bf24cd2a94
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: b016629ba87d807d7d0eec3c5c0b0c08bdda45c1
[debug] [XCUITest] Creating iDevice object with udid b016629ba87d807d7d0eec3c5c0b0c08bdda45c1
[XCUITest] Determining device to run tests on: udid: 'b016629ba87d807d7d0eec3c5c0b0c08bdda45c1', real device: true
[BaseDriver] Using local app '/Users/mitulrathod/Desktop/app/Reservation.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/l7/qgdml66j61qbhrln3w6mv9780000gq/T/20161029-11753-1j8tmr0.7weawtgldi/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/l7/qgdml66j61qbhrln3w6mv9780000gq/T/20161029-11753-1j8tmr0.7weawtgldi/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/l7/qgdml66j61qbhrln3w6mv9780000gq/T/20161029-11753-1j8tmr0.7weawtgldi/Payload/Reservation.app'
[debug] [XCUITest] Checking whether app '/var/folders/l7/qgdml66j61qbhrln3w6mv9780000gq/T/20161029-11753-1j8tmr0.7weawtgldi/Payload/Reservation.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/var/folders/l7/qgdml66j61qbhrln3w6mv9780000gq/T/20161029-11753-1j8tmr0.7weawtgldi/Payload/Reservation.app': 'mobi.tripadvisor.Reservation'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/Users/mitulrathod/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/mitulrathod/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
Killed: 9

**Comment by davidrova** [comment]
I have the same issue.

I have upgrade my app to xcode 8 and upgrade Appium to 1.6.0-beta1

I have tried several capabilities with no sucess.

I have installed carthage-0.18.1.sierra.bottle.tar.gz.
