### ISSUE TITLE
Cannot run test on real device using Appium 1.6.1 and XcuiTest

### ISSUE THREAD

**Issue by ptsiakos77** [appium/appium#7313]
## The problem
Web Driver agent remains in state Listening on USB and the appium tests never start in real device

## Environment
* Appium version 1.6.1:

## Details
i start the appium programatically in order to run test in real device using XCuiTest:

**Here is the output of my test:**

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Running TestSuite
[Appium] Welcome to Appium v1.6.1
[Appium] Non-default server args:
[Appium]   bootstrapPort: 5204
[Appium]   defaultCommandTimeout: 7200
[Appium]   launchTimeout: 180000
[Appium]   udid: '5f1003ad41aced640c492edee48fe6b69dceb3ee'
[Appium] Deprecated server args:
[Appium]   -lt,--launch-timeout => --default-capabilities '{"launchTimeout":180000}'
[Appium]   -U,--udid => --default-capabilities '{"udid":"5f1003ad41aced640c492edee48fe6b69dceb3ee"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   launchTimeout: 180000
[Appium]   udid: '5f1003ad41aced640c492edee48fe6b69dceb3ee'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.1","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 23 ms - 83 
29/11/16 14:51:56 main         INFO  - c.p.o.q.s.s.SteviaTestBase - Selenium RC mode run in local enviroment; First start Selenium RC Server
29/11/16 14:51:56 main         ERROR - c.p.o.q.s.s.SteviaTestBase - Selenium server is not in the classpath, please modify and retry
29/11/16 14:51:56 main         WARN  - c.p.o.q.s.s.SteviaTestBase - *************************************************************************************
29/11/16 14:51:56 main         WARN  - c.p.o.q.s.s.SteviaTestBase - *** SUITE initialisation phase START                                              ***
29/11/16 14:51:56 main         WARN  - c.p.o.q.s.s.SteviaTestBase - *************************************************************************************
29/11/16 14:51:57 main         INFO  - q.s.s.c.c.r.DriverRegistry - Registering driver selenium with driver factory com.persado.oss.quality.stevia.selenium.core.controllers.factories.SeleniumWebControllerFactoryImpl@4d847d32
29/11/16 14:51:57 main         INFO  - q.s.s.c.c.r.DriverRegistry - Registering driver webdriver with driver factory com.persado.oss.quality.stevia.selenium.core.controllers.factories.WebDriverWebControllerFactoryImpl@77128dab
29/11/16 14:51:57 main         INFO  - q.s.s.c.c.r.DriverRegistry - Registering driver appium with driver factory com.persado.oss.quality.stevia.selenium.core.controllers.factories.AppiumWebControllerFactoryImpl@773bd77b
29/11/16 14:51:58 main         WARN  - .p.o.q.s.s.c.SteviaContext - Thread main just registered {runOnRealDevice=true, mobilePlatformName=iOS, xcodeConfigFile=/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/driverAgent.xcconfig, login=true, highlight=false, waitForElement=10, realDeviceLogger=/usr/local/lib/node_modules/deviceconsole/deviceconsole, postgressUri=postgres://jdohgwrdwcugue:6qSrAW71-pjpkV3uPEnSksP8ym@ec2-23-21-164-237.compute-1.amazonaws.com:5432/d8tbr2ejeuqpsc, automationName=Xcuitest, debugging=true, tests.takeScreenshot=true, suite.init.context=true, mobileDeviceUUID=5f1003ad41aced640c492edee48fe6b69dceb3ee, rcHost=localhost, bpPort=5204, actionsLogging=true, recordVideo=false, threadCount=1, mobileApp=/Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/workable-hieiamomevucbecuklmxksgnbsgt/Build/Products/QA-iphoneos/workable.app, mobileDeviceName=Test iPhone 6s - 1, driverType=appium, rcPort=4723, waitForCandidate=120, mobilePlatformVersion=9.3.2, scrollTimeOut=20, parallelSetup=tests, cloudService=Local}
29/11/16 14:51:58 main         INFO  - umWebControllerFactoryImpl - Appium Desired capabilities Capabilities [{app=/Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/workable-hieiamomevucbecuklmxksgnbsgt/Build/Products/QA-iphoneos/workable.app, platformVersion=9.3.2, platformName=iOS, deviceName=Test iPhone 6s - 1}]
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/workable-hieiamomevucbecuklmxksgnbsgt/Build/Products/QA-iphoneos/workable.app","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"9.3.2","automationName":"Xcuitest","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/driverAgent.xcconfig","platformName":"iOS","deviceName":"Test iPhone 6s - 1"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/workable-hieiamomevucbecuklmxksgnbsgt/Build/Products/QA-iphoneos/workable.app","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"9.3.2","automationName":"Xcuitest","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/driverAgent.xcconfig","platformName":"iOS","deviceName":"Test iPhone 6s - 1"},null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/workable-hieiamomevucbecuklmxksgnbsgt/Build/Products/QA-iphoneos/workable.app'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   platformVersion: '9.3.2'
[Appium]   automationName: 'Xcuitest'
[Appium]   xcodeConfigFile: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/driverAgent.xcconfig'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'Test iPhone 6s - 1'
[Appium]   launchTimeout: 180000
[Appium]   udid: '5f1003ad41aced640c492edee48fe6b69dceb3ee'
[debug] [XCUITest] XCUITestDriver version: 2.2.0
[BaseDriver] Session created with session id: 2d17ba43-a6ce-4a25-a550-cd133a8482bb
[debug] [XCUITest] Xcode version set to '7.3.1'
[debug] [XCUITest] iOS SDK Version set to '9.3'
[debug] [XCUITest] Available devices: 5f1003ad41aced640c492edee48fe6b69dceb3ee
[debug] [XCUITest] Creating iDevice object with udid 5f1003ad41aced640c492edee48fe6b69dceb3ee
[XCUITest] Determining device to run tests on: udid: '5f1003ad41aced640c492edee48fe6b69dceb3ee', real device: true
[BaseDriver] Using local app '/Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/workable-hieiamomevucbecuklmxksgnbsgt/Build/Products/QA-iphoneos/workable.app'
[debug] [XCUITest] Checking whether app '/Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/workable-hieiamomevucbecuklmxksgnbsgt/Build/Products/QA-iphoneos/workable.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/workable-hieiamomevucbecuklmxksgnbsgt/Build/Products/QA-iphoneos/workable.app': 'com.workable.ats.qa'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Using Xcode configuration file: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/driverAgent.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=5f1003ad41aced640c492edee48fe6b69dceb3ee -configuration Debug -xcconfig /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/driverAgent.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/CD7B906E-F61F-48E6-840D-1C3B0F460D1F/Session-2016-11-29_14:52:01-IRFeyU.log
[debug] [WebDriverAgent] Device: Nov 29 14:52:05 Test-iPhone-6s-1 XCTRunner[233] <Warning>: Running tests...
[debug] [WebDriverAgent] Device: Nov 29 14:52:06 Test-iPhone-6s-1 XCTRunner[233] <Warning>: Continuing to run tests in the background with task ID 1
[debug] [WebDriverAgent] Device: Nov 29 14:52:07 Test-iPhone-6s-1 XCTRunner[233] <Warning>: Built at Nov 29 2016 14:32:25
[debug] [WebDriverAgent] Device: Nov 29 14:52:07 Test-iPhone-6s-1 XCTRunner[233] <Warning>: ServerURLHere->http://10.9.43.244:8100<-ServerURLHere
[debug] [WebDriverAgent] Device: Nov 29 14:52:07 Test-iPhone-6s-1 XCTRunner[233] <Warning>: Listening on USB

**AND NO PROGRESS IS DONE IT STAYS THERE....**

**Here is the output from Session-2016-11-29_15:56:25-dMM1NV.log**

        deviceName:                 Test iPhone 6s - 1
        deviceIdentifier:           5f1003ad41aced640c492edee48fe6b69dceb3ee
        productVersion:             9.3.2
        buildVersion:               13F69
        deviceSoftwareVersion:      9.3.2 (13F69)
        deviceArchitecture:         arm64
        deviceTotalCapacity:        12648312832
        deviceAvailableCapacity:    8646500352
        deviceIsTransient:          NO
        ignored:                    NO
        deviceIsBusy:               NO
        deviceIsActivated:          YES
        deviceActivationState:      Activated
        deviceType:                 <DVTDeviceType:0x7faaa3e990c0 Xcode.DeviceType.iPhone>
        supportedDeviceFamilies:    (
    1
)
        applications:              (null)
        provisioningProfiles:      (null)
        activityProgress:          -2
        activityTitle:             
        hasInternalSupport:        NO
        isSupportedOS:             YES
        developerDiskMountError:   (null)
(null)
    } (9.3.2 (13F69))
14:52:01.947 xcodebuild[33207:6314722]  /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
build
test
-project
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
-scheme
WebDriverAgentRunner
-destination
id=5f1003ad41aced640c492edee48fe6b69dceb3ee
-configuration
Debug
-xcconfig
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/driverAgent.xcconfig
14:52:01.947 xcodebuild[33207:6314722] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
14:52:01.949 xcodebuild[33207:6314722] Initializing test infrastructure.
14:52:02.186 xcodebuild[33207:6314722] Launch session started, setting a disallow-finish-token on the run operation.
14:52:02.219 xcodebuild[33207:6314725] Creating the connection.
14:52:02.219 xcodebuild[33207:6314725] Listening for proxy connection request from the test bundle (all platforms)
14:52:02.220 xcodebuild[33207:6314725] Resuming the connection.
14:52:02.220 xcodebuild[33207:6314725] Test connection requires daemon assistance.
14:52:02.220 xcodebuild[33207:6314722] Checking test manager availability..., will wait up to 120s
14:52:02.221 xcodebuild[33207:6314722] Starting test session with ID <__NSConcreteUUID 0x7faaa3c3bd80> 4754DC1F-187C-44CD-B04C-11183581293B
14:52:02.237 xcodebuild[33207:6314854] testmanagerd handled session request.
14:52:02.238 xcodebuild[33207:6314722] Waiting for test process to launch.
14:52:02.386 xcodebuild[33207:6314851] app uninstall set - {(
)}
14:52:02.386 xcodebuild[33207:6314851] app install set - {(
    <DVTFilePath:0x7faaa42cbe30:'/Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app'>
)}
14:52:03.316 xcodebuild[33207:6314852] remoteExecutable setInstalledPath:/private/var/containers/Bundle/Application/2DBD66A5-6F55-4A69-9F3C-E4CBCA33F0F2/WebDriverAgentRunner-Runner.app
14:52:03.317 xcodebuild[33207:6314852] Updated test configuration with device paths: <XCTestConfiguration: 0x7faaa3c3dc80>
                      testBundleURL:file:///private/var/containers/Bundle/Application/2DBD66A5-6F55-4A69-9F3C-E4CBCA33F0F2/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
             testBundleRelativePath:(null)
                  productModuleName:WebDriverAgentRunner
                        testsToSkip:(null)
                         testsToRun:(null)
                 reportResultsToIDE:YES
                  sessionIdentifier:<__NSConcreteUUID 0x7faaa3c3bd80> 4754DC1F-187C-44CD-B04C-11183581293B
         pathToXcodeReportingSocket:(null)
          disablePerformanceMetrics:no
    treatMissingBaselinesAsFailures:no
                    baselineFileURL:(null)
           baselineFileRelativePath:(null)
              targetApplicationPath:(null)
          targetApplicationBundleID:(null)
                   reportActivities:YES
           testsMustRunOnMainThread:YES
             initializeForUITesting:YES
14:52:04.477 xcodebuild[33207:6314852] Uploaded test configuration directory from: /var/folders/vf/kq7z0zfs0dz5ccmz9kfxkdfh0000gn/T/com.apple.dt.XCTest/4754DC1F-187C-44CD-B04C-11183581293B/remote-container
14:52:04.477 xcodebuild[33207:6314852] Updated testing environment variables {
    "DTX_CONNECTION_SERVICES_PATH" = "/Developer/Library/PrivateFrameworks/DTXConnectionServices.framework";
    "DYLD_FRAMEWORK_PATH" = "/private/var/containers/Bundle/Application/2DBD66A5-6F55-4A69-9F3C-E4CBCA33F0F2/WebDriverAgentRunner-Runner.app/Frameworks:/Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks";
    "DYLD_LIBRARY_PATH" = "/private/var/containers/Bundle/Application/2DBD66A5-6F55-4A69-9F3C-E4CBCA33F0F2/WebDriverAgentRunner-Runner.app/Frameworks:/Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks";
    "OBJC_DISABLE_GC" = YES;
    "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
    XCTestConfigurationFilePath = "/private/var/mobile/Containers/Data/Application/7E7F3610-99F9-48FC-BAC5-E2DFC6C178D5/tmp/WebDriverAgentRunner-4754DC1F-187C-44CD-B04C-11183581293B.xctestconfiguration";
}
14:52:05.610 xcodebuild[33207:6314722] Adding console adaptor <IDEConsoleAdaptor: 0x7faaa42c9180 'target'> for test session 4754DC1F-187C-44CD-B04C-11183581293B.
14:52:05.856 xcodebuild[33207:6314784] Got proxy channel request from test bundle
14:52:05.856 xcodebuild[33207:6314784] Test bundle is ready, running protocol 16, requires at least version 8. IDE is running 16 and requires at least 8
14:52:05.857 xcodebuild[33207:6314852] Creating secondary transport and connection for whitelisting test process PID.
14:52:05.921 xcodebuild[33207:6314852] Creating the connection.
14:52:05.921 xcodebuild[33207:6314852] Resuming the secondary connection.
14:52:05.922 xcodebuild[33207:6314852] Whitelisting test process ID 233
14:52:02.193 testmanagerd[229:5816] Launched testmanagerd from /Developer/usr/libexec/testmanagerd, built at Saturday 20 February 2016 at 02 h 50 min 51 s Eastern European Standard Time
14:52:02.194 testmanagerd[229:5816] Setting availability state.
14:52:02.194 testmanagerd[229:5816] Posting availability to test bundles...
14:52:02.194 testmanagerd[229:5821] IDE connected via lockdown over socket 5 (__54-[XCTestManagerIDEServer initWithLockdownServiceName:]_block_invoke)
14:52:02.194 testmanagerd[229:5821] Created session with socket 5
14:52:02.197 testmanagerd[229:5828] Handled a proxy request from the IDE with session <XCIDESession: 0x12d5144a0> proxy <_DTXProxy: 0x12d51baf0>
14:52:02.197 testmanagerd[229:5816] __84-[XCIDESession _IDE_initiateSessionWithIdentifier:forClient:atPath:protocolVersion:]_block_invoke <__NSConcreteUUID 0x12d508090> 4754DC1F-187C-44CD-B04C-11183581293B 1 5 from client 3A76334A-3489-44C8-86FA-65DD52B63878-33207-00006C2E57E1D6C6 (/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild)
14:52:02.197 testmanagerd[229:5827] __45-[XCTestManager setIDESession:forIdentifier:]_block_invoke <XCIDESession: 0x12d5144a0> -> <__NSConcreteUUID 0x12d508090> 4754DC1F-187C-44CD-B04C-11183581293B
14:52:02.197 testmanagerd[229:5827] -[XCTestManager _handleRequestForSessionWithIdentifier:]
14:52:05.702 testmanagerd[229:5828] Received new test session connection (-[XCTestManager listener:shouldAcceptNewConnection:])
14:52:05.703 testmanagerd[229:5816] Initial orientation 0
14:52:05.704 testmanagerd[229:5828] Test session <__NSConcreteUUID 0x12d5022d0> 4754DC1F-187C-44CD-B04C-11183581293B requested socket (-[XCTestSession _XCT_requestSocketForSessionIdentifier:reply:])
14:52:05.704 testmanagerd[229:5828] Test session <__NSConcreteUUID 0x12d5022d0> 4754DC1F-187C-44CD-B04C-11183581293B requested socket (__57-[XCTestManager requestSocketForSessionIdentifier:reply:]_block_invoke)
14:52:05.704 testmanagerd[229:5828] -[XCTestManager _handleRequestForSessionWithIdentifier:]
14:52:05.704 testmanagerd[229:5828] Closing IDE connection before sending socket 6 to test host.
14:52:05.704 testmanagerd[229:5828] -[XCIDESession closeIDEConnection:] sending barrier
14:52:05.704 testmanagerd[229:5816] barrier flushed, closing DTXConnection to IDE, socket will not be closed
14:52:05.704 testmanagerd[229:5821] Socket disconnected
14:52:05.704 testmanagerd[229:5821] Disconnecting lockdown socket
14:52:05.704 testmanagerd[229:5828] __33-[XCTestManager closeIDESession:]_block_invoke <XCIDESession: 0x12d5144a0>
14:52:05.704 testmanagerd[229:5828] Considering exiting, 1 test sessions, 0 sessions with identifiers, 0 unidentified sessions...
14:52:05.814 testmanagerd[229:5816] Sending socket 6 to test host
14:52:05.815 testmanagerd[229:5828] __33-[XCTestManager closeIDESession:]_block_invoke <XCIDESession: 0x12d5144a0>
14:52:05.815 testmanagerd[229:5828] Considering exiting, 1 test sessions, 0 sessions with identifiers, 0 unidentified sessions...
14:52:05.882 testmanagerd[229:5828] IDE connected via lockdown over socket 7 (__54-[XCTestManagerIDEServer initWithLockdownServiceName:]_block_invoke)
14:52:05.882 testmanagerd[229:5828] Created session with socket 7
14:52:05.884 testmanagerd[229:5821] Handled a proxy request from the IDE with session <XCIDESession: 0x12d6098a0> proxy <_DTXProxy: 0x12d624980>
14:52:05.884 testmanagerd[229:5821] -[XCIDESession _IDE_initiateControlSessionForTestProcessID:protocolVersion:] 233 16
14:52:05.884 testmanagerd[229:5816] Set control session <XCIDESession: 0x12d6098a0> with proto 16 and proxy <_DTXProxy: 0x12d624980>
14:52:05.931 xcodebuild[33207:6314725] Got whitelisting response and daemon protocol version 16
14:52:05.699 XCTRunner[233:6055] Linked XCTest.framework from /var/containers/Bundle/Application/2DBD66A5-6F55-4A69-9F3C-E4CBCA33F0F2/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest, built at Tuesday 29 November 2016 at 14 h 52 min 01 s Eastern European Standard Time
14:52:05.699 XCTRunner[233:6055] Process arguments: (
    "/var/containers/Bundle/Application/2DBD66A5-6F55-4A69-9F3C-E4CBCA33F0F2/WebDriverAgentRunner-Runner.app/XCTRunner",
    "-NSTreatUnknownArgumentsAsOpen",
    NO,
    "-ApplePersistenceIgnoreState",
    YES
)
14:52:05.699 XCTRunner[233:6055] Process environment: {
    "CFFIXED_USER_HOME" = "/private/var/mobile/Containers/Data/Application/7E7F3610-99F9-48FC-BAC5-E2DFC6C178D5";
    "CFLOG_FORCE_STDERR" = YES;
    CLASSIC = 1;
    "DTX_CONNECTION_SERVICES_PATH" = "/Developer/Library/PrivateFrameworks/DTXConnectionServices.framework";
    "DYLD_FRAMEWORK_PATH" = "/private/var/containers/Bundle/Application/2DBD66A5-6F55-4A69-9F3C-E4CBCA33F0F2/WebDriverAgentRunner-Runner.app/Frameworks:/Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks";
    "DYLD_LIBRARY_PATH" = "/private/var/containers/Bundle/Application/2DBD66A5-6F55-4A69-9F3C-E4CBCA33F0F2/WebDriverAgentRunner-Runner.app/Frameworks:/Users/panagiotistsiakos/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks";
    FBSClientLogging = 0;
    HOME = "/private/var/mobile/Containers/Data/Application/7E7F3610-99F9-48FC-BAC5-E2DFC6C178D5";
    LOGNAME = mobile;
    NSUnbufferedIO = YES;
    "OBJC_DISABLE_GC" = YES;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin";
    SHELL = "/bin/sh";
    TMPDIR = "/private/var/mobile/Containers/Data/Application/7E7F3610-99F9-48FC-BAC5-E2DFC6C178D5/tmp";
    USER = mobile;
    "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
    XCTestConfigurationFilePath = "/private/var/mobile/Containers/Data/Application/7E7F3610-99F9-48FC-BAC5-E2DFC6C178D5/tmp/WebDriverAgentRunner-4754DC1F-187C-44CD-B04C-11183581293B.xctestconfiguration";
    "XPC_FLAGS" = 0x0;
    "XPC_SERVICE_NAME" = "UIKit...

**The following desired capabilities are also set:**

    <parameter name="realDeviceLogger" value="/usr/local/lib/node_modules/deviceconsole/deviceconsole"/>
    <parameter name="xcodeConfigFile" value="/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/driverAgent.xcconfig"/>

**Comment by jlipps** [comment]
Not sure what to say @ptsiakos77. On the Appium side everything looks correct. It appears that something about WDA is not working. Can you raise an issue at facebook/WebDriverAgent? I'll close this for now, and if we determine that Appium is doing something funny we can reopen.

**Comment by ptsiakos77** [comment]
@jlipps 
Not sure what to do with this. The strange think here is that the first time I run a test in a new device the test starts. Subsequent tests never start even if I remove the webdriver agent from the mobile device, restart the iphone or even restart my mac. I even reinstalled appium. I observed this behavior in 2 different devices so I don't think is coincidence.


Below is the feedback from the WebDriverAgent guys:

From your logs it looks like WDA booted property and is waiting for requests.
If you can't make request you should poke Appium guys probably there is something wrong with proxy.

**Comment by mykola-mokhnach** [comment]
@ptsiakos77 Are you able to physically access this URL http://10.9.43.244:8100 from the machine where your test is running?

**Comment by ptsiakos77** [comment]
@mykola-mokhnach 

{
  "value" : "Unhandled endpoint: \/ -- http:\/\/10.9.43.244:8100\/ with parameters {\n    wildcards =     (\n        \"\"\n    );\n}",
  "sessionId" : "D3E181C8-9970-476E-8545-4818A9A5FC4B",
  "status" : 1
}

this is the output

**Comment by mykola-mokhnach** [comment]
Yup, this means WDA is running and is awaiting for commands, but Appium does not query for anything

**Comment by ptsiakos77** [comment]
Yes because I would expect also this command to output something netstat -a | grep 10.9.43.244

where 10.9.43.244 is the ip of the mobile device

I also changed the wdaLocalPort capability to 8200 but no luck

**Comment by mykola-mokhnach** [comment]
@jlipps I suppose I know where the problem might be and why it happens for real device only.
There is an interesting code part in xctest driver:

```javascript
  async waitForStart (startTime) {
    // we have to wait for the sim to start before we can tail the log file
    if (!this.realDevice) {
      await systemLogExists(this.device);
    }

    let agentUrl;
    let lineCount = 0;
    let reachedEnd = !this.realDevice; // simulator does not need to wait, since we are tailing
    let showWaitingMessage = true; // turn off logging once we have hit the end

    let startDetector = (stdout) => {
      // on a real device there may already be system logs that need to be
      // passed before we get to the real startup logs, otherwise
      // we expect two lines, one after another
      //     Jul 20 13:03:57 iamPhone XCTRunner[296] <Warning>: Built at Jul 20 2016 13:03:50
      //     Jul 20 13:03:57 iamPhone XCTRunner[296] <Warning>: ServerURLHere->http://10.35.4.122:8100<-ServerURLHere
      if (!reachedEnd) {
        let dateMatch = REAL_DEVICE_BUILD_LOG_STARTTIME_REGEX.exec(stdout);
        if (dateMatch) {
          let buildTime = new Date(dateMatch[1]);
          if (buildTime.isAfter(startTime)) {
            reachedEnd = true;
          }
        }
      }

      if (reachedEnd) {
        let match = AGENT_STARTED_REGEX.exec(stdout);
        if (match) {
          agentUrl = match[1];
          log.info(`Detected that WebDriverAgent is running at url '${agentUrl}'`);
          if (!agentUrl) {
            log.errorAndThrow(new Error('No url detected from WebDriverAgent'));
          }
          showWaitingMessage = false;
          return true;
        }
      }

      // periodically log, so it does not look like everything died
      lineCount++;
      let threshold = this.realDevice ? 5000 : 200;
      if (showWaitingMessage && lineCount % threshold === 0) {
        log.debug('Waiting for WebDriverAgent server to finish loading...');
      }

      return false;
    };

    log.info('Waiting for WebDriverAgent to start on device');
    await this.deviceLogs.start(startDetector);
    log.info(`WebDriverAgent started at url '${agentUrl}'`);

    return agentUrl;
  }
```

and the most interesting stuff here is

```javascript
      if (!reachedEnd) {
        let dateMatch = REAL_DEVICE_BUILD_LOG_STARTTIME_REGEX.exec(stdout);
        if (dateMatch) {
          let buildTime = new Date(dateMatch[1]);
          if (buildTime.isAfter(startTime)) {
            reachedEnd = true;
          }
        }
```

which means, that if the date on the device under test differs from the local machine date then the test will wait forever (what, actually, happens).

**Comment by mykola-mokhnach** [comment]
I suppose it can be fixed if we set the most recent log record timestamp as _startTime_  variable value instead of setting it to the current local Date()

**Comment by ptsiakos77** [comment]
@mykola-mokhnach @jlipps 

Absolutely correct!!!!

Just  for debugging I made the method return always true and it worked like charm

 if (!reachedEnd) {
            reachedEnd = true;
        }

**Comment by Prakash-Saravanan** [comment]
@mykola-mokhnach Still facing the issue. Using appium 1.6.3.
The test fails throwing exception 

> An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: socket hang up

XCode log says 

> [Xcode] 2016-12-14 07:10:07.989 xcodebuild[49208:183246]  DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.WebDriverAgentRunner-Runner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running." UserInfo={NSLocalizedFailureReason=Too many instances of this service are already running., 

Other logs say

> [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.pearson.rrdev","arguments":[],"environment":{},"shouldWaitForQuiescence":true}}
> [debug] [XCUITest] Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: socket hang up

**Comment by crashbell** [comment]
@Prakash-Saravanan You might need to check your Activity Monitor, there must be some `xcodebuild` processes leaking out there.

**Comment by ybb8131225** [comment]
so, i still don't know how to do

**Comment by ybb8131225** [comment]
so , i stall don't know how to do , sometimes it can succeed ,sometiems can not succeed.

**Comment by wangtao169447** [comment]
i wonder where to change the func:

if (!reachedEnd) {
reachedEnd = true;
}

in which file?

**Comment by propaul** [comment]
I'm having issues finding object properties on a web application to run on my iOS devices.  I downlaoded Appium 1.6.3 and all my iOS devices are updated to 10.2.  I can run the script using Xpath on the iOS simulators but when i try to run script on real device it does not work.

I'm trying to use the Accessibility Inspector through Xcode but it seems it does not provide the object hierarchy. 
-Is anyone else facing similar issues?

**Comment by propaul** [comment]
This code works on the simulator but not iOS real device.  Does anyone know how to convert these codes using XCUIElement ?

driver.findElement(By.xpath("//*[@id='prod_drop']")).click();
	 driver.findElement(By.xpath("//*[@id='prod_drop']/option[2]")).click();
	 driver.findElement(By.xpath("//*[@id='puchase_input']")).sendKeys("250000");
	 driver.findElement(By.xpath("//*[@id='lnamount_input']")).sendKeys("200000");

**Comment by RonitJoardar** [comment]
I am also facing the same issue.
Working on Appium Desktop 1.6.4 beta
iOS- 10.2.1
OSX- 10.12

Any permanent solutions for this?
@imurchie @mykola-mokhnach

**Comment by imurchie** [comment]
The problem under discussion in this issue is no longer present, as the logic has completely changed.
