### ISSUE TITLE
Update android webview logic to only connect to active webviews

### ISSUE THREAD

**Issue by jvillacortam** [appium/appium#7314]
## The problem
ChromeDriver fails locating an element or sending javascript to a Webview when app is built with API Target 24.

## Environment
Appium version: 1.6.1, 1.6.0, 1.5.3
Chromedriver version: 2.25 - 2.21
Devices: Nexus 4 - 4.4.2 and Nexus 5 - 6.0

## Details
Driver seems to not access the correct webview or fails to identify the content.  Tried using several versions of Appium and ChromeDriver

If I do 

## Link to Appium logs
- API 23 (Successful) --> https://gist.github.com/jvillacortam/07a42aa4ae06ec3da686070bec1a3608
- API 24 (Fails) --> https://gist.github.com/jvillacortam/385e97ef31b64030a3181b7f1d3b1552

## Code To Reproduce Issue
Simplified code:
`contexts = [webview for webview in all_contexts if 'WEBVIEW' in webview]` --> ['NATIVE_APP', 'WEBVIEW_com.qa.unitytest']
`driver.switch_to.context('WEBVIEW_com.qa.unitytest')`
`driver.execute_script('success()')`

**Comment by jlipps** [comment]
Are you able to use latest chromedriver on its own (outside of Appium) to attach to your app?

**Comment by jvillacortam** [comment]
OK I did some tests running ChromeDriver directly (Without Appium) and using selenium as client.

There seems to be a difference on how the webview context are handled when the app is built against API 24.

Due to the nature of our app we have several webview instances but only one active and visible, on API 23 or below is sending only the active webview in the list when querying http://localhost:<port>/json:
```json
[ {
   "description": "{\"attached\":false,\"empty\":false,\"height\":1080,\"screenX\":0,\"screenY\":0,\"visible\":true,\"width\":1794}",
   "devtoolsFrontendUrl": "http://chrome-devtools-frontend.appspot.com/serve_rev/@0025f7fed6e0228b34d3adcb489a092ed7a72c0b/inspector.html?ws=localhost:12697/devtools/page/81560e2a-b8d4-4eec-b4ff-8a7f5b3e6e5b",
   "id": "81560e2a-b8d4-4eec-b4ff-8a7f5b3e6e5b",
   "title": "about:blank",
   "type": "page",
   "url": "about:blank",
   "webSocketDebuggerUrl": "ws://localhost:12697/devtools/page/81560e2a-b8d4-4eec-b4ff-8a7f5b3e6e5b"
} ]
```
API 24 returns:
```json
[ {
   "description": "{\"attached\":true,\"empty\":false,\"height\":1080,\"screenX\":0,\"screenY\":0,\"visible\":true,\"width\":1794}",
   "devtoolsFrontendUrl": "http://chrome-devtools-frontend.appspot.com/serve_rev/@0025f7fed6e0228b34d3adcb489a092ed7a72c0b/inspector.html?ws=localhost:12843/devtools/page/7607c63f-4798-4fb2-a2e0-61cfa4907503",
   "id": "7607c63f-4798-4fb2-a2e0-61cfa4907503",
   "title": "about:blank",
   "type": "page",
   "url": "about:blank",
   "webSocketDebuggerUrl": "ws://localhost:12843/devtools/page/7607c63f-4798-4fb2-a2e0-61cfa4907503"
}, {
   "description": "{\"attached\":false,\"empty\":true,\"screenX\":0,\"screenY\":0,\"visible\":true}",
   "devtoolsFrontendUrl": "http://chrome-devtools-frontend.appspot.com/serve_rev/@0025f7fed6e0228b34d3adcb489a092ed7a72c0b/inspector.html?ws=localhost:12843/devtools/page/8f133b40-4baf-4e88-9ab3-46f70ba3df44",
   "id": "8f133b40-4baf-4e88-9ab3-46f70ba3df44",
   "title": "Unity Ads WebView",
   "type": "page",
   "url": "about:blank",
   "webSocketDebuggerUrl": "ws://localhost:12843/devtools/page/8f133b40-4baf-4e88-9ab3-46f70ba3df44"
} ]
```

It looks like the last window is the one believed to be active so when I send a javascript command it cannot find the class as it is triggered to the incorrect webview.

**Comment by jvillacortam** [comment]
We should only be looking at "attached" windows to avoid this issue ("description": "{\"attached\":true...)

**Comment by jlipps** [comment]
@jvillacortam thanks for this research, that's very helpful. We may need to reconsider how we're finding the webviews (we're not using whatever tool it is that you did, I believe we're examining processes on the device using `ps`). I'll add this to our backlog to see if there's a way for us to find the attached window.

One thing I'm confused about, though: in the API 23 example, `attached` was `false`---should that webview be ignored?

**Comment by jvillacortam** [comment]
@jlipps I believe by mistake I got the webview list from ChromeDriver after the webview was closed for API 23, therefore showing as `attached:false`, this is returned for a few seconds after the webview is closed, possibly while the webview instance is still in memory.

The correct output for API 23 when the webview is visible and active is:
```json
[ {
   "description": "{\"attached\":true,\"empty\":false,\"height\":1776,\"screenX\":0,\"screenY\":0,\"visible\":true,\"width\":1080}",
   "id": "73ac821f-edd0-4507-bca3-09f25cb2faba",
   "title": "about:blank",
   "type": "page",
   "url": "about:blank"
} ]
```

To clarify the way I am interacting with ChromeDriver is through a selenium webdriver client:
```python
import time
from selenium import webdriver

capabilities = {
    'chromeOptions': {
        'androidPackage': 'com.qa.unitytest',
        'androidActivity': 'com.unity3d.player.UnityPlayerActivity'
    }
}
driver = webdriver.Remote('http://localhost:9515', capabilities)
time.sleep(10)
driver.execute_script('mraid.success()')
time.sleep(2) 
```
Once I run the script, I launch the desired webview and grab the endpoint for the session in the Chromedriver logs, then I query `<endpoint>/json` to get the webview list.

**Comment by jlipps** [comment]
I see. So once we start up chromedriver, we can query it for webviews first before starting a session. We'll have to try that. Thanks!

**Comment by khandelwalgarima** [comment]
I am seeing the same issue for api > 23.

**Comment by mykola-mokhnach** [comment]
Now Android driver has `ensureWebviewsHavePages` cap. If this cap is enabled then Appium will ask remote debugger if the corresponding web view has at least one page and will exclude this web view from the contexts list if there are none.
