### ISSUE TITLE
appium 1.6.1, ios 10.1.1 - real device - issue launching the app on real device

### ISSUE THREAD

**Issue by srk9ravi** [appium/appium#7315]
## The problem

below errors while running the appium..
Error: xcodebuild failed with code 70
Encountered internal error running command: Error: xcodebuild failed with code 70
[HTTP] <-- POST /wd/hub/session 500 68618 ms - 167

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.0
* Desktop OS/version used to run Appium: OS X EI Captain
* Mobile platform/version under test: 10.1.1
* Real device or emulator/simulator: real device

## Details

in 1.6.0 it used to work fine, and i updated it to 1.6.1 and facing this above error. find the attached screenshot from the webdriveragent of version conflict with xcode8. Eventhough xcode8 supports 10.1.1, it is showing that dailogue if i run using webdriveragent from xcode.
<img width="420" alt="screenshot at nov 29 11-51-50" src="https://cloud.githubusercontent.com/assets/8058405/20719612/7fb68d28-b62a-11e6-8b00-1704af32f9ab.png">

## Link to Appium logs
https://gist.github.com/srk9ravi/fbf298d6eabd29f936dae3813d0f6a4f

**Comment by jlipps** [comment]
@srk9ravi you're saying that this same test and same ios 10.1.1 device was working with appium 1.6.0, and now it's not with 1.6.1?

**Comment by srk9ravi** [comment]
@jlipps 
sorry, it is with 10.0 i remember.

**Comment by jlipps** [comment]
OK, it's probably just that we need to bring in a newer version of WDA that supports a newer xcode

**Comment by srk9ravi** [comment]
Sure, any expected ETA?

**Comment by jlipps** [comment]
Looking to get a new Appium release out sometime this week with an updated WDA, though I haven't been following WDA changes closely so I'm not sure if the changes that will be ready are the ones that will resolve this issue.

**Comment by srk9ravi** [comment]
@jlipps 
sure, thank you.
