### ISSUE TITLE
fix android CI

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7316]
Acceptance criteria:
* [ ] ensure functional tests can run in Android CI environment
* [ ] upgrade emulators to support latest version (or support multiple)
* [ ] look into Genymotion as they may be faster emulators

**Comment by jlipps** [comment]
cc @SrinivasanTarget

**Comment by jlipps** [comment]
oops, I mean cc @sravanmedarapu

**Comment by imurchie** [comment]
It seems that Cloudbees has axed its free tier, which is what we were using. Nothing is getting executed now.

**Comment by dpgraham** [comment]
Have we ever looked into CircleCI? They have a free tier for Linux:

https://circleci.com/pricing/

**Comment by dpgraham** [comment]
@imurchie @jlipps Is there anything left that needs to be done on this issue?

**Comment by imurchie** [comment]
I think we're good.
