### ISSUE TITLE
Android Coverage desired capability not working as expected

### ISSUE THREAD

**Issue by Prasant-Sutaria** [appium/appium#7317]
## The problem

We are following the following links to generate Android code coverage for our Android test:

http://appium.io/slate/en/v1.0.0/?java#android-coverage
https://github.com/appium/appium/blob/0.18.x/docs/en/android_coverage.md

We are passing "androidCoverage" desired capability:

capabilities.setCapability("androidCoverage","com.example.xyz.activitylearning/com.example.xyz.instrumentation.MyInstrumentation");

**Expected:** Appium to launch app in instrumented mode using following ADB command:

adb shell am instrument -e coverage true -w com.example.xyz.activitylearning/com.example.xyz.instrumentation.MyInstrumentation

**Actual:** Appium is launching in normal mode

["-P",5037,"-s","emulator-5554","shell","am","start","-n","com.example.e880579.activitylearning/com.example.e880579.activitylearning.SplashScreenActivity","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3 (Ara)
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: OS X El Capitan Version 10.11.2
* Node.js version (unless using Appium.app|exe): Appium.app
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs

https://gist.github.com/Prasant-Sutaria/caa16878b6df34307a452f3e3b251838

**Comment by Prasant-Sutaria** [comment]
Hi Team,

Any update/pointer is appreciated.

**Comment by jlipps** [comment]
I've added this to our backlog to take a look. Unfortunately I don't have any guidance at this point.

**Comment by jlipps** [comment]
I did a brief investigation into this. It looks like we may have simply failed to copy over the instrumentation starting code conditional to the androidCoverage cap. I think it should be an easy fix to add that back in. Bumping this in our backlog.

**Comment by shashankjhs** [comment]
Hi @jlipps / @Prasant-Sutaria ,
Any appium version with which 'androidCoverage' capabilities worked or suppose to work?

Any Clue ...!!!!!

**Comment by jonathong** [comment]
Does anyone know if producing coverage files with Appium is possible?  If so, are there any good resources you can suggest?

**Comment by MorganDream** [comment]
@jlipps What is the status of this bug fix? Does Appium team has a plan to fix this issue? I really want to use this capability and I'm stuck by this problem.

**Comment by Sw0rdstream** [comment]
@Prasant-Sutaria @jlipps 
I plan to use this fix to open the instrumentation capability of appium-uiautomator2-driver.

If this fix can be merged, what you need to do is:
[1] set `androidCoverage` as {package}/{instrumentation class}, as same required in old doc.
[2] set `appWaitActivity` as your instrument activity. (This instrument activity is launched in your `MyInstrumentation`)
[3] set `appWaitPackage` as {package}
[4] set `androidCoverageEndIntent` as a singal broadcast intent to dump coverage to file. (For example, in the example of https://github.com/appium/appium/blob/0.18.x/docs/en/android_coverage.md, the intent should be `com.example.pkg.END_EMMA`.

However, adding a new cap  `androidCoverageEndIntent`  seems a little bit tricky. Maybe it is not appium but user's own responsibility to send this intent for dumping coverage data to file.

**Comment by jonathong** [comment]
Could you give a few more details?  You mean that by following these steps we can have code coverage working now?  Will it work for Jacoco? Also, could you provide a link to the old doc you are referring to?  Thanks for the help, I have been trying to get code coverage to work for a while now.

**Comment by jlipps** [comment]
sounds good @Sw0rdstream, we await your addition to the docs so this can be clear to everyone!

**Comment by Sw0rdstream** [comment]
@jonathong https://github.com/Sw0rdstream/appium/blob/6f11ede8df88d99ef90bc2776b8e9e26f7329242/docs/en/writing-running-appium/android_coverage.md 
Can you check this PR's documentation? Hope it can help you.

**Comment by jlipps** [comment]
@Sw0rdstream's documentation resolves this issue and should be merged soon.
