### ISSUE TITLE
Appium 1.6.1, Xcode 8, platformVersion 10.1 doesn't install app 

### ISSUE THREAD

**Issue by davidrova** [appium/appium#7318]
## The problem

I have upgrade my ios app to xcode 8 and upgrade Appium to 1.6.1.
Appium is not able to install the app (I suppose).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: iOS Sierra
* Node.js version (unless using Appium.app|exe): v6.2.2
* Mobile platform/version under test: iPhone 5s
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: cli

## Details
N/A

## Link to Appium logs

[appium logs](https://gist.github.com/davidrova/731397e989c53cfc4b380bda59278b28).

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by davidrova** [comment]
I have identified the problem.

You cannot start appium with sudo. My first try was without sudo and there was a "not allowed access", so I change to sudo. FAIL

Solution:
- Change owner under my user directory (sudo chown -R user:group /Users/user
- Start appium WITHOUT sudo
- Start my testing project

**Comment by jlipps** [comment]
Thanks, @davidrova. Yes, sudo is not recommended.
