### ISSUE TITLE
problem about Xcodebuild failed with code 65.

### ISSUE THREAD

**Issue by qkjs** [appium/appium#7320]
## The problem
I can't run test on ios beacue the err "Xcodebuild failed with code 65."

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac 10.12.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.1.1
* Real device or emulator/simulator:Real device  and simulator
* Appium CLI or Appium.app|exe: Appium CLI
* Xcode 8.1

## Details
I try to run my automation test on iOS using Mac. but I meet an err "Xcodebuild failed with code 65."
I read a lot blog about this issue. but no one can help me fix this problem.
So I add my scrip as follow. anybody can help me fix this problem.
By the way, the app can run as developer mode in read device using xcode 8. But I using appium for automation, the err will be occurs.

if you have any details, please let me know.

## Code To Reproduce Issue
**TestScrip for Python:**

import unittest
import os
from random import randint
from appium import webdriver
from time import sleep

class SimpleIOSTests(unittest.TestCase):

    def setUp(self):
        # set up appium
        app = os.path.abspath('/Users/bernie/Library/Developer/Xcode/DerivedData/TestApp-cwseioecpjrniqendxgilnjxsonw/Build/Products/Debug-iphoneos/TestApp.app')
        self.driver = webdriver.Remote(
            command_executor='http://127.0.0.1:4723/wd/hub',
            desired_capabilities={
                'app': app,
                'platformName': 'iOS',
                'platformVersion': '10.1.1',
                'deviceName': 'iPhone 6',
                'xcodeConfigFile' : '/usr/local/lib/node_modules/appium/node_modules/.2.2.0@appium-xcuitest-driver/WebDriverAgent/xcodeConfigFile.xcconfig',
                'udid': 'a92f6a26d7c1------bae135b4c2352e52a18dd8'
            })

    def tearDown(self):
        self.driver.quit()

    def test_scroll(self):
        els = self.driver.find_elements_by_class_name('UIAButton')
        els[5].click()

if __name__ == '__main__':
     suite = unittest.TestLoader().loadTestsFromTestCase(SimpleIOSTests)
     unittest.TextTestRunner(verbosity=2).run(suite)

**Script for xcodeConfigFile**
  DEVELOPMENT_TEAM = WAG---C4YA
  CODE_SIGN_IDENTITY = iPhone Developer

**Comment by levyshachar2** [comment]
i had a similar issue , i got my working by adding to my capabilities the following

capabilities.setCapability("realDeviceLogger","/usr/local/lib/node_modules/deviceconsole/deviceconsole");

**Comment by qkjs** [comment]
I am very glad to comment this. I had been fixed this problem.  the reason is one framework missing. I using bootstrap.sh -d re-download the framework. 
thanks everyone.
