### ISSUE TITLE
Appium Settings application crashes on Android

### ISSUE THREAD

**Issue by jeangb** [appium/appium#7321]
## The problem

The "Appium Settings" application crashes each time I try to launch it.
I noticed that when I was trying to understang why the driver.setConnection(Connection.NONE) doesn't work anymore.
I rebooted my device, uninstalled Appium Settings, updated Appium Server but that didn't change a thing. 

## Environment

* Appium version : 1.6.1
* Last Appium version that did not exhibit the issue (if applicable): I don't remember, it was before 1.5.
* Desktop OS/version used to run Appium: windows 7 64bit
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: Android 4.4.2
* Real device or emulator/simulator: real (Galaxy S4)
* Appium CLI or Appium.app|exe:

## Details

When I launch Appium Settings on my device, it instantanly crashes. "Unfortunately, Appium Settings has stopped".
 I guess this related with the fact that I can't anymore change the connection status of my device ?

**Comment by jlipps** [comment]
What does logcat say? Any info about why Appium Settings crashed?

**Comment by jeangb** [comment]
@jlipps hey, here's what logcat says ;

```
V/SmartFaceService - 3rd party pause(  844): onReceive [android.intent.action.ACTIVITY_STATE/io.appium.settings/create]
D/STATUSBAR-NetworkController( 1225): refreshSignalCluster: data=-1 bt=false
D/STATUSBAR-IconMerger( 1225): checkOverflow(648), More:false, Req:false Child:7
E/AndroidRuntime( 1898): FATAL EXCEPTION: main
E/AndroidRuntime( 1898): Process: io.appium.settings, PID: 1898
E/AndroidRuntime( 1898): java.lang.RuntimeException: Unable to start activity ComponentInfo{io.appium.settings/io.appium.settings.Settings}: java.lang.NullPointerException
E/AndroidRuntime( 1898): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
E/AndroidRuntime( 1898): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
E/AndroidRuntime( 1898): 	at android.app.ActivityThread.access$900(ActivityThread.java:161)
E/AndroidRuntime( 1898): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
E/AndroidRuntime( 1898): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1898): 	at android.os.Looper.loop(Looper.java:157)
E/AndroidRuntime( 1898): 	at android.app.ActivityThread.main(ActivityThread.java:5356)
E/AndroidRuntime( 1898): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1898): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1898): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
E/AndroidRuntime( 1898): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
E/AndroidRuntime( 1898): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1898): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 1898): 	at io.appium.settings.Settings.onCreate(Settings.java:42)
E/AndroidRuntime( 1898): 	at android.app.Activity.performCreate(Activity.java:5426)
E/AndroidRuntime( 1898): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/AndroidRuntime( 1898): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
E/AndroidRuntime( 1898): 	... 11 more
W/ActivityManager(  844):   Force finishing activity io.appium.settings/.Settings
W/ContextImpl(  844): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1478 com.android.server.am.ActivityStack.startPausingLocked:1006 com.android.server.am.ActivityStack.finishActivityLocked:3162 com.android.server.am.ActivityStack.finishTopRunningActivityLocked:3005 com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked:3071 
V/SmartFaceService - 3rd party pause(  844): onReceive [android.intent.action.ACTIVITY_STATE/io.appium.settings/pause]
D/STATUSBAR-StatusBarManagerService(  844): manageDisableList what=0x0 pkg=WindowManager.LayoutParams
W/ContextImpl(  844): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1478 com.android.server.analytics.data.collection.application.CrashAnrDetector.broadcastEvent:296 com.android.server.analytics.data.collection.application.CrashAnrDetector.processDropBoxEntry:254 com.android.server.analytics.data.collection.application.CrashAnrDetector.access$100:60 com.android.server.analytics.data.collection.application.CrashAnrDetector$1.onReceive:102 
V/WindowManager(  844): rotationForOrientationLw(orient=1, last=0); user=0  sensorRotation=-1 mLidState=-1 mDockMode=0 mHdmiPlugged=false mAccelerometerDefault=false gripRotationLock=false
W/ContextImpl(  844): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1478 com.android.s 
```

You can find the full log here if you want 
[logs_galaxy_s4_crash_appiumsettings.txt](https://github.com/appium/appium/files/624075/logs_galaxy_s4_crash_appiumsettings.txt)

**Comment by jlipps** [comment]
OK, this might indeed be a bug in that settings app. Can you reproduce it on any other android versions or anything but a Galaxy S4?

**Comment by jeangb** [comment]
Yes it crashes on a Galaxy S3 to (I think it's the same android version).

**Comment by jeangb** [comment]
Hi, do you have some news on this ?
Regards

**Comment by jeangb** [comment]
Hey @jlipps have you been able to reproduce it ?

**Comment by jlipps** [comment]
No, we haven't had a chance to look at it yet, but it is in our backlog.

**Comment by jeangb** [comment]
Ok thank you !

**Comment by appiumnovice** [comment]
Hi,
I have the same problem with Android 4.2.2 on Wiko Rainbow.

Appium version : 1.6.3
Last Appium version that did not exhibit the issue: 1.5.3
Desktop OS/version used to run Appium: OSX 10.11.6
Mobile platform/version under test: Android 4.4.2
Real device or emulator/simulator: real (Wiko Rainbow)
Appium CLI

**Comment by paniego** [comment]
Hi,
I have the same problem with Android 7
Appium version : 1.6.3
Last Appium version that did not exhibit the issue: It has so far not worked with Android 7 device
Desktop OS/version used to run Appium: OSX 10.11.6

I detected the problem when trying to manually install and start the Appium Settings app, after i was getting all the time the error below, when i would try to start my app in my automatic tests (implemented with Robot Framework using AppiumLibrary):
\io.appium.settings\bin\settings_apk-debug.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package io.appium.settings signatures do not match the previously installed version; ignoring!]'; Code: '1'

It seems to be working fine on an Android 5.1 device though

**Comment by egorvas** [comment]
Same problem with my galaxy S7 and Moto Droid X. Issue really need to be fixed.

**Comment by SrinivasanTarget** [comment]
+1

**Comment by cpfontan** [comment]
+1

**Comment by ChanielYu** [comment]
+1

**Comment by mustafahmalik** [comment]
+1

**Comment by amiteshri92** [comment]
+1

**Comment by amiteshri92** [comment]
Has anyone found any solution for it?

**Comment by egorvas** [comment]
@amiteshri92 are you using latest appium version? In appium settings 2.1 version its already fixed

**Comment by amiteshri92** [comment]
ohk, I am using 1.5.3 currently.

**Comment by fdPoornima** [comment]
+1 on Galaxy Tab
Android Version : 7
Appium version :1.7

**Comment by imurchie** [comment]
@fdPoornima Can you provide the stacktrace from the device logs? We would like to track this issue down but cannot reproduce.

**Comment by fdPoornima** [comment]
@imurchie ,pfa
[Logs_AppiumSettings.txt](https://github.com/appium/appium/files/1320920/Logs_AppiumSettings.txt)

**Comment by imurchie** [comment]
Relevant stack:
```
E/AndroidRuntime( 5526): Process: io.appium.settings, PID: 5526
E/AndroidRuntime( 5526): java.lang.RuntimeException: Unable to start activity ComponentInfo{io.appium.settings/io.appium.settings.Settings}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set android.os.Bundle.keySet()' on a null object reference
E/AndroidRuntime( 5526): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3151)
E/AndroidRuntime( 5526): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261)
E/AndroidRuntime( 5526): 	at android.app.ActivityThread.access$1000(ActivityThread.java:219)
E/AndroidRuntime( 5526): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1735)
E/AndroidRuntime( 5526): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5526): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime( 5526): 	at android.app.ActivityThread.main(ActivityThread.java:6939)
E/AndroidRuntime( 5526): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5526): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5526): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime( 5526): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
E/AndroidRuntime( 5526): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set android.os.Bundle.keySet()' on a null object reference
E/AndroidRuntime( 5526): 	at io.appium.settings.Settings.onCreate(Settings.java:42)
E/AndroidRuntime( 5526): 	at android.app.Activity.performCreate(Activity.java:6609)
E/AndroidRuntime( 5526): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
E/AndroidRuntime( 5526): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3104)
E/AndroidRuntime( 5526): 	... 10 more
D/InputDispatcher(  743): Focused application set to: xxxx
W/ActivityManager(  743):   Force finishing activity 1 io.appium.settings/.Settings
D/FocusedStackFrame(  743): Set to : 0
I/ActivityManager(  743): Skip updateThumbnail for r=ActivityRecord{13ac078a u0 io.appium.settings/.Settings t3 f}
```

This should fix the issue: https://github.com/appium/appium-android-driver/pull/272

**Comment by mekxtari** [comment]
How can i get this fix for appium 1.7.0? Should i use beta?

**Comment by shabana-parveen** [comment]
Me also facing the same issue with version 1.7.0

**Comment by saikrishna321** [comment]
you need to update appium to beta 

npm install -g appium@beta

**Comment by mekxtari** [comment]
Thanks @saikrishna321 !

**Comment by shabana-parveen** [comment]
Getting below error:

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@1.7.0" "beta"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! path /usr/local/lib/node_modules/.staging/node-pre-gyp-0a7c6790
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/node-pre-gyp-0a7c6790' -> '/usr/local/lib/node_modules/appium/node_modules/fsevents/node_modules/node-pre-gyp'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/node-pre-gyp-0a7c6790' -> '/usr/local/lib/node_modules/appium/node_modules/fsevents/node_modules/node-pre-gyp'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by amitrparmar** [comment]
I'm also facing the same issue.

Appium V. - 1.7.2
Device: Nexus 7
Android: 5.1.1

Same issue doesn't occur where Android v. is 6.0.1.

**Comment by amitrparmar** [comment]
After FACTORY reset, I didn't get this issue. It seems, it gone 👍
