### ISSUE TITLE
Test Script Execution for iOS Native App takes too long time using Appium 1.6.1 Beta

### ISSUE THREAD

**Issue by dilsreccse** [appium/appium#7322]
## The problem
We migrated our scripts to support the newer version of Appium 1.6.1 beta to support iOS 10. When we did a dry run for the migrated  IOS 10 test scripts, Test execution went more than 2 days, previously the execution time was only 16 to 17 hours.  
we changed the uia elements to relative xpath elements. we could find that WDA is taking too long time to identify the xpath element and WebElement Lists. How can we reduce the execution time ?

## Environment
* Appium version (or git revision) that exhibits the issue: 1.6.1 beta
* Last Appium version that did not exhibit the issue (if applicable): 1.4.3
* Desktop OS/version used to run Appium: MAC
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10 version 10.0.1
* Real device or emulator/simulator: Real 
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by mykola-mokhnach** [comment]
Wait for Appium 1.6.2 release or merge the recent WDA release from https://github.com/facebook/WebDriverAgent repository manually

**Comment by mykola-mokhnach** [comment]
Or don't use xpath locators ;)

**Comment by dilsreccse** [comment]
@mykola-mokhnach we are using the recent WDA Version 2.37 , what are the alternate ways that we can use to handle list elements?  when Appium 1.6.2 will be launched, any idea about it?

**Comment by mykola-mokhnach** [comment]
I'm talking about WDA sources rather than the version of appium-xcuitest-driver component. You need to clone driver sources from the given repository and put them manually into 

```
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
```

**Comment by jlipps** [comment]
1.6.2 will be out in the next 48 hours though, so it may be easier just to wait.

**Comment by dilsreccse** [comment]
thanks @jlipps :)
