### ISSUE TITLE
UnhandledPromiseRejectionWarning after upgrading to node v7.2.0

### ISSUE THREAD

**Issue by JaniJegoroff** [appium/appium#7324]
## The problem

After upgrade from `node v5.1.1` to `node v7.2.0` I started to see following error in the console:
```
(node:16198) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Can't stop process; it's not currently running
(node:16198) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
```
Janis-MacBook-Pro:bdd janijegoroff$ bundle e rake ios
About to execute: node node_modules/appium -a localhost -p 4723 --log-level error
Waiting for the Appium server to boot up
Waiting for the Appium server to boot up
Waiting for the Appium server to boot up
About to execute: cucumber APPIUM_SERVER_URL=http://localhost:4723 -p ios -p launch
About to boot up mock server at: http://127.0.0.1:9999
Waiting for mock backend
Puma starting in single mode...
* Version 3.6.0 (ruby 2.2.5-p319), codename: Sleepy Sunday Serenity
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:9999
Use Ctrl-C to stop
Mock server up and running
Using the ios, launch, default_flags, default_tags, skip_offline and skip_android profiles...
Feature: example

  Background:                   # features/launch.feature:4
    Given I am on launch screen # features/step_definitions/common_steps.rb:1

  Scenario: already registered and have a card            # features/launch.feature:8
    When I have a card                                    # features/step_definitions/launch_steps.rb:1
    Then I should be taken to the login screen            # features/step_definitions/launch_steps.rb:9

(node:16198) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Can't stop process; it's not currently running
(node:16198) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

In spite of that tests are running fine.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.0-beta
* Desktop OS/version used to run Appium: Mac OS X Sierra 10.12.1
* Node.js version (unless using Appium.app|exe): v7.2.0
* Mobile platform/version under test: iOS 10
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by jlipps** [comment]
Thanks for the report @JaniJegoroff. I've seen this too. It shouldn't affect your tests but I've added it to our backlog so we can ensure the message goes away.

**Comment by jlipps** [comment]
AC:
* [ ] add process handler to get stack traces for unhandled rejections
* [ ] ensure no unhandled rejection warnings in top-level driver test suites

**Comment by imurchie** [comment]
I did a little experimentation on this one. It seems that if promises are rejected by throwing an exception, in Node 7, we get the warning no matter if we `await` the promise or not.

The following works fine:

```js
let p = new B(async (resolve, reject) => {
  reject(new Error('oops'));
});
await p;
```

And the following emits the deprecation warning:

```js
let p = new B(async (resolve, reject) => {
  throw new Error('oops');
});
await p;
```

**Comment by jlipps** [comment]
@imurchie in your second example, I think there _is_ an unhandled rejection. Consider what you have:

```js
new B(async (resolve, reject) => {
```

vs what I would argue is the more standard:

```js
new B((resolve, reject) => {
```

I.e., in the first case, an error thrown is thrown inside the promise returned by calling the _async_ function. This promise is never `await`ed---only the wrapping promise is. So it's true that it's not handled.

Moral of the story for us should probably be: never define a promise using `async` functions?

**Comment by jlipps** [comment]
(Or if we do, make sure we try/catch everything on the inside and call `reject`)

**Comment by imurchie** [comment]
Hmph. You're right.

**Comment by jlipps** [comment]
I ran a search in my directory that has all the appium code (not guaranteed to be latest master or include all repos):

```
~/C/appium ❯❯❯ ag "new \w\(async"
appium-instruments/lib/instruments.js
355:    return new B(async (resolve) => {

appium-ios-simulator/lib/tail-until.js
18:  return new B(async (resolve, reject) => {

appium-webdriveragent-driver/lib/webdriveragent.js
43:    return new B(async (resolve, reject) => {

appium-xcuitest-driver/lib/webdriveragent.js
328:    return await new B(async (resolve, reject) => {
415:    return await new B(async (resolve, reject) => {
```

So we definitely do this in a few places

**Comment by imurchie** [comment]
The sim one definitely causes the warning on my system. That was where I copied my code from. :|

**Comment by jlipps** [comment]
For the instances in xcuitest-driver, I think we could fix them by simply expanding the `try` block to include the whole function body (with maybe a comment to explain why). It does seem useful to be able to do this. Or we could try a new pattern:

```js
    return await new B(async (resolve, reject) => {
      this.iproxy.on('exit', (code) => {
        log.warn(`iproxy exited with code '${code}'`);
        if (code) {
          return reject(new Error(`iproxy exited with code '${code}'`));
        }
      });
      this.iproxy.on('output', (stdout, stderr) => {
        let out = stdout || stderr;
        for (let line of out.split('\n')) {
          if (!line.length) continue;
          iproxyLog.debug(line);
        }
      });

      try {
        await this.iproxy.start(5000);
        resolve();
      } catch (err) {
        log.error(`Error starting iproxy: '${err.message}'`);
        reject('Unable to start iproxy. Is it installed?');
      }
    });
```

**Comment by jlipps** [comment]
For the instances in xcuitest-driver, I think we could fix them by simply expanding the `try` block to include the whole function body (with maybe a comment to explain why). It does seem useful to be able to do this. Or we could try a new pattern:

```js
    return await new B((resolve, reject) => {
      return await (async () => {
        // inner code, which we are now properly awaiting
      })();
    });
```

**Comment by jlipps** [comment]
Oops, that's not correct, should be:

```js
return await new B((resolve, reject) => {
  return (async () => {
    // inner code, which we are now properly awaiting
  })();
});
```

Need to return the promise, not await it since we're not in an async fn at that point.

**Comment by imurchie** [comment]
With recent changed to the remote debugger, I'm now getting through our entire suite without a warning!
