### ISSUE TITLE
Identifying elements with out accessibility identifier

### ISSUE THREAD

**Issue by srkannan** [appium/appium#7327]
## The problem

There are some elements with out accessibility identifier. In this case using index is not working

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.1-beta
* Mobile platform/version under test:iOS 10.1.1
* Real device or emulator/simulator:iPad real device

## Details

\<XCUIElementTypeTextField name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0/0/1/0/0/0/16/2" x="243" y="184" width="538" height="44">
</XCUIElementTypeTextField\>
For the above XCUIElementTypeTextField there is no identifier if I use "//XCUIElementTypeTextField[@index='0']" it still does not identify.

**Comment by mykola-mokhnach** [comment]
Your xpath is incorrect. There is no _index_ attribute defined for the XCUIElementTypeTextField  xml node

**Comment by srkannan** [comment]
Please suggest me an alternative to use if not the index

**Comment by JaniJegoroff** [comment]
Why not simply add accessibility identifier or finding elements by class name.

Something like this in Ruby
```ruby
find_element(class_name: 'XCUIElementTypeTextField')
find_elements(class_name: 'XCUIElementTypeTextField')
```
