### ISSUE TITLE
Appium 1.6.1 (beta) does not respond correctly to SIGINT or SIGTERM when it is running in a Selenium GRID

### ISSUE THREAD

**Issue by henrymclay** [appium/appium#7328]
(First of all, thank you Appium community for all the help and hard work keeping things running!) 

## The problem

When opened from the command line with options to register to a Selenium GRID (rather than a standalone server), Appium 1.6.1 beta does not exit when it receives a SIGINT or SIGTERM command. 

## Environment

* Appium version (or git revision) that exhibits the issue: Appium v1.6.1-beta
* Last Appium version that did not exhibit the issue (if applicable): v1.6.0
* Desktop OS/version used to run Appium: macOS El Capitan
* Node.js version (unless using Appium.app|exe): 6.7.0
* Mobile platform/version under test: N/A
* Real device or emulator/simulator: N/A
* Appium CLI or Appium.app|exe: CLI

## Details

Running in to an error similar to https://github.com/appium/appium/issues/7265, I updated my appium with the command: 

```
npm uninstall -g appium && npm install -g appium@beta
```

That part worked, and I'm on the new version with a standalone instance opening and closing normally.

However, on the instances I have registered to a Selenium GRID, the server starts normally and registers properly, but closing with CTRL+C or sending a SIGTERM with ```kill [process]``` does not work: I get a message saying ``` ^C[Appium] Received SIGINT - shutting down```, but it continues to communicate with GRID normally and I need to send a ```kill -9 [process]``` to stop it... which is new. 

## Link to Appium logs

https://gist.github.com/henrymclay/c77c6f1aca12714a748ddf71a99b816e

(the registration errors are before I started the GRID - which is selenium-server-standalone-3.0.1.jar)

## Code To Reproduce Issue [ Good To Have ]

Set up a Selenium GRID and launch an Appium server registered there, then attempt to exit with ^C or ```kill [process]```

**Comment by jlipps** [comment]
Hmm, that's really odd. Not sure what we could have done to change signal handling. We'll look into it.

**Comment by appiumnovice** [comment]
Same pb for me on Appium 1.6.1 (not beta).

**Comment by jlipps** [comment]
This is most likely due to changes introduced by https://github.com/appium/appium/pull/7015. It sounds like we'll need to re-evaluate that use case and maybe come up with a different approach.

**Comment by tfcardoso** [comment]
Migrating tests to 1.6.3 and this is happening to me. Kind of annoying when developing new tests :)

**Comment by jlipps** [comment]
I agree @tfcardoso. We have this prioritized in our backlog so it should be fixed in a sprint or two.

**Comment by rahulmr** [comment]
Hello All, is it possible to know which version it was working fine? I was trying 1.5.3 but getting same issue.

**Comment by tfcardoso** [comment]
@rahulmr I had 1.5.3 for long time and never encounter this problem

**Comment by jmehtaebates** [comment]
I see similar issue in Appium 1.6.3 when I try to stop the appium server via Ctrl+c

```

[Appium] Received SIGINT - shutting down
^C[Appium] Received SIGINT - shutting down
^C[Appium] Received SIGINT - shutting down
^C[Appium] Received SIGINT - shutting down
^C[Appium] Received SIGINT - shutting down


```

At this point terminating the process is the only way to stop the server.

**Comment by jmehtaebates** [comment]
Also there is this issue with catch signals #7644

**Comment by jmehtaebates** [comment]
#7644

**Comment by jmehtaebates** [comment]
Do we have any update on this?

**Comment by Mikulasi** [comment]
So, how to fix it? Anyone knows?

**Comment by imurchie** [comment]
Up[pgrade to 1.6.4-beta.

**Comment by mykola-mokhnach** [comment]
closing the issue as fixed

**Comment by mroien** [comment]
I upgraded to 1.6.4-beta, but getting the same issue.
```
[Appium] Welcome to Appium v1.6.4-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Received SIGTERM - shutting down
```

**Comment by gastonci** [comment]
This issue still occurs on 1.6.5
