### ISSUE TITLE
sendkey language :English but actually languge : Korean

### ISSUE THREAD

**Issue by dmlch123** [appium/appium#7332]
## The problem

sendkey language :English but actually language : Korean

## Environment

nodejs v6.9.1
appium v1.6.0
android v6.0

**Comment by jlipps** [comment]
Please submit your appium logs. In any case, there is no language facility in the sendKeys function, so if anything you may be experiencing a client library error rather than an appium error

**Comment by dmlch123** [comment]
Found the cause of the problem. Language problem, according to the keyboard. 
Thank you.
