### ISSUE TITLE
Appium iOS Wrongly Clicks Element

### ISSUE THREAD

**Issue by raymondlapak** [appium/appium#7333]
## The problem

Clicking the button used to work. But today I updated my Appium and it stopped working. Appium iOS seems to wrongly clicks another element. I tried to click a button named "Lihat estimasi biaya pengiriman" as it is shown in the structure below. 

<img width="1198" alt="pengiriman" src="https://cloud.githubusercontent.com/assets/21168984/20787620/7c0b8e6a-b7df-11e6-92ab-3dc01ff21e0f.png">

The element is found by appium but when the element is  tapped it clicks another button named "Back" instead. 

<img width="1204" alt="back" src="https://cloud.githubusercontent.com/assets/21168984/20787627/805f0122-b7df-11e6-99a5-dc0339d25a6f.png">

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6.0-beta3 and Appium 1.6.1 above
* Last Appium version that did not exhibit the issue (if applicable): Appium 1.6.0-beta3 from October
* Desktop OS/version used to run Appium: Mac OSX

**Comment by mykola-mokhnach** [comment]
How do you identify the button? Having code snippet would be ok.

**Comment by raymondlapak** [comment]
@mykola-mokhnach  thanks

```
String buttonEstimasiLocator = "//XCUIElementTypeStaticText[contains(@name,'Estimasi Pengiriman')]/preceding-sibling::XCUIElementTypeButton"; 
IOSElement buttonElement = waitForElementPresent(buttonEstimasiLocator, 10);
Thread.sleep(4000);
buttonElement.tap(1, 1);
```

**Comment by mykola-mokhnach** [comment]
Why so complicated? The button has name, so you can just do

```
driver.findElement(MobileBy.AccessibilityId("Lihat estimasi biaya pengiriman")).click()
```

**Comment by raymondlapak** [comment]
@mykola-mokhnach In other occasions the button will already be filled with another string, so we have to figure out how to find the element dynamically. Hence the rather complicated XPath. 

I already tried the `driver.findElement(MobileBy.AccessibilityId("Lihat estimasi biaya pengiriman")).click();` as expected, it cannot find the element.

I already tried to find the element `By.name`as well, but the result is still the same, clicking the other element I mentioned above. It seems like instead of clicking the particular element, it just clicks the first element on the page.

**Comment by mykola-mokhnach** [comment]
What if you get button coordinates and then just tap directly by coordinates?

**Comment by raymondlapak** [comment]
@mykola-mokhnach I already managed to get the x and y of the element. Now the question is which method I have to use to click on those coordinates?

Is it the `driver.tap(args)` ?

**Comment by mykola-mokhnach** [comment]
I cannot help here, since we don't use any _tap_ or _TouchAction_ methods invocations in our test framework, but rather direct WDA API calls. They are at least stable and reliable.

**Comment by raymondlapak** [comment]
@mykola-mokhnach May you give example on how do I made such WDA API calls? Will be much appreciated. Thanks

**Comment by mykola-mokhnach** [comment]
https://github.com/facebook/WebDriverAgent/wiki/Queries 
WDA itself is usually running at http://localhost:8100 for Appium tests.

**Comment by jlipps** [comment]
Looks like WDA's xpath parsing is not up to the challenge of that weird xpath query you're using. I'd recommend a different query type as @mykola-mokhnach has mentioned.

I'd also recommend against using WDA directly. If there's something WDA does that's not supported by Appium, we should just support it in Appium instead.
