### ISSUE TITLE
Signing for WebDriverAgentRunner requires a development team. for IOS 10 with Appium

### ISSUE THREAD

**Issue by amar143** [appium/appium#7334]
## The problem

Facing problem with Appium in IOS 10, When trying to load the application, applium is throwing the exception saying like Singing for webDriverAgentRunner requires Developement team.

Code signing is required for product type UI Testing Bundle in SDK IOS 10.2
## Environment
Appium Version using 1.6.0
node version using 6.9.1

Testing with Real Device IPAD with version 10.2
## Details

When trying to load any application with real device in IOS 10.2 IPAD, it is giving code signing issue for WebDriverAgentRunner

**Comment by amar143** [comment]
Hi We have already mapped the code signing with developer id.But still this issue is showing like that .

**Comment by amar143** [comment]
please let me know the proper settings as to be done from xcode for working with Code Signing issue.

**Comment by asnaith** [comment]
@amar143 see my comment on https://github.com/appium/appium-xcuitest-driver/issues/316

If you follow those steps exactly you should have no problem with the webDriverAgent

**Comment by ShayTaub** [comment]
@asnaith 

Hi, I am unable to access the link you have just provided and I am receiving the same error.
Thanks in advance.
