### ISSUE TITLE
Script running properly on old Mac OS(10.10) but i have got an error on latest Mac OS(10.12.1).

### ISSUE THREAD

**Issue by vpkhachane** [appium/appium#7335]
My Script running properly on old mac os version 10.10 but it is not working on latest mac os 10.12.1

## Environment

* Appium version  1.5
* Desktop OS/version used to run Appium: MAC OS
* Node.js version (unless using Appium.app|exe): 6.8.1
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Both
* Appium CLI or Appium.app|exe:

 Please refer attachment . I have got this error.  How to fic it?

![screen shot 2016-11-30 at 3 41 20 pm](https://cloud.githubusercontent.com/assets/15686482/20792720/5f33ae4e-b7e9-11e6-90fd-aa6a52f431c4.png)

**Comment by vikramvi** [comment]
@vpkhachane can you fill the details as well in issue tracker , without that it's not possible to find out root cause of issue.

**Comment by imurchie** [comment]
This has been fixed.
