### ISSUE TITLE
XPath contains is not working correctly after the upgrade to Appium 1.6.1Beta

### ISSUE THREAD

**Issue by jtappi** [appium/appium#7336]
## The problem

I am in the process of updating my XPath to search for XCUI elements.  When searching for items using XPath, [contains] no longer works unless the string value precisely matches the value in the attribute.

If the contains does not have a precise value, it times out regardless of whether the timeout is 60s or 300 seconds.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.6.1Beta
* NuGet Pckgs: Appium.WebDriver: 2.0.1.1
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: Mac, El Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): 3.10.9
* Mobile platform/version under test: 9.3 and 10.1
* Real device or emulator/simulator: Simulator (iPhone 6s and 7)
* Appium Inspector (https://github.com/mykola-mokhnach/Appium-iOS-Inspector)

## Details
Searching for a a part of the value rather then the specific value in an XPath is failing.  Why would the contains functionality be broken?
//XCUIElementTypeStaticText[contains(@value, 'FNAME') - fails (TIMES OUT)
//XCUIElementTypeStaticText[contains(@value, 'LNAME, FNAME') - works

## Link to Appium logs
WORKS
[HTTP] --> POST /wd/hub/session/01c40ab5-8806-4171-9b33-b3d8c2161002/elements {"using":"xpath","value":"//XCUIElementTypeStaticText[contains(@value, 'ADAMS, TIMOTHY')]"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeStaticText[contains(@value, 'ADAMS, TIMOTHY')]","01c40ab5-8806-4171-9b33-b3d8c2161002"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/4713D3A6-FB39-4186-AC08-71589CDA0427/elements] with body: {"using":"xpath","value":"//XCUIElementTypeStaticText[contains(@value, 'ADAMS, TIMOTHY')]"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"66092B6F-3B0F-435F-969E-548E25B402F7","type":"XCUIElementTypeStaticText","label":"ADAMS, TIMOTHY"}],"sessionId":"4713D3A6-FB39-4186-AC08-71589CDA0427","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"66092B6F-3B0F-435F-969E-548E25B402F7","type":"XCUIElementTypeStaticText","label":"ADAMS, TIMOTHY"}]
[HTTP] <-- POST /wd/hub/session/01c40ab5-8806-4171-9b33-b3d8c2161002/elements 200 2129 ms - 184 

FAILS
[HTTP] --> POST /wd/hub/session/01c40ab5-8806-4171-9b33-b3d8c2161002/elements {"using":"xpath","value":"//XCUIElementTypeStaticText[contains(@value, 'TIMOTHY')]"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeStaticText[contains(@value, 'TIMOTHY')]","01c40ab5-8806-4171-9b33-b3d8c2161002"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/4713D3A6-FB39-4186-AC08-71589CDA0427/elements] with body: {"using":"xpath","value":"//XCUIElementTypeStaticText[contains(@value, 'TIMOTHY')]"}
[HTTP] <-- POST /wd/hub/session/01c40ab5-8806-4171-9b33-b3d8c2161002/elements - - ms - -

**Comment by mykola-mokhnach** [comment]
Please attach the full xml tree and logs (the current one has POST response missing)

**Comment by jtappi** [comment]
Ok, I will get these attached.  The POST response that is missing in the 'FAILS' is one of the issues i am facing.  It never responds because it times out.

**Comment by mykola-mokhnach** [comment]
@jtappi 
1. Can you try _findElement_ call instead of _findElements_?
2. Can you try to manually replace WDA sources in /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent with https://github.com/facebook/WebDriverAgent and restart the test?

**Comment by mykola-mokhnach** [comment]
I've also notices strange thing in the response - you are looking for \@value, but receiving \@label instead: 

```
http://localhost:8100/session/4713D3A6-FB39-4186-AC08-71589CDA0427/elements] with body: {"using":"xpath","value":"//XCUIElementTypeStaticText[contains(@value, 'ADAMS, TIMOTHY')]"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"66092B6F-3B0F-435F-969E-548E25B402F7","type":"XCUIElementTypeStaticText","label":"ADAMS, TIMOTHY"}],"sessionId":"4713D3A6-FB39-4186-AC08-71589CDA0427","status":0}
```

What if you replace attribute name in your request?

**Comment by jtappi** [comment]
1. Yes, I have tried FindElement as well.  Same result.
2. I will try this and report back with the results.

Good catch on the label...not sure what it means yet but will keep an eye on it.  I'll respond back with your request and XML\Log attachments shortly

**Comment by jtappi** [comment]
***I included the information below in case you wanted to look deeper into the issue with the XPath contains HOWEVER....replacing the WDA folder fixed my issue!!!  Thank you so much for that! 

Q) *What if you replace attribute name in your request?
A) I have tried '@name' and '@label' as well, but with the same result.

Q) Try FindElement
A) I tried using the same search with FindElement instead of FindElement(s) however the same failure occurs.
*[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/D5704D9E-971C-44F9-BCF6-8F6438D2967C/element] with body: {"using":"xpath","value":"//XCUIElementTypeStaticText[contains(@label, 'TIMOTHY')]"}

Q) Can you try to manually replace WDA sources in 
A) I replaced the WDA files and the test passed!!!

XML Link:
https://gist.github.com/jtappi/b0c9d773cb8897bf7879701d415e10d7

Appium Log:
https://gist.github.com/jtappi/654e69001fcff05dabdc4a471dbba60d

**Comment by jtappi** [comment]
@mykola-mokhnach Do i just need to use these WDA files until the next release of Appium?
Also, canI go ahead and close this issue as it is resolved?

**Comment by mykola-mokhnach** [comment]
Wait for Appium release 1.6.2

**Comment by jtappi** [comment]
will do, thanks for your help!

**Comment by vikramvi** [comment]
@jtappi new release is out, can you try again and update back please ?

**Comment by jtappi** [comment]
Sorry for the delay.  The contains is now working (1.6.3).  thanks for the help team!

**Comment by samsonbarukula** [comment]
HI Vikram : in ios 11 is there any pageFactory annotation to search with AccessibilityID because every thing is failing when I tried with 
@iOSFindBy(accessibility ="erty")
private MobileElement getaccess;

any solution pls ...

**Comment by vikramvi** [comment]
@samsonbarukula 
- please ask queries in http://discuss.appium.io/
- don't comment on already closed issue
