### ISSUE TITLE
How to update Appium to beta?

### ISSUE THREAD

**Issue by joaomrossetto** [appium/appium#7337]
I'm new with Mac systems, and i want to install 1.6 appium beta to test ios with the new xcode, but I don't know how to. I've tried to install by the comand line but i don't know how to use appium in comand line, set configs. I could not use Appium in comand line. I want to know if there is a way to install a dmg so I can have any UI with appium 1.6 beta.

**Comment by vikramvi** [comment]
@triager please close this , it is a question to be asked on https://discuss.appium.io/ and not an issue
