### ISSUE TITLE
Appium with Xcode 8 and macosx sierra 10.12

### ISSUE THREAD

**Issue by mzbedat** [appium/appium#7338]
Hi,
I have mac os 10.10 on my Mac and I can't install Xcode cause its supported only for 10.11 and above.
So I want to update my os, and the version available for me is 10.12

From searching I found there is a problem with Appium to recognize the version of sierra... is this problem solved on newest versions?

I don't want to update it and get stuck with non working environment.

BR

**Comment by JaniJegoroff** [comment]
> From searching I found there is a problem with Appium to recognize the version of sierra... is this problem solved on newest versions?

I don't know why you need to `recognize the version of sierra` but I have no problems running Appium on Sierra (both official and beta releases).

**Comment by mzbedat** [comment]
Hi,
My concern was to face issue similar to this one:
[]https://github.com/appium/appium/issues/6609#issuecomment-255974100

But if you are saying that you has it working with official releases then its encouraging.
Anyway, am making a backup (with TimeMachine) just in case I need to rollback.

Thanks.

**Comment by JaniJegoroff** [comment]
For `appium-doctor` here is my output from Sierra:
```
npm install -g appium-doctor
appium-doctor
```
```
info AppiumDoctor Appium Doctor v.1.2.5
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode8/Xcode.app/Contents/Developer
WARN AppiumDoctor  ✖ Xcode Command Line Tools are NOT installed!
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage
info AppiumDoctor  ✔ HOME is set to: /Users/janijegoroff
info AppiumDoctor  ✔ ANDROID_HOME is set to: /Users/janijegoroff/android-development/sdk
info AppiumDoctor  ✔ JAVA_HOME is set to: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
info AppiumDoctor  ✔ adb exists at: /Users/janijegoroff/android-development/sdk/platform-tools/adb
info AppiumDoctor  ✔ android exists at: /Users/janijegoroff/android-development/sdk/tools/android
info AppiumDoctor  ✔ emulator exists at: /Users/janijegoroff/android-development/sdk/tools/emulator
WARN AppiumDoctor  ✖ Bin directory for $JAVA_HOME is not set
info AppiumDoctor ### Diagnostic completed, 2 fixes needed. ###
info AppiumDoctor
info AppiumDoctor ### Manual Fixes Needed ###
info AppiumDoctor The configuration cannot be automatically fixed, please do the following first:
WARN AppiumDoctor - Add '$JAVA_HOME/bin' to your PATH environment
info AppiumDoctor ###
info AppiumDoctor
info AppiumDoctor Bye, run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor
```

**Comment by mzbedat** [comment]
I'm afraid that I got the same issue was reported #6609

>Last login: Mon Dec  5 10:47:45 on ttys000
macbook-air:~ admin$ '/Applications/Appium.app/Contents/Resources/node/bin/node' '/Applications/Appium.app/Contents/Resources/node_modules/appium-doctor/appium-doctor.js'
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
[Error: Could not detect Mac OS X Version from sw_vers output: '10.12.1
']

**Comment by mzbedat** [comment]
Hi @jlipps 
Can you please share your recommendation ...

To download 1.6.2 beta release (which understood doesn't have a GUI yet) and from 1.5.3 Developer Settings to use --automation-name XCUITest?
What about the "Use External Appium package"? to which folder should I point?
![snip20161205_2](https://cloud.githubusercontent.com/assets/17043182/20885193/24aeca26-baf8-11e6-952c-9044087a35a2.png)
