### ISSUE TITLE
Appium support AirwatchBrowser

### ISSUE THREAD

**Issue by sureshgorantla** [appium/appium#7339]
Hi All,

Can we run appium scripts on Airwatch browser either in iOS Or Android device? I am trying to run few of my appium scripts on Airwatch browser and i am looking for what are the desired capabilities we need to provide for browser Name? Please let me know.

Thanks,
Suresh G

**Comment by jlipps** [comment]
I've never heard of the Airwatch Browser so I'm not sure.

On iOS:
- You'll be able to automate the native portion of the app if you have permissions to build and run it for a simulator or on your device
- You'll be able to automate the webview if it's a standard Apple webview

On Android:
- You'll be able to automate the native portion just by installing the app
- You'll be able to automate the web portion if it uses Chrome-backed webviews

**Comment by RoakyWood** [comment]
@jlipps @sureshgorantla Jon, I know this was closed, but I am talking with the AirWatch people right now about this. 

No-one seems to yet know the AirWatch Web Browser name for the capabilities. 

Also, please define 'App' i.e. what and where installed? Do you mean the Appium software package? Or the Device Browser App being tested? 

As AirWatch becomes more pervasive, it might be mutually valuable for the Appium project to have more linkages with VMware/AirWatch.

RW
