### ISSUE TITLE
can't sendKey in alert popup

### ISSUE THREAD

**Issue by romainlouvet** [appium/appium#7340]
## Description

When try to sendKey on alert popup

Test code : 
Alert alert = getDriver().switchTo().alert();
alert.sendKeys("hello");

![image1](https://cloud.githubusercontent.com/assets/4262374/20791294/886e4918-b7bc-11e6-900c-2546ce90ee68.PNG)

## Environment

* java client build version : 4.1.2
* Appium server version : 1.6.1
* Mobile platform/version under test: iPhone 7 iOS 10.1 / Xcode 8.1
* Real device

## Link to Appium logs

Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["text"]} and you sent ["value"]

**Comment by JaniJegoroff** [comment]
> alert.sendKeys("hello");

Looks weird to me. Basically you are trying to type text to alert view itself?
Can't you just send key events to the textfield instead?

**Comment by romainlouvet** [comment]
no @JaniJegoroff see https://github.com/appium/appium/issues/7245#issuecomment-262104894

**Comment by jlipps** [comment]
@romainlouvet can you link to a gist of your full appium logs please?

**Comment by JaniJegoroff** [comment]
I did a simple test with UICatalog app (alert view with secure textfield) and works fine when simply finding element by classname:
- iPhone 6 simulator
- Appium 1.6.1
- Ruby

```ruby
find_element(class_name: 'XCUIElementTypeSecureTextField').send_keys 'qwerty'
```

<img width="1094" alt="screen shot 2016-12-01 at 20 12 50" src="https://cloud.githubusercontent.com/assets/2363231/20810695/a4ed4896-b802-11e6-96a7-05edda9e6146.png">

**Comment by jlipps** [comment]
That might be a workaround, but it does seem like there may be either a server or client bug in the parameters mismatch error, which is why I want to see the logs.

**Comment by romainlouvet** [comment]
https://gist.github.com/romainlouvet/371bf0b032ee48f53af8e6e85f5ea0db

**Comment by romainlouvet** [comment]
I created another issue in java-client project

**Comment by babusurendra** [comment]
Hi  @JaniJegoroff , when i tried that code you given above it is not even able find element .

do you have any idea about this?
 bellow is the scree shot 


![image](https://cloud.githubusercontent.com/assets/8430311/20928888/d293a896-bbed-11e6-89a4-c14f7c2ab6e7.png)

**Comment by JaniJegoroff** [comment]
@babusurendra Notice that my example was using SecureTextField. Take the view hierarchy dump and see what is element class in your case.

**Comment by babusurendra** [comment]
@JaniJegoroff  , i tried like this but it not able to find elements 
driverEle.find_element(:xpath,'//XCUIElementTypeAlert//XCUIElementTypeTextField').send_keys 'qwerty'

**Comment by babusurendra** [comment]
Hi @jlipps , @JaniJegoroff  , I am seeing the following errors when tried to send keys to text field in alert 

Can you help me if you have an other work arounds for this.
![image](https://cloud.githubusercontent.com/assets/8430311/20977776/90a723a6-bccc-11e6-8dc7-65b42810c259.png)

**Comment by mykola-mokhnach** [comment]
Closed as fixed
