### ISSUE TITLE
iOS real devices - Application is crashing and all tests stop their execution

### ISSUE THREAD

**Issue by nenkonenkov** [appium/appium#7341]
Hi, guys,
I'm new at automation with Appium and I have very serious issue with testing iOS for real devices. I have a set of tests and they work fine for Android. When I run the tests for iOS, they start to executing, but in some point (in random test or step) the application is crashing and all tests stop their execution. I receive this error in Java:

org.openqa.selenium.NoSuchSessionException: A session is either terminated or not started (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5 milliseconds
Build info: version: '3.0.0-beta3', revision: 'c7b525d', time: '2016-09-01 14:57:03 -0700'
System info: host: 'Georgis-iMac.local', ip: '10.185.44.31', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_60'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{networkConnectionEnabled=false, bundleId=com.wacom.bamboospark, databaseEnabled=false, deviceName=Antoaneta Stoyanova's iPhone, platform=MAC, showIOSLog=true, nativeInstrumentsLib=true, desired={showIOSLog=true, nativeInstrumentsLib=true, newCommandTimeout=111120, platformVersion=9.0, bundleId=com.wacom.bamboospark, platformName=iOS, udid=c35e79493f50a5709ec42d21f6d9d89fbfab32ac, deviceName=Antoaneta Stoyanova's iPhone, autoAcceptAlerts=true}, newCommandTimeout=111120, platformVersion=9.0, webStorageEnabled=false, locationContextEnabled=false, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=c35e79493f50a5709ec42d21f6d9d89fbfab32ac, autoAcceptAlerts=true}]
Session ID: 6119fa28-94bb-4251-9d29-1cc55d3408de

I'm using:
Appium: 1.5.3
Language: Java
Xcode: Version 7.3.1
Real Device: iPhone 6 with OS version: 9.0.2

Appium log:
[Appium_Log.txt](https://github.com/appium/appium/files/625266/Appium_Log.txt)

**Comment by jlipps** [comment]
As the log says, your app crashed:

> [debug] [Instruments] [INST] 2016-11-25 13:29:44 +0000 Fail: The target application appears to have died

There's even a clue as to why in the crash report in the logs:
```
 [iOSLog] [IOS_SYSLOG_ROW] Nov 25 15:29:44 Antoaneta-Stoyanovas-iPhone ReportCrash[617] <Error>: Process:             Inkspace [613]
[iOSLog] [IOS_SYSLOG_ROW] Path:                /private/var/mobile/Containers/Bundle/Application/1C2E9649-0E56-47FF-8FDF-57D79590E9DA/Inkspace.app/Inkspace
[iOSLog] [IOS_SYSLOG_ROW] OS Version:          iOS 9.0.2 (13A452)
[iOSLog] [IOS_SYSLOG_ROW] Nov 25 15:29:44 Antoaneta-Stoyanovas-iPhone ReportCrash[617] <Error>: Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
[iOSLog] [IOS_SYSLOG_ROW] Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000001
[iOSLog] [IOS_SYSLOG_ROW] Triggered by Thread:  0
```

This isn't an appium issue; you'll need to figure out why your app is crashing and fix it.
