### ISSUE TITLE
Appium 1.6.1 Real device Framework path does not match existing job path

### ISSUE THREAD

**Issue by pengboZheng** [appium/appium#7343]
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.1 with Xcode 7.3 on El Capitan or same environment with Simulator
* Desktop OS/version used to run Appium:10.12.1
* Node.js version (unless using Appium.app|exe):v7.1.0
* Mobile platform/version under test:iOS 9.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details
on macOS Sierra with Both Xcode 8 and Xcode 7.3 installed
on terminal to set Xcode 7 as default: sudo xcode-select --switch /Applications/Xcode\ 7.app
It will work with simulator but not with real device.
It complains "Framework path does not match existing job path".

## Link to Appium logs

https://gist.github.com/pengboZheng/adf39db9ed0cb47ae7128355b0a4ac24

**Comment by jlipps** [comment]
I've not seen this before. Seems like an apple issue. Right now I can only recommend restarting your computer and device and trying again.

**Comment by pengboZheng** [comment]
@jlipps Thanks for your quick response. but restart both computer and device not help with this situation.

**Comment by jlipps** [comment]
I don't know what to tell you then. Does googling for that error result in anything helpful? It seems like an instruments error, not an appium error, to me.

**Comment by pengboZheng** [comment]
@jlipps Thanks man
