### ISSUE TITLE
Interactions problems in iOS XCode 8 with Appium 1.6.1 

### ISSUE THREAD

**Issue by davidrova** [appium/appium#7344]
## The problem

My SUT is a hybrid application.

I had a testing project for an XCode 7 iOS application working on Appium 1.4.13.

Last week we upgrade to XCode 8, so were forced to upgrade to 1.6.1, and the testing project stops working.

## Environment

* Appium version 1.6.1
* Last Appium version that did not exhibit the issue (if applicable): N/A. The project were migrated to Xcode 8, so it is mandatory to upgrade appium
* Desktop OS/version used to run Appium: iOS 
* Node.js version (unless using Appium.app|exe): v6.2.2, v7.1.0
* Mobile platform/version under test: iOS 10.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: npm package
* Language: Javascript
* Framework: WebdriverIO 4.4.0

## Details

- Appium's desiredCapabilities:
     - browserName: ''
     - deviceName: 'iPhone 5s'
     - platformVersion: 10.1
     - platformName: 'iOS'
     - app: 'path to ipa'
     - newCommandTimeout: 70000 --> trying to force a wait....
     - noReset: false
     - interKeyDelay: 10
     - autoAcceptAlerts: true
     - fullReset: false --> because it is very very slow
     - launchTimeout: 60000  --> trying to force a wait, but I think it doesn't work
     - iosInstallPause: 10000  --> trying to force a wait....

The testing project doesn't work. We have tried several workarounds, but found blocker issues:

- Startup:
    -  The simulator is restarted twice before starting the test
    -  I have to force a pause of 10 seconds. The first first action (switches to native context) doesn't wait for the application to be started and crushes the execution, closing the app. If I force the pause then it passes the first step.
    - noReset doesn't work in all executions. Sometimes I see the screen when is the first access and sometimes not.
    - fullReset restart the application three times and is too slowly.

- autoAcceptAlerts
     - The first time you go inside the application you have to allow the application to access the system (native window), and in 1.6.1 doesn't work.

- If the screen is not ready application crashes and close.
     - If I force a pause and assure the screen is loaded, then it works.

*note*: In Android the application is not able to change to webview context.

## Link to Appium logs

https://gist.github.com/davidrova/4184935f077a4772fe3094d84ae9e86b

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/davidrova/26cba995a61be9010efb74c6285bcf19

**Comment by jlipps** [comment]
> newCommandTimeout: 70000 --> trying to force a wait....

Not sure this does what you think it does. The point of setting this is to keep Appium from shutting itself down after not having received a client command. It doesn't do any "waiting" per se.

> launchTimeout: 60000 --> trying to force a wait, but I think it doesn't work

I don't think this capability is relevant for XCUITest

> The simulator is restarted twice before starting the test

This is unfortunately not uncommon. Sometimes the simulator takes too long to boot or freezes and we have to restart it.

> I have to force a pause of 10 seconds. The first first action (switches to native context) doesn't wait for the application to be started and crushes the execution, closing the app. If I force the pause then it passes the first step.

If Appium has returned control to your script after starting a session, but your app is not yet ready for interaction, that's an odd scenario. It suggests that WebDriverAgent may finish its session loading before the app is ready. @marekcirkos have you ever seen this? @davidrova what do you mean when you say your app 'crashes'. Are there crash logs that let you know why?

> noReset doesn't work in all executions. Sometimes I see the screen when is the first access and sometimes not.

It would be helpful if you could find some kind of pattern here that we could use to diagnose what's not working with noReset.

> fullReset restart the application three times and is too slowly.

Unfortunately the underlying systems are not very stable, and so if things go wrong we have to retry, which can take some time. By looking at Appium or system logs, are you able to see why it's starting the app more than once?

> The first time you go inside the application you have to allow the application to access the system (native window), and in 1.6.1 doesn't work.

WebDriverAgent has chosen not to support autoAcceptAlerts, so you'll have to interact with the alert using the typical selenium alert handling methods.

The log you sent looks like it exhibits some strange behavior, but without the whole log (starting from when you begin to run the server), it's not as useful for debugging.

**Comment by davidrova** [comment]
> @davidrova The simulator is restarted twice before starting the test
> @jlipps This is unfortunately not uncommon. Sometimes the simulator takes too long to boot or freezes and we have to restart it.

I have seen this trace in log file and I don't know how to increase the timeout.

https://gist.github.com/davidrova/7baaa68edfc6ddf7a8090257d1490b3b

> what do you mean when you say your app 'crashes'. Are there crash logs that let you know why?

The application is closed and the test finished.

> fullReset and noReset settings

I will try to identify a pattern

> Allow alerts

Lets try with your idea

I am going to change my testing project with what we have discussed here and then take a clean log identifying each execution phase.

Regards, and thanks so much for your kick support.

**Comment by davidrova** [comment]
> autoAcceptAlerts is mentioned as a iOS feature

So if WebDriverAgent is not going to support it you will have to remove from capabilities, isn't it?

**Comment by davidrova** [comment]
> noReset appium logs

https://gist.github.com/davidrova/08a5d26eeca677c849fa4cbcbbf03525

I have tried restarting appium with no sucess.
If I don't force a reset in the simulator or use fullReset capability it doesn't clear data.

**Comment by davidrova** [comment]
> The simulator is restarted twice before starting the test
> -----
> This is unfortunately not uncommon. Sometimes the simulator takes too long to boot or freezes and we > have to restart it.

I don't know why but if you uninstall the application before running the test it doesn't restart the execution. Do you have any idea why?

**Comment by marekcirkos** [comment]
@jlipps Do you use xcodebuild to start WDA? If so you should consider trying fbsimctl (aka FBSimulatorControl). It is more stable and test execution is much much faster.

According to your question. I have seen very rarely that WDA may return from start session earlier that AUT is ready. It might be related to overloaded host.

**Comment by jlipps** [comment]
@marekcirkos we are going to try and tackle switching to fbsimctl next sprint: https://github.com/appium/appium/issues/7281. but currently we use xcodebuild.

**Comment by davidrova** [comment]
As I understand, it is not in my hands the use of xcodebuild or fbsimctl, isn't it?

Should I wait next sprint?

**Comment by jlipps** [comment]
@davidrova yes. I'll close this in favor of #7281 so you can track the resolution of that instead.

**Comment by davidrova** [comment]
Thanks!!
