### ISSUE TITLE
Add new touchId enrollment endpoint

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7347]
Migrated from appium-base-driver
https://github.com/appium/appium-base-driver/issues/87

We need an endpoint for the device to be enrolled.

**Comment by dpgraham** [comment]
Hi @rkavalap, do you know if this is supported in XCUITest?

**Comment by rkavalap** [comment]
@dpgraham I haven't completely looked at the source code for this if this was ever implemented. If your work for https://github.com/appium/appium/issues/7013 covers the api, then we should close this. 
According @midopa  who skimmed the code mentioned it was not implemented.

**Comment by midopa** [comment]
The whole point of appium/appium-base-driver#87 was to first add the endpoints so the downstream drivers can begin to implement it.

Right now XCUITest only supports the Touch ID match/pass action. But you need to enroll into Touch ID through the simulator first. That part is not exposed. Last time I checked, the Touch ID match/pass API didn't automatically do that part for you.

So there are two options here:
1. Update the XCUITest driver so that calling Touch ID match/pass will auto enroll into Touch ID for you
2. Add a separate call to enroll/unenroll into Touch ID that XCUITest then implements

Option 2 is more flexible, as it allows people to test flows where a user has not enabled Touch ID at all.

**Comment by dpgraham** [comment]
I just don't know if Apple's XCUITest framework (https://developer.apple.com/reference/xctest#symbols) exposes the 'enroll' functionality. I didn't see anything in https://github.com/facebook/webdriveragent that implements it either. What we'll have to do is:

* [ ] Check if 'enroll' is supported in XCUI Test

If it is...
* [ ] Create an issue or pull request to add it to WebDriverAgent
* [ ] Update xcuitest-driver to use that endpoint
* [ ] Update the clients

If it is _not_
* [ ] Document the lack of functionality and explain how to enable enrollment manually
* [ ] Submit a radar ticket with Apple
* [ ] Confirm if SauceLabs iOS Simulators enable enrollment by default

**Comment by mykola-mokhnach** [comment]
Seems like @kaleposhobios has already [tried it](https://github.com/facebook/WebDriverAgent/issues/26), but didn't succeeded. One can use Apple scripting to click the corresponding menu item in Simulator, but this requires controller app to be explicitly authorised in System Preferences.

**Comment by jlipps** [comment]
For now, it sounds to me like enrolling should be a problem solved by an applescript which is not part of Appium itself but anyone could run it in their test setup if they want...?

**Comment by midopa** [comment]
That seems reasonable. What about tests run through Sauce Labs? Is there anything users can do in that regard?

**Comment by jlipps** [comment]
@midopa hmm that would be difficult to be sure. I'd reach out to the Sauce Labs product team and make a request for them to investigate adding some way to set up touch ids on our sims. They will appreciate hearing from a customer :-)

**Comment by jlipps** [comment]
(cc @chiarnglin)

**Comment by jlipps** [comment]
OK, I'm changing my mind on this after hearing about another way to achieve this. I think we can support an endpoint like this in Appium. Here's the method/criteria:

* new endpoint `/session/:sessionid/appium/simulator/toggle_touch_id_enrollment` (no params) added in base-driver
* during appium-xcuitest-driver session start, run the following system command, which sets a crazy key binding for toggling the enrolled state
```
defaults write "Apple Global Domain" NSUserKeyEquivalents -dict-add "Toggle Enrolled State" "@~\$^t"
```
* new endpoint exposed in appium-xcuitest-driver. when called, runs an applescript with the following content, which ensures the sim is frontmost and sends the key command to toggle
```
activate application "Simulator"
tell application "System Events"
	key code 17 using {control down, shift down, option down, command down}
end tell
```
* during session cleanup, remove the keybinding:
```
defaults write "Apple Global Domain" NSUserKeyEquivalents -dict-add "Toggle Enrolled State" nil
```

it's a little wonky, but it should work.

**Comment by mykola-mokhnach** [comment]
@jlipps And how are you going to solve Accessibility access issue? node executable is not Mac OS application container, so it cannot be explicitly added into the corresponding list under System Preferences.

**Comment by jlipps** [comment]
People will have to add the terminal if they want to use this feature. or Appium Desktop I guess if they're using that.

**Comment by jlipps** [comment]
Looks like there are also command line tools we could build into authorize_ios (for example https://github.com/jacobsalmela/tccutil) if we wanted this to be an automatic part of setup.

**Comment by aluedeke** [comment]
@jlipps sounds like this won't work for real devices right?

**Comment by dpgraham** [comment]
@aluedeke That's correct, real devices don't a TouchID simulation feature. Only the Simulators do that.

**Comment by dpgraham** [comment]
This is the prompt that comes up when attempting to access menu items via `osascript`. Keeping it here for posterity.

![screen shot 2017-03-15 at 3 02 04 pm](https://cloud.githubusercontent.com/assets/852574/23972787/71e28f08-0990-11e7-91b2-a559f7b8c427.png)

**Comment by dpgraham** [comment]
This needs to be documented:

![screen shot 2017-03-15 at 3 03 54 pm](https://cloud.githubusercontent.com/assets/852574/23972838/a86f94da-0990-11e7-9138-2fda591750d4.png)

![screen shot 2017-03-15 at 3 04 33 pm](https://cloud.githubusercontent.com/assets/852574/23972847/b8280650-0990-11e7-88ea-4087394e33f9.png)

**Comment by dpgraham** [comment]
Hey @jlipps, can you elaborate more on your osascript

```applescript
defaults write "Apple Global Domain" NSUserKeyEquivalents -dict-add "Toggle Enrolled S

activate application "Simulator"
tell application "System Events"
	key code 17 using {control down, shift down, option down, command down}
end tell

defaults write "Apple Global Domain" NSUserKeyEquivalents -dict-add "Toggle Enrolled State" nil
```

I've tested these three lines of applescript with no success. 

I tried this too, and it has worked so far:

```applescript
activate application "Simulator"
tell application "System Events" to tell process "Simulator"
    try
        click menu item "Toggle Enrolled State" of menu 1 of menu item  "Touch ID" of menu 1 of menu bar item "Hardware" of menu bar 1
    end try
end tell
tell application "System Events" to tell process "Simulator"
    try
        click menu item "Touch ID Enrolled" of menu 1 of menu bar item "Hardware" of menu bar 1
    end try
end tell
```

**Comment by dpgraham** [comment]
published to v2.24.0 of appium-xcuitest-driver

**Comment by jazzpetzah** [comment]
In case anybody needs apple script relevant for Simulator version 10.

To enable Touch ID (incl. verification it is not already checked) :
`activate application "Simulator"
tell application "System Events" to tell process "Simulator"
	set touchEnroll to menu item "Enrolled" of menu 1 of menu item "Touch ID" of menu 1 of menu bar item "Hardware" of menu bar 1
	tell touchEnroll
		set checkStatus to value of attribute "AXMenuItemMarkChar" of touchEnroll
		if checkStatus is "✓" then click touchEnroll
	end tell
end tell`

**Comment by dpgraham** [comment]
@jazzpetzah Did the current solution stop working with Simulator 10?
