### ISSUE TITLE
Android Driver failed to start with latest Appium 1.6.1 from 2 Dec

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#7349]
## The problem

Driver failed to start with latest version of appium.

Look like issue due to latest https://github.com/appium/appium-adb/pull/186

## Environment

* Appium version (or git revision) that exhibits the issue: "**1.6.1 --no-shrinkwrap**"
* Last Appium version that did not exhibit the issue (if applicable): "**1.6.1**"
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device Android 6.0

## Link to Appium logs

[debug] [ADB] Running '/Users/Aleksei/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","LGH8155e9892e6","shell","am","force-stop","io.appium.unlock"]
[debug] [Logcat] Stopping logcat capture
[debug] [AndroidDriver] App was not copied, so not deleting
[HTTP] <-- POST /wd/hub/session 500 2178 ms - 222 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: targetSdkVersionFromManifest failed. Original error: Cannot read property '1' of null (WARNING: The server did not provide any stacktrace information)

**Comment by sankleta** [comment]
I have the same issue with Appium 1.6.0, Android SDK 24.4.1 and build-tools 4.0.3 and real device with Android 5.1, but in a bit different place.
Here is the logs:

[debug] [ADB] Running '/opt/android-sdk-linux/platform-tools/adb' with args: ["-P",5037,"-s","33005a71c782236b","install","/node_modules/io.appium.settings/bin/settings_apk-debug.apk"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/opt/android-sdk-linux/platform-tools/adb' with args: ["-P",5037,"-s","33005a71c782236b","shell","getprop","ro.build.version.sdk"]
[debug] [ADB] Device API level: 22
[ADB] Checking whether aapt is present
[ADB] Using aapt from /opt/android-sdk-linux/build-tools/24.0.3/aapt
[ADB] Extracting package and launch activity from manifest
[ADB] Error: targetSdkVersionFromManifest failed. Original error: Cannot read property '1' of null
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (../../../lib/tools/android-manifest.js:101:9)
    at tryCatch (/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: targetSdkVersionFromManifest failed. Original error: Cannot read property '1' of null
    at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
    at ADB.callee$0$0$ (../../../lib/tools/android-manifest.js:101:9)
    at tryCatch (/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Called deleteSession but bootstrap wasn't active

**Comment by jlipps** [comment]
@sravanmedarapu any ideas here?

**Comment by gustavomick** [comment]
+1

**Comment by sravanmedarapu** [comment]
Seems something broken with appium-adb v2.9.0, Please downgrade appium-adb to v2.7.0 as a temporary work around.

**Comment by gustavomick** [comment]
thanks

**Comment by sravanmedarapu** [comment]
Ohh actually it should not be, as the issue introduced with changes of 2.9.0.

Could you please cross check that downgrading was successful.

**Comment by gustavomick** [comment]
whats the best way to checkit?

**Comment by gustavomick** [comment]
$ npm-check -g

appium-adb   �  MINOR UP  Minor update available. https://github.com/appium/appium-adb
                          npm install --global appium-adb@2.9.0 to go from 2.7.0 to 2.9.0

**Comment by sravanmedarapu** [comment]
Please execute `npm install appium-adb@2.7.0`  from appium repo.

**Comment by gustavomick** [comment]
thanks i dint think about that. so now im here

protractor conf.js

[15:07:51] I/hosted - Using the selenium server at http://127.0.0.1:4723/wd/hub
[15:07:51] I/launcher - Running 1 instances of WebDriver
[15:07:57] E/runner - Unable to start a WebDriver session.
[15:07:59] E/launcher - Error: WebDriverError: Method has not yet been implemented

**Comment by sravanmedarapu** [comment]
Please share appium server logs for better understanding in a separate [gist](https://gist.github.com/).

**Comment by gustavomick** [comment]
https://gist.github.com/gustavomick/f22b2c06714c98ec0265ab1f7222f092 i saw app opening then inmediatly shutdown.

**Comment by sravanmedarapu** [comment]
It seems issue is with calling  async_script, 

`[HTTP] <-- POST /wd/hub/session/c4f36fdc-fbf1-4c33-b414-e9f9dd398877/timeouts/async_script 501 7 ms - 122` 

Please refer this https://github.com/appium/appium/issues/7062

**Comment by gustavomick** [comment]
hey so this hotfix works, thanks!

**Comment by amedvedjev** [comment]
today\s "1.6.2 --no-shrinkwrap" - fixed!

but driver start added 15sec :-(

**Comment by jlipps** [comment]
@sravanmedarapu i also noticed the slowdown for adding many different permissions. do you think we should put this behind a capability or something so that people will opt into the permission updates?

**Comment by sravanmedarapu** [comment]
Sure @jlipps, What should be the capability name?.

**Comment by sravanmedarapu** [comment]
Mentioned possible approach on the issue [here](https://github.com/appium/appium/issues/5561#issuecomment-266063805)

**Comment by amedvedjev** [comment]
latest version just great appium start with android. 7sec vs 31sec
