### ISSUE TITLE
Chromedriver Install issues: Appium installation failing on Windows 7

### ISSUE THREAD

**Issue by HPramesh** [appium/appium#7350]
## The problem
I am very new to the Mobile world.
Not able to install Appium 1.6 on windows 7 from the cmd prompt. 
Could anyone please help me on this??

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6
* Last Appium version that did not exhibit the issue (if applicable): Not tried 
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe):  node-v6.3.0-x64 and node-v7.2.0-x64
* Mobile platform/version under test: NA
* Real device or emulator/simulator: NA
* Appium CLI or Appium.app|exe:  Appium CLI

## Details
i am trying to set up an environment to automate apps on the Android mobile phones. Downloaded the appium latest master version from git and tried installing through command line. But its failing at   **Failed at the appium-chromedriver@2.9.4 install script 'node install-npm.js'.**.

Tried various suggestions from previous issues reported here but for no success.

## Link to Appium logs
https://gist.github.com/HPramesh/01e00663a289d1ec856fc54b79060665#file-appium_chromedriver_failure 

## Code To Reproduce Issue [ Good To Have ]
NA

**Comment by jlipps** [comment]
If you just want to use appium, you don't need to download via git or anything. Just ensure you have Node 6 or higher, and run `npm install -g appium` from a command prompt.

**Comment by HPramesh** [comment]
Thanks! 
Yes that's the exact command i ran after setting the proxy configurations.

**Comment by jlipps** [comment]
Hmm, I don't think the issue would be related to Appium itself then. Are you able to just try `npm install appium-chromedriver` somewhere?

**Comment by HPramesh** [comment]
Tried and seeing the same error. Find the logs at below link for reference.
https://gist.github.com/HPramesh/8a6c1b4f3048f2d5fc8c6557db067267#file-npm_chromedriver-debug-txt

**Comment by jlipps** [comment]
@HPramesh are you doing this from an admin console?

**Comment by HPramesh** [comment]
Yes. I have tried both running cmd prompt as user and as administrator. But the results are the same.

**Comment by vikramvi** [comment]
@HPramesh this is happening as you're in company network ( behind proxy ). Try same thing from your home net and it should work without any problem.

Update here once you give it a try.

**Comment by HPramesh** [comment]
@jlipps and @vikramvi  : Thanks for the replies!  Yep i think the issue is with the Proxy itself as i was successful in installing appium with usual commands from my home. But appreciate if could get any workarounds to handle this situation.

**Comment by jlipps** [comment]
You can get around this by installing appium with a special flag:

```
npm install -g --chromdriver-cdnurl=http://chromedriver.storage.googleapis.com appium
```
