### ISSUE TITLE
Misleading error on using XCUITest to select a non-existant attribute

### ISSUE THREAD

**Issue by emil-petersen** [appium/appium#7352]
## The problem

While crafting selectors to work through a smartphone app, I was exploring my options for selecting a certain element, and generated the error I document below.

I was trying to select the `enabled` attribute, although `value` was the correct choice. That isn't the bug report, though - I suspect that the log I'm attaching highlights some crash or other underlying issue. Either way I think the error message is confusing and opaque - our iOS developer told me it's the sort of error that should be caught at compile time, happening due to misconfiguration.

In the example I am using `aoeuasdf` as the example selector. The issue I am reporting here is that the error message that results is very opaque, and possibly shows some underlying issue with the server. In the specific example of the Python driver, something like a KeyError would been more helpful.

## Environment

* Appium version: 1.6.0-beta3
* Desktop OS/version used to run Appium: OSX
* Node.js version (unless using Appium.app|exe): v7.0.0
* Mobile platform/version under test: iOS 10.1 on iPhone 6S
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Python driver

## Link to Appium logs

https://gist.github.com/emil-petersen/5406e77d1c767a369de7168af8d4e2e4

## Code To Reproduce Issue [ Good To Have ]

Using the Python driver:

```
things = driver.find_elements_by_xpath(
    '//XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeSwitch')
dictionary['things'] = [
  (source.get_attribute('name'), source.get_attribute('aoeuasdf')) for source in
  things if source.get_attribute('name')]
```

**Comment by emil-petersen** [comment]
@jlipps Because of the things I'm working on being sensitive, my preference is not to do so. Is there some particular information in there you'd be looking at? Then I could pull that out and sanitize it. Sorry about the inconvenience.

**Comment by mykola-mokhnach** [comment]
@emil-petersen I'm currently working on setting rules for elements attributes. In general, this starts with https://github.com/facebook/WebDriverAgent/pull/379 PR and then I plan to standardise available properties for all other external accessors, like getAttribute. This standardisation is based on [FBElement](https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Routing/FBElement.h) protocol

**Comment by emil-petersen** [comment]
@mykola-mokhnach I'm closing this issue since work is under progress along these lines.
