### ISSUE TITLE
Retrieving the UDID of iOS Device from caps

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#7355]
Hello 

I am trying to retrieve the UDID of iOS Device that is connected to my MAC using Java code. I am trying to run scenarios in Grid and I want a way through I can get to know which scenario is running in which UDID ?

**Comment by saikrishna321** [comment]
@pavanbachu0604 which client are you using ? Are you trying to get the UDID on which the session has started?

**Comment by mykola-mokhnach** [comment]
```java
driver.getCapabilities().getCapability("udid")
```

do you need something like this?

**Comment by saikrishna321** [comment]
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/AndroidDriverTest.java#L129

**Comment by pavanbachu0604** [comment]
@saikrishna321 I am using Java Client and in the above link it shows for Android Device.
@mykola-mokhnach Yeah something similar to that which can tell the UDID of device from Java Code

**Comment by saikrishna321** [comment]
@pavanbachu0604 this way works if your passing the UDID on the server start and ignoring on the caps. 

@mykola-mokhnach line of code works when you have passed UDID on the DesiredCaps and not on server start

**Comment by mykola-mokhnach** [comment]
How about this approach? But you need to execute this command on the particular node, where your device is physically connected. This will return the udid of the first connected iPhone or iPad.

```java
    private static Optional<String> udid = Optional.empty();

    public static String getUDID() throws Exception {
        if (!udid.isPresent()) {
            for (String deviceName : new String[]{"iPhone", "iPad"}) {
                final String result = CommonUtils.executeOsXCommandWithOutput(new String[]{
                        "/bin/bash",
                        "-c",
                        "system_profiler SPUSBDataType | sed -n '/"
                                + deviceName
                                + "/,/Serial/p' | grep 'Serial Number:' | awk -F ': ' '{print $2}'"}).trim();
                if (result.length() > 0) {
                    udid = Optional.of(result);
                    break;
                }
            }
        }
        if (udid.isPresent()) {
            return udid.get();
        }
        throw new IllegalStateException("No connected iOS devices can be detected");
    }
```

**Comment by mykola-mokhnach** [comment]
@imurchie Can we do the same fix in iOS, that we already did in Android - to assign 'udid' property in capabilities automatically if the device has been autodetected?

**Comment by pavanbachu0604** [comment]
I really appreciate that help , does it work when you are more than one device connected?

**Comment by mykola-mokhnach** [comment]
Yes, you just need to parse command output differently.

**Comment by pavanbachu0604** [comment]
![screen shot 2016-12-08 at 10 07 33 am](https://cloud.githubusercontent.com/assets/21222084/21015572/72efcd18-bd30-11e6-867a-d6a3d0ff488a.png)
I am getting this issue

**Comment by mykola-mokhnach** [comment]
I've just pasted a piece code we use in our own framework to give you a quick overview on how it **can** be implemented. I don't understand why one can expect it to work from the scratch..

**Comment by pavanbachu0604** [comment]
driver.getCapabilities().getCapability("udid")
    driver.getCapabilities().getCapability("deviceName")
    driver.getCapabilities().getCapability("platformVersion")

Works perfect but cast it to RemoteWebDriver

**Comment by imurchie** [comment]
For XCUITest [this commit](https://github.com/appium/appium-xcuitest-driver/commit/34611c4e968f101b9555e4125a19cf058c4507ca) ought to fix this.
