### ISSUE TITLE
Can't start-up the APP that I want to test through WDA after upgrade appium1.6.2

### ISSUE THREAD

**Issue by iriszhang1986** [appium/appium#7357]
## The problem

when start test，the log stop on this，And the app can't startup：
Continuing to run tests in the background with task ID 1

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.2
* Last Appium version that did not exhibit the issue (if applicable):1.6.0
* Mobile platform/version under test:iOS10.1，xcode8
* Real device or emulator/simulator:Real device

## Detail

now I Have to replace the .../node_modules/.appium_npminstall/appium-xcuitest-driver/2.3.0/appium-xcuitest-driver/WebDriverAgent with appium 1.6.0‘s，and then it's ok.
is it wda's problem?

## Link to Appium logs

[Appium] Welcome to Appium v1.6.2
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.2","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 19 ms - 83 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.2","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 10 ms - 83 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"com.gzj.haiuser","automationName":"XCUITest","platformName":"iOS","udid":"1ab4e5d80d69a02d954cb8ab0f456b0774b9a5da","deviceName":"111"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"com.gzj.haiuser","automationName":"XCUITest","platformName":"iOS","udid":"1ab4e5d80d69a02d954cb8ab0f456b0774b9a5da","deviceName":"111"},null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: 'com.gzj.haiuser'
[Appium]   automationName: 'XCUITest'
[Appium]   platformName: 'iOS'
[Appium]   udid: '1ab4e5d80d69a02d954cb8ab0f456b0774b9a5da'
[Appium]   deviceName: '111'
[debug] [XCUITest] XCUITestDriver version: 2.3.0
[BaseDriver] Session created with session id: 1178a436-5b47-4de5-931e-8ad3cbdc477c
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [XCUITest] Available devices: 1ab4e5d80d69a02d954cb8ab0f456b0774b9a5da
[debug] [XCUITest] Creating iDevice object with udid 1ab4e5d80d69a02d954cb8ab0f456b0774b9a5da
[XCUITest] Determining device to run tests on: udid: '1ab4e5d80d69a02d954cb8ab0f456b0774b9a5da', real device: true
[debug] [XCUITest] App is an iOS bundle, will attempt to run as pre-existing
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/Users/iris/Documents/node-v6.3.1-darwin-x64/lib/node_modules/.appium_npminstall/appium-xcuitest-driver/2.3.0/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/iris/Documents/node-v6.3.1-darwin-x64/lib/node_modules/.appium_npminstall/appium-xcuitest-driver/2.3.0/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /Users/iris/Documents/node-v6.3.1-darwin-x64/lib/node_modules/.appium_npminstall/appium-xcuitest-driver/2.3.0/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=1ab4e5d80d69a02d954cb8ab0f456b0774b9a5da -configuration Debug' in directory '/Users/iris/Documents/node-v6.3.1-darwin-x64/lib/node_modules/.appium_npminstall/appium-xcuitest-driver/2.3.0/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/iris/Library/Developer/Xcode/DerivedData/WebDriverAgent-agebempnhgnrebfwxttizzlbbbzc/Logs/Test/3C73416E-29E6-4E0B-9BD5-E913E5E45C07/Session-WebDriverAgentRunner-2016-12-05_150539-yg8COq.log
**[debug] [WebDriverAgent] Device: Dec  5 15:05:48 duomaiceshide-iPhone XCTRunner[226] <Notice>: Running tests...
[debug] [WebDriverAgent] Device: Dec  5 15:05:50 duomaiceshide-iPhone XCTRunner[226] <Notice>: Continuing to run tests in the background with task ID 1**
^C[Appium] Received SIGINT - shutting down
[XCUITest] System log exited with code '0'
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGINT'
[HTTP] <-- POST /wd/hub/session - - ms - -

**Comment by romainlouvet** [comment]
same for me :(

[debug] [WebDriverAgent] Device: Dec  5 10:20:09 iPhoneQA5SBlanc XCTRunner[4277] <Notice>: Continuing to run tests in the background with task ID 1
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...

**Comment by mykola-mokhnach** [comment]
1. Are you sure you finished the previous testing session properly?
2. There should be no active system alerts on the screen while WDA is starting.
3. Have you tried to compile and run WDA manually on the device from Xcode (Product->Test on WebDriverRunner project)?

**Comment by romainlouvet** [comment]
@mykola-mokhnach 
1. Yes
2. Yes
3. xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=4c1b23a8f47deeb851bdba9c7aca6c0214779c2e' clean build test

**Comment by romainlouvet** [comment]
I downgraded with 1.6.1 -> no problem

**Comment by mykola-mokhnach** [comment]
Create an issue here https://github.com/facebook/WebDriverAgent/issues, but replace your local WDA with the most recent sources from master branch and check these first.

**Comment by saikrishna321** [comment]
@romainlouvet its the same on ma side too +1

**Comment by jlipps** [comment]
@mykola-mokhnach are we dealing with a legitimate regression in WDA-side code? if so we should see if we can fix and get appium 1.6.3 out asap

**Comment by mykola-mokhnach** [comment]
@jlipps Let's see what @marekcirkos thinks about it. I use WDA from master branch and don't see any noticeable issues so far.
@romainlouvet have you created an issue in WDA project? I don't see anything new there.

**Comment by RashmiMurthy** [comment]
@romainlouvet : I updated Appium to 1.6.2, when I try to compile after adding valid provisioning profile

xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=ae7e4de6d18f3990190a6db32dbc6cb28a908a40' clean build test

throws below error:
Testing failed:
	'RoutingHTTPServer/RoutingHTTPServer.h' file not found
** TEST FAILED **

**Comment by romainlouvet** [comment]
@mykola-mokhnach I try the last WDA same result
https://github.com/facebook/WebDriverAgent/issues/398

**Comment by mykola-mokhnach** [comment]
@romainlouvet What is your Xcode and OS version? I use 8.0 GM @ El Capitan

**Comment by romainlouvet** [comment]
Mac OS Sierra 10.12.1  & Xcode 8.1

**Comment by hepilt** [comment]
>  I updated Appium to 1.6.2, when I try to compile after adding valid provisioning profile
> xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination > 'id=ae7e4de6d18f3990190a6db32dbc6cb28a908a40' clean build test
> 
> throws below error:
> Testing failed:
> 'RoutingHTTPServer/RoutingHTTPServer.h' file not found
> ** TEST FAILED **

Just run script from ./WebAgentRunner/Scripts/bootstrap.sh, u have no updated dependencies and npm bundle

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/7313#issuecomment-265429856

Seems like we've found the reason

**Comment by mykola-mokhnach** [comment]
I could even create a PR if I get a t-shirt with Appium logo for that
![grinch2](https://cloud.githubusercontent.com/assets/7767781/20968608/78201c76-bc85-11e6-8b87-ba7ff49fd95e.gif)

**Comment by jlipps** [comment]
@mykola-mokhnach t-shirt guaranteed! PM me on appium slack and i'll get your details :-)

**Comment by maesiva** [comment]
Verified on 1.6.3 and I could launch the app. Thanks !!

Now, waiting for "invalid clicks in Landscape mode" (https://github.com/appium/appium/issues/6994) fix of WDA.
