### ISSUE TITLE
Running xcuitest from Windows like others are doing?

### ISSUE THREAD

**Issue by outofrange** [appium/appium#7360]
I'm aware that Appium can only control iOS devices from a Mac, since Xcode is required to be available in order to provide xcuitest.

But: I know about at least one paid tool that is able to do exactly that, seemingly by using some port (?) of xcuitest for Windows, called xcuitest_runner.
I have no idea if xcuitest_runner (for Windows) is developed and maintained by the tool's company or by Apple itself, but it's definitely possible to run iOS tests using Windows - just not with Appium right now.

Being able to use other OS than Mac for iOS tests on real devices is quite important for us, which is why we paid for the tool in the first place, instead of using Appium. I guess the same applies to quite some more people here.

Having this feature would be a huge bonus for Appium, so I would like to use this thread for a discussion about the following:
* Does anyone know more about xcuitest_runner, ie. how it's running xcuitest tests?
* Is it possible to use xcuitest_runner (if it's something official provided by Apple) or to build it by our own? (if it's something proprietary)
* Is this something others are interested too?
* Is this something the core team is interested in?
* What would be needed for this to work?

(I'm not really sure if I should mention the company's name here, 'cause I'm not sure if I want to do marketing for them, but you should be able to find them by searching for xcuitest_runner)

(if the answer is among the lines of "We know about this, but haven't had any time to implement it, you are free to submit a PR", I'm happy too :))

**Comment by vikaspune** [comment]
+1

**Comment by jlipps** [comment]
While this would be a useful feature for some users, it's not on the Appium team's roadmap to reverse engineer XCUITest and reimplement the protocol on Windows or Linux. However, if someone else is able to do this and wants to open source the code, we would take a look at integrating it.

I'm aware of this problem having been solved by a couple companies but I'm not aware of any open source solution at the moment.
