### ISSUE TITLE
Error : Unable to start WebDriverAgent (Appium : 1.6.2)

### ISSUE THREAD

**Issue by muratme** [appium/appium#7361]
## The problem

With Appium 1.6.2, the webDriverAgent could not finish loading when i try to execute automation tests on real device.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6.2
* Desktop OS/version used to run Appium: MACOS 10.11.6 El Capitan
* Node version (unless using Appium.app|exe): v6.8.0
* Npm Version : 3.10.8
* Mobile platform/version under test: IOS 10.1
* Real device or emulator/simulator: Iphone6
    java version "1.8.0_40"

## Details

After webdriver and application load on device successfully finished, webDriverAgent opened and closed. And the application tests could not initialized. Notthing happen after that.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

murat-mercans-MacBook-Pro:~ admin$ appium --address "0.0.0.0" --port "8001" -U "b7041fd671219970b8af025171cf61540ce38ca6" --session-override --command-timeout 600
[Appium] Welcome to Appium v1.6.2 (REV d8b31e829e114bdd3e97687b7c9b2b67942fe6b6)
[Appium] Non-default server args:
[Appium]   port: 8001
[Appium]   sessionOverride: true
[Appium]   defaultCommandTimeout: 600
[Appium]   udid: 'b7041fd671219970b8af025171cf61540ce38ca6'
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"b7041fd671219970b8af025171cf61540ce38ca6"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: 'b7041fd671219970b8af025171cf61540ce38ca6'
[Appium] Appium REST http interface listener started on 0.0.0.0:8001
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/opt/sahibinden/sahibinden.app","nativeInstrumentsLib":"true","newCommandTimeout":"600","platformVersion":"10.1","automationName":"XCUITest","bundleid":"com.sahibinden.sahibinden","waitForAppScript":"$.delay(5000); $.acceptAlert();","platformName":"iOS","udid":"b7041fd671219970b8af025171cf61540ce38ca6","deviceName":"iPhone 6"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/opt/sahibinden/sahibinden.app","nativeInstrumentsLib":"true","newCommandTimeout":"600","platformVersion":"10.1","automationName":"XCUITest","bundleid":"com.sahibinden.sahibinden","waitForAppScript":"$.delay(5000); $.acceptAlert();","platformName":"iOS","udid":"b7041fd671219970b8af025171cf61540ce38ca6","deviceName":"iPhone 6"},null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/opt/sahibinden/sahibinden.app'
[Appium]   nativeInstrumentsLib: 'true'
[Appium]   newCommandTimeout: '600'
[Appium]   platformVersion: '10.1'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleid: 'com.sahibinden.sahibinden'
[Appium]   waitForAppScript: '$.delay(5000); $.acceptAlert();'
[Appium]   platformName: 'iOS'
[Appium]   udid: 'b7041fd671219970b8af025171cf61540ce38ca6'
[Appium]   deviceName: 'iPhone 6'
[debug] [XCUITest] XCUITestDriver version: 2.3.0
[BaseDriver] Capability 'nativeInstrumentsLib' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'newCommandTimeout' changed from string ('600') to integer (600). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: bundleid.
[BaseDriver] Session created with session id: fc0926ca-f699-4c32-a9fa-5ad787d78a14
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [XCUITest] Available devices: b7041fd671219970b8af025171cf61540ce38ca6
[debug] [XCUITest] Creating iDevice object with udid b7041fd671219970b8af025171cf61540ce38ca6
[XCUITest] Determining device to run tests on: udid: 'b7041fd671219970b8af025171cf61540ce38ca6', real device: true
[BaseDriver] Using local app '/opt/sahibinden/sahibinden.app'
[debug] [XCUITest] Checking whether app '/opt/sahibinden/sahibinden.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/opt/sahibinden/sahibinden.app': 'com.sahibinden.sahibinden'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] Error checking install status: Command 'ios-deploy --exists --id b7041fd671219970b8af025171cf61540ce38ca6 --bundle_id com.sahibinden.sahibinden' exited with code 255
[debug] [XCUITest] App is not installed. Will try to install.
[debug] [XCUITest] App installed successfully.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=b7041fd671219970b8af025171cf61540ce38ca6 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/E49ABC90-2BBB-4B40-8145-A820604FEAD3/Session-WebDriverAgentRunner-2016-12-05_154123-oi78RG.log
[debug] [WebDriverAgent] Device: Dec  5 15:41:24 qamobiltestekibigmailcoms-iPhone XCTRunner[269] <Notice>: Running tests...
[debug] [WebDriverAgent] Device: Dec  5 15:41:25 qamobiltestekibigmailcoms-iPhone XCTRunner[269] <Notice>: Continuing to run tests in the background with task ID 1
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...

`15:56:47.840 xcodebuild[40074:2228044] Test operation failure: Launch session expired.
15:56:47.840 xcodebuild[40074:2228044] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Launch session expired." UserInfo={NSLocalizedDescription=Launch session expired.} didCancel: 1
`

**Comment by romainlouvet** [comment]
https://github.com/appium/appium/issues/7357
