### ISSUE TITLE
Appium 1.6 beta 2 Xcode 8 - set value to slider not working

### ISSUE THREAD

**Issue by kineret321** [appium/appium#7362]
Hi,

Im using appuim 1.6.2-beta, XCUITestDriver version: 2.0.36, ios 10.0.1
trying to set slider value to "1.0" by send_keys:
element.send_keys("1.0")
and its not working return:
[debug] [iProxy] recv failed: Resource temporarily unavailable
[debug] [iProxy] recv failed: Operation not permitted

logs:

[Appium] Welcome to Appium v1.6.2
[Appium] Non-default server args:
[Appium]   log: '/Users/israellocal/Desktop/appium_log.txt'
[Appium]   showIOSLog: true
[Appium] Deprecated server args:
[Appium]   --show-ios-log => --default-capabilities '{"showIOSLog":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   showIOSLog: true
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"deviceName":"10.0.1","udid":"4ba95a2da3af6869344047620c1755dd23cdbc57","app":"/Users/israellocal/Downloads/FMLTester.ipa","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","appium-version":"1.6","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig","newCommandTimeout":0,"platformVersion":"10.0.1","fullReset":true,"platformName":"ios","automationName":"XCUITest"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"10.0.1","udid":"4ba95a2da3af6869344047620c1755dd23cdbc57","app":"/Users/israellocal/Downloads/FMLTester.ipa","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","appium-version":"1.6","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig","newCommandTimeout":0,"platformVersion":"10.0.1","fullReset":true,"platformName":"ios","automationName":"XCUITest"},null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   deviceName: '10.0.1'
[Appium]   udid: '4ba95a2da3af6869344047620c1755dd23cdbc57'
[Appium]   app: '/Users/israellocal/Downloads/FMLTester.ipa'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   appium-version: '1.6'
[Appium]   xcodeConfigFile: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig'
[Appium]   newCommandTimeout: 0
[Appium]   platformVersion: '10.0.1'
[Appium]   fullReset: true
[Appium]   platformName: 'ios'
[Appium]   automationName: 'XCUITest'
[Appium]   showIOSLog: true
[debug] [XCUITest] XCUITestDriver version: 2.0.36
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appium-version.
[BaseDriver] Session created with session id: baf08f25-757b-425d-b1f0-b06e964bfe9b
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [XCUITest] Available devices: 4ba95a2da3af6869344047620c1755dd23cdbc57
[debug] [XCUITest] Creating iDevice object with udid 4ba95a2da3af6869344047620c1755dd23cdbc57
[XCUITest] Determining device to run tests on: udid: '4ba95a2da3af6869344047620c1755dd23cdbc57', real device: true
[BaseDriver] Using local app '/Users/israellocal/Downloads/FMLTester.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/2016115-58905-153o681.0sgksurf6r/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/2016115-58905-153o681.0sgksurf6r/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/2016115-58905-153o681.0sgksurf6r/Payload/FMLTester.app'
[debug] [XCUITest] Checking whether app '/var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/2016115-58905-153o681.0sgksurf6r/Payload/FMLTester.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/var/folders/x7/g459t3xs3nz99lmm86jwvx140000gp/T/2016115-58905-153o681.0sgksurf6r/Payload/FMLTester.app': 'com.pingidentity.fmltester.enterprise'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset requested. Forcing app install after uninstall app
[debug] [XCUITest] App installed successfully.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Using Xcode configuration file: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig'
[debug] [XCUITest] Beginning test with command '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/bin/run-xcodebuild.sh --project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj --scheme WebDriverAgentRunner --destination id=4ba95a2da3af6869344047620c1755dd23cdbc57 --xcode-version 8 --xcode-config-file "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig"' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/israellocal/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/4C14BF6E-F2A2-4609-9231-757FD26FDACA/Session-WebDriverAgentRunner-2016-12-05_164652-O6Mh5e.log
[XCUITest] Detected that WebDriverAgent is running at url 'http://10.8.3.3:8100'
[XCUITest] WebDriverAgent started at url 'http://10.8.3.3:8100'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.pingidentity.fmltester.enterprise","arguments":[],"environment":{},"shouldWaitForQuiescence":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239","capabilities":{"device":"iphone","browserName":"FML Tester","sdkVersion":"10.0.1","CFBundleIdentifier":"com.pingidentity.fmltester.enterprise"}},"sessionId":"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239","status":0}
[debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
[debug] [JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239","status":0}
[Appium] New XCUITestDriver session created successfully, session baf08f25-757b-425d-b1f0-b06e964bfe9b added to master session list
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"deviceName":"10.0.1","udid":"4ba95a2da3af6869344047620c1755dd23cdbc57","app":"/Users/israellocal/Downloads/FMLTester.ipa","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","appium-version":"1.6","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Config.xcconfig","newCommandTimeout":0,"platformVersion":"10.0.1","fullReset":true,"platformName":"ios","automationName":"XCUITest","showIOSLog":true}
[HTTP] <-- POST /wd/hub/session 200 28918 ms - 747 
[HTTP] --> POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/timeouts/implicit_wait {"sessionId":"baf08f25-757b-425d-b1f0-b06e964bfe9b","ms":3000}
[debug] [MJSONWP] Calling AppiumDriver.implicitWait() with args: [3000,"baf08f25-757b-425d-b1f0-b06e964bfe9b"]
[debug] [XCUITest] Executing command 'implicitWait'
[debug] [BaseDriver] Set implicit wait to 3000ms
[debug] [MJSONWP] Responding to client with driver.implicitWait() result: null
[HTTP] <-- POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/timeouts/implicit_wait 200 7 ms - 76 
[HTTP] --> POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/element {"using":"id","sessionId":"baf08f25-757b-425d-b1f0-b06e964bfe9b","value":"automation_test_1.xml"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","automation_test_1.xml","baf08f25-757b-425d-b1f0-b06e964bfe9b"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 3000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239/element] with body: {"using":"id","value":"automation_test_1.xml"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"2BC959E8-82C8-4C1C-A7E1-259B30B2C7FF","type":"XCUIElementTypeStaticText","label":"automation test 1"},"sessionId":"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"2BC959E8-82C8-4C1C-A7E1-259B30B2C7FF","type":"XCUIElementTypeStaticText","label":"automation test 1"}
[HTTP] <-- POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/element 200 1273 ms - 185 
[HTTP] --> POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/element/2BC959E8-82C8-4C1C-A7E1-259B30B2C7FF/click {"sessionId":"baf08f25-757b-425d-b1f0-b06e964bfe9b","id":"2BC959E8-82C8-4C1C-A7E1-259B30B2C7FF"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/element/2BC959E8-82C8-4C1C-A7E1-259B30B2C7FF/click] to [POST http://localhost:8100/session/EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239/element/2BC959E8-82C8-4C1C-A7E1-259B30B2C7FF/click] with body: {"sessionId":"baf08f25-757b-425d-b1f0-b06e964bfe9b","id":"2BC959E8-82C8-4C1C-A7E1-259B30B2C7FF"}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"2BC959E8-82C8-4C1C-A7E1-259B30B2C7FF","value":"","sessionId":"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239"}
[JSONWP Proxy] Replacing sessionId EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239 with baf08f25-757b-425d-b1f0-b06e964bfe9b
[HTTP] <-- POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/element/2BC959E8-82C8-4C1C-A7E1-259B30B2C7FF/click 200 1664 ms - 118 
[HTTP] --> POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/element {"using":"id","sessionId":"baf08f25-757b-425d-b1f0-b06e964bfe9b","value":"inheritSlider"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","inheritSlider","baf08f25-757b-425d-b1f0-b06e964bfe9b"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 3000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239/element] with body: {"using":"id","value":"inheritSlider"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"786135E5-F3FF-4E01-B46D-7E9BA992F3E0","type":"XCUIElementTypeSlider","label":null},"sessionId":"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"786135E5-F3FF-4E01-B46D-7E9BA992F3E0","type":"XCUIElementTypeSlider","label":null}
[HTTP] <-- POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/element 200 1442 ms - 166 
[HTTP] --> POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/element/786135E5-F3FF-4E01-B46D-7E9BA992F3E0/value {"sessionId":"baf08f25-757b-425d-b1f0-b06e964bfe9b","id":"786135E5-F3FF-4E01-B46D-7E9BA992F3E0","value":["1",".","0"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["1",".","0"],"786135E5-F3FF-4E01-B46D-7E9BA992F3E0","baf08f25-757b-425d-b1f0-b06e964bfe9b"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [JSONWP Proxy] Proxying [GET /element/786135E5-F3FF-4E01-B46D-7E9BA992F3E0/attribute/type] to [GET http://localhost:8100/session/EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239/element/786135E5-F3FF-4E01-B46D-7E9BA992F3E0/attribute/type] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypeSlider\",\n  \"sessionId\" : \"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239\",\n  \"status\" : 0\n}"
[debug] [JSONWP Proxy] Proxying [POST /element/786135E5-F3FF-4E01-B46D-7E9BA992F3E0/value] to [POST http://localhost:8100/session/EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239/element/786135E5-F3FF-4E01-B46D-7E9BA992F3E0/value] with body: {"value":["1",".","0"]}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239","status":0}
[debug] [MJSONWP] Responding to client with driver.setValue() result: null
[HTTP] <-- POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/element/786135E5-F3FF-4E01-B46D-7E9BA992F3E0/value 200 7878 ms - 76 
[HTTP] --> POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/element {"using":"id","sessionId":"baf08f25-757b-425d-b1f0-b06e964bfe9b","value":"Home_Settings_Button"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","Home_Settings_Button","baf08f25-757b-425d-b1f0-b06e964bfe9b"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 3000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239/element] with body: {"using":"id","value":"Home_Settings_Button"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"Home_Settings_Button","description":"unable to find an element"},"sessionId":"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239","status":7}
[debug] [BaseDriver] Waited for 1043 ms so far
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239/element] with body: {"using":"id","value":"Home_Settings_Button"}
[HTTP] --> POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/element {"using":"id","sessionId":"baf08f25-757b-425d-b1f0-b06e964bfe9b","value":"Home_Settings_Button"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["id","Home_Settings_Button","baf08f25-757b-425d-b1f0-b06e964bfe9b"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"Home_Settings_Button","description":"unable to find an element"},"sessionId":"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239","status":7}
[debug] [BaseDriver] Waited for 2627 ms so far
[HTTP] <-- POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/element - - ms - - 
[HTTP] <-- POST /wd/hub/session/baf08f25-757b-425d-b1f0-b06e964bfe9b/element - - ms - - 
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239/element] with body: {"using":"id","value":"Home_Settings_Button"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"Home_Settings_Button","description":"unable to find an element"},"sessionId":"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239","status":7}
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 3000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239/element] with body: {"using":"id","value":"Home_Settings_Button"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"Home_Settings_Button","description":"unable to find an element"},"sessionId":"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239","status":7}
[debug] [BaseDriver] Waited for 1030 ms so far
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239/element] with body: {"using":"id","value":"Home_Settings_Button"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"Home_Settings_Button","description":"unable to find an element"},"sessionId":"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239","status":7}
[debug] [BaseDriver] Waited for 2620 ms so far
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239/element] with body: {"using":"id","value":"Home_Settings_Button"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"id","value":"Home_Settings_Button","description":"unable to find an element"},"sessionId":"EF9B2107-FE1B-46A9-AFB9-BBCD53BBC239","status":7}
[debug] [iProxy] recv failed: Resource temporarily unavailable
[debug] [iProxy] recv failed: Operation not permitted

**Comment by mykola-mokhnach** [comment]
Try

```bash
sudo chmod 777 /var/db/lockdown
```

**Comment by dpgraham** [comment]
Closing this as a duplicate. For progress on that, follow this issue:

https://github.com/appium/appium/issues/7435
