### ISSUE TITLE
Cordova hybrid only return NATIVE_APP context

### ISSUE THREAD

**Issue by Maaarek** [appium/appium#7365]
## The problem
Hi,

I am using Cordova  and  followed the steps on "Automating hybrid apps" already. I am trying to switch the context from NATIVE_APP to WEBVIEW_1. The only available context which I am getting is NATIVE_APP. (see logs file).

The is  "setWebContentsDebuggingEnabled = true;"  I can use google.chrome to navigate/debug throw the app.

Thank you for your time.
## Environment
Appium Version: 1.4.13.1
Desktop OS: Window 10
Visual Studio 2015
Mobile platform/version under  
Real device 
Appium CLI 

Logfile:
https://gist.github.com/Maaarek/198400a40b3f4a2707c3678af8dcbd40
Inside log file line: 138: Available Context

## Code To Reproduce Issue [ Good To Have ]
![codesnip](https://cloud.githubusercontent.com/assets/14011754/20903761/8215cc2e-bba1-11e6-853e-026ac3064b5f.JPG)

**Comment by jlipps** [comment]
Are you able to use Chromedriver at all to automate your application?

**Comment by Maaarek** [comment]
I haven't use Chromedriver. I only heard about Chromedriver but I haven't use Cd.

**Comment by jlipps** [comment]
OK, that is the next step in diagnosing this problem. Instructions for getting chromedriver and attaching to a webview are here: https://sites.google.com/a/chromium.org/chromedriver/getting-started/getting-started---android

**Comment by Maaarek** [comment]
It's done. Now I am getting a new error message inside the logfile

 info: [debug] Error: 'java -version' failed. Error: Command failed: 'java' is not recognized as an internal or external command,
> operable program or batch file.

**Comment by mayureshshirodkar** [comment]
This could be related to this issue:
https://github.com/appium/appium/issues/4597#issuecomment-164540456

**Comment by Maaarek** [comment]
It still doesn't work. System Variables -> Path +  JAVA_HOME

**Comment by raviraj-bidchat** [comment]
Guys can anybody help me in the same above issue.
I can only see Native and Chromium as my webviews, the actual webview of my App is not getting displayed in the console

I changed my hybrid .js file and changed line match pointing to my App
androidHybrid.listWebviews = function (cb) {
  logger.debug("Getting a list of available webviews");
  var webviews = [];
  var definedDeviceSocket = this.args.androidDeviceSocket;
  this.adb.shell("cat /proc/net/unix", function (err, out) {
    if (err) return cb(err);
    _.each(out.split("\n"), function (line) {
      line = line.trim();
      var webviewPid = line.match(/@?com.bidchatapp.bidchat_devtools_remote_(\d+)/);
      if (definedDeviceSocket) {
        if (line.indexOf("@" + definedDeviceSocket) ===
          line.length - definedDeviceSocket.length - 1) {
          if (webviewPid) {
            webviews.push(this.WEBVIEW_BASE + webviewPid[1]);
          } else {
            webviews.push(this.CHROMIUM_WIN);

>> I hope i need to change only Line match and nothing else

This is my appium console where i get error
nfo: [debug] Available contexts: NATIVE_APP,CHROMIUM
> info: [debug] Connecting to chrome-backed webview
> info: Chromedriver: Changed state to 'starting'
> info: Chromedriver: Set chromedriver binary as: C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
> info: Chromedriver: Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
> info: Chromedriver: No old chromedrivers seemed to exist
> info: Chromedriver: Spawning chromedriver with: C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=9515
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Can't stop process; it's not currently running)","origValue":"Can't stop process; it's not currently running"},"sessionId":"08af73bd-19db-48b6-9a0b-a8958e3e43a8"}
> info: <-- POST /wd/hub/session/08af73bd-19db-48b6-9a0b-a8958e3e43a8/context 500 296.376 ms - 280 
> info: [debug] Didn't get a new command in 60 secs, shutting down...
> info: Shutting down appium session
> info: [debug] Pressing the HOME button
> info: [debug] executing cmd: C:\Users\Raviraj\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0915f9e3a0d20a05 shell "input keyevent 3"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}


I'm stuck due to this, Please me out guys, i would really appreciate any help from you'll

**Comment by jlipps** [comment]
@raviraj-bidchat did you try switching to the chromium context?

**Comment by raviraj-bidchat** [comment]
@jlipps Yes jlipps, The above appium log was observed after switching to Chromium context.
Later I tried changing my hybrid.js file by referring this link https://github.com/ITKarel/ChromeDriver, After that i'm now getting NATIVE_APP,WEBVIEW_undefined


Below is new updated log with webview_undefined



 info: [debug] Available contexts: NATIVE_APP,WEBVIEW_undefined
> info: [debug] Responding to client with success: {"status":0,"value":["NATIVE_APP","WEBVIEW_undefined"],"sessionId":"dd9ae084-bab0-4ca7-9e93-dc05f1679c9f"}
> info: <-- GET /wd/hub/session/dd9ae084-bab0-4ca7-9e93-dc05f1679c9f/contexts 200 113.929 ms - 106 {"status":0,"value":["NATIVE_APP","WEBVIEW_undefined"],"sessionId":"dd9ae084-bab0-4ca7-9e93-dc05f1679c9f"}
> info: --> POST /wd/hub/session/dd9ae084-bab0-4ca7-9e93-dc05f1679c9f/context {"name":"WEBVIEW_undefined"}
> info: [debug] Getting a list of available webviews
> info: [debug] executing cmd: C:\Users\Raviraj\AppData\Local\Android\sdk\platform-tools\adb.exe -s 0915f9e3a0d20a05 shell "cat /proc/net/unix"
> info: [debug] Available contexts: NATIVE_APP,WEBVIEW_undefined
> info: [debug] Connecting to chrome-backed webview
> info: Chromedriver: Changed state to 'starting'
> info: Chromedriver: Set chromedriver binary as: C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
> info: Chromedriver: Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
> info: Chromedriver: No old chromedrivers seemed to exist
> info: Chromedriver: Spawning chromedriver with: C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=9515
> info: [debug] Responding to client with error: {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command. (Original error: Can't stop process; it's not currently running)","origValue":"Can't stop process; it's not currently running"},"sessionId":"dd9ae084-bab0-4ca7-9e93-dc05f1679c9f"}
> info: <-- POST /wd/hub/session/dd9ae084-bab0-4ca7-9e93-dc05f1679c9f/context 500 317.129 ms - 280 

Thanks for replying Jonathan, If possible please me on this, Thank you so much

**Comment by jlipps** [comment]
@raviraj-bidchat so you're using a crosswalk webview? And you are sure the new chromedriver is the correct binary from that other repo? If it's not working then I'm afraid I can't help further; Appium doesn't officially support the crosswalk webview because Chromedriver doesn't officially support it. You could ask @ITKarel for help though; maybe the android-hybrid.js code needs to be rebased on top of the latest.
