### ISSUE TITLE
Large disk cache usage from instruments

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7367]
@midopa commented on [Thu Sep 29 2016](https://github.com/appium/appium-instruments/issues/82)

I have iOS CI machines and they've run out of disk space. The culprit was large disk usage in /Library/Caches/com.apple.dt.instruments (25GB-54GB seen).

Should there be something in Appium that clears out old/stale cache files?

FWIW, users of Calabash ran into this as well and the team decided to implement to rotate the cache directories. 
https://github.com/calabash/run_loop/issues/276
https://github.com/calabash/run_loop/pull/304

I think maybe just deleting all but the last few subdirectories would be sufficient. I figure keeping a few around would avoid stepping on any other Appium process that might be running on the same machine.

One simple command line script:

```
ls -t1 /Library/Caches/com.apple.dt.instruments | grep -v '^\.\+$' | tail -n +5 | xargs rm -rf
```

---

@imurchie commented on [Thu Sep 29 2016](https://github.com/appium/appium-instruments/issues/82#issuecomment-250531159)

There _could_ be. I would say that if it were implemented, it should be behind an endpoint (so your test could hit it and delete the logs generated).

---

@jlipps commented on [Tue Oct 04 2016](https://github.com/appium/appium-instruments/issues/82#issuecomment-251541055)

Or maybe a server flag that turns on cache clearing between sessions? I don't necessarily like the idea of an endpoint that's just for appium internal housekeeping.

**Comment by mykola-mokhnach** [comment]
There is _clearSystemFiles_ capability since Appium release 1.6.1 Does it work for this purpose?

**Comment by jlipps** [comment]
It should. Closing this since even if it doesn't we're not likely to prioritize updating the instruments version of Appium.
