### ISSUE TITLE
Script threw an uncaught JavaScript error: Error getting next command

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7368]
@nghiadhd commented on [Thu Sep 08 2016](https://github.com/appium/appium-instruments/issues/79)

I wrote a script to test long run capability in 6 hours, However after 1 hour, I got exception from Appium and interrupt the test.

https://gist.github.com/nghiadhd/8bc7a1a7cb13f60379f9c1cf4d0337c1#file-bootstrap-log

Seem the data that we write to bootstrap.js make the js file wrong format

Device:
iPhone 6 - iOS 9.3.4

---

@nghiadhd commented on [Tue Sep 13 2016](https://github.com/appium/appium-instruments/issues/79#issuecomment-246659210)

@jlipps 

I see the root cause is the SafariLauncher was moved to background in long time and the OS is going to kill it, it makes the instrument exits with code 0 and the test will be interrupted. Do you know how to keep the SafariLauncher still alive or we must change the flow to exit instruments after launch SafariLauncher to avoid it interrupt the test
How do you think about it?

---

@jlipps commented on [Wed Sep 14 2016](https://github.com/appium/appium-instruments/issues/79#issuecomment-247184866)

We expect SafariLauncher to die, that's its whole purpose. So I doubt that's the problem. There may indeed be a bug here, but we'd need a way to reproduce it without waiting for it to randomly appear in 6 hours. Any ideas?

---

@nghiadhd commented on [Wed Sep 14 2016](https://github.com/appium/appium-instruments/issues/79#issuecomment-247210991)

Yep @jlipps 
I expected after the instrument invoke the SafariLauncher to launch the Safari Browser. The SafariLauncher goes to background and the instrument will be exit. 
But in the case, we have the long run test (we call driver.start and do a lot of test without call driver.quit). I see the instrument process is still exist (check by activity monitor)
After 1 hour, maybe the timeout in https://github.com/appium/appium-uiauto/blob/master/uiauto/vendors/mechanic.js  make the instrument exit and it interrupts the test script

I can reproduce by while doing the test, just force close the SafariLauncher by double press home button and swipe up the SafariLauncher. Log will be 

```
[iOSLog] [IOS_SYSLOG_ROW] Sep 15 08:40:12 iPhone-6 SpringBoard[58] <Warning>: BSXPCMessage received error for message: Connection interrupted
[iOSLog] [IOS_SYSLOG_ROW] Sep 15 08:40:13 iPhone-6 mediaserverd[28] <Notice>: '' com.bytearc.SafariLauncher(pid = 237) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None
[iOSLog] [IOS_SYSLOG_ROW] Sep 15 08:40:13 iPhone-6 assertiond[67] <Error>: assertion failed: 13F69: assertiond + 72572 [0B862A7D-6E8B-3778-AD17-C7694ECD5BCD]: 0x3
[debug] [Instruments] [INST] 2016-09-15 01:40:14 +0000 Fail: The target application appears to have died
[iOSLog] [IOS_SYSLOG_ROW] Sep 15 08:40:13 iPhone-6 Unknown[67] <Error>:
[iOSLog] [IOS_SYSLOG_ROW] Sep 15 08:40:13 iPhone-6 SpringBoard[58] <Warning>: Unable to get short BSD proc info for 237: No such process
[iOSLog] [IOS_SYSLOG_ROW] Sep 15 08:40:13 iPhone-6 SpringBoard[58] <Warning>: Application 'UIKitApplication:com.bytearc.SafariLauncher[0xc611]' exited voluntarily.
[iOSLog] [IOS_SYSLOG_ROW] Sep 15 08:40:13 iPhone-6 assertiond[67] <Error>: assertion failed: 13F69: assertiond + 72572 [0B862A7D-6E8B-3778-AD17-C7694ECD5BCD]: 0x3
[iOSLog] [IOS_SYSLOG_ROW] Sep 15 08:40:13 iPhone-6 Unknown[67] <Error>:
[iOSLog] [IOS_SYSLOG_ROW] Sep 15 08:40:13 iPhone-6 UserEventAgent[26] <Warning>: 360346818011: id=com.bytearc.SafariLauncher pid=237, state=0
[debug] [Instruments] [INST STDERR] 2016-09-15 08:40:14.320 instruments[2578:162387] Attempting to change event horizon while disengage
[debug] [Instruments] [INST] Instruments Trace Complete (Duration : 152.690430s; Output : /var/folders/my/chbbx01x2x7d9h1nq2qxbqy40000gn/T/appium-instruments/instrumentscli0.trace)
[debug] [Instruments] Instruments exited with code 0
[debug] [iOS] Deleting ios session
[debug] [UIAuto] Destroying instruments client socket.
[debug] [UIAuto] Closing socket server.
```

---

@nghiadhd commented on [Wed Sep 14 2016](https://github.com/appium/appium-instruments/issues/79#issuecomment-247216122)

@jlipps 

Seem the instrument got timeout 
https://github.com/appium/appium-uiauto/blob/master/uiauto/lib/commands.js#L23 

BTW, we still expect the instrument exit after launching Safari Browser

---

@jlipps commented on [Thu Sep 15 2016](https://github.com/appium/appium-instruments/issues/79#issuecomment-247298080)

Interesting. @imurchie my understanding was we ignored instruments startup failures for safarilauncher, but maybe instruments behavior changed or this is an edge case?

---

@tin-tran-logigear commented on [Thu Nov 10 2016](https://github.com/appium/appium-instruments/issues/79#issuecomment-259870418)

Can anyone update this issue? I have the same problem.

**Comment by dpgraham** [comment]
Closing. We no longer support Instruments.
