### ISSUE TITLE
Instruments doesn't always shut down on driver quit, leaks processes over time

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7370]
@vicwomg commented on [Mon May 23 2016](https://github.com/appium/appium-instruments/issues/72)

From the discussion here: 
https://discuss.appium.io/t/cannot-delete-session-driver-quit/9823

Instruments intermittently doesn't shut down and this log entry is shown

> [iOS] Instruments didn't shut down. Error: Instruments did not terminate after 5 seconds!
> [debug] [iOSLog] Stopping iOS log capture
> [debug] [iOS] Reset not set, not ending sim

Over time on long test suites, old instruments processes can start to stack up and lead to hangs on simulator launch.

Looks like the old instruments.js in appium 1.4.X was much more draconian about killing instruments, issuing SIGKILL

appium/node_modules/appium-instruments/lib/instruments.js, line 92

> Instruments.killAll = function () {
> logger.debug("Killall instruments");
> exec('pkill -9 instruments');
> };

Whereas the new one has a more polite approach:

appium/node_modules/appium-instruments/lib/instruments.js, line 755

> _logger2['default'].debug('Sending sigterm to instruments');
> this.proc.kill('SIGTERM');

Sure enough when I override driver.quit() and add a hard-coded "pkill -9 instruments" my long test runs no longer fail to launch nor leak instruments processes.

I also confirmed that changing the above to this.proc.kill('SIGKILL'); fixes the issue

Anyone see a reason not to just issue a SIGKILL? Not sure how instruments gets into this state, but it does happen with 100% reproducibility for one of my tests.

---

@midopa commented on [Wed Jun 08 2016](https://github.com/appium/appium-instruments/issues/72#issuecomment-224698167)

Seeing this behavior as well. After leaving my automation running I can end up with 10-50 orphaned instruments processes.

---

@midopa commented on [Wed Jun 08 2016](https://github.com/appium/appium-instruments/issues/72#issuecomment-224752675)

Looking at the code briefly, it seems the only hinderance would be SIGKILL doesn't trigger listeners/callbacks that less obtrusive signals do. The question is how important is `this.onShutdownDeferred.resolve();` at https://github.com/appium/appium-instruments/blob/master/lib/instruments.js#L364 ?

---

@igalep commented on [Mon Jun 20 2016](https://github.com/appium/appium-instruments/issues/72#issuecomment-227112214)

any update on this one ?
in appium ver 1.5.3 the problem still exists

---

@imurchie commented on [Mon Jun 20 2016](https://github.com/appium/appium-instruments/issues/72#issuecomment-227197726)

If `appium-instruments@3.8.3` does not fix it, then I'm not sure what to do. It implements what @midopa suggested above.

---

@igalep commented on [Thu Jun 23 2016](https://github.com/appium/appium-instruments/issues/72#issuecomment-228048178)

@imurchie if I execute **pkill -9 instruments** by using terminal , I do able to terminate running instruments , but trough the code it doesn't work ...

maybe permission issues ?

**Comment by igalep** [comment]
Any chance to solve it for appium 1.6.1 ?

Thanks
