### ISSUE TITLE
appium kills all instruments processes

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7373]
@aluedeke commented on [Thu Nov 12 2015](https://github.com/appium/appium-instruments/issues/50)

We currently experiencing issues running parallel tests with appium on the same host (which is technical possible since some time).

Fortunately testing fails randomly. We currently believe thats because appium is trying to kill all instrument processes on an host. I think that is a super ugly behaviour and should be changed if possible (or must be at least configurable).

@sebv @lbielski do you have some opinions on that?

---

@lbielski commented on [Thu Nov 12 2015](https://github.com/appium/appium-instruments/issues/50#issuecomment-156313004)

Yes, this is not a good behaviour when Appium is not run locally on a single device.
We have successfully tested running multiple Appium sessions in parallel on the same host and it does work (you just have to provide different `tmp` folders as a parameter), but killing all of the `instruments` processes also messes up with other running Appium sessions.

I understand that there is a need to kill `instruments` sometimes and for that we need to link Appium sessions to instruments instance. You can kind of `tag` a process by starting it with an environmental variable, for example `APPIUM_SESSION_ID=<session_id>./`. Then, when you need instruments to be restarted you can search for a process which contains this env variable. On Mac it can be done by `ps -p <pid> -wwwE`. This way you can uniquely identify instruments instance for a specific Appium session.
I would think it makes sense to make this an option for people running Appium sessions on parallel.

Another and simpler option would be to provide an option to disable this behaviour, so when instruments are not working Appium just gives up without trying to fix instruments.  

---

@aluedeke commented on [Sun Nov 15 2015](https://github.com/appium/appium-instruments/issues/50#issuecomment-156941985)

@jlipps @bootstraponline any feedback?

---

@jlipps commented on [Mon Nov 16 2015](https://github.com/appium/appium-instruments/issues/50#issuecomment-157093716)

i do think appium tries to kill all instruments processes, which is bad. i'm not sure if this same strategy is used in appium 1.5 though. @imurchie ?

---

@imurchie commented on [Mon Nov 16 2015](https://github.com/appium/appium-instruments/issues/50#issuecomment-157099491)

1.5 does still do this. I'm not sure why, other than it always has.

I'm all for making this the default behaviour and putting the other behind a desired capability. We will have to investigate the best route for this.

---

@aluedeke commented on [Tue Nov 17 2015](https://github.com/appium/appium-instruments/issues/50#issuecomment-157333008)

@imurchie we are currently evaluating if providing a custom path to pkill would be sufficient, will ping back when we now more

---

@saikrishna321 commented on [Mon Dec 28 2015](https://github.com/appium/appium-instruments/issues/50#issuecomment-167715858)

@aluedeke any updates on this ?

**Comment by ohadschn** [comment]
I believe this is still relevant in Appium 1.6.3 with an `automationName` of `XCUITest` (for iOS 10), since it kills all `xcodebuild` and `iproxy` processes, possibly while they are being used by a parallel `appium` instance: https://github.com/appium/appium-xcuitest-driver/blob/65257b414a6a19f858d044bdc5cdec3b21af822b/lib/webdriveragent.js#L330.

**Comment by felyppers** [comment]
I'm having the same problem. Running tests in parallel, when instruments behaves well, all tests run fine. However, if it fails to launch the first time in one or more devices and launches during the retries, all running appium session crash because instruments gets killed. I thought this was not supposed to happen since each device have its own port and temporary folder to run its instruments session independently. Any news on this issue?

**Comment by jlipps** [comment]
Thanks for the workaround @felyppers. Given that we're not planning on maintaining the old Instruments-based driver moving forward, we're not going to spend time fixing this since it's not an issue in the new xcuitest. But @ohadschn makes a good point that if we kill all xcodebuild processes, it might interrupt the flow of another test. @mykola-mokhnach or @imurchie did we have any plans to restrict that to PID?

**Comment by imurchie** [comment]
We do. Right now it happens as a stop-gap measure that might not need to happen any more.

**Comment by alexander-poulikakos** [comment]
> Thanks for the workaround @felyppers. Given that we're not planning on maintaining the old Instruments-based driver moving forward, we're not going to spend time fixing this since it's not an issue in the new xcuitest. 

@jlipps Does this mean Appium will never support testing on multiple devices in parallel, for devices with a platformVersion that requires UiAutomation?

**Comment by imurchie** [comment]
I don't see anywhere in the codebase where `killAllInstruments` is actually called.

**Comment by alexander-poulikakos** [comment]
@imurchie For me the "Kill instruments" command is happening for two reasons. See logs below. Maybe this can help you locate where the "kill instruments" is called from, if from Appium at all.

1) When something goes wrong when launching the app, then I see this in the log
```
[debug] [iOS] Starting UIAutoClient, and launching Instruments.
[debug] [UIAuto] Instruments socket server started at /var/folders/f7/7x9ly9hx03vd9r1pl_rppl200000gp/T/appium7396881024154540551/instruments_sock
[debug] [Instruments] Instruments is at: /Applications/Xcode7.app/Contents/Developer/usr/bin/instruments
[debug] [Instruments] Attempting to launch instruments, this is try #1
[Instruments] Launching instruments
[debug] [Instruments] Attempting to run app on real device with UDID '73e0249e89baa62aedcb0372afe7048debf492a6'
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode7.app/Contents/Developer/usr/bin/instruments -t /Applications/Xcode7.app/Contents/Applications/Instruments.app/Contents/PlugIns/AutomationInstrument.xrplugin/Contents/Resources/Automation.tracetemplate -D /var/folders/f7/7x9ly9hx03vd9r1pl_rppl200000gp/T/appium7396881024154540551/appium-instruments/instrumentscli0.trace -w 73e0249e89baa62aedcb0372afe7048debf492a6 com.my.bundle.id -e UIASCRIPT "/Users/alexanderpoulikakos/Library/Application Support/appium/bootstrap/bootstrap-365db28672ebdc12.js" -e UIARESULTSPATH /var/folders/f7/7x9ly9hx03vd9r1pl_rppl200000gp/T/appium7396881024154540551/appium-instruments'
[debug] [Instruments] And extra without-delay env: {}
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}
[debug] [Instruments] [INST STDERR] 2017-04-24 15:58:11.844 instruments[97393:5978484] WebKit Threading Violation - initial use of WebKit from a secondary thread.
[Instruments] Instruments socket client never checked in; timing out (global)
[debug] [Instruments] Kill instruments
[debug] [Instruments] Sending SIGTERM
[debug] [Instruments] [INST] Instruments Trace Complete (Duration : 88.385246s; Output : /var/folders/f7/7x9ly9hx03vd9r1pl_rppl200000gp/T/appium7396881024154540551/appium-instruments/instrumentscli0.trace)
[debug] [Instruments] Instruments exited with code: 0
[Instruments] Error launching instruments: Instruments never checked in
```

2) When`AppiumDriver.closeApp()` is called, an "Kill instruments" is also issued.
```
[debug] [MJSONWP] Calling AppiumDriver.closeApp() with args: ["3bc15254-e903-4b55-a680-3cbbf64faf07"]
[debug] [iOS] Executing iOS command 'closeApp'
[debug] [UIAuto] Destroying instruments client socket.
[debug] [UIAuto] Closing socket server.
[debug] [UIAuto] Instruments socket server was closed
[debug] [Instruments] Starting shutdown.
[debug] [Instruments] Kill instruments
[debug] [Instruments] Sending SIGTERM
```

**Comment by imurchie** [comment]
That log line comes from https://github.com/appium/appium-instruments/blob/master/lib/instruments.js#L358-L385, which only kills the single Instruments process. It should not kill everything.

**Comment by dpgraham** [comment]
@imurchie Is this still an open issue?

**Comment by imurchie** [comment]
I don't think so. It's Instruments, so deprecated.
