### ISSUE TITLE
UiAutomator instance thowing - IllegalStateException: UiAutomation not connected! exception

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7377]
@sravanmedarapu commented on [Tue Apr 19 2016](https://github.com/appium/appium-uiautomator2-driver/issues/19)

below is the stacktrace 

```
04-19 19:01:38.116  5105  5127 W System.err: java.lang.IllegalStateException: UiAutomation not connected!
04-19 19:01:38.116  5105  5127 W System.err:    at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:971)
04-19 19:01:38.116  5105  5127 W System.err:    at android.app.UiAutomation.waitForIdle(UiAutomation.java:577)
04-19 19:01:38.116  5105  5127 W System.err:    at android.support.test.uiautomator.UiAutomatorBridge.waitForIdle(UiAutomatorBridge.java:112)
04-19 19:01:38.116  5105  5127 W System.err:    at android.support.test.uiautomator.UiDevice.waitForIdle(UiDevice.java:639)
04-19 19:01:38.116  5105  5127 W System.err:    at android.support.test.uiautomator.UiDevice.waitForIdle(UiDevice.java:629)
04-19 19:01:38.116  5105  5127 W System.err:    at android.support.test.uiautomator.UiDevice.getWindowRoots(UiDevice.java:1074)
04-19 19:01:38.116  5105  5127 W System.err:    at android.support.test.uiautomator.UiDevice.findObject(UiDevice.java:164)
04-19 19:01:38.116  5105  5127 W System.err:    at io.appium.uiautomator2.handler.FindElement.findElememnt(FindElement.java:71)
04-19 19:01:38.116  5105  5127 W System.err:    at io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:45)
04-19 19:01:38.116  5105  5127 W System.err:    at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:159)
04-19 19:01:38.116  5105  5127 W System.err:    at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:150)
04-19 19:01:38.117  5105  5127 W System.err:    at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:45)
04-19 19:01:38.117  5105  5127 W System.err:    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
04-19 19:01:38.117  5105  5127 W System.err:    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
04-19 19:01:38.117  5105  5127 W System.err:    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
04-19 19:01:38.117  5105  5127 W System.err:    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
04-19 19:01:38.117  5105  5127 W System.err:    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
04-19 19:01:38.117  5105  5127 W System.err:    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
04-19 19:01:38.118  5105  5127 W System.err:    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:148)
04-19 19:01:38.118  5105  5127 W System.err:    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
04-19 19:01:38.118  5105  5127 W System.err:    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
04-19 19:01:38.118  5105  5127 W System.err:    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
04-19 19:01:38.118  5105  5127 W System.err:    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
04-19 19:01:38.118  5105  5127 W System.err:    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
04-19 19:01:38.118  5105  5127 W System.err:    at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
04-19 19:01:38.118  5105  5127 W System.err:    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
04-19 19:01:38.118  5105  5127 W System.err:    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
04-19 19:01:38.118  5105  5127 W System.err:    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
04-19 19:01:38.118  5105  5127 W System.err:    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
04-19 19:01:38.118  5105  5127 W System.err:    at java.lang.Thread.run(Thread.java:818)
```

This is happening only when we are doing e2e testing (after uiautomator2 driver+server integration). However this is not reproduced while testing the server part independently.

below are the logcat and server console logs
abd logcat:
https://gist.github.com/sravanmedarapu/e5c3193f143196b60a81298946060678#file-adb_logcat

appium server log:
https://gist.github.com/sravanmedarapu/e5c3193f143196b60a81298946060678#file-appium_console_log

Observations:
throwing above exception immediately after executing below statement in logcat

`W WindowManager: Attempted to remove non-existing token: android.os.Binder@2728fc2`

---

@bootstraponline commented on [Wed Apr 20 2016](https://github.com/appium/appium-uiautomator2-driver/issues/19#issuecomment-211935213)

related source links:
- [same issue in droiddriver](https://github.com/appium/droiddriver/blob/72a40802f8e7d24a3175e09adc4b44a89df54f38/src/io/appium/droiddriver/uiautomation/UiAutomationContext.java#L48)
- [uiautomator2 sources](https://github.com/bootstraponline/uiautomator2)
- [uiautomator2 disconnect line](https://github.com/android/platform_frameworks_base/blob/master/core/java/android/app/UiAutomation.java#L969)
- [window manager issue](https://android.googlesource.com/platform/frameworks/base/+/baf6bef001a582fea275bf891294cf1fe9d5472e/services/core/java/com/android/server/wm/WindowManagerService.java#3604)
- [uiautomator bug reported upstream](https://github.com/googlesamples/android-testing/issues/89)

---

@sravanmedarapu commented on [Wed May 18 2016](https://github.com/appium/appium-uiautomator2-driver/issues/19#issuecomment-219984056)

Tried by using 3rd party module called [adbKit](https://github.com/appium/appium-uiautomator2-driver/blob/master/lib/uiautomator2.js#L90) instead of existing [appium-adb](https://github.com/appium/appium-uiautomator2-driver/blob/master/lib/uiautomator2.js#L72) to invoke instrument test and working fine.

Need to figure out the what is going wrong with appium-adb module.

**Comment by jlipps** [comment]
@sravanmedarapu did you ever have a chance to look into this one?

**Comment by andreiaionitoaiesv** [comment]
Any updates on this? I'm using aws device farm. After the first test, Appium is failing to start. After looking in logcat seems that UIAutomation is not connected.

**Comment by auto-mator** [comment]
anyone??

**Comment by grvermeulen** [comment]
Any updates on this? A work around or fix?

**Comment by PurushothamQA** [comment]
Did any one find resolution/workaround for this. If so, please let us know.

**Comment by saikrishna321** [comment]
@PurushothamQA can u please provide more details, server logs and code to reproduce

**Comment by PurushothamQA** [comment]
Hey @saikrishna321 , 
1. Using "shell  am instrument" to run the tests.
2. M triggering this command through a test apk where I have a button to trigger the command.
3. At the initial point itself, I get the below error
` I/TestRunner: java.lang.IllegalStateException: UiAutomation not connected!
        at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:971)
        at android.app.UiAutomation.getRootInActiveWindow(UiAutomation.java:414)
        at android.support.test.uiautomator.UiAutomatorBridge.getRootInActiveWindow(UiAutomatorBridge.java:82)
        at android.support.test.uiautomator.QueryController.getRootNode(QueryController.java:170)
        at android.support.test.uiautomator.QueryController.findAccessibilityNodeInfo(QueryController.java:149)
        at android.support.test.uiautomator.QueryController.findAccessibilityNodeInfo(QueryController.java:138)
        at android.support.test.uiautomator.UiObject.findAccessibilityNodeInfo(UiObject.java:188)
        at android.support.test.uiautomator.UiObject.waitForExists(UiObject.java:928)
        at android.support.test.uiautomator.UiObject.exists(UiObject.java:979)`

This actually works well if I trigger through Studio. But the requirement is that our automation should trigger from device itself.

**Comment by saikrishna321** [comment]
How is this related to appium ?

**Comment by mykola-mokhnach** [comment]
This looks like a third party issue to me

**Comment by Vishnu-Jmatics** [comment]
I think it's due to adding test dependencies in gradle. Like 
testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner" or any testing dependencies like espresso

**Comment by git-wasim** [comment]
You can try with below capabilities:-
caps.setCapability("automationName", "uiautomator2");
