### ISSUE TITLE
Waiting page loading fails, if trying to open with lots of content on real IOs Device

### ISSUE THREAD

**Issue by APshenkin** [appium/appium#7380]
## The problem

Page loading fails, if trying to open with lots of content on real IOs Device because of failing ruunning script 
```
Sending javascript command (function (){ return document.readyState; })()
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
[MJSONWP] Encountered internal error running command: TimeoutError: operation timed out
    at afterTimeout (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/timers.js:16:15)
    at Timeout.timeoutTimeout (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/timers.js:59:9)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

```

## Environment

* Appium version: 1.6.2
* Desktop OS/version used to run Appium: OS X El Capitan 10.11.6
* Node.js version: 6.9.1 LTS
* Mobile platform/version under test: IOs 8.1.3
* Real device or emulator/simulator: real IPad mini

## Details

When trying to open page with lots of content in Safari, after html page loading we try to run script to check document readyState. But if on page you have a lot of javascripts, readyState will be completed after some delay.  But appium fails during script execution because of operation timed out. Setting scripts and page load delay doesn't fix it.

## Link to Appium logs

https://gist.github.com/APshenkin/a1eade0efd432442f5ac9f34d5318e66

## Code To Reproduce Issue [ Good To Have ]

Try to open https://ru.4game.com page

here is desired capabilities:
desiredCapabilities: {
                platformName: "iOS",
                deviceName: "iPad Mini",
                browserName: "Safari",
                udid: "UDID",
                platformVersion: "8.1.3"
            },
timeouts: {
                script: 30000,
                implicit: 30000,
                ['page load']: 30000 // ms
            }

**Comment by yoosufm** [comment]
I am having same issue. Any solution for this. Thanks in advance.

**Comment by jlipps** [comment]
Appium itself already checks the readyState of the loading page, and returns control to you when the page is ready. Thus there should be no reason for you to check this yourself. If the page never loads, then that's a problem with the page, and not with Appium. Closing this unless you think Appium is doing something wrong in loading the page.

**Comment by yoosufm** [comment]
@jlipps I am getting this error after just after switch to Webview. Any idea?

**Comment by yoosufm** [comment]
@jlipps do we need provisioning profile when run Appium test on Apple real device.

**Comment by RufusAnderson** [comment]
I got the same issue.Is there any resolution to this?

Safari launches and loads the URL --> Immediately the execution stopped
Appium version - v1.6.3

Terminal Logs:
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Page.navigate","...
[debug] [RemoteDebugger] Receiving WebKit data: {"result":{},"id":1}
[debug] [RemoteDebugger] Found handler for message '1'
[debug] [RemoteDebugger] Received page navigated message: {"result":{},"id":1}
[debug] [RemoteDebugger] Waiting for dom...
[debug] [RemoteDebugger] Page loaded, verifying whether ready
[debug] [RemoteDebugger] Checking document readyState
[debug] [RemoteDebugger] Sending javascript command (function (){ return document.readyState; })()
[debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
[MJSONWP] Encountered internal error running command: TimeoutError: operation timed out
at afterTimeout (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/timers.js:16:15)
at Timeout.timeoutTimeout [as _onTimeout] (/usr/local/lib/node_modules/appium/node_modules/bluebird/js/main/timers.js:59:9)
at ontimeout (timers.js:386:14)
at tryOnTimeout (timers.js:250:5)
at Timer.listOnTimeout (timers.js:214:5)

Eclipse console:
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: operation timed out (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 6.54 seconds
Build info: version: 'unknown', revision: '5234b32', time: '2017-03-10 09:00:17 -0800'
Eclipse code snippet:
AppiumDriver driver;
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("deviceName", "iPhone 6s");
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("platformVersion", "9.3.4");
capabilities.setCapability("browserName", "safari");
capabilities.setCapability(MobileCapabilityType.UDID, "9e8b4415d7a2ecbc934dea32ef72ad00091eb4xx");
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("xcodeOrgId", "UR7996XGXX");
capabilities.setCapability("xcodeSigningId", "iPhone Developer");
capabilities.setCapability("newCommandTimeout", "45000");

	driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"),capabilities);
	
	//driver = new IOSDriver(new URL("http://localhost:4723/wd/hub"),capabilities);
	driver.get("https://test-site.com");
