### ISSUE TITLE
getPageSource() - return elements from another page

### ISSUE THREAD

**Issue by pisarenco92** [appium/appium#7381]
## The problem

When the script navigates to HomePage and executes getPageSource() returns the correct elements. After the script navigates to another page SoonPage, getPageSource() returns elements from HomePage. I spent a lot of time to investigate but I didn't find a solution.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.2
* Desktop OS/version used to run Appium: macOS Sierra
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator

## Details

I have added timeouts - same results

**Comment by mykola-mokhnach** [comment]
Do you see any errors like this in simulator logs?

```
[debug] [WebDriverAgent] Sim: Nov 14 09:39:09 vision XCTRunner[45364]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessib
ilityElement: 0x61000024c510> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
```

**Comment by pisarenco92** [comment]
@mykola-mokhnach No
https://gist.github.com/pisarenco92/159f0efb75572dfd7821b21dbc5420ed

**Comment by jtappi** [comment]
I dont want to steer away from @pisarenco92 original issue, but am wondering what the error @mykola-mokhnach posted is about.  

@mykola-mokhnach I am seeing this error during tests runs although, for some elements it eventually recognizes the element and moves on (doesnt work with the Picker Wheel though).  

debug] [WebDriverAgent] Sim: Dec  6 07:05:23 myApple XCTRunner[75180]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x6000002552a0> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1

**Comment by qamonstir** [comment]
I have same error as @jtappi

**Comment by mykola-mokhnach** [comment]
Welcome to the [club](https://github.com/facebook/WebDriverAgent/issues/372) then.

**Comment by mykola-mokhnach** [comment]
@pisarenco92 I think it would be better to post your issue directly to [WDA](https://github.com/facebook/WebDriverAgent/issues), since Appium itself just proxies what it gets from WDA server.
