### ISSUE TITLE
Appium uses outdated /source WDA API call

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#7382]
## The problem

WDA has deprecated /source call using POST method and it will be removed soon. It is recommended to use /source call with GET or, even better, /source/json and /source/xml calls, which have been merged [recently](https://github.com/facebook/WebDriverAgent/pull/389)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OSX 10.11
* Node.js version (unless using Appium.app|exe): 6
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: -
* Appium CLI or Appium.app|exe: CLI

**Comment by jlipps** [comment]
@mykola-mokhnach makes sense. Any interest in taking this change on? Should be pretty minimal.

**Comment by jlipps** [comment]
Acceptance criteria:
* [ ] xcuitest-driver uses new WDA source endpoint and returns XML directly
* [ ] XML output compared with current output to confirm no breaking changes in format
