### ISSUE TITLE
[iOS] Appium Closes App During Test

### ISSUE THREAD

**Issue by raymondlapak** [appium/appium#7383]
## The problem

So today I updated my Appium from version 1.6.1 into 1.6.2. After updating, I tried to run the existing tests (tens of them) and surprisingly suddenly tests are failing because Appium or WDA closes the apps in the middle of tests, hence making finding element impossible thing to do. This happens on iOS testing.

The interesting thing is that I then uninstalled my Appium 1.6.2 (by npm) to go back to 1.6.1 only to find the behaviour of Appium closes apps in the middle of tests is still there.

Below is the log file from command line. I suspect it  tries to relaunch another session of apps while actually it is currently running one.

```
debug] [XCUITest] Log file for xcodebuild test: /Users/raymondluckysumargo/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/A1FCF61E-5BAD-4567-9363-04759BA4148F/Session-WebDriverAgentRunner-2016-12-06_205504-HKTBwX.log
[debug] [WebDriverAgent] Sim: Dec  6 20:55:04 Raymonds-MacBook-Pro CoreSimulatorBridge[12181]: Requesting installation of file:///Users/raymondluckysumargo/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/ with options: {
[debug] [WebDriverAgent] Sim: 	    CFBundleIdentifier = "com.apple.test.WebDriverAgentRunner-Runner";
[debug] [WebDriverAgent] Sim: 	    PackageType = Developer;
[debug] [WebDriverAgent] Sim: 	    SimulatorRootPath = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";
[debug] [WebDriverAgent] Sim: 	    SimulatorUserPath = "/Users/raymondluckysumargo/Library/Developer/CoreSimulator/Devices/694B5617-59CA-4A51-A0EC-3A7514967587/data";
[debug] [WebDriverAgent] Sim: 	}
[HTTP] --> POST /wd/hub/session/7b15f215-1d90-4a9b-ac83-be3b581c6de8/element {"using":"name","value":"Stop"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["name","Stop","7b15f215-1d90-4a9b-ac83-be3b581c6de8"]
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.2, 1.6.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.1, 1.6.0-beta3
* Desktop OS/version used to run Appium: Mac OSX
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
It would be more useful to have full device log.

**Comment by raymondlapak** [comment]
The problem lies on the XCUITestDriver, as I force downgrade the XCUITestDriver to 2.0.34, tests are back up and running well but failing when I use 2.4.0. Closing this and will raise more detailed logs on appium-xcuitest-driver GitHub instead.
