### ISSUE TITLE
Allow custom sigalg, digestalg

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7384]
@bootstraponline commented on [Thu Jul 31 2014](https://github.com/appium/appium-adb/issues/32)

Custom sigalg / digestalg has been requested on the mailing list.

https://github.com/appium/appium-adb/blob/af9fd45a94dd1cd058a6008e07d5783ec834aedf/lib/adb.js#L401

---

@imurchie commented on [Thu Jul 31 2014](https://github.com/appium/appium-adb/issues/32#issuecomment-50784918)

:+1: 

---

@jlipps commented on [Thu Jul 31 2014](https://github.com/appium/appium-adb/issues/32#issuecomment-50801639)

let's do this for appium 1.3

**Comment by mykola-mokhnach** [comment]
I assume this is now obsolete
