### ISSUE TITLE
Add methods to get and set the battery details

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7389]
@imurchie commented on [Fri Jan 29 2016](https://github.com/appium/appium-adb/issues/133)

How much control we want to give is up in the air.

Getting the status:

```
👻 ➤ adb shell dumpsys battery
Current Battery Service state:
  AC powered: true
  USB powered: false
  Wireless powered: false
  status: 2
  health: 2
  present: true
  level: 89
  scale: 100
  voltage: 0
  temperature: 0
  technology: Li-ion
```

Setting the status:

```
👻 ➤ adb shell dumpsys battery set
Dump current battery state, or:
  set ac | usb | wireless | status | level | invalid <value>
```

---

@filmaj commented on [Fri Jan 29 2016](https://github.com/appium/appium-adb/issues/133#issuecomment-176879148)

+1 !

---

@SrinivasanTarget commented on [Tue Feb 09 2016](https://github.com/appium/appium-adb/issues/133#issuecomment-181961127)

+1

**Comment by filmaj** [comment]
I would still love to see this land :)

**Comment by pavanbachu0604** [comment]
Can we add method for iOS devices so as to get details about device parameters like memory consumption, battery and CPU Consumption ?

**Comment by jlipps** [comment]
@pavanbachu0604 do you know of a way to programmatically retrieve those details for ios?

**Comment by pavanbachu0604** [comment]
@jlipps: we can use iprofiler from terminal to invoke the CPU and Memory Usages

**Comment by jlipps** [comment]
I think @vrunoa is working on this in https://github.com/appium/appium-android-driver/pull/236

**Comment by mykola-mokhnach** [comment]
The necessary additions to the driver have been merged to Appium beta
