### ISSUE TITLE
Support for multiple appWaitActivity

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7390]
@email2vimalraj commented on [Thu Feb 11 2016](https://github.com/appium/appium-adb/issues/138)

If the appWaitActivity capability is comma-sepearted, like this:
`appWaitActivity: com.example.demo.activities.Activity1,com.example.demo.activities.Activity2`, then the `launchApp` fails.

The reason is, in `adb.js`, we are doing this in the method `waitForActivityOrNot`:
1. Parsing the relative name of the activity given
2. Then we are splitting by comma on the relative name (Refer: https://github.com/appium/appium-adb/blob/v1.7.5/lib/adb.js#L1285)

However, it should be:
1. Split by comma first
2. then we should parse the relative name of the activity.

Since `appium v1.4.6` is dependent on `appium-adb v1.7.5`, this leads to the failure of automation. I can send you the PR for 1.7.5 if you confirm this is a valid bug.

---

@imurchie commented on [Thu Feb 11 2016](https://github.com/appium/appium-adb/issues/138#issuecomment-183048379)

Can you upgrade to Appium 1.5 and try again? Further work on dependencies of 1.4 are not going to be done.

---

@imurchie commented on [Mon Feb 22 2016](https://github.com/appium/appium-adb/issues/138#issuecomment-187275432)

Any changes on upgrade? I don't think that it is currently a feature to allow multiple wait packages/activities. It could be added at some point, though.

---

@email2vimalraj commented on [Mon Feb 22 2016](https://github.com/appium/appium-adb/issues/138#issuecomment-187463165)

Yes, I don't see Appium 1.5 support Multiple activities. I would suggest we should support this in 1.5. I'll see if I can send a PR for this.

---

@imurchie commented on [Tue Feb 23 2016](https://github.com/appium/appium-adb/issues/138#issuecomment-187765327)

That would be awesome! Otherwise we can add it to our list of things to do.

**Comment by KazuCocoa** [comment]
Looks finished by `appium-adb@2.17.4`
