### ISSUE TITLE
Optional Intent Arguments being stripped away

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7391]
@hariskhaliq commented on [Wed Aug 31 2016](https://github.com/appium/appium-adb/issues/170)

## The problem

Optional Intent Arguments being stripped away when adb gets executed.
## Environment
- Appium version **v1.5.3**
- Last Appium version that did not exhibit the issue: **Didn't try an older version**
- Desktop OS/version used to run Appium: **Mac OS v10.11**
- Node.js version (unless using Appium.app|exe): Using **Appium.exe**
- Mobile platform/version under test: **Android 6.0**
- Real device or emulator/simulator: **Emulator**
- Appium CLI or Appium.app|exe: **appium.exe**
## Details

Detail inside gist.
## Link to Appium logs

https://gist.github.com/hariskhaliq/559fb8998a1bcad849ce43d28eba7b05

**Comment by dpgraham** [comment]
This has been fixed already (see https://github.com/appium/appium-adb/commit/5db0b1acafe6f522b00419df6373353d1e2c2f6a). Internal hyphens were breaking the regex that was used to parse the 'optionalIntentArguments' argument.
