### ISSUE TITLE
Testing system apps

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7393]
@rickybscs commented on [Tue Nov 15 2016](https://github.com/appium/appium-adb/issues/183)

Hi there, I have a situation where our app installs as a system app.  Appium tries to do a pm list with -3 parameter which never returns our package.  It would need to use -s

In any case, the issue is that Appium is not able to launch our activity.  If I run the exact same shell am start command from the command line it works fine.

Are there any special flags I need to use to get appium to automate system apps?

**Comment by imurchie** [comment]
This has been fixed.
