### ISSUE TITLE
touch actions & 'cancel'

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7396]
@scottdixon commented on [Fri Sep 11 2015](https://github.com/appium/appium-android-driver/issues/37)

"Rethink the gesture API in light of spec changes. Cancel might not even be there."

```
commands.doTouchAction = async function (action, opts) {
   ...
    case 'cancel':
      // TODO: clarify behavior of 'cancel' action and fix this
      log.warn("Cancel action currently has no effect");
      break;
   ...
```

**Comment by dpgraham** [comment]
This doesn't have enough details. Going to close this.
