### ISSUE TITLE
Issues with select date from the datepicker with Appium for Android Driver

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7398]
@niranjanparija commented on [Thu Feb 04 2016](https://github.com/appium/appium-android-driver/issues/91)

Hi,I am facing issues to select date from the datepicker with Appium for Android Driver.Please check the attached screenshots of the Calender I am looking for.

I have already tried with element.clear() followed by element.sendkeys("text"),but its not working.

Also I tried to work with Scroll to followed by TouchAction ,where its working till selecting the Year ,but after that its failed to select the date and month which should be selected from the screenshot named as DatePicker2.

Can anyone please suggest me any workout .
![daypicker1](https://cloud.githubusercontent.com/assets/16086474/12818547/41dde152-cb4f-11e5-9103-f1730b1f3080.PNG)
![daypicker2](https://cloud.githubusercontent.com/assets/16086474/12818552/44d5feee-cb4f-11e5-9815-92a7aa436885.PNG)
![daypicker3](https://cloud.githubusercontent.com/assets/16086474/12818554/472640aa-cb4f-11e5-8b72-fec568533c5f.PNG)

---

@niranjanparija commented on [Fri Feb 05 2016](https://github.com/appium/appium-android-driver/issues/91#issuecomment-180412205)

Can anyone please suggest on this ,how to tackle the issue.So far tried with all the possible options like DatePicker,Number Picker with Xpath,Class,SendKeys,Scroll To and unfortunately nothing works so far.

---

@niranjanparija commented on [Fri Feb 05 2016](https://github.com/appium/appium-android-driver/issues/91#issuecomment-180412796)

Facing the same issue with attached calender also.
![2nd calender](https://cloud.githubusercontent.com/assets/16086474/12851266/dc8d993c-cc20-11e5-8ca0-4d1dbc1f7620.PNG)

---

@niranjanparija commented on [Mon Feb 08 2016](https://github.com/appium/appium-android-driver/issues/91#issuecomment-181356541)

@TikhomirovSergey - can you please guide on this issue

**Comment by kbalakumar99** [comment]
@imurchie  Could you throw some light on this?

Is it supported to send keys to this DatePicker("com.android.internal.widget.ViewPager").

I am also facing the same issue.
https://discuss.appium.io/t/android-new-date-picker-sendkeys-not-working/14939

@rkavalap  Have you found any solution for this?

**Comment by jlipps** [comment]
@imurchie do we have any datepicker tests in our android suite?

**Comment by imurchie** [comment]
Not that I know of, no.

**Comment by lanzelot1989** [comment]
I solved this for the first format of the date picker of your screenshot by navigating to the page that contains that desired date and tapping it via the accessibility ID.
Here is the C# that works with appium-dotnet-driver:
```
Driver.FindElementById("android:id/prev").Click(); // or "android:id/next" for the next month

Driver.FindElementByAccessibilityId(dateToPick.ToString("dd MMMM yyyy")).Click(); // tap a visible date
Driver.FindElementById("android:id/button1").Click() // "OK" button
```

You can also open the year picker with the ID "android:id/date_picker_header_year"

**Comment by lanzelot1989** [comment]
However, it seems that after closing the dialog, I no longer am able to let Appium interact with the app.
Am I the only one facing this issue?

**Comment by jlipps** [comment]
@lanzelot1989 are you using the uiautomator2 driver? please link to a gist of your appium logs and we can see what's happening.

**Comment by Kavitha14manoj** [comment]
Any updates , I am also not able to set the date on Android 7.0 and 7.1.2 devices (appium 1.6.5)
I am using xpath and send_keys and it works fine with android 6.0 devices ( Appium app 1.5.3)

**Comment by CharanpreetHora** [comment]
ANY UPDATES ON THIS? Shall we move to Android 6.0, if appium ot compatibile with Android 7.0

**Comment by CharanpreetHora** [comment]
This is pretty strange. I am able to select date picker date if I am using below capability instead of uiautomator2.
capability name="automationName" value="Appium"

removed below

capability name="automationName" value="uiautomator2"
But now for me Allow Permission is blocker.
Can you suggest?

**Comment by helenren** [comment]
Hit the same issue with appium 1.8.1 and android 7 still. Any progress and update? And any workaround will be helpful as well. Thanks

**Comment by KazuCocoa** [comment]
📝 (Haven't tested though)
Can work like  https://github.com/KazuCocoa/appium-espresso-driver/commit/2e97193f81bf1c4d136a4b9a791ea1e89726d0a7 with Espresso Driver?

**Comment by mykola-mokhnach** [comment]
Closed as third party issue. Perhaps Espresso could handle this better.

**Comment by rcuyugan** [comment]
This is still an issue.
Using appium 1.9.1 on Android emulator API 23. 
Works fine on an actual device (Samsung Galaxy S6, android 6.0)

My steps:
select the year element on the scrolling date picker.
Clear the text (.click())
Send in the new year (sendKeys("2000")

Observations:
clear(); does not clear the text
sendKeys sends the text, text highlighted, seems like it will replace the text but the old text stays.
without automation, I can click on the same text field, delete it and type in a new value and works just fine.

**Comment by KazuCocoa** [comment]
link https://github.com/appium/appium-espresso-driver/pull/324

**Comment by Sukhwinder-003** [comment]
> Closed as a third party issue. Perhaps Espresso could handle this better.

Can you please share some reference, how? Or can anyone help me with this 

![image](https://user-images.githubusercontent.com/53421593/62942108-409a4500-bdf5-11e9-817a-6df3a4bcc338.png)

**Comment by mykola-mokhnach** [comment]
https://kazucocoa.wordpress.com/2018/12/24/appiumandroidset-datapicker-and-timepicker-via-espresso-driver-eng/

**Comment by sonichanchal** [comment]
Hello @KazuCocoa and @mykola-mokhnach 

Reaching out to you guys again. 

Got stuck with a calendar in IOS automation. 

Have used Javascript executor to scroll the same, but Appium service says XCUI driver doesn't support this method. 

Attaching the screenshot of the calendar - I m trying to select value from.  Below code I have used.
	**JavascriptExecutor js = ((JavascriptExecutor)rdriver);
       js.executeScript("arguments[0].setAttribute('value','"+startdate+"');", startDate);**

<img width="378" alt="Screenshot 2021-05-24 at 12 11 44 AM" src="https://user-images.githubusercontent.com/81279839/119272649-a0f22380-bc24-11eb-9620-03be3910181a.png">

Please throw some lights here. 

Appium Error logs:

 Calling AppiumDriver.execute() with args: ["arguments[0].setAttribute('value','5/15/21');",[{"ELEMENT":"14020000-0000-0000-D45C-000000000000","element-6066-11e4-a52e-4f735466cecf":"14020000-0000-0000-D45C-000000000000"}],"f6b7ab0a-b61b-4d58-871a-f7a66835d980"]
[XCUITest] Executing command 'execute'
[W3C (f6b7ab0a)] Encountered internal error running command: NotImplementedError: Method is not implemented
[W3C (f6b7ab0a)]     at XCUITestDriver.execute (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/execute.js:13:11)
[W3C (f6b7ab0a)]     at commandExecutor (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
[W3C (f6b7ab0a)]     at /Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:137:12
[W3C (f6b7ab0a)]     at AsyncLock._promiseTry (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:261:31)
[W3C (f6b7ab0a)]     at exec (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:136:9)
[W3C (f6b7ab0a)]     at AsyncLock.acquire (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/async-lock/lib/index.js:152:3)
[W3C (f6b7ab0a)]     at XCUITestDriver.executeCommand (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:348:39)
[W3C (f6b7ab0a)]     at XCUITestDriver.executeCommand (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:731:24)
[W3C (f6b7ab0a)]     at AppiumDriver.executeCommand (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/lib/appium.js:563:36)
[W3C (f6b7ab0a)]     at runMicrotasks ()
[W3C (f6b7ab0a)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[W3C (f6b7ab0a)]     at asyncHandler (/Applications/Appium 2.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:21)
[HTTP] <-- POST /wd/hub/session/f6b7ab0a-b61b-4d58-871a-f7a66835d980/execute/sync 405 4 ms - 1737

**Comment by jlipps** [comment]
@sonichanchal you can't execute javascript in native apps.
