### ISSUE TITLE
enable/disable data fix

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7399]
@scottdixon commented on [Tue Feb 09 2016](https://github.com/appium/appium-android-driver/issues/98)

appium-android-driver is failing to set mobile data on API23.

```
adb -s emulator-5554 shell am start -n io.appium.settings/.Settings -e data off
adb -s emulator-5554 shell settings get global mobile_data // --> 1 (should be 0)
```

More info: http://stackoverflow.com/questions/26539445/the-setmobiledataenabled-method-is-no-longer-callable-as-of-android-l-and-later

I've tested the following commands on API23 with success:

```
shell svc data enable
shell settings get global mobile_data // --> 1
```

```
shell svc data disable
shell settings get global mobile_data // --> 0
```

This will require testing against all supported API levels.

---

@imurchie commented on [Tue Feb 09 2016](https://github.com/appium/appium-android-driver/issues/98#issuecomment-182008516)

Ugh. Thanks!

---

@vrunoa commented on [Fri Mar 04 2016](https://github.com/appium/appium-android-driver/issues/98#issuecomment-192451176)

``` bash
shell svc data enable
shell svc data disable
```

works on an emulatorx86 with API 19

---

@scottdixon commented on [Fri Mar 04 2016](https://github.com/appium/appium-android-driver/issues/98#issuecomment-192464978)

Good to know. Thanks @vrunoa 

---

@vrunoa commented on [Sat Mar 05 2016](https://github.com/appium/appium-android-driver/issues/98#issuecomment-192656284)

``` bash
shell svc data enable
shell svc data disable
```

isn't working on a Moto E with Android 5.1 API 22

---

@SrinivasanTarget commented on [Sat May 21 2016](https://github.com/appium/appium-android-driver/issues/98#issuecomment-220782331)

svc needs a root access on real devices.Fix is in here,

https://github.com/appium/appium-adb/pull/158
https://github.com/appium/appium-android-driver/pull/148

**Comment by SrinivasanTarget** [comment]
@triager please close
