### ISSUE TITLE
The appium-android-driver cannot unlock the screen on some devices

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7401]
@nghiadhd commented on [Thu May 19 2016](https://github.com/appium/appium-android-driver/issues/146)

Appium@1.5.2
Issue devices:
1. Galaxy Note 3: Model: SM-N9005, version: 4.4.2
2. Galaxy S4: Model: GT-I9500, version: 4.4.2
3. HTC one: Model: HTC6525LVW, version: 5.0.1

Other devices still work well

Note: In the past, the Galaxy S4 still works well, but after upgrade to newer OS version, it doesn't work any more

Issue: "Encountered internal error running command: Error: Screen did not unlock successfully"
Expectation: The screen should be unlocked

---

After do some investigating, found that the adb command to start the unlock doesn't work
`adb with args: ["-P",5037,"-s","xxxxxxxxxx","shell","am","start","-n","io.appium.unlock/.Unlock","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]`

I can reproduce the issue by adb command

adb -s <UDID> shell am start -n 'io.appium.unlock/.Unlock' -S -a 'android.intent.action.MAIN' -c 'android.intent.category.LAUNCHER' -f '0x10200000'

Some addresses

> The '-S' option doesn't work (should be remove from command)
> If the unlock is on foreground, the command doesn't make effect

My solution, use 'adb shell am force-stop' to kill 'unlock' and 'adb shell am start' to restart 'unlock' app. I tested on issue devices and confirm it works well

```
adb -s <UDID>  shell am force-stop 'io.appium.unlock
adb -s <UDID>  shell am start -n 'io.appium.unlock/.Unlock' -a 'android.intent.action.MAIN' -c 'android.intent.category.LAUNCHER' -f '0x10200000'
adb -s <UDID>  shell am start -n 'io.appium.unlock/.Unlock' -a 'android.intent.action.MAIN' -c 'android.intent.category.LAUNCHER' -f '0x10200000'
```

Weird that after force-stop, we should call 'am start' 2 times to invoke the 'unlock' app. That's should be the reason why '-S' option doesn't work

---

@imurchie commented on [Fri May 20 2016](https://github.com/appium/appium-android-driver/issues/146#issuecomment-220731907)

Interesting! Thank you for the detailed update. I'll take a look at this!

---

@nghiadhd commented on [Mon May 23 2016](https://github.com/appium/appium-android-driver/issues/146#issuecomment-221148508)

Thank @imurchie 

That's seem a critical issue. The test script always failed if the screen cannot unlocked

---

@rkavalap commented on [Mon Aug 01 2016](https://github.com/appium/appium-android-driver/issues/146#issuecomment-236647715)

+1

**Comment by igalep** [comment]
doesn't work on my side as well , after unlocking the screen , .Unlock activity is launched  , all I see is black screen and grey toolbar with "Unlock" title


Could you pls assist

**Comment by jlipps** [comment]
Sounds like we should change the way we run the unlock apk. Adding to our backlog to address.

**Comment by aaronmagi** [comment]
Hi @jlipps 

I wanted to know what the current status is on this as we seem to be experiencing it?

Thank you

**Comment by mykola-mokhnach** [comment]
@aaronmagi Please check https://github.com/appium/appium-android-driver/pull/209

**Comment by aaronmagi** [comment]
@mykola-mokhnach we just installed the latest Appium android driver via NPM and we are still not able to communicate to the device to have it unlocked.  Will Appium 1.6.3 use the latest installed appium-android-driver once installed or do you need to configure it manually?

As far as I saw in the linked item there is no need to explicitly call the unlock and the phone does not have a lock pin or locking enabled.

**Comment by mykola-mokhnach** [comment]
@aaronmagi Please update to 1.6.4-beta to try this feature

**Comment by argeas** [comment]
Appium 1.6.4
Motorola Moto G 2nd Gen (android 6.0)  
Having issues with unlocking. 
It unlocks the screen, then takes a while to launch activity, (about 10secs)
as activity starts the screen locks again. ( even though I have set the device to stay awake from dev options)

Cant see anything strange in the logs.
On other devices such as LG X screen I am not having this issue

**Comment by imurchie** [comment]
Fixed: https://github.com/appium/appium-android-driver/blob/master/docs/UNLOCK.md
