### ISSUE TITLE
Checkboxes on Hybrid Apps have large, invalid X values

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7402]
@midopa commented on [Mon Jun 06 2016](https://github.com/appium/appium-android-driver/issues/151)

## Description

On hybrid apps, visible checkboxes on the screen have negative x-axis values for center and location. X-value for size is very large as well.

```
element.getCenter(); // (-1356, 1296)
element.getLocation(); // (-3433, 1232)
element.getSize(); // (4154, 129)
appium.manage().window().getSize(); // (1440, 2560)
```

Interestingly, in Inspector, the location and size values seem OK:

```
type: android.widget.CheckBox
text: 
index: 4
enabled: true
location: {0, 1232}
size: {721, 129}
```

When I view the page source directly from Appium, I see the checkboxes have valid-looking values for their `bound` property.
## Environment
- java client build version or git revision if you use some shapshot: 3.4.1
- Appium server version or git revision if you use some shapshot: 1.5.3
- Desktop OS/version used to run Appium if necessary: OSX El Capitan
- Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 6.1.0
- Mobile platform/version under test: Android 6.0
- Real device or emulator/simulator: Real
## Code To Reproduce Issue [ Good To Have ]
1. Open a Appium session on an Android device
2. Open a hybrid app
3. Load a page that has a checkbox in it
4. Locate the checkbox somehow (eg. xpath = "//android.widget.CheckBox")
5. Investigate the above properties (center, location, size)
## Link to Appium logs

https://gist.github.com/midopa/ba91923519a6b288a1cd510690c2a2b8

---

@midopa commented on [Fri Jul 29 2016](https://github.com/appium/appium-android-driver/issues/151#issuecomment-236340511)

Dug a little more. It looks like the values from `UiObject,getBounds()` are incorrect! Even though the values you see in `appium.getPageSource()` look valid.

UI Object has a method called `getVisibleBounds` that seems to give more accurate results. When the checkbox is off screen, the bounds are a 0-rectangle. When the checkbox is on screen, the bounds describe the portion of the checkbox on the screen. This doesn't seem to happen for other elements (buttons, input fields, etc). So either this needs to be fixed in UIAutomator (not sure about timeline, turn-around, and process here), handled in Appium, or `getVisibleBounds` should be exposed as another command.

Thoughts?

**Comment by dpgraham** [comment]
The difference between `getBounds` and `getVisibleBounds` is that visible bounds clips the on-screen coordinates. So this could be a problem if the 'center' is off the screen.

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
