### ISSUE TITLE
WebElement.findElements(By.className()) on a parent object returns all classes on dom that match

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7405]
@aaronmagi commented on [Tue Jul 05 2016](https://github.com/appium/appium-android-driver/issues/164)

```
WebElement linearLayouts = driver.findElementByXPath("//android.widget.LinearLayout[@index='1']");
List<WebElement> views = linearLayouts.findElements(By.className("android.widget.TextView"));

System.out.println(views.size());
```

I would expect to only get back the 2 elements for the TextViews in the tree attached.  Instead all the elements with that class in the document are returned?

![tree lg](https://cloud.githubusercontent.com/assets/17730298/16603654/a63cc848-42d2-11e6-9c9b-72124ccaf241.JPG)

**Comment by dpgraham** [comment]
I don't think
