### ISSUE TITLE
Cannot create new session after run few sessions

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7407]
@nghiadhd commented on [Mon Dec 05 2016](https://github.com/appium/appium-android-driver/issues/197)

I wrote a test script to measure long run capability of Appium.
However after a few sessions, the appium stub at create new session

`[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"988633304d4b323634"}}}`

I used 'adb' to check "chrome" process on device and see that many chrome processes are leaking

```
./adb shell ps | grep chrome                        
u0_a85    2757  3184  1578696 194580 SyS_epoll_ 0000000000 S com.android.chrome
u0_i39    2804  3184  1201756 86092 SyS_epoll_ 0000000000 S com.android.chrome:sandboxed_process0
u0_a85    2836  3184  1212104 93312 SyS_epoll_ 0000000000 S com.android.chrome:privileged_process0
u0_a86    10842 3183  1664788 59756 SyS_epoll_ 0000000000 S com.sec.android.app.chromecustomizations
u0_a85    30465 3184  1548556 182592 SyS_epoll_ 0000000000 S com.android.chrome
u0_a85    30671 3184  1234504 89732 SyS_epoll_ 0000000000 S com.android.chrome
```

Because my device is non-root so I cannot kill "chrome" process by 'shell pkill' or 'am force-stop com.android.chrome'.
Now my device cannot work with appium any more until restarting to clean up leaking processes

Environment: 
Appium: 1.6.1/1.6.2
Chromedriver: 2.25
Nodejs: v6.8.0
NPM: 3.10.8

Device:
Galaxy S7: SM-G930F
Android: 6.0.1
Chrome: 54.0.2840.85

Start commands:
- Appium
`node build/lib/main.js --command-timeout "7200" --debug-log-spacing --default-capabilities '{"platformName":"Android"}' --default-device`

- Client
`UDID=988633304d4b323634 PLATFORM=Android npm run wd`

Appium's log: https://gist.github.com/nghiadhd/88c8bf0e14ac32f2f47f3e3052d2ddfa
Testscript: https://gist.github.com/nghiadhd/8388fe2b2e9e1917298e0b9d4d52d952

**Comment by nghiadhd** [comment]
Update

I workaround to kill chrome processes by go to "Settings -> Developer Options -> Limit background processes" and change to "No background processes"
So do you know the adb command to change it automatically? My idea that we shall change to "No background processes" and then switch back "Standard limit" before create any Appium session

**Comment by rkavalap** [comment]
@nghiadhd 

Is the device getting locked after several runs ? 
Based on the exception stack trace and chromedriver source code
https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver/chrome/device_manager.cc

**Comment by nghiadhd** [comment]
Thanks @rkavalap 

Actually, it doesn't get lock, I still can open chrome and use normally by manual (hand). However
when I goto "cached running process". I found it has 3 chrome processes, I tried to close them but not success
Now, only one workaround solution is set "limit background process" to "no background process" to kill them

I'll investigate the chromedriver source, may it help me find the root cause

**Comment by jlipps** [comment]
Hmm, appium is doing the right thing and deleting the chromedriver session. I think this is a chromedriver process leak or something.
