### ISSUE TITLE
Install flow needs to be examined

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7414]
@imurchie commented on [Tue May 03 2016](https://github.com/appium/appium-ios-driver/issues/141)

In particular, installing an `ipa` file on a real device repeats steps and bypasses the checks for reset/no reset. This needs to be examined.

See https://github.com/appium/appium-ios-driver/pull/139#discussion_r61896077

**Comment by dpgraham** [comment]
@imurchie Does this still need to be looked at?

**Comment by imurchie** [comment]
I think this has been fixed.
