### ISSUE TITLE
problem finding children of an element by xpath in IOS

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7415]
@alizelzele commented on [Sun Aug 28 2016](https://github.com/appium/appium-ios-driver/issues/176)

There is a bug in `commands.findUIElementsByXpath` (find.js:166). When trying to find children of an element by xpath, `au.getElement(context).getTreeForXML()` returns indexPath relative to the parent (not full index path), so the next command that wants to get elements by their indexPath `au.getElementsByIndexPaths(["/0/3"])` will fail or will find the wrong element (because of wrong indexPath).

The problem here is the only info about the parent we have is  the id of parent element. is there any way to get indexPath of an element by id? this way we can calculate the full indexPath and make the method work correctly.

---

@alizelzele commented on [Mon Aug 29 2016](https://github.com/appium/appium-ios-driver/issues/176#issuecomment-243026705)

some console logs (cropped to make it easier to read).

```
au.mainApp().getTreeForXML();
  ->"UIANavigationBar":{"name":"Sample", "path":"/0/0/0"}
          > {"UIAButton":{"name":"Tap", "path":"/0/0/0/3"}


au.getElementByIndexPath('/0/0/0');
  -> returned [object UIANavigationBar] with the name "Sample" (id: 0).


au.getElement('0').getTreeForXML()
  ->"path":"/0/0"
          >{"UIAButton":{"name":"Tap", "path":"/0/3"}


au.getElementsByIndexPaths(["/0/3"]); => wrong IndexPath
```

**Comment by dpgraham** [comment]
Related to https://github.com/appium/appium/issues/6700
