### ISSUE TITLE
Execute is not implemented according Webdriver protocol in native context

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7417]
@christian-bromann commented on [Tue Dec 06 2016](https://github.com/appium/appium-ios-driver/issues/199)

In [14.2.1 Execute Script](https://www.w3.org/TR/webdriver/#execute-script) it states that:

> Let result be the result of calling [execute a function body](https://www.w3.org/TR/webdriver/#dfn-execute-a-function-body), with arguments body and arguments.

This is not working as expected in a native context. Given the following command:

```
[MJSONWP] Calling AppiumDriver.execute() with args: ["return (function (a) {\n ...
[debug] [iOS] Executing iOS command 'execute'
[debug] [UIAuto] Sending command to instruments: return (function (a) {
                                return a + 2;
                            }).apply(null, arguments)
```

It fails with:

```json
{"status":17,"value":"Return statements are only valid inside functions."}
```

I think this should be handled in the iOS driver because the state of the context is known so that the command payload can be handled properly.

Here is another comparison between the difference between native and webview context (WebdriverIO log [excerpt](https://github.com/webdriverio/webdriverio/blob/master/test/spec/mobile/ios/execute.js)):
```
// native context
[15:23:35]  COMMAND     POST     "/wd/hub/session/2c54d96e-0fe3-4f1b-92f0-87bd738cb38d/execute"
[15:23:35]  DATA                {"script":"3 + 2","args":[]}
[15:23:36]  RESULT              5

// webview context
[15:23:37]  COMMAND     POST     "/wd/hub/session/2c54d96e-0fe3-4f1b-92f0-87bd738cb38d/execute"
[15:23:37]  DATA                {"script":"return 3 + 2","args":[]}
[15:23:37]  RESULT              5
```

**Comment by mykola-mokhnach** [comment]
Closed as obsolete
