### ISSUE TITLE
Support hideKeyboard() action

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7419]
@kaleposhobios commented on [Tue Jan 05 2016](https://github.com/appium/appium-xcuitest-driver/issues/8)

Hi,

Right now the appium-specific command "hideKeyboard(strategy, ...possibleKeys)" is not supported (unless I'm confused).

I was able to get a simple version of it working, in combination with some WebDriverAgent changes, as follows:
Appium: capture the request by adding a proxy avoid list item: ['POST', /appium/], and don't proxy it. 
Then implement code to call a new WDA route I made.

WebDriverAgent: Implement a new route like this:

```
    [[FBRoute POST:@"/hide_keyboard"] respond: ^ id<FBResponsePayload> (FBRouteRequest *request) {
        FBXCTSession *session = (FBXCTSession *)request.session;
        [[session.application.windows elementAtIndex:0] tap];
      return FBResponseDictionaryWithOK();
    }],
```

This worked, so it satisfied me that it seems to be possible. But before I did anything further I wanted to see what the community thought as to the best implementation. Additionally, I wasn't sure what the intention of possibleKeys was. I think I understand the various strategies, but if I actually implement this I think it would be helpful to have more info on each of the desired strategies.

Thanks!

**Comment by hepilt** [comment]
Still not implemented? Very necessary thing

**Comment by dpgraham** [comment]
This is supported: 
* https://github.com/appium/appium-xcuitest-driver/blob/37c93010b3fb28f4bb0c3f355bd99ef1c3c27fed/lib/commands/general.js#L111 ; 
* https://github.com/appium/appium-xcuitest-driver/commit/19d1e9fab51aaaec054132b17b6eb8b794562213

If it's not working, provide the logs and I'll re-open this issue.
