### ISSUE TITLE
WDA derivedData using disk space

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7425]
@joshrlesch commented on [Mon Sep 19 2016](https://github.com/appium/appium-xcuitest-driver/issues/163)

Not 100% were to put this issue, but while updating our framework to use the new appium-xcuitest-driver, WDA gets build with xcodebuild every time which just keeps expanding the derivedData for that project. Just in the last week it took up 81GB of space. Should this driver clean up derivedData or the WDA project?

<img width="529" alt="screen shot 2016-09-19 at 12 42 39 pm" src="https://cloud.githubusercontent.com/assets/8480230/18645822/61bebef0-7e74-11e6-8ff9-d1366b9aff62.png">

---

@yaphatak commented on [Tue Sep 20 2016](https://github.com/appium/appium-xcuitest-driver/issues/163#issuecomment-248523225)

I saw this and thanks for reporting. We should fix it soon :)

**Comment by imurchie** [comment]
`preventWDAAttachments` capability will help this.
