### ISSUE TITLE
Wrong button being clicked

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7428]
@joshrlesch commented on [Tue Oct 04 2016](https://github.com/appium/appium-xcuitest-driver/issues/209)

ok this is a difficult one, but we are seeing the wrong buttons being clicked. All of the logs look fine with no errors, its just that it literally clicks the wrong button in the app. So its hard to give logs and debug info.

I saw this after upgrading the appium-xcuitest-driver by doing `npm uninstall -g appium && npm install -g appium@beta`. This picked up v2.0.23. Nothing has changed in our app and I know this used to work. So I started to downgrade the driver until it started working again which was v2.0.19. So something in v2.0.20 is causing this issue. :/

If you want any info for debugging this, I will give it to you.

---

@imurchie commented on [Tue Oct 04 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-251421138)

Since it seems unlikely that we will be able to reproduce this, can you do a little investigating? I'm willing to bet, given the changes that have happened, that this is from the update of the underlying WebDriverAgent. To see if this is true, can you get the latest from `appium-xcuitest-driver` (version `2.0.23`), then get a copy of the WebDriverAgent and get it to the previous commit:

```
// somewhere temporary
git clone https://github.com/facebook/WebDriverAgent.git
cd WebDriverAgent
git checkout e05cce2d6f1e43ea52ac4a7a9ab0dd22650fcb8e
```

You should see some output ending with `HEAD is now at e05cce2... Add health check enpoint`.

Now get the full path to that WebDriverAgent directory, and pass it into your test in _both_ the `agentPath` and `bootstrapPath` desired capabilities (these might cause a log line to be generated saying they are not recognized, but don't worry about that).

This should make the system use the different WDA installation, which is in the state the driver version `2.0.20` was in.

Phew!

Anyway, hopefully that will work, and we can start figuring out what changed in the WDA system that would cause this.

---

@imurchie commented on [Tue Oct 04 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-251453598)

Oh shoot! I mislead you. The `agentPath` cap should be the directory, plus `/WebDriverAgent.xcodeproj`. :( It needs to point to the project itself.

---

@joshrlesch commented on [Tue Oct 04 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-251455453)

no worries, I figured that out :)

But I tried that wda commit and it still clicked the wrong button, so I have been going down the list of commits but they all don't seem to work, I made it to `b2e1c07d1028b696708b64b130292770b72e8052`

Im going to keep going down the list till I get to `de045610520f6b6e793ecd58b4f900c9c2636af0` which is what v2.0.19 was using.

---

@joshrlesch commented on [Tue Oct 04 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-251457430)

@imurchie well I jumped the gun, WDA commit `eb8514512703f54dda0a9953a3be6755f572a7b8` worked, but `b2e1c07d1028b696708b64b130292770b72e8052` didn't. 

---

@imurchie commented on [Tue Oct 04 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-251461025)

Alrighty. Thanks for the investigation.

One more thing to try. Can you do the same, but for my fork, in which I've reverted the commit after the one you identified (which does have to do with clicking, so that checks out).

```
// somewhere temporary
git clone https://github.com/imurchie/WebDriverAgent.git
```

And do the same with the directory/xcode project file.

Thanks!

---

@joshrlesch commented on [Tue Oct 04 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-251468668)

Ok so cloned your fork, updated the `agentPath` and `bootstrapPath` to point to it, and the test passes.

---

@imurchie commented on [Tue Oct 04 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-251470894)

Alrighty. I will open an issue on WDA and link to here. Thanks for all the work in getting to the bottom of this.

---

@joshrlesch commented on [Tue Oct 04 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-251471564)

No worries man. Thanks for the fast turn around.

---

@imurchie commented on [Wed Oct 05 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-251704547)

@joshrlesch Can you provide more detail about the error. How is the view laid out? It seems like the upstream maintainer doesn't feel like fixing it unless I can produce a reproduction case.

---

@joshrlesch commented on [Wed Oct 05 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-251705859)

yeah I saw that :( So the views that it happens on are very complex ones that load a lot of elements into memory but not all are visible at a give time. 

There really is no error, but trying to figure out how to get more info on why its clicking the wrong button. 

I'll get you the DOM of the page state and the appium logs of the command that is being sent, maybe something is off that I'm missing.

---

@joshrlesch commented on [Wed Oct 05 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-251715925)

@imurchie https://gist.github.com/joshrlesch/d7651d49b3d9e28e234f1fe0c36ebb94

---

@pavanbachu0604 commented on [Wed Oct 19 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-254912914)

@joshrlesch : were you able to fix it ? I am facing the same issue in appium 1.6 (final version). It is able to recognise the xpath but it is not clicking 

---

@joshrlesch commented on [Wed Oct 19 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-254958873)

I have not, but @imurchie I think it might have something to do with being in landscape mode. Whenever it clicks on the wrong button, our app is forcing landscape mode. Like when entering a video player, the app locks it in landscape.

@pavanbachu0604 are you in landscape when the wrong element is being clicked?

---

@pavanbachu0604 commented on [Thu Oct 20 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-255121786)

Yeah its not clicking on right element when its in landscape mode , I need to test it in portrait mode 

---

@pavanbachu0604 commented on [Thu Oct 27 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-256793880)

@joshrlesch Any updates ? I am struck at that same point and worst thing is that app I am testing on is completely in landscape mode 

---

@joshrlesch commented on [Fri Oct 28 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-256928026)

Believe it is being looked at by WDA

---

@maesiva commented on [Tue Nov 01 2016](https://github.com/appium/appium-xcuitest-driver/issues/209#issuecomment-257699678)

My app too works only in Landscape mode and am blocked due to this issue. Eager to see a fix soon!

**Comment by pavanbachu0604** [comment]
@rkavalap Is there any fix ?  I know its an apple issue but cant it be handled by WDA ? As its been quite a long time
