### ISSUE TITLE
xcodeConfigFile path cannot contain spaces

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7430]
@Schnutzel commented on [Mon Oct 10 2016](https://github.com/appium/appium-xcuitest-driver/issues/224)

When using the xcodeConfigFile capability, if the path to the file contains spaces, the run-xcodebuild.sh script will split it into separate arguments, causing xcodebuild to fail with error code 127.

**Comment by imurchie** [comment]
No longer an issue.
