### ISSUE TITLE
Driver gets stuck in loop trying to connect to app

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7432]
@midopa commented on [Fri Oct 14 2016](https://github.com/appium/appium-xcuitest-driver/issues/242)

This doesn't repro all the time.
1. Launch Appium with a browser session
2. Sometimes, it gets stuck trying to connect to the app

Log snippet: https://gist.github.com/midopa/be2377863348a30e98288fb772fad3a7

After the 20th attempt, the driver loops back and repeats ad nauseam.

Appium 1.6.0
Node 6.7.0
Java client 4.1.2
OSX El Capitan
XCode 8
iOS 10 simulator (iPad Air)

Capabilities:

```
{
  networkConnectionEnabled=false,
  noReset=false,
  databaseEnabled=false,
  deviceName=iPad Air,
  platform=MAC,
  showIOSLog=true,
  sendKeyStrategy=grouped,
  newCommandTimeout=10000,
  platformVersion=10.0,
  safariAllowPopups=true,
  webStorageEnabled=false,
  locationContextEnabled=false,
  browserName=safari,
  takesScreenshot=true,
  javascriptEnabled=true,
  platformName=iOS
}
```

---

@midopa commented on [Fri Nov 25 2016](https://github.com/appium/appium-xcuitest-driver/issues/242#issuecomment-262904902)

Ping? This happens with apps too.

Runtime environment is the same except now I'm running Appium 1.6.x @ 7131abb.

Log snippet: https://gist.github.com/midopa/3180433a146324135db1fdb94128cab1
Specific error: https://gist.github.com/midopa/3180433a146324135db1fdb94128cab1#file-gistfile1-txt-L213

Some possible clues at lines:
- https://gist.github.com/midopa/3180433a146324135db1fdb94128cab1#file-gistfile1-txt-L26
- https://gist.github.com/midopa/3180433a146324135db1fdb94128cab1#file-gistfile1-txt-L41

Interestingly, I can take a screenshot and get the page source:
- https://gist.github.com/midopa/3180433a146324135db1fdb94128cab1#file-gistfile1-txt-L260
- https://gist.github.com/midopa/3180433a146324135db1fdb94128cab1#file-gistfile1-txt-L271

---

@midopa commented on [Fri Nov 25 2016](https://github.com/appium/appium-xcuitest-driver/issues/242#issuecomment-263014070)

FWIW, it looks like this doesn't happen when I reset the Appium instance between every test run. So it might be some kind of leaked state Appium gets into?

---

@jlipps commented on [Mon Nov 28 2016](https://github.com/appium/appium-xcuitest-driver/issues/242#issuecomment-263435313)

@midopa it does look like it might be a bug of some kind. I'm not up on the remote debugger code at the moment though, so we may have to wait for @imurchie to get back from vacation after this week

**Comment by mykola-mokhnach** [comment]
Closed as fixed
