### ISSUE TITLE
Tap by x,y does not work any more

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7436]
@amedvedjev commented on [Mon Nov 07 2016](https://github.com/appium/appium-xcuitest-driver/issues/281)

Appium version: 1.6.1-beta (similar problems in https://github.com/appium/appium/issues/7158)

here are 2 ways of try:
 - new TouchAction((AppiumDriver) driver).tap(x, y).perform();
 - ((AppiumDriver) driver).tap(1, x, y, 200);

**Code:**
new TouchAction((AppiumDriver) driver).tap(x, y).perform();

**Error:**
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/C11F928A-A390-4AAB-8E89-CE6B7EBD1430/tap -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/C11F928A-A390-4AAB-8E89-CE6B7EBD1430/tap"
    );
} (WARNING: The server did not provide any stacktrace information)

**Logs:**
   tapElement: x = 36, y = 286
[HTTP] --> POST /wd/hub/session/ba9e17a7-6a0e-4995-b9aa-0e54d0d24b11/touch/perform {"actions":[{"action":"tap","options":{"x":36,"y":286}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"x":36,"y":286}}],"ba9e17a7-6a0e-4995-b9aa-0e54d0d24b11"]
[debug] [XCUITest] Executing command 'performTouch'
[JSONWP Proxy] Proxying [POST /tap/] to [POST http://localhost:8100/session/C11F928A-A390-4AAB-8E89-CE6B7EBD1430/tap] with body: {"x":36,"y":286}
[JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/C11F928A-A390-4AAB-8E89-CE6B7EBD1430/tap -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/C11F928A-A390-4AAB-8E89-CE6B7EBD1430/tap\"\n    );\n}","sessionId":"C11F928A-A390-4AAB-8E89-CE6B7EBD1430","status":1}
[HTTP] <-- POST /wd/hub/session/ba9e17a7-6a0e-4995-b9aa-0e54d0d24b11/touch/perform 500 6 ms - 380 #

-------------------------------------------------------------------------------------------------

**Code:**
((AppiumDriver) driver).tap(1, x, y, 200);

**Error:**
org.openqa.selenium.UnsupportedCommandException: Parameters were incorrect. We wanted "WDA long press needs an element" and you sent undefined
Command duration or timeout: 7 milliseconds

**Logs:**
   tapElement: x = 36, y = 286
[HTTP] --> POST /wd/hub/session/218140d0-bf7b-4f21-b746-b165ab8384dc/touch/perform {"actions":[{"action":"press","options":{"x":36,"y":286}},{"action":"wait","options":{"ms":200}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":36,"y":286}},{"action":"wait","options":{"ms":200}},{"action":"release","options":{}}],"218140d0-bf7b-4f21-b746-b165ab8384dc"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted "WDA long press needs an element" and you sent undefined
[HTTP] <-- POST /wd/hub/session/218140d0-bf7b-4f21-b746-b165ab8384dc/touch/perform 400 2 ms - 93 

---

@imurchie commented on [Mon Nov 07 2016](https://github.com/appium/appium-xcuitest-driver/issues/281#issuecomment-258919687)

By "anymore" what do you mean? 

---

@amedvedjev commented on [Mon Nov 07 2016](https://github.com/appium/appium-xcuitest-driver/issues/281#issuecomment-258921932)

i mean it was working with all appium versions of 1.6.0-X. but stopped at 1.6.1-beta

---

@imurchie commented on [Mon Nov 07 2016](https://github.com/appium/appium-xcuitest-driver/issues/281#issuecomment-258949511)

Hmm. Yes, it began using long press, since there is a duration. This will need to be fixed.

---

@imurchie commented on [Tue Nov 15 2016](https://github.com/appium/appium-xcuitest-driver/issues/281#issuecomment-260632910)

It is available in `appium-xcuitest-driver@2.0.35`. You can update by re-installing 1.6.1-beta

```
npm uninstall -g appium
npm install -g appium@beta
```

---

@amedvedjev commented on [Tue Nov 15 2016](https://github.com/appium/appium-xcuitest-driver/issues/281#issuecomment-260663837)

just tested successfully!

---

@PeterGolf commented on [Mon Nov 28 2016](https://github.com/appium/appium-xcuitest-driver/issues/281#issuecomment-263260138)

@imurchie i have the same problem on 1.6.1 release version. How can i fix this?

---

@zademaxfield commented on [Mon Nov 28 2016](https://github.com/appium/appium-xcuitest-driver/issues/281#issuecomment-263351469)

I have the same problem on 1.6.1 and 1.6.1beta. This works in 1.6.0. Any Ideas on how to get this to work? 

Code:
			myElement = driver.findElement(By.name(userToSearch));
			Point myPoint = myElement.getLocation();
			driver.tap(1, myPoint.x, myPoint.y, 200);

Error:
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/AE140EC7-BEEA-4D50-B76D-5D6C3C349EC5/touchAndHold -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/AE140EC7-BEEA-4D50-B76D-5D6C3C349EC5/touchAndHold"
    );
} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 12 milliseconds
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'MacBook-Pro', ip: '10.109.128.94', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_45'
Driver info: io.appium.java_client.ios.IOSDriver

---

@vishwathma commented on [Tue Nov 29 2016](https://github.com/appium/appium-xcuitest-driver/issues/281#issuecomment-263801569)

When is the fix expected?

---

@midopa commented on [Wed Nov 30 2016](https://github.com/appium/appium-xcuitest-driver/issues/281#issuecomment-263965701)

Same issue for me. I'm using the v2.0.35 XCUITest driver with Appium at the head of 1.6 (c05fd69) (had to modify the package.json).

---

@zademaxfield commented on [Mon Dec 05 2016](https://github.com/appium/appium-xcuitest-driver/issues/281#issuecomment-264897972)

This is what I did for a work around: 
myElement = driver.findElement(By.name(userToSearch));
TouchAction myAction = new TouchAction(driver);
Point myPoint = myElement.getLocation();
myAction.press(myPoint.x, myPoint.y).release();
driver.performTouchAction(myAction);

**Comment by gitsaquib** [comment]
This code is not working for me. I am trying to click assistive touch on iPad iOS 10.x

**Comment by imurchie** [comment]
"not working" is not a useful error. What is happening? Can you post the _full_ server logs as a [gist](https://gist.github.com)?

**Comment by gitsaquib** [comment]
I am trying to tap on Assistive touch on iOS 10 with Appium 1.6.2. Appium doesn't give any error but doesn't tap as well.

**Comment by mykola-mokhnach** [comment]
@gitsaquib this might happen because XCTest does not respect landscape orientation properly. I hope [this](https://github.com/facebook/WebDriverAgent/pull/411) PR can resolve it for now.

**Comment by dpgraham** [comment]
Here's the 'gist' that @gitsaquib provided in the issue (https://github.com/appium/appium/issues/7564) that he opened up:

https://gist.github.com/gitsaquib/03bc64b099067effb8ede578b5e13b92

It indeed looks like it is due to XCTest faulty orientation.
