### ISSUE TITLE
Numerous early termination of test runs on iOS 10 devices leads to "house arrest" error.

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7441]
@michaelgallacher commented on [Mon Nov 21 2016](https://github.com/appium/appium-xcuitest-driver/issues/307)

## The problem
After a period of time, XCUITests will begin failing until the device is rebooted.

## Environment.
iPhone 6s on 10.2
iPad 4 on 10.2

## Details
Empirical testing shows the failure is related to the number of aborted runs done on 'older' devices.  
@Schnutzel experienced the same in #167, where an iPhone 5C fails and an iPhone SE doesn't.  

When an XCUITest is terminated before completing normally, it leaves a zombie process on the phone called `mobile_house_arrest`  After five zombies are created, iOS refuses to launch more, returning the error 

> Too many instances of this service are already running

I have never seen `mobile_house_arrest` during runs on my iPhone 6s.  It is present on every run with the iPad 4.

## Link to Appium logs
[gist](https://gist.github.com/michaelgallacher/d4224ae834eb19ff1dffd51cab59e006)

---

@imurchie commented on [Tue Nov 22 2016](https://github.com/appium/appium-xcuitest-driver/issues/307#issuecomment-262341565)

Before continuing too far, can you try the latest Appium version (`npm uninstall -g appium && npm install -g appium@beta`)? There was a significant problem in how xcodebuild was being ended, which has been fixed.

---

@michaelgallacher commented on [Wed Nov 23 2016](https://github.com/appium/appium-xcuitest-driver/issues/307#issuecomment-262636290)

No luck using `appium@beta`.   Aborting an iOS 10 test five times still requires a device reboot due to the zombies.

**Comment by Prakash-Saravanan** [comment]
I too face same issue with following. 
iOS 10.1
Xcode 8.1
Appium 1.6.3

**Comment by giripalanivel** [comment]
@rkavalap @imurchie @michaelgallacher Anyone seen this resolved recently?

**Comment by jlipps** [comment]
Can you try running Appium from master (not 1.6.3)? Lots of changes recently. I also haven't really heard of this recently.

**Comment by michaelgallacher** [comment]
I'd forgotten about this issue since posting in November.  I am on 1.6.3 but have not seen the issue since the iOS 10.2 release in December.

**Comment by jlipps** [comment]
Thanks @michaelgallacher. I'll wait to hear if @giripalanivel has any other thoughts, and then close otherwise.

**Comment by meirtsvi** [comment]
Still happens on 32bit devices with 10.2

**Comment by jlipps** [comment]
Why is the XCUITest run aborted to begin with? And anyway this zombie house arrest issue seems not to be an Appium one, unless we can see that Appium is somehow causing the run to be aborted.

**Comment by meirtsvi** [comment]
Upgrading the 32bit device to iOS 10.2.1 seems to solve the issue

**Comment by giripalanivel** [comment]
Update:
Tried with appium master version (which actually points to 1.6.3) and iOS 10.1.1. 
Faced new issue:
_An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/1A355A7C-1000-4E47-A124-B23E1CBD984B/source/xml -- http://localhost:8100/ with parameters { 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/1A355A7C-1000-4E47-A124-B23E1CBD984B/source/xml -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/1A355A7C-1000-4E47-A124-B23E1CBD984B/source/xml"
    );
} (WARNING: The server did not provide any stacktrace information)_

Which I think is https://github.com/appium/appium/issues/7634

Soon ran in to this mobile_house_arrest error.
I am trying to upgrade to iOS 10.2.1 in couple of days and see it is fixed there. Will keep you posted.

**Comment by jlipps** [comment]
@giripalanivel that seems unrelated to both this and #7634. Please open a new issue and be sure to include your full set of appium logs.

**Comment by giripalanivel** [comment]
@jlipps I was able to reproduce this issue with Appium 1.6.4 beta and iOS 10.2.1.
The execution was fine for 5 tests but then it fails due to this issue.
I did set useNewWDA to true but still seeing this. Please help.

Attached the full appium log: (Look for the string 'Failed to create session' from where the test started failing.)
(https://gist.github.com/giripalanivel/0a222e3cf133de5aaa6037f771d15381)

**Comment by mykola-mokhnach** [comment]
@giripalanivel It's known Apple issue, which is, most likely, not going to be fixed. Try to run your tests on newer 64-bit devices (iPhone 6 and never).

**Comment by cbrea** [comment]
Hi all,

   Same issue reproduced here.  Several iterations of the same test resulted on:

[Xcode] 2017-03-22 21:44:47.808 xcodebuild[5788:171894]  DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.WebDriverAgentRunner-Runner [Error Domain=com.apple.dtdevicekit Code=-402653093 "Too many instances of this service are already running

  Used two devices but the error only appears in a 5S:

    iPhone 5s -> 10.0.2  --> Testing lead to fail after several iterations 
    iPhone 6 -> 10.1.1   ---> No test fails even test being executed for 50 times

   Using appium version: 1.6.4-beta
