### ISSUE TITLE
After updating from appium 1.6.0 to 1.6.2, I can no longer find elements the same way

### ISSUE THREAD

**Issue by Blinkk** [appium/appium#7444]
**Note:** This is for automation on iOS using XCode 8.1 and iOS 10.1
I have this method that I use to grab an element at a given index:
```
public IWebElement GetProductElement(int index)
{
    try
    {
        return driver.FindElement(By.XPath(
            string.Format("//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]" + 
            "/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]" +
            "/XCUIElementTypeOther[1]/XCUIElementTypeTable[1]/XCUIElementTypeCell[{0}]", index)));
    }
    catch (Exception e)
    {
        Debug.WriteLine("Failed to GetProductElement(" + index + ") in " + this.ToString());
        throw e;
    }
}
```

This worked when I was using Appium 1.6.0 and since the upgrade, I get the following error when it tries to find elements using this method:
`XCTRunner[1068]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x608000248a30> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1`

I can go back to 1.6.0 for the time being, but I don't want to be forced to use an older version if I don't have to. Any help would be appreciated.

**Comment by mykola-mokhnach** [comment]
Known WDA issue: https://github.com/facebook/WebDriverAgent/issues/372
