### ISSUE TITLE
Why appium still install winappdriver 0.5 beta

### ISSUE THREAD

**Issue by amitg25** [appium/appium#7445]
I install appium for Windows automation and see while running npm -g install appium command that it still install 0.5 beta version of WinAppDriver, though we now have 0.7 version.

**Comment by jlipps** [comment]
Did you `npm uninstall -g appium` first?

**Comment by amitg25** [comment]
Yes I did jlipps

**Comment by jlipps** [comment]
Hmm, I just tried this myself. Somehow I think the shrinkwrap is wrong. We're going to need to release appium 1.6.3 to fix this.

**Comment by jlipps** [comment]
this has been fixed and will be released in 1.6.3
