### ISSUE TITLE
Appium 1.6.1 failed to launch app on Real Device

### ISSUE THREAD

**Issue by pengboZheng** [appium/appium#7446]
## The problem

1. Be able to install WebDriver on device
2. Run `xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test` without any issues.
3. Get output: (See [Gist](https://gist.github.com/pengboZheng/9993bedc0a8baef7ff2e6914d4e230c2))

> Unable to start WebDriverAgent session: An unknown server-side error occurred while processing the command.

## Environment

- Appium version (or git revision) that exhibits the issue: 1.6.1
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: 10.12.1
- Node.js version (unless using Appium.app|exe):7.2.0
- Mobile platform/version under test: iOS 9.3
- Real device or emulator/simulator: Real device
- Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
I'd rather report this issue to [WDA](https://github.com/facebook/WebDriverAgent/issues)
