### ISSUE TITLE
Noe able to run with Appium 1.6.0

### ISSUE THREAD

**Issue by Rdexmah** [appium/appium#7447]
## The problem

I am not able to run my test cases on my device with even details as below 👍 

OS : Mac OS 10.11.6
Device : IPod with 10.0.1

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.0 beta 3
* Last Appium version that did not exhibit the issue (if applicable):v1.5
* Desktop OS/version used to run Appium: Mac OS 10.11.6
* Node.js version (unless using Appium.app|exe): npm@3.10.9 
* Mobile platform/version under test: IOS 10.0.1 on ipod touch
* Real device or emulator/simulator Ipod touch:

## Details

I am not able to rum test cases on my device.
I am getting folllowing error.
It stuck with "Cotinuing to run tests in the background with task ID 1
" 
## Link to Appium logs

[Appium] Welcome to Appium v1.6.0-beta3
[Appium] Non-default server args:
[Appium]   address: '127.0.0.1'
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.0-beta3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 23 ms - 89 
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Repos/iOS Build for Appium/XXX-Enterprise.app","showIOSLog":false,"noReset":true,"showXcodeLog":false,"newCommandTimeout":1800,"realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole","automationName":"XCUITest","udid":"baa51e99d366568f3344f33e95d651960d371d6b","platformName":"iOS","deviceName":"ipod6","fullReset":false}}
wIOSLog":false,"noReset":true,"showXcodeLog":false,"newCommandTimeout":1800,"realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole","automationName":"XCUITest","udid":"baa51e99d366568f3344f33e95d651960d371d6b","platformName":"iOS","deviceName":"ipod6","fullReset":false}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Repos/iOS Build for Appium/XXX-Enterprise.app","showIOSLog":false,"noReset":true,"showXcodeLog":false,"newCommandTimeout":1800,"realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole","automationName":"XCUITest","udid":"baa51e99d366568f3344f33e95d651960d371d6b","platformName":"iOS","deviceName":"ipod6","fullReset":false},null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Repos/iOS Build for Appium/XXX-Enterprise.app'
[Appium]   showIOSLog: false
[Appium]   noReset: true
[Appium]   showXcodeLog: false
[Appium]   newCommandTimeout: 1800
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole'
[Appium]   automationName: 'XCUITest'
[Appium]   udid: 'baa51e99d366568f3344f33e95d651960d371d6b'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'ipod6'
[Appium]   fullReset: false
[debug] [XCUITest] XCUITestDriver version: 2.3.0
[BaseDriver] Session created with session id: 17c48888-0a0a-46eb-95f3-54e1ecb5af03
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [XCUITest] Available devices: baa51e99d366568f3344f33e95d651960d371d6b
[debug] [XCUITest] Creating iDevice object with udid baa51e99d366568f3344f33e95d651960d371d6b
[XCUITest] Determining device to run tests on: udid: 'baa51e99d366568f3344f33e95d651960d371d6b', real device: true
[BaseDriver] Using local app '/Repos/iOS Build for Appium/XXX-Enterprise.app'
[debug] [XCUITest] Checking whether app '/Repos/iOS Build for Appium/XXX-Enterprise.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/Repos/iOS Build for Appium/XXX-Enterprise.app': 'com.dexcominc.CGM'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] Error checking install status: Command 'ios-deploy --exists --id baa51e99d366568f3344f33e95d651960d371d6b --bundle_id com.dexcominc.CGM' exited with code 255
[debug] [XCUITest] App is not installed. Will try to install.
[debug] [XCUITest] App installed successfully.
[XCUITest] Using WDA path: '/Users/xxxxx/Desktop/appium-master/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/xxxxx/Desktop/appium-master/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Error : Command 'bash -c "ps -ax|grep -i \"xcodebuild\"|grep -i \"baa51e99d366568f3344f33e95d651960d371d6b\"|grep -v grep|awk '{print \"kill -9 \" \$1}'|sh"' errored out: Error: spawn bash ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[debug] [XCUITest] Error : Command 'bash -c "ps -ax|grep -i \"/usr/local/lib/node_modules/deviceconsole\"|grep -i \"baa51e99d366568f3344f33e95d651960d371d6b\"|grep -v grep|awk '{print \"kill -9 \" \$1}'|sh"' errored out: Error: spawn bash ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[debug] [XCUITest] Error : Command 'bash -c "ps -ax|grep -i \"iproxy\"|grep -i \"baa51e99d366568f3344f33e95d651960d371d6b\"|grep -v grep|awk '{print \"kill -9 \" \$1}'|sh"' errored out: Error: spawn bash ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[XCUITest] Real device logger '/usr/local/lib/node_modules/deviceconsole' is a directory. Appending 'deviceconsole' executable
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /Users/xxxxx/Desktop/appium-master/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=baa51e99d366568f3344f33e95d651960d371d6b -configuration Debug' in directory '/Users/xxxxx/Desktop/appium-master/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/xxxxx/Library/Developer/Xcode/DerivedData/WebDriverAgent-cbfsytngebgyyvbdivyjmdiivtzv/Logs/Test/F5F8AE88-2B68-4BD7-8DBE-21F2A3D448DC/Session-WebDriverAgentRunner-2016-12-06_114333-JaEK0S.log
[debug] [WebDriverAgent] Device: Dec  6 11:43:39 iPod-touch XCTRunner[312] <Notice>: Running tests...
[debug] [WebDriverAgent] Device: Dec  6 11:43:40 iPod-touch XCTRunner[312] <Notice>: Continuing to run tests in the background with task ID 1
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...

**Comment by mykola-mokhnach** [comment]
What is the content of this file:
/Users/xxxxx/Library/Developer/Xcode/DerivedData/WebDriverAgent-cbfsytngebgyyvbdivyjmdiivtzv/Logs/Test/F5F8AE88-2B68-4BD7-8DBE-21F2A3D448DC/Session-WebDriverAgentRunner-2016-12-06_114333-JaEK0S.log
?

**Comment by Rdexmah** [comment]
13:58:28.803 Xcode[28654:1008459] Uploaded test configuration directory from: /var/folders/z0/nn0ck07s6ms8pzdmvpv8vbpxw2pm1k/T/com.apple.dt.XCTest/2B27CC7F-AD34-4722-AB58-EE584D6BCB2A/remote-container
13:58:28.803 Xcode[28654:1008459] Updated testing environment variables {
    "DTX_CONNECTION_SERVICES_PATH" = "/Developer/Library/PrivateFrameworks/DTXConnectionServices.framework";
    "DYLD_FRAMEWORK_PATH" = "/private/var/containers/Bundle/Application/419DDF58-0530-4A28-80BC-F3D26E61C97C/WebDriverAgentRunner-Runner.app/Frameworks:/Users/XXX/Library/Developer/Xcode/DerivedData/WebDriverAgent-asjzypkhkwbdladbetqrwssmkdkz/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks";
    "DYLD_LIBRARY_PATH" = "/private/var/containers/Bundle/Application/419DDF58-0530-4A28-80BC-F3D26E61C97C/WebDriverAgentRunner-Runner.app/Frameworks:/Users/XXX/Library/Developer/Xcode/DerivedData/WebDriverAgent-asjzypkhkwbdladbetqrwssmkdkz/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks";
    "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
    XCTestConfigurationFilePath = "/private/var/mobile/Containers/Data/Application/8C64CCE6-70DD-4110-B5C7-C4187884A9C2/tmp/WebDriverAgentRunner-2B27CC7F-AD34-4722-AB58-EE584D6BCB2A.xctestconfiguration";
}
13:58:29.851 Xcode[28654:1009469] Started debugserver on device. fd = 46
13:58:29.960 Xcode[28654:657452] Adding console adaptor <IDEConsoleAdaptor: 0x7f8d7522b5d0 'target'> for test session 2B27CC7F-AD34-4722-AB58-EE584D6BCB2A.
13:58:30.132 Xcode[28654:657452] Launch session finished initial intensive file IO.
13:58:30.132 Xcode[28654:657452] Waiting for test process to check in..., will wait up to 120s
13:58:30.132 Xcode[28654:657452] Test process runnable PID is 430.
13:58:32.066 Xcode[28654:1009864] Got proxy channel request from test bundle
13:58:32.067 Xcode[28654:1009864] Test bundle is ready, running protocol 22, requires at least version 8. IDE is running 22 and requires at least 8
13:58:32.067 Xcode[28654:1009865] Creating secondary transport and connection for whitelisting test process PID.
13:58:32.122 Xcode[28654:1009865] Creating the daemon control connection.
13:58:32.122 Xcode[28654:1009865] Resuming the secondary connection.
13:58:32.122 Xcode[28654:1009865] Whitelisting test process ID 430
13:58:32.128 Xcode[28654:1009458] Got whitelisting response and daemon protocol version 22
13:58:20.196 testmanagerd[414:53098] Launched testmanagerd from /Developer/usr/libexec/testmanagerd, built at Sunday, July 31, 2016 at 6:31:58 PM Pacific Daylight Time
13:58:20.198 testmanagerd[414:53098] Setting availability state.
13:58:20.199 testmanagerd[414:53098] Posting availability to test bundles...
13:58:20.200 testmanagerd[414:53123] IDE connected via lockdown over socket 4 (__54-[XCTestManagerIDEServer initWithLockdownServiceName:]_block_invoke)
13:58:20.201 testmanagerd[414:53123] Created session with socket 4
13:58:32.158 testmanagerd[414:53098] Received request to collect crash reports in directories '/var/mobile/Library/Logs/CrashReporter/' for processes with names 'XCTRunner', 'WebDriverAgentRunner-Runner', 'xctest'
13:58:20.218 testmanagerd[414:53123] Handled a proxy request from the IDE with session <XCIDESession: 0x100217540> proxy <_DTXProxy: 0x100408150>
13:58:20.219 testmanagerd[414:53098] __84-[XCIDESession _IDE_initiateSessionWithIdentifier:forClient:atPath:protocolVersion:]_block_invoke 2B27CC7F-AD34-4722-AB58-EE584D6BCB2A 1 4 from client DC2AD469-18CC-4E0B-9221-7F983BB689D2-28654-00001F50389C6E44 (/Applications/Xcode.app)
13:58:20.219 testmanagerd[414:53123] __45-[XCTestManager setIDESession:forIdentifier:]_block_invoke <XCIDESession: 0x100217540> -> 2B27CC7F-AD34-4722-AB58-EE584D6BCB2A
13:58:32.160 testmanagerd[414:53098] Initializing crash report observer for /var/mobile/Library/Logs/CrashReporter/
13:58:20.219 testmanagerd[414:53123] -[XCTestManager _handleRequestForSessionWithIdentifier:]
13:58:25.202 testmanagerd[414:53098] Considering exiting, 0 test sessions, 1 sessions with identifiers, 0 unidentified sessions, does not have control session...
13:58:32.160 testmanagerd[414:53098] Getting files in /var/mobile/Library/Logs/CrashReporter/
13:58:31.977 testmanagerd[414:53456] Received new test session connection (-[XCTestManager listener:shouldAcceptNewConnection:])
13:58:31.980 testmanagerd[414:53098] Initial orientation 5
13:58:31.983 testmanagerd[414:53458] Test session 2B27CC7F-AD34-4722-AB58-EE584D6BCB2A requested socket (-[XCTestSession _XCT_requestSocketForSessionIdentifier:reply:])
13:58:31.983 testmanagerd[414:53458] Test session 2B27CC7F-AD34-4722-AB58-EE584D6BCB2A requested socket (__57-[XCTestManager requestSocketForSessionIdentifier:reply:]_block_invoke)
13:58:31.983 testmanagerd[414:53458] -[XCTestManager _handleRequestForSessionWithIdentifier:]
13:58:31.983 testmanagerd[414:53458] Closing IDE connection before sending socket 5 to test host.
13:58:31.983 testmanagerd[414:53458] -[XCIDESession closeIDEConnection:] sending barrier
13:58:31.983 testmanagerd[414:53098] barrier flushed, closing DTXConnection to IDE, socket will not be closed
13:58:31.984 testmanagerd[414:53456] DTXSocketTransport disconnected
13:58:31.984 testmanagerd[414:53456] Disconnecting lockdown socket
13:58:31.984 testmanagerd[414:53119] __33-[XCTestManager closeIDESession:]_block_invoke <XCIDESession: 0x100217540>
13:58:31.984 testmanagerd[414:53119] Considering exiting, 1 test sessions, 0 sessions with identifiers, 0 unidentified sessions, does not have control session...
13:58:31.984 testmanagerd[414:53458] app info {
    BKSApplicationStateAppIsFrontmost = 1;
    BKSApplicationStateExtensionKey = 0;
    SBApplicationStateDisplayIDKey = "com.apple.test.WebDriverAgentRunner-Runner";
    SBApplicationStateKey = 8;
    SBApplicationStateProcessIDKey = 430;
    SBMostElevatedStateForProcessID = 8;
}
13:58:31.985 testmanagerd[414:53458] Got request for process assertion for pid 430.
13:58:31.985 testmanagerd[414:53458] Created process assertion for pid 430: <BKSProcessAssertion: 0x10040f120>, waiting for response from assertiond.
13:58:31.985 testmanagerd[414:53458] Starting to monitor com.apple.test.WebDriverAgentRunner-Runner
13:58:31.987 testmanagerd[414:53119] Got reply for process assertion request, success: YES
13:58:31.987 testmanagerd[414:53457] Got application state update: com.apple.test.WebDriverAgentRunner-Runner (430) -> 8
13:58:32.090 testmanagerd[414:53098] Sending socket 5 to test host
13:58:32.090 testmanagerd[414:53119] __33-[XCTestManager closeIDESession:]_block_invoke <XCIDESession: 0x100217540>
13:58:32.090 testmanagerd[414:53119] Considering exiting, 1 test sessions, 0 sessions with identifiers, 0 unidentified sessions, does not have control session...
13:58:32.153 testmanagerd[414:53119] IDE connected via lockdown over socket 6 (__54-[XCTestManagerIDEServer initWithLockdownServiceName:]_block_invoke)
13:58:32.153 testmanagerd[414:53119] Created session with socket 6
13:58:32.155 testmanagerd[414:53456] Handled a proxy request from the IDE with session <XCIDESession: 0x100217540> proxy <_DTXProxy: 0x1002204a0>
13:58:32.155 testmanagerd[414:53456] -[XCIDESession _IDE_initiateControlSessionForTestProcessID:protocolVersion:] 430 22
13:58:32.155 testmanagerd[414:53098] Set control session <XCIDESession: 0x100217540> with proto 22 and proxy <_DTXProxy: 0x1002204a0>
13:58:32.183 testmanagerd[414:53098] Found 183 files in /var/mobile/Library/Logs/CrashReporter/
13:58:32.183 testmanagerd[414:53098] Started monitoring /var/mobile/Library/Logs/CrashReporter/
13:58:31.867 XCTRunner[430:53397] Linked XCTest.framework from /var/containers/Bundle/Application/419DDF58-0530-4A28-80BC-F3D26E61C97C/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest, built at Friday, December 2, 2016 at 1:55:25 PM Pacific Standard Time
13:58:31.869 XCTRunner[430:53397] System uptime: 3:59:29
13:58:31.869 XCTRunner[430:53397] Process arguments: (
    "/var/containers/Bundle/Application/419DDF58-0530-4A28-80BC-F3D26E61C97C/WebDriverAgentRunner-Runner.app/XCTRunner",
    "-NSTreatUnknownArgumentsAsOpen",
    NO,
    "-ApplePersistenceIgnoreState",
    YES
)
13:58:31.869 XCTRunner[430:53397] Process environment: {
    "CFFIXED_USER_HOME" = "/private/var/mobile/Containers/Data/Application/8C64CCE6-70DD-4110-B5C7-C4187884A9C2";
    CLASSIC = 1;
    "DTX_CONNECTION_SERVICES_PATH" = "/Developer/Library/PrivateFrameworks/DTXConnectionServices.framework";
    "DYLD_FRAMEWORK_PATH" = "/private/var/containers/Bundle/Application/419DDF58-0530-4A28-80BC-F3D26E61C97C/WebDriverAgentRunner-Runner.app/Frameworks:/Users/XXX/Library/Developer/Xcode/DerivedData/WebDriverAgent-asjzypkhkwbdladbetqrwssmkdkz/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks";
    "DYLD_LIBRARY_PATH" = "/private/var/containers/Bundle/Application/419DDF58-0530-4A28-80BC-F3D26E61C97C/WebDriverAgentRunner-Runner.app/Frameworks:/Users/XXX/Library/Developer/Xcode/DerivedData/WebDriverAgent-asjzypkhkwbdladbetqrwssmkdkz/Build/Products/Debug-iphoneos:__PLATFORMS__/iPhoneOS.platform/Developer/Library/Frameworks";
    HOME = "/private/var/mobile/Containers/Data/Application/8C64CCE6-70DD-4110-B5C7-C4187884A9C2";
    LOGNAME = mobile;
    NSUnbufferedIO = YES;
    "OS_ACTIVITY_DT_MODE" = YES;
    PATH = "/usr/bin:/bin:/usr/sbin:/sbin";
    SHELL = "/bin/sh";
    TMPDIR = "/private/var/mobile/Containers/Data/Application/8C64CCE6-70DD-4110-B5C7-C4187884A9C2/tmp";
    USER = mobile;
    "XCODE_DBG_XPC_EXCLUSIONS" = "com.apple.dt.xctestSymbolicator";
    XCTestConfigurationFilePath = "/private/var/mobile/Containers/Data/Application/8C64CCE6-70DD-4110-B5C7-C4187884A9C2/tmp/WebDriverAgentRunner-2B27CC7F-AD34-4722-AB58-EE584D6BCB2A.xctestconfiguration";
    "XPC_FLAGS" = 0x0;
    "XPC_SERVICE_NAME" = "UIKitApplication:com.apple.test.WebDriverAgentRunner-Runner[0x2771]";
    "__CF_USER_TEXT_ENCODING" = "0x1F5:0:0";
}
13:58:31.870 XCTRunner[430:53397] Loading DTXConnectionServices from /Developer/Library/PrivateFrameworks/DTXConnectionServices.framework
13:58:31.974 XCTRunner[430:53397] Session ID 2B27CC7F-AD34-4722-AB58-EE584D6BCB2A
13:58:31.975 XCTRunner[430:53397] Registering for testmanagerd availability notify post.
13:58:31.975 XCTRunner[430:53397] testmanagerd availability confirmed via notify_get_state.
13:58:31.975 XCTRunner[430:53397] Initiating connection to testmanagerd to request socket for IDE connection.
13:58:31.977 XCTRunner[430:53397] Requesting socket
13:58:31.983 XCTRunner[430:53421] Got daemon protocol version 6
13:58:32.090 XCTRunner[430:53421] Got socket 4 from daemon, making connection to IDE
13:58:32.091 XCTRunner[430:53421] Creating connection with transport
13:58:32.092 XCTRunner[430:53421] Resuming connection
13:58:32.093 XCTRunner[430:53421] Messaging IDE proxy - _XCT_testBundleReadyWithProtocolVersion:22 minimumVersion:8
13:58:32.192 XCTRunner[430:53397] -[XCTestDriver _runSuite]
13:58:32.165 Xcode[28654:657452] Starting test plan, clearing initialization timeout timer.
13:58:32.193 XCTRunner[430:53397] Initializing for UI testing.
13:58:32.196 testmanagerd[414:53458] Performing block with diagnostics...
13:58:32.197 testmanagerd[414:53458] Waiting 15.0s for AX to finish loading...
13:58:32.200 testmanagerd[414:53458] _AXSApplicationAccessibilityEnabled() returned false
13:58:32.531 testmanagerd[414:53098] AX is loaded
13:58:32.547 testmanagerd[414:53458] AXDisableAccessibilityOnTermination() returned 0
13:58:32.550 testmanagerd[414:53458] Created system wide AX element <AXUIElement 0x100431540> {pid=0}
13:58:32.553 testmanagerd[414:53458] Registered for accessibility notification 1021
13:58:32.559 testmanagerd[414:53458] Registered for accessibility notification 1000
13:58:32.560 testmanagerd[414:53458] Registered for accessibility notification 1005
13:58:32.566 testmanagerd[414:53458] Registered for accessibility notification 1001
13:58:32.567 testmanagerd[414:53458] Registered for accessibility notification 1011
13:58:32.569 testmanagerd[414:53458] Registered for accessibility notification 4002
13:58:32.570 testmanagerd[414:53458] Registered for accessibility notification 4000
13:58:32.571 testmanagerd[414:53458] Registered for accessibility notification 4001
13:58:32.573 testmanagerd[414:53458] Registered for accessibility notification 5000
13:58:32.574 testmanagerd[414:53458] Block succeeded, canceling diagnostics.
13:58:33.295 testmanagerd[414:53458] AXUIElementSetMessagingTimeout(<AXUIElement 0x100431540> {pid=0}, 15) -> 0 
13:58:33.371 testmanagerd[414:53456] -[XCTestManager allowUITestControlForPID:] 430 vs 430
13:58:33.373 testmanagerd[414:53456] Registered for AX notification 4002
13:58:33.674 testmanagerd[414:53117] -[XCTestManager allowUITestControlForPID:] 430 vs 430
13:58:33.679 testmanagerd[414:53117] Registered for AX notification 1006
13:58:33.681 testmanagerd[414:53456] -[XCTestManager allowUITestControlForPID:] 430 vs 430
13:58:33.683 testmanagerd[414:53456] Registered for AX notification 1021
13:58:33.685 testmanagerd[414:53458] Got request for process assertion for pid 430.
13:58:33.686 testmanagerd[414:53458] Invalidating previous process assertion for pid 430.
13:58:33.689 testmanagerd[414:53458] Created process assertion for pid 430: <BKSProcessAssertion: 0x10040f120>, waiting for response from assertiond.
13:58:33.694 testmanagerd[414:53458] Got reply for process assertion request, success: YES
13:58:33.695 XCTRunner[430:53424] Got reply for background assertion for test process, acquired: YES.
13:58:33.697 XCTRunner[430:53397] Registering for UIApplicationDidEnterBackgroundNotification
13:58:33.698 XCTRunner[430:53397] Hitting home button to enter background.
13:58:33.700 testmanagerd[414:53458] -[XCTestManager allowUITestControlForPID:] 430 vs 430
13:58:33.701 testmanagerd[414:53458] Performing <XCDeviceEvent:0x10023f0f0 page 12 usage 64 duration 0.01s
13:58:33.706 testmanagerd[414:53458] Dispatching device event synthesis to background queue
13:58:33.707 testmanagerd[414:53458] Sleeping for 0.005000s before sending up event
13:58:33.715 testmanagerd[414:53458] Device event sent.
13:58:34.419 testmanagerd[414:53098] AX Notification 4002
13:58:34.456 XCTRunner[430:53462] Got AX notification 4002
13:58:34.454 testmanagerd[414:53098] Got user testing notification with payload {
    event = ButtonEventsCompleted;
}
13:58:34.454 testmanagerd[414:53098] Device event complete, replying to client.
13:58:34.799 testmanagerd[414:53098] AX Notification 1021
13:58:34.801 XCTRunner[430:53421] Got AX notification 1021
13:58:34.801 XCTRunner[430:53421] Got kAXPidStatusChangedNotification for 430: active
13:58:34.871 XCTRunner[430:53397] No application process found matching pid 430, caching
13:58:34.918 testmanagerd[414:53098] AX Notification 4002
13:58:34.921 testmanagerd[414:53098] Got user testing notification with payload {
    controllerClass = SBLeafIconViewController;
    event = ViewDidAppear;
}
13:58:34.922 testmanagerd[414:53098] AX Notification 1000
13:58:34.923 testmanagerd[414:53098] AX Notification 1000
13:58:34.923 testmanagerd[414:53098] AX Notification 1000
13:58:34.925 XCTRunner[430:53421] Got AX notification 4002
13:58:34.923 testmanagerd[414:53098] AX Notification 4002
13:58:34.927 testmanagerd[414:53098] Got user testing notification with payload {
    controllerClass = SBIconController;
    event = ViewDidAppear;
}
13:58:34.928 XCTRunner[430:53421] Got AX notification 4002
13:58:35.204 testmanagerd[414:53098] AX Notification 1011
13:58:35.378 testmanagerd[414:53119] Got application state update: com.apple.test.WebDriverAgentRunner-Runner (430) -> 4
13:58:35.398 testmanagerd[414:53098] AX Notification 4002
13:58:35.400 testmanagerd[414:53098] Got user testing notification with payload {
    controllerClass = SBAppContainerViewController;
    event = ViewDidDisappear;
}
13:58:35.401 testmanagerd[414:53098] AX Notification 1021
13:58:35.404 testmanagerd[414:53098] AX Notification 4002
13:58:35.405 testmanagerd[414:53098] Got user testing notification with payload {
    controllerClass = SBLeafIconViewController;
    event = ViewDidAppear;
}
13:58:35.409 XCTRunner[430:53420] Got AX notification 4002
13:58:35.411 XCTRunner[430:53420] Got AX notification 1021
13:58:35.411 XCTRunner[430:53420] Got kAXPidStatusChangedNotification for 430: suspended
13:58:35.415 XCTRunner[430:53424] Got AX notification 4002
13:58:35.416 XCTRunner[430:53397] Got UIApplicationDidEnterBackgroundNotification
13:58:35.420 XCTRunner[430:53397] No application process found matching pid 430, caching
13:58:35.439 XCTRunner[430:53397] Done initializing for UI testing.
13:58:35.439 XCTRunner[430:53397] Loading test suite...
13:58:35.449 XCTRunner[430:53397] Finished loading test suite, took 0.009s
13:58:35.454 XCTRunner[430:53397] -[_XCTestDriverTestObserver testBundleWillStart:]
13:58:35.454 XCTRunner[430:53397] Running suite...
13:58:35.458 XCTRunner[430:53397] -[_XCTestDriverTestObserver testSuiteWillStart:]
13:58:39.433 Xcode[28654:1009476] (LOG ARBITER) Rotating message buffer with 20 messages.
13:58:35.434 Xcode[28654:657452] _XCT_testSuite:Selected tests didStartAt:2016-12-02 21:58:35 +0000
13:58:35.462 XCTRunner[430:53397] -[_XCTestDriverTestObserver testSuiteWillStart:]
13:58:35.436 Xcode[28654:657452] _XCT_testSuite:WebDriverAgentRunner.xctest didStartAt:2016-12-02 21:58:35 +0000
13:58:35.464 XCTRunner[430:53397] -[_XCTestDriverTestObserver testSuiteWillStart:]
13:58:35.437 Xcode[28654:657452] _XCT_testSuite:UITestingUITests didStartAt:2016-12-02 21:58:35 +0000
13:58:35.466 XCTRunner[430:53397] -[_XCTestDriverTestObserver testCaseWillStart:] UITestingUITests testRunner
13:58:35.440 Xcode[28654:657452] _XCT_testCaseDidStartForTestClass:UITestingUITests method:testRunner
2016-12-02 13:58:31.489112 XCTRunner[430:53397] Running tests...
2016-12-02 13:58:34.676526 XCTRunner[430:53397] Continuing to run tests in the background with task ID 1
Test Suite 'Selected tests' started at 2016-12-02 13:58:35.456
Test Suite 'WebDriverAgentRunner.xctest' started at 2016-12-02 13:58:35.462
Test Suite 'UITestingUITests' started at 2016-12-02 13:58:35.463
Test Case '-[UITestingUITests testRunner]' started.
13:58:35.509 XCTRunner[430:53397] -[UITestingUITests testRunner] started activity <XCActivityRecord: 0x1700aada0> 2016-12-02 21:58:35 +0000: Start Test at 2016-12-02 13:58:35.468
13:58:35.484 Xcode[28654:657452] -[UITestingUITests testRunner] will start activity <__NSConcreteUUID 0x7f8d829c9560> 340A60ED-F520-409A-8233-E97310AB558E:'Start Test at 2016-12-02 13:58:35.468'
13:58:35.510 XCTRunner[430:53397] -[UITestingUITests testRunner] finished activity <XCActivityRecord: 0x1700aada0> 2016-12-02 21:58:35 +0000: Start Test at 2016-12-02 13:58:35.468 (0.040896s)
13:58:35.487 Xcode[28654:657452] -[UITestingUITests testRunner] did finish activity <__NSConcreteUUID 0x7f8d73a02f30> 340A60ED-F520-409A-8233-E97310AB558E:'Start Test at 2016-12-02 13:58:35.468'
13:58:35.513 XCTRunner[430:53397] -[UITestingUITests testRunner] started activity <XCActivityRecord: 0x1700aada0> 2016-12-02 21:58:35 +0000: Set Up
13:58:35.487 Xcode[28654:657452] -[UITestingUITests testRunner] will start activity <__NSConcreteUUID 0x7f8d6fb56e60> 25900259-BC3D-4724-A1D6-950E04B97EA4:'Set Up'
13:58:35.517 XCTRunner[430:53397] -[UITestingUITests testRunner] finished activity <XCActivityRecord: 0x1700aada0> 2016-12-02 21:58:35 +0000: Set Up (0.004776s)
13:58:35.491 Xcode[28654:657452] -[UITestingUITests testRunner] did finish activity <__NSConcreteUUID 0x7f8d746b66b0> 25900259-BC3D-4724-A1D6-950E04B97EA4:'Set Up'
13:58:35.892 testmanagerd[414:53098] AX Notification 1011
13:59:07.810 Xcode[28654:657452] Test operation failure: Test operation was canceled.
13:59:07.810 Xcode[28654:657452] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled." UserInfo={NSLocalizedDescription=Test operation was canceled.} didCancel: 1

**Comment by JasonZhu0603** [comment]
I met the same problem with same log info as you attached, could someone help around this? @triager 
@Rdexmah @mykola-mokhnach 

Thanks a lot. 

Thx
Jason

**Comment by Rdexmah** [comment]
Solution that  I can suggest , Downgrade ur appium to 1.6.0
