### ISSUE TITLE
appium-xcuitest-driver: Find with xpath does not work as expected

### ISSUE THREAD

**Issue by cschabetsberger-micro-focus** [appium/appium#7449]
## The problem

Some find with xpath operations do not work as expected. For example:
 * Find with "path" attribute does not work: Path is in the hierarchy from Appium but it is not in the hierarchy of the WebDriverAgent which (I think) is the reason for this issue.

Example: If the hierarchy contains an element like the following
`<XCUIElementTypeImage name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0/0/0/0/0/0/0/0/0/0" x="0" y="0" width="320" height="64">`

The following find does not work (i.e. the call throws a NoSuchElementException)
`appiumDriver.findElementByXPath("//XCUIElementTypeImage [@path='/0/0/0/0/0/0/0/0/0/0/0/0/0/0']");`

 * Find with empty attribute value does not work:
`appiumDriver.findElementByXPath("//XCUIElementTypeImage [@name='']");`

This call throws also a NoSuchElementException although the element exists in the hierarchy.

## Environment

* Appium 1.6.1
* macOS Sierra 10.12:
* Node.js 6.9.1:
* iOS 10 XCUITest:
* Simulator

**Comment by JaniJegoroff** [comment]
Have you tried Appium 1.6.2? There are some improvements around xpaths.

**Comment by mykola-mokhnach** [comment]
@cschabetsberger-micro-focus This is by design. Only these XPath attributes are available for search  prior to Appium 1.6.2:
name, value, label
And after 1.6.2:
name, value, label, x, y, width, height, visible, enabled

> appiumDriver.findElementByXPath("//XCUIElementTypeImage [@name='']")

should be replaced with //XCUIElementTypeImage[not(@name)]

**Comment by jlipps** [comment]
@cschabetsberger-micro-focus how are you guys using the `path` attribute?

In general `path` is something that the underlying automation doesn't know about, Appium added it to its xml schema to help with things like building the inspector

**Comment by bakiko** [comment]
@jlipps 
I did testing automation with iOS 9 (real device) with driver.find_elements(By.XPATH,([('XPATH', '/*[1]/*[1]')])). Now, in iOS10, it does not work. How do the research with path in iOS 10 (Appium 1.6.3, real device).
Thank you for help

**Comment by jlipps** [comment]
@bakiko i would recommend dumping the page source and constructing a valid xpath query based on what you see there.
