### ISSUE TITLE
iOS10 - WebdriverAgent expires

### ISSUE THREAD

**Issue by sondremare** [appium/appium#7450]
## The problem

Sometimes (more than not) the tests just fail because of a socket hang up on iOS 10. There is no consistent way to reproduce this issue, it appears random.

Log line I believe to be the culprit is:
[debug] [WebDriverAgent] Sim: Dec  6 17:06:09 controlosxprod1ahostondemandosx103 XCTRunner[5273]: background task expired!!!

But I have no idea on how to fix it.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS 10.12
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: iOS 10.1
* Real device or emulator/simulator: iPhone 6 simulator
* Appium CLI or Appium.app|exe: appium cli

## Link to Appium logs

https://gist.github.com/sondremare/b71005c4421d82ada3b1e437a7fe45b2

**Comment by amedvedjev** [comment]
+1. met same issue when test was hanging for 50min. (as workaround added timeout in test execution and repeat).

**Comment by jlipps** [comment]
I'm sorry, but this appears to be a WebDriverAgent issue, not a Appium issue. Please report it at https://github.com/facebook/WebDriverAgent/issues
