### ISSUE TITLE
Cant launch SafariLauncher on real iOS device - Appium 1.5.3

### ISSUE THREAD

**Issue by mzbedat** [appium/appium#7452]
## The problem

SafariLauncher is not launched on real iOS device

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: OS X 10.11.6
* Node.js version (unless using Appium.app|exe): 6.9.2
* Mobile platform/version under test: iOS 9.3.3
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium GUI

## Details

I took this version of SafariLauncher: https://github.com/budhash/SafariLauncher

- ran the ./build.sh, and then took the SafariLauncher.zip generated and located it under:
/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher

- Opened the project with Xcode and used my provisioning profile to deploy it on my device with this bundle Id: com.bytearc.SafariLauncher

- ran the iOS_webkit
ios_webkit_debug_proxy -c 99a093d37ad2ab93e0fafd00320689438fcba433:27753 -d

But still not able to launch the SafariLauncher

## Link to Appium logs

[appium.log](https://gist.github.com/mzbedat/c560ed32587f7e97c2f10a56f627b724) 

![snip20161207_1](https://cloud.githubusercontent.com/assets/17043182/20969612/6ca70ea6-bc92-11e6-8dae-8d1631fab891.png)

![snip20161207_2](https://cloud.githubusercontent.com/assets/17043182/20969619/7316e298-bc92-11e6-8e60-5d625f00b868.png)

**Comment by mzbedat** [comment]
I found that I had the wrong bundle ID in my provisioning profile for Safari Launcher:

![snip20161207_3](https://cloud.githubusercontent.com/assets/17043182/20971749/459c520e-bc9b-11e6-9f88-ec7da23cc6f2.png)
I changed to:
![snip20161207_4](https://cloud.githubusercontent.com/assets/17043182/20971760/50c08f7e-bc9b-11e6-95af-6ff4944cfee2.png)

But now I'm getting:
Could not find button to launch Safari. Make sure you are using the latest version of SafariLauncher that appium is using

**Comment by mzbedat** [comment]
When trying to launch it on Simulator the SafariLauncher is opened but kind of stuck and it can navigate to the URL!

From Appium:

>[MJSONWP] Encountered internal error running command: Error: Could not navigate to webview; there are none!
    at IosDriver.spinHandles$ (lib/commands/context.js:478:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:104:47)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:115:28
    at flush (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[debug] [iOS] No web frames found.
[HTTP] <-- POST /wd/hub/session 500 178731 ms - 183 
[HTTP] <-- GET /wd/hub/status - - ms - - 
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] --> GET /wd/hub/status {}

**Comment by jlipps** [comment]
@mzbedat are you running ios-webkit-debug-proxy?

**Comment by mzbedat** [comment]
Hi,
When I try to launch it for simulator I'm getting:

>MacBook-Air:build admin$ ios_webkit_debug_proxy -c 47C0B0B6-096E-472D-9DA4-325F93505BB9:27753 -d
Unknown file: 47C0B0B6-096E-472D-9DA4-325F93505BB9:27753
ss.add_fd(3)
Unknown file: 47C0B0B6-096E-472D-9DA4-325F93505BB9:27753
ss.recv fd=3 len=294

I thought the webkit is only for real devices, no?

**Comment by mzbedat** [comment]
Any ideas please... What am I missing?
Why its working from real device and from simulator its not?

I noticed that when deploying the SafariLauncher project from Xcode to my device the SafariLauncher app is installed on it and a shortcut icon is created, but when deploying it on simulator its not there... so it suppose to be installed each time the flow run?

**Comment by jlipps** [comment]
@mzbedat are you trying to run a test on a real device or a simulator? ios-webkit-debug-proxy and SafariLauncher are only for real devices. Your log shows that you are attempting to run on a real device (you used the `udid` capability, which is only for real devices), but now you're talking about it not working on a simulator? I'm confused.

**Comment by mzbedat** [comment]
Hi,
Please correct me if am doing something wrong...

I need to run Safari on both real device and simulators and play videos from sites like: DailyMotion, Metacafe, etc...

1. real device
In order to have it working I need to start appium with these caps:
- Use Mobile Safari
- Force device = iPad
- UDID = my device did
then start the iOS_webkit:
ios_webkit_debug_proxy -c 99a093d37ad2ab93e0fafd00320689438fcba433:27753 -d

and its working fine that way.

2. Simulator - I got it working finally (have no idea how! maybe after restarting my mac)
What am doing to have it working:
- Start Appium without "Force Device" & UDID. Instead I pass the simulator name in deviceName
- Start the iOS_webkit:
$ ios_webkit_debug_proxy
Listing devices on :9221
(without starting the webkit the simulator is not opening! which is conflicting with what I had read that the iOS_webkit is only for real device)

Can u guide me how to work with simulators if SafariLauncher is not needed there?
Anyway,
I have another problem that I wanted to verify... the Safari screen is not being terminated after the test is done, despite am using "Close All Applications" (from robot framework)!

**Comment by jlipps** [comment]
For simulators, you should not run ios-webkit-debug-proxy. You simply run an Appium test with these capabilities:

```
{
  "platformName": "iOS",
  "platformVersion": "10.1",
  "browserName": "Safari",
  "deviceName": "iPhone 6"
}
```

(adjusting platformVersion and deviceName for your use case)

Going to close this since since starting Safari on sims is part of our build and is well tested. If you have a repro for a bug regarding this, we can reopen.
