### ISSUE TITLE
Cannot properly start testing Android Native App (locally and via SauceLabs)

### ISSUE THREAD

**Issue by NikitaSmall** [appium/appium#7453]
Good day!

I am creating an integration for my testing environment with SauceLabs to be able test applications (both web and native). It's all fine when I work with web or iOS application with Appium both locally and via SauceLabs. However I met mentioned in topic problem when tried to run test. Whenever I try to start tests for Android app (no matter where, locally or on SauceLabs), I got the error. It happens before any test code involved, on the time when platform is initialised.

This is example of stacktrace (I am a ruby developer and testing tool is written in ruby) for this tests.

```
Failure/Error: if e = error()
     
     Selenium::WebDriver::Error::UnknownError:
       Method has not yet been implemented
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:649:in `raw_execute'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:627:in `execute'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:190:in `getCurrentUrl'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/common/driver.rb:147:in `current_url'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/capybara-2.10.2/lib/capybara/selenium/driver.rb:73:in `current_url'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/capybara-2.10.2/lib/capybara/session.rb:194:in `current_url'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.14/lib/capybara-screenshot/rspec.rb:55:in `block in after_failed_example'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/capybara-2.10.2/lib/capybara.rb:355:in `using_session'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.14/lib/capybara-screenshot/rspec.rb:54:in `after_failed_example'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/capybara-screenshot-1.0.14/lib/capybara-screenshot/rspec.rb:84:in `block (2 levels) in <top (required)>'
     # /Users/nikitasmall/.rvm/gems/ruby-2.3.0/gems/ui_automation-0.2.0/lib/ui_automation/runner.rb:7:in `run'
```

From SauceLabs log and support team I got this: 

```
The following error is being returned for the command: AppiumDriver.getUrl()
{"message":“Method has not yet been implemented”}
```

## Environment

* Appium version: locally I have 1.6.2, on SauceLabs 1.5.3 version is used,
* Local OS is OS X El Capitan 10.11.6, Saucelabs starts new virtual machine and I am not sure about their version,
* Local Node.js version is 5.12.0,
* in both cases I test Android app, inside the generic Android emulator, Android version is 5.1,
* Both locally and on SauceLabs emulators are used,
* Appium CLI is used locally, something like that on SauceLabs I guess.

## Details

The app I am trying to test is hybrid app: webpage bundled with Cordova into usual Android apk. Is it possible that this could somehow raise this issue?

Also I have a question (I shouldn't but I have realised it recently): do I need to specify any additional capabilities when my app needs internet connection?

## Link to Appium logs

Local logs: https://gist.github.com/NikitaSmall/c1acc785befd9bc169d4b17dd1a9cd72
SaucaLabs logs: https://gist.github.com/NikitaSmall/00e50dedd9ca4c676a91dd141a4d3fd9

## Code To Reproduce Issue

I can't give you an application, but I can give you my configuration code (most important parts). It quite generic and I am almost 100% sure that the problem is somewhere else. Anyway, here is a meaningful part of configuration:  https://gist.github.com/NikitaSmall/42e4ca68d8895c9b384231895b46cfbb

**Comment by imurchie** [comment]
These look like two separate issues.

For the SauceLabs logs: You are trying to set a url on a native application and it is failing as not implemented. This is correct.

For the local ones, this issue was fixed. What version of Appium are you using? Can you provide the _full_ logs as a [gist](https://gist.github.com)?
