### ISSUE TITLE
Not able to install npm on my mac

### ISSUE THREAD

**Issue by shay777** [appium/appium#7454]
I had appium installed and I deleted it. I also deleted node.js and npm.
I re-installed node.js and npm and I am not able to install appium now using the command:
npm install -g appium

not sure what is happening here. any help please?

thanks

https://gist.github.com/shay777/3d4887b23301e55edcbffdedabe2e850

**Comment by mykola-mokhnach** [comment]
downgrade npm to 3.10.10

**Comment by slipy12** [comment]
or try 4.0.5

**Comment by shay777** [comment]
thanks. 
i downgraded npm to 3.10.9 and it is now working.
the issue can be closed.
