### ISSUE TITLE
Appium inspector does not launch as it does not recognise the bundle id of the app

### ISSUE THREAD

**Issue by rajeshwaran88** [appium/appium#7455]
Appium inspector does not launch as it does not recognise the bundle id of the app

Install from XCode 7.3.1 to the real device is successful. But Appium does not recognise the bundle id of the app and so not able to run the scripts and also the inspector doesn't launch. This started happening recently just before the launch of iOS 10 and also the company changed the team name for the certificate from X to Y but the Bundle ID was always the same.

## Environment

* Appium version : 1.4.13
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13 - worked as expected until the company name changed
* Desktop OS/version used to run Appium: OS X El Capitan
* Mobile platform/version under test: iOS 8 / iOS 9
* Real device or emulator/simulator: iPhone 5S
* Appium CLI or Appium.app|exe: Appium app

## Details

As mentioned above since the new iOS and the change in the team name, Appium is unable to recognise the bundle id. Not sure where to edit or view the desired capabilities related to the bundle id to see if the change in team name is affecting Appium.

## Link to Appium logs
Attached
[Appium Log.zip](https://github.com/appium/appium/files/636868/Appium.Log.zip)

Tried with Appium 1.5.2 and also with XCode 8 and also with new certificates as well.  Still facing the same issue. Unsure of how to modify the Appium's desired capabilities.
Also this is an error message that i see in the log - Not auto-detecting udid, running on sim

**Comment by jlipps** [comment]
Can you link to a gist of an appium 1.6.2 log exhibiting this error?

**Comment by rajeshwaran88** [comment]
Sorry I am kind of new to this. I have so far worked with 1.4.13 and 1.5.2 with the GUI. Does Appium 1.6.2 have GUI support? I mean do we have app file for the 1.6.2 version? As much I researched I can see options to run via terminal and I don't have enough training to run via the terminal with proper desired capabilities.

**Comment by vikramvi** [comment]
@rajeshwaran88 please try https://github.com/appium/appium-dot-app/issues/577

@triager please close this issue

**Comment by rajeshwaran88** [comment]
@vikramvi Thanks for the suggestion but it did not resolve the issue. @triager request you to please keep it open. I am attaching the log and desired capabilities set as well. I am going through the other options provided in the other thread and will keep trying more from my end. Thanks!!!

**Comment by jlipps** [comment]
@rajeshwaran88 appium 1.6.2 has no official GUI support. we have stopped maintaining the old appium-dot-app and are in the process of building a new one that the current team can maintain. until then, there are guides online about how to get appium 1.6.2 into the old appium-dot-app. for now, i would recommend running from the command line. will keep this open to give you a chance to get logs for 1.6.2 exhibiting the problem.

**Comment by jlipps** [comment]
The new GUI has been out for some time now: https://github.com/appium/appium-desktop.
