### ISSUE TITLE
Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

### ISSUE THREAD

**Issue by jtrimachi** [appium/appium#7456]
## The problem
Running appium to test an application.  I am running XCUITestDriver version 2.2.0.  Co-worker is running version < 2.2.0 and no issues.  However when i run i get following error: 

Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

Have run with both using xcconfig file in capabilities and without. 

## Environment

* Appium version  1.6.2
* Desktop OS/version used to run Appium: Mac OS X Sierra
* Node.js version (unless using Appium.app|exe): 7.2.0
* Mobile platform/version under test: iOS 10.1
* Real device or emulator/simulator: Real Device - iPad Mini 2
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs
https://gist.github.com/jtrimachi/280f769472635aa27be3bf83236bbbfa

## Code To Reproduce Issue 

DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability("appium-version", "1,6");
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("platformVersion", "10.1");
		capabilities.setCapability("deviceName", "iPad");
		capabilities.setCapability("app", "/Users/jtrimac/Library/Developer/Xcode/DerivedData/MyAppp-amnzmnshxepyjydfplfnczbbgabh/Build/Products/Debug-iphoneos/MyApp.app");
		capabilities.setCapability("bundleId", "com.t-mobile.MyApp");
		capabilities.setCapability("newCommandTimeout", 300);
		capabilities.setCapability("udid", "someUDID");
                //capabilities.setCapability("xcodeConfigFile","/User/jtrimac/Documents/myconfig.xcconfig");
		capabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
		wd = new IOSDriver<WebElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);

		Set<String> contextNames = wd.getContextHandles();
		for (String contextName : contextNames) {
		    System.out.println(contextName); //prints out something like NATIVE_APP \n WEBVIEW_1
		}

**Comment by mykola-mokhnach** [comment]
code 65 - problems with WDA signing

**Comment by jtrimachi** [comment]
Ok I am still new to apple how do i resolve? attached is screenshot of how i am signing WebDriverAgent Runner

![screen shot 2016-12-07 at 9 28 55 am 2](https://cloud.githubusercontent.com/assets/5826767/20978944/aa1f29b8-bc5f-11e6-84ac-8496b8177f9f.png)

**Comment by jeangb** [comment]
Hi I have the same problem. Informations about how to get this Xcode project builded would be nice.

**Comment by imurchie** [comment]
Appium 1.6.4-beta has been released (to upgrade, run `npm uninstall -g appium && npm install -g appium@beta`). How we connect to devices has been significantly changed, and should be more reliable. Please try it out.

There is some documentation here: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

I am closing this issue since the details will have changed completely. If you still have problems, please see if there is a similar issue, or else create a new issue with as much information as possible. We are committed to tracking down these elusive problems!

**Comment by dipakingale** [comment]
I am able to execute scripts using Appium 1.6.4-Beta.2 version on iOS device 10.2 but strange thing is after 10 attempts, am getting above error and after restarting the device, scripts work normally till 10 attempts.
This is really frustrating.

Could you please tell update me how to overcome this issue??

Thanks in advance.

**Comment by mykola-mokhnach** [comment]
@dipakingale Are you using iPhone 5 or older to run automated tests? Then replace it with iPhone 6 or something better. There is a known issue about XCTest compatibility and 32-bit iDevices.

**Comment by dipakingale** [comment]
I am using iPhone 5 with iOS 10.2 version.

Thanks for the quick reply. I will try.

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach @imurchie i am facing a similar issue wherein i get this error:
Device
iPhone 5s
iOS 10.3.1 
xcode 8.3.2
2017-05-07 12:39:03.765 xcodebuild[45156:1320179] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart wil be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}


But it works completely fine on iPhone 6. I use the same set of certificates on both. 
iPhone 6 is on iOS 10.2.1.

is iPhone 5S also included in the list of incompatible devices?
"There is a known issue about XCTest compatibility and 32-bit iDevices."

**Comment by mykola-mokhnach** [comment]
iPhone 5S is 64bit, but seems to be not a good match as well. Check Apple forums to make sure.
