### ISSUE TITLE
Cannot access control center on real IOS device

### ISSUE THREAD

**Issue by lmlindy** [appium/appium#7457]
## The problem
I am not able to access the control center or change the wireless connectivity during a test on a real device.

## Environment

* Appium version: 1.5.3
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: Mac / El Capitan
* Node.js version (unless using Appium.app|exe): NA
* Mobile platform/version under test: iOS 9
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium.app

## Details

I used to be able to swipe up from the bottom of the screen to access the control center on a real IOS device, which I used in many tests to set airplane mode and Wifi connectivity. Since updating to Appium 1.5 this functionality has not worked. The swipe is not pulling up control center, and trying to start the swipe below the screen creates a "point is not within the bounds of the screen" exception. If this functionality is going to be broken going forward, I would like some alternative to pull up the control center.

## Code To Reproduce Issue 

```
int swipeX = driver.manage().window().getSize().getWidth() /2;
int swipeY = driver.manage().window().getSize().getHeight();
driver.swipe(swipeX, swipeY, swipeX, swipeY *2/3, 1000);
```

**Comment by jlipps** [comment]
Please attach a full set of Appium logs as a [gist](https://gist.github.com)
