### ISSUE TITLE
Get "Chrome version must be >= 53.0.2785.0" with Appium 1.6.2 and Android 6 Emulator

### ISSUE THREAD

**Issue by ltutitote** [appium/appium#7459]
## The problem
I got this error whenever switching to webview context: 
`*error occurred while processing the command. Original error - unknown error - Chrome version must be >= 53.0.2785.0
  (Driver info - chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.1 x86_64) (Selenium - -WebDriver - -Error - -UnknownError)*`

## Environment
* Appium version: 1.6.2
* OS: Mac OS X 10.11.6 x86_64
* Mobile platform: Android 6 (API23)
* Genymotion Emulator
* Appium CLI

## Details
I have no problem when switching to webview context with Android 5.0, Android 5.1 Emulator and Android 6 Real device with same environment but facing this error with Android 6 Emulator. I tried many ways but no luck:
- Reinstall chromedriver with all versions 2.2, 2.3, 2.4, 2.5 and 2.6
- Install latest chrome version on emulator
- Install latest appium 1.6.2 (1.6.1 got same problem as well)

## Link to Appium logs
https://gist.github.com/ltutitote/88bec54efe31a267b9766953c7155433

**Comment by mykola-mokhnach** [comment]
Use _chromedriverExecutable_ to set the path to an older chromedriver executable or upgrade the renderer component for your webview.

**Comment by ltutitote** [comment]
Hi @mykola-mokhnach, thank you so much for your help. Do you mean **chromedriverExecutable** is Chrome Driver that gets from https://sites.google.com/a/chromium.org/chromedriver/? I tried with many versions like 2.2, 2.3, 2.4, 2.5 and 2.6 but no luck. Could you help to give more details about that?

**Comment by mykola-mokhnach** [comment]
then you do something wrong. Make sure the correct binary (provided by you) is set by checking the logs.

```
[Chromedriver] Set chromedriver binary as: ...
```

**Comment by ltutitote** [comment]
Thanks @mykola-mokhnach, I solved this problem by myself. For anyone who facing this issue, just download and install https://play.google.com/store/apps/details?id=com.google.android.webview on emulator and it will work perfectly

**Comment by hardik-d** [comment]
@ltutitote are you testing a hybrid app?

**Comment by ankitgupta0304** [comment]
Update WebView and chrome Browser on device from PlayStore, ur problem would be resolve
