### ISSUE TITLE
XCUITest Driver Closes App During Tests

### ISSUE THREAD

**Issue by raymondlapak** [appium/appium#7460]
## The problem

I tried to upgrade my Appium XCUITest after learning that there is an implementation for faster XPath traverse. However when I upgraded to appium-xcuitest-driver to 2.4.0 from 2.0.34, tests start to fail as Appium closes app in the middle of tests.

## Details

It seems that Appium requests webdriver agent to be installed (again??) in the middle of test as it is shown in the log file (gist link below). The first request for installation of webdriver agent is shown at line 49 and the second one is shown at line 918. From line 918 below, tests are starting to fail because, well obviously because the webdriver agent has been restarted and Appium forcefully closes the app.

`[Line 49] [debug] [WebDriverAgent] Sim: Dec  8 11:40:24 Raymonds-MacBook-Pro CoreSimulatorBridge[18034]: Requesting installation of file:///Users/raymondluckysumargo/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/ with options: {`

`[Line917] [debug] [WebDriverAgent] Sim: Dec  8 11:43:12 Raymonds-MacBook-Pro CoreSimulatorBridge[18034]: Requesting installation of file:///Users/raymondluckysumargo/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/ with options: {`

#7383 
## Link to Appium logs

https://gist.github.com/raymondlapak/c2f4632b3dcc987d0f86cc1efb0f01c8

**Comment by mykola-mokhnach** [comment]
I think I know what it might be. WDA crashed because of a bug, which I have fixed recently, and the system tried to restart it automatically. You can either change your xpath locator:

```
{"using":"xpath","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeNavigationBar[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]"}

```

or update WDA sources from [master](https://github.com/facebook/WebDriverAgent) manually and wait for the next Appium release, which will include the fix.

**Comment by raymondlapak** [comment]
Thanks @mykola-mokhnach , will try your suggestion. Keeping this issue open for now.
