### ISSUE TITLE
Add support to use preinstalled WDA in real devices

### ISSUE THREAD

**Issue by Prakash-Saravanan** [appium/appium#7462]
## The problem

Appium codesigns the WebDriverAgent.xcodeproj, builds and tests (installs) it on the device each time a driver session is created. This becomes unnecessary when I run more than one driver session or when WDA is already installed/running on the device (actually I need to run around 100 tests)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.x
* Desktop OS/version used to run Appium: Mac OS X 10.11.6
* Node.js version (unless using Appium.app|exe): 7.2.1
* Mobile platform/version under test: iOS 9.3.5
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

When I run multiple tests, WDA gets codesigned, built and installed for each test.

**Comment by mykola-mokhnach** [comment]
There is such capability already: _usePrebuiltWDA_ since Appium 1.6.1

**Comment by Prakash-Saravanan** [comment]
Yes. It does not work for ios 9.3.5 also.

**Comment by Prakash-Saravanan** [comment]
Is there any way to use the WDA that is already installed in the device?
Instead of codesigning everytime or using WDA.ipa externally, it will be great to just launch the WDA that is installed already in the device.

**Comment by Prakash-Saravanan** [comment]
Also, if the previous driver session has not ended properly, the next session is not able to get launched. It waits intermittently. Need to add session-override capability to WDA instance also.

**Comment by Prakash-Saravanan** [comment]
The capabilities usePrebuiltWDA and webDriverAgentUrl are not working.
Appium still tries to build and install WDA even if WDA is already installed and usePrebuiltWDA is set to true.
When having webDriverAgentUrl capability set, it does not work as expected. The webDriverAgentUrl is alive before sending any request. After appium begins to send any request to the webDriverAgentUrl, it hangs up and removes WDA from device.

**Comment by smccarthy** [comment]
usePrebuiltWDA Doesn't work with iOS 9, someone mentioned above. What version of iOS are you trying ? Above says 9, but maybe you upgraded ?

**Comment by Prakash-Saravanan** [comment]
iOS 9.3.5

**Comment by smccarthy** [comment]
ok, so this issue is only about webDriverAgentUrl ?

**Comment by Prakash-Saravanan** [comment]
yeah.. as mentioned above

> When having webDriverAgentUrl capability set, it does not work as expected. The webDriverAgentUrl is alive before sending any request. After appium begins to send any request to the webDriverAgentUrl, it hangs up and removes WDA from device.

**Comment by Prakash-Saravanan** [comment]
The capability usePrebuiltWDA is not working for iOS 10 also.
It says "usePrebuiltWDA is set, but on real device. So skipping"

**Comment by imurchie** [comment]
This should work in the latest version of the `appium-xcuitest-driver` driver, 2.5.1.

**Comment by Prakash-Saravanan** [comment]
@imurchie yes. it works with appium-xcuitest-driver driver, 2.5.1.
But still it tries to install WDA into the device every time when launching driver session.

**Comment by imurchie** [comment]
Yes, that is how it works. Even when using a pre-built one, it just doesn't build it. There is no other way.

**Comment by pyraman** [comment]
Hi all! I'm facing the same problem with appium-xcuitest-driver version 2.28.1.
Is there any way to prevent driver from removing WebDriverAgent?

**Comment by wei-gu** [comment]
I am using ios 11, phone looks like hanging there each time xcodebuild install WDA on to it. It would be great to use a command to launch pre-installed WDA instead of re-installing WDA every session. Anyone has clue on how to to this?
