### ISSUE TITLE
dearchitect: appium-logger

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7465]
`appium-logger` has been moved to `appium-support` instead of living in its own package. We need to update references in these other packages:

* [x] appium
* [x] appium-adb
* [x] appium-android-driver
* [x] appium-chromedriver
* [x] appium-fake-driver
* [x] appium-ios-driver
* [x] appium-selendroid-driver
* [x] appium-uiautomator2-driver
* [x] appium-windows-driver
* [x] appium-xcuitest-driver
* [x] appium-ci
* [x] appium-support
* [x] appium-xcode
* [x] node-simctl

And also:

* [x] deprecate `appium-logger` on NPM with notice to import from `appium-support` instead

Let's do this after all the other dearchitecture issues so it's easier! If we do that, we can omit changing / publishing all these packages:

* [x] appium-android-bootstrap
* [x] appium-doctor
* [x] appium-instruments
* [x] appium-ios-simulator
* [x] appium-remote-debugger
* [x] appium-uiauto
* [x] appium-uiautomator
* [x] authorize-ios

**Comment by jlipps** [comment]
Hmm, if we do this after a bunch of other dearchitectures, it will be less work. Maybe we should hold off until there are fewer packages? Might be best to work in a fashion where we do the packages which have fewest dependents first.

**Comment by jlipps** [comment]
@imurchie I'm now kind of wondering if we want to put appium-logger inside appium-support instead of appium-base-driver. How much sense does it make for e.g. node-simctl, appium-ci, or appium-support to import appium-base-driver?

**Comment by imurchie** [comment]
That's a thought, yes. What is the plan for `appium-support` _vis-a-vis_ the dearchitecture work? Will it remain it's own thing?

**Comment by jlipps** [comment]
Yeah, as much as I'd like to find a better home for it, it seems weird to shoehorn it into anything else. I'm fine having it remain separate.

**Comment by imurchie** [comment]
PR for youiengine driver: https://github.com/YOU-i-Labs/appium-youiengine-driver/pull/46

**Comment by imurchie** [comment]
Waiting now only for the release of Appum 1.6.4, to be completely free of `appium-logger` package (already in, just needs publishing).

**Comment by imurchie** [comment]
Moved into `appium-boneyard`. The only things using `appium-logger` are themselves deprecated at this point.
