### ISSUE TITLE
dearchitect: appium-cookies

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7466]
* [x] move appium-cookies code into appium-ios-driver
* [x] update imports in appium-ios-driver
* [x] ensure appium-cookies tests/CI are now a part of appium-ios-driver
* [x] publish new appium-ios-driver
* [x] replace appium-cookies README with deprecation notice
* [x] deprecate appium-cookies on NPM
* [x] move appium-cookies repo to appium-boneyard

**Comment by jlipps** [comment]
work being done at https://github.com/appium/appium-ios-driver/pull/204

**Comment by imurchie** [comment]
`appium-ios-driver@1.14.0` published with `appium-cookies` brought in.

**Comment by jlipps** [comment]
did the NPM deprecation and moved the repo to boneyard.

**Comment by imurchie** [comment]
Cool! I closed my PR.
