### ISSUE TITLE
dearchitect: appium-ios-log

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7467]
* [x] move appium-ios-log code into appium-ios-driver
* [x] update imports in appium-ios-driver
* [x] ensure appium-ios-log tests/CI are now a part of appium-ios-driver
* [x] publish new appium-ios-driver
* [x] update imports in appium-xcuitest-driver to import from appium-ios-driver
* [x] replace appium-ios-log README with deprecation notice
* [x] deprecate appium-ios-log on NPM

**Comment by imurchie** [comment]
I moved the repo into `appium-boneyard` too soon, it seems. There is a PR there to update the README, then this ought to be closeable.
