### ISSUE TITLE
dearchitect: appium-uiauto

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7468]
* [x] move appium-uiauto code into appium-ios-driver
* [x] update imports in appium-ios-driver
* [x] ensure appium-uiauto tests/CI are now a part of appium-ios-driver
* [x] publish new appium-ios-driver
* [x] replace appium-uiauto README with deprecation notice
* [x] deprecate appium-uiauto on NPM

**Comment by imurchie** [comment]
`appium-ios-driver@1.21.0` now includes the `uiauto` code.

**Comment by imurchie** [comment]
`appium-uiauto` moved to `appium-boneyard` org.
