### ISSUE TITLE
dearchitect: appium-doctor

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7474]
* [ ] move appium-doctor code into appium
* [ ] expose appium-doctor binary from appium
* [ ] ensure appium-doctor tests/CI are now a part of appium
* [ ] update appium docs to reference new usage for appium-doctor (i.e., delete references to npm installing it on its own)
* [ ] replace appium-doctor README with deprecation notice/link
* [ ] deprecate appium-doctor on NPM

**Comment by mykola-mokhnach** [comment]
Closed as fixed
