### ISSUE TITLE
dearchitect: appium-uiautomator2-installer

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7476]
* [x] move appium-uiautomator2-installer code into appium-uiautomator2-driver
* [x] ensure appium-uiautomator2-installer tests/CI are now a part of appium-uiautomator2-driver
* [x] publish new appium-uiautomator2-driver, ensuring it installs correctly
* [x] replace appium-uiautomator2-installer README with deprecation notice/link
* [x] deprecate appium-uiautomator2-installer on NPM
* [x] move repo to appium-boneyard

**Comment by jlipps** [comment]
cc @sravanmedarapu we're trying to reduce the number of separate repos/packages we have to maintain. if there's not a compelling reason to have the installer be separate from the driver, let's combine them.

**Comment by sravanmedarapu** [comment]
@jlipps,  appium-uiautomator2-installer already [moved](https://github.com/appium/appium-uiautomator2-driver/blob/master/lib/installer.js) into appium-uiautomator2-driver.

**Comment by jlipps** [comment]
@sravanmedarapu can you run this from npm since i am not an owner of this package?

```
npm deprecate appium-uiautomator2-installer "This package is now a part of appium-uiautomator2-driver and should not be used directly"
```

Then we can close this

**Comment by sravanmedarapu** [comment]
Sure. I am also not the owner for this module. Will request @prakash.goulla from Imaginea to it on Monday.

**Comment by jlipps** [comment]
@sravanmedarapu can we ping prakash to deprecate this?

**Comment by sravanmedarapu** [comment]
@jlipps, appium-uiautomator2-installer deprecated now.

**Comment by jlipps** [comment]
👍  thank you!
