### ISSUE TITLE
dearchitect: appium-android-ime

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7477]
* [ ] move appium-android-ime code into appium-android-driver
* [ ] update imports in appium-android-driver
* [ ] ensure appium-android-ime tests/CI are now a part of appium-android-driver
* [ ] publish new appium-android-driver
* [ ] replace appium-android-ime README with deprecation notice/link
* [ ] deprecate appium-android-ime on NPM

**Comment by mykola-mokhnach** [comment]
This package has been merged to appium settings
