### ISSUE TITLE
dearchitect: appium-unlock

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7479]
* [ ] move appium-unlock code into appium-android-driver
* [ ] update imports in appium-android-driver
* [ ] ensure appium-unlock tests/CI are now a part of appium-android-driver
* [ ] publish new appium-android-driver
* [ ] replace appium-unlock README with deprecation notice/link
* [ ] deprecate appium-unlock on NPM

**Comment by mykola-mokhnach** [comment]
Appium unlock has been moved to appium settings
