### ISSUE TITLE
merge desired capabilities in getSession with what WDA returns

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7480]
When you call `GET /session/:id` on an XCUITest session, it proxies the request to WDA, which returns weird things. This breaks some client behavior (see appium/ruby_lib#390).

The solution is for us to merge our desired capabilities into what WDA sends back as a result of the proxy request, and give that to the client instead.

**Comment by danqa** [comment]
@jlipps Thanks for fixing! How can I get this fix? Do I need to wait for the next Appium release?

**Comment by jlipps** [comment]
@danqa since you're only experiencing the bug on Sauce, unfortunately you'll need to wait till (a) 1.6.3 is released, and (b) 1.6.3 is made available on sauce (usually within a day or two of the open source release)

**Comment by danqa** [comment]
Kinda what I thought you would say. Thanks again for the fix.
