### ISSUE TITLE
Encountering the Issue with Appium WebdriverAgent with real device when Running appium server from terminal with Xcode 8.2

### ISSUE THREAD

**Issue by avinaspandey** [appium/appium#7481]
## When running my script encountering undeclared identifier response.

[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Logs/Test/0A1C9CAE-F456-41E9-9C61-58DC836069B6/Session-WebDriverAgentRunner-2016-12-08_205930-Pyhm3r.log
[Xcode] 2016-12-08 20:59:31.190 xcodebuild[21877:365356] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Logs/Test/0A1C9CAE-F456-41E9-9C61-58DC836069B6/Session-WebDriverAgentRunner-2016-12-08_205930-Pyhm3r.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Logs/Test/0A1C9CAE-F456-41E9-9C61-58DC836069B6/Session-WebDriverAgentRunner-2016-12-08_205930-Pyhm3r.log}

[Xcode] 
Testing failed:

[Xcode] 	Use of undeclared identifier 'RouteResponse'
	Use of undeclared identifier 'response'
	Receiver type 'RoutingHTTPServer' for instance message is a forward declaration
	Use of undeclared identifier 'response'
	Use of undeclared identifier 'response'
** TEST FAILED **

The following build commands failed:
	CompileC DerivedData/WebDriverAgent/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBHTTPOverUSBServer.o WebDriverAgentLib/Routing/FBHTTPOverUSBServer.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] xcodebuild failure warrants retry. Retrying...
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down Logger process (pid 21882)
[XCUITest] System log exited with code '0'
[debug] [XCUITest] Removing WDA application from device

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1-beta
* Desktop OS/version used to run Appium: Xcode 8.2
* Node.js version (unless using Appium.app|exe): v7.2.0
* Mobile platform/version under test:10.1.1
* Real device or emulator/simulator: Real device (iPhone 6)
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Code To Reproduce Issue [ Good To Have ]

	  String apkpath="//Users//avinash//Documents//IOSIPK//MVP-QA-2.1-10.ipa";
	// TODO Auto-generated method stub
	  AppiumDriver<MobileElement> driver; 

	  DesiredCapabilities cap=new DesiredCapabilities();
	  File f= new File(apkpath);
	  cap.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
	  cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.1");
	  cap.setCapability(MobileCapabilityType.UDID,"XXXXXXXXXXXXX");
	  cap.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6"); 
	  cap.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
	  cap.setCapability("newCommandTimeout", "9000");
	  cap.setCapability(MobileCapabilityType.NO_RESET,"true");
	  cap.setCapability("sendKeyStrategy","setValue");
	  cap.setCapability("--no-reset", false);
	  cap.setCapability(MobileCapabilityType.APP,f.getAbsolutePath());
	  driver = new IOSDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), cap);
	  driver.manage().timeouts().implicitlyWait(600, TimeUnit.SECONDS);

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Run
 
```
bash Scripts/bootstrap.sh -d
```

from WDA root folder to retrieve Carthage dependencies first.

**Comment by jlipps** [comment]
@imurchie why wouldn't appium have gotten the carthage deps?

**Comment by imurchie** [comment]
It does not run the dependency retrieval unless there are no dependencies at all. It does not try to update them at the moment.

**Comment by jlipps** [comment]
ah ok. maybe we should do this on `npm install`?

**Comment by imurchie** [comment]
We could. I think that might bring in a host of problems with installing, though.

It would not be difficult to change it to always run the dependency management code (just changing the conditional [here](https://github.com/appium/appium-xcuitest-driver/blob/master/lib/webdriveragent.js#L127)). I'm not sure of the performance implications, though.

**Comment by jlipps** [comment]
hmm hmm. alternatively, `npm install` could just clear out the dir, to ensure new deps are retrieved after every install? that should be pretty straightforward, right?

**Comment by imurchie** [comment]
Yes, that could be an option. I feel like I've seen it update when it needs to, run manually. I can try some things out to experiment.

**Comment by avinaspandey** [comment]
When I tried the nom install in the appium directory encountered the below -

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.2.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3
npm ERR! path /Users/avinash/appium/node_modules/appium-xcuitest-driver
npm ERR! code EISGIT

npm ERR! git /Users/avinash/appium/node_modules/appium-xcuitest-driver: Appears to be a git repo or submodule.
npm ERR! git     /Users/avinash/appium/node_modules/appium-xcuitest-driver
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/avinash/appium/npm-debug.log

What should I do next

**Comment by avinaspandey** [comment]
Regarding, bash Scripts/bootstrap.sh -d => All dependencies fetched successful I think. 
WD build is successful.

**Comment by avinaspandey** [comment]
Hi imurchie,

Could you please help on this, I am really stuck to launch the app on the iOS phone 6

[Xcode] 2016-12-13 16:21:19.474 xcodebuild[1822:34111] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Logs/Test/CB6FDE4C-7465-4380-A567-CF112234DF52/Session-WebDriverAgentRunner-2016-12-13_162119-OSCaZT.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/DerivedData/WebDriverAgent/Logs/Test/CB6FDE4C-7465-4380-A567-CF112234DF52/Session-WebDriverAgentRunner-2016-12-13_162119-OSCaZT.log}

[Xcode] 
Testing failed:
	Use of undeclared identifier 'RouteResponse'
	Use of undeclared identifier 'response'

[Xcode] 	Receiver type 'RoutingHTTPServer' for instance message is a forward declaration
	Use of undeclared identifier 'response'
	Use of undeclared identifier 'response'
** TEST FAILED **


The following build commands failed:
	CompileC DerivedData/WebDriverAgent/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBHTTPOverUSBServer.o WebDriverAgentLib/Routing/FBHTTPOverUSBServer.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] xcodebuild failure warrants retry. Retrying...
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down Logger process (pid 1827)
[XCUITest] System log exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes


The following build commands failed:
	CompileC DerivedData/WebDriverAgent/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBHTTPOverUSBServer.o WebDriverAgentLib/Routing/FBHTTPOverUSBServer.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] xcodebuild failure warrants retry. Retrying...
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down Logger process (pid 1827)
[XCUITest] System log exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes

**Comment by imurchie** [comment]
Appium 1.6.4-beta has been released (to upgrade, run `npm uninstall -g appium && npm install -g appium@beta`). How we connect to devices has been significantly changed, and should be more reliable. Please try it out.

There is some documentation here: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

I am closing this issue since the details will have changed completely. If you still have problems, please see if there is a similar issue, or else create a new issue with as much information as possible. We are committed to tracking down these elusive problems!
