### ISSUE TITLE
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1 (WARNING: The server did not provide any stacktrace information)

### ISSUE THREAD

**Issue by GopalakrishnaNagam** [appium/appium#7483]
## The problem

When I am trying to run my script ,below is the error in the logs
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1 (WARNING: The server did not provide any stacktrace information) 

## Environment

* Appium version : 1.6.2 (installed through terminal)
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13 (Draco)
* Desktop OS/version used to run Appium: Mac OS - OS X EI Capitan Version : 10.11.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPad Air iOS 10.1
* Real device or emulator/simulator: Simulator 

## Details
Xcode Version 8.1
Started appium (1.6.2) through Terminal
Ran the script , then I am getting  the below error in the error logs
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1 (WARNING: The server did not provide any stacktrace information)

**Comment by mykola-mokhnach** [comment]
There is a nice feature called "Search" . Don't hesitate to use it before posting new issues.

**Comment by jlipps** [comment]
If you think there's a bug here, you need to include your full appium log

**Comment by pavanbachu0604** [comment]
@GopalakrishnaNagam : /bin/bash Scripts/bootstrap.sh -d 
This cmd helps to install all the dependencies needed for appium, if you are using in ur office network I would recommend you to switch to public network once that would help in installing dependencies
