### ISSUE TITLE
unable to launch  appium inspector

### ISSUE THREAD

**Issue by rkn411** [appium/appium#7484]
#unable to launch appium inspector for locating paths in mac for android application 
## Environment

* Appium version (or git revision) that exhibits the issue:1.6
* Last Appium version that did not exhibit the issue (if applicable):1.4
* Desktop OS/version used to run Appium:ios10.12.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:6.0
* Real device or emulator/simulator:realdevice
* Appium CLI or Appium.app|exe:

## Details

i tried to automate android application on mac machine and i want to locate elements rather than using UIautomator viewer by appium inspector .
 i am unable to launch the inspector window as like for iOS apps 

1.selected pre-launch and verified

**Comment by jlipps** [comment]
The old inspector is no longer supported. We're working on a new one.

**Comment by abduzar** [comment]
@jlipps just curious, when it will be available

**Comment by jlipps** [comment]
"soon". If you want to run from source, it's available now at https://github.com/appium/appium-desktop.
