### ISSUE TITLE
Cannot switch to webview context with appium 1.6.2 in a hybrid Android 7.0 application

### ISSUE THREAD

**Issue by davidrova** [appium/appium#7487]
## The problem

Since I have upgrade my project to 1.6.x (I am trying 1.6.2 now) I cannot switch to webview context.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.2
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: MAC Book Pro
* Node.js version (unless using Appium.app|exe): 6.2.2+
* Mobile platform/version under test: Android 7.0 API Level 24
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: npm appium

* Chrome: Upgraded to 54

## Details

Since I have upgraded Appium version I cannot switch to webview context. 

The context exists, the command is called but an exception is thrown.

I have upgrade Chrome version to 54.x. The log says you must have at lest version 53.x.

## Link to Appium logs

https://gist.github.com/davidrova/833d09670682391fee592d571a08517e

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/davidrova/91a617705479499f0eddaacb20733d9c

**Comment by mykola-mokhnach** [comment]
Updating Chrome itself won't help. You need to update Android System WebView component.

**Comment by davidrova** [comment]
I have update Android System WebView but still opens a Webview Browser 51.

I have installed an Android emulator 7.1 (api level 25) and works with WebView 52.

How can you update WebView browser in an emulator?

**Comment by davidrova** [comment]
Downloading chromedriver to 2.20 resolves the issue.

I have seen it in [issue-7138](https://github.com/appium/appium/issues/7138).

Regards
