### ISSUE TITLE
Send_keys = "No keyboard found" for Appium 1.6.2 and iOS 10 Simulator

### ISSUE THREAD

**Issue by ericzered** [appium/appium#7488]
Hello,
I have a problem with the send_keys function and Simulator iOS 10.
I have an app I want to test. Purpose is to fill the field in the pop up.
It looks like this : http://img4.hostingpics.net/pics/367739ios10.png

With Appium 1.6.1 and iOS 10.0 Simulator, I have no problem
With Appium 1.6.1 and iOS 10.1 Simulator, I have the "No keyboard found" error

But what is strange is that with Appium 1.6.2 is that I've got the "No Keyboard found" on both iOS 10.0 and 10.1.
I didn't change a thing, just update Appium to make the test. And on each case, I can see the keyboard displayed.
I've tried with and without the "Connect Hardware Keyboard" option.

my test code (in ruby)
find_element(:xpath, "//*/XCUIElementTypeTextField[1]").send_keys "11111"

So why the only combinaison which work is Appium 1.6.1 and iOS 10.0 ?
Thanks !

The appium logs:

**When the test is OK:**
Appium 1.6.1
iOS 10.0

[HTTP] --> POST /wd/hub/session/0671ddc8-249f-492d-a868-d53ef3ecc7f5/element/1B31023C-85EF-4033-88FB-C03E526A9B61/value {"value":["2232"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["2232"],"1B31023C-85EF-4033-88FB-C03E526A9B61","0671ddc8-249f-492d-a868-d53ef3ecc7f5"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [JSONWP Proxy] Proxying [GET /element/1B31023C-85EF-4033-88FB-C03E526A9B61/attribute/type] to [GET http://localhost:8100/session/04377DAE-C350-497A-960C-59E19A586D84/element/1B31023C-85EF-4033-88FB-C03E526A9B61/attribute/type] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypeCell\",\n  \"sessionId\" : \"04377DAE-C350-497A-960C-59E19A586D84\",\n  \"status\" : 0\n}"
[debug] [JSONWP Proxy] Proxying [POST /element/1B31023C-85EF-4033-88FB-C03E526A9B61/value] to [POST http://localhost:8100/session/04377DAE-C350-497A-960C-59E19A586D84/element/1B31023C-85EF-4033-88FB-C03E526A9B61/value] with body: {"value":["2","2","3","2"]}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"1B31023C-85EF-4033-88FB-C03E526A9B61","value":"","sessionId":"04377DAE-C350-497A-960C-59E19A586D84"}
[debug] [MJSONWP] Responding to client with driver.setValue() result: null
[HTTP] <-- POST /wd/hub/session/0671ddc8-249f-492d-a868-d53ef3ecc7f5/element/1B31023C-85EF-4033-88FB-C03E526A9B61/value 200 2155 ms - 76

**When the tests failed:** 
Appium 1.6.1
iOS 10.1

[HTTP] --> POST /wd/hub/session/a8917fdd-a541-48b5-baf4-0f897352c4a0/element/DA4F9DB9-B12D-4877-9400-26EEA0400820/value {"value":["2232"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["2232"],"DA4F9DB9-B12D-4877-9400-26EEA0400820","a8917fdd-a541-48b5-baf4-0f897352c4a0"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [JSONWP Proxy] Proxying [GET /element/DA4F9DB9-B12D-4877-9400-26EEA0400820/attribute/type] to [GET http://localhost:8100/session/43A670C2-33EF-45C9-B38D-789190FE69C9/element/DA4F9DB9-B12D-4877-9400-26EEA0400820/attribute/type] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypeTextField\",\n  \"sessionId\" : \"43A670C2-33EF-45C9-B38D-789190FE69C9\",\n  \"status\" : 0\n}"
[debug] [BaseDriver] Set implicit wait to 0ms
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/43A670C2-33EF-45C9-B38D-789190FE69C9/element] with body: {"using":"class name","value":"XCUIElementTypeKeyboard"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Alert is obstructing view","sessionId":"43A670C2-33EF-45C9-B38D-789190FE69C9","status":26}
[debug] [XCUITest] No keyboard found. Clicking element to open it.
[debug] [JSONWP Proxy] Proxying [POST /element/DA4F9DB9-B12D-4877-9400-26EEA0400820/click] to [POST http://localhost:8100/session/43A670C2-33EF-45C9-B38D-789190FE69C9/element/DA4F9DB9-B12D-4877-9400-26EEA0400820/click] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"DA4F9DB9-B12D-4877-9400-26EEA0400820","value":"","sessionId":"43A670C2-33EF-45C9-B38D-789190FE69C9"}

Appium 1.6.2
iOS 10.0

[HTTP] --> POST /wd/hub/session/5ebd651f-8c83-4724-9ae6-c1d54b872867/element/E2C327BF-34F9-424C-BBE7-1C62A0F798E6/value {"value":["2232"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["2232"],"E2C327BF-34F9-424C-BBE7-1C62A0F798E6","5ebd651f-8c83-4724-9ae6-c1d54b872867"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [JSONWP Proxy] Proxying [GET /element/E2C327BF-34F9-424C-BBE7-1C62A0F798E6/attribute/type] to [GET http://localhost:8100/session/DB6C6675-4DD1-4F97-B830-C5AC1BFAADD6/element/E2C327BF-34F9-424C-BBE7-1C62A0F798E6/attribute/type] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypeTextField\",\n  \"sessionId\" : \"DB6C6675-4DD1-4F97-B830-C5AC1BFAADD6\",\n  \"status\" : 0\n}"
[debug] [BaseDriver] Set implicit wait to 0ms
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/DB6C6675-4DD1-4F97-B830-C5AC1BFAADD6/element] with body: {"using":"class name","value":"XCUIElementTypeKeyboard"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Alert is obstructing view","sessionId":"DB6C6675-4DD1-4F97-B830-C5AC1BFAADD6","status":26}
[debug] [XCUITest] No keyboard found. Clicking element to open it.
[debug] [JSONWP Proxy] Proxying [POST /element/E2C327BF-34F9-424C-BBE7-1C62A0F798E6/click] to [POST http://localhost:8100/session/DB6C6675-4DD1-4F97-B830-C5AC1BFAADD6/element/E2C327BF-34F9-424C-BBE7-1C62A0F798E6/click] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"E2C327BF-34F9-424C-BBE7-1C62A0F798E6","value":"","sessionId":"DB6C6675-4DD1-4F97-B830-C5AC1BFAADD6"}

**Comment by mykola-mokhnach** [comment]
Known WDA bug https://github.com/facebook/WebDriverAgent/issues/384

@triager please close
