### ISSUE TITLE
allow designating autocorrect behavior for ios simulator runs

### ISSUE THREAD

**Issue by michalkaftanski-airhelp** [appium/appium#7489]
## The problem

Actual result:
The problem is that regular sendKeys (for every sendKeysStrategy) after clearing and typing a value to the specified element, at the end accepts auto-correct value. This is also when setValue for MobileElement is used. [Example screenshot](https://postimg.org/image/kd0g0tcbf/4af07250/).

Expected result:
Is not to use at the auto-correct value. Or at least use some property to disable it. Unfortunately this happens also on iOS simulator where auto-correction property can't be set and saved for next runs.

## Environment

* Appium version: 1.6.1
* Desktop OS/version used to run Appium: 10.12.1 MacOs
* Node.js version (unless using Appium.app|exe): 7.1.0
* Mobile platform/version under test: iOS 10.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium nodejs server

## Code To Reproduce Issue

Either:
```
	public void setValue(String id, String value) {
		WebElement we = driver.findElementByAccessibilityId(id);
		MobileElement me = (MobileElement) we;
		me.setValue(value);
	}
```
or:
```
	public void sendKeys(String id, String keys) {
		driver.findElementByAccessibilityId(id).sendKeys(keys);
	}
```
for any XCUIElementTypeTextField which has auto-correction enabled.

**Comment by mykola-mokhnach** [comment]
I think this cannot be avoided using XCTest instruments only. In our app we've just added a special command line flag, which disables autocorrection for all input fields and we use this flag for automated tests.

**Comment by michalkaftanski-airhelp** [comment]
I've just talked with devs and they're not happy for such a resolution. I spent days in looking for some workaround:
- using alternative setValue from MobileElement as suggested on some past articles: doesn't help
- permanent disable on iOS simulator auto-correction as for the default value: resolution not found

**Comment by mykola-mokhnach** [comment]
Let me know if you find better solution then ;)

**Comment by jlipps** [comment]
There's probably a way to update some settings plist before sim launch to have the sim start with autocorrect off. There's no way to do this on a real device though AFAIK. I'll treat this as a feature request and update the title accordingly.

**Comment by michalkaftanski-airhelp** [comment]
Thanks for converting issue for enhancement.

Anyway, I've tried to change it on _com.apple.Preferences.plist_ within my unique simulator at _~/Library/Developer/CoreSimulator/Devices/<Unique Simulator ID>/data/Library/Preferences_, but still not working. Even properties found, but they're already disabled:
`<key>HWKeyboardAutocorrection</key>
        <false/>
        <key>HWKeyboardPeriodShortcut</key>
        <false/>
        <key>HardwareKeyboardLastSeen</key>
        <true/>
        <key>KeyboardAllowPaddle</key>
        <false/>
        <key>KeyboardAutocapitalization</key>
        <false/>
        <key>KeyboardAutocorrection</key>
        <false/>
`

**Comment by jlipps** [comment]
Hmm. OK, well we'll do what we can to see if that approach will work. Hopefully we'll figure something out.

**Comment by mykola-mokhnach** [comment]
For now there is no way to change autocorrection settings from the "outside" of iOS Simulator application. All questions to Apple.
