### ISSUE TITLE
Appium 1.6.2 WDA doesn't launch the app

### ISSUE THREAD

**Issue by gopi09m** [appium/appium#7490]
## The problem

[debug] [WebDriverAgent] Device: Dec  9 10:41:09 MyDevice XCTRunner[873] <Notice>: Continuing to run tests in the background with task ID 1

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.2
* Desktop OS/version used to run Appium: Mac 0s 10.12
* Node.js version (unless using Appium.app|exe): latest
* Mobile platform/version under test: iPad 10.1.1
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: NA

## Details

ast login: Fri Dec  9 10:31:15 on ttys000
ubmac:~ automation$ appium
[Appium] Welcome to Appium v1.6.2
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"app":"/Users/automation/Downloads/UbSeleniumAutomation/TestCasesData/Customer_QA-3.0.0-40.ipa","proxy":true,"newCommandTimeout":20000,"realDeviceLogger":"/Users/automation/node_modules/deviceconsole/deviceconsole","appiumVersion":"1.6","platformVersion":"10.1","xcodeConfigFile":"/Users/automation/Documents/xcodeConfigfile.xcconfig","udid":"39b20ed2606f6f3cf95e767f240d15f1595678f3","platformName":"iOS","deviceName":"MyDevice"},"requiredCapabilities":{}},"desiredCapabilities":{"app":"/Users/automation/Downloads/UbSeleniumAutomation/TestCasesData/Customer_QA-3.0.0-40.ipa","proxy":true,"newCommandTimeout":20000,"realDeviceLogger":"/Users/automation/node_modules/deviceconsole/deviceconsole","appiumVersion":"1.6","platformVersion":"10.1","xcodeConfigFile":"/Users/automation/Documents/xcodeConfigfile.xcconfig","udid":"39b20ed2606f6f3cf95e767f240d15f1595678f3","platformName":"iOS","deviceName":"MyDevice"},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/automation/Downloads/UbSeleniumAutomation/TestCasesData/Customer_QA-3.0.0-40.ipa","proxy":true,"newCommandTimeout":20000,"realDeviceLogger":"/Users/automation/node_modules/deviceconsole/deviceconsole","appiumVersion":"1.6","platformVersion":"10.1","xcodeConfigFile":"/Users/automation/Documents/xcodeConfigfile.xcconfig","udid":"39b20ed2606f6f3cf95e767f240d15f1595678f3","platformName":"iOS","deviceName":"MyDevice"},{},{"desiredCapabilities":{"app":"/Users/automation/Downloads/UbSeleniumAutomation/TestCasesData/Customer_QA-3.0.0-40.ipa","proxy":true,"newCommandTimeout":20000,"realDeviceLogger":"/Users/automation/node_modules/deviceconsole/deviceconsole","appiumVersion":"1.6","platformVersion":"10.1","xcodeConfigFile":"/Users/automation/Documents/xcodeConfigfile.xcconfig","udid":"39b20ed2606f6f3cf95e767f240d15f1595678f3","platformName":"iOS","deviceName":"MyDevice"},"requiredCapabilities":{}},null,null]
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/automation/Downloads/UbSeleniumAutomation/TestCasesData/Customer_QA-3.0.0-40.ipa'
[Appium]   proxy: true
[Appium]   newCommandTimeout: 20000
[Appium]   realDeviceLogger: '/Users/automation/node_modules/deviceconsole/deviceconsole'
[Appium]   appiumVersion: '1.6'
[Appium]   platformVersion: '10.1'
[Appium]   xcodeConfigFile: '/Users/automation/Documents/xcodeConfigfile.xcconfig'
[Appium]   udid: '39b20ed2606f6f3cf95e767f240d15f1595678f3'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'MyDevice'
[debug] [XCUITest] XCUITestDriver version: 2.3.0
[BaseDriver] The following capabilities were provided, but are not recognized by appium: proxy, appiumVersion.
[BaseDriver] Session created with session id: 774a8982-fe24-4588-ad75-dddeedfddb86
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [XCUITest] Available devices: 39b20ed2606f6f3cf95e767f240d15f1595678f3
[debug] [XCUITest] Creating iDevice object with udid 39b20ed2606f6f3cf95e767f240d15f1595678f3
[XCUITest] Determining device to run tests on: udid: '39b20ed2606f6f3cf95e767f240d15f1595678f3', real device: true
[BaseDriver] Using local app '/Users/automation/Downloads/UbSeleniumAutomation/TestCasesData/Customer_QA-3.0.0-40.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/7k/0hdprxfd16q71myzp0htb43r0000gn/T/2016119-6324-m9fmsu.21nqvbzkt9/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/7k/0hdprxfd16q71myzp0htb43r0000gn/T/2016119-6324-m9fmsu.21nqvbzkt9/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/7k/0hdprxfd16q71myzp0htb43r0000gn/T/2016119-6324-m9fmsu.21nqvbzkt9/Payload/Customer.app'
[debug] [XCUITest] Checking whether app '/var/folders/7k/0hdprxfd16q71myzp0htb43r0000gn/T/2016119-6324-m9fmsu.21nqvbzkt9/Payload/Customer.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/var/folders/7k/0hdprxfd16q71myzp0htb43r0000gn/T/2016119-6324-m9fmsu.21nqvbzkt9/Payload/Customer.app': 'com.tds.universal.customer'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/Users/automation/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Using Xcode configuration file: '/Users/automation/Documents/xcodeConfigfile.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=39b20ed2606f6f3cf95e767f240d15f1595678f3 -configuration Debug -xcconfig /Users/automation/Documents/xcodeConfigfile.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/automation/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/862376DD-49E1-41C4-BC0F-2322F7765EF2/Session-WebDriverAgentRunner-2016-12-09_103555-qAXc2E.log
[debug] [WebDriverAgent] Device: Dec  9 10:36:01 MyDevice XCTRunner[865] <Notice>: Running tests...
[debug] [WebDriverAgent] Device: Dec  9 10:36:02 MyDevice XCTRunner[865] <Notice>: Continuing to run tests in the background with task ID 1

**Comment by mykola-mokhnach** [comment]
Known issue. Sync the time on the device under test with you local machine time and wait for Appium update 1.6.3
@triager please close

**Comment by gopi09m** [comment]
The time on my mac and iPad are in sync. They show the same time. Is it something else i need to update ?

**Comment by mykola-mokhnach** [comment]
@gopi09m Then downgrade to 1.6.1 for now as temporary solution

**Comment by gopi09m** [comment]
Thanks it worked again after i rollback
