### ISSUE TITLE
xpath and tap doesn't work consistently with Appium 1.6.1

### ISSUE THREAD

**Issue by gopi09m** [appium/appium#7491]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.0
* Desktop OS/version used to run Appium: Mac Sierra
* Node.js version (unless using Appium.app|exe): latest 
* Mobile platform/version under test: iPad Air
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

Xpath and tap doesn't work consistently with Appium 1.6.1.

To set text on a text field i execute below code:
xpath  we are using for an element:
//XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther[2]/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther[6]/XCUIElementTypeTextField

MobileElement mobileElement = iosDriver.findElement(By.xpath("..."));
mobileElement.tap(1, 500);
mobileElement.sendKeys(text value);

To select an item in dropdown look alike in iOS app we use below approach which is again not working consistently.
mobileElement.tap(1, 500); //taps on the textfield of the dropdown look alike in iOS app and waits for the options to show up
mobileElement.findelement(..find element by text..).click

Sometimes it doesn't recognize the object by xpath and sometimes it does. Whenever it does, it sometimes work and some other time it doesn't set the text.

I get org.openqa.selenium.NoSuchElementException whenever it doesn't work.

**Comment by jlipps** [comment]
Are you sure the element always exists? The only way to be sure is to print the XML source immediately before trying to find the element, then manually ensuring your xpath query would find an element.

Xpath is definitely not recommended as an element finding strategy. Is there some reason you are using it instead of another strategy?

**Comment by gopi09m** [comment]
I have something like this:

 <XCUIElementTypeTextField name="" label="" value="Address" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0/0/0/0/0/1/0/0/0/1" x="211" y="511" width="677" height="20">

It some times recognizes and enters text. sometimes it doesn't find it. sometimes it finds it but enters the text in a different text field .

Do we need to give it the location as well ?

**Comment by jlipps** [comment]
Again, the only way to be sure you're targeting the right element with a very messy xpath query like that is to print out the source immediately before finding the element, and tracing the xpath query out by hand to ensure you have the right element. closing this for now unless you can prove that the query is always targeting the correct element

**Comment by AnuvrathElastica** [comment]
Am seeing this same issue intermittently.. Please find the attached xml file and the xpath am using is:  **//XCUIElementTypeTextField[@name='Email or phone']**
Appium version: 1.6.6-beta.2
[xml.txt](https://github.com/appium/appium/files/1132484/xml.txt)
