### ISSUE TITLE
Value Attribute in XCUITest & UIA Differs  

### ISSUE THREAD

**Issue by dilsreccse** [appium/appium#7492]
## The problem
Unable to check whether the value is selected or not using XCUITest. 
When the element is selected, its value is 1 in UIA but now in XCUITest the value is null.   

When i used Appium iOS inspector, for the corresponding element i'm not getting the value attribute.
Device : iPad 10.x / Appium 1.6.1 
-------------------------------------------------------------------------------------------------------------------
Type: XCUIElementTypeCell
Accessibility Id:
Value:
Label:
Is Visible: true
Rect: x=694, y=195, h=44, w=320
Absolute XPath:
/AppiumAUT/XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther[2]/XCUIElementTypeOther[3]/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell
-------------------------------------------------------------------------------------------------------------------

When i used Appium inspector, for the same element i'm getting the value 
Device : iPad 8.x / Appium 1.4.3
-------------------------------------------------------------------------------------------------------------------
name: All Content Types
type: UIATableCell
value: 1
label: 
enabled: true
visible: false
valid: true
location: {694, 195}
size: {320, 44}
xpath: //UIAApplication[1]/UIAWindow[1]/UIAPopover[1]/UIATableView[1]/UIATableCell[1]
-------------------------------------------------------------------------------------------------------------------

Kindly help me with a workaround to check whether the element is selected or not.

**Comment by jlipps** [comment]
These versions of appium are not compatible. If you want to use the inspector these days you'll need to find instructions online for making it work with appium 1.6.x. We're in the process of building a new inspector that the appium team maintains, so that will be better going forward.

**Comment by dilsreccse** [comment]
Hi @jipps: when will the new inspector that the appium team uses will be released to us ??

**Comment by jlipps** [comment]
There is no official ETA. Probably a few weeks.

**Comment by dilsreccse** [comment]
Hi @jlipps is there any update on the ETA for new inspector that the appium team uses to us ?

**Comment by dilsreccse** [comment]
@imurchie & @mykola-mokhnach  do you know any the background details why this issue is happening, what my developer needs to change to adopt these changes.. Kindly share your views on this

**Comment by mykola-mokhnach** [comment]
I don't know. You should, probably, reach Apple developer)s_, who were working on both these frameworks (UIAutomation and XCTest) and ask them to know for sure.

**Comment by dilsreccse** [comment]
thank you @mykola-mokhnach , Reported in [Apple forum](https://forums.developer.apple.com/message/220407#220407) , Will update here if there is any  updates
