### ISSUE TITLE
dearchitect: ios-app-utils

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7495]
* [x] move ios-app-utils code into appium-ios-driver
* [x] ensure ios-app-utils tests/CI are now a part of appium--ios-driver
* [x] publish new appium--ios-driver
* [x] update imports in appium-xcuitest-driver
* [x] replace ios-app-utils README with deprecation notice
* [x] deprecate ios-app-utils on NPM
* [x] move ios-app-utils to appium-boneyard org

**Comment by jlipps** [comment]
@imurchie so we decided to put them into ios-driver instead of appium-xcode? I'm ok with that, but we probably want to update the acceptance criteria here

**Comment by imurchie** [comment]
Yes, they are never used below the driver level, so it makes more sense to keep the functions there. I'll update.
