### ISSUE TITLE
Possible optimization for getting page source

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7499]
@midopa commented on [Thu Jun 23 2016](https://github.com/appium/appium-android-bootstrap/issues/26)

I was looking through this code today and noticed that whenever I send a command to [get the page source](https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/io/appium/android/bootstrap/handler/Source.java#L38), bootstrap will:
1. [Dump the UI XML into a on-device temp file](https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/io/appium/android/bootstrap/utils/XMLHierarchy.java#L126)
2. [Read it back into a string](https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/io/appium/android/bootstrap/utils/XMLHierarchy.java#L128)
3. [Do some cleanup on the string](https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/io/appium/android/bootstrap/utils/XMLHierarchy.java#L156)
4. [... and then pass it back in a JSON response](https://github.com/appium/appium-android-bootstrap/blob/master/bootstrap/src/io/appium/android/bootstrap/handler/Source.java#L40)

And this is all done on-device in bootstrap.

Can't the XML be passed back as a string and skip to step 3?

---

@midopa commented on [Thu Jun 23 2016](https://github.com/appium/appium-android-bootstrap/issues/26#issuecomment-228268095)

I tested the change on my phone (6.0 with high speed SD card) and there's very little difference.

Instead of writing to a file, the code returns a string.

From 500 runs, 99th percentile was ~0.3s for both the current implementation and the String implementation.

Also, not sure how fair this test is, given there must be tons of other stuff running on my phone that can add noise to the timing measurements. And maybe the tests would be different if there's a low speed SD card on the phone.

If you're curious, here's what the code change was:
https://github.com/midopa/appium-android-bootstrap/commit/92745190fccc4ce499442d4b3abb21526e3151e1

**Comment by dpgraham** [comment]
Since there's no difference in performance I'm going to close this.

**Comment by jlipps** [comment]
Thanks for the investigation anyway, @midopa!
