### ISSUE TITLE
UiScrollableParser.coerceArgToType lacks support for type double

### ISSUE THREAD

**Issue by rkavalap** [appium/appium#7502]
@tcnh commented on [Thu Oct 20 2016](https://github.com/appium/appium-android-bootstrap/issues/32)

We're trying to use setSwipeDeadZonePercentage(double percentage) to be able to use a partially obscured UiScrollView. 

This method takes a double between 0 and 1 as its argument. When passing i.e. 0.2, AndroidBootstrap logs:

```
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiScrollable coerce type: double arg: 0.2
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":9,"value":"Could not parse UiSelector argument: Could not coerce 0.2 to any sort of Type"}
```

Doc: https://developer.android.com/reference/android/support/test/uiautomator/UiScrollable.html#setSwipeDeadZonePercentage(double)

**Comment by dpgraham** [comment]
Looks like this is fixed by https://github.com/appium/appium-android-bootstrap/pull/33
