### ISSUE TITLE
[XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability.

### ISSUE THREAD

**Issue by rockyav** [appium/appium#7503]
## The problem

An issue occurred when run automation:
"[XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability. "

## Environment

* Appium version : 1.6.2
* Desktop OS/version used to run Appium: Mac Sierra 10.12.1
* Node.js version (unless using Appium.app|exe): v7.0.0
* Mobile platform/version under test: iphone 6, OS 9.3
* Real device 

## Logs

vunguyens-Mac-mini:~ vunguyen$ appium -U 8bda5aa970d8f5291d6c1032b39a514d01b9997d -p 4843 --session-override --automation-name XCUITest
[Appium] Welcome to Appium v1.6.2
[Appium] Non-default server args:
[Appium]   port: 4843
[Appium]   sessionOverride: true
[Appium]   automationName: 'XCUITest'
[Appium]   udid: '8bda5aa970d8f5291d6c1032b39a514d01b9997d'
[Appium] Deprecated server args:
[Appium]   --automation-name => --default-capabilities '{"automationName":"XCUITest"}'
[Appium]   -U,--udid => --default-capabilities '{"udid":"8bda5aa970d8f5291d6c1032b39a514d01b9997d"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   automationName: 'XCUITest'
[Appium]   udid: '8bda5aa970d8f5291d6c1032b39a514d01b9997d'
[Appium] Appium REST http interface listener started on 0.0.0.0:4843
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"com.itsoninc.liteclient.ref","appPackage":"com.itsoninc.liteclient.ref","appActivity":"none","newCommandTimeout":"130","platformVersion":"10.1","platformName":"iOS","deviceName":"iOS"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"com.itsoninc.liteclient.ref","appPackage":"com.itsoninc.liteclient.ref","appActivity":"none","newCommandTimeout":"130","platformVersion":"10.1","platformName":"iOS","deviceName":"iOS"},null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: 'com.itsoninc.liteclient.ref'
[Appium]   appPackage: 'com.itsoninc.liteclient.ref'
[Appium]   appActivity: 'none'
[Appium]   newCommandTimeout: '130'
[Appium]   platformVersion: '10.1'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iOS'
[Appium]   automationName: 'XCUITest'
[Appium]   udid: '8bda5aa970d8f5291d6c1032b39a514d01b9997d'
[debug] [XCUITest] XCUITestDriver version: 2.3.0
[BaseDriver] Capability 'newCommandTimeout' changed from string ('130') to integer (130). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: appPackage, appActivity.
[BaseDriver] Session created with session id: 664a3dd1-6793-4dd7-b643-fef6f92738c3
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [XCUITest] Available devices: 8bda5aa970d8f5291d6c1032b39a514d01b9997d
[debug] [XCUITest] Creating iDevice object with udid 8bda5aa970d8f5291d6c1032b39a514d01b9997d
[XCUITest] Determining device to run tests on: udid: '8bda5aa970d8f5291d6c1032b39a514d01b9997d', real device: true
[debug] [XCUITest] App is an iOS bundle, will attempt to run as pre-existing
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/Users/vunguyen/.node/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/vunguyen/.node/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /Users/vunguyen/.node/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=8bda5aa970d8f5291d6c1032b39a514d01b9997d -configuration Debug' in directory '/Users/vunguyen/.node/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/vunguyen/Library/Developer/Xcode/DerivedData/WebDriverAgent-cmbplewikcuscuaashrwxgatyeng/Logs/Test/11C920F1-AB49-4D20-A138-43BF678610FE/Session-WebDriverAgentRunner-2016-12-11_193420-3K9bjK.log
[XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability.
[Xcode] 2016-12-11 19:34:21.193 xcodebuild[5395:43022] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/vunguyen/Library/Developer/Xcode/DerivedData/WebDriverAgent-cmbplewikcuscuaashrwxgatyeng/Logs/Test/11C920F1-AB49-4D20-A138-43BF678610FE/Session-WebDriverAgentRunner-2016-12-11_193420-3K9bjK.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/vunguyen/Library/Developer/Xcode/DerivedData/WebDriverAgent-cmbplewikcuscuaashrwxgatyeng/Logs/Test/11C920F1-AB49-4D20-A138-43BF678610FE/Session-WebDriverAgentRunner-2016-12-11_193420-3K9bjK.log}

[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'

[Xcode] 

[Xcode] 
Testing failed:

[Xcode] 	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'
** TEST FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] xcodebuild failure warrants retry. Retrying...
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down Logger process (pid 5402)
[XCUITest] System log exited with code '0'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /Users/vunguyen/.node/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=8bda5aa970d8f5291d6c1032b39a514d01b9997d -configuration Debug' in directory '/Users/vunguyen/.node/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/vunguyen/Library/Developer/Xcode/DerivedData/WebDriverAgent-cmbplewikcuscuaashrwxgatyeng/Logs/Test/212844C6-C1D4-4967-A66F-F92913264225/Session-WebDriverAgentRunner-2016-12-11_193423-Ua9Sz9.log
[XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability.
[Xcode] 2016-12-11 19:34:23.634 xcodebuild[5435:43245] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/vunguyen/Library/Developer/Xcode/DerivedData/WebDriverAgent-cmbplewikcuscuaashrwxgatyeng/Logs/Test/212844C6-C1D4-4967-A66F-F92913264225/Session-WebDriverAgentRunner-2016-12-11_193423-Ua9Sz9.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/vunguyen/Library/Developer/Xcode/DerivedData/WebDriverAgent-cmbplewikcuscuaashrwxgatyeng/Logs/Test/212844C6-C1D4-4967-A66F-F92913264225/Session-WebDriverAgentRunner-2016-12-11_193423-Ua9Sz9.log}

[Xcode] 
Testing failed:
	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.

[Xcode] 	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'
** TEST FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:332:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:332:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down Logger process (pid 5442)
[XCUITest] System log exited with code '0'
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
(node:5353) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Can't stop process; it's not currently running
(node:5353) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:332:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[HTTP] <-- POST /wd/hub/session 500 5667 ms - 167

**Comment by mykola-mokhnach** [comment]
Are you sure you've applied all the configuration steps for real devices described in https://github.com/appium/appium-xcuitest-driver ?

**Comment by rockyav** [comment]
Thanks, it's resolved my issue.

**Comment by huhutouch** [comment]
hi,I have encountered the same problem, I would like to ask you how to solve the final it

**Comment by rockyav** [comment]
@huhutouch  Can i have your logs ?

**Comment by huhutouch** [comment]
testdeiMac:~ test$ appium -a 172.27.34.27 -p 4727
[Appium] Welcome to Appium v1.6.1
[Appium] Non-default server args:
[Appium]   address: '172.27.34.27'
[Appium]   port: 4727
[Appium] Appium REST http interface listener started on 172.27.34.27:4727
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","bundleId":"sg.bigo.live","udid":"00e3eb9b9d0acf3efcb1aee31c13927edaf97bc6","platformName":"iOS","deviceName":"iPhone 6s Plus","newCommandTimeout":"180*60"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","bundleId":"sg.bigo.live","udid":"00e3eb9b9d0acf3efcb1aee31c13927edaf97bc6","platformName":"iOS","deviceName":"iPhone 6s Plus","newCommandTimeout":"180*60"},null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'sg.bigo.live'
[Appium]   udid: '00e3eb9b9d0acf3efcb1aee31c13927edaf97bc6'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6s Plus'
[Appium]   newCommandTimeout: '180*60'
[debug] [XCUITest] XCUITestDriver version: 2.2.0
[BaseDriver] Capability 'newCommandTimeout' changed from string ('180*60') to integer (180). This may cause unexpected behavior
[BaseDriver] Session created with session id: fb82cf2f-c59a-4c08-96fb-9c190846cb3f
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: 00e3eb9b9d0acf3efcb1aee31c13927edaf97bc6
[debug] [XCUITest] Creating iDevice object with udid 00e3eb9b9d0acf3efcb1aee31c13927edaf97bc6
[XCUITest] Determining device to run tests on: udid: '00e3eb9b9d0acf3efcb1aee31c13927edaf97bc6', real device: true
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=00e3eb9b9d0acf3efcb1aee31c13927edaf97bc6 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability.
[debug] [XCUITest] Log file for xcodebuild test: /Users/test/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/816B8D39-D177-4B78-A162-A2911BEE1036/Session-WebDriverAgentRunner-2017-01-10_162648-C6flxG.log
[Xcode] 2017-01-10 16:26:53.212 xcodebuild[40016:6349176] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/test/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/816B8D39-D177-4B78-A162-A2911BEE1036/Session-WebDriverAgentRunner-2017-01-10_162648-C6flxG.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/test/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/816B8D39-D177-4B78-A162-A2911BEE1036/Session-WebDriverAgentRunner-2017-01-10_162648-C6flxG.log}

[Xcode] 
Testing failed:

[Xcode] 	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'
** TEST FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] xcodebuild failure warrants retry. Retrying...
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down Logger process (pid 40021)
[XCUITest] System log exited with code '0'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=00e3eb9b9d0acf3efcb1aee31c13927edaf97bc6 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability.
[debug] [XCUITest] Log file for xcodebuild test: /Users/test/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/BBB316B6-069B-4F0F-B9D8-0F082B5B359C/Session-WebDriverAgentRunner-2017-01-10_162700-xlRpbJ.log
[Xcode] 2017-01-10 16:27:05.487 xcodebuild[40272:6350162] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/test/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/BBB316B6-069B-4F0F-B9D8-0F082B5B359C/Session-WebDriverAgentRunner-2017-01-10_162700-xlRpbJ.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/test/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/BBB316B6-069B-4F0F-B9D8-0F082B5B359C/Session-WebDriverAgentRunner-2017-01-10_162700-xlRpbJ.log}

[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'

[Xcode] Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'

[Xcode] 

[Xcode] 
Testing failed:

[Xcode] 	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.0'
** TEST FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:332:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:332:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down Logger process (pid 40277)
[XCUITest] System log exited with code '0'
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
(node:39987) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Can't stop process; it's not currently running
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:332:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[HTTP] <-- POST /wd/hub/session 500 23786 ms - 167

**Comment by rockyav** [comment]
@huhutouch 
1. Make sure you perform install follow the link : https://github.com/appium/appium-xcuitest-driver 
2. Then you perform step "Manual configuration alternative" to signing code by:
. Open Terminal
. enter : open /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj
There will be Xcode window open --> waiting build complete --> double click on WebDriverAgent --> WebDriverAgent.xcodeproj open --> click all tabs in TARGETS column and Signing
After signing, switch back to previous window and build.

If there is any steps not clear, you can ping me via skype. My account : rockyav

**Comment by huhutouch** [comment]
Very grateful, I reload the appium, according to the steps you do, the problem has been solved

**Comment by samsonbarukula** [comment]
realdeviceLogger is in which compatibility?

**Comment by samsonbarukula** [comment]
any sample code to fetch the ios app crash log on real device ?

**Comment by imurchie** [comment]
`realDeviceLogger` has been available since Appium 1.7.0.

**Comment by imurchie** [comment]
Sample code depends on the language.

**Comment by samsonbarukula** [comment]
java please

**Comment by samsonbarukula** [comment]
Thanks for the immediate response

**Comment by samsonbarukula** [comment]
I am trying on ios 11 device using appium desktop version: 1.2.4.603
and java client as :  5.0.4
seleniumserverstandalone : 3.6.0

**Comment by imurchie** [comment]
The Java API for getting crash logs is found here: http://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/logging/Logs.html

iOS has a log type `'crashlog'` that includes all the current crash logs.

**Comment by samsonbarukula** [comment]
I have used this 'crashlog' but it is returning a blank list. [ ]

**Comment by samsonbarukula** [comment]
What might be the issue?

**Comment by samsonbarukula** [comment]
Can you please tell on what compatibility the iOS11 real device crashlog will be logged?

**Comment by samsonbarukula** [comment]
hi rockyav, Can you send the sample code pls

**Comment by rockyav** [comment]
@samsonbarukula  what's problem you facing now ?

**Comment by samsonbarukula** [comment]
Johns-Mac-mini-4:bin john$ sudo npm install deviceconsole
-
> deviceconsole@1.0.1 install /usr/local/bin/node_modules/deviceconsole
> make

Making deviceconsole...
ld: framework not found MobileDevice
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1
npm ERR! Darwin 16.7.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "deviceconsole"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! deviceconsole@1.0.1 install: `make`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the deviceconsole@1.0.1 install script 'make'.
npm ERR! This is most likely a problem with the deviceconsole package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make
npm ERR! You can get their info via:
npm ERR!     npm owner ls deviceconsole
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/npm-debug.log

**Comment by samsonbarukula** [comment]
1: I am getting empty list while fetching the crash & syslogs
2: Should I use ""realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole"" Capability ?
3: if I need to use 
realDeviceLogger | Device logger for real devices. It could be path to deviceconsole (installed with npm install deviceconsole, a compiled binary named deviceconsole will be added to ./node_modules/deviceconsole/) or idevicesyslog (comes with libimobiledevice). Defaults to idevicesyslog
-- | --

Both these folders are not present in my mac ... what need to be done next. "While trying sudo npm install deviceconsole it is giving error."

**Comment by samsonbarukula** [comment]
thanks rockyav... can you help or give some sample code, how you could sortit out...

**Comment by samsonbarukula** [comment]
I found there is a "/usr/local/bin/idevicesyslog".... what has to be done next ?

**Comment by imurchie** [comment]
The `realDeviceLogger` capability sets the logger for the device logs. The crash logs are gathered from `~/Library/Logs/DiagnosticReports`, which is where iOS write crash logs.

**Comment by samsonbarukula** [comment]
Form this location: "/usr/local/Cellar/libimobiledevice/1.2.0/bin" I got the crash log.
Thank you imurchie & rockyav......

**Comment by samsonbarukula** [comment]
Isaac: Even I think by show_IOS_ Log and show_xCode_Log generates a crash log because till after noon logs were there, soon after I add "RealDeviceLogger" capability,  new logs are not in  "~/Library/Logs/DiagnosticReports"... .................................(Currently my work got done..........but what might be the cause....? any idea ?)

**Comment by imurchie** [comment]
Do you mean that without `realDeviceLogger` you get crash reports in `~/Library/Logs/DiagnosticReports`? And with it set you do not, though a crash still happens?

**Comment by samsonbarukula** [comment]
Do you mean that without realDeviceLogger you get crash reports in ~/Library/Logs/DiagnosticReports?  Yes

**Comment by rockyav** [comment]
@samsonbarukula Are you signing iOS account in WebDriverAgent ?

**Comment by samsonbarukula** [comment]
[23_11_2017_13-31-41_Crash3c.txt](https://github.com/appium/appium/files/1499007/23_11_2017_13-31-41_Crash3c.txt)

[crashlog - Copy.txt](https://github.com/appium/appium/files/1498999/crashlog.-.Copy.txt)
I am getting a crash log from appium helper but, when I compare with Device crashlogs through xcode It is entirely different. Is there a way to get Device Crash log..... Can you pls cross check both file which i have attached pls .

**Comment by samsonbarukula** [comment]
Hi Isaac any help pls

**Comment by samsonbarukula** [comment]
sorry App Crash Log
