### ISSUE TITLE
[XCUITest] Waiting for WebDriverAgent server to finish loading... 

### ISSUE THREAD

**Issue by razor901** [appium/appium#7504]
## The problem

**[XCUITest] Waiting for WebDriverAgent server to finish loading...**
Basically I keep getting this error repeatedly and it gets repeated more than once if I keep the server opened .
The test doesn't start.
WebDriverAgent & our app get installed but the app does not start

## Environment

Appium 1.6.2
MacOSX 10.11.16
latest node 
All dependencies are installed .

## Link to Appium logs

https://gist.github.com/razor901/5b1af7d71f80f252cbc10443d693d2fd

**Comment by mykola-mokhnach** [comment]
Known issue in the version 1.6.2 Either downgrade to 1.6.1 or wait for 1.6.3 release
