### ISSUE TITLE
Appium1.6.2 iOS9.3.4 about UIAccessibility Error

### ISSUE THREAD

**Issue by CrazyInAppium** [appium/appium#7505]
## The problem

WDA works fine,and the Server URL returns a correct json. But the text will never be executed.Here is my environment and logs.

any help  could be appreciated.
much thanks.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.2
* Last Appium version that did not exhibit the issue (if applicable):none
* Desktop OS/version used to run Appium:Mac OX X EI Capitan 10.11.5
* Node.js version (unless using Appium.app|exe):v6.6.0
* Mobile platform/version under test:iOS/9.3.4
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:CLI

## Details

[HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"ipad","app":"/Users/hoolai/Desktop/TestApp.ipa","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"9.3.4","platformName":"iOS","automationName":"XCUITest"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"ipad","app":"/Users/hoolai/Desktop/TestApp.ipa","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"9.3.4","platformName":"iOS","automationName":"XCUITest"},{},null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   deviceName: 'ipad'
[Appium]   app: '/Users/hoolai/Desktop/TestApp.ipa'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   platformVersion: '9.3.4'
[Appium]   platformName: 'iOS'
[Appium]   automationName: 'XCUITest'
[Appium]   udid: 'c598c3d4d15e6b2f3362db95863da8dc15f6e785'
[Appium]   fullReset: true
[debug] [XCUITest] XCUITestDriver version: 2.3.0
[BaseDriver] Session created with session id: 62b4400b-b017-4268-a95b-75ab8b5fb93c
[debug] [XCUITest] Xcode version set to '8.0'
[debug] [XCUITest] iOS SDK Version set to '10.0'
[debug] [XCUITest] Available devices: c598c3d4d15e6b2f3362db95863da8dc15f6e785
[debug] [XCUITest] Creating iDevice object with udid c598c3d4d15e6b2f3362db95863da8dc15f6e785
[XCUITest] Determining device to run tests on: udid: 'c598c3d4d15e6b2f3362db95863da8dc15f6e785', real device: true
[BaseDriver] Using local app '/Users/hoolai/Desktop/TestApp.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/pv/v9r2x8gs7t72n25qkzgbm9sc0000gn/T/20161112-5965-16o9uhk.apt4qxs9k9/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/pv/v9r2x8gs7t72n25qkzgbm9sc0000gn/T/20161112-5965-16o9uhk.apt4qxs9k9/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/pv/v9r2x8gs7t72n25qkzgbm9sc0000gn/T/20161112-5965-16o9uhk.apt4qxs9k9/Payload/TestApp.app'
[debug] [XCUITest] Checking whether app '/var/folders/pv/v9r2x8gs7t72n25qkzgbm9sc0000gn/T/20161112-5965-16o9uhk.apt4qxs9k9/Payload/TestApp.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/var/folders/pv/v9r2x8gs7t72n25qkzgbm9sc0000gn/T/20161112-5965-16o9uhk.apt4qxs9k9/Payload/TestApp.app': 'com.hoolai.TestApp'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset requested. Forcing app install after uninstall app
[debug] [XCUITest] App installed successfully.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=c598c3d4d15e6b2f3362db95863da8dc15f6e785 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/hoolai/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/78B54A42-B171-4D01-B9A3-4E47D172CDB7/Session-WebDriverAgentRunner-2016-12-12_150057-GSNucF.log
[debug] [WebDriverAgent] Device: Dec 12 15:02:20 iPad XCTRunner[781] <Warning>: Running tests...
[debug] [WebDriverAgent] Device: Dec 12 15:02:21 iPad XCTRunner[781] <Warning>: Continuing to run tests in the background with task ID 1
[debug] [WebDriverAgent] Device: Dec 12 15:02:22 iPad XCTRunner[781] <Warning>: Built at Dec 12 2016 09:55:52
[debug] [WebDriverAgent] Device: Dec 12 15:02:22 iPad XCTRunner[781] <Warning>: ServerURLHere->http://10.0.7.3:8100<-ServerURLHere
[debug] [WebDriverAgent] Device: Dec 12 15:02:22 iPad XCTRunner[781] <Warning>: Listening on USB
[debug] [WebDriverAgent] Device: Dec 12 15:03:21 iPad XCTRunner[786] <Warning>: Running tests...
[debug] [WebDriverAgent] Device: Dec 12 15:03:22 iPad XCTRunner[786] <Warning>: Continuing to run tests in the background with task ID 1
[debug] [WebDriverAgent] Device: Dec 12 15:03:23 iPad XCTRunner[786] <Warning>: Built at Dec 12 2016 09:55:52
[debug] [WebDriverAgent] Device: Dec 12 15:03:23 iPad XCTRunner[786] <Warning>: ServerURLHere->http://10.0.7.3:8100<-ServerURLHere
[debug] [WebDriverAgent] Device: Dec 12 15:03:23 iPad XCTRunner[786] <Warning>: Listening on USB
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding -[DOMNode _moveRight:withHistory:]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding -[DOMNode _moveLeft:withHistory:]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding -[DOMNode _updateSelectionWithTextRange:withAffinityDownstream:]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding +[DOMNode safeCategoryBaseClass]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding -[UIWebFormAccessory initWithFrame:]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding -[UIWebFormAccessory _accessibilityLoadAccessibilityInformation]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding +[UIWebFormAccessory safeCategoryBaseClass]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding +[UIWebFormSelectPeripheral safeCategoryBaseClass]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding +[UIWebFormSelectPeripheral createPeripheralWithDOMHTMLSelectElement:]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding -[UIWebSelectSinglePicker _accessibilityServesAsFirstElement]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding +[UIWebSelectSinglePicker safeCategoryBaseClass]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding -[UIWebSelectMultiplePicker _accessibilityServesAsFirstElement]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding +[UIWebSelectMultiplePicker safeCategoryBaseClass]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding -[UIWebPlugInView webPlugInStart]
[debug] [WebDriverAgent] Device: Dec 12 15:03:24 iPad XCTRunner[786] <Warning>: UIAccessibility Error adding +[UIWebPlugInView safeCategoryBaseClass]
[HTTP] <-- POST /wd/hub/session - - ms - - 
[HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"ipad","app":"/Users/hoolai/Desktop/TestApp.ipa","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"9.3.4","platformName":"iOS","automationName":"XCUITest"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"ipad","app":"/Users/hoolai/Desktop/TestApp.ipa","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","platformVersion":"9.3.4","platformName":"iOS","automationName":"XCUITest"},{},null,null,null,null,null]
[debug] [XCUITest] Log file for xcodebuild test: /Users/hoolai/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/78B54A42-B171-4D01-B9A3-4E47D172CDB7/Session-WebDriverAgentRunner-2016-12-12_151549-3kpH3b.log
[Xcode] 2016-12-12 15:15:49.842 xcodebuild[6004:893780] Error Domain=IDEFoundationErrorDomain Code=3 "The device cannot run executables for arm64." UserInfo={NSLocalizedDescription=The device cannot run executables for arm64., NSLocalizedRecoverySuggestion=The device does not support the architecture of the selected executable. Switch to a device that supports arm64.}

[Xcode] 2016-12-12 15:15:49.842 xcodebuild[6004:893780] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

[Xcode] 
Testing failed:
	Run test suite UITestingUITests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

[Xcode] Failing tests:
	-[UITestingUITests testRunner]
** TEST FAILED **

[Xcode] 2016-12-12 15:03:21.476 XCTRunner[786:344210] Running tests...
2016-12-12 15:03:22.351 XCTRunner[786:344210] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2016-12-12 15:03:23.046
Test Suite 'WebDriverAgentRunner.xctest' started at 2016-12-12 15:03:23.050
Test Suite 'UITestingUITests' started at 2016-12-12 15:03:23.052
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2016-12-12 15:03:23.056
    t =     0.01s     Set Up
2016-12-12 15:03:23.065 XCTRunner[786:344210] Built at Dec 12 2016 09:55:52
2016-12-12 15:03:23.092 XCTRunner[786:344210] ServerURLHere->http://10.0.7.3:8100<-ServerURLHere
2016-12-12 15:03:23.093 XCTRunner[786:344210] Listening on USB
2016-12-12 15:03:24.189 XCTRunner[786:344210] UIAccessibility Error adding -[DOMNode _moveRight:withHistory:]
2016-12-12 15:03:24.189 XCTRunner[786:344210] UIAccessibility Error adding -[DOMNode _moveLeft:withHistory:]
2016-12-12 15:03:24.190 XCTRunner[786:344210] UIAccessibility Error adding -[DOMNode _updateSelectionWithTextRange:withAffinityDownstream:]
2016-12-12 15:03:24.190 XCTRunner[786:344210] UIAccessibility Error adding +[DOMNode safeCategoryBaseClass]
2016-12-12 15:03:24.190 XCTRunner[786:344210] UIAccessibility Error adding -[UIWebFormAccessory initWithFrame:]
2016-12-12 15:03:24.192 XCTRunner[786:344210] UIAccessibility Error adding -[UIWebFormAccessory _accessibilityLoadAccessibilityInformation]
2016-12-12 15:03:24.192 XCTRunner[786:344210] UIAccessibility Error adding +[UIWebFormAccessory safeCategoryBaseClass]
2016-12-12 15:03:24.193 XCTRunner[786:344210] UIAccessibility Error adding +[UIWebFormSelectPeripheral safeCategoryBaseClass]
2016-12-12 15:03:24.205 XCTRunner[786:344210] UIAccessibility Error adding +[UIWebFormSelectPeripheral createPeripheralWithDOMHTMLSelectElement:]
2016-12-12 15:03:24.211 XCTRunner[786:344210] UIAccessibility Error adding -[UIWebSelectSinglePicker _accessibilityServesAsFirstElement]
2016-12-12 15:03:24.214 XCTRunner[786:344210] UIAccessibility Error adding +[UIWebSelectSinglePicker safeCategoryBaseClass]
2016-12-12 15:03:24.216 XCTRunner[786:344210] UIAccessibility Error adding -[UIWebSelectMultiplePicker _accessibilityServesAsFirstElement]
2016-12-12 15:03:24.218 XCTRunner[786:344210] UIAccessibility Error adding +[UIWebSelectMultiplePicker safeCategoryBaseClass]
2016-12-12 15:03:24.221 XCTRunner[786:344210] UIAccessibility Error adding -[UIWebPlugInView webPlugInStart]
2016-12-12 15:03:24.223 XCTRunner[786:344210] UIAccessibility Error adding +[UIWebPlugInView safeCategoryBaseClass]

## Link to Appium logs

Here is the console log:[gist](https://gist.github.com/CrazyInAppium/b385ddbde45f12cb8fb59ebffc14ed7a)

## Code To Reproduce Issue [ Good To Have ]

"""
    Simple iOS tests, showing accessing elements and getting/setting text from them.
    """
import unittest
import os
from random import randint
from appium import webdriver
from time import sleep

class SimpleIOSTests(unittest.TestCase):
    
    def setUp(self):
        # set up appium
        app = os.path.abspath('/Users/hoolai/Desktop/TestApp.ipa')
        self.driver = webdriver.Remote(
            command_executor='http://127.0.0.1:4723/wd/hub',
            desired_capabilities={
                'app': app,
                'platformName': 'iOS',
                'platformVersion': '9.3.4',
                'deviceName': 'ipad',
                'automationName': 'XCUITest',
                'realDeviceLogger': '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
            })
    
    def tearDown(self):
        self.driver.quit()
    
    def _populate(self):
        # populate text fields with two random numbers
        els = [self.driver.find_element_by_accessibility_id('TextField1'),
               self.driver.find_element_by_accessibility_id('TextField2')]
            
        self._sum = 0
        for i in range(2):
            rnd = randint(0, 10)
            els[i].send_keys(rnd)
            self._sum += rnd

    def test_ui_computation(self):
        # populate text fields with values
        self._populate()
        
        # trigger computation by using the button
        self.driver.find_element_by_accessibility_id('ComputeSumButton').click()
        
        # is sum equal ?
        # sauce does not handle class name, so get fourth element
        sum = self.driver.find_element_by_accessibility_id('Answer').text
        self.assertEqual(int(sum), self._sum)
    
    def test_scroll(self):
        els = self.driver.find_elements_by_class_name('UIAButton')
        els[5].click()
        
        sleep(1)
        try:
            el = self.driver.find_element_by_accessibility_id('OK')
            el.click()
            sleep(1)
        except:
            pass
        
        el = self.driver.find_element_by_xpath('//UIAMapView[1]')
        
        location = el.location
        self.driver.swipe(start_x=location['x'], start_y=location['y'], end_x=0.5, end_y=location['y'], duration=800)

if __name__ == '__main__':
    suite = unittest.TestLoader().loadTestsFromTestCase(SimpleIOSTests)
    unittest.TextTestRunner(verbosity=2).run(suite)

**Comment by mykola-mokhnach** [comment]
Known issue with 1.6.2
Either downgrade to 1.6.1 or wait until the next release

**Comment by jlipps** [comment]
1.6.3 is out now.
