### ISSUE TITLE
Can't run test multiple tests in one run

### ISSUE THREAD

**Issue by jacketti** [appium/appium#7508]
## The problem
I have several tests that I used to  be able to run in a suite, but since appium 1.6 I started using the server version and it appears I cannot start a new session for the next test. 

## Environment
* Appium version (or git revision) that exhibits the issue: Appium v1.6.0 (REV ece7f8a24232288832b81aaa230469bdb82faff4)
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13 osx app
* Node.js version (unless using Appium.app|exe): v6.9.1
* Mobile platform/version under test: iOS 10.0.2
* Real device or emulator/simulator: Real device iPhone 6s plus 
* Appium CLI or Appium.app|exe: CLI

## Details

I use Intellij to run my java tests, but when the first test is finished and the next one should start, I encounter problem which prevent the next test to run. 

## Link to Appium logs

log after failed testcase
https://gist.github.com/jacketti/8deafc46f01a37ea2831782d62891421

log after succesful testcase
https://gist.github.com/jacketti/99f9725616b222a632eab116f153c567

## Link to capabilities
https://gist.github.com/jacketti/39155965ef2650604955db66edbdca06

**Comment by imurchie** [comment]
You'll notice that the capabilities being sent in are different.

Working case:
```
{
  "desiredCapabilities": {
    "app": "/Users/robert/Downloads/POSTNL/iOS/AUTO/PostNL3.17.ipa",
    "realDeviceLogger":"/Users/robert/node_modules/deviceconsole/deviceconsole",
    "platformVersion":"10.0.2", 
    "automationName":"XCUITest",
    "bundleId":"nl.postnl.app.acc",
    "xcodeConfigFile":"/Users/robert/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig",
    "platformName":"iOS",
    "udid":"####",
    "fullReset":true,
    "deviceName":"iPhone van Polteq Mobile 131"
  },
  "requiredCapabilities":{}
}
```

Non-working case:
```
{
  "capabilities": {
    "desiredCapabilities": {
      "app":"/Users/robert/Downloads/POSTNL/iOS/AUTO/PostNL3.17.ipa",
      "realDeviceLogger":"/Users/robert/node_modules/deviceconsole/deviceconsole",
      "platformVersion":"10.0.2",
      "automationName":"XCUITest",
      "bundleId":"nl.postnl.app.acc",
      "xcodeConfigFile":"/Users/robert/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig",
      "platformName":"iOS",
      "udid":"####",
      "fullReset":true,
      "deviceName":"iPhone van Polteq Mobile 131"
    },
    "requiredCapabilities": {}
  },
  "desiredCapabilities": {
    "app":"/Users/robert/Downloads/POSTNL/iOS/AUTO/PostNL3.17.ipa",
    "realDeviceLogger":"/Users/robert/node_modules/deviceconsole/deviceconsole",
    "platformVersion":"10.0.2",
    "automationName":"XCUITest",
    "bundleId":"nl.postnl.app.acc",
    "xcodeConfigFile":"/Users/robert/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig",
    "platformName":"iOS",
    "udid":"####",
    "fullReset": true,
    "deviceName":"iPhone van Polteq Mobile 131"
}
```

Your client binding is adding a "capabilities" entry into the hash, for some reason. This ought to have been fixed, though, by [this](https://github.com/appium/appium-base-driver/blob/master/lib/mjsonwp/routes.js#L12). I would update to the latest Appium to get that fix.

**Comment by jacketti** [comment]
After updating to Appium 1.6.3 I get an error with ios-deploy
[debug] [XCUITest] Error checking install status: Command 'ios-deploy --exists --id #### --bundle_id nl.postnl.app.acc' exited with code 255
And I still have my capabilities error which I don't understand. 


https://gist.github.com/jacketti/788db10cdd8df414a5fc0b69f10a145c

**Comment by imurchie** [comment]
What happens when you run 

```
idevicedate -u 487de1d28bc3e6b44528d25cb5662874e46d6127
```

**Comment by jacketti** [comment]
ERROR: Could not connect to lockdownd, error code -21

**Comment by mykola-mokhnach** [comment]
```bash
sudo chmod 777 /var/db/lockdown
```

should do the job. Apple issue, which we (actually, idevicelibrary) cannot workaround

**Comment by jacketti** [comment]
@mykola-mokhnach 

after performing sudo chmod -R 777 /var/db/lockdown/

ERROR: Could not connect to lockdownd, error code -5

**Comment by mykola-mokhnach** [comment]
Uninstall current libimobiledevice and install the most recent one using brew option **--HEAD**

**Comment by jacketti** [comment]
okay now i see the date when I execute the command, but now I get the message that my WebDriverAgentRunner isn't signed properly. I didn't change anything here, and when I fire up Appium 1.6.0 it can run a test, and Appium 1.6.3 gives this log:
https://gist.github.com/jacketti/6614c587bbef09055a9d475719776506

**Comment by jlipps** [comment]
@jacketti appium bundles WebDriverAgent with it, so if you've signed the one with 1.6.0 that doesn't mean the one that came with 1.6.3 is signed. I recommend using the xcodeConfigFile capability rather than signing yourself.
