### ISSUE TITLE
Unable to get the resource id in UIA automator for android Hybrid application in Emulator

### ISSUE THREAD

**Issue by tekisrinivas20** [appium/appium#7509]
## The problem
 As I am automating android hybrid application. I am able to see resource-id in real device but i am not getting the resource-id in Android Emulator, Real device and Emulator are having same configuration. Could any one please help on this.

Please refer the below emulator screenshot.

## Environment

*  Appium 1.5
* Windows 7
* Android 5.0.2
* Emulator
![device1](https://cloud.githubusercontent.com/assets/22059441/21096708/0578c7a8-c087-11e6-95d7-f6da72ae4351.jpg)

Thanks and regards.

**Comment by jlipps** [comment]
Sorry, but if uiautomatorviewer is not showing the resource-id, then this is not an Appium issue. I'd recommend searching around general android help forums for this one.
