### ISSUE TITLE
NODE: ANDROID: Sample code is passing false positive, doesn't run all commands, and hangs up

### ISSUE THREAD

**Issue by goldylucks** [appium/appium#7510]
## The problem
I copied the most minimalistic sample code from the [example repo](https://github.com/appium/sample-code):
- [android simple test suite](https://github.com/goldylucks/dual-n-back/blob/native-e2e/test/e2e-native/home.spec.js)
- [appium servers](https://github.com/goldylucks/dual-n-back/blob/native-e2e/test/helpers/appium-servers.js)
- [caps](https://github.com/goldylucks/dual-n-back/blob/native-e2e/test/helpers/caps.js)
- [logging](https://github.com/goldylucks/dual-n-back/blob/native-e2e/test/helpers/logging.js)
- [setup](https://github.com/goldylucks/dual-n-back/blob/native-e2e/test/helpers/setup.js)

when I run `mocha test/e2e-native/home.spec.js`, I get false positive, only one command is running, and the test hangs up and times out (see attached gists)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Ubuntu 16.04
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: android emulator 6.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: cli

## Details
see gists

## Link to Appium logs
[gist](https://gist.github.com/goldylucks/5a6a46580fb7e6d10e38205fb4f229da)

## Code To Reproduce Issue [ Good To Have ]
I cloned the sample repo and ran the node simple-android test case, ran into the same problem

**Comment by hardik-d** [comment]
@goldylucks it seems memoryNBack is not available as an npm package. who is referencing that package?

**Comment by goldylucks** [comment]
@hardik-d 
indeed it's not available as a package.

It's available in this [repo](https://github.com/goldylucks/dual-n-back/blob/native-e2e)

> who is referencing that package?
what do u mean by that?

**Comment by jlipps** [comment]
@goldylucks those examples are probably pretty out of date now. it might be easiest to just try and accomplish your automation and put the problems you're running into here. I can't see anything particularly wrong with the Appium log output that you've attached. It might be easier to start with a basic one-file setup and see if you can get your app launching and finding something.

**Comment by goldylucks** [comment]
@jlipps thanks for the guidance
in the gist I posted u can c the tests r timing out

>  those examples are probably pretty out of date now
do u have any minimalistic example I can copy?

**Comment by imurchie** [comment]
I recently had to create a simple iOS example in Node. It could be adapted for Android.

https://github.com/imurchie/basic-js-test

**Comment by goldylucks** [comment]
@imurchie I don't c any Appium reference on that repo
r u using it?

**Comment by imurchie** [comment]
Yes, I used it. You need to start Appium manually, and then run the tests.

**Comment by goldylucks** [comment]
@imurchie I'm trying your solution it seems like it works, tho I can't be sure since I can't find anywhere a working example or a documentation of nodeJS appium syntax + react native corresponding code.

do u know of any?

I find it very odd there is no full example anywhere, showing how to find an element.

especially when appium has bold giant title in the homepage saying
# Easy setup process, run a test now

this is supposed to be simple :(

**Comment by jlipps** [comment]
There are two things that "setup" could mean:
* Getting the Appium server running
* Getting an initial test of your application written

What we advertise on the homepage is the first thing. If you're having any problems getting the Appium server running, we'd definitely like to hear about it. Obviously we'd like for the second thing to be easy as well, but our sample code repo, which you found, has not been well maintained. We have a project on the books to update it so that it is guaranteed to work against the latest version of Appium.

In the meantime, the code @imurchie shared can be used in conjunction with our documentation to get you up to speed. The fact that you're using React Native should not in any way prevent you from following existing guides

**Comment by goldylucks** [comment]
> What we advertise on the homepage is the first thing

Gotcha.

>The fact that you're using React Native should not in any way prevent you from following existing guides

is there an existing guide that shows an example for node js?
regardless of react-native.

**Comment by jlipps** [comment]
The files in @imurchie's test repo are a good place to start. It doesn't take the form of a guide. There are guides galore on the internet (and even books) which a google search can help you find, but unfortunately they tend to go out of date quickly since the ecosystem is very fast-moving at this point.

**Comment by goldylucks** [comment]
@jlipps I haven't found a single guide, tutorial, or example, using appium with nodejs.

maybe I'm missing something obvious?

**Comment by jlipps** [comment]
@goldylucks did you look at the link @imurchie shared above? https://github.com/imurchie/basic-js-test.

Getting Appium itself set up is not Node-specific. You can follow any Appium guide. If you want to write and run tests written in Node, then the link I just shared should be a good starting template.

**Comment by goldylucks** [comment]
@jlipps the android example there is new.
I'll check it out, thanks!

**Comment by goldylucks** [comment]
@imurchie i c u use `elementByAccessibilityId` in your tests.
is that equal to the string of an element?

if so for some reason it doesn't work on my app.
Maybe it's a react native glitch.

I can make a barebones repo of an apk and the test.
will that help?

**Comment by hardik-d** [comment]
accessibilityID maps to content-desc in android and accessiblityID in ios. your respective app elements needs to have these properties set for you to use accessiblityID strategy

**Comment by jlipps** [comment]
There's an open issue about react native ids being mapped to the tag field in Android which makes them unfindable using normal mechanisms. So that may cause problems for now: https://github.com/appium/appium/issues/6025 (we're working on this though)

**Comment by goldylucks** [comment]
following #6025 , I ended up using [this](https://github.com/facebook/react-native/pull/9942#issuecomment-266992184) solution.

thanks for the help @jlipps !

I've seen many people online struggling with RN and appium (and actually, e2e testing in general).

I think it could b very valuable to have an updated sample code.
I can prepare a PR for this repo or the sample-code repo.

What do u think?

**Comment by jlipps** [comment]
@goldylucks if you have a PR for the sample-code repo, please do send it in!
