### ISSUE TITLE
iOS Driver Build is Broken: SQLITE_CANTOPEN

### ISSUE THREAD

**Issue by imurchie** [appium/appium#7511]
I've tracked the problem down to there not being a `Librarys/Keychains/TrustStore.sqlite3` directory in the sim's `data` dir, on Travis. Not sure why this would be. But the certificate trust store module then dies with `SQLITE_CANTOPEN` error that is uncatchable, for some reason.

The temporary solution is probably to quarantine the test on Travis. See https://github.com/appium/appium-ios-driver/pull/201

**Comment by jlipps** [comment]
do you think it's worth trying to get to the bottom of this on travis in the next sprint?

**Comment by imurchie** [comment]
I think the sqlite3 stuff needs to be looked at. We're seeing a number of issues around installing it. This can be wrapped into that, if possible.

**Comment by midopa** [comment]
I see this error when I try to start an iOS simulator with Appium 1.6.3 and with the `customSSLCert` capability.

**Comment by midopa** [comment]
The most naive, brute force way to fix this is to create the paths/file/table. This is obviously fragile and can break without notice. Is there some way to trigger the simulator to create these files without have to manually recreate a SQLite database/table/schema?

Otherwise, here's a patch for getting the file created. It goes in `appium-ios-simulator`. I'm not inclined to submit a PR for this since it's sooo hacky:

```patch
diff --git a/lib/certificate.js b/lib/certificate.js
index 11cf4e7..6b10150 100644
--- a/lib/certificate.js
+++ b/lib/certificate.js
@@ -1,6 +1,8 @@
+import log from './logger';
 import crypto from 'crypto';
 import B from 'bluebird';
 import path from 'path';
+import fs from 'fs';

 const sqlite3 = B.promisifyAll(require('sqlite3'));
 const openssl = B.promisify(require('openssl-wrapper').exec);
@@ -110,8 +112,22 @@ class Certificate {
  */
 class TrustStore {
   constructor (sharedResourceDir) {
-    this.sqliteDBPath = path.resolve(sharedResourceDir, 'Library/Keychains/TrustStore.sqlite3');
+    let sqlDBFolder = path.resolve(sharedResourceDir, 'Library/Keychains');
+    let folderExists = fs.existsSync(sqlDBFolder);
+    if (!folderExists) {
+      log.warn('SQLite DB folder did not exist. Creating');
+      fs.mkdirSync(sqlDBFolder);
+    }
+
+    this.sqliteDBPath = path.resolve(sqlDBFolder, 'TrustStore.sqlite3');
+    let dbFileExists = fs.existsSync(this.sqliteDBPath);
     this.db = new sqlite3.Database(this.sqliteDBPath);
+
+    // We'll have to create the tables
+    if (!dbFileExists) {
+      log.warn('Recreating SQLite DB...');
+      this.db.exec("CREATE TABLE tsettings(sha1 BLOB NOT NULL DEFAULT '',subj BLOB NOT NULL DEFAULT '',tset BLOB,data BLOB,PRIMARY KEY(sha1)); CREATE INDEX isubj ON tsettings(subj);");
+    }
   }

   /**
```

The schema was lifted from opening and inspecting the TrustStore DB after drag/dropping a self-signed cert onto the simulator and installing it.

**Comment by imurchie** [comment]
@dpgraham Any thoughts on this?

**Comment by dpgraham** [comment]
If there is no sqlite truststore present in the Keychains directory than we would indeed expect there to be problems. The tests that I wrote didn't account for that directory not existing and @midopa's fix would correct this.

**Comment by imurchie** [comment]
Does @midopa 's hack make the trust store work? Or just make our code not break? Does the custom cert take affect?

Further, is there some plist entry we're missing that would turn on the feature and make the sim build its own trust store?

**Comment by dpgraham** [comment]
I would have to create a test to confirm if it actually fixes the problem. @imurchie you might have a point about the plist entry. The non-existence of a SQLite TrustStore might suggest that the simulator isn't configured to accept truststore entries.

**Comment by dpgraham** [comment]
p.s.: I'm going to be away from December 30th to January 14th so we may want to move this up on our priority list so that I can take a look at it.

**Comment by imurchie** [comment]
Yeah. If we are saying that we support this, we should be clear about it.

**Comment by jlipps** [comment]
OK, moved into current sprint

**Comment by midopa** [comment]
> @dpgraham asked: Were you actually able to observe that one of your simulators didn't have a TrustStore and then when you drag-and-dropped the cert onto Safari, the TrustStore appeared for the first time?

I thought I did, but I can't repro that specific scenario. I think the drag-drop cert was a red herring. I believe the TrustStore files are created after the Simulator restarts outside of Appium.

Here's how I can repro the original issue:
1. Run an Appium session with `fullReset: true` and `noReset: false`
2. Close the session (this will cause all the simulator's files to be removed from disk, include the `Keychains` directory)
3. Start another Appium session, this time with a `customSSLCert` capability
4. The initialization will immediately fail with `Error: SQLITE_CANTOPEN: unable to open database file`

Addendum:
5. Navigate to where the simulator files are.
6. Verify the Keychains dir is missing
7. Start the simulator outside of Appium
8. After the simulator starts again, verify the Keychains dir and TrustStore files are recreated

Given the addendum, I think the better way to handle the original error is to wait for the simulator to finish starting before attempting to add something to the TrustStore DB.

WRT to imurchie's question, I don't know if this will enable custom SSL capability. It only addresses the error message.

**Comment by dpgraham** [comment]
I opened a pull request at https://github.com/appium/appium-ios-simulator/pull/86. 

Most of this was taken from what @midopa did and then was refactored to be more async. Thanks for the help on this @midopa!

The test I did was
1. Rimraf the keychains dir of Simulator 345072D1-38A2-4EFA-8407-AEDD32D350FC
2. Start an https server with a new certificate at localhost:9758
3. Open Simulator 345072D1-38A2-4EFA-8407-AEDD32D350FC Safari to that page to confirm that it's unaccessible
4. Call the installSSLCert method in ios-simulator
5. Restart the Simulator
6. Check the page to confirm that it's now accessible
7. Check the keychains dir to confirm that a new TrustStore sqlite database was added

**Comment by dpgraham** [comment]
This test proves that there is a case where a Keychains folder gets deleted and then when you use 'installSSLCert' it will re-create the Keychains folder and the SQLite truststore and work correctly, so far that reason I think we can apply the patch that I provided.

But it's still TBD if there is a case where a Keychains folder doesn't exist for some other reason and re-inserting the truststore won't apply the certificate.
