### ISSUE TITLE
Both Appium 1.6.1 and 1.6.2 and 1.6.3 failed to launch app on Real Device

### ISSUE THREAD

**Issue by pengboZheng** [appium/appium#7512]
## The problem
**This issue will only happen when** `capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");` **with Real Device**

WebDriverAgent installed on device but couldn't install app. It will work with simulator. And it will work on device without xcuitest enabled.
1. HW kbd: Failed to set (null) as keyboard focus
2. App accessibility isn't loaded
3. App state is still not running active, state = XCApplicationStateNotRunning
4. Unable to start WebDriverAgent session: An unknown server-side error occurred while processing the command.

**Appium 1.6.2 with xcuitest 2.4.1 installed but still doesn't work**

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1 and 1.6.2 and 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.12.1
* Node.js version (unless using Appium.app|exe): 7.2.0
* Mobile platform/version under test: iOS 9.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details
See 1.6.1 [Gist](https://gist.github.com/pengboZheng/212e8becf8d0c16d9ae014409bac7433) log
See 1.6.2 [Gist](https://gist.github.com/pengboZheng/9981319256e4fdcc23fb89acebf38e4f) log
See 1.6.3 [Gist](https://gist.github.com/pengboZheng/8e978a578bb9f792a6e5efe88155ef1b) log

**Comment by dilsreccse** [comment]
its due to timestamp in the real device, updating the time in the iPad/iPhone device worked work for me.

**Comment by f-liu0117** [comment]
@dilsreccse I have the same issue as @pengboZheng , could I ask you how to update the time in iPhone?

**Comment by pengboZheng** [comment]
@dilsreccse the time on the device has been set automatically already, And this is only happen on iOS 9.3 device, iOS 10 device works fine with same settings

**Comment by pengboZheng** [comment]
@imurchie Could you take a look this issue please?

**Comment by mykola-mokhnach** [comment]
Appium cannot execute app with bundle id "com.myownapp.myownapp"
What are your capabilities?

**Comment by mykola-mokhnach** [comment]
try to remove this line

```\
```

**Comment by pengboZheng** [comment]
after remove bundleid from capabilities: 

> [debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] The following capabilities were provided, but are not recognized by appium: takesScreenshot, ipa.
[XCUITest] Error: The desired capabilities must include either an app or a bundleId for iOS

**Comment by mykola-mokhnach** [comment]
rename _ipa_ capability to _app_

**Comment by mykola-mokhnach** [comment]
closing as non-Appium issue

**Comment by pengboZheng** [comment]
@mykola-mokhnach Ah, Thanks!
