### ISSUE TITLE
Unable to install Appium CLI w/ NPM - Issue with sqlite3?

### ISSUE THREAD

**Issue by topraman91** [appium/appium#7515]
## The problem

While setting up the appium development environment on my work MacBook, I've been running into issues installing Appium CLI through npm. I've followed the steps recommended for installing Appium CLI using Homebrew and NPM after setting the proxy for npm and git. I've also tried hard copied/pasted from a non-enterprise MacBook to the enterprise machine and that's not working. Please check out the below steps to recreate the issue.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.X
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: Mac OS X El Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): Node v7.2.1, npm v4.0.3
* Mobile platform/version under test: Android & iOS
* Real device or emulator/simulator: Real devices
* Appium CLI or Appium.app|exe: Appium CLI

## Details

While trying to install Appium CLI through npm, I'm getting an error when npm is trying to install sqlite3. I already have sqlite3 installed on my system in my Android sdk's platform-tools folder because it does start up. However, when executing "npm install -g appium," the following error comes up. I've also tried sudo while installing Homebrew, Node, and Appium but I'm not allowed to even though my account has administrator rights. I've tried to install sqlite3 by itself but that gave me an error that pointed me to node-pre-gyp, which I was also not able to install independently using npm.

## Error:

Before executing git config command:
<img width="564" alt="beforegitconfigcommands" src="https://cloud.githubusercontent.com/assets/24533361/21122000/7d354440-c084-11e6-9f1e-f2341a5aab4a.png">

After executing git config command:
[appiumIssue1.txt](https://github.com/appium/appium/files/647579/appiumIssue1.txt)

## Code To Reproduce Issue

Commands run to reproduce error:

1) Install Homebrew:
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

2) Install Node & NPM:
brew update
brew install node

3) Set proxy either in bash( or execute command to set proxy):
3.1) Add following to bash_profile:
proxy-set() {
   export HTTP_PROXY=http://proxy.company.com:8080";
   export HTTPS_PROXY=http://proxy.company.com:8080";
   npm config set proxy "http://proxy.company.com:8080";
   npm config set https_proxy "http://proxy.company.com:8080";
   npm config set registry "http://registry.npmjs.org/";
   npm config set strict_ssl "false";
}
3.2) Set proxy for current terminal:
proxy-set
3.3) Set git proxy:
git config --global http.proxy http://proxy.company.com:8080
git config --global https.proxy http://proxy.company.com:8080

4) Install Appium CLI:
npm install -g appium

**Comment by jlipps** [comment]
the npm config command should be `npm config set http-proxy`, did you try that?

**Comment by topraman91** [comment]
@jlipps Yea I tried that but same error

**Comment by jlipps** [comment]
Hmm I'm out of ideas then. I'm closing this though since it's not an appium issue but rather something with your network or with NPM.

**Comment by topraman91** [comment]
I've tried the steps to install Appium on both enterprise and non-enterprise Mac's that are not on an enterprise network and I get the same error. There could be some version mismatching or unsupported versions of other packages that Appium uses. Npm fetches I believe the latest version of the package specified by the specific or range of supported versions in the package.json's. Since Appium just came out with a new release yesterday, there could be a chance that something broke on Appium or NPM side. Can someone verify this by trying to install Appium now starting from the beginning of the process where you have to install Homebrew?

**Comment by jlipps** [comment]
@topraman91 since appium uses a shrinkwrap, the dependency upgrade theory shouldn't be possible.

i ran into an npm issue myself yesterday and solved it with:

```
npm uninstall -g appium
npm install -g npm@4.0.5
npm install -g appium
```
