### ISSUE TITLE
UiObject2 referring to wrong element

### ISSUE THREAD

**Issue by sravanmedarapu** [appium/appium#7516]
@sravanmedarapu commented on [Tue Oct 18 2016](https://github.com/appium/appium-uiautomator2-server/issues/29)

The Problem:
Referring to previously created element which is not exist in the screen (in the same activity/view) pointing to a random element instead of throwing `StaleObjectException` in Scrollable view.

Happens only with UiObject2 elements.

Reported in google [UIAutomator2](https://code.google.com/p/android/issues/detail?id=224441)

**Comment by jlipps** [comment]
@sravanmedarapu do you have any ideas on how to resolve this? can we do some kind of check on it before acting on it?

**Comment by igalep** [comment]
Keep annoying !!!

PLS try to fix it , or rise it's priority

Thanks
