### ISSUE TITLE
unable to launch application from appium 1.6

### ISSUE THREAD

**Issue by kumarmp4git** [appium/appium#7518]
## The problem
Appium able to install the app on the iOS device (both - testApp & webdriveragentRunner), and it launches the webDrvierAgentRunner app & just hangs there. there will be no errors/debug info logged to the logs. but once i kill that app from the phone it shows below logs: 
Please see the link for the logs until it struck - https://gist.github.com/kumarmp4git/443d7e2c22b6755782795f7439f305c0

[Xcode] 2016-12-13 17:04:24.947 xcodebuild[2478:33848] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

[Xcode] 
Testing failed:

[Xcode] 	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **

[Xcode] Test Suite 'All tests' started at 2016-12-13 17:00:41.385
Test Suite 'WebDriverAgentRunner.xctest' started at 2016-12-13 17:00:41.389
Test Suite 'UITestingUITests' started at 2016-12-13 17:00:41.389
Test Case '-[UITestingUITests testRunner]' started.

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:332:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
 Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:332:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down Logger process (pid 2484)
[XCUITest] System log exited with code '0'
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:332:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
[HTTP] <-- POST /wd/hub/session 500 553422 ms - 167

**Comment by mykola-mokhnach** [comment]
Try to upgrade to 1.6.3 - that version contains a bugfix for startup on real devices.

Pay attention to this log line:
> [XCUITest] The real device logger 'idevicesyslog' was unable to start log capture. Please try installing 'deviceconsole' ('npm install -g deviceconsole') and specify the path to it using the 'realDeviceLogger' capability.

And make sure you are following real device configuration steps from [this](https://github.com/appium/appium-xcuitest-driver) tutorial

**Comment by kumarmp4git** [comment]
thanks @mykola-mokhnach ,
added real deviceLogger capability. Now even it launched the webdriveragentrunner app and hangs in there. logs here
https://gist.github.com/kumarmp4git/e3208b74b98848a654cd574ac3bb4bce

**Comment by mykola-mokhnach** [comment]
Try restarting the phone

**Comment by kumarmp4git** [comment]
@mykola-mokhnach , i updated appium to 1.6.3 and restarted device. on device i can see testApp is installed but not the webdriverAgentrunner. below is log snippet.
Appreciate your help.

[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[XCUITest] Real device logger '/usr/local/lib/node_modules/deviceconsole' is a directory. Appending 'deviceconsole' executable
[debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Using Xcode configuration file: '/Users/ballolli.s/playground/a_project/myconfig.xcconfig'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=268a5e06e19c4bc406721881933b851063424515 -configuration Debug -xcconfig /Users/ballolli.s/playground/a_project/myconfig.xcconfig' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u 268a5e06e19c4bc406721881933b851063424515' exited with code 255
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u 268a5e06e19c4bc406721881933b851063424515' exited with code 255
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: undefined
[HTTP] <-- POST /wd/hub/session 500 1822 ms - 262

**Comment by mykola-mokhnach** [comment]
use search. Other people had the same problem

**Comment by kumarmp4git** [comment]
got this resolved after building the webdriverAgentRunner from the Xcode and sudo chmod 777 /var/db/lockdown.
Now am able to launch the test application.

thank you.
