### ISSUE TITLE
Unable to find version 3.8.6 in appium-instruments repo

### ISSUE THREAD

**Issue by john7doe** [appium/appium#7519]
## The problem

In https://github.com/appium/appium/blob/v1.6.3/npm-shrinkwrap.json I see:

"appium-instruments": {
      "version": "3.8.6"
...

That version is nowhere to be found here:

https://github.com/appium/appium-instruments

Last version is 3.8.5

**Comment by imurchie** [comment]
Someone must have forgotten to push the publish commit to Github. It is definitely published on [npm](https://www.npmjs.com/package/appium-instruments) though:

```
$ npm view appium-instruments dist-tags
{ latest: '3.8.6', beta: '3.2.0' }
```

@jlipps Can you check if you need to push after publishing `appium-instruments`?

**Comment by jlipps** [comment]
Fixed--pushed to my fork rather than appium. I'm unclear how this could have caused any issues, however.
