### ISSUE TITLE
Fail to launch test on real iOS device

### ISSUE THREAD

**Issue by jeangb** [appium/appium#7520]
## The problem

Since 3 days I'm struggling to launch a test on real device.
I'm trying to use the XCUITest framework. I've been setting the team on all the targets from the WDA Xcode project.
When I launch my test, I've got this error from appium server:

> [XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u e75c0085c74a872846772a6b2ee56a86849a4d92' exited with code 255

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: 10.11.6
* Node.js version (unless using Appium.app|exe): v6.9.1
* Mobile platform/version under test: iOS 9.3.5
* Real device or emulator/simulator: real (iPhone 6 plus)
* Appium CLI or Appium.app|exe: appium CLI
* Xcode : **8.1**

## Details

Here's my setup to launch the appium driver:
```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"[MY_DEVICE_NAME]");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "9.3.5");
capabilities.setCapability(MobileCapabilityType.UDID, "[MY_UDID]");
capabilities.setCapability("bundleId", "im.vector.app");//app
		
//TODO: XCUITest is used because Appium Ios driver doesn't support xcode version 8.0
capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
capabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
capabilities.setCapability("xcodeConfigfile", "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig");
capabilities.setCapability("autoDismissAlerts", false);
AppiumFactory appiumFactory=new AppiumFactory();
appiumFactory.setiOSDriver1(new URL(Constant.SERVER1_ADRESS), capabilities);
```

Here's the full logs of appium server:
https://gist.github.com/jeangb/904a7fcd0077f8e342fef7baf3811280
I saw Appium Server is trying to build the WDA agent with the command 

> xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e75c0085c74a872846772a6b2ee56a86849a4d92 -configuration Debug

so I've been executed this command and here's the log it give me:
https://gist.github.com/jeangb/c6c9b2b28e4620f426137f4da60091fe.

And when I launch the "build an then test the current scheme" of the runner target of the Xcode project (WDA), I've got this:
```
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/BBFB42C4-6E64-494A-AE2B-0E45C4FF2E8F/WebDriverAgentRunner-Runner.app/XCTRunner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/BBFB42C4-6E64-494A-AE2B-0E45C4FF2E8F/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/BBFB42C4-6E64-494A-AE2B-0E45C4FF2E8F/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
	/private/var/containers/Bundle/Application/BBFB42C4-6E64-494A-AE2B-0E45C4FF2E8F/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/BBFB42C4-6E64-494A-AE2B-0E45C4FF2E8F/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
(lldb) 
```
It manages to launch WebDriverAgent on the phone but screen is black.

Can you help me ?

**Comment by pavanbachu0604** [comment]
please update libimobiledevice

**Comment by pengboZheng** [comment]
Based on my experience: https://github.com/appium/appium/issues/7512, A Real Device with iOS 9.3 and Xcuitest won't work.
If anyone can have a way to solve this issue, I am really happy to hear about it.

**Comment by imurchie** [comment]
What happens when you run `idevicedate -u e75c0085c74a872846772a6b2ee56a86849a4d92`?

**Comment by jeangb** [comment]
@pavanbachu0604, I did "brew upgrade libimobiledevice" and got "Error: libimobiledevice 1.2.0 already installed".
Nothing changed when I launched the tests.

**Comment by jeangb** [comment]
@pengboZheng I'm very sorry to hear that... can others confirm that ? what will work so ?

@imurchie : I got "ERROR: Could not connect to lockdownd, error code -21" when executing your command.

**Comment by imurchie** [comment]
`brew install libimobiledevice@HEAD`.

You can also get around it by running `sudo chmod 777 /var/db/lockdown`.

**Comment by pengboZheng** [comment]
```
~ $  brew install libimobiledevice@HEAD
Updating Homebrew...
Error: No available formula with the name "libimobiledevice@head"
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

**Comment by jeangb** [comment]
@imurchie @pengboZheng when doing brew install libimobiledevice@HEAD I got the same logs than pengboZheng ones.
But after using "sudo chmod 777 /var/db/lockdown", I launched the tests and logs from appium server are different:
I got the famous "[XCUITest] xcodebuild exited with code '65' and signal 'null'" error and the same error than Xcode too : "[Xcode] dyld: Library not loaded: @rpath/XCTest.framework/XCTest".
Full logs here: https://gist.github.com/jeangb/a5872e360996c61b0ffb00e61d48e44b

**Comment by pengboZheng** [comment]
@jeangb based on your log, seems you need to follow "Manual configuration alternative" in https://github.com/appium/appium-xcuitest-driver

**Comment by pavanbachu0604** [comment]
It should be brew install libimobiledevice --HEAD

**Comment by jeangb** [comment]
Sorry I have a new problem now when I try to open the project with xCode: "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBXPath.h:13:9: 'WebDriverAgentLib/XCElementSnapshot.h' file not found"
I don't know why suddenly I have that. I've been removing node_modules/appium-xcuitest-driver and installing appium again, but it still there .........

**Comment by jeangb** [comment]
@pengboZheng I'm doing this but I'm blocked at "sh ./Scripts/bootstrap.sh -d". I have sh: ./Scripts/bootstrap.sh: No such file or directory.

**Comment by jeangb** [comment]
Forgot my last message I was in the wrong directory

**Comment by jeangb** [comment]
So following "Manual configuration alternative" and executing   "xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test" (with the real udid) I got this:

https://gist.github.com/jeangb/498c1c2f53209d1268cfec86dc69db7f

**Comment by pengboZheng** [comment]
Suggestions:
1. update node
2. take a look at https://github.com/appium/appium/issues/7022 in details
By the way, xcuitest and iOS 9, 10 with Real Device working fine on my end.

**Comment by jeangb** [comment]
So the problem when Xcode couldn't execute the wda on a real device was because I executed the wrong target.
Now when I build and test on the WebDriverAgentRunner I have the following error:
```
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/419931E5-8687-4A55-A434-E632AF6CC56C/WebDriverAgentRunner-Runner.app/XCTRunner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/419931E5-8687-4A55-A434-E632AF6CC56C/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/419931E5-8687-4A55-A434-E632AF6CC56C/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
	/private/var/containers/Bundle/Application/419931E5-8687-4A55-A434-E632AF6CC56C/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/419931E5-8687-4A55-A434-E632AF6CC56C/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
```

I had this error yesterday but when I was referencing this framework I still had this issue...
@pengboZheng thanks, I'm looking at #7022

**Comment by jeangb** [comment]
![red](https://cloud.githubusercontent.com/assets/22364949/21175821/8bee3904-c1e4-11e6-8646-4f9d9c3de24e.png)
In xcode I noticed I have these products which aren't founded, is that a problem ?

**Comment by syedasadulhaq** [comment]
I got the exact same error with appium 1.6.3 while trying to execute the test cases on real device
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u udid' exited with code 255
idevicedate -u udid
ERROR: Could not connect to lockdownd, error code -5
(I had tried with iPad Air 2 and iPad mini 4)

sudo chmod 777 /var/db/lockdown didn't help.

**Comment by mykola-mokhnach** [comment]
@syedasadulhaq make sure the libimobiledevice is installed from HEAD branch

**Comment by mstrelex** [comment]
I expirience the same issue.

# Environment

- Appium version (or git revision) that exhibits the issue: 1.6.3
- Desktop OS/version used to run Appium: 10.12.1
- Node.js version (unless using Appium.app|exe): v7.0.0
- Mobile platform/version under test: iOS 9.3.4 (13G35)
- Real device or emulator/simulator: Real Device (iPad Mini 2)
- Appium CLI or Appium.app|exe: appium CLI (bash)
- Xcode : Version 8.1 (8B62)

# Capabilities

- capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
- capabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
- capabilities.setCapability("xcodeConfigFile", "~/Desktop/Appium.xcconfig");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "[DEVICE_NAME]");
- capabilities.setCapability(MobileCapabilityType.UDID, "[UDID]");
- capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "9.3");
- capabilities.setCapability(IOSMobileCapabilityType.BUNDLE_ID, "[BUNDLE_ID]");

# Log

> `
> [debug] [XCUITest] XCUITestDriver version: 2.4.2
> [BaseDriver] Session created with session id: d7fabff1-d6d7-4e65-984a-ba7847c85899
> [debug] [XCUITest] iOS SDK Version set to '10.1'
> [debug] [XCUITest] Available devices: [UDID]
> [debug] [XCUITest] Creating iDevice object with udid [UDID]
> [XCUITest] Determining device to run tests on: udid: '[UDID]', real device: true
> [debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
> [debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
> [XCUITest] Setting up real device
> [XCUITest] Using WDA path: '~/appium-1.6.3/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
> [XCUITest] Using WDA agent: '~/appium-1.6.3/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
> [XCUITest] Launching WebDriverAgent on the device
> [debug] [XCUITest] Carthage found: /usr/local/bin/carthage
> [debug] [XCUITest] Killing hanging processes
> [debug] [XCUITest] Using real device logger '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
> [debug] [XCUITest] Using Xcode configuration file: '~/appium-1.6.3/Appium.xcconfig'
> [debug] [XCUITest] Beginning test with command 'xcodebuild build test -project ~/appium-1.6.3/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=8457b818646c3089a8ddd896bcc5155c755ea5a7 -configuration Debug -xcconfig ~/Desktop/Appium.xcconfig' in directory '~/appium-1.6.3/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
> [XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u [UDID]' exited with code 255
> [XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u [UDID]' exited with code 255
> [XCUITest] Shutting down sub-processes
> [debug] [XCUITest] Running ios real device reset flow
> [debug] [XCUITest] Resetting simulator
> [debug] [iOSLog] Stopping iOS log capture
> [MJSONWP] Encountered internal error running command: undefined
> [HTTP] <-- POST /wd/hub/session 500 1634 ms - 262 
> `

**Comment by jeangb** [comment]
I give up. I'm starting to loose my mind on this.

**Comment by syedasadulhaq** [comment]
@ mykola-mokhnach:
brew install libimobiledevice --HEAD

Warning: libimobiledevice-1.2.0 already installed
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.

**Comment by mstrelex** [comment]
As @imurchie and @mykola-mokhnach suggested `brew install libimobiledevice --HEAD` resolves this. But it works only ones, and then for the second attempt it's stuck. WebDriverAgent is opened and closed, but logs never continues and is just frozen after _Waiting for WebDriverAgent to start on device_

**Comment by jeangb** [comment]
I've been installing the libimobiledevice-HEAD-9df4e69, fetching dependencies with Script/build.sh, restarting device, using chmod 777 /var/db/lockdown, added the XCtest framework to the project, and I still have this:
```
[Xcode] 2016-12-14 14:18:46.647 xcodebuild[18363:149085] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

[Xcode] 
Testing failed:
	Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

[Xcode] ** TEST FAILED **


[Xcode] dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /var/containers/Bundle/Application/A04D1FDF-8104-4061-B053-F082513002DC/WebDriverAgentRunner-Runner.app/XCTRunner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/A04D1FDF-8104-4061-B053-F082513002DC/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/A04D1FDF-8104-4061-B053-F082513002DC/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest'
	/private/var/containers/Bundle/Application/A04D1FDF-8104-4061-B053-F082513002DC/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/A04D1FDF-8104-4061-B053-F082513002DC/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest' 
```

**Comment by syedasadulhaq** [comment]
Able to solve the problem by reinstalling libimobiledevice
brew uninstall libimobiledevice
brew install libimobiledevice --HEAD

**Comment by jibingli** [comment]
@jeangb i meet the same problem, have you solved it ?

**Comment by jeangb** [comment]
@jibingli No I put that aside for the moment. Keep us in touch if you find something ! good luck

**Comment by jibingli** [comment]
@jeangb it failed when I directly use xcodebuild command to run WDA in real devices, but succeed when destination is simulator. Maybe it is WDA problems, new issue has been opened there

**Comment by jeangb** [comment]
@jibingli Hi, do you have the issue id you mentioned ?

**Comment by jeangb** [comment]
@imurchie Hi, do you have some news ? I'm still having the "dyld: Library not loaded: @rpath/XCTest.framework/XCTest" error from appium server. 
In Xcode, I've been trying some solutions like adding "$(PROJECT_DIR)/Carthage/Build/iOS" in framework search path, putting XCTest.framework status as optional, nothing change.

**Comment by jeangb** [comment]
I finally solved my problem ... As I wanted to build the .ipa with the developer certificate myself, I put a few weeks ago the iPhone developer certificate at "Always trust" in "When using this certificate", in order not to be prompted.
Following this: https://forums.developer.apple.com/message/69085#69085, I saw it had to be "Use system defaults".

**Comment by vikramvi** [comment]
unlink older version and install HEAD

```
Vikrams-MacBook-Pro:~ vikram-anna$ brew install libimobiledevice --HEAD
Error: libimobiledevice-1.2.0 already installed
To install this version, first `brew unlink libimobiledevice`
Vikrams-MacBook-Pro:~ vikram-anna$ brew unlink libimobiledevice
Unlinking /usr/local/Cellar/libimobiledevice/1.2.0... 39 symlinks removed
Vikrams-MacBook-Pro:~ vikram-anna$ brew install libimobiledevice --HEAD
```

**Comment by Althafpasha** [comment]
Im getting the below error on running "brew install libimobiledevice --HEAD" command

ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.

how to configure this-- CFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib ./configure

**Comment by skhanam** [comment]
not sure why am seeing this without the results others are seeing


idevicedate -u E6CD048D-7AA8-4113-874A-A77A4548B215
Usage: idevicedate [OPTIONS]
Display the current date or set it on a device.

NOTE: Setting the time on iOS 6 and later is only supported
      in the setup wizard screens before device activation.

  -d, --debug		enable communication debugging
  -u, --udid UDID	target specific device by its 40-digit device UDID
  -s, --set TIMESTAMP	set UTC time described by TIMESTAMP
  -c, --sync		set time of device to current system time
  -h, --help		prints usage information

Homepage: <http://libimobiledevice.org>

**Comment by imurchie** [comment]
@skhanam You need to upgrade your Appium version. The problem you are having is a known issue with older versions.

**Comment by skhanam** [comment]
@imurchie  am on Appium 1.6.5-beta

**Comment by imurchie** [comment]
@skhanam Can you provide the full server logs (as a link to a [gist](https://gist.github.com)) then? Appium 1.6.5-beta should not be using `idevicedate` at all.
