### ISSUE TITLE
Cannot start Facebook default app "IntegrationApp" on simulator

### ISSUE THREAD

**Issue by dcaric** [appium/appium#7521]
## The problem

I have latest appium 1.6.3 and I think everything is configured correctly
I'm testing only on IOS so these warnings for Android can be ignored.
124-87-17:~ dariocaric$ appium-doctor
info AppiumDoctor Appium Doctor v.1.2.5
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed.
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage
info AppiumDoctor  ✔ HOME is set to: /Users/dariocaric
WARN AppiumDoctor  ✖ ANDROID_HOME is NOT set!
info AppiumDoctor  ✔ JAVA_HOME is set to: /usr/bin/java
WARN AppiumDoctor  ✖ adb could not be found because ANDROID_HOME is NOT set!
WARN AppiumDoctor  ✖ android could not be found because ANDROID_HOME is NOT set!
WARN AppiumDoctor  ✖ emulator could not be found because ANDROID_HOME is NOT set!
info AppiumDoctor  ✔ Bin directory of $JAVA_HOME is set
info AppiumDoctor ### Diagnostic completed, 4 fixes needed. ###
info AppiumDoctor 
info AppiumDoctor ### Manual Fixes Needed ###
info AppiumDoctor The configuration cannot be automatically fixed, please do the following first:
WARN AppiumDoctor - Manually configure ANDROID_HOME.
WARN AppiumDoctor - Manually configure ANDROID_HOME and run appium-doctor again.
info AppiumDoctor ###
info AppiumDoctor 
info AppiumDoctor Bye, run appium-doctor again when all manual fixes have been applied!
info AppiumDoctor 

124-87-17:~ dariocaric$ node -v
v7.2.0

## Environment

* Appium version 1.6.3
* Desktop macOS Sierra 10.12.1
* Node.js version 7.2.1
* Mobile platform/version under test: iOS9.3 and iOS10.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI
* Xcode 8.1 (latest)

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs
This is link to Appium log
https://gist.github.com/dcaric/824b30d905e3724bdb115784616eec1e#file-simpletestinjava

What I can see from this log is this:
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.facebook.IntegrationApp","arguments":[],"environment":{},"shouldWaitForQuiescence":true}}
[debug] [WebDriverAgent] Sim: Dec 13 15:30:00 124-87-17 XCTRunner[23082]: Enqueue Failure: UI Testing Failure - App accessibility isn't loaded /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
[debug] [WebDriverAgent] Sim: Dec 13 15:31:00 124-87-17 XCTRunner[23082]: Enqueue Failure: UI Testing Failure - '<XCUIApplicationImpl: 0x7fdc76ce1320 com.facebook.IntegrationApp>' App state is still not running active, state = XCApplicationStateNotRunning /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.facebook.IntegrationApp application","sessionId":"8EFA9E3E-A9A6-448C-8BC8-DC459BE86519","status":13}
[debug] [XCUITest] Unable to start WebDriverAgent session: An unknown server-side error occurred while processing the command. Original error: Failed to launch com.facebook.IntegrationApp application
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying

But don't know how to fix?

## Code To Reproduce Issue [ Good To Have ]

and this is link to my simple Java test
https://gist.github.com/dcaric/824b30d905e3724bdb115784616eec1e#file-simpletestinjava

**Comment by razor901** [comment]
did you add the xConfigFile to the capabilities?

**Comment by imurchie** [comment]
@razor901 This is a simulator issue, so that is not needed.

**Comment by imurchie** [comment]
May I ask _why_ you are trying to launch that application?

**Comment by dcaric** [comment]
Just to try as a first step, after that I'm planning to write some test form APP on my iPad

**Comment by imurchie** [comment]
The app you are choosing to use is build for a real device, though.

**Comment by dcaric** [comment]
Ok I wil try on iPad

**Comment by dcaric** [comment]
APP was installed (i checked and it is correctly deployed, it can be started manually)
but ..
I got this
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u a79e9243fd45c7000727b9187346ef9fdeedbeab' exited with code 255
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u a79e9243fd45c7000727b9187346ef9fdeedbeab' exited with code 255
[XCUITest] Shutting down sub-processes


and I have latest 
124-87-17:~ dariocaric$ brew install libimobiledevice
Updating Homebrew...
Warning: libimobiledevice-1.2.0 already installed
124-87-17:~ dariocaric$

**Comment by imurchie** [comment]
You'll need the latest: `brew install libimobiledevice --HEAD` (you might need to uninstall the old one to install this one).

**Comment by dcaric** [comment]
OK thx I will in 5-10min

**Comment by dcaric** [comment]
Now with the new libimobiledevice I have to install latest Xcode 8.2 and latest macOS Sierra, it will take a while :)

**Comment by imurchie** [comment]
You should not need either. I am using it right now on OSX 10.11 and Xcode 7.3.

**Comment by dcaric** [comment]
After 
brew install libimobiledevice --HEAD

I got this .....

autom4te: need GNU m4 1.4 or later: /usr/bin/m4
automake: error: autoconf failed with exit status: 1
autom4te: need GNU m4 1.4 or later: /usr/bin/m4
./autogen.sh: line 14: ./configure: No such file or directory
xcodebuild: error: SDK "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk" cannot be located.
clang: error: unable to find utility "clang", not a developer tool or in PATH

READ THIS: https://git.io/brew-troubleshooting


Error: Your Xcode (8.1) is outdated.
Please update to Xcode 8.2 (or delete it).
Xcode can be updated from the App Store.

124-87-17:~ dariocaric$

**Comment by dcaric** [comment]
I think this is an issue related to Sierra 10.12.12 + latest Xcode 8.x (8.2)
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u a79e9243fd45c7000727b9187346ef9fdeedbeab' exited with code 255
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u a79e9243fd45c7000727b9187346ef9fdeedbeab' exited with code 255
[XCUITest] Shutting down sub-processes


ETK-MacBook-Pro:~ dariocaric$ idevicedate -u a79e9243fd45c7000727b9187346ef9fdeedbeab
ERROR: Could not connect to lockdownd, error code -5
ETK-MacBook-Pro:~ dariocaric$ 


https://github.com/libimobiledevice 
is not working 

This was working (I'm sure) with Xcode 8.1 but now with 8.2 it's not working with or without sudo
sudo ideviceinstaller -l -u <UDID>
Could not connect to lockdownd. Exiting.
ETK-MacBook-Pro:OSXTools dariocaric$

**Comment by mykola-mokhnach** [comment]
```
sudo chmod 777 /var/db/lockdown
```

**Comment by syedasadulhaq** [comment]
I got the exact same error with appium 1.6.3 while trying to execute the test cases on real device
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u udid' exited with code 255
idevicedate -u udid
ERROR: Could not connect to lockdownd, error code -5

sudo chmod 777 /var/db/lockdown didn't help.

**Comment by dcaric** [comment]
I did before sudo chmod 777 /var/db/lockdown but doesn't help

**Comment by dcaric** [comment]
OK I did it worked. I was getting errors -5 when I used ideviceinstaller -l -u  UDID so I looked into lockdown.h and -5 means LOCKDOWN_E_SSL_ERROR. I also get ssl error while running ./configure
Apple is using TLS in favour of openssl so I needed to tell configure to use openssl
I found this post useful
https://github.com/libimobiledevice/libimobiledevice/issues/356

I did: (if you don't have installed openssl install it before using "brew install openssl")
===============================================================
- clone https://github.com/libimobiledevice/libimobiledevice
- CFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib ./configure
- make
- make install

After that Appium 1.6.3 (latest so far) worked on the real device with iOS10.2

**Comment by syedasadulhaq** [comment]
Able to solve the problem by reinstalling libimobiledevice
brew uninstall libimobiledevice
brew install libimobiledevice --HEAD
