### ISSUE TITLE
Unhandled endpoint: /session/.. When Running Tests on Web

### ISSUE THREAD

**Issue by razor901** [appium/appium#7522]
## The problem

When testing on iOS device on Web
I get this exception Message : 
Unhandled endpoint: /session/9316971A-DC0D-4633-B6DE-8A73F0073200/url -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/9316971A-DC0D-4633-B6DE-8A73F0073200/url"
    );

Although I can see that the browser starts and loads the default address : apple.com , but then it shuts down and this exception is thrown

## Environment

* Appium version 1.6.1
* Last Appium version that did not exhibit the issue (if applicable):
*MAC OSX 10.11.6
* latest node
* iOS 9.3.3
* Real device 
* Appium CLI 
* xCode 8

## Link to Appium logs

https://gist.github.com/razor901/7e4e8be16c9fe017aefe3660165b40ca

**Comment by razor901** [comment]
My bad I was using the capability browser instead of BrowserName , but after I fixed it,
Safari is launched with appium.io address and I get this loop in the server log : 

```
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
[iOS] Could not find any webviews yet, refreshing/retrying
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
[iOS] Could not find any webviews yet, refreshing/retrying
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
[iOS] Could not find any webviews yet, refreshing/retrying
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugg
```

And even with CTRL & C It won't stop. 

I must mention that on android it is working perfectly . this only happens in iOS 


After waiting about 2 minutes after the SIGNIT this is the final log:
`[XCUITest] Error: Could not navigate to webview; there are none!
    at XCUITestDriver.spinHandles$ (../../../lib/commands/context.js:506:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not navigate to webview; there are none!
    at XCUITestDriver.spinHandles$ (../../../lib/commands/context.js:506:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [JSONWP Proxy] Proxying [DELETE /session/7a8ade57-41ab-4697-b27e-98203c6fdb60] to [DELETE http://localhost:8100/session/48FACEA4-CC75-451B-9636-AEAD59179C84] with no body
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8100
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
`

**Comment by jlipps** [comment]
In the log, it shows you sending in these capabilities

```
[Appium] Capabilities:
[Appium]   app: null
[Appium]   appPackage: 'com.apple.mobilesafari'
[Appium]   appActivity: ''
[Appium]   chromedriverExecutable: '/Users/automation/Desktop/chromedriver/chromedriver'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   browser: 'safari'
[Appium]   bundleId: 'com.apple.mobilesafari'
[Appium]   automationName: 'XCUITest'
[Appium]   xcodeConfigFile: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/xcodeConfigFile.xcconfig'
[Appium]   udid: 'dad43a298ffee62ae138e884422c2934e1e06621'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'dad43a298ffee62ae138e884422c2934e1e06621'
```

Whereas you should be sending these _only_ (note also some that you didn't include):

```
platformName: 'iOS'
platformVersion: '10.0' (or whatever)
deviceName: 'iPhone 6' (or whatever)
automationName: 'XCUITest'
browserName: 'safari'
udid: 'dad43a298ffee62ae138e884422c2934e1e06621'
xcodeConfigFile: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/xcodeConfigFile.xcconfig'
realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
```

Please try with these and report back

**Comment by razor901** [comment]
@jlipps  I fixed that too, I am sending empty app, appPackage, appActivity  & no bundleID .
I still get the same output .

This is the full log : 
https://gist.github.com/razor901/73fa887654828f8659defac99caf2d6a`

**Comment by jlipps** [comment]
And are you running ios-webkit-debug-proxy per the instructions?

**Comment by razor901** [comment]
@jlipps It is installed on my mac , but I'm not sure I'm using it the right way

**Comment by jlipps** [comment]
How are you using it?

**Comment by razor901** [comment]
@jlipps I just run it through another terminal : ios-webkit-debug-proxy 
I see that it is connected to the same device & start the appium server in another terminal

**Comment by jlipps** [comment]
I mean, what is the command you are running to start it? Are you starting it on the port that Appium expects? (27753)

**Comment by razor901** [comment]
@jlipps  Yes this is the command & the output : 
automations-Mac-mini:~ automation$ ios_webkit_debug_proxy -c null:27753
Listing devices on :27753

I didn't specify a device but I put the port which appium expects

**Comment by jlipps** [comment]
pretty sure you have to explicitly give it the right device too?

**Comment by razor901** [comment]
@jlipps gave it the device udid & now it's working .
I thought the device is automatically connected even if I dont specify it .

Thanks anyway :)

**Comment by jlipps** [comment]
Glad we could track it down.

**Comment by imurchie** [comment]
Please give the Appium server logs as a link to a [gist](https://gist.github.com). Without them we cannot do anything.

**Comment by kailo777** [comment]
@imurchie 
Here is the Appium Serverlog
[gist](https://gist.github.com/kailo777/6e1dbb0d4d4f251f3116da00f50144cd )

**Comment by imurchie** [comment]
Thanks.

I guess I don't understand what your problem is, from these logs. I don't see the problem in this issue that you are having.

What I see is that you are starting a new session in the middle of an old one.

**Comment by kailo777** [comment]
Thanks @imurchie  

It looks like that my selenium hub lose connection to the selenium node. 

Hub Debug Information: 

19:06:16.384 DEBUG - Failed to check status of node: Read timed out
19:06:16.385 INFO - Marking the node http://MBMU001:4723 as down: cannot reach the node for 2 tries

As a result of this he try to open a new connection that would explain my logs. 

Thank you for that now I'm a little step further.

**Comment by imurchie** [comment]
If this persists, please open a new issue. It has nothing to do with the one described in this issue, and continuing here makes it very difficult to use the issue for reference.
