### ISSUE TITLE
XCUITest does not support drag and drop

### ISSUE THREAD

**Issue by PiotrNestor** [appium/appium#7523]
## The problem

XCUITest does not support drag and drop action according to the action example

```
        action = TouchAction(self._d)
        action.long_press(_from_account).move_to(_to_account).release().perform()
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.12.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.1.1
* Real device or emulator/simulator: real device iPhone 5s
* Appium CLI or Appium.app|exe:

## Details

The error reply:
WebDriverException: Message: Support for this gesture is not yet implemented. Please contact an Appium dev

## Link to Appium logs

[debug] [XCUITest] Received the following touch action: longPress-moveTo-release
[HTTP] <-- POST /wd/hub/session/6a5caaab-1ecd-478d-9908-407932418ad4/touch/perform 501 16 ms - 164 

## Code To Reproduce Issue [ Good To Have ]

```
        action = TouchAction(self._d)
        action.long_press(_from_account).move_to(_to_account).release().perform()
```

**Comment by imurchie** [comment]
Where is the action example? Drag and drop needs a `wait` to be properly mapped.

**Comment by duonganhthu43** [comment]
I have the same issue with appium version 1.6.3  Even if i add "Wait" 500 miliseconds, error is still there

 
`   var customAction = new TouchAction(_driver as IPerformsTouchActions);
                customAction.LongPress(coordinateX, coordinateY).Wait(500).MoveTo(coordinateX + 20, coordinateY).Release().Perform();
                `

**Comment by PiotrNestor** [comment]
OK. I've added wait

```
        action = TouchAction(self.driver)
        action.long_press(_from_account).wait(1000).move_to(_to_account).release().perform()
```
Result:
WebDriverException: Message: Support for this gesture is not yet implemented. Please contact an Appium dev

The appium log: 
```
[HTTP] --> POST /wd/hub/session/84f9b8ca-0194-44a4-a01a-a68f0e8a0490/touch/perform {"sessionId":"84f9b8ca-0194-44a4-a01a-a68f0e8a0490","actions":[{"action":"longPress","options":{"y":null,"x":null,"duration":1000,"element":"9A34512D-2417-4717-9E05-3E739267F2BA"}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"y":null,"x":null,"element":"37E9CB4D-FEBC-43B0-8D9D-76F752B67B3F"}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"y":null,"x":null,"duration":1000,"element":"9A34512D-2417-4717-9E05-3E739267F2BA"}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"y":null,"x":null,"element":"37E9CB4D-FEBC-43B0-8D9D-76F752B67B3F"}},{"action":"release","options":{}}],"84f9b8ca-0194-44a4-a01a-a68f0e8a0490"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: longPress-wait-moveTo-release
[HTTP] <-- POST /wd/hub/session/84f9b8ca-0194-44a4-a01a-a68f0e8a0490/touch/perform 501 22 ms - 164 
```

**Comment by PiotrNestor** [comment]
OK the following action actually works:
```
action = TouchAction(self.driver)
        action.press(_from_account).wait(1000).move_to(_to_account).release().perform()
``
