### ISSUE TITLE
Exception in findElement when using automationName=uiautomator2

### ISSUE THREAD

**Issue by ptsiakos77** [appium/appium#7524]
Appium Version: 1.6.3
I set automationName=uiautomator2

The exception below is thrown in findElement

An unknown server-side error occurred while processing the command. Original error: org.w3c.dom.DOMException: android.support.v7.app.ActionBar$Tab at org.apache.harmony.xml.dom.NodeImpl.setName(NodeImpl.java:286) at org.apache.harmony.xml.dom.ElementImpl.(ElementImpl.java:56) at org.apache.harmony.xml.dom.DocumentImpl.createElement(DocumentImpl.java:344) at org.apache.harmony.xml.dom.DocumentImpl.createElement(DocumentImpl.java:48) at io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:150) at io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140) at io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179) at io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140) at io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179) at io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140) at io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179) at io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140) at io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179) at io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140) at io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179) at io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140) at io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179) at io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140) at io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179) at io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140) at io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179) at io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140) at io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179) at io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140) at io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179) at io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140) at io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179) at io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140) at io.appium.uiautomator2.model.XPathFinder.buildDomNode(XPathFinder.java:179) at io.appium.uiautomator2.model.XPathFinder.getDomNode(XPathFinder.java:140) at io.appium.uiautomator2.model.XPathFinder.find(XPathFinder.java:88) at io.appium.uiautomator2.model.XPathFinder.getNodesList(XPathFinder.java:120) at io.appium.uiautomator2.handler.FindElements.getXPathUiObjects(FindElements.java:61) at io.appium.uiautomator2.handler.FindElements.findElements(FindElements.java:140) at io.appium.uiautomator2.handler.FindElements.safeHandle(FindElements.java:85) at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:54) at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:201) at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:192) at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911) at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611) at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) at java.lang.Thread.run(Thread.java:818) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 983 milliseconds Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06' System info: host: 'Panagiotiss-MacBook-Pro.local', ip: '10.9.43.25', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_101' Driver info: io.appium.java_client.android.AndroidDriver Capabilities [{appActivity=com.workable.sign_in.WelcomeActivity, app=/Users/panagiotistsiakos/jenkins-slave/workspace/build-android-qa/app/build/outputs/apk/app-stg4.apk, recreateChromeDriverSessions=true, noReset=true, platformVersion=5.1.1, automationName=uiautomator2, platformName=Android, udid=42008bb6d2332325, deviceName=42008bb6d2332325, platform=ANY}] Session ID: 3a306be7-22ea-4e20-98a9-e1bebd9d3fc8 *** Element info: {Using=xpath, value=//*[contains(@text,'Candidates')]}

**Comment by mykola-mokhnach** [comment]
replace your xpath locator with 

```
//*[contains(.,'Candidates')]
```

**Comment by sravanmedarapu** [comment]
W3C API unable to create DOM element with special characters (in this case class name contains **`$`** ). Will update here once issue is fixed.

**Comment by sravanmedarapu** [comment]
should work with appium-uiautomator2-driver v0.2.6

**Comment by zademaxfield** [comment]
Is there an easy way to install appium-uiautomator2-driver v0.2.6 while running appium 1.6.3?

**Comment by imurchie** [comment]
Either re-install using `npm unisntall -g appium && npm install -g appium --no-shrinkwrap`, or find where Appium is installed, `cd` there, and run `npm install appium-uiautomator2-driver`.

**Comment by zademaxfield** [comment]
I did npm unisntall -g appium && npm install -g appium --no-shrinkwrap and it fixed the problem for me.
Thanks!

**Comment by ohadschn** [comment]
@imurchie I had to issue `npm install appium-uiautomator2-driver@latest`.
