### ISSUE TITLE
npm install -g appium fails for 1.6.1, 1.6.2, 1.6.3

### ISSUE THREAD

**Issue by magleahy** [appium/appium#7525]
## npm install -g appium fails for 1.6.1, 1.6.2, 1.6.3

Please see https://github.com/npm/npm/issues/15210 for more details. 
You mentioned shrinkwrap as a reason for 1.6.3 and this was mentioned in the npm debug log: 

30098 silly cleanup remove extracted module
30099 verbose stack TypeError: Cannot read property 'deep-extend' of undefined
30099 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:35:40
30099 verbose stack     at Array.filter (native)
30099 verbose stack     at inflateShrinkwrap (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:34:49)
30099 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:16
30099 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
30099 verbose stack     at zalgoSafe (/usr/local/lib/node_modules/npm/node_modules/dezalgo/dezalgo.js:20:10)
30099 verbose stack     at finalize (/usr/local/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:39:5)
30099 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/realize-package-specifier/index.js:22:20
30099 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:276:29
30099 verbose stack     at FSReqWrap.oncomplete (fs.js:111:15)
30100 verbose cwd /Users/magleahy/Desktop/projects/client/App
30101 error Darwin 16.0.0
30102 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appium@1.6.3"
30103 error node v7.2.0
30104 error npm  v4.0.3
30105 error Cannot read property 'deep-extend' of undefined
30106 error If you need help, you may report this error at:
30106 error     <https://github.com/npm/npm/issues>
30107 verbose exit [ 1, true ]

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable): 1.6.0-beta3
* Desktop OS/version used to run Appium: MacOS Sierra
* Node.js version (unless using Appium.app|exe): See npm ticket linked above

**Comment by jlipps** [comment]
This is an npm bug, please try the following:

```
npm uninstall -g appium
npm install -g npm@4.0.5
npm install -g appium
```

**Comment by magleahy** [comment]
You are an impressive responder @jlipps! 

I did this and can confirm that npm@4.0.5 works for 1.6.3.

Hopefully npm will follow up on their ticket which is npm/npm#15210.

Many thanks. :)

**Comment by jlipps** [comment]
You're welcome! You got lucky because I ran into this myself yesterday and had to figure out that there was a new version of npm which fixed it :-)

**Comment by magleahy** [comment]
The luck of the Irish!

**Comment by jlipps** [comment]
🍀

**Comment by zkat** [comment]
🌊 hey y'all. Just popping in to link https://github.com/npm/npm/pull/15082 as the root-cause fix for this issue. 👍

**Comment by skhanam** [comment]
Hi there,

I am upgrading from appium version 1.4.X to 1.6.3 

npm uninstall -g appium
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "uninstall" "-g" "appium"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:


Is this issue relating to npm or appium ?
