### ISSUE TITLE
Be able to retrieve the app though an appURL instead of an appPath

### ISSUE THREAD

**Issue by bcivel** [appium/appium#7526]
Is it possible to retrieve the application through an URL instead of path (For example --app=http://mymedia/myapplication/latest) ? 

Would it be supported or is it definitelly not something that you would do?

* Appium 1.6.3-SNAPSHOT

**Comment by jlipps** [comment]
You can already set the `app` capability to a url. It needs to end with `.apk` or `.app.zip`.
