### ISSUE TITLE
appium 1.6.3 can't run tests

### ISSUE THREAD

**Issue by bily621** [appium/appium#7529]
## The problem

i use appium 1.6.3 to run ios test,  occur an exception "org.apache.http.NoHttpResponseException: 127.0.0.1:4723 failed to respond"

## Environment

* Appium version : 1.6.3
* mac os :10.11.6
* Node.js version :4.4.3
* Real device or emulator/simulator: real device
* ios version : 9.3.4
* java_client version: 4.1.2
* xcode version :8.1

## Details

org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'guyandeMacBook-Pro.local', ip: '172.17.37.170', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_45'
Driver info: driver.version: IOSDriver

	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:36)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:114)
	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:132)
	at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:82)
	at com.example.IOSTest.init(IOSTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.NoHttpResponseException: 127.0.0.1:4788 failed to respond
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'

## Link to Appium logs

[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] Session created with session id: 67fbae9d-9624-4781-bc8e-19750612c3df
[debug] [XCUITest] Xcode version set to '8.1'
[debug] [XCUITest] iOS SDK Version set to '10.1'
[debug] [XCUITest] Available devices: ea3f18d9e5b2a94be76a99890349e14500a15b7a
[debug] [XCUITest] Creating iDevice object with udid ea3f18d9e5b2a94be76a99890349e14500a15b7a
[XCUITest] Determining device to run tests on: udid: 'ea3f18d9e5b2a94be76a99890349e14500a15b7a', real device: true
[debug] [XCUITest] App is an iOS bundle, will attempt to run as pre-existing
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger '/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/deviceconsole/deviceconsole'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=ea3f18d9e5b2a94be76a99890349e14500a15b7a -configuration Debug' in directory '/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/gy/Library/Developer/Xcode/DerivedData/WebDriverAgent-eeheqhhyhaecndefwtmhbvxathyj/Logs/Test/A8605F6B-DA8D-4DC3-8CDB-20DEEAFE48C2/Session-WebDriverAgentRunner-2016-12-14_112839-b6mssI.log
[debug] [WebDriverAgent] Device: Dec 14 11:28:46 guafeide-iPhone XCTRunner[244] <Warning>: Running tests...
[debug] [WebDriverAgent] Device: Dec 14 11:28:48 guafeide-iPhone XCTRunner[244] <Warning>: Continuing to run tests in the background with task ID 1
[debug] [WebDriverAgent] Device: Dec 14 11:28:49 guafeide-iPhone kernel[0] <Notice>: Sandbox: XCTRunner(244) deny(1) file-write-data /private/var/mobile/Library/Preferences/com.apple.Accessibility.plist
[debug] [WebDriverAgent] Device: Dec 14 11:28:49 guafeide-iPhone XCTRunner[244] <Warning>: Built at Dec 13 2016 18:05:39
[debug] [WebDriverAgent] Device: Dec 14 11:28:49 guafeide-iPhone XCTRunner[244] <Warning>: ServerURLHere->http://172.17.38.252:8100<-ServerURLHere
[debug] [WebDriverAgent] Device: Dec 14 11:28:49 guafeide-iPhone XCTRunner[244] <Warning>: Listening on USB
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding -[DOMNode _moveRight:withHistory:]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding -[DOMNode _moveLeft:withHistory:]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding -[DOMNode _updateSelectionWithTextRange:withAffinityDownstream:]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding +[DOMNode safeCategoryBaseClass]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding -[UIWebFormAccessory initWithFrame:]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding -[UIWebFormAccessory _accessibilityLoadAccessibilityInformation]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding +[UIWebFormAccessory safeCategoryBaseClass]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding +[UIWebFormSelectPeripheral safeCategoryBaseClass]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding +[UIWebFormSelectPeripheral createPeripheralWithDOMHTMLSelectElement:]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding -[UIWebSelectSinglePicker _accessibilityServesAsFirstElement]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding +[UIWebSelectSinglePicker safeCategoryBaseClass]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding -[UIWebSelectMultiplePicker _accessibilityServesAsFirstElement]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding +[UIWebSelectMultiplePicker safeCategoryBaseClass]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding -[UIWebPlugInView webPlugInStart]
[debug] [WebDriverAgent] Device: Dec 14 12:15:52 guafeide-iPhone XCTRunner[248] <Warning>: UIAccessibility Error adding +[UIWebPlugInView safeCategoryBaseClass]

## Code To Reproduce Issue [ Good To Have ]

        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "9.3.4");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "“guafei”的 iPhone");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");
        capabilities.setCapability(MobileCapabilityType.APP,"com.jg.mgjdev");
            capabilities.setCapability("realDeviceLogger","/Users/gy/WorkSpaces/nvm/versions/node/v4.4.3/lib/node_modules/deviceconsole/deviceconsole");
        capabilities.setCapability(MobileCapabilityType.UDID,"ea3f18d9e5bzsxcbe76a99890349e14500a15b7a");
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,"XCUITest");
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT,60);
        driver = new IOSDriver<>(new URL("http://127.0.0.1:4788/wd/hub"), capabilities);

**Comment by mykola-mokhnach** [comment]
org.openqa.selenium.remote.UnreachableBrowserException means that the client is unable to detect appium server running on the given host/port. Pay attention to your test setup.

Closing as non Appium-related issue. The forum is a better place to solve such things.
