### ISSUE TITLE
Freeze when using wait

### ISSUE THREAD

**Issue by PeterGolf** [appium/appium#7533]
## The problem

After updating to 1.6.3 i have problems with wait. When i use wait.until(Expected.....) i have a freeze.

## Environment

appium 1.6.3
iphone - real device
IOS - 10.2

## Link to Appium logs

https://gist.github.com/PeterGolf/a7b71b31085e1cc14b760e6acad96d6e

## Code To Reproduce Issue [ Good To Have ]

public TestPage(IOSDriver driver, WebDriverWait wait) throws InterruptedException {
       super(driver, wait);
       ((IOSElement) driver.findElement(By.xpath(CLOSE_TUTORIAL_BUTTON_LOCATOR))).tap(1, 1);      this.wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath(LOCATOR)));
   }

**Comment by mykola-mokhnach** [comment]
Check the device log whether you see anything similar to [this](https://github.com/facebook/WebDriverAgent/issues/372) there.

**Comment by PeterGolf** [comment]
@mykola-mokhnach i can't see device logs :(

**Comment by mykola-mokhnach** [comment]
Please reopen when you have logs. Otherwise it's not possible to help.
