### ISSUE TITLE
uiautomator2 - How download drivers from a local server ?

### ISSUE THREAD

**Issue by marcbuils** [appium/appium#7534]
## The problem

I can't install appium 1.6.2 on a computer without direct internet access.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.2
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS X 10.12.1
* Node.js version (unless using Appium.app|exe): v6.9.1
* Mobile platform/version under test: 
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

I can't install appium 1.6.2 on a computer without direct internet access because I can'nt download the appium-uiautomator-server.

## Link to Appium logs

```
dbug AndroidDriver Getting Java version
info AndroidDriver Java version is: 1.8.0_92
info UiAutomator2 downloading UiAutomator2 Server APK v0.0.7 : https://github.com/appium/appium-uiautomator2-server/releases/download/v0.0.7/appium-uiautomator2-server-v0.0.7.apk
info UiAutomator2 downloading UiAutomator2 Server test APK v0.0.7 : https://github.com/appium/appium-uiautomator2-server/releases/download/v0.0.7/appium-uiautomator2-server-debug-androidTest.apk
(node:26580) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Unable to import and run the installer. If you're running from source, run `gulp transpile` and then re-run `npm install`
```

full logs: https://gist.github.com/marcbuils/3db92b8dbd57e7731ae6420a82e7027e

## Code To Reproduce Issue [ Good To Have ]

```bash
npm install appium@1.6.2
```

**Comment by sravanmedarapu** [comment]
published in 0.2.4

#https://github.com/appium/appium-uiautomator2-driver/pull/56
