### ISSUE TITLE
Appium 1.6.3 iOS find_element from within an element does not seem to work

### ISSUE THREAD

**Issue by darragk** [appium/appium#7536]
## The problem

This worked fine in Appium 1.6.0 beta 3  - but now it cannot locate elements within elements. E.g. I am doing the following off of the "shot" object - which is an element I found already: I am using Ruby:

shot.find_element(xpath: ".//XCUIElementTypeOther[@label='Shot Closed View']")

This cannot find the element. But when I get the page source I can see it definitely exists.
## Environment

* Appium version 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.6.0 beta 3 ( Note I upgraded straight to 1.6.3 so not sure about appium versions in between)
* Desktop OS/version used to run Appium: Mac 10.11.6
* Node.js version (unless using Appium.app|exe): v5.10.0
* Mobile platform/version under test: iPhone SE OS 10.2
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs
Not really applicable - as not giving any errors. Just not finding the above element

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
What if you remove starting dot from your xpath?

**Comment by darragk** [comment]
It works without the dot. Tried everything except that!

Many thanks.
