### ISSUE TITLE
Appium unable to locate elements - sporadic issues - also unable to get page source Xcode 8.2

### ISSUE THREAD

**Issue by darragk** [appium/appium#7538]
## The problem

Hi I am struggling a bit with iOS tests at the moment - on the new XCUI strategy. I am running tests on a real device - need to do this because the app involves taking videos and photos.  I understand that running on real devices is a bit flakey with the XCUI strategy?  I kept getting the described issues "Enqueue Failure: UI Testing Failure " ALOT - but seems to be in different places. I have upgraded everything I can think of. Now appium logs no longer show above scary issues, but still seem to just give up trying to locate elements. 

It's weird but sometimes when the test runs, it finds the element, sometimes it does not.  I notice that when it fails, sometimes it helps to get the page source before that bit in the test. And indeed sometimes it takes minutes (sometimes over 5) just to get the page source (and other times, it gets it straight away). But if it manages to get the page source, it does usually  find the element.  In other places where it sporadically fails, I do a get page source and it fails to even do this. 

I am not sure why it is so slow in getting the source. 

It seems to be mainly an issue with xpath locators - which on the whole I avoid using, but sometimes it's the only way. . but it feels like the issue is in getting the xml?? 

Anyway I got the below error from web driver when I tried to get the page source on the page which is having the issues:

An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT (Selenium::WebDriver::Error::UnknownError)

## Environment

Appium version 1.6.3
Last Appium version that did not exhibit the issue (if applicable): N/A
Desktop OS/version used to run Appium: Mac 10.11.6
Node.js version (unless using Appium.app|exe): v5.10.0
Mobile platform/version under test: iPhone SE OS 10.2
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: CLI

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

https://gist.github.com/darragk/7f1c688f336f12c4ec4db6d1847c884b

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Known WDA [issue](https://github.com/facebook/WebDriverAgent/issues/372)
There's nothing we can de here.
