### ISSUE TITLE
can anyone one please point me to documentation or example for launching appium server programmatically for appium 1.6.3

### ISSUE THREAD

**Issue by kumarmp4git** [appium/appium#7544]
HI,
Am trying to test on 2 iOS devices simultaneously as we have requirement to do operation on one phone and verify on the other. so trying to launch appium server and create 2 iosDrivers. please help.

Env: 
iPhone 5c and iPhone 6
1. iOS 10.1.1
2. iOS 9.3.4 or 8.2

**Comment by mykola-mokhnach** [comment]
This is a place for issues. Please use Appium forum if you need to get suggestions, help, etc.

**Comment by kumarmp4git** [comment]
Thanks..
