### ISSUE TITLE
Appium 1.6.3: Android: App: Splash screen but app does not launch for e2e tests

### ISSUE THREAD

**Issue by magleahy** [appium/appium#7549]
## The problem

When I run my e2e test on Android device, plugged into my Mac, the app splash screen launches, but the app itself does not. The commands are kicked off via a gulp file on the command line. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: macOS Sierra 
* Node.js version (unless using Appium.app|exe): 7.2.0
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device - Nexus 6
* Appium CLI or Appium.app|exe: CLI
* npm version: 4.0.5

## Config Capabilities
```
    capabilities: {
        app: apk,
        automationName: 'Appium',
        autoWebview: true,
        browserName: '',
        deviceName: 'Android',
        dontStopAppOnReset: true,
        enablePerformanceLogging: true,
        fullReset: true,
        nativeWebScreenshot: true,
        newCommandTimeout: 120,
        platformName: 'Android',
        platformVersion: '7.0',
        udid: getFirstDeviceFromAdb()
    },
```

## Link to Appium logs

https://gist.github.com/magleahy/1b9b57682057aaa09910dadbb29ac0b3

This feels like it is not enough info., but hoping anyway!

**Comment by magleahy** [comment]
@jlipps I call out to your greatness :)

**Comment by ahmetkocu** [comment]
I have same issue.

**Comment by jlipps** [comment]
sorry @magleahy I guess my greatness took a 4-month break :-) I looked at your logs, and nothing looks out of the ordinary. Other than that immediately after starting the session and setting an async script timeout, your client code ends the session. No further commands are sent. Can you try upgrading to 1.6.4 to see if the problem still persists?
