### ISSUE TITLE
Swipe to right using moveTo function not working

### ISSUE THREAD

**Issue by dilsreccse** [appium/appium#7550]
## The problem
Unable to perform right swipe in landscape mode. Whereas left swipe working fine. i'm using touch action press & move to action to perform swipe.  
please find the code below in  "Code To Reproduce Issue"  Section. 
i tried location based swipe, encountering the same with it  i.e unable to move towards right side. 

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:MAC
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:iOS 9.3.5
* Real device or emulator/simulator:Real
* Appium CLI or Appium.app|exe:CLI

## Details
Basically i have three carousel in my application landing page, I'm in the middle carousel & trying to move to right side carousel  [Not Working] whereas from the middle carousel i'm able to move to left carousel fine.

## Link to Appium logs
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/orientation] to [POST http://localhost:8100/session/EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255/orientation] with body: {"orientation":"LANDSCAPE"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255","value":{},"status":0}
[JSONWP Proxy] Replacing sessionId EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255 with 9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670
[HTTP] <-- POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/orientation 200 3842 ms - 74 
[HTTP] --> POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element {"using":"accessibility id","value":"Open in My Folders"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["accessibility id","Open in My Folders","9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255/element] with body: {"using":"accessibility id","value":"Open in My Folders"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255","value":{"label":"Open in My Folders","type":"XCUIElementTypeButton","ELEMENT":"00F31176-462C-4B97-84A6-8A1D722A1B00"},"status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"label":"Open in My Folders","type":"XCUIElementTypeButton","ELEMENT":"00F31176-462C-4B97-84A6-8A1D722A1B00"}
[HTTP] <-- POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element 200 3570 ms - 182 
[HTTP] --> POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element {"using":"accessibility id","value":"Open in My Folders"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["accessibility id","Open in My Folders","9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255/element] with body: {"using":"accessibility id","value":"Open in My Folders"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255","value":{"label":"Open in My Folders","type":"XCUIElementTypeButton","ELEMENT":"959F427E-1FD3-4995-A8DD-0CA96EE68193"},"status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"label":"Open in My Folders","type":"XCUIElementTypeButton","ELEMENT":"959F427E-1FD3-4995-A8DD-0CA96EE68193"}
[HTTP] <-- POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element 200 3541 ms - 182 
[HTTP] --> POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element {"using":"accessibility id","value":"My Folders"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["accessibility id","My Folders","9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255/element] with body: {"using":"accessibility id","value":"My Folders"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255","value":{"label":"My Folders","type":"XCUIElementTypeStaticText","ELEMENT":"E6DE4286-15A1-4B1A-8779-81553BDEDA36"},"status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"label":"My Folders","type":"XCUIElementTypeStaticText","ELEMENT":"E6DE4286-15A1-4B1A-8779-81553BDEDA36"}
[HTTP] <-- POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element 200 3559 ms - 178 
[HTTP] --> POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element {"using":"accessibility id","value":"My Folders"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["accessibility id","My Folders","9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255/element] with body: {"using":"accessibility id","value":"My Folders"}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255","value":{"label":"My Folders","type":"XCUIElementTypeStaticText","ELEMENT":"0EEFABDB-C021-4CD6-A2AE-856D03C72F82"},"status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"label":"My Folders","type":"XCUIElementTypeStaticText","ELEMENT":"0EEFABDB-C021-4CD6-A2AE-856D03C72F82"}
[HTTP] <-- POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element 200 3599 ms - 178 
[HTTP] --> GET /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element/959F427E-1FD3-4995-A8DD-0CA96EE68193/location {}
[debug] [MJSONWP] Calling AppiumDriver.getLocation() with args: ["959F427E-1FD3-4995-A8DD-0CA96EE68193","9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670"]
[debug] [XCUITest] Executing command 'getLocation'
[debug] [JSONWP Proxy] Proxying [GET /element/959F427E-1FD3-4995-A8DD-0CA96EE68193/rect] to [GET http://localhost:8100/session/EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255/element/959F427E-1FD3-4995-A8DD-0CA96EE68193/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"sessionId\" : \"EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255\",\n  \"value\" : {\n    \"y\" : 188,\n    \"width\" : 140,\n    \"x\" : 801,\n    \"height\" : 32\n  },\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getLocation() result: {"x":801,"y":188}
[HTTP] <-- GET /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element/959F427E-1FD3-4995-A8DD-0CA96EE68193/location 200 1977 ms - 89 
[HTTP] --> GET /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element/959F427E-1FD3-4995-A8DD-0CA96EE68193/location {}
[debug] [MJSONWP] Calling AppiumDriver.getLocation() with args: ["959F427E-1FD3-4995-A8DD-0CA96EE68193","9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670"]
[debug] [XCUITest] Executing command 'getLocation'
[debug] [JSONWP Proxy] Proxying [GET /element/959F427E-1FD3-4995-A8DD-0CA96EE68193/rect] to [GET http://localhost:8100/session/EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255/element/959F427E-1FD3-4995-A8DD-0CA96EE68193/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"sessionId\" : \"EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255\",\n  \"value\" : {\n    \"y\" : 188,\n    \"width\" : 140,\n    \"x\" : 801,\n    \"height\" : 32\n  },\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getLocation() result: {"x":801,"y":188}
[HTTP] <-- GET /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element/959F427E-1FD3-4995-A8DD-0CA96EE68193/location 200 1989 ms - 89 
[HTTP] --> GET /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element/0EEFABDB-C021-4CD6-A2AE-856D03C72F82/location {}
[debug] [MJSONWP] Calling AppiumDriver.getLocation() with args: ["0EEFABDB-C021-4CD6-A2AE-856D03C72F82","9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670"]
[debug] [XCUITest] Executing command 'getLocation'
[debug] [JSONWP Proxy] Proxying [GET /element/0EEFABDB-C021-4CD6-A2AE-856D03C72F82/rect] to [GET http://localhost:8100/session/EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255/element/0EEFABDB-C021-4CD6-A2AE-856D03C72F82/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"sessionId\" : \"EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255\",\n  \"value\" : {\n    \"y\" : 195,\n    \"width\" : 85,\n    \"x\" : 123,\n    \"height\" : 19\n  },\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getLocation() result: {"x":123,"y":195}
[HTTP] <-- GET /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element/0EEFABDB-C021-4CD6-A2AE-856D03C72F82/location 200 1977 ms - 89 
[HTTP] --> GET /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element/0EEFABDB-C021-4CD6-A2AE-856D03C72F82/location {}
[debug] [MJSONWP] Calling AppiumDriver.getLocation() with args: ["0EEFABDB-C021-4CD6-A2AE-856D03C72F82","9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670"]
[debug] [XCUITest] Executing command 'getLocation'
[debug] [JSONWP Proxy] Proxying [GET /element/0EEFABDB-C021-4CD6-A2AE-856D03C72F82/rect] to [GET http://localhost:8100/session/EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255/element/0EEFABDB-C021-4CD6-A2AE-856D03C72F82/rect] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"sessionId\" : \"EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255\",\n  \"value\" : {\n    \"y\" : 195,\n    \"width\" : 85,\n    \"x\" : 123,\n    \"height\" : 19\n  },\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getLocation() result: {"x":123,"y":195}
[HTTP] <-- GET /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/element/0EEFABDB-C021-4CD6-A2AE-856D03C72F82/location 200 1991 ms - 89 
[HTTP] --> POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/touch/perform {"actions":[{"action":"press","options":{"x":821,"y":208}},{"action":"moveTo","options":{"x":143,"y":215}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":821,"y":208}},{"action":"moveTo","options":{"x":143,"y":215}},{"action":"release","options":{}}],"9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-moveTo-release
[debug] [JSONWP Proxy] Proxying [POST /uiaTarget/0/dragfromtoforduration] to [POST http://localhost:8100/session/EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255/uiaTarget/0/dragfromtoforduration] with body: {"fromX":821,"fromY":208,"toX":964,"toY":423,"duration":0}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255","value":{},"status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/touch/perform 200 11944 ms - 74 
[HTTP] --> POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/touch/perform {"actions":[{"action":"press","options":{"x":143,"y":215}},{"action":"moveTo","options":{"x":821,"y":208}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":143,"y":215}},{"action":"moveTo","options":{"x":821,"y":208}},{"action":"release","options":{}}],"9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-moveTo-release
[debug] [JSONWP Proxy] Proxying [POST /uiaTarget/0/dragfromtoforduration] to [POST http://localhost:8100/session/EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255/uiaTarget/0/dragfromtoforduration] with body: {"fromX":143,"fromY":215,"toX":964,"toY":423,"duration":0}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"EF6EE8C9-E6E1-4FEB-A4BB-22CF44AFB255","value":{},"status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/9d08a9d4-dcd9-4dbb-88b9-bf93ce69a670/touch/perform 200 16286 ms - 74

## Code To Reproduce Issue [ Good To Have ]

TouchAction tAction=new TouchAction(ElementsAction.driver);
WebElement sE=driver.findElementByAccessibilityId("Open in My Folders");
WebElement eE=driver.findElementByAccessibilityId("My Folders");		int startx = sE.getLocation().getX();
int starty = sE.getLocation().getY();
int endx = eE.getLocation().getX();
int endy = eE.getLocation().getY();
System.out.println(startx + " ::::::: " + starty + " ::::::: " + endx +  " ::::::: " +	endy);
//First tap on the screen and swipe it right using moveTo function [NOT Working]
tAction.press(startx+20,starty+20).moveTo(endx+20,endy+20).release().perform(); 
Thread.sleep(1000);
//Second tap on the screen and swipe it left using moveTo function[Working]
tAction.press(endx+20,endy+20).moveTo(startx+20,starty+20).release().perform();

**Comment by dilsreccse** [comment]
in iPad iOS 10 devices, i'm not to do both the swipe :( right swipe doesnt nothing on the device, whereas left swipe is partially done, control remains in the middle  carousel only :( please help !

**Comment by jlipps** [comment]
@mykola-mokhnach could this be related to gesture recognition issues in landscape mode?

**Comment by pengboZheng** [comment]
I am using portrait mode on iPhone 6, instead of swipe to left, it clicked into the cell

**Comment by jlipps** [comment]
@dilsreccse why doesn't your action chain code have a 'wait' action? You need this to say how long the duration of the swipe is...

**Comment by dilsreccse** [comment]
@jlipps : You mean the below  waitAction? tAction.press(startx+20,starty+20).moveTo(endx+20,endy+20).waitAction().release().perform();

**Comment by dilsreccse** [comment]
driver.swipe(92, 730,102, 176,1) was scrolling along left side of the screen in the earlier version of appium 1.6, now when i use this co-ordinates in Appium 1.6.3 , its scrolling in the middle of the screen :( so i'm unable to scroll through the section that are available in the left pane :( as this is not working i'm trying to use the press moveTo TouchAction, no use its also not working :(

**Comment by qakapil** [comment]
Swipes are not working for me also in Landscape mode. They do work fine in Portrait. I am using Appium 1.6.3. Is this a known issue ? 

Here is the code snippet which I am using to perform swipe  - 

action = TouchAction(self)
        action \
            .press(x=start_x, y=start_y) \
            .wait(ms=duration) \
            .move_to(x=end_x, y=end_y) \
            .release()
        action.perform()

**Comment by qakapil** [comment]
ok turns out it is a known issue - https://github.com/appium/appium/issues/7566
Looks like exchanging x and y co-ordinates is a workaround for now....

**Comment by dilsreccse** [comment]
I tried that, its not working , will the next appium release will resolve the swipe issues ??

**Comment by pb-z** [comment]
Hopefully, 1.6.4 will get this issue fixed (https://github.com/appium/appium/issues/7573)

**Comment by jlipps** [comment]
closing in favor of #7573.

**Comment by syedasadulhaq** [comment]
when 1.6.4 will be available?

**Comment by dilsreccse** [comment]
Tried swipe using 1.6.4 beta version, in that swipe from bottom to top is not working, [Gist Here](https://gist.github.com/dilsreccse/a9682d833be0bad968852caa5dabc2cc) .

**Comment by mykola-mokhnach** [comment]
@dilsreccse We are currently working on driver additions for iOS, so gestures will be more reliable in the recent beta. We'll add more documentation and examples on that as soon as all the necessary changes are tested and merged
