### ISSUE TITLE
Appium 1.6.3 find_element by xpath locator strategy not working(at least on android)

### ISSUE THREAD

**Issue by hardik-d** [appium/appium#7551]
I am getting error:

"Selenium::WebDriver::Error::TimeOutError:
       timed out after 10 seconds (An element could not be located on the page using the given search parameters.)"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac OS X EL Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): v5
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: N/A

piece of code that is failing:

    set_context "NATIVE_APP"
    within_context('NATIVE_APP') do
      wait_true(10) { @driver.find_element(:xpath, "//text[@value='7-Eleven']").displayed? }
      @driver.find_element(:xpath, "//text[@value='7-Eleven']").click
    end

capabilities:

opts = {caps: {
          platformName: 'Android',
          udid: ENV["UDID"],
          deviceName: "Android Emulator",
          appPackage: 'com.paynearme.consumer.dev',
          appActivity: 'com.paynearme.android.pnmc.MobileConsumer',
          appWaitActivity: 'com.paynearme.android.pnmc.MobileConsumer',
          dontStopAppOnReset: 'true',
          app: '~/android-pnminc-dev-debug.apk'
      }, appium_lib: { port: ENV["PORT"].present? ? ENV["PORT"] : "4723" }
      }

appium inspector screen shot:

<img width="209" alt="screen shot 2016-12-15 at 3 17 15 pm" src="https://cloud.githubusercontent.com/assets/7215179/21246117/8da8e404-c2db-11e6-8870-29ccd3957085.png">

appium logs:

https://gist.github.com/hardik-d/93f1a0e1feed00ed15ae5f5dffb1c36f

**Comment by jlipps** [comment]
`text` is not a valid android classname. it's an attribute. You should print the source and make sure the xpath query you're constructing matches that. what you probably want is something more like:

```
//android.widget.TextView[@text='7-Eleven']
```
