### ISSUE TITLE
iOS: automationName XCUITest not part of Appium,Selendroid,WebDriverAgent. 

### ISSUE THREAD

**Issue by rong4188** [appium/appium#7553]
## The problem
INFO: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): automationName XCUITest not part of Appium,Selendroid,WebDriverAgent. (WARNING: The server did not provide any stacktrace information)

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Desktop OS/version used to run Appium: El Captain
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: 9.3.5
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe: CLI

**Comment by jlipps** [comment]
Please link to a gist of your full Appium logs.

**Comment by rong4188** [comment]
@jlipps it doesn't have any Appium logs. it is just an error log from my java-client.

**Comment by jlipps** [comment]
Well, somewhere Appium is running, right? To help you we need to see the full set of logs from when Appium was started through to you receiving this error. With just your client logs and client error there's nothing we can do to investigate or help.

**Comment by rong4188** [comment]
@jlipps ok. Below is all I got. it didn't get anything after started.
[Appium] Welcome to Appium v1.6.3 (REV bf20a138788ae2355052619ab59a9b23c3b8e10a)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

**Comment by rong4188** [comment]
@jlipps it seems like my java-client is not setup/updated correctly.

**Comment by rong4188** [comment]
@jlipps client side error:
Dec 16, 2016 1:11:44 PM stayinfront.test.automation.framework.TestBase logInfo
INFO: Setting up test parameters.
Disconnected from the target VM, address: '127.0.0.1:49302', transport: 'socket'
Dec 16, 2016 1:15:03 PM stayinfront.test.automation.framework.MobileAutomationController logInfo
INFO: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): automationName XCUITest not part of Appium,Selendroid,WebDriverAgent. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 507 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'Roni10', ip: '192.168.98.14', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: io.appium.java_client.ios.IOSDriver
Dec 16, 2016 1:15:03 PM stayinfront.test.automation.framework.TestBase logInfo
INFO: Setting up test parameters.
Dec 16, 2016 1:15:03 PM stayinfront.test.automation.framework.MobileAutomationController logInfo
INFO: A new session could not be created. Details: The desiredCapabilities object was not valid for the following reason(s): automationName XCUITest not part of Appium,Selendroid,WebDriverAgent. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 23 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'Roni10', ip: '192.168.98.14', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: io.appium.java_client.ios.IOSDriver

**Comment by rong4188** [comment]
```
                DesiredCapabilities e = new DesiredCapabilities();
                e.setCapability("platformName", "iOS");
                e.setCapability("platformVersion", "9.3.5");
                e.setCapability("deviceName", "iPad");
                e.setCapability("browserName", "");
                e.setCapability("app", this.m_appPath);
                e.setCapability("udid", this.m_deviceId);
                e.setCapability("newCommandTimeout", Long.valueOf(300L)); 
                e.setCapability("autoAcceptAlerts", true);
                e.setCapability("automationName", "XCUITest");
                this.m_driver = new IOSDriver(new URL(this.m_serverUrl), e);
```

**Comment by rong4188** [comment]
@jlipps can you please help me out about that? That would be helpful enough if you tell me in what circumstance it throws an error like this.

**Comment by rong4188** [comment]
@jlipps sorry man, I just found that I got an Appium 1.5.x GUI opened and started, while I was using Appium 1.6.3 in CLI. I think this issue is caused by incorrect Appium version.

please close this issue. Thanks.
