### ISSUE TITLE
Cannot automate browser in Android 6.0

### ISSUE THREAD

**Issue by SteffenL** [appium/appium#7554]
## The problem

The stock browser launches and quits immediately a few times before Appium gives up.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.12.2
* Node.js version (unless using Appium.app|exe): 7.1.0
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I am not sure whether more explanation is necessary, but since the stock browser is called "Browser", I am not sure why Chrome is mentioned. This is the error received on the client side:
```
unknown error: Chrome version must be >= 53.0.2785.0
  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.12.2 x86_64)
```

I have also tried to start Appium with the `--chromedriver-executable` argument using the latest version of chromedriver, just in case it would make a difference:
```
unknown error: Chrome version must be >= 53.0.2785.0
  (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.12.2 x86_64)
```

## Link to Appium logs

https://gist.github.com/SteffenL/3741126ad7ef12482b6a6dd64a725fb8

## Code To Reproduce Issue [ Good To Have ]

```
from selenium import webdriver

cap = {"browserName": "Browser", "platformName": "Android", "deviceName": "Android Emulator", "platformVersion": "6.0", "automationName": "Appium", "avd": "Nexus_5_6.0"}
driver = webdriver.Remote("http://localhost:4723/wd/hub", cap)
driver.get("http://www.seleniumhq.org/")
driver.quit()
```

**Comment by jlipps** [comment]
Chrome is mentioned because we use Chromedriver to automate webviews, and the Browser app uses Chrome-backed webviews.

This error is probably because the version of Chrome backing the webviews in your Browser app is too old to be automated by the version of Chromedriver bundled with Appium. Can you try with progressively older versions of Chromedriver?

**Comment by mykola-mokhnach** [comment]
@SteffenL you need to either update System webview component on the phone under test (recommended) or downgrade chrome webdriver by using _chromedriverExecutable_ capability.

**Comment by rkavalap** [comment]
@SteffenL For every chromedriver version, there is a corresponding mapping for chrome version.
You may want to look at the notes to see which version is most applicable http://chromedriver.storage.googleapis.com/2.26/notes.txt

**Comment by SteffenL** [comment]
Sorry for the delay. I can finally confirm that chromedriver version 2.20 works with the Android 6 emulator.

**Comment by kulin24** [comment]
Thanks @SteffenL I tried many different things and this finally worked for me.

Final configurations - 
Installed System Webview application in Android 6.0 emulator.
Installed chrome browser version 64 for Android 6.0 emulator.
Configured "chromedriverExecutable" driver capability with the chromeDriver executable version 2.20.

Thank you everyone in this thread.
