### ISSUE TITLE
how to launch inspector from command line.

### ISSUE THREAD

**Issue by eastyu** [appium/appium#7555]
## Environment

* Appium version (or git revision) that exhibits the issue:1.6.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:OSX 10.12.2
* Node.js version (unless using Appium.app|exe):v6.9.2
* Mobile platform/version under test:IOS 10.2
* Real device or emulator/simulator:iPhone 6s Plus
* Appium CLI or Appium.app|exe:CLI

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for such questions. Here we only help to solve bugs/issues
