### ISSUE TITLE
Appium is not launching from terminal on mac

### ISSUE THREAD

**Issue by GopalakrishnaNagam** [appium/appium#7556]
## The problem

Xcode : Version 8.1
Installed appium from terminal (npm install -g appium 1.6.2). 
Now i trying to launch appium from terminal (appium) 
Throwing as -bash: appium: command not found

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.2
* Last Appium version that did not exhibit the issue (if applicable):No
* Desktop OS/version used to run Appium: Mac book

**Comment by mykola-mokhnach** [comment]
Check if the folder where Appium is installed is in you PATH
Closed as non Appium-related issue

**Comment by vikramvi** [comment]
@GopalakrishnaNagam http://stackoverflow.com/questions/24813589/how-to-setup-appium-on-mac-os-to-run-automated-tests-from-java-classes-on-androi
