### ISSUE TITLE
Complete installation procedure for Appium v1.6.2+

### ISSUE THREAD

**Issue by abourdon** [appium/appium#7557]
Hi,

I'm Aurélien Bourdon, from the [Cerberus](https://cerberus-testing.org/index.php/en/) project, an open source user-friendly automated testing framework.

We are using Appium for mobile application testing and we just updated our documentation procedure to install, configure and run the latest version of Appium.

Maybe you would be interested in getting a complete procedure from the use side. So please take a look: https://cerberustesting.github.io/documentation_en.html#_appium

Thanks for this impressive tool and keep up this nice work!

Regards,
Aurélien Bourdon

**Comment by vikramvi** [comment]
@abourdon please post this useful info in discuss.appium.io

@triager please close.

**Comment by imurchie** [comment]
Thanks for the writeup, @abourdon !

**Comment by SrinivasanTarget** [comment]
@abourdon Thanks for the writeup again :) Would you mind sending this as a PR [here](https://github.com/SrinivasanTarget/awesome-appium)

**Comment by abourdon** [comment]
Alright! I'm away until the end of the the year so I will send you a PR in January.

Regards,
Aurélien
