### ISSUE TITLE
Appium 1.6.3 - XCUITest - long_press action not implemented for iOS 

### ISSUE THREAD

**Issue by PiotrNestor** [appium/appium#7559]
## The problem

For iOS test, the following is not implemented:

```
        action = TouchAction(self._d)
        action.long_press(_from).move_to(_to).release().perform()
```

The following works in stead:
```
        action = TouchAction(self._d)
        action.press(_from).wait(500).move_to(_to).release().perform()
```
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: MacOS 10.12.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: read device
* Appium CLI or Appium.app|exe: appium cli

## Details

For long_press the error is returned:
WebDriverException: Message: Support for this gesture is not yet implemented. Please contact an Appium dev

## Link to Appium logs

```
[HTTP] --> POST /wd/hub/session/313da6ec-7df6-4ff6-88a8-008ce5305c25/touch/perform {"sessionId":"313da6ec-7df6-4ff6-88a8-008ce5305c25","actions":[{"action":"longPress","options":{"y":null,"x":null,"duration":1000,"element":"DF579FF0-D838-45B4-805E-6B6A40918F90"}},{"action":"moveTo","options":{"y":null,"x":null,"element":"F3178F98-8747-4D98-9638-E416F2501B0C"}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"y":null,"x":null,"duration":1000,"element":"DF579FF0-D838-45B4-805E-6B6A40918F90"}},{"action":"moveTo","options":{"y":null,"x":null,"element":"F3178F98-8747-4D98-9638-E416F2501B0C"}},{"action":"release","options":{}}],"313da6ec-7df6-4ff6-88a8-008ce5305c25"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: longPress-moveTo-release
[HTTP] <-- POST /wd/hub/session/313da6ec-7df6-4ff6-88a8-008ce5305c25/touch/perform 501 12 ms - 164 
```

## Code To Reproduce Issue [ Good To Have ]

```
        action = TouchAction(self._d)
        action.long_press(_from).move_to(_to).release().perform()
```

**Comment by dpgraham** [comment]
The issue is that 'long_press->move-to->release' is an invalid chain of events. A 'long_press' event is the pressing and holding of a specific element for a given duration.

```python
def long_press(self, el=None, x=None, y=None, duration=1000):
        """Begin a chain with a press down that lasts `duration` milliseconds
        """
        self._add_action('longPress', self._get_opts(el, x, y, duration))

        return self
```

Here is the code snippet in appium-xcuitest-driver that determines if an array of gestures is a long press

```js
function isLongPress (gestures) {
  if (gestures.length === 1 && gestures[0].action.toLowerCase() === 'longpress') {
    return true;
  } else if (gestures.length === 3 &&
              gestures[0].action === 'press' &&
              gestures[1].action === 'wait' &&
              gestures[2].action === 'release') {
    return true;
  }
  return false;
}
```

According to your logs, these are the gestures being provided

```js
[
    [{
        "action": "longPress",
        "options": {
            "y": null,
            "x": null,
            "duration": 1000,
            "element": "DF579FF0-D838-45B4-805E-6B6A40918F90"
        }
    }, {
        "action": "moveTo",
        "options": {
            "y": null,
            "x": null,
            "element": "F3178F98-8747-4D98-9638-E416F2501B0C"
        }
    }, {
        "action": "release",
        "options": {}
    }], "313da6ec-7df6-4ff6-88a8-008ce5305c25"
]
```

As you can see, the gestures won't pass the 'isLongPress' test and that's why it's reaching the exception.

What I would recommend is to keep using your workaround. On our end though it might be worth looking into updating the xcuitest-driver to show more helpful error message (something like: _cannot call move-to on a longpress event_)

**Comment by PiotrNestor** [comment]
The present Appium Python binding implementation for drag and drop contradicts your comments.
This is the present drag_an_drop in the Appium Python  binding
```
    # convenience method added to Appium (NOT Selenium 3)
    def drag_and_drop(self, origin_el, destination_el):
        """Drag the origin element to the destination element

        :Args:
         - originEl - the element to drag
         - destinationEl - the element to drag to
        """
        action = TouchAction(self)
        action.long_press(origin_el).move_to(destination_el).release().perform()
        return self
```

**Comment by dpgraham** [comment]
The client needs to be changed. It should be:

```python
action.press(origin_el).wait().move_to(destination_el).release().perform()
```

**Comment by slipy12** [comment]
@dpgraham @imurchie In ruby I've been chaining long_press and move_to

**Comment by dpgraham** [comment]
Yeah, @imurchie is working on that right now so that XCUITest chains long_press and move_to. We can leave the python client as is.

**Comment by gkvappium** [comment]
@imurchie ,

Is there any update on this issue. I recently upgraded to IOS 10 and long_press doesn't work. I use 1.6.4 beta version. I get an error message saying that this gesture is not yet supported. Please contact an appium developer.

Thanks

**Comment by mykola-mokhnach** [comment]
@gkvappium Please update to 1.6.4-stable and read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md

**Comment by gkvappium** [comment]
@mykola-mokhnach , thanks..Will try this out
