### ISSUE TITLE
Unrecognized Appium errors appear during mobile automation TC running using Ruby + Capybara + Appium + Rspec

### ISSUE THREAD

**Issue by kay4444** [appium/appium#7560]
## The problem
I see "Failure/Error: if e = error()" error while running my TC for android using Ruby + Capybara + Appium + Rspec

## Environment
Appium version: 1.4.16.1
* Desktop OS/version used to run Appium: Windows 7
Samsung Galaxy S6 - real device

## Details
I am trying to set up environment for mobile automation TC running. I use Ruby + Capybara + Appium + Rspec. But something went wrong. I see errors while run TC

## Link to Appium logs
Appium logs: https://gist.github.com/kay4444/50f4ece611acbd4bb0b4713e2b7f57ef
Appium server logs: https://gist.github.com/kay4444/e177e688d959f0db22278b4787037203

## Code To Reproduce Issue [ Good To Have ]
1) My settings file:
https://gist.github.com/kay4444/0e903c1368e14ffb055300661a6a4331
2) My TC file:
https://gist.github.com/kay4444/1a8ef7f9fca011882cf8a0392521abbd
3) My Gem file:
https://gist.github.com/kay4444/34e1616eb9463c5d79d8b3ee74e7baa2

**Comment by imurchie** [comment]
Can you provide the Appium server logs?

**Comment by kay4444** [comment]
Updated my post. i've added link to Appium Server logs: https://gist.github.com/kay4444/e177e688d959f0db22278b4787037203

**Comment by imurchie** [comment]
There is no indication of any error on the server side. 

I see you've opened an [issue](https://github.com/appium/appium_capybara/issues/28) on the `appium_capybara` repository. Closing this one.
