### ISSUE TITLE
Appium TouchAction issues [1.6.1, 1.6.2 and 1.6.3]

### ISSUE THREAD

**Issue by gitsaquib** [appium/appium#7564]
## The problem

TouchAction is unable to Tap Assistive Touch

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): Yes
* Desktop OS/version used to run Appium: Mac 10.12
* Node.js version (unless using Appium.app|exe): v6.9.1
* Mobile platform/version under test: iOS 10.2 [iPad]
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CL

## Details
We want to switch Wifi. We are unable to swipe from bottom to do so. We are then using assistive touch to open and switch wifi  

## Link to Appium logs
https://gist.github.com/gitsaquib/03bc64b099067effb8ede578b5e13b92

## Code To Reproduce Issue [ Good To Have ]
```java
public static void tapAt(AppiumDriver<MobileElement> driver, int tapPointX, int tapPointY) {
		TouchAction action = new TouchAction(driver);
		Log.event("Tapping at (" + tapPointX + ", " + tapPointY + ")");
		//action.tap(tapPointX, tapPointY).perform();
		action.press(tapPointX, tapPointY).waitAction(500).moveTo(tapPointX+10, tapPointY+10).release().perform();
		Log.event("Tapped at position (" + tapPointX + ", " + tapPointY + ")");
	}
```

**Comment by dpgraham** [comment]
This is due to XCUITest having incorrect touch events in landscape mode. We're waiting on a pull request (https://github.com/facebook/WebDriverAgent/pull/411) to hopefully fix this problem.

**Comment by gitsaquib** [comment]
Thanks @dpgraham . Any ETA on when the fix will be available

**Comment by dpgraham** [comment]
Not sure. This will need to be reviewed by Marek (he's the maintainer of Web Driver Agent, which is a FB project). Once it's committed we'll need to update appium-xcuitest-driver to the latest.

**Comment by gitsaquib** [comment]
Thanks @dpgraham . Please update me once you have latest available

**Comment by dpgraham** [comment]
We'll mention it in the Appium release notes I'm sure

**Comment by KBhatti** [comment]
@dpgraham I am not able to do a driver.tap() or tap for a particular timeframe using TouchAction. I am using Appium 1.6.3/iOS 10.2 simulator. From your comments seems like its an issue that Appium WDA is looking at. Is it resolved yet?
TIA!

**Comment by gitsaquib** [comment]
@dpgraham when are we expecting the fix?

**Comment by gitsaquib** [comment]
@dpgraham when are we expecting the fix?

**Comment by dpgraham** [comment]
Have you are tried again with the latest Appium? They made a fix for the landscape issue in WDA recently.

**Comment by gitsaquib** [comment]
@dpgraham 

Yes, we tried with the latest version of appium (1.6.4@beta). We are facing same issue again. 

"actions":[{"action":"press","options":{"element":"BC501045-EBB6-41C2-A36E-4D6A49B7DD3E"}},{"action":"wait","options":{"ms":10}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"element":"BC501045-EBB6-41C2-A36E-4D6A49B7DD3E"}},{"action":"wait","options":{"ms":10}},{"action":"release","options":{}}],"d9a1b849-a557-4114-976a-526a22cc617d"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-wait-release
[debug] [JSONWP Proxy] Proxying [POST /wda/element/BC501045-EBB6-41C2-A36E-4D6A49B7DD3E/touchAndHold] to [POST http://localhost:8100/session/CA93AAC4-0C61-43BF-A8A0-CD0D7DEFEC41/wda/element/BC501045-EBB6-41C2-A36E-4D6A49B7DD3E/touchAndHold] with body: {"duration":0.01}
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"CA93AAC4-0C61-43BF-A8A0-CD0D7DEFEC41","value":"Unhandled endpoint: /session/CA93AAC4-0C61-43BF-A8A0-CD0D7DEFEC41/wda/element/BC501045-EBB6-41C2-A36E-4D6A49B7DD3E/touchAndHold -- http://localhost:8100/ with parameters
{\n    wildcards =    
(\n        \"session/CA93AAC4-0C61-43BF-A8A0-CD0D7DEFEC41/wda/element/BC501045-EBB6-41C2-A36E-4D6A49B7DD3E/touchAndHold\"\n    );
\n}","status":1}

**Comment by dpgraham** [comment]
So this is a different bug that we've seen before: https://github.com/appium/appium/issues/7304

Can you try doing an uninstall of appium ```npm uninstall -g appium``` and then reinstalling it ```npm install appium```. 

It looks like the version of WebDriverAgent you have is missing the `touchAndHold` endpoint, which should be there in the latest Appium release (you can look in `node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Commands/FBElementCommands.m` to see if `touchAndHold` is defined)
