### ISSUE TITLE
 Swipe gesture works incorrect on landscape mode using xcuitest driver.

### ISSUE THREAD

**Issue by SergeVKom** [appium/appium#7566]
## The problem

Swipe gestures do not change their directions when application changes a screen orientation from portrait to landscape.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium: -
* Node.js version (unless using Appium.app|exe): v7.2.0
* Mobile platform/version under test: 10.1.1
* Real device or emulator/simulator: Real device and simulator
* Appium CLI or Appium.app|exe: cli
* XCUITestDriver version: 2.4.2

## Details

For example element.swipe(SwipeElementDirection.RIGHT, 1) in landscape mode works as element.swipe(SwipeElementDirection.UP, 1). It looks like swipe gestures do not understand that application is in an landscape mode.
BTW the method slider.sendKeys('<0..1>') have the same behaviour in landscape mode.

## Link to Appium logs

https://gist.github.com/SergeVKom/52f041a041ec1b1df6075de5926fc20a#file-swipegestures

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/SergeVKom/34a459f7133a49ac3dd2b15e87cf1928#file-codeexample

**Comment by mykola-mokhnach** [comment]
Known XCTest issue. for now you can exchange x and y coordinates in your code as a workaround. Should be fixed by [this](https://github.com/facebook/WebDriverAgent/pull/411) PR

**Comment by mykola-mokhnach** [comment]
WDA workaround for coordinates calculation:

```objc
CGPoint FBInvertPointForApplication(CGPoint point, CGSize screenSize, UIInterfaceOrientation orientation)
{
  switch (orientation) {
    case UIInterfaceOrientationUnknown:
    case UIInterfaceOrientationPortrait:
      return point;
    case UIInterfaceOrientationPortraitUpsideDown:
      return CGPointMake(screenSize.width - point.x, screenSize.height - point.y);
    case UIInterfaceOrientationLandscapeLeft:
      return CGPointMake(point.y, screenSize.height - point.x);
    case UIInterfaceOrientationLandscapeRight:
      return CGPointMake(screenSize.width - point.y, point.x);
  }
}
```
