### ISSUE TITLE
[appium 1.5.3][xcode 7.3.1]run test on iPhone5s real device failed

### ISSUE THREAD

**Issue by wensj** [appium/appium#7568]
## The problem
run test on iPhone5s real device failed,simulator is ok

## Environment

appium 1.5.3
xcode 7.3.1
mac 10.11.2

## Details

everything is ok on iOS simulator,appium doctor test is ok. I can use xcode to run app on real device,instrument is ok.So I don't know why I can't use appium to launch app on real device.the log is here:

[debug] [UIAuto] Dynamic bootstrap path: /Users/wensj/Library/Application Support/appium/bootstrap/bootstrap-2428963e067af126.js
[debug] [UIAuto] Reusing dynamic bootstrap: /Users/wensj/Library/Application Support/appium/bootstrap/bootstrap-2428963e067af126.js
[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'

[debug] [iOS] Creating iDevice object with udid 156aa7c8bd6b8334921d2bab442ce0762a7c950a

[debug] [iOS] App is not installed. Will try to install.

[MJSONWP] Encountered internal error running command: Error: Installing /var/folders/0g/p2ndjzhs2w54tdwn8tkd8d480000gn/T/20161119-4506-5fdoip/TestApp.app failed
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:159:6
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)

**Comment by imurchie** [comment]
You need to re-install `libimobiledevice` with the latest version. Apple changed how it did things, and broke much stuff.

```
brew uninstall libimobildevice
brew install libimobiledevice --HEAD
```

**Comment by jlipps** [comment]
Also, pretty sure you need a signed `.ipa` file for real devices, not an `.app`

**Comment by wensj** [comment]
After use this command:"sudo chmod -R 777 /var/db/lockdown/",the problem solved.Thanks !

**Comment by pavanbachu0604** [comment]
@wensj sudo chmod -R 777 /var/db/lockdown/ is not permanent fix , its a workaround I would suggest you to follow these commands 
brew uninstall libimobildevice
brew install libimobiledevice --HEAD
