### ISSUE TITLE
Cannot use start_activity on Appium 1.6.0

### ISSUE THREAD

**Issue by sepiol** [appium/appium#7571]
## The problem

Trying to run another app within a test with start_activity function from appium webdrvier (python)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Desktop OS/version used to run Appium: OSX
* Node.js version 7.1.0:
* Mobile platform/version under test: iOS 10.1.1
* Real device or emulator/simulator: Real device (iPhone 6)
* Appium CLI

## Details

Within the iOS capabilities i provide the following bundleId: "com.apple.Preferences" that opens the Settings menu. After the settings i want to open the dialer with the package: "com.apple.mobilephone" and i get the error

## Link to Appium logs

https://gist.github.com/anonymous/9bc5a74a68370b08ed31d08f0ad6e98f

## Code To Reproduce Issue

https://gist.github.com/sepiol/433ddc9f2919a9883e5b99b38d4d5566

**Comment by imurchie** [comment]
`start_activity` is only valid for Android.

https://github.com/appium/python-client/blob/fb37b816f5073e4eea1937046b006a9447a87e91/appium/webdriver/webdriver.py#L543

**Comment by sepiol** [comment]
@imurchie OK, so is there any equivalent function for iOS that allows opening other apps from within the curren session??

**Comment by jlipps** [comment]
@sepiol you can click the home button then find another app's icon in the UI and tap on it using all the usual appium commands.
