### ISSUE TITLE
How to reduce ESOCKETTIMEDOUT timeout option in appium server

### ISSUE THREAD

**Issue by Siddh010** [appium/appium#7572]
## The problem
I am trying to select "Date Picker"  value  in IOS device with "setValue" command  and able to select  value but it throw error message as shown below and take lot of time for http request to go to next step.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium:  Mac 10.11.6
* Node.js version (unless using Appium.app|exe): 6.9.2
* Mobile platform/version under test:  IOS 10.0.2
* Real device or emulator/simulator:  Iphone 6
* Appium CLI or Appium.app|exe: Appium CLI

## Details
I would like to reduce ESOCKETTIMEDOUT timeout option   while executing appium server.
public void setValue(IOSElement els, String value){
		try{
		els.setValue(value);
		}catch(WebDriverException e){
			System.out.println("WebDriverException  exception message ");
		}
	}

## Link to Appium logs

```
debug] [MJSONWP] Responding to client with driver.implicitWait() result: null
[HTTP] <-- POST /wd/hub/session/071dd04a-38a6-412d-aef3-c97eb90c66d6/timeouts/implicit_wait 200 2 ms - 76 
[HTTP] --> POST /wd/hub/session/071dd04a-38a6-412d-aef3-c97eb90c66d6/appium/element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/value {"id":"5FB7B19F-CC31-48E3-B919-8F9F426BE651","value":"2016"}
[debug] [MJSONWP] Calling AppiumDriver.setValueImmediate() with args: ["2016","5FB7B19F-CC31-48E3-B919-8F9F426BE651","071dd04a-38a6-412d-aef3-c97eb90c66d6"]
[debug] [XCUITest] Executing command 'setValueImmediate'
[XCUITest] There is currently no way to bypass typing using XCUITest. Setting value through keyboard
[debug] [JSONWP Proxy] Proxying [GET /element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/attribute/type] to [GET http://localhost:8100/session/C913959C-840F-4401-AC65-0EA594F665B2/element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/attribute/type] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypePickerWheel\",\n  \"sessionId\" : \"C913959C-840F-4401-AC65-0EA594F665B2\",\n  \"status\" : 0\n}"
[debug] [JSONWP Proxy] Proxying [POST /element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/value] to [POST http://localhost:8100/session/C913959C-840F-4401-AC65-0EA594F665B2/element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/value] with body: {"value":["2","0","1","6"]}
[debug] [iProxy] recv failed: Resource temporarily unavailable
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/071dd04a-38a6-412d-aef3-c97eb90c66d6/appium/element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/value 500 240200 ms - 251 

[HTTP] <-- POST /wd/hub/session/071dd04a-38a6-412d-aef3-c97eb90c66d6/appium/element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/value 500 240200 ms - 251 
[HTTP] --> POST /wd/hub/session/071dd04a-38a6-412d-aef3-c97eb90c66d6/timeouts/implicit_wait {"ms":0}
[debug] [MJSONWP] Calling AppiumDriver.implicitWait() with args: [0,"071dd04a-38a6-412d-aef3-c97eb90c66d6"]
[debug] [XCUITest] Executing command 'implicitWait'
[debug] [BaseDriver] Set implicit wait to 0ms
[debug] [MJSONWP] Responding to client with driver.implicitWait() result: null
```

**Comment by dpgraham** [comment]
@imurchie @jlipps Could one of you look at this one?

**Comment by Siddh010** [comment]
It is taking around 4 min now to get HTTP request after "Internal Error  ProxyRequestError: Could not proxy command to remote server."
[HTTP] <-- POST /wd/hub/session/071dd04a-38a6-412d-aef3-c97eb90c66d6/appium/element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/value 500 **_240200_** ms - 251 

Thanks
Siddartha

**Comment by mykola-mokhnach** [comment]
I cannot help here without device logs. There should be some delay on WDA side and iproxy fails here because it does not get any response from WDA after the timeout expires.

**Comment by Siddh010** [comment]
Hi 

Please find the device log in https://gist.github.com/Siddh010/65f05fa1b0d8bdc7b69109f6f3bb13cd

Thanks
Siddartha

**Comment by mykola-mokhnach** [comment]
Unfortunately it's not what is needed. This is Appium log and I need the log from the device itself.

**Comment by Siddh010** [comment]
Hi  

Please find the device log in https://gist.github.com/Siddh010/d579d11db61d94bbfae95387fffe47d8  

I am facing similar issue : -
https://discuss.newrelic.com/t/how-to-ignore-esockettimedout-socket-hang-up-errors/10697

Thanks
Siddartha

**Comment by Siddh010** [comment]
Facing same issue as :- https://github.com/appium/appium/issues/7538

**Comment by vamsidharj12** [comment]
Hi , 
I am also facing  the same issue.  
Unable to connect to running web driver agent. Could not proxy command to remote server. ESOCKETTIMEDOUT exception. 
I am using Appium 1.2.0

**Comment by vamsidharj12** [comment]
Can somebody provide resolution for the above issue please?

**Comment by don0077** [comment]
I am also getting this error, is any one have the solution for this, surprisingly this I am getting this issue at clicking on button which works fine first time, but same page same button clicking second time is failing.

> [MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/21d7bc5d-4d47-4c8e-9677-c4c450d52193/screenshot] to [GET http://127.0.0.1:8000/wd/hub/session/3a82ba491a5ee2f725f173fbe964a73b/screenshot] with body: {}
[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:384:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by don0077** [comment]
Resolved : In my case this was resolved, I was using the take screen shot option by calling the `getScreenshotAs(OutputType.BYTES);` and this was working fine on desktop browser version, but same script when executing on Android device (hybrid app) it causing the issues and giving me the ESOCKETTIMEOUT error. I did the debug step by step and just commented this line. Now scripts was executing fine with out issues. Surpirsingly getScreenshot method is not working in both Android and Iphone real devices.

**Comment by laxmikantm** [comment]
Hi Guys, Kindly refer recommended java snippet on taking snapshot on cucumber.io website (https://cucumber.io/docs/reference), notice that- it recommends using above method:
getScreenshotAs(OutputType.BYTES);

Is there any way to get it fixed ? Thanks
