### ISSUE TITLE
WDA has a new "swipe" endpoint. Use it.

### ISSUE THREAD

**Issue by imurchie** [appium/appium#7573]
Swiping [has been implemented in WDA](https://github.com/facebook/WebDriverAgent/commit/143332260c53561bb7e544ae4e2d4b8dc649ac8d). Implement mappings so it can be exposed through Appium.

**Comment by jlipps** [comment]
This seems high priority. Thanks for pulling it into the current sprint.

**Comment by suganeby** [comment]
I am also waiting for the swipe functionality. I am facing issue in 1.6.3. Is it fixed?

**Comment by mykola-mokhnach** [comment]
@suganeby yes, it works in Appium 1.6.4-beta
