### ISSUE TITLE
installApp fails for APKs with no launchable activity

### ISSUE THREAD

**Issue by wsander3** [appium/appium#7579]
## The problem

I need to use the .installApp functionality as part of my test suite, however the APK I am installing does not have a launchable activity. It is a daemon that runs in the background. I would like to use Appium to test the interaction with this daemon APK.

The issue that it appears that calling driver.installApp("my_apk_with_no_launchable_activity.apk") fails because it tries to search for a launchable activity via "aapt dump badging the.apk".

Why is having a launchable activity a prerequisite for installing an apk? I can install this APK directly using ADB, but I would like my tests to do this step for me automatically.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium server 1.5.12
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS X 10.11.6
* Node.js version (unless using Appium.app|exe): v6.2.2
* Mobile platform/version under test: Android. Using SDK Build Tools 25.
* Real device or emulator/simulator: LG Nexus 5
* Appium CLI or Appium.app|exe: Appium Java Client 5.0.0.

## Link to Appium logs

Appium Server Logs: https://gist.github.com/wsander3/77d36b39f52818493665b08eff44f7c2

## Code To Reproduce Issue [ Good To Have ]

driver.installApp("Any_app_without_launchable_activity.apk")

Thanks for your time!

**Comment by jlipps** [comment]
@wsander3 can you try with Appium 1.6.3? We don't support Appium 1.5.x any longer.

**Comment by wsander3** [comment]
@jlipps I just tried with Appium 1.6.3. Appears to be the same issue, with the same error message.

**Comment by jlipps** [comment]
OK, adding this to the bugs list. Probably true that when calling `installApp` we should not need to verify it has a launchable activity. That's more for starting the AUT.

**Comment by mykola-mokhnach** [comment]
This is not the case anymore. Closed as fixed
