### ISSUE TITLE
Appium is not getting initialized when a group of scripts are scheduled for execution. i.e. it is failing to initialize randomly in between in the execution.

### ISSUE THREAD

**Issue by subasarav** [appium/appium#7580]
We are executing the Appium scripts as a test suite that has many scripts say 20 scripts. When the scripts are getting executed, Appium is not getting initialized in between the execution.

## Environment

* Appium version : 1.4.16.1
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 6.8.1
* Mobile platform/version under test: Android 5.1 and Android 6.0
* Real device or emulator/simulator: Real Device (Samsung Galaxy S4 and Moto G4 plus)
* Appium CLI or Appium.app|exe:

## Details

When the scripts are getting executed, Appium is not initialized in between randomly. Say when the group has 20 scripts, it is running fine for couple of scripts say 5, then Appium is not initializing for the 6th script. But again say from 7-10 the scripts are getting executed and again for the 11th script Appium is not initialized. This is happening randomly to any of the scripts.

## Link to Appium logs

<script src="https://gist.github.com/subasarav/7906407ee4ed4b39bcc908dc98f397c5.js"></script>

**Comment by mykola-mokhnach** [comment]
Try updating Appium to the most recent version (1.6.3) and check whether the problem is still reproducible
