### ISSUE TITLE
Appium 1.6.3 - iOS driver pre-launches app app even if autoLaunch capability is False

### ISSUE THREAD

**Issue by PiotrNestor** [appium/appium#7582]
## The problem

There is 'autoLaunch' appium remote driver capability.
In my understanding autoLaunch=False should start the driver without launching the app.

This works as expected for the Android platform. 
For the iOS platform the driver launches the app anyway.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS 10.12.1
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Details

Start  driver with autoLaunch = False.
The app should not be launched when the driver is created/initiated with the provided capabilities.

Otherwise the following set of capabilities are provided when creating the driver

```
            platformName
            platformVersion
            deviceName
            udid
            app
            newCommandTimeout 
            fullReset = False
            noReset = True
            autoLaunch = False,
            realDeviceLogger 
            xcodeConfigFile
```

**Comment by jlipps** [comment]
autoLaunch was removed in Appium 1.5.

**Comment by EltonZhong** [comment]
hi, so what's the solution if I want to kill app in ios and start a new session without launching the app?
