### ISSUE TITLE
Unable to launch app sucessfully

### ISSUE THREAD

**Issue by RupalJoshi-cf247** [appium/appium#7584]
## Issue:
Unable to launch the application on an android device. Following error message displayed:
_'System.InvalidOperationException : Unable to launch the app: Error: Trying to start logcat capture but it's already started! (IndexOutOfBounds)'_

## Environment
* Appium version that exhibits the issue: 1.4.16.1
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): Appium App|exe
* Mobile platform/version under test: Android 6
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium App|exe

## Details

When I use the launchApp() command - I get the failure message mentioned above - however when I remove the launchApp() command and use the InstallApp() command instead then my test will successfully pass

**Comment by dpgraham** [comment]
Can you provide a code snippet and a gist of the appium server logs?

**Comment by dpgraham** [comment]
@midopa: Were you actually able to observe that one of your simulators didn't have a TrustStore and then when you drag-and-dropped the cert onto Safari, the TrustStore appeared for the first time?

**Comment by midopa** [comment]
@dpgraham I think you meant to comment on another issue: #7511 
I'll respond in that one.
