### ISSUE TITLE
An unknown server-side error occurred while processing the command. Original error: Could not navigate to webview; there are none!

### ISSUE THREAD

**Issue by hardik-d** [appium/appium#7587]
## The problem

Whenever I launch my web test suite on iphone6 ios 10 simulator using XCUITest driver and appium 1.6.3 test fail randomly with above errors. What i noticed running the tests is webdriveragent app launches then safari launches and then goes in background. Whenever this happens tests fail randomly and not sure what the solution is here.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: OSX El Capitan
* Node.js version (unless using Appium.app|exe): node v5
* Mobile platform/version under test: iphone6 ios 10.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: N/A

## Link to Appium logs

https://gist.github.com/hardik-d/49c99b7f899bbc220161caef6baab94a

## Link to simulator logs when this happens

https://gist.github.com/hardik-d/6da54f391ab02cd6e101b28118746cfc

## Code To Reproduce Issue [ Good To Have ]
```
opts = {caps: {
          browserName: "safari",
          platformName: "iOS",
          platformVersion: "10.2",
          deviceName: "iPhone 6",
          automationName: "XCUITest",
          autoDismissAlerts: "true"
      }
      }
@driver = Appium::Driver.new(opts).start_driver
@driver.get("http://dev.paynearme.com:3000/consumers/")
Appium.promote_appium_methods Object
```
sleep 5 #give enough time for webdriveragent app to launch the app, if have any better suggestion here, let me know

rest of the code is immaterial

**Comment by hardik-d** [comment]
@imurchie @jlipps any workaround here ?

**Comment by dpgraham** [comment]
What happens if you try running the test without setting the automationName?

**Comment by hardik-d** [comment]
same results @dpgraham

**Comment by jlipps** [comment]
@imurchie if I'm reading this log right, we're looking at the pageDict but it's empty ("waiting for data") for long enough that we time out. When it finally does have useful data, we're no longer listening for it. Could we resolve this simply by trying more times, or increasing the timeout between each try?

**Comment by imurchie** [comment]
Yes, this looks like things are in weird state, where the page gets in before we actually get a connection. I'll look a little at this to see if I can make some headway.

**Comment by imurchie** [comment]
@hardik-d  Can you try updating the dependencies so you have `appium-remote-debugger@3.2.1`? I've added a check to at least try things out when no app is there. I'm hoping this has some effect.

**Comment by hardik-d** [comment]
@imurchie it is better than before. All the commands in webview context work, but safari still goes in background and hence none of the native_app context commands work nor will i be able to capture meaningful screenshot at the point of failure since safari is not in foreground.

**Comment by hardik-d** [comment]
@imurchie is there a way for us to make sure safari is the app in focus or not, if not bring it in focus? that would solve the problem.

**Comment by imurchie** [comment]
Can you provide the logs from the latest run? Things were obscured in the old ones.

Secondly, can you try manually starting the session, to see if the same behaviour exists?


In one terminal session,
```
/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
xcodebuild build-for-testing test-without-building -project /Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=BC14239B-5C6D-4DE6-9717-A9CD2AEC58AB -configuration Debug
```

In another,
```
export DEVICE_URL='http://localhost:8100'
export JSON_HEADER='-H "Content-Type: application/json;charset=UTF-8, accept: application/json”'
curl -X POST $JSON_HEADER -d "{\"desiredCapabilities\":{\"bundleId\":\"com.apple.mobilesafari\",\"arguments\":[\"-u\", \"http://0.0.0.0:4723/welcome\"],\"environment\":{},\"shouldWaitForQuiescence\":true}}" $DEVICE_URL/session
```

**Comment by hardik-d** [comment]
@imurchie here are the new logs: https://gist.github.com/hardik-d/570a95da837a2113e3a5edd29921e49f

not sure if this helps because like i said all the test commands were in webview context and test passed however safari was in background

**Comment by hardik-d** [comment]
@imurchie the manual commands work!

**Comment by hardik-d** [comment]
@imurchie any updates here? let me know if i can help debug it any further.

**Comment by jlipps** [comment]
@imurchie I'm unclear what's happening here. Things are working when running WDA directly but not when running via Appium?

**Comment by nirmeshptl** [comment]
Hey Guys, I am facing similar issue and would like to know if we have come to any solution or workaround here. 

I can help if there is anything further to debug @dpgraham @jlipps @imurchie

**Comment by jlipps** [comment]
@hardik-d @nirmeshptl can you try installing appium 1.6.4-beta to see if it affects this issue at all?

**Comment by hardik-d** [comment]
will try @jlipps do you have the command handy to get appium 1.6.4-beta through npm? is it just npm install -g appium@1.6.4-beta

**Comment by hardik-d** [comment]
@jlipps things are even worst in 1.6.4 beta it seems. Tests never rescue from previous failure asin appium never kills and start a new browser session. Almost got 98 failures from 100 tests. gonna revert back for now

**Comment by mykola-mokhnach** [comment]
@hardik-d Can you please attach logs? We'd be happy to review and fix the issues there if possible. But it is hardly possible to do this without detailed description. Thanks.

**Comment by hardik-d** [comment]
@mykola-mokhnach will give you shortly

**Comment by hardik-d** [comment]
@mykola-mokhnach @jlipps https://gist.github.com/hardik-d/91b107e39b411fa5b408819a4dd72163
i ran the full suite, first 2 tests passed and 3rd one failed and every test from here on fails because the safari session was not cleaned up after the second test.

**Comment by hardik-d** [comment]
my caps:
opts = {caps: {
          browserName: "safari",
          platformName: "iOS",
          platformVersion: "10.2",
          deviceName: "iPhone 6",
          automationName: "XCUITest",
          autoDismissAlerts: "true"
      }

**Comment by mykola-mokhnach** [comment]
Everything seems to be fine according to the log. What exactly is not cleaned in safari session?

**Comment by hardik-d** [comment]
@mykola-mokhnach hence i didn't give you the logs and stated the problem. My tests used to start a fresh browser session with cookies and cache cleared with each test on 1.6.3. Meaning if i was logged in to my application under test, it would log me out after each test. In 1.6.4 beta it seems user stays logged in, browser gets killed and restarted but the session data is not cleared so i get test failures.

**Comment by mykola-mokhnach** [comment]
do you keep session info in cookies? is it possible in the second test, that fails, to check manually whether these cookies are still available?

**Comment by hardik-d** [comment]
nope, my tests don't do anything with cookies.

**Comment by hardik-d** [comment]
do i need to change something in my capabilities to get the behavior as before?

**Comment by hardik-d** [comment]
in 1.6.4 i don't see simulator getting reset at all. Without that idk, how you guys are handling that on appium side?

**Comment by mykola-mokhnach** [comment]
you may reset _fullReset_ capability to _true_, but it will take much more time to restart the simulator between tests. I just want to know which information persists in browser after "default" reset, so it restores the session. Having this info we could find and cleanup the stuff without resetting the whole simulator.

**Comment by hardik-d** [comment]
@mykola-mokhnach i don't know how to give you that information? maybe i can ask around with my devs. What are you looking for? I can try something manually if you like. From my testing experience since ios9 safari has a bug where clearing safari history and cookies manually also doesn't clear all site data. I have to manually go into advanced settings and clear site data individually.

**Comment by mykola-mokhnach** [comment]
There are several options. If the webapp you're testing is a public one then we can just try it with test credentials and figure out ourselves what can/should be removed. Or you check with developers on which sources the site is using to restore the session (cookies/indexDB/keychain, etc) and whether these sources are still present after default Appium cleanup.

**Comment by hardik-d** [comment]
@mykola-mokhnach answer from devs is that they use local storage

**Comment by hardik-d** [comment]
yes, we have consumer facing product so i can also give you that url. 
repro:
1st test: sign up https://www.paynearme.com/consumers/ 
2nd test launch this url again

issue: user still logged in

I will also try this simplest case, and let you know!

**Comment by mykola-mokhnach** [comment]
This might be some safari issue though. You might add [this](http://sqa.stackexchange.com/questions/10466/how-to-clear-localstorage-using-selenium-and-webdriver) method to each test teardown to make sure your local storage is clean:

```
driver.get('javascript:localStorage.clear();');
```

**Comment by hardik-d** [comment]
@mykola-mokhnach 
[HTTP] --> POST /wd/hub/session/79695a7d-0029-4690-9fbb-529f442ce00e/url {"url":"javascript:localStorage.clear();"}
[MJSONWP] Encountered internal error running command: Error: Url or Uri must start with <scheme>://
    at Object.setUrl (../../../lib/mjsonwp/validators.js:18:13)
    at asyncHandler$ (../../../lib/mjsonwp/mjsonwp.js:221:32)
    at tryCatch (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:201:7)
    at AsyncIterator.enqueue (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at asyncHandler (../../../lib/mjsonwp/mjsonwp.js:262:20)
    at ../../../lib/mjsonwp/mjsonwp.js:291:15
    at Layer.handle [as handle_request] (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
    at /Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/index.js:281:22
    at param (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
    at logger (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
    at /Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
    at /Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/raw-body/index.js:262:16)
    at done (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/Users/hardik/.nvm/versions/node/v5.0.0/lib/node_modules/appium/node_modules/raw-body/index.js:307:7)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
[HTTP] <-- POST /wd/hub/session/79695a7d-0029-4690-9fbb-529f442ce00e/url 500 13 ms - 209

**Comment by hardik-d** [comment]
@mykola-mokhnach tried all 3 solutions in the link you provided, didn't work

**Comment by hardik-d** [comment]
@mykola-mokhnach tried with fullReset: "true" and it is behaving same as 1.6.3. Launches safari and then safari goes into background and hence all native commands fail to execute. Back to where i was.

**Comment by hardik-d** [comment]
@mykola-mokhnach i manually logout the user after each test now and that seem to be working fine.  I won't have such an easy option for native apps, will let you know what happens there.

**Comment by mykola-mokhnach** [comment]
@hardik-d sorry for the inconveniences and thanks for cooperation. We are now trying to address the stuff. Please stay tuned - these fixes will be in 1.6.4-beta soon

**Comment by hardik-d** [comment]
@mykola-mokhnach @jlipps are we allowed to log bugs against 1.6.4 beta? all my tests that interact on pages that have loading spinner(animation) are failing i think. is it a known issue or you need info on it?

**Comment by mykola-mokhnach** [comment]
This must be a separate issue. If you can provide logs and/or any other useful information (and if nothing similar has been reported so far) then feel free to create a new issue report.

**Comment by mykola-mokhnach** [comment]
Hi @hardik-d 

we've recently did some improvements in beta branch, so you can try how it works now without fullReset attribute set to _true_

```
npm uninstall -g appium
npm install -g appium@1.6.4-beta
```

**Comment by hardik-d** [comment]
k will try it out

**Comment by hardik-d** [comment]
@mykola-mokhnach looks much better, thanks for the quick turn around on this!

**Comment by siggerzz** [comment]
I'm still seeing this issue when running tests in series on real iOS device when using Appium 1.6.5 😢

**Comment by fisnikbatusha** [comment]
I was also getting a similar error "Encountered internal error running command: Error: Url or Uri must start with ://".
Fixed it by replacing the target url from www.test.com to http://www.test.com
Wasted a couple of hours :(
