### ISSUE TITLE
Cannot find element after alert_accept

### ISSUE THREAD

**Issue by mjduvall** [appium/appium#7588]
## The problem

After accepting a system permissions alert, appium fails to locate an element. 

## Environment

* Appium 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): n/a
* Desktop OS/version used to run Appium: Mac 10.12.1
* Node.js version (unless using Appium.app|exe): v6.7.0
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

In my ruby script pasted below, after the first alert__accept (line 44), the Android dialogue box appears to go away, but I get the error "An element could not be located" on find__element(:id, 'com.myapp.app:id/grant__microphone__permission__button').click (line 48).

When I run it in ARC, I don't experience this issue. I've tried adding page right after the first alert__accept, but when I run the ruby script, I get no output. It's as if Appium has 'lost' my app, even though it is appearing on the screen.

## Link to Appium logs

<script src="https://gist.github.com/mjduvall/0e26524e0724bfad974f6df2f86407ca.js"></script>

## Code To Reproduce Issue [ Good To Have ]

<script src="https://gist.github.com/mjduvall/07610233f4ae8756cf08766b2513ea0c.js"></script>

**Comment by jlipps** [comment]
Are you sure it's not a timing issue? To check if it is, add a 5-10s sleep between the accept alert and the click. If that resolves the issue, it means you have a race condition of some kind and should account for that in your code (using some strategy other than a static sleep of course)

**Comment by mjduvall** [comment]
@jlipps I did try adding a 10, 20, and 60 second wait between the alert_accept and the next .click, but this did not resolve the issue.

**Comment by mykola-mokhnach** [comment]
@mjduvall What do you see in driver.getPageSource() output after the alert has been accepted?

**Comment by mjduvall** [comment]
If I add page to the script after the first alert accept, the script hangs
- it doesn't time out and there are no errors; it just sits.

When I step through the script using ARC, I can pull 'page' after the alert
accept and it contains the next button that I want to click.

**Comment by mykola-mokhnach** [comment]
Have you tried Appium 1.6.3? Do you see the same issue there?

**Comment by mjduvall** [comment]
I just updated and I'm seeing the same issue. What I don't understand is that it works in the Appium Ruby console, but the same code does not work in my script. There has to be something happening in ARC that isn't happening in my script, but I'm not sure how to pin that down.

**Comment by jlipps** [comment]
@mjduvall can you paste the output of your ARC session for comparison with your code?

**Comment by mjduvall** [comment]
When I last ran it in ARC, I was getting the permissions dialog, but I am not getting that now. Is there a way to automatically set permissions in my Ruby script, so that I don't get hung on this page?

**Comment by jlipps** [comment]
@mjduvall which type of permissions dialog is it?

**Comment by mjduvall** [comment]
We have a permissions page within the app where the user selects a button to grant permissions and that calls the associated system permission. It's after the system permission is accepted, using 'alert_accept', that I'm having the issue. 

I took another look and realized that I was running ARC with autoGrantPermissions set to True, which explains why I suddenly wasn't seeing the permissions issue. When I set that to false, here is the output from ARC:

If I run the script without any steps to debug:
[1] pry(main)> find_element(:id, 'android:id/content').click
true
[2] pry(main)> 
[3] pry(main)> find_element(:id, 'com.myapp.app:id/log_in_button').click
true
[4] pry(main)> 
[5] pry(main)> find_element(:id, 'android:id/content').click
true
[6] pry(main)> 
[7] pry(main)> @email = 'mandy@myapp.com'
[8] pry(main)> @password = 'password'
[9] pry(main)> 
[10] pry(main)> find_element(:id, 'com.myapp.app:id/change_email_dialog_fragment_email_edit_text').type(@email)
true
[11] pry(main)> find_element(:id, 'com.myapp.app:id/password_edit_text').type(@password)
true
[12] pry(main)> find_element(:id, 'com.myapp.app:id/log_in_button').click
true
[13] pry(main)> 
[14] pry(main)> 
[15] pry(main)> find_element(:id, 'com.myapp.app:id/grant_location_permission_button').click
true
[16] pry(main)> alert_accept
true
[17] pry(main)> find_element(:id, 'com.myapp.app:id/grant_microphone_permission_button').click
Selenium::WebDriver::Error::NoSuchElementError: An element could not be located on the page using the given search parameters.
from ....ruby-2.3.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'


And here it is when I replace the last find_element with page (an effort to see which elements ARE available):
[1] pry(main)> find_element(:id, 'android:id/content').click
true
[2] pry(main)> 
[3] pry(main)> find_element(:id, 'com.myapp.app:id/log_in_button').click
true
[4] pry(main)> 
[5] pry(main)> find_element(:id, 'android:id/content').click
true
[6] pry(main)> 
[7] pry(main)> @email = 'mandy@myapp.com'
[8] pry(main)> @password = 'password'
[9] pry(main)> 
[10] pry(main)> find_element(:id, 'com.myapp.app:id/change_email_dialog_fragment_email_edit_text').type(@email)
true
[11] pry(main)> find_element(:id, 'com.myapp.app:id/password_edit_text').type(@password)
true
[12] pry(main)> find_element(:id, 'com.myapp.app:id/log_in_button').click
true
[13] pry(main)> 
[14] pry(main)> page

android.widget.FrameLayout (1)
  id: android:id/content

android.widget.TextView (0)
  text: In order to give you the full myapp experience, the app needs the following permissions enabled:
  id: com.myapp.app:id/ap_mode_description_text_view
  strings.xml: permissions_description

android.widget.TextView (1)
  text: Location
  strings.xml: coarse_permission

android.widget.Button (0)
  text: Grant
  id: com.myapp.app:id/grant_location_permission_button
  strings.xml: grant

android.widget.TextView (2)
  text: Scans available Wi-Fi networks to properly sync your myapp.
  strings.xml: coarse_permission_description

android.widget.TextView (3)
  text: Microphone
  strings.xml: record_audio_permission

android.widget.Button (1)
  text: Grant
  id: com.myapp.app:id/grant_microphone_permission_button
  strings.xml: grant

android.widget.TextView (4)
  text: Enables the hold-to-talk functionality with on-demand calls.
  strings.xml: record_audio_permission_description

android.widget.TextView (5)
  text: Storage
  strings.xml: write_to_external_storage_permission

android.widget.Button (2)
  text: Grant
  id: com.myapp.app:id/grant_storage_permission_button
  strings.xml: grant

android.widget.TextView (6)
  text: Allows you to save recorded calls made or received from your myapp.
  strings.xml: write_to_external_storage_permission_description

android.view.View (0)
  id: android:id/statusBarBackground
nil
[15] pry(main)> 
[16] pry(main)> find_element(:id, 'com.myapp.app:id/grant_location_permission_button').click
true
[17] pry(main)> alert_accept
true
[18] pry(main)> 
[19] pry(main)> page

## I waited over five minutes before stopping the command and got: ##

^CInterrupt: 
from ..../ruby-2.3.0/lib/ruby/2.3.0/net/protocol.rb:158:in `wait_readable'

In the second session, after line 19, the appium server doesn't seem to be doing anything, meaning there is no output. Normally, when I run 'page' in ARC, there are several lines of output (i have logging set to verbose, I believe).

**Comment by jlipps** [comment]
I'm not sure, @mjduvall. The next thing I'd recommend is running `adb logcat` side by side with your ARC session, and see in the error cases if any  interesting exceptions pop up in the logcat logs.

**Comment by reach2jeyan** [comment]
@mjdetullio I am having the same issue when i am automating my tests with the ruby code. I am able to tap on that element using the inspector tool in appium but when I try to locate that element while running the test cases or by using the locator feature in appium, it isn't able to locate.

I see the same thing happening in 1.6.4 too. Any idea? if this is a appium issue?

**Comment by yu-t** [comment]
I see the same issue only on versions 7.0 and above.

**Comment by abisekkachroo** [comment]
Hi @mjduvall 
have you found a solution for this
i am getting the same issue on appium 1.6.4 and after the popup closes  my execution gets hanged
not able to do anything after that

**Comment by zwan2016** [comment]
Hi @abisekkachroo , try android 6.0 instead of 7.x, it woks for me.

**Comment by lironskycure** [comment]
I see the same issue on android 7.0 with appium 1.6.4.
As a workaround you relaunch the app and continue with the execution.

**Comment by lironskycure** [comment]
I see the same issue on android 7.0 with appium 1.6.4.
As a workaround you relaunch the app and continue with the execution.

**Comment by DmitryMarkovnikov** [comment]
I have the same issue on Android 7.x, after closing pop up window appium session can not display anything

**Comment by gkvappium** [comment]
Yes, I have seen the issue with Android 7.x as well. Looks like a UI automator issue. We hit this problem whenever there is a screen on top of another screen (Example Permission popup, contextual menu etc). Post this, appium fails to see the screen at all. At the moment I have been following these workarounds to mitigate the problem.

1. For the permission pop up, once I accept it, I do a self.driver.close_app() followed by launch_app().
2. For other contextual menu screens, I do a self.driver.back() and comeback to the same screen

https://github.com/appium/appium/issues/8879

**Comment by anonygoose** [comment]
Also suffering from this same problem on Android 7.0.

Same symptoms.  Can't find elements after dismissing a system alert, and doing a driver.getPageSource() hangs indefinitely.

**Comment by sikhwalanil2** [comment]
Hi, After closing popup, use this,
try{
	driver.runAppInBackground(1);
}catch(Exception e){}

It works for 7.x devices

**Comment by krirohini** [comment]
I tried 
try{
driver.runAppInBackground(1);
}catch(Exception e){}

and worked fine.
Thanks

**Comment by abhijeetnimbalkar** [comment]
@gkvappium

**Comment by abhijeetnimbalkar** [comment]
Thanks @anonygoose 
Using uiautomator2 solved my problem. 
Also uninstalled appium setting. 
Thanks.

**Comment by sqxz** [comment]
@sikhwalanil2 this way could back to the AUT,this issue would not exist;

**Comment by JeanMaritain** [comment]
@mjduvall
try this after your alert_accept 
```python
duration = 0.1  # seconds
driver.background_app(duration)
```
