### ISSUE TITLE
Appium fails to findElements and perform action in CreateContact screen

### ISSUE THREAD

**Issue by SatishKumarKV** [appium/appium#7590]
## The problem

Appium fails to findElements and perform action in CreateContact screen
**While parsing the screen for elements, looks like it is stuck at Postal Code**
![img_0002](https://cloud.githubusercontent.com/assets/22965310/21418600/5d97f058-c848-11e6-8f85-7fc508cfc3f0.PNG)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6.1
* Desktop OS/version used to run Appium: All
* Node.js version (unless using Appium.app|exe): Latest
* Mobile platform/version under test: iOS 10
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe:CLI

## Details

1. We have an app which allows users to create a contact.
2. When driver ends up in this page. It parses and gets all the elements.
3. This screen has lot of textFields in it. Please check contacts Native app and try to create a contact.
4. Now try to click on first name or any other text field within the screen.

Found that when driver tries to find an element in this screen..
1. Cursor moves to end of the screen , to the last texField in the screen.
2. Try to find an element or scrolluptoElement will fails and cursor will be forced to stay at last textFiled ( Postcode textField )

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Can you also attach page source returned by driver.getPageSource() and piece of your code where click is happening?

**Comment by SatishKumarKV** [comment]
@mykola-mokhnach 
getPageSource() is failing just for this screen. Tried with both HTML inspector as well as GUI appium version.

**Comment by mykola-mokhnach** [comment]
Update Appium to the most recent version and add the visibility patch described in https://github.com/facebook/WebDriverAgent/issues/372
This might help. There's nothing we can do from Appium side to solve this.

**Comment by SatishKumarKV** [comment]
@mykola-mokhnach 
After lot of tries on this screen , I am able to capture its XML. Please check once..
`<?xml version="1.0" encoding="UTF-8"?>
<AppiumAUT>
    <XCUIElementTypeApplication name="MaaS360" label="MaaS360" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0" x="0" y="0" width="375" height="667">
        <XCUIElementTypeWindow name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0" x="0" y="0" width="375" height="667">
            <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0" x="0" y="0" width="375" height="667">
                <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0" x="0" y="0" width="375" height="667">
                    <XCUIElementTypeNavigationBar name="New Contact" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0" x="0" y="20" width="375" height="44">
                        <XCUIElementTypeButton name="Cancel" label="Cancel" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0/0" x="16" y="27" width="53" height="30">
                        </XCUIElementTypeButton>
                        <XCUIElementTypeStaticText name="New Contact" label="New Contact" value="New Contact" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/0/1" x="136" y="28" width="104" height="27">
                        </XCUIElementTypeStaticText>
                        <XCUIElementTypeButton name="Save" label="Save" value="" dom="" enabled="false" valid="true" visible="true" hint="" path="/0/0/0/0/0/2" x="315" y="30" width="44" height="24">
                        </XCUIElementTypeButton>
                    </XCUIElementTypeNavigationBar>
                    <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1" x="0" y="0" width="375" height="667">
                        <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0" x="0" y="0" width="375" height="667">
                            <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0" x="0" y="64" width="375" height="603">
                                <XCUIElementTypeTable name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0" x="0" y="64" width="375" height="603">
                                    <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/0" x="0" y="-867" width="375" height="1">
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/1" x="0" y="-999" width="375" height="133">
                                        <XCUIElementTypeTextField name="" label="" value="First Name" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/1/0" x="0" y="0" width="245" height="25">
                                        </XCUIElementTypeTextField>
                                        <XCUIElementTypeTextField name="" label="" value="Middle Name" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/1/1" x="0" y="0" width="245" height="25">
                                        </XCUIElementTypeTextField>
                                        <XCUIElementTypeTextField name="" label="" value="Last Name" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/1/2" x="0" y="0" width="245" height="25">
                                        </XCUIElementTypeTextField>
                                        <XCUIElementTypeTextField name="" label="" value="Salutation" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/1/3" x="0" y="0" width="245" height="25">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/2" x="0" y="-717" width="375" height="0">
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/3" x="0" y="-849" width="375" height="44">
                                        <XCUIElementTypeStaticText name="Job Title" label="Job Title" value="Job Title" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/3/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Job Title" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/3/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/4" x="0" y="-805" width="375" height="44">
                                        <XCUIElementTypeStaticText name="Dept" label="Dept" value="Dept" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/4/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Department" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/4/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/5" x="0" y="-761" width="375" height="44">
                                        <XCUIElementTypeStaticText name="Company" label="Company" value="Company" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/5/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Company" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/5/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/6" x="0" y="-348" width="375" height="21">
                                        <XCUIElementTypeStaticText name="Phone" label="Phone" value="Phone" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/6/0" x="0" y="-348" width="375" height="21">
                                        </XCUIElementTypeStaticText>
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/7" x="0" y="-680" width="375" height="45">
                                        <XCUIElementTypeStaticText name="Mobile" label="Mobile" value="Mobile" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/7/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Mobile" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/7/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/8" x="0" y="-636" width="375" height="45">
                                        <XCUIElementTypeStaticText name="Home" label="Home" value="Home" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/8/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Home 1" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/8/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/9" x="0" y="-592" width="375" height="45">
                                        <XCUIElementTypeStaticText name="Home" label="Home" value="Home" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/9/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Home 2" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/9/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/10" x="0" y="-548" width="375" height="45">
                                        <XCUIElementTypeStaticText name="Work" label="Work" value="Work" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/10/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Work 1" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/10/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/11" x="0" y="-504" width="375" height="45">
                                        <XCUIElementTypeStaticText name="Work" label="Work" value="Work" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/11/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Work 2" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/11/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/12" x="0" y="-460" width="375" height="45">
                                        <XCUIElementTypeStaticText name="Assistant" label="Assistant" value="Assistant" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/12/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Assistant" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/12/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/13" x="0" y="-416" width="375" height="45">
                                        <XCUIElementTypeStaticText name="Pager" label="Pager" value="Pager" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/13/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Pager" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/13/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/14" x="0" y="-372" width="375" height="45">
                                        <XCUIElementTypeStaticText name="Business Fax" label="Business Fax" value="Business Fax" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/14/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Business Fax" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/14/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/15" x="0" y="-178" width="375" height="20">
                                        <XCUIElementTypeStaticText name="e-mail" label="e-mail" value="e-mail" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/15/0" x="0" y="-178" width="375" height="20">
                                        </XCUIElementTypeStaticText>
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/16" x="0" y="-290" width="375" height="44">
                                        <XCUIElementTypeStaticText name="Work" label="Work" value="Work" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/16/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="E-mail Address" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/16/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/17" x="0" y="-246" width="375" height="44">
                                        <XCUIElementTypeStaticText name="Home" label="Home" value="Home" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/17/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="E-mail Address" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/17/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/18" x="0" y="-202" width="375" height="44">
                                        <XCUIElementTypeStaticText name="Other" label="Other" value="Other" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/18/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="E-mail Address" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/18/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/19" x="0" y="64" width="375" height="20">
                                        <XCUIElementTypeStaticText name="Home Address" label="Home Address" value="Home Address" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/19/0" x="0" y="64" width="375" height="20">
                                        </XCUIElementTypeStaticText>
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/20" x="0" y="-121" width="375" height="45">
                                        <XCUIElementTypeStaticText name="Street" label="Street" value="Street" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/20/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Street" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/20/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/21" x="0" y="-77" width="375" height="45">
                                        <XCUIElementTypeStaticText name="City" label="City" value="City" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/21/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="City" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/21/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/22" x="0" y="-33" width="375" height="45">
                                        <XCUIElementTypeStaticText name="State" label="State" value="State" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/22/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="State" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/22/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/23" x="0" y="11" width="375" height="45">
                                        <XCUIElementTypeStaticText name="Country" label="Country" value="Country" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/23/0" x="0" y="0" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Country" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/23/1" x="0" y="0" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/24" x="0" y="55" width="375" height="45">
                                        <XCUIElementTypeStaticText name="Postal Code" label="Postal Code" value="Postal Code" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/24/0" x="15" y="55" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Postal Code" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/24/1" x="140" y="63" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/25" x="0" y="117" width="375" height="20">
                                        <XCUIElementTypeStaticText name="Business Address" label="Business Address" value="Business Address" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/25/0" x="0" y="117" width="375" height="20">
                                        </XCUIElementTypeStaticText>
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/26" x="0" y="137" width="375" height="44">
                                        <XCUIElementTypeStaticText name="Street" label="Street" value="Street" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/26/0" x="15" y="137" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Street" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/26/1" x="140" y="145" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/27" x="0" y="181" width="375" height="44">
                                        <XCUIElementTypeStaticText name="City" label="City" value="City" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/27/0" x="15" y="181" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="City" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/27/1" x="140" y="189" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/28" x="0" y="225" width="375" height="44">
                                        <XCUIElementTypeStaticText name="State" label="State" value="State" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/28/0" x="15" y="225" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="State" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/28/1" x="140" y="233" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/29" x="0" y="269" width="375" height="44">
                                        <XCUIElementTypeStaticText name="Country" label="Country" value="Country" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/29/0" x="15" y="269" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Country" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/29/1" x="140" y="277" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/30" x="0" y="313" width="375" height="44">
                                        <XCUIElementTypeStaticText name="Postal Code" label="Postal Code" value="Postal Code" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/30/0" x="15" y="313" width="120" height="44">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeTextField name="" label="" value="Postal Code" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/30/1" x="140" y="321" width="225" height="28">
                                        </XCUIElementTypeTextField>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/31" x="0" y="374" width="375" height="21">
                                        <XCUIElementTypeStaticText name="GROUP" label="GROUP" value="GROUP" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/31/0" x="0" y="374" width="375" height="21">
                                        </XCUIElementTypeStaticText>
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/32" x="0" y="394" width="375" height="45">
                                        <XCUIElementTypeStaticText name="Folder" label="Folder" value="Folder" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/32/0" x="15" y="405" width="52" height="22">
                                        </XCUIElementTypeStaticText>
                                        <XCUIElementTypeStaticText name="Contacts" label="Contacts" value="Contacts" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/0/1/0/0/0/32/1" x="266" y="405" width="74" height="22">
                                        </XCUIElementTypeStaticText>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/33" x="0" y="456" width="375" height="20">
                                        <XCUIElementTypeStaticText name="Notes" label="Notes" value="Notes" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/33/0" x="0" y="456" width="375" height="20">
                                        </XCUIElementTypeStaticText>
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/34" x="0" y="476" width="375" height="154">
                                        <XCUIElementTypeTextView name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/34/0" x="12" y="484" width="359" height="120">
                                        </XCUIElementTypeTextView>
                                    </XCUIElementTypeCell>
                                    <XCUIElementTypeOther name="BUSINESS ADDRESS" label="BUSINESS ADDRESS" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/35" x="0" y="117" width="375" height="20">
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeOther name="GROUP" label="GROUP" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/36" x="0" y="374" width="375" height="21">
                                    </XCUIElementTypeOther>
                                    <XCUIElementTypeOther name="NOTES" label="NOTES" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/1/0/0/0/37" x="0" y="456" width="375" height="20">
                                    </XCUIElementTypeOther>
                                </XCUIElementTypeTable>
                            </XCUIElementTypeOther>
                        </XCUIElementTypeOther>
                    </XCUIElementTypeOther>
                </XCUIElementTypeOther>
            </XCUIElementTypeOther>
            <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/1" x="330" y="467" width="45" height="45">
                <XCUIElementTypeButton name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/1/0" x="330" y="467" width="45" height="45">
                </XCUIElementTypeButton>
            </XCUIElementTypeOther>
        </XCUIElementTypeWindow>
        <XCUIElementTypeWindow name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/1" x="0" y="0" width="375" height="667">
            <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/1/0" x="0" y="0" width="375" height="667">
            </XCUIElementTypeOther>
        </XCUIElementTypeWindow>
        <XCUIElementTypeWindow name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2" x="0" y="0" width="375" height="667">
            <XCUIElementTypeStatusBar name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2/0" x="0" y="0" width="375" height="20">
                <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/2/0/0" x="0" y="0" width="375" height="20">
                </XCUIElementTypeOther>
                <XCUIElementTypeOther name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2/0/1" x="0" y="0" width="375" height="20">
                    <XCUIElementTypeOther name="3 of 5 bars, signal strength" label="3 of 5 bars, signal strength" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2/0/1/0" x="6" y="0" width="35" height="20">
                    </XCUIElementTypeOther>
                    <XCUIElementTypeOther name="Jio network" label="Jio network" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2/0/1/1" x="44" y="0" width="17" height="20">
                    </XCUIElementTypeOther>
                    <XCUIElementTypeOther name="LTE" label="LTE" value="SSID" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2/0/1/2" x="70" y="0" width="17" height="20">
                    </XCUIElementTypeOther>
                    <XCUIElementTypeOther name="11:55 PM" label="11:55 PM" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2/0/1/3" x="162" y="0" width="54" height="20">
                    </XCUIElementTypeOther>
                    <XCUIElementTypeOther name="Orientation Locked" label="Orientation Locked" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2/0/1/4" x="290" y="0" width="12" height="20">
                    </XCUIElementTypeOther>
                    <XCUIElementTypeOther name="StandardLocationTrackingOn" label="Location tracking on" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2/0/1/5" x="308" y="0" width="9" height="20">
                    </XCUIElementTypeOther>
                    <XCUIElementTypeOther name="Bluetooth on" label="Bluetooth on" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2/0/1/6" x="323" y="0" width="8" height="20">
                    </XCUIElementTypeOther>
                    <XCUIElementTypeOther name="100% battery power, Charging" label="100% battery power, Charging" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/2/0/1/7" x="337" y="0" width="33" height="20">
                    </XCUIElementTypeOther>
                </XCUIElementTypeOther>
            </XCUIElementTypeStatusBar>
        </XCUIElementTypeWindow>
    </XCUIElementTypeApplication>
</AppiumAUT>`
