### ISSUE TITLE
Appium 1.6.3 XCUITest - iOS 10 Tests Are Running Very Slow

### ISSUE THREAD

**Issue by RashmiMurthy** [appium/appium#7591]
## The problem

Tests running using Appium 1.6.3 XCUITest is very slow

findelement by xpath take very very long time.Test stuck for few seconds on finding element before proceeding to execute any task. I have to use XPATH locator majorly as in my app its not possible to find elements using Accessibility ID.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):1.5.3
* Device OS/version used to run Appium:iOS 10.1 iPAD
* Real device or emulator/simulator: Real device

## Sample XPATHs:

//XCUIElementTypeStaticText[contains(@name,'FIRST NAME')]
//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeButton[1]

Thanks...

**Comment by mykola-mokhnach** [comment]
Known [WDA issue](https://github.com/facebook/WebDriverAgent/issues/372)
