### ISSUE TITLE
Inspector does not open main window. Driver permanently wait for server response.

### ISSUE THREAD

**Issue by MikeFursov** [appium/appium#7592]
## The problem

After starting Appium inspector, driver permanently wait for server response, Inspector does not open main window.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): unknown
* Desktop OS/version used to run Appium: MacOS 10.12 Sierra
* Node.js version (unless using Appium.app|exe): 6.3.1
* Mobile platform/version under test: iOS 10.1.1
* Real device or emulator/simulator: real device
* Appium.app: 1.5.3

## Details

In Appium.app set external Appium package installed globally.
When I try to start Inspector, atfer installing testing app and running WebDriverAgentRunner in Appium.app console displayed next permanently repeated messages:

`[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - `

Inspector does not open main window.

## Link to Appium logs

[Full Appium logs](https://gist.github.com/MikeFursov/25820949b5117531a7ae3381ba38f461)

## Code To Reproduce Issue [ Good To Have ]

None

**Comment by dpgraham** [comment]
Inspector doesn't support 1.6.3

We have a new GUI in progress called appium-desktop which should be released within the next few weeks.
