### ISSUE TITLE
How to get the url of WebView?

### ISSUE THREAD

**Issue by Mygod** [appium/appium#7594]
Original issue: https://github.com/appium/appium-uiautomator2-server/issues/44

```
for (WebElement element : driver.findElementsByTagName("android.webkit.WebView"))
    if (someRules(element)) {
        String handle = /* element.getWindowHandle()? */;
        driver.context("WEBVIEW_" + getPackageName());
        driver.switchTo().window(handle);
        System.out.println(driver.getCurrentUrl());
    }
```

I can also get all the window handles by calling `driver.getWindowHandles()` but is it possible to know which WebView uses which handle?

**Comment by dpgraham** [comment]
Hi @Mygod, what happens when you run this code? Does driver.getCurrentUrl() do anything?

**Comment by Mygod** [comment]
Yes. The problem is how to retrieve the window handle for a specific webview.

**Comment by dpgraham** [comment]
I understand now. You're trying to infer the window handle from the web element. I couldn't uncover any such functionality. 

@jlipps and @imurchie Do either of you know of a way to do this?

**Comment by jlipps** [comment]
Right now there's no way to select a webview based on its url. You need to switch into the context then call `GET /url` to determine the url.

Also, I'm unclear why you're working with window handles. Typically you'd care about context, not window handles, in mobile tests.

**Comment by Mygod** [comment]
Well I'm working on a test bot so I'm wishing to use this feature. So this won't be implemented in the near future right?

**Comment by jlipps** [comment]
@Mygod correct, there are no plans to build this feature at the moment. If you research and discover a way for us to get the url of a webview internally, maybe there's a case for expanding the protocol to include `GET /context/:name` to retrieve information about the webview including url.
