### ISSUE TITLE
Appium failure attempting to set the date via exec("adb shell 'date...

### ISSUE THREAD

**Issue by rhyjouett** [appium/appium#7595]
## The problem
Appium crash attempting to set the date via exec("adb shell 'date #{mm}#{dd}#{hh}#{mn}#{yyyy}.00'")

## Environment
* Appium version (or git revision) that exhibits the issue: 1.5.3 (Ara)
* Desktop OS/version used to run Appium: OS X, 10.10.5 (14F1021)
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android 6.0 - API Level 23
* Real device or emulator/simulator: AVD Device: Nexus 6
* Appium CLI or Appium.app|exe: Appium.app

## Details
I have a need to set the device date/time. I found no built-in appium method for doing this so i wrote one (see gist below). The code executes and correctly sets the emulator's time but appium crashes. The logs don't indicate that there's been a crash.

## Link to Appium, adb logs and command line results
https://gist.github.com/rhyjouett/7d36a377e6704c5c1a2cbd1729a49262

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/rhyjouett/55f560f6f8474cd81ce1a17b73aa5056

**Comment by dpgraham** [comment]
When does the crash happen? I don't see any errors.

**Comment by rhyjouett** [comment]
The failure happens when the exec line executes `exec("adb shell 'date #{mm}#{dd}#{hh}#{mn}#{yyyy}.00'")` There's nothing i see that really indicates a crash. However the behavior is: 
* the tests fails to complete
* the command line displays the date/time and returns control (the test quits)
* subsequent attempts to run appium tests without relaunching results in `[HTTP] <-- POST /wd/hub/session 500 4 ms - 193`

**Comment by rhyjouett** [comment]
One more note: i change the description from 
`Appium crash attempting to set the date via exec("adb shell 'date...` to 
`Appium failure attempting to set the date via exec("adb shell 'date...`

**Comment by rhyjouett** [comment]
A bit more info: I was wondering i the problem is with the specific adb command or with exec() so i changed the command to a simple `exec("ENV > /dev/nul")`, that results in the same behavior. Conclusion: the problem isn't with the adb command or the bash output, it's with exec.

**Comment by rhyjouett** [comment]
After digging around in the Kernel module, i've found the following:
For Kernel.exec `# Replaces the current process by running the given external _command_...`
for Kernel.system `# Executes _command..._ in a subshell.`

These methods are behaving as specified. #system does what i'm wanting whereas #exec replaces the currently running of the tests (and seems to bork appium until it's stop/launched again).

**Comment by jlipps** [comment]
Why is it necessary to set the date on the emulator in the middle of a test? Can you set it before starting Appium? Seems like changing the date/time while other processes are running on the emulator has weird consequences.

**Comment by rhyjouett** [comment]
There are legitimate test scenarios for 
* doing something
* waiting some period of time (10 minutes, a day, a month, whatever)
* doing some else
If i set the time before selenium/appium loads, i can't run these type of scenarios. 

In any case, my problem is solved using a `Kernel.system` (which uses a sub-shell) vs. `Kernel.exec` (which replaces the current shell). IMHO, i'm not convinced this is a bug; or that it's Appium's job to recover from a hijacked shell.

**Comment by rahulmr** [comment]
@rhyjouett  is it possible for you to share how you did the time settings? Is there any way we can do this using webdriverio?
Actually, in my case I can set the time before starting tests also. My scenario is like I want to set the device with Kenya time zone date and time settings.

**Comment by rhyjouett** [comment]
@rahulmr i've posted some code for setting time in stackoverflow. If you find it useful, please +1 my answer: http://stackoverflow.com/questions/36648080/appium-set-custom-time-programatically-on-emulator-or-saucelabs/41349574#41349574
