### ISSUE TITLE
Not able to set Geo location on google map by passing lat and long in Appium

### ISSUE THREAD

**Issue by prem0144** [appium/appium#7596]
## The problem
Showing error FAILED CONFIGURATION: @BeforeClass setUp org.openqa.selenium.WebDriverException: ERROR running Appium command: port should be string=false

## Code To Reproduce Issue [ Good To Have ]

package Test;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.html5.Location;
//import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.*;

public class FullHouse {
	WebDriver driver;

@BeforeClass
public void setUp() throws MalformedURLException{
	//Set up desired capabilities and pass the Android app-activity and app-package to Appium
	DesiredCapabilities capabilities = new DesiredCapabilities();
	capabilities.setCapability("BROWSER_NAME", "");
	capabilities.setCapability("platformName","Android");
	capabilities.setCapability("deviceName","emulator-5554");
    capabilities.setCapability("platformVersion", "5.1");
    
  
    capabilities.setCapability("appPackage","com.google.android.apps.maps");
   
    capabilities.setCapability("appActivity","com.google.android.maps.MapsActivity");
 //It will launch the Calculator App in Android Device using the configurations specified in Desired Capabilities
   //driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
  
  AppiumDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
 // WebDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),getDesiredCapabilities("192.21.168.56:5555"));
  Location location = new Location(77.59974003, 12.91024781, 909);
  driver.setLocation(location);
  driver.manage().timeouts().implicitlyWait(200, TimeUnit.SECONDS);
   //driver.manage().timeouts().implicitlyWait(100, TimeUnit.SECONDS);
   
}

@Test
public void testCal() throws Exception {
   Some test here

}

@AfterClass
public void teardown(){
	//close the app
	driver.quit();
}
}

**Comment by SrinivasanTarget** [comment]
Been tracked on #7151
