### ISSUE TITLE
Appium Java client shows longPress duration in ms

### ISSUE THREAD

**Issue by SatishKumarKV** [appium/appium#7597]
## The problem

LongPress not working with 1.6 Appium

EDIT: The JavaDocs say that longPress delays are in 'milliseconds' (http://appium.github.io/java-client/) but in appium-xcuitest-driver it takes the value in seconds. We'll either need to update the documentation to say seconds or we need to update the appium-xcuitest-driver to accept values in milliseconds --DG

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: CLI

## Details

LongPress not working with 1.6 Appium

## Link to Appium logs

**Logs for long press on element identified by name**
`[HTTP] --> POST /wd/hub/session/2146c03a-c5fc-45ac-9378-8151e0517557/element {"using":"name","value":"dignity"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["name","dignity","2146c03a-c5fc-45ac-9378-8151e0517557"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 15000 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/3AB1197C-E5B9-41CC-AA06-6B66ED8B6E27/element] with body: {"using":"name","value":"dignity"}
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"162E9DA8-A474-4941-A2F8-A4529F37C2DD","type":"XCUIElementTypeStaticText","label":"dignity"},"sessionId":"3AB1197C-E5B9-41CC-AA06-6B66ED8B6E27","status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"162E9DA8-A474-4941-A2F8-A4529F37C2DD","type":"XCUIElementTypeStaticText","label":"dignity"}
[HTTP] <-- POST /wd/hub/session/2146c03a-c5fc-45ac-9378-8151e0517557/element 200 630 ms - 178 
[HTTP] --> POST /wd/hub/session/2146c03a-c5fc-45ac-9378-8151e0517557/touch/perform {"actions":[{"action":"longPress","options":{"element":"162E9DA8-A474-4941-A2F8-A4529F37C2DD","duration":3000}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"element":"162E9DA8-A474-4941-A2F8-A4529F37C2DD","duration":3000}}],"2146c03a-c5fc-45ac-9378-8151e0517557"]
[debug] [XCUITest] Executing command 'performTouch'
[JSONWP Proxy] Proxying [POST /uiaElement/162E9DA8-A474-4941-A2F8-A4529F37C2DD/touchAndHold] to [POST http://localhost:8100/session/3AB1197C-E5B9-41CC-AA06-6B66ED8B6E27/uiaElement/162E9DA8-A474-4941-A2F8-A4529F37C2DD/touchAndHold] with body: {"duration":3000}
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...
[debug] [XCUITest] Waiting for WebDriverAgent server to finish loading...`

## Code To Reproduce Issue [ Good To Have ]

**Code for long press**
`TouchAction myAction = new TouchAction(IOSAppiumConnection.driver);
myAction.longPress(findBy(By.name(textToBeChecked), timeout) , 3000).perform().release();`

Also tried

`TouchAction myAction = new TouchAction(IOSAppiumConnection.driver);
myAction.longPress(findBy(By.name(textToBeChecked), timeout) , 3000).perform();
myAction.release();`

**Comment by SatishKumarKV** [comment]
According to Documentation , TouchAction time is suppose to be in milliseconds , same above code worked after change time from 3000 to 3.

**Comment by dpgraham** [comment]
Xcuitest Driver takes the values in seconds. The documentation is incorrect. Thanks for pointing that out for us. We'll put this as a fix on our backlog but until then just keep using longPress in milliseconds.

**Comment by dpgraham** [comment]
Hi @SatishKumarKV, we finally got around to looking at this issue. Turns out that using seconds for xcuitest was incorrect and we should have been using ms. Thanks for pointing this out for us.

Just to let you know, we updated appium to use `ms` instead of `s` so for future versions of Appium (> 1.6.4) you'll need to revert back to using the duration parameter in `ms`.

**Comment by mykola-mokhnach** [comment]
java client since 5.0.0-BETA7 supports the built in Java 8 **Duration** type for time periods, which allows to avoid such issues.

**Comment by dpgraham** [comment]
The problem was with xcuitest-driver which was accepting numbers in `s` when it should have been `ms`
