### ISSUE TITLE
Error connecting to device!

### ISSUE THREAD

**Issue by Timoxa84** [appium/appium#7598]
## The problem

Appium does not always start the test. 

## Environment

* Appium v1.6.3.
* Desktop OS/version used to run Appium: OS X EL Capitan
* Node.js version : v6.6.0
* Mobile platform/version under test: iOS 10.0.1
* Real device or emulator/simulator: iPhone 6 Plus
* Appium CLI or Appium.app|exe: CLI

## Details

I have met the issue with starting of the tests, very often it fails to start. To avoid this issue I have updated Appium and the libimobiledevice with the following commands:

```
- npm install -g appium
- brew install libimobiledevice --HEAD
```

However it does not solve the issue. Moreover i am restarting the appium along with the following commands:

```
ps -ax|grep -i "idevicesyslog"|grep -v grep|awk '{print "kill -9 " $1}'|sh
ps -ax|grep -i "xcodebuild"|grep -v grep|awk '{print "kill -9 " $1}'|sh
ps -ax|grep -i "iproxy"|grep -v grep|awk '{print "kill -9 " $1}'|sh
```

The current issue could be duplicate of: 
https://github.com/appium/appium/issues/7192
https://github.com/appium/appium/issues/7063
 
## Link to Appium logs

https://gist.github.com/Timoxa84/1d1861defc6b919310f0c7ce589cf658

**Comment by mykola-mokhnach** [comment]
I think it has never been stable with multiple iOS devices connected to the same host.

**Comment by Timoxa84** [comment]
That is bad. Thank you @mykola-mokhnach for the response.

**Comment by vikramvi** [comment]
@Timoxa84 can you please clarify how are you connecting to multiple devices ? Are you using Selenium HUB or something else ? 

If you can share sample project can be helpful to debug and get this important bug prioritized for upcoming release. 

As not all companies can afford to run daily regression runs on cloud based services, it will be nice to get this fixed earlier.

**Comment by jlipps** [comment]
Looking at the logs, it doesn't seem that Appium is failing. Rather it seems iproxy somehow disconnects to the device or otherwise gets confused. Any reason that could be?

**Comment by Timoxa84** [comment]
@vikramvi indeed I am using Selenium HUB to run my tests, 

To start Appium I'm using bash script:

```
#!/bin/bash

nohup /usr/local/bin/node /appium/appium --address <My IP> --port 4721 --command-timeout 600000 --session-override --nodeconfig /appium/iPhone/nodeAppiumiPhone.json --debug-log-spacing --udid <my iPhone UDID> > /logs/appiumFromCmdiPhone.log --tmp /appium/iPhone/tmp_iphone 2>&1 < /dev/null &

PID=$!
echo $PID > /appium/iPhone/pidAppiumFromCmdiPhone.txt

nohup /usr/local/bin/node /usr/local/lib/node_modules/appium --address <My IP> --port 4725 --command-timeout 600000 --session-override --nodeconfig /appium/iPad/nodeAppiumiPad.json --debug-log-spacing  --udid <My iPad UDID> > /logs/appiumFromCmdiPad.log --tmp /appium/iPad/tmp_ipad 2>&1 < /dev/null &

PID=$!
echo $PID > /appium/iPad/pidAppiumFromCmdiPad.txt
```


_**nodeAppiumiPhone.json**_

```
{
  "capabilities":
      [
        {
		"browserName": "iPhone",
		"version":"9.3",
		"selenimProtocol": "WebDriver",
		"platformName":"iOS",
		"maxInstances":1,
		"deviceName":"iPhone5s",
      		"showIOSLog":"true",
		"platform":"MAC"
        }
      ],
  "configuration":
  {

    "cleanUpCycle":2000,
    "timeout":600000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "host": "<My IP>",
    "port": 4723,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
	  "hubPort": 4444,
    "hubHost": "Selenium HUB IP"
  }
}

```
**_nodeAppiumiPad.json_** similar to **_nodeAppiumiPhone.json_** the only diffrence is `"browserName": "iPad".`

I am using Java and TestNG with `parallel="methods"`. For each method, I am passing the `wdaLocalPort` and `browserName`. So that the way.

However, I found the solution. Restoring of the device to the factory settings solved the issue. Currently works well for me.
Thank you guys for participating. 
@jlipps  could you please close the issue.

**Comment by vikramvi** [comment]
@triager please close per last comment
