### ISSUE TITLE
Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

### ISSUE THREAD

**Issue by swachhab** [appium/appium#7599]
## The problem

I am stuck while automating IOS 10 using appium.. Test target WebDriverAgentRunner encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)

desired_caps['platformName'] = 'IOS'
desired_caps['platformVersion'] = '10.1.1'
desired_caps['deviceName'] = 'Iphone 5'
desired_caps['udid'] = '********'
desired_caps['app'] = <APP_PATH>
desired_caps['realDeviceLogger'] = '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
desired_caps['automationName'] = 'XCUITest'

## Environment

Appium: 1.6.3
IOS 10.1
Xcode 8.1
Node 4.0.5

## Details

I have added all the dependencies including changes in xcode for WebDriverAgent file and given xcconfig cap as well. Still the same same error.

## Link to Appium logs

Detailed Logs of xcuitest as well xcode: https://gist.github.com/swachhab/0ce715b6264ccab14b13e5c41fb17363

Please help me out.

**Comment by mykola-mokhnach** [comment]
Pay attention to this log line:

> [Xcode] 2016-12-23 19:55:41.244 xcodebuild[15951:345008] Error Domain=com.apple.platform.iphoneos Code=-12 "Unable to launch com.apple.test.WebDriverAgentRunner-Runner" UserInfo={NSLocalizedDescription=Unable to launch com.apple.test.WebDriverAgentRunner-Runner, NSUnderlyingError=0x7fcdb83d89c0 {Error Domain=DTXMessage Code=1 "(null)" UserInfo={DTXExceptionKey=The operation couldn’t be completed. Unable to launch com.apple.test.WebDriverAgentRunner-Runner because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user. : Failed to launch process with bundle identifier 'com.apple.test.WebDriverAgentRunner-Runner'}}}

Something is wrong with code signing. Can you check WDA source building manually using Xcode?

**Comment by swachhab** [comment]
@ @mykola-mokhnach thanks for the reply, It got resolved after downgrading appium to 1.6.1.

**Comment by swachhab** [comment]
@mykola-mokhnach  Need another help as am getting exception while running touch action functions like Pinch(x,y).Perform() in AppiumV1.6.1 with IOS 10.1. Does appium 1.6.1 supports it?

**Comment by mykola-mokhnach** [comment]
it would be better if you try it with the most recent version available. Although, as far as I know, many gesture actions are still missing there.

**Comment by swachhab** [comment]
@mykola-mokhnach Thanks for the prompt reply. 
But if I go back to v1.6.3, the above code signing issue occurs. And all gesture actions are available in latest version(1.6.3)?
