### ISSUE TITLE
Appium IOSDriver enters first few chars in send keys method

### ISSUE THREAD

**Issue by gopi09m** [appium/appium#7600]
## The problem

org.openqa.selenium.WebDriverException  An unknown server-side error occurred while processing the command. Original error Error Domain XCTestManagerErrorDomain Code=14 "Timed out waiting for key event to complete" UserInfo={NSLocalizedDescription=Timed out waiting for key event to complete} (WARNING: The server did not provide any stacktrace information

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Last Appium version that did not exhibit the issue (if applicable): 1.6
* Desktop OS/version used to run Appium: mac 10.12
* Node.js version (unless using Appium.app|exe): latest
* Mobile platform/version under test: iOS 10.1
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: 1.6.1

## Details

Send keys sometimes skips last few chars and gives following error.

org.openqa.selenium.WebDriverException  An unknown server-side error occurred while processing the command. Original error Error Domain XCTestManagerErrorDomain Code=14 "Timed out waiting for key event to complete" UserInfo={NSLocalizedDescription=Timed out waiting for key event to complete} (WARNING: The server did not provide any stacktrace information

**Comment by dpgraham** [comment]
Can you provide the logs leading up to the error and provide a code snippet?

**Comment by mykola-mokhnach** [comment]
I believe this is WDA/XCTest issue. I can observe it randomly in my automated tests, but I cannot understand why the timeout happens.

**Comment by dpgraham** [comment]
Does this problem happen consistently? I'd be curious to see if we can re-create it.

**Comment by gopi09m** [comment]
Yes, i can recreate it consistently..

**Comment by dpgraham** [comment]
Can you provide a code snippet and server logs? I'd like to try duplicating it on my side. I have a feeling it's a wda or xctest issue but I'd like to confirm it.

**Comment by gopi09m** [comment]
sorry, its not very consistent. i will provide the detailed log next time i see that error again.

**Comment by pisarenco92** [comment]
I have the same problem (Appium 1.6.3, iOS simulator 10.2).

**Comment by yashzanwar** [comment]
is there any solution to this problem?
