### ISSUE TITLE
Appium doesn't take my xpath value instead takes value as "xpath"

### ISSUE THREAD

**Issue by gopi09m** [appium/appium#7601]
## The problem

I use xpath at many places but at one particular screen it doesn't work.Appium doesn't take my xpath value instead takes value as "xpath". E.g. xpath i am using is below.I am trying to do a click action to open keyboard and type some text using send keys. but only for one screen it enables to find elements by xpath.

//XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[7]/XCUIElementTypeTextField

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: mac 10.12
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

[debug] [XCUITest] Executing command 'timeouts'
[debug] [iOS] Set page load timeout to 60000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/f2899102-c482-49ac-a306-0c10273b896e/timeouts 200 2 ms - 76 
[debug] [iProxy] recv failed: Resource temporarily unavailable
[debug] [iProxy] recv failed: Operation not permitted
[HTTP] --> POST /wd/hub/session/f2899102-c482-49ac-a306-0c10273b896e/element {"using":"xpath","value":"xpath"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","xpath","f2899102-c482-49ac-a306-0c10273b896e"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 15000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/421294BF-4E0D-47DE-9270-4B716DD0170E/element] with body: {"using":"xpath","value":"**xpath**"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"xpath","value":"xpath","description":"unable to find an element"},"sessionId":"421294BF-4E0D-47DE-9270-4B716DD0170E","status":7}
[debug] [BaseDriver] Waited for 846 ms so far

**Comment by dpgraham** [comment]
Can you provide a code snippet for when that HAPPENS?

**Comment by dpgraham** [comment]
Ignore the uppercase, my caps was turned on by mistake

**Comment by gopi09m** [comment]
closing as there is an issue with my code using class xpath.
