### ISSUE TITLE
click and tap do not work on NATIVE_APP - iOS 10.2 - XCode 8.2.1 - Real Device

### ISSUE THREAD

**Issue by srdanb** [appium/appium#7602]
## The problem

I find a WebElement in an native iOS app and call a click() method or perform a tap() action on it. It is not triggering any reaction in the app. When I tap on the same element with a finger, the app opens new WebView.

## Environment

* Appium version that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: macOS Sierra 10.12.2
* Xcode version: 8.2.1 
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Real Device - iPad mini 3
* Appium CLI or Appium.app|exe: CLI

## Details

// start appium server
appium --default-capabilities '{"automationName":"XCUITest","xcodeConfigFile":"/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig","orientation":"LANDSCAPE"}' --webkit-debug-proxy-port 27753
 

// OPTION 1 - click()
 
// java code
driver.context("NATIVE_APP");
 
// Appium server log
[HTTP] --> POST /wd/hub/session/f062052c-b2e5-4d0e-9520-12e23752a799/context {"name":"NATIVE_APP"}
[debug] [MJSONWP] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","f062052c-b2e5-4d0e-9520-12e23752a799"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'NATIVE_APP'
[debug] [RemoteDebugger] Disconnecting from WebKit remote debugger
[debug] [MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/f062052c-b2e5-4d0e-9520-12e23752a799/context 200 4 ms - 76
[debug] [RemoteDebugger] WebKit remote debugger socket disconnected
 
// java code
WebElement we = driver.findElement(By.xpath("//XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeStaticText[@name='ACCOUNTS']"));
 
// Appium server log
[HTTP] --> POST /wd/hub/session/f062052c-b2e5-4d0e-9520-12e23752a799/element {"using":"xpath","value":"//XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeStaticText[@name='ACCOUNTS']"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeStaticText[@name='ACCOUNTS']","f062052c-b2e5-4d0e-9520-12e23752a799"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/5C7C5BE4-68E8-4E19-BBD3-EAC3444B79E6/element] with body: {"using":"xpath","value":"//XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeStaticText[@name='ACCOUNTS']"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"D1508149-80C8-49C1-9866-28B3E6E8B9BD","type":"XCUIElementTypeStaticText","label":"ACCOUNTS"},"sessionId":"5C7C5BE4-68E8-4E19-BBD3-EAC3444B79E6","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"D1508149-80C8-49C1-9866-28B3E6E8B9BD","type":"XCUIElementTypeStaticText","label":"ACCOUNTS"}
[HTTP] <-- POST /wd/hub/session/f062052c-b2e5-4d0e-9520-12e23752a799/element 200 37356 ms - 176
 
// java code
we.click();
 
// Appium server log
[HTTP] --> POST /wd/hub/session/f062052c-b2e5-4d0e-9520-12e23752a799/element/D1508149-80C8-49C1-9866-28B3E6E8B9BD/click {"id":"D1508149-80C8-49C1-9866-28B3E6E8B9BD"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/f062052c-b2e5-4d0e-9520-12e23752a799/element/D1508149-80C8-49C1-9866-28B3E6E8B9BD/click] to [POST http://localhost:8100/session/5C7C5BE4-68E8-4E19-BBD3-EAC3444B79E6/element/D1508149-80C8-49C1-9866-28B3E6E8B9BD/click] with body: {"id":"D1508149-80C8-49C1-9866-28B3E6E8B9BD"}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"D1508149-80C8-49C1-9866-28B3E6E8B9BD","value":"","sessionId":"5C7C5BE4-68E8-4E19-BBD3-EAC3444B79E6"}
[JSONWP Proxy] Replacing sessionId 5C7C5BE4-68E8-4E19-BBD3-EAC3444B79E6 with f062052c-b2e5-4d0e-9520-12e23752a799
[HTTP] <-- POST /wd/hub/session/f062052c-b2e5-4d0e-9520-12e23752a799/element/D1508149-80C8-49C1-9866-28B3E6E8B9BD/click 200 7657 ms - 118

// RESULT: no reaction
 

// OPTION 2 - tap()
 
// java code
driver.context("NATIVE_APP");
 
// Appium server log
[HTTP] --> POST /wd/hub/session/55fe03fe-5766-40ae-9f04-2026b42baad7/context {"name":"NATIVE_APP"}
[debug] [MJSONWP] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","55fe03fe-5766-40ae-9f04-2026b42baad7"]
[debug] [XCUITest] Executing command 'setContext'
[debug] [iOS] Attempting to set context to 'NATIVE_APP'
[debug] [RemoteDebugger] Disconnecting from WebKit remote debugger
[debug] [MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/55fe03fe-5766-40ae-9f04-2026b42baad7/context 200 5 ms - 76
[debug] [RemoteDebugger] WebKit remote debugger socket disconnected
 
// java code
WebElement we = driver.findElement(By.xpath("//XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeStaticText[@name='ACCOUNTS']"));
 
// Appium server log
[HTTP] --> POST /wd/hub/session/55fe03fe-5766-40ae-9f04-2026b42baad7/element {"using":"xpath","value":"//XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeStaticText[@name='ACCOUNTS']"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeStaticText[@name='ACCOUNTS']","55fe03fe-5766-40ae-9f04-2026b42baad7"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/40F98273-3D86-4303-9728-8931E5589C3B/element] with body: {"using":"xpath","value":"//XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeStaticText[@name='ACCOUNTS']"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"9DB74766-1123-43EB-9FC7-E94F02BAC66A","type":"XCUIElementTypeStaticText","label":"ACCOUNTS"},"sessionId":"40F98273-3D86-4303-9728-8931E5589C3B","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"9DB74766-1123-43EB-9FC7-E94F02BAC66A","type":"XCUIElementTypeStaticText","label":"ACCOUNTS"}
[HTTP] <-- POST /wd/hub/session/55fe03fe-5766-40ae-9f04-2026b42baad7/element 200 20896 ms - 176
 
// java code
new TouchAction((IOSDriver) getWebDriver()).tap(we).perform();
 
// Appium server log
[HTTP] --> POST /wd/hub/session/55fe03fe-5766-40ae-9f04-2026b42baad7/touch/perform {"actions":[{"action":"tap","options":{"element":"9DB74766-1123-43EB-9FC7-E94F02BAC66A"}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"element":"9DB74766-1123-43EB-9FC7-E94F02BAC66A"}}],"55fe03fe-5766-40ae-9f04-2026b42baad7"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: tap
[debug] [JSONWP Proxy] Proxying [POST /tap/9DB74766-1123-43EB-9FC7-E94F02BAC66A] to [POST http://localhost:8100/session/40F98273-3D86-4303-9728-8931E5589C3B/tap/9DB74766-1123-43EB-9FC7-E94F02BAC66A] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"40F98273-3D86-4303-9728-8931E5589C3B","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/55fe03fe-5766-40ae-9f04-2026b42baad7/touch/perform 200 11424 ms - 74
 
// RESULT: no reaction

**Comment by dpgraham** [comment]
Hi @srdanb,

I noticed it's in landscape mode which XCUITest has had issues with (it doesn't respect coordinates properly).

I would recommend testing in portrait (if that's possible) or find a workaround (e.g.: hardcoding the coordinates) until the fix is ready: https://github.com/facebook/WebDriverAgent/pull/411
