### ISSUE TITLE
selecting value from picker control using appium 1.6

### ISSUE THREAD

**Issue by gopi09m** [appium/appium#7604]
## The problem

I am trying to use send keys method to select experience which is in years and months.
Its a combination of two pickertypewheels one to elect number of years (in ui it has values like 0 Years, 1 Years, 2 Years ....) and another one as months (O Months,1Months,2Months ...) 

When i use SendKeys method with below code it doesn't select the value. it simply collapses the picker control. I was able to use send keys for date picker control.

iosDriver.findElements(By.className("XCUIElementTypePickerWheel")).get(0).sendKeys("1 Years"); //mont

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.12.2
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe:

## Details

     `
       <XCUIElementTypeCell name="" label="" value="" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/2/0/1/6" x="230" y="345" width="794" height="46">
                                    <XCUIElementTypeStaticText name="Length of Occupation" label="Length of Occupation" value="Length of Occupation" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/2/0/1/6/0" x="413" y="360" width="176" height="17">
                                    </XCUIElementTypeStaticText>
                                    <XCUIElementTypeTextField name="" label="" value="0 Years 0 Months" dom="" enabled="true" valid="true" visible="false" hint="" path="/0/0/0/0/2/0/1/6/1" x="598" y="353" width="286" height="31">
                                    </XCUIElementTypeTextField>
                                </XCUIElementTypeCell>

         <XCUIElementTypePicker name="" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/2/0/0/0" x="599" y="95" width="286" height="200">
                                <XCUIElementTypePickerWheel name="" label="" value="0 Years, 1 of 61" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/2/0/0/0/0" x="599" y="57" width="140" height="276">
                                </XCUIElementTypePickerWheel>
                                <XCUIElementTypePickerWheel name="" label="" value="0 Months, 1 of 12" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/1/2/0/0/0/1" x="744" y="57" width="140" height="276">
                                </XCUIElementTypePickerWheel>
                            </XCUIElementTypePicker>`

**Comment by mykola-mokhnach** [comment]
This might be related to https://github.com/appium/appium/issues/6962, which is rather XCTest issue.

**Comment by gopi09m** [comment]
Ok. Thanks for the update. Are there are any workarounds ? Not sure if Apple is aware of this issue.

**Comment by dpgraham** [comment]
Closing this as non-appium related issue.

Unfortunately I don't know of any workaround for this. And Apple should be aware but it's unknown how long they'll take to reply.
