### ISSUE TITLE
Implement feature to set Geo Location in Google map via using Appium in Java

### ISSUE THREAD

**Issue by prem0144** [appium/appium#7606]
I have to set Geo location when Google app starts by passing latitude and Longitude with Appium in Java. If this is already implemented then please let me the code in java to set Geo location by lat and long instead of current location. If not implemented then please implement it very fast. thanks!

**Comment by dpgraham** [comment]
Can you explain this in more detail? Is it the Google Maps app you're using or are you using Google Maps as a WebView from inside of your app?

**Comment by dmlemeshko** [comment]
hi @prem0144 
There is a possibility to change your current location (setting mocked geo location) for your test device by calling `setLocation` on AppiumDriver instance:
```
Location location = new Location(latitude, longitude, altitude);
driver.setLocation(location);
```
for location you can import `org.openqa.selenium.html5.Location;`

By default it will work only on Android & iOS simulators, but if you select `Appium Settings` as mocked location app in Developer options, it should work for Android real device as well. Don't know about real iOS devices.

**Comment by jlipps** [comment]
@dmlemeshko has it right, these are your options.

**Comment by premji456** [comment]
@dmlemeshko Below is my code for setting location on Google map by passing lat and long but it doesn't work.


package Test;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.html5.Location;
//import org.openqa.selenium.remote.CapabilityType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.*;

public class FullHouse {
WebDriver driver;

@BeforeClass
public void setUp() throws MalformedURLException{
//Set up desired capabilities and pass the Android app-activity and app-package to Appium
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("BROWSER_NAME", "");
capabilities.setCapability("platformName","Android");
capabilities.setCapability("deviceName","emulator-5554");
capabilities.setCapability("platformVersion", "5.1");

capabilities.setCapability("appPackage","com.google.android.apps.maps");

capabilities.setCapability("appActivity","com.google.android.maps.MapsActivity");
//It will launch the Calculator App in Android Device using the configurations specified in Desired Capabilities
//driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

AppiumDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
// WebDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),getDesiredCapabilities("192.21.168.56:5555"));
Location location = new Location(77.59974003, 12.91024781, 909);
driver.setLocation(location);
driver.manage().timeouts().implicitlyWait(200, TimeUnit.SECONDS);
//driver.manage().timeouts().implicitlyWait(100, TimeUnit.SECONDS);

}

@Test
public void testCal() throws Exception {
Some test here

}

@AfterClass
public void teardown(){
//close the app
driver.quit();
}
}


Showing error FAILED CONFIGURATION: @BeforeClass setUp org.openqa.selenium.WebDriverException: ERROR running Appium command: port should be string=false

**Comment by premji456** [comment]
@dpgraham for now I am using google map. If it passes then i will jump to my app where I am using google map as webview.

**Comment by dmlemeshko** [comment]
@premji456 
Please provide more details about your env and full stacktrace: `Appium server version` (I hope you are using 1.5.3 or above), `appium-java-client` version, what type of emulator: Android SDK or genymotion. 
So far you can check [this thread](https://github.com/appium/appium/issues/4309), looks like your issue

**Comment by premji456** [comment]
Appium 1.6.3 Java client 4.1.2 Android SDK emulator I am using shwoing issue in screenshot 
![google map set location](https://cloud.githubusercontent.com/assets/6905826/21809699/dc64c4da-d76e-11e6-8f88-327079ca4ced.png)

**Comment by premji456** [comment]
@dmlemeshko Now I able to set one location on android emulator. But I have to set multiple location on map. I am not abler to do that. My code is below. it setting only first location but I have to set multiple location. Any idea? Some problem in sleep time?


public void setUp() throws MalformedURLException, InterruptedException{
//Set up desired capabilities and pass the Android app-activity and app-package to Appium
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("noReset","true");
capabilities.setCapability("fullReset","false");
capabilities.setCapability("BROWSER_NAME", "");
capabilities.setCapability("platformName","Android");
capabilities.setCapability("deviceName","emulator-5554");
capabilities.setCapability("platformVersion", "5.1.1");
Thread.sleep(10000);
capabilities.setCapability("appPackage","com.google.android.apps.maps");

capabilities.setCapability("appActivity","com.google.android.maps.MapsActivity");
Thread.sleep(20000);
//It will launch the Calculator App in Android Device using the configurations specified in Desired Capabilities
//driver = new RemoteWebDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

AppiumDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
driver.manage().timeouts().implicitlyWait(500, TimeUnit.SECONDS);
Thread.sleep(20000);
// WebDriver driver = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),getDesiredCapabilities("192.21.168.56:5555"));
Location location = new Location(28.6520,77.2315, 830);
driver.setLocation(location);
Thread.sleep(10000);


Location location1 = new Location(27.6520,76.2315, 830);
driver.setLocation(location1);
Thread.sleep(50000);
//driver.manage().timeouts().implicitlyWait(100, TimeUnit.SECONDS);
