### ISSUE TITLE
allow wildcards in appWaitActivity

### ISSUE THREAD

**Issue by gleemitsu** [appium/appium#7607]
## Issue
 
I have a trouble launching my android app on Appium 1.6.0 or later.
`
[ADB] Error: Activity used to start app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
`
I understand that `appWaitActivity` is required and the problem may be fixed by setting a correct activity, however, I think it is very difficult to set all activities to `appWaitActivity` for a number of reasons:
* My app includes an Ad SDK which contains multiple activities.
* I tried `driver.currentActivity();` but it returns various values. It may be a timing issue, though.
* This Ad SDK is developed by an outside developer so there is a possibility that the activity name of the SDK may be changed.
 
It would be great if Appium provide an option to skip the activity check or a setting to specify appWaitActivity like `'com.mydomain.*, com.sdkdomain.*'`.
 
## Environment
 
* appium 1.6.0 or later
* Desktop OS/version used to run Appium:Mac OS X El Capitan
* Node.js version (unless using Appium.app|exe): v6.9.2
* Mobile platform/version under test: android
* Real device or emulator/simulator: both

**Comment by dpgraham** [comment]
appWaitActivity is an optional parameter. What happens when you omit it?

**Comment by gleemitsu** [comment]
Certainly appWaitActivity is optional.
 
When I omitted both appActivity and appWaitActivity, I cannot launch my app and I got log message like this.
```
[debug] [ADB] Waiting for pkg: 'com.mydomain.android.top' and activity: 'com.mydomain.android.top.MainActivity' to be focused
[debug] [ADB] Possible activities, to be checked: com.mydomain.android.top.MainActivity, .MainActivity, .com.mydomain.android.top.MainActivity
[debug] [ADB] Getting focused package and activity
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running '/Users/myname/android-sdk-macosx/platform-tools/adb' with args: ["-P",5037,"-s","BH933S2J44","shell","dumpsys","window","windows"]
[debug] [ADB] Found package: 'com.sdkdomain.android.ads' and activity: 'com.sdkdomain.android.ads.AdActivity'
[debug] [ADB] Incorrect package and activity. Retrying.
```
So I tried setting appWaitActivity referring to [Android on appium 1.6: 'Incorrect package and activity.' error - Issues/Bugs - Appium Discuss](https://discuss.appium.io/t/android-on-appium-1-6-incorrect-package-and-activity-error/12608) and encountered this problem.

**Comment by imurchie** [comment]
This seems like a good feature to have, to be able to send in a wildcard. Adding it to our work.

**Comment by gleemitsu** [comment]
@imurchie thank you! 
I've been thinking about a way to make it work.
If I come up with a good one, I'll send a PR.

**Comment by Gocoollnath** [comment]
Hi Guys,

Can we have this wildcard feature for appActivity too. Xamarin framework creates encrypted activity names for each version of the app. In order to solve this frequent change of launchactivity name in Appium code for every version, it will be useful if appActivity too has the wildcard feature.

Thanks.

**Comment by dpgraham** [comment]
@Gocoollnath I don't know when we could get to working on that feature, but we do take pull requests.
