### ISSUE TITLE
【BUG】 start appium  for xcuitest and stuck at ”Waiting for WebDriverAgent to start on device“

### ISSUE THREAD

**Issue by huanglik** [appium/appium#7609]
using the newest appium source and wda source， and i find that appium server will stuck at ”Waiting for WebDriverAgent to start on device“ and can‘t  do anything。

so i check the source in appium server

in fact， appium will launch wda and Waiting for WebDriverAgent return message to match /ServerURLHere->(.*)<-ServerURLHere/;

const AGENT_STARTED_REGEX = /ServerURLHere->(.*)<-ServerURLHere/;
![image](https://cloud.githubusercontent.com/assets/3026388/21500107/8cc00302-cc76-11e6-80ed-82ebeb9cfe80.png)

however，checking out  the newest wda source， and i run it using xcodebuild （just like appium do），wda did not print “ServerURLHere... ” anymore.
 
![image](https://cloud.githubusercontent.com/assets/3026388/21500124/a67655da-cc76-11e6-87af-fc82b4eec6ec.png)

so appium can't launch app for test, i think i find the bug of appium 
waiting for  fix 
thank you

**Comment by imurchie** [comment]
This is not where WDA prints the message. It prints it in the device log.

But Appium will no longer be using this as a check for starting, moving forward.

**Comment by huanglik** [comment]
WDA print log in device log ?   how can I find that log ?
I am trying to fix this for launch my app testing,  also waiting for appium

**Comment by imurchie** [comment]
On a real device you can either use `idevicesyslog` or `deviceconsole` to see it, or go through "Devices" in Xcode. On a simulator it is in your home library (the exact path is printed in the Appium logs).

**Comment by imurchie** [comment]
But if you re-install the dependencies from the Appium repo (`rm -rf node_modules && npm install`) you will get an entirely different mechanism for checking WDA startup.

**Comment by huanglik** [comment]
i re-install the dependencies and see what you did for checking WDA startup.
so good， thank you very much ！！！
