### ISSUE TITLE
Cannot get content-desc from element [UIAutomator2]

### ISSUE THREAD

**Issue by tfcardoso** [appium/appium#7612]
## Environment

* Appium version: 1.6.3
* Desktop OS/version used to run Appium: OSX 10.12.1
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Samsung S5
* Driver: UIAutomator2

## The problem

Using appium 1.6.3 with UIAutomator2 I'm unable to get content-description from elements.

With UIAutomator we did:

    driver.findElement(By.id("my_id")).getAttribute("name")

Now doing that is giving me the same result as getAttribute("text").

I'm aware that I can do (or similar via XPath):

    driver.findElementByAccessibilityId("my_content_desc");

But in this case I already have the element and just want to know the content-desc.

**Comment by dpgraham** [comment]
Can you try calling 'driver.getPageSource()' and inspect the source XML. The XML format has changed between UIAutomator and UIAutomator2 and the way of accessing the content description may have changed.

**Comment by sravanmedarapu** [comment]
Using `driver.findElement(By.id("my_id")).getAttribute("contentDescription")` should work.

**Comment by tfcardoso** [comment]
Amazing @sravanmedarapu. It works. I'll close this issue and will post your answer on appium forum. Thanks

**Comment by dpgraham** [comment]
Thank you Sravan

**Comment by CharanpreetHora** [comment]
amazing...this also resolved my issue to fetch data using contentDescription.

**Comment by mahammadgoni** [comment]
Thanks @sravanmedarapu
