### ISSUE TITLE
ChromeDriver Gets Stuck When Switching Back & Forth In Web/Native Contexts

### ISSUE THREAD

**Issue by razor901** [appium/appium#7613]
## The problem

ChromeDriver Gets Stuck When Switching Back & Forth In Web/Native Contexts

**EDIT : Tried to fix the problem by adding another launchApp after using closeApp, even though I noticed that driver.get(URL) opens the chrome successfully without launching the chrome again
But now after switching to WEB again and going to the URL this is the page source that was returned :
<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body></body></html> 
 ---> Couldn't Find any element ofc**

## Environment

* Appium 1.6.1
* MAC OS 10.11.16
* Latest node
* Samsung S6 6.0.1
* Real device 
* Appium CLI 

## Details

ChromeDriver Gets Stuck When Switching Back & Forth In Web/Native Contexts
When writing a test on Chrome & then closing chrome by closeApp function and then launching chrome again . (I'm switching between contexts) chrome driver stops working and gets stuck .
This is the message from the appium server when that happens : 

`[debug] [MJSONWP] Calling AppiumDriver.setContext() with args: ["CHROMIUM","d877a200-e94f-41e4-8a90-f67d0080b00e"]
[debug] [AndroidDriver] Available contexts: ["NATIVE_APP","CHROMIUM"]
[debug] [AndroidDriver] Connecting to chrome-backed webview context 'CHROMIUM'
[debug] [AndroidDriver] Found existing Chromedriver for context 'CHROMIUM'. Using it.
[debug] [JSONWP Proxy] Proxying [GET /url] to [GET http://127.0.0.1:8000/wd/hub/session/6af7d5cf0e31005fb2d15e649287cae8/url] with no body
[debug] [AndroidDriver] ChromeDriver is not associated with a window. Re-initializing the session.
[Chromedriver] Restarting chromedriver
[debug] [Chromedriver] Changed state to 'restarting'
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8000/wd/hub/session/6af7d5cf0e31005fb2d15e649287cae8] with no body
[debug] [AndroidBootstrap] Emitting alert message...
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Emitting system alert message`

## Link to Appium logs

https://gist.github.com/razor901/75a208922e344875694d3e451a88bcd1

Note : If I don't close the appium server it will keep replacing the session with a new session .

**Comment by razor901** [comment]
**EDIT : Tried to fix the problem by adding another launchApp after using closeApp, even though I noticed that driver.get(URL) opens the chrome successfully without launching the chrome again 
But now after switching to WEB again and going to the URL this is the page source that was returned :
<html xmlns="http://www.w3.org/1999/xhtml"><head></head><body></body></html> 
 ---> Couldn't Find any element ofc
**

**Comment by jlipps** [comment]
Are you trying to automate the Chrome browser? If so, there's no need to mess with setting contexts. Just start a session using the appropriate capabilities:

```
{
  "platformName": "Android",
  "platformVersion": "6.0",
  "browserName": "Chrome",
  "deviceName": "Android"
}
```

If you want to start and stop Chrome, don't use launchApp and closeApp. Just create and quit sessions.

**Comment by razor901** [comment]
I wanted to check if the user closes the browser & then visits again the website in Chrome in one session.
But if this is not supported it's fine I can pass on that @jlipps
