### ISSUE TITLE
appium-1.6.3 for mobile safari

### ISSUE THREAD

**Issue by wjl025** [appium/appium#7615]
## The problem
ios_webkit_debug_proxy is run
SafariLuancher is build and install on  real device
safari is not run
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:10.11.6
* Node.js version (unless using Appium.app|exe):v6.9.1
* Mobile platform/version under test:ios9.3.5
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:CLI

## Link to Appium logs

https://gist.github.com/wjl025/bbc6704909b834e7b389c67421745f34

**Comment by imurchie** [comment]
Can you try running the startup command:

```
cd /Users/jialinwang/git/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
xcodebuild build test -project /Users/jialinwang/git/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=c272590c478347233bb2b8dc1e31cd2506531675 -configuration Debug -xcconfig /usr/local/appium-xcuitest-driver/myconfig.xcconfig
```

**Comment by wjl025** [comment]
@imurchie 
i reinstall appium,now issue is resolve.
thank you!
