### ISSUE TITLE
Appium 1.6.3 Real IOS :Failed with "Unable to start WebDriverAgent: Error: Command 'idevicedate -u b92d1245a0d0818ee09ab09621cca98bdb2e42ca' exited with code 255"

### ISSUE THREAD

**Issue by debbie-qin** [appium/appium#7616]
Here is the log:
xxxx:~ xxx$ appium -U b92d1245a0d0818ee09ab09621cca98bdb2e42ca 
[Appium] Welcome to Appium v1.6.3 (REV 604f4b6a0785e0295e548e6d033823303da19061)
[Appium] Non-default server args:
[Appium]   udid: 'b92d1245a0d0818ee09ab09621cca98bdb2e42ca'
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"b92d1245a0d0818ee09ab09621cca98bdb2e42ca"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: 'b92d1245a0d0818ee09ab09621cca98bdb2e42ca'
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"com.yahoo.Aerogram","automationName":"XCUITest","platformName":"iOS","screenshotWaitTimeout":"240","deviceName":"iPhone 6 Plus"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"com.yahoo.Aerogram","automationName":"XCUITest","platformName":"iOS","screenshotWaitTimeout":"240","deviceName":"iPhone 6 Plus"},null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: 'com.yahoo.Aerogram'
[Appium]   automationName: 'XCUITest'
[Appium]   platformName: 'iOS'
[Appium]   screenshotWaitTimeout: '240'
[Appium]   deviceName: 'iPhone 6 Plus'
[Appium]   udid: 'b92d1245a0d0818ee09ab09621cca98bdb2e42ca'
[debug] [XCUITest] XCUITestDriver version: 2.4.3
[BaseDriver] Capability 'screenshotWaitTimeout' changed from string ('240') to integer (240). This may cause unexpected behavior
[BaseDriver] Session created with session id: 9249c9da-2679-48c7-8ecb-a2fb340f6aa1
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [XCUITest] Available devices: b92d1245a0d0818ee09ab09621cca98bdb2e42ca
[debug] [XCUITest] Creating iDevice object with udid b92d1245a0d0818ee09ab09621cca98bdb2e42ca
[XCUITest] Determining device to run tests on: udid: 'b92d1245a0d0818ee09ab09621cca98bdb2e42ca', real device: true
[debug] [XCUITest] App is an iOS bundle, will attempt to run as pre-existing
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/.2.4.3@appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/.2.4.3@appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/.2.4.3@appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=b92d1245a0d0818ee09ab09621cca98bdb2e42ca -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/.2.4.3@appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u b92d1245a0d0818ee09ab09621cca98bdb2e42ca' exited with code 255
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u b92d1245a0d0818ee09ab09621cca98bdb2e42ca' exited with code 255
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: undefined
[HTTP] <-- POST /wd/hub/session 500 1088 ms - 262 

Could you help me?

**Comment by mykola-mokhnach** [comment]
Please use search to look for similar resolved issues.
In general, you need to remove currently installed idevicelibrary package and update it to HEAD revision.
