### ISSUE TITLE
[XCUITest] xcodebuild exited with code '70' and signal 'null'  [XCUITest] Error: xcodebuild failed with code 70

### ISSUE THREAD

**Issue by sudhirsingh1** [appium/appium#7617]
[Appium] Welcome to Appium v1.6.3

[Appium] Non-default server args:

[Appium]   port: 4727

[Appium]   launch: true
[Appium]   robotPort: 4
[Appium]   debugLogSpacing: true
[Appium]   platformName: 'iOS'

[Appium]   platformVersion: '10.1.1'
[Appium]   deviceName: 'iPhone'
[Appium]   app: 'com.app.CGR'
[Appium]   udid: 'e7c69546539cc06d5351e33c6a4aa8cd1f13d263'
[Appium]   fullReset: true
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"10.1.1"}'
[Appium]   --device-name => --default-capabilities '{"deviceName":"iPhone"}'
[Appium]   --app => --default-capabilities '{"app":"com.app.CGR"}'

[Appium]   -U,--udid => --default-capabilities '{"udid":"e7c69546539cc06d5351e33c6a4aa8cd1f13d263"}'
[Appium]   --full-reset => --default-capabilities '{"fullReset":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.1.1'
[Appium]   deviceName: 'iPhone'
[Appium]   app: 'com.app.CGR'
[Appium]   udid: 'e7c69546539cc06d5351e33c6a4aa8cd1f13d263'
[Appium]   fullReset: true

[Appium] Appium REST http interface listener started on 0.0.0.0:4727

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[HTTP] <-- GET /wd/hub/status 200 33 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[HTTP] <-- GET /wd/hub/status 200 19 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[HTTP] <-- GET /wd/hub/status 200 15 ms - 83 
[HTTP] --> GET /wd/hub/sessions {}
[debug] [MJSONWP] Calling AppiumDriver.getSessions() with args: []
[debug] [MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 4 ms - 40 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","app":"/Users/developer/Downloads/Payload (3).ipa","deviceName":"iPhone","platformVersion":"10.1.1","udid":"e7c69546539cc06d5351e33c6a4aa8cd1f13d263","bundleId":"com.app.CGR","automationName":"Appium"}}

[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","app":"/Users/developer/Downloads/Payload (3).ipa","deviceName":"iPhone","platformVersion":"10.1.1","udid":"e7c69546539cc06d5351e33c6a4aa8cd1f13d263","bundleId":"com.app.CGR","automationName":"Appium"},null,null,null,null]

[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.

[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   app: '/Users/developer/Downloads/Payload (3).ipa'
[Appium]   deviceName: 'iPhone'
[Appium]   platformVersion: '10.1.1'
[Appium]   udid: 'e7c69546539cc06d5351e33c6a4aa8cd1f13d263'
[Appium]   bundleId: 'com.app.CGR'
[Appium]   automationName: 'Appium'
[Appium]   fullReset: true
[debug] [XCUITest] XCUITestDriver version: 2.4.2

[BaseDriver] Session created with session id: 2b41d900-11c6-4570-9e07-1c71fa79bb4e

[debug] [XCUITest] Xcode version set to '8.2.1'

[debug] [XCUITest] iOS SDK Version set to '10.2'

[debug] [XCUITest] Available devices: e7c69546539cc06d5351e33c6a4aa8cd1f13d263

[debug] [XCUITest] Creating iDevice object with udid e7c69546539cc06d5351e33c6a4aa8cd1f13d263

[XCUITest] Determining device to run tests on: udid: 'e7c69546539cc06d5351e33c6a4aa8cd1f13d263', real device: true
[BaseDriver] Using local app '/Users/developer/Downloads/Payload (3).ipa'
[debug] [BaseDriver] Copying local zip to tmp dir

[debug] [BaseDriver] Unzipping /var/folders/vq/85xfnb8d3f1gbbflrnvy9q1h0000gn/T/20161128-5895-68gmnc.yrhciyhkt9/appium-app.zip

[debug] [BaseDriver] Testing zip archive: /var/folders/vq/85xfnb8d3f1gbbflrnvy9q1h0000gn/T/20161128-5895-68gmnc.yrhciyhkt9/appium-app.zip

[BaseDriver] Unzipped local app to '/var/folders/vq/85xfnb8d3f1gbbflrnvy9q1h0000gn/T/20161128-5895-68gmnc.yrhciyhkt9/Payload/CGR.app'

[debug] [XCUITest] Checking whether app '/var/folders/vq/85xfnb8d3f1gbbflrnvy9q1h0000gn/T/20161128-5895-68gmnc.yrhciyhkt9/Payload/CGR.app' is actually present

[debug] [XCUITest] App is present
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog

[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'

[XCUITest] Setting up real device

[debug] [XCUITest] Error checking install status: Command 'ios-deploy --exists --id e7c69546539cc06d5351e33c6a4aa8cd1f13d263 --bundle_id com.app.CGR' exited with code 255

[debug] [XCUITest] App is not installed. Will try to install.

[debug] [XCUITest] App installed successfully.

[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'

[XCUITest] Launching WebDriverAgent on the device

[debug] [XCUITest] Carthage found: /usr/local/bin/carthage

[debug] [XCUITest] Killing hanging processes

[debug] [XCUITest] Using real device logger 'idevicesyslog'

[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e7c69546539cc06d5351e33c6a4aa8cd1f13d263 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'

[debug] [XCUITest] Unable to get device time. Using local system time

[debug] [XCUITest] Output from idevicedate: Wed Dec 28 11:56:35 IST 2016

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[HTTP] <-- GET /wd/hub/status - - ms - - 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[XCUITest] Waiting for WebDriverAgent to start on device

[HTTP] <-- GET /wd/hub/status - - ms - - 

[XCUITest] xcodebuild exited with code '70' and signal 'null'

[XCUITest] Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

[XCUITest] Shutting down sub-processes

[XCUITest] Shutting down Logger process (pid 6066)
[XCUITest] System log exited with code '0'
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Full reset requested. Will try to uninstall the app 'com.app.CGR'.

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [XCUITest] Removed 'com.app.CGR'

[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture

[MJSONWP] Encountered internal error running command: Error: xcodebuild failed with code 70
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:355:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:197:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

[HTTP] <-- POST /wd/hub/session 500 81835 ms - 167 

[HTTP] <-- GET /wd/hub/status - - ms - - 

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 19 ms - 83 

[HTTP] --> GET /wd/hub/status {}

[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []

[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 16 ms - 83 

[Appium] Received SIGTERM - shutting down

**Comment by mykola-mokhnach** [comment]
1. You need to update idevicelibrary to HEAD revision

2. Execute 

```
xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e7c69546539cc06d5351e33c6a4aa8cd1f13d263 -configuration Debug
```

command in Terminal and get the output from there. Attach it as a gist to this issue. Do not paste as raw text, since it's hard to read.

**Comment by jlipps** [comment]
@ChiWhiteSox56 `signal null` just means that a subprocess exited on its own, not in response to an external signal. Your issue is probably unrelated.

**Comment by imurchie** [comment]
Appium 1.6.4-beta has been released (to upgrade, run `npm uninstall -g appium && npm install -g appium@beta`). How we connect to devices has been significantly changed, and should be more reliable. Please try it out.

There is some documentation here: https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

I am closing this issue since the details will have changed completely. If you still have problems, please see if there is a similar issue, or else create a new issue with as much information as possible. We are committed to tracking down these elusive problems!
