### ISSUE TITLE
[XCUITest] Can't complete appium-xcuitest-driver setup for getting "Listening on USB"

### ISSUE THREAD

**Issue by ansonliao** [appium/appium#7619]
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Mac MacOS Sierra, 10.12.2
* Node.js version (unless using Appium.app|exe): 6.5.0
* Mobile platform/version under test: iPhone 6P with iOS 10.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I checkout the latest version of `appium-xcuitest-driver` (vesion: 2.5.0), and completed the setup in `XCode` by selecting `team` and automatically select sign cert., with no problem.

and then I run the test of `appium-xcuitest-driver` mention by the usage document, the command is: `xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test`

as the document mention, the last output of this test command run, should be get `Listening on USB`, and it means that all setup is completed.

but after I run the test command, the process is stop in below of log, and no `Listening on USB` was got.

could you advise how I can fix it?
@imurchie 

```bash
>>>> $ xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=ccf1e887452d914e84d09ae21b501b28a73d4aa2' test

2016-12-28 16:37:03.165 xcodebuild[16423:325203]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/ansonliao/Library/Developer/Xcode/DerivedData/WebDriverAgent-grgmxcxgtxbtdzgaqaryrhbyvtsw/Logs/Test/E8AA9C05-0B73-4893-B151-245E3529FAC4/Session-WebDriverAgentRunner-2016-12-28_163703-0tUjP1.log
2016-12-28 16:37:03.165 xcodebuild[16423:325186] [MT] IDETestOperationsObserverDebug: (CD8BFA6D-37EA-4691-8EBC-EA0A0E4CF25C) Beginning test session WebDriverAgentRunner-CD8BFA6D-37EA-4691-8EBC-EA0A0E4CF25C at 2016-12-28 16:37:03.163 with Xcode 8C1002 on target <DVTiOSDevice: 0x7fb492aadbf0> {
		deviceSerialNumber:         C39NW0GFG5QV
		identifier:                 ccf1e887452d914e84d09ae21b501b28a73d4aa2
		deviceClass:                iPhone
		deviceName:                 Anson iPhone
		deviceIdentifier:           ccf1e887452d914e84d09ae21b501b28a73d4aa2
		productVersion:             10.2
		buildVersion:               14C92
		deviceSoftwareVersion:      10.2 (14C92)
		deviceArchitecture:         arm64
		deviceTotalCapacity:        58888056832
		deviceAvailableCapacity:    11614601216
		deviceIsTransient:          NO
		ignored:                    NO
		deviceIsBusy:               NO
		deviceIsActivated:          YES
		deviceActivationState:      Activated
		deviceType:                 <DVTDeviceType:0x7fb4921af130 Xcode.DeviceType.iPhone>
		supportedDeviceFamilies:    (
    1
)
		applications:              (null)
		provisioningProfiles:      (null)
		activityProgress:          -2
		activityTitle:
		hasInternalSupport:        NO
		isSupportedOS:             YES
		developerDiskMountError:   (null)
(null)
	} (10.2 (14C92))
=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/jf/xlj3jzj16xv1j13g2zbsx0lm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/697d997cfb3a1df93f47fde14485ad9b/ccf1e887452d914e84d09ae21b501b28a73d4aa2/ManifestCache.plist
Test Suite 'All tests' started at 2016-12-28 16:37:29.613
Test Suite 'WebDriverAgentRunner.xctest' started at 2016-12-28 16:37:29.616
Test Suite 'UITestingUITests' started at 2016-12-28 16:37:29.618
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2016-12-28 16:37:29.623
    t =     0.01s     Set Up
```

**Comment by imurchie** [comment]
With that running in one tab can you try this in another:

```
export DEVICE_URL='http://localhost:8100'
export JSON_HEADER='-H "Content-Type: application/json;charset=UTF-8, accept: application/json”'
curl -X GET $JSON_HEADER $DEVICE_URL/status
```

**Comment by emil-petersen** [comment]
@imurchie Hey, for what it's worth, I have the same problem, and this is the output I get when trying to run the commands you posted: 

```ci-mac-03:auto_tests emil.petersen$ curl -X GET $JSON_HEADER $DEVICE_URL/status
curl: (6) Could not resolve host: application
curl: (6) Could not resolve host: accept
curl: (6) Could not resolve host: application
curl: (7) Failed to connect to localhost port 8100: Connection refused```

**Comment by imurchie** [comment]
Something is wrong with the quotation marks. It may have been in the original pasting. Make sure that the quotes around the header are both regular.

```
-H "Content-Type: application/json;charset=UTF-8, accept: application/json"
```

**Comment by emil-petersen** [comment]
@imurchie I believe I resolved that. This is still the output I get: 

```
SERVER:auto_tests USER$ echo $JSON_HEADER
-H "Content-Type: application/json;charset=UTF-8, accept: application/json"
SERVER:auto_tests USER$ echo $DEVICE_URL
http://localhost:8100
SERVER:auto_tests USER$ echo $JSON_HEADER
-H "Content-Type: application/json;charset=UTF-8, accept: application/json"
SERVER:auto_tests USER$ curl -X GET $JSON_HEADER $DEVICE_URL/status
curl: (6) Could not resolve host: application
curl: (6) Could not resolve host: accept
curl: (6) Could not resolve host: application
curl: (7) Failed to connect to localhost port 8100: Connection refused
SERVER:auto_tests USER$
```

**Comment by emil-petersen** [comment]
All of the above is with Appium 1.6.3, using XCUITest on real iOS devices.

**Comment by emil-petersen** [comment]
@imurchie I tried manually passing in the headers, to avoid whatever was going wrong with the quotes ETC. It removed the errors ETC I was getting, but on `localhost`', it's a definite failure.

The `appium` logs mention the IP 10.67.29.44, and substituting `localhost` for that - keeping the port the same - instead of getting the error, I see `curl` hanging indefinitively.

**Comment by imurchie** [comment]
IS this a real device or a simulator?

**Comment by emil-petersen** [comment]
@imurchie Real device, iOS 9.3.5. Trying with iOS 10.1 (also real), still using the `10.67.29.44` IP, I get a similar hanging, and then same result - operation timed out.

**Comment by imurchie** [comment]
Yes, real device will need the ip of the device. Can you try starting `iproxy` in another tab?

```
iproxy 8100 8100 <UDID>
```

**Comment by emil-petersen** [comment]
@imurchie I find that the `iproxy` I started in another tab exits (Killed: 9) a little while after I start up my test suite (Python, Appium CLI). Starting it back up manually allows me to get past this, and instead get to 'Waiting for WebDriverAgent server to finish loading...'.

However the manually-started process (that I re-started after it was killed) just says 'waiting for connection' indefinitely. What output should I be expecting here?

**Comment by imurchie** [comment]
I don't understand what you are trying to do anymore. This issue was about manually starting xcodebuild and trying to test whether the server was up and running.

**Comment by emil-petersen** [comment]
@imurchie Sorry, I was trying to run my test suite and connect to iOS. If I manually run the `curl` command after starting `iproxy` in another tab, it still times out. The `iproxy` command itself just outputs 'waiting for connection'.

**Comment by imurchie** [comment]
So, to recap, you have run the `xcodebuild` command and it eventually prints something like `Test Case '-[UITestingUITests testRunner]' started.`

Keeping that going, in another tab you open `iproxy` with `iproxy 8100 8100 <UDID>`, which will print `waiting for connection`.

Finally, in another tab, you run the `curl` command. This _should_ give a status object. 

And it is this last step that does not work?

**Comment by emil-petersen** [comment]
@imurchie Sorry for being all over the place. Yes, that is what I did, and what I'm doing, and I am finding still that it gives me 'operation timed out'. However the reason I came to this thread was because I could not run my company's app on iOS. I found, though, that grabbing the latest Appium from git (commit ccb7b26dfa0f9b45636e5876d6977bab2a12e5a0) solved that problem for me.

I apologize for being misleading / unfocused. But yes - I run the `xcodebuild` command, start `iproxy` with the UDID of my real device (as reported by `instruments -s devices`), then run the curl command (against the IP appium wrote to the log), and what I get is eventually a time-out.

I did also change my desired caps, when I saw your changes to the docs, I went and fixed them up for iOS. That is not relevant to the specific issue in this thread, but that + the newest Appium from git fixed the issue that brought me here originally.

**Comment by imurchie** [comment]
Well, I'm glad that it was fixed!

Can you try one last thing, just to clarify? After starting the `iproxy` proxy, use `localhost:8100` for the curl command? It proxy is there to send traffic through usb. 

Along the same lines, are the device and the computer running Appium on the same network?

**Comment by ansonliao** [comment]
@imurchie 
I am sorry that I only run `appium-xcuitest-driver` project test, no appium server run, so how I can get the real device's IP?

**Comment by ansonliao** [comment]
@imurchie 
I can run iOS 10 on real device now.

**Comment by imurchie** [comment]
Excellent! Closing this.

**Comment by Chenneyfang** [comment]
i met the same problem,how to fix it ? 
logs below:
share:~ chen-pc$ export DEVICE_URL='http://localhost:8100'
share:~ chen-pc$ export JSON_HEADER='-H "Content-Type: application/json;charset=UTF-8, accept: application/json”'
share:~ chen-pc$ curl -X GET $JSON_HEADER $DEVICE_URL/status
curl: (6) Could not resolve host: application
curl: (6) Could not resolve host: accept
curl: (6) Could not resolve host: application
{
  "value" : {
    "state" : "success",
    "os" : {
      "name" : "iOS",
      "version" : "10.2"
    },
    "ios" : {
      "simulatorVersion" : "10.2"
    },
    "build" : {
      "time" : "Jan 20 2017 17:25:36"
    }
  },
  "sessionId" : "5C996610-8296-4E44-B0B3-A9510B698928",
  "status" : 0
