### ISSUE TITLE
Creating new AndroidDriver or AndroidUiautomator2Driver session fails

### ISSUE THREAD

**Issue by wojciwojci** [appium/appium#7620]
## The problem

Appium server returns HTTP response 500 when asked to create session with following capabilities,
`2016-12-27 15:56:31:293 - [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"http://lkw-dev-selenium-srv01/apps/android/4.5.17.apk","appPackage":"com.seamless.seqr","recreateChromeDriverSessions":true,"noReset":false,"usage":"prod_test","deviceName":"Anyname","platform":"ANDROID","appActivity":"com.seamless.mpayment.qr.androidapp.ui.MainActivity","automationName":"uiautomator2","platformName":"Android","udid":"SH442WM04371","status":"registration"}}
`
I tried with automation name uiautomator2 and appium with the same result.

## Environment

* Appium version: 1.6.3
* Last Appium version that did not exhibit the issue: 1.5
* Desktop OS/version used to run Appium: Mac OS X EL Capitan
* Node.js version (unless using Appium.app|exe): v7.3.0
* Mobile platform/version under test: Android 5.0.1
* Real device or emulator/simulator: Phone 
* Appium CLI or Appium.app|exe:Appium installed via npm

## Details

I have mobile tests setup consisting of several android emulators and real devices all connected to one selenium hub. Selenium hub uses custom Capability Matcher that dispatches tests. Each mobile device is connected to appium server started with node_config.json 
```
{
  "capabilities": [
    {
      "browserName": "Android",
      "version": "5.0.1",
      "maxInstances": 1,
      "platform": "ANDROID",
      "phoneNumber": "+48575872750",
      "udid": "SH442WM04371",
      "deviceName": "htc_europe",
      "usage": "prod_test",
      "status": "registration"
    }
  ],
  "configuration": {
    "cleanUpCycle": 2000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url": "http://lkw-prd-selenium-srv01:4970/wd/hub",
    "host": "lkw-prd-selenium-srv01",
    "port": "4970",
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "gtsp-prd-utils-selenium01"
  }
}

```
Capability Matcher uses "usage" and "status" parameters from node capabilities to select proper node. 

When correct node (mobile device) is selected for tests, selenium hub calls appium server to request new session. This request fails, in my opinion due to custom capabilities. 

## Link to Appium logs

I attache logs from selenium hub and appium
https://gist.github.com/wojciwojci/38aee6dbfc8c3f01f46ebaa6815c651e
Appium server log from creating session with automation Appium
https://gist.github.com/wojciwojci/467acacdcb50a23613e607755b0b50ad
Appium server log from creating session with automation uiautomation2
https://gist.github.com/wojciwojci/5c48dc1a27eaa93e88a398086b832014

**Comment by sravanmedarapu** [comment]
Seems it is more of an issue with launching activity com.seamless.seqr/com.seamless.mpayment.qr.androidapp.ui.MainActivity, 

Can you try to execute below command and see if you it launching the activity with and with out app reset
`adb -P 5037 -s SH442WM04371 shell am start -W -n com.seamless.seqr/com.seamless.mpayment.qr.androidapp.ui.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000`

**Comment by wojciwojci** [comment]
@sravanmedarapu 
Thanks for quick reply.
This command worked like a charm, the app MainActivity is started without app reset.
```
adb -P 5037 -s SH442WM04371 shell am start -W -n com.seamless.seqr/com.seamless.mpayment.qr.androidapp.ui.MainActivity -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000
Stopping: com.seamless.seqr
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.seamless.seqr/com.seamless.mpayment.qr.androidapp.ui.MainActivity }
Status: ok
Activity: com.seamless.seqr/com.seamless.mpayment.qr.androidapp.ui.registration.RegistrationWelcomeActivity
ThisTime: 573
TotalTime: 1023
WaitTime: 1056
Complete
```

I am suspect handling custom session capabilities because when i removed "status" and "usage" from node config the session in appium server was created correctly. Unfortunately i cannot remove "status" and "usage"  permanently.

**Comment by jlipps** [comment]
The issue would not be due to custom capabilities, as you can see in the log:

> 2016-12-27 15:56:31:304 - [BaseDriver] The following capabilities were provided, but are not recognized by appium: usage, platform, status.

Appium just ignores unknown capabilities.

Is Appium launching the app at this point, or not?
