### ISSUE TITLE
longPress ignores duration in UIAutomator2 (turning it into a normal tap)

### ISSUE THREAD

**Issue by tfcardoso** [appium/appium#7621]
## The problem

longPress method ignores duration when using UIAutomator2

## Environment

* Appium version: 1.6.3
* Desktop OS/version used to run Appium: OSX & Windows
* Mobile platform/version under test: Android M
* Real device or emulator/simulator: Samsung S5
* Driver: UIAutomator2 v0.2.5
* Java-client: v4.1.2

## Details

element is a valid element. Independently of the duration inserted, it performs a tap/click on element instead of long press.

## Code To Reproduce Issue

    TouchAction touchAction=new TouchAction(driver)
    touchAction.longPress(element,6000).release().perform()

I tried using:

    touchAction.press(element).waitAction(6000).release().perform();

And it works.

**Comment by jlipps** [comment]
I'm actually pretty sure this would be a client issue. `long press` is not part of the action api itself. I'm guessing it's something in how the Java client works. If you shared your appium logs, we could probably prove that hypothesis.

**Comment by tfcardoso** [comment]
Hi, please look at the full logs here:
https://gist.github.com/tfcardoso/6c4d22e0d0d55e5b82181a19e15025ca

The command seen in logs is:

    [debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"element":"b151ddda-1d88-4047-810e-b062fa5b2dc9","duration":6000}},{"action":"release","options":{}}],"a2d11779-24ac-4f6b-bff9-19e2d5bfb5d7"]


By the way on the logs it appears:

    [UiAutomator2] UIAutomator2 Driver version:0.2.3
    [UiAutomator2] Starting uiautomator2 server v0.0.8

And I'm pretty sure these are not the versions I have installed :)

**Comment by jlipps** [comment]
Yes, as I suspected, your client is sending in a `longPress` action as part of the chain, but I don't think that is a valid touch action. If you shared your client code I could probably figure out where the error is.

**Comment by tfcardoso** [comment]
The code is what I mentioned above

    TouchAction touchAction=new TouchAction(driver)
    touchAction.longPress(element,6000).release().perform()

**Comment by sravanmedarapu** [comment]
Using appium-uiautomator2-driver v0.2.11 should fix this issue.

**Comment by sravanmedarapu** [comment]
Closing the issue, Please feel free to report if it is replicating.
