### ISSUE TITLE
Selective autoAcceptAlerts / autoDismissAlerts

### ISSUE THREAD

**Issue by ohadschn** [appium/appium#7623]
The current `autoAcceptAlerts` / `autoDismissAlerts` capabilities are very generic. As I understand it, they will accept/dismiss any and all alerts, including my own app's alerts or alerts I expect due to actions in my test (such as push notification approval). 

What I'd really want to have is a selective variant that provides me with some information on the alert (e.g. title, text, buttons text) and allow me to decide whether I want to let appium handle it automatically, or handle it myself manually (in my test code). That way I can handle alerts I expect, and let Appium handle alerts I don't expect (like OS upgrade) that would have otherwise broken my test.

**Comment by mykola-mokhnach** [comment]
These capabilities are not relevant anymore for XCTest-based Appium backend

**Comment by ohadschn** [comment]
Is there another way to accomplish this in XCUItest then?

**Comment by mykola-mokhnach** [comment]
Nothing we know about. Check this [issue](https://github.com/facebook/WebDriverAgent/issues/335) for more details
