### ISSUE TITLE
/element/:uuid/value endpoint only works on sliders with value 0

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#7626]
When calling 'sendKeys' on a slider element, passing it a value between 0 and 1, the slider value only changes if the value was 0 to begin with. Otherwise, no change takes effect

## Details
Here are the server logs for when /value is applied to a slider with value > 0

```
[JSONWP Proxy] Proxying [GET /element/D9434424-2A17-4F6B-A239-1D842A63E98C/attribute/type] to [GET http://localhost:8100/session/BB0F7F5A-51FF-41CF-AC9E-D6DCBDA1A3E7/element/D9434424-2A17-4F6B-A239-1D842A63E98C/attribute/type] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypeCell\",\n  \"sessionId\" : \"BB0F7F5A-51FF-41CF-AC9E-D6DCBDA1A3E7\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Proxying [POST /element/D9434424-2A17-4F6B-A239-1D842A63E98C/value] to [POST http://localhost:8100/session/BB0F7F5A-51FF-41CF-AC9E-D6DCBDA1A3E7/element/D9434424-2A17-4F6B-A239-1D842A63E98C/value] with body: {"value":["0",".","1"]}
[JSONWP Proxy] Got response with status 200: {"value":"Error Domain=com.facebook.WebDriverAgent Code=1 \"Keyboard is not present\" UserInfo={NSLocalizedDescription=Keyboard is not present}","sessionId":"BB0F7F5A-51FF-41CF-AC9E-D6DCBDA1A3E7","status":13}
```

When you apply it to a slider with value = 0 then this happens
```
[JSONWP Proxy] Proxying [GET /element/D7F25DB5-FDE6-44D0-87F9-C43B7662F815/attribute/type] to [GET http://localhost:8100/session/BB0F7F5A-51FF-41CF-AC9E-D6DCBDA1A3E7/element/D7F25DB5-FDE6-44D0-87F9-C43B7662F815/attribute/type] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypeSlider\",\n  \"sessionId\" : \"BB0F7F5A-51FF-41CF-AC9E-D6DCBDA1A3E7\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Proxying [POST /element/D7F25DB5-FDE6-44D0-87F9-C43B7662F815/value] to [POST http://localhost:8100/session/BB0F7F5A-51FF-41CF-AC9E-D6DCBDA1A3E7/element/D7F25DB5-FDE6-44D0-87F9-C43B7662F815/value] with body: {"value":["0",".","1"]}
[JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"BB0F7F5A-51FF-41CF-AC9E-D6DCBDA1A3E7","status":0}
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): Never worked
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: iPhone 5s version 10.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Node dependency in Appium Desktop

## Link to Appium logs

https://gist.github.com/dpgraham/9e766bd4b4edbcd4281548182235371f

## Steps To Reproduce Issue
* Open appium desktop (npm run dev)
* Start a session with the following desired capabilities:

```javascript
{
  "app": "http://appium.github.io/appium/assets/UICatalog7.1.app.zip",
  "platformName": "iOS",
  "deviceName": "iPhone 5s",
  "platformVersion": "10.2",
  "automationName": "XCUITest",
  "noReset": "true"
}
```

* Open the 'Sliders' menu option in the Simulator
* Select the first slider in the inspector
* Call 'sendKeys' on it with a value between 0 and 1 (nothing will happen)
* Go into the Simulator and manually set the slider to 0 (pull to left)
* Call 'sendKeys' again with a value greater than 0 and less than 1 (the change will occur)
* Call 'sendKeys' again with a value between 0 and 1 (nothing will happen)

**Comment by jlipps** [comment]
Interesting. @marekcirkos do you think this is an XCTest bug? Could we workaround it by setting the slider to 0 first in WDA before then trying to change its value?

**Comment by marekcirkos** [comment]
Wow that sounds crazy. Let me write integration test that checks that. I'll get back to you.

**Comment by marekcirkos** [comment]
Just checked WDA query `curl -X POST $JSON_HEADER -d "{\"value\":[\"0\",\".\",\"1\"]}" $DEVICE_URL/session/$SESSION_ID/element/$EL_ID/value`, multiple times with different values and it works correctly? Can you try updating WDA? Maybe this is an old bug?

**Comment by dpgraham** [comment]
I'll test it again today, thanks.

**Comment by dpgraham** [comment]
Hi @marekcirkos,

I've done some more testing and it appears to be a WebDriverAgent issue. I have attached a zip of a NodeJS script that reproduces the issue.

###What the script does
* Starts a WDA session at http://localhost:8100
* Opens our UICatalog App
* Navigates to a page with slider on it
* Asks the user to enter a value between 0...1
* If the slider has a value > 0 nothing will happen no matter what value is input
* If you manually set the slider to 0 and then set the value again, it will work

###How to run the script
* Unzip the folder
* Run ```node ./test.js```

[WDASliderTest.zip](https://github.com/appium/appium/files/740810/WDASliderTest.zip)

**Comment by arrk-shch** [comment]
Hi,
Any update on this. I am using appium v1.6.4-beta. I am not able to change the value of the slider using setValue/sendKeys. I am executing scripts on simulator.
Thanks

**Comment by jlipps** [comment]
I can confirm this is working in 1.6.4 final

**Comment by marekcirkos** [comment]
There were few issues with `setValue`. @jlipps what was the fix here?

**Comment by dpgraham** [comment]
I can still reproduce this error.

**Comment by jlipps** [comment]
I didn't fix anything. I just confirmed I could change the values multiple times to anything I wanted from any other value. I was using the GUI to do this, though; maybe there's a timing issue relevant to this?

**Comment by arrk-shch** [comment]
@jlipps if possible can you please share the .ipa file or .app file on which you are able to change the value of slider. I tried with GUI with various version of appium and it didn't work for me. We have a native app an most of the functionality is depending on setting the value of the slider. I really stuck up with this. I just want to cross check.

**Comment by arrk-shch** [comment]
I tried with IntegrationApp & its changing values by sendKeys. I'll talk to our developers.

**Comment by ssimakurthy** [comment]
@arrk-shch, did you figured out what is the issue. If the issue is resolved, can you please share me the resolutions

**Comment by arrk-shch** [comment]
@ssimakurthy  Yes when the slider is inside the table then we are not able to set the slider value. If we remove slider from table then it works. This issue is with xcode version. Here is the isseue raised by one of the apple developer
https://www.google.co.in/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiW0732tsHUAhUMsI8KHTNlCOEQFgghMAA&url=https%3A%2F%2Fforums.developer.apple.com%2Fthread%2F77445&usg=AFQjCNEfQ3QXiZfEAHB0bLQmYpscqDhTsw
We are planning to upgrade iOS version to 11 where will able to get newer xcode version. We will try & let you know.

**Comment by ssimakurthy** [comment]
Thank you @arrk-shch . 

In our application slider is not inside the table, it is under XCUIElementTypeOther. and the other thing is, it is a vertical slider not a horizontal slider. Please let me know your findings after upgrading the iOS version to 11.

**Comment by dilsreccse** [comment]
Hi @ssimakurthy , i'm encountering the same issue have you got any resolution for it ,  kindly help team

**Comment by ssimakurthy** [comment]
@dilsreccse , We wrote our own code to manage the sliders

**Comment by dilsreccse** [comment]
Hi @ssimakurthy it would be helpful , if you could share the code snippet for it
