### ISSUE TITLE
/touch/click endpoint not being proxied through WDA

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#7627]
## The problem

Calling `/touch/click` on an element is not doing anything. Returning error saying 'endpoint not being proxied through WDA'

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.6.0
* Desktop OS/version used to run Appium: MacOS
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: iPhone 5s 10.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: NPM dependency

## Link to Appium logs

https://gist.github.com/dpgraham/fc760755872ec39276875483934cc4e4

## Steps To Reproduce Issue
* Open appium desktop (npm run dev)
* Start a session with the following desired capabilities:

```javascript
{
  "app": "http://appium.github.io/appium/assets/UICatalog7.1.app.zip",
  "platformName": "iOS",
  "deviceName": "iPhone 5s",
  "platformVersion": "10.2",
  "automationName": "XCUITest",
  "noReset": "true"
}
```

* Select a menu item
* Click 'Tap Element' button

**Comment by jlipps** [comment]
@dpgraham out of curiosity why are you using that endpoint instead of the usual click one?
