### ISSUE TITLE
driver.get and sDriver.navigate().to() not render the page.

### ISSUE THREAD

**Issue by pyraman** [appium/appium#7628]
## The problem

the 2 functions: driver.get() and sDriver.navigate().to() not render the page although the URL is in address bar.

## Environment

* Appium version: 1.6.3
* Node.js version: 5.1.0
* Mobile platform/version under test: iPad Mini 4, iOS 10.1.
* Real device or emulator/simulator: Real device.
* Client: java-client-4.1.2.jar, selenium-server-standalone-3.0.1.jar

## Details

sometimes functions: driver.get() and driver.navigate.to don't work as expected. The page is not rendered. (https://google.com), but the address is in address bar.

## Link to Appium logs

https://gist.github.com/pyraman/d04904d9eab957d330c67e8681b76eb3

## Code To Reproduce Issue [ Good To Have ]

sCapabilities = new DesiredCapabilities();
		sCapabilities.setCapability("platformName", "iOS");
		sCapabilities.setCapability("platformVersion", "10.1");
		sCapabilities.setCapability("deviceName", "1ed2e482c87218209be4ee3440e4c154666b3468");
		sCapabilities.setCapability("udid", "1ed2e482c87218209be4ee3440e4c154666b3468");
		sCapabilities.setCapability("browserName", "Safari");
		sCapabilities.setCapability("wdaLocalPort", 8101);
		sCapabilities.setCapability("automationName", "XCUITest");
		
		
		
		try {
			sUrl = new URL("http://192.168.167.129:4724/wd/hub");
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
		
		System.currentTimeMillis();
		sDriver = new AppiumDriver<WebElement>(sUrl, sCapabilities, JsonToWebElementConverter.class) {

			@Override
			public void swipe(int arg0, int arg1, int arg2, int arg3, int arg4) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void rotate(DeviceRotation arg0) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public DeviceRotation rotation() {
				// TODO Auto-generated method stub
				return null;
			}
		};
		
		sDriver.manage().timeouts().pageLoadTimeout(15, TimeUnit.SECONDS);
		
		sDriver.get("https://google.com");
		
		String szUrl = sDriver.getCurrentUrl();
		String szTitle = sDriver.getTitle();
		
		File screenshot = sDriver.getScreenshotAs(OutputType.FILE);
		try {
			FileUtils.copyFile(screenshot, new File("D:/screenshot/iPadMini4.png"));
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		sDriver.quit();
![ipadmini4](https://cloud.githubusercontent.com/assets/1914695/21536144/4e52b66e-cdb1-11e6-9096-6f52f2e7a37a.png)

**Comment by pyraman** [comment]
hi! Can anybody please take a look at this?
If i execute script: window.location = "https://google.com" instead of using webdriver API functions, i get the same behavior. Maybe this issues belong to safari.

**Comment by jlipps** [comment]
To me this just looks like an issue with safari or maybe your network (page not loading fully?). Given that the title is coming back correct, Appium did the right thing in talking to the remote debugger. I'd recommend upgrading to the latest version of Appium at this point.
