### ISSUE TITLE
suppress-adb-kill-server didn't work

### ISSUE THREAD

**Issue by codeVerySlow** [appium/appium#7629]
## The problem

i use --suppress-adb-kill-server to start appium(cmd: appium --suppress-adb-kill-server),it still kill adb server and restart.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Desktop OS/version used to run Appium: windows 10 1607
* Node.js version (unless using Appium.app|exe):v6.9.1

## Details

I think the suppressKillServer option did not pass to appium-adb, so i have read the appium-android-driver source code.
then i find the appium-android-driver just pass { javaVersion, adbPort } to appium-adb.

**Comment by jlipps** [comment]
This has been fixed.

**Comment by ajit-jadhav** [comment]
In which version of Appium[deskop] this issue has been fixed?
