### ISSUE TITLE
Appium 1.6.3 - Test hungs - Wait Polling not working

### ISSUE THREAD

**Issue by limitcracker** [appium/appium#7630]
## The problem

I type a word in a search. This made a loader to appear. In my next step I am trying to tap a second a element. This leads Appium to make a POST. There I have expected conditions that keeps polling. 
While in prior versions my expected conditions worked just fine and polling was working in Appium 1.6.3 it hungs and the whole test stops at the point of the first POST request.
If I put a static sleep that warranties loader has finished then test continues fine.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.6.0
* Desktop OS/version used to run Appium: MacOS
* Mobile platform/version under test: iOS 10.2 (XCUITest)
* Real device or emulator/simulator: Real and Emulator

## Link to Appium logs

`[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/83971C74-37C4-4020-9738-787B00269351/element] with body: {"using":"xpath","value":"//XCUIElementTypeStaticText[@name='Dev Ops']/../following-sibling::XCUIElementTypeCell"}`

**Comment by mykola-mokhnach** [comment]
It must be this WDA issue: https://github.com/facebook/WebDriverAgent/issues/372

Try to use non-xpath locator as a workaround or apply visibility patch I mentioned in that WDA issue to your local WDA source

**Comment by limitcracker** [comment]
Thanks for the quick response once again @mykola-mokhnach !
I am trying the patch right now. It helped me with some tests but I think it makes some discrepancies on others. I 'll get back to you when I 'll try some more to be sure.

**Comment by ohadschn** [comment]
For the benefit of Googlers who get here (as I did), I'll sum up the workaround:

1. Assuming you installed appium globally, open `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Categories/XCUIElement+FBIsVisible.m` with your favorite text editor.
2. Replace the content of `XCElementSnapshot`'s `(BOOL)fb_isVisible` method with the following: `return !CGRectIsEmpty(self.frame) && !CGRectIsEmpty(self.visibleFrame) && (CGRectIntersectsRect(self.visibleFrame, self.application.frame) || ((self.application.interfaceOrientation == UIInterfaceOrientationLandscapeLeft || self.application.interfaceOrientation == UIInterfaceOrientationLandscapeRight) && self.application.frame.size.height > self.application.frame.size.width && CGRectIntersectsRect(self.visibleFrame, CGRectMake(0, 0, self.application.frame.size.height, self.application.frame.size.width))));`

**Comment by jlipps** [comment]
Thanks for summarizing the workaround @ohadschn! Closing since it's a WDA issue, not an Appium issue, and interested parties can follow the linked WDA issue.
