### ISSUE TITLE
iOS App crashes after calling window().getSize() - Appium 1.6.3 - XCUITest

### ISSUE THREAD

**Issue by limitcracker** [appium/appium#7631]
## The problem

I go to a screen that is our Sing Out screen. When I go by hand and perform actions app doesn't crash, but when I call `window().getSize()` or any other method via appium on that screen the app crashes.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: MacOS
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: real and emulator

## Link to Appium logs

```
[debug] [MJSONWP] Calling AppiumDriver.getWindowSize() with args: ["current","c0c2d84d-406d-43ea-b6c1-b370e8d23b64"]
[debug] [XCUITest] Executing command 'getWindowSize'
[debug] [JSONWP Proxy] Proxying [GET /window/current/size] to [GET http://localhost:8100/session/68D14552-77E6-4591-836E-5505D4A9D260/window/current/size] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"Application is not running, possibly crashed\",\n  \"sessionId\" : \"68D14552-77E6-4591-836E-5505D4A9D260\",\n  \"status\" : 10\n}"

```

**Comment by mykola-mokhnach** [comment]
What do you see in the device/simulator logs?

**Comment by limitcracker** [comment]
Attached
[iphone-6-plus-emulator-logs.txt](https://github.com/appium/appium/files/677395/iphone-6-plus-emulator-logs.txt)

**Comment by mykola-mokhnach** [comment]
BTW https://github.com/wireapp/wire-ios/blob/develop/Wire-iOS/Sources/UserInterface/Conversation/Content/Cells/ConversationCell.m#L213 
This is how we define accessibility elements for table cells in our app. Maybe, this could be useful for your app as well.
