### ISSUE TITLE
Run script on already launched application

### ISSUE THREAD

**Issue by StevieSun** [appium/appium#7632]
## The problem

I dont want appium to launch the application, because when I run the script the application will already be open. In DesiredCapabilities, the autoLaunch key is not present for iOS. Please help with correct configuration.

## Environment

* Appium 1.6,3
* OS X 10.11.6
* Node.js 5.7.0
* iPhone 6 - iOS 10.1.1

**Comment by pavanbachu0604** [comment]
Can you share the logs as gist ?
