### ISSUE TITLE
Cannot get 'xml' source of the current application

### ISSUE THREAD

**Issue by pisarenco92** [appium/appium#7634]
## The problem

I have some pages in my app that when I call getPageSource() - nothing returns. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: macOS Sierra
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator

## Details
![screen shot 2017-01-02 at 10 38 45 am](https://cloud.githubusercontent.com/assets/15072906/21586268/b03c7742-d0d7-11e6-9c3e-76140bec38c5.png)

I added timeout before getPageSource() - same result.

## Link to Appium logs
https://gist.github.com/pisarenco92/a700e22ea8d970c5f4fd19087abe4b0f

**Comment by mykola-mokhnach** [comment]
Can you attach the device log?

**Comment by botnari** [comment]
Hi! I have the same problem! @mykola-mokhnach How can I add the device log?

**Comment by jlipps** [comment]
@pisarenco92 what is your client code? It's doing something funky. See this line in the logs:

> Proxying [GET /source/xml]

Should be `GET /source`, not `/source/xml`.

**Comment by pisarenco92** [comment]
@jlipps I'm using java-client.

**Comment by mykola-mokhnach** [comment]
@botnari https://support.avg.com/SupportArticleView?l=en&urlName=How-to-collect-console-logs-for-iOS-devices

**Comment by imurchie** [comment]
The proxied command is correct (to `/source/xml`, on the device side). I'm not sure why nothing would be returned, though.

**Comment by jlipps** [comment]
Oh yes, I do now see that the response is to the correct query on the Appium side. Weird that WDA made up their own source API.

**Comment by mykola-mokhnach** [comment]
WDA had only json source implementation before, which was used by the built-in inspector module. And I've recently added XML, which is 1:1 representation of the tree, which is generated for internal xpath search.

**Comment by jlipps** [comment]
Oh right, I remember that now :-)

**Comment by GRyabkin** [comment]
I found out recently that this error happened to me because of used accessebilityIdentifiers on elements without any values specified, empty. By removing them it backs to work normally
