### ISSUE TITLE
issue in automtting native android app

### ISSUE THREAD

**Issue by NamrathaKRao** [appium/appium#7635]
## The problem

Trying to automate a native app.The click and sendKey do not do work. App is getting launched but click on the button is not happening and sendKey gives an error " {"status":13,"value":{"message":"An unknown server-side error occurred while processing the command.","origValue":"Unknown error"}"

## Environment
* Appium version 1.4.16.1, 1.4.13.1
* Desktop OS/version used to run Appium:windows 10
* Mobile platform/version under test:android ,6.0
* Real device or emulator/simulator:real device

## Link to Appium logs
[https://gist.github.com/NamrathaKRao/8b3dceaee0d41609c2c0983d3f1d4333](https://gist.github.com/NamrathaKRao/8b3dceaee0d41609c2c0983d3f1d4333)

## Link of java code
[https://gist.github.com/NamrathaKRao/ae3b496bc75efdebc8bc293322829810](https://gist.github.com/NamrathaKRao/ae3b496bc75efdebc8bc293322829810)

## Link of eclips console log
[https://gist.github.com/NamrathaKRao/d4f375a4ca4f481dd64e64f391a90790](https://gist.github.com/NamrathaKRao/d4f375a4ca4f481dd64e64f391a90790)

**Comment by mykola-mokhnach** [comment]
Does the same error happen to Appium 1.6.3?

**Comment by NamrathaKRao** [comment]
Am not getting the link to download the latest Appium version, 1.6.3. Can the link be shared here please.

**Comment by NamrathaKRao** [comment]
Am facing same issue with Appium 1.6.3 too.

**Comment by jlipps** [comment]
Please update the gist with yoru Appium 1.6.3 logs.

**Comment by NamrathaKRao** [comment]
It worked. am able to run the test now for the native android apps. but not able the locate the elements in the same way ie (driver.findElement(By.xpath("//android.widget.EditText[@content_desc='email']")).sendKeys("namratha@gmail.com");) for application built using React native. is there any other dependency for react native based apps? Please can you help me out with this.

**Comment by jlipps** [comment]
We're currently working on https://github.com/appium/appium/issues/6025 which should address finding elements using react native.
