### ISSUE TITLE
webElement click function not working on appium1.6.3 on real device ios 10.0.1

### ISSUE THREAD

**Issue by xiaoningz** [appium/appium#7636]
## The problem

calling WebElement click function on an element is not doing anything, but show 200 status for the click request

[HTTP] <-- POST /wd/hub/session/c02bd830-b5e4-4f24-93cb-e6f0dc6ab4fa/element/5004/click 200 510 ms - 76 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): no one 
* Desktop OS/version used to run Appium: MacOS v10.11.6
* Node.js version (unless using Appium.app|exe): v6.9.2
* Mobile platform/version under test:  iPad Air 10.0.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

What I want to do is login in with a valid account, but it don't happen when it click the sign in button, I also try the driver.tap(1, element, 1000) method, it also return 200 status code, but still not working as page keep not doing anything.

I used to use below command in real ios device for any click/tap method, but currently, I update the appium to 1.6.3 to support the ios 10,  below command become not supported, so I change to use the element click function, but it seems not working.
```
JavascriptExecute.executeScript("mobile: tap", tabObject)
```
## Link to Appium logs

https://gist.github.com/xiaoningz/bb0fa890cde6b5b1cd604c7e86b62d6e

## Steps To Reproduce Issue
* build the WebdriverAgent to the iPad Air, build the target test app to the iPad Air
* start the ios-webkit-debug-proxy with real iPad Air uuid
* start the appium by comand: appium
* run below code
just a sample code here, 
```
WebElement account= driver.findElement(By.xpath(xpath));
account.sendKeys(user_name);
WebElement pwd= driver.findElement(By.xpath(xpath));
pwd.sendKeys(password);
WebElement login= driver.findElement(By.xpath(xpath));
login.click();
```
the first two sendKeys step work well, but the login.click() not working

**Comment by mykola-mokhnach** [comment]
Is it in landscape mode?

**Comment by mykola-mokhnach** [comment]
what if you calculate coordinates of the text input on the screen and then perform tap by coordinates?

**Comment by xiaoningz** [comment]
@mykola-mokhnach thank a lot. I try the tap with coordinates would work but only when we exchange the x, y coordinates.  it seems that it is the same problem for https://github.com/appium/appium/issues/6994, as you mention the landscape mode, hope it would be in the next appium release.

**Comment by imurchie** [comment]
Can you try using the `nativeWebTap` capability?

**Comment by Jitu1888** [comment]
I have a solution for it to click on landscape mode.

**Comment by jlipps** [comment]
The landscape mode fix will be in Appium 1.6.4!

**Comment by fengzzzz** [comment]
click textview not working in 1.6.5 (android7.0)

**Comment by saimeera22** [comment]
Hi,
I have tried click, tap, touch event for a ionic Cordova application.. it is working at some buttons but in few places it was not working.
Tried with xpath, ID, x and y co-ordinate etc.
Test is passed, as if it clicked the concern element, but it is not redirecting to the next state if click was successful.
I am using Webview_com.xxx as context.
Capabilities set are App package, App activity, uniautomator2 etc..
Please help me with this struck here for past 2 days.
Went through many of ur comments, hope you will help me with this
