### ISSUE TITLE
Getting time out error when find element on web view

### ISSUE THREAD

**Issue by yoosufm** [appium/appium#7638]
## The problem
I am test ios hybrid app. I am getting time out error when find element on web view (Just after switch to web view).

## Environment

* Appium version : 1.6.2
* Desktop OS/version used to run Appium: iOS
* Real device or emulator/simulator: Real Device
## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

https://gist.github.com/yoosufm/6a60482abf478865a69c56fe1aa39f56

## Code To Reproduce Issue [ Good To Have ]

Capabilities ...
---------------------------
 capabilities.setCapability(MobileCapabilityType.UDID, "b86914019a958f66892ee67a72a289ffece8d7a0");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPad Air");
        capabilities.setCapability(IOSMobileCapabilityType.BUNDLE_ID, "com.xxxxx.xxxx");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.IOS);
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.2");
        capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 3000);
        capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.APPIUM);
capabilities.setCapability("realDeviceLogger", "/Users/yoosufm/node_modules/deviceconsole/deviceconsole");
        capabilities.setCapability("xcodeConfigFile", System.getProperty("user.dir") + "/src/main/resources/Config.xcconfig");

**Comment by mykola-mokhnach** [comment]
> Create a gist which is a paste of your full Appium logs, and link them here.

**Comment by yoosufm** [comment]
@mykola-mokhnach gist path is added. Thanks in advance.

**Comment by mykola-mokhnach** [comment]
It would be useful to see the log generated by the device itself

**Comment by yoosufm** [comment]
@mykola-mokhnach thanks for you quick attention

device log 
https://gist.github.com/yoosufm/170bd5a046903b336b38585186c60b59

**Comment by mykola-mokhnach** [comment]
I don't see anything suspicious in the log. Although I've seen similar issue report before and this was happening for web views with many elements.

**Comment by yoosufm** [comment]
Do we need to setup Provisioning profile when build a app? I just saw in one blog. they says we need build using provisioning profile. Thanks in advance.

**Comment by jlipps** [comment]
@yoosufm I'd recommend loading up the Safari inspector with this page open (not involving Appium at all), then running this JS command in the console: 

```
document.getElementsByTagName("html")[0].outerHTML
```

This is what Appium is sending over via the remote debugger. It would be interesting to see if there are likewise problems with this even outside of Appium.

**Comment by yoosufm** [comment]
@jlipps Web view working without any issue on Web and Android app. I am having issue with iOS app. As per dev they using same code for Web, Android and iOS.

**Comment by jlipps** [comment]
@yoosufm what I'm saying is take Appium out of the picture. Launch your app manually on a simulator. Then open the Safari desktop browser and try to connect to the webview in your app, using the debug tools. Does that work?

**Comment by yoosufm** [comment]
@jlipps first of all thanks for your support. I tried above steps. Its not worked.

**Comment by jlipps** [comment]
In that case, there's nothing Appium can do :-( Appium uses the remote debugger to connect to the webview. This is the same technology that Safari uses to connect to an iOS simulator webview. This proves it's not an Appium issue. The next thing I'd do is ensure that the web inspector is enabled (go to Settings > Safari > Advanced, and ensure "Web Inspector" is enabled.

**Comment by yoosufm** [comment]
@jlipps Thanks..
