### ISSUE TITLE
Appium 1.6.1 : Android OS version 6.0.1 : Native app calendar is not handled by appium

### ISSUE THREAD

**Issue by skumar1122** [appium/appium#7640]
## The problem

I am trying to test Android native calendar on web browser using appium UIAutomator. After switching to Native app context, I can't access any of calendar elements by using UIAutomator (used ID,all Xpath's).

Not sure if something has changed with new Appium version, I haven't seen this before with any older versions. 
can someone please suggest ?

**Below my native calendar view in UIAutomator:**
<img width="1184" alt="screen shot 2017-01-03 at 13 56 48" src="https://cloud.githubusercontent.com/assets/20112173/21609951/1ca6de1e-d1bd-11e6-8f13-c5eaf45cfcc6.png">

## Environment
* Appium version (or git revision) that exhibits the issue:1.6.1
* Mobile platform/version under test:Android OS v6.0.1
* Real device or emulator/simulator:Samsung GalaxyS6

**Comment by jlipps** [comment]
@skumar1122 if you'd like us to investigate a potential problem with appium, it's best follow the instructions in the issue template, for example:

> Create a gist which is a paste of your full Appium logs, and link them here. Do not paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, always include Appium logs!
