### ISSUE TITLE
resetApp resets Android app state even when noReset=true and fullReset=false

### ISSUE THREAD

**Issue by Schnutzel** [appium/appium#7642]
## The problem

I am running Appium to test an Android app using the java client. The capabilities include noReset=true and fullReset=false. Executing driver.resetApp() deletes all the app data. This is different from the behaviour on iOS apps, where driver.resetApp() only restarts the app.

From looking at the code, it looks like the reset command always executes adb.stopAndClear, which clears the app data.

For now I managed to workaround the problem by calling driver.closeApp() and driver.launchApp()

## Environment

* Reproduces on various Appium versions, from 1.4.16 to 1.6.3
* Desktop OS/version used to run Appium: Windows 7.
* Mobile platform/version under test: Android 6.0
* Real device or emulator/simulator: Both.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-android-driver/blob/73bbe22d9988570ab40efe04cff5568e40981765/lib/driver.js#L96-L103

https://github.com/appium/appium-android-driver/blob/41c9a5f40d8d90fe00dec6f2a9cd5f3a5a6117b8/lib/android-helpers.js#L333

it looks currently `resetApp` does not clear data when `noReset: true` and `fullReset: false` case.
