### ISSUE TITLE
Not able to identify below xpath element using XCUITest -iOS Automation Native App

### ISSUE THREAD

**Issue by shabinmohan** [appium/appium#7645]
@jlipps ## The problem
Not able to locate the below xpath element:

//XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeStaticText

There are few more elements [l/XCUIElementTypeStaticText] also not able to identify (mostly those are user-created/posted input text or image)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3 with WebDriverAgent 
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: MAC Sierra 10.12.1
* Node.js version (unless using Appium.app|exe): 6.9.2
* Mobile platform/version under test:  iOS 10.1.1
* Real device or emulator/simulator: Real Device

## Details

When came to the below element(xpath "My Post" it took almost 1 or 2 mins to throw the null value

[//XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther[2]/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell/XCUIElementTypeStaticText]

(Basically the user input text have to verify but not ale to identify this element)
In Appium-iOS-Inspector the element showing above xpath and as it is a user input label is same as user input text)

## Link to Appium logs

Appium Logs :

https://gist.github.com/shabinmohan/694e7c634d3e5b3c28bcfb1b6d3721c8.js

**Comment by mykola-mokhnach** [comment]
Do you see these elements in the accessibility tree when you use built-in XCode inspector tool?
