### ISSUE TITLE
Not able to run test on 2 different iOs real devices

### ISSUE THREAD

**Issue by jeangb** [appium/appium#7646]
## The problem

Hi,
In order to test main features of my application, I need to execute tests using 2 devices.

I'm able to launch tests controlling 2 Android devices at the same time, using 2 different servers (one with port 4723 and the other with port 4724).

So I thought I could do the same with iOS devices.
However the second server isn't able to launch the application under test on the second device: he can launch the WDA but not my application ; I have a 

> [XCUITest] iproxy exited with code '208'
> [XCUITest] Error: iproxy exited with code '208'

 error.
Full logs of the second server are [here](https://gist.github.com/jeangb/3bc5dbd6a2b7333e875531ae832f96f2).
As it was not working the first time, I changed the second appium server and I use _appium -a 127.0.0.1 -p 8080_ instead of _appium -p 4724_, but it still doesn't work.
I read [here](https://discuss.appium.io/t/support-for-automating-multiple-devices-simultaneously/230/4) that it was not possible to do this on iOS, but I doubt that. 
Have people ever manage to do this ?

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Desktop OS/version used to run Appium: Mac OS 10.11.6
* Node.js version (unless using Appium.app|exe): 3.10.10
* Mobile platform/version under test: iOs 9.3.2 and iOS 9.3.5
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: CLI

**Comment by imurchie** [comment]
Can you try adjusting the local port for one of the servers? Using `--webdriveragent-port`.

**Comment by imurchie** [comment]
I'm not sure that this is possible, but that would get you past the iproxy error, anyway.

**Comment by jeangb** [comment]
Hi, thank you, I'm able to launch the application on the device now !
But this is very very slow. The time that appium server 2 click on a button on device 1, appium server 1 close the application on the first device due to timeout...

**Comment by imurchie** [comment]
Unfortunately this hasn't been tested. It probably is not possible.

**Comment by jeangb** [comment]
Thank you for your answer. It's too bad because I'm able to doing well with Android.

**Comment by imurchie** [comment]
Yes, Android has much better support for testing. Apple disallows a lot of stuff in its tools.

**Comment by jlipps** [comment]
Pretty sure this is theoretically possible, however we haven't put time into supporting it. No clue why it would be slow.

**Comment by jeangb** [comment]
Maybe if all the objects were identified with accessibility ids, it should be fast enough.

**Comment by pavanbachu0604** [comment]
@imurchie How can i run the parallel tests on 2 iOS devices (Appium 1.6.3 and iOS 10.2 devices)

**Comment by jeangb** [comment]
FYI it seems to work pretty well, using the capability newCommandTimeout helped me.
Indeed as tests are running pretty slow, even using accessibilityId, one of the two server often exceeded the timeout.

> capabilities1.setCapability("newCommandTimeout", 1200);

**Comment by jlipps** [comment]
OK, well I'll go ahead and close this issue. We may have another open one already about general slowness in the xcuitest support.

**Comment by jeangb** [comment]
@jlipps About the slowness with xcuitest: I should ask this question in the appropriate issue but I don't find it.
It was really faster with the old automation framework ?

**Comment by jlipps** [comment]
@jeangb I guess so. At least there's nothing in Appium that appears to be adding to the slowness. We're just making HTTP calls to WebDriverAgent :-/

**Comment by jeangb** [comment]
@jlipps I'm sure this is not due to appium. However it's ok using accessibility id, but the development team must be concerned motivated to add theses accessibility ids.
