### ISSUE TITLE
Appium occasionally fails to enter keyboard input

### ISSUE THREAD

**Issue by codiophile** [appium/appium#7651]
## The problem

Appium occasionally fails to enter keyboard input.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: mac 10.12
* Node.js version (unless using Appium.app|exe): v7.0.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details

When using `driver.action.send_keys(text).perform` the keyboard input is occasionally not registered by the app. There is no exception thrown and the test will fail as soon as it discovers that it is in the wrong state. 

This started happening after migrating to iOS 10 and XCUITest. 

## Link to Appium logs

Unfortunately, the Appium logs have not been retained. We only keep the Appium logs for the last run (since they are massive) and this error did not occur during the last run. It does occur quite frequently, so I might be able to update this issue with logs.

**Comment by imurchie** [comment]
Please do update with logs next time it happens.

**Comment by codiophile** [comment]
I added a 1 second sleep before every `driver.action.send_keys(text).perform` and since then we haven't had a single failure because of this reason. I'm assuming the timings changed in the switch to XCUITest which causes Appium to send input before the app is ready to receive it.

**Comment by imurchie** [comment]
Unfortunately, there is no way for Appium to know if/when the app is ready to receive something. :(

**Comment by codiophile** [comment]
I'm guessing that you are at least checking that the keyboard is on screen. Maybe it would be worth adding a small delay between detecting the keyboard and sending input?

**Comment by kcinman11358** [comment]
i'd recommend putting a wait in your test code rather than a thread.sleep
