### ISSUE TITLE
How to setup safari to start on blank page and not appium.io 

### ISSUE THREAD

**Issue by nikolmarku1** [appium/appium#7652]
## The problem
When browser safari start it starts with appium.io url open 
Can I change this to about:blank and how ?

## Environment

* Appium version : 1.6.3 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: iOS 10.12.2
* Node.js version (unless using Appium.app|exe):  7.3.0
* Mobile platform/version under test:  iPad mini 9.3.5
* Real device or emulator/simulator: Real  iPad mini 9.3.5
* Appium CLI or Appium.app|exe:
Xcode 8.2.1 

## Details

Describe in more detail the problem you have been experiencing, if necessary.

As I want to start my test on my company website is normal to start the test on blank page

**Comment by nikolmarku1** [comment]
[appiumlog.txt](https://github.com/appium/appium/files/687702/appiumlog.txt)
GIST
https://gist.github.com/nikolmarku1/b784ffcf85ab6c6dc75e2018819b28f6

**Comment by imurchie** [comment]
Try using the `safariInitialUrl` desired capability.

**Comment by jlipps** [comment]
I believe we used to go to about:blank but it did not have the same kind of webview or something. Maybe it'd work nowadays.

**Comment by nikolmarku1** [comment]
Thanks imurchie ....
