### ISSUE TITLE
AUT stops immediately after launch - "App accessibility isn't loaded"

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/appium#7653]
After updating Appium and the XCUITest driver, my app under test now terminates immediately after opening. 

The Appium log says "App accessibility isn't loaded".

I've asked the Google about this, and it seems most people who've run into this problem are trying to deploy ARM-build IPAs to their sim. In my case though, I'm building the app seemingly properly:

`xcodebuild clean build -scheme "TestApp Alpha" -sdk iphonesimulator10.2 -arch "x86_64" ONLY_ACTIVE_ARCH=NO VALID_ARCHS="i386 x86_64"`

Appium log: https://gist.github.com/VivaLosDoyers/2eb688be0e897347f4fbeafb41ac38e5

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.6.1
* Desktop OS/version used to run Appium: OS X 10.12.1
* Node.js version (unless using Appium.app|exe): 7.0.0
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: sim
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
Are you sure the app with the "com.oblong.TestApp-Alpha" identifier is installed properly before WDA is started? Do you get the same output after you execute xcodebuild from the terminal?

```
xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=C9D8B3A0-B994-46D3-A9B6-A5DC71AA33DE -configuration Debug
```

**Comment by VivaLosDoyers** [comment]
I'm fairly certain the app is not installed properly, because I can't manually launch it either.

With that said, I've used the exact same build method for months now (using the xcodebuild string I posted above), so I'm really not clear on what could have changed for it to suddenly stop working.

I'm confident that my app itself is OK, because if I build and deploy to the simulator through Xcode directly, it works.

Here's the output when running the command you specified: https://gist.github.com/VivaLosDoyers/fd29cfb5fcf308ee2aed1387d601cf99

**Comment by rkavalap** [comment]
@VivaLosDoyers Did you trust the AUT in settings ?

**Comment by VivaLosDoyers** [comment]
@rkavalap is that something you need to do for the simulator? I've never seen it pop up any dialogs regarding trust.

**Comment by rkavalap** [comment]
Oops. My earlier statement was something i encountered for real device. That is the developer / Enterprise signing the app needs to be trusted for you continue further.

**Comment by VivaLosDoyers** [comment]
It looks like the way I was building the app was the problem. Interestingly though, I've been building this way for months, and this was not problem until updating to appium 1.6.3 (it worked with 1.6.0).

Instead, I'm now building this way:
`xcodebuild -project TestApp.xcodeproj/ -scheme 'TestApp Alpha' -destination 'platform=iOS Simulator,name=iPad Retina,OS=10.2'`

**Comment by dpgraham** [comment]
Can we close this issue or are there any issues left?

**Comment by VivaLosDoyers** [comment]
If you ask me, it's worth investigating why my build style suddenly stopped working. But at least I have a workaround.

**Comment by jlipps** [comment]
@imurchie what changes did we make to the way WDA is built? Or could this just be due to WDA upgrades?
