### ISSUE TITLE
"Could not proxy command" when getting logcat logs with UiAutomator2

### ISSUE THREAD

**Issue by adarliu** [appium/appium#7654]
## The problem

I tried to get the logs with Python client. However, I always got the error "Could not proxy command to remote server. Original error: 404 - undefined".

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: WIndows 10
* Node.js version (unless using Appium.app|exe): 6.9.3
* Mobile platform/version under test: Moto Z, Android 6.0.1
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/adarliu/259f5dae3ca253b9ff73d502683cb8c3

**Comment by jlipps** [comment]
Thanks for reporting, @adarliu. It looks like uiautomator2 does not respond to the logs command. @sravanmedarapu, should it? Or should we just not proxy it to the uiautomator2 server?

**Comment by sravanmedarapu** [comment]
@jlipps, We should not proxy it to the uiautomator2 server.

**Comment by sravanmedarapu** [comment]
Using appium-uiautomator2-driver v0.2.7 should fix the issue.
