### ISSUE TITLE
Concurrent Android emulators

### ISSUE THREAD

**Issue by SteffenL** [appium/appium#7655]
## The problem

I am in most cases unable to run multiple Android emulators concurrently because Appium is unable to find one of the emulators. It looks like a bug to me now but I will explain more and let you decide.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.12.2
* Node.js version (unless using Appium.app|exe): 7.1.0
* Mobile platform/version under test: 5.1.1, 7.1.1
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

There is one case where concurrent emulators actually work, and one where it does not. I will share logs from the case where it does not work.

I run two Appium server instances with the following parameters:
```
appium --default-capabilities default-capabilities-02.json --port 4725 --bootstrap-port 4726 --chromedriver-port 9515
appium --default-capabilities default-capabilities-03.json --port 4727 --bootstrap-port 4728 --chromedriver-port 9517
```
default-capabilities-02.json:
```json
{
    "avdArgs": "-port 5556",
    "udid": "emulator-5556"
}
```
default-capabilities-03.json:
```json
{
    "avdArgs": "-port 5558",
    "udid": "emulator-5558"
}
```
Run the script below in this order without any emulators running:
```
python test_android_appium.py chrome 7.1 4725
python test_android_appium.py browser 5.1 4727
```
Note: Make sure to create AVDs with the names "Nexus_5_5.1" and "Nexus_5_7.1".

In this case, the first emulator will boot up and run the tests successfully. The second emulator is stuck with a black screen, unable to boot.

I make a note of a couple weird lines in one of the logs:
```
[debug] [ADB] Telnet command got response: Nexus_5_7.1
[debug] [ADB] Emulator Nexus_5_5.1 not running
```
There is however a way to make this work by running both commands immediately:
```
python test_android_appium.py chrome 7.1 4725 &
python test_android_appium.py browser 5.1 4727 &
```
Both emulators boot up and run the tests. From this point, I can run new tests successfully on both emulators. I suspect that this may not always work.

## Link to Appium logs

02: https://gist.github.com/SteffenL/9719119c7d15ddc267cafb49797b2f7c
03: https://gist.github.com/SteffenL/8112fad8ad38ee45a849193a2b90fd86

## Code To Reproduce Issue [ Good To Have ]

test_android_appium.py:
```python
import sys
from selenium import webdriver

def main():
    browser = sys.argv[1]
    version = sys.argv[2]
    webdriver_port = sys.argv[3]

    cap = {"browserName": browser, "platformName": "Android", "deviceName": "Android Emulator", "platformVersion": version, "avd": "Nexus_5_{0}".format(version)}
    driver = webdriver.Remote("http://localhost:{0}/wd/hub".format(webdriver_port), cap)
    driver.get("http://www.seleniumhq.org/")
    driver.quit()

if __name__ == "__main__":
    main()
```

**Comment by imurchie** [comment]
Interesting. Looking into this.

**Comment by imurchie** [comment]
I'm seeing the same behavior. Digging a little deeper.

**Comment by imurchie** [comment]
Unfortunately, this seems like an Android problem. Without Appium I still can't get two Emulators to start. One always sits with a black screen. Each individually works fine.

You can try. The command is like

```
/usr/local/Cellar/android-sdk/24.4.1_1/tools/emulator -avd Nexus_5_5.1 -port 5558
```

**Comment by imurchie** [comment]
This might be related to Intel. I can get it to work if one of the emulators is ARM based and the other Intel.

**Comment by SteffenL** [comment]
Thanks for looking into this. Feels like the ARM-based emulator takes forever to boot (even Appium gives up). :)

When using Intel for both emulators, do you happen to see this in the console?
```
The memory needed by this VM exceeds the driver limit.
```

I was able to launch both emulators in sequence after making adjustments to the limit.

**Comment by SteffenL** [comment]
Despite the emulators seeminly working, the console still says things like..
```
[debug] [ADB] Telnet command got response: Nexus_5_5.1
[debug] [ADB] Emulator Nexus_5_7.1 not running
```

No idea if that was intended or not.

**Comment by imurchie** [comment]
Yes, adjusting the limit let me run your scenario, too.

The logs will say that until the new emulator is available. It is querying what is there, and gets the other emulator, so tries again.
