### ISSUE TITLE
"An unknown server-side error occurred while process ing the command." when call driver.back() with automationName "uiautomator2"

### ISSUE THREAD

**Issue by adarliu** [appium/appium#7656]
## The problem

When calling driver.back() while automationName is uiautomator2, the Python client always got exception "WebDriverException: Message: An unknown server-side error occurred while process
ing the command."

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 6.9.3
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real Android device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/adarliu/f36b6c7746b4389ad1314ce8691aa509

**Comment by sravanmedarapu** [comment]
```
 Could not proxy command to remote server. Original error: 500 - {"sessionId":"7defe6f6-76db-4c62-82a3-61be2524f219","status":13,"value":false}
```
Is `back` operation performed ?

**Comment by adarliu** [comment]
@sravanmedarapu Yes, the back operation was performed on the phone, even there was the error.

**Comment by sravanmedarapu** [comment]
Using appium-uiautomator2-driver v0.2.7 should fix the issue.
