### ISSUE TITLE
Unable to Build WebDriverAgent using Appium 1.6.1

### ISSUE THREAD

**Issue by nidhitri** [appium/appium#7657]
## The problem

Unable to build Webdriver Agent using Appium 1.6. **Getting Error as:**-

[Xcode] Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'
Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'
Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'

[Xcode] 
Testing failed:
Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.1'
** TEST FAILED **

**The following build commands failed:
Check dependencies
(1 failure)

[XCUITest] **xcodebuild exited with code '65' and signal 'null'****
[debug] [XCUITest] xcodebuild failure warrants retry. Retrying...

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.1
* Desktop OS/version used to run Appium: OS X EI Capitan (Ver 10.11.6)
* Node.js version (unless using Appium.app|exe):6.1.0
* Mobile platform/version under test:IOS 10.1
* Real device or emulator/simulator:Iphone 6

## Details

Tried Solutions like using .Xcconfig file as well where w have mentioned the Development Team and code signing identity and given the capability for using that config file as well. Still facing the same issue.

## Link to Appium logs

https://gist.github.com/nidhitri/e6b41e4d14c031a1139f0fb7a99eede5

## Code To Reproduce Issue [ Good To Have ]

package demo;

import java.net.MalformedURLException;
import java.net.URL;

import io.appium.java_client.ios.IOSDriver;

import org.openqa.selenium.remote.DesiredCapabilities;

public class check {

public static void main(String args[]) throws Exception{
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("platformName", "iOS");
capabilities.setCapability("platformVersion", "10.1");
capabilities.setCapability("deviceName", "bf92e5ccd0ce489ff8f29900ca4c2ab73c7f4c1d");
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("udid","bf92e5ccd0ce489ff8f29900ca4c2ab73c7f4c1d");
capabilities.setCapability("browserName", "safari");
capabilities.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
//capabilities.setCapability("app", "/Users/macbookpro/Desktop/Sharanya/ipa/TestmunkDemo.ipa");
//capabilities.setCapability("bundleid", "com.cognizantmobile.TestmunkDemo");
System.out.println("driver initialized");
  capabilities.setCapability("xcodeConfigfile","/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/xcodeConfigFile.xcconfig");
IOSDriver driver = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
System.out.println("driver over");
driver.get("www.google.com");
}
}

**Comment by mykola-mokhnach** [comment]
There is a problem with WDA code signing. Make sure you follow real device configuration steps from https://github.com/appium/appium-xcuitest-driver#usage
