### ISSUE TITLE
After running for some time,WDA response very slowly.

### ISSUE THREAD

**Issue by xyuklin** [appium/appium#7658]
## The problem
After running for some time,WDA response very slowly.
(appium-xcuitest-driver v2.5.2)

[HTTP] --> POST /wd/hub/session/04e60673-d667-4d44-905e-48fce7035640/touch/perform {"actions":[{"options":{"x":150,"y":150},"action":"press"},{"options":{"ms":500},"action":"wait"},{"options":{},"action":"release"}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"options":{"x":150,"y":150},"action":"press"},{"options":{"ms":500},"action":"wait"},{"options":{},"action":"release"}],"04e60673-d667-4d44-905e-48fce7035640"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-wait-release
[debug] [JSONWP Proxy] Proxying [POST /touchAndHold] to [POST http://localhost:8100/session/69D6F93D-F80E-425F-9D99-7327284F8FCB/touchAndHold] with body: {"duration":0.5,"x":150,"y":150}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"69D6F93D-F80E-425F-9D99-7327284F8FCB","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/04e60673-d667-4d44-905e-48fce7035640/touch/perform 200 **95151** ms - 74 
[HTTP] --> POST /wd/hub/session/04e60673-d667-4d44-905e-48fce7035640/touch/perform {"actions":[{"options":{"x":329,"y":237},"action":"press"},{"options":{"ms":500},"action":"wait"},{"options":{},"action":"release"}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"options":{"x":329,"y":237},"action":"press"},{"options":{"ms":500},"action":"wait"},{"options":{},"action":"release"}],"04e60673-d667-4d44-905e-48fce7035640"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-wait-release
[debug] [JSONWP Proxy] Proxying [POST /touchAndHold] to [POST http://localhost:8100/session/69D6F93D-F80E-425F-9D99-7327284F8FCB/touchAndHold] with body: {"duration":0.5,"x":329,"y":237}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"69D6F93D-F80E-425F-9D99-7327284F8FCB","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/04e60673-d667-4d44-905e-48fce7035640/touch/perform 200 **233668** ms - 74 

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Last Appium version that did not exhibit the issue (if applicable):1.6.0
* Desktop OS/version used to run Appium:osx 10.12.1
* Node.js version (unless using Appium.app|exe):v7.2.0
* Mobile platform/version under test:ios 10.1.1
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe:CLI

## Link to Appium logs

[appium.txt](https://github.com/appium/appium/files/689384/appium.txt)

**Comment by imurchie** [comment]
Can you turn on timestamping and re-post the logs (as a [gist](https://gist.github.com), not a txt file)? That will allow us to see where the time is being spent. Just use the `--log-timestamp` flag when starting Appium.

**Comment by StevieSun** [comment]
In my case the WDA does not startup at all..!!!
Any support on this is very much appriciated. I waited for almost 4 minutes and still the WDA did not finish starting. Please find the gist below. Thanks in advance.
[https://gist.github.com/StevieSun/ab201c65b03e9ffe1d79e9cd393e3b29](url)

**Comment by mykola-mokhnach** [comment]
@xyuklin Does this problem happen if you run this this test not as a part of test sequence? Because it might be related to [this](https://github.com/facebook/WebDriverAgent/issues/372) WDA issue.

**Comment by xyuklin** [comment]
@imurchie I had re-post the logs https://gist.github.com/xyuklin/0ab095383987a76c12fd1e7eeb933941

**Comment by xyuklin** [comment]
@mykola-mokhnach After the implementation of many times will appear

**Comment by mykola-mokhnach** [comment]
I see there's a big delay between sending request and getting a response from WDA. Can you also attach the log from the device for this time period when requests are getting too slow?

**Comment by xyuklin** [comment]
appium log: https://gist.github.com/xyuklin/e24d2e468bf9b66b9dcfaf041f9880b9
device log:https://gist.github.com/xyuklin/70a1399a5b22e6ec7a40adbbd02b2492

**Comment by mykola-mokhnach** [comment]
I see only one potential candidate for making delays in the log:

```
XCTRunner(WebDriverAgentLib)[274] <Notice>: Enqueue Failure: UI Testing Failure - Failed to get snapshot within 15.0s <unknown> 0 1
```

And this is Apple's XCTest issue for sure. Have no idea why it happens though. @xyuklin Probably, you can observe what is happening in your app at the time when the corresponding logline appears.

**Comment by xyuklin** [comment]
Thanks for your detailed reply.I try to run the case without appium ,found the wda response time has been increasing.
https://gist.github.com/xyuklin/668833d8abc6a0185f5de1dad1caf0d4
