### ISSUE TITLE
in iOS system, getPagesource function works very slow

### ISSUE THREAD

**Issue by wangtao169447** [appium/appium#7660]
## The problem

the getPagesource() works very slow in iOS; however which works very quick in Android
in Android system, less than 1 second
in iOS,more than 10 seconds

the gist path of log:https://gist.github.com/wangtao169447/60587200d4b0835dd301bc9e5fc32994

thanks for your help

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac OS

**Comment by mykola-mokhnach** [comment]
This is not appium issue, but rather Apple's XCTest framework, which we use as a backend, is slow and buggy. Also, XCTest does not directly support neither XML representation of the UI tree nor XPath search. That is why this is slow and we hardly can do anything to speed it up.

**Comment by wangtao169447** [comment]
@mykola-mokhnach
thanks
