### ISSUE TITLE
Getting error while running appium with iOS 10

### ISSUE THREAD

**Issue by tadesushilgithub** [appium/appium#7662]
## The problem

[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
[MJSONWP] Encountered internal error running command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.2
* Last Appium version that did not exhibit the issue (if applicable): 1.3
* Desktop OS/version used to run Appium: iOS 10.2
* Node.js version (unless using Appium.app|exe):  6.3.1
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: 

## Details

Not able to figure out what is the issue with?

## Link to Appium logs

https://gist.github.com/tadesushilgithub/f1ed1fd063d8766df746d8a3fc905eb8.js

## Code To Reproduce Issue [ Good To Have ] -NA

**Comment by mykola-mokhnach** [comment]
Please search existing issues. This one has been reported many times already.
