### ISSUE TITLE
process.env.HOME undefined when Appium tries to start an iOS simulator

### ISSUE THREAD

**Issue by steinwelberg** [appium/appium#7663]
## The problem

When running tests using Appium with the `XCUITest` automator on a simulator I run into the following problem. The simulator fails to start due to the following error: the home directory path cannot be resolved. `process.env.HOME` is resolved to `undefined`. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable): Don't know
* Desktop OS/version used to run Appium: Mac OS 10.11.6
* Node.js version (unless using Appium.app|exe): 6.9.4
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: simulator (iPhone 6s) 9.3
* Appium CLI or Appium.app|exe: CLI

## Details

I've added a log statement in the file where the error occurs and saw that the response of `process.env.HOME` is actually undefined. When I open a terminal window and execute `echo $HOME` I see that this variable points to my home directory.

## Link to Appium logs

https://gist.github.com/steinwelberg/13cf604bee960ebed9cf0d41e5b14e43

## Code To Reproduce Issue [ Good To Have ]

On another mac I cannot reproduce this issue because the home directory is properly resolved there.

**Comment by mykola-mokhnach** [comment]
How do you execute appium? Usually, a new process inherits environment from its parent. So, in case you execute Appium as a system service, then it might be possible these env vars are not initialised yet on this stage.

**Comment by steinwelberg** [comment]
Hmm good point Mykola, we are running Appium as a daemon.. That is also probably why I couldn't reproduce this issue on another mac where I'm running Appium in a terminal window..

Thanks for the Tip, I'll investigate this, and it will probably solve my issue.

Thanks for the quick reply!

**Comment by steinwelberg** [comment]
Adding an additional environment variable to the daemon configuration resolved my issue. Thanks again @mykola-mokhnach  for your quick reply!

**Comment by HoonHee** [comment]
i set environment variable.

    /usr/bin
    /bin
    /usr/sbin
    /sbin
    /usr/local/bin

what is "all the necessary environment variables" ??
