### ISSUE TITLE
Always Unable to connect to WDA for 60 secs

### ISSUE THREAD

**Issue by pankyopkey** [appium/appium#7664]
## The problem

In the Appium Logs, i am seeing this log everytime i try to create a session. It waits for 60 seconds to connect to the WDA, and then says unable to connect.

## Environment

* Appium version (or git revision) that exhibits the issue : 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe): v7.2.1
* Mobile platform/version under test: 10.1
* Real device or emulator/simulator: Real iOS Device
* Appium CLI or Appium.app|exe: CLI

## Details

Describe in more detail the problem you have been experiencing, if necessary.

> ################################################################################
> 
>  2017-01-09 13:37:01:231 - info: [debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
> 2017-01-09 13:37:01:844 - info: [debug] [XCUITest] Log file for xcodebuild test: /Users/lalitjain/Library/Developer/Xcode/DerivedData/WebDriverAgent-atqsdljwcmtjkwbegjfdwgfpoeqm/Logs/Test/B52E4748-9E78-453D-9F68-4333149D4123/Session-WebDriverAgentRunner-2017-01-09_190701-aLVMQL.log
> 2017-01-09 13:38:02:187 - info: [debug] [XCUITest] Unable to connect to running WebDriverAgent: Error: connect ECONNREFUSED 127.0.0.1:8100
> 2017-01-09 13:38:02:188 - warn: [XCUITest] Getting status of WebDriverAgent on device timed out. Continuing
> ################################################################################
> 
Why is appium trying to connect to WDA on **localhost and device port?**
If this wants to connect to iProxy, then it should connect to localhost and local iProxy Port which is 16001 and not 8100

## Link to Appium logs
https://gist.github.com/pankyopkey/2a3a020fbe451dddefba3a6f48310fb8

**Comment by imurchie** [comment]
Hmm. Yes, it should. Investigating.

**Comment by anshumanchatterji** [comment]
This happens when i change the wdaLocalPort while launching the Appium CLI. I beleive this should be a minor fix where instead of the wdaLocalPort, the port where WDA is listening to in the device is being used.

**Comment by imurchie** [comment]
Can you try updating? I have fixed this.

**Comment by anshumanchatterji** [comment]
@imurchie How to take the update? I dont see any push in the git for the last 6 days.

**Comment by anshumanchatterji** [comment]
@imurchie ..

**Comment by imurchie** [comment]
It was fixed in https://github.com/appium/appium-xcuitest-driver/commit/0e2d8c3bdff4355a370f7c67d9976d6e17258126 which should be in version 2.5.3 of the driver.
