### ISSUE TITLE
Running Appium Scripts in iOS 10 devices parallely

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#7665]
Device iOS Version : iOS 10.2 
Appium : 1.6.3

**Req: Need to run automation scripts in iOS 10.2 using Selenium-Grid** 

Experimented Methods:
1. Passing the wdaLocalPort as capability in nodeconfig file
  _Observation_ : Both the devices are pointing to 8100 and error in appium logs : iproxy exited with 208

2. Pass the wdaLocalPort as the capability in Code, wdaLocalPort would increment dynamically.
 _Observation:_ Same as above.

Any help is appreciated .

**Comment by vikramvi** [comment]
@pavanbachu0604 please ask this in discuss.appium forum. This place is to file bugs related to appium server only

@triager please close
