### ISSUE TITLE
Unable to click a button when an alert is displayed in the background

### ISSUE THREAD

**Issue by nchinenk** [appium/appium#7666]
I have this command:

wd.find_element_by_xpath("//XCUIElementTypeButton[@name='Cancel']").click()

or using full Xpath:

wd.find_element_by_xpath("//XCUIElementTypeApplication[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[2]/XCUIElementTypeButton[2]").click()

which no matter what time out I set returns an error: An element could not be located on the page using the given search parameters.

I'm running Appium 1.6.3 from the Terminal and in its log I see the following:

[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/F5298351-AA27-43B7-AA22-B5CAAD72CD04/element] with body: {"using":"xpath","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[2]/XCUIElementTypeButton[2]"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"**Alert is obstructing view**","sessionId":"F5298351-AA27-43B7-AA22-B5CAAD72CD04","status":26}
[HTTP] <-- POST /wd/hub/session/9843786c-bd74-4566-87df-3e99d7c82272/element 500 3776 ms - 164 

I know there is an alert box behind the window where I try to click the button to close it, so I can get to that alert, but it won't let me.

I think based on the Appium log the alert which is displayed in the background somehow prevent the window on top of it from being discovered, but not sure how to solve that.

**Comment by mykola-mokhnach** [comment]
What happens if you call driver.switchTo().alert().accept() to accept the alert first?

**Comment by nchinenk** [comment]
I'm getting an error for this line of code you provided:

AttributeError: 'WebDriver' object has no attribute 'switchTo'

**Comment by mykola-mokhnach** [comment]
in python this might have different name. Try switch_to

**Comment by nchinenk** [comment]
I used wd.switch_to().alert().accept(). Now the following error appears:

AttributeError: MobileSwitchTo instance has no __call__ method

Sorry, I've never used this method before. Trying to find out what the syntax in Python is for it.

Thanks!

**Comment by nchinenk** [comment]
wd.switch_to_alert().accept() worked, but it still doesn't find the button and displays same error in the terminal Appium log: Alert is obstructing view

**Comment by jlipps** [comment]
I'm not sure if there's anything we can do about this. This is the logic that webdriveragent uses to determine whether elements are obstructed by an alert: https://github.com/facebook/WebDriverAgent/blob/b2e1c07d1028b696708b64b130292770b72e8052/WebDriverAgentLib/FBAlert.m#L150-L164

looks like it does some kind of ancestor check. Maybe there's a way to design the app slightly differently so that this doesn't happen? Sorry we can't be of more use. I'd ping the webdriveragent project directly as maybe they know more about this.

**Comment by nchinenk** [comment]
Isn't it related to https://github.com/facebook/WebDriverAgent/issues/384 for which there seems to be a fix now?

**Comment by jlipps** [comment]
Maybe so @nchinenk. In that case, did you try the latest appium xcuitest driver?

**Comment by nchinenk** [comment]
How do I install the latest appium xcuitest driver on top of existing appium installation?

**Comment by jlipps** [comment]
One way is as follows:

```
npm uninstall -g appium
npm install -g appium --no-shrinkwrap
```

This instructs npm to ignore the locked dependency tree and instead install the newest subpackages according to the version spec. In this case it should pull in `appium-xcuitest-driver@2.5.3`, which is the latest.

**Comment by nchinenk** [comment]
I've tried this. Unfortunately, it didn't solve my issue.

**Comment by jlipps** [comment]
@nchinenk in the output of the npm install command, did it say that it installed appium-xcuitest-driver at 2.5.3?

**Comment by nchinenk** [comment]
It actually installed 2.5.4 it seems:

appium-xcuitest-driver@2.5.4
