### ISSUE TITLE
Appium can't launch .ipa with iOS 10 beta / Xcode 8 beta

### ISSUE THREAD

**Issue by SumanthSanathi** [appium/appium#7667]
**Appium can't launch ipa with iOS 10 beta / Xcode 8 beta.**

Environment

Appium version : 1.6
Desktop OS/version used to run Appium: OS X 10.12
Mobile platform/version under test: iPhone 6S with iOS 10
Real device or emulator/simulator: **Real device**
**Xcode 8 beta**

**Comment by mykola-mokhnach** [comment]
There 's not enough information to help. We need at least both logs: xcode and appium.
