### ISSUE TITLE
[HELP ] could not find shrinkwrap;  skipping fixing shrinkwarp

### ISSUE THREAD

**Issue by huanglik** [appium/appium#7673]
i check out the source of appium
when i run 'npm install', it works well and i can use 'node .' launch appium

however, when i modify the source of appium, just like adding more log , and then try to rebuild appium, it occurs something wrong like ' not find shrinkwrap;  skipping fixing shrinkwarp' 
<img width="994" alt="143ad7ef-6afc-4a02-b8e7-f2e3b2bbc4f5" src="https://cloud.githubusercontent.com/assets/3026388/21807622/9c1c5c6a-d77a-11e6-8a3a-1f7f96d021d0.png">

**Comment by dpgraham** [comment]
I was able to reproduce this on my side. Even with the 'skipping fixing shrinkwrap' message, ```node .``` still works fine.

If you want the error to go away though, try calling ```npm shrinkwrap``` before you call ```npm install```.

**Comment by jlipps** [comment]
The "could not find shrinkwrap" message is expected. This is a gulp task which is designed to fix the shrinkwrap before publishing, if the shrinkwrap exists. If it doesn't, then it just skips it. No problems here unless you were actually trying to publish appium :-)
