### ISSUE TITLE
Android getPageSource() returns unformatted source code

### ISSUE THREAD

**Issue by VolhaMartynovich** [appium/appium#7675]
## The problem

driver.getPageSource() returns markup as one string which is unreadable (for comparison, calling such a method for iOS application returns well formatted markup).

## Environment

* Appium version for Android: 1.5.3 
* Android platform/version under test: 5.1
* Real device or emulator/simulator: emulator

**Comment by mykola-mokhnach** [comment]
Please provide the string you get from driver.getPageSource() call and Appium log.

**Comment by dpgraham** [comment]
This is proxied through uiautomator2

https://github.com/appium/appium-uiautomator2-driver/blob/f34d3c8961b56d92062092dd666014e1f5539d01/lib/commands/general.js

If you want the XML to be readable you can format it in your Java code

http://stackoverflow.com/questions/139076/how-to-pretty-print-xml-from-java
