### ISSUE TITLE
Unable to find WEBVIEW in an hybrid app possibly due to ios-webkit-debug-proxy

### ISSUE THREAD

**Issue by sp5594** [appium/appium#7676]
Hey guys,
I`m trying to find WEBVIEW in an hybrid app but all I`m getting back is NATIVE_APP. Here`s my setup:
- xcode 10.2
- ios 10.1
- appium 1.6.3

'TestCase: 
@Before
    public void setup() {

        try {

            DesiredCapabilities capabilities = new DesiredCapabilities();
            capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.6.3");
            capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
            capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
            capabilities.setCapability(MobileCapabilityType.UDID, "456af3fa1a0b67bc8f587ef5de70474dd8fc132");
            capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
            capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.1");
            capabilities.setCapability("bundleId", "com.example");
       //     capabilities.setCapability(MobileCapabilityType.APP_ACTIVITY, "com.example.MainActivity");
          capabilities.setCapability("autoWebview", "true");

            driver = new IOSDriver<WebElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);

        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

    }`

`[debug] [MJSONWP] Calling AppiumDriver.getContexts() with args: ["3e48975f-b789-45ca-b529-06475ed400b5"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
[debug] [MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP"]`

**Comment by pavanbachu0604** [comment]
Please check if you web inspector is turned ON in ur device

**Comment by sp5594** [comment]
web inspector is turned on

**Comment by dpgraham** [comment]
1. Have you installed `ios-webkit-debug-proxy`?

http://appium.io/slate/en/1.6/?ruby#ios-webkit-debug-proxy

2. If yes, what happens when you navigate to http://localhost:27753/json ?

**Comment by sp5594** [comment]
sorry I forgot to update this topic. I didn`t have ios-webkit-debug-proxy installed. It worked after installing it.

**Comment by KBhatti** [comment]
@dpgraham @sp5594 I have a native app which clicks on a certain element which leads to a webview page being loaded (not in Safari but within the app itself). I am trying to switch to webview to test it but it is not working. I printed out the context on console so it alteast prints out the webview context name, but just doesn't recognize it.

Also when I type ios_webkit_debug_proxy on the terminal I get this:
Invalid message _rpc_reportConnectedDriverList: <dict>
	<key>WIRDriverDictionaryKey</key>
	<dict>
	</dict>
</dict>
Disconnected :9222 from SIMULATOR (SIMULATOR)
please advise

**Comment by dpgraham** [comment]
@KBhatti have you tried uninstalling and reinstalling ios_webkit_debug_proxy?

**Comment by imurchie** [comment]
@KBhatti What command are you using to start `ios_webkit_debug_proxy`? It should not be connecting to a simulator if used correctly. Appium also expects it on a particular port.

**Comment by KBhatti** [comment]
I'm just typing "ios_webkit_debug_proxy" and then hitting enter. Am I missing something?

**Comment by imurchie** [comment]
Yes. You'll want to restrict it to your device, and to the port that Appium expects (unless you specify the port in your Appium command).

See https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/ios-webkit-debug-proxy.md#running-ios-webkit-debug-proxy

**Comment by KBhatti** [comment]
@imurchie the link you pasted is for real device, does that apply to both simulator and real device? I will try that on a real device.
From that link I understand we have to run that patch of 'make' commands, and then ios_webkit_debug_proxy command (-c 0e4b2f612b65e98c1d07d22ee08678130d345429:27753 -d). So that would work for real device...but I does simulator has UDID?

**Comment by DrMabuse23** [comment]
Hi thx for this issue / readme here 
my solutions: 
install porxy

start => 
```
ios_webkit_debug_proxy
Listing devices on :9221
Connected :9222 to m-Way (2607f2690b7629b030102d9c990adedaf5f4e4ef)
```
appium : 
````
appium --webkit-debug-proxy-port 9222
````

**Comment by masoodmd0786** [comment]
Hi @KBhatti @imurchie  I am facing similar issue on Real Device

"I am trying to switch to webview(not in Safari but within the app itself) to test but it is not working. I printed out the context on console so it alteast prints out the webview context name, but it doesn't recognize web view, it is only returning NATIVEVIEW" 

Tried Manual proxy
1. launch iOS-webKit-proxy: **ios_webkit_debug_proxy -c myDeviceUDID:27753 -d**
2. In App Navigate to the webContent page (it opens within the App not in safari)
3. Open url http://localhost:27753/json 
4. Empty response - {}

Do we have any solution ? If yes please help

Created support ticket for more details https://discuss.appium.io/t/unable-to-find-webview-in-ios-hybrid-app-xcode9-appium1-7-1/19046

**Comment by imurchie** [comment]
@masoodmd0786 What sort of Web View is it?

**Comment by DewanshuAwasthi** [comment]
@masoodmd0786 Hi are you able to solve the issue. i am facing the issue on real device.

**Comment by DewanshuAwasthi** [comment]
Hi 
Can anyone help me here ?

**Comment by masoodmd0786** [comment]
@DewanshuAwasthi I am unable to resolve the issue

@imurchie webView(safari) which opens within the App

**Comment by skansar** [comment]
Hello @masoodmd0786/ @imurchie  / @jlipps  ,  I am facing the similar issue with Appium v1.7.2 and Java_client 4.1.2, IOS 10.3(iphone 7s),  mac OS Sierra, XCODE 9.2, ios_webkit_debug_proxy 1.8
Built with libimobiledevice v1.2.1, libplist v2.0.0 and safari 11.2.

WebViews are not recognized / shown with appium desktop as well through java client.

**appium server**
appium --webkit-debug-proxy-port 9222  (tried with OR 27753)
[Appium] Welcome to Appium v1.7.2
[Appium] Non-default server args:
[Appium]   webkitDebugProxyPort: 9222 (OR 27753)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723

**wda**
ios_webkit_debug_proxy
Listing devices on :9221 (OR 27753)
Connected :9222 to iPhone (470ab1f19c630548f76ed0b2f8a4a31614b2c847)

**capabilities:**
[Appium] Creating new XCUITestDriver (v2.64.0) session
[Appium] Capabilities:
[Appium]   app: com.amazon.AmazonUK.Enterprise
[Appium]   newCommandTimeout: 380
[Appium]   platformVersion: 10.3
[Appium]   xcodeOrgId: 94KV3E626L
[Appium]   automationName: XCUITest
[Appium]   autoWebview: false
[Appium]   platformName: iOS
[Appium]   udid: 470ab1f19c630548f76ed0b2f8a4a31614b2c847
[Appium]   deviceName: IOSDevice
[Appium]   xcodeSigningId: iPhone Developer

**appium Log:**
[debug] [MJSONWP] Calling AppiumDriver.getContexts() with args: ["e5be6ced-f4ac-4e21-8618-d97e1d9991c2"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[debug] [RemoteDebugger] Page element JSON: []
[debug] [iOS] No web frames found.
[debug] [MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP"]

Any help appreciated.  Thank You.
