### ISSUE TITLE
Appium inspector says an iOS element is visible whereas it is not on my screen (xcuitest)

### ISSUE THREAD

**Issue by jeangb** [appium/appium#7679]
## The problem

Hello,
On the login page of my application, there is a button "cancel" which is only displayed after user submitted the login form. 
The problem is appium inspector see it all the time, even when not displayed, and his attributes visible, enabled are always true.
So during my test, if I want to check that this kind of element isn't displayed I can't because this one is never saw as not displayed.
I tried many ways, such as ExpectedConditions.elementToBeClickable.
Is there a way to detect if this element is really hidden ?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Automation framework used: Xcuitest
* Desktop OS/version used to run Appium: Mac OS 10.11.6
* Node.js version (unless using Appium.app|exe): v7.2.1
* Mobile platform/version under test: iOS 9.3.5
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: CLI

**Comment by slipy12** [comment]
Is it possible that you are using xcuitest driver? I think it shows everything loaded in the phone's memory :( (not sure if it's that, but seems the behaviour in my same situation)

**Comment by jeangb** [comment]
@slipy12 Yes I use xcuitest, I forgot to mention that (I'm going to edit my issue). 
Oh it seems problematic...

**Comment by mykola-mokhnach** [comment]
This may depend on the actual application code, since it has full control over accessibility and can also change visibility attribute.

**Comment by mykola-mokhnach** [comment]
Check this for example http://stackoverflow.com/questions/25259822/showing-hiding-accessibility-elements-in-an-overflow-menu-when-opening-a-custo

**Comment by jeangb** [comment]
You mention accessibility element, is it related with the accessibility from accessibility id and accessibility label ?

**Comment by kcinman11358** [comment]
I had something similar, where multiple pop ups with "OK" button were being found, but they were in the background. Here's my solution:
                WebDriverWait wait = new WebDriverWait(_driver, new TimeSpan(0, 0, 20));
                wait.Until(ExpectedConditions.ElementIsVisible(By.Name("OK")));
                var i = _driver.FindElements(By.Name("OK")).Count;
                _driver.FindElements(By.Name("OK")).ElementAt(i-1).Click();

**Comment by jeangb** [comment]
Hi @kcinman11358 your solution is interesting but only in a case where these multiple buttons have the same accessibilityId/xpath. Thank you anyway !
