### ISSUE TITLE
Appium Not scrolling to the end of the list

### ISSUE THREAD

**Issue by iceKirthi** [appium/appium#7680]
## The problem

In previous appium version, If I want to select an element that is present at the end of the list (which is not visible inside the screen and need to scroll down), appium automatically scrolled down and selected that particular element. Now it is not scrolling down and it is selecting some other element present inside the screen view. Do anyone have fix for this?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue : 1.4.13
* Mobile platform/version under test: iPad and iPhone iOS 9.x/10.x
* Real device or emulator/simulator: Real Device

**Comment by pavanbachu0604** [comment]
Can you share the reproducible code ?

**Comment by steffencrespo** [comment]
What is the element location strategy you are using?

**Comment by iceKirthi** [comment]
No. Actually, I am not scrolling down by code. 

**For Example, consider the scenario :**
 I am having a list of 15 elements in a table view. And only 10 elements can be viewed at once and need to scroll down to view the remaining 5 elements.

In previous Appium versions, I just used **list.get(14).click()** function and appium automatically scrolled down and selected that element.

In latest Appium version, when I used the same code **list.get(14).click()**, appium selects first element in the list and it is not selecting the last element.

**Comment by Akulavenkatesh** [comment]
+1 facing the same issue on Appium 1.6.3 (I use Appium Python client)

**Comment by iceKirthi** [comment]
@jlipps , @imurchie  - Could you pls help on this ?

**Comment by jlipps** [comment]
A lot of things have changed in Appium 1.6 including this behavior. Please see https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md
