### ISSUE TITLE
Can we run multiple IOS devices(parallel) using Appium on single MAC machine?

### ISSUE THREAD

**Issue by swachhab** [appium/appium#7683]
## The problem

I am using Appium 1.6.3 for automating IOS 10 devices, But don't know how to do parallel execution. Please help if anybody executed parallel execution of IOS devices using Appium?

**Comment by saikrishna321** [comment]
@swachhab can you pls post questions on discuss.appium.io, there are many threads pointing to parallel execution

@jlipps @SrinivasanTarget can we close this ?
