### ISSUE TITLE
cannot start Appium inspector and errors

### ISSUE THREAD

**Issue by jeffradom** [appium/appium#7684]
## The problem

I see the the error after launching Appium inspector and it doesn't start

[MJSONWP] Encountered internal error running command: Error: Xcode version [object Object] is not yet supported
    at handleUnsupportedXcode (lib/simulator.js:15:11)
    at getDeviceString$ (lib/simulator.js:44:3)
    at tryCatch (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applic

When run Doctor I get those errors

Last login: Wed Jan 11 16:55:26 on ttys000
Jeffs-Air:~ jeffradom$ '/Applications/Appium.app/Contents/Resources/node/bin/node' '/Applications/Appium.app/Contents/Resources/node_modules/appium-doctor/appium-doctor.js'
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
[Error: Could not detect Mac OS X Version from sw_vers output: '10.12.2
']

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe): Appium.app
* Mobile platform/version under test: IOS 7 IOS Version 9.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details
I can run Python code like below with no problem

desired_caps = dict(
    platformName='iOS',
    deviceName='iPhone 7',
    automationName='XCUITest',
    platformVersion='10.0',
    # The original app from Appium github project.
    app='https://store.applitools.com/download/iOS.TestApp.app.zip')

#wd = webdriver.Remote('http://127.0.0.1:4723/wd/hub', desired_caps)
wd = webdriver.Remote('http://0.0.0.0:4723/wd/hub', desired_caps) 

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
https://medium.com/@chenchaoyi/the-options-of-inspecting-ios-10-app-with-appium-1-6-534ba166b958#.3ygytpg9a

**Comment by mykola-mokhnach** [comment]
In general, the old standalone Appium inspector application is not supported anymore. The Appium team is currently working on a new [cross-platform implementation](https://github.com/appium/appium-desktop), but it's still in progress.

**Comment by jeffradom** [comment]
mykola-mokhnach.  I've tried Option 1 from your suggestion but still cannot start Appium Inspector
I this this popup
Could not start a new session

Be sure the Appium server is running with an application opened by using the "App Path" parameter in Appium.app (along with package and activity for Android) or by connecting with selenium client and supplying this in the desired capabilities object.

**Comment by mykola-mokhnach** [comment]
Please try other options then

Closing the issue as irrelevant.
