### ISSUE TITLE
Appium loads the app but fails on WebDriver on AppleTV (4th Gen) tvOS 10.2

### ISSUE THREAD

**Issue by SteveKSB** [appium/appium#7688]
## The problem

Using open source "Auntie Player" and Appium v1.6, trying to load and bring up inspector fails after the app installs successfully on real AppleTV device.
## Environment

* Appium version (or git revision) that exhibits the issue: v1.6
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: MacOS Sierra
* Node.js version (unless using Appium.app|exe): using Appium app with external Appium package 1.6
* Mobile platform/version under test: AppleTV 4th Gen
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: Appium app

## Details

The Appium app installs the Auntie Player app to the real appleTV device.  Appium connects via XCuiTestDriver since the ios version is 10.1 when the inspector tries to come up. The log indicates the app exits with code '780 and signal 'null'. Log indicates UnhandledPromiseRejectionWarning. 
## Link to Appium logs

https://gist.github.com/SteveKSB/61f013067237ee2b5b0c56174f0ca4c6

## Code To Reproduce Issue [ Good To Have ]. Just trying to bring up the inspector causes this.

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
IF you update to the latest (either the release, 1.6.3, or with `--no-shrinkwrap` the UnhandledPromiseRejectionWarning ought to go away.

But the larger problem is that Appium has not been tested with AppleTV, so if it works, yay! But if it does not, there is not a lot that we can do at this moment. If you wanted to jump in and try to figure it out, that would be amazing and we would be very appreciative. We can help out in whatever way is possible.

**Comment by SteveKSB** [comment]
Hi Isaac,


I updated to 1.6.3 as suggested and as you indicated, the warning goes away but it still fails. I did run the xcodebuild line that fails at and it appears the problem is that the list of devices that is returned to appium only includes all IOS devices except AppleTV. The xcode 8.2.1 tool supports it as it's listed under the Device menu in Xcode. Here's the copy of the command I ran manually.


xcodebuild build test -project /usr/local/Cellar/node/7.1.0/libexec/npm/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=b4c3a49c3c99b9df6036a573e9cc01bde42f0479 -configuration Debug

xcodebuild: error: Unable to find a destination matching the provided destination specifier:

{ id:b4c3a49c3c99b9df6036a573e9cc01bde42f0479 }


Available destinations for the "WebDriverAgentRunner" scheme:

{ platform:iOS Simulator, id:4026E8B1-2D62-49B9-B54D-9F40439DB01E, OS:9.3, name:iPad 2 }

{ platform:iOS Simulator, id:E99102F0-4D19-48E3-80C1-52B9E35ED7EA, OS:9.3, name:iPad Air }

{ platform:iOS Simulator, id:0585B148-ACE4-4823-A78E-C0CDBFAEA4D3, OS:10.2, name:iPad Air }

{ platform:iOS Simulator, id:6853D1B4-0093-42CD-86A1-90C89E54B9CF, OS:9.3, name:iPad Air 2 }

{ platform:iOS Simulator, id:3C9B0293-1343-479E-BB51-91E0DFABD43E, OS:10.2, name:iPad Air 2 }

{ platform:iOS Simulator, id:4E96FC26-43F2-45B1-9D12-0D4EB453FE40, OS:9.3, name:iPad Pro }

{ platform:iOS Simulator, id:9C8A33A9-4300-4F17-9F87-A17B76A6E2AA, OS:10.2, name:iPad Pro (9.7 inch) }

{ platform:iOS Simulator, id:55004C5A-C6C1-49DA-ABDF-CDA5C5BCDFD0, OS:10.2, name:iPad Pro (12.9 inch) }

{ platform:iOS Simulator, id:FB6E570B-A2CB-4DA5-B8F5-2979BFB247DC, OS:9.3, name:iPad Retina }

{ platform:iOS Simulator, id:CF2AB975-CF60-4B5E-95D2-4B7C8DB933ED, OS:10.2, name:iPad Retina }

{ platform:iOS Simulator, id:53B0B352-EC1B-45A0-88F4-91CF206A47FE, OS:9.3, name:iPhone 4s }

{ platform:iOS Simulator, id:FB4FB459-6E91-4236-A489-75F4DD879A65, OS:9.3, name:iPhone 5 }

{ platform:iOS Simulator, id:3B10DA25-A835-4884-B8B7-07B4C20D704E, OS:10.2, name:iPhone 5 }

{ platform:iOS Simulator, id:04CBEBDA-DE78-4866-917F-A9443134DBA9, OS:9.3, name:iPhone 5s }

{ platform:iOS Simulator, id:C770A49A-BCBD-4C1C-B2F7-BFADA3EB47B2, OS:10.2, name:iPhone 5s }

{ platform:iOS Simulator, id:BAAC1E9E-0B3D-4B83-8568-389A326FF056, OS:9.3, name:iPhone 6 }

{ platform:iOS Simulator, id:15BBA4FF-C98A-4B38-8403-12DB123A1606, OS:10.2, name:iPhone 6 }

{ platform:iOS Simulator, id:95B320B6-7783-47A4-A1C5-5FF26B2291E5, OS:9.3, name:iPhone 6 Plus }

{ platform:iOS Simulator, id:8562C382-9934-4EC7-954F-929AFFD09EAC, OS:10.2, name:iPhone 6 Plus }

{ platform:iOS Simulator, id:9FBDFB13-1C9A-4A48-9774-889CCF8EC5CA, OS:9.3, name:iPhone 6s }

{ platform:iOS Simulator, id:EA9217FA-76C9-4468-A3D6-C37776CD2D20, OS:10.2, name:iPhone 6s }

{ platform:iOS Simulator, id:01098E56-D78F-4953-87FB-C7D37F1FF438, OS:9.3, name:iPhone 6s Plus }

{ platform:iOS Simulator, id:8566602F-7106-4D63-AA80-38C1C57B244B, OS:10.2, name:iPhone 6s Plus }

{ platform:iOS Simulator, id:3590905A-1C23-4669-A31C-CFC6703D1AFB, OS:10.2, name:iPhone 7 }

{ platform:iOS Simulator, id:6EA400A0-4D17-47FD-96BE-ED5027D67F61, OS:10.2, name:iPhone 7 Plus }

{ platform:iOS Simulator, id:E11A9E9D-D51D-4D0E-9218-BE31F9D7FD0A, OS:10.2, name:iPhone SE }


Ineligible destinations for the "WebDriverAgentRunner" scheme:

{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }

{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }


________________________________

**Comment by SteveKSB** [comment]
Hi Issac,

AppleTV support is critical for us. What else can we do to fix this problem? I tried using a simple Python appium test using XCUItest and it ends with same failure as what I already submitted. Thanks!

**Comment by dpgraham** [comment]
@SteveKSB, appium-xcuitest-driver depends on Facebook's WebDriverAgent, which does not support  tvOS (see https://github.com/facebook/WebDriverAgent/issues/195).

In the meantime, your only options will be to either write the XCUI tests in Objective-C or Swift, or to submit a pull request in WebDriverAgent to add tvOS support.

**Comment by TamimiGitHub** [comment]
Hey all, I would like to know is there any updates on the AppletV support? If there are changes needed to be done on the web driver side where would the starting point be? I would be interested to contribute for any changes if required :) AppleTV is very close to be supported with Appium and up until now I havent had any successful implementation with AppleTV and Appium

**Comment by imurchie** [comment]
No work has been done on this, and it is not currently in our timeline to do any.

**Comment by monsam** [comment]
Any update on Apple TV?

**Comment by dpgraham** [comment]
The core Appium team won't have time in the near future to work on supporting Apple TV. We would need a member of the community to work on it.

**Comment by monsam** [comment]
Anyone has any luck on Apple TV yet?
