### ISSUE TITLE
Appium : [Error: Could not detect Mac OS X Version from sw_vers output: '10.12.2 ']

### ISSUE THREAD

**Issue by sudheertreddy** [appium/appium#7689]
Hello,
I am new to Appium. I am using 1.5.3 on my mac. I am getting below error. Can someone please help. 
[Error: Could not detect Mac OS X Version from sw_vers output: '10.12.2
']

tried the solution from here. It didnt help http://stackoverflow.com/questions/40129794/how-to-fix-error-could-not-detect-mac-os-x-version-from-sw-vers-output-10-12/40168992#40168992

**Comment by mykola-mokhnach** [comment]
Please update Appium to version 1.6+
1.5.X is not supported anymore
