### ISSUE TITLE
Appium errors locating by xpath Error copying attributes -25202

### ISSUE THREAD

**Issue by jmolliver** [appium/appium#7691]
Using Appium 1.6.3 for iOS, locating elements by Xpath often throw this error and will eventually locate it and move on. Using Xcode 8.1.

Error copying attributes -25202

[debug] [WebDriverAgent] Sim: Jan 10 14:04:54 jmolliver-ltm XCTRunner[10506]: Enqueue Failure: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x81e79430> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1

**Comment by mykola-mokhnach** [comment]
Known XCTest/WDA issue: https://github.com/facebook/WebDriverAgent/issues/372
