### ISSUE TITLE
"Continue" button does not get clicked with iOS-9+ version.

### ISSUE THREAD

**Issue by atiqul2007** [appium/appium#7692]
**## The Problem:**
"Continue" button does not get clicked with iOS-9+ version. But this is not an issue with iOS-8.3

**Acceptance Criteria:** 
1. By tapping Continue button, user should be able to open device camera to capture and save image
2. By tapping Continue button, user should be able to get into Signing Room to capture signature and save them for documents.

**## Environment:**
- Appium version: 1.5.3
- Robotframework: 3.0 
- Mobile platform: iPad2 iOS-9.2.1
- Real device:  Real Device
- Robotframework-Appiumlibrary: 1.4.0.1
- Python: 2.7 

**## Details:**
Our native app named DRSA2.0, is a digital contracting app for automotive market. In our app there are some gates user needs to enter - like 1. opening device camera to capture & save images and 2.Signing Room to sign documents. User requires to tap on Continue button to get into these.

I use Appium server with Robotframework and xpath to indentify elements. My device version is iOS-9.2.1. Everything works fine but Continue buttons do not get clicked though result shows that Continue button clicked.
But when I try to run same script on iOS-8.3, I get no issue to get Continue button visually clicked.  

**Test report:** 
[gistfile1.txt](https://github.com/appium/appium/files/704713/gistfile1.txt)
https://gist.github.com/atiqul2007/aaa8e7f86a54f9205bd7dbad7912fe0d

**Comment by mykola-mokhnach** [comment]
What if you tap by coordinates instead of invoking click method?

**Comment by atiqul2007** [comment]
Do you mean using Location attribute? I tried below xcode with Keyword " Click Element At Coordinates" but it did not work. Can you elaborate if you meant otherwise?

1. xpath=//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAWebView[1]/UIAButton[@location='{312, -73}']
2.  xpath=//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAWebView[1]/UIAButton[contains(@location,'{312}') and contains(@location,'{-73}')]

**Comment by mykola-mokhnach** [comment]
No I mean using driver.tap method call, which taps by absolute screen coordinates.
BTW, You have to think about updating class names. UIA* locators are obsolete for XCTest-based Appium.

**Comment by atiqul2007** [comment]
I have so far built script based on UIA locator. not an expert yet in it.
Can you pls make an example script for me so i can update my script accordingly and try?

**Comment by dpgraham** [comment]
For XCTest, the locators are backwards compatible with UIA so that shouldn't be an issue.

@atiqul2007 Can you provide a code snippet that shows how you're clicking the 'Continue' button?

**Comment by atiqul2007** [comment]
@dpgraham , i tried in below different ways:

1. click element       xpath=//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAWebView[1]/UIAButton[@name='Continue']

2.
Click Element At Coordinates           xpath=//UIAApplication[1]/UIAWindow[1]/UIAScrollView[1]/UIAWebView[1]/UIAButton[contains(@location,'{312}') and contains(@location,'{-73}')]

Note: in my script i put variables for xpath.

**Comment by jlipps** [comment]
@atiqul does the page source support the xpath query you are trying to make?

**Comment by atiqul2007** [comment]
@jlipps , yes it does. I use xpath to invoke other button of the same page.

**Comment by mykola-mokhnach** [comment]
Guys don't overcomplicate things. The task is simple and the solution might be even simpler. I usually don't write source code, to let people figure it out themselves, but since it's already getting to far...
How to click element by coordinate:

```java
WebElement el = driver.findElement(MobileBy.AccessiblityId("Continue"));
Dimensions dim = el.getSize();
Location loc = el.getLocation();
driver.tap(loc.x + dim.width / 2, loc.y + dim.height / 2, 1000);
``` 

Using xpath is not recommended. It's slow with XCTest:
![hct37](https://cloud.githubusercontent.com/assets/7767781/22028242/e2c9f062-dcd6-11e6-9c1c-27851dc27458.png)

**Comment by mykola-mokhnach** [comment]
Also, this might be known issue if you try do the click in landscape mode. Check https://github.com/facebook/WebDriverAgent/pull/411 for more details
