### ISSUE TITLE
Original error: Removing com.abc.xyz failed

### ISSUE THREAD

**Issue by Manikanta29** [appium/appium#7697]
I am new to IOS Automation.  Able to open the .app in Simulator. But, difficult to open the .app on real devices.
Xcode: 7.3.1
Iphone: 5s
IOS: 10.0.2
Appium :1.5.3

DesiredCapabilities: 

DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone");
		cap.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.0.2");
		cap.setCapability(MobileCapabilityType.UDID, "XXXxXXXXXXXXXXX");
		//cap.setCapability(MobileCapabilityType.APP, "/Users/mani/Documents/AppFile/xyz.app");
		driver = new IOSDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), cap);

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --address "127.0.0.1" --debug-log-spacing --robot-address "127.0.0.1" --robot-port "4723" --platform-version "8.1" --platform-name "iOS" --app "/Users/mani/Documents/AppFile/xyz.app" --full-reset --show-ios-log --default-device

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:

[Appium]   address: '127.0.0.1'

[Appium]   defaultDevice: true
[Appium]   robotAddress: '127.0.0.1'
[Appium]   robotPort: 4723
[Appium]   debugLogSpacing: true

[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '8.1'
[Appium]   app: '/Users/mani/Documents/AppFile/xyz.app'
[Appium]   fullReset: true
[Appium]   showIOSLog: true
[Appium] Deprecated server args:
[Appium]   --platform-name => --default-capabilities '{"platformName":"iOS"}'
[Appium]   --platform-version => --default-capabilities '{"platformVersion":"8.1"}'
[Appium]   --app => --default-capabilities '{"app":"/Users/mani/Documents/AppFile/xyz.app"}'

[Appium]   --full-reset => --default-capabilities '{"fullReset":true}'
[Appium]   --show-ios-log => --default-capabilities '{"showIOSLog":true}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

[Appium]   platformName: 'iOS'

[Appium]   platformVersion: '8.1'
[Appium]   app: '/Users/mani/Documents/AppFile/xyz.app'
[Appium]   fullReset: true

[Appium]   showIOSLog: true

[Appium] Appium REST http interface listener started on 127.0.0.1:4723

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 24 ms - 83 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"udid":"XXXXXXXXXXXXXXXXXXXXXX","platformName":"iOS","deviceName":"iPhone","platformVersion":"10.0.2"}}

[MJSONWP] Calling AppiumDriver.createSession() with args: [{"udid":"XXXXXXXXXXXXXXXX...

[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium]   udid: 'XXXXXXXXXXXXXXXXXX'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone'
[Appium]   platformVersion: '10.0.2'
[Appium]   app: '/Users/mani/Documents/AppFile/xyz.app'
[Appium]   fullReset: true
[Appium]   showIOSLog: true

[BaseDriver] Session created with session id: aac63a43-97ac-462e-ae4e-54d31b582f68

[debug] [iOS] Not auto-detecting udid.

[BaseDriver] Using local app '/Users/mani/Documents/AppFile/xyz.app'

[debug] [iOS] Removing any remaining instruments sockets

[debug] [iOS] Cleaned up instruments socket /var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/instruments_sock
[debug] [iOS] No language specified. Using default strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!

[debug] [ios-app-utils] Getting bundle ID from app

[iOS] Extracted bundleID: com.abc.xyz from app: /Users/mani/Documents/AppFile/xyz.app
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/man/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

[debug] [UIAuto] Dynamic bootstrap path: /Users/mani/Library/Application Support/appium/bootstrap/bootstrap-e70ca8c7f7b8bd1e.js

[debug] [UIAuto] Reusing dynamic bootstrap: /Users/man/Library/Application Support/appium/bootstrap/bootstrap-e70ca8c7f7b8bd1e.js

[debug] [iOS] Running ios real device reset flow
[debug] [iOS] Full reset requested. Will try to uninstall the app 'com.abc.xyz'.
[debug] [iOS] Creating iDevice object with udid XXXXXXXXXXXXXXXXXX

[iOS] Could not remove 'com.abc.xyz' from device

[MJSONWP] Encountered internal error running command: Error: Removing com.abc.xyz failed
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/node-idevice/main.js:145:6
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

[HTTP] <-- POST /wd/hub/session 500 767 ms - 172 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...

[HTTP] <-- GET /wd/hub/status 200 16 ms - 83

**Comment by mykola-mokhnach** [comment]
Appium 1.5.3 is incompatible with iOS 10.0+
Please update to 1.6.3

**Comment by Manikanta29** [comment]
Thanks for your comments.  I have downloaded the latest appium 1.6.3 from https://github.com/appium/appium/releases.  But in zip, unable to find the .dmg file.  Could you please guide me, how to install 1.6.3

**Comment by mykola-mokhnach** [comment]
Appium 1.6+ is not available as dmg package and can only be installed with npm utility as a normal NodeJS module.
Please use Appium forum for howto question.
