### ISSUE TITLE
UNKNOWN SERVER-SIDE ERROR when performing gestures (move-actions single and multi)

### ISSUE THREAD

**Issue by ngavrish** [appium/appium#7699]
## The problem

I'am trying to emulate something like swipe with 3+ fingers from top to the bottom. And I got Unknown server-side Error.

Same error I get when I perform touchAction 'move' from 1 element to another

```python
TouchAction(pytest.driver).tap(ride_).wait(1000).move_to(lower_).wait(1000).perform()

ride_ = pytest.page.wait_for_element(By.XPATH, '//*[@text="Ride"]')
lower_ = pytest.page.wait_for_element(By.XPATH, '//*[@text="Lower"]')
```

## Environment

Python 3.6, 3.5
Appium 1.6.3 from git
Android 5.1.1
Real device

## Details

I need to perform multitouch gesture. While multitouch without gesture works fine, when I start doing move actions - it fails with 

UNKNOWN SERVER-SIDE ERROR

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/appium/webdriver/common/multi_action.py:64: in perform
    self._driver.execute(Command.MULTI_ACTION, self.json_wire_gestures)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:236: in execute
    self.error_handler.check_response(response)
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/appium/webdriver/errorhandler.py:29: in check_response
    raise wde
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/appium/webdriver/errorhandler.py:24: in check_response
    super(MobileErrorHandler, self).check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <appium.webdriver.errorhandler.MobileErrorHandler object at 0x1042766d8>
response = {'status': 500, 'value': '{"status":13,"value":{"message":"An unknown server-side error occurred while processing the command."},"sessionId":"1800a692-c9c3-404c-ac67-8f036bc7d37e"}'}

## Link to Appium logs

https://gist.github.com/ngavrish/ba9d6cba51b393589b39918e6c0c5efb#file-gistfile1-txt

## Code To Reproduce Issue [ Good To Have ]

def test_gearshift_with_miltitouch_and_move():
    # pass

    el = pytest.driver.find_element_by_android_uiautomator('new UiSelector().text("Raise")')
    fingers = [TouchAction(pytest.driver).press(el),
               TouchAction(pytest.driver).press(el),
               TouchAction(pytest.driver).press(el),
               TouchAction(pytest.driver).press(el)]
    multitouch = MultiAction(pytest.driver)
    multitouch.add(fingers[0])
    multitouch.add(fingers[1])
    multitouch.add(fingers[2])
    multitouch.add(fingers[3])
    multitouch.perform()
    gearbox = pytest.driver.find_element_by_xpath("//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/org.charge.sdk.widget.ViewPagerCustom5[1]/android.widget.RelativeLayout[1]/android.widget.RelativeLayout[1]")
    move_fingers = [TouchAction(pytest.driver).tap(gearbox, 800, 800).wait(2000).move_to(gearbox, 0, 0).wait(2000),
                    TouchAction(pytest.driver).tap(gearbox, 800, 800).wait(2000).move_to(gearbox, 0, 0).wait(2000),
                    TouchAction(pytest.driver).tap(gearbox, 800, 800).wait(2000).move_to(gearbox, 0, 0).wait(2000),
                    TouchAction(pytest.driver).tap(gearbox, 800, 800).wait(2000).move_to(gearbox, 0, 0).wait(2000)]
    multitouch.add(move_fingers[0])
    multitouch.add(move_fingers[1])
    multitouch.add(move_fingers[2])
    multitouch.add(move_fingers[3])
    multitouch.perform()

**Comment by dpgraham** [comment]
Hi @ngavrish,

Can you try replacing your calls to .tap with .press?

**Comment by ngavrish** [comment]
Its not .tap or .press problem. It fails when it comes to .move_to. 

If I don't do .move_to in multitouch event - it works fine. It does multitouch. And it does single touch. What it doesn't do - is move_to. 

I tested it on level of rest api - I did POST request with move actions and was able to reproduce the failure.

That means I am pretty sure the problem is in Appium server. Not in my code.

**Comment by dpgraham** [comment]
A tap event is a shorthand way of doing a press and release in quick succession. I wouldn't expect move_to to work after a tap event because the touch action has already been released.

**Comment by ngavrish** [comment]
So press and move_to works for you?

**Comment by dpgraham** [comment]
You may need to also do a .release
