### ISSUE TITLE
getPageSource getting only elements for primary application for split screen in iOS 10 devices

### ISSUE THREAD

**Issue by dilsreccse** [appium/appium#7700]
## The problem
i'm having 2 applications on my iPad screen, driver.getPageSource() getting the only the primary application elements, whereas i have my application to be automated as secondary.In early version of appium , it has a control over it & so i was able to inspect the elements for it using Appium inspector. is there any workaround possible to grab elements for the application when it is opened as secondary app?

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Last Appium version that did not exhibit the issue (if applicable):1.5.3
* Desktop OS/version used to run Appium:Mac
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPad Pro
* Real device or emulator/simulator:Real
* Appium CLI or Appium.app|exe:Apppium CLI

**Comment by mykola-mokhnach** [comment]
Appium shows what WDA is returning to it. Think about adding this issue to WDA: https://github.com/facebook/WebDriverAgent/pulls

Also, it would be good to have more detailed description with screenshots, examples, the actual and expect result, because the current one is hard to understand.

**Comment by jlipps** [comment]
Unfortunately this is something that would be needed to be added to WebDriverAgent, as @mykola-mokhnach suggests.

**Comment by umaralikhan** [comment]
Does latest Appium support split view mode or picture in picture?
