### ISSUE TITLE
remote debugger socket timeout needs increasing

### ISSUE THREAD

**Issue by h3dkandi** [appium/appium#7701]
## The problem

WebKit Remote debugger socket disconnects for no apparent reason.
## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.3 (REV ea239916f56cc63c13ebf527fc116a606f102792)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.12.2
* Node.js version (unless using Appium.app|exe): 7.2.1
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

This happens when I try to navigate to the website that I use for testing.
It has a 50% chance to happen on an iPhone 6 and have never seen it on the iPad mini I use for testing (both iOS 10.2). I don't have the ios_webkit_debug_proxy log but I could possibly pipe the process to a txt which might be a good think to do for the future :)

## Link to Appium logs

[Appium log](https://gist.github.com/h3dkandi/0637d0691cf7ad66ca0259f413faab65)

**Comment by dpgraham** [comment]
@imurchie @jlipps Can one of you two have a look at this? Lines 130-133 are of interest

```
2017-01-16 09:03:21:569 - info: [debug] [RemoteDebugger] Checking document readyState
2017-01-16 09:03:21:570 - info: [debug] [RemoteDebugger] Sending javascript command (function (){ return document.readyState; })()
2017-01-16 09:03:21:570 - info: [debug] [RemoteDebugger] Sending WebKit data: {"method":"Runtime.evaluate...
2017-01-16 09:03:21:572 - info: [debug] [RemoteDebugger] WebKit remote debugger socket disconnected
```

The socket appears to be disconnected for no reason, and without the WebKitRpcClient.disconnect method being called.

**Comment by jlipps** [comment]
@dpgraham it looks like the original error is this one:

```
2017-01-16 09:03:26:573 - error: [MJSONWP] Encountered internal error running command: TimeoutError: operation timed out
    at afterTimeout (/Users/<user>/automated_testing/github/appium/node_modules/bluebird/js/main/timers.js:16:15)
    at Timeout.timeoutTimeout [as _onTimeout] (/Users/<user>/automated_testing/github/appium/node_modules/bluebird/js/main/timers.js:59:9)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
2017-01-16 09:03:26:577 - info: [HTTP] <-- POST /wd/hub/session/9dd46239-7553-4a26-bbb8-23759c3975ab/url 500 6525 ms - 190 
```

where setting the URL has failed. I'm not sure what could have happened. I think the IWDP log would be helpful. Also @h3dkandi what do you notice happening on the device when the url is set? Does it actually navigate? Does it crash? Etc...

**Comment by h3dkandi** [comment]
@jlipps Here is the [iwdp log](https://gist.github.com/h3dkandi/0a9e9afe69acf430bb25ed208dab3adb) without --debug option(Do you need it?).
Nothing happens on device. The appium.io page opens and nothing after that.

**Comment by jlipps** [comment]
That log is actually not very helpful, hmm. I'm really not sure what could be happening. Maybe the device is just having trouble connecting to the site and then it times out. If you just manually try and refresh that url on your device hundreds of times, can you ever reproduce the behavior without Appium? Or does @imurchie have any other ideas?

**Comment by imurchie** [comment]
The timeout might be too low. It is, I think, coming from https://github.com/appium/appium-remote-debugger/blob/0a55ab05be05742614f2538bf7896f23f0e8b82f/lib/webkit-rpc-client.js#L102

**Comment by h3dkandi** [comment]
@jlipps I couldn't reproduce the behavior without Appium.

**Comment by jlipps** [comment]
OK, adding this to our backlog to up the timeout, and modifying title to suit

**Comment by mare1012** [comment]
@jlipps @imurchie is there any update on this issue? because I'm facing the same problem. I'm using appium 1.6.5 to test safari on iPhone 6s 10.3.1. 

here is my log file:
https://gist.github.com/mare1012/f351035e7d7b17cf5626a64fa4581c98

**Comment by imurchie** [comment]
There is a capability, `webkitResponseTimeout`, which sets the timeout waiting for webkit to respond on real devices, in milliseconds.

**Comment by mare1012** [comment]
@imuchie i already used that capability. i set it to 35000, but the problem still appears

**Comment by mare1012** [comment]
@imurchie if i set the  `webkitResponseTimeout ` to 180000, it will only wait longer until the test quits. But while waiting is the webkit remote debugger already disconnected, when i monitor the log file

**Comment by mare1012** [comment]
Hallo @imurchie, do you have any update on this issue?

**Comment by mare1012** [comment]
Hallo @h3dkandi , do you have any update on this issue?

**Comment by h3dkandi** [comment]
@mare1012 Well most of my socket disconnects were due to the fact that the Appium machine was connected to the internet trough wi-fi. The mac I was using was defaulting to wi-fi and not Lan and it took me a while to notice that :(. I don't know how helpful is this for you.

**Comment by mare1012** [comment]
@h3dkandi thks for your response. the mac i'm using is actually connecting to LAN not wi-fi. But i still get the same issue. do you still reproduce this issue or you had already resolved it?

**Comment by h3dkandi** [comment]
I do get time outs but I believe they are a different kind of issue. You
probably used brew to install the outside dependencies like "ios web debug
proxy", you could try updating them to use their HEAD versions.

**Comment by mare1012** [comment]
@h3dkandi i did try also to install HEAD versions and to build from source. But it doesn't work. Do you know, if there is an alternativ for ios-webkit-debug-proxy or similiar issue?

**Comment by h3dkandi** [comment]
I don't know. Sorry man can't really help you.

**Comment by jlipps** [comment]
considering this particular issue closed since we added a capability to manage the timeout.
