### ISSUE TITLE
xcodebuild failed with code 65

### ISSUE THREAD

**Issue by h3dkandi** [appium/appium#7705]
## The problem

Web driver doesn't seem to build, codesign failed with exit code 1, xcodebuild failed with code 65

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.3 (REV ea239916f56cc63c13ebf527fc116a606f102792)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.12.2
* Node.js version (unless using Appium.app|exe): 7.2.1
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

Happens for a second time. The other time was three weeks ago and I am not exactly sure if the logs (there are none) or the case was the same, just that it spit "xcodebuild failed with code 65" error. This time I have some logs. 
Don't know why it happens, can't really recreate it. All my tests from last night failed with this error. Is this an Appium thing or an xcode?

## Link to Appium logs

[Appium log](https://gist.github.com/h3dkandi/bb657cdd5122d7ad83226691727958d3)
[WebDriver log 1 URtNrL](https://gist.github.com/h3dkandi/5bf8794b1d2da3311582b102f1cd418c)
[WebDriver log 2 65lnI2](https://gist.github.com/h3dkandi/966048f245cea67c2fb24fd54c8aa7f2)

**Comment by mykola-mokhnach** [comment]
Looks like WDA app cannot start on the target device. Do you see any errors in the device log?

**Comment by pavanbachu0604** [comment]
@h3dkandi  Please mention the steps followed to provision WDA and also share the capabilities

**Comment by h3dkandi** [comment]
Yesterday when I tried to run the test while I was there it worked. This night they failed again with code 65

@mykola-mokhnach  I see no logs in the _xcode>devices>device logs_ for the 18th there are logs for the 17th but I don't think they are relevant. Did you meant that by device log? It seems to me that it is a CodeSign problem. Then again I can't say which comes first:
```
03:14:00.475 xcodebuild[16814:1163027] Test operation failure: Test operation was canceled.
03:14:00.475 xcodebuild[16814:1163027] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled." UserInfo={NSLocalizedDescription=Test operation was canceled.} didCancel: 1
```
or:
```
2017-01-17 01:14:03:583 - info: [Xcode] 
Testing failed:
	Command /usr/bin/codesign failed with exit code 1
** TEST FAILED **

```
Does it fail to codesign because it cancels the test or the other way around?
@pavanbachu0604 Isn't all you are asking in the Appium log that is provided? The WebDriverAgent.xcconfig contains `DEVELOPMENT_TEAM` and `CODE_SIGNING_IDENTITY`

**Comment by h3dkandi** [comment]
Appart from the test failing last night when I try to start them while I am present they do fail again.
I added `security unlock-keychain` and it seems to fix the problem. I do hope this was what was wrong with the setup. Probably sometimes the keychain is unlocked and sometimes not.

**Comment by jlipps** [comment]
Interesting, @h3dkandi. Care to add this tip to our docs? :-)

**Comment by h3dkandi** [comment]
@jlipps I still get the code 65 error. So I don't know if the unlock was actually the fix.

**Comment by jlipps** [comment]
Yeah the code 65 error can arise for a multitude of reasons so there's not going to be one single fix for it probably. If it went away and then came back, I'd take a look at your signing pipeline or certs or something like that.
