### ISSUE TITLE
xCode 8.2.1, iOS 10.12 (Sierra) not working with Appium 1.6.3

### ISSUE THREAD

**Issue by WoodPlank** [appium/appium#7706]
## The problem
I'm getting a notable error when I try to use a physical device with Appium 1.6.3 on my iOS 10.12 Mac.

## Environment
Appium version (or git revision) that exhibits the issue: 1.6.3
Desktop OS/version used to run Appium: mac OSx 10.12.1
Mobile platform/version under test: iOS 10.2
Real device or emulator/simulator:: Real Device
Appium CLI or Appium.app|exe: 1.6.3 no UI

## My Caps:
```
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "iOS");
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("newCommandTimeout", 9000);
capabilities.setCapability("xcodeConfigFile", "/usr/local/lib/node_modules/appium/"
	+ "node_modules/appium-xcuitest-driver/WebDriverAgent/xcodeConfigFile.xcconfig");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPad Pro");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.2");
capabilities.setCapability(MobileCapabilityType.UDID, "faa0447802b5fbe83e06907fbfd2dd007e1dcece");`
```

## Error
This is the main error I'm getting: 
`Encountered internal error running command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1`

## Link to Appium logs
Here is a link to the full log which has the error I mentioned above near the bottom (just do a search for bootstrap). https://gist.github.com/WoodPlank/85d8421a2c93f46cda7d56acaac8765c

## Trying to Fix
I've looked at previous posts and their fixes didn't seem to work for me. When I try to run 
```
$ bash Scripts/bootstrap.sh -d
Fetching dependencies
Error: Command "bootstrap" does not exist.`
```
I know I'm in the right location because
```
$ pwd
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
```
Any help would be greatly appreciated!

**Comment by mykola-mokhnach** [comment]
Make sure carthage is installed on the machine

**Comment by WoodPlank** [comment]
It is installed.
`WebDriverAgent$ carthage version
Carthage Version: 1.0.6
Built internally @ devagnos.com`

**Comment by mykola-mokhnach** [comment]
What is the output of
```bash
/bin/bash -xe Scripts/bootstrap.sh -d
```

**Comment by WoodPlank** [comment]
I ran `/bin/bash -xe Scripts/bootstrap.sh -d` and this is the output:

`+ set -e`
`+ export`
`PATH=/Users/financialtown/.nvm/versions/node/v6.9.1/bin:/Users/financialtown/local/bin:/Users/financialtown/.rvm/gems/ruby-2.1.1/bin:/Users/financialtown/.rvm/gems/ruby-2.1.1@global/bin:/Users/financialtown/.rvm/rubies/ruby-2.1.1/bin:/Users/financialtown/Downloads/apache-maven-3.3.9/bin:/Users/financialtown/local/bin:/Users/financialtown/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/financialtown/.rvm/bin:/Users/financialtown/.rvm/bin:/usr/local/bin`
`+` `PATH=/Users/financialtown/.nvm/versions/node/v6.9.1/bin:/Users/financialtown/local/bin:/Users/financialtown/.rvm/gems/ruby-2.1.1/bin:/Users/financialtown/.rvm/gems/ruby-2.1.1@global/bin:/Users/financialtown/.rvm/rubies/ruby-2.1.1/bin:/Users/financialtown/Downloads/apache-maven-3.3.9/bin:/Users/financialtown/local/bin:/Users/financialtown/.rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/financialtown/.rvm/bin:/Users/financialtown/.rvm/bin:/usr/local/bin`
`+ BOLD='\033[1m'`
`+ [[ ! -f Scripts/bootstrap.sh ]]`
`+ getopts ' i d D h ' option`
`+ case "$option" in`
`+ FETCH_DEPS=1`
`+ getopts ' i d D h ' option`
`+ [[ -n x ]]`
`+ fetch_and_build_dependencies`
`+ echo -e '\033[1mFetching dependencies'`
`Fetching dependencies`
`+ assert_has_carthage`
`+ command -v carthage`
`+ cmp -s Cartfile.resolved Carthage/Cartfile.resolved`
`+ carthage bootstrap`
`Error: Command "bootstrap" does not exist.`

**Comment by dpgraham** [comment]
Can you try running `carthage help` from your terminal? I'd like to see if `bootstrap` is one of the available commands.

**Comment by WoodPlank** [comment]
I ran `WebDriverAgent $ carthage help`

Results:
`db:bootstrap`	
     `Runs db:drop, db:create, db:prepare, db:migrate, db:seed`

**Comment by dpgraham** [comment]
When I run `carthage help` the result is:

```
   archive           Archives built frameworks into a zip that Carthage can use
   bootstrap         Check out and build the project's dependencies
   build             Build the project's dependencies
   checkout          Check out the project's dependencies
   copy-frameworks   In a Run Script build phase, copies each framework specified by a SCRIPT_INPUT_FILE environment variable into the built app bundle
   fetch             Clones or fetches a Git repository ahead of time
   help              Display general or command-specific help
   outdated          Check for compatible updates to the project's dependencies
   update            Update and rebuild the project's dependencies
   version           Display the current version of Carthage
```

When I run `carthage version` the result is `0.18.1`

I think you may be running a program called carthage but it's different from the one that is published on Homebrew that we use in Appium.

Can you try doing this:

```
brew uninstall carthage
brew install carthage
```

**Comment by WoodPlank** [comment]
You're absolutely right. I actually had 2 different versions of carthage. The `brew uninstall carthage` uninstalled the carthage published by Homebrew. I had installed carthage using npm. I did `npm uninstall -g carthage` and that seemed to get rid of it (it was a global package). 

I ran `brew install carthage` but when I run `carthage version` it says `-bash: /Users/financialtown/.nvm/versions/node/v6.9.1/bin/carthage: No such file or directory`

Do I need to update my .bash_profile in order to run `carthage version` ? It looks like we're on the right track. Thanks for all your help, dpgraham!

**Comment by pavanbachu0604** [comment]
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/
/bin/bash Scripts/bootstrap.sh -d

These steps will help you download the dependencies that are related to WDA.

**Comment by jlipps** [comment]
@WoodPlank if you do `which carthage` in a new terminal window, what does it say? Seems like your terminal still thinks `carthage` is a node module.

**Comment by WoodPlank** [comment]
I have appium opening the app on my ios device! Thank you all for your help! I will close this issue.

@jlipps you were right. I had to close my terminal and run `npm uninstall -g carthage` and then close my terminal again and reopen it. I'm now running 0.18.1 carthage and it's located /usr/local/bin/carthage

@pavanbachu0604 These two steps installed bootstrap.sh! I then had to install ios-deploy but it's working now.

**Comment by jlipps** [comment]
glad to hear it @WoodPlank!

**Comment by mikhailpractice** [comment]
@dpgraham @WoodPlank Thanks a lot, trying to solve that problem all day

**Comment by mouli0107** [comment]
when i am running the command --  cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/
/bin/bash Scripts/bootstrap.sh -d    ------      i am getting this error  .......

           Fetching dependencies
*** Cloning KissXML
*** Cloning peertalk
*** Checking out KissXML at "5.0.5"
*** Cloning KissXML
*** Checking out peertalk at "v1.0"
*** Cloning peertalk
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/marekcirkos/KissXML.git /Users/ca_automation/Library/Caches/org.carthage.CarthageKit/dependencies/KissXML) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

CAN ANYONE HELP ME I AM NEW TO APPIUM 
APPIUM VERSION---    1.6.1
XCODE VERSION---- 8.3.2
MAC OS--------------10.12.5

**Comment by KaranKKK** [comment]
when i am running the command -- cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/
/bin/bash Scripts/bootstrap.sh -d ------ i am getting this error .......

       Fetching dependencies
*** Cloning KissXML
*** Cloning peertalk
*** Checking out KissXML at "5.0.5"
*** Cloning KissXML
*** Checking out peertalk at "v1.0"
*** Cloning peertalk
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/marekcirkos/KissXML.git /Users/ca_automation/Library/Caches/org.carthage.CarthageKit/dependencies/KissXML) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

CAN ANYONE HELP ME I AM NEW TO APPIUM
APPIUM VERSION--- 1.6.1
XCODE VERSION---- 8.3.2
MAC OS--------------10.12.5

**Comment by KaranKKK** [comment]
when i am running the command -- cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/
/bin/bash Scripts/bootstrap.sh -d ------ i am getting this error .......

   Fetching dependencies
*** Cloning KissXML
*** Cloning peertalk
*** Checking out KissXML at "5.0.5"
*** Cloning KissXML
*** Checking out peertalk at "v1.0"
*** Cloning peertalk
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/marekcirkos/KissXML.git /Users/ca_automation/Library/Caches/org.carthage.CarthageKit/dependencies/KissXML) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

CAN ANYONE HELP ME I AM NEW TO APPIUM
APPIUM VERSION--- 1.6.1
XCODE VERSION---- 8.3.2
MAC OS--------------10.12.5

**Comment by imurchie** [comment]
Appium 1.6.3 will no longer work if it was not used before. An upstream dependency was deleted by its owner. Please upgrade Appium.
