### ISSUE TITLE
Investigate Android test failures

### ISSUE THREAD

**Issue by imurchie** [appium/appium#7707]
## Investigate Android test failures

Some of our Android tests fail on different systems. Explore what the problems are and if they can be fixed (they are quarantined now).

Android 7.1, 7.0, 5.1
- performance getPerformanceData should get the amount of cpu by user and kernel process

Android 7.1, 7.0
- should find an element with recursive UiSelectors

Android 5.1, 5.0
- apidemo - notifications should open the notification shade @skip-ci
  - works individually, just not in suite
  - appears to come after setting locale. Not sure if that has anything to do with it

Android 5.1, 4.4, 4.3
- createSession should be able to grant permissions

Android 5.1
- Localization - locale @skip-ci @skip-real-device should start as FR

Android 4.3
- clear text does not work at all
- Localization - locale @skip-ci @skip-real-device should start as US
- performance getPerformanceData should get the network statistics

**Comment by jlipps** [comment]
Sounds good, I'll bump this in priority.

**Comment by vrunoa** [comment]
can I help with anything here @imurchie  ?

**Comment by saikrishna321** [comment]
@imurchie ping
