### ISSUE TITLE
iproxy error connecting to device with xcode 8 and appium 1.6.3

### ISSUE THREAD

**Issue by gopi09m** [appium/appium#7708]
## The problem

We were able to use appium 1.6.3 to run tests on ipad. But when we use the same script with all the capabilities correctly updated it doesnt run the tests on iPhone. But it was able to launch WDA and iphone app and launches iphone app too. But when it posts a command to click a button it crashes the app and isee "iProxy Error connecting to device!".

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: Mac OS 10.12
* Node.js version (unless using Appium.app|exe): latest
* Mobile platform/version under test: IOS 10.2
* Real device or emulator/simulator: Iphone real device with 10.2 OS 
* Appium CLI or Appium.app|exe: CLI

## Debug:

[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther","2738f9a0-0ed2-456f-b692-dbb94a31fd37"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 15000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/31CF96D8-13BA-4341-A457-B16D35DE5192/element] with body: {"using":"xpath","value":"//XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther"}
[debug] [iProxy] recv failed: Resource temporarily unavailable
[debug] [iProxy] recv failed: Operation not permitted
[debug] [BaseDriver] Waited for 455 ms so far
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/31CF96D8-13BA-4341-A457-B16D35DE5192/element] with body: {"using":"xpath","value":"//XCUIElementTypeApplication/XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther[3]/XCUIElementTypeOther/XCUIElementTypeScrollView/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther"}
[debug] [iProxy] Error connecting to device!​

## Workaround:
When i debugged this issue further i found that the session is expiring , so i started executing .getpagesource() everytime before i execute any action. And this works for now. But i don't know iphone is different than iPad in this context.

I have below code which works for iPad.

iosDriver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
iosDriver.manage().timeouts().pageLoadTimeout(90, TimeUnit.SECONDS);
wait = new WebDriverWait(iosDriver, 60);​

**Comment by mykola-mokhnach** [comment]
This usually means that WDA is frozen and does not respond to HTTP requests. Please check https://github.com/facebook/WebDriverAgent/issues/372 
Nothing we can do to fix it from Appium side.
