### ISSUE TITLE
FindElementsByXPath("//XCUIElementTypeCell") is not returning the correct results

### ISSUE THREAD

**Issue by jtappi** [appium/appium#7710]
## The problem

For some reason, the following XPath Query returns 0 results.  However, I can clearly see the the fields I am searching for in the XML.  

## Environment

* Appium: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: MAC El Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): 3.10.9
* Mobile platform/version under test: iOS 10.1
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: n/a

## Details

The XPath query is not working as expected.  Some elements are easily found while others are not found but are clearly visible and found via other methods (FindElementsById for example).

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/58dcffc7-7cb6-472a-b255-0ad99d447776/elements {"using":"xpath","value":"//XCUIElementTypeCell"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeCell","58dcffc7-7cb6-472a-b255-0ad99d447776"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/BA702CF2-A0AB-482E-ADF5-825EA67FB394/elements] with body: {"using":"xpath","value":"//XCUIElementTypeCell"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"BA702CF2-A0AB-482E-ADF5-825EA67FB394","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/58dcffc7-7cb6-472a-b255-0ad99d447776/elements 200 18433 ms - 74 

## Code To Reproduce Issue [ Good To Have ]

C# Code used to search for the XCUI Element
var p = driver.FindElementsByXPath("//XCUIElementTypeCell");
Count = 0

## XML File being search
***There are 19 XCUIElementTypeCell elements that are all enabled, valid and visible
***Replaced <> with !!
!!XCUIElementTypeCell name="cell" label="cell" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/1/0/0/0/0/0/0/0/3/0/0/4" x="0" y="109" width="375" height="118"!!
!!XCUIElementTypeStaticText name="1" label="1" value="1" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/1/0/0/0/0/0/0/0/3/0/0/4/7" x="287" y="126" width="22" height="17"!!
!!/XCUIElementTypeStaticText!!
!!/XCUIElementTypeCell"!!

**Comment by mykola-mokhnach** [comment]
This might be a race condition. _findElements_ does not wait for element to appear in DOM, but rather returns matches immediately. Can you put a delay or a timer in your code before to invoke this method?

**Comment by mykola-mokhnach** [comment]
The second possible issue - https://github.com/facebook/WebDriverAgent/issues/372

**Comment by jtappi** [comment]
Thanks Mykola!

I tried putting a Thread.Sleep(2000) just to see if it makes a difference but it does not.  I also applied your patch a week or so ago.  maybe i will remove it and see if the current issue of not finding the elements still exists.  However, since i have applied your patch the pro has been that my tests run faster due to no longer running into the Error Copying attributes issue.  

Thanks for your help but I guess i'll have to figure out a different way to get the information that i need from the XML.

**Comment by mykola-mokhnach** [comment]
also check what 

```
driver.FindElementsByClassName("XCUIElementTypeCell")
```

returns for the same case

**Comment by jtappi** [comment]
That helped.  It quickly returned all elements with that Class Name.  i'll see if i can use this to drill further down and find what i am looking for.  Thanks!

**Comment by jlipps** [comment]
@jtappi it would also be interesting to see if a call to findElement (singular) works any differently? Especially if you have an implicit wait timeout set. I.e., `driver.FindElementByXPath("//XCUIElementTypeCell");`

**Comment by kcinman11358** [comment]
you can attempt to inspect it to using the inspector. 


    launch the appium (1.6 or above) from the command prompt/terminal
    Open the appium 1.5.3 GUI and fill in all required settings(AppPath, package, Automation Name, Platform version - even if we couldn't find in drop down edit it, Device Name) DONOT HIT LAUNCH
    then click on the inspector icon on the GUI.

Also, select an iPhone 7 from the drop down

**Comment by jtappi** [comment]
@jlipps thanks for the suggestions!  I do use the singular in other places and i tried it here and it successfully finds the first element.  Unfortunately there are situations where the first element is not useful for my test.  

@kcinman11358 thanks for the suggestion.  I am not sure if the Appium inspector will help me much here.  I am already getting the source during the test run (while debugging) and i also do make use of the iOS Appium Inspector.  If I misunderstood your suggestion please let me know.

**Comment by jlipps** [comment]
@jtappi it's possible what you're experiencing is a duplicate of https://github.com/appium/appium/issues/7583 if there's a discrepancy between what the singular and plural versions return

**Comment by jtappi** [comment]
hmm.  thanks @jlipps .  I'll see if i can come up with a different way to get the to the exact elements i am looking for.

**Comment by jtappi** [comment]
I am closing this ticket as there are existing issues already documented.  I have not found a solution to my problem, I simply found a different way to achieve my task.  Thanks for all the help!
