### ISSUE TITLE
Appium inspector is not locating element properly on UIAWebview with iOS-9+.

### ISSUE THREAD

**Issue by atiqul2007** [appium/appium#7714]
**The problem**
With iOS-9+ version, Appium inspector is not locating element properly on UIAWebview, locator (red mark as in attached screenshot) is not aligned with element. As a result, button does not get clicked when we use coordinates. This is not an issue with iOS-8.3            

**Environment:**
Appium version: 1.5.3
Robotframework: 3.0
Mobile platform: iPad2 iOS-9.2.1
Real device: Real Device
Robotframework-Appiumlibrary: 1.4.0.1
Python: 2.7

**Details**
With iOS-9+ version, Appium inspector is not locating element properly on UIAWebview, locator (red mark as in attached screenshot) is not aligned with element. As a result, button does not get clicked when I use coordinates.  I used iOS-9.2.1 and this issue is only reproducible on UIAWebview. 
But when I use iOS-8.3, locator is properly on top of correct element.

**Screenshots:**
1.
<img width="1433" alt="screen shot 2017-01-18 at 9 33 35 am" src="https://cloud.githubusercontent.com/assets/25082074/22072068/17a048d4-dd6f-11e6-8d1d-da20d2e12b27.png">

2.
<img width="775" alt="screen shot 2017-01-18 at 9 33 42 am" src="https://cloud.githubusercontent.com/assets/25082074/22072086/28a104a2-dd6f-11e6-83c9-e6cef6b2350f.png">

**Comment by jlipps** [comment]
That version of the inspector is not supported or maintained. We're working on a brand new one that will be.

**Comment by atiqul2007** [comment]
@jlipps, you are referring to appium version or iOS version?

**Comment by jlipps** [comment]
I'm saying that Appium.app itself is not supported or maintained.
