### ISSUE TITLE
Toggle Airplane Mode method on real Android Device (7.1) not working

### ISSUE THREAD

**Issue by tjhillard** [appium/appium#7716]
## The problem

When calling `driver.toggleAirplaneMode()` while testing on a physical Android device, Airplane Mode appears to be toggled but the phones behavior does not change. In other words, the device's airplane mode icon in the notifications tray changes appropriately (enables/disables) but the desired functionality is not applied. WiFi & Data remain on and working. If I manually toggle the Airplane Mode button on, it works as expected where the WiFi & Data icons are dimmed, desired functionality also occurs going the other way (on --> off).

## Environment

* Appium v1.6.3
* macOS Sierra v10.12.1
* Nodfe v7.1.0
* Android 7.1 (Google Pixel)
* Real Device
* Appium CLI

## Link to Appium logs

[Gist](https://gist.github.com/tjhillard/27ab0e7ffa77bb10989df76446cffb90)

## Code To Reproduce Issue

```js
it('should toggle airplane mode', function() {
    return driver.toggleAirplaneMode();
});
```

Following this code the device will still have a fully functioning network connection, even though the Airplane Mode toggle in the notifications tray is enabled (lit up).

**Comment by leskop-sk** [comment]
I can confirm this, is there any update?

**Comment by jlipps** [comment]
I'm not sure there's anything we can do about this, if it's still an issue. Looking through the logs, Appium is successfully running the Android commands. And the UiAutomator process is stopped as a result of wifi mode being on. Maybe there is some other device setting that needs to be toggled for things to actually take effect, or maybe this is a limitation of the adb method we're using. At any rate I don't think there's anything we can do. Unless @sravanmedarapu or @mykola-mokhnach have any ideas.

**Comment by mykola-mokhnach** [comment]
Toggling airplane mode on real android devices is not available for non-system applications, because Google denied this on API level. There is NO workaround for it. It only possible to toggle Wi-Fi on and off. And data connection can be only enabled/disabled on rooted phones with the recent Appium 1.6.4 beta release.

**Comment by robertarles** [comment]
This is the solution I implemented.

``` this.When (/^I toggle airplane mode "([^"]*)"$/, (state) => {

    // set airplane mode ON (disable comms) or OFF (enable comms)
    switch (state) {
      case 'off':
        state = 'enable';
        break;
      case 'on':
        state = 'disable';
        break;
      default:
        state = 'disable';
    }

    // toggle airplane mode on/off
    // browser.toggleAirplaneMode ();
    execFileSync (`${process.env.ANDROID_HOME}/platform-tools/adb`, [
      'wait-for-device'
    ]);
    execFileSync (`${process.env.ANDROID_HOME}/platform-tools/adb`, [
      'root'
    ]);
    execFileSync (`${process.env.ANDROID_HOME}/platform-tools/adb`, [
      'shell',
      `svc data ${state}`
    ]);
    execFileSync (`${process.env.ANDROID_HOME}/platform-tools/adb`, [
      'shell',
      `svc wifi ${state}`
    ]);
  });```

**Comment by julien-c** [comment]
I'm new to this, but can't you (programmatically) swipe down the system's notification center and send a tap to XPath element `//android.widget.Switch[@content-desc="Airplane mode"]` (via appium obviously)?
