### ISSUE TITLE
"Waiting for WebDriverAgent server to finish loading..." for more than 30 mins

### ISSUE THREAD

**Issue by StevieSun** [appium/appium#7717]
## The problem
When i execute the automation script, appium server tries to start the WebDriverAgent on the device. I can see the WebDriverAgent launching on the device and pushing to background. But the appium server still displays

"Waiting for WebDriverAgent server to finish loading..." even if i wait for 30 mins.

Please help as soon as possible. This is a real blocker

## Environment

* Appium version - 1.6.3
* Desktop OS version - 10.11.6
* Node.js version - 5.7.0
* Mobile platform - iOS 10.1.1
* Real device - true
* Appium CLI 

## Details

But sometimes when the appium server starts the iproxy successfully for that particular run. Then the subsequent runs are always working. Closing the WebDriverAgent in the device manually again runs into the same issue mentioned. Tried reinstalling appium also and it did not help.

## Link to Appium logs

The appium server logs 

https://gist.github.com/StevieSun/b32794db0fbca3911ecb6add93c7da84

**Comment by mykola-mokhnach** [comment]
Try the updated xcuitest component:

```
npm remove -g appium
npm install -g appium --no-shrinkwrap
```

**Comment by StevieSun** [comment]
Great!!! That worked @mykola-mokhnach. Thanks for your help.... Appreciate it.
