### ISSUE TITLE
Unable to start appium_giving an error as process ended

### ISSUE THREAD

**Issue by laliths** [appium/appium#7718]
## The problem

we installed appium 1.4.161 ophiu chus version but when we start we are facing an issue of process ended.we unintalled and re installed again.But throwing the same error.Even before it is working fine.But it stopped abruptly.We tried changing the port number also but no use.please provide some solution to start appium,
## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by dpgraham** [comment]
Reinstall Appium and use the latest version 1.6.3 

```
npm remove -g appium
npm install -g appium --no-shrinkwrap
```
