### ISSUE TITLE
Not able to click on the button in the overlay

### ISSUE THREAD

**Issue by ADYASHA-PADHI** [appium/appium#7720]
Hi,
 I am trying to click on a button with accessibility id "JOIN" in an overlay. The element isDisplayed returns true. But when I wait for the element to be displayed, it doesn't return any value. And I can't click on it because appium does not find it. (appium 1.6.3 , iOS simulator on 10.2, Xcode 8.2.1, mac version 10.11.16).
Below are the logs. I have also attached a screenshot of the inspector.

[debug] [XCUITest] Executing command 'getCurrentContext'
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/context 200 1 ms - 84
[HTTP] --> POST /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/elements {"using":"accessibility id","value":"JOIN"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["accessibility id","JOIN","444f6a5c-7969-44da-85df-d1ad41507ca2"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/8636CCA3-3FB6-47E3-9832-DD2191829A41/elements] with body: {"using":"accessibility id","value":"JOIN"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"28B60DC9-BEDE-4E95-9558-90CC84582355","type":"XCUIElementTypeButton","label":"JOIN"}],"sessionId":"8636CCA3-3FB6-47E3-9832-DD2191829A41","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"28B60DC9-BEDE-4E95-9558-90CC84582355","type":"XCUIElementTypeButton","label":"JOIN"}]
[HTTP] <-- POST /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/elements 200 3776 ms - 170
[HTTP] --> POST /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/timeouts {"type":"implicit","ms":1000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",1000,"444f6a5c-7969-44da-85df-d1ad41507ca2"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 1000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/timeouts 200 2 ms - 76
[HTTP] --> GET /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/element/28B60DC9-BEDE-4E95-9558-90CC84582355/displayed {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/element/28B60DC9-BEDE-4E95-9558-90CC84582355/displayed] to [GET http://localhost:8100/session/8636CCA3-3FB6-47E3-9832-DD2191829A41/element/28B60DC9-BEDE-4E95-9558-90CC84582355/displayed] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : true,\n  \"sessionId\" : \"8636CCA3-3FB6-47E3-9832-DD2191829A41\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId 8636CCA3-3FB6-47E3-9832-DD2191829A41 with 444f6a5c-7969-44da-85df-d1ad41507ca2
[HTTP] <-- GET /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/element/28B60DC9-BEDE-4E95-9558-90CC84582355/displayed 200 199 ms - 76
[HTTP] --> POST /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/timeouts {"type":"implicit","ms":0}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",0,"444f6a5c-7969-44da-85df-d1ad41507ca2"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 0ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/timeouts 200 1 ms - 76
[HTTP] --> GET /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/context {}
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["444f6a5c-7969-44da-85df-d1ad41507ca2"]
[debug] [XCUITest] Executing command 'getCurrentContext'
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/context 200 1 ms - 84
[HTTP] --> POST /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/elements {"using":"accessibility id","value":"JOIN"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["accessibility id","JOIN","444f6a5c-7969-44da-85df-d1ad41507ca2"]
[debug] [XCUITest] Executing command 'findElements'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/8636CCA3-3FB6-47E3-9832-DD2191829A41/elements] with body: {"using":"accessibility id","value":"JOIN"}
[debug] [WebDriverAgent] Sim: Jan 19 15:16:30 adyasha-inl XCTRunner[13038]: Enqueue Failure: UI Testing Failure - Failed to get snapshot within 15.0s /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1
[debug] [JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"8636CCA3-3FB6-47E3-9832-DD2191829A41","status":0}
[debug] [MJSONWP] Responding to client with driver.findElements() result: []
[HTTP] <-- POST /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/elements 200 59860 ms - 74
[HTTP] --> POST /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/timeouts {"type":"implicit","ms":1000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",1000,"444f6a5c-7969-44da-85df-d1ad41507ca2"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 1000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2/timeouts 200 2 ms - 76
[HTTP] --> DELETE /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["444f6a5c-7969-44da-85df-d1ad41507ca2"]
[debug] [JSONWP Proxy] Proxying [DELETE /session/444f6a5c-7969-44da-85df-d1ad41507ca2] to [DELETE http://localhost:8100/session/8636CCA3-3FB6-47E3-9832-DD2191829A41] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"60C5829A-AFE2-4539-96C8-38077C59D92D\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 13019)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Shutting down Logger process (pid 13024)
[XCUITest] Simulator log exited with code 'null'
[debug] [XCUITest] Reset not set, not ending sim
[debug] [iOSLog] Stopping iOS log capture
[Appium] Removing session 444f6a5c-7969-44da-85df-d1ad41507ca2 from our master session list
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/444f6a5c-7969-44da-85df-d1ad41507ca2 200 59322 ms - 76

<img width="1353" alt="screen shot 2017-01-19 at 3 38 29 pm" src="https://cloud.githubusercontent.com/assets/25221476/22102484/9990b812-de5d-11e6-9e5f-da6c19ba8f4e.png">

**Comment by jlipps** [comment]
2 things:

1. in a situation like this,  you always want to print out the source immediately before finding your element to prove that it is actually there

2. if you're finding an element by accessibility id, you probably don't want to find multiple elements. if you try to find a single element, it will trigger the built-in implicit wait which will make your tests less flakey. if you find multiple elements, you have to manage waits yourself.

**Comment by ADYASHA-PADHI** [comment]
When I try to print any of the attributes(name, id, accessibility id), i get this error: Can't locate an element by this strategy: [unknown locator]. I **can't even click** on it.

But the isDisplayed() returns true for the element.

**But the appium log says** : [debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id

Could you help? Any idea whats going wrong here. This is an overlay element which comes up after we click another element on the parent screen.

The logs are the same as above.

**Comment by jlipps** [comment]
1. What is your test code?
2. What is the output of getPageSource (the XML document) immediately before finding the element?

**Comment by ADYASHA-PADHI** [comment]
Never mind. It worked. Just a system level problem. Its working on other systems. Anyways, thanks a lot for your time and effort.

**Comment by jlipps** [comment]
OK, great to hear!

**Comment by HasaanAli** [comment]
Guys i'm having a related issue. Appium server running in terminal says "[WebDriverAgend] Failed to get snapshot within 15.0s"

**Comment by prakashpqa** [comment]
> Never mind. It worked. Just a system level problem. Its working on other systems. Anyways, thanks a lot for your time and effort.

I am having the same problem. Can you tell me how it worked. I am not able to click the button on the overlay.
