### ISSUE TITLE
.touchPerform({action:'longPress'}) is not implemented

### ISSUE THREAD

**Issue by jesusMT** [appium/appium#7721]
## The problem
When I try to test an iOS app with a WebDriverIO .touchPerform() the test fails.

## Environment
Appium version (or git revision) that exhibits the issue: 1.6.3
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: Mac Book Pro
Node.js version (unless using Appium.app|exe): 6.9.1
Mobile platform/version under test: iPhone 5
Real device or emulator/simulator: simulator
Appium CLI or Appium.app|exe: npm appium
Chrome: 55.0.2883.95
ChromeDriver: 2.20.353124

## Details
I want to paste a text into my iOS device simulator. I try it with .touchPerform() action and longPress or press screen, but the action is not recognized by Appium.
When do you implement it??

Thanks!

## Link to Appium logs

Error: Support for this gesture is not yet implemented. Please contact an Appium dev
   at elementIdClick("5047") - click.js:20:22

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/jesusMT/9ca034744f9a0e7210bb843da1c312a4

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by dpgraham** [comment]
Can you paste more of the Appium logs?

**Comment by jesusMT** [comment]
https://gist.github.com/jesusMT/48cdaf1ff0dee8c9ca90d2ee3e63cf0e

**Comment by dpgraham** [comment]
Do you have the logs where it shows the error "Support for this gesture is not yet implemented. Please contact an Appium dev
at elementIdClick("5047")" 

It's helpful to see the logs leading up to that error.

**Comment by imurchie** [comment]
This might be something weird with webdriver.io's implementation, which we need to handle.

The following log bit shows the lack of arguments in the touch action.
```
[HTTP] --> POST /wd/hub/session/b960d826-0f9b-4791-a23a-8218c3168b0f/touch/perform {"actions":{"action":"longPress"}}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [{"action":"longPress"},"b960d826-0f9b-4791-a23a-8218c3168b0f"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action:
[HTTP] <-- POST /wd/hub/session/b960d826-0f9b-4791-a23a-8218c3168b0f/touch/perform 501 5 ms - 164
```

It is sending `{"actions":{"action":"longPress"}}` while Appium is expecting something more like `{"actions":[{"action":"longPress","options":{"element":"539F3063-4445-4CB5-8E6C-C43D187FD591"}}]}`.

**Comment by imurchie** [comment]
But also, there needs to be something to long press _on_. Without an element or a location, it cannot do much of anything.

**Comment by jlipps** [comment]
@christian-bromann any ideas why webdriverio allows this case?

**Comment by christian-bromann** [comment]
@jesusMT you are using the protocol command with wrong parameters. I would recommend to use the [touchAction](http://webdriver.io/api/mobile/touchAction.html) command here. It has a cleaner argument structure.

Note that WebdriverIO has two kind of commands: protocol and action commands. Protocol commands (like [touchPerform](https://github.com/webdriverio/webdriverio/blob/master/lib/protocol/touchPerform.js)) just take what you pass along as parameter and send it directly to Appium whereas action commands (like [touchAction](https://github.com/webdriverio/webdriverio/blob/master/lib/commands/touchAction.js)) have a whole lot of logic to assist you (e.g. giving errors if the command isn't used properly).

**Comment by jesusMT** [comment]
@dpgraham this error is from these logs --> https://gist.github.com/jesusMT/315b76678df3b514fd8416dd34131552 but there are no more info here.

Should I send more than one parameter?

**Comment by dpgraham** [comment]
I would recommend using the touchAction function in place of touchPerform
