### ISSUE TITLE
https://github.com/appium/appium-xcuitest-driver > Real devices > Configuration is not working

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#7723]
## The problem

As per https://github.com/appium/appium-xcuitest-driver > Real devices > Configuration

I did setup but it didn't work as expected. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac  10.11.6
* Node.js version (unless using Appium.app|exe): 7.2.1
* Mobile platform/version under test:  iPhone SE  10.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

1. As per instructions under https://github.com/appium/appium-xcuitest-driver > Real devices > Configuration
2. I did setup but it didn't work
3. I've mentioned workaround in https://github.com/appium/appium/issues/6867#issuecomment-273795275

Please have a look again and update this part of README

4. Any sample project for users to try out with these instruction will be of great help as well.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by jlipps** [comment]
Those instructions do work, and are working for others. If there's something that's not working for you, it's not because the configuration instructions are incorrect. there might be some other bug or system problem. We'll need you to provide full logs and a repro case if you want us to look into it further.

**Comment by vikramvi** [comment]
@jlipps Please find logs of the issue
https://github.com/appium/appium/issues/6867#issuecomment-273531206

https://github.com/appium/appium/issues/6867#issuecomment-273513356

Also I did generic search with term "is:issue is:open Error 65" fetched 36 open issues. This means many users are having tuff time running app in real iOS device with 10.2

I personally felt documentation is too complex and lack detail explanation with figures.

**Comment by jlipps** [comment]
A lot of issues come up for that term because it's a very generic error, which in most cases indicate that users are having trouble with their certificates and signing (and that is unfortunately an Apple complexity, not an Appium one).

**Comment by jlipps** [comment]
@vikramvi what are the contents of your xcconfig file? Are you able to launch the app on your device using Xcode outside of Appium?

**Comment by vikramvi** [comment]
@jlipps I've below in myconfig.xcconfig file

DEVELOPMENT_TEAM = {correct_value}
CODE_SIGN_IDENTITY = iPhone Developer

Yes I could able to launch app on real phone from xcode. 

My request was to have a re-look at setup documents and add minute details with figures.

Thanks in advance.

**Comment by vikramvi** [comment]
@jlipps one more appium user has mentioned same thing as I've mentioned. Which is step mentioned in setup documentation never done or useful

Please check https://github.com/appium/appium/issues/6867#issuecomment-273983412

**Comment by jlipps** [comment]
@vikramvi we'll take a close look at the docs and make sure they have full and complete information as part of https://github.com/appium/appium/issues/7577
