### ISSUE TITLE
Error launching instruments: Instruments never checked in 

### ISSUE THREAD

**Issue by harishgm25** [appium/appium#7725]
## The problem

I am facing a issue with appium server args --tracetemplate 
error : [Instruments] Error launching instruments: Instruments never checked in
xcode: 7.3 V

## Environment

Appium Version 1.5.3 and 1.6.3

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Appium] Welcome to Appium v1.6.3
[Appium] Non-default server args:
[Appium] port: 60344
[Appium] sessionOverride: true
[Appium] log: '/Users/Appzui/dev/HEXCTZ/UIFunctional/target/appiumlogs/c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6__TestPostRegDenyPermissions.txt'
[Appium] automationTraceTemplatePath: '/Users/Appzui/Network.tracetemplate'
[Appium] tmpDir: '/Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344'
[Appium] webkitDebugProxyPort: 60311
[Appium] Appium REST http interface listener started on 0.0.0.0:60344
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.3","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 18 ms - 83
Setting iOS Desired Capabilities:
Setting Android Desired Capabilities:
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/Appzui/Desktop/Ctz_app/ctz.ipa","platformVersion":"9.0","bundleId":"com.appzui.dev.ctzdev","udid":"c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6","platformName":"iOS","deviceName":"iPhone","nativeWebTap":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/Appzui/Desktop/Ctz_app/ctz.ipa","platformVersion":"9.0","bundleId":"com.appzui.dev.ctzdev","udid":"c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6","platformName":"iOS","deviceName":"iPhone","nativeWebTap":true},null,null,null,null]
[Appium] Creating new IosDriver session
[Appium] Capabilities:
[Appium] app: '/Users/Appzui/Desktop/Ctz_app/ctz.ipa'
[Appium] platformVersion: '9.0'
[Appium] bundleId: 'com.appzui.dev.ctzdev'
[Appium] udid: 'c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6'
[Appium] platformName: 'iOS'
[Appium] deviceName: 'iPhone'
[Appium] nativeWebTap: true
[debug] [iOS] IosDriver version: 1.13.2
[BaseDriver] Session created with session id: a33a75b6-0bc2-4464-b3a5-66334e49f330
[debug] [iOS] Xcode version set to 7.3.1
[debug] [iOS] Not auto-detecting udid.
[BaseDriver] Using local app '/Users/Appzui/Desktop/Ctz_app/ctz.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/pw/lf7sgm517s57wjj9jrff3bqm0000gn/T/2017011-1177-1tdpvge/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/pw/lf7sgm517s57wjj9jrff3bqm0000gn/T/2017011-1177-1tdpvge/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/pw/lf7sgm517s57wjj9jrff3bqm0000gn/T/2017011-1177-1tdpvge/Payload/Citizens Emergency Response App.app'
[debug] [iOS] Removing any remaining instruments sockets
[debug] [iOS] Cleaned up instruments socket /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/instruments_sock
[debug] [iOS] No language specified. Using default strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/Appzui/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/usr/local/Cellar/node4-lts/4.6.1/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...bug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
[debug] [UIAuto] Dynamic bootstrap path: /Users/Appzui/Library/Application Support/appium/bootstrap/bootstrap-77ff5609db8aae5d.js
[debug] [UIAuto] Creating or overwriting dynamic bootstrap: /Users/Appzui/Library/Application Support/appium/bootstrap/bootstrap-77ff5609db8aae5d.js
[debug] [iOS] Creating iDevice object with udid c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6
[debug] [iOS] Running ios real device reset flow
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [iOS] App is not installed. Will try to install.
[debug] [iOS] App installed.
[debug] [iOS] Starting UIAutoClient, and launching Instruments.
[debug] [UIAuto] Instruments socket server started at /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/instruments_sock
[debug] [Instruments] Instruments is at: /Applications/Xcode.app/Contents/Developer/usr/bin/instruments
[debug] [Instruments] Attempting to launch instruments, this is try #1
[Instruments] Launching instruments
[debug] [Instruments] Attempting to run app on real device with UDID 'c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6'
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Users/Appzui/Network.tracetemplate -D /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments/instrumentscli0.trace -w c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6 com.appzui.dev.ctzdev -e UIASCRIPT "/Users/Appzui/Library/Application Support/appium/bootstrap/bootstrap-77ff5609db8aae5d.js" -e UIARESULTSPATH /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments'
[debug] [Instruments] And extra without-delay env: {}
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}
[debug] [Instruments] [INST STDERR] 2017-01-11 17:06:23.219 instruments[1189:103618] WebKit Threading Violation - initial use of WebKit from a secondary thread.
[Instruments] Instruments socket client never checked in; timing out (global)
[debug] [Instruments] Kill instruments
[debug] [Instruments] Sending SIGTERM
[debug] [Instruments] [INST] Instruments Trace Complete (Duration : 83.412544s; Output : /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments/instrumentscli0.trace)
[debug] [Instruments] Instruments exited with code: 0
[Instruments] Error launching instruments: Instruments never checked in
[debug] [Instruments] Attempting to launch instruments, this is try #2
[Instruments] Launching instruments
[debug] [Instruments] Attempting to run app on real device with UDID 'c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6'
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Users/Appzui/Network.tracetemplate -D /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments/instrumentscli0.trace -w c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6 com.appzui.dev.ctzdev -e UIASCRIPT "/Users/Appzui/Library/Application Support/appium/bootstrap/bootstrap-77ff5609db8aae5d.js" -e UIARESULTSPATH /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments'
[debug] [Instruments] And extra without-delay env: {}
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}
[debug] [Instruments] [INST STDERR] 2017-01-11 17:07:55.659 instruments[1195:104441] WebKit Threading Violation - initial use of WebKit from a secondary thread.
[Instruments] Instruments socket client never checked in; timing out (global)
[debug] [Instruments] Kill instruments
[debug] [Instruments] Sending SIGTERM
[debug] [Instruments] [INST] Instruments Trace Complete (Duration : 88.006195s; Output : /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments/instrumentscli0.trace)
[debug] [Instruments] Instruments exited with code: 0
[Instruments] Error launching instruments: Instruments never checked in
[debug] [Instruments] Attempting to launch instruments, this is try #3
[Instruments] Launching instruments
[debug] [Instruments] Attempting to run app on real device with UDID 'c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6'
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Users/Appzui/Network.tracetemplate -D /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments/instrumentscli0.trace -w c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6 com.appzui.dev.ctzdev -e UIASCRIPT "/Users/Appzui/Library/Application Support/appium/bootstrap/bootstrap-77ff5609db8aae5d.js" -e UIARESULTSPATH /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments'
[debug] [Instruments] And extra without-delay env: {}
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}
[debug] [Instruments] [INST STDERR] 2017-01-11 17:09:30.882 instruments[1204:105424] WebKit Threading Violation - initial use of WebKit from a secondary thread.
[Instruments] Instruments socket client never checked in; timing out (global)
[debug] [Instruments] Kill instruments
[debug] [Instruments] Sending SIGTERM
[debug] [Instruments] [INST] Instruments Trace Complete (Duration : 88.531746s; Output : /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments/instrumentscli0.trace)
[debug] [Instruments] Instruments exited with code: 0
[Instruments] Error launching instruments: Instruments never checked in
[debug] [Instruments] Attempting to launch instruments, this is try #4
[Instruments] Launching instruments
[debug] [Instruments] Attempting to run app on real device with UDID 'c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6'
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Users/Appzui/Network.tracetemplate -D /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments/instrumentscli0.trace -w c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6 com.appzui.dev.ctzdev -e UIASCRIPT "/Users/Appzui/Library/Application Support/appium/bootstrap/bootstrap-77ff5609db8aae5d.js" -e UIARESULTSPATH /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments'
[debug] [Instruments] And extra without-delay env: {}
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}
[debug] [Instruments] [INST STDERR] 2017-01-11 17:11:07.534 instruments[1210:106317] WebKit Threading Violation - initial use of WebKit from a secondary thread.
[Instruments] Instruments socket client never checked in; timing out (global)
[debug] [Instruments] Kill instruments
[debug] [Instruments] Sending SIGTERM
[debug] [Instruments] [INST] Instruments Trace Complete (Duration : 88.548218s; Output : /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments/instrumentscli0.trace)
[debug] [Instruments] Instruments exited with code: 0
[Instruments] Error launching instruments: Instruments never checked in
[debug] [Instruments] Attempting to launch instruments, this is try #5
[Instruments] Launching instruments
[debug] [Instruments] Attempting to run app on real device with UDID 'c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6'
[debug] [Instruments] Found Insruments-Without-Delay: /usr/local/lib/node_modules/appium/node_modules/appium-instruments/thirdparty/iwd7
[debug] [Instruments] Spawning instruments with command: '/Applications/Xcode.app/Contents/Developer/usr/bin/instruments -t /Users/Appzui/Network.tracetemplate -D /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments/instrumentscli0.trace -w c02bbbf3b4a8b0e47e75d4a6872f8ee6084aa0c6 com.appzui.dev.ctzdev -e UIASCRIPT "/Users/Appzui/Library/Application Support/appium/bootstrap/bootstrap-77ff5609db8aae5d.js" -e UIARESULTSPATH /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments'
[debug] [Instruments] And extra without-delay env: {}
[debug] [Instruments] And launch timeouts (in ms): {"global":90000}
[debug] [Instruments] [INST STDERR] 2017-01-11 17:12:44.076 instruments[1216:107291] WebKit Threading Violation - initial use of WebKit from a secondary thread.
[Instruments] Instruments socket client never checked in; timing out (global)
[debug] [Instruments] Kill instruments
[debug] [Instruments] Sending SIGTERM
[debug] [Instruments] [INST] Instruments Trace Complete (Duration : 88.009659s; Output : /Users/Appzui/dev/HEXCTZ/UIFunctional/target/tmp_60344/appium-instruments/instrumentscli0.trace)
[debug] [Instruments] Instruments exited with code: 0
[Instruments] Error launching instruments: Instruments never checked in
[Instruments] Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch
at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
at Instruments.launch$ (../../lib/instruments.js:223:15)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
at nextTickCallbackWith0Args (node.js:420:9)
at process._tickCallback (node.js:349:13)
[Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch]
[MJSONWP] Encountered internal error running command: Error: We exceeded the number of retries allowed for instruments to successfully start; failing launch
at Object.wrappedLogger.errorAndThrow (lib/logger.js:60:13)
at Instruments.launch$ (../../lib/instruments.js:223:15)
at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
at[HTTP] <-- POST /wd/hub/session 500 489699 ms - 232
run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
at nextTickCallbackWith0Args (node.js:420:9)
at process._tickCallback (node.js:349:13)

## Code To Reproduce Issue [ Good To Have ]

Please remember that, with sample code; it's easier to reproduce bug and much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Are you sure your app can be started properly on the device? 
What if you remove bundleId parameter from capabilities?
