### ISSUE TITLE
i get stuck at the step "    t =     0.01s     Set Up",but it can work on Simulator

### ISSUE THREAD

**Issue by Chenneyfang** [appium/appium#7726]
## The problem
i get stuck at the step " t = 0.01s Set Up",it can't continue,but it can work on Simulator
## Environment

* Appium version (or git revision) that exhibits the issue:git version
* Last Appium version that did not exhibit the issue (if applicable):1.6.3
* Desktop OS/version used to run Appium:10.11.6 (15G31)
* Node.js version (unless using Appium.app|exe):v4.4.5
* Mobile platform/version under test:iOS 10.1.1
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:  CLI

## Details
i get stuck at the step " t = 0.01s Set Up",it can't continue.

## Link to Appium logs
CodeSign Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
    cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/chen-pc/Applications/infer-os/infer/bin:{/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/chen-pc/.rvm/bin:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin}:/usr/local/bin/libimobiledevice-macosx-master/"

Signing Identity:     "iPhone Developer: xxxxxxxxx"
Provisioning Profile: "iOS Team Provisioning Profile: *"
                      (xxxxxxxxxx)

    /usr/bin/codesign --force --sign A55D3D1ACA634AB55C1C9ACB9B191CF41228ED1A --deep --entitlements /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentRunner.build/WebDriverAgentRunner.xctest.xcent --timestamp=none /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app: replacing existing signature

writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/qy/tbjywb2d3fgfmtqv108knyr80000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/98ad6f863ad4ada460fa48d44ad543b9/02c2afe9d5acb35f04b292ea84ff4f6d83c15482/ManifestCache.plist
Test Suite 'All tests' started at 2017-01-20 17:20:27.725
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-01-20 17:20:27.727
Test Suite 'UITestingUITests' started at 2017-01-20 17:20:27.727
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2017-01-20 17:20:27.729
    t =     0.00s     Set Up

**Comment by mykola-mokhnach** [comment]
Try with updated modules:

```
npm remove -g appium
npm install -g appium --no-shrinkwrap
```
