### ISSUE TITLE
Appium cant start because it cant find uiautomator

### ISSUE THREAD

**Issue by hsarmah09** [appium/appium#7727]
I am trying to automate some tests on android virtual device and appium. But appium cant start the remote driver due to error that it cant kill the process uiautomator.

Appium version : 1.4.16.1
Android version: 7.0

Logs: 
 info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\Users\HSARMAH\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ps 'uiautomator'"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> warn: UiAutomator did not shut down fast enough, calling it gone
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> error: Failed to start an Appium session, err was: Error: Command failed: C:\Users\HSARMAH\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ps 'uiautomator'"
> 
> info: [debug] Error: Command failed: C:\Users\HSARMAH\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ps 'uiautomator'"
> 
>     at ChildProcess.exithandler (child_process.js:206:12)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Command failed: C:\\Users\\HSARMAH\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -s emulator-5554 shell \"ps 'uiautomator'\"\n)","killed":false,"code":1,"signal":null,"cmd":"C:\\Users\\HSARMAH\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -s emulator-5554 shell \"ps 'uiautomator'\"","origValue":"Command failed: C:\\Users\\HSARMAH\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -s emulator-5554 shell \"ps 'uiautomator'\"\n"},"sessionId":null}
> info: <-- POST /wd/hub/session 500 12367.466 ms - 556 

What I don't understand is why is it trying to kill the process, I tried to execute the command manually from adb shell and of course there is no such process running on the AVD.

**Comment by mykola-mokhnach** [comment]
1.4.16 is very old Appium version. Can you try 1.6.3?

**Comment by hsarmah09** [comment]
How do I upgrade? Even if I have downloaded the latest version, it installs 1.14.16 everytime. And it doesnt show any update on startup.

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for howto questions. You can install Appium 1.6.3 using NPM:

```
npm install -g appium@1.6.3
```
