### ISSUE TITLE
Processes not killed while doing iOS automation

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#7728]
## The problem

With latest 1.6.3 server have problem that processes not get stopped/killed while iOS automating. This cause reaching Mac limit quite fast and need either restart or killing opened processes.

List of opened processes is (hundreds of each):
 - pkd
 - IDSKeychainSyncingProxy
 - CloudKeychainProxy
 - aslmanager

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3 including latest (no-shrinkwrap)
* Last Appium version that did not exhibit the issue (if applicable): 1.6.1/2 (if i remember correctly)
* Desktop OS/version used to run Appium: MAC 10.12.2
* Mobile platform/version under test: iOS Simulator 10.2

**Comment by mykola-mokhnach** [comment]
Which capabilities do you use in your tests?

**Comment by amedvedjev** [comment]
**one time when install client:**
Capabilities [{app=/Users/jenkinss/Downloads/test_clients/xxxx.app, preventWDAAttachments=false, noReset=false, clearSystemFiles=true, scaleFactor=0.5, version=, deviceName=iPhone 6s, fullReset=true, platform=MAC, newCommandTimeout=120, platformVersion=10.2, automationName=XCuiTest, browserName=, waitForAppScript=$.delay(3000); $.acceptAlert(); true;, wdaConnectionTimeout=60000}]

**about 20 times with client reset:**
Capabilities [{app=/Users/jenkinss/Downloads/test_clients/xxxx.app, preventWDAAttachments=false, noReset=false, clearSystemFiles=true, scaleFactor=0.5, version=, deviceName=iPhone 6s, fullReset=false, platform=MAC, newCommandTimeout=120, platformVersion=10.2, automationName=XCuiTest, browserName=, waitForAppScript=$.delay(3000); $.acceptAlert(); true;, wdaConnectionTimeout=60000}]

**and all others (many):**
Capabilities [{app=/Users/jenkinss/Downloads/test_clients/xxxx.app, preventWDAAttachments=false, noReset=true, clearSystemFiles=true, scaleFactor=0.5, version=, deviceName=iPhone 6s, fullReset=false, platform=MAC, newCommandTimeout=120, platformVersion=10.2, automationName=XCuiTest, browserName=, waitForAppScript=$.delay(3000); $.acceptAlert(); true;, wdaConnectionTimeout=60000}]

**Comment by jlipps** [comment]
Hmm. We don't open those processes directly. Can you link to a gist of an appium log? I'm wondering if something odd is going on. Are there a certain number of processes that the list increases by every session?

**Comment by jlipps** [comment]
Perhaps #7732 is a clearer indication of what is happening here?

**Comment by amedvedjev** [comment]
ok. investigated and fixed on my side. the story is:
we know that new facebook driver has bad manner to stuck in any place. in 99% it is hanging on driver open or command driver.launchApp().
**Workaround #1:** When test execution exceeding 10min just retry did not help. cause problem was in Simulator that needed to be restarted.
**Workaround #2:** First quick (but not best) solution was to kill Simulator process before test for sure. Helped to reduce number of stuck but still sometimes happens. Look like this solution cause  nested processes not get killed and after 2 test suite run i was need to reboot mac or kill many processes.
**Workaround #3:** Simulator kill was replaced with soft kill via osascript fist and then with hard kill -9 (for sure). This fixed all problems with left processes.

Now i am testing solution to execute in "Executors.newFixedThreadPool(1)" and with "if (!executor.awaitTermination(100, TimeUnit.SECONDS)) {" retry again.

So if you do not see Appium problem here i guess we can close issue.

**Comment by jlipps** [comment]
That is interesting that it's related to the simulator. Appium does already kill the sim on its own, do you not see that? I'm wondering if the way we're killing the sim is leaving hanging processes. Are you just killing the simulator process itself? Or other things too?

**Comment by amedvedjev** [comment]
when we complete test with (fullReset=false + noReset=true) Simulator will left running after driver.quit().
subsequent re-using of Simulator cause stuck to happen much more often comparing with case when simulator did fresh start. so mine simulator close actually affected tests "**and all others (many):**"

**Comment by imurchie** [comment]
If you leave n`noReset` true (so sim stays running) and add `useNewWDA` capability, so we uninstall the application each time through, do you see the same problem with getting stuck?

**Comment by amedvedjev** [comment]
i do not want to reinstall app each time. it is slow. current driver start time is 80sec with reinstall app, 50sec with reset app and about 30sec normal. with current 70tests it will take 80x70=5600/60=93min = 1.5h of pure start time..... damn slow...

**Comment by amedvedjev** [comment]
Also wonder why driver.quit() closes simulator with fullReset=true or noReset=false but leave it with fullReset=false + noReset=true ?

**Comment by jlipps** [comment]
That's kind of the point of these capabilities, to do as little cleanup as possible, including leaving the sim open for future tests so it doesn't have to reboot.

**Comment by amedvedjev** [comment]
@imurchie @jlipps 
adding `useNewWDA=true` helped to minimize even more. and first time i got successful run with not closing emulator before every test. although from second try (first met with stuck also and i got fixed mine trap in code to catch it correctly in code).
And this gave large time improvement from 3h to 2h30min due to minimize time on driver start.
thanks.

**Comment by amedvedjev** [comment]
closing issue. after adding first soft close to Simulator problem gone.
thanks for hint with "`useNewWDA`"!

**Comment by imurchie** [comment]
Excellent! I'm glad it helped!
