### ISSUE TITLE
iOS: Driver.closeApp() cause app to uninstall

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#7729]
## The problem

when driver started with "fullReset=true" or "noReset=false" driver.closeApp() cause to uninstall application in simulator and simulator close.

when driver started with "fullReset=false" + "noReset=true" driver.closeApp() does not uninstall app but just close it without closing Simulator.

Expected: i prefer that closeApp() - just close application in all cases.

## Environment

* Appium version (or git revision) that exhibits the issue: latest 1.6.3 (no-shrinkwrap)
* Last Appium version that did not exhibit the issue (if applicable): ?
* Desktop OS/version used to run Appium: mac 10.12.2
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator 10.2

**Comment by imurchie** [comment]
Yes, too much is being done in the `stop` method. This should mirror what happens in `appium-ios-driver`.

**Comment by jlipps** [comment]
@imurchie is this done now with the PR being merged?

**Comment by imurchie** [comment]
Yes. I think the closeApp/reset logic is messed up (should keep WDA going, etc). But this specific issue is done.
