### ISSUE TITLE
Driver Session Details are not getting updated properly

### ISSUE THREAD

**Issue by SrinivasanTarget** [appium/appium#7730]
## The problem

Driver Session Details are not getting updated properly

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator: iOS/Android devices
* Appium CLI or Appium.app|exe: CLI

## Details

1) ```browserName``` parameter is ```null``` in Android while running tests on Native Context whereas it is ```empty string``` for iOS
iOS:
<img width="929" alt="screen shot 2017-01-18 at 10 38 39 pm" src="https://cloud.githubusercontent.com/assets/8896549/22158282/93ac80d4-df61-11e6-8da7-856df9d6e9f8.png">
android:
<img width="865" alt="screen shot 2017-01-18 at 10 53 25 pm" src="https://cloud.githubusercontent.com/assets/8896549/22158316/aee2dce0-df61-11e6-9be0-1666467eecaa.png">

This results in patch work on client side https://github.com/appium/java-client/pull/556/commits/3047a97f86556cec6d1946fad8b2571c2f1d3ec8#diff-5cc23e0813c3b69a6a372e9605891da4R60

2)Switching to Web Context from Native Context doesn't update ```browserName``` parameter as safari for iOS whereas it is updated properly in android.
<img width="1037" alt="screen shot 2017-01-19 at 8 44 29 pm" src="https://cloud.githubusercontent.com/assets/8896549/22158389/04a21a06-df62-11e6-8310-5567f631d2c5.png">

This result in patching on ```java-client``` here https://github.com/appium/java-client/pull/556/commits/3047a97f86556cec6d1946fad8b2571c2f1d3ec8#diff-c60f84c0cc90f37a9a4513eeebd4896dR437

Clients like ```java-client``` and  ```dotnet-driver``` depends on session details for several decisions like determining driver type, element type etc.

Also it is same in new drivers and legacy drivers as well.

Tests are available here to reproduce: https://github.com/TikhomirovSergey/java-client/blob/3047a97f86556cec6d1946fad8b2571c2f1d3ec8/src/test/java/io/appium/java_client/appium/element/generation/ios/IOSElementGenerationTest.java#L74

@jlipps @issac @sravanmedarapu FYI

cc @TikhomirovSergey

**Comment by SrinivasanTarget** [comment]
@triager please label: Bug

**Comment by jlipps** [comment]
So IIUC there are two things we need to discuss here:

1. Ensuring we pass the same thing back from all drivers for an empty browserName, which I think is reasonable.
2. Figure out what we want to return if we're in a web context. I am not convinced we should set the browserName to safari when we're in a web context. What if we're in a different app altogether, not a browser? Why is the Java client so sensitive to this? Can it just keep a local version of the current context instead and check against that? That's what it should really care about IMO.

**Comment by SrinivasanTarget** [comment]
@jlipps  Sorry for the delay.
>Ensuring we pass the same thing back from all drivers for an empty browserName, which I think is reasonable.

Yes SGTM
>Figure out what we want to return if we're in a web context. I am not convinced we should set the browserName to safari when we're in a web context. What if we're in a different app altogether, not a browser?

Accepted, Can we send it as ```null``` please in android when we are in web context as like how we do currently for iOS to maintain session consistency?

>Can it just keep a local version of the current context instead and check against that?

Yes.We have updated it already.

**Comment by jlipps** [comment]
OK, so the task here is just to ensure that we send `null` back for browserName everywhere, when we're not actually automating a browser like Safari or Chrome. Adding to backlog.

**Comment by mykola-mokhnach** [comment]
I assume this is not relevant anymore
