### ISSUE TITLE
Appium 1.6.3 Terminate Abruptly during the test script execution 

### ISSUE THREAD

**Issue by dilsreccse** [appium/appium#7731]
## The problem
Appium 1.6.3 [XCUITestDriver version: 2.5.3]getting terminated in the terminal when i do a test script execution for multiple test scripts, due to this issue my test scripts are not executed completely. provided the appium logs below. What could be the possible way to resolve this?
 
"[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
<--- Last few GCs --->
31052638 ms: Mark-sweep 1377.4 (1431.8) -> 1338.0 (1403.5) MB, 920.6 / 0.0 ms [allocation failure] [GC in old space requested].
31053808 ms: Mark-sweep 1338.0 (1403.5) -> 1337.9 (1405.5) MB, 1170.1 / 0.0 ms [allocation failure] [GC in old space requested].
31054796 ms: Mark-sweep 1337.9 (1405.5) -> 1337.5 (1372.5) MB, 987.3 / 0.0 ms [last resort gc].
31055716 ms: Mark-sweep 1337.5 (1372.5) -> 1337.5 (1372.5) MB, 920.8 / 0.0 ms [last resort gc].
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0x11b0631cfb51 <JS Object>
    2: onOutput [/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/lib/device-log/ios-log.js:404] [pc=0x150935659b35] (this=0x1b026445d3a1 <an IOSLog with map 0x2981e963d9>)
    3: /* anonymous */ [/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/lib/device-log/ios-log.js:~311] [pc=0x1509387a349b] (this=0x1b026445d4f1 <a SubProcess with map 0x2981e6a...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 5: v8::internal::(anonymous namespace)::FastElementsAccessor<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::AddArguments(v8::internal::Handle<v8::internal::JSArray>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::Arguments*, unsigned int, v8::internal::(anonymous namespace)::Where) [/usr/local/bin/node]
 6: v8::internal::(anonymous namespace)::DoArrayPush(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)0>) [/usr/local/bin/node]
 7: v8::internal::Runtime_ArrayPush(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 8: 0x1509347079a7
Abort trap: 6
unameits-Mac-mini:~ mnameit$ " 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Sierra Mac OS
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10 [iPad Air ]
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: Appium CLI 
* XCUITestDriver version           : 2.5.3
## Link to Appium logs
 [https://gist.github.com/dilsreccse/6da92d43623cc4872af9de16292935ac]

**Comment by mykola-mokhnach** [comment]
@imurchie it looks like the device is generating too much logs and thus _this.logsSinceLastRequest_ property of IOSLog class eats too much memory

**Comment by mykola-mokhnach** [comment]
@dilsreccse for now you can try just to get appium logs of **syslog** category as a workaround, since this class will clean up the temporary buffer.

**Comment by dilsreccse** [comment]
@mykola-mokhnach thank you :) could you tell me how to get the appium logs of syslog category?

**Comment by mykola-mokhnach** [comment]
I don't know which high-livel client you use. [Here](http://stackoverflow.com/questions/25431380/capturing-browser-logs-with-selenium) you can see the general approach

**Comment by dilsreccse** [comment]
@mykola-mokhnach i'm using java client & automating iOS native app, how to do that, i'm not getting it approach properly , need your help !

**Comment by jlipps** [comment]
@dilsreccse at this point it may just be easier to wait until @mykola-mokhnach's PR is merged, then you can try out the new behavior in Appium.

**Comment by jlipps** [comment]
ok, this has been merged. give a try as follows:

```
npm uninstall -g appium
npm install -g appium --no-shrinkwrap
```

**Comment by mykola-mokhnach** [comment]
@dilsreccse Is the problem fixed now with the updated component?

**Comment by dilsreccse** [comment]
Yes, Now Appium is not getting terminated!  @mykola-mokhnach & @jlipps thanks 👍

**Comment by jlipps** [comment]
Amazing!

**Comment by risinek** [comment]
Hi, is there any documentation to the --no-shrinkwrap parameter?
