### ISSUE TITLE
idevicesyslog processes doesn't get killed.

### ISSUE THREAD

**Issue by h3dkandi** [appium/appium#7732]
## The problem

I have 300 idevicesyslog processes. I don't know if they are left from the current environment or the one before it. It was updated 3 days ago.

## Environment

* Appium version (or git revision) that exhibits the issue: Welcome to Appium v1.6.3 (REV ca3233c0974e56c75ee0aee3666c32ad20fc322d)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.12.2
* Node.js version (unless using Appium.app|exe): 7.2.1
* Mobile platform/version under test: iOS 10.2 and 9.5.3
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Old Environment

Appium version (or git revision) that exhibits the issue: v1.6.3 (REV ea23991)
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: macOS 10.12.2
Node.js version (unless using Appium.app|exe): 7.2.1
Mobile platform/version under test: iOS 10.2
Real device or emulator/simulator: Real device
Appium CLI or Appium.app|exe: Appium CLI

## Details

I see them trough the Application Monitor. Is this normal? Shouldn't they be killed after appium is killed?

## Link to Appium logs

iOS Safari tests [appium log](https://gist.github.com/h3dkandi/7df47c8be18e89a0bc7b81cf11745633)
Hybrid tests [appium log](https://gist.github.com/h3dkandi/84540d794bed398cda8695c8c442ad62)

**Comment by imurchie** [comment]
They should be, yes. Can you provide the logs so we can see what is happening?

**Comment by h3dkandi** [comment]
@imurchie I edited my original post and attached last night tests' logs. There are probably  a couple of unrelated Appium problems in them but haven't read them fully. At some point the webdriver just gives up starting - "Early unexpected exit" there are some socket hang ups as well.

**Comment by h3dkandi** [comment]
As I see it after the last for the session WDA retry fail with code 65 there is no shutting down procedure. What follows is the next XCUITestDriver session which probably starts its own idevicesyslog. Could this be it?

**Comment by jlipps** [comment]
Perhaps, @h3dkandi. I also just noticed that when we start the session, we call `driver.startLogCapture()` which apparently starts both a `syslog` and a `crashlog` capture. But in `deleteSession` we only stop the capture of the `syslog`. So, there's a chance we are forgetting to clean up the other log as well? @imurchie what do you see?

**Comment by imurchie** [comment]
The crash log doesn't actually do anything, until one tries to get the logs, since they are just files on the local file system. I'll look a little at how we're handling it in the retry.

**Comment by imurchie** [comment]
Can you move to the latest (`npm uninstall -g appium && npm install -g appium --no-shrinkwrap`? The startup no longer makes use of logging, so it should not be an issue anymore.

**Comment by h3dkandi** [comment]
Is `npm install -g appium --no-shrinkwrap` the same as updating from github? I have cloned the github repository and that is how I use Appium. That is because I though this was the only way to get the latest.

Side note: Cloning the latest WDA and replacing the one in the appium-xcuitest-driver seems to fix alot of the problems. However I would like to see how it will go with further/longer testing. (I also have the --HEAD brew installs for IWDP and HEAD installs for its dependencies)

**Comment by jlipps** [comment]
@h3dkandi it's not exactly the same as updating from GitHub, although in the case where (a) no commits have been made to appium/appium since the last release, and (b) all changes to subpackages have been published, it is the same. But updating from GitHub (`cd $appium_git_checkout; rm -rf node_modules && npm install && node .`) is the most surefire way to get latest, yes.

**Comment by mykola-mokhnach** [comment]
@h3dkandi Is the problem fixed after update?

**Comment by h3dkandi** [comment]
I am still accumulating _idevicesyslog_ - [processes.txt](https://gist.github.com/h3dkandi/3b5225bad946d24fee16e7317506dc9c). 
My naked eye observation deduced that the problem is when hangup processes and other termination doesn't execute because of some error that prevents them to. Then Appium retries anew to start the test driver session with the given capabilities. The previous _idevicesyslog_ will persist .

But maybe this is not that big of an issue. If I manage to fix my crashing the accumulation will disappear as well.

**Comment by mykola-mokhnach** [comment]
yup, I think it makes sense to call driver.quit in any case for correct cleanup.
@imurchie is it possible in nodejs to add an observer/callback in case the "parent" driver object does not exist anymore to cleanup such leftover processes automatically in the situation described above?

**Comment by jlipps** [comment]
Looks like what @imurchie did in https://github.com/appium/appium-xcuitest-driver/pull/353 suffices for that purpose! Closing here unless we still notice an issue with that change applied.
