### ISSUE TITLE
Appium server eventually stops replying (iOS 10.2 Simulator, Cordova)

### ISSUE THREAD

**Issue by jamsesso** [appium/appium#7734]
## The problem

On a hybrid Cordova app, I've been writing a test that performs a high number of fuzzed form submissions in an attempt to reproduce a long-standing bug that we've not been able to witness in-house. This test consists of navigating from the main screen (tasks.html) to the form (numerical.html). Once the form is submitted, the user is redirected back to home.html. This is in a loop set to iterate 1000 times.

Eventually the Appium server seems to stop responding after the navigation to tasks.html. I am using a `WebDriverWait` to wait until the URL is tasks.html and the list of tasks are rendered, and the request never seems to be fulfilled by the server. It also seems to ignore my timeout of 60 seconds as it reattempts for much longer than that.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): (haven't used previous versions)
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe): v5.11.0
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Details

One additional note about our app specifically is that whenever the tasks.html page is requested, the Cordova webview is destroyed, a new one is created, and the Cordova plugins are re-initialized. This is unfortunately because of the technical debt surrounding our app. Because the bug only seems to occur when we navigate to tasks.html, I am speculating that it has to do with this re-init process that has been hacked into Cordova. However, it's non-deterministic nature seems like it may be a problem with Appium itself, as it works most of the time. Perhaps a timing issue?

I have tried resetting the context to be the new webview once it is created, but this seemed to cause this freezing behaviour to happen more often.

## Link to Appium logs

Appium logs: https://gist.github.com/jamsesso/7c5d2499a826d996d134f55732ddbe4c
Java output: https://gist.github.com/jamsesso/8a14d836eea845802271cd9005815ade

**Comment by jlipps** [comment]
@imurchie some weird stuff in the logs here that I'm not sure initially how to interpret. Looks like multiple calls are getting queued up eventually? And also looks like we're not selecting what looks like the right app?

@jamsesso could you also try with the latest appium from master? 

```
npm uninstall -g appium
npm install -g --no-shrinkwrap appium
```

We've made some changes to the remote debugger logic which may affect this issue.

**Comment by jamsesso** [comment]
@jlipps Thank you for the suggestion. That did not seem to work. I believe `npm install -g --no-shrinkwrap appium` would install the same version I was running previously, but I tried anyways and captured the (full) logs:

https://gist.github.com/jamsesso/98e48edbf44f3ccb29ccd6d317fc579e

Would it be worth attempting to clone the repository, build Appium, and install that?

**Comment by jlipps** [comment]
@jamsesso yeah that might be worth it. should be as simple as a clone, an `npm install`, and then running `node .` in that dir to start appium.

would you also mind sharing your java code? i'm just confused why we're getting what look like multiple responses from the debugger for the same requests.

**Comment by jamsesso** [comment]
@jlipps Here is the code: https://gist.github.com/jamsesso/e821cde61d2c247653ce944bb1978062
To annotate: I start by logging in, clicking a task in the list (hardcoded as #9 right now), and continue to fill in data, submit the form and then return to submit more data (1000 times).

When I run this, Appium successfully submits the form < 10 times before apparently freezing up.

The master branch appears to exhibit the same behaviour. I've include those logs here as well: https://gist.github.com/jamsesso/d8bd0a59cde1754cfca31da5d76bf7b0

**Comment by jlipps** [comment]
> [HTTP] <-- POST /wd/hub/session/879cd797-2926-437a-a184-0b036f291b66/context - - ms - -

Shows that the client disconnected before receiving any data from the server. Perhaps due to a timeout. Please try with latest Appium (1.6.4) and I'm happy to reopen if we can still repro it.
