### ISSUE TITLE
Appium v1.6.3 - iOS hybrid app no WEBVIEW java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by fnkbz** [appium/appium#7737]
## The problem

I use appium 1.6.3, iphone 6 with ios 10.2 and mac os sierra 10.12.2. I am trying to create a maven project using java-client 3.4.1 to run my tests for a hybrid cordova mobile app. I have created a first test to see if appium is working for my enviroment. I follow [these](https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/hybrid.md) instructions to get the webview of my app. The result that i get is java.lang.ArrayIndexOutOfBoundsException: 1 when i am trying to access the driver.getContextHandles().

I start the appium server with **default** capabilities like this:

- $ `appium --address 127.0.0.1 --default-capabilities '{"app": "//Users/unifydev/Library/Developer/Xcode/DerivedData/myPortalToGo-bruslmewcrrhtgcptjccttkzsnoz/Build/Products/Debug-iphoneos/myapp.app", "udid":"08c4ff299bf4b7f21c7114bc7631166a37cdc1ae","platformName":"ios","deviceName": "iPhone 6","automationName":"XCUITest"}'`

## Environment

* Appium v1.6.3
* mac os sierra 10.12.2
* Node version v7.4.0
* Mobile platform/version under test: iOS
* Real device: iPhone 6

### Logs

The server starts and the output is : 

> [Appium] Welcome to Appium v1.6.3
> [Appium] Non-default server args:
> [Appium]   address: '127.0.0.1'
> [Appium]   defaultCapabilities: { app: '//Users/unifydev/Library/Developer/Xcode/DerivedData/myPortalToGo-bruslmewcrrhtgcptjccttkzsnoz/Build/Products/Debug-iphoneos/myPortal to go.app',
>   udid: '08c4ff299bf4b7f21c7114bc7631166a37cdc1ae',
>   platformName: 'ios',
>   deviceName: 'iPhone 6',
>   automationName: 'XCUITest' }
> [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
> [Appium]   app: '//Users/unifydev/Library/Developer/Xcode/DerivedData/myPortalToGo-bruslmewcrrhtgcptjccttkzsnoz/Build/Products/Debug-iphoneos/myPortal to go.app'
> [Appium]   udid: '08c4ff299bf4b7f21c7114bc7631166a37cdc1ae'
> [Appium]   platformName: 'ios'
> [Appium]   deviceName: 'iPhone 6'
> [Appium]   automationName: 'XCUITest'
> [Appium] Appium REST http interface listener started on 127.0.0.1:4723

> [HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"platformName":"iOS"},"requiredCapabilities":{}},"desiredCapabilities":{"platformName":"iOS"},"requiredCapabilities":{}}
> [debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS"},{},{"desiredCapabilities":{"platformName":"iOS"},"requiredCapabilities":{}},null,null]
> [Appium] Creating new XCUITestDriver session
> [Appium] Capabilities:
> [Appium]   platformName: 'iOS'
> [Appium]   app: '//Users/unifydev/Library/Developer/Xcode/DerivedData/myPortalToGo-bruslmewcrrhtgcptjccttkzsnoz/Build/Products/Debug-iphoneos/myPortal to go.app'
> [Appium]   udid: '08c4ff299bf4b7f21c7114bc7631166a37cdc1ae'
> [Appium]   deviceName: 'iPhone 6'
> [Appium]   automationName: 'XCUITest'
> [debug] [XCUITest] XCUITestDriver version: 2.4.2
> [BaseDriver] Session created with session id: 70e1e71e-365e-40b5-8583-3ee4ca9b0f20
> [debug] [XCUITest] Xcode version set to '8.2.1'
> [debug] [XCUITest] iOS SDK Version set to '10.2'
> [debug] [XCUITest] Available devices: 08c4ff299bf4b7f21c7114bc7631166a37cdc1ae
> [debug] [XCUITest] Creating iDevice object with udid 08c4ff299bf4b7f21c7114bc7631166a37cdc1ae
> [XCUITest] Determining device to run tests on: udid: '08c4ff299bf4b7f21c7114bc7631166a37cdc1ae', real device: true
> [BaseDriver] Using local app '//Users/unifydev/Library/Developer/Xcode/DerivedData/myPortalToGo-bruslmewcrrhtgcptjccttkzsnoz/Build/Products/Debug-iphoneos/myPortal to go.app'
> [debug] [XCUITest] Checking whether app '//Users/unifydev/Library/Developer/Xcode/DerivedData/myPortalToGo-bruslmewcrrhtgcptjccttkzsnoz/Build/Products/Debug-iphoneos/myPortal to go.app' is actually present
> [debug] [XCUITest] App is present
> [debug] [ios-app-utils] Getting bundle ID from app '//Users/unifydev/Library/Developer/Xcode/DerivedData/myPortalToGo-bruslmewcrrhtgcptjccttkzsnoz/Build/Products/Debug-iphoneos/myPortal to go.app': 'com.unify.osso.myPortalToGo'
> [debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
> [debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
> [XCUITest] Setting up real device
> [debug] [XCUITest] App is already installed.
> [debug] [XCUITest] Full reset not requested. No need to install.
> [XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
> [XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
> [XCUITest] Launching WebDriverAgent on the device
> [debug] [XCUITest] Carthage found: /usr/local/bin/carthage
> [debug] [XCUITest] Killing hanging processes
> [debug] [XCUITest] Using real device logger 'idevicesyslog'
> [debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=08c4ff299bf4b7f21c7114bc7631166a37cdc1ae -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
> [debug] [XCUITest] Unable to get device time. Using local system time
> [debug] [XCUITest] Output from idevicedate: Tue Jan 24 10:23:08 EET 2017
> 
> [XCUITest] Waiting for WebDriverAgent to start on device
> [debug] [XCUITest] Log file for xcodebuild test: /Users/unifydev/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/E552C5B5-13A8-4879-90EA-3FBA5C873915/Session-WebDriverAgentRunner-2017-01-24_102309-BLv7Yb.log
> [debug] [WebDriverAgent] Device: Jan 24 10:23:15 Vassiliss-iPhone XCTRunner[4465] <Notice>: Running tests...
> [debug] [WebDriverAgent] Device: Jan 24 10:23:16 Vassiliss-iPhone XCTRunner[4465] <Notice>: Continuing to run tests in the background with task ID 1
> [XCUITest] Detected that WebDriverAgent is running at url 'http://192.168.173.183:8100'
> [XCUITest] WebDriverAgent started at url 'http://192.168.173.183:8100'
> [debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
> [debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.unify.osso.myPortalToGo","arguments":[],"environment":{},"shouldWaitForQuiescence":true}}
> [debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"D5EE452B-9F1F-46CF-9FEE-A9C985D66532","capabilities":{"device":"iphone","browserName":"myPortal to go","sdkVersion":"10.2","CFBundleIdentifier":"com.unify.osso.myPortalToGo"}},"sessionId":"D5EE452B-9F1F-46CF-9FEE-A9C985D66532","status":0}
> [debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
> [debug] [JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/D5EE452B-9F1F-46CF-9FEE-A9C985D66532/orientation] with body: {"orientation":"PORTRAIT"}
> [debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"D5EE452B-9F1F-46CF-9FEE-A9C985D66532","status":0}
> [Appium] New XCUITestDriver session created successfully, session 70e1e71e-365e-40b5-8583-3ee4ca9b0f20 added to master session list
> [debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"platformName":"iOS","app":"//Users/unifydev/Library/Developer/Xcode/DerivedData/myPortalToGo-bruslmewcrrhtgcptjccttkzsnoz/Build/Products/Debug-iphoneos/myPortal to go.app","udid":"08c4ff299bf4b7f21c7114bc7631166a37cdc1ae","deviceName":"iPhone 6","automationName":"XCUITest"}
> [HTTP] <-- POST /wd/hub/session 200 18763 ms - 544 
> [HTTP] --> GET /wd/hub/session/70e1e71e-365e-40b5-8583-3ee4ca9b0f20/contexts {}
> [debug] [MJSONWP] Calling AppiumDriver.getContexts() with args: ["70e1e71e-365e-40b5-8583-3ee4ca9b0f20"]
> [debug] [XCUITest] Executing command 'getContexts'
> [debug] [iOS] Getting list of available contexts
> [debug] [iOS] Retrieving contexts and views
> [debug] [iOS] Selecting by url: false 
> [debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
> [debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
> [debug] [RemoteDebugger] Page element JSON: []
> [debug] [iOS] No web frames found.
> [debug] [MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
> [HTTP] <-- GET /wd/hub/session/70e1e71e-365e-40b5-8583-3ee4ca9b0f20/contexts 200 21 ms - 86 
> [HTTP] --> DELETE /wd/hub/session/70e1e71e-365e-40b5-8583-3ee4ca9b0f20 {}
> [debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["70e1e71e-365e-40b5-8583-3ee4ca9b0f20"]
> [debug] [JSONWP Proxy] Proxying [DELETE /session/70e1e71e-365e-40b5-8583-3ee4ca9b0f20] to [DELETE http://localhost:8100/session/D5EE452B-9F1F-46CF-9FEE-A9C985D66532] with no body
> [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"C31B4631-ED70-4722-ACC7-C1ACF0B9A843\",\n  \"status\" : 0\n}"
> [XCUITest] Shutting down sub-processes
> [XCUITest] Shutting down xcodebuild process (pid 1740)
> [XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
> [XCUITest] Shutting down Logger process (pid 1745)
> [XCUITest] System log exited with code '0'
> [XCUITest] Shutting down iproxy process (pid 1756)
> [XCUITest] iproxy exited with code 'null'
> [debug] [XCUITest] Running ios real device reset flow
> [debug] [XCUITest] Resetting simulator
> [debug] [iOSLog] Stopping iOS log capture
> [Appium] Removing session 70e1e71e-365e-40b5-8583-3ee4ca9b0f20 from our master session list
> [debug] [MJSONWP] Received response: null
> [debug] [MJSONWP] But deleting session, so not returning
> [debug] [MJSONWP] Responding to client with driver.deleteSession() result: null
> [HTTP] <-- DELETE /wd/hub/session/70e1e71e-365e-40b5-8583-3ee4ca9b0f20 200 367 ms - 76 
> 

## Code To Reproduce Issue 
```

  DesiredCapabilities capabilities = new DesiredCapabilities(); 
        driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        System.out.println("DRIVER" + driver);

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> contextNames = driver.getContextHandles();
        for (String contextName : contextNames) {
            System.out.println(contextNames); //prints out something like NATIVE_APP \n WEBVIEW_1
        }
        driver.context((String) contextNames.toArray()[1); // java.lang.ArrayIndexOutOfBoundsException: 1
        System.out.println(driver.context((String) contextNames.toArray()[1]));

```

**Comment by mykola-mokhnach** [comment]
Can you try java_client 4.1.2?
https://mvnrepository.com/artifact/io.appium/java-client/4.1.2

Also try _autoWebview_ capability.

**Comment by fnkbz** [comment]
i tried with java client 4.1.2 same error  java.lang.ArrayIndexOutOfBoundsException: 1
Then i set autoWebview capability to true. The exception is not thrown because a loop for finding webviews is executed  but it cannot find any webviews.

### Server Logs 

> 
> 
> [debug] [iOS] Retrieving contexts and views
> [debug] [iOS] Selecting by url: false 
> [debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
> [debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
> [debug] [RemoteDebugger] Page element JSON: []
> [debug] [iOS] No web frames found.
> [iOS] Could not find any webviews yet, refreshing

**Comment by mykola-mokhnach** [comment]
@imurchie I'm out of ideas. Do you know why Appium might not detect a webview?

**Comment by imurchie** [comment]
If `ios-webkit-debug-proxy` isn't returning any web frames, there is not much that can be done. Is anything in the logs from iwdp?

**Comment by fnkbz** [comment]
@imurchie , just wi.recv_packet  / wi.send_packet information int the iwdp logs. But today something weird happened. Without changing anything in my code, appium found the webview. The only thing that i did is restart my laptop. Then i started the server with the autowebview flag enabled. I didn't re-change the java-client version. I left the 4.1.2 as @mykola-mokhnach suggested at my pom.xml. Do you now if this behaviour is random?

**Comment by jlipps** [comment]
Unfortunately, Apple's software is so unstable that sometimes a restart is indeed what fixes an issue.
