### ISSUE TITLE
https://github.com/appium/appium-ios-driver > Commands section is outdated

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#7738]
## The problem

https://github.com/appium/appium-ios-driver > Commands section is outdated
some of the methods mentioned here are no more valid.
This is confusing to new users.

May be we can remove this section and replace with 
http://appium.github.io/java-client/io/appium/java_client/ios/IOSDriver.html#method.summary

I guess above page is updated each for after new build is created.

**Comment by jlipps** [comment]
@vikramvi the commands section are the commands which are available if you were to import `IOSDriver` as a node library, not use it from a client perspective. This is a reference for developers of the `appium-ios-driver` library, not a reference for Appium users. The commands are still correct in this sense. Appium users should at this time be reading the main (appium/appium) repo's docs only, not docs on specific driver repos.
