### ISSUE TITLE
Appium will not launch my real device

### ISSUE THREAD

**Issue by stjean33** [appium/appium#7739]
## The Problem

During set I can run my appium doctor 'no errors', I am able to setup my iphone 6s plus to Xcode, and my capabilities are set in my ide...When I run my ide my appium executes but does not want to connect to my real device. 
## Environment

* Appium version 1.5
* Desktop OS/version 10.12.2
* Real device  iphone 6s plus
* xcode version 8
* IDE intellij

**Comment by imurchie** [comment]
Appium 1.5 will not work with Xcode 8/iOS 10. You will need to upgrade to 1.6 at least.

**Comment by vikramvi** [comment]
@stjean33 https://medium.com/@chenchaoyi/the-options-of-inspecting-ios-10-app-with-appium-1-6-534ba166b958#.ni3nhz70t 

https://vikramviknowledgesharing.wordpress.com/2017/01/01/appium-mobile-automation/

@triager please close as this is query and not a bug
