### ISSUE TITLE
add access to WDA's homescreen press method

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7741]
WDA has now given access via `/wda/homescreen` to homescreen press functionality. This is different from `deactivateApp` since it is more about the button press and less about deactivating the app and bringing it back. There are a couple options for implementing this:

* extend `deactivateApp` with a parameter that clarifies we don't want to bring the app back
    * maybe `deactivateApp(0)`
    * maybe add a JSON param `deactivateApp({permanent: true});`
* re-tool the inner logic of `closeApp` to simply press the homescreen button instead of kill WDA (which is the current behavior). this would be a breaking change but i'm guessing more users would appreciate this behavior anyway.
* add a new endpoint to appium that we then build into all the clients as well. Downside is that's a lot of work and we already have similar things. Upside is we may also be adding a double-tap homescreen press (https://github.com/facebook/WebDriverAgent/issues/461), so if we have a couple things like this, maybe having one endpoint with two modes makes more sense. (Or we could add another JSON param to `deactivateApp`).

**Comment by mykola-mokhnach** [comment]
This feature might be pointless if there are no methods to interact with onscreen elements after homescreen button is clicked.

**Comment by jlipps** [comment]
@mykola-mokhnach why wouldn't you be able to interact with them?

**Comment by midopa** [comment]
It's very useful for cross-application automation. There are flows where you need to go to the Settings app (or any other system app) to tweak something that your app may interact with.

Fortunately, XC UI Test driver still works even if you leave the app-under-test. If I run a simulator in debug mode, press the home shortcut, I can query and interact with all the elements seen on the home screen and other apps.

**Comment by mykola-mokhnach** [comment]
@jlipps because I had problems while interacting with other apps. Anyway, if this works properly then having _deactivateApp_ with zero duration looks good to me and might be the easiest way to have it immediately available in clients (java-client, python-client, etc.)

**Comment by imurchie** [comment]
I think both should probably be done. 
1. Deprecate the old way (just a number) while adding a magic number for _actually_ doing something else (though I tend to think that `0` might be a valid number for some use cases, so perhaps something that has no meaning now, like `-1`)
2. Adding a new parameter that is the preferred way (like `deactiveApp({timeout: 5000})` and `deactivateApp({permanent: true})`).

**Comment by jlipps** [comment]
Good ideas! I like it. What about this, based on what you guys said:

1. Recognize `-1` as a magic number meaning don't bring the app back.
2. Add recognition of an object with one key, `timeout` in ms. If a number, that's the duration to wait. If it's `null`, never come back, e.g.:

```js
deactivateApp(5); // come back after 5 seconds, show deprecation warning
deactivateApp(-1); // never come back, show deprecation warning
deactivateApp(); // come back after current default time, show deprecation warning
deactivateApp({timeout: 5000}); // come back after 5 seconds
deactivateApp({timeout: null}); // never come back
// deactivateApp(); // eventually, never come back. breaking change though so will need to wait
```

**Comment by imurchie** [comment]
Sounds like a good plan to me!

**Comment by korenevichev** [comment]
Is it available in appium 1.6.4 Beta? What appium version would it provide?

**Comment by mykola-mokhnach** [comment]
@korenevichev yes, the recent beta contains all the necessary stuff to support the call. The PR for java client is still not reviewed

**Comment by korenevichev** [comment]
@mykola-mokhnach could you please give the link to this PR?

**Comment by mykola-mokhnach** [comment]
yw: https://github.com/appium/appium/pull/8048

**Comment by mykola-mokhnach** [comment]
Also, in older client version one could just provide negative duration value to emulate the desired behaviour
