### ISSUE TITLE
Getting an issue xcodebuild code 65

### ISSUE THREAD

**Issue by jglifonea** [appium/appium#7742]
Im trying to automate a web in iOS using safari as browser but I have been encountering this error 3 days ago. Below is my configuration 

DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.2");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone");
capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "Safari");
capabilities.setCapability("app", /Users/mac/Library/Developer/Xcode/DerivedData/SafariLauncher-guflaeaoaburtmhedksjvszbrtkc/Build/Products/Debug-iphoneos/SafariLauncher.app);
capabilities.setCapability("udid", "09254f2e89304784152bd91b2ac03f9e74ecd279");
capabilities.setCapability("automationName", "XCUITest");
capabilities.setCapability("realDeviceLogger", "idevicesyslog");
driver = new IOSDriver(url, capabilities);

I only use the command "appium" on terminal to run the server.

Already build the Safari App on the phone using xCode 8.2

During execution 

[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 37549)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[debug] [XCUITest] WebDriverAgent successfully started after 2681ms
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=09254f2e89304784152bd91b2ac03f9e74ecd279 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [XCUITest] Log file for xcodebuild test: /Users/juliusglifonea/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/16C92343-4E57-456C-96F2-A1BBDCC4B197/Session-WebDriverAgentRunner-2017-01-25_112400-vxs0BY.log
[Xcode] 2017-01-25 11:24:00.473 xcodebuild[37580:2486851] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/juliusglifonea/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fee5e4d2ad0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

[Xcode] 2017-01-25 11:24:00.474 xcodebuild[37580:2486851] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

[Xcode] ** TEST EXECUTE FAILED **

XCUITest] xcodebuild exited with code '65' and signal 'null'
[XCUITest] Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:246:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:205:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 Error: xcodebuild failed with code 65
    at SubProcess.<anonymous> (../../lib/webdriveragent.js:246:25)
    at emitTwo (events.js:106:13)
    at SubProcess.emit (events.js:191:7)
    at ChildProcess.<anonymous> (../../lib/teen_process.js:205:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[debug] [JSONWP Proxy] Proxying [DELETE /session/80559a6f-b0ff-43de-b723-857a681443ec] to [DELETE http://localhost:8100/session/80559a6f-b0ff-43de-b723-857a681443ec] with no body
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: socket hang up
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:127:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session 500 26167 ms - 216 
[HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"app":"appPath","realDeviceLogger":"idevicesyslog","platformVersion":"10.2","automationName":"XCUITest","bundleId":"com.webrage.appium.exist","browserName":"Safari","platformName":"iOS","udid":"09254f2e89304784152bd91b2ac03f9e74ecd279","deviceName":"iPhone"},"requiredCapabilities":{}}}
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id"]} and you sent ["capabilities"]
[HTTP] <-- POST /wd/hub/session 400 6 ms - 171

**Comment by mykola-mokhnach** [comment]
WDA cannot start on the target device. This is, most likely, signing issue.

**Comment by jlipps** [comment]
If you are automating safari, use the browserName capability and do _not_ use an app capability. Appium will figure that out on its own.

But yeah the main problem looks to be some issue with WDA being built or installed. The error message says the file doesn't exist. I'd uninstall Appium, then reinstall, then try again.

**Comment by jglifonea** [comment]
yes for your replies, as of now im re-installing appium as suggested. will keep this updated if issue persists

**Comment by jglifonea** [comment]
so i upgraded my Appium to the latest as of now (1.6.3), and error message changes

[Xcode] Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.

[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.2'

[Xcode] Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.

[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.2'

[Xcode] Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.2'

I think WebDriver Agent also needs to be included in Apple Developer Account. Will keep this updated.

**Comment by ragePowered** [comment]
@jglifonea have this or similar issue today. Got resolved with enabling automatic signing on each target (WebDriverAgentLib, WebDriverAgentRunner, ..., IntegrationApp). Also pay attention to any signing-related errors in Xcode. When all this is reviewed do Product->Clean, and then Product->Build

**Comment by jglifonea** [comment]
@ragePowered yes just did the same thing today. Added the bundleIdentifierId of WebDriverAgentLib to my provisioningProfile (Apple Account) then build it again on my iPhone. 

@jlipps this can be closed now. Thank you!

**Comment by asjadtariq** [comment]
Hi @jglifonea and @ragePowered  I am having same issues, If possible please explain more about steps you did as do not know much about XCODE. Thanks

**Comment by ragePowered** [comment]
@asjadtariq 
1) go to folder where webDriverAgent is located (search under node_modules/appium/node_modules...)
2) open webDriverAgentRunner.xcodeproj
3) on a left side of the screen you will see your project name and bellow its targets
4) on each target (where applicable) go to General tab, Signing section. Check "Automatically manage signing", and pick proper Team id from drop down list
5) when all targets are configured, go to Product -> Clean, and then do Product -> Build

After this manipulations all should be set. If you got any error - create [gist](https://gist.github.com/) for them

**Comment by mmguhe** [comment]
@ragePowered 
I am getting similar issue.
I did build the project successfully but when I run my tests, I am getting the error : 

[Xcode] 
Testing failed:
	Signing for "WebDriverAgentRunner" requires a development team. Select a development team in the project editor.
	Code signing is required for product type 'UI Testing Bundle' in SDK 'iOS 10.2'

[Xcode] ** TEST FAILED **

**Comment by AshrafRizvi01** [comment]
@ragePowered Thank you for the detailed instructions.

**Comment by mohamedrks** [comment]
Appium 1.6.5
Xcode 8.3.2

I am running my tests on ipadAir (10.3.1).I am using jenkins to run my tests while i am running the tests(25 test cases) i can see in the middle of the execution i am getting the following error "[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65"

While test was running when i manually plug the device to another usb port tests starts to run normally.I want to run the tests with a continuos follow without any issues or manual interaction.Any solution for the above issue.

**Comment by mykola-mokhnach** [comment]
@mohamedrks Try https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md or wait until https://github.com/appium/appium-xcuitest-driver/pull/456 is merged into beta.

**Comment by kittu462** [comment]
@jlipps , Is developer account is mandatory to work on safari web browser automation? I am not using any app, just I am using safari browser.

When I run my script on Simulator it's working good but on real device I am getting "Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65" error. I have tried steps mentioned by @mykola-mokhnach but same issue.
