### ISSUE TITLE
Can I execute adb command while using connection to appium server?

### ISSUE THREAD

**Issue by hepilt** [appium/appium#7743]
If I init driver with device udid and send command to adb like 'abd -s udid shell input text some_text' it wouldn't be executed. Can I execute it from driver or try other same ways?

**Comment by jlipps** [comment]
Why isn't it executed? What error do you get? You should be able to execute commands using adb.

**Comment by dmlemeshko** [comment]
@hepilt I have no problems to run adb commands from java code:
```List<String> output = Helper.runCommand("adb -s " + deviceUDID + " shell getprop ro.product.brand")```
Answering your question: you can't run adb commands directly using appium client. I saw a request for such functionality maybe a half year ago and the conclusion was that if there is some specific `adb`  command user want to execute and it is not covered with appium functionality, you have to do it on your own. And it totally makes sense.
Please share the code how you run the command and I think you get help. Next time better to post such questions [here](https://discuss.appium.io/).
