### ISSUE TITLE
Appium 1.6 execute script support

### ISSUE THREAD

**Issue by chenchaoyi** [appium/appium#7748]
From https://github.com/appium/appium-base-driver/blob/master/docs/mjsonwp/protocol-methods.md , both `/wd/hub/session/{sessionId}/execute_async` and `/wd/hub/session/{sessionId}/execute` are marked as implemented.

But it seems they are not implemented in the latest XCtest driver: https://github.com/appium/appium-xcuitest-driver/blob/master/lib/commands/execute.js

Do we have any plan to implement these two endpoints? And shall we put it as a known issues in https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md ?

**Comment by jlipps** [comment]
These are implemented in the only context in which it makes sense for them to be implemented, namely a webview context. There is no such thing as executing javascript in an XCUITest native environment, so there's no way to support it.

I.e., if you want to use these endpoints, you need to be in a webview context. Then they'll work. Thanks!
