### ISSUE TITLE
iOS10 test hangs when application opens another application

### ISSUE THREAD

**Issue by NagyRobertt** [appium/appium#7749]
## The problem

When application navigates to another application (example: clicking on a link which opens Safari) the test run hangs and after a while get timeout issues in the appium log.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MacOS Sierra 10.12.1
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPhone 7 iOS 10.2.1

## Details

During my test there is help button in the application which opens a help page in Safari.
It navigates to the page without a problem. But after that the whole test hangs and after a while it timeouts (See log below). 

## Link to Appium logs

https://gist.github.com/NagyRobertt/7852ee6c7fa057bddcb7c23fdfb37127

Regards,
Robert

**Comment by mykola-mokhnach** [comment]
This might happen because of https://github.com/facebook/WebDriverAgent/issues/372
