### ISSUE TITLE
iOS: After ios app launches, ChromeDriver quits with "Only local connections allowed"

### ISSUE THREAD

**Issue by reuningATL** [appium/appium#7750]
## The problem

I inherited our testing environment that had not been maintained for some time and I have been working on getting it up to date. I finally was able to get the app to launch but right when it closes the alerts I receive a chromedriver error. I was under the impression that chromedriver was only used for android testing so I don't know why this would come up. Our android appium environment is stable.

## Environment

* Appium version: 1.6.3
* Desktop OS: mac 10.12.2
* Node.js version (unless using Appium.app|exe):
* iOS 10.2.1
* iPhone 5s

## Details

This is the error I get after the app launches on the device (excuse the copy and paste):
*****************************************************
 INFO [main] (Log.java:37)- <iOS app> launched
Starting ChromeDriver 2.22.397929 (fb72fb249a903a0b1041ea71eb4c8b3fa0d9be5a) on port 3005
Only local connections are allowed.
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Jan 26, 2017 9:56:48 AM org.openqa.selenium.os.UnixProcess$SeleniumWatchDog destroyHarder
INFO: Command failed to close cleanly. Destroying forcefully (v2). org.openqa.selenium.os.UnixProcess$SeleniumWatchDog@78c8ec7e
******************************************************

## Desired Capabilities

*some info redacted*
caps.setCapability("platformName", "iOS");
caps.setCapability("automationName", "XCUITest");
caps.setCapability("platformVersion", "10.2");
caps.setCapability(MobileCapabilityType.APP, app);
caps.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole" );
caps.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone5s");
caps.setCapability("udid", <udid>);
caps.setCapability("bundleID", "com.mmodal.app");
caps.setCapability("xcodeOrgId", id);
caps.setCapability("xcodeSigningId", "iPhone Developer");

## Link to Appium logs

[gist](https://gist.github.com/reuningATL/f560db98092f0696d01adb8d718bbda2)

**Comment by imurchie** [comment]
There is something wrong with your [gist](https://gist.github.com).

Without the logs it is not clear what is going on. There should be _no_ case in which ChromeDriver is being used in an iOS test.

**Comment by reuningATL** [comment]
Let me work on the logs, I'll update when I get it formatted correctly.

**Comment by reuningATL** [comment]
Update the output gist

**Comment by imurchie** [comment]
That does not look like Appium doing anything, but rather TestNG starting ChromeDriver after the successful session creation on the Appium server.

**Comment by reuningATL** [comment]
Think I found the problem, there is a method to open chrome and navigate to a youtube video to test audio recording. I will have to work on that... Thanks for your help  @imurchie
