### ISSUE TITLE
Command "bootstrap" does not exist.

### ISSUE THREAD

**Issue by Manikanta29** [appium/appium#7752]
OS X : 10.0.2
Appium:1.6.3
Xcode:8.2.1
npm:4.1.1
node:6.9.1

Followed the steps in https://github.com/appium/appium-xcuitest-driver and installed all the external dependencies. 

Navigated to node_modules/appium-xcuitest-driver/WebDriverAgent thorugh terminal 
cmd: mkdir -p Resources/WebDriverAgent.bundle
cmd: sh ./Scripts/bootstrap.sh -d

getting below message: 

IMCHLT191:WebDriverAgent manikantav$ mkdir -p Resources/WebDriverAgent.bundle
IMCHLT191:WebDriverAgent manikantav$ sh ./Scripts/bootstrap.sh -d
-e Fetching dependencies
Error: Command "bootstrap" does not exist.

Please help me.

**Comment by mykola-mokhnach** [comment]
make sure you have correct carthage version installed and available in PATH.

**Comment by pavanbachu0604** [comment]
Check if carthage is installed: brew install carthage
If its already installed, reinstall carthage : brew uninstall -g carthage; brew install carthage
Then link the carthage: brew link carthage

**Comment by Manikanta29** [comment]
I reinstalled appium 1.6.4 beta version and working good.

**Comment by prashantkumar1041** [comment]
Reinstalling & linking Carthage worked out.

Thanks!!

**Comment by mmcintyre123** [comment]
This solved my issue as well.  All I had to do was
`brew uninstall -g carthage; brew install carthage `
Then force the sym links to overwrite the bad link --
`brew link --overwrite carthage`
Thank you!

**Comment by crspybits** [comment]
This did not fix the issue for me. Still having the same error :(.

**Comment by imurchie** [comment]
What version of carthage do you have? What is the output of `carthage version`?

**Comment by crspybits** [comment]
It turns out the fix for me was to move the Appium app to the /Applications folder on my Mac. See also https://github.com/appium/appium/issues/8033. Thanks!

**Comment by edrum** [comment]
Only two things(reinstallation & linking)  i did is 
1. brew uninstall carthage
2.brew install carthage
3.brew link --overwrite carthage
4.restart & try

**Comment by vanessalarkin** [comment]
if you are unable to brew install carthage or sudo brew install carthage (I'm on High Sierra) try using the following to download:
https://github.com/Carthage/Carthage/releases/download/0.30.1/Carthage.pkg
