### ISSUE TITLE
QueryController: Got null root node from accessibility - Retrying...

### ISSUE THREAD

**Issue by Abur73** [appium/appium#7753]
## The problem
When trying to get the elements out of a screen (Android) thru Spy Inspector, the inspector window keeps waiting for an answer (elements to display) eternally. If we move to another screen on the emulator, then that page elements are shown on the spy inspector. If we go back into the "problematic page" then again Spy inspector cannot get out the elements.

Checked for issues alike, and updated appium all the way from 1.4.13 to 1.5.3 then to 1.6.0 and today I tried to 1.6.3. Used first android Emulator with 5.0.0, then tried with 6.0 and all the way up to 7.1.1
But still issue is there.

## Environment
* Appium version (or git revision) that exhibits the issue: Appium 1.6.3 (GUI 1.5.3)
* Last Appium version that did not exhibit the issue (if applicable): all versions have this same issue
* Desktop OS/version used to run Appium: Mac OS 10.11.6
* Node.js version (unless using Appium.app|exe): v.4.3.1
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Android Emulator (AVD)
* Appium CLI or Appium.app|exe: CLI + Appium.app for Spy Inspector

## Details
When above issue happened, tried some other application screens, and there more with the same issue, stopping me from continue automating around 40% of my Test Scripts.
I noticed that when such "stoppage" happens, Appium server tries to get the source out of the screen:
2017-01-26 19:59:36:580 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
2017-01-26 19:59:36:580 - [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source
2017-01-26 20:01:36:566 - [HTTP] <-- GET /wd/hub/session/9f3948b3-0435-4789-92e3-979cbbfaec63/source - - ms - - 
2017-01-26 20:01:36:568 - [HTTP] --> GET /wd/hub/session/9f3948b3-0435-4789-92e3-979cbbfaec63/orientation {}

...and basically stops there.

I checked the logical execution log from the emulator, and I found this was happening:
01-26 19:59:31.340  2920  2932 E QueryController: Got null root node from accessibility - Retrying...

For some reason, emulator seems to be sending something that Appium server does not recognizes.

Needless to say, the elements can be retrieved though, thru uiautomatorviewer. (attached the logcat when launching elements locator)

## Link to Appium logs
AppiumLog:
<script src="https://gist.github.com/Abur73/c771d234d3edb8736a29101502d14865.js"></script>

Logcat.log
<script src="https://gist.github.com/Abur73/3af0b286f62a054b38993362a245ed62.js"></script>

uiautomatorviewerLogcat.log
<script src="https://gist.github.com/Abur73/039dcfd10f299bbb874a8b9e2e0bae41.js"></script>

## Code To Reproduce Issue [ Good To Have ]
No code used, just prior to that when trying to get the elements out from the screen.

**Comment by mykola-mokhnach** [comment]
GUI inspector is not supported anymore.
