### ISSUE TITLE
iOS: With latest version of xcuitest-driver no client reset happens

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#7754]
## The problem
With latest xcuitest-driver **v2.5.4**  client does not reset with (previous version working as expected):
**Reset without uninstall**
```
capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
capabilities.setCapability(MobileCapabilityType.NO_RESET, false);
```

Reset happens only with:
**Reset with uninstall**
```
capabilities.setCapability(MobileCapabilityType.FULL_RESET, true);
capabilities.setCapability(MobileCapabilityType.NO_RESET, false);
```

**Comment by imurchie** [comment]
What is the behavior you are expecting from having both false?

**Comment by amedvedjev** [comment]
Client starting as fresh install. Now first case working same as:
```
                    capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
                    capabilities.setCapability(MobileCapabilityType.NO_RESET, true);
```

changing "NO_RESET" does not effect anything.

**Comment by jlipps** [comment]
You can't use fullReset and noReset together. You should either:

1. Use nothing (the default case)
2. Use fullReset (sometimes does some extra cleanup if possible)
3. Use noReset (does less cleanup than the default case)

It's not surprising that combining fullReset and noReset leads to weird behaviors. Maybe we should just fail a test immediately if someone tries to do this.

**Comment by amedvedjev** [comment]
@jlipps maybe you right! but i used it from beginning 2+ years without changes for iOS and Android.
so what is best config? Pls correct if i am wrong:
**Reset with uninstall old client and install new one**
`capabilities.setCapability(MobileCapabilityType.FULL_RESET, true);`
**Reset without uninstall old client**
`capabilities.setCapability(MobileCapabilityType.NO_RESET, false);`
**Normal start**
`//nothing`

**Comment by jlipps** [comment]
The full list of things that fullReset does should probably be documented. But it's like this:

noReset -- do some small number of things to clean up
_normal_ -- do the things noReset does, plus some other things
fullReset -- do the things _normal_ does, plus even more things

So for Android I think the normal case may uninstall the app and reinstall it, for example.

But I think we should maybe document what happens in each of these cases, so people know.

**Comment by amedvedjev** [comment]
anyway "noReset" does not work any more as it worked before. now it does clean up only on driver quit.

**Comment by jlipps** [comment]
@amedvedjev oh you're talking about something other than driver.quit? That is what we designed the reset scenarios to handle. Is there a reason you don't want to just use different sessions? I understand maybe things have changed since a while ago, but we've made so many sweeping changes in Appium it might be hard to track them down. FWIW, I don't really like `closeApp` and the rest.

**Comment by amedvedjev** [comment]
@jlipps yes! not only quit. i have 3 group of tests:
1 initial install and update client on test device. used fullReset. one first test only.
2 tests that need FULL client reset cause it settings may affect next text. used NO_RESET=false. some tests about 10-15.
3 tests that may start with any client state. most of tests.

**Comment by jlipps** [comment]
@amedvedjev I still don't understand why you can't have 1 test per session though?

**Comment by amedvedjev** [comment]
i have 1 per session. but i just like idea when reset working always before test not after when by some reason driver.quit will fail/not start/whatever.

**Comment by amedvedjev** [comment]
with Android client it is continues correctly. Reset happens on driver START not QUIT

**Comment by jlipps** [comment]
@amedvedjev when you select fullReset, it does the cleaning on session start, not just session end, doesn't it? Or maybe that logic somehow got lost in the rewrite.

**Comment by amedvedjev** [comment]
fullReset - continues to work correctly on start, not end for both iOS and Android.

**Comment by imurchie** [comment]
Yes, we appear to have missed the reset logic on session start. Testing out with it added.

**Comment by amedvedjev** [comment]
latest 1.6.4-beta.
Reset without uninstall old client
capabilities.setCapability(MobileCapabilityType.NO_RESET, false);

cause to uninstall application on simulator after driver.quit()... why?

**Comment by imurchie** [comment]
I don't see that happening. Do you have logs for this run so I can see what is going on?

**Comment by amedvedjev** [comment]
here is gist (name of app is removed) - https://gist.github.com/amedvedjev/d77b77181e48b74393cddb4ccd545aed
after this i am trying to open simulator manually. first try i see it black screen and nothing happens. closing simulator softly with menu option quit. open again. application is absent.

**Comment by imurchie** [comment]
Ok. I see it happening. But this is the same behavior as iOS has always had.

**Comment by amedvedjev** [comment]
and what the difference with fullReset if we totally remove everything?

**Comment by imurchie** [comment]
Indeed. That is a good question. 

First part in rectifying this: https://github.com/appium/appium-ios-simulator/pull/88

**Comment by QAutomatron** [comment]
I also noticed that for iOS device with `fullReset=true`, app is reinstalled ok before each test, but `Location Service` permission remains saved until i do a manual uninstall. Is it same issue or a new one?

**Comment by imurchie** [comment]
That is a different issue. And one that will slow things down considerably. The problem: for `fullReset` to _actually_ delete the app in the normal way the simulator needs to be booted. And to clean the rest of the simulator, it needs to be shut down. So for both to happen the sim needs to be booted up, delete the app, then shut down to delete the sim state. Then booted to run the test. 

On my (quite fast) machine, this is the difference between 55 second test and a 2 minute test.

**Comment by amedvedjev** [comment]
@imurchie tried "1.11.0" version .... and did not notice changes... it still does not reset on start and removing app on quit...  [quit.driver](https://gist.github.com/amedvedjev/4fb96e593e86dbe21986d264eb7b0f40)

**Comment by imurchie** [comment]
That is to be expected. That is a **first** step. I'm wiring it into the driver now. As it stands it makes no difference.

**Comment by amedvedjev** [comment]
latest try again and looks more lucky! more over now start time decreased nicely on mine machine (in sec): 
                     Was   Now
Full start        81     75
Fast Reset     47     27 (only sometimes 47 by some reason)
Normal           16     16

**Comment by vikramvi** [comment]
@jlipps Per your comment https://github.com/appium/appium/issues/7754#issuecomment-275802436, didn't find any reference to `normal` under https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/reset-strategies.md nor https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md, 
can you please clarify what does this term means ?
