### ISSUE TITLE
Locale/language support for launching apps in XCUITests

### ISSUE THREAD

**Issue by crummy** [appium/appium#7755]
It seems there's a way to add locale and language arguments when launching an iOS app. We've implemented this in our own modified version of an app launcher forked from FBSimulatorControl code to verify it works. Implementing this on Appium would involve either using our app launcher, or modifying webdriveragent, and then passing the arguments through to them.

Here's our changed code from FBSimulatorControl's launch method:

```
NSMutableArray *args = [NSMutableArray new];
    if (language) {
        [args addObjectsFromArray:@[@"-AppleLanguages", [NSString stringWithFormat:@"(%@)", language]]];
        [args addObjectsFromArray:@[@"-NSLanguages", [NSString stringWithFormat:@"(%@)", language]]];
    }
    if (locale) {
        [args addObjectsFromArray:@[@"-AppleLocale", locale]];
    }
	    
    FBApplicationLaunchConfiguration *appLaunch = [FBApplicationLaunchConfiguration
                                                   configurationWithBundleID:bundleId
                                                   bundleName:bundleId
                                                   arguments:args
                                                   environment:@{}
                                                   options:0];
```

@jlipps Happy to provide additional information if you'd like.

**Comment by mykola-mokhnach** [comment]
There is a possibility to pass command line parameters to application under test:

```java
final List<String> processArgs = new ArrayList<>(Arrays.asList(
....
);
final JSONObject argsValue = new JSONObject();
argsValue.put("args", processArgs);
capabilities.setCapability("processArguments", argsValue.toString());
```

 Is it what you need?

**Comment by crummy** [comment]
That's great, I didn't know about that. In that case, if we already have the ability pass args to the app under test, it should only be necessary to catch the existing locale and language Appium capabilities and add them as arguments.

**Comment by dpgraham** [comment]
[Link to TestObject fix using WDA processArguments](https://github.com/testobject/product/blob/master/org.testobject.runtime/devices/src/main/java/org/testobject/runtime/devices/pool/server/provisioning/ios/AppiumServerIos.java#L201) (private link)

**Comment by dpgraham** [comment]
@crummy @mykola-mokhnach There's 2 capabilities called `locale` and `language`.

Is the idea for this that `locale` and `language` would get passed into the WDA arguments called `AppleLanguages`, `NSLanguages` and `AppleLocale`?

**Comment by crummy** [comment]
That's right, that's how we do it.
