### ISSUE TITLE
Android: Driver capability errors are not correct

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#7759]
## The problem

[AndroidDriver] Error: The desired capabilities must include either an app, **package** or browser

Actually it is waiting for "appPackage".

Same with "activity" -> "appActivity"

**Comment by imurchie** [comment]
Can you provide more information? What version of Appium is this? What are the desired capabilities being sent in?

**Comment by amedvedjev** [comment]
latest 1.6.3 with --no-shrinkwrap

**Comment by imurchie** [comment]
Got it.
