### ISSUE TITLE
iOS screenshotting sometimes fails

### ISSUE THREAD

**Issue by imurchie** [appium/appium#7762]
## The problem

Some users are having issues with iOS screenshot, where they timeout or are generally slow through Instruments.

`simctl` provides a way to do screenshots. We should add access to it to `node-simctl`, and then add a capability to bypass normal screenshots and use the other version.

If the sim's udid is `1CFAC022-4ADB-4514-B448-6F0A6EF2C453` then the command
```
xcrun simctl io 1CFAC022-4ADB-4514-B448-6F0A6EF2C453 screenshot <file>
```
will produce a `png` screenshot wherever "file" points.

Cc: @albedith

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 6
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/imurchie/82d56e4776034cba44d7eabd184532f6

**Comment by jlipps** [comment]
good idea

**Comment by mykola-mokhnach** [comment]
I think the 'screenshot' option is only available for simctl after XCode release 8.1

**Comment by mykola-mokhnach** [comment]
Correct me if I'm wrong, but we were using the following objc tool to take simulator screenshots for instruments-based Appium (the tool should be executed via Teminal, and the Terminal should be authorised for UI access in Mac OS prefs):

```objc
#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>

int getSimWindowPid() {
    @autoreleasepool {
        NSArray *windowInfos = (__bridge_transfer NSArray*)CGWindowListCopyWindowInfo(kCGWindowListOptionAll, kCGNullWindowID);
        int result = 0;
        for(NSDictionary *windowInfo in windowInfos) {
            NSString* windowName = windowInfo[(__bridge NSString*)kCGWindowName];
            NSString* windowOwnerName = windowInfo[(__bridge NSString*)kCGWindowOwnerName];
            if ([windowName containsString:@"iOS"] && [[windowOwnerName lowercaseString] containsString:@"simulator"]) {
                return [windowInfo[(__bridge NSString*)kCGWindowNumber] intValue];
            }
        }
        return result;
    }
}

#define TOP_BAR_HEIGHT 22

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        if (argc < 2) {
            NSLog(@"Usage: simshot <path_to_result_png_screenshot>");
            return -1;
        }
        int simWindowPid = getSimWindowPid();
        if (simWindowPid <= 0 ) {
            return -1;
        }
        CGImageRef img = CGWindowListCreateImage(CGRectNull, kCGWindowListOptionIncludingWindow, simWindowPid, kCGWindowImageBoundsIgnoreFraming);
        size_t currentWidth = CGImageGetWidth(img);
        size_t currentHeight = CGImageGetHeight(img);
        // Remove the top window bar from the screenshot
        img = CGImageCreateWithImageInRect(img, CGRectMake(0, TOP_BAR_HEIGHT, currentWidth, currentHeight - TOP_BAR_HEIGHT));
        NSMutableData *imgData = [[NSMutableData alloc] init];
        CGImageDestinationRef imgDest = CGImageDestinationCreateWithData((__bridge CFMutableDataRef)imgData, kUTTypePNG, 1, NULL);
        CGImageDestinationAddImage(imgDest, img, NULL);
        BOOL finalizeRes = CGImageDestinationFinalize(imgDest);
        if(!finalizeRes) return -1;
        
        NSString *dstPath = [NSString stringWithUTF8String:argv[1]];
        if (![imgData writeToFile:dstPath atomically:YES]) {
            return -1;
        }
    }
    return 0;
}

```

**Comment by imurchie** [comment]
Yeah, it's not available. Ugh. The whole 'io' task is not there.

**Comment by jlipps** [comment]
this fix has been published in the xcuitest driver
