### ISSUE TITLE
Investigate W3C/mobile spec touch action section, and make preliminary roadmap for implementation

### ISSUE THREAD

**Issue by imurchie** [appium/appium#7763]
We need to eventually implement the specification for interactions with the device. It is in flux now, and the standard we _did_ implement is no longer there. But moving forward we ought to work in such a way as to minimize the changes necessary to both the server and clients.

1. W3C Spec: 
2. Mobile Spec: the [mobile spec](https://github.com/SeleniumHQ/mobile-spec/blob/master/spec-draft.md#touch-gestures) needs work. Figure out what this "Multi-Action API pioneered by Mozilla" is, and perhaps get in the ground floor for any necessary modifications.

**Comment by dpgraham** [comment]
@mykola-mokhnach is working on the implementations right now. We can track it on this issue.

**Comment by mykola-mokhnach** [comment]
The implementation is done for UIA2/Espresso and XCUITest drivers
