### ISSUE TITLE
add event timing framework to appium

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7768]
Appium CI and cloud services like Sauce are interested in tracking Appium startup time and other similar timings, to monitor Appium performance, etc... Individual users may even be curious about this themselves, and it would certainly help in our debugging process. Using `--log-timestamp` we can extract certain timing information from our logs, but I think the time has come for a more substantive solution.

What we need is (a) a standardized way for drivers to report timing events to Appium, and (b) a standardized way for Appium clients to retrieve that data.

In terms of reporting timing events to Appium, my proposal is simply that we add functionality to `BaseDriver` which allows drivers to log events, for example, `XCUITestDriver` could use code like:

```js
this.logEvent('wdaBuildStart');
// ...
this.logEvent('wdaBuildFinish');
```

These events would be added to a hash of events for the session, with timestamps associated.

In terms of clients retrieving the data, we have a lot of different approaches to choose from:

1. Log the events and times to the console in a standard format that could be parsed by someone streaming the Appium log
2. Create a new endpoint like `/session/:sessionid/timings` that returns the JSON timing hash
3. Utilize an existing endpoint to stick the timings in. Reasonable candidates include:
    * A: `POST /session`: return the hash back in the new session response
    * B: `GET /status`: decorate this response with an object like:
        ```js
        {
            ...,
            timings: {
                session12341234: {
                    wdaBuildStart: 1013401050760,
                    wdaBuildFinish: 1013401050780,
                }
            }
         }
         ```
         
    * C: `GET /session/:sessionid`: decorate the capabilities returned by the server for a given session with any existing timing info for that session
    * D: `DELETE /session/:sessionid`: add a JSON response to `driver.quit()` which are all the timings collected before the session ended
     
My favorite out of all of these events is 3C, because:
* We get structured data, not simply log text
* We reuse an existing endpoint which means no new client work
* We don't risk messing up clients which expect certain responses (decorating desired capability response is pretty safe)
* We're not tied to one particular moment in a session lifecycle (new session or delete session; what if the session crashes and we never get a chance to quit?)
* We don't require the client to remember the session ID to retrieve it from a response to `GET /status`; they can just use `driver.sessionInfo()` or whatever it is.

In addition of course I think we _should_ log timings to the console.

Anyway, looking for some feedback from @imurchie and I think @pamepros will also be interested.

**Comment by imurchie** [comment]
I like this idea, and agree with your reasoning and choice of `3C` as the best option. Two things I would add:
1. I think this should be behind a desired capability so that on the off-chance that some client is affected by it or doesn't want the information for some reason. If it is opt-in, current setups will not be affected. This desired capability could be a combination of a boolean to turn it on and a list of events that are cared about.
2. The base driver should record the basic information for all requests (session creation timing, each command timing, etc.).

**Comment by jlipps** [comment]
Yes, agree with your ideas, Isaac.
