### ISSUE TITLE
Unable to see the buttons on a header while inspecting element through Appium Inspector

### ISSUE THREAD

**Issue by GopalakrishnaNagam** [appium/appium#7769]
## The problem

When I am trying to inspect an element through Appium Inspector , contents are displaying but the buttons on the Header are not displaying

## Environment

* Appium version (or git revision) that exhibits the issue: Appium Version 1.4.13 (Draco)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OS X EI Capitan 10.11.6 
* Real device or emulator/simulator: Simulator 9.1

## Details

XCode version : 7.1
Appium Version : 1.4.13 (Draco)

Previously for the above mentioned versions my scripts used to work ,after that I upgraded to XCode 8 and Appium 1.6.2 . As I am facing some issues with  XCode 8 and Appium 1.6.2, I deleted the upgraded versions and reinstalled the older versions only (XCode version : 7.1 / Appium Version : 1.4.13 (Draco)). Once I ran the scripts some scripts are getting failed and on seeing the logs it says that eg : unable to tap on Edit / Save / Delete buttons.So I manually tried to inspect the element, the page is getting loaded , but the buttons are not displaying in the Inspector screen.

Kindly let me know how to proceed on this.

<img width="1440" alt="screen shot 2017-01-28 at 1 52 23 pm" src="https://cloud.githubusercontent.com/assets/23022325/22395345/b692b190-e560-11e6-9443-1a17c04a4a82.png">

**Comment by mykola-mokhnach** [comment]
Sorry, this inspector is deprecated and not supported anymore. We are currently working on a new cross-platform implementation.
