### ISSUE TITLE
Appium - 1.6.3 issue

### ISSUE THREAD

**Issue by danubiapaiva** [appium/appium#7771]
Good night, I have the problems:

[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\danub\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","192.168.104.101:5555","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\danub\AppData\Local\Android\android-sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","192.168.104.101:5555","shell","am","force-stop","io.appium.unlock"]
[debug] [Logcat] Stopping logcat capture
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[Appium] Removing session fa94520e-3e37-42b3-b0f0-9877868a1f16 from our master session list
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/fa94520e-3e37-42b3-b0f0-9877868a1f16 200 1599 ms - 76
[HTTP] --> POST /wd/hub/status/session {"capabilities":{"desiredCapabilities":{"app":"D:\\Automacao\\Banestes.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}},"desiredCapabilities":{"app":"D:\\Automacao\\Banestes.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /wd/hub/status/session 404 3 ms - 64
[HTTP] --> POST /wd/hub/status/session {"desiredCapabilities":{"app":"D:\\Automacao\\Banestes.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /wd/hub/status/session 404 2 ms - 64
[HTTP] --> POST /wd/hub/status/session {"capabilities":{"desiredCapabilities":{"app":"D:\\Automacao\\Banestes.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}}}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /wd/hub/status/session 404 2 ms - 64

**Comment by mykola-mokhnach** [comment]
'No route' error means you didn't set appium server url in capabilities or it is unreachable

**Comment by jlipps** [comment]
`/wd/hub/status/session` is not a valid API URL. How are you constructing these?

**Comment by Gurupaartha** [comment]
Hi @jlipps 

I am facing the same issue. 

Please let me know once you find a solution for it.

**Comment by eliassal** [comment]
I am facing the same issue. I have a very simple basic test as follows

```
DesiredCapabilities appCapabilities = new DesiredCapabilities();
appCapabilities.SetCapability("app", @"C:\Windows\System32\notepad.exe");
NotepadSession = new WindowsDriver<WindowsElement>(new Uri("http://127.0.0.1:4723"), appCapabilities);
NotepadSession.FindElementByClassName("Edit").SendKeys("This is some text");

```
 I am sure that appium is listening as i did a telnet to 127.0.0.1 port 4723, The message in the appium server log is
No route found. Setting content type to 'text/plain'

in the Testmethod error log in Visual studio the message is

> Message: Test method CodedUIAppium.CodedUITest1.EditorEnterTextLocal threw exception: 
> OpenQA.Selenium.WebDriverException: Unexpected error. The URL '/session' did not map to a valid resource
> 

Again, typing in the windows  run dialogbox 

> C:\Windows\System32\notepad.exe

notepad opens without any issue. What is missing?

**Comment by pankajigec26** [comment]
I was able to resolve it by removing comments .

e.g .

I was doing this in robotframework , my script was looking something like this when i encountered this error

```
*** Variables ***
${Device_name}  GDG59YE03161    #Device id
${Appium_server}  http://localhost:4723/wd/hub   #server 
${appPackage}  com.android.dialer  # App package
${appActivity}  com.android.dialer.DialtactsActivity #App Activity
${platfrom}  4.4
${automationName}  uiautomator2
```
'#' symbol which i used to start commenting was causing this issue, once i removed it the issue got resolved

so the new code looks like below

```
*** Variables ***
${Device_name}  GDG59YE03161
${Appium_server}  http://localhost:4723/wd/hub
${appPackage}  com.android.dialer
${appActivity}  com.android.dialer.DialtactsActivity
${platfrom}  4.4
${automationName}  uiautomator2
```
