### ISSUE TITLE
Can't tap to buttons in system alerts in landscape mode (WDA 2.6.0)

### ISSUE THREAD

**Issue by dsavchenkov** [appium/appium#7772]
appium ver. : 1.6.3
appium-xcuitest-driver ver. : 2.6.0
env:  iOS 10.2, iPar Air 2

methods: 
driver.find_element_by_id('Allow').click() (Allow it's button in alert)
driver.switch_to.alert.accept()
driver.switch_to.alert.dismiss()

log for tap in alert - https://gist.github.com/dsavchenkov/067b36950c7a90183287ceda25710447

in Portrait mode working correctly 

Problem reproduce only on system alerts(Permissions for Photo, Photo album and other)
Not reproduced on application alerts

**Comment by mykola-mokhnach** [comment]
is it the same if you use driver.switchTo().alert().accept() method to accept an alert?

**Comment by dsavchenkov** [comment]
Don't work
https://gist.github.com/dsavchenkov/9ca34d5e8ee90e5dc774212e08d830a2

python:
driver.switch_to.alert.accept()
driver.switch_to.alert.dismiss()

**Comment by dsavchenkov** [comment]
UPDATE
i checked on iPhone:
hide keyboards - works
tap to buttons in alert - works

**Comment by mykola-mokhnach** [comment]
@dsavchenkov Can you try to apply this [patch](https://github.com/facebook/WebDriverAgent/pull/470) to you local WDA source and restart your test?

**Comment by mykola-mokhnach** [comment]
Also there is a "universal" workaround where you can change display orientation to portrait before accepting an alert and then change it back.

**Comment by mykola-mokhnach** [comment]
This is how the stuff is currently implemented in our framework:

```java
public void handleAlert(AlertAction action, Timedelta timeout) throws Exception {
        final Optional<String> initialAlertText = readAlertText(timeout);
        if (initialAlertText.isPresent()) {
            int retry = 0;
            do {
                try {
                    // Workaround for https://github.com/facebook/WebDriverAgent/issues/300
                    boolean wasLandscape = false;
                    if (getDriver().getOrientation() == ScreenOrientation.LANDSCAPE) {
                        getDriver().rotate(ScreenOrientation.PORTRAIT);
                        wasLandscape = true;
                    }
                    switch (action) {
                        case ACCEPT:
                            getDriver().switchTo().alert().accept();
                            break;
                        case DISMISS:
                            getDriver().switchTo().alert().dismiss();
                            break;
                        default:
                            throw new IllegalArgumentException(
                                    String.format("Illegal alert action '%s'", action.name())
                            );
                    }
                    if (wasLandscape) {
                        getDriver().rotate(ScreenOrientation.LANDSCAPE);
                    }
                } catch (WebDriverException e) {
                    // ignore silently
                }
                final Optional<String> currentText = readAlertText(Timedelta.fromSeconds(1));
                if (!currentText.isPresent() || !currentText.get().equals(initialAlertText.get())) {
                    return;
                }
                retry++;
            } while (retry < MAX_ALERT_HANDLING_RETRIES);
            if (retry < MAX_ALERT_HANDLING_RETRIES) {
                return;
            }
        }
        throw new IllegalStateException(
                String.format("No alert has been shown after %s or it cannot be %s after %s retries",
                        timeout.toString(),
                        (action == AlertAction.ACCEPT) ? "accepted" : "dismissed",
                        MAX_ALERT_HANDLING_RETRIES)
        );
    }
```

**Comment by dsavchenkov** [comment]
@mykola-mokhnach 
>>> dr.driver.switch_to.alert.dismiss()
>>> dr.driver.switch_to.alert.accept()

These functions are working with patch now. Good ;)

**Comment by jlipps** [comment]
@dsavchenkov so is this issue resolved with the patch? @mykola-mokhnach if not, could it be the X/Y exchanged values issue?

**Comment by mykola-mokhnach** [comment]
@jlipps no, you cannot simply exchange x and y to fix the stuff here. The problem here is, that XCTest "distorts" element coordinates differently in non-portrait mode if system alert is visible in comparison to how it is doing it if such alert is not visible.

**Comment by dsavchenkov** [comment]
@mykola-mokhnach , @jlipps Need I create another issue about hide keyboard?

**Comment by mykola-mokhnach** [comment]
yes, it would be better to close this issue and create a new one. Btw, there is no guarantee that patch will be merged to WDA, because it's more like ugly workaround rather then a fix. So I would just recommend to temporarily change device orientation to portrait to handle alerts.

**Comment by dsavchenkov** [comment]
I created a separate issue about hide keyboard.
@mykola-mokhnach , is problem related only to the system alerts?

**Comment by mykola-mokhnach** [comment]
it seems like. You can investigate it deeper if you have time.

**Comment by dsavchenkov** [comment]
ok, thanks. if I have more information, I will write in this issue

**Comment by Asyranok** [comment]
I have a more robust example for getting around this issue. 

If you need to dismiss an iOS alert in landscape mode, this method will work for you. It clicks in a square 10x pixels away from the exact center of the screen until hitting the alert. My automation framework is all client side, as unusual as that might sound, so I only need appium to dismiss device level alerts. After that, I do not need something to instantly detect and break from this loop. So adjust this code for that behavior as necessary. This is Python.

      ```
      # Get screen middle
       dimensions = self.driver.get_window_size()
       middle_width = dimensions["width"] / 2
       middle_height = dimensions["height"] /2
       action = TouchAction(self.driver)
       pixel_additive = 0;
       action.tap(x=middle_width, y=middle_height).perform() # Exact Center.

       try:
           while pixel_additive <= 50:
               # Tap in square of increasing size.
               action.tap(x=middle_width, y=middle_height + pixel_additive).perform()
               action.tap(x=middle_width, y=middle_height - pixel_additive).perform()
               action.tap(x=middle_width + pixel_additive, y=middle_height).perform()
               action.tap(x=middle_width - pixel_additive, y=middle_height).perform()
               action.tap(x=middle_width + pixel_additive, y=middle_height + pixel_additive).perform()
               action.tap(x=middle_width - pixel_additive, y=middle_height - pixel_additive).perform()
               action.tap(x=middle_width + pixel_additive, y=middle_height - pixel_additive).perform()
               action.tap(x=middle_width - pixel_additive, y=middle_height + pixel_additive).perform()
               pixel_additive += 10
       except BaseException as e:
           log(str(e))
```
