### ISSUE TITLE
UIAutomator2 finds alls elements VISIBLE inside ViewPager

### ISSUE THREAD

**Issue by ptsiakos77** [appium/appium#7773]
## The problem

Appium 1.6.3
automationName: uiautomator2

I have in myapp a **ViewPager** switching items of same kind by swiping right and left. Let's say I have 3 items.
When I search for VISIBLE elements using locator X (e.g //*[contains(@resource-id,'fragment_evaluation_score')] ), it returns 3 items instead of 1 that is currently visible.

This was not the case withe previous UIAutomator.

It seems that in a such case UIAUtomator2 it messes the element PRESENCE with the element VISIBILITY

**Comment by jlipps** [comment]
Probably @sravanmedarapu should have a look at this, maybe there's some way to address it if the underlying behavior hasn't just changed.

**Comment by ptsiakos77** [comment]
@sravanmedarapu any ideas about this?

**Comment by sravanmedarapu** [comment]
@ptsiakos77, Can you please share the page source, if you can ?

**Comment by ptsiakos77** [comment]
@sravanmedarapu I will talk to the developers and see if possible

**Comment by ptsiakos77** [comment]
@sravanmedarapu  what part of the code you want, the specific area's ViewPager?

**Comment by sravanmedarapu** [comment]
@ptsiakos77, need page source(`getPageSource()`) of the ViewPager.

**Comment by ptsiakos77** [comment]
@sravanmedarapu 
I attach you the page source
[ViewPager.txt](https://github.com/appium/appium/files/777624/ViewPager.txt)

**Comment by sravanmedarapu** [comment]
@ptsiakos77, Can you please try with appium-uiautomator2-driver v0.2.10 and let me know if it is replicating ?

**Comment by xsveda** [comment]
We have the same problem in our project with **ListView** and **RecyclerView** widgets. No issue present with older UIAutomator.
Appium: 1.6.3
UIAutomator2 driver: 0.2.11
