### ISSUE TITLE
Not sure how to check for Toast messages in Appium 1.6.3

### ISSUE THREAD

**Issue by popandrei** [appium/appium#7774]
According to the change log ([link](https://github.com/appium/appium/releases)), it seems that Appium 1.6.3 has support for checking toast messages, but there is no documentation related to this.

I used appium 1.6.3 and added "uiautomator2" as capability in a java project, but I don't know what should I do further. I tried to read the page source (webDriver.getPageSource) to get the xml of the page, at the exact moment when the toast message appeared, but the xml did not contain "Toast", neither the text inside the toast.

If this helps, I used a Nexus 6P emulator running Android 6.0 (API 23).

**Comment by JaniJegoroff** [comment]
Have you checked this ticket for details: https://github.com/appium/appium/issues/4824
Discussion and unit test examples should help you go forward.

**Comment by adarshem** [comment]
what is the element locator for toast message in Android?

after setting the uiautomator2 as desired capability, which piece of code should find the toast message?

like driver.findElement(By.....);

Kindly provide your comments.

**Comment by wesleyvanderlee** [comment]
I would assume the element locator for Android is: `driver.findElements(By.className("android.widget.Toast"));` although I have not been able to verify this yet.

**Comment by garinchas** [comment]
> I would assume the element locator for Android is: `driver.findElements(By.className("android.widget.Toast"));` although I have not been able to verify this yet.

This solution did not help in my case
