### ISSUE TITLE
QueryController: Got null root node from accessibility - Retrying...

### ISSUE THREAD

**Issue by Abur73** [appium/appium#7775]
## The problem

This issue has been reported on #7753, which was closed due Appium 1.6.3 does not use GUI inspector anymore (no surprise since 1.6.3 is CLI, but followed a comment that we could use the GUI Inspector from 1.5.3 [not running] and CLI running in the background), but the issue happens on several ways, GUI inspector was just one of them, so this bug re-opens this thread (no GUI inspector used whatsoever!!!, so please look deeper into this problem please, we have around 30% of our scripts stalled due to this)

On some screens the elements are not detected, execution stalls and Android Emulator starts replying:
"QueryController: Got null root node from accessibility - Retrying..."
until the execution is manually stopped.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): All experience this issue
* Desktop OS/version used to run Appium: Mac OS 10.11.6
* Node.js version (unless using Appium.app|exe): v4.3.1
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Emulator (Android)
* Appium CLI or Appium.app|exe: Appium CLI 1.6.3

## Details

First time this issue was experienced, it was using Android Emulator 6.0 + Appium 1.4.13.
Performed a search on problems alike, found that issue might be regarding the old version of Appium, so I upgrade it to 1.5.0, then to 1.5.3, then to 1.6.3. All shown this same issue.

Using latest Appium version (1.6.3) found that while running the application, the executions get further using Android 6.0, than when using 7.0/7.1

Originally when using Appium 1.6.3 + Android OS 6.0, executions stopped when getting the page source, on a specific page, that I detected this problem happened:

          System.out.println( driver.getPageSource() );

Now using Appium 1.6.3 + Android 7.0/7.1, execution stalls way before than on Android OS6.0, and it tries to locate an ID which DOES exist, and it was fetched using UiAutomatorViewer. But it just cannot be detected at all by Appium server.

## Link to Appium logs

Log files can be found at:
<script src="https://gist.github.com/Abur73/d525c55395c258300cd6d00a274974e7.js"></script>

Basically, on above link can be found 2 log files on each test:
1) AppiumLog_OS60.txt goes together with AndroidLog_OS60.txt
    This means I have used Appium 1.6.3 and Android OS 6.0 and shows it tries to fetch the page source, but Android just replies back with "QueryController: Got null root node from accessibility - Retrying..."

2) AppiumLog_OS70.txt goes together with AndroidLog_OS70.txt
This means I have used Appium 1.6.3 and Android OS 7.0 and shows it tries to fetch a page element, in fact it is a TextView field, using ID (com.disney.wdpro.dlr:id/tap_to_explore_view). Such ID has been located using both Appium GUI 1.5.3 + CLR 1.6.3 and UiAutomatorViewer, both showed the same ID.
Execution stalls while trying to fetch such ID element. It is worth to mention that this step is successfully executed when using Android 6.0, but with this Android version the executions stalls. Issue also shows: "QueryController: Got null root node from accessibility - Retrying..."

3) AppiumLog_OS71.txt goes together with AndroidLog_OS71.txt
This means I have used Appium 1.6.3 and Android OS 7.1. Same comment as bullet 2).

## Code To Reproduce Issue [ Good To Have ]
          System.out.println( driver.getPageSource() );

**Comment by mykola-mokhnach** [comment]
Try UIAutomation2 backend for Android automation. UIA1 is not supported by Google itself anymore and might eventually stop working in new OS versions.

**Comment by Bert-K** [comment]
I'm facing the same issue
**Environment**
- Appium version (or git revision) that exhibits the issue: 1.6.3
- Last Appium version that did not exhibit the issue (if applicable): All experience this issue
- Desktop OS/version used to run Appium: Windows 10
- Node.js version (unless using Appium.app|exe): v6.9.1
- Mobile platform/version under test: Android
- Real device or emulator/simulator: Real  (Nexus 5X)
- Appium CLI or Appium.app|exe: Appium CLI 1.6.3
- App: Multi Touch Painting Demo
https://play.google.com/store/apps/details?id=com.electricsheep.mtp

**Details**
I can reproduce this problem on Android 7.1 every time with multiple devices and apps, but only on specific pages in those apps.
When the multi touch app gets started, the driver.getPageSource() command works fine. Then I close the initial popup so that only the black background and icons at the bottem are visible.
If I execute the command again on that screen, the driver gives a timeout for the command.
When using wireshark to spy on the usb port, I can see the device returning the error "QueryController: Got null root node from accessibility - Retrying..." repeatedly.
When using uiautomatorviewer, I can retrieve the page source without problems.

The same device on Android 6 with the same app does not produce this error.

**Comment by Bert-K** [comment]
Slightly different error, but sounds like the same cause: #7235

And also linking issue #7274, because I get the reported issue as well with findelement sometimes in android 7 when using the apps I mentioned.

**Comment by bennid** [comment]
I just started seeing this with Android 6.0.  Running against the emulator after the app was installed the first time worked fine.  When running again, it's like the AppiumBootstrap.jar gets stuck, and I only see the errors over and over on an app activity I'm trying to test

`04-07 10:21:00.955  9026  9037 E QueryController: Got null root node from accessibility - Retrying...
04-07 10:21:01.210  9026  9037 E QueryController: Got null root node from accessibility - Retrying...
04-07 10:21:01.462  9026  9037 E QueryController: Got null root node from accessibility - Retrying...
04-07 10:21:01.716  9026  9037 E QueryController: Cannot proceed when root node is null. Aborted search`

I'll try uninstalling the app and re-installing (and maybe restarting the emulator), however I haven't had any issues with this until recently.

More output from before the accessibility output

04-07 10:14:09.393  8737  8737 I AppiumUnicodeIME: onFinishInput
04-07 10:14:09.395  8737  8737 I AppiumUnicodeIME: onStartInput
04-07 10:14:09.446  1607  1626 I ActivityManager: Displayed com.tripadvisor.tripadvisor.prerelease/com.tripadvisor.android.lib.tamobile.activities.CalendarActivity: +265ms
04-07 10:14:09.744  9095  9095 D skia    : Skia Error: Invalid Argument: I got -0.819939 and -0.819939 as radii to SkPath::AddRoundRect, but negative radii are not allowed.
04-07 10:14:09.744  9095  9095 D skia    : Skia Error: Invalid Argument: I got -0.819939 and -0.819939 as radii to SkPath::AddRoundRect, but negative radii are not allowed.
04-07 10:14:09.747  9095  9095 D ViewRootImpl: changeCanvasOpacity: opaque=true
04-07 10:14:09.748  9095  9095 D skia    : Skia Error: Invalid Argument: I got -0.819939 and -0.819939 as radii to SkPath::AddRoundRect, but negative radii are not allowed.
04-07 10:14:09.749  9095  9095 D skia    : Skia Error: Invalid Argument: I got -0.819939 and -0.819939 as radii to SkPath::AddRoundRect, but negative radii are not allowed.
04-07 10:14:09.763  9095  9256 D skia    : Skia Error: Invalid Argument: I got -0.819939 and -0.819939 as radii to SkPath::AddRoundRect, but negative radii are not allowed.
04-07 10:14:09.765  9095  9256 D skia    : Skia Error: Invalid Argument: I got -0.819939 and -0.819939 as radii to SkPath::AddRoundRect, but negative radii are not allowed.
04-07 10:14:09.766  9095  9095 D skia    : Skia Error: Invalid Argument: I got -0.819939 and -0.819939 as radii to SkPath::AddRoundRect, but negative radii are not allowed.
04-07 10:14:09.767  9095  9095 D skia    : Skia Error: Invalid Argument: I got -1.000000 and -1.000000 as radii to SkPath::AddRoundRect, but negative radii are not allowed.
04-07 10:14:09.767  9095  9095 D skia    : Skia Error: Invalid Argument: I got -1.000000 and -1.000000 as radii to SkPath::AddRoundRect, but negative radii are not allowed.
04-07 10:14:09.843  9095  9095 W View    : requestLayout() improperly called by android.support.v7.widget.AppCompatTextView{a06182f V.ED..... ......I. 0,0-0,0 #1020016 android:id/title} during layout: running second layout pass
04-07 10:14:09.844  9095  9095 W View    : requestLayout() improperly called by android.widget.LinearLayout{350ce3c V.E...... ......I. 0,0-0,0} during layout: running second layout pass
04-07 10:14:09.844  9095  9095 D skia    : Skia Error: Invalid Argument: I got -1.000000 and -1.000000 as radii to SkPath::AddRoundRect, but negative radii are not allowed.
04-07 10:14:09.844  9095  9095 D skia    : Skia Error: Invalid Argument: I got -1.000000 and -1.000000 as radii to SkPath::AddRoundRect, but negative radii are not allowed.
04-07 10:14:09.867  9095  9256 D skia    : Skia Error: Invalid Argument: I got -1.000000 and -1.000000 as radii to SkPath::AddRoundRect, but negative radii are not allowed.
04-07 10:14:09.872  9095  9256 D skia    : Skia Error: Invalid Argument: I got -1.000000 and -1.000000 as radii to SkPath::AddRoundRect, but negative radii are not allowed.
04-07 10:14:09.886  9095  9150 E Surface : getSlotFromBufferLocked: unknown buffer: 0xdb5b45a0
04-07 10:14:09.899  1260  1260 W SurfaceFlinger: couldn't log to binary event log: overflow.
04-07 10:14:10.783  9026  9026 I chatty  : uid=0(root) uiautomator expire 54 lines
04-07 10:14:11.298  9095  9095 D ViewRootImpl: changeCanvasOpacity: opaque=false
04-07 10:15:00.072  1260  1294 D hwcomposer: hw_composer sent 262 syncs in 60s
04-07 10:15:00.312  9026  9037 I chatty  : uid=0(root) WatchTimer expire 25 lines
04-07 10:15:01.013  1607  1621 I ActivityManager: Start proc 9583:com.android.deskclock/u0a25 for broadcast com.android.deskclock/com.android.alarmclock.DigitalAppWidgetProvider
04-07 10:15:01.076  9583  9583 W System  : ClassLoader referenced unknown path: /system/app/DeskClock/lib/x86_64

**Comment by VasilijSviridov** [comment]
any update on this ?

**Comment by neapovea** [comment]
I try with new Appium version and have the same error:

- Appium version: 5.0.0-BETA8
- Selenium version: 3.4.0

No news?
ciao.

**Comment by neapovea** [comment]
In the related issue [7235](https://github.com/appium/appium/issues/7235#issuecomment-298919780) have the solution: use  uiautomator2, with this capabilitie:

`capabilities.setCapability("automationName", "uiautomator2");`

Ciao. 
happy coding.

**Comment by VasilijSviridov** [comment]
@neapovea there's another issues with ui2 :/ =) 

Cheers
