### ISSUE TITLE
[Appium 1.6.3] Unable to install SafariLauncher

### ISSUE THREAD

**Issue by JESii** [appium/appium#7776]
## The problem

I'm running real iOS device tests from the command-line using ruby/cucumber and friends. I've followed the appium and apple-ios instructions. I have an enterprise Apple Developer license and have created a profile and installed it on my device.

When trying to run the test:
    `bundle exec cucumber   DEVICE=Iphone -p mobile_website_default APPIUM=TRUE    SITE=MCOM URL=http://m.<testURL>.com/  features/website/Selection/MEW/registry/MCOM/registry_navigation.feature:14`
I get the error:
    `An unknown server-side error occurred while processing the command. Original error: Installing /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app failed (Selenium::WebDriver::Error::UnknownError)`

## Environment

* Appium version (or git revision) that exhibits the issue:
1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
N/A - first time testing
* Desktop OS/version used to run Appium:
OS X ElCap 10.11.6
* Node.js version (unless using Appium.app|exe):
7.4.0
* Mobile platform/version under test:
iOS 9.3.5
* Real device or emulator/simulator:
Real Device
* Appium CLI or Appium.app|exe:
Appium is automatically started by our test framework

Xcode 7.3.1

## Details

The command:
`ios_webkit_debug_proxy -c <Connected device UDID>:27753 –d`
fails to start ios_webkit_debug_proxy

I have specified my UDID via `export UDID=1234567890`

If I run the appium server separately and do not have the framework start it, I get the same error:
    `An unknown server-side error occurred while processing the command. Original error: Installing /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app failed (Selenium::WebDriver::Error::UnknownError)`

Complete gist of the console messages for this test is here: https://gist.github.com/JESii/7a58c9a73573cf67d2dcb6a964111edb#file-appium_1-5-3-consolelog

## Link to Appium logs

https://gist.github.com/JESii/e35b2e25e9d44e821b75e200a7329632#file-appium_1-5-3-log

## Code To Reproduce Issue [ Good To Have ]

Not testing an app; testing a web page through ruby/cucumber

**Comment by pavanbachu0604** [comment]
What is XCode Version you are using ?

**Comment by JESii** [comment]
7.3.1; I'll update the issue

**Comment by JESii** [comment]
Is using https://github.com/budhash/SafariLauncher/ still the recommended way to install SafariLauncher? Or is there another approach now... I see that this repo was last updated in 2013!

**Comment by imurchie** [comment]
The version Appium uses is https://github.com/snevesbarros/SafariLauncher, which is not much less old! But what it does is relatively simple, so updates are rarely needed. And going forward (iOS 9.3+) it is not necessary at all.

But the problem you are facing is one of code-signing. Unfortunately Xcode has changed the way it does stuff and made it _much_ more difficult to automate the signing and installation on real devices.

Could you try the following:
- open `/usr/local/lib/node_modules/appium/node_modules/appium-ios-driver` in Xcode
- use you identity to sign the `SafariLauncher` target (you may need to add a bundle id, in which case use `com.bytearc.SafariLauncher`).
- build and install
- re-run your test

**Comment by JESii** [comment]
thanks, @imurchie  - will try what you suggested.

Also, you said that from iOS9.3+ it is not necessary at all -- that' what I'm using; how do I get around the requirement/error?

**Comment by JESii** [comment]
@imurchie - Xcode refuses to open that folder: 
` Xcode does not support opening folders without a project or workspace.`

**Comment by imurchie** [comment]
Adding this to our backlog. Given recent changes to the signing processes, SafariLauncher needs to be revisited.

**Comment by JESii** [comment]
Thanks... earlier you said no longer needed for iOS9.3+ If that's the case, how would I resolve that?

**Comment by imurchie** [comment]
If you want to give it a shot, Appium 1.6.3 supports XCUITest-based tests for iOS 9.3+. In this scheme SafariLauncher is not needed.

**Comment by JESii** [comment]
OK; I'll give that a shot; thanks!

**Comment by JESii** [comment]
OK; I setup XCUItest, but running my test still is stuck on trying to load SafariLauncher.app -- what should I do to stop that behavior?
