### ISSUE TITLE
Unable to perform Click Action after opening "selendroid-test-app-0.17.0.apk" application

### ISSUE THREAD

**Issue by vsrd13** [appium/appium#7777]
## Unable to perform Click Action after opening "selendroid-test-app-0.17.0.apk" application

Hi Everyone,

I started learning Appium couple of days back using my windows machine.

I got succeed in launching the application(selendroid app) "selendroid-test-app-0.17.0.apk" downloaded from Internet on my AVD device, but I couldn't perform any other Actions like "Click" or "SendKeys" on my AVD. Can someone help me with the real quick solution?
## Environment
Device specifications are in attached screenshot(AVD details.jpg).
**adb version:**
Android Debug Bridge version 1.0.36
Revision 0e9850346394-android
Appium Server Version : 1.4.16.1 

## Details

AVD details are in attached screen shot.

## Link to Appium logs
[> Checking if an update is available
> Update not available
> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --app C:\Users\Kumar\workspace6\Appium\src\selendroid-test-app-0.17.0.apk --platform-name Android --platform-version 23 --automation-name Appium --log-no-color
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"app":"C:\\Users\\Kumar\\workspace6\\Appium\\src\\selendroid-test-app-0.17.0.apk","address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"23","automationName":"Appium"}
> info: Console LogLevel: debug
> Killed Node Server.
> Appium server process ended
> Launching Appium server with command: C:\Program Files (x86)\Appium\node.exe lib\server\main.js --address 127.0.0.1 --port 4723 --app C:\Users\Kumar\workspace6\Appium\src\selendroid-test-app-0.17.0.apk --platform-name Android --platform-version 23 --automation-name Appium --log-no-color
> info: Welcome to Appium v1.4.16 (REV ae6877eff263066b26328d457bd285c0cc62430d)
> info: Appium REST http interface listener started on 127.0.0.1:4723
> info: [debug] Non-default server args: {"app":"C:\\Users\\Kumar\\workspace6\\Appium\\src\\selendroid-test-app-0.17.0.apk","address":"127.0.0.1","logNoColors":true,"platformName":"Android","platformVersion":"23","automationName":"Appium"}
> info: Console LogLevel: debug
> info: --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"app":"C:\\Users\\Kumar\\workspace6\\Appium\\src\\selendroid-test-app-0.17.0.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}},"desiredCapabilities":{"app":"C:\\Users\\Kumar\\workspace6\\Appium\\src\\selendroid-test-app-0.17.0.apk","platformName":"Android","deviceName":"Android Emulator"},"requiredCapabilities":{}}
> info: Client User-Agent string: Apache-HttpClient/4.5.2 (Java/1.8.0_111)
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from desired caps: C:\Users\Kumar\workspace6\Appium\src\selendroid-test-app-0.17.0.apk
> info: [debug] Creating new appium session 8cac2081-3e73-4b5c-a1d1-e97424fec6e1
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_112
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe
> info: [debug] Parsing package and activity from app manifest
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\Kumar\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe
> info: [debug] Extracting package and launch activity from manifest.
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe dump badging C:\Users\Kumar\workspace6\Appium\src\selendroid-test-app-0.17.0.apk
> info: [debug] badging package: io.selendroid.testapp
> info: [debug] badging act: io.selendroid.testapp.HomeScreenActivity
> info: [debug] Parsed package and activity are: io.selendroid.testapp/io.selendroid.testapp.HomeScreenActivity
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device emulator-5554
> info: [debug] Setting device id to emulator-5554
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 wait-for-device
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: Device API level is: 19
> info: [debug] Extracting strings for language: default
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\Kumar\workspace6\Appium\src\selendroid-test-app-0.17.0.apk" "C:\Users\Kumar\AppData\Local\Temp\io.selendroid.testapp" en
> info: [debug] No strings.xml for language 'en', getting default strings.xml
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "C:\Users\Kumar\workspace6\Appium\src\selendroid-test-app-0.17.0.apk" "C:\Users\Kumar\AppData\Local\Temp\io.selendroid.testapp"
> info: [debug] Reading strings from converted strings.json
> info: [debug] Setting language to default
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 push "C:\\Users\\Kumar\\AppData\\Local\\Temp\\io.selendroid.testapp\\strings.json" /data/local/tmp
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\Users\Kumar\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe
> info: [debug] Retrieving process from manifest.
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\build-tools\25.0.2\aapt.exe dump xmltree C:\Users\Kumar\workspace6\Appium\src\selendroid-test-app-0.17.0.apk AndroidManifest.xml
> info: [debug] Set app process to: io.selendroid.testapp
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Checking app cert for C:\Users\Kumar\workspace6\Appium\src\selendroid-test-app-0.17.0.apk.
> info: [debug] executing cmd: java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar" C:\Users\Kumar\workspace6\Appium\src\selendroid-test-app-0.17.0.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning C:\Users\Kumar\workspace6\Appium\src\selendroid-test-app-0.17.0.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\Users\Kumar\AppData\Local\Android\sdk\build-tools\25.0.2\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\build-tools\25.0.2\zipalign.exe -f 4 C:\Users\Kumar\workspace6\Appium\src\selendroid-test-app-0.17.0.apk C:\Users\Kumar\AppData\Local\Temp\117030-5160-1k3udvp\appium.tmp
> info: [debug] MD5 for app is be7e3511e08655587546131ae6eff0c8
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ls /data/local/tmp/be7e3511e08655587546131ae6eff0c8.apk"
> info: [debug] Getting install status for io.selendroid.testapp
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "pm list packages -3 io.selendroid.testapp"
> info: [debug] App is installed
> info: App is already installed, resetting app
> info: [debug] Running fast reset (stop and clear)
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "am force-stop io.selendroid.testapp"
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "pm clear io.selendroid.testapp"
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg io.selendroid.testapp -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] json loading complete.
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":true,"status":0}
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data","status":0}
> info: [debug] dataDir set to: /data
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":false,"status":0}
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 19
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n io.selendroid.testapp/io.selendroid.testapp.HomeScreenActivity"
> info: [debug] Waiting for pkg "io.selendroid.testapp" and activity "io.selendroid.testapp.HomeScreenActivity" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "dumpsys window windows"
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "getprop ro.build.version.release"
> info: [debug] Device is at release version 4.4.2
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId 8cac2081-3e73-4b5c-a1d1-e97424fec6e1
> info: <-- POST /wd/hub/session 303 36598.165 ms - 74 
> info: --> GET /wd/hub/session/8cac2081-3e73-4b5c-a1d1-e97424fec6e1 {}
> info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.4.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"C:\\Users\\Kumar\\workspace6\\Appium\\src\\selendroid-test-app-0.17.0.apk","platformName":"Android","deviceName":"Android Emulator"},"app":"C:\\Users\\Kumar\\workspace6\\Appium\\src\\selendroid-test-app-0.17.0.apk","platformName":"Android","deviceName":"emulator-5554"},"sessionId":"8cac2081-3e73-4b5c-a1d1-e97424fec6e1"}
> info: <-- GET /wd/hub/session/8cac2081-3e73-4b5c-a1d1-e97424fec6e1 200 7.990 ms - 604 {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"4.4.2","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"C:\\Users\\Kumar\\workspace6\\Appium\\src\\selendroid-test-app-0.17.0.apk","platformName":"Android","deviceName":"Android Emulator"},"app":"C:\\Users\\Kumar\\workspace6\\Appium\\src\\selendroid-test-app-0.17.0.apk","platformName":"Android","deviceName":"emulator-5554"},"sessionId":"8cac2081-3e73-4b5c-a1d1-e97424fec6e1"}
> info: [debug] Didn't get a new command in 60 secs, shutting down...
> info: Shutting down appium session
> info: [debug] Pressing the HOME button
> info: [debug] executing cmd: C:\Users\Kumar\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell "input keyevent 3"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 75.361
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] UiAutomator shut down normally
> info: [debug] Cleaning up android objects
> info: [debug] Cleaning up appium session
> info: [debug] We shut down because no new commands came in
![avd details](https://cloud.githubusercontent.com/assets/23694773/22454024/ad39a178-e748-11e6-8f37-d198c6aefb06.jpg)
](url)

**Comment by mykola-mokhnach** [comment]
1. It is reproducible with the most recent Appium version (1.6.3)
2. There are no errors/failures in this log. Please attach valid log. Also it would be good to see the client code

**Comment by vsrd13** [comment]
I haven't tried this with Appium 1.6.3 version. I will upgraded it now and let you know.

I don't see failure information on my Eclipse IDE output Console except the below information.

<snip>
Jan 31, 2017 11:42:58 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Jan 31, 2017 11:43:41 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
</snip>

Please let me know if you have any other better way for capturing the client side information.

**Comment by vsrd13** [comment]
Also, could you please share how can I upgrade my Appium server to 1.6.3.

**Comment by mykola-mokhnach** [comment]
You can use NodeJS Packages Manager (npm) to update Appium
Please use Appium forum for howto question
