### ISSUE TITLE
Appium provides incorrect values for the invisible cells in UITableView

### ISSUE THREAD

**Issue by PradeshKumar-emisweb** [appium/appium#7778]
## The problem

Appium provides the correct values for the visible cells, but incorrect values for the invisible cell in UITableView.

## Environment

* Appium version:1.6.3
* Desktop OS/version used to run Appium: Mac OS Capitan

## Details

I'm testing an scenario to verify the cell values for UITableView in appium. Appium provides the correct values for the visible cells, but incorrect values for the invisible cell.

For eg., A table is having 30 rows, 20 is visible and 10 is not visible. The table returned to the tests has the top 20 ones correct. The last 10 has the same information as the 30th row.

Do we have any work around for this issue?

**Comment by mykola-mokhnach** [comment]
Appium uses [WebDriverAgent](https://github.com/facebook/WebDriverAgent/issues) as a backend and has nothing to do with cells visibly detection itself 
closing as irrelevant
