### ISSUE TITLE
Can't hide keyboard appium 1.6.3 and WDA 2.6.0 

### ISSUE THREAD

**Issue by dsavchenkov** [appium/appium#7779]
appium ver. : 1.6.3
appium-xcuitest-driver ver. : 2.6.0
env:  iOS 10.2, iPar Air 2

method for hide keyboard: driver.hide_keyboard()
log for hide keyboard- https://gist.github.com/dsavchenkov/a1251ef69c10deb57034f46f0a2635a1
<img width="764" alt="screen shot 2017-01-26 at 9 14 57 pm" src="https://cloud.githubusercontent.com/assets/20097188/22415420/44c76082-e6d8-11e6-9106-5ca54d4da13c.png">

Coordinates for 'Hide Keyboard'  in Landscape mode:
>>> button.rect['x']
6
>>> button.rect['y']
933

Coordinates for 'Hide Keyboard' in Portrait mode:
>>> button.rect['x']
699
>>> button.rect['y']
960

**Comment by mykola-mokhnach** [comment]
OK, I investigated the stuff here and it seems like there is no universal way in iOS to hide keyboard. Every application is allowed to implement keyboard hiding in its own manner.
@imurchie @jlipps  I'd rather deprecate the _hideKeybaord_ for iOS and exclude it from all drivers.

Regarding button coordinates - it know bug. XCTest does not return correct coordinates in non-portrait mode. Please file a bug for Apple instead.

**Comment by imurchie** [comment]
You can try specifying the key which will be pressed. The default here (`tapOutside`) currently does not do anything in XCUITest-based iOS tests.
