### ISSUE TITLE
Robot Frame work  throws KeyError: 'platformName'  - Appium 

### ISSUE THREAD

**Issue by prgovind** [appium/appium#7781]
## The problem

Hi Friends,

        I am learning Appium with Robot frame work.My Test cases is to Login a and Logout a Gmail webpage in chrome browser in samsung mobile with android version 4.4.2 . 
    web page launched successfully but while entering the username, facing a issue as Keyerror: 'Platform Name'.Attached the log file and my code below for your references. Will be more great if some body provide the solution.

Error: 
KeyError: 'platformName'

## Environment
Appium Version - 1.4.16
Robot Frame work Version - 3.0

## Details

Describe in more detail the problem you have been experiencing, if necessary.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
*** settings ***

Library     AppiumLibrary
Resource    D:\\Resource.txt

*** Test Cases ***
Login into Gmail Account
	Open Browser to Login Gmail
	Login Details
	
	
*** Keywords ***
Open Browser to Login Gmail  
    
	Open Application    http://127.0.0.1:4723/wd/hub  platformName=Android  platformVersion=4.4.2  deviceName=42034dbac8074100  app=com.android.browser  automationName=appium  appPackage=com.android.browser  appActivity=com.google.android.apps.chrome.Main
    Go To Url    https://www.gmail.com
	Sleep    5
	#Wait Until Page Contains    ${loginID}
	
Login Details	
	Input Text    ${loginID}    ${UserNameValue}
	Click Element    ${Next}
	Input Password    ${Password}    ${PwdValue}

*** Log File***
info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATO STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] dataDir set to: /data/local/tmp
> info: Chromedriver: Changed state to 'starting'
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"\/data\/local\/tmp","status":0}
> info: Chromedriver: Set chromedriver binary as: C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
> info: Chromedriver: Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"9515 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
> info: Chromedriver: No old chromedrivers seemed to exist
> info: Chromedriver: Spawning chromedriver with: C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=9515
> info: Chromedriver: [STDOUT] Starting ChromeDriver 2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a) on port 9515
> Only local connections are allowed.
> info: JSONWP Proxy: Proxying [GET /status] to [GET http://127.0.0.1:9515/wd/hub/status] with no body
> info: JSONWP Proxy: Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"6.1 SP1\"}}}"
> info: JSONWP Proxy: Proxying [POST /session] to [POST http://127.0.0.1:9515/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","androidDeviceSerial":"42034dbac8074100"}}}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"758ea211d412964c5b4974583a281d34","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},"cssSel...
> info: Chromedriver: Changed state to 'online'
> info: [debug] Overriding session id with "758ea211d412964c5b4974583a281d34"
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to the default of 60 secs
> info: [debug] Appium session started with sessionId 758ea211d412964c5b4974583a281d34
> info: <-- POST /wd/hub/session 303 20492.882 ms - 70 
> info: --> GET /wd/hub/session/758ea211d412964c5b4974583a281d34 {}
> info: JSONWP Proxy: Proxying [GET /wd/hub/session/758ea211d412964c5b4974583a281d34] to [GET http://127.0.0.1:9515/wd/hub/session/758ea211d412964c5b4974583a281d34] with body: {}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"758ea211d412964c5b4974583a281d34","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{},"cssSel...
> info: JSONWP Proxy: Replacing sessionId 758ea211d412964c5b4974583a281d34 with 758ea211d412964c5b4974583a281d34
> info: <-- GET /wd/hub/session/758ea211d412964c5b4974583a281d34 200 7.000 ms - 529 
> info: --> POST /wd/hub/session/758ea211d412964c5b4974583a281d34/url {"url":"https://www.yahoo.com","sessionId":"758ea211d412964c5b4974583a281d34"}
> info: JSONWP Proxy: Proxying [POST /wd/hub/session/758ea211d412964c5b4974583a281d34/url] to [POST http://127.0.0.1:9515/wd/hub/session/758ea211d412964c5b4974583a281d34/url] with body: {"url":"https://www.yahoo.com","sessionId":"758ea211d412964c5b4974583a281d34"}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"758ea211d412964c5b4974583a281d34","status":0,"value":null}
> info: JSONWP Proxy: Replacing sessionId 758ea211d412964c5b4974583a281d34 with 758ea211d412964c5b4974583a281d34
> info: <-- POST /wd/hub/session/758ea211d412964c5b4974583a281d34/url 200 22995.895 ms - 72 
> info: --> GET /wd/hub/session/758ea211d412964c5b4974583a281d34/screenshot {}
> info: JSONWP Proxy: Proxying [GET /wd/hub/session/758ea211d412964c5b4974583a281d34/screenshot] to [GET http://127.0.0.1:9515/wd/hub/session/758ea211d412964c5b4974583a281d34/screenshot] with body: {}
> info: JSONWP Proxy: Got response with status 200: {"sessionId":"758ea211d412964c5b4974583a281d34","status":0,"value":"iVBORw0KGgoAAAANSUhEUgAAAeAAAAL6CAIAAABhExKiAAAgAElEQVR4nOzdd3wcxd0/8O/MbLl+OvXuJksy7g03isGG0GsIBEMCCSQkQMhDIJCQAGm/UBJaIMlDSCh5Q...
> info: JSONWP Proxy: Replacing sessionId 758ea211d412964c5b4974583a281d34 with 758ea211d412964c5b4974583a281d34
> info: <-- GET /wd/hub/session/758ea211d412964c5b4974583a281d34/screenshot 200 893.445 ms - 319330 
> info: [debug] Didn't get a new command in 60 secs, shutting down...
> info: Shutting down appium session
> info: Chromedriver: Changed state to 'stopping'
> info: JSONWP Proxy: Proxying [DELETE /] to [DELETE http://127.0.0.1:9515/wd/hub/session/758ea211d412964c5b4974583a281d34] with no body
> info: JSONWP Proxy: Got response with status 200: "{\"sessionId\":\"758ea211d412964c5b4974583a281d34\",\"status\":0,\"value\":null}"
> info: Chromedriver: Changed state to 'stopped'
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"value":"OK, shutting down","status":0}
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 99.14
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] UiAutomator shut down normally
> info: [debug] executing cmd: C:\Users\Administrator\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s 42034dbac8074100 shell "am force-stop com.android.chrome"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] Cleaning up appium session
> info: [debug] We shut down because no new commands came in

**Comment by mykola-mokhnach** [comment]
1. Appium 1.4.16 is outdated. Please update to 1.6.3
2. Use Appium forum for howto questions. This is the place for bugs and issues.
