### ISSUE TITLE
not able to navigate to URL in safari launcher app through appium remote web driver

### ISSUE THREAD

**Issue by prateekchawla** [appium/appium#7783]
not able to navigate to URL in safari launcher app through appium remote web driver
Using driver.Navigate().GoToUrl("https://www.google.com"); - It does nothing to the safari launcher app

Appium version (or git revision) that exhibits the issue: 1.6.1-beta
Last Appium version that did not exhibit the issue (if applicable): NA
Desktop OS/version used to run Appium: 10.11.5
Node.js version (unless using Appium.app|exe): NA
Mobile platform/version under test: Ipad - 9.3.5
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium CLI

https://gist.github.com/prateekchawla/abf39846988d13a946a402be3cc744fb

Code for Capabilities:
                DesiredCapabilities capabilities = new DesiredCapabilities();
                capabilities.SetCapability("platformName", "iOS");
                capabilities.SetCapability("automationName", "XCUITest");
                capabilities.SetCapability("platformVersion", "9.3.5");
                capabilities.SetCapability("platform", "Mac");
                capabilities.SetCapability("deviceName", "Comparenow’s iPad");
                capabilities.SetCapability("udid", "1c2f3e964c8290a8833f1410692f0ace26403c41");
                capabilities.SetCapability("bundleId", "com.AutomationDec");
                capabilities.SetCapability("newCommandTimeout", 180);
                capabilities.SetCapability("BrowserName", "Safari");
                driver = new RemoteWebDriver(new Uri("http://10.140.3.89:4723/wd/hub"), capabilities);
                driver.Navigate().GoToUrl("https://www.google.com");

Note: I am using the IWebDriver

**Comment by imurchie** [comment]
Can you provide the full Appium server logs?

Ae you wanting a Safari test? Try deleting the `"bundleId"` capability.

**Comment by prateekchawla** [comment]
https://gist.github.com/prateekchawla/fa3dbc2b55e1bea15593306090108c21

Yes i am wanting a safari web test - I am launching SafariLauncher app
when i delete the bundle id capability , it asks to provide either app path or bundle id

**Comment by imurchie** [comment]
Set the `browserName` (not lower case `b`) capability to `Safari` and do not set a `bundleId` or `app`.

**Comment by prateekchawla** [comment]
Thanks :) @imurchie 
This did help. 
Just a question out of this issue , how can i inspect elements on the safari web ?

**Comment by imurchie** [comment]
Easiest way is to look at the page source.

**Comment by prateekchawla** [comment]
Thanks. 
Would you suggest using IOS driver or Xcuit driver ( I guess it is used internally) ?

**Comment by imurchie** [comment]
If the platform version is supported, I would recommend using XCUITest driver.

**Comment by MMuralidh** [comment]
I have to switch between My native app and safari on a real device. I am able to open safari using JavaScriptExecutor, I am unable to load the url. Need help.

**Comment by imurchie** [comment]
@MMuralidh This is a closed issue for a system that almost certainly does not apply in your case.

Please create a new issue with all the information asked for.
