### ISSUE TITLE
node_sqlite3.node not found

### ISSUE THREAD

**Issue by dpgraham** [appium/appium#7784]
## The problem

Getting the error ```Cannot find module '/Users/danielgraham/appium-ios-driver/node_modules/sqlite3/lib/binding/node-v51-darwin-x64/node_sqlite3.node' ``` again. The solution was for me to delete the sqlite3 package and then reinstall it. 

## Details

My proposal is that we get rid of the sqlite3 dependency and just do sqlite3 through the command line. Sqlite3 comes packaged with osx and the SSL Certificate code that uses sqlite3 only applies to IOS Simulators.

**Comment by imurchie** [comment]
I'm all for this.
