### ISSUE TITLE
Wrong parameters sent to instruments when swipe

### ISSUE THREAD

**Issue by lduretz** [appium/appium#7787]
## The problem

Error when swipe on iOS

## Environment

* Appium 1.6.3
* Desktop OS: Mac OSX 10.11.6
* Node.js version (unless using Appium.app|exe): 5.1.1
* Mobile platform/version under test: iOS 8.2
* Real device or emulator/simulator: Real iPhone 5s

## Details

Using Robotframework + robotfrawemork-appiumlibrary to perform a Swipe(0.5, 0.9, 0.5, 0.5)
Following error is displayed : WebDriverException: Message: Unexpected number '.5'. Expected ')' to end a argument list.
Descending in appium server logs I found the request below

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/02197371-d5e3-4fa1-a8a1-519e16b1910c/touch/perform {"sessionId":"02197371-d5e3-4fa1-a8a1-519e16b1910c","actions":[{"action":"press","options":{"y":"0.9","x":"0.5"}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"y":"0.5","x":"0.5"}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"y":"0.9","x":"0.5"}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"y":"0.5","x":"0.5"}},{"action":"release","options":{}}],"02197371-d5e3-4fa1-a8a1-519e16b1910c"]
[debug] [iOS] Executing iOS command 'performTouch'
**[debug] [UIAuto] Sending command to instruments: au.dragApp(0.5, 0.9, 0.50.5, 0.90.5, 1)**
[debug] [Instruments] [INST] 2017-02-01 14:03:08 +0000 Debug: Got new command 7 from instruments: au.dragApp(0.5, 0.9, 0.50.5, 0.90.5, 1)
[debug] [Instruments] [INST] 2017-02-01 14:03:08 +0000 Debug: evaluating au.dragApp(0.5, 0.9, 0.50.5, 0.90.5, 1)
[debug] [UIAuto] Socket data received (86 bytes)
[debug] [UIAuto] Got result from instruments: {"status":17,"value":"Unexpected number '.5'. Expected ')' to end a argument list."}
[HTTP] <-- POST /wd/hub/session/02197371-d5e3-4fa1-a8a1-519e16b1910c/touch/perform 500 1171 ms - 147

**Comment by kcinman11358** [comment]
can you provide the code and what language it is in?

**Comment by imurchie** [comment]
Interesting. It looks like it is taking the strings and concatenating, rather than dealing in numbers.

**Comment by imurchie** [comment]
Added to our backlog to fix. 

In the meantime, is there a way to coerce the values into numbers? I see that the `ms` wait is correctly a number, so the framework must support it somehow.

**Comment by lduretz** [comment]
I think the problem is in the areOffsets attribute computation when coordinates are indicated as percent of screen

**Comment by lduretz** [comment]
I compared appium 1.4 and appium 1.6 source code about gesture.
1.6 does not include cases about percentages of screen size.

I patched the gesture.js code to return x and y percentages instead of coordinates and my swipe is now working :)

**Comment by jlipps** [comment]
thanks @lduretz. Unfortunately we're not supporting the Instruments/UIAutomation driver anymore so your patch will have to suffice.
