### ISSUE TITLE
Not finding the swipe image in Swipe screen in IOS, in Appium 1.6.3, even though the image is present

### ISSUE THREAD

**Issue by saritau** [appium/appium#7792]
## The problem

Not finding the swipe image in Swipe screen in IOS, in Appium 1.6.3, even though the image is present

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.0/1/6/3
* Last Appium version that did not exhibit the issue (if applicable):1.5.8
* Desktop OS/version used to run Appium: Mac os
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:

## Details

I am in a swipe screen with a swipe image. Not able to find swipe image even though its present in the swipe screen. Attached screen for reference.

<img width="322" alt="screen shot 2017-02-02 at 2 14 23 pm" src="https://cloud.githubusercontent.com/assets/23231769/22544373/7d815246-e95a-11e6-8b1b-1046e5faaf11.png">

Even in the dom tree(when we see it in Appium inspector), the element is missing(not shown).

Please reply me ASAP

## Link to Appium logs

Nothing is shown in logs as it is trying to locate the swipe image & not finding it.

**Comment by p00j4** [comment]
this could be built using WebView/ScrollView/PageViewController sort of ios native component, and that is the hint that you need to figure out a way to switch to that first for letting appium know that "yes, now go ahead, read the page source & use the elements hierarchy associated with"

**Comment by jlipps** [comment]
Unfortunately some controls are not visible to appium because they're not visible to the automation technology. If the item is not shown in the dom, then you won't be able to automate it with appium.
