### ISSUE TITLE
Not scrolling after few scrolls in case of large screens & which has more elements even when the scroll based element is present.

### ISSUE THREAD

**Issue by saritau** [appium/appium#7793]
## The problem

Not scrolling after few scrolls in case of large screens & which has more elements even when the scroll based element is present.

## Environment

Appium version (or git revision) that exhibits the issue:1.6.0/1/6/3
Last Appium version that did not exhibit the issue (if applicable):1.5.8
Desktop OS/version used to run Appium: Mac os
Node.js version (unless using Appium.app|exe):
Mobile platform/version under test:
Real device or emulator/simulator:simulator
Appium CLI or Appium.app|exe:

## Details

Not scrolling after few scrolls in case of large screens & which has more elements even when the scroll based element is present.

I am trying to scroll based on XCUIElementTypeCollectionView. I am able to scroll till last but one instance of XCUIElementTypeCollectionView. After this instance, it has more number of elements & then there is an instance of XCUIElementTypeCollectionView. Till the last instance of  XCUIElementTypeCollectionView, scrolling is not happening. It stops scroll in the last but one instance. I have observed this in many screens in my application which involves large number of elements. Has anyone observed the same.

**Comment by mykola-mokhnach** [comment]
Known [WDA issue](https://github.com/facebook/WebDriverAgent/issues/293). You need to invoke scroll method manually in such case.

**Comment by saritau** [comment]
Can u pls share some sample code for both the suggestions asked to be implemented.

Thanks in advance.

**Comment by saritau** [comment]
Hi Mykola Mokhnach

Can you pls share some sample code for both the suggestions asked to be implemented.

Thanks & regards
Sarita U

**Comment by mykola-mokhnach** [comment]
Unfortunately I cannot , since I don't use TouchAction interface for our automation. Try to ask in Appium forum.
