### ISSUE TITLE
Enqueue Failure: UI Testing Failure - Failed to get snapshot within 15.0s

### ISSUE THREAD

**Issue by amleszk** [appium/appium#7796]
## The problem

Error finding elements

`XCTRunner[83980:8602143] Enqueue Failure: UI Testing Failure - Failed to get snapshot within 15.0s /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1`

## Environment

* Appium version (or git revision) that exhibits the issue: Appium `1.6.3` and Appium `1.6.4-beta`
* Last Appium version that did not exhibit the issue (if applicable): `1.6.4-beta`
* Desktop OS/version used to run Appium: OSX 10.11.5 (15F34) El Capitan
* Node.js version (unless using Appium.app|exe): v6.2.1
* Mobile platform/version under test: iOS Simulator 10.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Appium will hang and not perform any actions, this error appears randomly

## Link to Appium logs

https://gist.github.com/amleszk/1c4ef4c75227f23b3cbee7ba4865b6ca

**Comment by mykola-mokhnach** [comment]
The issue has nothing to do with Appium, but rather with [WDA](https://github.com/facebook/WebDriverAgent/issues). Please describe it there. Also, it is necessary to have full device log and to know what is happening in the application under test
