### ISSUE TITLE
Input are sometime replaced

### ISSUE THREAD

**Issue by tesseslol** [appium/appium#7798]
## The problem

i'm using appium (by robotframework) to make a simple login test on a mobile app.
the test sometime works fine,
in the username input appium wrong the insert...  

## Environment

* Appium version : 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  Windows
* Node.js version (unless using Appium.app|exe): 7.4.0
* Mobile platform/version under test:  6.0
* Real device or emulator/simulator:  emulator
* Appium CLI or Appium.app|exe:  Appium cli

## Details

https://youtu.be/-q-UCUkspIQ

## Link to Appium logs

https://gist.github.com/tesseslol/eec86e2771e0132444ce0c2149cfb5ea

## Code To Reproduce Issue [ Good To Have ]

https://github.com/tesseslol/appium-issue

**Comment by mykola-mokhnach** [comment]
Please decorate the issue report properly according to the template. Otherwise I don't think one could be able to help you anytime soon.

**Comment by tesseslol** [comment]
ok srry

**Comment by tesseslol** [comment]
i've updated the issue...

**Comment by mykola-mokhnach** [comment]
If this is the same field where username and password is typed then you have to clear it first before entering a new value. Or make sure it is done properly in you application under test.

**Comment by tesseslol** [comment]
https://github.com/serhatbolsu/robotframework-appiumlibrary/issues/157
