### ISSUE TITLE
Appium is not adding the Resources folder for WebDriverAgent during installation

### ISSUE THREAD

**Issue by TheChell** [appium/appium#7800]
## The problem

When installing appium (`npm install -g appium`) it installs the WebDriverAgent folder, but is neglecting to add the Resources folder, containing the WebDriverAgent.bundle file. This is not letting me build the WebDriverAgent project in Xcode and I'm not sure how else to add it.

## Environment

* Appium version: 1.6.3
* Desktop OS/version used to run Appium: 10.11.6
* Node.js version: 5.5.0
* Xcode version: 8.2

## Details

My process has been:

```
$ npm install -g appium
$ npm install -g appium-doctor
$ brew install libimobiledevice --HEAD
$ brew install ideviceinstaller
$ npm install -g ios-deploy
$ gem install xcpretty
$ cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/
$ brew install carthage
$ npm i -g webpack
$ ./Scripts/bootstrap.sh -d
```

However, during the first step of installing appium, I see that the Resources folder has not been added to the WebDriverAgent folder. 

![screen shot 2017-02-03 at 12 27 36 pm](https://cloud.githubusercontent.com/assets/8346663/22601385/a4b49eba-ea0c-11e6-9506-62147638d0c9.png)

When I open the project in Xcode, I see the following:

![screen shot 2017-02-03 at 12 30 21 pm](https://cloud.githubusercontent.com/assets/8346663/22601474/05e2aefc-ea0d-11e6-9ae7-82391849028a.png)

I know I can add a new config file to remedy the missing ProjectSettings.xcconfig file, but am not sure how to get around the error:

`error: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Resources/WebDriverAgent.bundle: No such file or directory`

I've tried uninstalling and reinstalling appium a few times and it never seems to add the Resources folder.

**Comment by imurchie** [comment]
The Resources folder is created when Appium is run.

If you really want to do things manually, it is just an empty directory. If you run `mkdir -p /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Resources/WebDriverAgent.bundle` it ought to be fixed.

**Comment by TheChell** [comment]
Thank you, I didn't realize it was only created when run.
