### ISSUE TITLE
After set value the test hungs

### ISSUE THREAD

**Issue by ptsiakos77** [appium/appium#7801]
Appium 1.6.4 beta version
XCode 8.2

My test suite hangs sporadically when I type values usually in search fields.(Usually it manages to type a part of value in the field and then stucks). This is not happening consistently but when it happens the logs are as follows:

[HTTP] --> POST /wd/hub/session/033fdfb0-031d-42e0-851f-db8ea44dff3d/element/049105F2-4EC2-48A5-8E24-C00271E85DA7/value {"id":"049105F2-4EC2-48A5-8E24-C00271E85DA7","value":["Dev Ops"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["Dev Ops"],"049105F2-4EC2-48A5-8E24-C00271E85DA7","033fdfb0-031d-42e0-851f-db8ea44dff3d"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [JSONWP Proxy] Proxying [POST /element/049105F2-4EC2-48A5-8E24-C00271E85DA7/value] to [POST http://localhost:8100/session/4773D56E-0639-4FBB-A722-76C20A5648E8/element/049105F2-4EC2-48A5-8E24-C00271E85DA7/value] with body: {"value":["D","e","v"," ","O","p","s"]}
[HTTP] <-- POST /wd/hub/session/033fdfb0-031d-42e0-851f-db8ea44dff3d/element/049105F2-4EC2-48A5-8E24-C00271E85DA7/value - - ms - - 
[HTTP] --> POST /wd/hub/session/033fdfb0-031d-42e0-851f-db8ea44dff3d/element/049105F2-4EC2-48A5-8E24-C00271E85DA7/value {"id":"049105F2-4EC2-48A5-8E24-C00271E85DA7","value":["Dev Ops"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["Dev Ops"],"049105F2-4EC2-48A5-8E24-C00271E85DA7","033fdfb0-031d-42e0-851f-db8ea44dff3d"]
[debug] [XCUITest] Executing command 'setValue'
[HTTP] <-- POST /wd/hub/session/033fdfb0-031d-42e0-851f-db8ea44dff3d/element/049105F2-4EC2-48A5-8E24-C00271E85DA7/value - - ms - - 
04/02/17 **00:17:23** Stevia [RC IOSController$$EnhancerBySpringCGLIB$$82e69aef@c6c3] ERROR - IOSLogger                  - Error communicating with the remote browser. It may have died.
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 **13:08:06'**
System info: host: 'Workables-iMac.local', ip: '10.9.42.250', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.3', java.version: '1.8.0_121'
Driver info: driver.version: IOSDriver
[HTTP] --> GET /wd/hub/session/033fdfb0-031d-42e0-851f-db8ea44dff3d/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[HTTP] <-- GET /wd/hub/session/033fdfb0-031d-42e0-851f-db8ea44dff3d/screenshot - - ms - - 
[HTTP] --> GET /wd/hub/session/033fdfb0-031d-42e0-851f-db8ea44dff3d/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'

AND IT NEVER PROGRESSES FROM HERE...LIKE A DEADLOCK THAT NEVER EXITS
This is kind of blocking because after that the suite is not finished and no results are taken

**Comment by mykola-mokhnach** [comment]
Try to disable hardware keyboard if this is a simulator. Anyway, it is unlikely an Appium issue. It should be reported to [WDA](https://github.com/facebook/WebDriverAgent/issues) instead.

**Comment by ptsiakos77** [comment]
Guys do you need any additional info for that? (I have opened it to WDA as well but no response)It's kind of blocking for our test suites since it may be sporadic but when we run the whole suite at least one test will be blocked by this cause and will block the whole suite

@mykola-mokhnach 
is it possible to be an appium problem?
From what we say in release notes of appium 1.6.4 beta this version:
Speed up setting the value of text fields

We are really blocked from this issue

**Comment by imurchie** [comment]
More information is always better. Did this not happen in 1.6.3? Can you make a [gist](https://gist.github.com) of the full logs?

**Comment by ptsiakos77** [comment]
Yes this happened but after 4 minutes I retrieved the error: ProxyRequestError: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT

In 1.6.4 beta in the same cases I never take this but eventually I took the above

because I saw in the Appium 1.6.4 beta that the way in which setting value in input fields has changed (is actually faster) maybe does not handle cases that the request may hung?

**Comment by mykola-mokhnach** [comment]
it's XCTest bug and we can do nothing to fix it. All complains to Apple please.
The thing, that was mentioned in the changelist is about optimising the way we call WDA REST methods, but the called method is still the same.

**Comment by ptsiakos77** [comment]
Hi all, just some clarifications that trouble me

Regarding the XCTest bug you mean this correct?:
est failure: -[TestSearchUItest testExample()] failed: UI Testing Failure - Failure fetching attributes for element <XCAccessibilityElement: 0x17584cae0> Device element: Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202}

@mykola-mokhnach You have right there is this XCtest bug we reproduced this with the developer here writing directly in XCTest with XCode

Two things I want to ask here:

1) The thing that hangs when trying to setValue in an input field is (set only some characters)
is for sure connected to that? Because it seems a different issue to me. It has already identified the element as visible and start inserting values to this.

2) The XCTest test crashed out immediately but in out case the test hangs like for ever. Is there any capability to reduce this timeout at least to proceed to next test?

**Comment by mykola-mokhnach** [comment]
"Error copying attributes" has nothing to do to keyboard input thing. These two are different XCTest bugs, which raise different errors in logs (check https://github.com/facebook/WebDriverAgent/issues/453)

Regarding the timeout - there is **newCommandTimeout** capability, which might be useful for you.

**Comment by ptsiakos77** [comment]
Ok thanks for the response.
I tried the newCommandTimeout capability but with no luck. There was a commandTimeout capability.
Is this deprecated?

**Comment by mykola-mokhnach** [comment]
This is how we solve timeouts in our overridden AppimDriver instance. Feel free to reuse the code if you find it useful.

```java
    public boolean isSessionLost() {
        return this.isSessionLost;
    }

    private void setSessionLost(boolean isLost) {
        if (isLost != this.isSessionLost) {
            log.warn(String.format("Changing isSessionLost to %s", isLost));
            log.debug(LOG_DECORATION_PREFIX + "\n" + AppiumServer.getInstance().getLog().orElse("")
                    + "\n" + LOG_DECORATION_SUFFIX);
        }
        this.isSessionLost = isLost;
    }

    private ExecutorService pool;

    private synchronized ExecutorService getPool() {
        if (this.pool == null) {
            this.pool = Executors.newFixedThreadPool(1);
        }
        return this.pool;
    }

    private boolean isSessionLostBecause(Throwable e) {
        return (e instanceof UnreachableBrowserException) || (e instanceof SessionNotFoundException);
    }

    @Override
    protected Response execute(String command) {
        return this.execute(command, ImmutableMap.<String, Object>of());
    }

    @Override
    public Response execute(String driverCommand, Map<String, ?> parameters) {
        if (this.isSessionLost()) {
            throw new IllegalStateException(
                    String.format("Appium session is dead. Skipping execution of '%s' command...", driverCommand));
        }

        final Callable<Response> task = () -> super.execute(driverCommand, parameters);
        final Future<Response> future = getPool().submit(task);
        Timedelta timeout = MAX_COMMAND_DURATION;
        switch (driverCommand) {
            case DriverCommand.GET_PAGE_SOURCE:
                timeout = MAX_GET_SOURCE_DURATION;
                break;
            case DriverCommand.NEW_SESSION:
                timeout = MAX_SESSION_INIT_DURATION;
                break;
        }
        try {
            return future.get(timeout.asMilliSeconds(), TimeUnit.MILLISECONDS);
        } catch (Exception e) {
            if (e instanceof ExecutionException) {
                if (isSessionLostBecause(e.getCause())) {
                    setSessionLost(true);
                }
                if (e.getCause() instanceof WebDriverException) {
                    throw (WebDriverException) e.getCause();
                } else {
                    throw new WebDriverException(e.getCause());
                }
            } else {
                if (e instanceof TimeoutException) {
                    setSessionLost(true);
                }
                throw new WebDriverException(e);
            }
        }
    }
```

**Comment by ptsiakos77** [comment]
@mykola-mokhnach 
I' ll take a try. thanks a lot

**Comment by vikramvi** [comment]
@mykola-mokhnach If you can please open source the framework; will be useful to many users of appium.

**Comment by mykola-mokhnach** [comment]
I would be happy to do it, but the framework possesses the knowledge about our backdors for testing purposes, which Wire cannot disclose.

**Comment by vikramvi** [comment]
Anyways thanks for posting solutions from your project

**Comment by ptsiakos77** [comment]
@mykola-mokhnach 
Thanks very much for your solution!!!
With Appium 1.6.4Beta and your code this sporadic error happens rarely BUT when is happened, the TIMEOUT is respected and the suite continues

I think appium-java-client should integrate this kind of elegant solution since with the current implementation the handle of TIMEOUTS is not reliable

Thanks once again for your great support!

**Comment by SatishKumarKV** [comment]
@ptsiakos77  : How did u reuse above code. Can u please help ?

**Comment by mykola-mokhnach** [comment]
We added **commandTimeouts** capability to xcuitest driver, which implements the same approach as the java code above. You can try it as well.

**Comment by SatishKumarKV** [comment]
Thanks @mykola-mokhnach. So if i set below capability..
capabilities.setCapability("commandTimeouts", "120000");
All commands such as "SetValue" which are being executed will have a default timeout of 3 mins ?

**Comment by mykola-mokhnach** [comment]
you can see the detailed description at https://github.com/appium/appium-xcuitest-driver/
I would recommend to set the timeout for the particular command instead to avoid unexpected failures. For example

```
'{"setValue": 20000}''
```
