### ISSUE TITLE
Release notes for xcuitest-driver?

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/appium#7802]
I see the xcuitest-driver is updated fairly regularly, but outside of looking at the actual commits themselves, there aren't really any release notes.

Or have I not been looking in the right place?

**Comment by mykola-mokhnach** [comment]
Is [this](https://github.com/appium/appium/releases) what you are looking for?

**Comment by VivaLosDoyers** [comment]
That's helpful, but I'm talking more about release notes related specific to the XCUITest driver, which gets updated far more frequently.

**Comment by mykola-mokhnach** [comment]
I doubt there are release notes specific to that project. You have commits history though.
