### ISSUE TITLE
[Appium 1.6.3] Unable to run XCUItests - fails looking for SafariLauncher

### ISSUE THREAD

**Issue by JESii** [appium/appium#7803]
## The problem

I'm trying to run ruby/cucumber tests with Appium, right now for the IphoneSimulator and next for a real iOS device.  The command I'm using is:
```
bundle exec cucumber   DEVICE=IphoneSimulator -p mobile_website_default    SITE=MCOM URL=http://<test-url>/  features/website/Selection/MEW/registry/MCOM/registry_navigation.feature:14
```
The command is eventually failing with:
```
An unknown server-side error occurred while processing the command. Original error: Bad app: /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/build/SafariLauncher/SafariLauncher.app. App paths need to be absolute, or relative to the appium server install dir, or a URL to compressed file, or a special app name. (Selenium::WebDriver::Error::UnknownError
```
I previously had problems with SafariLauncher (issue #7776) on Xcode 7.3.1 so upgraded to Xcode 8.1 hoping the XCUItest setup would solve the problem. No luck...

#### Possible duplicate issue?

I'm assuming that with Xcode 8, it will use XCUItest even for an iOS 9.3 device
** If not, then this is probably a duplicate of issue #7776, except that now I've upgraded to the latest non-beta Xcode (8.2.1).

## Environment

* Appium version (or git revision) that exhibits the issue:
1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
N/A
* Desktop OS/version used to run Appium:
ElCap; 10.11.6
* Node.js version (unless using Appium.app|exe):
7.4.0
* Mobile platform/version under test:
iOS 9.3.5
* Real device or emulator/simulator:
Simulator (have also tried real device and making no progress there as well)
* Appium CLI or Appium.app|exe:
Appium.app (have also tried the CLI and no progress there either)
* Xcode
8.2.1

What I've installed and configured
*    Appium.app is running and launched for iOS
*    ios-webkit-debug-proxy running (tested with and without
*    appium-ios-driver installed
*    libmobiledevice installed
*    ideviceinstalled installed
*    ios-deploy -g installed but had "extraneous" errors
```
npm list | grep ios-deploy
npm ERR! missing: appium-logger@^2.1.0, required by appium-ios-log@1.2.0
npm ERR! missing: appium-support@^2.0.9, required by appium-ios-log@1.2.0
npm ERR! missing: appium-xcode@^3.1.0, required by appium-ios-log@1.2.0
npm ERR! missing: asyncbox@^2.3.1, required by appium-ios-log@1.2.0
npm ERR! missing: babel-runtime@=5.8.24, required by appium-ios-log@1.2.0
npm ERR! missing: bluebird@^2.10.2, required by appium-ios-log@1.2.0
npm ERR! missing: date-utils@^1.2.17, required by appium-ios-log@1.2.0
npm ERR! missing: teen_process@^1.3.1, required by appium-ios-log@1.2.0
```
*    .xcconfig defined and contains default settings
*    carthage installed; no cartfile; testing web page, not app

## Details

I have tried every combination I can think of to run either the simulator of a real iPad... Now I'm just trying to keep it simple and get the simulator running and that is what I'm reporting here.

## Link to Appium logs

Log is here, https://gist.github.com/JESii/ad13793caa36159897f9960fda7051bc copied from Appium.app. The last section has the relevant information.

## Code To Reproduce Issue [ Good To Have ]

Not testing an app; testing a web page through ruby/cucumber

**Comment by imurchie** [comment]
Are your logs correct for this issue? They are neither Appium 1.6.3 nor XCUITest-based iOS.

**Comment by JESii** [comment]
Sorry: I copied them from the console output of Appium.app which I had just downloaded -- but it turns out that's 1.5.3; my bad. I'll download/install and try again.

And where do I find the logs from the command-line?

**Comment by JESii** [comment]
So... I just downloaded the latest GUI version from here (http://appium.io/slate/en/master/?ruby#appium-gui) but it's only 1.5.3 -- so I guess there is no 1.6.3 GUI version? and I'll have to re-run with the node/command-line version.

**Comment by imurchie** [comment]
The GUI is being re-written as the old one could not be updated.

**Comment by JESii** [comment]
Got it; thanks.

For the CLI version, where do I find the logs for submitting an issue?

**Comment by imurchie** [comment]
Wherever you start Appium, they are just the standard output. So if you run `appium` on the command line, whatever comes out is the logs.

**Comment by JESii** [comment]
Cool; thank you! very much I'll tee that for future questions.
