### ISSUE TITLE
Unable to install appium from terminal. 

### ISSUE THREAD

**Issue by vigneshph** [appium/appium#7805]
## The problem

Unable to install appium via npm. I have the latest version of node and npm running in my machine 

## Environment

* Appium version (or git revision) that exhibits the issue: All versions
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: El Capitan 10.11.6
* Node.js version (unless using Appium.app|exe): v0.10.28
* Mobile platform/version under test: 
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: 
[appium.txt](https://github.com/appium/appium/files/753790/appium.txt)

**Comment by mykola-mokhnach** [comment]
your NodeJS version is quite old. Try to update it to 7.0+
