### ISSUE TITLE
"Socket hang up" error is displayed in the middle of the test execution when running 30 test cases

### ISSUE THREAD

**Issue by VeenuGogia** [appium/appium#7807]
## The problem
When running 30 test cases, then in the middle of the test execution application will not run. "Socket hang up" error is displayed in the appium console. Tool Name: Appium is displayed in the eclipse console.

## Environment
* Appium version (or git revision) that exhibits the issue: Appium v1.6.3
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: OS X EL Capitan (v 10.11.6)
* Mobile platform/version under test: v 10.1.1
* Real device or emulator/simulator: Real Device : iPhone 5

##Details
WebDriverAgent is killed from the device i.e. it is closed and application is not started after that in the middle of the test execution.

[Appium Console - 3rd Feb Report.zip](https://github.com/appium/appium/files/753991/Appium.Console.-.3rd.Feb.Report.zip)

## Link to Appium logs
Refer the attachement

**Comment by mykola-mokhnach** [comment]
It might be related to https://github.com/facebook/WebDriverAgent/issues/372
Try updating Appium to 1.6.4-beta

**Comment by VeenuGogia** [comment]
Tried with Appium 1.6.4-beta. But facing the issue. Even tried in different machine also.

**Comment by mykola-mokhnach** [comment]
Also tried to apply the patch for visibility descried there?

**Comment by dilsreccse** [comment]
Even I'm encountering the same issue , when I do execution of more no of test scripts , it's hang in between and rest of the scripts are not getting executed

**Comment by VeenuGogia** [comment]
@mykola-mokhnach  I do not get you. Can you please elaborate that what are you trying to say ?

**Comment by jlipps** [comment]
please use newest beta release and set the `maxTypingFrequency` capability to something low like `5` or `8`. This should work.
