### ISSUE TITLE
Unable to install appium via npm

### ISSUE THREAD

**Issue by sergiomjm** [appium/appium#7808]
## The problem

I am having problems installing appium on my machine, the error is in the installation of Chromedriver

## Environment

node v6.9.5
npm  v3.10.10
windows 10

## Details

info Chromedriver Install Installing Chromedriver version '2.25' for platform 'win' and architecture '32'
info Chromedriver Install Opening temp file to write chromedriver_win32 to...
info Chromedriver Install Downloading https://chromedriver.storage.googleapis.com/2.25/chromedriver_win32.zip...
RequestError: Error: connect ETIMEDOUT 216.58.214.176:443

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\desarrollo\\nodejs\\node.exe" "C:\\desarrollo\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "appium"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! appium-chromedriver@2.9.4 install: `node install-npm.js`
npm ERR! Exit status 1

## Code To Reproduce Issue [ Good To Have ]

npm install -g appium

**Comment by JaniJegoroff** [comment]
Are you able to download chromedriver package manually?

**Comment by sergiomjm** [comment]
Yes, I have access and I have it downloaded

**Comment by mykola-mokhnach** [comment]
might be a proxy issue. Look for docs on how to configure a proxy for npm. Anyway, this is not Appium-related thing
