### ISSUE TITLE
iOS: Dynamically loaded element is not selectable and not displayed right in Appium Inspector

### ISSUE THREAD

**Issue by Seijan** [appium/appium#7809]
## The problem

I'm trying to click on some buttons that are loaded on a page, where I previously select a category, which triggers the buttons to be loaded. The problem is now that I can't click on them, because they are not loaded correctly, it looks like there is an issue with the not populated cell that is than populated after I select the category. 

To clarify it, this is how it looks like in the Appium Inspector:
![problem appium](https://cloud.githubusercontent.com/assets/9142695/22653875/2e43f7a4-ec8b-11e6-830a-3bd1ba39a4a2.png)

As can be seen the selected cell contains all the names of the elements in the name-tag and it is a staticTextElement, which is not what it is in the app. 

This happens if I execute the test in Intellij as well, the item can't be found.

## Environment

* Appium version: 1.6.3
* Desktop OS/version used to run Appium: Mac 10.12
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Both

**Comment by mykola-mokhnach** [comment]
Sorry, the old desktop-based inspector is not supported anymore

**Comment by Seijan** [comment]
Okay I get that, but I still have the problem when I use my code. Because of that it would be nice to get an answer.

**Comment by mykola-mokhnach** [comment]
Check if these UI elements are visible in the standard Accessibility Inspector.

**Comment by Seijan** [comment]
They are, I automated this test with calabash before and it was working just fine.

**Comment by mykola-mokhnach** [comment]
are these elements visible in driver.getPageSource() outpur?

**Comment by Seijan** [comment]
Yes they are visible like they are visible in the old appium inspector, as a list of names. Every other object is normally initialized.

**Comment by mykola-mokhnach** [comment]
If they are visible in page source then it should be possible to find them. Probably, there is a race condition there and you need to wait for a while until the appear on the page before looking for them.

**Comment by Seijan** [comment]
`<XCUIElementTypeStaticText name="Kameratyp, Marke, HD-fähig, Zustand, Übergabe, Bitte wählen, Bitte wählen, Gebraucht, Bitte wählen" label="Kameratyp, Marke, HD-fähig, Zustand, Übergabe, Bitte wählen, Bitte wählen, Gebraucht, Bitte wählen" value="Kameratyp, Marke, HD-fähig, Zustand, Übergabe, Bitte wählen, Bitte wählen, Gebraucht, Bitte wählen" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/0/1/0/0/0/9/0" x="0" y="357" width="320" height="186">
</XCUIElementTypeStaticText>`

That's how i get the element, it's a static text and not buttons.

**Comment by mykola-mokhnach** [comment]
Which means these elements, that you want to interact with, are NOT visible in page source, right?

If yes then check the source of your application under test. Probably, these buttons are not available for accessibility inspection at all.

**Comment by Seijan** [comment]
Ah now I get what you mean with elements, yes thats correct they are not visible in the page source, sorry for this misunderstanding.
