### ISSUE TITLE
Error when trying to run appium test on real device

### ISSUE THREAD

**Issue by jayczech23** [appium/appium#7813]
I keep getting an xcode-build error when trying to run appium tests on my iPhone 6. Logs are below.

Appium version: 1.6.3
Mac OS Sierra 10.12.2
node -version: 7.4.0
Testing: iPhone 6/ iOS 10.2.1
REAL DEVICE

Was running my python tests on Simulator just fine, but then I keep on getting xcode-build errors and 'socket hang up' errors when trying to run on an iPhone 6. WebDriver is not installing on device either. 

Logs for both my local terminal and appium logs:

APPIUM LOGS
https://gist.github.com/jayczech23/fb014a6c7a53239c8f42fba32ea359bb

CONSOLE LOGS
https://gist.github.com/jayczech23/4d47262b684b3e68a5f115a4be25dc12

**Comment by mykola-mokhnach** [comment]
Seems like there are problems with WDA sources signing. Make sure you follow [this](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md) tutorial.

**Comment by jayczech23** [comment]
@mykola-mokhnach Hi thanks for reply! When I tried to build the 'WebDriverAgentRunner' in the WebDriverAgent.xcodeproj , I keep getting the error: 

"Failed to creat provisioning profile. The app ID "com.facebook.IntegrationApp' cannot be registered to your development team. Change your bundle identifier and try again."

But there is no option for bundle id to change under WebDriverAgentRunner -> General

Any idea how to change the provisioning profile?

**Comment by imurchie** [comment]
You should not need to build the Integration app. If you need to change the bundle id, it will be under "Build Settings" as "Product Bundle Identifier".

**Comment by jayczech23** [comment]
@imurchie Hey there thanks for reply! I changed the bundle under "Product Bundle Identifier" for all the targets of WebDriverAgent , but still no luck. Still getting the same errors as before.

**Comment by imurchie** [comment]
You have two scenarios on the go, so I'm not sure what you mean by "as before". Do you mean through Appium or building in Xcode?

**Comment by jayczech23** [comment]
@imurchie Sorry, I meant when trying to run the test on appium, I got the same logs as the ones in the initial post.

**Comment by imurchie** [comment]
What steps did you do to configure it?

**Comment by jayczech23** [comment]
1. I opened WebdriverAgent.xcodeproj at appium/node-modules/appium-xcuitest-driver/WebDriverAgent     

2. Changed the Product Bundle Identifier for the targets: WebDriverAgentLib, WebDriverAgentRunner, and WebDriverAgentUSB Client

3. Build the WebDriverAgent.xcodeproj ->> "Build Successful"

4. run appium with the same python test.

**Comment by imurchie** [comment]
You will still need to provide the information used for signing to the build process. This is done through the `xcodeConfigFile` desired capability, which is the full path to an `xcconfig` file you create with the information necessary.

**Comment by jayczech23** [comment]
Here are my capabilities

desired_caps = {}
desired_caps['appium-version'] = '1.0'
desired_caps['platformName'] = 'iOS'
desired_caps['platformVersion'] = '10.2'
desired_caps['deviceName'] = 'iPhone 6'
desired_caps['app'] = os.path.abspath('/Users/ueff/Desktop/iOSBuilds/iPhone6FMBuild.ipa')
desired_caps['noReset'] = True
desired_caps['udid'] = '889f82039dce7c9d45173dd8547b08363e74dcd2'
desired_caps['automationName'] = 'XCUITest'
desired_caps['bundleId'] = 'com.att.fleetmode.ios'
desired_caps['xcodeOrgId'] = 'V78S87P3ZH'
desired_caps['xcodeSigningId'] = 'iPhone Developer'
desired_caps['xcodeConfigFile'] = '/Users/ueff/Desktop/iosConfig.xcconfig'
#----------------------------------------------------------------------------------

I have DEVELOPMENT_TEAM and CODE_SIGN_IDENTITY in the xcconfig file

**Comment by imurchie** [comment]
And this still fails? Can you post the logs as a gist?

**Comment by jayczech23** [comment]
LOCAL TERMINAL LOGS:
https://gist.github.com/jayczech23/26d11d8203c83d25afbccaf4f5314a51

APPIUM LOGS:
https://gist.github.com/jayczech23/7b01e4c430f4d670dae74fd5c1767869

**Comment by imurchie** [comment]
Now can you try running the following and seeing what xcodebuild has to say?

```
cd /Users/ueff/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
xcodebuild build-for-testing test-without-building -project /Users/ueff/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=889f82039dce7c9d45173dd8547b08363e74dcd2 -configuration Debug -xcconfig /Users/ueff/Desktop/iosConfig.xcconfig
```

**Comment by jayczech23** [comment]
Here's the result of that command:

https://gist.github.com/jayczech23/5cb7faf28dbddfbd0e3d46eb034dfb67

**Comment by imurchie** [comment]
It is still using the old bundle id. Something was not changed.

```
Check dependencies
No profiles for 'com.facebook.IntegrationApp' were found:  Xcode couldn't find a provisioning profile matching 'com.facebook.IntegrationApp'.
Code signing is required for product type 'Application' in SDK 'iOS 10.2'

** TEST BUILD FAILED **
```

**Comment by jayczech23** [comment]
Oh I see, so does that mean I have to set 'com.facebook.IntegrationApp' as the provisioning profile for the WebDriverAgent.xcodeproj ?

**Comment by imurchie** [comment]
I don't know what you mean by that. You need to be able to build and sign WebDriverAgent with the command posted above. This seems, on your system,  to mean that you need to change the bundle identifier for the Integration App, though I have never seen that.

**Comment by jayczech23** [comment]
Okay, I went into the WebDriverAgent.xcodeproj and changed the provisioning profile for all targets manually, I think the provisioning file I was using wasn't giving me permission to use that profile with WebDriverAgent

**Comment by jayczech23** [comment]
@imurchie I tried the xcodebuild command after making some changes with the provisioning profiles. 

This was the result: 
https://gist.github.com/jayczech23/10a8019f3e163d837ff87418eae201c8

**Comment by imurchie** [comment]
That looks like your phone is not plugged in.

**Comment by jayczech23** [comment]
@imurchie After installing `xcpretty` and `ios-deploy` and changing the provisioning on WebDriver, I tried running a test again and am getting a new error now in the APPIUM logs.

APPIUM LOGS:
https://gist.github.com/jayczech23/1c2182af1529f99190677e0243172e4e

**Comment by jayczech23** [comment]
Fixed Error by only using the capabilities 'xodeOrgId' and 'xcodeSigningId' , before I was using these two along with the xcConfigFile capability.
