### ISSUE TITLE
IOS WebDriverAgent Proxying POST issue from second/further test runs in Appium 1.6.3

### ISSUE THREAD

**Issue by Vigneshh** [appium/appium#7814]
## The problem

I am performing ios webautomation, where i started appium(1.6.3) command from my java code (using process and processbuilder). Appium started sucessfully with its node config capabilities and configurations, which also got registered successfully with the selenium hub.

## Environment

macOS Sierra 10.12.1
xcode 8.2.1
Appium 1.6.3(Also tried 1.6.3)
Nodejs 7.2.0
Real Device iPhoneSE-iOS version 10.0.1
libimobiledevice --HEAD
selenium-server-standalone-3.0.1.jar(for hub)

## Details

The test run got successfully executed for the first time. The problem is, when i execute for the second time and further runs, it hangs and no indication of launching the safari browser.

So, i cant run any of my scripts untill i restart my iphone device. After restart, it will again run successfully for the first time and hangs from my next runs.

Even i checked for any iProxy process is open for the wdalocalport, but it is not available. Note sure, somewhere the WebdriverAgent holding its previous session when i start appium through java process.

## Link to Appium logs

Attaching the appium logs @ 
https://gist.github.com/Vigneshh/72dac8e108e96126ba4053807f3d9ff5

Note: Log contains first time successful execution as well followed by the second run execution which hangs. Meanwhile got an info in the HUG Log mentioned below,

HUB Log for references
INFO - Removed a session that had not yet assigned an external key 7e1e7755-0f55-4180-b49a-4a54ad4c366c, indicates failure in session creation PROXY_REREGISTRATION

## Code To Reproduce Issue [ Good To Have ]

Java Snippet @ 
https://gist.github.com/Vigneshh/302d7dc501fd04c6b1918c2fdc7942db
JsonConfigFile @ 
https://gist.github.com/Vigneshh/dfcd435cf31d1a431b60d8741b53b0b1

Can someone help me to resolve this.
Thank you

**Comment by mykola-mokhnach** [comment]
1. Do you quit the driver properly after your test finishes?
2. Try to set _useNewWDA_  capability to _false_ for keeping WDA from reinstall

**Comment by Vigneshh** [comment]
Thanks for your response @mykola-mokhnach

1.) Yes, my driver quits after my test got finished, i have used driver.quit();
2.) By default useNewWDA is false, i thought of WebDriverAgent issue and i gave useNewWDA as true and tried. But no luck in both the cases, it behaves the same.

**Comment by jlipps** [comment]
@Vigneshh please try with appium 1.6.4 and update here with _full_ appium logs (the ones you posted before only contain little http snippets)
