### ISSUE TITLE
Click using Horizontal position is no longer working on appium 1.6.4

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#7820]
Hi. 
I updated to appium 1.6.4 and after this update some clicks inside of my code are no longer working. (on 1.6.3 this worked)

For examample:
click(userEmail, Element.ELEMEN_TYPE_XCUIElementTypeStaticText, true, LEFT);

This is the click method:
ios.utils.WebElementHelpers.click(String id, String type, boolean strictValue, HorizontalPosition horizontalPositionOfFinger)

Click (tap) on a web element identified by its id and type. strinctValue indicates if the id should be identical (true) or element should just contain the given id (false). HorizontalPosition indicates where the element should be tapped. If element is not found or cannot be clicked, a retry mechanism is implemented. It will retry up to a set number of retries.

Parameters:
id
type
strictValue
horizontalPositionOfFinger

To make it work i need to remove the Horizontal position.
click(userEmail, Element.ELEMEN_TYPE_XCUIElementTypeStaticText, true);

 Any ideas whats happening here?

**Comment by imurchie** [comment]
Can you provide the logs? Without them it is impossible to know what is happening on the server.

**Comment by vjmaiky** [comment]
[log.pdf](https://github.com/appium/appium/files/758057/log.pdf)
if the format is not ok tell me please

**Comment by imurchie** [comment]
Just paste the logs into a [gist](https://gist.github.com). I cannot open a pdf.

**Comment by vjmaiky** [comment]
https://gist.github.com/vjmaiky/0ad951bf379199037244c99d8cd5f740#file-log

**Comment by vjmaiky** [comment]
any ideas here?

**Comment by jlipps** [comment]
Nothing seems odd in the logs. WDA is just not able to find the elements you're looking for. Did you print out the source before attempting to find them to ensure they are present in the tree?

**Comment by vjmaiky** [comment]
was fixed meanwhile.
