### ISSUE TITLE
WebDriverAgent is not starting if there is any pop up

### ISSUE THREAD

**Issue by thejuskrishna** [appium/appium#7821]
## The problem

I tried to run a script with a pop up (UI alertItem). Appium driver never starts and it is seen that WebDriverAgent is not started successfully.

Appium 1.6

**Comment by mykola-mokhnach** [comment]
Try to play with **waitForAppScript** capability.
Setting it to something like this

```
$.delay(3000); $.acceptAlert(); true;
```

might help to solve the thing

**Comment by imurchie** [comment]
`waitForAppScript` does not currently work for XCUITest-based tests. 

@thejuskrishna Can you provide logs as a [gist](https://gist.github.com), so we can at least try to see what is happening?

**Comment by thejuskrishna** [comment]
https://gist.github.com/thejuskrishna/1674b7624eeb209e98ec96243fc66bca

**Comment by imurchie** [comment]
What is the alert? This is happening before we have any control over the device (since we need WDA to load before we can do anything) so there is little that can be done.

**Comment by thejuskrishna** [comment]
There were few pop ups software update pop up, face time pop ups, apple store pop up - which comes very often. Also I tried running the xcodebuild command manually. Error has been added. https://gist.github.com/thejuskrishna/1c6aba60148c09d940bfc555a13a9d04

**Comment by imurchie** [comment]
There is nothing that can be done about alerts outside of Appium's automation of the device.

As for the other error, I cannot say without more information about the build context (what command is being used, is this a real device or sim, etc etc).

**Comment by adamlfs** [comment]
I had similar situation. When my test execution failed and there was an notification alert displayed then rest of test on that particular device failed because appium wasnt able to run AUT.
