### ISSUE TITLE
ID or Name missing in Inspector unless user manually navigates/refresh to another page and come back to the previous page 

### ISSUE THREAD

**Issue by alangithubtrader** [appium/appium#7824]
Spec
Appium: 1.6.3
Simuluator: iPhone 7 iOS 10.2
Appium c# client driver: 2..1.1
Xcode: 8.2.1
Mac: Sierra 10.12.2

In Xcode 7 (UIAutomation), the element is a UIATableGroup and it has 2 child elements that I was ABLE to access via ID/Name. However, after upgrading my system to Xcode 8 and using the new Appium server which supports the new Apple XCUITest framework, the UIATableGroup element became XCUIElementTypeTable (as expected) and its child elements' ID/Name is no long there UNLESS I manually navigate to another page and then come back.

Has anyone encountered this after making the switch from using the UIAutomation to XCUITest framework from Apple? Is this something that can be fixed on Xcode side or Appium side?

-Alan

**Comment by mykola-mokhnach** [comment]
Are these elements visible in the standard Accessibility Inspector?

**Comment by alangithubtrader** [comment]
Sorry to clarify, I was inspecting these elements using the Appium Inspector.

**Comment by mykola-mokhnach** [comment]
Desktop inspector is not supported anymore. Don't expect it to work properly.

I mean you need to use something like this to confirm your elements are available for accessibility in general
Xcode -> Open Developer Tools -> Accessibility Inspector

**Comment by alangithubtrader** [comment]
Thanks Mykola, I tried using the Xcode accessibility inspector and also could not access that element i mentioned in my op.  I am working with the developers on this issue. Thank you for you input. It was really helpful. Cheers.

-Alan
