### ISSUE TITLE
[Appium 1.6.4(beta)] : Xcode error 65 when running real iOS device with XCUITest

### ISSUE THREAD

**Issue by JESii** [appium/appium#7825]
## The problem

I've gotten the iOS Simulator running with XCUITest; now trying to get Real device tests working

## Environment

* Appium version (or git revision) that exhibits the issue:
1.6.4(beta)
* Last Appium version that did not exhibit the issue (if applicable):
N/A - Only have iOS simulator running
* Desktop OS/version used to run Appium:
OS X El Cap; 10.11.6
* Node.js version (unless using Appium.app|exe):
7.5.0
* Mobile platform/version under test:
iOS 9.3
* Real device or emulator/simulator:
Real device
* Appium CLI or Appium.app|exe:
appium CLI - command line is:
`appium -g ~/appium_server.log --log-timestamp --local-timezone --debug-log-spacing --tmp ~/tmp --default-capabilities '{"showXcodeLog": "true", "automationName": "XCUITest", "cssSelectorsEnabled": "true", "nativeEvents": "true", "nativeWebTap": "true"}'`
* Xcode version:
8.2.1

#### Additional environment details
* appium-ios-driver@1.16.0  (installed with -g option)
* appium-xcuitest-driver@2.7.0  (installed with -g option)
* authorize-ios@1.0.4  (installed with -g option)
* ios-deploy@1.9.1 (installed with -g option)
*` ios_webkit_debug_proxy --debug` running in another terminal window and connected to my device ("JON's iPad") 
* libimobiledevice: stable 1.2.0 (bottled), HEAD
* .xcconfig created with:
`DEVELOPMENT_TEAM = XXXXXXXXXX`
`CODE_SIGN_IDENTITY = iPhone Developer`

## Details

I'm running a ruby/cucumber test with the following command line; this currently works on Chrome browser and appium iOS Simulator:
`bundle exec cucumber   DEVICE=Iphone -p mobile_website_default     SITE=MCOM URL=http://m.qa19codemacys.fds.com/  features/website/Selection/MEW/registry/MCOM/registry_navigation.feature:14`

Failure messages from cucumber:
```
An unknown server-side error occurred while processing the command. Original error: xcodebuild failed with code 65 (Selenium::WebDriver::Error::UnknownError)
 /Users/yc98js1/.rvm/gems/ruby-2.0.0-p643/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
 /Users/yc98js1/.rvm/gems/ruby-2.0.0-p643/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
 /Users/yc98js1/.rvm/gems/ruby-2.0.0-p643/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
 /Users/yc98js1/.rvm/gems/ruby-2.0.0-p643/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:78:in `create_response'
 /Users/yc98js1/.rvm/gems/ruby-2.0.0-p643/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
 /Users/yc98js1/.rvm/gems/ruby-2.0.0-p643/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
 /Users/yc98js1/.rvm/gems/ruby-2.0.0-p643/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:649:in `raw_execute'
 /Users/yc98js1/.rvm/gems/ruby-2.0.0-p643/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:123:in `create_session'
 /Users/yc98js1/.rvm/gems/ruby-2.0.0-p643/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:87:in `initialize'
 /Users/yc98js1/.rvm/gems/ruby-2.0.0-p643/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/common/driver.rb:59:in `new'
 /Users/yc98js1/.rvm/gems/ruby-2.0.0-p643/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/common/driver.rb:59:in `for'
 /Users/yc98js1/.rvm/gems/ruby-2.0.0-p643/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver.rb:84:in `for'
 /Users/yc98js1/dev/QAA/support/mobile_website/mobile_device/base.rb:7:in `perform'
 /Users/yc98js1/dev/QAA/support/mobile_website/mobile_device/base.rb:17:in `open'
 /Users/yc98js1/dev/QAA/support/mobile_website/mobile_device/base.rb:12:in `initialize'
 /Users/yc98js1/dev/QAA/support/mobile_website/mobile_browser.rb:15:in `new'
 /Users/yc98js1/dev/QAA/support/mobile_website/mobile_browser.rb:15:in `start'
 /Users/yc98js1/dev/QAA/support/mobile_website/hooks.rb:6:in `Before'
```

## Link to Appium logs

Appium logs (which include the Xcode log as well): https://gist.github.com/JESii/a19d3554fc86b89b0bf621fa21f5cf8d

In case it helps, here's the Xcode build log: https://gist.github.com/JESii/14e0888d10e95919f6e53693bdce7a0d

## Code To Reproduce Issue [ Good To Have ]

Testing mobile web, not app

**Comment by mykola-mokhnach** [comment]
WDA sources are not signed. Follow the real device config [tutorial](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md) to get it working.

**Comment by JESii** [comment]
Thanks; thought I had done all that (updated the original comment) but there's obviously some kind of profile issue. I'll check that out and update this when I learn more.

**Comment by JESii** [comment]
OK; I've run through all that and have gotten beyond the build 65 error (redid my .xcconfig settings, reinstalled appium-xcuitest-driver, reinstalled ios-deploy). However, I'm am now seeing only appium.io on the device screen and repeated errors like so:
```
2017-02-10 08:16:48:229 - info: [debug] [iOS] No web frames found.
2017-02-10 08:16:48:229 - warn: [iOS] Could not find any webviews yet, refreshing/retrying
```

Also, I am not able to see the "Settings | General | Profiles & Device Manager" as described by that page.

So... I'll close this issue and open another one focusing on these latest issues.
