### ISSUE TITLE
Appium hangs if system clock is ahead than the device's clock (iOS, XCUITest)

### ISSUE THREAD

**Issue by Schnutzel** [appium/appium#7826]
## The problem

When starting the xcuitest driver on a real device, it checks the logs and compares the current system time to the time when the "ServerURLHere" message was displayed. If the system clock is ahead of the device's clock, this will cause the driver to hang, because it will assume this was an old log message.

## Environment

* Appium version: 1.6.3
* Real device or emulator/simulator: real device

**Comment by imurchie** [comment]
This is fixed in 1.6.4-beta. Install with `npm uninstall -g appium && npm install -g appium@beta`.
