### ISSUE TITLE
[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1

### ISSUE THREAD

**Issue by jtappi** [appium/appium#7830]
## The problem
Hi all, 
I am trying to get a fresh Appium install to run on my mac.  I am running into an error when starting the test run.  Everything installed without any error messages.

***By the way, i can find the so called 'missing' file in my WebDriver folder.

[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Sierra (10.12.3)
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test: iPhone Simulator (6s v10.2)
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: N/A

## Details

Basically, the test never gets going.  Appium boots up, installs the App and crashes as soon as it Launches the WebDriverAgent on the Device.

## Link to Appium logs
***Log is short so i am pasting

myMAC:~ myUserName$ /usr/local/bin/node /Users/myUserName/node_modules/appium/build/lib/main.js
[Appium] Welcome to Appium v1.6.3
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/myUserName/Downloads/myAppName.app","platformName":"iOS","platformVersion":"10.2","deviceName":"iPhone 6s","newCommandTimeout":90000,"launchTimeout":90000,"noReset":true,"automationName":"XCUITest"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/myUserName/Downloads/myAppName.app","platformName":"iOS","platformVersion":"10.2","deviceName":"iPhone 6s","newCommandTimeout":90000,"launchTimeout":90000,"noReset":true,"automationName":"XCUITest"},null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/myUserName/Downloads/myAppName.app'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '10.2'
[Appium]   deviceName: 'iPhone 6s'
[Appium]   newCommandTimeout: 90000
[Appium]   launchTimeout: 90000
[Appium]   noReset: true
[Appium]   automationName: 'XCUITest'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] Session created with session id: dc1ccc46-62a4-496f-9235-bebf87fbfa58
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[iOSSim] Constructing iOS simulator for Xcode version 8.2.1 with udid '1EC2D583-07AA-446D-A9AF-2B38F4F2C1E1'
[XCUITest] Determining device to run tests on: udid: '1EC2D583-07AA-446D-A9AF-2B38F4F2C1E1', real device: false
[BaseDriver] Using local app '/Users/myUserName/Downloads/myAppName.app'
[debug] [XCUITest] Checking whether app '/Users/myUserName/Downloads/myAppName.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/Users/myUserName/Downloads/myAppName.app': 'com.myAppName.myAppExtension'
[debug] [iOSLog] Starting iOS 10.2 simulator log capture
[debug] [iOSLog] System log path: /Users/myUserName/Library/Logs/CoreSimulator/1EC2D583-07AA-446D-A9AF-2B38F4F2C1E1/system.log
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid '1EC2D583-07AA-446D-A9AF-2B38F4F2C1E1' already booted
[debug] [XCUITest] Installing app '/Users/myUserName/Downloads/myAppName.app' on device
[XCUITest] Using WDA path: '/Users/myUserName/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/myUserName/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
 { Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  stdout: '\u001b[1mFetching dependencies\n',
  stderr: 'Error: Command "bootstrap" does not exist.\n',
  code: 1 }
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Reset not set, not ending sim
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

**Comment by imurchie** [comment]
What is the output of the following:

```
cd /Users/myUserName/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/
/bin/bash Scripts/bootstrap.sh -d
```

**Comment by jtappi** [comment]
-bash: cd: /Users/myUserName/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/bin/bash: No such file or directory

**Comment by imurchie** [comment]
Those are two different things. First  `cd /Users/myUserName/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/` then `/bin/bash Scripts/bootstrap.sh -d`.

**Comment by jtappi** [comment]
ha..no excuse, my fault.

Fetching dependencies
Error: Command "bootstrap" does not exist.

**Comment by imurchie** [comment]
Can you run `carthage bootstrap`?

**Comment by imurchie** [comment]
Also, how did you install Appium?

**Comment by jtappi** [comment]
carthage bootstrap
Error: Command "bootstrap" does not exist.

I used npm (npm install -g appium)

**Comment by jtappi** [comment]
i also installed carthage the same way.  
carthage version
Carthage Version: 1.0.6
Built internally @ devagnos.com

**Comment by imurchie** [comment]
Something is wrong with your Carthage installation. What version is it? `carthage version`

**Comment by jtappi** [comment]
Carthage Version: 1.0.6
Built internally @ devagnos.com

**Comment by imurchie** [comment]
Weird. I would uninstall and re-install. According to Carthage the latest is 0.18.1.

https://github.com/Carthage/Carthage/releases

**Comment by jtappi** [comment]
@imurchie Thanks a lot for the quick answers!  

I'll try to uninstall/reinstall

**Comment by jtappi** [comment]
Thanks again @imurchie, my issue has been resolved!

I uninstalled carthage and installed it using the link from your post.  I downloaded the package and it moved past that failure.

**Comment by imurchie** [comment]
Awesome! Glad to hear it.

**Comment by PrakashChoudhary-20** [comment]
Hi, 

I am getting this error : fatal: repository 'https://github.com/marekcirkos/peertalk.git/' not found
When I execute ./Script/bootstrap.sh -d 
How to solve this? Can you help please?

More information : 
Carthage version : 0.23.0
Appium version : 1.6.3
Installed appium via npm command.

Thanks.

**Comment by imurchie** [comment]
Appium 1.6.3 had a dependency that the owner deleted. It is no longer available, and any initial use of it for iOS will fail. 

The only solution is to upgrade.

**Comment by messianic** [comment]
:WebDriverAgent qksysadmin$ ./Scripts/bootstrap.sh -d
Fetching dependencies
Please update to the latest Carthage version: 0.24.0. You currently are on 0.23.0
*** Cloning peertalk
*** Checking out peertalk at "v1.0"
*** Cloning peertalk
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/marekcirkos/peertalk.git /Users/qksysadmin/Library/Caches/org.carthage.CarthageKit/dependencies/peertalk) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled


Getting this when running ./Scripts/bootstrap.sh -d
Help...

**Comment by imurchie** [comment]
@messianic Please upgrade Appium. As per above, version 1.6.3 and below have dependencies that no longer exist.
