### ISSUE TITLE
Session-specific logs via a new capability (e.g. sessionLog)

### ISSUE THREAD

**Issue by ohadschn** [appium/appium#7831]
Suppose I want to run multiple tests on the same host in my CI build. I can't do it using different appium processes due to shared processes that might get killed (e.g. iproxy and xcodebuild): https://github.com/appium/appium/issues/7373.

Therefore the only reliable approach would be to use different sessions in the same appium process. The problem is that logs from all sessions will blend together and test failures will be hard to debug. Ideally, each session could have its own log file (via something like a `sessionLog` capability). 

That way I can start the session, log it to `session123.txt`, and then when the suite completes take that specific file and archive it as an artifact (using Jenkins terminology) / print it in my build.

**Comment by jlipps** [comment]
We're actually solving the problem more directly by disentangling the processes and killing logic. (See recent work in appium-ios-simulator and appium-xcuitest-driver. But I'll keep this open as a lower-priority feature request.

**Comment by mykola-mokhnach** [comment]
I think it would be hardly possible to implement something like this with the current architecture. Currently drivers have their own loggers which know about sessions, but static APIs don't have it and use shared static loggers connected to their modules.
