### ISSUE TITLE
Appium kills my device logger when calling driver.launchApp(), if it is same logger as set in desired_capabilities.

### ISSUE THREAD

**Issue by ashwither** [appium/appium#7832]
## Issue

When I run an iOS device logger of the same type as the one being specified in **readDeviceLogger** (of desired capabilities), my log process gets killed every time I launch the app on the device.

## Environment

* Appium (1.6.3)
* macOS Sierra (10.12.3)
* Node (5.3.0)
* Python 2.7.11
* Tested on iOS 9.3-10.2.1 (not tested on other OS versions)
* Using XCUITest
* Real devices (not tested on Sim)
* Appium-Python-Client (0.22)

## Details

This issue has been occurring for both **idevicesyslog** and **deviceconsole**. The issue does not occur if I use one device log utility for my processes, and another to pass into realDeviceLogger for Appium to use. While checking the process queue, I noticed that Appium appears to use one process of **idevicesyslog** regardless of designation in desired capabilities (for whatever reason), and then uses a second device logger instance (whichever one is user specified) when calling **driver.launchApp()**. It is a that time when Appium appears to kill my device logger instance.

Why is Appium killing my device logging process?

## Workaround
I am now polling my processes, and just restarting it if it dies. I am also setting my desired capabilities logger to be different than my own log reader. This is an effective method for getting around this issue, but it seems to me that APpium should not be killing my logger process in the first place.

## Code To Reproduce Issue

```
from appium import webdriver
import subprocess
import time

device_id = "<UDID>"

class Driver:
    def __init__(self):
        self.driver = webdriver.Remote(
            command_executor='http://127.0.0.1:4723/wd/hub',
            desired_capabilities={
                'bundleId': "com.application.Name",
                'platformName': 'iOS',
                'deviceName': "iOS Real Device",
                'udid': device_id,
                'showXcodeLog': 'true',
                'automationName': 'XCUITest',
                'realDeviceLogger': 'idevicesyslog',
                'xcodeOrgId': 'ABCDEFG1234',
                "xcodeSigningId": "iPhone Developer",
            }
        )


def is_syslog_alive():
    if syslog.poll() is not None:
        print "[SYSLOG] DEAD!"
    else:
        print "[SYSLOG] Alive"


device_driver = Driver()
syslog = subprocess.Popen(['idevicesyslog', "-u", device_id], stdout=subprocess.PIPE)

while True:
    print "App is launching (wait 10s)"
    time.sleep(10)
    is_syslog_alive() # Syslog is alive

    print "Closing App"
    device_driver.driver.close_app()
    time.sleep(3)
    is_syslog_alive() # Syslog is alive

    print "Launching App"
    device_driver.driver.launch_app()
    time.sleep(2)
    is_syslog_alive() # Syslog is killed!

```

**Comment by imurchie** [comment]
Upgrade to 1.6.4-beta (`npm uninstall -g appium && npm install -g appium@beta`). It no longer uses the real device logger (the `realDeviceLogger` cap is no longer valid) and the problem should not persist.

**Comment by ashwither** [comment]
I updated to the Appium 1.6.4 beta, and can confirm that my idevicesyslog process is no longer getting killed (by the Appium server). However, it appears that the Appium server is now spawning new idevicesyslog instances each time I launch the app. This occurs regardless of whether or not I use either device logger type on my own (idevicesyslog / deviceconsole).

#7838

**Comment by imurchie** [comment]
Closing. See #7838.
