### ISSUE TITLE
scroll to non visible element in appium with iOS is not working for me. 

### ISSUE THREAD

**Issue by saritau** [appium/appium#7834]
## The problem
I am trying to scroll to an invisible element. Not able to get its location as its not in visible area.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Last Appium version that did not exhibit the issue (if applicable):1.5.8
* Desktop OS/version used to run Appium:mac
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:

Failing at WebElement uiElement = getDriver().findElementByName("xyz");

Failing at xyz step, as xyz is not visible.

**Comment by imurchie** [comment]
You will need to manually scroll. Easiest way is with `execute('mobile: scroll', {element: el, toVisible: true})` (you'll need to adjust the syntax for whatever language you are using).
