### ISSUE TITLE
Do we have any Appium API to get the iOS device's time format (12H or 24H) ?

### ISSUE THREAD

**Issue by adarshem** [appium/appium#7835]
## The problem
Since we have no option to set the iOS device's time format (12 or 24) , I would like to get the time format set in the 'Settings >General >Date & Time' 

The 'idevicedate -s udid' always provide a value which is in 24 hour format even though the device format is in 12H.
E.g : Thu Feb  9 15:23:39 IST 2017

## Environment

* Appium version (or git revision) that exhibits the issue: Java - client 5.0.0 beta2
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC OS Sierra 10.12
* Node.js version (unless using Appium.app|exe):1.6.1
* Mobile platform/version under test: IOS / 10.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[debug] [MJSONWP] Calling AppiumDriver.getDeviceTime() with args: ["7c9442d8-e113-484c-84f4-468c43a6d896"]
[debug] [XCUITest] Executing command 'getDeviceTime'
[iOS] Attempting to capture iOS device date and time
[iOS] Found idevicedate: '/usr/local/bin/idevicedate'
[debug] [MJSONWP] Responding to client with driver.getDeviceTime() result: "Invalid Date"

**Comment by mykola-mokhnach** [comment]
I don't think this is possible with idevicedate tool, since it has no configurable interfaces for changing the output format. Is it a problem to convert the date in client code though?

**Comment by adarshem** [comment]
Thank You @mykola-mokhnach 

Why I asked this because , irrespective of the device time format the output value of 'idivicedate -s udid' always in 24H format! With this out put we would not be able to understand the Time-format of the device(12H or 24H). We can convert the date in client code but that will not satisfy what I required. I want to pass some test data for validation based on the device time format.

For iOS10.x devices now I have created my own method to check the device time format in my automation framework:

public static void checkIOSDeviceTimeFormat() {
		if (defaultIOSDriver != null) {
			try {
				MobileElement ele = (MobileElement) defaultIOSDriver.findElement(
						By.xpath(".//XCUIElementTypeOther[contains(@label,'PM') or contains(@label,'AM')]"));
				logger.info("Device time is found set in 12-Hour format.");
				isIosDeviceTimeFormat24H = false;
			} catch (Exception e) {
				logger.info("Device time is found set in 24-Hour format.");
				isIosDeviceTimeFormat24H = true;
			}
		}


I am closing this ticket as per your comments.

Thanks!
Adarsh E M

**Comment by saj94** [comment]
@adarshem , how do you get the datetime in the first place , the appium log shows that the date is not returned : 
Responding to client with driver.getDeviceTime() result: "Invalid Date"

**Comment by adarshem** [comment]
@saj94 I 

Sorry for the confusion. For IOS i have created a custom method to retrieve the device data and time:
I used the RunTime Executor and executed the shell command 'idevicedate -s udid' and take the out put into a string variable.
Runtime.getRuntime().exec("idevicedate -s "+udid )


TH o/p will be something like : Thu Feb 9 15:23:39 IST 2017

**Comment by imurchie** [comment]
The latest Appium version should return the output of `idevicedate` directly, if there is any problem with parsing it (which is what brought about the `"Invalid Date"` return value).

**Comment by saj94** [comment]
@imurchie , yeah there is a parsing error in appium 1.7.1 when it tries to return the date from idevicedate.

**Comment by imurchie** [comment]
Weird. I thought that had been fixed. Alas.

https://github.com/appium/appium-ios-driver/pull/254

**Comment by saj94** [comment]
@imurchie I still face this issue 

https://github.com/appium/appium/issues/9514

**Comment by imurchie** [comment]
Can you post the appium server logs as a link to a [gist](https://gist.github.com)? There is nothing that can be done without them.
