### ISSUE TITLE
Appium 1.6.4 always open the same simulator in spite of sending capability UDID

### ISSUE THREAD

**Issue by jeevanshu30** [appium/appium#7836]
## The problem
 
Using xcrun simctl i was able to install an .app file on simulator. But from code if hit appium server it always open same simulator where app is getting crashed.

Is there any settings because appium not able to find devises listed in xcrun simctl list command.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4
* Desktop OS/version used to run Appium: MAC
* Mobile platform/version under test: IOS
* Real device or emulator/simulator: Simulator

**Comment by mykola-mokhnach** [comment]
We won't be able to help without logs and  the actual _xcrun simctl list_ command output

**Comment by jeevanshu30** [comment]
**Please find below xcrun simctl list logs with iphone 6s plus booted**

lab-mac-358bc4:~ labuser$ xcrun simctl list
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
Apple TV 1080p (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
== Runtimes ==
iOS 9.2 (9.2 - 13C75) (com.apple.CoreSimulator.SimRuntime.iOS-9-2)
iOS 9.3 (9.3 - 13E233) (com.apple.CoreSimulator.SimRuntime.iOS-9-3)
iOS 10.2 (10.2 - 14C89) (com.apple.CoreSimulator.SimRuntime.iOS-10-2)
tvOS 10.1 (10.1 - 14U591) (com.apple.CoreSimulator.SimRuntime.tvOS-10-1)
watchOS 3.1 (3.1 - 14S471a) (com.apple.CoreSimulator.SimRuntime.watchOS-3-1)
== Devices ==
-- iOS 9.2 --
    iPhone 4s (180332C0-7F41-4A96-8E45-609C81EC5749) (Shutdown)
    iPhone 5 (A1C0F08C-BDF5-437B-8F37-6729D5EE0263) (Shutdown)
    iPhone 5s (FF09468C-FE15-4284-89A2-87DD40E66C0E) (Shutdown)
    iPhone 6 (381C72D2-4500-4DA4-9C4A-198F4FDA2D4D) (Shutdown)
    iPhone 6 Plus (CCCA487B-4263-4B77-A498-8DCF81268CA2) (Shutdown)
    iPhone 6s (FE1B9FFE-CAC2-4588-BDE8-68ED171D48C1) (Shutdown)
    iPhone 6s Plus (C73B55C8-241D-411D-8D90-17F7A4DFAA14) (Shutdown)
    iPad 2 (0AFF4557-8096-43B6-9186-46C1301FD9EF) (Shutdown)
    iPad Retina (7D5B8272-0A6E-4510-9638-0023151BDDC0) (Shutdown)
    iPad Air (76F2726B-B720-49F3-BC66-152810F21234) (Shutdown)
    iPad Air 2 (BDDE71D8-BA7A-4028-96D7-3F86CD5DEB6B) (Shutdown)
    iPad Pro (CB154436-A5BA-488F-B080-EB893402EA39) (Shutdown)
-- iOS 9.3 --
    iPhone 4s (7A93817D-D545-418A-B654-F70E9106DF52) (Shutdown)
    iPhone 5 (73F3E471-06E3-4D35-92CF-44F73A16DDEA) (Shutdown)
    iPhone 5s (AF05465B-7A4C-48E7-9A74-1854C861319B) (Shutdown)
    iPhone 6 (0A1C450C-1DA7-47FD-AB18-FFDD129CE04E) (Shutdown)
    iPhone 6 Plus (E8A24CEB-CE96-4257-B2CF-F34B0977D1A1) (Shutdown)
    iPhone 6s (1B082CB5-617E-4B30-9005-0E5BC89B78D0) (Shutdown)
    iPhone 6s Plus (FB714EFD-0457-43BD-86B1-BF5A6E755830) (Booted)
    iPad 2 (3B625774-963E-4CC5-9E11-7A1F9C7034CD) (Shutdown)
    iPad Retina (3D39CFBD-CD72-42FE-9B26-699E48838A76) (Shutdown)
    iPad Air (A4D24BD7-2346-4C7F-98B5-F2FADEFB3FCF) (Shutdown)
    iPad Air 2 (70426179-7241-454B-AA2B-283B9BA9F1E0) (Shutdown)
    iPad Pro (AA6B0FF7-32C4-44CC-8540-421B543C5129) (Shutdown)
-- iOS 10.2 --
    iPhone 5 (6C9C6024-B6D9-4A94-937C-666AD443CAB5) (Shutdown)
    iPhone 5s (F90F4E1E-047B-4217-8F36-ED6FE9A538E5) (Shutdown)
    iPhone 6 (9F38C4ED-44E4-41FB-A415-2D662E69EF0E) (Shutdown)
    iPhone 6 Plus (3309146D-8B20-4D02-8BBE-4B53535334D4) (Shutdown)
    iPhone 6s (3927E35D-5D96-475D-B911-F06190DBB75F) (Shutdown)
    iPhone 6s Plus (C4CB7547-021A-40CC-91F4-BA849727722B) (Shutdown)
    iPhone 7 (7FD71280-C4A9-400F-BF8B-6CC7DCBA2558) (Shutdown)
    iPhone 7 Plus (7DF81832-2694-4D0A-9420-DE882BC620F1) (Shutdown)
    iPhone SE (9E251E7C-BBD6-4944-B0E6-CEFACCBEE50F) (Shutdown)
    iPhone SE (A829ECE0-1CD9-4D63-963B-2593DD17AFE6) (Shutdown)
    iPad Retina (CF9B65FC-5703-4DCF-8B91-00CC0191E38B) (Shutdown)
    iPad Air (18787867-1345-4497-A0C8-83D4B4EA89D0) (Shutdown)
    iPad Air 2 (985C488C-0420-4709-890C-C8FF10A0F7FF) (Shutdown)
    iPad Pro (9.7 inch) (2FB92809-5C3C-4D6F-85B5-9B3A85A55A6A) (Shutdown)
    iPad Pro (12.9 inch) (C871AAD2-01C6-4762-8B7F-4C7896FF6A1C) (Shutdown)
-- tvOS 10.1 --
    Apple TV 1080p (5529DD17-F663-4B92-8BCF-EE5118190C8E) (Shutdown)
-- watchOS 3.1 --
    Apple Watch - 38mm (FC7ED2CE-810F-4A8A-B869-2667169183EF) (Shutdown)
    Apple Watch - 42mm (3CE18D43-990D-47B2-93FF-E068723505E6) (Shutdown)
    Apple Watch Series 2 - 38mm (C50F0682-167E-431E-9E3F-E641F0FEC47F) (Shutdown)
    Apple Watch Series 2 - 42mm (62A7A244-0C11-4825-B1CB-3D06788071B3) (Shutdown)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-9-2 --
    Apple TV 1080p (66511DB5-C2BC-43B0-BA5A-7D2F8B0EE0B2) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-2-2 --
    Apple Watch - 38mm (1CEB921A-00CF-47C0-B242-A59EDFDEAEA1) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (17C85E81-F37C-4EB2-B433-F76EB40F7DCF) (Shutdown) (unavailable, runtime profile not found)
== Device Pairs ==
7DCC6B39-A5DA-495F-A188-21FDBFAB5E39 (active, disconnected)
    Watch: Apple Watch Series 2 - 38mm (C50F0682-167E-431E-9E3F-E641F0FEC47F) (Shutdown)
    Phone: iPhone 7 (7FD71280-C4A9-400F-BF8B-6CC7DCBA2558) (Shutdown)
B5BAA00B-B2D9-4B82-B5E4-071E40B430F1 (active, disconnected)
    Watch: Apple Watch Series 2 - 42mm (62A7A244-0C11-4825-B1CB-3D06788071B3) (Shutdown)
    Phone: iPhone 7 Plus (7DF81832-2694-4D0A-9420-DE882BC620F1) (Shutdown)
E8E7322A-F0F3-4DCF-8F29-D15DF95B7907 (unavailable)
    Watch: Apple Watch - 38mm (1CEB921A-00CF-47C0-B242-A59EDFDEAEA1) (Shutdown)
    Phone: iPhone 6s (1B082CB5-617E-4B30-9005-0E5BC89B78D0) (Shutdown)
F2124400-6CC2-4673-8095-14A05A74E490 (unavailable)
    Watch: Apple Watch - 42mm (17C85E81-F37C-4EB2-B433-F76EB40F7DCF) (Shutdown)
    Phone: iPhone 6s Plus (FB714EFD-0457-43BD-86B1-BF5A6E755830) (Booted)

**Comment by mykola-mokhnach** [comment]
I don't see Appium log

**Comment by jeevanshu30** [comment]
**Please find below the Appium server logs**

[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"nativeInstrumentsLib":"true","platformVersion":"9.3","automationName":"XCUITest","bundleId":"XYZ","udid":"FB714EFD-0457-43BD-86B1-BF5A6E755830","platformName":"iOS","deviceName":"iPhone 6s Plus","platform":"iOS"},{},null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   nativeInstrumentsLib: 'true'
[Appium]   platformVersion: '9.3'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'XYZ'
[Appium]   udid: 'FB714EFD-0457-43BD-86B1-BF5A6E755830'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6s Plus'
[Appium]   platform: 'iOS'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] Capability 'nativeInstrumentsLib' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: platform.
[BaseDriver] Session created with session id: ee5deb65-3481-475b-ba33-7d87c904ae4d
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [XCUITest] Available devices: 
[XCUITest] Error: Unknown device or simulator UDID: 'FB714EFD-0457-43BD-86B1-BF5A6E755830'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:437:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unknown device or simulator UDID: 'FB714EFD-0457-43BD-86B1-BF5A6E755830'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:437:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [XCUITest] Running iOS simulator reset flow
[MJSONWP] Encountered internal error running command: Error: Unknown device or simulator UDID: 'FB714EFD-0457-43BD-86B1-BF5A6E755830'
    at XCUITestDriver.determineDevice$ (../../lib/driver.js:437:17)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 72 ms - 209 
[HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"nativeInstrumentsLib":"true","platformVersion":"9.3","automationName":"XCUITest","bundleId":"XYZ","udid":"FB714EFD-0457-43BD-86B1-BF5A6E755830","platformName":"iOS","deviceName":"iPhone 6s Plus","platform":"iOS"},"requiredCapabilities":{}}}
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id","sessionId","id"]} and you sent ["capabilities"]
[HTTP] <-- POST /wd/hub/session 400 0 ms - 307

**Comment by mykola-mokhnach** [comment]
Try to exclude udid from your capabilities. having **deviceName** and **platformVersion** set should suffice to start the sim.

**Comment by jeevanshu30** [comment]
But the sim which it is starting is not in the simctl list , it always start the same sim which is not listed in simctl list.

**Comment by mykola-mokhnach** [comment]
And which one do you want to be started?

**Comment by jeevanshu30** [comment]
Any sim listed in the xcrun simctl list command.

**Comment by mykola-mokhnach** [comment]
sorry, but I don't have any other suggestions yet, except of the one above (exclude UDID).

**Comment by jeevanshu30** [comment]
okay is there any settings where we can tell appium to search for simctl simulators.

**Comment by jeevanshu30** [comment]
or any way ou to connect appium driver to already open simulator . (simctl simulator)

**Comment by mykola-mokhnach** [comment]
there is **noReset** capability and you can set it to **true**

**Comment by jeevanshu30** [comment]
basically the device ID appium is trying to open up is not available in simctl so the installing is getting failed. 
I dont know from where it is picking the default simulator.

**Comment by imurchie** [comment]
The issue here is larger. Your Appium system is not registering _any_ devices:
```
[debug] [XCUITest] Available devices: 
```
In your case this shouldn't be printed out, but if it is, it should have everything in the device list from `xcrun simctl list`. I've piped your output through Appium's parser and all is well.

**Comment by imurchie** [comment]
Is the Appium process run in the same terminal as the `xcrun simctl list` command? Is xcode the same?

**Comment by tom00** [comment]
Thanks @imurchie! Your post gave me the hint on the same issue. It turned out I had Appium server run by a different user than the executed selenium test.
