### ISSUE TITLE
Sandbox mode for untrusted appuim scripts

### ISSUE THREAD

**Issue by giantpune** [appium/appium#7839]
## The problem

I would like to run apps with Appium scripts which are submitted by users and are considered untrusted code.  I would like to sandbox the scripts in such a way where it cannot break the system it is running on and can be restricted to a specific device out of several devices connected via usb. 

## Environment

* Appium version - latest git master branch
* Last Appium version that did not exhibit the issue (if applicable): None
* Desktop OS/version used to run Appium: Linux, ubuntu 14.04, x86_64
* Node.js version (unless using Appium.app|exe): whatever your latest required version is.  i'm flexible.
* Mobile platform/version under test: Android 6.0.1 and iOS 9/10
* Real device or emulator/simulator: real devices
* Appium CLI or Appium.app|exe: either.  prefer the CLI, but again, I'm flexible.

**Comment by crummy** [comment]
Can you just run multiple VMs or Docker containers with a single Appium instance and a single device mounted each?

**Comment by jlipps** [comment]
While an interesting question, this really isn't an issue. Feel free to keep dialoguing here but I'm going to close it for the purposes of our issue tracker.
