### ISSUE TITLE
Cannot start previously working iOS tests on Appium 1.6.3

### ISSUE THREAD

**Issue by xshuRoadie** [appium/appium#7840]
## The problem

I have appium 1.6.1 (installed last year) as well as 1.6.3 (just installed). A same test runs perfectly with 1.6.1 but failed right away with 1.6.3. 

## Environment

* Appium version (or git revision) that exhibits the issue:  1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.6.1
* Desktop OS/version used to run Appium: macOSierra 10.12.3
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Real Device

## Link to Appium logs

https://gist.github.com/xshuRoadie/6cda8bf76ebc9a936e2995c8ac04f0de#file-1-6-3_test_fail-txt

## Code To Reproduce Issue [ Good To Have ]

I wonder if "desired_capbilities" needs to change. Here are mine that work with 1.6.1 but not 1.6.3
IPHONE_6Plus_iOS10={
        'deviceName': 'QA 6-Plus',
        'platformName': 'iOS',
        'platformVersion': '10.2.1',
        'udid': '{a real udid}', 
        'autoAcceptAlerts': 'true',
        'newCommandTimeout': 240,
        'automationName': 'XCUITest',
       'realDeviceLogger':'/Users/someone/.node/lib/node_modules/deviceconsole/deviceconsole',
        'xcodeConfigFile': '/Users/someone/someone/src/myconfig.xcconfig',
        'fullReset': 'true'
    }

**Comment by imurchie** [comment]
Please try 1.6.4-beta. It fixed this problem. (`npm uninstall -g appium && npm install -g appium@beta`).

**Comment by xshuRoadie** [comment]
Got it running. Thank you! @imurchie
