### ISSUE TITLE
appium-xcuitest -Can't click/tap on keyboard search button when device in landscape mode

### ISSUE THREAD

**Issue by qakapil** [appium/appium#7841]
I have noticed this issue in LANDSCAPE orientation only. xcuitest does recognize the Search button on the keyboard. However, when it fires the click() method, nothing happens

* Appium version - appium@1.6.4-beta
* Device - iPad2, iPad pro
* OS - iOS9.3
* Appium client bindings - Python

**Comment by mykola-mokhnach** [comment]
There's known XCTest bug and we can do nothing in Appium to fix it. Although you can try to run the test on iOS 10.0+, where it is supposed to be OK.
