### ISSUE TITLE
swipe bug

### ISSUE THREAD

**Issue by desided** [appium/appium#7842]
## The problem

swipe dont work, i think it bug, help please

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): -
* Desktop OS/version used to run Appium:ubuntu 16.04
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test:android 5.1
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe: cli

## Details
swipe stop on check of boolean - driver.findElement(By.name("Russian Federation")).isDisplayed() - its can be give true or false, but script crash. Swipe great work without find element, and also findelement - work great if element is already on screen.
 i cant understand, try ewerything.

## Link to Appium logs

logs https://gist.github.com/desided/c35644cc5984205ad3bc1116c6e891b3

## Code To Reproduce Issue [ Good To Have ]

code https://gist.github.com/desided/1cef5005e4c4ed456d1504212dae69bd 
element it is on screen but need to swipe, try find by xpart, classname, etc - nothing works

**Comment by desided** [comment]
also i tried 
this code 
        MobileElement mobElement = (MobileElement) driver.findElement(By.xpath("//android.widget.CheckedTextView[contains(@text, 'Russian Federation')]"));
        JavascriptExecutor js = (JavascriptExecutor) driver;
        HashMap<String, String> scrollByObj = new HashMap<String, String>();
        scrollByObj.put("direction", "up");
        scrollByObj.put("element", ((RemoteWebElement) mobElement).getText());
        scrollByObj.put("text", "Russian Federation");
        js.executeScript("mobile: scroll", scrollByObj);

**Comment by RockChild** [comment]
Man, sorry but how stuck search of element is related to swipe()? You have problems with element identification, not swipe.

**Comment by Siddh010** [comment]
Should the Element be String or WebElement Object ? in below code ...
scrollByObj.put("element", ((RemoteWebElement) mobElement).getText());

**Comment by jlipps** [comment]
"mobile: scroll" is not implemented for android...
