### ISSUE TITLE
print out xcodebuild logs

### ISSUE THREAD

**Issue by ohadschn** [appium/appium#7844]
It seems like `xcodebuild` deletes all its previous logs whenever it runs. This can be really annoying because sometimes appium will try running `xcodebuild`, fail, and then retry the operation, at which point the original failure logs (that may hold the real root cause) would be overridden. In addition, other jobs might closely follow on the same CI node, effectively deleting even those retry logs (of the previous job).

I'm thinking the easiest way to do this would be to grep the xcodebuild output and look for `[debug] [XCUITest] Log file for xcodebuild test: /path/to/log/file` and then maybe just `cat` it.

**Comment by imurchie** [comment]
I'm not sure what you are asking.

If you want the `xcodebuild` logs printed out, just set the `showXcodeLog` capability to `true`.

**Comment by ohadschn** [comment]
@imurchie thanks! I totally missed that one. However it seems that not all logs are printed out. To clarify, I'm comparing appium's (stdout) output with the file that's mentioned in appium's logs like this: `[debug] [XCUITest] Log file for xcodebuild test: /Users/foo/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/CD864BC8-49A5-4341-8F75-9E6CFA53ED88/Session-WebDriverAgentRunner-2017-02-10_190914-VmFWMR.log`

Enabling said capability does add some xcodebuild logs from that file that weren't there before, like:
```
[Xcode] 2017-02-10 19:09:14.494 xcodebuild[83591:1010670] [MT] IDETestOperationsObserverDebug: (7BF96310-9BD2-4C96-AC7F-DDD20F698FE5) Beginning test session WebDriverAgentRunner-7BF96310-9BD2-4C96-AC7F-DDD20F698FE5 at 2017-02-10 19:09:14.493 with Xcode 8C1002 on target <DVTiOSDevice: 0x7fc0d4edf5f0> {
		deviceSerialNumber:         DxxxxxxxV1
		identifier:                 a3fxxxxxxxxxxxxxx3faf42949705
		deviceClass:                iPad
		deviceName:                 My iPad 
                ...
```

However the xcodebuild log file still contains logs that do not appear in appium's log, for example:
```
19:09:19.055 xcodebuild[83591:1010739] Updated test configuration at /var/folders/6m/kb2b2v255mbbl6q31jdth6rm0000gn/T/com.apple.dt.XCTest/7BF96310-9BD2-4C96-AC7F-DDD20F698FE5/remote-container/tmp/WebDriverAgentRunner-7BF96310-9BD2-4C96-AC7F-DDD20F698FE5.xctestconfiguration with device paths: <XCTestConfiguration: 0x7fc0d673a550>
                          testBundleURL:file:///private/var/containers/Bundle/Application/DE1E0E77-CC5D-4888-9191-CA0B91EBF303/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest
                 testBundleRelativePath:(null)
                      productModuleName:WebDriverAgentRunner
                            testsToSkip:(null)
                             testsToRun:(null)
                     reportResultsToIDE:YES
                      sessionIdentifier:<__NSConcreteUUID 0x7fc0d64cf860> 7BF96310-9BD2-4C96-AC7F-DDD20F698FE5
                     ...
}
```

**Comment by imurchie** [comment]
It would probably be possible to add a log type to get the files. That would not be too difficult.

**Comment by ohadschn** [comment]
Very strange. For me these files disappear, any idea what could delete them? 

Regardless, adding this might make life easier for you guys too - half of the issue comments are "please attach the xcodebuild logs" :)

**Comment by imurchie** [comment]
No idea.

**Comment by ohadschn** [comment]
Fair enough. 

So back on topic, perhaps `showXcodeLog` could be renamed to something like `XcodeLogVerbosity` with possible values of `none`, `info`, and `full`.

**Comment by imurchie** [comment]
The latest driver will now print out the contents of the xcodebuild log file when xcodebuild fails, if `showXcodeLog` is on.

**Comment by ohadschn** [comment]
Even better!

**Comment by ohadschn** [comment]
@imurchie that's great! However I wonder if there could be situations where you'd want the xcodebuild log files even when the former reportedly succeeded. For example the test run passed but was very slow, or xcodebuild reported success even though something did go wrong (maybe some tests didn't run). Perhaps an additional capability like `showXcodeFullLog` that could be `never`, `onFailure` (default), and `always`?

**Comment by jlipps** [comment]
Added this as a feature enhancement request.

**Comment by imurchie** [comment]
This is actually done.
