### ISSUE TITLE
Get "An unknown server-side error occurred while processing the command." error when running test

### ISSUE THREAD

**Issue by suryasri13** [appium/appium#7845]
## The problem

I'm new to Appium and running a sample test suite which I've cloned from git and ".rvm/gems/ruby-2.3.3/gems/selenium-webdriver-3.0.8/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok': An unknown server-side error occurred while processing the command. Original error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1 (Selenium::WebDriver::Error::UnknownError)"

## Environment

* Appium version I'm using is 1.6.3
* using OSx 10.11.6
* running tests on iOS 10.2:
* simulator:
* Appium CLI

## Details

When I'm running the test which was available online, I see the above mentioned error

## Link to Appium logs

https://gist.github.com/suryasri13/41db6d95329c907d557bccead58c767b

## Code To Reproduce Issue 

I've used the sample code at https://github.com/appium/sample-code for ruby
when running simple_test.rb, I see the above mentioned error.

**Comment by mykola-mokhnach** [comment]
Check if carthage is installed properly on the machine where the test is running.

**Comment by suryasri13** [comment]
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 1
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)

I have it installed

**Comment by imurchie** [comment]
What version of Carthage (run `carthage version`)?

**Comment by suryasri13** [comment]
0.18.1

**Comment by mykola-mokhnach** [comment]
Please paste the output of 

```
/bin/bash -x Scripts/bootstrap.sh -d
```

command

**Comment by suryasri13** [comment]
I don't see that

**Comment by suryasri13** [comment]
/bin/bash: Scripts/bootstrap.sh: No such file or directory

**Comment by imurchie** [comment]
```
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
/bin/bash Scripts/bootstrap.sh -d
```

**Comment by suryasri13** [comment]
/bin/bash Scripts/bootstrap.sh -d didn't have permissions, but with sudo it worked

**Comment by imurchie** [comment]
You should not install Appium with sudo. These sorts of problems are going to crop up.

**Comment by suryasri13** [comment]
Should I uninstall and install from scratch again ?
And what would happen if I don't have permissions ?

**Comment by mykola-mokhnach** [comment]
@suryasri13 yes. Many unexpected things will happen, which will stop your automation from working properly, like the one above.

**Comment by suryasri13** [comment]
@mykola-mokhnach could you tell me how can this be resolved ?

**Comment by mykola-mokhnach** [comment]
install appium without using sudo

**Comment by suryasri13** [comment]
I get Error: EACCES: permission denied, access '/usr/local/lib/node_modules/appium/node_modules/adbkit-logcat'

**Comment by mykola-mokhnach** [comment]
```
chown -R $USER /usr/local
```

**Comment by suryasri13** [comment]
I have a huge list of operations that are not permitted

chown: /usr/local/bin/appium: Operation not permitted
chown: /usr/local/bin/bsqldb: Operation not permitted
chown: /usr/local/bin/bundle: Operation not permitted
chown: /usr/local/bin/bundler: Operation not permitted
chown: /usr/local/bin/chromedriver: Operation not permitted
chown: /usr/local/bin/cucumber: Operation not permitted
chown: /usr/local/bin/datacopy: Operation not permitted
chown: /usr/local/bin/defncopy: Operation not permitted
chown: /usr/local/bin/fisql: Operation not permitted
chown: /usr/local/bin/freebcp: Operation not permitted
chown: /usr/local/bin/git: Operation not permitted
chown: /usr/local/bin/git-credential-osxkeychain: Operation not permitted
chown: /usr/local/bin/git-cvsserver: Operation not permitted
chown: /usr/local/bin/git-shell: Operation not permitted
chown: /usr/local/bin/git-upload-pack: Operation not permitted
chown: /usr/local/bin/gitk: Operation not permitted
chown: /usr/local/bin/grunt: Operation not permitted
chown: /usr/local/bin/htmldiff: Operation not permitted
chown: /usr/local/bin/ldiff: Operation not permitted
chown: /usr/local/bin/monitor: Operation not permitted
chown: /usr/local/bin/node: Operation not permitted
chown: /usr/local/bin/nokogiri: Operation not permitted
chown: /usr/local/bin/osql: Operation not permitted
chown: /usr/local/bin/rackup: Operation not permitted
chown: /usr/local/bin/rake: Operation not permitted
chown: /usr/local/bin/rspec: Operation not permitted
chown: /usr/local/bin/socksify_ruby: Operation not permitted
chown: /usr/local/bin/tdspool: Operation not permitted
chown: /usr/local/bin/tilt: Operation not permitted
chown: /usr/local/bin/tsql: Operation not permitted
chown: /usr/local/etc/freetds.conf: Operation not permitted
chown: /usr/local/etc/locales.conf: Operation not permitted
chown: /usr/local/etc/pool.conf: Operation not permitted
chown: /usr/local/git/bin/git: Operation not permitted
chown: /usr/local/git/bin/git-credential-osxkeychain: Operation not permitted
chown: /usr/local/git/bin/git-cvsserver: Operation not permitted
chown: /usr/local/git/bin/git-receive-pack: Operation not permitted
chown: /usr/local/git/bin/git-shell: Operation not permitted
chown: /usr/local/git/bin/git-upload-archive: Operation not permitted
chown: /usr/local/git/bin/git-upload-pack: Operation not permitted
chown: /usr/local/git/bin/gitk: Operation not permitted
chown: /usr/local/git/bin: Operation not permitted
chown: /usr/local/git/contrib/completion/git-completion.bash: Operation not permitted
chown: /usr/local/git/contrib/completion/git-completion.zsh: Operation not permitted
chown: /usr/local/git/contrib/completion/git-prompt.sh: Operation not permitted
chown: /usr/local/git/contrib/completion: Operation not permitted
chown: /usr/local/git/contrib: Operation not permitted
chown: /usr/local/git/etc/gitconfig: Operation not permitted
chown: /usr/local/git/etc: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/5.18.2/darwin-thread-multi-2level/auto/Git/.packlist: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/5.18.2/darwin-thread-multi-2level/auto/Git: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/5.18.2/darwin-thread-multi-2level/auto: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/5.18.2/darwin-thread-multi-2level: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/5.18.2: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Error.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/I18N.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/IndexInfo.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/SVN/Editor.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/SVN/Fetcher.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/SVN/GlobSpec.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/SVN/Log.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/SVN/Memoize/YAML.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/SVN/Memoize: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/SVN/Migration.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/SVN/Prompt.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/SVN/Ra.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/SVN/Utils.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/SVN: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git/SVN.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl/Git.pm: Operation not permitted
chown: /usr/local/git/lib/perl5/site_perl: Operation not permitted
chown: /usr/local/git/lib/perl5: Operation not permitted
chown: /usr/local/git/lib: Operation not permitted
chown: /usr/local/git/libexec/git-core/git: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-add: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-add--interactive: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-am: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-annotate: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-apply: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-archimport: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-archive: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-bisect: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-bisect--helper: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-blame: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-branch: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-bundle: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-cat-file: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-check-attr: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-check-ignore: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-check-mailmap: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-check-ref-format: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-checkout: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-checkout-index: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-cherry: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-cherry-pick: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-citool: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-clean: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-clone: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-column: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-commit: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-commit-tree: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-config: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-count-objects: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-credential: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-credential-cache: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-credential-cache--daemon: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-credential-store: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-cvsexportcommit: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-cvsimport: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-cvsserver: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-daemon: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-describe: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-diff: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-diff-files: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-diff-index: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-diff-tree: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-difftool: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-difftool--helper: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-fast-export: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-fast-import: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-fetch: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-fetch-pack: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-filter-branch: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-fmt-merge-msg: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-for-each-ref: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-format-patch: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-fsck: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-fsck-objects: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-gc: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-get-tar-commit-id: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-grep: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-gui: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-gui--askpass: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-hash-object: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-help: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-http-backend: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-http-fetch: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-http-push: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-imap-send: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-index-pack: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-init: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-init-db: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-instaweb: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-interpret-trailers: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-log: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-ls-files: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-ls-remote: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-ls-tree: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-mailinfo: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-mailsplit: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-merge: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-merge-base: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-merge-file: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-merge-index: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-merge-octopus: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-merge-one-file: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-merge-ours: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-merge-recursive: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-merge-resolve: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-merge-subtree: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-merge-tree: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-mergetool: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-mergetool--lib: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-mktag: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-mktree: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-mv: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-name-rev: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-notes: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-p4: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-pack-objects: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-pack-redundant: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-pack-refs: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-parse-remote: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-patch-id: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-prune: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-prune-packed: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-pull: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-push: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-quiltimport: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-read-tree: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-rebase: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-rebase--am: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-rebase--interactive: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-rebase--merge: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-receive-pack: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-reflog: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-relink: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-remote: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-remote-ext: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-remote-fd: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-remote-ftp: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-remote-ftps: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-remote-http: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-remote-https: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-remote-testsvn: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-repack: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-replace: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-request-pull: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-rerere: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-reset: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-rev-list: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-rev-parse: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-revert: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-rm: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-send-email: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-send-pack: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-sh-i18n: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-sh-i18n--envsubst: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-sh-setup: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-shell: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-shortlog: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-show: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-show-branch: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-show-index: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-show-ref: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-stage: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-stash: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-status: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-stripspace: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-submodule: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-submodule--helper: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-subtree: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-svn: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-symbolic-ref: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-tag: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-unpack-file: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-unpack-objects: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-update-index: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-update-ref: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-update-server-info: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-upload-archive: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-upload-pack: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-var: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-verify-commit: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-verify-pack: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-verify-tag: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-web--browse: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-whatchanged: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-worktree: Operation not permitted
chown: /usr/local/git/libexec/git-core/git-write-tree: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/araxis: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/bc: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/bc3: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/codecompare: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/deltawalker: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/diffmerge: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/diffuse: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/ecmerge: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/emerge: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/gvimdiff: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/gvimdiff2: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/gvimdiff3: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/kdiff3: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/kompare: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/meld: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/opendiff: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/p4merge: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/tkdiff: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/tortoisemerge: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/vimdiff: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/vimdiff2: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/vimdiff3: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/winmerge: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools/xxdiff: Operation not permitted
chown: /usr/local/git/libexec/git-core/mergetools: Operation not permitted
chown: /usr/local/git/libexec/git-core: Operation not permitted
chown: /usr/local/git/libexec: Operation not permitted
chown: /usr/local/git/Library/Perl/Updates/5.18.2/darwin-thread-multi-2level/perllocal.pod: Operation not permitted
chown: /usr/local/git/Library/Perl/Updates/5.18.2/darwin-thread-multi-2level: Operation not permitted
chown: /usr/local/git/Library/Perl/Updates/5.18.2: Operation not permitted
chown: /usr/local/git/Library/Perl/Updates: Operation not permitted
chown: /usr/local/git/Library/Perl: Operation not permitted
chown: /usr/local/git/Library: Operation not permitted
chown: /usr/local/git/share/git-core/templates/branches: Operation not permitted
chown: /usr/local/git/share/git-core/templates/description: Operation not permitted
chown: /usr/local/git/share/git-core/templates/hooks/applypatch-msg.sample: Operation not permitted
chown: /usr/local/git/share/git-core/templates/hooks/commit-msg.sample: Operation not permitted
chown: /usr/local/git/share/git-core/templates/hooks/post-update.sample: Operation not permitted
chown: /usr/local/git/share/git-core/templates/hooks/pre-applypatch.sample: Operation not permitted
chown: /usr/local/git/share/git-core/templates/hooks/pre-commit.sample: Operation not permitted
chown: /usr/local/git/share/git-core/templates/hooks/pre-push.sample: Operation not permitted
chown: /usr/local/git/share/git-core/templates/hooks/pre-rebase.sample: Operation not permitted
chown: /usr/local/git/share/git-core/templates/hooks/prepare-commit-msg.sample: Operation not permitted
chown: /usr/local/git/share/git-core/templates/hooks/update.sample: Operation not permitted
chown: /usr/local/git/share/git-core/templates/hooks: Operation not permitted
chown: /usr/local/git/share/git-core/templates/info/exclude: Operation not permitted
chown: /usr/local/git/share/git-core/templates/info: Operation not permitted
chown: /usr/local/git/share/git-core/templates: Operation not permitted
chown: /usr/local/git/share/git-core: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/about.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/blame.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/branch.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/branch_checkout.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/branch_create.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/branch_delete.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/branch_rename.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/browser.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/checkout_op.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/choose_font.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/choose_repository.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/choose_rev.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/class.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/commit.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/console.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/database.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/date.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/diff.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/encoding.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/error.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/Git Gui.app/Contents/Info.plist: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/Git Gui.app/Contents/MacOS/Wish: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/Git Gui.app/Contents/MacOS: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/Git Gui.app/Contents/Resources/git-gui.icns: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/Git Gui.app/Contents/Resources/Scripts/AppMain.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/Git Gui.app/Contents/Resources/Scripts: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/Git Gui.app/Contents/Resources: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/Git Gui.app/Contents: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/Git Gui.app: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/git-gui.ico: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/git-gui.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/index.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/line.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/logo.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/merge.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/mergetool.tcl: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/msgs/bg.msg: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/msgs/de.msg: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/msgs/el.msg: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/msgs/fr.msg: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/msgs/hu.msg: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/msgs/it.msg: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/msgs/ja.msg: Operation not permitted
chown: /usr/local/git/share/git-gui/lib/msgs/nb.msg: Operation not permitted

**Comment by dmshantanu** [comment]
I see this:

acbc328a71a3:WebDriverAgent mujums$ sudo /bin/bash Scripts/bootstrap.sh -d
Password:
Fetching dependencies
*** Please update to the latest Carthage version: 0.23.0. You currently are on 0.20.0
*** Cloning RoutingHTTPServer
*** Cloning peertalk
*** Checking out peertalk at "v1.0"
*** Cloning peertalk
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/marekcirkos/peertalk.git /var/root/Library/Caches/org.carthage.CarthageKit/dependencies/peertalk) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled

I have github setup to operate with stored credentials so that I don't have to enter those everytime. Then I searched  github for "marekcirkos/peertalk" and I don't see it there. I am blocked on this. Any help is much appreciated.

**Comment by dmshantanu** [comment]
I also tried using rsms/peertalk by changing the Cartfile  and Cartfile.resolved files in appium.
However, appium kept on failing since it did not find the version 1.0 for rsms/peertalk.

**Comment by JohnProg** [comment]
I'm getting the same error. After run the command `/bin/bash -x Scripts/bootstrap.sh -d`
```
*** Cloning peertalk
*** Downloading RoutingHTTPServer.framework binary at "v1.0.1"
*** Checking out peertalk at "v1.0"
*** Cloning peertalk
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/marekcirkos/peertalk.git /Users/johnmachahuay/Library/Caches/org.carthage.CarthageKit/dependencies/peertalk) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```
