### ISSUE TITLE
Not able to turn on/off wifi

### ISSUE THREAD

**Issue by tadesushilgithub** [appium/appium#7846]
## The problem

I am using .net appium driver 2.0.1.1 and Appium 1.6.3, not able to turn of wifi using API.
 OpenQA.Selenium.Appium.Android.ConnectionType.DataOnly;

but was working earlier in Appium version 1.3.4. Is there any other way to toggle network connection type.

Android OS : 6

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.3.4
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): 6.9.2
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/tadesushilgithub/a826ea0224d6f756c5c02e1e26c46957

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by jlipps** [comment]
According to the log, the change was successful. If it didn't actually take place on the device, that might be an issue on the Android side. We did update some connection logic in 1.6.4, so try that version and maybe it will be fixed.
