### ISSUE TITLE
[Appium 1.6.4(beta)] : iOS Real Device loops on ios error - " Could not find any webviews yet, refreshing/retrying"

### ISSUE THREAD

**Issue by JESii** [appium/appium#7847]
## The problem

I am running ruby/cucumber tests against a mobile web page (not an app). The test hits the device (iPad 9.3.5) but then, instead of displaying the requested web page, appium.io is opened in Safari.

## Environment

* Appium version (or git revision) that exhibits the issue:
1.6.4(beta)
* Last Appium version that did not exhibit the issue (if applicable):
N/A - Only have iOS simulator running
* Desktop OS/version used to run Appium:
OS X El Cap; 10.11.6
* Node.js version (unless using Appium.app|exe):
7.5.0
* Mobile platform/version under test:
iOS 9.3
* Real device or emulator/simulator:
Real device
* Appium CLI or Appium.app|exe:
appium CLI
* Xcode version:
8.2.1

#### Additional environment details

* appium-ios-driver@1.16.0 (installed with -g option)
* appium-xcuitest-driver@2.7.0 (installed with -g option)
* authorize-ios@1.0.4 (installed with -g option)
* ios-deploy@1.9.1 (installed with -g option)
* ios_webkit_debug_proxy@ 1.7.1, Built with libimobiledevice v1.2.0, libplist v1.12
* libimobiledevice: stable 1.2.0 (bottled), HEAD
* ideviceinstaller: stable 1.1.0 (bottled), HEAD
* .xcconfig created with:
DEVELOPMENT_TEAM = XXXXXXXXXX
CODE_SIGN_IDENTITY = iPhone Developer
* iPad Apps installed during the test process
`WebDriverAgentRunner version 1, com.apple.test.WebDriverAgentRunner-Runner`
`IntegratonApp version 1, com.facebook.IntegrationApp`

#### Symptoms

1) The test begins running, the WEbDriverAgent is built and loaded, and I can see the device / Safari reacting: Starting from Safari, the device slides Safari out of the way, displays a completely black screen, then goes to the home screen, then back to Safari.

2) After a short pause, the device displays http://appium.io page on Safari

3) appium server logs show endless, quick repetitions of error 
```
2017-02-10 08:16:48:224 - info: [debug] [iOS] No web frames found.
2017-02-10 08:16:48:224 - info: [debug] [iOS] Retrieving contexts and views
2017-02-10 08:16:48:224 - info: [debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
2017-02-10 08:16:48:224 - info: [debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
2017-02-10 08:16:48:225 - info: [debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
2017-02-10 08:16:48:228 - warn: [iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
2017-02-10 08:16:48:229 - info: [debug] [iOS] No web frames found.
2017-02-10 08:16:48:229 - warn: [iOS] Could not find any webviews yet, refreshing/retrying
2017-02-10 08:16:48:735 - info: [debug] [iOS] Retrieving contexts and views
2017-02-10 08:16:48:735 - info: [debug] [iOS] Selecting by url: true (expected url: 'http://appium.io')
2017-02-10 08:16:48:735 - info: [debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
2017-02-10 08:16:48:735 - info: [debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
2017-02-10 08:16:48:739 - warn: [iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
```

Furthermore, I am not able to see the "Settings | General | Profiles & Device Manager" as described in the [real device tutorial](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md) as referenced in Issue #7825 

#### Running programs

Appium server:
`  appium -g ~/appium_server.log --log-timestamp --local-timezone --debug-log-spacing --tmp ~/tmp --default-capabilities '{"showXcodeLog": true, "automationName": "XCUITest", "cssSelectorsEnabled": true, "nativeWebTap": true, "nativeEvents": true, "autoWebView": true}'`

ios_webkit_debug_proxy:
`ios_webkit_debug_proxy -c XXXUDIDXXX:9222 -d` running in another terminal window and connected to my device ("JON's iPad")

Cucumber test:
`bundle exec cucumber   DEVICE=Iphone -p mobile_website_default     SITE=MCOM URL=http://m.qa17codemacys.fds.com/  features/website/Selection/MEW/registry/MCOM/registry_navigation.feature:14`

## Link to Appium logs

Here are the logs: https://gist.github.com/JESii/fa5ea5fb09deaf3ed6a1ab8f103c0c22

## Code To Reproduce Issue [ Good To Have ]

Mobile website testing, not an app

**Comment by imurchie** [comment]
If you want to run `ios-webkit-debug-proxy` on a port other than `27753`, you need to specify that port through the `--webkit-debug-proxy-port` server argument. Otherwise it has no way of knowing where the proxy is running.

**Comment by JESii** [comment]
Thanks; I'll go check that out right now...

**Comment by JESii** [comment]
Okaaay - now we're talking. thank you very much. Still unable to complete the test but it started, so closing this issue. Can't remember where I picked up that port number...

**Comment by JESii** [comment]
FYI... Just for the record, I tried port 9222 because I mis-read the comments in issue #6970: 
```
The problem is starting ios-webkit-debug-proxy in the way that Google recommends. 
This leads to the proxy listening on port 9221, but each individual device being on subsequent 
(open) ports. So with a single iPhone attached I get it actually listening on port 9222.
```

**Comment by imurchie** [comment]
Ah. Glad things worked out, though. I'm not sure why Appium defaults to such a strange port. But there is work underway to automate the use of ios-webkit-debug-proxy inside appium, so it should not be an issue too much longer.

**Comment by messianic** [comment]
I have to manually start an i-w-d-p session in a separate and pass that port through cap: webkitDebugProxyPort. Can't Appium automatically start i-w-d-p on the specified port?
