### ISSUE TITLE
Do Appium Support Windows Phone Native Application?

### ISSUE THREAD

**Issue by dilsreccse** [appium/appium#7850]
It is mentioned in the Appium release notes that"Windows Application Driver supports testing Universal Windows Platform (UWP) and Classic Windows (Win32) apps on Windows 10 PC". Is this mean appium right now support only Windows desktop based Native Application running on Windows 10 PC or it supports for native application/web application  running on Windows Phone  also? 

[Reference Link ](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/windows-app-testing.md) : capabilities mentioned for  a Windows App automation is 
platformName: Windows 
deviceName: WindowsPC

What could be the  capability if i use a Windows Phone for Automating the native application installed in the real device?

**Comment by dilsreccse** [comment]
Kindly provide  your thoughts soon on this @jlipps

**Comment by dilsreccse** [comment]
@jlipps can you provide the insight of Universal Windows Platform (UWP) support w.r.t Appium?

**Comment by kcinman11358** [comment]
Not sure if pinging jlipps is the right way to go ;)

As far as I know, appium is for phone apps, not desktop apps

**Comment by imurchie** [comment]
Appium can automate windows apps. I do not think that includes Windows Phone apps, just desktop.

**Comment by dilsreccse** [comment]
Thanks @imurchie can you please ping the right person, urgent need to kick start /Explore Appium with windows phone

**Comment by imurchie** [comment]
I think there is a _right person_. Someone with knowledge of Windows Phone needs to step up and begin work on it. Right now there is no such person.
