### ISSUE TITLE
UI Automator Viewer is not loading my screen

### ISSUE THREAD

**Issue by nvphaneendra** [appium/appium#7852]
Hi Team,

When I am trying to take the screenshot of my current running screen, it was throwing an error window could you please me for the issue resolution.

Reproduce issue ,
![image](https://cloud.githubusercontent.com/assets/11880421/22869519/c587da9c-f1c5-11e6-89c3-80e00b61743e.png)

Environment,
Windows 2010 machine.
Mobile : Lenovo K3 Note

Note : Appium server is not running and I am new to Appium.

Thanks in Advance...

Cheers,
Phani

**Comment by bmvbab** [comment]
Not an appium issue. That said, this is most likely because there is another Adb session probably because of a running test or so. Just kill and restart adb and uiautomator should work.

**Comment by JaniJegoroff** [comment]
`uiautomatorviewer` is part of Android SDK toolchain and therefore nothing to do with Appium.

**Comment by nvphaneendra** [comment]
Thanks Guys,

I am able to resolve my issue.

I have one more query.

When I try to open my mobile using asm, it having more resolution size as (1080 x 1920). Is it possible to decrease asm window?

**Comment by nvphaneendra** [comment]
@bmvbab, Still I am getting the same issue. I have killed all the adb threads.

**Comment by bmvbab** [comment]
After you killed adb server, did you try adb devices? Does it show your device?

**Comment by eyypbgds** [comment]
@nvphaneendra Hi,

You can use appium gui inspector for this issue. Put debug pointer on your project which page you want to inspect than start appium from console and debug test. When page viewed, click inspector button on appium gui.

**Comment by niteshsingh2311** [comment]
In the latest android studio uiautomatorviewer.bat is present in the bin folder. Try to open it. It worked for me

**Comment by kavithasrinivas** [comment]
In UIautomatorViewer unable to get screen shot of android 8.1.0 (MI note 5) . i am getting
![capture](https://user-images.githubusercontent.com/43744047/47063400-79c75000-d1f8-11e8-8ae7-390bbf4cdbb9.PNG)
 the following error

**Comment by IrappaH** [comment]
I too facing the same issue on my Windows 10 64 bit
Some unexpected error while obtaining UI hierarchy 
Could anyone help me to resolve this issue
