### ISSUE TITLE
Applet 1.6.3 wda inspector web access error

### ISSUE THREAD

**Issue by liangjinwen** [appium/appium#7854]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:mac 10.12.1
* Node.js version (unless using Appium.app|exe):v6.9.5
* Mobile platform/version under test:ios 10.0
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:CLI

## Details
Applet 1.6.3 wda inspector web access error
Connect localhost: 8100 shows the status is normal, but the link inspector is incorrect
Please help look at,whether I set up a problem where the problem,thank you!
If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]
**Error code：**
2017-02-13 20:00:57.643 XCTRunner[84707:2104507] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2017-02-13 20:00:58.282
Test Suite 'WebDriverAgentLib.framework' started at 2017-02-13 20:00:58.283
Test Suite 'WebDriverAgentLib.framework' passed at 2017-02-13 20:00:58.283.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-02-13 20:00:58.284
Test Suite 'UITestingUITests' started at 2017-02-13 20:00:58.285
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.00s     Start Test at 2017-02-13 20:00:58.286
    t =     0.00s     Set Up
2017-02-13 20:00:58.289 XCTRunner[84707:2104507] Built at Feb 13 2017 16:16:17
2017-02-13 20:00:58.306 XCTRunner[84707:2104507] ServerURLHere->http://XXXXXX:8100<-ServerURLHere
2017-02-13 20:02:05.451 XCTRunner[84707:2104507] *** Assertion failure in -[FBResponseFilePayload initWithFilePath:], /usr/local/lib/node_modules/appium/node_modules/.2.8.0@appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBResponseFilePayload.m:24

**Visit inspector error code：**
{
  "value" : "Invalid parameter not satisfying: path\n\n(\n\t0   CoreFoundation                      0x0000000109b4834b __exceptionPreprocess + 171\n\t1   libobjc.A.dylib                     0x00000001095a921e objc_exception_throw + 48\n\t2   CoreFoundation                      0x0000000109b4c442 +[NSException raise:format:arguments:] + 98\n\t3   Foundation                          0x000000010913fedd -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195\n\t4   WebDriverAgentLib                   0x000000011c3c0e1b -[FBResponseFilePayload initWithFilePath:] + 283\n\t5   WebDriverAgentLib                   0x000000011c3bc347 FBResponseFileWithPath + 87\n\t6   WebDriverAgentLib                   0x000000011c3ce9ec __29+[FBInspectorCommands routes]_block_invoke + 108\n\t7   WebDriverAgentLib                   0x000000011c3bc60c -[FBRoute_Sync mountRequest:intoResponse:] + 140\n\t8   WebDriverAgentLib                   0x000000011c3b2cc4 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 548\n\t9   RoutingHTTPServer                   0x000000011c46dc18 -[RoutingHTTPServer handleRoute:withRequest:response:] + 136\n\t10  RoutingHTTPServer                   0x000000011c46e4fa __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 47\n\t11  libdispatch.dylib                   0x000000010c86b12e _dispatch_client_callout + 8\n\t12  libdispatch.dylib                   0x000000010c8537a5 _dispatch_barrier_sync_f_slow_invoke + 315\n\t13  libdispatch.dylib                   0x000000010c86b12e _dispatch_client_callout + 8\n\t14  libdispatch.dylib                   0x000000010c85252d _dispatch_main_queue_callback_4CF + 1054\n\t15  CoreFoundation                      0x0000000109b0c4f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9\n\t16  CoreFoundation                      0x0000000109ad1f8d __CFRunLoopRun + 2205\n\t17  CoreFoundation                      0x0000000109ad1494 CFRunLoopRunSpecific + 420\n\t18  Foundation                          0x000000010908c080 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 274\n\t19  Foundation                          0x000000010908bf5b -[NSRunLoop(NSRunLoop) run] + 76\n\t20  WebDriverAgentLib                   0x000000011c3b1bb6 -[FBWebServer startServing] + 262\n\t21  WebDriverAgentRunner                0x000000011c3a9d34 -[UITestingUITests testRunner] + 100\n\t22  CoreFoundation                      0x0000000109acf05c __invoking___ + 140\n\t23  CoreFoundation                      0x0000000109aceee1 -[NSInvocation invoke] + 289\n\t24  XCTest                              0x0000000108f7ff77 __24-[XCTestCase invokeTest]_block_invoke_2 + 481\n\t25  XCTest                              0x0000000108fb87df -[XCTestContext performInScope:] + 190\n\t26  XCTest                              0x0000000108f7fd83 -[XCTestCase invokeTest] + 255\n\t27  XCTest                              0x0000000108f8059c -[XCTestCase performTest:] + 457\n\t28  XCTest                              0x0000000108f7d664 -[XCTestSuite performTest:] + 491\n\t29  XCTest                              0x0000000108f7d664 -[XCTestSuite performTest:] + 491\n\t30  XCTest                              0x0000000108f7d664 -[XCTestSuite performTest:] + 491\n\t31  XCTest                              0x0000000108f69618 __25-[XCTestDriver _runSuite]_block_invoke + 51\n\t32  XCTest                              0x0000000108f8ad2b -[XCTestObservationCenter _observeTestExecutionForBlock:] + 602\n\t33  XCTest                              0x0000000108f694b5 -[XCTestDriver _runSuite] + 436\n\t34  XCTest                              0x0000000108f6a302 -[XCTestDriver _checkForTestManager] + 287\n\t35  XCTest                              0x0000000108fb9d67 _XCTestMain + 628\n\t36  CoreFoundation                      0x0000000109aed25c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12\n\t37  CoreFoundation                      0x0000000109ad2304 __CFRunLoopDoBlocks + 356\n\t38  CoreFoundation                      0x0000000109ad1a75 __CFRunLoopRun + 901\n\t39  CoreFoundation                      0x0000000109ad1494 CFRunLoopRunSpecific + 420\n\t40  GraphicsServices                    0x000000010bfa9a6f GSEventRunModal + 161\n\t41  UIKit                               0x0000000109f6bf34 UIApplicationMain + 159\n\t42  XCTRunner                           0x0000000108eea81c XCTRunner + 6172\n\t43  libdyld.dylib                       0x000000010c8b468d start + 1\n\t44  ???                                 0x0000000000000005 0x0 + 5\n)",
  "sessionId" : "1AA78138-7396-4159-B5F7-DBDD6202A9AF",
  "status" : 13
}
Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
What inspector are you talking about?

**Comment by JaniJegoroff** [comment]
I believe it's about WDA inspector endpoint: `http://localhost:8100/inspector`

**Comment by imurchie** [comment]
You'll have to take that up with the WebDriverAgent people, then. https://github.com/facebook/WebDriverAgent/

**Comment by prudhvialahari** [comment]
I'm getting the same issue, please look into it.

**Comment by imurchie** [comment]
Appium does not have anything to do with the inspector.
