### ISSUE TITLE
error: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Resources/WebDriverAgent.bundle: No such file or directory

### ISSUE THREAD

**Issue by sagar3715** [appium/appium#7855]
## The problem

While Buiding the Xcode Project WebDriver Agent Lib I got this above error 
previously I got this error. [debug] [iProxy] recv failed: Resource temporarily unavailable. (Random commands).   so after this solution [https://github.com/appium/appium/issues/7570](url)
I upgrade my Appium version and I got this above error 
## Environment

* Welcome to Appium v1.6.4-beta
* last version 1.6.3
* Mac 10.12.2
* Node.js :7.4.0
* iPhone 5c version 10.1.1

**Comment by sagar3715** [comment]
I have tried this solution also [https://github.com/vrunoa/appium-workshop/issues/2](url)

**Comment by imurchie** [comment]
While runnign Appium? Can you provide the logs (as a [gist](https://gist.github.com)) so we can actually try to see what is up?

**Comment by sagar3715** [comment]
but this error comes in Xcode while building the project of WebDriver Agent Runner

**Comment by imurchie** [comment]
Ok. Just create the directory. Appium creates it while running an xcuitest-base iOS test, and it's just an empty directory.

**Comment by sagar3715** [comment]
device gist

[https://gist.github.com/sagar3715/86920ff725cbedff808def2eb7ef7980#file-gistfile1-txt](url)

**Comment by imurchie** [comment]
I don't know what I'm supposed to be looking for in here. The error in this issue is not there. Please create a new issue with all the information needed to pinpoint the problem.
