### ISSUE TITLE
appium install too slow

### ISSUE THREAD

**Issue by harlentan** [appium/appium#7860]
## The problem

npm install appium is too slow for the new version.

The installation always block on downloading apks or  `node-pre-gyp install --fallback-to-build`

## Environment

OS: macOS 10.12.3

Is there any way to speed up the installation? 
or there is anything wrong with the installation scripts?

**Comment by tangzhentao** [comment]
me too

**Comment by harlentan** [comment]
There may be someting wrong with the network.

Just close this issue.
