### ISSUE TITLE
Android Emulator crashes when scripts are run using Appium in Mac

### ISSUE THREAD

**Issue by rajeshshiv** [appium/appium#7861]
## The problem

Android Emulator (From Android Studio) crashes when scripts are run using Appium 1.5.3 or Appium 1.6.3

## Environment

* Appium 1.5.3 and Appium 1.6.3
* Mac OS version 10.12 (Sierra )
* Android SDK 25.2.5
* Emulator with API Level 21 and Android OS 5.0

## Details

Scripts were running fine until 2 days back when the emulator started crashing frequently. It launches the App but remains IDLE for a while and then Emulator crashes. Can anyone help me out in this

## Link to Appium logs

https://gist.github.com/rajeshshiv/29c51b539b4c5237c837ee55cd8d7fd7

**Comment by rajeshshiv** [comment]
anyone?

**Comment by imurchie** [comment]
Was anything changed 2 days ago that could have precipitated this?

**Comment by rajeshshiv** [comment]
Nope nothing. I didn't update nor did anything. It's just that if i run scripts 100 times, this will run perfectly 2 times. Rest 98 times I get the above mentioned log. Really no clue how come all of sudden

**Comment by rajeshshiv** [comment]
@imurchie  ??

**Comment by imurchie** [comment]
I have no idea. My first thing would be to restart the Mac.

**Comment by rajeshshiv** [comment]
I did those. Probably not related to Appium right?

**Comment by imurchie** [comment]
If nothing changed in Appium, then no. And I have no real advice to give. :(

**Comment by rajeshshiv** [comment]
Ok let me try downgrading Android SDK and tools. As of now am using all latest. Then will update here
