### ISSUE TITLE
how to complete an action “long press” in android 7.0?

### ISSUE THREAD

**Issue by MarvinLiuMing** [appium/appium#7862]
## The problem

I want to finish an “long press” action in android 7.0. I tried a lot of ways but could not solve it.
ex:
     1. driver.tap(1,element,2000)  
     2. TouchAction
          TouchAction ta=new TouchAction(driver);
          ta.longPress(element).release().perform();

## Environment

* Appium version : 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: win10
* Node.js version : 4.5.0
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: Appium CLI 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/MarvinLiuMing/b142784a5630608e1264cf3a8849df1e

**Comment by amedvedjev** [comment]
maybe you need you custom time:
`ta.longPress(element, 2000).release().perform(); //2000ms`

**Comment by MarvinLiuMing** [comment]
It cause the same problem. But thanks a lot.

**Comment by amedvedjev** [comment]
i use same code tested with Android 6.X:
`new TouchAction((AndroidDriver) driver).press(some_element).waitAction(2000).release().perform();`

can you see that press happens actually on device? just enable 'show touches' in developer modes.

**Comment by MarvinLiuMing** [comment]
@amedvedjev Sorry for some other things delayed. I have tried it in Android 6.X with your code. It still doesn't work. What is your version of appium? And did you use appium-dotnet-driver ?

**Comment by vikramvi** [comment]
@MarvinLiuMing please ask queries in discuss.appium.io and if there is bug in appium server file it here.

@triager please close
