### ISSUE TITLE
Appium raise ESOCKETTIMEDOUT error when invoke find_element on webview

### ISSUE THREAD

**Issue by chaoli46** [appium/appium#7863]
## Appium raise ESOCKETTIMEDOUT error when invode find_element on webview 

After click link on Android app's webview, the ruby client will get stuck, and the appium server will raise an error called `ESOCKETTIMEDOUT` after almost 10 minutes.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS 10.12.3
* Node.js version (unless using Appium.app|exe): 6.9.4
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

1. Open Android app
2. Open web page in the Android app
3. Open a link of the web page

## Link to Appium logs

https://gist.github.com/chaoli46/33c0a31f5d60322110c1247e2c8c85cd

The error is from line 1397.

```
[HTTP] --> POST /wd/hub/session/f1d005ab-4bc7-4888-aac0-95c2ae71fb6e/element {"using":"xpath","value":"//a[@class='item']"}

[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/f1d005ab-4bc7-4888-aac0-95c2ae71fb6e/element] to [POST http://127.0.0.1:8000/wd/hub/session/9c38138b4d7925a297bf5aaaa511ab92/element] with body: {"using":"xpath","value":"//a[@class='item']"}

[MJSONWP] Encountered internal error running command: Error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
    at doJwpProxy$ (../../../lib/mjsonwp/mjsonwp.js:343:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

## Code To Reproduce Issue

```ruby
require 'appium_lib'

class Test
  def initialize caps
    driver = Appium::Driver.new(caps: caps).start_driver
    Appium.promote_appium_methods self.class
    wait_true { find_element(xpath: '//com.tencent.mm.ui.mogic.WxViewPager').displayed? }
    test_webview
  end

  def test_webview
    find_element(xpath: "//android.view.View[@text='微信团队']").click
    text('常见问题').click
    text('更多帮助').click
    set_context 'WEBVIEW_com.tencent.mm:tools'
    find_element(id: 'faq_section').find_element(tag_name: 'li').click
    sleep 10
    find_element(class_name: 'q-content').text
  end
end

caps =
  { "platformName" => "Android",
    "platformVersion" => 7.1,
    "deviceName" => "00d5d10b8060c135",
    "appPkg" => "com.tencent.mm",
    "appWaitPackage" => "com.tencent.mm",
    "appActivity" => ".ui.LauncherUI",
    "appWaitActivity" => ".ui.LauncherUI",
    "unicodeKeyboard" => true,
    "resetKeyboard" => true,
    "noReset" => true,
    "clearSystemFiles" => true,
    "autoWebviewTimeout" => 5000,
    "chromeOptions" => { "androidProcess" => "com.tencent.mm:tools" } }
Test.new caps
```

It requires debug tool for set context to webview. The debug tool can be installed by open `debugtbs.qq.com` in the app, and it should be set by `debugx5.qq.com`. (Second tab -> Check second option on)

**Comment by rseek** [comment]
Same problem on
* Appium 1.6.3
* chromedriver 2.24
* Android 7.1.1
* x86 Emulator

Details:
* Open Android app
* Open web page in the Android app (login page in my case)
* Input credentials on a web page (it works)
* Click "login" button

Result:

Button is clicked, webview disappears (as expected, but appium hangs for minutes, and ESOCKETTIMEDOUT is thrown

**Comment by darina-techery** [comment]
I can see the same error when invoking findElement on iPhone simulator.
Workaround: if I add a 2 sec Thread.sleep() before element lookup, no such issue occurs, but it's a very ugly solution.

**Comment by jlipps** [comment]
Sorry @chaoli46 looking at the logs, this is some problem with the interaction between chrome and chromedriver. It's not an appium issue. We can only hope that newer chromes and chromedrivers will resolve it.

**Comment by aaronmagi** [comment]
@chaoli46 or @rseek  did you get this to work yet with a newer version?

Thank you
