### ISSUE TITLE
How to verify appium server has started programmatically  

### ISSUE THREAD

**Issue by KalveeduVijay** [appium/appium#7866]
## Hello Everyone,

I'm invoking the Appium server programatically. Currently I am facing an exception named "Ureachable browser exception". 

Now, 1) can someone guide me on how to verify appium server has started up and running ? 

2) Also how can we manually check the network status of "http://127.0.0.1:4723/wd/hub"

Please be informed that I've not installed Appium through terminal + device not connected to internet.

## Environment

Appium version: 1.4.13
Desktop OS/version used to run Appium:10.11.13
Node.js version (unless using Appium.app|exe):
Mobile platform/version under test: iOS 9.3.4
Real device or emulator/simulator: Real Device.
Appium CLI or Appium.app|exe: Xcode 7.3.1

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
@Test
public void startWebkitProxy(){
//Commmand provided in terminal to start webkit debug
//"ios_webkit_debug_proxy -c 29808cb769651582f444f6d95a2ece576beb2591:27753 -d"
CommandLine iOSWebkitDebugProxyCommand = new CommandLine("starting ios_webkit_debug_proxy");
iOSWebkitDebugProxyCommand.addArgument("-c");
iOSWebkitDebugProxyCommand.addArgument(udidOfDevice+":27753"); //input
iOSWebkitDebugProxyCommand.addArgument("-d");

  DefaultExecuteResultHandler iOSWebkitResultHandler = new DefaultExecuteResultHandler();
  DefaultExecutor iOSProxyexecutor = new DefaultExecutor();
  iOSProxyexecutor.setExitValue(1);
  try {
  iOSProxyexecutor.execute(iOSWebkitDebugProxyCommand, iOSWebkitResultHandler);
  iOSWebkitResultHandler.toString();
  Thread.sleep(5000);
  System.out.println("iOS Webkit debug proxy : Started");
  } catch (IOException e) {
  System.out.println("Failed to start iOS Webkit debug Proxy" + e);
  e.printStackTrace();//paste the complete trace.
  } catch (InterruptedException e) {
	  System.out.println("Failed to start iOS Webkit debug Proxy" + e);
	  e.printStackTrace();//paste the complete trace.
  }
}
@Test
public void startAppiumServer(){

  //Appium Server Arguements.
  CommandLine commandAppiumServer = new CommandLine("/Applications/Appium.app/Contents/Resources/node/bin/node");
  commandAppiumServer.addArgument("/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium.js", false);
  commandAppiumServer.addArgument("--address", false);
  commandAppiumServer.addArgument("127.0.0.1");
  commandAppiumServer.addArgument("--port", false);
  commandAppiumServer.addArgument("4723");
  commandAppiumServer.addArgument("--no-reset", false);//Avoid resetting the app betweeen sessions
//	commandAppiumServer.addArgument("--full-reset", false);
//	commandAppiumServer.addArgument("--log-level", false);// Will block the console logs in eclipse
commandAppiumServer.addArgument("--log", false);
commandAppiumServer.addArgument("--session-override", true);
commandAppiumServer.addArgument("--pre-launch", true);
commandAppiumServer.addArgument("safari", true);

//	commandAppiumServer.addArgument("--webkit-debug-proxy-port");port is 27753
System.out.println("Server Flags : Completed.");

  //Customizing logs with time stamp information.
//	Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
//	command.addArgument("/Users/sethupandi/appium"+currentTimestamp+".log");

  DefaultExecuteResultHandler serverResultHandler = new DefaultExecuteResultHandler();
  DefaultExecutor executor = new DefaultExecutor();
  executor.setExitValue(1);
  
  System.out.println("Default Executor : executed commands.");
  try {
	   executor.execute(commandAppiumServer, serverResultHandler);
	   System.out.println("Appium Server Started");
	  } catch (ExecuteException e) {
	System.out.println("Failed to start Appium server" + e);
	   e.printStackTrace();
	  } catch (IOException e) {
	   System.out.println("Failed to start Appium server" + e);
	   e.printStackTrace();
	  }
//	appiumService = AppiumDriverLocalService.buildDefaultService();
//	appiumServerURL= appiumService.getUrl().toString();
//	System.out.println("Appium service URL " + appiumServerURL);

}

@Test(dependsOnMethods={"startAppiumServer"})
public void killExistingSessions() {

  System.out.println("killing the existing sessions");
   CommandLine command = new CommandLine("cmd");
    command.addArgument("/c");
    command.addArgument("killall");
    command.addArgument("node");
   
    DefaultExecuteResultHandler resultHandler = new DefaultExecuteResultHandler();
    DefaultExecutor executor = new DefaultExecutor();
    executor.setExitValue(1);
   
    try {
      executor.execute(command, resultHandler);
      System.out.println("Sessions cleared");
    } catch (IOException e) {
    	System.out.println("Failed to pre kill the appium session" + e);
		  e.printStackTrace();//paste the complete trace.
    }
}

@Test(dependsOnMethods={"killExistingSessions"})
public void addCapabilities() {

    System.out.println("Declaring capabilities");
  
    iosCapabilities= new DesiredCapabilities();
    iosCapabilities.setCapability("CapabilityType.Browser_Name","Safari");
    iosCapabilities.setCapability("browserName", "");//Safari if we invoke browser for automation. Else an empty string.
    iosCapabilities.setCapability("autoWebview", true); // to retain the webview of app corresponding to session.
    iosCapabilities.setCapability("sendKeyStrategy", "grouped");
    iosCapabilities.setCapability("platformName", "iOS");
    iosCapabilities.setCapability("appium-version", "1.4.13");
    iosCapabilities.setCapability("platformVersion", "9.3.4");
    iosCapabilities.setCapability("deviceName", "XXXX Ipad");
    iosCapabilities.setCapability("device", "iPad Air 2");
    iosCapabilities.setCapability("appName", "XXXXX");
    iosCapabilities.setCapability("Udid", "29808cb769651XXXXXXf6d95a2ece576beb2591");
    iosCapabilities.setCapability("bundleId", "com.XX.XXXX.mobile");
//	iosCapabilities.setCapability("FullReset", true);
iosCapabilities.setCapability("NoReset", false);
iosCapabilities.setCapability("nativeInstrumentsLib", true); //Instructing to use Native instruments lib
iosCapabilities.setCapability("app", "/Users/XX/Documents/XXXX.ipa"); //<Mention the path , when app needs to be installed>
iosCapabilities.setCapability("orientation", "PORTRAIT");//setting up orientation due to open bugs in interacting with UI elements in Landscape mode.

}

@Test(dependsOnMethods={"addCapabilities"})
public void appiumDriverInitialization() throws MalformedURLException, InterruptedException{

   ios_driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"),iosCapabilities);
//	ios_driver = new IOSDriver(new URL(appiumServerURL),cap);

   System.out.println("Driver initialized");
}

**Comment by mykola-mokhnach** [comment]
```java
import org.openqa.selenium.net.UrlChecker;

....

    private static final String SERVER_URL = String.format("http://127.0.0.1:%d/wd/hub", PORT);

    private boolean waitUntilIsRunning(Timedelta timeout) throws Exception {
        final URL status = new URL(SERVER_URL + "/sessions");
        try {
            new UrlChecker().waitUntilAvailable(timeout.asMilliSeconds(), TimeUnit.MILLISECONDS, status);
            return true;
        } catch (UrlChecker.TimeoutException e) {
            return false;
        }
    }

```

**Comment by KalveeduVijay** [comment]
@mykola-mokhnach 
It'll be really helpful if you can explain about the code?

**Comment by mykola-mokhnach** [comment]
There is to explain here. The standard Selenium [UrlChecker](https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/net/UrlChecker.html) utility class is used to implement a timer, which verifies that Appium server returns 200 response.

**Comment by surikiran** [comment]
It has been frequently found that lots of people prefer CommandLine class for starting Appium server as if they are starting from a command line or terminal but this is not a good practice and it has lots of disadvantages as when type a command for starting appium through commandline or terminal it requires certain arguments/parameters in a relevant sequence if there is a change in this sequence the result will be failed. Having personal experience for starting appium through commandline for parallel execution I refrained doing this and started using AppiumDriverLocalService which is the best and has much and much more features hence I suggest you to modify your code by replacing CommandLine class with AppiumDriverLocalService. For more information refer the URL http://aksahu.blogspot.in/2015/10/start-and-stop-appium-server.html which is excellent and gives more information
