### ISSUE TITLE
Element not Found: XPATH with unicode characters 

### ISSUE THREAD

**Issue by RashmiMurthy** [appium/appium#7867]
## The problem

Element not Found exception : XPATH with unicode characters 
ex://XCUIElementTypeStaticText[@name='PRÉNOM']/following-sibling::XCUIElementTypeTextField

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 beta
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device

Exception:
org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)Command duration or timeout: 11.28 secondsFor documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.htmlBuild info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'System info: host: 'v-MacBook-Air.local', ip: '10.33.195.105', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12', java.version: '1.8.0_102'Driver info: io.appium.java_client.ios.IOSDriverCapabilities [{app=/Users/v/Library/Developer/Xcode/DerivedData/vi/Build/Products/Debug-iphoneos/Debug.app, networkConnectionEnabled=false, databaseEnabled=false, deviceName=iPad Simulator, platform=MAC, platformVersion=10.2, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=81c104c50d70ca9b065bd573e1e35a5620fc0dd0}]Session ID: f35942ca-f81d-416f-8799-93d02491d013*** Element info: {Using=xpath, value=//XCUIElementTypeStaticText[@name='PRÉNOM']/following-sibling::XCUIElementTypeTextField}

**Comment by mykola-mokhnach** [comment]
Is the element searchable by Accessibility Id?

```
driver.findElement(MobileBy.AccessibilityId("PRÉNOM"));
```

**Comment by RashmiMurthy** [comment]
Yes... Able to locate with driver.findElement(MobileBy.AccessibilityId("PRÉNOM"));

I want to type text in PRÉNOM field. so I am trying with xpath //XCUIElementTypeStaticText[@name='PRÉNOM']/following-sibling::XCUIElementTypeTextField.

driver.findElement(By.xpath(ObjRepoProp.getProperty("searchCriteriaTextBox_Part1_XPATH")
					+ TextProp.getProperty("Firstname") + ObjRepoProp.getProperty("searchCriteriaTextBox_Part2_XPATH"))).sendKeys("rrr");
			
does not locate that xpath

**Comment by mykola-mokhnach** [comment]
can you show the output of _getPageSource_ then? maybe your xpath locator is incorrect?

**Comment by RashmiMurthy** [comment]
hi....
Please find page source

<XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" x="0" y="0" width="1024" height="768">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="1024" height="768">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="1024" height="120">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="1024" height="70">
          <XCUIElementTypeButton type="XCUIElementTypeButton" name="FRANÇAIS" label="FRANÇAIS" enabled="true" x="912" y="20" width="84" height="50"/>
        </XCUIElementTypeOther>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="70" width="1024" height="50"/>
      </XCUIElementTypeOther>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="1024" height="768">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="1024" height="768">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="1024" height="768">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="1024" height="768">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="1024" height="768">
                <XCUIElementTypeImage type="XCUIElementTypeImage" name="bg-main.jpg" enabled="true" x="-1" y="-1" width="1026" height="770"/>
                <XCUIElementTypeScrollView type="XCUIElementTypeScrollView" enabled="true" x="0" y="0" width="1024" height="768">
                  <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="1024" height="768">
                    <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="LOUIS VUITTON" name="LOUIS VUITTON" label="LOUIS VUITTON" enabled="true" x="343" y="130" width="338" height="50"/>
                    <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="LV PARIS CHAMPS ELYSEES" name="LV PARIS CHAMPS ELYSEES" label="LV PARIS CHAMPS ELYSEES" enabled="true" x="350" y="190" width="324" height="28"/>
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="111" y="252" width="802" height="416">
                      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="111" y="252" width="490" height="416">
                        <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="RECHERCHE CLIENT" name="RECHERCHE CLIENT" label="RECHERCHE CLIENT" enabled="true" x="139" y="282" width="196" height="30"/>
                        <XCUIElementTypeCollectionView type="XCUIElementTypeCollectionView" enabled="true" x="131" y="320" width="450" height="252">
                          <XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" x="131" y="320" width="215" height="84">
                            <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="PRÉNOM" name="PRÉNOM" label="PRÉNOM" enabled="true" x="139" y="328" width="62" height="28"/>
                            <XCUIElementTypeTextField type="XCUIElementTypeTextField" label="" enabled="true" x="139" y="356" width="199" height="40"/>
                          </XCUIElementTypeCell>
                          <XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" x="366" y="320" width="215" height="84">
                            <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="NOM" name="NOM" label="NOM" enabled="true" x="374" y="328" width="40" height="28"/>
                            <XCUIElementTypeTextField type="XCUIElementTypeTextField" label="" enabled="true" x="374" y="356" width="199" height="40"/>
                          </XCUIElementTypeCell>
                          <XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" x="131" y="404" width="215" height="84">
                            <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="EMAIL" name="EMAIL" label="EMAIL" enabled="true" x="139" y="412" width="40" height="28"/>
                            <XCUIElementTypeTextField type="XCUIElementTypeTextField" label="" enabled="true" x="139" y="440" width="199" height="40"/>
                          </XCUIElementTypeCell>
                          <XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" x="366" y="404" width="215" height="84">
                            <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="TÉLÉPHONE" name="TÉLÉPHONE" label="TÉLÉPHONE" enabled="true" x="374" y="412" width="77" height="28"/>
                            <XCUIElementTypeTextField type="XCUIElementTypeTextField" label="" enabled="true" x="374" y="440" width="199" height="40"/>
                          </XCUIElementTypeCell>
                          <XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" x="131" y="488" width="215" height="84">
                            <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="NUMÉRO DE PASSEPORT" name="NUMÉRO DE PASSEPORT" label="NUMÉRO DE PASSEPORT" enabled="true" x="139" y="496" width="163" height="28"/>
                            <XCUIElementTypeTextField type="XCUIElementTypeTextField" label="" enabled="true" x="139" y="524" width="199" height="40"/>
                          </XCUIElementTypeCell>
                          <XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" x="366" y="488" width="215" height="84">
                            <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="PAYS DE RÉSIDENCE" name="PAYS DE RÉSIDENCE" label="PAYS DE RÉSIDENCE" enabled="true" x="374" y="496" width="132" height="28"/>
                            <XCUIElementTypeTextField type="XCUIElementTypeTextField" label="" enabled="true" x="374" y="524" width="199" height="40"/>
                          </XCUIElementTypeCell>
                        </XCUIElementTypeCollectionView>
                        <XCUIElementTypeButton type="XCUIElementTypeButton" name="RECHERCHE" label="RECHERCHE" enabled="true" x="139" y="600" width="202" height="40"/>
                        <XCUIElementTypeImage type="XCUIElementTypeImage" name="icn-enterbtn-arrow.png" enabled="true" x="154" y="613" width="9" height="14"/>
                      </XCUIElementTypeOther>
                      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="627" y="252" width="286" height="416">
                        <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="NOUVEAU CLIENT" name="NOUVEAU CLIENT" label="NOUVEAU CLIENT" enabled="true" x="655" y="282" width="181" height="30"/>
                        <XCUIElementTypeButton type="XCUIElementTypeButton" name="icon new client" label="icon new client" enabled="true" x="706" y="396" width="128" height="128"/>
                        <XCUIElementTypeButton type="XCUIElementTypeButton" name="CRÉATION" label="CRÉATION" enabled="true" x="655" y="600" width="230" height="40"/>
                        <XCUIElementTypeImage type="XCUIElementTypeImage" name="icn-enterbtn-arrow.png" enabled="true" x="670" y="613" width="9" height="14"/>
                      </XCUIElementTypeOther>
                    </XCUIElementTypeOther>
                    <XCUIElementTypeButton type="XCUIElementTypeButton" name="PARAMÈTRES" label="PARAMÈTRES" enabled="true" x="461" y="712" width="102" height="38"/>
                    <XCUIElementTypeImage type="XCUIElementTypeImage" name="icon-top-arrow.png" enabled="true" x="566" y="725" width="13" height="8"/>
                  </XCUIElementTypeOther>
                </XCUIElementTypeScrollView>
              </XCUIElementTypeOther>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" x="0" y="0" width="1024" height="768">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="1024" height="768"/>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" x="0" y="0" width="1024" height="768">
    <XCUIElementTypeStatusBar type="XCUIElementTypeStatusBar" enabled="true" x="0" y="0" width="1024" height="20">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="1024" height="20"/>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="1024" height="20">
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="iPad" label="iPad" enabled="true" x="6" y="0" width="26" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" value="SSID" name="3 of 3 Wi-Fi bars" label="3 of 3 Wi-Fi bars" enabled="true" x="37" y="0" width="13" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="6:37 PM" label="6:37 PM" enabled="true" x="488" y="0" width="52" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="100% battery power, On AC Power" label="100% battery power, On AC Power" enabled="true" x="951" y="0" width="68" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="100% battery power" label="100% battery power" enabled="true" x="951" y="0" width="32" height="20"/>
      </XCUIElementTypeOther>
    </XCUIElementTypeStatusBar>
  </XCUIElementTypeWindow>
</XCUIElementTypeApplication></AppiumAUT>

**Comment by RashmiMurthy** [comment]
Hi...

PFA Page source
[PageSource.txt](https://github.com/appium/appium/files/776071/PageSource.txt)

**Comment by mykola-mokhnach** [comment]
That's strange...

Can you try whether the following xpaths work?

```
//XCUIElementTypeStaticText[@name='PRÉNOM']
//XCUIElementTypeCell[ ./XCUIElementTypeStaticText[@name='PRÉNOM'] ]/XCUIElementTypeTextField
```

**Comment by RashmiMurthy** [comment]
Hi...

Above mentioned works. With Unicode characters not working.
In our framework text we are storing text with different language in property file eclipse.
So it will be stored like this  Firstname=PRE\u0301NOM

Code: 
driver.findElement(By.xpath("//XCUIElementTypeStaticText[@name='+TextObj.getProperty("Firstname")+']/following-sibling::XCUIElementTypeTextField")).sendKeys("rrr");

On execution:

org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. Element info: {Using=xpath, value=//XCUIElementTypeStaticText[@name='PRÉNOM']/following-sibling::XCUIElementTypeTextField}.

As if now I ll use directly with out property file.

**Comment by mykola-mokhnach** [comment]
So the issue can be closed?

**Comment by RashmiMurthy** [comment]
Yeah.
