### ISSUE TITLE
[Appium 1.6.3] On iOS, Failed to launch the Safari browser-Error: Could not connect to a valid app after 20 tries.

### ISSUE THREAD

**Issue by vsadineni1** [appium/appium#7870]
As part of my test I am trying to launch the Safari browser on iOS simulator on Mac. It fails to launch the Safari browser and goes in cycles & fails eventually.

## Environment

* Appium version : 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: MAC OSX Sierra (10.12.2)
* Node.js version (unless using Appium.app|exe): v7.1.0
* Mobile platform/version under test: iOS 10.0
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: Appium exe. 
* XCode - 8.2.1

## Details
Sometimes it works for the first test othertimes it may fail even for the first test.
I have the below components installed:
Mac OSX: 10.12.2
XCode: 8.2.1
Appium: 1.6.3
carthage
We have tested this on Multiple MAc machines. Observed the same behavior.
If we launch the Safari browser manually while the test is trying & failing to launch, then the rest of the test execution is successful.

## Link to Appium logs
Gist Link: https://gist.github.com/vsadineni1/2b283c8c6f0862356236ce2d7f0d1414

**Comment by vsadineni1** [comment]
So once we reach this bad state:
**_[RemoteDebugger] Error: Could not connect to a valid app after 20 tries._**

 then all subsequent tests are also behaving the same. They fail to launch the Safari browser.
I confirmed that each test is calling the quit.  Here is the snippet of the log lines for that: 
https://gist.github.com/vsadineni1/2a0f4d07f9a87711fc43bb140c08a513

**Comment by imurchie** [comment]
Can you try the 1.6.4 beta (`npm uninstall -g appium && npm install -g appium@beta`)? There was a change that should help with this.

**Comment by vsadineni1** [comment]
Thank you @imurchie 
I tested on **appium 1.6.4-beta**. So far it is **looking good**. I did not see this issue. I ran a whole bunch of tests.
