### ISSUE TITLE
Unable to verify chrome browser access popup

### ISSUE THREAD

**Issue by 910301** [appium/appium#7873]
## The problem

after using the appium browser to automate Chrome Browser, No access popup are detected in the Chrome Browser.
Please help me with this

## Environment

* Appium version (or git revision) that exhibits the issue: recent version
* Last Appium version that did not exhibit the issue (if applicable): ?
* Node.js version (unless using Appium.app|exe): ? 
* Mobile platform/version under test: Android allversion
* Real device or emulator/simulator: realdevice, emulator
* Appium CLI or Appium.app|exe:

**Comment by mykola-mokhnach** [comment]
Sorry, we are not able to help without having appium logs, code examples and/or a screenshot. Please fill out the issue template carefully and reopen the issue then.
