### ISSUE TITLE
Sometimes when click a element will throw a issue

### ISSUE THREAD

**Issue by MarvinLiuMing** [appium/appium#7876]
## The problem

Sometimes when click a element will throw a issue. But not every time being wrong

## Environment

Appium version : 1.6.3
Last Appium version that did not exhibit the issue (if applicable):
Desktop OS/version used to run Appium: win10
Node.js version : 4.5.0
Mobile platform/version under test: Android 7.0
Real device or emulator/simulator: emulator
Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/MarvinLiuMing/a869e1bcfd29caf7720f154284e645f6

**Comment by mykola-mokhnach** [comment]
**StaleObjectException** is thrown when one tries to access an element, which does not exist in DOM tree anymore or which state has been changed. Read http://stackoverflow.com/questions/12967541/how-to-avoid-staleelementreferenceexception-in-selenium for more details.

Simple solution - do not reuse **WebElement** instance, but rather call *driver.findElement* each time you need to do some action on the element.

**Comment by MarvinLiuMing** [comment]
@mykola-mokhnach 
It helps me too much. Thanks a lot!!
