### ISSUE TITLE
Clearing a password edit text in native app on Android Emulators

### ISSUE THREAD

**Issue by tshkursk** [appium/appium#7878]
Observation:
When calling io.appium.java_client.MobileElement.clear() where the instance of MobileElement is a password text field (secure field with dots instead of characters ), field remains uncleared

Expected:
All characters in a password text field should be deleted.

* Appium version: 1.4.16, 1.5.3
* Android: 4.4 (API level 19), 5.0 (API level 21), 5.1 (API level 22), 6.0 (API level 23)
* Device: Nexus S (4.0'')
* io.appium >> java-client: 4.1.2

Note that instance of MobileElement - password text field - io.appium.java_client.MobileElement.getTest() returns empty string value, but in fact the field can be non-empty at the moment

Workaround (https://github.com/appium/appium/issues/2349):
Long press and use the delete keyevent -works fine, but it would be great to have default action functioning.

Link to Appium logs:
https://gist.github.com/tshkursk/147399705bebce4eafe91fa9eae549cb

**Comment by imurchie** [comment]
Android does not give any way of getting the text, obscured or not, from a password field. It will always report as empty.

That said, the latest Appium will faithfully delete the text from it. I just did a quick test and it deleted 100 characters without a problem.
