### ISSUE TITLE
getting error iproxy exited with code '208' when running test on parallel device iOS

### ISSUE THREAD

**Issue by prateekchawla** [appium/appium#7879]
When running an appium test paraallely on multiple iOS devices , the test does not launches on second device and gives "iproxy exited with code '208'".

Appium version (or git revision) that exhibits the issue: 1.6.1-beta
Last Appium version that did not exhibit the issue (if applicable): NA
Desktop OS/version used to run Appium: 10.11.5
Node.js version (unless using Appium.app|exe): NA
Mobile platform/version under test: Ipad - 9.3.5
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe: Appium CLI

**Comment by prateekchawla** [comment]
I can provide logs if necessary 
Is it related to running multiple iproxy sessions? since the teest on second devicce breaks on the point
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB

**Comment by imurchie** [comment]
Most likely, yes. You can set the `wdaLocalPort` to change what iproxy is connecting to.

**Comment by prateekchawla** [comment]
Thanks thats in the cap? and what are the other ports avalilable @imurchie ?

**Comment by imurchie** [comment]
`wdaLocalPort` is a desired capability. It takes an integer, which can be any valid port that is not already in use.

**Comment by prateekchawla** [comment]
my webkit remote debugger socket is getting disconnected on one appium server session 
You got any idea to fix this?

**Comment by prateekchawla** [comment]
or how to change the port for Webkit remote debugger?

**Comment by imurchie** [comment]
See `--webkit-debug-proxy-port` https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md

**Comment by prateekchawla** [comment]
okay. For eg:
How can i tell my apppium server session to pick --webkit-debug-proxy-port 27754

**Comment by prateekchawla** [comment]
because i already have a session of --webkit-debug-proxy-port 27753

**Comment by imurchie** [comment]
I don't understand your question. Are you trying to run two iOS sessions at the same time on one Appium server? Because that will not work.

**Comment by prateekchawla** [comment]
no i have two different Appium server sesssions and ios webkit debug connected on 27753 and 27754.
Now, How can i tell my appium server session to consider two different webkit debug proxy

**Comment by prateekchawla** [comment]
and I am using 2 different wda ports for 2 different appium sessions

**Comment by eyypbgds** [comment]
Hi @prateekchawla ,

You should start webkit in two different terminal; 
Device 1 :
ios_webkit_debug_proxy -c udid1:27753 -d

Device 2 :
ios_webkit_debug_proxy -c udid2:27754 -d

And start appium for each devices with udid's and webkit port's ;

Device 1 :
appium -U udid1 --webkit-debug-proxy-port 27753

Device 2 :
appium -U udid2 --webkit-debug-proxy-port 27754

**Comment by prateekchawla** [comment]
Thanks @eyypbgds , @imurchie It worked. 
Closing the issue now
