### ISSUE TITLE
"Unhandled endpoint" from AppiumDriver.getPageSource()

### ISSUE THREAD

**Issue by giripalanivel** [appium/appium#7880]
AppiumDriver.getPageSource() is throwing the below error.

An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/1A355A7C-1000-4E47-A124-B23E1CBD984B/source/xml -- http://localhost:8100/ with parameters {
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/1A355A7C-1000-4E47-A124-B23E1CBD984B/source/xml -- http://localhost:8100/ with parameters {
wildcards = (
"session/1A355A7C-1000-4E47-A124-B23E1CBD984B/source/xml"
);
} (WARNING: The server did not provide any stacktrace information)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.1
* Desktop OS/version used to run Appium: MAC OS 10.10
* Node.js version (unless using Appium.app|exe): n/a
* Mobile platform/version under test: iOS 10.2.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs
[gist](https://gist.github.com/giripalanivel/abbf043b149b4a56e3ea3a41234ed7f7)

**Comment by imurchie** [comment]
Did you update Appium without uninstalling? This feels like for some reason the WebDriverAgent installation didn't get updated.

**Comment by giripalanivel** [comment]
Yes I did uninstalled and installed but somehow it didn't work that time.
After I tried for couple of times, now it is working. Thanks @imurchie .

**Comment by epankaj1** [comment]
I am still getting the same issue with Appium 1.6.4 , iPhone6s Real device ( iOS 10.3) , Xcode 8.3.1 , Java Client 4.1.2...I uninstalled Appium 1.6.4 and re-installed it 3 times and i am still facing the same issue.

**Comment by epankaj1** [comment]
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/094A8646-A2A6-4255-A832-978EF7675922/wda/tap/7BA4C7C0-4AE4-4336-9C1C-CBC270A18098 -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/094A8646-A2A6-4255-A832-978EF7675922/wda/tap/7BA4C7C0-4AE4-4336-9C1C-CBC270A18098"
    );
} (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 36 milliseconds
Build info: version: 'unknown', revision: '1969d75', time: '2016-10-18 09:43:45 -0700'
System info: host: 'watsonhalthsmbp.in.ibm.com', ip: '9.193.78.29', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.4', java.version: '1.8.0_121'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/Users/watsonhealth/Documents/PANKAJ/WatsonHealthNativeApp/WatsonHealthV&VNative.ipa, networkConnectionEnabled=false, bundleid=com.ibm.curam.mobile.Test123, databaseEnabled=false, deviceName=Sarat chandra Sambangi's iPhone, launchTimeout=500000, platform=MAC, platformVersion=10.3, webStorageEnabled=false, locationContextEnabled=false, automationName=XCuiTest, browserName=, takesScreenshot=true, javascriptEnabled=true, platformName=iOS, udid=89825b99211488fa90ce578f24dbb5f860f0f9c7}]
Session ID: 47a54b37-39b3-4644-811e-ea5b13c80ea4
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:40)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.AppiumDriver.performTouchAction(AppiumDriver.java:336)
	at io.appium.java_client.TouchAction.perform(TouchAction.java:323)
	at appium.test.TapTest1.setUp(TapTest1.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by epankaj1** [comment]
appium 1.6.4
Xcode: 8.3.1
iPhone 6s: iOS 10.3.1
mac OS Sierra: 10.12.4
Java Client 5.0.0-BETA ( Also tried with 4.1.2)

**Comment by epankaj1** [comment]
I am testing on native iOS app
Method i tried
A)
driver.tap(1, driver.findElement(By.id( "Next")), 10)
B)
TouchAction action1 = new TouchAction(driver);
action1.tap(driver.findElementByAccessibilityId("Next")).perform();


Can anyone help resolve this error..in case i need to provide further log details please let me know.

**Comment by epankaj1** [comment]
i uninstalled appium1.6.3 and re-installed appium1.6.4 multiple times...the Test that is working on my native iOS entering text in a text box. Rotating but actions like tap,touch,press,longpress is not working.

**Comment by epankaj1** [comment]
Can any one assist what could be wrong...

**Comment by epankaj1** [comment]
[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"app":"/Users/watsonhealth/Documents/PANKAJ/WatsonHealthNativeApp/WatsonHealthV&VNative.ipa","platformVersion":"10.3","bundleid":"com.ibm.curam.mobile.Test123","automationName":"XCuiTest","platformName":"iOS","udid":"89825b99211488fa90ce578f24dbb5f860f0f9c7","deviceName":"Sarat chandra Sambangi's iPhone","launchTimeout":500000},"requiredCapabilities":{}},"desiredCapabilities":{"app":"/Users/watsonhealth/Documents/PANKAJ/WatsonHealthNativeApp/WatsonHealthV&VNative.ipa","platformVersion":"10.3","bundleid":"com.ibm.curam.mobile.Test123","automationName":"XCuiTest","platformName":"iOS","udid":"89825b99211488fa90ce578f24dbb5f860f0f9c7","deviceName":"Sarat chandra Sambangi's iPhone","launchTimeout":500000},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/watsonhealth/Documents/PANKAJ/WatsonHealthNativeApp/WatsonHealthV&VNative.ipa","platformVersion":"10.3","bundleid":"com.ibm.curam.mobile.Test123","automationName":"XCuiTest","platformName":"iOS","udid":"89825b99211488fa90ce578f24dbb5f860f0f9c7","deviceName":"Sarat chandra Sambangi's iPhone","launchTimeout":500000},{},{"desiredCapabilities":{"app":"/Users/watsonhealth/Documents/PANKAJ/WatsonHealthNativeApp/WatsonHealthV&VNative.ipa","platformVersion":"10.3","bundleid":"com.ibm.curam.mobile.Test123","automationName":"XCuiTest","platformName":"iOS","udid":"89825b99211488fa90ce578f24dbb5f860f0f9c7","deviceName":"Sarat chandra Sambangi's iPhone","launchTimeout":500000},"requiredCapabilities":{}},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1492167437439 (16:27:17 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   app: '/Users/watsonhealth/Documents/PANKAJ/WatsonHealthNativeApp/WatsonHealthV&VNative.ipa'
[Appium]   platformVersion: '10.3'
[Appium]   bundleid: 'com.ibm.curam.mobile.Test123'
[Appium]   automationName: 'XCuiTest'
[Appium]   platformName: 'iOS'
[Appium]   udid: '89825b99211488fa90ce578f24dbb5f860f0f9c7'
[Appium]   deviceName: 'Sarat chandra Sambangi\'s iPhone'
[Appium]   launchTimeout: 500000
[debug] [XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] The following capabilities were provided, but are not recognized by appium: bundleid.
[BaseDriver] Session created with session id: 47a54b37-39b3-4644-811e-ea5b13c80ea4
[debug] [XCUITest] Xcode version set to '8.3.1' (tools v8.3.0.0.1.1490382677)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1492167437570 (16:27:17 GMT+0530 (IST))
[debug] [XCUITest] Available devices: 89825b99211488fa90ce578f24dbb5f860f0f9c7
[debug] [XCUITest] Creating iDevice object with udid '89825b99211488fa90ce578f24dbb5f860f0f9c7'
[XCUITest] Determining device to run tests on: udid: '89825b99211488fa90ce578f24dbb5f860f0f9c7', real device: true
[BaseDriver] Using local app '/Users/watsonhealth/Documents/PANKAJ/WatsonHealthNativeApp/WatsonHealthV&VNative.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/08/kwqlv05x2hj7q68stj69qw8m0000gn/T/2017314-2100-14aw1kq.mie3rtfbt9/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/08/kwqlv05x2hj7q68stj69qw8m0000gn/T/2017314-2100-14aw1kq.mie3rtfbt9/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/08/kwqlv05x2hj7q68stj69qw8m0000gn/T/2017314-2100-14aw1kq.mie3rtfbt9/Payload/WatsonHealthV&VNative.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1492167437962 (16:27:17 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/var/folders/08/kwqlv05x2hj7q68stj69qw8m0000gn/T/2017314-2100-14aw1kq.mie3rtfbt9/Payload/WatsonHealthV&VNative.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/08/kwqlv05x2hj7q68stj69qw8m0000gn/T/2017314-2100-14aw1kq.mie3rtfbt9/Payload/WatsonHealthV&VNative.app': 'com.ibm.curam.mobile.Test123'
[debug] [BaseDriver] Event 'resetStarted' logged at 1492167437978 (16:27:17 GMT+0530 (IST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1492167437979 (16:27:17 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1492167438128 (16:27:18 GMT+0530 (IST))
[XCUITest] Setting up real device
[debug] [XCUITest] Reset requested. Removing app with id 'com.ibm.curam.mobile.Test123' from the device
[debug] [XCUITest] Installing '/var/folders/08/kwqlv05x2hj7q68stj69qw8m0000gn/T/2017314-2100-14aw1kq.mie3rtfbt9/Payload/WatsonHealthV&VNative.app' on device with UUID '89825b99211488fa90ce578f24dbb5f860f0f9c7'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1492167439781 (16:27:19 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1492167439783 (16:27:19 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=89825b99211488fa90ce578f24dbb5f860f0f9c7 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.3.1\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.3.1\"\n    },\n    \"build\" : {\n      \"time\" : \"Apr  6 2017 11:03:39\"\n    }\n  },\n  \"sessionId\" : \"AE42622E-D5B4-4893-8109-B89BF6244393\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent successfully started after 776ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1492167445661 (16:27:25 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.ibm.curam.mobile.Test123","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [XCUITest] Log file for xcodebuild test: /Users/watsonhealth/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/D1415B88-2B81-4F91-8E0E-4CE700F9610E/Session-WebDriverAgentRunner-2017-04-14_162726-FnQM64.log
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1492167448788 (16:27:28 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.ibm.curam.mobile.Test123","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1492167449799 (16:27:29 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.ibm.curam.mobile.Test123","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1492167450808 (16:27:30 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.ibm.curam.mobile.Test123","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1492167451815 (16:27:31 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.ibm.curam.mobile.Test123","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1492167452822 (16:27:32 GMT+0530 (IST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.ibm.curam.mobile.Test123","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"094A8646-A2A6-4255-A832-978EF7675922","capabilities":{"device":"iphone","browserName":"WatsonHealthV&VNative","sdkVersion":"10.3.1","CFBundleIdentifier":"com.ibm.curam.mobile.Test123"}},"sessionId":"094A8646-A2A6-4255-A832-978EF7675922","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1492167453628 (16:27:33 GMT+0530 (IST))
[debug] [XCUITest] Found WDA derived data folder: '/Users/watsonhealth/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy'
[XCUITest] Setting '555' permissions to '/Users/watsonhealth/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
[debug] [XCUITest] Found WDA derived data folder: '/Users/watsonhealth/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn'
[XCUITest] Setting '555' permissions to '/Users/watsonhealth/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn/Logs/Test/Attachments' folder
[debug] [XCUITest] Found WDA derived data folder: '/Users/watsonhealth/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs'
[XCUITest] Setting '555' permissions to '/Users/watsonhealth/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Attachments' folder
[debug] [BaseDriver] Event 'wdaPermsAdjusted' logged at 1492167453632 (16:27:33 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1492167453632 (16:27:33 GMT+0530 (IST))
[debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
[debug] [JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/094A8646-A2A6-4255-A832-978EF7675922/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"094A8646-A2A6-4255-A832-978EF7675922","status":0}
[debug] [BaseDriver] Event 'orientationSet' logged at 1492167454010 (16:27:34 GMT+0530 (IST))
[Appium] New XCUITestDriver session created successfully, session 47a54b37-39b3-4644-811e-ea5b13c80ea4 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1492167454011 (16:27:34 GMT+0530 (IST))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"app":"/Users/watsonhealth/Documents/PANKAJ/WatsonHealthNativeApp/WatsonHealthV&VNative.ipa","platformVersion":"10.3","bundleid":"com.ibm.curam.mobile.Test123","automationName":"XCuiTest","platformName":"iOS","udid":"89825b99211488fa90ce578f24dbb5f860f0f9c7","deviceName":"Sarat chandra Sambangi's iPhone","launchTimeout":500000}
[HTTP] <-- POST /wd/hub/session 200 16578 ms - 598 
[HTTP] --> POST /wd/hub/session/47a54b37-39b3-4644-811e-ea5b13c80ea4/timeouts {"type":"implicit","ms":100000}
[debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",100000,"47a54b37-39b3-4644-811e-ea5b13c80ea4"]
[debug] [XCUITest] Executing command 'timeouts'
[debug] [BaseDriver] Set implicit wait to 100000ms
[debug] [MJSONWP] Responding to client with driver.timeouts() result: null
[HTTP] <-- POST /wd/hub/session/47a54b37-39b3-4644-811e-ea5b13c80ea4/timeouts 200 11 ms - 76 
[HTTP] --> POST /wd/hub/session/47a54b37-39b3-4644-811e-ea5b13c80ea4/element {"using":"accessibility id","value":"Next"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["accessibility id","Next","47a54b37-39b3-4644-811e-ea5b13c80ea4"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[debug] [BaseDriver] Waiting up to 100000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/094A8646-A2A6-4255-A832-978EF7675922/element] with body: {"using":"accessibility id","value":"Next"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"7BA4C7C0-4AE4-4336-9C1C-CBC270A18098","type":"XCUIElementTypeButton","label":"Next"},"sessionId":"094A8646-A2A6-4255-A832-978EF7675922","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"7BA4C7C0-4AE4-4336-9C1C-CBC270A18098","type":"XCUIElementTypeButton","label":"Next"}
[HTTP] <-- POST /wd/hub/session/47a54b37-39b3-4644-811e-ea5b13c80ea4/element 200 212 ms - 168 
[HTTP] --> POST /wd/hub/session/47a54b37-39b3-4644-811e-ea5b13c80ea4/touch/perform {"actions":[{"action":"tap","options":{"element":"7BA4C7C0-4AE4-4336-9C1C-CBC270A18098"}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"tap","options":{"element":"7BA4C7C0-4AE4-4336-9C1C-CBC270A18098"}}],"47a54b37-39b3-4644-811e-ea5b13c80ea4"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: tap(options={"element":"7BA4C7C0-4AE4-4336-9C1C-CBC270A18098"})
[debug] [XCUITest] Found matching gesture: tap
[debug] [JSONWP Proxy] Proxying [POST /wda/tap/7BA4C7C0-4AE4-4336-9C1C-CBC270A18098] to [POST http://localhost:8100/session/094A8646-A2A6-4255-A832-978EF7675922/wda/tap/7BA4C7C0-4AE4-4336-9C1C-CBC270A18098] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Unhandled endpoint: /session/094A8646-A2A6-4255-A832-978EF7675922/wda/tap/7BA4C7C0-4AE4-4336-9C1C-CBC270A18098 -- http://localhost:8100/ with parameters {\n    wildcards =     (\n        \"session/094A8646-A2A6-4255-A832-978EF7675922/wda/tap/7BA4C7C0-4AE4-4336-9C1C-CBC270A18098\"\n    );\n}","sessionId":"094A8646-A2A6-4255-A832-978EF7675922","status":1}
[HTTP] <-- POST /wd/hub/session/47a54b37-39b3-4644-811e-ea5b13c80ea4/touch/perform 500 20 ms - 462 
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted

**Comment by epankaj1** [comment]
The same code works fine on Simulator

**Comment by levinzhang1981** [comment]
when i use appium 1.6.3 and the latest WebDriverAgent(clone from GitHub),I encount this problem.Then I remove  latest WebDriverAgent and use WebDriverAgent  in appium_xcuitest_driver 2.9.0,the problem is solved.

**Comment by lvconley** [comment]
I'm running Appium 1.6.4 and getting the same error:

[com.disney.appium.common.BaseTest setupDriver] inside catch, message: Unhandled endpoint: /session/3783C5C0-CF8D-4ABE-A86F-C04E36FB875F/url -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/3783C5C0-CF8D-4ABE-A86F-C04E36FB875F/url"
    );

I've commented out on driver.getPageSource() calls and the issue is still happening. What is maddening is that all was fine for most of the day and then all of a sudden the issue started happening even though no changes were made to the environment. 

This issue is blocking me %100, so any feedback on what the cause is would be most helpful.

**Comment by lvconley** [comment]
@levinzhang1981, what is the process for removing the current WebDriverAgent and replacing it with appium_xcuitest_driver 2.9.0? I can use NPM to install like so:

`npm install appium-xcuitest-driver@2.9.0`

But when I do this I get the following error:

```
$ npm install appium-xcuitest-driver@2.9.0
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "appium-xcuitest-driver@2.9.0"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ENOSELF
npm ERR! Refusing to install appium-xcuitest-driver as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/laconley/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Scripts/npm-debug.log
```

I found the driver here:

[(https://www.versioneye.com/nodejs/appium-xcuitest-driver/2.9.0)]

**Comment by lvconley** [comment]
Oddly, this issue was caused by the initialization of logging objects in a method we have for initializing the driver.  Once I commented-out the lines which initialized the logging object, the "unhandled endpoint" error went away. We are still trying to figure out what's happening with this because we need that logging:

  ```
public static AppiumDriver initializeDriver(final String testName,
      final String applicationName, final String platform,
      final String platformVersion, final String deviceName,
      final String seleniumUrl) throws Exception {

    final AppiumDriver driver = buildDriver(applicationName, platform, platformVersion, deviceName, seleniumUrl, true, testName);

//    Log.initialize(testName, driver);
//    Log.replaceLogFormatter(driver);
//    Log.replaceErrorLogFormatter(driver);

    return driver;
  }
```

**Comment by frenchtoastcrew** [comment]
For me , manually deleting the WebDriverAgent app from the target device , solved the problem. 
The issue was with different versions of appium running against the same device , so I guess WDA version didn't match.

**Comment by hemano** [comment]
Works fine with Appium 1.8.1 and Java client 6.1.0
