### ISSUE TITLE
Is there any way to reset iOS App in each test case execution?

### ISSUE THREAD

**Issue by davidrova** [appium/appium#7881]
## The problem

I would like to execute each test case as it would be the first access.

It is very easy in Android, using browser.reset(); but it doesn't work in iOS

See issue opened in webdriverIO's repository https://github.com/webdriverio/webdriverio/issues/1875

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta, 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe): 6.2.2
* Mobile platform/version under test: iPhone 5s
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

I would like to execute each test case as it would be the first access.

It is very easy in Android, using browser.reset(); but it doesn't work in iOS

See issue opened in webdriverIO's repository https://github.com/webdriverio/webdriverio/issues/1875

## Link to Appium logs

At this moment it is not necessary.

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by mykola-mokhnach** [comment]
Have you tried to set **fullReset** capability to **true**?

**Comment by davidrova** [comment]
fullReset is very very slow, and only works in the first scenario.

iOS is getting me mad :-(

**Comment by mykola-mokhnach** [comment]
> and only works in the first scenario

What does it mean? What happens to the following scenarios? Are you testing in a web browser or this is a standalone app?

**Comment by davidrova** [comment]
It is an hybrid application.

**Comment by amedvedjev** [comment]
also try "NO_RESET" = false

**Comment by davidrova** [comment]
Yes I have tried.

Right now, my colleagues have tried with 

```
After hook: this.does.closeApp();
Before hook: this.does.launch();
```

and they assure it works. 

This issue is related with
[https://discuss.appium.io/t/want-to-restart-ios-application-in-a-single-appium-session-without-deleting-uninstalling-it/6027/22](issue)

**Comment by mayureshshirodkar** [comment]
I have been using fullReset capability to true and it works fine for me.
Although i should mention it is very slow and adds up to the time my test suite as @davidrova mentioned.

**Comment by jlipps** [comment]
Rather than having one session and calling reset manually in between, it's best to just have a new session for each test, using whatever reset strategy you want.

**Comment by hansjoergkeser** [comment]
driver.closeApp() and .launchApp() seems to just restart the iOS App without removing the app data. But it is helpful to start over at the app entry point like onboarding, e.g. at the end of a test before next one starts.
Also i don't like the approach to start a new session for each test as it takes time, especially if real devices have to be allocated.
The following (Java) code worked for me

driver.launchApp();
driver.removeApp(iOSAppBundleId);
String appPath = driverProvider.getAppDriver().getCapabilities().getCapability("app").toString();
driver.installApp(appPath);
driver.launchApp();

Now the app is uninstalled and installed afterwards, having the app in clean state without any user-data or similar.

**Comment by Krisgk1** [comment]
@hansjoergkeser Where did you write the above kava code to reset the app /I need to reset for every feature test

**Comment by hansjoergkeser** [comment]
@Krisgk1 i used JUnit TestRule and added a annotation at each test (between @Test and the test method name) where needed, to let only reinstall the app if necessary.
Have to mention that unfortunately it fails sometimes during my tests on real devices with WebDriverException:
Could not install app: 'Command 'ios-deploy --id [...] --uninstall --bundle /Users/ios/[...].app' exited with code 253'
