### ISSUE TITLE
How to "clear history and website data" or start clear session 

### ISSUE THREAD

**Issue by shapovalovei** [appium/appium#7882]
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: OS X Sierra 
* Node.js version (unless using Appium.app|exe): 7
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real device (iPhone 6 iOS 10.2)
* Appium CLI or Appium.app|exe: CLI

## Details

How to "clear history and website data" or start clear session on iOS ? 

Capabilities didn't help 
`desiredCapabilities.setCapability(MobileCapabilityType.NO_RESET, false);`

**Comment by mykola-mokhnach** [comment]
Did you try setting **fullReset** capability to _true_?

**Comment by shapovalovei** [comment]
@mykola-mokhnach Yes. but this didn't help

**Comment by mykola-mokhnach** [comment]
Ah, you are on real device. Then pass our kudos to Apple ;) There is no known way to reset Safari browsing data using one simple command.
Although, in theory you can try to:

- Open a private tab and then work inside this tab
- Clear browsing data by clicking the same buttons (using Appium), that "normal" user would click to clear the data.
- Create a "magic" control on your site under test, which resets the local data and activate it every time you need to clear the stuff

**Comment by saikrishna321** [comment]
@mykola-mokhnach how can we start private tab from appium ?

**Comment by mykola-mokhnach** [comment]
There is no built-in possibility to do it directly. Just perform the same tap actions as a normal user would do in order to open it.
