### ISSUE TITLE
Running Appium tests remotely

### ISSUE THREAD

**Issue by qakapil** [appium/appium#7883]
This is more of a question rather than a bug.I was wondering if it is possible to execute appium tests on a remote host ? 
To keep it simple - For example I have a Mac A where I have Appium server installed and test code deployed. And a Mac B where I have Xcode installed and iOS device connected. Can I run tests on Mac B which for webdriver commands makes calls to remote Appium server on Mac A ?

**Comment by imurchie** [comment]
The architecture would be more like Mac A running the test code, and Mac B with Xcode installed running the Appium server process.

The answer to that is yes.

**Comment by qakapil** [comment]
@imurchie Thanks for the quick reply. So my iOS device also needs to be connected to Mac B right ?

**Comment by imurchie** [comment]
Yes. To the same machine running the Appium server.

**Comment by qakapil** [comment]
Okay. I was thinking that if we could have one appium server deployed on a centralized server and all the client hosts running tests by connecting this centralized appium server then running tests in parallel would have been much simpler.
At the moment, I do run my tests in parallel on multiple devices connected to a Mac but I have to launch different instances on appium for each test run and make sure that each instance uses a different port. Though I haven't tried this on Appium-XcuiTest yet. I guess in addition to appium port (default 4723), I will also have to now consider about WDA port (default 9221)
