### ISSUE TITLE
Cannot Launch Appium Inspector 

### ISSUE THREAD

**Issue by GEguy** [appium/appium#7886]
Hello I am new to Appium and App test automation.

I am trying all the steps to automate testing using Appium. I made sure the app path points to the IPA file, and I have connected my device and properly entered the UDID. Then I click on launch and once the "Get 200" comes up, I click the "Inspector" icon and I get the following error

Could Not Launch Appium Inspector

Could not start a new session

Be sure the Appium server is running with an application opened by using the "App Path" parameter in Appium.app (along with package and activity for Android) or by connecting with selenium client and supplying this in the desired capabilities object.

Why is this happening? This seems to be a fairly common post, but I can't figure out what I'm doing wrong. Some people mention somehting about a selenium client? I'm not sure what that is but I have downloaded the two JAR files:

selenium-server-standalone-3.0.1.jar
java-client-4.1.2.jar

What do I do with those files. Thanks for any help! Below are my setup stats:

MacOS Sierra 10.12.3
Xcode 8.2.1
iOS 10.2
Appium version 1.5.3

Someone suggested that I run the following command in Terminal: 

appium --default-capabilities '{"fullReset":true}'

But I got the following response: -bash: appium: command not found

**Comment by mykola-mokhnach** [comment]
Sorry, but Appium inspector for desktop is not supported anymore. Although you can try some [alternatives](https://medium.com/@chenchaoyi/the-options-of-inspecting-ios-10-app-with-appium-1-6-534ba166b958) while we working on a new one. 

Also, please use Appium forum for howto question.
