### ISSUE TITLE
How do you use Appium to test iOS and Android apps

### ISSUE THREAD

**Issue by GEguy** [appium/appium#7888]
Hello, can someone help me understand how to generally use Appium for app test automation? There is something I'm missing. I have downloaded Appium, Xcode and I have the eclipse IDE. I can't find any clear steps on how to actually carry out the testing, some forums talk about selenium clients, others talk about needing Ruby. Can someone assist? I have an .IPA file, what else do I need to carry out testing. Please see my setup details below. 

Setup:

MacOS Sierra 10.12.3
Xcode 8.2.1
iOS 10.2
Appium version 1.5.3

**Comment by mykola-mokhnach** [comment]
Sorry, but we don't provide support for Appium or frameworks setup here. Please use Appium forum for such type of requests.
