### ISSUE TITLE
Launching to Windows 10 mobile emulator fails with "ProxyRequestError: Could not proxy command to remote server."

### ISSUE THREAD

**Issue by wluu** [appium/appium#7889]
## The problem

Launching to Windows 10 mobile emulator fails with "ProxyRequestError: Could not proxy command to remote server."

## Environment

* Appium version (or git revision) that exhibits the issue: **1.6.3**
* Desktop OS/version used to run Appium: **Windows 10**
* Node.js version (unless using Appium.app|exe): **6.9.5**
* Mobile platform/version under test: **10.0.14393.0**
* Real device or emulator/simulator: **Mobile Emulator 10.0.14393.0 WVGA 4 inch 512MB** 

## Link to Appium logs

[Appium logs](https://gist.github.com/wluu/a47dc4c854535fed6aa3f1a5fcc3b6d2)

## Code To Reproduce Issue 

Below is the simple mocha test code I was using with `wd@1.1.3`.

```
'use strict';

const Setup = require('../helpers/setup.js');

let
	driver = null,
	webdriver = null;

before('suite setup', function () {
	this.timeout(300000);

	const setup = new Setup();

	webdriver = setup.getWd();

	driver = webdriver.promiseChainRemote({
		host: 'localhost',
		port: 4723
	});

	setup.logging(driver);

	return driver.init({
		automationName: 'Appium',
		platformName: 'Windows',
		deviceName: 'Mobile Emulator 10.0.14393.0 WVGA 4 inch 512MB',
		platformVersion: '10.0',
		app: 'com.appc.meh_51yh0rwc9c8h2!App',
		noReset: true 
	});
});

after('suite teardown', function () {
	return driver.quit();
});

describe('meh', function () {
	it('is a windows', function () {
		console.log('DONE');
	});
});
```

**Comment by wluu** [comment]
Ah, looks like there's no Windows 10 Mobile support yet: https://github.com/Microsoft/WinAppDriver/issues/38

Will close this issue.

**Comment by imurchie** [comment]
No, the Windows support is for desktop apps. Sorry.
