### ISSUE TITLE
Inspector will jam when refreshed

### ISSUE THREAD

**Issue by DSJsoul** [appium/appium#7890]
## The problem
I use appium inspector for iOS real device test on OS X.In my testing app, some pages would stuck when I click the refresh button until it times out.

## Environment
os: mac OS  10.12
appium inspector : 1.5.3
external appium package: 1.6.1
iOS : 10.0
node: v6.9.1
mobile platform: iOS(real device)

## Details

I am using appium inspector 1.5.3 and specify the appium CLI 1.6.1 for my iOS real device test.During my debugging process, I found that getting the page often timed out.And sometimes, it could be fast, sometimes it would be stuck. Also, in some specific pages, it always refresh failed.
At first, I think it is because of webview. But even I had open "ios_webkit_debug_proxy -c xxxxx:27753 -d" , it still not work.
For more details, I found these stuck pages have a characteristic, they have some numbers in pages always being changes.But I am not sure it is associated with the problem.

## Link to Appium logs

https://gist.github.com/DSJsoul/14d02ad853afdb308bce2b5070b199fa

## Code To Reproduce Issue [ Good To Have ]
Xcode console output:
`Appium[26520:1237836]Selenium Error: -1001 -Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x6080004565f0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=http://127.0.0.1:4723/wd/hub/session/a25657cf-616f-4aeb-9e20-51a1af528d79/source, NSErrorFailingURLKey=http://127.0.0.1:4723/wd/hub/session/a25657cf-616f-4aeb-9e20-51a1af528d79/source, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=http://127.0.0.1:4723/wd/hub/session/a25657cf-616f-4aeb-9e20-51a1af528d79/source, NSErrorFailingURLKey=http://127.0.0.1:4723/wd/hub/session/a25657cf-616f-4aeb-9e20-51a1af528d79/source, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.} `

Thanks for reading!

**Comment by mykola-mokhnach** [comment]
Can you try Appium 1.6.4-beta?

**Comment by DSJsoul** [comment]
@mykola-mokhnach Sorry, it is my fault. Appium 1.6.4-beta doesn't has this problem. Thank you.
