### ISSUE TITLE
[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 134

### ISSUE THREAD

**Issue by Jakester14** [appium/appium#7893]
## The problem

I installed the latest versions of the tools, appium(1.6.3), node(7.5.0), and everything else, as I started the appium server, and I got the following log below when I started the appium server and running one tests. I am also running OS 10.12.3 with the latest version of XCode, with the simulator running 10.2

[Appium] Welcome to Appium v1.6.3 (REV 70b1c6de0b889aabc86b1990c59994e6acb8d726)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"iPhone 7 Plus","udid":"B5C7EB4D-08D1-4063-B3C9-0A8214566EDD","app":"/Users/jakerushing/dice-seeker/UIScriptsTests/Dice.app","platformVersion":"10.2","platformName":"iOS","automationName":"XCUITest","bundleId":"com.dice.Dice"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"iPhone 7 Plus","udid":"B5C7EB4D-08D1-4063-B3C9-0A8214566EDD","app":"/Users/jakerushing/dice-seeker/UIScriptsTests/Dice.app","platformVersion":"10.2","platformName":"iOS","automationName":"XCUITest","bundleId":"com.dice.Dice"},{},null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   deviceName: 'iPhone 7 Plus'
[Appium]   udid: 'B5C7EB4D-08D1-4063-B3C9-0A8214566EDD'
[Appium]   app: '/Users/jakerushing/dice-seeker/UIScriptsTests/Dice.app'
[Appium]   platformVersion: '10.2'
[Appium]   platformName: 'iOS'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleId: 'com.dice.Dice'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] Session created with session id: 87a302fe-861e-45a7-bec7-8972c012c466
[debug] [XCUITest] Xcode version set to '8.2.1'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[iOSSim] Constructing iOS simulator for Xcode version 8.2.1 with udid 'B5C7EB4D-08D1-4063-B3C9-0A8214566EDD'
[XCUITest] Determining device to run tests on: udid: 'B5C7EB4D-08D1-4063-B3C9-0A8214566EDD', real device: false
[BaseDriver] Using local app '/Users/jakerushing/dice-seeker/UIScriptsTests/Dice.app'
[debug] [XCUITest] Checking whether app '/Users/jakerushing/dice-seeker/UIScriptsTests/Dice.app' is actually present
[debug] [XCUITest] App is present
[debug] [iOSLog] Starting iOS 10.2 simulator log capture
[debug] [iOSLog] System log path: /Users/jakerushing/Library/Logs/CoreSimulator/B5C7EB4D-08D1-4063-B3C9-0A8214566EDD/system.log
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid 'B5C7EB4D-08D1-4063-B3C9-0A8214566EDD' not booted. Booting up now
[debug] [iOSSim] Killing all iOS Simulators
[iOSSim] Starting simulator with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID B5C7EB4D-08D1-4063-B3C9-0A8214566EDD
[iOSSim] Simulator log at '/Users/jakerushing/Library/Logs/CoreSimulator/B5C7EB4D-08D1-4063-B3C9-0A8214566EDD/system.log'
[iOSSim] Tailing simulator logs until we encounter the string "com.apple.springboard"
[iOSSim] We will time out after 60000ms
[debug] [iOSSim] Waiting an extra 10000ms for the simulator to really finish booting
[debug] [iOSSim] Done waiting extra time for simulator
[iOSSim] Simulator booted in 12954ms
[debug] [XCUITest] Installing app '/Users/jakerushing/dice-seeker/UIScriptsTests/Dice.app' on device
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 134
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
 { Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 134
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  stdout: '\u001b[1mFetching dependencies\n',
  stderr: 'dyld: Symbol not found: __TMV6Result8AnyError\n  Referenced from: /usr/local/Cellar/carthage/0.19.1/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveSwift.framework/ReactiveSwift\n  Expected in: /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks/Result.framework/Versions/A/Result\n in /usr/local/Cellar/carthage/0.19.1/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveSwift.framework/ReactiveSwift\nScripts/bootstrap.sh: line 45: 19980 Abort trap: 6           carthage bootstrap $USE_SSH\n',
  code: 134 }
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Running iOS simulator reset flow
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [XCUITest] Cleaning simulator state.
[debug] [iOSSim] Cleaning app data files for 'Dice.app', 'com.dice.Dice'
[debug] [iOSSim] Checking whether simulator has been run before
[debug] [iOSSim] Simulator has been run before
[debug] [iOSSim] Building bundle path map
[debug] [iOSSim] Checking whether simulator has been run before
[debug] [iOSSim] Simulator has been run before
[debug] [iOSSim] Building bundle path map
[debug] [iOSSim] Deleting directory: '/Users/jakerushing/Library/Developer/CoreSimulator/Devices/B5C7EB4D-08D1-4063-B3C9-0A8214566EDD/data/Containers/Data/Application/44D3EF5F-7780-49F1-B7D5-A7D5F2D6B434'
[debug] [iOSSim] Deleting directory: '/Users/jakerushing/Library/Developer/CoreSimulator/Devices/B5C7EB4D-08D1-4063-B3C9-0A8214566EDD/data/Containers/Bundle/Application/731A5F3A-1600-496A-A158-47667ECD7173'
[debug] [iOSSim] Deleting file: '/Users/jakerushing/Library/Developer/CoreSimulator/Devices/Library/Preferences/com.dice.Dice.plist'
[debug] [iOSSim] Killing any simulator daemons for B5C7EB4D-08D1-4063-B3C9-0A8214566EDD
[iOSSim] Cleaning simulator B5C7EB4D-08D1-4063-B3C9-0A8214566EDD
[debug] [XCUITest] Resetting simulator
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 134
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[HTTP] <-- POST /wd/hub/session 500 30599 ms - 201

**Comment by Jakester14** [comment]
Update: There's something wrong with Carthage that I installed. When I type the following commands:

cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/
/bin/bash Scripts/bootstrap.sh -d

I get the following message:

Fetching dependencies
dyld: Symbol not found: __TMV6Result8AnyError
  Referenced from: /usr/local/Cellar/carthage/0.19.1/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveSwift.framework/ReactiveSwift
  Expected in: /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks/Result.framework/Versions/A/Result
 in /usr/local/Cellar/carthage/0.19.1/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks/ReactiveSwift.framework/ReactiveSwift
Scripts/bootstrap.sh: line 45: 26035 Abort trap: 6           carthage bootstrap $USE_SSH

**Comment by mykola-mokhnach** [comment]
You've found the problem. Try to find a solution in carthage issues tracker.

**Comment by kbalakumar99** [comment]
@Jakester14 

This can occur if you have an old version of /Library/Frameworks/CarthageKit.framework. If you're using the Homebrew version of Carthage, you don't need that copy of the framework, so it can be safely deleted.
