### ISSUE TITLE
Appium Hangs with 'find elements by xpath' (when no results are expected - JS+NATIVE_APP ctx)

### ISSUE THREAD

**Issue by gustavomick** [appium/appium#7894]
While working with  javascript+webView we need to switch context to native to accept location-gps authorization. After switching to NATIVE_APP context we search thru xpath like:

`let btsPromise = browser.driver.findElements( by.xpath('//android.widget.Button'));`

two different results are happening:  

1 if a button exist this promise is resolved immediately.
2 if there is no button present promise is never resolved as empty array [ ]  o rejected as error. even using wait+ispresent with timeout does not affect result. 

```
[debug] [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["f89228b3-53b8-48e3-9726-d5a2222b5d5f"]
[debug] [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
[HTTP] <-- GET /wd/hub/session/f89228b3-53b8-48e3-9726-d5a2222b5d5f/context 200 10 ms - 84
[HTTP] --> POST /wd/hub/session/f89228b3-53b8-48e3-9726-d5a2222b5d5f/elements {"using":"xpath","value":"//android.widget.Button"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//android.widget.Button","f89228b3-53b8-48e3-9726-d5a2222b5d5f"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.Button","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.Button","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.widget.Button' using 'XPATH' with the contextId: '' multiple: true
```

**Comment by jlipps** [comment]
I don't see anything wrong in the appium logs here. Are you saying that Appium stops doing anything after the log line you posted and nothing ever happens?

**Comment by gustavomick** [comment]
@jlipps yes

**Comment by jlipps** [comment]
@gustavomick even if you wait say 5 or 10 minutes? That is an extremely wasteful Xpath query, and for apps with large numbers of elements, Android is very slow. You might also try with `ignoreUnimportantViews` cap set to `true` to use the compressed layout.

**Comment by gustavomick** [comment]
@dpgraham wondering if you closed because is fixed or because is not reproducible? thankx

**Comment by dpgraham** [comment]
I was closing it due to inactivity. Are you still having issues after trying what @jlipps recommended.

**Comment by akropyva-virtru** [comment]
@gustavomick I have some issue. Appium stops to print any log info about 404 of element

**Comment by fescobar** [comment]
@akropyva-virtru  https://github.com/appium/appium/issues/9653 https://github.com/appium/appium/issues/10430

**Comment by J4-D06-0041** [comment]
still have this issue, currently using appium 1.13.0
