### ISSUE TITLE
iDeviceInstaller Hangs and test don't run further

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#7895]
## The problem

On reseting app on iOS, iDeviceInstaller hangs up intermittently. On Closing the appium server the below error is shown.

Error Log: 
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/shirodkm/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/usr/local/bin/node","commandProxyClientPath":"/usr/local/lib/node_modules/appium/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/pm/gmzrw5vj1_98pqzs7t3vsvb8tjylz3/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":true,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
...bug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
[debug] [UIAuto] Dynamic bootstrap path: /Users/shirodkm/Library/Application Support/appium/bootstrap/bootstrap-f773e55d013a5ef3.js
[debug] [UIAuto] Reusing dynamic bootstrap: /Users/shirodkm/Library/Application Support/appium/bootstrap/bootstrap-f773e55d013a5ef3.js
[debug] [iOS] Creating iDevice object with udid 9f18f3f8f092bce333b63fd1e50a36332109654f
[debug] [iOS] Running ios real device reset flow
[debug] [iOS] Full reset requested. Will try to uninstall the app 'com.eab.se'.
## [MJSONWP] Encountered internal error running command: Error: Command failed: ideviceinstaller -u 9f18f3f8f092bce333b63fd1e50a36332109654f -l 
    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

Similar ticket was added and closed.
for reference: https://github.com/appium/appium/issues/5039
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: Mac 10.11.6
* Mobile platform/version under test: 9.3.5
* Real device or emulator/simulator: Real Device iPhone 5S
* Appium CLI 
Versions installed:
ideviceinstaller HEAD-442f670_2
ios-webkit-debug-proxy 1.7 HEAD-d1ca626

## Code To Reproduce Issue [ Good To Have ]

On Trying full reset the iDeviceInstaller hangs up. 
Set capability
		iOSCapabilities.setCapability("fullReset", true);

driver.resetApp();

**Comment by yunusmete** [comment]
I think it's signing problem. Be sure your ipa file signed with development identity.

**Comment by mayureshshirodkar** [comment]
@yunusmete i use .app file and it is signed with a Development identity. 
I don't have issues with installing the app. Just Reset starts giving intermittent issues.

**Comment by mayureshshirodkar** [comment]
There is currently a ticket raised in iDeviceInstaller Github about this.
For reference:
https://github.com/libimobiledevice/ideviceinstaller/issues/22

**Comment by jlipps** [comment]
Unfortunately the old instruments driver is no longer supported. Please use Appium 1.6.4 with the xcuitest driver.
