### ISSUE TITLE
1.6.4: No_reset=false does not reset client 

### ISSUE THREAD

**Issue by amedvedjev** [appium/appium#7897]
## The problem
When i need to reset client in Simulator quickly i use "No_reset=false".
```
                    capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
                    capabilities.setCapability(MobileCapabilityType.NO_RESET, false);
```

But it does not work any more with 1.6.4 build. (last worked correctly with 1.6.3). Client still sees some of it settings.
i do not see remove plist file in logs (not sure that this is the cause but in case)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Mobile platform/version under test: iOS, xCode 8.2.1
* Real device or emulator/simulator: Simulator 10.0

[logs](https://gist.github.com/amedvedjev/9820b3c1c9c3f786fff01558379d8d49)

**Comment by mykola-mokhnach** [comment]
This information is totally not enough to investigate the issue. We need at least:

- Appium log
- Information about the client environment
- Full description of the actual and the expected resulsts

**Comment by amedvedjev** [comment]
logs just added. other updated.

**Comment by mykola-mokhnach** [comment]
Can you try to reinstall your app using standard **simctl** commands and check which data is not cleaned?

```
xcrun simctl uninstall app_bundle_id
xcrun simctl install path_to_app
```

**Comment by amedvedjev** [comment]
tried (only added udid into command) and got same affect. client sees it previous settings stored.

**Comment by mykola-mokhnach** [comment]
it would be interesting to know then where your app saves these settings (or how, I mean the source API calls), because it means even standard iOS application uninstall procedure does not kill them, which is weird.

**Comment by mykola-mokhnach** [comment]
Quick googling only shows that there are two possible ways in iOS for an app to persist local data after uninstall (and both of them should be explicitly supported in the app):

- Setting keychain items. In this case the app itself should verify the fact of first run and [clean up](http://stackoverflow.com/questions/4747404/delete-keychain-items-when-an-app-is-uninstalled) the data if needed 
- Backing up the local data to iCloud. Same story here - it's app the the app what to do with this data and should be configurable from the inside.

**Comment by amedvedjev** [comment]
yes i see in code it is "Keychain"

**Comment by mykola-mokhnach** [comment]
so we can close this as non-Appium related issue. Right?

**Comment by amedvedjev** [comment]
you mean you cannot reset correctly Keychain in simulator?

**Comment by mykola-mokhnach** [comment]
I mean the current behaviour is correct. You should either reset the whole simulator to reset keychain as well or implement correct cleanup in your app (which might be also a good fix for a potential security issue)

**Comment by amedvedjev** [comment]
there is no potential issue as far as Keychain according to apple is safest place on planet :-) and it is only available to correct user. when user migrate to new phone he can migrate also all his passwords to new device and use them.

maybe we can implement something similar: https://github.com/calabash/run_loop/issues/265 ?

**Comment by mykola-mokhnach** [comment]
restarting simulator before every test case takes precious time. I'd rather try to delete things from keychain using normal SQL requests, since it's a normal SQLLite database internally.

This is just in case you'd like to have this workaround instead of fixing the stuff in the app.

**Comment by amedvedjev** [comment]
1) regarding start - agreed, but the time of start much less then after fullReset. just like quick start.
2) your way suggest to implement it into every application as mandatory option. which does not sound like workaround but some mandatory functionality in application not in test code.

i compared driver start with fast reset on mine machine :

initial condition - simulator running before test start
 - no changes = 20sec
 - changes with close simulator and delete keychain file = 37sec

indeed quite much ...

**Comment by mykola-mokhnach** [comment]
@amedvedjev https://www.tutorialspoint.com/sqlite/sqlite_java.htm ?

**Comment by amedvedjev** [comment]
Just realized that sql also will not help cause this file getting updated once we close simulator. So all the stuff with start simulator will left.

Closing untill will get more ideas...
