### ISSUE TITLE
Appium 1.6.3, XCode 8.2.1 - Not able to search element using name attribute in xpath

### ISSUE THREAD

**Issue by abh7nav** [appium/appium#7901]
## The problem

I am trying to search an element using name attribute but it is not able to do so.  
Earlier it was working fine but after upgrading to latest WDA build from github, it has now not able to search that element.

XPATH is like below:
"//*[@name='menu_logo.png' and @visible='true' and @enabled='true']"

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Sierra
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test: ios 10
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

I am trying to search an element using name attribute but it is not able to do so.  
Earlier it was working fine but after upgrading to latest WDA build from github, it has now not able to search that element.

XPATH is like below:
"//*[@name='menu_logo.png' and @visible='true' and @enabled='true']"

You can refer to below screenshot, it shows that element is present in XML but on executing through it is not able to find it.

<img width="1269" alt="screen shot 2017-02-21 at 2 25 39 pm" src="https://cloud.githubusercontent.com/assets/16793057/23157858/cb3b72f4-f842-11e6-8447-8a9fcbf437ce.png">

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Following is being used to find element:
Wait<AppiumDriver<MobileElement>> wait = new FluentWait<AppiumDriver<MobileElement>>(
				IOSAppiumConnection.driver)
				.withTimeout(seconds, TimeUnit.SECONDS)
				.pollingEvery(1, TimeUnit.SECONDS)
				.ignoring(NoSuchElementException.class);
		WebElement foo = wait.until(new Function<WebDriver, WebElement>() {
			public WebElement apply(WebDriver driver) {
				WebElement element = null;
				int count =0; 
				try {
					element = driver.findElements(by).get(0);
					while(element==null & count < 5)
						element = driver.findElements(by).get(0);	
					EggReporter.log("Element found on the screen : " + element);
				} catch (Exception e) {
					System.out.println("Element not present in the UI");
				}
				return element;
			}
		});
		return foo;

**Comment by mykola-mokhnach** [comment]
This works as expected. WDA does not provide \@visible attribute for xpath tree anymore, because it causes unexpected freezes.

**Comment by abh7nav** [comment]
I am still using 1.6.3 where visible attribute is there. Should not it be working ? Instead of closing can you help solving that issue.

**Comment by mykola-mokhnach** [comment]
How can I help? Only Apple can if they fix XCTest bugs.

**Comment by abh7nav** [comment]
This has been working prior to upgrading WDA to latest today. There is something with APPIUM then

**Comment by mykola-mokhnach** [comment]
It has absolutely nothing to do with Appium. Appium is just a proxy between WDA and your app. And WDA itself is a proxy for XCTest. There is a bug in XCTest, which cases the client to freeze for a while while detecting visibility. That is why WDA maintainers decided to remove the attribute from the tree at all. And Appium just proxies what WDA produces for it.

**Comment by abh7nav** [comment]
One quick question. What can I use to check for visibility of element?

**Comment by mykola-mokhnach** [comment]
I have already replied in https://github.com/appium/appium/issues/7900 ...
