### ISSUE TITLE
ios Swipe does not work Appium 1.6.4-beta 

### ISSUE THREAD

**Issue by tmytlovych** [appium/appium#7902]
## The problem

Cannon swipe in iOS native app with Appium 1.6.4-beta  using python.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: OS X El Capitan
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: real device, iPad Air 2
* SELENIUM : selenium (3.0.1)

## Details
I was trying following: 
window_size = self.driver.get_window_size()
 self.driver.swipe(window_size['width'] * 0.8, window_size['height'] * 0.8, window_size['width'] * 0.8, -window_size['height'] * 0.7)
With appium 1.6.3 it works, but now I have an error: WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint

Then  I have tried
self.driver.execute_script("mobile: scroll", {"direction": "down"})
self.driver.execute_script("mobile: swipe", {"direction": "down"})

Result is the same:
WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint:

## Link to Appium logs

https://gist.github.com/tmytlovych/1ab02c4ea104602e1ba8f16eb1b65ff9

**Comment by mykola-mokhnach** [comment]
Can you make sure the WDA source at /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent is updated to the recent master?

**Comment by tmytlovych** [comment]
I have updated to Sierra reinstalled the appium and rebuild WebdriverAgent and it helps.

**Comment by vikramvi** [comment]
@triager please close per last comment
