### ISSUE TITLE
Can't launch application on Simulator

### ISSUE THREAD

**Issue by razelkayamdev** [appium/appium#7904]
## The problem

Trying to launch ```arc``` tool, while Appium server runs locally, and the application does not install, and the arc quits.

## Environment

* Appium version: 1.6.3
* Desktop OS/version used to run Appium: macOS Sierra (10.12.3)
* Node.js version: v6.9.5
* Mobile platform/version under test: iOS
* simulator: iPhone 7 10.2
* Appium CLI

## Details

1. I've created an ```appium.txt``` file with the following contents:

```
[caps]
platformName = "ios"
app = "/Users/username/Desktop/Appium/myApp.app"
```

2. Run the Appium via terminal with the following command:

```sudo appium --debug-log-spacing --platform-version "10.2" --platform-name "iOS" --device-name "iPhone 7" --automation-name XCUITest```

3. run the ```arc``` command in the location of the ```appium.txt``` file location.

## Link to Appium logs

Links to the log files, both for ```arc``` command, and the Appium from terminal.
https://gist.github.com/razelkayamdev/231c2103308e2bdbcdfba51d7520b655

**Comment by mykola-mokhnach** [comment]
It looks like the iOS Simulator is broken on your system. Are you able to execute it manually and install the app there?

**Comment by razelkayamdev** [comment]
@mykola-mokhnach - thanks for responding!

I'm able to launch the application directly via Xcode.
And when executing the following commands:

```
$ xcrun simctl install booted /Users/username/Desktop/MyApp.app 
$ xcrun simctl launch booted com.bundleIdentifier
```

I'm able to install and launch the application (only when the simulator is already open).

**Comment by mykola-mokhnach** [comment]
strange. is it the same simulator you want to use in your automated test (iPhone 7 @ 10.2)? If yes, can you try to delete and then create it again in devices manager?

**Comment by razelkayamdev** [comment]
Yes, that's the simulator I'm using.
I'll delete the simulator, and let you know how it worked. 
If fail - I'll attach the new logs.
Thanks.

**Comment by razelkayamdev** [comment]
@mykola-mokhnach, I've removed all of my Simulators, reinstalled them, and the same results. 
As well, deleted Xcode, reinstalled it, with the same results.

I did noticed that when I changed the params for launching Appium to use ```iPhone 6``` instead of ```iPhone 7```, the ```iPhone SE``` Simulator opened.
Perhaps this is a lead?

**Comment by mykola-mokhnach** [comment]
Can you try Appium 1.6.4-beta? Also, it is recommended to pass capabilities in code rather than as command line parameters.

**Comment by razelkayamdev** [comment]
I'll give 1.6.4-beta a try.

>   it is recommended to pass capabilities in code rather than as command line parameters.

Can you point me to a document which explains how to do so?

**Comment by mykola-mokhnach** [comment]
[Here](http://appium.io/slate/en/master/?java#mobile-safari-on-simulator) is an example of passing capabilities. And [here](https://github.com/appium/appium-xcuitest-driver#usage) you can find the list of XCUITest driver capabilities.

**Comment by razelkayamdev** [comment]
Using Appium@1.6.4-beta resulted in a crash. 
Logs are here: https://gist.github.com/razelkayamdev/c5dcc9a4c3605f385032e55a919736d8

Trying to pass capabilities as you suggested.

**Comment by mykola-mokhnach** [comment]
Is it possible to execute the test on some other Mac machine? Just to make sure it has nothing to do with Simulator/Xcode setup

**Comment by razelkayamdev** [comment]
I'll try it, but probably will take me a few days.

**Comment by jlipps** [comment]
Also I'm pretty sure that Appium should never be run under sudo; if for some reason it must be on your system, that typically indicates that it wasn't installed correctly.
