### ISSUE TITLE
Appium GUI inspector

### ISSUE THREAD

**Issue by qakapil** [appium/appium#7905]
Hi,

Is there a plan for Appium 1.6 gui tool to recognize XCUITest elements ? At the moment I have to fetch page_source of the screen to get the DOM.
Inspector provided by WDA doesn't seem to be working.

**Comment by kcinman11358** [comment]
There is. You can check out the progress here:
https://github.com/appium/appium-desktop

For now, try this guide
https://medium.com/@chenchaoyi/the-options-of-inspecting-ios-10-app-with-appium-1-6-534ba166b958#.bx7a4rt7i

**Comment by mykola-mokhnach** [comment]
Yes, the team is currently working on a new desktop client. Check https://github.com/appium/appium-desktop. We've, actually, just released beta version of it.

**Comment by vikramvi** [comment]
@triager please close as this is not bug
