### ISSUE TITLE
Unwanted pop up when opening google drive with appium 1.6.3 but it works fine with AppiumForWindows.exe

### ISSUE THREAD

**Issue by AmitVerma4HP** [appium/appium#7906]
## The problem

I am facing an issue while opening google drive via latest released appium v1.6.3 where it shows product welcome msg each time app opens
In apps works just fine if i use appiumForWindows.exe (GUI one) - v1.4.16.1

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16.1
* Desktop OS/version used to run Appium: Win7 x64
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test: Nexus 5 (6.0) and Nexus 5(6.0)
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe:
[appium_v1.6.3.txt](https://github.com/appium/appium/files/791969/appium_v1.6.3.txt)
![capture](https://cloud.githubusercontent.com/assets/22062978/23192579/19e4d704-f859-11e6-9fee-674b3c8fbbae.PNG)

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
Attached appium log when it does not work and shows welcome pop up

## Code To Reproduce Issue [ Good To Have ] - You can just set any basic 
This issue can be reproduced just by opening google drive via below pkg and activity for Android 6.0 device such as Nexus6 , Nexus 5x , Nexus 5 with appium version v1.6.3
 capabilities.setCapability("appPackage", "com.google.android.apps.docs");
 capabilities.setCapability("appActivity", "com.google.android.apps.docs.app.NewMainProxyActivity");

**Comment by jlipps** [comment]
If you don't want the state to be reset each time, use the `noReset` capability set to `true`.
