### ISSUE TITLE
Please Help, ASAP : RoutingHTTPServer/RoutingHTTPServer.h' file not found

### ISSUE THREAD

**Issue by NarenGandhi** [appium/appium#7907]
I've installed appium 1.6.3. It starts normally. However, when i try to executed my script to launch the app on a real device, it fails during launching of webDriverAgent. I suspect, it has something to do with bootstrap script. I've pasted the log, below. Could someone help me ASAP ? It's really important for me to get this resolved, immediately. 

LOG 

[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","deviceName":"ios-nativeapp-mobile","newCommandTimeout":300}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","deviceName":"ios-nativeapp-mobile","newCommandTimeout":300},null,null,null,null]
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'ios-nativeapp-mobile'
[Appium]   newCommandTimeout: 300
[Appium]   automationName: 'XCUITest'
[Appium]   app: '/Users/gandhin/Downloads/PAYLOAD_3/Tylecom.app'
[Appium]   udid: 'e26e54ec522e7a5797c0d2328f0da5dd45b38ggh'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] Session created with session id: a401c49d-b590-4245-a985-6bd754df9946
[debug] [XCUITest] Xcode version set to '8.2'
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [XCUITest] Available devices: e26e54ec522e7a5797c0d2328f0da5dd45b38ggh
[debug] [XCUITest] Creating iDevice object with udid e26e54ec522e7a5797c0d2328f0da5dd45b38ggh
[XCUITest] Determining device to run tests on: udid: 'e26e54ec522e7a5797c0d2328f0da5dd45b38ggh', real device: true
[BaseDriver] Using local app '/Users/gandhin/Downloads/PAYLOAD_3/Tylecom.app'
[debug] [XCUITest] Checking whether app '/Users/gandhin/Downloads/PAYLOAD_3/Tylecom.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/Users/gandhin/Downloads/PAYLOAD_3/Tylecom.app': 'com.vzw.myverizon.Tylecom.enterprise'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/Users/gandhin/Documents/appium-1.6.3/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/gandhin/Documents/appium-1.6.3/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /Users/gandhin/Documents/appium-1.6.3/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e26e54ec522e7a5797c0d2328f0da5dd45b38ggh -configuration Debug' in directory '/Users/gandhin/Documents/appium-1.6.3/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Waiting for WebDriverAgent to start on device
[debug] [XCUITest] Log file for xcodebuild test: /Users/gandhin/Library/Developer/Xcode/DerivedData/WebDriverAgent-cjliprzskqpnjxgamyanmwimtdsg/Logs/Test/142A73C7-29EB-46CF-95CC-09A3DDD6134D/Session-WebDriverAgentRunner-2017-02-21_211643-QjOgRM.log
[Xcode] 2017-02-21 21:16:44.612 xcodebuild[10778:112220] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/gandhin/Library/Developer/Xcode/DerivedData/WebDriverAgent-cjliprzskqpnjxgamyanmwimtdsg/Logs/Test/142A73C7-29EB-46CF-95CC-09A3DDD6134D/Session-WebDriverAgentRunner-2017-02-21_211643-QjOgRM.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/gandhin/Library/Developer/Xcode/DerivedData/WebDriverAgent-cjliprzskqpnjxgamyanmwimtdsg/Logs/Test/142A73C7-29EB-46CF-95CC-09A3DDD6134D/Session-WebDriverAgentRunner-2017-02-21_211643-QjOgRM.log}

[Xcode] 
Testing failed:

[Xcode] 	'RoutingHTTPServer/RoutingHTTPServer.h' file not found
	Unable to execute command: posix_spawn failed: Permission denied
** TEST FAILED **

The following build commands failed:
	CompileC /Users/gandhin/Library/Developer/Xcode/DerivedData/WebDriverAgent-cjliprzskqpnjxgamyanmwimtdsg/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBHTTPOverUSBServer.o WebDriverAgentLib/Routing/FBHTTPOverUSBServer.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/gandhin/Library/Developer/Xcode/DerivedData/WebDriverAgent-cjliprzskqpnjxgamyanmwimtdsg/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/XCUIApplication+FBHelpers.o WebDriverAgentLib/Categories/XCUIApplication+FBHelpers.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

[XCUITest] xcodebuild exited with code '65' and signal 'null'

**Comment by mykola-mokhnach** [comment]
it looks like one has installed Appium with root permissions, which is wrong. Make sure your local user has correct R/W permissions to the folder, where Appium binaries are installed and reinstall Appium without _sudo_.

**Comment by pavanbachu0604** [comment]
Did you execute /bin/bash Scripts/bootStrap.sh -d ?
