### ISSUE TITLE
Why Appium use es6 nor nodejs?

### ISSUE THREAD

**Issue by 0x88l** [appium/appium#7908]
I try to read the code of Appium. Some doubts I did not figure out.
question 1:  The version before 1.4.16 was use node why did Appium use es6  now? What is it advantage?
question 2: Why is it done by GULP compiled into nodejs without using nodejs directly?

**Comment by jlipps** [comment]
Some motivations for the appium rewrite are given in a talk: https://www.youtube.com/watch?v=WrWX-K1f57E
