### ISSUE TITLE
sessionNotFoundException when create session/quit driver for each test method. 

### ISSUE THREAD

**Issue by vkvikaskmr** [appium/appium#7910]
## The problem

For a test scenario I need to create a driver session and quit driver for every test method as I want a clean state for each of the test methods. For that I am creating a new driver instance in the @BeforeMethod and quitting the driver in @AfterMethod. But only the first test method runs and subsequent tests fail after throwing SessionNotFoundException.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: Macosx 10.12
* Node.js version (unless using Appium.app|exe): v7.0.0
* Mobile platform/version under test: iOS 9.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

## Link to Appium logs

https://gist.github.com/vkvikaskmr/b6b0ff43cf025a08628af9621cb7ccf2

**Comment by mykola-mokhnach** [comment]
Try Appium 1.6.4-beta

**Comment by vkvikaskmr** [comment]
Is that a known issue that has been fixed recently?

**Comment by imurchie** [comment]
It is not a known issue, but the startup flow has significantly changed.

**Comment by vkvikaskmr** [comment]
@imurchie do you have any suggested workaround for this issue?

**Comment by vkvikaskmr** [comment]
Hey! sorry for the noise looks like a problem in my setup. Please ignore this.
