### ISSUE TITLE
Android : Appium 1.6.3 Clears the app data every time when driver.launchApp() is called

### ISSUE THREAD

**Issue by vinodbenure** [appium/appium#7911]
When we use driver.launchApp() it clears the app data every time. Since, all the data/files that created and stored by the app are getting cleared before next test starts.

## Environment

* Appium Version 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: Windows 7
* Node.js version (unless using Appium.app|exe): 6.9.4
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Java Client Version : 3.3.0

## Details

Example : If you login to an app which internally creates some local files and if you clear the appa data, then it will delete all the local files and the will again prompt to log in by displaying the initial page.

This is happening because of the **adb shell pm clear**  command which has been added in 1.6.3 release as you can see in the below logs.

##Appium logs
```
[debug] [ADB] Running 'C:\Users\Vinod\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","079a1ea4d037eeb7","shell","am","force-stop","PACKAGENAME"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
**[debug] [ADB] Running 'C:\Users\Vinod\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","079a1ea4d037eeb7","shell","pm","clear","PACKAGENAME"]**
[debug] [ADB] Device API level: 23
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\Vinod\AndroidSDK\platform-tools\adb.exe' with args: ["-P",5037,"-s","079a1ea4d037eeb7","shell","am","start","-W","-n","PACKAGENAME/.ui.SplashActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
```

## Code To Reproduce Issue [ Good To Have ]

`driver.launchApp();`

**Comment by imurchie** [comment]
Without the full logs there isn't much we can do, as the context of this is unclear.

**Comment by AmitVerma4HP** [comment]
This looks similar to my case #7906 
where i get welcome screen each time google drive opens (may be because app data is being cleared each time app is opened)

**Comment by draganglumac** [comment]
Try setting the noReset capability to true before launching the app. It seems to be set to reset data by default. Or did I misunderstand the issue?

**Comment by AmitVerma4HP** [comment]
@draganglumac ..Thanks.
--no-reset flag works for me so I am able to execute my all my automated tests (without getting app data clearing up).

**Comment by vikramvi** [comment]
Per this https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md, the `--no-reset flag is deprecated`. correct way of using it through capabilities `noReset`
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md

@triager please close
