### ISSUE TITLE
Using Appium 1.6.4-beta Gui inspector shows blank columns

### ISSUE THREAD

**Issue by senevit4** [appium/appium#7912]
Using Appium 1.6.4-beta Gui inspector shows blank columns in inspector gui (see the screenshot), element searching in inspector works well.
![screen shot 2017-02-22 at 13 42 41](https://cloud.githubusercontent.com/assets/10827147/23208113/d5a2ac5e-f904-11e6-80f2-b960e2d44184.png)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: 10.11.6
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iOS 10.2.1
* Real device or emulator/simulator: Real device iPhone 6s
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

Log that happens after Refresh button is pressed:
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.4-beta","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 10 ms - 88 
[HTTP] --> GET /wd/hub/session/f99372a0-a317-43b7-af77-9c753e75a820/source {}
[debug] [MJSONWP] Calling AppiumDriver.getPageSource() with args: ["f99372a0-a317-43b7-af77-9c753e75a820"]
[debug] [XCUITest] Executing command 'getPageSource'
[debug] [JSONWP Proxy] Proxying [GET /source/xml] to [GET http://localhost:8100/session/F5409C0C-E212-43EA-924F-A727E48996A3/source/xml] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"tree\" : \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<XCUIElementTypeApplication type=\\\"XCUIElementTypeApplication\\\" name=\\\"Circuit\\\" label=\\\"Circuit\\\" enabled=\\\"true\\\" x=\\\"0\\\" y=\\\"0\\\" width=\\\"414\\\" height=\\\"736\\\">\\n  <XCUIElementTypeWindow type=\\\"XCUIElementTypeWindow\\\" enabled=\\\"true\\\" x=\\\"0\\\" y=\\\"0\\\" width=\\\"414\\\" height=\\\"736\\\">\\n    <XCUIElementTypeOther type=\\\"XCUIElementTypeOther\\\" enabled=\\\"true\\\" x=\\\"0\\\" y=\\\"0\\\" width=\\\"414\\\" height=\\\"736\\\">\\n      <XCUIElementTypeOther type=\\\"XCUIElementTypeOther\\\" enabled=\\\"true\\\" x=\\\"0\\\" y=\\\"0\\\" width=\\\"414\\\" height=\\\"736\\\">\\n        <XCUIElementTypeOther type=\\\"XCUIElementTypeOther\\\" enabled=\\\"true\\\" x=\\\"0\\\" y=\\\"0\\\" width=\\\"414\\\" height=\\\"736\\\">\\n          <XCUIElementTypeOther type=\\\"XCUIElementTypeOther\\\" enabled=\\\"true\\\" x=\\\"0\\\" y=\\\"0\\\" width=\\\"414\\\" height=\\\"736\\\">...
[debug] [MJSONWP] Responding to client with driver.getPageSource() result: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><AppiumAUT><XCUIElementTypeApplication type=\"XCUIElementTypeApplication\" name=\"Circuit\" label=\"Circuit\" enabled=\"true\" x=\"0\" y=\"0\" width=\"414\" height=\"736\">\n  <XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" x=\"0\" y=\"0\" width=\"414\" height=\"736\">\n    <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" x=\"0\" y=\"0\" width=\"414\" height=\"736\">\n      <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" x=\"0\" y=\"0\" width=\"414\" height=\"736\">\n        <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" x=\"0\" y=\"0\" width=\"414\" height=\"736\">\n          <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" x=\"0\" y=\"0\" width=\"414\" height=\"736\">\n            <XCUIElementTypeOther type=\"XCUIElementTypeOther\" enabled=\"true\" x=\"0\" y=\"0\" width=\"414\" height=\"736\">\n              <XCUIElementTypeOther type=\"XCUIElementTypeOther\...
[HTTP] <-- GET /wd/hub/session/f99372a0-a317-43b7-af77-9c753e75a820/source 200 1133 ms - 85028 
[HTTP] --> GET /wd/hub/session/f99372a0-a317-43b7-af77-9c753e75a820/orientation {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/f99372a0-a317-43b7-af77-9c753e75a820/orientation] to [GET http://localhost:8100/session/F5409C0C-E212-43EA-924F-A727E48996A3/orientation] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"PORTRAIT\",\n  \"sessionId\" : \"F5409C0C-E212-43EA-924F-A727E48996A3\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId F5409C0C-E212-43EA-924F-A727E48996A3 with f99372a0-a317-43b7-af77-9c753e75a820
[HTTP] <-- GET /wd/hub/session/f99372a0-a317-43b7-af77-9c753e75a820/orientation 200 1005 ms - 82 
[HTTP] --> GET /wd/hub/session/f99372a0-a317-43b7-af77-9c753e75a820/screenshot {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/f99372a0-a317-43b7-af77-9c753e75a820/screenshot] to [GET http://localhost:8100/session/F5409C0C-E212-43EA-924F-A727E48996A3/screenshot] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"iVBORw0KGgoAAAANSUhEUgAABNoAAAigCAYAAADpkk+ZAAAAAXNSR0IArs4c6QAA\\r\\nABxpRE9UAAAAAgAAAAAAAARQAAAAKAAABFAAAARQAAMbsMKYNgQAAEAASURBVHgB\\r\\n7J1nn9tGlnf3O+yzM7aVOucc1MrByjnLsmVbsiVbWd2SWtJsnNmdjbN5Z+OnxXP\\/\\r\\nBVYLLAIkQIJskn1e4AeQRKhwCDZO31v1Bx8\\/fox2yvKrX\\/0q6sSyU9qTeu6c7w59\\r\\nTV\\/DAAzAAAzAAAzAAAzAAAzAQHkMdMJNcI3OOKCwnf9gJ31Rwsq36\\/VOalPqWt6N\\r\\nlrakLWEABmAABmAABmAABmAABmBgZzDQLh\\/BebdHriXbHdHWhig3bow748ZIP9PP\\r\\nMAADMAADMAADMAADMAADMAADzTCQFDNsb78cK7MPEG2Ith2TOtzMzY9j+NGEARiA\\r\\nARiAARiAARiAARiAARgom4EyxQ7n6i5Rh2hDtCHadtA4hWX\\/OHA+\\/uCAARiAARiA\\r\\nARiAARiAARiAgeIMIMe6S46V2R+INkQbog3RBgMwAAMwAAMwAAMwAAMwAAMwAAMd\\r\\nZKBMscO5ukvaIdoQbdxMO3gz5T89xf\\/TQ5vRZjAAAzAAAzAAAzAAAzAAA\\/3GAHKs\\r\\nu+RYmf2BaEO0IdoQbTAAAzAAAzAAAzAAAzAAAzAAAzDQQQbKFDucq7ukHaIN0cbN\\r\\ntIM30377Lwz14T+LMAADMAADMAADMAADMAADMFCcAeRYd8mxMvsD0YZoQ7Qh2mAA\\r\\nBmAABmAABmAABmAABmAABmCggwyUKXY4V3dJO0Qboo2baQdvpvynp\\/h\\/emgz2gwG\\r\\nYAAGYAAGYAAGYAAGYKDfGECOdZccK7M\\/EG2INkQbog0GYAAGYAAGYAAGYAAGYAAG\...
[JSONWP Proxy] Replacing sessionId F5409C0C-E212-43EA-924F-A727E48996A3 with f99372a0-a317-43b7-af77-9c753e75a820
[HTTP] <-- GET /wd/hub/session/f99372a0-a317-43b7-af77-9c753e75a820/screenshot 200 156 ms - 369930 
[HTTP] --> GET /wd/hub/session/f99372a0-a317-43b7-af77-9c753e75a820/contexts {}
[debug] [MJSONWP] Calling AppiumDriver.getContexts() with args: ["f99372a0-a317-43b7-af77-9c753e75a820"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false 
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible
[debug] [iOS] No web frames found.
[debug] [MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/f99372a0-a317-43b7-af77-9c753e75a820/contexts 200 11 ms - 86 
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.4-beta","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 14 ms - 88 
[HTTP] --> GET /wd/hub/status {}
////////////////////////////////////////////////END OF THE LOG

**Comment by senevit4** [comment]
But if to turn on 'Show invisible', everything works.
![screen shot 2017-02-22 at 15 29 40](https://cloud.githubusercontent.com/assets/10827147/23211558/c92edd3a-f913-11e6-8654-fae7a1e90b78.png)

**Comment by slipy12** [comment]
FYI: I have the same behaviour with the 1.5.3 GUI

**Comment by senevit4** [comment]
This is a screen shot from gui 1.5.3 but cli appium 1.6.4-beta is used as server (like here https://medium.com/@chenchaoyi/the-options-of-inspecting-ios-10-app-with-appium-1-6-534ba166b958#.y1ebfmr5b). There is also a lot of rubbish shown because of that.

**Comment by pavanbachu0604** [comment]
Where can i download the Appium 1.6.4 GUI ?

**Comment by slipy12** [comment]
Is in development, not published, but will be a beta asap

**Comment by senevit4** [comment]
But it possible to use inspector from gui 1.5.3 on iOS 10, see the instructions here: https://medium.com/@chenchaoyi/the-options-of-inspecting-ios-10-app-with-appium-1-6-534ba166b958#.y1ebfmr5b .

**Comment by lewbloch** [comment]
I see this happening using Appium server 1.6.3.

**Comment by vikramvi** [comment]
@senevit4 @lewbloch please use https://github.com/appium/appium-desktop instead of earlier version. 

In case issue still reproducible, open issue in above repo

@triager please close
