### ISSUE TITLE
Xcode build is failing because of codesign

### ISSUE THREAD

**Issue by thejuskrishna** [appium/appium#7913]
## The problem
Appium tries to run xcodebuild command but it fails because of a codesigning issue.

* Appium version (or git revision) that exhibits the issue: v1.6.3
* Desktop OS/version used to run Appium: MAC Sierra
* Node.js version (unless using Appium.app|exe): v6.6.0
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: Real XCUITest

## Details

I have been trying to run on a real device and it fails in appium while running xcodebuild.
It shows that codesigning has failed:

The following build commands failed:
	CodeSign /Users/pbox/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/Frameworks/Peertalk.framework
	CodeSign /Users/pbox/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentLib.framework/Frameworks/RoutingHTTPServer.framework
	CodeSign /Users/pbox/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/IntegrationApp.app

Tried to run from XCode UI to build and everything worked but from Appium it fails.

## Link to Appium logs

https://gist.github.com/thejuskrishna/509bb70ad245c68f6914c2b4c8ca8cc1

**Comment by mykola-mokhnach** [comment]
Do you follow [real device setup procedure ](https://github.com/appium/appium-xcuitest-driver#usage)?

**Comment by thejuskrishna** [comment]
Yes, I do follow that. Except for the security keychain steps. On import security keychain, I was getting an error. Added the keys directly to login.keychain and System.keychain because of the error.

**Comment by pavanbachu0604** [comment]
I feel its because of lockdown issue, try sudo chmod -R 777 /var/db/lockdown/ , later try idevicepair pair . Try running your script
