### ISSUE TITLE
Partial swipe left is not working on iOS simulator

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#7914]
## The problem

Please refer to issue https://github.com/appium/java-client/issues/580

1. I've an element in form of row ( XCUIElementTypeTable[1]/XCUIElementTypeCell[1] ) on which I need to swipe partial left
2. This will unhide button on right side of the row ( XCUIElementTypeTable[1]/XCUIElementTypeCell[1]/XCUIElementTypeButton[1] )
3. I have tried all options possible but couldn't get this working
4. It always results in normal swipe and next screen gets loaded
5. The behaviour is similar to Mail app in iOS.
6. I think chaining of events are not happening properly in this case.
Instead of waiting for next chain event Press -> MoveTo -> Release -> Perform

## Environment

- java client build version or git revision if you use some shapshot: 5.0.0-BETA3
- Appium server version or git revision if you use some shapshot: 1.6.4. beta
- Desktop OS/version used to run Appium if necessary: Mac 10.11.6
- Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: v7.2.1
- Mobile platform/version under test: 10.2
- Real device or emulator/simulator: iOS Simulator

## Details

Already mentioned under problem statement.

## Link to Appium logs

https://gist.github.com/vikramvi/220ba19708a8f1ec0bbc8d906072f209

## Code To Reproduce Issue [ Good To Have ]

I tried techniques mentioned in 
https://discuss.appium.io/t/left-or-right-swipe-not-working-in-appium-for-android-app/14515
https://discuss.appium.io/t/partial-swipe-left-on-ios-simulator-10-x-not-working/14948

I didn't yet find any open source project which has similar control. Please let me know if you know any so that I can share the detailed code.

**Comment by vikramvi** [comment]
@mykola-mokhnach  please review per https://github.com/appium/java-client/issues/580#issuecomment-281712894

**Comment by mykola-mokhnach** [comment]
did you try to invoke "mobile: swipe" instead of using _TouchAction_?

**Comment by vikramvi** [comment]
Nop https://appium.github.io/java-client/io/appium/java_client/ios/IOSDriver.html#swipe-int-int-int-int-int- , this says swipe method is deprecated.

can you please clarify how to use that method in this situation ?

**Comment by vikramvi** [comment]
@mykola-mokhnach can you please clarify as per above comment ?

**Comment by vikramvi** [comment]
I tried below but still it's not working @mykola-mokhnach  @imurchie 

`                	    JavascriptExecutor js = (JavascriptExecutor) driver;
                	    HashMap<String, String> swipeObject = new HashMap<String, String>();
                	    swipeObject.put("direction", "left");
                	    swipeObject.put("startX", "250");
                	    swipeObject.put("startY", "147");
                	    swipeObject.put("endX", "200");
                	    swipeObject.put("endY", "147");
                	    swipeObject.put("duration", "1.8");
                	    js.executeScript("mobile: swipe", swipeObject);`

`[HTTP] --> POST /wd/hub/session/35b08508-5ce6-4d83-adba-bcf897f316af/execute {"script":"mobile: swipe","args":[{"duration":"1.8","endY":"147","endX":"200","startY":"147","startX":"250","direction":"left"}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: swipe",[{"duration":"1.8","endY":"147","endX":"200","startY":"147","startX":"250","direction":"left"}],"35b08508-5ce6-4d83-adba-bcf897f316af"]
[debug] [XCUITest] Executing command 'execute'
[debug] [BaseDriver] Waiting up to 1000 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/33E71E7C-965E-4F42-A210-8C61954D9ECF/element] with body: {"using":"class name","value":"XCUIElementTypeApplication"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"44E78537-0BD2-47CF-8BBC-050B7E1A7011","type":"XCUIElementTypeApplication","label":"Crew"},"sessionId":"33E71E7C-965E-4F42-A210-8C61954D9ECF","status":0}
[debug] [JSONWP Proxy] Proxying [POST /wda/element/44E78537-0BD2-47CF-8BBC-050B7E1A7011/swipe] to [POST http://localhost:8100/session/33E71E7C-965E-4F42-A210-8C61954D9ECF/wda/element/44E78537-0BD2-47CF-8BBC-050B7E1A7011/swipe] with body: {"direction":"left"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"33E71E7C-965E-4F42-A210-8C61954D9ECF","status":0}
[debug] [MJSONWP] Responding to client with driver.execute() result: null
[HTTP] <-- POST /wd/hub/session/35b08508-5ce6-4d83-adba-bcf897f316af/execute 200 700 ms - 76`

There is little info for swipe action https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md

**Comment by vikramvi** [comment]
@jlipps can you please review

**Comment by jlipps** [comment]
@vikramvi you need to use the latest appium 1.6.4 for this to work.
