### ISSUE TITLE
sign and release 1.0 beta of appium desktop

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7915]
Get this out into the hands of beta testers!

**Comment by senevit4** [comment]
@jlipps , will 1.0 beta of appium desktop include a element inspector for iOS(like in 1.5.3 gui) or not?

**Comment by dpgraham** [comment]
@senevit4 It will yes. You can try the beta release right now https://github.com/appium/appium-desktop/releases and give it a try. If you're using Mac you'll have to allow your os to use apps from unidentified developers.
