### ISSUE TITLE
After starting React-Native app programatically, Appium commands hang.

### ISSUE THREAD

**Issue by c-Brooks** [appium/appium#7917]
## The problem

I have a React Native application that I am testing with Mocha.  The tests I write for iOS work fine, but when I run my Android tests, all of my locators just hang, even just printing out page source. 

The same thing happens when I run `arc` HOWEVER when I click Home and start the app manually on the emulator, arc works perfectly (in fact, I don't even need to start the app).  `driver.reset` and `driver.start` have the same problem.  It's kind of like driver's start commands don't focus the app in the same way that manually starting it does.

## Environment

* Appium version:  1.6.3
* Node.js version: 7.3.0
* Mobile platform/version under test:
Emulator: Android 7.1.1 (API Level 25), CPU: Google APIs Intel Atom (x86)

`appium.txt`:
```
[caps]
  platformName = 'Android'
  deviceName   = 'testDevice'
  appPackage   = '_domain.package_'
  appActivity  = '.MainActivity'

[appium_lib]
  sauce_username   = false
  sauce_access_key = false
```

* React Native version:  0.38.0

## Link to Appium logs

Here!
https://gist.github.com/c-Brooks/6094175affc70233b3911a7cecbe8f5e

## Code To Reproduce Issue [ Good To Have ]

Not really too sure which code is relevant, but happy to supply if you need.

Thanks a lot guys!

**Comment by jlipps** [comment]
Sorry @c-Brooks I couldn't find an issue in the logs you uploaded. What does your client code look like? And have you tried with Appium 1.6.4, possibly also using the UiAutomator2 driver?
