### ISSUE TITLE
Connect Hardware Keyboard Option in iOS sim doesn't work in 1.6.4 beta

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/appium#7918]
## The problem

With appium 1.6.4-beta and XCUITest driver 2.9 and 2.10, the Connect Hardware Keyboard option in the iOS simulator is always off, even if you go the menu to enable it.

This makes manually typing into a simulator impossible, which is quite frustrating.

To Reproduce:
`npm uninstall -g appium`
`npm install -g appium@beta`
`cd path/to/your/appium.txt`
`arc`

After the simulator completes launching, check Hardware -> Keyboard -> Connect Hardware Keyboard. It will be unchecked. Try enabling it, then check the menu again. It will still be disabled.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: macOS 10.12
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test: iOS 
* Real device or emulator/simulator: sim
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
The option to disable hardware keyboard has been included into default Simulator deliberately because this helps to avoid a bunch of unexpected problems with automated input. What is the reason to still use manual input there?

**Comment by VivaLosDoyers** [comment]
Many of us writing tests in Ruby use the Ruby Console. That works by launching the AUT in the simulator, and then accepting input of the user. 

In my case, I'm often targeting parts of my application that are nowhere near the initial state the app is in. Typing is required, and it's just plain silly to have to click keys on the simulator keyboard.

With all of that said, if you want to disable the keyboard by default, then by all means. But I should still be able to turn it back in whenever I please, and that I cannot do.

**Comment by mykola-mokhnach** [comment]
We can make this option configurable via capabilities

**Comment by VivaLosDoyers** [comment]
That would be nice!

**Comment by vikramvi** [comment]
@VivaLosDoyers can you please clarify how did you get 2 versions of XCUITest driver 2.9 and 2.10 with appium 1.6.4-beta  ?

I've installed appium 1.6.4-beta  and npm list -g shows appium-xcuitest-driver@2.9.0

**Comment by VivaLosDoyers** [comment]
I simply uninstalled and reinstalled, and it was there.

**Comment by VivaLosDoyers** [comment]
Also I'd like to reiterate that this isn't simply a matter of whether or not hardware keyboard is enabled when the simulator is launched. I also cannot enable it at all when appium launches it.

I think that should be fixed.

**Comment by mykola-mokhnach** [comment]
The PR has just been merged. Please reinstall Appium beta and set **connectHardwareKeyboard** capability to _true_
