### ISSUE TITLE
After use appium, No displayed Chrome Access Pop-up

### ISSUE THREAD

**Issue by dmlch123** [appium/appium#7919]
## The problem

After proceeding with automation, access pop-up No displayed in the chrome browser.
How do you solve this problem?

## Environment

node - v 6.9.1
npm - v3.10.8
appium - 1.6.1

Desktop OS/version
- windows 7 Enterprise K

all real devices

## Details

[URL]
https://m.map.naver.com
This pop-up is Location Information Access pop-up

![2017-02-23 10 27 44](https://cloud.githubusercontent.com/assets/17824741/23240820/e43c84e8-f9b2-11e6-93f4-1fe7b8d864f8.PNG)

**Comment by jlipps** [comment]
I don't understand the issue reported here. If it's still happening, please reopen a new issue with logs or a more detailed explanation of what the expected and actual behaviors are.
