### ISSUE TITLE
SetLocation Throws WebDriverException: Method has not yet been implemented

### ISSUE THREAD

**Issue by cyildirim** [appium/appium#7920]
## The problem

We are using setLocation method to set device location. But it throws  WebDriverException: Method has not yet been implemented. I tried cast to (AppiumDriver) to (IosDriver and MobileDriver) but it threw same exception again.

 

## Environment

* Appium version : 1.6.3
* Desktop OS/version used to run Appium: MacOS 10.11.6
* Node.js version (unless using Appium.app|exe): v6.9.1
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: simulator
* Appium java client: 4.1.2 

## Link to Appium logs

https://gist.github.com/cyildirim/aafb4aea1be32ad1e878bfa2782bbdb4

## Code To Reproduce Issue 

```
AppiumDriver driver = new IOSDriver(url, capabilities);
 //.. standart lauch app operations
@Test
   public void testTappingOnUserLocationDoesNotBringUpPreviewBar() throws InterruptedException
    {
        Location locAntalya = new Location(36.849259, 30.763740, 1);
        driver.setLocation(locAntalya);
        openMapView();

        Point center = iosSearchPage.mapView.getCenter();
        pinch(center.x, center.y, 75, true);

        float oldY = iosSearchPage.previewCollectionView.getLocation().y;
        WebElement currentLocAnnotation = driver.findElement(By.xpath("//*[@name='Current Location']"));
        tapOnElement(currentLocAnnotation);

        float newY = iosSearchPage.previewCollectionView.getLocation().y;

        Assert.assertTrue(newY == oldY);
    }
```

**Comment by mykola-mokhnach** [comment]
Currently Apple does not provide any API for XCTest framework to simulate GPS location. Although you  still set custom location in Simulator via menu bar using Apple scripting.

**Comment by alexisalvarez88** [comment]
How? can you please describe it?

**Comment by LukasLewandowski** [comment]
@alexisalvarez88 check this:

https://stackoverflow.com/questions/45831592/appium-how-to-set-geo-location-on-ios-device/46973709#46973709

**Comment by mykola-mokhnach** [comment]
This feature is going to merged into Appium beta. It requires, that Appium process has access to system accessibility:

https://github.com/appium/appium-xcuitest-driver/pull/551
