### ISSUE TITLE
Appium 1.6.3 doesn't install/launch application on real device

### ISSUE THREAD

**Issue by iglunev** [appium/appium#7921]
## The problem

Trying to launch iOS application on real device, no UI interaction with application is needed. Appium simply hangs after server is launched. No error in logs. Reproduced on multiple machines.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0, 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.4.3
* Node.js version (unless using Appium.app|exe): v4.8.0
* Mobile platform/version under test: iOS 10.1.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Details

Launching appium with the following command:

appium -U "$(idevice_id -l)" --show-ios-log --ipa "$(pwd)/application.ipa" --pre-launch --log-level debug --launch-timeout 10 --platform-name "ios"

Tried adding --automation-name "XCUItest" option, no luck.

iOS device is attached and is listed with idevice_id, "Enable UI automation" setting is enabled on the phone. Able to manually install the application with ideviceinstaller, able to launch installed app with Instruments.

XCode version 8.2
$ xcode-select -p
/Applications/Xcode8.2.app/Contents/Developer

## Link to Appium logs
https://gist.github.com/iglunev/d313dc66b1f0859581f577679bc05778

**Comment by mykola-mokhnach** [comment]
make sure you follow [real device setup procedure](https://github.com/appium/appium-xcuitest-driver#usage) for Appium. The stuff has been significantly changed since version 1.4

**Comment by iglunev** [comment]
Thank you for the link, mykola-mokhnach, but the issue was different.
Apparently the reason for Appium hanging is because Appium didn't like the device-name parameter  missing (which can be pretty much any gibberish anyway so why would it matter?), but it was never explicitly shown anywhere.

**Comment by imurchie** [comment]
Looking at the logs, is this everything? I think the issue is that `--pre-launch` doesn't do anything with iOS 10.
