### ISSUE TITLE
Unable to pass Args to commandline for AndroidDriver

### ISSUE THREAD

**Issue by malandra12** [appium/appium#7922]
## The problem

I attempted to pass chromeOptions to the AndroidDriver. When the driver initializes, it throws the following error:
```
[MJSONWP]` Encountered internal error running command: Error: unknown error: cannot parse capability: chromeOptions
from unknown error: unrecognized chrome option: Arguments
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.14393 x86_64)
    at Chromedriver.callee$2$0$ (../../lib/chromedriver.js:177:15)
    at tryCatch (C:\Users\michael-malandra\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\michael-malandra\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\michael-malandra\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke `(C:\Users\michael-malandra\AppData\Roaming\npm\node_modules\appium\node_modules\babel-runtime\regenerator\runtime.js:136:37)
```

## Environment

* Appium version (or git revision) - 1.6.3
* Desktop OS/version used to run Appium: Windows 10
* Mobile platform/version under test: Android 7.1.1
* Real device or emulator/simulator: Emulator
* Appium CLI or Appium.app|exe: Appium CLI

## Details & Code

I've tried both AndroidMobileCapabilityType.ChromeOptions and ChromeOptions.Capability.  I've tried passing the options object, calling options.ToCapabilities(), and building an anonymous object.  
`var options = new ChromeOptions();
            options.AddUserProfilePreference("distribution.skip_first_run_ui", true);
            options.AddUserProfilePreference("first_run_tabs", "chrome://newtab");
            options.AddUserProfilePreference("distribution.show_welcome_page", false);
            capabilities.SetCapability(ChromeOptions.Capability, new { prefs = new { distribution = new { skip_first_run_ui = true, first_run_tabs = "chrome://newtab", show_welcome_page = false } } });
            //capabilities.SetCapability(ChromeOptions.Capability, options);`

## Link to Appium logs

https://gist.github.com/malandra12/41109918eeb14bfc63aa81484d6b066d

**Comment by mykola-mokhnach** [comment]
Check the doc at https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md for an example of how to set **chromeOptions** capability

**Comment by malandra12** [comment]
So this worked:

`capabilities.SetCapability(ChromeOptions.Capability, new Dictionary<string, object>() { { "args", new string[] { "--disable-popup-blocking" } }});`

However, I get the following error when trying to use prefs:
```
Error: unknown error: cannot parse capability: chromeOptions
from unknown error: unrecognized chrome option: prefs
```

I've tried the following format:
`var prefs = new Dictionary<string, object>() { { "distribution.skip_first_run_ui", true }, { "distribution.show_welcome_page", false }, { "first_run_tabs", new string[] { "chrome://newtab" } } };
            capabilities.SetCapability(ChromeOptions.Capability, new Dictionary<string, object>() { { "prefs", prefs } });`

and

`var distributionPrefs = new Dictionary<string, object>() { { "skip_first_run_ui", true}, { "show_welcome_page", false } };
            var prefs = new Dictionary<string, object>() { { "distribution", distributionPrefs }, { "first_run_tabs", new string[] { "chrome://newtab" } } };
            capabilities.SetCapability(ChromeOptions.Capability, new Dictionary<string, object>() { { "prefs", prefs} });`

**Comment by malandra12** [comment]
Looks like this may be an issue with the chromedriver:

From https://github.com/bayandin/chromedriver/blob/e8117250b96711b80fec1b24d2bd3de0c135f9da/capabilities.cc
```
  if (is_android) {
    parser_map["androidActivity"] =
        base::Bind(&ParseString, &capabilities->android_activity);
    parser_map["androidDeviceSerial"] =
        base::Bind(&ParseString, &capabilities->android_device_serial);
    parser_map["androidPackage"] =
        base::Bind(&ParseString, &capabilities->android_package);
    parser_map["androidProcess"] =
        base::Bind(&ParseString, &capabilities->android_process);
    parser_map["androidUseRunningApp"] =
        base::Bind(&ParseBoolean, &capabilities->android_use_running_app);
    parser_map["args"] = base::Bind(&ParseSwitches);
    parser_map["excludeSwitches"] = base::Bind(&ParseExcludeSwitches);
    parser_map["loadAsync"] = base::Bind(&IgnoreDeprecatedOption, "loadAsync");
  } else if (is_remote) {
    parser_map["debuggerAddress"] = base::Bind(&ParseUseRemoteBrowser);
  } else {
    parser_map["args"] = base::Bind(&ParseSwitches);
    parser_map["binary"] = base::Bind(&ParseFilePath, &capabilities->binary);
    parser_map["detach"] = base::Bind(&ParseBoolean, &capabilities->detach);
    parser_map["excludeSwitches"] = base::Bind(&ParseExcludeSwitches);
    parser_map["extensions"] = base::Bind(&ParseExtensions);
    parser_map["forceDevToolsScreenshot"] = base::Bind(
        &ParseBoolean, &capabilities->force_devtools_screenshot);
    parser_map["loadAsync"] = base::Bind(&IgnoreDeprecatedOption, "loadAsync");
    parser_map["localState"] =
        base::Bind(&ParseDict, &capabilities->local_state);
    parser_map["logPath"] = base::Bind(&ParseLogPath);
    parser_map["minidumpPath"] =
        base::Bind(&ParseString, &capabilities->minidump_path);
    parser_map["mobileEmulation"] = base::Bind(&ParseMobileEmulation);
    parser_map["prefs"] = base::Bind(&ParseDict, &capabilities->prefs);
  }
```

Doesn't look like android supports prefs for some reason.

**Comment by mykola-mokhnach** [comment]
I'd rather ask this question in Appium driver for .NET project or even in Chrome issues tracker
No idea how the stuff is supposed to work there. This is what Google search returns to me: https://bugs.chromium.org/p/chromedriver/issues/detail?id=1014

**Comment by malandra12** [comment]
I've modified the issue to represent the real issue with Appium, as far as I can tell.

While we can pass in the args to the chromeOptions, they aren't actually used when launching chromedriver.

We can see this here:
`Spawning chromedriver with: C:\Users\michael-malandra\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=8000 --adb-port=5037`

The args they I passed to chromeOptions are here:

            capabilities.SetCapability(ChromeOptions.Capability, new Dictionary<string, object>() { { "args", new string[] { "--disable-fre", "--no-first-run" } } });

As you can see, those options are not passed to the command line when starting chromedriver, and I can't tell if they're ever actually used.

**Comment by imurchie** [comment]
The chrome options aren't part of the startup, but part of session creation with ChromeDriver. In your original logs they are here: https://gist.github.com/malandra12/41109918eeb14bfc63aa81484d6b066d#file-gistfile1-txt-L115

**Comment by malandra12** [comment]
Here is my updated log file.

https://gist.github.com/malandra12/eea1859b4c66fa2c823504d942cf7145

I'm no longer getting the error from the original log file due to the changes made based on mykola's suggestions.  The problem is when chrome is initialized from the command line, its not passing the switches that I included in the args for chromeOptions.  


You can see the new

**Comment by jlipps** [comment]
This was fixed a few weeks ago and should be in Appium 1.6.4
