### ISSUE TITLE
iOS 10.0.2: Lots of <Others> tagged elements are observed on inspecting elements using app-inspector

### ISSUE THREAD

**Issue by Dheepthi** [appium/appium#7925]
Issue:
I'm trying to automate my app in iOS 10.02 simulator using Appium 1.6.3.
one of the steps were failing due to element not found.
When i got the page source and when i inspected the element using app-inspector-UI (./node_modules/.bin/app-inspector -u {simulator_ID}), i found lots of <Others> tag elements. The actual locator name is missing.

I'm sure its not <Others> tag because i can see the locator name in iOS9.x and iOS8.x version.

Appium: 1.6.3
XCode: 8
iOS Simulator: 10.0.2

![screen shot 2017-02-23 at 2 23 35 pm](https://cloud.githubusercontent.com/assets/22946030/23281834/b10430a0-f9d3-11e6-9705-60160a61102d.png)

**Comment by mykola-mokhnach** [comment]
XCTest uses absolutely different approach to build UI tree and this is normal that it looks differently from what is created by instruments. This anyway has nothing to do to Appium itself, because Appium itself is a proxy between WDA and client code.
