### ISSUE TITLE
mobile scroll command is able to scroll to not visible element on ios 10 Appium 1.6.3

### ISSUE THREAD

**Issue by abh7nav** [appium/appium#7926]
## The problem

mobile:scroll command is not working on ios 10 and appium 1.6.3

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3 
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS sierra
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test: ios 10 
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: appium CLI

## Details

I have written below method to use mobile scroll method to scroll to a non visible element but it is not working.

public void scrollToElement() {
		String targetCell = "//*[@name='elementText']";
		RemoteWebElement cellWithText = (RemoteWebElement)IOSAppiumConnection.driver.findElement(By.xpath(targetCell));
		HashMap<String, String> scrollObject = new HashMap<String, String>();
		scrollObject.put("element", cellWithText.getId());
		scrollObject.put("toVisible", "true");
		IOSAppiumConnection.driver.executeScript("mobile: scroll", scrollObject);
	}

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/880bc9ea-ad98-46c0-983a-68718ec3cb04/element {"using":"xpath","value":"//*[@name='elementText']"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//*[@name='elementText']","880bc9ea-ad98-46c0-983a-68718ec3cb04"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/0B9E5B59-5A10-4188-A755-3A45ABDA0A89/element] with body: {"using":"xpath","value":"//*[@name='elementText']"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"404D9B39-04C6-4BDF-84C7-ECED6F95F40C","type":"XCUIElementTypeButton","label":"elementText"},"sessionId":"0B9E5B59-5A10-4188-A755-3A45ABDA0A89","status":0}
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"404D9B39-04C6-4BDF-84C7-ECED6F95F40C","type":"XCUIElementTypeButton","label":"elementText"}
[HTTP] <-- POST /wd/hub/session/880bc9ea-ad98-46c0-983a-68718ec3cb04/element 200 21595 ms - 184 
[HTTP] --> POST /wd/hub/session/880bc9ea-ad98-46c0-983a-68718ec3cb04/execute {"script":"mobile: scroll","args":[{"toVisible":"true","element":"404D9B39-04C6-4BDF-84C7-ECED6F95F40C"}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: scroll",[{"toVisible":"true","element":"404D9B39-04C6-4BDF-84C7-ECED6F95F40C"}],"880bc9ea-ad98-46c0-983a-68718ec3cb04"]
[debug] [XCUITest] Executing command 'execute'
[debug] [JSONWP Proxy] Proxying [POST /uiaElement/404D9B39-04C6-4BDF-84C7-ECED6F95F40C/scroll] to [POST http://localhost:8100/session/0B9E5B59-5A10-4188-A755-3A45ABDA0A89/uiaElement/404D9B39-04C6-4BDF-84C7-ECED6F95F40C/scroll] with body: {"toVisible":"true"}
[debug] [iProxy] recv failed: Resource temporarily unavailable
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/880bc9ea-ad98-46c0-983a-68718ec3cb04/execute 500 240026 ms - 251 

## Code To Reproduce Issue [ Good To Have ]
public void scrollToElement() {
		String targetCell = "//*[@name='elementText']";
		RemoteWebElement cellWithText = (RemoteWebElement)IOSAppiumConnection.driver.findElement(By.xpath(targetCell));
		HashMap<String, String> scrollObject = new HashMap<String, String>();
		scrollObject.put("element", cellWithText.getId());
		scrollObject.put("toVisible", "true");
		IOSAppiumConnection.driver.executeScript("mobile: scroll", scrollObject);
	}

**Comment by mykola-mokhnach** [comment]
Update Appium to 1.6.4-beta

**Comment by abh7nav** [comment]
@mykola-mokhnach is this the solution for every issue? 

Also, as appium-1.6.4 is still in Beta in phase, it will not be feasible for us to make such change till there is any release. Hope you understand.

**Comment by mykola-mokhnach** [comment]
Then you need to wait until 1.6.4 is released. As you can see, Appium 1.6.3 does not support swipe command yet.

**Comment by abh7nav** [comment]
OK

**Comment by navnathkarche** [comment]
Scroll to visible not working in XCUITest.

**Environment:**
  1. Appium: 1.7.1

**Problem**
When we call `Appiumdriver.execute_script('mobile: scroll', { element: "E8A012C5-2509-44EA-BE85-F9AC98057DBC", 'toVisible': 'true'})`
it only scroll down and try to find element if element is present on top then it could not find that element.

Try to  scroll down for multiple time and then throws error 
`An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Failed to perform scroll with visible cell due to max scroll count reached" UserInfo={NSLocalizedDescription=Failed to perform scroll with visible cell due to max scroll count reached}`

**Comment by AmukthaTandra** [comment]
@navnathkarche Did you find a work around for this issue? I am running in to the same issue.

**Comment by navnathkarche** [comment]
@amuktha if you running test cases on iOS >=10 then it is Facebook web driver agents issue. I have already created issue on it https://github.com/facebook/WebDriverAgent/issues/770 but still not resolve the issue.

**Comment by AmukthaTandra** [comment]
I am using iOS version 9.3 and I still have the same issue.

**Comment by navnathkarche** [comment]
Can you post appiumn log?

**Comment by AmukthaTandra** [comment]
[Appium.log](https://github.com/appium/appium/files/1565300/Appium.log)
Here you go
