### ISSUE TITLE
Session issue .NoSuchElementException: An element could not be located on the page using the given search parameters. 

### ISSUE THREAD

**Issue by efawan** [appium/appium#7927]
## The problem

Hi all, im start to learn appium. 
I'm facing this problem, please help me to fix this. Thank You

org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)

## Environment

* Appium version ( 1.4.16 and 1.4.13 ) Windows Version
* Desktop OS/version Win 10
* Mobile platform Android os 5.1.1
* Real device : Galaxy J1 Ace
* Junit

## Details

Somehow i can run this code properly, but mostly i facing this problem. 
Its frustasing me, how to fix this problem.  I'm trying to change appium version to 1.4.13 to 1.4.16 and latest version using node JS, but its not fixed. 

## Link to Appium logs
 POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"app":"D:\\Appium\\QlueAc\\src\\bookMyShow-ucb.apk","platformName":"Android","deviceName":"4200278de44ba300","newCommandTimeout":"100"},"requiredCapabilities":{}},"desiredCapabilities":{"app":"D:\\Appium\\QlueAc\\src\\bookMyShow-ucb.apk","platformName":"Android","deviceName":"4200278de44ba300","newCommandTimeout":"100"},"requiredCapabilities":{}}
> info: Client User-Agent string: Apache-HttpClient/4.5.2 (Java/1.8.0_121)
> info: [debug] No appActivity desired capability or server param. Parsing from apk.
> info: [debug] No appPackage desired capability or server param. Parsing from apk.
> info: [debug] Using local app from desired caps: D:\Appium\QlueAc\src\bookMyShow-ucb.apk
> info: [debug] Creating new appium session a93302cc-6341-46e1-a70e-40bc789303a2
> info: Starting android appium
> info: [debug] Getting Java version
> info: Java version is: 1.8.0_121
> info: [debug] Checking whether adb is present
> info: [debug] Using adb from C:\SDK\platform-tools\adb.exe
> info: [debug] Parsing package and activity from app manifest
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\SDK\build-tools\25.0.1\aapt.exe
> info: [debug] Extracting package and launch activity from manifest.
> info: [debug] executing cmd: C:\SDK\build-tools\25.0.1\aapt.exe dump badging D:\Appium\QlueAc\src\bookMyShow-ucb.apk
> info: [debug] badging package: com.bt.bms
> info: [debug] badging act: com.bt.bms.activities.SplashActivity
> info: [debug] Parsed package and activity are: com.bt.bms/com.bt.bms.activities.SplashActivity
> info: [debug] Set chromedriver binary as: C:\Program Files (x86)\Appium\node_modules\appium\build\chromedriver\windows\chromedriver.exe
> info: [debug] Using fast reset? true
> info: [debug] Preparing device for session
> info: [debug] Checking whether app is actually present
> info: Retrieving device
> info: [debug] Trying to find a connected android device
> info: [debug] Getting connected devices...
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe devices
> info: [debug] 1 device(s) connected
> info: Found device 4200278de44ba300
> info: [debug] Setting device id to 4200278de44ba300
> info: [debug] Waiting for device to be ready and to respond to shell commands (timeout = 5)
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 wait-for-device
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "echo 'ready'"
> info: [debug] Starting logcat capture
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: Device API level is: 22
> info: [debug] Extracting strings for language: default
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "getprop persist.sys.language"
> info: [debug] Current device persist.sys.language: en
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "D:\Appium\QlueAc\src\bookMyShow-ucb.apk" "C:\Users\Budiyono\AppData\Local\Temp\com.bt.bms" en
> info: [debug] No strings.xml for language 'en', getting default strings.xml
> info: [debug] java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\appium_apk_tools.jar" "stringsFromApk" "D:\Appium\QlueAc\src\bookMyShow-ucb.apk" "C:\Users\Budiyono\AppData\Local\Temp\com.bt.bms"
> info: [debug] Reading strings from converted strings.json
> info: [debug] Setting language to default
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 push "C:\\Users\\Budiyono\\AppData\\Local\\Temp\\com.bt.bms\\strings.json" /data/local/tmp
> info: [debug] Checking whether aapt is present
> info: [debug] Using aapt from C:\SDK\build-tools\25.0.1\aapt.exe
> info: [debug] Retrieving process from manifest.
> info: [debug] executing cmd: C:\SDK\build-tools\25.0.1\aapt.exe dump xmltree D:\Appium\QlueAc\src\bookMyShow-ucb.apk AndroidManifest.xml
> info: [debug] Set app process to: com.bt.bms
> info: [debug] Not uninstalling app since server not started with --full-reset
> info: [debug] Checking app cert for D:\Appium\QlueAc\src\bookMyShow-ucb.apk.
> info: [debug] executing cmd: java -jar "C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-adb\jars\verify.jar" D:\Appium\QlueAc\src\bookMyShow-ucb.apk
> info: [debug] App already signed.
> info: [debug] Zip-aligning D:\Appium\QlueAc\src\bookMyShow-ucb.apk
> info: [debug] Checking whether zipalign is present
> info: [debug] Using zipalign from C:\SDK\build-tools\25.0.1\zipalign.exe
> info: [debug] Zip-aligning apk.
> info: [debug] executing cmd: C:\SDK\build-tools\25.0.1\zipalign.exe -f 4 D:\Appium\QlueAc\src\bookMyShow-ucb.apk C:\Users\Budiyono\AppData\Local\Temp\117124-10832-1mvlvfy\appium.tmp
> info: [debug] MD5 for app is 8c3d1b1372441237108d673a6fe85c8f
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "ls /data/local/tmp/8c3d1b1372441237108d673a6fe85c8f.apk"
> info: [debug] Getting install status for com.bt.bms
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "pm list packages -3 com.bt.bms"
> info: [debug] App is installed
> info: App is already installed, resetting app
> info: [debug] Running fast reset (stop and clear)
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "am force-stop com.bt.bms"
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "pm clear com.bt.bms"
> info: [debug] Forwarding system:4724 to device:4724
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 forward tcp:4724 tcp:4724
> info: [debug] Pushing appium bootstrap to device...
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 push "C:\\Program Files (x86)\\Appium\\node_modules\\appium\\build\\android_bootstrap\\AppiumBootstrap.jar" /data/local/tmp/
> info: [debug] Pushing settings apk to device...
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 install "C:\Program Files (x86)\Appium\node_modules\appium\build\settings_apk\settings_apk-debug.apk"
> info: [debug] Pushing unlock helper app to device...
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 install "C:\Program Files (x86)\Appium\node_modules\appium\build\unlock_apk\unlock_apk-debug.apk"
> info: Starting App
> info: [debug] Attempting to kill all 'uiautomator' processes
> info: [debug] Getting all processes with 'uiautomator'
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "ps 'uiautomator'"
> info: [debug] No matching processes found
> info: [debug] Running bootstrap
> info: [debug] spawning: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell uiautomator runtest AppiumBootstrap.jar -c io.appium.android.bootstrap.Bootstrap -e pkg com.bt.bms -e disableAndroidWatchers false
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] io.appium.android.bootstrap.Bootstrap:
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 1
> info: [debug] [BOOTSTRAP] [debug] Socket opened on port 4724
> info: [debug] [BOOTSTRAP] [debug] Appium Socket Server Ready
> info: [debug] [BOOTSTRAP] [debug] Loading json...
> info: [debug] Waking up device if it's not alive
> info: [debug] Pushing command to appium work queue: ["wake",{}]
> info: [debug] [BOOTSTRAP] [debug] json loading complete.
> info: [debug] [BOOTSTRAP] [debug] Registered crash watchers.
> info: [debug] [BOOTSTRAP] [debug] Client connected
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"wake","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: wake
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":true}
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "dumpsys window"
> info: [debug] Screen already unlocked, continuing.
> info: [debug] Pushing command to appium work queue: ["getDataDir",{}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"getDataDir","params":{}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: getDataDir
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"\/data\/local\/tmp"}
> info: [debug] dataDir set to: /data/local/tmp
> info: [debug] Pushing command to appium work queue: ["compressedLayoutHierarchy",{"compressLayout":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"compressedLayoutHierarchy","params":{"compressLayout":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: compressedLayoutHierarchy
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":false}
> info: [debug] Getting device API level
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "getprop ro.build.version.sdk"
> info: [debug] Device is at API Level 22
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "am start -S -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.bt.bms/com.bt.bms.activities.SplashActivity"
> info: [debug] Waiting for pkg "com.bt.bms" and activity "com.bt.bms.activities.SplashActivity" to be focused
> info: [debug] Getting focused package and activity
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "dumpsys window windows"
> info: [debug] executing cmd: C:\SDK\platform-tools\adb.exe -s 4200278de44ba300 shell "getprop ro.build.version.release"
> info: [debug] Device is at release version 5.1.1
> info: [debug] Device launched! Ready for commands
> info: [debug] Setting command timeout to 100 secs
> info: [debug] Appium session started with sessionId a93302cc-6341-46e1-a70e-40bc789303a2
> info: <-- POST /wd/hub/session 303 16490.279 ms - 74 
> info: --> GET /wd/hub/session/a93302cc-6341-46e1-a70e-40bc789303a2 {}
> info: [debug] Responding to client with success: {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"5.1.1","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"D:\\Appium\\QlueAc\\src\\bookMyShow-ucb.apk","platformName":"Android","deviceName":"4200278de44ba300","newCommandTimeout":"100"},"app":"D:\\Appium\\QlueAc\\src\\bookMyShow-ucb.apk","platformName":"Android","deviceName":"4200278de44ba300","newCommandTimeout":"100"},"sessionId":"a93302cc-6341-46e1-a70e-40bc789303a2"}
> info: <-- GET /wd/hub/session/a93302cc-6341-46e1-a70e-40bc789303a2 200 1.956 ms - 599 {"status":0,"value":{"platform":"LINUX","browserName":"Android","platformVersion":"5.1.1","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"app":"D:\\Appium\\QlueAc\\src\\bookMyShow-ucb.apk","platformName":"Android","deviceName":"4200278de44ba300","newCommandTimeout":"100"},"app":"D:\\Appium\\QlueAc\\src\\bookMyShow-ucb.apk","platformName":"Android","deviceName":"4200278de44ba300","newCommandTimeout":"100"},"sessionId":"a93302cc-6341-46e1-a70e-40bc789303a2"}
> info: --> POST /wd/hub/session/a93302cc-6341-46e1-a70e-40bc789303a2/element {"using":"id","value":"com.bt.bms:id/btnLogin"}
> info: [debug] Waiting up to 0ms for condition
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"id","selector":"com.bt.bms:id/btnLogin","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.bt.bms:id/btnLogin","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding com.bt.bms:id/btnLogin using ID with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.bt.bms:id/btnLogin]
> info: [debug] [BOOTSTRAP] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
> info: [debug] [BOOTSTRAP] [debug] Finding com.bt.bms:id/btnLogin using ID with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.bt.bms:id/btnLogin]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":7,"value":"No element found"}
> info: [debug] Condition unmet after 703ms. Timing out.
> info: [debug] Responding to client with error: {"status":7,"value":{"message":"An element could not be located on the page using the given search parameters.","origValue":"No element found"},"sessionId":"a93302cc-6341-46e1-a70e-40bc789303a2"}

## Code To Reproduce Issue [ Good To Have ]

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import io.appium.java_client.remote.MobilePlatform;

public class login {

	@Test
	public void test() throws MalformedURLException {
		       File appDir = new File("src");
		    File app = new File(appDir,"bookMyShow-ucb.apk");
		DesiredCapabilities cap=new DesiredCapabilities();
		cap.setCapability(MobileCapabilityType.PLATFORM_NAME,MobilePlatform.ANDROID);
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, "4200278de44ba300");
		cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "100");
		cap.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
		AndroidDriver driver=new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),cap );
		driver.findElementById("com.bt.bms:id/btnLogin").click();
		driver.findElementById("com.bt.bms:id/btnSignUp").click();
	int s=driver.findElements(By.className("android.widget.EditText")).size();
		System.out.println(s);
		List<WebElement>a=driver.findElements(By.className("android.widget.EditText"));
		a.get(0).sendKeys("Appium");
		a.get(1).sendKeys("Mobile");
		a.get(2).sendKeys("appium@training");
		a.get(3).sendKeys("password");
		driver.findElementById("com.bt.bms:id/action_icon").click();
		
	}
}

**Comment by mykola-mokhnach** [comment]
This exception is thrown when an element cannot be located in DOM using the given search locator. Please use Appium forum for howto questions

**Comment by abisekkachroo** [comment]
@mykola-mokhnach 
As per your comments the element is not getting loaded in DOM 
What are the causes and how to solve this issue 
I am facing the same issue , It was working till last night but now I am getting the same exception error
Can you please explain

**Comment by DeepikaThiru** [comment]
I have a scenario in which i have to click  a particular element if it is presented in the page else i have to skip and click other element in the page.when i checked the presence of the element in the page using isdisplayed() function it is saying as 
Can't locate an element by this strategy: Locator map: 
- native content: "By.id: Close" 
- html content: "by id or name "closeButton""

I know that the particular element is not present over there that's why gave in if block but still got the same error..

**//code snippet**
if (closeButton.isDisplayed()) {
                    closeButton.click();
                }
else{
                    pauseButton.click(); //pausing the video
                    playButton.click(); //playing the video
                    doneButton.click(); //closing the video player
}

help me out

**Comment by abisekkachroo** [comment]
@DeepikaThiru 
u can use  
Webdriverwait wait = new WebdriverWait(driver,Time in Seconds);
wait.until(ExpectedConditions.visibilityof("Your element"));
then use your if else logic 
It will work

**Comment by DeepikaThiru** [comment]
Thank you leet me try it
