### ISSUE TITLE
Appium is getting stuck after "unable to find an element" for ~15 seconds

### ISSUE THREAD

**Issue by RockChild** [appium/appium#7928]
## The problem

AppiumDriver is getting stuck for around 15 secs after trying to find an element which is not displayed even if I set implicit wait of 1 second.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: Mac OS X 10.12.3
* Node.js version (unless using Appium.app|exe):v6.9.5
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: both
* Appium CLI or Appium.app|exe:

## Details

Driver is getting stuck after unable to find element, and after more than 15 seconds driver is setting imlicit wait for a 1 second by itself(can see in logs)
When I set implicit wait for the driver, it doesn't help. I tried setting 1/5/60 seconds, but no diff.
It's repeating everytime element is not displayed. 
Tried to initiate pages like:

       PageFactory.initElements(new AppiumFieldDecorator(driver, 1, TimeUnit.SECONDS), this);

Tried 

       driver.manage().timeouts().implicitlyWait(1, TimeUnit.SECONDS);

No changes.

## Link to Appium logs

https://gist.github.com/RockChild/1981c37a24b6b06e47fc1ec84ad2caad#file-wait

Delay is right after getting response(500)

## Code To Reproduce Issue [ Good To Have ]
Because I set @iOSFindBy annotations for every element, I don't want to make 'waitForElement' using xpath, that's why I'm looking if it is displayed with handling it in try-catch.

class:

     public class LoginScreen {
              @iOSFindBy(xpath = "//XCUIElementTypeTable/XCUIElementTypeCell[1]/XCUIElementTypeTextField")
             private IOSElement loginInput;
          
             public LoginScreen(IOSDriver driver) {
                   this.driver = driver;
                   PageFactory.initElements(new AppiumFieldDecorator(driver, 1, TimeUnit.SECONDS), this);
             }
     }

wait:
        
        public void waitForElement(IOSElement element) {
        wait = new FluentWait(driver);
        wait.ignoring(NoSuchElementException.class)
                .pollingEvery(500, TimeUnit.MILLISECONDS)
                .withTimeout(EXPLICIT_TIMEOUT, TimeUnit.SECONDS)
                .until((Predicate<WebDriver>) webDriver -> isElementDisplayedOnScreenSafe(element));
      }
    public boolean isElementDisplayedOnScreenSafe(IOSElement element) {
        try {
            return element.isDisplayed();
        } catch (Exception ex) {
            Reporter.log(String.format("Exception caught while looking whether an element is visible: \n %s",
                    ex.getMessage()), true);
            return false;
        }
    }

**Comment by mykola-mokhnach** [comment]
Your problem is https://github.com/facebook/WebDriverAgent/issues/372, which has nothing to do with Appium itself.

**Comment by RockChild** [comment]
@mykola-mokhnach 
I see. But reading that issue, haven't understood completely: is there a workaround? and if yes, pls point me to exact comment, where it is described. I would be appreciated!

**Comment by mykola-mokhnach** [comment]
There is a workaround, but it is not ideal.

Apply this patch to the local WDA source, file WebDriverAgentLib/Categories/XCUIElement+FBIsVisible.m

```
@@ -9,6 +9,7 @@
 
 #import "XCUIElement+FBIsVisible.h"
 
+#import "FBMathUtils.h"
 #import "XCElementSnapshot+FBHelpers.h"
 #import "XCTestPrivateSymbols.h"
 
@@ -29,18 +30,10 @@
 - (BOOL)fb_isVisible
 {
   if (CGRectIsEmpty(self.frame) || CGRectIsEmpty(self.visibleFrame)) {
-    /*
-     It turns out, that XCTest triggers
-       Enqueue Failure: UI Testing Failure - Failure fetching attributes for element
-       <XCAccessibilityElement: 0x60000025f9e0> Device element: Error Domain=XCTestManagerErrorDomain Code=13
-       "Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202} <unknown> 0 1
-     error in the log if we try to get visibility attribute for an element snapshot, which does not intersect with visible appication area
-     or if it has zero width/height. Also, XCTest waits for 15 seconds after this line appears in the log, which makes /source command
-     execution extremely slow for some applications.
-     */
     return NO;
   }
-  return [(NSNumber *)[self fb_attributeValue:FB_XCAXAIsVisibleAttribute] boolValue];
+  CGSize screenSize = FBAdjustDimensionsForApplication(self.application.frame.size, self.application.interfaceOrientation);
+  return CGRectIntersectsRect(self.visibleFrame, CGRectMake(0, 0, screenSize.width, screenSize.height));
 }
 
 @end
```

**Comment by RockChild** [comment]
Thanks! I definitely give it a whirl!

**Comment by RockChild** [comment]
Hi @mykola-mokhnach  
I tried only today your code and unfortunately, it didn't help, console(as well as the WDA I suppose) is getting stuck, when I try to find element wich is not on the screen. 
I tried every option form main issue page. I still see this in ~15seconds after run element.isVisible(); :

    [HTTP] --> POST /wd/hub/session/98b7337b-6a06-4552-8cbf-8f24db7d5ad2/timeouts {"type":"implicit","ms":1000}
    [debug] [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",1000,"98b7337b-6a06-4552-8cbf-8f24db7d5ad2"]
    [debug] [XCUITest] Executing command 'timeouts'
    [debug] [BaseDriver] Set implicit wait to 1000ms
    [debug] [MJSONWP] Responding to client with driver.timeouts() result: null
    [HTTP] <-- POST /wd/hub/session/98b7337b-6a06-4552-8cbf-8f24db7d5ad2/timeouts 200 1 ms - 76 

As you can see I don't receive any error. Just stack. Any suggestions for a workaround?

**Comment by jlipps** [comment]
@RockChild please try Appium 1.6.4, which I believe has improvements from WDA.
