### ISSUE TITLE
Appium 1.6.4 beta- iOS Hybrid Native App Application taking longer time in WEBVIEW context

### ISSUE THREAD

**Issue by dilsreccse** [appium/appium#7931]
## The problem

Appium 1.6.4 beta is taking too longer time to identify elements in WEBVIEW context for  iOS Hybrid Native App Application.

Appium version (or git revision) that exhibits the issue: 1.6.4 beta
Desktop OS/version used to run Appium: Sierra Mac OS
Node.js version (unless using Appium.app|exe):
Mobile platform/version under test: iOS 10 [iPad Air ]
Real device or emulator/simulator: Real
Appium CLI or Appium.app|exe: Appium CLI
XCUITestDriver version : 2.5.3

## Link to Appium logs

Gist [here](https://gist.github.com/dilsreccse/20537230b364ed016802094111b72cc0)

**Comment by mykola-mokhnach** [comment]
Try to minimize count of calls to WDA and cache as much elements as possible to increase the speed.

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach  what do you mean by caching elements? Could you give and example.
As even i see my tests taking longer time on iOS Hybrid as compared to Android Hybrid.

**Comment by mykola-mokhnach** [comment]
Each api call which generates request to WDA backend takes time. FindElement(s) requests can be exceptionally time consuming. That is why it could save a lot of time if one caches results of such requests and performs further actions on cached elements.

**Comment by mayureshshirodkar** [comment]
@mykola-mokhnach That sounds good! I'll surely try it out.
But is there anything that can be done on the Appium side to reduce the lookup times with WDA.

**Comment by mykola-mokhnach** [comment]
@mayureshshirodkar Probably it can, but I don't know what. You are welcome to commit if you know.

**Comment by dilsreccse** [comment]
@mykola-mokhnach & @mayureshshirodkar ,even FindElement is taking longer time :( previous versions of appium before 1.6 was not so.. @jlipps can this be fixed from appium team?

**Comment by mayureshshirodkar** [comment]
Agreed with @dilsreccse . My tests took less time to run and were faster with version 1.4.16 compared to 1.5.3 and later.

**Comment by mykola-mokhnach** [comment]
There is only one very tiny problem there. Apple has completely removed instruments support from iOS 10.0+ and replaced it with XCTest. So you may continue to use old Appium if you like it, but it's possible only to test old iOS builds.

**Comment by vikramvi** [comment]
@mayureshshirodkar  @dilsreccse don't use implicit wait ( or keep very minimal 1 sec ) always use explicit wait for individual elements.
Also as @mykola-mokhnach suggested reduce findElements calls if possible.
I don't recommend using older versions of appium at all.

**Comment by dilsreccse** [comment]
@vikramvi thanks , but I have used explicit wait for the elements still it remains the same

**Comment by dilsreccse** [comment]
@mykola, you mean xctest doesn't have better performance than instruments , if so We need to wait for apple to improve xctest performance ?

**Comment by mykola-mokhnach** [comment]
@dilsreccse I cannot say for sure - something works better, something not really. It is normal, that every new technology (and is XCTest is such a new technology built from scratch) requires some time to achieve decent stability and solidity levels. The only problem I can observe there is very slow feedback from Apple. It can take months for them to fix an issue in XCTest. :(

**Comment by dilsreccse** [comment]
@mykola-mokhnach thanks ! Hope so Apple will fix the slowness issue at the earliest.
