### ISSUE TITLE
Update documentation for Appium 1.6.4 on http://appium.io/slate/en/master/

### ISSUE THREAD

**Issue by mykola-mokhnach** [appium/appium#7935]
The most recent Appium version described there is 1.6.1, which is older than 3 months already. Also, the doc contains information about the old standalone Appium UI client, which is not supported anymore and confuses our users.

**Comment by dpgraham** [comment]
@mykola-mokhnach Closing this. @rkavalap's PR fixed these issues (https://github.com/appium/appium.io/commit/868b35d88af839285dbd47a5d3e8a6c6c0facd02#diff-34c4da6d4768d05e50db99357a299b5c)
