### ISSUE TITLE
Unable to automate anything inside in-app browser

### ISSUE THREAD

**Issue by sp5594** [appium/appium#7937]
I have an app that requires me to click on a link inside the app. Upon clicking on that link, a webpage will open up inside the app. I have to enter my credentials on that webpage. I`m trying to automate this part but so far no success. I have tried using both NATIVE and WEBVIEW but no luck so far. 

The app is an hybrid iOS and Android app. On Android, I can switch to NATIVE and it works. On iOS, nothing is working.

**Comment by mykola-mokhnach** [comment]
Have you tried to set **autoWebview** capability to _true_?

**Comment by sp5594** [comment]
I have already tried that..

**Comment by mykola-mokhnach** [comment]
And what is present in the log if you try it?

**Comment by sp5594** [comment]
Unable to find the element..

**Comment by sp5594** [comment]
Issue is fixed. I was in the wrong WebView. When the in-app browser opens up, I have 2 WebViews. Once for the hybrid app and the other one is for the web page that opens up in the in-app browser.
