### ISSUE TITLE
automated testsuite has  been running fine but recently started getting intermittent failure "Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure

### ISSUE THREAD

**Issue by AmitVerma4HP** [appium/appium#7940]
## The problem
My automated testsuite was running fine but recently I started seeing that few tests will be fail in setup() stating. 

**FAILED CONFIGURATION: @BeforeClass setup("ZX1G22V3TS")
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'AutomationPC', ip: '15.47.191.31', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_111'
Driver info: driver.version: AndroidDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)**

**Only few test setup failed with this error whereas other run just fine so behavior is intermittent.**

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: Win7 64bit
* Node.js version (unless using Appium.app|exe): 
* Mobile platform/version under test: Android /6.0
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

Attached is the appium sever log -

[AppiumForWindows.txt](https://github.com/appium/appium/files/804566/AppiumForWindows.txt)

Attached is the test log -
[build_consolelog.txt](https://github.com/appium/appium/files/804568/build_consolelog.txt)

**Comment by mykola-mokhnach** [comment]
1.4.16 is a very old Appium version. Please try the newest one: 1.6.4-beta

**Comment by AmitVerma4HP** [comment]
I have started using npm appium 1.6.3 and will keep an eye to see if I come across same issue there.

**Comment by vikramvi** [comment]
@triager please close per last comment
