### ISSUE TITLE
How to deal with the alarm layer in 1.6.3, I am currently the environment appium1.6.3

### ISSUE THREAD

**Issue by liangjinwen** [appium/appium#7945]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:10.12.3
* Node.js version (unless using Appium.app|exe):v6.9.5
* Mobile platform/version under test:10.2
* Real device or emulator/simulator:Real device
* Appium CLI or Appium.app|exe:Appium CLI

## Details
I am currently trying to handle the system shell, using autoAcceptAlerts does not work
If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Please fill out the issue description template properly and reopen it then.

If you are talking about alerts then you might find the driver.switchTo.alert interface useful for such purpose. You can only control alerts, which were generated by your application under test. System alerts (like battery alert) cannot be accessed by XCTest methods.
