### ISSUE TITLE
ADB timeout error / JSON WP proxy problem

### ISSUE THREAD

**Issue by ferhorv** [appium/appium#7947]
## The problem

I experience several problems during automation:

1. I get a timeout for adbExec command.
The test code containted only the removeApp method.
[adbExecTimeout.txt](https://github.com/appium/appium/files/806756/adbExecTimeout.txt)

2. The test case hangs after "Waiting for UiAutomator2 to be online..." and execution does not continue. After 15 minutes just a several log entries like ([debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body).
The test code containted only the removeApp method.
[JSONWPProxyHangs.txt](https://github.com/appium/appium/files/806757/JSONWPProxyHangs.txt)

3. I get a ProxyRequestError at a random position during execution.
The test code in this case containted several commands (see log).
[MJSONWPProxyRequestError.txt](https://github.com/appium/appium/files/806755/MJSONWPProxyRequestError.txt)

## Environment

* Appium version (or git revision) that exhibits the issue: appium v1.6.3, appium-adb v2.11.1, appium-uiautomator2-driver v0.2.10,  appium-uiautomator2-server v0.1.3
* Desktop OS/version used to run Appium: Windows 7 Enterprise SP1
* Node.js version (unless using Appium.app|exe): 6.9.5
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Device: LG Nexus 5
* Appium CLI or Appium.app|exe: Appium CLI

## Details

As seen in the attached logs.

## Link to Appium logs

Sorry, we can't create a gist, because our proxy denies access. Attached txt.

**Comment by ferhorv** [comment]
any updates on this one?

**Comment by sravanmedarapu** [comment]
@ferhorv, Can you please try with latest version of appium-uiautomator2-driver and do share adb logcat if issues are replicating in latest version of appium-uiautomator2-driver ?
