### ISSUE TITLE
Can't click on 'Allow' button on Notification popup at startup on IOS

### ISSUE THREAD

**Issue by alexander-poulikakos** [appium/appium#7949]
## The problem

When appium starts my app, I get a system notification popup at start up, regarding allowing, or not allowing my app to send notifications. There's two buttons to choose from: "Don't Allow" and "Allow". In my Test I want to click on "Allow". But seems Appium ckicks on the wrong one. "Don't Allow".

## Environment

* Appium version: 1.6.3
* Desktop OS/version used to run Appium: Mac OSX 10.12.3 (Sierra)
* Node.js version: 7.5.0
* Mobile platform/version under test: IOS 10.2.1
* Real device is used
* Appium CLI, using Java client.

## Details

By looking at my app, this appears to happen (while debug stepping my test):

Appium clicks twice, first time on "Don't Allow" button, which causes the popup to dissapear. 
Then appium clicks again (instantly) on the location where the "Allow" button was, which happens to be the location of a  "connect to facebook" button on my app.  

Additionally: my app always runs in Landscape mode

## Link to Appium logs

Appium logs: https://gist.github.com/alexander-poulikakos/c2547ea4cf990d7f1d2d079b77075561

Appium doctor:
```
$ appium-doctor --ios 
info AppiumDoctor Appium Doctor v.1.4.1
info AppiumDoctor ### Diagnostic starting ###
info AppiumDoctor  ✔ The Node.js binary was found at: /usr/local/bin/node
info AppiumDoctor  ✔ Node version is 7.5.0
info AppiumDoctor  ✔ Xcode is installed at: /Applications/Xcode.app/Contents/Developer
info AppiumDoctor  ✔ Xcode Command Line Tools are installed.
info AppiumDoctor  ✔ DevToolsSecurity is enabled.
info AppiumDoctor  ✔ The Authorization DB is set up properly.
info AppiumDoctor  ✔ Carthage was found at: /usr/local/bin/carthage
info AppiumDoctor  ✔ HOME is set to: /Users/alexanderpoulikakos
info AppiumDoctor ### Diagnostic completed, no fix needed. ###
info AppiumDoctor 
info AppiumDoctor Everything looks good, bye!
info AppiumDoctor  
```

## Code To Reproduce Issue [ Good To Have ]

```java
IOSDriver<IOSElement> appium = ...;
System.out.println(appium.getPageSource()); // I have a break point here to ensure the Notifications popup is visible before continuing 
IOSElement allow = appium.findElementByName("Allow");
System.out.println(allow.getText()); // See printout in log for this
System.out.println(allow.getLocation()); // See printout in log for this
new TouchAction(appium).tap(allow).perform();
```

**Comment by mykola-mokhnach** [comment]
Try

```
driver.switchTo().alert().accept();
driver.switchTo().alert().dismiss();
```

methods to handle alerts

**Comment by alexander-poulikakos** [comment]
I have tried these, with no success:

```java
driver.switchTo().alert().accept();
driver.switchTo().alert().dismiss();
```

**Comment by alexander-poulikakos** [comment]
Forgot to mention: My app always runs in Landscape mode (first post updated with this.)

**Comment by mykola-mokhnach** [comment]
Try 1.6.4-beta then

**Comment by mykola-mokhnach** [comment]
Also, there is known XCTest bug for system alerts, which you cannot workaround in landscape mode. you need to change to portrait to accept it and then back

**Comment by alexander-poulikakos** [comment]
I tried with the 1.6.4-beta, and appium didn't click at all (i.e. it got worse).

My app can't run in Portrait mode :(

**Comment by vjmaiky** [comment]
I'm using something like this:

public static void acceptAllAlerts() {
		try {
			while (true) {
				log.info("Checking for alerts and dismissing them.");
				Thread.sleep(2000);
				// needed because in appium 1.4.8 accept() will choose the Deny.
				// Update list of alerts as needed
				if (Properties.IOS_VERSION.startsWith("9")) {
					Alert a = AppiumDriverInstance.getInstance().switchTo().alert();
					try {
						AppiumDriverInstance.getInstance().findElement(By.id(Element.ALERT_OK_ALL_CAPITAL_NAME))
								.click();
					} catch (Throwable t) {
						throw new RuntimeException(
								"Alert displayed, but not handled in acceptAllAlerts (and it should be :) ) since this is iOS9 running on Appium 1.4.8. Alert: "
										+ a.getText());
					}
				} else {
					AppiumDriverInstance.getInstance().switchTo().alert().accept();
				}
			}
		} catch (Throwable t) {
			// do nothing
		}
	}

**Comment by vjmaiky** [comment]
but as Mykola said...there is painfull bug for landscape...everything works in Portrait, but on landscape all is gone...i§m trying to find also an workaround..i have over 600 tests and i don§t want to refactor the login part because there are dependencies....

**Comment by jlipps** [comment]
Please report the xcuitest alert + landscape bug to Apple!

**Comment by SamyQAZ** [comment]
seems I got same issue with portrait mode, inspector cannot locate and click pop-up alerts.

Hope they fix it soon or have some work around for it. This issue stopped iOS automation for me :(

**Comment by Thialison** [comment]
In your Env put the capabilities => autoGrantPermissions: true.
By default the Grant Permissions are disable.

**Comment by SamyQAZ** [comment]
@Thialison Will try it, hope it works

**Comment by SamyQAZ** [comment]
@Thialison Tried, still no luck

Below are my capabilities,
<img width="1207" alt="screen shot 2017-12-27 at 2 57 30 pm" src="https://user-images.githubusercontent.com/30425316/34373543-a361a38a-eb16-11e7-9626-9744d47035a1.png">

**Comment by Thialison** [comment]
@SamyQAZ Look at this link: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md
I use this link to see all caps available for Android, iOS or both.

**Comment by SamyQAZ** [comment]
@Thialison Yes I am using the same page to look for capabilities. 
However after using autoGrantPermissions=True I still can see the pop-up appearing and tests fail as currently I am unable to click on it.

**Comment by valerybugakov** [comment]
I've resolved this issue using:
```js
driver.execute('mobile:alert', { action: 'accept' });
```

**Comment by SamyQAZ** [comment]
@valerybugakov it worked this morning with iphone8 11.0.2 no idea how.``` *_*```
Glad that it worked phewww, I just added sleep time after clicking allow to wait for page to load. However earlier it failed  when it couldn't locate allow button.
Will try with other devices and see if it works.

**Comment by SamyQAZ** [comment]
Any updates on this issue, seems it only happens for iOS 10.X devices. It works as expected for iOS 11.0.2 device.

I suspect it is leading from AX error -25205 issue. Does anyone encountered the same?

**Comment by jbMiracle** [comment]
Thanks valerybugakov, your resolution for handling the alert in JavaScript worked for me

**Comment by ivanzotov** [comment]
@valerybugakov thank you so much, it works

**Comment by narendra-chandratre** [comment]
Solution suggested by @valerybugakov is for XCUITest also? anybody tried?

**Comment by narendra-chandratre** [comment]
Modified for Python:
`Driver.Instance.execute_script('mobile: alert', {'action': 'accept', 'buttonLabel': 'Allow'})`

**Comment by Storehub-Divya** [comment]
> driver.execute_script('mobile: alert', {'action': 'accept', 'buttonLabel': 'Allow'})

It worked for me. Thanks :)

**Comment by raaghuler** [comment]
I am trying to use this code but I am facing invalid character constant, Please help ou to resolve this

Attached the screenshot
![Screen Shot 2019-05-15 at 12 34 40 PM](https://user-images.githubusercontent.com/29144150/57755264-165dbc00-770e-11e9-95f9-414457edb0d6.png)

**Comment by HimabinduKethireddy** [comment]
I have the same problem with V1.13 and with Mac OS. could someone help me out. Thanks in Advance

**Comment by bjoernuhlig** [comment]
> device.acceptAlert() <
worked for me

**Comment by HimabinduKethireddy** [comment]
didn't worked.


please find the screenshot attached . I want to accept that thru code. could u help me out


Himabindu Kethireddy
Quality Assurance Engineer



iHaus AG
Siedlerstrasse 2
D - 85774 Unterföhring


Web:  ihaus.com

**Comment by bjoernuhlig** [comment]
> didn't worked. please find the screenshot attached . I want to accept that thru code. could u help me out Himabindu Kethireddy Quality Assurance Engineer iHaus AG Siedlerstrasse 2 D - 85774 Unterföhring Web:  ihaus.com From: Björn Uhlig <notifications@github.com> To: appium/appium <appium@noreply.github.com> Cc: HimabinduKethireddy <himabindu.kethireddy@ihaus.de>, Comment <comment@noreply.github.com> Sent: 22/08/2019 2:55 PM Subject: Re: [appium/appium] Can't click on 'Allow' button on Notification popup at startup on IOS (#7949) device.acceptAlert() < worked for me — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Hi
I am using it with browserstack and webdriverio, my device is a  webdriverio browserobject
( declare var browser: WebdriverIOAsync.BrowserObject; ) 

  it('test-1', () => 
    if(browser.isIOS) {
      console.log(browser.getAlertText());
      browser.acceptAlert();
    }
  });

maybe helps...
