### ISSUE TITLE
IOS parallel testting " internal error - operation timed out"

### ISSUE THREAD

**Issue by Lightmoor** [appium/appium#7951]
## The problem

Hi, 

we try to run parallel testing on iOS Devices. 

Appium crashed when two test run parallel.

## Environment

* Appium version: 1.6.3 & 1.6.4 Beta
* Desktop OS/version used to run Appium: macOS Sierra (10.12)
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test: IOS
* Real device
* Appium CLI
* Selenium: 2.53.1

## Details

Appium crashed when two test run parallel. 
When test run serial it works fine.

## Link to Appium logs

https://gist.github.com/Lightmoor/f8d14e340299b9e2eb03680dff2da4c1

**Comment by imurchie** [comment]
This is to be expected. Appium does not currently support parallel iOs testing.
