### ISSUE TITLE
XCUISiriService is partial: introduced in iOS 10.3 XCUIDevice.h

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#7952]
Trying to compile the WebDriver Agent Project with XCode 8.3 Beta 3., Appium Version 1.6.3

AIM: To run automation on iOS 10.3 Beta 3 Device

Any help is appreciated

**Comment by mykola-mokhnach** [comment]
Not gonna happen. You will need 1.6.4-beta to run recent WDA release

**Comment by pavanbachu0604** [comment]
How do i install Appium 1.6.4 Beta once i download it from Github ?

**Comment by mykola-mokhnach** [comment]
what is "this issue". It would not hurt to be more specific and provide some logs, etc.

**Comment by pavanbachu0604** [comment]
Steps followed : 
1. Install appium 1.6.4 beta using : npm install -g@appium-beta 
2. Point to WebDriver Agent Port : cd /usr/local/lib/node_modules/appium/node_modules/appium-cuitest-driver/WebDriverAgent
3. Install the dependencies: /bin/bash Scripts/bootStrap.sh -d 
4. Open WDA project and choose the "Automatic Signing" and choose Developer Account.
5. When I compile the Xcode Project, I am observing the following error


<img width="1132" alt="screen shot 2017-02-28 at 11 08 09 am" src="https://cloud.githubusercontent.com/assets/21222084/23492752/90188f7a-fed4-11e6-9f2f-17e8eb09308e.png">

**Comment by mykola-mokhnach** [comment]
Please forward the issue to https://github.com/facebook/WebDriverAgent/issues
Or, probably, @marekcirkos can comment on this report if he has time.

**Comment by marekcirkos** [comment]
This is `unguarded-availability` being marked as error. I think this is Apple's issue of organising headers. Probably you can fix it by changing deployment target to iOS 10.3

**Comment by mykola-mokhnach** [comment]
Closing as non Appium-related problem

**Comment by laiyuncong8404** [comment]
I've got this issue too.
Appium@1.6.4-beta
Xcode@8.3
OSX:10.12.3

**Comment by BasThomas** [comment]
I am seeing this issue as well. @marekcirkos, changing the Deployment Target does not resolve the issue.

**Comment by dipakingale** [comment]
I am trying to automate the hybrid application on iOS 10 device and after installation trying to build the WebdriverAgentLib in XCode and received this error.

Can anyone tell me how to explicitly redeclare 'XCUISIRIService' to silence this warning.

**Comment by mykola-mokhnach** [comment]
Try the patch from https://github.com/facebook/WebDriverAgent/pull/525

**Comment by garkinv** [comment]
@marekcirkos thanks, you suggestion helped me.

@BasThomas Just change deployment target for "WebDriverAgentRunner" and "WebDriverAgentLib" targets

**Comment by dipakingale** [comment]
After resolving above issue now i'm getting the following issue while building WDA in xcode :

Deprecations : /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Commands/FBSessionCommands.m:55:43: 'openURL:' is deprecated: first deprecated in iOS 10.0 - Please use openURL:options:completionHandler: instead

Line :
if (![[UIApplication sharedApplication] openURL:url]) {
return FBResponseWithErrorFormat(@"Failed to open %@", url);
}
Could you please help me??

**Comment by skumar1122** [comment]
Hi @garkinv , @dpgraham ...

re:#8132

It looks I had similar issue today with new version. I even tried with iOS 10.3 on iPhone7 with Appium beta version in Xcode 8.3.
I am getting again error this time bit different.

When I run build command:

> CompileC /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBElementCache.o WebDriverAgentLib/Routing/FBElementCache.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
>     cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent
>     export LANG=en_US.US-ASCII
>     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/skumar/Library/Android/sdk/tools:/Users/skumar/Library/Android/sdk/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch arm64 -fmessage-length=159 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/skumar/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/skumar/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -fno-common -Werror -Wmissing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Warc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wunused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -pedantic -Wshadow -Wno-four-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wassign-enum -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=10.3 -g -Wno-sign-conversion -Winfinite-recursion -iquote /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-generated-files.hmap -I/Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-own-target-headers.hmap -I/Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-all-target-headers.hmap -iquote /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/WebDriverAgentLib-project-headers.hmap -I/Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/libxml2 -I/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Modules -I/Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/DerivedSources/arm64 -I/Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/DerivedSources -Weverything -Wno-objc-missing-property-synthesis -Wno-unused-macros -Wno-disabled-macro-expansion -Wno-gnu-statement-expression -Wno-language-extension-token -Wno-overriding-method-mismatch -Wno-missing-variable-declarations -Rno-module-build -Wno-auto-import -Wno-objc-interface-ivars -Wno-documentation-unknown-command -Wno-reserved-id-macro -Wno-unused-parameter -Wno-gnu-conditional-omitted-operand -Wno-explicit-ownership-type -Wno-date-time -Wno-cast-align -Wno-cstring-format-directive -Wno-double-promotion -F/Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -F/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/iOS -F/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Carthage/Build/Mac -MMD -MT dependencies -MF /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBElementCache.d --serialize-diagnostics /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBElementCache.dia -c /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Routing/FBElementCache.m -o /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBElementCache.o
> 
> 2017-03-30 19:11:07.787 xcodebuild[4884:713362] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/C4A86192-B212-4E00-8128-8A99A637E106/Session-WebDriverAgentRunner-2017-03-30_191106-fpVAGJ.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/C4A86192-B212-4E00-8128-8A99A637E106/Session-WebDriverAgentRunner-2017-03-30_191106-fpVAGJ.log}
> 
> Testing failed:
> 	'openURL:' is deprecated: first deprecated in iOS 10.0 - Please use openURL:options:completionHandler: instead
> ** TEST FAILED **
> 
> 
> The following build commands failed:
> 	CompileC /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Intermediates/WebDriverAgent.build/Debug-iphoneos/WebDriverAgentLib.build/Objects-normal/arm64/FBSessionCommands.o WebDriverAgentLib/Commands/FBSessionCommands.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)


Xcode ScreenShot:

![image](https://cloud.githubusercontent.com/assets/20112173/24519838/373478c2-157e-11e7-87b2-8d04608376dd.png)

Please let me know for any changes.

**Comment by imurchie** [comment]
Can you update your Appium installation and make sure that you have `appium-xcuitest-driver@2.25.0`

**Comment by dkdodson3** [comment]
I am unable to build the WDA. XCUISiriService is partially introduced and could not build module XCTest.

appium@1.6.4-beta.2
appium-xcuitest-driver@2.25.0
Xcode@8.3
OSX:10.12.3

**Comment by skumar1122** [comment]
@imurchie 
I have updated Appium and pulled latest appium-xcuitest-driver@2.25.0,

when I am building WDA I am getting error again as below , 
https://gist.github.com/skumar1122/0e04d8f01db4cac05e8ff573a80b5b1e


Also WDA logs: 

> BMH00:EC0551E0-6659-4DA6-BA3E-EE0720B347A3 skumar$ vi Session-WebDriverAgentRunner-2017-03-30_205333-Yg0Tg6.log 
> 
>     1
> )
>                 applications:              (null)
>                 provisioningProfiles:      (null)
>                 activityProgress:          -2
>                 activityTitle:
>                 hasInternalSupport:        NO
>                 isSupportedOS:             YES
>                 developerDiskMountError:   (null)
> (null)
>         bootArgs:                  <unavailable>
>                 } (10.3 (14E277))
> 20:53:33.136 xcodebuild[8810:849744]    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
> -project
> WebDriverAgent.xcodeproj
> -scheme
> WebDriverAgentRunner
> -destination
> id=47b562c6a454e596df5583e1ff6743afe785de45
> test
> 20:53:33.136 xcodebuild[8810:849744] Launching with Xcode.IDEFoundation.Launcher.PosixSpawn
> 20:53:33.205 xcodebuild[8810:849745] Connecting to mobile device: 47b562c6a454e596df5583e1ff6743afe785de45
> 20:53:33.211 xcodebuild[8810:849745] Starting session with mobile device
> 20:53:33.257 xcodebuild[8810:849745] Starting test manager service on mobile device.
> 20:53:33.264 xcodebuild[8810:849750] Received connection for test runner session
> 20:53:33.264 xcodebuild[8810:849750] Listening for proxy connection request from the test bundle
> 20:53:33.264 xcodebuild[8810:849744] Test runner session acquired connection.
> 20:53:33.264 xcodebuild[8810:849744] Waiting for test process to launch.
> 20:53:33.264 xcodebuild[8810:849750] Initiating session with identifier: DC463D52-E980-47A3-A903-04DDF8CFBB79
> 20:53:33.293 xcodebuild[8810:849750] Got reply to session initiation request with identifier DC463D52-E980-47A3-A903-04DDF8CFBB79 (result:error): 22: (null)
> 20:53:34.857 xcodebuild[8810:849744] Test operation failure: Test operation was canceled.
> 20:53:34.857 xcodebuild[8810:849744] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled." UserInfo={NSLocalizedDescription=Test operation was canceled.} didCancel: 1

let me know for any other things?

Thanks
SK

**Comment by skumar1122** [comment]
Hi @imurchie ,

After few tries , I managed to build success from XCODE and created a new project and name as some Test and ran successfully(Test ran on iPhone7) for the first time but Its bit intermittent, failed second opens WDA app and goes to appium site and stays ideal. Sorry If I am not clear, I am bit lost here. 

Can you please check the logs if you could find anything for me.

https://gist.github.com/skumar1122/76b5ca00d18914aa673569b41d529ac0

Thanks
