### ISSUE TITLE
[Appium 1.6.4(beta)] :: Real device test does not proceed until Safari browser is manually opened

### ISSUE THREAD

**Issue by JESii** [appium/appium#7953]
## The problem

I am running ruby/cucumber tests against a mobile web page (not an app). The test hits the device (iPad 9.3.5) and flashes the device when installing WebDriverAgent. However, it never proceeds to the requested homepage and times out with a Net::ReadTimeout

The test runs successfully on my local machine as well as on the iOS Simulator.

## Environment

* Appium version (or git revision) that exhibits the issue:
1.6.4(beta)
* Last Appium version that did not exhibit the issue (if applicable):
N/A - Only have iOS simulator running
* Desktop OS/version used to run Appium:
OS X El Cap; 10.11.6
* Node.js version (unless using Appium.app|exe):
7.5.0
* Mobile platform/version under test:
iOS 9.3
* Real device or emulator/simulator:
Real device
* Appium CLI or Appium.app|exe:
appium CLI
* Xcode version:
8.2.1

#### Additional environment details

* appium-ios-driver@1.16.0 (installed with -g option)
* appium-xcuitest-driver@2.7.0 (installed with -g option)
* authorize-ios@1.0.4 (installed with -g option)
* ios-deploy@1.9.1 (installed with -g option)
* ios_webkit_debug_proxy@ 1.7.1, Built with libimobiledevice v1.2.0, libplist v1.12
* libimobiledevice: stable 1.2.0 (bottled), HEAD
* ideviceinstaller: stable 1.1.0 (bottled), HEAD
* .xcconfig created with:
`DEVELOPMENT_TEAM = XXXXXXXXXX`
`CODE_SIGN_IDENTITY = iPhone Developer`
`IOS_INSTALL_PAUSE = 3000`
* iPad Apps installed during the test process
`WebDriverAgentRunner version 1, com.apple.test.WebDriverAgentRunner-Runner`

#### Symptoms
* The test begins running, the WebDriverAgent is built and loaded, and I can see the device / Safari reacting: Starting from Safari, the device slides Safari out of the way, displays a completely black screen, then goes to the home screen.

* The sever gets to the POST command and sits there waiting...

* Eventually the test times out. (Logs attached below)

However, if I manually tap Safari on the device, then the test proceeds as expected, loading the webpage, etc.

##### Appium server

`appium -g ~/appium_server.log --log-timestamp --local-timezone --debug-log-spacing --tmp ~/tmp --default-capabilities '{"showXcodeLog": true, "automationName": "XCUITest", "cssSelectorsEnabled": true, "nativeWebTap": true, "nativeEvents": true, "autoWebView": true}'`

##### ios_webkit_debug_proxy

`ios_webkit_debug_proxy -c xxxUDIDxxx:27753 -d running in another terminal window and connected to my device ("JON's iPad")`

##### Cucumber test

`bundle exec cucumber DEVICE=Iphone -p mobile_website_default SITE=XXX URL=http://XXX.com/ features/website/Selection/MEW/registry/MCOM/registry_navigation.feature:14`

## Link to Appium logs

https://gist.github.com/JESii/c7c2ac21c3d1f3aaeab9defc42495434

Appium log with showIOSLog = true
https://gist.github.com/anonymous/8ae1b6db3d4664c999dbf0a6417f44c9

## Code To Reproduce Issue [ Good To Have ]

Testing mobile web, not mobile app

**Comment by mykola-mokhnach** [comment]
It would be useful to see the log from the device. There should be some errors for sure.

**Comment by mykola-mokhnach** [comment]
btw. appium-ios-driver and appium-xcuitest-driver components are installed (and updated) together with Appium beta package. There is no need to install them separately.

**Comment by JESii** [comment]
OK, @mykola... new log with showIOSLog = true added to the issue

**Comment by mykola-mokhnach** [comment]
> 2017-02-28 13:06:46:240 - info: [iOSLog] [IOS_SYSLOG_ROW] Feb 28 13:06:46 JONs-iPad SpringBoard[48] <Warning>: [FBSystemService] Error launching com.apple.mobilesafari: Busy (6)

Looks like it's something on your device. What if you use some other device?

**Comment by JESii** [comment]
Same thing has happened with an iOS 10.0 device... and the only thing that makes a difference is that I tap on the Safari icon on the device and then the test takes off...

**Comment by imurchie** [comment]
Can you:
1. Fix the `xcodeConfigFile` capability to point to an existing xcconfig file
2. Delete the build of WebDriverAgent so that a new build is created? (this should be in `/Users/<USER>/Library/Developer/Xcode/DerivedData/` as `WebDriverAgent-<something>`).

And then rerun the test, to get everything built and up-to-date on the device.

**Comment by JESii** [comment]
Will do; thanks.

**Comment by JESii** [comment]
OK; deleted the existing WDA build and re-ran as you suggested:
Appium command line:
` appium -g ~/appium_server.log --log-timestamp --local-timezone --debug-log-spacing --tmp ~/tmp --default-capabilities '{"showXcodeLog": true, "xcodeLogFile": "/Users/yc98js1/.xcconfig", "showIOSLog": true, "automationName": "XCUITest", "webStorageEnabled": true, "cssSelectorsEnabled": true, "nativeWebTap": true, "nativeEvents": true, "autoWebView": true}'`

New appium logs:
https://gist.github.com/JESii/46a391a69ca5c1a79f7082e63e908288

I see the 'busy' status.
However, I don't understand why that would be something wrong on my device -- all I have to do is tap on the Safari icon to open the browser and the test then gets past this point and runs successfully.

**Comment by imurchie** [comment]
It _is_ weird. Unfortunately I don't have access to a 9.3 read device to test. 

Does it make a difference if Safari is already running, or fully quit?

**Comment by JESii** [comment]
Re: "fully quit"- isn't that a non-starter because Safari needs to be started to load the WDA? I will try running the test when I stop Safari (double-tap home and swipe up on Safari) and let you know what I find.

Re: "access to 9.3 device" - I have a 10.0 device and will run the same test there and let you know.

**Comment by JESii** [comment]
Well... Safari must have been corrupted somehow because now it works (3 x in a row), even though there was nothing visible running on it.

Interesting that the appium.io page was NOT showing up prior to forcibly shutting down Safari, and now on these tests it did show up before moving on to the test. I'll make a note of that for a possible future indicator of problems... along with the IOSLog and the 'busy' signal

thanks very much!

**Comment by imurchie** [comment]
I'm glad it started working! Apple works in mysterious ways sometimes.

**Comment by JESii** [comment]
Fur sure... 

is there an automated method for completely shutting down Safari before the test, or from Appiuj? I had thought the fullReset option would do that? I had used that in the past but it didn't seem to help?

**Comment by mykola-mokhnach** [comment]
With real real device it's always tricky. On simulator we can do more, but here we can only rely on some "partially-official" methods, which are not directly supported by Apple. So you know who to blame ;)
