### ISSUE TITLE
appium-ios-inspector is Not recognizing SVG tags and its child elements

### ISSUE THREAD

**Issue by umarao** [appium/appium#7955]
I tried to identify elements using appium-ios-inspector.

In the page almost all the elements got recognized.
When I select starting point and end point automatically a new line drawn.
Not able to identify locators for this in appium ios inspector.

I am able see the elements in windows chrome browser(application is same angular js developed application)

SVG tag and its sub tags are not identified with appium ios inspector

**Comment by mykola-mokhnach** [comment]
@jlipps do we want to collect inspector issues here of in https://github.com/appium/appium-desktop/issues?
I'd prefer to keep them separately.

**Comment by vikramvi** [comment]
@umarao  please open new issue related to Appium Desktop at https://github.com/appium/appium-desktop/issues

@triager please close
