### ISSUE TITLE
Appium-adb doesn't support android-sdk-tools 25.3.1

### ISSUE THREAD

**Issue by xuanzhaopeng** [appium/appium#7961]
## The problem

Android-adb use command $ANDROID_HOME/tools/android list avd -c  to detect the available avd. However since android sdk tools 25. (maybe 24),  the command "android" is obsoleted, that replaced by tools/bin/avdmanager and tools/bin/sdkmanager

## Environment
Appium 1.6.3, installed by nodejs.

Reference source code : https://github.com/appium/appium-adb/blob/master/lib/tools/system-calls.js#L427

**Comment by mykola-mokhnach** [comment]
you could create a PR with a fix. We'd be happy to review ;)

**Comment by mykola-mokhnach** [comment]
Linking https://github.com/appium/appium-adb/pull/200

**Comment by xuanzhaopeng** [comment]
Fixed by the PR above.
