### ISSUE TITLE
Switching native app to browser and back to native app

### ISSUE THREAD

**Issue by bnimmagadda** [appium/appium#7963]
## The problem

We have ios native app which launches browser at certain action.

Does Appium support switching between native app and broswer?
Perform some action in browser and switch back to native app.

Please let me know if it is possible. I have read somewhere that it is not possible due to limitation from Apple. 

Thanks
Bindu

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for howto question. This is the place for issue.

I'd use separate automation for a native app and for a browser unless web pages are opened in the built-in webview inside the app.
