### ISSUE TITLE
.pageSource() return only base classes

### ISSUE THREAD

**Issue by mstrelex** [appium/appium#7964]
## The problem

Can't get the real class name (tag name) of a custom widget.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: OSX
* Node.js version (unless using Appium.app|exe): 7
* Mobile platform/version under test: Android 7.1
* Real device or emulator/simulator: Device (Nexus 6P)

## Details

Returned XML for .pageSource() shows only base Android tag names, and not custom tag name. 

For example, for this App https://github.com/chenupt/SpringIndicator the layout should have `github.chenupt.springindicator.SpringIndicator` node but it's returned as `FrameLayout` that this custom widget extends.

I understand that this is a UIAutomator limitation, but is there any way to overcome this ?

Thanks.

**Comment by dpgraham** [comment]
I doubt it. I don't think UIAutomator can access that info.

@sravanmedarapu Do you know the answer?
