### ISSUE TITLE
LockDevice() not implemented for iOS devices. is there any way available to automated LockDevice for iOS?

### ISSUE THREAD

**Issue by PriyankaMittal2017** [appium/appium#7967]
## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Appium). Tell us what you were trying to do and what happened instead. Remember, this is _not_ a place to ask questions. For that, go to http://discuss.appium.io!

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by SrinivasanTarget** [comment]
@PriyankaMittal2017 Can you give us more info asked above? Which version you are trying client, server & iOS version?

**Comment by amedvedjev** [comment]
@SrinivasanTarget 
1.6.4-beta, java-client: 5.0.0-BETA4
```
((IOSDriver)driver).lockDevice(1);
```
->
org.openqa.selenium.WebDriverException: Method has not yet been implemented 

@PriyankaMittal2017 
for Simulator ONLY!
```
    public void lockUnlockScreen() {
        System.out.println("    lockUnlockScreen()");
        //((IOSDriver) driver).lockDevice(2); // not implemented
        tapLockButton();
        sleep(1);
        tapHomeButton();
        sleep(1);
        tapHomeButton();
    }

    public void tapLockButton() {
        System.out.println("    tapLockButton()");
        try {
            String[] cmd = {"osascript", "-e", "tell application \""+simulatorAppName()+"\"\n" +
                    "    activate\n" +
                    "end tell\n" +
                    " \n" +
                    "tell application \"System Events\"\n" +
                    "    tell process \""+simulatorAppName()+"\"\n" +
                    "        tell menu bar 1\n" +
                    "            tell menu bar item \"Hardware\"\n" +
                    "                tell menu \"Hardware\"\n" +
                    "                    click menu item \"Lock\"\n" +
                    "                end tell\n" +
                    "            end tell\n" +
                    "        end tell\n" +
                    "    end tell\n" +
                    "end tell"};
            executeShell(cmd);
            try{Thread.sleep(500);}catch (Exception e1){}
        } catch (Exception e) {}
    }

    public void tapHomeButton() {
        System.out.println("    tapHomeButton()");
        try {
            String[] cmd = {"osascript", "-e", "tell application \""+simulatorAppName()+"\"\n" +
                    "    activate\n" +
                    "end tell\n" +
                    " \n" +
                    "tell application \"System Events\"\n" +
                    "    tell process \""+simulatorAppName()+"\"\n" +
                    "        tell menu bar 1\n" +
                    "            tell menu bar item \"Hardware\"\n" +
                    "                tell menu \"Hardware\"\n" +
                    "                    click menu item \"Home\"\n" +
                    "                end tell\n" +
                    "            end tell\n" +
                    "        end tell\n" +
                    "    end tell\n" +
                    "end tell"};
            executeShell(cmd);
            try{Thread.sleep(500);}catch (Exception e1){}
        } catch (Exception e) {}
    }

    public static String simulatorAppName() {
        return "Simulator";
    }
```

**Comment by imurchie** [comment]
There is currently no way to lock the screen for iOS 10+. Apple hasn't provided a way to do it.

**Comment by mykola-mokhnach** [comment]
@amedvedjev WDA provides more convenient way to tap Home button. There is an endpoint for it (not sure about how it is wrapped in Appium)

**Comment by amedvedjev** [comment]
@mykola-mokhnach 
you mean below? if it is real TAP on home that is nice. Will add FR. thanks.
```
curl -X POST $JSON_HEADER -d "" $DEVICE_URL/wda/homescreen
```

**Comment by mykola-mokhnach** [comment]
I think there is nothing more to add here
