### ISSUE TITLE
Inspector is not able to locate elements of application on UIView

### ISSUE THREAD

**Issue by omkara120120** [appium/appium#7969]
Hello,

One toggle button and one label is there on my application screen, and these elements are designed using OR related to "UIView". Problem is Inspector is not able to find these elements i.e no information is being displayed on inspector - but I am able to see these two element on screenshot shown by inspector but entry of these elements are not present in element hierarchy displayed on inspector 

I tried three different inspectors
- Appium inspector  (of older version of appium)
- Appium-iOS-Inspector
- Webdriver agent - Accessibility Inspector  

## Environment

* Appium version : 1.6.3
* Desktop OS/version used to run Appium: 10.12 (16A323)
* npm version : 3.10.9
* Mobile platform/version under test: 10.0.2(14A456) 
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

Please let me know, is there any way to locate such elements which are designed differently?
Is there any need to switch driver on that view ?

**Comment by mykola-mokhnach** [comment]
It might be a developer should to make these elements accessible explicitly ion the source code. Just check whether they are visible or not in built-in iOS accessibility inspector to make sure.

**Comment by vikramvi** [comment]
@omkara120120 can you try with https://github.com/appium/appium-desktop and open issue in that repo in case you still see the problem.

**Comment by omkara120120** [comment]
@vikramvi Thank you for suggestion, I'll try this inspector

**Comment by omkara120120** [comment]
@vikramvi - I have downloaded the folder of - appium-desktop - but there are not clear instruction how to use it..Can u please guide, What needs to be done after downloading this folder

**Comment by vikramvi** [comment]
@omkara120120 goto above link and carefully go through each of the instructions in README. It has got all the info needed

**Comment by vikramvi** [comment]
@triager  please close

**Comment by omkara120120** [comment]
This is what I am getting after clicking on Start new session - I am running my test on real device

Error
An unknown server-side error occurred while processing the command. Original error: Sdk '10.0.2(14A456)' was not in list of simctl sdks


Capabilities I have set:
platformName = iOS
app = <My app's path>
automationName = XCUITest
UDID = <UDID of my real ipad decvice>
bundleID = <My app's bunddle ID>
platformVersion = 10.0.2(14A456)
deviceName = <Name of my ipad>

**Comment by vikramvi** [comment]
@omkara120120 please file under https://github.com/appium/appium-desktop

**Comment by ludo550** [comment]
I am still getting this issue. I have used the Macaca app-inspector, Mykola app-Inspector, Appium's new inspector and also the driver.PageSource(); way with the same heirarchy of elements which don't show any static texts, edit texts or buttons. It only shows Type other. The XCode accessibility inspector shows each elements' property when highlighted but the heirarchy is not usable and the use is very limited. I can search for each element in the appium inspector with class names but they don't show up on the xml heirarchy. Please help, Will share sample xml soon.
