### ISSUE TITLE
Appium 1.6.3: Swiping fails using java-client 3.3.0. On Java-Client 4.1.2, it is able to swipe but in few cases it zooms the text present on the screen

### ISSUE THREAD

**Issue by abh7nav** [appium/appium#7971]
## The problem

Swiping fails, on trying to swipe vertically for duration of 1000 ms using java-client 3.3.0

Using Java-Client 4.1.2, it is able to swipe but it some cases where text it on the screen, it presses on the screen and causes text to get zoomed and hence not able to swipe. Earlier using Java-client 3.3 and Appium older versions this kind of issue never occurred.

Also, it do not give any error. It just zooms in on text.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: Mac OS sierra
* Node.js version (unless using Appium.app|exe): 7.5
* Mobile platform/version under test: ios 10
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: CLI

## Details

Swiping fails, on trying to swipe vertically for duration of 1000 ms using java-client 3.3.0

Using Java-Client 4.1.2, it is able to swipe but it some cases where text it on the screen, it presses on the screen and causes text to get zoomed and hence not able to swipe. 

For ex: After signing on to google drive there is one option to click on Allow for which it has to scroll down but instead of scrolling it zooms in.

Earlier using Java-client 3.3 and Appium older versions this kind of issue never occurred.

Also, it do not give any error. It just zooms in on text.

I have now written wrapper to execute "mobile:scroll" command but it scrolls down to bottom of screen. I tried using "mobile: scroll" command to scroll till element is visible but it does not work.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

AppiumConnection.driver.swipe(500, 500 + 200, 500, 500 - 150,  1000);

**Comment by vikramvi** [comment]
@abh7nav can you please try with latest versions and update here.

Even I'm facing similar issue, for details refer to https://github.com/appium/appium/issues/7914
