### ISSUE TITLE
ensure all drivers correctly call super.getSession

### ISSUE THREAD

**Issue by jlipps** [appium/appium#7974]
To ensure the timing framework will not get overridden.

**Comment by dpgraham** [comment]
I just did a search in Appium org for all instances of 'getSession' (https://github.com/search?p=1&q=org%3Aappium+getSession&type=Code&utf8=%E2%9C%93)

It looks like `appium-xcuitest-driver` is the only driver to call `getSession` and it does indeed call `super.getSession`

Are there any other drivers outside of the Appium org that extend `appium-base-driver`?

**Comment by imurchie** [comment]
https://github.com/YOU-i-Labs/appium-youiengine-driver

**Comment by dpgraham** [comment]
I just had a look at that one and it doesn't override `getSession`
