### ISSUE TITLE
XCUITest command xcodebuild build-for-testing test-without-building -project runs in wrong folder

### ISSUE THREAD

**Issue by guizeferino** [appium/appium#7976]
## The problem

I'm starting appium Server with the latest beta release, then I'm launching the inspector via Appium GUI on a real device. Every previous problems I've got solved, but there is a XCUITest command running in the wrong foder and I can't change it. 

When Launching Inspector, XCUITest command launches the output "Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=7640a631710d0182031c0c27ce2ee641a8551cbe -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'"

 but I know this is not the appium folder. 

Later on the terminal, the test fails and xcode launches the message [Xcode] 2017-03-04 19:56:15.637 xcodebuild[33790:490589] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/guilhermedossantoszeferino/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7f8453edddf0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

As long as I understood, it's not possible to find the WebDriverAgentRunner-Runner.app, because the WebDriverAgent.xcodepro is in another folder: /Users/guilhermedossantoszeferino/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

So how do I force the XCUITest command to run in the right folder? Or there is a better workaround?

## Environment

* Appium v1.6.4-beta
* MacOS Sierra 10.12.3
* Node.js v6.10.0
* Iphone 5S/iOS 10.2.1
* Appium GUI Version 1.5.3

## Link to Appium logs

https://gist.github.com/guizeferino/5fc54c24a7fd0e4b12264823f10296ef

**Comment by imurchie** [comment]
If you are running Appium from the global command, then the location is most likely right. The error not being able to find `WebDriverAgentRunner-Runner.app` is most often caused by a signing issue. If you use the `showXcodeLog` capability (set to `true`) the real error will be evident in the logs.

**Comment by guizeferino** [comment]
@imurchie problem is I'm new on appium tests and I don't know how to set capabilities. I see this term in most discussions and I don't have a clue of what capabilities are or how to find/edit them. As the log shows, I'm running the tests on a .ipa file, not a project where I can edit :/

**Comment by imurchie** [comment]
The "desired capabilities" are a hash of key-value pairs sent in when you create a session. I'm not sure what language or client you are using, so it is hard to say how to do it exactly. [Here](http://www.guru99.com/desired-capabilities-selenium.html) is a bit of a discussion on the subject: http://www.guru99.com/desired-capabilities-selenium.html

**Comment by guizeferino** [comment]
Ok, after a long research, the only way I found is to create a project and put the desired capabilities on the project. So I am going to try this way, rather to just executing the .ipa
