### ISSUE TITLE
Not able to perform LongPress and Drag to element on IOS Native application using XCUITest (Appium)

### ISSUE THREAD

**Issue by TARIFABBAS** [appium/appium#7978]
## The problem

There are some buttons in IOS application that are visible after longPress and need to be drag on those button to actually work on them.

## Environment

* Appium version 1.6.3
* Xcode version 8.2
* Mac 10.11.6
* IOS version 10.2

## Code To Reproduce Issue 

Take any native application, where after long press some more buttons like play video or add comments is visible and manually we need to drag on those button to actually worked.
Same scenario i am struck in. I have use 'MultiTouch' class for this but getting error that This action is not yet implemented.

Can anyone help me out to handle this scenario.

**Comment by imurchie** [comment]
Ok. What have you tried and what is the outcome?

**Comment by TARIFABBAS** [comment]
I have tried below code and got the error::
_new TouchAction(LaunchIOSApplication.driver).longPress(50, 50).moveTo(100, 100).release().perform();_

_**org.openqa.selenium.WebDriverException**: Support for this gesture is not yet implemented. Please contact an Appium dev_ (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 25 milliseconds
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:11:55'
System info: host: 'CTND1147', ip: '172.17.20.18', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_112'
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities [{app=/usr/local/Astro_8_0_6.ipa, rotatable=true, networkConnectionEnabled=false, launch=true, xcodeConfigFile=/usr/local/appium.xcconfig, databaseEnabled=false, deviceName=iPad, launchTimeout=90000, appPath=/usr/local/Astro_8_0_6.ipa, platform=MAC, wdaLocalPort=8200, newCommandTimeout=3000, realDeviceLogger=/usr/local/lib/node_modules/deviceconsole/deviceconsole, webStorageEnabled=false, locationContextEnabled=false, automationName=XCUITest, browserName=, takesScreenshot=true, javascriptEnabled=true, udid=f354a07f20184c92bbcfdcc5bbfbc6a8d25385eb, platformName=iOS}]
Session ID: 2539a88e-05b1-4729-bfb8-179bf9c3d32d
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
	at io.appium.java_client.AppiumDriver.performTouchAction(AppiumDriver.java:314)
	at io.appium.java_client.TouchAction.perform(TouchAction.java:301)
	at com.tarif.appiumIOS.CommandExecute.longPressAndMove(CommandExecute.java:96)
	at com.tarif.appiumIOS.CommandExecute.Command(CommandExecute.java:87)
	at com.tarif.appiumIOS.GreetingServer.run(GreetingServer.java:28)

**Comment by mykola-mokhnach** [comment]
this should be implemented in WDA first (https://developer.apple.com/reference/xctest/xcuicoordinate/1615003-press)

**Comment by mykola-mokhnach** [comment]
OK, it looks like it is implemented in WDA _/wda/dragfromtoforduration_ endpoint, parameter _duration_. 
So, Appium is missing it.

**Comment by mykola-mokhnach** [comment]
@imurchie FYI

**Comment by mykola-mokhnach** [comment]
@TARIFABBAS Can you try to replace _longPress_ call with _press_ + _wait_ calls? This should work
@SergeyTikhomirow @imurchie How about deprecating _longPress_ touch action or replacing downstream events with _press + wait_ sequence to make it simpler?

**Comment by jerrytom2020** [comment]
Hi @mykola-mokhnach ,

I'm too encountering the above issue. Quick summary, I was able to swipe up in the app by using "driver.swipe(75,500,75,0,800)" in Appium 1.6.3. However when I attempted to swipe down using "driver.swipe(75,30,75,250,800)" it swipes but it takes almost 5 minutes to perform the swipe action and then I came across this above reported issue by @TARIFABBAS which is much related.
Further I upgraded appium to 1.6.4 beta and my setup now is:

**Environment:**
Appium version 1.6.4
WDA version: 2.15.0
Xcode version 8.2
Mac 10.12.3 (Sierra)
IOS version 10.2 (Real device)

As suggested in the above discussion I have tried to implement the following combinations of TouchAction using press+wait calls, but none of them seems to work 
TouchAction action = new TouchAction(driver) followed by the following combinations:
1) action.press(75, 30).waitAction(500).moveTo(75, 250).waitAction(500).moveTo(75,300).release().perform();

2) action.longPress(75, 30).moveTo(75, 250).release().perform();
3) action.press(75, 30).waitAction(100).moveTo(75, 250).waitAction(100).release().perform();


I have even tried to use the tap method but still no go:
MobileElement mobele = driver.findElement(By.name("Element to drag"));
1) action.tap(mobele).waitAction(100).moveTo(75, 250).waitAction(100).release().perform();

2) action.tap(mobele).waitAction(100).moveTo(mobele.getCenter().x, mobele.getCenter().y + 250).waitAction(100).release().perform();

In addition to this the code to swipe up i.e. "driver.swipe(75,500,75,0,800)" is also broken on the latest Appium 1.6.4 beta. Is there a way where I can perform swipe up and swipe down actions on the latest appium version?
Any suggesstions is much appreciated.

Regards,
Jerry

**Comment by TARIFABBAS** [comment]
@mykola-mokhnach I have already tried that and getting the error below

_java.lang.IllegalMonitorStateException
	at java.lang.Object.wait(Native Method)
	at com.tarif.appiumIOS.CommandExecute.longPressAndMove(CommandExecute.java:97)
	at com.tarif.appiumIOS.CommandExecute.Command(CommandExecute.java:88)
	at com.tarif.appiumIOS.GreetingServer.run(GreetingServer.java:28)_

**Comment by mykola-mokhnach** [comment]
So, this is how the gesture recogniser looks in Appium _(lib/commands/gesture.js_ in appium-xcuitest-driver module):

```javascript
function isDrag (gestures) {
  return (
      gestures.length === 4 &&
      gestures[0].action === 'press' &&
      gestures[1].action === 'wait' &&
      gestures[2].action === 'moveTo' &&
      gestures[3].action === 'release'
  );
}
```

So I suppose the chain in the client should look like:

```java
press(75, 30).waitAction(500).moveTo(75, 250).release().perform()
```

in order to make it work. Everything else will fail.

**Comment by mykola-mokhnach** [comment]
@imurchie @TikhomirovSergey @jlipps  It would be good to sit together and discuss what we do support and what we don't in these action chains. At least, it might be useful for end users to explicitly show actions chains that we do support in case of failure, so they can easily fix the stuff themselves without reading the source code.

@TARIFABBAS Please try Appium 1.6.4-beta. 1.6.3 does not contain all the necessary fixes.

**Comment by jerrytom2020** [comment]
Hi @mykola-mokhnach , @imurchie, @jlipps ,

The press(75, 500).waitAction(800).moveTo(75, 250).release().perform() works but the WDA takes nearly 6 minutes to perform this swipe action in the app. This delay is similar when I use driver.swipe(75,500,75,250,800). And this delay is same in both Appium 1.6.3 and Appium 1.6.4 versions.

I'm currently on Appium 1.6.4. Could you help me find the reason causing this 6 minutes delay? Kindly find the test execution appium log below for reference:

**Logs:**
[HTTP] --> POST /wd/hub/session/42fcccdb-b13a-488a-b6b8-87b90d0c696d/touch/perform {"actions":[{"action":"press","options":{"x":24,"y":150}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":24,"y":500}},{"action":"release","options":{}}]}

[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":24,"y":150}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":24,"y":500}},{"action":"release","options":{}}],"42fcccdb-b13a-488a-b6b8-87b90d0c696d"]

[debug] [XCUITest] Executing command 'performTouch'

[debug] [XCUITest] Received the following touch action: press-wait-moveTo-release
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/A313621D-05CC-4C35-9B4D-AF2DE8C9ADA0/wda/dragfromtoforduration] with body: {"fromX":24,"fromY":150,"toX":48,"toY":650,"duration":0.5}

[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"A313621D-05CC-4C35-9B4D-AF2DE8C9ADA0","status":0}
[debug] [MJSONWP]

**Comment by vjmaiky** [comment]
what i managed to use int this case was:

TouchAction touch = new TouchAction(driver).press(x,y).waitAction(1000).moveTo(x, y).realease().perform();

The problem is if i use correct coordinates it is not working..so for swiping up on moveTo(x was for ex. 149, and Y was -400).

Still did not managed to find some coordinates to open iOS control center.

**Comment by dkdodson3** [comment]
This is also taking upwards of 5-6 minutes for swipe to work...

Other issue is that on android I can do a press+moveto+moveto+release but it is not allowed in the iOS driver.

**Comment by reach2jeyan** [comment]
I am blocked here from dragging an element to a particular location. I can swipe up and down in the native application. 

I am using ruby with `appium_lib`. Please can someone help me with pressing and dragging the element to a location?

**Comment by jlipps** [comment]
@reach2jeyan have you tried `driver.execute_script("mobile: dragFromToForduration", ...)` (with appropriate args?)

**Comment by KazuCocoa** [comment]
You can call `drag_from_to_for_duration`, wrapper for  `mobile:` method, if you use ruby_lib 9.4.0.
You also can call `mobile:` methods with `execute_script` mentioned the above like https://github.com/appium/ruby_lib/pull/537/files
@reach2jeyan

**Comment by reach2jeyan** [comment]
@jlipps @KazuCocoa Thank you for the reply. This I believe, uses coordinates that changes from device to device as per the screen-size? Though I will try this out, is there a way, I can identify the element by its id or xpath and then initiate the drag method?

**Comment by KazuCocoa** [comment]
@reach2jeyan 
You can set an element like the following.
https://github.com/appium/ruby_lib/pull/537/files#diff-62d6fd176adcc2a859750b2064fb85feR118

So, you can identify element with `find_element/s` and set the element to `"mobile: dragFromToForduration"`.

**Comment by reach2jeyan** [comment]
@KazuCocoa Thanks...! Does appium have a fix for `ScrollTo` for android? The current `scroll_to` doesnt seem to navigate to the correct element or even click it. 

Any idea how to swipe by index? I have tried scroll_to(scrollable_index: '8') but it wouldnt work.

**Comment by KazuCocoa** [comment]
@reach2jeyan 
I think `scroll_to(scrollable_index: '8')` does't work because this method have no `text` argument as 1st arg.
https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/android/element/generic.rb#L40

`scrollable_index` used to specify nested or multi scrollable elements.
https://github.com/appium/ruby_lib/blob/master/lib/appium_lib/android/element/generic.rb#L33

By default, if your app use one scrollable element, you can use `scroll_to` like `scroll_to('text, contentDescription or resource_id')`.
If you have two scrollable elements on the screen and you'd like to scroll 2nd element, you can use  `scroll_to` like `scroll_to('text, contentDescription or resource_id', scrollable_index: 1)`.

**Comment by reach2jeyan** [comment]
@KazuCocoa Thanks a lot for the reply. I am basically, trying to create a generic code for cucumber, so will this code do good then

`scroll_to(text: arg, scrollable_index: arg1)`

Considering, I am going to provide the values for both of them in the cucumber?

**Comment by reach2jeyan** [comment]
@KazuCocoa I tried implementing your code, it does swipe, but like I said, it is not, going to the element, where I want it to scroll and click, though I am giving the text and the index of the element.

**Comment by vjmaiky** [comment]
I'm using something like this:

1. Here i want to find an element which exists but it is not visible (this of course can be improved) :

public static void findElementToClickOnIt(By by) {
		WebElement we = null;
		we = AppiumDriverInstance.getInstance().findElement(by);
		if (we.isDisplayed()) {
			// do nothing
		} else {
			int retry = 0;
			while (!we.isDisplayed() && retry < 20) {
				swipe_UpWithTouch();
				retry++;
			}
		}
	}

2. Here i wan to find an element which is does not exist (it will appear after few seconds and i need to go up in order to click on it)
	public static void refreshEmailListUntilEmailIsDisplayed(String subject) {
		int retry = 0;
		while (retry < 20) {
			try {
				WebElement we = null;
				we = AppiumDriverInstance.getInstance().findElementById(subject);
				if (we.isDisplayed()) {
					break;
				}
			} catch (Throwable e) {
				swipe_DownWithTouch();
			}
			retry++;
		}

	}

Swipe method (instead of coordinates use x and y for your device) as:
		Dimension screenSize = AppiumDriverInstance.getInstance().manage().window().getSize();
		int high = screenSize.getHeight();
		int width = screenSize.getWidth();


	public static void swipe_UpWithTouch() {
		if (!Properties.IS_TABLET) {
			TouchAction touch = new TouchAction(AppiumDriverInstance.getInstance()).press(149, 659).waitAction(1000)
					.moveTo(149, -400).release().perform();
		} else {
			// this needs to be updated accrodingly
			TouchAction touch = new TouchAction(AppiumDriverInstance.getInstance()).press(149, 659).waitAction(1000)
					.moveTo(149, -400).release().perform();
		}
	}

**Comment by vjmaiky** [comment]
hope this workaournd it will help you.

**Comment by KazuCocoa** [comment]
@reach2jeyan 
> Should I create it an as a new issue and probably have the discussion there since the issue here appears different to what I am posting?

Yes, it's better to create a new issue in https://github.com/appium/ruby_lib .

You can use the following method. So, you can scroll without element with it.

```ruby
Appium::TouchAction.new.swipe(start_x: start_x, start_y: start_y, end_x: end_x, end_y: end_y, duration: DURATION).perform
```
