### ISSUE TITLE
Appium 1.6.4 Swipe to bring the iOS control center is not working

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#7980]
## The problem
Swipe to bring the iOS control center is not working

## Environment

* Appium version: 1.6.4
* Desktop OS/version used to run Appium: Mac OS 10.11.6
* Node.js version: v7.4.0
* Mobile platform/version under test: iOS 10.2.1 (iPhone 6+)
* Real device: iPhone 6+

## Details
I am trying to open iOS control centering order to enable AirPlane mode

## Link to Appium logs
[debug] [MJSONWP] Calling AppiumDriver.getWindowSize() with args: ["current","266f41d6-ddff-4d60-8353-ca13857b2ce9"]
[debug] [XCUITest] Executing command 'getWindowSize'
[debug] [JSONWP Proxy] Proxying [GET /window/size] to [GET http://localhost:8100/session/1CFD7852-59F3-4EA8-B739-482F15FA414F/window/size] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"width\" : 414,\n    \"height\" : 736\n  },\n  \"sessionId\" : \"1CFD7852-59F3-4EA8-B739-482F15FA414F\",\n  \"status\" : 0\n}"
[debug] [MJSONWP] Responding to client with driver.getWindowSize() result: {"width":414,"height":736}
[HTTP] <-- GET /wd/hub/session/266f41d6-ddff-4d60-8353-ca13857b2ce9/window/current/size 200 500 ms - 98 
[HTTP] --> POST /wd/hub/session/266f41d6-ddff-4d60-8353-ca13857b2ce9/touch/perform {"actions":[{"action":"press","options":{"x":190,"y":735}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":190,"y":200}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":190,"y":735}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":190,"y":200}},{"action":"release","options":{}}],"266f41d6-ddff-4d60-8353-ca13857b2ce9"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-wait-moveTo-release
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8100/session/1CFD7852-59F3-4EA8-B739-482F15FA414F/wda/dragfromtoforduration] with body: {"fromX":190,"fromY":735,"toX":380,"toY":935,"duration":1}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"1CFD7852-59F3-4EA8-B739-482F15FA414F","status":0}
[debug] [MJSONWP] Responding to client with driver.performTouch() result: {}
[HTTP] <-- POST /wd/hub/session/266f41d6-ddff-4d60-8353-ca13857b2ce9/touch/perform 200 4450 ms - 74 
[HTTP] --> POST /wd/hub/session/266f41d6-ddff-4d60-8353-ca13857b2ce9/touch/perform {"actions":[{"action":"press","options":{"x":40,"y":200}},{"action":"wait","options":{"ms":500}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","options":{"x":40,"y":200}},{"action":"wait","options":{"ms":500}},{"action":"release","options":{}}],"266f41d6-ddff-4d60-8353-ca13857b2ce9"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: press-wait-release
[debug] [JSONWP Proxy] Proxying [POST /wda/touchAndHold] to [POST http://localhost:8100/session/1CFD7852-59F3-4EA8-B739-482F15FA414F/wda/touchAndHold] with body: {"duration":0.5,"x":40,"y":200}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"1CF

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

public static void enableDisableAirplaneMode() {
		// Swipe up to bring control center on iPhone
		try {
			Thread.sleep(1000);
		} catch (InterruptedException e1) {
			// Auto-generated catch block
			e1.printStackTrace();
		}
		Dimension screenSize = AppiumDriverInstance.getInstance().manage().window().getSize();
		System.out.println(screenSize);
		Swipe.swipe(190, 735, 190, 200, 1000);
		// Swipe.swipe(145, 567, 145, 100, 1000, true);

		// iphone 5 coordinates for airplane mode: 40, 200
		// iphone 5 coordinates for wifi: 80, 200
		// iphone 6+ location: {32, 295} airplane mode
		// iphone 6+ location: {107, 295} wifi
		// tap airplane mode
		try {
			Thread.sleep(1000);
		} catch (InterruptedException e1) {
			// Auto-generated catch block
			e1.printStackTrace();
		}
		AppiumDriverInstance.getInstance().tap(1, 40, 200, 500);

		// "No Sim Card installed" OK message may appear. If not, ignore it
		try {
			Thread.sleep(1000);
			acceptAllAlerts();
		} catch (Exception e) {
			// ignore it
		}
		// collapse control center by tapping the upper area
		AppiumDriverInstance.getInstance().tap(1, 40, 40, 200);
	}

Any ideas how can i do it?
Thanks.

**Comment by priyankshah217** [comment]
i believe, you do not have any control over ios control center since its not in debug mode. You only play with your app only which in debug mode.

**Comment by vjmaiky** [comment]
on iOS9 and lower it worked..it`s just a swipe with certain coordinates to bring up the controller and after that tap on button...but i do not get it how to make it work on ios10

**Comment by vjmaiky** [comment]
@mykola-mokhnach  any suggestion?

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/7960

This has never been workign for me, so I use direct WDA calls for swiping instead ("mobile:swipe" in Appium 1.6.-beta)
Also, don't expect the stuff to work in the same way it was in iOS9. XCTest is a completely new frameworks and is totally different from what instruments was providing.

**Comment by vjmaiky** [comment]
@mykola-mokhnach can you please give me an example, how would you do it? (using java)..i know it`s kinda lame what i`m asking but i really want to resolve that problem..

At work i also used something like this:

		driver.performTouchAction(new TouchAction(drivere()).press(145, 567))
				.moveTo(145, 100).release().perform();

And if i remember the message was that the method is not yet implemented and to contact an Appium developer.

**Comment by mykola-mokhnach** [comment]
> And if i remember the message was that the method is not yet implemented and to contact an Appium developer.

It's probably this about this issue https://github.com/appium/appium/issues/7978

Regarding how to do it - unfortunately I cannot help there, since we don't use Appium wrappers for swipe actions in our automation framework.

**Comment by vjmaiky** [comment]
ok ; i`ll follow the threads that you posted; thank you.

**Comment by vjmaiky** [comment]
Managed to bring iOS control center with touch actions, but using negative coordinates for endpointY. For some reason if i put positive value and endpointY, it is added to startpointY and will not work.

Ex: if i do press(250, 735).waitaction().moveTo(250, 200).release.perform
It will try to move the screen to 735+200 which is 935 and it will not work
But if i do press(250, 735).waitaction().moveTo(250, -500).release.perform 
It will work :) 

@mykola-mokhnach do you see any bug here? of it is considered as expected?
If it is as expected issue can be closed.

**Comment by mykola-mokhnach** [comment]
This works as expected. _moveTo_ handles coordinates as relative to the recent point in the chain.

**Comment by mayureshshirodkar** [comment]
@vjmaiky  can you add the code to pull up the control center?
As when i try it shows a pointer pulling upwards.

**Comment by mayureshshirodkar** [comment]
Got it to work. It was required that i have a lower wait time. Previously had a wait of 1 second
eg. driver.swipe( (int) (0.5 * screenWidth), screenHeight, (int) (0.5 * screenWidth), (int) (.2 * screenHeight), 100);

**Comment by vjmaiky** [comment]
public static void enableDisableAirplaneModeiPhone6Plus() {
		new TouchAction(AppiumDriverInstance.getInstance()).press(250, 735).waitAction(90).moveTo(250, -460).release()
				.perform();
		if (AppiumDriverInstance.getInstance().findElement(By.id("Airplane Mode")).isEnabled()) {
			click("Airplane Mode", Attribute.NAME);
			EmailApplicationHelpers.acceptAllAlerts();
		} else {
			click("Airplane Mode", Attribute.NAME);
			EmailApplicationHelpers.acceptAllAlerts();
		}
		new TouchAction(AppiumDriverInstance.getInstance()).press(250, 10).waitAction(90).moveTo(250, 736).release()
				.perform();
	}

**Comment by vjmaiky** [comment]
my method to enable disable

**Comment by mayureshshirodkar** [comment]
Thanks @vjmaiky for the code snippet.

**Comment by F1NaL** [comment]
Thanks @vjmaiky.
How do you find id ? Inspector doesn't see elements in control/notification center

**Comment by chandanijain9** [comment]
even I have the same query @vjmaiky 
how did you find id ?
