### ISSUE TITLE
Appium 1.6.3, How can I scroll to particular element in java

### ISSUE THREAD

**Issue by omkara120120** [appium/appium#7981]
## The problem

I am using appium 1.6.3, and **IOSDriver**, what are the ways available to scroll to the particular element on page

## Environment

Appium version : 1.6.3
Desktop OS/version used to run Appium: 10.12 (16A323)
npm version : 3.10.9
Mobile platform/version under test: 10.0.2(14A456)
Real device or emulator/simulator: Real device

**Comment by priyankshah217** [comment]
raise this question on appium forum, and close this issue.
