### ISSUE TITLE
java.lang.NoClassDefFoundError: org/openqa/selenium/HasInputDevices

### ISSUE THREAD

**Issue by sjenasears** [appium/appium#7982]
## The problem

java.lang.NoClassDefFoundError: org/openqa/selenium/HasInputDevices
getting this error while running appium script below in eclipse

    @Before
    public void setUp() throws Exception {
 
    	
    	DesiredCapabilities capabilities = new DesiredCapabilities();
    	
    	capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.6.4-beta");
    	capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
    	capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.2");
    	capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6s");
    	//capabilities.setCapability(MobileCapabilityType.UDID, "");
    	
    	//capabilities.setCapability(MobileCapabilityType.APP, "/Users/sjena/Desktop/Relay_Appium/ipa/SYW_Relay.app");
    	capabilities.setCapability(MobileCapabilityType.APP, "settings");

    	
    	capabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, "500000");
    	capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, AutomationName.IOS_XCUI_TEST);
    	driver = new IOSDriver<WebElement>(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
    	driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
    	
    }
    

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by imurchie** [comment]
This is an issue with the Java client library. Please make an issue there (https://github.com/appium/java-client)
