### ISSUE TITLE
iOS 10 device logs

### ISSUE THREAD

**Issue by qakapil** [appium/appium#7985]
Hi,

This is not exactly an Appium issue but something which Appium automators would have noticed so asking this here in case someone has already found a solution to this. 

One of the goals of my automation tests is to capture device logs and present them to the stake holders. Now with iOS10 devices the device logs are not really in presentable format.  idevicesyslog is spewing a lot of kernel level debug logs which I don't really need.
Any suggestions please ? 

Regards,
Kapil.

**Comment by mykola-mokhnach** [comment]
How this is related to Appium? You can just filter unnecessary records from the log yourself in the client code.
