### ISSUE TITLE
[XCUITest] Error: Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by bhardw17** [appium/appium#7987]
## The problem

After signing and deploying WebDriverAgent on a Real iPhone, running a test that works on an iOS simulator on the real device results in a Error about Unable to start WebDriverAgent.

The WDA gets installed on the device and launches to a black screen but just waits there till the log shows

[XCUITest] Error: Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: socket hang up

## Environment

* Appium version: 1.6.4 BETA
* Desktop OS/version used to run Appium: Mac OS X El Captain 10.11.6
* Node.js version:6.7.0
* Mobile platform/version under test: iPhone 6s , OS 10.0
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

I have a simple test for iOS written in Appium via python bindings, This test works on a simulator no problem. However when i am trying to run the same test on a real device I am getting a

[XCUITest] Error: Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: socket hang up

[MJSONWP] Encountered internal error running command: Error: Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: socket hang up

## Link to Appium logs

https://gist.github.com/bhardw17/e8d44e01f4cea696344ee082e7e9a823

## Code To Reproduce Issue [ Good To Have ]
'''python
from appium import webdriver
import os
import time

deviceName = "XXXXX Automation's iPhone"
udid = "abb9129e8a120cae1a7991d8e519096e71339e52"

platformVersion = "10.0"

success = True
desired_caps = {}
desired_caps['platformName'] = 'iOS'
desired_caps['platformVersion'] = platformVersion
desired_caps['deviceName'] = deviceName
desired_caps['udid'] = udid
desired_caps['automationName'] = 'XCUITest'
desired_caps['realDeviceLogger'] = 'idevicesyslog'
desired_caps['bundleId'] = 'com.apple.Preferences'
desired_caps['autoAcceptAlerts'] = True;
desired_caps['ShowIOSLog'] = True 
desired_caps['showXcodeLog'] = True

wd = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
wd.implicitly_wait(10)

try:
	wd.find_element_by_accessibility_id('General').click()
	wd.find_element_by_accessibility_id('About').click()
finally:
	wd.quit()
	time.sleep(3)
''''

## Terminal Log
python appiumXcPyt.py
Traceback (most recent call last):
  File "appiumXcPyt.py", line 43, in <module>
    wd = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
  File "/Library/Python/2.7/site-packages/appium/webdriver/webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "/Library/Python/2.7/site-packages/selenium-2.53.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 91, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Python/2.7/site-packages/selenium-2.53.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 173, in start_session
    'desiredCapabilities': desired_capabilities,
  File "/Library/Python/2.7/site-packages/selenium-2.53.2-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 233, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium-2.53.2-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session: Could not proxy command to remote server. Original error: Error: socket hang up

**Comment by mykola-mokhnach** [comment]
Please fix _showIOSLog_ capability name and attach the lo, which includes device output.

**Comment by bhardw17** [comment]
Updated GIST https://gist.github.com/bhardw17/e8d44e01f4cea696344ee082e7e9a823 with the showIOSLogs also.

**Comment by mykola-mokhnach** [comment]
```
[iOSLog] [IOS_SYSLOG_ROW] Symbolication may be possible by manually cleaning up and including the Binary Image section of a full report from this same device -- good luck!
[iOSLog] [IOS_SYSLOG_ROW] Mar  6 13:01:27 XXXXX-Automations-iPhone ReportCrash(CrashReporterSupport)[1531] <Notice>: Process:             testmanagerd [1530]
[iOSLog] [IOS_SYSLOG_ROW] Path:                /Developer/usr/libexec/testmanagerd
[iOSLog] [IOS_SYSLOG_ROW] OS Version:          iPhone OS 10.0 (14A5297c)
[iOSLog] [IOS_SYSLOG_ROW] Mar  6 13:01:27 XXXXX-Automations-iPhone ReportCrash(CrashReporterSupport)[1531] <Notice>: Exception Type:  EXC_CRASH
[iOSLog] [IOS_SYSLOG_ROW] Exception Codes: 0x0000000000000000, 0x0000000000000000
[iOSLog] [IOS_SYSLOG_ROW] Exception Note:  EXC_CORPSE_NOTIFY
[iOSLog] [IOS_SYSLOG_ROW] Termination Description: DYLD, Symbol not found: _UIAccessibilityAutomationEventButtonEventsCompleted | Referenced from: /Developer/usr/libexec/testmanagerd | Expected in: dyld shared cache | in /Developer/usr/libexec/testmanagerd
[iOSLog] [IOS_SYSLOG_ROW] Triggered by Thread:  0
[iOSLog] [IOS_SYSLOG_ROW] Mar  6 13:01:27 XXXXX-Automations-iPhone ReportCrash(CrashReporterSupport)[1531] <Notice>: Thread 0 Crashed:
[iOSLog] [IOS_SYSLOG_ROW] 0   dyld                          	0x0000000100175c18 0x100150000 + 154648
[iOSLog] [IOS_SYSLOG_ROW] 1   dyld                          	0x00000001001755f0 0x100150000 + 153072
[iOSLog] [IOS_SYSLOG_ROW] 2   dyld                          	0x00000001001544f0 0x100150000 + 17648
[iOSLog] [IOS_SYSLOG_ROW] 3   dyld                          	0x0000000100156984 0x100150000 + 27012
[iOSLog] [IOS_SYSLOG_ROW] 4   dyld                          	0x0000000100151044 0x100150000 + 4164
[iOSLog] [IOS_SYSLOG_ROW] Mar  6 13:01:27 XXXXX-Automations-iPhone ReportCrash(CrashReporterSupport)[1531] <Notice>: Thread 0 crashed with ARM Thread State (64-bit):
[iOSLog] [IOS_SYSLOG_ROW]     x0: 0x0000000000000006   x1: 0x0000000000000004   x2: 0x000000016fd123b0   x3: 0x000000000000007f
[iOSLog] [IOS_SYSLOG_ROW]     x4: 0x000000016fd11fb0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x000000016fd12740
[iOSLog] [IOS_SYSLOG_ROW]     x8: 0x0000000000000004   x9: 0x0000000000000009  x10: 0x657665442f206e69  x11: 0x73752f7265706f6c
[iOSLog] [IOS_SYSLOG_ROW]    x12: 0x752f7265706f6c65  x13: 0x786562696c2f7273  x14: 0x6d747365742f6365  x15: 0x0064726567616e61
[iOSLog] [IOS_SYSLOG_ROW]    x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x00000001001894f8
[iOSLog] [IOS_SYSLOG_ROW]    x20: 0x000000000000007f  x21: 0x0000000100181d60  x22: 0x0000000000000000  x23: 0x0000000000000001
[iOSLog] [IOS_SYSLOG_ROW]    x24: 0x0000000100181d60  x25: 0x0000000100181ab8  x26: 0x0000000100183ba8  x27: 0x906b9c7c63010070
[iOSLog] [IOS_SYSLOG_ROW]    x28: 0x0000000100181000   fp: 0x000000016fd11f90   lr: 0x00000001001755f0
[iOSLog] [IOS_SYSLOG_ROW]     sp: 0x000000016fd11f90   pc: 0x0000000100175c18 cpsr: 0x00000000
```

This crash looks suspicious. You can either try to update iOS version on iPhone and try another device.

**Comment by bhardw17** [comment]
Okay will update to latest 10.2.1 and try again and reply back. Anything else that may standout as in signing of the app etc?

**Comment by bhardw17** [comment]
@mykola-mokhnach I updated my iOS to 10.2.1 which forced me to update Xcode but now after all the updates i was able to run my script successfully on a real device.

👍 

Closing this issue. Thanks
