### ISSUE TITLE
How do I check if the appium session creation has encountered an error or is encountering an error

### ISSUE THREAD

**Issue by reach2jeyan** [appium/appium#7990]
Basically, I am trying to automate the tests here, for our CI. Since a lot of our tests run in parallel, our appium sometimes, hangs up with existing sessions, and not allowing for a new connection to create.

In this scenario, I would like to know, how do I let my code, know this error, and execute `killall adb` or `adb kill-server` and start the appium server all over again.

**Comment by SrinivasanTarget** [comment]
Refer this: https://github.com/saikrishna321/AppiumTestDistribution and see how parallel tests are handled, you will get a better idea. Raise your questions in discussion forum please not here.
@triager please close

**Comment by reach2jeyan** [comment]
Thank you!

On Mar 12, 2017 10:05 PM, "Srinivasan Sekar" <notifications@github.com>
wrote:

Refer this: https://github.com/saikrishna321/AppiumTestDistribution and see
how parallel tests are handled, you will get a better idea. Raise your
questions in discussion forum please not here.
@triager <https://github.com/triager> please close

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/appium/appium/issues/7990#issuecomment-285956364>, or mute
the thread
