### ISSUE TITLE
App not installed in IOS real device 

### ISSUE THREAD

**Issue by seenuvlr1** [appium/appium#7994]
## The problem

i try to install .ipa application into iphone 4s real device but app not installed and getting error in ios-deploy library. Please help me friends.

[XCUITest] Error checking install status: Command 'ios-deploy --exists --id 59397a6dbcae8dfb6be88883540f8ee70d2f8917 --bundle_id com.experitest.ExperiBank' exited with code 255
[debug] [XCUITest] App is not installed. Will try to install.
[debug] [XCUITest] Error : Command 'ios-deploy --id 59397a6dbcae8dfb6be88883540f8ee70d2f8917 --uninstall --bundle /var/folders/nk/ptgb2_5n65b6t4nw5526zmwh0000gn/T/201727-3663-kkpmr2.d71dkro1or/Payload/Experibank.app' exited with code 253
[XCUITest] Error: Could not install app Command 'ios-deploy --id 59397a6dbcae8dfb6be88883540f8ee70d2f8917 --uninstall --bundle /var/folders/nk/ptgb2_5n65b6t4nw5526zmwh0000gn/T/201727-3663-kkpmr2.d71dkro1or/Payload/Experibank.app' exited with code 253

please help me friends.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.5
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac sierra 10.12.5
* Node.js version (unless using Appium.app|exe): 7.7.1
* Mobile platform/version under test: IOS version 9.3.3 iphone
* Real device or emulator/simulator: Iphone and ipad real device
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
The application might be not signed properly or is not build in debug mode. BTW, I won't recommend using 32-bit iDevices with XCTest, since this causes other unexpected issues in automation.

**Comment by seenuvlr1** [comment]
@mykola-mokhnach thanks for your replay. So are you telling the issue might be in .ipa file??
could you please tell about "I won't recommend using 32-bit iDevices with XCTest" this?? i am not able to catch what you telling.

**Comment by mykola-mokhnach** [comment]
There are several known issues in XCTest if one executes automation on iPhone 5 or older, which don't support arm64 instructions set.

**Comment by seenuvlr1** [comment]
Thanks @mykola-mokhnach . Now i am facing below mentioned error. 
[Xcode] 
Testing failed:
	'RoutingHTTPServer/RoutingHTTPServer.h' file not found
** TEST FAILED **

may i know the cause of this issue???

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for howto questions
