### ISSUE TITLE
chrome browser launching again and again 

### ISSUE THREAD

**Issue by tarunHub** [appium/appium#7995]
**Problem**

unable to launch google.com though chrome browser app.

**Code**

DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability("deviceName", "emulator-5554"); // Real Device Name
        capabilities.setCapability("platformVersion", "4.4.2");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("browsername", "Chrome");
      //  capabilities.setCapability("appPackage", "com.android.chrome");
       // capabilities.setCapability("appActivity", "com.google.android.apps.chrome.Main");
        driver = new AndroidDriver<MobileElement>(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        driver.get("https://google.com");

**Environment**

* Appium version (or git revision) that exhibits the issue: - 1.4.13.1
* Desktop OS/version used to run Appium: Windows 7
* Mobile platform/version under test: tested on 6.0 and 4.4.2
* Real device or emulator/simulator: lenovo vibe k5 note (tested on android emulators as well)

**Logs**

info: JSONWP Proxy: Got response with status 200: {"sessionId":"94bee90d145fa367d9a4d433770c5e07","status":33,"value":{"message":"session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid 'context': {\"auxData\":{...
> error: Chromedriver: Chromedriver exited unexpectedly with code null, signal SIGTERM
> info: Chromedriver: Changed state to 'stopped'
> info: Chromedriver stopped unexpectedly on us, shutting down then calling back up with the on-die callback
> error: Chromedriver: Error: A new session could not be created. (Original error: session not created exception
> from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"10292.1","isDefault":true},"id":1,"name":"","origin":"://"}
>   (Session info: chrome=56.0.2924.87)
>   (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64))
>     at JWProxy.command$ (lib/proxy.js:149:15)
>     at tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:67:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:294:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:100:21)
>     at GeneratorFunctionPrototype.invoke (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\appium-chromedriver\node_modules\babel-runtime\regenerator\runtime.js:136:37)
>     at GeneratorFunctionPrototype.b (domain.js:183:18)
>     at lib$es6$promise$$internal$$tryCatch (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\es6-promise\dist\es6-promise.js:331:16)
>     at lib$es6$promise$$internal$$invokeCallback (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\es6-promise\dist\es6-promise.js:343:17)
>     at lib$es6$promise$$internal$$publish (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\es6-promise\dist\es6-promise.js:314:11)
>     at Object.lib$es6$promise$asap$$flush [as _onImmediate] (C:\Program Files (x86)\Appium\node_modules\appium\node_modules\es6-promise\dist\es6-promise.js:125:9)
>     at processImmediate [as _immediateCallback] (timers.js:330:15)
>  { [Error: A new session could not be created. (Original error: session not created exception
> from unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"10292.1","isDefault":true},"id":1,"name":"","origin":"://"}
>   (Session info: chrome=56.0.2924.87)
>   (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64))]
>   status: 33,
>   value: { message: 'session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid \'context\': {"auxData":{"frameId":"10292.1","isDefault":true},"id":1,"name":"","origin":"://"}\n  (Session info: chrome=56.0.2924.87)\n  (Driver info: chromedriver=2.18.343845 (73dd713ba7fbfb73cbb514e62641d8c96a94682a),platform=Windows NT 6.1 SP1 x86_64)' },
>   httpCode: 200 }
> info: [debug] Cleaning up appium session

**Comment by mykola-mokhnach** [comment]
You appium version is very old and it might be that built-in chromedriver does not support the current engine version in the webview. Update Appium to version 1.6.4-beta and try it

**Comment by tarunHub** [comment]
Thanks works for me
