### ISSUE TITLE
setNetworkConnection does not work on Android 7.1 Nougat (API 25) emulator

### ISSUE THREAD

**Issue by xsveda** [appium/appium#7997]
## The problem

setNetworkConnection does not work on Android 7.1 Nougat (API 25) emulator.
Works fine on Android 6.0 Marshmallow amulator and below.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 7.5.0
* Mobile platform/version under test: Android 7.1 Nougat
* Real device or emulator/simulator: emulator Android 7.1.1 (Google APIs)	x86_64
* Appium CLI or Appium.app|exe: Installed through `npm`

## Details

The problem is in ADB commands executed:

- `adb shell settings put global airplane_mode_on 1` executes by the emulator has still Internet access
- `adb shell am broadcast -a android.intent.action.AIRPLANE_MODE --ez state true` ends with SecurityException:
`java.lang.SecurityException: Permission Denial: not allowed to send broadcast android.intent.action.AIRPLANE_MODE from pid=13653, uid=2000
        at android.os.Parcel.readException(Parcel.java:1684)
        at android.os.Parcel.readException(Parcel.java:1637)
        at android.app.ActivityManagerProxy.broadcastIntent(ActivityManagerNative.java:3537)
        at com.android.commands.am.Am.sendBroadcast(Am.java:772)
        at com.android.commands.am.Am.onRun(Am.java:404)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:51)
        at com.android.commands.am.Am.main(Am.java:121)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)`

## Link to Appium logs

https://gist.github.com/xsveda/1c112f1989ae733ef616ab364fe8913b

## Code To Reproduce Issue [ Good To Have ]

`((AndroidDriver) driver).setConnection(Connection.AIRPLANE);`

**Comment by mykola-mokhnach** [comment]
There is no known universal way to change network state in Android 7.0+ via ADB due to security limitations.
The only way I have found so far would be to write own utility, give it permissions to change airplane mode settings and then broadcast messages to this utility using adb to change network state.

**Comment by jlipps** [comment]
@vrunoa did you do some work related to this recently?

**Comment by vrunoa** [comment]
@jlipps @mykola-mokhnach for emulators we can use `adb shell settings put global airplane_mode_on 1`, just tried it on Android 7.1.1 and it works. I don't know if that's already implemented in appium.

**Comment by mykola-mokhnach** [comment]
> adb shell settings put global airplane_mode_on 1

for now broadcasting is used for this purpose, which is only the case for real devices running Android <=6. Regarding simulator solution - it's not implemented yet. I'll create a PR.

**Comment by mykola-mokhnach** [comment]
```javascript
  await this.wrapBootstrapDisconnect(async () => {
    await this.adb.setAirplaneMode(airplaneMode);
  });
  await this.wrapBootstrapDisconnect(async () => {
    await this.adb.broadcastAirplaneMode(airplaneMode);
  });


...

/*
 * on: true (to turn on) or false (to turn off)
 */
methods.setAirplaneMode = async function (on) {
  await this.shell(['settings', 'put', 'global', 'airplane_mode_on', on ? 1 : 0]);
};

/*
 * on: true (to turn on) or false (to turn off)
 */
methods.broadcastAirplaneMode = async function (on) {
  let args = ['am', 'broadcast', '-a', 'android.intent.action.AIRPLANE_MODE',
              '--ez', 'state', on ? 'true' : 'false'];
  await this.shell(args);
};
```

**Comment by mykola-mokhnach** [comment]
there is no way to change airplane mode on Android 7+

**Comment by cedric-roux** [comment]
@mykola-mokhnach, you write:

> There is no known universal way to change network state in Android 7.0+ via ADB due to security limitations.
> The only way I have found so far would be to write own utility, give it permissions to change airplane mode settings and then broadcast messages to this utility using adb to change network state.

Is it something that you tried yourself?

I need to programmatically enter and leave air plane mode and with the new phones we just bought it is no more possible using:
```shell
settings put global airplane_mode_on 0; am broadcast -a android.intent.action.AIRPLANE_MODE --ez state false
```
and:
```shell
settings put global airplane_mode_on 1; am broadcast -a android.intent.action.AIRPLANE_MODE --ez state true
```

So, based on the information you provide, I guess I will need to write a small apk and put it in all the phones we have. But before going further I wonder if this method has been tested by you or someone else.

Thanks for any information you can provide!
