### ISSUE TITLE
How to select entries from android AutoComplete dropdown using Javascript

### ISSUE THREAD

**Issue by shashikumarraja** [appium/appium#7999]
## The problem
I am unable to find any method to select entries from autocomplete dropdown using javascript.
The dropdown is not detected by uiautomator viewer so can't get its id.
![screenshot from 2017-03-07 11-43-00](https://cloud.githubusercontent.com/assets/13863716/23654875/be16e894-0358-11e7-95ac-ec070693b339.png)

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Desktop OS/version used to run Appium:Ubuntu 16.04
* Node.js version (unless using Appium.app|exe):7.7.1
* Mobile platform/version under test:Android/6.01
* Real device or emulator/simulator:Real Device
* Appium CLI or Appium.app|exe:

**Comment by ochubey** [comment]
@shashikumarraja have you tried to getPageSource when text entered?
I would create small test and print out page source before and after text entered.
In case there would be no difference it might mean that element would not be found with Appium.

**Comment by mykola-mokhnach** [comment]
@shashikumarraja  Sorry, but this place is for issues rather than for questions. Please use Appium forum instead
