### ISSUE TITLE
ios app not able to install in iphone real device "Error occurred: ApplicationVerificationFailed"

### ISSUE THREAD

**Issue by seenuvlr1** [appium/appium#8002]
## The problem

Mac-mini:~ qassurechennai$ ideviceinstaller --udid 78475895789347549385jhjkfhjd --install /Users/qassurechennai/Sample_IPA_files/EriBank.ipa
WARNING: could not locate iTunesMetadata.plist in archive!
WARNING: could not locate Payload/ExperiBank.app/SC_Info/ExperiBank.sinf in archive!
Copying '/Users/Sample_IPA_files/EriBank.ipa' to device... DONE.
Installing 'com.experitest.ExperiBank'
 - CreatingStagingDirectory (5%)
 - ExtractingPackage (15%)
 - InspectingPackage (20%)
 - TakingInstallLock (20%)
 - PreflightingApplication (30%)
 - InstallingEmbeddedProfile (30%)
 - VerifyingApplication (40%)
 - Error occurred: ApplicationVerificationFailed

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: MAC 10.12.1
* Node.js version (unless using Appium.app|exe): 7.7.1
* Mobile platform/version under test: IOS 9.3
* Real device or emulator/simulator: real device iphone
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [gist](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
This usually happens if the app under test is not signed properly or is not build in debug mode and has nothing to do with Appium itself.

**Comment by wchensc** [comment]
Hi, @imurchie how did you solve this issue?
