### ISSUE TITLE
appium server 1.6.4beta - different XCUITestDriver versions - issue when get Text property of the element

### ISSUE THREAD

**Issue by obstar** [appium/appium#8005]
## The problem

I can't get Text property of button element when run Appium Server 1.6.4beta through terminal  - need to specifically get 'label' attribute BUT when I run same code through Appium Server 1.6.3 or Appium Desktop with Appium Server 1.6.4beta (?? - yes same version as console..) it worked perfectly fine
Below is example code:
```
	var text = _device.FindElementById(MY_ID)
			       .Text;
	Console.WriteLine($"\t\t......     {text}");
```

In the logs I've notice that the difference is the XCUITestDriver version, it looks like in the newer one(v2.15.0) the text/label property behavior change

## Environment
* Appium version: 1.6.4beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: macOS Sierra 10.12.3
* Node.js version (unless using Appium.app|exe): 4.1.2
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: simulator of iPhone 6
* Appium CLI or Appium.app|exe: CLI

## Appium logs

**_Appium Server 1.6.4beta from terminal**
>Creating new XCUITestDriver (v2.15.0) session`
- getting value of the element Text property in this case is **null**
`[HTTP] --> GET /wd/hub/session/398e065d-376f-46e8-b7c1-34a1d5838ac2/element/6D7CD2A0-35D6-4714-B238-8F9AA42CF90F/text {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [GET /wd/hub/session/398e065d-376f-46e8-b7c1-34a1d5838ac2/element/6D7CD2A0-35D6-4714-B238-8F9AA42CF90F/text] to [GET http://localhost:8100/session/C998849B-4188-401B-8E89-B9326EB38A58/element/6D7CD2A0-35D6-4714-B238-8F9AA42CF90F/text] with body: {}
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : null,\n  \"sessionId\" : \"C998849B-4188-401B-8E89-B9326EB38A58\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId C998849B-4188-401B-8E89-B9326EB38A58 with 398e065d-376f-46e8-b7c1-34a1d5838ac2
[HTTP] <-- GET /wd/hub/session/398e065d-376f-46e8-b7c1-34a1d5838ac2/element/6D7CD2A0-35D6-4714-B238-8F9AA42CF90F/text 200 233 ms - 76` 

**_Appium Server 1.6.4beta started from Appium Desktop GUI 1.0.2beta**

> Creating new XCUITestDriver (v2.12.1) session

- getting value of the element Text property in this case is **LOGIN**
`[HTTP] --> GET /wd/hub/session/c9a506ea-f5c0-4eea-a193-0dc2675e9ea9/element/A632F105-DE9F-4B5E-A444-1201CBEBEFAD/text {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[XCUITest] Executing command 'proxyReqRes'
[JSONWP Proxy] Proxying [GET /wd/hub/session/c9a506ea-f5c0-4eea-a193-0dc2675e9ea9/element/A632F105-DE9F-4B5E-A444-1201CBEBEFAD/text] to [GET http://localhost:8100/session/EC72B93B-7EFD-47A1-92E5-08FA13352796/element/A632F105-DE9F-4B5E-A444-1201CBEBEFAD/text] with body: {}
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"LOGIN\",\n  \"sessionId\" : \"EC72B93B-7EFD-47A1-92E5-08FA13352796\",\n  \"status\" : 0\n}"
[JSONWP Proxy] Replacing sessionId EC72B93B-7EFD-47A1-92E5-08FA13352796 with c9a506ea-f5c0-4eea-a193-0dc2675e9ea9
[HTTP] <-- GET /wd/hub/session/c9a506ea-f5c0-4eea-a193-0dc2675e9ea9/element/A632F105-DE9F-4B5E-A444-1201CBEBEFAD/text 200 287 ms - 79
`

**Comment by mykola-mokhnach** [comment]
Yes, this has been changed in WDA - our XCTest backend component. And never Appium version contain fresh WDA snapshots.

I suppose it might be [this](https://github.com/facebook/WebDriverAgent/commit/7113842e09f3ea136904fadd56011fe0c28d8f3a) commit.

**Comment by obstar** [comment]
hey @mykola-mokhnach 
I'm not fully understand the change of my ticket to 'Question' and how this will be handle it? 
Because for me its a bug that I can't use Text property anymore in new version and need it use it GetAttribute("label") to return text value of the element in iOS platform

**Comment by mykola-mokhnach** [comment]
I don't think we can do anything about it in Appium, since we just use the output provided by WDA. Please report directly to WDA project if you don't like the change and want to revert it back.

**Comment by amedvedjev** [comment]
Met the same in 2 places of our client. Both are button elements.

**Comment by Ysoko** [comment]
[Pull Request](https://github.com/facebook/WebDriverAgent/pull/511) to fix the issue introduced with [that](https://github.com/facebook/WebDriverAgent/commit/7113842e09f3ea136904fadd56011fe0c28d8f3a) commit. Waiting for WebDriverAgent to accept.

**Comment by imurchie** [comment]
Closing as fixed.
