### ISSUE TITLE
Error while mobile:tap in android with javascript

### ISSUE THREAD

**Issue by shashikumarraja** [appium/appium#8006]
## The problem

Getting error message when trying to tap on a particular coordinate on the screen.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Desktop OS/version used to run Appium:Ubuntu 16.04
* Node.js version (unless using Appium.app|exe):7.7.1
* Mobile platform/version under test:Android/6.0.1
* Real device or emulator/simulator:Real Device

## Link to Appium logs

/session/:sessionID/execute {"script":"mobile: tap","args":[{"x":210,"y":1272}]}
{"message":"[execute(\"mobile: tap\",[{\"x\":210,\"y\":1272}])] Error response status: 13, , UnknownError - An unknown server-side error occurred while processing the command. Selenium error: Method has not yet been implemented","status":13,"cause":{"status":13,"value":{"message":"Method has not yet been implemented"},"sessionId":"a46348c6-5880-44cf-9890-f020d2a0810d"},"jsonwire-error":{"status":13,"summary":"UnknownError","detail":"An unknown server-side error occurred while processing the comm...

## Code To Reproduce Issue [ Good To Have ]
` exports.selectLocationFromAutoComplete` = function (driver) {
    return driver.elementById(this.enterLocationTextBox).getLocation()
        .then(function (location) {
            console.log('location is'.green,location);  
            el = driver.elementById(this.enterLocationTextBox);
            var tapOpts = {
                x: location.x, // in pixels from left
                y: location.y - 100, // in pixels from top
                element: el.value // the id of the element we want to tap
            };
            return driver.execute("mobile: tap", [tapOpts],function(err,res){
                if(err){
                    console.log(err)
                }
                else{
                    console.log(res);
                }
                
            })

        });

};`

**Comment by mykola-mokhnach** [comment]
"mobile: tap" is not supported in 1.6.3
Try 1.6.4-beta with TouchAction chain _press-release_ or _tap-release_

**Comment by shashikumarraja** [comment]
I was able to solve this issue using
`exports.selectLocationFromAutoComplete = function (driver) {
    return driver.elementById(this.enterLocationTextBox).getLocation()
        .then(function (location) {
            el = driver.elementById(this.enterLocationTextBox);
            var tapOpts = {
                x: location.x, // in pixels from left
                y: location.y - 100 // in pixels from top
            };
            //steps to perform tap action on the screen
            var action = new TouchAction(driver);
            action.tap(el.value, tapOpts);
            action.perform();
        })

};`
