### ISSUE TITLE
Chrome Browser Opens and Close without hitting the URL

### ISSUE THREAD

**Issue by srinuplr** [appium/appium#8007]
## The problem
I am trying to launch chrome browser in android emulator from my windows machine, then the browser opens and  a url "data;" is running and closes after 1 minute.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Windows 7 64bit
* Node.js version (unless using Appium.app|exe): v6.9.4
* Mobile platform/version under test:Android 6.0
* Real device or emulator/simulator: emulator,Nexus One
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[Appium] Welcome to Appium v1.6.3 (REV 0824f9d4bc9d980b0a8c79de7db5f625c134b60e)
[Appium] Non-default server args:
[Appium]   address: '127.0.0.1'
[Appium]   sessionOverride: true
[Appium]   debugLogSpacing: true
[Appium]   defaultCommandTimeout: 7200
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"Chrome","appiumVersion":"1.6.3","platformName":"android","platformVersion":"6.0","deviceName":"Android Emulator","avd":"Android_Phone","avdArgs":"-dns-server 8.8.8.8","appPackage":"com.android.chrome","appActivity":"com.google.android.apps.chrome.Main","automationName":"Appium","waitforTimeout":30000,"commandTimeout":30000,"chromeOptions":{"args":["start-maximized","disable-extensions"]},"requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"}}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"Chrome","appiumVersion":"1.6.3","platformName":"android","platformVersion":"6.0","deviceName":"Android Emulator","avd":"Android_Phone","avdArgs":"-dns-server 8.8.8.8","appPackage":"com.android.chrome","appActivity":"com.google.android.apps.chrome.Main","automationName":"Appium","waitforTimeout":30000,"commandTimeout":30000,"chromeOptions":{"args":["start-maximized","disable-extensions"]},"requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"}},null,null,null,null]
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   javascriptEnabled: true
[Appium]   locationContextEnabled: true
[Appium]   handlesAlerts: true
[Appium]   rotatable: true
[Appium]   browserName: 'Chrome'
[Appium]   appiumVersion: '1.6.3'
[Appium]   platformName: 'android'
[Appium]   platformVersion: '6.0'
[Appium]   deviceName: 'Android Emulator'
[Appium]   avd: 'Android_Phone'
[Appium]   avdArgs: '-dns-server 8.8.8.8'
[Appium]   appPackage: 'com.android.chrome'
[Appium]   appActivity: 'com.google.android.apps.chrome.Main'
[Appium]   automationName: 'Appium'
[Appium]   waitforTimeout: 30000
[Appium]   commandTimeout: 30000
[Appium]   chromeOptions: { args: [ 'start-maximized', 'disable-extensions' ] }
[Appium]   requestOrigins: { url: 'http://webdriver.io',
  version: '4.6.2',
  name: 'webdriverio' }
[debug] [AndroidDriver] AndroidDriver version: 1.10.38
[BaseDriver] The following capabilities were provided, but are not recognized by appium: javascriptEnabled, locationContextEnabled, handlesAlerts, rotatable, appiumVersion, waitforTimeout, commandTimeout, requestOrigins.
[BaseDriver] Session created with session id: d8005a4b-7534-4521-af9b-1e0612805226
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_111

[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe
[debug] [ADB] Trying to find Android_Phone emulator
[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] 1 emulator(s) connected
[debug] [ADB] Sending telnet command to device: avd name
[debug] [ADB] Getting running emulator port
[debug] [ADB] Socket connection to device created
[debug] [ADB] Socket connection to device ready
[debug] [ADB] Telnet command got response: Android_Phone
[debug] [ADB] Found emulator Android_Phone in port 5554
[debug] [ADB] Setting device id to emulator-5554
[debug] [AndroidDriver] Not launching AVD because it is already running.
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe
[debug] [ADB] Setting device id to emulator-5554
[AndroidDriver] App file was not listed, instead we're going to run com.android.chrome directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","com.android.chrome"]
[AndroidDriver] Starting Android session
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","install","C:\\Users\\wsebastian\\git\\metlife_aut_dexMObIntel\\node_modules\\appium\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk"]
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","install","C:\\Users\\wsebastian\\git\\metlife_aut_dexMObIntel\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk"]
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","getprop","ro.build.version.release"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","dumpsys","window"]
[AndroidDriver] Screen already unlocked, doing nothing
[AndroidDriver] No app sent in, not parsing package/activity
[debug] [AndroidDriver] No app capability. Assuming it is already on the device
[debug] [AndroidDriver] Running fast reset (stop and clear)
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","com.android.chrome"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","clear","com.android.chrome"]
[debug] [AndroidBootstrap] Watching for bootstrap disconnect
[debug] [ADB] Forwarding system: 4724 to device: 4724
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","forward","tcp:4724","tcp:4724"]
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","push","C:\\Users\\wsebastian\\git\\metlife_aut_dexMObIntel\\node_modules\\appium\\node_modules\\appium-android-bootstrap\\bootstrap\\bin\\AppiumBootstrap.jar","/data/local/tmp/"]
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","emulator-5554","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.android.chrome","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[debug] [UiAutomator] Moving to state 'online'
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Loading json...
[AndroidBootstrap] Android bootstrap socket is now connected
[AndroidDriver] Starting a chrome-based browser session
[debug] [AndroidDriver] A port was not given, using random port: 8000
[debug] [Chromedriver] Changed state to 'starting'
[Chromedriver] Set chromedriver binary as: C:\Users\wsebastian\git\metlife_aut_dexMObIntel\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe
[Chromedriver] Killing any old chromedrivers, running: FOR /F "usebackq tokens=5" %a in (`netstat -nao ^| findstr /R /C:"8000 "`) do (FOR /F "usebackq" %b in (`TASKLIST /FI "PID eq %a" ^| findstr /I chromedriver.exe`) do (IF NOT %b=="" TASKKILL /F /PID %a))
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Registered crash watchers.
[Chromedriver] No old chromedrivers seemed to exist
[Chromedriver] Spawning chromedriver with: C:\Users\wsebastian\git\metlife_aut_dexMObIntel\node_modules\appium\node_modules\appium-chromedriver\chromedriver\win\chromedriver.exe --url-base=wd/hub --port=8000 --adb-port=5037
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Client connected
[Chromedriver] [STDOUT] Starting ChromeDriver 2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed) on port 8000
Only local connections are allowed.
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8000/wd/hub/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"\",\"status\":0,\"value\":{\"build\":{\"version\":\"alpha\"},\"os\":{\"arch\":\"x86_64\",\"name\":\"Windows NT\",\"version\":\"6.1.7601 SP1\"}}}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://127.0.0.1:8000/wd/hub/session] with body: {"desiredCapabilities":{"chromeOptions":{"androidPackage":"com.android.chrome","args":["start-maximized","disable-extensions"],"androidDeviceSerial":"emulator-5554"}}}
[HTTP] <-- POST /wd/hub/session - - ms - - 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"Chrome","appiumVersion":"1.6.3","platformName":"android","platformVersion":"6.0","deviceName":"Android Emulator","avd":"Android_Phone","avdArgs":"-dns-server 8.8.8.8","appPackage":"com.android.chrome","appActivity":"com.google.android.apps.chrome.Main","automationName":"Appium","waitforTimeout":30000,"commandTimeout":30000,"chromeOptions":{"args":["start-maximized","disable-extensions"]},"requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"}}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"Chrome","appiumVersion":"1.6.3","platformName":"android","platformVersion":"6.0","deviceName":"Android Emulator","avd":"Android_Phone","avdArgs":"-dns-server 8.8.8.8","appPackage":"com.android.chrome","appActivity":"com.google.android.apps.chrome.Main","automationName":"Appium","waitforTimeout":30000,"commandTimeout":30000,"chromeOptions":{"args":["start-maximized","disable-extensions"]},"requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"}},null,null,null,null,null,null]
[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"280697c4dd97a3b9868d8dcb7185f5fa","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedriverVersion":"2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed)"},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":true,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"pageLoadStrategy":"normal","platform":"ANDROID","rotatable":false,"takesHeapSnapshot":true,"takesScreenshot":true,"version":"53.0.2785.124","webStorageEnabled":true}}
[debug] [Chromedriver] Changed state to 'online'
[Appium] New AndroidDriver session created successfully, session d8005a4b-7534-4521-af9b-1e0612805226 added to master session list
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   javascriptEnabled: true
[Appium]   locationContextEnabled: true
[Appium]   handlesAlerts: true
[Appium]   rotatable: true
[Appium]   browserName: 'Chrome'
[Appium]   appiumVersion: '1.6.3'
[Appium]   platformName: 'android'
[Appium]   platformVersion: '6.0'
[Appium]   deviceName: 'Android Emulator'
[Appium]   avd: 'Android_Phone'
[Appium]   avdArgs: '-dns-server 8.8.8.8'
[Appium]   appPackage: 'com.android.chrome'
[Appium]   appActivity: 'com.google.android.apps.chrome.Main'
[Appium]   automationName: 'Appium'
[Appium]   waitforTimeout: 30000
[Appium]   commandTimeout: 30000
[Appium]   chromeOptions: { args: [ 'start-maximized', 'disable-extensions' ] }
[Appium]   requestOrigins: { url: 'http://webdriver.io',
  version: '4.6.2',
  name: 'webdriverio' }
[Appium] Session override is on. Deleting other sessions.
[Appium]     Deleting session 'd8005a4b-7534-4521-af9b-1e0612805226'
[debug] [AndroidDriver] Shutting down Android driver
[debug] [AndroidDriver] Stopping chromedriver for context CHROMIUM
[debug] [Chromedriver] Changed state to 'stopping'
[debug] [JSONWP Proxy] Proxying [DELETE /] to [DELETE http://127.0.0.1:8000/wd/hub/session/280697c4dd97a3b9868d8dcb7185f5fa] with no body
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":true,"warnings":{},"desired":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"browserName":"Chrome","appiumVersion":"1.6.3","platformName":"android","platformVersion":"6.0","deviceName":"Android Emulator","avd":"Android_Phone","avdArgs":"-dns-server 8.8.8.8","appPackage":"com.android.chrome","appActivity":"com.google.android.apps.chrome.Main","automationName":"Appium","waitforTimeout":30000,"commandTimeout":30000,"chromeOptions":{"args":["start-maximized","disable-extensions"]},"requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"}},"handlesAlerts":true,"rotatable":true,"browserName":"Chrome","appiumVersion":"1.6.3","platformName":"android","platformVersion":"6.0","deviceName":"emulator-5554","avd":"Android_Phone","avdArgs":"-dns-server 8.8.8.8","appPackage":...
[debug] [JSONWP Proxy] Got response with status 200: "{\"sessionId\":\"280697c4dd97a3b9868d8dcb7185f5fa\",\"status\":0,\"value\":null}"
[debug] [Chromedriver] Changed state to 'stopped'
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","input","keyevent",3]
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [UiAutomator] UiAutomator shut down normally
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","ps"]
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Moving to state 'stopped'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","am","force-stop","io.appium.unlock"]
[debug] [Logcat] Stopping logcat capture
[debug] [AndroidDriver] Not cleaning generated files. Add `clearSystemFiles` capability if wanted.
[Appium] Removing session d8005a4b-7534-4521-af9b-1e0612805226 from our master session list
[debug] [AndroidDriver] AndroidDriver version: 1.10.38
[BaseDriver] The following capabilities were provided, but are not recognized by appium: javascriptEnabled, locationContextEnabled, handlesAlerts, rotatable, appiumVersion, waitforTimeout, commandTimeout, requestOrigins.
[BaseDriver] Session created with session id: 4de8e302-fc20-4c9c-b07d-f6dce2b84616
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_111

[AndroidDriver] We're going to run a Chrome-based session
[AndroidDriver] Chrome-type package and activity are com.android.chrome and com.google.android.apps.chrome.Main
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe
[debug] [ADB] Trying to find Android_Phone emulator
[debug] [ADB] Getting connected emulators
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] 1 emulator(s) connected
[debug] [ADB] Sending telnet command to device: avd name
[debug] [ADB] Getting running emulator port
[debug] [ADB] Socket connection to device created
[debug] [ADB] Socket connection to device ready
[debug] [ADB] Telnet command got response: Android_Phone
[debug] [ADB] Found emulator Android_Phone in port 5554
[debug] [ADB] Setting device id to emulator-5554
[debug] [AndroidDriver] Not launching AVD because it is already running.
[AndroidDriver] Using device: emulator-5554
[ADB] Checking whether adb is present
[ADB] Using adb.exe from C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe
[debug] [ADB] Setting device id to emulator-5554
[AndroidDriver] App file was not listed, instead we're going to run com.android.chrome directly on the device
[debug] [AndroidDriver] Checking whether package is present on the device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","pm","list","packages","com.android.chrome"]
[AndroidDriver] Starting Android session
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","install","C:\\Users\\wsebastian\\git\\metlife_aut_dexMObIntel\\node_modules\\appium\\node_modules\\io.appium.settings\\bin\\settings_apk-debug.apk"]
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Running 'C:\Users\wsebastian\AppData\Local\Android\sdk\platform-tools\adb.exe' with args: ["-P",5037,"-s","emulator-5554","install","C:\\Users\\wsebastian\\git\\metlife_aut_dexMObIntel\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk"]
[HTTP] <-- POST /wd/hub/session - - ms - - 

## Code To Reproduce Issue [ Good To Have ]

 capabilities: [
        {
            browserName: 'Chrome', // 'Chrome',
            appiumVersion: '1.6.3',
            platformName: 'android',
            platformVersion: '6.0',
            deviceName: 'Android Emulator',
            avd: 'Android_Phone',     //'Android_Phone',
            avdArgs: '-dns-server 8.8.8.8',
            app: undefined, // will be set later
            appPackage: 'com.android.chrome',
            appActivity: 'com.google.android.apps.chrome.Main',
            automationName: 'Appium',
            //autoWebview: true,
            waitforTimeout: 30000,
            commandTimeout: 30000
        }
    ],

**Comment by mykola-mokhnach** [comment]
I suppose it is not needed to provide _app*_ capabilities if _browserName_ is already set

**Comment by srinuplr** [comment]
I tried by removing app* capability but still facing the same issue.
and
Once browser closes it showing error message "Couldn't connect to selenium server"

**Comment by jlipps** [comment]
Please try with these caps:
```
{
browserName: 'Chrome',
appiumVersion: '1.6.4',
platformName: 'android',
platformVersion: '6.0',
deviceName: 'Android Emulator',
avd: 'Android_Phone',
avdArgs: '-dns-server 8.8.8.8',
waitforTimeout: 30000,
commandTimeout: 30000
}
```
(and try with latest appium, 1.6.4)
