### ISSUE TITLE
handle new webdriver spec capabilities structure

### ISSUE THREAD

**Issue by jlipps** [appium/appium#8009]
The new webdriver spec does away with the current new session object which looks like:

```
{
  "desiredCapabilities": {...},
  "requiredCapabilities": {...}
}
```

And is replacing it with something like:

```
{
  "capabilities": {
    "alwaysMatch": {...},
    "firstMatch": [...]
  }
}
```

I haven't read the [processing algorithm](https://www.w3.org/TR/webdriver/#processing-capabilities) in detail but it looks like at the least we will need to support clients which are sending the new type of request. This will mean changes in basedriver.

At this point I am not sure whether we just want to take `capabilities.alwaysMatch` to be the new `desiredCapabilities` or if we should go through the whole algorithm to respect the semantics of these new keys.

**Comment by TikhomirovSergey** [comment]
👣 (watching)...
