### ISSUE TITLE
Elements are not found with explicit wait

### ISSUE THREAD

**Issue by ferhorv** [appium/appium#8012]
## The problem

Whenever I have an explicit wait for an element which will be present after some time, it will be not located by Appium.

## Environment

* Appium version (or git revision) that exhibits the issue: v1.6.3
* Last Appium version that did not exhibit the issue (if applicable): v1.4.13
* Desktop OS/version used to run Appium: Windows 7 Enterprise SP1
* Node.js version (unless using Appium.app|exe): v6.9.5
* Mobile platform/version under test: 7.1.1
* Real device or emulator/simulator: Nexus 5X
* Appium CLI or Appium.app|exe: CLI

## Details

With an explicit wait for an element the test fails with timeout as the searched element will be not found with the driver.findElement() attempts. It looks like UIAutomator does not get the the updated UI, although the element is already present. (Maybe the accessibility cache clear is missing?)

With an implicit wait of 10 seconds before findElement it works, as the element exists when executing findElement.

## Link to Appium logs

https://gist.github.com/dpgraham/4a994de495b245f6c2262441ff8e8a46

## Code To Reproduce Issue [ Good To Have ]

```
private static final long POLL_INTERVAL = 1000;
Wait<AppiumDriver<MobileElement>> wait = new FluentWait<>(this.appiumDriver)
				.withTimeout(timeout, TimeUnit.SECONDS)
				.pollingEvery(POLL_INTERVAL, TimeUnit.MILLISECONDS)
				.ignoring(NoSuchElementException.class, StaleElementReferenceException.class);
		WebElement element;

		try {
			element = wait.until(presenceOfElementLocated(locator));
		} catch (TimeoutException e) {
			LOG.debug("Element with locator {} was not present after {} seconds", locator, timeout, e);
			element = null;
		} catch (WebDriverException e) {
			LOG.warn("Could not determine presence of element with locator {} after {} seconds", locator, timeout, e);
			throw e;
		}
```

**Comment by dpgraham** [comment]
@ferhorv I copied your .txt to a Gist (https://gist.github.com/dpgraham/4a994de495b245f6c2262441ff8e8a46)

Which lines in the server logs are the problems happening?

**Comment by vikramvi** [comment]
@ferhorv try getPageSource() along with temporary sleep( ) and check if element is really present

**Comment by ferhorv** [comment]
@dpgraham the first findElement() is in line 871 and the last attempt is in line 1411 where the Wait is timed out.
It is also reproducible with Appium 1.6.4-beta.

**Comment by ferhorv** [comment]
@vikramvi When I do a gerPageSource while I am waiting for my condition to be satisfied Appium the element will be successfully located after it is present.
I added a getPageSource() to my Condition presenceOfElementLocated.

So this way it works:
[withGetPageSource.txt](https://github.com/appium/appium/files/833551/withGetPageSource.txt)

Without getPageSource it is timed out:
[withoutGetPageSource.txt](https://github.com/appium/appium/files/833552/withoutGetPageSource.txt)

**Comment by milos2905** [comment]
Hi guys, I'm having same problem with Appium 1.6.3 running test on real device, iPhone 6 iOS 10.2.1. I'm writing script in Python and I couldn't find getPageSource() method in driver. Could anyone help? Thanks

**Comment by dpgraham** [comment]
@ferhorv 
```java
.withTimeout(timeout, TimeUnit.SECONDS)
```

What is 'timeout' set to? In the logs it's saying `waiting up to 0 ms for condition`. 

@milos2905 The python client has a different API, check the API docs for the python version of 'getPageSource'

**Comment by milos2905** [comment]
Hi @dpgraham , thank you for response. I was cheking in my project and on https://github.com/appium/python-client/blob/master/appium/webdriver/webdriver.py and there isn't that method. Any idea?

**Comment by imurchie** [comment]
It's part of the standard selenium python client, which Appium's client extends.

http://selenium-python.readthedocs.io/api.html?highlight=page_source#selenium.webdriver.remote.webdriver.WebDriver.page_source
