### ISSUE TITLE
No response from screenshot request

### ISSUE THREAD

**Issue by rossjohnson90** [appium/appium#8014]
## The problem
I'm trying to test a native hybrid app when I attempt to take a screenshot it appears as though appium is not receiving a response

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.0 & 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: Android 7.0 emulator + 6.0.1 real device
* Real device or emulator/simulator: ^
* Appium CLI or Appium.app|exe: appium cmd line (installed by webdriver manager)

## Details

I'm using protractor + cucumbers + typescript
```
browser.takeScreenshot().then(function (png) {
```

The code within the `.then` never executes presumably because it appears no response ever comes back from the screenshot request

## Link to Appium logs
https://gist.github.com/rossjohnson90/bcef8ca203b55fd18cd0ef29f505b8f1

## Code To Reproduce Issue [ Good To Have ]
Added some snippets above but can set one of these up if it is needed

**Comment by mykola-mokhnach** [comment]
The logs says the screenshot API call succeeds, but the following executeScript method

```
window.localStorage.clear()
```

freezes and causes socket timeout.

**Comment by rossjohnson90** [comment]
Really? theres no line similar to [JSONWP Proxy] Got response with status 200: {"sessionId":"511737fab9ee1...

After the screenshot call?

**Comment by mykola-mokhnach** [comment]
Probably it has something to do with the fact, that local storage cleanup is executed while screenshot is still in progress. Is there anything suspicious in logcat output?

**Comment by rossjohnson90** [comment]
@mykola-mokhnach removed the local storage clearing and updated the gist with the new log

**Comment by mykola-mokhnach** [comment]
Ok I see one issue in the log, which should not happen:

```
[ADB] Error: Unable to get pids for uiautomator. Orginial error: this.shell(...).trim is not a function
```

But there is nothing, which says anything about why screenshoting may freeze. As I said it might be useful to see the [device log](https://forum.xda-developers.com/showthread.php?t=1726238) while this issue happens.

**Comment by mykola-mokhnach** [comment]
@jlipps FYI

**Comment by rossjohnson90** [comment]
I managed to solve this it was due to attempting to take the screenshot in the webview context some kind of clear error message would have made it easier to find the issue sooner
`wdBrowser.contexts().then((con)=>{
            wdBrowser.context(con[0]).then(() => {
                browser.takeScreenshot().then(function (png) {
                    var decodedImage = new Buffer(png.replace(/^data:image\/(png|gif|jpeg);base64,/,''), 'base64');
                    scenario.attach(decodedImage, 'image/png');
                    wdBrowser.context(con[1]).then(callback);
                });
            });
        })`

**Comment by mykola-mokhnach** [comment]
I don't think it is possible to provide better error message, since the timeout happens on the lower level and it simply stops responding to us.
