### ISSUE TITLE
After " npm uninstall -g appium && npm install -g appium@beta" folder WebDriverAgent is missing 

### ISSUE THREAD

**Issue by shapovalovei** [appium/appium#8015]
## The problem

After " npm uninstall -g appium && npm install -g appium@beta" folder WebDriverAgent is missing 

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: OS X Sierra 10.12.1

**Comment by imurchie** [comment]
What is the directory structure that gets installed?

**Comment by shapovalovei** [comment]
@imurchie thanks for quick answer. 
Tomorrow I attache "directory structure" and install.

**Comment by kenmcc** [comment]
I saw the same this morning with 1.6.4 beta
had to git clone the webdriveragent into the right place and then it was ok

**Comment by imurchie** [comment]
I think there was something wrong with npm this morning. I replicated it and now cannot.

**Comment by kenmcc** [comment]
yeah tried to reproduce now to give the logs but seems ok

**Comment by imurchie** [comment]
¯\_(ツ)_/¯

Closing for now. Re-open if it happens again.

**Comment by shapovalovei** [comment]
Thanks for answer. Today I reinstall appium-beta with npm and problem resolved.
