### ISSUE TITLE
sometimes unable to find an element by absolute xpath

### ISSUE THREAD

**Issue by adfghzhang** [appium/appium#8020]
## The problem
![qq 20170310164447](https://cloud.githubusercontent.com/assets/20984179/23788311/edfd1006-05b0-11e7-8972-0518efb65fe0.png)

## the xpath:

//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeTextField[1]

I test it in another framework  [openatx-facebook-wda](https://github.com/openatx/facebook-wda), this xpath works right. 
And when I use appium desktop to send keys in this element it also works right.

## the logs in appium desktop:

[HTTP] --> POST /wd/hub/session/dc45eb17-99dc-4a95-ab28-b22de24e2a1a/element {"using":"xpath","value":"//*[1]//*[1]//*[1]//*[1]//*[1]//*[1]//*[2]//*[1]//*[1]//*[3]//*[3]//*[2]"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//*[1]//*[1]//*[1]//*[1]//*[1]//*[1]//*[2]//*[1]//*[1]//*[3]//*[3]//*[2]","dc45eb17-99dc-4a95-ab28-b22de24e2a1a"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/025D1FD8-8071-4A8A-98CD-9C6FCB30FD46/element] with body: {"using":"xpath","value":"//*[1]//*[1]//*[1]//*[1]//*[1]//*[1]//*[2]//*[1]//*[1]//*[3]//*[3]//*[2]"}
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"3E788D80-6DE1-46D0-B923-FDC538982519","type":"XCUIElementTypeTextField","label":""},"sessionId":"025D1FD8-8071-4A8A-98CD-9C6FCB30FD46","status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"3E788D80-6DE1-46D0-B923-FDC538982519","type":"XCUIElementTypeTextField","label":""}
[HTTP] <-- POST /wd/hub/session/dc45eb17-99dc-4a95-ab28-b22de24e2a1a/element 200 906 ms - 167 
[HTTP] --> POST /wd/hub/session/dc45eb17-99dc-4a95-ab28-b22de24e2a1a/element/3E788D80-6DE1-46D0-B923-FDC538982519/value {"value":["231321321"]}
[MJSONWP] Calling AppiumDriver.setValue() with args: [["231321321"],"3E788D80-6DE1-46D0-B923-FDC538982519","dc45eb17-99dc-4a95-ab28-b22de24e2a1a"]
[XCUITest] Executing command 'setValue'
[JSONWP Proxy] Proxying [POST /element/3E788D80-6DE1-46D0-B923-FDC538982519/value] to [POST http://localhost:8100/session/025D1FD8-8071-4A8A-98CD-9C6FCB30FD46/element/3E788D80-6DE1-46D0-B923-FDC538982519/value] with body: {"value":["2","3","1","3","2","1","3","2","1"]}
[JSONWP Proxy] Got response with status 200: {"status":0,"id":"3E788D80-6DE1-46D0-B923-FDC538982519","value":"","sessionId":"025D1FD8-8071-4A8A-98CD-9C6FCB30FD46"}
[MJSONWP] Responding to client with driver.setValue() result: null
[HTTP] <-- POST /wd/hub/session/dc45eb17-99dc-4a95-ab28-b22de24e2a1a/element/3E788D80-6DE1-46D0-B923-FDC538982519/value 200 4769 ms - 76 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3 and 1.6.4beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS 10.12
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

[HTTP] --> POST /wd/hub/session/d449d39b-3ecd-49ef-a883-50c6b7740482/element {"using":"xpath","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeTextField[1]"}
[debug] [MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeTextField[1]","d449d39b-3ecd-49ef-a883-50c6b7740482"]
[debug] [XCUITest] Executing command 'findElement'
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, accessibility id
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/6EAA8F2E-B519-472A-A588-D23C73EDF893/element] with body: {"using":"xpath","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeTextField[1]"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"using":"xpath","value":"//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeTextField[1]","description":"unable to find an element"},"sessionId":"6EAA8F2E-B519-472A-A588-D23C73EDF893","status":7}
[HTTP] <-- POST /wd/hub/session/d449d39b-3ecd-49ef-a883-50c6b7740482/element 500 724 ms - 164

**Comment by vikramvi** [comment]
never use absolute xpath, instead use relative xpath and try again. 

AccessibilityID or just ID is best in case you don't have them use something like below

`//XCUIElementTypeTabBar[1]/XCUIElementTypeButton[contains(@label,'unique_name')]`

**Comment by dpgraham** [comment]
@adfghzhang On Appium Desktop what shows up in the inspector isn't always the same as what is in the app, because the app view hierarchy can change and it has no way of broadcasting that it has changed to the inspector.

If this happens, hit the `refresh` button and then try it again.
