### ISSUE TITLE
Execute asyncScript iPad 1 Mini does not return result .. test hangs   appium 1.6.3

### ISSUE THREAD

**Issue by nikolmarku** [appium/appium#8022]
## The problem
Does appium 1.6.3 support executeAsync script ?

Open url and execute the command:
Object result = ((JavascriptExecutor) getWebDriver()).executeAsyncScript("var c = arguments[0];alert(c);c(1);");

or any other JS script ....

Test hangs ... no response received and grid not notified of response ... 

Could be related to: https://github.com/webdriverio/webdriverio/issues/999

Running test on real device
Platform :iOS,
 Version :9.3.5, 
Browser name :Safari, 
DeviceName :iPad 1 mini, 
CurrentBrowserName :Safari
java-client : 4.0.0

selenium 2.53 or 3.1.0

## Environment
* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: iOS 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:  iPad 1 mini 9.3.5
* Real device or emulator/simulator:  Real   safari test
* Appium CLI or Appium.app|exe:

Thank you for your Advice.

**Comment by imurchie** [comment]
It should be working, yes. Without logs it's hard to say. Can you try a minimal example (go to your page, try the async code, perhaps) and post a link to a [gist](https://gist.github.com) of the logs?

**Comment by nikolmarku** [comment]
Hi,
Thank you for looking into this ... I have attached the files below .. I updated node to latest 7.7.2 but still same error ... test are run using selenium grid ... 

When I run the simple javascript ... I see the popup in the browser but my test code run forever .. is not notified back of the error show on appium server

The other test code is my test and it hangs forever even though appium server has executed the script or it shows so ...

Thanks 


Let me know if you need more info ... 


[jsAsyncError.txt](https://github.com/appium/appium/files/834529/jsAsyncError.txt)
[jsAsyncErrorSimpleScript.txt](https://github.com/appium/appium/files/834528/jsAsyncErrorSimpleScript.txt)

**Comment by jlipps** [comment]
@nikolmarku can you please upload these files as a [gist](https://gist.github.com) instead? it's not advisable for us to open random files downloaded from the internet.
