### ISSUE TITLE
UIAutomator2 - getAttribute("name") returns different value text argument

### ISSUE THREAD

**Issue by saikrishna321** [appium/appium#8023]
@sravanmedarapu @dpgraham 

Using UIAutomator1 legacy driver, when i use the code 

```
driver.findElementByXPath(".//*[@text='admin']").getAttribute("name");
```
returns value from content-desc

Using UIAutomator2 the above code, returns value from text field.

To get the value from content-desc i need to use 

```
driver.findElementByXPath(".//*[@text='admin']").getAttribute("contentDescription");
```
https://gist.github.com/saikrishna321/160eaaf5a75001859aca596b5acbf77e
Is this expected ?

**Comment by dpgraham** [comment]
I don't know for sure (@sravanmedarapu knows this stuff better than me, but he's away). I'm pretty sure what happened is that  'name' was an alias for 'content-desc' in UIAutomator1 and now in UIAutomator2 'name' is an alias for 'text'.

**Comment by saikrishna321** [comment]
@dpgraham closing as changes are on UIAutomator2 . @dpgraham Thanks :)
