### ISSUE TITLE
Get same id from application code and test code

### ISSUE THREAD

**Issue by talarari** [appium/appium#8026]
For my tests i need to set some values specifically for the device i will run the test on, before i launch the app, and then have the app pull these values when it launches.
For that i need some kind of unique id for the app installed in this test, that will be known to both the app code and the test code.

Any suggestions on which appium api might provide a solution for this?

I need this mostly for ios, but Android as well.

Thanks

**Comment by mykola-mokhnach** [comment]
Sorry, this is the place for issues, not for questions. Please use Appium forum instead.

Regarding the question - Appium can pass command line parameters and/or send environment variables for the app under test.
