### ISSUE TITLE
Latest appium install 1.6.3 fails on node 6.10.0

### ISSUE THREAD

**Issue by bvedam** [appium/appium#8027]
Have both node 6.10.0 and 6.9.1 installed thru nvm on my Win 8.1 (x64) client.

npm install -g appium failed with EPERM error. Tried multiple times both behind corp proxy and outside of it.
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Program Files\nodejs\
node_modules\appium-doctor\node_modules\appium-support' -> 'C:\Program Files\nod
ejs\node_modules\appium-doctor\node_modules\.appium-support.DELETE'
npm ERR!     at moveAway (C:\Users\bvedamur\AppData\Roaming\nvm\v6.9.1\node_modu
les\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\bvedamur\AppData\Roaming\nvm\v6.9.1\node_m
odules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)

Then switched to 6.9.1 and tried. Worked without any issue.

* Appium version (or git revision) that exhibits the issue: 1.6.3 on node 6.10.0
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3 on node 6.9.1
* Desktop OS/version used to run Appium: Win 8.1 (x64)
* Node.js version (unless using Appium.app|exe): 6.10.0 vs 6.9.1

**Comment by pavanbachu0604** [comment]
Can you trying upgrading node , brew upgrade npm

**Comment by bvedam** [comment]
I do have the latest 6.10.0 LTS release. No v6 release available after that. Tried all the following based on the suggestions offered in the past for this same issue
  - running a cmd window with Admin privileges. 
  - Ran npm cache clean everytime before retrying. 
  - Disable antivirus software

None of these helped. It appears this issue is common with some npm versions on windows and the EPERM error can occur with any NPM module install, not just appium.
https://github.com/npm/npm/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%20EPERM

Here is a latest ref to this issue : https://github.com/npm/npm/issues/15124

Will try out more options but you can close this issue as this doesn't seem to be pertaining to appium.
