### ISSUE TITLE
[appium 1.6.3] click element not performed and server remains stuck

### ISSUE THREAD

**Issue by aeroxr1** [appium/appium#8028]
Using appium I have to found an android native component and I have to click on it.

I found the Android native element using xPath in the following way : 

            >     WebElement element = (new WebDriverWait(driver, 90))
>                         .until(ExpectedConditions.presenceOfElementLocated(By.xpath(getXPath(label,idName))));
>                  element.click(); 

But the server after call click() method stop to respond and remains stuck; and the click is not correctly performed. 
The problems not happened If I get the element position and I do a tap on that location. In this case the server correctly works and the tap is correctly executed.
(The component is not clickable, is inside a clickable framelayout and on a imageview clickable)

The following is the log : 
 
> [debug] [MJSONWP] Calling AppiumDriver.click() with args: ["9","d740b625-33eb-4782-9c5c-61b78f158072"]
> [debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"element:click","params":{"elementId":"9
> "}}
> [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"element:click","params":{"ele
> mentId":"9"}}
> [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
> [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: click
> [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":true}
> [debug] [AndroidBootstrap] Received command result from bootstrap
> [debug] [MJSONWP] Responding to client with driver.click() result: true
> [HTTP] <-- POST /wd/hub/session/d740b625-33eb-4782-9c5c-61b78f158072/element/9/click 200 244873 ms - 76
> [HTTP] --> DELETE /wd/hub/session/d740b625-33eb-4782-9c5c-61b78f158072 {}
> [debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["d740b625-33eb-4782-9c5c-61b78f158072"]
> [debug] [AndroidDriver] Shutting down Android driver

i'm on Windows 10 and i'm using :
Appium v1.6.3
java-client 5.0.0-BETA5 
selenium 3.2
Android version 5.1.1

**Comment by SrinivasanTarget** [comment]
@aeroxr1 We have issues in java-client Beta 5 with Selenium 3.2. Fix is in progress for the same. I suggest to use Beta 4 instead of Beta 5 till we release a new beta version. https://github.com/appium/java-client/issues/594

**Comment by SrinivasanTarget** [comment]
@triager please close
