### ISSUE TITLE
BadParametersError with Selenium 3

### ISSUE THREAD

**Issue by Lightmoor** [appium/appium#8030]
## The problem

 BadParametersError: Parameters were incorrect.

## Environment

* Appium version: 1.6.3 & 1.6.4Beta
* Desktop OS/version used to run Appium: Linux
* Mobile platform/version under test: Android
* Real device

## Details

BadParametersError: Parameters were incorrect. 
When i run Test with Selenium 3.
With Selenium 2 it works fine

## Link to Appium logs
(https://gist.github.com/Lightmoor/1fb341ad73c07e903efb4601ad1aa2bc)

**Comment by mykola-mokhnach** [comment]
Will be fixed by https://github.com/appium/java-client/pull/597

**Comment by szaluk** [comment]
Is this fix included in 5.0.0-BETA6?  I am still getting this error using that version of the Java Client with Appium 1.6.4-beta:

[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id"]} and you sent ["desiredCapabilities","requiredCapabilities","capabilities","alwaysMatch","firstMatch"]

**Comment by dpgraham** [comment]
This is being fixed by: https://github.com/appium/appium/issues/8009

**Comment by abisekkachroo** [comment]
Did any found solution to this 
I tried this with appium version 1.6.2 , 1.6.3 , 1.6.4
Consistent Error is displayed 
[MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["required Capabilities","capabilities","sessionId","id"]} and you sent ["desiredCapabilities","requiredCapabilities","capabilities","alwaysMatch","firstMatch"

**Comment by dpgraham** [comment]
@abisekkachroo We just released 1.6.5 can you try that?

**Comment by dramer** [comment]
@dpgraham  did we fix this with the windows U/I beta 1.6.4? Will we fix it with a new Beta?

**Comment by abisekkachroo** [comment]
@dpgraham 
I resolved the issue by using Selenium Standalone jar 2.53.1
All the errors were fixed and I used 1.6.4 appium version
