### ISSUE TITLE
1.6.4-beta iOS: GetScreenshot() error base-64

### ISSUE THREAD

**Issue by omsting** [appium/appium#8035]
## The problem

Often on iOS I get an error when I take a screenshot with Driver.GetScreenshot() or Driver.TakeScreenshot(). You can find my logs (Appium and Nunit) below in Gist, you'll see that I get an error when the screenshot is basically empty. Sometimes it works for the same test on the same device. Please tell me if you need more information.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 beta
* Desktop OS/version used to run Appium: macOS Sierra 10,12.3
* Node.js version: 3.10.10
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Real device

## Link to Appium logs

https://gist.github.com/omsting/85ac9b3d3d7e0c01ce888fc60e5b39fe#file-gistfile1-txt

**Comment by mykola-mokhnach** [comment]
Please create this issue directly in [WDA project](https://github.com/facebook/WebDriverAgent/issues). It has nothing to do with Appium components.
