### ISSUE TITLE
Cursor appears in the middle of the text instead of at the end

### ISSUE THREAD

**Issue by sp5594** [appium/appium#8037]
I have an hybrid app that requires me to sign in using fb. I`m switching from web view to native view to achieve this.

Problem: When the fb page loads...the email field is already pre-filled. I`m trying to clear it using the code below. However, when I do that, the cursor appears in the middle of the pre-filled text instead of at the end. For ex: facebook123@gmail.com, the cursor is appearing before "com" instead of after com.  The code below works fine except for the cursor`s position.  It clears out the pre-filled text but only facebook123@gmail. and NOT com at the end...because the cursor is in front of it.

This is happening only on iOS 10.2 iPhone 5s. I haven`t noticed this on iphone 6 or 7. 

I`m on appium 1.6.3 xcode 8 

`

        public void setwebfbemail(String webfbemail){
       driver.findElement(ios_fb_webemail).click();
        String isempty = driver.findElement(ios_fb_webemail).getText();
        if(!isempty.equals("")){
            driver.findElement(ios_fb_webemail).clear();
                          }      driver.findElement(ios_fb_webemail).sendKeys(webfbemail);       }

`

**Comment by mykola-mokhnach** [comment]
this might happen because click happens at the center of the text field. Try to use tap by coordinates and perform tap closer to the right side of the text edit to solve the issue.

**Comment by sp5594** [comment]
why is the click happening at the center? Can I use something else besides tap to make the click happen at the end of the pre-filled text?

**Comment by mykola-mokhnach** [comment]
Because this is how webdriver's click works. 
Regarding the other method - maybe it exists, but I don't know about it.

**Comment by jlipps** [comment]
@sp5594 why are you clicking the e-mail box before trying to clear it?
