### ISSUE TITLE
App too big loading from simulator makes the buffer overload

### ISSUE THREAD

**Issue by KingSoares** [appium/appium#8039]
## The problem

My app produced an error with the ipa file containing such a large number of commands that it overloads the buffer to handle the output of the ipa file.

## Environment

* Appium version: 1.6.3
* OSX and iOS
* iOS 9.3
* Real Device

## Details
The appium logs contain:

2017-03-07 09:24:40:616 - info: [debug] Using local .ipa from command line: /tmp/tmpm9T5rE/_SAUCE_SIGNED_Programming.ipa
2017-03-07 09:24:40:616 - info: [debug] Copying local zip to tmp dir
2017-03-07 09:24:41:432 - info: [debug] /tmp/tmpm9T5rE/_SAUCE_SIGNED_Programming.ipa copied to /tmp/11727-1943-b39pyl.fgmn8nnrk9/appium-app.zip
2017-03-07 09:24:41:455 - info: [debug] Unzipping /tmp/11727-1943-b39pyl.fgmn8nnrk9/appium-app.zip
2017-03-07 09:24:41:455 - info: [debug] Testing zip archive: /tmp/11727-1943-b39pyl.fgmn8nnrk9/appium-app.zip
2017-03-07 09:24:46:155 - info: [debug] Zip archive tested clean
2017-03-07 09:24:47:223 - error: Unzip threw error Error: stdout maxBuffer exceeded
2017-03-07 09:24:47:224 - error: Stderr: Archive:  /tmp/11727-1943-b39pyl.fgmn8nnrk9/appium-app.zip
   creating: Payload/
   creating: Payload/X3ApplicationEducationMonoTouch.app/
  inflating: Payload/X3ApplicationEducationMonoTouch.app/Info.plist  
  inflating: Payload/X3ApplicationEducationMonoTouch.app/Icon-76.png  
   creating: Payload/X3ApplicationEducationMonoTouch.app/Checkbox/
 extracting: Payload/X3ApplicationEducationMonoTouch.app/Checkbox/CheckboxTrueToFalse.png  
 extracting: Payload/X3ApplicationEducationMonoTouch.app/Checkbox/CheckboxTrue.png  
  inflating: Payload/X3ApplicationEducationMonoTouch.app/Checkbox/CheckboxFalseToTrue.png  
  inflating: Payload/X3ApplicationEducationMonoTouch.app/Checkbox/CheckboxFalse.png  ...

It is a 400 Mb App.

**Comment by mykola-mokhnach** [comment]
You could unzip your package in the client app and pass unzipped .app to Appium instead of ipa to workaround the problem.

**Comment by mykola-mokhnach** [comment]
@jlipps Unfortunately I did not find any option for teen_process.exec, that allows to change max buffer size (something similar to https://github.com/SaschaGalley/grunt-phpunit/pull/30/files)
Is it possible to add one?

**Comment by mykola-mokhnach** [comment]
This is a helper class we use in our automation framework to wrap the package. Probably, it might be useful for you if you use java client:

```java

    private static final int BUFFER_SIZE = 4096;

    private static void extractFile(ZipInputStream zipIn, File resultFile) throws IOException {
        byte[] bytesIn = new byte[BUFFER_SIZE];
        try (BufferedOutputStream bos = new BufferedOutputStream(new FileOutputStream(resultFile))) {
            int read;
            while ((read = zipIn.read(bytesIn)) != -1) {
                bos.write(bytesIn, 0, read);
            }
        }
    }

    public static File extractAppFromIpa(File ipaFile) throws Exception {
        if (!ipaFile.exists()) {
            throw new IllegalArgumentException(String.format(
                    "Please make sure the file %s exists and is accessible", ipaFile.getCanonicalPath())
            );
        }
        final Path root = Files.createTempDirectory(null);
        Optional<File> result = Optional.empty();
        try (ZipInputStream zis = new ZipInputStream(new FileInputStream(ipaFile))) {
            ZipEntry zipEntry;
            while ((zipEntry = zis.getNextEntry()) != null) {
                try {
                    final String entryName = zipEntry.getName();
                    final File currentPath = new File(root.toString() + File.separator + entryName);
                    if (!result.isPresent() && entryName.endsWith(".app/")) {
                        result = Optional.of(currentPath);
                    }
                    if (entryName.contains(".app")) {
                        if (zipEntry.isDirectory()) {
                            if (!currentPath.mkdirs()) {
                                throw new IllegalStateException(String.format(
                                        "Cannot create %s output folder", currentPath.getCanonicalPath())
                                );
                            }
                        } else {
                            extractFile(zis, currentPath);
                        }
                    }
                } finally {
                    zis.closeEntry();
                }
            }
        }
        return result.orElseThrow(
                () -> new IllegalArgumentException(String.format("Cannot find a compressed .app inside %s",
                        ipaFile.getAbsolutePath()))
        );
    }

.....

public class IOSDistributable {
    private static Map<String, IOSDistributable> instances = new HashMap<>();

    public static IOSDistributable getInstance(String path) {
        if (!instances.containsKey(path)) {
            instances.put(path, new IOSDistributable(path));
        }
        return instances.get(path);
    }

    private File appPath;
    private boolean isAppRootTemporary = false;
    private Optional<String> bundleId = Optional.empty();

    private IOSDistributable(String path) {
        try {
            final File fPath = new File(path);
            if (path.toLowerCase().endsWith(".app")) {
                appPath = fPath;
            } else if (path.toLowerCase().endsWith(".ipa")) {
                appPath = CommonUtils.extractAppFromIpa(fPath);
                isAppRootTemporary = true;
            } else {
                throw new IllegalArgumentException(
                        String.format("Only .ipa and .app packages are supported. %s is given instead", path)
                );
            }
        } catch (Exception e) {
            Throwables.propagate(e);
        }
    }

    public File getAppRoot() {
        return appPath;
    }

    private static String parseBundleId(File plist) throws Exception {
        final NSDictionary rootDict = (NSDictionary) PropertyListParser.parse(plist);
        return rootDict.objectForKey("CFBundleIdentifier").toString();
    }

    public String getBundleId() throws Exception {
        if (!this.bundleId.isPresent()) {
            this.bundleId = Optional.of(parseBundleId(new File(appPath.getCanonicalPath() + "/Info.plist")));
        }
        return this.bundleId.get();
    }

    {
        Runtime.getRuntime().addShutdownHook(new Thread() {
            @Override
            public void run() {
                try {
                    if (isAppRootTemporary) {
                        FileUtils.deleteDirectory(appPath);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }
}
```

how to use it:

```java
        capabilities.setCapability("bundleId", IOSDistributable.getInstance(appPath).getBundleId());
```

**Comment by TheJusticeLeague** [comment]
If you use SauceLabs... Would something like this work, given the fact that you need to have the app in a remote storage?

Also, if you extract the .app file, will all the content from the app not be available then?

**Comment by TheJusticeLeague** [comment]
I have tried to extract manually the app file from the .ipa... then the app file is over 500 Mb... won't I end up in the same problem?

**Comment by mykola-mokhnach** [comment]
ipa file is technically just a simple zip archive. The bug, which affects you, is about executing unzip command in Appium code. You could also wait until it is fixed on server side.

**Comment by imurchie** [comment]
Can you post a [gist](https://gist.github.com) of the full logs?

**Comment by TheJusticeLeague** [comment]
Sure :-)

https://gist.github.com/TheJusticeLeague/bd0febbcc5a5ccb9a17548fc196d8f8c

**Comment by imurchie** [comment]
Ok. So the version is 1.4.16. I would upgrade. This issue has been fixed in more recent versions of Appium.

**Comment by TheJusticeLeague** [comment]
ok ... Great! :-) Since I am running ... only this version seems to work somehow... I will write them a ticket.

Thank you so much.
