### ISSUE TITLE
Touch Actions not Working on iOS

### ISSUE THREAD

**Issue by TheJusticeLeague** [appium/appium#8042]
## The problem

I am trying to make a tap action using the appium driver for iOS using coordinates but it seems to not be working. The tap action just creates no effect. This is both tried on a real device and a simulator.

## Environment

* 1.6.3
* iOS

## Details

boolean tapOnImage(String targetImgPath) {
        Point2D coords = getCoords(takeScreenshot(), targetImgPath)
        println ("Click X: "+coords.getX() + " Y: " + coords.getY())
        if ((coords.getX() >= 0) && (coords.getY() >= 0)) {
            new TouchAction( driver).tap((int) coords.getX(),(int) coords.getY() ).perform()
            //driver.tap(1, (int) coords.getX(), (int) coords.getY(), 500)
            return true
        }
        throw new ElementNotVisibleException("Element not found - " + targetImgPath)
    }

The coordinates are found correctly and it works fine for Android. Driver is an AppiumDriver that gets create as a IOSDriver.

driverInstance = new IOSDriver<>(new Resources().getCloudUrl(new AppUtilities()), caps)

**Comment by mykola-mokhnach** [comment]
Is it the same in 1.6.4-beta?

**Comment by TheJusticeLeague** [comment]
I haven't tried ... but I will

**Comment by oscheller1** [comment]
Can confirm TouchAction isn't working in 1.6.4-beta using the XCUITest `automationName` capability:
```
{WebDriverException}Message: Support for this gesture is not yet implemented. Please contact an Appium dev
```

**Comment by mykola-mokhnach** [comment]
@oscheller1 The set of supported touch actions is quite limited in XCUITest-backed driver. 
You may check 
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/commands/gestures.js
if you want to know exactly which chains are supported.
