### ISSUE TITLE
Swipe from left to right not working in iOS 10.2

### ISSUE THREAD

**Issue by Dheepthi** [appium/appium#8043]
Swipe from left to right not working in iOS 10.2

iOS Version : 10.2
XCode : 8.2.1
Appium : 1.6.3
Mac OS: Sierra

Actual Code to perform swipe:
int right = 500;
        int left = 1;
        int height = 700;
        int swipeDuration = 1000;

        driver.swipe(left, height, right, height, swipeDuration);

Error thrown : 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unhandled endpoint: /session/05F8E1EB-8F93-45CF-9A9E-46FF270E3AE4/uiaTarget/0/dragfromtoforduration -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/05F8E1EB-8F93-45CF-9A9E-46FF270E3AE4/uiaTarget/0/dragfromtoforduration"
    );
}

**Comment by mykola-mokhnach** [comment]
1. Update to appium beta

```
npm uninstall -g appium
npm install -g appium@1.6.4-beta
```

2. Use "mobile: swipe" call:

```java
    JavascriptExecutor js = (JavascriptExecutor) driver;
    HashMap<String, Double> swipeObject = new HashMap<String, Double>();
    swipeObject.put("direction", "right");
// one can also set the particular element to swipe on
// otherwise it will be performed on the XCUIElementTypeApplication UI element
// swipeObject.put("element", el);
    js.executeScript("mobile: swipe", swipeObject);
```

**Comment by Dheepthi** [comment]
Thank you.
Could you also tell me how to specify co-ordinates in this case?

**Comment by Dheepthi** [comment]
When i uninstalled and re-installed appium i'm getting this issue
Viruals-MacBook-Pro:WebDriverAgent virtualmachine$ /usr/local/bin/node /usr/local/Cellar/node/7.7.2/libexec/npm/lib/node_modules/appium/build/lib/main.js -a 127.0.0.1 -p 4723 --app /Users/virtualmachine/Desktop/Automation/Skylight.app --automation-name XCUITest --platform-name iOS --device-name 'iPad Pro' --platform-version=9.3
Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1142:25)
    at Function.Module._resolveLookupPaths (module.js:391:17)
    at Function.Module._resolveFilename (module.js:461:31)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/Cellar/node/7.7.2/libexec/npm/lib/node_modules/appium/build/lib/main.js:21:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by Dheepthi** [comment]
I fixed my last issue.

**Comment by Dheepthi** [comment]
could you help me understand how to do mobile:swipe with co-ordinates?

JavascriptExecutor js = (JavascriptExecutor) driver;
		HashMap<String, String> swipeObject = new HashMap<String, String>();
		swipeObject.put("direction", "right");

like this  driver.swipe(left, height, right, height, swipeDuration);

**Comment by mykola-mokhnach** [comment]
The swipe endpoint does not support coordinates. The only endpoint, which supports coordinates is **drag**. For now this can be achieved by executing invoking _press-wait-moveto-release-perform_ touch action.

**Comment by Dheepthi** [comment]
Thank you mykola.
 driver.swipe(left, height, right, height, swipeDuration); is internally taken as press-wait-moveto-release-perform in Appium1.6.4-beta.

Thank you this solved my problem. 
I'm able to perform swipe with coordinated using driver.swipe(left, height, right, height, swipeDuration);

Thanks for your support i appreciate it

**Comment by vutukuriswathi** [comment]
can u plz let me know how it is resolved.I tried it on appium 1.6.5 on iOS 10.0.But I am still getting the same error as you mentioned.
