### ISSUE TITLE
Appium just opening and closing the app

### ISSUE THREAD

**Issue by sjenasears** [appium/appium#8044]
Below are the code for my appium.
It just opens and closes the app.

DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);

		capabilities.setCapability("appium-version", "1.6.4-beta");
		capabilities.setCapability("platformName", "iOS");
		capabilities.setCapability("platformVersion", "10.2");
		capabilities.setCapability("browserName", "Safari");
		//capabilities.setCapability("automationName", "XCUITest");
		capabilities.setCapability("udid", "84A7914B-4349-4E79-AA88-090F97FAFFC9");
		capabilities.setCapability("deviceName", "iPhone Simulator");
		capabilities.setCapability("noReset", "true");
		capabilities.setCapability("app", "/Users/sjena/Desktop/Relay_Appium/ipa/SYW_Relay.app");

Appium

**Comment by mykola-mokhnach** [comment]
Please fill out the issue reporting template carefully to provide the necessary information and reopen the issue when done.
