### ISSUE TITLE
findElementsByAndroidUIAutomator gives an error "Could not parse UiSelector argument: new Uiselector method expects an argument "

### ISSUE THREAD

**Issue by dilp** [appium/appium#8045]
## The problem
I try to use "findElementsByAndroidUIAutomator "  to extract the all the element using class.

code : 
 List <WebElement> textfeilds=dr.findElementsByAndroidUIAutomator("new Uiselector().className(\"android.widget.EditText\")");

For the same if i use Findby elements its works : 
 List <WebElement> textfeilds =	 dr.findElements(By.className("android.widget.EditText"));

## Environment

* Appium version 1.4.16.1
* Node.js version (unless using Appium.app|exe):3.5.0
* Mobile platform/version under test: Android ,6.0.1
* Real device or emulator/simulator:Real device 

## Details
For the same locator without any issue Findby element by class is working.
But when use  "findElementsByAndroidUIAutomator" its fails. 
Find the error log bellow

## Link to Appium logs

> info: --> POST /wd/hub/session/07c95e88-d199-4dc2-a870-b9957b1dcf93/elements {"using":"-android uiautomator","value":"new Uiselector().className(\"android.widget.EditText\")"}
> info: [debug] Waiting up to 5000ms for condition
> info: [debug] Pushing command to appium work queue: ["find",{"strategy":"-android uiautomator","selector":"new Uiselector().className(\"android.widget.EditText\")","context":"","multiple":true}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new Uiselector().className(\"android.widget.EditText\")","context":"","multiple":true}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding new Uiselector().className("android.widget.EditText") using ANDROID_UIAUTOMATOR with the contextId:  multiple: true
> info: [debug] [BOOTSTRAP] [debug] Parsing selector: new Uiselector().className("android.widget.EditText")
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":9,"value":"Could not parse UiSelector argument: new Uiselector method expects an argument"}
> info: [debug] Responding to client with error: {"status":9,"value":{"message":"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.","origValue":"Could not parse UiSelector argument: new Uiselector method expects an argument"},"sessionId":"07c95e88-d199-4dc2-a870-b9957b1dcf93"}
> info: <-- POST /wd/hub/session/07c95e88-d199-4dc2-a870-b9957b1dcf93/elements 500 13.994 ms - 314 
> info: [debug] Didn't get a new command in 60 secs, shutting down...
> info: Shutting down appium session
> info: [debug] Pressing the HOME button
> info: [debug] executing cmd: C:\Users\uwickdi\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZX1G323XDM shell "input keyevent 3"
> info: [debug] Stopping logcat capture
> info: [debug] Logcat terminated with code null, signal SIGTERM
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"shutdown"}
> info: [debug] [BOOTSTRAP] [debug] Got command of type SHUTDOWN
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
> info: [debug] [BOOTSTRAP] [debug] Closed client connection
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: numtests=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=.
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: current=1
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: 0
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS: stream=
> info: [debug] [UIAUTOMATOR STDOUT] Test results for WatcherResultPrinter=.
> info: [debug] [UIAUTOMATOR STDOUT] Time: 72.493
> info: [debug] [UIAUTOMATOR STDOUT] OK (1 test)
> info: [debug] [UIAUTOMATOR STDOUT] INSTRUMENTATION_STATUS_CODE: -1
> info: [debug] Sent shutdown command, waiting for UiAutomator to stop...
> info: [debug] UiAutomator shut down normally
> info: [debug] Cleaning up android objects

## Code To Reproduce Issue [ Good To Have ]
package com.pearson.eselenium.liverPool.testmob;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.AfterMethod;

import io.appium.java_client.android.AndroidDriver;

public class TestApp {

	AndroidDriver<WebElement> dr;

	@Test
	public void testapp() throws MalformedURLException, InterruptedException {
		
		DesiredCapabilities capabilities = DesiredCapabilities.android();
		
		capabilities.setCapability("deviceName", "motorola-nexus_6-ZX1G323XDM");
		capabilities.setCapability("platformVersion", "6.0.1");
		capabilities.setCapability("platformName", "Android");
		
		// use app package and app activity
		capabilities.setCapability("appPackage", "com.nnacres.app");
		capabilities.setCapability("appActivity", "com.nnacres.app.activity.SplashActivity");

		dr = new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
		dr.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);

		 dr.findElement(By.id("com.nnacres.app:id/imageViewNavigationDrawerMenu")).click();
		 															   
		 
		 //tap on feedback 
		// dr.findElementByAndroidUIAutomator("UiSelector().resourseId(\"com.nnacres.app:id/sectionShortlist\")");
		 dr.scrollToExact("Feedback");
		 dr.findElement(By.id("com.nnacres.app:id/sectionShortlist")).click();
		 
		 //taking  list of web elements 
		// List <WebElement> textfeilds =	 dr.findElements(By.className("android.widget.EditText"));
		 List <WebElement> textfeilds=dr.findElementsByAndroidUIAutomator("new Uiselector().className(\"android.widget.EditText\")");
		 
		 System.out.println("total list of web element " + textfeilds);
		 textfeilds.get(1).sendKeys("this is my  genaral feedback ");

	
		// clicking
		Thread.sleep(10000);

	}

	@AfterMethod
	public void quit() {
		if (dr != null) {
			dr.quit();
		}

	}

}

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
The Appium version you use is outdated. Try Appium 1.6.4-beta

**Comment by imurchie** [comment]
The string passed in is parsed as Java code, and needs to be valid. Try  changing `Uiselector` to `UiSelector`.

**Comment by dilp** [comment]
Thanks a lot @imurchie  Its works once change the UIselector spelling

**Comment by vikramvi** [comment]
@triager please close per last comment

**Comment by Gocoollnath** [comment]
Issue reproducible in Latest appium and Java client versions. Trying to scroll to a particular element in a list view
Code:
	MobileElement element = driver.findElement(MobileBy.AndroidUIAutomator("new UiScrollable(new UiSelector().resourceId(\"ID\")).getChildByText("+ "new UiSelector().resourceId(\"ID\"), \"Text\")"));


Error log:

https://gist.github.com/Gocoollnath/1e00b1bf5036f3885c45d5e07a896230

**Comment by venkateshseerapu** [comment]
@Gocoollnath 

Did u find the solution for your issue?

**Comment by Gocoollnath** [comment]
@venkateshseerapu No
