### ISSUE TITLE
Appium just opening and closing the app

### ISSUE THREAD

**Issue by sjenasears** [appium/appium#8047]
## The problem

While trying to launch my app from from Appium UI or from Script the webdriver app is opening.Then my app is opening for a moment and then closing.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4-beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac Os Sierra
* Node.js version (unless using Appium.app|exe):v7.6.0
* Mobile platform/version under test:IOS  10.2
* Real device or emulator/simulator:Simulator
* Appium CLI or Appium.app|exe: Appium.app|

## Details

The app which i want to test is just opening and closing.

 

## Code To Reproduce Issue [ Good To Have ]

DesiredCapabilities capabilities = new DesiredCapabilities();
			capabilities.setCapability(InternetExplorerDriver.IE_ENSURE_CLEAN_SESSION, true);

			capabilities.setCapability("appium-version", "1.6.4-beta");
			capabilities.setCapability("platformName", "iOS");
			capabilities.setCapability("platformVersion", "10.2");
			capabilities.setCapability("browserName", "Safari");
			//capabilities.setCapability("automationName", "XCUITest");
			capabilities.setCapability("udid", "67840d8ffcb8b2e3d4cc26fa1808087cc2994d01");
			//capabilities.setCapability("deviceName", "iPhone Simulator");
			capabilities.setCapability("deviceName", "iPhone Simulator");
			capabilities.setCapability("noReset", "true");
			//capabilities.setCapability("app", "/Users/sjena/Desktop/Relay_Appium/ipa/SYW_Relay.app");
			capabilities.setCapability("app", "/Users/sjena/Desktop/Relay_Appium/ipa/SYW_Relay.ipa");
			
			try {
				driver = new IOSDriver(new URL("http://0.0.0.0:4723/wd/hub"), capabilities);
				driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
				
				
				driver.close();
			} catch (MalformedURLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			driver.findElement(By.className("Continue")).click();

**Comment by mykola-mokhnach** [comment]
Please attach appium log

**Comment by Brian-Watson** [comment]
Make sure your app was specifically built for the simulator.  This happened to me before too.

**Comment by sjenasears** [comment]
Yes it is for simulator.

Logs are below.
https://gist.github.com/sjenasears/a25541ff84cd56e7484ba52b08ac6df8

**Comment by jlipps** [comment]
@sjenasears there are no errors in that log. Anyway we need the _full_ logs, not just a snippet.
Also you are setting your `app` capability to an ipa file, which is not supported by the simulator.

**Comment by dpgraham** [comment]
The problem is setting app capability to `.ipa` on a Simulator, which is unsupported.

**Comment by rohikris** [comment]
I am facing the same.... ipa app lauch and close.
Please let me know fix for this
