### ISSUE TITLE
IOS 10.X Accessibility Identifier problem

### ISSUE THREAD

**Issue by eyypbgds** [appium/appium#8050]
## The problem

There is a problem with iOS 10 versions not showing accessibility identifiers. When i inspect on ios 9.x versions i see and run test properly but on ios 10 did not find element with same id. Are there any solution ? Thanks.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3 
* Desktop OS/version used to run Appium: Sierra 10.12
* Node.js version (unless using Appium.app|exe): 7.6
* Mobile platform/version under test: 9.3.5 and 10.0.2
* Real device
* Appium CLI 

## Details

![fizy-9 3 5](https://cloud.githubusercontent.com/assets/24698969/24032062/26718598-0af7-11e7-93ae-8d8293183444.png)
![fizy-ios10](https://cloud.githubusercontent.com/assets/24698969/24032064/27ba5560-0af7-11e7-926e-08360b9c2120.png)
![letgo-ios9 3 5](https://cloud.githubusercontent.com/assets/24698969/24032063/27b765f8-0af7-11e7-9237-a3bdebb0ed22.png)
![letgo-ios10](https://cloud.githubusercontent.com/assets/24698969/24032065/27f7a9a6-0af7-11e7-95bb-833221dd9cdc.png)

**Comment by mykola-mokhnach** [comment]
The issue has nothing to do with Appium itself, but rather with your application code. We just show what WDA/XCTest passes to us. You can also check your application using the standard iOS accessibility inspector, which is a built-in tool since Xcode 8+, to make sure these ids are not there.
My suggestion would be to double check it with developers.

**Comment by eyypbgds** [comment]
@mykola-mokhnach thanks for reply, I tried standard iOS accessibility inspector and i can inspect elements.
i encountered a new scenerio about identifiers. When first time inspect i can see all identifiers but after a second i will try inspect again, this time some identifiers (also elements XCUIElementTypeStaticText change to XCUIElementTypeOther) disappear.

First Time
![screen shot 2017-03-17 at 16 31 53](https://cloud.githubusercontent.com/assets/24698969/24045353/d90093ba-0b2f-11e7-9c81-0981a100fc31.png)


Second Time
![screen shot 2017-03-17 at 16 32 03](https://cloud.githubusercontent.com/assets/24698969/24045388/f6d8f346-0b2f-11e7-9220-566a7c41687c.png)

**Comment by mykola-mokhnach** [comment]
Try Appium 1.6.4-beta. It has the newest WDA

**Comment by jlipps** [comment]
In addition, we do not support the inspector you're using. So it looks like either an issue with how the app is developed or the inspector. As @mykola-mokhnach said, try the latest beta as well just in case it helps.
