### ISSUE TITLE
Searching off-screen element by nested xpath doesn't work

### ISSUE THREAD

**Issue by oscheller1** [appium/appium#8051]
## The problem

Searching for
```
'//XCUIElementTypeTable/descendant::XCUIElementTypeCell[@name="settings_debugging_backend_connection_select_hub_region"]/descendant::XCUIElementTypeButton'
```
while the element is not shown on the screen does not work. If the element is shown on screen, the query works just fine.

Error when searching off-screen element shows:
```
selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.
```

On the other hand, 
```
'//XCUIElementTypeCell[@name="settings_debugging_backend_connection_select_hub_region"]'
```
works even if the element is off-screen.

I've investigated this a bit further, and the problem seems to be the `/descendant` filter. Unfortunately we depend on using tight filters like these within our XPaths. Is there a way to make these more complex xpaths work with elements that are off-screen?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta
* Last Appium version that did not exhibit the issue (if applicable): - 
* Desktop OS/version used to run Appium: MacOS 10.12.2
* Node.js version (unless using Appium.app|exe): 6.1.0
* Mobile platform/version under test: 10.2.1
* Real device or emulator/simulator: iPad real device
* Appium CLI or Appium.app|exe: appium CLI

* Appium Client: Python
* Launch parameters `appium -p 1337 -dc '{"newCommandTimeout": 3600, "orientation": "LANDSCAPE"}'`

**Comment by mykola-mokhnach** [comment]
this might fail because the element is really not present in the tree. The query itself does not care about elements visibility. Did you try to print getPageSource output and check the actual xml before executing these queries?

**Comment by oscheller1** [comment]
The element is indeed present in the tree, I just double checked it (using appium inspector).  Any Xpath *not* using `/descendant::` will find the element, so it's clearly there. Just the nested Xpath using `/descendant::` doesn't find it.

**Comment by oscheller1** [comment]
I just used the appium inspector locator feature to try out the nested xpath and it did indeed locate the element correctly. What might cause the problem occuring from the Python client?

**Comment by mykola-mokhnach** [comment]
it might be that your DOM is changed by the app dynamically, so the snapshot you get in the inspector is not the same that you have in the app at the moment of time when lookup is running. Try to use explicit/implicit wait

**Comment by oscheller1** [comment]
Here are some appium logs:

Searching from the python application while the element is not on screen:
![bildschirmfoto 2017-03-17 um 13 28 46](https://cloud.githubusercontent.com/assets/14994408/24044340/291b0fa2-0b1b-11e7-9539-1814355a890a.png)

Searching from the appium inspector locator:
![bildschirmfoto 2017-03-17 um 13 35 39](https://cloud.githubusercontent.com/assets/14994408/24044352/3569fd9a-0b1b-11e7-9898-52ff5bb55e9c.png)

**Comment by oscheller1** [comment]
Small update: I've run the same thing on another iPad and this time the query actually found the appropriate elements (w/ using `descendant`). I'll monitor this problem and watch out for anything that might have caused this on the other iPad.

**Comment by jlipps** [comment]
Thanks @oscheller1 feel free to add more information here in that event. Closing for now.
