### ISSUE TITLE
unable to run against android 7.1.1

### ISSUE THREAD

**Issue by banditgp** [appium/appium#8052]
## The problem

can run against a device running v5.1.1 but unable to run against device running v7.1.1

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: windows 10
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: andrdoi 7.1.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

i'm trying to get my head round installing and running on windows before attempting a more unfamiliar mac, connecting and running a sample ruby script on a device running android 5.1.1 is working fine but does not then work as hoped on a device running android 7.1.1, seems to be getting stuck as below:

[MJSONWP] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'C\:\\Users\\qa\\AppData\\Local\\Android\\sdk\\platform-tools\\adb.exe -P 5037 -s 00d2f51ee2e5462b install C\:\\Users\\qa\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk' exited with code 1'; Stderr: 'Failed to install C:\Users\qa\AppData\Roaming\npm\node_modules\appium\node_modules\appium-unlock\bin\unlock_apk-debug.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package io.appium.unlock signatures do not match the previously installed version; ignoring!]'; Code: '1'

have tried a few things after trolling google but to no avail, any help would be greatly appreciated

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Try to set non-default unlock type like described here: https://github.com/appium/appium-android-driver/blob/master/docs/UNLOCK.md
