### ISSUE TITLE
Find Element by Xpath for Hybrid app in iOS takes a lot of time

### ISSUE THREAD

**Issue by poorvikamahesh** [appium/appium#8053]
Hello,

I am currently in the process of automating a Hybrid application. Few pages in the app have a WebView with a lot of data. One particular page has 50 + links which I need to validate.

I am using a common xpath -
//XCUIElementTypeStaticText[@name='DATA_TO_REPLACE']
I replace the name with the actual display text in the above xpath to validate if the element is present in the screen or not using driver.findElement by xpath.

Since this is a web view, none of the links have an accessibility ID.

Currently, each link validation takes 1 min.

Is there a faster way of doing this?

Environment : 

* Appium version - 1.6.4Beta
* Mobile platform/version under test - IOS 10.2.1
* Real device

PLASE NOTE : 
Previously for iOS 9.3.5 and Appium 1.5.3, we were using findElementByIosUIAutomation () for this page since it was faster. Is there an alternative for this?

**Comment by mykola-mokhnach** [comment]
This is known issue. XPath locators are not natively supported by XCTest and thus quite slow. Use location by accessibility ids, class names and predicates where possible to achieve the best speed.
