### ISSUE TITLE
Scroll and Swipe functions

### ISSUE THREAD

**Issue by Manikanta29** [appium/appium#8057]
## The problem

How to scroll/swipe the IOS screen on both Real and Simulators? 

## Environment

OS X : 10.0.2
Appium:1.6.4 beta
Xcode:8.2.1
Iphone Real/Simulators devices

**Comment by mykola-mokhnach** [comment]
Please read https://github.com/mykola-mokhnach/appium/blob/f7ed6f1d5fa1a72c95316f5d043b643405bc8353/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md
