### ISSUE TITLE
web driver agent not loading

### ISSUE THREAD

**Issue by coolrahim29** [appium/appium#8058]
Hi

I Upgraded appium from 1.6.3 to 1.6.4 as swipe was not working and one of the forum it said to upgrade it to 1.6.4 so i did that and now gettign this error "xcodebuild exited with code '65' and signal 'null'". Below is the logs for this.
Also i did check the signature on xcode and run the build is successful for all web driver agent and runner on xcode.
I ahve also Tried to Clean  and run it again. Still getting same error.
Please Help

Last login: Mon Mar 20 14:49:43 on ttys000
lubnas-MacBook-Air:~ lubnashaikh$ appium
[Appium] Welcome to Appium v1.6.4-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/lubnashaikh/Desktop/ios_testing/src/Weatherzone (Debug).app","newCommandTimeout":"3000","platformVersion":"10.1","automationName":"XCUITest","bundleid":"com.weatherzone.wzlite.beta","browserName":"iOS","udid":"36CAEBBE-7B9E-441E-ADE7-8D8741344FD0","platformName":"iOS","deviceName":"iphone 6"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/lubnashaikh/Desktop/ios_testing/src/Weatherzone (Debug).app","newCommandTimeout":"3000","platformVersion":"10.1","automationName":"XCUITest","bundleid":"com.weatherzone.wzlite.beta","browserName":"iOS","udid":"36CAEBBE-7B9E-441E-ADE7-8D8741344FD0","platformName":"iOS","deviceName":"iphone 6"},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1489983463637 (15:17:43 GMT+1100 (AEDT))
[Appium] Creating new XCUITestDriver (v2.22.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/lubnashaikh/Desktop/ios_testing/src/Weatherzone (Debug).app'
[Appium]   newCommandTimeout: '3000'
[Appium]   platformVersion: '10.1'
[Appium]   automationName: 'XCUITest'
[Appium]   bundleid: 'com.weatherzone.wzlite.beta'
[Appium]   browserName: 'iOS'
[Appium]   udid: '36CAEBBE-7B9E-441E-ADE7-8D8741344FD0'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iphone 6'
[debug] [XCUITest] XCUITestDriver version: 2.22.0
[BaseDriver] Capability 'newCommandTimeout' changed from string ('3000') to integer (3000). This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: bundleid.
[BaseDriver] Session created with session id: a0f837c4-00aa-4086-9d2e-4f0b1af15fd4
[Xcode] Failed to get command line tools version: Command 'pkgutil --pkg-info\=com.apple.pkg.CLTools_Executables' exited with code 1.
[debug] [XCUITest] Xcode version set to '8.2.1' (tools vundefined)
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1489983463758 (15:17:43 GMT+1100 (AEDT))
[iOSSim] Constructing iOS simulator for Xcode version 8.2.1 with udid '36CAEBBE-7B9E-441E-ADE7-8D8741344FD0'
[XCUITest] Determining device to run tests on: udid: '36CAEBBE-7B9E-441E-ADE7-8D8741344FD0', real device: false
[BaseDriver] Using local app '/Users/lubnashaikh/Desktop/ios_testing/src/Weatherzone (Debug).app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1489983463941 (15:17:43 GMT+1100 (AEDT))
[debug] [XCUITest] Checking whether app '/Users/lubnashaikh/Desktop/ios_testing/src/Weatherzone (Debug).app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/Users/lubnashaikh/Desktop/ios_testing/src/Weatherzone (Debug).app': 'com.weatherzone.wzlite.beta'
[debug] [BaseDriver] Event 'resetStarted' logged at 1489983463946 (15:17:43 GMT+1100 (AEDT))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[debug] [BaseDriver] Event 'resetComplete' logged at 1489983464118 (15:17:44 GMT+1100 (AEDT))
[debug] [iOSLog] Starting iOS 10.1 simulator log capture
[debug] [iOSLog] System log path: /Users/lubnashaikh/Library/Logs/CoreSimulator/36CAEBBE-7B9E-441E-ADE7-8D8741344FD0/system.log
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1489983464229 (15:17:44 GMT+1100 (AEDT))
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid '36CAEBBE-7B9E-441E-ADE7-8D8741344FD0' already booted
[debug] [BaseDriver] Event 'simStarted' logged at 1489983464412 (15:17:44 GMT+1100 (AEDT))
[debug] [XCUITest] Reset requested. Removing app with id 'com.weatherzone.wzlite.beta' from the device
[debug] [XCUITest] Installing /Users/lubnashaikh/Desktop/ios_testing/src/Weatherzone (Debug).app on Simulator with UUID '36CAEBBE-7B9E-441E-ADE7-8D8741344FD0'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1489983469677 (15:17:49 GMT+1100 (AEDT))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1489983469680 (15:17:49 GMT+1100 (AEDT))
[XCUITest] Using WDA path: '/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=36CAEBBE-7B9E-441E-ADE7-8D8741344FD0 -configuration Debug' in directory '/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/lubnashaikh/Library/Developer/Xcode/DerivedData/WebDriverAgent-cctedmyutfblpucvorxgkhkxizhh/Logs/Test/F07E683C-24FD-49EE-B15E-F2ED6B99C1EA/Session-WebDriverAgentRunner-2017-03-20_151752-vypSq1.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2017-03-20 15:17:56.527 xcodebuild[3400:36030] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] 2017-03-20 15:17:56.496 XCTRunner[3447:36552] Running tests...
[Xcode] 2017-03-20 15:17:56.515 XCTRunner[3447:36552] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
[Xcode] 2017-03-20 15:17:56.518 XCTRunner[3447:36552] (dlopen_preflight(/Users/lubnashaikh/Library/Developer/Xcode/DerivedData/WebDriverAgent-cctedmyutfblpucvorxgkhkxizhh/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
[Xcode]   Referenced from: /Users/lubnashaikh/Library/Developer/Xcode/DerivedData/WebDriverAgent-cctedmyutfblpucvorxgkhkxizhh/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner
[Xcode]   Reason: image not found)
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1489983476551 (15:17:56 GMT+1100 (AEDT))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[HTTP] <-- POST /wd/hub/session - - ms - - 
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1489983486715 (15:18:06 GMT+1100 (AEDT))
[XCUITest] Using WDA path: '/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=36CAEBBE-7B9E-441E-ADE7-8D8741344FD0 -configuration Debug' in directory '/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /Users/lubnashaikh/Library/Developer/Xcode/DerivedData/WebDriverAgent-cctedmyutfblpucvorxgkhkxizhh/Logs/Test/C7947AF3-7440-44B4-A31B-716B47DBD627/Session-WebDriverAgentRunner-2017-03-20_151808-57c42j.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[Xcode] 2017-03-20 15:18:12.275 xcodebuild[3465:36757] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[Xcode] 2017-03-20 15:18:12.256 XCTRunner[3482:36937] Running tests...
[Xcode] 2017-03-20 15:18:12.266 XCTRunner[3482:36937] The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
[Xcode] 2017-03-20 15:18:12.266 XCTRunner[3482:36937] (dlopen_preflight(/Users/lubnashaikh/Library/Developer/Xcode/DerivedData/WebDriverAgent-cctedmyutfblpucvorxgkhkxizhh/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): Library not loaded: @rpath/RoutingHTTPServer.framework/RoutingHTTPServer
[Xcode]   Referenced from: /Users/lubnashaikh/Library/Developer/Xcode/DerivedData/WebDriverAgent-cctedmyutfblpucvorxgkhkxizhh/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner
[Xcode]   Reason: image not found)
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1489983492294 (15:18:12 GMT+1100 (AEDT))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:368:15)
    at tryCatch (/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:368:15)
    at tryCatch (/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:368:15)
    at tryCatch (/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Users/lubnashaikh/.npm-packages/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
^C[Appium] Received SIGINT - shutting down
lubnas-MacBook-Air:~ lubnashaikh$

**Comment by skyline-gleb** [comment]
You install with `--no-shrinkwrap` for get latest version for submodules? It helped me.

**Comment by mykola-mokhnach** [comment]
> The bundle “WebDriverAgentRunner” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle

Looks like there was some error during update. Have you uninstalled Appium before to install the new version?

```
npm unintsall -g appium
npm install -g appium@1.6.4-beta
```

**Comment by imurchie** [comment]
You may also need to delete the derived data, as it might be trying to update build versions that are incompatible. 

```
rm -rf ~/Library/Developer/Xcode/DerivedData/WebDriverAgent-*
```

**Comment by HlebHalkouski** [comment]
I have the same issue. appium-xcuitest-driver don't have WebDriverAgent inside.

`npm unintsall -g appium
npm install -g appium@1.6.4-beta`
It helped me.
Thank you.

**Comment by ashishjsharda** [comment]
I did try uninstalling and installing again.
However that did not help
Right now I do have appium 1.6 beta 
However I still see the below error:

The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file."

**Comment by ashishjsharda** [comment]
Also the url localhost:8100 does not load

**Comment by imurchie** [comment]
@ashishjsharda That is a signing issue. Please look at https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md

**Comment by ashishjsharda** [comment]
Hi @imurchie  : 
Below are the list of steps that I followed:

sudo npm -g install ios-deploy --unsafe-perm=true 
brew install carthage
 npm install -g deviceconsole
  gem install xcpretty
  bash Scripts/bootstrap.sh -d
 mkdir -p Resources/WebDriverAgent.bundle
 
I am able to build the Webdriver Agent in Xcode.
I have also created the xcconfig file as mentioned in the doc with 
DEVELOPMENT_TEAM = Company Team Id and 
CODE_SIGN_IDENTITY = iPhone Developer

Below is my code snippet:

/**
 * 
 */
package com.webdriver.ltree.tests.OfferPage;

import java.net.MalformedURLException;
import java.net.URL;

import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.ios.IOSDriver;
import io.appium.java_client.remote.MobileCapabilityType;

/**
 * @author ANIMBALKAR
 *
 */
public class TestNative {
	
	private AppiumDriver driver;
	@Test
	public void setUp() throws MalformedURLException
	{
		DesiredCapabilities capabilities=DesiredCapabilities.iphone();
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"Jeffrey A's iPhone");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");
		//capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION,"10.2.1");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION,"10.2.1");
		capabilities.setCapability("udid", "myudid");
		capabilities.setCapability("bundleId", "com.lendingtree.mylendingtree");
		capabilities.setCapability("xcodeConfigfile", "config.xcconfig");
		capabilities.setCapability("app", "/Users/ANIMBALKAR/Downloads/QA.ipa");
		driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
		driver.quit();
		
	}

}

I get the below error:
[Xcode] 2017-05-04 11:50:47.181 xcodebuild[14617:19168985] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/ANIMBALKAR/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fff215de880 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

Can you please help.

**Comment by imurchie** [comment]
That is almost always a signing issue. If you run with `showXcodeLog` capability set to `true`, the error logs will be printed. Or you can pull the `xcodebuild` command out of the Appium logs and run it manually.

**Comment by ashishjsharda** [comment]
Thanks @imurchie ,works now.
I did pass xcodeorgId and xcodeSigningId in my code.

**Comment by imurchie** [comment]
Excellent!

**Comment by codedgeass** [comment]
Thank you @ashishjsharda this helped me with my own similar issue: https://github.com/appium/appium/issues/8854. Performing the signing manually continued to cause problems. Passing `xcodeOrgId` and `xcodeSigningId` into my capabilities was successful.
