### ISSUE TITLE
For UIDatePicker, developer are able to write XCUITEST and  select value but through Appium we are not.

### ISSUE THREAD

**Issue by Siddh010** [appium/appium#8059]
## The problem
I am trying to select "Date Picker" value in IOS device with "setValue" command and able to select value but it throw error message as shown below and take lot of time for http request to go to next step.

For UIDatePicker, developer are able to write a XCUITest  and was able to successfully automate the date picker. This is because for datePickers we don’t need to implement ‘viewForRow:” or 'titleForRow:’ and so it should work as expected.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  MAc
* Node.js version (unless using Appium.app|exe):  6
* Mobile platform/version under test: IOS 10.0.2
* Real device or emulator/simulator: iPhone 6s Real device
* Appium CLI or Appium.app|exe:

## Details

we have two different kind of picker controls – UIPickerView and UIDatePicker. UIPickerView is used for any non date related fields and UIDatePicker is strictly used when we are dealing with date/time.

According to bug https://github.com/appium/appium/issues/6962#issuecomment-264732117
UIPickerView issue seems like an apple bug to  which is already reported to apple by other developers.
For UIPickerView, the issue persist when we use ‘viewForRow:” method instead of “titleForRow:”. 

But for UIDatePicker, my developer are able to write a XCUITest  and was able to successfully automate the date picker. This is because for datePickers we don’t need to implement ‘viewForRow:” or 'titleForRow:’ and so it should work as expected. Please refer the code below.

Developer Code :- (Was able to  select Value for Date Picker)
        let birthDatePicker : XCUIElement = app.datePickers["BirthdatePicker"];
        birthDatePicker.pickerWheels.element(boundBy: 0).adjust(toPickerWheelValue: "January")
        birthDatePicker.pickerWheels.element(boundBy: 1).adjust(toPickerWheelValue: "1")
        birthDatePicker.pickerWheels.element(boundBy: 2).adjust(toPickerWheelValue: "1990")

It is failing due to code below in  WDA project ->  file FBElementCommands.m

if (element.elementType == XCUIElementTypePickerWheel) {    
      [element adjustToPickerWheelValue:textToType];
    return FBResponseWithOK();
      
  }

With  Appium :- 
public void setValue(IOSElement els, String value){
try{
els.setValue(value);
}catch(WebDriverException e){
System.out.println("WebDriverException exception message ");
}

## Link to Appium logs

ebug] [MJSONWP] Responding to client with driver.implicitWait() result: null
[HTTP] <-- POST /wd/hub/session/071dd04a-38a6-412d-aef3-c97eb90c66d6/timeouts/implicit_wait 200 2 ms - 76 
[HTTP] --> POST /wd/hub/session/071dd04a-38a6-412d-aef3-c97eb90c66d6/appium/element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/value {"id":"5FB7B19F-CC31-48E3-B919-8F9F426BE651","value":"2016"}
[debug] [MJSONWP] Calling AppiumDriver.setValueImmediate() with args: ["2016","5FB7B19F-CC31-48E3-B919-8F9F426BE651","071dd04a-38a6-412d-aef3-c97eb90c66d6"]
[debug] [XCUITest] Executing command 'setValueImmediate'
[XCUITest] There is currently no way to bypass typing using XCUITest. Setting value through keyboard
[debug] [JSONWP Proxy] Proxying [GET /element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/attribute/type] to [GET http://localhost:8100/session/C913959C-840F-4401-AC65-0EA594F665B2/element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/attribute/type] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypePickerWheel\",\n  \"sessionId\" : \"C913959C-840F-4401-AC65-0EA594F665B2\",\n  \"status\" : 0\n}"
[debug] [JSONWP Proxy] Proxying [POST /element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/value] to [POST http://localhost:8100/session/C913959C-840F-4401-AC65-0EA594F665B2/element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/value] with body: {"value":["2","0","1","6"]}
[debug] [iProxy] recv failed: Resource temporarily unavailable
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:126:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/071dd04a-38a6-412d-aef3-c97eb90c66d6/appium/element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/value 500 240200 ms - 251 

[HTTP] <-- POST /wd/hub/session/071dd04a-38a6-412d-aef3-c97eb90c66d6/appium/element/5FB7B19F-CC31-48E3-B919-8F9F426BE651/value 500 240200 ms - 251 
[HTTP] --> POST /wd/hub/session/071dd04a-38a6-412d-aef3-c97eb90c66d6/timeouts/implicit_wait {"ms":0}
[debug] [MJSONWP] Calling AppiumDriver.implicitWait() with args: [0,"071dd04a-38a6-412d-aef3-c97eb90c66d6"]
[debug] [XCUITest] Executing command 'implicitWait'
[debug] [BaseDriver] Set implicit wait to 0ms
[debug] [MJSONWP] Responding to client with driver.implicitWait() result: null

**Comment by mykola-mokhnach** [comment]
Can you please attach the output of getPageSource command when this date picker is shown? I'll try to add a fix into WDA then.

**Comment by Siddh010** [comment]
Hi Mykola,

Thanks for  help , below  contain getPage Source() details.
Last 15 lines contains Picker details :- 

<?xml version="1.0" encoding="UTF-8"?><AppiumAUT><XCUIElementTypeApplication type="XCUIElementTypeApplication" name="Empower" label="Empower" enabled="true" x="0" y="0" width="375" height="667">
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" x="0" y="0" width="375" height="667">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="375" height="667">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="375" height="667">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="375" height="667">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="375" height="667">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="375" height="667">
              <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="375" height="667">
                <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="375" height="667">
                  <XCUIElementTypeNavigationBar type="XCUIElementTypeNavigationBar" enabled="true" x="0" y="0" width="375" height="64">
                    <XCUIElementTypeButton type="XCUIElementTypeButton" name="Back" label="Back" enabled="true" x="5" y="26" width="36" height="30"/>
                  </XCUIElementTypeNavigationBar>
                  <XCUIElementTypeScrollView type="XCUIElementTypeScrollView" enabled="true" x="0" y="64" width="375" height="603">
                    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="-17" width="375" height="604">
                      <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="Let's look up your account" name="Let's look up your account" label="Let's look up your account" enabled="true" x="40" y="-17" width="295" height="87"/>
                      <XCUIElementTypeSecureTextField type="XCUIElementTypeSecureTextField" value="SOCIAL SECURITY NUMBER" enabled="true" x="28" y="93" width="319" height="37"/>
                      <XCUIElementTypeTextField type="XCUIElementTypeTextField" value="ZIP / POSTAL CODE" label="" enabled="true" x="28" y="149" width="319" height="37"/>
                      <XCUIElementTypeTextField type="XCUIElementTypeTextField" value="OCECNCIM" label="" enabled="true" x="28" y="205" width="319" height="37"/>
                      <XCUIElementTypeTextField type="XCUIElementTypeTextField" value="DATE OF BIRTH" name="GWMBirthdateTextField" label="" enabled="true" x="28" y="257" width="319" height="37"/>
                      <XCUIElementTypeTextField type="XCUIElementTypeTextField" value="NUMERIC STREET ADDRESS" label="" enabled="true" x="28" y="317" width="319" height="37"/>
                      <XCUIElementTypeButton type="XCUIElementTypeButton" name="FIND ME" label="FIND ME" enabled="false" x="0" y="526" width="375" height="61"/>
                    </XCUIElementTypeOther>
                  </XCUIElementTypeScrollView>
                </XCUIElementTypeOther>
              </XCUIElementTypeOther>
            </XCUIElementTypeOther>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" x="0" y="0" width="375" height="667">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="375" height="667">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="407" width="375" height="260">
        <XCUIElementTypeToolbar type="XCUIElementTypeToolbar" enabled="true" x="0" y="407" width="375" height="44">
          <XCUIElementTypeButton type="XCUIElementTypeButton" name="Next" label="Next" enabled="true" x="302" y="409" width="46" height="40"/>
        </XCUIElementTypeToolbar>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="451" width="375" height="216"/>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" x="0" y="0" width="375" height="667">
    <XCUIElementTypeStatusBar type="XCUIElementTypeStatusBar" enabled="true" x="0" y="0" width="375" height="20">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="375" height="20"/>
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="0" width="375" height="20">
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="3 of 5 bars, signal strength" label="3 of 5 bars, signal strength" enabled="true" x="6" y="0" width="35" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="Airtel network" label="Airtel network" enabled="true" x="44" y="0" width="31" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" value="SSID" name="3 of 3 Wi-Fi bars" label="3 of 3 Wi-Fi bars" enabled="true" x="80" y="0" width="13" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="1:13 PM" label="1:13 PM" enabled="true" x="166" y="0" width="46" height="20"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" name="71% battery power, Charging" label="71% battery power, Charging" enabled="true" x="337" y="0" width="33" height="20"/>
      </XCUIElementTypeOther>
    </XCUIElementTypeStatusBar>
  </XCUIElementTypeWindow>
  <XCUIElementTypeWindow type="XCUIElementTypeWindow" enabled="true" x="-1" y="-1" width="377" height="669">
    <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="-1" y="-1" width="377" height="669">
      <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="-1" y="406" width="377" height="262">
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="-1" y="406" width="377" height="46"/>
        <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="-1" y="450" width="377" height="218">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="-1" y="450" width="377" height="218">
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="-1" y="450" width="377" height="218"/>
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="-1" y="450" width="377" height="218"/>
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="-1" y="450" width="377" height="218"/>
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="-1" y="450" width="377" height="218"/>
            <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="-1" y="450" width="377" height="218"/>
          </XCUIElementTypeOther>
        </XCUIElementTypeOther>
        <XCUIElementTypeDatePicker type="XCUIElementTypeDatePicker" name="GWMBirthdatePicker" enabled="true" x="-1" y="450" width="377" height="218">
          <XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="-1" y="450" width="377" height="218">
            <XCUIElementTypePickerWheel type="XCUIElementTypePickerWheel" value="20" enabled="true" x="51" y="413" width="50" height="292"/>
            <XCUIElementTypePickerWheel type="XCUIElementTypePickerWheel" value="March" enabled="true" x="105" y="413" width="137" height="292"/>
            <XCUIElementTypePickerWheel type="XCUIElementTypePickerWheel" value="1987" enabled="true" x="246" y="413" width="78" height="292"/>
          </XCUIElementTypeOther>
        </XCUIElementTypeDatePicker>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
  </XCUIElementTypeWindow>
</XCUIElementTypeApplication></AppiumAUT>

**Comment by mykola-mokhnach** [comment]
Thanks, but please format it properly. Or, which would be better, attach as a file.

**Comment by Siddh010** [comment]
Sorry Xml was not accepting in comment  so added in gist now 
https://gist.github.com/Siddh010/2bdbd142786fff9c2acb877db2efdb68

**Comment by mykola-mokhnach** [comment]
hm, this should work properly though. Which locator do you use to detect the element?

**Comment by Siddh010** [comment]
I have used xpath locator
//XCUIElementTypePickerWheel[1]    For Date
//XCUIElementTypePickerWheel[2]   for Month
//XCUIElementTypePickerWheel[3]   for Year

**Comment by mykola-mokhnach** [comment]
can you try with these locators instead:

```java
driver.findElements(By.className("XCUIElementTypePickerWheel")).get(0)
driver.findElements(By.className("XCUIElementTypePickerWheel")).get(1)
driver.findElements(By.className("XCUIElementTypePickerWheel")).get(2)
```

**Comment by Siddh010** [comment]
Hi 
I used below  command  but for selecting each value in datepicker, it is   taking around (362166 ms)  approx. (4 min) .
Applium Log  message :- https://gist.github.com/Siddh010/1fbe550175a85f6f000e87a87e858a6f

	List<IOSElement> wheels =  (List<IOSElement>) driver.findElements(By.className("XCUIElementTypePickerWheel"));		
		wheels.get(0).sendKeys("8");
		wheels.get(1).sendKeys("January");
		wheels.get(2).setValue("1970");

**Comment by mykola-mokhnach** [comment]
Are there any error in device logs during these 4 minutes?

**Comment by Siddh010** [comment]
Hi 
Please find the Device log in for selecting date Picker  https://gist.github.com/Siddh010/905b409f392743dd52f615f529db4df0


Below are the error message I got in log 

ar 20 17:47:23 iphone6s XCTRunner(UIAccessibility)[374] <Info>: Loading bundle post launch: NSBundle </System/Library/PrivateFrameworks/CoreSymbolication.framework> (loaded)
Mar 20 17:47:23 iphone6s XCTRunner(UIAccessibility)[374] <Info>: Main bundle: (null)
Mar 20 17:47:23 iphone6s XCTRunner(WebDriverAgentLib)[374] <Notice>: Enqueue Failure: UI Testing Failure - No matches found for PickerWheel
Query input was {(
    Application 0x17436e100: {{0.0, 0.0}, {375.0, 667.0}}, label: 'Empower'
)} <unknown> 0 1


Mar 20 17:47:27 iphone6s kernel(Sandbox)[0] <Notice>: SandboxViolation: logd(44) deny(1) file-read-data /private/var/containers/Bundle/Application/A4FB144B-525B-4D84-A2B2-C1354B0F54D2/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner


Mar 20 17:47:38 iphone6s XCTRunner(WebDriverAgentLib)[374] <Notice>: Enqueue Failure: UI Testing Failure - Unsupported picker wheel "March" PickerWheel of type 0 <unknown> 0 1



Thanks
Siddartha

**Comment by mykola-mokhnach** [comment]
It's quite strange that it works from Xcode and does not work with WDA, since both use the same _adjustToPickerWheelValue_  call.
I've just prepared some small code snippet, which exactly repeats what was done in the test written  by your developer, so you can try if it works on your environment:


```objc
#import "XCElementSnapshot+FBHelpers.h"

....

+ (void)adjustPickerFor:(XCUIElement* )wheel value:(NSString* )value
{
  XCElementSnapshot *datePicker = [wheel.lastSnapshot fb_parentMatchingOneOfTypes:@[@(XCUIElementTypeDatePicker)]];
  if (nil == datePicker) {
    [wheel adjustToPickerWheelValue:value];
    return;
  }
  NSArray<XCElementSnapshot *> *allWheels = [datePicker descendantsByFilteringWithBlock:^BOOL(XCElementSnapshot *snapshot) {
    return snapshot.elementType == XCUIElementTypePickerWheel;
  }];
  NSInteger wheelIdx = -1;
  for (NSUInteger i = 0; i < allWheels.count; ++i) {
    if ([[allWheels objectAtIndex:i] _matchesElement:wheel.fb_lastSnapshot]) {
      wheelIdx = i;
      break;
    }
  }
  if (wheelIdx >= 0) {
    NSArray<XCUIElement *> *allDatePickers = [wheel.application descendantsMatchingType:XCUIElementTypeDatePicker].allElementsBoundByIndex;
    for (XCUIElement *datePickerEl in allDatePickers) {
      if ([datePickerEl.fb_lastSnapshot _matchesElement:datePicker]) {
        [[datePickerEl.pickerWheels elementBoundByIndex:wheelIdx] adjustToPickerWheelValue:value];
        return;
      }
    }
  }
}

......
  if (element.elementType == XCUIElementTypePickerWheel) {
    [self.class adjustPickerFor:element value:textToType];
    return FBResponseWithOK();
  }
....
```

Please insert this code into _FBFindElementCommands.m_, cleanup WDA to make sure it is not cached and try your automated test

**Comment by Siddh010** [comment]
I shall try with this , thank a lot.

**Comment by mykola-mokhnach** [comment]
@Siddh010 did the patch work for you?

**Comment by Siddh010** [comment]
No it  didn't work for me .. I am getting same issue. I am trying now with
sample code to automate date picker .

**Comment by Siddh010** [comment]
Hi Mykola,

Code patch didn't work for me . I am getting same issue.

I was able to select value for "UIDatePicker "  and "UIPickerView" by clicking "Increment" and "Decrement" button by using  Xcode Accessibility Inspector tool.
So can we integrate similar function in Appium/WDA  tool also.
Please see this screen shot below:- 

![image](https://cloud.githubusercontent.com/assets/20200289/24343652/33e9e60c-12e5-11e7-9583-ee4eafbd545c.png)

**Comment by mykola-mokhnach** [comment]
We've added a workaround to Appium for this XCTest issue. Check the _mobile: selectPickerWheelValue_ method in https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md

**Comment by Siddh010** [comment]
Hi MyKola,

I am getting below errror message whicl using command "selectPickerWheelValue"

org.openqa.selenium.UnsupportedCommandException: Unknown mobile command "selectPickerWheelValue". Only scroll,swipe,pinch,doubleTap,twoFingerTap,touchAndHold,tap,dragFromToForDuration commands are supported. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 140 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'C07R10GSG1HV', ip: '10.217.224.159', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_91'
Driver info: io.appium.java_client.ios.IOSDriver

**Comment by Siddh010** [comment]
Thank you @mykola-mokhnach , Now selectPickerWheelValue method is work in 1.6.5 appium version.
I am able to select datePicker With send Key. But in some Pages it is taking 3-4 min. I suppose it might be due to Accessibility issue.

 Also I have observe that App get hang initially after opening for 3-4 min and then only perform first action .  

List<IOSElement> wheels =  (List<IOSElement>) driver.findElements(By.className("XCUIElementTypePickerWheel"));		
	wheels.get(0).sendKeys("8");
	wheels.get(1).sendKeys("January");
	wheels.get(2).setValue("1970");

**Comment by ssimakurthy** [comment]
Hi @mykola-mokhnach, I am also facing issues with XCUIElementTypePickerWheel. I read in one of the comments that selectPickerWheelValue is available in appium 1.6.5 beta. How to upgrade to 1.6.5 beta version.

I am presently using appium 1.6.5

**Comment by saikrishna321** [comment]
@ssimakurthy you install the latest beta 1.6.6 (npm install -g appium@beta) 

> I read in one of the comments that selectPickerWheelValue is available (Yes, pls refer the link below)

https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md#mobile-selectpickerwheelvalue

**Comment by ssimakurthy** [comment]
Tq @saikrishna321.. I upgraded to 1.6.6 beta and able to use selectPickerWheelValue

**Comment by prat3ik** [comment]
We can only select next or previous date Using Appium(selectPickerWheelValue), read this: https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures.md
