### ISSUE TITLE
Question: Future plans about UIAutomator 2 back-end

### ISSUE THREAD

**Issue by HlebHalkouski** [appium/appium#8061]
HI!

I'm interesting in future UIAutomator 2 in Appium. 

Is it replace UIAutomator in future? 
What are the priorities in develop of UIAutomator and UIAutomator 2 back-ends? 
Is there reasons to switch my test framework to UIAutomator 2 right now? 

Thanks you!

**Comment by mykola-mokhnach** [comment]
UIAutomation2 uses the new version of Google's automation framework based on UIObject2. The UIAutomation(1) approach is based on the old framework, which is not supported by Google anymore. So, it is possible, in future Android version UIAutomation1 will just stop working and nobody will care about that. I've already seen several reports, about there are problems in Android 7.0+

**Comment by JaniJegoroff** [comment]
There is also wiki page available for detailed info:
https://github.com/appium/appium-uiautomator2-server/wiki

**Comment by HlebHalkouski** [comment]
Thanks you for answers. We discussed it with my project and make decisions switch our framework to UIAutomator 2 in the near future.
