### ISSUE TITLE
appium memory leak

### ISSUE THREAD

**Issue by liweiting** [appium/appium#8063]
## The problem

I find when a appium server run long time with session override ,the memory  will be ever-increasing。 is have bug in appium?

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3, 1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: linux redhat5.0
* Node.js version (unless using Appium.app|exe): 6.10.0
* Mobile platform/version under test:android
* Real device or emulator/simulator:
* Appium CLI or Appium.app|exe:Appium CLI  (npm install appium -g)

**Comment by mykola-mokhnach** [comment]
Please try Appium 1.6.4-beta. There was a fix for logs buffer (it was never reset on driver reset)
