### ISSUE TITLE
I am unable to click on the button, because button id have some space between the text. 

### ISSUE THREAD

**Issue by Manikanta29** [appium/appium#8064]
## The problem
I am unable to click on the button. 
Button "Accessibility Id: Get Started and Label: Get Started" in iphone real device.

Code: 
driver.findElementByXPath("//XCUIElementTypeButton[@name = 'Get Started']").click();
//driver.findElementByAccessibilityId("Get Started").click();

Error message: 
I am getting the following error message in appium server 

[debug] [BaseDriver] Waited for 56434 ms so far

[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/5F5F0960-DBA8-480B-AB83-9CBC839C764B/element] with body: {"using":"xpath","value":"//XCUIElementTypeButton[@name = 'Get Started']"}

[debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"5F5F0960-DBA8-480B-AB83-9CBC839C764B","value":{"using":"xpath","value":"//XCUIElementTypeButton[@name = 'Get Started']","description":"unable to find an element"},"status":7}

Eclipse error: 
An element could not be located on the page using the given search parameters.
*** Element info: {Using=xpath, value=//XCUIElementTypeButton[@name = 'Get Started']}

## Environment
OS X : 10.0.2
Appium:1.6.4 beta
Xcode:8.2.1
Iphone Real/Simulators devices

**Comment by vjmaiky** [comment]
//XCUIElementTypeButton[contains(@name, 'Get Started']") try with contains

**Comment by Manikanta29** [comment]
Works fine.

**Comment by Jazzjorean** [comment]
How can I use contains in Accessibility Id?

**Comment by vjmaiky** [comment]
use predicates for example:
type == 'XCUIElementTypeButton' AND name CONTAINS[c] 'Get Started'
or type == 'XCUIElementTypeButton' AND value CONTAINS[c] 'Get Started'
or instead of contains use MATCHES or others

**Comment by Jazzjorean** [comment]
@vjmaiky 
Can I use something like this:
'type == 'XCUIElementTypeTable' AND name == 'Get Started'
will this work?

**Comment by vjmaiky** [comment]
this is a predicate:

type == 'XCUIElementTypeButton' AND name MATCHES[c] 'Get Started'

**Comment by Jazzjorean** [comment]
@vjmaiky 
It worked ! Thanks alot.
