### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by claytonneal** [appium/appium#8065]
Hello.
When i download the windows installer the version number is 1.4.x However on github the latest release is 1.6.x
Why such a difference please?
Thanks

**Comment by imurchie** [comment]
Which Windows installer are you referring to?

**Comment by imurchie** [comment]
[Appium-dot-exe](https://github.com/appium/appium-dot-exe) is deprecated and probably unusable. [Appium-desktop](https://github.com/appium/appium-desktop) is in full development and ought to supply the latest Appium server.

**Comment by claytonneal** [comment]
Hiya. 
When i look at the appium app downloads from https://bitbucket.org/appium/appium.app/downloads/ the latest windows installer is v1_4_16_1. However when i look at appium releases from https://github.com/appium/appium/releases, the latest is v1.6.3. Can you explain the difference please?

**Comment by vikramvi** [comment]
@claytonneal https://github.com/appium/appium/releases is the project which will be maintained now on.

**Comment by imurchie** [comment]
The GUI apps were re-written: https://github.com/appium/appium-desktop/releases

**Comment by vikramvi** [comment]
@triager please close as not appium issue
