### ISSUE TITLE
Not able to Hide numeric keypad on ios 10.2.1

### ISSUE THREAD

**Issue by HemantTrivedi** [appium/appium#8067]
## The problem
I am not able to hide numeric keypad on ios 10.2.1. I tried the following command 

driver.getkeyboard().sendkeys(keys.RETURN) . This command works good when keypad is alphabetic but for numeric keypad its not working .

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6
* Desktop OS/version used to run Appium: MAC 
* Mobile platform/version under test: Ios 10.2.1
* Real device or emulator/simulator:Real device

**Comment by mykola-mokhnach** [comment]
Is it possible to hide the keyboard manually though?

**Comment by HemantTrivedi** [comment]
Yes @mykola-mokhnach . I am able to hide with "DONE" key

**Comment by mykola-mokhnach** [comment]
So  you can simply locate and tap this key

**Comment by HemantTrivedi** [comment]
I tried locating it with Appium inspector . But Appium is not displaying any locater for the same.

**Comment by HemantTrivedi** [comment]
I am able to hide alphabetic keypad . Dont know whats the issue with numeric.

**Comment by mykola-mokhnach** [comment]
Can you provide inspector screenshot and the output of getPageSource method?

**Comment by HemantTrivedi** [comment]
ya sure

**Comment by mykola-mokhnach** [comment]
I mean if you cannot hide the keypad manually then it will not be possible to hide it in automated test as well

**Comment by HemantTrivedi** [comment]
But I can hide it manually with Done key

**Comment by HemantTrivedi** [comment]
I have checked the page source . No property or value is present for "Done" button in the page source

**Comment by mykola-mokhnach** [comment]
How about attaching page source and screenshot to this issue?

**Comment by HemantTrivedi** [comment]
ya @mykola-mokhnach  , from DOM , I got the name for the element which Appium was not able to locate . So I am able to click on the same.  Thanks for your help.
