### ISSUE TITLE
Get syslog not work on 1.6.4-beta

### ISSUE THREAD

**Issue by skyline-gleb** [appium/appium#8068]
## The problem

On `driver.get_log('syslog')` i get nothing

## Environment

* Appium version (or git revision) that exhibits the issue: appium@1.6.4-beta
* Desktop OS/version used to run Appium: el capitan 10.11.6
* Node.js version (unless using Appium.app|exe): v7.7.3
* Mobile platform/version under test: iOS 9.3.1
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe:

## Link to Appium logs
[link](https://gist.github.com/skyline-gleb/c9cff9c728053ea12b4a96914d0c175c)

**Comment by imurchie** [comment]
I do not see any call to get the logs in the Appium server logs you have provided.

**Comment by skyline-gleb** [comment]
@imurchie sorry, confused build. I update the same [link](https://gist.github.com/skyline-gleb/c9cff9c728053ea12b4a96914d0c175c)

**Comment by z00sts** [comment]
Same issue

**Comment by imurchie** [comment]
Does your version of `idevicesyslog` get anything from the device? If not, can you re-install `libimobiledevice` with the latest?

```
brew uninstall libimobiledevice
brew install libimobiledevice --HEAD
```

**Comment by skyline-gleb** [comment]
@imurchie yes, successfully get syslog from device using `idevicesyslog` manually
```
~ user$ brew info libimobiledevice
libimobiledevice: stable 1.2.0 (bottled), HEAD
Library to communicate with iOS devices natively
http://www.libimobiledevice.org/
/usr/local/Cellar/libimobiledevice/HEAD-45fda81 (66 files, 997KB) *
  Built from source on 2017-03-18 at 11:36:42
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libimobiledevice.rb
==> Dependencies
Build: pkg-config ✔
Required: libtasn1 ✔, libplist ✔, usbmuxd ✔, openssl ✔
```

**Comment by imurchie** [comment]
And when you run it you get stuff?
```
isaac-2 appium-xcuitest-driver → git master* → idevicesyslog                                                                                                                                        4.7.2
[connected]
Mar 22 10:22:07 iamPhone kernel(AppleBiometricSensor)[0] <Debug>: entry
Mar 22 10:22:07 iamPhone kernel(AppleBiometricSensor)[0] <Debug>: entry
Mar 22 10:22:07 iamPhone kernel(AppleBiometricSensor)[0] <Debug>: txBufferLength=7 rxBufferLength=23
...
```

Getting the `syslog` works on my device so I am trying my best to figure this out.

**Comment by skyline-gleb** [comment]
Yes, i get
```
~ user$ idevicesyslog
[connected]


Mar 22 19:05:54 iPhone syncdefaultsd[776] <Notice>: (Note ) SYDAccount: no account
Mar 22 19:05:54 iPhone syncdefaultsd[776] <Notice>: (Note ) SYDBootAccount: no account (null)
Mar 22 19:05:54 iPhone syncdefaultsd[776] <Notice>: (Note ) SYDPIMAccount: no account (null)
<...>
```
Maybe enable additional debug logs? For more info

**Comment by imurchie** [comment]
What is the output of `which idevicesyslog`?

**Comment by skyline-gleb** [comment]
```
~ user$ which idevicesyslog
/usr/local/bin/idevicesyslog
```

**Comment by imurchie** [comment]
Hmmm. That's the one Appium is using, so that should not be a problem.

**Comment by imurchie** [comment]
It's very strange. I would also expect inlined logs, since `showIOSLog` is turned on. Lines like 
```
info iOSLog [IOS_SYSLOG_ROW STDERR] Mar 22 10:35:47 iamPhone SpringBoard[16573] <Notice>: Running <SBAppExitedWorkspaceTransaction: 0x11a96a3a0> for transition request:
```

**Comment by skyline-gleb** [comment]
I too... What can I help? Any research

**Comment by imurchie** [comment]
One quick question: do the server and the device have the same time? I can reproduce this by setting the device time earlier than the system time on the server to which it is connected.

**Comment by skyline-gleb** [comment]
@imurchie unbelievable, you right! I can not check right now (remote view-only access on phone), but check as soon as possible

**Comment by skyline-gleb** [comment]
Great, works after synchronize the server system time and device time!
@imurchie thanks! :+1:

**Comment by imurchie** [comment]
Awesome! Great! I'm in the process of removing that restriction, so it should not be a problem to have them differ going forward.
