### ISSUE TITLE
Swipe not working in simulator 

### ISSUE THREAD

**Issue by sjenasears** [appium/appium#8069]
## The problem

Swipe from left to right not working in simulator 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 Beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac Sierra
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:IOS
* Real device or emulator/simulator:Simulator
* Appium CLI or Appium.app|exe:CLI

## Details

 

 logs: https://gist.github.com/sjenasears/af447e9ea71e1ee16adf2a6d301234e8

Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

driver.swipe(400, 150, 900, 150, 1000);

**Comment by mykola-mokhnach** [comment]
Try with java_client 5.0-beta4

**Comment by sjenasears** [comment]
I am using driver.swipe(400, 150, 900, 150, 1000);
Still it is not working after using java_client 5.0-beta4

Appium logs are below
[{"action":"press","options":{"x":400,"y":150}},{"action":"wait","options":{"ms":1000}},{"action":"moveTo","options":{"x":500,"y":0}},{"action":"release","options":{}}],"bdbd4906-0ae0-4f64-8b11-d36d1c267646"]

**Comment by mykola-mokhnach** [comment]
Try "mobile: swipe", "mobile: scroll" or "mobile: dragFromToForDuration" instead. Check https://github.com/mykola-mokhnach/appium/blob/3966c017d07118df259838b2473d3aeb8cc91387/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md for more details

**Comment by rossjohnson90** [comment]
@mykola-mokhnach Sorry to hijack this issue but in my tests I'm using mobile scroll but nothing happens at all:
```
REQUEST
{
	"script": "mobile: scroll",
	"args": [
		{
			"direction": "left",
			"element": "5002"
		}
	]
}
RESPONSE
{
	"status": 0,
	"value": null,
	"sessionId": "756589eb-367c-4719-9535-85a1763af997"
}
```

Should mobile:scroll work for android and iOS? I've managed to get touch actions working on Android but same code on iOS I just get method not implemented

**Comment by mykola-mokhnach** [comment]
Element id looks suspicious. Can you show the code?

**Comment by rossjohnson90** [comment]
```
element(by.css(cssSelector)).getId().then((id) => {
                        browser.driver.executeScript('mobile: scroll',{direction: 'left', element: id}).then(()=>{prom.fulfill()});
                    })
```

**Comment by mykola-mokhnach** [comment]
The code looks good.
Are you sure _scroll_ is what you need? _swipe_ or _dragFromToForDuration_ might work as well.

**Comment by rossjohnson90** [comment]
@mykola-mokhnach I was leaning away from swipe as reading the documentation its iOS only, ideally I'd like a solution that works on both android and iOS, but I tried it and I get this error:
`UnsupportedOperationError: Unknown command, all the mobile commands except scroll have been removed.`

This is where I'm reading from:
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md

**Comment by mykola-mokhnach** [comment]
You need to install the recent beta to get mobile: * commands working

**Comment by jlipps** [comment]
@rossjohnson90 it also looks like you're trying to do a native mobile scroll based on a webview element id (those start with 5000). that won't work. "mobile: scroll" is for native elements and views only.

**Comment by rossjohnson90** [comment]
@jlipps Any suggestions how I might scroll/swipe an element (or any part of the screen) in a web view?
