### ISSUE TITLE
How to handle multiple webviews with Appium 1.6.x ?

### ISSUE THREAD

**Issue by aricalee** [appium/appium#8070]
## The problem

fail to recognize the webview showing up.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: windows 7 64bit Enterprise Edition
* Node.js version (unless using Appium.app|exe): exe
* Mobile platform/version under test: Android 5.1 + webview 54
* Real device or emulator/simulator: Samsong Note III
* Appium CLI or Appium.app|exe: exe

## Details

With Appium, I failed to recognize the webview showing up when multiple webview existing. For example, when we have 4 tabs and click on each will switch to a webview containing some web elements. So far, I can only recognize the first webview, and then...I have no idea on how to differentiate those webviews.

## Link to Appium logs

N/A

## Code To Reproduce Issue [ Good To Have ]

N/A

**Comment by mykola-mokhnach** [comment]
Please carefully fill out the necessary information in the reporting template.

**Comment by aricalee** [comment]
Hi mykola-mokhnach

I've added more information to the template. For the code, sorry that I have no way to provide now as it's owned by my customer. I need to talk to him to see if I can paste the code here.

Just want to know, what alternatives we can use to handle the multiple webviews with Appium?

Appreciated.

**Comment by dpgraham** [comment]
@aricalee Can you provide the Appium Server logs?

**Comment by aricalee** [comment]
@dpgraham After a close talk with customer...they refused to provide codes and logs....customer R&D responded with following statement
"When we fetch the hierarchy from a device, 
we only get elements which are currently visible on the screen. If the user swipes 
up or down, a web view might disappear in the hierarchy or it might show up. Since 
we do not have a possibility to mark a web view control in the hierarchy on the device, we do not know which web view belongs to which browser window spy. This was the main reason for this limitation. Besides if a web view is not in the hierarchy anymore, we would not know if it is just out 
of view or if it is completely gone. "

May I know if you or anyone else can provide me any hints with this statement?

Appreciated.

**Comment by dpgraham** [comment]
The thing about the WebView being out of view is an unfortunate limitation. We can only access elements when they are in view.

AFAIK webview's don't have unique identifiers so I don't think you can differentiate between WebViews unless you have some attribute on the hierarchy that identifies them uniquely. @imurchie @jlipps can one of you confirm this?

**Comment by aricalee** [comment]
@dpgraham Actually...what I intent to do is to just identify the webview on the front...
When you say "have some attribute on the hierarchy that identifiers ...", does it mean that the R&D of the apps needs to add some special property to the class for automate identification?

Appreciated.

**Comment by dpgraham** [comment]
Actually I was wrong about that, the attribute strategy doesn't work.

There's no way to know exactly which webview is which. You have to look at the contents of the webview to see what it is.

**Comment by aricalee** [comment]
@dpgraham 
Thanks for the response so much! Then...what about if we have multiple webviews existing the same time? For example, an apps having a page with 4 tabs, clicking on each tab will switch to a webview. 

How to handle this scenario with Appium?

Appreciated.

**Comment by dpgraham** [comment]
Clicking on a tab won't focus on the WebView. You have to switch to it using `driver.setContext`. Unfortunately there's no way to know which tab each webview belongs to. You'll have to look inside the contents of the webview itself to figure that out.
