### ISSUE TITLE
XCUITest element XCUIElementTypeGroup missing

### ISSUE THREAD

**Issue by Brian-Watson** [appium/appium#8072]
## The problem

It appears that the old UIAutomation element type of 'UIATableGroup' is not being identified in the new Appium with XCUITest.  It's showing as "XCUIElementTypeOther" when I assume it should be 'XCUIElementTypeGroup'.

## Environment

* Appium version (or git revision) that exhibits the issue:  1.6.4-beta
* Last Appium version that did not exhibit the issue (if applicable):  1.5.3
* Mobile platform/version under test:  iOS 10.2
* Real device or emulator/simulator:  Simulator
* Appium CLI or Appium.app|exe:  CLI  /  Java-client

## Details

I have a table view in my iOS app which under Appium 1.5.3 UIAutomation getPageSource() looked like this for a table group header and the first cell under the header...

`<UIATableView name="" label="" value="rows 1 to 20 of 70" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/24" x="0" y="140" width="421" height="884">
	<UIATableGroup name="TRANSACTION INFORMATION" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/24/0" x="0" y="140" width="421" height="20">
		<UIAStaticText name="TRANSACTION INFORMATION" label="TRANSACTION INFORMATION" value="TRANSACTION INFORMATION" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/24/0/0" x="10" y="141" width="401" height="18"></UIAStaticText>
	</UIATableGroup>
	<UIATableCell name="Name" label="" value="" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/24/1" x="0" y="160" width="421" height="44">
		<UIAStaticText name="Name" label="Name" value="Name" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/24/1/0" x="8" y="166" width="47" height="32.5"></UIAStaticText>
		<UIATextField name="" label="" value="editTRPropertyDetails_ListingDetails_BA (ios) - 11467" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/24/1/1" x="63" y="166" width="317" height="32.5">
			<UIATextField name="" label="" value="editTRPropertyDetails_ListingDetails_BA (ios) - 11467" dom="" enabled="true" valid="true" visible="true" hint="" path="/0/0/24/1/1/0" x="63" y="166" width="317" height="32.5"></UIATextField>
		</UIATextField>
	</UIATableCell>`

Now, when I get the page source with Appium 1.6.4-beta, I see this...

`
																	<XCUIElementTypeTable type="XCUIElementTypeTable" enabled="true" x="0" y="140" width="421" height="884">
																		<XCUIElementTypeOther type="XCUIElementTypeOther" enabled="true" x="0" y="140" width="421" height="20">
																			<XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="TRANSACTION INFORMATION" name="TRANSACTION INFORMATION" label="TRANSACTION INFORMATION" enabled="true" x="10" y="141" width="401" height="18"/>
																		</XCUIElementTypeOther>
																		<XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" x="0" y="160" width="421" height="44">
																			<XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="Name" name="Name" label="Name" enabled="true" x="8" y="166" width="47" height="33"/>
																			<XCUIElementTypeTextField type="XCUIElementTypeTextField" value="editTRPropertyDetails_ListingDetails_BA (ios) - 08189" label="" enabled="true" x="63" y="166" width="317" height="33"/>
																		</XCUIElementTypeCell>
`
Notice how the UIATableGroup shows as XCUIElementTypeOther instead of XCUIElementTypeGroup like the other controls. Also, it's missing it's name attribute which was there in Appium 1.5.3.  Is this something Appium is doing during the conversion?  Also, for the "groups" that are off screen at the time in this table, Appium is no longer returning any of the useful attributes for them, such as value, name or label.

**Comment by mykola-mokhnach** [comment]
The issue has nothing to do with Appium itself and it works as designed. XCTest has its own logic for elements tree assembling and this tree might be totally different from what was build by instruments. Please post the issue to Apple's bugtracker if you don't like the current behaviour.
