### ISSUE TITLE
Appium not working while connected in VPN

### ISSUE THREAD

**Issue by sjenasears** [appium/appium#8075]
## The problem

I am testing my ios app through simulator through appium script.
It is launching simulator and working fine.
But when i am connectting my latop to my company Virtual Public Netwotk it is not working.
Simulator not getting launched and testcase not running.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4 Beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Sierra mac
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:Ios
* Real device or emulator/simulator:Simulator
* Appium CLI or Appium.app|exe:CLI

**Comment by JaniJegoroff** [comment]
I'm using company VPN all the time and no problems with Appium.

**Comment by mykola-mokhnach** [comment]
This does not look like Appium issue. Please ask it in Appium forum instead.
