### ISSUE TITLE
Error-Could not proxy command to remote server. Original error: Error: socket hang up

### ISSUE THREAD

**Issue by RonitJoardar** [appium/appium#8076]
## The problem

I am trying to automate an app on iPAD Air 2 and when I run my appium script I get the following error message-Could not proxy command to remote server. Original error: Error: socket hang up
Logs are mentioned below

## Environment

* Appium version - 1.6.4 beta(Appium Desktop)
* Desktop OS/version used to run Appium: ASX 10.12 Sierra
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: Real device iPAD Air 2

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/RonitJoardar/664ae270a5435206b84811db3ea790bd

## Code To Reproduce Issue [ Good To Have ]

String app_path= System.getProperty("user.dir")+"/Application/OracleServiceCloud-iOS-OracleServiceCloud-1.0.0.ipa";
		File app = new File(app_path);
		DesiredCapabilities cap = new DesiredCapabilities();
		cap.setCapability("deviceName", "Air 2");
		cap.setCapability("platformName", "IOS");
		cap.setCapability("platformVersion", "10.2");
		cap.setCapability(CapabilityType.BROWSER_NAME, "ios");
		cap.setCapability("automationName", "XCUITest");
		cap.setCapability("noReset", true);
		cap.setCapability("bundleId", "com.pankanis.apps.osc");
		cap.setCapability("xcodeConfigFile", "/Users/ronit.joardar/Documents/workspace/AppiumTest/appium.xcconfig");
		cap.setCapability("udid", "d6ee40dcb1779aba7b0324d8ede975362e2a17c0");
		cap.setCapability("updatedWDABundleId","pankanis.appium-WebDriverAgentRunner");
		cap.setCapability(MobileCapabilityType.APP,app.getAbsolutePath());
		driver= new IOSDriver(new URL("http://127.0.0.1:4725/wd/hub"),cap);

**Comment by imurchie** [comment]
What happens on the device? Can you manually open the WebDriverAgentRunner app which Appium installed?

**Comment by RonitJoardar** [comment]
Thanks for replying! 
The app gets installed on the device but does not get open end. Yes clicking on the app opens it

**Comment by imurchie** [comment]
On the command line can you try running

```
cd /Applications/AppiumDesktop.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent

xcodebuild build-for-testing test-without-building -project /Applications/AppiumDesktop.app/Contents/Resources/app/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=d6ee40dcb1779aba7b0324d8ede975362e2a17c0 -configuration Debug -xcconfig /Users/ronit.joardar/Documents/workspace/AppiumTest/appium.xcconfig
```

**Comment by RonitJoardar** [comment]
Yes I has tried this but did not work.
I get this message in the logs
No Info.plist found for target application at path /Users/ronit.joardar/Library/Developer/Xcode/DerivedData/WebDriverAgent-dfqspvdyxhodsnduoperzzrhxmla/Build/Products/Debug-iphoneos/IntegrationApp.app/Info.plist 
can this be a possible reason?

**Comment by RonitJoardar** [comment]
Just to add, when I build the project WebDriverAgent in xcode 
 In the +handleOpenUrl file I get the following error
 'openUrl:' is deprecated first deprecated in iOS 10.0, please use openURL:options:completionHandler
On the line 
  if (![[UIApplication sharedApplication] openURL:url]) {
    return FBResponseWithErrorFormat(@"Failed to open %@", url);
  }
if this helps.

**Comment by mykola-mokhnach** [comment]
I've found [this](http://www.cnblogs.com/JulieandJulia/p/5611603.html) solution so far. This looks like an issue with local Xcode settings.

**Comment by RonitJoardar** [comment]
@mykola-mokhnach I applied the mentioned settings on xcode, still the same issue. Any workaround which can be implemented?

**Comment by mykola-mokhnach** [comment]
Try it on different machine

**Comment by RonitJoardar** [comment]
Thanks a Ton for your help the issue got resolved. One last question please! How to open Inspector in the appium desktop app

**Comment by mykola-mokhnach** [comment]
Please use [this](https://github.com/appium/appium-desktop/releases) inspector. The detailed tutorial is present in [README](https://github.com/appium/appium-desktop) file

**Comment by akashkhandelwal** [comment]
@RonitJoardar How your issue got resolved?

**Comment by zyjin** [comment]
An unknown server-side error occurred while processing the command. Original error: Could not proxy command to remote server. Original error: Error: read ECONNRESET (WARNING: The server did not provide any stacktrace information)
