### ISSUE TITLE
Appium Inspector not launching.

### ISSUE THREAD

**Issue by bargeharish** [appium/appium#8077]
Hi

I am try to launch appium inspector but it shows me following error message.

"Could not start a new session

Be sure the Appium server is running with an application opened by using the "App Path" parameter in Appium.app (along with package and activity for Android) or by connecting with selenium client and supplying this in the desired capabilities object "

Logs

MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 10 ms - 83 
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 1 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"Android","platformVersion":"4.4","newCommandTimeout":"7200","app":"/Users/housing/Downloads/app-gamma-release.apk","automationName":"Appium","deviceName":"AndroidTest"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"Android",...
[Appium] Creating new AndroidDriver session
[Appium] Capabilities:
[Appium]   platformName: 'Android'
[Appium]   platformVersion: '4.4'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/housing/Downloads/app-gamma-release.apk'
[Appium]   automationName: 'Appium'
[Appium]   deviceName: 'AndroidTest'
[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
[BaseDriver] Session created with session id: 47ca4b82-260f-4883-8ea0-7b7e74b7b804
[debug] [AndroidDriver] Getting Java version

[AndroidDriver] Java version is: 1.8.0_101

[MJSONWP] Encountered internal error running command: Error: ENOENT: no such file or directory, scandir '/Users/housing/Documents/tools/build-tools'
    at Error (native)

[ADB] Checking whether adb is present
[debug] [AndroidDriver] Shutting down Android driver
[AndroidDriver] Cannot shut down Android driver; it has already shut down

[HTTP] <-- POST /wd/hub/session 500 123 ms - 224 

[HTTP] --> GET /wd/hub/status {}

[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 31 ms - 83 
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []

[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 9 ms - 83 

appium version:1.5.3
OS X : 10.11.16

**Comment by mykola-mokhnach** [comment]
1. It looks like Android SDK is not installed / ANDROID_HOME env variable is not present
2. This inspector is outdated and is not supported anymore. Consider using the new one: https://github.com/appium/appium-desktop/releases

Closing as non Appium-related issue.
