### ISSUE TITLE
iOS Swiping takes 5-6 minutes to complete

### ISSUE THREAD

**Issue by dkdodson3** [appium/appium#8079]
## The problem

A swipe command is sent, the phone waits 2-3 minutes, executes the swipe correctly, waits 2-3 minutes and then tests continue on. No sleeps added.

## Environment

* appium 1.6.4-beta
* appium-xcuitest-driver@2.23.1
* iOS 10.2
* Node.js version: v7.6.0
* Real Device: iPhone 7 Plus
* Using the python-client

## Link to Appium logs

https://gist.github.com/dkdodson3/0e5a19c246c77b7e5ac60e29d4b08746

## Code To Reproduce Issue [ Good To Have ]

```
def swipe(self, start_element, end_element):
	action = TouchAction(self.driver)
        action.press(start_element, 10, 10)
        action.wait(500)
        action.move_to(end_element, 10, 10)
        action.release()
        action.perform()
```

**Comment by mykola-mokhnach** [comment]
This might be XCTest issue. What do you see in device logs during the delay?

**Comment by mykola-mokhnach** [comment]
Can you also try "mobile: dragFromToForDuration" call and see whether it causes the same behaviour?
See https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md for more details

**Comment by dkdodson3** [comment]
Not seeing anything useful in the device logs...

SENT SWIPE
Mar 24 11:04:30 iPhone testmanagerd[1285] <Notice>: <private>
Mar 24 11:04:30 iPhone testmanagerd[1285] <Notice>: <private>
Mar 24 11:04:30 iPhone testmanagerd[1285] <Notice>: <private>
Mar 24 11:04:30 iPhone testmanagerd[1285] <Notice>: <private>

SWIPE HAPPENED
Mar 24 11:06:23 iPhone testmanagerd(AXRuntime)[1285] <Info>: void _AXManagePidState(CFDictionaryRef):87 pid status change recorded: {
Mar 24 11:06:23 iPhone testmanagerd(AXRuntime)[1285] <Info>: void _AXAddSuspendedPid(pid_t):260 Suspended pid added: 1187
Mar 24 11:06:23 iPhone testmanagerd(AXRuntime)[1285] <Info>: void _AXManagePidState(CFDictionaryRef):140 suspended pids: 1187 512067983.214482
Mar 24 11:06:23 iPhone testmanagerd[1285] <Notice>: <private>
Mar 24 11:06:28 iPhone testmanagerd(AXRuntime)[1285] <Info>: void _AXManagePidState(CFDictionaryRef):87 pid status change recorded: {
Mar 24 11:06:28 iPhone testmanagerd(AXRuntime)[1285] <Info>: void _AXAddSuspendedPid(pid_t):260 Suspended pid added: 1187
Mar 24 11:06:28 iPhone testmanagerd(AXRuntime)[1285] <Info>: void _AXManagePidState(CFDictionaryRef):140 suspended pids: 1187 512067988.914300
Mar 24 11:06:28 iPhone testmanagerd[1285] <Notice>: <private>
Mar 24 11:06:30 iPhone testmanagerd[1285] <Notice>: <private>
Mar 24 11:06:30 iPhone testmanagerd[1285] <Notice>: <private>

CONTROL FROM SWIPE WAS RETURNED 
Mar 24 11:09:30 iPhone testmanagerd[1285] <Notice>: <private>
Mar 24 11:09:30 iPhone testmanagerd[1285] <Notice>: <private>
Mar 24 11:09:30 iPhone testmanagerd[1285] <Notice>: <private>
Mar 24 11:09:30 iPhone testmanagerd[1285] <Notice>: <private>
Mar 24 11:09:30 iPhone testmanagerd[1285] <Notice>: <private>

**Comment by dkdodson3** [comment]
you got some python code I can try to "mobile: dragFromToForDuration"?

**Comment by dkdodson3** [comment]
So I tried to run a dragFromToForDuration but it did nothing... What am I doing wrong here?

params = {'toX': 282, 'toY': 299, 'element': u'59039AE9-054C-4DBF-8485-E94E66915435', 'duration': 0.5, 'fromY': 263, 'fromX': 145}
self.driver.execute_script('mobile: dragFromToForDuration', params)

**Comment by mykola-mokhnach** [comment]
probably the xcuitest driver you have is not at the recent version. Try to reinstall beta.

**Comment by dkdodson3** [comment]
reinstalled appium@beta
Version appium-xcuitest-driver@2.23.1

my code:
params =  {'toX': 282, 'toY': 330, 'element': u'A68757CA-1D44-489A-9E4E-A081D222E752', 'duration': 0.5, 'fromY': 294, 'fromX': 145}
self.driver.execute_script('mobile: dragFromToForDuration', params)

Appiums Output

2017-03-27 16:22:21:073 - [HTTP] --> POST /wd/hub/session/9fcfecd1-b735-4430-bc12-baa13174712c/execute {"sessionId":"9fcfecd1-b735-4430-bc12-baa13174712c","args":[{"toX":282,"toY":330,"element":"A68757CA-1D44-489A-9E4E-A081D222E752","duration":0.5,"fromY":294,"fromX":145}],"script":"mobile: dragFromToForDuration"}
2017-03-27 16:22:21:074 - [debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: dragFromToForDuration",[{"toX":282,"toY":330,"element":"A68757CA-1D44-489A-9E4E-A081D222E752","duration":0.5,"fromY":294,"fromX":145}],"9fcfecd1-b735-4430-bc12-baa13174712c"]
2017-03-27 16:22:21:074 - [debug] [XCUITest] Executing command 'execute'
2017-03-27 16:22:21:083 - [debug] [JSONWP Proxy] Proxying [POST /wda/element/A68757CA-1D44-489A-9E4E-A081D222E752/dragfromtoforduration] to [POST http://localhost:8100/session/DF139A1B-F19E-499D-8020-201DB961D228/wda/element/A68757CA-1D44-489A-9E4E-A081D222E752/dragfromtoforduration] with body: {"duration":0.5,"fromX":145,"fromY":294,"toX":282,"toY":330}
2017-03-27 16:28:24:068 - [debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"DF139A1B-F19E-499D-8020-201DB961D228","status":0}

Logs from iPhone:
https://gist.github.com/dkdodson3/eb816611d5ee7a1034e4c179077a7450

**Comment by mykola-mokhnach** [comment]
Can you try to with absolute coordinates instead of relative?

**Comment by dkdodson3** [comment]
Once I removed the element from the parameters the command worked...

What should I be looking for in the logs? 

I see tons of these "iPhone testmanagerd[3481] <Notice>: <private>" but nothing that says it is tapping on coordinates.

**Comment by mykola-mokhnach** [comment]
Happy to help. The reason of such behaviour will, probably, become one of the biggest XCTest secrets (unless you have somebody at Apple to ask) :)

**Comment by dkdodson3** [comment]
Any where else I could look to see what is taking so long to swipe?

**Comment by mykola-mokhnach** [comment]
Closing the issue as resolved.

**Comment by dkdodson3** [comment]
This is not resolved... It still takes the same amount of time... What needs to be done?

**Comment by mykola-mokhnach** [comment]
Np, I reopen the issue. But I have doubts anyone can explain the reason of the delay there

**Comment by jlipps** [comment]
Unfortunately we can't control WDA; it just took ~3 minutes to execute your command. I'd suggest raising an issue at Facebook's repo to let them know there is this huge delay. Maybe they have a better idea.

**Comment by kienmun** [comment]
I also facing the same issue which taking 3-4 minutes to perform action swipe action. Below is my code:
TouchAction TA = new TouchAction(getInstance().innerDriver);
TA.press(coorX + 240, coorY).waitAction(-1000).moveTo(-305, 0).release().perform();

I'm using xcode9 and appium 1.6.5. Anyone know how to solve this? Please help.

**Comment by vikramvi** [comment]
@kienmun please open new issue with below info

1. update to latest appium server, one you're using is quite old
2. Appium server log
3. Refer to https://discuss.appium.io/t/swipe-scroll-best-practice-with-java-client-5/18589/17
