### ISSUE TITLE
Unable to hide numeric keypad on android devices

### ISSUE THREAD

**Issue by HemantTrivedi** [appium/appium#8081]
## The problem

I am entering value in a textbox and then i want to hide the numeric keypad.
I try to find element using page source, but numeric keypad elements are not displaying in page source.
Also tried,
1. ((JavascriptExecutor) driver).executeScript("mobile: keyevent",  new HashMap<String, Double>() {{ put("keycode",(double) 61);}});
But our framework is not supporting above 
2. String command =" adb -s input keyevent 61" 
Process result = Runtime.getRuntime().exec(command); 
On using above command getting error : Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified .

## Environment

* Appium version (or git revision) that exhibits the issue: 1.4.16.1
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Windows
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: Android  6.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: 

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
1. Please update Appium to 1.6.4-beta
2. Have you tried _driver.hideKeyboard_?
3. Have you tried UIAutomation2 driver?
4. Google says it's also possible to execute

```
adb shell input keyevent 111
```

**Comment by HemantTrivedi** [comment]
@mykola-mokhnach . Thanks for the updates . please find the following 

1. Appium version we have is 1.4 .
2. We are invoking Android driver , and with Android driver object , we are not getting hidekeyboard() function.
3.  UIAutomation2 driver we , haven't tried. 

4. When I execute the following command , it generates error
Command :String command =" adb -s input keyevent 61" 
Process result = Runtime.getRuntime().exec(command); 


Error : java.io.IOException: CreateProcess error=2, The system cannot find the file specified

**Comment by JaniJegoroff** [comment]
@HemantTrivedi 
4. `adb` command you are using is completely wrong. Use the command @mykola-mokhnach provided and it will work.

**Comment by HemantTrivedi** [comment]
Tried this : String command = " adb shell input keyevent 111" ;
		 Process result = Runtime.getRuntime().exec(command);

Getting below error :
Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified

**Comment by HemantTrivedi** [comment]
@mykola-mokhnach @JaniJegoroff  

The issue is resolved . i am able to hide numeric keypad using driver.navigate().back().


Thanks for your help
