### ISSUE TITLE
Unable to accept Custom Notification Alert with Xcuitest 

### ISSUE THREAD

**Issue by vikaspayasi** [appium/appium#8082]
![screen shot 2017-03-23 at 3 44 18 pm](https://cloud.githubusercontent.com/assets/20970801/24243003/a57b532c-0fdf-11e7-9e0a-ee47971a7820.png)

Hello,

I am not able to accept custom notification alerts in iOS 10 with xcuitest.

Below code is not able to find alert:

                  WebDriverWait wait = new WebDriverWait(driver,30);
		  wait.until(ExpectedConditions.alertIsPresent());
                 Alert alert = driver.switchTo().alert();
                 alert.accept()

Appium 1.6.3, xcode: 8, Simulator: iOS 10.

Please provide solution for same.

XCUITEST trying to find 'getAlertText' command.

}
[debug] [MJSONWP] Calling AppiumDriver.getAlertText() with args: ["d9ba5212-d591-4edc-8caf-289e6ff6d4a2"]
[debug] [XCUITest] Executing command 'getAlertText'
[debug] [JSONWP Proxy] Proxying [GET /alert/text] to [GET http://localhost:8100/session/083E0AE2-DFD0-4091-AD4C-0622FC04E851/alert/text] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"083E0AE2-DFD0-4091-AD4C-0622FC04E851\",\n  \"status\" : 27\n}"
[HTTP] <-- GET /wd/hub/session/d9ba5212-d591-4edc-8caf-289e6ff6d4a2/alert_text 500 501 ms - 87

**Comment by amedvedjev** [comment]
when client itself shows notification (not system) you should accept it manually depending on code of your application.

it is just like same as you are doing with your application elements e.g. tap on your application Login button.

**Comment by vikaspayasi** [comment]
@amedvedjev I have attached screenshot of my alert along with issue. Kindly check and provide a solution to accept this pop up through java.

**Comment by amedvedjev** [comment]
yes. we have similar. not as big as yours :-) but same. so this is screen of your application and you should just check that notification alert loaded and tap on Yes/No button.

**Comment by vikaspayasi** [comment]
@amedvedjev : Is there any way by which i can do it through code in JAVA?
I have mentioned the code which i am using, but it's not working.

**Comment by vikramvi** [comment]
@vikaspayasi Try to find locator for Alert dialog with new appium desktop https://github.com/appium/appium-desktop
or use ARC approach, method get_source will help you getting identifier.

**Comment by Brian-Watson** [comment]
@vikaspayasi At the point in your code where this dialog is displayed, please print out the output for driver.getPageSource() and find the dialog controls there.  That dialog is not considered an actual Alert.

**Comment by amedvedjev** [comment]
@vikaspayasi  like all mentioned you should do just in same way like it is pure your application screen with control elements.

**Comment by vikaspayasi** [comment]
@amedvedjev @Brian-Watson @vikramvi 

Thanks for your suggestions,but still i am not able to find that alert. It is coming on top of another window, with the help of Inspector or driver.getPageSource() i can access the xml for background window on which this alert is pops up, not getting xml of application pop up and hence unable to find xpath, ids or tag.

Would really appreciate if you guys can provide some other way.

Thanks,

**Comment by vikaspayasi** [comment]
@jlipps : Can you provide any solution on this with xcuitest.

**Comment by mayukataoka** [comment]
If this is a standard iOS alert, driver.switchTo().alert() should work with Appium 1.6.3, xcode: 8, Simulator: iOS 10. 

Maybe there is something different about the alert in your app?

**Comment by vikaspayasi** [comment]
@mayukataoka : This is not iOS standard alert, it's custom alert instead.

I got the solution for this. This is not coming on appium inspector because of Accessibility Identifier.

We have to make it visible through code.

Thanks,

**Comment by keshavwy** [comment]
@vikaspayasi Can you help how to make alert visible? I am facing similar kind of issue.

**Comment by vikaspayasi** [comment]
@keshavwy : You need to tell your iOS developer to enable Accessibility for these type of elements in order to get these visible on appium.
