### ISSUE TITLE
[IOS, XCUnitTest] has anyone else noticed degrading performance in repeatedly launching test script?

### ISSUE THREAD

**Issue by kenmcc** [appium/appium#8083]
## The problem
Following on from https://github.com/appium/appium/issues/7192 being reported yesterday as also happening on 64 bit devices, I decided to writ a very simple looper to see if i can determine how many restarts we get before a physical reboot is needed.

The test case is as follows (simplified from real script so may not be syntactically correct):

```
caps= {'deviceName': device_name, 'platformName': 'iOS', 'newCommandTimeout': 3600, 'udid': device_id, 'fullReset': False, 'automationName': 'xcuitest', 'platformVersion': "10.2.1", 'realDeviceLogger': 'idevicesyslog', 'bundleId': 'com.google.ios.youtube'}
for loop in testloops:
    loopstart = datetime.datetime.now()
    launchstart = datetime.datetime.now()
    driver = webdriver.Remote("http://localhost:4723/wd/hub", caps)
    launchend = datetime.datetime.now()
    launchtime = (launchend-launchstart).seconds
    logger.info("Created webdriver remote in {0} seconds".format(launchtime))
    driver.save_screenshot("launch{0:04}_screenshot.png".format(loop))
    sleep(5)
    driver.close_app()
    loopend = datetime.datetime.now()
    looptime = (loopend - loopstart).seconds
    logger.debug("END OF LOOP : {0} seconds duration".format(looptime))

```
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta
* Last Appium version that did not exhibit the issue (if applicable): unknown
* Desktop OS/version used to run Appium: OSX 10.11.6
* Node.js version (unless using Appium.app|exe): 6.5.0
* Mobile platform/version under test: IOS 10.2.1
* Real device or emulator/simulator: Real
* Appium CLI or Appium.app|exe: appium python bindings

I've set this up to perform 2000 test loops. Currently on loop 31 of these (had previously got to 65 and noticed the degrading performance so restarted with the timings printed out) and these are the results so far (I've abbreviated after the middle ones to make it shorter....):

```
2017-03-23 11:01:58,824 - DEBUG - ///////////////// Test run 0 of 2000 \\\\\\\\\\
2017-03-23 11:03:57,667 - INFO - Created webdriver remote in 118 seconds
2017-03-23 11:04:03,818 - DEBUG - ****** END OF LOOP : 124 seconds duration ******

Loop:1; created remote: 15 seconds; loop duration: 21 seconds 
Loop:2; created remote: 17 seconds; loop duration: 22 seconds 
Loop:3; created remote: 16 seconds; loop duration: 23 seconds 
Loop:4; created remote: 17 seconds; loop duration: 24 seconds 
Loop:5; created remote: 19 seconds; loop duration: 26 seconds 
Loop:6; created remote: 20 seconds; loop duration: 28 seconds 
Loop:7; created remote: 19 seconds; loop duration: 27 seconds 
Loop:8; created remote: 21 seconds; loop duration: 29 seconds 
Loop:9; created remote: 19 seconds; loop duration: 28 seconds 
Loop:10; created remote: 26 seconds; loop duration: 35 seconds 
Loop:11; created remote: 21 seconds; loop duration: 30 seconds 
Loop:12; created remote: 26 seconds; loop duration: 36 seconds 
Loop:13; created remote: 23 seconds; loop duration: 33 seconds 
Loop:14; created remote: 25 seconds; loop duration: 36 seconds 
Loop:15; created remote: 32 seconds; loop duration: 43 seconds 
Loop:16; created remote: 28 seconds; loop duration: 40 seconds 
Loop:17; created remote: 36 seconds; loop duration: 49 seconds 
Loop:18; created remote: 39 seconds; loop duration: 54 seconds 
Loop:19; created remote: 45 seconds; loop duration: 56 seconds 
Loop:20; created remote: 53 seconds; loop duration: 69 seconds 
Loop:21; created remote: 47 seconds; loop duration: 63 seconds 
Loop:22; created remote: 49 seconds; loop duration: 66 seconds 
Loop:23; created remote: 67 seconds; loop duration: 84 seconds 
Loop:24; created remote: 47 seconds; loop duration: 59 seconds 
Loop:25; created remote: 45 seconds; loop duration: 62 seconds 
Loop:26; created remote: 59 seconds; loop duration: 78 seconds 
Loop:27; created remote: 60 seconds; loop duration: 78 seconds 
Loop:28; created remote: 66 seconds; loop duration: 84 seconds 
Loop:29; created remote: 57 seconds; loop duration: 77 seconds 
Loop:30; created remote: 69 seconds; loop duration: 89 seconds

2017-03-23 11:28:28,748 - DEBUG - ///////////////// Test run 31 of 2000 \\\\\\\\\\
2017-03-23 11:29:36,779 - INFO - Created webdriver remote in 68 seconds
2017-03-23 11:29:56,908 - DEBUG - ****** END OF LOOP : 88 seconds duration ******
```

and in fact since i started writing this it's up to loop 40:

```
017-03-23 11:41:25,672 - test - DEBUG - ///////////////// Test run 40 of 2000 \\\\\\\\\\
2017-03-23 11:42:38,849 - test - INFO - Created webdriver remote in 73 seconds
2017-03-23 11:43:01,001 - test - DEBUG - ****** END OF LOOP : 95 seconds duration ******
```

So as you can see, it's quite quickly degrading in both the launch time of the application, and I presume the time to take the screenshot is also increasing as there's nothing else happening in the loop..... ( I consider the first one an outlier as I had just booted the ipad, so maybe it wasn't fully ready)

Has anyone else noticed similar behaviour?

**Comment by mykola-mokhnach** [comment]
Cool test - thanks for the investigation. It would be interesting to know the result if one changes the default values for capabilities like
**useNewWDA**
or
**usePrebuiltWDA**

**Comment by kenmcc** [comment]
Ok, so some more findings.
This time I got to loop 54 successfully.
Loop 55, I created the webdriver.remote in 103 seconds. Then when i tried to screenshot, i get the exception 'an unknown server-side error occurred while processing the command.... Original error : Error: socket hang up"....

all subsequent test loops failed to launch the webdriveragent failed *until loop 286* which has started recovering and is now behaving correctly (102 seconds to open, 184 to complete)
287 : 35, 41
288:  24, 32
289: 19,29
..
293: 40, 61
294: 36, 49
295: 28, 51

... it's all over the place now!

I'll let this run for a bit more and then try those 2 capabilities you suggested.

**Comment by kenmcc** [comment]
This ran to loop 358 ok, failed to screenshot in 359 and then failed to create the webdriver remote until loop 591 and is currently on loop 631, again getting slower and slower:
loop 628: 83, 125
629: 97, 187, 
630: 155, 288
631: 158, 164

I'm going to leave this run overnight and see if i get to the blackscreen at launch, and will implement those capabilities tomorrow

**Comment by kenmcc** [comment]
I hit the blackscreen on run 712 :(

**Comment by kenmcc** [comment]
have added the 'usePrebuildWDA' capability and am seeing the same behaviour in terms of increasing duration of test to a point where they fail in quick succession for a while and recover and repeat.
Waiting to see if i also get black screen

**Comment by kenmcc** [comment]
Now the device has thrown up the 'do you trust this computer' dialog, which means that WDA fails to start. Not seen this in relation to starting the WDA before....

**Comment by kenmcc** [comment]
OK.
Running over the weekend, again looking to get 2000 loops of the same test. I rebooted the device and restarted appium 1.6.4-beta prior to launching the test run at (2017-03-24 17:09:19)

Capabilities this time are:
`caps= {'deviceName': device_name, 'platformName': 'iOS', 'newCommandTimeout': 3600, 'udid': device_id, 'fullReset': False, 'automationName': 'xcuitest', 'platformVersion': "10.2.1", 'realDeviceLogger': 'idevicesyslog', 'bundleId': 'com.google.ios.youtube', 'clearSystemFiles': True, 'preventWDAAttachments': True, 'usePrebuiltWDA': True, 'useNewWDA': True}
`
Loops 1-22 Ran ok. Fastest loop 25seconds, slowest loop 342 seconds, avg = 156.7, Median = 174 seconds

Loop 23 Failed, Exception taking screenshot, 1444 seconds before 'completing'

Loops 24-36 ran OK, Fastest loop 37 seconds, slowest 252, average 81, median 57

Loop 37 Failed, again exception taking screenshot, 1259 seconds before 'completing'

Loops 38-67 ran ok, Fastest = 37, slowest, 353, average 189, median 183

Loop 68 Failed (413 seconds) and returned a huge exception stacktrace:
```
Exception Message: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session: An unknown server-side error occurred while processing the command. Original error: Active application instance is not expected to be equal to nil
(
	0   CoreFoundation                      0x000000018ede91d0 <redacted> + 148
	1   libobjc.A.dylib                     0x000000018d82055c objc_exception_throw + 56
	2   CoreFoundation                      0x000000018ede908c <redacted> + 0
	3   Foundation                          0x000000018f8a102c <redacted> + 112
	4   WebDriverAgentLib                   0x0000000102055a0c +[FBApplication fb_activeApplication] + 612
	5   WebDriverAgentLib                   0x0000000102044428 -[FBSession application] + 52
	6   WebDriverAgentLib                   0x000000010204a9d8 +[FBSessionCommands currentCapabilities] + 116
	7   WebDriverAgentLib                   0x000000010204a8a0 +[FBSessionCommands sessionInformation] + 280
	8   WebDriverAgentLib                   0x0000000102049eec +[FBSessionCommands handleCreateSession:] + 936
	9   WebDriverAgentLib                   0x0000000102036918 -[FBRoute_TargetAction mountRequest:intoResponse:] + 208
	10  WebDriverAgentLib                   0x000000010202c6d0 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496
	11  RoutingHTTPServer                   0x00000001020fe3cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144
	12  RoutingHTTPServer                   0x00000001020feb80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44
	13  libdispatch.dylib                   0x000000018dc721bc <redacted> + 16
	14  libdispatch.dylib                   0x000000018dc83084 <redacted> + 320
	15  libdispatch.dylib                   0x000000018dc721bc <redacted> + 16
	16  libdispatch.dylib                   0x000000018dc76d68 _dispatch_main_queue_callback_4CF + 1000
	17  CoreFoundation                      0x000000018ed96810 <redacted> + 12
	18  CoreFoundation                      0x000000018ed943fc <redacted> + 1660
	19  CoreFoundation                      0x000000018ecc22b8 CFRunLoopRunSpecific + 444
	20  Foundation                          0x000000018f7ff26c <redacted> + 304
	21  Foundation                          0x000000018f853aa0 <redacted> + 88
	22  WebDriverAgentLib                   0x000000010202b728 -[FBWebServer startServing] + 320
	23  WebDriverAgentRunner                0x000000010201bed0 -[UITestingUITests testRunner] + 120
	24  CoreFoundation                      0x000000018edef150 <redacted> + 144
	25  CoreFoundation                      0x000000018ece1eac <redacted> + 284
	26  XCTest                              0x000000010023e0a8 __24-[XCTestCase invokeTest]_block_invoke_2 + 388
	27  XCTest                              0x0000000100272c98 -[XCTestContext performInScope:] + 208
	28  XCTest                              0x000000010023df0c -[XCTestCase invokeTest] + 268
	29  XCTest                              0x000000010023e5e0 -[XCTestCase performTest:] + 460
	30  XCTest                              0x000000010023ba5c -[XCTestSuite performTest:] + 428
	31  XCTest                              0x000000010023ba5c -[XCTestSuite performTest:] + 428
	32  XCTest                              0x000000010023ba5c -[XCTestSuite performTest:] + 428
	33  XCTest                              0x0000000100227740 __25-[XCTestDriver _runSuite]_block_invoke + 56
	34  XCTest                              0x0000000100248260 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 528
	35  XCTest                              0x00000001002275d8 -[XCTestDriver _runSuite] + 460
	36  XCTest                              0x00000001002283b4 -[XCTestDriver _checkForTestManager] + 296
	37  XCTest                              0x0000000100274164 _XCTestMain + 628
	38  CoreFoundation                      0x000000018ed96a44 <redacted> + 20
	39  CoreFoundation                      0x000000018ed96240 <redacted> + 288
	40  CoreFoundation                      0x000000018ed94094 <redacted> + 788
	41  CoreFoundation                      0x000000018ecc22b8 CFRunLoopRunSpecific + 444
	42  GraphicsServices                    0x0000000190776198 GSEventRunModal + 180
	43  UIKit                               0x0000000194d027fc <redacted> + 684
	44  UIKit                               0x0000000194cfd534 UIApplicationMain + 208
	45  XCTRunner                           0x00000001000f03d4 XCTRunner + 33748
	46  libdyld.dylib                       0x000000018dca55b8 <redacted> + 4
)
```
Seems to have recovered then again
Loops 69 -> 96 Succeeded, fastest 28, slowest 330, avg 158, median 175 seconds

and then it was all over, nothing succeeded to execute from loop 97 (2017-03-24 22:05:55) to now(2017-03-27 09:22:50) at loop 455. It executed with success or with successful recovery for just under 5 hours.

I'm going to remove the 'newWDA' capability and see if that is having any impact on the behaviour.

It appears to be a WDA issue still, so I'm not sure what if anything can be done to solve it, as fundamentally it looks to be exhibit the same behaviour that was previously seen on the 32 bit devices; the appium console shows 'too many instances of this service are already running' as it did for the 32 bit devices.

**Comment by mykola-mokhnach** [comment]
What if **useNewWDA** is set to _false_?

**Comment by kenmcc** [comment]
yeah am going to try that to see. have changed both usePrebuiltWDA and useNewWDA to false

**Comment by kenmcc** [comment]
Ok, so using those capabilities, I got 55 successful tests, still getting ever slower as before, before my ipad went into a reboot (i have no auto-updates or anything enabled), and didn't come back up for over 5 minutes. The test was still trying to continue so got 225 failures.

It's now trying to launch WDA again after the reboot completed, so will be interesting to see if it recovers.

**Comment by kenmcc** [comment]
A new failure mechanism this time:
1-> 39, OK 21seconds minimum, 101 maximum
40->122 Failed
first failure was with 
`Exception Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up
`
and then 41-122 were with 
`Exception Message: An unknown server-side error occurred while processing the command. Original error: Unknown device or simulator UDID: '0d5a4XXXX'
`
so it's like as if the device rebooted again..... and then recovered for a bit because 

123-> 146 OK 21seconds min, 128 max

147: Failed - it created the session in 22 seconds and then threw an empty exception trying to take the screenshot

148-> 2000 instantaneous fails. Whereas before it would sit for 10 minutes or more before failing the test.

**Comment by kenmcc** [comment]
Restarted Appium, and ran a new set of tests; first 17 ran ok, then the 18th threw an exception, dumped the screenshot to stdout and forced a reboot of the device, and when it booted, it instantly rebooted once more..

Getting weirder and weirder.

Think i'll set that useNewWDA back to true for the evening run

**Comment by kenmcc** [comment]
So last nights run failed after 25 test loops.
loop 26 failed to take a screenshot even though it apparently created the session after 225 seconds.
It appears then that the device rebooted, since loops 27-> 371 report an exception 'unknown device or simulator'
From 372-> 728 (this mornings current running test loop) failed with ' unable to launch webdriverAgent', I suspect because after reboot the device had gone to lock screen and needed to be unlocked (press the home key). All tests failed after 153-155 seconds (seems thats how long it was trying to start webdriveragent for
Did that, then it's asking do I trust the computer, so hit Trust.

The next test runs still failed to launch WebDriverAgent, so the test loop will never seem to recover.

This is really frustrating me. We need to be able to run many unattended automated tests of various durations, but as it stands I can't achieve this. I understand it's not a fault of Appium though, it seems to be much deeper, either XCode or XCUITest or thereabouts.

If I could even figure out a consistent mechanism that would allow some sort of workaround to allow testing to succeed it'd be fine, but so far i've struggled to do so.

Am I the only one seeing this, or am I the only one looking for it?

**Comment by kenmcc** [comment]
The only way i could recover this time was to reboot the device, (i'd already tried restart appium so I don't know if it could have been left running).
And the first test caused a reboot of the ipad.
this device is 3 weeks old - it seems to be dying in front of my eyes!

**Comment by Brian-Watson** [comment]
@kenmcc So are you launching an appium server process and then running 100s of tests against it?

I've found that even with the older versions of Appium, after running for a while, performance goes down and flakey errors start popping up.  I've actually re-worked my automation to start a new Appium process for each test suite I run.  Each suite has 1 to 10 tests in it.  Once the suite is over, I kill the process so the next suite gets a new one.  Since I've started doing this, my runs are much more stable.  It take a little longer to execute since you have the extra time it takes to start and stop the Appium process, but it's ultimately worth it in the end.

**Comment by kenmcc** [comment]
Hi Brian,
yes that was my current mode of operation, although I'm working on implementing your suggestion at the moment. For some reason the startup time of appium appears to be large or small, and I'm not sure why that might be. But yeah, need to wait for appium to be ready before continuing on with the test launch.

Ultimately I might resort to only doing one test run inside an appium run if it means i get stability.

**Comment by mare1012** [comment]
Hallo @kenmcc , @Brian-Watson , @mykola-mokhnach 

I'm having a similiar problem with appium. But I'm testing a web-app on safari with iOS 10.3.1 using appium 1.6.5 and iso-webkit-debug-proxy. The test script sometimes works but sometimes doesn't. Until now I don't know exactly how to solve this problem. Do you guys know how to make the web-app-test using appium more stable?

here is my test script:
https://gist.github.com/mare1012/cbb66ac36e840f93a64ace3487b3f922
and here is my log-file, if the test its failing:
https://gist.github.com/mare1012/14395f42689d002ecd595a550d648470

**Comment by mykola-mokhnach** [comment]
@mare1012 Try https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/wda-custom-server.md

**Comment by mare1012** [comment]
@mykola-mokhnach I was trying to configure like the site you sent. But it's not working for me. I also already added "webDriverAgentUrl" to my script. But the error says " couldn't proxy command to remote server. 

here is the new log-file:
https://gist.github.com/mare1012/189642df1bad0cafd621b98e12e32732

Do you you have any suggestion?

**Comment by mykola-mokhnach** [comment]
ECONNREFUSED means WDA server is not running. Have you tried to build and deploy WDA to the device manually from Xcode first to verify WDA can be compiled and installed? Have you checked the xcodebuild log?

**Comment by mare1012** [comment]
@mykola-mokhnach I did, after installing iProxy i cleaned and builded the project from Xcode. And then I run the test from the terminal. If I see the log, WDA will always be trying to create but it always fails

**Comment by mare1012** [comment]
@mykola-mokhnach now I'm having another problem. It says, webkit remote debugger disconnected. even sometimes the script is working, but the script is often failing.

here is my new log-file( incl. xcodebuild log)
https://gist.github.com/mare1012/f351035e7d7b17cf5626a64fa4581c98

**Comment by DudaGod** [comment]
Hello guys @jlipps @imurchie @mykola-mokhnach.

I'm having a very similar problem. But I'm testing a website in iPhone 8 simulator with iOS 11 using appium 1.7.1. When running tests, I do not experience degrading perfomance like that of @kenmcc. But if something goes wrong: "socket hang up", "remote debugger is not connected", "ECONNRESET", ... there is a high probability that the appium will not start later when the next test is run.

Have you an understanding of how this can be fixed? 
Thank you.

**Comment by kenmcc** [comment]
I'm out of this space now, so won't be able to help any further I'm afraid.
