### ISSUE TITLE
Appium v1.6.4-beta not detecting the proper elements.

### ISSUE THREAD

**Issue by sjenasears** [appium/appium#8085]
## The problem

When i tried to click some element using appium Ui it is going to different screen.
It is not able to detect the right elements.

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4 Beta
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:Mac Sieera
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test:ios
* Real device or emulator/simulator:simulator
* Appium CLI or Appium.app|exe:cli

## Details

When i tried to click some element using appium Ui it is going to different screen.
It is not able to detect the right elements.
When i tried to open in simple simulator my app is working fine.But through appium ui it is not detecting to right screen.

**Comment by mykola-mokhnach** [comment]
1. Sorry, it is not possible to help having only this information, which is provided in the description
2. If you are unsure whether this is a bug then please ask the question in Appium forum first. Developers simply don't have time to answer howto questions.

**Comment by sjenasears** [comment]
Click on tap of an appium element through new appium inspector, But the UI redirects to a wrong screen.
It is a bug in Appium inspector UI.
Because same is working fine if click on simulator manually.

**Comment by dpgraham** [comment]
The screenshot and inspector contain the state of the app at the point in time immediately after the `tap` action was completed. If you want to update to the current state of the app, press the `Refresh` button above the inspector.
