### ISSUE TITLE
Appium v1.6.3 Unable to get WebDriverAgent for Physical Device

### ISSUE THREAD

**Issue by Jordan-Little314** [appium/appium#8087]
## The problem

Hello Appium Team,

As the title says, I'm unable to get the WDA working properly for Appium testing on a physical device. Everything works fine when using a simulator, but for some reason I can't get this working for a physical device. My understanding is that I don't have the .app file in the debug-iphoneos folder, while the .app file IS in the debug-iphonesimulator folder.

I am using v1.6.3 server through the terminal, and then running the Appium 1.5.3 app to use the inspector to create automation scripts.

I'm very new to Appium, so I apologize if the solution is trivial, but I was unable to find anything via Google.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): Never working for physical device
* Desktop OS/version used to run Appium: Mac OS 10.12.2
* Node.js version (unless using Appium.app|exe): 7.4.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: both?

## Link to Appium logs

https://gist.github.com/Jordan-Little314/9feb97f09dad5315a74d79893b4cfcf0

**Comment by mykola-mokhnach** [comment]
Please follow [this tutorial](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md) to set up automation for real device

**Comment by sgupta3112** [comment]
Go to below given path 
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

Then open WebDriverAgent.xcodeproj using xcode and do the code sign-in. 

Then build the application on real device. your issue will get resolved.
