### ISSUE TITLE
appium 1.6.4 beta Calling AppiumDriver.performTouch() returns [iProxy] recv failed: Operation not permitted

### ISSUE THREAD

**Issue by songzcn** [appium/appium#8089]
## The problem

Hi, appium team,
     i have trouble when i  perform touch a point on my ios device. 
    Appium actually called command 'performTouch', but when appium executed command 'performTouch',it returned '[iProxy] recv failed: Operation not permitted'.
     It seems that connection to WDA was broken.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6.4 beta
* Last Appium version that did not exhibit the issue (if applicable): not tested
* Desktop OS/version used to run Appium: OSX 10.12
* Node.js version (unless using Appium.app|exe): 7.0.0
* Mobile platform/version under test: ios 10.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:  Appium desktop 1.0.0 beta4

## Link to Appium logs

https://gist.github.com/songzcn/70da4314904d85275c0e5250bcf6f51c

**Comment by mykola-mokhnach** [comment]
There is 
```
[2017-03-24 03:00:01][Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability
```
record in the log. Have you tried to increase this timeout?

And regarding the touch action - try "mobile: tap". More details [here](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md)

**Comment by songzcn** [comment]
@mykola-mokhnach i have try both way you said, both were failed...
Here is the error log when i use "mobile:tap"
https://gist.github.com/songzcn/faf1e227d5a025d3ad96ea3d0eb2a2dc

**Comment by mykola-mokhnach** [comment]
Can you show me the log from the real device itself when this error happens in Appium?

**Comment by songzcn** [comment]
here is the result of idevicesyslog
https://gist.github.com/songzcn/def6c9b970823626db12fb4e571a06a7

**Comment by mykola-mokhnach** [comment]
Nothing suspicious in the log. Although I see, that the version of the driver, which you have installed, is not the newest one. Please reinstall beta to make sure all the modules are updated to most recent versions and try one more time with "mobile: tap":

```
npm uninstall -g appium
npm install -g appium@1.6.4-beta
```

**Comment by amedvedjev** [comment]
@mykola-mokhnach tried "mobile:tap" with latest appium 1.6.4-beta - and result TAP does not happen. Although e.g. Touch does not have any problem.

```
// touch tap
new TouchAction((MobileDriver) driver).press(element).waitAction(70).release().perform();

// mobile:tap
JavascriptExecutor js = (JavascriptExecutor) driver;
HashMap<String, String> tapObject = new HashMap<String, String>();
tapObject.put("x", String.valueOf(element.getCenter().getX()));
tapObject.put("y", String.valueOf(element.getCenter().getY()));
tapObject.put("element", element.getId());
System.out.println("tapObject: " + tapObject.toString());
js.executeScript("mobile:tap", tapObject);
```

Log of "mobile:tap":
```
tapObject: {x=187, y=578, element=87F806C9-2722-450E-95DA-ED9FA0ACD940}
[HTTP] --> POST /wd/hub/session/0002829e-d13c-49cc-891b-d64b5f40983e/execute {"script":"mobile:tap","args":[{"x":"187","y":"578","element":"87F806C9-2722-450E-95DA-ED9FA0ACD940"}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile:tap",[{"x":"187","y":"578","element":"87F806C9-2722-450E-95DA-ED9FA0ACD940"}],"0002829e-d13c-49cc-891b-d64b5f40983e"]
[debug] [XCUITest] Executing command 'execute'
[debug] [JSONWP Proxy] Proxying [POST /wda/tap/87F806C9-2722-450E-95DA-ED9FA0ACD940] to [POST http://localhost:8100/session/BDC48FD3-000A-4544-BC39-DDA3C0D136E8/wda/tap/87F806C9-2722-450E-95DA-ED9FA0ACD940] with body: {"x":187,"y":578}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"BDC48FD3-000A-4544-BC39-DDA3C0D136E8","status":0}
[debug] [MJSONWP] Responding to client with driver.execute() result: null
[HTTP] <-- POST /wd/hub/session/0002829e-d13c-49cc-891b-d64b5f40983e/execute 200 855 ms - 76 
```

**Comment by mykola-mokhnach** [comment]
@amedvedjev Probably because you are providing absolute coordinates to "mobile: tap" instead of relative

**Comment by amedvedjev** [comment]
@mykola-mokhnach you are correct.
```
tapObject.put("x", "0");
tapObject.put("y", "0");
```
started work -)!
but look failed to tap with some elements on page.
i tried to tap on it in loop with same delay (just to wonder if it work):
```
        for (int i=0; i<10; i++) {
            assertTrue("Button NOT loaded", mainPage.tapButton());
            sleep(5);
        }
```

and still nothing. so right now at least for our application "TouchAction" is preferable way.
```
tapObject: {x=0, y=0, element=CE1437EE-C0F2-4120-9989-4C7A5EDACAF4}
[HTTP] --> POST /wd/hub/session/40d63d92-adfe-41fb-8025-899a5cc72d68/execute {"script":"mobile:tap","args":[{"x":"0","y":"0","element":"CE1437EE-C0F2-4120-9989-4C7A5EDACAF4"}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile:tap",[{"x":"0","y":"0","element":"CE1437EE-C0F2-4120-9989-4C7A5EDACAF4"}],"40d63d92-adfe-41fb-8025-899a5cc72d68"]
[debug] [XCUITest] Executing command 'execute'
[debug] [JSONWP Proxy] Proxying [POST /wda/tap/CE1437EE-C0F2-4120-9989-4C7A5EDACAF4] to [POST http://localhost:8100/session/C61E784B-AE10-4E77-8A7C-FB972582C11A/wda/tap/CE1437EE-C0F2-4120-9989-4C7A5EDACAF4] with body: {"x":0,"y":0}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"C61E784B-AE10-4E77-8A7C-FB972582C11A","status":0}
[debug] [MJSONWP] Responding to client with driver.execute() result: null
[HTTP] <-- POST /wd/hub/session/40d63d92-adfe-41fb-8025-899a5cc72d68/execute 200 886 ms - 76 
    sleep - 5
```

**Comment by mykola-mokhnach** [comment]
@amedvedjev (0, 0) is, probably, not the best place to click.
I'd prefer (el.width / 2,el. height / 2)

**Comment by amedvedjev** [comment]
@mykola-mokhnach AAAA!!!!! sec will check! Pls just put it more clear into doc.
Working! thanks. will check more places.

**Comment by songzcn** [comment]
@mykola-mokhnach thanks! I use appium cli 1.6.4 beta，mobile:tap works fine. Then i use appium desktop 1.0.0 beta 4 again，the problem happens again. Perhaps the appium desktop haven't merged the newest appium version?

**Comment by mykola-mokhnach** [comment]
Maybe... I don't know for sure, since I use my own [inspector](https://github.com/mykola-mokhnach/Appium-iOS-Inspector) ;)

**Comment by mykola-mokhnach** [comment]
@amedvedjev Y're welcome to create a PR  and fix the doc. It's [here](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md)

**Comment by amedvedjev** [comment]
Made more tests for performance. Result not nice. Mobile:tap 30%+ slower.
20 taps (execution time in ms):
```
new TouchAction((MobileDriver) driver).press(element).waitAction(70).release().perform();
````
 - 28194

```
new TouchAction((MobileDriver) driver).tap(element).perform();
```
- 26035

```
element.click();
```
- 27701

finally: mobile:tap
- 41948

**Comment by vjmaiky** [comment]
@mykola-mokhnach 

Im trying to use this method to bring up the iOS control center (i want to enable airplane mode)

	public static void newWayToEnableAirplaneMode(){
		Dimension screenSize = AppiumDriverInstance.getInstance().manage().window().getSize();
		int width = screenSize.getWidth();
		int height = screenSize.getHeight();
		JavascriptExecutor js = (JavascriptExecutor) AppiumDriverInstance.getInstance();
		HashMap<String, Object> params = new HashMap<String, Object>();
		params.put("duration", 1.0);
		params.put("fromX", width/2);
		params.put("fromY", height-1);
		params.put("toX", width/2);
		params.put("toY", height/2);
		params.put("element", ((RemoteWebElement) element).getId());
		js.executeScript("mobile: dragFromToForDuration", params);
	}

What should i put as element? if i comment it out nothing happens...any hint? or other way to do it?

**Comment by mykola-mokhnach** [comment]
No idea - I've never tried anything like this

**Comment by vjmaiky** [comment]
you said once that you`re working directly with WDA coordinates...how do you do that? (maybe sound like a noob question but i`m out of ideas...tried tons of things with no results)...

**Comment by mykola-mokhnach** [comment]
Easy, via direct API calls: https://github.com/facebook/WebDriverAgent/wiki/Queries
