### ISSUE TITLE
Element is located by Appium inspector but not present in Page source

### ISSUE THREAD

**Issue by HemantTrivedi** [appium/appium#8090]
## The problem

An element is located by xpath and name in ios 10+ by appium . But when I print page source in console , it's not displaying the element .

## Environment

* Appium version : 1.6.3
* Desktop OS/version used to run Appium:MAC
* Mobile platform/version under test:iPhone 6 s
* Real device or emulator/simulator: Real device

## Details

I have scenario as follow  
1. Clicking on calendar icon , I am able to locate dates by name and xpath 
2. But when i am tring to click on same , it says no such element .
3. Also I tried to print the Page source after clicking on date icon and giving 20 sec wait   to make sure whether dates are present in source or not . But dates are not displayed . 

A perticular element in calender is haveing xpath as : //XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeTable[1]/XCUIElementTypeCell[4]/XCUIElementTypeButton[9]

and name as "26" is date of i.e month .

**Comment by HemantTrivedi** [comment]
@mykola-mokhnach   Please give me a solution . I am stuck due to this

**Comment by vjmaiky** [comment]
you could try:

//XCUIElementTypeButton[9][@name='your element name']
//XCUIElementTypeButton[9][contains(@name,'your element name)']

find it using its siblings:
//other button that it is displayed and it is a sibling for your button/preceding-sibling:://XCUIElementTypeButton[1][@name='your element name']

etc.

**Comment by dpgraham** [comment]
@HemantTrivedi How did you figure out that the calendar has that xpath? I'm just trying to understand why there's no calendar in the app source but you were able to infer an xpath.

**Comment by HemantTrivedi** [comment]
@dpgraham  I was able to locate the dates through appium locater. But after clicking on calendar icon when I printed page source on the console, there were no elements relate to a calendar in the page source.

**Comment by HemantTrivedi** [comment]
@vjmaiky @dpgraham My doubt is , how can I deal with dates. Because when I search by name or xpath and click on it, it says no such element . How can I click on the element . 
![datepicker](https://cloud.githubusercontent.com/assets/22052541/24325157/0bd1629e-11b9-11e7-939e-a1921219ac84.jpg)

**Comment by prashantkumar1041** [comment]
@HemantTrivedi : I'm unable to launch my app on real devices (iPhones), but it works perfectly on simulators. Could you pls help me with the steps/setups you have followed for your test scripts.

Coming to your query, two things: 1) Though I have not seen your scripts, I feel you need to first click on the date picker then date-picker would be picked by Selenium.
2) Get the table >> Get all rows >> Get column values and then compare and select

**Comment by HemantTrivedi** [comment]
@mykola-mokhnach Please give me a solution . I am stuck due to this

**Comment by HemantTrivedi** [comment]
@dpgraham

**Comment by dpgraham** [comment]
Have you tried different locator strategies?

https://saucelabs.com/blog/advanced-locator-strategies

Also, try running it in our desktop app: https://github.com/appium/appium-desktop/releases/latest. With that you can open up an ad-hoc appium session and inspect the contents of your app's source.

**Comment by HemantTrivedi** [comment]
@dpgraham  , I have tried with xpath and name as there are no other locates available.

**Comment by jlipps** [comment]
If the control doesn't show up in the source, Appium won't be able to automate it. This is likely because your dev used a custom control of some kind. Most automation technologies only work on standard UI controls.

**Comment by LakshminarayananG** [comment]
Hi.. I am trying to click on the calendar icon in my app in IOS. The console says that the element is clicked but the calendar popup is not displayed after clicking on it.

**Comment by skansar** [comment]
@HemantTrivedi did you get solution for this, if so how?
