### ISSUE TITLE
accessibilityActivationPoint not taken account for

### ISSUE THREAD

**Issue by fabb** [appium/appium#8092]
## The problem

The `accessibilityActivationPoint` is ignored when clicking on an element.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): happens since ever
* Desktop OS/version used to run Appium: macOS Sierra
* Node.js version (unless using Appium.app|exe): not relevant
* Mobile platform/version under test: iOS 10.2 Simulator
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: both

## Details

Accessibility elements on iOS have the property [https://developer.apple.com/reference/objectivec/nsobject/1615179-accessibilityactivationpoint#](`accessibilityActivationPoint`) for the case a VoiceOver click should **not** happen to the center of an element, but rather offset. An example use case is a UIView containing a UILabel and a UISwitch. The UIView will be made an accessibility element in order to read out the text of the label, and to provide more click area for blind users. The `accessibilityActivationPoint` will be offset in order to correctly click the switch, even though it does not sit in the middle of the UIView. This works great for VoiceOver users.

Appium ignores the `accessibilityActivationPoint`, and rather always clicks in the middle of an element. So for cases like the above mentioned, the switch will **not** be triggered when clicking the UIView via Appium.

As the UIView is an accessibility element, its subviews are **not** exposed to Appium as it seems. For Calabash we had the workaround to find a subview of type `UISwitch` and click that, but Appium does not see any subviews.

=> So we need Appium to correctly use the `accessibilityActivationPoint` when clicking elements.

**Comment by dpgraham** [comment]
Thanks for opening this issue @fabb. I've never actually heard of this property before and it certainly would be a useful enhancement for our xcui driver. We could probably put this on our feature backlog but we do also take pull requests.

**Comment by fabb** [comment]
Phew, I would not know where to start, maybe when I have some more time on my hands.

**Comment by fabb** [comment]
I guess the issue lies in WebDriverAgent in this method?
https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement%2BFBTap.m#L22

**Comment by dpgraham** [comment]
Yeah, this is something that would have to be updated in WebDriverAgent.

**Comment by fabb** [comment]
Issue was fixed in WebDriverAgent: https://github.com/facebook/WebDriverAgent/issues/545

**Comment by dpgraham** [comment]
Nice!
