### ISSUE TITLE
Unable to locate element

### ISSUE THREAD

**Issue by chaithram123** [appium/appium#8095]
Hi,

```java
public class Desiredcapabilities 
{
	@Test
	public void test() throws MalformedURLException 
	{
		File appDir = new File("src");
		File app = new File(appDir, "BookMyShow.apk");
	   DesiredCapabilities cap = new DesiredCapabilities();	
	   cap.setCapability(MobileCapabilityType.PLATFORM_NAME, MobilePlatform.ANDROID);
	   cap.setCapability(MobileCapabilityType.DEVICE_NAME, "HT4B6JT02320");
	   cap.setCapability(CapabilityType.VERSION, "5.1.1");
	   cap.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
	   AndroidDriver driver =  new AndroidDriver(new URL("http://127.0.0.1:4723/wd/hub"),cap);
	   cap.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, "1500");
	   driver.findElementById("com.bt.bms:id/language_card_view").click();
	   System.out.println("Success");
	}
}
```
Used above to click "Let's Get started" option in Nexus 9 running on 5.1.1 build. Able to launch the app in device, but fails to click the option

Below is the log from Appium
```
info: [debug] Pushing command to appium work queue: ["find",{"strategy":"id","selector":"com.bt.bms:id/language_card_view","context":"","multiple":false}]
> info: [debug] [BOOTSTRAP] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"id","selector":"com.bt.bms:id/language_card_view","context":"","multiple":false}}
> info: [debug] [BOOTSTRAP] [debug] Got command of type ACTION
> info: [debug] [BOOTSTRAP] [debug] Got command action: find
> info: [debug] [BOOTSTRAP] [debug] Finding com.bt.bms:id/language_card_view using ID with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.bt.bms:id/language_card_view]
> info: [debug] [BOOTSTRAP] [debug] Failed to locate element. Clearing Accessibility cache and retrying.
> info: [debug] [BOOTSTRAP] [debug] Finding com.bt.bms:id/language_card_view using ID with the contextId:  multiple: false
> info: [debug] [BOOTSTRAP] [debug] Using: UiSelector[INSTANCE=0, RESOURCE_ID=com.bt.bms:id/language_card_view]
> info: [debug] [BOOTSTRAP] [debug] Returning result: {"status":7,"value":"No element found"}
```
Please help me to solve the issue

**Comment by imurchie** [comment]
Is the element available? You can print out the source to see what is there. Also you can play around with the implicit wait so it can have more time.

**Comment by vjmaiky** [comment]
For sure he needs to put a fluen wait;
Try somthing like this:

    public void clickOn(By element) {
        waithelper.waitForElementVIsibility(element);
        getDriver().findElement(element).click();
    }

**Comment by hustlerism** [comment]
Im having the same issue using node tested on Nexus5x (Android v7.1.2). The element id exists in uiautomatorviewer but appium could'nt find the element and returns error:

> Error: [elementById("username")] Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters. Selenium error: An element could not be located on the page using the given search parameters.

Ive set the implicit wait:

> return driver
      .init(desired)
      .setImplicitWaitTimeout(15000);

and thread sleep before finding the element:

>  it("Login", function () {
    return driver
      .sleep(15000)
      .elementById('username')
