### ISSUE TITLE
automationName XCUITest not part of Appium,Selendroid,WebDriverAgent

### ISSUE THREAD

**Issue by UserAutomation** [appium/appium#8096]
I am unable to get appium start working. Using a real device iphone 5.
Went to the xcode Project added Team ID 
installed libimobiledevice
installed ios deploy

But i am Getting this error of XCUITest is not part of Appium. Searched everywhere but couldn't find appropriate solution  

[HTTP] <-- GET /wd/hub/status 200 14 ms - 83 
[HTTP] --> GET /wd/hub/sessions {}
[MJSONWP] Calling AppiumDriver.getSessions() with args: []
[MJSONWP] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 200 3 ms - 40 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformName":"iOS","newCommandTimeout":"7200","app":"/Users/tvs00023/Desktop/TVSMILES.ipa","platformVersion":"8.3","udid":"34fdaad05eebafbec529faf9f144dd9b9e5788","deviceName":"iPhone 5","automationName":"Appium"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","new...
[Appium] Creating new IosDriver session
[Appium] Capabilities:

[Appium]   platformName: 'iOS'
[Appium]   newCommandTimeout: '7200'
[Appium]   app: '/Users/tvs00023/Desktop/TVSMILES.ipa'
[Appium]   platformVersion: '8.3'
[Appium]   udid: '34fdaad05eebafbec529faf9f144dd9b9e5788'
[Appium]   deviceName: 'iPhone 5'
[Appium]   automationName: 'Appium'
[Appium]   launchTimeout: 7200

[Appium]   fullReset: true
[Appium]   showIOSLog: true
[BaseDriver] Capability 'newCommandTimeout' changed from string ('7200') to integer (7200). This may cause unexpected behavior
[BaseDriver] Session created with session id: 35a5c511-690e-406c-8aad-c38e2e8babde
[debug] [iOS] Not auto-detecting udid.
[BaseDriver] Using local app '/Users/tvs00023/Desktop/TVSMILES.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir

[debug] [BaseDriver] Unzipping /var/folders/03/cf3bj85550s0xnpm1y7vnqt80000gn/T/2017224-82369-3y7pmr/appium-app.zip

[debug] [BaseDriver] Testing zip archive: /var/folders/03/cf3bj85550s0xnpm1y7vnqt80000gn/T/2017224-82369-3y7pmr/appium-app.zip

[BaseDriver] Unzipped local app to '/var/folders/03/cf3bj85550s0xnpm1y7vnqt80000gn/T/2017224-82369-3y7pmr/Payload/DE Debug.app'

[debug] [iOS] Removing any remaining instruments sockets

[debug] [iOS] Cleaned up instruments socket /var/folders/03/cf3bj85550s0xnpm1y7vnqt80000gn/T/instruments_sock
[debug] [iOS] No language specified. Using default strings
[debug] [iOS] Strings file not found. Looking in 'en.lproj' directory
[iOS] Could not file localizable strings file 'Localizable.strings'!
[debug] [ios-app-utils] Getting bundle ID from app
[iOS] Extracted bundleID: de.tvsmiles.tvsmiles-dev from app: /var/folders/03/cf3bj85550s0xnpm1y7vnqt80000gn/T/2017224-82369-3y7pmr/Payload/DE Debug.app
[debug] [iOS] Creating instruments
[debug] [UIAuto] Preparing bootstrap code
[debug] [UIAuto] Dynamic bootstrap dir: /Users/tvs00023/Library/Application Support/appium/bootstrap
[debug] [UIAuto] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js","instrumentsSock":"/var/folders/03/cf3bj85550s0xnpm1y7vnqt80000gn/T/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}

[debug] [UIAuto] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...

[debug] [UIAuto] Dynamic bootstrap path: /Users/tvs00023/Library/Application Support/appium/bootstrap/bootstrap-624df5447b43b034.js

[debug] [UIAuto] Reusing dynamic bootstrap: /Users/tvs00023/Library/Application Support/appium/bootstrap/bootstrap-624df5447b43b034.js
[debug] [iOS] Running ios real device reset flow
[debug] [iOS] Full reset requested. Will try to uninstall the app 'de.tvsmiles.tvsmiles-dev'.
[debug] [iOS] Creating iDevice object with udid 34fdaad05eebafbec529faf9f144dd9b9e5788

[iOS] Could not remove 'de.tvsmiles.tvsmiles-dev' from device

[MJSONWP] Encountered internal error running command: Error: Command failed: ideviceinstaller -u 34fdaad05eebafbec529faf9f144dd9b9e5788 -U de.tvsmiles.tvsmiles-dev

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

[HTTP] <-- POST /wd/hub/session 500 4285 ms - 241 
## Environment

* Appium version : 1.5.3
* mac OS X 10.12.3
* Mobile platform: iphone 5 Real Device
*XCode : 8.3

Here is my DesiredCapabilites Code:
import io.appium.java_client.AppiumDriver;

import io.appium.java_client.ios.IOSDriver;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.remote.DesiredCapabilities;

public class AppiumTest {
	
	public static AppiumDriver driver;
	
	
	public static void main (String[] args) throws MalformedURLException, InterruptedException{
		
	DesiredCapabilities capabilities = new DesiredCapabilities();
	capabilities.setCapability("deviceName", "iphone 5");	
	capabilities.setCapability("platformName", "iOS");
	capabilities.setCapability("platformVersion", "10.3");
	
	capabilities.setCapability("automationName", "XCUITest");
	
	capabilities.setCapability("app", "DE Debug");
	
	driver = new IOSDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);
	driver.manage().timeouts().implicitlyWait(80, TimeUnit.SECONDS );
	}
	
	
}

**Comment by imurchie** [comment]
The XCUITest integration only came in in Appium 1.6.0. Upgrade if you want it.

```
npm uninstall -g appium && npm install -g appium@beta
```

**Comment by UserAutomation** [comment]
I did upgrade but upgrade is only possible in terminal. The version of Appium is still old one in mac. 
How can i run a new version of appium on mac after upgrading it through command line?

**Comment by imurchie** [comment]
Do you mean the GUI? There is an updated graphical user interface: https://github.com/appium/appium-desktop/releases
