### ISSUE TITLE
Unable to concatenate moveTo actions for Appium::TouchAction

### ISSUE THREAD

**Issue by JoelWhitney** [appium/appium#8097]
## The problem

I'm trying to implement a ui test for a feature in my app that allows users to draw on the screen. I want simulate this by drawing circle, square, blob, etc. Once you pick up your finger the geometry is complete.

I tried to chain moveTo actions (see below) and then call myAction.release.perform, but it looks like the gesture is not implemented/supported. It was suggested via Gitter that this is a bug. Please advise.

```
pry(main)> Appium::TouchAction.new.press(x:100,y:100).move_to(x:20,y:20).move_to(x:20,y:20).release.perform
Selenium::WebDriver::Error::UnknownError: Support for this gesture is not yet implemented. Please contact an Appium dev
```

Note: Another user on Gitter attempted using multi-touch action, such as `MultiAction().add(action0).add(action1).perform()`, with the same result

## Environment

* Appium version (or git revision) that exhibits the issue: **Appium v1.6.4-beta**
* Desktop OS/version used to run Appium: **MacOS Sierra (10.12.3)**
* Mobile platform/version under test: **iOS 10.2**
* Real device or emulator/simulator: **Simulator**
* Appium CLI or Appium.app|exe: **Appium.app**

## Link to Appium logs

https://gist.github.com/JoelWhitney/2661a1ef7981d6f4cb4873810e0e993c

## Code To Reproduce Issue

```
Appium::TouchAction.new.press(x:100,y:100).move_to(x:20,y:20).move_to(x:20,y:20).release.perform
```

**Comment by mykola-mokhnach** [comment]
Yes, unfortunately, the current approach won't work with XCTest. Think about splitting it into a chain of separate swipe actions.

**Comment by JoelWhitney** [comment]
Thanks for the response @mykola-mokhnach. 

I'm not sure chaining swipe actions will capture the interaction I need. In my case, I imagine each swipe will effectively create a new line geometry in my app. I need to be able to interact with the screen without "picking up the finger". 

I attempted chaining swipes to see how it behaved and received the the following error:

```
[9] pry(main)> Appium::TouchAction.new.swipe(start_x: 100, start_y: 100, delta_x: 10, delta_y: 10, duration: 10).swipe(start_x:100, start_y:100, delta_x:30, delta_y:30).perform
Selenium::WebDriver::Error::UnknownError: Support for this gesture is not yet implemented. Please contact an Appium dev
```

**Comment by mykola-mokhnach** [comment]
XCTest does not provide any public methods "to interact with the screen without picking up the finger", so we cannot implement this in Appium. Please create a request to Apple to add such.
