### ISSUE TITLE
iOS 10, XCUITest, WebView, Cordova. Appium searching for incorrect element

### ISSUE THREAD

**Issue by fedorc** [appium/appium#8098]
## The problem

Appium doesn't search elements in webview
some id's and names was changed due to privacy

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta (and i use desktop appium v1.0.0-beta.4)
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3 (but ios version was 9.0)
* Desktop OS/version used to run Appium: macOS Sierra v10.12.3 (16D32)
* Node.js version (unless using Appium.app|exe): v7.4.0
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: real device iPad
* Appium CLI or Appium.app|exe: Appium.app

## Details

My app is hybrid and it built with Cordova. Appium can find WebView once i run ios_webkit_debug_proxy. After appium switch to WebView it trying to find XCUIElementTypeButton which i definitely don't try to interact with in my code.

## Link to Appium logs

https://gist.github.com/fedorc/50e8cf9a143d764bf379146982487bf8

## Link to inspector
https://gist.github.com/fedorc/4acb23edb29bae440e5f47f28247b4f8

## Link to source
https://gist.github.com/fedorc/e08ae75df7ec25be8ea708345be31191

## Code To Reproduce Issue [ Good To Have ]

https://gist.github.com/fedorc/b27dab19d28c80cb25e96bc222cdbbd7

**Comment by mykola-mokhnach** [comment]
Detecting alerts inside webviews is a non-trivial operation, since XCTest does not mark them explicitly. This makes the built-in detection algorithm not 100% reliable, because it tries to guess what is alert and what is not. I'd rather try to find and click elements form the webview UI tree directly instead of using _..Alert.._ calls

**Comment by fedorc** [comment]
Thank you @mykola-mokhnach, will check tomorrow

**Comment by fedorc** [comment]
@mykola-mokhnach, rechecked, i do not have any activities related to Alerts.

When i run form.UserNameInput.IsEnabled in appium log i see next:
[JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/88CB5799-14F1-4F77-AF65-5DEDA07FC686/elements] with body: {"using":"class name","value":"XCUIElementTypeScrollView"}
[JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"285BA053-7B27-4916-9196-808D07D6C97F","type":"XCUIElementTypeScrollView","label":null}],"sessionId":"88CB5799-14F1-4F77-AF65-5DEDA07FC686","status":0}
[BaseDriver] Waiting up to 100000 ms for condition
[JSONWP Proxy] Proxying [POST /element/285BA053-7B27-4916-9196-808D07D6C97F/elements] to [POST http://localhost:8100/session/88CB5799-14F1-4F77-AF65-5DEDA07FC686/element/285BA053-7B27-4916-9196-808D07D6C97F/elements] with body: {"using":"class name","value":"XCUIElementTypeButton"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"88CB5799-14F1-4F77-AF65-5DEDA07FC686","status":0}
[BaseDriver] Waited for 996 ms so far
[JSONWP Proxy] Proxying [POST /element/285BA053-7B27-4916-9196-808D07D6C97F/elements] to [POST http://localhost:8100/session/88CB5799-14F1-4F77-AF65-5DEDA07FC686/element/285BA053-7B27-4916-9196-808D07D6C97F/elements] with body: {"using":"class name","value":"XCUIElementTypeButton"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"88CB5799-14F1-4F77-AF65-5DEDA07FC686","status":0}
[BaseDriver] Waited for 4496 ms so far
[JSONWP Proxy] Proxying [POST /element/285BA053-7B27-4916-9196-808D07D6C97F/elements] to [POST http://localhost:8100/session/88CB5799-14F1-4F77-AF65-5DEDA07FC686/element/285BA053-7B27-4916-9196-808D07D6C97F/elements] with body: {"using":"class name","value":"XCUIElementTypeButton"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"88CB5799-14F1-4F77-AF65-5DEDA07FC686","status":0}
[BaseDriver] Waited for 11443 ms so far
[JSONWP Proxy] Proxying [POST /element/285BA053-7B27-4916-9196-808D07D6C97F/elements] to [POST http://localhost:8100/session/88CB5799-14F1-4F77-AF65-5DEDA07FC686/element/285BA053-7B27-4916-9196-808D07D6C97F/elements] with body: {"using":"class name","value":"XCUIElementTypeButton"}
[JSONWP Proxy] Got response with status 200: {"value":[],"sessionId":"88CB5799-14F1-4F77-AF65-5DEDA07FC686","status":0}
[HTTP] <-- GET /wd/hub/session/b3f187f5-966c-4a24-9816-fce354c32833/alert_text 500 112854 ms - 158 
[XCUITest] Connection to WDA timed out
[iProxy] recv failed: Operation not permitted

**Comment by mykola-mokhnach** [comment]
I see these lines in Appium log:
```
[MJSONWP] Calling AppiumDriver.setContext() with args: ["WEBVIEW_12","267304ff-3522-4a14-aec4-de7ddd614bcb"]
[XCUITest] Executing command 'setContext'
[iOS] Attempting to set context to 'WEBVIEW_12'
[RemoteDebugger] WebKit debugger web socket connected to url: ws://localhost:27753/devtools/page/12
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/267304ff-3522-4a14-aec4-de7ddd614bcb/context 200 11 ms - 76 
[HTTP] --> GET /wd/hub/session/267304ff-3522-4a14-aec4-de7ddd614bcb/alert_text {}
[MJSONWP] Calling AppiumDriver.getAlertText() with args: ["267304ff-3522-4a14-aec4-de7ddd614bcb"]
[XCUITest] Executing command 'getAlertText'
```

and say say somebody is calling _getAlertText_ text command - either explicitly or implicitly. May it be there's a bug in C# driver?

**Comment by fedorc** [comment]
Agree, something weird:

[MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["b3f187f5-966c-4a24-9816-fce354c32833"]
[XCUITest] Executing command 'getCurrentContext'
[MJSONWP] Responding to client with driver.getCurrentContext() result: "WEBVIEW_6"
[HTTP] <-- GET /wd/hub/session/b3f187f5-966c-4a24-9816-fce354c32833/context 200 2 ms - 83 
[HTTP] --> GET /wd/hub/session/b3f187f5-966c-4a24-9816-fce354c32833/alert_text {}
[MJSONWP] Calling AppiumDriver.getAlertText() with args: ["b3f187f5-966c-4a24-9816-fce354c32833"]
[XCUITest] Executing command 'getAlertText'
[BaseDriver] Waiting up to 100000 ms for condition
[JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8100/session/88CB5799-14F1-4F77-AF65-5DEDA07FC686/elements] with body: {"using":"class name","value":"XCUIElementTypeScrollView"}
[JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"285BA053-7B27-4916-9196-808D07D6C97F","type":"XCUIElementTypeScrollView","label":null}],"sessionId":"88CB5799-14F1-4F77-AF65-5DEDA07FC686","status":0}
[BaseDriver] Waiting up to 100000 ms for condition

**Comment by fedorc** [comment]
I think i found a place which triggers **[MJSONWP] Calling AppiumDriver.getAlertText() with args:**.

If you have set up ```appiumDriver.Manage().Timeouts().ImplicitlyWait``` it will trigger getAlertText() after each iteration.

**Comment by mykola-mokhnach** [comment]
Can you check whether this is called elsewhere in C# driver?

**Comment by fedorc** [comment]
I found a problem, in our framework we using separate thread wich checking for alerts and auto accepting it. 
Checked on code without our wrappers, and its working correct.

**Comment by mykola-mokhnach** [comment]
> I found a problem, in our framework we using separate thread wich checking for alerts and auto accepting it.

I wouldn't say this is a good idea, since XCTest is strictly single-threaded, which means all the UI commands will block each other even if executed from parallel threads.

**Comment by fedorc** [comment]
I found one more thing about alerts

When you Invoking action, AppiumDriver call getAlertText() method, and after that appium try to find element and make given action

https://gist.github.com/fedorc/a5162e2259a6075e23725f502df2f28b
