### ISSUE TITLE
Appium server is waiting for the server to respond and goes in infinite loop

### ISSUE THREAD

**Issue by ektayadav029** [appium/appium#8101]
## The problem

When I tap on 'Launch' in Appium app ,below mentioned error displays.
On tapping Appium doctor it says 'Everything looks good!'.But still I am getting the error.

## Environment

* Appium version (or git revision) that exhibits the issue: Mac
* Last Appium version that did not exhibit the issue (if applicable):1.5.3
* Desktop OS/version used to run Appium:10.12.3
* Node.js version (unless using Appium.app|exe):7.4
* Mobile platform/version under test:android
* Real device or emulator/simulator: emulator

## Details

When I tap on 'Launch' in Appium,below mentioned error displays.
On tapping Appium doctor says 'Everything looks good!'.But still I am getting the error.
I have tried it with multiple server numbers but no luck.

## Link to Appium logs

Launching Appium with command: '/Applications/Appium.app/Contents/Resources/node/bin/node' appium/build/lib/main.js --address "127.0.0.1" --callback-address "127.0.0.1" --callback-port "4723" --session-override --debug-log-spacing --log-level "debug" --automation-name "Appium" --platform-name "Android" --platform-version "4.4"

[Appium] Welcome to Appium v1.5.3

[Appium] Non-default server args:

[Appium] address: '127.0.0.1'

[Appium] callbackAddress: '127.0.0.1'
[Appium] callbackPort: 4723
[Appium] sessionOverride: true
[Appium] debugLogSpacing: true
[Appium] platformName: 'Android'
[Appium] platformVersion: '4.4'
[Appium] automationName: 'Appium'
[Appium] Deprecated server args:

[Appium] --platform-name => --default-capabilities '{"platformName":"Android"}'
[Appium] --platform-version => --default-capabilities '{"platformVersion":"4.4"}'
[Appium] --automation-name => --default-capabilities '{"automationName":"Appium"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:

[Appium] platformName: 'Android'
[Appium] platformVersion: '4.4'
[Appium] automationName: 'Appium'
[Appium] Appium REST http interface listener started on 127.0.0.1:4723
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 35 ms - 83
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 14 ms - 83
[HTTP] --> GET /wd/hub/status {}
[MJSONWP] Calling AppiumDriver.getStatus() with args: []
[MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.5.3"...
[HTTP] <-- GET /wd/hub/status 200 12 ms - 83

**Comment by mykola-mokhnach** [comment]
Please use https://github.com/appium/appium-desktop/releases. The old inspector is not supported anymore.
