### ISSUE TITLE
Can't locate android.support.v7.app.ActionBar.Tab

### ISSUE THREAD

**Issue by mstrelex** [appium/appium#8102]
## The problem

Using UIAutomator2 can't locate android.support.v7.app.ActionBar.Tab usign XPath, Appium always complains that element doesn't exist. Although using UIAutomator (first version) everything works fine. This is probably because the class name of the widget is android.support.v7.app.ActionBar$Tab, but $ (dollar) sign is not acceptable as valid XPath. 

Anything that can be done on this matter ? (Beside using a different locator strategy) ? 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3

**Comment by mykola-mokhnach** [comment]
What is the output of _getPageSource_ method?

**Comment by mstrelex** [comment]
Here's an example: https://gist.github.com/mstrelex/03dbfe61b51f0837548bfd6030651885
it converts the $ sign node names to a dot (.) and leaves the $ sign only in class attribute.

**Comment by mykola-mokhnach** [comment]
So what is the problem to find it by class attribute?

```
//*[@class='android.support.v7.app.ActionBar$Tab']
```

**Comment by mstrelex** [comment]
There are other elements with this value in their attribute class....
I rely on elements hierarchy, therefore I use Xpath using indexes. 

There is nothing wrong with my Xpath, but Appium claims there is not element that can be found using the Xpath.

**Comment by mykola-mokhnach** [comment]
It is only possible to use xpath queries, which are supported in the document generated by _getPageSource_ method. Appium works as designed in this case.

**Comment by mstrelex** [comment]
The XML example I showed in GIST is getPageSource output. Using XPath I can locate any other element but ```android.support.v7.app.ActionBar.Tab``` and I assume it's because the original output of the UIAutoamtor had $ in it's node name: ```android.support.v7.app.ActionBar$Tab```

**Comment by mykola-mokhnach** [comment]
Yep, there might be a problem that at some level "reverse" node name transformation is not performed properly, but I wouldn't care much, since with xpath one can easily workaround it by using either _class_ attribute value or name()/local-name() functions.

**Comment by mstrelex** [comment]
So you are saying that I should change my XPath to look like:

`//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.widget.LinearLayout[1]/android.widget.HorizontalScrollView[1]/android.widget.LinearLayout[1]/*[@class = 'android.support.v7.app.ActionBar$Tab'][2]/android.widget.ImageView[1]`

**Comment by mykola-mokhnach** [comment]
Yes you can try it.
Another option:

```
/android.widget.LinearLayout[1]/*[starts-with(local-name(), 'android.support.v7.app.ActionBar')][2]/android.widget.ImageView[1]
``` 

Although, IMHO absolute xpaths are easy breakable and hard to support. I'd never use such in my automation.

**Comment by mstrelex** [comment]
I totally agree with you that XPath is definitely not a generic approach and I wouldn't use them if there would be other choice :) Many thanks.

**Comment by srilakshmi211** [comment]
I am facing the same problem. Could you please let me know a work around?
I am uisng this: @AndroidFindBy(xpath="//*[@class='android.support.v7.app.ActionBar$Tab'][@index=0]") but says no such element. I am blocked with this.

**Comment by ashu123mae** [comment]
The issue can be resolved by performing Click on on class "android.support.v7.app.ActionBar$Tab"
use :  @AndroidFindBy(xpath="//android.widget.TextView[@text='Discover']")

**Comment by rkn411** [comment]
> I am facing the same problem. Could you please let me know a work around?
> I am uisng this: @AndroidFindBy(xpath="//*[@**C**### should replace with small"class='android.support.v7.app.ActionBar$Tab'][@index=0]") but says no such element. I am blocked with this. @srilakshmi211
