### ISSUE TITLE
Appium installation failed with error in ChromeDriver update

### ISSUE THREAD

**Issue by Kalyan1989** [appium/appium#8103]
## The problem:
Appium installation failed with error in ChromeDriver update
The root cause might be the expected ChromeDriver 2.28 is not available on DevOps portal.
How can manually change the driver version in such cases?

## Environment
* Appium version (or git revision) that exhibits the issue: Performing first setup (Appium 1.4.16 is installed via windows direct exe installation)
* Last Appium version that did not exhibit the issue (if applicable): NA
* Desktop OS/version used to run Appium: Win7 64Bit
* Node.js version (unless using Appium.app|exe): 4.4.4
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real device

## Details

[2017-03-27T09_02_34_284Z-debug.txt](https://github.com/appium/appium/files/871918/2017-03-27T09_02_34_284Z-debug.txt)
![appiumerror2](https://cloud.githubusercontent.com/assets/26275148/24349010/5380ccfe-12fb-11e7-9859-f9477f6c1984.png)
![startandr](https://cloud.githubusercontent.com/assets/26275148/24349014/5a4a0c9e-12fb-11e7-9e76-ee8b33fc0ad4.png)

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by dpgraham** [comment]
Hi @Kalyan1989, that GUI isn't supported any more. We have a new GUI tool that you can download at: https://github.com/appium/appium-desktop/releases/latest.
