### ISSUE TITLE
Appium-uiAutomator is working fine for android but not iOS

### ISSUE THREAD

**Issue by RonitJoardar** [appium/appium#8104]
## Environment

Appium version - 1.6.4 beta(Appium Desktop)
Desktop OS/version used to run Appium: ASX 10.12 Sierra
Mobile platform/version under test: 10.2
Real device or emulator/simulator: Real device iPAD Air 2

## Details

I am trying to scroll to an element using the following code:

@AndroidFindBy(uiAutomator="new UiScrollable(new UiSelector()).scrollIntoView(" + "new UiSelector().text(\"Contacts\"));") @iOSFindBy(uiAutomator="new UiScrollable(new UiSelector()).scrollIntoView(" + "new UiSelector().text(\"Contacts\"));") public MobileElement orgContact;

This works perfectly in Android but on iOS I get the following error: org.openqa.selenium.NoSuchElementException: Can't locate an element by this strategy: Locator map: - native content: "By.IosUIAutomation: new UiScrollable(new UiSelector()).scrollIntoView(new UiSelector().text("Contacts"));"

I have also tried to scroll using: public void verticalScroll(AppiumDriver driver) {

this.driver=driver;
dimensions = driver.manage().window().getSize();
Double screenHeightStart = dimensions.getHeight() * 0.5;
int scrollStart = screenHeightStart.intValue();
System.out.println("s="+scrollStart);
Double screenHeightEnd = dimensions.getHeight() * 0.2;
int scrollEnd = screenHeightEnd.intValue();
driver.swipe(0,scrollStart,0,scrollEnd,5000);
} But it also does not work. Can anyone please suggest what am I doing wrong here

**Comment by mykola-mokhnach** [comment]
Apple has dropped UIAutomation support in iOS 10.0. You need to upgrade your automation to use XCTest. Read https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md for more details.

**Comment by RonitJoardar** [comment]
Thank you for the input. Any idea for the swipe method is not working?

**Comment by vikramvi** [comment]
@RonitJoardar Please search with **swipe** term under issues, you will find the solution
