### ISSUE TITLE
Appium is unable to turn screen back on for LG G5

### ISSUE THREAD

**Issue by oldstone** [appium/appium#8108]
## The problem

I have a Samsung S7 and an LG G5 (both Android 6.0.1) that I use for Appium tests. Both devices have screen lock disabled. Now I'm having an issue on the G5 where after its screen is turned off (after idle for 10 minutes), Appium is unable to turn the screen back on, and the test will then fail due to a screen unlock error ([https://gist.github.com/oldstone/99a69aa456bfc442adb716d8f34a24ba](https://gist.github.com/oldstone/99a69aa456bfc442adb716d8f34a24ba))
The S7 doesn't have this issue(info: [AndroidDriver] Screen already unlocked, doing nothing), and for some specific requirements keep screen always on is not an option for us.
I also tried ADB command that wakes up the screen 'adb shell input keyevent 224' before the test execution, but it also doesn't help.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3
* Desktop OS/version used to run Appium: CentOS 64-bit
* Node.js version (unless using Appium.app|exe): 6.7.0
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: Real device (AT&T)
* Appium CLI or Appium.app|exe:
java-client 4.1.2
chromedriver 2.28

## Link to Appium logs
GIST log [https://gist.github.com/oldstone/99a69aa456bfc442adb716d8f34a24ba](https://gist.github.com/oldstone/99a69aa456bfc442adb716d8f34a24ba)

**Comment by mykola-mokhnach** [comment]
Please try Appium 1.6.4 with [updated unlock](https://github.com/appium/appium-android-driver/blob/master/docs/UNLOCK.md)

**Comment by oldstone** [comment]
I thought about it, but my devices both have **screen lock disabled**, is Appium 1.6.4's updated unlock going to help? Isn't it just going to fall back to the default unlock apk if no specific capability is given?

**Comment by mykola-mokhnach** [comment]
It does, but you can, at least, have a workaround

**Comment by mykola-mokhnach** [comment]
The other option might be that you push a PR with fixed unlock

**Comment by oldstone** [comment]
Okay, so you suggested that I should have the screen locked and then use Appium 1.6.4's updated unlock?

**Comment by JaniJegoroff** [comment]
Do you have `Stay awake` enabled from `Developer options` in device?

**Comment by oldstone** [comment]
Unfortunately, 'Stay awake' is not an option for us as we're told that
it'll cause a burn-in.

**Comment by jlipps** [comment]
@oldstone did you try latest with one of the new unlock methods?

**Comment by oldstone** [comment]
Not yet. I'm waiting for Java-client to include the new unlock method. Should I create a feature request?
