### ISSUE TITLE
Android Nougat Compatability

### ISSUE THREAD

**Issue by WoodPlank** [appium/appium#8109]
## The problem

I'm not able to use my physical device (Android 7.0 Nougat) with Appium. I can run earlier versions of Android without any issues (API levels for 5.0 and 6.0).

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 6.9.2
* Mobile platform/version under test: 7.0
* Real device or emulator/simulator: Real device

## Details

Every time I run a physical device using 7.0 Nougat it never loads but when I use Android API levels for 5.0 and 6.0 then Appium works. I'm not sure what the problem is but I've looked around without any success. Any and all help is very much appreciated.

## Link to Appium logs

[gist for logs](https://gist.github.com/WoodPlank/2051cb22614f97d0e90c6de7224f5bf1)

## Code To Reproduce Issue [ Good To Have ]

Gist to my capabilities: [gist for capabilities](https://gist.github.com/WoodPlank/c52bcc24cf1096ed874bd775f4732307)

**Comment by mykola-mokhnach** [comment]
There's only one suggestion to switch to UIAutomator2 backend.

**Comment by WoodPlank** [comment]
@mykola-mokhnach I actually did have 7.0 Nougat working with Appium a few weeks ago. I may have to look into UIAutomator2 to get something working. I don't know what changed or what I've done to have it stop working.

**Comment by mykola-mokhnach** [comment]
You may just remove Appium settings app from your phone to fix the error you have now, but UIAutomation1 will anyway stop working sooner or later.

**Comment by WoodPlank** [comment]
@mykola-mokhnach Actually, this did not work initially. After I removed the "Appium Settings" and "Unlock" apps then it did work. Thanks so much for your help! I will close this issue
