### ISSUE TITLE
Error An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by lionel-pushios** [appium/appium#8110]
I know this error has something to do with Xcode signing provisions, and I have followed these steps:

Goto /usr/local/lib/node_modules/app-inspector/node_modules -> webdriveragent -> WebDriverAgent -> WebDriverAgent.xcodeproj
changed team to your apple developer account team name for all under TARGETS
Installed WebDriverAgent through xcode on the test device.

However, once I tried running Appium again, I got the same error message.

I blurred out some fields just for security.

![screen shot 2017-03-27 at 6 25 48 pm](https://cloud.githubusercontent.com/assets/24396183/24381057/682dc2b2-131c-11e7-91af-cbdd1384b69b.png)

**Comment by mykola-mokhnach** [comment]
It is not possible to help without having Appium and xcodebuild logs.Also make sure you carefully follow [these](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md) steps to set up real device automation

**Comment by lionel-pushios** [comment]
Thanks for your quick response. I left off the xcodeOrgId and the xcodeSigningId. It works now. Thanks.

**Comment by mmguhe** [comment]
Hi,
I am getting similar issue in my project. I followed the Full Manual Configuration from the link provided.
1.Do I need to setup the webdriveragent project separate from my project?
2. I added the bundle identifier for my project under the build settings for WebDriverAgent but still I don't see the 'Provisioning Profile' getting updated.

**Comment by skumar1122** [comment]
Hello All, 

I am getting same error today , everything was working until I have updated XCUITest , WDA and New XCODE 8.2.1.
WDA: I did followed manual config and I had no issues setting up provisional profile but I  am seeing new error as mentioned in screenshot. did anyone see this error in XCODE?
<img width="1277" alt="screen shot 2017-03-28 at 22 06 17" src="https://cloud.githubusercontent.com/assets/20112173/24427629/98e0d682-1403-11e7-91ca-508105d17e76.png">


Used:
Appium latest Beta
Xcode 8.2
iOS10.2
iPhone6 and iPhone7 

Appium Logs:
> skumar$ appium -U 47b562c6a454e596df5583e1ff6743afe785de45 --webkit-debug-proxy-port 27753
> [Appium] Welcome to Appium v1.6.4-beta
> [Appium] Non-default server args:
> [Appium]   udid: '47b562c6a454e596df5583e1ff6743afe785de45'
> [Appium] Deprecated server args:
> [Appium]   -U,--udid => --default-capabilities '{"udid":"47b562c6a454e596df5583e1ff6743afe785de45"}'
> [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
> [Appium]   udid: '47b562c6a454e596df5583e1ff6743afe785de45'
> [HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
> Error: listen EADDRINUSE 0.0.0.0:4723
>     at Object.exports._errnoException (util.js:1012:11)
>     at exports._exceptionWithHostPort (util.js:1035:20)
>     at Server._listen2 (net.js:1252:14)
>     at listen (net.js:1288:10)
>     at net.js:1398:9
>     at _combinedTickCallback (internal/process/next_tick.js:77:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
> WHM5003604:~ skumar$ appium -U 47b562c6a454e596df5583e1ff6743afe785de45 --webkit-debug-proxy-port 27753
> [Appium] Welcome to Appium v1.6.4-beta
> [Appium] Non-default server args:
> [Appium]   udid: '47b562c6a454e596df5583e1ff6743afe785de45'
> [Appium] Deprecated server args:
> [Appium]   -U,--udid => --default-capabilities '{"udid":"47b562c6a454e596df5583e1ff6743afe785de45"}'
> [Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
> [Appium]   udid: '47b562c6a454e596df5583e1ff6743afe785de45'
> [Appium] Appium REST http interface listener started on 0.0.0.0:4723
> [HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"platformVersion":"10.2","browserName":"Safari","platformName":"iOS","version":"","deviceName":"47b562c6a454e596df5583e1ff6743afe785de45","platform":"MAC"},"requiredCapabilities":{}},"desiredCapabilities":{"platformVersion":"10.2","browserName":"Safari","platformName":"iOS","version":"","deviceName":"47b562c6a454e596df5583e1ff6743afe785de45","platform":"MAC"},"requiredCapabilities":{}}
> [debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"platformVersion":"10.2","browserName":"Safari","platformName":"iOS","version":"","deviceName":"47b562c6a454e596df5583e1ff6743afe785de45","platform":"MAC"},{},{"desiredCapabilities":{"platformVersion":"10.2","browserName":"Safari","platformName":"iOS","version":"","deviceName":"47b562c6a454e596df5583e1ff6743afe785de45","platform":"MAC"},"requiredCapabilities":{}},null,null]
> [debug] [BaseDriver] Event 'newSessionRequested' logged at 1490734837039 (22:00:37 GMT+0100 (BST))
> [Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
> [Appium] Creating new XCUITestDriver (v2.23.1) session
> [Appium] Capabilities:
> [Appium]   platformVersion: '10.2'
> [Appium]   browserName: 'Safari'
> [Appium]   platformName: 'iOS'
> [Appium]   version: ''
> [Appium]   deviceName: '47b562c6a454e596df5583e1ff6743afe785de45'
> [Appium]   platform: 'MAC'
> [Appium]   udid: '47b562c6a454e596df5583e1ff6743afe785de45'
> [debug] [XCUITest] XCUITestDriver version: 2.23.1
> [BaseDriver] The following capabilities were provided, but are not recognized by appium: version, platform.
> [BaseDriver] Session created with session id: 6c6ba7af-1ed6-49b3-a7f1-ea8974cb2663
> [debug] [XCUITest] Xcode version set to '8.2.1' (tools v7.3.1.0.1.1461711523)
> [debug] [XCUITest] iOS SDK Version set to '10.2'
> [debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1490734837300 (22:00:37 GMT+0100 (BST))
> [debug] [XCUITest] Available devices: 47b562c6a454e596df5583e1ff6743afe785de45
> [debug] [XCUITest] Creating iDevice object with udid '47b562c6a454e596df5583e1ff6743afe785de45'
> [XCUITest] Determining device to run tests on: udid: '47b562c6a454e596df5583e1ff6743afe785de45', real device: true
> [XCUITest] Safari test requested
> [debug] [BaseDriver] Event 'appConfigured' logged at 1490734837802 (22:00:37 GMT+0100 (BST))
> [debug] [BaseDriver] Event 'resetStarted' logged at 1490734837802 (22:00:37 GMT+0100 (BST))
> [debug] [XCUITest] Reset: running ios real device reset flow
> [debug] [BaseDriver] Event 'resetComplete' logged at 1490734837804 (22:00:37 GMT+0100 (BST))
> [debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
> [debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
> [debug] [BaseDriver] Event 'logCaptureStarted' logged at 1490734837969 (22:00:37 GMT+0100 (BST))
> [XCUITest] Setting up real device
> [debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1490734837972 (22:00:37 GMT+0100 (BST))
> [XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
> [XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
> [XCUITest] Launching WebDriverAgent on the device
> [debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
> [debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
> [debug] [XCUITest] Creating WebDriverAgent resources directory
> [debug] [XCUITest] Creating WebDriverAgent resource bundle directory
> [debug] [XCUITest] Killing hanging processes
> [debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=47b562c6a454e596df5583e1ff6743afe785de45 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
> [debug] [XCUITest] Output from xcodebuild will not be logged
> [debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
> [debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [XCUITest] Log file for xcodebuild test: /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/3CC8E5DE-FB51-4DF6-A309-661A175041B7/Session-WebDriverAgentRunner-2017-03-28_220051-5rhqbQ.log
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [Xcode] 2017-03-28 22:00:53.358 xcodebuild[35217:4873579] Error Domain=com.apple.dtdevicekit Code=-402620395 "App installation failed" UserInfo={NSLocalizedFailureReason=A valid provisioning profile for this executable was not found., com.apple.dtdevicekit.stacktrace=(
> [Xcode] 	0   DTDeviceKitBase                     0x0000000118b8137b DTDKCreateNSError + 113
> [Xcode] 	1   DTDeviceKitBase                     0x0000000118b81ab9 DTDK_AMDErrorToNSError + 791
> [Xcode] 	2   DTDeviceKitBase                     0x0000000118bc19df __90-[DTDKRemoteDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 158
> [Xcode] 	3   DVTFoundation                       0x000000010fbce989 DVTInvokeWithStrongOwnership + 75
> [Xcode] 	4   DTDeviceKitBase                     0x0000000118bc1725 -[DTDKRemoteDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1181
> [Xcode] 	5   IDEiOSSupportCore                   0x0000000118ab7e1f __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.336 + 4597
> [Xcode] 	6   DVTFoundation                       0x000000010fcf2cb7 __DVTDispatchAsync_block_invoke + 827
> [Xcode] 	7   libdispatch.dylib                   0x00007fff921b093d _dispatch_call_block_and_release + 12
> [Xcode] 	8   libdispatch.dylib                   0x00007fff921a540b _dispatch_client_callout + 8
> [Xcode] 	9   libdispatch.dylib                   0x00007fff921aa03b _dispatch_queue_drain + 754
> [Xcode] 	10  libdispatch.dylib                   0x00007fff921b0707 _dispatch_queue_invoke + 549
> [Xcode] 	11  libdispatch.dylib                   0x00007fff921a8d53 _dispatch_root_queue_drain + 538
> [Xcode] 	12  libdispatch.dylib                   0x00007fff921a8b00 _dispatch_worker_thread3 + 91
> [Xcode] 	13  libsystem_pthread.dylib             0x00007fff9c7b54de _pthread_wqthread + 1129
> [Xcode] 	14  libsystem_pthread.dylib             0x00007fff9c7b3341 start_wqthread + 13
> [Xcode] ), NSLocalizedRecoverySuggestion=A valid provisioning profile for this executable was not found., NSLocalizedDescription=App installation failed}
> [Xcode] 
> [Xcode] 2017-03-28 22:00:53.358 xcodebuild[35217:4873579] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
> [Xcode] 
> [Xcode] ** TEST EXECUTE FAILED **
> [Xcode] 
> [Xcode] 
> [XCUITest] xcodebuild exited with code '65' and signal 'null'
> [debug] [BaseDriver] Event 'wdaStartFailed' logged at 1490734853383 (22:00:53 GMT+0100 (BST))
> [debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
> [debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
> [XCUITest] Shutting down sub-processes
> [XCUITest] Shutting down iproxy process (pid 35216)
> [debug] [XCUITest] iproxy exited with code 'null'
> [debug] [XCUITest] Removing WDA application from device
> [debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1490734863500 (22:01:03 GMT+0100 (BST))
> [XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
> [XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
> [XCUITest] Launching WebDriverAgent on the device
> [debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
> [debug] [XCUITest] Killing hanging processes
> [debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=47b562c6a454e596df5583e1ff6743afe785de45 -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
> [debug] [XCUITest] Output from xcodebuild will not be logged
> [debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
> [debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [XCUITest] Log file for xcodebuild test: /Users/skumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/EE875431-03E5-4473-83EB-F814C7C4661F/Session-WebDriverAgentRunner-2017-03-28_220110-RO3rq0.log
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
> [Xcode] 2017-03-28 22:01:12.137 xcodebuild[35377:4874135] Error Domain=com.apple.dtdevicekit Code=-402620395 "App installation failed" UserInfo={NSLocalizedFailureReason=A valid provisioning profile for this executable was not found., com.apple.dtdevicekit.stacktrace=(
> [Xcode] 	0   DTDeviceKitBase                     0x0000000113ad337b DTDKCreateNSError + 113
> [Xcode] 	1   DTDeviceKitBase                     0x0000000113ad3ab9 DTDK_AMDErrorToNSError + 791
> [Xcode] 	2   DTDeviceKitBase                     0x0000000113b139df __90-[DTDKRemoteDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 158
> [Xcode] 	3   DVTFoundation                       0x000000010ab36989 DVTInvokeWithStrongOwnership + 75
> [Xcode] 	4   DTDeviceKitBase                     0x0000000113b13725 -[DTDKRemoteDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1181
> [Xcode] 	5   IDEiOSSupportCore                   0x0000000113a09e1f __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.336 + 4597
> [Xcode] 	6   DVTFoundation                       0x000000010ac5acb7 __DVTDispatchAsync_block_invoke + 827
> [Xcode] 	7   libdispatch.dylib                   0x00007fff921b093d _dispatch_call_block_and_release + 12
> [Xcode] 	8   libdispatch.dylib                   0x00007fff921a540b _dispatch_client_callout + 8
> [Xcode] 	9   libdispatch.dylib                   0x00007fff921aa03b _dispatch_queue_drain + 754
> [Xcode] 	10  libdispatch.dylib                   0x00007fff921b0707 _dispatch_queue_invoke + 549
> [Xcode] 	11  libdispatch.dylib                   0x00007fff921a8d53 _dispatch_root_queue_drain + 538
> [Xcode] 	12  libdispatch.dylib                   0x00007fff921a8b00 _dispatch_worker_thread3 + 91
> [Xcode] 	13  libsystem_pthread.dylib             0x00007fff9c7b54de _pthread_wqthread + 1129
> [Xcode] 	14  libsystem_pthread.dylib             0x00007fff9c7b3341 start_wqthread + 13
> [Xcode] ), NSLocalizedRecoverySuggestion=A valid provisioning profile for this executable was not found., NSLocalizedDescription=App installation failed}

Any suggestions ?

Thanks
SK
