### ISSUE TITLE
How to give tap with two fingers on a location? 

### ISSUE THREAD

**Issue by Sandarekha** [appium/appium#8111]
## The problem

org.openqa.selenium.WebDriverException: Support for this multi-action is not yet implemented. Please contact an Appium dev.

## Environment
Appium v1.6.4-beta
Xcode 8.2
macOs Sierra 10.12

## Details

I want to give a tap with two fingers on a location in order to test a guide in a drawing app. 
I have used it as, 

    driver.tap(2, 453, 368, 10);

But it gives issue as 

    org.openqa.selenium.WebDriverException: Support for this multi-action is not yet implemented. Please contact an Appium dev.

## Code To Reproduce Issue [ Good To Have ]
https://gist.github.com/Sandarekha/0342a0af00cd2b13f4f2338ea78355a0

**Comment by mykola-mokhnach** [comment]
Please update your beta once more to get the recent xcuitest driver and read https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md

**Comment by Sandarekha** [comment]
it does not work. I used it in java, 

    HashMap<String, String> tfTap = new HashMap<String, String>();
    tfTap.put("element","//XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[3]/XCUIElementTypeOther[1]/XCUIElementTypeImage[1]");
    	    driver.executeScript("mobile: twoFingerTap", tfTap);

When I execute it says 

    org.openqa.selenium.UnsupportedCommandException: Unknown command, all the mobile commands except scroll and swipe have been removed.
