### ISSUE TITLE
Bad Parameters Error using 5.0.0-BETA6 and Appium 1.6.3/1.6.4-beta

### ISSUE THREAD

**Issue by szaluk** [appium/appium#8118]
## The problem

I am getting the following error when I use the 5.0.0-BETA6 java client:

```
[Appium] Welcome to Appium v1.6.4-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/steven.zaluk/test/Digital Banking.app","appiumVersion":"1.6.4-beta","platformVersion":"10.2","automationName":"XCUITest","takesScreenshot":true,"autoWebview":true,"platformName":"iOS","deviceName":"iPhone 6"},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/steven.zaluk/test/Digital Banking.app","appiumVersion":"1.6.4-beta","platformVersion":"10.2","automationName":"XCUITest","takesScreenshot":true,"autoWebview":true,"platformName":"iOS","deviceName":"iPhone 6"},"requiredCapabilities":{}},"alwaysMatch":{"app":"/Users/steven.zaluk/test/Digital Banking.app","appiumVersion":"1.6.4-beta","platformVersion":"10.2","automationName":"XCUITest","takesScreenshot":true,"autoWebview":true,"platformName":"iOS","deviceName":"iPhone 6"},"firstMatch":[]}
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","capabilities","sessionId","id"]} and you sent ["desiredCapabilities","requiredCapabilities","capabilities","alwaysMatch","firstMatch"]
[HTTP] <-- POST /wd/hub/session 400
```

## Environment

* Appium version (or git revision) that exhibits the issue: Appium version 1.6.3 and 1.6.4-beta and 5.0.0-BETA6 of the Java client
* Last Appium version that did not exhibit the issue (if applicable): Works using the 4.1.2 version of the Java Client
* Desktop OS/version used to run Appium: Max OS X El Capitan (10.11.6)
* Node.js version (unless using Appium.app|exe): Node v7.7.4
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: iOS Simulator
* Appium CLI or Appium.app|exe: appium

## Details

I am getting a BadParametersError when using the 5.0.0-BETA6 version of the Java client but am not getting this error using the 4.1.2 version.  

## Link to Appium logs

https://gist.github.com/szaluk/eabe36aa5103978078c37fcf7968d7bc

## Code To Reproduce Issue [ Good To Have ]

This is how I am creating my XCUITest WebDriver instance:

```
    private WebDriver createiOSWebDriver() throws Exception {
        DesiredCapabilities desiredCapabilities = new DesiredCapabilities();

        desiredCapabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.6.4-beta");
        desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
        desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.2");
        desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
        desiredCapabilities.setCapability(MobileCapabilityType.APP, "/path/to/app");
        desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
        desiredCapabilities.setCapability(MobileCapabilityType.AUTO_WEBVIEW, true);
        desiredCapabilities.setCapability(CapabilityType.TAKES_SCREENSHOT, true);

        RemoteWebDriver remoteWebDriver = new RemoteWebDriver(new URL("http://url-to-appium-server"), desiredCapabilities);

        return remoteWebDriver;
    }
```

**Comment by SrinivasanTarget** [comment]
@szaluk  Can you please confirm whether it is only when you use ```RemoteWebDriver``` only not when you use ```IosDriver```?

**Comment by mykola-mokhnach** [comment]
Can you show your pom.xml?

**Comment by szaluk** [comment]
@mykola-mokhnach Here is my pom.xml -> https://gist.github.com/szaluk/c59a4cb7d3b95395ce60b7bcec067707

I will try with IosDriver and post back

**Comment by mykola-mokhnach** [comment]
Hm, can you make sure that your maven cache is clean and there are no leftovers from old libs?
Also, try put a breakpoint inside _doExecute_ method of _AppiumCommandExecutor_ class to make sure your client code uses the most recent version of this file (it should be the same as in https://github.com/appium/java-client/pull/597/files)

**Comment by szaluk** [comment]
@SrinivasanTarget - It does seem to work using IOSDriver.  I created the following tests:

```
    public void executeUsingRemoteWebDriver() {
        try {
            DesiredCapabilities desiredCapabilities = new DesiredCapabilities();

            desiredCapabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.6.4-beta");
            desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
            desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.2");
            desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
            desiredCapabilities.setCapability(MobileCapabilityType.APP, "/path/tp/app");
            desiredCapabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITest");
            desiredCapabilities.setCapability(MobileCapabilityType.AUTO_WEBVIEW, true);
            desiredCapabilities.setCapability(CapabilityType.TAKES_SCREENSHOT, true);

            WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4723/wd/hub"), desiredCapabilities);
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }

    public void executeUsingIOSDriver() {
        try {
            DesiredCapabilities desiredCapabilities = new DesiredCapabilities();

            desiredCapabilities.setCapability(MobileCapabilityType.APPIUM_VERSION, "1.6.4-beta");
            desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
            desiredCapabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.2");
            desiredCapabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6");
            desiredCapabilities.setCapability(MobileCapabilityType.APP, "/path/to/app");
            desiredCapabilities.setCapability(MobileCapabilityType.AUTO_WEBVIEW, true);
            desiredCapabilities.setCapability(CapabilityType.TAKES_SCREENSHOT, true);

            IOSDriver<WebElement> driver = new IOSDriver(new URL("http://localhost:4723/wd/hub"), desiredCapabilities);
        } catch(Exception ex) {
            ex.printStackTrace();
        }
    }
```

When I run the executeUsingIOSDriver() method, the simulator launches and there are no issues.  Wen I run the executeUsingRemoteWebDriver() method, I immediately get the error above.  

Is it better to use the IOSDriver?  Is the IOSDriver backed by XCUITest?

Thanks,
Steve

**Comment by mykola-mokhnach** [comment]
I'd say it is rather mandatory to use IOSDriver :)

**Comment by szaluk** [comment]
Ok.  I move to using IOSDriver and it's working now.  You can close this issue.

Thanks for the help!

**Comment by dhegdetech** [comment]
Hi,
  Have same issue 
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","sessionId","id"]} and you sent ["desiredCapabilities","requiredCapabilities","capabilities"]
"chromedriverExecutable":"/Users/deepa/Desktop/chromedriver","newCommandTimeout":"60","platformName":"Android","deviceName":"Android"},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Android"},"firstMatch":[]}}

Appium version (or git revision) that exhibits the issue: Appium version 1.6.3 and 1.6.5-beta and 5.0.0-BETA6 of the Java client.
