### ISSUE TITLE
runAppInBackground() restarts the app

### ISSUE THREAD

**Issue by mayureshshirodkar** [appium/appium#8122]
## The problem
On Android, when i do a runAppInBackground, it actually restarts the app instead of just bringing the app to the foreground.
The issue exists in the current build.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta.
* Last Appium version that did not exhibit the issue (if applicable): 1.4.13
* Desktop OS/version used to run Appium: Mac OSX 10.11.6
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator:Moto G4

## Details

runAppInBackground() method actually restarts the app (after the specified timeout), because it brings the app to foreground using adb -S, which "force stop the target app before starting the activity".

Reference to an old Pull request that din't work out:
https://github.com/appium/appium/pull/5315

## Link to Appium logs
[runAppInBackground.txt](https://github.com/appium/appium/files/878130/runAppInBackground.txt)

## Code To Reproduce Issue [ Good To Have ]

driver.runAppInBackground(4);

**Comment by mykola-mokhnach** [comment]
This works as designed. Set the capability **dontStopAppOnReset** to _true_ if you don't want the app to be restarted

**Comment by mayureshshirodkar** [comment]
Thanks @mykola-mokhnach  for looking into this.
I checked by setting the capability as dontStopAppOnReset to true, it worked fine.
