### ISSUE TITLE
Could not start a new session with iOS. Appium v1.6.4beta (Appium Desktop v1.0.0-beta.5)

### ISSUE THREAD

**Issue by louis57** [appium/appium#8123]
## The problem

I am using Appium v1.6.4beta (Appium Desktop v1.0.0-beta.5). It works fine with Android, but when I test iOS app, the app is not installed on device and I get this error message about ideviceinstaller, as the screenshot below with desired capabilities settings:

![screen shot 2017-03-28 at 10 49 53](https://cloud.githubusercontent.com/assets/12949146/24399662/bcd0663a-13ad-11e7-899e-59c220955816.png)

I am not sure if it is because this ipa file is not built with Developer Signature or if my desired capabilities settings missing something. So I try with another ipa file. I also add "bundleId" capability, and this time, the app is installed, but it keeps blinking (open and close real quick) and after few times, I get this message:

> Error: An unknown server-side error occurred while processing the command. Original error: We exceeded the number of retries allowed for instruments to successfully start; failing launch

Can someone help me with a solution? Much appreciated. Thanks

## Environment

* Appium version : v1.6.4beta (Appium Desktop v1.0.0-beta.5)
* Desktop OS/version used to run Appium: Mac OSX Sierra, Version 10.12.3
* Mobile platform/version under test: iPhone5, iOS v8.3

**Comment by mykola-mokhnach** [comment]
Do you follow the [tutorial](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md)?

**Comment by louis57** [comment]
Hi @mykola-mokhnach, I have a look at the tutorial, but unfortunately, I don't have a hold on source code. I receive only ipa file to test.

**Comment by mykola-mokhnach** [comment]
it won't work then if both the ipa and WDA sources are not signed properly

**Comment by mykola-mokhnach** [comment]
or you can use simulator for testing

**Comment by mykola-mokhnach** [comment]
Closed as not an issue
