### ISSUE TITLE
driver.tap fails with 'TypeError: 'int' object is not subscriptable'

### ISSUE THREAD

**Issue by joe-mcg** [appium/appium#8126]
## The problem

I'm attempting to use the driver.tap method in python. I'm passing in a tuple with the values (197,386) (which I've gotten from driver.find_element_by_name(elementName).location_in_view). When I try to run I get the following error:

```
self = <appium.webdriver.webdriver.WebDriver (session="40dcd08c-f0ae-455a-b6ee-c095ebad6911")>, positions = (197, 386), duration = None

    def tap(self, positions, duration=None):
        """Taps on an particular place with up to five fingers, holding for a
            certain time
    
            :Args:
             - positions - an array of tuples representing the x/y coordinates of
             the fingers to tap. Length can be up to five.
             - duration - (optional) length of time to tap, in ms
    
            :Usage:
                driver.tap([(100, 20), (100, 60), (100, 100)], 500)
            """
        if len(positions) == 1:
            action = TouchAction(self)
            x = positions[0][0]
            y = positions[0][1]
            if duration:
                action.long_press(x=x, y=y, duration=duration).release()
            else:
                action.tap(x=x, y=y)
            action.perform()
        else:
            ma = MultiAction(self)
            for position in positions:
>               x = position[0]
E               TypeError: 'int' object is not subscriptable

_env/lib/python3.6/site-packages/appium/webdriver/webdriver.py:230: TypeError
```

## Environment

* Appium 1.6.3
* Node.js version v6.5.0
* Using an iOS 10.2 simulator for testing

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/joe-mcg/a98db1895f028302d966cc06a9cfc027

**Comment by mykola-mokhnach** [comment]
This won't work in any case with XCTest, since support of touch actions is quite limited there. Update Appium to 1.6.4-beta and try _mobile: *_  methods from https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md

**Comment by imurchie** [comment]
In terms of the immediate error, pass in the tuple inside an array:
```python
loc = driver.find_element_by_name(elementName).location_in_view
driver.tap([loc])
```

**Comment by mykola-mokhnach** [comment]
And a nice exercise for Python geeks. What would be the output of such code:

```python
arr = [1, 2, 3] 
for item in arr:
    print(item[0]) 
```

**Comment by songzcn** [comment]
@mykola-mokhnach how can i perform a long press gesture in 1.6.4-beta.2?

**Comment by mykola-mokhnach** [comment]
@songzcn check the link from my comment above. Also make sure you have the most recent beta (reinstall will do the job)

**Comment by jlipps** [comment]
@mykola-mokhnach wouldn't that just result in an attribute error? are you just making the point that `positions` is a list of tuples?
