### ISSUE TITLE
Nougat Permissions

### ISSUE THREAD

**Issue by WoodPlank** [appium/appium#8127]
## The problem

I recently reported a bug where Appium wouldn't open apps on Android Nougat (7.0), which you can see [here](https://github.com/appium/appium/issues/8109) . Now that is resolved and Appium does open the app. The new issue is that the app does not remember any of the app permissions like it does on Android Marshmellow.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 6.9.2
* Mobile platform/version under test: Android 7.0
* Real device or emulator/simulator: Real device

## Details

App does not remember app permissions when opened by Appium. This still happens after I give the app the necessary permissions the next time it opens the app.

## Link to Appium logs

Link to [gist](https://gist.github.com/WoodPlank/6864735cc47dad8b93e192f554f2db3a)

## Code To Reproduce Issue [ Good To Have ]

Link to [gist](https://gist.github.com/WoodPlank/c52bcc24cf1096ed874bd775f4732307)

**Comment by mykola-mokhnach** [comment]
Probably, you just need to set **autoGrantPermissions** capability to _true_?

**Comment by WoodPlank** [comment]
@mykola-mokhnach That was in fact the issue. Thanks again! 👍

**Comment by amedvedjev** [comment]
also it is look like you start driver with RESET option.
