### ISSUE TITLE
iOS 10.3 setValue and sendKeys serverside error

### ISSUE THREAD

**Issue by pb-z** [appium/appium#8128]
## The problem

After update iPad to 10.3, when use **setValue** or **sendKeys** will stop the automation.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3 and 1.6.4Beta2
* Last Appium version that did not exhibit the issue (if applicable):1.6.3 with iOS 10.2
* Desktop OS/version used to run Appium: macOS Sierra
* Node.js version (unless using Appium.app|exe):v7.7.4
* Mobile platform/version under test:iOS 10.3
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI
## Details

> [debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"XCUIElementTypeTextField\",\n  \"sessionId\" : \"2BF4DBBA-3635-4665-8428-0D2E070B83CE\",\n  \"status\" : 0\n}"
[XCUITest] Cannot type in the text field because of UnknownError: An unknown server-side error occurred while processing the command. Original error: -[XCTestDriver managerProxy]: unrecognized selector sent to instance 0x174241d40

## Link to Appium logs
Appium Log is [here](https://gist.github.com/pb-z/ba700a000ad916bcd24cfd64db545fef)

**Comment by djyarber** [comment]
I'm having this issue, not sure what caused it.  Were you able to solve the issue?

**Comment by pb-z** [comment]
@djyarber yes. In my case, I forget to modify webdriver for real device by following this [document](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md).
