### ISSUE TITLE
Calculating the CPU and Memory Usage

### ISSUE THREAD

**Issue by pavanbachu0604** [appium/appium#8129]
I understand that there were few old threads on this topic, with developments w.R.t WDA this would be whole new topic .

My question is that is it possible to calculate the CPU consumption and Memory Usage of the application with help of Appium ?

**Comment by imurchie** [comment]
For Android, yes. For iOS, not really.

**Comment by pavanbachu0604** [comment]
?Any Workaround ?

________________________________

**Comment by imurchie** [comment]
By "workaround" do you mean "implementation"? Not that I know of. We would love help with that, though!

**Comment by pavanbachu0604** [comment]
Does appium create kind of Tracetemplate which we could be used to calculate the CPU or Memory ?

**Comment by imurchie** [comment]
No. One could probably wire in `iprofiler` and get useful information, though.

**Comment by pavanbachu0604** [comment]
?What is iprofiler ? Can anyone share how to implement this ?

________________________________

**Comment by imurchie** [comment]
See the section "Profile from the Command Line" in this doc: https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/Recording,Pausing,andStoppingTraces.html#//apple_ref/doc/uid/TP40004652-CH12-SW1

**Comment by mannypp** [comment]
On iOS I have been using the Allocations instrument in the Instruments application. In the VM Tracker section when it is expanded you can look at the Resident Size to see the entire memory footprint of your app.

**Comment by pavanbachu0604** [comment]
@imurchie  I was trying to implement the iprofiler, but it seems that it finds the Vitals for only the MAC not the iPad connected. I tried the _instruments_ command. But I am not able to runt the automation runs as it creates a new session.

**Comment by mannypp** [comment]
We are not able to run instruments and automation tests at the same time. The issue we run into is that instruments crashes the application when you try to connect to the running application that was started with appium. Tried lots of things to fix this, but was unable to.

**Comment by pavanbachu0604** [comment]
@mannypp @imurchie   Any update regarding the capture of iOS Vitals?

**Comment by Hoang-Minh** [comment]
@imurchie : Just wonder if we are able to get the memory consumption on the new appium version 1.9.0 yet or not ? Thanks
