### ISSUE TITLE
Appium1.6.4Beta2 stucks on hideKeyboard

### ISSUE THREAD

**Issue by pb-z** [appium/appium#8131]
## The problem

When use the "driver.hideKeyboard();", it will output

> [debug] [JSONWP Proxy] Proxying [POST /wda/keyboard/dismiss] to [POST http://localhost:8100/session/68E58D3B-BEFE-4236-8C3C-6F71ECC853FD/wda/keyboard/dismiss] with no body

The Full Appium log [here](https://gist.github.com/pb-z/5078bfa1aeb49383f522ef6e9c20206b)
WebDriverAgentRunner Log is [here](https://gist.github.com/pb-z/93693b66c2cc7e086eb31f273c667a96)
## Environment

* Appium version (or git revision) that exhibits the issue:**Xcode 8.3 iOS 10.3 Appium 1.6.4Beta2**
* Last Appium version that did not exhibit the issue (if applicable): **Xcode 8.2 iOS 10.2 Appium 1.6.3**
* Desktop OS/version used to run Appium: Sierra 10.12.3
* Node.js version (unless using Appium.app|exe):v7.7.4
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by NagyRobertt** [comment]
Hi @pb-z i see the same issue. Did you fix this problem somehow?

**Comment by pb-z** [comment]
@NagyRobertt In my case, I use `driver.getKeyboard().pressKey(Keys.ENTER);` instead of `driver.hideKeyboard();`
