### ISSUE TITLE
How to use "findElOrEls" in appium-android-driver chromedriver.

### ISSUE THREAD

**Issue by DongWenHu** [appium/appium#8134]
How to use "findElOrEls" in appium-android-driver chromedriver.

The test demo "https://github.com/appium/appium-android-driver/blob/master/test/functional/webview-browser-tester-e2e-specs.js"

Does findElOrEls function go to bootstrap?

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask questions. This is the place for issues.
