### ISSUE TITLE
Problems to get elements on real device (XCUITest)

### ISSUE THREAD

**Issue by marvincod2** [appium/appium#8135]
I go with XCUITest in Xcode to test UI of my application. And I have a problem with existing of some UI elements in tree on real device. These elements have accessibilityIdentifiers in source code. I am able successfully use it on simulator (OS 10.2, iPad Air as example), I can see this element in tree when I use 'p print (app.debugDescription)' command during test run. But test fails on real device (iPad Air OS 10.2.1) and some elements are absent in elements tree. 

Will be I able to get rid of this problem using appium and WebDriverAgent. 

Sorry for my question not exactly about appium. 

## Environment

* Appium version (or git revision) that exhibits the issue:
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: ios 10
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
Probably not, since WDA uses the same XCTest calls under the hood. But you could give it a quick shot by checking in [Appium Desktop ](https://github.com/appium/appium-desktop/releases)
