### ISSUE TITLE
why can't get any webview element when using appium-uiautomator2-driver ?

### ISSUE THREAD

**Issue by yunduankaifa** [appium/appium#8136]
## The problem
hi, i can't get any webview elements when set 'automationName' as "uiautomator2". but it works when using default 'automationName'.

## Environment

* Appium version (or git revision) that exhibits the issue:  1.6.3
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:  android
* Node.js version (unless using Appium.app|exe):  v7.5.0
* Mobile platform/version under test: 7.1.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:  appium CLI

## Details
![Uploading rate.png…]()

![](https://static.dingtalk.com/media/lALOuVx-Ac0Cv80EVg_1110_703.png_620x10000q90g.jpg)

## Link to Appium logs

log (when using default 'automationName': appium-android-driver):
https://gist.github.com/yunduankaifa/866820851678d7c75cc404cca1ee9a3c

log (when setting 'automationName' as uiautomator2)：
https://gist.github.com/yunduankaifa/e086a8d31b74d9633b66383802232121

## Code To Reproduce Issue [ Good To Have ]

el = driver.findElement(By.ID, "rateIconWrap”)

**Comment by mykola-mokhnach** [comment]
Please fill out the issue template properly, attach logs and code, so then it will be possible to help.

**Comment by yunduankaifa** [comment]
thanks for your reminder.  i added logs and screenshot.

**Comment by mykola-mokhnach** [comment]
Do you observe the same issue while updating to 1.6.4-beta?
Can you also attach the output of 'adb logcat' while the lookup fails if yes?

**Comment by yunduankaifa** [comment]
yes, this issue still exist while updating to 1.6.4-beta.
adb log: 
https://gist.github.com/yunduankaifa/ce5f88c00d71707e5861ce85b554b847

**Comment by mykola-mokhnach** [comment]
ok, that all looks normal. What is the output of getPageSource though? Is the element present there?

**Comment by devstrat** [comment]
I'm observing the similar issue. 
Appium desktop v.1.6.4. 
The default automationName shows two contexts: Native and Webview, however if I switch to the uiautomator2, there's only Native context present, all other settings are absolutely the same and setWebContentDebuggingEnabled is set to true in the app.  
I've tried running getPageSource with uiautomator2 and the webview is indeed present in the xml.
