### ISSUE TITLE
Problem with build WebDriverAgent runner 

### ISSUE THREAD

**Issue by shapovalovei** [appium/appium#8137]
## The problem
After uninstall and install Appium again I have xcode error
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUIDevice.h:50:22: 'XCUISiriService' is partial: introduced in iOS 10.3`

I need use iOS version >= 10.3 ? Or its a bug ? How I must testing on prev version ? 
Please help me 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4@beta.2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4@beta
* Desktop OS/version used to run Appium: OSX Sierra 
* Node.js version (unless using Appium.app|exe): 7.0
* Mobile platform/version under test: iOS 10.2.1
* Real device or emulator/simulator: Real device (iPhone 6)
* Appium CLI or Appium.app|exe: CLI

**Comment by mykola-mokhnach** [comment]
Apply [this patch ](https://github.com/facebook/WebDriverAgent/pull/525) to WDA source to make it possible.

**Comment by shapovalovei** [comment]
@mykola-mokhnach  Thanks, I manually insert changes in Xcode project. Its work

**Comment by dkdodson3** [comment]
I am unsure what I am supposed to do with this patch to get things building. do you just add the flag no-partial-availability when building from the commandline?

**Comment by dkdodson3** [comment]
add this to the WARNING_CFLAGS in WebDriverAgent/Configurations/ProjectSettings.xcconfig:
-Wno-partial-availability

It seemed to work

**Comment by mykola-mokhnach** [comment]
We must wait until the patch is landed to WDA prior to publish it in Appium. Command line parameter workaround in Appium is possible, but it is going to be temporary in any case.
