### ISSUE TITLE
Unable to click the right element through Xpath/classname/ Index .

### ISSUE THREAD

**Issue by UserAutomation** [appium/appium#8138]
## The problem
I am working to automate an android app which have some screen of webview too. I am unable to click the right element through xpath, class, with index or even with giving name text.

![screen shot 2017-03-31 at 14 41 49](https://cloud.githubusercontent.com/assets/26655798/24555853/e2a045d8-1632-11e7-8e10-1b1351388a35.png)
![screen shot 2017-03-31 at 14 40 55](https://cloud.githubusercontent.com/assets/26655798/24555858/e46bb0a0-1632-11e7-8d8c-69524681814f.png)
![screen shot 2017-03-31 at 14 33 03](https://cloud.githubusercontent.com/assets/26655798/24555861/e5fbc05e-1632-11e7-9107-7c4c7a2d61a8.png)

if you see these screenshots it is visible that when i inspect element i get link to somewhere else. i tried using getlocation and then pass it for click but it also getting me wrong click.

i tried touchaction class methods but they are not working. My code get pass through appium but the methods tap or press nothing. 

tried this way too WebElement Quiz1 = (new WebDriverWait(driver , 20))
     .until(ExpectedConditions.presenceOfElementLocated(By.xpath("//android.view.View[contains(@content-desc,'Die Wish App')]")));
Quiz1.click();

but no luck.
Any help would be appreciated. Also how can i use webview rather than webelement? and which one is preferable?

**Comment by mykola-mokhnach** [comment]
Maybe there are multiple elements with the same property value on the page and the one you highlighted on the screenshot is not the one you are looking for and belongs to another view, which is in the background.

**Comment by mykola-mokhnach** [comment]
Can you also attach the output of driver.getPageSource command?

**Comment by UserAutomation** [comment]
Here is the output of .getpagesource()

[HTTP] --> GET /wd/hub/session/955f485b-4a4b-4975-a1a1-94e940e901fd/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["955f485b-4a4b-4975-a1a1-9...
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"source","params":{}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: source

[debug] [AndroidBootstrap] [UIAUTO STDOUT] [APPIUM-UIAUTO] [debug] Returning result: {"status":0,"value":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><hierarchy rotation=\"0\"><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.kwizzad.debugapp\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,0][1440,2392]\" resource-id=\"\" instance=\"0\"><android.widget.LinearLayout index=\"0\" text=\"\" class=\"android.widget.LinearLayout\" package=\"com.kwizzad.debugapp\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,0][1440,2392]\" resource-id=\"\" instance=\"0\"><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.kwizzad.debugapp\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,0][1440,2392]\" resource-id=\"android:id\/content\" instance=\"1\"><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.kwizzad.debugapp\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,0][1440,2392]\" resource-id=\"com.kwizzad.debugapp:id\/layout\" instance=\"2\"><android.widget.FrameLayout index=\"0\" text=\"\" class=\"android.widget.FrameLayout\" package=\"com.kwizzad.debugapp\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,0][1440,2392]\" resource-id=\"com.kwizzad.debugapp:id\/kwizzadView\" instance=\"3\"><android.webkit.WebView index=\"0\" text=\"\" class=\"android.webkit.WebView\" package=\"com.kwizzad.debugapp\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,0][1440,2392]\" resource-id=\"\" instance=\"0\"><android.webkit.WebView index=\"0\" text=\"\" class=\"android.webkit.WebView\" package=\"com.kwizzad.debugapp\" content-desc=\"KWIZZAD\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"true\" focused=\"true\" scrollable=\"true\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,0][1440,2392]\" resource-id=\"\" instance=\"1\"><android.view.View index=\"0\" text=\"\" class=\"android.view.View\" package=\"com.kwizzad.debugapp\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[955,563][1326,878]\" resource-id=\"\" instance=\"0\"><android.view.View index=\"0\" text=\"\" class=\"android.view.View\" package=\"com.kwizzad.debugapp\" content-desc=\"\" checkable=\"false\" checked=\"false\" clickable=\"false\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[955,563][1326,731]\" resource-id=\"\" instance=\"1\"><android.view.View index=\"0\" text=\"\" class=\"android.view.View\" package=\"com.kwizzad.debugapp\" content-desc=\"❎\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bo
unds=\"[1078,584][1204,710]\" resource-id=\"\" instance=\"2\"\/><\/android.view.View><android.view.View index=\"1\" text=\"\" class=\"android.view.View\" package=\"com.kwizzad.debugapp\" content-desc=\"FALSCH\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[955,728][1326,878]\" resource-id=\"\" instance=\"3\"\/><\/android.view.View><android.view.View index=\"1\" text=\"\" class=\"android.view.View\" package=\"com.kwizzad.debugapp\" content-desc=\"Worum geht es in diesem Quiz?\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[462,1568][1440,1645]\" resource-id=\"\" instance=\"4\"\/><android.view.View index=\"2\" text=\"\" class=\"android.view.View\" package=\"com.kwizzad.debugapp\" content-desc=\"Die Wish App\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[612,1946][990,2023]\" resource-id=\"\" instance=\"5\"\/><android.view.View index=\"3\" text=\"\" class=\"android.view.View\" package=\"com.kwizzad.debugapp\" content-desc=\"Einen Kuchen\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[1288,1946][1440,2023]\" resource-id=\"\" instance=\"6\"\/><android.view.View index=\"4\" text=\"\" class=\"android.view.View\" package=\"com.kwizzad.debugapp\" content-desc=\"Wrong Ans\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[647,2219][955,2296]\" resource-id=\"\" instance=\"7\"\/><android.view.View index=\"5\" text=\"\" class=\"android.view.View\" package=\"com.kwizzad.debugapp\" content-desc=\"Wrong Answer\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[1274,2219][1440,2296]\" resource-id=\"\" instance=\"8\"\/><android.view.View index=\"6\" text=\"\" class=\"android.view.View\" package=\"com.kwizzad.debugapp\" content-desc=\"1\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[1106,24][1134,77]\" resource-id=\"\" instance=\"9\"\/><android.view.View index=\"7\" text=\"\" class=\"android.view.View\" package=\"com.kwizzad.debugapp\" content-desc=\"\/\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[1130,24][1151,77]\" resource-id=\"\" instance=\"10\"\/><android.view.View index=\"8\" text=\"\" class=\"android.view.View\" package=\"com.kwizzad.debugapp\" content-desc=\"1\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"false\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[1148,24][1176,77]\" resource-id=\"\" instance=\"11\"\/><android.widget.Button index=\"9\" text=\"\" class=\"android.widget.Button\" package=\"com.kwizzad.debugapp\" content-desc=\"Info\" checkable=\"false\" checked=\"false\" clickable=\"true\" enabled=\"true\" focusable=\"true\" focused=\"false\" scrollable=\"false\" long-clickable=\"false\" password=\"false\" selected=\"false\" bounds=\"[0,0][133,133]\" resource-id=\"\" instance=\"0\"\/><\/android.webkit.WebView><\/android.webkit.WebView><\/android.widget.FrameLayout
><\/android.widget.FrameLayout><\/android.w
[debug] [AndroidBootstrap] [UIAUTO STDOUT] idget.FrameLayout><\/android.widget.LinearLayout><\/android.widget.FrameLayout><\/hierarchy>"}[/APPIUM-UIAUTO]
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.getPageSource() result: "<?xml version=\"1.0\" enco...
[HTTP] <-- GET /wd/hub/session/955f485b-4a4b-4975-a1a1-94e940e901fd/source 200 112 ms - 8270 
[HTTP] --> POST /wd/hub/session/955f485b-4a4b-4975-a1a1-94e940e901fd/element/4/click {"id":"4"}

**Comment by mykola-mokhnach** [comment]
Sorry, I cannot read this. Attach it as a file/gist for both cases (UiAutomation 1 and 2)

**Comment by UserAutomation** [comment]
<android.view.View index="2" text="" class="android.view.View" package="com.kwizzad.debugapp" content-desc="Die Wish App" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[612,1946][990,2023]" resource-id="" instance="5"/>

<android.view.View index="3" text="" class="android.view.View" package="com.kwizzad.debugapp" content-desc="Einen Kuchen" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[1288,1946][1440,2023]" resource-id="" instance="6"/>

**Comment by UserAutomation** [comment]
No the element i highlighted is right one But the inspection link go at the next element. If i highlight the next element it goes somewhere else
![screen shot 2017-04-04 at 14 21 42](https://cloud.githubusercontent.com/assets/26655798/24656258/176e692c-1942-11e7-9f6f-7637c0f5830b.png)
![screen shot 2017-04-04 at 14 21 54](https://cloud.githubusercontent.com/assets/26655798/24656259/191face0-1942-11e7-8a96-27411abfeb1b.png)

xt element it goes somewhere else

**Comment by UserAutomation** [comment]
Logs for the property 
[logs.docx](https://github.com/appium/appium/files/893095/logs.docx)

**Comment by dpgraham** [comment]
If it's in a webview you won't be able to locate it in Appium Desktop.

If you're still having issues, let me know and I can re-open this ticket.
