### ISSUE TITLE
command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 133

### ISSUE THREAD

**Issue by rameshkvv6231** [appium/appium#8141]
Hi Team,
Setup for 1.6 appium I have done all setup and done provising  with webdriveragent and it was success

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: 10.11
* Node.js version (unless using Appium.app|exe): 7.7
* Mobile platform/version under test: 10.0
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe:

## Details

While launching the app only I am facing the issue.

## Link to Appium logs
System log path: /Users/ga-mlsdiscovery/Library/Logs/CoreSimulator/D1D0CF38-F2E6-42A1-8AE9-6E41DF81060B/system.log
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid 'D1D0CF38-F2E6-42A1-8AE9-6E41DF81060B' not booted. Booting up now
[debug] [iOSSim] Killing all iOS Simulators
[iOSSim] Starting simulator with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID D1D0CF38-F2E6-42A1-8AE9-6E41DF81060B
[iOSSim] Simulator log at '/Users/ga-mlsdiscovery/Library/Logs/CoreSimulator/D1D0CF38-F2E6-42A1-8AE9-6E41DF81060B/system.log'
[iOSSim] Tailing simulator logs until we encounter the string "com.apple.springboard"
[iOSSim] We will time out after 60000ms
[debug] [iOSSim] Waiting an extra 10000ms for the simulator to really finish booting
[debug] [iOSSim] Done waiting extra time for simulator
[iOSSim] Simulator booted in 11553ms
[debug] [XCUITest] Installing app '/Users/ga-mlsdiscovery/Desktop/eswar/Payload/carousel.app' on device
[XCUITest] Using WDA path: '/opt/nodes/7.7.1/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/opt/nodes/7.7.1/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /opt/boxen/homebrew/bin/carthage
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[XCUITest] Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 133
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
 { Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 133
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  stdout: '\u001b[1mFetching dependencies\n',
  stderr: 'dyld: Symbol not found: __TMV6Result8AnyError\n  Referenced from: /opt/boxen/homebrew/Cellar/carthage/0.20.1/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks//ReactiveSwift.framework/ReactiveSwift\n  Expected in: /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks/Result.framework/Versions/A/Result\n in /opt/boxen/homebrew/Cellar/carthage/0.20.1/bin/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks//ReactiveSwift.framework/ReactiveSwift\nScripts/bootstrap.sh: line 45: 86076 Trace/BPT trap: 5       carthage bootstrap $USE_SSH\n',
  code: 133 }
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Running iOS simulator reset flow
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [XCUITest] Cleaning simulator state.
[debug] [iOSSim] Cleaning app data files for 'carousel.app', 'com.comenity.DualCardENT'
[debug] [iOSSim] Checking whether simulator has been run before
[debug] [iOSSim] Simulator has been run before
[debug] [iOSSim] Building bundle path map
[debug] [iOSSim] Checking whether simulator has been run before
[debug] [iOSSim] Simulator has been run before
[debug] [iOSSim] Building bundle path map
[debug] [iOSSim] Could not find app directories to delete. It is probably not installed
[debug] [iOSSim] Killing any simulator daemons for D1D0CF38-F2E6-42A1-8AE9-6E41DF81060B
[iOSSim] Cleaning simulator D1D0CF38-F2E6-42A1-8AE9-6E41DF81060B
[debug] [XCUITest] Resetting simulator
[debug] [XCUITest] Shutting down simulator
[debug] [iOSSim] Killing all iOS Simulators
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Command '/bin/bash Scripts/bootstrap.sh -d' exited with code 133
    at ChildProcess.<anonymous> (../../lib/teen_process.js:66:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[HTTP] <-- POST /wd/hub/session 500 33013 ms - 201 

## Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

Please git clone https://github.com/appium/sample-code and use one of your favourite languages and sample apps to reproduce the issue.

In case a similar scenario is missing in sample-code, please submit a PR with one of the sample apps provided.

**Comment by mykola-mokhnach** [comment]
try to reinstall carthage and make sure it works properly from command line

**Comment by rameshkvv6231** [comment]
Thanks but same thing issue happening can anyone tell me what to do

**Comment by mykola-mokhnach** [comment]
"Trace/BPT trap: 5" error code means there are problems while loading dynamic libraries. Usually this happens if PATH variable is corrupted or some important system libraries are missing/damaged. I'd rather try it on some other computer.

Check http://apple.stackexchange.com/questions/113379/how-to-debug-trace-bpt-trap-5 for example

**Comment by mykola-mokhnach** [comment]
Closing the issue as non Appium-related
