### ISSUE TITLE
Error while executing "webdriverAgentRunner" in xcode. 

### ISSUE THREAD

**Issue by vinyasjain77** [appium/appium#8144]
## The problem
Since Appium doesn't support UI Automation  using appium inspector now, I installed latest 1.6 version of appium and did the necessary changes to Xcode. But opening WebdriverAgent and choosing team as personal team in webdriverAgent I get errors and build fails. I need help on this. Tried various threads on this issue but none helped me.

## Environment

* Appium version : 1.6

* Desktop OS/version used to run Appium: 10.12
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Details

Failed to create provisioning profile.
The app ID "com.facebook.WebDriverAgentRunner" cannot be registered to your development team. Change your bundle identifier to a unique string to try again.

No profiles for 'com.facebook.WebDriverAgentRunner' were found

Attaching screenshot of the same
![screen shot 2017-04-01 at 7 50 16 pm](https://cloud.githubusercontent.com/assets/6780971/24579520/0b1738f4-1715-11e7-8c8a-7c42708bd4a7.png)

**Comment by MaisGurbanov** [comment]
Go to WebDriverAgentRunner -> Build Settings -> Build Settings -> Packaging -> Product Bundle Identifier and change it.

**Comment by vinyasjain77** [comment]
@MaisGurbanov I did that. Still the same result. What do I change it to?

**Comment by MaisGurbanov** [comment]
After changing please clear the project and rebuild it.

**Comment by mykola-mokhnach** [comment]
Try the **updatedWDABundleId** [capability](https://github.com/appium/appium-xcuitest-driver#usage)

**Comment by vinyasjain77** [comment]
I was able to successfully build both webdriverAgentLib and WebDriverAgent. But I still see those errors in xcode. Is that ok? @mykola-mokhnach @MaisGurbanov

**Comment by mykola-mokhnach** [comment]
It should not bother you unless you can run your automation.

**Comment by vinyasjain77** [comment]
Thanks it wo

**Comment by vinyasjain77** [comment]
Thanks. It is fixed. I am closing this issue.

**Comment by VytautasKoncius** [comment]
so how to fix it jesus

**Comment by paweldomas** [comment]
@vv1991
automatic signing worked for me after changing the WDA runner's bundle id, as mentioned above by @mykola-mokhnach 

Follow [this](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md#basic-automatic-configuration) part of "how to run on real device tutorial" and then use this code in the app (Java):

`capabilities.setCapability("xcodeOrgId", "CQA2B4G3K2");` (update with your 10 digit team id)
`capabilities.setCapability("xcodeSigningId", "iPhone Developer");` (this stays as "iPhone Developer")
`capabilities.setCapability("updatedWDABundleId", "com.something.WebDriverAgentRunner");` (come up with custom bundle id different than "com.facebook.WebDriverAgentRunner")

This way you don't have to manually open the .xcode project and change the signing settings. If you've done so then reinstall Appium first to have the defaults there.
