### ISSUE TITLE
Encountered internal error running command: Error: simctl error running 'io': Invalid device: <UDID>

### ISSUE THREAD

**Issue by MaisGurbanov** [appium/appium#8146]
Hello guys,

While testing through appium, there is the error about invalid UDID of real device. Please see the linked gist.

Appium 1.6.4-beta.2
XCode 8.3
iPhone 5s

https://gist.github.com/MaisGurbanov/8dbead8a56c96968e964d6377fdcdd3a

Thanks in advance.

**Comment by mykola-mokhnach** [comment]
Please temporarily apply the patch from https://github.com/appium/appium-xcuitest-driver/pull/413

**Comment by mykola-mokhnach** [comment]
you may use "gulp transpile" command to transpile files from "lib" folder into "bin" (it may also ask you to install some additional local npm dependencies there)

**Comment by imurchie** [comment]
The fix from @mykola-mokhnach is published in `appium-xcuitest-driver@2.26.1`.
