### ISSUE TITLE
Detecting ellipsis (...) in text

### ISSUE THREAD

**Issue by qakapil** [appium/appium#8147]
Hi,
It seems that Appium does not recognize ellipsis or truncation of text in the App. For example in our iOS app the text displayed is - "Game of Thr...", which is a bug. However, if I use element.get_text() to fetch the text of this element it returns proper text - "Game of Thrones"

Has anyone successfully used Appium to detect such text truncations ?

Thanks,
Kapil.

**Comment by mykola-mokhnach** [comment]
It works as expected. iOS UI shortens strings automatically while rendering the layout and this is not reflected on accessibility properties (don't forget that these properties are initially intended to be used by people with disabilities, so the string without period is much better option for them). 
You may try to implement either screenshots comparison (less stable) or calculate the expected text width and then compare it to the actual UI label width (more stable) instead.
