### ISSUE TITLE
Hang in step `[debug] [XCUITest] Removing WDA application from device`

### ISSUE THREAD

**Issue by cbalea** [appium/appium#8149]
## The problem

Simulator hangs when trying to remove the WDA application if xcodebild fails when testing `com.apple.test.WebDriverAgentRunner-Runner`.

## Environment

* Appium version (or git revision) that exhibits the issue: Appium 1.6.3 & Appium 1.6.4-beta.2
* Last Appium version that did not exhibit the issue (if applicable): Appium 1.6.3 before OS X update to 10.12.4
* Desktop OS/version used to run Appium: OS X Sierra 10.12.4 (16E195)
* Node.js version (unless using Appium.app|exe): v6.3.0
* Mobile platform/version under test: SIMULATOR - iOS 10.2
* Real device or emulator/simulator: SIMULATOR
* Appium CLI or Appium.app|exe: CLI
* XCode 8.2.1

## Details

This issue was happening for me from time to time, but it was very sporadic. After updating to the latest version of OS X, it behaves consistently. I'm using the Ruby library, version 9.3.6.

Steps to reproduce:
- launch any appium test via CLI
- Simulator hangs at this step: `[debug] [XCUITest] Removing WDA application from device`
- Above this line in the appium logs there seems to be an error when building the WebDriverAgent app: `Error Domain=IDETestOperationsObserverErrorDomain Code=12 "Failed to background test runner. If you believe this error represents a bug, please attach the log file at /Users/ciprian.balea/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/B3960F54-B007-42F4-BFCC-C34000B91E76/Session-WebDriverAgentRunner-2017-04-03_082049-kDUbck.log"`. I've attached the suggested log files as well.

When I'm building the Webdriver app manually with `xcodebuild` from cli, I get the same error. 

I've tried both Appium 1.6.3 and Appium 1.6.4-beta.2. They both produce the same error. Both logs attached. Using the `useNewWDA` capability for 1.6.4 doesn't fix the issue.

Appium-doctor says everything is ok.

## Link to Appium logs

[Appium 1.6.3 logs](https://gist.github.com/cbalea/e7b25fdc13846177cacca62a39d3962e)
[[1.6.3]Session-WebDriverAgentRunner-2017-04-03_082049-kDUbck.log](https://gist.github.com/cbalea/e30f19e7f9e80999d5467aa648f0454b)

[Appium 1.6.4-beta.2 logs](https://gist.github.com/cbalea/e89272f602f7ff2498573fcd341831d1)
[[1.6.4-beta.2] Session-WebDriverAgentRunner-2017-04-03_090411-AHtcTt.log](https://gist.github.com/cbalea/8f4a2a89af53f3d5bb8492a2fdb9832a)

**Comment by mykola-mokhnach** [comment]
Can you attach full appium log?

**Comment by cbalea** [comment]
@mykola-mokhnach Logs are attached as gist at the end of the description.

**Comment by mykola-mokhnach** [comment]
Can you try to remove "bundleId" capability from capabilities set?

**Comment by cbalea** [comment]
@mykola-mokhnach By removing `bundleId` I get the same error. New logs here: [appium.log](https://gist.github.com/cbalea/cb4f5d8119d7a9b84f8088f2ff78603c), [xcodebuild.log](https://gist.github.com/cbalea/6cb05b9c32d238bd59c2cfa2e8f0fe38)

**Comment by mykola-mokhnach** [comment]
What if you reset the simulator?

**Comment by cbalea** [comment]
Even if I use the `fullReset` capability to completely reset simulator, the bug is still happening.

**Comment by mykola-mokhnach** [comment]
What is the output if you select Product->Test for WDA source from Xcode? Try also with different devices in simulator

**Comment by cbalea** [comment]
@mykola-mokhnach Can you please give more detailed how to do `Product->Test for WDA source from Xcode`? What project do I need to open in XCode?

**Comment by mykola-mokhnach** [comment]
Usually it is located in folder:
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent

**Comment by cbalea** [comment]
@mykola-mokhnach I've opened this project: `open -a Xcode /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj` and ran `Product-> Test`.

This is the output: `Testing project WebDriverAgent with scheme WebDriverAgentRunner_2017-07-13T19-00-32`
```

Showing Recent Issues

=== BUILD TARGET WebDriverAgentLib OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

The file “ProjectSettings.xcconfig” couldn’t be opened because there is no such file. (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig)


=== BUILD TARGET WebDriverAgentRunner OF PROJECT WebDriverAgent WITH CONFIGURATION Debug ===

Check dependencies

The file “ProjectSettings.xcconfig” couldn’t be opened because there is no such file. (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/ProjectSettings.xcconfig)



Build succeeded    13/07/2017, 19:00

```

**Comment by mykola-mokhnach** [comment]
I have no other ideas. Try, probably, on some other machine or open an issue in https://github.com/facebook/WebDriverAgent/issues, since it is not an Appium issue, that WDA cannot start on the device.

**Comment by cbalea** [comment]
Manually verifying for the existance of that file, I see it is in there. 
```
cd /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Configurations/
Ciprians-MacBook-Pro:Configurations ciprian.balea$ ls -al
total 8
drwxr-xr-x   3 ciprian.balea  admin   102 Mar 31 20:29 .
drwxr-xr-x  20 ciprian.balea  admin   680 Apr  3 09:42 ..
-rw-r--r--   1 ciprian.balea  admin  1350 Mar 31 20:29 ProjectSettings.xcconfig
```

**Comment by cbalea** [comment]
Also, running on multiple Simulators and machines produces the same errors.

**Comment by cbalea** [comment]
Another stack trace when building the WebDriverAgentLib: https://gist.github.com/cbalea/db6f595271969f2b52c559a02e1b978e

**Comment by cbalea** [comment]
@mykola-mokhnach I have some updates that might be interesting for you:

1. I've browsed to this folder `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent`
2. ran `./Scripts/bootstrap.sh` as suggested in the [WebDriverAgent docs](https://github.com/facebook/WebDriverAgent#getting-started).
3. opened XCode and run `Product->Test`
4. tests failed
5. removed `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent`
6. checked out latest code of `WebDriverAgent` in `/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/`
7. run `./Scripts/bootstrap.sh`
8. opened XCode and run `Product->Test`
9. build succeeds, simulator starts and runs tests
10. stop XCode tests
10. start Appium server and run an Appium test
11. WDA still hangs when starting

Is Appium running `./Scripts/bootstrap.sh` at any time during the setup?

**Comment by cbalea** [comment]
Also, I've tried using the `usePrebuiltWDA = true` capability to use the WDA app I've built from XCode, but when I run the Appium test, it still fails when opening the WDA app.

**Comment by cbalea** [comment]
cc @imurchie maybe this is something related to appium-xcuitest-driver.

**Comment by cbalea** [comment]
I also when I run `./Scripts/bootstrap.sh`, I get this error:
```
Cannot find module 'eslint-config-appium'
Referenced from: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/.eslintrc
Error: Cannot find module 'eslint-config-appium'
Referenced from: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/.eslintrc
    at ModuleResolver.resolve (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:515:25)
    at load (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:532:26)
    at configExtends.reduceRight.e (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config/config-file.js:566:22)
    at loadConfig (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Inspector/node_modules/eslint/lib/config.js:260:26)
```

**Comment by mykola-mokhnach** [comment]
The last error happens if one executes bootstrap with -d option.

**Comment by Dheepthi** [comment]
Hi cbalea,
i m facing the exact same issue like u, https://github.com/appium/appium/issues/9269

Did u get any updates from WDA team?

**Comment by cbalea** [comment]
No. I'm just using appium 1.6.5 and everything works ok.

**Comment by sandeeppremise** [comment]
I found 1.6 was stable version comparatively others, there are less issues in that build. I am using latest Appium, this having WDA issues. It gets removed from real device when you run script.
