### ISSUE TITLE
"Application is not running, possibly crashed"

### ISSUE THREAD

**Issue by BasThomas** [appium/appium#8152]
## The problem

Running Appium `1.6.4-beta.2` on any non-iPad device crashes the app on startup. `iPad Air 2`, `iPad Air`, `iPad Pro (9.7 inch)` and `iPad Pro (12.9 inch)` all work fine. `iPhone 7 Plus`, `iPhone 5s` and others crash.

The app also works fine when run from `Xcode` directly; it is not crashing.

## Environment

* Appium version (or git revision) that exhibits the issue: `1.6.4-beta.2`
* Last Appium version that did not exhibit the issue (if applicable): `1.6.3` (with `iOS 10.2`)
* Desktop OS/version used to run Appium: `macOS 10.12.4`
* Node.js version (unless using Appium.app|exe): `v7.5.0`
* Mobile platform/version under test: `iOS 10.3`
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

As can be seen in the logs, creating a `WDA` session is failing. `WDA` is started when booting, after which the app is booted... but then crashes. As also can be seen in the logs, the app then restarts, but just keeps crashing.

## Link to Appium logs

https://gist.github.com/BasThomas/93ef691feb7498d354e55350cdad8f8f

**Comment by ochubey** [comment]
Sounds like incorrect device type selected while the application was built. 
Could you try to uninstall an application from iPhone simulator and install it using the following command from a terminal : `xcrun simctl install booted {path to app}` and run an application manually?

**Comment by BasThomas** [comment]
Thanks for the pointer, @ochubey. Installing the app with `xcrun` and then using the app doesn't crash it, but via Appium (which *WILL* reinstall the app), it once again is crashing.

**Comment by BasThomas** [comment]
With the same app, the View Hierarchy Debugger in Xcode is also failing on iPhone. Might this be related? https://gist.github.com/BasThomas/05a77124d2874f9c05334ce482dcbd37

**Comment by mykola-mokhnach** [comment]
@BasThomas You may have this problem https://github.com/facebook/WebDriverAgent/issues/535

**Comment by BasThomas** [comment]
I don't see any backtraces for unrecognised selectors, so I think this is a separate issue.

**Comment by dpgraham** [comment]
Closing this. If it's still happening on 1.6.6 I'll re-open.
