### ISSUE TITLE
Unable to start WebDriverAgent: Error: Command 'idevicedate -u <UDID> ' exited with code 25

### ISSUE THREAD

**Issue by vinyasjain77** [appium/appium#8153]
## Summary

When I try to install my test app(.ipa ) file on my real device I get this error every time. How do I fix this? Any help on this is really helpful?

## Environment

* Appium version 1.6

* Desktop OS/version used to run Appium: 10.12 (Xcode 8 )
* Mobile platform/version under test: iOS (10.2)
* Real device or emulator/simulator: Real device iphone 7

## Details

Getting an error everytime I run appium testng code from eclipse using appium from terminal. 
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent: Error: Command 'idevicedate -u <UDID>' exited with code 255 (WARNING: The server did not provide any stacktrace information)

## Link to Appium logs

 Calling AppiumDriver.createSession() with args: [{"app":"/Users/vinyasjain/Desktop/Wishbone.ipa","platformVersion":"10.2","--noReset":true,"platformName":"iOS","udid":"auto","deviceName":"iPhone 7"},null,null,null,null,null,null,null,null]
[Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[Appium] Creating new XCUITestDriver session
[Appium] Capabilities:
[Appium]   app: '/Users/vinyasjain/Desktop/Wishbone.ipa'
[Appium]   platformVersion: '10.2'
[Appium]   --noReset: true
[Appium]   platformName: 'iOS'
[Appium]   udid: 'auto'
[Appium]   deviceName: 'iPhone 7'
[debug] [XCUITest] XCUITestDriver version: 2.4.2
[BaseDriver] The following capabilities were provided, but are not recognized by appium: --noReset.
[BaseDriver] Session created with session id: e4669966-4150-42f3-8779-368741be617c
[debug] [XCUITest] Xcode version set to '8.3'
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [XCUITest] Auto-detecting real device udid...
[debug] [XCUITest] Using idevice_id
[debug] [XCUITest] Detected real device udid: '<UDID>'
[debug] [XCUITest] Creating iDevice object with udid e63439f13a9351ac209d3261454117a2e33f6cbd
[XCUITest] Determining device to run tests on: udid: 'e63439f13a9351ac209d3261454117a2e33f6cbd', real device: true
[BaseDriver] Using local app '/Users/vinyasjain/Desktop/<App>.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/m0/tt70y77s3jv44xfhmd50006w0000gn/T/201733-6269-oy99uf/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/m0/tt70y77s3jv44xfhmd50006w0000gn/T/201733-6269-oy99uf/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/m0/tt70y77s3jv44xfhmd50006w0000gn/T/201733-6269-oy99uf/Payload/Wishbone.app'
[debug] [XCUITest] Checking whether app '/var/folders/m0/tt70y77s3jv44xfhmd50006w0000gn/T/201733-6269-oy99uf/Payload/Wishbone.app' is actually present
[debug] [XCUITest] App is present
[debug] [ios-app-utils] Getting bundle ID from app '/var/folders/m0/tt70y77s3jv44xfhmd50006w0000gn/T/201733-6269-oy99uf/Payload/Wishbone.app': 'com.Science.Cyclops'
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[XCUITest] Setting up real device
[debug] [XCUITest] App is already installed.
[debug] [XCUITest] Full reset not requested. No need to install.
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: /usr/local/bin/carthage
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Using real device logger 'idevicesyslog'
[debug] [XCUITest] Beginning test with command 'xcodebuild build test -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=<uDID> -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u <UDID>' exited with code 255
[XCUITest] Unable to start WebDriverAgent: Error: Command 'idevicedate -u <UDID>' exited with code 255
[XCUITest] Shutting down sub-processes
[debug] [XCUITest] Running ios real device reset flow
[debug] [XCUITest] Resetting simulator
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: undefined
[HTTP] <-- POST /wd/hub/session 500 7142 ms - 262 

Please help me with this ASAP

**Comment by mykola-mokhnach** [comment]
Install Appium 1.6.4-beta

**Comment by vinyasjain77** [comment]
@mykola-mokhnach from where do I install that?

**Comment by mykola-mokhnach** [comment]
```
npm install -g appium@1.6.4-beta
```

**Comment by mykola-mokhnach** [comment]
Closed as duplicate
