### ISSUE TITLE
[xmldom error]	element parse error: TypeError: source.indexOf is not a function  @#[line:0,col:undefined]

### ISSUE THREAD

**Issue by liniqb** [appium/appium#8154]
## The problem

I am getting this issue when i tried to run my scripts in a real device, but am able to run the same scripts in a simulator.

## Environment

* Appium version (or git revision) that exhibits the issue: appium desktop 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: MAC OS
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPad 10 +
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe:

Also please let me know when the stable version of appium get released.

**Comment by mykola-mokhnach** [comment]
Make sure there are no WDA leftovers on the device from the previous installation
Also, it would be good to see Appium log.

**Comment by mykola-mokhnach** [comment]
Potential duplicate for https://github.com/appium/appium/issues/8080

**Comment by liniqb** [comment]
@mykola-mokhnach Thanks for the reply.
 I have removed earlier WDA references and ran the scripts.
But now getting this error:
Sebin Joseph (sebinj@qburst.com)
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted

**Comment by mykola-mokhnach** [comment]
I cannot help without the log

**Comment by TheChell** [comment]
@liniqb I also ran into this issue, but @mykola-mokhnach's suggestion about having WDA leftovers seemed to be my problem. Just to be sure, you deleted the WebDriverAgentRunner app and (if it had it) the Integration App from Xcode? After that, did you rerun a test, installing a new version of WebDriverAgentRunner?

**Comment by liniqb** [comment]
@TheChell We have to remove the WDA references from the **device** running the scripts.

**Comment by TheChell** [comment]
Yes, you can do that through Xcode by selecting the app and hitting the minus button.

**Comment by liniqb** [comment]
ok.. i am not sure about that. what I have done is, I deleted the WebDriverAgentRunner app from device and ran the scripts. It got worked.
Also deleted derived data and user data for the WDA instance.

**Comment by liniqb** [comment]
yes. 👍
