### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65

### ISSUE THREAD

**Issue by vinyasjain77** [appium/appium#8160]
## The problem

Not able to launch my app on real device. It works fine on simulators. I get the above error every time.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4- beta

* Desktop OS/version used to run Appium: 10.12

* Mobile platform/version under test:10.2
* Real device or emulator/simulator: iphone 7 real device

## Details

I am setting up 1.6.4 appium for automation tests and not able to launch my app on my real device. Error that I get is :  An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65 
## Link to Appium logs

[Xcode] 2017-04-03 22:55:28.503 xcodebuild[10029:749913] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/vinyasjain/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fcd99586a70 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 
[Xcode] 2017-04-03 22:55:28.503 xcodebuild[10029:749913] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1491240328544 (22:55:28 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 10028)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:373:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
 [Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65]
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:373:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:108:47)
    at /usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/es6.promise.js:119:28
    at flush (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
[HTTP] <-- POST /wd/hub/session 500 85121 ms - 230 
^C[Appium] Received SIGINT - shutting down

## Code To Reproduce Issue [ Good To Have ]

MY desired capabilites:

DesiredCapabilities caps = new DesiredCapabilities();
		File app=new File("/Users/vinyasjain/Desktop/app.ipa");
		caps.setCapability(MobileCapabilityType.APP,app); //To set the app path
		caps.setCapability(MobileCapabilityType.PLATFORM_VERSION,"10.2");//To set the iOS version
	    caps.setCapability(MobileCapabilityType.PLATFORM_NAME,"iOS");//To set the OS name
		caps.setCapability(MobileCapabilityType.DEVICE_NAME,"iPhone 7");
		caps.setCapability(MobileCapabilityType.UDID, "auto");// Type valid simulator name otherwise appium will throw an exception
	
		caps.setCapability("--noReset", true);
		driver = new IOSDriver (new URL("http://127.0.0.1:4723/wd/hub"), caps);
			     driver.manage().timeouts().implicitlyWait(30,TimeUnit.SECONDS);

Is there something wrong that I am doing? I need to set this appium ASAP. Any help will much appreciated. I am facing hurdles at each step with 1.6

**Comment by vinyasjain77** [comment]
@mykola-mokhnach any thoughts on this one?

**Comment by imurchie** [comment]
Can you provide the _full_ Appium logs, as a link to a [gist](https://gist.github.com)? There is no way to discuss anything without the configuration.

**Comment by vinyasjain77** [comment]
@imurchie here it is https://gist.github.com/vinyasjain77/28ab2a6571d6b07c41bc7320740144a4#file-gistfile1-txt

**Comment by mykola-mokhnach** [comment]
The logs says WDA cannot be compiled. What is in xcodebuild log?

```
[debug] [XCUITest] Log file for xcodebuild test: /Users/vinyasjain/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/AF3B52F8-4C8F-4310-A9A9-62D3E21ECB74/Session-WebDriverAgentRunner-2017-04-03_225528-5ANmR9.log
```

**Comment by imurchie** [comment]
Yeah. Sounds like a signing issue.

**Comment by vinyasjain77** [comment]
@mykola-mokhnach @imurchie No signing issue . Look at the screenshot
![screen shot 2017-04-04 at 12 15 06 am](https://cloud.githubusercontent.com/assets/6780971/24625193/de47eb30-18cb-11e7-95db-878b8343323d.png)

**Comment by imurchie** [comment]
But Appium is using xcodebuild from the command line to re-build this application. You need to provide the credentials or it will not work. The instructions are here: https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md#configuring-ios-real-device-tests-xcode-8-and-ios-93-and-above

**Comment by vinyasjain77** [comment]
Thanks a lot @imurchie @mykola-mokhnach . I did a manual signing and it's working fine.

**Comment by anhautomation** [comment]
Hi 
i have xcodebuild failed with code 65 too
May you let me know my root cause 
![failedcode65](https://cloud.githubusercontent.com/assets/26708307/25937395/b3bd8986-3655-11e7-8e13-d7128f473d68.JPG)
![xcodebuild](https://cloud.githubusercontent.com/assets/26708307/25937494/1d3ded92-3656-11e7-8d27-75a3fe6a9f2f.JPG)

Thanks,
Anh

**Comment by Turkistan** [comment]
Hello, I'm getting this same error code. I went in and manually configured the **Appium XCUITest Driver Real Device Setup** per the instructions, trying both manually and automatic. I tried both mutually exclusive methods. I have posted my failure log here 

https://gist.github.com/Turkistan/7ef0bf6fcabdaff8ff429216fbc9cab1

**Comment by imurchie** [comment]
@Turkistan It looks like you are running `appium-desktop` from a weird location. Have you installed it? Or are you running from inside the DMG?

**Comment by Turkistan** [comment]
@imurchie Thanks for the quick reply. I was able to get it running, I was having the same issues as others with the signing permissions not be saved properly in the xcode project for the WebDriverAGent. It kept reverting to the facebook.com. bundle name instead of the one I specified, but this time it seemed to take hold. 

This machine that I installed appium on is a laboratory machine meant to be accessible to multiple people. If it's installed weirdly, do you know how I can re-install without affecting my settings and saved capability profiles etc... ?

**Comment by imurchie** [comment]
I don't know of how to do that, no.

My assumption was from this line:
```
EROFS: read-only file system, mkdir '/private/var/folders/v6/zswzw5v10sx826mkrcgx_xy40000gn/T/AppTranslocation/7AB164D6-AF70-4543-AEE2-F330C561551A/d/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Resources'
```

**Comment by sameerapurini** [comment]
Hi,

I am unable to launch the app in iPhone 6s from macbook pro using Appium 1.7.1 and XCode 9.0.1. The error I am encountering is "Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device."

Can you please suggest?

Thanks,
S

**Comment by findmanish** [comment]
@sameerapurini  facing the same on save env details..

**Comment by imurchie** [comment]
@sameerapurini @findmanish This error is a catch-all for a number of things, usually related to code signing. If you want any help, you will need to provide the Appium server logs as a link to a [gist](https://gist.github.com), preferably with the `showXcodeLog` capability set to `true` so what Xcode is doing can be seen.

**Comment by sameerapurini** [comment]
hi @imurchie many thanks for the prompt reply.

Please find the logs in the gist

https://gist.github.com/sameerapurini/f494a89e5410b3b194e1793cace90ff0

thanks
S

**Comment by imurchie** [comment]
@sameerapurini The logs say you need a code signing identity. Since you didn't provide all the logs I can't tell if you provided one and it is in the wrong format or what.

Please see https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by sameerapurini** [comment]
@imurchie, the issue was with the webdriver agent not properly installed and running for the appium to pick up. Its resolved now, thanks again for the support.
