### ISSUE TITLE
Can't detect a crash on iOS application

### ISSUE THREAD

**Issue by jeangb** [appium/appium#8163]
## The problem

I'm writing an automated test to cover a scenario where my application crashes.
The problem is my test pass even if the application crashes !

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta
* Desktop OS/version used to run Appium: Mac OS 10.11.6
* Node.js version (unless using Appium.app|exe): 3.10.10
* Mobile platform/version under test: iOS 9.3.5
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: CLI

## Details
At the step where the app crashes, Appium is still able to access to the object.
Folowing step is swiping done on the application. Appium is actually able to swipe even if the application is crashed, as if my application was in background.
This is a very major issue if my tests aren't even able to detect a crash.
Can you help me ?

**Comment by mykola-mokhnach** [comment]
This is not a bug, since WDA works even if the app is in background/terminated. The only way to detect the application is in foreground or not is to explicitly check UI elements presence in the client code

**Comment by jeangb** [comment]
@mykola-mokhnach using isVisible() on a mobileElement for example ?

**Comment by mykola-mokhnach** [comment]
yes
