### ISSUE TITLE
Appium settings application(android) version 2.2.0 not installing after test launch

### ISSUE THREAD

**Issue by egorvas** [appium/appium#8164]
## The problem

Seems that with last implementations with appium settings application mechanism of app installing was broken. Now if you don't have previous  version of application you not able to get it during test session

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 beta latest
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3 beta
* Desktop OS/version used to run Appium: OSX
* Node.js version (unless using Appium.app|exe): v7.8.0
* Mobile platform/version under test: Android

## Details

Seems that it caused by merge of this pr https://github.com/appium/appium-android-driver/pull/219

## Link to Appium logs

https://gist.github.com/egorvas/56adda5dd5cf8d7b54d873eac83df85a

## Code To Reproduce Issue

You just need to install latest version of appium@beta via npm
And uninstall Appium Settings application from your cellphone

**Comment by mykola-mokhnach** [comment]
Are you on Simulator or real phone?

**Comment by egorvas** [comment]
I tried on my real Android 5.1.1 cellphone and 6.0 emulator

**Comment by mykola-mokhnach** [comment]
The logic has been changed, do now the settings apk is only installed on real devices (when **avd** capability is not set).

Do you want to say it is also not installed on the real phone?

**Comment by egorvas** [comment]
@mykola-mokhnach yes, exactly.
You can check provided gist, there no any commands like 
`["-P",5037,"-s","bb4ac01d","install","/usr/local/lib/node_modules/appium/node_modules/io-appium-settings/bin/io-appium-settings-debug.apk"]`

But I tried to run test on my real device in this case.

**Comment by mykola-mokhnach** [comment]
Thanks for the report. The fix is coming

**Comment by mykola-mokhnach** [comment]
Please update your beta and try it

**Comment by egorvas** [comment]
@mykola-mokhnach I need to say that current issue fixed and appium application installs correctly now.

But setting geolocation not working on real devices now, on 5 Android version as well.

**Comment by mykola-mokhnach** [comment]
Please provide appium log and adb logcat output for both emulator and real device. I'll check it

**Comment by egorvas** [comment]
@mykola-mokhnach It can takes some time for me, but I can confirm that on emulator geolocation works well.
But on my real cellphone appium settings application sends this logs:

```
04-04 17:00:57.405 3312-3312/io.appium.settings E/MOCKED LOCATION SERVICE: Location mocking only works in debug mode
04-04 17:01:28.175 3312-3324/io.appium.settings I/art: Debugger is no longer active
```
So, as I understand issue caused by bad implementation of debuging on real devices.

**Comment by mykola-mokhnach** [comment]
Let's see if we can do something about it. We very appreciate your assistance.

**Comment by egorvas** [comment]
@mykola-mokhnach 
I found that issue caused by check

`    if ((getApplication().getApplicationInfo().flags & ApplicationInfo.FLAG_DEBUGGABLE) != 0) {
            Log.e(TAG, "Location mocking only works in debug mode");
            return START_NOT_STICKY;
        }`

For some reasons this check not passed on my real device, but passed on emulator. In my understanding we should remove this check or replace with another one.

After deleting this check everything works fine on my side(real device and emulator).

**Comment by mykola-mokhnach** [comment]
;)

**Comment by mykola-mokhnach** [comment]
Also, you are welcome to become Appium contributor. 
![images](https://cloud.githubusercontent.com/assets/7767781/24662389/33a69ae8-1955-11e7-94ec-ec4b9f97ba4c.jpg)
