### ISSUE TITLE
Appium.getPageSource() is returning a botched element stack for my app.  Why?

### ISSUE THREAD

**Issue by kirksl** [appium/appium#8171]
Please see the links below to a gist of my appium log and an image of what I see when using Appium Element Inspector using Appium Desktop.  TestObject is the Appium Host and i've spec'd 1.6.3 in the capabilities.  The device has varied, with same results.  One device is an iPad mini 3 16GB with iOS 9.3.4.

Notice in the image that there are username and password fields along with a login button.  The element inspection is returning all 3 of those controls under one element with all of the textual data lumped together.

Any ideas on what I can try to resolve this?  The origin of my iPad app is React Native if that matters.

//gist
https://gist.github.com/kirksl/ed571f947292e4e4f4d94594413a430c

//appium desktop output image
http://pasteboard.co/tKlxBCkD.png

Appreciate any insight...

**Comment by mykola-mokhnach** [comment]
This is rather known XCTest bug, which does not respect landscape orientation properly. Appium 1.6.4-beta has some workarounds implemented for it, but,unfortunately, not everything can be workarounded.

**Comment by kirksl** [comment]
I'm also having this exact same issue with Appium Desktop 1.6.4-beta.  Can you elaborate on what workarounds it has in place or point me to documentation.  Thanks for the KT.
