### ISSUE TITLE
mobile: scroll is not working in 1.6.4-beta

### ISSUE THREAD

**Issue by sebinjqburst** [appium/appium#8174]
## The problem

I want to scroll down to an element at the bottom of my iPad and I was using mobile:scroll for the same. But after I updated to 1.6, scrolling is not working

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 beta
* Last Appium version that did not exhibit the issue (if applicable): 1.5.3
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe):
* Mobile platform/version under test: iPad iOS 10.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:

## Code To Reproduce Issue [ Good To Have ]

JavascriptExecutor js = (JavascriptExecutor) driver;
HashMap<String, String> scrollObject = new HashMap<String, String>();
scrollObject.put("direction", "down");
scrollObject.put("element", ((IOSElement) element).getId());
js.executeScript("mobile: scroll", scrollObject);

// 'element' is passed as a parameter

**Comment by mykola-mokhnach** [comment]
1. This may not work as expected in landscape mode, which is a known XCTest bug
2. Try different [approaches](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md), like swipe, dragFromToForDuration, absolute coordinates. Probably, something will work.

**Comment by sebinjqburst** [comment]
@mykola-mokhnach Okay, let me try. Thank You :-)

**Comment by sebinjqburst** [comment]
@mykola-mokhnach Has this been fixed?

**Comment by suganeby** [comment]
@sebinjqburst,
Were you able to scroll? I am using appium 1.6.5, i need to scroll to an element at the bottom of the screen in iphone.

**Comment by sebinjqburst** [comment]
@suganeby You can use moveTo element in touch action for scrolling till the required element.

**Comment by suganeby** [comment]
@sebinjqburst,
Thank you
I am using Swipe function to do scrolling.

**Comment by amatsuba1222** [comment]
Hi, I'm using Appium 1.6.5 and having issue scrolling down using swipe. Did anyone solve the issue?

**Comment by suganeby** [comment]
@amatsuba1222 
Below code should swipe to bottom of the screen.

       //Get the size of screen.
        Dimension size = iosDriver.manage().window().getSize();
      
        int starty = (int) (size.height * 0.80);   
        int endy = (int) (size.height * 0.20);
        
        int startx = size.width / 2;
       
        iosDriver.swipe(startx, starty, startx, endy, 3000);

**Comment by sebinjqburst** [comment]
@amatsuba1222 I am using moveTo element so as to move until an element.

TouchAction ta = new TouchAction(driver);
ta.press(100, 100).moveTo(element).release();
ta.perform();

**Comment by amatsuba1222** [comment]
Thanks for your replies!
@suganeby I am doing exactly the same thing except it is AndroidDriver, but I will get the unknown server-side error. My code worked perfectly well for iOS though. 
@sebinjqburst Thanks, I've tried your code but still getting the same error message.

**Comment by amatsuba1222** [comment]
Solved the problem. I needed to make Appium wait to make sure the page is loaded.

**Comment by vikramvi** [comment]
@triager please close per last comment

**Comment by sebinjqburst** [comment]
Hi @mykola-mokhnach, **mobile:scroll not working in landscape mode, which is a known XCTest bug**- Is the issue still open?
Thanks in advance.

**Comment by mykola-mokhnach** [comment]
The problem has been reported to Apple Radar more than a year ago. Nobody responded from Apple side since that.

**Comment by sebinjqburst** [comment]
@mykola-mokhnach Thank you for the update.
