### ISSUE TITLE
Randomly getting: Failed to create WDA session. Retrying...

### ISSUE THREAD

**Issue by lkounadis** [appium/appium#8178]
## The problem

Hello, I am facing the following problem, at random times. Appium gets stuck and I see this in the console I/launcher - Running 1 instances of WebDriver just hangs and retries which may continue after some time. In the logs at the same time I see this error  [XCUITest] returns this in the logs: Failed to create WDA session. Retrying...

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: MacOS 10.12.4
* Node.js version (unless using Appium.app|exe): 4.6
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Simulator
* Appium CLI or Appium.app|exe: 

## Link to Appium logs

https://gist.github.com/lkounadis/7990c79b820df64f1099d5543bfef282

**Comment by mykola-mokhnach** [comment]
Try Appium 1.6.4-beta
