### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70 

### ISSUE THREAD

**Issue by Manikanta29** [appium/appium#8180]
## The problem

When I try to run the code with iphone 5S (10.3.1) real device, I am getting the error "Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70 "  . The Same code is working fine with Iphone 4s & 6s (9.3.5) real device. 

## Environment

Appium:1.6.4-beta
Xcode:8

## Link to Appium logs

[Appium] Welcome to Appium v1.6.4-beta
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/mani/Documents/workspace_Mars2/Claim.ipa","buldleId":"com.abc.xyx","noReset":"false","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","automationName":"XCUITEST","udid":"a1313452435xxxxxxx","platformName":"iOS","deviceName":"iPhone","launchTimeout":500000}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/mani/Documents/workspace_Mars2/Claim.ipa","buldleId":"com.abc.xyx","noReset":"false","realDeviceLogger":"/usr/local/lib/node_modules/deviceconsole/deviceconsole","automationName":"XCUITEST","udid":"a1313452435xxxxxxx","platformName":"iOS","deviceName":"iPhone","launchTimeout":500000},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1491471465499 (15:07:45 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.20.0) session
[Appium] Capabilities:
[Appium]   app: '/Users/mani/Documents/workspace_Mars2/Claim.ipa'
[Appium]   buldleId: 'com.abc.xyx'
[Appium]   noReset: 'false'
[Appium]   realDeviceLogger: '/usr/local/lib/node_modules/deviceconsole/deviceconsole'
[Appium]   automationName: 'XCUITEST'
[Appium]   udid: 'a1313452435xxxxxxx'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone'
[Appium]   launchTimeout: 500000
[debug] [XCUITest] XCUITestDriver version: 2.20.0
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: buldleId, realDeviceLogger.
[BaseDriver] Session created with session id: e9c7045d-6bae-4576-8bdb-cc2a3479c553
[debug] [XCUITest] Xcode version set to '8.2.1' (tools v8.3.0.0.1.1490382677)
[debug] [XCUITest] iOS SDK Version set to '10.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1491471466042 (15:07:46 GMT+0530 (IST))
[debug] [XCUITest] Available devices: a1313452435xxxxxxx, a1313452435xxxxxxx
[debug] [XCUITest] Creating iDevice object with udid 'a1313452435xxxxxxx'
[XCUITest] Determining device to run tests on: udid: 'a1313452435xxxxxxx', real device: true
[BaseDriver] Using local app '/Users/mani/Documents/workspace_Mars2/Claim.ipa'
[debug] [BaseDriver] Copying local zip to tmp dir
[debug] [BaseDriver] Unzipping /var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201736-14118-1q9rx6p.nwgsyvi/appium-app.zip
[debug] [BaseDriver] Testing zip archive: /var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201736-14118-1q9rx6p.nwgsyvi/appium-app.zip
[BaseDriver] Unzipped local app to '/var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201736-14118-1q9rx6p.nwgsyvi/Payload/ClaimReporter.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1491471474219 (15:07:54 GMT+0530 (IST))
[debug] [XCUITest] Checking whether app '/var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201736-14118-1q9rx6p.nwgsyvi/Payload/ClaimReporter.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app '/var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201736-14118-1q9rx6p.nwgsyvi/Payload/ClaimReporter.app': 'com.GallagherBassett.firstconnect.test'
[debug] [BaseDriver] Event 'resetStarted' logged at 1491471474227 (15:07:54 GMT+0530 (IST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1491471474228 (15:07:54 GMT+0530 (IST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Found idevicesyslog: '/usr/local/bin/idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1491471474405 (15:07:54 GMT+0530 (IST))
[XCUITest] Setting up real device
[debug] [XCUITest] Reset requested. Removing app with id 'com.GallagherBassett.firstconnect.test' from the device
[debug] [XCUITest] Installing '/var/folders/8t/147j7y0j0c3gc14728jmcvmm0000gp/T/201736-14118-1q9rx6p.nwgsyvi/Payload/ClaimReporter.app' on device with UUID 'a1313452435xxxxxxx'...
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1491471482982 (15:08:02 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1491471482987 (15:08:02 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=a1313452435xxxxxxx -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[XCUITest] xcodebuild exited with code '70' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1491471554404 (15:09:14 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 14171)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1491471564658 (15:09:24 GMT+0530 (IST))
[XCUITest] Using WDA path: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=a1313452435xxxxxxx -configuration Debug' in directory '/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[XCUITest] xcodebuild exited with code '70' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1491471631425 (15:10:31 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 14208)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:368:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:368:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[debug] [iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70
    at XCUITestDriver.quitAndUninstall$ (../../lib/driver.js:368:15)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 176489 ms - 230 

## Code To Reproduce Issue [ Good To Have ]

public AppiumDriver<MobileElement> driver;
CommanFunctions commonFunctions = new CommanFunctions();
	
	
	@BeforeTest
	public void startUp() throws MalformedURLException
	{
		DesiredCapabilities cap = new DesiredCapabilities();
		File file = new File("/Users/mani/Documents/workspace_Mars2/Claim.ipa");
		try{
		cap.setCapability(MobileCapabilityType.UDID, commonFunctions.deviceUDID()); 
		cap.setCapability(MobileCapabilityType.DEVICE_NAME, commonFunctions.deviceName() );
		}
		catch(Exception e)
		{
			System.out.println("Unable to find the connected device");
		}
		
		cap.setCapability("buldleId", "com.abc.xyz");
		cap.setCapability("realDeviceLogger", "/usr/local/lib/node_modules/deviceconsole/deviceconsole");
		cap.setCapability("xcodeConfigFile", "/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/xcodeConfigFile.xcconfig");
		cap.setCapability(MobileCapabilityType.APP, file.getAbsolutePath());
		cap.setCapability(MobileCapabilityType.AUTOMATION_NAME, "XCUITEST");
		cap.setCapability("useNewWDA", "true");
		cap.setCapability("noReset","false");
		cap.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, 500000);
		
		driver = new IOSDriver<MobileElement>(new URL("http://0.0.0.0:4723/wd/hub"), cap);
		
	}

**Comment by mykola-mokhnach** [comment]
Have you tried to build and deploy WDA from Xcode to that device?

**Comment by Manikanta29** [comment]
Yes, WDA was theirs. Once I  ran the above code, WDA disabled from the iphone.

**Comment by imurchie** [comment]
Yes, Xcode 8.2.1 does not support iOS 10.3.

**Comment by Manikanta29** [comment]
Update the Xcode 8.3 and Appium 1.6.4@beta.2. Iphone 5s(10.3.1) is recognizing by the xcode 8.3.

**Comment by kavithaks** [comment]
I am also facing this issue. I have appium 1.6.5 
xcode 8.3.3
mac OS: sierra 10.12.6 
device: 10.3

Unable to launch the app on real device. 

I have the .ipa file shared from developer and using that to create automated tests.

Please help me on how to run scripts using 1.6.5 on real devices.

**Comment by vkatha** [comment]
Any resolution on above issue?.

**Comment by sumeetpanjabi** [comment]
@imurchie 
Will it be the same issue with Xcode Version 10.0 (10A255) 
Appium: 1.9.1
device: 12.1.2

**Comment by lizatniche** [comment]
was experiencing the same behavior.adding `useNewWDA:true` to `capabilities` and reinstalling carthage and forcing a re-symlink

**Comment by imurchie** [comment]
@sumeetpanjabi Yes. Xcode 10.0 does not know anything about iOS 12.1.2. Xcode 10.1 does, however. As a rule of thumb, if you plug in the device and open Xcode, if it cannot connect to the device then Appium will also not be able to do anything.

**Comment by sumeetpanjabi** [comment]
Yup, updated Xcode to 10.1 and it is supporting iOS 12.1.2

**Comment by ivantay2003** [comment]
This issue is same to the one that I filed 2 weeks ago
https://github.com/facebook/WebDriverAgent/issues/1027

**Comment by sumitgos** [comment]
Xcode10.1

and appium1.8.2

we face issue :
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70

any update on this ??

**Comment by sumitgos** [comment]
Hi all any update ??
Xcode10.1

and appium1.8.2
mac : 10.13.6
we face issue :
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70

any update on this ??
