### ISSUE TITLE
Hybrid App - Appium is unable to find Webview context on a real Android device

### ISSUE THREAD

**Issue by siggerzz** [appium/appium#8182]
## The problem
I'm trying to run tests for my hybird app on a real Android device. My test works fine on a simulator, however when running tests on a real Android device, my app launches, but my webview context is never found by the Appium driver.

## Environment

* Appium version (or git revision) that exhibits the issue: Tested: 1.6.3 / 1.6.0 / 1.5.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Windows/MacOS
* Node.js version (unless using Appium.app|exe): 4.6.1
* Mobile platform/version under test: Tested 7.1.1/7.0/6.0/5.0.1
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
**Can't find webview context**
[Nexus 5 - 5.0.1 Real Device Appium Log](https://gist.github.com/siggerzz/55d3deab95ff892b5fe8753818c99683)
**Working Simulator** 
[Nexus 6 - 7.1.1 Simulator Appium Log](https://gist.github.com/siggerzz/609e34f97cbb7b7b81a35ea216758f14 )

**Comment by NozomiIto** [comment]
I encountered the same issue:

- Android real device (HUAWEI P8lite)
- Appium server 1.6.4
- Mac
- Android version: 6.0

**Comment by nbhasker** [comment]
Hi - I'm having trouble using the Appium desktop (which uses Appium server 1.6.4) with an Ionic app on an Android emulator. The app is launched  but the screen shot retrieval never completes. Could you post the configuration that worked for the emulator in your case?

Thanks

**Comment by okanerdogan84** [comment]
Hi i face same problem . Appium deosn't find any webview
Android real device (Samsung Galaxy tab 4 )
Appium server 1.6.4
Mac
Android version: 5.0.2

**Comment by chinafootballyu** [comment]
same issue

**Comment by siggerzz** [comment]
Set the following in the onCreate method in your Android project. and it should fix the issue.

WebView.setWebContentsDebuggingEnabled(true);

**Comment by chinafootballyu** [comment]
@siggerzz it work, thanks.
