### ISSUE TITLE
Uiautomator2 times out when being initialised

### ISSUE THREAD

**Issue by bayerjan** [appium/appium#8183]
Appium version 1.6.3
automationName: uiautomator2

When I try to initialise my Appium server with uiautomator2, the server never manages to come up. The machine was restarted to avoid any problematic processes. 

[debug] [ADB] Running '/Users/bayer/Library/Android/sdk/platform-tools/adb' with args: ["-P",5037,"-s","0af4b63e02b3c03d","shell","kill",19705]
[UiAutomator2] Starting uiautomator2 server v0.0.8 with cmd: am,instrument,-w,io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner
[UiAutomator2] running command...
 adb -s 0af4b63e02b3c03d shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner... 
[UiAutomator2] Waiting for UiAutomator2 to be online...
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
[HTTP] <-- POST /wd/hub/session - - ms - - 
[HTTP] --> POST /wd/hub/session {"capabilities":{"desiredCapabilities":{"app":"/Users/bayer/Documents/apk/ar/android/app-release.apk","noReset":false,"clearSystemFiles":true,"platformVersion":"6.0.1","automationName":"uiautomator2","platformName":"Android","udid":"0af4b63e02b3c03d","deviceName":"Nexus5","fullReset":false},"requiredCapabilities":{}},"desiredCapabilities":{"app":"/Users/bayer/Documents/apk/ar/android/app-release.apk","noReset":false,"clearSystemFiles":true,"platformVersion":"6.0.1","automationName":"uiautomator2","platformName":"Android","udid":"0af4b63e02b3c03d","deviceName":"Nexus5","fullReset":false},"requiredCapabilities":{}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/bayer/Documents/apk/ar/android/app-release.apk","noReset":false,"clearSystemFiles":true,"platformVersion":"6.0.1","automationName":"uiautomator2","platformName":"Android","udid":"0af4b63e02b3c03d","deviceName":"Nexus5","fullReset":false},{},{"desiredCapabilities":{"app":"/Users/bayer/Documents/apk/ar/android/app-release.apk","noReset":false,"clearSystemFiles":true,"platformVersion":"6.0.1","automationName":"uiautomator2","platformName":"Android","udid":"0af4b63e02b3c03d","deviceName":"Nexus5","fullReset":false},"requiredCapabilities":{}},null,null,null,null]
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body

**Comment by mykola-mokhnach** [comment]
check the adb logcat output - probably there are some errors there

**Comment by JF-Rabbit** [comment]
@mykola-mokhnach 
i met similar issue.
run a simple code again and again, but after about 15 minutes, i can't start app even wait 10 minutes, and log show:

io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner...
[UiAutomator2] Waiting for UiAutomator2 to be online...
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8200/wd/hub/status] with no body
...

When is issue happened, adb logcat break.
it looks like somewhere suspend, only reboot cellphone to resolve.

**Comment by mykola-mokhnach** [comment]
@JF-Rabbit That sounds bad. But it is still possible to get the log. Set log buffer to the maximum available size in developer settings, wait until the freeze issue happens, restart the phone and dump  the log into a file. With larger buffer it is not going to override the stuff, which happened before reboot.

**Comment by Allfex** [comment]
@JF-Rabbit 
i have exactly same issue
did you solve this issue?
