### ISSUE TITLE
if another webview loads after setting the context it switches to that one

### ISSUE THREAD

**Issue by lkounadis** [appium/appium#8185]
## The problem

I have an cordova app which also has tealium. Tealium itself loads a second webview which is not visible. Because of this webview I am facing a couple of issues.
The first one which I solved was that capabilities.autoWebview had to be set to false and then manually set the context I wanted. Btw I am using webdriver as well for this to work.
to get the context I do something like this
`
wdBrowser.contexts().then(function (contexts) {
            return wdBrowser.context(contexts[1])
        })
`

which as stated works just as it should.
The second problem which I have yet to find a solution for is that, occasionally the tealium webview loads after I have already set my context to the one I want but for some weird reason appium-ios-driver goes and sets as the default context the new webview. This occurs in 
appium-ios-driver/lib/commands/context.js
 
`
extensions.onPageChange =  async function (pageChangeNotification) {
................
if (newPages.length) {
      newPage = _.last(newPages);
      logger.debug(`We have new pages, going to select page '${newPage}'`);
    } else {
.............
`

Is there anything I am missing here? Any help would be much appreciated

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Desktop OS/version used to run Appium: MacOs 10.12.4
* Node.js version (unless using Appium.app|exe): 4.6
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: cli

## Link to Appium logs
https://gist.github.com/lkounadis/875f114970d6bc6950e7fddc42a6a551

**Comment by dpgraham** [comment]
The first problem I don't think we can fix. autoWebView just opens the first webView it finds.

As for your second problem, is it switching contexts with you even doing anything? Which line in the logs does it switch to the Tealium webview?

**Comment by lkounadis** [comment]
No, I am not doing anything there. it just seems that tealium webview gets loaded slightly late sometimes and causes the the change you see on line is 106 [debug] [RemoteDebugger] Page changed...

**Comment by dpgraham** [comment]
@lkounadis Sorry I didn't end up following up on this. Did this problem keep happening for you or did you find a workaround? (Going to close this ticket but will re-open if necessary)
