### ISSUE TITLE
How to upgrade Appium-XCUITest-Driver without re-installing Appium?

### ISSUE THREAD

**Issue by dr12782** [appium/appium#8186]
This is a question and not really an issue. So, my apologies for posting this question here.

I find that the XCUITestDriver frequently keeps releasing a new version. I get this new version of XCUITestDriver only when I re-install my Appium. Is there a way where I can upgrade the XCUITestDriver without reinstalling my Appium? Thanks in advance.

**Comment by imurchie** [comment]
Yes. You can find whee appium is installed, and go there. There will be a `node_modules` directory inside the appium installation. There you can run `npm install appium-xcuitest-driver`. This will break, however, if there is anything outside of that driver that is synchronized (if another package needs to be updated or something). So it is definitely not recommended.
