### ISSUE TITLE
Appium Desktop failing to connect to TestObject with error EPROTO

### ISSUE THREAD

**Issue by kirksl** [appium/appium#8188]
Appium Desktop failing to connect to TestObject with error EPROTO

Repro
1. From either Windows 10 or OSX El Capitan open Appium Desktop.
2. Leave everything set to defaults and click Start Server.
3. Click Start New Session.
4. Click TestObject option from the top.
5. Enter a valid TestObject API Key.
6. Enter a capability to target a TestObject device (eg "testobject_device": "iPad_mini_3_16GB_real_2")
7. Click Start Session.
8. Error: EPROTO displays --> http://pasteboard.co/1bI0ZrvQZ.png
9. Uninstall/install Appium Desktop and repeat steps above.  EPROTO error displays again at step 8.
10. Note the original install was not experiencing this error yesterday.
11. Knowing the information in 10. continue with further testing.
12. Execute a test against the same TestObject API Key and testobject_device from wdio.
13. Test successfully connects, executes and passes.  TestObject UI also functions correctly.

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4-beta
* Desktop OS/version used to run Appium: Windows 10 | OSX El Capitan
* Node.js version (unless using Appium.app|exe): Not sure what TestObject is using
* Mobile platform/version under test: Agnostic happens to any device type on TestObject
* Real device or emulator/simulator: TestObject uses real devices
* Appium CLI or Appium.app|exe: Appium Desktop both .app and .exe

**Comment by mykola-mokhnach** [comment]
Please create the report in Applium Desktop issue [tracker](https://github.com/appium/appium-desktop/issues). Also, full Appium log is required

**Comment by kirksl** [comment]
https://github.com/appium/appium-desktop/issues/127
