### ISSUE TITLE
Appium 1.6 or above XCUITest not able to find the web views in my hybrid ios app

### ISSUE THREAD

**Issue by EBtransversal** [appium/appium#8190]
## The problem

Hi,I am doing the automation of hybrid(Native + webview) iOS app in real ios device connected with my PC where I could not able to find my web views when I gave "available_context" command.It showing only the "Native_app" as a output.

## Environment

* Appium version 1.6.1
* Xcode : 8.2.1
* Mac Desktop OS: 10.11.6
* Node.js version :4.4.4
* Mobile platform/version under test: ios 10.2.1
* Real device : iOS Device connected to MAC
* Appium CLI : Appium CLI 1.6.1

## Details

In earlier version of Appium (1.6 or below) I could find the web views using "available_context" commend since appium was using UIAutomate now it has been upgraded to XCUITest where I have the problem. In my app, till login page it had developed by native components after that everything is in web views. 

now please help me out to solve the issues despite i used "autoWebview" and "startIWDP" capabilities in my appium.txt.

**Comment by mykola-mokhnach** [comment]
Try Appium 1.6.4-beta

**Comment by EBtransversal** [comment]
I did installation of appium 1.6.4-beta version and still I am facing the same error.

When I do "arc" for getting available context and I got below.

**[3] pry(main)> available_contexts**

/Users/test/.rvm/rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/awesome_print-1.7.0/lib/awesome_print/formatters/base_formatter.rb:31: warning: constant ::Fixnum is deprecated
[
    [0] "NATIVE_APP"
]
 
Older version I got with web view like,
[
    [0] "NATIVE_APP",
    [1] "web_view_1"
]

## **Below are my appium output:**

[HTTP] --> GET /wd/hub/session/8ea9d83b-40d4-4a6b-93da-904023f70303/contexts {}
[debug] [MJSONWP] Calling AppiumDriver.getContexts() with args: ["8ea9d83b-40d4-4a6b-93da-904023f70303"]
[debug] [XCUITest] Executing command 'getContexts'
[debug] [iOS] Getting list of available contexts
[debug] [iOS] Retrieving contexts and views
[debug] [iOS] Selecting by url: false
[debug] [RemoteDebugger] Getting WebKitRemoteDebugger pageArray: localhost, 27753
[debug] [RemoteDebugger] Sending request to: http://localhost:27753/json
[iOS] **Attempted to get a list of webview contexts but could not connect to ios-webkit-debug-proxy. If you expect to find webviews, please ensure that the proxy is running and accessible**
[debug] [iOS] No web frames found.
[debug] [MJSONWP] Responding to client with driver.getContexts() result: ["NATIVE_APP"]
[HTTP] <-- GET /wd/hub/session/8ea9d83b-40d4-4a6b-93da-904023f70303/contexts 200 8 ms - 86

**Comment by mykola-mokhnach** [comment]
Try to set **startIWDP** capability to have the debug proxy connected

**Comment by SelvamaniD** [comment]
Thanks mykola-mokhnach  
Upgraded to appium to 1.6.4 and tried with following desired capabilities, it is working 
{'platformName' => iOS,'automationName' => 'XCUITest','platformVersion' => 10.2,'browserName' => 'Safari','deviceName' => iPhone 6 Plus 'autoWebview' => 'true', 'safariInitialUrl' => https://example.recognia.com, "bundleid"=>"com.apple.mobilesafari", 'startIWDP'=>'true'};
