### ISSUE TITLE
Appium not navigating to right URL 

### ISSUE THREAD

**Issue by SelvamaniD** [appium/appium#8191]
Appium Version : 1.6.4 
IOS version : 10.2 

However my problem is when I launch the test, it initiates the iOS simulator and launches safari perfectly, but always goes to http://0.0.0.0:4723/welcome first. Once it goes to that, after another 30 sec, it goes to my test and executes fine. The problem more specifically is when it is going to http://0.0.0.0:4723/welcome, since I am behind a corporate proxy, the page navigates to a captcha page which I have to manually enter. If I don't, it wont initiate my test and gets stuck at http://0.0.0.0:4723/welcome. I don't even know where this url (http://0.0.0.0:4723/welcome) is coming from. I want to remove this first initial test. I think it is something defaulted in Appium. This is my console output:

debug] [RemoteDebugger] Received response from socket send: '["PID:29882",
{"1":{"WIRTitleKey":"Page verifica...'
[debug] [RemoteDebugger] Page changed: {"1":{"WIRTitleKey":"Page 
verification","WIRTypeKey":"WIRTypeWeb","WIRURLKey":
"https://captcha.gecirtnotification.com/pitc/}}
[debug] [RemoteDebugger] Received app, but expected url 
('http://0.0.0.0:4723/welcome') was not found. Trying again.
[debug] [RemoteDebugger] Found app id key 'PID:29880' for bundle 
'com.apple.mobilesafari'
[debug] [RemoteDebugger] Found separate bundleId 
'com.apple.WebKit.WebContent' acting as proxy for 'com.apple.mobilesafari', 
with app id 'PID:29882'
[debug] [RemoteDebugger] Trying out the possible app ids: PID:29882
[debug] [RemoteDebugger] Selecting app PID:29882 (try #17 of 20)
[debug] [RemoteDebugger] Sending '_rpc_forwardGetListing:' message to remote 
debugger

**Comment by imurchie** [comment]
Try using the `safariInitialUrl` desired capability, setting it to the url you want to go to first. Appium needs to go somewhere, and in the absence of any indication, it opens a page that it itself serves.

**Comment by SelvamaniD** [comment]
I have tried with safariInitialUrl as desired capability but it is throwing error 
This is my desired capabilities 
 { 'app' => 'safari', 'platformName' => 'iOS','automationName' => 'XCUITest','platformVersion' =>'10.2','browserName' => 'Safari','deviceName' => 'iPhone 6  Plus', 'autoWebview' => 'true', 'safariInitialUrl' => 'https://google.com', "bundleid"=>"com.apple.mobilesafari"}

> Received app, but expected url ('https://google.com') was not found. Trying again.
Encountered internal error running command: Error: Could not navigate to webview; there are none!

**Comment by mykola-mokhnach** [comment]
**app** capability is not expected to be set in such case

**Comment by SelvamaniD** [comment]
Removed the app capability then tired. It is not working

**Comment by mykola-mokhnach** [comment]
please attach the new log

**Comment by SelvamaniD** [comment]
**Desired capabilities**
[Appium] Welcome to Appium v1.6.4-beta
[Appium] Non-default server args:
[Appium]   port: 4473
[Appium]   defaultCommandTimeout: 300
[Appium] Appium REST http interface listener started on 0.0.0.0:4473
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.6.4-beta","revision":null}}
[HTTP] <-- GET /wd/hub/status 200 20 ms - 88 
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"acceptSslCerts":true,"platform":"ANY","autoWebview":true,"automationName":"XCUITest","platformVersion":"10.2","version":"","browserName":"Safari","deviceName":"iPhone 6 Plus","bundleid":"com.apple.mobilesafari","safariInitialUrl":"https://example.recognia.com","javascriptEnabled":true,"platformName":"iOS"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"acceptSslCerts":true,"platform":"ANY","autoWebview":true,"automationName":"XCUITest","platformVersion":"10.2","version":"","browserName":"Safari","deviceName":"iPhone 6 Plus","bundleid":"com.apple.mobilesafari","safariInitialUrl":"https://example.recognia.com","javascriptEnabled":true,"platformName":"iOS"},null,null,null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1491808348899 (03:12:28 GMT-0400 (EDT))
[Appium] Creating new XCUITestDriver (v2.27.1) session
[Appium] Capabilities:
[Appium]   acceptSslCerts: true
[Appium]   platform: 'ANY'
[Appium]   autoWebview: true
[Appium]   automationName: 'XCUITest'
[Appium]   platformVersion: '10.2'
[Appium]   version: ''
[Appium]   browserName: 'Safari'
[Appium]   deviceName: 'iPhone 6 Plus'
[Appium]   bundleid: 'com.apple.mobilesafari'
[Appium]   safariInitialUrl: 'https://example.recognia.com'
[Appium]   javascriptEnabled: true
[Appium]   platformName: 'iOS'
[debug] [XCUITest] XCUITestDriver version: 2.27.1 


**Debug log :** 

[debug] [RemoteDebugger] Sending '_rpc_forwardGetListing:' message to remote debugger
[debug] [RemoteDebugger] Receiving data from remote debugger: '{"__argument":{"WIRApplicationIdentifierKey":"PID:22192","WIRListingKey":{"1":{"WIRTitleKey":"","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"https://example.recognia.com/serve.shtml?page=login","WIRPageIdentifierKey":1}}},"__selector":"_rpc_applicationSentListing:"}'
[debug] [RemoteDebugger] Received response from socket send: '["PID:22192",{"1":{"WIRTitleKey":"","WIRTypeKey...'
[debug] [RemoteDebugger] Page changed: {"1":{"WIRTitleKey":"","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"https://example.recognia.com
/serve.shtml?page=login","WIRPageIdentifierKey":1}}
[debug] [RemoteDebugger] Received app, but expected url ('https://example.recognia.com') was not found. Trying again.
[debug] [RemoteDebugger] Found app id key 'PID:22187' for bundle 'com.apple.mobilesafari'
[debug] [RemoteDebugger] Found separate bundleId 'com.apple.WebKit.WebContent' acting as proxy for 'com.apple.mobilesafari', with app id 'PID:22192'
[debug] [RemoteDebugger] Trying out the possible app ids: PID:22192
[debug] [RemoteDebugger] Selecting app PID:22192 (try #20 of 20)
[debug] [RemoteDebugger] Sending '_rpc_forwardGetListing:' message to remote debugger
[debug] [RemoteDebugger] Receiving data from remote debugger: '{"__argument":{"WIRApplicationIdentifierKey":"PID:22192","WIRListingKey":{"1":{"WIRTitleKey":"","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"https://example.recognia.com/serve.shtml?page=login","WIRPageIdentifierKey":1}}},"__selector":"_rpc_applicationSentListing:"}'
[debug] [RemoteDebugger] Received response from socket send: '["PID:22192",{"1":{"WIRTitleKey":"","WIRTypeKey...'
[debug] [RemoteDebugger] Page changed: {"1":{"WIRTitleKey":"","WIRTypeKey":"WIRTypeWeb","WIRURLKey":"https://example.recognia.com/serve.shtml?page=login","WIRPageIdentifierKey":1}}
[debug] [RemoteDebugger] Received app, but expected url ('https://example.recognia.com') was not found. Trying again.
[debug] [iOS] Could not navigate to webview. Retrying if possible.

**Error log** : 

[XCUITest] Error: Could not navigate to webview; there are none!
    at XCUITestDriver.spinHandles$ (../../../lib/commands/context.js:511:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
 Error: Could not navigate to webview; there are none!
    at XCUITestDriver.spinHandles$ (../../../lib/commands/context.js:511:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[MJSONWP] Encountered internal error running command: Error: Could not navigate to webview; there are none!
    at XCUITestDriver.spinHandles$ (../../../lib/commands/context.js:511:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)

**Comment by mykola-mokhnach** [comment]
check **startIWDP** capability

**Comment by SelvamaniD** [comment]
Thanks mykola-mokhnach  
Upgraded to appium to 1.6.4 and tried with following desired capabilities, it is working 
{'platformName' => iOS,'automationName' => 'XCUITest','platformVersion' => 10.2,'browserName' => 'Safari','deviceName' => iPhone 6 Plus 'autoWebview' => 'true', 'safariInitialUrl' => https://example.recognia.com, "bundleid"=>"com.apple.mobilesafari", 'startIWDP'=>'true'};
