### ISSUE TITLE
HideKeyboard method fails on iOS 10.3 with Appium 1.6.4-beta2

### ISSUE THREAD

**Issue by NagyRobertt** [appium/appium#8194]
## The problem

After upgrading to Xcode 8.3 and iOS 10.3 using Appium 1.6.4-beta2. Calling the hideKeyboard method fails.
On the Device i see that it puts the application to the background. Or rather it calls the WebDriverAgent in the foreground thus putting the tested app to the background. I'm guessing the WDA is reinitialized for some reason. Added Gist with appium log (Xcode log enabled) below.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4-beta2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: Sierra 10.12.1
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/NagyRobertt/b4838aa87bd77fdabd98ffeddfbfaf08

**Comment by HemantTrivedi** [comment]
@NagyRobertt  : Try using driver.navigate.back() .This should able to hide your keyboard

**Comment by mykola-mokhnach** [comment]
The hideKeyboard method might not work on iPhone and this is known XCTest/Apple bug. Try some other methods supported by your application under test.
