### ISSUE TITLE
appium fails to install iOS app

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [appium/appium#8196]
## The problem

I am trying to test a app developed with xamarin forms on iOS. Appium starts the simulator but failts in installing the app.

**Edit:** The app works fine when started from xamarin studio for iOS.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): not applicable
* Desktop OS/version used to run Appium: macOS Sierra 10.12.3
* Node.js version (unless using Appium.app|exe): v7.7.1
* Mobile platform/version under test: iOS iPhoneSimulator 10.3
* Real device or emulator/simulator: None
* Appium CLI or Appium.app|exe: appium-python

## Details

I am testing a xamarin forms app. The android version works, including the automated tests with appium.

For iOS I start appium with:

```
/usr/local/bin/appium --port "4724" --debug-log-spacing --platform-name "iOS" --show-ios-log --default-device  --default-capabilities '{"platformVersion":"10.3"}'
```

I then connect using appium-python:

```
        desired_caps = {}
        desired_caps['platformName'] = 'iOS'
        desired_caps['platformVersion'] = '10.3'
        desired_caps['automationName'] = 'XCUITest'
        desired_caps['deviceName'] = 'iPhone Simulator'
        desired_caps['app'] = appFile

        self.driver = webdriver.Remote('http://localhost:4724/wd/hub', desired_caps)
```

The resulting log file is full of things that seem to go wrong. I am unsure what the initial problem could be.

## Link to Appium logs

https://gist.github.com/RudolfVonKrugstein/edf32f7e79046e3088bb4ab94f8683c7

**Comment by imurchie** [comment]
Can you install the app into the simulator without Appium? The command Appium runs is `xcrun simctl install DF267A25-D872-4EB4-87BB-5614AE39B084 /Users/Shared/Jenkins/Home/workspace/OM-App-Pipeline/AppiumTests/tests/../../OM-App/OM_App.iOS/bin/iPhoneSimulator/Debug/OM_App.iOS.app`

**Comment by RudolfVonKrugstein** [comment]
No, that also fails with

```
$ xcrun simctl install DF267A25-D872-4EB4-87BB-5614AE39B084 /Users/Shared/Jenkins/Home/workspace/OM-App-Pipeline/AppiumTests/tests/../../OM-App/OM_App.iOS/bin/iPhoneSimulator/Debug/OM_App.iOS.app
An error was encountered processing the command (domain=MIInstallerErrorDomain, code=4):
Failed to chmod /Users/Shared/Jenkins/Library/Developer/CoreSimulator/Devices/DF267A25-D872-4EB4-87BB-5614AE39B084/data/Library/Caches/com.apple.containermanagerd/Bundle/Application/B9A27DBE-ADA9-4852-85E3-32EC9598F83A/OM_App.iOS.app/OM_App.iOS : No such file or directory
```

I am unsure why it is looking in that path. Or should it have been copied there?

**Comment by imurchie** [comment]
that's what you are passing in as the `app` capability.

**Comment by mykola-mokhnach** [comment]
closing as non Appium-related issue
