### ISSUE TITLE
appium1.6.3 -bash: appium: command not found 

### ISSUE THREAD

**Issue by johnmorrisQADeveloper** [appium/appium#8197]
## The problem

Not able to run appium on command prompt

I can see the /Users/username/.node_modules_global/lib
└─┬ appium@1.6.3

## Environment

* Appium version 1.6.3
* MAX Seirra 10.12.4
* Node.js version v7.8.0

**Comment by imurchie** [comment]
Did you install it locally or globally?

**Comment by mykola-mokhnach** [comment]
```
npm install -g appium
```

then make sure /usr/local/bin is present in PATH

**Comment by mykola-mokhnach** [comment]
Please use Appium forum for asking questions. Closing as not an issue

**Comment by johnmorrisQADeveloper** [comment]
my apologies for the late reply; I did install gloablly npm install -g appium ; and also I have in my ~/.bash_profile PATH=/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/bin
Not sure why it's like not able to launch it.

**Comment by mykola-mokhnach** [comment]
make sure appium has been installed properly. There should an executable _/usr/local/bin/appium_ script. One may also use appium-doctor tool for such purpose

**Comment by johnmorrisQADeveloper** [comment]
thank you, after appium script path was included my bash_profile, I can launch appium

**Comment by UtsavSaha** [comment]
just to add onto this, if i install appium locally (without the -g parameter), appium command is not getting recognized from the local directory. is there anything more that needs to be done?

**Comment by imurchie** [comment]
@UtsavSaha You mean running `appium` from the command line doesn't work? That will always be true for a local (non `-g`) installation. You can run it using `./node_modules/.bin/appium`

**Comment by UtsavSaha** [comment]
@imurchie 
Thanks.This helps.

**Comment by debasree888** [comment]
i have installed appium globally on ubuntu 18.04. when i ran appium-doctor it showed all okay. but when i run the command appium it shows command not found..please help
