### ISSUE TITLE
Bad Parameters error

### ISSUE THREAD

**Issue by abhilashcae** [appium/appium#8198]
## The problem

I'm running into BadParametersError while using Appium 1.5.3 and Python client (tried both 0.21 and 0.24). Everything was working fine 3 days ago. Not sure why it started failing now.

## Environment

* Appium version : 1.5.3
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Real Device
* Appium CLI or Appium.app|exe: CLI

## Appium logs gist

https://gist.github.com/abhilashcae/71f859d6823bcda35dfe59161f919062

**Comment by mykola-mokhnach** [comment]
This happens because of selenium lib update. You need to either update Appium to 1.6.4-beta and java_client to 5.0.0-BETA6 or downgrade selenium lib.

**Comment by abhilashcae** [comment]
As mentioned in the problem, I'm using Python client. Is there an update for that?

**Comment by abhilashcae** [comment]
Thank you @mykola-mokhnach ! As mentioned in the problem, I'm using Python client. Is there an update for that?

**Comment by mykola-mokhnach** [comment]
Downgrade Selenium to 3.2 helps for python
