### ISSUE TITLE
Unable to set focus on Text Box in iOS Real Device with Appium 1.6.4-beta version

### ISSUE THREAD

**Issue by Elangopalakrishnan** [appium/appium#8203]
The Problem:
I need to set focus the textbox and when i focus the text box It will open a keyboard.

Getting following error when trying to enter the value to textbox by using the below code:
AppDriver.Keyboard.SendKeys("1");

Error:

OneTimeSetUp: OpenQA.Selenium.WebDriverException : Unexpected error. Error Domain=com.facebook.WebDriverAgent Code=1 "Keyboard is not present" UserInfo={NSLocalizedDescription=Keyboard is not present}

So tired to focus the textbox, So if we focus the textbox, iOS will open a keyboard.
Then we can use the sendkyes to enter the value.

Environment:
Appium v1.6.4-beta
Desktop OS/version used to run Appium - OS 10.11.6
Mobile platform/version under test: iOS 10.2.1
Real device
Appium with C# code.
Visual Studio codedUI Framework.

Details:

I'm using appium with c# code.
Testing the web application on Safari browser in iOS Device, I need to enter the value and tap somewhere in the screen. (like entering the product quantity and touch somewhere in screen, then it will add into shopping cart).

I tried below code:
webDriver.FindElement(By.XPath("//input[@id='ProductDetails_QuantityTxt_3']")).SendKeys("1");
TouchAction tp = new TouchAction(AppDriver);
tp.Tap(100, 200, 3);
Here i can't hit tap event in iOS screen.
It doesn't work in c#.

I tried to set focus on text box by using Action class:
webElement = webDriver.FindElement(By.XPath("//input[@id='ProductDetails_QuantityTxt_3']"));
Actions act = new Actions(AppDriver);
act.MoveToElement(webElement).Click().Build().Perform();
Exxception: This method not implemented in c#.

I tried to set focus by using java script:
IJavaScriptExecutor js = (IJavaScriptExecutor).AppDriver;
js.ExecuteScript("return document.getElementById('ProductDetails_QuantityTxt_4').focus()");
But it doesn't focus the textbox in iOS Device safari browser, works fine in mac book safari browser.

I tried to open a keyboard by using this code also, got from [(2866](https://github.com/appium/appium/issues/2866) issue)
webElement = AppDriver.FindElement(By.XPath("//input[@id='ProductDetails_QuantityTxt_4']"));
IJavaScriptExecutor js = (IJavaScriptExecutor)AppDriver;
js.ExecuteScript("target.frontMostApp().keyboard().typeString('2')", webElement);
But i got Exception: [in C#]
[An unknown server-side error occurred while processing the command. Original error: Error while executing atom: Can't find variable: target (status: 13)]

Text box got focused when i tap the textbox manualy. and iOS open up a keyboard.
Entering the value:
AppDriver.Keyboard.SendKeys("1");
Hiding the keyboard:
IJavaScriptExecutor js = (IJavaScriptExecutor)AppDriver;
js.ExecuteScript("return document.getElementById('ProductDetails_QuantityTxt_4').blur()")

Please help me to open a keyboard in iOS Device or set focus on textbox in iOS Real Device.

Thanks in advance!

**Comment by mykola-mokhnach** [comment]
What if you simply invoke Click method on the text box before sending keys?

**Comment by Elangopalakrishnan** [comment]
Hi, I tried that too, Selenium click()
WebElement.click();
It doesn't work out.

**Comment by mykola-mokhnach** [comment]
Try ["mobile:tap"](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios-xctest-mobile-gestures.md) then

**Comment by Elangopalakrishnan** [comment]
I tried,
Dictionary<string, string> tfTap = new Dictionary<string, string>();
tfTap.Add("element", "//input[@id='ProductDetails_QuantityTxt_1']");
((IJavaScriptExecutor)mkConstants.AppDriver).ExecuteScript("mobile: twoFingerTap", tfTap);

but exception:
NotImplementedException was caught
Unknown command, all the mobile commands except scroll and swipe have been removed.

**Comment by mykola-mokhnach** [comment]
1. Update Appium to 1.6.4 (stable)
2. Element **ID** should be provided as argument (which is an internal hexadecimal hash), not locator string
3. You didn't try to tap by ccordinates

**Comment by chandrasekharmelam** [comment]
Hi Elango, 

Please try the below code for tap

WebElement ele = driver.findElement(By.className("abc"));
Point loc = ele.getLocation();
int x = loc.getX();
int y = loc.getY();
driver.tap(x, ele, y);

Note: This is java code.


Thank you,
Sekhar

**Comment by Elangopalakrishnan** [comment]
Hi Mykola mokhnach,

Updated appium 1.6.4 stable,
Tried mobile:tap functions,
IWebElement element = AppDriver.FindElement(By.XPath("//input[@id='ProductDetails_QuantityTxt_4']"));
                    Dictionary<string, string> tfTap = new Dictionary<string, string>();
                    tfTap.Add("element", string.Format("{0:X}", element));
                    ((IJavaScriptExecutor)AppDriver).ExecuteScript("mobile: twoFingerTap", tfTap);

But There is no actions performed in iOS Screen.
I have tried to Tap on Textbox and as well as one Link. 
Both didn't work.

Hi Sekhar,
Tried to Tap by using coordinates, 
IWebElement element = AppDriver.FindElement(By.XPath("//input[@id='ProductDetails_QuantityTxt_4']"));
                    Point point = element.Location;
                    int a = point.X; 
                    int b = point.Y;
                    AppDriver.Tap(a, element, b);
Exception caught:
Support for this multi-action is not implemented. Try to use "mobile: *" interface to workaround the issue in C#.

Note:
Developer written a js like The value entered by keyboard when text box is focused i guess.
they might be used First Responder keyboard Event Listener. i'm not sure about this.
But if i focus a textbox manually it gets focus then i use appdriver.keyboard.sendkeys("1");
It is working fine. I think i need to set focus and open a keyboard.
Please suggest on this.

Thanks!
Elango

**Comment by mykola-mokhnach** [comment]
```
IWebElement element = AppDriver.FindElement(By.XPath("//input[@id='ProductDetails_QuantityTxt_4']"));
Dictionary<string, string> tfTap = new Dictionary<string, string>();
tfTap.Add("element", string.Format("{0:X}", element));
((IJavaScriptExecutor)AppDriver).ExecuteScript("mobile: twoFingerTap", tfTap);
```

this code will not work as expected. Please read the document carefully.

**Comment by chandrasekharmelam** [comment]
@mykola-mokhnach you are correct. Elango, the code you tried was wrong.

Please try the below code
JavascriptExecutor js = (JavascriptExecutor) driver;
HashMap<String, String> params = new HashMap<String, Object>();
params.put("duration", 1.0);
params.put("fromX", 100);
params.put("fromY", 100);
params.put("toX", 200);
params.put("toY", 200);
params.put("element", ((RemoteWebElement) element).getId());
js.executeScript("mobile: tap", params);



Note: This is java code.

**Comment by Elangopalakrishnan** [comment]
Hi Sekhar and Mykola,
Tried below code in c#,
1) IWebElement element = AppDriver.FindElement(By.XPath("//input[@id='ProductDetails_QuantityTxt_3']"));
Dictionary<string, object> tapd = new Dictionary<string, Object>();
tapd.Add("duration",1.0);
tapd.Add("fromX", 428);
tapd.Add("fromY",583);                                    
tapd.Add("element",element);
((IJavaScriptExecutor)AppDriver).ExecuteScript("mobile: tap", tapd);

2) int x = 428, y = 583;
                    Dictionary<string, object> tapd = new Dictionary<string, Object>();
                    tapd.Add("duration",1.0);
                    tapd.Add("element", element);
                    ((IJavaScriptExecutor)AppDriver).ExecuteScript("mobile: tap", tapd,x,y);
Both code caught same exception:
**InvalidOperationException was caught**
An unknown server-side error occurred while processing the command. Original error: "x" parameter is mandatory for "tap" call.
Please have a look , 

Thanks!
Elango

**Comment by Elangopalakrishnan** [comment]
Hi ,
I have tried in java code in eclipse also,
No action performed when i run this code.
It doesn't Tap on textbox. :(
WebElement ele = driver.findElement(By.xpath("//input[@id='ProductDetails_QuantityTxt_4']"));		
		Point loc = ele.getLocation();
		int x = loc.getX();
		int y = loc.getY();		
		JavascriptExecutor js = (JavascriptExecutor) driver;
		Map<String, Object> params = new HashMap();
		params.put("x", x);
		params.put("y", y);
		params.put("element", ((RemoteWebElement)ele).getId());
		js.executeScript("mobile: tap", params);

Please have a look!
Thanks!

**Comment by mykola-mokhnach** [comment]
Tap at the center of the element instead of the top left corner

**Comment by Elangopalakrishnan** [comment]
Hi ,

I tried to Tap on Element's center position, but still i don't see any actions on screen.

int centerx = ele.getLocation().getX() + (ele.getSize().getWidth() / 2);		
int centery = ele.getLocation().getY() + (ele.getSize().getHeight() / 2);		

JavascriptExecutor js = (JavascriptExecutor) driver;
Map<String, Object> params = new HashMap();
params.put("x", centerx);
params.put("y", centery);
params.put("element", ((RemoteWebElement)ele).getId());
js.executeScript("mobile: tap", params);

Please have look on this code.

Thanks!
Elango

**Comment by Elangopalakrishnan** [comment]
Hi ,

I tried to tap on center of the element.
It is tapping on address bar instead of that particular element.
I tried with different element but still it is tapping address bar only.

Did i miss any point here, please review my code..

WebElement ele = driver.findElement(By.xpath("//input[@id='ProductDetails_QuantityTxt_4']"));
		int centerx = (ele.getSize().getHeight()) /2;		
		int centery = (ele.getSize().getWidth()) / 2;				
		JavascriptExecutor jss = (JavascriptExecutor) driver;
		Map<String, Object> params = new HashMap();
		params.put("x", centerx);
		params.put("y", centery);
		params.put("element", ((RemoteWebElement)ele).getId());
		jss.executeScript("mobile: tap", params);

Thanks!
Elango

**Comment by Elangopalakrishnan** [comment]
Hi ,

I have fixed this issue by switching the context to Native App.
mobile:Tap is not working accurately, So i changed the Web View to Native App view and Enter the value into text box and changed to Web View.
It is working fine.

Thanks for all your support :)
Elango

**Comment by RahimRahimov** [comment]
@Elangopalakrishnan 
Hi,

I have the same issue. Could you please explain how did you fixed this issue?  "So i changed the Web View to Native App" - how?

Thanks.

**Comment by DiogoMiranda** [comment]
Same issue. 
I am with a problem using version of Appium > 1.7.2. When starting to insert a text in a native app iOS, Appium miss the focus on screen, and then can't insert a text. 
I returned to version 1.7.2 and it is working well in this version.

Details

Command: find_elements(class: @field)[4].send_keys(Date[:text])
Version - working 1.7.2
version is not working, higher 1.7.2
Appium with Ruby 
Emulator - iPhone 6
iOS Version 11.4

![screen shot 2018-10-23 at 7 56 20 pm](https://user-images.githubusercontent.com/13684104/47437089-39c71680-d77e-11e8-8fe0-70a7e0244aea.png)
