### ISSUE TITLE
Question about clear Safari Cookies for mobile web 

### ISSUE THREAD

**Issue by xuanzhaopeng** [appium/appium#8204]
## The problem
I cannot use deleteAllCookies or deleteCookie (ruby lib + appium 1.6.4) to delete the cookies after i open the web in safari on iOS 10.3 (iphone 6s simulator),through appium-xcuitest-driver

The reason is I don't want to restart ios simulator after each scenario, thus i set noReset to true. However if I run test about 'user login',  so the users' cookies will always been there for other following scenarios, so I'd like to clear cookies at the very top of each scenario, but it doesn't work.

Should I post this question to Selenium or here?

Or do we have some options to clear the safari sessions but do not reset the simulator? (I already search a lot on internet, but unfortunately no suitable answer)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 (installed by npm)
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: macOS Sierra 10.12
* Node.js version (unless using Appium.app|exe):  v7.6.0
* Mobile platform/version under test: iOS simulator 10.3 (IPHONE 6S)
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: appium clii

Thanks a lot for your help

**Comment by xuanzhaopeng** [comment]
Finally I get a workaround for that :
```
rm -rf /Users/<Your name>/Library/Developer/CoreSimulator/Devices/<Device UUID>/data/Library/Cookies/Cookies.binarycookies
```

That works, but I still hope to know how you handle this in proper way?

**Comment by mykola-mokhnach** [comment]
This should work in 1.6.4. See 
https://github.com/appium/appium-ios-simulator/blob/master/lib/simulator-xcode-6.js, _ cleanSafari_ method

**Comment by mykola-mokhnach** [comment]
Although the current behaviour is expected if _noReset_ option is set to _true_. Use your workaround in such case.

**Comment by mykola-mokhnach** [comment]
> The reason is I don't want to restart ios simulator after each scenario, thus i set noReset to true. 

It should not be restarted in 1.6.4 unless fullReset is set to _true_ or _resetOnSessionStartOnly_ is set to _false_

**Comment by xuanzhaopeng** [comment]
Since 1.6.4, as @mykola-mokhnach said, I just remove noRest, and it will call the function https://github.com/appium/appium-ios-simulator/blob/master/lib/simulator-xcode-6.js, cleanSafari to clear all the data! It works really very properly!!

Thanks @mykola-mokhnach 's help

**Comment by aluckin3** [comment]
Hi guys, now in 1.9.1 if i don't type noReset=true, it will fullReset simulator. And how to use this cleanSafari through robotframework?
