### ISSUE TITLE
Chrome Browser is not closing from background 

### ISSUE THREAD

**Issue by UserAutomation** [appium/appium#8205]
## The problem

I want to quit the Chrome Browser after performing a certain task.
I used driver.close() its not working 
driver.quit() closes the session but browser is still running in background.what i want is remove the browser running instance from background too. in other words to kill the chrome process. I used driver.AppRest() too but no luck.

**Comment by mykola-mokhnach** [comment]
Can you show your session capabilities?

**Comment by UserAutomation** [comment]
capabilities.setCapability("appium-version", "1.6.4");
        capabilities.setCapability("platformName", "Android");
        capabilities.setCapability("platformVersion", "5.1.1");
        capabilities.setCapability("deviceName", "Nexus 6");
        capabilities.setCapability("app", "/Users/tvs00023/Desktop/KwizzAdd.apk");
        driver = new AppiumDriver(new URL("http://127.0.0.1:4723/wd/hub"), capabilities);

**Comment by mykola-mokhnach** [comment]
IMHO this is not possible since chrome is not the application under  test. You can workaround it by executing the corresponding adb command directly from your test framework.

**Comment by UserAutomation** [comment]
I am not even able to quit the application under test with these methods. after using the driver.quit();
Application still runs in background. is there any way to kill tht application ?

**Comment by mykola-mokhnach** [comment]
There is driver.closeApp method. I assume it should do the job for the application under test
