### ISSUE TITLE
searching element using name attribute is not working for ios 10.2

### ISSUE THREAD

**Issue by abh7nav** [appium/appium#8206]
## The problem

I used to search elements using name attribute but I observed in ios 10.2 and above, it is not able to search element using name attribute as below:
`//*[@name='Mail']`

This is now not working. Can anybody confirm.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.3/1.6.4
* Last Appium version that did not exhibit the issue (if applicable):1.6.3
* Desktop OS/version used to run Appium: mac os sierra
* Node.js version (unless using Appium.app|exe):7.5
* Mobile platform/version under test: ios 10.2
* Real device or emulator/simulator: real
* Appium CLI or Appium.app|exe: appium cli

## Details

I used to search elements using name attribute but I observed in ios 10.2 and above, it is not able to search element using name attribute as below:
`//*[@name='Mail']`

This is now not working. Can anybody confirm.

## Link to Appium logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here. 
Do _NOT_ paste your full Appium logs here, as it will make this issue very long and hard to read! 
If you are reporting a bug, _always_ include Appium logs!

## Code To Reproduce Issue [ Good To Have ]

`driver.searchElement(by.xpath("//*[@name='Mail']"));`

**Comment by vjmaiky** [comment]
Avoid using to search in root (//*[@name='Mail'])

Better to use  //XCUIElementTypeCell[@name,"Mail"]  or //XCUIElementTypeCell[contains(@name,"Environment")]

Replace //XCUIElementTypeCell with your own XCUI element/view

**Comment by mykola-mokhnach** [comment]
I'd rather say avoid using xpath in iOS at all :)

**Comment by vjmaiky** [comment]
indeed he can use id "Mail" eventually using an enum attribute (text, label, value) or element type (cell, etc) :); name is equivalent of id on iOS.

**Comment by abh7nav** [comment]
I tried searching using ID in xpath but it is not able to find element. You can look at below from appium inspector that element name is ios_confidence. I tried using xpath like:
a.) //XCUIElementTypeStaticText[contains(@id,'ios_confidence')]
b.) //XCUIElementTypeStaticText[contains(@name,'ios_confidence')]

As the element name is dynamic hence I am using xpath to find the element. 
Both it did not worked for me.
<img width="848" alt="screen shot 2017-04-18 at 9 51 50 am" src="https://cloud.githubusercontent.com/assets/16793057/25114557/09cca56e-241d-11e7-8581-1df096512638.png">

**Comment by mykola-mokhnach** [comment]
1. Use search by predicate instead of xpath. It is much faster

```
type == 'XCUIElementTypeStaticText' AND name CONTAINS 'ios_confidence'
```

2. The inspector you use is unsupported. Check https://github.com/appium/appium-desktop/releases instead

**Comment by abh7nav** [comment]
I tried using that `appium-desktop` but it is failing to start with below error:
```
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] Cannot parse major and minor version numbers from platformVersion "undefined". Will build for the default platform instead
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=e1e7256afc04d3430db23018c1e879979d25aefc -configuration Debug' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/Abhinav/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/8342CA55-5F14-4E66-A78C-B866562129FB/Session-WebDriverAgentRunner-2017-04-18_120305-gXQ08C.log
[Xcode] 2017-04-18 12:03:05.715 xcodebuild[82052:3755987] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/Abhinav/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7feed6df1c40 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 2017-04-18 12:03:05.715 xcodebuild[82052:3755987] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1492497185740 (12:03:05 GMT+0530 (IST))
```
