### ISSUE TITLE
WDA timeout when trying to send keys to a input field

### ISSUE THREAD

**Issue by vjmaiky** [appium/appium#8207]
## The problem

WDA timeout when trying to send keys to a input field

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4 beta2
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4 i got this error but not so often
* Desktop OS/version used to run Appium: max os sierra 10.12.4
* Node.js version (unless using Appium.app|exe): v7.4.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: iPhone 6+ 10.2.1/xCode 8.3

## Details
Basically i have a login method for all of my tests

		MobileElement login = (MobileElement) AppiumDriverInstance.getInstance().findElement(By.id("login_username"));
		login.clear();
		login.click();
		login.sendKeys(userName);

		MobileElement pass = (MobileElement) AppiumDriverInstance.getInstance().findElement(By.id("login_password"));
		pass.clear();
		pass.click();
		pass.sendKeys(password);

Randomly i get WDA timeout on username or on password, after 15 tests, 3 tests, 30 tests (it is not a rule).

I also added the capability:
capabilities.setCapability("wdaConnectionTimeout", 60000);

## Link to Appium logs
[debug] [MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"756D2C64-4CC2-4D83-9BE0-05F116E3FB75","type":"XCUIElementTypeSecureTextField","label":"login_password"}
[HTTP] <-- POST /wd/hub/session/49b453e4-1419-4a4d-b88d-8ba1d871109b/element 200 564 ms - 187 
[HTTP] --> POST /wd/hub/session/49b453e4-1419-4a4d-b88d-8ba1d871109b/element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/clear {"id":"756D2C64-4CC2-4D83-9BE0-05F116E3FB75"}
[debug] [MJSONWP] Calling AppiumDriver.clear() with args: ["756D2C64-4CC2-4D83-9BE0-05F116E3FB75","49b453e4-1419-4a4d-b88d-8ba1d871109b"]
[debug] [XCUITest] Executing command 'clear'
[debug] [JSONWP Proxy] Proxying [POST /element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/clear] to [POST http://localhost:8100/session/45AB7676-B4F5-4914-8B91-909B9186482A/element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/clear] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"status\" : 0,\n  \"id\" : \"756D2C64-4CC2-4D83-9BE0-05F116E3FB75\",\n  \"value\" : \"\",\n  \"sessionId\" : \"45AB7676-B4F5-4914-8B91-909B9186482A\"\n}"
[debug] [MJSONWP] Responding to client with driver.clear() result: null
[HTTP] <-- POST /wd/hub/session/49b453e4-1419-4a4d-b88d-8ba1d871109b/element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/clear 200 2196 ms - 76 
[HTTP] --> POST /wd/hub/session/49b453e4-1419-4a4d-b88d-8ba1d871109b/element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/click {"id":"756D2C64-4CC2-4D83-9BE0-05F116E3FB75"}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[debug] [XCUITest] Executing command 'proxyReqRes'
[debug] [JSONWP Proxy] Proxying [POST /wd/hub/session/49b453e4-1419-4a4d-b88d-8ba1d871109b/element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/click] to [POST http://localhost:8100/session/45AB7676-B4F5-4914-8B91-909B9186482A/element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/click] with body: {"id":"756D2C64-4CC2-4D83-9BE0-05F116E3FB75"}
[debug] [JSONWP Proxy] Got response with status 200: {"status":0,"id":"756D2C64-4CC2-4D83-9BE0-05F116E3FB75","value":"","sessionId":"45AB7676-B4F5-4914-8B91-909B9186482A"}
[JSONWP Proxy] Replacing sessionId 45AB7676-B4F5-4914-8B91-909B9186482A with 49b453e4-1419-4a4d-b88d-8ba1d871109b
[HTTP] <-- POST /wd/hub/session/49b453e4-1419-4a4d-b88d-8ba1d871109b/element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/click 200 1243 ms - 118 
[HTTP] --> POST /wd/hub/session/49b453e4-1419-4a4d-b88d-8ba1d871109b/element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/value {"id":"756D2C64-4CC2-4D83-9BE0-05F116E3FB75","value":["1234test"]}
[debug] [MJSONWP] Calling AppiumDriver.setValue() with args: [["1234test"],"756D2C64-4CC2-4D83-9BE0-05F116E3FB75","49b453e4-1419-4a4d-b88d-8ba1d871109b"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [JSONWP Proxy] Proxying [POST /element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/value] to [POST http://localhost:8100/session/45AB7676-B4F5-4914-8B91-909B9186482A/element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/value] with body: {"value":["1","2","3","4","t","e","s","t"]}
[debug] [XCUITest] Connection to WDA timed out
[debug] [JSONWP Proxy] Proxying [GET /element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/attribute/type] to [GET http://localhost:8100/session/45AB7676-B4F5-4914-8B91-909B9186482A/element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/attribute/type] with no body
[debug] [XCUITest] Connection to WDA timed out
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:144:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/49b453e4-1419-4a4d-b88d-8ba1d871109b/element/756D2C64-4CC2-4D83-9BE0-05F116E3FB75/value 500 120044 ms - 251 
[HTTP] --> POST /wd/hub/session/49b453e4-1419-4a4d-b88d-8ba1d871109b/element {"using":"id","value":"Nicht teilnehmen"}

Any suggestion here? if i update to java 5.0 beta6 and new selenium (to use setValue) i have too many framework dependencies that i need to fix (legacy on framework). So i would prefer to still use java 3.4.1 and selenium 2.53.0...

**Comment by mykola-mokhnach** [comment]
Update Appium to 1.6.4 stable and try to play with the  value for **maxTypingFrequency** capability.

Closed as [duplicate](https://github.com/facebook/WebDriverAgent/issues/481).

**Comment by dcohena** [comment]
@vjmaiky were you able to solve this issue? It happens for me occasionally but I can't find a way to solve this. Tried to play with maxTypingFrequency without any success..

**Comment by vjmaiky** [comment]
well for the moment i`m no longer facing this issue (appium 1.6.5).
i modified a bit the code:

MobileElement pass = (MobileElement) driver.findElement(By.id("login_password"));
pass.clear();
pass.click();
pass.sendKeys(password);

And i have some tries and waits for what i`m using. For now seems to work perfectly.

**Comment by mare1012** [comment]
Hallo @vjmaiky , have you tried on iPhone 10.3.1?

**Comment by mare1012** [comment]
@vjmaiky do you use ios-webkit-debug-proxy?if yes, which version? because sometimes my script is working and sometimes doesn't

**Comment by vjmaiky** [comment]
@mare1012  i`m not using it but i have it installed...4.0.5 version

**Comment by mare1012** [comment]
@vjmaiky you don't test the mobile safari right?

**Comment by vjmaiky** [comment]
nop. native iOS mobile app

**Comment by mare1012** [comment]
i see, i thougt you're testing mobile safari
