### ISSUE TITLE
WebView Element attributes different on different Android devices

### ISSUE THREAD

**Issue by poorvikamahesh** [appium/appium#8208]
Hello,

We have a hybrid application which we are trying to automate. Initially we had a Nexus 5 Android 6.0.1 device and completed writing our scripts and running on the same device.

We recently changed our device to another Nexus 5 (Android 6.0.1) but all our scripts failed. When we inspected, we noticed that the attributes of many elements are different.

For example, as we see in the screenshot, the resource ID is missing for the Forgot Password button in the new device

This is the case with other devices as well. Sometimes the element xpath changes from one device to another, though the Android Version, Appium Version, Application / web content version is the same.

Kindly help

* Appium  - 1.6.4 Beta
![nesus_5_office_login](https://cloud.githubusercontent.com/assets/10269471/24861809/a8735a3e-1e17-11e7-8712-8cbe43790086.png)
<img width="1440" alt="nexus_5_personal_login" src="https://cloud.githubusercontent.com/assets/10269471/24861808/a872cbb4-1e17-11e7-9e63-bcb48e29543e.png">

**Comment by poorvikamahesh** [comment]
@mykola-mokhnach 
We are stuck with this issue.
Could you kindly help?

**Comment by dpgraham** [comment]
Closing as duplicate
