### ISSUE TITLE
path info missing when "getPageSource" is called 1.6.4 release

### ISSUE THREAD

**Issue by jensen7up** [appium/appium#8209]
## The problem

The path info is missing when "getPageSource" is called 1.6.4 release, I found this to be useful in the automation process. 

<XCUIElementTypeWindow type=\"XCUIElementTypeWindow\" enabled=\"true\" x=\"0\" y=\"0\" width=\"375\" height=\"667\">\n

## Environment

* Appium version: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium:
* Node.js version (unless using Appium.app|exe): 10.12.4
* Mobile platform/version under test: 10.x
* Real device or emulator/simulator: simulator
* Java Client: 5.0.0-BETA3

## Details

The path info is missing when "getPageSource" is called 1.6.4 release

## Link to Appium logs
[debug] [XCUITest] Executing command 'getPageSource'
[debug] [JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/F939B7F0-7568-4056-A0D9-CF13B335C37D/source] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<XCUIElementTypeApplication type=\\\"XCUIElementTypeApplication\\\" name=\\\"Family Tree\\\" label=\\\"Family Tree\\\" enabled=\\\"true\\\" x=\\\"0\\\" y=\\\"0\\\" width=\\\"375\\\" height=\\\"667\\\">\\n  <XCUIElementTypeWindow type=\\\"XCUIElementTypeWindow\\\" enabled=\\\"true\\\" x=\\\"0\\\" y=\\\"0\\\" width=\\\"375\\\" height=\\\"667\\\">\\n    <XCUIElementTypeOther type=\\\"XCUIElementTypeOther\\\" enabled=\\\"true\\\" x=\\\"0\\\" y=\\\"0\\\" width=\\\"375\\\" height=\\\"667\\\">\\n      <XCUIElementTypeOther type=\\\"XCUIElementTypeOther\\\" enabled=\\\"true\\\" x=\\\"0\\\" y=\\\"0\\\" width=\\\"375\\\" height=\\\"667\\\">\\n        <XCUIElementTypeScrollView type=\\\"XCUIElementTypeScrollView\\\" enabled=\\\"true\\\" x=\\\"0\\\" y=\\\"0\\\" width=\\\"375\\\" height=\\\"667\\\">\\n          <XCUIElement ...

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by mykola-mokhnach** [comment]
That attribute has been used for internal purposes and was never intended to be used in the actual xpath queries.

**Comment by jensen7up** [comment]
80% of the automation I do is done with locators that I have created from getPageSource, the only time I use a Appium locator is when I do keyboard entry. I find by doing this the automation runs at least 10x faster, and I do not need to edit the app and add accessibility locators. There are several other benefits also, same code can be shared with Android, the automation is more robust with UI changes. It is easy to distinguish between the app window and say a status bar window (XCUIElementTypeWindow) using the "path", it would be nice to have. I do not use it as a xpath, more like a tag.

**Comment by jensen7up** [comment]
I also liked it when the  'getPageSource' returned attributes is empty values instead of not returning the attribute if it was empty.

**Comment by pb-z** [comment]
@jensen7up This is the old topic that has not resolved on WebDriverAgent side yet. Take a look at this [issue](https://github.com/facebook/WebDriverAgent/issues/372) You will find answer from mykola-mokhnach's comment

**Comment by mykola-mokhnach** [comment]
It's open source. You can always implement it in the way you like and create a pull request. What I can advice for now - try to use location by [class chain](https://github.com/facebook/WebDriverAgent/wiki/Queries). It is based on elements hierarchy and is faster than xpath

**Comment by jensen7up** [comment]
I have work around the issue

**Comment by jensen7up** [comment]
I have work around the issue
