### ISSUE TITLE
come up with plan for better mac CI

### ISSUE THREAD

**Issue by jlipps** [appium/appium#8210]
Travis is a great service but the feedback we get is very slow, jobs often take hours or days to start. Let's explore other options:

* MacStadium
* Resurrecting the specialty VMs hosted in the Sauce Labs infrastructure
* Using Sauce Labs test VMs directly with a custom pre-built Appium

Acceptance criteria here are just a plan for moving forward and new issues created!

**Comment by imurchie** [comment]
Travis paid plans: https://travis-ci.com/plans
