### ISSUE TITLE
hook up TestObject to android CI

### ISSUE THREAD

**Issue by jlipps** [appium/appium#8211]
Let's start testing at least a subset of our tests on real devices! TestObject has created a capability for running arbitrary versions of Appium so it's now possible to do this with CI:

* Use Travis to `npm install` all Appium's deps
* Zip everything up
* Upload zip to s3 or somewhere
* Run tests with that zip url as a special appium cap on testobject

We can start with a subset of tests at first if we want. Probably the android-driver and uiautomator2-driver is where we want this.

One wrinkle is that we want to test a driver, not all of appium. So we can either zip up a driver and claim it's appium (maybe it will just work), or we can npm install appium, npm link the driver at its state in the CI build, and zip up all that.

**Comment by dpgraham** [comment]
Acceptance criteria:

* [ ] Add helper methods to appium-test-support that extend wd so that it uploads Appium zips to S3 and then runs tests on TestObject
* [ ] Amend `appium-uiautomator2-driver` so that it runs TestObject tests when an environment variable is set (this may require some refactoring to use WD instead of the appium driver)
* [ ] Get it working on iOS
* [ ] Amend `appium-xcuitest-driver` to run tests on TestObject

**Comment by kirksl** [comment]
@dpgraham Do you know what rev of appium will take the changes for "Ammend appium-xcuitest-driver to run tests on TestObject"?

**Comment by imurchie** [comment]
`appium-xcuitest-driver` already uses `wd` to run its tests. Should be fine already, other than where it sends its requests, which should be easy to adjust.

**Comment by kirksl** [comment]
@imurchie appium-xcuitest-driver is bundled with appium correct?  if true what i was wondering is what version of appium 1.6.4, 1.6.5, etc i need that includes the amended appium-xcuitest-driver.  ultimately i'm targeting testobject so i need to know if their latest 1.6.5 choice will pickup this amendment.

**Comment by imurchie** [comment]
I think you are talking about something different from this issue. This issue is to make it so we can run our tests _of_ Appium within the Test Object cloud.

As far as I know the current version of Appium works fine in production at Test Object.

**Comment by kirksl** [comment]
Thanks @imurchie.  I was hoping this might have been a fix that came in for the defective element stack we get back on iOS devices when using Appium and TestObject.   https://github.com/appium/appium-desktop/issues/131
