### ISSUE TITLE
Error while setting up WebDriverAgent on realdevice.

### ISSUE THREAD

**Issue by vinyasjain77** [appium/appium#8212]
## The problem

I am suddenly facing  issues on starting  WebdriverAgent. It quits when unexpectedly. Was working fine all these days. Now the tests are failing all the time. 

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4_beta

* Desktop OS/version used to run Appium: 10.12

* Mobile platform/version under test:10.2 
* Real device or emulator/simulator: iPhone 7

## Details

Steps are like this:
1. I start the appium server
2. Run my selenium code from eclipse
3. App installs from the specific app path

But Test fails since the webdriver fails and gets uninstalled from the device.

## Link to Appium logs
https://gist.github.com/vinyasjain77/75bb2c69ea28375b15493bd9be5f2f05

**Comment by mykola-mokhnach** [comment]
Try to reboot the device

**Comment by vinyasjain77** [comment]
@mykola-mokhnach No other way to solve this issue? It will erase the content in my phone.

**Comment by vinyasjain77** [comment]
https://gist.github.com/vinyasjain77/cdb56df21c1f778e68d313d0f1ecb905 rebooting didn't work. Gist has the webDriverAgent test failure logs

**Comment by mykola-mokhnach** [comment]
There was known XCTest bug about Mac OS update. You must update Xcode to 8.3 after updating your Mac OS to 10.12.4

**Comment by vinyasjain77** [comment]
I am in the latest xcode and MAC OS . Still the problem persists

**Comment by vinyasjain77** [comment]
Xcode: 8.3.1
Mac OS : 10.12.4

**Comment by mykola-mokhnach** [comment]
Have you tried to build and deploy WDA from Xcode?

**Comment by vinyasjain77** [comment]
Yes did that both of WebDriverAgentLib and WebDriverRunner were built successfully with no errors

**Comment by mykola-mokhnach** [comment]
Is the error reproducible with Appium 1.6.4-stable?

**Comment by mykola-mokhnach** [comment]
Also check the log on real device - probably there is some useful info there

**Comment by vinyasjain77** [comment]
I updated to 1.6.4 and it is working after the update.
