### ISSUE TITLE
I cannot select/find an element using xpath when using xcuitests

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [appium/appium#8214]
## The problem

I am trying to select a item from an action sheet. Also "pageSource" says, it is there, it is not found.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): not applicable
* Desktop OS/version used to run Appium: macOS Sierra 10.12.3
* Node.js version (unless using Appium.app|exe): v7.7.1
* Mobile platform/version under test: iOS iPhoneSimulator 10.3
* Real device or emulator/simulator: None
* Appium CLI or Appium.app|exe: appium-python

## Details

I am using appium-python to test on iOS. I am opening an action sheet and I want to select an element, for this I do:

     driver.find_element_by_xpath("//XCUIElementTypePickerWheel/XCUIElementTypeOther")

to find the elements. But there is always 0 elements returned, also `driver.page_source` returns a page where it should be found.

Here is the page_source: https://gist.github.com/RudolfVonKrugstein/15bee03099a9b519edcf211b5f2087a6

## Link to Appium logs

**UPDATE**: https://gist.github.com/RudolfVonKrugstein/ce196d45302a2e4995cb68c464945ac7

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by mykola-mokhnach** [comment]
Please share appium log. 
Have you tried to use explicit wait to check element presence?

**Comment by RudolfVonKrugstein** [comment]
I have added the appium logs. Yes I am waiting for the peresence of the element. And I can see the the iOS simultor, that the action sheet is definitly present.

**Comment by RudolfVonKrugstein** [comment]
Mmmh, it seems to be related to this specific `xpath`.

`//XCUIElementTypePicker/XCUIElementTypePickerWheel` returns one element as expected.

What I am actually looking for is a way to make a choice in a action sheet (picker wheel).

**Comment by RudolfVonKrugstein** [comment]
Well, I did not read this https://github.com/appium/appium/blob/master/docs/en/advanced-concepts/migrating-to-xcuitest.md properly.

A solution is shown in #6962
Thans!
