### ISSUE TITLE
Unable to Launch App in Real Device : appium 1.6.4

### ISSUE THREAD

**Issue by Lakshmi2310** [appium/appium#8215]
## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium: Mac OS Siera 10.12.4
* Node.js version (unless using Appium.app|exe):v7.8.0
* Mobile platform/version under test: 10.3.2
* Real device or emulator/simulator: Real Device 
* Appium CLI or Appium.app|exe:

## Details

application is getting launched in the Device and i could see the home page as well but the page is not opening up in the mac machine 

Desired Capabilities 

	DesiredCapabilities capabilities = new DesiredCapabilities();
		capabilities.setCapability(MobileCapabilityType.APPIUM_VERSION,"1.6.4");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME,"IOS");
		capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION,"10.3.2");
		capabilities.setCapability(MobileCapabilityType.DEVICE_NAME,"iPhone 5s");
		capabilities.setCapability(MobileCapabilityType.UDID,"813f6a5691bc091cb6653dc09176a107be108193");
		capabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT,50000);
		capabilities.setCapability(MobileCapabilityType.AUTOMATION_NAME,AutomationName.IOS_XCUI_TEST);
		capabilities.setCapability(MobileCapabilityType.APP,"/Users/maria/Downloads/CastAppDLR-1.0.39.ipa");

## Link to Appium logs
https://gist.github.com/Lakshmi2310/1f17c73a523211fe2e041ec3fcd4f0ac

**Comment by mykola-mokhnach** [comment]
Try to increase IOSMobileCapabilityType.LAUNCH_TIMEOUT

**Comment by shapovalovei** [comment]
@mykola-mokhnach  I have same problem. 
OSX ver: 10.12.4
Xcode ver: 8.3.1

**Comment by shapovalovei** [comment]
Any updates ?

**Comment by mykola-mokhnach** [comment]
@shapovalovei are you sure your problem is the same?

Do you see this error in the log as well?

> [Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'

**Comment by shapovalovei** [comment]
@mykola-mokhnach No

**Comment by Lakshmi2310** [comment]
Hi Mykola , i tried increased the time but still i get the same issue, I am able to launch the app and able to perform the actions as well in the app but still in appium logs i see this 

[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted

**Comment by mykola-mokhnach** [comment]
@shapovalovei This has been already discussed many times here. There is known XCTest bug and only Apple can solve it. Try to keep WDA running without reinstall/restart as long as possible to avoid the error above on real device.

**Comment by mykola-mokhnach** [comment]
> Hi Mykola , i tried increased the time but still i get the same issue, I am able to launch the app and able to perform the actions as well in the app but still in appium logs i see this

This is another issue then. Please check the log carefully and try to find matches in existing issue reports. I'm sure someone already had similar problems. If not then create a new issue report and attach all the necessary information.

Closing this as resolved.
