### ISSUE TITLE
Not able to run app Simulator, not an  Inspector Doctor launch

### ISSUE THREAD

**Issue by DipakMakwana123** [appium/appium#8216]
## The problem

Hello,

I am new in Mobile Automation.
I am using Appium version Version 1.0.0-beta.6, when I tried to launch the app in ios Simulator, Simulator launched and install WebDriver App, then after nothing has happened.The Webdriver app dismisses automatically. If Webdriver app is installed in the simulator, my app is launched and dismiss automatically.I don't know why this happened.

## Environment

* Appium version (or git revision) that exhibits the issue: **Version 1.0.0-beta.6 (1.0.0-beta.6)**
* Last Appium version that did not exhibit the issue (if applicable): - **This is my first version**
* Desktop OS/version used to run Appium:**10.12.4 (16E195)**
* Node.js version (unless using Appium.app|exe):**7.7.1**
* Mobile platform/version under test:**Mobile platform - IOS / iOS Version - 10.2**
* Real device or emulator/simulator:**simulator**
* Appium CLI or Appium.app|exe: Appium.app

## Details

Please let me know, is this issue due to using the beta version of Appium?
If yes, please give me its solution.

## Link to Appium logs

**Some of them log line:**

[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.2\",\n      \"ip\" : \"192.168.1.215\"\n    },\n    \"build\" : {\n      \"time\" : \"Apr  7 2017 12:28:52\"\n    }\n  },\n  \"sessionId\" : \"15200BBB-15FF-466E-B43D-40E750BF649C\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent running on ip '192.168.1.215'
[XCUITest] WebDriverAgent successfully started after 35577ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1491894037442 (12:30:37 GMT+0530 (IST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.HowAbout.HABChat","arguments":[],"environment":{},"shouldWaitForQuiescence":true}}

## Code To Reproduce Issue [ Good To Have ]

**Steps which I followed to produce this issue:**
1) Start the Appium Server 
2) Set the desired capabilities 
3) Start the Session
4) Webdriver app lunches and dismiss automatically.

**Comment by mykola-mokhnach** [comment]
Please use Appium forum to ask question. This is the place for bugs and issues

**Comment by DipakMakwana123** [comment]
Is this is not an issue?

**Comment by DipakMakwana123** [comment]
This is not my question. The issue which I faced.

**Comment by mykola-mokhnach** [comment]
"Issue" means some exception, blocked functionality, non-expected behaviour, etc. In your case everything works as expected and the problem lies in server setup itself. That is why the is the question.
