### ISSUE TITLE
appium  fail to create new session when perform touchAndHold for a long time

### ISSUE THREAD

**Issue by songzcn** [appium/appium#8217]
## The problem
Appium started up with command "appium -a 127.0.0.1 --session-override".Had a session set up successfully. During performing touchAndHold command for a long time, requested for a new session. Appium logged 'Proxying [DELETE /session/3cb3876e-9039-466f-b839-80174a299f57] to [DELETE http://localhost:8100/session/2C47C874-E32A-4EA7-9FB9-A9BA8A9AE9E5] with no body' and started new session failed.
Tested on Appium Desktop-1.0.0 release, have the same result.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): maybe 1.6.4-beta.2
* Desktop OS/version used to run Appium: os X 10.12
* Node.js version (unless using Appium.app|exe): 7.0.0
* Mobile platform/version under test:  ios 10.2、ios 10.3
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe:  both CLI and app

## Link to Appium logs
https://gist.github.com/songzcn/984085d6cd1862d6115f49825e31e6ce

**Comment by mykola-mokhnach** [comment]
I don't see any problems so far. The logs says:

> [Appium] Session override is on. Deleting other sessions.

**Comment by songzcn** [comment]
@mykola-mokhnach It seems like deleting session event was failed?

**Comment by mykola-mokhnach** [comment]
Why do you think the problem lies in _session-override_ option? Maybe it's just a problem with new session creation? Can you attach the log where it is clearly visible where the failure happens?

**Comment by songzcn** [comment]
Sorry mokhnach,  i mistook the error. The error is when i execute 'mobile: touchAndHold' command and set duration for a long time, before the command is finished, the session won't create successfully.

**Comment by mykola-mokhnach** [comment]
Then this is expected. WDA calls are synchronous and there is no other way to stop/cancel them on real device except of uninstalling the whole WDA client application

**Comment by songzcn** [comment]
Yes, thanks mokhnach.
