### ISSUE TITLE
Problem with coordinates in landscape mode. Appium 1.6.4

### ISSUE THREAD

**Issue by korenevichev** [appium/appium#8218]
## Environment

Appium version (or git revision) that exhibits the issue:1.6.4
Last Appium version that did not exhibit the issue (if applicable):1.6.3
Desktop OS/version used to run Appium: Mac OS Siera 10.12.3
Node.js version (unless using Appium.app|exe):v7.8.0
Mobile platform/version under test: 10.2
Real device or emulator/simulator: Real Device
Appium CLI or Appium.app|exe:Appium CLI

## Details
Problems with coordinates for phone in landscape mode. For example it could switch to another screen instead of clicking on required element. And couldn't switch when it's needed. Those tests are still work with appium 1.6.3

**Comment by mykola-mokhnach** [comment]
This is known XCTest bug, that it does not respect coordinates in landscape mode. We have some workarounds for it in our code, but not everything can be workarounded. Let us know what exactly you are trying to do and maybe we can find a solution.

**Comment by korenevichev** [comment]
@mykola-mokhnach But why it does work with appium 1.6.3?

**Comment by mykola-mokhnach** [comment]
Sorry, but I'm not an expert in your client code and don't know what is "it" and why it worked before and why it does not work now. All the server code is open source - you can investigate the diff between 1.6.3 and 1.6.4

**Comment by tylerrrrrr** [comment]
@mykola-mokhnach I see this too.

Our app displays in landscape mode, and on 1.6.3 using both simulator and real device I am able to find and click on this certain element for example.

On 1.6.4, the real device can find and click on the element but the simulator will not. Using the iOS inspector, the coordinates for the desired element seem to be way off causing the element to not be found. Strange how in this case only the simulator is affected.

**Comment by mykola-mokhnach** [comment]
@tylerrrrrr It may depend on iOS version on the device, since the bug has been introduced by XCTest/Apple, which means it might be also fixed in some newer OS version. Can you specify OS versions for both platforms where it works and where it does not and provide inspector screenshots?

**Comment by tylerrrrrr** [comment]
@mykola-mokhnach 
OSX: 10.11.6
Xcode: 8.2.1
iOS(simulator & device): 10.2

The simulator has the issue on 1.6.4, but works fine on 1.6.3.

**Comment by mykola-mokhnach** [comment]
@tylerrrrrr This information is not enough. It would be useful to see the comparison of inspector screenshots and also concrete cases where API calls fail
