### ISSUE TITLE
setText after clear prefixes old value when accessed by  android class after being cleared

### ISSUE THREAD

**Issue by patrickgallagher** [appium/appium#8219]
## The problem

When trying to set set the text value of EditText if the value has been cleared before it will prefix the last value to the input after being cleared

## Environment

* Appium version 1.6.3
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: Debian Linux 8.7
* Node.js version (unless using Appium.app|exe): 7.6.0
* Mobile platform/version under test: Android 4.3
* Real device or emulator/simulator: 
* Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs

https://gist.github.com/patrickgallagher/9eff9ffd93c26c165b0c167fb38036ad

**Comment by mykola-mokhnach** [comment]
What code do you use to set the text? Have you tried to use sendKeys?

**Comment by patrickgallagher** [comment]
I am using java to set the text. the code is as follows:

AndroidElement element  = getAndroidDriver().findElements(By.xpath("//android.widget.EditText")).get(elementNum-1);
element.clear();
element.sendKeys(value);

**Comment by mykola-mokhnach** [comment]
1. Can you make sure the value contains correct text?
2. Try to click the text field to set the input focus there before clearing it
3. Try to add a small delay between clear and sendKeys
4. Try to set a breakpoint after element.clear(); and enter the text manually to see what happens then

**Comment by patrickgallagher** [comment]
ok after some debugging it looks like clear is the problem, it said that it has been cleared but it has not been deleted out so when it sets the text it appends the old value

**Comment by Brian-Watson** [comment]
@patrickgallagher Are you using UIAutomator or UIAutomator2?  Can you upgrade to Appium 1.6.4 and try it again.  The older UIAutomator has always been "flakey" for me when it comes to clearing text fields.  Since upgrading to UIAutomator2, it has been much better.

`desiredCapabilities.setCapability("automationName", "uiautomator2");
`

**Comment by patrickgallagher** [comment]
Thank you that has fixed the issue
