### ISSUE TITLE
[iOS] SessionNotCreatedError: A new session could not be created. Details: Appium's IosDriver does not support xcode version 8.3.1. Apple has deprecated UIAutomation. Use the "XCUITest" automationName capability instead.

### ISSUE THREAD

**Issue by jaredgilmore** [appium/appium#8222]
## The problem

When trying to run the inspector tool in Appium I get the above error in my appium server logs as it is failing to create a session to inspect my app I have built out. I have added the `custom server flag`: --automation-name "XCUITest" in my Appium.app but that didn't seem to help. 

## Environment

* Appium version: 1.6.4-beta.2
* Desktop OS/version used to run Appium: macOS Sierra version 10.12.2
* Node.js version: v6.9.4 
* Mobile platform/version under test: iPhone 6 Plus (Platform Version 9.3)
* Appium CLI or Appium.app|exe: Appium.app

## Link to Appium logs
[GIST](https://gist.github.com/jaredgilmore/4e5ef9fc588765c71780e0ef927f2f6e)

**Comment by Brian-Watson** [comment]
Are you using the latest Appium Desktop from here...

https://github.com/appium/appium-desktop

**Comment by jaredgilmore** [comment]
Hello @Brian-Watson , I'm not using appium-desktop, I am using the `Appium.app` which looks a bit different than the one you posted. Is that the one I should be using?

**Comment by mykola-mokhnach** [comment]
Appium.app is obsolete and not supported anymore. Please use Appium desktop.

**Comment by jaredgilmore** [comment]
Will go that route. Thank you!
