### ISSUE TITLE
driver.get_log("syslog") does not work

### ISSUE THREAD

**Issue by qakapil** [appium/appium#8223]
## The problem

I have noticed this issue in Appium v1.6.4 and v1.6.4beta2. In my test suite after every test I get device logs with driver.get_log("syslog"). This was working fine till v1.6.4beta however, since beta2 after first couple of tests driver.get_log("syslog") returns empty string.

Please note that this issue exists with iOS10 only. With iOS9 device Appium is returning syslog for all the tests.

Could this be because iOS10 logs are very huge and Appium internally has a limit to the size of device logs it can handle ? 

## Environment

* Appium version - Appium v1.6.4 and v1.6.4beta2.
* Last Appium version that did not exhibit the issue : v1.6.4beta
* Desktop OS/version used to run Appium: mac Sierra
* Node.js version (unless using Appium.app|exe): 6.7
* Mobile platform/version under test: iOS10
* Real device or emulator/simulator: Real

**Comment by dpgraham** [comment]
Can you provide the server logs?

**Comment by qakapil** [comment]
here are the device logs - https://gist.github.com/qakapil/06d1f774f839745631d48da640aacf99

Seems this issue has already been acknowledged and fix is on the way...
