### ISSUE TITLE
appium-xcuitest-driver TypeError: Cannot read property 'sendCommand' of undefined

### ISSUE THREAD

**Issue by mantisbayne** [appium/appium#8225]
## The problem

I keep getting this error when running a test using XCUITest for iOS 10.2. The same test works for Android, so I would think it would work for iOS, with the correct XCUITest locator.  I posted this on the discussion board, so I apologize for the repetition.  I am thinking it might be an actual issue with XCUITest and the environment I'm using (XCode 8.2)

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS Sierra, iOS Simulator
* Node.js version (unless using Appium.app|exe): 6.10.1
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium logs
https://gist.github.com/mantisbayne/5b002d296629de92d769102a010cb8cd

## Code To Reproduce Issue [ Good To Have ]
Test:
```javascript
  it('should have an element', (done) => {
    locateElement(driver, 'class name', 'XCUIElementTypeStaticText').then((element) => {
      driver.deviceDriver.elementDisplayed(element.ELEMENT).then((isDisplayed) => {
        expect(isDisplayed).toBe(true);
        done();
      });
    });
  });
```
```javascript
export async function locateElement(driver: Driver, strategy: string, element: string) {
  const elements = await driver.deviceDriver.findElements(strategy, element);
  return elements[0];
}
```

**Comment by imurchie** [comment]
What is `driver.deviceDriver.elementDisplayed` doing? I'm trying to figure out where `sendCommand` might be (it's not in the xcuitest driver).

**Comment by mantisbayne** [comment]
@imurchie driver.deviceDriver is my initialization of the driver.  I abstracted it out to a class so that I could handle some extra logic and keep things clean. I thought I could use the same methods as IosDriver (probably didn't really understand the docs for appium-xcuitest-driver). Back to the point though, elementDisplayed isn't implemented in xcuitest driver for sure.  sendCommand is called in the IosDriver implementation, so maybe it is called there?  Anyway, I was able to get this to work using .getAttribute('visible', element.ELEMENT) instead of .elementDisplayed().  If you have any ideas about why that works and .elementDisplayed() doesn't, let me know and thanks for your help! Maybe implementing elementDisplayed in XCUITest would be a good feature to have, but I'm still very new to Appium, so I'm not sure.

**Comment by imurchie** [comment]
Are you using the driver (`appium-xcuitest-driver`) on its own? These are meant to be wired into the Appium server. Using them directly means you lose the primary benefits of the system (scalability, etc.).

**Comment by mantisbayne** [comment]
Ok, I will look into different approaches, because my code does seem to initialize an AndroidDriver or XCUITest driver based on the desired capabilities I pass in.  It's been more of a challenge to develop a solid framework, because my team is requiring that I use the same libraries and frameworks as them, and they chose to develop a NativeScript app and use Jasmine syntax for tests.  It's a work in progress.  If you know of any examples, I would love to see them.  Thanks for the tips!

**Comment by imurchie** [comment]
I presume that means you are writing in JavaScript? This should be entirely possible using Appium as it is intended. You can see some examples in JavaScript (using mocha, which is pretty close) here: https://github.com/imurchie/basic-js-test

For installing Appium as a whole, you can begin here: https://github.com/appium/appium#quick-start

**Comment by mantisbayne** [comment]
Yes, using JS.  I did see some examples using Chai/Mocha and wd, but they were so old and the code was messy, so thanks for pointing me in the right direction! Appium is already installed, so I think I have enough to get going.  Thanks again!

**Comment by mantisbayne** [comment]
@imurchie I was able to get this working pretty quickly and everything is looking good so far.  Thanks again

**Comment by imurchie** [comment]
Awesome!
