### ISSUE TITLE
WinAppDriver kept opened when running UWP tests

### ISSUE THREAD

**Issue by yaphatak** [appium/appium#8228]
If we keep running test for several hours. I see that lots of WinAppdriverAgents running in background.
This leads to too many ports are engaged and also eating memory and CPU

Appium Version 1.6.3
OS: Windows 10

**Comment by dpgraham** [comment]
Sorry for not getting back on this.

Do you have Appium logs for this?

**Comment by jlipps** [comment]
closed due to inactivity
