### ISSUE TITLE
'Unknown app_id..." Error causes Webkit remote debugger socket disconnection

### ISSUE THREAD

**Issue by Hiran47** [appium/appium#8232]
## The problem

When running my tests written for an iOS application (in its WEBVIEW context), the Webkit remote debugger gets disconnected while login in to the application. There is loading animator that appears just after I tap the login button, and that's where the issue happens.

## Environment

* Appium version: 1.6.4
* Desktop OS/version: Mac OS 10.12.4
* Node.js version: 6.9.1
* Mobile platform/version: iOS 10.3.1
* Real device: iPad Air

## Link to Appium logs

Error segment from Appium Server Log:
> [IWDP] [ 'Unknown app_id PID:319' ]
[IWDP] [ 'Invalid message _rpc_applicationSentListing: <dict>',
  '\t<key>WIRApplicationIdentifierKey</key>',
  '\t<string>PID:319</string>',
  '\t<key>WIRListingKey</key>',
  '\t<dict>',
  '\t\t<key>5</key>',
  '\t\t<dict>',
  '\t\t\t<key>WIRPageIdentifierKey</key>',
  '\t\t\t<integer>5</integer>',
  '\t\t\t<key>WIRTitleKey</key>',
  '\t\t\t<string>JSContext</string>',
  '\t\t\t<key>WIRTypeKey</key>',
  '\t\t\t<string>WIRTypeJavaScript</string>',
  '\t\t</dict>',
  '\t</dict>',
  '</dict>' ]
[debug] [RemoteDebugger] WebKit remote debugger socket disconnected
[MJSONWP] Encountered internal error running command: Error: Error while executing atom: Remote debugger is not connected
    at XCUITestDriver.callee$0$0$ (../../../lib/commands/web.js:78:11)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/140467a9-91e8-4398-b321-a71bf7c4443b/element 500 798 ms - 231 
[debug] [XCUITest] Connection to WDA timed out
[debug] [iProxy] recv failed: Operation not permitted

[Appium Server Log (Full)](https://gist.github.com/Hiran47/7a29d5a207afff0676aa805fe004c0cc)

## Additional Info

My Capabilities:
`capabilities.setCapability(MobileCapabilityType.UDID, "0d82b8ca6683a099f767d6ac1aed23c8845b29f1");
capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPad");
capabilities.setCapability(IOSMobileCapabilityType.BUNDLE_ID, "com.abccorp.xxx");
capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "10.3.1");
capabilities.setCapability(MobileCapabilityType.PLATFORM_NAME, "iOS");
capabilities.setCapability("xcodeConfigFile", System.getProperty("user.dir") + "/src/main/resources/Config.xcconfig");
capabilities.setCapability(MobileCapabilityType.NEW_COMMAND_TIMEOUT, 3000);
capabilities.setCapability(MobileCapabilityType.FULL_RESET, false);
capabilities.setCapability(MobileCapabilityType.NO_RESET, false);
capabilities.setCapability(MobileCapabilityType.AUTO_WEBVIEW, true);
capabilities.setCapability("autoDismissAlerts", true);
capabilities.setCapability("startIWDP", true);`

**Comment by mykola-mokhnach** [comment]
This looks more like an application crash, because IWDP was not able to detect application process id:

> [debug] [BaseDriver] Waited for 279 ms so far
> [IWDP] [ 'Unknown app_id PID:319' ]
> [IWDP] [ 'Invalid message _rpc_applicationSentListing: <dict>',

**Comment by Hiran47** [comment]
@mykola-mokhnach Not really. The application is running smoothly as expected every time, but Appium logs this for some reason. It happens every time when the Loading animator screen appears after my test tap on login button.

**Comment by Hiran47** [comment]
Following has solved the issue for me:

```
brew update
brew reinstall --HEAD libimobiledevice
brew reinstall -s ios-webkit-debug-proxy
```
