### ISSUE TITLE
How to build source code

### ISSUE THREAD

**Issue by cool-firer** [appium/appium#8233]
I run appium through source code from the instruction:
https://github.com/appium/appium/blob/master/docs/en/contributing-to-appium/appium-from-source.md
I modified some code, how do i do to make that work?

**Comment by mykola-mokhnach** [comment]
```
gulp transpile
```

to transplie modified sources from lib to bin

```
gulp once
```

to perform verification with lint, transplie code and run unit tests

```
gulp watch
```

to watch the source for modifications and check/transpile it on the fly

**Comment by cool-firer** [comment]
@mykola-mokhnach 
I got error while run gulp watch:
D:\appium\node_modules\appium>gulp watch
[16:14:24] Using gulpfile D:\appium\node_modules\appium\gulpfile.js
[16:14:24] Starting 'watch'...
[16:14:24] Finished 'watch' after 3.28 ms
Error: spawn D:\appium\node_modules\appium\node_modules\.bin\gulp ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by mykola-mokhnach** [comment]
I never tried this on Windows. ENOENT means "No such folder"

**Comment by dpgraham** [comment]
Looks like a bug in the Path construction.

`D:\appium\node_modules\appium\node_modules.bin\gulp`

should be

`D:\appium\node_modules\appium\node_modules\.bin\gulp`

**Comment by dpgraham** [comment]
@cool-firer Why are you running it from `D:\appium\node_modules\appium` and not `D:\appium`?

**Comment by dpgraham** [comment]
@cool-firer I'm able to reproduce the issue.

Are you running this from 'git bash' or 'powershell'?

I think the problem may be that it's detecting the OS as windows and constructing the path the windows way (`D:\appium\node_modules\appium\node_modules\.bin\gulp`) but should actually be doing it the Bash way (`/d/appium/node_modules/appium/node_modules/.bin/gulp`)

**Comment by dpgraham** [comment]
Found the problem: https://github.com/nodejs/node-v0.x-archive/issues/2318#issuecomment-7470062

We need to set `{shell: true}` for calls to spawn.

**Comment by dpgraham** [comment]
Fix published to 1.4.13

https://www.npmjs.com/package/appium-gulp-plugins

@cool-firer Can you try re-installing your npm modules and running gulp again? `rm -rf node_modules && npm install`. If it doesn't work for you, let me know and I'll re-open the ticket.
