### ISSUE TITLE
Appium 1.6.4 Test run fails with "[UiAutomator2] Unable to remove port forward " on android devices.

### ISSUE THREAD

**Issue by dc-ikozlov** [appium/appium#8234]
## The problem

All my android test runs fail with code 500 error from appium server after updating appium CLI from 1.6.3. to 1.6.4. On appium 1.6.3 it still works fine.
## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.3
* Desktop OS/version used to run Appium: macOS 10.12.4
* Node.js version (unless using Appium.app|exe): v6.8.1
* Mobile platform/version under test: Android 5.0
* Real device or emulator/simulator: real devices
* Appium CLI or Appium.app|exe: CLI

## Details

Something wrong is going on on uiatomator2 session creation:
`[debug] [UiAutomator2] Deleting UiAutomator2 session `
`[debug] [UiAutomator2] Deleting UiAutomator2 server session `
`...`
`[UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/Users/i.kozlov/Library/Android/sdk/platform-tools/adb -P 5037 -s 551f5572 forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''`

Also when I manually remove appium-uiautomator2-server apps from the device, appium doesn't install it  itself. "Unable to remove port forward.." error remains the same. 

## Link to Appium logs

https://gist.github.com/dc-ikozlov/ab69a041755b7dd4cc05fd7e1da68beb

**Comment by sravanmedarapu** [comment]
@dc-ikozlov not able to replicate the issue, can you please try with v1.6.4-beta.2 and share the appium server and adb logs if issue replicating?

**Comment by dc-ikozlov** [comment]
@sravanmedarapu 
Same error on v1.6.4-beta.2 and v1.6.4-beta:
https://gist.github.com/dc-ikozlov/a957f706c3c9f836a580cbe2fe7d1893
https://gist.github.com/dc-ikozlov/bc79e5232410a8030cf35d1e2c964923

**Comment by sravanmedarapu** [comment]
`[MJSONWP] Encountered internal error running command: Error: Command '/Users/i.kozlov/Library/Android/sdk/platform-tools/adb unroot' exited with code 1
`
https://gist.github.com/dc-ikozlov/a957f706c3c9f836a580cbe2fe7d1893#file-gistfile1-txt-L113


@imurchie running [`adb unroot`](https://github.com/appium/appium-adb/blob/master/lib/tools/system-calls.js#L508) throwing below errror, I think we should catch and ignore the exception.

`adb: unable to connect for unroot: closed`

**Comment by HlebHalkouski** [comment]
Have same issue as [UIAutomator 2](https://gist.github.com/HlebHalkouski/de9f0e9f927993cb8ca9e1e894ba6a31) and [UIAutomator 1](https://gist.github.com/HlebHalkouski/0c0784430694e2e923e2758b35d05a15).

**Comment by imurchie** [comment]
A fix is on its way. Though I'm not convinced it is actually going to fix the port forwarding problem.

**Comment by sravanmedarapu** [comment]
In [catch](https://github.com/appium/appium-uiautomator2-driver/blob/master/lib/driver.js#L166) block we are removing port forwarding, as port not forwarded it is throwing exception and we are just logging the exception. but the actual reason for falling in catch block is `adb unroot`

**Comment by imurchie** [comment]
`appium-adb@2.17.0` has been published which will log the error and continue. Update and hopefully it is solved!

**Comment by aaronmagi** [comment]
@imurchie is there a fix for this?  We are seeing it as shown below.  This will then cause the test to fail when running on multiple devices.

`2017-11-09 22:21:47:420 - info: [debug] [ADB] Removing forwarded port socket connection: 8200 

2017-11-09 22:21:47:421 - info: [debug] [ADB] Running '/opt/android-sdk-linux/platform-tools/adb' with args: ["-P",5037,"-s","f6c8483d","forward","--remove","tcp:8200"]

2017-11-09 22:21:47:430 - info: [debug] [ADB] Running '/opt/android-sdk-linux/platform-tools/adb' with args: ["-P",5037,"-s","f6c8483d","forward","--remove","tcp:8200"]

**2017-11-09 22:21:47:438 - warn: [UiAutomator2] Unable to remove port forward 'Error executing adbExec. Original error: 'Command '/opt/android-sdk-linux/platform-tools/adb -P 5037 -s f6c8483d forward --remove tcp\:8200' exited with code 1'; Stderr: 'error: listener 'tcp:8200' not found'; Code: '1''**

2017-11-09 22:21:47:439 - error: [MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: connect ECONNREFUSED 127.0.0.1:8200
    at JWProxy.proxy$ (/opt/mcellblock/adbservice/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:152:13)
    at tryCatch (/opt/mcellblock/adbservice/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/mcellblock/adbservice/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/opt/mcellblock/adbservice/node_modules/babel-runtime/regenerator/runtime.js:100:21)`

**Comment by mali5590** [comment]
issue resolved by removing udid from the code
