### ISSUE TITLE
Cannot get 'instance' attribute of Android Web View element

### ISSUE THREAD

**Issue by poorvikamahesh** [appium/appium#8235]
Hello,

I am trying to automate an hybrid application and need the instance attribute of a particular element.

But when i use the below code, I get an error msg - "Element does not have the 'instance' attribute"

`driver.getAttribute("instance");`

When I use appium inspector to locate the element, the instance attribute is visible.

Kindly Help

FYI
Appium Version - 1.6.4
Android Version - 6.0.1
<img width="1437" alt="screen shot 2017-04-12 at 4 30 07 pm" src="https://cloud.githubusercontent.com/assets/10269471/24954640/dbd0fb8e-1f9d-11e7-85ee-b8ac91d9a8b4.png">

**Comment by dpgraham** [comment]
You need to locate the element first and then call `getAttribute('instance')` on the element will get the value of the `instance` attribute.

**Comment by poorvikamahesh** [comment]
@dpgraham 
Apologies. I have typed the wrong code.
I have used find element and it returns a web element and then I am trying to get attribute.

**Comment by dpgraham** [comment]
Can you call `driver.getPageSource` (or whatever the 'get source' method is for the client you are using) before you call `getAttribute` and verify that the 'instance' attribute is in the XML?

**Comment by poorvikamahesh** [comment]
@dpgraham 
This was what was returned for the element highlighted in the image -

`	<android.view.View index="0" text="" class="android.view.View" package="com.philips.sleepmapper.root" content-desc="How do I correct my Login username?›" checkable="false" checked="false" clickable="true" enabled="true" focusable="false" focused="false" scrollable="false" long-clickable="false" password="false" selected="false" bounds="[0,596][678,680]" resource-id="" instance="12"/>
</android.view.View>`

**Comment by xueying-tan** [comment]
I have the same issue. can not get some attributes that apparently exist.

**Comment by mykola-mokhnach** [comment]
Webview-related operations should not be executed in native context.  Also, UIAutomator1 is considered obsolete
