### ISSUE TITLE
npm ERR! extraneous: nan@2.6.1 /usr/local/lib/node_modules/appium/node_modules/nan

### ISSUE THREAD

**Issue by vikramvi** [appium/appium#8236]
## The problem

- Uninstalled existing appium beta and installed latest version
- npm -g --depth=0 list 
  this command throws below error

/usr/local/lib
├── app-inspector@1.2.18
├── appium@1.6.4
├── ios-deploy@1.9.0
└── npm@4.4.4

npm ERR! extraneous: nan@2.6.1 /usr/local/lib/node_modules/appium/node_modules/nan

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 1.6.4 Beta
* Desktop OS/version used to run Appium: Mac
* Node.js version (unless using Appium.app|exe):  v7.9.0 , npm 4.4.4
* Mobile platform/version under test: NA 
* Real device or emulator/simulator: NA
* Appium CLI or Appium.app|exe: CLI

## Details

NA

## Link to Appium logs

NA

## Code To Reproduce Issue [ Good To Have ]

NA

**Comment by imurchie** [comment]
This seems like an npm problem. `nan` is used by `fsevents`, but in their gyp build (https://github.com/strongloop/fsevents/blob/master/binding.gyp#L16).

**Comment by imurchie** [comment]
Perhaps https://github.com/npm/npm/issues/15727

**Comment by mykola-mokhnach** [comment]
Try to downgrade npm. Closing as non Appium-related issue

**Comment by JESii** [comment]
GM, @imurchie...

I ran into this same problem and have tried three different versions of node and they all give the same error:
`pm ERR! extraneous: nan@2.6.1 /usr/local/lib/node_modules/appium/node_modules/nan`
This happens with node v7.10.0, v7.7.4, and now v6.10.3.

It's definitely related to fsevents:
```
   510 │ ├── UNMET OPTIONAL DEPENDENCY fsevents@1.x
   511 │ ├── lodash@4.17.4
   512 │ ├── nan@2.6.1 extraneous
```
but didn't occur previously, and I would have thought that v6.10.3 would be old enough to get around the problem.

Also, this part of the tree is for `appium@v1.6.4`; I used to be on `appium@v1.6.4-beta` which worked OK.

**_So, I upgraded to appium@1.6.5-beta and the problem went away._** 

This was on node@6.10.3; I then tried node@7.4.4 and node@7.10.0 and they all worked just fine wth no ERR.

**Comment by vikramvi** [comment]
@JESii can you please clarify from where you got 1.6.5-beta, as per https://github.com/appium/appium/releases 1.6.4 is the latest version

**Comment by imurchie** [comment]
@vikramvi `npm uninstall -g appium && npm install -g appium@beta`

**Comment by vikramvi** [comment]
@imurchie I'm just curious why beta release is not shown under github or https://www.npmjs.com/package/appium, where can I refer to release notes for beta release ?

**Comment by imurchie** [comment]
We generally don't put the release up for beta versions. The changelog is not detailed either, since most of the work happens in subpackages and it would get out of sync.

What we do have is here: https://github.com/appium/appium/blob/master/CHANGELOG.md#changes-in-version-165-beta-from-164

**Comment by vikramvi** [comment]
Thanks for detailed clarification @imurchie
