### ISSUE TITLE
[XCode 8.3 - iOS 10.3.1] Unable to launch WebDriverAgentRunner

### ISSUE THREAD

**Issue by dmkone** [appium/appium#8238]
WebdriverAgentRunner installs on the phone opens up and then crashes. Tried to reinstall all things, but error is the same.

I have signing certificate and I'm able to install .ipa file from command line or xcode, build from xcode succeeded

* Appium 1.6.4
* Real device, iPhone 7 . 10.3.1
* Xcode 8.3

Before, when I haven't signing certificate I was not able to install .ipa file and I received error 65, but now this problem is fixed and everything should work..Appium is able to install application, but after that it runs into problem with WDA

Logs :
**xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id= <myudid>' test**
https://gist.github.com/dmkone/52e5b305916e4f22cb37d333c6d853ce

Appium logs : I do not understand why appium is still showing error 65, appium is able to install .ipa file.
https://gist.github.com/dmkone/1458cceb99919a1cbd6c744c3fb53fef

**Comment by mykola-mokhnach** [comment]
> Library not loaded: @rpath/XCTest.framework/XCTest

I think this error has been already discussed earlier somewhere. Try to search for matches

**Comment by dmkone** [comment]
I tried to fix this issue by linking to XCTest.framework in WebDriverAgent.xcodeproj under WebDriverAgentLib -> Build Phases -> Link Binary With Libraries, and WebDriverAgentRunner -> Build Phases -> Link Binary With Libraries. But this didn't solve my problem.

**Comment by imurchie** [comment]
Get the latest Xcode. This was happening to me but stopped with that update.

**Comment by dmkone** [comment]
I've reinstalled all things again, also xcode was reinstalled - problem is solved now. Thank You!
