### ISSUE TITLE
Unable start new session with Appium Desktop

### ISSUE THREAD

**Issue by Katipalli** [appium/appium#8243]
## The problem

While trying to start new session getting below error:

[MJSONWP] Encountered internal error running command: Error: Could not determine iOS SDK version: Command 'xcrun --sdk iphonesimulator --show-sdk-version' exited with code 1: xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: unable to lookup item 'SDKVersion' in SDK 'iphonesimulator

## Environment

* Appium Desktop 1.0
* MAC 10.11
* Mobile platform/version : iOS 10.2
* Real device or emulator/simulator: same issue with both
* XCODE: 8.2

JSON Representation:
{
  "platformName": "iOS",
  "platformVersion": "10.2",
  "deviceName": "iPhone Simulator",
  "app": "XXXXXX",
  "noReset": true
}

Please help me to resolve this issue

**Comment by mykola-mokhnach** [comment]
Make sure you have simulator sdk installed and you can run 10.2 Simulator from Xcode.

**Comment by Katipalli** [comment]
I do have other issues, but this one resolved
