### ISSUE TITLE
Errors Encountered Automating Google Sign On (Appium.app & Appium-Python)

### ISSUE THREAD

**Issue by mwalla210** [appium/appium#8244]
## The problem

Inspector for Appium GUI incorrectly highlights Google Sign On process in React Native application, tap unresponsive, and Appium-Python-Client is unable to `set_value()` for parts of process.

## Environment

* Desktop OS/version used to run Appium: Mac 10.12.4
* Mobile platform/version under test: Android
* Real device or emulator/simulator: Nexus 5X running 6.0.0
* Application type: React Native app
* Appium CLI or Appium.app|exe: Appium.app (1.5.3) & Appium-Python-Client (0.24)

## Details

GUI highlighting in Inspector is incorrect/missing for Password EditText, Sign In button, and Forgot Password View.
![screen shot 2017-04-12 at 2 20 03 pm](https://cloud.githubusercontent.com/assets/18332047/24973028/542a4fc6-1f8b-11e7-9728-a38487c9d21f.png)
![screen shot 2017-04-12 at 2 20 11 pm](https://cloud.githubusercontent.com/assets/18332047/24973033/578dc206-1f8b-11e7-9b5a-d7de658a11cc.png)
![screen shot 2017-04-12 at 2 20 18 pm](https://cloud.githubusercontent.com/assets/18332047/24973035/5a28b8fe-1f8b-11e7-88c3-29b99ecc3591.png)

The Inspector is unsuccessful on tap for:
* Sign in button
* Forgot my password view

Despite this, Appium-Python-Client _is_ able to 
* Script an entry into the Email EditText (prior screen)
* Click the "Next" button (prior screen)

```
# Enter email
email = self.driver.find_element_by_xpath("//android.view.View[4]/android.widget.EditText[1]")
self.assertEqual(email.get_attribute("name").strip(), "Email or phone")
self.driver.set_value(email, emailstr)
button = self.driver.find_element_by_xpath("//android.view.View[4]/android.widget.Button[1]")
self.assertEqual(button.get_attribute("name").strip(), "Next")
button.click()
self.driver.implicitly_wait(60)
```

It _fails_ on:
* Script an entry into the Password EditText (no text entered into field and nothing printed)
  * I have tried a few varieties of xpath including shorter ones like I use in other scripts
* Click the "Sign in" button (button appears to be correctly identified in script - assertEqual does not fail - but `click()` execution does nothing)

```
# Enter password
pw = self.driver.find_element_by_xpath("//android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.view.ViewGroup[1]/android.view.ViewGroup[1]/android.view.ViewGroup[2]/android.webkit.WebView[1]/android.webkit.WebView[1]/android.view.View[4]/android.widget.EditText[1]")
self.driver.set_value(pw, pwstr)
print(pw.get_attribute("text"))
```
```
button = self.driver.find_element_by_xpath("//android.view.View[4]/android.widget.Button[1]")
self.assertEqual(button.get_attribute("name").strip(), "Sign in")
button.click()
```

## Link to Appium logs

Sample of trying to click "Sign in" in Appium.app Inspector
https://gist.github.com/mwalla210/9a730f97086a2ecd875d0d175a91e8f8
Trying to find the Password EditText
https://gist.github.com/mwalla210/f3797dbbc8d51d115c8844ab2c029f9f

**Comment by mykola-mokhnach** [comment]
Appium.app is unsupported. Try it with Appium 1.6.4-stable

**Comment by imurchie** [comment]
Supported GUI is https://github.com/appium/appium-desktop/releases

**Comment by mwalla210** [comment]
This is still a problem utilizing Appium installed via `npm -g` (v1.6.4). 
I ran `appium` and then began my test file with a Genymotion simulator open. 

After updating to the new GUI version, issue is still experienced. I would upload new screenshots but I don't know they'll help much. Issue is same as before - email EditText & Next button are fine, but password EditText and Sign in button are not. I additionally tried to identify the Sign in button with different code, but despite requesting a click, nothing happens.
```
button = self.driver.find_element_by_accessibility_id("Sign in")
button.click()
```
