### ISSUE TITLE
Can't double-tap an element in iOS

### ISSUE THREAD

**Issue by VivaLosDoyers** [appium/appium#8245]
I can't double-tap an element.

When I try, I get this error:

```
[1] pry(main)> Appium::TouchAction.new.double_tap(find_element(id: 'DOUBLE-TAP TO ZOOM')).perform
NoMethodError: private method `select' called for #<Selenium::WebDriver::Element:0x007ff6dee10fc8>
from /Users/hooray/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/appium_lib-9.3.7/lib/appium_lib/device/touch_actions.rb:111:in `double_tap'
```

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Appium: macOS 10.12
* Node.js version (unless using Appium.app|exe): 7.8.0
* Mobile platform/version under test: iOS 10.3
* Real device or emulator/simulator: sim
* Appium CLI or Appium.app|exe: CLI

**Comment by VivaLosDoyers** [comment]
As a workaround, I'm doing:

`execute_script 'mobile: doubleTap', element: find_element(id: 'DOUBLE-TAP TO ZOOM')`

But I'm not clear on why this necessary.

**Comment by mykola-mokhnach** [comment]
Please report this issue to ruby client project
@KazuCocoa FYI


Regarding

```ruby
execute_script 'mobile: doubleTap', element: find_element(id: 'DOUBLE-TAP TO ZOOM')
```

It will not work, since element id is expected as the second argument, which is a hexadecimal hash. Not sure how to extract it in ruby client though.

**Comment by KazuCocoa** [comment]
Thanks! > FYI

How about the following command? You should set arguments with hash @VivaLosDoyers 

```
Appium::TouchAction.new.double_tap(element: find_element(id: 'DOUBLE-TAP TO ZOOM')).perform
```

**Comment by VivaLosDoyers** [comment]
find_element returns the hash...right?

@KazuCocoa I tried
`Appium::TouchAction.new.double_tap(element: find_element(id: 'DOUBLE-TAP TO ZOOM')).perform`

However my app under test did not respond to it as if it was a double-click, even though I got a successful return:
```
[7] pry(main)> Appium::TouchAction.new.double_tap(element: find_element(id: 'DOUBLE-CLICK TO ZOOM').perform
#<Appium::TouchAction:0x007f9248a48990 @actions=[]>
```

Can you tell me what the delay is between the two taps? I'm wondering if it is either too long or too short.

**Comment by mykola-mokhnach** [comment]
You cannot set the delay there. It simply invokes XCUIElement's doubleTap method, which does not not contain any arguments.

**Comment by KazuCocoa** [comment]
@VivaLosDoyers 

> find_element returns the hash...right?

No, `find_element` return Selenium::WebDriver::Element object and `Selenium::WebDriver::Element#ref` returns an `id` for the element.


1. `Appium::TouchAction.new.double_tap` stores `doubleTap` command in `@actions`.[code](https://github.com/appium/ruby_lib/blob/80f80715dcee6de968700ece40894222af41579a/lib/appium_lib/device/touch_actions.rb#L113)

```
action = Appium::TouchAction.new.double_tap(element: find_element(id: 'DOUBLE-CLICK TO ZOOM')
```
2. `perform` [code](https://github.com/appium/ruby_lib/blob/80f80715dcee6de968700ece40894222af41579a/lib/appium_lib/device/touch_actions.rb#L178
) send `@actions` commands to appium server [code](https://github.com/appium/ruby_lib/blob/4ae081549cf1aad89c6d304fc8a8b9499db96160/lib/appium_lib/common/command.rb#L46)
```
action.perform
```

The behaviour depends on server side. ( as mykola-mokhnach mentioned.)
