### ISSUE TITLE
Update to Appium desktop 1.0.0 Observing MyTestApp closes continuously after splash screen

### ISSUE THREAD

**Issue by chaitanyadeshmukh** [appium/appium#8246]
## Hangup on Appium Desktop Version 1.0.0 (1.0.0) UI  
Hello Team,

I have updated to 1.0.0 from beta with below details in desiredCapabilities of Appium UI 
{
  "platformName": "iOS",
  "platformVersion": "9.3",
  "deviceName": "iPhone Simulator",
  "app": my_app_path,
  "automationName": "XCUITest"
}
and observed my app is getting close continuously after Splash screen.

Below are the logs
===============================================================

The server is running
Start New SessionStop Server
[JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"4CD60F82-D3F3-40F3-B17C-AACCC743F609","status":0}
[BaseDriver] Event 'orientationSet' logged at 1492061210031 (22:26:50 GMT-0700 (MST))
[Appium] New XCUITestDriver session created successfully, session e0d38b7e-319f-40e6-a929-06922e7bc9b8 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1492061210033 (22:26:50 GMT-0700 (MST))
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"app":"/Users/user/Documents/maWorkspace/apptestApp.app","automationName":"XCUITest","deviceName":"iPhone Simulator","platformName":"iOS","platformVersion":"9.3","newCommandTimeout":0,"connectHardwareKeyboard":true,"udid":"9AE76A4D-FE19-4D73-B6A5-5B813AB12A37"}
[HTTP] <-- POST /wd/hub/session 200 194551 ms - 532 
[Appium] Welcome to Appium v1.6.4
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/user/Documents/maWorkspace/apptestApp.app","automationName":"XCUITest","deviceName":"iPhone Simulator","platformName":"iOS","platformVersion":"9.3","newCommandTimeout":0,"connectHardwareKeyboard":true}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"app":"/Users/user/Documents/maWorkspace/apptestApp.app","automationName":"XCUITest","deviceName":"iPhone Simulator","platformName":"iOS","platformVersion":"9.3","newCommandTimeout":0,"connectHardwareKeyboard":true},null,null,null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1492061263935 (22:27:43 GMT-0700 (MST))
[Appium] Creating new XCUITestDriver (v2.27.2) session
[Appium] Capabilities:
[Appium]   app: '/Users/user/Documents/maWorkspace/apptestApp.app'
[Appium]   automationName: 'XCUITest'
[Appium]   deviceName: 'iPhone Simulator'
[Appium]   platformName: 'iOS'
[Appium]   platformVersion: '9.3'
[Appium]   newCommandTimeout: 0
[Appium]   connectHardwareKeyboard: true
[XCUITest] XCUITestDriver version: 2.27.2
[BaseDriver] Session created with session id: 6bf82fba-2b17-42b0-bba5-ed3baa7861b7
[XCUITest] Xcode version set to '8.3.1' (tools v8.3.0.0.1.1490382677)
[XCUITest] iOS SDK Version set to '10.3'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1492061264378 (22:27:44 GMT-0700 (MST))
[XCUITest] Changing deviceName from 'iPhone Simulator' to 'iPhone 6'
[iOSSim] Constructing iOS simulator for Xcode version 8.3.1 with udid '9AE76A4D-FE19-4D73-B6A5-5B813AB12A37'
[XCUITest] Determining device to run tests on: udid: '9AE76A4D-FE19-4D73-B6A5-5B813AB12A37', real device: false
[BaseDriver] Using local app '/Users/user/Documents/maWorkspace/apptestApp.app'
[BaseDriver] Event 'appConfigured' logged at 1492061264754 (22:27:44 GMT-0700 (MST))
[XCUITest] Checking whether app '/Users/user/Documents/maWorkspace/apptestApp.app' is actually present on file system
[XCUITest] App is present
[iOS] Getting bundle ID from app '/Users/user/Documents/maWorkspace/apptestApp.app': 'com.myapp.output.development.apptest'
[XCUITest] Setting 'connectHardwareKeyboard' Simulator option to 'on'
[BaseDriver] Event 'resetStarted' logged at 1492061264757 (22:27:44 GMT-0700 (MST))
[XCUITest] Not scrubbing third party app in anticipation of uninstall
[BaseDriver] Event 'resetComplete' logged at 1492061265084 (22:27:45 GMT-0700 (MST))
[iOSLog] Starting iOS 9.3 simulator log capture
[iOSLog] System log path: /Users/user/Library/Logs/CoreSimulator/9AE76A4D-FE19-4D73-B6A5-5B813AB12A37/system.log
[BaseDriver] Event 'logCaptureStarted' logged at 1492061265286 (22:27:45 GMT-0700 (MST))
[XCUITest] Setting up simulator
[iOS] No reason to set locale
[iOS] No iOS / app preferences to set
[XCUITest] Reset requested. Removing app with id 'com.myapp.output.development.apptest' from the device
[XCUITest] Simulator with udid '9AE76A4D-FE19-4D73-B6A5-5B813AB12A37' already booted
[BaseDriver] Event 'simStarted' logged at 1492061265639 (22:27:45 GMT-0700 (MST))
[XCUITest] Installing /Users/user/Documents/maWorkspace/apptestApp.app on Simulator with UUID '9AE76A4D-FE19-4D73-B6A5-5B813AB12A37'...
[XCUITest] The app has been installed successfully.
[BaseDriver] Event 'appInstalled' logged at 1492061268832 (22:27:48 GMT-0700 (MST))
[BaseDriver] Event 'wdaStartAttempted' logged at 1492061268839 (22:27:48 GMT-0700 (MST))
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing hanging processes
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGKILL'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=9AE76A4D-FE19-4D73-B6A5-5B813AB12A37 -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=9.3' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/AB6F3F3B-E552-49DF-B938-48502C169D17/Session-WebDriverAgentRunner-2017-04-12_222750-CyXscT.log
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iPhone OS\",\n      \"version\" : \"9.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"9.3\",\n      \"ip\" : \"192.168.1.6\"\n    },\n    \"build\" : {\n      \"time\" : \"Apr 12 2017 22:19:16\"\n    }\n  },\n  \"sessionId\" : \"850AB952-7195-4D71-B954-F18A90ABFEC7\",\n  \"status\" : 0\n}"
[XCUITest] WebDriverAgent running on ip '192.168.1.6'
[XCUITest] WebDriverAgent successfully started after 7242ms
[BaseDriver] Event 'wdaSessionAttempted' logged at 1492061276368 (22:27:56 GMT-0700 (MST))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.myapp.output.development.apptest","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":true,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"8F85EB89-F41D-40A0-B3D2-82F17589CD05","capabilities":{"device":"iphone","browserName":" ","sdkVersion":"9.3","CFBundleIdentifier":"local.pid.40815"}},"sessionId":"8F85EB89-F41D-40A0-B3D2-82F17589CD05","status":0}
[BaseDriver] Event 'wdaSessionStarted' logged at 1492061458004 (22:30:58 GMT-0700 (MST))
[XCUITest] Found WDA derived data folder: '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy'
[XCUITest] Setting '555' permissions to '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
[XCUITest] Found WDA derived data folder: '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-cvqckynzuuktkogfpkkkgyompmoj'
[XCUITest] Setting '555' permissions to '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-cvqckynzuuktkogfpkkkgyompmoj/Logs/Test/Attachments' folder
[XCUITest] Found WDA derived data folder: '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs'
[XCUITest] Setting '555' permissions to '/Users/user/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Attachments' folder
[BaseDriver] Event 'wdaPermsAdjusted' logged at 1492061458025 (22:30:58 GMT-0700 (MST))
[BaseDriver] Event 'wdaStarted' logged at 1492061458025 (22:30:58 GMT-0700 (MST))
[XCUITest] Setting initial orientation to 'PORTRAIT'
[JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/8F85EB89-F41D-40A0-B3D2-82F17589CD05/orientation] with body: {"orientation":"PORTRAIT"}
[JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"8F85EB89-F41D-40A0-B3D2-82F17589CD05","status":0}
[BaseDriver] Event 'orientationSet' logged at 1492061458173 (22:30:58 GMT-0700 (MST))
[Appium] New XCUITestDriver session created successfully, session 6bf82fba-2b17-42b0-bba5-ed3baa7861b7 added to master session list
[BaseDriver] Event 'newSessionStarted' logged at 1492061458177 (22:30:58 GMT-0700 (MST))
[MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"app":"/Users/user/Documents/maWorkspace/apptestApp.app","automationName":"XCUITest","deviceName":"iPhone Simulator","platformName":"iOS","platformVersion":"9.3","newCommandTimeout":0,"connectHardwareKeyboard":true,"udid":"9AE76A4D-FE19-4D73-B6A5-5B813AB12A37"}
[HTTP] <-- POST /wd/hub/session 200 194246 ms - 532 
[HTTP] --> POST /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/context {"name":"NATIVE_APP"}
[MJSONWP] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","6bf82fba-2b17-42b0-bba5-ed3baa7861b7"]
[XCUITest] Executing command 'setContext'
[iOS] Attempting to set context to 'NATIVE_APP'
[MJSONWP] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/context 200 13 ms - 76 
[HTTP] --> GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["6bf82fba-2b17-42b0-bba5-ed3baa7861b7"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/8F85EB89-F41D-40A0-B3D2-82F17589CD05/source] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"\\n\\n  \\n    \\n      \\n        \\n      <\\/XCUIElementTypeOther>\\n      
[MJSONWP] Responding to client with driver.getPageSource() result: "\n  \n    \n      \n        \n      \n      \n        \n      \n      
[HTTP] <-- GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/source 200 108 ms - 17440 
[HTTP] --> GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/screenshot {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["6bf82fba-2b17-42b0-bba5-ed3baa7861b7"]
[XCUITest] Executing command 'getScreenshot'
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAEDWlDQ1BJQ0MgUHJvZmlsZQAAOI2NVV1oHFUUPrtzZyMkzlNsNIV0qD8NJQ2TVjShtLp/3d02bpZJNtoi6GT27s6Yyc44M7v9oU9FUHwx6psUxL+3gCAo9Q/bPrQvlQol2tQgKD60+INQ6Ium65k7M5lpurHeZe58853vnnvuuWfvBei5qliWkRQBFpquLRcy4nOHj4g9K5CEh6AXBqFXUR0rXalMAjZPC3e1W99Dwntf2dXd/p+tt0YdFSBxH2Kz5qgLiI8B8KdVy3YBevqRHz/qWh72Yui3MUDEL3q44WPXw3M+fo1pZuQs4tOIBVVTaoiXEI/MxfhGDPsxsNZfoE1q66ro5aJim3XdoLFw72H+n23BaIXzbcOnz5mfPoTvYVz7KzUl5+FRxEuqkp9G/Ajia219thzg25abkRE/BpDc3pqvphHvRFys2weqvp+krbWKIX7nhDbzLOItiM8358pTwdirqpPFnMF2xLc1WvLyOwTAibpbmvHHcvttU57y5+XqNZrLe3lE/Pq8eUj2fXKfOe3pfOjzhJYtB/yll5SDFcSDiH+hRkH25+L+sdxKEAMZahrlSX8ukqMOWy/jXW2m6M9LDBc31B9LFuv6gVKg/0Szi3KAr1kGq1GMjU/aLbnq6/lRxc4XfJ98hTargX++DbMJBSiYMIe9Ck1YAxFkKEAG3xbYaKmDDgYyFK0UGYpfoWYXG+fAPPI6tJnNwb7ClP7IyF+D+bjOtCpkhz6CFrIa/I6sFtNl8auFXGMTP34sNwI/JhkgEtmDz14ySfaRcTIBInmKPE32kxyyE2Tv+thKbEVePDfW/byMM1Kmm0XdObS7oGD/MypMXFPXrCwOtoYjyyn7BV29/MZfsVzpLDdRtuIZnbpXzvlf+ev8MvYr/Gqk4H/kV/G3csdazLuyTMPsbFhzd1UabQbjFvDRmcWJxR3zcfHkVw9GfpbJmeev9F08WW8u...
[HTTP] <-- GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/screenshot 200 811 ms - 150442 
[HTTP] --> POST /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/element {"using":"xpath","value":"//*[1]//*[2]//*[2]//*[1]//*[1]//*[2]//*[1]//*[2]//*[1]//*[2]//*[1]"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["xpath","//*[1]//*[2]//*[2]//*[1]//*[1]//*[2]//*[1]//*[2]//*[1]//*[2]//*[1]","6bf82fba-2b17-42b0-bba5-ed3baa7861b7"]
[XCUITest] Executing command 'findElement'
[BaseDriver] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/8F85EB89-F41D-40A0-B3D2-82F17589CD05/element] with body: {"using":"xpath","value":"//*[1]//*[2]//*[2]//*[1]//*[1]//*[2]//*[1]//*[2]//*[1]//*[2]//*[1]"}
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"0CD24C06-7E54-4576-B9D6-E869606B775F","type":"XCUIElementTypeOther","label":null},"sessionId":"8F85EB89-F41D-40A0-B3D2-82F17589CD05","status":0}
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"0CD24C06-7E54-4576-B9D6-E869606B775F","type":"XCUIElementTypeOther","label":null}
[HTTP] <-- POST /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/element 200 528 ms - 165 
[HTTP] --> POST /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/element/0CD24C06-7E54-4576-B9D6-E869606B775F/click {}
[MJSONWP] Driver proxy active, passing request on via HTTP proxy
[XCUITest] Executing command 'proxyReqRes'
[JSONWP Proxy] Proxying [POST /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/element/0CD24C06-7E54-4576-B9D6-E869606B775F/click] to [POST http://localhost:8100/session/8F85EB89-F41D-40A0-B3D2-82F17589CD05/element/0CD24C06-7E54-4576-B9D6-E869606B775F/click] with body: {}
[JSONWP Proxy] Got response with status 200: {"status":0,"id":"0CD24C06-7E54-4576-B9D6-E869606B775F","value":"","sessionId":"8F85EB89-F41D-40A0-B3D2-82F17589CD05"}
[JSONWP Proxy] Replacing sessionId 8F85EB89-F41D-40A0-B3D2-82F17589CD05 with 6bf82fba-2b17-42b0-bba5-ed3baa7861b7
[HTTP] <-- POST /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/element/0CD24C06-7E54-4576-B9D6-E869606B775F/click 200 872 ms - 118 
[HTTP] --> GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["6bf82fba-2b17-42b0-bba5-ed3baa7861b7"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/8F85EB89-F41D-40A0-B3D2-82F17589CD05/source] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"\\n\\n  \\n    \\n      \\n        \\n      <\\/XCUIElementTypeOther>\\n      
[MJSONWP] Responding to client with driver.getPageSource() result: "\n  \n    \n      \n        \n      \n      \n        \n      \n      
[HTTP] <-- GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/source 200 100 ms - 17440 
[HTTP] --> GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/screenshot {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["6bf82fba-2b17-42b0-bba5-ed3baa7861b7"]
[XCUITest] Executing command 'getScreenshot'
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAEDWlDQ1BJQ0MgUHJvZmlsZQAAOI2NVV1oHFUUPrtzZyMkzlNsNIV0qD8NJQ2TVjShtLp/3d02bpZJNtoi6GT27s6Yyc44M7v9oU9FUHwx6psUxL+3gCAo9Q/bPrQvlQol2tQgKD60+INQ6Ium65k7M5lpurHeZe58853vnnvuuWfvBei5qliWkRQBFpquLRcy4nOHj4g9K5CEh6AXBqFXUR0rXalMAjZPC3e1W99Dwntf2dXd/p+tt0YdFSBxH2Kz5qgLiI8B8KdVy3YBevqRHz/qWh72Yui3MUDEL3q44WPXw3M+fo1pZuQs4tOIBVVTaoiXEI/MxfhGDPsxsNZfoE1q66ro5aJim3XdoLFw72H+n23BaIXzbcOnz5mfPoTvYVz7KzUl5+FRxEuqkp9G/Ajia219thzg25abkRE/BpDc3pqvphHvRFys2weqvp+krbWKIX7nhDbzLOItiM8358pTwdirqpPFnMF2xLc1WvLyOwTAibpbmvHHcvttU57y5+XqNZrLe3lE/Pq8eUj2fXKfOe3pfOjzhJYtB/yll5SDFcSDiH+hRkH25+L+sdxKEAMZahrlSX8ukqMOWy/jXW2m6M9LDBc31B9LFuv6gVKg/0Szi3KAr1kGq1GMjU/aLbnq6/lRxc4XfJ98hTargX++DbMJBSiYMIe9Ck1YAxFkKEAG3xbYaKmDDgYyFK0UGYpfoWYXG+fAPPI6tJnNwb7ClP7IyF+D+bjOtCpkhz6CFrIa/I6sFtNl8auFXGMTP34sNwI/JhkgEtmDz14ySfaRcTIBInmKPE32kxyyE2Tv+thKbEVePDfW/byMM1Kmm0XdObS7oGD/MypMXFPXrCwOtoYjyyn7BV29/MZfsVzpLDdRtuIZnbpXzvlf+ev8MvYr/Gqk4H/kV/G3csdazLuyTMPsbFhzd1UabQbjFvDRmcWJxR3zcfHkVw9GfpbJmeev9F08WW8u...
[HTTP] <-- GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/screenshot 200 238 ms - 150442 
[HTTP] --> POST /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/back {}
[MJSONWP] Calling AppiumDriver.back() with args: ["6bf82fba-2b17-42b0-bba5-ed3baa7861b7"]
[XCUITest] Executing command 'back'
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8100/session/8F85EB89-F41D-40A0-B3D2-82F17589CD05/element] with body: {"using":"class name","value":"XCUIElementTypeNavigationBar"}
[JSONWP Proxy] Got response with status 200: {"value":{"ELEMENT":"78CE3690-2DFF-4066-BA17-B392976A40BB","type":"XCUIElementTypeNavigationBar","label":null},"sessionId":"8F85EB89-F41D-40A0-B3D2-82F17589CD05","status":0}
[BaseDriver] Waiting up to 0 ms for condition
[JSONWP Proxy] Proxying [POST /element/78CE3690-2DFF-4066-BA17-B392976A40BB/elements] to [POST http://localhost:8100/session/8F85EB89-F41D-40A0-B3D2-82F17589CD05/element/78CE3690-2DFF-4066-BA17-B392976A40BB/elements] with body: {"using":"class name","value":"XCUIElementTypeButton"}
[JSONWP Proxy] Got response with status 200: {"value":[{"ELEMENT":"F2D56664-DB51-461F-99E4-71E5C9ABBDBD","type":"XCUIElementTypeButton","label":"Clear text"},{"ELEMENT":"A8D66C32-5180-4443-AF8B-28B91EDB03D0","type":"XCUIElementTypeButton","label":"Cancel"},{"ELEMENT":"84C5EC63-0700-44E5-BE21-093986D4DD52","type":"XCUIElementTypeButton","label":"Back"}],"sessionId":"8F85EB89-F41D-40A0-B3D2-82F17589CD05","status":0}
[XCUITest] Found navigation bar 'back' button. Clicking.
[JSONWP Proxy] Proxying [POST /element/84C5EC63-0700-44E5-BE21-093986D4DD52/click] to [POST http://localhost:8100/session/8F85EB89-F41D-40A0-B3D2-82F17589CD05/element/84C5EC63-0700-44E5-BE21-093986D4DD52/click] with body: {}
[JSONWP Proxy] Got response with status 200: {"status":0,"id":"84C5EC63-0700-44E5-BE21-093986D4DD52","value":"","sessionId":"8F85EB89-F41D-40A0-B3D2-82F17589CD05"}
[MJSONWP] Responding to client with driver.back() result: null
[HTTP] <-- POST /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/back 200 1494 ms - 76 
[HTTP] --> GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["6bf82fba-2b17-42b0-bba5-ed3baa7861b7"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/8F85EB89-F41D-40A0-B3D2-82F17589CD05/source] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"\\n\\n  \\n    \\n      \\n        \\n      <\\/XCUIElementTypeOther>\\n      
[MJSONWP] Responding to client with driver.getPageSource() result: "\n  \n    \n      \n        \n      \n      \n        \n      \n      
[HTTP] <-- GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/source 200 90 ms - 17440 
[HTTP] --> GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/screenshot {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["6bf82fba-2b17-42b0-bba5-ed3baa7861b7"]
[XCUITest] Executing command 'getScreenshot'
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAEDWlDQ1BJQ0MgUHJvZmlsZQAAOI2NVV1oHFUUPrtzZyMkzlNsNIV0qD8NJQ2TVjShtLp/3d02bpZJNtoi6GT27s6Yyc44M7v9oU9FUHwx6psUxL+3gCAo9Q/bPrQvlQol2tQgKD60+INQ6Ium65k7M5lpurHeZe58853vnnvuuWfvBei5qliWkRQBFpquLRcy4nOHj4g9K5CEh6AXBqFXUR0rXalMAjZPC3e1W99Dwntf2dXd/p+tt0YdFSBxH2Kz5qgLiI8B8KdVy3YBevqRHz/qWh72Yui3MUDEL3q44WPXw3M+fo1pZuQs4tOIBVVTaoiXEI/MxfhGDPsxsNZfoE1q66ro5aJim3XdoLFw72H+n23BaIXzbcOnz5mfPoTvYVz7KzUl5+FRxEuqkp9G/Ajia219thzg25abkRE/BpDc3pqvphHvRFys2weqvp+krbWKIX7nhDbzLOItiM8358pTwdirqpPFnMF2xLc1WvLyOwTAibpbmvHHcvttU57y5+XqNZrLe3lE/Pq8eUj2fXKfOe3pfOjzhJYtB/yll5SDFcSDiH+hRkH25+L+sdxKEAMZahrlSX8ukqMOWy/jXW2m6M9LDBc31B9LFuv6gVKg/0Szi3KAr1kGq1GMjU/aLbnq6/lRxc4XfJ98hTargX++DbMJBSiYMIe9Ck1YAxFkKEAG3xbYaKmDDgYyFK0UGYpfoWYXG+fAPPI6tJnNwb7ClP7IyF+D+bjOtCpkhz6CFrIa/I6sFtNl8auFXGMTP34sNwI/JhkgEtmDz14ySfaRcTIBInmKPE32kxyyE2Tv+thKbEVePDfW/byMM1Kmm0XdObS7oGD/MypMXFPXrCwOtoYjyyn7BV29/MZfsVzpLDdRtuIZnbpXzvlf+ev8MvYr/Gqk4H/kV/G3csdazLuyTMPsbFhzd1UabQbjFvDRmcWJxR3zcfHkVw9GfpbJmeev9F08WW8u...
[HTTP] <-- GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/screenshot 200 231 ms - 150602 
[HTTP] --> GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/source {}
[MJSONWP] Calling AppiumDriver.getPageSource() with args: ["6bf82fba-2b17-42b0-bba5-ed3baa7861b7"]
[XCUITest] Executing command 'getPageSource'
[JSONWP Proxy] Proxying [GET /source] to [GET http://localhost:8100/session/8F85EB89-F41D-40A0-B3D2-82F17589CD05/source] with no body
[JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"\\n\\n  \\n    \\n      \\n        \\n      <\\/XCUIElementTypeOther>\\n      
[MJSONWP] Responding to client with driver.getPageSource() result: "\n  \n    \n      \n        \n      \n      \n        \n      \n      
[HTTP] <-- GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/source 200 92 ms - 17440 
[HTTP] --> GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/screenshot {}
[MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["6bf82fba-2b17-42b0-bba5-ed3baa7861b7"]
[XCUITest] Executing command 'getScreenshot'
[MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAu4AAAU2CAYAAADK1zMGAAAEDWlDQ1BJQ0MgUHJvZmlsZQAAOI2NVV1oHFUUPrtzZyMkzlNsNIV0qD8NJQ2TVjShtLp/3d02bpZJNtoi6GT27s6Yyc44M7v9oU9FUHwx6psUxL+3gCAo9Q/bPrQvlQol2tQgKD60+INQ6Ium65k7M5lpurHeZe58853vnnvuuWfvBei5qliWkRQBFpquLRcy4nOHj4g9K5CEh6AXBqFXUR0rXalMAjZPC3e1W99Dwntf2dXd/p+tt0YdFSBxH2Kz5qgLiI8B8KdVy3YBevqRHz/qWh72Yui3MUDEL3q44WPXw3M+fo1pZuQs4tOIBVVTaoiXEI/MxfhGDPsxsNZfoE1q66ro5aJim3XdoLFw72H+n23BaIXzbcOnz5mfPoTvYVz7KzUl5+FRxEuqkp9G/Ajia219thzg25abkRE/BpDc3pqvphHvRFys2weqvp+krbWKIX7nhDbzLOItiM8358pTwdirqpPFnMF2xLc1WvLyOwTAibpbmvHHcvttU57y5+XqNZrLe3lE/Pq8eUj2fXKfOe3pfOjzhJYtB/yll5SDFcSDiH+hRkH25+L+sdxKEAMZahrlSX8ukqMOWy/jXW2m6M9LDBc31B9LFuv6gVKg/0Szi3KAr1kGq1GMjU/aLbnq6/lRxc4XfJ98hTargX++DbMJBSiYMIe9Ck1YAxFkKEAG3xbYaKmDDgYyFK0UGYpfoWYXG+fAPPI6tJnNwb7ClP7IyF+D+bjOtCpkhz6CFrIa/I6sFtNl8auFXGMTP34sNwI/JhkgEtmDz14ySfaRcTIBInmKPE32kxyyE2Tv+thKbEVePDfW/byMM1Kmm0XdObS7oGD/MypMXFPXrCwOtoYjyyn7BV29/MZfsVzpLDdRtuIZnbpXzvlf+ev8MvYr/Gqk4H/kV/G3csdazLuyTMPsbFhzd1UabQbjFvDRmcWJxR3zcfHkVw9GfpbJmeev9F08WW8u...
[HTTP] <-- GET /wd/hub/session/6bf82fba-2b17-42b0-bba5-ed3baa7861b7/screenshot 200 202 ms - 150694

**Comment by dpgraham** [comment]
Where in the logs is the problem happening?
