### ISSUE TITLE
Appium 1.6.4 send keys, returns 'Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["value"]} and you sent ["text","sessionId","id","value"]'

### ISSUE THREAD

**Issue by songzcn** [appium/appium#8247]
## The problem
Appium server is  on Mac, and my code is run on win 10.Use remote debug to debug appium script.
When I clear the text field and input text to the text field, appium returns 'Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["value"]} and you sent ["text","sessionId","id","value"]' 

## Environment

* Appium version (or git revision) that exhibits the issue:  1.6.4 
* Node.js version (unless using Appium.app|exe): 7.0.0
* Mobile platform/version under test: 10.2
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/songzcn/81e46e415482a59da4d0063ec816b6e0

**Comment by mykola-mokhnach** [comment]
Do you use python client?

**Comment by songzcn** [comment]
yes, i use Appium-Python-Client (0.24) and run script on robot framework

**Comment by songzcn** [comment]
Maybe the problem is related to selenium. I have upgrade my selenium version to 3.3.3 day before and i see the send_keys method has changed.

**Comment by mykola-mokhnach** [comment]
Then it';s rather a bug in python client and I think it's already reported. Try to downgrade Selenium to workaround it or wait for a fix
