### ISSUE TITLE
Error : Unable to Rotate Device

### ISSUE THREAD

**Issue by muratme** [appium/appium#8248]
## The problem
When the screen orientation is in Portrait mode, and want to execute driver.rotate(ScreenOrientation.PORTRAIT); the driver throws error "Unable to Rotate Device"

When I want to get orientation: There is another problem which returns "Unexpected orientation returned: portraıt" NOT portrait. I think "ı" letter is wrong here.

## Environment

    Appium version (or git revision) that exhibits the issue: Appium 1.6.4
    Desktop OS/version used to run Appium: MACOS 10.12.3 Sierra
    Node version (unless using Appium.app|exe): v6.8.0
    Npm Version : 3.10.8
    Mobile platform/version under test: IOS 10.2
    Real device or emulator/simulator: Iphone6
    java version "1.8.0_40"

**Comment by mykola-mokhnach** [comment]
Please provide full log
