### ISSUE TITLE
appium build xcode WebDriverAgent 

### ISSUE THREAD

**Issue by avrahamShutterFly** [appium/appium#8250]
## The problem

PBXCp Error
error: /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/Resources/WebDriverAgent.bundle: No such file or directory

## Environment

* Appium version 1.6.5-beta
* Last Appium version that did not exhibit the issue (if applicable)
* mac version 10.12.2
* Node.js version v6.10.0
* IOS iPhone version 9.3.2

## Details
I try to build xcode webDriverAgent and I got this error

**Comment by imurchie** [comment]
This is most likely a code signing issue. See https://github.com/appium/appium/blob/master/docs/en/appium-setup/real-devices-ios.md
