### ISSUE TITLE
Android background method fails [uiautomator2][appiumv1.6.4]

### ISSUE THREAD

**Issue by NagyRobertt** [appium/appium#8252]
## The problem

When calling runAppInBackground it does put the application to the background and comes back after the specified time, but after the application reappears appium simply closes the application instead of continuing the test. Added full Appium log gist below.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.6.4
* Last Appium version that did not exhibit the issue (if applicable): 
* Desktop OS/version used to run Appium: Mac OS 10.12.1
* Node.js version (unless using Appium.app|exe): 6.9.1
* Mobile platform/version under test: Android 6.0.1
* Real device or emulator/simulator: real device
* Appium CLI or Appium.app|exe: CLI

## Link to Appium logs

https://gist.github.com/NagyRobertt/6f6e3be5595879a2a9378e3ce96c31f5

**Comment by mykola-mokhnach** [comment]
thanks for the bugreport. The [fix](https://github.com/appium/appium-android-driver/pull/226) will be merged soon to 1.6.5-beta

**Comment by mykola-mokhnach** [comment]
The fix has been published. Closing the issue as fixed
