### ISSUE TITLE
Python Selenium client incompatible with Appium server 1.6.4.

### ISSUE THREAD

**Issue by imurchie** [appium/appium#8253]
## The problem

Recent updates to the Selenium Python client have updated parameters, etc. at least in the case of `send_keys` (though I would be surprised if it were that simple). This breaks when used against Appium and its old version of the JSON Wire Protocol.

We need to either lock the compatible version of the Se client within the Python client to a known-good, and/or update our JSON WP.

W3C Spec: https://www.w3.org/TR/webdriver/

**Comment by jlipps** [comment]
I think we should update our mjsonwp implementation to receive either parameter and pass it on to drivers. should be just a basedriver change in that case.

**Comment by imurchie** [comment]
Sounds like a reasonable solution.

**Comment by mykola-mokhnach** [comment]
Added PR https://github.com/appium/appium-base-driver/pull/120

**Comment by LucaVazz** [comment]
I'm assuming this is fixed by PR https://github.com/appium/appium-base-driver/pull/121 right?

Is there an ETA for a release including this PR?

**Comment by dpgraham** [comment]
@jlipps @mykola-mokhnach Did the PR's fix this issue or should I leave this open?

**Comment by mykola-mokhnach** [comment]
@dpgraham yes, this should be fixed

**Comment by LucaVazz** [comment]
Great news!

But @mykola-mokhnach, when can we expect v 1.6.6, which would include those PRs, to ship?

**Comment by dpgraham** [comment]
@LucaVazz 1.6 beta is out now. The full release should be in the very near future.
