### ISSUE TITLE
App is constantly crashing on start up with Appium desktop 1.0.0

### ISSUE THREAD

**Issue by Katipalli** [appium/appium#8255]
## The problem

I am trying start a new session on iPhone simulator, it seems like installed an app, but keeps on crashing with below error logs:

[JSONWP Proxy] Got response with status 200: {"value":"Failed to launch com.usbank.tmup.mobile.SinglePoint application","sessionId":"753D08B2-23C1-4152-A20E-B5DBBEAC497F","status":13}
[XCUITest] Failed to create WDA session. Retrying...
[BaseDriver] Event 'wdaSessionAttempted' logged at 1492107494876 (14:18:14 GMT-0400 (EDT))
[XCUITest] Sending createSession command to WDA
[JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.usbank.tmup.mobile.SinglePoint","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}

## Environment

* MAC 10.11
* Appium Desktop 1.0.0
* Xcode 8.2
* Mobile platform/version under test: iOS 10.2
* Real device or emulator/simulator: Simulator

Please help me to resolve the issue
Thank you

**Comment by mwalla210** [comment]
Also experiencing this issue, despite following all instructions [here](http://appium.io/slate/en/master/?ruby#system-setup-ios).

**Comment by dpgraham** [comment]
If the app is crashing then I would say it's an Appium issue and not an Appium Desktop issue.

**Comment by mwalla210** [comment]
My Appium logs match those above, with the "failed to create WDA session", except using my own app.

**Comment by imurchie** [comment]
Can you turn on device logging and xcode logging (both the `showIOSLog` and `showXcodeLog` caps set to `true`) and post a link to a [gist](https://gist.github.com) of the _entire_ server logs?

**Comment by mwalla210** [comment]
Gist [here](https://gist.github.com/mwalla210/16951e23f3852defe483d583c6e35938)
I stopped the session after some repetitive processes occurred.

**Comment by AmitVerma4HP** [comment]
I have similar problem in 3 of my windows machine where I am running Appium 1.0.0 desktop version to run automated tests on real android devices. Appium is running on 2 dev machines and 1 Jenkins machine. I see Appium crashing consistently when appium is ON and kept idle for long hrs. Let me know what details you need in order to debug/fix this problem.

**Comment by dpgraham** [comment]
@AmitVerma4HP Is the UI crashing or is the appium server crashing?

**Comment by AmitVerma4HP** [comment]
UI is crashing so scheduled automated tests in late hours would not run.

**Comment by dpgraham** [comment]
@AmitVerma4HP We can look into that. We've seen other similar problems, I think it's some sort of memory leak. I would recommend for automated tests you should be using the command line server

```
npm install -g appium
appium
```

**Comment by AmitVerma4HP** [comment]
@dpgraham , yes , I have moved back to npm appium after getting into this.
Please let me know whenever you feel that this problem is resolved, would love to use GUI version.

**Comment by dpgraham** [comment]
Sure thing. Just a tip, if you wanted to use the GUI and the server concurrently you can follow these directions: https://github.com/appium/appium-desktop/issues/116

**Comment by jlipps** [comment]
@mwalla210 you can't run an .ipa on a simulator, which is what you're trying to do. For a sim you need a .app built for the sim. If you want to run on a real device, you must include the `udid` capability.
