### ISSUE TITLE
The second switch to textview, kill webdriver process error

### ISSUE THREAD

**Issue by swmvp** [appium/appium#8257]
## The problem

I need to test the mixed application, need to switch the context many times, but I found that the second time I switch to webview, the following error.（See the log）

## Environment

* Appium 1.6.4
* windows 10
* Node.js v6.3.0,npm v3.10.3
* Real device：Samsung SM-9208 ,Android 6.0.1
* Appium CLI 

## Details

I think the reason for the problem is that the second times create a chromedriver（port 8001）, did not kill the first created chromedriver（port 8000）

Description of my system chrome version is too low, so I reduced the chromedriver version（chromedriver 2.26）

Refer to the first comment of https://gist.github.com/swmvp/f84cd4a4693186209d209698103f9dad

## Link to Appium logs

https://gist.github.com/swmvp/f84cd4a4693186209d209698103f9dad

**Comment by abhilashcae** [comment]
I'm also facing the same issue.

**Comment by HemantTrivedi** [comment]
I am also facing same but for iOS

**Comment by dpgraham** [comment]
We should test this out to see if this is reproducible.

**Comment by mykola-mokhnach** [comment]
Is the problem still reproducible in the most recent Appium release?
