### ISSUE TITLE
Can't execute async script on Android >= 6.0

### ISSUE THREAD

**Issue by alsorokin** [appium/appium#8259]
## The problem

Cannot execute async javaScript in a webview of a hybrid app on Android 6.0 and 7.0
Android 4.4 and 5.1 are OK.

## Environment

* Appium version (or git revision) that exhibits the issue: 1.5.3, 1.6.3, 1.6.4 (with chromedriver downgraded to 2.20, so it would work with Android 6.0)
* Last Appium version that did not exhibit the issue (if applicable): haven't tried any version lower than 1.5.3
* Desktop OS/version used to run Appium: Windows 10
* Node.js version (unless using Appium.app|exe): 4.5.0
* Mobile platform/version under test: Android 6.0, Android 7.0
* Real device or emulator/simulator: emulator
* Appium CLI or Appium.app|exe: CLI

## Details

I am testing a hybrid app created using Apache Cordova locally and on Sauce Labs emulators.
Until recently, I was only testing on 4.4 and 5.1 Android versions. About two weeks ago, Sauce Labs introduced new Android emulators: 6.0 and 7.0. While still passing on the old ones, my tests fail on the new ones on `executeAsync` step with the following error message:
```
UnknownError - An unknown server-side error occurred while processing the command. Selenium error: unknown error: Maximum call stack size exceeded
```
I've tried running it on Appium 1.5.3, 1.6.3, 1.6.4, both locally and on Sauce Labs.

## Link to Appium logs

https://gist.github.com/alsorokin/2e13b6af77168125b22fb7eb59955870#file-appiumserver-log-L240

## Code To Reproduce Issue [ Good To Have ]
I haven't been able to reproduce the issue using your samples (`executeAsync` with the function calling `setTimeout` with the callback would just hang forever). Maybe I'm doing something wrong here.

Anyways, here's the bit of my code that fails:
```
return driver
    .setAsyncScriptTimeout(60000)
    .executeAsync(function (cb) {
        document.addEventListener('deviceready', cb, false);
    }, []);
```

*UPD*: I've uploaded an apk with my test app:
https://yadi.sk/d/I-VWbTzk3Gy59g

**Comment by alsorokin** [comment]
At first I was thinking that cordova has something to do with it, but this also fails with the same message:
```
return driver
    .setAsyncScriptTimeout(ASYNC_SCRIPT_TIMEOUT)
    .executeAsync(function (cb) {
        var event = new Event('atata');
        document.addEventListener('atata', cb, false);
        setTimeout(function() {
            document.dispatchEvent(event);
        }, 2000);
    }, []);
```

**Comment by alsorokin** [comment]
My suspicion is that chromedriver@2.20 may be the cause. Unfortunately, newer versions doesn't work with 6.0 and 7.0 Android emulators causing this error: https://github.com/appium/appium/issues/7138

**Comment by mykola-mokhnach** [comment]
habe you tried to update the system webview on the emulator (http://stackoverflow.com/questions/30785197/update-android-system-webview-on-sdk-emulator)?

**Comment by imurchie** [comment]
I played around a little bit and found that putting the Selenium callback into an anonymous function worked for me on 6.0:
```js
      driver
        .contexts().then(function (ctxs) {
          ctxs.should.contain("WEBVIEW_io.cordova.hellocordova");
          return driver.context("WEBVIEW_io.cordova.hellocordova");
        })
        .setAsyncScriptTimeout(60000)
        .executeAsync("return (function (cb) {\r\n            document.addEventListener('deviceready', function () {cb('hi');}, false);\r\n        }).apply(null, arguments);")
        .then(function (args) {
          console.log('ARGS:', args);
        })
        .nodeify(done);
```

**Comment by alsorokin** [comment]
@mykola-mokhnach The answer on your link says that webview is updated via Play Store, which is not present on the emulators.
What exactly are you suggesting? To build WebView AOSP myself? I don't have a "beefy Linux machine" to do so.

**Comment by alsorokin** [comment]
@imurchie hey, thanks for checking it out! Which chromedriver version were you using?

**Comment by imurchie** [comment]
2.20.

**Comment by alsorokin** [comment]
Thanks, I'll give it a shot at Monday

**Comment by mykola-mokhnach** [comment]
Why PlayStore only? it's also possible to download and install pure [apk](http://www.apkmirror.com/apk/google-inc/android-system-webview/)

**Comment by alsorokin** [comment]
@imurchie works like a charm, thank you!
@mykola-mokhnach thanks for the suggestions! I am running my tests on Sauce Labs though, and as far as I know, they don't have this SDK available.

**Comment by imurchie** [comment]
Excellent!
