### ISSUE TITLE
Failed to Dump Window Hierarchy

### ISSUE THREAD

**Issue by desided** [appium/appium#8262]
## The problem

Hi all,
I am Getting Error "Failed to Dump Window Hierarchy","status":13", ubuntu+genymotion

## Environment

* Appium version (or git revision) that exhibits the issue:1.6.4
* Last Appium version that did not exhibit the issue (if applicable):
* Desktop OS/version used to run Appium:ubuntu
* Node.js version (unless using Appium.app|exe):4.2.6
* Mobile platform/version under test:genymotion android 5.0
* Real device or emulator/simulator:emulator
* Appium CLI or Appium.app|exe:

## Details

at also not working when try to screen page from uiautomator 

## Link to Appium logs
`Responding to client with driver.click() result: true
[HTTP] <-- POST /wd/hub/session/8a9fe811-4616-4479-8861-c6997f1f76d6/element/6/click 200 283 ms - 76
[HTTP] --> POST /wd/hub/session/8a9fe811-4616-4479-8861-c6997f1f76d6/elements {"using":"xpath","value":"//android.widget.TextView[contains(@resource-id, 'jp.naver.line.android:id/comment_text_btn')]"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["xpath","//android.widget.TextView[contains(@resource-id, 'jp.naver.line.android:id/comment_text_btn')]","8a9fe811-4616-4479-8861-c6997f1f76d6"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.TextView[contains(@resource-id, 'jp.naver.line.android:id/comment_text_btn')]","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//android.widget.TextView[contains(@resource-id, 'jp.naver.line.android:id/comment_text_btn')]","context":"","multiple":true}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//android.widget.TextView[contains(@resource-id, 'jp.naver.line.android:id/comment_text_btn')]' using 'XPATH' with the contextId: '' multiple: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Command returned error:java.lang.RuntimeException: Failed to Dump Window Hierarchy
[debug] [AndroidBootstrap] Received command result from bootstrap
[HTTP] <-- POST /wd/hub/session/8a9fe811-4616-4479-8861-c6997f1f76d6/elements 500 350 ms - 154
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":13,"value":"Failed to Dump Window Hierarchy"}
acces`

it failed when on screen is emoji or italian text

**Comment by mykola-mokhnach** [comment]
Please provide full log and also the device log received from **adb logcat**.
