### ISSUE TITLE
Bad parameters: BadParametersError:..wanted {“required”:[“desiredCapabilities”],“optional”: [“requiredCapabilities”,“sessionId”,“id”]}

### ISSUE THREAD

**Issue by AlexLuya** [appium/appium#8263]
## The problem

Just as issue title

## Environment

Windows 10 64bit
appium 1.6.4
appium java-client-5.0.0-BETA7
android 5.1   
Real device 

Error messages:

```
 [debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were
 incorrect. We wanted {"required":["desiredCapabilities"],"optional":
 ["requiredCapabilities","sessionId","id"]} and you sent 
 ["capabilities","desiredCapabilities","requiredCapabilities"]
```
I checked the error message:

```
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were 
incorrect. We wanted {"required":["desiredCapabilities"],"optional":
["requiredCapabilities","sessionId","id"]} and you sent 
["capabilities","desiredCapabilities","requiredCapabilities"]
```
it seems that the sent parameter format

` {"required":["desiredCapabilities"],"optional":["requiredCapabilities","sessionId","id"]}`
mismatched with wanted format,just like a version mismatching issue:

`["capabilities","desiredCapabilities","requiredCapabilities"]`
But same configuration (appium,java-client,android),and test code works in ubuntu 16.04 64bit,

**Comment by dpgraham** [comment]
We submitted a fix for this. It will be in version 1.6.5

`capabilities` is a recent addition to the WebDriver standard. Are you able to use an older version of the Java Client until then? Looks like you're using a beta client.

**Comment by shabana-parveen** [comment]
I am also facing the same, issue. Now I downgrade the appium version, still getting same error.
Shabana:~ f2849$ appium
[Appium] Welcome to Appium v1.5.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"app":"/Users/XX/Desktop/XXX/XXX-dev-debug.apk","sendKeyStrategy":"setValue","no-reset":"true","platformVersion":"6.0","full-reset":"False","javascriptEnabled":true,"deviceOrientation":"portrait","platformName":"Android","deviceName":"192.168.57.101:5555  ","launchTimeout":90000},"requiredCapabilities":{},"capabilities":{"desiredCapabilities":{"app":"/Users/f2849/Desktop/shine_sumosc_mostUpdatedBuild/shine-dev-debug.apk","sendKeyStrategy":"setValue","no-reset":"true","platformVersion":"6.0","full-reset":"False","javascriptEnabled":true,"deviceOrientation":"portrait","platformName":"Android","deviceName":"192.168.57.101:5555  ","launchTimeout":90000},"requiredCapabilities":{},"alwaysMatch":{"platformName":"Android"},"firstMatch":[]}}
[debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["desiredCapabilities"],"optional":["requiredCapabilities","sessionId","id"]} and you sent ["desiredCapabilities","requiredCapabilities","capabilities"]
[HTTP] <-- POST /wd/hub/session 400 7 ms - 201

**Comment by dpgraham** [comment]
@shabana-parveen The fix (https://github.com/appium/appium-base-driver/pull/117) hasn't made it's way to a release yet. It will be in a future Appium release.

**Comment by imurchie** [comment]
Should be available in the latest 1.6.5 beta (`npm uninstall -g appium && npm install -g appium@beta`).

**Comment by shabana-parveen** [comment]
I'll try with 1.6.5 beta version, but wanted to know why I am unable to run my automation suite with stable appium version 1.5.1? 

PS: I don't want to run my automation suite with the beta version, please confirm, When can I expect the release?

Thanks,
kind regards
Shabana Parveen

**Comment by imurchie** [comment]
Appium 1.5.1 was released 13 months ago. A lot has changed since then. In terms of this particular issue, the source was not even contemplated at that time. The change to the Selenium spec was recent and the update to the underlying client even more recent.

The solution in the short term is to downgrade the Java client.

**Comment by guodong-xia** [comment]
thanks！！！
